### ISSUE TITLE
[bug] Exporting module - zip issue

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10004]
The exported standard module zip file is wrecked (need to change zip to rar, unpack, zip again once done above, import got the problem with blocks.
the imported module in this way don't refresh specific to module relations

Exported attached
[OSSEmployees.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/2998787/OSSEmployees.zip)

The code I use:

**Comment by waran70** [comment]
`<?php
require __DIR__ . '/include/main/WebUI.php';
$moduleName = 'OSSEmployees';
$moduleModel = \vtlib\Module::getInstance($moduleName);
$package = new vtlib\PackageExport();
$package->export($moduleModel, '', sprintf('%s-%s.zip', $moduleModel->name, $moduleModel->version), true);
`

**Comment by konadrian** [comment]
It works perfectly in current dev version
![ImportModule](https://user-images.githubusercontent.com/3193498/75538328-b4f6a780-5a18-11ea-8160-698bf0e58a76.gif)
