### ISSUE TITLE
[bug] PDF tables without borders

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10003]
PDF generator don't add properties for styling cells such as "border-style: and border-width:" just border-color. This won't get me customized effect here

**Comment by neuronetio** [comment]
could you use shorthand `border:1px solid red` for this?

**Comment by rafalpospiech** [comment]
closed due to inactivity

**Comment by rafalpospiech** [comment]
@waran70 `border:1px solid red` ?

**Comment by waran70** [comment]
This should work from CKEditor without the need to go to the source code. You can set cell border color, but it invisible even table border size is set to 1. There must be blocker somewhere in CK settings. 
Actually, CK options are set to be pretty poor. It quite PITA when designing lots of reports.

**Comment by rafalpospiech** [comment]
https://ckeditor.com/cke4/addon/table
CKEditor doesn't support settings like you need.

**Comment by rafalpospiech** [comment]
We need to adopt color dialog plugin https://ckeditor.com/cke4/addon/colordialog
@bpabiszczak ? @mariuszkrzaczkowski ?

**Comment by bpabiszczak** [comment]
Low priority.

**Comment by JohnMaverick** [comment]
bpabiszczak reporting tool is a low priority issue in CRM/ERP?

**Comment by bpabiszczak** [comment]
@JohnMaverick this topic applies to PDF.

**Comment by JohnMaverick** [comment]
Blazej, you are right, but there is no reporting tool except PDF generator. The only way (at the moment) to get the report out of the screen.
