### ISSUE TITLE
[Question]  opcache.interned_strings_buffer = 100 > crm down

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10006]
When I set opcache.interned_strings_buffer to 100 it kneeling YF. Why? Maybe value is set too high for generic servers? 50 works OK

**Comment by mariuszkrzaczkowski** [comment]
what is the value for the parameter opcache.memory_consumption

**Comment by elvissaba** [comment]
Just set opcache.memory_consumption=512 (default is 128 in your .ini) if you want to use opcache.interned_strings_buffer =100. I don't know what value is recommended for Yetiforce, but 512 works for me.
