### ISSUE TITLE
[Question]  Cancel stock moving - cancel IGDN

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#10000]
> Hi there ,
> 
>     I want to cancel an IGDN (a stock movement). For example, i have created an IGDN for product A, and my colleague comes in 10 minutes, without knowing that i have already made that and, makes it again. How can i cancel it so i have only -1 product A not -2 ? 
>    If i delete an IGDN entry, stock remains -2.

**Comment by vovpff** [comment]
What you mean? At first you need to cancel IGDN.

**Comment by liviubbo** [comment]
Hy there ,

   If i create a Goods Dispatched Note for a product, on the Inventory it will register it in inventory, right ? 
  So, after i created it, how can i cancel it if i want to do that?
  I want it because it happens that both me, and my colleague make the same Dispatched note for the same product, so, inventory is not settlet.
  I can make it only with Goods Dispatched Notes Correction?

**Comment by vovpff** [comment]
IGDN affect to inventory only with status `Accepted` If you made a lot of IGDNs with status `Draft` you can cancel them without any problems. If you need to cancel Accepted IGDN you need to modify hardcoded record locking code here

https://github.com/YetiForceCompany/YetiForceCRM/blob/dd58ad2e21eb347b3076a7da895cdac40bf37a87/modules/IGDN/IGDN.php#L15

But this is not so safe action. Trust me.

**Comment by liviubbo** [comment]
Ah, ok ! Thank you very much !

**Comment by vovpff** [comment]
@liviubbo keep in mind what this is very dangerous!
