### ISSUE TITLE
[Question] WorkFlow Logs

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10014]
Where in config can i enable saving errors of Workflow? Because i have problem with one and must look for erorros. In /cache/logs there is no errors from Workflow.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/user-documentation/item/debugowanie

Możesz też włączyć logi PHP w CLI [bo cron działa w CLI]
