### ISSUE TITLE
[Question] Renaming of "Companies and Contacts". 

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#10015]
### Description

Is it an idea to rename the **Companies and contacts** into **Relationships** in the CRM Menu? As an overall change to the CRM, I mean. (I know that I can do that for myself in the Language Management, which I did also.)

It will look nicer in the Menu and with the meaning of the name you are covering all modules that are placed under that label.

**Two applicable meanings of the word "Relationship" as per the dictionary:**
* The way in which two or more people or things are connected, or the state of being connected.
* The way in which two or more people or groups regard and behave towards each other.

**Comment by waran70** [comment]
"Accounts" (corporate account, personal account, employee account, vendor account etc.)
The "Relationship" might be confusing for IT guys... :)

**Comment by alagmouch** [comment]
I was thinking of that too, initially, but Leads is part of the list too.

"Companies and contacts" is not it, I believe. Accounts might be good, but Leads have to be moved under Marketing then.

**Comment by waran70** [comment]
Leads to Marketing should be moved. Under account only those entities and contacts who are in the deals circle. Deal starts from quotation onward

**Comment by bpabiszczak** [comment]
You can change this in the menu configuration.

**Comment by alagmouch** [comment]
Yes I know. I mentioned this also in the first text. It was a suggestion, as an overall change to the CRM. Instead of the 3 words of "Accounts and companies".
