### ISSUE TITLE
How install Yeti 5.1 on openserver?

### ISSUE THREAD

**Issue by Oplement** [YetiForceCompany/YetiForceCRM#10018]
Hello, need to install yeti on openserver to edit the code, what settings are needed for this? The default settings give an error:
Fatal error: Uncaught Error: Class 'App \ Exceptions \ AppException' not found in W: \ domains \ Yeti \ include \ RequirementsValidation.php: 9 Stack trace: # 0 W: \ domains \ Yeti \ index.php (13): require () # 1 {main} thrown in W: \ domains \ Yeti \ include \ RequirementsValidation.php on line 9

**Comment by TomaszQr** [comment]
You have wrong PHP version, We recommended version >= 7.1

**Comment by Oplement** [comment]
> You have wrong PHP version, We recommended version >= 7.1

Where can I see all the required versions of the components?

**Comment by TomaszQr** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/wymagania-dla-serwera-www

**Comment by adudekyeti** [comment]
In English you can find it here:
[https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements)

**Comment by Oplement** [comment]
Thanks, all works
