### ISSUE TITLE
[Feature]    WYSIWG Field - allow selecting from local resources

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10016]
got need to select an image and embed it in WYSIWG Field while editing record. The system allows only for links to remote resources. How to fix it?

**Comment by JohnMaverick** [comment]
Tried to replace CK (custom build) in both locations:
public_html/vendor/ckeditor/ckeditor
and
/var/www/html/crm1/vendor/ckeditor

Nothing working. Can you guys advise where and how to change CKEditor settings?

**Comment by adudekyeti** [comment]
@JohnMaverick you can find it there, but you need to know, it works globally:
https://github.com/YetiForceCompany/YetiForceCRM/blob/056b1b876300dc8de37d7c6ba1d4a3dddcc4850a/public_html/layouts/resources/Fields.js#L379

**Comment by garryatbrighton** [comment]
> @JohnMaverick you can find it there, but you need to know, it works globally:
> 
> https://github.com/YetiForceCompany/YetiForceCRM/blob/056b1b876300dc8de37d7c6ba1d4a3dddcc4850a/public_html/layouts/resources/Fields.js#L379

in 6.4 it must be somewhere else as Fields.js seems to be truncated a lot
