### ISSUE TITLE
Feature:ADD the ability to DELETE related modules

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1002]
ADD the ability to DELETE related modules from the setting 
Arrange related modules
because sometimes some relations crashes the whole related module

![related](https://cloud.githubusercontent.com/assets/6897502/7943815/b950a320-096f-11e5-8467-c31c7af792a7.jpg)

**Comment by nikdejan** [comment]
+1

**Comment by rskrzypczak** [comment]
Added a new parameter in developer's configuration that allows for adding/deleting relations between modules.
