### ISSUE TITLE
[Question]  Product inventory history

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#10039]
Hy all ! 

   I dont have any product history. If i click a product and check goods dispatched notes tab, i get nothing. I changed the relation tab many times with different options but no luck. 
   I want to see what changes i had in the inventory for that specific product. 
   I attached a gif. For that product were 2 Good Dispatched Notes but, are not appearing there. 

![products-history](https://user-images.githubusercontent.com/42461923/55138054-d1b49c00-5132-11e9-9817-8c618cb61afc.gif)

**Comment by vovpff** [comment]
This is because standard relations not works with line items. You need some programming to establish new type of relation.

**Comment by liviubbo** [comment]
Oh, i understand. Too bad :) I needed that history.

**Comment by liviubbo** [comment]
Thanks for you answer.

**Comment by vovpff** [comment]
@liviubbo 
![image](https://user-images.githubusercontent.com/8545791/55144128-3383fe80-5151-11e9-8b0a-72740bf68e03.png)

This is simple

**Comment by liviubbo** [comment]
Well, but i dont know were to start ! :)

**Comment by liviubbo** [comment]
@vovpff - Can you just give me a hint ? :) I will try and make it

**Comment by vovpff** [comment]
@liviubbo contact me by email
