### ISSUE TITLE
[Question]           

### ISSUE THREAD

**Issue by shawnbure** [YetiForceCompany/YetiForceCRM#10037]
I have created a custom function, and tested the logic (works) contained in the function. I created it with this:

include_once 'include/main/WebUI.php';
require 'modules/com_vtiger_workflow/VTEntityMethodManager.php';
$emm = new VTEntityMethodManager(PearDatabase::getInstance()); 
$emm->addEntityMethod("Leads", "Send_Text", "modules/Leads/workflows/webhook.php", "send_text"); 

and here is the webhook.php 

<?php 

function send_text($entity){ 
    /* 
    $contact_no = $entity->data[contact_no]; 
    $entityarray = get_object_vars($entity); 
    echo '<pre>'; print_r($entityarray); 
    echo '</pre>'; 
    */ 

    $ch = curl_init();
    $fields = array( 'first_name'=>'shawn', 'to_number'=>'xxxxxxxxxxxxxxxxx', 'from_number'=>'xxxxxxxxxxxxxxxxx', 'key'=>'xxxxxxxxxxxxxxxxx', 'text_message'=>'hello world');
    $postvars = '';
    foreach($fields as $key=>$value) {
    	$postvars .= $key . "=" . $value . "&";
    }
    $url = "https://xxxxxxxxxxxxxxxxx/sms";
    curl_setopt($ch,CURLOPT_URL,$url);
    curl_setopt($ch,CURLOPT_POST, 1); //0 for a get request
    curl_setopt($ch,CURLOPT_POSTFIELDS,$postvars);
    curl_setopt($ch,CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch,CURLOPT_CONNECTTIMEOUT ,3);
    curl_setopt($ch,CURLOPT_TIMEOUT, 20);
    $response = curl_exec($ch);
    
    curl_close ($ch);
} 
    
?> 

The curl function executes in a separate php page fine and the function is in the database properly.

On invocation this is in the logs:

PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'send_text' not found in /var/www/yetiforce/modules/com_vtiger_workflow/VTEntityMethodManager.php on line 47

I can't figure this out?

**Comment by mlorencik** [comment]
check how such files are built on the basis of eg modules HelpDesk/workflows/HelpDeskWorkflow.php, especially for the file name, class and method. Then correct the entry in the database it should be something like:
$emm->addEntityMethod ("Leads", "sendText", "modules / Leads / workflows / SendText.php", "SendText");
in other words module, method name, path, class name

**Comment by shawnbure** [comment]
I looked at these in detail - and I have changed them numerous times. Just confusing. Maybe pictures are worth more :)
![database](https://user-images.githubusercontent.com/4427703/55162571-5a2c4000-5125-11e9-919f-b45afed2ac00.png)
![error](https://user-images.githubusercontent.com/4427703/55162572-5a2c4000-5125-11e9-9d53-a6d324bcd452.png)
![file](https://user-images.githubusercontent.com/4427703/55162573-5ac4d680-5125-11e9-8d9c-ab97e7f9ebd2.png)
![function](https://user-images.githubusercontent.com/4427703/55162574-5ac4d680-5125-11e9-9c58-ec4b81de0336.png)

**Comment by shawnbure** [comment]
Oh I do keep deleting the database entry, workflow, etc. and re-add this when I change the names with the following code:

include_once 'include/main/WebUI.php';
require 'modules/com_vtiger_workflow/VTEntityMethodManager.php';
$emm = new VTEntityMethodManager(PearDatabase::getInstance()); 
$emm->addEntityMethod("Leads", "SendText", "modules/Leads/workflows/TestWebhook.php", "sendText");

**Comment by shawnbure** [comment]
Out of following exactly - I renamed the file  "modules/Leads/workflows/SendText.php" - I did notice that you illustrated the addEntityMethod pathname with spaces - does that matter? I am still getting errors.

**Comment by shawnbure** [comment]
AHHHH EUREKA!!!

So I will document my path to success for future generations of hackers :)

Issues I would like confirmed:

- The php file must include a class - not just a function. 

php file start

class LeadsWorkflow
{
	public static function sendText($entity){ 

    	$ch = curl_init();
    	$fields = array('to_number'=>'4805551212', 'from_number'=>'4805551313','text_message'=>'test worked');
    	$postvars = '';
    	foreach($fields as $key=>$value) {
    	    $postvars .= $key . "=" . $value . "&";
    	}
    	$url = "https://url_to_twilio_function_or_api";
    	curl_setopt($ch,CURLOPT_URL,$url);
    	curl_setopt($ch,CURLOPT_POST, 1); //0 for a get request
    	curl_setopt($ch,CURLOPT_POSTFIELDS,$postvars);
    	curl_setopt($ch,CURLOPT_RETURNTRANSFER, true);
    	curl_setopt($ch,CURLOPT_CONNECTTIMEOUT ,3);
    	curl_setopt($ch,CURLOPT_TIMEOUT, 20);
    	$response = curl_exec($ch);
    	curl_close ($ch);
	} 
}
php file end 

- the php file should exist in /var/www/yetiforce/modules/Leads/workflows/LeadsWorkflow.php and be named the same as the class (this was just an observation). Even if that is irrelevant, the system workflows follow this nomenclature and I followed suit with naming convention and location. Most items online say create a file /modules/workflow - but I wanted to keep it standard.

- yeticrm hides the system files by only exposing the www files in a public_html folder. Makes it tough to execute a php file with relative referenced includes (that exist in the yetiforce folder). My solution was simply to use the cli - php addWorkFlowToDatabase.php

- that file in it's final form looks like this:

include_once 'include/main/WebUI.php';
require 'modules/com_vtiger_workflow/VTEntityMethodManager.php';
$emm = new VTEntityMethodManager(PearDatabase::getInstance());
$emm->addEntityMethod("Leads", "sendText", "modules/Leads/workflows/LeadsWorkflow.php", "SendText"); 

- notice in the above line that the sendText class function name - this the name of the class.function of the php workflow file - it is written all over online interpreted as "This is what shows up in the dropdown". In fact it maps to the database table com_vtiger_workflowtasks_entitymethod and field method_name. This is the method being called inside the class. I don't know if this was misdocumented or misinterpreted - but it seems to need to be switched

- "SendText" is the item displayed in the drop down AND is the class name in the file. I don't know if I just renamed the heck out of everything and this is a coincidence but this seemed to be the key that unlocked my success. It maps to the database table com_vtiger_workflowtasks_entitymethod and field function_name.

Last I found this all over:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$emm->addentitymethod("modulename", "mymethodname", "modules/workflow/outbound_webhook.php", "Outbound Webhook"); 

modulename - valid module names are: contacts, purchaseorder, ???more???  
mymethodname - this is the name that will appear in the drop down list for you to choose from. 
modules/workflow/myexample.inc - the path and filename that contains the method function.
mymethodfunctionname - the name of the method function declared in myexample.inc

if the modules/workflow/ directory does not exist, then just create it!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I think the above code block is applicable to vtiger, and not yeti, or - it is just outdated everywhere I found. I think the correct definitions should be:

$emm->addentitymethod("modulename", "functionname", "path", "classname"); 

modulename - valid module names are: Leads, Contacts, HelpDesk, etc. maps to com_vtiger_workflowtasks_entitymethod.method_name

functionname - this is the function name inside your class. maps to com_vtiger_workflowtasks_entitymethod.method_name

path - the path and filename that contains the class and method function. maps to com_vtiger_workflowtasks_entitymethod.path

classname - the name of the class that the function declared in the php file and this is the name that will appear in the drop down list for you to choose from. maps to com_vtiger_workflowtasks_entitymethod.function_name 


If the moderator can contribute some clarity - I can rewrite this into a better tutorial.

**Comment by shawnbure** [comment]
Correction - After refreshes and using the system for a few hours - it seems functionname DOES map to the dropdown selection in the workflow editor and NOT classname.
