### ISSUE TITLE
[bug] <br> ignored - PDF

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10036]
My code looks like:
--------------------
SINGLE TRIP REPORT

EVENT NAME: $(record : title)$
START DATE: $(record : date_start)$
BOAT ENGAGED: $(record : type)$

LIST OF ATTENDEES AND RELATED DETAILS:
----------------------

But printed PDF looks like:
----------------------------
SINGLE TRIP REPORT EVENT NAME: test START DATE: 22-03-2019 BOAT ENGAGED: Boat 1 LIST OF ATTENDEES AND RELATED DETAILS:
---------------------------

What happened to PDF templater?

**Comment by mlorencik** [comment]
check the source code of the template if you have <br>, I checked several types of writing (separate / one lines from <br> / <br />), as the editor itself encodes and in every case the generated PDF was correct. Maybe you have some css styles over?
