### ISSUE TITLE
Auto update date field 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10038]
### Description

In workflow >> action  >> Update fields >>   Expression >> Function 

add_days(datefield, noofdays) by using these formula can add days but my requirement is add months .i did not find any add months function . is this expression functions support to add months or not?

**Comment by vovpff** [comment]
you have two ways:
Program new function for add mouns or add 30*n days where n number of mounts

**Comment by guide5232** [comment]
i have given 30*n  that time i got wrong output 
Again i have given n*30.43 but no use i got wrong output because some months contain 30 or 31 and 27 

Months =6 
![SubLead Test contract term field2](https://user-images.githubusercontent.com/47585969/55145115-3ead4d80-5196-11e9-97f1-f26746928090.png)

Months =12 
![SubLead Test contract term field1](https://user-images.githubusercontent.com/47585969/55145112-3e14b700-5196-11e9-8abc-056c57c5c963.png)
Months =18

![SubLead Test contract term field](https://user-images.githubusercontent.com/47585969/55145111-3e14b700-5196-11e9-9046-ef90980ab14f.png)

**Comment by vovpff** [comment]
In your case you need to program new function for add mounts.
30*n work only for approximate date.

**Comment by vovpff** [comment]
You found solution?

**Comment by guide5232** [comment]
No But my programmer will do that work
