### ISSUE TITLE
Email template only populating email subject

### ISSUE THREAD

**Issue by gittygit2** [YetiForceCompany/YetiForceCRM#10035]
Hi,

I created a test email template under the "Email Templates" module. I see the template showing up in the dropdown in when I compose a new email in Roundcube. When I click on the template, the only field that is populated is the email subject. The email message does not populate with the "email content" from the email template. The email message remains blank.

What might be causing this issue?

Thank you.

**Comment by adudekyeti** [comment]
Hi,
What version do you use? Could you record screen with open debug console while reproducing the bug?

**Comment by gittygit2** [comment]
Hello,

Ver 5.1.0

https://youtu.be/tEw8IAvawLA
I recorded me trying to add the email template while I opened the Chrome console log. Please let me know what other method of debug console I can send for you.

Thank you.

**Comment by adudekyeti** [comment]
Hi, we fixed this problem:
https://github.com/YetiForceCompany/lib_roundcube/pull/29

Duplicate: #9616
