### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10041]
### Description
How to add forgot password button on login  home

**Comment by vovpff** [comment]
@guide5232 check configuration giles

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/caa56b6b11b393ce59c2e9dc2da0d79cb550a0e8/config/Security.php#L26-L27

**Comment by acsinsurancegroup** [comment]
Well this was easy and used to work before the 5.1.0 version. You simply would go to the Config directory in the root of your CRM and edit the Security.php file.

Change line 27 to "true"

	/** Possible to reset the password while logging in (true/false) */
	public static $RESET_LOGIN_PASSWORD = true;

and then you would have that option. Again, no it doesn't work for me no matter what I do. Every time a new version rolls out, we seem to lose something we depended on before.

**Comment by mariuszkrzaczkowski** [comment]
Check if your smtp is active. You won't see this option without it because the system won't be able to send messages.

https://github.com/YetiForceCompany/YetiForceCRM/blob/95356a2d089324caac86912ca8a5033f3b819cd6/layouts/basic/modules/Users/Login.Default.tpl#L93

**Comment by acsinsurancegroup** [comment]
> Check if your smtp is active. You won't see this option without it because the system won't be able to send messages.
> 
> [YetiForceCRM/layouts/basic/modules/Users/Login.Default.tpl](https://github.com/YetiForceCompany/YetiForceCRM/blob/95356a2d089324caac86912ca8a5033f3b819cd6/layouts/basic/modules/Users/Login.Default.tpl#L93)
> 
> Line 93 in [95356a2](/YetiForceCompany/YetiForceCRM/commit/95356a2d089324caac86912ca8a5033f3b819cd6)
> 
>  {if App\Config::security('RESET_LOGIN_PASSWORD') && App\Mail::getDefaultSmtp()}

@mariuszkrzaczkowski You are the man. That was it, thanks so much for the tip all good now :)
