### ISSUE TITLE
[bug] Relation issue (Reservation > employees)

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10042]
In Reservation created field 1:m linking to Employees. Once I add Employee to the reservation, it should show this Reservation record in Employee related tab (Reservations) but it not. Reservation list is always empty. Little bug?

**Comment by mlorencik** [comment]
the relationships are very delicate, you probably have the wrong type, there are two main types of getRelatedList (search / add many) and getDependentsList (you assign a record from the edition like here)

**Comment by waran70** [comment]
Both have been checked.

**Comment by mlorencik** [comment]
Please check one think, by default Reservation has related to Employees by link field (Company), when you create another field it will be not working

**Comment by bpabiszczak** [comment]
It must check your programmer.
