### ISSUE TITLE
[Feature] UI type 10 Contacts > Employees

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10040]
When I add to some module Contact field (UIT10) it shows First and Last name in the field.
If I do the same with employees it shows just last name. How to fix this inconsistency?

**Comment by vovpff** [comment]
@waran70 search labels?

**Comment by waran70** [comment]
?

**Comment by vovpff** [comment]
Just add here `My home page/Software configuration/Search and filters/Search - Configuration
` needed fields

![image](https://user-images.githubusercontent.com/8545791/55139787-aa1bfe80-5147-11e9-8812-f992bf8248c8.png)

**Comment by adudekyeti** [comment]
Hi,
@vovpff wrote everything. I can only add that after change you have to wait for cron which will update field labels.
