### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10058]
# 🐞 bug report
I am trying to upload a mp3 file in document module That time i am getting "413 Request Entity Too Large" error but i have given 3MB file only

![Documents Create](https://user-images.githubusercontent.com/47585969/55215555-4f20ff00-524e-11e9-877e-7f3271ffc288.png)

 I got below error 
![Document error](https://user-images.githubusercontent.com/47585969/55215554-4e886880-524e-11e9-81bc-86e3e5d7a276.JPG)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0
| Web server (name and version)|	Apache	|
| PHP  |	7.1.x, 7.2.x, 7.3.x (dev)							|
| Browser (name and version)  | 	Google chrome	|
| Operating System (name and version)  | window 7		|
| Database (name and version) | MySQL		|

**Comment by mariuszkrzaczkowski** [comment]
attach a screenshot of verification of configuration

**Comment by JohnMaverick** [comment]
I checked too on developer version. see screenshot
![Capture](https://user-images.githubusercontent.com/29787568/55216727-1bcf7780-5230-11e9-97a2-e482fae5b134.PNG)

**Comment by guide5232** [comment]
> attach a screenshot of verification of configuration

I am not understanding above statement which means error logs or any thing else

**Comment by bpabiszczak** [comment]
https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/
