### ISSUE TITLE
[Question] - How to properly update to latest version (e.g. v3 to v4)

### ISSUE THREAD

**Issue by yakovfeldman** [YetiForceCompany/YetiForceCRM#10052]
I installed update from ver 4.4.0 to 5.0.0 v3 (4.4.0_to_5.0.0_v3.zip)
If install new update 4.4.0_to_5.0.0_v4.zip I see an error.
How to properly update from 5.0.0_v3 to 5.0.0_v4?

Thanks

**Comment by vovpff** [comment]
You can't. 5.0.0 V3 to v4 impossible. You can only update to 5.1.0
