### ISSUE TITLE
[Question] Where is the best place to find Yetiforce freelancer? 

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10059]
Was looking at Upwork, but I see the same faces as for Vtiger, what got me disappointed a few times before. 

I mean I know I can get a package from Yeti's but this is not biggy stuff. Just few reports - like that

**Comment by paula-w** [comment]
We don’t recommend hiring freelancers, as this kind of services is usually low quality. 
They don’t guarantee compatibility nor security. Also, they unfortunately don’t contribute to the development of YetiForce.
We’re going to open partnership programs very soon and you will be able to pick one of our authorized and reliable partners to do the work for you.
