### ISSUE TITLE
[bug] Account > Contacts PDF

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10056]
Created PDF template for Accounts with: $(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]|)$

While I trying to print PDF I have an error as follow:

Argument 1 passed to YetiForcePDF\Style\Style::convertUnits() must be of the type string, null given, called in /var/www/html/crm1/vendor/yetiforce/yetiforcepdf/lib/Style/Normalizer/Normalizer.php on line 84

checked on git developper

**Comment by rafalpospiech** [comment]
paste your template code here

**Comment by JohnMaverick** [comment]
Checked myself on developer. same issue. See attached
![Capture](https://user-images.githubusercontent.com/29787568/55217130-4837c380-5231-11e9-9227-f8be0553ea33.PNG)

**Comment by JohnMaverick** [comment]
Now I see it fixed in developer ... what was that? :-)

**Comment by waran70** [comment]
Just this:

$(relatedRecordsList : Contacts|firstname|)$

Help appreciated

**Comment by rafalpospiech** [comment]
try this `$(relatedRecordsList : Contacts|firstname)$` without pipe character at the end `|`

**Comment by waran70** [comment]
That works, so I guess pipe comes with more than one field. Tnx.
