### ISSUE TITLE
[bug] Related list default layout 

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10055]
See attached. This is what happens with the table if one field gets too more characters. Can it be fixed so as a default field text going to be wrapped?

[Reservations_155_2019_03_29 (13).pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/3020934/Reservations_155_2019_03_29.13.pdf)

**Comment by mlorencik** [comment]
one of the options is certainly the limitation of the number of columns, for the relatedlist we have extensive possibilities as in the example below, but in fact there is no parameter for specifying the maximum length of the value, now I add this

$(relatedRecordsList : Contacts|firstname,lastname,email|[[["firstname","a","Tom"]]]||5|10|50)$
on this example is defined module|columns|conditions|view id or name|limit|max value length

**Comment by waran70** [comment]
What about wrapping text in the column as we can do in a spreadsheet cell?

**Comment by mlorencik** [comment]
word-wrap would be good here, but unfortunately our library does not support it yet
https://github.com/YetiForceCompany/YetiForcePDF
