### ISSUE TITLE
Error while transferring to another hosting

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10057]
Hi, I just transferred yetiforce 4.4 to another hosting which does not have yetiforce in softaculous. The php ver is 7.1. I used the following method:
1. I transferred the backup of files in file manager to the new hosting.
2. Then I created a new database and user using the same name as in the other hosting.
3. In this new database I Imported the old database.
4. I changed the database password in config.inc.php.

After All worked fine, the transfer was Ok. Then suddenly It is not working. Please help to solve this problem.

Thanks.

**Comment by indrabhusanroy** [comment]
This error message is being displayed when I open the link:
This page isn’t working 
HTTP ERROR 500

**Comment by indrabhusanroy** [comment]
Right now sometimes, the login page is showing, then when I try to login after I provide username and password, it showing the error message again.Please help...

**Comment by indrabhusanroy** [comment]
The error log shows error : modules/Users/models/Record.php on line 460

PHP Fatal error:  Uncaught Error: Call to a member function get() on null in modules/Users/models/Record.php:460

**Comment by indrabhusanroy** [comment]
Hi, Is this due to unique application Id conflict. I have transferred to new hosting but the original copy is active at the other hosting, and I don't want to remove the older copy at the other hosting, so how to generate a new application id?

**Comment by indrabhusanroy** [comment]
Now the original copy of yetiforce is also not working.

**Comment by indrabhusanroy** [comment]
It seems when I try to login as admin, This error is showing up, but when other users are logged in, they can access the system.

**Comment by bpabiszczak** [comment]
After transferring the system to another server, it should work.
You have an incorrect configuration in the config file or an incorrect server configuration.
It must check the programmer.
