### ISSUE TITLE
Synchronizacja z google calendar

### ISSUE THREAD

**Issue by jucia** [YetiForceCompany/YetiForceCRM#1006]
Witam,

W jaki sposób uruchomić synchronizację z google calendar oraz google contact ?

pozdrawiam

**Comment by bpabiszczak** [comment]
Witam,

za nim odpowiem, mam jeszcze krótkie pytanie? W jakim celu chcesz dokonać integracji ? Czy po to, aby później zintegrować z innymi urządzeniami i aplikacjami czy też po to, że codziennie korzystasz z webowej wersji. 

Pytam, ponieważ w zależności od Twojej odpowiedzi są różne wersje mojej odpowiedzi.

**Comment by jucia** [comment]
Pytam, ponieważ z 'normalnej' wersji vtiger widziałem integrację zarówno kontaktów i kalendarza google.

Obecnie na co dzień używam zarówno kontaktów i kalendarza z google - jeśli była by możliwość integracji tego z yeti - to dla mnie by była 'bomba' użytkowa:)

**Comment by miriampl** [comment]
Dokładnie tak samo to rozumiem. 
Dziś dla mnie najważniejsza jest dostępność danych. Jeżeli system komunikował by się z google calendar i google contacts to można pracować po wyjściu z biura. Jestem wdrożeniowcem i często mam tak, że mimo wyjazdu wykonuje 10 rozmów podczas jazdy. Problem jest w tedy gdy dane do kontaktu / terminu i opisu są w systemie, który nie robi mi przypomnień, łatwego podglądu, łatej modyfikowalności zadania, głosowego opisu przebiegu rozmowy. 
Dodatkowo jest to backup moich działań bo google account jest spięte firmowa poczta, tak więc całość ma większy sens. 
Robienie nowych app dla rozwiązania które już istnieje (telefony android nexus 5 dla wszystkich) kontra nowe rozwiązanie w postaci aplikacji caldav, które robią dodatkowy ruch z siecią i synchronizują się do jednej maszyny a nie w tle w firmie do serwerów google a do telefonów po przez synchro po push systemu google (tylko wtedy gdy coś jest).

**Comment by waw555** [comment]
I also think this feature useful, I have synchronized the phone with contacts and Google Calendar Google, and when there comes a CRM event or an event, the phone appears notified and added to the crm contact appears in your phone.

**Comment by eptapsyxos** [comment]
+1

**Comment by jucia** [comment]
Dodatkowo na stronie w nowościach opisujecie:
https://yetiforce.com/pl/yetiforce-crm/155-yetiforce-2-0.html

Poniżej skrócona lista zmian:

Możliwość synchronizacji kalendarza i kontaktów z dowolnym programem i urządzeniem.

Więc dalej pytam gdzie jest ta synchronizacja możliwa do ustawienia ?

**Comment by bpabiszczak** [comment]
Jucia ;] 

1. Modyfikujemy plik w swoim CRM: https://github.com/YetiForceCompany/YetiForceCRM/blob/master/config/api.php i zmieniamy wszystko co dotyczy caldav i carddav, czyli:
   a) w zmiennej $enabledServices usuwamy komentarz przy pozycji dav.
   b) $enableCardDAV = TRUE;
   c) $enableCalDAV = TRUE;
2. Generujemy sobie klucze u siebie w CRM: https://test.yetiforce.com/index.php?parent=Settings&module=Dav&view=Keys&block=5&fieldid=77
3. Konfigurujemy odpowiednią aplikacje [program, urządzenie] które ma integracje z caldav i carddav wbudowaną np. iphone, podając następujące dane:
   a) adres do api: [nasz.adres.do.crm/api/dav.php
   b) login i hasło które wygenerowaliśmy sobie w punkcie 2.

i ogólnie to wszystko.

Odnośnie google i integracje z nim. Raczej nie planujemy tego w przyszłości, ponieważ integracja CardDav i CalDav daje o wiele większe możliwości. Żadna poważna i duża firma nie korzysta z rozwiązań Google a tym bardziej żadna organizacja publiczna. Nikt nie chce przechowywać swoich poufnych informacji nie wiadomo gdzie. 

Aktualnie nasze rozwiązanie i rozwiązanie Google działa w trybie serwera. Należy albo znaleźć rozwiązanie synchronizujące serwery dav pomiędzy sobą, albo jeden z nich zmienić w tryb klienta. Dla nas integracja z Google to raczej krok do tyłu. 

Odnosnie integracji którą posiada Vtiger, to nigdy nie działała ona poprawnie, za starych czasów czyli Vtiger 6.0/1 zgłosiliśmy 15 błędów które były ignorowane przez 8 miesięcy, z tego co pamiętam w wersji 6.2 pojawiła się nowa wersja tej integracji, ale ona również zawierała tyle błędów, że nie byliśmy wstanie tego zaakceptować i wyłączyliśmy tą integracje z naszego silnika. Kod za to odpowiedzialny, zostanie również całkowicie usunięty z YetiForce.

**Comment by waw555** [comment]
Well, how then to sync contacts and calendar on the Android (for example Samsung Galaxy S3)?

**Comment by bpabiszczak** [comment]
https://github.com/bitfireAT/davdroid
