### ISSUE TITLE
[Question]  Styling related records table

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10067]
Hi guys, could you please provide some sample on how to style related record? I mean font size, table borders etc. Let say I have:
$(relatedRecordsList : Contacts|firstname,lastname,email)$

and I want above to be font-size: 8; and table-borders #ccc;

How to get it working?

**Comment by mariuszkrzaczkowski** [comment]
```html
add a style tag
<style>

</style>
```

**Comment by JohnMaverick** [comment]
How to add tag to variable?

**Comment by JohnMaverick** [comment]
You cannot set fields in different table cells - can you?

**Comment by rafalpospiech** [comment]
We need to add classes to variables again, because they were not supported for some time, after that we will tell you which classes you can use on which elements.

**Comment by JohnMaverick** [comment]
The aim is to allow to style table, so reports can be nicely prepared. By the way, Rafal, maybe it is time to think of size of pdf? pretty big... cannot imagine complex report... there must be a way of compression to the let say PDF/X-1a:2001.
Will drop 20 bucks

**Comment by waran70** [comment]
Hi Rafalpospiech is there any update on that classes?

**Comment by adudekyeti** [comment]
Hi,
Now the only way to put a style on this list is modify relatedRecordsList() in this file: "app\TextParser.php". There you can add styles which you want.

**Comment by davide-alghi** [comment]
> ```
> add a style tag
> <style>
> 
> </style>
> ```

Hi @mariuszkrzaczkowski,
if I put style tag into PDF template, that is dropped; or am I forgetting something?
YF6.1 SP7
