### ISSUE TITLE
[Feature] New field: Values from the dependent module

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10068]
Would be perfect to show in the related module, field values from the dependent module.
Actually, it will amazingly extend functionality. 
For instance, We do a reservation for some contact. Once we chose in reservation details particular contact (UI type 10), I would like to see also contact phone and collar number without clicking on it. 
Who is with me? 
:-)

**Comment by bpabiszczak** [comment]
Like this ;)
![image](https://user-images.githubusercontent.com/10197525/55296148-e5ebe800-5415-11e9-83b6-95879cd029be.png)

**Comment by vovpff** [comment]
@bpabiszczak what you mean?

**Comment by waran70** [comment]
Blazej, can you elaborate a bit?

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
this is Błażej's answer:
1. The system has a functionality that allows you to show fields from related modules.
2. Contact has a M:M relation and other relations are not supported for this module. The solution available in the system is the preview of a related module. If you would like to order this functionality as you described, it would take 2 working days to create.

**Comment by waran70** [comment]
Just to make sure we understand each other well:
The idea is to show (for example) a document and all its relations to other modules.
Would be cool to think of the others including custom modules.

**Comment by konadrian** [comment]
You can see the related record details by hovering over a relation
![image](https://user-images.githubusercontent.com/3193498/61375483-4d338800-a89f-11e9-808f-4d605179459c.png)
