### ISSUE TITLE
[Question]           

### ISSUE THREAD

**Issue by shawnbure** [YetiForceCompany/YetiForceCRM#10066]
Hi! I tried to create a custom global variable to override a value in the system that is pretty restrictive. Doesn't seem to take:

This is the variable I added (assumed I could easily reference it globally)
**********************************************************
yeti_root_folder/config/Main.php

class Main

/** Number of Scheduled Workflows **/
public static $MAX_ALLOWED_SCHEDULED_WORKFLOWS = 1000;
**********************************************************

This is the page I tried to change it in. When I assign an actual number aka return 1000 it works. Otherwise it limits the number to unknown
**********************************************************
yeti_root_folder/modules/com_vtiger_workflow/VTWorkflowManager.php

public function getMaxAllowedScheduledWorkflows()
	{
		//return 10;
		return $MAX_ALLOWED_SCHEDULED_WORKFLOWS;
	}
**********************************************************

**Comment by liviubbo** [comment]
Hy there,

   is the variable working ?

**Comment by konadrian** [comment]
If you would like use MAX_ALLOWED_SCHEDULED_WORKFLOWS  variable in code you should change it for:
`\App\Config::main('MAX_ALLOWED_SCHEDULED_WORKFLOWS');`
