### ISSUE TITLE
[bug] Exported csv from calendar contains crmids instead names

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#10075]
# 🐞 bug report

### ⁉️ Describe the bug

When csv from calendar exported then related Account appear in table as record crmid instead record name / search label.
### 🔥 How to trigger the error

Just export from calendar to csv and check result.

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.1.0

**Comment by bpabiszczak** [comment]
Details::Subject,"Details::Assigned To","Details::Start date &amp; time","Details::Time start","Details::End time","Details::Due date &amp; time","Details::Share with users:",Details::Status,Details::Priority,"Details::Send notification","Details::Modified time","Details::Created time","Details::Created by","Details::Activity type",Details::Visibility,Details::Duration,Details::Updated,"Details::Duration in minutes",Details::Location,"Details::Show as","Details::No time","Details::Last modified by","Details::Closed time","Details::All day",Details::Private,"Description details::Description","Reminder details::Send reminder","Recurrence details::Repeat","Recurrence details::Repetition","Related to::Company","Related to::Process","Related to::Subprocess","Related to::Related event","Related to::Contact","Related to::Second level subprocess"
fghfg,"YetiForce Demo",2019-04-01,00:07:00,01:07:00,2019-04-01,,PLL_PLANNED,Low,0,"2019-04-01 00:07:30","2019-04-01 00:07:30","YetiForce Demo",Meeting,Private,1,0,0,,PLL_OPAQUE,0,"YetiForce Demo",,0,0,,,0,,115,0,0,,0,0

In my opinion, it works well.
