### ISSUE TITLE
[bug] Mass edit - pick list = not working

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10072]
When I do mass edit of records and if I wish to change some status, it gives me **"None of the field values are changed in mass edit"**.

That concerns system created picklists as well as new created picklist in new modules

**Comment by bpabiszczak** [comment]
I checked and works, record a movie.

**Comment by JohnMaverick** [comment]
![Capture](https://user-images.githubusercontent.com/29787568/55296743-10569900-5448-11e9-87c6-562c61e691b4.PNG)

**Comment by JohnMaverick** [comment]
same same.... no logs for that

**Comment by bpabiszczak** [comment]
![ps](https://user-images.githubusercontent.com/10197525/55296762-69a9d280-541e-11e9-8dd1-c80355dcae9f.png)

**Comment by JohnMaverick** [comment]
Not sure I got what you mean... Industry field is disabled here, not necessary. Type returning mentioned notification

**Comment by waran70** [comment]
Just check on YF stable  - exactly the same behavior.

**Comment by vovpff** [comment]
@JohnMaverick to change something you need to pick value and click field label button. Label button should be gray before clicking save!

**Comment by waran70** [comment]
O.O 

Git should allow for converting stupid questions to FAQ

**Comment by vovpff** [comment]
@waran70 problem solved?
