### ISSUE TITLE
[Question] Workflow - System

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10071]
How more friendly and easier to understand can we name workflow trigger "System"?
Any help?

**Comment by bpabiszczak** [comment]
It's OK for me.

**Comment by vovpff** [comment]
@waran70 `System` workflow has hardcoded in core conditions to start some automation process.

**Comment by waran70** [comment]
how often it running? Which predefined cron triggering it?

**Comment by mlorencik** [comment]
workflows starts every 15 minutes by default

**Comment by waran70** [comment]
I believe when I want to trigger "update related record" workflow, "System" will run with intervals set in CRON/Workflow (Scheduler)?

**Comment by bpabiszczak** [comment]
First, CRON is run in Linux. This triggers CRON in YetiForce. Actions run in accordance with the order.
