### ISSUE TITLE
[bug] Calendar export to csv exports all records data

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#10074]
# 🐞 bug report

### ⁉️ Describe the bug

When calendar records exported from custom filter to csv then exported file contains all available columns (fields from calendar) instead only visible column in records list view.

### 🔥 How to trigger the error

1. Go to Calendar
2. Select records
3. Export them to csv
4. Check file

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.1.0

**Comment by bpabiszczak** [comment]
Export works like this. Only export to xls works as you wrote.

**Comment by vovpff** [comment]
@bpabiszczak I'm so sorry. You are right. is it possible to activate export to xls for calendar?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks for reopening. I think export to xls can be added by some strings in core but I don't know where.

**Comment by vovpff** [comment]
any updates?

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/10930
will be available in version 5.2
