### ISSUE TITLE
[Feature]    Invoice to Contact as an option

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10076]
I designing system for some company whos Customer have various departments. Each department has a person responsible for signing invoices, so my client needs to tie a particular invoice to a few persons in the same organizations, that they can get automated correspondence diverted to own mailboxes. This is actually a very common scenario. Maybe implement it in the core?

**Comment by bpabiszczak** [comment]
We currently do not have time for this.

**Comment by JohnMaverick** [comment]
Here is similar: the person responsible for a batch of work, signing off the invoice sent to his department. Once he signs it off, he dropping it to expense ledger department. There are 5 different guys in this company who must be assigned to a particular invoice. Vtiger model perfectly suits to this scenario. Maybe worth to redesign a little bit? It easy to customize it, but above scenario relating to nearly all large corporations...
