### ISSUE TITLE
[Question] YF registration warnings

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10077]
I am dealing with CRM for one company, nearly finished things so 15 users surfing already there.
While installing, I provided all necessary registration details and it showed that this is properly finished. Now everyone sees a warning triangle at the bottom about registration and license etc... it is pretty crazy to get answering massive amount of questions from all users... (legal company!!!). Can you guys at least limit such warnings to admins only? You don't wanna me to give em your number do you?
 :-)

**Comment by bpabiszczak** [comment]
After this change, we have 3x more registrations, why?
