### ISSUE TITLE
[bug] Value from the related module

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10073]
This field and its values with the use of filtered by field and the respective value behave inconsistently in the case when we change a field value in the related module. 
Basically, corn not updating this condition and filter not respecting changed condition(s).
Moreover, in the parent module the mentioned field (after changing the field value in related module) shows 'rr" value, it smells me like some "array" word messing in the code. I don't sniff deeply as I extensively testing front end. Hope someone can follow up with nose into relevant code set.

**Comment by espeoceka** [comment]
Yes its showing up in my case when i add anything to a related module and then ( in case of human error ) im changing related item again. It keeps adding old values inside field with Array and some delimiters ( Array5000.00000000|#|old number ). In case this value is left empty after any change in record it keeps showing Array. 

Also in automatization when im trying to update this field i got a nice picklist with values but even if one is picked it still see Array and cant use it for calculations
