### ISSUE TITLE
Modules - Prefixes

### ISSUE THREAD

**Issue by mitk0s** [YetiForceCompany/YetiForceCRM#10070]
Hello,

Can the order number for the invoice / Sales Order / Opportunity be changed as follows:
XXXХХХХХ-ZZZZ-0000001 - Where X represents variable ( the code of the cash register used ),
Z - variable ( the last name of the person assigned to the order -last name is entered as 4 digit number ) and after that is sequence starting from 0000001

I am asking this kind of confusing questions, due to change in the law regarding systems connected with payments. This is one of the requirements. 

Thank you in advance! :)

**Comment by bpabiszczak** [comment]
In which country?

**Comment by mitk0s** [comment]
The country is Bulgaria and there is brand new law comming which will affect every software which is able to track Sales Orders. We need to comply with all the regulations and this is one of them.

**Comment by paula-w** [comment]
It requires some programming work and we don’t really have time for it right now. It wouldn’t take long (1 ~2 days)  so it’s quite easy to add to the system. Right now a dozen companies in Bulgaria use the system in version 5.x so you can use our Open Collective page to donate towards this functionality: https://opencollective.com/yetiforcecrm
