### ISSUE TITLE
How to update Total time [h] in ticket

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#10079]
### Description
How to update Total time [h] in ticket and which time based this field will update.

**Comment by vovpff** [comment]
Also interested

**Comment by mlorencik** [comment]
in tickets you have relation tab "time control", after add there time with status = Accepted, time is auto recalculate by workflows, cron fo this turns on every 15 minutes

**Comment by gopi12343** [comment]
In below screenshot we can able see total time without time control
![time contral](https://user-images.githubusercontent.com/45963919/55454334-456f1100-562b-11e9-8228-fca3df36d3e2.JPG)

**Comment by konadrian** [comment]
Could you get more information because I'm not sure what do you suggest?
