### ISSUE TITLE
[Question]   "update related record" trigger frequency         

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10086]
How often workflow "update related record" is triggered if "System" will run with intervals set in CRON/Workflow (Scheduler)?
I experience a situation where I have no idea how it triggers. Sometimes works and usually not. 
This task is very useful, but maybe needs more documentation?

**Comment by mlorencik** [comment]
by default it starts every 15 minutes

**Comment by waran70** [comment]
Actually, it is not at least here. What do you mean by default? Which cron job triggering it?

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/55334571-301aab00-54a2-11e9-927e-d3b119870730.png)
No2 20

**Comment by mlorencik** [comment]
ok, I meant that a temporary workflow fires every 15 minutes. The one you are talking about is called in the save record, Vtiger_Workflow_Handler is called via EventHandler, in this case VTUpdateRelatedFieldTask
