### ISSUE TITLE
Auto assign records  

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#10080]
### Description

How to Auto escalate ticket records from one level to another level on hours and dates based.
ex:if we create ticket record,that record status is not closed with in one hour then auto escalate(assign) next level person,if that person not closed with in two hours then auto escalate(assign) to next level person.

**Comment by vovpff** [comment]
@gopi12343 workflows?

**Comment by gopi12343** [comment]
Which condition we have to take

**Comment by mlorencik** [comment]
First execution schedule - set time to check records to hour
Second add conditions to select records with not closed status and open time is an hour ago
Then just set Auto assign record and select your template

**Comment by gopi12343** [comment]
> First execution schedule - set time to check records to hour
> Second add conditions to select records with not closed status and open time is an hour ago
> Then just set Auto assign record and select your template

I have searched for open time is an one hour ago but i did't find any field.please help where can i find open time is an hour ago

**Comment by mlorencik** [comment]
Created time or add new field for this

**Comment by guide5232** [comment]
I have given below condition but no user this is not wait for four hours  i create record at 2 pm this will be fire at 6 pm .but this fired  at 3 pm i have seen task actions
![desktop](https://user-images.githubusercontent.com/47585969/55395403-30dc3b80-558d-11e9-80d1-5530e570084b.JPG)

**Comment by gopi12343** [comment]
I have set Execution schedule (defined time intervals)

I have created workflow using below condition.I have given more than hours before 4. Actually this record will fire at  created time +4 hours .but this is not wait 4 hours.    
![image](https://user-images.githubusercontent.com/45963919/55395827-28383500-558e-11e9-92ad-7ed8cfbee87f.png)

**Comment by konadrian** [comment]
Could you try occur this error on https://gitdeveloper.yetiforce.com/

**Comment by konadrian** [comment]
Could you try occur this error on https://gitdeveloper.yetiforce.com/

**Comment by konadrian** [comment]
I closed the issue because we've waited too long for an answer
