### ISSUE TITLE
[bug] "Update related record" task is not working

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10092]
I did the test on https://gitstable.yetiforce.com/

following steps:
Module "Accounts"
Related module "Campaigns"
Related campaign "Kampania słownik"

Workflow name "Update_campaign_name"
Specify when to execute this workflow "System"
No filter conditions
Task for workflow "update_campaign_name_with_account_name"

Task for workflow config - set field value: 

- Left column: related module field "Campaign name"
- Right column: Parent module field "accountname"

Workflow set at 9:08 am
checked if Campaign field changed: 09:15 result: no field was renamed
checked if Campaign field changed: 09:20 result: no field was renamed
checked if Campaign field changed: 09:30 result: no field was renamed

Workflow is active in the system and can be inspected at any time. In case of the system will be overwritten/refreshed I attaching workflow here.
[77_workflow.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/3032068/77_workflow.zip)

**Comment by vovpff** [comment]
@waran70 As I know `System` workflow can't trigger any of record modifications.

**Comment by waran70** [comment]
So what is this for?

**Comment by vovpff** [comment]
I'm not really sure but `System` has hardcoded conditions inside for system some actions

**Comment by waran70** [comment]
If that is the case why it can be used by users as a condition? A bit more info about this execution would be helpful.
