### ISSUE TITLE
[bug] Conditions with dates in filter lists dont work properly

### ISSUE THREAD

**Issue by nkzach** [YetiForceCompany/YetiForceCRM#10090]
# 🐞 bug report

### ⁉️ Describe the bug

if the user select a date format different from yyyyy-mm-dd  e.g dd-mm-yyyy the conditions with dates in filter lists dont work properly

### 🔥 How to trigger the error

1. Go to 'https://gitdeveloper.yetiforce.com/index.php?module=Users&view=PreferenceDetail&record=5'
2. Choose Date format : dd-mm-yyyy
3. Go to 'https://gitdeveloper.yetiforce.com/index.php?module=FInvoice&view=List'
4. Create a new filter and add dates condition
5. See the unexpected results

**Comment by nkzach** [comment]
if choose date format with "/" e.g. yyyy/mm/dd then

<img width="1144" alt="Στιγμιότυπο 2019-04-01, 5 23 03 μμ" src="https://user-images.githubusercontent.com/22010748/55334999-fd24e700-54a2-11e9-9865-69e127193a31.png">

**Comment by konadrian** [comment]
This error was solved
