### ISSUE TITLE
[Question]           Change Add Record button color and background

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#10091]
### Description

I need to change the background only for Add Record Button from List View.
I tried to change it, but change all buttons with same class.

Tried to access ButtonViewLink.tpl, ButtonLinks.tpl, ListViewActions.tpl and other files, but i haven't finded a way to change only this.

How i can do this change?

**Comment by mlorencik** [comment]
Write css, buttons have specified and individual classes so it will be easy
![image](https://user-images.githubusercontent.com/11301300/55383194-e1afef80-5527-11e9-97b4-89b0952fbf9b.png)

**Comment by cltvchannel** [comment]
Thanks!

**Comment by vovpff** [comment]
@cltvchannel explain please how you colored buttons?
