### ISSUE TITLE
[Question]  Execution schedule (defined time intervals)

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10093]
How  to set Execution schedule (defined time intervals) to trigger every 1 min?

**Comment by JohnMaverick** [comment]
>>> /var/www/html/crm1/modules/com_vtiger_workflow/Workflow.php

if ($scheduleType == self::$SCHEDULED_HOURLY) {
			$nextTime = date('Y-m-d H:i:s', strtotime('+1 minutes'));
		}

**Comment by konadrian** [comment]
It needs some programing, here you have examples
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/com_vtiger_workflow/Workflow.php#L328
