### ISSUE TITLE
[bug] Workflow with "or" condition issue

### ISSUE THREAD

**Issue by tullio1969** [YetiForceCompany/YetiForceCRM#10097]
Hi,
I created a workflow for updating field: there are many "or" conditions, but update field only works if the last "or" condition occurs.

I'm using yetiforce 5.1, but also tested in gitdeveloper, with same issue.

Here are the gif file

![workflow](https://user-images.githubusercontent.com/49146880/55397300-35313600-5546-11e9-8557-a36e52f79648.gif)
![test workflow](https://user-images.githubusercontent.com/49146880/55397311-3a8e8080-5546-11e9-9a5c-31c07009569b.gif)

**Comment by vovpff** [comment]
@tullio1969 try `has changed to` instead `is`

**Comment by tullio1969** [comment]
already tried, no result

**Comment by waran70** [comment]
@vovpff "or" doesn't mean "if" !!
