### ISSUE TITLE
Not sure if yours or not, but y0u might be interested.  Softaculous install of 5.01 throwing following fatal error:  Fatal error: Class 'App\Exceptions\AppException' not found in /home/anonymous/public_html/anonymous/yeti/include/RequirementsValidation.php on line 9.  Attempted to install on Siteground into most robust shared server. [bug] 

### ISSUE THREAD

**Issue by rancov** [YetiForceCompany/YetiForceCRM#10102]
# 🐞 bug report

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by vovpff** [comment]
What is maximum title length on github? xD

**Comment by paula-w** [comment]
All issues related to errors that pop up when you install YetiForce via Softaculous have to be reported directly to Softaculous. 
The current stable version is 5.2.
