### ISSUE TITLE
[Question] Update field returns number          

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10104]
In the same module I have UI 10 and text field. Created workflow to update txt field with value from mentioned UI 10 and instead of mirrored text I got number only.
Any way to make it working?

**Comment by JohnMaverick** [comment]
up issue? Any help?

**Comment by mariuszkrzaczkowski** [comment]
Call this error on the gitdev version and burn the video so that we can understand what the problem is

**Comment by vovpff** [comment]
Really UI 10 value is numeric. But whe you pick some record numeric value replaced with record label. This is ok for system at all but dont works proper with workflows as you checked.

**Comment by adudekyeti** [comment]
Hi,
You use wrong type of fields. Everytime you need to use the same types of source and target fields.
