### ISSUE TITLE
[Pytanie][PL] Dodawanie modułu

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10108]
Witam,

Gdy tworze własny moduł podstawowy to czy jest on typem entity?  Chodzi mi o używanie QueryGenerator we własnych modułach, czy jest to możliwe? 

Zgodnie ze [strona](https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-programistyczna/item/querygenerator)
"System YetiForce od wersji 3.5 ma nowy mechanizm QueryGenerator, którym można listować dowolne dane z modułów typu entity."

**Comment by bpabiszczak** [comment]
Entity to te moduły, które mają standardowe mechanizmy takiej lista rekordów, podgląd rekordu, filtrowanie itd. Rekordy wówczas znajdują się [między innymi] w vtiger_crmentity. Każdy moduł tworzony z poziomu panelu jest takim modułem.

**Comment by mrzewnicki** [comment]
OK, dzięki wielkie
