### ISSUE TITLE
[Feature]  Modules prefixes

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10116]
In Modules prefixes, postfix word is used instead of word suffix...

**Comment by waran70** [comment]
I mean it is OK but in the linguistic field better is to use a suffix, while in the programming language postfix is OK. Here is kind of linguistic thing ;-)

**Comment by paula-w** [comment]
We think it's alright the way it is now, but if more users wants to change it then we will change it. Thanks for the suggestion.
