### ISSUE TITLE
Chart from filter (Widgets-Configuration)

### ISSUE THREAD

**Issue by d-dune** [YetiForceCompany/YetiForceCRM#10111]
Making a "Chart from Filter" works at the individual level. Making a "Chart from Filter" at the Widgets-Configuration level has an issue (in my case) where it ignores the stated filter and defaults to the "all" filter.

I'm on Yetiforce 5.1.0. This wasn't an issue on 4.4. We upgraded and now it's an issue. I may be missing something simple, wondering if anyone else has experienced this issue or if anyone can help point me in the right direction.

**Comment by vovpff** [comment]
Try to edit widget from admin panel. There you can pick default value.

**Comment by d-dune** [comment]
When I try to edit widget from the admin panel, I only have the "Mandatory Widget", "Cache", "Width", & "Height" options to edit. When I created the widget from the admin panel I selected the filter value I want and everything seems fine until I go to the widget and it isn't using the filter I had selected, it defaults to "all" ignoring what I had selected. I can't get to that setting by editing the widget. It only gives me the "Mandatory Widget", "Cache", "Width", & "Height" options to edit.

I'm not 100% sure if I'm missing something or if this is a legit bug. It worked fine in 4.4 but started after we updated to 5.1.

**Comment by nkzach** [comment]
Same problem for me. Also the problem exist in gitdeveloper!

**Comment by konadrian** [comment]
Could you try occur this error on https://gitdeveloper.yetiforce.com/

**Comment by nkzach** [comment]
Now on gitdeveloper error not exist , on gitstable error exist.

**Comment by nkzach** [comment]
In my system, 5.1 with Service Pack v4, the error continues to exist.

**Comment by Pietrox** [comment]
Same here, wanted to make a chart with login activity for users grouped by country within last 7 days. On perdonal level it works:

![image](https://user-images.githubusercontent.com/22810723/65667195-7dd23380-e03f-11e9-8628-3a15bb376a00.png)

But when I'm doing it from admin so others can use it - it ignores the filter limitation. Also version 5.1 with service pack.

**Comment by Pietrox** [comment]
Found an error during creation of the chart:

```
[Fri Sep 27 06:35:28.052561 2019] [php7:warn] [pid 27961] [client 80.55.8.66:51175] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/jinni/web/crmv2.jinni.technology/public_html/app/Request.php on line 296
[Fri Sep 27 06:35:28.052596 2019] [php7:warn] [pid 27961] [client 80.55.8.66:51175] PHP Warning:  current() expects parameter 1 to be array, string given in /home/jinni/web/crmv2.jinni.technology/public_html/app/Request.php on line 297
```

**Comment by Pietrox** [comment]
For anyone who can't update to new version this should help and fix the problem:

![image](https://user-images.githubusercontent.com/22810723/65762621-be09e280-e121-11e9-9cd8-fa0bbb952da8.png)

**Comment by paula-w** [comment]
It works properly in the current stable version.
If you still experience this issue on version 5.2 please record a video that shows the error.
