### ISSUE TITLE
[Question]  scss - how to

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10115]
Hi guys, how to deal with scss? got a bit lost

**Comment by poradz** [comment]
Hi,

when you change one of our scss file you have to compile Main.css file with Sass.
To achive this, first of all, you have to install Sass:

https://sass-lang.com/install 

Then just run command below in _public_html\layouts\basic\styles_:

`sass Main.scss Main.css`

Hope this helps!
