### ISSUE TITLE
New module related with other module(field) error

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1012]
I ve created a new module
i created a new field 1:m (related module) to related the new module with contacts

when i am trying to add the releated contact to this module a get this error

{"success":false,"error":{"code":"Record you are trying to access is not found: 114 Prescription","message":"Record you are trying to access is not found: 114 Prescription"}}

**Comment by eptapsyxos** [comment]
![error](https://cloud.githubusercontent.com/assets/6897502/7984360/605e437c-0ad1-11e5-88c2-64d483edc463.jpg)

**Comment by eptapsyxos** [comment]
might this helps? 

https://github.com/sardoj/VTModuleDesigner/issues/6

**Comment by bpabiszczak** [comment]
A similar problem: https://github.com/YetiForceCompany/YetiForceCRM/issues/1013

**Comment by mariuszkrzaczkowski** [comment]
I did a simple test I added two modules:
[RelOneToMany](https://test.yetiforce.com/index.php?module=RelOneToMany&view=List&parent=44)
[RelManyToMany](https://test.yetiforce.com/index.php?module=RelManyToMany&view=List&parent=44)

Added relationships:
RelOneToMany and Contacts - 1:M
RelManyToMany and Contacts - M:M

Added records, and shows correctly, it can improperly created relationships?
