### ISSUE TITLE
[Question] Update via SVN after install of complete package

### ISSUE THREAD

**Issue by rodrigolzd** [YetiForceCompany/YetiForceCRM#10122]
I have installed the complete package of the latest version (5.1.0) and I would like to update the install to the latest dev revision with svn. Is there a way to do this safely that wont break the current install? I did not find any information on how to use SVN with yetiforce. I could not find any howtos on using composer to install it either. 

I noticed that the automatic search for accounts under support tickets is not working on 5.1 but it is the development version. I like to have that working and that is why I want to update.

**Comment by paula-w** [comment]
There is currently no way to update it via SVN.
