### ISSUE TITLE
[Question]     refresh the permissions how does this work?

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#10123]
how does this work?   thanks

you can try to refresh the permissions:

\App\Cache::clear();
\App\Cache::clearOpcache();
\App\Module::createModuleMetaFile();
\Settings_GlobalPermission_Record_Model::recalculate();
\App\UserPrivilegesFile::recalculateAll();
\App\Cache::clear();
\App\Cache::clearOpcache();
\App\Colors::generate();

**Comment by mariuszkrzaczkowski** [comment]
Refreshing permissions or in other words reloading permissions.
Please specify your question because if you want to know how it works, it is necessary to look into the code.
