### ISSUE TITLE
[bug] Invoice workflow - no conditions allowed

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10127]
Invoice module - fields "gross" and "net" are not allowed to carry any conditions. Can it be changed?

**Comment by nkzach** [comment]
I don't know why this is happening and if it can be changed. I solved the problem by creating 2 new fields in invoice module,  "gross1 " and  "net1 ", which with a workflow get the values  "gross " and  "NET " each time an invoice is saved, and when i need a condition i use these.
