### ISSUE TITLE
[bug] workflow not showing related module 

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10126]
Created workflow for the invoice with the task "Sum filed values from related module fields".
In this task it should be shown fields from the related modules but is showing fields ONLY from Account, which is the dependent module. 
I have related "Payments in" to "Invoices" from which I need to get values, so Invoice status can be updated if sum of "Payments in" equal to invoice total. 
Is it bug?

**Comment by konadrian** [comment]
You can use this option when a module is related to main module with a uitype 10 field. In the current version the Sales Invoices module doesn't have this relation. 

In workflows you have the possibility to add your own methods where you can write your code in PHP. So you can add a new workflow task which will calculate it for you.
