### ISSUE TITLE
How to enable the encryption mechanism?

### ISSUE THREAD

**Issue by cfrancois7** [YetiForceCompany/YetiForceCRM#10136]
I installed Yetiforce 5.1, but I'm trying to enable the encryption mechanism but I failed.
See the picture above.

<img width="1219" alt="Capture d’écran 2019-04-07 à 16 48 48" src="https://user-images.githubusercontent.com/11422336/55685354-4ec2eb00-5955-11e9-8af7-41510c144cae.png">

I don't understand why it failed to activate.
The password and the configuration are the same in yeti interface and in the `\config\SecurityKeys.php` file. Cron works fine so I don't understand why it failed to work.

**Comment by salloubani** [comment]
Can you share steps to install 5.1?

**Comment by cfrancois7** [comment]
Sorry. It was a mistake of a co-worker who pushed a wrong cron.sh file.
So the export USE_PHP was erased but the cron interface seemed to work fine.
