### ISSUE TITLE
[Question]  installation help 5.1.0

### ISSUE THREAD

**Issue by salloubani** [YetiForceCompany/YetiForceCRM#10135]
Hi There, 
can someone help me please installing YetiForce 5.1 on ubuntu. I have been looking for manuals or videos on this and every finding i see is about 3.1 which works.. applying same steps to 5.1 does not work. appreciate any help or commands to use.

**Comment by vovpff** [comment]
At first you need to install LAMP and php 7.1+. After that you need to configure your server. For this you can check google. If all configured you can install yeti without any problems.

**Comment by mariuszkrzaczkowski** [comment]
https://www.google.com/search?q=YetiForce+ubuntu&oq=YetiForce++ubuntu

https://wpcademy.com/how-to-install-yetiforce-crm-on-ubuntu-16-04/
https://websiteforstudents.com/install-yetiforce-crm-on-ubuntu-18-04-16-04-with-apache2/
https://www.linuxhelp.com/how-to-install-yetiforce-crm-on-ubuntu-16-04
