### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column

### ISSUE THREAD

**Issue by mjapple** [YetiForceCompany/YetiForceCRM#10137]
# 🐞 bug report

### ⁉️ Describe the bug

Hello
When I moved to new hosting i faced the errors which obviously was before on system but not giving error.
When I add new comment on opportunities module there is error for MYSQL 
the error prevents to add the comment successfully while i can see some portion of the comment in the tables in MySQL
the error is as below:
`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'searchlabel' at row 1
The SQL being executed was: INSERT INTO `u_yf_crmentity_search_label` (`crmid`, `searchlabel`, `setype`) VALUES (31382, 'iam trying to type a long message to check whether the text is able to be posted as comment or no, last time i was getting SQLSTATE 22001 error so now again we need to see error is comming or not anyway then bye for now we lookforward to rectify this error soon ', 'ModComments')`

### 🔥 How to trigger the error

1. Go to 'module opportunities'
2. try to comment on any record with long text ''
3. post the comment

### 👎 Actual Behavior

The first Time i posted the same error for table `u_yf_crmentity_label` and field `label` , then i googled and saw the solution is to change `VARCHAR` to `LONGTEXT`
I Did 
![TFI_industries_ 2019-04-08 at 7 13 29 AM](https://user-images.githubusercontent.com/6837503/55696429-f5e36900-59cd-11e9-958b-ba612156d1d3.png)
and now the error is coming to table `u_yf_crmentity_search_label` and this time i am not able to change the type to `LONGTEXT` 
![TFI_industries_ 2019-04-07 at 5 07 46 PM](https://user-images.githubusercontent.com/6837503/55696491-36db7d80-59ce-11e9-96eb-f003f87fa08c.png)

### 👍 Expected Behavior

i expected to post all text in the comment
### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  4.3.0
| Web server (name and version)|	Apache 2.4	| 
| PHP  |					7.1.2			|
| Browser (name and version)  | 	Chrome73.0	|
| Operating System (name and version)  | 	CentOS 7	|
| Database (name and version) | 	MYSQL	|

**Comment by paula-w** [comment]
It has been fixed in the newer versions.
