### ISSUE TITLE
[Pytanie][PL] Import Modułu

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10132]
Czy da się zaimportował Moduł podstawowy np Zgłoszenia tak jak własny? Do Zip'a?

**Comment by bpabiszczak** [comment]
Jeżeli masz na myśli same pola... to pewnie tak [jak się odblokuje taki eksport bo jest na sztywno w kodzie zablokowany]... ale my tak dawno tego nie robiliśmy, że przypuszczam pojawią się jakieś problemy. I tak nie wyeksportuje się wielu ważnych rzeczy a dodatkowo i tak przed importem należy zmienić nazwy tabel, klas, modułu... 

Robiłem tak około 10 lat temu jak bawiłem się w Vtiger i nie miałem programistów... teraz moduły robi się od ręki więc kopiowanie powoduje więcej problemów niż korzyści, osobiście odradzam.
