### ISSUE TITLE
[Pytanie][PL] Kopia zapasowa

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10140]
Witam,

mam pytanie o kopie zapasową, czy mogę wykonywać ją ręcznie w Managerze Backup'ów?

W zgłoszeniu o numerze #3663 wspominaliście coś o skrypcie do tego, pojawił się gdzieś czy jeszcze nie?

**Comment by bpabiszczak** [comment]
Menadżer backów służy tylko do listowania i pobierania, wykonywać go powinien skrypt shellowy. Niestety dla każdego rozwiązania LAMP taki skrypt może wyglądać inaczej, nie publikowaliśmy go raczej nigdzie, montujemy u klientów na koniec wdrożenia i dopasowujemy do jego infrastruktury.
