### ISSUE TITLE
[Question] What condition should be met to be able to create entity          

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10145]
I related Payments to a custom module. Now I need to create workflow what will create entity record in the related "Payments Out" module. Unfortunately workflow don't show related module on the list (attached). What and where should I fix so I can create records with workflow?
![Untitled-1](https://user-images.githubusercontent.com/29787568/55780585-7ee3c880-5ad2-11e9-8098-faef08a681b6.jpg)

**Comment by konadrian** [comment]
You can use option **"Get mapping from panel"** but before you need to create a new mapping for the modules
https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&page=1&view=List
