### ISSUE TITLE
[Feature][5.1.12][User permissions] Show records created by a user in a private module

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#10148]
### Describe the solution you'd like
If I give private access to a module, a user can only see records assigned to him/her. It would be a good idea to have the posibility to see records assigned to him/her and records created by him/her and assigned to another user.

### Additional context
![yeti1](https://user-images.githubusercontent.com/16593721/55798159-2c041400-5ac6-11e9-8432-efb10063ab90.png)

**Comment by bpabiszczak** [comment]
Please test this panel
Software configuration > Permissions > Module access

![image](https://user-images.githubusercontent.com/10197525/62012285-9b406980-b184-11e9-8426-8387f70d39d8.png)
