### ISSUE TITLE
[Question] How to add a gobal room in the chat module?      

### ISSUE THREAD

**Issue by cfrancois7** [YetiForceCompany/YetiForceCRM#10151]
Hello,

Is it possible to add new public channel in the chat module, other than just **General**?
I didn't find documentation to do this.

Thanks in advance.

**Comment by liviubbo** [comment]
Hy there ! 

   You go to settings - > Permissions - > Groups. You create a group, add the users you want to have access to that group, give a name, and there you have it. You will find it under : Group Room.

**Comment by acsinsurancegroup** [comment]
@liviubbo Hello and thanks for your suggestion. I tried what you suggested however and created a group and it doesn't show up anywhere in my chat module. This is on Version 5.0 any thoughts?

**Comment by konadrian** [comment]
It's possible if you add a record directly to the 'u_yf_chat_global' table. We don't yet have an interface to create new global rooms.
