### ISSUE TITLE
PDF Error Content Editor

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1016]
The template editor PDF, the visual editor is displayed only in the header, in the area of content and footer is not displayed
![pdferror](https://cloud.githubusercontent.com/assets/1402355/8000255/9fa90058-0b71-11e5-9b03-5c87cc293eec.JPG)

**Comment by MaciejStencel** [comment]
I have checked it on newest revision 2.0.75 and cannot recreate this problem. All three text areas are WYSIWYG editors.
