### ISSUE TITLE
[PL][Pytanie] Filtrowanie po mailu.

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10161]
Witam,
Mam pytanie związane z filtrowaniem. Pobrałem sobie z "Maile firmowe" adres z którego przyszedł mail na skrzynkę za pomocą dodania pola w Zgłoszeniach "Wartość z modułu". I z tego co widzie to opcje filtrowania są zacznie ograniczone po tym polu, dlaczego tak? 😄  W Mailach firmowych opcji jest 8 a tu tylko 4.

![image](https://user-images.githubusercontent.com/21024857/55955023-9486f880-5c60-11e9-80c4-63de30e31980.png)

**Comment by bpabiszczak** [comment]
Są to dwa niezależne mechanizmy [pole i pole powiązane] a więc mogą mieć inne warunki. Na razie ma to niski priorytet więc pewnie nic z tym nie zrobimy [wiemy, że takich przypadków jest o wiele więcej].
