### ISSUE TITLE
[Question]           Install hanging after accepting criteria - Apache session issues

### ISSUE THREAD

**Issue by sj7272** [YetiForceCompany/YetiForceCRM#10172]
Apache error log showing "Session data file is not created by your uid in /var/www/public/app/Session.php on line 34; session_start(): Failed to read session data: user (path: /var/www/public/cache/session) in /var/www/public/app/Session.php line 34

### Description
I'm using a vagrant box on windows 10 with standard PHP/Apache/MySQL setup
My Yeti install is as follows...
`
sudo mkdir ~/yetiforce
sudo wget --quiet -P ~/yetiforce https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.0.0/YetiForceCRM-5.0.0-complete.zip

sudo chmod +x ~/yetiforce
sudo unzip -o -d /var/www/public ~/yetiforce/YetiForceCRM-5.0.0-complete.zip`

I can walk through the install process in the browser, but at the last stage I get blank page and the items in the error log.
Is this permissions and if so, can someone recommend what to change?

**Comment by vovpff** [comment]
Problem in your server config. I'm not sure but I think I has the same problems at first installation. In my case reason was a slow server and my solution to change max_execution_time and other timing parameters for installation to 10000+. 600 not enough for my server hardware.

**Comment by vovpff** [comment]
Also you need to change owner of crm root folder.

**Comment by sj7272** [comment]
ok, within /etc/apache2/envars, export APACHE_RUN_USER and export APACHE_RUN_GROUP were both set to www-data. 
I performed chmod _R www-data:www-data /var/www/public... nochange
So I reset the chmod using the original vagrant user and group, set this up in the envvars and it worked (after restartting apache2 service) !

**Comment by vovpff** [comment]
:)
