### ISSUE TITLE
Not able to install        

### ISSUE THREAD

**Issue by papacico** [YetiForceCompany/YetiForceCRM#10175]
Hello,
I am trying to install the system but I don't get the wizard started.
- Permissions are all ok
- I run php 7.3.4 on Centos
-I have the script in a directory named crm
-I have tried www.mysite.com/crm  www.mysite.com/crm/public_html/install/Install.php,
but still not working

I get this error when trying to reach the script:

AH01071: Got error 'PHP message: PHP Warning: Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) in Unknown on line 0\nPHP message: PHP Fatal error: Class 'App\\Exceptions\\AppException' not found in .../crm/include/RequirementsValidation.php on line 9\n'

- I have enabled the OPcache in php.ini but did not help

thank you for your suggestions

**Comment by mariuszkrzaczkowski** [comment]
> I run php 7.3.4 on Centos

The system works stably only on php 7.1, 7.2 version 7.3 is in the testing phase and we do not recommend it yet

> PHP Warning: Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) in Unknown on line 0

Delete the .user.ini file

> PHP Fatal error: Class 'App\Exceptions\AppException' not found in .../crm/include/RequirementsValidation.php on line 9

The error occurs if you have a php version of less than 7.1
