### ISSUE TITLE
[PL][Pytanie] Uprawnienia

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10174]
Witam, 

Zacząłem budować w Rolach Strukturę firmy. Wcześniej jakoś udało mi się to zrobić a teraz nie wiem czemu nie mogę, a mianowicie, użytkownicy nie mogą edytować statusów zgłoszeń. Pole jest wyszarzane, ja jako Admin mogę ale Oni nie. Mają nadane uprawnienia edycji i nie mogą zmieniać statusów. Mogę prosić o podpowiedź co za to odpowiada?  Mają możliwość edycji w **Roli**, **Dostępy w profilach** i **Dostępach do Modułu**

Yetiforce 5.0 complete

**Comment by bpabiszczak** [comment]
Należy przejść do edycji słownika i dla wartości słownika nadać uprawnienia: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9

**Comment by mrzewnicki** [comment]
Faktycznie, dzięki wielkie za podpowiedź. Zapomniałem o słownikach.
