### ISSUE TITLE
[Question]           regarding visable data and modules in portal

### ISSUE THREAD

**Issue by hoeyer** [YetiForceCompany/YetiForceCRM#10177]
Hi all,

within the user portal our customers will have access to way more information then we would wish.
Is it possible for us to limit the user access in the portal to  tickets and noting else really? just want them to be able to view ticket and add comments and so on.

thanks for your help.

**Comment by bpabiszczak** [comment]
You can disable this in the profile configuration

![image](https://user-images.githubusercontent.com/10197525/56509125-735abd80-6526-11e9-870f-d7fc5cb87ebe.png)

![image](https://user-images.githubusercontent.com/10197525/56509180-98e7c700-6526-11e9-9105-2a696cac05cd.png)

**Comment by hoeyer** [comment]
Thanks for your reply.

I found the profile section of the system, and have made a profile that should only have access to tickets within Yeti portal.

How do i go about assigning the profile created to portal user?

thanks for your help.

**Comment by hoeyer** [comment]
alright.
So i dont really understand how this works.

but creating a role under roles and assigning this to the profile then assigning the role to a user and then when creating the portal user, assigning my portal role/profile/user to that portal user gives the wanted result.

though when trying to edit og create a new ticket i get the following error.

**Comment by hoeyer** [comment]
Logo
Lasse Hansen
10500 Tandlægerne i Hørning

    Tickets

Logo
Lasse Hansen
10500 Tandlægerne i Hørning

    Tickets

Code: 8
Message: Undefined index: REFERENCED_MODULE_NAME
Backtrace: #0 /var/www/kundeportal/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php (123) >> content_5cb581740cd726_86847105()<br /> #1 /var/www/kundeportal/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php (114) >> Smarty_Template_Resource_Base->getRenderedTemplateCode()<br /> #2 /var/www/kundeportal/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php (206) >> Smarty_Template_Compiled->render()<br /> #3 /var/www/kundeportal/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php (365) >> Smarty_Internal_Template->render()<br /> #4 /var/www/kundeportal/cache/layouts/Default/b22aad96646e648e55dad1b9d1bb09b6b571f41b_0.file.EditView.tpl.php (41) >> Smarty_Internal_Template->_subTemplateRender('modules/Base/fieldtypes/Reference.tpl',NULL,NULL,0,3600,[object(YF\Modules\Base\FieldTypes\BaseField)],0,true)<br /> #5 /var/www/kundeportal/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php (123) >> content_5cb58174064b33_42211998()<br /> #6 /var/www/kundeportal/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php (114) >> Smarty_Template_Resource_Base->getRenderedTemplateCode()<br /> #7 /var/www/kundeportal/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php (206) >> Smarty_Template_Compiled->render()<br /> #8 /var/www/kundeportal/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php (232) >> Smarty_Internal_Template->render(false,1)<br /> #9 /var/www/kundeportal/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php (134) >> Smarty_Internal_TemplateBase->_execute(,NULL,NULL,NULL,1)<br /> #10 /var/www/kundeportal/app/Viewer.php (79) >> Smarty_Internal_TemplateBase->display('modules/Base/EditView.tpl')<br /> #11 /var/www/kundeportal/modules/Base/View/EditView.php (82) >> App\Viewer->view('EditView.tpl','HelpDesk')<br /> #12 /var/www/kundeportal/app/WebUI.php (67) >> YF\Modules\Base\View\EditView->process()<br /> #13 /var/www/kundeportal/public_html/index.php (28) >> App\WebUI->process()

**Comment by bpabiszczak** [comment]
We are just creating the customer portal2! It will be available in 2-3 weeks. You are trying to run unfinished versions.

**Comment by hoeyer** [comment]
Thats fair enough :-)

Thanks
