### ISSUE TITLE
[Feature]  Support options

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10171]
Would be nice if you guys can allow for :

- support micro package for 1 h (40 USD*) (some issues are too small to pay for 4 hours) - access must be prepared 
- priority support > question, advice, example (no access to customer server required) - 20 USD*

*suggested price but up to your consideration

**Comment by hoeyer** [comment]
I concur

**Comment by KatarzynaUlichnowska** [comment]
We already had a one-hour package, but it simply didn't work. In most cases, before we could log in to the server, more than 1-2 hours passed. People have huge problems with managing their servers and it is simply a waste of time for us. Secondly, most servers were misconfigured, and we couldn't fix an error until the configuration was correct (errors often result from wrong server configuration).

Błażej has an idea to offer support for YetiForce for 69 Euro per month ... then we will be able to help and solve problems with the system on a regular basis. Is this price alright or too high?

**Comment by hoeyer** [comment]
69€ for us sounds fair.

the price may vary depending on SLA.

Ofcourse, you should be able to expect the customer to at least configure the server correctly.

maybe you could consider making a package that can be bought and downloaded with VMWare guest / HyperV machine that has default configuration running and working with latest yetiforce and connected to github with one simple update script.

when we originally got started with Nextcloud, we didnt have much experience with linux, so we ended up buying a preconfigured Ubuntu machine from hansson IT.

https://shop.hanssonit.se/product-category/virtual-machine/

what they do, makes it extremely simple for people with minimal experince with linux to get up and running.

**Comment by paula-w** [comment]
Support packages will be built into the system (during installation and after installation you will be able to purchase tech support). It should solve most of the problems at the beginning.
