### ISSUE TITLE
[Question] Installation unsuccessful issue

### ISSUE THREAD

**Issue by GenCr** [YetiForceCompany/YetiForceCRM#10182]
Hi,

I'm trying to install YetiForce on a new CentOs 7 VM which I configured according to the instructions and web server requirements (Apache 2.4, MySQL 5.6, PHP 7.1). I configured most of the required parameters which are displayed as part of the installation process (missing a few of the security related ones). The installation works up until the last part (after entering the company details). When I click "Next", the page takes a couple of seconds to load but then I get a page that says "Installation unsuccessful" with no other details.

Could you please assist with troubleshooting and fixing?

Thanks,
Gen.

**Comment by vovpff** [comment]
I think problem in you server confifuration. Check it one more time

**Comment by GenCr** [comment]
What do I need to check for? There's no indication of what's wrong.

**Comment by rskrzypczak** [comment]
check if your database is empty

**Comment by rskrzypczak** [comment]
The database should be empty prior to installation of the system. 
Please empty the database and try again.

**Comment by GenCr** [comment]
Works now, thank you!

**Comment by adrianvanderwal** [comment]
I have a similar issue, however, my database is completely empty.
Recreating the database does not resolve the issue.

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.1.0 |
| Web server (name and version)|	Apache/2.4.29 (Ubuntu)	|
| PHP  | PHP 7.2.17-0ubuntu0.18.04.1								|
| Browser (name and version)  | Chrome Version 74.0.3729.157 (Official Build) (64-bit)		|
| Operating System (name and version)  | Ubuntu 18.04 (server), Ubuntu 19.04 (client)		|
| Database (name and version) | mysql  Ver 14.14 Distrib 5.7.26		|
| Database Default Charset | utf8 |
| Database Default Collation | utf8_generalci |

As an aside, I've also tried to set `output_buffering` to On, but it always reports as 1.

**Comment by rskrzypczak** [comment]
enable logs and run installation again
https://github.com/YetiForceCompany/YetiForceCRM/blob/cf9d56a7ca07755bce0601f022cac6cf3931aa8e/config/Debug.php#L20-L21
https://github.com/YetiForceCompany/YetiForceCRM/blob/cf9d56a7ca07755bce0601f022cac6cf3931aa8e/config/Debug.php#L41-L42

**Comment by adrianvanderwal** [comment]
I believe this is the applicable section of the log.

```log
2019-05-22 01:55:25.3499 [info][yii\db\Command::execute] - /*Table structure for table `a_yf_adv_permission` */

CREATE TABLE `a_yf_adv_permission` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `tabid` smallint(5) DEFAULT NULL,
  `status` tinyint(1) unsigned NOT NULL,
  `action` tinyint(1) unsigned NOT NULL,
  `conditions` text DEFAULT NULL,
  `members` text NOT NULL,
  `priority` tinyint(1) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `tabid` (`tabid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 
2019-05-22 01:55:25.3509 [error] - PDOException: SQLSTATE[42000]: Syntax error or access violation: 1142 CREATE command denied to user 'yeti'@'localhost' for table 'a_yf_adv_permission' in /var/www/yeti/vendor/ye$
Stack trace:
#0 /var/www/yeti/vendor/yetiforce/yii2/db/Command.php(259): PDO->prepare('/*Table structu...')
#1 /var/www/yeti/vendor/yetiforce/yii2/db/Command.php(1070): yii\db\Command->prepare(false)
#2 /var/www/yeti/install/models/InitSchema.php(81): yii\db\Command->execute()
#3 /var/www/yeti/install/models/InitSchema.php(22): Install_InitSchema_Model->initializeDatabase('install/install...', Array)
#4 /var/www/yeti/install/views/Index.php(307): Install_InitSchema_Model->initialize()
#5 /var/www/yeti/install/views/Index.php(112): Install_Index_View->step7(Object(App\Request))
#6 /var/www/yeti/install/Install.php(37): Install_Index_View->process(Object(App\Request))
#7 {main}
```
