### ISSUE TITLE
[BUG] Email Templates in roundcube show templates for all users !!!URG!!!

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#10183]
### Description
When creating an email templates and making them private they correctly works here
https://portal.hmcvanlines.ca/index.php?module=EmailTemplates&view=List
 (You cannot access the records of other users)
However it still accessible through the roundcube.

How to create a template so it will be available only for users it assigned to?

I did make changes here:
https://gitdeveloper.yetiforce.com/index.php?module=SharingAccess&parent=Settings&view=Index&block=1&fieldid=5

but this not working

**Comment by z0lo13** [comment]
@bpabiszczak any updates yet on that issue?

**Comment by z0lo13** [comment]
@mariuszkrzaczkowski @bpabiszczak please do not forget to include this commit as anyone from the system can use any templates which do not belong to them, or install roundcube plugin to have html signatures

**Comment by rskrzypczak** [comment]
1. https://github.com/YetiForceCompany/lib_roundcube/commit/10892a1b861bf3af90c73c26e9ef043bb10ca505
2. https://github.com/YetiForceCompany/YetiForceCRM/commit/4d53af6b00db04418c8ca256d3964439cade9e3c
