### ISSUE TITLE
PHP Notice:  Undefined index: action in /www/crm/include/utils/utils.php

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1018]
PHP Notice:  Undefined index: action in /www/crm/include/utils/utils.php on line 359
PHP Notice:  Undefined index: search in /www/crm/include/utils/utils.php on line 360
PHP Notice:  Undefined index: module in /www/crm/include/utils/utils.php on line 370
PHP Notice:  Undefined index: file in /www/crm/include/utils/utils.php on line 370

**Comment by bpabiszczak** [comment]
Duplicate: #981
