### ISSUE TITLE
[bug] Groups membership and calendar bug

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10188]
Calendar dont read records assigned to user which is assigned to particular group.
Let say: 
user1 is assigned to Group "Booking"
user1 create reservation entry

Admin (who is a top-level priviledged) selecting in Users window (Reservations right panel) Booking group and see no entries of user1.

Bug or wrong design?

**Comment by waran70** [comment]
Also sharing rules don't respect Group membership.

**Comment by bpabiszczak** [comment]
Make a video on gitdeveloper so that I can understand what you want to configure...
