### ISSUE TITLE
[bug] Mapping has bug

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10185]
1. Custom module with field 1:M (Accounts) - custom module have multiple 1:M fields with different names and labels.
2. Payments in module with custom field 1:M (Accounts)
Both fields have the same name and label.
Set mapping to those fields but it is never paired as expected. System chose always one field 1:M but not the one that was mapped.
It is obviously some bug as the designation of mapping function is invalidated

**Comment by waran70** [comment]
I need to add that it works IF the other field is empty. It means that Yetiforce prioritizing probably the first 1:M field created in the custom module.

**Comment by bpabiszczak** [comment]
Are there two fields 1: M [in one module] pointing to the same module ?
