### ISSUE TITLE
[bug] Quick edit not working for some of custom 1:M fields

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10187]
Got some custom 1:M fields in a custom module, some of them can be edited in detail view mode but some not, and I dont get why...

**Comment by bpabiszczak** [comment]
Probably because they are different types of boxes. Can you show such fields on gitdeveloper?

**Comment by svdaru** [comment]
As I understand, quick edit is not working at all for 1:M fields, isn't it?

**Comment by svdaru** [comment]
@bpabiszczak As I understand, quick edit is not working at all for 1:M fields, isn't it?

**Comment by paula-w** [comment]
This is @bpabiszczak 's response
Quick edit doesn't work for some field types. If someone orders further development of this functionality then we'll add it.
