### ISSUE TITLE
[Question] PDF report design

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10199]
Need to design nicely looking PDF report. RESERVATIONS > CUSTOM MODULE.
Related records needs to be nicely designed withing table/cells, records should be able to get wrapped in the cell (if too long), font needs to be clear but lightweight. 

How much?

**Comment by bpabiszczak** [comment]
You need to paste an example of how this PDF should look like. It would be good to describe every PDF element.

**Comment by JohnMaverick** [comment]
Basically, in related records if you can adapt PDFMaker (for vtiger) model, where each field of related table is represented by separate variable it will bring much easier design abilities. 
In PDFMaker  they call it RELATED BLOCKS and it looks like:

#PRODUCTBLOC_START# |  

| $PRODUCTPOSITION$ | $PRODUCTQUANTITY$ | $PRODUCTUSAGEUNIT$ | $PRODUCTNAME$ | 

 #PRODUCTBLOC_END#

**Comment by JohnMaverick** [comment]
They also uses mPDF library which gives better output.

**Comment by bpabiszczak** [comment]
https://user-images.githubusercontent.com/36499752/56420798-bc4d1080-629f-11e9-8ba7-19e23822bb37.gif

**Comment by vovpff** [comment]
@bpabiszczak looks like this but PDFMaker can pick up values directly from Products module instead products table in active advanced record.

**Comment by vovpff** [comment]
@bpabiszczak I checked gif at pull request. Will be cool if this will be available to save columns presets

**Comment by waran70** [comment]
Interesting but I have still limited understanding where it goes. Can you guys share more on that?

**Comment by mariuszkrzaczkowski** [comment]
@JohnMaverick 
we've recently introduced a lot of improvements in pdf, see for yourself
If you still have a problem with pdf, attach the file with the pdf template

@vovpff 
It is possible to save columns per record or generate without saving, massive from the list

**Comment by waran70** [comment]
Mariusz,  all cool, but we are pretty far from WYSWIG with PDF. Maybe it can start from setting related list fields in tables? Currently front-end design of related list is very limited. 
Maybe it will not be exhausting to allow simillar model as in PDFMaker (vtiger)?

#RELBLOCK19_START#
$cf_1246$ $cf_893$ $projecttaskname$ $startdate$ $enddate$ $projecttaskstatus$ 
#RELBLOCK19_END#

In this case every single field of related list can be fitted in different cell of table. This actually will turn most of the things on WYSWIG path. If you asses that this could be achievable in some reasonable time (best before next release) we may start begging for donations, so less pain ;-)
