### ISSUE TITLE
PHP Notice:  Undefined index: action in /www/crm/include/utils/ListViewUtils.php

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1019]
PHP Notice:  Undefined index: action in /www/crm/include/utils/ListViewUtils.php on line 625
PHP Notice:  Undefined index: file in /www/crm/include/utils/ListViewUtils.php on line 625

**Comment by bpabiszczak** [comment]
Duplicate: #981
