### ISSUE TITLE
[Feature] values summary in pdf report

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10206]
How to sum all values in a column in pdf report? PDFMaker for vtiger provides relevant function.
Maybe some way around?

**Comment by bpabiszczak** [comment]
Can you paste an example?

**Comment by JohnMaverick** [comment]
![image](https://user-images.githubusercontent.com/29787568/56552078-510f8100-65b4-11e9-972d-3accd4b5c21c.png)

**Comment by bpabiszczak** [comment]
You have to write a custom function.
