### ISSUE TITLE
[Question] Parsing variables          

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10205]
Hi, can you guys provide documentation related to:

$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]|)$

parameters: ModuleName|Columns|Conditions|CustomViewIdOrName|Limit

For instance, I have no clue how to use "Conditions" or "Limit"
Searched everywhere but it not described at all.

**Comment by konadrian** [comment]
Limit is like limit in sql it will show only 2 records achive requirements, conditions is like a filter for example give me contacts where name contains "Tom"
