### ISSUE TITLE
PHP Notice:  Undefined variable: where in /www/crm/modules/OSSMail/models/Record.php

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1020]
PHP Notice:  Undefined variable: where in /www/crm/modules/OSSMail/models/Record.php on line 28
PHP Notice:  Undefined index: modifiedtime in /www/crm/modules/Users/models/Record.php on line 152
PHP Notice:  Undefined index: modifiedtime in /www/crm/include/runtime/BaseModel.php on line 31
PHP Notice:  Undefined variable: where in /www/crm/modules/OSSMail/models/Record.php on line 28
PHP Notice:  Undefined property: OSSMailScanner::$column_fields in /www/crm/modules/Vtiger/models/Record.php on line 255

**Comment by bpabiszczak** [comment]
Duplicate: #981
