### ISSUE TITLE
[Question] How to add new icons font?     

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#10202]
### Description

How i can add a new font to menu icon selector?

**Comment by mariuszkrzaczkowski** [comment]
You can add a new font to the array, but this change will be overwritten during the upgrade
https://github.com/YetiForceCompany/YetiForceCRM/blob/fb44a998149386e431ab8aacb8bd6cdc143b055c/modules/Settings/Vtiger/models/Icons.php#L21

**Comment by cltvchannel** [comment]
Ok. Thanks !
