### ISSUE TITLE
[Feature]  Navigation in detail view

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10219]
In record detail view there are no navigation buttons, which basically is a pretty common, necessary and logical way of working on databases records.
What I do is changing the number in the browser address bar. It is not very comfortable, is it?
Can it be added?
![buttons](https://user-images.githubusercontent.com/29787568/56453429-c1c45c80-636c-11e9-96fd-dcd32314fa49.png)

**Comment by mariuszkrzaczkowski** [comment]
Ideal notice but not simple to do.
Switching must include the set filters in the record list, and when someone entered the record from the link not a list.

**Comment by vovpff** [comment]
I remember how strange this works in VT. John, try records preview
