### ISSUE TITLE
[bug] PDF don't remember page layout and

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10212]
Created template but PDF don't remember the layout and what is the most important don't print records in list (in table, but each record on a separate page.
Am I missed something?

You can check it here: https://gitdeveloper.yetiforce.com/index.php?module=PaymentsIn&view=List&mid=72&parent=71

**Comment by davide-alghi** [comment]
About records into pdf, this could help you

![PdfRecords](https://user-images.githubusercontent.com/48508691/56420304-b9e9b700-629d-11e9-87a8-9463f85a40e4.jpg)

**Comment by JohnMaverick** [comment]
Nope. I mean, I have one module, and I want to list in pdf records from this module. Super basic need - like export to excel.

**Comment by JohnMaverick** [comment]
For instance function: $(recordsList : PaymentsIn)$ generating as many pdf's as there is records selected and on each page list of all of those records. This is obviously a bug

**Comment by konadrian** [comment]
![image](https://user-images.githubusercontent.com/3193498/61511833-4bc9a300-a9f8-11e9-9fce-8d1f95baf567.png)
It was fixed

**Comment by waran70** [comment]
konradian, can you get me link to this fix?
Cheers
