### ISSUE TITLE
[bug] PDF Stopped respecting currency Sign Before the Amount in Product table.

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#10226]
# 🐞 bug report

### ⁉️ Describe the bug
When choosing the Currency Sign to Appear **Before** the value, around the system it does work okay, but when generating PDF it is broken.
1. (https://user-images.githubusercontent.com/23143958/56473959-8dfa3d00-6427-11e9-9adb-409a55747a17.png)

2. Broken PDF from Gitdeveloper.
(https://user-images.githubusercontent.com/23143958/56473982-cf8ae800-6427-11e9-8e0c-1fa6a260a877.png)

### 🔥 How to trigger the error

1. Go to 'https://gitdeveloper.yetiforce.com/index.php?module=FInvoice&view=Detail&record=3617'
2. Click on 'Generate'
3. See error

### 👎 Actual Behavior
$ Sign Before Value Everywhere

### 👍 Expected Behavior
$ sign placed before and after in some cells.

### 📷 Screenshot of configuration

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce	GitDeveloper		|     GitDeveloper

### ❓ Additional context
My production 5.0.0 Have same Issue. I dont know when this issue started but i guess it has been working fine only in 4.4.0. Please Fix It as soon as possible it is crucial for some countries. In addition it is just a mess in invoice with two different symbol placements.

**Comment by z0lo13** [comment]
@bpabiszczak Any updates? System not usable for north american invoices, pease hotfix it.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/10458

**Comment by konadrian** [comment]
It's fixed by commit above
