### ISSUE TITLE
[Question] How to add tabs in custom modules ????????

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#10228]
i want to add "tabs" in my custom modules like in regular modules, i did it in Yeti Version 4.4 but now in 5.1 i cant find how to do it. 

i cant seem to apply what is shown in the first picture to the second one.

What i want to put in my custom modules = 

![leads](https://user-images.githubusercontent.com/45770116/56478969-8f0b8880-6480-11e9-8e15-f330a3ea1222.PNG)

and here is my custom modules = 

![custom module](https://user-images.githubusercontent.com/45770116/56478979-9af74a80-6480-11e9-8f7a-1ba7360290bc.PNG)

**Comment by vovpff** [comment]
The same way as in 4.4. At first  you need to activate ability to add relations in system config files. After that go to 'Standart modules - > Reldtions' .

**Comment by maeglin4** [comment]
what system config file ?

**Comment by maeglin4** [comment]
okay thanks, found it
