### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1022]
I'm don't have experience in webservers. I have some skills but this skills too small to solve this.

Yesterday I established fresh apache 2.4 with latest versions of PHP 5.6.9 and MySQL. After installation   I was redirecter to "My home page". Every click to any module returns the next error message "CSRF protection: Hacking attempt detected" with two bottons: "Go Back" and "Home page". "Go Back" botton return me to "My home page". Clicking to "Home pade" don't start any actions?

How to solve it? 
![image](https://cloud.githubusercontent.com/assets/8545791/8000587/622555c6-0b65-11e5-8366-b3c18707e7bf.png)

**Comment by waw555** [comment]
Clicking on links should be carried out only with the root of the site, the transition from the outside is not allowed.

**Comment by vovpff** [comment]
What you mean?

**Comment by waw555** [comment]
I think the problem is related to the localhost, maybe not correctly prescribed path.

I had a problem as long as / etc / apache2 / sites-aviable not prescribed the right track and create a symbolic link

**Comment by bpabiszczak** [comment]
Please check $site_url In config/config.inc.php

**Comment by waw555** [comment]
Else check $site_url in config/config.inc.php

**Comment by vovpff** [comment]
Thanks guys! It's works! I fount unnecessary slash in site url. Sorry for attention. This is my mistake.
