### ISSUE TITLE
change layout for custom module 

### ISSUE THREAD

**Issue by cosmibota** [YetiForceCompany/YetiForceCRM#10225]
How can I change the layout for custom module? I want 2 columns in summary view.

**Comment by vovpff** [comment]
Let's put widgets to 2 columsns from admin menu

**Comment by bpabiszczak** [comment]
![Untitled Project](https://user-images.githubusercontent.com/10197525/56506068-b2d0dc00-651d-11e9-85ac-cafbd21b4100.gif)
