### ISSUE TITLE
[bug] or [Question] $(custom : ProductsTableRelatedModule)$ does not show any values ?

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#10227]
# 🐞 bug report

### ⁉️ Describe the bug
$(custom : ProductsTableRelatedModule)$
not showing any custom values from related modules

### 🔥 How to trigger the error

1. Go to 'https://gitdeveloper.yetiforce.com/index.php?module=Accounts&view=Detail&record=115'
2. Click on Generate PDF
3. Click Generate
4. See Empty PDF file

### 📷 Screenshot of configuration
GITdeveloper

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
GITdeveloper

### ❓ Additional context
No information how to use it

**Comment by vovpff** [comment]
I'm not sure but this function should call products table from related IGDN to active IGDNC
