### ISSUE TITLE
Edit Language Endless Loading

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1023]
Tried to edit language and i am getting endless loading.
![endless loading translation](https://cloud.githubusercontent.com/assets/6897502/8002879/f6e4182c-0b7a-11e5-89da-84ae13a74638.jpg)

**Comment by 1250572980** [comment]
I meet this problem too,but 2.0.0 RC no this problem

**Comment by bpabiszczak** [comment]
Please check test version. What version you have?

**Comment by 1250572980** [comment]
![snip20150605_1](https://cloud.githubusercontent.com/assets/12697896/8005270/a0e46a9a-0bba-11e5-97d5-d9561bab6406.png)

**Comment by 1250572980** [comment]
![snip20150605_2](https://cloud.githubusercontent.com/assets/12697896/8005282/ce94d9de-0bba-11e5-8ca7-89fc51063050.png)

**Comment by bpabiszczak** [comment]
Please clear browser cache and please check test version.

**Comment by eptapsyxos** [comment]
cache cleared the problem remains.
Test version works like a charm.
I ll go for fresh install and i wil reply to you
