### ISSUE TITLE
[Question]  Limitation of scheduled workflows

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#10236]
Hello there,

    I have a limitation of how many workflows i can create. The problem is that i need more than 10 (i guess this is the maximum limit). 
   How can i create more scheduled workflows ?

**Comment by konadrian** [comment]
We deleted  limit of scheduled workflows
https://github.com/rskrzypczak/YetiForceCRM/commit/b57a451c107bbb68c5c71016f9e5052df3869431
