### ISSUE TITLE
Partnership Programs 🤝🏻

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#10233]
Hello everyone!

We just launched our **partnership programs**, you can find them here: https://yetiforce.com/en/yetiforce/partnership-programs 

Please let us know what you think, we're looking forward to your feedback. If you'd like to become our Partner but some of  the Rules/Benefits/Costs are not clear, or would stop you from becoming our Partner also let us know, we're open to suggestions and ideas.

Thanks!

**Comment by elvissaba** [comment]
If you plan to have more partners per country/region, in go-go stage of bussiness developement, participation for resseller should not pay any fee. With 100EUR fee and 10% discount you set target of 1000EUR sales worth per month (earnining =0)

**Comment by z0lo13** [comment]
how reseller should sell an open source system? you mean selling the support?

**Comment by elvissaba** [comment]
Read benefits and cost in program description
