### ISSUE TITLE
You don&#039;t have the permissions required to view/edit this record. Contact the administrator if you should have the permission to view it.

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10230]
# 🐞 bug report

I have given all permission to users but user can not able to edit records of others that time users  getting below error "You don&#039;t have the permissions required to view/edit this record. Contact the administrator if you should have the permission to view it".Actually they have all permission to edit and create and view permission.
![Permission](https://user-images.githubusercontent.com/47585969/56555200-81b4e200-65d7-11e9-87be-415e11fe0f0b.JPG)

Note:Here one bug there when ever user getting this error that time  i have edit user profile and i made little bit changes (like add or remove Other event duration (mins)) in that user profile. after changes usre profile user can not getting  " "You don&#039;t have the permissions required to view/edit this record. Contact the administrator if you should have the permission to view it"" error .they can able to edit records of others . users getting this problem every 2 or 3 days once. 

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.1
| Web server (name and version)|	Apache	|
| PHP  |		7.1.x, 7.2.x, 7.3.x (dev)						|
| Browser (name and version)  | 	google chrome	|
| Operating System (name and version)  | 	Windows	|
| Database (name and version) | 	mysql	|

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/56555512-8062c580-6595-11e9-9127-0e364ef83cb0.jpg)

**Comment by guide5232** [comment]
# 🐞 bug report


I have given all permission to users but user can not able to edit records of others that time users  getting below error "You don&#039;t have the permissions required to view/edit this record. Contact the administrator if you should have the permission to view it".Actually they have all permission to edit and create and view permission.
![Permission](https://user-images.githubusercontent.com/47585969/56555200-81b4e200-65d7-11e9-87be-415e11fe0f0b.JPG)


Note:Here one bug there when ever user getting this error that time  i have edit user profile and i made little bit changes (like add or remove Other event duration (mins)) in that user profile. after changes usre profile user can not getting  " "You don&#039;t have the permissions required to view/edit this record. Contact the administrator if you should have the permission to view it"" error .they can able to edit records of others . users getting this problem every 2 or 3 days once. 



### ⁉️ Describe the bug






### 🔥 How to trigger the error


Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### 👎 Actual Behavior


### 👍 Expected Behavior


### 📷 Screenshot of configuration


### 📝 PHP/Apache/Nginx/Browser/CRM Logs



### 🌍  Your Environment 



| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0
| Web server (name and version)|	Apache	|
| PHP  |		7.1.x, 7.2.x, 7.3.x (dev)						|
| Browser (name and version)  | 	google chrome	|
| Operating System (name and version)  | 	Windows	|
| Database (name and version) | 	mysql	|

### ❓ Additional context
Add any other context about the problem here.

**Comment by guide5232** [comment]
Please don't ignore it.this thing is happening in only one role

**Comment by mariuszkrzaczkowski** [comment]
🔥 How to trigger the error
📷 Screenshot of configuration
📝 PHP/Apache/Nginx/Browser/CRM Logs

**Comment by guide5232** [comment]
Please check it 
[_Importer.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3106087/_Importer.log)
[_system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3106088/_system.log)

[_updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3106089/_updateLogsTrace.log)
[Importer.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3106090/Importer.log)
[php.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3106091/php.log)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3106092/system.log)

[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3106093/updateLogsTrace.log)


[_errors.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/3106100/_errors.txt)
[errors.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/3106179/errors.txt)

**Comment by vovpff** [comment]
Cron enabled?

**Comment by guide5232** [comment]
Yes enabled

**Comment by KatarzynaUlichnowska** [comment]
Hello, as our dev requested more info and you ignore his requests please record a video on our GitDeveloper version where you will show what the problem is. Once we see it, we will be able to tell you what was misconfigured.

**Comment by manwenick** [comment]
Hello @guide5232 !
Did you solve this problem? 
I have the same problem on my system in module projects. 
I gave all permissions to the user, But the user receive this error. 
My cron is even enabled, all configs are fine. I don't understand it too. 
What do you use as a web server apache or nginx?
Kind regards!

**Comment by snenko** [comment]
I have the same problem

**Comment by snenko** [comment]
I fount the reason why is "Permission denied".
I think the problem when a role is saving several profiles.

I separate profiles by functionality: knowledgebase and Passwords
And If "Passwords Profile" will be after knowledgebase so "Passwords Management" will be locked.

![image](https://user-images.githubusercontent.com/11363876/76154204-269db800-60e1-11ea-813b-45e07f8f8205.png)


The solution is: combine all permission in one profile for one role.

**Comment by manwenick** [comment]
> 
> 
> I fount the reason why is "Permission denied".
> I think the problem when a role is saving several profiles.
> 
> I separate profiles by functionality: knowledgebase and Passwords
> And If "Passwords Profile" will be after knowledgebase so "Passwords Management" will be locked.
> 
> ![image](https://user-images.githubusercontent.com/11363876/76154204-269db800-60e1-11ea-813b-45e07f8f8205.png)
> 
> The solution is: combine all permission in one profile for one role.

Hi @snenko ,
I just tried to change the permissions in the way you described it. It worked for me! 
Question to @mariuszkrzaczkowski @KatarzynaUlichnowska is it normal behavior of the permission model? Or is it a bug?
