### ISSUE TITLE
Where this filter is modified services

### ISSUE THREAD

**Issue by inser2** [YetiForceCompany/YetiForceCRM#10240]
Having a large volume of products, I need to be able to filter through other fields, but I do not know where I should modify them.

![Snap_2019 04 17_16h19m51s_001_](https://user-images.githubusercontent.com/48966411/56620744-3ed02a00-662a-11e9-80b1-870f6a171f7d.jpg)

**Comment by vovpff** [comment]
@inser2 you need to modify this file

https://github.com/YetiForceCompany/YetiForceCRM/blob/ad231fddfe9f0b3a7c198ce4bd2f9dff7bd7b45b/modules/Products/Products.php#L40

**Comment by vovpff** [comment]
Te same file you can find for services

**Comment by inser2** [comment]
Thank you
