### ISSUE TITLE
[PL][BUG] Widok tygodniowego kalendarza a dłuższe zadanie

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1024]
Załóżmy, że poniedziałek to 1 dzień miesiąca. Przy utworzeniu wpisu który trwa od 1 do ~17 (obejmuje zakresem więcej niż 3 tygodnie włącznie) to przy widoku tygodnia i wybraniu zakresu dat od 8 do 14 wpis nie jest wyświetlany.

Prościej mówiąc - wpis wyświetla się tylko w wtedy jeśli zaczyna lub kończy się w wybranym tygodniu.
Sprawdziłem jeszcze i taka sama sytuacja jest z dniem i miesiącem (jeśli zadanie obejmuje dany dzień/miesiąc ale nie zaczyna lub kończy się w nim to nie wyświetla się.

**Comment by MaciejStencel** [comment]
Problem został opisany i rozwiązany w tym zgłoszeniu:
https://github.com/YetiForceCompany/YetiForceCRM/issues/1045
