### ISSUE TITLE
[PL] Fakturowanie - kilka pytań

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1025]
Chciałbym się dowiedzieć czy moduł Faktur dostosowywaliście do polskich warunków/przepisów, ew. przewidujecie takie prace ?
Co z fakturami korygującymi i zaliczkowymi - te dokumenty mają określoną formę, numerację i powiązanie z fakturą oryginalną. Czy teraz można wygenerować te dokumenty w systemie ?

**Comment by bpabiszczak** [comment]
przy niewielkiej energii faktury sprzedażowe, zakupowe i proforma można z systemu generować. Obecnie nie ma faktur zaliczkowych i korygujących, w planach mamy dodanie tych funkcjonalności.

**Comment by florek41** [comment]
Wracając do tematu - jakieś nowe, dobre wieści ? :)
Jeśli prowadzenie normalnej działalności z możliwością zaliczek, korekt i polskich faktur będzie bezproblemowe to myślę, że dla większości polskich użytkowników nie będzie konkurencyjnego systemu.

Druga, powiązana sprawa - import danych z GUS - jest szansa na ten moduł dla YF ?

**Comment by bpabiszczak** [comment]
Trzeba myśleć optymistycznie :] 
Dużo modułów księgowo/finansowych powinno przyjść razem z wersją 2.5.
