### ISSUE TITLE
UI Upgrade (Ideas for Discusion)

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1026]
Hello again.
Because i believe the User Interface of yetiforce is the most weak point of the crm
and simultaneously i understand that is difficult to change the core files,because of the dependcy from the Vtiger
 i ve photoshoped some changes that i believe(i dont have any idea from coding)
that is more easy to accomplished with the existing elements.

My target is to 
1)Reduced Clicks
2)Highlight Important Elements
3)The User to have the lowest number of changing pages.
4)To have an overall View 360 Degree as possible.

Until we have this Result---->
(Take a look to the Future)
https://wrapbootstrap.com/themes/admin
and this is the most POWERFULL Template i found on the net
http://www.keenthemes.com/preview/metronic/start.html

I ve made something Like This
![ui-clear-jpg-final](https://cloud.githubusercontent.com/assets/6897502/8025357/4b124a12-0d5c-11e5-85de-3c5305740813.jpg)

and i am explaing below:
![ui-additions-withouts-details](https://cloud.githubusercontent.com/assets/6897502/8025359/5bddbfa2-0d5c-11e5-89d9-3f13c0041168.jpg)

Please Bring Mobility and Simplicity on Yeti.....
Now we can use it only Desktop or Laptop.

Any Ideas we can discuss it here,So do not Rush to close the thread Because i want to re-post here
my other ideas about Ui.

**Comment by waran70** [comment]
very interesting

**Comment by eptapsyxos** [comment]
Photo Of User On List View 

![photouser](https://cloud.githubusercontent.com/assets/6897502/8104893/195f28e4-103d-11e5-91df-e2b4ea1d43ed.jpg)

**Comment by bpabiszczak** [comment]
I do appreciate your attempt to encourage the discussion. However, before it will make any sense, we have to send you our vision of how the system will work and look. Then we will be able to discuss what is wrong, what would you like to change and improve. Every new interface will be added to GitHub and an issue will get a "discussion" tag and you will be able to add your ideas.

Your suggestion doesn’t solve anything, you just add some info that already is in the system but requires to be enabled and then it will appear, but it doesn't make the system more legible. Additionally, I consider some of the ideas as unjustified. I’m going to close this issue for now, soon we will add a new issue. Please be patient :)

**Comment by eptapsyxos** [comment]
Ok bpabiszczak.I would like to share your ideas about the UI with me and the community.
So you will post ''the vision'' of the feature of yetiforce.?
A roadmap maybe(example here  http://zurmo.org/roadmap )?
Or a Poll with upcoming enchacments(after member proposals and admins),so we can vote or discuss etc.?

Thank you very much.sorry if i did something wrong
but really i want to see this project to be the first on the world.

**Comment by bpabiszczak** [comment]
So you will post ''the vision'' of the feature of yetiforce.?

YES

**Comment by KatarzynaUlichnowska** [comment]
1. Soon we will present you the first drafts of the Customer Portal. When we publish them, you will have an opportunity to express your opinion and make remarks. If we consider them as reasonable, we will accept them and make changes.
2. The plan is to redesign the entire interface of our CRM and Customer Portal, it should take us about 8 months.
3. If you need some changes, add an issue to GitHub. We make changes that are considered to be priorities for us and for our customers. If you want us to consider your suggestions, please add them to GitHub. There is no point in creating a Poll, we don’t have such a large community.
