### ISSUE TITLE
[bug] Roundcube Errors

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#10279]
Hello , in roundcube i only have 2 users that are able to use the mailbox, so while i was going into the setting to figure out why other employees cant connect, i came face to face with 2 error messages.

**First Error** : 
- in modules installation
- click on "module configuration" of "my mailbox"

![error1](https://user-images.githubusercontent.com/45770116/56851706-25f09e80-68e0-11e9-9046-74eded6f710d.PNG)

**and the error message is :** 
Incorrect value detected, please contact your administrator

#0 [info] SHOW FULL COLUMNS FROM `l_yf_settings_tracker_basic` || yii\db\Command::query
#1 [info] Opening DB connection: mysql:host=localhost;dbname=expertcloud_y952;port=3306 || yii\db\Connection::open
#2 [info] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'l_yf_settings_tracker_basic' AND kcu.table_name = 'l_yf_settings_tracker_basic' || yii\db\Command::query
#3 [info] INSERT INTO `l_yf_settings_tracker_basic` (`user_id`, `type`, `module_name`, `record_id`, `date`, `action`) VALUES (5, 1, 'OSSMail', 0, '2019-04-27 11:34:03', 'View:Index') || yii\db\Command::execute
#4 [info] SHOW FULL COLUMNS FROM `u_yf_browsinghistory` || yii\db\Command::query
#5 [info] Opening DB connection: mysql:host=localhost;dbname=expertcloud_y952;port=3306 || yii\db\Connection::open
#6 [info] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'u_yf_browsinghistory' AND kcu.table_name = 'u_yf_browsinghistory' || yii\db\Command::query
#7 [info] INSERT INTO `u_yf_browsinghistory` (`userid`, `date`, `title`, `url`) VALUES (5, '2019-04-27 11:34:03', 'My mailbox System settings', 'index.php?module=OSSMail&amp;parent=Settings&amp;view=Index&amp;block=4&amp;fieldid=') || yii\db\Command::execute
#8 [info] SELECT * FROM `vtiger_links` || yii\db\Command::query
#9 [info] SELECT * FROM `vtiger_tab` || yii\db\Command::query
#10 [info] SELECT * FROM `vtiger_entityname` || yii\db\Command::query
#11 [info] SELECT * FROM `u_yf_browsinghistory` WHERE `userid`=5 ORDER BY `id` DESC LIMIT 20 || yii\db\Command::query
#12 [info] SELECT * FROM `vtiger_actionmapping` || yii\db\Command::query
#13 [error] ERR_NOT_ALLOWED_VALUE||fieldid||
App\Exceptions\IllegalValue: ERR_NOT_ALLOWED_VALUE||fieldid|| in app/Request.php:203
Stack trace:
#0 modules/Settings/Vtiger/views/Index.php(71): App\Request->getInteger('fieldid', false)
#1 modules/Settings/Vtiger/views/Index.php(51): Settings_Vtiger_Index_View->preProcessSettings(Object(App\Request))
#2 include/main/WebUI.php(262): Settings_Vtiger_Index_View->preProcess(Object(App\Request))
#3 include/main/WebUI.php(182): Vtiger_WebUI->triggerPreProcess(Object(Settings_OSSMail_Index_View), Object(App\Request))
#4 index.php(24): Vtiger_WebUI->process(Object(App\Request))
#5 {main}

______________________________________________________________________________________________________

**Second error**
- in "security" click on "Mail - Download history"
![error 2](https://user-images.githubusercontent.com/45770116/56851743-a911f480-68e0-11e9-8ad1-d427b6d374f3.PNG)

**and the error message is :**
 
LBL_HANDLER_NOT_FOUND

#0 [error] Error Vtiger_Loader::getComponentClassName(View, logs, Settings:OSSMailScanner): Handler not found
#1 [error] LBL_HANDLER_NOT_FOUND
App\Exceptions\AppException: LBL_HANDLER_NOT_FOUND in include/Loader.php:169
Stack trace:
#0 include/main/WebUI.php(158): Vtiger_Loader::getComponentClassName('View', 'logs', 'Settings:OSSMai...')
#1 index.php(24): Vtiger_WebUI->process(Object(App\Request))
#2 {main}

Environment | Version / Name
-- | --
YetiForce | 5.1.0
Web server | Apache
PHP | 7.1.28
Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
Operating System | Linux  3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64
Database | mysql \| 5.5.5-10.2.23-MariaDB \| mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

**Comment by mariuszkrzaczkowski** [comment]
Each error reported. If your system was updated? It looks like it to mislead updates.
calls to these errors on the gitdev version

**Comment by maeglin4** [comment]
no update, its a fresh update

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version

**Comment by konadrian** [comment]
I closed the issue because we've waited too long for an answer
