### ISSUE TITLE
Update from 4.4 to 5.0 Failed

### ISSUE THREAD

**Issue by Nugroho777** [YetiForceCompany/YetiForceCRM#10283]
Hi,

I am now using YetiForce version 4.4 and have problem when trying to update to 5.0.
System settings > Standard modules > Module - Installation > Install from file > Appear alarm:

**Upload limit is too small
Upload limit is too small (%s) so the file cannot be uploaded to the server. It is recommended to check the system configuration <a href="index.php?parent=Settings&module=ConfReport&view=Index">Sprawdź konfigurację serwera</a>**

After I keep try to upload/import zip file 4.4.0_to_5.5.0_v4, then after uploading 100% error message:

**Error!!!
Invalid request - Response For Illegal Access
[Go back] [Home page]**

Can someone advise me the solutions for above problems?

Thanks
NR

**Comment by vovpff** [comment]
Try to go to updates history and use upload update button

**Comment by mariuszkrzaczkowski** [comment]
attach a dump from configuration verification, the message says that some configuration limit is too small and can not process the entire file

**Comment by konadrian** [comment]
I closed the issue because we've waited too long for an answer
