### ISSUE TITLE
ADD BUTTON EXPORT PDF

### ISSUE THREAD

**Issue by inser2** [YetiForceCompany/YetiForceCRM#10280]
I have created a module and I would like to be able to export the data in pdf, but I do not know how to do it.
![Snap_2019 04 27_17h42m09s_001_](https://user-images.githubusercontent.com/48966411/56852040-155b1b00-6916-11e9-9262-08a0c5b3fbe0.jpg)

**Comment by vovpff** [comment]
You need to add some pdf template for this module by admin panel
