### ISSUE TITLE
[bug] Vtiger_Record_Model in scheduler 

### ISSUE THREAD

**Issue by asyven** [YetiForceCompany/YetiForceCRM#10281]
# 🐞 bug report
### ⁉️ Describe the bug
I want to use Vtiger_Record_Model::getCleanInstance in cron scheduler, but this class isn't in crm classes scope.
Fatal error: Uncaught Error: Class 'Vtiger_Record_Model' not found
### 🔥 How to trigger the error
1. Create cron task
2. Call Vtiger_Record_Model::getCleanInstance("CallHistory") (for example)
3. Wait when cron will starts

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Fatal error: Uncaught Error: Class 'Vtiger_Record_Model' not found
 
 ### ❓ Additional context
Do I need to "require" something?
Or just use raw sql queries?

**Comment by mariuszkrzaczkowski** [comment]
show sample file

**Comment by konadrian** [comment]
I closed the issue because we've waited too long for an answer
