### ISSUE TITLE
[bug] workflow on creation doesn't work

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10295]
Created workflow for invoice to prefill some fields uppon invoice creation. Checked one-by-one and it not updating any field on creation.

**Comment by vovpff** [comment]
usually workflow starts after saving (creation/modification) of record

**Comment by JohnMaverick** [comment]
Not really, we have two trigerring versions:
1. Creating record
2. Every time a record is saved (eg. creating, modifying)

The first should be triggered while creating record? It means that when you click create record, it will popup with prefilled fields (for instance)

**Comment by vovpff** [comment]
@JohnMaverick no. You has misunderstanding of this mechanism
`Creating record` works only after first save. Save means clicking `Save` button
`Every time a record is saved (eg. creating, modifying)` works after every clicking save. In this case `Save means clicking `Save` button or editing some field from detail view.
