### ISSUE TITLE
[Feature] Editing record from list view

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10294]
When I click a little icon/button to edit the record from the list view (in the set of little actions buttons) it open record for editing. Once I save record it stays in Detail View. Logically it should return to list view-especially that navigation buttons are not planned at the moment.
Action buttons should allow for easy and fast interaction with records

**Comment by LaurensCleyman** [comment]
Do you mean like this:

![inline](https://user-images.githubusercontent.com/16014524/60666043-5fa4cf00-9e66-11e9-98f4-34d450645fd6.png)

In Vtiger it is possible to triple click a record to edit in list view. Should be nice to have the same functionality in YetiForce! :-)

**Comment by paula-w** [comment]
This is @bpabiszczak 's answer:
If we collect enough money on OpenCollective or a client orders this functionality we will definitely add it.
