### ISSUE TITLE
[Question]   Picklists and additional fields 

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10293]
When editing picklists  I can see additional 2 fields Description ad Prefix.
What is this for and how to use it?

**Comment by konadrian** [comment]
1 - Value description will display information in the progress bar if you pick the "visible in preview headers" option as progress bar. You'll be able to see a description next to the picklist value that you set in record preview

2 - Prefixes are used to set record numbering. When you choose picklist in record numbering then, once you pick certain picklist value, it will be added to the "record number" field. 


![Picklist_prefix](https://user-images.githubusercontent.com/3193498/61432157-d2ff1400-a92f-11e9-9c99-eb5ac0ed9fe7.png)
![PIcklist_description](https://user-images.githubusercontent.com/3193498/61432168-dabeb880-a92f-11e9-9e08-7e51c7f81ab8.png)
