### ISSUE TITLE
[PL][Pytanie] Roundcube - zarządzanie Tożsamościami

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10298]
Witam,

Chciałem zapytać czy jest możliwe ustawienie domyślnych tożsamości w odpowiedzi na przykład na konkretne maile?  Czyli żeby dla maila abc@mail.com zawsze odpowiadał z Tożsamości: test@mail.com.

v5.0.0 Complete

**Comment by bpabiszczak** [comment]
W systemie jest wbudowany mechanizm, który:

1. Przy odpowiedzi na maila ustawia maila na którego przyszedł mail na który odpowiadamy [tak jak w Outlook]
2. Jest możliwość ustawienia maila w zależności z jakiego modułu odpisujemy np. klikając w Zgłoszeniu "odpowiedź", wówczas domyślnie ustawi nam maila pomoc@yetiforce.com.

Innych mechanizmów nie ma, ale bez problemu można je dodać.
