### ISSUE TITLE
[bug] Sum fields from related module doesnt seems to be working for invoices

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#10300]
get it updated on the creation of invoice but not on invoice deletion. The issue mentioned here: https://github.com/YetiForceCompany/YetiForceCRM/issues/7307 probably fixed Payments, but it still hanging on invoices.

**Comment by cltvchannel** [comment]
@JohnMaverick To make this working, you need to create same workflow with execution when "Deleting record".

**Comment by JohnMaverick** [comment]
Thanks
