### ISSUE TITLE
Branches Developer

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1030]
What do the following branches and where to get the latest changes?

LAB-AK
LAB-MS
LDB-RS

**Comment by bpabiszczak** [comment]
Let’s assume there are only two branches:

1. master – main, production so if someone wants to upload an amendment, he does it when it appears on a master branch.

2. developer - initially verified [when we commit to master we verify it more thoroughly].

3. LAB-XX – means laboratory versions of particular employees who work on large changes, e.g. look at LAB-RS, he has been working on Bootstrap 3.3.4 update for over two weeks and there are so many changes (that mess up the system) that they need to be uploaded to one location first and when Radek finishes it, all of the changes will be verified and uploaded to developer branch and then to master. LAB versions will only be used by developers who work on something for a few days and uploading these parts would result in problems with the system.
