### ISSUE TITLE
[Question] CalDAV or CardDAV on iOS error

### ISSUE THREAD

**Issue by SALITEL** [YetiForceCompany/YetiForceCRM#10318]
### Description

I can not configure CardDav and CalDav on iOS. I have reviewed all the issues (open and close) and I have not found a solution.

The GitDeveloper installation works correctly and the result of the screen is the same as mine.

The account configuration in iOS is correct but does not synchronize the calendar or contacts.

It also does not work in Thunderbird.

### Versions
YetiForceCRM: **5.1.0** (Clean install 5.0.0 and updated to 5.1.0 no errors)
PHP: **7.3**

### Log files
**/cache/logs/davException.log:**
https://docs.google.com/document/d/17IrCxwQq8hy8pEqN-EnLAdhZ-GmbRZaUuvpfwI_DR2w

**/cache/logs/davDebug.log**:
https://docs.google.com/document/d/1PNy1fZ4MnOPy4BPppCHJd7zwWhPm7TxcWRJMjn-dvFw

**Log Thunderbird**:
URL:
https://yf.dominio.com/dav.php/addressbooks/demo/YFAddressBook/ (REPORT)

Request:
<card:addressbook-multiget xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:prop><d:getetag /><card:address-data /></d:prop><d:href>/dav.php/addressbooks/demo/YFAddressBook/115.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/45480.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/45481.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/45745.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/45767.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/45856.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/45865.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/45972.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/45994.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/45999.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/46007.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/46044.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/46045.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/46048.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/46049.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/46056.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/46200.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/46202.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/46203.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/51732.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/51963.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/52312.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/52790.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/53110.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/53154.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/53588.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/53589.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55435.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55436.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55437.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55438.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55439.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55440.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55441.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55442.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55443.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/55567.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/56127.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/56526.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/56532.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/56571.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/57648.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/57678.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/58269.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/58352.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/58353.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/58395.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/58579.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/58581.vcf</d:href><d:href>/dav.php/addressbooks/demo/YFAddressBook/58961.vcf</d:href></card:addressbook-multiget>

Response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML>
<HEAD>
<TITLE>403 Forbidden</TITLE>
</HEAD>
<BODY>
<H1>Forbidden</H1>
You don't have permission to access /dav.php/addressbooks/demo/YFAddressBook/ on this server.
<HR>
<I>yf.dominio.com</I>
</BODY>
</HTML>

**(The domain name and user have been changed)**

Thanks in advance ;)

**Comment by dimitrisand** [comment]
Can you login from web browser?. You have to have the KEY to login , not the password of your username. You can find the key in your profile when you login.
Hope that helps.

**Comment by SALITEL** [comment]
@dimitrisand 
> Can you login from web browser?. You have to have the KEY to login , not the password of your username. You can find the key in your profile when you login.

Yes. On web browser work fine.. and I have compared with GitDeveloper and there are no structural differences.

I use the user and password of the option DAV of the configuration.

The validation in iOS/Web/Tunderbird is correct but does not synchronize anything.

In the DAV configuration shows contacts and events in the counter.

> Hope that helps.

Thanks

**Comment by dimitrisand** [comment]
Try to increase  max_input_vars in php.ini
https://discussions.vtiger.com/discussion/55821/forbidden-you-dont-have-permission-to-access-index-php-on

**Comment by SALITEL** [comment]
I increase max_input_vars from 10000 to 20000 but not work.

**Comment by SALITEL** [comment]
(More info)

Thunderbird shows this trace:

Login - Ok
Synchronizing - Ok
Synchronizing (0/54) - Ok (54 contacts)
Sever rejected connection (forbidden) - Error

I think the problem is the permission to download the contact file or the calendar event file.

The strange thing is that the web looks good and you can download those files.

Is it a problem with server permissions? In the registry it does not show any problem of permissions.

**Comment by mariuszkrzaczkowski** [comment]
logs?
dump from verification of configuration?
what is your apache or nginx server?

**Comment by z0lo13** [comment]
@SALITEL 
make sure to allow following HTTP methods:
| GET, POST, PUT, OPTIONS, PATCH, PROPFIND, REPORT, LOCK, DELETE, COPY, MOVE |

without them DAV not going to work from any mobile device

**Comment by SALITEL** [comment]
Thanks @z0lo13 and @mariuszkrzaczkowski 

You both helped me. Effectively the problem was the HTTP_METHODS property.

Now that it works, I see that it only works with contacts.

Is it possible to "export" leads, companies and suppliers as a contact?

**Comment by mariuszkrzaczkowski** [comment]
> Is it possible to "export" leads, accouts and provider as a contact?


create a new issue
