### ISSUE TITLE
[PL][Pytanie] Workflow - "Okreslone przez system"

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10312]
Witam,

Co dokładnie oznacza "Okreslone przez system" przy tworzeniu Obiegu informacji. Tzn że bedzie wykonywany z częstotliwością CRON'a?

**Comment by davide-alghi** [comment]
Witam, tak.

if I remember correctly, yes. it means every time CRON executes workflows.

**Comment by bpabiszczak** [comment]
To oznacza, że skrypt sam decyduje o tym kiedy uruchomić mechanizm w nim zaszyty... to jest pewnie zła nazwa, bo cron wywołuje plik za każdym razem, ale to wewnątrz pliku są dodatkowe mechanizmy, które nie są już kontrolowane przez system. 

a przynajmniej tak mi się wydaje :P
