### ISSUE TITLE
Pdf Template write numbers in words

### ISSUE THREAD

**Issue by integrator2** [YetiForceCompany/YetiForceCRM#10315]
Dear support team,

Does there is a way to write numbers in words (price or so) in PDF template?
I mean "digits to word" text conversion.

Environment | Version / Name
-- | --
YetiForce | 4.4.0
Web server (name and version) | ngnix
PHP | 7.0.0
Browser (name and version) | google Chrome
Operating System (name and version) | Ubuntu 16.04 or MacOS

**Comment by vovpff** [comment]
There is function available for pdf. Check more carefully

**Comment by integrator2** [comment]
Thank you,
but it generate words with Polish currency sign.
Example: тысяча двести **zł** ноль **gr**)
Question: How to change currency sign also?

BR
Oleg Kuryan

**Comment by vovpff** [comment]
I think you need to edit original php function.

**Comment by integrator2** [comment]
ok,

may you point me? 
I am not so familiar with PHP and would not wont to be spoil something in production system.
Thank you in advance.
BR
Oleg Kuryan

**Comment by vovpff** [comment]
Посмотрите здесь https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app/Custom/NumberToWords.php.
Либо еще вариант, что где то пропущен перевод валют и берутся значения по умолчанию

**Comment by vovpff** [comment]
Проблема решилась?

**Comment by integrator2** [comment]
I woud say yes and no.
I did direct modification of string: public static function process($amount, $currencyName = 'zł', $centName = 'gr')
to
public static function process($amount, $currencyName = 'рублей, $centName = 'копеек')
but if I would like to change currency I need to modify it again every time.
Could you correct me?

BR
Oleg Kuryan

**Comment by vovpff** [comment]
I don't really know how to modify this file correct but there are should be some currency variable instead hardcoded currency names

**Comment by rskrzypczak** [comment]
This functionality didn't work properly and was removed from the system (https://github.com/YetiForceCompany/YetiForceCRM/commit/6477a2e5567e555743a00c0ba45ec9405f74f704).
It can be brought back into the system if we collect enough money to rebuild it. You can support the project at https://opencollective.com/yetiforcecrm

**Comment by JEEVAN28** [comment]
Hello I have contributed $20, for open collective for this functionality. please see if it is possible to rebuild

**Comment by mariuszkrzaczkowski** [comment]
```php
$f = new NumberFormatter("en", NumberFormatter::SPELLOUT);
echo $f->format(123456);
```
Produces the result:
one hundred twenty-three thousand four hundred fifty-six
