### ISSUE TITLE
Is there a PDF manual with all the info of each module?         

### ISSUE THREAD

**Issue by untecnologo** [YetiForceCompany/YetiForceCRM#10314]
Hello, Thanks for provide us this amazing solution.

I am implementing Yetiforce in a big company in middle east, but the documentation you have in the website is not enough to explain the final users properly about what they can do in each module.

So, is there a manual that I can download to read more even about the process an all documentation of the YetiForce. For example to explain them properly each Icon and establish the steps for them.

Really Thank you for your support.

**Comment by vovpff** [comment]
At this there is no manual system.
