### ISSUE TITLE
[bug] Wrong sorting dates in charts when date format is dd-mm-yyyy

### ISSUE THREAD

**Issue by nkzach** [YetiForceCompany/YetiForceCRM#10311]
# 🐞 bug report

![Στιγμιότυπο 2019-05-02, 11 07 50 πμ](https://user-images.githubusercontent.com/22010748/57063670-ae01ea00-6ccc-11e9-8361-2d78a67728a8.png)

### 📷 Screenshot of configuration
![yetiforce_settings-3](https://user-images.githubusercontent.com/22010748/57063500-26b47680-6ccc-11e9-928b-25a5844e5c20.png)

**Comment by nkzach** [comment]
Related issue https://github.com/YetiForceCompany/YetiForceCRM/issues/10090

**Comment by konadrian** [comment]
Which version of Yetiforce?

**Comment by konadrian** [comment]
Could you try occur this error on https://gitdeveloper.yetiforce.com/

**Comment by nkzach** [comment]
This is a screen shot from gitdeveloper
<img width="2206" alt="Στιγμιότυπο 2019-07-18, 8 33 06 πμ" src="https://user-images.githubusercontent.com/22010748/61431649-de097280-a936-11e9-915b-3ec2ccb7f375.png">

**Comment by konadrian** [comment]
The problem no longer exists. The ticket has been closed. You can also use sorting functionality which was added while ago
