### ISSUE TITLE
[bug]  LBL_USER login page caused from 4.4->5.0 upgrade

### ISSUE THREAD

**Issue by stevenbouillon** [YetiForceCompany/YetiForceCRM#10331]
# 🐞 bug report

### ⁉️ Describe the bug
-Login page "LBL_USER"

1. Go to 'my CRM'
2. Click on 'nothing'
3. Scroll down to 'hopefully nowhere'
4. See error -> where I type in the username it says "LBL_USER"

### 👍 Expected Behavior

No LBL_USER where people type in their username

### 📷 Screenshot of configuration
I'm not sure if I uploaded the image right. The only box highlighted inside of server configuration is "Header: Apache"

https://imgur.com/a/crQ2H53
-or-
<blockquote class="imgur-embed-pub" lang="en" data-id="a/crQ2H53"><a href="//imgur.com/crQ2H53"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Nothing in my logs other than another issue I will fill out regarding roundcube api failing.

* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log 

--> I could enable debugging if you'd like me to email the logs but I haven't found anything in them. I've since updated to 5.1 hoping that solved the problem but did not.

### 🌍  Your Environment 
Ubuntu Server w/ PHP 7.1
Chrome, Edge, Firefox - doesn't matter
mariadb
Cron is working correctly

### ❓ Additional context
I don't know if there's anything else to add.... Just want to make "LBL_USER" disappear from the login page so users do not see it.

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/57277633-3c9bb000-70ad-11e9-92f3-5fbbe9e83680.png)
Same situation

**Comment by davide-alghi** [comment]
Hi,
it seems (very strange) "LBL_USER" label is missed.
Please check if label 
```code
"LBL_USER": "User"
```
is there into

/languages/en-US/_Base.json

**Comment by stevenbouillon** [comment]
![Capture](https://user-images.githubusercontent.com/37988738/57312649-d90c8500-70a2-11e9-8380-fad2d0674dc8.PNG)

**Comment by stevenbouillon** [comment]
That was one of the first places I looked. Any other ideas?

**Comment by davide-alghi** [comment]
What about the value of
```code
$default_language
```
in **/config/Main.php** file?

AND

in **/layouts/basic/modules/Users/Login.Default.tpl** file at line **34**, do you find something like this?
```code
placeholder="{\App\Language::translate('LBL_USER',$MODULE)}"
```

**Comment by stevenbouillon** [comment]
![Capture](https://user-images.githubusercontent.com/37988738/57315313-293a1600-70a8-11e9-8186-70888e6be232.PNG)

**Comment by davide-alghi** [comment]
Your $default_language is wrong (en_us).
Right code is **en-US**

**Comment by stevenbouillon** [comment]
FYI - I really appreciate your help. I look forward to your response.

**Comment by stevenbouillon** [comment]
Oh. thx. I'll give that a try.

**Comment by stevenbouillon** [comment]
Unfortunately, no change. I cleared Cache and to be safe rebooted server.
![Capture](https://user-images.githubusercontent.com/37988738/57315939-7b2f6b80-70a9-11e9-9a2f-10302b0166c2.PNG)
![Capture1](https://user-images.githubusercontent.com/37988738/57315940-7b2f6b80-70a9-11e9-8a5a-2ac09d5de731.PNG)

**Comment by stevenbouillon** [comment]
Actually, you were right. I missed the "-".

Thank you so much!
