### ISSUE TITLE
 fsockopen(): SSL operation failed with code 1

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [YetiForceCompany/YetiForceCRM#1033]
PHP Warning:  fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in public_html/modules/OSSMail/RoundcubeLogin.class.php on line 477

**Comment by bpabiszczak** [comment]
https://demo.yetiforce.com/index.php?module=OSSMail&view=index&parent=44
