### ISSUE TITLE
mail scanner error

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#1034]
Błąd!!!

Nie można połączyć się z serwerem poczty: Certificate failure for xxxxxxxxxxxxxxxxx: Server name does not match certificate: /OU=GT01172648/OU=See www.rapidssl.com/resources/cps (c)15/OU=Domain Control Validated - RapidSSL(R)/CN=*.xxxxxxxxxxxxxxx

fresh install, how to close ssl validation in mail scanner. ?!

**Comment by waw555** [comment]
change port on 25
https://test.yetiforce.com/index.php?module=OSSMail&parent=Settings&view=index&block=8&fieldid=36

**Comment by IngewonPL** [comment]
Mam ten sam bład, port 25 dot. smtp a tutaj jest raczej problem z imap, nie działa z sll jak i bez. Problem powstał po pierwszym logowaniu sie na konto pocztowe (przed logowaniem na pocztę mogłem wejść w te ustawienia).  Co ciekawe klient poczty działa bez problemu.

**Comment by waldektroc** [comment]
Jestem początkujacym uzytkownikiem YF i właściwie sam bez przerwy potrzebuję pomocy. NIemniej może Wam się przyda co odkryłem. 

Po pierwsze, występował u mnie identyczny błąd. Moja instalacja jest na home.pl. Z treści błędu wynikało, że skaner szuka certyfikatu SSL i znajduje takowy lecz pasujący do sewera. NIe mamy certyfikatu SSL w naszej domenie w ogóle ale home.pl ma taki certyfikat i w zasadzie każdy klient może z niego korzystać. Rzecz w tym, że jest on przypisany do domeny home.pl, a nie do mojej domeny. 

Co zrobiłem. W ustawieniach Poczta/Klient poczty zmieniłem w polu Nazwa serwera IMAP z xxxx.pl na xxxx.home.pl. Teraz wszystko działa.

**Comment by bpabiszczak** [comment]
My wykonujemy instalacje YetiForce na kilku/kilkunastu serwerach tygodniowo. 99% problemów stanowi niepoprawne wprowadzanie danych lub komunikacja jest blokowane przez firewall. 

Aktualnie autor nie zastosował się do tego artykułu: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html, aby móc pomóc lub zasugerować rozwiązanie musimy zrozumieć w 100% jakie środowisko ma autor problemu, co wpisał i gdzie i jak ten błąd wywołać np. u nas na wersji testowej. 

Bez podstawowych informacji, wkrótce zamknę to zgłoszenie.

**Comment by IngewonPL** [comment]
no dobrze, to ja postaram się kontynuować temat. 
System mam także na home.pl jak waldektroc ale u mnie jego rozwiązanie nie działa (prawdopodobnie z powodu poprzedniej próby testu na gmailu). 
Przy pierwszej próbie uruchomienia skanera (pierwsze co zrobiłem to zalogowałem się na firmowego maila), wyskoczył błąd jak w pierwszym poście.W chwili obecnej podejrzewam, że przy tym kroku rozwiązanie waldektroc  by pomogło (wydaje się logiczne)
Później uzupełniłem dane jak w waszym serwerze testowym na gmaila (zalogowałem się na pocztę) i przy wejściu na skaner  otzymałem :
Błąd!!!

Nie można połączyć się z serwerem poczty: Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate)
Teraz próbowałem rozwiązania waldektroc i mam ten sam bład co w pierwszym poście, czyli:
Błąd!!!

Nie można połączyć się z serwerem poczty: Certificate failure for imap.xxxx.home.pl: certificate has expired: /serialNumber=YX-o4xB2oyc6M2QxC3O868uRlBk1EVUr/C=PL/O=xxxx.pl/OU=GT06518253/OU=See www.rapidssl.com/resources/cps (c)12/OU=Domain Control Validated - RapidSSL(R)/CN=xxxx.pl
Chciałbym zauważyć, że w błedzie w późniejszej częsci komuniakty widnieje domena xxxx.pl a nie xxxx.home.pl (jak domena przy piewrszym udanym logowaniu do poczty).
Teraz mam pytanie czy mogę w jakiś sposób podejrzeć i usunąć profile poczty? Przy autologowaniu widze, żę mam ich utworzonych już kilka z różnymi domenami (xxxx.pl, gmai.com, xxxx.home.pl) i to moze mieszać.
Dleczego nawet jeżeli w domenie klienta nie wpiszę ssl:// system sprawdza certyfikat ssl?? Czy można ominąć sprawdzenie ssl?

**Comment by mariuszkrzaczkowski** [comment]
Usuń wszystkie wpisy z tablicy roundcube_users to błędu nie powinno być i wtedy ponownie spróbuj ponownie się zalogować.

**Comment by rcrrich** [comment]
It seems the mail system doesn't work right the system sends a test email from admin It also sends password reset emails. But the scanner doesn't work at all I am not sure what I need to do as it is not 3 days trying to get this to work. I am starting to think I have made a big mistake using this script.

**Comment by rcrrich** [comment]
I get the info from my mail program on what to put and so far putting the wrong info is not my problem as i get an error message connection to storage server failed.

**Comment by IngewonPL** [comment]
Usunięcie wpisów pomogło, mogłem się dostać do skanera. Jednak po wpisaniu wartości z domeną home.pl po pierwszym zalogowaniu ponownie wyskakuje błąd:
Błąd!!!

Nie można połączyć się z serwerem poczty: Certificate failure for imap.xxxx.home.pl: certificate has expired: /serialNumber=YX-o4xB2oyc6M2QxC3O868uRlBk1EVUr/C=PL/O=xxxx.pl/OU=GT06518253/OU=See www.rapidssl.com/resources/cps (c)12/OU=Domain Control Validated - RapidSSL(R)/CN=xxxx.pl

Dlaczego mimo wpisania domeny w kliencie poczty xxxx.home.pl w opisie błedu mam ciągle xxxx.pl??? 
Dodatkowo ponawiam pytanie, czy można ominąć sprawdzanie certyfikatu ssl???
Całkowicie z innej strony dlaczego w tabeli roundcube_users HASŁO do maila jest varchar a nie PASSWORD?? Trochę to dziwne (wydaje się mało prfesjonalne), że hasło do maila jest jawne.

**Comment by bpabiszczak** [comment]
Jeden problem jeden wątek. 

1. Należy problem certyfikatu ustalić z Home. Komunikat który widzisz dotyczy odpowiedzi serwera [aplikacja sama z siebie nie generuje takiej odpowiedzi] a więc należy to skonsultować z administratorem lub spróbować we własnym zakresie to naprawić.

2. Gdy dodaje nasz skrypt konto do tabel roundcube to po ich dodaniu, należy dla pewności sprawdzić w tabeli czy dane [adresy] do serwera i nazwa użytkownika, port itd. odpowiednio się dodamy [tak jak zaleca home]. Możliwe, że logując się nasz skrypt dodaje domenę A a powinien domenę B. 

3. Opcja walidacji certyfikatu jest dostępna tutaj: https://test.yetiforce.com/index.php?module=OSSMail&parent=Settings&view=index&block=8&fieldid=36

4. Z hasłami proponuje oddzielny wątek. Są one domyślnie tak zapisywane jak robi to roundcube.

**Comment by mariuszkrzaczkowski** [comment]
Try to upload this fix  (https://github.com/YetiForceCompany/YetiForceCRM/commit/191fb55f2671b8158c08175a992f8c37d1156667 ) and see if the bug still exists. In the configuration, there is a parameter that determines whether a certificate should be validated or not (Settings > Mail > Mail client > Validate certificate).

**Comment by mariuszkrzaczkowski** [comment]
Spróbuj wgrać poprawekę (https://github.com/YetiForceCompany/YetiForceCRM/commit/191fb55f2671b8158c08175a992f8c37d1156667 ) i sprawdzić czy będzie występował ten błąd.
W konfiguracji jest parametr który określa czy walidaować certyfikat czy nie (Settings > Mail > Mail client > Validate certificate.

**Comment by IngewonPL** [comment]
po wporadzeniu w/w zmina w kodzie skanej działa.

**Comment by rcrrich** [comment]
Each day I come back to your crm I get a blank page when going to the website crm or after I login to the crm i get a blank page. I can't keep redoing this each day and I can't even start to work as each day I have to reset everything. Why does this happen?? It seems that it is possible that the something is running that would cause this to happen. I will try one more time to reinstall then if it happens again I will look for something that will work and not die everyday. I have 40 sites with databases and not one other does this.

**Comment by rcrrich** [comment]
Maybe my troubles are that this is not working in the US-Lang anyway I going to try to down the latest version again and get the updates hope as you update you also update the download crm???

**Comment by KatarzynaUlichnowska** [comment]
Hello,
that's a different problem so please create a new issue and describe everything - what you did, when it happened etc.
Please read the following articles:
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by rcrrich** [comment]
On 2015-06-15 07:21, IngewonPL wrote: 

> po wporadzeniu w/w zmina w kodzie skanej działa. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

Is there anyway to add a translator script to the email program??? 
-- 

RICHARD C. ROSSY
BUSAV
V.P. SALES
PHONE: 305-332-5599 

Links:
------
[1]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1034#issuecomment-112023009

**Comment by rcrrich** [comment]
ok the problem seems to be backin the latest version [ver. 2.0.210] can we fix this please!
![mailscanner fw](https://cloud.githubusercontent.com/assets/12788182/8444958/57866e66-1f65-11e5-9740-6ffb4009a23a.png)

**Comment by rskrzypczak** [comment]
Hello,
This problem was fixed here: https://github.com/YetiForceCompany/YetiForceCRM/commit/6476dd8237bb4b8a98f406aec3c811d379f7870d
Please verify developer version as well.

**Comment by bpabiszczak** [comment]
https://gitdeveloper.yetiforce.com/

**Comment by mariuszkrzaczkowski** [comment]
Added status of e-mail accounts in the mail scanner, so that you can check if the scanner will work for this account.
Just that somebody can change the password in the mail and scanner will not work.
https://github.com/YetiForceCompany/YetiForceCRM/commit/c51687f70a846f25746c5fca525337fc523d5422
