### ISSUE TITLE
[bug] Unable to Update Library

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#10341]
It seems that I am un able to update the round cube module library.
It ask me to update the library and when I click on it nothing happens.

I have a clean new installation yeti 5.1.0

Ths status says downloaded and i should just need to click on update library but nothing happens. 
![unable to update Libarary](https://user-images.githubusercontent.com/7829825/57312013-52e25400-711f-11e9-93ed-0cc31541d925.png)

**Comment by mariuszkrzaczkowski** [comment]
logs

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/57351773-69aa9a00-7163-11e9-9786-65789cc215a0.jpg)

**Comment by konadrian** [comment]
I closed the issue because we've waited too long for an answer
