### ISSUE TITLE
[Question]         Where to Change default Time zone and currency?

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#10340]
I would like to know where and how I can change the default time zone and currency. Mine is currently set to Canada Eastern Time and I need to change it to UTC Hong Kong. I would like to know where I can make this change.

Thanks

**Comment by davide-alghi** [comment]
Hi,
**about TIMEZONE**
**for YF** default timezone, you need to edit (manually) the file /config/Main.php at line 94
```code
public static $default_timezone = 'Asia/Hong_Kong';
```

**for user** you need to set timezone into profile form
(https://gitstable.yetiforce.com/index.php?module=Users&parent=Settings&view=Detail&record=1)

![UTZ](https://user-images.githubusercontent.com/48508691/57312442-d97e3d80-70ed-11e9-85aa-1de7c77faf66.png)


**about CURRENCY**
BE: System Tools >> Currencies
(https://gitstable.yetiforce.com/index.php?parent=Settings&module=Currency&view=List&block=4&fieldid=16)
