### ISSUE TITLE
How to restrict workflow fire on only business hours

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10349]
### Description
How to restrict workflow fire for  working hours and working days 

for example : 9 am to 5 pm

**Comment by joelbcampos** [comment]
I HOPE TO BE HELPFUL

![capture-3](https://user-images.githubusercontent.com/29610537/57523608-b76f0000-7325-11e9-9128-1fdb51569d63.gif)

**Comment by guide5232** [comment]
Is it control the workflow firing for business hours?(Workflow does not  fire on public holidays,Saturday,Sundays and Evening  5PM to  Morning 9AM)

**Comment by mariuszkrzaczkowski** [comment]
Currently it's not possible to define working hours on workflow
We're working on implementing business hours to be used with the SLA module and support service,  
I assume it won't be hard to combine with workflow

**Comment by guide5232** [comment]
Hi Team
 I have found another bug in CRM. I have recorded one video for your reference.Same workflow condition and same update i have done 3 days back. but today i am getting error while i am updating the hours field.Please give me solution for this bug.
![Update field bug](https://user-images.githubusercontent.com/47585969/57681041-3c358300-7672-11e9-8c9e-412133300c13.gif)

**Comment by vovpff** [comment]
@guide5232 let's use `expression` instead `field` when set value

**Comment by paula-w** [comment]
Please open a separate issue for each new question / bug.

**Comment by guide5232** [comment]
Ok

**Comment by guide5232** [comment]
> @guide5232 let's use `expression` instead `field` when set value

days back worked fine.

**Comment by guide5232** [comment]
Hi Team 
By using Business Hours and SLA Policy can we restrict workflow fire for working hours and working days?(Workflow does not fire on public holidays,Saturday,Sundays and Evening 5PM to Morning 9AM).
