### ISSUE TITLE
New module of reports (crowdfunding)

### ISSUE THREAD

**Issue by lichnost3d** [YetiForceCompany/YetiForceCRM#10351]
Sorry for my English.
We have been following the development of your CRM for 1 year already, in the hope that a report module will appear in it, but alas, it is still not clear whether it is worth the wait or not. It is a pity that such an excellent CRM does not have one of the most important elements of any CRM without which it is difficult to consider it competitive. If the reason for the absence of a module is money, can we try to collect the necessary amount using crowdfunding? I think that many community members are willing to donate a little money for.

**Comment by lichnost3d** [comment]
Please tell me how much money you need to collect in order to be sure that the reporting module will be created?

**Comment by acsinsurancegroup** [comment]
They've stated previously that the widgets give us all the reporting we need. I hardly see how that is the case when you're trying to run a professional firm and have to obtain the information from a widget. A true reporting module with a nice GUI is what's truly needed to effectively print out proper reporting features. I'd gladly contribute so keep me posted as well.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/10839

https://opencollective.com/YetiForceCRM
