### ISSUE TITLE
[Question]  Dynamic inventory columns.         

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#10354]
Where i can test dynamic inventory columns option?

### Description

Tried to test on gitdeveloper but i can't find option.
I see that pull request is merged.
Pull request https://github.com/YetiForceCompany/YetiForceCRM/pull/10247 abd https://github.com/YetiForceCompany/YetiForceCRM/pull/10200.

Thanks !

**Comment by cltvchannel** [comment]
Thanks !

**Comment by mariuszkrzaczkowski** [comment]
we've added a dynamic template for the gitdev version

https://gitdeveloper.yetiforce.com/index.php?module=FInvoice&view=List&mid=129&parent=71

![image](https://user-images.githubusercontent.com/10198654/58156194-d9497a80-7c75-11e9-9564-4579ed04e23d.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I checked quick new stuff
If I add 2 or more templates there are only one scheme available for all dynamic tables.
Is it possible to make separate columns presets per template?
![image](https://user-images.githubusercontent.com/8545791/58164802-2be36080-7c8f-11e9-9762-7abb486d1000.png)

**Comment by mariuszkrzaczkowski** [comment]
no
