### ISSUE TITLE
[Question]   How i can get full developer version?        

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#10363]
### Description

I need to install developer version because i want to try developing some new functions.
How i can do this?
Thanks !

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM#where-else-can-you-find-yetiforce

**Comment by cltvchannel** [comment]
@mariuszkrzaczkowski 
Checked and all seems to be ok, but not show dynamic inventory.
