### ISSUE TITLE
GANTT: no way to display tasks and milestones

### ISSUE THREAD

**Issue by CN41SAS** [YetiForceCompany/YetiForceCRM#10377]
Hello,
when creating tasks and milestones in a project, they do not show in GANTT mode.
Start and end date are set
linking a milestone does not change anything
should be shown

date format dd-mm-yyyy
PhP 7.1
Yetiforce 4.4
Firefox quantum 66.0.5 (64 bits)
win7pro 64b

In advance thanks for support
Best regards
Jean-François

**Comment by konadrian** [comment]
Could you try duplicate this error on https://gitdeveloper.yetiforce.com/
