### ISSUE TITLE
[bug] incorrect picklist items title in detail / edit / conditionbuilder

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#10371]
# 🐞 bug report

### ⁉️ Describe the bug
Picklist items title is wrong in detail, edit, and condition builder view

### 🔥 How to trigger the error
![bug_0012](https://user-images.githubusercontent.com/48508691/57465875-c8fdcc80-727f-11e9-94b0-ef34a1e9cee5.gif)

### 👎 Actual Behavior
Wrong picklist items title

### 👍 Expected Behavior
Correct picklist items title

### 📷 Screenshot of configuration
[none]

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
[indipendent]

### 🌍  Your Environment 
[indipendent]

### ❓ Additional context
[none]

### :heavy_check_mark: Fix
simply replace $PICKLIST_NAME with **$PICKLIST_VALUE** in **title**
in /layouts/basic/modules/Vtiger/Edit/Field/Picklist.tpl:36 replace
```HTML
        ...
        <option value="{\App\Purifier::encodeHtml($PICKLIST_NAME)}"
		title="{\App\Purifier::encodeHtml($PICKLIST_NAME)}" {if trim($FIELD_VALUE) eq trim($PICKLIST_NAME)} selected {/if}>{\App\Purifier::encodeHtml($PICKLIST_VALUE)}</option>
	...
```
with
```HTML
        ...
        <option value="{\App\Purifier::encodeHtml($PICKLIST_NAME)}"
		title="{\App\Purifier::encodeHtml($PICKLIST_VALUE)}" {if trim($FIELD_VALUE) eq trim($PICKLIST_NAME)} selected {/if}>{\App\Purifier::encodeHtml($PICKLIST_VALUE)}</option>
         ...
```

and in /layouts/basic/modules/Vtiger/ConditionBuilder/Picklist.tpl:11 replace
```HTML
    ...
    <option value="{\App\Purifier::encodeHtml($PICKLIST_NAME)}"
		title="{\App\Purifier::encodeHtml($PICKLIST_NAME)}" {if in_array($PICKLIST_NAME, $FIELD_VALUES)} selected {/if}>{\App\Purifier::encodeHtml($PICKLIST_VALUE)}</option>
    ...
```
with
```HTML
    ...
    <option value="{\App\Purifier::encodeHtml($PICKLIST_NAME)}"
		title="{\App\Purifier::encodeHtml($PICKLIST_VALUE)}" {if in_array($PICKLIST_NAME, $FIELD_VALUES)} selected {/if}>{\App\Purifier::encodeHtml($PICKLIST_VALUE)}</option>
    ...
```

**Comment by mariuszkrzaczkowski** [comment]
You can send all fixes via pull request
