### ISSUE TITLE
[Question] Hello Team,          

### ISSUE THREAD

**Issue by kilim1983** [YetiForceCompany/YetiForceCRM#10372]

**Comment by kilim1983** [comment]
Hello Team,

I have some question about export records to excel from module Support Ticket for example. I create filter. In www I can see records which some fileds are cut for example Subject or description. In www this is not problem, but when I export to excel I can see the same...not all information I can see. I can see part of information with three dots...

I assume that I can forget about somthing. My question is how I can receive xml file with all information in excel file.

I have 5.0.0 version.

Regards,
Damian

**Comment by davide-alghi** [comment]
Hi,
you can set text length for list view and for excel exporting in BE:**System Tools:System Configuration** with "**Maximum text length in List View**" field.

https://gitstable.yetiforce.com/index.php?module=Vtiger&parent=Settings&view=ConfigEditorDetail&block=4&fieldid=25

**Comment by kilim1983** [comment]
Hi Dave,

Thank you for your response. Yes you are right when I change this settings I can see all Title and toher fileds  but description filed are still cut. This filed sometimes has more than 100 text lenght...:(

Regards,
Damian

**Comment by kilim1983** [comment]
I found solutions.

Thanks for your help.

Regards,
Damian

**Comment by vovpff** [comment]
What is your solution?

**Comment by davide-alghi** [comment]
Hi Kilim,
I would be interested too :)

**Comment by kilim1983** [comment]
Hi Team,

Under "Maximum text length in List View" by web interface you can set only 100 value not more. I set more than 100 under config file /var/www..../config/main.php $listview_max_textlenght.....of course I dont know if this not crash something else in other place (I suppose that developers have imposed this restriction for some purpose) but this cover my needs.

Regards,
Damian

**Comment by davide-alghi** [comment]
Hi Kilim,
if it's useful for you and you are familiar with php-code, I post here a simple solution: this bypass "truncate" only for excel export.

Edit /app/TextParser.php file.

1. rename "public static function **htmlTruncate**(...)" in "public static function **_htmlTruncate**(...)"
2. rename "public static function **textTruncate**(...)" in "public static function _textTruncate(...)"
3. add following two function (copy/paste)
```PHP
public static function htmlTruncate($html, $length = false, $addDots = true, &$isTruncated = false) {
	$_html = '';
	
	if(\App\Request::_get('action') == 'QuickExport' && \App\Request::_get('mode') == 'exportToExcel') { // full html if it's excel export
		$_html = $html;
	} else { // truncated html
		$_html = self::_htmlTruncate($html, $length, $addDots, $isTruncated);
	}
	
	return($_html);
}


public static function textTruncate($text, $length = false, $addDots = true) {
	$_text = '';
	
	if(\App\Request::_get('action') == 'QuickExport' && \App\Request::_get('mode') == 'exportToExcel') { // full text if it's excel export
		$_text = $text;
	} else { // truncated text
		$_text = self::_textTruncate($text, $length, $addDots);
	}
	
	return($_text);
}
```

**Comment by vovpff** [comment]
@davide-alghi this mod absolutely kill mentions feature
