### ISSUE TITLE
[bug] No mapping FIELD

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#10376]
I did not map the fields, I did a test from Guitdeveloper, and it does not work either

![capture-2](https://user-images.githubusercontent.com/29610537/57517739-ce0e5a80-7317-11e9-97ed-920910bd028a.gif)

**Comment by vovpff** [comment]
This is some explanation of mapping. For example you can map invoice fields to GDN. When you open invoice there should be button what create new GDN with all fields data copied from original invoice.

**Comment by joelbcampos** [comment]
> Esta es una explicación del mapeo. Por ejemplo, puede asignar campos de factura a GDN. Cuando abra la factura, debe haber un botón que cree un nuevo GDN con todos los datos de los campos copiados de la factura original.

**sorry but I do not understand your answer**

**Comment by vovpff** [comment]
Mapping the tool for quick transfer data from one module to another. This is not for your task. For your task you need to manage this file https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/user_privileges/moduleHierarchy.php
