### ISSUE TITLE
[bug] Initial wizard creates a username that is deemed invalid

### ISSUE THREAD

**Issue by YourCommunications** [YetiForceCompany/YetiForceCRM#10385]
# 🐞 bug report

### ⁉️ Describe the bug

Default admin username is in the format admin1239 (admin plus a number).
Once you go to the summary screen, this name is missing and you can not continue

### 🔥 How to trigger the error
Following the first run wizard (http://DOMAINNAME.COM/install/Install.php you go through the wizard and a username is AUTOMATICALLY selected (admin3645)

When you complete the rest of the fields and then try to confirm the username (on the summary screen), the username is Blank and you can not continue.

If you go back and change to a text only username AdminDemo this works

### 👎 Actual Behavior
Unable to complete wizard after summary screen

### 👍 Expected Behavior
allow username to include numbers

### 📷 Screenshot of configuration
NA - 

![Pasted File at May 10, 2019 7_17 PM](https://user-images.githubusercontent.com/50491347/57533255-3a4b8700-7335-11e9-8a97-2428de2b4d37.png)

### 🌍  Your Environment 

CPU:
1 vCore
RAM:
2048 MB
Storage:
55 GB SSD

Yetiforce 5.1

PHP 7.2.17-0ubuntu0.18.04.1 (cli) (built: Apr 18 2019 14:12:38) ( NTS )

Safari / Mac + Windows 10/Firefox

4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper

**Comment by konadrian** [comment]
Try to enable logs https://yetiforce.com/en/component/zoo/item/debugging?highlight=WyJsb2dzIl0=
We need more information about the problem because I can't duplicate it
