### ISSUE TITLE
Notification Module Malfunctioning

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10390]
Hi, the notification module seems to be malfunctioning. It says contact the administrator. I was just trying to send notification manually when this happened.

The error log show this:
An error occurred: Could not resolve host: security.sensiolabs.org. in vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/CurlCrawler.php:75

Version used:4.40

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/9686
https://github.com/YetiForceCompany/YetiForceCRM/issues/8739
