### ISSUE TITLE
How to activate DAV Application

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#10395]
I would like how to uncomment  as I am still new in yetiforce and i would like to use the Dav application however I got the error below

DAV application is not active
DAV application has not been activated yet, enable it in config/api.php

What do i exactly need to do to activate it as i am not sure when it mentions to uncomment

I know very basic for some  but i am still learning so if someone kindly shows me the way would be greatly appreciated

<?php

/**
 * Configuration file.
 * This file is auto-generated.
 *
 * @package Config
 *
 * @copyright YetiForce Sp. z o.o
 * @license   YetiForce Public License 3.0 (licenses/LicenseEN.txt or yetiforce.com)
 */

namespace Config;

/**
 * Configuration Class.
 */
class Api
{
	/** List of active services. Available: dav, webservices, webservice */
	public static $enabledServices = [];

	/** Dav configuration. Available: false, true */
	public static $enableBrowser = false;

	/** Dav configuration. Available: false, true */
	public static $enableCardDAV = false;

	/** Dav configuration. Available: false, true */
	public static $enableCalDAV = false;

	/** Dav configuration. Available: false, true */
	public static $enableWebDAV = false;

	/** Webservice config. Available: false, true */
	public static $ENCRYPT_DATA_TRANSFER = false;

	/** Webservice config. */
	public static $AUTH_METHOD = 'Basic';

	/** Webservice config. */
	public static $PRIVATE_KEY = 'config/private.key';

	/** Webservice config. */
	public static $PUBLIC_KEY = 'config/public.key';
}

****

**Comment by SALITEL** [comment]
Hello @bangde 

**1**) The steps to activate DAV (CalDAV and CardDAV) are as follows:
`	/** List of active services. Available: dav, webservices, webservice */
	public static $enabledServices = ['**dav**'];

	/** Dav configuration. Available: false, true */
	public static $enableBrowser = **true**;

	/** Dav configuration. Available: false, true */
	public static $enableCardDAV = **true**;

	/** Dav configuration. Available: false, true */
	public static $enableCalDAV = **true**;
`

**2**) In the YetiCRM configuration, Integration option and then DAV Applications.
-Press the "Add Key" button, select user and press "Save"

**3**) Now you can configure the CalDAV and CardDAV account on your mobile phone using the user and the password for that option. To obtain the hidden key, press the "Key" button.

Consider the server configuration. I had problems myself because I did not have it properly configured: #10405

**Comment by acsinsurancegroup** [comment]
It won't much matter if it's activated or not. It doesn't ever work anyway from my experience. I have tried to Sync with CalDavSynchronizer and DAVx5 and both throw errors all the time. Some appointments go into the calendar and some don't. I have my cron setup properly and all of my Warnings are Green so no server issues and it still doesn't work for me.

**Comment by bpabiszczak** [comment]
https://public.yetiforce.com/img/CalDav_and_DavDroid.gif
