### ISSUE TITLE
invoice 1000 seperator issues

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#104]
If user changes setting from , to . as 1000-seperator. 
So nunbers are showed like
1.000,00
instead of 
1,000.00

in order to show one thousand 
the invoice pdf generator has error.
it only changes the decimal seperator.

so output looks like 
1,000,00

plesae take a look at this pdf invoice capture
http://www.screencast.com/t/WTldQDJEC

**Comment by lalord** [comment]
Is this fix pushed to version 1.2 ? 
still have same bug when generating invoices.

**Comment by mariuszkrzaczkowski** [comment]
Changes have been added to 1.2.1 version so that means they will be published in 1.3. If you want, you can copy a file from this revision and upload it to CRM.
