### ISSUE TITLE
I want to remove or hide the field "Private" and add other industries in Accounts Field

### ISSUE THREAD

**Issue by untecnologo** [YetiForceCompany/YetiForceCRM#10407]
Hello dear community of Yetiforce 

I have a certain requirement of the main user for the Fields in Accounts Registration.

1)  Our customers belong to a different industries areas, so we need add others industry areas to the pick list, how can I do it?

2) I need to remove the field private from the form. How can I do it, it appears like active and I can't delete it. 

3) By mistake I delete from the form Account the field "Lead Source" how can undo my mistake.
Thanks for your nice support like always.

Best Regards,

**Comment by vovpff** [comment]
@untecnologo 

1. https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9 for picklists
2. You can hide this field by profiles https://gitdeveloper.yetiforce.com/index.php?module=Profiles&parent=Settings&view=List&block=1&fieldid=3
3 . This is very good question... If this is picklist you can add it by field editor. I'm not sure but old Lead Source field can be system field and some errors can occurs in future...

**Comment by untecnologo** [comment]
3.- It was not a pick list... =( So how can I fix it...

**Comment by vovpff** [comment]
@untecnologo at standard fresh system there are no `Lead Source` field for Accounts.

**Comment by davide-alghi** [comment]
Hi guys,

2. If you need to overall hide the field, simply hide it: green button, un-tick Active checkbox
here https://gitstable.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=Accounts
3. I presume it was a custom field. built-in fields are not deletable. Unfortunately you cannot roll-back: when you deleting a field, it's completly removed from system and values too.


PS: in future, hide field, don't delete it
