### ISSUE TITLE
ERR_NOT_ALLOWED_VALUE FILTER FIELD SEARCH

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#10406]
![Snap_2019 05 13_11h48m54s_002_](https://user-images.githubusercontent.com/29610537/57612425-1bd3ce80-7575-11e9-82ca-2f09a8e05cd4.jpg)

/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
'use strict';

window.AppConnector = {

	/**
	 * Sends a pjax request (push state +ajax)
	 * The function is deferred. it will be resolved on success and error on failure
	 *  Success - if request is success it will send you data that it recieved
	 *  error - it will send two parameters first gives string regarding error
	 *                   Second gives you error object if exists
	 *
	 *  @return - deferred promise
	 */
	requestPjax: function (params) {
		return AppConnector._request(params, true);
	},

	/**
	 *  Sends ajax request to the specified url.
	 *  The function is deferred. it will be resolved on success and error on failure
	 *  Success - if request is success it will send you data that it recieved
	 *  error - it will send two parameters first gives string regarding error
	 *                   Second gives you error object if exists
	 *
	 *  @return - deferred promise
	 */
	request: function (params, rawData) {
		return AppConnector._request(params, false, rawData);
	},

	_request: function (params, pjaxMode, rawData) {
		const aDeferred = jQuery.Deferred();
		if (typeof rawData === "undefined") {
			rawData = false;
		}
		if (typeof pjaxMode === "undefined") {
			pjaxMode = false;
		}
		if (typeof params === "undefined") {
			params = {};
		}
		let fullUrl = '',
			index,
			callerParams;
		//caller has send only data
		if (typeof params.data === "undefined" || rawData) {
			if (typeof params === 'string') {
				callerParams = fullUrl = params;
				index = callerParams.indexOf('?');
				if (index !== -1) {
					let subStr = callerParams.substr(0, index + 1);//need to replace only "index.php?" or "?"
					callerParams = callerParams.replace(subStr, '');
				}
			} else {
				callerParams = $.extend({}, params);
			}
			params = {};
			params.data = callerParams;
		}
		//Make the request as post by default
		if (typeof params.type === "undefined" || rawData)
			params.type = 'POST';
		if (typeof params.jsonp === "undefined" || rawData)
			params.jsonp = false;

		//By default we expect json from the server
		if (typeof params.dataType === "undefined" || rawData) {
			let data = params.data;
			//view will return html
			params.dataType = 'json';
			if (data.hasOwnProperty('view')) {
				params.dataType = 'html';
			} else if (typeof data === 'string' && data.indexOf('&view=') !== -1) {
				params.dataType = 'html';
			}
			if (typeof params.url !== "undefined" && params.url.indexOf('&view=') !== -1) {
				params.dataType = 'html';
			}
		}
		//If url contains params then seperate them and make them as data
		if (typeof params.url !== "undefined" && params.url.indexOf('?') !== -1) {
			fullUrl = params.url;
			let urlSplit = params.url.split('?'),
				queryString = urlSplit[1];
			params.url = urlSplit[0];
			let queryParameters = queryString.split('&');
			for (index = 0; index < queryParameters.length; index++) {
				let queryParam = queryParameters[index],
					queryParamComponents = queryParam.split('=');
				params.data[queryParamComponents[0]] = queryParamComponents[1];
			}
		}
		if (typeof params.url === "undefined" || params.url.length <= 0) {
			params.url = 'index.php';
		}
		params.success = function (data, status, jqXHR) {
			if (data !== null && typeof data === 'object' && data.error) {
				app.errorLog(data.error);
				if (data.error.message) {
					Vtiger_Helper_Js.showMessage({
						text: data.error.message,
						type: 'error'
					});
				}
			}
			aDeferred.resolve(data);
		};
		params.error = function (jqXHR, textStatus, errorThrown) {
			let action = jqXHR.getResponseHeader('yf-action');
			if (action === 'logout') {
				window.location.href = 'index.php';
			}
			if (CONFIG.debug) {
				if (jqXHR.status === 406) {
					let sep = "-".repeat(150);
					console.warn("%cYetiForce debug mode!!!", "color: red; font-family: sans-serif; font-size: 1.5em; font-weight: bolder; text-shadow: #000 1px 1px;");
					console.error('Error: ' + errorThrown, '\n' + sep + '\nTrace:\n' + sep + '\n' + (jqXHR.responseJSON ? jqXHR.responseJSON.error.trace : ''), '\n' + sep + '\nParams:\n' + sep + '\n' + JSON.stringify(params, null, '\t'));
				} else {
					app.errorLog(jqXHR, textStatus, errorThrown);
				}
			}
			aDeferred.reject(textStatus, errorThrown, jqXHR);
		};
		jQuery.ajax(params);
		if (pjaxMode) {
			if (typeof params.data.historyUrl !== 'undefined') {
				fullUrl = params.data.historyUrl;
			}
			if (fullUrl === '') {
				fullUrl = 'index.php?' + $.param(params.data);
			} else if (fullUrl.indexOf('index.php?') === -1) {
				fullUrl = 'index.php?' + fullUrl;
			}
			if (history.pushState && fullUrl !== '') {
				const currentHref = window.location.href;
				if (!history.state) {
					history.replaceState(currentHref, "title 1", currentHref);
				}
				history.pushState(fullUrl, "title 2", fullUrl);
			}
		}
		return aDeferred.promise();
	},

	requestForm: function (url, params) {
		var newEle = '<form action=' + url + ' method="POST">';
		if (typeof csrfMagicName !== "undefined") {
			newEle += '<input type="hidden" name="' + csrfMagicName + '"  value=\'' + csrfMagicToken + '\'>';
		}
		if (typeof params !== "undefined") {
			jQuery.each(params, function (index, value) {
				newEle += '<input type="hidden" name="' + index + '"  value=\'' + value + '\'>';
			});
		}
		newEle += '</form>';
		var form = new jQuery(newEle);
		form.appendTo('body').submit();
	},
}

**Comment by vovpff** [comment]
What are you doing?

**Comment by joelbcampos** [comment]
I'm doing a search by filter field, in the preinvoice module.

![search](https://user-images.githubusercontent.com/29610537/57710257-d4c90480-766c-11e9-8a4d-a73ad01922ba.gif)

**Comment by vovpff** [comment]
Cliente means account? How you achieve dropdown list for this field?

**Comment by joelbcampos** [comment]
First of all, I would like to thank you. People like you help me to continue with the project because otherwise I would give up.

Customers is not Accounts is Leads.
It is not a drop-down field, but since the database is large it is necessary that you can search by entering the name or any data that can speed up the tasks.

In the rest of the modules the search is carried out without problem, so it is a problem of this module.

**Comment by vovpff** [comment]
As I know this field should be UI type 10 (maybe not correct value, easely 1:m field) and for this fields searching with dropdown not avalable from 4.x.x version. @mariuszkrzaczkowski I'm right?
My first idea what cache of your browser or entrine system not cleared perfect. Or some stuff upgraded unsucessful. 
In any case this is self brainstorming and really I can't help with this problem... I'm so sorry.

**Comment by joelbcampos** [comment]
Solved, the problem is, that asinaba values from another module and does not allow to perform associated searches, I created the link directly to the module and it works correctly.

Thank you.

**Comment by mariuszkrzaczkowski** [comment]
Check it https://github.com/YetiForceCompany/YetiForceCRM/pull/10273

**Comment by mariuszkrzaczkowski** [comment]
I updated the package 5.1.0_ServicePack_v4.zip https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.1.0
