### ISSUE TITLE
Export Pdf Invoice

### ISSUE THREAD

**Issue by rezaizadi** [YetiForceCompany/YetiForceCRM#1042]
For example : after click for export pdf at invoice module page go to root index.php blank .

**Comment by rezaizadi** [comment]
Hello,
but yet after click for export pdf at invoice module page go to root index.php blank .

**Comment by MaciejStencel** [comment]
Hi,

Could you direct me to invoice record that you want to print?

I was testing this record:
https://demo.yetiforce.com/index.php?module=Invoice&view=Detail&record=600

I've fixed one error and now it's printing properly. Can you post here a link to record that You want to print as PDF. Maybe there must be specyfic record with specyfic data that is causing problems.

**Comment by bpabiszczak** [comment]
Please check list view.

**Comment by MaciejStencel** [comment]
Rezaizadi it seems that i was fixing completly diffrent bug. Thats why we need more informations. Like for example record id.

Your error was fixed, but please test it if it's the thing You were after :)

I could see problem You described in this invoice:
https://demo.yetiforce.com/index.php?module=Invoice&view=Detail&record=602

It is now printing without any problems.

**Comment by rezaizadi** [comment]
I replaced $robocza = fetchGroupName( $field ) with $robocza = getGroupName( $field ) at yeti V2.0
but have problem at list view and detail view after click export redirect to blank page.

**Comment by MaciejStencel** [comment]
Please implement all changes as in this revision:
https://github.com/YetiForceCompany/YetiForceCRM/commit/9ff9c7d4c64863364d51ac898f5eaed12d954f4a

If you still have problems please direct me to record that is causing problems in demo.yetiforce.com

**Comment by rezaizadi** [comment]
ok thanks i will change and test this revision 9ff9c7d.
i have not user and pass for login demo.yetiforce.com

**Comment by MaciejStencel** [comment]
Please excuse me, demo is our private testing crm.
So You had problem on your private crm. This revision should fix Your problem if it was that.

If it wont fix it, it will be best if You could try to recreate few records in test.yetiforce.com (login and pass autocompleted). And check there, files can be a bit outdated but if You can recreate there problem it will be easy for us to look into it and help You.

**Comment by rezaizadi** [comment]
show this error at test.yetiforce.com after click export PDF invoice:


Fatal error: Cannot use isset() on the result of a function call (you can use "null !== func()" instead) in /home/yetiforce1/domains/test.yetiforce.com/public_html/modules/OSSPdf/PDFExport.php on line 24

**Comment by MaciejStencel** [comment]
This test is a mirror of last full release so in that case Yetiforce 2.0.
This error was fixed on 25th may in YF 2.0.20.

Here is the revision that fixed above error: https://github.com/YetiForceCompany/YetiForceCRM/commit/71b6e9d601211118fc1cfce8d981c81232dec144
