### ISSUE TITLE
 Sub-Category to be Selected Automatically when Main-Category is selected

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10434]
Hi, I have created a Main-category naming Men and two sub-category naming Tees & Hoodie from Fields-Folders Under Standard Modules. 
Now, When I select the Main-Category "Men" I want the sub-category to be selected automatically.

So how this can be done?

Please help.
Version4.4

**Comment by vovpff** [comment]
Are you talking about Picklist or trees?

**Comment by indrabhusanroy** [comment]
trees

**Comment by vovpff** [comment]
Selfmade handler what triggers with some conditions.
