### ISSUE TITLE
[PL][Pytanie] Wyłączenie powiadomienia w Zgłoszeniu

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10433]
Witam, 

W mojej konfiguracji nie używamy w firmie modułu Kontrahentów i Umów wsparcia SLA, więc chciałem zapytać czy jest możliwość wyłączenia poniższego komunikatu?
![image](https://user-images.githubusercontent.com/21024857/57772839-d51dda00-7716-11e9-8a0d-f94e533d71f7.png)

**Comment by davide-alghi** [comment]
Witam, tak.

You need to disable "Service Contracts" (Umów wsparcia SLA modułu) module.
here
https://gitstable.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List

![issue10433](https://user-images.githubusercontent.com/48508691/57779232-fd610500-7725-11e9-8362-71fc04d5db1b.jpg)

Same thing for Vendors (Kontrahentów)

**Comment by mrzewnicki** [comment]
I tred what you offered but there is still norification. 
![image](https://user-images.githubusercontent.com/21024857/57857281-15508b80-77ef-11e9-88f0-5eaaa35f323d.png)
![image](https://user-images.githubusercontent.com/21024857/57857323-24cfd480-77ef-11e9-962d-8a906c971795.png)

**Comment by davide-alghi** [comment]
Sorry mrzewnicki, :(
you are right.

You have also to set $CHECK_ACCOUNT_EXISTS variable to "false" in /config/Modules/HelpDesk.php

```PHP
/** Check if account exists */
public static $CHECK_ACCOUNT_EXISTS = false;
```
Please try this and feedback here.

**Comment by mrzewnicki** [comment]
Yes it's work. Thank you very much!!
