### ISSUE TITLE
Cannot update organization primary address

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#1043]
I cannot update organization primary address.

I notice when I put a primary email address into an organization, the email address becomes part of the organization name and that is how it looks.

ExampleCompany bob@examplecompany.com is the relation added.

I tried to update an organization's email address and the system gives me an error and says
"There is already and organization with Examplecompany bob@examplecomany.com"

Is that how the CRM should work?

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
1. I don’t know what is exactly the problem?
2. It seems that you configured fields in a panel tab for searching [and probably that’s why you see a name and an email]
3. Please do the following:
•	Describe step-by-step how to reproduce the error on https://test.yetiforce.com 
•	Describe what exactly is the problem and how this should work in your opinion.
