### ISSUE TITLE
New User Creation 

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10435]
Is there a way to allow a user to create new users, roles and profiles. But I don't wan't to make that user admin as only admin can create new users/roles/profiles.

I only want this user to be able to create new users/roles/profiles only. I don't want to provide admin rights to this user type. 

Also, if the above is possible, then I don't want this user type to view or edit admin user credentials.---------------This is not a mandatory requirement.

version:4.4

Thanks.

**Comment by mariuszkrzaczkowski** [comment]
currently it is not possible
