### ISSUE TITLE
[Question] Multi Depend Field       

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#10437]
### Description

I see on closed pull request that we have a Multi Depend field, but i can't see in the system.
This is the pull request: https://github.com/YetiForceCompany/YetiForceCRM/pull/8240
Field was removed?

**Comment by davide-alghi** [comment]
Hi cltvchannel,

field type is available for BE
![issue10437_1](https://user-images.githubusercontent.com/48508691/57834407-84f95300-77bc-11e9-817d-c0e4fd35cfbf.jpg)

not available for FE
https://github.com/YetiForceCompany/YetiForceCRM/blob/b87ab907d978e2b7abdcb7efab4b213f156c90ab/modules/Settings/LayoutEditor/models/Module.php#L83

![issue10437_2](https://user-images.githubusercontent.com/48508691/57834439-92164200-77bc-11e9-9512-e063fb0b02ec.jpg)

![issue10437_3](https://user-images.githubusercontent.com/48508691/57834468-a4907b80-77bc-11e9-825c-7fc8105f2831.jpg)

**Comment by cltvchannel** [comment]
Ok. Thanks !
