### ISSUE TITLE
SMSAPI brak Pro/2Way tylko Eco

### ISSUE THREAD

**Issue by ArturGabrys** [YetiForceCompany/YetiForceCRM#10432]
### Description

Witam,
Czy YF ma możliwość wysyłać SMSy Pro/2Way za pomocą SMSAPI? Podczas dodawania tokenu mam do wyboru tylko wiadomości ECO. Nie wiem czy to u mnie jakiś błąd czy po prostu nie ma takiej możliwości. Oprócz ustawienia własnej nazwy wyświetlanej bardzo zależy mi na tym aby ewentualne odpowiedzi odbiorców zapisywały się gdzieś w CRMie. 

Pozdrawiam

**Comment by bpabiszczak** [comment]
Domyślnie nie ma takiej możliwości, trzeba pewnie poświęcić kilka godzin aby dodać nowe opcje.
