### ISSUE TITLE
Problem in transfer to another hosting

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10449]
Hi, I am trying to transfer to another hosting and domain. It is showing this error message:

 PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'docker_yeti521'@'localhost' (using password: YES) in /home3/docker/public_html/vendor/yetiforce/yii2/db/Connection.php:687

#1 /home3/docker/public_html/app/Db.php(181): yii\db\Connection->createPdoInstance()
#2 /home3/docker/public_html/vendor/yetiforce/yii2/db/Connection.php(613): App\Db->createPdoInstance()
#3 /home3/docker/public_html/vendor/yetiforce/yii2/db/Connection.php(996): yii\db\Connection->open()
#4 /home3/docker/public_html/vendor/yetiforce/yii2/db/Connection.php(983): yii\db\Connection->getMasterPdo()
#5 /home3/docker/public_html/vendor/yetiforce/yii2/db/Command.php(253): yii\db\Connection->getSlavePdo()
#6 /home3/docker/public_html/vendor/yetiforce/yii2/db/Command.php(1143): yii\db\Command->prepare(true)
#7 /home3/docker/public_html/app/Db/Comma in /home3/docker/public_html/vendor/yetiforce/yii2/db/Connection.php on line 624

PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1650 but version 1654 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
Version:4.4

After Transfer, nothing is showing up.

Please help.

Thanks.

**Comment by mariuszkrzaczkowski** [comment]
You have a problem with database permissions.
Check if you entered the password correctly and if this user has permissions for this database.

**Comment by indrabhusanroy** [comment]
There is no problem with database permissions. I have checked the password and the user permissions for this database. Everything is ok, but the application is not working somehow.

**Comment by mariuszkrzaczkowski** [comment]
this is a message from the database, not the application
https://stackoverflow.com/questions/31154124/sqlstatehy000-1045-access-denied-for-user-usernamelocalhost-using-cakep
