### ISSUE TITLE
[PL][PYTANIE] Skaner maili - tworzenie szansy sprzedaży

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1044]
Zastanawiam się czy istnieje opcja automatycznego tworzenia szansy sprzedaży przez skaner maili ?
W tej chwili możemy jedynie zautomatyzować tworzenie zgłoszeń, ale w moim przypadku większość (90% maili nie będących odpowiedzią na wysłane oferty/negocjacje) jest czymś w stylu szansy sprzedaży. Może warto rozważyć takie rozwiązanie ?

Cały czas próbuję ułożyć sobie w głowie sposób pracy z systemem przez kilka osób - szczególnie chodzi mi o wysyłanie/odbieranie maili od klientów - możecie podać jakiś przykład z Waszego doświadczenia ?
Wszyscy korzystają z jednego maila, czy każdy ma podpiętą swoją skrzynkę ? W jaki sposób prowadzić korespondencję z klientami (jednocześnie kilka osób negocjuje z kilkoma osobami), żeby całość była spójna i zarazem wygodna do pracy ?

**Comment by bpabiszczak** [comment]
Aktualnie istnieje tylko półautomatyczne metoda polegająca na tym, że w module produkty sprzedane masz przycisk, który pozwala Ci zaznaczyć X produktów na liście i automatycznie dla nich wygenerować X szans. 

Aby móc automatycznie tworzyć szansę z poziomu skanera, wystarczy skopiować akcje tworzenia helpdesk i zmiany w niej odpowiednich linijek kodu. Nie jest to trudne.

Kolejne pytania jakie zadajesz czyli sposób pracy w systemie, jest tematem rzeką. Każdy ma swoją wizję i każde rozwiązanie ma swoje plusy i minusy. My dla wsparcia, marketingu itd. stosujemy skrzynki ogólne typu info@ help@, jednakże każdy pracownik posiada swoją indywidualną skrzynkę i tylko z niej odpisuje. Nie ma czegoś takiego jak jedyna słuszna druga. System jest na tyle elastyczny, że pozwala na realizacje różnych procesów biznesowych na różne sposoby. 

Aby określić najlepszą metodę pracy to należy:
 - albo zlecić wykonanie analizy przed wdrożeniowej 
 - albo usiąść we własnym gronie i przy okazji wdrożenia systemu klasy CRM omówić procesy i je zoptymalizować.
