### ISSUE TITLE
[Question]  Is there any way to prevent "Account" Duplication?          

### ISSUE THREAD

**Issue by Rizzao** [YetiForceCompany/YetiForceCRM#10445]
Hello there. I just want to say - Amazing product, I am loving it.
Anyways, is there any way to prevent "Account" Duplication? 
For example by unique VAT numbers?
    PS. I am using YetiForce 4.4

**Comment by davide-alghi** [comment]
Hi Rizzao,
read this #8731 (YF 5.0)

Maybe you have to check VAT number before insert.

**Comment by vovpff** [comment]
@davide-alghi this is cool idea with VAT but how?

**Comment by davide-alghi** [comment]
![issue_10445](https://user-images.githubusercontent.com/48508691/58378430-fe9af900-7f93-11e9-8a69-186430bf83d6.gif)

**Comment by vovpff** [comment]
Thanks! but this is manual solution what takes some time. In this case there is no problem to create new company with the same VAT. Better way to prevent saving of record if VAT or account already exists. This functionality was available in vtiger but missed in yety.

**Comment by davide-alghi** [comment]
Hi Vladimir,
you are right, but manual solution is the only way.
I know about VT duplication check: I think YF-team dropped duplication check there was a valid reason

**Comment by vovpff** [comment]
I think so!

**Comment by konadrian** [comment]
In the current version we don't have this mechanism. You can use a solution provided by @davide-alghi
Sometimes we do this mechanism for our individual clients depending on their expectations for the type of fields.

**Comment by rioshaz** [comment]
@konadrian has the duplicate check been implemented yet ? i mean a this is very basic featue and needs address asap as how can multiple users work if there is no duplicate check and this kills the whole crm productivity...

**Comment by mariuszkrzaczkowski** [comment]
we already have it, see it
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=EventHandler&view=Index
![image](https://user-images.githubusercontent.com/10198654/86497291-628c1580-bd81-11ea-9504-79fcb576cfac.png)
https://github.com/YetiForceCompany/YetiForceCRM/blob/87545422218568db7c8c31ef3f25a98adbcda7ff/modules/Accounts/handlers/DuplicateVatId.php#L21-L42
