### ISSUE TITLE
Turn off Mail sound notification     

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#10454]
I would like to know where and how to turn off the mail sound notification.

It keeps having a sound every few minutes, where can this sound be muted.

I am using the latest version of yetiforce crm 5.1.0

I am using a Linux shared hosting  account

![turn off sound notifiction](https://user-images.githubusercontent.com/7829825/57922395-3b9b2780-78d2-11e9-90a8-44e778d10b83.png)

How to turn off would be great
Thanks

**Comment by davide-alghi** [comment]
in /config/Sounds.php set $IS_ENABLED to false

```PHP
public static $IS_ENABLED = false;
```

**Comment by bangde** [comment]
Thank you .

This should be an option in the system notification are to turn on or turn off.

Thanks for your help.

I have turned off the sound

**Comment by jmginfor** [comment]
I am wondering if a similar process can be done to disable the "flash animation" for those notifications ?

**Comment by mariuszkrzaczkowski** [comment]
Everything is possible

**Comment by jmginfor** [comment]
Very useful thanks!
