### ISSUE TITLE
[bug] Bom dia não consigo importar contatos, sempre da um erro no campo phone ou celular

### ISSUE THREAD

**Issue by projetus2** [YetiForceCompany/YetiForceCRM#10455]
# 🐞 bug report

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by projetus2** [comment]
sempre que faço upload de um arquivo  csv para contatos ou leds, seleciono os campos e clico para iniciar mas logo aparece uma mensagem de erro em um dos campos, ja tentei inclusive com arquivos exportados do meu vtiger

**Comment by projetus2** [comment]
sempre que faço upload de um arquivo csv para contatos ou leds, seleciono os campos e clico para iniciar mas logo aparece uma mensagem de erro em um dos campos, ja tentei inclusive com arquivos exportados do meu vtiger

**Comment by vovpff** [comment]
One more time and in english

**Comment by projetus2** [comment]
whenever I upload a csv file to contacts or leds, I select the fields and I click to start but soon an error message appears in one of the fields, already tried with files exported from my vtiger

**Comment by vovpff** [comment]
Logs needed...

**Comment by konadrian** [comment]
We need more information about your problem
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/how-to-report-bugs

**Comment by rskrzypczak** [comment]
It means that in imported data you got a phone number in the wrong format.
It's best to fix the phone number format but if you don't want to do that you can also disable number validation in `config\Main.php` -> $phoneFieldAdvancedVerification
