### ISSUE TITLE
[Question] Looking for very simple template of webform for contacts          

### ISSUE THREAD

**Issue by Marshal4582** [YetiForceCompany/YetiForceCRM#10462]
Can anyone show me please a sample of basic html webform connected to contacts module (or any other). Thank you in advance

**Comment by davide-alghi** [comment]
Webforms are not available.

You can meet your needs via mailscanner (email form) or via REST Api (outer form)

**Comment by Marshal4582** [comment]
Thats what I mean... would like to learn how to use REST to connect form with CRM

**Comment by davide-alghi** [comment]
You can find info here
https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+api+OR+rest+OR+Webservice+

no docs are available

**Comment by konadrian** [comment]
We don't currently have API documentation, we will create it but we don't know when. You can find a lot of info at github. https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+api+OR+rest+OR+Webservice+
