### ISSUE TITLE
[Question]  Regarding Multiple SMTP and Email Accounts

### ISSUE THREAD

**Issue by acsinsurancegroup** [YetiForceCompany/YetiForceCRM#10467]
### Description
 

How do you account for multiple different SMTP and email accounts within the system? For example, let's say there's 50 users in the system. Let's assume that 10 of them have Gmail accounts, 10 have Outlook/Hotmail accounts, 10 have Yahoo email accounts and the remaining 20 have corporate email accounts based on the domain the system is setup on. How would we accomplish this in the latest 5.1 version so all 50 users can send and receive emails within the system? Greetz :)

**Comment by acsinsurancegroup** [comment]
Does anyone know how to do this? @bpabiszczak said this could be done easily in the system. Can someone please point me in the right direction? Thank you :)

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/58397486-7bd87380-8051-11e9-99d2-21167aada1af.png)
![image](https://user-images.githubusercontent.com/10198654/58397487-7ed36400-8051-11e9-8a7a-c4dc33342a44.png)

**Comment by acsinsurancegroup** [comment]
Thank you @mariuszkrzaczkowski that's what I was looking for :)

**Comment by simple-AMS** [comment]
Actually @mariuszkrzaczkowski How do you add the multiple SMTP servers to match all of the Imap servers that were added? I'm trying to accomplish this in the new 6.1.0 version. Thank you!

**Comment by mariuszkrzaczkowski** [comment]
there is no easy way to do it :( 
https://www.google.com/search?q=roundcube+multiple+SMTP+servers&oq=roundcube+multiple+SMTP+servers

https://gist.github.com/kimbtech/b6b08f1778420766ee1a2d24117d4871
https://github.com/roundcube/roundcubemail/issues/6129

**Comment by simple-AMS** [comment]
> there is no easy way to do it :(
> https://www.google.com/search?q=roundcube+multiple+SMTP+servers&oq=roundcube+multiple+SMTP+servers
> 
> https://gist.github.com/kimbtech/b6b08f1778420766ee1a2d24117d4871
> [roundcube/roundcubemail#6129](https://github.com/roundcube/roundcubemail/issues/6129)

@mariuszkrzaczkowski I'm learning that. It works fine in version 5.3.0 but with that said I have two domains that are pretty identical and are on the same server and for the most part the server settings are the exact same. The email server is on the same server for both accounts.

The one I'm needing help with at the moment however is one email address on Office365 business email and the other is a G Suite business account. I have the servers showing up in the drop down and can log into one but no matter what I do, login always fails for the gmail one.

The Microsoft one logs in with no problem and I can even send emails from it. The inbox however NEVER loads up the incoming emails.

**Comment by mariuszkrzaczkowski** [comment]
look at this
![image](https://user-images.githubusercontent.com/10198654/104456858-930f0080-55a9-11eb-8ae5-f41f88f6c0f3.png)

**Comment by simple-AMS** [comment]
@mariuszkrzaczkowski Thanks but that doesn't work because again we have some on Microsoft Office 365 business email and some on G Suite Google business email addresses.

The picture you sent would work if everyone was only on Gmail, however that is not the case.

The most current version of VTiger has the ability to use 100's of SMTP servers so I don't understand why it's so hard to accomplish this with YF. It's a standard feature with just about every CRM out there now.
