### ISSUE TITLE
[Question]           Sync Google contacts

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#10460]
Does yeti have a way to sync with Google Contacts with yetiforce like in vtiger

I have been told about CalDAv but not sure how that works.

Is there any documentation or tutorial to get this to work.

Guys you really need better documentation. Hire some documentation specialist to work on your documentation. A great product but lacking documentation or tutorial videos.

Thanks

**Comment by z0lo13** [comment]
caldav its an app for android - in IOS i am not sure how it could be done. 
1. Enable it in webservices.php 
2. Then add users in Setting>Integration>DAV Applications.

**Comment by bpabiszczak** [comment]
caldav = calendar
carddav = contacts
