### ISSUE TITLE
Mapping- How it works?

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#10461]
I would like to know how does it work.

For example, if I have a lead can I map certain fields to contacts so I can create a contact from the lead. At the moment I can create an account from a lead but I can not convert the lead to a contact, vendor or 
partner.

I am hoping to be able to use this Mapping technique to be able to do this.

I hope someone can explain how mapping works and what it is used for and can it be used for what I would like to do.

Thanks

**Comment by vovpff** [comment]
This is tool for quick transfer data from one module to another. Short video:
![mapping expl](https://user-images.githubusercontent.com/8545791/58004504-0bc76c00-7aec-11e9-9e2a-bbdba4c0a74e.gif)
