### ISSUE TITLE
Problem Install, no execute

### ISSUE THREAD

**Issue by jjnavarros** [YetiForceCompany/YetiForceCRM#10463]
Dear Sirs,
I've been trying for two days to install the Yeti, and I can not get past the first welcome screen. I have used different versions of PHP, as well as two last versions of the system, but it still does not work.

I have followed the instructions, step by step, but I do not know what is missing and I do not see.

The page is:
www.reforcanary.es/intranet

**Comment by dimitrisand** [comment]
Firstly you have to give the appropriate access to the folder where cam is installed . Also check your server requirements.

**Comment by jjnavarros** [comment]
I checked the server options, and they're fine. I changed the permissions to the folders and it remains the same. Until you try to install it through Softaculous, through the server, and there is no way.
I have read from the we, the instructions, and apart from not saying any special requirement, it does not say any localized faults.

**Comment by dimitrisand** [comment]
Did you create the db with innodb ? 
Check if extension=intl is enabled. php.ini
Is there a conf file? It would be good to take a look.

**Comment by mariuszkrzaczkowski** [comment]
check all server logs

**Comment by rojecas** [comment]
@jjnavarros I installed Yetiforce using both methods through softaculous and directly over the server.

"... and I cannot get past the first welcome screen", please be more specific what does mean? If get the first screen, you have the basic prerequisites and does not need to change your PHP, you already have the database created?

The following video is very useful: https://www.youtube.com/watch?v=zpo6jr2k0YA

If you want can write in Spanish too.

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/58910229-a98e7e00-871d-11e9-854b-2f4d11008ce1.png)
cool background

Problem solved?

**Comment by paula-w** [comment]
I'm closing the issue since the author isn't responding anymore - the problem might have been solved.
