### ISSUE TITLE
Entity fields should have possibility to relate to contacts

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#1047]
As it was mentioned in mailing list, it seems to be enough reasons to be able to relate entity modules to organizations AND contacts. Without considering giant quantity of use cases which are based on Contacts as a primary customer this function was removed. It reflecting even in Portal operations. Looks like role of customer who got First and Last name has been here depreciated. This is very wrong operational logic which will not help YetiForce in expansion. 
I would like to ask (not only in my name) to return to previous model and keep entity modules running in line with vtiger, so migrations and other goodies can be applied without issues.. Additional functions and eventually logic in choosing model of use case could be enabled as a separate configuration.

**Comment by eptapsyxos** [comment]
+1

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1063

**Comment by waran70** [comment]
So, it means that yetiforce will not get back to the previous state where we can assign Contacts to entities records? Making sure as my customer pressing me (actually two of them).

**Comment by reetp** [comment]
Yes, funny I noticed it was still wontfix, and that the goalpost seemed to have been moved somehow to 1063, and that despite the mail on list from Katarzyna "We will read every single comment and reply to them on Monday." I am starting to wonder which Monday they are referring too.

Hmmmm.. really starting to question the whole ethic here.

**Comment by bpabiszczak** [comment]
We will describe in detail our point of view in Issue #1063. In regards to your question, there is a possibility to relate many contacts M:M in all documents, projects, tickets, opportunities etc. If it isn’t somewhere, it will be added soon. However, the record will have to be related with Accounts, e.g.:

An invoice will be related to Account [1:M] and additionally you select many contacts on an invoice [M:M]

**Comment by waran70** [comment]
Than at least pre-filtering on related list on contacts will be needed. 
In vtiger if we relate invoice to organization, and than I wanna add contact, I will see list of contact ONLY assigned to current organization. In this way you are limited in getting into human error. Having option to relate it to contacts out of organization to which record is preliminary assigned will be additional advantage BUT, pre-filtering will be required.
Actually standard filters in related lists was claimed many times in vtiger forum but seems like it was too comfy for users in open source version. I will create separate ticket on this matter. Please comment on above so we know where we going to

**Comment by reetp** [comment]
Waran70 +1
A Contact from the Account HAS to be linked to the Invoice (and any other docs) No Contact, no use - well, it might be for some individual edge cases. But I don't think that is the majority of CRM users.
