### ISSUE TITLE
Feature Request:Αdd Widget Directly From Module

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1048]
Without to have to move to settings...on summary page 
Example
![widgetinside](https://cloud.githubusercontent.com/assets/6897502/8144054/d21b0dda-11d2-11e5-86e6-7674ba6f7f8f.jpg)

**Comment by bpabiszczak** [comment]
If we add this option it will work in the same way as it works now on the desktop.

Unfortunately, the interface is going to be changed and optimized soon so if you won't like it, we will come back to this topic. The working principles for widgets will be changed too.
