### ISSUE TITLE
Instalacja [bug] 

### ISSUE THREAD

**Issue by soplica** [YetiForceCompany/YetiForceCRM#10480]
# 🐞 bug report

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.1.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by soplica** [comment]
Po instalacji aplikacji, imporcie danych , dokonaniu ustawień mailowych itp ... na innym komputerze po przejściu na adres strony wyświetla mi sie wciąż kreator instalacji. Czy po instalacji trzeba usunąć jakiś plik? zmieniłem nazwę katalogu install ale to nie pomaga.

**Comment by soplica** [comment]
Obecnie widzę, że nie może zostać wygenerowany poprawny klucz unikalny dla sesji i dlatego wpis w index.php
if (!\App\Config::main('application_unique_key', false)) {                                                                                                                                                  
<------>header('location: install/Install.php');
}
​
Przekierowuje na folder instalacyjny.

**Comment by mariuszkrzaczkowski** [comment]
uruchom pełne logi, coś pewnie jest nie tak z konfiguracją skoro nie może wygenerować klucza

**Comment by rskrzypczak** [comment]
> Czy po instalacji trzeba usunąć jakiś plik? zmieniłem nazwę katalogu install ale to nie pomaga.

Po poprawnej instalacji katalog install powinien zostać usunięty automatycznie, jeżeli go posiadasz, to znaczy, że błędnie przeprowadzono proces instalacji, co potwierdza Twój kolejny komentarz 


> if (!\App\Config::main('application_unique_key', false)) {
> <------>header('location: install/Install.php');
> }

Brak wygenerowania podstawowych plików konfiguracyjnych.
Wyczyść bazę danych, cache przeglądarki, zweryfikuj konfigurację serwera, włącz logi systemowe i uruchom ponownie instalacje systemu. Nie powinno być problemu.
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa

P.S.
 Jeżeli na jednym komputerze Ci działa, a n a drugim nie - wyczyść cache przeglądarki
