### ISSUE TITLE
Calendar: Assigned record does not update to members after modification or deletion

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#10483]
The Bug:

Previously assigned entry in calendar to other users (secretary does the task) is doing this behavior:

1.- Trying to modify the record (date or hour) it does the job but in the assigned users the old one is still appearing only in the assigned users

2.- When deleting a date (record) it is not deleted in assigned users, only in the user that is doing the deletion.

How to detect the bug:

1.- Create a new entry in calendar: a phone call at 14:00 of today
2.- Assign this call to another member (like if you were a secretary)
3.- Try to modify the entry from 14:00 to 17:00 (you will see in your calendar that it is modified. The assigned user will see the new entry and the old one)
4.- Try to delete de entry. In your calendar (secretary) the record is deleted, but in assigned user it is appearing yet.

### 👎 Actual Behavior
The modification or deletion will keep old record in assigned user

### 👍 Expected Behavior
When modifing or deleting a record it will take place in all assigned users

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
No special error is reported in logs

| YetiForce	4.4	apache 2.6 php 7.1 on Centos 7	mariaDB

**Comment by santyabreu** [comment]
Solved it. Before @paula-w closes the ticket.

For your interest: It is caused by the spaces in the personalized statuses that you can bring into modules list. Take care to not put spaces in the personalized status and it will work perfectly. Maybe a bug...

Best Regards

**Comment by mariuszkrzaczkowski** [comment]
can you give an example?with screenshot

**Comment by santyabreu** [comment]
Yes of course:
It is in the another threat:
https://github.com/YetiForceCompany/YetiForceCRM/issues/9229#issuecomment-516169768
