### ISSUE TITLE
[PL][PYTANIE] Nie uzupełniające się pole adresu odpowiedzi na maila

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10495]
Witam, 

Podczas wyboru "Odpowiedz wszystkim" lub "Odpowiedz" na rekordzie maila firmowego nie uzupełnia się pole odbiorcy automatycznie tylko użytkownicy muszą je uzupełniać ręcznie. Czy to jest błąd?
W Cliencie Roundcube odpowiadając na maila pole uzupełnia się prawidłowo, więc może plugin "yetiforce" ?

![gif1](https://user-images.githubusercontent.com/21024857/58232706-8685c680-7d3a-11e9-96e3-ec80f6b14787.gif)

**Comment by mariuszkrzaczkowski** [comment]
Sprawdź czy w workflow masz aktywne zadania od generowania książki adresowej

**Comment by mrzewnicki** [comment]
Jest i działa:
![image](https://user-images.githubusercontent.com/21024857/58237617-d61dbf80-7d45-11e9-9287-2a8e2129b86a.png)

**Comment by mrzewnicki** [comment]
Zaktualizowałem bibliotekę Roundcube'a i działa.
