### ISSUE TITLE
[Question] Własny moduł do załączników          

### ISSUE THREAD

**Issue by espeoceka** [YetiForceCompany/YetiForceCRM#10498]
### Description

Cześć, zwracam się do was z pytaniem odnośnie dodawania załączników. Problem z którym się spotykam wymaga aby dokumenty były podzielone na kategorię np dokumenty dotyczące spłat w ramach umowy A muszą posiadać pewne pola, a w ramach umowy B inne. Czy istnieje sposób na rozwiązanie tego problemu w ramach samej aplikacji ? 

PS. Problem wydaje się banalny niestety pola dostępne z poziomu edytora odnoszą jedynie do plików graficznych

**Comment by mariuszkrzaczkowski** [comment]
W module dokumentów masz pole kategorii   do tego

**Comment by espeoceka** [comment]
Panie Mariuszu,

Bardzo dziękuję za szybką odpowiedź i przepraszam że nie wyjaśniłem tego
dokładniej.
Jedne dokumenty będą dotyczyły tematów finansowych ( egzekucja długów w
postępowaniu sądowym oraz spłaty częściowe ) i muszą mieć całkiem inny
zestaw pól niż dokumenty ogólnego przeznaczenia.
Kategorie/Foldery niestety pasują jedynie do zwykłych dokumentów. Być może
istnieje opcja warunkowego ukrywania bloków lub inna możliwość przypisania
pól ?

Z góry Dziękuję




czw., 23 maj 2019 o 09:59 Mariusz Krzaczkowski <notifications@github.com>
napisał(a):

**Comment by bpabiszczak** [comment]
Inne pola = inny moduł. Np. Umowy SLA w systemie to inny moduł pomimo, że to też dokumenty, ale mają swoją logikę i są częścią procesu wsparcia.
