### ISSUE TITLE
[Question] Print Receipts from Thermal Printer

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10499]
Hi, May I please be assisted with linking the software with a Thermal Printer?

It would print an Invoice as a Receipt via a Thermal Printer, most likely an Epson printer. Instead of the A4 Invoice printed over a standard office printer.

**Comment by paula-w** [comment]
This is @bpabiszczak 's response:
We would have to have a printer like this in order to be able to test the printouts. If you can cover the costs of that then we will be able to help.
