### ISSUE TITLE
Your system was not properly registered

### ISSUE THREAD

**Issue by craigharrington** [YetiForceCompany/YetiForceCRM#10503]
![Screenshot 2019-05-23 at 9 39 08 AM](https://user-images.githubusercontent.com/33829554/58238204-bcc54500-7d3e-11e9-82d5-fb2fb2381e4e.png)

"Your system was not properly registered. Check registration status, an incorrectly registered system is not compliant with the license.

No e-mail address was added to company details. If you want to receive newsletter Fill in the required information."

No other link or button works

**Comment by paula-w** [comment]
Hi
Please send us an email to registration@yetiforce.com about this issue in order not to disclose any company information publicly.
Thanks
