### ISSUE TITLE
[Question]   Determination of identity value in mail header.   

### ISSUE THREAD

**Issue by quasi754** [YetiForceCompany/YetiForceCRM#10510]
Hello,

I'm curious what actually determines the value of identity when message is composing? Of course from YetiForce level because from roundcube level i catched it. In yetifoce.php plugin i didn't find any functioons responsible for manage id of identity, only in jacascript editor and that curious me ;). I suspect that function in js is onlye t select manually .

Thank you for reply.

**Comment by z0lo13** [comment]
> 
> 
> Hello,
> 
> I'm curious what actually determines the value of identity when message is composing? Of course from YetiForce level because from roundcube level i catched it. In yetifoce.php plugin i didn't find any functioons responsible for manage id of identity, only in jacascript editor and that curious me ;). I suspect that function in js is onlye t select manually .
> 
> Thank you for reply.

@quasi754 Exactly which header are you interested in?
