### ISSUE TITLE
[bug] [list view] "Time" is not displayed for related "Calendar - Start date & time" field

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#10518]
Hi,

Steps to reproduce the issue :

1- go to YF official demo
2- Go to system settings / standard module / edit fileds for Contact module
3- Select Contact Module and Create a 1:M field related to Calendar.
4- Go to Contacts module, list view.
5- Create (or edit) a list view and add "Calendar - Start date & time" column.
6- Save

--> 	In "Calendar - Start date & time" column, **only date is displayed and time is not**.

![display_issue_yetiforce](https://user-images.githubusercontent.com/2930560/58338770-a99e9c00-7e48-11e9-8d03-6cbfb9ad9de2.jpg)

**Comment by acsinsurancegroup** [comment]
@apcloic What I did to get around this was to go into the Custom Views area which is under the Search and Filters area and now called Filters - Configuration. 

Then select the module you need this to display in and select the Date field and then the Time field and you should be good to go. Not sure about the Contacts module like you posted but this worked for me in the Projects section.

I then went into the Language Management and changed the Date and Time field to just Start Date and it had the Time separately anyway so it showed up when I selected it as noted above.

Hope that helps :)

**Comment by apcloic** [comment]
@acsinsurancegroup Thanks a lot for the workaround. 
However, even if it's a minor issue, I think it should be reported as a bug.

**Comment by acsinsurancegroup** [comment]
@apcloic Totally understand man :)

**Comment by mariuszkrzaczkowski** [comment]
The error doesn't occur on the developer version.
https://gitdeveloper.yetiforce.com/index.php?module=Calendar&view=List
![image](https://user-images.githubusercontent.com/10198654/76502990-4f0d1580-6445-11ea-83bf-9848bbde9a61.png)

**Comment by apcloic** [comment]
@mariuszkrzaczkowski 
The error still occurs, you did not follow the steps to reproduce the issue.
Your screenshot is about calendar module while I'm talking about contact module with 1:m relation with calendar module.
Regards

**Comment by areksolek** [comment]
From the level of filters, these fields are divided into two parts. If you want to have an hour, you must select an additional field.
![image](https://user-images.githubusercontent.com/25615135/78539742-567cd000-77f3-11ea-9d1f-24198e3454da.png)

**Comment by apcloic** [comment]
@areksolek Yes, I'm aware of this workaround which was already suggested by @acsinsurancegroup  but...this is just a workaround.
Start date **& Time** means Date **& Time**, not only date.
So IMO, the issue still exists and you should not be closed.
