### ISSUE TITLE
[Question] Print from Yetiforce           

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10525]
Hi, how can I achieve printing an Invoice or Quotation directly from Yetiforce without having to first export a pdf file?

**Comment by davide-alghi** [comment]
your question may have many different answers. I try to give a somewhat generic answer. a web-app (YF) cannot directly access computer resources: only the browser can do it (unless you have a dedicated plug-in or java application). the only way to print is to export and print: you can open the pdf directly in the browser and then print without having to download it.

**Comment by vovpff** [comment]
@davide-alghi now impossible to open pdf generated by system without downloading...

**Comment by MyBlissIT** [comment]
Thanks @davide-alghi , I should for the plug-in or java application then

**Comment by davide-alghi** [comment]
@MyBlissIT: thanks to you for your contribution :smiley:

@vovpff: maybe you are right
I'm a little confused :confused:
I just tried to open pdf (from detail view - list view create a zip file) and in some browsers win/linux I cannot get direct pdf browser preview.

With Chrome I can:
- with debian stretch, it opens directly into system pdf viewer, with just a click on YF "Export to PDF" icon
- with windows 8, it opens in Chrome preview (directly into browser) by clicking on bottom bar after file is downloaded

Usually download behavior depend on client, installed plug-in and browser configuration.
I have done a quick check: I'll try again with more time

**Comment by Marshal4582** [comment]
I wish PDF in yeti is as good as PDFMaker for vtiger. At the moment it looks very far away

**Comment by mariuszkrzaczkowski** [comment]
> I wish PDF in yeti is as good as PDFMaker for vtiger. At the moment it looks very far away

What is worse in the yeti pdf?

**Comment by z0lo13** [comment]
> 
> 
> > I wish PDF in yeti is as good as PDFMaker for vtiger. At the moment it looks very far away
> 
> What is worse in the yeti pdf?

1. To create customized product tables great knowledge of yeti php structure needed
2. Slow time for parsing large documents
3. Cant add custom css
4. Floats still dont work
5. Sometimes the width of elements have to be more then 100 to correctly fill a 100% of a page

**Comment by Marshal4582** [comment]
6. Designing tables is a nightmare
7. Designing tables of related modules is a hell
8. Size of generated PDF's are out of mind
9. General user interface very unfriendly 

If someone wanna still argue with above, it means he NEVER use PDFMaker for vtiger. I am far from promoting it, but I wish yetiforce spend some time on analysing this extension, so differences can be better understood.

**Comment by davide-alghi** [comment]
I think all we should have an appropriate communication method (IMHO) :wink:

**Comment by waran70** [comment]
@davide-alghi: you mean a phone call or what?
Guys above are right. Criticism is a part of contribution too.

**Comment by davide-alghi** [comment]
> @davide-alghi: you mean a phone call or what?

I spoke about appropriate comunication "style", mode of expression on posting

> Guys above are right.

I don't put in doubt

> Criticism is a part of contribution too.

You are right

**Comment by paula-w** [comment]
This is @bpabiszczak 's answer:

An answer to the first question has been provided. 

As far as missing PDF functionalities are concerned, you should check out the latest developer version. Currently there is a built in mechanism there, it allows you to decide while generating PDF which columns should be printed in PDF. Our company creates quite a large amount of printouts and the current version of the library is enough for us. When we believe there is something missing in a  library - we add it. When you think something is missing you wait until someone else adds it for you ;)

Why don’t you donate a couple of dollars each month to support the development of PDF? If enough people do that we will be able to improve the library on an ongoing basis.
