### ISSUE TITLE
No list in customer portal . ListView error not found  

### ISSUE THREAD

**Issue by dimitrisand** [YetiForceCompany/YetiForceCRM#10526]
I can login in the portal but no list appears. Althouth there are records (7 records).
Asset not found: layouts/Default/modules/HelpDesk/resources/ListView.js in debugging.

![portal_error_listview](https://user-images.githubusercontent.com/11174205/58385456-7d764d00-7ff9-11e9-9c1e-30bfad4f38f2.png)

**Comment by bpabiszczak** [comment]
The first test version of the client portal 2 will appear together with version 5.2.
