### ISSUE TITLE
[Question] Set "Employee" as CRM "User"

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10535]
Hi, How can I set "Employee" as a CRM "User" or User as an Employee?

So that data is synchronized correctly and activity log is accurate

**Comment by z0lo13** [comment]
+1 Would be great to have that

**Comment by bpabiszczak** [comment]
The "Assigned to" field in the OSSEmployees module is used for this purpose.
