### ISSUE TITLE
[Question] Uploading Images           

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10536]
Hi,

I am trying to edit PDF templates and include Company Logo on the header, I am battling to upload the image file via the interface attached
![image](https://user-images.githubusercontent.com/34719141/58432477-df46bd80-80b2-11e9-8648-ce73cc40b1c1.png)

I have inserted links from different sources and none appears. I tried to upload the logo via Documents but I was unable to source URL.

**Comment by joelbcampos** [comment]
Upload the image via ftp and copy the address of the route insert and ready

**Comment by MyBlissIT** [comment]
Thanks, isn't there an easier way?

Most users are not tech savvy and this route seems to be cumbersome to me

**Comment by neuronetio** [comment]
You can also use base64 representation of the image.

**Comment by MyBlissIT** [comment]
@joelbcampos I am avoiding a scenario where I mess things up: I am guessing I will need to create a new folder and probably name it "Images". 

Where exactly can I save this folder at?

@neuronetio I do not know what that is and how I can achieve that feet?

**Comment by rafalpospiech** [comment]
https://www.base64-image.de/  copy image button

**Comment by vovpff** [comment]
Stupid question: how to put Base64 code to template?

**Comment by rafalpospiech** [comment]
best way (probably the only) is to click on `Source` button from editor header and add `<img src="yourbase64" />` where you want

**Comment by rafalpospiech** [comment]
ckeditor image dialog will freeze when you paste base64 into url :/

**Comment by rafalpospiech** [comment]
@bpabiszczak @mariuszkrzaczkowski maybe we could easily implement something like [this](https://codepen.io/AshDevFr/pen/yyXQxQ) along with the standard image url?

**Comment by MyBlissIT** [comment]
It would be easier if the image icon directed a user to their PC Folders, like it does when you upload a Logo.

**Comment by MyBlissIT** [comment]
> Stupid question: how to put Base64 code to template?

It is stupid to you yes, but this platform exists so we can ask questions that will prevent us from messing things up.

**Comment by MyBlissIT** [comment]
> You can also use base64 representation of the image.

I tried this and the screen locks. I practically cannot do anything after I have inserted the image code.

**Comment by rafalpospiech** [comment]
@MyBlissIT did you paste base64 inside `src` attribute of the `<img />` tag?
Did you click on `Source` button from editor header?

**Comment by rafalpospiech** [comment]
If you are editing the source code - content is an simple text area so it should not crash, but when you edit as wysiwyg then there might be some problems. If you are pasting base64 into url field in image dialog then of course it will hang as I mentioned earlier.

**Comment by joelbcampos** [comment]
@rafalpospiech Although I have always done it through ftp, it seems an interesting thread. Could I do a gif with the steps that it performs?
Thanks for your dedication.****

**Comment by rafalpospiech** [comment]
Of course, thanks.

**Comment by rskrzypczak** [comment]
There are now three ways of adding images:
1. Using the button in the wysiwyg menu
 
![image](https://user-images.githubusercontent.com/10221999/75349371-f23a2880-58a4-11ea-8644-044cdbebd7d9.png)

2. Specifying the address directly in the document source, eg. 
`<img src="https://public.yetiforce.com/gallery/uploads/big/e06faf7b08dc7f944a784daada1e8e4e.jpg" />`
It requires adding the domain to exceptions. We do not recommend this method due to security concerns
3. Pasting the image using CTRL + V, eg. prtscr ->CTRL+V (in the wysiwyg window)
