### ISSUE TITLE
[bug] No insert link email

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#10540]
It does not save the links inserted in email templates.
I try to insert a link like in the description but when the link template is selected it does not appear.
I have tried to do the same in gitdeveloper and Gitestable, but the same thing happens.

![Proyecto sin título7](https://user-images.githubusercontent.com/29610537/58465249-9127cd80-8137-11e9-921c-14fbd357504c.gif)

![Snap_2019 05 28_10h43m14s_004_](https://user-images.githubusercontent.com/29610537/58465279-a43a9d80-8137-11e9-86a5-5904cec7f5bb.jpg)
![Snap_2019 05 28_10h42m12s_001_](https://user-images.githubusercontent.com/29610537/58465280-a43a9d80-8137-11e9-9767-ca30b4f84cd4.jpg)
![Snap_2019 05 28_10h42m31s_002_](https://user-images.githubusercontent.com/29610537/58465281-a43a9d80-8137-11e9-8968-bce0416f5264.jpg)
![Snap_2019 05 28_10h43m00s_003_](https://user-images.githubusercontent.com/29610537/58465282-a43a9d80-8137-11e9-809b-b10bdc040151.jpg)

**Comment by joelbcampos** [comment]
Waiting for help, I tried to perform this operation from Accounts and the funny thing is that from accounts, if you let you send the link but from contacts NOT

**Comment by ikyamoet** [comment]
I have the exact same issue in the knowledge base, none of the links are registered..

**Comment by mariuszkrzaczkowski** [comment]
in the wysiwyg editor, all url addresses (link and photos) are verified if they are allowed.
Below you have a file with the list of allowed URLs.
https://github.com/YetiForceCompany/YetiForceCRM/blob/7c6d6bfed2a5bcee4347c711b301be1ed291ce0d/config/Security.php#L92-L93

```php
public static $PURIFIER_ALLOWED_DOMAINS = ['yetiforce.com','github.com'];
```

**Comment by joelbcampos** [comment]
@mariuszkrzaczkowski

One more time. Thank you very very much.

**Comment by McDrewBlue** [comment]
I know this was a while ago now...but could this still be an issue? I have made the changes above and still my href's are removed on save of an email template...any ideas?? thanks guys
