### ISSUE TITLE
Multiple Advanced Blocks

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10544]
Hi, In quote module, The comment section usually comes below each product, but for me it will be better if the comment section comes before the product so that I can add a product information before the product.

Also, Is there a way to add multiple advanced Block to this module or every module.

Thanks

**Comment by indrabhusanroy** [comment]
I am using ver:4.4

**Comment by mariuszkrzaczkowski** [comment]
> Hi, In quote module, The comment section usually comes below each product, but for me it will be better if the comment section comes before the product so that I can add a product information before the product.

No

> Also, Is there a way to add multiple advanced Block to this module or every module.

No
