### ISSUE TITLE
[Question] Install on Sub-domain

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10548]
Hi,

I have just tried installing YF on a subdomain. The steps I took are:

1. Created sub-domain via cPanel,
2. Uploaded YF zip on sub-domain/publichtml 
3. Extracted YF files onto sub-domain/publichtml and deleted YF zip folder
4. I then tried to access sub-domain via www. and this is the error 500:

![image](https://user-images.githubusercontent.com/34719141/58518444-8b6dce80-81af-11e9-999a-562291a7fd56.png)

I have no clue what to do next, please assist.

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-uzytkownika/item/apache-500-internal-server-error-3

**Comment by MyBlissIT** [comment]
I actually found a YouTube Tutorial of how to load Softaculous scripts on a subdomain via cPanel. Thanks though @mariuszkrzaczkowski 

https://www.youtube.com/watch?v=Ghg5qYkU890
