### ISSUE TITLE
Duplicate Quantity Field in Advanced block

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10545]
Hi, I want to add a multiplying factor to quantity, so that when I add a product, price gets multiplied with quantity and my multiplying factor so that 
NET=unit price x quantity x multiplying factor.

In other words I want to duplicate the quantity field in advanced block.

Thanks

**Comment by vovpff** [comment]
I think this is hardcoded in system but you can replace expressions by yourself

**Comment by indrabhusanroy** [comment]
Can you please tell where these changes has to be made, only the names will suffice.

Thanks

**Comment by vovpff** [comment]
@indrabhusanroy I don't really know where modification must be applied. Check code.
