### ISSUE TITLE
Project and calendar

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#1055]
Hi!

Why projects are not tied to calendar? It was very useful in vtiger!
If this is not a problem please revert. It easier to switch off projects from calendar view than mess with code

Tony

**Comment by eptapsyxos** [comment]
+1

**Comment by waran70** [comment]
Thanks Blazej :)

**Comment by florek41** [comment]
Good idea !
But it's only for Projects or for Project Tasks too ? I think that both things are important.

**Comment by bpabiszczak** [comment]
I got bad news for you. Most likely, we'll never display anything else but the calendar events. It results from two factors:

1. At the moment every module will have its own mechanisms and summaries, e.g. The reservations module has its own calendar view, projects module has its own gantt view [in the future we'll add the ability to browse all projects in one chart; if its necessary we'll add the calendar view in the project]. The working time module has it's own calendar view. In contrast to Vtiger these elements are separated in our system
2. Different elements have different mechanisms and different fields, it doesn't seem right to present them on the same screen, because it will cause a variety of problems [e.g. moving them to some other date] 

Maybe in the future we'll add a general view of the calendar on the start screen, which will present it all in one form, but we certainly won't add it to the regular calendar view.
