### ISSUE TITLE
  Advanced Block Fields In Profiles

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10569]
Hi, I have made a quote and assigned it to a user. Now I have given this user the Right to edit the quote, but I don't want to give power to edit everything. 

For this, I went to Permissions---Profiles to select what this user type can edit or not. But I don't see the fields of Advanced Block like Tax Mode, Adding A Product, Setting the Tax Rate and Discount Rate. This is my problem.

I don't want this user type to change any product Information, so please help in this.

Thanks

**Comment by paula-w** [comment]
This is @bpabiszczak 's answer:
It's not currently possible. In order for us to add this functionality either a client would have to order this or it would have to be crowdfunded in OpenCollective.
