### ISSUE TITLE
Created By In Quotes

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10563]
Hi, How to create a Created By Field in Quotes just like in Accounts Module.
I have used created_user_id as field name but its not working.

**Comment by davide-alghi** [comment]
Hi indrabhusanroy,
duplicated #10396

**Comment by indrabhusanroy** [comment]
I don't think there are any bugs in created By. In some records like Accounts, created by field is present and working fine, but In quotes & orders, created by field is not there, so I want to add this field. 

ver4.4

**Comment by davide-alghi** [comment]
You are right indrabhusanroy: **Created by** field hasn't a bug.

What @cltvchannel wrote you is, probabily, that YF-team has in planning to create a new custom field "Creator" type, just like custom fields integer, text, picklist and so on. A new field type. But, it seems, at now, it has a bug and it's not put in production.

Now, about **Created by** field: in database there is a table with all fields for all modules. For some modules the **Created by** field was not inserted into table, for some reason. So you cannot see it in detail view and into filter editor.
It was created only for some modules like Lead, Account, Contacts, ...

I hope this is a clarification of the problem :roll_eyes:
