### ISSUE TITLE
[Question] Transfer related records from module A to module B

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#10561]
Hi, 
I've created a custom function in Workflow which works very well for me but I would like to know if it's the right way ?

Goal : transfer Module C related records from module A to module B

Use case :
-> Module A has M:M relation with Module C
-> Module B has M:M relation with Module C
-> Module B has 1:M relation with Module A

My custom function : 

`

// Step1 - get some ID's and Module Names

$module_A_id = $recordModel->get('your_1_M_relation_field_name');

$module_B_id = $recordModel->getId();

$module_A_Name = Vtiger_Record_Model::getInstanceById($module_A_id)->getModuleName();

$module_B_Name = $recordModel->getModuleName();

$module_C_Name = 'Your_Module_C_Name';

// step2 - check in table vtiger_crmentityrel if related records has already been transfered

	if ((new \App\Db\Query())->select(['crmid','relmodule'])->from('vtiger_crmentityrel')->where(['crmid' => $module_B_id,'relmodule'=>$module_C_Name])->exists()) {

	// related records found --> do nothing

	} else {

	// step3 - get module A related records from vtiger_crmentityrel

	$dataReader = (new \App\Db\Query())->select(['crmid','module','relcrmid','relmodule'])->from('vtiger_crmentityrel')->where(['crmid' => $module_A_id, 'relmodule'=>$module_C_Name])->createCommand()->query();

	// step4 - transfer Module A related records to Module B

	while ($row = $dataReader->read()) {

		$db = App\Db::getInstance();
		$resultNew = $db->createCommand()->insert('vtiger_crmentityrel', [
				'crmid' => $module_B_id,
				'module' => $module_B_Name,
				'relcrmid' => $row['relcrmid'],
				'relmodule' => $row['relmodule'],
				'rel_created_user' => \App\User::getCurrentUserId(),
				'rel_created_time' => date('Y-m-d H:i:s'),
			])->execute();

		}

		$dataReader->close();

		return;

	}
`

Do you think it's correct ?
Regards

**Comment by mariuszkrzaczkowski** [comment]
no, it's not that easy, there's functionality for it
https://github.com/YetiForceCompany/YetiForceCRM/blob/0c5f6ed616c6049f5ac545d434a3ff604e2f7764/app/RecordTransfer.php#L26-L42

**Comment by apcloic** [comment]
@mariuszkrzaczkowski thanks for your help.
Indeed, it looks more difficult than my basic script, I will try to learn how to use the transfer function.
