### ISSUE TITLE
[PL][Pytanie] Problem z odpowiedzią na maile firmowe

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10560]
Witam,
na wersji 5.0.0
z poziomu użytkownika przy wyborze opcji:"Odpowiedz", "Odpowiedz Wszystkim", "Przekaż" automatycznie pojawia się okno wyboru skrzynki. Porblem pojawia się tylko z poziomu użytkownika, nie administratora.. Próbowałem aktualizować biblioteki ale nic to nie dało. Kiedy kliknie "Wyślij maila" to nie ma problemu, tylko przy odpowiedzach.
![pocztayetiforce](https://user-images.githubusercontent.com/21024857/58536613-60a46a00-81f1-11e9-9c50-b4b189334802.gif)

Przeglądarka wyświetla że plik odpowiedzi jest niezdefiniowany

**Comment by mrzewnicki** [comment]
po otwarciu linku ze źródła strony pojawia sie następujacy błąd 

![image](https://user-images.githubusercontent.com/21024857/58781239-aa1efb80-85db-11e9-9c9e-4f394b178b18.png)

**Comment by mrzewnicki** [comment]
Najprawdopodobniej jest to wina uprawnień na serwerze.. nie chcący zmieniłem je nie w tym pliku.. jakie uprawnienia powinny być na yetiforce.php ?

**Comment by bpabiszczak** [comment]
skrypt muszą działa z uprawnieniami usera www np. data-www [zależy od systemu operacyjnego], czyli z uprawnieniami do podglądu, edycji, usuwania pliku

**Comment by mrzewnicki** [comment]
Dzięki za odpowiedź. Zmieniłem właściciela na www-data:www-data i nadałem uprawnienia  ale niestety dalej użytkownik nie może odpowiedzieć.. Z poziomu root'a można ale tylko on. Nawet użytkownik z uprawnieniami Administratorskimi nie może, tylko root.

**Comment by mrzewnicki** [comment]
Aktualizacja bibliotek lub ponowna instalacja Roundcube nic nie daje niestety.

**Comment by bpabiszczak** [comment]
chyba nie na to zgłoszenie odpowiadałem [odnośnie uprawnień]... czy błąd występuje na gitstable i gitdeveloper [są tam mailem podpięte więc można testować]?

**Comment by mrzewnicki** [comment]
Taki sam błąd mam na wersji gitdeveloper na Waszej stronie oraz na wersji 5.0.0 stable na swoim serwerze. Po akutalizacji bibliotek roundcube zaczęło się psuć.
Filmik z waszej wersji:
![Nienazwany](https://user-images.githubusercontent.com/21024857/58865075-31d93880-86b6-11e9-9af2-2a9f5395ac64.gif)

**Comment by bpabiszczak** [comment]
za to odpowiada pole [Wewnętrzny klient email] w edycji użytkownika

**Comment by mrzewnicki** [comment]
OK, działa!! dzięki wielkie!!
