### ISSUE TITLE
Fatal error on your test site

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1056]
Fatal error: Cannot use isset() on the result of a function call (you can use "null !== func()" instead) in /home/yetiforce1/domains/test.yetiforce.com/public_html/modules/OSSPdf/PDFExport.php on line 24

I created a test ivoice
then from the invoices list a checked it and tried to download it to my pc.

then that error appeared.

**Comment by MaciejStencel** [comment]
This error was already fixed in YetiForce 2.0.19. Here you can check the revision:
https://github.com/YetiForceCompany/YetiForceCRM/commit/71b6e9d601211118fc1cfce8d981c81232dec144

**Comment by eptapsyxos** [comment]
Thanks mate.keep the good work
