### ISSUE TITLE
[Question] Installation Error 

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10572]
Hi, I have just installed YF on a subdomain via Softaculous.

I get this error even though my php seems to be configured accordingly:

![image](https://user-images.githubusercontent.com/34719141/58589616-9a618900-8262-11e9-9d8c-63d4b122c1f7.png)

and these are my php settings or configurations:

![image](https://user-images.githubusercontent.com/34719141/58589733-d72d8000-8262-11e9-9c0b-b08a051cbc5d.png)

Please assist.

**Comment by davide-alghi** [comment]
that error depend on **intl** package. you haven't installed it.
please verify all YF requirements before install

https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

**Comment by MyBlissIT** [comment]
> that error depend on **intl** package. you haven't installed it.
> please verify all YF requirements before install
> 
> https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

Thank you @davide-alghi . I had to refresh my php because I kept installing intl but when I select "save" it would be unselected.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/9821
