### ISSUE TITLE
[Question] PDF Quote Template           

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10579]
Hi,

I am trying to create a Quote PDF Template but I do not know what to add on "Edit Document Contents"

How I wish the basic PDF Templates like "Invoice" and "Quote" came with the installation.

Can someone please help me out?

**Comment by neuronetio** [comment]
What you want to add? be specific :)
here you have variables that you can copy and paste inside the template
![image](https://user-images.githubusercontent.com/25027696/58721404-34494300-83d5-11e9-919e-812fb2a795d8.png)

**Comment by ippeas1** [comment]
i have the same problem. i try to find the related fields but i can not. Where is the quote fields? i want to create a pdf template for Quote but i can not. Here is my print screen . http://prntscr.com/nz1sn8
After that i want to create a manually workflow to sent an email with above PDF file attachment. Could you help me please ?
thank you

**Comment by vovpff** [comment]
Use picklist "field from module" and blue button to copy field variable.
For PDF mailing you need to add workflow with send PDF action.

**Comment by ippeas1** [comment]
> 
> 
> Use picklist "field from module" and blue button to copy field variable.
> For PDF mailing you need to add workflow with send PDF action.

thank you for your reply !
ok this is easy but i can not find the product fields or services fields of Quote. Take a look on print screen please http://prntscr.com/nzcubk. how can I choose specific fields? for example: i want only the fields Unit price, Purchase, Tax and Gross on my pdf file or email. 

how can i do it ?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/9840#issuecomment-471886292

**Comment by ippeas1** [comment]
could i change the width of table? i want to define the width. for example 80%

**Comment by vovpff** [comment]
try this as source around table variable
```
<div style="width:80%">
yuor stuff
</div>
```

**Comment by ippeas1** [comment]
Fine! we have the code for custom quote table.

    $(inventory : type=table columns=name,qty,price href=yes)$

it works very well !

Is there the same for PaymentIn and PaymentOut? i want to create custom table of any field.
Thank you !

**Comment by mariuszkrzaczkowski** [comment]
What exactly do you want to show?
`$(relatedRecordsList : PaymentIn)$`

**Comment by ippeas1** [comment]
Thank you for your reply!

i want to show only Payment Name, value and status.

**Comment by konadrian** [comment]
I will give you an example with Contacts module 
$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|)$
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app/TextParser.php#L717
