### ISSUE TITLE
[BUG][PL] Zapis szansy sprzedaży

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1057]
Przy zapisanie szansy sprzedaży dostaję w konsoli:
TypeError: app.validateHiddenBlocks is not a function
app.validateHiddenBlocks();

**Comment by MaciejStencel** [comment]
Pozostałość mojej poprawki która Mariusz usprawnił na masterze. Funkcja już nie istnieje w systemie i jest niepotrzebna, jej wywołanie generujce bład zostało usunięte.
