### ISSUE TITLE
[Question] How can i add the "MAP" tab in a custom module

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#10570]
Hello, i created a couple of custom modules and now i want to add the "MAP" tab in one of them.

here is the map tab from Leads. How can i add this to my module ?

![image](https://user-images.githubusercontent.com/45770116/58577864-6f047d00-8215-11e9-8831-a97e535b6fef.png)

**Comment by apcloic** [comment]
+1, I'm also interested.

For now, I have created a custom DetailView in MyCustomModule/models/DetailView.php

` class MyCustomModule_DetailView_Model extends Vtiger_DetailView_Model
{
	public function getDetailViewRelatedLinks()
	{
		$recordModel = $this->getRecord();
		$relatedLinks = parent::getDetailViewRelatedLinks();
		$userPrivilegesModel = Users_Privileges_Model::getCurrentUserPrivilegesModel();
		if ($userPrivilegesModel->hasModulePermission('OpenStreetMap')) {
			$relatedLinks[] = [
				'linktype' => 'DETAILVIEWTAB',
				'linklabel' => 'LBL_MAP',
				'linkurl' => $recordModel->getDetailViewUrl() . '&mode=showOpenStreetMap',
				'linkicon' => '',
			];
		}
		return $relatedLinks;
	}
}`

Then I had to include my module in OpenStreetMap_OpenStreetMapHandler_Handler on vtiger_eventhandlers table.

Now I do have a new Map tab to my custom module but it's not enough because I have to do the mapping of my custom address fields which do not respect the exact same logic as for native modules.

So I have a map, but an empty one.

**Comment by apcloic** [comment]
Ok, MAP tab works as expected now after renaming address fields in my custom module table (and also in vtiger_fields) , for example "addresslevel1a" for country, addresslevel5a for city and addresslevel7a for zip code, etc. the same names as in standard modules.

**Comment by maeglin4** [comment]
> +1, I'm also interested.
> 
> For now, I have created a custom DetailView in MyCustomModule/models/DetailView.php
> 
> ```
>  class MyCustomModule_DetailView_Model extends Vtiger_DetailView_Model
> {
> 	public function getDetailViewRelatedLinks()
> 	{
> 		$recordModel = $this->getRecord();
> 		$relatedLinks = parent::getDetailViewRelatedLinks();
> 		$userPrivilegesModel = Users_Privileges_Model::getCurrentUserPrivilegesModel();
> 		if ($userPrivilegesModel->hasModulePermission('OpenStreetMap')) {
> 			$relatedLinks[] = [
> 				'linktype' => 'DETAILVIEWTAB',
> 				'linklabel' => 'LBL_MAP',
> 				'linkurl' => $recordModel->getDetailViewUrl() . '&mode=showOpenStreetMap',
> 				'linkicon' => '',
> 			];
> 		}
> 		return $relatedLinks;
> 	}
> }
> ```
> 
> Then I had to include my module in OpenStreetMap_OpenStreetMapHandler_Handler on vtiger_eventhandlers table.
> 
> Now I do have a new Map tab to my custom module but it's not enough because I have to do the mapping of my custom address fields which do not respect the exact same logic as for native modules.
> 
> So I have a map, but an empty one.

how did you include "my module" in OpenStreetMap_OpenStreetMapHandler_Handler on vtiger_eventhandlers table????????????????????????????????

**Comment by rskrzypczak** [comment]
Modify directly in the database
![image](https://user-images.githubusercontent.com/10221999/62919437-f4261980-bda2-11e9-91c0-16933c2b2158.png)
