### ISSUE TITLE
Error: JS_FUTURE_EVENT_CANNOT_BE_MARKED_AS_HELD

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1058]
index.php?module=Calendar&view=List&searchResult=["162","158","156"]

![notmarkedasheld](https://cloud.githubusercontent.com/assets/6897502/8164647/178c7612-1393-11e5-8f70-108ef18cfd93.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/19e1663b18559b63cfff673727891c342e7f0e25
