### ISSUE TITLE
[Question] Rows or columns overflow! Excel5 has limit to 65535 rows and 255 columns. Use XLSX instead.

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#10580]
Hello, im trying to export all the fields from a custom module and i am having this error message... 

my question is : how to i use .XLSX file type instead of .XLS

here, is how i triggered the error : 
![yeti export problem](https://user-images.githubusercontent.com/45770116/58638889-c8c38080-82c3-11e9-9597-a7b385a1da6e.gif)

this is the error message and full details below it : 
![image](https://user-images.githubusercontent.com/45770116/58638308-80f02980-82c2-11e9-9792-92bb2b5fc4f4.png)

#0 [info] SELECT * FROM `vtiger_tab` || yii\db\Command::query
#1 [info] Opening DB connection: mysql:host=localhost;dbname=expertcloud_y952;port=3306 || yii\db\Connection::open
#2 [info] SELECT * FROM `vtiger_entityname` || yii\db\Command::query
#3 [info] SELECT * FROM `vtiger_actionmapping` || yii\db\Command::query
#4 [info] SELECT * FROM `vtiger_field` WHERE `tabid`=127 || yii\db\Command::query
#5 [info] SELECT `columnindex`, `field_name`, `module_name`, `source_field_name` FROM `vtiger_cvcolumnlist` WHERE `cvid`='141' ORDER BY `columnindex` || yii\db\Command::query
#6 [info] SELECT `vtiger_field`.`fieldname`, `u_yf_cv_duplicates`.`ignore` FROM `u_yf_cv_duplicates` INNER JOIN `vtiger_field` ON vtiger_field.fieldid = u_yf_cv_duplicates.fieldid WHERE `u_yf_cv_duplicates`.`cvid`='141' || yii\db\Command::query
#7 [info] SELECT `u_yf_cv_condition`.`group_id`, `u_yf_cv_condition`.`field_name`, `u_yf_cv_condition`.`module_name`, `u_yf_cv_condition`.`source_field_name`, `u_yf_cv_condition`.`operator`, `u_yf_cv_condition`.`value`, `u_yf_cv_condition`.`index` AS `condition_index`, `u_yf_cv_condition_group`.`condition`, `u_yf_cv_condition_group`.`parent_id`, `u_yf_cv_condition_group`.`index` AS `group_index` FROM `u_yf_cv_condition` INNER JOIN `u_yf_cv_condition_group` ON u_yf_cv_condition_group.id = u_yf_cv_condition.group_id WHERE `u_yf_cv_condition_group`.`cvid`='141' ORDER BY `u_yf_cv_condition_group`.`parent_id` || yii\db\Command::query
#8 [info] SELECT * FROM `vtiger_customview` WHERE `cvid`='141' LIMIT 1 || yii\db\Command::query
#9 [info] SELECT `vtiger_field`.* FROM `vtiger_field` LEFT JOIN `vtiger_blocks` ON vtiger_field.block = vtiger_blocks.blockid WHERE `vtiger_field`.`tabid`=127 ORDER BY `vtiger_blocks`.`sequence`, `vtiger_field`.`sequence` || yii\db\Command::query
#10 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=497 LIMIT 1 || yii\db\Command::query
#11 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=438 LIMIT 1 || yii\db\Command::query
#12 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=449 LIMIT 1 || yii\db\Command::query
#13 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=440 LIMIT 1 || yii\db\Command::query
#14 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=448 LIMIT 1 || yii\db\Command::query
#15 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=496 LIMIT 1 || yii\db\Command::query
#16 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=452 LIMIT 1 || yii\db\Command::query
#17 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=453 LIMIT 1 || yii\db\Command::query
#18 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=454 LIMIT 1 || yii\db\Command::query
#19 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=455 LIMIT 1 || yii\db\Command::query
#20 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=456 LIMIT 1 || yii\db\Command::query
#21 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=457 LIMIT 1 || yii\db\Command::query
#22 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=458 LIMIT 1 || yii\db\Command::query
#23 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=459 LIMIT 1 || yii\db\Command::query
#24 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=460 LIMIT 1 || yii\db\Command::query
#25 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=464 LIMIT 1 || yii\db\Command::query
#26 [info] SELECT * FROM `vtiger_ws_fieldtype` || yii\db\Command::query
#27 [info] SELECT `relmodule` AS `module` FROM `vtiger_fieldmodulerel` INNER JOIN `vtiger_tab` ON vtiger_tab.name = vtiger_fieldmodulerel.relmodule WHERE (`fieldid`=3247) AND (`vtiger_tab`.`presence` <> 1) ORDER BY `sequence` || yii\db\Command::query
#28 [info] SELECT `relmodule` AS `module` FROM `vtiger_fieldmodulerel` INNER JOIN `vtiger_tab` ON vtiger_tab.name = vtiger_fieldmodulerel.relmodule WHERE (`fieldid`=3233) AND (`vtiger_tab`.`presence` <> 1) ORDER BY `sequence` || yii\db\Command::query
#29 [info] SELECT DISTINCT `vtiger_field`.`fieldid`, `vtiger_field`.`fieldname`, `vtiger_field`.`columnname`, `vtiger_profile2field`.`readonly`, `vtiger_profile2field`.`visible` FROM `vtiger_field` INNER JOIN `vtiger_profile2field` ON vtiger_profile2field.fieldid = vtiger_field.fieldid WHERE ((`vtiger_field`.`tabid`=127) AND (`vtiger_profile2field`.`visible`=0) AND (`vtiger_field`.`visible`=0) AND (`vtiger_field`.`presence` IN (0, 2))) AND (`vtiger_profile2field`.`profileid`=1) || yii\db\Command::query
#30 [info] SELECT * FROM `vtiger_role` WHERE `roleid`='H2' LIMIT 1 || yii\db\Command::query
#31 [info] SELECT `u_yf_renocollectedonne`.`renocollectedonneid` AS `id`, `u_yf_renocollectedonne`.`marquethermopompe` AS `marquethermopompe`, `u_yf_renocollectedonne`.`modelnumextint` AS `modelnumextint`, `u_yf_renocollectedonne`.`thermopompe` AS `thermopompe`, `u_yf_renocollectedonne`.`thermoenergystar` AS `thermoenergystar`, `u_yf_renocollectedonne`.`thermopompepuisscapacite` AS `thermopompepuisscapacite`, `u_yf_renocollectedonne`.`climatisationcentrale` AS `climatisationcentrale`, `u_yf_renocollectedonne`.`climatisationenergystar` AS `climatisationenergystar`, `u_yf_renocollectedonne`.`vermiculite` AS `vermiculite`, `u_yf_renocollectedonne`.`appareilsdextraction` AS `appareilsdextraction`, `u_yf_renocollectedonne`.`appareilsdextractionendroit` AS `appareilsdextractionendroit`, `u_yf_renocollectedonne`.`hottecuisinere` AS `hottecuisinere`, `u_yf_renocollectedonne`.`ventsallebain` AS `ventsallebain`, `u_yf_renocollectedonne`.`aspiracentrale` AS `aspiracentrale`, `u_yf_renocollectedonne`.`total5sur10` AS `total5sur10`, `u_yf_renocollectedonne`.`totalwatt` AS `totalwatt`, `u_yf_renocollectedonne`.`typedemaison` AS `typedemaison`, `u_yf_renocollectedonne`.`videsanitairesisspp4` AS `videsanitairesisspp4`, `u_yf_renocollectedonne`.`plafond1construction` AS `plafond1construction`, `u_yf_renocollectedonne`.`plafond1typestructure` AS `plafond1typestructure`, `u_yf_renocollectedonne`.`plafond1isolant1` AS `plafond1isolant1`, `u_yf_renocollectedonne`.`plafond1isolant2` AS `plafond1isolant2`, `u_yf_renocollectedonne`.`plafond1basedutoit` AS `plafond1basedutoit`, `u_yf_renocollectedonne`.`plafond1interieur` AS `plafond1interieur`, `u_yf_renocollectedonne`.`plafond1superficie` AS `plafond1superficie`, `u_yf_renocollectedonne`.`plafond1pente` AS `plafond1pente`, `u_yf_renocollectedonne`.`plafond1talon` AS `plafond1talon`, `u_yf_renocollectedonne`.`plafond2construction` AS `plafond2construction`, `u_yf_renocollectedonne`.`plafond2typestructure` AS `plafond2typestructure`, `u_yf_renocollectedonne`.`plafond2isolant1` AS `plafond2isolant1`, `u_yf_renocollectedonne`.`plafond2isolant2` AS `plafond2isolant2`, `u_yf_renocollectedonne`.`plafond2basedutoit` AS `plafond2basedutoit`, `u_yf_renocollectedonne`.`plafond2interieur` AS `plafond2interieur`, `u_yf_renocollectedonne`.`plafond2superficie` AS `plafond2superficie`, `u_yf_renocollectedonne`.`plafond2pente` AS `plafond2pente`, `u_yf_renocollectedonne`.`plafond2talon` AS `plafond2talon`, `u_yf_renocollectedonne`.`plafond3construction` AS `plafond3construction`, `u_yf_renocollectedonne`.`plafond3typestructure` AS `plafond3typestructure`, `u_yf_renocollectedonne`.`plafond3isolant1` AS `plafond3isolant1`, `u_yf_renocollectedonne`.`plafond3isolant2` AS `plafond3isolant2`, `u_yf_renocollectedonne`.`plafond3basedutoit` AS `plafond3basedutoit`, `u_yf_renocollectedonne`.`plafond3interieur` AS `plafond3interieur`, `u_yf_renocollectedonne`.`plafond3superficie` AS `plafond3superficie`, `u_yf_renocollectedonne`.`plafond3pente` AS `plafond3pente`, `u_yf_renocollectedonne`.`plafond3talon` AS `plafond3talon`, `u_yf_renocollectedonne`.`plafond4construction` AS `plafond4construction`, `u_yf_renocollectedonne`.`plafond4typestructure` AS `plafond4typestructure`, `u_yf_renocollectedonne`.`plafond4isolant1` AS `plafond4isolant1`, `u_yf_renocollectedonne`.`plafond4isolant2` AS `plafond4isolant2`, `u_yf_renocollectedonne`.`plafond4basedutoit` AS `plafond4basedutoit`, `u_yf_renocollectedonne`.`plafond4interieur` AS `plafond4interieur`, `u_yf_renocollectedonne`.`plafond4superficie` AS `plafond4superficie`, `u_yf_renocollectedonne`.`plafond4pente` AS `plafond4pente`, `u_yf_renocollectedonne`.`plafond4talon` AS `plafond4talon`, `u_yf_renocollectedonne`.`mur1endroit` AS `mur1endroit`, `u_yf_renocollectedonne`.`mur1typestructure` AS `mur1typestructure`, `u_yf_renocollectedonne`.`mur1perimetrexpose` AS `mur1perimetrexpose`, `u_yf_renocollectedonne`.`mur1interieur` AS `mur1interieur`, `u_yf_renocollectedonne`.`mur1coin` AS `mur1coin`, `u_yf_renocollectedonne`.`mur1hauteurmoy` AS `mur1hauteurmoy`, `u_yf_renocollectedonne`.`mur2endroit` AS `mur2endroit`, `u_yf_renocollectedonne`.`mur2typestructure` AS `mur2typestructure`, `u_yf_renocollectedonne`.`mur2exterieur` AS `mur2exterieur`, `u_yf_renocollectedonne`.`mur2interieur` AS `mur2interieur`, `u_yf_renocollectedonne`.`mur2perimetrexpose` AS `mur2perimetrexpose`, `u_yf_renocollectedonne`.`mur2hauteurmoy` AS `mur2hauteurmoy`, `u_yf_renocollectedonne`.`mur2coin` AS `mur2coin`, `u_yf_renocollectedonne`.`mur1exterieur` AS `mur1exterieur`, `u_yf_renocollectedonne`.`mur3endroit` AS `mur3endroit`, `u_yf_renocollectedonne`.`mur3interieur` AS `mur3interieur`, `u_yf_renocollectedonne`.`mur3typestructure` AS `mur3typestructure`, `u_yf_renocollectedonne`.`mur3hauteurmoy` AS `mur3hauteurmoy`, `u_yf_renocollectedonne`.`mur3exterieur` AS `mur3exterieur`, `u_yf_renocollectedonne`.`mur3coin` AS `mur3coin`, `u_yf_renocollectedonne`.`mur3perimetrexposer` AS `mur3perimetrexposer`, `u_yf_renocollectedonnecf`.`cf_3388` AS `cf_3388`, `u_yf_renocollectedonnecf`.`cf_3390` AS `cf_3390`, `u_yf_renocollectedonnecf`.`cf_3393` AS `cf_3393`, `u_yf_renocollectedonne`.`mur4typestructure` AS `mur4typestructure`, `u_yf_renocollectedonnecf`.`cf_3396` AS `cf_3396`, `u_yf_renocollectedonnecf`.`cf_3392` AS `cf_3392`, `u_yf_renocollectedonnecf`.`cf_3395` AS `cf_3395`, `u_yf_renocollectedonne`.`hauteurrdc` AS `hauteurrdc`, `u_yf_renocollectedonne`.`hauteuretage` AS `hauteuretage`, `u_yf_renocollectedonne`.`hauteurssol` AS `hauteurssol`, `u_yf_renocollectedonne`.`hauteursolives` AS `hauteursolives`, `u_yf_renocollectedonne`.`no_evaluation` AS `no_evaluation`, `u_yf_renocollectedonne`.`no_evaluation_d` AS `no_evaluation_d`, `u_yf_renocollectedonne`.`notes_rdv` AS `notes_rdv`, `u_yf_renocollectedonne`.`plagehoraire` AS `plagehoraire`, `u_yf_renocollectedonne`.`personne_presente` AS `personne_presente`, `u_yf_renocollectedonne`.`proprio_legal` AS `proprio_legal`, `u_yf_renocollectedonne`.`particularites` AS `particularites`, `u_yf_renocollectedonne`.`travaux` AS `travaux`, `u_yf_renocollectedonne`.`habitation_admissible` AS `habitation_admissible`, `u_yf_renocollectedonne`.`chauffage_appoint` AS `chauffage_appoint`, `u_yf_renocollectedonne`.`acces_syst_mecanique` AS `acces_syst_mecanique`, `u_yf_renocollectedonne`.`acces_grenier` AS `acces_grenier`, `u_yf_renocollectedonne`.`etatsdestravaux` AS `etatsdestravaux`, `u_yf_renocollectedonne`.`telephonecoproprio_extra` AS `telephonecoproprio_extra`, `u_yf_renocollectedonne`.`telephoneautre_extra` AS `telephoneautre_extra`, `u_yf_renocollectedonne`.`telephoneprincipal_extra` AS `telephoneprincipal_extra`, `u_yf_renocollectedonne`.`telephonesecondaire_extra` AS `telephonesecondaire_extra`, `u_yf_renocollectedonne`.`documentsrequis` AS `documentsrequis`, `u_yf_renocollectedonnecf`.`cf_3422` AS `cf_3422`, `u_yf_renocollectedonne`.`imagesjointe` AS `imagesjointe`, `u_yf_renocollectedonne`.`document` AS `document`, `u_yf_renocollectedonne`.`service` AS `service`, `u_yf_renocollectedonne`.`no_dossier` AS `no_dossier`, `u_yf_renocollectedonne`.`facade` AS `facade`, `u_yf_renocollectedonne`.`aidememoire` AS `aidememoire`, `u_yf_renocollectedonne`.`formeduplan` AS `formeduplan`, `u_yf_renocollectedonne`.`preocc_proprio` AS `preocc_proprio`, `u_yf_renocollectedonne`.`fondation` AS `fondation`, `u_yf_renocollectedonne`.`systchauffprinc` AS `systchauffprinc`, `u_yf_renocollectedonne`.`energie` AS `energie`, `u_yf_renocollectedonne`.`puissance` AS `puissance`, `u_yf_renocollectedonne`.`rendement` AS `rendement`, `u_yf_renocollectedonne`.`appenergistar` AS `appenergistar`, `u_yf_renocollectedonne`.`nbthermostelect` AS `nbthermostelect`, `u_yf_renocollectedonne`.`chauffageappoint1` AS `chauffageappoint1`, `u_yf_renocollectedonne`.`energiechauffageappoint1` AS `energiechauffageappoint1`, `u_yf_renocollectedonne`.`locchauffageappoint1` AS `locchauffageappoint1`, `u_yf_renocollectedonne`.`typechauffageappoint` AS `typechauffageappoint`, `u_yf_renocollectedonne`.`energiechauffageappoint2` AS `energiechauffageappoint2`, `u_yf_renocollectedonne`.`locchauffageappoint2` AS `locchauffageappoint2`, `u_yf_renocollectedonne`.`certifier_epa` AS `certifier_epa`, `u_yf_renocollectedonne`.`ventilation` AS `ventilation`, `u_yf_renocollectedonne`.`marqueventilation` AS `marqueventilation`, `u_yf_renocollectedonne`.`murfondation` AS `murfondation`, `u_yf_renocollectedonne`.`garageattacher` AS `garageattacher`, `u_yf_renocollectedonne`.`energiechauffeeau1` AS `energiechauffeeau1`, `u_yf_renocollectedonne`.`reservoirchauffeeau1` AS `reservoirchauffeeau1`, `u_yf_renocollectedonne`.`chauffeeau1isoler` AS `chauffeeau1isoler`, `u_yf_renocollectedonne`.`capaciterchauffeeau1` AS `capaciterchauffeeau1`, `u_yf_renocollectedonne`.`locchauffeeau1` AS `locchauffeeau1`, `u_yf_renocollectedonne`.`energiechauffeeau2` AS `energiechauffeeau2`, `u_yf_renocollectedonne`.`reservoirchauffeeau2` AS `reservoirchauffeeau2`, `u_yf_renocollectedonne`.`chauffeeau1isoler2` AS `chauffeeau1isoler2`, `u_yf_renocollectedonne`.`capaciterchauffeeau2` AS `capaciterchauffeeau2`, `u_yf_renocollectedonne`.`locchauffeeau2` AS `locchauffeeau2`, `u_yf_renocollectedonne`.`telephoneautre` AS `telephoneautre`, `u_yf_renocollectedonne`.`adressecourriel` AS `adressecourriel`, `u_yf_renocollectedonne`.`languecorrespondance` AS `languecorrespondance`, `u_yf_renocollectedonne`.`nbetages` AS `nbetages`, `u_yf_renocollectedonne`.`anneconstruction` AS `anneconstruction`, `u_yf_renocollectedonne`.`sourcenergieprincipal` AS `sourcenergieprincipal`, `u_yf_renocollectedonne`.`raison` AS `raison`, `u_yf_renocollectedonne`.`evaluationprecedente` AS `evaluationprecedente`, `u_yf_renocollectedonne`.`statutevaluation` AS `statutevaluation`, `u_yf_renocollectedonne`.`envoyersondage` AS `envoyersondage`, `u_yf_renocollectedonne`.`envoyeraucq` AS `envoyeraucq`, `u_yf_renocollectedonne`.`number` AS `number`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `vtiger_crmentity`.`modifiedtime` AS `modifiedtime`, `vtiger_crmentity`.`smcreatorid` AS `created_user_id`, `u_yf_renocollectedonne`.`appartenance` AS `appartenance`, `u_yf_renocollectedonne`.`compagnie` AS `compagnie`, `u_yf_renocollectedonne`.`evalentretienproprio` AS `evalentretienproprio`, `u_yf_renocollectedonne`.`dureevisite` AS `dureevisite`, `u_yf_renocollectedonne`.`numerodeporte` AS `numerodeporte`, `u_yf_renocollectedonne`.`code_postal` AS `code_postal`, `u_yf_renocollectedonne`.`regionadministrative` AS `regionadministrative`, `u_yf_renocollectedonne`.`casier_postal` AS `casier_postal`, `u_yf_renocollectedonne`.`ville` AS `ville`, `u_yf_renocollectedonne`.`nomevaluateur` AS `nomevaluateur`, `u_yf_renocollectedonne`.`prenomcoproprio` AS `prenomcoproprio`, `u_yf_renocollectedonne`.`nomcoproprio` AS `nomcoproprio`, `u_yf_renocollectedonne`.`datedemanderdv` AS `datedemanderdv`, `u_yf_renocollectedonne`.`adressecorrespondance` AS `adressecorrespondance`, `u_yf_renocollectedonne`.`adressehabitation` AS `adressehabitation`, `u_yf_renocollectedonne`.`daterdv` AS `daterdv`, `u_yf_renocollectedonne`.`etat` AS `etat`, `u_yf_renocollectedonne`.`telephoneprincipal` AS `telephoneprincipal`, `u_yf_renocollectedonne`.`telephonesecondaire` AS `telephonesecondaire`, `u_yf_renocollectedonne`.`prenom` AS `prenom`, `u_yf_renocollectedonne`.`nom` AS `nom`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `u_yf_renocollectedonne`.`typederdv` AS `typederdv`, `u_yf_renocollectedonne`.`typehabitation` AS `typehabitation`, `u_yf_renocollectedonne`.`montant_a_payer` AS `montant_a_payer`, `u_yf_renocollectedonne`.`hautplushautplafond` AS `hautplushautplafond`, `u_yf_renocollectedonne`.`plancherexposerlong` AS `plancherexposerlong`, `u_yf_renocollectedonne`.`plancherexposersurf` AS `plancherexposersurf`, `u_yf_renocollectedonne`.`plancherexposerisolant` AS `plancherexposerisolant`, `u_yf_renocollectedonne`.`murbasloc` AS `murbasloc`, `u_yf_renocollectedonne`.`murbashauteur` AS `murbashauteur`, `u_yf_renocollectedonne`.`murbasperimetre` AS `murbasperimetre`, `u_yf_renocollectedonne`.`murbasstructure` AS `murbasstructure`, `u_yf_renocollectedonne`.`murbasisolant` AS `murbasisolant`, `u_yf_renocollectedonnecf`.`cf_3372` AS `cf_3372`, `u_yf_renocollectedonnecf`.`cf_3375` AS `cf_3375`, `u_yf_renocollectedonnecf`.`cf_3376` AS `cf_3376`, `u_yf_renocollectedonnecf`.`cf_3377` AS `cf_3377`, `u_yf_renocollectedonnecf`.`cf_3378` AS `cf_3378`, `u_yf_renocollectedonnecf`.`cf_3379` AS `cf_3379`, `u_yf_renocollectedonnecf`.`cf_3382` AS `cf_3382`, `u_yf_renocollectedonnecf`.`cf_3383` AS `cf_3383`, `u_yf_renocollectedonnecf`.`cf_3380` AS `cf_3380`, `u_yf_renocollectedonnecf`.`cf_3384` AS `cf_3384`, `u_yf_renocollectedonnecf`.`cf_3385` AS `cf_3385`, `u_yf_renocollectedonnecf`.`cf_3386` AS `cf_3386`, `u_yf_renocollectedonnecf`.`cf_3387` AS `cf_3387`, `u_yf_renocollectedonnecf`.`cf_3423` AS `cf_3423`, `u_yf_renocollectedonnecf`.`cf_3424` AS `cf_3424`, `u_yf_renocollectedonnecf`.`cf_3425` AS `cf_3425`, `u_yf_renocollectedonnecf`.`cf_3426` AS `cf_3426`, `u_yf_renocollectedonnecf`.`cf_3427` AS `cf_3427`, `u_yf_renocollectedonnecf`.`cf_3428` AS `cf_3428`, `u_yf_renocollectedonnecf`.`cf_3429` AS `cf_3429`, `u_yf_renocollectedonnecf`.`cf_3430` AS `cf_3430`, `u_yf_renocollectedonnecf`.`cf_3431` AS `cf_3431`, `u_yf_renocollectedonnecf`.`cf_3432` AS `cf_3432`, `u_yf_renocollectedonnecf`.`cf_3433` AS `cf_3433`, `u_yf_renocollectedonnecf`.`cf_3434` AS `cf_3434`, `u_yf_renocollectedonne`.`fondation1attachera` AS `fondation1attachera`, `u_yf_renocollectedonne`.`fondation1longueur` AS `fondation1longueur`, `u_yf_renocollectedonne`.`typedesoussol1` AS `typedesoussol1`, `u_yf_renocollectedonne`.`longplancherexposer1` AS `longplancherexposer1`, `u_yf_renocollectedonne`.`longplancherexposer2` AS `longplancherexposer2`, `u_yf_renocollectedonne`.`longplancherexposer3` AS `longplancherexposer3`, `u_yf_renocollectedonne`.`surfplancherexposer1` AS `surfplancherexposer1`, `u_yf_renocollectedonne`.`surfplancherexposer2` AS `surfplancherexposer2`, `u_yf_renocollectedonne`.`surfplancherexposer3` AS `surfplancherexposer3`, `u_yf_renocollectedonne`.`structureplancherexposer1` AS `structureplancherexposer1`, `u_yf_renocollectedonne`.`structureplancherexposer2` AS `structureplancherexposer2`, `u_yf_renocollectedonne`.`structureplancherexposer3` AS `structureplancherexposer3`, `u_yf_renocollectedonne`.`isolationplanchersexposes1` AS `isolationplanchersexposes1`, `u_yf_renocollectedonne`.`isolationplanchersexposes2` AS `isolationplanchersexposes2`, `u_yf_renocollectedonne`.`isolationplanchersexposes3` AS `isolationplanchersexposes3`, `u_yf_renocollectedonne`.`planchdessufondation` AS `planchdessufondation`, `u_yf_renocollectedonne`.`isolationplanchdessufondation` AS `isolationplanchdessufondation`, `u_yf_renocollectedonnecf`.`cf_3397` AS `cf_3397`, `u_yf_renocollectedonnecf`.`cf_3398` AS `cf_3398`, `u_yf_renocollectedonnecf`.`cf_3399` AS `cf_3399`, `u_yf_renocollectedonnecf`.`cf_3405` AS `cf_3405`, `u_yf_renocollectedonnecf`.`cf_3417` AS `cf_3417`, `u_yf_renocollectedonnecf`.`cf_3420` AS `cf_3420`, `u_yf_renocollectedonnecf`.`cf_3421` AS `cf_3421`, `u_yf_renocollectedonnecf`.`cf_3435` AS `cf_3435`, `u_yf_renocollectedonnecf`.`cf_3436` AS `cf_3436`, `u_yf_renocollectedonnecf`.`cf_3437` AS `cf_3437`, `u_yf_renocollectedonnecf`.`cf_3438` AS `cf_3438`, `u_yf_renocollectedonnecf`.`cf_3439` AS `cf_3439`, `u_yf_renocollectedonnecf`.`cf_3440` AS `cf_3440`, `u_yf_renocollectedonnecf`.`cf_3441` AS `cf_3441`, `u_yf_renocollectedonnecf`.`cf_3442` AS `cf_3442`, `u_yf_renocollectedonnecf`.`cf_3443` AS `cf_3443`, `u_yf_renocollectedonnecf`.`cf_3444` AS `cf_3444`, `u_yf_renocollectedonnecf`.`cf_3445` AS `cf_3445`, `u_yf_renocollectedonnecf`.`cf_3446` AS `cf_3446`, `u_yf_renocollectedonnecf`.`cf_3447` AS `cf_3447`, `u_yf_renocollectedonnecf`.`cf_3448` AS `cf_3448`, `u_yf_renocollectedonnecf`.`cf_3449` AS `cf_3449`, `u_yf_renocollectedonnecf`.`cf_3450` AS `cf_3450`, `u_yf_renocollectedonnecf`.`cf_3451` AS `cf_3451`, `u_yf_renocollectedonnecf`.`cf_3452` AS `cf_3452`, `u_yf_renocollectedonnecf`.`cf_3453` AS `cf_3453`, `u_yf_renocollectedonnecf`.`cf_3454` AS `cf_3454`, `u_yf_renocollectedonnecf`.`cf_3455` AS `cf_3455`, `u_yf_renocollectedonnecf`.`cf_3456` AS `cf_3456`, `u_yf_renocollectedonnecf`.`cf_3457` AS `cf_3457`, `u_yf_renocollectedonnecf`.`cf_3458` AS `cf_3458`, `u_yf_renocollectedonnecf`.`cf_3459` AS `cf_3459`, `u_yf_renocollectedonnecf`.`cf_3460` AS `cf_3460`, `u_yf_renocollectedonnecf`.`cf_3461` AS `cf_3461`, `u_yf_renocollectedonnecf`.`cf_3462` AS `cf_3462`, `u_yf_renocollectedonnecf`.`cf_3465` AS `cf_3465`, `u_yf_renocollectedonnecf`.`cf_3466` AS `cf_3466`, `u_yf_renocollectedonnecf`.`cf_3491` AS `cf_3491`, `u_yf_renocollectedonnecf`.`cf_3492` AS `cf_3492`, `u_yf_renocollectedonnecf`.`cf_3494` AS `cf_3494`, `u_yf_renocollectedonnecf`.`cf_3497` AS `cf_3497`, `u_yf_renocollectedonnecf`.`cf_3504` AS `cf_3504`, `u_yf_renocollectedonne`.`videsanitaire1` AS `videsanitaire1`, `u_yf_renocollectedonnecf`.`cf_3538` AS `cf_3538`, `u_yf_renocollectedonne`.`chauffage` AS `chauffage`, `u_yf_renocollectedonne`.`systventilationrefroid` AS `systventilationrefroid`, `u_yf_renocollectedonne`.`etancheisation` AS `etancheisation`, `u_yf_renocollectedonne`.`chauffeauresidenttiellepropane` AS `chauffeauresidenttiellepropane`, `u_yf_renocollectedonne`.`autre` AS `autre`, `u_yf_renocollectedonnecf`.`cf_3480` AS `cf_3480`, `u_yf_renocollectedonnecf`.`cf_3481` AS `cf_3481`, `u_yf_renocollectedonne`.`signature` AS `signature`, `u_yf_renocollectedonnecf`.`cf_3469` AS `cf_3469`, `u_yf_renocollectedonnecf`.`cf_3472` AS `cf_3472`, `u_yf_renocollectedonnecf`.`cf_3474` AS `cf_3474`, `u_yf_renocollectedonnecf`.`cf_3489` AS `cf_3489` FROM `u_yf_renocollectedonne` INNER JOIN `vtiger_crmentity` ON u_yf_renocollectedonne.renocollectedonneid = vtiger_crmentity.crmid LEFT JOIN `vtiger_users` `vtiger_userscreated_user_id` ON vtiger_crmentity.smcreatorid = vtiger_userscreated_user_id.id LEFT JOIN `vtiger_groups` `vtiger_groupscreated_user_id` ON vtiger_crmentity.smcreatorid = vtiger_groupscreated_user_id.groupid INNER JOIN `u_yf_renocollectedonnecf` ON u_yf_renocollectedonne.renocollectedonneid = u_yf_renocollectedonnecf.renocollectedonneid WHERE (`vtiger_crmentity`.`deleted`=0) AND (`u_yf_renocollectedonne`.`renocollectedonneid`='18867') || yii\db\Command::query
#32 [info] SELECT `crmid`, `setype`, `deleted`, `smcreatorid`, `smownerid`, `createdtime`, `private` FROM `vtiger_crmentity` WHERE `crmid`=18867 || yii\db\Command::query
#33 [info] SELECT `last_name`, `first_name`, `id` AS `id`, `is_admin`, `cal_color`, `status` FROM `vtiger_users` || yii\db\Command::query
#34 [info] SELECT `groupid`, `groupname` FROM `vtiger_groups` ORDER BY `groupname` || yii\db\Command::query
#35 [error] Rows or columns overflow! Excel5 has limit to 65535 rows and 255 columns. Use XLSX instead.
PhpOffice\PhpSpreadsheet\Writer\Exception: Rows or columns overflow! Excel5 has limit to 65535 rows and 255 columns. Use XLSX instead. in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xls/Worksheet.php:402
Stack trace:
#0 vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xls.php(185): PhpOffice\PhpSpreadsheet\Writer\Xls\Worksheet->close()
#1 modules/Vtiger/actions/QuickExport.php(122): PhpOffice\PhpSpreadsheet\Writer\Xls->save('/home/expertclo...')
#2 [internal function]: Vtiger_QuickExport_Action->exportToExcel(Object(App\Request))
#3 app/Controller/ExposeMethod.php(65): call_user_func_array(Array, Array)
#4 app/Controller/ExposeMethod.php(78): Vtiger_QuickExport_Action->invokeExposedMethod('exportToExcel', Object(App\Request))
#5 include/main/WebUI.php(183): Vtiger_QuickExport_Action->process(Object(App\Request))
#6 index.php(24): Vtiger_WebUI->process(Object(App\Request))
#7 {main}

**Comment by vovpff** [comment]
@maeglin4 You are called your system modification as a bug. Maybe main your main problem what the maximum number of columns for filter is 12 in standard system?

**Comment by vovpff** [comment]
Difficult to read your log but I counted about 300+ fields in filter. For me quicker way to use sql query in database manager and export result to csv

**Comment by maeglin4** [comment]
yeah, but its for users, i dont want to give them acces to the database.... :/

**Comment by vovpff** [comment]
Ok. What about expert to csv?

**Comment by bpabiszczak** [comment]
What you do [hundreds of columns] is not normal:] It must be designed by an architect and optimized mechanisms.
