### ISSUE TITLE
[bug] Calendar - DEFAULT_VIEW_RECORD not set in config

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#10591]
# 🐞 bug report
Accessing to calendar record view doesn't highlight **Details** tab

### 🔥 How to trigger the error
![detailhighlight](https://user-images.githubusercontent.com/48508691/58689449-561bd900-8387-11e9-9b45-c91f55506f29.gif)

### 👎 Actual Behavior
Details tab is not highlighted

### 👍 Expected Behavior
Highlighting of Details tab

### 📷 Screenshot of configuration
[none]

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
[indipendent]

### 🌍  Your Environment 
[indipendent]

### ❓ Additional context
[none]

### :heavy_check_mark: Fix
add DEFAULT_VIEW_RECORD in calendar config
/modules/Calendar/ConfigTemplate.php
```PHP
...
  'HIDDEN_DAYS_IN_CALENDAR_VIEW' => [
    'default' => [0, 6],
    'description' => 'Exclude certain days-of-the-week from being displayed. The value is an array of day-of-week indices to hide. Each index is zero-base (Sunday=0) and ranges from 0-6. By default, no days are hidden',
    'validation' => function () {
      $arg = func_get_arg(0);
      return $arg === 'Extended' || $arg === 'Standard';
    }
  ],
// ===>> added DEFAULT_VIEW_RECORD array index
  'DEFAULT_VIEW_RECORD' => [
    'default' => 'LBL_RECORD_PREVIEW',
    'description' => 'Default view for record detail view. Values: LBL_RECORD_DETAILS or LBL_RECORD_SUMMARY',
    'validation' => function () {
      $arg = func_get_arg(0);
      return $arg === 'LBL_RECORD_PREVIEW' || $arg === 'LBL_RECORD_DETAILS';
    }
  ],
  'SEND_REMINDER_INVITATION' => [
    'default' => true,
    'description' => 'Send mail notification to participants',
    'validation' => '\App\Validator::bool',
    'sanitization' => '\App\Purifier::bool'
  ],
...
```

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/16cc92a51d37f98c57059d31ea9905aaa5811154
