### ISSUE TITLE
{"success":false,"error":{"code":"Illegal request","message":"Illegal request"}}

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1059]
I ve created a sales user and he is getting this error first with Google chrome.
Then he changed to internet explorer and worked as normal.
Suddenly this message appeared on internet explorer too.

He can not do anything 

{"success":false,"error":{"code":"Illegal request","message":"Illegal request"}}

Help please

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html
