### ISSUE TITLE
syntax error, unexpected ''=>1559592301];' (T_ENCAPSED_AND_WHITESPACE)[Question]           

### ISSUE THREAD

**Issue by onpoint01** [YetiForceCompany/YetiForceCRM#10617]
Has anyone else gotten this error message sporadically, out of nowhere?

This is the second time this has happened to me in the last couple of days. No changes to the file were made, but this same thing occurred a few nights ago while setting up my YetiForm CRM

syntax error, unexpected ''=>1559592301];' (T_ENCAPSED_AND_WHITESPACE)

Error Log:
[03-Jun-2019 17:05:01 America/New_York] PHP Parse error:  syntax error, unexpected ''=>1559592301];' (T_ENCAPSED_AND_WHITESPACE) in /home/***/public_html/crm/user_privileges/cron.php on line 36
[03-Jun-2019 17:05:01 America/New_York] PHP Parse error:  syntax error, unexpected ''=>1559592301];' (T_ENCAPSED_AND_WHITESPACE) in /home/***/public_html/crm/user_privileges/cron.php on line 36
[03-Jun-2019 17:05:01 America/New_York] PHP Parse error:  syntax error, unexpected ''=>1559592301];' (T_ENCAPSED_AND_WHITESPACE) in /home/***/public_html/crm/user_privileges/cron.php on line 36
[03-Jun-2019 17:10:02 America/New_York] PHP Parse error:  syntax error, unexpected ''=>1559592301];' (T_ENCAPSED_AND_WHITESPACE) in /home/***/public_html/crm/user_privileges/cron.php on line 36

Referencing Line 36, user_privileges/cron.php:

> 'spaceRoot'=>['container'=>'env','type'=>'Space','testCli'=>false,'label'=>'SPACE_ROOT','status'=>true],'spaceStorage'=>['container'=>'env','type'=>'Space','testCli'=>false,'label'=>'SPACE_STORAGE','status'=>true],'spaceTemp'=>['container'=>'env','type'=>'Space','testCli'=>false,'label'=>'SPACE_TEMP','status'=>true],'lastCronStart'=>['container'=>'env','testCli'=>false,'label'=>'LAST_CRON_START','status'=>true],'open_basedir'=>['container'=>'php','testCli'=>true,'status'=>true],'variables_order'=>['container'=>'php','testCli'=>true,'status'=>true,'cron'=>'GPCS']],'publicDirectoryAccess'=>['config'=>['type'=>'ExistsUrl','container'=>'request','testCli'=>false,'status'=>true],'cache'=>['type'=>'ExistsUrl','container'=>'request','testCli'=>false,'status'=>true],'storage'=>['type'=>'ExistsUrl','container'=>'request','testCli'=>false,'status'=>true],'user_privileges'=>['type'=>'ExistsUrl','container'=>'request','testCli'=>false,'status'=>true]],'writableFilesAndFolders'=>['config/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'user_privileges/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'user_privileges/tabdata.php'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'user_privileges/menu_0.php'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'user_privileges/user_privileges_1.php'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/addressBook/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/images/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/import/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/logs/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/session/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/templates_c/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/upload/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/vtlib/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cache/vtlib/HTML'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'cron/modules/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'modules/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'storage/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'storage/Products/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'storage/Users/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'storage/Contacts/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'storage/OSSMailView/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'public_html/modules/OSSMail/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'public_html/libraries/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES'],'public_html/layouts/resources/Logo/'=>['type'=>'IsWritable','testCli'=>true,'status'=>true,'cron'=>'LBL_YES']],'last_start'=>1559592301];rt'=>1559592301];

Cite this part of Line 36:

**'last_start'=>1559592301];rt'=>1559592301];**

Changed the syntax to:

**'last_start'=>1559592301,'rt'=>1559592301];**

Just wondering if anyone else has had this, and why this seemingly changed on it's own without any human intervention or file updates since the last time 2-3 days ago.

**Comment by rskrzypczak** [comment]
This error could have appeared if you ran out of space on your drive for example. 
Remove the user_privileges/cron.php file.

**Comment by MandarinaWebs** [comment]
We have not that file

Did you get it fixed?
