### ISSUE TITLE
[Question]  Email thread not showing in Accounts page      

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10614]
Hi,

I have sent an email to an Account yet it does not appear in the Account profile under the emails section.

I sent the email by selecting "email" on the Account profile emails section and Roundcube opened a new window which I created and sent the email via.

Selecting an Account via RoundCube also returns the same issue.

**Comment by joelbcampos** [comment]
Look first if you have activated the mailscaner cron, and try this.
![Snap_2019 06 04_16h41m14s_001_2](https://user-images.githubusercontent.com/29610537/58896120-a54e6a80-86f5-11e9-9a82-7ae497d2aea5.gif)

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=Index&block=8&fieldid=44
