### ISSUE TITLE
[Question] Trying to connect webform and stucked with this:          

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10619]
Fatal error: Class 'Api\Core\BaseAction' not found in /var/www/html/yetiforce/api/webservice/Portal/Users/Login.php on line 11

What you can suggest?

**Comment by davide-alghi** [comment]
Hi waran,
what about your YF version?

I'm attaching some links, maybe they help you

https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST
https://github.com/YetiForceCompany/YetiForceCRM/issues/7276
https://github.com/YetiForceCompany/YetiForceCRM/issues/9103
