### ISSUE TITLE
Cron tasks not working after changing DocumentRoot to "public_html"

### ISSUE THREAD

**Issue by onpoint01** [YetiForceCompany/YetiForceCRM#10615]
Problem Statement: Cron is processing, however, the scheduled sequences under "Automation >> CRON" is not updating. Problem arose after altering the DocumentRoot from "/" to "public_html" within the YetiForce CRM

Troubleshooting:
- Opened the error_log and found the following error, once every five minutes, since the DocumentRoot was updated.: [03-Jun-2019 18:25:01 UTC] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/*******************/public_html/crm/app/Config.php on line 58 .......... This is in-line with when CRON is ran... possible correlation?

- On the "CRON" page, "Last Start" updates every five minutes as intended, however, "total time" shows "0 seconds" no matter what

- Nothing was changed with the cron job setup in cPanel, and the PHP path in Cron.sh is correct. Just for good measure, I tried to change the absolute paths in the cron jobs to include the "yetiforcecrm/public_html" root --- no change.

- If I run the cron.php directly in the Yetiforce root folder, the sequences update and the tasks are performed

- I've also referenced the "Enable Cron" documentation multiple times. Nothing in this documentation has helped thus far after troubleshooting the last few hours.

Any suggestions as to what could be causing this.

**Comment by onpoint01** [comment]
As an added FYI... in the process of all of this... the cron.log was throwing a 500 Internal Server Error... if my mind serves me correctly, it should produce the output result if successful.

Which leads to the question, why throw a 500 Internal Server error when I simply changed the DocumentRoot?

**Comment by paula-w** [comment]
Try the following steps:
1. Check if the cron file is properly executed.
2. Check if cron refers to proper PHP configuration (it’s the most common mistake, as there is a different configuration for the CRM and a different one for cron) 
3. The file often is not executable.
4. Get in touch with your admin, he should tell you what the cause is. 
We can help, but it’s a service we charge for.
