### ISSUE TITLE
How to add comments widget for custom module

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10626]
### Description

I am trying to add comments and calendar widget for custom module. I have identified comments and calendar type available for standard module but not for custom  module.How to add comments and calendar widget for custom module. Please check below video
![comments and calender](https://user-images.githubusercontent.com/47585969/58870169-02045200-8703-11e9-9e6b-e02e49823de2.gif)

**Comment by joelbcampos** [comment]
Did you add the links to your custom module?

**Comment by apcloic** [comment]
Did you try via vtlib ?
https://github.com/YetiForceCompany/YetiForceCRM/issues/2709

**Comment by vovpff** [comment]
@joelbcampos you can do it by SQL query
```
INSERT INTO db_name.vtiger_fieldmodulerel (fieldid, module, relmodule, status, sequence) VALUES ('601', 'ModComments', 'MODULE_NAME', NULL, NULL);
```

This is method to add comments at 3.x version but I think this should work in latest version. Maybe with some modifications.

**Comment by MixTecnico** [comment]
after updating I lost my comments module, in custom module..

any ideas!

**Comment by MixTecnico** [comment]
I solved the problem ... the module was created with a capital letter ...

when updating the module I change to lowercase ...

using with the new module name resolves

INSERT INTO db_name.vtiger_fieldmodulerel (fieldid, module, relmodule, status, sequence) VALUES ('601', 'ModComments', 'MODULE_NAME', NULL, NULL);

**Comment by simple-AMS** [comment]
@mariuszkrzaczkowski How would I accomplish this into a custom recruiting module I created in version 6.1.0 with Service Pack 6 installed? I copied exactly what I needed from another module within the database and have managed to get the comments module to display in setup but nothing within the summary tab of the record.

![1](https://user-images.githubusercontent.com/42642523/114507795-3e574200-9bf9-11eb-893f-747309da7112.png)
Shows up fine here

![2](https://user-images.githubusercontent.com/42642523/114507813-4616e680-9bf9-11eb-9441-e93f64964b2a.png)
Yet nothing where I need it

**Comment by MixTecnico** [comment]
sorry spanish

usa este código como ejemplo desde consola como root, cambiando el nombre **por el de tu modulo** (MODULE_NAME), podrás agregar comentarios al mismo

`INSERT INTO db_name.vtiger_fieldmodulerel (fieldid, module, relmodule, status, sequence) VALUES ('601', 'ModComments', 'MODULE_NAME', NULL, NULL);`

**Comment by simple-AMS** [comment]
Thanks @MixTecnico but I tried doing that and still nothing.

**Comment by MixTecnico** [comment]
lo estas intentando conectado a la base de datos?

**Comment by simple-AMS** [comment]
@MixTecnico Sorry don't understand. I tried adding it via an SQL inquiry which shows it worked got no errors but does not display the ability to select comments from the widget area.

**Comment by simple-AMS** [comment]
> @joelbcampos you can do it by SQL query
> 
> ```
> INSERT INTO db_name.vtiger_fieldmodulerel (fieldid, module, relmodule, status, sequence) VALUES ('601', 'ModComments', 'MODULE_NAME', NULL, NULL);
> ```
> 
> This is method to add comments at 3.x version but I think this should work in latest version. Maybe with some modifications.

@mariuszkrzaczkowski What is the process to make this work in Version 6.1.0 with Service Pack 6 installed?

**Comment by vovpff** [comment]
I think the same

**Comment by MixTecnico** [comment]
verificaste el nombre de tu modulo, me paso que por ser mayúscula no me tomaba el cambio

@MixTecnico Sorry don't understand. I tried adding it via an SQL inquiry which shows it worked got no errors but does not display the ability to select comments from the widget area.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/7f70873e4d83224574ccf58def524647928f6037/modules/LettersIn/LettersIn.php#L92-L98

**Comment by simple-AMS** [comment]
> $modcommentsModuleInstance = vtlib\Module::getInstance('ModComments'); 
>  if ($modcommentsModuleInstance && file_exists('modules/ModComments/ModComments.php')) { 
>  	include_once 'modules/ModComments/ModComments.php'; 
>  	if (class_exists('ModComments')) { 
>  		ModComments::addWidgetTo(['LettersIn']); 
>  	} 
>  }

@mariuszkrzaczkowski YOU ARE THE MAN!!!! Thank you so much mate. I'll dance at your wedding, you're a genius.

**Comment by JEEVAN28** [comment]
> ModComments

This worked for me, Thanks
