### ISSUE TITLE
[Question] Rewrite rules          

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#10640]
Just to make sure it is correct:

.htaccess contains following:

RewriteRule ^webservice/(.*)/(.*)/(.*)$ webservice.php?module=$1&action=$2&record=$3 [QSA,NC,L]
RewriteRule ^webservice/(.*)/(.*)$ webservice.php?module=$1&action=$2 [QSA,NC,L]
RewriteRule ^webservice/(.*)$ webservice.php?action=$1 [QSA,NC,L]

Is it correct bearing in mind that directory "webservice" is in "api" folder?

**Comment by mariuszkrzaczkowski** [comment]
it's not a folder, only the name in the url's address only for Rewrite
example: https://gitdeveloper.yetiforce.com/**webservice**/Methods
