### ISSUE TITLE
[BUG][PL] Zarządzanie językami - wybór języka w edycji języka

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1064]
Przy wyborze języka w Edycji języka i Ikony pomocy, loader się zawięsza, na print screenie błąd z konsoli 
![zrzut](https://cloud.githubusercontent.com/assets/3193498/8181188/3f1fa49c-1424-11e5-9971-26d307664f6c.png)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1089
