### ISSUE TITLE
[bug] In Yetiforce 5.1.0 version there is bug with output_buffering	On	1 is defaults taking 1 if we set On in php.ini also please clarify this to fix due to this my installation  is getting unsuccessful.

### ISSUE THREAD

**Issue by jaison-26** [YetiForceCompany/YetiForceCRM#10656]
# 🐞 bug report

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mariuszkrzaczkowski** [comment]
Attach the screen with the phpinfo, see our ini file as should be set to set
https://github.com/YetiForceCompany/YetiForceCRM/blob/81b2b2f74d8ac8413921826f01317c87a72a6a5a/.user.ini#L8

**Comment by waran70** [comment]
Does user.ini overriding php.ini settings (CLI, APACHE)?

**Comment by mariuszkrzaczkowski** [comment]
it depends on the server configuration

**Comment by mariuszkrzaczkowski** [comment]
check if you have correctly set up in php.ini
Correctly
`
 output_buffering = "On" 
`
Incorrectly:
`
 output_buffering = On 
`
OR
`
 output_buffering = 1
`

**Comment by HOSTED-POWER** [comment]
> Incorrectly:
> output_buffering = On

Any idea why this is incorrectly translated to 1? I would expect this to be really on and not converted to 1 by the parser :/

**Comment by mariuszkrzaczkowski** [comment]
https://www.php.net/manual/en/outcontrol.configuration.php

> output_buffering boolean/integer
You can enable output buffering for all files by setting this directive to 'On'. If you wish to limit the size of the buffer to a certain size - you can use a maximum number of bytes instead of 'On', as a value for this directive (e.g., output_buffering=4096). This directive is always Off in PHP-CLI.

**Comment by HOSTED-POWER** [comment]
Thanks a lot for your fast reply, I read the numerous times and still don't understand what's wrong with just writing On instead of "On" :/

Off/On work for other settings as far as I know, normally "" aren't needed afaik
