### ISSUE TITLE
[Question] REST API           

### ISSUE THREAD

**Issue by Marshal4582** [YetiForceCompany/YetiForceCRM#10660]
How to get token used in connection with yeti via provided API? Is there any documents on that?
Let say, I need to create a record in Contacts" module, what usual steps I need to take to get it working

**Comment by Marshal4582** [comment]
Asking, as I noticed that in current webservice files there is a lot of stuff like that:
if (\Api\Portal\Privilege::isPermitted($value['name'])) {

Where path Api\Portal simply dont exists

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=WebserviceApps&view=Index&parent=Settings&block=5&fieldid=100
![image](https://user-images.githubusercontent.com/10198654/59086855-42cab980-8903-11e9-82eb-df7f9efbdff1.png)
