### ISSUE TITLE
[Question] How to add other languages?

### ISSUE THREAD

**Issue by beppe9000** [YetiForceCompany/YetiForceCRM#10668]
I only get english ?
![](https://i.imgur.com/Y3YTuHE.png)

**Comment by mariuszkrzaczkowski** [comment]
Software configuration > System tools > Language Management

![image](https://user-images.githubusercontent.com/10198654/59098655-28073d80-8921-11e9-8537-1adb26e2544b.png)


![image](https://user-images.githubusercontent.com/10198654/59098667-335a6900-8921-11e9-88d9-2af14de84af8.png)

**Comment by beppe9000** [comment]
Thanks!
