### ISSUE TITLE
[BUG][PL] Tworzenie klienta - nadawanie dostępu do portalu

### ISSUE THREAD

**Issue by MaciejStencel** [YetiForceCompany/YetiForceCRM#1066]
Obieg informacji jest tak skonstruowany że dane dostępowe dla kontaktu są generowane i wysyłane TYLKO przy edycji już istniejącego kontaktu kiedy się zaznaczy dostęp do portalu.

W przypadku gdy tworzymy rekord kontaktu i od razu zaznaczymy dostęp do portalu, wtedy taki kontakt nie otrzyma żadnych danych dostępowych do portalu.

Żeby je otrzymał trzeba zedytować kontakt i odznaczyć dostęp do portalu (warunek w obiegu to zmiana tego pola, a skrypt sprawdza czy jest włączone), zapisać go, następnie ponownie zedytować i nadać dostęp. Dopiero przy tym zapisie wyśle dane dostępowe.

**Comment by bpabiszczak** [comment]
Obecnie workflow może być uruchamiany przez użytkownika, potrzebowaliśmy to u kilku klientów. A więc całe wysyłanie maili należy przerzucić jako wywoływane ręcznie. Wtedy użytkownik klika ikonkę, wybiera akcje [np. wyślij maila z dostępem] i mail leci ;]

**Comment by bpabiszczak** [comment]
Nie uważam tego za błąd, tak to zostało zaprojektowane, należy to zmienić.

**Comment by waran70** [comment]
Rozumiem

I think it should be automated. Bear in mind creation of contacts using
webservices or mailscanner.
In many instances it will help a lot. Actually it works in automated mode
in vtiger

Stern

On Wed, Jun 17, 2015 at 6:59 PM, Błażej Pabiszczak <notifications@github.com

**Comment by bpabiszczak** [comment]
Portal klienta jest właśnie całkowicie przebudowywany, a więc i cała logika będzie zupełnie inna. Więcej informacji tutaj: https://github.com/YetiForceCompany/YetiForceCRM/issues/1385
