### ISSUE TITLE
How to Register Invoke custom function task      

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10667]
### Description

How to Register Invoke custom function task     

![custome invoke](https://user-images.githubusercontent.com/47585969/59093366-1fc9f500-8957-11e9-8870-9d6287f38208.JPG)

**Comment by z0lo13** [comment]
1. Create a script and put it in 
"modules/YOURMODULE/workflows/YOURSCRIPT.php"
2.to add your function over there ->com_vtiger_workflowtasks_entitymethod
3. Modify ->com_vtiger_workflowtasks_entitymethod_seq
4. Add it in worfklow
5. Enjoy
