### ISSUE TITLE
[Question] REST API Module Permissions

### ISSUE THREAD

**Issue by dbrlk** [YetiForceCompany/YetiForceCRM#10675]
Hello,

I'm trying to add new records to Accounts module via REST but it fails. I can successfully login and get token but when I call "listModules" function, an empty array returns. I think this is the problem. 

Is there any proper document for it? 

Thanks in advance.

**Comment by Marshal4582** [comment]
Me postman returning this:

modules Array ( ) ************************ methods Array ( ) ************************ privileges for module Accounts Array ( ) ************************ fields for module Accounts ************************ create new recordArray ( ) ************************ uuups, tried to logout, but session still alive...


Any clue?

**Comment by waran70** [comment]
My server configuration is nearly perfect. The only public_html is not as per recommendation. 
Webservices here also got problems...

**Comment by mariuszkrzaczkowski** [comment]
we need the following information to analyze the problem:

- attach a screenshot of server configuration verification
- create an example request in the postman application and attach screenshots with all settings
- attach screenshots from Web service - Applications (https://gitdeveloper.yetiforce.com/index.php?module=WebserviceApps&view=Index&parent=Settings&block=5&fieldid=100)
- attach screenshots from Web service - users
  (https://gitdeveloper.yetiforce.com/index.php?module=WebserviceUsers&view=List&parent=Settings&block=5&fieldid=106)
- run full application and server logs and send to us github@yetiforce.com (in the title, give the error number from github)
- check the same on gitdev, see if you log in properly to api
- turn on api logs and send to us github@yetiforce.com (in the title, give the error number from github)
https://github.com/YetiForceCompany/YetiForceCRM/blob/f9e59c0e72ce8693d89b18c66c81a3a982a36254/config/Debug.php#L87-L91

**Comment by mariuszkrzaczkowski** [comment]
We start creating documentation for the API, see https://doc.yetiforce.com/api/
