### ISSUE TITLE
[bug] No e-mail adress

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#10678]
# 🐞 bug report

### ⁉️ Describe the bug

Every login as admin I has this message:

```
No e-mail address was added to company details. If you want to receive newsletter Fill in the required information.
```
I can't managed e-mail here: `Software configuration/Company information/Company details/System settings`

![image](https://user-images.githubusercontent.com/8545791/59179196-f1703380-8b69-11e9-9c98-96c7166a41cc.png)

But now if I click edit button I can't fill email address because there is no field for email.

![image](https://user-images.githubusercontent.com/8545791/59179316-50ce4380-8b6a-11e9-83de-0c95df1a0097.png)

What I doing wrong?

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.1.0 sp 4

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/59179883-b10db700-8b63-11e9-8c6f-e72bc5af7a1b.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks but I don't need newsletters. I checks github every 15 minutes.

**Comment by acoolov** [comment]
How do I get opt out of a news letter and don't receive this message? This is forcing people to opt in to a news letter.

**Comment by mariuszkrzaczkowski** [comment]
@vovpff 
Have you seen it https://www.youtube.com/playlist?list=PLX0lktP3Kukh0O7w3cXbYx6cP0Z81VJdw

**Comment by mariuszkrzaczkowski** [comment]
@acoolov 
![image](https://user-images.githubusercontent.com/10198654/59179883-b10db700-8b63-11e9-8c6f-e72bc5af7a1b.png)

**Comment by acoolov** [comment]
Once I opt out it constantly displays message that there is no email on file. 
How do I not receive this message?
