### ISSUE TITLE
[Question] How to ignore Item No changes for history tab?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#10679]
### Description

Is it possible ignore `Item No` changes for history tab? `Item No` column needed  but if only order of records changed there are a lot of trash records appears in updates tab.

![image](https://user-images.githubusercontent.com/8545791/59182561-be7e6d80-8b72-11e9-9f53-8084c3142d1c.png)

**Comment by davide-alghi** [comment]
___
I write this for other future readers! 
**This proposal is only for an experienced YF user. This modifies the YF core code and it's always discouraged. This change may require actions on release/version updating.**
___

Hi Vladimir,
you need to modify YF core code.

in /layouts/basic/modules/Vtiger/RecentActivitiesInventory.tpl:11 add **$KEY eq 'seq'** into if statement
```HTML
	{if !$CHANGE['field']->isVisible() || $KEY eq 'seq'}{continue}{/if}
```

**Comment by konadrian** [comment]
We don't have a feature which allows you to disable and enable fields in changes tracker

**Comment by vovpff** [comment]
@davide-alghi your solution affects only on data imagination? What about database?
Also many many thanks for this solution!!!

**Comment by davide-alghi** [comment]
Yes Vladimir, only on layout. About data storing, a change should be made on ModTracker module, and honestly I have no experience on that.

**Comment by vovpff** [comment]
@davide-alghi ok. Thanks!
