### ISSUE TITLE
How to increase workflow  maximum limit for Execution schedule 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10685]
### Description

How to increase workflow  maximum limit for Execution schedule 

![Maximum limit exceeded](https://user-images.githubusercontent.com/47585969/59247043-74c08080-8c61-11e9-81ae-48a40d849c09.JPG)

**Comment by mrzewnicki** [comment]
I would suggest to check config files, does it's hard coded somewhere. Before you change anything remember that once hard coded it's not without reason and you can "demage"  a system. So if it's hard coded i wouldn't touch it.  Other way i suggest write your own script and add it to CRON. Mayby describe you problem. What you need?

**Comment by mrzewnicki** [comment]
Please also give your Yeti version becaue on 5.0.0 - complete i don't have problem with execution limit

**Comment by guide5232** [comment]
> Please also give your Yeti version becaue on 5.0.0 - complete i don't have problem with execution limit

5.1 version
