### ISSUE TITLE
Cron.php error

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10686]
Błąd pojawia się przy próbie odczytu Konfiguracji Serwera w Logach w Panelu Administratora
Nie do końca wiem w czym ma problem. Wersja 5.0.0 na linuxie. Błąd pojawił się po porannym zalogowaniu, innymi słowy wczoraj go nie bylo ;)

![image](https://user-images.githubusercontent.com/21024857/59248368-7dde2d00-8c22-11e9-857a-8e5fca6698e8.png)

po "debugingu" czyli po przenoszeniu do nowych linii żeby zobaczyć gdzie jest błąd 😄  wskazał to miejsce:
![image](https://user-images.githubusercontent.com/21024857/59248030-7cf8cb80-8c21-11e9-860e-1cb39e3f698c.png)

błąd z cron.log:
`PHP Parse error:  syntax error, unexpected 'cron' (T_STRING) in /var/www/html/my_path/user_privileges/cron.php on line 32
18/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/mysqli.so (/usr/lib/php/20170718/mysqli.so: undef$
PHP Parse error:  syntax error, unexpected 'cron' (T_STRING) in /var/www/html/my_path/user_privileges/cron.php on line 32

Parse error: syntax error, unexpected 'cron' (T_STRING) in /var/www/html/my_path/user_privileges/cron.php on line 32
`

**Comment by mariuszkrzaczkowski** [comment]
1. Zalecamy aktualizacje do 5.1.0
2. Usuń plik user_privileges/cron.php jak po uruchomieniu cron-a dalej będzie błąd to sprawdź konfiguracji PHP dla CLI

**Comment by mrzewnicki** [comment]
Po usunięciu pliku błąd zniknął, dzięki za podpowiedź. Aktualizacją się zainteresuje.
