### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by apabiszczak** [YetiForceCompany/YetiForceCRM#1069]
![kolorystyka logo](https://cloud.githubusercontent.com/assets/10338411/8205144/3a86681a-14ee-11e5-8d3b-7b6302f488fd.jpg)

Currently there are no plans to change the appearance of the logo because we have already made a decision. That’s why we asked you for advice about colors and gradient (with or without it?). I suggest everyone who is interested in this topic to vote on GitHub for the best color [you can also suggest a different color if you don’t like the suggested ones]. We are also eager to discuss this topic, but we don’t want to spend on it more than 48 hours.

**Comment by waw555** [comment]
I'm select №9

If the logo in the system, to change it depending on the color theme

**Comment by eptapsyxos** [comment]
vote number 3

**Comment by mariuszkrzaczkowski** [comment]
9,10,8

**Comment by apabiszczak** [comment]
#1 :)

**Comment by MaciejStencel** [comment]
Obviously number 8 ;)

**Comment by GorskaAnna** [comment]
1  :):)

**Comment by konadrian** [comment]
5,10

**Comment by KatarzynaUlichnowska** [comment]
1 or 5

**Comment by bpabiszczak** [comment]
3 or 5

**Comment by rskrzypczak** [comment]
7,2,9,4

**Comment by waran70** [comment]
3 - closer to #D50F25 what is one of google color. It works great with black and white. Standard application colors nicely going with #D50F25
It works good with alpha transparency. Gradient don't suit to modern flat web design.
3 can be starting point for shades. Grey's are also OK in some design.
my 2 grosze

**Comment by apabiszczak** [comment]
![kolorystyka logo 2](https://cloud.githubusercontent.com/assets/10338411/8205936/61a6679a-14f5-11e5-9a5f-9bc160a04618.jpg)

**Comment by eptapsyxos** [comment]
a see an extra logo and i liked!
vote for 11

**Comment by kpaulaha** [comment]
3, 5

**Comment by waran70** [comment]
11 - clear, aggressive, evokes respect

**Comment by waran70** [comment]
Looks like holy graal or on the other hand gets close to pentagram - showing female and male connection.
![61a6679a-14f5-11e5-9a5f-9bc160a04618](https://cloud.githubusercontent.com/assets/6852348/8213091/bba2fb6a-1549-11e5-85c0-e299a0c1f4fe.jpg)

Powerful!

**Comment by florek41** [comment]
as Błażej - 3 or 5

**Comment by GorskaAnna** [comment]
The results of voting:
The vinning logo is no. 3
Logo no. 3 - 5 votes
Logo no. 1 - 3 votes
Logos no. 9 &11 - 2 votes
Logos no. 5,7,8 - 1 vote each

**Comment by GorskaAnna** [comment]
The results of voting:
The vinning logo is no. 3
Logo no. 3 - 5 votes
Logo no. 1 - 3 votes
Logos no. 9 &11 - 2 votes
Logos no. 5,7,8 - 1 vote each
