### ISSUE TITLE
[bug] Do not save, the modifications in profiles.

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#10699]
I try to modify the profiles but when I save, I do not make the modifications.

![Untitled Project](https://user-images.githubusercontent.com/29610537/59265430-990e6400-8c45-11e9-9b2b-caa20faf5a2f.gif)

**Comment by paula-w** [comment]
Can you post configuration verification screenshots?

**Comment by joelbcampos** [comment]
Sorry, but I do not know exactly what capture asks me

**Comment by joelbcampos** [comment]
![Snap_2019 06 11_14h22m51s_004_](https://user-images.githubusercontent.com/29610537/59271974-3d4bd700-8c55-11e9-8e62-eaab998a92fa.jpg)
![Snap_2019 06 11_14h27m59s_005_](https://user-images.githubusercontent.com/29610537/59271975-3d4bd700-8c55-11e9-8035-d9f4087b209a.jpg)
![Snap_2019 06 11_14h28m20s_006_](https://user-images.githubusercontent.com/29610537/59271976-3d4bd700-8c55-11e9-92f3-9ca0b4706850.jpg)
![Snap_2019 06 11_14h28m33s_007_](https://user-images.githubusercontent.com/29610537/59271977-3de46d80-8c55-11e9-9d11-ecbfcc14447d.jpg)
![Snap_2019 06 11_14h17m01s_001_](https://user-images.githubusercontent.com/29610537/59271978-3de46d80-8c55-11e9-8fde-4cb5cedda5d3.jpg)
![Snap_2019 06 11_14h17m15s_002_](https://user-images.githubusercontent.com/29610537/59271980-3de46d80-8c55-11e9-9660-eb0027675622.jpg)

**Comment by paula-w** [comment]
In order for your CRM to work properly all the parameters must be correct. Profiles don't work because the configuration is wrong.
