### ISSUE TITLE
mailing list archieve not updated

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#107]
Hi,
looked for a message in the mailing list archieve and saw that it didn'get updated since Friday 2am. http://sourceforge.net/p/yetiforce/yetiforce/yetiforce-mailing/?viewmonth=201501

**Comment by KatarzynaUlichnowska** [comment]
Hello,
thank you for informing us, we reported it to SourceForge.
Due to the fact that this issue is not related to functioning of YetiForce system it will be closed.
Regards
