### ISSUE TITLE
[bug] [PL] Wartość z modułu powiązanego Array

### ISSUE THREAD

**Issue by espeoceka** [YetiForceCompany/YetiForceCRM#10708]
# 🐞 bug report

### ⁉️ Describe the bug

Cześć, mam problem z wartością z modułu powiązanego. 
Mam 2 moduły w jedym jest zlecenie a w drugim spłaty. Moduł spłaty pobiera wartość zlecenia z modułu sprawy. Wartość za pierwszym razem jest poprawna ale kiedy zmienię umowę ( np ludzki błąd ). Wartość zmienia się na Arraynowakwota|#|starakwota|#|itd.

Wiem że to pole nie koniecznie powinno być widoczne w widoku edycji ale niestety w widoku listy również pojawia się wartość Array. 

Czy jest na to jakiś sposób żeby wartośc z pola zależnego wyświetlała się poprawnie ? ( bez Array)
Czy mogę użyć tego pola do prostej automatyzacji kwota zlecenia - kwota spłaty ? ( pole wartości powiązanej traktowane jest jako 0 nawet jeżeli przyjmuje poprawną wartość za pierwszym razem )

### 🔥 How to trigger the error

1. Utwórz moduł dodaj pole walutowe kwota
2. Utwórz moduł i powiąż go z pierwszym modułem
3. Utwórz pole wartości z modułu powiązanego dla kwoty
4.Wprowadź do obu modułów po rekordzie
5. Dodaj z modułu drugiego powiązanie do modułu pierwszego
6. Usuń powiązanie
7. Dodaj ponownie
8. Wartość Array w polu powiązanym

### 📷 Screenshot of configuration

Screenshot
https://screenshots.firefox.com/1pDsKXf0n23GG4LP/gitdeveloper.yetiforce.com

Link do gitdeveloper
https://gitdeveloper.yetiforce.com/index.php?module=TestB&view=Detail&record=3900&mode=showDetailViewByMode&requestMode=full&tab_label=LBL_RECORD_DETAILS

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by arek1-618** [comment]
Sprawdziłem ten problem na obecnej wersji i wygląda na to, że błąd już nie występuje.
