### ISSUE TITLE
Bug: Backup does not work

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1070]
Version 2.0.132

When executing the function 'System Settings -> Security -> Backup', I get a page without any content (only the header, menu, and footer).

cache/logs/phpError.log contains the following error message:
[17-Jun-2015 15:35:46 Europe/Amsterdam] PHP Fatal error:  Call to a member function FetchRow() on boolean in /opt/yetiforce-2.0.132/include/database/PearDatabase.php on line 506

**Comment by bpabiszczak** [comment]
Please test here: https://lab.yetiforce.com/backup/index.php [admin/Dostep97]

**Comment by diderich** [comment]
In this version, it works fine.
Claude

**Comment by waw555** [comment]
Version 2.0.133 same as a blank page with no errors in phpError.log

**Comment by waw555** [comment]
More stops working and the history of the accordion passages as if the script is canceled

And the menu climbs been here #1015

**Comment by waw555** [comment]
system.log

Thu Jun 18 17:43:39 2015,385 [9104] DEBUG VT - query being executed : SELECT * FROM `vtiger_users` WHERE is_admin = 'on' AND deleted = 0
Thu Jun 18 17:43:39 2015,386 [9104] DEBUG VT - query being executed : SELECT vtiger_backup_tmp.*, vtiger_backup.filename FROM vtiger_backup_tmp LEFT JOIN vtiger_backup ON vtiger_backup.id = vtiger_backup_tmp.id WHERE vtiger_backup_tmp.status = 0
Thu Jun 18 17:43:39 2015,437 [9104] INFO VT - PearDatabase ->ADODB error  Query Failed:SELECT vtiger_backup_tmp.*, vtiger_backup.filename FROM vtiger_backup_tmp LEFT JOIN vtiger_backup ON vtiger_backup.id = vtiger_backup_tmp.id WHERE vtiger_backup_tmp.status = 0::->[1146]Table 'crm.vtiger_backup' doesn't exist


Country does not create a database vtiger_backup

**Comment by waw555** [comment]
When you import a query

CREATE TABLE `vtiger_backup` (
   `id` int (19) unsigned NOT NULL AUTO_INCREMENT,
   `filename` varchar (20) NOT NULL,
   `starttime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `endtime` datetime DEFAULT NULL,
   `status` tinyint (1) unsigned NOT NULL DEFAULT '0'
   `backuptime` decimal (8,3) unsigned NOT NULL DEFAULT '0.000',
   `backupcount` tinyint (1) unsigned NOT NULL DEFAULT '0'
   PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

It produces an error

# 1067 - Invalid default value for 'starttime'

**Comment by waw555** [comment]
change starttime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
