### ISSUE TITLE
[BUG] Language Editor and jquery.min.js

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1071]
Not working language editor in version 2.0 and higher.

If you replace a file jquery.min.js, file of version 1.4, everything works.

**Comment by waw555** [comment]
To fix this problem? I can not do normal transfer

**Comment by mariuszkrzaczkowski** [comment]
Fixed in  https://github.com/YetiForceCompany/YetiForceCRM/commit/86e86e2441df172918c3288fb2bc9883df5a6651
