### ISSUE TITLE
How to add Calender widget for custom module        

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10725]
### Description
How to add Calender widget for custom module

**Comment by davide-alghi** [comment]
Hi guide5232,
it cannot be done via GUI: you need a few code development.

**Comment by davide-alghi** [comment]
better ...

What it cannot be done via GUI is to relate an calendar record to custom module record: this can be done only for ['Accounts', 'Leads', 'Contacts', 'Vendors', 'OSSEmployees', 'Campaigns', 'HelpDesk', 'Project', 'ServiceContracts', 'SSalesProcesses', 'SQuoteEnquiries', 'SRequirementsCards', 'SCalculations', 'SQuotes', 'SSingleOrders', 'SRecurringOrders', 'SVendorEnquiries']. This is the reason you cannot add Calendar widget to your custom module. eg for Project Milestones you cannot add Calendar widget.

But let's go to see which relations you can establish between you custom module records and Calendar records

1. simple and single Calendar record relation
---- simply add a **Related field 1:M** in your module. In this way you create a relation 1:M between custom module record and Calendar record
2. multiple records Calendar relations
---- create a **relation** with the Calendar module
---- create a **Related module** widget and select Calendar module

**Comment by konadrian** [comment]
As @davide-alghi  said this is list of allowed modules for this widget
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Vtiger/widgets/Activities.php#L11

Adding additional modules need a programmer
