### ISSUE TITLE
[bug] add picture and table when create a new email on workflow. Add template module on roundcube

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#10726]
Oh hi there !
This is the first time opening an issue - bug....sorry for my english....<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

I have two versions of Yetiforce. 4.3.0 and 5.1.0. 

The bug is at version 5.1.0:

1. When i try to add picture or table inside the workflow it doesn't work fine. I can not write letters or numbers. I tried it with firefox and chrome, the same. I also tried it on demo. The same. But be careful, when you try to create an email template it work fine
Go to System settings->Automation->Workflow. Add any workflow and try to create a new email. After that try to add a picture or a table. See the error.
http://prntscr.com/o1pjae
2. i have made an email template (for example on module Accounts) and try to compose a new email and add the email template from Roundcube. It doesn't work fine, especially it doesn't add the main text of email but only the subject of email. (i see on demo it works fine on [ver. 5.1.93] )

the strange is that the above both issues work fine on version 4.3.0

i hope to describe it well

thank you for all and i am happy i am here !

**Comment by rskrzypczak** [comment]
The bug doesn't occur in the current version.
It is difficult to point out specific commits because there have been many modifications.
Check this: https://github.com/YetiForceCompany/YetiForceCRM/issues/10536#issuecomment-591428418
