### ISSUE TITLE
[Question]  [error] No guardar, las modificaciones en los perfiles. # 10699         

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#10729]
I attach the php configuration, which is what is wrong configured that prevents me from saving the profiles.

![Snap_2019 06 14_12h33m16s_001_](https://user-images.githubusercontent.com/29610537/59503500-d91d5300-8ea0-11e9-9cf7-327685ed2919.jpg)

**Comment by mariuszkrzaczkowski** [comment]
This is just a list of extensions, the problem is probably in the php configuration

**Comment by joelbcampos** [comment]
Thank you, but unfortunately I still do not know exactly what it may be. Do you have a specific paramenter for this function?

**Comment by mariuszkrzaczkowski** [comment]
attach the contents of phpinfo

**Comment by joelbcampos** [comment]
[phpinfo().txt](https://github.com/YetiForceCompany/YetiForceCRM/files/3300745/phpinfo.txt)

**Comment by joelbcampos** [comment]
![Snap_2019 06 18_16h55m25s_021_](https://user-images.githubusercontent.com/29610537/59696210-e1042c80-91eb-11e9-8300-32657265727c.jpg)
![Snap_2019 06 18_16h55m49s_022_](https://user-images.githubusercontent.com/29610537/59696212-e19cc300-91eb-11e9-8d61-4051728ae142.jpg)
![Snap_2019 06 18_16h56m09s_023_](https://user-images.githubusercontent.com/29610537/59696216-e3668680-91eb-11e9-9565-014ec3ac5c70.jpg)
![Snap_2019 06 18_16h56m30s_024_](https://user-images.githubusercontent.com/29610537/59696217-e3668680-91eb-11e9-8cc0-3b8cee5d4c7e.jpg)
![Snap_2019 06 18_16h56m50s_025_](https://user-images.githubusercontent.com/29610537/59696218-e3ff1d00-91eb-11e9-9e82-1c76ce130220.jpg)
![Snap_2019 06 18_17h02m12s_030_](https://user-images.githubusercontent.com/29610537/59696219-e3ff1d00-91eb-11e9-9e6b-8f1cf37dd820.jpg)
![Snap_2019 06 18_16h46m14s_001_](https://user-images.githubusercontent.com/29610537/59696220-e3ff1d00-91eb-11e9-844f-0acfe6573e3e.jpg)
![Snap_2019 06 18_16h46m40s_002_](https://user-images.githubusercontent.com/29610537/59696221-e497b380-91eb-11e9-950e-566e6ef3ce96.jpg)
![Snap_2019 06 18_16h47m03s_003_](https://user-images.githubusercontent.com/29610537/59696224-e497b380-91eb-11e9-9e31-0e7367f2a56a.jpg)
![Snap_2019 06 18_16h47m37s_004_](https://user-images.githubusercontent.com/29610537/59696225-e497b380-91eb-11e9-8e90-991673d7fb24.jpg)
![Snap_2019 06 18_16h47m59s_005_](https://user-images.githubusercontent.com/29610537/59696226-e497b380-91eb-11e9-83ac-fa4a50998352.jpg)
![Snap_2019 06 18_16h48m23s_006_](https://user-images.githubusercontent.com/29610537/59696227-e5304a00-91eb-11e9-9fb0-46e6bb375be7.jpg)
![Snap_2019 06 18_16h48m50s_007_](https://user-images.githubusercontent.com/29610537/59696228-e5304a00-91eb-11e9-85dc-0995fcb0b84b.jpg)
![Snap_2019 06 18_16h49m13s_008_](https://user-images.githubusercontent.com/29610537/59696230-e5304a00-91eb-11e9-86b2-7a06ad71f6cd.jpg)
![Snap_2019 06 18_16h49m42s_009_](https://user-images.githubusercontent.com/29610537/59696232-e5c8e080-91eb-11e9-8479-16f1a0780a9c.jpg)
![Snap_2019 06 18_16h50m15s_010_](https://user-images.githubusercontent.com/29610537/59696233-e5c8e080-91eb-11e9-942c-c73c1333c00e.jpg)
![Snap_2019 06 18_16h51m01s_011_](https://user-images.githubusercontent.com/29610537/59696236-e792a400-91eb-11e9-9325-859b633e304d.jpg)
![Snap_2019 06 18_16h51m18s_012_](https://user-images.githubusercontent.com/29610537/59696238-e792a400-91eb-11e9-8eef-2e5327762ec7.jpg)
![Snap_2019 06 18_16h51m41s_013_](https://user-images.githubusercontent.com/29610537/59696239-e792a400-91eb-11e9-9144-97bec9b0e570.jpg)
![Snap_2019 06 18_16h52m11s_014_](https://user-images.githubusercontent.com/29610537/59696240-e792a400-91eb-11e9-968a-c8b396bb540e.jpg)
![Snap_2019 06 18_16h52m35s_015_](https://user-images.githubusercontent.com/29610537/59696241-e82b3a80-91eb-11e9-8649-3701e8911a16.jpg)
![Snap_2019 06 18_16h53m02s_016_](https://user-images.githubusercontent.com/29610537/59696242-e82b3a80-91eb-11e9-8fc2-57a234ee1c32.jpg)
![Snap_2019 06 18_16h53m25s_017_](https://user-images.githubusercontent.com/29610537/59696243-e82b3a80-91eb-11e9-9105-fefae758b0f4.jpg)
![Snap_2019 06 18_16h54m06s_018_](https://user-images.githubusercontent.com/29610537/59696245-e8c3d100-91eb-11e9-8210-e5fe0cc7d01d.jpg)
![Snap_2019 06 18_16h54m39s_019_](https://user-images.githubusercontent.com/29610537/59696246-e8c3d100-91eb-11e9-829f-66fc1e19b219.jpg)
![Snap_2019 06 18_16h54m57s_020_](https://user-images.githubusercontent.com/29610537/59696249-e95c6780-91eb-11e9-9d50-662f2990da7e.jpg)
