### ISSUE TITLE
Installation unsuccessful

### ISSUE THREAD

**Issue by Batalenkov** [YetiForceCompany/YetiForceCRM#10734]
Good day. I configured the server but the installation fails. You give a "Installation unsuccessful"
[Sat Jun 15 15:14:35.735336 2019] [fcgid:warn] [pid 5296] [client 188.170.74.235:55420] mod_fcgid: stderr: PHP Warning:  Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) in Unknown on line 0
My options are http://crm2019.batalenkow820919.411.com1.ru/i.php

What can be done?
thank

**Comment by davide-alghi** [comment]
Hi Batalenkov,
maybe the problem is related to your web-server: in some web-servers, if you enable Opache two times, it stops to work. I suppose you have correctly enabled Opache into php.ini. 
Now, in **/.user.ini** and in **/public_html/.user.ini**, try to comment Opache enabling setting with a semicolon **;** (in both files)

```CODE
...
disable_functions = "shell_exec,exec,system,passthru"
;opcache.enable = "On"
opcache.enable_cli = "On"
opcache.max_accelerated_files = 40000
...
```
If this resolves the problem in web-server, maybe you need to fix it for Cron too [**;** (in both files)]
```CODE
...
disable_functions = "shell_exec,exec,system,passthru"
;opcache.enable = "On"
;opcache.enable_cli = "On"
opcache.max_accelerated_files = 40000
...
```

**Comment by Batalenkov** [comment]
> Привет Баталенков,
> возможно, проблема связана с вашим web-сервером: на некоторых web-серверах, если вы включаете Opcache два раза, он перестает работать. Я полагаю, вы правильно включили Opcache в php.ini.
> Сейчас, в **/.пользователь.ini **и in**/public_html/.пользователь.ini**, попробуйте прокомментировать параметр Opcache с точкой с запятой**; **(в обоих файлах)
> 
> ```
> ...
> disable_functions = "shell_exec,exec,system,passthru"
> ;opcache.enable = "On"
> opcache.enable_cli = "On"
> opcache.max_accelerated_files = 40000
> ...
> ```
> 
> Если это решает проблему в web-server, возможно, вам нужно исправить это для Cron [**; **(в обоих файлах)]
> 
> ```
> ...
> disable_functions = "shell_exec,exec,system,passthru"
> ;opcache.enable = "On"
> ;opcache.enable_cli = "On"
> opcache.max_accelerated_files = 40000
> ...
> ```

Thanks for the quick response.
The problem remains, but the error is different
2019/06/15 19:25:24 [warn] 591 # 591: * 1 / up / 1/00/0000000001 while reading upstream, client: 188.170. 74.235, server: crm2019.batalenkow820919.411.com1.ru, request: "POST /install/Install.php HTTP / 1.1", upstream: "http://127.0.0.1:8080/install/Install.php", host : "crm2019.batalenkow820919.411.com1.ru"

**Comment by davide-alghi** [comment]
What about your web-server? nginx?
if yes, maybe that is a proxy problem related to your server

**Comment by Batalenkov** [comment]
> А как насчет вашего веб-сервера? nginx?
> если да, возможно, это проблема прокси, связанная с вашим сервером

Unfortunately, I am not an expert, and I only give up everything. According to the server, as I understand it, there are characteristics http://crm2019.batalenkow820919.411.com1.ru/i.php
Can you tell what to see yet?
Thank you so much!

**Comment by davide-alghi** [comment]
it's a page not found: 404 error

**Comment by davide-alghi** [comment]
https://www.reg.ru/support/hosting-i-servery/sajty-i-domeny/moy-sayt-ne-rabotaet/oshibka-404

**Comment by Batalenkov** [comment]
![crm2019 batalenkow820919 411 com1 ru_i php](https://user-images.githubusercontent.com/51854340/59554056-64344100-8fa6-11e9-9589-9798b5dce0b2.jpg)

**Comment by Batalenkov** [comment]
> это страница не найдена: ошибка 404

attached a screenshot

**Comment by davide-alghi** [comment]
sorry, but I cannot detect system distribution ... anyway ... it's not important
I think this is a problem related to your web-server configuration.
try to submit the error to your sys admin or your provider support and then write feedback here


**I suggest you to remove phpInfo image for (your) security reasons**

**Comment by Batalenkov** [comment]
> sorry, but I cannot detect system distribution ... anyway ... it's not important
> I think this is a problem related to your web-server configuration.
> try to submit the error to your sys admin or your provider support and then write feedback here
> 
> **I suggest you to remove phpInfo image for (your) security reasons**

Thanks for the reply and help! Unfortunately, my vpn provider is silent (((

**Comment by davide-alghi** [comment]
have you patience
when you will have info, reply here

**Comment by mariuszkrzaczkowski** [comment]
Check the PHP versions and then in PHPINFO Check the configurations

https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

**Comment by Batalenkov** [comment]
> Check the PHP versions and then in PHPINFO Check the configurations
> 
> https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

Good morning! Now this problem remains an upcoming response file / var / cache / nginx / proxy_temp / 5/02/0000000025

**Comment by davide-alghi** [comment]
> Check the PHP versions and then in PHPINFO Check the configurations
> 
> https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

Did you check Mariusz's suggestion?

**Comment by mariuszkrzaczkowski** [comment]
first PHP version
