### ISSUE TITLE
[PL][Pytanie] Zmiana nazwy statusów

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10742]
Witam,

W wersji 5.0.0 dlaczego niektórym statusom mogę zmienić nazwy a np "Oczekuje na realizacje" już wartość nie jest edytowalna?

**Comment by mariuszkrzaczkowski** [comment]
część wartości jest zablokowana ponieważ te statusy są zakodowane w kodzie systemu i nie mogą ulec zmianie, zalecamy zmianę tłumaczenia 
https://github.com/YetiForceCompany/YetiForceCRM/blob/c8f0e684914dbf8643fb31a8a72458a3ec865a68/languages/en-US/HelpDesk.json#L71

**Comment by mrzewnicki** [comment]
ok, dzięki wielkie
