### ISSUE TITLE
[PL][Pytanie] Masowa edycja nie działa

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10751]
Witam, dlaczego może nie działać masowa edycja na wersji 5.0.0?

![image](https://user-images.githubusercontent.com/21024857/59658995-792af300-91a5-11e9-89cf-49d1d42b5dd8.png)

**Comment by bpabiszczak** [comment]
Pewnie dlatego, że jakieś inne pole jest może wymagane? W logach powinno być.

**Comment by mariuszkrzaczkowski** [comment]
Trzeba wybrać ple które ma być zmodyfikowane i potem dopiero wartość 
![image](https://user-images.githubusercontent.com/10198654/59664210-e2fcca00-91b0-11e9-8619-d9aba403a566.png)
