### ISSUE TITLE
Deleting Dataentry

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#1075]
Hello everyone,

i've discoverd a certain issue:

when i saved a dataset (eg: Organisation) and afterwards i delete it and try to create the same one again, then the CRM tells me that the organisation already exits!!?!!

This is weired. So i took a look into the MySQL Database and discovered that the organisation has not been deleted in the MYSQL-DATABASE only in the CRM.

How can i fix this?

Best regards,
Ralph

**Comment by waw555** [comment]
The same thing happens with the user profiles and groups udalyaesh profile or group sozschdaesh the same, and the system says that the profile or group already exists.

**Comment by mariuszkrzaczkowski** [comment]
Validation works fine, validation check also the record that are in the basket.
To allow you to add record should empty the trash.

**Comment by mariuszkrzaczkowski** [comment]
Improved validation https://github.com/YetiForceCompany/YetiForceCRM/issues/1176

**Comment by ralphkretzschmar** [comment]
how can i empty the trash?

**Comment by ralphkretzschmar** [comment]
thank you for the hint. do you mean on sql to empty the trash?
