### ISSUE TITLE
[bug] TimeControl editing wrong time

### ISSUE THREAD

**Issue by gerripeach** [YetiForceCompany/YetiForceCRM#10754]
# 🐞 bug report

### ⁉️ Describe the bug
When clicking on the edit button of a TimeControl Record. The Time is displayed wrong.

**To make things like config/etc simple. The bug can be reproduced both on gitdeveloper & gitstable.**
See .gif animation for more details/reproducion steps/...

https://drive.google.com/file/d/1M_aT0-Shuoe1jAludph2-SesKv7aLj9C/preview

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version

**Comment by gerripeach** [comment]
Yes. The bug exists in the dev version.
