### ISSUE TITLE
[PL][Pytanie] Informacja o odpowiedzi klienta

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10758]
Witam,

Czasami sprawy ciągną się i nie można ich od razu zamknąć, czy można ustawić jakoś zmiane statusu po odpowiedzi Klienta na nasz mail który podpina się pod zgłoszenie? Np: "czeka na odpowiedź konsultanta" (jeśli sobie  taki stworzę oczywiście)

**Comment by bpabiszczak** [comment]
Była nawet kiedyś taka opcja [ale widzę, że teraz jej nie ma]... Można to prosto zrobić w skryptach odpowiedzialnych za mapowanie maila ze zgłoszeniem [jeżeli przychodzi od klienta a status jest "oczekuje na odpowiedź" wówczas zmień status na "Do realizacji".

**Comment by mrzewnicki** [comment]
OK, dzieki za podpowiedź. To pewnie są te BindHelpDesk.php
