### ISSUE TITLE
[bug] Interface Language Displays LBL

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#10766]
Hi,

For a while now my system has been displaying "LBL" before any field and the language returned to its original value.

I tried to update the language files but the LBL still remains.

![image](https://user-images.githubusercontent.com/34719141/59749829-0c375c00-927e-11e9-99be-5982492a674f.png)

**Comment by mariuszkrzaczkowski** [comment]
The current user has a selected language that does not exist in the system.
