### ISSUE TITLE
[Question] Integrating dynamic data ?

### ISSUE THREAD

**Issue by beppe9000** [YetiForceCompany/YetiForceCRM#10770]
Is it possible to define an entity type that is dynamically loaded from a webservice ?
For example I have a list of contacts that are served as a JSON list by an API. 
What is the proper way to make that data available to yeti dynamically (without importing it in the database, since the data changes frequently) ?

What is the proper way to achieve that ?

PS: Where can I find developer documentation and examples on how to extend Yeti ?

**Comment by davide-alghi** [comment]
Hi,
a solution could be, starting from your json list, insert the contacts in YF via YetiForce REST Api.
There is no official documentation, but you can find some information here

https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST

https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+api+OR+rest+OR+Webservice+

**Comment by mariuszkrzaczkowski** [comment]
Do you want to download data from YetiForce and display somewhere on the website or the other way round - display in YetiForce from another source?

**Comment by beppe9000** [comment]
> Do you want to download data from YetiForce and display somewhere on the website or the other way round - display in YetiForce from another source?

Yes, the other way round: I have an external data source (another db/cloud api) and wanted to show every object as an entity in Yeti since that data is being changed very often and i will nee to sync it always.

Is there a PHP interface or class that i can implement? Basically the idea would be to have a customized entity with overridden field loading so that yeti-specific fields are loaded from the yeti db and the rest of the fields are loaded from the remote source.

**Comment by mariuszkrzaczkowski** [comment]
Currently, it isn't possible, it requires writing a dedicated integration.

**Comment by beppe9000** [comment]
Is there documentation on customizing yeti like this?

**Comment by mariuszkrzaczkowski** [comment]
no, this is a non-standard integration

**Comment by beppe9000** [comment]
Ok. For other code customizations such as how to work with ORM (search and CRUD), define cron jobs and others can I find docs somewhere ?

**Comment by beppe9000** [comment]
How much of [vTiger's customization documentation](https://www.vtiger.com/docs/vtiger-customization) is applicable to YetiForce? Are there dev resources to explain the internals of yeti and how to customize it?

**Comment by paula-w** [comment]
@bpabiszczak's response:

Our documentation is quite poor and needs a lot of work - donations to our project would definitely speed up the process - https://opencollective.com/YetiForceCRM

As far as Vtiger's documentation is concerned, we have no idea if anything works (most likely not), but even when we created Vtiger modules 5 years ago we didn't use their documentation (it doesn't really include anything substantial programming-wise).

**Comment by mariuszkrzaczkowski** [comment]
> PS: Where can I find developer documentation and examples on how to extend Yeti ?

We start creating documentation for the API, see https://doc.yetiforce.com/api/

**Comment by beppe9000** [comment]
Nice to have external api documented with swigger! Actually I was after overriding some backend behaviours in an upgrade-safe way. For example how to run code before saving an entity and do additional validation or things like that (eg. doing duplicate checking, custom api entrypoints).

**Comment by vovpff** [comment]
@beppe9000 for running code before or after saving you can write handler

**Comment by vovpff** [comment]
You can check sourse code for handlers examples
