### ISSUE TITLE
[bug] Manual work trigger

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#10777]
I create a manual workflow shot but the icon does not appear to be able to do it,
![Snap_2019 06 21_11h46m30s_001_](https://user-images.githubusercontent.com/29610537/59914350-800e6b80-941a-11e9-9305-3ae343dab534.jpg)

**Comment by vovpff** [comment]
Is it Workflow trigger available for your user profile?

**Comment by joelbcampos** [comment]
:) Of course @vovpff, It's very weird

**Comment by mariuszkrzaczkowski** [comment]
The error doesn't occur in the latest version https://gitdeveloper.yetiforce.com/index.php?module=Accounts&view=Detail&record=115
