### ISSUE TITLE
[Question][PL] Automatyzacja kalendarza    

### ISSUE THREAD

**Issue by espeoceka** [YetiForceCompany/YetiForceCRM#10786]
### Description

Cześć czy jest jakaś możliwość żeby automatycznie generować wydarzenia w kalendarzu poprzez automatyzacje ?
Mam prosty moduł z datą spotkania i chciałbym na podstawie tego rekordu wygenerować rekord w kalendarzu. Moduł jest powiązany z kalendarzem ale w automatyzacjach w utwórz rekord niestety nie ma takiej opcji

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/10666#issuecomment-500706258
