### ISSUE TITLE
[Question]           Contacts editing

### ISSUE THREAD

**Issue by cornutaurus** [YetiForceCompany/YetiForceCRM#10784]
Hello, I have a couple questions regarding contact.

1. I see that from Lead you can convert to Account via "ready for conversion". Could I convert Lead to Contact instead. We're working with mainly individuals.
2. Under Account, every time I add a Contact, I have to create a new Contact. It doesn't let me add Exiting Contact. I have to go to Contact and click on Member of in order to link both.
3. Could not edit Salutation, Mr. Mrs. Ms. when editing contact. I could edit first name, last name, and everything else, except for that.

Please lead me in the right direction.

Thanks

**Comment by joelbcampos** [comment]
1º You must create Mapping of fields and assign a value to a field that is the one that determines that the work can be done.
Once you have this, a field will appear to change to the module you choose.

2º Create a contact field 1: M, in this way you can directly select the contact to your account.

3º I do not understand very well what is needed.

**Comment by davide-alghi** [comment]
Hi, my replies inline ...

> Hello, I have a couple questions regarding contact.
> 
>     1. I see that from Lead you can convert to Account via "ready for conversion". Could I convert Lead to Contact instead. We're working with mainly individuals.
> 
The short answer is NO.
Alternatively you can create a **Mapping Leads to Contacts** (BE: Standard modules: Mapping) to generate a new contact with _lead detail data_. Relations are not movable.
I seem to understand you are moving to consider contacts like as customers: I suggest you don't do it.
CRMs presuppose account is at the center of information and data flow: if you move the center, maybe you may encounter problems in the future.
My suggest: individuals and companies can cohabit into the account module. It's enough to add custom fields to describe **individual entity** (and / or hide not used built-in fields). This operation has to be done both in Leads module and Accounts module. Then you need to modify Lead Conversion mapping to convert Lead into individual account (BE: Standard modules: Custom field mapping)



>     2. Under Account, every time I add a Contact, I have to create a new Contact. It doesn't let me add Exiting Contact. I have to go to Contact and click on Member of in order to link both.
> 
it is assumed that a contact belongs to a single entity: account, vendor, lead, partner and so on. If you were able to **select** a contact for an account, the same contact may be related with many accounts and this may not be correct. In you specific case, for individual, a contact could be the wife, the son, the father and so on: do you understand that it must have a single relationship with the account?


>     3. Could not edit Salutation, Mr. Mrs. Ms. when editing contact. I could edit first name, last name, and everything else, except for that.
> 
This is very strange: perhaps you have to check user profile privileges on salutation field, or, in picklist editor, check if salutation picklist values are correctly assigned to roles.

**Comment by cornutaurus** [comment]
Thank you for the help. I guess I have to modify the account to have first and last name
Also with the salutation, yes I could edit when go to full edit view.
