### ISSUE TITLE
[PL][Pytanie] Opcja ponownego otwarcia zgłoszenia po otrzymaniu odpowiedzi nie działa

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10792]
Witam,

Na wersji 5.0.0 - complete nie działa mi opcja 
![image](https://user-images.githubusercontent.com/21024857/60010564-52266280-9678-11e9-96cc-ddb14eb69bcd.png)

Tworzy nowe zgłoszenia zamiast otwierać stare. Mógłbym prosić o podpowiedź czego to może być wina?

**Comment by mariuszkrzaczkowski** [comment]
Sprawdź czy to działa na wersji 5.1 i wersji deweloperskiej

**Comment by mrzewnicki** [comment]
Wszystko działa na Git Stable, na Developer nie chciała się zeskanować skrzynka nie wiem czemu ale jak wskazałem to ręcznie to zadziałało. 

U mnie natomiast wygląda to tak że scanner wiąże wiadomość ze zgłoszeniem ale nie zmienia statusu. Kiedy ja sam wejde w maila to tworzy się zgłoszenie i zmienia się status. Tak jakby w skrypcie do crona czegoś brakowało może? Nie wiem. Nie mam z tego żadnego błędu, ani w consoli ani w logach.

**Comment by bpabiszczak** [comment]
skoro działa na 5.1 to należy się uaktualnić z 5.0 do 5.1 :]

**Comment by mrzewnicki** [comment]
Mam 5.1 teraz.

**Comment by bpabiszczak** [comment]
Polecam wykupienie wsparcia technicznego. Ewentualnie jest też opcja zbierania "godzin wsparcia" za polecenia.

**Comment by mrzewnicki** [comment]
Wszystko działa... tylko zamiast w `/var/www/html/YetiForce/config/Components/Mail.php` w parametrze $HELPDESK_OPENTICKET_STATUS należy podać poprawna nazwe statusu, nie "Wait for response" tylko "Wait For Response"...
