### ISSUE TITLE
Problem with SSL

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#10793]
Hi, I am using version 4.4. I just added SSL to my domain name. After that sometime the crm is opening and sometimes it is not. 

**Error Message: The site cannot be reached.**

 I checked config.inc.php and it site url has been automatically transferred from http to https. Is there anything that needs to change to solve this problem. Please help...

**Comment by mrzewnicki** [comment]
That's all message you have? nothing more?

**Comment by mrzewnicki** [comment]
Check also to be sure when it work, when you're using ssl or not. If does on ssl then redirect connection to ssl in default apache file.  if not you should also check does the paths to certs are correct, does ssl is enable in UFW (generally firewall) settings if you are using

**Comment by mrzewnicki** [comment]
Example of my config file:
`  <IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerAdmin [admin@mail.pl] <-admin mail here
                DocumentRoot /var/www/html/[your_root_dir]
                ServerName [server_name]
                ServerAlias [alias server]

                ErrorLog /var/log/apache2/some_path.pl-error_log <- paths to logs
                CustomLog /var/log/apache2/ some_path.pl-access_log common <- paths to logs

                SSLEngine on 

                SSLCertificateFile /etc/ssl/certs/ some_path /file.crt 
                SSLCertificateKeyFile /etc/ssl/certs/ some_path /file.key

                SSLCertificateChainFile /etc/ssl/certs/ some_path /ca-bundle.crt

                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                        SSLOptions +StdEnvVars
                </FilesMatch>

                <Directory /usr/lib/cgi-bin>
                        SSLOptions +StdEnvVars
                </Directory>

                <Directory /var/www/html/[root_dir_file]>
                        Options FollowSymLinks
                        AllowOverride All
                </Directory>

        </VirtualHost>
</IfModule>`
