### ISSUE TITLE
Comments/History - modified date format

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#108]
Hi,
in modules Comments and History the modified date is displayed as the date difference (4 hours ago). My users feedback is hat this is Ok when the change was made a couple of hours or day ago. but if the change was made for example 23 days ago they need a calendar as a reference and would prefer to have a timestamp displayed i.e "23.05.2014 15:30h".

I already modied the tpl files in our installation but this is something to consider as a improvement for future versions

**Comment by KatarzynaUlichnowska** [comment]
Hello,
when you hover the cursor on the number of days, e.g. 23 days ago, the system will show you the precise date. We think that this solution is more useful.

**Comment by setras** [comment]
I think it depends on how you're using the system and what the personal preference is. My users hate it and would like to have the opposite behaviour.
As said it is a easy adjustment but maybe it would be preferencial in future to give the user the choice but adding a configuration variable.
