### ISSUE TITLE
"Modifying record"  condition is not working in workflows 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10809]
# 🐞 bug report
Hello
"Modifying record"  condition is not working in workflows . I have checked many times but no use. 

In workflows:
**first workflow   condition**:   Execution schedule (defined time intervals):  execution frequency is Hourly.

This workflow is used for auto updated  hour filed for every one hour.

**second workflow condition** : Modifying record:
Choose filter conditions  is  Hour = 1 then updated status is "In progress".

In here first workflow is auto updating hour field each hour but second workflow is not updating status flied.Please check below videos for your reference.   

![Modifying record new](https://user-images.githubusercontent.com/47585969/60086135-e62e2200-977d-11e9-9e7d-aae52249483d.gif)
![Modifying record new after one hour](https://user-images.githubusercontent.com/47585969/60086154-ededc680-977d-11e9-873b-f90047407a7e.gif)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| [ver. 5.1.105]
| Web server (name and version)|	www (apache)	|
| PHP  |		7.1.x, 7.2.x, 7.3.x (dev)	|
| Browser (name and version)  | 	Google chrome 	|
| Operating System (name and version)  | 	Windows 7	|
| Database (name and version) | 	mysql	|

**Comment by davide-alghi** [comment]
Hi,
it's correct. It's not a bug.

"Modifying record" means "When an user changes at least a field value and saves record".

Your **Update fields** workflow changes Ticket field **Status** to **In Progress** if
1) **hours** field is equal to 1
2) an **user** edits the record
3) user **changes** a field value (NB; saving without changing at least one field value does not call workflow)
4) record is saved => workflow changes **status** to **In Progress**

**Comment by guide5232** [comment]
In the above video the hours fields values updated from 0 to 1 that the record has  saved by system and modify time also changed.whenever we save or modify the record that time only modify field will be changed.Other wise modify time will not change.Based on the modify time field we can say that record is saved.but second workflow not fired(status to In Progress)
