### ISSUE TITLE
[bug]  [PL] SLA POLICY - Dodaj rekord Call to undefined method Settings_SlaPolicy_Module_Model::getModules()

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#10815]
# 🐞 bug report

### 🔥 How to trigger the error

1. Go to https://gitdeveloper.yetiforce.com/index.php?module=SlaPolicy&parent=Settings&view=Edit 
2. Click on 'Dodaj rekord'
3. See error  Call to undefined method Settings_SlaPolicy_Module_Model::getModules()

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| ver. 5.1.108
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by bpabiszczak** [comment]
bo to jeszcze nie skończone jest...
