### ISSUE TITLE
[PL][Pytanie] Uruchomienia powiązań YetiForce - Roundcube

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10819]
Witam,

Na waszej wersji testowej jest coś takiego:
![image](https://user-images.githubusercontent.com/21024857/60167566-a14cce80-9803-11e9-938b-026d337d88c7.png)

Chodzi mi o te przyciski, Kontrachenci, Kontakty itp itp. Bardzo fajnie podpowiada maila które są w kontaktach. Da się to uruchomić jakoś?

Mam wypisane moduły w Configu: /my_path/config/Components/Mail.php
![image](https://user-images.githubusercontent.com/21024857/60169441-f807d780-9806-11e9-8e8d-45ac6238b3f5.png)

**Comment by bpabiszczak** [comment]
Banalnie prosto:

1. Dodajemy do systemu kontakty, firmy, dostawców itd. z adresami mailowymi
2. Włączamy CRON-a

i tyle :]

**Comment by bpabiszczak** [comment]
Tylko nie wiem co u Ciebie nie jest ok [nie widać przycisków?]. Maile podpowiada gdy jest włączony CRON i do modułów tj. kontakty, kontrahencie, dostawcy dodamy rekordy z adresami mailowymi.

**Comment by mrzewnicki** [comment]
Ja w skanerze mam: Tworzenie wiadomości email,zgłoszenia, powiązania z kontaktem oraz ze zgłoszeniem. Więc to pewnie przez to

![image](https://user-images.githubusercontent.com/21024857/60178235-4b842080-981b-11e9-9acf-163b7d3d7f1c.png)

**Comment by bpabiszczak** [comment]
a co ma skaner poczty do zrzutu ekranu w pierwszym poście?

**Comment by mrzewnicki** [comment]
myslałem że tam muszą być powiązania do wymienionych. Czyli źle zrozumiałem

**Comment by mrzewnicki** [comment]
No to w CRONIE za to odpowiada pewnie "Aktualizacja książki adresowej" tak?

**Comment by bpabiszczak** [comment]
za podpowiadanie adresów tak, a guziki pokazują się zgodnie z uprawnieniami do modułu z profilu.

**Comment by mrzewnicki** [comment]
Na koncie Administratora mam zaznaczone wszystkie moduły. Cron jest uruchomiony. I kiedy odpisuje na Maila to niestety nie widze żadnych ikonek modułów i nie podpowiada mi maili ale w miare pisania miga w prawym dolnym rogu komunikat "Wyszukiwanie" jakby próbował.

**Comment by mrzewnicki** [comment]
Jeżeli jest to jakaś wskazówka na wersji próbnej jest w modułach na mailu Contacts a u mnie HelpDesk
![image](https://user-images.githubusercontent.com/21024857/60181515-a705dc80-9822-11e9-8464-fc0b1453f633.png)

**Comment by mrzewnicki** [comment]
Pracuje na wersji, 5.0.0 czy to było wprowadzone od 5.1?

**Comment by bpabiszczak** [comment]
To było wprowadzone w wersji 3.x [albo i wcześniej], zalecamy aktualizację do najnowszej wersji razem z service pack.

**Comment by mrzewnicki** [comment]
czy msui być włączony plugin do roundcube'a czy zawiera się wszystko w pluginie "yetiforce"?
