### ISSUE TITLE
Price based on product quantity

### ISSUE THREAD

**Issue by estudioalfa** [YetiForceCompany/YetiForceCRM#10817]
Hello,

Is it possible to establish a relationship between the product quantity and the unit price? So if we receive an order of 1000 units the price is lower than for an order of 200 units.

It needs to be able to establish those relationship individually for each product.

Thanks in advance!

Best Regards,
Roberto

**Comment by NeeleshmEBA** [comment]
I think there is no such relation. We might need to customize according to the quantity the price has to get changed.

Regards,
Neelesh.

**Comment by bpabiszczak** [comment]
At the moment, there is no such functionality.
