### ISSUE TITLE
[Feature] Mail-Sender Additional headers (With Solution)

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#10814]
## 🚀 feature request
Mail-Sender Additional headers 
### Describe the solution you'd like

Our CRM has a newsletter sender option which is not using Roundcube library but php mailer,
By many providers (Apple, Google, Outlook) it is required to have **List-Unsubscribe Header** to avoid going your email into spam.

In addition in Canada we have Canada’s Anti-Spam Legislation (CASL) act which is requiring all mass senders to provide an option to unsubscribe.

Besides List-Unsubscribe headers which is great to have are:
**Organization;
X-Sender;
User-Agent;**
this headers secure the messages from going to SPAM

Not Needed headers are:
**X-Mailer: YetiForceCRM Mailer;**

In roundcube we can use the additional_message_headers plugin, however it is not a solution for mass mailing through the CRM mechanism.

### Solution
add this to the Mailer.php
```
$this->mailer->AddCustomHeader("List-Unsubscribe: <mailto:EMAIL>, <unsubscribe script>");
$this->mailer->AddCustomHeader("Organization: Organization Name");
$this->mailer->AddCustomHeader("X-Sender: Sender Email");
```

### Describe alternatives you've considered

Exporting emails and using other software such as mail chimp.

### Additional context

I cant call the implemented features compliant with a marketing policies of different email providers.

**Comment by z0lo13** [comment]
@mariuszkrzaczkowski 
Great It was added!
Add the feature to the list please

**Comment by mariuszkrzaczkowski** [comment]
> Add the feature to the list please

what do you mean?
