### ISSUE TITLE
PDF template image not being saved

### ISSUE THREAD

**Issue by GenCr** [YetiForceCompany/YetiForceCRM#10824]
Hi,

I'm trying to upload a static image to a pdf template in the header. I can add the image (external or internal path) and I see it displayed in the "Edit header" section.

However, after I save the template and reopen it, the image does not seem to get saved - only the text remains.

I've added (both internal and external) URLs in the $PURIFIER_ALLOWED_DOMAINS section in Security.php.

The images still don't get saved.

I'm on YetiForce 5.1.0.

Any ideas?
Thanks.

**Comment by GenCr** [comment]
Bump

**Comment by GenCr** [comment]
Could anyone please advise on how to fix this or troubleshoot futher?

Thanks.

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version

**Comment by GenCr** [comment]
Not quite sure what you mean. How can I check that?

**Comment by maeglin4** [comment]
https://gitdeveloper.yetiforce.com/
