### ISSUE TITLE
[Question] - System condition type workflow           

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#10826]
Hello  all,

   i have seen that there is a System condition in Workflows.
   I would like more details about it : 
  - How often is it running?
  - What is triggering it?

I have seen some answers around here, but nothing solid, like : 
   - This type of condition starts every .... based on your cron settings (or else) .... 

  Some more detalied explanations would be good because, like in #10071 said, System name is very vague. 

    Thank you !

**Comment by davide-alghi** [comment]
Hi liviubbo,
you are right: **System** term is non-explicative.
**System** means that the workflow is called by the module with which the workflow is associated.

If you select **System** as "**Specify when to execute this workflow**" value, the workflow is not called via CRON: it's called by module itself, if and only if, into module core code, a specific handler is implemented.

It's not easy to explain and I hope I was clear :)

I just proposed to YF-team a new label for "System": "On the occurrence of an event defined in the module itself", but there may be a better label.

**Comment by liviubbo** [comment]
So, basically, if i didnt made any changes to a module, it will not work, right ? 
If i dindt implemented a specific handler, right ?

**Comment by davide-alghi** [comment]
Yes Liviu, you 're right.
That option is to "open a door" for customizing workflow execution: you need to develop it.

**Comment by liviubbo** [comment]
Thank you for the quick answer!
Have a great day!
