### ISSUE TITLE
[bug] Error updating permissions

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#10822]
I have the cron task configured and it works correctly but for 5 days the permissions updater does not work.
I need urgent help.****

**Comment by joelbcampos** [comment]
![Snap_2019 06 26_14h09m41s_002_](https://user-images.githubusercontent.com/29610537/60178562-204e0100-981c-11e9-8498-dc501bd9614e.jpg)

**Comment by z0lo13** [comment]
I actually saw this couple times on my system but i guess it is due to amount of records i have ~700k it goes away after cron tries it one more time

**Comment by mariuszkrzaczkowski** [comment]
turn on the logs and check what the error is

**Comment by noelhunter** [comment]
I had an error where a module name string seemed to be empty:

TypeError: Argument 1 passed to App\Module::isModuleActive() must be of the type string, null given, called in/app/Privilege.php on line 88 and defined in app/Module.php:95

I added a check to make sure module name was defined in app/Privilege.php line 88

 if(strlen($moduleName) > 0) {

before the line:
                if (!Module::isModuleActive($moduleName)) {

Probably a better way, but it was a quick fix to get the cron to complete.
