### ISSUE TITLE
[bug] Error on custom module - related module

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#10827]
Hello all,

    I have created a custom module that uses a field from employees module (related module field type).
   When i try to search inside the custom module for an entry related to employees, i get an error.

    
![error](https://user-images.githubusercontent.com/42461923/60246420-f26dc880-98be-11e9-8e0f-cc14c6bd6656.gif)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.1.0 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by liviubbo** [comment]
I have figured out an alternative way to fix it. A childish way.
I have created a new field with the same relation, filled it up with the appropiate informations, and after, i have deleted the field that was causing the issue.

**Comment by konadrian** [comment]
I can't duplicate this error on https://gitdeveloper.yetiforce.com/ however, we advise to use "_" as word separator
