### ISSUE TITLE
[PL][Pytanie]Błąd w pluginie yetiforce.php Roundcube

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10829]
Witam, 
Na wersji 5.0.0 . 
Błąd pojawia się za każdym razem gdy przy odpowiedzi na jakiegoś maila albo pisząc nowego, uzupełniam pole adresu email. I faktycznie mam problem z niedziałającymi podpowiedziami maili.

Pojawia mi się błąd w cache/logs/errors o następującej treści:

[27-Jun-2019 11:33:00 Europe/Warsaw] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/YetiForce/public_html/modules/OSSMail/roundcube/plugins/yetiforce/yetiforce.php on line 45 

![image](https://user-images.githubusercontent.com/21024857/60256331-99f3f680-98d1-11e9-9abb-aea1ea70fe8f.png)

**Comment by mrzewnicki** [comment]
Zamieniłem ją na `foreach (\App\Config::component('Mail', 'RC_COMPOSE_ADDRESS_MODULES') as $moduleName) {...` i pojaawiły sie w ogóle przyciski do wyboru z modułów ale dalej nie podpowiada maili

**Comment by mrzewnicki** [comment]
Cron.log mnie informuje o takim błędzie:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20170718/mysqli (/usr/lib/php/20170718/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/mysqli.so (/usr/lib/php/20170718/mysqli.so: undefined symbol: mysqlnd_global_stats)) in Unknown on line 0`

Więc to pewnie przez to mi nie podpowiada..

**Comment by bpabiszczak** [comment]
skoro przez to, to nie ma to nic wspólnego z CRM :P

**Comment by mrzewnicki** [comment]
W pluginie yetiforce.php był błąd jak napisałem wyżej. Nie mam pojęcia dlaczego przy ściąganiu samej biblioteki kod był poprawny a przy aktualizacji bibliotek nie zaciągał pliku z poprawnym kodem. Z CRM nie jest związane podpowiadanie adresów. Tu się zgodzę w pełni, kwestia ustawień mojego serwera nad czym właśnie pracuje.
