### ISSUE TITLE
[Feature]    Multiple roles to a single user

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#10837]
### Describe the solution you'd like
If a user logs in and has more than one role, he should be given the option to determine which role he wants to use.
In this way, someone who has 2 completely different roles in an organization can still have the option to perform their tasks via 1 single user account.

![login](https://user-images.githubusercontent.com/16014524/60330981-e7389c80-9993-11e9-844a-068f66ed6d41.png)

### Is your feature request related to a problem? Please describe.
To achieve the same result, it is necessary to create two different accounts with two different e-mail addresses for 1 person. This causes confusion.

### Describe alternatives you've considered
Creating two user accounts for 1 person.

### Additional context
/

**Comment by paula-w** [comment]
You can create 2 users with different roles and permissions and allow them to switch to each others’ accounts. Check out this mechanism: https://gitdeveloper.yetiforce.com/index.php?module=Users&view=SwitchUsers&parent=Settings&block=4&fieldid=17
