### ISSUE TITLE
[Feature]   Transfer Ownership to a role.

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#10836]
### Describe the solution you'd like
Assign Contacts to Roles when transfering ownership.
Currently it is only possible to assign records to users or groups.
If you assign a record to a role, the parent roles must of course also have access.

![roles](https://user-images.githubusercontent.com/16014524/60330236-4c8b8e00-9992-11e9-8f2b-1ade919e5821.png)

### Is your feature request related to a problem? Please describe.
To achieve the same result as described above, you must assign a record to a group, with the relevant role and all parent roles in that group.
This is a very cumbersome process.

### Describe alternatives you've considered
/

**Comment by paula-w** [comment]
Right now you can’t assign records to roles, it’s only possible to assign them to users and groups. This functionality might be developed in the future, if the community needs it urgently it can be crowdfunded on Open Collective and then it will become out priority: https://opencollective.com/yetiforcecrm
