### ISSUE TITLE
[PL][Question] Konwersja walut

### ISSUE THREAD

**Issue by kwypych** [YetiForceCompany/YetiForceCRM#10838]
### Description
1. Waluta domyślna = euro
2. Druga waluta = PLN
3. Konfiguracja systemu/waluty kurs wymiany euro = 1, PLN = 4.
4. Tworzę produkt_1, cena = 100 euro.
5. Tworzę fakturę sprzedaży, wybieram produkt_1, automatycznie importowana jest cena 100 euro, zmieniam walutę na PLN, system prosi o wpisanie kursu waluty ręcznie. Nie przelicza według kursu ustawionego w punkcie 3. Dlaczego pomimo ustawienia wcześniej kursu waluty, nie ma on automatycznego zastosowania przy zmianie waluty?
6. Tworzę fakturę sprzedaży, wybieram produkt_1, automatycznie importowana jest cena 100 euro, zmieniam walutę na PLN, system prosi o wpisanie kursu waluty ręcznie. Wpisuję kurs = 4 i system przelicza przez dzielenie kwoty przez kurs zamiast pomnożenie kwoty przez kurs. Gdzie można zmienić to w kodzie, aby kwota była mnożona przez kurs?

**Comment by bpabiszczak** [comment]
Bo tam się wpisuje przelicznik... a więc 1 euro to 0.25 w PLN. Po drugie najlepiej włączyć cron i pobierać przelicznik waluty z NBP automatycznie!
