### ISSUE TITLE
YetiForce and OpenCollective 🆕

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#10839]
![banner_help](https://user-images.githubusercontent.com/13310141/60346199-f121c600-99ba-11e9-8a92-e59c95b75230.png)

We develop software that everyone can use without any limitations or hidden fees. YetiForce was created almost five years ago and since then we have been developing it on a daily basis for our customers and the community. The community is growing daily and currently there are 700 people who watch the project and at least several dozen who test the system and open new issues (over 5.500 issues in 5 years).
 
Together with the release of version 5.0 we started collecting information about installations. Over a period of **4 months** (since February the 12th) we registered over **10.000 installations**, including 2.000 companies and individuals with correct registrations. The three most popular countries are the United States, Poland and Brazil. Currently, YetiForce is used in over **110 countries** around the world and there have been over 30.000 installations since we created the project. Just like we promised at the beginning - the system remains free and we don’t plan to introduce a second, paid version like the majority of our competitors did. 
 
We want to provide the highest quality support here on GitHub, and we don’t want you to have to wait for days or even weeks for us to solve an issue, that’s why the best solution was to create a place where the open source community can fund better tech support and development of the project. Especially that some of you expressed the interest in influencing the **direction of the development and the future of YetiForce**. 
 
One hour of our support costs $40 and solving a single issue sometimes takes a few hours. For many people and companies that just began working with the system it is a significant amount, therefore, the best way out of this is to collect money for a **designated programmer** who will take care of the GitHub issues. If every company that uses the system supported the project with $5 a month, the community would have a few designated full-time programmers at its disposal. Collecting funds via OpenCollective isn’t free of charge as the organisation takes 5-10% of the collected amount, so we also take it into consideration when estimating the goals, budget and tiers. 

For everyone who would like to support YetiForce we prepared our [Collective](https://opencollective.com/YetiForceCRM) where you can donate to our project and help us develop new versions of the system. There is also a new **Sponsor button** at the top of our GitHub repository page.
@johnMaverick and @nkzach have already chipped in (thanks!❤). Who would like to be next?

We realize that the cost of 1 hour of our support might seem expensive, however, the developer that we’re going to assign to GitHub community support is _NOT_ going to be a random freelancer who doesn’t know anything about YetiForce. Quite the opposite - we’ll assign an expert with an extensive knowledge about our system. 

Thanks to OpenCollective you can also collect money towards 3 functionalities that the community has been requesting for a while, namely **Webforms**, **Reports**, and **PBX**. We set up 3 tiers for this purpose; all money collected from these tiers will be spent solely on developing these functionalities.

We hope you visit our Collective, if you’d like to give YetiForce a “gratitude tip” but none of the tiers we suggested sounds good to you, you can use the **Custom Donation** option at the bottom of the list, where you decide how much you want to donate.

**Thanks to everyone who has already donated and everyone who is going to do so.** 

Let us know if you have any questions about the collective, our tiers, or anything else.

**Comment by bpabiszczak** [comment]
THANK YOU

> Just a quick note to let you know that Dimitris Andavoglou is now a backer of YetiForceCRM.

**Comment by z0lo13** [comment]
@paula-w is there any GUI ideas fro reports module?
