### ISSUE TITLE
[bug] Change Assigned To to a user who edits a record Is not Working

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#10840]
# 🐞 bug report

### ⁉️ Describe the bug

Yetiforce has a feature "Change Assigned To to a user who edits a record"
which when enabled suppose to change "assigned_to" field to the user who just made the edit.
However, it is not working and i was not able to find a function to do that.

### 🔥 How to trigger the error

1. Go to https://gitdeveloper.yetiforce.com/index.php?module=MarketingProcesses&view=Index&parent=Settings&block=6&fieldid=83
2. Click on 'Change Assigned To to a user who edits a record'
3. Go to Leads and Open Any Lead which is **not assigned** to the user you are currently logged in 
4. Make any edit
5. Assigned to left unchanged

### 👎 Actual Behavior
"assigned_to" field not changing after a user edit the record. (Option 'Change Assigned To to a user who edits a record' Enabled)

### 👍 Expected Behavior

"assigned_to" field changing after a user edit the record. (Option 'Change Assigned To to a user who edits a record' Enabled)

### 📷 Screenshot of configuration

Gitdeveloper

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Gitdeveloper

### 🌍  Your Environment 

Gitdeveloper

### ❓ Additional context
Thats actually a great feature but only if it was working

**Comment by davide-alghi** [comment]
Hi z0lo,
I investigated about that option and I didn't find any use of that variable. It seems that the "Change Assigned To to a user who edits a record" option in marketing process is not used :confused:

It seems.

**Comment by z0lo13** [comment]
> 
> 
> Hi z0lo,
> I investigated about that option and I didn't find any use of that variable. It seems that the "Change Assigned To to a user who edits a record" option in marketing process is not used 😕
> 
> It seems.

it is just a checkbox which do nothing basically.

**Comment by paula-w** [comment]
When you check this option it won’t automatically change the owner of a record. When you convert a lead to an account it will only suggest the user who made the conversion to be the owner of the record. 

For example, if user A is the owner of the lead, but user B converts the lead, and the option you’re asking about is enable, the pop up window will suggest user B to be the owner of the account.

**Comment by davide-alghi** [comment]
Hi Paula,
you are right for **CONVERSION: Change Assigned To**: it works fine.
We are speaking about **LEADS: Change Assigned To to a user who edits a record**: it seems to be not used. If you tick the option and an user, who has got the role with privileges to change owner, **modify** a lead, owner doesn't change.

**Comment by paula-w** [comment]
Hi Davide, 
sorry, my bad! we were looking at the "leads" tab, not the "conversion" tab. Thanks for the clarification, we'll look into that again.

**Comment by davide-alghi** [comment]
Paula,
please don't worry. We all have so many things to do and sometimes something escapes us.
:thumbsup:

**Comment by z0lo13** [comment]
`<?php

class ChangeOwner
{
    /**
     * Update Assigned Owner
     *
     * @param \Vtiger_Record_Model $recordModel
     * @throws \yii\db\Exception
     */
    public static function AssignedChange(Vtiger_Record_Model $recordModel)
    {
        \App\Log::trace('Entering AssignedChange');
        
        $userModel = App\User::getCurrentUserModel();
		$currentUserId = $userModel->getId();
        $leadId = $recordModel->getId();
		
        $sql = "UPDATE  vtiger_crmentity SET smownerid='".$currentUserId."'  WHERE crmid='".$leadId."';";
				
		$db = \App\Db::getInstance()->createCommand($sql)->execute();
		
		\App\Log::trace('AssignedChange end');
    }
}`

**Comment by davide-alghi** [comment]
please z0lo enclose code between triple-single-quote

**Comment by z0lo13** [comment]
@davide-alghi 
thats the class i added to my system to have it work as needed.

**Comment by konadrian** [comment]
This option was deleted from crm
