### ISSUE TITLE
Install Portal 2           

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#10844]
Hello friends

I've tried to install the yetiportal2 but was unsuccessfull.

if I got my yeti at crm.domain.com, I'm trying to put it in crm.domain.com/portal

I'm using yeti in the folder public_html

I did copy files to the directory crm.domain.com/portal
set all permissions and ownerwhip
did composer install
But nothing, does not work...

Any help installing it from zero?

Thank you in advance!!!

**Comment by waran70** [comment]
Looks like not ready yet. I looking forward to get it good, as this is pretty crucial part or CRM (Customer Relationship Management). Fingers crossed

**Comment by paula-w** [comment]
Portal 2 will be released together with CRM version 5.2, most likely at the end of the month.

**Comment by santyabreu** [comment]
@paula-w seems you love to close issues. 

Please Keep this open until 5.2 is released and finally Portal2 is released. It will help you not to forget there is a item unsolved. Many administrators are waiting for this promised functionality. Thank you.!
