### ISSUE TITLE
YetiForce 5.1.0 Progres % not working 

### ISSUE THREAD

**Issue by buscofen89** [YetiForceCompany/YetiForceCRM#10852]
Hello all, im new here and i need a little j\help if is possible.
I use YetiForce 5.1.0, and i have created a Project, on this project i have created 2 mile Milesones, in one milestone i have created 6 Task, 4 task have are complited and 2 not, now my problem is, why the Progres % is not calculate ? On the project i have 0% Progress. 
Please help me if is possible. 
Thank You

**Comment by arek1-618** [comment]
Hello,
Progress on projects is calculated by cron.
First, make sure that the cron works correctly.
Check if the "LBL_BATCH_METHODS" task is active.
