### ISSUE TITLE
[PL][Pytanie] Liczenie czasu w CRM

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10869]
WItam,

Chciałbym zapytać o kilka pól w Zgłoszeniach:
**Czas zamknięcia** - czy po ponownym otworzeniu zgłoszenia czas jest sumowany czy liczony osobno?
**Czas realizacji** - Jak dokładnie to pole liczy ten czas? Po zmianach statusów?
**Łączny czas** - Jak dokładnie to pole liczy ten czas? Co to jest za czas?
**Czas zgłoszenia** - Jak dokładnie to pole liczy ten czas? Co to jest za czas?

Dziękuje za informacje.

**Comment by bpabiszczak** [comment]
Mówimy tutaj o nowych funkcjonalnościach, które jeszcze nie zostały opublikowane... 
- Łączny czas - liczy się z czasu pracy powiązanego z rekordem
- pozostałe 3 pola, liczą się w zależności od ustawienia na słowniku [można w nim określać kiedy czas jest obliczany], po publikacji wersji proponuje testować lub poczekać aż dodamy informacje do bazy wiedzy.
