### ISSUE TITLE
[bug] Здравствуйет, уважаемые разработчики. Написал Вам на facebook о одной проблеме: пригласили сюда. Проблема следующая - версии выше 4 при установке вызывают системную ошибку и белый экран. дальнейшая установка и апдейт становятся невозможны. 

### ISSUE THREAD

**Issue by tv-igor** [YetiForceCompany/YetiForceCRM#10878]
# 🐞 bug report

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs

**Comment by tv-igor** [comment]
YetiForce 4 or up
Web server (name and version) Apache  2.4.25 
Browser (name and version) ALL
Debian/Ubuntu/CentOS/suse
Database - MySQL (MarinaDB) 10.1.38 |  
Независимо от версии появляется белый экран и больше ничего не происходит.

**Comment by rskrzypczak** [comment]
check this: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements
and your PHP version

**Comment by vovpff** [comment]
Версия php важна!!! Белый экран означает, что есть ошибки и страница не отображается. Можете в конфигах включить отображение ошибок и сразу увидите что идет не так.

**Comment by rskrzypczak** [comment]
no response, I close
