### ISSUE TITLE
[PL][Pytanie] Edytowalne pole w Mailach Firmowych

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10875]
Witam,

Czy jest możliwość dodanie edytowalnego pola w Mailach firmowych? Np Status? Chce by użytkownik mógł zmieniać tylko ten jedno pole a nie treść maila.

Dziękuje.

**Comment by bpabiszczak** [comment]
Wszystko można :] Najlepiej zrobić to oddzielną akcją, przy czym dobrze, aby nadal to bazowało na uprawnieniach z profilu.

**Comment by mrzewnicki** [comment]
😄, w profilach mam wszędzie uprawnienia zapis, ale pól w Szczegółach edytować nie mogę. Mail firmowy jest zablokowany do edycji?

**Comment by bpabiszczak** [comment]
1. Pytałeś, czy można coś zrobić a nie jak :)
2. Jeżeli w profilu może edytować wszystko to będzie mógł edytować wszystko [wyjątkiem są funkcjonalności, które my celowo z jakiegoś powodu zablokowaliśmy i maile firmowe mogą być zablokowane do edycji pomimo, że z uprawnień wynika coś innego]. 
3. Jeżeli ktoś coś edytuje, to zawsze musi mieć do edycji również pola wymagane [a więc nie da się zrobić tak, aby mógł edytować jedno pole, zawsze będzie ich kilka]. Aby móc edytować tylko jedno pole, musi być zrobiona niezależna akcja [np. przycisk], który daje możliwość edycji statusu.

**Comment by mrzewnicki** [comment]
OK, rozumiem. Dziękuje
