### ISSUE TITLE
[bug] [PL] Problem z dodaniem urlopu do kalendarza

### ISSUE THREAD

**Issue by kwypych** [YetiForceCompany/YetiForceCRM#10871]
# 🐞 bug report

### ⁉️ Describe the bug

W menu Firma -> Czas Pracy chcę dodać nowy rekord. Wybieram rodzaj 'Urlop', ustawiam datę zakończenia tydzień po dacie rozpoczęcia. Po naciśnięciu przycisku zatwierdzającego pojawia się komunikat "Czas pracy nie powinien być dłuższy niż 24 h", a sam urlop nie zostaje dodany do kalendarza. Błąd ten występuje również w wersji testowej https://gitdeveloper.yetiforce.com/index.php
### 🔥 How to trigger the error

1. Idź do Firma->Czas Pracy
2. Kliknij "Dodaj Rekord"
3. W polu "Rodzaj" wybierz "Urlop". Datę zakończenia ustaw na tydzień później, niż data rozpoczęcia.
4. Kliknij przycisk zatwierdzający

### 👎 Actual Behavior

Wyświetlenie komunikatu "Czas pracy nie powinien być dłuższy niż 24 h" i nie dodanie rekordu do kalendarza
### 👍 Expected Behavior

Dodanie rekordu urlopu do kalendarza

### 📷 Screenshot of configuration

![Yetiforce_bug](https://user-images.githubusercontent.com/33757799/60518466-dfedf780-9ce1-11e9-9774-e5bd4be462bd.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by bpabiszczak** [comment]
Na chwilę obecną, system celowo blokuje urlopy powyżej 1 dnia roboczego, obecnie każdy dzień dodaje się indywidualnie, w niedalekiej przyszłości będzie mechanizm, który pozwoli na dodawanie urlopu na wiele dni. W teorii można sobie samemu zdjąć tą blokadę, jednakże to wymaga "rozwiązania" wielu innych problemów z tym powiązanych.

**Comment by damian123526** [comment]
Czy problem z tą funkcjonalnością został rozwiązany?
