### ISSUE TITLE
i need to show my lead list on yeti crm []

### ISSUE THREAD

**Issue by islamnasar** [YetiForceCompany/YetiForceCRM#10883]
<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

Oh hi there! 😄
i cant show lead list i had add to yeti crm on leads module 
but i can see other modules records list 
is there a solution  

thanks

**Comment by rskrzypczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs
