### ISSUE TITLE
[bug] Open Street Map wont work in canada

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#10882]
hello, im am trying to configure open street map, i tried with opencage geocoder and google geocoder and none of them works in canada.

After configurating the api in yetiforce adress finder page, do i need to edit system/config files or something ?????

Expected Behavior
make routes

How to trigger the error

1. Go to 'leads' , 'partners', 'contacts' or 'vendors'...
2. Click on 'show on map'
3. search 2 addresses and set route
4. Infinite Loading

Configuration problems

Security errors:
public_html: Off | -
.htaccess: Off | -
session.use_strict_mode: Off | Off
disable_functions: exec,passthru,shell_exec,system | -
Header: server: Apache | -
Server stability errors:
protocolVersion: 2.0 | -
output_buffering: |
auto_detect_line_endings: Off | Off
Server database errors:
innodb_lock_wait_timeout: 50 | -
character_set_server: latin1 | -
Server performance errors:
opcache.interned_strings_buffer: 8 | 8
opcache.save_comments: 1 | 1
opcache.file_update_protection: 2 | 2
realpath_cache_ttl: 120 | 120
mysqlnd.collect_statistics: On | On

Library errors:
apcu
imagick
PHP/Apache/Nginx/Browser/CRM Logs
Please include a part of logs which describes when the error occurred. The more info you provide, the quicker we will be able to solve your problem. Description how to enable logs can be found here: https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging Additionally, include a screenshot of your browser’s console (e.g. press F12 in Google Chrome). ex. cache/logs/phpError.log, cache/logs/system.log

Your Environment
Describe the environment
Environment	Version / Name
YetiForce	5.1.0
Web server	Apache
PHP	7.1.30
Browser	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
Operating System	Linux odedi56318.mywhc.ca 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64
Database	mysql | 5.5.5-10.2.25-MariaDB | mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
Please check on your issue from time to time, in case we have questions or need some extra information.

**Comment by maeglin4** [comment]
its working in Europe...
![europe](https://user-images.githubusercontent.com/45770116/60602453-c8664b80-9d81-11e9-9856-1de515c2a0ec.PNG)

But NOT working in North America, Canada
![yeti openstreetmap1](https://user-images.githubusercontent.com/45770116/60602714-56dacd00-9d82-11e9-961f-0cb596a42487.gif)

**Comment by maeglin4** [comment]
I specified  CA for Canada in the config file : AddressFinder
![addressfinder](https://user-images.githubusercontent.com/45770116/60666857-1a68a900-9e36-11e9-9817-83346a4e06e9.PNG)

**Comment by maeglin4** [comment]
Here is the /config/Modules/OpenStreetMap.php

![OpenStreetMap](https://user-images.githubusercontent.com/45770116/60667394-6e27c200-9e37-11e9-898c-4357a1c2254b.PNG)

**Comment by maeglin4** [comment]
do i need to change something in these files/folders ??
![modules-openstreetmap](https://user-images.githubusercontent.com/45770116/60667564-cf4f9580-9e37-11e9-9e9c-2c4cdaf4978f.PNG)

**Comment by z0lo13** [comment]
better to integrate google maps

**Comment by maeglin4** [comment]
> better to integrate google maps

yeah but how exactly, i entered the api key and it does not work in Canada

**Comment by z0lo13** [comment]
> 
> 
> > better to integrate google maps
> 
> yeah but how exactly, i entered the api key and it does not work in Canada

Google maps needs a custom module its not built-in current version only you can use openstreet map - for directions in canada can confirm it is not working

**Comment by adudekyeti** [comment]
Hi, unfortunately OpenStreetMap has a problem with routing in Canada, therefore we can't fix it. We tested it also on their website (http://www.yournavigation.org/) and they have there the same bug. If you want to have this functionality, we can offer paid integration with Google Maps.

**Comment by maeglin4** [comment]
thanks for the answer and the offer, but it will be okay
