### ISSUE TITLE
[Question]           How to give a user access to records based on field value?

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#10888]
Is it possible to give a user acces to a certain record based on a picklist value in that record?

For example:
![Aantekening 2019-07-04 143517](https://user-images.githubusercontent.com/16014524/60667104-f96d7b80-9e68-11e9-8b9a-c6bbe178582b.png)

As you can see in the example above User A has acces to 3 records, because those contacts has the city Rome.

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=AdvancedPermission&parent=Settings&view=List&block=1&fieldid=11

**Comment by LaurensCleyman** [comment]
Hi @mariuszkrzaczkowski , 

How does the 'Priority' parameter work?

Kind regards, 

Laurens

**Comment by paula-w** [comment]
“Priority” is used only to define the order of reloading/refreshing permissions. Permissions are saved in the database and must always be reloaded.
