### ISSUE TITLE
[Question] Which Google API to choose ??   

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#10884]
wich one do i need to choose to work with YetiForce ??

![google map api](https://user-images.githubusercontent.com/45770116/60617370-97960e80-9da1-11e9-8b4b-d670d1c0982f.PNG)

**Comment by davide-alghi** [comment]
An API key is service indipendent. create a project and require a key. maybe google will ask you c/c for billing. not all services are free and other are free up to a number of requests/queries.
after you have created an api key, remember to limit its use to your server IP address on google

https://console.cloud.google.com/apis/credentials

https://cloud.google.com/docs/authentication/api-keys

**Comment by paula-w** [comment]
The integration with google is only used to suggest addresses.
Everything else related to integration with maps uses Open Street Maps, not Google.
