### ISSUE TITLE
[Feature]    View by sales stage

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#10894]
### Describe the solution you'd like

![Opportunity-Kanban-4](https://user-images.githubusercontent.com/23143958/60682367-1736e280-9e61-11e9-8be1-78e70334fa75.png)

### Additional context

This view is much more convinient and user friendly then ours currently have

**Comment by paula-w** [comment]
We totally agree, this view would be amazing.
We're not sure when we can implement it in YetiForce however, it'll most likely have to wait until a client orders it from us.
Alternatively the community could collect funds on Open Collective https://opencollective.com/yetiforcecrm and then a view like that would become our priority.

**Comment by z0lo13** [comment]
> We totally agree, this view would be amazing.
> We're not sure when we can implement it in YetiForce however, it'll most likely have to wait until a client orders it from us.
> Alternatively the community could collect funds on Open Collective https://opencollective.com/yetiforcecrm and then a view like that would become our priority.

how much exactly is estimated cost for the view like that? could you please create sales funnel contribution on open collective then ?
