### ISSUE TITLE
Any image displays for a day then crushes 

### ISSUE THREAD

**Issue by one-use** [YetiForceCompany/YetiForceCRM#10898]
# 🐞 bug report

### ⁉️ Describe the bug
Images for products or for anything else can be uploaded and display fine for about a day. After that they crush, system shows that there is a image but can not display. This includes even logo fr CMR. 
![image](https://user-images.githubusercontent.com/42323603/60711624-34c18600-9f0d-11e9-9d0a-23507dd13922.png)

### 🔥 How to trigger the error
Images display fine for about a day. After that they crush. There is no specific way to reproduce the error. If I upload images today, they will be fine today. However broken next day. 

### 👎 Actual Behavior
Images won't display next day. When editing record I can see that file is still attached however it won't display. 
![image](https://user-images.githubusercontent.com/42323603/60711459-e7451900-9f0c-11e9-935e-64b5d039022b.png)

### 👍 Expected Behavior
Images to be visible every day. Obviously. :)

### 📷 Screenshot of configuration
![image](https://user-images.githubusercontent.com/42323603/60711827-98e44a00-9f0d-11e9-816e-1ff0940cb5ec.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.1
| Web server (name and version)|	Apache 2.4.39	|
| PHP  |			7.1					|
| Browser (name and version)  | 	Chrome Version 75.0.3770.100 (Official Build) (64-bit)	|
| Operating System (name and version)  | 	Linux if18.nano.lv 3.10.0-962.3.2.lve1.5.25.8.el6h.x86_64 #1 SMP Wed May 15 10:57:13 EDT 2019 x86_64	|
| Database (name and version) | 		|

**Comment by nkzach** [comment]
Check here https://github.com/YetiForceCompany/YetiForceCRM/issues/10164#issue-432504022

**Comment by one-use** [comment]
I have applied the fix suggested by @nkzach and now will just monitor behaviour for a couple of days. If the images stay where they are, i will then resolve the ticket.

**Comment by rskrzypczak** [comment]
I recommend installing the [5.1.0_ServicePack_v4.zip](https://github.com/YetiForceCompany/YetiForceCRM/releases)
