### ISSUE TITLE
[BUG] Language editor dont work

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1089]
![langeditor](https://cloud.githubusercontent.com/assets/1402355/8254381/751f9860-16b1-11e5-8bfa-40ed70082d67.JPG)

**Comment by waran70** [comment]
Here seems to work.  More details Alex pls

**Comment by waw555** [comment]
Button to add a variable does not work
Choose languages impossible

**Comment by waw555** [comment]
Languages are not hidden by the selection, the choice of language occurs only if once again choose the language selection box
