### ISSUE TITLE
[bug] syntax error, unexpected 'type' (T_STRING)

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#10891]
# 🐞 bug report

### ⁉️ Describe the bug

syntax error, unexpected 'type' (T_STRING)

![error](https://user-images.githubusercontent.com/16014524/60672995-03967680-9e77-11e9-9f5b-e1b342f655e1.png)

### 🔥 How to trigger the error

1. Set CACHING_PERMISSION_TO_RECORD in [config/security.php] variable to true.
2. Go to Settings -> Automation -> CRON
OR
Go to Settings -> Logs -> Server Configuration

### 👎 Actual Behavior
syntax error, unexpected 'type' (T_STRING)

### 👍 Expected Behavior
CRON page

### 📷 Screenshot of configuration

Page is not available due to bug.

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
![console](https://user-images.githubusercontent.com/16014524/60673093-41939a80-9e77-11e9-80ba-c28fd7ec97a3.png)

**cron.log**

Parse error: syntax error, unexpected 'type' (T_STRING) in ...../user_privileges/cron.php on line 3

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.1.0
| Web server (name and version)|Apache		|
| PHP  |	7.1.30							|
| Browser (name and version)  | Chrome	75	|
| Operating System (name and version)  | Windows 10		|
| Database (name and version) | MySQL	5.6.40-84.0-log	|

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version

**Comment by LaurensCleyman** [comment]
Fixed it: 

I deleted _user_privileges / cron.php_

Problem was similar to issue #10686.
