### ISSUE TITLE
[Question]  How to export all records in descending order for .CSV

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#10904]
### Description

Hello
How to export all records in descending order for .csv

for Ex: 
 In Lead module four records is their 
record name 1
record name 2
record name 3
record name 4

if we export all records in .csv file all record will come ascending order 

record name 1
record name 2
record name 3
record name 4

But i don't want this formats i want to descending order means
record name 4
record name 3
record name 2
record name 1

How can we achieve this format please help me

**Comment by ippeas1** [comment]
the same csv file has the ability to classificate . for example with openoffice or Libre office
