### ISSUE TITLE
5.2

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#10918]
For years, I've been monitoring the development of the YETIFORCE application, especially the time periods between versions. In my opinion, the next version 5.2. will bee one of the most stable so far, because the development team really took the time to truly correct all (most) issues. Therefore, all current and future users are very pleased 5.2.

**Comment by one-use** [comment]
what is the proposed ETA?

**Comment by LaurensCleyman** [comment]
I'm also curious about when version 5.2 would be released. 😃

**Comment by fbojan** [comment]
It was planned for the end of June, but because there is always some complication, it will still be necessary to wait. But the programmers are really trying to fix something more than issseus. I also hope that soon we will begin to work seriously.

**Comment by paula-w** [comment]
Thanks a bunch @fbojan !
We do our best to make all the versions we release stable and secure.
We're planning to release version 5.2 at the end of the month.
