### ISSUE TITLE
[PL][Pytanie] Problem z widokiem Kontaktów

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10919]
Witam, 

Na wersji 5.0.0 po utworzeniu Kontaktu nie widzę ich w liście, natomiast w bazie danych widnieją.
![Multimedia1](https://user-images.githubusercontent.com/21024857/60867945-343a2f80-a22c-11e9-9173-270cae4c276b.gif)

Proszę o podpowiedź co może być przyczyną.

**Comment by mariuszkrzaczkowski** [comment]
Jaki jest ustawiony domyślny filtr w liście rekordów ?
Proszę sprawdzić jakie są ustawione w filtrze.

**Comment by mrzewnicki** [comment]
Filtr jest domyślny Wszystkie bez żadnych ograniczeń
![image](https://user-images.githubusercontent.com/21024857/60868930-50d76700-a22e-11e9-83c0-671ff0857e26.png)

**Comment by bpabiszczak** [comment]
Nie da się z tym zgłoszeniem nic zrobić ponieważ nie ma logów, ale co ważniejsze, w takich przypadkach musimy mieć dostęp do takiego systemu. Ostatnio mieliśmy 2 podobne problemy i miały one związek z tym, że używamy funkcjonalności, która nie działa poprawnie na niektórych przeglądarkach: https://caniuse.com/#feat=textencoder, rozwiązaniem było aktualizacja przeglądarki i wyłączenie skryptów blokujących wyświetlanie reklam.

Obecnie mamy wersje 5.1 [od 5 miesięcy], warto przetestować czy problem występuje na najnowszej wersji, jeżeli tak, to najlepiej pokazać nam, jak wywołać błąd na wersji gitstable i gitdeveloper.

**Comment by mrzewnicki** [comment]
Sprawdze sobie na nowszej wersji, dziękuje za odpowiedź.
