### ISSUE TITLE
[Question] Privileges from SSH and YetiForce Settings aren't equal: How I can make it equal?    

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#10921]
### Description

Hi,
I'm new user from Yetiforce and I love it: So mutch more understandable and comprehensible than vTiger. 

#### But I have one problem:
I cannot upload images (e.g. watermarks in PDF) to the server.

I guess, it has to do with the fact that according to «Settings/Protocolling/Server configuration/System settings»
the paths 
- cache
- storage
- user_privileges

seams to have the wrong privileges.
![Privileges_YetiForce_Settings](https://user-images.githubusercontent.com/6169308/60873130-22f62080-a236-11e9-9524-e3024e814948.png)

But when I check the privileges via sFTP tool or SSH, they have exactly the same and (probably) correct privileges like the «config» folder:
folder: 755
files: 644

![Privileges_SSH](https://user-images.githubusercontent.com/6169308/60873189-3acda480-a236-11e9-9774-5c77fd8bf799.png)

**- Are the privileges maybe cached somewhere in YetiForce?**
**- Is there any way I can flush this cache for YF to request permissions new and right?**
**- Or how can I set the permissions for the 3 folders correctly?**

Would be great to get help or a hint in the right direction.
Regards
Martin

**Comment by vovpff** [comment]
I'm not sure but:
* Try to `chmod 755` for files also
* user and group should be your web server user:group. For example for ubuntu 14+ should be `chown www-data:www-data`

**Comment by paula-w** [comment]
1. You have to discuss it with your admin, we don’t provide support for servers.
2. From what we can see in the screenshots your configuration is incorrect (just like vovpff said, your user and group are most likely incorrect), your admin has to find out why you don’t have the necessary permissions.
3. You should have the read, save, and edit permission for all files. 
4. Here are our server requirements: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements
 In order for an image to show in pdf you have to add the domain to the list of trusted domains: https://github.com/YetiForceCompany/YetiForceCRM/blob/46af284fe479b1824e876fd148083a417f52c0b9/config/Security.php#L93 

As far as your questions about cache are concerned, the application manages cache using opcache and apcu, your permissions on files and folders are wrong.
Your server admin will tell you why the application doesn’t have the required permissions.

**Comment by mad99** [comment]
Thank you vovpff and paula-w for help.
I have create a support-ticket for the question about the server-group.
The server user is uid108539.

But I can't understand why the same user:group setting is not pictured/mapped in the Yeti-Backend.
Same user:group setting for config and cache
But for config the rights are OK.
For cache the rights are «Wrong».

Have set the user:group to server user:group:
uid108539:gid108539
![group_changed](https://user-images.githubusercontent.com/6169308/61449390-20da4300-a955-11e9-830e-cd165a23bdf9.png)


But no change in Backend:

![changed_group_same_error](https://user-images.githubusercontent.com/6169308/61449404-26d02400-a955-11e9-9c96-6702e396f7a7.png)

So the group is not the problem, I guess.
Maybe I have to set the files to 755 like vovpff recommended.
But why the folder rights is dependent from file-permissions?
This is not really comprehensible.

Maybe you (paula-w) has any logical explanation, before I do anything so far-reaching.
I don't like to set permissions for so many files «wrong»...

Regards
Martin

**Comment by mad99** [comment]
Thank you for your advice for about:
«In order for an image to show in pdf you have to add the domain to the list of trusted domains:
 	public static $PURIFIER_ALLOWED_DOMAINS = []; 
»

I have searched for any explanation in documentation, also in your linked ressources on git in my PDF-custom-fonts-question (other issue-thank you too! https://github.com/YetiForceCompany/YetiForcePDF#custom-fonts)

There is no advice, how YetiForce recommends to store/link images in PDF.

1. Is there a update-save Folder/area in the default-installation for? (without add the yetiForce-istallation domain to the list of secure domains)

2. Or do I have to link the Image from an other «server» anyway, because this is the recommended way to use images in PDF's? And so I have to link with absolute path and add the domain in the list of trusted domains?

IF 2. -> Do I have to do this «hardcoded»/by hand (update-secure?) or in the YetiForce-Backend?
And with the hole value like protocoll and end-slash «https://www.my-domain.com/»? Or only «my-domain.com»?

Thank you for help or hint for the matching documentation
Martin
