### ISSUE TITLE
[BUG] Menu create text error

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1092]
The text goes beyond the field
![menucreate](https://cloud.githubusercontent.com/assets/1402355/8254498/627f7f44-16b2-11e5-8e45-c48224d42cc6.JPG)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/adcd397f325019675c0e2d65653b96a23961de37
