### ISSUE TITLE
[PL][PYTANIE] Reguły Roundcube

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10942]
Witam,

Czy jest możliwość włączenia reguł w kliencie poczty? A jeśli tak to jak? 

Czy muszę szukać sobie plugin'a do roundcube'a?

**Comment by bpabiszczak** [comment]
Trzeba sobie poszukać pluginu.

**Comment by mrzewnicki** [comment]
OK, dzięki
