### ISSUE TITLE
[Question]  How can I configure the PDF editor to get all the options, example to be able to justify text.          

### ISSUE THREAD

**Issue by ojimenezt** [YetiForceCompany/YetiForceCRM#10955]
### Description

I am doing templates in PDF generator, but I have problems since I can not find the option to justify the text.

If anyone knows how to configure and add the options please help `me.

![chrome_etrASFVvMJ](https://user-images.githubusercontent.com/13370996/61080700-ed178e80-a425-11e9-94c3-2e928ca6932d.png)

**Comment by z0lo13** [comment]
@ojimenezt 
First of all recomending using the inline-html method for constructing templates.
Bad news is that YetiforcePdf does not support Justify rule

**Comment by paula-w** [comment]
Just like @z0lo13 said you have the use the inline html method.
The list of all supported rules can be found here: https://github.com/YetiForceCompany/YetiForcePDF

**Comment by ojimenezt** [comment]
Thanks for the answer, however, I'm not an expert in html, help me with an example of the inline method

**Comment by ojimenezt** [comment]
> Just like @z0lo13 said you have the use the inline html method.
> The list of all supported rules can be found here: https://github.com/YetiForceCompany/YetiForcePDF

Thanks for the answer, however, I'm not an expert in html, help me with an example of the inline method

**Comment by z0lo13** [comment]
@ojimenezt 
there are a lot of styles you can use, send what you need exactly.

**Comment by ojimenezt** [comment]
> @ojimenezt
> there are a lot of styles you can use, send what you need exactly.

What I need exactly is that in the PDF template, a contract with the following characteristic is generated.

Pararafos: justified.

I mean, I need all the paragraphs to be justified, like doing it in the PDF editor, I have no idea
