### ISSUE TITLE
[BUG] Field data Organizations

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1095]
You can not add a field with the Cyrillic alphabet

When you add a field with Latin, throws to home with a clean sheet

![orgfield](https://cloud.githubusercontent.com/assets/1402355/8254699/023e05e0-16b4-11e5-8770-bd33191b2568.JPG)

**Comment by bpabiszczak** [comment]
please write same example

**Comment by waw555** [comment]
If I add a new field with the name of KPP, then he sends me to an empty home page, and the field is not added. If I add a field check point, the field is simply not added.

**Comment by waw555** [comment]
Please Fix in Version YetiForce 2.1 GA 
![animation 4](https://cloud.githubusercontent.com/assets/1402355/8652070/1581db32-2996-11e5-8521-1b508779b004.gif)

**Comment by paula-w** [comment]
The field name  should preferably be in English, and can't contain any special characters, and no Cyrillic alphabet either. Then you can add the translation of the displayed value to the language file in languages\en_us\Settings\Vtiger.php.
