### ISSUE TITLE
[BUG] Profile and Group and Role, save button don't work

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1096]
![profilesave](https://cloud.githubusercontent.com/assets/1402355/8254853/1e83e516-16b5-11e5-8c31-ff1c08d0dd19.JPG)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/638eeb6adb823233869caaaa301b9c2142ce1f93
