### ISSUE TITLE
Calendar view all users calendar by default

### ISSUE THREAD

**Issue by amgsports** [YetiForceCompany/YetiForceCRM#10978]
How to view all users calendars by default. Now I should go into the filter and select each user one by one? Thank you!

**Comment by guide5232** [comment]
If you change  Default module  Home to calendar then view all users calendar  by default.



![calender](https://user-images.githubusercontent.com/47585969/61207124-a1235d00-a737-11e9-8793-d81d92c34a76.JPG)

**Comment by amgsports** [comment]
Thank you!
