### ISSUE TITLE
Cant print PDF Template - it seems like many various stuff currently  not works.

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#1098]

**Comment by MaciejStencel** [comment]
Hi. I have tested printing of PDF on newest YF 2.0.162 on Quotes records and everything worked ok.
We need more informations, versions, record data etc. 

It would be best if You could reproduce it on test.yetiforce.com

**Comment by waran70** [comment]
Maciej this is where I found issue. Please see test version. Invoice module and print pdf

**Comment by MaciejStencel** [comment]
test.yetiforce.com is a mirror of older full release Yetiforce 2.0.0. Those errors were fixed lately and will be present in YF 2.1.

Soon we will have another testing environment which will represent current state of yetiforce code from github.

If Youll give more informations about error message etc i can fix it or direct You to patch that will fix your installation. As I mentioned newest YF prints nicely pdf files.

**Comment by waran70** [comment]
Maciej, I notified that so the error can be removed from test version and source can be patched. The issue I think is YF public image. People visits test version and they should get good user experience instead of errors. From marketing point of view it is essential to keep test public versions working, especially that this release is called "stable GA" :-)

**Comment by bpabiszczak** [comment]
Unfortunately, our testing version contains many changes and is restored automatically. In order for the change to work, we would have to enter in in 3 different locations that’s why we won’t upload it to the testing version. Next week we are going to update it to 2.1 so this issue will no longer be a problem.

At the same time, we are also working on two additional versions: gitmaster.yetiforce.com, gitdeveloper.yetiforce.com that will be updated with the changes from GitHub every 60 minutes.
