### ISSUE TITLE
Bug or UI change: Hovering cursor over menu does not show menu

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1099]
When hovering the cursor over a menu item, the menu no longer appears. I have to click on the menu to see it. Is that the new indended behavior or a bug? If it is intended, what is the reasoning behing.
Version: 2.0.151

**Comment by waran70** [comment]
Current test version is broken. We need to wait for update as so far it is noticed many errors

**Comment by bpabiszczak** [comment]
The current version contains changes from over 110 revisions, they require more tests than we would be able to perform on our own. We will fix each bug that you report.

**Comment by bpabiszczak** [comment]
The way the menu works is a result of migration to the latest version of Bootstrap [that’s how the menu works there]. We are going to change the menu and the way it works and it worked in the past. Soon we are going to present our vision.
