### ISSUE TITLE
Outgoing mail server in mail client settings

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#11]
It seems the mailclient / roundcube is not authenticating right.
When we set it to our local system it returns an authentication error.
When I set it manually in Roundcube identities itself, it works fine, same for the standard (vtiger) outgoing mail settings.
We tried both localhost and mail.domain settings but still get the same error.

**Comment by bpabiszczak** [comment]
We haven't received enough information about this issue, that's why we are closing it. If the problem appears in the future, please send us more detailed descriptions.
