### ISSUE TITLE
[Question] Upload Images does not work because of wrong privileges. Change privileges to the requirements but no change           

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11017]
Hi,
Sorry to open a new issue about. 
But [the first](https://github.com/YetiForceCompany/YetiForceCRM/issues/10923#event-2482731051) was closed before the problem is solved...

So thanks to vovpff and paula-w I have createe a support-ticket for the question about the server-group at my hosting-provider.
The server user is uid108539.

Neverless I can't understand why the same user:group setting is not pictured/mapped in the Yeti-Backend.
Same user:group setting for `config `and `cache`
But for `config `the rights are OK (green).
For `cache`, `storage`, `user_privileges ` the privileges are «wrong» (red).

Have set the user:group to server user:group:
uid108539:gid108539
![group_changed](https://user-images.githubusercontent.com/6169308/61449390-20da4300-a955-11e9-830e-cd165a23bdf9.png)

But no change in Backend:

![changed_group_same_error](https://user-images.githubusercontent.com/6169308/61449404-26d02400-a955-11e9-9c96-6702e396f7a7.png)

So the group is not the problem, I guess.
Maybe I have to set the files to 755 like vovpff recommended.
But why the folder rights is dependent from file-permissions?
This is not really comprehensible.

Maybe you (paula-w) has any logical explanation, before I do anything so far-reaching.
I don't like to set permissions for so many files «wrong»...

Regards
Martin

**Comment by bpabiszczak** [comment]
We do not provide server support. You need to discuss that with your administrator.
