### ISSUE TITLE
time control

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#11013]
The Time control module only allows for 24 hours... is there a way to by pass that limitation? i have projects that last for days - sometimes weeks & I need to be able to track the total time of the entire project. Also individual time records aren't adding up. Please help, thanks.

**Comment by davide-alghi** [comment]
Hi hobejeans,
edit ```config/Modules/OSSTimeControl.php``` and set **$DISALLOW_LONGER_THAN_24_HOURS** to **false**

```PHP
class OSSTimeControl
{
	/** Right calendar panel visible by default. true - show right panel, false - hide right panel */
	public static $SHOW_RIGHT_PANEL = true;

	/** Block creating record if duration exceeds 24 hours */
	public static $DISALLOW_LONGER_THAN_24_HOURS = false;
}
```

**Comment by vslonska** [comment]
Hello,
Same problem. I tried to add public static `$DISALLOW_LONGER_THAN_24_HOURS = false;` to that file, but without success.
It seems this solution doesn't work anymore.
Anyone would know how to solve this ?
Thank you, Regards,
