### ISSUE TITLE
Unable to send workflow email

### ISSUE THREAD

**Issue by vjstyla** [YetiForceCompany/YetiForceCRM#1102]
Hello There,

I can see that the workflow is running well and I created a test email sent when lead is hot but its not happening?

Please help

**Comment by mariuszkrzaczkowski** [comment]
I tested on the latest version and it works fine.
Do you have an active workflow in cron? All e-mails are sent workflow in cron.

**Comment by IngewonPL** [comment]
I have the same problem. Tasks are formed without a problem, test mail comes. When sending e-mail at the following event, nothing happens. Mail created according to the following template.
![mail](https://cloud.githubusercontent.com/assets/12641874/8325166/7d7008de-1a57-11e5-9109-c33186aba63f.jpg)

YetiForce CRM 2.0

**Comment by mariuszkrzaczkowski** [comment]
Bug does not exist in the latest version (2.0.176), it has been fixed in this revision
https://github.com/YetiForceCompany/YetiForceCRM/commit/1082e6c29424777870e33dd0aa118530ebe59ee5

**Comment by IngewonPL** [comment]
Ask for additional help. I added the change 1082e6c, but when I type in the e-mail rigidly "on *", for example, help@example.com everything works. If I choose ", $ (assigned_user_id: (Users) Email1) 'mail is no longer occurs.
Do I need to still change a file?
