### ISSUE TITLE
[PL][Pytanie] Zwolnienie pracy i nieodświeżanie się animacji     

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11046]
Temat może troszke nie intuicyjny ale już tłumaczę. Podczas zmiany w rekordach np uruchamia się animacja praca "proszę czekać" i tyle:
![image](https://user-images.githubusercontent.com/21024857/61636672-5e610800-ac96-11e9-9186-6e8f6382d6b3.png)

Musze odświeżyć F5 i wtedy widzę efekty pracy.
To samo mam przy jakiejkolwiek edycji rekordów lub też masowej edycji. Z tym że przy masowej czasem nawet nie jest dokonywana zmiana i muszę próbować po 2-3 razy. Mógłbym prosić o rade z czego to może wynikać? Jakie logi byłby pomocne przy diagnozie?

**Comment by bpabiszczak** [comment]
Czy błąd występuje na gitdeveloper? Co wówczas widać w konsoli przeglądarki?

**Comment by mrzewnicki** [comment]
NIe, na Gitdeveloper to wszystko Idealnie działa. 
U mnie jest taki błąd:
![image](https://user-images.githubusercontent.com/21024857/61686761-ea1f7680-ad20-11e9-8c5d-4bc67e3c58ba.png)

**Comment by mrzewnicki** [comment]
Po rozwinięciu błędów mają następującą treść:
![image](https://user-images.githubusercontent.com/21024857/61686993-7fbb0600-ad21-11e9-84c7-9390436b715d.png)

![image](https://user-images.githubusercontent.com/21024857/61687012-8e092200-ad21-11e9-9379-682919c574f2.png)

![image](https://user-images.githubusercontent.com/21024857/61687024-96f9f380-ad21-11e9-9906-a8003a27536b.png)

![image](https://user-images.githubusercontent.com/21024857/61687044-a2e5b580-ad21-11e9-8733-c5ab30634fce.png)

**Comment by mariuszkrzaczkowski** [comment]
Prosze o przesłanie zrzutu ekrany z weryfikacji konfiguracji, 
komunikat mówi ze nie ma uprawnień do zapisania pliku

**Comment by mrzewnicki** [comment]
![yetiforce_settings](https://user-images.githubusercontent.com/21024857/61687968-01ac2e80-ad24-11e9-8b6c-3e3503884d64.png)

**Comment by mrzewnicki** [comment]
Faktycznie, zmieniłem uprawnienia do pliku i zaczęło chulać... Jakoś zapomniałem o konsoli... Dzięki wielkie za podpowiedź!!

**Comment by mrzewnicki** [comment]
U moich użytkowników pojawił się następujący komunikat:
![image](https://user-images.githubusercontent.com/21024857/61696001-cb2adf80-ad34-11e9-8c9a-fbfbb70eaf35.png)
 U mnie działa, więc pewnie coś źle robią xD  ale animacje się zawieszają.

**Comment by mrzewnicki** [comment]
Ale to mogę zmienić sobie typ na bazie już teraz czy na wyższą wersję muszę czekać? BO boje się zeby mi się db nie wyłożyła jak zmienie typ pola.

**Comment by mariuszkrzaczkowski** [comment]
Najbezpieczniej to czekać na paczkę aktualizacyjną, ale sądzę że ta zmiana nie powinna nic popsuć.

**Comment by mrzewnicki** [comment]
ok 😄  lepiej poczekam. Dzięki wielkie za szybką pomoc!
