### ISSUE TITLE
[bug] [PL] Dodawanie załączników z CRM

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11053]
# 🐞 bug report

### ⁉️ Describe the bug
Na wersji 4.1 niestety nie działa mi załącznia plików z CRM do maila. Ten sam problem występuje na GitDeveloper. 

### 🔥 How to trigger the error
1. Przejdź do Wsparcia
2. Przejdź do Zgłoszenia
3. WYbierz jeden i w niego wejdź
4. Jeśli nie ma podpiętego maila to wybierz, jeśli jest to jedną z opcji odpowiedzi.
![image](https://user-images.githubusercontent.com/21024857/61703308-996c4580-ad41-11e9-8604-34dd17a8c8f2.png)

5. Następnie wybierz "Plik z CRM" po prawej stronie. 
6. Otworzy się okno z listą, wybierz jeden lub więcej po czym naciśnij u góry ekranu "Wybierz z Listy"
7. Okno się zamnie ale załacznik nie doda do listy w panelu po prawej stronie maila
### 👎 Actual Behavior
Można wybrac załącznik z listy, ale po akceptacji nie dodaje się on do listy po prawej stronie

### 👍 Expected Behavior
Po wyborze i akceptacji, załącznik powinien się tam zlistować

### 📷 Screenshot of configuration
![yetiforce_settings (1)](https://user-images.githubusercontent.com/21024857/61703548-14356080-ad42-11e9-9996-7fd1d2ca0a02.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Niestety Brak logów dodawania 

* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log 

-->

### 🌍  Your Environment 
YetiForce 4.1
Apache2.0
php7.2
Opera 60.0.3255.170
Server: Ubuntu 18.04 LTS
User: Win 10
mysqld  Ver 5.7.26-0ubuntu

### ❓ Additional context
U mnie na serwerze nie otwiera się w ogóle okno wyboru załączników kiedy robie to przez głoszenie. Muszę przechodzić przez skrzynkę, nowa wiadomośc i tam.
![Nienazwany](https://user-images.githubusercontent.com/21024857/61704041-2663ce80-ad43-11e9-8e3a-cbcdeeac4bca.gif)

**Comment by mariuszkrzaczkowski** [comment]
Czy błąd występuje w wersji stabilnej (https://gitstable.yetiforce.com) i deweloperskiej (https://gitdeveloper.yetiforce.com) ?

**Comment by mrzewnicki** [comment]
Na obu niestety nie dołącza mi załączników do maila.

**Comment by konadrian** [comment]
Proszę się upewnić, że dokument rzeczywiście posiada dołączony załącznik
![Dodawanie załacznika](https://user-images.githubusercontent.com/3193498/61929251-2f3ee500-af7b-11e9-829b-cee43c71cecf.gif)
