### ISSUE TITLE
[PL][Pytanie] Dołączanie załaczników do maile z CRM      

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11052]
Na wersji 4.1, niestety nie działa mi załącznia plików z CRM do maila. Ten sam problem występuje na GitDeveloper.

Przycisk otwiera okno, mogę wybrać pliki ale po wciśnięciu "Wybierz z listy", okno się zamyka a załącznik nie dodaje. Dodawanie z Lokalnego dysku działa bezbłędnie zarówno na GitDeveloper jak i u mnie. 
Nagrania u mnie:
![Nienazwany](https://user-images.githubusercontent.com/21024857/61701919-35e11880-ad3f-11e9-9405-fd29b103b620.gif)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/61702471-20202300-ad40-11e9-8210-060283dbb8a5.jpg)
