### ISSUE TITLE
[bug] Email templates image upload hung

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11057]
Upload applet in email templates hung. No way to post link to image. By the way, when you guys allow uploading images to server? This is pretty annoying.

**Comment by waran70** [comment]
Actually other elements too like tables. Priviledges OK, server 100% compatible...
Anyone got the same?

**Comment by paula-w** [comment]
This is @bpabiszczak 's response:
This functionality will have to be crowdfunded on OpenCollective.
