### ISSUE TITLE
Workflow - Payments In - Send Email Template 500 error

### ISSUE THREAD

**Issue by sirwinston1** [YetiForceCompany/YetiForceCRM#11060]
This only occurs in the workflow for Payments In.  When trying to add the task "Send Email Template" an error 500 is generated.  Screen shows loading cursor but never loads the email template box.  Error log below: 

`2019-07-23 12:10:51.7165 [error] - Call to a member function getId() on boolean
Error: Call to a member function getId() on boolean in /var/www/html/modules/Vtiger/models/Relation.php:245
Stack trace:
#0 /var/www/html/modules/Settings/Workflows/views/EditTask.php(82): Vtiger_Relation_Model::getInstance(false, Object(Documents_Module_Model))
#1 /var/www/html/include/main/WebUI.php(183): Settings_Workflows_EditTask_View->process(Object(App\Request))
#2 /var/www/html/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#3 /var/www/html/public_html/index.php(11): require('/var/www/html/i...')
#4 {main}
 - 0 include/main/WebUI.php (186)  >>  App\Log->error('Call to a member function getId() on boolean
Error: Call to a member function getId() on boolean in modules/Vtiger/models/Relation.php:245
Stack trace:
#0 modules/Settings/Workflows/views/EditTask.php(82): Vtiger_Relation_Model::getInstance(false, Object(Documents_Module_Model))
#1 include/main/WebUI.php(183): Settings_Workflows_EditTask_View->process(Object(App\\Request))
#2 index.php(24): Vtiger_WebUI->process(Object(App\\Request))
#3 public_html/index.php(11): require(\'i...\')
#4 {main}')
 - 1 index.php (24)  >>  Vtiger_WebUI->process()
 - 2 public_html/index.php (11)  >>  require('index.php')
2019-07-23 12:10:51.6725 [info][application] -
$_GET = [
    'module' => 'Workflows'
    'parent' => 'Settings'
    'view' => 'EditTask'
    'type' => 'VTEmailTemplateTask'
    'for_workflow' => '116'
]
`

**Comment by sirwinston1** [comment]
Error also occurs in both stable and dev builds as well. 

[https://gitstable.yetiforce.com/index.php?module=Workflows&parent=Settings&view=Edit&record=79]

[ https://gitstable.yetiforce.com/index.php?module=Workflows&parent=Settings&view=EditTask&type=VTEmailTemplateTask&for_workflow=78]

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/61930570-6ebb0080-af7e-11e9-831a-ca338254022b.jpg)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/8545
