### ISSUE TITLE
[bug] Editing workflow email task - escape issue

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11062]
when you edit workflow email template and you hit escape accidentally your work is gone (unless you save it sometimes - who does?). This is annoying bug. I have lost half an hour of work.

**Comment by rskrzypczak** [comment]
It's not an error, it's how the modal windows work.
You will be able to block it in the upcoming version.
![image](https://user-images.githubusercontent.com/10221999/62048343-f158ef80-b20c-11e9-8512-0ce8763fe02b.png)
