### ISSUE TITLE
[PL][Pytanie] Aktualizacja czasu zamknięcia rekordu

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11074]
Witam,

Mam pytanie o aktualizacje czasu zgłoszeń. Ponieważ przestał mi się aktualizować czas "Obiegiem informacji" z warunkiem "Raz gdy zostaną spełnione warunki", te same ustawienia działają gdy zmienie wariant uruchomienia na "Ręczne wywołanie przez Użytkownika". Ta sama opcja działa na GitStable.  Wersja 4.1. Próbowałem Eksportować Workflow z GitStable i potem Importować do siebie, pomimo importu zakończonego powodzeniem, niestety nic nie ruszyło.

Nie mam żadnego błędu w logach ani consoli. Gdzie mogę sprawdzić w czym jest problem?

**Comment by bpabiszczak** [comment]
Nie wspieramy wersji 4.1...

**Comment by mrzewnicki** [comment]
Mój błąd wersja to 5.1 ale udało mi się rozwiązać kwestie. Musiałem dodaj aktualizacje rekordów powiązanych do Przepływu pracy i zaczęło działać.
