### ISSUE TITLE
[Feature] Sub Status   

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11076]
Is that possible to add in feature a sub status? That would be very helpfull for creating and controling a proccess. Also it allow to divide and perform action depend on status.

For example:
If product is have been return on guarantee we can approve it or reject but we keep fact the product was reported on guarantee. If product have been reported on guarantee we can select only two status, approve or reject. We don't haave long list of status. I think that would be nicer for user.

I saw on gitDeveloper some great graph of status in Ticket summary view, that would be great way to implement it.

What you say? 😃

**Comment by davide-alghi** [comment]
Hi mrzewnicki,
in Tickets module, Status picklist has about ten values and you can add new ones.
You can, via back-end, add a new Sub-Status picklist with all needed values.
So you can create your custom view (filter) with needed fields (picklist too) and show graph as dashboard widget.
