### ISSUE TITLE
[Question] Block Editing Except Assigned To Field?

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#11080]
### Description

Can we block editing a record until the record is assigned to the user from specific role?

example:

**record is created by Admin**
-sales team cannot edit any information in it except assigned to field
**a user from a sales team change assigned to himself or any in the sales team**
-sales team can edit record

**Comment by bpabiszczak** [comment]
You can set up something similar using groups and a custom rule.

![image](https://user-images.githubusercontent.com/10197525/62011856-89f45e80-b17e-11e9-820b-4b67cdf33705.png)

**Comment by z0lo13** [comment]
> 
> 
> You can set up something similar using groups and a custom rule.
> 
> ![image](https://user-images.githubusercontent.com/10197525/62011856-89f45e80-b17e-11e9-820b-4b67cdf33705.png)
Thank you 

This feature is limiting other group from complete access to the record

But i dont need them to edit any other field **except one field**, if they change it -> then i transfer ownership of the record to them-> and they able to edit any fields.

 Otherwise if they have not change the record which is not protected they still cant edit any records

**Comment by bpabiszczak** [comment]
If you can edit one field, you can also edit other fields resulting from profile configuration. To change "Assigned To", you can use the tools in the list of records.

![image](https://user-images.githubusercontent.com/10197525/62012411-29691f80-b186-11e9-976b-1acf41e44667.png)
