### ISSUE TITLE
Background Login Yetiforce 5.1.0

### ISSUE THREAD

**Issue by walfs** [YetiForceCompany/YetiForceCRM#11089]
Yetiforce 2019:
Is it possible to change the background of the login page?

When making the change, and putting a background image the console throws the following error:
  Refused to load the image 'URL.jpg' because it violates the following Content Security Policy directive: "img-src 'self' data: a.tile.openstreetmap.org b.tile.openstreetmap.org c.tile.openstreetmap.org ".

For what is this? in which file "img-src" is authorized, is it safe?

**Comment by z0lo13** [comment]
where are you making changes?
you will need to create another class in login css and change Login.Default.tpl

**Comment by walfs** [comment]
I made the changes in "public_html / layouts / basic / modules / Users / Login.css" in the corresponding background line: url ("/ layouts / basic / skins / modern / images / imagen.png"); and throws me the error by browser console, that infirnge the rules. Sorry for the English, I'm using translator.

**Comment by z0lo13** [comment]
> 
> 
> I made the changes in "public_html / layouts / basic / modules / Users / Login.css" in the corresponding background line: url ("/ layouts / basic / skins / modern / images / imagen.png"); and throws me the error by browser console, that infirnge the rules. Sorry for the English, I'm using translator.

you need also place min.css and if you adding new container change  Login.Default**.tpl** to the correct name
