### ISSUE TITLE
Access local installation on internet

### ISSUE THREAD

**Issue by KrishnaPB** [YetiForceCompany/YetiForceCRM#11091]
Dear Team,

I have configured yatiforce on local server. and forwarded the port to static IP. But while accessing the application over web its redirecting to local server IP. Please help me to access the yatiforce on internet.

I have tried below code by commenting:

force/include/main/WebUI.php

if (AppConfig::main('forceRedirect')) {
                        $requestUrl = (\App\RequestUtil::getBrowserInfo()->https ? 'https' : 'http') . '://' . $request->getServer('HTTP_HOST') . $request->getServer('REQUEST_URI');
                        if (stripos($requestUrl, AppConfig::main('site_URL')) !== 0) {
                                header('location: ' . AppConfig::main('site_URL'), true, 301);

But it didnt work.

**Comment by davide-alghi** [comment]
check 'site_URL' value in config folder
