### ISSUE TITLE
[Question]           Assign Owner to to company, not user

### ISSUE THREAD

**Issue by cornutaurus** [YetiForceCompany/YetiForceCRM#11097]
Hello, I have a question regarding assign ownership

I'm using Linux Mint 19.1
Yetiforce Verson 5.1.0

I want anytime a user create an account, contacts, partners, etc and the Assign owner automatically selected the Company/Admin and they can't change it.

Below are the steps I've tried. 

- Created a new user (tester) and assigned it to a role (could be any role)
![user](https://user-images.githubusercontent.com/36463465/62013135-1e11f600-b17e-11e9-9975-656574913581.png)

---

- Make profile (tester) that the user can't delete
![profile](https://user-images.githubusercontent.com/36463465/62013146-2ff39900-b17e-11e9-8532-14e173b709e9.png)

---

- Link the role to the profile
- I unchecked "enable change of record owner because I want to records to be assigned to company/admin and not user". 

![role](https://user-images.githubusercontent.com/36463465/62013160-4ac60d80-b17e-11e9-9057-7e1bdc279298.png)

---
- Settings - Permission - Assign Owner. 
- I selected "tester" user to assign owner to Admin

![assign owner](https://user-images.githubusercontent.com/36463465/62013219-0b4bf100-b17f-11e9-98a5-922bb10a2e05.png)

---

- When logged in with username "tester" and tried to create an account it still show assign records to be to tester user but not Admin account

![Account](https://user-images.githubusercontent.com/36463465/62013230-27e82900-b17f-11e9-8000-f083f635a480.png)

---

How could I do it where it default to Admin/Company?
Thanks

**Comment by bpabiszczak** [comment]
What do you have here?

Software configuration > Permissions > Roles

![image](https://user-images.githubusercontent.com/10197525/62014077-b7500500-b19c-11e9-9cf0-0715bf4dc262.png)

**Comment by cornutaurus** [comment]
Hello. I had **[All Users]** for the option share with users.

**Comment by bpabiszczak** [comment]
In the first post you ask about the field "Assigned To" so what you have in the field: "Can assign records to".

**Comment by cornutaurus** [comment]
Hello, I had Can assign records to "All Users", exactly from the picture. 
> 
> In the first post you ask about the field "Assigned To" so what you have in the field: "Can assign records to".

**Comment by bpabiszczak** [comment]
Set the value to: from panel
Then set the group in the panel.
