### ISSUE TITLE
not translated - tworzenie obiegu informacji

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#111]
w module tworzenie obiegu informacji brak jest fukcjonalności pozwalajacej na przenoszenie danych pomiędzy modułami np. jeśli utworzę klienta i kontrahenta (w tej samej osobie) i chcę przenieść z jednego do drugiego dane podstawowe (nr telefonu, mail, etc) muszę to zrobić ręcznie. Obieg informacji pozwala na utworzenie rekordu lub jego modyfikację ale tylko w obrębie jednego modułu, brak też jest możliwości wyboru pól relacyjnych jako warunku zmiany np. jeśli w module Klient nastąpi zmiana pola X to  w module kontrahent uzupełnij pole Y. 

p.s. jaka jest różnica pomiędzy modułem produkty a produkty sprzedane ? co na co wpływa w systemie w odniesieniu do tych modułów?

**Comment by bpabiszczak** [comment]
Po pierwsze: jeden problem jedno zgłoszenie. Nowe pytanie to nowe zgłoszenie. Lepiej pytania przesyłać do nas na maila niż dawać tu w zgłoszenia.

Odnośnie pytania: Nie wiem jaka jest różnica pomiędzy klientem a kontrahentem, dla mnie jest to ten sam moduł.

**Comment by bpibiza** [comment]
Oczywiście wyraziłem się nieprecyzyjnie: miałem na myśli relację pomiędzy kontaktem a kontrahentem. W tym kontekście nalezy rozpatrywać problem opisany powyżej. Brak transferu danych pomiędzy modułami kontaktu i kontrahenta (via obieg informacji). do każdego z tych modułów (kontakt, kontrahent) podpięte są inne - nie zawsze te same - moduły powiązane. Stąd też potrzebne są takie "żabie skoki" od kontaktu do kontrahenta. Brakuje mi tu (podobnie jak vtiger) modułu który byłby swoistym centrum informacyjnym dla całego systemu, 

Odośnie uwagi: sądzę, że każda forma pomocy (również taka jak wymiana informacji tutaj) jest Wam pomocna przy tworzeniu tego oprogramowania. Nie byłoby banalnych pytań jeśli można byłoby dotrzeć do (szczątkowej choćby) dokumentacji; opisu modułów i ich funkcjonalności. MOże czas zacząć ubupliczniać wiki dla YF

**Comment by bpabiszczak** [comment]
Funkcjonalność przenoszenia danych pomiędzy modułami istnieje. Można ją zaobserwować w module Lead z konwersją do Kontrahenta jak również tworzenie np. ofert, zleceń itp. gdzie podstawowe dane się kopiują. Problem polega zapewne na tym, że większość tych konfiguracji wykonuje się poprzez utworzenie odpowiedniej tablicy w odpowiednim pliku. Raczej nie planujemy na chwilę obecną utworzenia do tego panelu. Ogólnie temat jest zbyt obszerny na jeden ticket. Takie rozwiązanie wymagało by wiele panel. Będziemy zaszywać w systemie logikę przenoszenia, ale nie wiem na ile będzie to w przyszłości konfigurowalne, nie chcę niczego obiecywać.

Moduł produkty służy do rejestrowania produktów które chcemy sprzedawać (w przypadku szans sprzedaży i zakładki produkty i usługi -> produkty zainteresowane bazujące na produktach służą do oznaczenia, jakimi produktami jest zainteresowany klient (z pośród tych, które sprzedajemy), zaś produkty sprzedane to te, które mu sprzedaliśmy (oddzielna baza produktów, powiązana polem z produktami które oferujemy).

Zdajemy sobie sprawę z potrzeby dokumentacji. Na chwilę obecną jej jeszcze nie ma, jak się pojawi to ją opublikujemy. Do tego czasu należy odkrywać system samemu, albo zamówić szkolenie u nas, albo zadawać pytania.
