### ISSUE TITLE
Looking forward to 6.0

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#11111]
Is there a message of 6.0 now? I look forward to opening up some new versions of the news, let us look forward to it, thank you.
     Many fields in the current version of the workflow send mail have problems and cannot be displayed. 
    Looking forward to 6.0

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
at the moment, we are planning to release 5.2 and then 5.3. We don't know when 6.0 will be released. 
You can report bugs anytime at GitHub. Please just remember to describe a problem properly because the issue you added above is cut in the middle of the sentence.
