### ISSUE TITLE
[bug] Error insert a Date

### ISSUE THREAD

**Issue by lzuccagnoli** [YetiForceCompany/YetiForceCRM#11126]
When I insert a date I get the error message "please enter a valid date" and the inserted date turns into "aaaa-06-gg" (I noticed that the only thing that remains correct is the month ...) but of course with this new text the date is invalid ...

I tried to change the English or Italian language but the problem remains the same ...

My version of Yeti is the 5.1.0 with update V.5.

On online demo the error is not present...

I attach the screensh
![Bug Yeti](https://user-images.githubusercontent.com/53175360/62117694-a696b080-b2bc-11e9-901f-2e11e74ba1a9.jpg)
ot

Thanks

**Comment by davide-alghi** [comment]
I suppose your cut-screenshot is about right-side of graphical calendar.
I cannot reproduce anywhere: more infos are needed. Are there some error in your browser console?
Are you inserting date via calendar or by hand?
What's about (exactly) date format in your user preferences?

**Comment by lzuccagnoli** [comment]
Yes it is the right side, but the problem is on all data field. 
It is strange, on the online demo I do not find this bug ...
The problem occurs in both insert method. 
Excluded if I import the data from csv but at the first modification of the record it tells me the error.
I noticed the error in a first installation with dd-mm-aaaa, but I installed everything with aaaa-mm-dd 
but nothing has changed. I use chrome and I have no errors ...

![yetiforce_settings](https://user-images.githubusercontent.com/53175360/62148456-09f30380-b2fa-11e9-8b52-bd44bcadaa71.png)

**Comment by lzuccagnoli** [comment]
Fixed or almost ...
The verison with this bug was installed via softculous present on my hosting service... 
I downloaded and installed the same version (5.1.0) from the sourceforge site and this error is not present ... mystery ...
I close this issues thanks
