### ISSUE TITLE
[PL][Pytanie] Masowa edycja

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11129]
Witam, gdy próbuje edytować rekordy zgłoszeń które są wypełnione danymi nie mogę ich edytować masowo. Jeśli stworze puste testowe i nadam im np tylko Temat to mogę to robić bez problemu. W consoli otrzymuje nastepujące błędy:
![image](https://user-images.githubusercontent.com/21024857/62128442-b7532080-b2d4-11e9-987b-a1da35e0c7e1.png)
![image](https://user-images.githubusercontent.com/21024857/62128470-cdf97780-b2d4-11e9-8dc8-af94dc5f6fbb.png)

W pliku system.log, mam następujący komunikat:

`2019-07-30 14:21:28.8958 [error] - ERR_RECORD_NOT_FOUND||6
App\Exceptions\NoPermittedToRecord: ERR_RECORD_NOT_FOUND||6 in /var/www/html/YetiForce/modules/Users/Users.php:173
Stack trace:
#0 /var/www/html/YetiForce/modules/Vtiger/models/Record.php(675): Users->retrieveEntityInfo(6, 'Users')
#1 /var/www/html/YetiForce/modules/com_vtiger_workflow/VTJsonCondition.php(46): Vtiger_Record_Model::getInstanceById(6, Object(Users_Module_Model))
#2 /var/www/html/YetiForce/modules/com_vtiger_workflow/Workflow.php(111): VTJsonCondition->evaluate('[{"fieldname":"...', Object(HelpDesk_Record_Model))
#3 /var/www/html/YetiForce/modules/Vtiger/handlers/Workflow.php(133): Workflow->evaluate(Object(HelpDesk_Record_Model), 94027)
#4 /var/www/html/YetiForce/modules/Vtiger/handlers/Workflow.php(57): Vtiger_Workflow_Handler->performTasks(Object(App\EventHandler), Array)
#5 /var/www/html/YetiForce/app/EventHandler.php(296): Vtiger_Workflow_Handler->entityAfterSave(Object(App\EventHandler))
#6 /var/www/html/YetiForce/modules/Vtiger/models/Record.php(483): App\EventHandler->trigger('EntityAfterSave')
#7 /var/www/html/YetiForce/modules/Vtiger/actions/MassSave.php(35): Vtiger_Record_Model->save()
#8 /var/www/html/YetiForce/include/main/WebUI.php(183): Vtiger_MassSave_Action->process(Object(App\Request))
#9 /var/www/html/YetiForce/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#10 {main}
2019-07-30 14:21:28.8085 [info][application] - 
$_GET = []
$_POST = [
    '__vtrftk' => 'sid:ac0a18afb729ba22f6c9620b0662ef26c63a2180,1564489281'
    'mappingRelatedField' => '{\"projectid\":{\"Project\":{\"parent_id\":[\"linktoaccountscontacts\"]}},\"contact_id\":{\"Contacts\":{\"parent_id\":[\"parent_id\"]}},\"pssold_id\":{\"Assets\":{\"product_id\":[\"product\",\"Products\"],\"parent_id\":[\"parent_id\",\"Accounts\"]},\"OSSSoldServices\":{\"product_id\":[\"serviceid\",\"Services\"]}},\"servicecontractsid\":{\"ServiceContracts\":{\"parent_id\":[\"sc_related_to\",\"Accounts\"],\"ticketpriorities\":[\"contract_priority\"],\"contract_type\":[\"contract_type\"],\"contracts_end_date\":[\"due_date\"]}}}'
    'picklistDependency' => '[]'
    'module' => 'HelpDesk'
    'action' => 'MassSave'
    'viewname' => '161'
    'selected_ids' => '[\"94025\",\"94027\",\"94026\"]'
    'excluded_ids' => '[]'
    'search_key' => ''
    'operator' => ''
    'search_value' => ''
    'search_params' => '[[]]'
    'ticketstatus' => 'Zgłoszenie IT'
]
$_FILES = []
$_COOKIE = [
    'chat-notSendByEnter' => 'false'
    '_ga' => 'GA1.2.1201055770.1549886751'
    'prefsviewsplitter' => '195'
    'folderviewsplitter' => '300'
    'identviewsplitter' => '300'
    'addressviewsplitter' => '250'
    'addressviewsplitterd' => '200'
    'language' => 'pl'
    'mailviewsplitterv' => '165'
    'mailviewsplitter' => '205'
    'composesplitterv1' => '200'
    'composesplitterv2' => '846.4'
    'YTSID' => 'of4trkf0mg0d1h7ojjsiupqqod'
    'roundcube_sessid' => 'g87bd41h82khjrnenlgk8nouhf'
    'roundcube_sessauth' => '9e93TH41ynFlTUYvsXyA2daOiy-1564463970'
]
$_SESSION = [
    'last_activity' => 1564489288.8095
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => 'e12bd70f3c83893a78397a56425749679caae85d'
    'user_name' => 'mrzewnicki'
    'full_user_name' => 'CRM System'
    'fingerprint' => 'd520c7a8-421b-4563-b955-f5abc56b97ec'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
    ]
    'lvs' => [
        'HelpDesk' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 161
            'entityState' => 'Active'
        ]
        'Documents' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 22
            'entityState' => 'Active'
        ]
        'RecycleBin' => [
            'viewname' => ''
        ]
        'EmailTemplates' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 105
        ]
        'ServiceContracts' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 39
        ]
        'MultiCompany' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 111
        ]
        'Leads' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 1
        ]
        'Accounts' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 4
        ]
        'Partners' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 86
        ]
        'Vendors' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 27
        ]
    ]
]
$security = [
    'public_html' => 'Off'
    'display_errors' => 'On'
    'disable_functions' => 'shell_exec, exec, system, passthru'
    'Header: server' => 'Apache/2.4.29 (Ubuntu)'
]
$database = [
    'innodb_lock_wait_timeout' => '50'
]
$performance = [
    'mysqlnd.collect_statistics' => 'Off'
]`

Wcześniej podobnie objawiał się problem kiedy to pole w db było za małe na request, ta kwestia została rozwiązana w zgłoszeniu #11046 choć błąd serwera jest 406 nie 500, to czy mogą byc te kwestie powiązane?

**Comment by arek1-618** [comment]
Czy w bazie danych istnieje użytkownik o ID 6 ?
Jeśli nie to mogłoby być przyczyną tego problemu.

**Comment by mrzewnicki** [comment]
Tak istnieje i jest aktywnym użytkownikiem.

**Comment by rskrzypczak** [comment]
Sprawdź w bazie czy masz przypisany jakiś rekordy do użytkownika o ID 6 (vtiger_crmentity->smownerid lub u_yf_crmentity_showners->userid), jeżeli tak to przepisz je na innego użytkownika.
Przypuszczalnie błędnie został usunięty ten użytkownik i zostały gdzieś informacje o jego istnieniu przez to, gdy system próbuje pobrać więcej danych o tym użytkowniku wyrzuca błąd.

**Comment by mrzewnicki** [comment]
W "u_yf_crmentity_showners" nic ale w "vtiger_crmentity" 43 535 rekordów... Mogę to UPDATE'em puścić?

**Comment by rskrzypczak** [comment]
To zależy czy masz jakieś triggery, akcje workflow lub cokolwiek innego co wymusza pewne akcje na modyfikacji tego pola.
Przypuszczam jednak, że nie będzie z tym problemu, choć możesz mieć problem ze znajdowaniem rekordów w globalnej wyszukiwarce.

**Comment by mrzewnicki** [comment]
robie backup i spróbuje 😄

**Comment by mrzewnicki** [comment]
Nie mam żadnego problemu z wyszukiwaniem, ale zauważyłem że pomimo że nie mam takiego użytnikwinka o id 6 to powstałe rekordy dalej przypisują się do niego. Domyślnie ustawione mam przypisanie powstałych rekordów do grupy, czy to może być to?
