### ISSUE TITLE
[bug] Reservations on mobile devices (mobile network) not working

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11123]
checked on various phones, devices... when trying to get new record in reservations module, it just keep spinning after saving record. What it can be?

**Comment by mariuszkrzaczkowski** [comment]
attach a screenshot and 
![github](https://user-images.githubusercontent.com/10198654/62106293-33357480-b2a5-11e9-9d6e-f15b84e94f35.jpg)
