### ISSUE TITLE
[PL][Pytanie] Dodawanie załączników do maila z CRM

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11122]
Witam,

Niedawno zgłaszałem błąd #11053  który faktycznie okazał się być spowodowany czymś innym niż początkowo sądziłem. 
1) Nie mniej jednak zastanawia mnie czy nie da się zrobić czegoś by w filtrze do wyboru załącznika były tylko te rekordy których istnienie pliku jest potwierdzone?
2) Czy da się jakoś zautomatyzować proces sprawdzania czy te pliki istnieją i je usuwać?

**Comment by bpabiszczak** [comment]
Nie rozumiem pytania.

**Comment by mrzewnicki** [comment]
W numerze zgłoszenia do którego się odnoszę jest przykład jak Konadrian pokazuje jak dodać załącznik. Żeby znaleźć odpowiedni musi pofiltrować liste. Problem w tym że u mnie jest ponad 10 tyś rekordów które mają zaznaczone "Link aktywny" kiedy wchodzę w taki rekord i sprawdzamgo ręcznie za pomocą : 
![image](https://user-images.githubusercontent.com/21024857/62105367-7b9f6300-b2a2-11e9-800f-9c108997058f.png)

Okazuje się że plik nie istnieje. WIęc pytam czy nie mozna procesu sprawdzania jakoś zautomatyzować bo nie będę teraz 10tyś rekordów ręcznie klikał..
