### ISSUE TITLE
[bug] cannot add a service to Quotes, Calculations, etc. when Product module is disabled

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#11133]
Hi,

We are not using product at all as we only sell services.
So, I have disabled product module via module manager.
But now I can't add any service to quotes, invoices, calculations, etc.
See screenshot attached.
The issue is reproductible on YF public demo.
As a temporary workaround, I've reactivate product module but I would like to get rid of it because it's totally useless for us.
Regards,

![issue_product_module_disabled](https://user-images.githubusercontent.com/2930560/62133452-161d9780-b2df-11e9-999c-4e344c22895a.jpg)

**Comment by davide-alghi** [comment]
Hi apcloic,
maybe you miss a step. Products module is referenced from many modules and if you disable it you will encounter many issues. Please re-enable it and watch the video. If you don't use products, simply hide it by BE:Permission:Profile settings.

PS you have to arrange all modules with reference to Products module: quotes, invoices, calculations, etc

![quote-no-prods](https://user-images.githubusercontent.com/48508691/62138795-88df4080-b2e8-11e9-840f-f339736fc6ee.gif)

**Comment by apcloic** [comment]
>Please re-enable it and watch the video. If you don't use products, simply hide it by >BE:Permission:Profile settings.

@davide-alghi 
Thank you very much for your help, I will follow your advice and use the "hide" feature.
That said, I still think it should have been possible to fully disable the module for service-only company like us but no big deal, for sure ;)

**Comment by davide-alghi** [comment]
apcloic,
you can disable Products module, but you have to arrange other modules with reference to Products module before disable it. I said you to re-enable Products to quickly avoid strange behaviours.
The Products module can be fully disabled if you take overall care.

:thumbsup:
