### ISSUE TITLE
[bug] unable to save records on inventory modules like invoices, quotes, etc.

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#11135]
Hi,
I'm using YF 5.1 on a dedicated VPS.
My system had been migrated a few weeks ago from 4.4 to 5.1
Today, I've just started using inventory module, service module, product, etc. but whatever module I am using (Invoice, Quotes, Calculations, ...), I'm unable to save records because of the following error :

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'crmid' in 'field list' Failed to prepare SQL: INSERT INTO `u_yf_ssingleorders_inventory` (`discountmode`, `taxmode`, `currency`, `currencyparam`, `name`, `unit`, `subunit`, `qty`, `price`, `total`, `discount`, `discountparam`, `net`, `purchase`, `marginp`, `margin`, `tax`, `taxparam`, `gross`, `comment1`, `crmid`) VALUES (:qp0, :qp1, :qp2, :qp3, :qp4, :qp5, :qp6, :qp7, :qp8, :qp9, :qp10, :qp11, :qp12, :qp13, :qp14, :qp15, :qp16, :qp17, :qp18, :qp19, :qp20)

Error log :

2019-07-30 19:23:55.4212 [error] - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'crmid' in 'field list'
Failed to prepare SQL: INSERT INTO `u_yf_ssingleorders_inventory` (`discountmode`, `taxmode`, `currency`, `currencyparam`, `name`, `unit`, `subunit`, `qty`, `price`, `total`, `discount`, `discountparam`, `net`, `purchase`, `marginp`, `margin`, `tax`, `taxparam`, `gross`, `comment1`, `crmid`) VALUES (:qp0, :qp1, :qp2, :qp3, :qp4, :qp5, :qp6, :qp7, :qp8, :qp9, :qp10, :qp11, :qp12, :qp13, :qp14, :qp15, :qp16, :qp17, :qp18, :qp19, :qp20)
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'crmid' in 'field list' in /var/www/html/yfcrmdev/vendor/yetiforce/yii2/db/Command.php:259
Stack trace:
#0 /var/www/html/yfcrmdev/vendor/yetiforce/yii2/db/Command.php(259): PDO->prepare('INSERT INTO `u_...')
#1 /var/www/html/yfcrmdev/vendor/yetiforce/yii2/db/Command.php(1070): yii\db\Command->prepare(false)
#2 /var/www/html/yfcrmdev/modules/Vtiger/models/Record.php(1122): yii\db\Command->execute()
#3 /var/www/html/yfcrmdev/modules/Vtiger/models/Record.php(513): Vtiger_Record_Model->saveInventoryData()
#4 /var/www/html/yfcrmdev/modules/Vtiger/models/Record.php(471): Vtiger_Record_Model->saveToDb()
#5 /var/www/html/yfcrmdev/modules/Vtiger/actions/Save.php(88): Vtiger_Record_Model->save()
#6 /var/www/html/yfcrmdev/modules/Vtiger/actions/Save.php(61): Vtiger_Save_Action->saveRecord(Object(App\Request))
#7 /var/www/html/yfcrmdev/include/main/WebUI.php(183): Vtiger_Save_Action->process(Object(App\Request))
#8 /var/www/html/yfcrmdev/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#9 {main}

Thanks to @mlorencik, I've been able to solve the issue by renaming all id fields to crmid ((in u_yf_finvoice_inventory, u_yf_squoteenquiries_inventory, etc.) like suggested in the following issue : 
https://github.com/YetiForceCompany/YetiForceCRM/issues/9838

So it looks like there is an issue regarding inventory modules and migrated systems 4.4->5.1
If there is a better workaround, let us know.
Regards,

**Comment by vovpff** [comment]
What means merged from 4.4 to 5.1???

**Comment by rskrzypczak** [comment]
Each table with the '_inventory' suffix should include in its structure a 'crmid' column, you don't have it, which means that your update process was faulty.
Remember that updates should be performed gradually, that means 4.4 => 5.0 => 5.1

**Comment by apcloic** [comment]
> What means merged from 4.4 to 5.1???

I think you didn't read properly, I've written "migrated" not merged

**Comment by apcloic** [comment]
> Each table with the '_inventory' suffix should include in its structure a 'crmid' column, you don't have it, which means that your update process was faulty.

yes, however I've just followed the official update process

> Remember that updates should be performed gradually, that means 4.4 => 5.0 => 5.1
yes, this is exactly what I've done.
