### ISSUE TITLE
[Feature] I have a landing page and i need to link the lead form with yeti crm

### ISSUE THREAD

**Issue by islamnasar** [YetiForceCompany/YetiForceCRM#11132]
## 🚀 feature request

please i need help in this:
I have a landing page and i need to link the lead form with yeti crm 
i had created a web service application key and web service user
i am trying with api reset through postman
{"status":0,"error":{"message":"Invalid data access","code":401}}
this error display to me

**Comment by davide-alghi** [comment]
Hi islamnasar,
try searching with the following links. Maybe your problem has already been issued.


https://github.com/YetiForceCompany/YetiForceCRM/issues/10675

https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+postman

https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST

https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+api+OR+rest+OR+Webservice+

**Comment by mariuszkrzaczkowski** [comment]
For security reasons, photos with access have been removed

**Comment by islamnasar** [comment]
I need a developer to reset api and link webform to crm
Any recommendation ?

**Comment by bpabiszczak** [comment]
sla@yetiforce.com
