### ISSUE TITLE
[Question] Yeti as a POS - steps          

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11136]
Has yeti been implemented as a POS? What are the chances?

**Comment by bpabiszczak** [comment]
Yes, in the basic version.

**Comment by waran70** [comment]
Guys here thinking of connecting scanner to YF. Honestly, if POS can be implemented, it could be a kick to users base... or am I wrong?

**Comment by bpabiszczak** [comment]
You can test here: https://gitdeveloper.yetiforce.com/portal/index.php?module=Products&view=Tree [draw]
