### ISSUE TITLE
[Security] Review Changes in Records

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11146]
Kind of misleading information. In fact it erasing information related to changes in record. "Review" got a bit different meaning. It should be called "Delete Changes History" or similar..

**Comment by paula-w** [comment]
Thanks a lot for the suggestion! You're absolutely right, it was misleading. We decided to change the translation to "Mark updates as reviewed" https://github.com/YetiForceCompany/YetiForceCRM/commit/f42007be7824d5eaf35aefbef6bd6a152a2043ea
Let us know if you stumble upon any other confusing translations and we'll look into them. Thanks again!
