### ISSUE TITLE
[PL][Pytanie] Maile wewnętrzne

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11141]
Witam,

W widżecie maili w podsumowaniu zgłoszenia można filtrować wiadomości. Interesuje mnie typ "Wewnętrzne", czy można jakoś ustawić by zawsze komunikacja wewnątrz mojej domeny była traktowana jako wewnętrzna? Bo póki co widzi maile wymieniane między pracownikami w tym zgłoszeniu jako zewnętrzne.
![image](https://user-images.githubusercontent.com/21024857/62202706-158e0b00-b38a-11e9-8e69-425658cdfe91.png)

**Comment by bpabiszczak** [comment]
Powinien widzieć jako wewnętrzne.... sprawdziłem u siebie w CRM i mi pokazuje poprawnie. Trzeba by napisać jak wywołać błąd razem z opisem konfiguracji.

**Comment by mrzewnicki** [comment]
Może to nie jest jeszcze błąd a brak tej konfiguracji. Gdzie mogę ustawić swoją domenę?
Któraś z tych opcji?
![image](https://user-images.githubusercontent.com/21024857/62206600-77eb0980-b392-11e9-9c18-412220816b5d.png)

**Comment by bpabiszczak** [comment]
to nie ma znaczenia, on wewnętrzne określa na podstawie maili na użytkownikach, jeżeli to jest od user-a do user-a i nie ma nikogo "obcego" wówczas określa to jako wewnętrzna korespondencja.

**Comment by mrzewnicki** [comment]
OK, to chyba wiem w czym jest błąd. Bo nie każdy z firmy ma jeszcze konto w CRM więc jeśli jest prowadzona korespondencja z kimś kto nie ma usera to jest jako zewnętrza. Dzięki za wyjaśnienie.

**Comment by bpabiszczak** [comment]
Polecam się :P
