### ISSUE TITLE
[bug]  Make Employees and associate to a Departments

### ISSUE THREAD

**Issue by lzuccagnoli** [YetiForceCompany/YetiForceCRM#11152]
Good morning, it's normal that if I put an employee in a department, I find the record inside the department itself, but if I create an employee inside employees and associate it with a department, inside the department can't I find it among the employees? I also did a test on the online demo with Test001 and Test002.

Thank you

**Comment by davide-alghi** [comment]
Hi lzuccagnoli,
**relation tabs**, in detail view, can show you different types of relation. There are several relation types.

 Actually the relation (in tab) is defined by a function name in vtiger_relatedlists table:
- getDependentsList
- getActivities
- getEmails
- getAttachments *
- getProducts
- getCampaigns
- getProductPricebooks
- getLeads
- getAccounts
- getPricebookProducts
- getCampaignsRecords
- getRelatedList *
- getPricebookServices
- getServicePricebooks
- getRecordToMails
- getOsstimecontrol
- getManyToMany *

\* editable via BE:Standard modules > Edit fields

About Employees tab in Departments module, the relation is define by **getRelatedList**: this function looks for relation into **vtiger_crmentityrel** table: a record is added when you add / select an employee from Department.

Instead, when you set the Department (**Organization structure**) on employee creation, you are defining an 1:M relation. To get this relation in Departments' (module name is MultiCompany) Employees tab, it **had** to be used another relation function: getDependentsList. getDependentsList function lists, in relation tab, all entities with a relation field (like Organization structure field is)

It's not a bug. it's behavior so defined.

**Comment by lzuccagnoli** [comment]
thank you very much, @davide-alghi, for the accurate explanation. 
I've change the relationship in mysql table on getDependentsList for my business use..

**Comment by davide-alghi** [comment]
:thumbsup:
to complete the change, you should remove **Select** action from there
