### ISSUE TITLE
[bug] empty value for calendar in notifications

### ISSUE THREAD

**Issue by gerripeach** [YetiForceCompany/YetiForceCRM#11158]
# 🐞 bug report

### ⁉️ Describe the bug
Calendar (Events/ToDos) are not displayed in the Notification tab.
 

### 🔥 How to trigger the error
1. Create a Workflow
2. Set some reprucucable trigger (eg. on change)
3. Add a Task (Notification)
4. trigger the workflow
5. look at the notification

### 👎 Actual Behavior
Calendar Field **In Template:** 
```
							{if $RECORD->get('link')}
								{\App\Language::translateSingularModuleName(\App\Record::getType($RECORD->get('link')))}:&nbsp;{$RECORD->getDisplayValue('link')}
							{/if}
```

1. is **always empty**
2. displays **always to do** (should display Meeting or Call?)

### 👍 Expected Behavior
a link to the linked calendar record should be displayed

### 👷 Testing 
- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
* [X] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
I simplified the call to the function  `getDisplayValue` by calling it before the renderer.

```
Vtiger_ReferenceLink_UIType->getDisplayValue (/var/www/Yeti/modules/Vtiger/uitypes/Reference.php:79)
Vtiger_Field_Model->getDisplayValue (/var/www/Yeti/modules/Vtiger/models/Field.php:190)
Notification_Record_Model->getDisplayValue (/var/www/Yeti/modules/Vtiger/models/Record.php:375)
Notification_Reminders_View->process (/var/www/Yeti/modules/Notification/views/Reminders.php:30)
Vtiger_WebUI->process (/var/www/Yeti/include/main/WebUI.php:183)
{main} (/var/www/Yeti/index.php:50)
```

`$referenceModule = $this->getReferenceModule($value);` returns null in Refercence.php which causes the function `getDisplayValue` to return an empty string instead of the link

**Comment by adudekyeti** [comment]
Hi, it was a bug because calendar is not a hierarchy module. It can not have a link to the linked calendar record.
