### ISSUE TITLE
[Question] Updating fields from related modules in Workflow          

### ISSUE THREAD

**Issue by lucixglcx** [YetiForceCompany/YetiForceCRM#11162]
Hi there,

I'm basically a noob at yetiforce but been busting my head today with the following:
1. I set a custom field payment_days (integer) on account.
2. I want to have the Due Date of any invoice issued to that account equal to the date of creation of the invoice + the payment_days from the account.

I could set Due Date by workflow to add any number of days via add_days(issue_time, XX), I can even use XX as integer or as field value from the invoice module, but I can't seem to find any way of updating a field in the invoice from the account. 

Any ideas?

**Comment by davide-alghi** [comment]
Hi lucixglcx,
I'm sure you are using **Update related record** task type.
Update related record task type:

- is asynchronous https://github.com/YetiForceCompany/YetiForceCRM/blob/f3835d1735f86958fcdfdb5bfb9297503549b285/modules/com_vtiger_workflow/tasks/VTUpdateRelatedFieldTask.php#L13
- you **can set** related module field value but you **cannot get** related module field value

Mt suggestion is:
1) create equal integer field (payment_days) into Accounts and FInvoices modules
2) set days value into Accounts entity instance
3) create a workflow to copy days from Accounts to FInvoice
4) create another workflow to set FInvoice-DueDate = FInvoice-CreationDate + FInvoiceDays

In this way you can set read-only the Due Date FInvoices field: the system will provide to set the date

Below an example. Create the two fields showed into image and upload the workflows : 
[workflows.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/3470675/workflows.zip)
 

![addDaystoDueDate](https://user-images.githubusercontent.com/48508691/62516410-54f2a680-b825-11e9-9a5f-cee802c48f6f.png)

**Comment by lucixglcx** [comment]
Thanks Davide, 
I appreciate the solution but it doesn't work for me. The reason is when an invoice is created it has to be sent out to the customer, but there's no workflow to update the payment_days on the new invoice on invoice creation. Your solution updates the payment_days field at certain hours because the workflow is set on the accounts module.

In my humble opinion, the easiest way would have been to allow in the workflow to update a field with expression like:
payment_days = $(relatedRecord : accountid|payment_days|Accounts)$

That would be a great feature.

I solved my problem by adding a trigger in the database. I'm leaving my solution here in case anyone else needs it:


DELIMITER $$
CREATE TRIGGER `payment_days` BEFORE INSERT ON `u_yf_finvoice` FOR EACH ROW BEGIN

    DECLARE pdays INT(11);
    DECLARE pdate date;
    SELECT payment_days INTO pdays FROM vtiger_account where accountid=NEW.accountid;
    SET NEW.payment_days = pdays;
    SELECT DATE_ADD(NEW.issue_time, INTERVAL pdays DAY)into pdate ; 
    SET NEW.paymentdate = pdate;


END
$$
DELIMITER ;
