### ISSUE TITLE
[PL][Pytanie] Tworzenie pola liczbowe w module

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11164]
WItam. Pracuje na wersji 5.1, czy można utworzyć pole liczbowe (całkowite) o wielkości większej niż 255? A jeśli tak to jak mogę to zrobić? 
Podana w polu liczba to tylko przykład, ale potrzebuję większej wartości w polu niż 255.
![image](https://user-images.githubusercontent.com/21024857/62372341-858dc400-b537-11e9-90cf-8457a0c28d1e.png)

**Comment by davide-alghi** [comment]
![Schermata da 2019-08-02 17-37-36](https://user-images.githubusercontent.com/48508691/62381869-b5939200-b54c-11e9-83b9-d4c0a68f5a7f.png)
![Schermata da 2019-08-02 17-38-20](https://user-images.githubusercontent.com/48508691/62381873-b75d5580-b54c-11e9-86b1-8befdfc0021e.png)
