### ISSUE TITLE
[PL][Pytanie] Relacje załączników

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11185]
Witam,
Pracuję na wersji 5.1. Stworzyłem sobie własny moduł i chciałbym do niego umieścić relacje załączników co zrobiłem. Zazwyczaj gdy dodaje taką relację, to pojawia się w db tabliica u_yf_[nazwa modułu]_[nazwa modułu]. Tutaj jednak nie pojawiła się taka tablica a potrzebuję mieć do niej dostęp. 
W tablicach attachments ani seattachmentsrel też nie znalazłem takiej relacji.

Jak może nazywać się taka tablica (jeśli tworzy się nowa)? lub W jakiej tablicy jest zawarta ta relacja?

**Comment by rskrzypczak** [comment]
vtiger_senotesrel - jest tylko jedna tablica dla relacji ze wszystkimi modułami.

**Comment by mrzewnicki** [comment]
Dzięki!!
