### ISSUE TITLE
[Feature] Mentions back links

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#11187]
### Describe the solution you'd like

Mentions is very cool feature in system because you can add simple link to another one record inside WYSYWIG field. But there no ability to understand is it current record was mentioned somewhere.

### Is your feature request related to a problem? Please describe.

There is no problems. Just request for useful feature.

### Describe alternatives you've considered

No alternatives.

### Additional context

This feature called as "backlinks" in mediawiki wiki engine. You can check wikipedia for understanding.

**Comment by paula-w** [comment]
Right now mentions work in the chat.

**Comment by vovpff** [comment]
@paula-w how your solution related with requested feature ? I'm asked for backlinks for usual mdules what helps to understand where record was mentioned...
