### ISSUE TITLE
[PL][Pytanie] Zmiana statusu po odpowiedzi

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11202]
Witam, przy niektórych rekordach od czasu aktualizacji do 5.1 z 5.0 ustawia się status:
![image](https://user-images.githubusercontent.com/21024857/62544584-57bebd00-b860-11e9-84fe-e496b1807abf.png)

ale pole jest wyszarzone i nieedytowalne. Wyświetla się napisa po ang pomimo tłumaczeń w słownikach. 

Żeby odblokować taki rekord, muszę wejść w słownik statusu, i zmieniać pole "Automatyzacji"  z LBL_AUTOMATION_NO_CONCERN na LBL_AUTOMATION_OPEN wtedy jakby rekord zaciągał ustawienia słownika i normalnie można go edytować. Jeśli później pojawi się spowrotem błąd to muszę zmieć LBL_AUTOMATION_OPEN na LBL_AUTOMATION_NO_CONCERN i działa, ale przez to muszę pilnować zgłoszeń bez sensu no i userzy nie mogą edytować statusu

Logów brak w system.log i consoli.
Ma ktoś może jakiś pomysł czego to może być wina?

**Comment by rskrzypczak** [comment]
Prawdopodobnie owa wartość, która blokuje edycje rekordu nie występuje w słowniku.
Jak przypuszczam ustawiana jest wartość 'Wait for response', a powinna być 'Wait For Response'.
Mechanizm, który aktualizuję to pola nadaje mu błędną wartość.
Dlatego też ta wartość słownika nie jest przetłumaczona - nie istnieje taka etykieta.
