### ISSUE TITLE
[Question]  How can i transfer products from one storage to an other ?  

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#11209]
ok so im working on the inventory management for my business and i have a problem with transfering a quantity of product from one storage to an other... :( 

i am able to receive products (adding them to inventory)
an able to send products (subtract from inventory)

when i try  "Storage Transfer Dispatched Notes" or "Storage Turnover Notes" or "Goods Dispatched Note" or anyother modules, it only subtract product quantity from the inventory... 
why are they so many modules that all do the same thing , its not very useful... is it me that does not understand how it works, or is there a problem, does it require some coding...

How can i transfer products from one storage to an other ? 

Thank you for your help !

**Comment by vovpff** [comment]
GIN from storage1
Mapping from this GIN to IDN with empty storage
Fill storage with storage2 value
Profit?!

**Comment by maeglin4** [comment]
not sure to understand, can you tell me where do i go in admin panel to set it up ?

Standard modules / Modules – Relations
or
Standard modules / Edit fields

or elsewhere, or do i need to edit a .php file ?

**Comment by vovpff** [comment]
When I get back to my laptop I will write to you some detailed explanation!

**Comment by maeglin4** [comment]
okay thanks alot.

**Comment by vovpff** [comment]
At first you need to check do you have mapping between `Storage Transfer Received Notes` and `Storage Transfer Dispatched Notes` [here](https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95).

It there is no mapping you need to add mapping manually. This is simple process.

After that you go to `Storage Transfer Dispatched Notes` and add record with list of consumables. Accept this record and products will out from stock. After that click this button:

![image](https://user-images.githubusercontent.com/8545791/62818645-9602f780-bb52-11e9-9f61-a314feca5c37.png)

and choose `Storage Transfer Received Notes`. 

You will achieve the same list of product but in another one module. **You need to fill `Storage` field with other one storage!** When you change status of record to accepted - you turn products quantity back.

**Comment by maeglin4** [comment]
the mapping was already there by default, but when i try to generate a record i get this error message ?

![error relation](https://user-images.githubusercontent.com/45770116/62870864-5b32c800-bce8-11e9-8b28-4fafcabf4aeb.gif)

**Comment by maeglin4** [comment]
![mapping error](https://user-images.githubusercontent.com/45770116/62871320-4e62a400-bce9-11e9-87ad-d4194ca3aa98.PNG)

**Comment by vovpff** [comment]
Ver?

**Comment by maeglin4** [comment]
Yetiforce 5.1.0
PHP 7.2.21
5.5.5-10.2.26-MariaDB
mysqlnd 5.0.12-dev - 20150407

**Comment by vovpff** [comment]
Could you provide screenshot of Storage Transfer Received Notes and Storage Transfer Dispatched Notes advanced fields list?

**Comment by maeglin4** [comment]
Storage Transfer Dispatched Notes
![storage transfer dispatched notes](https://user-images.githubusercontent.com/45770116/62886909-1e77c880-bd0a-11e9-9948-d22a72a594b8.PNG)

Storage Transfer Received Notes
![storage transfer received notes](https://user-images.githubusercontent.com/45770116/62886911-1e77c880-bd0a-11e9-8315-379ec19dc2f6.PNG)

**Comment by vovpff** [comment]
Let's add to mapping No. for soufce and destination!

**Comment by maeglin4** [comment]
PERFECT !! it works , thanks alot !! :D

**Comment by vovpff** [comment]
Thats ok!
