### ISSUE TITLE
[Question] Which version of yii use Yetiforce?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#11217]
### Description

Hi,
Which version of Yii use YetiForce?
Basic template or Advanced Template ?
Yii1 or Yii2?

Thanks !

**Comment by z0lo13** [comment]
2

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/193b0acab5620451ed4b0cc8e0d90f780875a8b7/composer.lock#L3081
