### ISSUE TITLE
ERR_NOT_FOUND_FIELD_MODEL

### ISSUE THREAD

**Issue by Carolinercraig** [YetiForceCompany/YetiForceCRM#11218]
Anybody knows why I'm getting this error? My team member changed a custom field from the database end to be Unique, and this caused this error. Even though we removed the Unique from that custom field. We are still getting that error! Help!!!

**Comment by mariuszkrzaczkowski** [comment]
the error says that the field does not exist.
There is more information in the logs

**Comment by Carolinercraig** [comment]
I went to the cache/logs/phpError.log but nothing is there. I ensured
display errors in on in the htaccess.  is there anywhere else I can check
for logs.
How to fix this issue if the field doesnt exist? We readded the field and
it still gave the error.

**Comment by davide-alghi** [comment]
Hi Carolinercraig,
maybe your deleted field name is into module default filter: check into vtiger_cvcolumnlist table for that module name; if deleted field name is there, remove relative record and try again to load module ListView.

**Comment by rskrzypczak** [comment]
Enable recording of logs and send us.
https://yetiforce.com/pl/component/zoo/item/debugging?highlight=WyJsb2dzIl0=
I think your team member changed something more :)

**Comment by Carolinercraig** [comment]
Thanks guys! I had indeed add the debugging to htaccess to allow logs but
nothing showed up there. However the suggestion to check the
vtiger_cvcolumnlist did the trick! Thank you sooooo much!

**Comment by Carolinercraig** [comment]
I was able to view the project list but when I clicked the project, I now got another error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vtiger_project.parentid' in 'field list' Failed to prepare SQL:  

I have checked the database and parentid isnt there thus why the sql failed.

**Comment by davide-alghi** [comment]
that is another problem :(
please upload screenshot of vtiger_project structure from your PhpMyAdmin (like in below image)

![Schermata da 2019-08-09 16-02-08](https://user-images.githubusercontent.com/48508691/62785376-d0bc4f80-bac0-11e9-8715-4d06ed27283f.png)


then, always from PhpMyAdmin, exec this SELECT

SELECT * FROM `vtiger_field` WHERE `tabid` = 43

upload screenshot of results: both pages (like in below images)

![Schermata da 2019-08-09 16-10-18](https://user-images.githubusercontent.com/48508691/62785508-0e20dd00-bac1-11e9-881c-74ecdc513a9e.png)
![Schermata da 2019-08-09 16-10-26](https://user-images.githubusercontent.com/48508691/62785509-0e20dd00-bac1-11e9-9891-fa5883200237.png)

**Comment by Carolinercraig** [comment]
Hi,

I went into the database and added the missing field 'parentid' and now I am able to see the project information, add new project, and edit. I also tested adding new tasks and milestones and it all seem to be working. I know the team member didnt removed the parentid from the project table, so this is very puzzling as to why it happened in the first place.

![image](https://user-images.githubusercontent.com/14927782/62786406-bd3cc480-ba7f-11e9-8884-1b90d17c96ef.png)

I ran the select statement:

![image](https://user-images.githubusercontent.com/14927782/62786478-e8271880-ba7f-11e9-8fa6-b091fa3c4165.png)

**Comment by davide-alghi** [comment]
it's very strange.
anyway ... check from my 1st screenshot if parentid column is equal to your added one

bye

**Comment by Carolinercraig** [comment]
Thank you, I have cross checked. I'd like to thank this community for all your help. I REALLY appreciate it!

**Comment by Akaki-1991** [comment]
hello,

i have this problem :

App\Exceptions\AppException: ERR_NOT_FOUND_FIELD_MODEL|which_module in /var/www/html/app/QueryGenerator.php:1151
Stack trace:
#0 /var/www/html/app/QueryGenerator.php(1065): App\QueryGenerator->getQueryField('which_module')
#1 /var/www/html/app/QueryGenerator.php(1116): App\QueryGenerator->getCondition('which_module', '\xE1\x83\x93\xE1\x83\x94\xE1\x83\xA4\xE1\x83\x98\xE1\x83\xAA...', 'e', false)
#2 /var/www/html/modules/com_vtiger_workflow/WorkFlowScheduler.php(194): App\QueryGenerator->addCondition('which_module', '\xE1\x83\x93\xE1\x83\x94\xE1\x83\xA4\xE1\x83\x98\xE1\x83\xAA...', 'e', true)
#3 /var/www/html/modules/com_vtiger_workflow/WorkFlowScheduler.php(49): WorkFlowScheduler->addWorkflowConditionsToQueryGenerator(Object(App\QueryGenerator), Array)
#4 /var/www/html/modules/com_vtiger_workflow/WorkFlowScheduler.php(62): WorkFlowScheduler->getWorkflowQuery(Object(Workflow))
#5 /var/www/html/modules/com_vtiger_workflow/WorkFlowScheduler.php(89): WorkFlowScheduler->getEligibleWorkflowRecords(Object(Workflow))
#6 /var/www/html/modules/Vtiger/crons/Workflow.php(30): WorkFlowScheduler->queueScheduledWorkflowTasks()
#7 /var/www/html/cron.php(98): Vtiger_Workflow_Cron->process()
#8 {main}
-----------
