### ISSUE TITLE
error Create New Record (contacts) not working but working the quick create

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1122]
when i am trying to create new record from contact list view
i am getting this error
![error](https://cloud.githubusercontent.com/assets/6897502/8272729/fc93e4b2-1856-11e5-8315-e79eee536542.jpg)
but when i am trying to create new record contact from QUICK CREATE its working...

any suggestions?

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by eptapsyxos** [comment]
Ok i read the documentation.
i restored the mysql database on previous save date,and worked again.
something crashed it.
on test site works normal.

thank you
