### ISSUE TITLE
[bug] Workflow, mail - don't stop send

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#11226]
Workflow - Wysyłka maila.
Witam, mam problem z Workflow,
Ręczne wywołanie - wyślij maila... z szablonu 
Przychodzi mail z każdym działaniem crona. Zadania usunięte , w bazie także ich nie widać... nie mogę przerwać wysyłki - jedynie jak wyłączę crona. 
Czy jest jakiś szybki sposób na rozwiązanie problemu ? 

Wersja 5.1

**Comment by zimart** [comment]
Dodam, że po ponownym włączeniu crona .. wysyłka się wznawia. Bardzo proszę o pomoc - gdzie ewentualnie szukać problemu.

**Comment by rskrzypczak** [comment]
Sprawdź czy nie masz już jakiś maili oczekujących do wysłania.
![image](https://user-images.githubusercontent.com/10221999/62774441-fcc9d780-baa4-11e9-8e11-63e9e145a634.png)

**Comment by zimart** [comment]
Nie miałem... nie zlokalizowałem problemu... ani na serwerze ani w systemie -  przywróciłem kopię zapasową..
