### ISSUE TITLE
[Feature]  Possibility of integrating a successful login notification?

### ISSUE THREAD

**Issue by ojimenezt** [YetiForceCompany/YetiForceCRM#11228]
As a suggestion, it would be necessary to send a notification email to the user when the session is successful.

This need arises as an explicit requirement of the password security policies of the Information Security Management System.

Additionally, the user activity history, seen from the administrator panel, would be required.

**Comment by mariuszkrzaczkowski** [comment]
look at this https://gitdeveloper.yetiforce.com/index.php?module=LoginHistory&parent=Settings&view=List&block=14&fieldid=7

**Comment by ojimenezt** [comment]
> look at this https://gitdeveloper.yetiforce.com/index.php?module=LoginHistory&parent=Settings&view=List&block=14&fieldid=7


Thanks for the reply. however, I was not referring to the access history.

The requirement is to have a history visible from the administrator of the actions or activities that users perform in the system, similar to the option "Recently viewed pages" that users have from their profile.

Second, an option to notify users by email when they access the system successfully.

**Comment by mariuszkrzaczkowski** [comment]
> The requirement is to have a history visible from the administrator of the actions or activities that users perform in the system, similar to the option "Recently viewed pages" that users have from their profile.

We have a module called Analyzer that shows you everything a user does, even in real time. Right now it only records a part of the user and what the user does in a record, but in the future it will record much more. The module will be available for purchase in our new store. 

> Second, an option to notify users by email when they access the system successfully.

You can achieve that by using workflow

**Comment by ojimenezt** [comment]
> We have a module called Analyzer that shows you everything a user does, even in real time. Right now it only records a part of the user and what the user does in a record, but in the future it will record much more. The module will be available for purchase in our new store.

Excellent news, the faster the better. It is a necessary module to comply with the parameters and compliance with security policies. In Spain it is a mandatory criterion for companies certified in the National Security Scheme (ENS) of medium level.

> You can achieve that by using workflow

I am reviewing them, but I have not yet obtained it, I have seen the execution of tasks and I have been called a lot by the option "Invoke custom function task", this was executed when creating a user. However, in the user module there is no parameter that allows the event to be carried out to notify if the user has logged in or not.

If you can guide me a little, I would appreciate it.

* Another recommendation that is generated from the security policies for passwords is to limit that they are not equal to the previous 5.

**Comment by mariuszkrzaczkowski** [comment]
> * Another recommendation that is generated from the security policies for passwords is to limit that they are not equal to the previous 5.

The system can already do that, however, it doesn't verify only the last 5 passwords, but all passwords ever changed.

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/91375914-2ecaea80-e81c-11ea-9502-c79f0ca3b8c0.png)

**Comment by bpabiszczak** [comment]
An e-mail notification can be added, but it requires a programmer [2-4h]
