### ISSUE TITLE
[Question] adding filter to Selection Popup

### ISSUE THREAD

**Issue by bartonglen** [YetiForceCompany/YetiForceCRM#11223]
For Version 5.1

Hi All,

Does anyone know, how to adding or apply filter for selection popup record ?

Thanks,
Barton

**Comment by vovpff** [comment]
What you mean???

**Comment by bartonglen** [comment]
When we : create a custom field --->  select field type : Related field 1:M, and for the module that we had select = Product module (as sample).

Currently when go to search selection for product : by default the selection popup all record. in this case I would like just pop up only the record with stock > 0 ( I would like filter it). 

My question : can set set the default popup selection list for product only for the stock > 0 as default.

**Comment by vovpff** [comment]
I'm not sure what this is possible. Wait some time. Maybe somebody post solution.

**Comment by mariuszkrzaczkowski** [comment]
This can only be done with code changes
