### ISSUE TITLE
CKeditor and paragraph format

### ISSUE THREAD

**Issue by Luxx99** [YetiForceCompany/YetiForceCRM#11229]
Hi all,
I'm using YF 5.1 and I noticed a weird thing. 

Editing a text field, and applying the paragraph format, the only choices available are Heading1/2/3. The Heading4/5/6 are missing. I attach a printscreen.

Someone can please tell me how to add/show them?
Thank you
L

![ckeditor](https://user-images.githubusercontent.com/23698008/62777275-5504d780-baad-11e9-869b-e21255e4845a.jpg)

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/62998734-bab9e080-be6c-11e9-8a03-e131e420d9ae.png)
