### ISSUE TITLE
[bug][feature] switch user - priviledges

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11239]
Switch User function - At the moment while admin switch to user with limited privileges (such inability to remove record)  the switched account can still perform operation assigned to Admin user.
For the testing and security purposed it should not be allowed. System should switch completely to the selected user (with all permissions and limitations) except ability to switch back to itself. 
Am I right?

xx

**Comment by bpabiszczak** [comment]
Record a video showing the error, in my opinion it works the way you want it to work.

**Comment by z0lo13** [comment]
@waran70 

in my system i have 1. Admin and 2. Users

if i switch from admin to user i cant access same functionality if i would be when logged in under Admin.

Admin 
![изображение](https://user-images.githubusercontent.com/23143958/62902961-37df3b80-bd2f-11e9-8f7b-d4914182e5cf.png)

User
![изображение](https://user-images.githubusercontent.com/23143958/62902950-30b82d80-bd2f-11e9-9243-6050b0e3178a.png)

I would say you need to provide us with more details
