### ISSUE TITLE
mail system warnings

### ISSUE THREAD

**Issue by LOCOSP** [YetiForceCompany/YetiForceCRM#11230]
Hi,
we are using the newest stable version of YF, and we have made a lot of effort to make our configuration spotless, so it happened.
Now we are getting system warning via email and we have no idea why, because all should be fine.

## cron.sh

```
export CRM_ROOT_DIR=`dirname "$0"`/..
export USE_PHP="php -c /etc/php/7.2/apache2/php.ini"
#export USE_PHP=/usr/local/php53/bin/php
#export USE_PHP=/usr/local/php56/bin/php56

cd $CRM_ROOT_DIR
# TO RUN ALL CORN JOBS
$USE_PHP -f cron.php
```
## mail content
```
Server configuration

Server configuration was not set properly. There may be problems with the system, or the data entered may be damaged or deleted. More information can be found in the article Web server requirements at yetiforce.com. Detected problems:

Stability:
  error_reporting = 'cron: E_ERROR | E_WARNING | E_PARSE | E_NOTICE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_USER_ERROR | E_USER_WARNING | E_USER_NOTICE (22527)' (Recommended: 'E_ALL & ~E_NOTICE')
  default_socket_timeout = 'cron: 60' (Recommended: '600')
  short_open_tag = 'cron: Off' (Recommended: 'On')
  post_max_size = 'cron: 8.00 MB' (Recommended: '50 MB')
  upload_max_filesize = 'cron: 2.00 MB' (Recommended: '100 MB')
  max_input_vars = 'cron: 1000' (Recommended: '10000')
  session.gc_probability = 'cron: 0' (Recommended: '1')
  auto_detect_line_endings = 'cron: Off' (Recommended: 'On')

Performance:
  opcache.enable_cli = 'cron: Off' (Recommended: 'On')
  opcache.max_accelerated_files = 'cron: 10000' (Recommended: '40000')
  opcache.interned_strings_buffer = 'cron: 8' (Recommended: '100')
  opcache.revalidate_freq = 'cron: 2' (Recommended: '30')
  realpath_cache_ttl = 'cron: 120' (Recommended: '600')
  mysqlnd.collect_statistics = 'cron: On' (Recommended: 'Off')
```
And please take a look on screenshots, all good excluding ssl and headers (it's cosmetics).

Thank You in advance ..

![yf01](https://user-images.githubusercontent.com/4149309/62779797-787f5080-bab4-11e9-9193-94cbbab1bc72.png)
![yf02](https://user-images.githubusercontent.com/4149309/62779798-7917e700-bab4-11e9-816e-22af3df5bb3e.png)
![yf03](https://user-images.githubusercontent.com/4149309/62779800-7917e700-bab4-11e9-9945-c1194fc0b12a.png)
![yf05](https://user-images.githubusercontent.com/4149309/62779801-7917e700-bab4-11e9-8f8c-5631597af62e.png)

**Comment by davide-alghi** [comment]
Hi LOCOSP,
the php.ini into your configuration is wrong.
![62779801-7917e700-bab4-11e9-8f8c-5631597af62e](https://user-images.githubusercontent.com/48508691/62807248-34f90680-baf5-11e9-9d81-21f957ec3efe.png)

You are forcing CLI to use Apache php.ini: CLI has its php.ini (```/etc/php/7.2/cli/php.ini```). Why do you impose to CLI to use Apache php.ini?

Remove ```-c /etc/php/7.2/apache2/php.ini``` option from cron.sh.

Wait next CRON execution and, probably, you'll see that your CLI is out of YF requirements, like in warning email.

**Comment by stevenbouillon** [comment]
If your email isn't scanning then I've found it much easier to delete the mail identity and re-add. The mail scanner doesn't allow me to change the folders after I've initially set them up. 

David's response should fix your issue though.

**Comment by LOCOSP** [comment]
@davide-alghi Thank You for reply, one more question. Should I leave it blank or point to .../cli/php.ini ?

**Comment by vovpff** [comment]
In Ubuntu 18.04 primary php version is 5.6.

I has additional versions of phph and use `export USE_PHP=php7.3` for php 7.3

This depends of your system. And you do not need to fill full path to php.ini

**Comment by stevenbouillon** [comment]
Just point at whatever cli/php.ini you want cron to use.

**Comment by mariuszkrzaczkowski** [comment]
it's important for CLI to have the same privileges as WWW
