### ISSUE TITLE
How to meet the php-requirements for "HTTP methods"?

### ISSUE THREAD

**Issue by e-andrianov** [YetiForceCompany/YetiForceCRM#11234]
I am trying to intall YetiForce 5.1.0 on Opensuse 15.2 server (PHP7, Apache2.4) and cann't understand how I have to make settings to meet the recommended php-requirements for "HTTP methods" like GET, POST, PUT, OPTIONS, PATCH, PROPFIND, REPORT, LOCK, DELETE, COPY, MOVE ?
![2019-08-09 19_41_58-YetiForce](https://user-images.githubusercontent.com/53948238/62794956-2521f800-bade-11e9-9a01-383bdf527737.png)

**Comment by mariuszkrzaczkowski** [comment]
This is configured in the apache configuration

**Comment by z0lo13** [comment]
@e-andrianov 
in httpd.conf

<Location "*ADJUST TO YOUR SERVER">
   AllowMethods GET POST PUT OPTIONS PATCH PROPFIND REPORT LOCK DELETE COPY MOVE
   Require all granted
</Location>

**Comment by e-andrianov** [comment]
I put to the httpd.conf and to the conf-file of my virtual host next lines:

<Location "/srv/www/htdocs/crm.it24x365.ru">
    AllowMethods GET POST PUT OPTIONS PATCH PROPFIND REPORT LOCK DELETE COPY MOVE
    Require all granted
</Location>

but it had no matter.

**Comment by z0lo13** [comment]
@e-andrianov try <Location "/">
also restart the httpd

or

you can also try modifying vhost for the user

**Comment by e-andrianov** [comment]
Thank you for support. Possible something is wrong in my server installation.
