### ISSUE TITLE
6 months on Crowdin

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#11243]
It’s been **6 months** since we joined Crowdin! Thank you so much for your commitment to translating YetiForce CRM.
We would like to seize this opportunity to reflect on our efforts.
Check out what we’ve managed to achieve so far!
![crowdin_-_infografika_en](https://user-images.githubusercontent.com/13310141/62861646-6eec2780-bd04-11e9-9779-b661b32f1c83.png)

**Comment by maeglin4** [comment]
i am proud to help to translate to french :) 

good job to all the Yetiforce Team you are all awsome !!

**Comment by elvissaba** [comment]
I finished complete and consistent YF language in 7 days. Awesome platform.
