### ISSUE TITLE
[Question]  Quick add in field         

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11247]
Sniffing around and dunno still how to make quick-add in field (see attachment) so I can add invoice right from payments-in. May I have a clue on it?

![Screenshot_2019-08-13 Payments in Create](https://user-images.githubusercontent.com/6852348/62903470-fa110000-bd8c-11e9-9673-ae616ae1b784.png)

**Comment by waran70** [comment]
OK Got it - difference between advanced and basic module,... however, it will be helpful to allow create record of advanced module without line items. Some operations can be significantly speed up... 
Waiting for coments

**Comment by bpabiszczak** [comment]
Unfortunately, this functionality has currently low priority.
