### ISSUE TITLE
[PL][bug] Niedozwolona liczba znaków

### ISSUE THREAD

**Issue by yotuze** [YetiForceCompany/YetiForceCRM#11258]
### Description

Witam,
Stworzyłem nowe pole słownikowe wielokrotnego wyboru ale chcąc dodać kolejne wartości już po stworzeniu dostaje błąd "Niedozwolona liczba znaków". Jak można to naprawić? To jakiś błąd czy trzeba coś ustawić? Problem jest tylko z tym nowym polem, w innych można kolejne wartości dodawać. 

Pozdrawiam

![blad-crm](https://user-images.githubusercontent.com/6560221/62919458-043df900-bda3-11e9-8e87-56f85a99fe10.png)

**Comment by bpabiszczak** [comment]
Pewnie przy zakładaniu pola coś poszło nie tak, albo źle zostało utworzone. Nagraj filmik jak tworzysz pole i jak dodajesz wartość na gitdeveloper.yetiforce.com. Wówczas możemy zdiagnozować czy problem występuję. Klienci mający wsparcie SLA mogą takie problemy zgłaszać bezpośrednio na maila i sprawdzamy to wówczas bezpośrednio na serwerze.

**Comment by epsilonsc** [comment]
W zależności od typu pola procedura moze sie różnić ale jeśli chodzi o pole tekstowe to należy rozszerzyć długość kolumny (Wykonać ALTER'a) oraz dla tego pola 
w tabeli vtiger_field w kolumnie maximumlength wstawić taką liczbę jaka jest długość kolumny w bazie danych

**Comment by mariuszkrzaczkowski** [comment]
Jaka jest wartość w kolumnie maximumlength (tabela vtiger_field) dla twojego pola ?
Pokaż strukturę tabeli z wartościami słownika

**Comment by yotuze** [comment]
```--
-- Struktura tabeli dla tabeli `vtiger_field`
--

CREATE TABLE `vtiger_field` (
  `tabid` smallint(5) NOT NULL,
  `fieldid` int(10) NOT NULL,
  `columnname` varchar(30) NOT NULL,
  `tablename` varchar(50) NOT NULL,
  `generatedtype` tinyint(3) UNSIGNED NOT NULL DEFAULT '0',
  `uitype` smallint(5) UNSIGNED NOT NULL,
  `fieldname` varchar(50) NOT NULL,
  `fieldlabel` varchar(50) NOT NULL,
  `readonly` tinyint(1) UNSIGNED NOT NULL,
  `presence` tinyint(1) UNSIGNED NOT NULL DEFAULT '1',
  `defaultvalue` text,
  `maximumlength` varchar(30) DEFAULT NULL,
  `sequence` smallint(5) UNSIGNED NOT NULL,
  `block` int(10) DEFAULT NULL,
  `displaytype` tinyint(1) UNSIGNED NOT NULL,
  `typeofdata` varchar(100) DEFAULT NULL,
  `quickcreate` tinyint(1) UNSIGNED NOT NULL DEFAULT '1',
  `quickcreatesequence` int(10) DEFAULT NULL,
  `info_type` varchar(20) DEFAULT NULL,
  `masseditable` int(10) NOT NULL DEFAULT '1',
  `helpinfo` varchar(30) DEFAULT '',
  `summaryfield` int(10) NOT NULL DEFAULT '0',
  `fieldparams` varchar(255) DEFAULT '',
  `header_field` varchar(15) DEFAULT NULL,
  `maxlengthtext` smallint(3) UNSIGNED DEFAULT '0',
  `maxwidthcolumn` smallint(3) UNSIGNED DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Zrzut danych tabeli `vtiger_field`
--

INSERT INTO `vtiger_field` (`tabid`, `fieldid`, `columnname`, `tablename`, `generatedtype`, `uitype`, `fieldname`, `fieldlabel`, `readonly`, `presence`, `defaultvalue`, `maximumlength`, `sequence`, `block`, `displaytype`, `typeofdata`, `quickcreate`, `quickcreatesequence`, `info_type`, `masseditable`, `helpinfo`, `summaryfield`, `fieldparams`, `header_field`, `maxlengthtext`, `maxwidthcolumn`) VALUES
(6, 2809, 'subindustry_multi', 'vtiger_account', 2, 33, 'subindustry_multi', 'Podbranża', 1, 2, '', NULL, 2, 441, 1, 'V~M', 2, 0, 'BAS', 1, '', 0, '', '0', 0, 0);```

**Comment by yotuze** [comment]
Czy jest szans na rozwiązanie tego problemu? Chciałem odtworzyć to na gitdeveloper.yetiforce.com, dodałem w "Moduły - pola", pole wielokrotnego wyboru "Podbranża" (podbranza_multi) i kilka wartości, stworzyło to pole. Przeszedłem do "Moduły - słowniki", do zakładki "Kontrahenci" ale gdy wybieram "Podbranża" i "Dodaj wartość" to wyskakuje okno i komunikat "Proszę czekać", testowałem to na innych polach i przeglądarkach, dalej to samo.

![yeti2](https://user-images.githubusercontent.com/6560221/64315593-c9e70680-cfb2-11e9-902e-09b402f6a776.PNG)

**Comment by paula-w** [comment]
Zajmiemy się tym w wolnej chwili, niestety w tym momencie nie mamy na to czasu. Jeśli jest to sprawa niecierpiąca zwłoki to polecamy kupno pakietu wsparcia.
