### ISSUE TITLE
[bug] Workflows can be deleted with on click

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11269]
Similar was happened to pdf templates (already fixed). Deletion of some complex workflows 
with one click and no action confirmation maybe painful for some of us.

**Comment by areksolek** [comment]
The problem in the newer version is solved
![Workflows](https://user-images.githubusercontent.com/25615135/74811567-094fa800-52f2-11ea-9e36-842bfa5ed295.gif)
