### ISSUE TITLE
[Question] Generate one PDF for many records is not working in 5.1           

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11268]
Generate one PDF for many records is not working in 5.1
It was mentioned in https://github.com/YetiForceCompany/YetiForceCRM/issues/10212#issuecomment-513098218
As I need it working now I kindly ask for link to PR / fix....

tnx

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/10365

**Comment by waran70** [comment]
Hi, applied all changes and still cannot generate one pdf for many records. It must be somewhere else?
Help appreciated

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/63567169-7ddaa180-c570-11e9-8929-0da5e840bad4.png)

https://github.com/YetiForceCompany/YetiForceCRM/blob/8ab2c9dbb6519ce2c0d5464d86a730c1d5736f6f/modules/Vtiger/actions/PDF.php#L79
you may need to update the PDF library
![image](https://user-images.githubusercontent.com/10221999/63567150-6d2a2b80-c570-11e9-8385-239aba431018.png)
