### ISSUE TITLE
[bug] Chat in Full Screen mode

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#11270]
Chat in full screen mode.
Blocks all links on the page.
It does not unfold correctly.
Gitdev
Firefox.

# 🐞 bug report

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
* [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by z0lo13** [comment]
@bpabiszczak 
Confirm:
![proof](https://user-images.githubusercontent.com/23143958/63062784-0c438900-bec8-11e9-98f5-32126ddb9d56.gif)
