### ISSUE TITLE
[Question]           Manual install on Cpanel server - really easy question

### ISSUE THREAD

**Issue by ohandy1** [YetiForceCompany/YetiForceCRM#11277]
Small matter not addressed in the documents. There is a public_html folder in the file structure, and there is a warning if that folder isn't designated the root directory.
Cpanel servers use public_html as the root directory inside the home directory.
Should the public_html directories unify, pushing all upstream files into the home directory?

I tried this once and while it worked for a bit, it developed a redirect loop. I don't know if I should try to resolve the redirect loop, or install everything in the original public_html directory then direct all crm traffic to the new _public_html/public_html_ directory, or just ignore the redirect loop and put everything into cpanel's public_html, which works.

Seems a small thing, but I can't find a directory tree for my use case.

**Comment by davide-alghi** [comment]
the path should be
```
|-- resident public_html folder (default cPanel webroot)
    |-- YF root folder
        |-- api
        |-- app
        |-- ...
        |-- public_html
        |-- ...
        |-- vtlib
        |-- ...
        |-- yarn.lock
```
with your DocumentRoot pointing to '**resident public_html folder/YF root folder/public_html**'

NB: indeed it should work without **YF root folder** folder, too

**Comment by ohandy1** [comment]
I greatly appreciate that.  I tried another install in the _home_ directory (merging the public_html folders) which seems to be working, but I don't want trouble down the road.  I'll use your suggestion when I create the production instance.

If I may, a follow-up. This is a shared environment (I do have root access) so I don't want to change the root directory in apache because that would affect other accounts. Would a htaccess rewrite be sufficient to send traffic to the nested public_html directory?  I've used other crm's including vTiger and this structure is a first for me. I can see a security advantage.

**Comment by davide-alghi** [comment]
I suggest you to try with tree up above: take into account that YF works fine also whether DocumentRoot points to YF folder (not to inner public_html). that is a security requirement.
however you can change DocumentRoot via .htaccess with something like this
```
RewriteEngine on
RewriteCond %{HTTP_HOST} ^domain-name.com$ [NC,OR]
RewriteCond %{HTTP_HOST} ^www.domain-name.com$
RewriteCond %{REQUEST_URI} !folder/
RewriteRule (.*) /folder/$1 [L]
```

**Comment by ohandy1** [comment]
thanks for the help. I didn't like the mess it made putting files in the home folder.  
I'll close this question
