### ISSUE TITLE
[bug] Board of Management Logo

### ISSUE THREAD

**Issue by sbouillon** [YetiForceCompany/YetiForceCRM#11272]
Describe the bug:
I'm having a lot of issues with the logo in the top left after logging in. The image looks broken like it cant find the path. I've tried almost everything in the closed issues but still not getting it to show up. The logo works on GitStable when I tested it 2 days ago.

### 🔥 How to trigger the error
Logo initially shows up but eventually turned to a broken image. Most likely from 4.4-> 5.0 update

1. Go to '...' settings
2. Click on '....' roles
3. Scroll down to '....' upload image to Board of Management or top level

### 👎 Actual Behavior
Still doesn't work
![Logo Missing](https://user-images.githubusercontent.com/37988748/63006349-37c86400-be33-11e9-8d60-7f7087ce68a1.PNG)

### 👍 Expected Behavior
Work

### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com - Works
* [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com - Works

### 📷 Screenshot of configuration
![Server Configuration](https://user-images.githubusercontent.com/37988748/63006331-2aab7500-be33-11e9-8dc7-1385e5592646.PNG)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
- YetiForce 5.1
- Debian 9
- PHP 7.1
- Apache
- Browser doesn't matter

I don't know which logs to enable in debug. That might solve this though... all of my folders permissions are correct including storage.

* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log 

### ❓ Additional context

Any help would be greatly appreciated. YetiForce is finally smooth sailing after fighting the mail scanner forever. The logo is the last piece that's an eye sore so I would really like to resolve this.

**Comment by acsinsurancegroup** [comment]
@sbouillon Go to the Admin Settings area and then under the Company Information menu select the Company Details link. Once that loads up click on the Choose File button towards the bottom of the page and choose the Logo image file you want displayed and upload it. It's that easy. Hope that helps.

**Comment by sbouillon** [comment]
Hi @acsinsurancegroup yes I tried this. It was actually my first step. I responded on your issue also. Let me know if you need help spinning up a container.

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/75136057-b99f2100-56e3-11ea-85fa-31a82db11eaa.png)

![image](https://user-images.githubusercontent.com/10198654/75136091-d50a2c00-56e3-11ea-860e-b04a3f916c5c.png)




https://gitdeveloper.yetiforce.com/index.php?module=MultiCompany&view=List&mid=152&parent=76
