### ISSUE TITLE
[Question] How to integrate Advanced block, product quantities in PDF ??

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#11281]
how can i integrate the products listed in a "Goods Received Note" in a custom PDF template , i need to be able to see the products quantities.

i want to send a pdf to supplyers to order products.

![Goods Received Note full](https://user-images.githubusercontent.com/45770116/63044819-0a180500-be9d-11e9-9e88-13a822eb03f5.PNG)

EDIT***
i want the products informations of this picture below, to appeir in my pdf template
![Goods Received Note](https://user-images.githubusercontent.com/45770116/63042750-aab7f600-be98-11e9-8c63-d5cc03dbfd53.PNG)

**Comment by vovpff** [comment]
I don't understand your question. Pls explain

**Comment by maeglin4** [comment]
ok sorry, 

so when it time to order products, i want to generate a PDF template to send to a company to buy products. 


When creating the PDF template, i dont see the variables to copy from the module in the photo below
![pdf template](https://user-images.githubusercontent.com/45770116/63058374-8a992e80-beba-11e9-866f-4510edd7dc0b.PNG)


what can i do to put in the pdf template, the exact products that i choosen in "Goods Received Note" record ?

is it more understandable ?

**Comment by maeglin4** [comment]
i would like to use "Goods Received Note" module to create a purchase order to send to a company and when the delevery is done and the i just have to change the status of the "Goods Received Note" to accepted so it will add to my inventory...

**Comment by z0lo13** [comment]
@maeglin4 you need to use:
 Additional variables->Choose one of Product tables->Profit?

**Comment by maeglin4** [comment]
Magnificent ! thanks alot, i found this $(custom : ProductsTableLongVersion)$

**Comment by maeglin4** [comment]
Magnificent ! thanks alot, i found this $(custom : ProductsTableLongVersion)$
