### ISSUE TITLE
[Question] (Reopen #11241) Why the issue is closed with no tests?

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#11286]
Hello Yeti Team,
@rskrzypczak @bpabiszczak 

First of all, I wanted to say, thank you for what you are doing it is really great! 

However, you can not close the issue based on theoretical tests, if you never even tested it, that will make the process of stabilizing the Yetiforce longer and longer.

I have tested email with the large attachment in gitdeveloper and it has the same issue:

![largeattachment](https://user-images.githubusercontent.com/23143958/63105191-4a838b80-bf4e-11e9-8ec9-3a7d19640677.gif)

@rskrzypczak  said

> I however think that the reason why your attachments aren't being downloaded is because of something else, namely their verification security-wise. If you check your logs you will probably see entries that confirm that.

I installed a new local version of yeti and enabled all logging there are no entries regarding the security of file size.

### 🔥 How to trigger the error

1. Go to Mail
2. Click on Attach a file
3.Attach PDF file Larger then 5 MB
4. Check the corporate emails record, 
5. No attachment

### 👎 Actual Behavior

#11241
### 👍 Expected Behavior

#11241
### 👷 Testing 

- [ ✔️] I confirm that I tested it at https://gitstable.yetiforce.com 
* [✔️ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### ❓ Additional context

I do understand that everyone has a lot to do, but we are here to make it better and in the shortest time.

Thank you,
z0lo13

**Comment by waran70** [comment]
PDF documents generated in YF are giant and this is what I mentioned before. 
I wish (and some of my customers) to pay 100 Euro for nicely designed and supported PDF extension - similar to those we can see in older brother.  Hope core stabilize and YF guys can earn more designing extensions.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/11241
