### ISSUE TITLE
[Question] PDF | Related list | sequential number         

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11283]
Pretty common thing is to print a list with sequential numbers on the left of row. Is there a way or chance to add a such to PDF templater so it can apply to module row list as well as related list?

**Comment by z0lo13** [comment]
is that for the advanced module? or a simple table?

**Comment by waran70** [comment]
Both

**Comment by z0lo13** [comment]
for an advanced module just add Item Number:
![изображение](https://user-images.githubusercontent.com/23143958/63200730-5192c280-c050-11e9-9a13-26639359b77c.png)
for a simple html table it will not be possible without javascript and php to put a row number.
