### ISSUE TITLE
[Question]  How do you install most recent dev version?       

### ISSUE THREAD

**Issue by acsinsurancegroup** [YetiForceCompany/YetiForceCRM#11287]
### Description

How do you install the same up to date version that is online right now as the demo version? No matter what I do, I cannot install it. Says missing vendor directory and when I add all of them with files from stable the installer still never works. How can I accomplish this?

**Comment by mariuszkrzaczkowski** [comment]
https://download.yetiforce.com/developer.zip
https://github.com/YetiForceCompany/YetiForceCRM#where-else-can-you-find-yetiforce
![image](https://user-images.githubusercontent.com/10198654/63146843-a60c5280-bffc-11e9-9819-e9208f0740c6.png)

**Comment by acsinsurancegroup** [comment]
Thanks @mariuszkrzaczkowski  :)
