### ISSUE TITLE
[Question] roundcube  email issue

### ISSUE THREAD

**Issue by xinkyo** [YetiForceCompany/YetiForceCRM#11285]
hello,
I have new install of yetiforce.
I found there is 2 issue for email roundcube.
1,could not add contact from quick link. I don't know why it become project task link as below photo. actually, it should be add contact.
2,While I click add comment, it just keep loading.there is no error message at sever side. 

![image](https://user-images.githubusercontent.com/43132285/63080940-ec1dd380-bf74-11e9-97d0-5d852747c893.png)
![image](https://user-images.githubusercontent.com/43132285/63080956-f2ac4b00-bf74-11e9-8dae-0c65b06f1fbc.png)

**Comment by bpabiszczak** [comment]
In the latest development version it works correctly. If you think it still doesn't work, record a video.
