### ISSUE TITLE
[Question] Future Plans?

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#11291]
### Description

Hello everyone,

In a new version, there will be paid modules which is absolutely great. However, vtiger started with paid modules and then switched to fully cloud-only CRM, as it is a more profitable model of distribution.
I guess most of the people will agree that one of the reasons to choose yetiforce was that it is could be installed on-premises. Which give us the gigantic opportunity in optimization for every company's workflows.

Please share with us your plans on the future Yeti.

Thank You

**Comment by ohandy1** [comment]
Foremost, I'd like to use yetiforce for my own purposes. If I can achieve a solid understanding of the inner workings, I know a number of people who would be interested in an affordable crm, potentially providing some supplemental income.

My biggest obstacle is the documentation for an installation in a shared environment, which most small businesses use. The addition to softaculous makes the project attractive, but there are server recommendations that don't make a lot of sense in a shared environment.

**Comment by mariuszkrzaczkowski** [comment]
> but there are server recommendations that don't make a lot of sense in a shared environment.

what do you mean ?

**Comment by waran70** [comment]
@ohandy1 there is great providers where you can get vps for 3.5 euro monthly. If (even) small company would like use advanced business IT apps, it should be wise to do so, or hire adviser/programmer.
Sharing servers are not for registered entities but individuals who don't care about safety & performance.

**Comment by paula-w** [comment]
@z0lo13 
Some of the paid features that in the new version will be available directly in the CRM marketplace are already  available in our online store. Some of them will be new and are not currently available. 
Rest assured, we’re not planning to create a separate version of YetiForce. You will be able to choose where you want to install YetiForce during the installation, the choices will be: your own server, YetiForce hosting (new service – more details soon), and YetiForce cloud.

**Comment by z0lo13** [comment]
> 
> 
> @z0lo13
> Some of the paid features that in the new version will be available directly in the CRM marketplace are already available in our online store. Some of them will be new and are not currently available.
> Rest assured, we’re not planning to create a separate version of YetiForce. You will be able to choose where you want to install YetiForce during the installation, the choices will be: your own server, YetiForce hosting (new service – more details soon), and YetiForce cloud.

Thank you @paula-w that is great news!
