### ISSUE TITLE
Which version of is the current stable version ?

### ISSUE THREAD

**Issue by harish-nair** [YetiForceCompany/YetiForceCRM#11290]
Hello,

Would someone please let me know which is the current stable version of YetiForce ?

I'm currently using V5.1.0 however I am seeing some issue as for example after creating a module I could see the "add custom field" button however once I save and exit and again try to edit field, the "add custom field" button is not visible. 
If I add a new Custom Block I can see the add custom field until i save the module.

Thanks in advance for your help

Regards,
Harish

**Comment by davide-alghi** [comment]
Hi harish-nair,
that's a very strange behavior. What about your browser? Did you clean browser cache?
Anyway, last version is the 5.1.0
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/5.1.0/

please try on stable / developer online instances to check if you have the same problem
https://gitstable.yetiforce.com/
https://gitdeveloper.yetiforce.com/

there are servicepack here
https://github.com/YetiForceCompany/YetiForceCRM/releases

**Comment by harish-nair** [comment]
Hi davide-alghi,

Thanks for your reply

I have already tried to clear browser cache also tried on multiple browsers with no luck.

As per your advice I tested on https://gitstable.yetiforce.com/ and It works there with no issues.

On that [link](https://gitstable.yetiforce.com/) It shows as version  5.1.0 on the footer which is the same version I am using which is strange.

**Comment by davide-alghi** [comment]
I go by trials

1) What's your webserver: win or linux?
2) Has your MySql user GRANT privileges on YF database?
3) Have **all** YF folders and files correct owner:group?
4) Try to use Firefox browser setting auto-clearing cache on close: **all cache in time and type**
5) Try to clear YF cache
1 - close the browser
2 - go into **/cache/templates_c** folder
3 - there you can see files *.tpl.php and a folder named basic
4 - remove all files *.tpl.php, but **not basic folder**
5 - go into **cache/templates_c/basic** folder
6 - there you can see files *.tpl.php and an index.html file
7 - remove all *.tpl.php files, but **not index.html file**

please, check and try and let us know info about above questions and feedback

**Comment by harish-nair** [comment]
Sure,

1. webserver: apache2/now 2.4.39-1+ubuntu18.04.1+deb.sury.org+1
2. Yes, mysql user has all privileges to the database.
3. Yes, all of them owned by webserver user:group.
4. Yes, Tried with no luck.
5. I tried to clear YF cache as per your instruction, still no luck.

This is happening only with modules which I have created using "Create Module" Button.
I also tried to test by creating a new test module called Test, and I got an error:
`
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
The SQL being executed was: CREATE TABLE `u_yf_test` (
	`testid` int(10)
) CHARACTER SET utf8 ENGINE=InnoDB`

Thanks

**Comment by davide-alghi** [comment]
something I cannot understand: random errors?
now cannot you create a new module?

it seems that **crmentity.crmid** field doesn't exist :scream:

Is it a fresh YF510 installation or a migration to YF510?

**Comment by harish-nair** [comment]
I tried to create another module with a different name 'Testn', and this time I was able to create the module without any error. I think there is some entry in database from previous test module I had created and when deleted the module was not deleted properly.

This is not a migrated instance, It was a fresh install.

**Comment by harish-nair** [comment]
I just noticed that TEST module which I had initially created is displayed on the "Module Manager",

Now If I try to delete the module, Its stuck at "Preview is loading".
Meanwhile I tried to debug, the below is what I found from the logs.
`
2019-08-21 19:10:11.861 [info][yii\db\Command::query] - SELECT * FROM `vtiger_tab`
2019-08-21 19:10:11.861 [info][yii\db\Connection::open] - Opening DB connection: mysql:host=localhost;dbname=yetiforce;port=3306
2019-08-21 19:10:11.9133 [info][yii\db\Command::query] - SELECT * FROM `vtiger_entityname`
2019-08-21 19:10:11.9309 [info][yii\db\Command::query] - SELECT * FROM `vtiger_entityname`
2019-08-21 19:10:11.9492 [error] - vtlib\Deprecated::checkFileAccessForInclusion(modules/TEST/TEST.php) - Sorry! Attempt to access restricted file. realfilepath:
2019-08-21 19:10:11.9493 [error] - Sorry! Attempt to access restricted file.
App\Exceptions\AppException: Sorry! Attempt to access restricted file. in /var/www/YetiForceCRM/vtlib/Vtiger/Deprecated.php:72
Stack trace:
#0 /var/www/YetiForceCRM/include/CRMEntity.php(60): vtlib\Deprecated::checkFileAccessForInclusion('modules/TEST/TE...')
#1 /var/www/YetiForceCRM/vtlib/Vtiger/ModuleBasic.php(191): CRMEntity::getInstance('TEST')
#2 /var/www/YetiForceCRM/modules/Settings/ModuleManager/actions/Basic.php(119): vtlib\ModuleBasic->delete()
#3 [internal function]: Settings_ModuleManager_Basic_Action->deleteModule(Object(App\Request))
#4 /var/www/YetiForceCRM/app/Controller/ExposeMethod.php(65): call_user_func_array(Array, Array)
#5 /var/www/YetiForceCRM/app/Controller/ExposeMethod.php(78): Settings_ModuleManager_Basic_Action->invokeExposedMethod('deleteModule', Object(App\Request))
#6 /var/www/YetiForceCRM/include/main/WebUI.php(183): Settings_ModuleManager_Basic_Action->process(Object(App\Request))
#7 /var/www/YetiForceCRM/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#8 /var/www/YetiForceCRM/public_html/index.php(11): require('/var/www/YetiFo...')
#9 {main}
2019-08-21 19:10:11.8241 [info][application] -
$_GET = []
$_POST = [
    '__vtrftk' => 'sid:6ca83ba960cb4b746bef55416b290c6b02ea6921,1566394667'
    'module' => 'ModuleManager'
    'action' => 'Basic'
    'parent' => 'Settings'
    'mode' => 'deleteModule'
    'forModule' => 'TEST'
]
$_FILES = []
$_COOKIE = [
    'YTSID' => 'ji4h1fqptqqg0p5dl8esdbpqui'
]
$_SESSION = [
    'return_params' => 'module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8'
    'last_activity' => 1566394811.8244
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => 'xxx'
    'user_name' => 'xxx'
    'full_user_name' => 'Administrator'
    'fingerprint' => 'xxx'
]
`

**Comment by davide-alghi** [comment]
if you are into production, I suggest you to take into account a support service by YetiForce Company.

**Comment by harish-nair** [comment]
I understand, Actually Im still in testing phase if this would be the right fit for my employer.
Yes, I did think of getting a support service from the company however only once I am able to convince this is the solution fit for my employer.

Anyways I was able to fix this issue as I found 2 errors in the database:
` [ERROR] /usr/sbin/mysqld: Table './yetiforce/u_yf_crmentity_label' is marked as crashed and should be repaired`

` [ERROR] /usr/sbin/mysqld: Table './yetiforce/u_yf_crmentity_search_label' is marked as crashed and should be repaired`

So, I repaired both the tables using: 


``REPAIR TABLE `u_yf_crmentity_label`;``
``REPAIR TABLE `u_yf_crmentity_search_label`;``


And now I can see the 'Add Custom Field' buttons 

Thanks  Davide :)

**Comment by mariuszkrzaczkowski** [comment]
It appears you have a corrupted database, if it was corrupted before the upgrade, you may have problems because it wasn't completed successfully.
Did you check logs after the update?

**Comment by harish-nair** [comment]
Hello Mariusz,
This was a fresh install not an upgrade.
It seems the issue is resolved now after I repaired the tables.
Thank You
