### ISSUE TITLE
CRON won't run correctly due to a parse error

### ISSUE THREAD

**Issue by d-dune** [YetiForceCompany/YetiForceCRM#11294]
**Issue** - CRON will not work correctly due to an error
**Log show's an error** - "Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/eagleweb/public_html/crm/include/ConfigUtils.php on line 107"

**Line 107** - "public static function sounds(?string $arg = null, $default = null)"

**PHP version** is running 7.1.3

[Screen Shot 2019-08-17 at 8 02 17 PM](https://user-images.githubusercontent.com/47238926/63219727-28942f80-c12d-11e9-877c-611779b0ecb6.png)

**Comment by davide-alghi** [comment]
I d-dune,
that's nullable types introduced since PHP 7.1.x. Maybe your **PHP CLI** is running with PHP version < 7.1.x

```public static function sounds(?string $arg = null, $default = null)```

**?string** means that $args may be a string or null, on call.

please upload here your Server Configuration log from
https://gitstable.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65

**Comment by mariuszkrzaczkowski** [comment]
https://www.google.com/amp/s/www.thegeekdiary.com/how-to-check-the-php-version-on-linux/amp/

**Comment by d-dune** [comment]
I have verified the php cli is running version 7.1.3 - which is why I'm stumped. Seems like a php problem to me, but can't seem to track it down. I've uploaded screen shots of php report.

<img width="505" alt="Screen Shot 2019-08-18 at 3 47 11 PM" src="https://user-images.githubusercontent.com/47238926/63231441-a4938380-c1d0-11e9-85c5-729bfaeb87c5.png">

<img width="1440" alt="Screen Shot 2019-08-18 at 3 52 31 PM" src="https://user-images.githubusercontent.com/47238926/63231443-ac532800-c1d0-11e9-9aeb-91c0639960e9.png">

**Comment by d-dune** [comment]
This problem has now been solved. The issue seems to have been caused by having CRON execution via wrong php version, even though I don't understand how that was possible since "php -v" showed the correct version. My host provider "Siteground" reset the PHP version to execute these scripts in PHP 7.1. which solved the problem.
