### ISSUE TITLE
[Question] Want to move one vtiger to YF - need to know when :-)          

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11293]
Hi gents!

got plan to move one 1 of VT to YF. The only thing is I wish I know when you gonna release 5.2
If that happen within week or two I can wait.. but if there is some longer wait-time I may start this weekend. Chance to get prompt answer?

**Comment by bpabiszczak** [comment]
1 week

**Comment by bpabiszczak** [comment]
max 2 = 100%

**Comment by bpabiszczak** [comment]
What version of Vtiger does the client have?

**Comment by waran70** [comment]
Thanks for that. Client have 7.1
