### ISSUE TITLE
Move to Recycle Bin for Custom Module available only to admin user [bug] 

### ISSUE THREAD

**Issue by nerimic** [YetiForceCompany/YetiForceCRM#11296]
For custom module the "Move to Recycle Bin" button is missing for users that are not flagged as "admin" in "Software configuration:Permissions:Users".

Also the related settings are missing in "Software configuration:Permissions:Profiles".

**Comment by bpabiszczak** [comment]
The programmer must add the [delete to recycle bin] action in the profile of the new module.
