### ISSUE TITLE
How can We be able to change the any status of the picklist values from record list page without having to go inside the summary page ?

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#11298]
### Description

How can We be able to change the any status of the picklist values from record list page without having to go inside the summary page ?

![Lead status change](https://user-images.githubusercontent.com/47585969/63236954-568b8800-c283-11e9-9dad-db2da22e2476.JPG)

In above screenshot How should   I be able to change the status of the Lead status from Record list page without having to go inside lead summary page?.

Please give me suggestions for how can i able achieve above task?.

**Comment by vovpff** [comment]
I think this function not available in standard package

**Comment by guide5232** [comment]
Ok

**Comment by rskrzypczak** [comment]
Mass edit
![image](https://user-images.githubusercontent.com/10221999/63241217-2926e600-c253-11e9-8f7c-6b85859d596c.png)

**Comment by vovpff** [comment]
@rskrzypczak Mass edit does not work with one record :)

**Comment by bpabiszczak** [comment]
@vovpff of course it works with one record

**Comment by vovpff** [comment]
@bpabiszczak sorry, Never tried mass edit for 1 record in the past. But this is too much actions for status changing :)

**Comment by z0lo13** [comment]
@vovpff #10894
