### ISSUE TITLE
[Question] Workflow Modify/Create logic trigger 

### ISSUE THREAD

**Issue by Pietrox** [YetiForceCompany/YetiForceCRM#11313]
Hello,

Just wanted to ask about the exact logic of the Workflows and it's triggers based on modify/create option.

We set a testing workflow to update every account with email domain ending with a raw text value to be assigned to a specific user.
So when someone becomes a customer or there is any edit update on the record to go through the db and make sure those are assigned to the person.

Now the thing is, I just can't make it run on existing records. We are editing name, statuses, even email on those test accounts and it seems we can't trigger the issue.

This logic seems to also not work on demo, below im attaching configs of the case:

![image](https://user-images.githubusercontent.com/22810723/63419555-53b8a080-c405-11e9-940c-7e06ac22bfb8.png)
![image](https://user-images.githubusercontent.com/22810723/63419573-5b784500-c405-11e9-879b-c65f5a253b20.png)
![image](https://user-images.githubusercontent.com/22810723/63419594-659a4380-c405-11e9-88bb-3cd786048aa3.png)
![image](https://user-images.githubusercontent.com/22810723/63419661-7c409a80-c405-11e9-9c4a-2fe296d1cc0f.png)

Originally I'm not reporting this as a bug, maybe im missing the point of the option for creating/updating records. But this looks that it's a possible bug.

**Comment by davide-alghi** [comment]
Hi Pietrox,
I just tried on gitstable and it works fine. take into account that modify means change some values and save

**Comment by davide-alghi** [comment]
here my wf

[77_workflow.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/3526565/77_workflow.zip)

**Comment by Pietrox** [comment]
Can't import it, on gitstable also gives errors.
Nevertheless on the screenshots im not pressing save, but record is being updated. So this is not taken into account? Changing one field?

**Comment by davide-alghi** [comment]
Hi Pietrox,
> Can't import it, on gitstable also gives errors.

yes, but it's a Notice, not an Error ... the workflow is correctly imported: please check well. I just uploaded

> Nevertheless on the screenshots im not pressing save, but record is being updated. So this is not taken into account? Changing one field?

yes if you modify inline in detail view, it's the same thing: workflow is called and it works fine

**Comment by Pietrox** [comment]
I did import your Workflow, but I also made exactly the same workflow but mine didnt work.

The only difference I see is that I use 4 conditions in "Any conditions" for primary email. Those are 4 different domains.
I deleted your workflow and updated mine that there is only one rule in those conditions and it works.
So maybe it is a logical bug? In any conditions I should be able to use multiple variations of the same logic right?

**Comment by davide-alghi** [comment]
argh!! it seems to take into account only the last condition into ANY group ... it seems a bug but it needs a deep check

workaround for your need: create a workflow for each email ending

**Comment by davide-alghi** [comment]
I tested on gitdeveloper and there is same problem

**Comment by Pietrox** [comment]
Yup did the workaround. But on 4.3 (currently on our prod) it seems to work well. So it's only for new version i guess.

**Comment by davide-alghi** [comment]
rollback: on gitdeveloper it seems to work now ... better deeper testing

**Comment by rskrzypczak** [comment]
Issue: https://github.com/YetiForceCompany/YetiForceCRM/issues/10097
Fix: https://github.com/YetiForceCompany/YetiForceCRM/commit/9556f0bde2065264d691f467f880eacfd0680825
