### ISSUE TITLE
Installation shows only ï»¿

### ISSUE THREAD

**Issue by joland** [YetiForceCompany/YetiForceCRM#1132]
I tried to install the webservice of yetiforce CRM.

PHP version 5.4.38, Debian wheezy.
But when opening the default dir. it redirects to ./install/Install.php 
it returns: ï»¿
I don't even get to the welcome page.
No logs, nothing.

**Comment by mariuszkrzaczkowski** [comment]
I added amendment try to install the latest version https://github.com/YetiForceCompany/YetiForceCRM/commit/cd978b1ddfb3beaf824167e9b6cc24562b526d1a

**Comment by diderich** [comment]
Install fails with the following error message (2.0.168):

[Tue Jun 23 08:56:36.063810 2015] [php5:error] [pid 29940] [client xxx.xxx.xxx.xxx:xxxxx] PHP Fatal error:  Call to a member function prepare() on null in /opt/yetiforce-2.0.168/include/database/PearDatabase.php on line 300

**Comment by joland** [comment]
Don't know what ur talkin about. But i still got the same issue, that is, with ur amendment.

**Comment by mariuszkrzaczkowski** [comment]
I introduced some amendments, now it should work

**Comment by diderich** [comment]
2.0.171 install did work for me!
