### ISSUE TITLE
How to restrict access of public folder without login?

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#11320]
### Description

I can access mp3 or document in public folder without login
How to restrict access of public folder without login?

Note : Mp3 file moved to storage folder, we cannot play audio.
It shows file not found or access forbidden

![Documents](https://user-images.githubusercontent.com/47585969/63481520-f9890f80-c4d8-11e9-808c-21ab81757afd.gif)

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/63485102-6a610500-c4a2-11e9-9d62-23b1e2aac474.png)

**Comment by guide5232** [comment]
![Public](https://user-images.githubusercontent.com/47585969/63485616-6905fb80-c4e7-11e9-99a4-2a2d79c4176f.JPG)

**Comment by z0lo13** [comment]
> 
> 
> We have followed all Recommended configuration but we cannot restrict access of public folder without login.
> 
> ![Public](https://user-images.githubusercontent.com/47585969/63485616-6905fb80-c4e7-11e9-99a4-2a2d79c4176f.JPG)
@guide5232 
have you find out what was the issue?

**Comment by guide5232** [comment]
I did not find any solution for that whenever we have url for particular  file then only can access data other we can not access the data.
