### ISSUE TITLE
Backup Problem

### ISSUE THREAD

**Issue by ercanbora37** [YetiForceCompany/YetiForceCRM#11323]
Dears,

I established software to the subdomain but only backup not working…

**crm.ebora.com.tr** : my main site
created crm.ebora.com.tr/backup for backup folder.....

changed values in config/backup.php like....

```
	/** Backup catalog path. */
	public static $BACKUP_PATH = '**/backup**';
```

am i right ? or how to write this short link ?

**Comment by ercanbora37** [comment]
**Exact code like that :** 

<?php

/**
 * Configuration file.
 * This file is auto-generated.
 *
 * @package Config
 *
 * @copyright YetiForce Sp. z o.o
 * @license   YetiForce Public License 3.0 (licenses/LicenseEN.txt or yetiforce.com)
 */

namespace Config\Components;

/**
 * Configuration Class.
 */
class Backup
{
	/** Backup catalog path. */
	public static $BACKUP_PATH = '/backup';

	/** Allowed extensions to show on the list. */
	public static $EXT_TO_SHOW = ['7z', 'bz2', 'gz', 'rar', 'tar', 'tar.bz2', 'tar.gz', 'tar.lzma', 'tbz2', 'tgz', 'zip', 'zipx'];
}

**Comment by davide-alghi** [comment]
Hi ercanbora37,
maybe I cannot understand the problem... if you are looking for backup execution, you know that back doesn't exist. You have to implement it and, saving those into backup folder, you can list and download files. Backup can be easily implemented via server Cron actions: it's enough to save db and YF folder.

**Comment by ercanbora37** [comment]
Just want to Backup and Import..... But impossible to backup because of permission problem. I think not possible from admin panel... We will use cpanel instead of software admin panel...

**Comment by davide-alghi** [comment]
Hi ercanbora37,

> Just want to Backup and Import..... 
do you mean backup from **server A** and replicate same installation to **server B**?

> But impossible to backup because of permission problem. I think not possible from admin panel... We will use cpanel instead of software admin panel...
please, could you be clearer?

**Comment by ercanbora37** [comment]
i used cpanel for backup and imported again... no problem..... forget my question :) thanks :)
