### ISSUE TITLE
Adding Primary Contact Informations to the filters

### ISSUE THREAD

**Issue by ercanbora37** [YetiForceCompany/YetiForceCRM#11328]
Hello,

If you want to see company owner name phone or email etc... you have to open account in detail...

By adding these values, we can have more selection in main page.... no need to enter account details to see owner details etc....

<img width="958" alt="Ek Açıklama 2019-08-23 091726" src="https://user-images.githubusercontent.com/54415452/63570949-678c1000-c587-11e9-990f-11ec9427fe19.png">

what i want to see, just detials of primary contact...

<img width="941" alt="Ek Açıklama 2019-08-23 091751" src="https://user-images.githubusercontent.com/54415452/63570964-7c68a380-c587-11e9-80b9-3f5ebad4c17b.png">

**Comment by davide-alghi** [comment]
In filter you can select only columns from Account fields (included fields from 1:M related module), but you cannot include fields from M:M related modules like Contacts.

**Solution A**
What you can do is to copy info from **Primary contact** (as you named) into Account->Contact info block and then modify filter columns.

**Solution B** - recommended
Alternatively you can add, to Accounts module, a custom relation (1:M) field type, pointing to Contacts module. This new field will point to **Primary contact** and it will can be pushed into filter as you need.
