### ISSUE TITLE
[Question]           Importing issue

### ISSUE THREAD

**Issue by AxLShiv** [YetiForceCompany/YetiForceCRM#11339]
hi

I've got a small issue with uploading csv for contacts. When i hit upload it goes to the progress screen and constantly refreshes the page every 5 seconds.Ive left it for 10 minutes as of the time of posting this.

The file I'm uploading is 760kb so im not sure whats going wrong.

Please assist

**Comment by vovpff** [comment]
Data import is some kind of science. There are a lot of things what affects to result. As for me greatest way to import any data by xml.
