### ISSUE TITLE
[Question]  generate record - required conditions  

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11335]
Hi

What conditins of entity and custom module should apply to succesfuly triger Generate Record function from list view? Here is situation, that it keep spinning infinity until I kick the browser... any tips?

**Comment by waran70** [comment]
Little addendum: If I get one record in list view and triger Generate Records/Open in new window - it works nice, when I select Create Automatically, it hangs or returning failed action.

**Comment by bpabiszczak** [comment]
Only a programmer can help you
