### ISSUE TITLE
[Question]  workflow - Task omitted, it has not been finished during the last scanning         

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11366]
Hi

> Task omitted, it has not been finished during the last scanning

My cron is set for 1 min and scheduler frequency the same. Workflow triggering very diferently like 8 min, 10 min... I dont really get why. Any tips?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/11367

> The "Last scan time" may be different from the set frequency, it is due to the fact that there are two mechanisms, one in CRM and the other on the OS layer. If the frequency in the operating system will be set for every 15 minutes, then regardless of what you set in the CRM system [e.g. 5 min] won't trigger CRON earlier than after 15 minutes.
