### ISSUE TITLE
Calendar resets to 5 day week.           

### ISSUE THREAD

**Issue by ohandy1** [YetiForceCompany/YetiForceCRM#11362]
I need weekends visible, but each time I open the calendar module it is reset to the m-f view.  ALL is highlighted, but I must select Filter>workdays> then change to all again.  This happens each time I open the calendar.

I've got other questions but trying to sort them myself.  This one has me stumped.

I'm working with a new install of 5.1 (softaculous)

Thanks.

Update: I checked the "update calendar when rescheduled" (or something to that effect) in the calendar config setting and my tasks started disappearing. Unchecked and they're all back. I don't expect this is the intended behavior.

**Comment by z0lo13** [comment]
@ohandy1 

in config/modules/calendar change

public static $HIDDEN_DAYS_IN_CALENDAR_VIEW = [0, 6];
to 
public static $HIDDEN_DAYS_IN_CALENDAR_VIEW = [];

**Comment by sistemasnow** [comment]
¡Thanks for the information!
