### ISSUE TITLE
[Question] How can i reset menus for different department ?

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#11365]
i've changed all the menus for all the different department and now i want to know how to reset it back to default for everybody ?

Default Menu
![image](https://user-images.githubusercontent.com/45770116/63885519-871ba200-c9a6-11e9-9ae8-735f5c5f58ea.png)

Marketing Department Menu
![image](https://user-images.githubusercontent.com/45770116/63885533-93076400-c9a6-11e9-8046-89d00fc747de.png)

**Comment by bpabiszczak** [comment]
Delete all in department
