### ISSUE TITLE
[Bug] Create entity task got some bugs

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11370]
Playing around I realized that create entity task, hanging and deleting itself entries. 
Just try to create workflow, create entity task, safe it, open again, add some field, enter illegal value or whatever, and you will see effect.

**Comment by TonyM15** [comment]
Confirmed. Once you save it and want edit, the fields are not available as usual.
Also, when you switch between Custom Mapping and Mapping from panel, the first get lost completely. I think it should be preserved somehow until workflow is saved.
Browser console shows: SyntaxError: JSON.parse: end of data while reading object contents at line 1 column 3 of the JSON data

**Comment by JohnMaverick** [comment]
Same here but I also cannot create new entity record and use as a reference UI type 10. Fields are not filled up... this is relating to v 5.1

**Comment by JohnMaverick** [comment]
Also mapping dont work on UI type 10... should be considered as a bug... it is two modules Mapping and Workflows/Create entity - affected by this issue

**Comment by konadrian** [comment]
I'm not sure if it is what you have mentioned?
![CreateEntity](https://user-images.githubusercontent.com/3193498/75548964-cc408f80-5a2e-11ea-91fe-b37d6e57a105.gif)

**Comment by rskrzypczak** [comment]
Recently, several improvements have been made to this functionality.
