### ISSUE TITLE
[Question] Subindustry field dissapears under account module after convertion 

### ISSUE THREAD

**Issue by rtorrescodes** [YetiForceCompany/YetiForceCRM#11375]
After convertion from a lead with industry and subindustry field filled, on account module subindustry isnt available.  I tried to add it but its not getting the lead subindustry field value.
¿Any ideas? Help please.  Thanks a lot.

**Comment by rtorrescodes** [comment]
Anyone?

**Comment by bpabiszczak** [comment]
Check this: Software configuration >> Standard modules >> Custom field mapping
