### ISSUE TITLE
[bug] Creating a chart from filter

### ISSUE THREAD

**Issue by jocape** [YetiForceCompany/YetiForceCRM#11389]
# 🐞 bug report

### ⁉️ Describe the bug

Error creating widget , in particular a chart from filter. 
I wanted to create a Donut graph of all the quotes, grouped by status with the total money using Total field.

It is impossible to do it neither in my local instalation nor in your demo system.
In my installation I am sure it worked previously as I have a chart created more an less 2 months ago. But If I try to create another graph I founded the described problem.

### 🔥 How to trigger the error

1. Go to System Settings, / Standard Modules / Widgets-Configuration
2. Click on +Chart from filter
3. Select any type of chart
4. Select module quotes
5. Select Value type, Sum
6. Select any filter and group by field status
7. Try to select Value Field **Total** and it is not possible as it is not appearing in the options list.
:-(

### 👎 Actual Behavior

Impossible to create the widget.

### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
* [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.01  service pack 4
| Web server (name and version)|Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_nss/1.0.14 NSS/3.28.4		|
| PHP  |7.3.3								|
| Browser (name and version)  | Chrome , Firefox		|
| Operating System (name and version)  | CENTOS 7.0		|
| Database (name and version) |5.5.60-MariaDB 		|

**Comment by jocape** [comment]
Why the net_total value (from a quote) doesn't appear in the list of available values when creating a graph? Is there any place to configure the available values? Thanks and incredible and great job :-)

**Comment by bpabiszczak** [comment]
Because the system does not yet support this type of field in charts.

**Comment by adudekyeti** [comment]
Hi,
In version 5.3 it is possible to select this field:
![image](https://user-images.githubusercontent.com/39482453/94905296-f2368280-049c-11eb-865e-f55f2980ffc0.png)

**Then on dashboard you will have:**
![image](https://user-images.githubusercontent.com/39482453/94905388-14300500-049d-11eb-8489-0d19e7801667.png)

Please update your system to newest version.
