### ISSUE TITLE
The menu and other items are showing some additional letters like MEN_ LBL_ etc          

### ISSUE THREAD

**Issue by eMayam** [YetiForceCompany/YetiForceCRM#11382]
Hi, I created a user and when the user logged in, they are finding some additional text prefix to all the menu and other names. Kindly refer the attached file. Please help me to solve this. Thanks,

![Yeti Error](https://user-images.githubusercontent.com/54782802/64083785-550d9580-cd42-11e9-9868-bb955c8316d3.PNG)

**Comment by mariuszkrzaczkowski** [comment]
Check:
what language is set
are there language files for this language

**Comment by eMayam** [comment]
Thank You, This solves the problem.
