### ISSUE TITLE
YetiForce 2.0.0 - fresh instalation fails

### ISSUE THREAD

**Issue by Armaia** [YetiForceCompany/YetiForceCRM#1139]
Hi,
I made some tests trying to install Yeticrm but after the instalation I have always HTTP ERROR 500.
I have WAMP server 64 bit with mysql 5.6.17, php 5.5.12 and apache 2.4.9. I have instaled and working on the same server Joomla and Vtigercrm.
First, I tried with some debug on and the instalation stopped immediatly with database empty without any table.

logs:

06/24/15 01:32:51,548 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:32:51,550 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:32:51,552 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:32:53,286 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:32:53,287 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:32:53,287 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:33:07,557 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:33:07,557 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:33:07,558 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:33:12,682 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:33:12,682 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:33:12,683 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:36:47,445 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:36:47,446 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:36:47,447 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:41:16,597 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:41:16,597 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:41:16,598 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:42:59,630 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:42:59,631 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 01:42:59,632 [1384] INFO VT - PearDatabase ->ADODB Connect : DBType not specified
06/24/15 00:43:00,267 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 00:43:00,268 [1384] DEBUG VT - query being executed : SET NAMES utf8
06/24/15 00:43:00,269 [1384] INFO VT - PearDatabase ->TRANS creating new connection
06/24/15 00:43:00,350 [1384] DEBUG VT - query being executed : SET FOREIGN_KEY_CHECKS = 0;
06/24/15 00:43:42,390 [1384] DEBUG VT - query being executed : /*
SQLyog Ultimate v11.5 (64 bit)
MySQL - 5.6.17 : Database - yetiforce
*********************************************************************
*/

/*!40101 SET NAMES utf8 */
06/24/15 00:43:42,391 [1384] DEBUG VT - query being executed : /*!40101 SET SQL_MODE=''*/
06/24/15 00:43:42,391 [1384] DEBUG VT - query being executed : /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */
06/24/15 00:43:42,392 [1384] DEBUG VT - query being executed : /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */
06/24/15 00:43:42,392 [1384] DEBUG VT - query being executed : /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */
06/24/15 00:43:42,393 [1384] DEBUG VT - query being executed : /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */
06/24/15 00:43:42,393 [1384] DEBUG VT - query being executed : /*Table structure for table `chat_bans` */

CREATE TABLE `chat_bans` (
  `userID` int(11) NOT NULL,
  `userName` varchar(64) NOT NULL,
  `dateTime` datetime NOT NULL,
  `ip` varbinary(16) NOT NULL,
  PRIMARY KEY (`userID`),
  KEY `userName` (`userName`),
  KEY `dateTime` (`dateTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
06/24/15 00:43:42,819 [1384] DEBUG VT - query being executed : /*Table structure for table `chat_invitations` */

CREATE TABLE `chat_invitations` (
  `userID` int(11) NOT NULL,
  `channel` int(11) NOT NULL,
  `dateTime` datetime NOT NULL,
  PRIMARY KEY (`userID`,`channel`),
  KEY `dateTime` (`dateTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
..........

After that, I tried install it again with diferente debug  and the database was installed with tables but without any user, even admin.
I attach some description and the logs.

system
.......
06/24/15 00:52:59,303 [1384] DEBUG VT - query being executed : insert  into `vtiger_profile2utility`(`profileid`,`tabid`,`activityid`,`permission`) values (2,49,6,0)
06/24/15 00:52:59,345 [1384] DEBUG VT - query being executed : insert  into `vtiger_profile2utility`(`profileid`,`tabid`,`activityid`,`permission`) values (2,49,8,0)
06/24/15 00:52:59,395 [1384] DEBUG VT - query being executed : insert  into `vtiger_profile2utility`(`profileid`,`tabid`,`activityid`,`permission`) values (2,49,14,0)
06/24/15 00:52:59,437 [1384] DEBUG VT - query being executed : insert  into `vtiger_profile2utility`(`profileid`,`tabid`,`activityid`,`permission`) values (2,49,15,0)
06/24/15 00:52:59,460 [1384] DEBUG VT - query being executed : insert  into `vtiger_profile2utility`(`profileid`,`tabid`,`activityid`,`permission`) values (2,49,17,0)
06/24/15 00:52:59,495 [1384] DEBUG VT - query being executed : insert  into `vtiger_profile2utility`(`profileid`,`tabid`,`activityid`,`permission`) values (2,49,18,0)
06/24/15 00:52:59,519 [1384] DEBUG VT - query being executed : insert  into `vtiger_profile2utility`(`profileid`,`tabid`,`activityid`,`permission`) values (2,49,19,0)
06/24/15 00:52:59,553 [1384] DEBUG VT - query being executed : insert  into `vtiger_profile2utility`(`profileid`,`tabid`,`activityid`,`permission`) values (2,49,22,0)
06/24/15 01:03:09,083 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:03:09,304 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM vtiger_tab
06/24/15 01:03:10,920 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:03:11,100 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM vtiger_tab
06/24/15 01:03:14,737 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:03:14,913 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM vtiger_tab
06/24/15 01:03:28,611 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:03:28,789 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM vtiger_tab
06/24/15 01:16:53,607 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:16:53,772 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM vtiger_tab
06/24/15 01:17:12,161 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:17:13,843 [1384] DEBUG VT - Prepared sql query being executed : select * from vtiger_organizationdetails
06/24/15 01:17:34,653 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:17:35,107 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM `vtiger_bruteforce` LIMIT 1
06/24/15 01:17:35,110 [1384] DEBUG VT - Prepared sql query being executed : SELECT count(login_id) as cn FROM `vtiger_loginhistory` vlh WHERE STATUS = 'Failed login' && user_ip = ? && unblock = 0 && (UNIX_TIMESTAMP(vlh.login_time) - UNIX_TIMESTAMP(ADDDATE(?, INTERVAL -15 MINUTE))) > 0
06/24/15 01:17:35,111 [1384] DEBUG VT - Prepared sql query parameters : [::1,2015-06-24 01:17:35]
06/24/15 01:17:35,114 [1384] DEBUG VT - query being executed : SELECT * FROM vtiger_bruteforce
06/24/15 01:17:35,117 [1384] DEBUG user - Entering Users() method ...
06/24/15 01:17:35,118 [1384] DEBUG VT - Entering getColumnFields(Users) method ...
06/24/15 01:17:35,119 [1384] DEBUG VT - in getColumnFields Users
06/24/15 01:17:35,120 [1384] DEBUG VT - Prepared sql query being executed : SELECT tabid, name, ownedby FROM vtiger_tab
06/24/15 01:17:35,122 [1384] DEBUG VT - Prepared sql query being executed : SELECT tabid, name, ownedby FROM vtiger_tab
06/24/15 01:17:35,123 [1384] DEBUG user - Exiting Users() method ...
06/24/15 01:17:35,143 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM vtiger_tab
06/24/15 01:17:35,144 [1384] DEBUG VT - Prepared sql query being executed : SELECT id from vtiger_users where user_name=? AND deleted=0
06/24/15 01:17:35,145 [1384] DEBUG VT - Prepared sql query parameters : [sixforce]
06/24/15 01:17:35,146 [1384] DEBUG user - Start of authentication for user: sixforce
06/24/15 01:17:35,147 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM yetiforce_auth
06/24/15 01:17:35,148 [1384] DEBUG user - Using integrated/SQL authentication
06/24/15 01:17:35,148 [1384] DEBUG VT - Prepared sql query being executed : SELECT crypt_type, user_name FROM vtiger_users WHERE user_name=?
06/24/15 01:17:35,149 [1384] DEBUG VT - Prepared sql query parameters : [sixforce]
06/24/15 01:17:35,150 [1384] ERROR PearDatabase_ - Rows Returned:0 More than 1 row returned for SELECT crypt_type, user_name FROM vtiger_users WHERE user_name=?
06/24/15 01:17:35,150 [1384] ERROR user - User not found: sixforce
06/24/15 01:17:49,394 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:17:49,651 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM `vtiger_bruteforce` LIMIT 1
06/24/15 01:17:49,653 [1384] DEBUG VT - Prepared sql query being executed : SELECT count(login_id) as cn FROM `vtiger_loginhistory` vlh WHERE STATUS = 'Failed login' && user_ip = ? && unblock = 0 && (UNIX_TIMESTAMP(vlh.login_time) - UNIX_TIMESTAMP(ADDDATE(?, INTERVAL -15 MINUTE))) > 0
06/24/15 01:17:49,653 [1384] DEBUG VT - Prepared sql query parameters : [::1,2015-06-24 01:17:49]
06/24/15 01:17:49,654 [1384] DEBUG VT - query being executed : SELECT * FROM vtiger_bruteforce
06/24/15 01:17:49,655 [1384] DEBUG user - Entering Users() method ...
06/24/15 01:17:49,655 [1384] DEBUG VT - Entering getColumnFields(Users) method ...
06/24/15 01:17:49,656 [1384] DEBUG VT - in getColumnFields Users
06/24/15 01:17:49,656 [1384] DEBUG VT - Prepared sql query being executed : SELECT tabid, name, ownedby FROM vtiger_tab
06/24/15 01:17:49,657 [1384] DEBUG VT - Prepared sql query being executed : SELECT tabid, name, ownedby FROM vtiger_tab
06/24/15 01:17:49,658 [1384] DEBUG user - Exiting Users() method ...
06/24/15 01:17:49,665 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM vtiger_tab
06/24/15 01:17:49,666 [1384] DEBUG VT - Prepared sql query being executed : SELECT id from vtiger_users where user_name=? AND deleted=0
06/24/15 01:17:49,666 [1384] DEBUG VT - Prepared sql query parameters : []
06/24/15 01:17:49,667 [1384] DEBUG user - Start of authentication for user: 
06/24/15 01:17:49,667 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM yetiforce_auth
06/24/15 01:17:49,668 [1384] DEBUG user - Using integrated/SQL authentication
06/24/15 01:17:49,668 [1384] DEBUG VT - Prepared sql query being executed : SELECT crypt_type, user_name FROM vtiger_users WHERE user_name=?
06/24/15 01:17:49,669 [1384] DEBUG VT - Prepared sql query parameters : []
06/24/15 01:17:49,669 [1384] ERROR PearDatabase_ - Rows Returned:0 More than 1 row returned for SELECT crypt_type, user_name FROM vtiger_users WHERE user_name=?
06/24/15 01:17:49,670 [1384] ERROR user - User not found: 
06/24/15 01:18:05,257 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:18:05,654 [1384] DEBUG VT - Prepared sql query being executed : select * from vtiger_organizationdetails
06/24/15 01:18:23,950 [1384] INFO VT - PearDatabase ->ADODB disconnect
06/24/15 01:18:24,203 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM `vtiger_bruteforce` LIMIT 1
06/24/15 01:18:24,204 [1384] DEBUG VT - Prepared sql query being executed : SELECT count(login_id) as cn FROM `vtiger_loginhistory` vlh WHERE STATUS = 'Failed login' && user_ip = ? && unblock = 0 && (UNIX_TIMESTAMP(vlh.login_time) - UNIX_TIMESTAMP(ADDDATE(?, INTERVAL -15 MINUTE))) > 0
06/24/15 01:18:24,204 [1384] DEBUG VT - Prepared sql query parameters : [::1,2015-06-24 01:18:24]
06/24/15 01:18:24,205 [1384] DEBUG VT - query being executed : SELECT * FROM vtiger_bruteforce
06/24/15 01:18:24,206 [1384] DEBUG user - Entering Users() method ...
06/24/15 01:18:24,206 [1384] DEBUG VT - Entering getColumnFields(Users) method ...
06/24/15 01:18:24,207 [1384] DEBUG VT - in getColumnFields Users
06/24/15 01:18:24,207 [1384] DEBUG VT - Prepared sql query being executed : SELECT tabid, name, ownedby FROM vtiger_tab
06/24/15 01:18:24,208 [1384] DEBUG VT - Prepared sql query being executed : SELECT tabid, name, ownedby FROM vtiger_tab
06/24/15 01:18:24,209 [1384] DEBUG user - Exiting Users() method ...
06/24/15 01:18:24,217 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM vtiger_tab
06/24/15 01:18:24,218 [1384] DEBUG VT - Prepared sql query being executed : SELECT id from vtiger_users where user_name=? AND deleted=0
06/24/15 01:18:24,219 [1384] DEBUG VT - Prepared sql query parameters : [admin]
06/24/15 01:18:24,219 [1384] DEBUG user - Start of authentication for user: admin
06/24/15 01:18:24,220 [1384] DEBUG VT - Prepared sql query being executed : SELECT * FROM yetiforce_auth
06/24/15 01:18:24,220 [1384] DEBUG user - Using integrated/SQL authentication
06/24/15 01:18:24,221 [1384] DEBUG VT - Prepared sql query being executed : SELECT crypt_type, user_name FROM vtiger_users WHERE user_name=?
06/24/15 01:18:24,221 [1384] DEBUG VT - Prepared sql query parameters : [admin]
06/24/15 01:18:24,222 [1384] ERROR PearDatabase_ - Rows Returned:0 More than 1 row returned for SELECT crypt_type, user_name FROM vtiger_users WHERE user_name=?
06/24/15 01:18:24,222 [1384] ERROR user - User not found: admin

viewer_debug

URI: /Yeticrm/install/Install.php, TYPE: GET
URI: /Yeticrm/install/Install.php?__vtrftk=sid%3Afe1a1d1b7db18681860a369c81a34d0ff8aaaf51%2C1435102374&lang=en_us&mode=Step2, TYPE: POST
URI: /Yeticrm/install/Install.php?__vtrftk=sid%3Acfc4097ffcf54b5b7b869635a27b67e4ff1f0188%2C1435102387&mode=Step3&lang=en_us, TYPE: POST
URI: /Yeticrm/install/Install.php?__vtrftk=sid%3A1b6ee1fdcf7ee7262dffd10692b9ffc85301cd4b%2C1435102393&mode=Step4&lang=en_us, TYPE: POST
URI: /Yeticrm/install/Install.php?__vtrftk=sid%3Ade67d68961964f30be10946b3462cf5872f4c776%2C1435102608&mode=Step5&lang=en_us&db_type=mysqli&db_hostname=localhost&db_username=sixforce&db_password=%25%266Force2015&db_name=sixforce_yeticrm&create_db=on&db_root_username=root&db_root_password=root&currency_name=Euro&admin=admin&password=Melissa_01&retype_password=Melissa_01&firstname=Arlindo&lastname=Maia&admin_email=arlindo.maia%40sixforce.pt&dateformat=dd-mm-yyyy&timezone=Europe%2FLondon, TYPE: POST
URI: /Yeticrm/install/Install.php?__vtrftk=sid%3A30ffcf71e361785617d480701c16a6cbe7096ca3%2C1435102877&mode=Step7&auth_key=228995af200cf2ceef0ba6f4516ba8b2&lang=en_us, TYPE: POST
URI: /Yeticrm/, TYPE: GET
VIEW: modules/Users/Header.tpl > modules/Vtiger/Header.tpl, FOUND: 1
DATA: APPTITLE, TYPE: literal
DATA: YETIFORCE_VERSION, TYPE: literal
DATA: PAGETITLE, TYPE: literal
DATA: SCRIPTS, TYPE: array
DATA: STYLES, TYPE: array
DATA: SKIN_PATH, TYPE: literal
DATA: LANGUAGE_STRINGS, TYPE: array
DATA: HTMLLANG, TYPE: literal
DATA: LANGUAGE, TYPE: literal
VIEW: modules/Users/Login.tpl, FOUND: 1
DATA: APPTITLE, TYPE: literal
DATA: YETIFORCE_VERSION, TYPE: literal
DATA: PAGETITLE, TYPE: literal
DATA: SCRIPTS, TYPE: array
DATA: STYLES, TYPE: array
DATA: SKIN_PATH, TYPE: literal
DATA: LANGUAGE_STRINGS, TYPE: array
DATA: HTMLLANG, TYPE: literal
DATA: LANGUAGE, TYPE: literal
DATA: MODULE, TYPE: literal
DATA: CURRENT_VERSION, TYPE: literal
URI: /Yeticrm/, TYPE: GET
VIEW: modules/Users/Header.tpl > modules/Vtiger/Header.tpl, FOUND: 1
DATA: APPTITLE, TYPE: literal
DATA: YETIFORCE_VERSION, TYPE: literal
DATA: PAGETITLE, TYPE: literal
DATA: SCRIPTS, TYPE: array
DATA: STYLES, TYPE: array
DATA: SKIN_PATH, TYPE: literal
DATA: LANGUAGE_STRINGS, TYPE: array
DATA: HTMLLANG, TYPE: literal
DATA: LANGUAGE, TYPE: literal
VIEW: modules/Users/Login.tpl, FOUND: 1
DATA: APPTITLE, TYPE: literal
DATA: YETIFORCE_VERSION, TYPE: literal
DATA: PAGETITLE, TYPE: literal
DATA: SCRIPTS, TYPE: array
DATA: STYLES, TYPE: array
DATA: SKIN_PATH, TYPE: literal
DATA: LANGUAGE_STRINGS, TYPE: array
DATA: HTMLLANG, TYPE: literal
DATA: LANGUAGE, TYPE: literal
DATA: MODULE, TYPE: literal
DATA: CURRENT_VERSION, TYPE: literal

 

![yeti zip](https://cloud.githubusercontent.com/assets/12982365/8320373/e84bc594-1a11-11e5-98c2-bea9493abc0c.png)

 

 
If I activated the debug as told me by email the starts and aborts immediately. The database is created but without any table:
$DEBUG_CONFIG = Array(
	// enable log4php -> cache/logs/system.log
	'LOG4PHP_DEBUG' => TRUE,
	
	// display sql queries in the browser during triggering
	'DISPLAY_SQL_QUERY' => TRUE,

	// stop the running process of the system if there is and error in sql query
	'SQL_DIE_ON_ERROR' => FALSE,
	
	// debug Viewer => cache/logs/viewer-debug.log
	'DEBUG_VIEWER' => TRUE,
	
	// Display Smarty Debug Console
	'DISPLAY_DEBUG_VIEWER' => FALSE,
	
	// sabre dav - This is a flag that allow or not showing file, line and code of the exception in the returned XML
	'DAV_DEBUG_EXCEPTIONS' => FALSE,
	
	'DAV_DEBUG_PLUGIN' => FALSE,

 

 

2nd try with debug:

$DEBUG_CONFIG = Array(
	// enable log4php -> cache/logs/system.log
	'LOG4PHP_DEBUG' => TRUE,
	
	// display sql queries in the browser during triggering
	'DISPLAY_SQL_QUERY' => FALSE,

	// stop the running process of the system if there is and error in sql query
	'SQL_DIE_ON_ERROR' => FALSE,
	
	// debug Viewer => cache/logs/viewer-debug.log
	'DEBUG_VIEWER' => TRUE,
	
	// Display Smarty Debug Console
	'DISPLAY_DEBUG_VIEWER' => FALSE,
	
	// sabre dav - This is a flag that allow or not showing file, line and code of the exception in the returned XML
	'DAV_DEBUG_EXCEPTIONS' => FALSE,
	
	'DAV_DEBUG_PLUGIN' => FALSE,

 
 
 

 
 
Database with tables but without any user.

Thanks in advance

AM,

**Comment by mariuszkrzaczkowski** [comment]
Check https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html
In logs can be seen only "DBTYPE not specified" as if you did not choose the type of database

**Comment by Armaia** [comment]
Hi Mariusz,

 

I’ve changed the parameters in my.cnf accordingly the information but yhe problem was not solved. I have not installation errors but now instead of HTTP Error 500, after I put the username and pass I have blank screen.

I attach the debug files where I can find the the admin user is not created. Can you help?

 

Thanks in advance,

 

Arlindo Maia 

 

De: Mariusz Krzaczkowski [mailto:notifications@github.com] 
Enviada: 24 de junho de 2015 14:41
Para: YetiForceCompany/YetiForceCRM
Cc: Armaia
Assunto: Re: [YetiForceCRM] YetiForce 2.0.0 - fresh instalation fails (#1139)

 

Check https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html
In logs can be seen only "DBTYPE not specified" as if you did not choose the type of database

**Comment by amicheals** [comment]
check you php version. it works best with php 5.5 and above

**Comment by Armaia** [comment]
Mysql: 5.6.17

PHP: 5.5.12

Apache: 2.4.9

 

De: amicheals [mailto:notifications@github.com] 
Enviada: 24 de junho de 2015 18:51
Para: YetiForceCompany/YetiForceCRM
Cc: Armaia
Assunto: Re: [YetiForceCRM] YetiForce 2.0.0 - fresh instalation fails (#1139)

 

check you php version. it works best with php 5.5 and above

**Comment by mariuszkrzaczkowski** [comment]
I tested it on a clean WAMP and everything works fine. 
Are all parameters during the installation process correct?

- Change .htaccess log_errors and display_errors to On
- Change max_execution_time in htacces and PHP.ini to a large value, e.g. 1000

The speed of the installation process is a common problem. A regular computer is simply too slow that is why there is not enough time to execute a script (max_execution_time )
Enter the suggested above changes and try to install the system.

**Comment by Armaia** [comment]
Hi,

 

I create a .htaccess file with the parameters you mentioned na finally I could install Yeti.

 

Thanks for your help.

 

Best Regards,

 

Arlindo Maia

 

De: Mariusz Krzaczkowski [mailto:notifications@github.com] 
Enviada: 1 de julho de 2015 08:18
Para: YetiForceCompany/YetiForceCRM
Cc: Armaia
Assunto: Re: [YetiForceCRM] YetiForce 2.0.0 - fresh instalation fails (#1139)

 

I tested it on a clean WAMP and everything works fine. 
Are all parameters during the installation process correct?

*	Change .htaccess log_errors and display_errors to On
*	Change max_execution_time in htacces and PHP.ini to a large value, e.g. 1000

The speed of the installation process is a common problem. A regular computer is simply too slow that is why there is not enough time to execute a script (max_execution_time )
Enter the suggested above changes and try to install the system.
