### ISSUE TITLE
[Feature] Related List > Summary | Details Down   

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11396]
Gotta relation m:m so from the native Related tab I can ADD and SELECT record, but when using nice layout: Summary Down or Details Down, I can see only ADD button. Should be allowed select too? May I have some advise on it?

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/74094026-dbd95200-4ada-11ea-80f9-261af80dccba.png)
