### ISSUE TITLE
How to Export Comments

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#11403]
### Description

How to Export "Comments"  of lead module.I want to export all the comments along with each record.is it possible in Yetiforce CRM?

![comments](https://user-images.githubusercontent.com/47585969/64306934-bef29d00-cfd7-11e9-9f5b-47d5252313cb.JPG)

**Comment by vovpff** [comment]
As for me simplest way to export comments directly from database.
