### ISSUE TITLE
[Question]     How to add Chat tab to a custom module? 

### ISSUE THREAD

**Issue by Maxpeg** [YetiForceCompany/YetiForceCRM#11402]
How to add Chat tab like in Accounts, or in the ProjectTask modules for a custom module?

**Comment by acsinsurancegroup** [comment]
My question to go with this is how can you just make the chat a part of the menu on the top bar instead of the floating and annoying icon that is always in the way towards the bottom of the screen now?

**Comment by bpabiszczak** [comment]
YetiForce 5.3

![image](https://user-images.githubusercontent.com/10197525/74094462-ffec6180-4ae1-11ea-8432-3a66971ccadf.png)

**Comment by rskrzypczak** [comment]
@Maxpeg it only works for modules in the hierarchy (https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app_data/moduleHierarchy.php#L4)
@acsinsurancegroup there is parameter in `config\Modules\Chat.php`

> /** True - chat button draggable, false - chat button in header. */
	public static $draggableButton = true;

**Comment by acsinsurancegroup** [comment]
Hi @rskrzypczak thanks so very much for your tip. However, I didn't see that code in my system. I am currently running 5.2 and although I see a lot of post about 5.3 I don't see it available for download anywhere and I have 5.2 doing what I need so would be scared to change when all my stuff is good right now. 

I added the code into the file I did have, rebooted server and everything and nothing. I still have the floating button. Any other thoughts?

**Comment by bpabiszczak** [comment]
You must wait for version 5.3 to be released

**Comment by acsinsurancegroup** [comment]
@bpabiszczak So there will not be an option to make this possible in 5.2 then? The only way would be to start completely over with 5.3?

**Comment by bpabiszczak** [comment]
You don't have to start again, just upgrade the system [when a new version appears].

**Comment by acsinsurancegroup** [comment]
Perfect, thank you sir :)
