### ISSUE TITLE
Error: Call to a member function getName() on boolean - When click on "Sales Invoice"

### ISSUE THREAD

**Issue by eMayam** [YetiForceCompany/YetiForceCRM#11400]
Hi, I was trying to optimise sales invoice fields relating to address, but suddenly the "sales invoice" module shows " Call to a member function getName() on boolean"  error when click on it. 

Please help to resolve this issue. 
![Sales Invoice error](https://user-images.githubusercontent.com/54782802/64275017-41d91080-cf62-11e9-9674-d87836c9543e.PNG)

**Comment by mariuszkrzaczkowski** [comment]
logs ?
