### ISSUE TITLE
Tworzenie nowego 'projektu' powiązanie z wieloma zgłoszeniami? [Question]           

### ISSUE THREAD

**Issue by marpas83** [YetiForceCompany/YetiForceCRM#11416]
Witam,
mając kilka zgłoszeń w systemie. W widoku głównym chciałbym wybrać/zaznaczyć kilka zgłoszeń i stworzyć z nich wspólny projekt. Następnie pracowałbym już na danym projekcie a w nim żeby było tylko pole wskazujące na powiązania z konkretnymi zgłoszeniami. Czy da się to zrobić?
1. Najlepiej tworzenie projektu z widoku modułu zgłoszeń po wybraniu tych odpowiednich.
2. Jeśli opcja 1 niemożliwa to jak stworzyć pole w module Projekt, gdzie będę mógł wskazać kilka róznych zgłoszeń? (ważne od róznych kontrahentów)

**Comment by bpabiszczak** [comment]
Da się! Tylko, że potrzeba do tego programistę :]
