### ISSUE TITLE
How to create Mass edit  button in the list of related records page

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#11410]
How to Create mass edit button in the list of related records

![Mass edit](https://user-images.githubusercontent.com/47585969/64403378-a78ce000-d0bb-11e9-92a7-51fc8bc8aa8c.JPG)

**Comment by z0lo13** [comment]
@guide5232 what you sent is not summary but the list of related records, a summary shows summary widgets.

**Comment by guide5232** [comment]
> @guide5232 what you sent is not summary but the list of related records, a summary shows summary widgets.

I have changed it .

**Comment by salvofan** [comment]
How did you fix it? I just need to do the same.
