### ISSUE TITLE
E-mails are not sent from crm roundcube

### ISSUE THREAD

**Issue by fratilitau** [YetiForceCompany/YetiForceCRM#11414]
I have a problem with yetiforce crm...it works great apart from sending e-mails. I can add my server info, read the e-mails, get them live etc but cannot send. When i push send it just says sending e-mails endlessly and doesn't send. Any idea what might be blocking the e-mail sending?

**Comment by sbouillon** [comment]
What is your environment? Check your ports also. Read the info needed to post an issue otherwise you’ll never receive responses here.
