### ISSUE TITLE
[Feature] [bug]  "Generate one PDF for many records"

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11425]
"Generate one PDF for many records" >>
This should print list of all records in current view or list of selected record. Currently if I tick 5 records I got 5 independent lists. This is wrong
Solution: Allow printing list without ticking any record or if they are ticked, print one document with all ticked rows.

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/64480077-58c96e00-d1c1-11e9-9997-746a017589e4.png)

**Comment by JohnMaverick** [comment]
This issue been closed but not resolved. https://github.com/YetiForceCompany/YetiForceCRM/issues/12545

**Comment by rskrzypczak** [comment]
![pdf](https://user-images.githubusercontent.com/10221999/74125659-2e4b6900-4bd6-11ea-87d5-e902b872c13d.gif)
