### ISSUE TITLE
[Design BUG]  Login Page

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1142]
ver. 2.0.171

![loginpage](https://cloud.githubusercontent.com/assets/1402355/8321927/df4d9780-1a46-11e5-9a8e-a380cc5219e2.JPG)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
could you explain what is wrong with it? And how would you like it to be?

**Comment by waw555** [comment]
![login](https://cloud.githubusercontent.com/assets/1402355/8352552/791cd6d8-1b4f-11e5-832a-f0ed1c21c7ec.JPG)
