### ISSUE TITLE
[bug] PDF - Selected by default check box

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11428]
"Selected by default" unnecessarily getting checked each time PDF template is edited. It annoying when you designing 15 different reports for the same module.

**Comment by vovpff** [comment]
Are you tested gitdev?

**Comment by waran70** [comment]
On upgraded to 5.2

**Comment by vovpff** [comment]
And on gitdev also

**Comment by vovpff** [comment]
Yahooo
