### ISSUE TITLE
[Design BUG] Quickly create

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1143]
Text merges, you expand the column

![quickcreate](https://cloud.githubusercontent.com/assets/1402355/8321948/3db2a84c-1a47-11e5-9dbd-542d52a4ff2f.JPG)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/263f5a6d6770d994e48a1f5eb14b311d3bb45518
