### ISSUE TITLE
[bug] PDF - variable group "Fields from dependent modules"

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11431]
group "Fields from dependent modules" shows set of various variables (what dont works anyway) but NOT those what are dependents to processed module. 

"Accounts"  have related module "Contacts". If we designing template for "Accounts" a Contacts is a related entity. But if we designing PDF for Contacts, an "Accounts" module should be in list of "Fields from dependent module". It could be modified as follows for better understanding:
"Accounts" - parent module 
"Contacts" - related module
So "Fields from dependent modules" could be renamed to "Fields from the parent module".
Here is also some thoughts about type of relation 1:1 or 1:M or M:1 or M:M it could be better organized. Variables Related-Parent (Dependent to) are based on UItype10

**Comment by bpabiszczak** [comment]
That's not true. The contacts are on a completely different level [level 4] and the accounts on the level 1. You can change it if you want, but you need a developer.
