### ISSUE TITLE
[bug] Call to a member function get() on bool.

### ISSUE THREAD

**Issue by ad1rie1** [YetiForceCompany/YetiForceCRM#11437]
# 🐞 bug report

### ⁉️ Describe the bug
When we access to https://vps.brain-networks.net/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8
We have the error : 
![image](https://user-images.githubusercontent.com/1949622/64518965-844c7580-d2f3-11e9-99b9-23a6d46b78b8.png)

We have the tracelog : 
#0 cache/templates_c/basic/02d1a58eee556628b516e515e812ea04410cc835_0.file.ListContents.tpl.php(66): OSSMailView_Module_Model->getSettingLinks()
#1 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5d760c48c3c881_35829198(Object(Smarty_Internal_Template))
#2 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#5 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#6 include/runtime/Viewer.php(204): Smarty_Internal_TemplateBase->fetch('modules/Setting...')
#7 modules/Settings/ModuleManager/views/List.php(30): Vtiger_Viewer->view('ListContents.tp...', 'Settings:Module...', true)
#8 include/main/WebUI.php(182): Settings_ModuleManager_List_View->process(Object(App\Request))
#9 index.php(24): Vtiger_WebUI->process(Object(App\Request))
#10 {main}

### 👎 Actual Behavior
Error and blocker loading of webpage

### 👍 Expected Behavior
Working :)

### 🌍  Your Environment 
Yetiforce 5.2
PHP 7.3
Linux Ubuntu 16.04

**Comment by ad1rie1** [comment]
[log.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3589707/log.log)

**Comment by ad1rie1** [comment]
[log.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3589719/log.log)

**Comment by Hernandesz** [comment]
Did you fix the issue, i really have problems with this type o problem, need hel how to fix the problem please!

**Comment by ad1rie1** [comment]
the patch writed by @mariuszkrzaczkowski  as fixed the issue for me, maybe update your yetiforce ;)

**Comment by drakub** [comment]
> 
> 
> the patch writed by @mariuszkrzaczkowski as fixed the issue for me, maybe update your yetiforce ;)

Can you send me this patch. I am also facing the same issue
