### ISSUE TITLE
[Question]          Class 'AppConfig' not found...

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#11442]
Po aktualizacji z 5.1 do 5.2

🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅-->

### Description
Witam, mam problem z własnymi modułami - po aktualizacji z 5.1 do 5.2 ...
Class 'AppConfig' not found 
Czy jest na to jakaś rada.. żeby szybko naprawić ?

**Comment by rskrzypczak** [comment]
Zamień AppConfig => App\Config

**Comment by zimart** [comment]
Gdzie mam zmienić :( ? Widzę także że przepisane praktycznie wszystkie inventoryfields...

**Comment by bpabiszczak** [comment]
A moduł o których piszesz, to ten utworzony z panelu czy sam go utworzyłeś skryptem?

**Comment by zimart** [comment]
Utworzony w panelu + własne inventory fields...

**Comment by zimart** [comment]
Powoli dochodzę do sedna... opiszę jak ogarnę wszystkie problemy ... i kolejny temat PDF.. 
Call to a member function getType() on boolean
