### ISSUE TITLE
May i restrict workflow fire in working hours and working days?

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#11453]
By using Business Hours and SLA Policy module , may i restrict workflow fire in working hours and working days?.
(Workflows don't fire on public holidays,Saturday,Sundays and Evening 5PM to Morning 9AM).Is it possible?

**Comment by davide-alghi** [comment]
Hi,
you cannot run **only** workflows into working days/hours.
What you can do is to run CRON, (it means all CRON jobs - including workflows) into working days/hours.

**In this way all CRON jobs are stopped out CRON timing.**

Here a CRON timing example

```*/5 9-17 * * 1-5```

This run CRON every 5 minutes from Monday to Friday between 09:00 and 17:00 o'clock.
**You cannot exclude public holidays**

**Comment by guide5232** [comment]
I want to run all workflow for every day except ticket module workflows. Is it possible?

**Comment by davide-alghi** [comment]
It isn't.
It's possible only programmatically: If you are going to modify YF core I discourage it.

**Comment by z0lo13** [comment]
@guide5232 @davide-alghi without modifying the core you can create a custom php function.

**Comment by guide5232** [comment]
> @guide5232 @davide-alghi without modifying the core you can create a custom php function.

Could you please give me one example of custom php function or sample function file.

**Comment by davide-alghi** [comment]
From my point of view there could be added a new "Trigger Type" like 10 => 'DAY_TIME_RANGE' and then manage it into tpl, WorkflowManager and so on. But this requires YF core modification.
@z0lo13, I'd be curious to know how to do this, or an alternative idea, without modify YF core.

**Comment by guide5232** [comment]
@z0lo13 @davide-alghi 
 I have written code like this 

function isweekend($date){
    $date = strtotime('*/5 9-17 * * *');
    $date = date("l", $date);
    $date = strtolower($date);
    echo $date;
    if($date == "saturday" || $date == "sunday") {
        return "true";
    } else {
        return "false";
    }
}
We have added new function database.But it is not working.
I want to control workflow runs 9 AM to 17 (Monday to Friday )PM is it possible using above code?.

**Comment by davide-alghi** [comment]
Hi Guide,
I see some imperfections into your function :(

anyway ... please can you explain us step by step what have you done? step by step please
 - Which files and where have you created/duplicated?
 - Where have you pushed isweekend function?
 - What means ```We have added new function database```: did you create a database store procedure?

**Comment by guide5232** [comment]
We written code in This path : 
1. newyeti\modules\HelpDesk\workflows\HelpDeskWorkflow.php
2. we inserted new function name in  "com_vtiger_workflowtasks_entitymethod" table.
3. we have created new workflow and we have created Invoke custom function task .

**Comment by z0lo13** [comment]
@guide5232 
your function above is only checking the day of week i do not see the function if True.
please add you full code.

1. HelpDeskWorkflow.php is already a class function, create another class.
