### ISSUE TITLE
Class 'Config\Components\Branding' not found - Update from 5.1.0 to 5.2.0

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#11456]
I just updated Yetiforce and the above error appears.

Please instruct me on escaping it because we have about 20 employees that depends on this installation. :) 

Thanks

**Comment by liviubbo** [comment]
I dont have a footer in the installation. The footer is missing. I dont know how to make it appear.

**Comment by liviubbo** [comment]
![11](https://user-images.githubusercontent.com/42461923/64613598-d3b7a200-d3d6-11e9-8acb-2679c7fef468.jpg)

**Comment by liviubbo** [comment]
Can someone from Yetiforce help me ? I also have 2 hours of free support from this ticket : #8524

**Comment by waran70** [comment]
experimenting on production?
![sideeye2](https://user-images.githubusercontent.com/6852348/64616619-20b36c80-d407-11e9-8419-88c1699d6051.jpg)

**Comment by mariuszkrzaczkowski** [comment]
show what is in the logs

**Comment by liviubbo** [comment]
Yes, unfortunately experimenting on production. Too idiot to make on test. :( 
What logs ? From update log ?

**Comment by liviubbo** [comment]
[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3595830/updateLogsTrace.log)

**Comment by liviubbo** [comment]
Bump ...

**Comment by liviubbo** [comment]
Its nice that people from YetiForce are joining. Like i said, i have won 2 hours of free support. Its urgent for me to fix this. For you guys, it will take about 10 minutes. Can someone help ? 😨

**Comment by liviubbo** [comment]
I was searching for 3 hours on entire GitHub and files/folders and dont find any reference to this. 
BUMP again! 

Search continues

**Comment by liviubbo** [comment]
@mariuszkrzaczkowski - is that file enough ?

**Comment by rskrzypczak** [comment]
This file is auto-generated.
if you don't have it, it means that it has been updated incorrectly.
You probably got a message.

> Some errors appeared during the update.
		We recommend verifying logs and updating the system once again.

**Comment by liviubbo** [comment]
Ok! So, whats the file that i am missing ? I was checking all the files from the GitHub and comparing them with the files on my server. Problem is that all look the same.

**Comment by liviubbo** [comment]
PS : the message didnt appear. The errors message

**Comment by liviubbo** [comment]
@rskrzypczak  - So, whats the fix, or whats the exact problem ?

**Comment by liviubbo** [comment]
Ok, if someone answers, can please explain like for a dumb person that i am ? 
For example : you need the file x updated or any other change
I am a user of more than one year of YetiForce and also with 2 hours of support gifted by you guys. Its not normal to gift someone something and not giving them when they need. 
Its a very quick fix for you guys at YetiForce.
I was searching on my own the fix but, i didnt find nothing. All files look the same as in YetiForce repository but, not working as it should.

**Comment by liviubbo** [comment]
PS :  i also contributed answering users questions as i knew, as i often as i knew the answers.

**Comment by rskrzypczak** [comment]
change version to 5.1.0 in config/version.php and try tu update again.

**Comment by liviubbo** [comment]
I have changed but, i dont have the options in the menu to go to modules/installation e.t.c.. The error still appears. I have deleted all cache and cookies before trying.

**Comment by rskrzypczak** [comment]
It's really difficult for me to say something positive because you can have many errors in your system.
All we advise you here is only a temporary patch of error, which can be tragic in the future.

Try temporarily creating the file manually in config/Components

![image](https://user-images.githubusercontent.com/10221999/64626002-67946880-d3ed-11e9-8ebb-50f7da4c0cb6.png)

**Comment by liviubbo** [comment]
I have created an new php file with that text that you provided. I have uploaded it to the directory your specified. Same error appears.

**Comment by z0lo13** [comment]
off: Never update test on production

**Comment by liviubbo** [comment]
So, anyone any other fix ? :(

**Comment by liviubbo** [comment]
I was thinking about it, but i tought maybe someone from YetiForce will reply ! Normaly it was an update package that went wrong on standard installation. 
Even if i have 2 hours of free support they dont reply. 
Wierd.

**Comment by paula-w** [comment]
Please send us the access data to your CRM to sla@yetiforce.com so we can check what's wrong with your system.
And in the future remember to ALWAYS update the test environment first to avoid situations like these.

**Comment by liviubbo** [comment]
Strange that no one knows the fix for this. Normally alot of people join in a conversation and say their oppinions. Now .......... Normaly, there are xxxxxxxxx posibilities. Now, everybody just : dont update on production. How else should i test a installation that have thousands of entries and more than 20GB total ? Should i keep always a copy of this installation ?

**Comment by waran70** [comment]
You are basically annoying, and if you don't stop you will have no help at all

**Comment by liviubbo** [comment]
Its your oppinion. Mine is just that i need to say this loud and clear ! Because i made an update, official one, i have said my problem and everybody just : production, production. No one says one word about how to fix this. Also, i have FREE SUPPORT and until now, not given. I dont expect necesarilly someone to fix this for me, but man, just telling me what could have gone wrong and were to look. If thats annoying, than yes, i am annoying. And @waran70 , btw, thanks for all your help in the past.

**Comment by liviubbo** [comment]
And btw, as i said, alot of comments on my mistakes, production, too much writing, but no solutions or hints ! Thank you all guys ! You are not owing me this, but at least, if someone writes, please write at the subject, not riddling questions or quarter of hints.

**Comment by liviubbo** [comment]
And until now, as i could, i have also helped here on this Git. But now, when i am in trouble i am annoying. Nice !

**Comment by waran70** [comment]
I cited fact: "annoyance"
and following consequences: "no help"
Here is nothing personal. 
Try to copy over original footer from git to: layouts/basic/modules/Vtiger/footer.tpl

**Comment by liviubbo** [comment]
@paula-w - I have sent the details. Please tell me if someone is working on the issue. If not, i will make a backup restoration. For me, its important to know if someone is looking into the issue or not. If yes, when ? If you dont want to do it, let me know so i can do a restoration.

**Comment by liviubbo** [comment]
@waran70  - Again, thank you very much for all your help that you provided. You are a good man. But, i will write until someone will give me that FREE HOURS that i deserve or tell me directly that they dont want to give me. I am not trying to be annoying. What i am trying to do is  : FIX MY PROBLEM !

**Comment by liviubbo** [comment]
As you can see, i am a little stressed by this ! 20 people waiting for me. Ok, production, production, production, test, e.t.c. It was an official update package.

**Comment by liviubbo** [comment]
Strange that no one from YetiForce can tell me : look there, try this. It takes 1 second !

**Comment by liviubbo** [comment]
@waran70 - i have done this by yesterday (copy footer.tpl) and its not solving the issue.

**Comment by mariuszkrzaczkowski** [comment]
@liviubbo 
1. already checking, 
2. be patient, 
3. monitor your email

**Comment by liviubbo** [comment]
Thanks YetiForce for fixing this ! YetiForce helped ! If anyone was offended by what i wrote, or, how much i wrote, thats that. I was stressed.

**Comment by krzysztofgit88** [comment]
I have the same problem, can I ask for information on how to solve the problem?
