### ISSUE TITLE
[bug] cron error ??

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#11463]
YETIFORCE 5.2

I can't log in to the admin module

cron.log

Content-type: text/html; charset=UTF-8

<br />
<b>Parse error</b>:  syntax error, unexpected ']' in <b>/home/eclansi/public_html/alpina/app_data/cron.php</b> on line <b>2</b><br />

logs/cron_error.log

2019-09-11 08:15:02 - syntax error, unexpected ']'

**Comment by mariuszkrzaczkowski** [comment]
delete this file app_data/cron.php

**Comment by fbojan** [comment]
Thanks mariuszkrzaczkowski
