### ISSUE TITLE
[Question] List / Overview for all variables usable in invoice / quote [PDF]

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11466]
Hi,
Is there somewhere a doc or Git-Issue about a list/overview for all usable variables for PDF inoices and quotes?

# 1. Variable List
Would be great to have a variable-list, instead to wriggle through the sales invoice and others.
Google, Source-Code and «Git-Issue search» could not help.

Did someone has a link or hint, where I can find a list about:

Would be great to get all the variables in one place for stuff like
$(relatedRecord : accountid|accountname|Accounts)$
$(organization : 1|company_name)$
$(custom : CurrentPage)$/$(custom : AllPages)$

# 2. change format on the fly
I also would like to name the invoice with the $(record : issue_time)$ but not like printed in invoice «tt.mm-jjjj». Instead it should output like «jjjjmmtt» so it would easy to find/sort with.
#### Is there a way to get the $(record : issue_time)$ in other format then for the invoice print-out without change the user-settings; only to format other in field «File Name»?

# 3. Calc with variable-values
Is there some doc with a list about all calc-examples those are usable with YetiForce Variables. 
Something like 
$calc((record : sum_gross)/3)$

Thank you for help/hint
Martin

**Comment by vovpff** [comment]
I'm also interested.

**Comment by mariuszkrzaczkowski** [comment]
see it
![image](https://user-images.githubusercontent.com/10198654/64694663-7553f780-d49a-11e9-901c-d32126798266.png)
https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=Edit&record=33

**Comment by mad99** [comment]
Hi mariuszkrzaczkowski,

### 1. Variables
thank you, in the meantime I found also this part in the YetiForce GUI.
Tried with this also...

#### But it is hard to «find in the pull-down-list
- the right «description-name» in the drop down.
- the linked «variable_name» in the code (below in the form-fields used from the sales invoice example)

Would be great to get a list with all possibilities/variables without «drop down». ;o)
To get fast to the searched term...

___
Do you or maybe someone else have information also about 
### - 2. Change on the fly?
### - 3. calc with var-value?

**Comment by mariuszkrzaczkowski** [comment]
2. see it  $(record : modifiedtime|format=Y/m/d)$ https://github.com/YetiForceCompany/YetiForceCRM/commit/17e2c662034f193115ec84fdb70f5af2469fe4ee

**Comment by bpabiszczak** [comment]
There is no additional documentation
