### ISSUE TITLE
[Question]  Update language         

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#11468]
Question! As I translate YETIFORCE into Slovenian via crowdin.com/translate/yetiforcecrm, I am interested in the update process in the current version I am using. 

thanks

**Comment by mariuszkrzaczkowski** [comment]
Prose looks like this:
All changes made on Crowdin are from time to time added to https://github.com/YetiForceCompany/YetiForceCRMLanguages
A CRM system downloads from https://github.com/YetiForceCompany/YetiForceCRMLanguages
By default, it downloads from the directory with the version number, if you enable the developer mode, it downloads from the Developer directory, which is the developer branch.

**Comment by fbojan** [comment]
mariuszkrzaczkowski .Thanks for the reply.
