### ISSUE TITLE
[bug] Illegal value has been entered for this field type. Field name: tax, Module: FInvoice, Value: 50.388

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11469]
Hi,
I'm searching for a solution to create a «part payment invoice»:

One approach could be to set a «Discount of 66%» to get 34% of the full amount for the first invoice of three in total.

If I fill 66 (%) in the field «Discount» YetiForce calculate all right and also changed the amounts.

But when I click «save» there is an error:

Illegal value has been entered for this field type. Field name: tax, Module: FInvoice, Value: 50.388

![Bildschirmfoto 2019-09-11 um 11 04 23](https://user-images.githubusercontent.com/6169308/64683891-66fae100-d484-11e9-95a5-9d335509c8b9.png)

So I guess there is an error/bug in the system, when the discount is bigger than 50.388 I guess.

Hope will help others. 

Maybe someone has a hint, how it is possible to create «üart payment invoices» with YetiForce.
https://github.com/YetiForceCompany/YetiForceCRM/issues/11467

Regards
Martin

**Comment by davide-alghi** [comment]
Hi Martin,
what about your YF version?

You are speaking about discount percentage, but the error is relative to tax ... something I don't understand

**Comment by mad99** [comment]
Hey davide-alighi,
thank you for the question.

Version YetiForce 5.2.0

Yes, I also don't understand:

Without Discount, there is no error, the PDF will create fine.

### Then I click on «set» in the box «Discount»
![Sales invoices Edit-Click Discount summary set](https://user-images.githubusercontent.com/6169308/64693676-168d7e80-d498-11e9-966a-271195d8d0ce.png)

### All is fine -> then I add 66 (%)
![Sales invoices Edit add 66](https://user-images.githubusercontent.com/6169308/64693708-27d68b00-d498-11e9-9124-8d75f07e41aa.png)
### And press «save»

![Sales invoices Edit - discount is calculated](https://user-images.githubusercontent.com/6169308/64693754-46d51d00-d498-11e9-9c08-0eb5b5cade28.png)
### All is fine -> then I click «save» for the invoice:
![Sales invoices Edit -click save](https://user-images.githubusercontent.com/6169308/64693777-59e7ed00-d498-11e9-9f21-227351c7a7c6.png)

## And then the error is there:
![Bildschirmfoto 2019-09-11 um 11 04 23](https://user-images.githubusercontent.com/6169308/64683891-66fae100-d484-11e9-95a5-9d335509c8b9.png)


### I guess the error is wrong «texted». Or something is wrong compound in the code.
I dont no why there is the information about «tax» instead of «discount». 
But I did only change the «discount».

Maybe the calculation from the tax has some limits and is depending on filed discount...

Hope information will help to solve the problem/bug.
Regards Martin

**Comment by mariuszkrzaczkowski** [comment]
Test this change
https://github.com/YetiForceCompany/YetiForceCRM/commit/b91f7b1b92a801f3bd06c66f64050b9bee983031

**Comment by mad99** [comment]
Hey mariuszkrzaczkowski

Have wrote a dirty trial_and_error file: backup'd «Validator.php» and changed on the server code direct.
There is no Error-Throwing left.

## So the bug seams to be fixed in the next update ;o))
Thank you, will leave the «hot-fix» in the Validator.php file.

Regards Martin

**Comment by hanybmw** [comment]
Hey  mariuszkrzaczkowski many thanks
