### ISSUE TITLE
[Question] Solution to Iterate/print elements/records of an invoice without a box [PDF]

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11471]
I would like to print invoices without the default box-layout (html-table with border/head/body/..).

### Iterate through records without box/table layout?
Is there a solution to iterate trough all records without the default and "fixed" box:
- $(custom : ProductsTableDescription)$
- $(custom : DynamicInventoryColumnsTable)$
- $(custom : ProductsTableShortVersion)$

So I could define an own Layout for the invoice?

### Or is there a way to change the box/table layout?
Would like at least to change the grey background and the border-style from the table.
Is there maybe a particular css-file for?

I can NOT find anything similar in «yetiforcepdf» source-folder.

Would be great to get some hints/docs/links.

Regards and thank you
Martin

**Comment by davide-alghi** [comment]
Hi mad99,
you can create your custom function. Into app/TextParser you can find all available functions (class into single php file)
If you are experienced with PHP, you can
1. duplicate (copy/paste) a similar / base (start point) built-in function (PHP file)
2. rename it
3. modify the new one
4. set the class name with the new filename of new php file
5. set $name with some label (that you'll set/translate in BE language section)
6. play with the code into process() function: the return value need to be a html string

**Comment by mad99** [comment]
Hey davide-alghi,
your information helped me a lot to know the TextParser code I found by accidence, while searching solutions in source-code, is the right place and to write an own TextParser is the right solution.

Thank you very much
Martin
