### ISSUE TITLE
[Question]           

### ISSUE THREAD

**Issue by nickallett** [YetiForceCompany/YetiForceCRM#11476]
### Description

Hi,

I would like to add a product’s part number to quotes, vendor enquiries, etc. 

In the file “ProductsTableShortVersion.php” I have added the field name “productcode” however it does not create a column and show data. 

Code Snippet @ Line 46: $fieldsColumnQuotes = ['Quantity', 'Name', 'productcode', 'UnitPrice', 'TotalPrice'];

Current Output

Item Name | Quantity | Sales Price | Net
-- | -- | -- | --
Example Product 1 | 1.00 | 100.00 | 100.00
Example Product 2 | 1.00 | 100.00 | 100.00
|  |  |  | 200.00

Desired Output

Part Code | Item Name | Quantity | Sales Price | Net
-- | -- | -- | -- | --
CD100021 | Example Product 1 | 1.00 | 100.00 | 100.00
CD154422 | Example Product 2 | 1.00 | 100.00 | 100.00
|  |  |  |  | 200.00

Could you please help. Thank you.

**Comment by vovpff** [comment]
@nickallett this is not possible. You can add column to module. After that you need to map this field to product field. In this case product code will be pulled when you choose product. After that you need to add column name to function what posted by @mariuszkrzaczkowski . You can change visibility of product code column. Really this works but has some faults like no auto pulling updated data from Products.

**Comment by mariuszkrzaczkowski** [comment]
now it is possible
added support for variables in inventory columns, e.g.

$(inventory : type=table columns=(translate : Products|Part Number)||(record : productcode),name,qty,unit,net , href=no)$

$(inventory : type=table columns=Product code||(record : productcode),name,qty,unit,net , href=no)$

(translate : Products|Part Number) = column label
(record : productcode) = column value
