### ISSUE TITLE
[Question] Release Portal 2

### ISSUE THREAD

**Issue by metrotyranno** [YetiForceCompany/YetiForceCRM#11486]
Portal 2 was said to release with 5.2 but it hasn't yet?

When will portal 2 release?

**Comment by acsinsurancegroup** [comment]
2-3 weeks? That was almost 7 weeks ago. Any updates?

**Comment by bpabiszczak** [comment]
For now only the beta version [internal].

**Comment by acsinsurancegroup** [comment]
@bpabiszczak Thanks for the update :) Any idea on potential release date?

**Comment by bpabiszczak** [comment]
No

**Comment by acsinsurancegroup** [comment]
@bpabiszczak Ok, thanks.
