### ISSUE TITLE
[bug] Zła waliadacja zapisu - przy rabacie...

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#11489]
Wersja 5.2
Sytuacja:
oferty, zamówienia - nie ważne - 

wybór rabatu grupowego - przy jednej pozycji artykułu - działa
po dodaniu kolejnej pozycji - 

Incorrect request

Illegal value has been entered for this field type. Field name: discount, Module: SQuotes, Value: 25.5068

Przetestowane na stable ... 
Szukałem u siebie problemu... ale.... Czy jest szansa na poprawkę ?

**Comment by bpabiszczak** [comment]
Sprawdziłem i jak dla mnie działa, jeżeli według Ciebie nie działa na gitdeveloper i gitstable to nagraj filmik
![image](https://user-images.githubusercontent.com/10197525/74094798-7cce0a00-4ae7-11ea-945e-5d520e1c5ae0.png)
