### ISSUE TITLE
[Question] Related record list - how to add empty space between            

### ISSUE THREAD

**Issue by TonyM15** [YetiForceCompany/YetiForceCRM#11492]
Hi
how to add empty space - let say 50px - between two variables of related records list?

Like that:
$(relatedRecordsList : Activity\|custmobilenumb,EMPTY_COLUMN_50PX,assignedsupervisor )$

**Comment by mad99** [comment]
Hi TonyM15,
Again I'm novice in YetiForce. But when I study the method from 
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app/TextParser.php#L719
It seams to be hardcoded Tables.

Maybe you can use some css-stylesheet with 
`"<td class=\"col-type-{$fieldModel->getFieldType()}\">{$value}</td>";`

I'm also waiting on some answers for your [Question about CSS](https://github.com/YetiForceCompany/YetiForceCRM/issues/11493).
If you have a solution for this, the same would go for table-columns.

Hope the link to related code helps.
Regards
Martin

**Comment by bpabiszczak** [comment]
Unnecessary addition ;) This must be written by the programmer.
