### ISSUE TITLE
[Question] Numery porzadkowy (pl)

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#11496]
Jak wyrdukowac pdf z numer em porzadkowy - related list?

**Comment by bpabiszczak** [comment]
Należy dodać tą opcje bezpośrednio w skrypcie generującym tabele w PDF.

**Comment by waran70** [comment]
I see you guys talking about lists order number.. is there any way to get such thing working out of the box in next release? It often important thing...
