### ISSUE TITLE
PDF Template

### ISSUE THREAD

**Issue by erikgtz** [YetiForceCompany/YetiForceCRM#11491]
Hi. 

I need to move currency simbol to left and add product image to PDF, I think I need to modify the following variable:

$(custom : ProductsTableShortVersion)$ 

Can you tell me where I can do it? 
[SQuotes_127_2019_09_12 (6).pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/3607479/SQuotes_127_2019_09_12.6.pdf)

**Comment by mad99** [comment]
Hey erikgtz,
I'm a novice in YetiForce and struggle also trough all the PDF-needs and problems, so enjoy my recommendation with caution.

### My Solution
In short: 
The **variable «ProduchtsTableShortVersion»** is the **output from Class ProductTableShortVersion** under: 
/app/TextParser/ProductsTableShortVersion.php

So if you would like to change something in the layout of this table-layout I suggest:
1. go to /app/TextParser/ProductsTableShortVersion.php
2. copy the file
3. rename it with e.G. «ProductsTableShortMyVersion.php»
4. Change the Classname and property $name in Class to the same ProductsTableShortMyVersion and 'LBL_PRODUCTS_TABLE_SHORT_MY_VERSION'
5. Change your needs.
6. Use in invoice or quotes the «$(custom : ProductsTableShortMyVersion)$»

### It works
I did exactly like I write and now I have an invoice/quote like I need.
Hope my suggestion helps to find a solution.

Regards
Martin

**Comment by erikgtz** [comment]
Thanks a lot.

That's exactly I was looking for.

**Comment by vovpff** [comment]
@erikgtz could you provide your pdf function just as example?
