### ISSUE TITLE
[Question] Link in PDF?

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11498]
Hi,
sorry next struggle with PDF-rendering...

I would like to use links in sent invoice/qote PDF, so customers can click simple in the PDF to redirect to a particular page or telefon-number.

### My Tries all end in error / No link :o(
Tried with:
- `<a href="https://www.mywebsite.com" style="color:#CC44DD">MyWebsite.com</a>`
- `<a href="tel:+32232323232">+3223 232 32 32</a>`

#### - Should this possible in YetiForcePDF but is not work/bug?

Thank you for your thought and experiences
Regards
Martin

**Comment by apcloic** [comment]
@mad99 
AFAIK, it works out-of-the-box, at least for emails and urls links.
Did you try on the [test version](https://yetiforce.com/en/download) ?

**Comment by vovpff** [comment]
look for `PURIFIER_ALLOWED_DOMAINS` parameters in configuration.
