### ISSUE TITLE
[bug] Pdf templater - cannot manipulate with colors

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11494]
See attached. I changed only color of variable. All get messed. If I remove format things goes OK. 
WYSWIG needed :-)
[report.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/3608413/report.pdf)

**Comment by bpabiszczak** [comment]
This is open source, if you can't do something in the configuration panel, it can be changed by the programmer.
