### ISSUE TITLE
[Question]: Does anybody know how to «underline» text in PDF?          

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11497]
Hi,
I tried all known solution to underline ___________ text in PDF YetiForcePDF.

tried with:
- `<div style="text-decoration:underline;">TEXT</div>`
- `<div><u>TEXT</u></div>`
- `<div> <span style="text-decoration:underline;">TEXT</span></div>`
- `<div> <u style="text-decoration:underline;">TEXT</u></div>`
- `<div> <span style="text-decoration:underline;"><u style="text-decoration:underline;> TEXT</u></span></div>`
- `<div><p style="text-decoration: underline;">TEXT</p></div>`

### Question:
- Any idea, what I do wrong?
- Or is it not possible to underline text in PDF-parsing?
- Or is it a bug?

Thank you for help
Regards
Martin

**Comment by z0lo13** [comment]
not possible yet ;(, i have managed to create a table and enable only bottom border

**Comment by mad99** [comment]
Hey @z0lo13,
Thank you for the information.
I also thought about the bottom border from table.
But in my invoice layout it would be break the hole style.

So I have to do without line under the title. It's a pitty ;o)
Anyway thanks
