### ISSUE TITLE
[Question] Simple Description or Doc for condition in recordsList?

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11505]
Hi,
I'm on the trail to find a solution for  an [invoice with payment-parts](https://github.com/YetiForceCompany/YetiForceCRM/issues/11467).
For this I should use a query like in the TextParser.php Method «recordsList()».

There the incode doc means:
`/**
	 * Parsing records list.
	 *
	 * @param string $params Parameter construction: ModuleName|Columns|Conditions|CustomViewIdOrName|Limit, Example: Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]||2
	 *
	 * @return string
	 */
	protected function recordsList($params)
`
### Problem
It is really hard to figure out with trial&error 
***what the hack «a» means in the condition?***

### Question: How I have to write the Condition?
- Does anybody know a place where this condition is described (doc/link/google)?
- Or could any experienced YediForce User give me a simple explanation?

### Target
I would like to ***query "all" records from a particular invoiceId*** (exactly id from the current invoice ;o))
Means something like:
`$recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid|[[["finvoiceid","a","364"]]])$`

### Result
I get NO results by trial&error. Only if I delete the condition totally, then I got all paymentsIn records. But this is not the solution at all...
### My Need
Would be great anybody could help me to find **the right conditions-array-key-value**.

- Maybe I have to fill out something different then «second part» "a". 
- Or I have to fill in INT different then text.

**I can't find docs or help in Git-Search or Google.**
### Heaven
When I understand the function of recordsList(), I will have the ability to code an own TextParser for my need.

### Used for Part-Payment Invoice
So within this TextParser I can subtract the paymentsIn from the Total Amount. 

That would help a lot for find a solution to code an [invoice with payment-parts](https://github.com/YetiForceCompany/YetiForceCRM/issues/11467).

Thank you for help
Regards
Martin

**Comment by mariuszkrzaczkowski** [comment]
"a" is an operator, to understand this you need to see how the conditions in querygenerator work

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app/QueryGenerator.php

**Comment by mariuszkrzaczkowski** [comment]
operators vary depending on the field type
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/app/Conditions/QueryFields

**Comment by mad99** [comment]
Hey @mariuszkrzaczkowski,
Thank you great, your hint helps a lot to see a bit deeper into YetiForce.

Unfortunately I tried all the possible Operators and at the end, the output is not filtered by condition. All is print out (2 only in the database).

I guess the use of the recordsList should be fine, because of the perfect filtering with Contacts.
I tried all from field as Integer and also field as ID. Because I can't figure out if finvoiceid is used as ID or INTEGER.
#### Trial but no filtering by condition:
The output are with all condition-trial 2 records (all of them) instead of only 1 :o((...
`TEST ZAHLUNGEN:$(recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid)$
TEST CONTACTS :$(recordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","dro"]]]||2)$
TEST ZAHLUNG 2 Operator A:$(recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid|[[["finvoiceid","a","Webauftritt Basis"]]]|)$
TEST ZAHLUNG 3 Field isINT Operator equal inheritedFromBase(Equal):$(recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid|[[["finvoiceid","e","368"]]]|)$
TEST ZAHLUNG 3 Field isINT Operator equal without "" inheritedFromBase(Equal):$(recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid|[[["finvoiceid","e",368]]]|)$
TEST ZAHLUNG 4 Field isID Operator S(like):$(recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid|[[["finvoiceid","s","368"]]]|)$
TEST ZAHLUNG 4b Field isID Operator Swithout""(like):$(recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid|[[["finvoiceid","s",368]]]|)$
TEST ZAHLUNG 5 Field isINT Operator C(contains):$(recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid|[[["finvoiceid","c","368"]]]|)$
TEST ZAHLUNG 5b Field isINT Operator C without ""(contains):$(recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid|[[["finvoiceid","c",368]]]|)$`

Database:
![Database](https://user-images.githubusercontent.com/6169308/64907568-96b02000-d6f4-11e9-90ca-e6e6db4920cd.png)

PDF-OUTPUT:
![PDF-Output](https://user-images.githubusercontent.com/6169308/64907397-21435000-d6f2-11e9-9297-81f2d1710fa4.png)

### Sorry to ask direct 
But I don't have any idea left, how I could find the right use of recordsList...
Maybe you or someone else experienced could give me 3 answers:
- Is finvoiceid a INTEGER or an ID?
- Should I encapsulate the finvoiceid «379» in ""? Tried both -> no difference.
- ***How would you write the condition, if you have to get all records from paymentsIn with the finvoiceid = 368?***

Instead of: `$(recordsList : PaymentsIn|paymentsname,modifiedtime,finvoiceid|[[["finvoiceid","e","368"]]]|)$`

Thank you for your help
Martin

**Comment by mariuszkrzaczkowski** [comment]
You can simply generate the conditions.  there are two ways 
1. create a view and conditions in it then use the view in pdf using recordsList 
2. in the list view select the conditions and copy from url (search_params=) to pdf


https://gitdeveloper.yetiforce.com/index.php?module=PaymentsIn&page=1&view=List&viewname=264&orderby=&sortorder=ASC&entityState=Active&parent=71&search_params=[[["finvoiceid","a","2015/01/17"],["paymentsin_status","e","PLL_PAID"]]]


https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app/Conditions/QueryFields/ReferenceField.php

**Comment by mad99** [comment]
Hey @mariuszkrzaczkowski,
Thank you for your time and help.

To be honest, I can't see the solution :o((

1. Does your first link show records? For me it is an empty list?
2. I tried with other param for "finvoiceid","a","FV%202016/02/06" (FV 2016/02/06) this invoiceid is for sure a record in demo-page.) Same result -> no results in list. Did I something wrong?


### But what really confuses me
Do I understand your link right? Do you search for "2015/01/17"?
Is this the finvoiceid? Not more like the «payment name»?

***So I tried on my own installation with «payment name» instead of the «finvoiceid from the database» (368).***
Result: There is only ONE (1) match. So with «payment name instead of finvoiceid» it is working with condition "a".

### Problem half solved, but new one added
«payment name» is not an unique id (I guess), and ***so I would walk in some predictable problems, if I would use the «payment name» for condition value in an correcting invoice***, because if I use 2 times the same «payment name» for paymentIn's there would be ***wrong payments listed/subtracted from the customer's invoice***.

### Question:
Is there a way to filter the list with the **"real" finvoiceid (INTEGER/ID: 368)** from the «paymentsin» records, instead of the **«pseudo-ID» "payment name" (2015/01/17)**?

### If not, maybe you could gave me a hint, how in YetiForce is possible to query direct to database
Because I would use the solution from above anyway in a custom TextParser and so I could also use PHP-code to get 

- an array with 
- all «records from dB-Table associated with the «paymentIn»
- with «invoiceid» === 368 (current invoice)
- sort ASC by payment-date

### More tricky then I thought
Sorry, to find a solution seams to be more tricky, then I thought, because YetiForce seams to handle some stuff hidden to translate the real finvoiceid to shown as "more readable" payment name...

It would totally help me figure out how to define the condition/query so that it would work with the "real» uniqueID of the INTEGER/ID (368) from finvoiceid.

If this doesn't work directly through the built-in YetiForce solution of "conditions", you might be able to send me a link where an example of a direct query in a TextParser is used comprehensibly.

Both would help more extremely.
Thank you very mutch
Martin

**Comment by mariuszkrzaczkowski** [comment]
check it https://github.com/YetiForceCompany/YetiForceCRM/commit/3dc4a18fd9a538331b03ef2e7abb552200d0ac9c
