### ISSUE TITLE
[Question]           How to change the width of table cell when export to PDF

### ISSUE THREAD

**Issue by cornutaurus** [YetiForceCompany/YetiForceCRM#11508]
OS: LInux Mint 19.2
Yetiforce Version 5.2

I want to know how to change the width of each cell individually when export to PDF. 

![changewidht](https://user-images.githubusercontent.com/36463465/64916123-7de05280-d766-11e9-90fc-44330c197b8b.png)

For example, item name is 40% and quantity is 10%.

I tried changing the width in Edit Fields - Sales Invoice - Managing an Advanced Block - Edit With for each one. Doing this will only edit the width when creating/editing an invoice. However when export to PDF it doesn't work.

Please give me guidance.

**Comment by mad99** [comment]
Hey cornutaurus,
I'm quite new in YetiForce code. But what I found for my own purpose:
**Each invoice-PDF is result from a TextParser.** 
The default invoice in YF (I guess this is what you print-out above) depends on the TextParser «ProductsTableShortVersion.php»
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app/TextParser/ProductsTableShortVersion.php#L75

On line 75 you find the table part for the invoice with a class-name.
So maybe you could change it with a css-class inclusion. 
*But unfortunately here my knowing lacks:* I don't know, if we could use css in PDF too :o((...

Maybe we got an answer about from the Issue @TonyM15's question about [CSS in PDF](https://github.com/YetiForceCompany/YetiForceCRM/issues/11493) too :o))

Hope the information about TextParser helps you in anyway to find a solution maybe with CSS.
Martin

**Comment by cornutaurus** [comment]
Hello @mad99 

Thank you for pointing it out for me, I guess i'll have to look into that. 

> Hey cornutaurus,
> I'm quite new in YetiForce code. But what I found for my own purpose:
> **Each invoice-PDF is result from a TextParser.**
> The default invoice in YF (I guess this is what you print-out above) depends on the TextParser «ProductsTableShortVersion.php»
> https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app/TextParser/ProductsTableShortVersion.php#L75
> 
> On line 75 you find the table part for the invoice with a class-name.
> So maybe you could change it with a css-class inclusion.
> _But unfortunately here my knowing lacks:_ I don't know, if we could use css in PDF too :o((...
> 
> Maybe we got an answer about from the Issue @TonyM15's question about [CSS in PDF](https://github.com/YetiForceCompany/YetiForceCRM/issues/11493) too :o))
> 
> Hope the information about TextParser helps you in anyway to find a solution maybe with CSS.
> Martin
