### ISSUE TITLE
[BUG] Email Error

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1151]
Fresh Install ver. 2.0.171
![emailerror](https://cloud.githubusercontent.com/assets/1402355/8322177/ae422bc0-1a4a-11e5-954e-436411318741.JPG)

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/cfcbd15f6b2944686a8c5280eddda6ced226c428
