### ISSUE TITLE
[bug] "Incorrect Request" when mapping advanced fields Sales Orders > Vendor Enquiries

### ISSUE THREAD

**Issue by nickallett** [YetiForceCompany/YetiForceCRM#11519]
# 🐞 bug report

### ⁉️ Describe the bug

When mapping an advanced field from Sales Orders to Vendor Enquiries (Item Name, Price, etc.) the system gives an "Incorrect Request" error. 

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
* [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by davide-alghi** [comment]
Hi nickallett,
with **mapping**, are you meaning map for record generating?
are **advanced fields** the **inventory fields**? if yes, where are you mapping advanced fields? I didn't know advanced fields can be mapped :(

please can you provide more information? a video-gif would be useful

**Comment by vovpff** [comment]
@nickallett all fields for destination module should be mapped. I think this is cause of error.

**Comment by bpabiszczak** [comment]
You must map all fields [e.g. quantity, price, tax, net, gross, etc.]. The fields must be of the same type!
