### ISSUE TITLE
[bug]  YetiForce 5.2 - Service Pack Save button not available

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#11513]
After I upgraded to YetiForce 5.2 - Service Pack, the save buttons for each module were grey and could not be used. Please help me.

**Comment by fbojan** [comment]
I had the same problem on WINDOWS XP and the old CROME version. Try it on another computer..

**Comment by Maxpeg** [comment]
In my case it was php-Smarty package error, which need to be installed on the server. 
You need to go to /config/Debug.php and switch all "false" to "true" for $LOG_*****  variables.
Than system will start to make logs in folder /cache/logs/     
Check errors, or errors.log text files.
If can clean these files, then go to your yetiforce website and try to repeat the error.  
Then go back to log files and check for new logs. 
You can post this logs here, there more clues in them.

**Comment by ripixxx** [comment]
i have the same Problem with Yetiforce 5.2. 
You must change this line in the file` /config/Developer.php` then is working the button in Chrome.

`public static $MINIMIZE_JS = true;`
**to**
`public static $MINIMIZE_JS = false;`

greetz Joachim

**Comment by bpabiszczak** [comment]
Please install last Service Pack and check @ripixxx solution.

**Comment by Flxleo** [comment]
Same issue here on 5.3 ServicePack 4

Did follow the idea of ripixxx and it fixed it for me. Though the latest SP didn't - FYI @bpabiszczak 

> i have the same Problem with Yetiforce 5.2.
> You must change this line in the file` /config/Developer.php` then is working the button in Chrome.
> 
> `public static $MINIMIZE_JS = true;`
> **to**
> `public static $MINIMIZE_JS = false;`
> 
> greetz Joachim
