### ISSUE TITLE
[Question]   Remove PROxx or SERxx

### ISSUE THREAD

**Issue by nickallett** [YetiForceCompany/YetiForceCRM#11516]
### Description

Hi,

How do I remove the Product (example PRO04) or Service Number (example SER04) / productid from the "Item Name" in Quotes, Invoices, Vendor Enquiries, etc.?

Many thanks,

**Comment by davide-alghi** [comment]
Hi nickallett,
please can you explain the question more deeply?

**Comment by vovpff** [comment]
@davide-alghi he want to remove `PRO` prefix from product record number.

**Comment by davide-alghi** [comment]
> @davide-alghi he want to remove `PRO` prefix from product record number.

to fill this need it's enough to empty **Use prefix** field at https://gitstable.yetiforce.com/index.php?module=Vtiger&parent=Settings&view=CustomRecordNumbering&block=2&fieldid=22 for Products and Services modules.

but I've the suspect that the problem is another.
