### ISSUE TITLE
[Question] How to debug variable-value in TextParser for PDF? 

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11512]
Hi,
I would like to print_r variable value in PDF from TextParser.

Unfortunately the print_r from array does only output «1» instead of the array-structure and value.
String is working fine.
Tried also with var_dump. Same result no structure in pdf :o(( 

***- Does anybody know what I have to do to get the structure and value from TextParser vars and properties?***

Thanks for any help/hint.
Martin

**Comment by mad99** [comment]
Found a solution for my own.

Maybe it's usable for someone else:
```
/**
	 * print_r_wrapped in outputbuffer for pdf-print_r.
	 *
	 * @return string
	 */
public function print_r_for_pdf($v){
		ob_start();
		print_r($v);
		$print_r_output = ob_get_clean();
		return htmlentities($print_r_output);
	}
```

Used in TextParser process() method:

```
public function process()
	{
		$relatedRecordModel = \Vtiger_Record_Model::getInstanceById($this->textParser->recordModel->get($this->relatedModulesFields[$this->textParser->recordModel->getModuleName()]));
		$temp = $this->textParser->recordModel->getInventoryData();
		$rows = reset($temp);
		$currency = \App\Fields\Currency::getById($rows['currency']);

		return $this->print_r_for_pdf($relatedRecordModel) ;
```

**Comment by mad99** [comment]
**Maybe there are other/better approaches, built in in YetiForce?**

Would be great if anyone share his knowledge!
Thanks

**Comment by apcloic** [comment]
I don't know if there is a better approaches, I'm using the following technique to output variable value to text file. :

$debug = print_r($variable, true);
file_put_contents(dirname(__FILE__).'/debug_output_$variable.txt', $debug);

**Comment by mariuszkrzaczkowski** [comment]
```php

$textParser = \App\TextParser::getInstanceById(565, 'SQuotes');
$textParser->setContent('
$(translate : Users|Email)$  ......    $(relatedRecord : assigned_user_id|email1|Users)$
$(translate : Users|Status)$   ........   $(relatedRecord : assigned_user_id|status|Users)$

$(recordsList : Contacts|firstname,lastname,email,jobtitle,contactstatus)$

$(inventory : type=table columns=name,qty,price href=yes)$
$(inventory : type=table columns=seq,name,qty,unit,price,total,net href=no)$

  ');
$textParser->parse();
echo '<hr>';
echo $textParser->getContent();
```

**Comment by mad99** [comment]
Ah @apcloic and @mariuszkrzaczkowski, 
Thank you both for sharing your solutions.

Now I'm sure, my solution is also used from others and quite OK. ;o)
And I see the more in-depth solution from @mariuszkrzaczkowski
