### ISSUE TITLE
Can't update from 5.0.0 to 5.1.0

### ISSUE THREAD

**Issue by manwenick** [YetiForceCompany/YetiForceCRM#11515]
Hello everyone, 

I saw a new release from 5.1.0 to 5.2.0.

I would like to upgrade from 5.0.0 to 5.1.0 first. But I can't find the right .zip file to download. 
Can somebody tell me which file and from where I shall use.

Thank you!

If I use to file YetiForceCRM-5.1.0-complete.zip than I get an error:
![grafik](https://user-images.githubusercontent.com/34367573/64951079-4617fe80-d87d-11e9-9638-241ec5a7bc53.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.1.0
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0

**Comment by manwenick** [comment]
> 
> 
> https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.1.0
> https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0

Hello @mariuszkrzaczkowski 

thank you for quick response!
I didn't got you, what you mean? I tried all files allready from 5.1.0 and also from 5.2.0 incl. service pack files. I have two errors: 
![grafik](https://user-images.githubusercontent.com/34367573/64951079-4617fe80-d87d-11e9-9638-241ec5a7bc53.png)
or 
![grafik](https://user-images.githubusercontent.com/34367573/64953037-1b7c7480-d882-11e9-8158-35f7be8672bc.png)

What do I wrong?

**Comment by mariuszkrzaczkowski** [comment]
1. 5.0.0_to_5.1.0_v1.zip https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.1.0/5.0.0_to_5.1.0_v1.zip
2. 5.1.0_to_5.2.0_v3.zip https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.2.0/5.1.0_to_5.2.0_v3.zip

**Comment by manwenick** [comment]
@mariuszkrzaczkowski thank you! 
Now it works! :)
