### ISSUE TITLE
Call to a member function checkActive() on boolean [bug] 

### ISSUE THREAD

**Issue by damonconway** [YetiForceCompany/YetiForceCRM#11520]
# 🐞 bug report

### ⁉️ Describe the bug
On a fresh install of YetiForce, I am getting the above error. There is nothing in the logs to indicate what is wrong. This happens on the main page before I am even able to log in. I was able to work through the installation wizard just fine, but have been unable to get beyond this error to a login page.

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
After enabling some logs, I am now getting a blank page. However, I do have some stack traces. However, it's only generating the system.log.

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.2.0
| Web server (name and version)|	nginx version: nginx/1.14.0 (Ubuntu)	|
| PHP  |	PHP 7.2.19-0ubuntu0.18.04.2					|
| Browser (name and version)  | Firefox 69.0 		|
| Operating System (name and version)  | 	Ubuntu 18.04	|
| Database (name and version) | 	MySQL 8.0.16	|

**Comment by damonconway** [comment]
Also, I have tested the DB connection from my host and I'm able to connect. Also, the install process was able to connect and create all of the necessary tables.

**Comment by damonconway** [comment]
Also if it's not clear, I'm getting this error at the root URL (https://yeti.domain.com).

**Comment by bpabiszczak** [comment]
No logs ... We can't help you without them.
