### ISSUE TITLE
[Question]           How to install Yetiforce Portal2

### ISSUE THREAD

**Issue by teka325** [YetiForceCompany/YetiForceCRM#11528]
Hi, I tried to install the portal but still gives errors. I just need to know if it has been completed? You said it will be done when yetiforce 5.2 is released but I still stuck somehow, please assist.

**Comment by paula-w** [comment]
Hi,
the release was delayed a bit, check this issue: https://github.com/YetiForceCompany/YetiForceCRM/issues/11486

**Comment by javjim** [comment]
Do we have a new date for this?

**Comment by acsinsurancegroup** [comment]
Release any time soon?

**Comment by acsinsurancegroup** [comment]
Hello I believe it was finally released. How do you install it though? I have followed all of the instructions. I went to the public_html directory and put in all of the information that I added in the CRM itself, I used the Composer setup in my Plesk Server panel and get the installation screen. However, when I add all the information and click the Install button, NOTHING happens.

![Screenshot from 2019-11-25 18-22-06](https://user-images.githubusercontent.com/42642523/69589118-877d0680-0fb0-11ea-8b9e-c1a8c94fcd03.png)

![Screenshot from 2019-11-25 18-26-54](https://user-images.githubusercontent.com/42642523/69589434-ac25ae00-0fb1-11ea-9991-02b561831c56.png)

**Comment by acsinsurancegroup** [comment]
Over 10 days and still no answer from ANYONE? Wow!

**Comment by iserveradmi** [comment]
from where i can find the API Key ?

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/73735185-28b9d300-473f-11ea-887f-ea8af573bb2e.png)

**Comment by igriberi** [comment]
Hi guys, i write here because when i install Portal2, installation fail with this message: "An error occurred while communicating with the CRM".
Could someone help me?
Thx
