### ISSUE TITLE
[Question]           Logo on login page broken

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#11540]
**YetiForce 5.2.0:**

I replaced the file **logo** in folder **/public_html/layouts/resources/Logo** with a different logo. Same dimensions, same name (without .PNG in filename), same filetype.

After that my login page looks like this:
![image](https://user-images.githubusercontent.com/16014524/65158721-35a98480-da33-11e9-8232-8bd9133b495b.png)

I also replaced the file **logo_yetiforce.png** in folder **/public_html/layouts/resources/Logo** with a different logo. Same dimensions, same name (with .PNG in filename), same filetype.

After that my menu looks like this:
![image](https://user-images.githubusercontent.com/16014524/65158989-ad77af00-da33-11e9-8a00-f88681593cb9.png)

Any ideas what i did wrong? 😊

**Comment by vovpff** [comment]
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Companies&view=List&block=3&fieldid=14

**Comment by Maxpeg** [comment]
Try to return back  **logo_yetiforce.png** in folder /public_html/layouts/resources/Logo
Only replace **logo** file with your logo.

**Comment by LaurensCleyman** [comment]
I tried that but it doesn't work ...

**Comment by Maxpeg** [comment]
What is the element address now? If you use opera browser, right click on the logo, "inspect element" 
Do you have any related errors in log files? /cache/logs

**Comment by LaurensCleyman** [comment]
I replaced all the files in /public_html/layouts/resources/Logo with the original files from the installation directory and nothing changes..

`<img title="Logo" height="256px" class="logo" alt="Logo" src="public_html/layouts/resources/Logo/logo">`

![image](https://user-images.githubusercontent.com/16014524/65308505-7ff14980-db8a-11e9-9c45-b429fcdad77a.png)

No errors in /chache/logs

I set display_errors to on and that gives no errors also.

Tried in in Chrome, Opera after deleting cache.

**Comment by LaurensCleyman** [comment]
Never mind 😃 

Fixed it, was a problem with FileZilla :-)

Kind regards,
