### ISSUE TITLE
[Question] 5.2 update SP2 over PS1

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#11545]
### Description

Is it possible?

**Comment by mariuszkrzaczkowski** [comment]
Yes, we always install the latest one even if we already have it installed.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0

**Comment by vovpff** [comment]
@mariuszkrzaczkowski 
![image](https://user-images.githubusercontent.com/8545791/65227310-15300780-dad1-11e9-9e81-0ec596fc2515.png)

**Comment by mariuszkrzaczkowski** [comment]
Try the new version 5.2.0_ServicePack_v3.zip
delete the /app_data/registration.php file
  https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Companies&view=List&block=3&fieldid=14
click on "Check status"

**Comment by vovpff** [comment]
@mariuszkrzaczkowski after updating to SP3 icon blinking.
After deletion of `/app_data/registration.php` and clicking to "Check status" status of company is accepted but icon blinking.
I checked what config file `/config/Components/Branding.php'
* `$footerName = ` string was automatically filled with company name Instead standard `'YetiForce'` 
* `public static $isCustomerBrandingActive = false;` line is missing
when SP1 to SP2 updated.

**Comment by acsinsurancegroup** [comment]
> Try the new version 5.2.0_ServicePack_v3.zip
> delete the /app_data/registration.php file
> https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Companies&view=List&block=3&fieldid=14
> click on "Check status"

@mariuszkrzaczkowski  Sorry but can you please share where is Service Pack 2 and 3 because I only see 1 which I've already installed. Thank you!

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.2.0/5.2.0_ServicePack_v6.zip
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/Update%20packages/

**Comment by acsinsurancegroup** [comment]
Thanks @mariuszkrzaczkowski and my bad I didn't read earlier it was v6 at this point at the end. I installed it with no issue but my updates section now shows the first one is V1 and now V6 I guess that doesn't matter right?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski What I can do with blinking icon?

**Comment by mariuszkrzaczkowski** [comment]
@vovpff I'll check how I find the moment, I have it in mind

**Comment by mariuszkrzaczkowski** [comment]
@vovpff Fixed in 5.2.0_ServicePack_v8
