### ISSUE TITLE
[Bug] Can not add products ver. 2.0.171

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#1155]
{"success":false,"error":{"code":"Record you are trying to access is not found: 111 Products","message":"Record you are trying to access is not found: 111 Products"}}

**Comment by mariuszkrzaczkowski** [comment]
Tests on version 2.0.183 and working properly. 
Check at this address https://test.yetiforce.com/test/index.php?module=Products&view=List&parent=84
Check the logs.
