### ISSUE TITLE
Nie mogę zainstalować roundcube. Strona się "zawiesza" 

### ISSUE THREAD

**Issue by McTommy007** [YetiForceCompany/YetiForceCRM#11552]
Cześć,
Mam pytanie.
Serwer Hostovita.pl, zainstalowałem Yeti przez Softaculous.
Zainstalował się ale okazało się, że brakuje poczty.
Chciałem doinstalować roundcube.
Software configuration
Standard modules
Modules – Installation
Wybieram update library i po minucie "mielenia" wyskakuje informacja, że "ta strona nie działa", Serwer nie może obsłużyć zadania, http error 500.
Z czym to może być związane? Ktoś się spotkał z tym problemem?
Może nie muszę mieć roundcube-a. Chciałbym móc wysyłać z Yeti e-maile. Konfiguracja SMTP nie działa. To znaczy po podaniu wszystkich danych system kręcił kółkiem przez godzinę ale po tym czasie go zamknąłem bo nie chciało mi się czekać. Zauważyłem, że można otworzyć roundcube bezpośrednio w Yeti. A może nie trzeba? Jestem trochę zielony w tym systemie. Ale e-maile raczej powinien CRM wysyłać :-)
Ktoś może mi coś doradzić?

**Comment by bpabiszczak** [comment]
Strzelam, że masz słabiutki hosting z setkami różnych limitów i pewnie serwer ubija CRM za nim pobierze on paczkę roundcube i ją zainstaluje. Możesz to zrobić ręcznie, albo jeszcze lepiej zainstaluj lokalnie na lapku i skopiuj zainstalowany system na hosting. 

Niestety bez logów nie mamy jak Tobie pomóc, możemy zainstalować system u nas na hostingu i możesz sobie go testować bezpłatnie przez 1-2 miesiące.
