### ISSUE TITLE
Can not install roundcube

### ISSUE THREAD

**Issue by elvissaba** [YetiForceCompany/YetiForceCRM#11565]
I can't install roundcube lib. Download button does nothing. YF version 5.20

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by elvissaba** [comment]
2019-09-21 19:33:11.3895 [warning][Settings_ModuleManager_Library_Model::download] - GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 10000 milliseconds with 6170270 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/testcrm/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185

**Comment by elvissaba** [comment]
Here is full log:

2019-09-21 20:22:42.9133 [warning][Settings_ModuleManager_Library_Model::download] - GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 10000 milliseconds with 4457953 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/testcrm/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(107): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(72): GuzzleHttp\RedirectMiddleware->checkRedirect(Object(GuzzleHttp\Psr7\Request), Array, Object(GuzzleHttp\Psr7\Response))
#10 /var/www/testcrm/vendor/guzzlehttp/promises/src/FulfilledPromise.php(39): GuzzleHttp\RedirectMiddleware->GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#11 /var/www/testcrm/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
#12 /var/www/testcrm/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#13 /var/www/testcrm/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#14 /var/www/testcrm/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#15 /var/www/testcrm/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#16 /var/www/testcrm/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#17 /var/www/testcrm/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#18 /var/www/testcrm/modules/Settings/ModuleManager/models/Library.php(115): GuzzleHttp\Client->request('GET', 'https://github....', Array)
#19 /var/www/testcrm/modules/Settings/ModuleManager/actions/Library.php(39): Settings_ModuleManager_Library_Model::download('roundcube')
#20 /var/www/testcrm/app/Controller/ExposeMethod.php(65): Settings_ModuleManager_Library_Action->download(Object(App\Request))
#21 /var/www/testcrm/app/Controller/ExposeMethod.php(78): Settings_ModuleManager_Library_Action->invokeExposedMethod('download', Object(App\Request))
#22 /var/www/testcrm/include/main/WebUI.php(182): Settings_ModuleManager_Library_Action->process(Object(App\Request))
#23 /var/www/testcrm/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#24 /var/www/testcrm/public_html/index.php(11): require('/var/www/testcr...')
#25 {main}
2019-09-21 20:22:32.6619 [info][application] - 
$_GET = [
    'module' => 'ModuleManager'
    'parent' => 'Settings'
    'action' => 'Library'
    'mode' => 'download'
    'name' => 'roundcube'
]
$_POST = [
    '__vtrftk' => 'sid:b4e21249b264d27dcaafe58789a877c0f10a01a9,1569089122'
]
$_FILES = []
$_COOKIE = [
    '_gcl_au' => '1.1.1246023128.1561982039'
    '_ga' => 'GA1.2.136433647.1561982040'
    '_fbp' => 'fb.1.1561982040197.908514501'
    'YTSID' => 'ds19qv23g17bb2lr03n2t3ruo7'
]
$_SESSION = [
    'last_activity' => 1569090152.6627
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => '8af21d93ffe7ac15745c0721909d12656a27b1c8'
    'user_name' => 'imtecadmin'
    'full_user_name' => 'Administrator Yeti'
    'fingerprint' => 'd520c7a8-421b-4563-b955-f5abc56b97ec'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
    ]
    'lvs' => [
        'HelpDesk' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 13
        ]
        'ServiceContracts' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 39
        ]
        'Faq' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 28
        ]
    ]
    'SystemWarnings' => true
]
$functionalVerification = [
    'branding' => 'No'
]
====================================================================================================================================

**Comment by mariuszkrzaczkowski** [comment]
there was not enough time to download the file.  downloaded 6mb from 7.7mb.  you can increase connection time or download files and upload to crm

**Comment by elvissaba** [comment]
Where can I set this parameter?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/eb36f626d93a1b65b1331c51a608f4e6c50cf8e2/app/RequestHttp.php#L27

**Comment by elvissaba** [comment]
Thank you Mariusz. Problem solved.

**Comment by elvissaba** [comment]
Thank you Mariusz. Problem solved.
