### ISSUE TITLE
Reg-YetiForceCRM Installation.

### ISSUE THREAD

**Issue by ENGINEERRAJASEKAR** [YetiForceCompany/YetiForceCRM#11562]
Hello,
I am new to Yetiforce.

1) I'll try to install in my hosting(godaddy).its not working.

2)I'll try to SOFTACULOUS.

But SOFTACULOUS not available godaddy.

I'll ask godaddy customer care .But its not useful.

any one help me please.

**Comment by mariuszkrzaczkowski** [comment]
You didn't give us any details so how can we help you?
describe the problem in detail, attach all required information see here
https://raw.githubusercontent.com/YetiForceCompany/YetiForceCRM/developer/.github/ISSUE_TEMPLATE/1-bug-report.md

**Comment by Pietrox** [comment]
From my experience goddaddy hosting will be problematic. Best to have sudo/root access on special hosting or vps/cloud vps.
