### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#11569]
Hi,
I can not modify or save records since I upgraded to 5.2. How do I fix this issue? Thanks

**Comment by mariuszkrzaczkowski** [comment]
Show logs

**Comment by hobejeans** [comment]
YetiForceUpdate::addFields| 2019-09-21 09:39:42 | 0 mim.
YetiForceUpdate::updateInvoice| 2019-09-21 09:39:42 | 0.01 mim.
YetiForceUpdate::updateProducts| 2019-09-21 09:39:42
YetiForceUpdate::setTree| 2019-09-21 09:39:42
YetiForceUpdate::setTree| 2019-09-21 09:39:42 | 0 mim.
YetiForceUpdate::updateProductAndServiceFiels| 2019-09-21 09:39:42
YetiForceUpdate::removeField | unit_price,Products,unit_price | 2019-09-21 09:39:42
YetiForceUpdate::removeField| 2019-09-21 09:39:42 | 0 mim.
YetiForceUpdate::removeField | commissionrate,Products,commissionrate | 2019-09-21 09:39:44
YetiForceUpdate::removeField| 2019-09-21 09:39:44 | 0 mim.
YetiForceUpdate::updateProductAndServiceFiels| 2019-09-21 09:39:44 | 0.04 mim.
YetiForceUpdate::addFields| 2019-09-21 09:39:44
[INFO] Skip adding field. Module: 14-Products; field name: category_multipicklist, field exists: 1
[INFO] Skip adding field. Module: 14-Products; field name: unit_price, field exists: 1
[INFO] Skip adding field. Module: 14-Products; field name: commissionrate, field exists: 1
YetiForceUpdate::addFields| 2019-09-21 09:39:44 | 0 mim.
YetiForceUpdate::updateProducts| 2019-09-21 09:39:44 | 0.04 mim.
YetiForceUpdate::updateServices| 2019-09-21 09:39:44
YetiForceUpdate::updateProductAndServiceFiels| 2019-09-21 09:39:44
YetiForceUpdate::removeField | unit_price,Services,unit_price | 2019-09-21 09:39:45
YetiForceUpdate::removeField| 2019-09-21 09:39:45 | 0 mim.
YetiForceUpdate::removeField | commissionrate,Services,commissionrate | 2019-09-21 09:39:45
YetiForceUpdate::removeField| 2019-09-21 09:39:45 | 0 mim.
YetiForceUpdate::updateProductAndServiceFiels| 2019-09-21 09:39:45 | 0.01 mim.
YetiForceUpdate::addFields| 2019-09-21 09:39:45
[INFO] Skip adding field. Module: 35-Services; field name: unit_price, field exists: 1
[INFO] Skip adding field. Module: 35-Services; field name: commissionrate, field exists: 1
YetiForceUpdate::addFields| 2019-09-21 09:39:45 | 0 mim.
YetiForceUpdate::updateServices| 2019-09-21 09:39:45 | 0.01 mim.
YetiForceUpdate::updateNextData| 2019-09-21 09:39:45
YetiForceUpdate::addPicklistValues| 2019-09-21 09:39:45
YetiForceUpdate::addPicklistValues| 2019-09-21 09:39:46 | 0.01 mim.
YetiForceUpdate::statusActivate| 2019-09-21 09:39:46
YetiForceUpdate::statusActivate| 2019-09-21 09:39:46 | 0.01 mim.
YetiForceUpdate::updateNextData| 2019-09-21 09:39:46 | 0.02 mim.
YetiForceUpdate::update| 2019-09-21 09:39:46 | 0.66 mim.
YetiForceUpdate::postupdate| 2019-09-21 09:40:08
YetiForceUpdate::postupdate| 2019-09-21 09:40:08 | 0 mim.

**Comment by rskrzypczak** [comment]
- install new [servicePack](https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0)
- clear browser cache (chrom Ctrl+Shift+R)

**Comment by hobejeans** [comment]
Hi,
I am still having the same problem after installing the service pack


Kind Regards,

*The Team*
*Hobe Design House, Inc.*
*1971 W McNab Road, Suite 3*
*Pompano Beach, FL 33069*

www.hobedesignhouse.com
hobedesignhouse@gmail.com
*(954) 247-1764*


*Hobe Design House, Inc.*


<https://www.facebook.com/hobedesignhouse/?ref=aymt_homepage_panel>
<https://plus.google.com/u/0/b/106912392464219417995/106912392464219417995/about>
    <https://www.youtube.com/channel/UCHrWDR_0lnrmpZW1-0zkReQ>
