### ISSUE TITLE
[pl][pytanie] Po aktualizacji do 5.2 oraz instalacji service pack problem z wysyłką maili 

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11578]
Po aktualizacji do 5.2 , po instalacji SP, po aktualizacji tłumaczeń oraz bibliotek roundcube:
Pojawia mi się w roundcube'ie podczas tworzenia nowej wiadomości komunikat o internal problem a w konsoli mam takie błędy:
![image](https://user-images.githubusercontent.com/21024857/65412780-3bff7e00-ddf0-11e9-976a-b333178906cd.png)

W update.log mam następujące informacje:
`Warning:  copy(/my_path/YetiForce/modules/OSSMailScanner/scanneractions/CreatedEmail.php): failed to open stream: Permission denied in /my_path/YetiForce/vtlib/Vtiger/Functions.php on line 530

Warning:  copy(/my_path/YetiForce/modules/OSSMailScanner/scanneractions/BindHelpDesk.php): failed to open stream: Permission denied in /my_path/YetiForce/vtlib/Vtiger/Functions.php on line 530

Warning:  copy(/my_path/YetiForce/modules/OSSMailScanner/scanneractions/BindHelpDesk.php): failed to open stream: Permission denied in /my_path/YetiForce/vtlib/Vtiger/Functions.php on line 473`

Na teście dałem maksymalne uprawnienia i usera www-data ale dalej jest problem z dostępem.

Zawartość updateLogsTreace.log:
jest masa błędów związanych z
Next yii\db\Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'name'
The SQL being executed was: DELETE FROM `a_yf_mapped_fields` WHERE (`source`=1833) OR (`target`=1833) in /my_path/YetiForce/vendor/yetiforce/yii2/db/Schema.php:664
Stack trace:

**Comment by mrzewnicki** [comment]
OK, miałem dodatek do filtrów zaimplementowany brakło $config['plugins'] = array('filters'); itp

**Comment by mariuszkrzaczkowski** [comment]
Dodatek "filters" jest na licencji GPLv3+ mam nadzieje że wiesz jakie to niesie za sobą obowiązki i zagrożenia

**Comment by bpabiszczak** [comment]
Ogólnie to nie problem, jeżeli ktoś u siebie to zainstaluje... Co innego kiedy my jako producent rozprowadzamy to razem z głównym oprogramowaniem.
