### ISSUE TITLE
[bug] Passwords Module

### ISSUE THREAD

**Issue by elvissaba** [YetiForceCompany/YetiForceCRM#11570]
I can't save record in passwords module, even when password criteria is met.
With Quick create, i can save password >8 characters, but in password settings minimum password length is 4.
Bug can be replicated on gitstable and gitdev.
Regards.

**Comment by elvissaba** [comment]
Any feedback about this issue?

**Comment by bpabiszczak** [comment]
I tested on the gitdeveloper version and it works fine. In the future, a separate configuration will be created for the password module.
