### ISSUE TITLE
[improvement] Projects and tasks header eat too much space - needs aligning

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#1157]
![image](https://cloud.githubusercontent.com/assets/6852348/8326344/d528dfe6-1a8a-11e5-8266-6903405c4d48.png)

**Comment by KatarzynaUlichnowska** [comment]
Hello,
this view has been slightly improved in the developer version https://github.com/YetiForceCompany/YetiForceCRM/issues/1157, and soon we will publish a new design and the community will have an opportunity to suggest changes and improvements.
