### ISSUE TITLE
[pl][pytanie] Problem ze zmianą statusu po aktualizacji        

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11580]
Po zaktualizowaniu do wersji 5.2 + service pack + update słowników mam problem ze zmianą na niektóre statusy.

Czasem również wybieram wartość, odklikuje na tło po czym status się nie zmienia tylko wraca do poprzedniego.

Np nie mogę zamykać rekordów a w konsoli mam taki błąd:
![image](https://user-images.githubusercontent.com/21024857/65426819-4da54d80-de11-11e9-9f52-28bdd7d893f1.png)

W logach natomiast mam taką notatkę:
`
2019-09-23 14:42:21.9305 [error] - Argument 3 passed to App\Utils\ServiceContracts::getDiffFromServiceContracts() must be of the type integer, null given, called in /var/www/html/YetiForce/app/Utils/ServiceContracts.php on line 346
TypeError: Argument 3 passed to App\Utils\ServiceContracts::getDiffFromServiceContracts() must be of the type integer, null given, called in /my_path/YetiForce/app/Utils/ServiceContracts.php on line 346 and defined in /my_path/YetiForce/app/Utils/ServiceContracts.php:364
Stack trace:
#0 /my_path/YetiForce/app/Utils/ServiceContracts.php(346): App\Utils\ServiceContracts::getDiffFromServiceContracts('2019-09-23 14:3...', '2019-09-23 14:4...', NULL, Object(HelpDesk_Record_Model))
#1 /my_path/YetiForce/app/RecordStatus.php(300): App\Utils\ServiceContracts::getDiff('2019-09-23 14:3...', Object(HelpDesk_Record_Model))
#2 /my_path/YetiForce/modules/Vtiger/handlers/RecordStatusHistory.php(27): App\RecordStatus::update(Object(HelpDesk_Record_Model), 'ticketstatus')
#3 /my_path/YetiForce/app/EventHandler.php(314): Vtiger_RecordStatusHistory_Handler->entityBeforeSave(Object(App\EventHandler))
#4 /my_path/YetiForce/modules/Vtiger/models/Record.php(458): App\EventHandler->trigger('EntityBeforeSav...')
#5 /my_path/YetiForce/modules/Vtiger/actions/RecordUnlock.php(42): Vtiger_Record_Model->save()
#6 /my_path/YetiForce/include/main/WebUI.php(182): Vtiger_RecordUnlock_Action->process(Object(App\Request))
#7 /my_path/YetiForce/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#8 {main}
2019-09-23 14:42:21.8845 [info][application] - 
$_GET = []
$_POST = [
    '__vtrftk' => 'sid:39983ac114db5888a0a8ffd2b58616efe8eab2d0,1569242539'
    'module' => 'HelpDesk'
    'action' => 'RecordUnlock'
    'record' => '130748'
    'ticketstatus' => 'Open'
]
$_FILES = []
$_COOKIE = [
    'chat-notSendByEnter' => 'false'
    '_ga' => 'GA1.2.1201055770.1549886751'
    'prefsviewsplitter' => '195'
    'folderviewsplitter' => '300'
    'identviewsplitter' => '300'
    'addressviewsplitter' => '250'
    'addressviewsplitterd' => '200'
    'language' => 'pl'
    'mailviewsplitterv' => '165'
    'mailviewsplitter' => '205'
    'composesplitterv1' => '200'
    'composesplitterv2' => '846.4'
    'YTSID' => '1hgn0g9i9c1bukq818fafc13mf'
]
$_SESSION = [
    'last_activity' => 1569242541.8855
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 9
    'app_unique_key' => 'e12bd70f3c83893a78397a56425749679caae85d'
    'user_name' => 'ibrynda'
    'full_user_name' => 'Brynda Iwona'
    'fingerprint' => 'd520c7a8-421b-4563-b955-f5abc56b97ec'
    'language' => 'pl-PL'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
    ]
]
$security = [
    'public_html' => 'Off'
    'display_errors' => 'On'
    'disable_functions' => 'shell_exec, exec, system, passthru'
    'Header: server' => 'Apache/2.4.29 (Ubuntu)'
]
$database = [
    'innodb_lock_wait_timeout' => '50'
]
$performance = [
    'opcache.revalidate_freq' => '30'
    'mysqlnd.collect_statistics' => 'Off'
]`

**Comment by mrzewnicki** [comment]
Przy próbie zmiany statusu używając masowej edycji mam następujące komunikaty:
![image](https://user-images.githubusercontent.com/21024857/65485366-fdc29700-dea1-11e9-9d3c-2722b8c0f242.png)

**Comment by mariuszkrzaczkowski** [comment]
jaką masz wersję service pack ?

**Comment by mrzewnicki** [comment]
Dziękuje za odpowiedź.
v3
![image](https://user-images.githubusercontent.com/21024857/65485503-5bef7a00-dea2-11e9-9dbd-954faf54c907.png)

**Comment by mariuszkrzaczkowski** [comment]
zainstaluj najnowszą wersję

**Comment by mrzewnicki** [comment]
Wydawało mi się że instaluje najnowszą ale ok. Zaraz poszukam. Dzięki za uwagę.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.2.0/5.2.0_ServicePack_v9.zip

**Comment by mrzewnicki** [comment]
OK, zainstalowałem. Zrestartowałem Apache, przelogowałem się i niestety dalej problem występuje.

![image](https://user-images.githubusercontent.com/21024857/65486060-c3f29000-dea3-11e9-962e-6f12a612e9f6.png)

Pytanie czy powinienem poczekać jakiś czas czy "od razu" powinno pomóc?

W logach mam również taki błąd. Sprawdałem uprawnienia do pliku i wszystko jest popranwie.
`
2019-09-24 08:18:02.6601 [error] - Invalid request - Response For Illegal Access
App\Exceptions\AppException: Invalid request - Response For Illegal Access in /var/www/html/YetiForce/config/csrf_config.php:21
Stack trace:
#0 [internal function]: CSRFConfig::{closure}('')
#1 /var/www/html/YetiForce/vendor/yetiforce/csrf-magic/src/Csrf.php(233): call_user_func(Object(Closure), '')
#2 /var/www/html/YetiForce/vendor/yetiforce/csrf-magic/src/Csrf.php(497): CsrfMagic\Csrf::check()
#3 /var/www/html/YetiForce/include/main/WebUI.php(151): CsrfMagic\Csrf::init()
#4 /var/www/html/YetiForce/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#5 {main}
2019-09-24 08:18:02.6535 [info][application] - 
$_GET = []
$_POST = [
    '__vtrftk' => 'sid:fc9df751cb8a8b294d73209e986dcaaa1908f82b,1569245781'
    'module' => 'Notification'
    'view' => 'Reminders'
]
$_FILES = []
$_COOKIE = [
    'chat-notSendByEnter' => 'false'
    '_ga' => 'GA1.2.1201055770.1549886751'
    'prefsviewsplitter' => '195'
    'folderviewsplitter' => '300'
    'identviewsplitter' => '300'
    'addressviewsplitter' => '250'
    'addressviewsplitterd' => '200'
    'language' => 'pl'
    'mailviewsplitterv' => '165'
    'mailviewsplitter' => '205'
    'composesplitterv1' => '200'
    'composesplitterv2' => '846.4'
    'YTSID' => '639qc0uk847osn8bkfsb3aptjm'
]
$_SESSION = [
    'CSP_TOKEN' => 'f4e1361bdb3b9159c3e52e10fce574496d3959e51edf2203b86c9068326fd57b'
    'last_activity' => 1569305879.116
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => 'e12bd70f3c83893a78397a56425749679caae85d'
    'user_name' => 'mrzewnicki'
    'full_user_name' => 'CRM System'
    'fingerprint' => 'd520c7a8-421b-4563-b955-f5abc56b97ec'
    'language' => 'pl-PL'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
    ]
    'lvs' => [
        'HelpDesk' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 161
            'entityState' => 'Active'
        ]
    ]
]
$security = [
    'public_html' => 'Off'
    'display_errors' => 'On'
    'disable_functions' => 'shell_exec, exec, system, passthru'
]
$headers = [
    'Header: server' => 'Apache/2.4.29 (Ubuntu)'
    'Header: x-powered-by' => false
    'Header: x-frame-options' => 'SAMEORIGIN'
    'Header: x-xss-protection' => '1; mode=block'
    'Header: x-content-type-options' => 'nosniff'
    'Header: x-robots-tag' => 'none'
    'Header: x-permitted-cross-domain-policies' => 'none'
    'Header: expect-ct' => 'enforce; max-age=3600'
    'Header: referrer-policy' => 'no-referrer'
    'Header: strict-transport-security' => 'max-age=31536000; includeSubDomains; preload'
]
$database = [
    'innodb_lock_wait_timeout' => '50'
]
$performance = [
    'opcache.revalidate_freq' => '30'
    'mysqlnd.collect_statistics' => 'Off'
]
$environment = [
    'error_log' => false
]

`

**Comment by mrzewnicki** [comment]
Z poziomu bazy danych mogę zamknąć testowy rekord ale z poziomu GUI otrzymuje komunikat 
![image](https://user-images.githubusercontent.com/21024857/65664685-254c6780-e03a-11e9-8002-34acb083d0f6.png)

**Comment by bpabiszczak** [comment]
Z tego co widzę, korzystasz z systemu pod innym adresem WWW niż jest wprowadzony w pliku konfiguracyjnym w site_url... przez co wywala Tobie zabezpieczenie CSRF.

**Comment by mrzewnicki** [comment]
![image](https://user-images.githubusercontent.com/21024857/65665484-eb7c6080-e03b-11e9-9c0c-960b5ee7d28d.png)
![image](https://user-images.githubusercontent.com/21024857/65665508-f636f580-e03b-11e9-955f-2ea2d4b55ee7.png)

W Main.php jest ten sam url co używam w przeglądarce.  Próbowałem też po IP ale efekt jest ten sam.

**Comment by mrzewnicki** [comment]
Spróbowałem zmienić na testowym zgłoszeniu to mam taki log:

`2019-09-26 09:12:12.3974 [error] - Argument 3 passed to App\Utils\ServiceContracts::getDiffFromServiceContracts() must be of the type integer, null given, called in /var/www/html/YetiForce/app/Utils/ServiceContracts.php on line 346
TypeError: Argument 3 passed to App\Utils\ServiceContracts::getDiffFromServiceContracts() must be of the type integer, null given, called in /var/www/html/YetiForce/app/Utils/ServiceContracts.php on line 346 and defined in /var/www/html/YetiForce/app/Utils/ServiceContracts.php:364
Stack trace:
#0 /var/www/html/YetiForce/app/Utils/ServiceContracts.php(346): App\Utils\ServiceContracts::getDiffFromServiceContracts('2019-09-26 09:1...', '2019-09-26 09:1...', NULL, Object(HelpDesk_Record_Model))
#1 /var/www/html/YetiForce/app/RecordStatus.php(300): App\Utils\ServiceContracts::getDiff('2019-09-26 09:1...', Object(HelpDesk_Record_Model))
#2 /var/www/html/YetiForce/modules/Vtiger/handlers/RecordStatusHistory.php(27): App\RecordStatus::update(Object(HelpDesk_Record_Model), 'ticketstatus')
#3 /var/www/html/YetiForce/app/EventHandler.php(314): Vtiger_RecordStatusHistory_Handler->entityBeforeSave(Object(App\EventHandler))
#4 /var/www/html/YetiForce/modules/Vtiger/models/Record.php(458): App\EventHandler->trigger('EntityBeforeSav...')
#5 /var/www/html/YetiForce/modules/Vtiger/actions/Save.php(88): Vtiger_Record_Model->save()
#6 /var/www/html/YetiForce/modules/Vtiger/actions/SaveAjax.php(21): Vtiger_Save_Action->saveRecord(Object(App\Request))
#7 /var/www/html/YetiForce/include/main/WebUI.php(185): Vtiger_SaveAjax_Action->process(Object(App\Request))
#8 /var/www/html/YetiForce/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#9 {main}
2019-09-26 09:12:12.3617 [info][application] - 
$_GET = []
$_POST = [
    '_csrf' => 'sid:a3b1c6e0bcfd817d25116fe8bf6f900e7c9521c7,1569481924'
    'value' => 'PLL_TO_CLOSE'
    'field' => 'ticketstatus'
    'record' => '133301'
    'module' => 'HelpDesk'
    'action' => 'SaveAjax'
]
$_FILES = []
$_COOKIE = [
    'chat-notSendByEnter' => 'false'
    '_ga' => 'GA1.2.1201055770.1549886751'
    'prefsviewsplitter' => '195'
    'folderviewsplitter' => '300'
    'identviewsplitter' => '300'
    'addressviewsplitter' => '250'
    'addressviewsplitterd' => '200'
    'language' => 'pl'
    'mailviewsplitterv' => '165'
    'mailviewsplitter' => '205'
    'composesplitterv1' => '200'
    'composesplitterv2' => '846.4'
    'YTSID' => 'k00mlaj7jitauns5casriegg7v'
    'roundcube_sessid' => 't8hbfp3ddropqd637mjahg8t0r'
    'roundcube_sessauth' => 'R0kcvnORyT5Hs7FUf2ViV3SbAI-1569468960'
]
$_SESSION = [
    'CSP_TOKEN' => '27b7809bd2167e6d3b6fbc426c8419bfe8ac12f8c21abd8f51e0679e41dfe8a0'
    'last_activity' => 1569481932.3626
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => 'e12bd70f3c83893a78397a56425749679caae85d'
    'user_name' => 'mrzewnicki'
    'full_user_name' => 'CRM System'
    'fingerprint' => 'd520c7a8-421b-4563-b955-f5abc56b97ec'
    'language' => 'pl-PL'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
    ]
    'lvs' => [
        'HelpDesk' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 161
            'entityState' => 'Active'
        ]
        'ServiceContracts' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 39
        ]
        'FBookkeeping' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 88
        ]
        'FInvoiceProforma' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 93
        ]
        'FCorectingInvoice' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 101
        ]
        'PaymentsOut' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 74
        ]
        'PaymentsIn' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 73
        ]
        'FInvoiceCost' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 108
        ]
        'IGRN' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 92
        ]
        'IGRNC' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 102
        ]
        'IGDNC' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 103
        ]
        'IGDN' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 94
        ]
        'IIDN' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 95
        ]
        'IStorages' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 91
        ]
        'DataSetRegister' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 112
        ]
        'LocationRegister' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 114
        ]
        'IncidentRegister' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 115
        ]
        'AuditRegister' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 116
        ]
        'MultiCompany' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 111
        ]
        'OSSEmployees' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 56
        ]
        'HolidaysEntitlement' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 72
        ]
        'CFixedAssets' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 106
        ]
        'CInternalTickets' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 107
            'entityState' => 'Active'
        ]
        'CMileageLogbook' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 109
        ]
        'LettersIn' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 75
        ]
        'LettersOut' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 76
        ]
        'Products' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 24
        ]
        'OutsourcedProducts' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 54
        ]
        'Assets' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 41
        ]
        'Services' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 40
        ]
        'OSSOutsourcedServices' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 52
        ]
        'OSSSoldServices' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 53
        ]
        'OSSMailView' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 50
        ]
        'SMSNotifier' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 46
        ]
        'EmailTemplates' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 105
        ]
        'Documents' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 22
        ]
        'OSSPasswords' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 55
        ]
        'CallHistory' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 68
        ]
        'Announcements' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 77
        ]
        'SMSPromo' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 120
        ]
        'RecycleBin' => [
            'viewname' => ''
        ]
        'Notification' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 104
        ]
    ]
]
$security = [
    'public_html' => 'Off'
    'display_errors' => 'On'
    'disable_functions' => 'shell_exec, exec, system, passthru'
]
$headers = [
    'Header: server' => 'Apache/2.4.29 (Ubuntu)'
    'Header: x-powered-by' => false
    'Header: x-frame-options' => 'SAMEORIGIN'
    'Header: x-xss-protection' => '1; mode=block'
    'Header: x-content-type-options' => 'nosniff'
    'Header: x-robots-tag' => 'none'
    'Header: x-permitted-cross-domain-policies' => 'none'
    'Header: expect-ct' => 'enforce; max-age=3600'
    'Header: referrer-policy' => 'no-referrer'
    'Header: strict-transport-security' => 'max-age=31536000; includeSubDomains; preload'
]
$database = [
    'innodb_lock_wait_timeout' => '50'
]
$performance = [
    'opcache.revalidate_freq' => '30'
    'mysqlnd.collect_statistics' => 'Off'
]
$environment = [
    'error_log' => false
]`

**Comment by mariuszkrzaczkowski** [comment]
Jaka jest zainstalowana wersja service pack-a  ?

**Comment by mrzewnicki** [comment]
v9, próbowałem 12 ale pojawia się błąd:
![image](https://user-images.githubusercontent.com/21024857/65667308-c25dcf00-e03f-11e9-81a2-e3a53f4f8ac9.png)


![image](https://user-images.githubusercontent.com/21024857/65667273-afe39580-e03f-11e9-977d-1ebc59d94d25.png)

**Comment by mariuszkrzaczkowski** [comment]
trzeba zmienić wersję na 5.2.0

**Comment by mrzewnicki** [comment]
W config/verion.php => appVersion ?

**Comment by mariuszkrzaczkowski** [comment]
tak

**Comment by mrzewnicki** [comment]
ok, SP przeszedł jak powinien, ale problem ze zmianą statusu dalej jest identyczny.

**Comment by mrzewnicki** [comment]
Stwierdzam po czasie że mój opis jest co najmniej bardzo lakoniczny więc może gif komuś podsunie pomysł
![ticket_status_change](https://user-images.githubusercontent.com/21024857/65691667-8a6f7f80-e071-11e9-871d-f23e74eaf1de.gif)
