### ISSUE TITLE
[Question] PDF - QUALITY - JAKOŚĆ          

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#11581]
Witam, czy jest szansa jakoś zmniejszyć ( skompresować) jakość generowanego PDF-a ? PLiki wychodzą mi ok 2 mb - średnio.

**Comment by bpabiszczak** [comment]
Zmienić czcionkę, domyślna ma dużo znaków aby obsłużyć domyślnie wiele języków.

**Comment by waran70** [comment]
PDF and no Reports are the weakest point of this amazing app. I don't mean give all for free, but let us buys great extensions... why not?
