### ISSUE TITLE
[Bug] Can not add lead -  ver. 2.0.171

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#1158]
{"success":false,"error":{"code":"Record you are trying to access is not found: 115 Leads","message":"Record you are trying to access is not found: 115 Leads"}}

**Comment by mariuszkrzaczkowski** [comment]
Tests on version 2.0.183 and working properly. 
Check at this address https://test.yetiforce.com/test/index.php?module=Leads&view=List
Check the logs.
