### ISSUE TITLE
[bug] Access to undeclared static property: Config\Developer::$updaterDevMode

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#11582]
# 🐞 bug report

### ⁉️ Describe the bug
![image](https://user-images.githubusercontent.com/16014524/65431784-4f274380-de1a-11e9-9121-5c307d3ee280.png)

Access to undeclared static property: Config\Developer::$updaterDevMode

### 🔥 How to trigger the error
1- Install latest service pack (V7)
2 - Go to Software Configuration 
/index.php?module=Vtiger&parent=Settings&view=Index

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.2.15
| Web server (name and version)|	Apache	|
| PHP  | 7.2.22								|
| Browser (name and version)  | 	Chrome 75	|
| Operating System (name and version)  |  Windows 10 | 
| Database (name and version) | MySQL 5.6.40-84.0-log		|
| Service Pack version | 	7	|

**Comment by mariuszkrzaczkowski** [comment]
check  5.2.0_ServicePack_v9.zip

**Comment by LaurensCleyman** [comment]
Fixed now, thanks! 😃
