### ISSUE TITLE
[bug] 5.2.0_ServicePack_v10

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#11592]
2019-09-20 09:04:03	bojanf	YetiForce CRM 5.2 Service Pack v3	5.2.0	  5.2.0	 Yes
2019-09-22 10:42:12	bojanf	YetiForce CRM 5.2 Service Pack v6	5.2.0	  5.2.0	 Yes

I tried updating YETIFORCE 5.2.0_ServicePack_v10

Failed
Wrong version of module, module version 5.2.0 but it should be greater than 5.2.15

**Comment by mariuszkrzaczkowski** [comment]
Change version number to 5.2.0 there was a bug in SP
https://github.com/YetiForceCompany/UpdatePackages/commit/89a5736d44249c2167e34d8baa5c48aaba197591
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0
