### ISSUE TITLE
[Question]           When to choose which table for custom fields? Rule of thumb?

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#11606]
Hi all, 

If you create custom fields in the contact module you get the option to choose the table:

![image](https://user-images.githubusercontent.com/16014524/65608064-eb358400-dfad-11e9-9c38-949f409728de.png)

Is there a rule of thumb that says when which table should be chosen?

Kind regards,

**Comment by bpabiszczak** [comment]
Choose a basic table.
