### ISSUE TITLE
How to Reset user password on every month of 1st date.

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#11601]
I want to reset user password on  every month of 1st date.How can we achieve  this task .

I tried like this:  Workflows 

1.Execution schedule (defined time intervals)
Execution frequency: Monthly by date
On these days: 1
2.Add TO DO
Which task should i give here? Please help me

**Comment by Maxpeg** [comment]
You can make it reset every 30 days in Settings/Security/Password configuration
"Force password change"

**Comment by guide5232** [comment]
> You can make it reset every 30 days in Settings/Security/Password configuration
> "Force password change"

Thank you for replay 
1.is it automation or manually we have to reset every 30 days ?
2.i did not find "Force password change"in that path

**Comment by Maxpeg** [comment]
![image](https://user-images.githubusercontent.com/54612661/65587878-28ebda00-dfb9-11e9-9c30-46830c7a607f.png)

After 30 days, user will login with his own password and system will ask him to change it. 
He will have 5 days (or other, see the next line) to create a new password.

**Comment by guide5232** [comment]
Ok thank you for help me
