### ISSUE TITLE
[Feature]    Notification from custom module, no link 

### ISSUE THREAD

**Issue by Maxpeg** [YetiForceCompany/YetiForceCRM#11609]
When creating a notification from a custom module, there are is no link to the place, where this notification was created.
![image](https://user-images.githubusercontent.com/54612661/65675167-594a7b80-e080-11e9-8924-b0e1830b209c.png)

Only tick is available. 

Would be great to automatically include a link of notification source.

**Comment by mrzewnicki** [comment]
Hello,

For sure since 5.0 stable version ( cuz i did it ) you can edit content of notification. I can add a Link to created record, check your workflow.
![image](https://user-images.githubusercontent.com/21024857/65750371-817dbd00-e108-11e9-9ec4-4349fe5b80e4.png)

**Comment by Maxpeg** [comment]
Hi, 
Help me find the exact place to make this work flow.
When I am in my custom module, I want to create a notification for another user, basically send him a short message to come to this record and do something.
I have two options to create a notification here:
![image](https://user-images.githubusercontent.com/54612661/65753625-f6211d80-e141-11e9-9408-267eaf0a289e.png)

Both this two methods has no links back to this record now. 
I tried to create a workflow for Notification module itself: 
![image](https://user-images.githubusercontent.com/54612661/65753894-7fd0eb00-e142-11e9-84eb-771e0b0f681f.png)
![image](https://user-images.githubusercontent.com/54612661/65753921-9119f780-e142-11e9-9e08-e0af265a07b6.png)

But for recipients I can only choose Users watching or Owner
![image](https://user-images.githubusercontent.com/54612661/65754046-cb839480-e142-11e9-80f9-593baa93b69f.png)
![image](https://user-images.githubusercontent.com/54612661/65754083-e0602800-e142-11e9-9770-a0a7d2cbdbbd.png)

I still receive original notification, seems like this workflow doesn't work.
Is it a wrong way, or I do it badly?

**Comment by mrzewnicki** [comment]
I don't see any wrong move. If that is possible maybe try change 
![image](https://user-images.githubusercontent.com/21024857/65773948-8d37a680-e13d-11e9-9617-978ecd626859.png)
to system. Maybe that will help.

Are you using 5.2 version?

**Comment by mrzewnicki** [comment]
Also you can check is that work on 
https://gitstable.yetiforce.com
and
https://gitdeveloper.yetiforce.com

**Comment by Maxpeg** [comment]
I'm using stable 5.2, sp 12.
I checked on developer, it looks the same. 
Is it works on your system?

**Comment by konadrian** [comment]
Please try to add into public static $PURIFIER_ALLOWED_DOMAINS in config/Security your crm's URL

**Comment by Maxpeg** [comment]
I added like this, is it a correct way to list domains? 
_public static $PURIFIER_ALLOWED_DOMAINS = [www.welformbase.cn]_

Unfortunately, no changes:
![image](https://user-images.githubusercontent.com/54612661/75499306-971f4780-5a04-11ea-8c49-c0e71d51db8e.png)

**Comment by rskrzypczak** [comment]
You must understand that you will not see related records if the notification module itself does not have such a relationship.
![image](https://user-images.githubusercontent.com/10221999/75515319-15c2b780-59fa-11ea-99b7-78a81b504af3.png)

**Comment by Maxpeg** [comment]
How to make this relation? 
Before the relation, I need to make a field in my custom module, but I can't find any field for a page link. Is there any?

I see how the standard modules send notifications with that link, but I can't figure out how they do it.

**Comment by z0lo13** [comment]
> You must understand that you will not see related records if the notification module itself does not have such a relationship.
> ![image](https://user-images.githubusercontent.com/10221999/75515319-15c2b780-59fa-11ea-99b7-78a81b504af3.png)

is it possible to expand subprocess field with another modules?

**Comment by bpabiszczak** [comment]
@z0lo13  this is open source, yes you can :)

**Comment by rioshaz** [comment]
@bpabiszczak saying its opensource doesnt help much. can u give a solution boss..

**Comment by JakubSzczesny** [comment]
This worked for me:
![Przechwytywanie](https://github.com/YetiForceCompany/YetiForceCRM/assets/98385591/22bcfe44-d2d6-4f95-b1f5-85a7c45c24f8)
Simply creating a redirect "by hand" in docs source. Be sure not to place any dots in href
