### ISSUE TITLE
Campaign | Send via Email [bug] 

### ISSUE THREAD

**Issue by keithhanna** [YetiForceCompany/YetiForceCRM#11604]
Have just started testing YetiForce and can not get the Send via Email function to work within Campaigns on version 5.2.15.  

As the button does not exit on the latest Stable and Developer editions so I can not re-create the bug on either of these systems.

After opening a Campaign and select a Lead or Contact and then click the Send Via Email button I get the message 'Please select at least one record' and the new window does not open.

![image](https://user-images.githubusercontent.com/55789629/65596916-d3e79e00-df8f-11e9-82d8-bf6801e7a1fc.png)

As I'm new to YetiForce and you direct me on how I can fix this.

**Comment by metrotyranno** [comment]
I have the same issue, See this video I made

https://1drv.ms/u/s!AhVD0Jo2ABPPlrAV4rOMVrTE-5uBlA

**Comment by keithhanna** [comment]
@metrotyranno If you enable the button on the latest Stable editions under https://gitstable.yetiforce.com/ the same error occurs but can't seem to the the button working on the developer site https://gitdeveloper.yetiforce.com/.

Which would suggest this functionality isn't working yet.

**Comment by apcloic** [comment]
Hi,
Same issue here, see attached screen2gif record.
I found that clicking again on "select all" option is working but this is just a workaround when you send to all related records.
![campaign_select_related_records_issue](https://user-images.githubusercontent.com/2930560/73006715-5f245380-3e0b-11ea-9017-49abf364a8ed.gif)
