### ISSUE TITLE
[Question] Relate email to custom module? 5.1.0

### ISSUE THREAD

**Issue by LukaszTod** [YetiForceCompany/YetiForceCRM#11616]
### Description

Is it possible to relate an email to custom module? How can I do this in YF 5.1.0?

![Zrzut ekranu 2019-09-26 o 17 45 04](https://user-images.githubusercontent.com/34128804/65703790-a1b86800-e085-11e9-93c8-e2a1c48ddaac.png)

**Comment by svdaru** [comment]
> ### Description
> Is it possible to relate an email to custom module? How can I do this in YF 5.1.0?
> 
> ![Zrzut ekranu 2019-09-26 o 17 45 04](https://user-images.githubusercontent.com/34128804/65703790-a1b86800-e085-11e9-93c8-e2a1c48ddaac.png)

Hello. How did you solve it?

**Comment by LukaszTod** [comment]
Hello, unfortunately I still didn't resolve it
