### ISSUE TITLE
[Display Bug] Adding a service shows a poorly formatted list to select from

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1161]
When trying to add a service to a lead under the products & services tab, and clicking on the icon next to the Interested in services, a poorly formatted list of services is shown to select from.
![bug04](https://cloud.githubusercontent.com/assets/10230144/8329146/5f2495e6-1a77-11e5-9710-a4ba80aa0721.jpg)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/0f7881f7e8d7382a3e21e9bffe88a0cf2690a5ab
