### ISSUE TITLE
[Question] Yetiforce upgrade on Softaculous

### ISSUE THREAD

**Issue by tfegyo** [YetiForceCompany/YetiForceCRM#11625]
Hi!

I tried to upgrade Yetiforce (from 4.3) which is installed in a softaculous framework, so not self hosted. There is no softaculous updgrader, therefore I've downloaded the zip files from github, and tried to install them as described:
Software configuration > Standard modules > Modules – Installation > System settings   :: Install from file

The problem is, that the uploaded zip file is declared as a possible threat by the malware security system of the server because of the included php scripts. We cannot avoid this security feature on the server. The zip file does not get to the yetiforce installer.

I can upload the zip file on the server without any issue, it is filtered when a webservice tries to do this.

My question is whether I can run the upgrader manually or is there a way to process the manually uploaded zip file. According to the system admins if I could start processing a local zip file that should work.

Regards,

**Comment by tfegyo** [comment]
No one had this problem before?

**Comment by bpabiszczak** [comment]
Update the system locally and upload to the server after the upgrade.
