### ISSUE TITLE
[Bug] Added contact field cannot be populated

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1162]
1. Add a field of type 'Related field 1:M' relating to the module 'Contacts', for example, in 'Leads'
2. Create a new 'Leads' record
3. Click on the '+' near the 'Contacts' field
4. The error shown below is display
![bug06](https://cloud.githubusercontent.com/assets/10230144/8329798/b731b246-1a7c-11e5-82cd-0ad36d7893dd.jpg)
5. Alternatively click on the magnifier
6. A windows pops-up showing the main screen of YetiForceCRM rather than a list to select a contact from

This test case does work on test.yetiforce.com, but fails in version 2.0.178

**Comment by mariuszkrzaczkowski** [comment]
Tests on version 2.0.183 and working properly. Check at this address https://test.yetiforce.com/test/index.php?module=Leads&view=Edit&record=109
