### ISSUE TITLE
[Question]    PDF EDITOR       

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#11635]
I don't remember exactly, but I think it was version 5.0, where the first difference between the old and the new PDF editor was noticed, and during that time I read a lot of comments that it didn't work as it should, or that it worked at least that way as in version 4.3. Any successful business ends with an invoice, but unfortunately I can't send it to my client because it's a terrible form. If you have a different solution that is payable no problem I'm happy to buy it just to work. But if you ask me why I insist on YETIFORCE? Because he's the best!

**Comment by vovpff** [comment]
@fbojan You found solution?

**Comment by fbojan** [comment]
@vovpff   There was no response or help, so I'll just try to make a normal PDF in HTML

**Comment by z0lo13** [comment]
use another pdf library for example old mpdf is much more flexible

**Comment by fbojan** [comment]
@z0lo13 If I understand correctly, from version 4.3 I copy the library to 5.2 and replace what ?? Or where? Thank you
