### ISSUE TITLE
[Question]  CRON not working          

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#11648]
Hy all ! 

   After the update (5.2.0), CRON stopped working and i got this error : 
2019-10-01 13:32:13 | LBL_WORKFLOW - Not ready to run as the time to run again is not completed
  I am triggering the CRON with this command from PLESK : curl --silent 'http://xxxxxxx.com/cron.php?app_key='xxxxxxxxxxxxxxxxxxxxxxxx' &>/dev/null
 Any ideas on what could have happened ? 
 Until the update, everything worked good with the CRON.

  Thanks all!

**Comment by acsinsurancegroup** [comment]
@liviubbo What kind of server and or panel are you running?

Try this command: /usr/bin/wget -O - -q -t 1 https://yoursystemurl.com/cron.php?app_key=yourappkeyfoundinconfigfolderandfilenameis main.php

**Comment by mariuszkrzaczkowski** [comment]
task suspended, you need to change the database status to 1

**Comment by acsinsurancegroup** [comment]
> task suspended, you need to change the database status to 1

I did this exact step to see if it would fix my question here https://github.com/YetiForceCompany/YetiForceCRM/issues/11421#issuecomment-537873440

and although the hazard icon went away, all it does now is sit there and spin in my Cal Dav cron task? Any idea why this is happening @mariuszkrzaczkowski?

**Comment by mariuszkrzaczkowski** [comment]
@acsinsurancegroup 
did you check on 5.2 + SP?

**Comment by acsinsurancegroup** [comment]
> @acsinsurancegroup
> did you check on 5.2 + SP?

@mariuszkrzaczkowski Yes sir I have Version 5.2 + the latest SP V.13 and I have restarted my server and same thing.

**Comment by mariuszkrzaczkowski** [comment]
logs

**Comment by acsinsurancegroup** [comment]
> logs

Do you want me to post the Debug from DAVx5? How do I get the actual logs other than the ones I posted last time from within the system that you said was not the logs you needed?

**Comment by mariuszkrzaczkowski** [comment]
I need logs from crm, send to e-mail github@yetiforce.com

**Comment by acsinsurancegroup** [comment]
@mariuszkrzaczkowski It's fixed, you're awesome. See my reply here:

https://github.com/YetiForceCompany/YetiForceCRM/issues/11421#issuecomment-539390259

**Comment by liviubbo** [comment]
Hello all ! Thank you all for the help ! 

The fix was : 
     - i had some custom calculations made in automatic workflows (scheduled) so, i disabled them one by one util i figured out wich was the one that was causing CRON to take so long (time out)
     - I guess that one of the workflows had a table issue. I guess, but, it fixed my problem.
