### ISSUE TITLE
[Question] Solution for negative value in invoice/quote [old entry throws an error]  

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11646]
Hi,
How is it possible to change the limitation to only use positive value in invoice/quote?

The old Issue-Solution does not help anymore, because the Link within throw an error.
https://github.com/YetiForceCompany/YetiForceCRM/issues/4392
So the solution is not longer usable...
Would be great to get help for.
Thanks Martin

![Bildschirmfoto 2019-10-01 um 08 34 14](https://user-images.githubusercontent.com/6169308/65939464-4c35df80-e426-11e9-8fb8-6af869b6d9a2.png)

**Comment by mariuszkrzaczkowski** [comment]
duplicate

**Comment by mad99** [comment]
If anybody has the same problem-errorThrowing:
You have to login first.

Hope the other issue will updated with usable solution. Currently only the prefix module is showing.

**Comment by mad99** [comment]
Does anybody now a solution for negative value in invoices/quotes?
I have to define more then one described discounts. So a product with negative value is the best solution I guess.
