### ISSUE TITLE
how to return my old default menu?

### ISSUE THREAD

**Issue by snenko** [YetiForceCompany/YetiForceCRM#11649]
I accidentally deleted items from the default menu.

![image](https://user-images.githubusercontent.com/11363876/65964725-347e4b80-e466-11e9-8890-5cdde4577902.png)

I put content from a fresh installation yetiforce into the file user_privileges/menu_0.php.
It's helpful for small time. But next, my deleted default menu it's going back.

What do I need to do?

**Comment by acsinsurancegroup** [comment]
@snenko Simply re-upload the user_privileges/menu_0.php file from the original download of the CRM and overwrite the file on the server. That's it.

**Comment by snenko** [comment]
I replace the menu_0.php file with the one from github.

It helped to give access to users, but the menu editing problem is still there. 

I found table yetiforce_menu. This table saves information about menus for users.

I am going to replace rows from clean Yetiforce.



**I think the default menu should not be editable.**

**Comment by snenko** [comment]
I remove all records from the table:
TRUNCATE TABLE yetiforce_menu;

Then import default data of the table from install/install_schema/data.sql.

The problem is resolved.
