### ISSUE TITLE
[bug] ListView: comparison operators not working yet

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#11647]
# 🐞 bug report

### ⁉️ Describe the bug

After update to 5.2 comparison operators are ignored in ListView search row for values.

5.1:

![image](https://user-images.githubusercontent.com/8545791/65940085-43e2a200-e430-11e9-8560-e4aa35d9ea53.png)

![image](https://user-images.githubusercontent.com/8545791/65940100-4e9d3700-e430-11e9-9734-bdd395d5f68d.png)

![image](https://user-images.githubusercontent.com/8545791/65940147-6c6a9c00-e430-11e9-9fd9-8c410ef6e828.png)

5.2:

![image](https://user-images.githubusercontent.com/8545791/65940183-80ae9900-e430-11e9-8dd0-1d26a2b84301.png)

![image](https://user-images.githubusercontent.com/8545791/65940189-87d5a700-e430-11e9-839a-1b25e8bb4fd8.png)

![image](https://user-images.githubusercontent.com/8545791/65940219-9e7bfe00-e430-11e9-904b-3274b1765f35.png)

### 👎 Actual Behavior

This is sad :(

### 👍 Expected Behavior

:)

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
* [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  gitdev 5.2.25, local 5.2.12 SP9

**Comment by vovpff** [comment]
@mariuszkrzaczkowski pls take a look to this issue

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thx a lot!

**Comment by mariuszkrzaczkowski** [comment]
5.2.0_ServicePack_v16.zip
