### ISSUE TITLE
LBL_NOTICE_FOOTER in mail template, edit

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#1165]
How do I edit the LBL_NOTICE_FOOTER in the mail template? where is that message?

**Comment by rskrzypczak** [comment]
Language Management->Edit language->Module:Vtiger
![footer](https://cloud.githubusercontent.com/assets/10221999/8348832/ff357ca8-1b17-11e5-9dc3-0f3738a859f9.jpg)

**Comment by rskrzypczak** [comment]
Language Management->Edit language->Module:Tickets
![footer](https://cloud.githubusercontent.com/assets/10221999/8348914/bc06553c-1b18-11e5-9e44-18918f0095f9.jpg)
