### ISSUE TITLE
[Question]: Working solution to use negative value for invoice/quote [Old Issue does not link to a working solution!]           

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11651]
Hi,
Does anybody know a solution for negative value in invoices/quotes?
I have to define more then one exactly described discounts. 
So a product with negative value (E.g. -330€) would be the best solution, I guess.

There is an old [closed issue](https://github.com/YetiForceCompany/YetiForceCRM/issues/4392) for same problem.
But the solution-link is pointing (after login) to the prefix-settings from YetiForce: **_There, I can not find a solution or setting to define «accept negative value»._**

### Old solution does not help/work and Issue is closed
_To ask for solution in a closed Issue, I guess there is quite no chance to get answer from community. This is the reason why I reopen a new one._

### Maybe relevant code would help to find a solution?
In source-code I found perhaps the right line https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/include/fields/CurrencyField.php#L275
which checks values under 0. Maybe this would be the right place in code. But I can't find the relevant setting in YetiForce.
### My trial & error
I tried different approaches but I can't find the settings for change the error-popup-throwing behavior in invoice-field.

- I tried to change the User-Settings «Digit grouping pattern». This does not change the negative-value blocking. 
- I also tried to change the code with no change. And I know, this would be neither safe nor wise for updates. But in despair, people do a lot of things. **_-> I'm trying to understand why in the old explanation/old YetiForce version a solution might be possible that doesn't work anymore, or maybe the settings were "stashed" somewhere completely different._**

I just can't find the place/settings. 
### Question:

- **Does anybody have a working setting/solution to use negative product-amount for invoice or quotes?**
- **Where is the setting stashed to use negative values in invoice or quotes?**

Thank you for help and hints
Martin

<img width="587" alt="Bildschirmfoto 2019-10-01 um 21 16 22" src="https://user-images.githubusercontent.com/6169308/65993208-0feb9900-e491-11e9-864b-7da6704307ca.png">

The Link in the old Issue is pointing to prefix-setting. Can't find a relevant settings also in all other module-settings from this page.
![Bildschirmfoto 2019-10-01 um 08 45 59](https://user-images.githubusercontent.com/6169308/65940239-4fca6600-e428-11e9-9430-74ffdbb30718.png)

**Comment by mad99** [comment]
Ohh :o((
1 week later - no answer.
Maybe some could give me a hint about:

- **Is it NOT possible to create negative value for invoices/quotes in the new version 5.X from YetiForce?** (So this possibility is not usable in current YF-versions anymore?)

- **Or is there some possibilities but it's to complicated to describe?** (Then I will search again for this in code, google, docs and so on)

Would be very nice to get some hint in one direction. 
I'm searching and trying and nothing helps :o((

Thanks
Martin

**Comment by mariuszkrzaczkowski** [comment]
you can comment on this, but then you will allow negative numbers everywhere in CRM, which can cause errors.
https://github.com/YetiForceCompany/YetiForceCRM/blob/78ac92a17c1d865eb238cb7a772dc9ac7bb69acc/public_html/layouts/resources/validator/FieldValidator.js#L1030-L1032

**Comment by mad99** [comment]
Wouw Thank you very much @mariuszkrzaczkowski!

Now it is possible to use multi "virtual" Discount-Product. So I can describe each of the amount for its own. 
Great solution!

I know, there are maybe draw-backs in system. But actually this is the only solution for a problem without, I couldn't use YetiForce at all.

Now I can use YF! Thank you.

### Code-Solution:
For others with the same problem: There are 2 Files you have to change (a guess). At least it was working only, when I also changed the matching code in min.js File.

Changes are on your one risk, so please backup your files (and dublicate the original also):
The change in FieldValidator.js:

`	if (strippedValue < 0) {
				/*errorInfo = app.vtranslate('JS_ACCEPT_POSITIVE_NUMBER');
				this.setError(errorInfo);
				return false;*/
			}`

The change in FieldValidator.min.js:

`'JS_CONTAINS_ILLEGAL_CHARACTERS'),this.setError(errorInfo),!1;/*if(0>strippedValue)return errorInfo=app.vtranslate('JS_ACCEPT_POSITIVE_NUMBER'),this.setError(errorInfo),!1*/;var maximumLength='undefined'==typeof`

In min.js I commented out the hole if() part. 

Hope sharing helps others.

**Comment by kamiro16** [comment]
Hey, @mad99 

I try to use your solution on version 5.3 SPv4 but doesnt work :( 
The validate in field its ok, but when i try save document system warrning me about incorrect value. 
Have you any idea for this problem?

**Comment by mad99** [comment]
Hey @kamiro16,
This is the reason why I hesitate to update YetiForce.
I don't do that with any other tool/app, it's probably also grossly negligent, but my YF is still in the 4.x version.
The tool is ingenious, if it works. If not, you are dependent on the goodwill of one or extremely few programmers.
The documentation is just already ... not existing.

Unfortunately I was also dependent on the help of @mariuszkrzaczkowski . The code is just too complex to be understood by an outsider with basic knowledge, like me.

It simply lacks a code explanation or a broader base of programmers/users.

Unfortunately I have no idea what the reason could be. First I had the problem that I had to find recommended changes in the uncompressed JS-code also in the compressed code and replace them cleanly.

- **But I think you already did that!?**

If so, probably something has changed in YetiForce 5.x in the DB-Layer-Abstraction. Maybe an additional check.

It would have been great if YetiForce had been given **«a possibility in the setting»** to allow this rudimentary and in my opinion very important function of **«negative amounts»** per checkbox-click.

### Maybe there is even exactly this solution in 5.x. 
And that's could be the reason, why the workaround is no longer necessary/or working.
But as usual, without detailed documentation, YetiForce and its possibilities are sometimes really a frozen monster from the stone age. Has huge feet and possibilities, but getting close to it and finding a real close friend makes it almost impossible...

Sorry, I hope one of the developers is a better help for you.

**Comment by 2techcomputing** [comment]
@kamiro16 The solution that @mad99 provided worked perfectly fine for me on version 5.x., make sure you perform edits to both of the mentioned files for it to function properly.

**Comment by kamiro16** [comment]
@2techcomputing I can write negative value in validator, but can't save. 
System give information the value incorrect.
U Can save? 

Can u help me?

**Comment by 2techcomputing** [comment]
@kamiro16 I was able to make the change and then save the invoice i created. Here are the files that i edited and used.


[FieldValidator.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/4973420/FieldValidator.zip)

**Comment by kamiro16** [comment]
@2techcomputing 

wow! Perfect! Thanks a lot! 
Can I do something for you?

best regards!

**Comment by 2techcomputing** [comment]
@kamiro16 Its all good, i am glad it worked out for you. :)
