### ISSUE TITLE
[Question]           Invoke custom function. Yetiforce vs Vtiger. Different approach?

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#11659]
Hi all, 

I want to invoke a custom function in my workflows. When I used Vtiger then the code below worked. In YetiForce this is different. Any ideas what is changed? 

**Goal: Calculate the age of a contact based on his birthday, then store this value in the field 'age'.**
```

<?php

chdir(dirname(__FILE__) . '/..');
require_once 'include/utils/utils.php';

global  $adb;

function calculateAge($entity){
	
	global  $adb;
	
	$entity_id = vtws_getIdComponents($entity->getId());
	$id = $entity_id[1];

	$birthday   = $entity->get('birthday');
	$age = 0;

	$from = new DateTime($birthday);
	$to   = new DateTime('today');
	$age  =  $from->diff($to)->y;
			
	$result = $adb->pquery("update vtiger_contactdetails
	set age = ? where contactid = ?  ",array($age,$id));
}

?>
```

**Comment by mariuszkrzaczkowski** [comment]
everything is rewrite see example 

https://github.com/YetiForceCompany/YetiForceCRM/blob/5c54c0efbe408ec6c0027a16d99f7a1d68f61968/modules/Users/workflows/UsersWorkflow.php#L12-L29

https://github.com/YetiForceCompany/YetiForceCRM/blob/5c54c0efbe408ec6c0027a16d99f7a1d68f61968/modules/HelpDesk/workflows/HelpDeskWorkflow.php#L9-L157

**Comment by LaurensCleyman** [comment]
Ok I'm a step closer thanks to the examples.

But how can I update the field 'age' with the result?

```
<?php

class ContactsWorkflow
{
	public static function Leeftijd(Vtiger_Record_Model $recordModel)
	{
		\App\Log::trace('Entering leeftijd');
		
		$birthday = $recordModel->get('birthday');
		$id = $recordModel->get('contactid');
		
		$from = new DateTime($birthday);
		$to   = new DateTime('today');
		$age  =  $from->diff($to)->y;*/
		
		//How to:
		//UPDATE vtiger_contactdetails
		//SET age = $age
		//WHERE contactid = $id
		
		\App\Log::trace('leeftijd');
	}
}
```

**Comment by z0lo13** [comment]
$recordModel->set('age', $age)
$recordModel->save();
