### ISSUE TITLE
[pl][pytanie] Zarządzanie czasami zgłoszeń

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11656]
Cześć, 
Czy mogę gdzieś ustawić jaki status oznacza że ma się zacząć liczyć np czas bezczynności czy jest to predefiniowane?

**Comment by bpabiszczak** [comment]
W edycji słownika [dla pól status]
![image](https://user-images.githubusercontent.com/10197525/66062251-5b5d8000-e541-11e9-87ae-e5962b0c5ae2.png)
