### ISSUE TITLE
[bug] currency fields (US dollar) are prefixed with '&#36' instead of '$'.

### ISSUE THREAD

**Issue by sirwinston1** [YetiForceCompany/YetiForceCRM#11662]
🐞 bug report

⁉️ Describe the bug

After updating to version 5.2 and installing the 5.2 service pack the following issues occurs:
-All currency fields (US dollar) are prefixed with '&#36' instead of '$'.  

Go to 'my CRM'
Go to any module with a currency fields

👍 Expected Behavior

All currency fields should be displayed as $1.00 not &#36 1.00

📷 Screenshot of configuration

https://i.imgur.com/5d8JVSW.png
https://i.imgur.com/f6DcOmC.png
https://i.imgur.com/QXaxSZz.png
https://i.imgur.com/Zzhc9g3.png

📝 PHP/Apache/Nginx/Browser/CRM Logs

Nothing in my logs

🌍 Your Environment
Yetiforce 5.2.0
Ubuntu Server w/ PHP 7.2
Chrome, Edge, Firefox - doesn't matter
mysql 
Cron is working correctly

❓ Additional context

https://i.imgur.com/wIPJ9nD.png

**Comment by sirwinston1** [comment]
Bug also appears in the dev version as well

https://imgur.com/IUzl0dc

**Comment by z0lo13** [comment]
Same issue on 5.2.0

**Comment by z0lo13** [comment]
![изображение](https://user-images.githubusercontent.com/23143958/66722767-abf59880-eddf-11e9-902f-d8b5ee8d4e19.png)

**Comment by sirwinston1** [comment]
Anyone have an idea how to fix this?

**Comment by maeglin4** [comment]
same problem here.

**Comment by swsin84** [comment]
same, 5.2 with service pack...

**Comment by swsin84** [comment]
I am not programming guy so I dont know if this is right fix, but its worked for me..

/include/fields/CurrencyField.php

Line 236
$returnValue = $currencySymbol. ' ' . $currencyValue;

Switch to
$returnValue = html_entity_decode($currencySymbol, ENT_COMPAT, 'UTF-8') . ' ' . $currencyValue;
