### ISSUE TITLE
Price Break for different quantities    

### ISSUE THREAD

**Issue by apruszenski** [YetiForceCompany/YetiForceCRM#11669]
### Describe the solution you'd like
Currently we can only enter 1 price for a particular product.
Widget X - Price 100.00
But I deal with products that the price is different for different quantites
Widget X quantities 1-10 - 150
Widget X quantities 11-25 - 125
Widget X quantities 26+ - 100

### Is your feature request related to a problem? Please describe.
Need a way to enter products easier that have price breaks in higher quantites

**Comment by bpabiszczak** [comment]
We can add it to the system for a fee :]
