### ISSUE TITLE
[Question] Can't get Calendar New Layout ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#11668]
Hi,

I'm using YetiForce CRM 5.2 Service Pack v13 on a dedicated VPS (Ubuntu 18.04)

I'm unable to get the new calendar layout like described in the following issue #9525

I've tried the 'edit menu' trick but without luck, still old layout.

Is there any other parameter or configuration setting to do ?

Regards

**Comment by vovpff** [comment]
```
