### ISSUE TITLE
Workflow Task - Create Entity

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1166]
How can I set workflow which for ex. create new project etc. when conditions are met ? Currently I can create only:
![entity](https://cloud.githubusercontent.com/assets/4824588/8339201/1b170ae8-1ab6-11e5-8705-a1d1a83d455f.JPG)

any suggestions ?

**Comment by mariuszkrzaczkowski** [comment]
This list is created based on relationships. You can see here all the modules with which is associated a module for which you are creating the workflow.

**Comment by florek41** [comment]
All right then. Is there any way to add relationship to module ? Can I do that from system settings ?

**Comment by mariuszkrzaczkowski** [comment]
Yes, here https://test.yetiforce.com/index.php?parent=Settings&module=LayoutEditor&mode=showRelatedListLayout&block=2&fieldid=41&sourceModule=Campaigns 
and here https://test.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&block=2&fieldid=33
