### ISSUE TITLE
How can we disable the left menu(few module) ?

### ISSUE THREAD

**Issue by Abhilash989** [YetiForceCompany/YetiForceCRM#11660]

**Comment by mariuszkrzaczkowski** [comment]
Software configuration > Standard modules > Menu - Configuration

https://gitdeveloper.yetiforce.com/index.php?module=Menu&view=Index&parent=Settings&block=2&fieldid=40

**Comment by acsinsurancegroup** [comment]
@Abhilash989 Why would you want to disable the menu? Kind of hard to work without one isn't it?

**Comment by Abhilash989** [comment]
I have different roles, Sales Executive, Sales Head and some other users so I want to give menus accordingly. Some menus are required for User1 and some for User2. 
Thnaks

**Comment by acsinsurancegroup** [comment]
@Abhilash989 Oh that's easy. Simply go to your Admin settings area under Standard Modules and then select Menu - Configuration. Once that loads in your upper right hand corner drop down it should say Default menu. Click the arrow down and select the role you need to add a menu for. The easiest thing to do is click on the green button on the left hand side where it says Copy menu. Once you have a starting point, just remove or add menu lines you need for the specific role you're working in.
