### ISSUE TITLE
[Question]           How to update a field in a custom function

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#11678]
Hi all, 

I created a custom function that calculates the age of a contact in _modules/Contacts/workflows/ContactsWorkflow.php_

Then i registered the function in table _com_vtiger_workflowtasks_entitymethod_

How can I update the field _age_ with the age of the contact?

```
<?php

class ContactsWorkflow
{
	public static function age(Vtiger_Record_Model $recordModel)
	{
		\App\Log::trace('Entering age');
		
		$birthday = $recordModel->get('birthday');
		$id = $recordModel->get('contactid');
		
		$from = new DateTime($birthday);
		$to   = new DateTime('today');
		$age  =  $from->diff($to)->y;*/
		
		//How to:
		//UPDATE vtiger_contactdetails
		//SET age = $age
		//WHERE contactid = $id
		
		\App\Log::trace('age');
	}
}
```

**Comment by apcloic** [comment]
Hi @LaurensCleyman 

No need to create a custom function for that, you should simply use built-in workflow module.
Have a look here : #10736

**Comment by LaurensCleyman** [comment]
Hi @apcloic , 

Thanks, but I know :-) 
This is just a simple expression as an example, but I want to make more complex calculations that are not possible via the built-in workflow module. :-) 

Kind regards,

**Comment by apcloic** [comment]
@LaurensCleyman 
Ok, I think you simply have to study an existing workflow to see how it works, for example this one :
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/HelpDesk/workflows/HelpDeskWorkflow.php

**Comment by LaurensCleyman** [comment]
I can't find the solution .. 
Does anyone have an example of a function that updates a field of a Contact record?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/687f6faaa61651f16dc40e3cccb62f8445c4ba4b/modules/com_vtiger_workflow/tasks/VTUpdateCalendarDates.php#L73L76

**Comment by LaurensCleyman** [comment]
It does not work.. any ideas what I do wrong?

[<?php

class ContactsWorkflow
{
	public static function age(Vtiger_Record_Model $recordModel)
	{
		$birthday = $recordModel->get('birthday');
		
		$from = new DateTime($birthday);
		$to   = new DateTime('today');
		$age  =  $from->diff($to)->y;
		
		$recordModel->set('age',$age);
		$recordModel->save();
	}
}](url)

**Comment by bpabiszczak** [comment]
No, the programmer must check it. We do it only for a fee.

**Comment by Patriciawa** [comment]
@LaurensCleyman did you find a solution? I'm having the same issue as yours, the records just won't update this way.
Edit: there was a typo in `com_vtiger_workflowtasks_entitymethod` it works now.
