### ISSUE TITLE
[Question] Customize E-Mail template before sending campaign

### ISSUE THREAD

**Issue by metrotyranno** [YetiForceCompany/YetiForceCRM#11676]
We are currently able to send out campaign emails from set templates, However there is a wish to add some custom data prior to sending. We want to have blank fields in the template which are filled in before the email is queued.

An example of this would be: Add the location & expected resolution time of an outage.

Is this accomplish able in the current version? Is this a feature you would like to adopt?

If not yet possible, I would envision it to be custom data fields in the template which need to be filled out in a form prior to sending.

A quick example would be something like this:

https://i.imgur.com/1cg1vpa.png

**Comment by metrotyranno** [comment]
Pretty much the wysiwyg editor vtiger has prior to sending an email.

Select from template & edit it.

**Comment by bpabiszczak** [comment]
We are currently not planning to add such functionality.
