### ISSUE TITLE
Problem with interface design (Calendar)

### ISSUE THREAD

**Issue by JeRRimix** [YetiForceCompany/YetiForceCRM#1167]
The last version downloaded 25/06/2015
There are problems in Calendar template with buttons in English.

![image](https://cloud.githubusercontent.com/assets/13039836/8342191/c9c3f4b6-1ae3-11e5-9b9b-fda1516ad3d7.png)

Also there are a big problems in Russia lang:

![image](https://cloud.githubusercontent.com/assets/13039836/8342254/301c5a32-1ae4-11e5-9e3b-6c7a56f235c4.png)

Such problems there are in all items:

![image](https://cloud.githubusercontent.com/assets/13039836/8342452/957eb414-1ae5-11e5-85a9-2537c8156607.png)

![image](https://cloud.githubusercontent.com/assets/13039836/8342455/a3409414-1ae5-11e5-8df0-fe3167c58637.png)

**Comment by waw555** [comment]
The screen resolution is among you?

**Comment by JeRRimix** [comment]
Screen resolution is not changed. So in Test CRM on official site is no such problem.

**Comment by JeRRimix** [comment]
:((((

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/82fa5017b84b20a23d5bdcf2580771f1a9ecc59d
