### ISSUE TITLE
[Question] Why are products in grey and others in white ??

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#11679]
i was doing a transfer from one storage to an other, but when i come back to change some thing i noticed that some products lines are grey'ed out and other normal in white. 

What is the difference and why is it like this ??

![image](https://user-images.githubusercontent.com/45770116/66335323-d4295700-e908-11e9-8db2-4b782b58e63e.png)

**Comment by vovpff** [comment]
Looks strange

**Comment by maeglin4** [comment]
and those in white are missing letters and words at the end but its the good price.

**Comment by mariuszkrzaczkowski** [comment]
check your browser console so it shouldn't look like this

**Comment by maeglin4** [comment]
this ? i right click "inspect" on the page and then click console

![image](https://user-images.githubusercontent.com/45770116/66343062-d0053580-e918-11e9-9b1c-2e1abbb7e1ca.png)

**Comment by konadrian** [comment]
What do you mean by saying "transfer" which action did you perform?
