### ISSUE TITLE
Problem with desktop (home page)

### ISSUE THREAD

**Issue by JeRRimix** [YetiForceCompany/YetiForceCRM#1168]
This is a last version from 25/06/2015

After installation and authorization as admin we looked white screen at Home page:

![image](https://cloud.githubusercontent.com/assets/13039836/8342338/c301b5d6-1ae4-11e5-9194-5961f9f4a93e.png)

**Comment by waw555** [comment]
In setting role and add widgets

https://test.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67

**Comment by JeRRimix** [comment]
Are you about this?

![image](https://cloud.githubusercontent.com/assets/13039836/8348092/43a3468a-1b28-11e5-9a57-24cba1157d76.png)

**Comment by waw555** [comment]
Widgets Management
Менеджер Виджетов

https://test.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67

**Comment by JeRRimix** [comment]
I found it! Thank you! It seems too complicated setup and the inclusion of widgets. In place of the the developers I would be simplified.
