### ISSUE TITLE
[Question] Portal Users Should be added manually?

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#11681]
### Description

When I create contact there are two checkmarks asking about the portal. When I create a contact it never creates a user in `https://gitdeveloper.yetiforce.com/index.php?module=WebserviceUsers&view=List&parent=Settings&block=5&fieldid=106
`
Is that supposed to create the user automatically? Or we should implement a custom function?

**Comment by acsinsurancegroup** [comment]
@z0lo13 Has the new Portal even be released yet?

**Comment by metrotyranno** [comment]
No, The new portal has not been released yet. Last time I asked it should be released around this week.

**Comment by acsinsurancegroup** [comment]
@metrotyranno Ok last I heard it was gonna be 2-3 weeks but that was almost a month ago. Glad to hear it's almost ready. Thanks.

**Comment by metrotyranno** [comment]
@acsinsurancegroup same

**Comment by bpabiszczak** [comment]
The portal is not finished [currently it is a beta version]. You want to use it, you must have a programmer.
