### ISSUE TITLE
[bug] Trash symbols when multiline comment added

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#11695]
# 🐞 bug report

### ⁉️ Describe the bug

![image](https://user-images.githubusercontent.com/8545791/66392330-34d39500-e9d8-11e9-9018-592f66e1eba5.png)

![image](https://user-images.githubusercontent.com/8545791/66392459-98f65900-e9d8-11e9-8be4-6f523592bb7b.png)

![image](https://user-images.githubusercontent.com/8545791/66392517-bf1bf900-e9d8-11e9-942c-6b642a9e7c1f.png)

![image](https://user-images.githubusercontent.com/8545791/66392614-0d30fc80-e9d9-11e9-8a6c-472577231d38.png)

### 🔥 How to trigger the error

Just add multiline comment for some record and check update widget or comment header.

### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| local 5.2.15, current gitdev

**Comment by bpabiszczak** [comment]
I don't see an error. If the error occurs in the gitdeveloper version, please describe it better.
