### ISSUE TITLE
/home/buukcguc/public_html/erp/cron/cron.sh: line 20: /usr/php/71/usr/bin/php-cli: No such file or direct

### ISSUE THREAD

**Issue by andrewchaosun** [YetiForceCompany/YetiForceCRM#11694]
I receive the following everyday from my email box, guess there is something wrong with the cron. 
/home/buukcguc/public_html/erp/cron/cron.sh: line 20: /usr/php/71/usr/bin/php-cli: No such file or direct

__________________________
Server Time: Tue, 08 Oct 2019 05:25:02 -0400

Execute scheduled task: Cleanup old sessions (core\task\session_cleanup_task)
... started 05:25:02. Current memory use 16.7MB.
... used 7 dbqueries
... used 0.0097100734710693 seconds
Scheduled task complete: Cleanup old sessions (core\task\session_cleanup_task)
Execute scheduled task: Delete unconfirmed users (core\task\delete_unconfirmed_users_task)
... started 05:25:02. Current memory use 17.7MB.
... used 1 dbqueries
... used 0.00032496452331543 seconds
Scheduled task complete: Delete unconfirmed users (core\task\delete_unconfirmed_users_task)
Execute scheduled task: Delete incomplete users (core\task\delete_incomplete_users_task)
... started 05:25:02. Current memory use 17.7MB.
... used 0 dbqueries
... used 2.4080276489258E-5 seconds
Scheduled task complete: Delete incomplete users (core\task\delete_incomplete_users_task)
Execute scheduled task: Clean backup tables and logs (core\task\backup_cleanup_task)
... started 05:25:02. Current memory use 17.8MB.
... used 2 dbqueries
... used 0.00049400329589844 seconds
Scheduled task complete: Clean backup tables and logs (core\task\backup_cleanup_task)
Execute scheduled task: Cleanup contexts (core\task\context_cleanup_task)
... started 05:25:02. Current memory use 17.8MB.
Cleaned up context instances
... used 11 dbqueries
... used 0.004141092300415 seconds
Scheduled task complete: Cleanup contexts (core\task\context_cleanup_task)
Execute scheduled task: Remove expired cache entries (core\task\cache_cleanup_task)
... started 05:25:02. Current memory use 17.9MB.
... used 1 dbqueries
... used 0.00015497207641602 seconds
Scheduled task complete: Remove expired cache entries (core\task\cache_cleanup_task)
Execute scheduled task: Background processing for messaging (core\task\messaging_cleanup_task)
... started 05:25:02. Current memory use 17.9MB.
... used 2 dbqueries
... used 0.00028896331787109 seconds
Scheduled task complete: Background processing for messaging (core\task\messaging_cleanup_task)
Execute scheduled task: Send new user passwords (core\task\send_new_user_passwords_task)
... started 05:25:02. Current memory use 17.9MB.
... used 1 dbqueries
... used 0.00024795532226562 seconds
Scheduled task complete: Send new user passwords (core\task\send_new_user_passwords_task)
Execute scheduled task: Send failed login notifications (core\task\send_failed_login_notifications_task)
... started 05:25:02. Current memory use 17.9MB.
... used 0 dbqueries
... used 2.6941299438477E-5 seconds
Scheduled task complete: Send failed login notifications (core\task\send_failed_login_notifications_task)
Execute scheduled task: Legacy cron processing for plugins (core\task\legacy_plugin_cron_task)
... started 05:25:02. Current memory use 18MB.
Running auth crons if required...
Running enrol crons if required...
Starting activity modules
Processing module function assign_cron ...
... used 4 dbqueries
... used 0.040257930755615 seconds
done.
Processing module function chat_cron ...
... used 5 dbqueries
... used 0.0017631053924561 seconds
done.
Processing module function quiz_cron ...

  Looking for quiz overdue quiz attempts...
  Considered 0 attempts in 0 quizzes.
Starting quiz reports
Processing cron function for quiz_statistics...
... started 05:25:02. Current memory use 25.5MB.

  Cleaning up old quiz statistics cache records...done. (1 dbqueries, 0.01 seconds)
Finished quiz reports
... used 5 dbqueries
... used 0.042843103408813 seconds
done.
Processing module function workshop_cron ...
processing workshop subplugins ...
Starting workshop allocation methods
Processing cron function for workshopallocation_scheduled...
... started 05:25:02. Current memory use 26.5MB.
... no workshops awaiting scheduled allocation. done. (1 dbqueries, 0 seconds)
Finished workshop allocation methods
... used 6 dbqueries
... used 0.010648012161255 seconds
done.
Finished activity modules
Starting blocks
Finished blocks
Starting admin reports
Finished admin reports
Starting course reports
Finished course reports
Starting gradebook plugins
Finished gradebook plugins
Starting repository plugins
Processing cron function for repository_dropbox...
... started 05:25:02. Current memory use 27.7MB.
done. (1 dbqueries, 0 seconds)
Processing cron function for repository_filesystem...
... started 05:25:02. Current memory use 27.7MB.
done. (3 dbqueries, 0 seconds)
Finished repository plugins
... used 32 dbqueries
... used 0.14015603065491 seconds
Scheduled task complete: Legacy cron processing for plugins (core\task\legacy_plugin_cron_task)
Execute scheduled task: Background processing for gradebook (core\task\grade_cron_task)
... started 05:25:02. Current memory use 27.7MB.
... used 2 dbqueries
... used 0.00072598457336426 seconds
Scheduled task complete: Background processing for gradebook (core\task\grade_cron_task)
Execute scheduled task: Calculate regular completion data (core\task\completion_regular_task)
... started 05:25:02. Current memory use 27.7MB.
... used 6 dbqueries
... used 0.0052218437194824 seconds
Scheduled task complete: Calculate regular completion data (core\task\completion_regular_task)
Execute scheduled task: Background processing for portfolio plugins (core\task\portfolio_cron_task)
... started 05:25:02. Current memory use 27.9MB.
... used 0 dbqueries
... used 2.7894973754883E-5 seconds
Scheduled task complete: Background processing for portfolio plugins (core\task\portfolio_cron_task)
Execute scheduled task: Background processing for legacy cron in plagiarism plugins (core\task\plagiarism_cron_task)
... started 05:25:02. Current memory use 27.9MB.
... used 0 dbqueries
... used 3.1948089599609E-5 seconds
Scheduled task complete: Background processing for legacy cron in plagiarism plugins (core\task\plagiarism_cron_task)
Execute scheduled task: Send calendar notifications (core\task\calendar_cron_task)
... started 05:25:02. Current memory use 27.9MB.
... used 1 dbqueries
... used 0.0038540363311768 seconds
Scheduled task complete: Send calendar notifications (core\task\calendar_cron_task)
Execute scheduled task: Sync external blogs (core\task\blog_cron_task)
... started 05:25:02. Current memory use 28.4MB.
... used 2 dbqueries
... used 0.0031552314758301 seconds
Scheduled task complete: Sync external blogs (core\task\blog_cron_task)
Execute scheduled task: Background processing for question engine (core\task\question_cron_task)
... started 05:25:02. Current memory use 28.7MB.

  Cleaning up old question previews...done.

  Cleaning up old question statistics cache records...done.
... used 6 dbqueries
... used 0.0019950866699219 seconds
Scheduled task complete: Background processing for question engine (core\task\question_cron_task)
Execute scheduled task: Background processing for caches (core\task\cache_cron_task)
... started 05:25:02. Current memory use 28.7MB.
Cleaning up stale session data from cache stores.
... used 0 dbqueries
... used 0.00027108192443848 seconds
Scheduled task complete: Background processing for caches (core\task\cache_cron_task)
Execute scheduled task: Automated backups (core\task\automated_backup_task)
... started 05:25:02. Current memory use 28.7MB.
Checking automated backup status...INACTIVE
... used 0 dbqueries
... used 0.026298999786377 seconds
Scheduled task complete: Automated backups (core\task\automated_backup_task)
Execute scheduled task: Award badges (core\task\badges_cron_task)
... started 05:25:02. Current memory use 30.9MB.
Started reviewing available badges.
Badges were issued 0 time(s).
Sending scheduled badge notifications.
... used 2 dbqueries
... used 0.0034210681915283 seconds
Scheduled task complete: Award badges (core\task\badges_cron_task)
Execute scheduled task: Global search indexing (core\task\search_index_task)
... started 05:25:02. Current memory use 31.2MB.
... used 0 dbqueries
... used 0.0015499591827393 seconds
Scheduled task complete: Global search indexing (core\task\search_index_task)
Execute scheduled task: Complete learning plans which are due (core\task\complete_plans_task)
... started 05:25:02. Current memory use 31.3MB.
... used 1 dbqueries
... used 0.0076959133148193 seconds
Scheduled task complete: Complete learning plans which are due (core\task\complete_plans_task)
Execute scheduled task: Sync plans from learning plan template cohorts (core\task\sync_plans_from_template_cohorts_task)
... started 05:25:02. Current memory use 32.1MB.
... used 1 dbqueries
... used 0.0016739368438721 seconds
Scheduled task complete: Sync plans from learning plan template cohorts (core\task\sync_plans_from_template_cohorts_task)
Execute scheduled task: Refresh OAuth tokens for service accounts (core\oauth2\refresh_system_tokens_task)
... started 05:25:02. Current memory use 32.1MB.
... used 1 dbqueries
... used 0.0014421939849854 seconds
Scheduled task complete: Refresh OAuth tokens for service accounts (core\oauth2\refresh_system_tokens_task)
Execute scheduled task: Analytics cleanup (core\task\analytics_cleanup_task)
... started 05:25:02. Current memory use 32.2MB.
... used 8 dbqueries
... used 0.015262842178345 seconds
Scheduled task complete: Analytics cleanup (core\task\analytics_cleanup_task)
Execute scheduled task: Remove unused random questions (qtype_random\task\remove_unused_questions)
... started 05:25:02. Current memory use 33.5MB.
Cleaned up 0 unused random questions.
... used 1 dbqueries
... used 0.00026917457580566 seconds
Scheduled task complete: Remove unused random questions (qtype_random\task\remove_unused_questions)
Execute scheduled task: Forum mailings and maintenance jobs (mod_forum\task\cron_task)
... started 05:25:02. Current memory use 33.8MB.
Starting digest processing...
Cleaned old digest records
... used 6 dbqueries
... used 0.023691177368164 seconds
Scheduled task complete: Forum mailings and maintenance jobs (mod_forum\task\cron_task)
Execute scheduled task: Background processing for SCORM (mod_scorm\task\cron_task)
... started 05:25:02. Current memory use 35.8MB.
... used 0 dbqueries
... used 0.0071628093719482 seconds
Scheduled task complete: Background processing for SCORM (mod_scorm\task\cron_task)
Execute scheduled task: Cohort enrolment sync task (enrol_cohort\task\enrol_cohort_sync)
... started 05:25:02. Current memory use 36.4MB.
... used 7 dbqueries
... used 0.0061771869659424 seconds
Scheduled task complete: Cohort enrolment sync task (enrol_cohort\task\enrol_cohort_sync)
Execute scheduled task: Manual enrolment synchronise enrolments task (enrol_manual\task\sync_enrolments)
... started 05:25:02. Current memory use 36.8MB.
Verifying manual enrolment expiration...
...manual enrolment updates finished.
... used 0 dbqueries
... used 0.00013899803161621 seconds
Scheduled task complete: Manual enrolment synchronise enrolments task (enrol_manual\task\sync_enrolments)
Execute scheduled task: Manual enrolment send expiry notifications task (enrol_manual\task\send_expiry_notifications)
... started 05:25:02. Current memory use 36.8MB.
manual enrolment expiry notifications will be sent at Tuesday, 8 October 2019, 6:00 AM.
... used 0 dbqueries
... used 0.00085902214050293 seconds
Scheduled task complete: Manual enrolment send expiry notifications task (enrol_manual\task\send_expiry_notifications)
Execute scheduled task: Self enrolment synchronise enrolments task (enrol_self\task\sync_enrolments)
... started 05:25:02. Current memory use 36.9MB.
Verifying self-enrolments...
...user self-enrolment updates finished.
No expired enrol_self enrolments detected
... used 2 dbqueries
... used 0.00067496299743652 seconds
Scheduled task complete: Self enrolment synchronise enrolments task (enrol_self\task\sync_enrolments)
Execute scheduled task: Self enrolment send expiry notifications task (enrol_self\task\send_expiry_notifications)
... started 05:25:02. Current memory use 36.9MB.
self enrolment expiry notifications will be sent at Tuesday, 8 October 2019, 6:00 AM.
... used 0 dbqueries
... used 0.00013399124145508 seconds
Scheduled task complete: Self enrolment send expiry notifications task (enrol_self\task\send_expiry_notifications)
Execute scheduled task: Refresh RSS feeds task (block_rss_client\task\refreshfeeds)
... started 05:25:02. Current memory use 36.1MB.

0 feeds refreshed (took 0.00048400000000004 seconds)
... used 1 dbqueries
... used 0.0070188045501709 seconds
Scheduled task complete: Refresh RSS feeds task (block_rss_client\task\refreshfeeds)
Execute scheduled task: Sync cohort role assignments (tool_cohortroles\task\cohort_role_sync)
... started 05:25:02. Current memory use 37MB.
Sync cohort roles...
Added 0
Removed 0
... used 2 dbqueries
... used 0.0048091411590576 seconds
Scheduled task complete: Sync cohort role assignments (tool_cohortroles\task\cohort_role_sync)
Execute scheduled task: Incoming email pickup (tool_messageinbound\task\pickup_task)
... started 05:25:02. Current memory use 37.5MB.
Inbound Message not fully configured - exiting early.
... used 0 dbqueries
... used 0.0013279914855957 seconds
Scheduled task complete: Incoming email pickup (tool_messageinbound\task\pickup_task)
Execute scheduled task: Cleanup event monitor events (tool_monitor\task\clean_events)
... started 05:25:02. Current memory use 37.7MB.
... used 0 dbqueries
... used 0.00012683868408203 seconds
Scheduled task complete: Cleanup event monitor events (tool_monitor\task\clean_events)
Execute scheduled task: Cleanup course recycle bin (tool_recyclebin\task\cleanup_course_bin)
... started 05:25:02. Current memory use 37.7MB.
... used 1 dbqueries
... used 0.00084090232849121 seconds
Scheduled task complete: Cleanup course recycle bin (tool_recyclebin\task\cleanup_course_bin)
Execute scheduled task: Cleanup category recycle bin (tool_recyclebin\task\cleanup_category_bin)
... started 05:25:02. Current memory use 37.8MB.
... used 1 dbqueries
... used 0.0007939338684082 seconds
Scheduled task complete: Cleanup category recycle bin (tool_recyclebin\task\cleanup_category_bin)
Execute scheduled task: Prepare submissions for annotation (assignfeedback_editpdf\task\convert_submissions)
... started 05:25:02. Current memory use 37.8MB.
... used 1 dbqueries
... used 0.00016903877258301 seconds
Scheduled task complete: Prepare submissions for annotation (assignfeedback_editpdf\task\convert_submissions)
Cron script completed correctly
Cron completed at 05:25:02. Memory used 37.8MB.
Execution took 0.452572 seconds

**Comment by andrewchaosun** [comment]
Does is have any thing to do with this? Set a path in the file /var/www/crm/cron/cron.sh to PHP: export USE_PHP=/usr/local/php71/bin/php [here it is also required to pay attention to the file, because it can be located differently on each server and also keep an eye on a path to PHP that is different for various servers. An administrator can provide information about this path or it can be checked in phpinfo]. 
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

**Comment by vovpff** [comment]
What OS you are using? For ubuntu 18.04 standard path to php just `phpX.X`

**Comment by andrewchaosun** [comment]
linux

**Comment by vovpff** [comment]
correct path depends from linux discr.

**Comment by andrewchaosun** [comment]
I am using a shared bluehost server.  If I am to ask the server provider, what question should I ask?

**Comment by andrewchaosun** [comment]
what is the file/folder that i should be looking for in the server? I can search it and reset the path.

**Comment by vovpff** [comment]
At first try `php -v` at terminal

**Comment by andrewchaosun** [comment]
my php version is : PHP 7.2.7

**Comment by andrewchaosun** [comment]
this is the phpinfo which i requested from the server provider. 
http://erp.overseaser.com/phpinfo.php

**Comment by andrewchaosun** [comment]
CHANGED THE FILE TO THIS:

export CRM_ROOT_DIR=`dirname "$0"`/..
export USE_PHP=php
#export USE_PHP=/usr/local/php53/bin/php
#export USE_PHP=/usr/local/php56/bin/php56
export USE_PHP=/usr/local/php71/bin/php


cd $CRM_ROOT_DIR
# TO RUN ALL CORN JOBS
$USE_PHP -f cron.php

**Comment by andrewchaosun** [comment]
/home/buukcguc/public_html/erp/cron/cron.sh: line 20: /usr/local/php71/bin/php: No such file or directory GUESS, THAT I HAVE NOT FOUND THE RIGHT PATH.

**Comment by andrewchaosun** [comment]
IT WORKS NOW, BROTHERS. THANK YOU ALL.
