### ISSUE TITLE
Error Widgets in 1.2.0 version

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#117]
Button Inactive
![error wigets](https://cloud.githubusercontent.com/assets/1402355/5824774/61f7cb8c-a108-11e4-9418-23e10b732e35.PNG)

Even when you create a widget, they do not appear on the main

![error wigets2](https://cloud.githubusercontent.com/assets/1402355/5824797/8329795e-a108-11e4-84ef-7c34555eb4e6.PNG)

**Comment by bpabiszczak** [comment]
You set wrong role (organisation).
