### ISSUE TITLE
Widget Configuration Bug

### ISSUE THREAD

**Issue by akpriest14** [YetiForceCompany/YetiForceCRM#11705]
When trying to set up widgets for the home page I am unable to do so. I can not physically add any to any page because it will not make the data entry

| YetiForce	3.1		|
| Web server (name and version)|		Ubunutu 16.04
| PHP  |						7.2		
| Browser (name and version)  | 	Chrome	
![yeti](https://user-images.githubusercontent.com/55858088/66511929-7e39e800-ea9d-11e9-85e3-38908077e4d1.gif)

**Comment by bpabiszczak** [comment]
3.1? Upgrade the system.
