### ISSUE TITLE
[Question] Automatically assign related module record to the owner

### ISSUE THREAD

**Issue by Pietrox** [YetiForceCompany/YetiForceCRM#11702]
I was wondering, is there any easy way to automate this process?
The goal is to for example assign all transactions to a user if source module record is also assigned to him eg. Accounts.

I tried mapping, but it seems i'm missing a trigger?
Would be glad for any tips or even a different way to acheive the logic.

**Comment by joelbcampos** [comment]
If you had an example capture, I could help you.
Actually I think what you want is that when you select one field it automatically updates another.

You must do that from the route I leave you.

/crm/user_privileges/moduleHierarchy.php

I leave you an example of how it should look.

'Leads' => [
			'comercial' => ['Accounts' => ['assigned_user_id' => ['assigned_user_id']]

**Comment by Pietrox** [comment]
Thanks I'll try it out this week.
