### ISSUE TITLE
Emails to send". Status is waiting to be sent

### ISSUE THREAD

**Issue by Abhilash989** [YetiForceCompany/YetiForceCRM#11700]
Email is not going automatically. It always shows waiting t be sent .

**Comment by mariuszkrzaczkowski** [comment]
does cron work?
check
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/Components/ConfigTemplates.php#L141-L143

**Comment by Abhilash989** [comment]
I have created a workflow. whenever status changed. mail should go.
Mail is getting created but but not going. I can see the mail in Mail tools/ Emails to send. 
it is asking me to send manual. if I click the button then it i working but I want the same without clicking on the button.

![yetiforce_mail](https://user-images.githubusercontent.com/17095321/66455268-cfd77800-ea87-11e9-8ee9-0e9448084777.png)

**Comment by vovpff** [comment]
CRON should be turned **on**
Here https://gitdeveloper.yetiforce.com/index.php?module=CronTasks&parent=Settings&view=List&block=15&fieldid=26 task
![image](https://user-images.githubusercontent.com/8545791/66455988-fcce5f80-ea74-11e9-81fb-36d0e6146df5.png)
should be active.

**Comment by Abhilash989** [comment]
Yes CRON is active but still this problem is coming

**Comment by Abhilash989** [comment]
My CRON is not working.  Lat scan is empty.

![CRON](https://user-images.githubusercontent.com/17095321/66458171-b9351f00-ea8f-11e9-9c8b-48214f500f86.png)

**Comment by mariuszkrzaczkowski** [comment]
so your cron doesn't work

**Comment by Abhilash989** [comment]
What is the solution Sir?

**Comment by mariuszkrzaczkowski** [comment]
start here it has already been discussed many times
https://github.com/YetiForceCompany/YetiForceCRM/issues?q=is%3Aissue+cron+is%3Aclosed
