### ISSUE TITLE
How to send notification as a mail to the user?

### ISSUE THREAD

**Issue by Abhilash989** [YetiForceCompany/YetiForceCRM#11709]
I want to send mail the notification as a mail to the assigned user.
Example:  UserA has assigned a sales enquiry to UserB. Then UserB should get a mail.

**Comment by guide5232** [comment]
1. Specify when to execute this workflow: 
a. Creating record
b. Modifying record


2. 
![condition](https://user-images.githubusercontent.com/47585969/66547231-802da500-eb8a-11e9-930d-ea8dfa38973d.JPG)

3. 
![email](https://user-images.githubusercontent.com/47585969/66547216-79069700-eb8a-11e9-8f12-82cef765c20a.JPG)

4. 
![email temp2](https://user-images.githubusercontent.com/47585969/66547809-c5060b80-eb8b-11e9-9722-c676222af852.JPG)

**Comment by Abhilash989** [comment]
Thanks
