### ISSUE TITLE
[Question] Insert into Single Orders inventory

### ISSUE THREAD

**Issue by Lynxu** [YetiForceCompany/YetiForceCRM#11718]
I need some help regarding the insert into single orders inventory via webservice.
I created a new single order and after that i need to fill up the inventory with specific data.

I want to insert data in this table "**u_yf_ssingleorders_inventory**" via **webservice** is it posible in any way?

I wanted to see the **hierarchy** of the module but it needs specific permissions and i cant figure it out where to find those. After i get the request to get the hierarchy of the **SSingleOrders** module i get the following response "**REST Error (405): Not available for this type of user Array ()**"

**Comment by bpabiszczak** [comment]
We do not provide programming advice for free. Check the documentation [https://doc.yetiforce.com/] and examples in the system.
