### ISSUE TITLE
[bug] OSSMail - Failed to load ical_attachments plugin

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#11719]
Hi,

I'm using YF 5.2 on a dedicated VPS.

I've noticed the following error on my YF system :
`PHP Error: Failed to load plugin file /var/www/html/yfcrm/public_html/modules/OSSMail/roundcube/plugins/ical_attachments/ical_attachments.php`

I can't find anything about this plugin which is referenced in /config/Modules/OSSMail.php :

`	/** List of plugins */
	public static $plugins = [
		'identity_smtp',
		'ical_attachments',
		'yetiforce',
		'thunderbird_labels',
		'zipdownload',
		'archive',
		'authres_status',
	];`

Not used anymore ? Do I simply have to remove it from the list of loaded plugins ?

**Comment by mariuszkrzaczkowski** [comment]
is no longer used, functionality added to our plugin
