### ISSUE TITLE
[pl][pytanie] Funkcje Vtiger

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11710]
Witam,

Czy jest możliwość użycia innych funkcji vtiger po za:
![image](https://user-images.githubusercontent.com/21024857/66547303-353a7000-eb3f-11e9-86e9-771e1de46415.png)

Chciałem liczyć różnice między dniami roboczymi, pomijając weekendy, funkcją:
[time_diffweekdays(a,b)](https://www.vtiger.com/docs/expressions#/time_diffdays_a_b_)

**Comment by bpabiszczak** [comment]
Czy jest możliwość użycia innych funkcji oprócz wbudowanych? Tak, to open source, można dodać sobie dowolne inne, lub zlecić nam i my je dodamy :]
