### ISSUE TITLE
[Question] How to calculate time in workflows?

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#11711]
Hello all ! 

   I want to create a workflow that calculates time (for employees shifts calculations)

   Field A = the time when employee has come to work
   Field B = the time when employee has finished work
   Field C = total working hours 
  
    Can someone explain how can i do this ? In workflow, not in the built in module ? 
    I need to make more time calculations after, but i need a starting point.
    
    Thank you!

**Comment by apcloic** [comment]
Example : #10736

**Comment by liviubbo** [comment]
@apcloic - thanks for the solution but, this one is reffering to days and i need to calculate hours. Also, it doesnt explain what type of field must be the result field. In this example FIELD C.

**Comment by vovpff** [comment]
just multiply result to 24

**Comment by liviubbo** [comment]
Thank you very much ! I just want to ask what type of field should the result field be ? Ex : text field, time field ?

**Comment by vovpff** [comment]
I think text will work

**Comment by liviubbo** [comment]
Thank you !
