### ISSUE TITLE
I would like to be able to insert a pdf instead of an image.

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#11723]
I would like to be able to insert a pdf instead of an image. It's possible?

![Snap_2019 10 11_15h30m24s_001_](https://user-images.githubusercontent.com/29610537/66655788-030f3800-ec3d-11e9-9df7-623d6991339d.jpg)

**Comment by mariuszkrzaczkowski** [comment]
No

**Comment by joelbcampos** [comment]
Thank you.
So how can I add the field to attach documentation in another module.

![Snap_2019 10 11_17h14m31s_001_](https://user-images.githubusercontent.com/29610537/66663360-dfeb8500-ec4a-11e9-8a54-d67169e650b7.jpg)

**Comment by Maxpeg** [comment]
You can add relations for your module:
![image](https://user-images.githubusercontent.com/54612661/66691930-81ff8180-eccc-11e9-988a-a2e74ed2587b.png)
![image](https://user-images.githubusercontent.com/54612661/66691945-9c395f80-eccc-11e9-9adb-2fa1e230e1ce.png)

Then you will have a tab, and can add files there
![image](https://user-images.githubusercontent.com/54612661/66691906-62685900-eccc-11e9-8359-752bb500b1d0.png)
