### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by aguianacional** [YetiForceCompany/YetiForceCRM#11728]
I need the order-order PDF to pull in the company address information (delivery location) as well as the company logo.

Another question, how do I activate and use the CRM module (is there any YouTube playlist for me to learn more about?)

**Comment by z0lo13** [comment]
@aguianacional no youtube, Search in issues.
You would need to use variables from Company Details Tab when creating a template.
![изображение](https://user-images.githubusercontent.com/23143958/66717956-64a1e480-edac-11e9-8876-66f9bf4797a5.png)

**Comment by aguianacional** [comment]
When I click to copy it advances and saves the template. Is there any documentation where I find all these parameters?

**Comment by z0lo13** [comment]
@aguianacional behaviour described seem to be a bug.

Copy them from gitdeveloper or gitstable.
