### ISSUE TITLE
How to display assigned user  in "first name last name"  format?

### ISSUE THREAD

**Issue by Abhilash989** [YetiForceCompany/YetiForceCRM#11722]
I am sending mail by using **Dear $(record : assigned_user_id)$**.
But it is displaying **last name first name** 
I want first name last name format.
How can I do this?

**Comment by vovpff** [comment]
Let's use separate variables for first name and last name

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/73950034-8c88fb00-48fb-11ea-8b0c-5a46310fb6c6.png)
