### ISSUE TITLE
[Security] 

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#11737]
Hi, I received this message in my email. How do I fix it

**Encryption mechanism**
No encryption causes that sensitive data such as passwords to mailboxes and access keys are stored in a public form in the database.

LBL_LIBRARY_PDF
Detected missing library. Some features were disabled. In order to enable them please download the library. If the CRM has no Internet connection, you can download the files and copy them to folder.

**Comment by mariuszkrzaczkowski** [comment]
- Enable the encryption mechanism https://gitdeveloper.yetiforce.com/index.php?module=Password&parent=Settings&view=Encryption&block=7&fieldid=109

- download the library https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List
