### ISSUE TITLE
"Character limit exceeded"

### ISSUE THREAD

**Issue by m-ally-m** [YetiForceCompany/YetiForceCRM#11734]
when creating new product and I add any value for Product's weight (like 20, 200, 2000, or 20000) and click save, I get "Character limit exceeded. Field name: weight, Module: Products, Value: 20000" used 20000 as an example here. any thought/advise?

![image](https://user-images.githubusercontent.com/56503098/66714879-83a47480-edb4-11e9-88a6-22a1452ecce7.png)

**Comment by m-ally-m** [comment]
Any thought on this folks? it's a brand new installation 5.2. with no changes to the code/application. Also have confirmed with my host's technical support, in terms of server config. any thought/hint appreciated.

**Comment by bpabiszczak** [comment]
The field value is not allowed. Correct the field type in the database.
