### ISSUE TITLE
Records list - change columns

### ISSUE THREAD

**Issue by m-ally-m** [YetiForceCompany/YetiForceCRM#11731]
hey,
new to Yetiforce. Any way to change the columns displayed in records list view? for example, under products list, is it possible to add Weight field, and remove unwanted ones?

Thanks.

**Comment by vovpff** [comment]
Go to admin panel and look for filters parameters

**Comment by m-ally-m** [comment]
> Go to admin panel and look for filters parameters

Thanks for the tip, managed to create the view. but also noticed that when I add any value for Product's weight (like 20, 200, 2000, or 20000) and click save, I get "Character limit exceeded. Field name: weight, Module: Products, Value: 20000". any thought/advise?

![image](https://user-images.githubusercontent.com/56503098/66714879-83a47480-edb4-11e9-88a6-22a1452ecce7.png)

**Comment by vovpff** [comment]
No ideas...

**Comment by m-ally-m** [comment]
> No ideas...

thanks.
