### ISSUE TITLE
[bug] UPDATE TO 5.2 FAILED. Failed Module does not contain default language (en_us).

### ISSUE THREAD

**Issue by andrewchaosun** [YetiForceCompany/YetiForceCRM#11730]
I download the V5.2, but failed to install it. 

It says: 

Failed
Module does not contain default language (en_us).

Please instruct me about the next step. thanks.

**Comment by mariuszkrzaczkowski** [comment]
try this 5.1.0_to_5.2.0_v4.zip
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0
