### ISSUE TITLE
[Question] How do I convert a Lead to existing account? 

### ISSUE THREAD

**Issue by OldMan-Running** [YetiForceCompany/YetiForceCRM#11747]
The first screen shot shows the option is selected to convert a Lead to an Existing Account.

In the 2nd screen I never get the name of an existing account to appear.
A new account is always generated.

<img width="1197" alt="Screenshot 2019-10-14 at 21 09 56" src="https://user-images.githubusercontent.com/56050807/66779867-3d8c0580-eec7-11e9-92ab-b34b95086077.png">
<img width="605" alt="Screenshot 2019-10-14 at 21 10 50" src="https://user-images.githubusercontent.com/56050807/66779877-411f8c80-eec7-11e9-9c84-f5a9d1312e1e.png">

**Comment by bpabiszczak** [comment]
> How do I convert a Lead to an existing account?

You can not

But you can convert to a new customer and use the duplicate merging tool.
