### ISSUE TITLE
[Question] Login only from one (or two) IP Address

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#11741]
Hy all ! 

   I have searched the entire GIT for this but cant find anyone mentioning it. 
   Is it possible to allow login only from 1,2 IP addresses and any other IP address to be blocked ? 

  Thank you !

**Comment by davide-alghi** [comment]
Hi,
you can restrict access to your installation via .htaccess

```
order deny,allow
deny from all
allow from <your ip>
```

**Comment by liviubbo** [comment]
Thank you very much !
