### ISSUE TITLE
[Question/Issue] How / Where can I add new folders for storing documents?

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1174]
In 1.0.x there was a button '+ Add Folder' to create a new folder in the Documents module.
In 2.0.x I am missing that button.

How / Where can I add new folders for storing documents?

**Comment by waw555** [comment]
https://test.yetiforce.com/index.php?module=TreesManager&parent=Settings&view=List&block=2&fieldid=70

**Comment by bpabiszczak** [comment]
Here: https://test.yetiforce.com/index.php?module=TreesManager&parent=Settings&view=List&block=2&fieldid=70
