### ISSUE TITLE
Reinstall Yeti

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#11754]

**Comment by hobejeans** [comment]
Hi,
after updating to 5.2 I have been facing many issues... Can install a new instance of YetiForce & import all the data including modified modules & pick list? I have created custom modules which I know how to import & export but the stock modules that came with yetiforce are a bit trickier. 
1. What are the steps to export stock modules?
2. What are the steps to save or export picklist(s)?

Thanks

**Comment by vovpff** [comment]
1 better way to import/export trough xml. I don't know about actual versions but i'm fully migrated from vtiger to yeti using csv to xml conversation on ver 3.x.
2  not sure what this will work. Add new picklist field to your fresh system with the same name. Export picklist table from old broken system database to SQL. Import SQL to new batabase. Profit!

**Comment by hobejeans** [comment]
thanks. I will try this method & let you know if it worked for me
