### ISSUE TITLE
[bug] test.yetiforce.vom/portal  not works with test.yetiforce.vom - regarding invoices and quotes

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1175]
Records not shows as suppose to.
How does contacts can see assigned to them invoices and quotes?
In my situation we have large organizations and people from various departments don't need to see invoices assigned to other departments. They actually should not see it. 5 of our large customers have similar situation.  Will this be working as suppose to work? Correctly working portal is a unbreakable part of CRM

**Comment by KatarzynaUlichnowska** [comment]
Fixes have been made in the latest version of the system; here you can see history:
https://github.com/YetiForceCompany/YetiForceCRM/commits/master/api/yetiportal.php 
We are going to develop the functionality of our Customer Portal within two weeks time, it will be possible to decide about levels of access directly on Contact, e.g.
• It can see only its records
• It can see records assigned to it and a company
• It can see records assigned to it, a company and the others
• It can see records within its company and subordinated companies
• It can see records within the entire hierarchy
There will be a button that will allow to switch between companies to which a contact has an access.
