### ISSUE TITLE
[PL][Pytanie] Błąd przy próbie logowania

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#11766]
Witam,

Jak mogę odblokować IP by użytkownik mógł się zalogować?

Chodzi mi o plik konfiguracyjny, nie .htaccess bo użytkownik może normalnie wpisać login i hasło po czym wyskakuje komunikat że jego IP jest zablokowane.

![image](https://user-images.githubusercontent.com/21024857/66991898-2ddc0f00-f0c9-11e9-9013-15eed028111a.png)

**Comment by mariuszkrzaczkowski** [comment]
logi
