### ISSUE TITLE
[bug] Unable to import the CSV file

### ISSUE THREAD

**Issue by KrishnaPB** [YetiForceCompany/YetiForceCRM#11762]
After I updated 4th patch in yatiforce I am unable to import the files. I am getting below error:

The imported file is in a different encoding than it was selected (%s)

![yati](https://user-images.githubusercontent.com/11535185/66978893-3fbdb200-f0c9-11e9-842b-c3b72516007d.png)

I am using ubuntu latest version 18.04
PHP Version 7.1.32

**Comment by maeglin4** [comment]
did you tried different "Character  encoding" ?

**Comment by vovpff** [comment]
csv from ms excel has not utf-8 encoding. Before import you need to change encoding by some text editor like notepad++

**Comment by garryatbrighton** [comment]
This bug still exists. Mentioned is a work around. Expected would be better compatibility. Libre office Calc compatibility would be good start. Anyway i checked and in latest stable version even work around not working

**Comment by mariuszkrzaczkowski** [comment]
import would be handy to expand and improve.
we are waiting for someone who will order it
https://yetiforce.com/en/marketplace/development-support

**Comment by mariuszkrzaczkowski** [comment]
many new formats could be added
