### ISSUE TITLE
Can't login after fresh install

### ISSUE THREAD

**Issue by glitchcowboy** [YetiForceCompany/YetiForceCRM#11768]
I've installed successfully on an Azure Ubuntu server, but the customer would like this on a different VPS.  I'm RHEL certified on 7, so I chose CentOS7 which I assume is a non-issue.  I've done the install multiple times and I get through with almost all green lights in the pre-checks.  If I remember correctly the only red lights are that php doesn't disable popen.
I get a login and username from the install program and then those creds don't work.  "Invalid Username or Password". 
Chrome gives the same result.
Apache logs look clean

I can see the failed attempts in vtiger_loginhistory 
`MariaDB [yetiforce]> select * from vtiger_loginhistory
    -> ;
+----------+------------+---------------+-------------+---------------------+--------------+-----------+
| login_id | user_name  | user_ip       | logout_time | login_time          | status       | browser   |
+----------+------------+---------------+-------------+---------------------+--------------+-----------+
|        1 | adminxx | 174.20.1x.x | NULL        | 2019-10-11 06:19:18 | Failed login | Safari 13 |
|        2 | adminxx | 174.20.1x.x | NULL        | 2019-10-11 06:20:33 | Failed login | Safari 13 |
|        3 | adminxx | 63.x.x.x   | NULL        | 2019-10-11 07:02:07 | Failed login | Safari 13 |
|        4 | adminxx | 63.x.x.x   | NULL        | 2019-10-11 07:26:42 | Failed login | Safari 13 |
|        5 | adminxx | 63.x.x.x   | NULL        | 2019-10-11 07:28:52 | Failed login | Safari 13 |
|        6 | adminxx | 63.x.x.x   | NULL        | 2019-10-11 07:41:46 | Failed login | Safari 13 |
|        7 | adminxx | 63.x.x.x   | NULL        | 2019-10-11 07:45:42 | Failed login | Safari 13 |
|        8 | adminxx | 63.x.x.x   | NULL        | 2019-10-11 07:51:09 | Failed login | Safari 13 |
|        9 | adminxx | 174.20.1x.x | NULL        | 2019-10-17 05:23:39 | Failed login | Safari 13 |
+----------+------------+---------------+-------------+---------------------+--------------+-----------+`

`<VirtualHost 199.x.x.x:443>
    DocumentRoot "/var/www/crm.me/public_html"
    ServerName crm.me

    # Other directives here
    SSLCertificateFile /etc/letsencrypt/live/crm.me/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/crm.me/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateChainFile /etc/letsencrypt/live/crm.me/chain.pem

    <Directory /var/www/crm.me/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    <Directory  /var/www/crm.me/public_html/>
        Options +Indexes +Includes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
   </Directory>
    </VirtualHost>
</IfModule>`
Any help you can give would be appreciated

**Comment by glitchcowboy** [comment]
looks like this worked: https://discussions.vtiger.com/discussion/181860/how-to-reset-the-admin-user-name-and-password-from-phpmyadmin

was 'admin' the password all along?  why would the installer tell me it's something else?

**Comment by vovpff** [comment]
@glitchcowboy this happens because your installation is fault

**Comment by Maxpeg** [comment]
I had the same, reinstall helped

**Comment by glitchcowboy** [comment]
But I have reinstalled 4 times

**Comment by mariuszkrzaczkowski** [comment]
check the logs after installing the system, you have a problem with the server configuration

**Comment by glitchcowboy** [comment]
Ok, where would I find installation logs?

**Comment by vovpff** [comment]
/cache/logs

**Comment by glitchcowboy** [comment]
My cache/logs directory has 2 files: 
total 2240
-rw-r--r-- 1 apache apache      71 Sep  7 01:51 index.html
-rw-r--r-- 1 apache apache 2287679 Oct 18 05:40 viewer-debug.log


Index.html is an almost empty html file and viewer-debug.log is a giant single-line file with stuff like this in it
.php, TYPE: GET\nURI: /install/Install.php, TYPE: GET\nURI: /, TYPE: GET\nVIEW: modules/Users/Header.tpl > modules/Vtiger/Header.tpl, FOUND: 1\nDATA: APPTITLE, TYPE: literal\nDATA: YETIFORCE_VERSION, TYPE: literal\nDATA: MODULE_NAME, TYPE: literal\nDATA: PAGETITLE, TYPE: literal\nDATA: BREADCRUMB_TITLE, TYPE: literal\nDATA: HEADER_SCRIPTS, TYPE: array\nDATA: STYLES, TYPE: array\nDATA: SKIN_PATH, TYPE: literal\nDATA: LAYOUT_PATH, TYPE: literal\nDATA: LANGUAGE_STRINGS, TYPE: array\nDATA: LANGUAGE, TYPE: literal\nDATA: HTMLLANG, TYPE: literal\nDATA: SHOW_BODY_HEADER, TYPE: literal\nDATA: SHOW_BREAD_CRUMBS, TYPE: literal\nDATA: USER_MODEL, TYPE: Users_Record_Model\nDATA: CURRENT_USER, TYPE: App\User\nDATA: MODULE, TYPE: literal\nDATA: VIEW, TYPE: literal\nDATA: PARENT_MODULE, TYPE: literal\nDATA: QUALIFIED_MODULE, TYPE: literal\nURI: /install/Install.php, TYPE: GET\nVIEW: modules/Vtiger/ExceptionError.tpl, FOUND: 1\nDATA: MESSAGE, TYPE: literal\nDATA: MESSAGE_EXPANDED, TYPE: literal\nDATA: HEADER_MESSAGE, TYPE: literal\nURI: /install/Install.php, TYPE: GET\nURI: /install/Install.php, TYPE: GET\nURI: /install/Install.php, TYPE: GET\nURI: /install/Install.php, TYPE: GET\nURI: /install/Install.php, TYPE: GET\nURI: /install/Install.php, TYPE: GET\n[2

**Comment by rskrzypczak** [comment]
enable debugging([link](https://www.google.com/search?q=yetiforce+debugging&oq=yetiforce+debugging)) and see what's wrong.
