### ISSUE TITLE
[Question] Yeti Installation fails

### ISSUE THREAD

**Issue by invensAB** [YetiForceCompany/YetiForceCRM#11765]
Hi,

Im trying to install Yeti CRM on a server my webhosting company supplying. 
Below are the requirements getting red, when everything is entered it start installing and after a while i get a red text saying "Installation unsuccessfull". Is there any log or similar that can tell me more?
Based on the below i think i should be fine since they are optional, except database version where i have 5.5, i read somewhere in Yeti documents that it should be alright with that?
below are MYSQL and Php settings

![image](https://user-images.githubusercontent.com/53469997/66988362-b4d9b900-f0c2-11e9-9990-dae99a3090eb.png)
![image](https://user-images.githubusercontent.com/53469997/66988400-befbb780-f0c2-11e9-93da-bc319476515e.png)
![image](https://user-images.githubusercontent.com/53469997/66988420-c4f19880-f0c2-11e9-9d3d-0a9009e305f6.png)
![image](https://user-images.githubusercontent.com/53469997/66988429-c8851f80-f0c2-11e9-8832-9a8ad844552b.png)
![image](https://user-images.githubusercontent.com/53469997/66988439-ce7b0080-f0c2-11e9-839e-c4c610506982.png)
![image](https://user-images.githubusercontent.com/53469997/66988448-d20e8780-f0c2-11e9-8193-59d6e9ace43d.png)

Thanks

**Comment by rskrzypczak** [comment]
> database version where i have 5.5, i read somewhere in Yeti documents that it should be alright with that?

5.5. is too low.
[Web server requirements](https://www.google.com/search?q=yetiforce+web+server+requirements&oq=yetiforce+web+server+requirements)
