### ISSUE TITLE
Reservation without contacts

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#1177]
reservations can not be related to contacts what obviously is nonsence. 
I think guys you should not use name Yetiforce CRM as it is not anymore.
Considering step out if this will not be changed to normal universal state.

**Comment by diderich** [comment]
If you need a contact field with a reservation, then simply add an 1:M field relating to the module 'Contact'. And disable the 'Company' field, if you don't want this one.
If you don't like the system, simply don't use it, but please avoid blaming YetiForce for having a different view than yours of the processes underlying a CRM system.

**Comment by reeid** [comment]
When we start using YF the financial and marketing process was different than now. This is major changes which are not in line with good practice and respect to community. I was holding this comment until I found many difficulties related to mentioned changes. 
I would also highlight that it is not ONLY my point of view. Many devs who watching this project are extremely disappointed. Another story is that introduced/mentioned process  is not in line with generally accepted/approved and deployed in real world business processes called CRM.
It is not big problem as we can adjust everything to point is that such a way discouraging new/existing YF community therefore chance that project will have many supporters are limited. 
I guess you didn't considered above before sending me to layout editor? The game is about harmony - here is a problem with it.

**Comment by waran70** [comment]
diderich, it not about reservation module only - which I personally dont need too much, it is about YF way of understanding importance of Contacts. CRM should threat Organization and Contacts in pretty same way as "Customer" means incorporated entity OR private person. If not than we should call it somehow different than CRM as it running away from widely understood customers relationship management process. All other improvements are brilliant and impressive but it should be more flexible from beginning not limited. It harms project and Yetiforce company too.
