### ISSUE TITLE
Installation on virtualmin server [Question] 

### ISSUE THREAD

**Issue by cosmibota** [YetiForceCompany/YetiForceCRM#11774]
Hello! 
I'm trying to install YF 5.2 on a Virtualmin server but i get this screen instead of normal installation page.
![image](https://user-images.githubusercontent.com/4603363/67127133-641caa00-f201-11e9-80d2-925cdae2f344.png)

Any recommendations?

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/web-server-requirements

**Comment by mariuszkrzaczkowski** [comment]
server configuration problem, check system requirements
