### ISSUE TITLE
[Question] Rest API, how to setup and use?

### ISSUE THREAD

**Issue by Sasamous** [YetiForceCompany/YetiForceCRM#11770]
### Description
Hello, I can't find anywhere a documentation that say how to setup and use API, I'm about to create a connector between this CRM and an existing ERP system, but I don't know where to start from YetiForce.

I found just [this partial documentation](https://doc.yetiforce.com/api/) in other tickets, but isn't enough explicit.

Someone know a place where to find a documentation or can suggest me how to use YetiForce API?

Thank you in advance. 😄

- [x] Understood way
- [x] Got slightly enough documentation
- [x] Got examples
- [x] Activated webservices by php
- [ ] Solved all problems
- [ ] In production! 😃

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST

**Comment by Sasamous** [comment]
> https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST

Thank you, this is very useful!
I have just some questions to ask.

1. I undestood I must create a WebService Application from YetiForce, in the field "URL" what I have to put?

2. "$host = 'https://gitdeveloper.yetiforce.com/';" must be replace with my standard address? e.g. "https//10.0.0.XX/" (local address while in develop)

3. "$baseurl;" where forward? 

4. In the example "https://gitdeveloper.yetiforce.com/webservice/Users/Login", the word "webservice" must be replaced with the name of my application? e.g. "https://10.0.0.XX/YetiConnector/User/Login? I tried to ping links like this but I had only 404 errors.


Thank you in advance 😄

**Comment by javjim** [comment]
How to set up API:

First you need to create a web service application
Integration -> Web Service application and Add key

URL is just for you to know where are you accessing from, it does not matter.
name and password is what you will use as basic auth as username and password.
![image](https://user-images.githubusercontent.com/30011667/67083589-a63de100-f158-11e9-8144-f98e0d334bc2.png)

then create a webservice user
the user and password you create there you have to add it in the body as this
![image](https://user-images.githubusercontent.com/30011667/67083569-9cb47900-f158-11e9-9db0-89276d251794.png)

and lastly copy the token 
![image](https://user-images.githubusercontent.com/30011667/67083773-046ac400-f159-11e9-8233-f24a60615843.png)

in the webservice application with the copy button next to the edit one
and add it like this
![image](https://user-images.githubusercontent.com/30011667/67083687-d5545280-f158-11e9-9364-3e023ee50249.png)





tadaaaaa

**Comment by mariuszkrzaczkowski** [comment]
Look at this:
https://learning.getpostman.com/docs/postman/collections/data_formats/#importing-openapi

OpenAPI file:
https://gitdeveloper.yetiforce.com/api/Portal.json

**Comment by Sasamous** [comment]
Thank you @javjim but doesn't work 😞 

![image](https://user-images.githubusercontent.com/40520020/67085081-7ca7a880-f19e-11e9-9efb-3221f8f575dc.png)

**Comment by javjim** [comment]
Yep, looks like after this, you need to first use Users/Login, and it will give you back a Token, that you need to add as a header with x-token:value and then you should be able to do stuff

**Comment by Sasamous** [comment]
> invalid URL
> CRM_URL/webservice/Users/Login

I did 2 attempts

![image](https://user-images.githubusercontent.com/40520020/67086266-a661cf00-f1a0-11e9-97d9-df2c7a9d6548.png)

![image](https://user-images.githubusercontent.com/40520020/67086291-b7124500-f1a0-11e9-946b-4bd874cfdfeb.png)

**Comment by javjim** [comment]
show me your yetiforce web app and web users..

**Comment by Sasamous** [comment]
> show me your yetiforce web app and web users..

![image](https://user-images.githubusercontent.com/40520020/67086449-0ce6ed00-f1a1-11e9-8799-96b5a7dfc027.png)

![image](https://user-images.githubusercontent.com/40520020/67086563-55060f80-f1a1-11e9-8371-e0ba685438f4.png)

**Comment by javjim** [comment]
try with https://URL/webservice.php?module=Users&action=Login

**Comment by Sasamous** [comment]
> try with https://URL/webservice.php?module=Users&action=Login

This return something
![image](https://user-images.githubusercontent.com/40520020/67087199-baa6cb80-f1a2-11e9-8d44-80f1a8685fb7.png)

The same result is returned also with "https://URL/webservice.php", which webservice should be activated? In webapplication it is active

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/Api.txt#L20-L21

**Comment by javjim** [comment]
you need to activate it in config/Api.php

**Comment by Sasamous** [comment]
> https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/Api.txt#L20-L21

There as enabled only dav, I just changed and now it answer "Wrong credentials", I tried with my YetiForce login credentials and with WebService User credentials but same situation.

![image](https://user-images.githubusercontent.com/40520020/67088572-c1830d80-f1a5-11e9-94bc-278983849443.png)

![image](https://user-images.githubusercontent.com/40520020/67088596-d3fd4700-f1a5-11e9-9a8d-a28257df15d6.png)

![image](https://user-images.githubusercontent.com/40520020/67088603-dc558200-f1a5-11e9-9b39-c2c8a0bdbc67.png)

**Comment by Sasamous** [comment]
Ok, credentials was userName: WebService Application Name and password: WebService Application Password, now the problem is "Internal Server Error":

![image](https://user-images.githubusercontent.com/40520020/67198727-d5c24700-f3ff-11e9-8b39-524863833f76.png)

**Comment by CesareD** [comment]
I'm following the issue.
I got the same problem _Internal Server Error_ when trying to execute login call

**Comment by javjim** [comment]
show the body tab

**Comment by Sasamous** [comment]
> show the body tab

This is the body tab
![image](https://user-images.githubusercontent.com/40520020/67265247-8f2b2600-f4ad-11e9-9e4b-bcc9157c5415.png)

**Comment by javjim** [comment]
change to form-data instead of x-www-formurlencoded

**Comment by Sasamous** [comment]
![image](https://user-images.githubusercontent.com/40520020/67265771-dc5bc780-f4ae-11e9-8eb3-4788dafab760.png)

![image](https://user-images.githubusercontent.com/40520020/67265805-f1d0f180-f4ae-11e9-8574-29172e645e15.png)

**Comment by javjim** [comment]
sorry, don't know what to tell you, verify all the steps, that is how I have it and it works properly, did you use the test and test123 username and password too? or you are just copying mine?

**Comment by Sasamous** [comment]
I used test and test123 in my users.

I understood how it works, I tried call with the Demo server, the problem is, how can I set my YetiForce installation to answer as Demo server? I installed YetiForce correctly, following all steps and configuring my server as YetiForce requirement page ask. Maybe I have to activate something else?

**Comment by mariuszkrzaczkowski** [comment]
looks like you have a server configuration problem

**Comment by Sasamous** [comment]
> looks like you have a server configuration problem

where can I see this?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/11770#issuecomment-544839907

**Comment by Sasamous** [comment]
No sorry, I was asking: where can I check to find the problem on my configuration? Some logs? Some pages?

**Comment by mariuszkrzaczkowski** [comment]
check all log logs: apache FPM php crm

**Comment by Sasamous** [comment]
I can't find any useful information by logs.
I installed the last version of YetiForce (5.2), I created an application an user for that application, I get the exactly same problems:
![image](https://user-images.githubusercontent.com/40520020/67289484-fad9b700-f4de-11e9-90eb-10b2fa1eaa16.png)

![image](https://user-images.githubusercontent.com/40520020/67289539-11800e00-f4df-11e9-9751-7f3ed7ee3147.png)

The server configuration:
![image](https://user-images.githubusercontent.com/40520020/67289629-34aabd80-f4df-11e9-840e-06422dc4a4f3.png)

**Comment by rskrzypczak** [comment]
enable showing errors: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/Debug.php#L88

**Comment by Sasamous** [comment]
> enable showing errors: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/Debug.php#L88

{"status":0,"error":{"message":"2: array_merge(): Argument #1 is not an array in \/var\/www\/html\/yetiforce\/api\/webservice\/Core\/Request.php, line 43","code":200}}

**Comment by javjim** [comment]
whats that x-encrypted? and also again, use form-data in body.

**Comment by Sasamous** [comment]
> whats that x-encrypted? and also again, use form-data in body.

I don't know why it autochanges to x-www-form-urlencoded, btw ok, with form-data it works, thanks you :)

**Comment by Sasamous** [comment]
To close issue, I need to achieve just another answer, why works with ../"webservice.php?module=Users&action=Login" and not with "../webservice/Users/Login"?
![image](https://user-images.githubusercontent.com/40520020/67295054-eb5e6c00-f4e6-11e9-8f30-69f0d1364b8d.png)

**Comment by ezbank** [comment]
**How to get list record via api by sort order**

**Comment by mariuszkrzaczkowski** [comment]
@ezbank you can't, but you can add it easily and quickly like this
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/api/webservice/Portal/BaseModule/RecordsList.php#L63L65

**Comment by mariuszkrzaczkowski** [comment]
@Sasamous check if you have it turned on mod_rewrite

**Comment by Sasamous** [comment]
@mariuszkrzaczkowski 
![image](https://user-images.githubusercontent.com/40520020/67370956-e4356d80-f57b-11e9-9035-a33d16b00e42.png)

**Comment by rskrzypczak** [comment]
check this: https://github.com/YetiForceCompany/YetiForceCRM/issues/4154

**Comment by Sasamous** [comment]
> check this: #4154

Perfect, this worked, I had to enable "rewrite" from mods.

I used this commands:
`a2enmod rewrite`
`systemctl restart apache2`

Thank you all 😄

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/7d55a95d3ad78155e5494168b74464013c00812e
see now https://doc.yetiforce.com/api/#/BaseAction/Api%5CPortal%5CBaseAction%5CModules%3A%3Aget

**Comment by Sasamous** [comment]
> Fixed [7d55a95](https://github.com/YetiForceCompany/YetiForceCRM/commit/7d55a95d3ad78155e5494168b74464013c00812e)
> see now https://doc.yetiforce.com/api/#/BaseAction/Api%5CPortal%5CBaseAction%5CModules%3A%3Aget

Works on demo page, but I don't have "api" folder in "public_html" folder, I'm on 5.2-Complete

![image](https://user-images.githubusercontent.com/40520020/67477481-73b14e00-f65a-11e9-9c5c-504bcb435fd6.png)

How can I solve on my installation?

**Comment by Sasamous** [comment]
I could just comment the `return false;` and it works, but there is a better way? I don't want allow all requests without a filter

**Comment by Sasamous** [comment]
Cause I didn't solved my problem, I'm using demo Yetiforce for test API, but I get this error:

`{"status":0,"error":{"message":"No permissions to view record","code":403,"backtrace":"#0 api\/webservice\/Portal\/BaseModule\/Record.php (62)  >>  Api\\Core\\Exception->__construct('No permissions to view record',403)\n#1 api\/webservice\/Core\/BaseAction.php (28)  >>  Api\\Portal\\BaseModule\\Record->checkPermission()\n#2 api\/webservice\/Controller.php (87)  >>  Api\\Core\\BaseAction->checkAction()\n#3 webservice.php (15)  >>  Api\\Controller->process()\n#4 public_html\/webservice.php (11)  >>  require('webservice.php')"}}`

when I try to make this call:
https://gitdeveloper.yetiforce.com/webservice.php?module=Vendors&action=Record&record=368

I'm using "demo@yetiforce.com" (administrator) user, all other calls I tried works

@mariuszkrzaczkowski

**Comment by mariuszkrzaczkowski** [comment]
check if user api has permissions for this record

**Comment by Sasamous** [comment]
> check if user api has permissions for this record
Yes, the user have permissions, with that user I can see the page

![image](https://user-images.githubusercontent.com/40520020/67761287-48a47100-fa43-11e9-8b34-2faedafccff1.png)

![image](https://user-images.githubusercontent.com/40520020/67761411-8608fe80-fa43-11e9-90c8-632d52bf2ca9.png)

**Comment by Sasamous** [comment]
@mariuszkrzaczkowski User have premissions, I checked and modified my demo session in different ways, nothing helps, maybe is a bug for that module?
By the way, how can I get this fix https://github.com/YetiForceCompany/YetiForceCRM/issues/11770#issuecomment-545848092 on version 5.2 (Complete)? Must I uninstall everything again and download a non-stable version to get a more working (but not completely working) API system?

**Comment by javjim** [comment]
2 things, use as different issue for different questions, also, that issue you have is the same I am having here right? https://github.com/YetiForceCompany/YetiForceCRM/issues/11841 can you add your info there

**Comment by Sasamous** [comment]
Yes, it is the same response but in Demo Environment I can get ../Contacts/Record/recordID, my problem is in ../Vendors/Record/recordID

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/11841#issuecomment-547734984

**Comment by Sasamous** [comment]
> [#11841 (comment)](https://github.com/YetiForceCompany/YetiForceCRM/issues/11841#issuecomment-547734984)

Shouldn't it set by default for every module? So I can access everything from API by default, if I need to exclude something I could disable it by that field 🙂 @mariuszkrzaczkowski 

Btw today it works without this fix, I dunno why, maybe a new commit fixed it (on demo version).

I will maintain opened my issue until a full API functionality isn't implemented, I'm creating a complete connector between YetiForce and C++ ERP Systems, so I must use all API calls in all ways for that reason.

**Comment by ezbank** [comment]
how to get total records by x-condition via api

**Comment by mariuszkrzaczkowski** [comment]
@ezbank create a new issue

**Comment by Sasamous** [comment]
I'm asking for a complete API documentation, I like you added this to 5.3 Milestone, but you can't close this until you wrote a full API Documentation.

I see you used Swagger to give some examples of "Record" action, but there are a lot of other actions (Dashboard, Fields, Hierarchy, Pdf, PdfTemplates, Privileges, RecordRelatedList, RecordsList..) so how can users use those actions?

Also, where do you show body headers? Like x-condition, x-fields..
I expect you will close this post when you get a documentation of your API System.


Thanks for your commitment 😃

**Comment by bpabiszczak** [comment]
> but you can't close this until you wrote a full API Documentation.

Of course I can :)

**Comment by Sasamous** [comment]
> > but you can't close this until you wrote a full API Documentation.
> 
> Of course I can :)

Yes, but it is clear you are randomly closing issues that aren't really closed and adding them to 5.3 Milestone to increase the "Complete" percentage instead of taking care of opened issues :)

**Comment by bpabiszczak** [comment]
I don't know what makes you think that if you ask for complete documentation the issue will be open until this "demand" of yours is met. The documentation is the way it is, if you don't think it's complete you can always expand it.

If you don't want to pay then accept the current state of the application/documentation.

If you do want to pay then, for a fee, we can expand the documentation, teach you how to use API, solve API issues. The whole community will surely be thankful to you if you spend several thousand € on the API documentation.

**Comment by Sasamous** [comment]
**I'm actually working on your product** by creating a connector between your CRM and several ERP Systems;

so your CRM will increase users by a lot once we (me and my team) finish the project.

But if **your product isn't incomplete**, because **you don't have a documentation** on how to use it, and you ask your users (who in this case are actually working for your CRM) to **pay several thousand € to ask you to work on your project** just by writing a documentation, that should be the first thing to do in a public software, I don't think we are creating a connect between ERP Systems and the right CRM System.

By the way, **I'm actually creating a sort of documentation** in your GitHub issues section, **by creating very detailed issues** with tons of information **useful for you and for who is reading**, so your **community is already thankful to me**.


So, **your request to users** to 
> spend several thousand € on the API documentation.

is pretty ridiculous because it means your software **isn't really free** if **users can't use it without paying it**.
