### ISSUE TITLE
White Screen at installation

### ISSUE THREAD

**Issue by GreatBrands** [YetiForceCompany/YetiForceCRM#11773]
Hello,
I am trying to install YetiForce CRM for the first time. Unfortunately, I only get a white screen when I want to launch the installation procedure.

Settings look ok, rights are set as described in the description. PHP Version is 7.1

Here is PHP.ini:

display_errors = On
max_execution_time = 900
max_input_time = 600
max_input_vars = 10000
memory_limit = 1024M
post_max_size = 64M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php71"
upload_max_filesize = 512M
zlib.output_compression = Off

What's wrong? Thanks for helping.

Kindest Regards

Marc

**Comment by mariuszkrzaczkowski** [comment]
server configuration problem, check logs

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/web-server-requirements
