### ISSUE TITLE
[Question] How to create printabale inventory

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#11771]
**Hello, i would like to create a PDF or excel document to print a list of all my products in all of my storages,**

_this image is just a example i made in excel to understand a little bit more_ 

![image](https://user-images.githubusercontent.com/45770116/67028702-cb3f3f00-f0d9-11e9-8066-c5d341aa6b43.png)

**can someone help me with this. i tried a couple of options but can find the right solution**

Thank you for helping

**Comment by apcloic** [comment]
Hi @maeglin4 

Did you try making a simple template using PDF module available on BO -> System tools -> PDF ?

**Comment by maeglin4** [comment]
ok so i found the right variable $(custom : ProductsTable|IStorages)$ to select to get the information i want, and i have to select all my storage before generating the PDF. 

thanks
