### ISSUE TITLE
[Question] User Name Field empty 

### ISSUE THREAD

**Issue by GreatBrands** [YetiForceCompany/YetiForceCRM#11782]
Hello,
I managed to get the installation done until the last screen: Confirm configuration settings

Here in the Database section the user Name is empty and I cannot continue. Please see screenshot.

Most of the server settings are done. 

What's wrong here?

Thanks for helping.

Marc

![Screenshot 2019-10-20 at 16 33 06](https://user-images.githubusercontent.com/56741621/67161107-96402000-f357-11e9-869c-56e973d3d94f.png)

**Comment by rskrzypczak** [comment]
what username did you give?

**Comment by bartusek27** [comment]
I have the same exact problem - my username is `gug-crm`
