### ISSUE TITLE
How to share records access to owner 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#11786]
Module access Lead is private.

User A (Created by) has lead1 and lead2 records. if admin  have assigned lead1 records to User B.
Now User A unable to see Lead1 records. But i want give that records  access to User A (Created by) at any level with out using Share with users filed.

Please help me

**Comment by fbojan** [comment]
How is it that each user sees only their own records.
I do not know how to set this.
I've been trying all day, everyone sees everything, even though they have different rolls
THANKS

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=SharingAccess&parent=Settings&view=Index&block=1&fieldid=5
