### ISSUE TITLE
how to change direction in pdf 

### ISSUE THREAD

**Issue by hamedbaseri** [YetiForceCompany/YetiForceCRM#11789]
I need help. After making a template for the pre-invoice. When taking pdf output. The Persian font is displayed incorrectly and the letters are displayed in reverse. I think this problem is due to the  direction and it should be the RTL direction . But I don't know how to solve this problem? !!

![Untitled-1](https://user-images.githubusercontent.com/56822243/67211787-291ca100-f3d0-11e9-8981-034030054fe5.png)

**Comment by bpabiszczak** [comment]
You need a programmer, we didn't have any clients who needed such functionality.
