### ISSUE TITLE
[Question] Extend basic php fnc in workflows

### ISSUE THREAD

**Issue by TonyM15** [YetiForceCompany/YetiForceCRM#11780]
Maybe it is good idea to extend basic php statements in workflows so to expand flexibility?
For instance I want to capitalize Each word in txt field with ucwords(). At the moment not possible

**Comment by vovpff** [comment]
You can modify system code for your needs. I has implenented once concatenation with optional separator and text replacement

**Comment by TonyM15** [comment]
Sure I know, however extending this to some operators widely used in basic database/field operations will make it nicer and easier.

**Comment by vovpff** [comment]
You can commit some stuff to project. As devs said workflow engine will be rewritten in nearest future.

**Comment by waran70** [comment]
Hope current workflows will be compatible with new engine.
O.O

**Comment by vovpff** [comment]
@waran70 as luck would have it
