### ISSUE TITLE
[bug] Context-sensitive help dont work

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#11783]
ver. 5.2.32

Software configuration/Standard modules/Edit fields/System settings/Context-sensitive help

Cannot save help text. If I press the save key, nothing happens.

Greetings from Slovenia

**Comment by fbojan** [comment]
Now I understand that it is not a bug to intentionally not close the popup window, but not to save the record.

**Comment by fbojan** [comment]
I do not understand ? How closed if it still doesn't work

![New Modul](https://user-images.githubusercontent.com/25682437/67356073-547ec780-f559-11e9-991c-bac8c17e3814.gif)

**Comment by fbojan** [comment]
I do not understand ? How closed if it still doesn't work.


![test](https://user-images.githubusercontent.com/25682437/67356284-fbfbfa00-f559-11e9-9695-2ec714ab6063.gif)

**Comment by vovpff** [comment]
Sorry. I misunderstanded your previous comment and closer. I will reopen issue.
What about browser console? Any errors?

**Comment by vovpff** [comment]
Check this issue #11550. Maybe some file acces rights problem?

**Comment by fbojan** [comment]
I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by fbojan** [comment]
And Local YetiForce CRM 5.2 Service Pack v16

THANKS

**Comment by fbojan** [comment]
I installed 5.2.0_ServicePack_v17.zip  and it works very well now. 

Thanks to the team
