### ISSUE TITLE
[Question]: Is there a debug-function for output plain PDF-code(NOT rendered)?

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11788]
Hi,
Is there a built-in ways in YetiForce-PDF to output the «source-code» from the hole PDF (with all `<table><thead></thead><tbody><tr><td>....</td></tr><tr>...</tr></tbody></table` stuff as string).

I tried different approaches, but alltime I get a rendered Version. With them, it is quite hard or impossible to figure out some HTML-Structure errors.

Would be great to have a simple solution for. So I could import the code beautify it and find the problem.

- **Do you know a debug-function or some build-in function in YetiForce to get the «plain source code as string»?**
- **Maybe there is a simple solution to disable the PDF-Rendering while developing/debugging?**

Usually, I debug PDF with output variables as string with my debug-function https://github.com/YetiForceCompany/YetiForceCRM/issues/11512 extended with @mariuszkrzaczkowski part Textparser.

But with all my different trials, the PDF is alltime rendered...
Thanks in advanced
Martin

**Comment by apcloic** [comment]
@mad99 
Output variables from app/Pdf/YetiForcePDF.php should work.

**Comment by mad99** [comment]
@»: Thank you.
I guess for the method «output» I have to use YetiForcePDF different then I do it now.
Usually I have cloned a «PDF Template» unter Settings>System Tools>PDF.
Therein the second «Document content» after first «Document basic option», I use the fields to choose an own written TextParser for particular pdf-sections.

_**Sometimes I guess there a two totally different approaches to use YetiForce-PDF in YetiForce. Maybe I use the «build-in» for simple use.**_

- Is there also an other approach to use own PHP-Scripts like in the examples Folder (https://github.com/YetiForceCompany/YetiForcePDF/tree/developer/examples) from GIT?

I can't figure out, how I could use them in the above described place « Settings>System Tools>PDF.»

- **Maybe you or someone else have a good hint for documentation or some dummy-code to get the clou?**

- **Or maybe I does not understand how I could use your mentioned «output» method in my «own TextParser»? (If there is an obvious** (not for me) solution for this «-build-in-way-with-textparser» I would be pleased to learn how!)

Thanks anyway
