### ISSUE TITLE
Customer Portal on Yetiforce 2.0

### ISSUE THREAD

**Issue by VSecurity** [YetiForceCompany/YetiForceCRM#1179]
Hi guys!

My Yetiforce 2.0 doesnt send customer portal login and password. I already actived my workflows, uncomment config/api yetiportal, configured smtp server and marked permission to send e-mail on contacts but i didn't receive Customer Portal Login. Can someone help me?

**Comment by KatarzynaUlichnowska** [comment]
For now, to send an email with a pasword to your customer portal you should follow these instructions first :  https://yetiforce.com/en/administrator-documentation/instalation/129-customer-portal-instalation.html and then:
- create a contact and tick "Permission to send emails" and fill in the "Primary Email" field. Save this contact. 
- edit contact and tick the "Portal User" field. Save again.
An email with password should be sent to the contact's email address.

PS. It's important to tick the "Portal User" field when editing the contact.
