### ISSUE TITLE
[feature] Sending email window modification

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#118]
Currently sending email opening roundcube module in the same window. it will be more convenient to create great looking popup with new email content or at least temporary every email click  send to new window so it will not mess with current open module.

**Comment by bpabiszczak** [comment]
Add: https://github.com/YetiForceCompany/YetiForceCRM/commit/cc6cbe8e515884f473c5dfff99d647d40608c89f https://github.com/YetiForceCompany/YetiForceCRM/commit/373a1f5c5238c6a1ddb8e882c9cbfd917ff48eb1 https://github.com/YetiForceCompany/YetiForceCRM/commit/96caaa6b942bcacfa0cd9aaf9e527158b317be8f
