### ISSUE TITLE
Is it possible to create a complex object (ie: quote) using REST API

### ISSUE THREAD

**Issue by joao-violante** [YetiForceCompany/YetiForceCRM#11807]
Hello
I've been performing some search around the internet. It's possible using REST API to retrieve "inventory" informations from complex object, but is it possible to create a new one.
If yes, example would be apreciated.
Regards

**Comment by mariuszkrzaczkowski** [comment]
Yes

**Comment by joao-violante** [comment]
Great
Would there be an option to get an example, or a link to something similar ?
Thanks

**Comment by bpabiszczak** [comment]
https://doc.yetiforce.com/api/
