### ISSUE TITLE
[Question]: Working Live Example for YetiForcePDF integration in YetiForce > Settings > SystemTools > PDF Templates 

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#11801]
Hi,
I'm searching the [right way](https://github.com/YetiForceCompany/YetiForceCRM/issues/11788#issuecomment-544523477) to insert the YetiForcePDF Framework into the YetiForce PDF Template-System.

I guess there have to be an other way then my current one (sea bellow):

### Question:
**- How we can use/include the examples from [YetiForcepPDF example folder](https://github.com/YetiForceCompany/YetiForcePDF/tree/developer/examples)?**

___

#### 1. Include own Class (e.G.) "OwnInvoice_2_3" 
Include Class under «System Settings» > «System Tools» > «PDF Template» > «Document Content» with `«$(custom` : `OwnInvoice_2_3)$»`.
This approach makes it easy to do changes for all kind of invoices/quotes in one place (source Code of OwnBase-php Script).
<img width="323" alt="Include OwnInvoice" src="https://user-images.githubusercontent.com/6169308/67265317-c26db500-f4ad-11e9-9c80-2ca7b1131d87.png">
#### 2. ownInvoice class extend ownBase 
This approach helps to reduce redundant code and make it a lot easier to manage.
And its easy to do change and extend existing invoices/quotes with less effort.
![define own class](https://user-images.githubusercontent.com/6169308/67265485-21cbc500-f4ae-11e9-95e0-58e460c930fc.png)
#### 3. ownBase class extend TextParser Base-class 
I guess this is the default way to use YetiForcePDF in YetiForce. But I can't figure out where I could include the example-code from link above...
![ownBaseClass](https://user-images.githubusercontent.com/6169308/67265639-82f39880-f4ae-11e9-84f2-b027f06172f7.png)

**Comment by bpabiszczak** [comment]
We do not provide programming advice free of charge. Buy a packet of hours, we'll be happy to help.
