### ISSUE TITLE
[Question] PDF table border color not showing

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#11812]
when creating a pdf template, i want to add a color for the borders of the table, it shows in the configuration , but when i generate the pdf the color is not showing

how can i fix this ?

![image](https://user-images.githubusercontent.com/45770116/67425612-558a1600-f5a6-11e9-985f-e139c11a2e71.png)

**Comment by apcloic** [comment]
@maeglin4 
Hi,
Check your source code, you have to use inline CSS + you will find the list of supported css rules here :
 https://github.com/YetiForceCompany/YetiForcePDF

**Comment by maeglin4** [comment]
below is the source code of the the screenshot above...

is this how its supposed to be ?

![image](https://user-images.githubusercontent.com/45770116/67497823-89b81200-f64c-11e9-8f7d-0b49d4dd4014.png)

**Comment by z0lo13** [comment]
@maeglin4 
try 
border: 1px #ff3333 solid;

**Comment by maeglin4** [comment]
thanks i found in the examples of the PDF LIB

`<td style="border:1px solid red;">youre text here blablabla</td>`
