### ISSUE TITLE
Problem z updatem z 4.4 do 5.2

### ISSUE THREAD

**Issue by yotuze** [YetiForceCompany/YetiForceCRM#11817]
Witam,
Mam problem z aktualizacją YetiForce z 4.4 do 5.2.

Pobrałem wszystkie potrzebne paczki i po kolei instaluje je, czyli:
- 4.4.0_to_5.0.0_v6
- 5.0.0_to_5.1.0_v1
i do tego momentu wszystko jest ok, ale gdy zainstaluje:
- 5.1.0_to_5.2.0_v4
to pojawia się błąd, że:

`Some errors appeared during the update. We recommend verifying logs and updating the system once again.`

Następnie wchodząc np. do kontrahenta dostaje błąd 500, po sprawdzeniu logów serwera jest błąd:

`[Thu Oct 24 09:34:12.606717 2019] [proxy_fcgi:error] [pid 572] [client 192.168.1.121:53173] AH01071: Got error 'PHP message: PHP Warning:  require(app_data/moduleHierarchy.php): failed to open stream: No such file or directory in /var/www/html/app/ModuleHierarchy.php on line 22\nPHP message: PHP Fatal error:  require(): Failed opening required 'app_data/moduleHierarchy.php' (include_path='.:/usr/share/php') in /var/www/html/app/ModuleHierarchy.php on line 22\n'`

i faktycznie nie ma katalogu "app_data" choć w paczce aktualizacji ten katalog z tym plikiem jest obecny.

**Comment by mariuszkrzaczkowski** [comment]
sprawdź logi z aktualizacji

**Comment by yotuze** [comment]
cache/logs/update.log - jest pusty

cache/logs/updateLogsTrace.log
`
etiForceUpdate::update| 2019-10-24 12:11:45
YetiForceUpdate::migrateCalendarDefaultTime| 2019-10-24 12:11:45
YetiForceUpdate::migrateCalendarDefaultTime| 2019-10-24 12:11:45 | 0 mim.
YetiForceUpdate::imageFix| 2019-10-24 12:11:52
YetiForceUpdate::imageFix| 2019-10-24 12:11:52 | 0 mim.
YetiForceUpdate::attachmentsFix| 2019-10-24 12:11:52
YetiForceUpdate::attachmentsFix| 2019-10-24 12:11:52 | 0 mim.
YetiForceUpdate::migrateDefOrgField| 2019-10-24 12:11:52
YetiForceUpdate::migrateDefOrgField| 2019-10-24 12:11:52 | 0 mim.
YetiForceUpdate::addFields| 2019-10-24 12:11:52
YetiForceUpdate::addFields| 2019-10-24 12:11:53 | 0 mim.
YetiForceUpdate::updateData| 2019-10-24 12:11:53
YetiForceUpdate::updateData| 2019-10-24 12:11:53 | 0 mim.
YetiForceUpdate::addPicklistValues| 2019-10-24 12:11:53
YetiForceUpdate::addPicklistValues| 2019-10-24 12:11:54 | 0 mim.
YetiForceUpdate::removeEventsModule| 2019-10-24 12:11:54
YetiForceUpdate::removeWorkflowTask| 2019-10-24 12:11:54
YetiForceUpdate::removeWorkflowTask| 2019-10-24 12:11:54 | 0 mim.
YetiForceUpdate::removeEventsModule| 2019-10-24 12:11:54 | 0 mim.
YetiForceUpdate::updateCron| 2019-10-24 12:11:54
YetiForceUpdate::updateCron| 2019-10-24 12:11:54 | 0 mim.
YetiForceUpdate::removeFields| 2019-10-24 12:11:54
YetiForceUpdate::removeFields| 2019-10-24 12:11:54 | 0 mim.
YetiForceUpdate::migrateCvColumnList| 2019-10-24 12:11:54
YetiForceUpdate::migrateCvColumnList| 2019-10-24 12:11:54 | 0.01 mim.
YetiForceUpdate::updateHeaderField| 2019-10-24 12:11:54
YetiForceUpdate::updateHeaderField| 2019-10-24 12:11:54 | 0 mim.
YetiForceUpdate::removePbxManager| 2019-10-24 12:11:54
YetiForceUpdate::addModules| 2019-10-24 12:11:55
YetiForceUpdate::addModules| 2019-10-24 12:11:55 | 0 mim.
YetiForceUpdate::updateInventory| 2019-10-24 12:11:55
YetiForceUpdate::updateInventory| 2019-10-24 12:11:57 | 0.02 mim.
YetiForceUpdate::update| 2019-10-24 12:11:57 | 0.19 mim.
YetiForceUpdate::postupdate| 2019-10-24 12:12:01
YetiForceUpdate::postupdate| 2019-10-24 12:12:01 | 0.01 mim.
YetiForceUpdate::update| 2019-10-24 12:12:31
YetiForceUpdate::addFields| 2019-10-24 12:12:35
YetiForceUpdate::addFields| 2019-10-24 12:12:35 | 0 mim.
YetiForceUpdate::updateData| 2019-10-24 12:12:35
YetiForceUpdate::updateData| 2019-10-24 12:12:35 | 0 mim.
YetiForceUpdate::update| 2019-10-24 12:12:36 | 0.08 mim.
YetiForceUpdate::postupdate| 2019-10-24 12:12:38
YetiForceUpdate::postupdate| 2019-10-24 12:12:38 | 0 mim.
YetiForceUpdate::update| 2019-10-24 12:23:00
YetiForceUpdate::updateScheme| 2019-10-24 12:23:02
YetiForceUpdate::getTableSeqToRemove | vtiger_salutationtype |2019-10-24 12:23:02
YetiForceUpdate::getTableSeqToRemove| 2019-10-24 12:23:02 | 0 mim.
YetiForceUpdate::getTableSeqToRemove | vtiger_leadsource |2019-10-24 12:23:02
YetiForceUpdate::getTableSeqToRemove| 2019-10-24 12:23:02 | 0 mim.
YetiForceUpdate::getTableSeqToRemove | vtiger_contactstatus |2019-10-24 12:23:02
YetiForceUpdate::getTableSeqToRemove| 2019-10-24 12:23:02 | 0 mim.
YetiForceUpdate::getTableSeqToRemove | vtiger_verification |2019-10-24 12:23:02
YetiForceUpdate::getTableSeqToRemove| 2019-10-24 12:23:02 | 0 mim.
YetiForceUpdate::getTableSeqToRemove | vtiger_industry |2019-10-24 12:23:02
YetiForceUpdate::getTableSeqToRemove| 2019-10-24 12:23:02 | 0 mim.
YetiForceUpdate::getTableSeqToRemove | vtiger_accounts_status |2019-10-24 12:23:02
YetiForceUpdate::getTableSeqToRemove| 2019-10-24 12:23:02 | 0 mim.
YetiForceUpdate::getTableSeqToRemove | vtiger_legal_form |2019-10-24 12:23:02
YetiForceUpdate::getTableSeqToRemove| 2019-10-24 12:23:02 | 0 mim.
`

Nic tutaj nie ma, chyba że chodzi jeszcze o jakieś inne logi?

**Comment by rskrzypczak** [comment]
Jeżeli uzyskałeś ten komunikat:
"_Some errors appeared during the update. We recommend verifying logs and updating the system once again._"
To informacja o błędzie musi znajdować się w logach.
Sprawdź jeszcze raz pliki updateLogsTrace.log, Importer.log

**Comment by rskrzypczak** [comment]
> Czy któreś katalogi wymagają specjalnych uprawnień?

![image](https://user-images.githubusercontent.com/10221999/68100202-01950080-fec7-11e9-9cee-dc97cf4b4f8f.png)
