### ISSUE TITLE
Ticket information fields order doesn't match with edit/detail views

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11823]
Hello,

When I edit fields order in the admin for Ticket Information block, it works with the edit view, meaning the edit view fields show up in the order I arrange them in the admin, but when I save the ticket and check the detail view, the order is different.

**Comment by vovpff** [comment]
This happens because admin user usually can see all possible fields. User can see only fields what listed in profile.

Also there are available fields what websible at detail view and not available in edit view and etc...

**Comment by acoolov** [comment]
I am so confused. Whenever I start messing around with the field order, it completely messes it up. 
For example, now for a contact module, in the field settings, my first name and last name are on the left side, but in the contact edit view they are on the right side, and all fields are completely the opposite of each other. Whatever is on the left side in the settings, now is on the right side in the edit view. 

Same thing with tickets. It was showing correctly before I started moving fields around. In the tickets, the detail view got messed up. It shows correctly in the edit view, but the detail view is completely the opposite of what I set it to in the field settings. 

What is going on?

**Comment by acoolov** [comment]
It must be a bug because I tried re-arranging the fields in the demo version and it does the same thing. As soon as I hide one or two modules, the order is completely messed up, and the more I move them around the worse it gets. I get get them in order anymore:/

**Comment by acoolov** [comment]
Looks like i was able to fix this by arranging the fields in a way that the fields that don't appear in the edit view (for example account number or ticket number) are not messing up the order of the fields. 

Was very tricky.

**Comment by vovpff** [comment]
%) maybe screenshots can help to understand what you mean
