### ISSUE TITLE
Starting ticket to a higher number

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11821]
Hi all!

How can I change the starting ticket number to a higher number if I don't want to start with ticket number 1. I need to start at least with 25000.

Thank you.

**Comment by vovpff** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Vtiger&parent=Settings&view=CustomRecordNumbering&block=2&fieldid=22

![image](https://user-images.githubusercontent.com/8545791/67491188-2e524800-f67d-11e9-910d-f62cf56c0ee8.png)

**Comment by acoolov** [comment]
Thanks so much Vladimir.
Also is it possible to remove the letter H from the ticket number?

**Comment by vovpff** [comment]
Try to change `Use prefix` field

**Comment by acoolov** [comment]
Thanks, that worked. 
When i try to remove the prefix for tickets, it says prefix is already in use. Would it be possible to find out which module uses no prefix so i can put some prefix to that module and use no prefix for my tickets?

Thanks again.

**Comment by vovpff** [comment]
@acoolov really I don't know. What is the problem to use H prefix?

**Comment by acoolov** [comment]
We just never really used ticket numbers with letters. Just a number is simpler.

**Comment by vovpff** [comment]
@acoolov as for me there is no difference in this letter...
