### ISSUE TITLE
Custom Ticket status

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11838]
Hello everyone,

How can I modify existing ticket statuses or create new ticket statuses in YetiForce. 

The problem is, it looks like the system is tied to the existing ticket statuses and you can't change them. So i tried creating new ticket status field with my desired values. But then I can't replace the old ticket status field with the new one because as soon as I remove existing ticket status field, the ticket module will not load. Gives me error. 

How can I have only these four ticket statuses:

Open
In Progress
Pending
Closed

Please help!

**Comment by davide-alghi** [comment]
Hi,
you must edit picklist values **only via YF GUI** not via DB or PHP code: you could have deep problems in the future.

That said, ticket module, and many others, have fixed picklist values to provide automatism.
What you can try to do is to get 4 of fixed status values and "map" to your needed status values (Open, In Progress, Pending, Closed).


closer ... 

**step one: logical and semantic mapping**
"Response received" => "Open"
"In Progress" => "In Progress"
"For approval" => "Pending"
"Accepted" => "Closed"

**step two: records status mass-edit**
by mass editing move ticket records to (4) chosen statuses: "Response received", "In Progress", "For approval", "Accepted"

**step three: rename status value labels by** 
System tools >> Language Management >> Edit language

**step four: hide not used status**
remove not used (fixed) picklist values from role

**Comment by acoolov** [comment]
In this step

step three: rename status value labels by
System tools >> Language Management >> Edit language

Can I just rename existing status values in language editor?
I tried renaming them but it gave me an error saying contact your administrator.

**Comment by acoolov** [comment]
How do I map my custom ticket status to an existing ticket status? Where in settings do I do that?

**Comment by davide-alghi** [comment]
> In this step
> 
> step three: rename status value labels by
> System tools >> Language Management >> Edit language
> 
> Can I just rename existing status values in language editor?
> I tried renaming them but it gave me an error saying contact your administrator.

Yes you can; try on https://gitstable.yetiforce.com/
if you have some error maybe you have some problem with your installation

_____

> How do I map my custom ticket status to an existing ticket status? Where in settings do I do that?

that is only a "mind mapping" to choose the four status to use

**Comment by acoolov** [comment]
Im trying to add a value Closed in Settings - Edit Picklists and it's not allowing me to save it. I can save other words but not the word Closed or Open. 

This is driving me insane. How come I am the only one that wants custom ticket statuses?

**Comment by acoolov** [comment]
Now I can't create a ticket from ticket quick create. Gives me this error:

{"success":true,"result":{"ticket_title":{"value":"sdfsdfsdfsdfsd","display_value":"sdfsdfsdfsdfsd","prev_display_value":false},"parent_id":{"value":"115","display_value":"<a class='modCT_Accounts showReferenceTooltip js-popover-tooltip--record' href='index.php?module=Accounts&view=Detail&record=115' title='Account'>Comfort Inn &amp; Suites Brooklyn M...<\/a>","prev_display_value":false},"ticketstatus":{"value":"Open","display_value":"<span class=\"picklistValue picklistLb_HelpDesk_ticketstatus_Open\">Awaiting verification<\/span>","prev_display_value":false},"assigned_user_id":{"value":"1","display_value":"<a class=\"js-popover-tooltip--record\" href=\"index.php?module=Users&view=Detail&record=1\"> Akulov Eduard <\/a>","prev_display_value":false},"ticketpriorities":{"value":"Low","display_value":"<span class=\"picklistValue picklistLb_HelpDesk_ticketpriorities_Low\">Low<\/span>","prev_display_value":false},"servicecontractsid":{"value":"","display_value":"","prev_display_value":false},"ticket_no":{"value":"10520","display_value":"10520","prev_display_value":false},"ticketcategories":{"value":"","display_value":"","prev_display_value":false},"private":{"value":"","display_value"

**Comment by acoolov** [comment]
I am indeed able to modify language variable and was able to rename ticket status values to what I need in the demo version. But mine does not allow me to save. Anybody would know what I should check? 

In settings - System Tools - Language Management 
I'm trying to edit ticket status values to what I need them to be, but it won't allow me to save them. It gives me this message - Error, please inform the Administrator

Please help.

**Comment by acoolov** [comment]
Was able to accomplish this by re-installing Yetiforce and meeting all requirements first. 
Then went to modify language variable for some ticket status values. 
Then disabled the ones I didn't need in pick list for tickets. 
Now I have only ticket statuses that I need without unnecessary statuses.
