### ISSUE TITLE
[Question] Wyzwalacz jednorazowy

### ISSUE THREAD

**Issue by espeoceka** [YetiForceCompany/YetiForceCRM#11832]
Cześć, tworze proste zadanie jednorazowe: jeżeli etap sprawy zmienił się na.... jednorazowo powinno wykonać się zadanie utworzenia nowego rekordu ( w module przebieg postępowania ).

Zadanie wykonuję się poprawnie problem że kilka razy pod rząd pomimo pozostawania na tym samym etapie ( warunek: etap zmienił się na... ), problem dotyczy wszystkich zadań jednorazowych. 

Zadanie: "Raz gdy zostaną spełnione warunki"----> warunek: jeżeli etap zmienił się na....---> utwórz rekord

Czy jest sposób żeby zadanie wykonywało się faktycznie tylko raz ?

Ewentualnie czy istnieje możliwość rejestrowania w historii tylko konkretynych wydarzeń ?

**Comment by bpabiszczak** [comment]
Proszę o filmik pokazujący problem na gitdeveloper...
