### ISSUE TITLE
Cannot edit language variable in Settings - Language Management

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11840]
I'm trying to edit ticket status fields in YetiForce.

I go to settings - System Tools - Language Management
I'm trying to edit ticket status values to what I need them to be, but it won't allow me to save them. It gives me this message - Error, please inform the Administrator

I was able to modify them in the demo version.

Please help.

**Comment by rskrzypczak** [comment]
enable logs.
what version are you using?
maybe you have wrong server configuration,
maybe you don't have proper permissions for files or directories.

**Comment by acoolov** [comment]
Fixed it by reinstalling and making sure all pho and permission requirements were met.
