### ISSUE TITLE
BUG when creating a ticket while being inside another ticket!

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11844]
I just spotted a bug.

If you go to any ticket and click on it, then while being on that ticket page, click on quick create and click try to create a new ticket. You will get this type of screen below. This happens even in the demo version. Please try it yourself. Hope you guys can fix this.

{"success":true,"result":{"ticket_title":{"value":"dfgdgdg","display_value":"dfgdgdg","prev_display_value":false},"pssold_id":{"value":"1164","display_value":"<a class='modCT_Assets showReferenceTooltip js-popover-tooltip--record' href='index.php?module=Assets&view=Detail&record=1164' title='Asset'>Akumulatory do zastosowa\u0144 telekomun...<\/a>","prev_display_value":false},"ticketstatus":{"value":"Open","display_value":"<span class=\"picklistValue picklistLb_HelpDesk_ticketstatus_Open\">Open<\/span>","prev_display_value":false},"product_id":{"value":"624","display_value":"<a class='modCT_Services showReferenceTooltip js-popover-tooltip--record' href='index.php?module=Services&view=Detail&record=624' title='Service'>Projektowanie i wykonywanie aplikac...<\/a>","prev_display_value":false},"assigned_user_id":{"value":"5","display_value":"<a class=\"js-popover-tooltip--record\" href=\"index.php?module=Users&view=Detail&record=5\"> YetiForce Demo <\/a>","prev_display_value":false},"servicecontractsid":{"value":"750","display_value":"<a class='modCT_ServiceContracts showReferenceTooltip js-popover-tooltip--record' href='index.php?module=ServiceContracts&view=Detail&record=750' title='Service Contract'>Umowa serwisowa nr 09.29.14<\/a>","prev_display_value":false},"ticketpriorities":{"value":"Low","display_value":"<span class=\"picklistValue picklistLb_HelpDesk_ticketpriorities_Low\">Low<\/span>","prev_display_value":false},"parent_id":{"value":"236","display_value":"<a class='modCT_Accounts showReferenceTooltip js-popover-tooltip--record' href='index.php?module=Accounts&view=Detail&record=236' title='Account'>K + K Sp. z o.o.<\/a>","prev_display_value":false},"ticketseverities":{"value":"","display_value":"","prev_display_value":false},"ticketcategories":{"value":"","display_value":"","prev_display_value":false},"update_log":{"value":"","display_value":"","prev_display_value":false},"modifiedby":{"value":"5","display_value":"YetiForce Demo","prev_display_value":false},"from_portal":{"value":"","display_value":"","prev_display_value":false},"contract_type":{"value":"","display_value":"","prev_display_value":false},"contracts_end_date":{"value":"","display_value":"","prev_display_value":false},"private":{"value":"","display_value":"","prev_display_value":false},"ticket_no":{"value":"H55","display_value":"H55","prev_display_value":false},"createdtime":{"value":"2019-10-26 02:01:01","display_value":"2019-10-26 02:01","prev_display_value":false},"created_user_id":{"value":"","display_value":"","prev_display_value":false},"modifiedtime":{"value":"2019-10-26 02:01:01","display_value":"2019-10-26 02:01","prev_display_value":false},"shownerid":{"value":"","display_value":"","prev_display_value":false},"crmactivity":{"value":"","display_value":"0","prev_display_value":false},"was_read":{"value":"","display_value":"","prev_display_value":false},"ordertime":{"value":"","display_value":"0.00","prev_display_value":false},"sum_time":{"value":"","display_value":"0.00","prev_display_value":false},"parentid":{"value":"","display_value":"","prev_display_value":false},"sum_time_subordinate":{"value":"","display_value":"0.00","prev_display_value":false},"description":{"value":"","display_value":"","prev_display_value":false},"attention":{"value":"","display_value":"","prev_display_value":false},"solution":{"value":"","display_value":"","prev_display_value":false},"response_range_time":{"value":"","display_value":"0m","prev_display_value":false},"solution_range_time":{"value":"","display_value":"0m","prev_display_value":false},"idle_range_time":{"value":"","display_value":"0m","prev_display_value":false},"closing_range_time":{"value":"","display_value":"0m","prev_display_value":false},"response_datatime":{"value":"","display_value":"","prev_display_value":false},"solution_datatime":{"value":"","display_value":"","prev_display_value":false},"idle_datatime":{"value":"","display_value":"","prev_display_value":false},"closing_datatime":{"value":"","display_value":"","prev_display_value":false},"response_expected":{"value":"","display_value":"","prev_display_value":false},"solution_expected":{"value":"","display_value":"","prev_display_value":false},"idle_expected":{"value":"","display_value":"","prev_display_value":false},"_recordLabel":"dfgdgdg","_recordId":3902,"isEditable":true}}

**Comment by acoolov** [comment]
Did anyone address this?

**Comment by acoolov** [comment]
Sorry for not understanding. Was this bug resolved?

**Comment by mariuszkrzaczkowski** [comment]
Yes

**Comment by acoolov** [comment]
Does this mean the bug fix will be included in the next update/release?

**Comment by vovpff** [comment]
Yes. Or you can temporary implement manually commit what available below.
