### ISSUE TITLE
Workflow notification emails

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11848]
Friends,

I've successfully configured smtp with a gmail account in the settings and when i saved, i successfully received a test email from Yetiforce. 

Now when i enable a workflow for ticket comments to send notification when a comment is added to a ticket, i get no notification. 

Am i missing any other piece of configuration or is it supposed to work since i received the test email from the system when configured smtp?

**Comment by acoolov** [comment]
@mariuszkrzaczkowski Do you or anyone else happen to know what i'm missing?

**Comment by mariuszkrzaczkowski** [comment]
start with that
![github](https://user-images.githubusercontent.com/10198654/68273036-ae0ce900-0065-11ea-99d5-dbfd50175736.jpg)
