### ISSUE TITLE
[Question] How to get a record (No Permission to view Record) API

### ISSUE THREAD

**Issue by javjim** [YetiForceCompany/YetiForceCRM#11841]
### Description
I am trying to get a record I just created via API.
I am using {HTTP_WEB_URL}/webservice/Contacts/Record/138

This is the error I get 
```{"status":0,"error":{"message":"No permissions to view record","code":401}}```

The contact is shared with the user I use on 'WebServices - User' and has the Permission based on User.

What am I doing wrong?

**Comment by mariuszkrzaczkowski** [comment]
What user owns the record created?
Which user is selected on the api user?

**Comment by javjim** [comment]
Same user is used everywhere

**Comment by rskrzypczak** [comment]
I don't know which version you use, but I think you need to add a new field  "Server Access" for the module.
![image](https://user-images.githubusercontent.com/10221999/67829127-3fb0af80-fad6-11e9-8204-637193fa1356.png)
and mark
![image](https://user-images.githubusercontent.com/10221999/67829185-8e5e4980-fad6-11e9-9005-74ecae153a9e.png)

**Comment by javjim** [comment]
Thanks, thats exactly what it needed. can I ask where did you find that info?

**Comment by rskrzypczak** [comment]
I checked the code :)
