### ISSUE TITLE
[bug] 5.2 - manual trigger on create entity (use of mapping) fails

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11856]
It says workflow executed but it not creating a record.
It also dont remember check box:
# Show tasks
# Enable deactivation tasks

Logs quiet

**Comment by sirwinston1** [comment]
any manual execution seems to be bugged right now.  I have to manual check each step in the workflow for it to actually work

**Comment by bpabiszczak** [comment]
No basic information in issue.
