### ISSUE TITLE
When marking ticket closed - enter resolution notes

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11853]
Hello Yetiforce friends,

When I mark the ticket closed, a window pops up asking me to enter some information. First i thought it was asking me to enter resolution notes, but instead, when i enter the notes and close the ticket, I can't even find those notes anywhere in that ticket. 

How can i edit that pop up window and put resolution notes field instead of that discrimination field? So that whenever i mark the ticket closed, it would ask me to enter resolution notes in that window. Seems to be a much more natural process.

**Comment by acoolov** [comment]
Anyone???????

**Comment by acoolov** [comment]
@mariuszkrzaczkowski @vovpff 
Is this possible to do?
When I close the ticket, a pop up window appears with a description field, which I don't know why is there. There should be a resolution field in the pop up window so I can enter resolution notes.

**Comment by vovpff** [comment]
Just rename Description to Resolution?

**Comment by acoolov** [comment]
Is it possible to edit the window that pops up when closing the ticket? 
I can edit the quick create window but I can't seem to edit the time control window that pops up when closing the ticket.

**Comment by mariuszkrzaczkowski** [comment]
which window are we talking about?  attach a screenshot

**Comment by acoolov** [comment]
When you close the ticket, a Time Control module pops up. It makes you fill out the time control for that ticket, but the ticket's resolution field ends up being just blank. How is it possible to fill out the resolution field during closing of the ticket?

**Comment by bpabiszczak** [comment]
no screenshots

**Comment by Anthony2244** [comment]
Hi all, first of all thanks for the great product. I'm facing the same issue, I will attach the video explaining what @acoolov was trying to say. Basically, we have a ticket, and we change ticket status to Accepted or To Close, or whatever status we set for ticket to be considered as closed. After that we are asked to input Time Control (if it wasn't already done), question is, Time Control opens in popup, can it be done that Ticket Solution opens in popup. Maybe in Edit view or Quick Edit?
[https://streamable.com/xfs7ip](url)

**Comment by acoolov** [comment]
Hello, is this being addressed? Can we streamline the ticket closing process so that when you close the ticket, there would be a resolution field available to fill out? This seems to be the most logical way to close out the ticket, instead of filling out time control. 

Please let me know. Thank you.

**Comment by yagobski** [comment]
Anyone have a resolution for that?

**Comment by mariuszkrzaczkowski** [comment]
everything can be done, propose a solution in a pull request and we will add it to the system
