### ISSUE TITLE
[Bug] Workflow has changed logic

### ISSUE THREAD

**Issue by Marshal4582** [YetiForceCompany/YetiForceCRM#11854]
When I use "Create entity" task and if I want to transfer picklist value from parent module to the related one, I can not do that as the only option is to select static value from picklist of parent module.
I believe before it was different and offered static and field value.
Can we have it back/fixed?

**Comment by waran70** [comment]
Agree... value from other field should be allowed. It is narrow bottleneck as messing between parent and sub record. Much more advanced wf are allowed, so maybe this should be too?

**Comment by bpabiszczak** [comment]
Good idea, you can order it for a fee!
