### ISSUE TITLE
[Question] How products and inventory work together

### ISSUE THREAD

**Issue by laportem** [YetiForceCompany/YetiForceCRM#11859]
### Description
We trying to evaluate if Yetiforce meets our crm + inventory requirements. We understand the documentation is not a priority right now, but can you shed some light on how the product module works. 

This is on the gitdeveloper demo instance

If I create a Product record, the **“Product quantity”** and **“Qty/Unit”** fields are always read-only. I presumed these two values are aggregated from some other related module(s).

Which Module(s), Which field(s)?

I was assuming from the “Storage” module, but the Product record do not have related “Storage” records.

I would greatly appreciate if you can shed some light on how the product and inventory modules works and how they link together.

Our requirement is simple. We have a Product called “Pineapples” – On a regular basic Vendors will upload line items against the Pineapples Product. Each line item includes the vendor name, the pineapples variety, the quantity, and the sell price. We then want the “Product quantity” to get updated based from the aggregated Line Item’s quantity.

**Comment by vovpff** [comment]
At first you need to add 1 ore more storages. After that you need to add related to storage GRN to increase or GDN to decrease product quantity

**Comment by vovpff** [comment]
At first you need to add 1 ore more storages. After that you need to add related to storage GRN to increase or GDN to decrease product quantity

**Comment by jmginfor** [comment]
> At first you need to add 1 ore more storages. After that you need to add related to storage GRN to increase or GDN to decrease product quantity

What mean GRN or GDN ???

**Comment by vovpff** [comment]
@jmginfor Goods Received Note and Goods Dispatched Note

**Comment by samuelsituma** [comment]
@vovpff  can we remove the GRN and GND its time consuming and makes it hard for someone to update the product quantity , When a product is sold the system should update automatically instead of someone filling GDN again.

**Comment by vovpff** [comment]
@samuelsituma You can do every thing what you want. But you need to understand your task isn't easy process like uncheking checkbox, you need to change system core files and this affects to whole system. This can be big fault.

Other bad thing: system update will overwrite your modifications
