### ISSUE TITLE
Sending email to leads 

### ISSUE THREAD

**Issue by rcrrich** [YetiForceCompany/YetiForceCRM#1185]
I can't seem to send emails to leads. To me a lead is someone that I want to introduce to my products and invite them to take a look at my shopping cart or whatever I want to ask a lead. But I can't seem to do that when I select a lead to send an email to and select an internal doc the doc has nothing in it. But when I look at the doc in documents it is there?? But when I try to send the email it shows 0 bits? Where did it go.

**Comment by rcrrich** [comment]
Hmmm, guess I am waisting my time on this question, I will do it another way then just copy and paste after getting lead emails thanks anyway.

**Comment by rcrrich** [comment]
![docsblank fw](https://cloud.githubusercontent.com/assets/12788182/8394801/3f7acc04-1d17-11e5-9c60-a93a4cae60ab.png)

**Comment by rcrrich** [comment]
as you can see when I trying to send an email all the docs are 0 B yet when you look at them all the info is there under docs. It is nice to have many things to use but it also very up setting to have so many things i can't make work right.

**Comment by mariuszkrzaczkowski** [comment]
I tested on the latest version and I do not see this error.
Install the latest version and check it or you can test here:
https://gitmaster.yetiforce.com/

**Comment by rcrrich** [comment]
I just downloaded the latest version of the whole script, on the 29th the problem is when you create a doc it is there I can see it, Now when I go into the email program and go to the compose an email section and select a file from the CRM the files all show up as 0 B If I upload a doc to the system first you see the file and the bites in the file and if you select it you get an attachment only you can't do anything else with it. Seems to me you should be able to add the upload doc to the email and even edit it their. Anyway all I can do is go to the doc area in the script and highlight the text then paste the text into the email.

**Comment by rcrrich** [comment]
By the way not sure how you were able to preform the same thing when there are no doc in your https://gitmaster.yetiforce.com/ script.

**Comment by rcrrich** [comment]
This still  is notworking show me where it is working?? I don't see it 

![image](https://cloud.githubusercontent.com/assets/12788182/8487522/91c2a8a8-20da-11e5-95f6-bdc9aafdc485.png)

**Comment by rcrrich** [comment]
Here is the doc I want in the doc area: As you can see the file is there but not when I select it to send in a email.

![image](https://cloud.githubusercontent.com/assets/12788182/8487551/d6752c50-20da-11e5-9217-9ca9e92494b3.png)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
please describe it one more time because we don't know what is the major problem here. 
Please provide a step-by-step description of what you do and explain what is wrong. Then, writie how it should work in your opinion. Screenshots would be very helpful and if you could test for the problem on our tesing version and provide a link that would be best :)

**Comment by rcrrich** [comment]
it seems I can't explain myself very good here. When you have a lead and want to send that lead an email in your email program the email program comes up with the lead email that you wish to send to, but if you have a saved doc in the yeti system and choose that doc to add in the email in the body of the email all doc chosen this way are BLANK there is nothing in the doc. BUT when you look at the doc in the doc area of the yeti system it is there the whole doc you can read it change the info etc etc but when you from your email program select that doc to add to the body of the email it is blank and even above shows blank meaning there is nothing in the doc it shows 0bits as you can see. SO why is this happening in the first place. WHen I select a doc to be added to the email body it should be also showing up to select for the email I am sending out. BUt it is empty with 0 bits blank nothing in it totally empty no txt no no nothing in it. So when I am trying to send an email to a lead or who ever and choose a document all the info that is in the document should also be able to be added to the body of the email and then send to the lead or who ever I wish to. This is a file from the CRM that I should above but again it is blank when you select it from the email program but not blank when you are in the document area of yeti all info is there. I sure hope you understand this please!

**Comment by bpabiszczak** [comment]
I don't understand which problem you describe:

1. Uploading of attachments from Documents to Mailbox doesn't work properly OR

2. It doesn't attach the content of a document [which doesn't have an attachment but it only has content].

If it's no. 1, we haven't noticed such a problem, you need to describe it step-by-step what we need to do to see it on our testing servers.

If it's no. 2, we will add such a possibility in the future, but it won't be sooner than in 2.3.

**Comment by rcrrich** [comment]
So in other words if I want to contact a lead by email in the system I have to manually add the text the body of the email. So what I have to do is either have a document on my computer at the office to copy and paste the body of the email then I have to add the leads name to that email that I am sending one at a time because there is no way to have a doc file on the system to add to the body of the email I am sending out. So really what I need to do is now have another email newsletter program that will do these things for me. So really this is not a contact management program but a invoicing program that doesn't do much to help me get new customers from leads oh yes it does, one at a time I can send out an email paste and add the name of the lead to the email and the 300 leads I have will take me months to send out. 
By the way I am not attaching anything to the email I simply want a way to be able to send mass emails to the leads in the system by selecting a file that has content already setup by me that I can even put your shortcodes in like the first name of the lead so as to say Hello jeff, or Hi Sam, By the way have to taken a look at our site lately we now have such and such etc etc I know your will love this...... so that I can send out to all the leads telling them what i have to offer them and every week or so send them specials until them buy from me. Now if I upload a file all your system does is put that as an attchment to the email. Not in the body. If I look at the crm files in the email program they are all blank when you try to open them in the email program. anyway I sure you still have no idea what i want 

Yes no 2 but not attach but add to the body of the email. Or I will just keep copy and paste and add the name of the contact to each email until I tind a better way
Have a nice day.... later!

**Comment by bpabiszczak** [comment]
The sarcasm was completely unnecessary. There are many options to automatize sending mails in the system.

There are e-mail templates that can adjust to every record independently. Therefore in my opinion you shouldn't use the documents module but rather the template module.

You can attach a file and send it to hundreds different addresses, adding them to BCC

You can use workflow to automatically send e-mails together with the attachments

Your idea of not attaching the file, but instead adding it to the body of the message did not convince me, because this is what e-mail templates are used for! Of course, it would be good to add the possibility of generating a PDF file and automatically attaching it in the e-mail, but it is an additional functionality we will deal with in 2.2 or 2.3 version.
