### ISSUE TITLE
[Question] Workflow in scheduler starts but never ends

### ISSUE THREAD

**Issue by Marshal4582** [YetiForceCompany/YetiForceCRM#11855]
Workflow in scheduler starts but never ends. What are the most common issues with that?

**Comment by waran70** [comment]
Some workflow may be invalid and it stops on it but it shouldn't

**Comment by aleterracciano** [comment]
Salve, riscontro lo stesso problema con il workflow in scheduler. Termine ultima esecuzione, 6 mesi fa. Allego screenshot. 
**(Italian translate)**

Hi, I'm having the same problem with the workflow in scheduler. Last execution deadline, 6 months ago. I attach screenshots. 
**(English translate)**

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/53528784/c4d076e9-1be1-4369-a211-6db4b14f2c16)

Allego configurazione del sistema

![ConfReport (11)](https://github.com/YetiForceCompany/YetiForceCRM/assets/53528784/f7d7b8e3-2b64-4ba6-89c1-92d2050d407d)

**Comment by aleterracciano** [comment]
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/53528784/ed541317-c0b8-4388-9759-ab4fd9482c57)
 dopo un po' diventa così!

**Comment by aleterracciano** [comment]
Ho creato un nuovo caso quì: https://github.com/YetiForceCompany/YetiForceCRM/issues/17325
