### ISSUE TITLE
backup page is missing

### ISSUE THREAD

**Issue by rcrrich** [YetiForceCompany/YetiForceCRM#1186]
When I go to back up nothing happens??? Just a blank page

**Comment by bpabiszczak** [comment]
I need more info:
1. yetiforce version? 
2. Please check here: https://gitmaster.yetiforce.com/ [admin/admin]

**Comment by rcrrich** [comment]
$patch_version = '20150616';  
$YetiForce_current_version = '2.0.132';
$_SESSION['yetiforce_version'] = $YetiForce_current_version;

I click on security and then backup and there is nothing there to enable a backup You can see the left side bar you can see the header and top menu but when the backup info is it is blank. You do not see this on the page:
 Backup creating   Logs  FTP settings General settings

**Comment by rcrrich** [comment]
![backup fw](https://cloud.githubusercontent.com/assets/12788182/8394628/2c5bd2dc-1d10-11e5-950f-cf4907d4e356.png)

**Comment by rcrrich** [comment]
also above in photo if you look close around where my logo is you will see some text links very very faint in background these are links showing up and you can click on them. I don't think that is correct

**Comment by mariuszkrzaczkowski** [comment]
Check for the latest version,
This module was rebuilt.
https://gitmaster.yetiforce.com/index.php?parent=Settings&module=BackUp&view=Index&block=7&fieldid=64

**Comment by rcrrich** [comment]
are you saying add the full yetiforcecrm system over again??? I tried just the update to the update system but that does nothing at all to the page I showed above. It would be nice to have away to do updates to the system with out having to start over again. You know like click this file add to the update section in your script and in just a few seconds the update is done to the area you need fixed. Also this github is one of the hardest things to understand I mean like just above you give me a link to your version of the program. Showing me that yours works, that does nothing for me and i can see you are all high end programmers and have no idea how to show end users things. I guess from all the 35 years i have been in computers it never changes. You all do things at a programmer lever and think everyone is on the same level. Well as always I have to do everything on my own the hard way. I have no idea how to import updates as I have tried and all I get is that the update is not in my native language and won't update.

**Comment by florek41** [comment]
Look at this https://yetiforce.com/en/administrator-documentation/updates/176-system-update-not-verified.html
This is guide how to updades works in YF.

You can only update (with easy way) official releases https://github.com/YetiForceCompany/YetiForceCRM/releases
