### ISSUE TITLE
[Question] How do I edit advanced block style in quote template?

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11864]
Hello friends,

I'm trying to create a nice quote template in Yetiforce, got the header working, got the created by, valid until part showing all correctly and nicely, but as soon as I paste the advanced block variable to show all the line items in the quote, it just shows an ugly looking, badly formatted block with line items in my pdf template. 

Is there any way to change style formatting of the advanced block?

If not, the quote functionality in YetiForce is DEFINITELY not finished.

Also, is there any ready to use, nice looking quote template for YetiForce?

**Comment by vovpff** [comment]
This is some kind of problem with PDF module... You are welcome

**Comment by acoolov** [comment]
How is this CRM being advertised as finished then if the very essential module QUOTES does not work?

**Comment by vovpff** [comment]
Quotes module works well. Promblem in pdf export

**Comment by acoolov** [comment]
Vladimir, do you also know if the quotes have the ability to group line items into different groups on the same quote? I haven't found this functionality anywhere in the quote.

**Comment by vovpff** [comment]
There is no this functionality available in system

**Comment by acoolov** [comment]
Unfortunately this changes everything for us. We are a growing company and we like this crm, but without the ability to group line items in the quote (very essential quote functionality for any crm) we won't be able to use it.
