### ISSUE TITLE
PDF ? BUG

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#1187]
W wersji stabilnej 2.0 niestety istnieje problem z modułem PDF.... natomiast w bieżącej do pobrania niestety rozsypane jest wszystko..

**Comment by bpabiszczak** [comment]
Eksportowanie do PDF było poprawione np. tutaj: 71b6e9d i https://github.com/YetiForceCompany/YetiForceCRM/commit/9ff9c7d4c64863364d51ac898f5eaed12d954f4a, można jeszcze poszukać w pozostałych issues. 

Obecnie są dwie wersje testowe: 
Master: https://gitmaster.yetiforce.com/
Developer: https://gitdeveloper.yetiforce.com/index.php

Wygląd można sprawdzić na wersji developer, bo czeka tam na wgranie dziesiątki rewizji [zostaną na master wgrane w poniedziałek]. 

Jeżeli są jakieś błędy z aktualną wersją proszę je zgłaszać [jeden błąd jeden issue], to nam pozwoli szybciej zamknąć wersje 2.1. 

Aktualna zmiana wyglądu i liczne błędy z wyglądem są spowodowane migracją do nowszej biblioteki bootstrap, która nie była uaktualniana od 2 lat. Planujemy wydać wersje stabilną [2.1] w przeciągu dwóch tygodni.

**Comment by bpabiszczak** [comment]
I jedna prośba, z Twojego zgłoszenia nic nie wynika, nie wiadomo co jest błędem, gdzie go wywołać itd. Proszę, abyś zapoznał się z tymi dwoma dokumentami: 
https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html
https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/109-debugowanie.html
