### ISSUE TITLE
[Question] How to sync txt field and picklist

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11874]
It was touched in separate issue, but I will refactor way of understanding.
So... how can we update picklist with txt field and vice versa in the same module?
Worflows limiting such by not giving option to use field value, but only picklist items.

Cheers

**Comment by vovpff** [comment]
@waran70 you can write handler for this

**Comment by waran70** [comment]
Much more advanced workflows tasks are in place. I would think why not so basic-obvious one?

**Comment by bpabiszczak** [comment]
This functionality is not available by default.
