### ISSUE TITLE
Import... oferty , zamówienia

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#1188]
Witam, czy jest jakaś szansa na import OFERT i ZAMÓWIEŃ Z csv ? z PRODUKTAMI I KONTRAHENTAMI NIE MA PROBLEMU - NIESTETY TAK SAMO NA OSTSTNIEJ WERSJI vTIGERA - NIE DZIAŁA IMPORT TYCH POZYCJI- a nie mogę doszukać się przyczyny . W wersji trial vTIGER W CHMURZE bez problemu importuje. Problem istnieje także w na wersji demo Yeti. Czy jest jakakoliwek szansa na udany import ? Czy pozostaje grzebanie w bazie...

**Comment by bpabiszczak** [comment]
Ale z czego do czego ma nastąpić ten import? Z Vtiger do YetiForce, czy z Vtiger do Vtiger czy z YetiForce do YetiForce czy możesz jeszcze coś innego?

**Comment by zimart** [comment]
Nie działa w żadej konfiguracji.. :) ani z Vtigera ani z YETI do YETI :) kręci sie w kółko , nawet przy tescie 1 oferty.

**Comment by bpabiszczak** [comment]
Sprawdzimy to wkrótce i dam informacje zwrotną.

**Comment by zimart** [comment]
Nie udalo się zerknąć... jaka może byc przyczyna problemu ... ?

**Comment by bpabiszczak** [comment]
Programista sprawdzał na wersji 6.3.0 i podobno działa, w tym tygodniu będziemy jeszcze u nas sprawdzali błąd.

**Comment by zimart** [comment]
sprawdziłem też na 6.3 - działa. Czy jest szansa za podjęcie działań w tym kierunku ?? Chętnie bym już się przesiadł na YETI - ale bez możliwości importu raczej nie mam szans :(

**Comment by MaciejStencel** [comment]
Witam,

Wprowadzono poprawki do kodu. Teraz można importować rekordy z produktami.
Może Pan przetestować na https://gitdeveloper.yetiforce.com/index.php.

Z tym że proszę mieć na uwadze, że jak chce Pan importować rekordy z innego systemu CRM. To najlepiej systemem kaskadowym tak importować rekordy z modułów najmniej zależnych do najwięcej. Chodzi o to że jak np. importuje Pan Oferty, to żeby wcześniej były np. zaimportowane Szanse sprzedaże, jako że są one powiązane z Ofertami. 

Mechanizm importu jeśli nie znajdzie powiązanego rekordu po etykiecie to tworzy go na nowo korzystając z jedynej informacji jaką posiada czyli samą nazwę rekordu.

Wyjątek to produkty i usługi, one muszą być wcześniej zaimportowane. Tak samo działa to w vtiger 6.3.

Proszę o przetestowanie i informację czy wszystko jest już dobrze, a jak nie to proszę o dokłądną informację co jeszcze nie działa a będzie to poprawione dalej.

**Comment by zimart** [comment]
ostatnia wersja na gITHUBIE ?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer

**Comment by bpabiszczak** [comment]
Ta: https://gitdeveloper.yetiforce.com/index.php
Czyli ta: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer
Czyli oficjalnie pojawi się w aktualizacji do wersji 2.1

**Comment by zimart** [comment]
Dziekuję :) testuję
