### ISSUE TITLE
[Question] Grouping line items in the quote?

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11881]
Is it possible to group line items, and have multiple groups of items in the same quote?

It is very important feature for any basic CRM.

**Comment by acoolov** [comment]
The support for this project is almost dead. 
And unfortunately I found out that there is not grouping of items in a quote in Yetiforce, so we won't be able to use it in our environment. Unless this feature is created.

**Comment by z0lo13** [comment]
if you are looking for dedicated support purchase it from yeti shop.

**Comment by acoolov** [comment]
They can't even tell me if this feature is possible to create or not. I can't pay for something that they can't promise they can do. Once i know it is possible i can pay for it.

**Comment by vovpff** [comment]
Is it possible to create anything. If you have programming skills you can doi it by yourself. If not - you need to pay for yeti crew or somebody else
