### ISSUE TITLE
[bug][5.2.42][Default mandatory field] Does not work like a text type field

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#11880]
# 🐞 bug report

### ⁉️ Describe the bug

I create a new module (when you create a new module it creates a mandatory text field too).
When I edit the default field of a record from 0.4 to 0.40 it does not detect changes so it does not save the new value (0.40).

### 🔥 How to trigger the error

![2019-10-29_11-11-34](https://user-images.githubusercontent.com/16593721/67762855-455ab680-fa3e-11e9-82c3-511f88aab44b.gif)

I think the problem is there because `$this->getPreviousValue()` is empty:
https://github.com/YetiForceCompany/YetiForceCRM/blob/acc6528abd051703737e0fc94e071058975f9916/modules/Vtiger/models/Record.php#L462

### 👎 Actual Behavior

Does not save the new value

### 👍 Expected Behavior
Save the new value because in my case we need to write on this field text or numbers but in the case of numbers it can be with zeros at the end.

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | Google chrome		|
| Operating System (name and version)  | Windows 10		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/74113542-2cb57d00-4ba5-11ea-9fc5-851c49a4ad3b.png)

Works on gitdeveloper.

**Comment by MacarenaReina** [comment]
I have just test it on gitdeveloper and it does not work. If you reload the view disappear the last zero.

![2020-02-19_08-46-04](https://user-images.githubusercontent.com/16593721/74817168-62204000-52f4-11ea-8eca-e9a652fe1847.gif)

I think it's a problem with the use of trim in some function, because it removes final zeros too.
