### ISSUE TITLE
[Feature] Please take this one seriously

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11906]
Ability to group line items into different groups with different sub totals on the same quote. 
This one is absolutely essential for almost any company. This is a huge turn off for us because there is no way to group different sub totals in the same quote. There is no way to show the customer an organized way of what we propose to them. Just a bunch of line items and a total at the end. This is not good. 

Is this possible to integrate? If yes, then our company is going to move to Yetiforce and you guys will earn a life customer.

**Comment by mariuszkrzaczkowski** [comment]
check Product bundles
https://gitdeveloper.yetiforce.com/index.php?module=Products&relatedModule=Products&view=Detail&record=568&mode=showRelatedList&tab_label=Product%20Bundles&tab_label=Product%20Bundles

**Comment by acoolov** [comment]
I understand you guys provide support bundles, but noone has still answered if you guys can indeed implement this feature for us. If yes, can it be a flat price? We can't just pay for something we don't know is possible to do, and we don't know how many hours it will take you support guys to do it. 

Please let me know.

**Comment by bpabiszczak** [comment]
4.000 EUR Netto
