### ISSUE TITLE
can't convert leads to accounts

### ISSUE THREAD

**Issue by ohandy1** [YetiForceCompany/YetiForceCRM#11909]
It seems I deleted the "for conversion" status in Leads picklist. I've figured out I needed this status to enable the lead conversion to Account. I'm running 5.1 and looking for the easiest way to repair this, any help out there?  **adding the status back into the picklist doesn't enable the conversion icon.

Sorry about the messed up first attempt at this question

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=MarketingProcesses&view=Index&parent=Settings&block=6&fieldid=83
![image](https://user-images.githubusercontent.com/10198654/67860101-5af2dd80-fb1d-11e9-9c17-89e87f625047.png)
