### ISSUE TITLE
Can not delete custom block[bug] 

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#11914]
I have made a custom block in the contact section and have three fields in there. I want to delete the custom block and I am unable to delete. It asks am I sure I want to delete I say yes and nothing happens.

Still there

Is there a step that I am missing

Please let  me know

Cheers

**Comment by guide5232** [comment]
Firstly you have to move that three fields to another block or delete three fields then only  you are able to delete block.
