### ISSUE TITLE
Conditional or smart  Fields - Is it  Possible

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#11915]
I would like to know if it's possible for Yeti to have smart fields or conditional fields for example

If one field if the answer is no in the checkbox nothing shows but if they choose yes then more options appear that allows me to gather more information.

Please let me know if this is possible

Cheers

**Comment by bpabiszczak** [comment]
Maybe that's enough: Software configuration > Standard modules > Fields – Picklists/Relations
