### ISSUE TITLE
[Question] CalDAV sync, how to rename calendar ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#11923]
Hi,

By default, when you sync calendar using CalDAV, it appears as YFCalendar.
How do I rename it to reflect my company name or else ?
It looks like it's defined in the following file :
YetiForceCRM/modules/API/models/CalDAV.php
`const CALENDAR_NAME = 'YFCalendar';`

I may rename it here but AFAIK, it will be lost on the next update.
It could be useful to add an option to define calendar name from admin panel.
Regards,

**Comment by mariuszkrzaczkowski** [comment]
We do not recommend such a change, maybe in the future we will add it to the panel
