### ISSUE TITLE
[bug] [5.2.48] "Module=Users", "Action=Record" returns "Record doesn't exist"

### ISSUE THREAD

**Issue by Sasamous** [YetiForceCompany/YetiForceCRM#11921]
# 🐞 bug report

### ⁉️ Describe the bug

When I try to get User details I get this error
```
{
	"status": 0,
	"error": {
		"message": "Record doesn't exist",
		"code": 404,
		"backtrace": "#0 api/webservice/Portal/BaseModule/Record.php (51)  >>  Api\\Core\\Exception->__construct('Record doesn\\'t exist',404)\n#1 api/webservice/Core/BaseAction.php (28)  >>  Api\\Portal\\BaseModule\\Record->checkPermission()\n#2 api/webservice/Controller.php (87)  >>  Api\\Core\\BaseAction->checkAction()\n#3 webservice.php (15)  >>  Api\\Controller->process()\n#4 public_html/webservice.php (11)  >>  require('webservice.php')"
	}
}
```

### 🔥 How to trigger the error

1. Call `https://gitdeveloper.yetiforce.com/webservice.php?module=Users&action=RecordsList`, it returns: 
```
{
	"status": 1,
	"result": {
		"headers": [],
		"records": {
			"1": {
				"recordLabel": "YetiForce Sp. z o.o. "
			},
			"5": {
				"recordLabel": null
			},
			"6": {
				"recordLabel": null
			},
			"7": {
				"recordLabel": null
			},
			"8": {
				"recordLabel": null
			}
		},
		"rawData": [],
		"count": 5,
		"isMorePages": false
	}
}
```
So record "1" exists.

2. Call `https://gitdeveloper.yetiforce.com/webservice.php?module=Users&action=Record&record=1` it returns: 
```
{
	"status": 0,
	"error": {
		"message": "Record doesn't exist",
		"code": 404,
		"backtrace": "#0 api/webservice/Portal/BaseModule/Record.php (51)  >>  Api\\Core\\Exception->__construct('Record doesn\\'t exist',404)\n#1 api/webservice/Core/BaseAction.php (28)  >>  Api\\Portal\\BaseModule\\Record->checkPermission()\n#2 api/webservice/Controller.php (87)  >>  Api\\Core\\BaseAction->checkAction()\n#3 webservice.php (15)  >>  Api\\Controller->process()\n#4 public_html/webservice.php (11)  >>  require('webservice.php')"
	}
}
```

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by Sasamous** [comment]
Still nothing in 5.2.50

**Comment by rskrzypczak** [comment]
We can't talk about an error in this case.
Users don't have standard entries in the CRM. 
You shouldn't be able to download other users' data from the client portal.

**Comment by Sasamous** [comment]
Even if I use administrator user based permissions?

**Comment by Sasamous** [comment]
If I want to put a new record in YetiForce from API, I must specify an "Assigned To: (User)", if I can't get this information, I can't put records on YF, so I can't sync values between an ERP system and YF, how can I solve this problem? @rskrzypczak @mariuszkrzaczkowski

**Comment by Sasamous** [comment]
I waited a week, can't I get more answers?

**Comment by bpabiszczak** [comment]
You got the answer but you don't understand how the permissions in the client portal work.

**Comment by mariuszkrzaczkowski** [comment]
check this https://github.com/YetiForceCompany/YetiForceCRM/commit/cc3b6b3fc24258e845ef655b3188b5cb1cd6dda8 https://github.com/YetiForceCompany/YetiForceCRM/commit/681a65252c0be733ecc51fa1f0c5bf84b76dc7b7 

https://doc.yetiforce.com/api/#/Users
