### ISSUE TITLE
[Question] Is it possible to define read-only access for DAV Users.

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#11925]
### Describe the solution you'd like

It would be great to have a function to define Read-only or Write access for DAV users, without this feature it is not good to give access to edit the company calendar for basic employees.

### Describe alternatives you've considered

Was not able to find any alternative
### Additional context

in sabre-dav library i see the read-only property how we can enable it for dav ?

**Comment by mariuszkrzaczkowski** [comment]
How did you solve the problem?
http://sabre.io/dav/caldav-proxy/
