### ISSUE TITLE
[Question] Softaculous install -> intl not found

### ISSUE THREAD

**Issue by tfegyo** [YetiForceCompany/YetiForceCRM#11924]
I'm trying to install Yetiforce 5.2 in a Softaculous environment.

Php version is 7.2.23
Intl is enabled, more precisely phpinfo() outputs are here:
 - Intl - 
Internationalization support enabled
- version 1.1.0
- ICU version 50.1.2
- ICU Data version 50.1
- ICU TZData version 2012j
- ICU Unicode version 6.2

Still during the installation the following errors were found, therefore I cannot install the software:
"Required PHP extension not found : intl"

What did I miss?
I cannot install or modify php settings myself, only the system admin has rights to do it. So I have to specify the task precisely.

**Comment by bpabiszczak** [comment]
https://stackoverflow.com/questions/33869521/how-can-i-enable-php-extension-intl

PS.: Ask on softaculous forum.
