### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by ashelshark** [YetiForceCompany/YetiForceCRM#11926]
What do I need to do to get rid of this error message. I can not configure the modules right now. access is recstricted. It occured after I have unticked most of the modules. See also screenshot.

![Bildschirmfoto 2019-11-01 um 11 02 41](https://user-images.githubusercontent.com/57219684/68017619-68cc6e00-fc97-11e9-9cd5-a5e54f079d0e.png)

**Comment by ashelshark** [comment]
Please consider that I am not a programmer. So I hope this can be resolved without programming knowledge.

**Comment by mariuszkrzaczkowski** [comment]
check the logs

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/68021655-5efc3800-fca2-11e9-883c-20cb5ef52c0e.jpg)

**Comment by calvinsug** [comment]
Hi, do you manage to run YetiForce in Localhost? or do you implement it at hosting ?

**Comment by ashelshark** [comment]
Local host.

Am 02.11.2019 08:41 schrieb Calvin Sugianto <notifications@github.com>:

Hi, do you manage to run YetiForce in Localhost? or do you implement it at hosting ?

**Comment by calvinsug** [comment]
oh nice, i also want to try to implement it in localhost.

Did you encounter this error after finished installation ?
"Class '\App\YetiForce\Shop\Product._YetiForceInstallInCloud' not found"

as you can see the screenshoot here below:
https://drive.google.com/open?id=1RW5VViGsltj2lW4JRm6AMIBTKneUtJiX

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/debugging

**Comment by leopardb** [comment]
Hi Mariusz,

I will take it from here.
ashelshark disable some module (possibly "My mailbox") and since then, he gets the error message posted in the first comment.

After enabling debugging, I could reach this:
`2019-11-06 12:24:31.7939 [error] - Call to a member function get() on bool
Error: Call to a member function get() on bool in /srv/crm/modules/OSSMailView/models/Module.php:19
Stack trace:
#0 /srv/crm/cache/templates_c/basic/bc0e01607c15a3bd573fba393f89a921d33fd496_0.file.ListContents.tpl.php(66): OSSMailView_Module_Model->getSettingLinks()
#1 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5dbbfa7ba32125_25115911(Object(Smarty_Internal_Template))
#2 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#5 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#6 /srv/crm/include/runtime/Viewer.php(204): Smarty_Internal_TemplateBase->fetch('modules/Setting...')
#7 /srv/crm/modules/Settings/ModuleManager/views/List.php(30): Vtiger_Viewer->view('ListContents.tp...', 'Settings:Module...', true)
#8 /srv/crm/include/main/WebUI.php(182): Settings_ModuleManager_List_View->process(Object(App\Request))
#9 /srv/crm/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#10 /srv/crm/public_html/index.php(11): require('/srv/crm/index....')
#11 {main}`

I would re-enable the module, but the interface won't let me do it.
Is the setting about enabled modules in the SQL DB or in a php file ?

thanks in advance for your answer :)

**Comment by ashelshark** [comment]
Dear Mariusz,

a while ago my clleague wrote the folloiwng. Can you please answer:

Hi Mariusz,

I will take it from here.
ashelshark disabled some module (possibly "My mailbox") and since then, he gets the error message posted in the first comment.

After enabling debugging, I could reach this:

2019-11-06 12:24:31.7939 [error] - Call to a member function get() on bool
Error: Call to a member function get() on bool in /srv/crm/modules/OSSMailView/models/Module.php:19
Stack trace:
#0 /srv/crm/cache/templates_c/basic/bc0e01607c15a3bd573fba393f89a921d33fd496_0.file.ListContents.tpl.php(66): OSSMailView_Module_Model->getSettingLinks()
#1 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5dbbfa7ba32125_25115911(Object(Smarty_Internal_Template))
#2 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#5 /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#6 /srv/crm/include/runtime/Viewer.php(204): Smarty_Internal_TemplateBase->fetch('modules/Setting...')
#7 /srv/crm/modules/Settings/ModuleManager/views/List.php(30): Vtiger_Viewer->view('ListContents.tp...', 'Settings:Module...', true)
#8 /srv/crm/include/main/WebUI.php(182): Settings_ModuleManager_List_View->process(Object(App\Request))
#9 /srv/crm/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#10 /srv/crm/public_html/index.php(11): require('/srv/crm/index....')
#11 {main}

I would re-enable the module, but the interface won't let me do it.
Is the setting about enabled modules in the SQL DB or in a php file ?

thanks in advance for your answer :)

**Comment by ashelshark** [comment]
Dear Mariusz,
a while ago my clleague wrote the folloiwng. Can you please answer:
Hi Mariusz,
I will take it from here.
ashelshark disabled some module (possibly "My mailbox") and since then, he gets the error message posted in the first comment.
After enabling debugging, I could reach this:
2019-11-06 12:24:31.7939 [error] - Call to a member function get() on bool
Error: Call to a member function get() on bool in /srv/crm/modules/OSSMailView/models/Module.php:19
Stack trace:
#0 /srv/crm/cache/templates_c/basic/bc0e01607c15a3bd573fba393f89a921d33fd496_0.file.ListContents.tpl.php(66): OSSMailView_Module_Model->getSettingLinks()
#1<https://github.com/YetiForceCompany/YetiForceCRM/issues/1> /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5dbbfa7ba32125_25115911(Object(Smarty_Internal_Template))
#2<https://github.com/YetiForceCompany/YetiForceCRM/issues/2> /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3<https://github.com/YetiForceCompany/YetiForceCRM/issues/3> /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4<https://github.com/YetiForceCompany/YetiForceCRM/issues/4> /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#5<https://github.com/YetiForceCompany/YetiForceCRM/issues/5> /srv/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#6<https://github.com/YetiForceCompany/YetiForceCRM/issues/6> /srv/crm/include/runtime/Viewer.php(204): Smarty_Internal_TemplateBase->fetch('modules/Setting...')
#7<https://github.com/YetiForceCompany/YetiForceCRM/issues/7> /srv/crm/modules/Settings/ModuleManager/views/List.php(30): Vtiger_Viewer->view('ListContents.tp...', 'Settings:Module...', true)
#8<https://github.com/YetiForceCompany/YetiForceCRM/issues/8> /srv/crm/include/main/WebUI.php(182): Settings_ModuleManager_List_View->process(Object(App\Request))
#9<https://github.com/YetiForceCompany/YetiForceCRM/issues/9> /srv/crm/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#10<https://github.com/YetiForceCompany/YetiForceCRM/issues/10> /srv/crm/public_html/index.php(11): require('/srv/crm/index....')
#11<https://github.com/YetiForceCompany/YetiForceCRM/issues/11> {main}
I would re-enable the module, but the interface won't let me do it.
Is the setting about enabled modules in the SQL DB or in a php file ?
thanks in advance for your answer :)


Mit freundlichen Grüssen,
Best regards,

--
Ashraf El Sharkawy - COO

TAMSCHICK MEDIA+SPACE GmbH
Bülowstr. 66, 10783 Berlin

Phone: +49 (0) 30 219 650 9-15
Fax:          +49 (0) 30 219 650 9-29

Mail: ashraf@tamschick.com<mailto:ashraf@tamschick.com>
Online: www.tamschick.com<http://www.tamschick.com/>

Geschäftsführer: Marc Tamschick

USt-Id Nr. DE 256698956
Steuernummer: 29/554/32063
Handelsregister: Berlin-Charlottenburg HRB 109850

----------------------------------------

Weitere Infos über Projekte, Neuigkeiten und Events gibt es in unserem Newsletter.
Hier<http://tamschick.com/newsletterform/html/index.html> geht’s zum Eintragen!

More information about our projects, news and events can be found in our newsletter.
Click here<http://tamschick.com/newsletterform/html/index.html> to register!

----------------------------------------

Diese Email einschließlich ihrer Anhänge ist vertraulich. Wir bitten eine fehlgeleitete Email unverzüglich vollständig zu löschen und uns eine Nachricht zukommen zu lassen.
Außerdem: Wir lieben Bäume. Bitte diese Mail nur ausdrucken wenn unbedingt notwendig.

This email and its attachments are confidential. If you are not the intended recipient of this email message, please delete it immediately and inform us accordingly.
Also, we do love trees. Please do not print this email unless it is absolutely necessary.



Von: Mariusz Krzaczkowski <notifications@github.com>
Antworten an: YetiForceCompany/YetiForceCRM <reply@reply.github.com>
Datum: Sonntag, 3. November 2019 um 18:42
An: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
Cc: Ashraf El Sharkawy <ashraf@tamschick.com>, Author <author@noreply.github.com>
Betreff: Re: [YetiForceCompany/YetiForceCRM] Error Message (#11926)


https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/debugging

**Comment by bpabiszczak** [comment]
This must be checked by the programmer.

**Comment by rskrzypczak** [comment]
solution: https://github.com/YetiForceCompany/YetiForceCRM/issues/12082#issuecomment-561496658
