### ISSUE TITLE
[Question] how to create a pdf from selected records on Calendar ? 

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#11937]
Hi there company! 😄

I have a question: I have created 4 records on Calendar. http://prntscr.com/prxl7m
i want to filter some of them records and export a pdf file. Now i select 2 records and it exports all of them . Or i can export selected records and it creates one page per record. i want all selected records in one page. (ex if i export 80 records it will create 80 pages. It is not convinient )

Is it possible to export all together in one or two pages?

Thank you !

**Comment by bpabiszczak** [comment]
Check on https://gitdeveloper.yetiforce.com/ this 2 functions:

![image](https://user-images.githubusercontent.com/10197525/73988617-828aea80-4943-11ea-9b83-79209a93b6e1.png)

**Comment by TonyM15** [comment]
bpabiszczak can you spend 1 min and try it yourself? I created template called "List selected contacts"
You cannot print report of selected records mate!

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/74094128-55257480-4adc-11ea-9d88-9fc627179e4e.png)

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/74094135-74240680-4adc-11ea-9d6b-706aab94cd5e.png)

**Comment by s2b-git** [comment]
How to print image with use of $(custom : RecordsList)$? Currently output is filename only
BEst

**Comment by aleterracciano** [comment]
Ciao, ho lo stesso identico problema ma non riesco a risolvere.
Ho inserito la funzione $(custom : RecordsList)$, ma non funziona. Quando provo ad esportare il PDF, Yetiforce mi restituisce il seguente errore.
Errore: Call to undefined method YetiForcePDF\Layout\TableBox::getRowSpan()

Se inserisco la funzione "$(recordsList : Calendar)$", esporto tutte le attività del calendario. Ho la versione Yetiforce 6.3.0.

Come posso risolvere?

-------------------------------------Translate to English

Hi, I have the exact same problem but I can't solve it. I have inserted the $(custom : RecordsList)$ function, but it doesn't work. When I try to export the PDF, YetiForce returns the following error:
Error: Call to undefined method YetiForcePDF\Layout\TableBox::getRowSpan()

If I insert the "$(recordsList : Calendar)$" function, I export all the calendar activities. I have YetiForce version 6.3.0.

How can I solve this?

**Comment by mariuszkrzaczkowski** [comment]
update to 6.4
