### ISSUE TITLE
[Question] which menu to send email in YetiForce 5.1.0

### ISSUE THREAD

**Issue by calvinsug** [YetiForceCompany/YetiForceCRM#11946]
Hi,

i have to installed version 5.1.0 to working on my localhost because there is an error in 5.2.0

I have configured the smtp server and when i want to test send email from email template, i couldn't find any menu to send the email,

any guidance to send the email in this version? Because when i see this online demo: https://gitstable.yetiforce.com/

I can find submenu "My Mailbox" inside Virtual Desk in dashboard, but this menu doesn't exists in version 5.1.0

How can i access that submenu?

**Comment by davide-alghi** [comment]
hi,
did you enable "My mailbox" module?
https://gitstable.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8

**Comment by calvinsug** [comment]
ahhh, i see, it is disabled on my localhost.
When i try to enable it, there appears an error "Could not find required roundcube library. Some features were disabled. Go to Modules – Installation to download."

**Comment by davide-alghi** [comment]
maybe this help
https://github.com/YetiForceCompany/YetiForceCRM/issues/9978
