### ISSUE TITLE
[Question] How does send via email work- Campaigns

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#11940]
When I click on send via email in campaigns I keep getting an error that says please select one record.

I am confused about what to select.

Can someone let me know what I am doing wrong?

Thank
![select_error](https://user-images.githubusercontent.com/7829825/68103505-0fbc3e80-ff12-11e9-9889-e21d4929ff40.png)

**Comment by fbojan** [comment]
![RECORD](https://user-images.githubusercontent.com/25682437/68107289-9e19cb80-fee4-11e9-8120-90743d663c19.gif)

**Comment by bangde** [comment]
I am afraid I have done that and the error still occurs. maybe it's a bug that you have not noticed. I have selected and it still says please select at least one record.

Something is not working correclty

**Comment by bangde** [comment]
I did a screen video to show you what I am getting

https://drive.google.com/file/d/1CC1DNw_6O2rxh6efd_CO8ia0YTWT9s1U/view

**Comment by mariuszkrzaczkowski** [comment]
do you have Service Pack  installed?
![github](https://user-images.githubusercontent.com/10198654/68183648-4c814780-ff9d-11e9-8269-e2f9f2e8e97c.jpg)

**Comment by mcjoonior** [comment]
I have exact the same error on the cloud hosted version (5.2 SP1).  Issue reported via sla@...
