### ISSUE TITLE
[Question] API sort data

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#11949]
Got some basic online form where data is sucked from module Accounts. 
I want to sort this data alphabetically without any html changes in form itself. Any idea how to implement it in yetirest.php?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/dc291df7425a386e7a8383b20810d4188467f856/api/webservice/Portal/BaseModule/RecordsList.php#L62-L64

**Comment by TonyM15** [comment]
Interesting.. tried with yetirest but it not work... what would be the way to sort records?

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/68275165-2de98200-006b-11ea-875c-1a1cf67570bf.png)
