### ISSUE TITLE
[bug] Cannot edit existing filters

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11948]
Hello,

How can I edit the filters that I create in Yetiforce? 
I can create then but I can't find where you can edit them.

**Comment by vovpff** [comment]
In admin menu there are something like `Filters - Cobfiguration`

**Comment by rskrzypczak** [comment]
what version do you have?
if you have version 5.2, install the latest [service pack](https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0)

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/68183099-6e35fb00-ffac-11e9-94ec-b567ac91d9e4.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/68183892-e34e0400-ff9d-11e9-8966-6a1ba87f1675.jpg)

**Comment by acoolov** [comment]
What do you mean by the latest service pack? The link points to version 5.2.0 which is the one i have.

**Comment by vovpff** [comment]
@acoolov https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.2.0/5.2.0_ServicePack_v18.zip

**Comment by acoolov** [comment]
Sorry for my ignorance, I imported the service pack by going Install From File in settings. It got successfully imported. Does it mean it has been installed now? Where do I check if it's been installed? 
I still don't see the menu to edit existing filters in settings.

**Comment by vovpff** [comment]
Hmmm. Screenshot?

**Comment by rskrzypczak** [comment]
> Where do I check if it's been installed?

![image](https://user-images.githubusercontent.com/10221999/68268388-3daa9b80-0056-11ea-98ce-d90082647fc7.png)
--------

> I still don't see the menu to edit existing filters in settings.

You don't see this menu https://github.com/YetiForceCompany/YetiForceCRM/issues/11948#issuecomment-549677757 ?
You say something strange.

---------
If you don't see this options clear browser cache (CTRL+SHIFT+R)
![image](https://user-images.githubusercontent.com/10221999/68268701-975f9580-0057-11ea-926e-e6db56c8a284.png)

**Comment by acoolov** [comment]
Installed the service pack for 5.2.0 and I see it now. Thank you.
