### ISSUE TITLE
[bug] Super annoying bug

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11956]
Hello everyone. 

There is a super annoying bug in Yetiforce, 

If you ever accidentally un-assign picklist items from a role, it un-assigns ALL picklist menus, from ALL roles, in ALL modules! This is crazy. I un-assigned one picklist in tickets, to change ticket status values around, and now all of my module pick lists are empty. I have to re-assign them all again for all modules. 

This is insane. I had to do it twice for ALL module roles/picklists. 

Can this be fixed?

**Comment by acoolov** [comment]
Is this one still being worked on?

**Comment by vovpff** [comment]
In any case bug will be fixed in next version.

**Comment by areksolek** [comment]
Could I have a gif, please? Which will present the  problem.

**Comment by acoolov** [comment]
This bug is bug is still present in 4.3.0 service pack 4. As soon as I change up a few things with my pick lists, ALL picklists get unassigned and I have to spend half a day re-selecting all the picklists for all the modules all over again. When is this going to be fixed?

**Comment by KatarzynaUlichnowska** [comment]
Could you please send us a gif as @areksolek requested? Please test if it still appears at gitdeveloper.
