### ISSUE TITLE
[Question]  Many to Many relationship Contacts and Leads, Converting Contacts to Leads, Customizing Lead Which Summary Fields are Displayed

### ISSUE THREAD

**Issue by All4LifeInc** [YetiForceCompany/YetiForceCRM#11957]
Hi,

1.) How can we customize which Lead Summary fields are shown?
2.) Is it possible to have a many to many relationships between contacts and leads (ie multiple contacts can belong to multiple leads and vice versa)?
3.) Is it possible to create a Lead from a contact?  How does one assign a contact to Lead(s) from the contact interface without creating a new one?
4.) Is it possible to add an existing Contact(s) to a Lead?
5.) Is it possible to establish a relationship between leads?  ie Lead 1 (Primary) -> Lead 2 (Secondary)
6.) Is it possible to integrate LinkedIn via a Web Service?
7.) Is it possible to integrate/ push calendar events to iCal / Bookafy (ex. Web Service)?

If YetiForce cannot do this, would you happen to know an Open Source CRM that does?

Thank you

**Comment by bpabiszczak** [comment]
1. Yes

![image](https://user-images.githubusercontent.com/10197525/74094768-da158b80-4ae6-11ea-92d1-d194da2023e3.png)

2. No. 
3. Try this: Software configuration >> Standard modules >> Mapping
4. Yes 

![image](https://user-images.githubusercontent.com/10197525/74094758-b81c0900-4ae6-11ea-93ce-5cb8b259773e.png)

5. Yes, but you need a programmer. Check how the hierarchy in Accounts works.
6. Yes, you need a programmer. 
7. Yes, you need a programmer.
