### ISSUE TITLE
[Question] [PL] OSSMailScanner Nie działa automatyczne pobieranie wiadomości 

### ISSUE THREAD

**Issue by Derikus** [YetiForceCompany/YetiForceCRM#11954]
### Description

Witam,
może ktoś będzie umiał mi pomóc, mianowicie do tej pory działało wszystko pięknie aż do 25.10 cron uruchomił automatyczne skanowanie wiadomości i w logach pobierania maili wisi mi cały czas na jednej wiadomości. Przycisk do ręcznego zatrzymania skanowania nie działa, przez skrzynkę można wczytać maile do systemu natomiast automat przestał działać. 

Może mi ktoś podpowiedzieć jak mogę go odblokować?
Screen z logów historii pobrań
![Opera Zdjęcie_2019-11-05_145755_agrafbcm pl](https://user-images.githubusercontent.com/25840164/68214368-99850e00-ffdd-11e9-9064-93082e18e866.png)

Environment | Version / Name
-- | --
YetiForce | 5,1
Web server (name and version) | Apache
PHP | 7.1
Browser (name and version) |  
Operating System (name and version) | Ubuntu 16.04
Database (name and version) | mysql
Service Pack version

**Comment by bpabiszczak** [comment]
Albo ręcznie w bazie przesunąć na następny mail, albo usunąć maila jeżeli wiadomo który to jest, albo sprawdzić problem co stanowi przeszkodę dla skanera i to naprawić :] Nie ma magicznej różdżki.

PS. Zalecam aktualizację do 5.2 z najnowszym SP. Możliwe, że problem został już wyeliminowany.

**Comment by Derikus** [comment]
Dzięki pomogło usunięcie rekordu z bazy. Przeskoczył dalej i wznowił pracę.
