### ISSUE TITLE
[PL] Loader zawiesza się 

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1195]
Po dodaniu w kontrahnecie produktu bądź usługi (w module powiązanym) loader zawiesza się

https://gitmaster.yetiforce.com/index.php?module=Accounts&view=Detail&record=133&mode=showRelatedProductsServices&requestMode=summary&tab_label=Produkty%20i%20us%C5%82ugi
![7](https://cloud.githubusercontent.com/assets/11139594/8403388/6b275f9c-1e44-11e5-9152-590ffb4c12ab.png)

**Comment by konadrian** [comment]
Nie uzyskano błędu
