### ISSUE TITLE
[bug] installation error in windows 10: Uncaught Exception: The imap library is missing

### ISSUE THREAD

**Issue by calvinsug** [YetiForceCompany/YetiForceCRM#11950]
hi there,

i have installed yetiforce 5.1.0 on MAC OS Catalina and it is running (can't install 5.2.0)

When i try to install it in windows 10 environment,

in the very first installation (when redirected to the installation page: install.php), there appears an error:

Fatal Error: Uncaught Exception: The imap library is missing in D:\xampp\htdocs\yetiforce\include\RequirementsValidation.php:15 Stack trace: #0
D:\xampp\htdocs\yetiforce\install\Install.php(21):include_once()#1 {main} thrown in D:\xampp\htdocs\yetiforce\include\RequirementsValidation.php on line 15

This should be working on MAC environment, but why not in windows?

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/component/zoo/item/web-server-requirements#libraries

> 
> THIRD PARTY LIBRARIES CONFIGURATION
> IMAP Mandatory
> PDO Mandatory
> MySQL Native Driver (mysqlnd) Mandatory
> GD Mandatory
> OpenSSL Mandatory
> Curl Mandatory
> PCRE Mandatory
> XML Mandatory
> JSON Mandatory
> SESSION Mandatory
> DOM Mandatory
> ZIP Archive Mandatory
> MBSTRING Mandatory
> SOAP Mandatory
> FILEINFO Mandatory
> ICONV Mandatory
> INTL Mandatory
> SPL Mandatory
> Reflection Mandatory
> SimpleXML Mandatory
> bcmath Mandatory
> filter Mandatory
> LDAP Optional
> EXIF Optional
> APCU Optional
> OPCACHE Optional
> IMAGICK Optional (but recommended)

**Comment by diderich** [comment]
Interestingly opensue (Leap 15.x) no longer ships php with imap library which makes it impossible to install the system on an opensuse system on which I am unable to re-compile and re-install php7-imap. Although you may not care about this, it would be decent to only rely on libraries that actually ship with major distributions.

**Comment by mariuszkrzaczkowski** [comment]
Debian and redhat do not have is problem.
you can use crm without mail your choice
