### ISSUE TITLE
Module and field wise permission is not working in new role-profile

### ISSUE THREAD

**Issue by P2remchand** [YetiForceCompany/YetiForceCRM#11959]
Module and field wise permission is not working in new profile creation.
i want to assign a particular module to be assessed by a particular user while not accessible by other users. but when i tray to do that in permission setting, the  system is just disabling almost 80% of the modules.  The editing function is only affecting some modules from 1 to 10 . after 10th module all the modules are getting disabled. this is a serious issue for us because currently every user is accessing every modules which is not required by us. Please help us to rectify this at earliest.
![yy](https://user-images.githubusercontent.com/55957002/68272287-36e94c00-0089-11ea-9710-26314cb7a1a1.png)
![yyy](https://user-images.githubusercontent.com/55957002/68272288-36e94c00-0089-11ea-8b61-9b16f789e88d.png)

**Comment by mariuszkrzaczkowski** [comment]
run the structure repair mechanism
```php
echo 'App\Db\Fixer::baseModuleTools: ' . App\Db\Fixer::baseModuleTools() . PHP_EOL;
echo 'App\Db\Fixer::baseModuleActions: ' . App\Db\Fixer::baseModuleActions() . PHP_EOL;
echo 'App\Db\Fixer::profileField: ' . App\Db\Fixer::profileField() . PHP_EOL;
```

**Comment by P2remchand** [comment]
its not working for me...
if you can do the same for me and also i have some other bugs too, how will
you charge us???

we are ready to pay for this.
