### ISSUE TITLE
[PL] Błąd kalendarza graficznego

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1196]
W kalendarzu graficznym zapisałam rezerwacje. Nie pojawia się w tym dniu żadna notatka. Dopiero po odświeżeniu jest informacja.
https://gitmaster.yetiforce.com/index.php?module=Reservations&view=Calendar&parent=80
![8](https://cloud.githubusercontent.com/assets/11139594/8403776/d33d2d84-1e47-11e5-8715-1810a0e3b6b4.png)

**Comment by konadrian** [comment]
Nie uzyskano błędu
