### ISSUE TITLE
[Feature] Duplicate Prevention

### ISSUE THREAD

**Issue by SaschaPapiniIVO** [YetiForceCompany/YetiForceCRM#11965]
Hi all, it's possible to add to a new milestone the feature Duplicate Prevention ?
In vtiger it was present. 
This is very important especially in companies, otherwise sellers can create more records with the same company and it is not correct. 
The company must be only one and must be assigned to only one seller who manages it

**Comment by fbojan** [comment]
This would also interest me because I have three companies

**Comment by KatarzynaUlichnowska** [comment]
We're planning to add a mechanism to block creating duplicates in Contacts with the same email address. We aren't planning a duplicate prevention mechanism for Accounts.

**Comment by rioshaz** [comment]
@KatarzynaUlichnowska  have u guys fixed the duplicate problem yet ? any help is appreciated ..

**Comment by mariuszkrzaczkowski** [comment]
we already have it, see it
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=EventHandler&view=Index
![image](https://user-images.githubusercontent.com/10198654/86497291-628c1580-bd81-11ea-9504-79fcb576cfac.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/87545422218568db7c8c31ef3f25a98adbcda7ff/modules/Accounts/handlers/DuplicateVatId.php#L21-L42

**Comment by kamiro16** [comment]
Thanks for the modification. 
Just appends the file to the directory? 
What else should I add to make the modification work?

**Comment by mariuszkrzaczkowski** [comment]
You must wait for the new version
running this requires modification of many files

**Comment by kamiro16** [comment]
Thanks you @mariuszkrzaczkowski for answer.
So I waiting for new version.

**Comment by rioshaz** [comment]
> we already have it, see it
> https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=EventHandler&view=Index
> ![image](https://user-images.githubusercontent.com/10198654/86497291-628c1580-bd81-11ea-9504-79fcb576cfac.png)

i see nothing for leads sir.. can we please add leads too and validate with mobile or email..

ideally a user should be able to choose which field he/she wants to be validated (name, phone, email,  any custom field etc )for duplicate check  like in vtiger

**Comment by mariuszkrzaczkowski** [comment]
sure that it would be useful, we will wait for someone to commission such a functionality

**Comment by mariuszkrzaczkowski** [comment]
you can always make a fundraiser for this purpose

**Comment by thazro** [comment]
Hi, I wrote a php similar to vat Id above, for a duplicate check in Assets, put it in modules/handlers, but it's ignored. Can you please tell me where else needs to be declared? Thanks
