### ISSUE TITLE
[Question] Add a document status

### ISSUE THREAD

**Issue by calvinsug** [YetiForceCompany/YetiForceCRM#11967]
Hi, 

I'm using YetiForce 5.1.0, and found a module named "Document" inside menu Database which we can upload a document, set a status, and set a note.

My question is: Can we add additional status ? As we know, there are only 2 statuses (none and checked). Just wondering if we can add status like "Rejected" or "Being Evaluated" and so on

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/73889746-aa5d4e00-4870-11ea-997f-4f1569c91be4.png)
