### ISSUE TITLE
[bug] There is no edit option in search filter

### ISSUE THREAD

**Issue by KrishnaPB** [YetiForceCompany/YetiForceCRM#11961]
Dear Team,

There is no edit option in search filter. Please find the attached screenshot.
![ya1](https://user-images.githubusercontent.com/11535185/68280692-0eb71880-009c-11ea-9880-f1cf5c36522b.png)

I am using version 5.2 of yatiforce.

**Comment by vovpff** [comment]
I'm not sure what I'm right but "All" filter can be changed only by admin via Admin panel

**Comment by KrishnaPB** [comment]
I am trying from admin panel only. It was working fine in older version of yatiforce.

**Comment by KrishnaPB** [comment]
Even it is not working in custom filter which I have created as well.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/11948
check this: https://github.com/YetiForceCompany/YetiForceCRM/issues/11948#issuecomment-549665305
after: clear browser cache (CTRL+SHIFT+R) https://github.com/YetiForceCompany/YetiForceCRM/issues/11948#issuecomment-550140277
and i think this is your fix: https://github.com/YetiForceCompany/YetiForceCRM/pull/11438
