### ISSUE TITLE
[bug] Time field in calendar not being populated

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11971]
I'm glad some bugs I report are being fixed. That's incredible. Plus I feel good for putting some effort to improve this great CRM platfort. 

Here is another bug that I found. Sorry for not following the guide, it's just much faster to post and this bug is easy to replicate.

When creating a new to do/call/meeting in calendar, and entering time on the animated clock, the time never gets updated in the time field. You have to manually enter time in the time field. 

Hope this one can be fixed as well.

Thank you.

**Comment by rskrzypczak** [comment]
I'm unable to duplicate what you're describing, neither on [gitdeveloper](https://gitdeveloper.yetiforce.com/) nor on [gitstable](https://gitstable.yetiforce.com/). 
So it's not as easy to trigger as you said.
-Enable the console in your browser, maybe some information pops up there
-Enable debugging, maybe something shows up in the logs
-Record a short clip using ScreenToGif for example to show us what it looks like and how to duplicate it
Being able to see it is going to explain more than just a description.

"Sorry for not following the guide, it's just much faster to post.."
Try not to skip the guide to save time of people who are here to help.

**Comment by acoolov** [comment]
![calendar](https://user-images.githubusercontent.com/38298689/68480137-155fa000-0202-11ea-9bfe-7f2efb53e414.gif)

Here is the gif of what happens when I try to select time in calendar. 
Yetiforce 5.2.0 with the latest service pack
Ubuntu 18.04
PHP 7.2

**Comment by rskrzypczak** [comment]
Updating *.min ([link](https://github.com/YetiForceCompany/clockpicker/commit/0715faf27c92aded031c6a2fa4c135a5caa481c2)) files is required.
You can:
- overwrite them manually
- reload yarn
- disable *.min in configuration
  `config/Developer.php`
