### ISSUE TITLE
[UI Improvement] Improve View / Edit Layout

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1198]
a. The edit buttons (red in figure below) take up a lot of vertical space
b. Right to the record description (blue in figure), there is a lot of free space

Suggestion:
1. Move the edit buttons (red) to the right (green location) and align them as shown
2. Make the size of the record description text the same width as the summary column

Reasoning:
1. Free space to the right of the record description is used
2. Additional vertical space is freed
3. Usually people move the cursor to the right when looking at a screen and don't want to have the cursor in the picture (due to most people being right-randed) and as such putting the edit bottons to the rights makes the UI more natural in used as the edit buttons are are close to where the cursor actually is when people look at the record

![suggestion](https://cloud.githubusercontent.com/assets/10230144/8404138/f6856006-1e4a-11e5-8d7d-49d5f517907a.jpg)

**Comment by eptapsyxos** [comment]
We can add on the empty space some statistics of the record.a summary of statistics released on the specific record.

**Comment by bpabiszczak** [comment]
We will soon publish draft new template. Then each of your attention will be important.

**Comment by reeid** [comment]
How about some very early preview/screen shots? does it will be similar to http://demo.makeyourcloud.com/vtiger6.3/ ?
How about supporting mobile devices?
Sorry for such interest but I planning moving and some forecast will help in steps here too

**Comment by bpabiszczak** [comment]
The screenshots should be ready next week so they will be sent to the mailing list and published on GitHub in a special issue. We will make changes and improvements for about a week and when we finish, we will implement a template to the Customer Portal and then to the entire CRM.

**Comment by bpabiszczak** [comment]
I added a draft of a new 2.0 portal to the issue [https://github.com/YetiForceCompany/YetiForceCRM/issues/1385] about it. We are waiting for your opinions and suggestions of what can be changed. In the future we would also like to change the look and feel of the system so it will look simmilar.
