### ISSUE TITLE
[bug] calendar-proxy-read does not work right for CALDAV

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#11982]
# 🐞 bug report

### ⁉️ Describe the bug

calendar-proxy-read give write and read access

### 🔥 How to trigger the error

Steps to reproduce the behaviour:
1. Create a new DAV Principal using the following guide from SABRE: [http://sabre.io/dav/caldav-proxy/](url)
2. Create user group relations manually from the same guide.
3. Log in as a user but specify the path "dav.php/principals/USERNAME/calendar-proxy-read"; using thunderbird or davdroid or you can just use web interface.
4. See that you still can write to the events or in case you using a web interface you can create folders.

### 👎 Actual Behavior

Write Access
### 👍 Expected Behavior

Read access if using calendar-read-proxy

### ❓ Additional context
Obviously it seems like that bug does not relate to your specific company because the question of the possibility of doing so was ignored! 

But in a lot of positions and industries, it is crucial to give read-only access for contacts and calendars. For example, it is a production facility and the worker needs to have a company directory address book on his phone. Another scenario is the usual clerk. need to access company calendars for meetings and briefs from his phone.

**Comment by bpabiszczak** [comment]
We do not plan to support this functionality.
