### ISSUE TITLE
[PL] Błąd kalendarza graficznego - DZIEŃ

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1199]
SEKRETARIAT>REZERWACJE
Zapisałam 30.06 rezerwacje w kalendarzu graficznym - DZIEŃ i jej nie widać. Jest widoczna dopiero po odświeżeniu.
TO samo jest w TYGODNIU
https://gitmaster.yetiforce.com/index.php?module=Reservations&view=Calendar&parent=80

![10](https://cloud.githubusercontent.com/assets/11139594/8404206/767b3dda-1e4b-11e5-882b-5a9ac559a496.png)

**Comment by konadrian** [comment]
Nie uzyskano błędu
