### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by marquetingca** [YetiForceCompany/YetiForceCRM#11996]
Hi, I have the following issue.
After doing `yarn install` and `composer install` and I enter localhost: 80 for the installation of yetiforce the following error appears.

![Screenshot_2019-11-11 Users](https://user-images.githubusercontent.com/44176697/68616263-165f2e80-049b-11ea-84d7-a360d52e0554.png)

looking for a solution update `composer update` and the following error appears.

![Captura](https://user-images.githubusercontent.com/44176697/68616374-51616200-049b-11ea-87f0-9ceb730b727d.JPG)

I need help please.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/68621728-c4d19680-04d0-11ea-8e9d-ba3965b2c849.jpg)
