### ISSUE TITLE
[bug] Bug with DateTime field - missing some month in the calendar

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#11991]
There is some strange bug in my Date and Time field that I added to my tickets module. 
It is missing some months. 
I created the same field in the demo version, but the bug is not there.
What could this be?
Please see gif below
![DateTimeField](https://user-images.githubusercontent.com/38298689/68534418-80909b80-0302-11ea-9b15-f90244b15055.gif)

**Comment by acoolov** [comment]
I just logged into another user's account and their field works fine. 
Once I'm logged into my account, the field is buggy.

**Comment by acoolov** [comment]
Ok I found out when it becomes buggy but don't know why exactly. It happens only when the user's first day of the week is Sunday. When it is back to Monday the error disappears. 

Steps to replicate on the demo version:

1. In user's preferences change the first day of the week to Sunday.
1. Create a Date and Time field in any module.
2. Go to quick create/full version and start choosing date and time.
3. Some months will be missing like in my gif example. 

Can this be fixed sometime soon?

**Comment by acoolov** [comment]
Is this issue going to be fixed any time soon?

**Comment by areksolek** [comment]
The bug has been fixed
![datatime](https://user-images.githubusercontent.com/25615135/75525841-df446700-5a10-11ea-9a64-9b2dd59d1f17.gif)
