### ISSUE TITLE
Language files: several lists should be in the database and not the language files

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#12]
Change request for the near future:
Actually I found some list in the language files, which should be defined in the database.
Examples: Products.php and Quotes.php definition of product groups:
'300-Sales-Software'=>'300-Sales-Software',
'301-Sales-Hardware'=>'301-Sales-Hardware',
'302-Rental-Income'=>'302-Rental-Income',
'303-Interest-Income'=>'303-Interest-Income',
'304-Sales-Software-Support'=>'304-Sales-Software-Support',
'305-Sales Other'=>'305-Sales Other',
'306-Internet Sales'=>'306-Internet Sales',
'307-Service-Hardware Labor'=>'307-Service-Hardware Labor',
'308-Sales-Books'=>'308-Sales-Books',
It makes not really sense there and should be found in the product settings in the database where it could be used from quotes, products etc..
The user must be able to change this without problems.
Also currencies should be completely in the database. Now therea re some defintions in the database and a translation in the language file...
And there are not all currencies defined.
Also in vtiger.php you find "Industries"
Some are very special and only localy usable like the polish definitions of goverment.
The user should be able to define his industries in the database.
Also the salut to the customer "Mrs, Ms, Mr, Hello, Dr,.." and so on should be defined in the database.
Is it possible to make this configurable within YetiForce without problems?
Is this a big problem for the structure or is it easy to change?
Thx

**Comment by bpabiszczak** [comment]
I don't understand this problem. Curently, a translating function works as follows:

1. Checks if the translation is in a translation file of a module, if not, then:

2. Checks if the translation is in the main file of the translation, if not, then:

3. It throws translations saved in the database.

Examples provided by you are possible to be translated from a language files level. I don't see any incorrectness here.
