### ISSUE TITLE
[PL] Zawiesza się loader i kursor myszki

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1200]
KONFIGURACJA SYSTEMU>UPRAWNIENIA>ROLE
Z Drzewa wybieram ZARZĄD I dodaj (ikona) zawiesza się loader i kursor myszki.
https://gitmaster.yetiforce.com/index.php?module=Roles&parent=Settings&view=Edit&parent_roleid=H2
![11](https://cloud.githubusercontent.com/assets/11139594/8404381/cc2fd9d8-1e4c-11e5-93ff-386dd6e427af.png)

**Comment by konadrian** [comment]
Nie uzyskano błędu
