### ISSUE TITLE
[Question] Uproszczenie procesu sprzedaży

### ISSUE THREAD

**Issue by yotuze** [YetiForceCompany/YetiForceCRM#12013]
Witam,
Czy można jakoś uprościć proces sprzedaży? Nie widzę zastosowania w naszym wypadku dla "Karty wymagań" i "Kalkulacji".

Rozumiem:
- Szanse sprzedaży - wyjazd do klienta, spotkanie biznesowe lub mail może taką szansą być
- Zapytanie ofertowe - tam wpisujemy co klienta interesuje
- Oferta - finalny dokument z wszystkimi pozycjami i cenami

W naszym przypadku karta wymagań i kalkulacja to po prostu przepisywanie tych samych danych, które de facto i tak można dodać finalnie w ofercie bo nie ma blokady, że nie mogę do oferty dodać produktu, którego nie było w zapytaniu ofertowym. Wystarczy tylko w "Moduły - pola" odznaczyć wymóg Kalkulacji? Jak w to miejsce dodać wymóg wybrania Zapytania ofertowego?

Czy pominięcie tych etapów ma wpływ na jakieś zdefiniowane raporty?

Jeszcze taka sugestia, czy można by było dodać do tych procesów sprzedaży automatycznie generowany numer? który byłby jednolity przez cały etap sprzedaży a nazwę zostawić opcjonalną bo wymyślanie tych nazw też może być nad wyrost.

Z ofertami mam jeszcze problem z generowaniem PDFu ale to założę osobne zgłoszenie.

Pozdrawiam

**Comment by bpabiszczak** [comment]
Wystarczy wyłączyć moduły i wyłączyć pola w panelu :D
Za dużo pytań...
