### ISSUE TITLE
[bug] Workflows stops sending email

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12018]
On record creation (Accounts) workflow dont trigger sending email. No logs, no errors.
Server configuration 100% perfect, no red labels.
What it could be? System updated to latest version.

**Comment by mariuszkrzaczkowski** [comment]
Check logs and is cron working properly?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/68735985-b4f4a800-05df-11ea-8ab7-3b4a50ce91ec.jpg)

**Comment by mariuszkrzaczkowski** [comment]
check the email queue

**Comment by JohnMaverick** [comment]
Nothing goes to email queue and nothing in logs. Once smtp is set email with confirmation is sent correctly. Any tips?
