### ISSUE TITLE
[bug] Błąd podczas generowanie PDF Oferty

### ISSUE THREAD

**Issue by yotuze** [YetiForceCompany/YetiForceCRM#12014]
# 🐞 bug report

### ⁉️ Describe the bug
Chcąc wygenerować ofertę (lub wysłać mailem) pojawia się błąd:

`Argument 1 passed to YetiForcePDF\Style\NumericValue::setValue() must be of the type string, null given, called in /var/www/html/vendor/yetiforce/yetiforcepdf/lib/Style/Normalizer/Normalizer.php on line 92`

### 🔥 How to trigger the error
1, Wejść do oferty
2, Kliknąć w "Eksportuj do PDF"
3, Kliknąć "Generuj" lub "Wyślij pocztą"

### 👎 Actual Behavior
Błąd

### 👍 Expected Behavior
Oferta w PDF

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

Nie ma przycisku "Eksportuj do PDF" w/w adresach, żeby to sprawdzić

### 📷 Screenshot of configuration
![config-serv-crm](https://user-images.githubusercontent.com/6560221/68657020-2cb8c900-0533-11ea-9c3b-0f44c8266ff7.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Brak błędów w logach Apache

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|   5.2
| Web server (name and version)|	Apache2 2.4.25	|
| PHP  |				7.2				|
| Browser (name and version)  | 	Firefox  70.0.1 64bit	|
| Operating System (name and version)  | 	Debian 9.1	|
| Database (name and version) | 	MySQL 5.0.12	|
| Service Pack version | 	18	|

**Comment by bpabiszczak** [comment]
proszę uruchomić szablon na gitdeveloper i jak błąd występuje, to przesłać nam kod tego szablonu.
