### ISSUE TITLE
[Question] Track a sent mail campaign

### ISSUE THREAD

**Issue by calvinsug** [YetiForceCompany/YetiForceCRM#12015]
Hi There, i'm trying to create a marketting -> campaign 
and tried to send to selected contact's email with my email template (document attached).

The email is working, i have sent the campaign email successfully with the document. But, can i track whether my document is being downloaded by my targetted contacts or not ? Like any analytics i can get from the email ?

**Comment by bpabiszczak** [comment]
You can not.

**Comment by vovpff** [comment]
If document attached you can't control anything. If you push to customer link to document - you can check web server access logs for customers activity. But this is can cause problems with GDRP
