### ISSUE TITLE
[Question] How to activate quick preview for custom module

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12019]
How to activate quick preview for custom module? It will be also prefect if quick preview will allow for editing fields. vtiger have this nice func of quick edit record in list view. Wil be cool to implement the same in YF

**Comment by mariuszkrzaczkowski** [comment]
which quick preview are you talking about,
attach a screenshot

**Comment by waran70** [comment]
![preview](https://user-images.githubusercontent.com/6852348/68743011-10488980-0624-11ea-99c8-50f849fed2bd.jpg)

**Comment by konadrian** [comment]
It should work for new modules https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Vtiger/models/Record.php#L1328
check if you don't overwrite this method in your new module
