### ISSUE TITLE
How to track the user 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#12016]
I want to track the all users  who did download the records (export .CSV file) from CRM. How can we track in Yetiforce CRM.

**Comment by maeglin4** [comment]
yeah, me too i would like to track everything that each and every user does anywhere in yeti. is it possible ?

**Comment by mariuszkrzaczkowski** [comment]
Maybe something like that?
https://yetiforce.com/en/analyzer

**Comment by maeglin4** [comment]
> Maybe something like that?
> https://yetiforce.com/en/analyzer

my company would like to have a demo, we are interested in buying the product

**Comment by paula-w** [comment]
We're currently working on this module to make it compatible with version 5.2. It should be ready in about a week or two.

**Comment by maeglin4** [comment]
you dont have like a video to demonstrate it ? or some sceenshots from older version ?

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/73943685-78d89700-48f1-11ea-9065-b3583cd7de4e.png)

![image](https://user-images.githubusercontent.com/10197525/73943704-855cef80-48f1-11ea-92d1-be10b3083169.png)

![image](https://user-images.githubusercontent.com/10197525/73943726-90b01b00-48f1-11ea-8f2a-d60f4372fdca.png)

![image](https://user-images.githubusercontent.com/10197525/73943776-a1f92780-48f1-11ea-8b0a-f333e73a0766.png)

![image](https://user-images.githubusercontent.com/10197525/73943820-bc330580-48f1-11ea-860b-131f8a36a232.png)
