### ISSUE TITLE
[bug] It may or not related to update package - error in services

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12026]
System with applied  5.2.0_ServicePack_v18.zip
Once I edit service unit price get cleared and upon saving logs shows:

2019-11-14 07:04:22.2994 [error] - ERR_ILLEGAL_FIELD_VALUE||unit_price||Services||10000
App\Exceptions\Security: ERR_ILLEGAL_FIELD_VALUE||unit_price||Services||10000 in /var/www/html/modules/Vtiger/uitypes/MultiCurrency.php:41
Stack trace:
#0 /var/www/html/modules/Vtiger/uitypes/Base.php(68): Vtiger_MultiCurrency_UIType->validate(10000, true)
#1 /var/www/html/modules/Vtiger/actions/Save.php(119): Vtiger_Base_UIType->setValueFromRequest(Object(App\Request), Object(Services_Record_Model))
#2 /var/www/html/modules/Vtiger/actions/Save.php(87): Vtiger_Save_Action->getRecordModelFromRequest(Object(App\Request))
#3 /var/www/html/modules/Vtiger/actions/Save.php(61): Vtiger_Save_Action->saveRecord(Object(App\Request))
#4 /var/www/html/include/main/WebUI.php(182): Vtiger_Save_Action->process(Object(App\Request))
#5 /var/www/html/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#6 {main}

**Comment by TonyM15** [comment]
The same here

**Comment by rskrzypczak** [comment]
yeah, it fixed in [update package v6](https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.2.0)
