### ISSUE TITLE
[bug] Error after changed $site_url in config/Main.php

### ISSUE THREAD

**Issue by calvinsug** [YetiForceCompany/YetiForceCRM#12029]
Hi guys,

I'm using Yetiforce 5.1 in my localhost and i need to changed $site_URL in config/Main.php to allow other user with the same network access my YetiForce web application.

I changed this 

`public static $site_URL = 'http://localhost:8080/yetiforce/';`

into this
`	
	public static $site_URL = 'http://192.168.64.3/yetiforce/';
`

The problem occurs when i changed it to my Local IP Address.
After i changed it, my app is become weird. It redirected to http://192.168.64.3/yetiforce/install/Install.php

and when i revert it back to localhost:8080
It still redirected to http://localhost:8080/yetiforce/install/Install.php

and now i can't access again the web application. I need to remove the project and start again with a fresh installation. What am i doing wrong here?

**Comment by mariuszkrzaczkowski** [comment]
Clear the browser cache
browsers remembers all redirects

**Comment by calvinsug** [comment]
it's not working, have tried this.

Anyway, is it the correct file to change redirected URL to my IP Address? 
Still need to do for other computer can access my Yetiforce web app in my localhost

**Comment by davide-alghi** [comment]
yes it is.

so you web server port is 8080. is it right?
what about **DocumentRoot** directive in apache <yf-site>.conf?

try this
```
public static $site_URL = 'http://192.168.64.3:8080/yetiforce/'
```

**Comment by calvinsug** [comment]
yes, my port is 8080 and i don't think i can use ip address with the port 8080 because when i type 192.168.64.3:8080 in my browser, i can't reach XAMPP default dashboard (must be 192.168.64.3 without the port).

For the .conf 
Did you mean httpd.conf file ?
Have tried to change the ServerName
from this
`ServerName localhost`
into
`ServerName 192.168.64.3:8080`
or
`ServerName 192.168.64.3`

but still not effecting anything

**Comment by davide-alghi** [comment]
it's strange. if previous was ```localhost:8080``` the new one need to be ```192.168.64.3:8080```
```localhost:8080``` is exactly ```127.0.0.1:8080```

but have you tried with ```public static $site_URL = 'http://192.168.64.3:8080/yetiforce/';``` ? in YF main.php?

ServerName should be 192.168.64.3 or commented if you don't use domain names

Is your virtual host directive something like this?
```<VirtualHost *:8080>```

**Comment by calvinsug** [comment]
have tried this
`public static $site_URL = 'http://192.168.64.3:8080/yetiforce/';`

but not working, it just blown up my whole application, i can't access it anymore (redirected to `http://192.168.64.3/yetiforce/install/Install.php`) even though i delete my cache, image, and files or browsing data in my browser after i revert the site_URL to the previous value.

for the virtual host, where i can find this? i have search the whole project with keyword VirtualHost but found nothing

nb: i'm using XAMPP anyway for the apache web server

**Comment by davide-alghi** [comment]
> for the virtual host, where i can find this? i have search the whole project with keyword VirtualHost but found nothing

in httpd.conf

**Comment by calvinsug** [comment]
in etc/httpd.conf right?

When i see that file, there is no such thing as this code
`<VirtualHost *:8080>`

**Comment by calvinsug** [comment]
I think i have solved this issue,

the solution for me is:
when i'm installing the fresh new Yetiforce 5.1.0, i accessed the installation from 192.168.64.3 instead of localhost:8080,

So when the installation is initiated, the default $site_URL become `'http://192.168.64.3/yetiforce/';` from the start and i'm not needed to change it. Every time i accessed in my browser using localhost:8080/yetiforce, it will be redirected to 192.168.64.3/yetiforce
and problem solved!

**Comment by Kayrocket** [comment]
I have successfully installed yetiforce on my ubuntu 16.04 server but I am not able to reach the yetiforce interface when I key in the domain name I used or the ip address. The ip address only bring up the apache server. What do I do to get the interface of the yetiforce?

**Comment by davide-alghi** [comment]
Hi @Kayrocket,
look in config/Main.php file: in $site_URL you have the correct url.
if it doesn't work something is wrong in your server configuration or installation.

**Comment by Kayrocket** [comment]
Hello @davide-alghi,
Thank you for the response
