### ISSUE TITLE
[Question] Access from different URLs

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#12022]
### Description

How to access to system from different URLs? For example I usually use `domain.com` to access system from internet but in case of ISP crashes i need access from LAN directly by IP? How to get it?

**Comment by davide-alghi** [comment]
Hi Vladimir,
if I understand correctly, you have the YF server locally and your provider DNS maps a public domain (e.g. www.yfdom.ru) to your internet router (and, obviously, your internet router redirects to local IP address). So you point to www.yfdom.ru to access to YF.

I can suggest you this:

1. install a small local DNS server (with internet access)
2. on local DNS server, map www.yfdom.ru to local IP address
3. configure local DNS (IP address) as secondary DNS on all clients those needs to access to YF

this allows you to access to domain regardless of the provider and speed up the YF access

**Comment by vovpff** [comment]
@davide-alghi thx for your advice. Whan software you can recommend for ubuntu? Maybe you can also give some article about installation and adjustments?

**Comment by davide-alghi** [comment]
**dnsmasq** is light and easy
this could help
https://computingforgeeks.com/install-and-configure-dnsmasq-on-ubuntu-18-04-lts/

- pay attention to ```systemctl stop systemd-resolved``` command
- IP to domain mapping is achieved by /etch/hosts

_errata corrige about 3rd point_: you have to set as primary DNS on local clients

**Comment by vovpff** [comment]
@davide-alghi Thx a lot for your help. I has some problems with `dnsmasq` because my server has BIND server and I can't start dnsmasq easy as written at your manual but this is not big problem.

**Comment by davide-alghi** [comment]
you can use BIND for your goal

**Comment by vovpff** [comment]
@davide-alghi I think so but I need some time for adjustments
