### ISSUE TITLE
[Question] Jak wyłączyć System warnings na maila?

### ISSUE THREAD

**Issue by yotuze** [YetiForceCompany/YetiForceCRM#12020]
### Description
Witam,
Jak wyłączyć ciągłe e-maile System warnings o np. braku szyfrowania? Mam testowy serwer gdzie nie chce jeszcze szyfrować a dostaje ciągle powiadomienia na maila nawet 4 jednocześnie.

**Comment by bpabiszczak** [comment]
Najlepiej wyłączyć akcje w cronie ;)
![image](https://user-images.githubusercontent.com/10197525/73941544-c3581480-48ed-11ea-851e-5218dcd8f418.png)
