### ISSUE TITLE
[bug] CurrencyUpdate module --> Error while downloading the exchange rate table

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#12023]
Hi,

FYI, module not working and display an error on both gitstable and gitdeveloper official demo :

https://gitstable.yetiforce.com/index.php?module=CurrencyUpdate&view=Index&parent=Settings&block=5&fieldid=88

https://gitdeveloper.yetiforce.com/index.php?module=CurrencyUpdate&view=Index&parent=Settings&block=5&fieldid=88

Apparently, it's related to the following URL that return a 404 error 👍 http://api.nbp.pl/api/exchangerates/tables/a/2019-11-11/?format=json

Regards,

**Comment by apcloic** [comment]
It looks like there is an issue on NBP side, using date is not working but using "today" instead is OK :
http://api.nbp.pl/api/exchangerates/tables/a/today/?format=json

**Comment by apcloic** [comment]
Ok, I found the explanation : last monday was 11th of November, so obviously it was not a working day !

**Comment by SobiDE** [comment]
On my fresh install still doesn't work, and I see also in the official demo it's still displaying the error message...

**Comment by apcloic** [comment]
> On my fresh install still doesn't work, and I see also in the official demo it's still displaying the error message...

yes, as currency update is based on 'last monday' rate which is not a working day so the error will still appear until next monday.

**Comment by konadrian** [comment]
On current versions works fine, also with 11/11 date
