### ISSUE TITLE
[PL ] Nie przetłumaczony tekst w polu

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1202]
KONFIGURACJA SYSTEMU>DOSTOSUJ MODUŁY>WIDGETY MODUŁU.
Klikam na przycisk WIDGET (z ikonką plusa) otwiera się okno, w  polu wybierz WIDGET - nie przetłumaczony tekst - " Selec an option "

https://gitmaster.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67
![13](https://cloud.githubusercontent.com/assets/11139594/8404697/4e343cec-1e4f-11e5-8d6b-d3be1444796e.png)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1218
