### ISSUE TITLE
[bug] Update package cracked Reservations

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12024]
Installed 5.2.0_ServicePack_v18.zip and Reservations graphical calendar became "unclickable".
No errors shown in console, no errors in logs.
Anyone noticed that too?

**Comment by TonyM15** [comment]
True, I have the same here

**Comment by JohnMaverick** [comment]
the same I have. Debugging shows nothing

**Comment by paula-w** [comment]
It works properly in SP version 19, you can check it on [gitstable](https://gitstable.yetiforce.com/). 
We’re changing the reservations calendar today, we’re substituting it with the one currently used in the Calendar module.

**Comment by TonyM15** [comment]
will it demolish previous Reservations records?
