### ISSUE TITLE
[Feature] Related list - mass edit

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12034]
Will it be exhausting task to add mass edit feature to related lists?

**Comment by JohnMaverick** [comment]
Truly important feature. If YF do that it will beat Vtiger a lot... as far as I remember it was always claimed from developer but ignored constantly.

**Comment by mariuszkrzaczkowski** [comment]
it takes about 8 - 16 hours, a lot of old code that needs to be rewritten.

**Comment by mariuszkrzaczkowski** [comment]
something similar is in the campaign module

**Comment by apcloic** [comment]
also similar in Occurrences module
#12496
