### ISSUE TITLE
SQLSTATE[28000] [1045] Access denied for user 'Username'@'localhost' (using password: YES)[bug] 

### ISSUE THREAD

**Issue by Digitisory** [YetiForceCompany/YetiForceCRM#12039]
SQLSTATE[28000] [1045] Access denied for user 'Username'@'localhost' (using password: YES)[bug] 

# 🐞 bug report

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by vovpff** [comment]
Ok. What is the question?

**Comment by Digitisory** [comment]
I am getting this error when trying to access the CRM. Yesterday I tried to
upgrade the CRM from 5.1 to 5.2. It did not work so I reverted to my back
up. But after doing so I am now getting this error.
https://digitisory.com/yeti/index.php

**Comment by vovpff** [comment]
@Digitisory do you have direct access to database using your database login and password?

**Comment by Digitisory** [comment]
I have access to the Cpanel, if that is what you mean.

**Comment by vovpff** [comment]
I mean database. Password for database and Cpanel can be different

**Comment by Digitisory** [comment]
Thank you Vladimir, I have solved it now.

I have some new problems though. How do I do an update from 5.1 to 5.2?
And how do I export contacts and leads from the CRM? When I choose the
action to Export Selected Records

**Comment by vovpff** [comment]
@Digitisory pls open new issue if you have problems.
Usualy you need to select records before export. After that click export and choose file format.
