### ISSUE TITLE
[bug] I upgraded to 5.2 from 5.1. Now I cannot log into the CRM at all

### ISSUE THREAD

**Issue by Digitisory** [YetiForceCompany/YetiForceCRM#12033]
# 🐞 bug report

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by vovpff** [comment]
Check /cache/logs/update.log. Looks like your update was unsuccessful...
