### ISSUE TITLE
[bug] Uppercase letters from A to Z

### ISSUE THREAD

**Issue by hilligsmann** [YetiForceCompany/YetiForceCRM#12037]
Hello, 

when trying to add a user to the system, on final SAVE, the system gives me the error message "Uppercase letters from A to Z". There's no field marked in red.

Could you please help?

**Comment by rskrzypczak** [comment]
Password.
check https://gitdeveloper.yetiforce.com/index.php?module=Password&parent=Settings&view=Index&block=7&fieldid=38
