### ISSUE TITLE
[PL]  Zbyt wąskie pole

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1203]
KONFIGURACJA SYSTEMU>DOSTOSUJ MODUŁY>WIDGETY MODUŁU.
Klikam na przycisk WIDGET Z FILTREM – otwiera się okno, nazwa w liście wyboru – WYBIER -  nie mieści się w polu

https://gitmaster.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67
![14](https://cloud.githubusercontent.com/assets/11139594/8404783/194d9964-1e50-11e5-90b0-3933b28b723d.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/a60cc838bfa8682bb2de8d2fda28e1e9e7644557
