### ISSUE TITLE
[bug] Workflows Task type-Notifications variables

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#12031]
Gitdeveloper  [ver. 5.2.62]
and GitStable
Testet on my  Server YETIFORCE 5.2.18, same error...

![varialble](https://user-images.githubusercontent.com/25682437/68858117-97f5cd00-06e4-11ea-8538-4fe942f94f43.gif)

Lep pozdrav

Bojan

**Comment by fbojan** [comment]
Can anyone please help me with this error. To me, this is the most important part of the app...

**Comment by calvinsug** [comment]
ahhh, i have the same desire to inject the variable. Did you find any solution ?

**Comment by fbojan** [comment]
> Can anyone please help me with this error. To me, this is the most important part of the app...

**Comment by mariuszkrzaczkowski** [comment]
https://user-images.githubusercontent.com/10198654/104893427-b5bb6380-5973-11eb-9d61-01bd2df5d605.mp4
