### ISSUE TITLE
[Feature] custom fields per product

### ISSUE THREAD

**Issue by zabos13** [YetiForceCompany/YetiForceCRM#12046]
hello it will be great if we create example 2 products with different fields.Like custom fields per product

**Comment by vovpff** [comment]
What is the main purpose of this feature? What is your target?

**Comment by davide-alghi** [comment]
Hi,
if your **product / service** - **types / typologies** number is limited, i.e. 10-15, you can do that creating a custom module per type / typology.

1. create a new module similar to product / service module
2. add new module to target inventory module (sales order, invoice, quote and so on) into advanced **item name** field

**Comment by zabos13** [comment]
i have one product that is pvc windows.the custom fields in the product is  1.dimensions 2.color
the second product is  doors and the fields is 1. size 2. material.

**Comment by mariuszkrzaczkowski** [comment]
how many product types you have, the easiest way is to create a new module

**Comment by vovpff** [comment]
@zabos13 simpliest way to add products like window 100x100 white, window 100x100 brown and etc.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski how this modules will work with quantity on stock calculation?

**Comment by vovpff** [comment]
@zabos13 if you don't have products on stock you can add additional columns to product table:
- Value or picklist for size. 
- Picklist for color.

**Comment by zabos13** [comment]
thanks for the help !!! i dont have quantity neither stock.

**Comment by zabos13** [comment]
i understand but when i see windows i dont want to see the fields that i have in doors

**Comment by zabos13** [comment]
can  i have unique fields in quotes templates??

**Comment by mariuszkrzaczkowski** [comment]
use dependencies between the selection list

**Comment by mariuszkrzaczkowski** [comment]
see
https://gitdeveloper.yetiforce.com/index.php?module=HideBlocks&parent=Settings&view=List&block=2&fieldid=72

**Comment by zabos13** [comment]
ok i will try it!!!
