### ISSUE TITLE
[Question] Customizing quotes and invoice

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#12056]
I tried searching the git closed  and googled for how to create custom invoice and quotes but was not successful.  can someone direct to the link how to do use variable and with the using concept behind it.

**Comment by davide-alghi** [comment]
Hi,
here to custimize invoice
https://gitstable.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=FInvoice

here for quote
https://gitstable.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=SQuotes

**Comment by gkArvindr** [comment]
@Davide Algh, thanks for the reply, I know how to customize fields, I want the syntax concepts of calling the fields to create customize template for pdf, which is in html format . 

example "accountid" is  a field and this is how it is represented $(relatedRecord : accountid|addresslevel8a|Accounts)$ in the example template.

While creating custom template I getting stuck with limited information, one is call custom, other translate : Other.PD. 

I want to know
1. list of fields like relatedRecord, record etc 
2. the concept behind the syntax followed to call the fields in the template to create pdf.

**Comment by gkArvindr** [comment]
![Untitled](https://user-images.githubusercontent.com/24363648/69209342-dc69e880-0b7c-11ea-959c-aba55f3e44b9.png)

How do I bring this fields in to pdf template

**Comment by rskrzypczak** [comment]
you can use the variable in your pdf template
![image](https://user-images.githubusercontent.com/10221999/69214090-49be4f00-0b66-11ea-8cc2-b8464fc97363.png)

or use this
![image](https://user-images.githubusercontent.com/10221999/69214202-8b4efa00-0b66-11ea-8958-f47fe9392ded.png)

then you'll see
![image](https://user-images.githubusercontent.com/10221999/69214239-a3bf1480-0b66-11ea-84b7-52e4c7189688.png)

**Comment by mariuszkrzaczkowski** [comment]
or
```
$(inventory : type=table columns=name,qty,price href=yes)$
$(inventory : type=table columns=seq,name,qty,unit,price,total,net href=no)$
```

**Comment by gkArvindr** [comment]
I still find it difficult is there a workflow diagram somewere, i will write the help doc for this once I am successful and share the same

**Comment by gkArvindr** [comment]
[1574234708.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/3867893/1574234708.pdf)

I got the data, but header labels are showing variables instead of actual names

**Comment by gkArvindr** [comment]
![Untitled](https://user-images.githubusercontent.com/24363648/69219242-712e0f80-0b98-11ea-88ba-4d55b5e68b04.png)

**Comment by gkArvindr** [comment]
![Screenshot from 2019-11-20 13-19-32](https://user-images.githubusercontent.com/24363648/69219293-93279200-0b98-11ea-94ca-a25c648f1ea4.png)

**Comment by vovpff** [comment]
@gkArvindr looks like your template language has no translation for columns labels.

**Comment by gkArvindr** [comment]
![Screenshot from 2019-11-20 16-32-20](https://user-images.githubusercontent.com/24363648/69233723-7056a700-0bb3-11ea-90f6-d07ce20c3e51.png)
I am not getting the dynamic template, where could be I going wrong

**Comment by gkArvindr** [comment]
@vovpff where should i check for it. please update

**Comment by gkArvindr** [comment]
@rskrzypczak can you help me, i dont see the dynamic template,

**Comment by vovpff** [comment]
@gkArvindr for dynamic template
![image](https://user-images.githubusercontent.com/8545791/69235242-ff5ac380-0ba1-11ea-9d0e-198a370deeeb.png)
For language try to change template language at first step of pdf template params.Try different languages

**Comment by gkArvindr** [comment]
@vovpff I tried with other lang, the status is the same, it shows only variable not the translated language

**Comment by vovpff** [comment]
Try other variables for products table. maybe this variable broken...

**Comment by gkArvindr** [comment]
@vovpff I tried sale invoice with the inbuilt template, there too the same issue 
![Screenshot from 2019-11-20 18-08-53](https://user-images.githubusercontent.com/24363648/69239733-eb728a00-0bc0-11ea-962a-b6796476ffdc.png)

**Comment by gkArvindr** [comment]
![Screenshot from 2019-11-20 18-08-53](https://user-images.githubusercontent.com/24363648/69239865-35f40680-0bc1-11ea-9fca-252c010ed81f.png)
I tried with sale invoice, the same issue.

**Comment by gkArvindr** [comment]
@vovpff I also updated the language files just to ensure

**Comment by mariuszkrzaczkowski** [comment]
did you set the language in the PDF template?

**Comment by gkArvindr** [comment]
yes I did to en_US and again tried fr_FR

**Comment by gkArvindr** [comment]
![Screenshot from 2019-11-20 18-24-09](https://user-images.githubusercontent.com/24363648/69240723-165ddd80-0bc3-11ea-858e-0ba7dcea808f.png)

Screen shot for your reference

**Comment by gkArvindr** [comment]
In Parallel I install a new by downloading the latest version all the titles displayed perfectly , as soon as i create a custom pdf template, the language translate stopped working, I deleted the created custom pdf template, still the  language translate stopped working. does it give you any clue

**Comment by gkArvindr** [comment]
I was able to produce the same issue again and again

**Comment by gkArvindr** [comment]
@mariuszkrzaczkowski @vovpff 
I experimented with many options, I reinstalled the whole application 3 times, now I feel the when creating custom pdf the language factor is not passing to while processing pdf file, it there anyway I can check to find out why it happens to custom pdf

**Comment by gkArvindr** [comment]
@mariuszkrzaczkowski @vovpff 

I had a doubt that it was not saving language , i checked the table Table: a_yf_pdf and it was well saved , 
![Screenshot from 2019-11-21 08-33-33](https://user-images.githubusercontent.com/24363648/69300667-e30a6580-0c39-11ea-8c56-778787cfb9a9.png)

**Comment by rskrzypczak** [comment]
so check your language settings (try to modify) and global language settings.
![image](https://user-images.githubusercontent.com/10221999/69306003-5efab280-0c26-11ea-8efa-1478a6aa8aeb.png)
![image](https://user-images.githubusercontent.com/10221999/69306104-b0a33d00-0c26-11ea-9bee-1fc349b08cf4.png)

**Comment by gkArvindr** [comment]
![Screenshot from 2019-11-21 11-04-01](https://user-images.githubusercontent.com/24363648/69306884-fffd6380-0c4e-11ea-8b6f-42b479ce8829.png)
![Screenshot from 2019-11-21 11-04-28](https://user-images.githubusercontent.com/24363648/69306892-0a1f6200-0c4f-11ea-8fd0-535ca52a67b6.png)

I think that's not a issue

**Comment by gkArvindr** [comment]
![Screenshot from 2019-11-21 11-09-22](https://user-images.githubusercontent.com/24363648/69307112-b103fe00-0c4f-11ea-8246-becbbd55975c.png)
Pdf after ensuring all languages are set, I think it is when modified somewhere the language parameter is getting passed to pdf processed

**Comment by mariuszkrzaczkowski** [comment]
Attach a screenshot of the server configuration

**Comment by mariuszkrzaczkowski** [comment]
you have wrong language code
![image](https://user-images.githubusercontent.com/10198654/69315439-cf113480-0c36-11ea-9d4c-2ffb78805802.png)

**Comment by hobejeans** [comment]
I had the same issue for months. I changed the Language to **en-US** in the language field all my PDF templates and now they are working perfectly. I opened MySql/a_yf_pdf/ edit template then scroll down to the language field and change to en-US. Thank you
