### ISSUE TITLE
[PL] Nie przetłumaczone wyrazy

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1205]
KONFIGURACJA SYSTEMU>DOSTOSUJ MODUŁY>Zarządzanie szablonami drzew
Nie przetłumaczone na język polski: CATEGORY i RESERVATIONS

https://gitmaster.yetiforce.com/index.php?module=TreesManager&parent=Settings&view=List&block=2&fieldid=70
![16](https://cloud.githubusercontent.com/assets/11139594/8405033/fa37b5b2-1e51-11e5-8b52-6478c24a322c.png)

**Comment by MaciejStencel** [comment]
Nazwy własne wprowadzone przez użytkownika systemu. Nie sa tłumaczone.
