### ISSUE TITLE
[Question] REST Error (406): ERR_VALUE_IS_TOO_LONG

### ISSUE THREAD

**Issue by yotuze** [YetiForceCompany/YetiForceCRM#12059]
### Description
Witam,
Chcąc dodać kontrahenta przez REST API dostaje błąd:

`REST Error (406): ERR_VALUE_IS_TOO_LONG||accountname||Accounts||<DŁUGA_NAZWA_KONTRAHENTA>`

W bazie widziałem, że ograniczenia dla nazw Leadów i Kontrahentów to 100 znaków, co ciekawe u Dostawców to 255. Zwiększyłem oba do 255 znaków ale widocznie, w którymś pliku jest validacja do 100 znaków, gdzie trzeba jeszcze zmienić żebym mógł dodawać rekordy z długą nazwą za pomocą API ale również ręcznie? W Moduły - Pola ustawiłem Maksymalna długość tekstu na 255 ale API ignoruje to.

Pozdrawiam

**Comment by yotuze** [comment]
Macie dość przedmiotowe podejście do użytkowników. Zgłaszają Wam błąd, odnotowujecie to i temat do zamknięcia. Rozumiem, że musicie jakoś zarabiać ale na tym polega Opensource, wy macie feedback my mamy CRMa i jeśli coś nie wymaga pisania setek linii kodu to chyba moglibyście odpowiedzieć na tego typu pytanie? 

A w tym wypadku jestem przekonany, że wiecie jaka jest odpowiedź, bo samemu udało mi się do tego dojść ale musiałem przeszukać całą bazę, i zamiast pomóc to każecie czekać do 5.3.

Jakby ktoś szukał rozwiązania to w tabeli **vtiger_field** trzeba znaleźć interesujące nas pole, w tym wypadku **accountname** i zwiększyć maximumlength do **255**.

Pozdrawiam

**Comment by rskrzypczak** [comment]
> Macie dość przedmiotowe podejście do użytkowników. Zgłaszają Wam błąd, odnotowujecie to i temat do zamknięcia. 

![image](https://user-images.githubusercontent.com/10221999/69126635-f20dde00-0aa8-11ea-9e24-1dd93eb079fd.png)

..co wyczerpuje temat :)

**Comment by bpabiszczak** [comment]
@yotuze jesteśmy jak stare wygi... rzadko piszemy ładny opis, często zamykamy za pomocą "commit-a" który jest odpowiedzią na Twoje pytanie. Odpowiedzieliśmy Tobie w sposób techniczny [podając link do tego co należy zmienić i gdzie] ale takie opisy nie są zrozumiałem dla osób nietechnicznych... 

PS. należy również zmienić w tabeli vtiger_account [dokładne zmiany masz podane tam, gdzie pokazuje to Radek]. 
PS2. Co złego to nie my ;)
PS3. Kup wsparcie za 25 euro i wszyscy będą szczęśliwi :D
