### ISSUE TITLE
[Question] Edit Account Look up column in Ticket Create module

### ISSUE THREAD

**Issue by calvinsug** [YetiForceCompany/YetiForceCRM#12052]
Hi guys,

i'm using Yetiforce 5.1.0.

Just wondering if we can change filter account when we search Account in Create a new Ticket page.

Here's the lookup menu i go through from Create a new ticket page:
https://drive.google.com/open?id=1i_U39LxYX93zIiilbfEcj89J0n1X8IF6

and here's the screenshoot after i click the search button in previous screenshoot and i need to change the Account's shown column:
https://drive.google.com/open?id=1tEqpe1k2iyhs_FV8AC587bODLUzXuCCX

I have explored the configuration, but i just found the filter configuration and it only can change the column we want to shown in Account Module

**Comment by davide-alghi** [comment]
Hi,
that is possible only modifying Account primary class (core code), but changes will be rewritten on next YF update/upgrade

**Comment by calvinsug** [comment]
ok, i already tried the version 5.2.0 on other windows computer and the issue has been solved
