### ISSUE TITLE
[PL] Tekst nie przetłumaczony w ukrywanie bloków

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1207]
KONFIGURACJA SYSTEMU>DOSTOSUJ MODUŁY>Ukrywanie bloków
Obok pola WIDOK – tekst w liście wyboru nie przetłumaczony – SELECT SOME OTIONS
https://gitmaster.yetiforce.com/index.php?mod
![18](https://cloud.githubusercontent.com/assets/11139594/8405227/397fb05c-1e53-11e5-92bb-ac91dc8fd09b.png)
ule=HideBlocks&parent=Settings&view=Edit

**Comment by waw555** [comment]
And as indented text

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1218
