### ISSUE TITLE
Database Update Issues

### ISSUE THREAD

**Issue by Coonzoba** [YetiForceCompany/YetiForceCRM#12073]
Hi Yeti Team,

I apologize, I got overly excited to try out the new features (which are awesome, well done) so I flew through 4.4.0>5.0>5.1>5.2 without actually trying to save records.

Turns out the 4.4.0>5 update didn't add the crmid columns, and now I can't do...anything really.

Is there a manual way I can do this / what tables should it be in? Or can I alter the php files of that update as a 5.2.1 update and try trimming it to just the database changes?

Thank you so much for your help and sorry for the hassle.

[updateLogTrace is here](https://gist.github.com/Coonzoba/7ef0e2c4009d5c114ee8f90b8cdbe6cb)

**Comment by mariuszkrzaczkowski** [comment]
here is your answer #11671
