### ISSUE TITLE
[bug] Custom PDF only non translated labels prinitng

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#12076]
refer : #12056 
I think it is a bug as I am able to reproduce it again and again
While creating Custom PDF the labels are not getting translated to language.
![Screenshot from 2019-11-20 13-19-32](https://user-images.githubusercontent.com/24363648/69303587-97f55000-0c43-11ea-88fd-1f85cf3ccdc3.png)

**Comment by vovpff** [comment]
Pls put your source code of html template.

**Comment by gkArvindr** [comment]
this is only code 
$(custom : DynamicInventoryColumnsTable)$

**Comment by gkArvindr** [comment]
I added this code
$(general : BaseTimeZone)$ in Heading 
$(custom : DynamicInventoryColumnsTable)$ in content 
![Screenshot from 2019-11-21 10-00-18](https://user-images.githubusercontent.com/24363648/69304233-eb689d80-0c45-11ea-9135-96b7891fff61.png)

**Comment by gkArvindr** [comment]
[1574311509.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/3872841/1574311509.pdf)
@vovpff  even if download the template and uploaded the same template as new template, the label are not using language

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/12056#issuecomment-556924671

**Comment by mariuszkrzaczkowski** [comment]
What version do you have

**Comment by gkArvindr** [comment]
YetiForce.com All rights reserved. [ver. 5.2.0] 

running on 
 Linux bh-74.webhostbox.net 2.6.32-954.3.5.lve1.4.61.el6.x86_64 #1 SMP Thu Mar 14 07:14:46 EDT 2019 x86_64

**Comment by mariuszkrzaczkowski** [comment]
Attach a screenshot of the server configuration

**Comment by gkArvindr** [comment]
here it the full details 
[server.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/3873242/server.pdf)

**Comment by mariuszkrzaczkowski** [comment]
I mean this: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65

**Comment by gkArvindr** [comment]
![Screenshot from 2019-11-21 12-52-05](https://user-images.githubusercontent.com/24363648/69316232-62119500-0c5e-11ea-81ff-a7d60afbc94a.png)
![Screenshot from 2019-11-21 12-52-34](https://user-images.githubusercontent.com/24363648/69316233-62119500-0c5e-11ea-804d-ed7423d1508b.png)
![Screenshot from 2019-11-21 12-52-51](https://user-images.githubusercontent.com/24363648/69316234-62aa2b80-0c5e-11ea-9e29-5036954c7001.png)
![Screenshot from 2019-11-21 12-53-12](https://user-images.githubusercontent.com/24363648/69316236-62aa2b80-0c5e-11ea-805a-5a09787670fd.png)
![Screenshot from 2019-11-21 12-53-30](https://user-images.githubusercontent.com/24363648/69316238-62aa2b80-0c5e-11ea-9275-79a20b89d4c1.png)
![Screenshot from 2019-11-21 12-53-57](https://user-images.githubusercontent.com/24363648/69316239-6342c200-0c5e-11ea-9726-178e6237f18b.png)
![Screenshot from 2019-11-21 12-54-19](https://user-images.githubusercontent.com/24363648/69316240-6342c200-0c5e-11ea-9f29-ff6c5324d129.png)
![Screenshot from 2019-11-21 12-54-35](https://user-images.githubusercontent.com/24363648/69316241-6342c200-0c5e-11ea-8b87-ef7dc16da0b4.png)

**Comment by mariuszkrzaczkowski** [comment]
set in php.ini 
request_order=GP
![image](https://user-images.githubusercontent.com/10198654/69316741-c40bd380-0c39-11ea-9cd6-32baa20542ea.png)

**Comment by gkArvindr** [comment]
@mariuszkrzaczkowski 
Modified php.ini and enabled GP 
![Screenshot from 2019-11-21 18-09-06](https://user-images.githubusercontent.com/24363648/69338860-0f4dd280-0c8a-11ea-92c2-2ae0a1998cf3.png)

still the language is not getting populated

**Comment by mariuszkrzaczkowski** [comment]
check this
![image](https://user-images.githubusercontent.com/10198654/69339221-262dfe00-0c65-11ea-81da-90272a6769d9.png)

**Comment by gkArvindr** [comment]
Yes, it is showing en_US

**Comment by gkArvindr** [comment]
@mariuszkrzaczkowski my feel is when template is modified, it does not pass the language parameter to the pdf making process

**Comment by mariuszkrzaczkowski** [comment]
after changing the php.ini configuration, edit the pdf template and check what has been saved to the database

**Comment by gkArvindr** [comment]
![Screenshot from 2019-11-21 18-43-32](https://user-images.githubusercontent.com/24363648/69341085-e1b75800-0c8e-11ea-9cd3-bf6a3eec844b.png)
@mariuszkrzaczkowski IT WORKED !! thanks
