### ISSUE TITLE
[bug] https://gitdeveloper.yetiforce.com/cron.php returns "file not found"

### ISSUE THREAD

**Issue by chops888** [YetiForceCompany/YetiForceCRM#12081]
Not an actual bug with the application, obviously. But my inbox is lighting up with Cron daemon failures due to your site being down, so I've disabled the cron job on my system. No status notice on your website that I can see, so I guess reply here when it's fixed?

Thanks

**Comment by gkArvindr** [comment]
please provide the cron details and the server details

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/69403482-f8939400-0cfa-11ea-82d9-d3ed74afd470.jpg)

**Comment by chops888** [comment]
Its up and running now. All good.

**Comment by chops888** [comment]
FYI - https://gitdeveloper.yetiforce.com - was displaying a "Server is restarting" msg all day yesterday, and https://gitdeveloper.yetiforce.com/cron.php -- with api key or without, was returning "File not found" -- as stated in the title of the ticket.
