### ISSUE TITLE
[Question] knowledge base add related docs

### ISSUE THREAD

**Issue by sartormary** [YetiForceCompany/YetiForceCRM#12085]

**Comment by mariuszkrzaczkowski** [comment]
?

**Comment by sartormary** [comment]
I had a problem to relate knowledge base pages

Il giorno sab 23 nov 2019 alle 13:29 Mariusz Krzaczkowski <
notifications@github.com> ha scritto:

**Comment by mariuszkrzaczkowski** [comment]
describe more precisely

**Comment by sartormary** [comment]
Add a page to knowledge base, trying to find related pages of the knowledge
base, but no pages find.

Il giorno sab 23 nov 2019 alle 21:01 Mariusz Krzaczkowski <
notifications@github.com> ha scritto:
