### ISSUE TITLE
[bug] Zablokowane moduły przez Błąd!!! Call to a member function get() on boolean

### ISSUE THREAD

**Issue by rbtm** [YetiForceCompany/YetiForceCRM#12082]
Chyba trochę za dużo modułów zostało wyłączonych i co z tym teraz począć? :-(

Proszę o pomoc, dziękuję.

![1](https://user-images.githubusercontent.com/58072546/69419976-ff7fce00-0d1d-11ea-985d-caf7e801b6e8.png)

![yetiforce_settings](https://user-images.githubusercontent.com/58072546/69420013-0f97ad80-0d1e-11ea-9159-0496a12403a0.png)

**Comment by mariuszkrzaczkowski** [comment]
logi

**Comment by rskrzypczak** [comment]
You have probably disabled e-mail modules.
Related: https://github.com/YetiForceCompany/YetiForceCRM/issues/11437, #11945, #10279
Fix: https://github.com/YetiForceCompany/YetiForceCRM/commit/29f58e8f570ca4687e77bcb5f757b3d6a8381c3b, https://github.com/YetiForceCompany/YetiForceCRM/commit/2d379ef3f35aee2e6bda71ea1a3f2c47af2eafc4
