### ISSUE TITLE
[Question] Prices in invoice performa

### ISSUE THREAD

**Issue by Rizzao** [YetiForceCompany/YetiForceCRM#12083]
Hello there. I have an issue.
I needed to create similar module like '''Products'' so I created it. I tried adding the prices to othe module but it does not seem to display when I try writing a new Performa Invoice. Anyone knows how to do this? I added a picture showing the issue.

![prices](https://user-images.githubusercontent.com/50708917/69428494-fdc40380-0d39-11ea-953e-bf2653a2fb80.JPG)

**Comment by Rizzao** [comment]
Can anyone help?

**Comment by bpabiszczak** [comment]
A programmer must help you.
