### ISSUE TITLE
[Question] Cell border width/color

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12098]
Trying to set global values for tables borders but whatever I do with 'td' I cannot get border visible in pdf report. Background OK. Where is the trick?

'table' => [
			'display' => 'table',
			'border-collapse' => 'separate',
			'border-spacing' => '3px',
			'border-color' => '#ccc',
			'border-width' => '1px',
		],
		'tbody' => [
			'display' => 'table-row-group',
			'vertical-align' => 'middle',
			'border-color' => 'inherit',
		],
		'td' => [
			'display' => 'table-cell',
			'vertical-align' => 'inherit',
			'padding' => '1px',
			'border-color' => '#ccc',
			'border-width' => '1px',

**Comment by vovpff** [comment]
@waran70 what is your solution?
