### ISSUE TITLE
changing name of the module is apparent 

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#121]
becouse it don't change the labels of the related fields in another modules. Suggestion to relate changes between names of the module and names of the fields.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
in order to proceed on this issue we require more info, such as examples or screenshots with highlighted names which you would like to translate.

**Comment by bpibiza** [comment]
Hi, 
for example: 
If You change - in the system menu - name of the module called "Projects" for "blablabla" You will see the change only in  the menu bar. Name of this module used as related fields in another modules will be without changes (still Project /s).

**Comment by bpabiszczak** [comment]
your idea would limit the existing functionality, now it is possible to name the same module differently in various places; this is a much better alternative. If you would like to change names everywhere, you can run language files in notepad ++ and change them in all files or you can do it manually from the level of language editor.
