### ISSUE TITLE
[PL] [bug]Status płatności w module faktur

### ISSUE THREAD

**Issue by piotr-siedlak** [YetiForceCompany/YetiForceCRM#12103]
# 🐞 bug report

Po dodatnie wpłaty i powiązaniu jej z FV, status płatności nie zmienia się. Ręcznie również nie można go zmienić ze względu na pole systemowe.

### 🔥 How to trigger the error
Dodać FV
Dodać wpłatę powiązaną z FV
Sprawdzić status płatności.
<img width="1589" alt="Zrzut ekranu 2019-11-25 12 33 14" src="https://user-images.githubusercontent.com/42056358/69537159-c777c580-0f7f-11ea-9868-59163d3a703e.png">

Screen konfiguracji:
![yetiforce_settings-2](https://user-images.githubusercontent.com/42056358/69537090-a020f880-0f7f-11ea-902f-4531b1f96837.png)

**Comment by bpabiszczak** [comment]
Ponieważ musi to zrobić programista :] 
Ale można też samemu wyłączyć na polu, aby nie było polem systemowym... i wówczas będziemy mogli edytować.
![image](https://user-images.githubusercontent.com/10197525/73893425-e5b04a80-4879-11ea-8a8b-64b155cede41.png)
