### ISSUE TITLE
[bug] [PL] Brak wyświetlenia Czasu pracy w module pracownicy

### ISSUE THREAD

**Issue by piotr-siedlak** [YetiForceCompany/YetiForceCRM#12104]
# 🐞 bug report

W module pracownicy, po wejściu w pracownika i przejściu do zakładki "Czas Pracy" nie wyświetlają się rekordy powiązane. 
<img width="1560" alt="Zrzut ekranu 2019-11-25 12 36 40" src="https://user-images.githubusercontent.com/42056358/69537576-b4192a00-0f80-11ea-8c24-0e3f226f0998.png">
<img width="1672" alt="Zrzut ekranu 2019-11-25 12 36 54" src="https://user-images.githubusercontent.com/42056358/69537577-b4b1c080-0f80-11ea-97c6-f597ad0ccc81.png">
<img width="1680" alt="Zrzut ekranu 2019-11-25 12 37 44" src="https://user-images.githubusercontent.com/42056358/69537578-b4b1c080-0f80-11ea-8837-bbe207e7cacb.png">

### 🔥 How to trigger the error
1. Utworzyć pozycję w module "czas pracy" powiązaną z pracownikiem
2. Wejść w moduł "Pracownicy"
3. Przejść do zakładki "czas pracy"
4. Sprawdzić czy występuje rekord powiązany.

Konfiguracja:
![yetiforce_settings-2](https://user-images.githubusercontent.com/42056358/69537562-aebbdf80-0f80-11ea-9465-7d9cbeac69b9.png)

W pliku /cache/logs/system.log, nie występują żadne wpisy podczas przechodzenia do zakładki "czas pracy" tak samo przy tworzeniu "czasu pracy".

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/73890954-6b7cc780-4873-11ea-9d4a-b1b77b1791c2.png)
