### ISSUE TITLE
[Question]  [PL] Maile wychodzące oznaczane są jako wewnętrzne.

### ISSUE THREAD

**Issue by piotr-siedlak** [YetiForceCompany/YetiForceCRM#12105]
Dzień dobry,
czy w module "Maile firmowe" da się jakoś zmienić oznaczanie maili tak aby maile wychodzące były kategoryzowane jako maile "Wychodzące" a nie "wewnętrzne"?

Screeny z modułu "Maile firmowe"
<img width="1670" alt="Zrzut ekranu 2019-11-25 12 52 35" src="https://user-images.githubusercontent.com/42056358/69538441-99e04b80-0f82-11ea-90ac-2a7221c7b636.png">
<img width="1599" alt="Zrzut ekranu 2019-11-25 12 53 21" src="https://user-images.githubusercontent.com/42056358/69538442-99e04b80-0f82-11ea-8a42-db91a859884c.png">

Odtworzenie błędu:
1. Wysłać maila poprzez round cube
2. Odczekać do następnego przebiegu CRON
3. Sprawdzić oznaczenie maila w module "Maile Firmowe"

Konfiguracja:
![yetiforce_settings-2](https://user-images.githubusercontent.com/42056358/69538210-1161ab00-0f82-11ea-8c4a-389062f48cb7.png)

W logach nie ma błędów. Jeśli potrzebne są dodatkowe dane proszę o podanie sposobu ich pobrania - plik logu system jest bardzo obszerny jeśli włączę pełne logowanie.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/69538111-dc555880-0f81-11ea-8fe2-a13985491a34.jpg)

**Comment by bpabiszczak** [comment]
Maile wewnętrzne to takie, które wychodzą od pracownika do pracownika. Nie ma znaczenia czy mail ten przychodzi czy wychodzi. Od strony technicznej może to zmienić w skryptach za to odpowiedzialnych.

Nie jest to błąd, tak zostało to zaprojektowane. Niestety nie widać nic w zrzutach, więc zakładam, że jest tak jak napisałem.

**Comment by piotr-siedlak** [comment]
Niestety błędnie Pan zakłada. Może warto dopytać jeśli nie jest się pewnym... A maile o których pisze są do całkowicie innych osób nie będących w organizacji. Ale dziękuję za informacje, że można to zmienić w skrypcie, odszukam i zmienię.

**Comment by bpabiszczak** [comment]
Sprawdzimy...

**Comment by mariuszkrzaczkowski** [comment]
Mechanizm oznaczania wiadomości mail w wersji deweloperskiej (5.3.0) został przebudowany i działa sporo lepiej zalecamy przetestowanie najnowszej wersji.
