### ISSUE TITLE
[Question] Two custom module and relation/filter

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12112]
Not sure I miss something but:
Have 2 custom modules where one is related to the parent.
In such case when I create filter, the related module fields not showing up in filter conditions.
Can anyone reproduce it?

**Comment by mariuszkrzaczkowski** [comment]
what type of relationship?  1:M or M:M?

**Comment by waran70** [comment]
1:M

**Comment by adudekyeti** [comment]
Hi,
I have a problem to reproduce this issue.
I created two modules: ModuleChild, ModuleParent.
In moduleChild I have field: _ChildField, ParentRelation (1:M):_
![image](https://user-images.githubusercontent.com/39482453/94684394-4cfa9d80-0328-11eb-8613-54af02d544e2.png)

In moduleParent I have field: _ParentField:_
![image](https://user-images.githubusercontent.com/39482453/94684411-5421ab80-0328-11eb-81dd-c6c05ccd8e51.png)


And now on the ModuleChild list I have ParentRelation - ParentField:
![image](https://user-images.githubusercontent.com/39482453/94684554-8206f000-0328-11eb-8644-8490afac86bc.png)

Please try to reproduce this issue on https://gitdeveloper.yetiforce.com/ and give me informations step by step how can I do it by myself.
