### ISSUE TITLE
[Feature] Currency field ToolTip

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12111]
Currency field have no ToolTip allowed. Could be helpful to make it for all type of fields

**Comment by mariuszkrzaczkowski** [comment]
attach a screenshot because I don't know what you mean

**Comment by waran70** [comment]
Hehe... cannot make it as it not exists. I meant here "Content-Sensitive help" - by the way, a bit complex naming though

**Comment by bpabiszczak** [comment]
Works on the gitdeveloper version

![image](https://user-images.githubusercontent.com/10197525/73943012-51cd9580-48f0-11ea-992a-7329d5b92747.png)
