### ISSUE TITLE
[IMPORTANT] PDF Template

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1211]
With the release of the stable version, you need to have a fully working template PDF!

1. You need to add the function of forming the name of the saved file, more precisely, it is necessary not only the date is set automatically, and add the ability to generate the file name of the template variables.

2. You need to add the ability to add images to the template, such as stamp and signature for the account.

**Comment by KatarzynaUlichnowska** [comment]
1. I understand that you don’t report a problem with incorrect saving of files, but you would like to have more options for forming the name of file? If so, it is an enhancement and it will be implemented in 2.2 at the earliest. 
2. It is possible to add images [as normal in html]. Or maybe there is something wrong with this functionality? If so, please describe what it is, how we can reproduce this error and what would be the most optimal solution.

**Comment by waw555** [comment]
2. I would like to make sure that when you create a business proposal had the opportunity to add different pictures and then print this offer with photographs. To poluchaetl I saw that he offered. This function is usually not in demand in the service or company that sells piece goods, such as furniture, telephones, etc., but some companies are unique products that are made to order, so for such companies require this function to be able to set an example in the offer .

1. Formation of the exported file should be more advanced, one date is not enough, as a minimum must be inserted into the file name, the theme of the exported template.

**Comment by MaciejStencel** [comment]
Hi waw555!

I would like more informations. I've checked forming of the file name and yes from the dropdown you can only choose few date formats, but in that input You can paste any variable from that records, for ex. in Quotes:

#yyyy-mm-dd#_#subject#_#requirementcards_id#_#carrier#

Switches nicely when printing to, ex:
2015-07-03_quote_requi_UPS.pdf

If it comes to printing images... you can embed static images in the template. I would need more info about what you are trying to achieve, You would like to print images from invoices related documents? Users can add diffrent file type there, pdf, xls, jpg, png etc etc. 

So it would be best if You would write your own special functions that takes from crm what you want and adds it to pdf file.

If You could give us specyfic algorithm about what You need, how it should work etc we can investigate it and if it can be applied generally to the system we will try to implement it.

If it's specific job for specific customer then it's best to just write custom special function for pdf module.

**Comment by waw555** [comment]
Formation file name

Here is an example of forming nazvapniya file comes first type of document, such as an account, quotation, order, and so on. D., And then the topic of commercial offers, such as "Delivery of piano tuning, etc. PC. D." And then the name of the customer and the date on general name Domenti should be flexible, you can even add a version of the document, if the document was changed, but it's oud in the corresponding module must be

![pdfexample3](https://cloud.githubusercontent.com/assets/1402355/8538049/562885e8-2480-11e5-8005-ea33a26a044f.JPG)

![pdfexample](https://cloud.githubusercontent.com/assets/1402355/8538005/d99fe520-247f-11e5-9a29-425753e57e61.JPG)

![pdfexample2](https://cloud.githubusercontent.com/assets/1402355/8538007/dcc11940-247f-11e5-85a5-d51b05b0d062.JPG)

**Comment by mjapple** [comment]
Hello,
is there any solution for this subject specially for the exported PDF "File name"
How could it be to have the exported PDF filed automatically named after subject of the Quote?

Many Thanks
