### ISSUE TITLE
[Feature] PDF variable "page # of #"

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12110]
In the list of Additional variables (PDF generator) we have missing "Page # of #".
Only current page is available.

**Comment by vovpff** [comment]
There are should be two variables: current page and overall amount of pages in document

**Comment by rskrzypczak** [comment]
You can use :
`Page {p}/{a}` or `Page $(custom : CurrentPage)$/$(custom : AllPages)$`
