### ISSUE TITLE
[IMPROVEMENT] Quotes

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1212]
You need to add the ability to add images to a commercial offer, regardless of the image of the goods, as well as add the ability to export these images to PDF.

This feature is useful when working with the product, which does not have a permanent image is made individually or

**Comment by bpabiszczak** [comment]
This functionality will be available in a new module [with products]. I'm closing this topic, once the problem emerges in the new module please reopen the issue.
