### ISSUE TITLE
[Question] Mapping - reference field

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12135]
Hi, what is the reason behind throwing mapping reference fields to separate workflow (delay in mapping)? Gotta kind of headache because of that

**Comment by JohnMaverick** [comment]
Hey developers, I just realized I have the same problem. Multireference field workflow running every 1 min, but field is updated in some random timeframe I canot get it. 
So if I create mapping, to get reference field updated it takes UNKNOWN time. How to keep it controlled?

**Comment by MixTecnico** [comment]
it is a question to know if it is possible

**Comment by bpabiszczak** [comment]
> what is the reason behind throwing mapping reference fields to separate workflow (delay in mapping)?

We moved this mechanism to the workflow because it slowed down for saving the record.

> How to keep it controlled?

Why control it? The field updates with a delay, this is how this mechanism was designed, we do not plan to change it.
