### ISSUE TITLE
[PL]  Pole edycja koloru – nie zamyka się

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1213]
KONFIGURACJA SYSTEMU>DOSTOSUJ MODUŁY>Konfiguracja kalendarza
Wybieram kolor W EDYCJI klikam na przycisk zapisz i nadal jest otwarte pole EDYCJI KOLORU. Nie zamyka się automatycznie.
https://gitmaster.yetiforce.com/index.php?parent=Settings&module=Calendar&view=UserColors&block=2&fieldid=74
![20](https://cloud.githubusercontent.com/assets/11139594/8408091/78e620a4-1e6d-11e5-911c-9bf4334fce9d.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/f7557da897e0902ecc657055a0a64132420d2571
