### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#12136]
I have exported all my records to .CSV from Yetiforce v5.1 and when I try to import them into v5.2 I receive this error message

![Screen Shot 2019-11-26 at 10 51 33 PM](https://user-images.githubusercontent.com/45261773/69692470-2c2a4180-10a0-11ea-856b-77d81c926084.png)

**Comment by svdaru** [comment]
According to error message, you should change "Character Encoding" at import form to appropriate one or change import file encoding to UTF-8.

> I have exported all my records to .CSV from Yetiforce v5.1 and when I try to import them into v5.2 I receive this error message
> 
> ![Screen Shot 2019-11-26 at 10 51 33 PM](https://user-images.githubusercontent.com/45261773/69692470-2c2a4180-10a0-11ea-856b-77d81c926084.png)

**Comment by hobejeans** [comment]
I changed the encoding to UTF-8 using open office and same result. Is there another way to resolve this issue?

**Comment by manwenick** [comment]
Did you tried to change the delimiter?

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/73942217-fa7af580-48ee-11ea-8dc2-b2992b1aecbc.png)
