### ISSUE TITLE
[Question] [PL] Generowanie FV z Proformy

### ISSUE THREAD

**Issue by piotr-siedlak** [YetiForceCompany/YetiForceCRM#12134]
Dzień dobry,
czy istnieje sposób pozwalający na wygenerowanie FV na podstawie Proformy?
Czy wystarczy powiązać moduły Proforma z Fakturami Sprzedaży czy jest to bardziej skomplikowany proces?

**Comment by bpabiszczak** [comment]
W teorii wystarczy użyć mapowania pól, wówczas w module faktury pro forma pojawi się przycisk generowania faktury sprzedażowej.
