### ISSUE TITLE
[PL] Pole nie przetłumacz. 

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1214]
KONFIGURACJA SYSTEMU>DOSTOSUJ MODUŁY>Konfiguracja kalendarza
Trzecia zakładka DNI WOLNE OD PRACY
Pole jest nieprzetłumaczone – SELEC SOME OPTIONS

https://gitmaster.yetiforce.com/index.php?parent=Settings&module=Calendar&view=UserColors&block=2&fieldid=74
![21](https://cloud.githubusercontent.com/assets/11139594/8408176/19586768-1e6e-11e5-8463-913b8e9b4e1e.png)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1218
