### ISSUE TITLE
[Question] Send Document notification

### ISSUE THREAD

**Issue by calvinsug** [YetiForceCompany/YetiForceCRM#12149]
Hello,

just trying the notification system via workflow or create manually, but i didn't find Document for the process and subprocess, so is it possible to send the document link in notification system ? 

My desire is to create notification when a new document is created, but i think for the workflow, i just can notify default plain text like only 'there is a new document' , but i can't specify the new created document's name. Just wondering if it is possible to notify more specific for the document.

nb: i'm using Yetiforce 5.2 on windows

**Comment by fbojan** [comment]
#12031

**Comment by adudekyeti** [comment]
Hi,
You can easily create Workflow on Documents module. Now in 5.3 TextParser function is fixed, so you can use variables to insert it into notification. 

**Example notification message:** 
_"Label: $(record : RecordLabel)$
Title: $(record : RecordLabel)$
Filename: $(record : filename)$"_

**Will show notification like this:**
![image](https://user-images.githubusercontent.com/39482453/94562793-12303100-0266-11eb-83f1-342f65220939.png)
