### ISSUE TITLE
[Question] block send email

### ISSUE THREAD

**Issue by calvinsug** [YetiForceCompany/YetiForceCRM#12150]
Hello guys,

Is there any way to prevent user to send mail for a specified campaign or document ? for the example if the document status is not equal to 'checked', we cannot send the document via email, 

i tried to prevent the not checked document to being added in email template via filter, but i can't set the default filter value to 'checked' in Document  selection popup in email template, i just managed to set the default document filter only in Document page.

Any other ways to prevent any not checked document to being sent to contact?

**Comment by bpabiszczak** [comment]
The programmer must write this script.
