### ISSUE TITLE
[Pytanie]Parametr "Ilość" w filtrze PZ

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#12166]
Witam, próbuję sprawić, aby na liście PZ widać było ilość przyjętego produktu, w filtrach jest do wyboru cena netto ale nie ma ilości. Stworzyłem pole Ilość (1:M) i mogę to pole wybrać w filtrze, jednak jak sprawić aby wyświetlało ilość z bloku zaawansowanego (LBL_QUANTITY)?
Chyba, że jest jakiś inny sposób.
![1](https://user-images.githubusercontent.com/58420665/69954507-c7397600-14fb-11ea-849b-947c28208616.jpg)

**Comment by rskrzypczak** [comment]
Nie ma takiej możliwości.
Pola bloku zaawansowanego nie są standardowymi pola modułu, więc nie można ich wyświetlić w widoku listy rekordów.
Można kombinować poprzez utworzenie nowego pola i uzupełnienie w nim wartości np. na zapisie rekordu, ale wymaga to prac developerskich.
