### ISSUE TITLE
Notice: Undefined offset: 32 in /home/gitstable/domains/gitstable.yetiforce.com/public_html/app/Privilege.php

### ISSUE THREAD

**Issue by MunnaManjhi** [YetiForceCompany/YetiForceCRM#12165]

**Comment by MunnaManjhi** [comment]
Access right is not working properly.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/69951155-03b5a380-14f5-11ea-80a5-11ebaaeb7fd8.jpg)

**Comment by rskrzypczak** [comment]
yes, configuration required
![image](https://user-images.githubusercontent.com/10221999/70113919-cc610700-165a-11ea-8a7e-fff7fa56a868.png)
