### ISSUE TITLE
[ PL] Ucięty tekst w polu

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1216]
KONFIGURACJA SYSTEMU>DOSTOSUJ TŁUMACZENIA> ZARZĄDZANIE JĘZYKAMI
Ucięty tekst w polu. Pole czwarte od dołu: 
"Nie można zapisać rekordu ponieważ wymagane dokumenty nie są d"
![23](https://cloud.githubusercontent.com/assets/11139594/8408364/d8a9f2b6-1e6f-11e5-9fb1-160b9299c8c7.png)

https://gitmaster.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=10&fieldid=53

**Comment by rskrzypczak** [comment]
To nie jest błąd. Tekst jest dostępny. Długość tekstu jest ograniczony szerokością pola. Klikając w dane pole i nawigując 'strzałkami' można przeczytać cały tekst.
