### ISSUE TITLE
[Feature] Sales funnel grouping field value sorting

### ISSUE THREAD

**Issue by svdaru** [YetiForceCompany/YetiForceCRM#12169]
At the moment sale funnel levels are sorted by quantity of records grouped by the specified field. So that if I build sale funnel by quantity of record grouped by status and quantity of closed are bigger then other states, then the first (up) level of sale funnel will be "Closed sales"

![image](https://user-images.githubusercontent.com/13922774/69967925-6aa17f80-152a-11ea-99ad-c6d571415d0f.png)

I suggest to find a way to sort levels by the way it is sorted at the status list-field.
After analyzing the source code, i see that it is not supported at the moment.
Changes are needed:
1.at chart.funnel.js to disable sorting by quantity
2. and at Vtiger_ChartFilter_Model, to sort chartData by picklist sort field

**Comment by svdaru** [comment]
or another way is to add one more attribute to chartdata with sort order info.

**Comment by paula-w** [comment]
If you want to get rid of the “Closed sales” status in the “sales funnel” chart you have to use data (filter) that doesn't contain sales records with this status. If you, however, want to see this status in this chart you should limit the data to one month for example. The chart is working properly. 

We know more sorting options for charts would be useful but it’s not a priority right now. We don’t know when we’ll add them.
