### ISSUE TITLE
[bug] Powiadomienie o mailach z Roundcube zablokowało się

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#12167]
Witam,
jak w temacie i na zdjęciu, liczni powiadomienia zablokował się na wartości 42, można to jakoś wyzerować?
![2](https://user-images.githubusercontent.com/58420665/69954810-7ece8800-14fc-11ea-9141-fe012cc50f4b.jpg)

**Comment by bpabiszczak** [comment]
z tego co widzę, jest to licznik nieprzeczytanych maili? Jeżeli tak, to informacja ta jest pobierana z serwera poczty... Z tego co pamiętam, kiedyś ta opcja potrafiła "zawiesić" CRM bo serwer poczty nie odpowiadał [skrypt się zapętlał za nim otrzymał odpowiedź].

Można to wyłączyć tutaj: Konfiguracja systemu > Narzędzia pocztowe >Poczta - konfiguracja
Powinno pomóc.
