### ISSUE TITLE
[Feature] Update WYSIWYG instead replace for mass edit

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#12197]
### Describe the solution you'd like

If mass edit used for any field data in this field will be fully replaced. Sometimes I has situation when I need to add some new equal strings to WYSIWYG fields without full field data replacement. Will be cool to have ability to add data from new string unstead full overwriting

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

No ideas.

**Comment by s2b-git** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/discussions/17018#discussioncomment-5697586
