### ISSUE TITLE
How to display Role instead of Username?

### ISSUE THREAD

**Issue by Abhilash989** [YetiForceCompany/YetiForceCRM#12193]
![yeti](https://user-images.githubusercontent.com/17095321/70206676-4f16be80-174e-11ea-8386-c51a776ac1de.png)

Assigned To: User's Role should display/

**Comment by manwenick** [comment]
Hello @Abhilash989 !
From my point of view, there is no possibility to show responsible as a role. 
What you can do: 
1. Admin View: Create a new Group which you call e.x. Team Selling and assign user you need to this group.
2. User View:  Go to sales enquires --> Obove you see the filters --> create a new filter with a name e.g. "Role: Team Selling" where you can choose upto 12 fields which you want to see in the same window down you can choose filter conditions --> add Assigned to ->equals -> Team Selling
3. Repeat this for each role you need. 

Maybe there is an another work around, I don't know.

**Comment by vovpff** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=13&fieldid=56 here you can choose fields what will be visible as user name. But this settings will be applied for all modules in system
