### ISSUE TITLE
[pl] Brak tłumaczenia pół

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1219]
KONFIGURACJA SYSTEMU>PROCESY> Procesy sprzedażowe
Brak tłumaczenia pół
![26](https://cloud.githubusercontent.com/assets/11139594/8408691/6747828e-1e72-11e5-9769-0fb8f891e577.png)
 - SELECT SOME OPTIONS
W Zakładce:  KALKULACJE, SZANSE SPRZEDAŻY,  PRODUKTY SPRZEDANE
https://gitmaster.yetiforce.com/index.php?module=SalesProcesses&view=Index&parent=Settings&block=6&fieldid=75

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1218
