### ISSUE TITLE
[Question] Dokumenty zapisywane jako root, plik nie jest gotowy do pobrania

### ISSUE THREAD

**Issue by lpolitowski** [YetiForceCompany/YetiForceCRM#12190]
### Description

Przy weryfikacji nowo dodanego pliku, mam komunikat "Sprawdź integralność pliku, plik nie jest gotowy do pobrania". W folderze storage/ widzę, że zostały utworzone z uprawnieniami root 500. Proszę o nakierowanie gdzie mam szukać błędu.
![yetiforce_settings](https://user-images.githubusercontent.com/621427/70123322-b6f7d700-1672-11ea-8f52-6271898020bb.png)

**Comment by mariuszkrzaczkowski** [comment]
It looks like you have a problem with file permissions, check what file ownership you have and what permissions you run with

**Comment by lpolitowski** [comment]
> It looks like you have a problem with file permissions, check what file ownership you have and what permissions you run with

Is there a file in YetiforceCRM that I can check or it is cron issue? I suppose permisions are ok, but owner should be www-data.

`root@debian:/var/www/html/yetiforce# tree -pufid storage/Documents
storage/Documents
[drwxr-xr-x root    ]  storage/Documents/2019
[drwxr-xr-x root    ]  storage/Documents/2019/November
[drwxr-xr-x root    ]  storage/Documents/2019/November/week1
[drwxr-xr-x root    ]  storage/Documents/2019/October
[drwxr-xr-x root    ]  storage/Documents/2019/October/week3
[drwxr-xr-x root    ]  storage/Documents/2019/October/week4
[drwxr-xr-x root    ]  storage/Documents/2019/October/week5`

**Comment by mariuszkrzaczkowski** [comment]
show permissions in the main crm directory

**Comment by lpolitowski** [comment]
> show permissions in the main crm directory

Here there are:

> root@debian:/var/www/html/yetiforce# ls -al
razem 376
drwxr-xr-x 18 www-data www-data   4096 lis 28 08:28 .
drwxr-xr-x  3 root     root       4096 paź 21 13:54 ..
drwxr-xr-x  3 www-data www-data   4096 wrz  7 08:51 api
drwxr-xr-x 28 www-data www-data   4096 lis 26 12:31 app
drwxr-xr-x  3 www-data www-data   4096 gru  4 10:05 app_data
drwxr-xr-x 14 www-data www-data   4096 gru  4 10:05 cache
-rw-r--r--  1 www-data www-data   1372 wrz  7 08:51 CODE_OF_CONDUCT.md
-rw-r--r--  1 www-data www-data   3033 wrz  7 08:51 composer.json
-rw-r--r--  1 www-data www-data 164735 wrz  7 08:51 composer.lock
drwxr-xr-x  4 www-data www-data   4096 gru  4 10:05 config
-rw-r--r--  1 www-data www-data   3510 wrz  7 08:51 CONTRIBUTING.md
drwxr-xr-x  4 www-data www-data   4096 gru  3 15:45 cron
-rw-r--r--  1 www-data www-data   5452 wrz  7 08:51 cron.php
-rw-r--r--  1 www-data www-data    186 wrz  7 08:51 crowdin.yml
-rw-r--r--  1 www-data www-data   2469 wrz  7 08:51 dav.php
-rw-r--r--  1 www-data www-data    282 wrz  7 08:51 .editorconfig
-rw-r--r--  1 www-data www-data     31 wrz  7 08:51 .eslintrc
-rw-r--r--  1 www-data www-data   5430 wrz  7 08:51 favicon.ico
-rw-r--r--  1 www-data www-data    933 wrz  7 08:51 file.php
-rw-r--r--  1 www-data www-data   1705 wrz  7 08:51 .htaccess
drwxr-xr-x  8 www-data www-data   4096 wrz  7 08:51 include
-rw-r--r--  1 www-data www-data   1001 wrz  7 08:51 index.php
-rw-r--r--  1 www-data www-data    173 wrz  7 08:51 jsconfig.json
drwxr-xr-x  4 www-data www-data   4096 paź 21 15:21 languages
drwxr-xr-x  3 www-data www-data   4096 wrz  7 08:51 layouts
-rw-r--r--  1 www-data www-data   1426 wrz  7 08:51 LICENSE
drwxr-xr-x  2 www-data www-data   4096 wrz  7 08:51 licenses
drwxr-xr-x 96 www-data www-data   4096 gru  4 10:05 modules
-rw-r--r--  1 www-data www-data   3176 wrz  7 08:51 package.json
drwxr-xr-x  7 www-data www-data   4096 lis 28 08:29 public_html
-rw-r--r--  1 www-data www-data  11463 wrz  7 08:51 README.md
-rw-r--r--  1 www-data www-data    185 wrz  7 08:51 robots.txt
-rw-r--r--  1 www-data www-data    686 wrz  7 08:51 shorturl.php
-rw-r--r--  1 www-data www-data   2607 wrz  7 08:51 sonar-project.properties
drwxr-xr-x 11 www-data www-data   4096 gru  4 10:05 storage
-rw-r--r--  1 www-data www-data    743 lis 26 08:48 .user.ini
drwxr-xr-x  2 www-data www-data   4096 gru  4 10:05 user_privileges
drwxr-xr-x 30 www-data www-data   4096 wrz  7 08:53 vendor
drwxr-xr-x  4 www-data www-data   4096 wrz  7 08:51 vtlib
-rw-r--r--  1 www-data www-data    897 wrz  7 08:51 webservice.php
-rw-r--r--  1 www-data www-data    137 wrz  7 08:51 .whitesource
-rw-r--r--  1 www-data www-data   5140 wrz  7 08:51 .yarnclean
-rw-r--r--  1 www-data www-data  25814 wrz  7 08:53 yarn.lock

**Comment by mariuszkrzaczkowski** [comment]
you can't have different file owners must be the same everywhere,
it means that your server creates them incorrectly, so there is a problem with reading
