### ISSUE TITLE
[Question] Profile saving time

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#12194]
### Description

I has checked what profile saving takes a lot of time in my system. This is something around 4+ minutes just for one saving cycle. Also I checked saving timing at gitdev and this takes around 6 seconds. Why my installation saves profiles too slow? What I can to adjust to make it quicker?

@mariuszkrzaczkowski @bpabiszczak pls help!?

**Comment by bpabiszczak** [comment]
Change server / hosting;)
This functionality needs optimization, but we don't have time for this right now.

**Comment by vovpff** [comment]
@bpabiszczak what server parameters should be changed?

**Comment by bpabiszczak** [comment]
You probably have very slow disks.

**Comment by vovpff** [comment]
@bpabiszczak what disks speed recommended? I checked just now - 126 MB/s

**Comment by bpabiszczak** [comment]
DataBase [DB]:: 5000+ IOPS [read/write]
Operating System (OS):: 2000+ IOPS [read/write]
User Data [UD]: 1000+ IOPS [read/write]

**Comment by mariuszkrzaczkowski** [comment]
this you can use for testing https://www.thomas-krenn.com/pl/wiki/Fio

**Comment by vovpff** [comment]
Server speed from built in tester
```
Read: 61829/s
Write: 34228/s
CPU: 2718465/s
RAM: 4681691/s
Data base: 56634629/s
```
