### ISSUE TITLE
Error when adding widget to Project task

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#122]
Adding widget to project task summary view causes "Access denied" error.

**Comment by bpabiszczak** [comment]
Unfortunately, the information you sent isn’t sufficient. Please describe step by step what is wrong and how to find the bug. It would be best if you could do it on our testing version, if it’s possible. It is also very helpful if you send us screenshots that illustrate the problem and show us where it exists.

**Comment by kpaulaha** [comment]
Sorry for not explaining. When I try to make a related module widget to project task it give error as below.
I tried the same on your test installation, but could not do it because it allways logged me out.

Regards

Kpa



-------- Alkuperäinen viesti --------
Lähettäjä Błażej Pabiszczak <notifications@github.com> 
Päivämäärä: 26.01.2015  15.51  (GMT+02:00) 
Vas. YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio kpaulaha <kimmo@tigersoft.fi> 
Aihe Re: [YetiForceCRM] Error when adding widget to Project task (#122) 
 
Unfortunately, the information you sent isn’t sufficient. Please describe step by step what is wrong and how to find the bug. It would be best if you could do it on our testing version, if it’s possible. It is also very helpful if you send us screenshots that illustrate the problem and show us where it exists.
