### ISSUE TITLE
[PL]  Brak tłumaczenia pod polem

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1220]
Brak tłumaczenia pod polem TYP - SELECT SOME OPTIONS
KONFIGURACJA SYSTEMU>PROCESY> Procesy wsparcia
https://gitmaster.yetiforce.com/index.php?module=SupportProcesses&view=Index&parent=Settings&block=6&fieldid=80
![27](https://cloud.githubusercontent.com/assets/11139594/8408758/fdaad99c-1e72-11e5-8e2a-2389de21e5a6.png)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1218
