### ISSUE TITLE
server error when composing a reply to an email

### ISSUE THREAD

**Issue by cobia** [YetiForceCompany/YetiForceCRM#12200]
When I go to reply to an email, the page opens fine but an alert pops over the screen saying "Server Error! (Internal Server Error)". I looked in "cache/logs/error" and this is what it recorded:

```
[06-Dec-2019 10:32:39 America/New_York] PHP Fatal error:  Uncaught Error: Call to a member function getRoleDetail() on null in /srv/www/crm/app/PrivilegeQuery.php:70
Stack trace:
#0 /srv/www/crm/app/PrivilegeQuery.php(48): App\PrivilegeQuery::getPrivilegeQuery(Object(App\Db\Query), 'EmailTemplates', Object(App\User), NULL)
#1 /srv/www/crm/app/QueryGenerator.php(991): App\PrivilegeQuery::getConditions(Object(App\Db\Query), 'EmailTemplates', Object(App\User), NULL)
#2 /srv/www/crm/app/QueryGenerator.php(806): App\QueryGenerator->loadWhere()
#3 /srv/www/crm/app/Mail.php(95): App\QueryGenerator->createQuery()
#4 /srv/www/crm/public_html/modules/OSSMail/roundcube/plugins/yetiforce/yetiforce.php(658): App\Mail::getTemplateList('', 'PLL_MAIL')
#5 /srv/www/crm/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_plugin_api.php(493): yetiforce->getEmailTemplates()
#6 /srv/www/crm/public_html/modules/OSSMail/roundcube/index.php(289): rcu in /srv/www/crm/app/PrivilegeQuery.php on line 70
```
I suspect this error has something to do with "Templates" in the roundcube interface, which is disabled on my installation. I can't figure out why and any help in the right direction would be much appreciated. I'm using yetiForce v5.2.0. on debian system with nginx and php 7.3.12. I don't see this problem on either the yetiforce public stable demo or developer instances, so maybe it's a configuration that i'm missing?

**Comment by cobia** [comment]
FYI, the fix for me was following the advice in issue# #11559. What I don't understand though is why the developer and stable online demo seem to work fine while my installation did not? I don't see anyone else except for the author of the above-mentioned issue complaining about this problem either so could it be something wrong with my environment? I wish someone would comment.

**Comment by lpolitowski** [comment]
> FYI, the fix for me was following the advice in issue# #11559. What I don't understand though is why the developer and stable online demo seem to work fine while my installation did not? I don't see anyone else except for the author of the above-mentioned issue complaining about this problem either so could it be something wrong with my environment? I wish someone would comment.

I had this problem to, but I found ticket you mentioned and applied solutions from it. You are not alone.

**Comment by apcloic** [comment]
Hi,

To fix this issue, I think you don't need to modify YF core files, you only have to go to Email Template module and check that user is allowed to use at least one of the available email template.
Regards,

**Comment by sandrosousa** [comment]
same problem where... error on email reply :( .
![image](https://user-images.githubusercontent.com/19153579/75188585-4a0d4e00-5744-11ea-9459-2f212b8122c6.png)

**Comment by jimlee213** [comment]
> Hi,
> 
> To fix this issue, I think you don't need to modify YF core files, you only have to go to Email Template module and check that user is allowed to use at least one of the available email template.
> Regards,

Hello,
Do you mind tell me where I can give the user permission to use the template?
Thanks

**Comment by apcloic** [comment]
@jimlee213 
Hi,
Go to email template module, edit the template you want to use and check 'Assigned to' and 'Shared with' fields.
Regards,
