### ISSUE TITLE
Can Yetiforce integrate with Facebook

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#12205]
I would like to know if Yetforce and be integrated with facebook as I want to generate leads and have them automatically inputted in my crm and it seems like all the mainstream crm are available to integrate except yetiforce.

I would also like to know can Yetiforce work with Zapier

**Comment by bpabiszczak** [comment]
You can do whatever you want [it's open source].
We do not have ready integration with Facebook and Zapier. We only add functionalities that customers pay for.
