### ISSUE TITLE
[Question] Trying to set up CalDAV

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12219]
I have activated DAV, trying to put in the URL to access my calendar from a CalDAV app and I'm not sure where to put in the login details to authenticate the calendar access. I have read all the other CalDAV questions but can't see this. e.g.

Your example: https://asperiti.uk/yetiforce/dav.php/calendars/(__dav_login__)/YFCalendar/

How do I substitute my username and key in the above? Is the syntax as below?

https://asperiti.uk/yetiforce/dav.php/calendars/("asperiti" "YdCxxxxxxx")/YFCalendar/

Does CRON have to be running? Or is this another issue?

**Comment by mariuszkrzaczkowski** [comment]
> Does CRON have to be running? 

Yes
See an example of using CalDav: 
https://www.youtube.com/watch?v=Jg3mDVPz5dg&list=PLX0lktP3Kukh0O7w3cXbYx6cP0Z81VJdw
