### ISSUE TITLE
[bug] Labels displayed instead of correct text

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12218]
My installation was working fine until Friday, when I opened it the buttons and menu labels have text like MEN_MARKETING and LBL_RECORDS_LIST and LBL_FIRST instead of the correct text. These look like the names of the placeholders. How can I get the correct labels back?

![image](https://user-images.githubusercontent.com/58600791/70433564-fdd23c00-1a79-11ea-9cc6-2c400a052228.png)

# 🐞 bug report

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by vovpff** [comment]
Language missed?

**Comment by asperitigroup** [comment]
Many thanks for your quick response, where do I set the language?  Strangely, it was working fine prior to Friday.

**Comment by vovpff** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=4&fieldid=53

Check your user language

**Comment by asperitigroup** [comment]
That's great, it is working fine now - I amended the system settings to force language selection at login, and now it is showing the labels correctly. Thanks for your help.
![image](https://user-images.githubusercontent.com/58600791/70440210-96bc8380-1a89-11ea-89b2-cb65d1b7aa54.png)
