### ISSUE TITLE
[bug] Send Email Template From Workflow

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#12211]
when you create a workflow and choose a task such as Send an email template.

No templates show in the SELECT AN EMAIL   TEMPLATE SECTION.

Even though there are many templates already in the system none shown to select and use.

**Comment by bpabiszczak** [comment]
Show the problem at gitdeveloper.yetiforce.com or gitstable.yetiforce.com.

![image](https://user-images.githubusercontent.com/10197525/70393756-d3d33800-19ed-11ea-9830-b42659d9d35a.png)

**Comment by bangde** [comment]
Sorry, what would you like me to do?

provide you with more information?

**Comment by bpabiszczak** [comment]
> provide you with more information?

Yes.

**Comment by bangde** [comment]
Okay I will send more info, why did you delete the other post I am asking for help regarding task not  running

**Comment by bpabiszczak** [comment]
no description, no photos

**Comment by bangde** [comment]
I did add I will do it again

**Comment by Abhilash989** [comment]
![image](https://user-images.githubusercontent.com/17095321/70532506-30b12880-1b7d-11ea-9474-e8dfd1fcf9dd.png)




GO to database/Email Template. Add new record. U need to select the module for which u want to create new workflow. As I selected Sales Enquiry in screenshots.
After this it will show in workflow when u will select the same module .
I hope this will help u.

**Comment by bangde** [comment]
Hi Abhilash989,

Thank you for pointing me in the right direction. The issue was that for the type i had chosen was a message and not record and that is why it was not showing up.

May I ask what is the difference between message and record.

I was thinking that since it was an email it was a message but I was wrong and after seeing your screenshot and changed it to record, I got it to work.

Thanks very much
