### ISSUE TITLE
[Question]  How can we disable/enable a field based on the value selected?

### ISSUE THREAD

**Issue by Abhilash989** [YetiForceCompany/YetiForceCRM#12228]
I have a field category with value 1 and value2 . If I select value1 then other field (cost) should enabled if I select value2, it should become disabled.

**Comment by Giorgos-Hellene** [comment]
i suggest you to try the Fields-Picklists/Relations

https://gitdeveloper.yetiforce.com/index.php?module=PickListDependency&parent=Settings&view=Edit&sourceModule=Leads&sourcefield=industry&targetfield=subindustry
