### ISSUE TITLE
[bug] Remove relation ONLY for admin (custom module)

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12222]
Remove relation little action button in related list (for custom module) is not showing up.
All other entity modules are fine. Is there any quick fix for that?
Need to add that It OK ONLY for users with admin priviledges

**Comment by JohnMaverick** [comment]
Confirmed. Have same issue here. 

Just recreated it in demo: https://gitdeveloper.yetiforce.com/index.php?module=Reservations&relatedModule=Testmodule&view=Detail&record=3569&mode=showRelatedList&relationId=624&tab_label=Testmodule

**Comment by rskrzypczak** [comment]
You must recalculate user permissions 
e.g. save the profile settings again.

**Comment by JohnMaverick** [comment]
This is not helping. Check it please on demo. It surely some  code blocker (bug).

**Comment by rskrzypczak** [comment]
I checked and everything looks fine now.
![image](https://user-images.githubusercontent.com/10221999/70499149-cc5c7d80-1b18-11ea-9943-2d46779d286a.png)

**Comment by JohnMaverick** [comment]
Not working here O.o
