### ISSUE TITLE
[Question] Calendar Time intervals displayed

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12224]
Is it possible to change the size of the time slots in the calendar to display say 10 or 15 minute intervals?  I have my working day set to 08:00 to 18:00, and the calendar starts correctly from 08:00, but I would like to see the hour split into 4 15 minute slots, or 6 10 minute slots. I looked in config/modules/calendar.php but couldn't see an option to configure this.

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Users&parent=Settings&view=Detail&record=5
![image](https://user-images.githubusercontent.com/10198654/70596979-74407c80-1be7-11ea-89b5-79ff25fe2ba1.png)

**Comment by asperitigroup** [comment]
Changing the default settings doesn't change the displayed graphical calendar intervals to show half or quarter hour divisions. Perhaps this is not possible?
![image](https://user-images.githubusercontent.com/58600791/70728578-932f3380-1cf9-11ea-93bc-7c478e45bd18.png)

**Comment by bpabiszczak** [comment]
This is the fullcalendar library, maybe you'll find the answer there: https://github.com/fullcalendar/fullcalendar/issues
