### ISSUE TITLE
[bug] User > 2FA authentication method mandatory

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#12227]
YF 5.2 without last patch

When creating new user few fields are mandatory but should NOT
*2FA authentication method
*Synchronize CardDAV contacts
*Synchronize CalDAV calendar

How to fix it?

**Comment by sports1546** [comment]
I'm having the same issue, not sure how to fix.

**Comment by sports1546** [comment]
Marius, my issue was fixed.. may have been user error on my part..

Not sure if JohnMaverick is have a different problem.

2FA authentication method:     (greyed out, but not mandatory as indicated before)

These were also required when creating a new user, and worked for me with these options:
Authentication method:   Password
Synchronize CardDAV contacts:    Owner + Share with + Group
Synchronize CalDAV calendar:    Owner + Share with
