### ISSUE TITLE
[Question] Default phone call service provider.

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12239]
When I click on a phone number, I am asked which phone call method to use. Can this be defaulted to always use the call.center provider? Or do I have to make the choice of my mobile or VOIP phone every time?

![image](https://user-images.githubusercontent.com/58600791/70715978-4e989d80-1ce3-11ea-9f75-a33feb8d7ac0.png)

**Comment by apcloic** [comment]
Afaik, this is related to your browser settings, not YF.
You should ask call.center to see if they provide an extension for Chrome or Firefox.

**Comment by asperitigroup** [comment]
Thanks, have sorted this now, as you say a browser setting, nothing to do with YF and quite useful, as I can select to place a call via my mobile or VOIP line.
