### ISSUE TITLE
[Question] Date Filter in Chart Widget

### ISSUE THREAD

**Issue by idakhigbe** [YetiForceCompany/YetiForceCRM#12231]
### Description

Hello,

I was wondering you could show me how the date filter in the lead by status chart widget was created.

I can't seem to figure it out.

Please see the highlighted in the screenshot below.

Thanks.

![Date Filter](https://user-images.githubusercontent.com/29756298/70621509-0feae080-1c1a-11ea-9f94-9e5d9b0e4abe.jpg)

**Comment by adudekyeti** [comment]
Hi,
This is a special widget named "Leads by status". You can easly add it: _[System settings > Standard modules > Widgets – Configuration > Click "+ Widget" > Select "Leads by status"]_
