### ISSUE TITLE
 [PL] Nowe okno z błędem

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1223]
KONFIGURACJA SYSTEMU>NARZĄDZIA>Automatyzacja
Po kliknięciu na dowolne pole np. Pod PODSUMOWANIEM - 
Pole – "Ualkualnij zapas produktów dla każdego zapisu"
pojawia się NOWE OKNO Z BŁĘDEM

https://gitmaster.yetiforce.com/index.php?module=Workflows&parent=Settings&view=List&block=4&fieldid=24

https://gitmaster.yetiforce.com/undefined
![29 b](https://cloud.githubusercontent.com/assets/11139594/8409207/2bdb7a44-1e76-11e5-8ed7-e1fdeb20d14a.png)
![29](https://cloud.githubusercontent.com/assets/11139594/8409206/2bd8da0a-1e76-11e5-9337-1fc26b0eb9ec.png)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1209
