### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by MandarinaWebs** [YetiForceCompany/YetiForceCRM#12230]
After setting up the yetiforce and waiting one day we get this
![Captura](https://user-images.githubusercontent.com/38534444/70619381-39553d80-1c15-11ea-9229-c7ea4f9d83de.PNG)

We have seen that this topic was discussed in the next post
https://github.com/YetiForceCompany/YetiForceCRM/issues/10617

The solution given is this:
This error could have appeared if you ran out of space on your drive for example.
Remove the user_privileges/cron.php file.

But we have not that file.

It happened one day, we deleted it and reinstalled it and it's the third time that happens to us

Thank you

**Comment by hico11** [comment]
Any fix on this one? Appeared out of nowhere.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/72667680-af23a480-3a1e-11ea-8cfa-962d2129e7fc.jpg)
