### ISSUE TITLE
[Feature] Home Page Widgets - Edit existing and re-order fields

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12246]
I would like to be able to edit widgets that I have created, rather than have to delete them and start again, and would also like to be able to re-order the chosen fields, and to change the displayed length of the field within the widget. Thanks.

**Comment by bpabiszczak** [comment]
It's simple, just buy 40h from this site: https://yetiforce.com/pl/marketplace/wsparcie-development
