### ISSUE TITLE
[Question] www and cron settings are different

### ISSUE THREAD

**Issue by artcien** [YetiForceCompany/YetiForceCRM#12241]
Server configuration warnings show that www settings are a match with the recommended setting but CRON is different.

error_reporting = 'www: E_ALL & ~E_NOTICE|cron: E_ALL (32767)' (Recommended: 'E_ALL & ~E_NOTICE')

I cannot figure out how to change or update cron:

Could someone give me a hint on how to go about that?

Thanks!!

**Comment by vovpff** [comment]
Look for php.ini for cli

**Comment by artcien** [comment]
@vovpff Thank you for your response. 
What I have found on the php.ini is that several settings are actually hardcoded on CLI SAPI - Does that mean that it cannot be changed at all?

```
; Note: This directive is hardcoded to On for the CLI SAPI
implicit_flush = Off
```

**Comment by vovpff** [comment]
What is your server?

**Comment by artcien** [comment]
@vovpff is WAMP

**Comment by artcien** [comment]
The problem was during cron execution. All ok now
