### ISSUE TITLE
[Question] Can't see completed activities in graphical calendar.

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12244]
I have filters set to show planned activities, completed activities and cancelled activities. These work fine in the calendar record list but not in the graphical calendar view - only planned activities show. Is this by design?

**Comment by Giorgos-Hellene** [comment]
Click on "History" . There is a button on right top 
http://prntscr.com/qfv6mz

**Comment by asperitigroup** [comment]
Many thanks.
