### ISSUE TITLE
Does Yeti have an API or other ways to connect to other apps and applications

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#12248]
I would like to know if yetiforce has an open api so that I can connect it to other websites such as facebook or integrate with automation like zapier.

I waiting for this answer

**Comment by apcloic** [comment]
Hi,
Instead of waiting, try searching ;)
#11770 
https://doc.yetiforce.com/api/
https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST

**Comment by mariuszkrzaczkowski** [comment]
https://doc.yetiforce.com/api/
