### ISSUE TITLE
[Question] Relationship Contacts <> Projects not Working autmatically

### ISSUE THREAD

**Issue by ripixxx** [YetiForceCompany/YetiForceCRM#12256]
Hi,
Unfortunately, I noticed that the sutomatically assignment does not work for the Contacts and Projects modules.

In the "Project" module I have added a 1:N field where you can select a "contact". The tab of the relationship is visible in the respective modules, but the relationship is not shown here.

I can only select it manually, which would also work.

I have Yetiforce 5.2.
What can I do?

**Comment by bpabiszczak** [comment]
> [I have added a 1:N field]
> What` can I do?

Delete this relation 

There is already a relationship to the contacts module in the project module
