### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by alejandroflamerich** [YetiForceCompany/YetiForceCRM#12260]
Oh hi there! 😄

### Description
 Is there a way to create a project with its milestones and taks predefined. I mean all our project has the same milestones and tasks so we must to create those every time. I imagine that could be a button to create a project with the milestones and task at once

Any suggestion?

Alejandro

**Comment by vovpff** [comment]
?

**Comment by mariuszkrzaczkowski** [comment]
yes , Workflows
![image](https://user-images.githubusercontent.com/10198654/70970080-bf520800-209d-11ea-8dae-ace64ea91a7c.png)

https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=List&block=15&fieldid=24

https://gitdeveloper.yetiforce.com/index.php?module=Accounts&view=Detail&record=115

**Comment by elvissaba** [comment]
Workflow for project milestones work. For project tasks workflow does not work
