### ISSUE TITLE
New Database

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#1226]
Hello everyone,

today i've tried the new yetiforcecrm and was really surprised that i get an error code
"{"success":false,"error":{"code":"There is no active transaction","message":"There is no active transaction"}}" when creating new records? (NEW EMPTY COMPLETE FRESH DATABASE)

How can i solve this?

Best regards,
Ralph

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
we need more information - a step-by-step description of your problem. 
This article should explain you what kind of info we need: 
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
If you could provide logs, it would be also very helpful:
https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by ralphkretzschmar** [comment]
Hello,
nice to meet you – i will do it immediately.

Best regards

Von: Katarzyna Ulichnowska [mailto:notifications@github.com]
Gesendet: Mittwoch, 1. Juli 2015 08:32
An: YetiForceCompany/YetiForceCRM
Cc: Ralph Kretzschmar
Betreff: Re: [YetiForceCRM] New Database (#1226)


Hello,
we need more information - a step-by-step description of your problem.
This article should explain you what kind of info we need:
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
If you could provide logs, it would be also very helpful:
https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by ralphkretzschmar** [comment]
Here we go:

1. I've downloaded the latest developer version of yetiforce (2 days ago).
2. installed it on a test system where other instances of vtiger and yetiforce are already running (and working properly)
3. after the installation without any error messages i've tried to create a COMPANY and get the following error-message:

"{"success":false,"error":{"code":"There is no active transaction","message":"There is no active transaction"}}"

Best regards,

if logs are still neede i'll try to provide them :)

**Comment by mariuszkrzaczkowski** [comment]
I tested on the latest version and I do not see this error.
Install the latest version and check it or you can test here:
https://gitmaster.yetiforce.com/
Download the latest version from the master and check if an error occurs.
We recently introduced a lot of amendments.
