### ISSUE TITLE
[bug] Can't set monthly recurrence in calendar activity

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12267]
When I try to set an activity to recur, I choose Month, then 1, then by Day of Month, then number of occurrences to 5. When I click Save, nothing happens, it is not saved.

![image](https://user-images.githubusercontent.com/58600791/70989989-8c6b3c80-20bc-11ea-90a8-95613a22e74e.png)

# 🐞 bug report

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by konadrian** [comment]
To update these fields you need to select of these options 
![image](https://user-images.githubusercontent.com/3193498/75446150-25dd8700-5967-11ea-87bd-e27e2952257e.png)

**Comment by kpieron** [comment]
Welcome, 

We have the same problem, but only with monthly recurrence - for days and weeks it's working ok.
After push Save button, there is no pup-up window to choose saving mode. The console error:

![image](https://user-images.githubusercontent.com/97565924/149037975-0a50f4b1-8fd4-4a96-aed8-f332962cb7f7.png)

**Comment by kpieron** [comment]
Any news about it?

**Comment by konadrian** [comment]
@kpieron The problem no longer exists. The ticket has been closed.
