### ISSUE TITLE
Copy field value into related module

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#12270]
Hi friends

I'd like to make a little procedure to copy the "notes" field in account to the related module everytime I create a new register. I tried with workflow but I have to wait the cron process time, and this field is needed in the moment we create a new register for consults (will be copied too in the printed forms)

Could you help me how to do it?

![image](https://user-images.githubusercontent.com/40429279/71004023-61dbac80-20d9-11ea-8cb8-d1018aa275ae.png)
This is the note I want to copy to the related module

![image](https://user-images.githubusercontent.com/40429279/71004095-86d01f80-20d9-11ea-9054-0110b9eabd35.png)
In the related module, in new register, this note must be filled in the moment we create the register.

Your help is much appreciated!!!
Best Regards
Santy

(Working on 4 and 5.2 versions over Centos 7 and Mariadb)

**Comment by mariuszkrzaczkowski** [comment]
try this
https://github.com/YetiForceCompany/YetiForceCRM/blob/b93b92f1a96affde4a68f45f637a2a7c4e1b13bf/app_data/moduleHierarchy.php#L36

**Comment by santyabreu** [comment]
I tried but I'm missed 

How do you porpose to do it?

**Comment by bpabiszczak** [comment]
Mariusz show you where to make the change. You can use our paid support if you still have a problem.
