### ISSUE TITLE
[Question] Estabilish relation 1:M failing

### ISSUE THREAD

**Issue by IanMuller** [YetiForceCompany/YetiForceCRM#12273]
Have two custom modules.
One have reference field to another. But when I select parent module in UI tupe 10 field, the related module is not sowing up in the related list. Is there any table responsible for this?
I have impression it was working correctly before I applied patch

**Comment by waran70** [comment]
Noticed the same. It should work out-of-the-box as those fields are created in Layout Editor (at least here)

**Comment by paula-w** [comment]
We haven't noticed any bugs, but if you found them please open a new issue with all the information required by the bug report template together with screenshots and steps to follow to duplicate the problem, so that our developers can investigate.
