### ISSUE TITLE
[Feature] PDF reports cannot filter on related module

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12276]
It kind of overlooked, as we can create reports with related modules, but we cannot filter values from related modules. I am talking about large tables, so obviously this would be wise to consider 
extending filters options

**Comment by rskrzypczak** [comment]
![pdf](https://user-images.githubusercontent.com/10221999/74003581-67d06a00-4973-11ea-8601-a9a75c3a01f6.gif)

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/74003925-8d11a800-4974-11ea-8854-621b45753126.png)
$(relatedRecordsList : $params)$
$params Parameter construction: RelatedModuleNameOrRelationId|Columns|Conditions|CustomViewIdOrName|Limit, Example: Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]||2
