### ISSUE TITLE
[Question] missing config/config.inc.php 

### ISSUE THREAD

**Issue by artcien** [YetiForceCompany/YetiForceCRM#12279]
I'm trying to execute my cron.php from a URL. For me it's the only way since my server it's Wamp. 
According to the documentation, there should be a file in config/config.inc.php with a key needed.

> ` URL can be used to run cron, e.g. https://gitdeveloper.yetiforce.com/cron.php?app_key=xxxx where app_key is the key that is located in the config/config.inc.php file in the $application_unique_key variable.`

The problem is that I do not have that file at all.  I only have that file under \public_html\modules\OSSMail\roundcube\config\config.inc.php and no mention of any key.

What am I missing here?

**Comment by rskrzypczak** [comment]
crm version >= 5.0      `config/config.inc.php` => `config/Main.php`
