### ISSUE TITLE
[question]  From quote to Invoice

### ISSUE THREAD

**Issue by MandarinaWebs** [YetiForceCompany/YetiForceCRM#12277]
How can we pass from one quote to one sale invoice with the same account, services, information, etc

**Comment by vovpff** [comment]
Mapping will help you

**Comment by MandarinaWebs** [comment]
We get this error from quote to Invoice. We can generate from quote to sale order but not tos ales invoice directly.


![solicitud incorrecta](https://user-images.githubusercontent.com/38534444/71347884-9e8d2500-256b-11ea-99e7-0db61d1519ff.PNG)

Here the mapping

![El mapping](https://user-images.githubusercontent.com/38534444/71348013-e01dd000-256b-11ea-9352-1acf8c975442.PNG)

**Comment by vovpff** [comment]
@MandarinaWebs sorry. I don't understand your language on screenshot.
At first check logs and browser console.
As I know all advanced fields of source should be mapped. They can't be empty. Check this also!

**Comment by mariuszkrzaczkowski** [comment]
enable logs, you'll see an error message
