### ISSUE TITLE
[BUG][PL] Wyszukiwarka - błąd wyświetlania

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1227]
Przy próbie użycia wyszukiwarki wyniki nie są pokazywane w odpowiednim miejscu, ale u dołu strony (początkowo ciężko się zorientować, że cokolwiek się wyświetla)

![search](https://cloud.githubusercontent.com/assets/4824588/8418212/e478235a-1eb1-11e5-8842-609162f2f353.JPG)

sprawdzone na gitdeveloper.yetiforce.com

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/b7472d4b4b7113b778945aa71ac8c15be7095fa9
