### ISSUE TITLE
Gannt doesn´t show milestones and tasks [bug] 

### ISSUE THREAD

**Issue by DSUMEKI** [YetiForceCompany/YetiForceCRM#12278]
Hello, I have installed a fresh instace of Yetiforce on my serve and have configured the server my best to try to minimice warnings.<br />
My problem is that whe I create a project, a milestone for that projects and tasks for that milestone, they are not shown on gannt view. I have setted dates for all fields as i have seen reported as mandatory for gannt view. I can&acute;t find what is wrong. I will apreciate some help. Thanks :)

![problema gannt](https://user-images.githubusercontent.com/25234514/71206940-175b5b00-22a6-11ea-879b-fde5469e54a0.gif)

<strong>Security errors:</strong><br />
public_html: Off | -<br />
display_errors: Off | On<br />
session.use_strict_mode: On | Off<br />
expose_php: On | On<br />
disable_functions: | -<br />
Header: server: Apache | -<br />
Header: strict-transport-security: max-age=63072000; includeSubDomains | -<br />
<strong>Server stability errors:</strong><br />
error_reporting: E_ALL &amp; ~E_NOTICE | E_ALL (32767)<br />
default_socket_timeout: 600 | 60<br />
auto_detect_line_endings: On | Off<br />
<strong>Server database errors:</strong><br />
innodb_lock_wait_timeout: 50 | -<br />
wait_timeout: 300 | -<br />
character_set_server: utf8mb4 | -<br />
<strong>Server performance errors:</strong><br />
opcache.enable_cli: Off | Off<br />
opcache.max_accelerated_files: 10000 | 10000<br />
opcache.interned_strings_buffer: 4 | 4<br />
opcache.validate_timestamps: 1 | 1<br />
opcache.revalidate_freq: 0 | 2<br />
opcache.save_comments: 1 | 1<br />
opcache.file_update_protection: 0 | 2<br />
realpath_cache_ttl: 120 | 120<br />
mysqlnd.collect_statistics: On | On
<h4>PHP/Apache/Nginx/Browser/CRM Logs</h4>
Please include a part of logs which describes when the error occurred. The more info you provide, the quicker we will be able to solve your problem. Description how to enable logs can be found here: https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging Additionally, include a screenshot of your browser&rsquo;s console (e.g. press F12 in Google Chrome). ex. cache/logs/phpError.log, cache/logs/system.log

<h4>Your Environment</h4>
Describe the environment

<table>
	<thead>
		<tr>
			<th>Environment</th>
			<th>Version / Name</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>YetiForce</td>
			<td>5.2.0</td>
		</tr>
		<tr>
			<td>Web server</td>
			<td>Apache</td>
		</tr>
		<tr>
			<td>PHP</td>
			<td>7.1.33</td>
		</tr>
		<tr>
			<td>Browser</td>
			<td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36</td>
		</tr>
		<tr>
			<td>Operating System</td>
			<td>Linux nl1-sr1.supercp.com 3.10.0-962.3.2.lve1.5.26.1.el7.x86_64 #1 SMP Fri Jun 28 06:30:57 EDT 2019 x86_64</td>
		</tr>
		<tr>
			<td>Database</td>
			<td>mysql | 10.2.26 | 10.2.26</td>
		</tr>
	</tbody>
</table>

**Comment by snenko** [comment]
I have the same problem since I started using Yetiforce.

**Comment by poradz** [comment]
Hi, please check if correct filters are selected, as below:
![image](https://user-images.githubusercontent.com/31520119/71718330-251eed80-2e1b-11ea-8e09-cfe932dcff9f.png)
![image](https://user-images.githubusercontent.com/31520119/71718335-2819de00-2e1b-11ea-98bd-057973d7e4dd.png)

**Comment by snenko** [comment]
All filters are selected

![image](https://user-images.githubusercontent.com/11363876/71751048-fb011600-2e82-11ea-9b17-993832b4ede6.png)

**Comment by snenko** [comment]
I made a copy of the project to my local computer. And everything is fine.
I think it is a problem on the server.
Maybe, the server doesn't have some PHP library that uses Grantt.
