### ISSUE TITLE
Unable to update "Total Time [h]" on Tickets and Service Contracts

### ISSUE THREAD

**Issue by tiagofmmonteiro** [YetiForceCompany/YetiForceCRM#12280]
Hi. I've created an Account. When i create a ticket and a time control inside that ticket, the time control is getting the correct on Total Time, but on tickets, the Total Time [h] is never updating... It shows always 0. The time control status is Accepted, the ticket is closed, but the CRM never updates that Total Time on tickets neither service contract, and on service contract the Used Units are never updated too... I don't know what i am doing wrong...

My installed version it was 5.2.0 completed.

**Comment by mariuszkrzaczkowski** [comment]
cron works?
![github](https://user-images.githubusercontent.com/10198654/71237039-c62c8500-2300-11ea-8623-930ac75043cc.jpg)

**Comment by tiagofmmonteiro** [comment]
Hi. Yes, CRON is working. I've watched on the online Demo that this values only update when cron runs the workflow. On mine, that isn't happen... Cron runs but does nothing... I need to have a SLA assigned to that ticket too?

Best regards

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version

**Comment by tiagofmmonteiro** [comment]
No, on booth versions you have on online demo it is working. Maybe some requirements failing on my side?

**Comment by tiagofmmonteiro** [comment]
On booth versions you have online for Demo, it's only working the calculation of the Total Time inside a ticket. After that, i can't refresh the total time on a Service Contract, even when ticket is closed. For what i understood, the Total Time on ticket is updated when a Time Control is closed, and the Total Time on the Service Contract is updated when a ticket is closed, but that is not hapenning on the online demos. On the Service Contract, the Progress, Total Time [h] and Used Units are never updated...

Thanks

**Comment by tiagofmmonteiro** [comment]
Not working yet? Even online, the progress is never updated on contract services.

**Comment by adudekyeti** [comment]
Hi,
When you create Time Control, you need to be sure that you correctly set relations on this record:
![image](https://user-images.githubusercontent.com/39482453/94777596-ffcc0980-03c3-11eb-85bb-b186bd8a0816.png)

Then if everything is filled, time will be counting correctly.

**Comment by gus3008** [comment]
It seems not to be working. I am using the docker image

"Fri Nov 13 22:07:02 UTC 2020"
Commit: b465ef2
YetiForce 5.3.356

I have a contract created with 10 hours.
I have read the suggestions in this article and I confirm the cron is running, relationships of the ticket between the contract and the time control. Total time in contract is updated, but progress and units used are not calculated.

![Screenshot_20201113_184249](https://user-images.githubusercontent.com/39811818/99131210-8dfcf780-25e0-11eb-8535-f64fde6ead4d.png)
![Screenshot_20201113_184418](https://user-images.githubusercontent.com/39811818/99131212-8f2e2480-25e0-11eb-98a1-5d12bc9d60a8.png)
![Screenshot_20201113_184645](https://user-images.githubusercontent.com/39811818/99131214-8fc6bb00-25e0-11eb-8435-650cc192240a.png)

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the gitdeveloper version

**Comment by waran70** [comment]
> Check if the error exists in the gitdeveloper version
Marius, as such is a large blocker for individual devs who take care of data consistency and seriousness of client installation.
I would suggest you guys support a stable version of YF by providing quick fixings on GIT and copy it to dev versions (plus all enhancements). Leaving stable alone and kicking guys to YF-dev-ver is not solving individual problems but creating atmosphere of instability and uncertainty. 

Proposed structure
1. Stable
2. Stable + fixes
3. Dev (Stable + fixes + all other stuff)
