### ISSUE TITLE
[Question] Manually executing MailScanner from within Web interface

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12287]
### Description

Is there a possibility to execute the MailScanner manually from within the Web interface, or does there exist a specific URL that I could open to manually execute the MailScanner?

Sometimes I manually move e-mails to the scanner imap folder and it would be great to import these messages right away rather than wait for the cron job to execute.

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=Logs&block=14&fieldid=45
