### ISSUE TITLE
[bug] 'more' link in previewing e-mail does not work

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12289]
# 🐞 bug report

### ⁉️ Describe the bug

When previewing an e-mail attached to a Contact (e.g., /index.php?module=OSSMailView&view=Preview&record=154), the more' link does not work.

![bug](https://user-images.githubusercontent.com/10230144/71306550-04e63c00-23e2-11ea-9561-325781576352.png)

### 🔥 How to trigger the error

1. Receive an e-mail from a contact registered with the system
2. Import / attach the e-mail using the mail scanner cron jon
3. Go to the contact record and click on the mail content (in mail widget, previously added to the contact summary page)
4. Click on the 'more' link

### 👎 Actual Behavior

Nothing happens.

### 👍 Expected Behavior

Full e-mail is displayed
### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

I cannot test the issue on any of the sites as I have found no record with an e-mail attachted

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

There are not related messages in the error log files

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.2.94 patch 2019.12.18 |
| Web server (name and version)| apache 2.4		| 
| PHP  | 7.4.1								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by konadrian** [comment]
It was fixed
![image](https://user-images.githubusercontent.com/3193498/75520770-9e475500-5a06-11ea-855f-eea26ac98589.png)
