### ISSUE TITLE
[bug] Previewing e-mail does not show 'From' field

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12288]
# 🐞 bug report

### ⁉️ Describe the bug

When previewing an e-mail attached to a Contact (e.g., /index.php?module=OSSMailView&view=Preview&record=154), the 'From' field is not shown. When looking-up the record in the database (vtiger_ossmailview table), the from_email field is empty.

![bug](https://user-images.githubusercontent.com/10230144/71306457-e469b200-23e0-11ea-8f12-4158fba09079.png)

The mail scanner correctly attaches the record to the contact according to the from field of the e-mail.

### 🔥 How to trigger the error

1. Receive an e-mail from a contact registered with the system
2. Import / attach the e-mail using the mail scanner cron jon
3. Go to the contact record and click on the mail content (in mail widget, previously added to the contact summary page)
4. See the missing from field

### 👎 Actual Behavior

The from field is not shown
### 👍 Expected Behavior

The from field should be shown
### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com
I cannot test the issue on any of the sites as I have found no record with an e-mail attachted

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

There are not related messages in the error log files

### 🌍  Your Environment 

php 7.4.1
yetiforce 5.2.94 patch 2019.12.18

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by KatarzynaUlichnowska** [comment]
The bug requires access to the mailbox and an individual approach. Without it, we are unable to verify why the from_email address is not in the database.

**Comment by fliszer** [comment]
Hi @diderich 

have you solved this bug - I have the same issue.
If yes, could you share your solution?

**Comment by fliszer** [comment]
Ok, I found bug in modules/OSSMailScanner/scanneractions/CreatedEmail.php line 44
You should to comment this line or change to: 
$record->set('from_email', $mail->get('from_email'));
but it will be duplicated with line 40.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/1c4f3774ab846bdf40e835deca95704abfe33b0b
