### ISSUE TITLE
[bug] developer version, update app_data/cron.php error!

### ISSUE THREAD

**Issue by jinsongzhao** [YetiForceCompany/YetiForceCRM#12299]
[cron.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/3997157/cron.zip)
app_data/cron.php wrong data is attached at the end, It's a random error,  and causes administrator panel error, error message: syntax error, unexpected ','

......
'mode'=>'onlyText','status'=>true]],'last_start'=>1577108401];**0,'perms'=>'0777'],'cache/vtlib/HTML'=>
......
['type'=>'PremiumModules','testCli'=>false,'label'=>'PREMIUM_MODULES','mode'=>'onlyText','status'=>true]],'last_start'=>1577108401];**

**Comment by jinsongzhao** [comment]
Add the follow test code and the problem no longer occurs!
file_put_contents(ROOT_DIRECTORY . '/app_data/cron_bak/cron.php.'.date('Ymd_His'), Utils::varExport(Utils\ConfReport::getAll()));
file_put_contents(ROOT_DIRECTORY . '/app_data/cron_bak/cron_merge.php.'.date('Ymd_His'), Utils::varExport(array_merge(Utils\ConfReport::getAll(),['last_start' => time()])));

**Comment by jinsongzhao** [comment]
New code can't work,
Utils::varExport(array_merge(['last_start' => time()], Utils\ConfReport::getAll()))

<?php return ['last_start'=>1577767202,'stability'=>[
......
'status'=>true]]];**ron'=>'LBL_YES',**
......

Could it be a bug of php7.4?
[cron.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/4011981/cron.zip)

**Comment by mariuszkrzaczkowski** [comment]
the system does not yet support the php version 7.4

**Comment by jinsongzhao** [comment]
Upgrade to the latest vendors and fix the problem.
The code is:
$all = Utils\ConfReport::getAll();
$all['last_start'] = time();
return file_put_contents(ROOT_DIRECTORY . '/app_data/cron.php', '<?php return ' . Utils::varExport($all) . ';');

**Comment by jinsongzhao** [comment]
The third day was still wrong!
'last_start'=>1578488701];','testCli'=>true,

**Comment by mariuszkrzaczkowski** [comment]
I tested cron on YT 5.2.100 on php 7.4.1 working fine

**Comment by rskrzypczak** [comment]
check the available space on the server (df -h) and remove this file `app_data/cron.php`

**Comment by jinsongzhao** [comment]
> check the available space on the server (df -h) and remove this file `app_data/cron.php`
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        59G  8.5G   48G  16% /

**Comment by mariuszkrzaczkowski** [comment]
Attach a screenshot of the configuration verification

**Comment by jinsongzhao** [comment]
![full_screenshot](https://user-images.githubusercontent.com/5493476/72413199-33212680-37aa-11ea-82cc-76b30001fe47.png)
the code works:
$all = Utils\ConfReport::getAll();
$last = date('Ymd_His');
file_put_contents(ROOT_DIRECTORY . '/app_data/cron_last/cron1.php.' . $last, Utils::varExport($all));
$all['last_start'] = time();
return file_put_contents(ROOT_DIRECTORY . '/app_data/cron.php', '<?php return ' . Utils::varExport($all) . ';');

**Comment by mariuszkrzaczkowski** [comment]
You must first fix everything in red

**Comment by mariuszkrzaczkowski** [comment]
you have many problems even with file permissions

**Comment by jinsongzhao** [comment]
haha, crontab duplicate items configured!

**Comment by mariuszkrzaczkowski** [comment]
wow

**Comment by rioshaz** [comment]
@jinsongzhao  i have the same problem buddy.. how did  u solve it  ?
