### ISSUE TITLE
[bug] picklist/relations (dependency) bug

### ISSUE THREAD

**Issue by swsin84** [YetiForceCompany/YetiForceCRM#12295]
# 🐞 bug report

### ⁉️ Describe the bug

Picklists/Relations (Dependency) doenst work if target picklist has more than 50 items.

### 🔥 How to trigger the error

![picklist_dependency_bug](https://user-images.githubusercontent.com/18065182/71324517-5fed6100-24be-11ea-9873-5b21e0e9057e.gif)

### 👎 Actual Behavior

If I add 51th item to target picklist, picklist/relations doenst apply.

### 👍 Expected Behavior

Dependency should apply indepently of how many items i have in picklists..

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by bpabiszczak** [comment]
OMG 
why don't you use the tree field?

**Comment by areksolek** [comment]
Please increase the configuration limit for the variable Picklist Limit to the selected value in the file config / Performance.php
