### ISSUE TITLE
[bug] Installed update 5.2.18  and Reservations are not clickable

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#12291]
Installed update 5.2. v 18  and click on Reservations (graphical calendar) not working. Anyone else got that?

**Comment by vovpff** [comment]
Try to clear cache (ctrl+shift+R for chrome)

**Comment by JohnMaverick** [comment]
Not helping at all. Checked few times. No errors in console or in logs

**Comment by JohnMaverick** [comment]
I checked files, nothing has changed in Reservation module, so problem is out of module...

**Comment by vovpff** [comment]
Check updates log. Maybe some errors occurs during update

**Comment by JohnMaverick** [comment]
Nothing in logs. It like some library not loading.

**Comment by TonyM15** [comment]
Someone mentioned to set stable branch with subsequently added upgrades. In this way will be easier to detect errors.

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/UpdatePackages/commit/3cb2dfcca85f247130a425fcbe57638ad233e008
