### ISSUE TITLE
[Question] Override Vtiger module using loader ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#12298]
Hello,

Regarding the loader mechanism, i would like to override the following Vtiger module file in order to configure a new theme :
/modules/Vtiger/helpers/Util.php

I've read the YF official documentation which says that any module could be overrided :
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/loader-and-autoloader-of-files

But it doesn't work, so maybe it works only for standard modules and not Vtiger module ?
Do you confirm ?

Regards

**Comment by mariuszkrzaczkowski** [comment]
show example

**Comment by apcloic** [comment]
I've added the following file in yf_root_directory/custom/modules/Vtiger/helpers/Util.php
I've only modified getAllSkins() function like this :

`	public static function getAllSkins()
	{
		return [
			'twilight' => '#404952',
			'gray' => '#d1d1db',
			'mytheme' => '#682E68'
		];
	}`
Then in yf_root_directory/config/Performances.php, I have turned load_custom_file on like this :
`	public static $LOAD_CUSTOM_FILES = true;`

Clear the cache -> restart Apache2 -> new theme not available under user settings.

However, if I modify the function directly within the original file (yf_root_directory/modules/Vtiger/helpers/Util.php), the new theme is available.

Regards,

**Comment by apcloic** [comment]
Hi,

FYI, I've also tried to add a new SMS provider in custom/modules/SMSNotifier/providers/MY_PROVIDER.php with no luck.
So it does not autoload.
Regards,

**Comment by apcloic** [comment]
I've done further tests :
- /languages/_Base.json cannot be overwritten
- /custom/modules/SMSNotifier/models/Record.php is properly autoloaded but it break the SMSNotifier settings page (blank page).

**Comment by mariuszkrzaczkowski** [comment]
> Zrobiłem dalsze testy:
> 
> * /languages/_Base.json nie można zastąpić

give an example of translation

**Comment by apcloic** [comment]
@mariuszkrzaczkowski 
My bad, I've been confusing because I was trying to overwrite FL_PROCESS which is related to Calendar.
