### ISSUE TITLE
[PL] Pasek menu za szeroki

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1230]
![34](https://cloud.githubusercontent.com/assets/11139594/8425523/ca3fcab0-1f06-11e5-90cd-caeeec7c136f.png)

https://gitmaster.yetiforce.com/index.php?module=Calendar&view=Edit&mode=Calendar&link=112

**Comment by rskrzypczak** [comment]
Wysokość paska menu jest uzależniona od liczby elementów dodanych do menu.

**Comment by florek41** [comment]
Mam wrażenie, że we wcześniejszych wersjach było to rozwiązane za pomocą JS i elementy które się nie mieściły były grupowane w "Pozostałe".
Moim zdaniem to lepsze rozwiązanie niż rozsypany układ menu etc.

**Comment by bpabiszczak** [comment]
Było, dlatego otworzony został ponownie ticket, bo tak być nie może jak jest :] Programista się zapędził z tym zamykaniem.

**Comment by bpabiszczak** [comment]
Menu zostanie zmienione w najbliższej wersji na wersje pionową [z lewej strony]. Zgłoszenie zamykam, gdy pojawi się nowa wersja, będzie można napisać swoje uwagi.

**Comment by reeid** [comment]
When testing available?

**Comment by paula-w** [comment]
We standardize the entire appearance of the system to bootstrap [in this menu], responsiveness included [this will last til the end of this month]. The menu should be ready  for testing next week.
