### ISSUE TITLE
[PL] Ucięte przyciski u góry i na dole

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1231]
https://gitmaster.yetiforce.com/index.php?module=Calendar&view=Edit&mode=Calendar&link=112
![35](https://cloud.githubusercontent.com/assets/11139594/8425552/30895f70-1f07-11e5-9df8-d832e9513037.png)
![35 b](https://cloud.githubusercontent.com/assets/11139594/8425625/e943462a-1f07-11e5-8370-44ad9c0b6877.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/599de1c1c4493db9b95965524ce709072e4729b6
