### ISSUE TITLE
[bug] Adding 'related module' widged shows wrong 'selecting field'

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12317]
# 🐞 bug report

### ⁉️ Describe the bug

When trying to add a 'related module' widget to e.g. 'Accounts', and selecting as related module e.g. 'Projects', the list from which to select the field to display ('selecting display') is populated with field from the 'Contact' module, rather than the selected 'Projects module' as shown in the figure below:
![bug](https://user-images.githubusercontent.com/10230144/71415812-ed1aec00-265d-11ea-9d8d-57472b14515d.png)

### 🔥 How to trigger the error

1. Go to 'Modules - Widget System settings' in 'System settings' / 'Standard modules'
2. Click on '+ Add widget'
3. Select type of widget 'related module' and press OK
4. Select 'Related module' as 'Project'
5. When 'Selecting field', fields from 'Contact' are shown rather than fields from 'Project'

### 👎 Actual Behavior

When 'Selecting field', fields from 'Contact' are shown rather than fields from 'Project' to select from

### 👍 Expected Behavior

When 'Selecting field', fields from 'Project' should be shown to select from
### 👷 Testing 

- [ -] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

Works on gitstable. Does not work on gitdeveloper!

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.2.97|
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by bpabiszczak** [comment]
Now is ok [gitdeveloper]
![image](https://user-images.githubusercontent.com/10197525/73826893-dc35cc80-47fe-11ea-8a2f-af05c9a0ca6d.png)
