### ISSUE TITLE
[Question] Roundcube Fail

### ISSUE THREAD

**Issue by MandarinaWebs** [YetiForceCompany/YetiForceCRM#12319]
We are having problems with the roundcube functionality.

Here are our configuration
![mail](https://user-images.githubusercontent.com/38534444/71467706-fcb44500-27c3-11ea-8145-8a8d774a7f1b.PNG)

But when we connect is not working.

We have seen all the related question in this github but is not working anything.

Where can we find the logs or what could be happening?

The error is this or the SMTP error
![fallo 2](https://user-images.githubusercontent.com/38534444/71467934-9f6cc380-27c4-11ea-86b3-27981dd93a53.PNG)

**Comment by Giorgos-Hellene** [comment]
Goodmorning ! Merry Cristmas!

It is my first help...
You should disable the security option for "less secure programs " in the gmail account. This is the link https://myaccount.google.com/security 

i suppose (on your second printscreen) you try to log in with google credentials like this username@gmail.com and password below.

try it

**Comment by MandarinaWebs** [comment]
First of all, merry christmas! Thank you in this day

The less secure programs option is disabled. 

I am doing several tests. Now, I am trying to connect the corporate mail, and the error is the same:

![mail server](https://user-images.githubusercontent.com/38534444/71468864-b2cd5e00-27c7-11ea-98d3-19d3210775b0.PNG)
![configuration ](https://user-images.githubusercontent.com/38534444/71468868-b52fb800-27c7-11ea-86b7-052887d64e05.PNG)

With this configuration, i am trying to connect with:
User: info (becouse the email is info@mandarinawebs.com)
Pass: Mypass

And the same error: "Connection to storage server failed"

**Comment by Giorgos-Hellene** [comment]
try to change those values:

Name of IMAP server:               ssl://mail.mandarinawebs.com

SMTP port (default 25; 465 for SSL; 587):    25

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/71533026-bc091880-28f6-11ea-99be-448c9288dd72.png)

**Comment by MandarinaWebs** [comment]
Great! After a lot of tries, this is the configuration that worked for me!

![Captura](https://user-images.githubusercontent.com/38534444/71578624-402aee00-2af9-11ea-8a91-ca22e0605d76.JPG)

But, the question is I have spoken with our server provider and they modified the host firewall. I think the problem was here. 

I have asked them what they have modified exactly and when I know I tell you for future cases.

Thank you very much

**Comment by MandarinaWebs** [comment]
Okey, they told me this:

An express rule has been made to allow connections to port 993 of the mail server to which mail is accessed from the web application.

**Comment by Giorgos-Hellene** [comment]
i am glad that everything went well !!

I think that port 993 is ever open for this service. 

I use the same details because i have the same provider. lol
