### ISSUE TITLE
[Question] Workflow to create a sale invoice to sale order

### ISSUE THREAD

**Issue by josealbertomandarinawebs** [YetiForceCompany/YetiForceCRM#12318]
I'm trying to create a workflow to pass from a sale invoice to sale order every time a sale order is created.
The mapping is working, i can do it with button "Generate record", but i want to do it automatically when a sale order is created.
The configuration is here:
![image](https://user-images.githubusercontent.com/59206077/71419876-35440980-2672-11ea-9f0e-514607011b3a.png)
![image](https://user-images.githubusercontent.com/59206077/71419887-45f47f80-2672-11ea-815e-20008e9177f0.png)
![image](https://user-images.githubusercontent.com/59206077/71419899-56a4f580-2672-11ea-9ebb-942c001cf46c.png)

Thank you so much

**Comment by josealbertomandarinawebs** [comment]
Log:
[24-Dec-2019 11:33:22 America/New_York] PHP Warning:  Declaration of Settings_CronTasks_Record_Model::getDisplayValue($fieldName) should be compatible with Settings_Vtiger_Record_Model::getDisplayValue(string $key)

**Comment by apcloic** [comment]
Hi, I had the same kind of issue today.
First, you need to check that all mandatory fields are configured in your 'create entity' task otherwise it won't work.
Regards,

**Comment by mariuszkrzaczkowski** [comment]
> getDisplayValue

https://github.com/YetiForceCompany/YetiForceCRM/commit/40990487e05d5e5f457ac5add3cd0cb90bb9a331#diff-2ec1e2b4c5415ead463aac2105acbf01L176-R178

**Comment by josealbertomandarinawebs** [comment]
resolved!
Thank you so much!

**Comment by joice-martins** [comment]
how did u resolve this?
Sorry I'm new to this and not a developer haha
