### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#12324]
Oh hi there! Hi group !!

i need your help .

When i close an appointment with my customers.
How could i send an email or sms or both to my customers , one hour before or the previous day?

i want the same rule for all customers e.g. Two reminder. 1 hour before and 1 day before 

i think there is a way.

thank you group!

**Comment by bpabiszczak** [comment]
Use workflow: Software configuration > Automation > Workflows

**Comment by guide5232** [comment]
Execution schedule (defined time intervals):

For ""created time field"" I have tried many example but i did not get correct output .workflows are not triggering for how many hours we have given in condition and it is triggering the first Execution frequency. suppose if i give condition as  more than hours later= 15 hours but it is triggering at the workflow first Execution frequency. 
Less than hours before,less than hours later,more than hours before and more than hours later are not following the  workflow condition hours.

![Capture11](https://user-images.githubusercontent.com/47585969/73818670-e4e4cd80-4813-11ea-83ae-5c5a97a47df6.JPG)

 If we take  same ""created time field"" for Creating record, Modifying record and Only once, when all conditions are not triggering and nothing change will happen.

please check below recorded video.

![workflows222](https://user-images.githubusercontent.com/47585969/73818308-114c1a00-4813-11ea-8ad3-29b44faa6fe1.gif)

Could you please give us to one example.

**Comment by Giorgos-Hellene** [comment]
I will try it. Thank you !
