### ISSUE TITLE
[Question] looking to connect booking.com

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#12321]
Need to connect reservations and other things with booking.com.
Anyone gone through their api?

**Comment by JohnMaverick** [comment]
To extend previous question .... looking for to adapt yetifirce to basic hotel booking app. Does developer recommend yetiforce for such ?

**Comment by bpabiszczak** [comment]
> Does developer recommend yetiforce for such ? 
Yes

> Anyone gone through their api?
This is a very complicated process, the last implementation we have done is 100,000 EUR [the whole project]

**Comment by TonyM15** [comment]
You are guys pretty pricey. That's scary. I hope "Whole project" was much more than connecting booking api? 
;-)

**Comment by waran70** [comment]
connecting API for 100k ? you guys must have golden knobs in toilets? 

:-)
