### ISSUE TITLE
[Note] update version for 5.2.x

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#12320]
```updates/files/config/version.php ```

for service-packs doesn't have correct version number: ```appVersion```

**Comment by mariuszkrzaczkowski** [comment]
what version of sp?

**Comment by davide-alghi** [comment]
Good morning Mariusz,
I just downloaded from SourceForge and checked

**SP 1-3**
```
return [
	'appVersion' => '5.2.0',
	'patchVersion' => '2019.09.12',
	'lib_roundcube' => '0.0.80'
];
```

**SP 4-10**
```
return [
	'appVersion' => '5.2.15',
	'patchVersion' => '2019.09.19',
	'lib_roundcube' => '0.0.80'
];
```

**SP 11-***
```
return [
	'appVersion' => '5.2.0',
	'patchVersion' => '2019.09.19',
	'lib_roundcube' => '0.0.80'
];
```

**Comment by mariuszkrzaczkowski** [comment]
It was a mistake and it has been corrected.  version number cannot be changed
