### ISSUE TITLE
[PL] Brak odstępu przed wyrazem

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1232]
https://gitmaster.yetiforce.com/index.php?module=Calendar&view=Edit&mode=Calendar&link=112
![36](https://cloud.githubusercontent.com/assets/11139594/8425656/4814036a-1f08-11e5-957d-c7589041200f.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/55149bcfa8f0a3c2203f77701207b1df73434d48
