### ISSUE TITLE
[Question] how to sent an email or sms before an event

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#12323]
<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

Oh hi there! 😄

When i close an appointment with my customers.
How could i send an email or sms or both to my customers , one hour before or the previous day?

i want the same rule for all customers e.g. Two reminder. 1 hour before and 1 day before 

i think there is a way.

thank you group!

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/12324
