### ISSUE TITLE
[bug]  Error while sending email

### ISSUE THREAD

**Issue by mateuszrudyk** [YetiForceCompany/YetiForceCRM#12322]
Hello.
I have this error: 
 PHP Notice:  Trying to access array offset on value of type null in /var/www/yeti2/app/User.php on line 192
Users_Record_Model::getCurrentUserModel() /var/www/yeti2/modules/Users/views/Login.php:43
PHP   7. App\\User->getId() /var/www/yeti2/modules/Users/models/Record.php:371
PHP Notice:  Undefined index: IP_ADDRESS in /var/www/yeti2/vendor/yetiforce/csrf-magic/src/Csrf.php on line 251
 PHP Stack trace:
 PHP   1. CsrfMagic\\Csrf::obHandler() /var/www/yeti2/vendor/yetiforce/csrf-magic/src/Csrf.php:0
 PHP   2. CsrfMagic\\Csrf::getTokens() /var/www/yeti2/vendor/yetiforce/csrf-magic/src/Csrf.php:178

Yeti force version 5.2.0
PHP 7.4
Apache 2.4.18

Please help :)

**Comment by bpabiszczak** [comment]
Z tego co pamiętam, to dla 5.2 nie była zalecana wersja PHP 7.4 tylko niższa....
Polecam sprawdzić logi aplikacji, należy je włączyć ponieważ domyślnie są wyłączone. https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-programistyczna/item/debugowanie
