### ISSUE TITLE
How do you solve the "public_html required:on" installation error?

### ISSUE THREAD

**Issue by bayardk** [YetiForceCompany/YetiForceCRM#12334]
I've tried searching and can't find this issue. Running YetiForce/install/Install.php, the output reports public_html Present Value as Off. How do I satisfy that error? Thank you.

**Comment by bayardk** [comment]
![Screen Shot 2019-12-31 at 1 25 24 PM](https://user-images.githubusercontent.com/12346317/71630500-54421e80-2bd1-11ea-895c-80fb23108f4e.png)

**Comment by bayardk** [comment]
Note that I'm only asking about the public_html item, not the HTTPS item.

**Comment by bpabiszczak** [comment]
You must change root_directory on vhost, this is example for nginx
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/Nginx/www.conf#L9
