### ISSUE TITLE
[PL]  Pole zbyt wąskie 

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1233]
W kontrahencie 
9 ikonka (zmiana właściciela)
 Pole zbyt wąskie 
https://gitmaster.yetiforce.com/index.php?module=Accounts&view=Detail&record=124&mode=showDetailViewByMode&requestMode=full&tab_label=Szczeg%C3%B3%C5%82y
![37](https://cloud.githubusercontent.com/assets/11139594/8425825/26360142-1f0a-11e5-8f24-74e65cd1a43b.png)

**Comment by konadrian** [comment]
Pole rozszerzone w wersji developerskiej, wersja master zapewne nie zawiera tej poprawki
