### ISSUE TITLE
[bug] Cannot edit or delete a filter once created

### ISSUE THREAD

**Issue by slashgob** [YetiForceCompany/YetiForceCRM#12333]
I believe a user should be able to edit his Filters once he has created them, but for some reason the Edit and Delete buttons are not showing up in the Filter drop down menu. Has anyone experienced this before? is there a configuration that needs to change for this to be possible?

![image](https://user-images.githubusercontent.com/44810039/71626400-d38d1d80-2be4-11ea-85d1-6cab970382b7.png)

I created a new filter in the Opportunities Module called "Quoted Opps" Once saved, I have no mechanism to edit or delete the filter. I can do this if I log in as Admin, but as a standard user I cannot.

**Comment by Giorgos-Hellene** [comment]
Do you have the latest version of Yetiforce ?
if not, try it

**Comment by mariuszkrzaczkowski** [comment]
duplicate #11948

**Comment by slashgob** [comment]
I've upgraded to the latest service pack v19 on Version 5.2.0 but the issue is still there?

**Comment by slashgob** [comment]
ok, after clearing browser cache with CTRL-SHIFT-R I can now see the edit filter buttons
