### ISSUE TITLE
[bug] Broken Images/Unable to Complete Registration

### ISSUE THREAD

**Issue by agentblackhosting** [YetiForceCompany/YetiForceCRM#12339]
### Description

![image](https://user-images.githubusercontent.com/59404459/71637939-74003380-2c1f-11ea-96f5-27f83350ff10.png)

Due to broken image and no text, unable to complete product registration. Unable to locate via search any information related to this and unable to fully register the system without this step.

**Comment by bpabiszczak** [comment]
A logo is not required for registration.
