### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by bayardk** [YetiForceCompany/YetiForceCRM#12335]
I've tried searching and can't find this issue. Running YetiForce/install/Install.php, the output reports LBL_LABEL_SCRIPT_USER as daemon. I assume this is looking at user & group IDs on file system. I've tried multiple users and it complains about all of them. Which file/folder is it checking? How do I satisfy that error? Thank you.

**Comment by mariuszkrzaczkowski** [comment]
attach a screenshot

**Comment by bayardk** [comment]
![Screen Shot 2019-12-31 at 1 25 06 PM](https://user-images.githubusercontent.com/12346317/71630469-265cda00-2bd1-11ea-90e5-874caba0c51e.png)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/9878c117126d78616cd7663615c62dbcc4722266#diff-a1f924b6419c895e0882a433ac419efd
