### ISSUE TITLE
[Question] What version of YetiForceCRM with be fully compliant with PHP 7.4?

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12341]
### Description

As I understand, YetiForceCRM 5.2 is not fully compliant with PHP 7.4. What version of YetiForceCRM is expected to be fully compliant with PHP 7.4?

**Comment by bpabiszczak** [comment]
5.3

**Comment by mariuszkrzaczkowski** [comment]
If you see errors in PHP 7.4, report them all on GitHub, just add the subject [PHP 7.4]
