### ISSUE TITLE
[PL] Wyszukiwarka nie działa

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1234]
https://gitmaster.yetiforce.com/index.php?module=Vendors&view=List&parent=47
![38](https://cloud.githubusercontent.com/assets/11139594/8425881/c3ac412a-1f0a-11e5-924f-058efd2c5255.png)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1227
