### ISSUE TITLE
[bug] [PHP 7.4] Error messages potentially related to php 7.4

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12347]
# 🐞 bug report

### ⁉️ Describe the bug

The following errors/warnings may be related to running YetiForceCRM using php 7.4
```

PHP Notice:  Trying to access array offset on value of type null in /opt/crm/app/User.php on line 192
PHP Notice:  Trying to access array offset on value of type null in /opt/crm/app/User.php on line 214
PHP Notice:  Undefined variable: typeDb in /opt/crm/app/Db.php on line 153
PHP Notice:  Trying to access array offset on value of type null in /opt/crm/app/Record.php on line 314
PHP Notice:  Undefined index: IP_ADDRESS in /opt/crm/vendor/yetiforce/csrf-magic/src/Csrf.php on line 261
PHP Notice:  Undefined index:  in /opt/crm/app/Utils/ConfReport.php on line 639
PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /opt/crm/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_db.php on line 917
PHP Warning:  Creating default object from empty value in /opt/crm/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/html.php on line 754

```

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.2.94 2019-12-18 |
|Roundcube | 0.0.84|
| Web server (name and version)|	apache 2.4	|
| PHP  |		7.4.1						|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by vovpff** [comment]
Yeti does not support php 7.4 at this time

**Comment by diderich** [comment]
See also bug report #12341

**Comment by mariuszkrzaczkowski** [comment]
add bugs separately, it's better this way

**Comment by mariuszkrzaczkowski** [comment]
Fixed
