### ISSUE TITLE
Create a default "checked Checkbox" rule in System Config that does not NOT add the country code ("+1 ") to phone numbers IN THE SAME COUNTRY as the user.

### ISSUE THREAD

**Issue by littledove22** [YetiForceCompany/YetiForceCRM#12348]

**Comment by littledove22** [comment]
In the current setup, you cannot add "+1 " to phone number field in a google spreadsheet, to export as csv and import into Yetiforce.  Google Sheets and similar tools see this as a math error.  This requires the user to choose another field to use to import phone numbers, then go into each phone field and move the numbers manually.  Very time consuming with thousands of records to import.
When you are in the same country as the number you are calling, the country code is not required.  

The default should be:  No Country Code for phone numbers in the same country as the user.

**Comment by Giorgos-Hellene** [comment]
i round solution is to use the csv file and add a new column with +1. After that add the field with +1 and field with number and you will create the right formatting. It is very simple. Do not forget to save with the same format (csv)

**Comment by littledove22** [comment]
Thanks for the tip! I'll try it.
