### ISSUE TITLE
[bug] Layout in "Add Record" broke up after adding WYSIWYG field

### ISSUE THREAD

**Issue by georgelouk** [YetiForceCompany/YetiForceCRM#12355]
I was creating a custom module, with various custom fields which where separated in 5 blocks.
In one of those blocks I had only a text area field (at the left half) and i added a WYSIWYG field at the right, mostly for testing purposes.

Immediately after that, the nightmare begun... 
The "Add Record" layout broke up and i cannot find a way to rollback at the previous view even if i deleted the WYSIWYG field..

Actually, instead of my blocks to be 100% width and their fields separated in two columns (all modules look like that when you are going for example to add a new customer), the blocks of my custom module are now separated in bootstrap's xl-4 xl-8 columns and their fields inside are 100% width.

I can't find a way to configure that layout or to roll back at the previous one...

### 🔥 How to trigger the error

Not sure if i can reproduce the behavior...

Actually i tried to reproduce it at a new module but i couldn't...

### 👎 Actual Behavior
When i'm going to add a new record at that custom module the layout is not as expected.
Instead of col-xl-12 and 50%-50% inside the blocks i get 
two columns col-xl-4 col-xl-8 and 100% blocks

### 👍 Expected Behavior
Somehow fix it in order to NOT recreate the whole module from the beginning..

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.2
| Web server (name and version)|		Apache|
| PHP  |		7.3.11						|
| Browser (name and version)  | 		Firefox 71 |
| Operating System (name and version)  | 	Mac OS 10.14.6	|
| Database (name and version) | 	MariaDB 10.3.1	|
| Service Pack version | 		|

### ❓ Additional context
Screenshot of the "Add Record" layout
https://ibb.co/y81xdb5

**Comment by rskrzypczak** [comment]
It is default layout for inventory module.
![image](https://user-images.githubusercontent.com/10221999/71904039-abae3480-3165-11ea-8d83-aeebf559d808.png)


https://github.com/YetiForceCompany/YetiForceCRM/blob/3a027ad45d9c8744c2ffe272e50dc48ac6c493b8/config/Performance.php#L145
