### ISSUE TITLE
[Question] Unable to make pagebreak in PDF because editor replace it

### ISSUE THREAD

**Issue by lpolitowski** [YetiForceCompany/YetiForceCRM#12366]
### Description

According to [this](https://github.com/YetiForceCompany/YetiForcePDF#page-break) YetiForcePDF supports page breaks, but when I insert
`<div style="page-break-after:always;"></div>`
in editor it is replaced with
`<div>&nbsp;</div>`
This happens also in demo on https://gitstable.yetiforce.com/
I search trough ckeditor settings, but it seems YetiForceCRM has it own sanitize HTML settings. Where can I edit them?

**Comment by apcloic** [comment]
Hi, 
#11714
Regards,
