### ISSUE TITLE
Mautic and YetiForce integration error

### ISSUE THREAD

**Issue by lgwapnitsky** [YetiForceCompany/YetiForceCRM#12369]
I'm attempting to integrate Mautic and YetiForce using the VTiger plugin. I keep receiving the following message:

![image](https://user-images.githubusercontent.com/647444/71934331-339a3b80-3172-11ea-8278-d23d835b44bf.png)

I'm not seeing much in the way of setting up **Webservice - Service**, and the prior discussions do not go into much detail.

Advice is welcome.

**Comment by bpabiszczak** [comment]
This will not work, you must create new integration.
