### ISSUE TITLE
[Question] Workflow to create multiple entity ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#12368]
Hi,

I'm using YF 5.2v18 on a dedicated VPS.

Using a custom mapping, I've configured a manual workflow that create a paymentIn record related to an Invoice. It works perfectly !

Now I also need to create 3 payementIn records and not just one.

So I've configured 3 different tasks within the same workflow...but only one paymentIn is created.

Is it normal behavior ?

As a workaround, I could create 3 workflow (one per task) and it works but it's not really nice.

Regards,

**Comment by IanMuller** [comment]
wf overlapping? maybe delay each workflow?

**Comment by apcloic** [comment]
> wf overlapping? maybe delay each workflow?

Thanks @IanMuller but if I'm using multiple workflow, ie one per task, it works.
My question was related to a single workflow with multiple 'create entity' tasks inside.
But as you said, it may be a problem of task overlapping.

**Comment by konadrian** [comment]
Could you reproduce yours problem on https://gitdeveloper.yetiforce.com/
![threepayments](https://user-images.githubusercontent.com/3193498/75519560-c7b2b180-5a03-11ea-8409-ef929c6cccf8.gif)

**Comment by apcloic** [comment]
@konadrian I've just give a try and it works on gitdeveloper, so I'm gonna close the issue and see what's wrong on my YF instance.
Ty !
