### ISSUE TITLE
Illegal value has been entered for this field type. Field name: contracts_end_date, Module: HelpDesk, Value: 2020-01-09

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#12370]
# 🐞 bug report
Hi Team,

When ever I am trying to create ticket record from service contract related list page 
that time i am getting This error "" Illegal value has been entered for this field type. Field name: contracts_end_date, Module: HelpDesk, Value: 2020-01-09 ""
 I have attached video for your reference .
![Servirce contract1](https://user-images.githubusercontent.com/47585969/71949964-a9ada980-3229-11ea-9470-a6ab6a653dc2.gif)
### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.2
| Web server (name and version)|	 apache 7.3	|
| PHP  |		7.1.x, 7.2.x, 7.3.x						|
| Browser (name and version)  | 	google chrome 	|
| Operating System (name and version)  | 	windows 7 	|
| Database (name and version) | 	mysql	|
| Service Pack version | YetiForce CRM 5.2 Service Pack v1		|

**Comment by mariuszkrzaczkowski** [comment]
install Service Pack v19

**Comment by guide5232** [comment]
I have installed pack v19 but error not resolved. We can see this error in developer demo version please check this screenshot.  

In screenshot 1 : I have changed date format from yyyy-mm-dd to dd-mm-yyyy. because of we are using this format only (dd-mm-yyyy).

In screenshot 2: we can see this error in demo.


 1.   
 ![Date format](https://user-images.githubusercontent.com/47585969/71960871-32d4d880-324a-11ea-9ab2-2de3cc7a3bdf.JPG)



2.![demo](https://user-images.githubusercontent.com/47585969/71960802-04ef9400-324a-11ea-8508-30c99c462bcf.JPG)

**Comment by guide5232** [comment]
Hi team please check bug

**Comment by mariuszkrzaczkowski** [comment]
attach logs and dump of configuration verification
