### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by arutimpl** [YetiForceCompany/YetiForceCRM#12378]
Hi,
I there possibility to change TAX value from number to text?
I ask because selling invoice with "service" inside eu (and outside poland in my case) should be writed  without vat value (0%) but with description np (nie podlega) / n/a - not applicable.

Czy istnieje jakaś prosta możliwość zmiany pola z numerowego na tekstowe w "podatkach"?
Pytam ponieważ eksport usług poza Polskę (np. do EU) powinna być ze stawką - (minus) lub np (nie podlega) i nie bardzo mam koncepcję jak osiągnąć ten cel.

**Comment by bpabiszczak** [comment]
Wynająć programistę i mu to zlecić.
