### ISSUE TITLE
[PL] Za wąskie pole

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1237]
[PL] Za wąskie pole
Bazy danych>Maile 
Załączniki
https://gitmaster.yetiforce.com/index.php?module=OSSMailView&view=List&parent=84
![41](https://cloud.githubusercontent.com/assets/11139594/8426119/262ff204-1f0d-11e5-8b83-812b48f18fae.png)

**Comment by konadrian** [comment]
Widok pola poprawiony zmieniono szerokość na 100%, wersja gitmaster nie zawiera pewnie jeszcze tej aktualizacji
