### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by watlingsdirect** [YetiForceCompany/YetiForceCRM#12376]
I have install YetiForce 5.2 using Softaculous PHP version 7.3 and cannot use as the following error shows
LBL_HANDLER_NOT_FOUND
Please can you advise as I am very new to this
Thanks

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/72049217-c3e59700-32be-11ea-976b-791cd09ec126.jpg)
