### ISSUE TITLE
[Question] Smtp reply work on 5.2 but not 4.3

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#12379]
Oh hi Company ! 😄

i need your help.

1) 
I try to send email with smtp reply from MailJet and i noticed something strange. 
when i put the smtp details it works on 5.2 version but not on 4.3 version 
My problem is that it doesn't work on 4.3 version. Especially it sends the email but they arrive only the company email not gmail or yahoo. I see the Mailjet dashboard and it seems as "Soft-bounced". e.g i send to info@mydomain.com, kiki@gmail.com, kiki@yahoo.com. They only arrive the info@mydomain.com
any idea for this issue ?

2) I saw a new ability on YetiForce 5.2 related email. Could you help me how to complete the details in the red table ? http://prntscr.com/qkzlmh
it might help an example 

Thank you !

**Comment by bpabiszczak** [comment]
Update the system or hire a developer.
