### ISSUE TITLE
Data Import Issue with relationships

### ISSUE THREAD

**Issue by McDrewBlue** [YetiForceCompany/YetiForceCRM#12377]
Hello and sorry if this has been covered, i've searched and found nothing. I would like to mass import a buch of Lead Companies (which I can do comfortably) and then import Contacts that work at these Companies. What is the relationship field? How do I make the person import to connect as a member of the Company document? Many thanks!

**Comment by apcloic** [comment]
Hi @McDrewBlue 
Relationships between Accounts and Contacts are M:M type, so AFAIK there is no easy way to do this.
However, you should be able to achieve this by using a custom php script.
#2449

**Comment by bpabiszczak** [comment]
Relationships between Accounts and Contacts are 1:M.
Use the export tool [in the contacts module] to see how the system connects the Contact with the Accounts.
