### ISSUE TITLE
[bug] Error message in Roundcube when selecting email from a recipient that is a Contact in YetiForce

### ISSUE THREAD

**Issue by slashgob** [YetiForceCompany/YetiForceCRM#12382]
YetiForce v5.2 service pack 19

When I select an email from a recipient in RoundCube that is a Contact in YetiForce I get the following errors instead of the buttons to link the email to the contact/account etc...

![image](https://user-images.githubusercontent.com/44810039/72065190-99530880-32d5-11ea-9159-eac0c3a156fd.png)

Clicking on the blue "Import Mail Manually" bar does nothing other than show a message saying "started downloading Email"

It says its a permissions problem but I'm not sure what needs which permissions??

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/72066705-8fcf9d80-32e1-11ea-921d-9b4e89dcf225.jpg)

**Comment by slashgob** [comment]
gee thanks, so very helpful
