### ISSUE TITLE
[Question] WYSYWiG How to enable ckeditor config.pasteFilter option?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#12387]
### Description

I'm looking for ability to clean up clipboard styles then paste some html or MS word content to WYSYWiG fields.

Now I'm replaced `allowedContent: true,` with `allowedContent: 'h1 h2 h3 div p...bla bla bla` This works but this action cuts ckeditor functionality.

I has checked what ckeditor has option like `pasteFilter` https://ckeditor.com/docs/ckeditor4/latest/features/drop_paste.html

```
pasteFilter: 'p a[!href]',
```
Instead allowedContent is ignored by system. Or I'm wrong? How to enable it?

@mariuszkrzaczkowski @bpabiszczak Looking forward for your answer also.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/0a8d97055d952cb74874690b9a510eec4ece834a/public_html/layouts/resources/Fields.js#L540-L634

**Comment by vovpff** [comment]
@mariuszkrzaczkowski you linked original code. This code doesn't cleanup clipboard content from trash code like on this source example:
```
<h1 style="border:none; border-bottom:0cm none black; padding-bottom:0cm; padding:0cm; margin-top:16px; margin-bottom:8px"><span style="font-size:14pt"><span style="font-family:Ubuntu,sans-serif">Функциональное технологическое испытание оборудования и проверку его состояния для обеспечения нормального функционирования.</span></span></h1>

<h2 style="border:none; border-bottom:0cm none black; padding-top:0cm; padding-bottom:0cm; padding:0cm; margin-top:8px; margin-bottom:8px"><span style="font-size:12pt"><span style="font-family:Ubuntu,sans-serif">Внешний осмотр установки микросварки.</span></span></h2>

<h3 style="border:none; border-bottom:0cm none black; padding-top:0cm; padding-bottom:0cm; padding:0cm; margin-bottom:8px"><span style="font-size:12pt"><span style="font-family:Ubuntu,sans-serif"><span style="font-weight:normal">Внутренний осмотр узлов установки микросварки.</span></span></span></h3>
```

I'm looking for solution how to achieve just 

```
<h1>bla bla bal</h1>

<h2>bla bla bal</h2>

<h3>bla bla bal</h3>
```

**Comment by mariuszkrzaczkowski** [comment]
I gave a link to add your changes here

**Comment by vovpff** [comment]
@mariuszkrzaczkowski if I put there `pasteFilter: 'p a[!href]',` this option is ignored...

**Comment by mariuszkrzaczkowski** [comment]
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I can't understand how to cleanup font-size, margins and font-family...

**Comment by bpabiszczak** [comment]
https://github.com/ckeditor/ckeditor4/issues
