### ISSUE TITLE
[Question] Errors in RoundCube when selecting an email from a Contact

### ISSUE THREAD

**Issue by slashgob** [YetiForceCompany/YetiForceCRM#12385]
YetiForce v5.2 service pack 19

When I select an email from a recipient in RoundCube that is a Contact in YetiForce I get the following errors instead of the buttons to link the email to the contact/account etc...

![image](https://user-images.githubusercontent.com/44810039/72073196-58fc8600-32e7-11ea-8918-6dc36d59a0d2.png)

Clicking on the blue "Import Mail Manually" bar does nothing other than show a message saying "started downloading Email"

It says its a permissions problem but I'm not sure what needs which permissions??

**Comment by vovpff** [comment]
Pls check your server configuration at first

**Comment by slashgob** [comment]
Hi vovpff, please could you be more specific? what exactly should i be looking for?

**Comment by vovpff** [comment]
At first you need to check your webserver configuration and system logs. You need to activate logging in php file in /config/ folder

After that you will understand what is going wrong.
