### ISSUE TITLE
[bug] Number of currency decimals setting also apply to quantity field.

### ISSUE THREAD

**Issue by swsin84** [YetiForceCompany/YetiForceCRM#12388]
# 🐞 bug report

### ⁉️ Describe the bug

In Advanced Modules, number of currency decimals setting also apply to quantity field. 

For example if I set 0 decimals for currency, I am not able to use decimals for Quantity field. Validator automatically remove decimals in quantity field.

### 👍 Expected Behavior

Currency setting should only apply to currency fields, and not other kind of fields.

**Comment by rskrzypczak** [comment]
Fixed in YF7.0.2
