### ISSUE TITLE
[PL] Nie działa przycisk – WIĘCEJ

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1239]
https://gitmaster.yetiforce.com/index.php?module=OSSMailView&view=List&viewname=79
![43](https://cloud.githubusercontent.com/assets/11139594/8426321/2fad5d06-1f0f-11e5-9121-c3ae17c4183f.png)

**Comment by rskrzypczak** [comment]
Fixed in  https://github.com/YetiForceCompany/YetiForceCRM/commit/e4f4b37d957b531771592f7cd384fc8cb2487cc4
