### ISSUE TITLE
[Question] file not updated?

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#12393]
Is it possible that some (import / install) files are not updated?
For example, in my 5.2 SP18 ```app/Db/Importers/Base.php``` is different that DEV version

**Comment by mariuszkrzaczkowski** [comment]
is correct, the files are being expanded all the time so they can be different.  in SP we give the part of the file that is needed and not the whole is faster

**Comment by davide-alghi** [comment]
thx Mariusz,
it's right.
my thought concerns modification of 2019 that I could not find in the importer, for example for the creation of MEDIUMTEXT fields.
if I run a SP with migration to MEDIUMTEXT, my updating will fail because is not updated.
... you know.

only just information
