### ISSUE TITLE
[bug] Menu item using filter, list view not updating

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#12403]
Hi,

Adding a contact menu item using filter, for example contacts with active status, list view is not updating when clicking the menu item while the filter name looks well selected.
You have to go to filter menu, click on the same filter name and then list view is updating.

This issue is reproductible on official YF gitstable demo.

See attached video.

![yf_filter_not_updating](https://user-images.githubusercontent.com/2930560/72248188-d8939900-35f6-11ea-9e29-2dd9cb31bc78.gif)

**Comment by apcloic** [comment]
As a workaround, I found that using a shortcut menu entry instead of filter menu entry is working as expected.
For example, you could point your shortcut to the filter ID :
https://yourcrm.url/index.php?module=MODULE_NAME&page=1&view=List&viewname=FILTER_ID

**Comment by bpabiszczak** [comment]
Very low priority.

**Comment by apcloic** [comment]
> Very low priority.
@bpabiszczak  Yes, for sure but why did you close the issue ?
This is not a feature request, just a bug report and bug is unresolved.
