### ISSUE TITLE
[PL] Napis-  LISTA REKORDÓW – nie jest przyciskiem

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1240]
[PL] Napis-  LISTA REKORDÓW – nie jest przyciskiem
Kadry>czas pracy

Napis-  LISTA REKORDÓW – nie jest zrobiony jak przycisk, myślałam, że wogóle nie ma tego przycisku mało widoczny, mała czcionka

https://gitmaster.yetiforce.com/index.php?module=OSSTimeControl&view=Calendar&parent=76
![44](https://cloud.githubusercontent.com/assets/11139594/8426477/568169da-1f10-11e5-8f63-23744355d83d.png)

**Comment by konadrian** [comment]
Poprawka została wprowadzona do wersji developerskiej, wersja master wymaga uaktualnienia
3730c01ef877001c57ab190537965292e9a4b103
