### ISSUE TITLE
[Question] PDF działania matematyczne

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#12404]
Witam,
czy można w szablonie pdf umieszczać działania matematyczne? Mam stworzony szablon do faktury vat rr i muszę umieścić na nim obliczenie 0.1% kwoty netto, czy można jakoś zmusić silnik do obliczeń w szablonie?
Chyba, ze jest jakiś sposób na policzenie tej kwoty w module przez pole, to proszę o podpowiedź.

**Comment by bpabiszczak** [comment]
Można to policzyć w wielu miejscach. Pewnie trzeba to zrobić w aplikacji aby pokazać to na samym dokumencie. Liczyć to można tak jak są liczone inne pola np. : rabat, podatek itd. Jeżeli będzie to pole to łatwo generuje się w pdf. Można również liczyć w bibliotece pdf czy też szablonie pdf który robi się w PHP i tam możemy korzystać z dowolnych operacji matematycznych. Dobry programista sobie z tym poradzi bez żadnego problemu.
