### ISSUE TITLE
Question/feature - Mandatory Fields

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#12416]
Question # 1 = is there a way to make some mandatory fields when adding a new record or when editing an existing record but not being mandatory when importing ??

Question # 2 = is there a way to make a madatory field but only after an other field is changed ?

**Comment by vovpff** [comment]
A1: uncheck mandatory checkbox before import. But in this case you will see red popups if mandatory unfiled wher record edited.
A2: no

**Comment by bpabiszczak** [comment]
The programmer can do it.
