### ISSUE TITLE
[PL] Loader zawiesił się

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1241]
Kontrahent – Podsumowanie
Podczas edycji  nazwy kontrahenta przez (ikonke edycji)

https://gitmaster.yetiforce.com/index.php?module=Accounts&view=Detail&record=124&mode=showDetailViewByMode&requestMode=summary&tab_label=Podsumowanie
![48](https://cloud.githubusercontent.com/assets/11139594/8427112/4f0ae406-1f15-11e5-891c-0dc82a1b7158.png)

**Comment by konadrian** [comment]
Nie udało się uzyskać ponownie błędu na wersjach :local, gitmaster, gitdeveloper
