### ISSUE TITLE
[bug] Install process not accepting database username

### ISSUE THREAD

**Issue by jbwaclawski-msm** [YetiForceCompany/YetiForceCRM#12417]
# 🐞 bug report

### ⁉️ Describe the bug
While attempting to install YetiForce as an Azure App Service, I've reached the System Configuration page asking for database information and YetiForce admin information.  After entering all of the proper data and clicking next, I am directed to a screen summarizing the information I entered previously.  This screen is indicating that the database username field is empty and is not letting me progress (no NEXT button, only BACK).  I've verified that the username is being entered correctly, but nothing seems to be resolving this.

### 🔥 How to trigger the error
1. Push contents of latest YetiForce zip to App Service application via FTP
2. Navigate to app service URL and walk through install process
3. Get to System Configuration page and enter requested information (mysql username is msmadmin@yetiforce-test)
4. Press next after entering all information
5. Notice that there is no NEXT button and that the User name field title is red and there is no username listed

### 👍 Expected Behavior
Expecting the summary page to list the username entered and allow me to continue setting up YetiForce

### 👷 Testing 

- [ ✔️ ] Entered correct data to trigger aforementioned results
- [ ✔️ ] Entered incorrect data to verify database connection is functional by showing inability to connect to database error

### 📷 Screenshot of configuration
![image](https://user-images.githubusercontent.com/59838275/72365928-38f20b80-36c7-11ea-80e9-f0da45c922a9.png)
![image](https://user-images.githubusercontent.com/59838275/72365944-427b7380-36c7-11ea-8bf8-33998e3656c8.png)

**Comment by vovpff** [comment]
@jbwaclawski-msm I'm not sure but database user name should be without @
Be careful: Using separated web-server and database is non secure.

**Comment by bpabiszczak** [comment]
> Be careful: Using separated web-server and database is non secure.

Really?

> @jbwaclawski-msm I'm not sure but database user name should be without @jbwaclawski-msm 

Check the database server logs or must the programmer check this.

**Comment by vovpff** [comment]
@bpabiszczak no.
