### ISSUE TITLE
[PL] Dodaje podwójnie etap projektu

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1242]
PROJEKT>Szybkie tworzenie Etap projektu
![49](https://cloud.githubusercontent.com/assets/11139594/8427491/0d4ecb2e-1f18-11e5-922e-ae4e44715c61.png)
https://gitmaster.yetiforce.com/index.php?module=Project&view=Detail&record=162

**Comment by konadrian** [comment]
Nie udało się uzyskać błędu na wersji lokalnej, gitmaster, gitdeveloper
