### ISSUE TITLE
There is no active transaction [bug] 

### ISSUE THREAD

**Issue by ousidahou** [YetiForceCompany/YetiForceCRM#12422]
Hey There,
After working with Yeti 3 years, Today we can't create records : after trying to save we got this message : <<There is no active transaction>> .
Any Idea how we can resolve this ???

![Capture d’écran 2020-01-16 à 22 27 28](https://user-images.githubusercontent.com/22946462/72564291-b7a99d00-38af-11ea-8f5a-a58e4da9d05d.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/72589177-c49fae00-38fa-11ea-816d-f97506528bb9.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Include all necessary information,
this looks like a database error, may restart the database server
