### ISSUE TITLE
[Question] Is anyone using Ringcentral as their pbx provider?

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#12423]
### Description

Is anyone using Ringcentral as their pbx provider?

**Comment by Coonzoba** [comment]
We are. It'd be interesting to see what the integration would cost.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/12500

**Comment by z0lo13** [comment]
@Coonzoba 
https://github.com/YetiForceCompany/YetiForceCRM/pull/12504
