### ISSUE TITLE
vtlib: PackageUpdate vs PackageImport

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#12459]
PackageUpdate has a different behavior than PackageImport.

PackageImport imports all folders into **settings/modules** in package zip.
https://github.com/YetiForceCompany/YetiForceCRM/blob/faf413c129205ac716431e5b3765474721e1db03/vtlib/Vtiger/PackageImport.php#L454

PackageUpdate updates only **actions, views** and **models** folders in Settings
https://github.com/YetiForceCompany/YetiForceCRM/blob/faf413c129205ac716431e5b3765474721e1db03/vtlib/Vtiger/PackageUpdate.php#L51

Same thing for **public_resources, settings/public_resources** and **languages** in package zip file.

Is there a reason for this?

**Comment by mariuszkrzaczkowski** [comment]
Looks like some old code
