### ISSUE TITLE
[Question] how to customize popups

### ISSUE THREAD

**Issue by lzuccagnoli** [YetiForceCompany/YetiForceCRM#12458]
Hi, how do I select which fields to display in the popup?
thanks

![yetipopup](https://user-images.githubusercontent.com/53175360/72916408-44d27300-3d42-11ea-9b1e-8f784e2e846c.png)

**Comment by vovpff** [comment]
Go to admin panel. Standard modules. Edit fields. After that check checkbox summary view.
