### ISSUE TITLE
"Discount" field in the accounts module ?!

### ISSUE THREAD

**Issue by MexasPT** [YetiForceCompany/YetiForceCRM#12452]
Hello!
Need help!

I have a "Discount" field in the accounts module and I need to use this value in the "FInvoice" module, more specifically in the total discount of the "FInvoice" document.

Help me please!

**Comment by rskrzypczak** [comment]
![discount](https://user-images.githubusercontent.com/10221999/96406145-1acdb480-11df-11eb-89a2-0d7806f6ef16.gif)
