### ISSUE TITLE
[Question] Where can I find a business scenario about building sales based on yetiforce?

### ISSUE THREAD

**Issue by snenko** [YetiForceCompany/YetiForceCRM#12454]
I want to keep workflow in yetiforce.
Please tell me where can I find a business scenario about building sales based on yetiforce?
The site has little material about it.

Oportunities
Sales requirements
Calculations
Quotes
Sales orders
Recurring sales orders
Price Booking

**Comment by snenko** [comment]
I drow scheme how I understood. Is correct this schema?

![yetiforce-sale](https://user-images.githubusercontent.com/11363876/73214479-f581ad80-415a-11ea-809e-8ef2f9434ef4.png)

**Comment by z0lo13** [comment]
@snenko the above scheme would work, however, you may utilize whatever flow you want, by creating modules etc.

**Comment by snenko** [comment]
I realize here that "Sales" have a little relation to my business.
Now I think the "service contracts" is my target.
We web developers in outsource.

Unfortunately, there are not enough clear information and examples about Yetforce.

**Comment by bpabiszczak** [comment]
YetiForce is a flexible system. In every company this process looks different. Your scheme is ok.
