### ISSUE TITLE
[Question] Is there option to add one filed (description field) when we use Quick Create button

### ISSUE THREAD

**Issue by kilim1983** [YetiForceCompany/YetiForceCRM#12456]
### Description

Hello Team,

I want to have description filed when I use quick create future to create To do task/Events

In configuration I can only change order fields not add or remove anything.

Regards,
Damian

**Comment by bpabiszczak** [comment]
Please describe the problem exactly. It's best to send screenshots and a movie.

**Comment by kilim1983** [comment]
Hello,

When I try to add Task I can see this form where we don't have Description field.

![image](https://user-images.githubusercontent.com/44589374/73843315-b4eef780-481e-11ea-84ae-e17caf475ddb.png)

I want to find/add this field in configuration but I can only change field oreder not add Description field

![image](https://user-images.githubusercontent.com/44589374/73843329-bddfc900-481e-11ea-8802-4a0edff91d24.png)

So now I can user quick create option to create task and then I must go to this record edit them and add some information on description field.

Regards,
Damian

**Comment by konadrian** [comment]
You can change it in your database in vtiger_field table in quickcreate  column

**Comment by kilim1983** [comment]
Hello,

I try to find this table and column but with no luck. Can you share query which I can use?

Thank you in advance
Regards,
Damian
