### ISSUE TITLE
[bug] Cannot send email template to Shared Users in the Ticket

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#12467]
Hi, I have a workflow notification that sends an email template to the ticket owner when the new ticket is assigned to them. 

But I also want to be able to sometimes enter shared users so that the email notification is sent to them as well, however, it is currently not possible to add shared users in the workflow send email action. 

How can I notify the shared users regarding the ticket I am creating?

**Comment by mariuszkrzaczkowski** [comment]
check developer version https://github.com/YetiForceCompany/YetiForceCRM/commit/54a9e83a1c7c93d0a8d194c933bcd2dff6af25b4#diff-9bbcf5e46afe9f7f00c6b43dc8c2d3c7

![image](https://user-images.githubusercontent.com/10198654/73097944-a6ccdd00-3ee8-11ea-80cf-2d6d3ef850ee.png)

**Comment by acoolov** [comment]
For some reason I don't have an option to select Shared Users email address into the Send Email Template field. What do you think is wrong here?

![Screenshot (1)](https://user-images.githubusercontent.com/38298689/73108537-9445aa00-3ece-11ea-90c1-f8eb74e7c1f2.png)

**Comment by mariuszkrzaczkowski** [comment]
what version will you check?

**Comment by acoolov** [comment]
Oh I see it in the developer version. Does that mean it will come with the future 5.3 update? When is the update coming out?

**Comment by mariuszkrzaczkowski** [comment]
yes it will appear in 5.3, the date of publication is not yet known exactly, we would like to do so soon
