### ISSUE TITLE
[bug] Comment notifications only work with tickets

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#12468]
Hello friends,

I was able to make email notifications work when a new comment is added to the ticket. It sends the email notification to the assigned user. 

But how can I do the same for a Lead? So that when I add a comment to a lead, it sends the notification to the lead owner. Is this possible?

**Comment by fbojan** [comment]
Workflows Notifications no Data
![cccc1](https://user-images.githubusercontent.com/25682437/73248887-0dd1e680-41b4-11ea-9975-ae8562f0f03b.gif)
