### ISSUE TITLE
REST API update not authorized

### ISSUE THREAD

**Issue by dldnet** [YetiForceCompany/YetiForceCRM#12463]
Hi,

I can login via REST API (yetirest.php).
I test with the Accounts modules.

I can read, I can insert a new account but I can not update an existing account: Error 401 not authorized.

I am testing with the Admin user, all the permissions are on.

Do you have an idea of the problem ?

Thanks in advance

**Comment by mariuszkrzaczkowski** [comment]
Upload this change and check again

https://github.com/YetiForceCompany/YetiForceCRM/commit/17ddba1c697be43924859a6613c2310c5ba376b0

**Comment by dldnet** [comment]
I have downloaded and copied the 3 files.
Now I have this error when I try to connect:

Error (92): HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

**Comment by dldnet** [comment]
I have re-downloaded Login.php from the stable branch and it works perfectly.
I can update Accounts.
So, summary:
Portal files from developer branch  and Login file from stable branch and it's ok

**Comment by dldnet** [comment]
Next step, Contacts
I can insert and update contacts but it is impossible to assign a parent_id
If I set the parent_id, I have an empty REST response

**Comment by dldnet** [comment]
Ok, solution found.
When I get content of a Contact via REST, the "parent_id" is the Account name (which is strange...but anyway).
But when I update the parent_id, it must be the Account ID (which seems more logical).
Anyway, it works nice

**Comment by mariuszkrzaczkowski** [comment]
If you report a bug in api, give an example of a request and response, it will help everyone understand what you have a problem with

**Comment by mariuszkrzaczkowski** [comment]
do you have a problem with something else?
