### ISSUE TITLE
Import csv with ampersand

### ISSUE THREAD

**Issue by lzuccagnoli** [YetiForceCompany/YetiForceCRM#12464]
Hi,
How should be write **Accounts :::: Acme & C** in a CSV file, to be correctly linked to the related accounts? if I write **Accounts :::: Acme & C** the import finish without error but the field is empity evenif exist an account **Acme & C**
thank you

**Comment by mariuszkrzaczkowski** [comment]
attach a sample file

**Comment by lzuccagnoli** [comment]
On csv import the field with the "Yeti force" account is correctly associated but with the account name "Acme & Co." the filed is not associated, it remains white ... the problem is with "&" and other special characters ...
[Tickets (2).zip](https://github.com/YetiForceCompany/YetiForceCRM/files/4111733/Tickets.2.zip)

**Comment by lzuccagnoli** [comment]
hi, 
I created a "CSV test" module on the online demo.
What was my question is now a bug!

I created the first three records, I exported them to csv and reimported ... this is the result the accounts with "&" are not recognized ....

[TEST_import_export_CSV.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/4116242/TEST_import_export_CSV.zip)

![screen](https://user-images.githubusercontent.com/53175360/73161043-e6631700-40ea-11ea-850c-4b0cb392c0c6.png)

**Comment by lzuccagnoli** [comment]
I opened this bug Import csv with ampersand [bug] #12481

**Comment by lzuccagnoli** [comment]
I hope someone finds a solution, since the bug has been closed without the slightest interest ....

**Comment by mariuszkrzaczkowski** [comment]
The report did not follow the rules.
Each error must be reported separately together with its full description and must follow the report template.
Reports that don't include these details will be ignored because we're not able to duplicate the error and fix it.
The templates were created in order to help us and speed up fixing errors.

**Comment by lzuccagnoli** [comment]
> The report did not follow the rules.
> Each error must be reported separately together with its full description and must follow the report template.
> Reports that don't include these details will be ignored because we're not able to duplicate the error and fix it.
> The templates were created in order to help us and speed up fixing errors.

However, I did not understand if what I wrote here is not enough ...

**Comment by konadrian** [comment]
To create a reference record try to change the following option: `$CREATE_REFERENCE_RECORD = true 
![ImportWithSave](https://user-images.githubusercontent.com/3193498/73827889-a0036b80-4800-11ea-92f6-32e4a678c484.gif)
`

**Comment by lzuccagnoli** [comment]
Test with "Acme & Co." please! the problem is the name with "ampersand"!

**Comment by konadrian** [comment]
Yetiforce dev version
![ImportWithAmpersan](https://user-images.githubusercontent.com/3193498/73831276-59b10b00-4806-11ea-82bd-798b9b005975.gif)

**Comment by lzuccagnoli** [comment]
Great thanks! in which file is ... $CREATE_REFERENCE_RECORD = true

**Comment by konadrian** [comment]
config\Modules\Import.php

**Comment by lzuccagnoli** [comment]
thanks!
