### ISSUE TITLE
[Feature] Manu name change - Realization

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12460]
Can we change menu item name from Realization to Projects Management? Or just Projects?
Current menu name is kind of not compatible with what Project can represent

**Comment by davide-alghi** [comment]
I agree: currently in italian is translate as
- Progetti => Projects
- Tappe di progetto => Project stages
- Attività di Progetto => Project activities

**Comment by vovpff** [comment]
Custom translation? Crowdin?

**Comment by davide-alghi** [comment]
On en-US: it has to be done by YF team.

**Comment by KatarzynaUlichnowska** [comment]
Thank you for your suggestion. We've discussed it and decided to change it to Project Management.
