### ISSUE TITLE
[Question] 5.3, when?

### ISSUE THREAD

**Issue by deniscuculic** [YetiForceCompany/YetiForceCRM#12466]
Hi, 

as most of us is expecting version 5.3, 
could you please let us know when we can expect it?

Thank you

**Comment by deniscuculic** [comment]
bump

**Comment by deniscuculic** [comment]
Do you have any info? :)

**Comment by bpabiszczak** [comment]
Soon.

**Comment by deniscuculic** [comment]
Thanks for the very precise answer.
