### ISSUE TITLE
[Feature] Naming changing

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12474]
List view "Actions" button/menu
Please consider changing menu name positions as follow:

Mass edit > Edit
Mass activate > Activate
Mass archive > Archive
Mass move to Recycle Bin > Recycle Bin
Mass Delete > Erase from system (actually it not necessary and dangerous option. Only Recycle Bin should be fine)
Mass add comments > Add comments

**Comment by paula-w** [comment]
Thanks for the suggestion.
We believe the current wording used for these actions is alright so we're not planning to change it for now.

**Comment by TonyM15** [comment]
I think Paula you did closed this issue too fast. 
1.  Waran70 proposing clearer base interface managed by logic (nonsense to write mass when you anyway ticks more than one record and system doing its job as usual) 
2. Shorter menu items, better responsiveness
3. Abused "Mass" word is not what native English speakers would love to see on the screen.  

It is incredibly easy to make this changes in language file, but this proposed change basically makes yetiforce better. Why kick it out so fast than?

Regarding Deleting records  - I would also cancel it and allow it only in thrash bin module.

I vote to rethink...

**Comment by paula-w** [comment]
Thanks for your feedback @TonyM15 ,

I don’t think we closed it too early, it was up for 10 days and nobody either agreed or disagreed with the suggestion. Maybe the community considers this issue low priority. 

> “Abused "Mass" word is not what native English speakers would love to see on the screen”

 I guess this can only be resolved if a native speaker speaks up. 

These actions are not only visible in the dropdown menu on the records list, you can also see them for example when you edit permissions. When you change permissions in the panel and you see an action called “mass edition” it’s easier to understand than “edition”, which already exists in this view. We believe there shouldn’t be two actions that perform different operations but have the same name.
