### ISSUE TITLE
Export to pdf is Missing

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#12476]
When I try to create a pdf template for module I get this error. When I try to edit the templates that are installed i get the same error.

Warning: Declaration of Settings_PDF_Record_Model::getDisplayValue($key) should be compatible with Settings_Vtiger_Record_Model::getDisplayValue(string $key) in /home/**MY Website.com**/modules/Settings/PDF/models/Record.php on line 238

How do I fix this issue? Thanks in advance

**Comment by davide-alghi** [comment]
Hi,
try to move
```public function getDisplayValue($key)```
to
```public function getDisplayValue(string $key)```
in
https://github.com/YetiForceCompany/YetiForceCRM/blob/63a2dbae572235c091034e52af52f1278e8f5564/modules/Settings/PDF/models/Record.php#L223

**Comment by hobejeans** [comment]
Thank you. That worked ...
Now all the label show LBL. How can I fix this?

![Screen Shot 2020-01-26 at 3 38 24 AM](https://user-images.githubusercontent.com/45261773/73132793-c0a41800-3fed-11ea-908e-3e7059068353.png)

**Comment by vovpff** [comment]
@hobejeans one question one issue.
Incorrect language of pdf selected or translations is missing

**Comment by hobejeans** [comment]
Where do I edit the language or translation? Can you show me an example. Thank you

**Comment by hobejeans** [comment]
Software configuration/System tools/PDF/System settings/**Document Basic options**

I changed the language to English but after press save it reverts back to empty

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/73141720-8dae6280-4087-11ea-9c44-04e062b99f38.jpg)

**Comment by hobejeans** [comment]
I fixed this issue by first fixing the error in my **Company Details**.

**Warning: Declaration of Settings_Companies_Record_Model::getDisplayValue($key) should be compatible with Settings_Vtiger_Record_Model::getDisplayValue(string $key) in /home/MyWebSite.com/modules/Settings/Companies/models/Record.php on line 329**

Now when I select save  the language that I selected remains.
