### ISSUE TITLE
Company Details error

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#12478]
How do I fix this. It is asking for my email address but the email field is missing.

Warning: Declaration of Settings_Companies_Record_Model::getDisplayValue($key) should be compatible with Settings_Vtiger_Record_Model::getDisplayValue(string $key) in /home/**MyWebSite.com**/modules/Settings/Companies/models/Record.php on line 329

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/73141714-70799400-4087-11ea-8878-6c4934a65fc0.jpg)

**Comment by hobejeans** [comment]
Hi
I changed the display value from($key) to (string $key) and that fixed the problem. It also helped with the PDF language error i was getting....  When I select English language in the PDF template then save it the language I selected changed to blank. Now when I select save the language that I select remains.

**Comment by baverhey** [comment]
Line number to add the String is 138
