### ISSUE TITLE
[bug] after select vendor does not return vendor name

### ISSUE THREAD

**Issue by hanybmw** [YetiForceCompany/YetiForceCRM#12477]
### Description

module - Vendor enquiries
after select vendor does not return vendor name
Ver5.2

1-

<img src="https://i.ibb.co/CsDXzT3/2020-01-26-092426.jpg" alt="2020-01-26-092426" border="0">

2-

<img src="https://i.ibb.co/PYbT8S3/2020-01-26-092451.jpg" alt="2020-01-26-092451" border="0">

**Comment by vovpff** [comment]
Cron active? Update search labels manually and check.

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/73796154-cd262e80-47ac-11ea-9e1e-4cd2256502f9.png)

Works on the latest system version.
