### ISSUE TITLE
[PL] Błąd generowania

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1247]
Usługi sprzedane
Klikam na przycisk GENERUJ PRZEDŁUŻENIE - 
https://gitmaster.yetiforce.com/index.php?module=OSSSoldServices&view=List&parent=84
![55](https://cloud.githubusercontent.com/assets/11139594/8428434/e02d43d0-1f1e-11e5-84ac-c312ce214ec9.png)

**Comment by konadrian** [comment]
Nie udało się uzyskać błędu
