### ISSUE TITLE
[bug] Incoming correspondence

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#12482]
![cccc](https://user-images.githubusercontent.com/25682437/73163698-c8001a00-40f0-11ea-827d-bbafb9c76be4.gif)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/7538d5bc598a3e5a17a87a0782861321b61c9c64
