### ISSUE TITLE
[Question] Custom importer example or documentation?

### ISSUE THREAD

**Issue by mgrommet** [YetiForceCompany/YetiForceCRM#12483]
Hi YetiForce users and team:

I'm currently evaluating YetiForce for a replacement of an existing CRM product.   I'm looking for a very basic example on writing a custom importer, and am not finding one -- or if I've missed some obvious docs, feel free to give me a friendly shove in the right direction.

Thanks!

**Comment by z0lo13** [comment]
@mgrommet if existing import mechanism is not fit your needs, best importer is SQL

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/custom-data-import
