### ISSUE TITLE
Import csv with ampersand [bug] 

### ISSUE THREAD

**Issue by lzuccagnoli** [YetiForceCompany/YetiForceCRM#12481]
da una semplice domanda a un bug? #12464

**Comment by lzuccagnoli** [comment]
from a simple question to a bug? #12464

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/73161817-b288f100-40ec-11ea-84b1-fbd002a66a1e.jpg)
