### ISSUE TITLE
[PL] Zapis w kalendarzu graficznym

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1249]
Kalendarz graficzny>Dzień> zapisałam Szybkie tworzenie Termin / Zadanie – Konferencje
po odświeżeniu zapis znika

https://gitdeveloper.yetiforce.com/index.php?module=Calendar&view=Calendar&parent=44
![57](https://cloud.githubusercontent.com/assets/11139594/8429754/fb53fefe-1f2a-11e5-93b0-f620d5289252.png)
![57 b](https://cloud.githubusercontent.com/assets/11139594/8429767/16bea5b8-1f2b-11e5-9170-f3966cf3d5bf.png)
![57](https://cloud.githubusercontent.com/assets/11139594/8429766/16bcdb5c-1f2b-11e5-9ca0-993afeee97c0.png)

**Comment by rskrzypczak** [comment]
Błąd nie występuje w aktualnej wersji systemu.
