### ISSUE TITLE
Multiple Tax

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#12494]
How can I add multiple taxes to one record in the advanced block section? Also multiple items

For example:
**1. Tax 1 5%
2. Tax 2 3%
3. Tax 3 .5%
4. Tax 4 2%**

Gross
Net 
Total

**Comment by rskrzypczak** [comment]
![tax](https://user-images.githubusercontent.com/10221999/73514663-d56c1b80-43f2-11ea-96a9-107f22ad4119.gif)
