### ISSUE TITLE
[Question] testing a branch

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#12495]
The easiest way, to test a branch, is to git --archive, as zip, the branch, install and then test, but it's very unproductive.

Is there an alternative way to test a branch after local fixes commit (before sync with github)?

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/

**Comment by davide-alghi** [comment]
thx Mariusz, yes, that after my pull request was merged; I mean on my local, before push to my fork and , obviously, before create the PR.
I realize that my twisted mind sometimes tries to do things out of the ordinary. Maybe solution is complex and I postpone the solution later. 
thx

**Comment by mariuszkrzaczkowski** [comment]
you can import the database locally and update files separately from git

**Comment by davide-alghi** [comment]
right, that is the goal, but implications are many and automatism is hard to implement.
my fixing procedure is
- I fix bug on full working separated (from local GIT repo) installation, obviously not fully synchronized with your development branch
- I keep track of changed files on this separated installation
- I apply same changes to destination local branch and commit them
- **here I'd like to test changes with fully synchronized version (this is my break point)**
- I push to my gihub repo
- I create a PR to your repo

Is this a good proceedings or there is a better one?

**Comment by mariuszkrzaczkowski** [comment]
it's ok,
If you want to test the changes on the latest dev branch then link git from https://github.com/YetiForceCompany/YetiForceCRM
run this directory ad web server
install the version
then you can upload your changes for testing, and after the test you can remove them to have the original dev version
to make dev version updates easier, update files only and when the database changes you should import it (don't install)
we got special scripts to automate it, just like on gitdeveloper.yetiforce.com

**Comment by davide-alghi** [comment]
yep, very clear!!

> we got special scripts to automate it, just like on gitdeveloper.yetiforce.com

this is what I thought you used ... custom scripts to automate
thx very much
