### ISSUE TITLE
[bug] Workflow - create entity issue

### ISSUE THREAD

**Issue by elvissaba** [YetiForceCompany/YetiForceCRM#12497]
# 🐞 bug report
Workflow - create entity issue
### ⁉️ Describe the bug
 I can not select Project task module to create record in: Add task for workflow-> Create entity for Project milestone workflow. Can anyone help?

### 🔥 How to trigger the error
Just try to do i said above

1. Go to Workflows and select Project milestone module
2. Create workflow steps until Ad task for workflow
3. Create task for workflow ->Create Entity, custom mapping checked
4. Try to select Project task module from list

### 👎 Actual Behavior
As on picture bellow:
![image](https://user-images.githubusercontent.com/20727670/73397261-6784fe80-42e3-11ea-9dc4-503d775f46f6.png)

### 👍 Expected Behavior
It should create project task record
### 👷 Testing 

- [ x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![image](https://user-images.githubusercontent.com/20727670/73397346-a0bd6e80-42e3-11ea-950f-5ef7c4ce640f.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.2
| Web server (name and version)|		apache and litespeed|
| PHP  |				7.3				|
| Browser (name and version)  | 	Firefox	|
| Operating System (name and version)  | 		|
| Database (name and version) | 		Mariadb (latest stable)|
| Service Pack version | 		V19|

**Comment by bpabiszczak** [comment]
> Can anyone help?

Yes, programmer.

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/12356
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/6d9d36d02e3dac3803aaf80b454ff74fd0ac70c0
