### ISSUE TITLE
Po aktualizacji problem Warning: require_once(modules/PBXManager/PBXManagerHandler.php): failed to open stream: No such file or directory in

### ISSUE THREAD

**Issue by doriandudzisz** [YetiForceCompany/YetiForceCRM#125]
Warning: require_once(modules/PBXManager/PBXManagerHandler.php): failed to open stream: No such file or directory in /..../public_html/pracownik/include/events/VTEventTrigger.inc on line 140

Oba pliki istnieją jak to ugryść ?

**Comment by bpabiszczak** [comment]
W tej lokalizacji nie powinien istnieć, ponieważ my zmienialiśmy strukturę i nastąpiła zmiana lokalizacji tego pliku. Skoro jednak pliki "podobno istnieją" to komunikat ten nie jest dla nas zrozumiały. Przypuszczam, że plik został przeniesiony przy aktualizacji i nie są poprawne ścieżki w bazie do handlerów. Należy to sprawdzić na swojej wersji. U nas nie zauważyliśmy takiego problemu.
