### ISSUE TITLE
[Question] convert opportunity to invoice

### ISSUE THREAD

**Issue by trostas** [YetiForceCompany/YetiForceCRM#12506]
i was wondering if its possible to convert an opportunity directly to invoice.
i beleive this is possible at vtiger.
althought i have tried i can find a way to do it.

thanks

**Comment by apcloic** [comment]
@trostas 
I think that first, you have to use Mapping module and map required fields.
Once done, use "Generate Record" option on Opportunities module.
https://gitstable.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95
Regards
