### ISSUE TITLE
[Question] treeview for Products and Services

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#12501]
### Description
I'm trying to debug treeview for Products and Services, because it doesn't work: always empty.
I have some difficulty understanding the logic: Products TreeRecords view is trying to cross data with Accounts related Products. Why this?
For Services is the same: it's an Products extended.

**Comment by waran70** [comment]
tree field should be abandoned. It mix between picklists and UI10.. I personally dont see advantages of it... shure there is but my use cases are not about it

**Comment by davide-alghi** [comment]
Hi @waran70,
I don't understand. what is the goal of this?
and ... 

> It mix between picklists and UI10.

which ones?

just another question: treeview list works for Services and Products on your instance?

**Comment by davide-alghi** [comment]
Products/Services Tree view shows, not Products or Services, but Accounts with some related P/S into **Interested in Products / Services** (Services & Products tab in account details).
It works only for categories, but not for single P/S selection.

IMHO they have to works showing only P/S into selected categories on right-side tree.

To move to this, it's required to remove views/TreeRecords.php and resources/TreeRecords.js files for borh P/S and simple enable tree-view

```
public function isActive()
{
	return true;
}
```
in model/TreeView.php for both P/S.

I'm going to fix it.
pls @mariuszkrzaczkowski stop me if I'm wrong

**Comment by rskrzypczak** [comment]
Fixed on current dev version, will work properly in version 6.3
