### ISSUE TITLE
[Question] Copy/add existing picklist field to module

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#12507]
Hello,

I want to add/copy the existing picklist field "Type" that is shown in module "Accounts" also to "Leads" and "Contacts".

Can someone help me with this please? Thanks!

I use latest yetifore version 5.2

Regards

**Comment by vovpff** [comment]
Try to add picklist to leads and contacts with the same field name like in accounts

**Comment by blu-IT** [comment]
Hi,

thanks for your quick response. I think that maybe i was in the wrong settings part.

I found in **Standard modules -> Edit fields -> Accounts** another option, but when I try there to copy, I can copy the field "Type" to clipboard, but when I change module to "Leads" there is no way to paste the entry.

So I tried to "**Add custom field**":
* Select field type: Pick list
* Label name: Type
* Field name: Type
* Table: accounttype **<- is this correct? - I took this from the "Accounts->Type" field**
* Picklist values: **what do I enter here?**

What I want to achieve is that in the end fields for the entry "Type" already defined in the picklist section "Accounts" are availabe in Leads and and Contacts.

Thanks!

**Comment by vovpff** [comment]
@blu-IT i will answer you at monday. Now I don have access to my laptop.

**Comment by mariuszkrzaczkowski** [comment]
look at this https://www.youtube.com/watch?v=J14paUYtVwI

**Comment by blu-IT** [comment]
Sorry for the late response: Thanks, I will try and give some feedback!

**Comment by blu-IT** [comment]
Everything went fine, thanks!
