### ISSUE TITLE
[Feature] PBX price

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12500]
Working PBX, reports, webforms and we have the best OS CRM ever.... 
If we talking about working PBX solution, how much you will guys eventually charge for that? 

Here I have also one Q. You often relating orders from your Customers to open source code. I am not sure if this is wise to charge one guy 10k Euro and let others use stuff for free. 
It is not against logic? 

What about let someone pay for extension and you release it as a paid stuff in your online store? Both: extension investor and Yetiforce can have income shares in that case.
Isn't it wise business strategy?

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
this is Błażej's answer to this issue:

I love your suggestions on how to settle the cost for modules :]
At the moment, there is no client who wants to pay for the integration and the community is not able to collect enough money for it, so for me, the topic of integration doesn't exist. Simply said, this functionality has no value for you :]
