### ISSUE TITLE
[bug] Latest version of the error: Call to a member function isActive() on bool

### ISSUE THREAD

**Issue by jinsongzhao** [YetiForceCompany/YetiForceCRM#12515]
The error code is in the "$moduleModel = Vtiger_Module_Model::getInstance($mixed);", and return value is false, error module is Locations.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/f67459b1d6478988e2d8ba42c0ec5e1ec141f509
