### ISSUE TITLE
[Question] API, Put Requests, how to edit a record?

### ISSUE THREAD

**Issue by Sasamous** [YetiForceCompany/YetiForceCRM#12512]
### Description

Hello, I'm trying to edit an existing record, in this case is the "accountname" of an account (of course) with the "PUT" Method.

If I use this address: `{{baseUrl}}/webservice/Accounts/Record/159`
without a body, I get: `{"status":1,"result":{"id":159}}`
(159 is already existing) else it would return me this:
`{"status":0,"error":{"message":"ERR_RECORD_NOT_FOUND||1590","code":0}}`
(I used `{{baseUrl}}/webservice/Accounts/Record/1590`, 1590 doesn't actually exist)

but with the same address (id 159), if I give both in "form-data" or "x-www-form-urlencoded" a body like this:
![image](https://user-images.githubusercontent.com/40520020/73661326-29e4f480-469a-11ea-843d-342f8e22930e.png)
![image](https://user-images.githubusercontent.com/40520020/73661472-6a447280-469a-11ea-9847-1e804bc339f9.png)
(in those screens ":BaseModule" is replaced with "Accounts" by PostMan)

I get this error:
```
{
	"status": 0,
	"error": {
		"message": "2: array_merge(): Argument #1 is not an array in /var/www/html/yetiforce/api/webservice/Core/Request.php, line 45",
		"code": 200
	}
}
```

the code at line 45 of Request.php is this:

![image](https://user-images.githubusercontent.com/40520020/73661744-e343ca00-469a-11ea-99ed-975e36583f91.png)

My question is, what kind of body should I use to edit one or more values of a record?

**Comment by mariuszkrzaczkowski** [comment]
Test the development version, this error has already been fixed

**Comment by Sasamous** [comment]
Ok, in Development version it works, but only if the form mode is "x-www-form-urlencoded".

By the way I reached another solution in stable version that doesn't work in development version:
if I give a "raw" body (PUT Method) in stable version in with that:
```
{
    "accountname": "AccountNameForTest"
}
```

I get this response:
```
{
    "status": 1,
    "result": {
        "id": 115
    }
}
```
and the account name of my record is changed, but if I do the same in development version I get same response but the change doesn't happen.

**Comment by mariuszkrzaczkowski** [comment]
does not work on the developer version because the profiles do not have permission to this field,
when you turn it on it works properly see example:

```
PUT /Accounts/Record/117 HTTP/1.1
Host: https://gitdeveloper.yetiforce.com/webservice
x-api-key: VMUwRByXHSq1bLW485ikfvcC97P6gJsz
Content-Type: application/json
x-token: 2522edb60f959e822eb8cf4961139e9759f199ab
x-raw-data: 1
Authorization: Basic cG9ydGFsOnBvcnRhbA==

{
    "accountname": "YetiForce Sp. z o.o.2"
}

```

```
{
    "status": 1,
    "result": {
        "id": 117
    }
}
```
we recommend using json data format to work flawlessly
