### ISSUE TITLE
Created time field conditions

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#12528]
# 🐞 bug report
Execution schedule (defined time intervals):

for created time field
workflows are not triggering for how many hours we have given in condition and it is triggering the first Execution frequency. suppose if i give condition as  more than hours later= 15 hours but it is triggering at the workflow first Execution frequency. 
Less than hours before,less than hours later,more than hours before and more than hours later are not following the  workflow condition hours.

![Capture11](https://user-images.githubusercontent.com/47585969/73818670-e4e4cd80-4813-11ea-83ae-5c5a97a47df6.JPG)

 If we take  same ""created time field"" for Creating record, Modifying record and Only once, when all conditions are not triggering and nothing change will happen.

please check below recorded video.

![workflows222](https://user-images.githubusercontent.com/47585969/73818308-114c1a00-4813-11ea-8ad3-29b44faa6fe1.gif)

### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| ver. 5.2.122
| Web server (name and version)|	apache	|
| PHP  |	7.2.x, 7.3.x, 7.4.x 							|
| Browser (name and version)  | google chrome	|
| Operating System (name and version)  | 	windows 7	|
| Database (name and version) | mysq		|
| Service Pack version | 		|

**Comment by guide5232** [comment]
Is there any update?

**Comment by areksolek** [comment]
The information flow is working properly.
After testing according to the posted video, the field has been modified.
Please remember that each information flow is triggered by cron - by default, cron starts every 15 minutes. The information flow schedule will send the information to cron after the set time, but it will be modified later.
