### ISSUE TITLE
[Question] YetiForce - Offline version

### ISSUE THREAD

**Issue by alexynadamas** [YetiForceCompany/YetiForceCRM#12535]
Hi

¿Is there a offline version of YetiForce? I need to register data without Internet conexion.

**Comment by vovpff** [comment]
You can install Yetiforce on your PC without internet.

**Comment by alexynadamas** [comment]
> You can install Yetiforce on your PC without internet.

But, Can I use it offline?

**Comment by vovpff** [comment]
@alexynadamas this is online system.

**Comment by paula-w** [comment]
You can install the system locally (on your laptop or a server in your company that doesn’t have access to the Internet). Everyone who wants to access the system has to log in using a browser but an Internet connection isn't necessary. However, the user who uses the browser has to “see” the system - you can use a closed company network.
