### ISSUE TITLE
[Question] make a notification via workflow

### ISSUE THREAD

**Issue by lzuccagnoli** [YetiForceCompany/YetiForceCRM#12531]
Hi,
can anyone tell me why is displayed $ (record: firstname) $ and $ (record: lastname) instead of "Tom Kowalski" ?

![screen](https://user-images.githubusercontent.com/53175360/73867261-ab798580-4846-11ea-9be6-2e5ee5f2fed1.jpg)

this is a screenshot of the online demo version 

thanks

**Comment by mariuszkrzaczkowski** [comment]
show html notifications and screenshot of notification configuration

**Comment by fbojan** [comment]
#12468

**Comment by lzuccagnoli** [comment]
> show html notifications and screenshot of notification configuration

Hi,
screenshot fom of the online demo version https://gitstable.yetiforce.com/

![screen 1](https://user-images.githubusercontent.com/53175360/73920733-46657480-48c6-11ea-94cc-5d2af1055ab3.png)

![screen-2](https://user-images.githubusercontent.com/53175360/73920740-4d8c8280-48c6-11ea-985a-200c15e4a65e.png)

![screen-3](https://user-images.githubusercontent.com/53175360/73920749-52513680-48c6-11ea-9815-988d2f36e910.png)

![screen-4](https://user-images.githubusercontent.com/53175360/73920806-6e54d800-48c6-11ea-83cc-d17780f6e33b.png)

![screen-5](https://user-images.githubusercontent.com/53175360/73920811-7280f580-48c6-11ea-9e63-331df590d356.png)
