### ISSUE TITLE
[Question] API, RecordRelatedList x-condition | RecordsList parent_id condition

### ISSUE THREAD

**Issue by Sasamous** [YetiForceCompany/YetiForceCRM#12541]
### Description

Hello, I want to get all tickets (HelpDesk) of an "Account" that have a creation date **("creationdate")*** higher than a specific value (example: 2020-01-10);

but "x-condition" doesn't exist on RecordRelatedList, and in RecordsList with "x-condition" I can't specify the accountid of the parent because "parent_id" return the partial name of the account that isn't primary key.

So how can I achieve this by account_id, or at least account_no of account of interest?

***I get "creationdate" adding at "x-field" header that field.**

**Comment by Sasamous** [comment]
I think adding x-condition header to RecordRelatedList in API System can help to solve a lot of situations.

Also, adding the "parent_no" (progressive number of the parent, for example O1) or the real "parent_id" (for example 115) can help too :)

**Comment by z0lo13** [comment]
@Sasamous  @mariuszkrzaczkowski 

there is a header x-parent-id

but it seems not to be working:

1. Creating user for testing with 4 type of priviligies
<img width="577" alt="image" src="https://user-images.githubusercontent.com/23143958/77368413-8c6d7f00-6d32-11ea-8d81-eeaf47645d19.png">

2. Lets take a look on Account id of that contact record
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/23143958/77368512-bcb51d80-6d32-11ea-8bcb-37fc3e80a89d.png">

3. Get list of related Tickets
[GET]
https://gitdeveloper.yetiforce.com/webservice/HelpDesk/RecordsList

4. Profit
