### ISSUE TITLE
[Question] Account list view  with account link and action disabled

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12540]
Hi,

try to find the way to achieve this situation 

role : secretary standardiste  ( pick up all incoming call , should identify assigned user)
menu : with only account  ( list view ) with following field : company name , phone , assigned to
right : can view all the company , can filter company name and phone

i would like to disable
the link on account name and icon "action"   for this role or Profile  to avoid apening detail view

can you guide us

thanks

**Comment by bpabiszczak** [comment]
Purchase support hours, then we'll guide you.
