### ISSUE TITLE
[bug] PDF - no way to get list view of records

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#12545]
Trying to generate report of selected records from contacts module. No way. I select 5 records and I have 5 zipped reports where on each there is 18 records. 
The generic outcome should be one pdf (zipped on demand) with list of records. 
This is basic thing. Yetiforce have no reports module, so we need to at least use filters and pdf to extract searched values

**Comment by IanMuller** [comment]
Yea basic - print pdf report from filter. Why it is so difficult?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/11937

**Comment by TonyM15** [comment]
Check contact module. select 3 records and print them to pdf. You will have 3 pages and on each list of all records for current screen set. It not working.

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/74094112-12fc3300-4adc-11ea-8e88-55cf82df29aa.png)

**Comment by bpabiszczak** [comment]
$(custom : RecordsList)$
