### ISSUE TITLE
[bug] Email notification to account on ticket create not working

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#12555]
# 🐞 bug report

### ⁉️ Describe the bug
Hello friends, i'm pretty sure it is a bug. 
When I create a new ticket for an account (client) I've configured my Yetiforce so it sends an email notification to that account. So each time I create a ticket, it sends the new ticket notification to that account's primary email address. But one of our clients has an email address written in format like this: firstname.lastname@gmail.com and this particular email format (using the . ) does not send the email notification. 

### 🔥 How to trigger the error
Create an account that has an email address with a dot . in the address as their primary email address.

Create a new ticket so that email notification would be sent to that account's email address.

### 👎 Actual Behavior
An email notification is not being sent when there is a dot . in the primary email address in the account.

**Comment by sperkey7007** [comment]
@joebordes

**Comment by sperkey7007** [comment]
?

**Comment by joebordes** [comment]
I am not related to this project in any way. Sorry, I can't help.

**Comment by adudekyeti** [comment]
Hi,
I created user with our gmail email separated by dot: [yetiforce.git.developery@gmail.com].
Also I created workflow which send email message to "primary email address" Account.

And normally I received it:
![image](https://user-images.githubusercontent.com/39482453/94685913-60a70380-032a-11eb-8506-a5fab0df4a94.png)

In that case we need more information step by step how to reproduce this issue. If is possible please verify and try it on https://gitdeveloper.yetiforce.com/
