### ISSUE TITLE
[bug] [PL][EN] Brak możliwości powiększenia i pobrania wgranego zdjęcia / Cannot zoom in or download photo

### ISSUE THREAD

**Issue by Pja-revo** [YetiForceCompany/YetiForceCRM#12551]
"Zoom in" or "Download" photo is not working at stable YetfiForce v 5.2.0 https://gitstable.yetiforce.com/ 

Steps to reproduce:

1. add photo, eg contact profile photo. 
2. Try to "Zoom in" or "Download" - popup with preview disappears without zooming or downloading

----------------------------------
Można wyświetlić podgląd wgranego zdjęcia, ale nie można go powiększyć ani pobrać.
Problem dotyczy wersji stabilnej https://gitstable.yetiforce.com/ i developerskiej przy użyciu różnych przeglądarek (chrome, Firefox, IE )

Odtworzenie problemu:

1. Udane wgranie zdjęcia np profilowe kontaktu
2. Przycisk **Powiększ** nie powiększa zdjęcia tylko zamyka popup. Tak samo **Pobierz**.
 

----------------------------------
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/60872592/74265011-00634300-4d02-11ea-8044-3e18a260c136.gif)

**Comment by rskrzypczak** [comment]
Niestety nie jestem w stanie wywołać tego zjawiska zarówno na wersji stabilnej https://gitstable.yetiforce.com/ jak i developerskiej.
Spróbuj opróżnij pamięć podręczną przeglądarki(chrome - ctrl+shift+r).
![image](https://user-images.githubusercontent.com/10221999/75227212-0fd89680-57ae-11ea-9a62-1dec6ece8051.gif)

Zamykam zgłoszenie, jeżeli jednak nadal widzisz problem, to otwórz je ponownie i uzupełnij informacje (np dołącz załączany obrazek)
