### ISSUE TITLE
[Question] What contains the documents folder?

### ISSUE THREAD

**Issue by alexynadamas** [YetiForceCompany/YetiForceCRM#12550]
The ClamAV found some malware on httpdocs/storage/Documents. 

What files save Yeti in this folder?

thanks

**Comment by z0lo13** [comment]
@alexynadamas 
its mostly are email attachments, pictures and icons. Also any document you upload in documents module.

**Comment by alexynadamas** [comment]
Whe you say email attachments, Do you mean when you add an account on Yeti, true? Using roundcube

Thanks
