### ISSUE TITLE
Updates not show Emails sent

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#12563]
I would like to know how to show when an email has been sent in the updates section. I have leads that i want to send leads to , I would like to be able to see if emails have been sent from the Updates section on the leads summary page.

I would also like to know why the emails section on the summary page always shows no email even though I have sent an email from that page to the leads. There seems to be no way to track what emails have

 been sent.

Can someone help me find a solution to this issue I am facing

![updates and emails notfication](https://user-images.githubusercontent.com/7829825/74219672-72c72980-4ce8-11ea-8fe6-6df69e0bcff5.png)

**Comment by rskrzypczak** [comment]
Mail scanner
https://www.google.com/search?q=Mail+%E2%80%93+Scanner+yetiforce
and maybe smtp configuration
![image](https://user-images.githubusercontent.com/10221999/74507748-a333e100-4efd-11ea-8b76-9b690c03a674.png)
