### ISSUE TITLE
[Question] Invoke custom function: How to mysqli_connect()

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#12572]
Hi all, 

I have create a custom function where **I want to update records directly in the database**, so without using the workflow 'Update fields'-option.

But, how do I fetch the connection details?

```
$con = mysqli_connect();
$sql = "UPDATE vtiger_contactdetails SET email= 'test@test.com' WHERE contactid = '116'";
return mysqli_query($con,$sql);
```

**Comment by vovpff** [comment]
```
$db = \App\Db::getInstance();
$db->createCommand('DROP TABLE IF EXISTS `a_vgdn`;')->execute();
```

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/nowy-silnik-komunikacji-z-baza-danych

**Comment by apcloic** [comment]
@mariuszkrzaczkowski Is there any english version of this documentation ?

**Comment by z0lo13** [comment]
it is yii2 
documention could be find here:
https://www.yiiframework.com/doc/api/2.0/yii-db-activequery
also the link above have some examples

**Comment by paula-w** [comment]
@apcloic  You can find the English version here: https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/new-db-communication-engine
