### ISSUE TITLE
Calculate fields in products

### ISSUE THREAD

**Issue by akromdoo** [YetiForceCompany/YetiForceCRM#12576]
Hi,

Can someone help me how to calculate fields in products. In version 4.2 i could do that now in 5.2 i cant as field unit_price gives {"currencies":{"1":{"price":31900}},"currencyId":1} reasult insted of 31900.

**Comment by davide-alghi** [comment]
Hi @akromdoo,
can you please be more detailed? What do you mean with 

> how to calculate fields in products

**Comment by vovpff** [comment]
You see raw data from database but why?
How you want to calculate price? Pls give more detailed explanation of your task.

**Comment by akromdoo** [comment]
Hi,

I enter a product and price is 5.000 € and i want in workflow to calculate tax for me when i save product and in Tax field i would have to have 1.100 €. 
When i do that in workflows in Update fields i put formula unit_price*0.22 as i did in older version but on new 5.2 version nothing hapens it stay 0 € value. 
I made extra field from curency field to calculate tax for me.
I think the problem si as @vovpff hase said as it shows raw data it cant make calculation and want to know how to make formula show only 5000 so it can make calculation.

I hope i made it clear what i want.
Thanks

**Comment by davide-alghi** [comment]
OK.
It's correct. unit_price field isn't a float value, but a string field: it contains P/S price in multi-currencies format. specifically in json format.
Maybe in YF 4.x was a float.
The alterative is to add a custom float field and insert doubly the price and calculate by this new one.
Else you have to implement, programmatically, a new workflow function to parse unit_price field and return float value on set currency.

**Comment by akromdoo** [comment]
Thanks do you know how to to that ne workflow function

**Comment by davide-alghi** [comment]
you need a YF developer
try to read these
https://github.com/YetiForceCompany/YetiForceCRM/issues/11678
https://github.com/YetiForceCompany/YetiForceCRM/issues/11659

try to search in Issues too
