### ISSUE TITLE
YetiforcePDF Tables broken after updating to 5.2 

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#12579]
Hello

Please help!!!

Im having a troubble. It seems my actual version of YETIFORCEPDF is corrupted. The tables brakes format when generating the pdf. I've been trying to repair the table, adjusted it, but nothing. In mPDF it was working perfectly.

Here is the table I done in composer:

![image](https://user-images.githubusercontent.com/40429279/74611778-1c4a5880-50f7-11ea-97e0-ee6d4a0511ca.png)

This is the result:

![image](https://user-images.githubusercontent.com/40429279/74611783-2f5d2880-50f7-11ea-8aa0-a607f66b7501.png)

This is de code of the table:
---------

[new.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/4210849/new.txt)

-------

**Comment by apcloic** [comment]
Hi,
Did you check supported css rules by YETIFORCEPDF ? 
https://github.com/YetiForceCompany/YetiForcePDF

**Comment by santyabreu** [comment]
Hi @apcloic 

Yes I did, the tables breaks when writing on colspan and cellspan merged cells

Any idea? Im making tests with no sucess

**Comment by santyabreu** [comment]
Solved... My direct opinion about YetiforcePDF.... please DO NOT CHANGE THE SYSTEM UNTIL EVERYTHING IS FULLY TESTED. This migration made me full of headaches. 

It is supposed that this is a Top One Software!!!! Thank you for your support (must be completely free when this changes are done)

**Comment by TonyM15** [comment]
One of my clients want to move vtiger to yetiforce (500+users), but there is like 200 PDFMaker templates where some of them are pretty complex - cannot do that. Will die trying recreate all of those formulas and nice design. I wish yeti have paid PDF extension with similar functionalities and user friendly GUI as PDFMaker from its4you (for vtiger)

**Comment by santyabreu** [comment]
@TonyM15 that's the same it occours to me. We are using this sofware in production, and We've been for a week stopped about this. The users (we) are being the real testers. Disagree!!!
