### ISSUE TITLE
Is there a Yetiforce book?

### ISSUE THREAD

**Issue by GregStevenson** [YetiForceCompany/YetiForceCRM#12588]
New to YetiForce looking to see what documentation exists. Came across this [link](https://findsbooks.com/index.php?file_name=yetiforce+book&spid=1i5tnvius47d4mq), but it seems to be somewhat bogus. It leads to a book download site, but after signing up, there does not seem to be a yetiforce book in their inventory.

Does such a Yetiforce book really exist?

**Comment by bpabiszczak** [comment]
No.
