### ISSUE TITLE
[Question] [PL] Zliczanie czasu 

### ISSUE THREAD

**Issue by maciejkopka** [YetiForceCompany/YetiForceCRM#12586]
### Description

Mam pytanie,
czy jest możliwość połączenia modułów Kalendarza z czasem pracy? Chodzi o to by po oznaczeniu zadania jako wykonane dodanego w kalendarzu i ustawienia godziny rozpoczęcia i zakończenia np od 13-14 w czasie pracy dodał się rekord z nazwą zadania i czasem trwania 1 godziny ?

**Comment by bpabiszczak** [comment]
To po co Tobie czas pracy, skoro masz kalendarz, który pokazuje 1:1 to samo :] To może rozliczajcie kalendarz. Odpowiadając jednak na pytanie, można napisać prosty skrypt, który będzie automatycznie robił takie wpisy. Zapewne to 1-2 h pracy
