### ISSUE TITLE
[Question] folder configuration for mail scanner

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12589]
dear all ,

i have made few query on open and closed issue but not able to understand the  solution

in my setting , Folder configuration is missing , but from witch menu , can i create the folder ?

from administration side or user side ?

i check all the menu below , can not find the template for folder creation

![image](https://user-images.githubusercontent.com/60758367/74779803-86513200-529e-11ea-9184-cdf699211147.png)

thanks for your help

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/74805567-c25ab600-52e3-11ea-8b27-486f40fa6e99.png)
https://gitdeveloper.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=Index&block=8&fieldid=44

**Comment by fanthome75** [comment]
Dear ,

using chrome V80  ,  following your link , works perfectly 

doing it , on my platform , page is becoming not responsive

![image](https://user-images.githubusercontent.com/60758367/74811769-7d8a4b80-52f2-11ea-86b7-4f7d88904d43.png)

my debug.php is set as below


[Debug.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/4223704/Debug.zip)

![yetiforce_settings](https://user-images.githubusercontent.com/60758367/74812591-0e155b80-52f4-11ea-8599-008e8257eb7d.png)

**Comment by rskrzypczak** [comment]
first:
![image](https://user-images.githubusercontent.com/10221999/74813579-cabbec80-52f5-11ea-83f3-b5d861aa24f1.png)
Check your `Mail – RoundCube` configuration. You probably have something wrong with it.
maybe port or server name in particular tls.

[Debugging](https://www.google.com/search?q=yetiforce+debugging)

**Comment by fanthome75** [comment]
will do and keep post updated - thanks

**Comment by fanthome75** [comment]
Great !   """Mail – RoundCube configuration. You probably have something wrong with it.""

works

![print](https://user-images.githubusercontent.com/60758367/74830393-57c16e80-5313-11ea-9bf3-4ff988a353d0.png)

**Comment by rohanjhanepal** [comment]
> Great ! """Mail – RoundCube configuration. You probably have something wrong with it.""
> 
> works
> 
> ![print](https://user-images.githubusercontent.com/60758367/74830393-57c16e80-5313-11ea-9bf3-4ff988a353d0.png)

For me those are already configured as show , but still no luck.
Login to mail server works like charm though

**Comment by rohanjhanepal** [comment]
Solved it by unticking "Validate Certificate" in same screen
