### ISSUE TITLE
[Question]  Making relationship between records

### ISSUE THREAD

**Issue by gjanczak-pfrportal** [YetiForceCompany/YetiForceCRM#12580]
### Description
I'd like to make standard relationship between Account record and Contact record on the code level. I get through some code and find method **Vtiger_Relation_Model::addRelation()** that was used in standard Save action. The problem is that when i run this code:

```php

/*
* $company is Account model
* $contact is Contact model
*/

$relation = Vtiger_Relation_Model::getInstance($company->getModule(), $contact->getModule());

if($relation){
    $relation->addRelation($company->getId(), $contact->getId());
}
```
i can't find it in contact list of account. What is interesting is that "Updates" shows that indeed relationship was created.

<img width="914" alt="Bez tytułu" src="https://user-images.githubusercontent.com/61156466/74670948-7526f900-51aa-11ea-938a-b9b041c72d1b.png">

I run out of ideas how to make this record show up in "Contacts list".

Can you provide some knowlage how to correctly make records relationship or point me to some examples?

**Comment by davide-alghi** [comment]
Hi @gjanczak-pfrportal,
updates box shows relation because a record was added to vtiger_relatedlists table.

My question is: did you insert account crmid into vtiger_contactdetails.parentid field?

**Comment by gjanczak-pfrportal** [comment]
@davide-alghi  It worked!
I may assume this is the case for all relationships?

**Comment by davide-alghi** [comment]
you are creating a 1:M relation
this is valid only for this type of relation
