### ISSUE TITLE
[Question] What does the 'Privileges'-column do in 'Filters - Configuration'

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#12599]
Hi all, 

I was wondering what is the function of the 'Privileges'-column in:
**System settings -> Labels, searching and filtering -> Filters - Configuration:**

![Aantekening 2020-02-20 144710](https://user-images.githubusercontent.com/16014524/74939525-5154f480-53f0-11ea-8eb1-5fa3bb12f5b6.jpg)

**Comment by davide-alghi** [comment]
Hi @LaurensCleyman,
Privileges switch enables/disables filter editing by **owner**
