### ISSUE TITLE
[Question] CRM GLOBAL SETTING

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12596]
hI TEAM  YetiForce

Would like to know ,  if all the setting made from interface system setting as administrator

are recorded 100 % in the database only  or there is also few scrip making change on files 

asking this question , for future requirement , 

 for exemple, if i proceed to a brand new install with a new release for exemple , backing-up the database will be enouth to recover all the setting ? or do i have also to backup few files

thanks

**Comment by davide-alghi** [comment]
Hi @fanthome75,

- config folder contains some by hand configurations
- user_privileges contains users access privileges
- custom contains custom translations


maybe other things are saved in files

**Comment by fanthome75** [comment]
hi @davide-alghi 

thanks for your contribution
