### ISSUE TITLE
[Question] RE-Open "How to enable The configuration in the Roles panel #12074"

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12597]
[closed without reply]

[How to enable The configuration in the Roles panel #12074[(url)

gitdeveloper  website

menu assign sharing user :  [https://gitdeveloper.yetiforce.com/index.php?module=RecordAllocation&view=Index&parent=Settings&type=sharedOwner&block=1&fieldid=102](url)

role sales department :  [https://gitdeveloper.yetiforce.com/index.php?module=Roles&parent=Settings&view=Edit&record=H10](url)

Where to enable assign sharing user ?

thanks

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/76545793-b13c3980-648a-11ea-95a2-a479a3e6c256.png)
