### ISSUE TITLE
[Error] De instalación - Menú faltante

### ISSUE THREAD

**Issue by eliuponce** [YetiForceCompany/YetiForceCRM#12607]
Buenas tardes, 

Soy nueva con Yeti Force, pero vengo trabajando con Vtiger desde hace algún tiempo, 

Realice la instalación, y no logro conseguir la opción de modificar los campos de la vista de lista, que en Vtiger está con un símbolo de cuatro cuadros unidos, en la vista de lista de cada módulo, al lado izquierdo, 

Investigando para validar donde tenía la funcionalidad en Yeti Force, me encuentro que el manual tiene la imagen de dicha funcionalidad en la cintillo superior del sistema, del lado izquierdo, 

Sin embargo, en la instalación realizada, no se muestra este menú, quisiera saber como lo arreglo, lo catalogo de error de instalación ya que no es igual el manual que mi sistema.

Agradecida

 

![image](https://user-images.githubusercontent.com/40632111/75062590-7e210e80-54b9-11ea-963e-3eaf5a888302.png)
 

# 🐞 bug report

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs
![github](https://user-images.githubusercontent.com/10198654/75072939-c57abf80-54f8-11ea-9ce9-9b473d97b5d3.jpg)
