### ISSUE TITLE
[bug] field account >  share with users > do no display value 

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12606]
Step 1 : create a simple workflow ,   when a new account is created and user = userA  update fields
share with user with value groupe1

workflow running correctly , record updated in tab update  when checking tab detail
field  share with user is empty 

checking directly in the database vtiger_account  there is no fields created by ; assigned to ; share with users  **in witch table are recorded those value** 

![image](https://user-images.githubusercontent.com/60758367/75058086-a1a88100-54da-11ea-99af-7ffdc6bee0c9.png)

![image](https://user-images.githubusercontent.com/60758367/75058261-f0eeb180-54da-11ea-9639-70b6ca8774bc.png)

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs
![github](https://user-images.githubusercontent.com/10198654/75073093-0bd01e80-54f9-11ea-9aff-f887f9811e4b.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version

**Comment by fanthome75** [comment]
hi, 

will follow next time - sorry for the mistake  [https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs](url)

Test made on the dev version ,  no bug  , should be on my server side 

i close this issue
