### ISSUE TITLE
YetiforcePDF <br /> ignored

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#12605]
Hi friends!!

YetiforcePDF is a nightmare!!! now, after remaking all forms now we've detecter that PDF is ignoring BR tag when a memo field is sent to pdf builder. We're a having a big problem!!! in our form we need this:

X bla bla bla
X bla bla bla
V bla bla bla..

and the system creates X bla bla bla X bla bla bla V bla bla bla

This is the field:
![image](https://user-images.githubusercontent.com/40429279/75054355-d6144100-54ca-11ea-83fe-e5977a49b809.png)

This is the printed pdf:

![image](https://user-images.githubusercontent.com/40429279/75054463-022fc200-54cb-11ea-93e7-ff1f16cc02be.png)

I've been trying with css with no sucess. I need a fix assap, please . Please any help!!!??

**Comment by Giorgos-Hellene** [comment]
Try with table

**Comment by santyabreu** [comment]
@Giorgos-Hellene  can you be a little bit more specific?

**Comment by Giorgos-Hellene** [comment]
When you try to create a pdf it is very easy to create a table. 

If you do it, your data will put in these cells
take a look at printscreen http://prntscr.com/r5v8da
It is from here https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=Edit&record=36

So it will be better to try create a table
notice that any cell and table has properties

**Comment by santyabreu** [comment]
It doesn't solve this problem. It's a Memo field. We have thousands of registry we cannot separate into fields. The pdf must accept the LF or BR and in this moment it is joining all the lines into one.

**Comment by davide-alghi** [comment]
hi @santyabreu, just a question: is a textarea field in your first screenshot? or is it a richtext (wysiwyg) field?

**Comment by santyabreu** [comment]
@davide-alghi it's a text field

**Comment by davide-alghi** [comment]
did you think about to move incriminated contents to a richtext? ... maybe yes but it is a big work?!?

**Comment by santyabreu** [comment]
I will try with another field and see if it does the br

**Comment by davide-alghi** [comment]
richtext should to go to a new line

**Comment by rskrzypczak** [comment]
I don't see this problem.
What YetiForce and YetiForcePdf version are you using?
![texarea](https://user-images.githubusercontent.com/10221999/75316389-85536e00-5865-11ea-9617-0f71294cd070.gif)

**Comment by davide-alghi** [comment]
sorry, I replied without checking the problem.
I just tried on 5.0, 5.1, 5.2 with last SP and both textarea and richtextbox render new lines in PDF.
Mine are fresh installation, not migrations.

**Comment by santyabreu** [comment]
Hello @davide-alghi Thank you for your review

In fact under new installations there is no bug on this. But in migrations we have a big problem with this little thing. I've been trying with two installations that are jumping from 4.4 to 5.2 both reflects the same problems, BR are ignored. On new ones there is no problem. So we must think about to solve this. We cannot make a new installation under productive environments.

Reserching a little bit more in this problem the PDF builder on every LF makes a tag of <span style=(whatever)> if I change this <span to <p the system understands the change, but only if I save from HTML. If I save from "wysiwyg" the builder insterts again the <span tag.

Pleae consider a round job about this bug on migrated sites. This is a really nightmare...

Thank you so much in advance

Best regards

**Comment by davide-alghi** [comment]
so, you have the same problem with both textarea (LF) and richtextbox (BR).
let's try with paragraph (p). please make this test

- create a new PDF template
- in content area type some text 
- go to new line pressing shift-return: this insert a paragraph (P tag); return insert a BR
- insert other text
- save and try to generate PDF

**Comment by rskrzypczak** [comment]
If you have issues after migration then the update most likely wasn't successful. Compare clean instance files with the updates ones, and if there are any discrepancies then most likely you will have to fix more than just that. 

I would do this instead of looking for a cause in who knows what code
