### ISSUE TITLE
Cron Task Error

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#12600]
Warning: Declaration of Settings_CronTasks_Record_Model::getDisplayValue($fieldName) should be compatible with Settings_Vtiger_Record_Model::getDisplayValue(string $key) in /home/**MyWebsite.com**/modules/Settings/CronTasks/models/Record.php on line 0.

I went in and corrected the php file with _getDisplayValue(string $key)_  but afterwards all the cron job disappeared. How do I fix this?

**Comment by rskrzypczak** [comment]
I think you forgot to replace the $fieldName variable with $key inside the function :)
that's why everything stopped working.

check this: https://github.com/YetiForceCompany/YetiForceCRM/commit/40990487e05d5e5f457ac5add3cd0cb90bb9a331#diff-2ec1e2b4c5415ead463aac2105acbf01R178
