### ISSUE TITLE
[Feature] Left menu scrolling issue

### ISSUE THREAD

**Issue by TonyM15** [YetiForceCompany/YetiForceCRM#12615]
Guys, left menu scrolling soooooo slow. Nee to adjust wheel rate maybe?

**Comment by mariuszkrzaczkowski** [comment]
give more details

**Comment by TonyM15** [comment]
Click menu Databases and use wheel to scroll down the menu position (use some smaller screen).
It slow like snail

**Comment by bpabiszczak** [comment]
It works perfectly.
