### ISSUE TITLE
How to filter Contact type by user group or role?

### ISSUE THREAD

**Issue by sandrosousa** [YetiForceCompany/YetiForceCRM#12619]
Hello, is possible to have diferente types of contacts and only give access to them depending on user group/role?
For example contact type A is only accessible by users from group A and contacts of type B only for users of group B.

Is that possible or i have to duplicate contacts module and give different accesses by module?

Thanks

**Comment by davide-alghi** [comment]
Hi @sandrosousa,
directly by role/group no; but you can "_assign_" contacts by "share with users" and disable "assigned to" and "share with users"  fields editing in target role/group.

Take into account that duplicating the Contacts module with all its behaviors is not an easy task.

**Comment by sandrosousa** [comment]
Thanks @davide-alghi,
So what the best approach to accomplish these need to split contacts in "types" and give access to  them depending on some role/filter/field?
Can i create a custom module that inherit contacts module attributes? like map, emails, comments, calls....
I just need contacts module to record all types of communications (email, sms, call) with the contacts, but i need to control witch user/group access to witch contact.

Regards
Sandro

**Comment by davide-alghi** [comment]
I understood your needs.
If you wanna clone Contacts module you need an YF developer.
