### ISSUE TITLE
[Question] PHP Fatal error

### ISSUE THREAD

**Issue by iputhil** [YetiForceCompany/YetiForceCRM#12612]
I am new to YetiForce and I have a problem even before installation is started. 

I set up a CentOS 7 server following "Web server requirements", then I unpacked YetiForceCRM-5.2.0-complete.zip to /var/www/html and pointed my web browser to the website, but the page is blank. If I tun on "display_errors", I get this:

PHP Fatal error:  Can't use function return value in write context in /var/www/html/include/main/WebUI.php on line 153

The same error is reported in /var/log/httpd/error_log and error 500 in access_log.

I hope someone will be able to help me since I have no idea what's going on. I have looked at the source code, but I see no write context at line 153.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/75100453-e3662400-55cd-11ea-871d-89c15cb4356a.jpg)

**Comment by iputhil** [comment]
I solved this problem. For some reason I believed I had PHP version 7.2, but it was 5.4. When I upgraded to 7.2 this problem went away.
