### ISSUE TITLE
[Question] Account forwarding address copy from account

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12614]
Hi team,

can you explain how to use it.

From https://gitdeveloper.yetiforce.com/  not able to understand no pop up display to choose account in list

![choose account](https://user-images.githubusercontent.com/60758367/75099056-8e221680-55bd-11ea-9ba8-fbd66b9361fd.gif)

**Comment by davide-alghi** [comment]
You have to fill "Member of" before get address from that.
Accounts are hierarchical.

**Comment by fanthome75** [comment]
thanks
