### ISSUE TITLE
[Question] VTIGER_account  Table

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12617]
Hi Team ,

Fields :  Assigned to   and  share with users  

![image](https://user-images.githubusercontent.com/60758367/75144778-fe34b780-56f7-11ea-9570-ed2851f50792.png)

are not recorded in VTIGER_account Table 
can you tell me in witch table name  those fields are recorded

Thanks

**Comment by davide-alghi** [comment]
Assigned to => vtiger_crmentity.smownerid
Share with users => u_yf_crmentity_showners.userid

**Comment by fanthome75** [comment]
thanks Davide
