### ISSUE TITLE
CRON - w formacie BASH

### ISSUE THREAD

**Issue by kapsel2105** [YetiForceCompany/YetiForceCRM#12613]
Witam wszystkich :-)

Zacząłem swoją przygodę z Yetiforce.
Niestety nadal mam problem z uruchomieniem Cron`a :-(
Czy jest możliwość otrzymania wpisów jakie należy wpisać w BASH, (niestety takie dostałem informację od hostingu (d.h.o.s.t.i.n.g) ) nie mam dostępu do pliku crontab :-(
Lub jakieś naprowadzenie jak takie wpisy należy zmienić.
Z góry dziękuję za pomoc.

**Comment by mariuszkrzaczkowski** [comment]
Co to za hosting ?

**Comment by kapsel2105** [comment]
... dhosting.pl

**Comment by bpabiszczak** [comment]
Wszystko co jest potrzebne do uruchomienia cron-a znajduje się w tym artykule: https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-administratora/item/uruchamianie-crona, wyślij im link do tego, powinni tobie pomóc co ustawić w tym panelu [obrazek poniżej]:

PS.: My też mamy hosting za 20 euro miesięcznie :P

![image](https://user-images.githubusercontent.com/10197525/75112082-b69f2480-5640-11ea-8b9a-9ba1c9b148c1.png)

**Comment by kapsel2105** [comment]
Dziękuję za odpowiedź.

Oczywiście że wysłałem. Zarówno już przerobione ścieżki zgodnie z umiejscowieniem php, jak i sam link do dokumentacji (j.w.)
Niestety odpisali abym skontaktował się z producentem aplikacji, aby wpisy cron "ubrać" w bash.

Tak, szperałem na waszej stronce, wiem że macie hosting :-) jednak przy nowej firmie, w porównaniu z nimi jesteście o jakieś ~400% drożsi :-(.

**Comment by bpabiszczak** [comment]
Nie są tańsi, po prostu oferują mniej :] [mniej dysku, mniej ramu, mniej procesora, mniejsze limity konfiguracji - wszystkiego mniej] Jeżeli nie potrafią uruchomić CRON-a to nie dobrze :P

**Comment by bpabiszczak** [comment]
CRON można uruchomić z CLI [to chyba oni nazywają bash] i z www. Obie metody zostały opisane w artykule, który linkowałem wcześniej. Niech do nas zadzwonią jak mają z tym problem.
