### ISSUE TITLE
[PL] Loader się zawiesza

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1262]
Konfiguracja systemu > Uprawnienia>Role> wybieram np Zarząd> Klikam na PLUSA DODAJ ROLE i za każdym razem loader na chwile się zawiesza
![66](https://cloud.githubusercontent.com/assets/11139594/8449085/7edc422e-1fce-11e5-9dd2-f5bd1ec55ecd.png)
![66](https://cloud.githubusercontent.com/assets/11139594/8449099/aa461ce6-1fce-11e5-9d92-d058417db345.png)

https://gitdeveloper.yetiforce.com/index.php?module=Roles&parent=Settings&view=Edit&parent_roleid=H10

**Comment by rskrzypczak** [comment]
To nie jest błąd. Po prostu trwa ładowanie wszystkich uprawnień.
