### ISSUE TITLE
[Question]  Module - customs fields  - safe upgrade

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12628]
Hi Team ,

i am in charge to try and implement YETIFORCE for the company.

I am not a high developper .  The idea is to prepare 90 % of the setting  and getting support
from team yetiforce for final setting with paid service

but i need to customize few modules , when adding  custom fields ,
working on sales enquiry  , main table is u_yf_squoteenquiries

when making this from  standard modules >edit fields

  there is only 2 proposals

![proposal](https://user-images.githubusercontent.com/60758367/75249986-a2d9f680-57d7-11ea-8a32-d4b3c5846bf7.png)

best choice for safe upgrade in future is the first one or second one 

Is it possible to add those customs fiels directly in the concern table u_yf_squoteenquiries

thanks

**Comment by davide-alghi** [comment]
Hi,
initially (by Vtiger team), engine was implemented with the "Additional" (cf suffix) table for custom fields (cf). In YetiForce the feature has been extended (by YF team) to both tables: Basic and Additional.
Currently, in YF, you can add custom fields indifferently to both tables and with the same properties and behaviors.
IMHO, if I have to find a difference, it's more likely that future "structural" changes can be done on Basic table. From my point of view, I consider "_more correct_" to add a custom field to cf table.

Anyway ... there are no particular impediments to choosing.

_________________________________________
> Is it possible to add those customs fiels directly in the concern table u_yf_squoteenquiries

```u_yf_squoteenquiries``` is the Basic table for Sales enquiries.

PS it would be interesting to know why you prefer to add custom fields to the Basic table

**Comment by fanthome75** [comment]
Hi Davide ,

thanks , will go ahead with "vtiger_accountcf"

Why to the basic table , may be a miss understanding about developpement side
This fields will be use and display only in the module " sales enquiries"  and will not use in account view,  so to avoid confusion , i was thinking to add it directly in the table u_yf_squoteenquiries

but as i said certainly miss understanding

**Comment by davide-alghi** [comment]
@fanthome75,
just a note: in your screenshot you see

- Basic (**eg**. vtiger_account) and
- Additional (**eg**. viteger_accountcf)

but those are only examples (**eg**), only labels. They were taken vtiger_account and viteger_accountcf tables names only as examples: your new field will not be stored into vtiger_account or vitger_accountcf. Your new fields for Sales enquiries will be stored into u_yf_squoteenquiries (Basic for Sales enquiries) or u_yf_squoteenquiriescf (Additional for Sales enquiries)

I hope you understand what I want to tell you
