### ISSUE TITLE
How to view related modules records in both modules?

### ISSUE THREAD

**Issue by sandrosousa** [YetiForceCompany/YetiForceCRM#12629]
Hello,

I have a custom module "Events" that have a relation with contacts module, so 1 contact can have many events and 1 event can have many contacts.
I want to show in Contact view a tab with all events that is registered and in the Event view a tab with all Contacts registered.
How to implement this view in both modules?

Regards
Sandro Sousa

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/75418564-198c0680-5934-11ea-88b7-db21e1438086.png)
Activate button: https://github.com/YetiForceCompany/YetiForceCRM/issues/2249
But be careful when you manipulate relationships, this option is disabled for a reason.

**Comment by sandrosousa** [comment]
Thanks @rskrzypczak , but I already done that, I have the "add relation" button and add a relation between contacts and events.
The problem is that in events module I can see all selected contacts but when i go to one of the select contacts the event is not listed.
How do I show in contacts the respective events?

Regards
Sandro

Regards

**Comment by rskrzypczak** [comment]
You probably have relationships set up incorrectly. In both modules there should be an M:M relation
