### ISSUE TITLE
[Question] ACCOUNT FIELDS and MODULE

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12621]
hI  Team,

i'am working on the setting of account module 

Would like to know the purpose of those fields,   i am wondering if it is for workflow 

event [crmactivity]
Data verification [verification]
updated   y/n
ownership

What's happen if a module is switched from basic to advanced ?

Last question 

With the drag and drop , i am trying to move a field from one block to another one 

exemple :  primary phone  moved from block contact info to  account detail , i save the field,
but position is not keeped 
can you help

**Comment by LaurensCleyman** [comment]
> With the drag and drop , i am trying to move a field from one block to another one
Click the button 'Save field sequence'
![Aantekening 2020-03-03 115854](https://user-images.githubusercontent.com/16014524/75769393-63b32480-5d46-11ea-9156-a305d6f426be.jpg)
