### ISSUE TITLE
Creating a PDF of a Quote

### ISSUE THREAD

**Issue by 2techcomputing** [YetiForceCompany/YetiForceCRM#12620]
I have created a quote in the CRM but i do not see an option to save it to a PDF so that i can show my customer. Is there a step i missed in order for the option to appear or do i need to create a PDF template for quotes. If a template needs to be created how do i go about creating one with the correct fields?

**Comment by davide-alghi** [comment]
Hi @2techcomputing,
yes, you have to create a PDF template here
https://gitstable.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35

**Comment by 2techcomputing** [comment]
@davide-alghi Alright i got a template to appear for Quotes now. I have another question though, is it possible to create quotes directly without the need of creating a sales enquiry, then a sales requirement and then a calculation. I dont need the additional property's of that and wish to just create quotes directly. Any idea if that is possible?

**Comment by davide-alghi** [comment]
yes, you can. you have to modify sales process. I'm going to give you an example, but my reccomendations are:
- before to go in production try it on an YF test instance
- check if all features, after sales process modification, are preserved for your needs

here how to
https://www.youtube.com/watch?v=l4AGy0bKWwA

**Comment by 2techcomputing** [comment]
@davide-alghi perfect, that video worked, thank you for your help.
