### ISSUE TITLE
[Question] Sales process  converting customer quote to customer order

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12636]
hi ,

before posting trying to find the reply on the forum and on youtube , but not able to track any 
help

howto convert a quote to order  ( including  product and service ) with yetiforce

just found  this post  : https://github.com/YetiForceCompany/YetiForceCRM/issues/1917
long chat with no solution

 we would like to do this :   https://youtu.be/sMkMJYo5984

is it possible to achieve this with no progaming

**Comment by fanthome75** [comment]
HI ,

Found it ,  i will made a screenvideo and post it for all the guy in my situation

Documentation is really poor ,  this is boring , 

this is not a good sign for people who want to try and will be possible good donateur for future

best regards

**Comment by waran70** [comment]
Before you start throwing stones give a good try and dont expect documentation and immediate help from free software devs. Remember: this is free product
