### ISSUE TITLE
LBL_LABEL_SCRIPT_USERLBL_LABEL_SCRIPT_USER

### ISSUE THREAD

**Issue by vickoza** [YetiForceCompany/YetiForceCRM#12630]
what in the value to set the LBL_LABEL_SCRIPT_USER when installing YetiForceCRM on FreeBSD?

**Comment by davide-alghi** [comment]
Hi @vickoza,
please could you be more detailed?
where does that label (LBL_LABEL_SCRIPT_USER) come from?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/75420314-17c44200-5938-11ea-8b55-e0c767400583.jpg)

**Comment by IpsaSciemtioPotestasEst** [comment]
https://gitlab.com/gitlab-org/project-templates/iosswift.git

**Comment by vickoza** [comment]
Parameter | Present values
-- | --
CRM version | 5.2.145
Version release date | 2020.02.21
Operating system | FreeBSD Laxmi2 12.1-RELEASE-p2 FreeBSD 12.1-RELEASE-p2 GENERIC amd64
Server ID | Apache/2.4.41 (FreeBSD) OpenSSL/1.1.1d-freebsd
LBL_LABEL_SCRIPT_USER | www (uid:80)
Temporary directory | /tmp//YetiForceTemp5ee8f691/
CRM Local directory | /usr/local/www/apache24/data/pcbcrm
Server API | apache2handler
LBL_LABEL_ZEND_VERSION | 3.2.0
Locale | en_US_POSIX

**Comment by vickoza** [comment]
ho do I set the apache setting to re color the PHP data in the Virual host
![image](https://user-images.githubusercontent.com/14866412/75475890-3c7fe000-595f-11ea-9ca1-2219620f2d7c.png)

**Comment by mariuszkrzaczkowski** [comment]
1. from where you downloaded developer version ?
2. the site has no styles so there are some errors and the installation will be incorrect
3. the development version may not have all translations

**Comment by davide-alghi** [comment]
maybe you are working on (wrong) developer version. are you installing via composer?

... anyway, some useful links:

- developer version: https://download.yetiforce.com/developer.zip
- stable (production) version 5.2: https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/5.2.0/
- stable version service packs (v19): https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/Update%20packages/ 

PS: https://github.com/YetiForceCompany/YetiForceCRM/blob/1ae75c1f52dea884208fc510f1450223922020c3/languages/en-US/Settings/ConfReport.json#L239

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases

**Comment by vickoza** [comment]
I cloned the git repository I think this has to do with an Apache configuration in the virtual host as getting through other means shows the 
https://github.com/YetiForceCompany/YetiForceCRM.git

**Comment by mariuszkrzaczkowski** [comment]
try to run it, you will compare https://download.yetiforce.com/developer.zip

**Comment by vickoza** [comment]
I think the display setting has to do with the https setting because if I log into the site with http the display work fine but the display is corrupted if I log into the site using the https. I think it does not share images or css on https

**Comment by mariuszkrzaczkowski** [comment]
this is a server configuration error, check the vhost configuration for https
