### ISSUE TITLE
[Question] product - subunit    how doect it work

### ISSUE THREAD

**Issue by fanthome75** [YetiForceCompany/YetiForceCRM#12639]
Dear forum

query with "  is:issue is:open is:closed [question]  subunit "" do not give any result , somebody get
experience with a product  subunit 

[https://gitdeveloper.yetiforce.com/index.php?module=Products&view=Detail&record=579](url)

field subunit has some value 

when going for edition ,   this field become empty 

![image](https://user-images.githubusercontent.com/60758367/75539063-f176d300-5a19-11ea-9e1a-b526731a1ec4.png)

Some help will be highly appreciated

**Comment by davide-alghi** [comment]
here
https://gitstable.yetiforce.com/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9

and here
https://gitstable.yetiforce.com/index.php?module=PickListDependency&parent=Settings&view=Edit&sourceModule=Products&sourcefield=usageunit&targetfield=subunit

I would have a prayer: please, spend some time studying YF; your questions are very basic
