### ISSUE TITLE
[Question] Show more than 20 records in a view

### ISSUE THREAD

**Issue by alexynadamas** [YetiForceCompany/YetiForceCRM#12637]
Hi

Is posible to show more than 20 records in a view? for example in invoicing

Thanks

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/35b2d5a526698fc4788f0d05be5695b3f83145bd/tests/setup/config/Main.txt#L72-L73
