### ISSUE TITLE
Possible to change Organisation structure name ?

### ISSUE THREAD

**Issue by K-MeLeOn** [YetiForceCompany/YetiForceCRM#12643]
Hello,

Is possible to change Organisation Structure name ?

I had set with " - CRM" at the end and now I just want the company name.

Thanks you in advance !

**Comment by davide-alghi** [comment]
Hi,
do you mean this?
https://gitstable.yetiforce.com/index.php?parent=Settings&module=Companies&view=List&block=3&fieldid=14

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=MultiCompany&view=List&mid=152&parent=76
?

**Comment by K-MeLeOn** [comment]
Woaaa,
Thanks you for you speedy response !

Is here, the combobox after label "Organizational structure":
https://gitstable.yetiforce.com/index.php?module=Roles&parent=Settings&view=Edit&parent_roleid=H1

**Comment by davide-alghi** [comment]
fantastic 3 replies 3 different links :rofl::rofl::rofl: ... I'm joking

**your right link is the Mariusz link**

**Comment by K-MeLeOn** [comment]
Haha, I'm regarding with the mariuszkrzaczkowski.

**Comment by K-MeLeOn** [comment]
Okay, is the good solution !
Sorry for your lost time.

Good community, it's too bad I'm not PHP developper.
