### ISSUE TITLE
[Question] - YetiForce Portal 1-2

### ISSUE THREAD

**Issue by K-MeLeOn** [YetiForceCompany/YetiForceCRM#12649]
Hello everyone!

I am really pleased with this CRM.
I am a former user of Vtiger and YetiForce is a big update for my customers. I promise you that when I earn enough money, I will give a good contribution.

I'm trying to install the YetiForce portal but all the documentation is gone!
I'm a desktop developer, I try to configure the second version of the portal with the configuration but it's the same problem. I can't find the necessary documentation and I don't understand the settings of two trees.

The css don't appear...etc.

Do you have information about the portal documentation?

Thank you in advance!

**Comment by davide-alghi** [comment]
Hi @K-MeLeOn,
the customer portal has not yet been released

https://github.com/YetiForceCompany/YetiForceCRM/issues/11681#issuecomment-583907355

**Comment by PhilEngel** [comment]
Hi David, just checking if the portal has a date for release? if not will portal v3 in any way work with the current Yetiforce release? Get a language error when installing..

**Comment by davide-alghi** [comment]
Hi @PhilEngel, I just saw Customer Portal v2 was updated 2 days ago: I'll try it over the afternoon.
But just a question: where have you read about v3?

**Comment by PhilEngel** [comment]
Hi David, https://sourceforge.net/projects/yetiforce/files/YetiForce%20Portal%203.x.x/

**Comment by davide-alghi** [comment]
ok, but that is the old one (YF Portal (1) version 3.x.x); it's outdated.
https://github.com/YetiForceCompany/YetiForcePortal
please take a look to the dates

the current and in progress customer portal is YF Portal 2 version n.a.
https://github.com/YetiForceCompany/YetiForcePortal2

**Comment by mariuszkrzaczkowski** [comment]
I corrected the names on sourceforge.net

**Comment by PhilEngel** [comment]
Thanks, tried the v2 you suggested but also getting an error when installing - Failed
Module does not contain default language (en-US).
