### ISSUE TITLE
[bug]  https://github.com/YetiForceCompany/YetiForceCRM/blob/5.2.0/tests/setup/php_prod.ini is missing 

### ISSUE THREAD

**Issue by vickoza** [YetiForceCompany/YetiForceCRM#12651]
# 🐞 bug report

### ⁉️ Describe the bug

https://github.com/YetiForceCompany/YetiForceCRM/blob/5.2.0/tests/setup/php_prod.ini is missing because https://github.com/YetiForceCompany/YetiForceCRM/blob does not exist  this php file may still exist somewhere else  the solution may either update the 
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/crm-installation
page to reflect the new location of this file or create the blob folders

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by davide-alghi** [comment]
Hi @vickoza,
I cannot understand which is the bug.
**tests/** folder is for PHPUnit testing, it is not part of application.
**tests/** folder is used from YF team not included into stable/development release

or I'm missing something?

**Comment by vickoza** [comment]
the blob folder is not part on the git report this would be a bug in the documentation about how to install YetiForceCRM to a bug in the code. I fix is simple either remover the link to this repo in the 
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/crm-installation
 or add the folders and files

**Comment by mariuszkrzaczkowski** [comment]
The "tests/setup" directory contains an example configuration of a production and development server. This is to help you configure the server by placing ready-made configuration files.

**Comment by rskrzypczak** [comment]
I don't see the problem on the website anymore.
