### ISSUE TITLE
alert-warning:LBL_IMPORT_FILE_DIFFERENT_ENCODING

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#12658]
I am getting this alert-warning while import the records in lead module.Please help how fix this alert-warning .It is not allowing me to import records in any module.
![Import Bug](https://user-images.githubusercontent.com/47585969/75767107-42633000-5d68-11ea-98f7-33ecb4ab7fee.JPG)

**Comment by mariuszkrzaczkowski** [comment]
duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/12136 https://github.com/YetiForceCompany/YetiForceCRM/issues/11762
