### ISSUE TITLE
[PL] Nazwa niepełna w oknie

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1265]
Sprzedaż>Oferty>Przycisk AKCJE>Wyszukiwanie duplikatów>Otwiera się okno> nazwa w polu nie jest pełna: WYBIERZ KILK
https://gitdeveloper.yetiforce.com/index.php?module=Quotes&view=List&parent=52
![69](https://cloud.githubusercontent.com/assets/11139594/8449974/8cacf7ec-1fd6-11e5-8010-4da4e402f19b.png)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1255
