### ISSUE TITLE
Knowledge Base default landing page

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#12652]
How to change Knowledge Base module default landing page ""from record list page to Knowledge Base page"". We are able see this functionality in Demo.

**Comment by rskrzypczak** [comment]
`config\Modules\KnowledgeBase.php`

> /** Default module view. Values: KnowledgeBase, List, ListPreview or DashBoard, refresh menu files after you change this value */
	public static $defaultViewName = 'KnowledgeBase';

**Comment by guide5232** [comment]
This changes is not effecting on default landing page in Knowledge Base module. i have removed files completely but i did not notice any changes.

![Base1](https://user-images.githubusercontent.com/47585969/75751356-4da86280-5d4c-11ea-95d0-8f58ecbccfc4.JPG)

**Comment by rskrzypczak** [comment]
It works.
You are sure you understood this part?:

> refresh menu files after you change this value

![menu](https://user-images.githubusercontent.com/10221999/75753429-09589a80-5d2b-11ea-8111-e9dbd1f58dba.gif)

**Comment by guide5232** [comment]
Oh sorry i did not refresh my menu.Now it is working.
Thank you

**Comment by JohnMaverick** [comment]
Here rfeshing menu (after changing value to the "List" giving me screen hang
![image](https://user-images.githubusercontent.com/29787568/149858017-a0795e04-19fe-47de-b254-24c9e68b18e9.png)

**Comment by mariuszkrzaczkowski** [comment]
> Tutaj rfeshing menu (po zmianie wartości na "Lista" co powoduje zawieszenie się ekranu ![obraz](https://user-images.githubusercontent.com/29787568/149858017-a0795e04-19fe-47de-b254-24c9e68b18e9.png)

Create a new bug report with complete information
