### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by nitishp001** [YetiForceCompany/YetiForceCRM#12666]
Hi,

I was trying to use this CRM software on my computer.
But I am getting this error

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in C:\xampp\htdocs\YetiForceCRM-5.2.0-complete\app\Config.php on line 58

Kindly help

My email id is nitish.p001@gmail.com

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/75995749-28a72180-5efd-11ea-9a2f-485d1b3aa9ce.jpg)
