### ISSUE TITLE
.htaccess recommended security setting

### ISSUE THREAD

**Issue by ozinfotech** [YetiForceCompany/YetiForceCRM#12667]
This is more a niggle, than anything else, but when installing I get an error showing that the ".htaccess file is inactive, it is required to properly handle all integrations and to secure the directories containing user data."
![htaccess](https://user-images.githubusercontent.com/35508717/76008392-3052d000-5ed5-11ea-8253-8cb511edebb7.png)

Yet, when I add the directive of "order deny, allow" and "deny from all" in the .htaccess file and refresh the page, I end up being forbidden from the site, as I should be.
![403-error](https://user-images.githubusercontent.com/35508717/76008516-61cb9b80-5ed5-11ea-8908-aa28ebab0014.png)

Is there something that I am missing from this error message? I'm not quite sure why it states that the .htaccess file is not "on" when clearly it is working.

**Comment by ohandy1** [comment]
yer not alone

**Comment by ozinfotech** [comment]
I should mention that the fix for this issue was to enable the DSO extension for PHP and then set the PHP handler to DSO.
