### ISSUE TITLE
[bug] Related record list not updated

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#12665]
# 🐞 bug report

### ⁉️ Describe the bug
In the Contact module I add two custom fields 'Related field 1:M' which point to another contact (the parents).

![image](https://user-images.githubusercontent.com/16014524/75983279-8715d500-5ee8-11ea-8d9e-36b2c260cde4.png)

In the contact record of _Tom Kowalski_ I select his parents in those fields:
![image](https://user-images.githubusercontent.com/16014524/75983600-1ae7a100-5ee9-11ea-9f64-7c8015a8956b.png)

If I then go to the 'Contacts'-tab of the _Daddy Benjamin_ then I don't see _Tom Kowalski_ in the list.
![image](https://user-images.githubusercontent.com/16014524/75983809-803b9200-5ee9-11ea-8850-7b3351e0201f.png)

I think the record should be visible overthere or did I miss something?

### 👎 Actual Behavior
Record not visible

### 👍 Expected Behavior
Record should be visible

### 👷 Testing 
- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com 
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by vovpff** [comment]
I think you can find Tom at Mommy record contacts tab. This happens because you can have only one relation between module A and B

**Comment by LaurensCleyman** [comment]
Hi @vovpff , 

You are correct, I did not notice that:
![image](https://user-images.githubusercontent.com/16014524/76001371-4aa4a200-5f05-11ea-8b1a-242c5f199455.png)

Any advice how I can achieve my goal? I want to add multiple parent contacts to a contact (a mom, a dad, a grandparent, ...)

Kind regards,

Laurens

**Comment by bpabiszczak** [comment]
This must be done by the programmer.
