### ISSUE TITLE
[bug] Unsuccessful Installation

### ISSUE THREAD

**Issue by ozinfotech** [YetiForceCompany/YetiForceCRM#12668]
# 🐞 bug report

### ⁉️ Describe the bug

I downloaded the complete version (5.2.0) of YetForceCRM. The process of installing via the web interface was fine until the final stage where I received an "installation unsuccessful" error.

### 🔥 How to trigger the error

1. wget the complete [YetiForceCRM version 5.2.0] (https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.2.0/YetiForceCRM-5.2.0-complete.zip) from a command line
2. Unzip the files
3. Enable debugging according to the section below
4. Start the installation process from a web browser and ensure requirements are met (note: I am seeing an error for the .htaccess file and reported it [here](https://github.com/YetiForceCompany/YetiForceCRM/issues/12667))
5. Finalize the installation
6. Receive "Installation unsuccessful" error

### 👎 Actual Behavior
Receive an "installation unsuccessful" error when attempting to install for the first time.

### 👍 Expected Behavior
Was hoping the installation would have occurred correctly.

### 👷 Testing 

N/A as these tests assume that the CRM is installed.

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

For the e-mail, I am including screenshot and cache/logs/system.log as that is the only log in the cache/logs folder.

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.2.0
| Web server (name and version)|	Apache 2.4.41
| PHP  |	7.3.15							|
| Browser (name and version)  | Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)		|
| Operating System (name and version)  | CENTOS  7.7 		|
| Database (name and version) | mySQL phpMyAdmin v4.9.4 with WHM version 86.0.9		|

### ❓ Additional context
None at this time.

**Comment by davide-alghi** [comment]
Hi @ozinfotech,
you have to fix your htaccess problem before install.
you wrote VHM as webserver, but that is your web host manager, not the webserver: maybe is it apache?

anyway, to enable htaccess you need something like this
```HTML
<Directory /var/www/html/yetiforcefolder/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```
into your web server virtualhost file (AllowOverride All is mandatory)

**Comment by mariuszkrzaczkowski** [comment]
it looks like there is a problem loading the database. send php error logs and database logs

**Comment by ozinfotech** [comment]
> Hi @ozinfotech,
> you have to fix your htaccess problem before install.
> you wrote VHM as webserver, but that is your web host manager, not the webserver: maybe is it apache?
> 
> anyway, to enable htaccess you need something like this
> 
> ```
> <Directory /var/www/html/yetiforcefolder/>
>     Options Indexes FollowSymLinks
>     AllowOverride All
>     Require all granted
> </Directory>
> ```
> 
> into your web server virtualhost file (AllowOverride All is mandatory)

DOH! You are right, I've updated the webserver as Apache 2.4.41.

For some reason, I can't seem to get the changes to show up in the httpd.conf file. I've used all of the 'safe' locations to edit the files by adding that directive with the proper folder location including _/etc/apache2/conf.d/includes/pre_main_global.conf_, _/etc/apache2/conf.d/includes/pre_virtualhost_global.conf_, and _/etc/apache2/conf.d/includes/post_virtualhost_global.conf_. Whenever I restart Apache, however, the directive never gets integrated.

> it looks like there is a problem loading the database. send php error logs and database logs

I've got the SQL_DIE_ON_ERROR variable set to _true_ in the _Debug.php_ file. When I set it to _false_, I still got an 'installation unsuccessful' error. To retry the installation I had to keep dropping all the tables to try the install again. It appears that until the .htaccess issue is resolved, I'm stuck doing this unless you really want me to do it and see what happens.

**Comment by davide-alghi** [comment]
as Mariusz suggests, please attach Apache **error** log and MySql log.
the logs only from start installation time to installation crash time

**Comment by ozinfotech** [comment]
I think I found a bug in cPanel. I finally figured out I needed to put a .conf file for that particular host according to the httpd.conf file for ensuring that the .htaccess problem is resolved. After creating the file and running the '_/scripts/ensure_vhost_includes --all-users_' script, the httpd.conf file only includes the custom .conf file for port 80, but not port 443,. I'm requesting assistance from cPanel to fix this, and then I'll continue with the error logs if there are still issues.

**Comment by ozinfotech** [comment]
Here is the system.log.
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4326741/system.log)

And then the SQL error log.
[domain.name.err](https://github.com/YetiForceCompany/YetiForceCRM/files/4326941/domain.name.err.log)

And finally the Apache error log.
[error_log.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4326948/error_log.log)

The Apache error log fills up with those errors after the web site has been dormant for a while. I have the site locked down just to specific IP addresses at the moment, so there should not be anything hitting it from the public internet.

**Comment by mariuszkrzaczkowski** [comment]
The ModSecurity module in apache blocked the installation, admin server must take care of it
```
[Thu Mar 12 16:41:05.135314 2020] [:error] [pid 13705] [client 165.x.x.x:43680] [client 165.x.x.x] ModSecurity: collections_remove_stale: Failed to access DBM file "/var/cpanel/secdatadir/yetiuser-global": Permission denied [hostname "domain.name"] [uri "/install/Install.php"] [unique_id "XmqsbbtmQKi0jhF0e7gYzgAAAAU"]
[Thu Mar 12 16:41:05.135466 2020] [:error] [pid 13705] [client 165.x.x.x:43680] [client 165.x.x.x] ModSecurity: collections_remove_stale: Failed to access DBM file "/var/cpanel/secdatadir/yetiuser-ip": Permission denied [hostname "domain.name"] [uri "/install/Install.php"] [unique_id "XmqsbbtmQKi0jhF0e7gYzgAAAAU"]
```

**Comment by davide-alghi** [comment]
security note: please @ozinfotech, remember to change your DB and YF password because into your logs they're in clear

**Comment by ozinfotech** [comment]
> security note: please @ozinfotech, remember to change your DB and YF password because into your logs they're in clear

I had sanitized the passwords before I attached the files, but I'll change anyway since I still can't get it installed, even with ModSecurity turned off. I'll get some more logs today.

**Comment by ozinfotech** [comment]
This time around, after disabling ModSecurity, the Apache error logs were not updated with any errors. Same thing with the SQL logs.

Attached is another sanitized _system.log_.
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4340155/system.log)

With these errors, I'm wondering if it has something to do with the database since it never gets populated at all.

```
2020-03-16 19:54:02.7747 [info][yii\db\Connection::open] - Opening DB connection: mysql:host=localhost;dbname=db_yeti;port=3306
2020-03-16 19:54:03.4873 [info] - Cannot translate this: 'MySQL' for module 'Install', lang: en-US
2020-03-16 19:54:03.5049 [info] - Cannot translate this: 'mysql' for module 'ConfReport', lang: en-US
2020-03-16 19:54:03.5049 [info] - Cannot translate this: 'MariaDb' for module 'ConfReport', lang: en-US
2020-03-16 19:54:03.5049 [info] - Cannot translate this: '10.0.38' for module 'ConfReport', lang: en-US
```

And also attached is a new sanitized _error_log_.
[error_log](https://github.com/YetiForceCompany/YetiForceCRM/files/4340193/error_log.txt)

**Comment by mariuszkrzaczkowski** [comment]
strange that in logs you have global variables empty should be given in them
```
$_GET = []
$_POST = []
```
send us a phpinfo email (github@yetiforce.com)

**Comment by ozinfotech** [comment]
Attached is sanitized information. [info.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/4346193/info.pdf)

**Comment by ozinfotech** [comment]
Did you all have a chance to check this out?

**Comment by mariuszkrzaczkowski** [comment]
No configuration errors are visible, your administrator should take care of it or you can buy the support package and we will verify that.

**Comment by ozinfotech** [comment]
Got it resolved. Thanks!

**Comment by mariuszkrzaczkowski** [comment]
give details of the solution to your problem

**Comment by ozinfotech** [comment]
I did nothing as I was out of work for a couple weeks, but when I went to install today it went fine. 
I could tell it was going to be different when the page asking for the name of the company had a couple other fields it didn't have before. I wish I could say I did something on my end to make it work, but it appears that waiting for whatever reason did the trick.
