### ISSUE TITLE
[Question] need help setting the https vhost apache webserver

### ISSUE THREAD

**Issue by vickoza** [YetiForceCompany/YetiForceCRM#12661]
### Description

![image](https://user-images.githubusercontent.com/14866412/75922739-3db28080-5e29-11ea-9e41-47a1ea640d85.png)
none of the CSS or images or JavaScript is work is downloaded to my remote broswer. Only the php is loaded as an abstract webpage I this should be a setting with the Https on the aphache web server

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/75923380-3b6e1780-5e65-11ea-9a70-00f564951c48.jpg)

**Comment by vickoza** [comment]
I do not think this is a bug per say as I think this would work if I disable the https settings this look like a configuration issue possible dealing with https.

**Comment by mariuszkrzaczkowski** [comment]
No information about the environment and CRM version etc.

**Comment by vickoza** [comment]
environment OS FreeBSD
YetiForceCRM v5.2.145 - The best opensystem in the world

**Comment by rskrzypczak** [comment]
I think you have a problem with Content Security Policy directive.
Try to temporarily disable csp and see if it helps.
https://github.com/YetiForceCompany/YetiForceCRM/blob/bd1f8c43f1fe9a1cd0154a9f1b084d76bbde6f4e/config/Security.php#L123

**Comment by vickoza** [comment]
I tried this and it did not work. I think this might apache's https
I an using apache 2.4

**Comment by mariuszkrzaczkowski** [comment]
logs
