### ISSUE TITLE
[Question] How to add a new SMS provider in Yetiforce? I have added a new file in modules/SMSNotifier/providers/mySMSAPI.php, still it is not working.

### ISSUE THREAD

**Issue by ritesh9763** [YetiForceCompany/YetiForceCRM#12679]

**Comment by ritesh9763** [comment]
This is the SMS API we have got from our provider: https://my-sms-provider.com/API/sms-api.php?
auth=<AUTH KEY>&msisdn=<TO NUMBER>&senderid=<FROM>&message=<SMS CONTENT>

However, we are not able to integrate this API in the Yetiforce CRM. Kindly help.

**Comment by z0lo13** [comment]
1. PHP is server based language it is no way to access source code from the link.
2. You need to create a new class for your provider.
3. No information provided at all ( What provider, documentation, methods etc.)

Sample integartion:
https://github.com/YetiForceCompany/YetiForceCRM/pull/12504

**Comment by ritesh9763** [comment]
Hi, what additional information you require? Its a simple HTTP GET request that we need to call to send a sms. The URL is somewhat similar to this: https://my-sms-provider.com/API/sms-api.php?
auth=&msisdn=&senderid=&message=
Here msisdn parameter should contain the phone numbers'(comma separated) and message parameter should have the sms content. The auth & senderid paramters will have some fixed values.
My question was how to invoke this URL from the Yetiforce CRM's Mass SMS option. 
I guess, this is a very basic requirement for all SMS providers and it would be great if you can give a sample code on how to set this up.
