### ISSUE TITLE
[Question] Is there any source code for new module create?

### ISSUE THREAD

**Issue by A4kon** [YetiForceCompany/YetiForceCRM#12671]
Hello,
Is there any source code with start point guide, in which based i would be able to create my own module for YETI and add own relationship to it with other modules which are already provided by your company?
I know it is possible to integrate other apps with your system with API but i need to create my own module

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/76086025-8d24b800-5fb3-11ea-8095-33ae1c1de242.png)

https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List

**Comment by A4kon** [comment]
Yes, i saw that option, but it's not allowing to add events from outside of the system, because i'm would like to add integration with external services

**Comment by davide-alghi** [comment]
Hi @A4kon,
you've to develop an extension to do that
