### ISSUE TITLE
[bug] You don&#039;t have the permissions required to view/edit this record. Contact the administrator if you should have the permission to view it

### ISSUE THREAD

**Issue by snenko** [YetiForceCompany/YetiForceCRM#12676]
error when I try to view record: 
"have the permissions required to view/edit this record. Contact the administrator if you should have the permission to view it. "

### ❗️ Inform the community if you solve the problem
**I fount the reason why is "Permission denied".**
I think the problem when a role is saving several profiles ($profileActionPermission).

I separate profiles by functionality: knowledgebase and Passwords
And If "Passwords Profile" will be after knowledgebase so "Passwords Management" will be locked.

![image](https://user-images.githubusercontent.com/11363876/76154243-b80d2a00-60e1-11ea-8402-cef212f15432.png)

**The fast solution is**: combine all permission in one profile for one role.

**But I think this bug needs to be fixed in code(when the role is saving for users).**

**Comment by bpabiszczak** [comment]
Use one profile per role. The system allows you to add several roles, but we do not recommend doing this
