### ISSUE TITLE
[Question] [PL] Jak poprawnie dodać wydarzenie w kalendarzu, aby wydarzenie wyświetliło się u osób współdzielonych?

### ISSUE THREAD

**Issue by kominekjacek** [YetiForceCompany/YetiForceCRM#12678]
**Pytanie:** W jaki sposób można dodać osoby do wydarzenia w kalendarzu, aby tym osobom wyświetliło się to wydarzenie w kalendarzu?

**Przykład:** Jacek tworzy wydarzenie pt. Spotkanie1. Chce żeby w spotkaniu wziął udział Michał i Piotr. Michał i Piotr są użytkownikami CRM. W jaki sposób Jacek ma dodać Michała i Piotra do wydarzenia, aby informacja o Spotkanie1 pojawiła się w ich kalendarzach. 

Pomocny może okazać się screen z bieżącą konfiguracją:
![image](https://user-images.githubusercontent.com/61247039/76197202-00b10a00-61ec-11ea-806b-bdc9924eb74c.png)

![image](https://user-images.githubusercontent.com/61247039/76197260-1b837e80-61ec-11ea-9815-4e6bd33eb77b.png)

Środowisko: 
YetiForce | 5.2.0
Web server | Apache/2.4.29 (Ubuntu)
PHP | 7.2.27-6+ubuntu18.04.1+deb.sury.org+1
Browser : Chrome
Operating System | Linux crm 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64
Database | mysql \| 10.1.44 \| mysqlnd 5.0.12-dev

**Comment by bpabiszczak** [comment]
Ogólnie to im się pojawi :) ale nie w kalendarzu graficznym ale w widżetach na stronie głównej [sprawy bieżące i sprawy zaległe]. Planujemy to poprawić, aby był widoczne domyślnie również w kalendarzu graficznym.

**Comment by bpabiszczak** [comment]
Gotowe: https://github.com/YetiForceCompany/YetiForceCRM/commit/db426ebbcab3f7c287a6f202c29ee9873daa06bd
