### ISSUE TITLE
[bug] Buttons in alerts are not working

### ISSUE THREAD

**Issue by A4kon** [YetiForceCompany/YetiForceCRM#12670]
# 🐞 bug report

### ⁉️ Describe the bug

I've started to use your system recently and I've noticed strange behaviour. Mainly when I'm trying to close pop-up neither of buttons are working. I'm unable to close it.

### 🔥 How to trigger the error

1. Go to any module
2. Change any settings or add new data
3. Pop-up comes in
4. You can't close it

### 👎 Actual Behavior

Buttons at pop-up are not working
### 👍 Expected Behavior

Pop-up should close
### 📝 PHP/Apache/Nginx/Browser/CRM Logs
In my opinion is more front-end problem than backend problem so i think logs are unnecessary, also i noticed that there isn't any event handler to that buttons
[https://imgur.com/ZMJDMyM](url)
[https://imgur.com/N5icnuQ](url)
[https://imgur.com/s1LOaBi](url)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.1.0
| Web server (name and version)|		|
| PHP  |				7.1.33				|
| Browser (name and version)  | 	ANY 	|
| Operating System (name and version)  | 	WINDOWS 10 / SERVER-2012,	|
| Database (name and version) | 		|
| Service Pack version | 		|

### ❓ Additional context
Also I've no idea what is the use of button with play icon?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/76085146-c3f9ce80-5fb1-11ea-9f74-66b1bb807fd9.jpg)

**Comment by A4kon** [comment]
Updated content of issue

**Comment by mariuszkrzaczkowski** [comment]
check if the bug is in the stable and development version

**Comment by A4kon** [comment]
Bug is not existing on both of them, problem solved  by reinstalling yeti
