### ISSUE TITLE
[Question] cross-version YF extension installer

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#12687]
### Description
Hi all,
is there any way to create a unique YF extension installer for different YF version?

```<vtiger_version>``` tag into manifest doesn't allow to set a version range like 5.x.x, so it's needed produce 3 different installers:
```<vtiger_version>5.0.x</vtiger_version>```
```<vtiger_version>5.1.x</vtiger_version>```
```<vtiger_version>5.2.x</vtiger_version>```

... or am I missing something?

**Comment by mariuszkrzaczkowski** [comment]
5.x.x cannot be created
each version may be different

**Comment by davide-alghi** [comment]
thx
