### ISSUE TITLE
[bug] Workflow Scheduling Error for "Every 5 minutes" task

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#12680]
# 🐞 bug report
There are multiple workflow execution schedules available for workflows, one of them is 'Defined time intervals' which suppose to fire workflow within the given time ex (Every 5 minutes or every 1 hour).

However, the task itself is fired by cron "Workflow" which is recommended to be put for 15 minutes and if set to 15 minutes will never fire task with "Every 5 minutes" schedule.

Which makes "every 5 minutes" useless.

### ⁉️ Describe the bug

The task in not fired by schedule it set in workflow setting but by global cron parameter which is 15 minutes.

### 🔥 How to trigger the error

1. Go to Workflows
2. Create a task which will be fired every 5 minutes
3. Wait for first fire
4. Count time since first fire
5. Next fire will in 15 minutes as cron is running every 15 minutes

### 👎 Actual Behavior

Workflow fires every 15 minutes
### 👍 Expected Behavior

Workflow fires every 5 minutes
### 👷 Testing 

[79_workflow.xml.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/4309078/79_workflow.xml.zip)

- [✔️  ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [✔️ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by KatarzynaUlichnowska** [comment]
Hello,
here is @bpabiszczak's answer:
Where do we recommend to start workflow every 15 minutes? [Here](https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron) we recommend to run it e.g. every 5 min. 
From the business and logical perspective, you can run it as you like, you can even run every minute (there is even a built-in mechanism that can trigger it every second), so all you need to do is set the CRON properly.

Fix the configuration in CRON at the operating system (OS) level and the problem will disappear.

I don't see any bug here, possibly we can improve the description somewhere to make it easier to understand.

**Comment by z0lo13** [comment]
@KatarzynaUlichnowska @bpabiszczak 
you recommend it when editing workflow
attached is screeenshot from latest developer version
That is definitely misleading 
![Screenshot (1)](https://user-images.githubusercontent.com/23143958/77267539-50c2ae80-6c79-11ea-94c3-2fc9fbe017d9.png)

**Comment by s2b-git** [comment]
Facing similar issue in 6.3. "Execution schedule (defined time intervals)" > 5 min
Workflow in the yetiforce every one minute
System cron every one minute
Does last two causing conflict?
