### ISSUE TITLE
LBL_HANDLER_NOT_FOUND

### ISSUE THREAD

**Issue by JCNMedia** [YetiForceCompany/YetiForceCRM#12693]
I created a widget and made it mandetory. After saving i went to my main (home)page and it said: error: LBL_HANDLER_NOT_FOUND, with the options go back and home page.
I tried to go back to the widget configuration page, but i get the same error there.

Is there a way to undo this action of creating the widget?

**Comment by mariuszkrzaczkowski** [comment]
Logs 
![github](https://user-images.githubusercontent.com/10198654/76569626-ddb87b80-64b3-11ea-9ff3-a1024c20c538.jpg)
