### ISSUE TITLE
Mail scanner: loading folders keeps loading

### ISSUE THREAD

**Issue by JCNMedia** [YetiForceCompany/YetiForceCRM#12694]
Hello,

I created a mail scanner for a mailbox I succesfully opend inside yetiforce. I have to assign a folder to scan, when I click the folder icon the message: Loading folder list in progress, It may take a few minutes stays on the screens and no folders are displayed.

I waited up to 30 minutes to load. And i checked to see if the credantials where correct. The are, I can log in to the account in roundcube.

How can I setup the folder if yetiforce keeps looping like this?

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/12589#issuecomment-588174008
