### ISSUE TITLE
How to create new "Assigned To" fields and make changes

### ISSUE THREAD

**Issue by littledove22** [YetiForceCompany/YetiForceCRM#12701]
I am unable to locate the "Assigned To" field in the Users screen.  I also need to Edit what is displayed for existing users.

**Comment by littledove22** [comment]
Is anyone available to complete the settings for this software?  The documentation is lacking.  Maybe someone who knows Yetiforce could make a video how to navigate it.

**Comment by bpabiszczak** [comment]
Show where you want to make changes, and write what you want to change.
