### ISSUE TITLE
📣 YetiForce 5.3 is here! 🔥

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#12705]
The latest stable version of YetiForce CRM has just been released. **Version 5.3** brings a ton of improvements and new functionalities as an answer to continuously and gradually growing needs of the community. And speaking of the community, we would want to thank each and every single one of our community members for their time and effort. 

As usual, the complete list of changes will be posted on our official website in the [Developer Documentation](https://yetiforce.com/en/knowledge-base/documentation/developer-documentation) section. Below we summarize the most important changes in 5.3:
1. **Marketplace** - in 5.2 we launched a test version of the Marketplace, in 5.3 we have significantly improved the subscription mechanism and now we also offer new add-ins, currently you can purchase:
- **YetiForce Help** - a basic support service for YetiForce system 
- **YetiForce Development** - a dedicated support service for YetiForce system
- **YetiForce Hosting** - professional hosting for  YetiForce system
- **YetiForce Cloud**- a professional VPS for YetiForce system
- **YetiForce Branding** - the ability to disable the default YetiForce branding
- **YetiForce Password** -  the ability to verify if your password has leaked
- **YetiForce Map** - the ability to visualize data on the map, search addresses around the world and map routes. In the previous version, it was based on public servers while version 5.3 has the 
YetiForce server set as default (you can also use any other server). 
- **YetiForce Address Search** - the ability to search any address in the world.  In the previous version it was based on public servers while version 5.3 has the YetiForce server set as default (you can also use any other server). 
- **YetiForce Outlook Integration Panel (Beta)** - a modern plugin for Microsoft Outlook that allows loading the CRM system directly in the Outlook window, currently it is being tested.
2. **Chat** - we have significantly improved the chat and its basic mechanisms, so now chatting is more convenient and faster than before.
3. **Updates** - we have launched an update mechanism that monitors whether a new version has been released.
4. **GDPR consents**- two new modules that allow automatic collection of consents (e.g. via API).
5. **Color panel**- a new color panel that allows finding the right color more easily. 
6. **PDF** - expanded PDF functionality with new special functions.
7. **Emails** - improved an e-mail scanner mechanism. 
8. **Import** - the ability to import related records (using the relation field). 
9. **MFA** - added IP whitelist.
10. **Occurrences** - a new module and redesigning all graphic calendars into one central mechanism.
11. **Configuration** - extended server performance panel. 
12. Hundreds of other minor changes.

🎯**LINKS**

- GitHub - https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.3.0 
- SourceForge - https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/ 
- Softaculous - It usually takes a few days for the new version to be released by Softaculous.

**UPDATE & REQUIREMENTS**
We would like to remind everyone that updates should first be executed on a test version, and only then on the production version (you should always have a backup copy of your environments).
- The list of current web server requirements necessary for version 5.3 to work properly can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements)
- A detailed description of the installation process can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-update)

Have a great weekend! Stay at home and enjoy the new version 😉

**Comment by Giorgos-Hellene** [comment]
wow ! Very good news !!! keep on !

**Comment by vovpff** [comment]
```
YetiForceUpdate::createConfigFiles		|	12:26:14 -> 12:26:14	|	0 min.
YetiForceUpdate::update - 2020-03-16 12:26:15 | 1.55 min
YetiForceUpdate::postupdate		|	12:26:17
YetiForceUpdate::baseModuleTools		|	12:26:17
```
Is it update sucessfull?

**Comment by mariuszkrzaczkowski** [comment]
yes

**Comment by mariuszkrzaczkowski** [comment]
check the Importer.log file

**Comment by vovpff** [comment]
@mariuszkrzaczkowski 
```
-------------  2020-03-16 12:26:14 (1.54 min)   -------------
```

**Comment by mariuszkrzaczkowski** [comment]
?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski this is last string of `Importer.log`. There is no visible errors in log file. Is it ok?

**Comment by mariuszkrzaczkowski** [comment]
If no word error or warning is ok

**Comment by simple-AMS** [comment]
I backed up everything including database before upgrade. Upgrade finished but it messed up all my calendar entries, deleted all my email relations. I didn't test any further.

I then reverted back to 5.2.0 and re-imported my database and I'm back to where I was again. Guess I'll have to stay on 5.2 because my calendar and email relations are vital for my projects.

**Comment by vovpff** [comment]
@acsinsurancegroup looks like something unsuccessful. My calendar is here after upgrade

**Comment by liviubbo** [comment]
Hy all ! 

On my test clone :) i had some problems with update.
Update from 5.2 to version 19 , all good.
Update from 5.2 (v19) to 5.3 - Internal server error.
I also tried directly from 5.2 to 5.3 - Internal server error.
Enviroment - exactely the same.

**Comment by vovpff** [comment]
@liviubbo I also has `Internal server error` at the end of installation but logs inspection talks what update successful

**Comment by liviubbo** [comment]
@vovpff - Hy Vladimir ! Nice to /see/ u :) 
I dont understand

**Comment by mariuszkrzaczkowski** [comment]
If there is a problem with the update please open a new ticket with all data such as logs etc and we will check it.

**Comment by liviubbo** [comment]
ok. Thank you @mariuszkrzaczkowski

**Comment by vovpff** [comment]
@mariuszkrzaczkowski #12724

**Comment by mariuszkrzaczkowski** [comment]
ServicePack has been published with all fixes performed until today. 
You can download it from:
https://github.com/YetiForceCompany/YetiForceCRM/tree/5.3.0
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/Update%20packages/

or run an update from the CRM system, here is a link to the tutorial: [YetiForce CRM | System update - Tutorial](https://www.youtube.com/watch?v=zhh7fxZ293w&list=PLX0lktP3Kukg_Da-TaEBys-aON68Yy2vh&index=2)

**Comment by iq0099** [comment]
Its not working with the latest hosting PHP.

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/index.php on line 11

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/index.php on line 17

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/index.php on line 17

Parse error: syntax error, unexpected T_STRING in /home/index.php on line 17

**Comment by mariuszkrzaczkowski** [comment]
> Its not working with the latest hosting PHP.

???

> Warning: Unexpected character in input: '' (ASCII=92) state=1 in /home/index.php on line 11
> 
> Warning: Unexpected character in input: '' (ASCII=92) state=1 in /home/index.php on line 17
> 
> Warning: Unexpected character in input: '' (ASCII=92) state=1 in /home/index.php on line 17
> 
> Parse error: syntax error, unexpected T_STRING in /home/index.php on line 17

- show this line
- file encoding, 
- end of line character

**Comment by iq0099** [comment]
Encoding is UTF-8


<?php
/* +**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * Contributor(s): YetiForce.com
 * ********************************************************************************** */
\define('ROOT_DIRECTORY', __DIR__ !== DIRECTORY_SEPARATOR ? __DIR__ : '');

require __DIR__ . '/include/main/WebUI.php';
require __DIR__ . '/include/RequirementsValidation.php';

if ('OPTIONS' === $_SERVER['REQUEST_METHOD']) {
	\App\Headers::getInstance()->send();
	return;
}

if (!\App\Config::main('application_unique_key', false)) {
	header('location: install/Install.php');
} else {
	\App\Process::$startTime = microtime(true);
	\App\Process::$requestMode = 'WebUI';

	$webUI = new Vtiger_WebUI();
	$webUI->process(\App\Request::init());
}

**Comment by iq0099** [comment]
UTF-8

```php
<?php
/* +**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * Contributor(s): YetiForce.com
 * ********************************************************************************** */
\define('ROOT_DIRECTORY', __DIR__ !== DIRECTORY_SEPARATOR ? __DIR__ : '');

require __DIR__ . '/include/main/WebUI.php';
require __DIR__ . '/include/RequirementsValidation.php';

if ('OPTIONS' === $_SERVER['REQUEST_METHOD']) {
	\App\Headers::getInstance()->send();
	return;
}

if (!\App\Config::main('application_unique_key', false)) {
	header('location: install/Install.php');
} else {
	\App\Process::$startTime = microtime(true);
	\App\Process::$requestMode = 'WebUI';

	$webUI = new Vtiger_WebUI();
	$webUI->process(\App\Request::init());
}
```

**Comment by mariuszkrzaczkowski** [comment]
end of line character

**Comment by iq0099** [comment]
how to show this?  I don't see it?

**Comment by mariuszkrzaczkowski** [comment]
e.g. Notepad ++
![image](https://user-images.githubusercontent.com/10198654/77298534-5b1d9080-6ceb-11ea-91de-2d6fa4ad3e2a.png)

**Comment by iq0099** [comment]
On my Windows its showing Unix LF

**Comment by vovpff** [comment]
@iq0099 
click this button

![image](https://user-images.githubusercontent.com/8545791/77299369-67124e00-6cfd-11ea-80fa-8229cad1929b.png)

You will see ends of line in the file

![image](https://user-images.githubusercontent.com/8545791/77299433-7c877800-6cfd-11ea-92a2-a1f0f67a412c.png)

**Comment by iq0099** [comment]
![2020-03-23_11-58-50](https://user-images.githubusercontent.com/6355502/77299648-da1bc480-6cfd-11ea-9cb6-0439e0baa008.jpg)

**Comment by iq0099** [comment]
But I'm editting the file inside the hostin using the built-in editor 
https://github.com/ajaxorg/ace/wiki

**Comment by iq0099** [comment]
Do you need more information from me?

**Comment by iq0099** [comment]
Please any updates?

**Comment by bpabiszczak** [comment]
@iq0099 
problem = issue

**Comment by DataBound** [comment]
This update has been a small nightmare. It broke on many different occasions due to things I can't wrap my head arround.

It started with a SQL-Error:

`Base table or view not found: 1146 Table 'yeti.vtiger_priority' doesn't exist Failed to prepare SQL: SELECT * FROM `vtiger_priority` ORDER BY `sortorderid` `

Then I got this:
![image](https://user-images.githubusercontent.com/19411972/85868266-570d7d00-b7ca-11ea-9ac1-fe2c79598985.png)

This error could be resolved by adding:

`public static $isCustomerBrandingActive = false;` in `config/Components` (on the current yeti running on the server)

Ok. I added a fresh and empty vtiger_priority and tried again.

`CREATE TABLE `vtiger_priority` (   `priorityid` int(10) NOT NULL AUTO_INCREMENT,   `priority` varchar(200) NOT NULL,   `sortorderid` int(10) NOT NULL DEFAULT '0',   `presence` int(1) NOT NULL DEFAULT '1',   PRIMARY KEY (`priorityid`),   UNIQUE KEY `priority_priority_idx` (`priority`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

Same error. Then I found this line:

`$this->importer->dropTable(['vtiger_durationhrs', 'vtiger_durationmins', 'vtiger_leadstage', 'vtiger_mail_accounts', 'vtiger_opportunitystage', 'vtiger_priority']);`

in init.php (update package). So I went and removed that and now it looks like 

`$this->importer->dropTable(['vtiger_durationhrs', 'vtiger_durationmins', 'vtiger_leadstage', 'vtiger_mail_accounts', 'vtiger_opportunitystage']);`

Zipped the contents again and another try.

![image](https://user-images.githubusercontent.com/19411972/85868911-372a8900-b7cb-11ea-9f45-71e2ee371e61.png)

It says: `Failure. Module doesn't exist in default language de-DE`

So I went over to https://github.com/YetiForceCompany/YetiForceCRMLanguages and downloaded the whole thing.
Look for your language, de-DE in my case, and copy past it to the folder `updates\files\languages` (Update package).

Zipping it. Next try

Same error, changing default language of the running system to english. Same error but now it says. Module doesnt exist in `en-US`.

So far im frustrated and applied a backup. Might try again later

**Comment by KatarzynaUlichnowska** [comment]
@DataBound please create a new issue.

**Comment by mwmentor** [comment]
Hi there:  I have a dev environment running 4.4 - I would like to upgrade it to 5.3.  I see that the upgrades are for 5.2 to 5.3.  Is there a repo that I could use to achieve this objective, or should I just start again?

Thanks.
-Michael

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/UpdatePackages
or
https://github.com/YetiForceCompany/YetiForceCRM/releases
![image](https://user-images.githubusercontent.com/10198654/88666118-e9fa4980-d0df-11ea-9a60-fde0fc9179c8.png)

**Comment by mwmentor** [comment]
> https://github.com/YetiForceCompany/YetiForceCRM/releases

Hi Marius: Thanks so much. -M 👍
