### ISSUE TITLE
[bug] "Last modified by" is not shown for "Services"

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12707]
# 🐞 bug report

### ⁉️ Describe the bug

"Edit fields" for "Services" includes field "Last modified by"
![src](https://user-images.githubusercontent.com/10230144/76684763-f25d5680-660e-11ea-8f32-93a7f4ff23cf.png)

When displaying a service in "Details", field "Last modified by" is not shown
![dst](https://user-images.githubusercontent.com/10230144/76684766-f6897400-660e-11ea-9d90-b9f31306b0f5.png)

### 🔥 How to trigger the error

1. Ensure that field "Last modified by" is part of the "Services" view
2. Display a service

### 👎 Actual Behavior

Field is not shown
### 👍 Expected Behavior

Field should be shown
### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

See above

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.3.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by diderich** [comment]
In the database the "displaytype" is set to 3 rather than 2. Updating it to 2 shows the field.

**Comment by adudekyeti** [comment]
It's not a bug it's a feature ;)
But for this field we will fix it.

You can easly manage visibility of fields in "Edit field".
**1. Firstly you need to click green button here:**
![image](https://user-images.githubusercontent.com/39482453/93591661-0ebcc000-f9b1-11ea-9435-2f6fd94fc873.png)

**2. Then you have a modal window with option "Field type"**
![image](https://user-images.githubusercontent.com/39482453/93591709-24ca8080-f9b1-11ea-8241-f6487819295f.png)

**3. Here you can select where this field can be shown:**
![image](https://user-images.githubusercontent.com/39482453/93591726-301dac00-f9b1-11ea-8947-090b3af33e16.png)
