### ISSUE TITLE
[Question] Modules references in process field

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12718]
### Description

Is there a possibility to disable modules (selected by drop-down) in a process field, as shown in the figure? I would, for example, like to remove Campaigns, from the list in the Track Control module.

![q](https://user-images.githubusercontent.com/10230144/76776600-40a55d80-67a7-11ea-91e5-b0eeeef9ce64.png)

**Comment by vovpff** [comment]
Manually in database

**Comment by diderich** [comment]
Could you point me to the appropriate tables? I have a hard time identifying that information in the database.

**Comment by vovpff** [comment]
@diderich really I don't remember what tables you need to modify. Pls spend some tame for analyzing

**Comment by diderich** [comment]
It seems that this data is stored in the table "vtiger_fieldmodulerel", but only for fields of uitype 10. I am unable to find where the relationship is stored for the fields of uitype 66, 67 and 68 in the OSSTimeControl module (see figure). Any idea where to look?

**Comment by blu-IT** [comment]
@diderich Have you already checked in `Software configuration -> Standard modules -> Edit fields ` ?

**Comment by rskrzypczak** [comment]
These types of relational fields are based on a hierarchy.
The module information is in the file, not in the database.
https://github.com/YetiForceCompany/YetiForceCRM/blob/3e4974bd70d124944a41cc55c73d099bb7e765e4/modules/Vtiger/uitypes/ReferenceProcess.php#L17
I recommend caution in modifying these relationships :)
