### ISSUE TITLE
[Question] Changing order of calendar fields

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12717]
### Description

Fields in other modules can be re-ordered. This seems not possible for calendar entries. Is there a possibility to re-order fields for entering a calendar entry?

**Comment by vovpff** [comment]
Put Calendar (or Event) to page adress instead other module name

**Comment by diderich** [comment]
When calling that page, I cannot move fields (see below). Moving is disabled!

![q](https://user-images.githubusercontent.com/10230144/76832534-c2d66600-6829-11ea-8b79-c8c36d7a1a02.png)

**Comment by vovpff** [comment]
I has checked. Yes. This is blocked. :(

I think you can change fields order in database but this actions can crush your system

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/12864
