### ISSUE TITLE
[PL] Loader zawiesza się - roczny wymiar urlopu

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1271]
![76](https://cloud.githubusercontent.com/assets/11139594/8451253/4168ff36-1fe2-11e5-91dc-664c20ead1a7.png)
Kadry>Roczny wymiar urlopu>zaznaczyć pracownika>przycisk AKCJE>Masowa edycja>
1,2 i 3 zakładka informacje ogólne>wybieram rok i przycisk zapisz

https://gitdeveloper.yetiforce.com/index.php?module=HolidaysEntitlement&parent=76&page=1&view=List&viewname=72&orderby=holidaysentitlement_year&sortorder=ASC&search_params=%5B%5B%5D%5D

**Comment by rskrzypczak** [comment]
Błąd nie występuję w aktualnej wersji
https://gitdeveloper.yetiforce.com/index.php?module=HolidaysEntitlement&parent=76&page=1&view=List&viewname=72&orderby=holidaysentitlement_year&sortorder=ASC&search_params=%5B%5B%5D%5D
