### ISSUE TITLE
[Question] How to add "Process" and/or "Company" fields

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12715]
### Description

How can I add a "Process" and "Company" field as found in the "Time Control" module to another module?

![q](https://user-images.githubusercontent.com/10230144/76772415-236d9080-67a1-11ea-96d4-a129f8a58044.png)

**Comment by vovpff** [comment]
This is just 1:M relation but you need to pick more than one module when add this field

**Comment by diderich** [comment]
Thanks a lot.
