### ISSUE TITLE
[Question] Role allow to assign record issues

### ISSUE THREAD

**Issue by JasonChau1227** [YetiForceCompany/YetiForceCRM#12719]
I have set the role can assign record to users having same role or subordinate role but it comes out the role can assign to all users. Any idea why it happens

**Comment by JasonChau1227** [comment]
Anyone has any idea?

**Comment by bpabiszczak** [comment]
A step-by-step description of what you are doing and what is wrong.

**Comment by KatarzynaUlichnowska** [comment]
Unfortunately, we requested a more detailed description over 3 months ago and you haven't provided it, so I'm closing the issue.
