### ISSUE TITLE
[PL][Question] Liczba rekordów powiązanych

### ISSUE THREAD

**Issue by IgorRSU** [YetiForceCompany/YetiForceCRM#12723]
Witam, czy jest możliwość pobrania aktualnej dla danego rekordu wartości 	'countRelated' i przeniesienie jej do pewnego pola? 
![screen](https://user-images.githubusercontent.com/50998347/76849961-b01e5a00-6846-11ea-94ed-67362fce245e.png)
Przykład na zdjęciu - chodzi mi o jedynkę nad "Dokumenty". Rozumiem, że przeniosę wartość za pomocą Wyzwalacza, tylko nie bardzo rozumiem, co mam przenieść.
Dziękuję

**Comment by bpabiszczak** [comment]
ale po co? np.: aby na liście wykazać te rekordy, które nie mają np. żadnych dokumentów powiązanych?

**Comment by IgorRSU** [comment]
Mam własny moduł Mieszkania, w którym są rekordy np. A, B, C. Każdy kontakt jest przydzielony do pewnego mieszkania. Jak wejdę w mieszkanie A, to mam tam pole Liczba miejsc ogółem oraz liczba miejsc dostępnych. Chcę automatycznie wyliczyć Liczbę miejsc dostępnych=liczba miejsc ogólem minus ilość kontaktów, przydzielonych do danego rekordu.

**Comment by bpabiszczak** [comment]
Musi to zrobić programista. U nas jest to usługa odpłatna.
