### ISSUE TITLE
Cron issue after updating to 5.3 [bug] 

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#12729]
Hello all,

CRON is not finishing tasks after updating to 5.3. On 5.2 was working without problems.
I would have posted the logs but i dont know were to find them (for cron)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/76954533-c55fbb00-6910-11ea-9ce1-ecf5bca917ad.jpg)

**Comment by liviubbo** [comment]
Yes ! Thank you ! I have managed to solve it. It was my bad. Thank you anyway. Sorry for opening the issue without details.

**Comment by elvissaba** [comment]
How did you solved it? I have still same issue. Cron in Verson 5.2 works fine. After update to version 5.3 cron tesks are not executed.

**Comment by elvissaba** [comment]
> 
> 
> Yes ! Thank you ! I have managed to solve it. It was my bad. Thank you anyway. Sorry for opening the issue without details.

How did you solved it? I have still same issue. Cron in Verson 5.2 works fine. After update to version 5.3 cron tesks are not executed.

**Comment by rskrzypczak** [comment]
Open cron/cron.sh file in n++, and change EOL. You probably have CR LF.
![image](https://user-images.githubusercontent.com/10221999/78102738-55aaff00-73eb-11ea-9e88-407d212fab02.png)

**Comment by liviubbo** [comment]
@elvissaba - I was on a test website and i did not had any CRON working on server side. So, bassicaly, the CRON worked but i did not had a command for it on the server.

**Comment by elvissaba** [comment]
> 
> 
> Open cron/cron.sh file in n++, and change EOL. You probably have CR LF.
> ![image](https://user-images.githubusercontent.com/10221999/78102738-55aaff00-73eb-11ea-9e88-407d212fab02.png)

The problem was in CRON.sh, thank you Radoslaw. After the upgrade, custom PHP path for LSPHP (Litespeed) was deleted.
