### ISSUE TITLE
[PL] Nazwa na str. Głównej

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#1272]
nazwa jest w pionie
https://gitdeveloper.yetiforce.com/index.php?module=Home&view=DashBoard
![77](https://cloud.githubusercontent.com/assets/11139594/8451573/894d7640-1fe4-11e5-9a5c-661a89564aa7.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/4e7a9cd4ef6488c868b62f2964213238555f0ec3
