### ISSUE TITLE
[bug] Routing / Driving directions not working. And how to fix it.

### ISSUE THREAD

**Issue by kcrudup** [YetiForceCompany/YetiForceCRM#12726]
Routing directions does not work

1. Go to: Companies and Contacts -> Leads -> List

2. Select two leads with addresses. 

3. Click on the World icon. (top right hand corner)

4. You should see a map with the two contacts on it.

5. Click one address as the Start

6. Click the other and set as End

7. Click Set Route

Map will hang (Unless none of your coordinates contain a negative number)

### 👍 Expected Behavior

A map drawn with the directions and a driving list written on the bottom right. 

### ❗️ Inform the community if you solve the problem

It seems if the map coordinates contain a negative number the call to modules/OpenStreetMap/actions/GetRoute.php will fail with a 406 error. You can use F12 in firefox before clicking on the Set Route button to see the error.

The program is purifying the coordinate values from the map using the "Version"  type value which apparently will reject negative numbers, causing the call to fail.

A coordinate of -80.1250568 will fail, but it is a valid coordinate.

Ex. $ilon = $request->getByType('ilon', 'Version');

I just changes ALL the "Versions" in that program to "Double"

$ilon = $request->getByType('ilon', 'Double');

That fixed the problem.

A LITTLE DETAIL ON THE YETI 5.3 MAPPING AND GETTING IT WORKING

Get an free api key at https://openrouteservice.org/dev/#/signup if you want. You dont need one unless you want to have them as a tile and routing server choice.

See their notes in Software configuration > Integration > Map > System settings

Here are some that are actually working. You will have to edit the PHP files as per their directions. Dont replace the Yeti servers in the code, add new ones to the list. They have good examples for non-coders. These are only the values used, you have to put it in the correct PHP array syntax.

For the tile server: 

openrouteservice - https://api.openrouteservice.org/mapsurfer/{z}/{x}/{y}.png?api_key=YourApiKey
OpenStreetMap - https://tile.openstreetmap.org/{z}/{x}/{y}.png

For the coordinate server:

Nominatim | https://nominatim.openstreetmap.org

For the routing server:

Dont even use YOURS its DEAD and not working.

It seems Yeti is using openrouteserver V1 api. Here in the USA currently at this time their routing server is timing out. You can incorporate openrouteserver directly without going thru Yeti by editing 
/app/Map/Routing/YetiForce.php and changing

https://osm-route.yetiforce.eu/ors/directions?

to

https://api.openrouteservice.org/directions?api_key=YourApiKey&

It is already setup to handle the openrouteservice API

SIDE NOTE:
In certain locations, such as here in the USA if you have private communities that are not mapped, the route mapping may fail for that location. For example if you cant see a road when you drop the little guy for street view in google maps at one of your coordinates.

**Comment by mariuszkrzaczkowski** [comment]
The bug does not exist in the current version, it has been fixed in 6.1.0
