### ISSUE TITLE
[bug] Sorting lists, e.g., Services, does not work

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12725]
# 🐞 bug report

### ⁉️ Describe the bug

When clicking on the column/field in a List, the list is not sorted.

![sort](https://user-images.githubusercontent.com/10230144/76879524-a876a980-6876-11ea-8acf-1ff2bcc19786.png)

### 🔥 How to trigger the error

1. Select a module, e.g., Services
2. Click on the title of one of the columns to sort it

### 👎 Actual Behavior

List is not sorted correctly
### 👍 Expected Behavior

List is sorted correctly
### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.3.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by davide-alghi** [comment]
I can confirm it. It's a regression: on 5.2 it works.
it seems bounded to Products and Services modules

**Comment by vovpff** [comment]
I can confirm it too!

**Comment by mariuszkrzaczkowski** [comment]
the patch has been published in [5.3.0_ServicePack_v1.zip](https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.3.0/5.3.0_ServicePack_v1.zip)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski looks like issue solved.

**Comment by allyh12** [comment]
I have the same problem with V5.3 service pack V1.

Need to reinstall?

**Comment by vovpff** [comment]
@allisonho browser cache cleaned?
