### ISSUE TITLE
Internal Server Error update 5.3 [bug] 

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#12728]
Hello,

I have created a clone to prepare the update as the first time i have got Internal Server Error.
I have attached an image with system config.
Can you please tell me if something screws the update ? 
Thank you
![yetiforce_settings](https://user-images.githubusercontent.com/42461923/76947036-50d34f00-6905-11ea-818a-08dc67634b54.png)

**Comment by vovpff** [comment]
@liviubbo my fault was solved by temporary increasing PHP script execution time

**Comment by liviubbo** [comment]
@vovpff  - Thank you Vladimir. I have increased script execution, as suggested and worked. Thank you !!!!!! :)

**Comment by vovpff** [comment]
@liviubbo tune your server configuration to make it with minimal amount of red rows

**Comment by liviubbo** [comment]
@vovpff  - Yes, normally i would do that. Problem is that i have about 30GB of data, and i am afraid that if i change anything, i will lose everything. I will try to change in a clone and see.
