### ISSUE TITLE
[bug] Widgets are folded when Summary tab opened when Comment widget active

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#12732]
# 🐞 bug report

### ⁉️ Describe the bug

Also I checked what part of modules has all widget folded at summary tab:
![image](https://user-images.githubusercontent.com/8545791/76965662-bdfed880-6935-11ea-9718-16365a413972.png)
![image](https://user-images.githubusercontent.com/8545791/76965714-d4a52f80-6935-11ea-86f4-6ce9a7a7edd0.png)
But in quotes all widgets are open
![image](https://user-images.githubusercontent.com/8545791/76965872-2057d900-6936-11ea-85e4-938467fe57aa.png)

### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.3.0 SP1
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

![ConfReport_200317_2](https://user-images.githubusercontent.com/8545791/76965981-4e3d1d80-6936-11ea-96e0-a537e80474fc.png)

**Comment by vovpff** [comment]
Comments widget crush autoopening

error from console
```
Uncaught ReferenceError: Tribute is not defined
    at Completions.register (Fields.js:850)
    at new Completions (Fields.js:751)
    at c.registerCommentEventsInDetail (Detail.js:2500)
    at Object.<anonymous> (Detail.js:296)
    at Object.dispatch (jquery.min.js?s=1584448268:2)
    at Object.v.handle (jquery.min.js?s=1584448268:2)
    at Object.trigger (jquery.min.js?s=1584448268:2)
    at Object.<anonymous> (jquery.min.js?s=1584448268:2)
    at Function.each (jquery.min.js?s=1584448268:2)
    at k.fn.init.each (jquery.min.js?s=1584448268:2)
```

**Comment by vovpff** [comment]
This buggy comments widgets blocks every popup. For example Knowledge base preview button not working on Summary tab if comments active

**Comment by vovpff** [comment]
I can confirm what this bug available on gitstable
@mariuszkrzaczkowski 
Pls take a look

**Comment by mariuszkrzaczkowski** [comment]
This is some error in the tributejs min file
the easiest way to fix this is to delete this file: public_html/libraries/tributejs/dist/tribute.min.js

**Comment by zazy** [comment]
I also struggled with this bug and found the problem in tribute.min.js. Instead of deleting the file I simply copied tribute.js over tribute.min.js and all works fine now.

**Comment by mariuszkrzaczkowski** [comment]
This can also be done

**Comment by Gil37** [comment]
How exactly should I delete this tributemin file? I am sorry but I have little knowledge on this subject.

**Comment by vovpff** [comment]
@Gil37 just rename tribute.min.js to tribute.min.js_
