### ISSUE TITLE
[bug] Can not update from 5,2 v19 to 5.3

### ISSUE THREAD

**Issue by elvissaba** [YetiForceCompany/YetiForceCRM#12735]
# 🐞 bug report

### ⁉️ Describe the bug
I can not update form 5.2 v19 to 5.3

### 🔥 How to trigger the error
Followed steps for update and got error bellow:
![image](https://user-images.githubusercontent.com/20727670/76996341-a0d80300-6951-11ea-8ed4-8fc5d0aee7af.png)

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
![image](https://user-images.githubusercontent.com/20727670/76996068-20190700-6951-11ea-925a-f9c6fcefaca5.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.2 v19
| Web server (name and version)|		litespeed|
| PHP  |						7.3		|
| Browser (name and version)  | 		Firefox latest|
| Operating System (name and version)  | 		CenOS 7|
| Database (name and version) | 		Mariadb latest stable|
| Service Pack version | 		19|

**Comment by vovpff** [comment]
I has the same bug when update. But I has used zip file for update.

**Comment by kcrudup** [comment]
Go here and use zip file:

https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%205.x.x/5.2.0_to_5.3.0/zip

**Comment by mariuszkrzaczkowski** [comment]
@vovpff @elvissaba  Show what the variable $toInstallcontains
https://github.com/YetiForceCompany/YetiForceCRM/blob/fe9436c94c53842b91d5d6b52785d6a50be40f8b/modules/Settings/Updates/views/Index.php#L15

**Comment by lpolitowski** [comment]
I have the same error on Debian 10. $toInstall looks like yours:

`$ less /var/www/html/yetiforce/modules/Settings/Updates/views/Index.php | grep toInstall
                $toInstall = \App\YetiForce\Updater::getToInstall();`

**Comment by mariuszkrzaczkowski** [comment]
show logs

**Comment by lpolitowski** [comment]
Updated system, installed zip, installed SP1, it seems to work, testing now. Sorry for confusion.

**Comment by vovpff** [comment]
```
Argument 1 passed to App\YetiForce\Updater::download() must be of the type array, null given, called in /home/etwh/etwh/modules/Settings/Updates/views/Index.php on line 18
```

**Comment by mariuszkrzaczkowski** [comment]
CRM logs ??
there may be a problem with communication with the server

**Comment by apcloic** [comment]
@mariuszkrzaczkowski 
Same issue for me so I don't think it's a simple communication issue with the server.
`Argument 1 passed to App\YetiForce\Updater::download() must be of the type array, null given, called in /var/www/html/yfcrmdev/modules/Settings/Updates/views/Index.php on line 18`
Like @vovpff, I had to use the zip.

**Comment by mariuszkrzaczkowski** [comment]
@vovpff @apcloic make these changes and show what the file is created

```php
class Settings_Updates_Index_View extends Settings_Vtiger_Index_View
{
	public function process(App\Request $request)
	{
		$viewer = $this->getViewer($request);
		$qualifiedModuleName = $request->getModule(false);
		$toInstall = \App\YetiForce\Updater::getToInstall();
		if (!$request->isEmpty('download')) {
			$key = array_search($request->getByType('download', 'Alnum'), array_column($toInstall, 'hash'));
			file_put_contents(ROOT_DIRECTORY . '/UpdatesDownload.log', print_r([
				'$request(download)' => $request->getByType('download', 'Alnum'),
				'$key' => $key,
				'$toInstall' => $toInstall,
			], true), FILE_APPEND);
		}
		$viewer->assign('TO_INSTALL', $toInstall);
		$viewer->assign('INSTALLED', Settings_Updates_Module_Model::getUpdates());
		$viewer->view('Index.tpl', $qualifiedModuleName);
	}
}
```

**Comment by vovpff** [comment]
@mariuszkrzaczkowski what file should be modified?

**Comment by mariuszkrzaczkowski** [comment]
modules\Settings\Updates\views\Index.php

**Comment by blu-IT** [comment]
I have this problem too:

`Argument 1 passed to App\YetiForce\Updater::download() must be of the type array, null given, called in /var/www/yetiforce/modules/Settings/Updates/views/Index.php on line 18`

Which logs are needed for further help? 

Thanks!

**Comment by blu-IT** [comment]
And when I try to use the ZIP-File, I get this error:

`Invalid request - Response For Illegal Access`

**Comment by elvissaba** [comment]
I updated manualy.

**Comment by blu-IT** [comment]
@elvissaba 

Hi, what does that mean? Is it like a "normal" full installation? 

Thanks!

**Comment by blu-IT** [comment]
OK, just to give a hint/update for people with the same problems mentioned here:

I took my php.ini form a fresh installation (see #13064) and copied it to this system. After that I could update Yetiforce with the ZIP-Package to V. 5.3 and then via internal yetiforce tools to 5.3 SP4.

**Comment by kofe1** [comment]
didn't work for me
![lbl_download_package_error](https://user-images.githubusercontent.com/67367613/85539567-46b4a100-b616-11ea-977b-1c270a8e2527.png)

upgrade form file
![upgrade_from_file](https://user-images.githubusercontent.com/67367613/85539624-56cc8080-b616-11ea-8463-91424b558bc6.png)
![upgrade_packages](https://user-images.githubusercontent.com/67367613/85539653-6055e880-b616-11ea-9a4f-e5bd2aa6a472.png)
![logs](https://user-images.githubusercontent.com/67367613/85539682-68ae2380-b616-11ea-984f-fbc9899b4637.png)
![yetiforce_settings](https://user-images.githubusercontent.com/67367613/85539691-6b107d80-b616-11ea-9a98-b49df2c2c728.png)

**Comment by manwenick** [comment]
> 
> 
> @vovpff @apcloic make these changes and show what the file is created
> 
> ```
> class Settings_Updates_Index_View extends Settings_Vtiger_Index_View
> {
> 	public function process(App\Request $request)
> 	{
> 		$viewer = $this->getViewer($request);
> 		$qualifiedModuleName = $request->getModule(false);
> 		$toInstall = \App\YetiForce\Updater::getToInstall();
> 		if (!$request->isEmpty('download')) {
> 			$key = array_search($request->getByType('download', 'Alnum'), array_column($toInstall, 'hash'));
> 			file_put_contents(ROOT_DIRECTORY . '/UpdatesDownload.log', print_r([
> 				'$request(download)' => $request->getByType('download', 'Alnum'),
> 				'$key' => $key,
> 				'$toInstall' => $toInstall,
> 			], true), FILE_APPEND);
> 		}
> 		$viewer->assign('TO_INSTALL', $toInstall);
> 		$viewer->assign('INSTALLED', Settings_Updates_Module_Model::getUpdates());
> 		$viewer->view('Index.tpl', $qualifiedModuleName);
> 	}
> }
> ```
@mariuszkrzaczkowski 
I changed the code you've posted. 
After I press the button LBL_DONWLOAD_PACKAGE nothing happens. The current window only updates it self and nothing happens

**Comment by acoolov** [comment]
I got the same error on my 5.3 version. Did anyone find a solution? I can't update to version 6. It gives me this error

Argument 1 passed to App\YetiForce\Updater::download() must be of the type array, null given, called in /home/etwh/etwh/modules/Settings/Updates/views/Index.php on line 18

When I replace the code which was provided by @mariuszkrzaczkowski and click download package, nothing happens and the page just refreshes. 

How can I update from 5.3 to 6? Please help.

**Comment by mariuszkrzaczkowski** [comment]
Upload the update package manually
https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%205.x.x/5.3.0_to_6.0.0/zip

**Comment by acoolov** [comment]
When I upload the package manually, it tries to upload it, spins, and then just goes to nowhere and says this page cannot be displayed. What should I do?

**Comment by mariuszkrzaczkowski** [comment]
start with full logs

**Comment by acoolov** [comment]
So sorry for being ignorant, where should I get the logs for you?

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging
![github](https://user-images.githubusercontent.com/10198654/136330834-2d089a62-24e5-4324-8831-09be6fe401b5.jpg)
