### ISSUE TITLE
[bug] Summary view including comments opens with all groups closed

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12731]
# 🐞 bug report

### ⁉️ Describe the bug

When displaying a summary page of a module record, the groups are all closed, although the indicators show they are open.

Actual screen when opening https://gitstable.yetiforce.com/index.php?module=Leads&view=Detail&record=272
![aaa](https://user-images.githubusercontent.com/10230144/76959821-a8c88080-691a-11ea-80d8-45233f545e73.png)

Screen when manually clicking on open groups icon for https://gitstable.yetiforce.com/index.php?module=Leads&view=Detail&record=272
![eeee](https://user-images.githubusercontent.com/10230144/76959842-b4b44280-691a-11ea-8408-c9953155cac1.png)

Screen when removing Comments group and opening https://gitstable.yetiforce.com/index.php?module=Leads&view=Detail&record=272
![wwww](https://user-images.githubusercontent.com/10230144/76959878-c0a00480-691a-11ea-98fc-49fede417814.png)

It works on the developer version (which commit did solve the problem?
![dev](https://user-images.githubusercontent.com/10230144/76960083-0d83db00-691b-11ea-95d3-b8a48c04aca9.png)

### 🔥 How to trigger the error

See screens above

### 👷 Testing 

- [ x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.3.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by vovpff** [comment]
Can confirm what my 5.3 PS1 has this bug.
Comment widget crush all other widgets.

#12732 

error from console

```
Uncaught ReferenceError: Tribute is not defined
    at Completions.register (Fields.js:850)
    at new Completions (Fields.js:751)
    at c.registerCommentEventsInDetail (Detail.js:2500)
    at Object.<anonymous> (Detail.js:296)
    at Object.dispatch (jquery.min.js?s=1584448268:2)
    at Object.v.handle (jquery.min.js?s=1584448268:2)
    at Object.trigger (jquery.min.js?s=1584448268:2)
    at Object.<anonymous> (jquery.min.js?s=1584448268:2)
    at Function.each (jquery.min.js?s=1584448268:2)
    at k.fn.init.each (jquery.min.js?s=1584448268:2)
```

**Comment by vovpff** [comment]
@areksolek what about this #12732

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/12732#issuecomment-601754886

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.3.0/5.3.0_ServicePack_v2.zip
