### ISSUE TITLE
[Question] Invoicing

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12734]
### Description

I have created a "Sales Invoice". Now the account has paid that invoice, but the invoice does not have any state "Booked" or "Paid". How do I tell the system that a sales invoice has been paid and (how) does the system update (or not update) the balance field associated with the Account.

**Comment by diderich** [comment]
Or is "Payments In" the only way to manage the balance of an Account. In that case, how can I see if an invoice has been paid, as "Payments In" has no relationship of "Sales Invoices"?

**Comment by diderich** [comment]
Or is actually the "Sales Order" an invoice from a conceptual point of view, that is, registering a "Payment In" sets the "Sales Order (rather than the Sales Invoice) to paid and updates the account? In that case, what is the role of the "Sales Invoice"?

**Comment by davide-alghi** [comment]
> Or is "Payments In" the only way to manage the balance of an Account. In that case, how can I see if an invoice has been paid, as "Payments In" has no relationship of "Sales Invoices"?

please, look better in **Payments In**

**Comment by diderich** [comment]
Sorry, missed that.
