### ISSUE TITLE
Font number Widget

### ISSUE THREAD

**Issue by inser2** [YetiForceCompany/YetiForceCRM#12738]
I would like to change the font size, they could tell me where I have to modify it and why the number looks very small.
![clase numero](https://user-images.githubusercontent.com/48966411/77097724-86fdf500-6a11-11ea-84e4-a9d3a0d31d4f.png)

**Comment by adudekyeti** [comment]
Hi,
If you want to change font size in Chart widget you need to modify this file: layouts\basic\modules\Vtiger\resources\dashboards\Widget.js
You need to change this parameters values: "size:".
