### ISSUE TITLE
Newbie Trying to create an opportunities filter and widget

### ISSUE THREAD

**Issue by barrykirk** [YetiForceCompany/YetiForceCRM#12733]
Testing Yeti crm v 5.20 
I manage to create a filter for opportunities
I am trying to get a widget for sales opportunities per month.
I try to add a widget, but cannot add a filter.

Can you please help?

**Comment by vovpff** [comment]
I think your filter should be with activated List in Metrics option

**Comment by konadrian** [comment]
As @vovpff said, check this if you have this option is selected
![image](https://user-images.githubusercontent.com/3193498/77535036-27cd3400-6e9a-11ea-8736-542f585dc2c7.png)
