### ISSUE TITLE
[Question] 1:M relations 

### ISSUE THREAD

**Issue by zazy** [YetiForceCompany/YetiForceCRM#12741]
Hello everybody, I'm struggling trying to implement a 1:M relation. 
Suppose I have two modules (this is only an axample to explain my problem): _Car_ and _Parking_. There is a 1:M relation between Car and Parking so that each Car can be in one and only one Parking at a time. Added a 1:M relation with a field in Car module called "Parked in" where I can choose the Parking record. After creating the Car record and assigning the Parking related record, if I go to the Car record dateil view I can see where the car is Parked, but if I go to Parking record I can't see all cars parked there. 
Is there a way to have something like tabs for M:M relations also for 1:M relations? Any other way to see the M part of the relation is well accepted.
Thank you in advance

**Comment by vovpff** [comment]
All related cars should be visible in Cars tab of Parking record!

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/77169310-56c65d00-6aca-11ea-9224-36a5857380c6.png)
`Запчасти` has 1:M field related to IGDN module. If this field filled: record appears in tab.

**Comment by zazy** [comment]
Thankyou vovpff for your reply but no, there is not such a tab in Parking record. Is there any settings I missed to let it appear? Or simply this doesn't work with "default" modules like Accounts?

**Comment by vovpff** [comment]
This should work everywhere. Activate logs and check what happens when you add 1:M field to Cars module. Maybe this process faulty.

**Comment by vovpff** [comment]
@zazy 
![1toM](https://user-images.githubusercontent.com/8545791/77175277-68603280-6ad3-11ea-9391-b9aac8bb2bae.gif)

**Comment by zazy** [comment]
That was the procedure I followed but nothing. Now I have disabled almost all modules, removed all "Cars" records, removed the 1:M relationship, forced cron to run ad added the relationship again and now it works as expected an as you explained above. Don't know what went wrong the firse time. Thank you very much for your support!
