### ISSUE TITLE
[Question] Sale workflow and products/services data

### ISSUE THREAD

**Issue by zazy** [YetiForceCompany/YetiForceCRM#12745]
Hi all,
I'm new to Yeti and I'm learning the sales process. As far as I can understand it starts with #0 Opportunities (not mandatory but heavily suggested to be created) and goes through several layers up to #5 sales orders. When I create the quote inquiry I add all products and services required by the customer (lets say there are 50 entries). When the inquiry enters the "Completed" state I create the requirements card and so on up to the quote. In each level I have to manually enter all products specified in the quote inquiry. Is there a way to "carry on" all entries across the whole process? For examples at this page https://yetiforce.com/en/knowledge-base/documentation/user-documentation/item/3-calculations is mentioned am additional tool "Generate a quote" that seems to be what I'm looking for but I can't find it anywhere. Am I missing something in the process?

**Comment by vdpawel** [comment]
This can be done by mapping:
Software configuration -> Standard modules -> Mapping

Thanks to this, you can generate a record in another module with already completed fields.

**Comment by zazy** [comment]
Thankyou vdpawel for your reply. I was already using the mapping feature but I didn't realized that a new button appears in the upper right corner of the Quote page for the "Generate record" action. Thank you again. Problem solved.
