### ISSUE TITLE
[PL][bug] Faktura kosztowa - edycja - jednostki produktów nie są wyświetlane

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#12744]
# 🐞 bug report

### ⁉️ Describe the bug
W module faktury kosztowe, po dodaniu produktu w edycji, nie jest wyświetlana jednostka (kg/szt./itp.).

### 🔥 How to trigger the error
Faktury kosztowe -> dodaj rekord -> dodaj produkt = jednostka nie jest wyświetlana na liście produktów

![there is no view of unit](https://user-images.githubusercontent.com/62466142/77226262-4b7d3b00-6b77-11ea-9df0-5d13395d79c2.gif)

### 👍 Expected Behavior
Po dodaniu produktu podczas edycji faktury kosztowej, jednostka będzie od razu widoczna na liście.

### 👷 Testing 
- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ x ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by vovpff** [comment]
Looks like mapping line missed in _invmap table for this module

**Comment by vdpawel** [comment]
In my database, the table "u_yf_finvoicecost_invmap" is empty.

**Comment by vovpff** [comment]
@vdpawel you can fill it manually. Check other _invmap tables for example. In case your system was installed without troubles this tables should be filled.

**Comment by vdpawel** [comment]
After adding the appropriate records to the database, displaying units began to work.

INSERT INTO `u_yf_finvoicecost_invmap` (`module`, `field`, `tofield`) VALUES ('Products', 'subunit', 'subunit'), ('Products', 'usageunit', 'unit'), ('Services', 'service_usageunit', 'unit') 

This table was not completed after installation in versions 5.2 and 5.3 and updates.

Thank you for your help.

**Comment by vovpff** [comment]
@vdpawel offtopic: animal ar right bottom corner. What is it?

**Comment by mariuszkrzaczkowski** [comment]
https://chomikuj.pl/ChomikBox.aspx

**Comment by vovpff** [comment]
@mariuszkrzaczkowski cloud storage?

**Comment by mariuszkrzaczkowski** [comment]
@vovpff yes

**Comment by konadrian** [comment]
Obecna wersja gitdeveloper, wszystko działa poprawnie 
![korekta](https://user-images.githubusercontent.com/3193498/77538286-c6a85f00-6e9f-11ea-81f3-806d6e73e47c.gif)
