### ISSUE TITLE
[BUG] Roundcube Language

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1274]
Language is almost unchanged, along with the language system
![2015-7-2_8-5-20 392](https://cloud.githubusercontent.com/assets/1402355/8469264/1ea0950e-2091-11e5-9c1b-c716e74ce1e8.jpg)

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/github/issues/206-system-development-ideas.html

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/0e52aca2c627f5102af87bef10bc2772a71f2ef4
