### ISSUE TITLE
[bug] [PL] Po dodaniu faktury korekty, nie pokazują się dane z faktury korygowanej (Problem with Correcting Invoices)

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#12746]
# 🐞 bug report

### ⁉️ Describe the bug
W module faktury korekty, po wybraniu faktury sprzedażowej która będzie korygowana, pozycje z  faktury korygowanej nie pojawiają się w oknie edycji.

![there is no view of invoice to be corrected](https://user-images.githubusercontent.com/62466142/77236211-de8c9400-6bbc-11ea-8130-f8840a7fa13b.gif)

### 🔥 How to trigger the error
Accounting -> Correcting Invoices -> Add record -> Select invoice to be corrected = brak danych dotyczących faktury korygowanej na ekranie edycji (no corrected invoice data)

### 👎 Actual Behavior
Po wybraniu faktury sprzedażowej, nie zostają odświeżone dane dot. faktury korygowanej, cięgle jest wyświetlany komunikat: "Select invoice to be corrected" w sekcji: "Before correction"

### 👍 Expected Behavior
Po wybraniu faktury sprzedażowej, zniknie komunikat: "Select invoice to be corrected", a pojawi się lista produktów/usług z faktury sprzedażowej.

### 👷 Testing 
Problem występuje w wersjach 5.2 SP19, 5.3 oraz przetestowane na:
- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by mariuszkrzaczkowski** [comment]
Changes published in 5.3.0_ServicePack_v3
