### ISSUE TITLE
[Question] CSRF protection causes unresponsive UI

### ISSUE THREAD

**Issue by zazy** [YetiForceCompany/YetiForceCRM#12751]
Don't know if this is a bug because I can't reproduce it on gitstable.yetiforce.com but on my 5.3.0 SP1 fresh install happens everytime.
This is the path I follow:
Log into YetiForce > Accounts > choose any account > click on Contacts tab > click on **Add record** 
The quick create overlay appears. Click on **Go to full form** then click on **Cancel**
Now if I try to go to another tab or to do anything that requires an ajax call, the _Loading, please wait_ overlay will never disappear and the request will never be served.

If I reload the page (F5 or SHIFT + F5) the problem persist. Even stranger if I copy the url that appears in the Chrome url bar after switching to Contacts tab and paste it in an incognito new Chrome widnow the problem persists!

This happens even if, when in the full form, I hit the back button.

I found on Github some issues that appears to be related to this one (CSRF protection system) where the problem is due to the url set in $PORTAL_URL. I've tried with and without / at the end of url and the problem persist.

In Developer tools when I cancel the add record form, I have the following advice:

![Schermata da 2020-03-23 17-41-43](https://user-images.githubusercontent.com/10668286/77341106-84134500-6d2e-11ea-82ec-93d19268e4ad.png)

This is what I found in cache/logs/system.log after enabling log:
```
====================================================================================================================================
2020-03-23 17:11:56.6543 [error] - Invalid request - Response For Illegal Access.
App\Exceptions\AppException: Invalid request - Response For Illegal Access. in /var/www/crm/config/csrf_config.php:21
Stack trace:
#0 /var/www/crm/vendor/yetiforce/csrf-magic/src/Csrf.php(243): CSRFConfig::{closure}('')
#1 /var/www/crm/vendor/yetiforce/csrf-magic/src/Csrf.php(515): CsrfMagic\Csrf::check()
#2 /var/www/crm/app/Controller/Base.php(40): CsrfMagic\Csrf::init()
#3 /var/www/crm/include/main/WebUI.php(163): App\Controller\Base->__construct()
#4 /var/www/crm/index.php(28): Vtiger_WebUI->process(Object(App\Request))
#5 /var/www/crm/public_html/index.php(11): require('/var/www/crm/in...')
#6 {main}
2020-03-23 17:11:56.6306 [info][application] - 
$_GET = []
$_POST = [
    'module' => 'Contacts'
    'xview' => 'Detail'
    'record' => '116'
    'view' => 'RecordPopover'
]
$_FILES = []
$_COOKIE = [
    'YTSID' => '632tbaf1hqnfqaumf68vj0bu4c'
]
$_SESSION = [
    'last_activity' => 1584979905.8698
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => 'e778c7fa53b4b6281998d70a0186971cdc9f199a'
    'user_name' => 'zazy'
    'full_user_name' => 'The Administrator'
    'fingerprint' => '2750bc42-702e-4cbe-bae5-798f171389e1'
    'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
    ]
    'PHPDEBUGBAR_STACK_DATA' => []
]
$stability = [
    'error_reporting' => 'E_ERROR | E_WARNING | E_PARSE | E_NOTICE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_USER_ERROR | E_USER_WARNING | E_USER_NOTICE (22527)'
    'default_socket_timeout' => '60'
    'short_open_tag' => 'Off'
    'post_max_size' => '8.00 MB'
    'upload_max_filesize' => '2.00 MB'
    'max_input_vars' => '1000'
    'session.gc_probability' => '0'
    'auto_detect_line_endings' => 'Off'
]
$security = [
    'session.use_strict_mode' => 'Off'
    'expose_php' => 'On'
]
$performance = [
    'xdebug' => 'On'
    'opcache.enable_cli' => 'Off'
    'opcache.max_accelerated_files' => '10000'
    'opcache.interned_strings_buffer' => '8'
    'opcache.revalidate_freq' => '2'
    'opcache.save_comments' => '1'
    'opcache.file_update_protection' => '2'
    'realpath_cache_ttl' => '120'
    'mysqlnd.collect_statistics' => 'On'
]
$environment = [
    'error_log' => false
    'open_basedir' => false
    'openssl.cafile' => false
    'openssl.capath' => false
]
====================================================================================================================================
```

Any advice on what can cause this behavior?

**Comment by zazy** [comment]
Here again just to add that if I disable CSRF protection in config/Security.php by setting  $csrfActive to false, the problem disappears. 
Any idea on what can cause this behavior?

**Comment by mariuszkrzaczkowski** [comment]
start by correcting the server configuration because you have a bad error_reporting

**Comment by zazy** [comment]
Thankyou @mariuszkrzaczkowski for your reply and for pointing out that. Value reported in the error log had been changed **after** the error was presented for the first time just to investigate the matter. Furthermore it is only for CLI php.ini while php.ini for Apache and PHP7.2-fpm is the one required.
I have restored my initial configuration and here it is (this is a "config-to-test pending" install so I don't care about security and performance until it will go live) 
![ConfReport](https://user-images.githubusercontent.com/10668286/77673314-4f032e80-6f8a-11ea-9ab2-f8482c207424.png)

**Comment by mariuszkrzaczkowski** [comment]
set error_log

**Comment by simple-AMS** [comment]
Disable CSRF altogether. Why use it in the first place?

**Comment by bpabiszczak** [comment]
We have already fixed a similar bug [check gitdeveloper version]
