### ISSUE TITLE
[BUGS]  Holidays Entitlement and Employees

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1275]
Step 1 - Go to Annual holiday entitlement
![step_1](https://cloud.githubusercontent.com/assets/1402355/8469476/1fafd438-2095-11e5-8ad3-f8e0e5d4cca2.png)

Step 2 - Add Employees

![step2](https://cloud.githubusercontent.com/assets/1402355/8469506/69a5f2d4-2095-11e5-9c4d-79e2a140171a.png)

Step 3 - Save

![step3](https://cloud.githubusercontent.com/assets/1402355/8469510/7a8d7234-2095-11e5-8ce3-fbe99dcc02ee.png)

Step 4 - Save

![step4](https://cloud.githubusercontent.com/assets/1402355/8469513/847722c2-2095-11e5-9058-5e9ebf4d7419.png)

Step 5 - Summary list clear

![step5](https://cloud.githubusercontent.com/assets/1402355/8469517/b61d7056-2095-11e5-9dd8-3aeb8cb7ab04.png)

Step 6 - Details work

![step6](https://cloud.githubusercontent.com/assets/1402355/8469521/cb75b81e-2095-11e5-8c07-fa244f54abbe.png)

Step 7 - Go to Annual holiday entitlement

![step7](https://cloud.githubusercontent.com/assets/1402355/8469524/de3db0dc-2095-11e5-9aa8-7cf431ed3aee.png)

Step 8 - It is necessary to correct a pattern, a lot of empty space and everything not included

![step8](https://cloud.githubusercontent.com/assets/1402355/8469528/ee046164-2095-11e5-849b-21183720a12a.png)

Step 9 - Click on Employees - Summary list clear

![step9](https://cloud.githubusercontent.com/assets/1402355/8469546/2687c03a-2096-11e5-9b6d-72aacea62e99.png)

**Comment by KatarzynaUlichnowska** [comment]
The display of columns has been improved. Other issues are some sort of enhancements, not bugs [widgets can be added, it's not a bug]. These modules will be developed in 2.2, maybe we will manage to do it in 2.1 but I don't want to make empty promises.
