### ISSUE TITLE
[Question] Image size too big when its exported to PDF

### ISSUE THREAD

**Issue by rtorrescodes** [YetiForceCompany/YetiForceCRM#12752]
Hello, does anybody know how fix this problem?  I need to add an image (a qr code) inside the orders. The image is 512px x 512px.  I added a custom field to enter the image.

Everything works perfect, but, when i use that field inside a pdf template for orders, image goes almost full page size.  Im sure its not that easy because in the template, the image is called with a shotcode, not an html <img> entry i can manipulate to fix its size.  

Thanks a lot.

**Comment by apcloic** [comment]
Hi @rtorrescodes 

YetiforcePDF supports width and height as params.

Example : $(record : your_image_field|512px|512px)$

You may also find useful informations on the following link :
https://github.com/YetiForceCompany/YetiForcePDF

Regards,

**Comment by rtorrescodes** [comment]
I really really thank you a lot, this will help me too much to create amazing template. Thanks again.
