### ISSUE TITLE
[BUG] Time Control

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1276]
Step 1 - Go to Time Control
![time1](https://cloud.githubusercontent.com/assets/1402355/8469638/8cac5136-2097-11e5-8643-b185a6d8597c.png)
Step 2 - Add record 
The top row left
![time2](https://cloud.githubusercontent.com/assets/1402355/8469639/8f816108-2097-11e5-9910-413565cc4bbd.png)
Step 3 - Add name and date
The visual editor can be extended
![time3](https://cloud.githubusercontent.com/assets/1402355/8469642/911db0d4-2097-11e5-9770-c64f5e2c3bfc.png)
Step 4 - Save
![time4](https://cloud.githubusercontent.com/assets/1402355/8469644/9282261c-2097-11e5-9025-82d7f91be7d9.png)
Step 5 - After saving the information is not updated
![time5](https://cloud.githubusercontent.com/assets/1402355/8469645/93b9bbee-2097-11e5-87d8-435ca62e8b67.png)
Step 6 - Choose a calendar day
![time6](https://cloud.githubusercontent.com/assets/1402355/8469646/952185f2-2097-11e5-9525-dacb3e39f434.png)
Step 7 - Oh, everything is in place
![time7](https://cloud.githubusercontent.com/assets/1402355/8469647/9678c14a-2097-11e5-9322-f2e7b6278cec.png)
Step 8 - Go back to the calendar for the month
![time8](https://cloud.githubusercontent.com/assets/1402355/8469648/97f4bbb4-2097-11e5-9fc1-e5e1bedc3b71.png)
Step 9 - Now everything is in place
One could specify a time period and a number Subject, and the description below
![time9](https://cloud.githubusercontent.com/assets/1402355/8469649/993b0da2-2097-11e5-98f8-c30c394d3a06.png)

The visual editor is needed at all in the description?

**Comment by bpabiszczak** [comment]
One error per issue, don't include many different errors in one issue, even if they concern the same place in CRM, because it is hard to manage and verify what's been fixed and what hasn't, what needs to be fixed and what's not an error.
