### ISSUE TITLE
[bug] Document URL renders incorrectly

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12765]
# 🐞 bug report

### ⁉️ Describe the bug

When defining a Document with external type and a long link associated, a subset of the link is show, ending with ... Unfortunately, the URL in the "a href=" is also the shortened link and not the full link.

### 🔥 How to trigger the error

1. Create a document of type 'external' and associate a long URL
![create](https://user-images.githubusercontent.com/10230144/77439958-fe53d000-6de7-11ea-997d-d7ba43a8d791.png)

2. View the document summary, for example in the summary view of a campaign. Due to a lack of space, not the full link is shown, but only a shortened version ending with ...
![view](https://user-images.githubusercontent.com/10230144/77440043-1cb9cb80-6de8-11ea-9142-131993f91ea2.png)

3. When clicking on the URL, the system tries to open the shortened URL, rather than the full URL
![openes](https://user-images.githubusercontent.com/10230144/77440137-3e1ab780-6de8-11ea-8a3c-a218b3a78546.png)

### 👎 Actual Behavior

Browser tries to open shortened URL

### 👍 Expected Behavior

Browser should open full URL.

### 👷 Testing 

- [ ?] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.3.0 SP1 & 5.3.12
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by diderich** [comment]
Record is correcly stored in vtiger_notes table. Problem is in displaying the data.

**Comment by mariuszkrzaczkowski** [comment]
Changes published in 5.3.0_ServicePack_v3
