### ISSUE TITLE
[bug] 5.3 Line items Comments absolutely non informative now

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#12760]
# 🐞 bug report

### ⁉️ Describe the bug

I has checked what now WYSIWYG fields has different display than 5.2

In 5.2 we have powerful tool to focus user on some important data inside line comments using HTML

![image](https://user-images.githubusercontent.com/8545791/77415150-179e5180-6dd3-11ea-9ad9-0b395db7ef4a.png)

Now we got absolutely non informative plain text without line breaks and user can't be focused on something important information inside item comment and need to click fullscreen button every time to check user-friendly comment 

![image](https://user-images.githubusercontent.com/8545791/77411923-34845600-6dce-11ea-8c39-725115acef23.png)

Is it possible to make this useless feature optional because now updated to 5.3 system Advanced module table looks like plain-text nightmare 👎👎👎

**Comment by vovpff** [comment]
@mariuszkrzaczkowski @bpabiszczak @paula-w 
Could you give comments this issue?
For this time this is only one thing what stops me with update production to 5.3

**Comment by z0lo13** [comment]
Confirm all html is stripped in 5.30 SP1

**Comment by alexandr256** [comment]
I can confirm what comment under item name became useless.

**Comment by vovpff** [comment]
Any solution for this?

**Comment by vovpff** [comment]
@z0lo13 do you have any solution for this issue?

**Comment by z0lo13** [comment]
@vovpff no quick fix...
 as now its using iframe element to display value its parsed correct when opened in iframe.....

**Comment by z0lo13** [comment]
@vovpff 

in
https://github.com/YetiForceCompany/YetiForceCRM/blob/42430532d77c0caaf8e32a0390ae26e345411078/app/Layout.php

change 

`$teaser = TextParser::textTruncate(trim(strip_tags($html)), $length);`
to 
`$teaser = $html;`

**Comment by vovpff** [comment]
@z0lo13 thx, I will try it tomorrow

**Comment by vovpff** [comment]
@z0lo13 i tried your mod. This works but affects to all HTML fields in system what has show full text button eg. in ListView. :( this is bad...

**Comment by z0lo13** [comment]
@vovpff seems like there is no separate class for html comments fields...

**Comment by vovpff** [comment]
@z0lo13 yes and this is fail

**Comment by waran70** [comment]
ugrr this is really bad, crippled me lot of dev hours
![oh](https://user-images.githubusercontent.com/6852348/79183596-14c7d700-7e3c-11ea-961c-4642f75fe13c.gif)

**Comment by vovpff** [comment]
@waran70 do you have solution?

**Comment by vovpff** [comment]
I has checked what this "feature" also affects on Announcements modal window... 

![image](https://user-images.githubusercontent.com/8545791/79716989-01f04f00-82e1-11ea-8bfa-cf297ed51736.png)

**Comment by mariuszkrzaczkowski** [comment]
config/Modules/SSingleOrders.php

```
namespace Config\Modules;

/**
 * Configuration Class.
 */
class SSingleOrders
{
	public static $inventoryCommentIframeContent = false;
}
```

**Comment by vovpff** [comment]
@mariuszkrzaczkowski this will affect only to SSingleOrders?

**Comment by mariuszkrzaczkowski** [comment]
yes

**Comment by vovpff** [comment]
@mariuszkrzaczkowski sorry but what you solve with this code? Problem - html stripped in product line comments for all advanced modules (Invoices, sales orders, all logistics modules and etc)

**Comment by mariuszkrzaczkowski** [comment]
then set this variable in for these modules in the config / modules directory

**Comment by vovpff** [comment]
Ok. I will do it. Is this fix will be available with next service pack?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I has enabled this fix for IGDN. Looks better but line comment trimmed. How to disable trimming?
![image](https://user-images.githubusercontent.com/8545791/79739521-f879dd80-8306-11ea-8cef-34ce76350495.png)

**Comment by mariuszkrzaczkowski** [comment]
listview_max_textlength

**Comment by vovpff** [comment]
@mariuszkrzaczkowski got it

**Comment by vovpff** [comment]
@mariuszkrzaczkowski what about stripped announcements?

https://github.com/YetiForceCompany/YetiForceCRM/issues/12760#issuecomment-616315891

**Comment by mariuszkrzaczkowski** [comment]
this is an error report in a new issue

**Comment by vovpff** [comment]
@mariuszkrzaczkowski 

> listview_max_textlength

This parameter also affects to rendering of usual text fields in listview. Now I has increased this param to 1000 to see full line comment in advanced modules but checked what job title column became very big for contact because text isn't trimmed:

![image](https://user-images.githubusercontent.com/8545791/79951989-5a128700-8482-11ea-805f-881db2d9a2cd.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski any suggestions? is it possible to trim columns content in list view?

**Comment by vovpff** [comment]
self-solved

**Comment by allyh12** [comment]
Hi, could you please share on the solutions? Thank you so much.

**Comment by vovpff** [comment]
@allyh12  `TextParser::textTruncate` was duplicated in core files with other name with ignored `listview_max_textlength` and set 10000 symbols instead.

https://github.com/YetiForceCompany/YetiForceCRM/blob/42430532d77c0caaf8e32a0390ae26e345411078/app/Layout.php textTruncate was replaced to new function name

this https://github.com/YetiForceCompany/YetiForceCRM/issues/12760#issuecomment-616325332 was applied for critical modules

this https://github.com/YetiForceCompany/YetiForceCRM/commit/2ab27e9db2beda812edc4880d3c6efefd17683d0 was applied

`listview_max_textlength` was turned back to 35

Now only announcement look like hell but I use them very often.

**Comment by allyh12** [comment]
@vovpff Thank you so much. Is it possible to include these line breaks when the record is exported to PDF? PDF still not showing the line breaks.

**Comment by allyh12** [comment]
@vovpff Thank you so much!

**Comment by apcloic** [comment]
@vovpff 

Hi, I've just apply the fix to get html back in item's comment but now they are all trimmed according to the value of listview_max_textlength

So if I want full item's comment in PDF export for Invoice module, I have to increase listview_max_textlength value.

I've followed your guidelines regarding this issue but unfortunately, item's comment remains trimmed.

I'm using a brand new install of YF 5.3 with SP4.

Any idea ?

Regards
