### ISSUE TITLE
[bug] 12 Hour Clockpicker "Please enter valid time"

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#12775]
# 🐞 bug report

### ⁉️ Describe the bug

in 5.3 SP 2 as well as gitstable does not allow to save time when using 12 hour format. It is fixed in current git developer but was not coming with a second service pack. 
### 🔥 How to trigger the error

Gitstable
![2020-03-26_01-42-51 (1)](https://user-images.githubusercontent.com/23143958/77614535-9397b700-6f03-11ea-9dd4-f610eeac754d.gif)

Our Instance
![2020-03-26_01-47-21 (1)](https://user-images.githubusercontent.com/23143958/77614711-fbe69880-6f03-11ea-9a6a-b0016471a361.gif)

### 👎 Actual Behavior

Time is not saved
### 👍 Expected Behavior

Time saved
### 👷 Testing 

- [ ✔️] I confirm that I tested it at https://gitstable.yetiforce.com Not working
- [ ✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com Working as it should but not included in SP

### 📷 Screenshot of configuration

Git Stable
### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Git Stable

### 🌍  Your Environment 

Git Stable
	|
| Service Pack version | 		2|

**Comment by kcrudup** [comment]
The clockpicker is adding an extra space between the AM/PM and the time.

Creating 10:00  AM - extra space - invalid
and not  10:00 AM - no extra space - valid

**Comment by z0lo13** [comment]
@konadrian
https://github.com/YetiForceCompany/YetiForceCRM/commit/6e6895d4859509e415bd5c1d909147a2a6aae40e the space on line 899

**Comment by simple-AMS** [comment]
Been an issue every release as far back as I can remember. No effort has gone into correcting it for 12 hour since it works for those in 24 hours.

**Comment by rskrzypczak** [comment]
The problem is in the clockpicker library itself, they have a wrongly compiled min.js file in there.
You can solve this error quickly in 2 ways:
1. Remove `public_html/libraries/clockpicker/dist/bootstrap4-clockpicker.min.js` file
2. Disable loading min.js files `config/Developer.php`  ($MINIMIZE_JS)

**Comment by simple-AMS** [comment]
Wow @rskrzypczak finally someone with a solution for an issue with this system that actually works. Thanks so much man, it worked perfectly. Assuming it doesn't cause issues elsewhere that is lol. 

Would you mind helping me out with this other issue that I really need to get working asap? #12793 

Thanks again mate!

**Comment by rskrzypczak** [comment]
install [service pack v4](https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.3.0)
