### ISSUE TITLE
[bug] Call to a member function getDisplayValue() on null.

### ISSUE THREAD

**Issue by federico0100** [YetiForceCompany/YetiForceCRM#12773]
# 🐞 bug report

### ⁉️ Describe the bug

Good morning.
When I create a project task and press "Save", I get the error "Call to a member function getDisplayValue () on null."
I send you the screenshot of the report.

Thank you

### 🔥 How to trigger the error

![image](https://user-images.githubusercontent.com/62551450/77550728-bb5e2f00-6eb1-11ea-92b0-8c19c74f64a1.png)

![image](https://user-images.githubusercontent.com/62551450/77550777-c87b1e00-6eb1-11ea-83ea-650399102fb7.png)

### 👷 Testing 

- [v] I confirm that I tested it at https://gitstable.yetiforce.com 
- [v] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
![image](https://user-images.githubusercontent.com/62551450/77550987-08da9c00-6eb2-11ea-834d-b1f0b3dfc1b1.png)

**Comment by rskrzypczak** [comment]
Go to "Labels and searches" panel and temporarily edit the "Columns for search mechanisms" for your module.
![image](https://user-images.githubusercontent.com/10221999/77614708-e2f2dd00-6f2d-11ea-81be-6811cc3902d4.png)

**Comment by federico0100** [comment]
Thanks a lot, it finally works now!
