### ISSUE TITLE
OpenStreetMap.php

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#12778]
Unfortunately, some things become more complicated and not simpler than I expected. I've tried everything before, but my knowledge is not enough to set up an Open Street Map in YETIFORCE. Please if anyone can help me where and how to set up https://www.openstreetmap.org/.

**Comment by apcloic** [comment]
@fbojan 
I think an easy way is to create a free Opencage account here :
 https://opencagedata.com/

And then insert your key :
https://gitdeveloper.yetiforce.com/index.php?module=ApiAddress&parent=Settings&view=Configuration&block=5&fieldid=61

Don't forget to configure cron correctly and enable coordinates tasks.
https://gitdeveloper.yetiforce.com/index.php?module=CronTasks&parent=Settings&view=List&block=15&fieldid=26

Regards,

**Comment by mariuszkrzaczkowski** [comment]
@fbojan give me a larger description of what you want to do because I don't know what part of OSM you are talking about

**Comment by fbojan** [comment]
> @fbojan give me a larger description of what you want to do because I don't know what part of OSM you are talking about
YETIFORCE 5.3. ver2
![map](https://user-images.githubusercontent.com/25682437/77748144-2a599600-7020-11ea-8ed2-ef8ff647b0d7.gif)

![ConfReport](https://user-images.githubusercontent.com/25682437/77748243-51b06300-7020-11ea-9527-73c59f58a4db.png)

**Comment by mariuszkrzaczkowski** [comment]
This panel what you show is for something else.
By default, public servers cannot be set, their regulations prohibit it.
See the panel with public suppliers added  https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Map&view=Config&block=5&fieldid=123
