### ISSUE TITLE
[question] `vtiger_ossmailview` is droping the update performance.

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#12774]
## 🚀 Question

in out production vtiger_ossmailview is super huge table (~32 GB)
I guess because of that large table the update is taking very long. 

Would you maybe recommend different update procedure for instances with big DBs?
or maybe it is a bug?

changeColumnType	|	16:04:11 -> 18:01:31	|	117.33 min.

**Comment by bpabiszczak** [comment]
First of all, you need to answer the question whether all these emails should actually be there [some clients import only those emails that have been related to a record in CRM].

If you have a CRM system and one of its tables has 32GB, it means that you have a large system with a lot of data that should be monitored and optimized constantly. Each change in a large table requires time, it isn't surprising that changing the main field in the 32GB table takes 2 hours. This depends on the server parameters and not on the update file. Obviously, some things can be performed faster from the console, but we don't have access to it from the application level.

The update process in large systems should be optimized and each time requires a full-stack developer. It appears necessary to consider changing free support to dedicated support ;)
