### ISSUE TITLE
[Feature] LDAP SSL, Security Enhancement

### ISSUE THREAD

**Issue by jobrien2001** [YetiForceCompany/YetiForceCRM#12777]
# 🚀 feature request

### Describe the solution you'd like
Would like an option to use an SSL port for LDAP integration. 

### Is your feature request related to a problem? Please describe.
No problem, just added security.

### Describe alternatives you've considered
If adding certificates to yeti is too much work, a checkbox to ignore certificate errors would be nice just to get temporary functionality.

### Additional context

![Capture](https://user-images.githubusercontent.com/12868319/77633756-ec744900-6f1d-11ea-9965-1df335ea56fe.PNG)

**Comment by bpabiszczak** [comment]
Currently it can be set in the script.
