### ISSUE TITLE
[Question] Przypisanie leadowi istniejącego dokumenty za pomocą API

### ISSUE THREAD

**Issue by odiiin** [YetiForceCompany/YetiForceCRM#12779]
### Description

Muszę ok. 1000 lead'om przypisać dokument istniejący już w CRMie. Zamiast robić to ręcznie chciałbym wykorzystać API, ogólnie API wykorzystałem już w kilku przypadkach ale nie wiem jak podejść do tego w tym konkretnym. 

Jeśli chodziłoby o standardowe pole to zrobiłbym coś takiego:
```
$record = array(
    'website' => ''.$website.''
);
$response = $yr->updateRecord($module, $id, $record);
```

Próbowałem też tak:
```
$record = array(
    'Documents' => [
       'notesid' => $note_id
     ]
);
$response = $yr->updateRecord($module, $id, $record);
```
ale nie działa, po prostu nie wiem jak się dobrać do modułów z którymi Lead wchodzi w relacje.

Może na odwrót, czyli w module Documents dodać powiązanie z id leada? Jeśli tak to jak będzie wyglądał kod ponieważ w polach modułu Documents nic związanego z powiązaniami nie widać.

Mógłbym dodać to zapytaniem SQL w tabeli `vtiger_senotesrel` i te pliki pojawią się w Lead -> Documents ale wiadomo, nie jest to najlepsze rozwiązanie bo wtedy nie ma żadnej informacji w "Historii zmian", itd.

Dzięki

**Comment by bpabiszczak** [comment]
My nie udzielamy bezpłatnych porad programistycznych [można wykupić u nas pakiet godzin i wówczas możemy pomóc]. Oznaczę jako dyskusja, może ktoś Tobie pomoże, jeżeli przez tydzień nikt nie napiszę, zamkniemy zgłoszenie.
