### ISSUE TITLE
[bug] Roundcube, double login window

### ISSUE THREAD

**Issue by federico0100** [YetiForceCompany/YetiForceCRM#12783]
# 🐞 bug report

Good morning. When I select "My Mail", I get a screen with double login to a "file not found" message. I attach the screenshot.

Thank you

### 🔥 How to trigger the error

![image](https://user-images.githubusercontent.com/62551450/77732601-764b1180-7005-11ea-957b-d4803d58a2dc.png)

### 👷 Testing 

- [v] I confirm that I tested it at https://gitstable.yetiforce.com 
- [v] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
![image](https://user-images.githubusercontent.com/62551450/77733012-67189380-7006-11ea-952b-c92af325298d.png)

**Comment by bpabiszczak** [comment]
Please fix the error first "file not found".

**Comment by federico0100** [comment]
I would do it but it doesn't specify what file it can't find

**Comment by federico0100** [comment]
Can you give me some clues on how to fix the file not found problem?

**Comment by vencatoitc** [comment]
Hi all,

Same error here... Plus from the inspector we have: "GET https://[...]/public_html/modules/OSSMail/roundcube/ 500 (Internal Server Error)" and yet nothing on Apache error log.
The Roundcube portion is unusable.

**Comment by KatarzynaUlichnowska** [comment]
Please add this in a separate issue. 
New problem = new ticket.

**Comment by vencatoitc** [comment]
@KatarzynaUlichnowska sorry I was thinking it was related. I'll follow the issue just in case it'll resolve mine. Thanks.

**Comment by vencatoitc** [comment]
@bpabiszczak it seems like that in "public_html/modules/OSSMail/roundcube/index.php" the $OUTPUT->send() is called twice on lines 248 and 316; after the latter it flows directly into rcmail::raise_error() (at the EOF) causing the duplicate login form and the error message.

**Comment by vencatoitc** [comment]
We just perform a fresh install of the CRM, updated to SP4 and installed the Roundcube library.
We confirm the "double login form" issue; from "errors" file we get twice the same error (which is triggered at the end of the script):

```
07-Apr-2020 14:09:49 +0200]: <n37hgeaf> PHP Error: Invalid request in /var/www/yetiforce/public_html/modules/OSSMail/roundcube/index.php on line 322 (GET /modules/OSSMail/roundcube/)

[07-Apr-2020 14:09:50 +0200]: <n37hgeaf> PHP Error: Invalid request in /var/www/yetiforce/public_html/modules/OSSMail/roundcube/index.php on line 322 (GET /modules/OSSMail/roundcube/)
```

How we can debug more?

**Comment by vencatoitc** [comment]
@bpabiszczak any news or hints?

**Comment by rskrzypczak** [comment]
Use auto login :)
![image](https://user-images.githubusercontent.com/10221999/79420844-01427a80-7fba-11ea-903b-50cd4d80ab00.png)

**Comment by vencatoitc** [comment]
@rskrzypczak alittle step forward:

```
[16-Apr-2020 08:29:45 +0200]: <0r7ak83a> PHP Error: Invalid request in /var/www/yetiforce/public_html/modules/OSSMail/roundcube/index.php on line 322 (GET /modules/OSSMail/roundcube/?_autologin=1&_autologinKey=19a84265e66d53c5c6c5f13f8dd070ce)
```

**Comment by vencatoitc** [comment]
@rskrzypczak besides the above mentioned error, the roundcube interface come up; I could see all my IMAP folders but no messages in it.
Oddly in the background I see a strange element... so I removed the "div" of the roundcube interface with the inspector and now I can see it (which displays the above mentioned error):

![Screenshot from 2020-04-16 08-45-09](https://user-images.githubusercontent.com/43751360/79423282-a0697100-7fbe-11ea-8744-dcd17de74e38.png)

**Comment by federico0100** [comment]
news?

**Comment by vencatoitc** [comment]
News from our side: we reinstalled (again) 5.4 on a Ubuntu server against the previous one CentOS.
So this issue is resolved for us.

**Comment by rskrzypczak** [comment]
Disable the uopz extension because it's probably active and that's all :)
