### ISSUE TITLE
[bug] [PL] Dodaj wykres z filtru - brak typu wartości "suma" oraz "średnia" (lack of "sum" and "average" in Add chart from filter)

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#12792]
# 🐞 bug report

### ⁉️ Describe the bug
Na wykresach z filtru brakuje możliwości uzyskania sumowania oraz średniej wartości na wykresach.

### 🔥 How to trigger the error
Sales invoices -> Dashboard -> Add chart from filter -> *Select module: Sales invoices, cost invoices, correcting invoices, proforma invoices = *Value type - only Number of records

### 👎 Actual Behavior
![a1](https://user-images.githubusercontent.com/62466142/77828573-a20ceb00-711c-11ea-9da2-17847869a121.png)

### 👍 Expected Behavior
![a2](https://user-images.githubusercontent.com/62466142/77828579-a802cc00-711c-11ea-89de-be6f26f141fd.png)

### 👷 Testing 
- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by bpabiszczak** [comment]
Proszę o zrzuty ekranu czego brakuje [na zrzucie napisać co gdzie być powinno i dlaczego to jest błędem].

**Comment by vdpawel** [comment]
**YetiForce CRM 5.2 Service Pack v19**
w module faktury sprzedażowe, przy dodawaniu wykresu z filtru można wybrać **typ wartości:**
- Ilość rekordów,
- suma,
- średnia.

co potwierdzam poniższym zrzutem ekranu:
![Screenshot_2020-03-29 Faktury sprzedażowe](https://user-images.githubusercontent.com/62466142/77850668-5f0e4e80-71d4-11ea-9d57-f7b46e794ae5.png)

W wersji deweloperskiej **YetiForce CRM 5.3 Service Pack v3**
w module faktury sprzedażowe, przy dodawaniu wykresu z filtru można wybrać **typ wartości:**
- Ilość rekordów.

co potwierdzam poniższym zrzutem ekranu:
![a1](https://user-images.githubusercontent.com/62466142/77850773-eeb3fd00-71d4-11ea-8289-dd53214538ad.png)

**Czego brakuje oraz dlaczego to jest błędem**
W kolejnej wersji YF nie można już wybrać **typu wartości:**
- Suma,
- średnia,
w module faktury sprzedażowe, przy dodawaniu wykresu z filtru.

Brakuje możliwości wyboru "suma" oraz "średnia" w module faktury sprzedażowe, przy dodawaniu wykresu z filtru. 
Błąd polega na tym, że możliwość wyboru "suma" oraz "średnia" w module faktury sprzedażowe przestały się pojawiać w nowej wersji YF.

Zauważyłem, że problem dotyczy również innych modułów dot. fakturowania.

**Comment by bpabiszczak** [comment]
Zależy od typu pola, widocznie pole które wybrałeś ma zły format [tzn. nie jest polem które obsługujemy w tym miejscu]. Można to rozszerzyć w dowolnym kierunku, ale musi się znaleźć najpierw chętny, który za to zapłaci.
