### ISSUE TITLE
[Question] Password Change at Login Screen NOT working in 5.3.0 Version

### ISSUE THREAD

**Issue by simple-AMS** [YetiForceCompany/YetiForceCRM#12793]
### Question?

What happened to the ability to change the password on the login screen in Version 5.3.0 with SP 3 installed? 

I went to the config directory and the Security.php file and I have the setting on True but it does not work in this version and worked fine before.

**Comment by mariuszkrzaczkowski** [comment]
have you set the default smtp?

**Comment by simple-AMS** [comment]
> have you set the default smtp?

Hi @mariuszkrzaczkowski sorry about that. I always seem to forget that step lol. As usual, you were right, that was it. You're the guru, thanks brother!
