### ISSUE TITLE
Yetiforce 5.2 security issue

### ISSUE THREAD

**Issue by sundersingh179** [YetiForceCompany/YetiForceCRM#12803]
hi there! 😄

I have deployed yetiforce 5.2 CRM on CentOS 7, Whenever opening my admin console, i am getting below warnings for Security/system configuration. Below is the configuration:
![yetiforce_settings](https://user-images.githubusercontent.com/62950315/78044564-ecdd6b80-7385-11ea-8a67-6a64d665dcb4.png)
[php.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/4410054/php.txt)
even i added both values inside /etc/php.ini 

opcache.max_accelerated_files = 40000
opcache.interned_strings_buffer = 100

Also, 
public_html value is off, from where i can make it recommended 'On'.

Thanks in advance.

**Comment by mariuszkrzaczkowski** [comment]
![20200331_221244](https://user-images.githubusercontent.com/10198654/78071283-86fcde00-739d-11ea-853d-942b5b183b77.png)

https://github.com/YetiForceCompany/YetiForceCRM/issues/6801

**Comment by bpabiszczak** [comment]
and?

**Comment by sundersingh179** [comment]
@mariuszkrzaczkowski , Thanks for your prompt reply. I have changed the value to opcache.max_accelerated_files = 40000 and i can see the changes but when i change opcache.interned_strings_buffer = 100 from 8 couldn't start apache. Error as: 
systemd-journal[92]: Runtime journal is using 8.0M (max allowed 189.0M, trying to leave 283.5M free of 1.8G available → current limit 189.0M).

Also, from where i can change public_html value to On.

Thanks once again.

**Comment by mariuszkrzaczkowski** [comment]
here you have a description of how to enable public_html
 https://github.com/YetiForceCompany/YetiForceCRM/issues/6801

**Comment by sundersingh179** [comment]
@mariuszkrzaczkowski Thanks. 
Please advise on this as well, I have changed the value to 
opcache.interned_strings_buffer = 100 from 8 couldn't start apache. Error as:
systemd-journal[92]: Runtime journal is using 8.0M (max allowed 189.0M, trying to leave 283.5M free of 1.8G available → current limit 189.0M).

**Comment by davide-alghi** [comment]
Hi @sundersingh179,
leave it at ```opcache.interned_strings_buffer = 8```
it's a performance settings: your server does not have enough resources

**Comment by sundersingh179** [comment]
@davide-alghi how much resources it would require to setup this as opcache.interned_strings_buffer = '100'
Thanks.

**Comment by davide-alghi** [comment]
try this (both Apache and PHP-CLI)

```opcache.memory_consumption=512```
```opcache.interned_strings_buffer=100```
