### ISSUE TITLE
[Question] PDF - List of of all Time Control entries associated with a given Project

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12802]
### Description

I would like to generate a report for all time control entries associated with a given project, ideally grouped by assigned to. I need such a report for the local authorities to prove the number of hours that have been worked. I have tried creating such a report using the PDF System settings, but with no success. Is there any documentation anywhere on how to do this?

**Comment by rskrzypczak** [comment]
![pdf (1)](https://user-images.githubusercontent.com/10221999/93600820-88a87580-f9c0-11ea-9d11-0ff02ffd9647.gif)
