### ISSUE TITLE
[Feature] Disable YetiForce branding.

### ISSUE THREAD

**Issue by EdwardStedE** [YetiForceCompany/YetiForceCRM#12804]

**Comment by EdwardStedE** [comment]
I cannot make a payment to disable YetiForce branding.

**Comment by bpabiszczak** [comment]
YetiForce version?

**Comment by EdwardStedE** [comment]
[ver. 5.2.0]

**Comment by bpabiszczak** [comment]
You must install the latest service pack for version 5.2 or upgrade to 5.3.
- YetiForce 5.2 SP v19 https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.2.0/5.2.0_ServicePack_v19.zip

**Comment by EdwardStedE** [comment]
Thank you, I will try that now.

**Comment by bpabiszczak** [comment]
Update pack from 5.2 > 5.3 https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%205.x.x/5.2.0_to_5.3.0/zip
