### ISSUE TITLE
[Question] How to enable Comments for a new custom module

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12806]
### Description

I have created a new module using "Create Module". Now I would like to allow Comments for that module. How can I enable comments?

**Comment by vovpff** [comment]
@diderich
```
INSERT INTO yourdbname.vtiger_fieldmodulerel (fieldid, module, relmodule, sequence) VALUES (601, 'ModComments', 'yourmodulename', NULL, 0); 
```

**Comment by diderich** [comment]
Thanks a lot for your help!

**Comment by simple-AMS** [comment]
@vovpff @diderich Hi guys I'm having the same exact issue in Version 6.1.0 with Service Pack 6 installed. The only info I need to change in the SQL query is only the parts that say yourdbname and that's it or what is the xact process? Sorry not the SQL query wiz so keep getting errors. Thanks guys!
