### ISSUE TITLE
[bug] RFatal error: Uncaught Exception: The imap library is missing in C:\xampp\htdocs\CRM\include\RequirementsValidation.php:15 Stack trace: #0 C:\xampp\htdocs\CRM\install\Install.php(24): include_once() #1 {main} thrown in C:\xampp\htdocs\CRM\include\RequirementsValidation.php on line 15equirementsValidation.php

### ISSUE THREAD

**Issue by marciopaixao** [YetiForceCompany/YetiForceCRM#12807]
# 🐞 bug report

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by simple-AMS** [comment]
@marciopaixao You didn't fill out any of the requested information above. In order to get assistance, you will need to provide all of the information in the template.

**Comment by mariuszkrzaczkowski** [comment]
The server configuration is not compatible with the requirements

**Comment by sudhakarmu** [comment]
Open xampp control panel click the config in the apache module and open the php.ini file search for ;extension = imap and remove the semicolon then it starts working fine
