### ISSUE TITLE
[Question] Mail Merger on YettiForce CRM for personalized Email

### ISSUE THREAD

**Issue by Abenzer24** [YetiForceCompany/YetiForceCRM#12808]
### Description

I am trying to send a personalize email to multiple contacts through Yetti Force CRM. I want to figure out how to send an email where it can automatically extract the first name from my contact list when I send email blasts.

For example:
To: 10 contacts
From: Me
Subject: Welcome {FirstName}

Hello {First Name},

This is a sample email {FirstName}

Thanks,
Me

**Comment by apcloic** [comment]
@Abenzer24 

Hi,

You have to create an email template :
https://gitstable.yetiforce.com/index.php?module=EmailTemplates&view=List&mid=175&parent=0

Regards,

**Comment by Abenzer24** [comment]
> @Abenzer24
> 
> Hi,
> 
> You have to create an email template :
> https://gitstable.yetiforce.com/index.php?module=EmailTemplates&view=List&mid=175&parent=0
> 
> Regards,

How can use that template once I create it with the "Welcome $(record : firstname)$" in the "my mailbox" function. When I go to my mailbox and i hover over the template option, it is deactivated and wont let me extract it from my records.
