### ISSUE TITLE
[Question] How to assign service contract to organization?

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#12809]
Hello,

when receiving a mail for example and assigning it to an existing organization, I get the message that there is _**no service contract assigned**_ to that organization. When I search for the service contracts (I have to types: "standard" and "premium"), these two types are _**not shown**_, but _**I have to create a new service contract for every organiszation**_.
But this is _**not what I want**_ and my understanding of service contracts. I only want to offer these 2 types of service and don't want to create a new contract for each customer or organization.

So, my first question:

**1.** Is it possible to to it the way I want (or maybe I don't get to point how to use the system)?

**2.** If it is not possible the way I explained above, is there a way to remove the message / mandatory of a service contract for each organization?

Thanks!

Regards

**Comment by apcloic** [comment]
@blu-IT 

Hi,

What you're trying to achieve is not really clear so I think you have to follow YF report error guidelines or at least show us what happen using ScreenToGif.

### 🔥 How to trigger the error

If possible, please make a video using [ScreenToGif] (https://screentogif.codeplex.com/) or any other program used for recording actions from your desktop.

Regards,

**Comment by blu-IT** [comment]
OK, sorry. Here are some screenshots:

1. I look at the ticktet in the system and it tells me that there is no SLA for this organization:

![1](https://user-images.githubusercontent.com/13665806/78539038-3862a000-77f2-11ea-996e-0c65ac0abe15.png)

2. I switch to the organization details looking for their service contract

![2](https://user-images.githubusercontent.com/13665806/78539166-68aa3e80-77f2-11ea-82a6-05cce6c0bc4d.png)

3. Then I want to assign an **already existing service contract** (see 4) to that organization, but I only can create a new one

![3](https://user-images.githubusercontent.com/13665806/78539625-26353180-77f3-11ea-9b48-b6aae7df0d94.png)
![4](https://user-images.githubusercontent.com/13665806/78539633-2af9e580-77f3-11ea-8b3f-682e631d8249.png)

4. But I already have these two types of service contracts I want to assign to my customers and don't want to create a new service contract for each organization

![5](https://user-images.githubusercontent.com/13665806/78539768-61cffb80-77f3-11ea-9149-42396c739b5d.png)

Is it clear now what I want to do?

**Comment by epsilonsc** [comment]
Hi, @blu-IT You must add an SLA for each contractor. 
You can use the templates created in the module https://gitdeveloper.yetiforce.com/index.php?module=SlaPolicy&parent=Settings&view=List&block=6&fieldid=119
and then add  a contract for each contractor
https://gitdeveloper.yetiforce.com/index.php?module=ServiceContracts&view=List&mid=65&parent=63

**Comment by blu-IT** [comment]
@epsilonsc 

Hi,

OK I have configured SLA now and created & assigned a service contract to the customer, but the warning still appears with a new ticket:

![Screenshot_2020-04-08 SlaPolicy System settings](https://user-images.githubusercontent.com/13665806/78835126-eedfa400-79ef-11ea-8c1e-21cabb71f974.png)

![Screenshot_2020-04-07 Service Contracts List](https://user-images.githubusercontent.com/13665806/78835160-f901a280-79ef-11ea-8ffc-d4fbc5cfec80.png)

![Screenshot_2020-04-08 Tickets Test 6](https://user-images.githubusercontent.com/13665806/78835172-ff901a00-79ef-11ea-9bfa-f639c4d0b374.png)

**Comment by mariuszkrzaczkowski** [comment]
The ServiceContracts must be of status "In Progress"
This can be turned off in config/Modules/HelpDesk.php CHECK_SERVICE_CONTRACTS_EXISTS =  false

**Comment by blu-IT** [comment]
@mariuszkrzaczkowski 

Sorry for that, but when trying to change status I can't select anything:

![Screenshot_2020-04-09 Service Contracts Standard](https://user-images.githubusercontent.com/13665806/78876572-d30bea80-7a4f-11ea-8c14-b05ae34defc0.png)

And what is also strange: A older ticket (Test 5) does not show the SLA warning...

![Screenshot_2020-04-07 Tickets Test 5](https://user-images.githubusercontent.com/13665806/78876754-1c5c3a00-7a50-11ea-90b1-92e2ea73b99b.png)
