### ISSUE TITLE
[Question] vTiger migration

### ISSUE THREAD

**Issue by nick-traeger** [YetiForceCompany/YetiForceCRM#12817]
Hello, we are currently using vTiger and would like to switch to YetiForce. Unfortunately, I have not found any useful information on how to migrate this the easiest way. Is there an official way?

**Comment by bpabiszczak** [comment]
We can do it as a paid service.

**Comment by nick-traeger** [comment]
Okay, what would it cost? And what are the requirements for this?

**Comment by vovpff** [comment]
Selfmade migration like nightmare. If you can charge for this - do it. But in any case check carefull current version for your requirements.

**Comment by paula-w** [comment]
@nick-traeger 
We’re going to need to know what modules you want to migrate, how much data is in each of them, and how many printouts you have. On the basis of this information we will be able to estimate the cost, it’s usually around 500€ net.
If you are interested, please send us an email to help@yetiforce.com and we will discuss the details. Thanks!
