### ISSUE TITLE
[Security] - User personal data

### ISSUE THREAD

**Issue by K-MeLeOn** [YetiForceCompany/YetiForceCRM#12818]
Why are the password/user name of the user tables included in plain text?

I doubt that personal data is kept safe in case of theft.

**Comment by bpabiszczak** [comment]
password? Show your table with test data.

**Comment by K-MeLeOn** [comment]
Thanks for your response.

Sure:
<img width="452" alt="Capture d’écran 2020-04-03 à 18 05 02" src="https://user-images.githubusercontent.com/47109782/78381894-4c31ba80-75d6-11ea-9238-7efb3bd15bb2.png">
<img width="452" alt="Capture d’écran 2020-04-03 à 18 06 25" src="https://user-images.githubusercontent.com/47109782/78381902-4e941480-75d6-11ea-96ed-2f131795fead.png">

**Comment by bpabiszczak** [comment]
Everything is as it’s supposed to be, encrypting consists of 2 keys, one is in the database and the other one in the file. Both are explicit just like SSL certificates or other security measures. In the case of the table with password history I can’t see any irregularities, the passwords are encrypted, and they are stored in order for the users not to set the same password twice.
