### ISSUE TITLE
[Question] Integration Web service - Applications

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#12815]
### Description

YetiForce 5.3

What means "_Paid functionality has been activated without purchasing the right product in the store. You violate the terms of the software license_" in **Integration Web service - Applications**

Are webservice and also customer portal subject to a charge?

**Comment by KatarzynaUlichnowska** [comment]
Hello, thanks for noticing. This message shouldn't be there. Paid functionalities are only in the Marketplace. We will have a look at it.

**Comment by snenko** [comment]
You scared me that I'm violating some license)
