### ISSUE TITLE
[Question] Filter in the invoice module showing the number of documents related to the record

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#12826]
**Is it possible to set an invoice display filter to show me if a document is attached to the invoice?**
Is it possible to create an item in the filter informing about the number of related documents?

I would like to get information that at least one document is added to a given record.
Unfortunately, the documents module is not displayed as a related module in filters, but it is actually linked because I can attach a file.

**Comment by Giorgos-Hellene** [comment]
i dont understand you. Could you explain it better with printscreen ?

**Comment by rskrzypczak** [comment]
At the moment, this is not possible.
This functionality requires crowdfunding.

**Comment by Giorgos-Hellene** [comment]
try it with a senario if you want.
I remember that invoices doesn't have document. The documents are on module Payments in. 
take a look to see if it suits you

**Comment by vdpawel** [comment]
@Giorgos-Hellene Thank you for your help, I tried to do it with triggers so that the field would update when I added a related document, but without success.
My guess is that I need a mechanism that would update the value of the variable, e.g. in the invoice module, so, after creating a relation to the document, the variable will be incremented or decremented when the document is deleted.
