### ISSUE TITLE
[Question] Is it possible for PDF documents to open in a browser window / tab instead of being saved to a file?

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#12828]
Is it possible for PDF documents to open in a browser window / tab instead of being saved to a file?
This would make it easier to preview the PDF before saving or sending by email.

**Comment by mariuszkrzaczkowski** [comment]
Comment out this line

https://github.com/YetiForceCompany/YetiForceCRM/blob/a8f0661b6e21aee5bff980d4daee571a82ff4e14/app/Pdf/YetiForcePDF.php#L545

**Comment by vdpawel** [comment]
Thank you very much for help!
[PL] Bardzo, bardzo, bardzo dziękuję za pomoc :)

**Comment by vdpawel** [comment]
Finally, I modified the indicated line to:
header("content-disposition: inline; filename=\"{$basename}\"");
