### ISSUE TITLE
[BUG][PL] Brak tłumaczenia w select

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1282]
Podczas edycji leada w polu brażna w przypadku braku wybrania opcji mamy "SELECT an Option"
![Error](https://cloud.githubusercontent.com/assets/3193498/8472385/15e80216-20a1-11e5-8dad-050c534621cf.png)

**Comment by rskrzypczak** [comment]
Błąd nie wystęuję w aktualnej wersji systemu. https://gitdeveloper.yetiforce.com
