### ISSUE TITLE
[Feature] To have public Account and private Contact

### ISSUE THREAD

**Issue by JasonChau1227** [YetiForceCompany/YetiForceCRM#12833]
### Describe the solution you'd like

To have Account set to public but Contact set to private. I know that it has a private field at Contact now but it makes the record only can be reached by the owner

### Is your feature request related to a problem? Please describe.
I want to have public Account and private Contact(Can see by higher role or special access) but it is not supported

### Describe alternatives you've considered

Make the existing private field in contact makes the record can be reached by higher role of the owner or special access.

### Additional context

However, If it is a bug inside my site that normally the private field works like what I want at other sites, please let me know.

**Comment by JasonChau1227** [comment]
Any update on this?

**Comment by vovpff** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=SharingAccess&parent=Settings&view=Index
