### ISSUE TITLE
Error during search processes in the calendar

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1283]
In calendar quick create window. When I'm logged in as user not an admin and select search icon in process I  get the error
EDIT: I get this same error when I choose "Employess" option in "Relation" field
![Error](https://cloud.githubusercontent.com/assets/3193498/8472641/41968c96-20a3-11e5-91e2-14ca5bb48103.png)
![PHP ERROR](https://cloud.githubusercontent.com/assets/3193498/8472675/856cde0c-20a3-11e5-95a3-2ac845ce26ad.png)

Edit: This same error occurs in Quick Create Contacts -> Members of -> Leads
![Members of](https://cloud.githubusercontent.com/assets/3193498/8473901/16e0cd2c-20ad-11e5-885b-2bc3ccdc1855.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed 7fe5886
