### ISSUE TITLE
[bug] Update Service Pack v4 not correctly registered

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12830]
# 🐞 bug report

### ⁉️ Describe the bug

I applied to most recent service pack, v4. The application succeeded, but at the end the screen shows that I applied v3 twice and required me to apply v4 again.

![update](https://user-images.githubusercontent.com/10230144/78579300-03297280-7831-11ea-80c6-c5966ec98647.png)

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.3.0 SP3
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by rskrzypczak** [comment]
Everything should be fine now, thx.
