### ISSUE TITLE
[Feature] Relations for Advanced Modules Inventory Lines

### ISSUE THREAD

**Issue by swsin84** [YetiForceCompany/YetiForceCRM#12839]
### Describe the solution you'd like

Hello, I like to list related advanced modules that contain parent entities in inventory lines from parent module.

Example: list from product module every invoice that contain specific product.. 

https://github.com/YetiForceCompany/YetiForceCRM/issues/9967#issue-422692150

this has been discussed before but not been implemented yet so i like to know if someone already implemeted this or there is any plan for yf team to implment in a near future, also how much gonna cost to do it for yf team to do it...

in a 5.1 instance of vtiger that i am using right now, this feature is implemented. only missing this feature to swap to yetiforce..T.T 

I like to write code by myself but i am not an expert at programming so, if anyone like to help to write this feature i think that the implementation is something like

1. Create a New Relation Files: modules/Vtiger/relations/GetAdvDependentsList.php to query u_yf_"module name"_inventory table

2. Need modify: modules/Vtiger/models/Relations.php to  add new relation

3. Add relation to table: vtiger_relatedlists

Thx!

**Comment by vovpff** [comment]
@swsin84 I has implemented this functionality by yourself
![image](https://user-images.githubusercontent.com/8545791/78668320-27de2280-78e3-11ea-967b-9f3706770e76.png)
This is buggy but works. Not for production.

**Comment by bpabiszczak** [comment]
The mechanism exists in the system. This requires testing and minor fixes.

**Comment by vovpff** [comment]
@bpabiszczak please describe how to test it?

**Comment by deepti4666** [comment]
> @swsin84 I has implemented this functionality by yourself ![image](https://user-images.githubusercontent.com/8545791/78668320-27de2280-78e3-11ea-967b-9f3706770e76.png) This is buggy but works. Not for production.

Hi there,

Have you managed to get this right?

The assets are pulling through to the product.

But I cannot see which quotes have a particular product.

**Comment by vovpff** [comment]
This is selfwritten relations mechanisms. You can implement them by yourself

**Comment by deepti4666** [comment]
> This is selfwritten relations mechanisms. You can implement them by yourself

How is this done - by mapping or workflow automation?
