### ISSUE TITLE
Calendar record list

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1284]
When I'm logged in as a user, not an administrator and I go to calendar list
![Error Trigger](https://cloud.githubusercontent.com/assets/3193498/8472896/5b027a76-20a5-11e5-924d-a9247fa4f75d.png)
 I get the  error
![Error](https://cloud.githubusercontent.com/assets/3193498/8472915/7d846884-20a5-11e5-9018-011ae886eaa3.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed 7fe5886
