### ISSUE TITLE
[bug] Can not translate custom module fields

### ISSUE THREAD

**Issue by elvissaba** [YetiForceCompany/YetiForceCRM#12844]
# 🐞 bug report

### ⁉️ Describe the bug
I have made custom module. Fields from custom module (except autogenerated field) can not be translated.

### 🔥 How to trigger the error
Make custom module and try to translate.

### 👎 Actual Behavior
Not working

### 👍 Expected Behavior
Functional translation for custom module

### 👷 Testing 

- [ x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![image](https://user-images.githubusercontent.com/20727670/78718234-3697fa00-7922-11ea-8d64-015b14af7b2f.png)

![image](https://user-images.githubusercontent.com/20727670/78718283-4c0d2400-7922-11ea-974f-1d8e3c58fb7e.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.3 sp4
| Web server (name and version)|		LightSpeed/Apache|
| PHP  |			7.3					|
| Browser (name and version)  | 	Firefox	|
| Operating System (name and version)  | 	Centos 7	|
| Database (name and version) | 		Mariadb (latest)|
| Service Pack version | 		SP4|

**Comment by vovpff** [comment]
@elvissaba click blue `Add translation` button!

**Comment by areksolek** [comment]
If you want to translate custom fields, you must add them manually. 
![proba](https://user-images.githubusercontent.com/25615135/78790792-4f9abc80-79af-11ea-9c0b-e98690cf467a.gif)

**Comment by elvissaba** [comment]
> 
> 
> @elvissaba click blue `Add translation` button!

Nice Workarround. Thnx.
