### ISSUE TITLE
[Question] 5.2 > 5.3 - reservations failed

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#12840]
Upgraded 52 to 53 but Reservations module stays as it was before. It will be enough to overwrite files, or database changes has been made?

**Comment by waran70** [comment]
Subsequent update fixed Reservation update BUT got issue, which make me scratching my bold head.
Adding new record to Reservation hanging with error:

2020-04-08 05:59:43.2274 [error] - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2385' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `u_yf_crmentity_label` (`crmid`, `label`) VALUES (2385, 'TEST RESERVATION RECORD')
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2385' for key 'PRIMARY' in /var/www/html/vendor/yetiforce/yii2/db/Command.php:1290

Tracking error bits leading me to nowhere. 

Tips?

**Comment by mariuszkrzaczkowski** [comment]
attach full logs

**Comment by waran70** [comment]
False alarm. It happen that workflow gets unusable after migration and that crippled module. 
Recreated WF and things goes as usual.
