### ISSUE TITLE
[Question] Is it possible to override a workflow task ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#12841]
Hi,

I'm playing with SMSNotifier module and try to understand why the new feature 'sending SMS to related records' is not working as expected.
#12812
 
As described [here](https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/loader-and-autoloader-of-files), I would like to use loader in order to use a custom workflow.

I have enabled the loading of custom files in /config/Performance.php
`public static $LOAD_CUSTOM_FILES = true;`

So basically, I would like to load my file in :
custom/modules/SMSNotifier/workflow/VTSMSTask.php
Instead of the original one in :
modules/SMSNotifier/workflow/VTSMSTask.php

It doesn't seem to work, orginal file is still loaded.

So I thought it's due to a hardcoded link in com_vtiger_workflow tasks, so I've tried to also load the following in
custom/modules/com_vtiger_workflow/tasks/VTSMSTask.php
This file point to my custom workflow :
`require_once 'custom/modules/SMSNotifier/workflow/VTSMSTask.php';`
instead of the original one in
modules/com_vtiger_workflow/tasks/VTSMSTask.php

Still no luck.

Do I miss something ?

Regards

**Comment by rskrzypczak** [comment]
In com_vtiger_workflow_tasktypes we have:
![image](https://user-images.githubusercontent.com/10221999/78747318-6cac9c80-7969-11ea-8562-b01c7e6b9b83.png)
