### ISSUE TITLE
[Feature] Send file and video call via chat

### ISSUE THREAD

**Issue by mdtuyen** [YetiForceCompany/YetiForceCRM#12847]
File transfer during chats is very important. Do you plan to integrate it into the next version?

As you know the current situation of online meetings is very important, video or voice chat is a good choice

**Comment by bpabiszczak** [comment]
https://jitsi.org/

**Comment by waran70** [comment]
in fact if that wont stab me a lot I will order such integration > #12709
I guess embedding not really possible, but some sort of connector creating conference + setting pass +  calendar entry with invitations - will be sweet. Looks like reservation would play vital role in such thing. Design, release for sell. Working solution for 100 euro in YF market would be reasonable.

**Comment by KatarzynaUlichnowska** [comment]
Version 5.4 will include full integration with Jitsi and that will include video calls, we are currently testing this solution and soon we will release more information about this integration. 
Regarding the file transfer, currently, we don't have a customer who would pay for chat development.
