### ISSUE TITLE
how to show the progress bar?

### ISSUE THREAD

**Issue by MixTecnico** [YetiForceCompany/YetiForceCRM#12855]
Should I enable any function for the progress bar?

![gitstable](https://user-images.githubusercontent.com/29989839/78969318-0ba5d580-7add-11ea-9ead-68b60b04e50e.png)

my yetiforce, it looks like this, version 5.3

![yeti](https://user-images.githubusercontent.com/29989839/78969601-aef6ea80-7add-11ea-8fcd-a8fa782525c5.png)

gitstable and gitdevelompent are shown, but not my installation

**Comment by vovpff** [comment]
You can go to edit fields and apply "show  preview in header" for picklists fields (eg. status) . There are should be 2 variants available value and progress var. Choose second.

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=HelpDesk
![image](https://user-images.githubusercontent.com/10198654/78970668-217dbf80-7b0a-11ea-9e92-da622f4722bd.png)

**Comment by MixTecnico** [comment]
gracias...
