### ISSUE TITLE
[Question] How to change site address path

### ISSUE THREAD

**Issue by jlumley99** [YetiForceCompany/YetiForceCRM#12854]
Hello, all.

I searched via Google and Github to find an answer to a basic question but couldn't find it ... also checked within YetiForce but had no luck.

I installed using cPanel's installer. I installed it to https://mysite.com/yeti/ and specified /yeti as the install path ... well, doing that means that all of my addresses show as:

https://mysite.com//yeti
(see the double slash there)

I would like to get that extra / removed. Is there a way to do this in the settings or by editing a text file? I don't want to delete and re-install the whole thing if I don't have to.

That's all for now. Thanks in advance!

**Comment by vovpff** [comment]
@jlumley99 config/Main.php
Try to play with system url.

**Comment by jlumley99** [comment]
AWESOME! Thank you! That was it!
