### ISSUE TITLE
Email OSS problem

### ISSUE THREAD

**Issue by kantino169** [YetiForceCompany/YetiForceCRM#12852]
Whenever I try to access my mailbox to configure it, I get this an access denied screen.
Also this is what my logs tell
[Thu Apr 09 10:11:36.927359 2020] [php7:notice] [pid 29495] [client 192.168.121.243:47042] PHP Notice:  Undefined variable: typeDb in /var/www/html/app/Db.php on line 174
[Thu Apr 09 10:11:36.927706 2020] [php7:notice] [pid 29495] [client 192.168.121.243:47042] PHP Notice:  Undefined index:  in /var/www/html/app/Utils/ConfReport.php on line 712

I'll appreciate the help with this

**Comment by areksolek** [comment]
Hello kantino169. What is your version of CRM ?

**Comment by rvyhmeister** [comment]
Version is 5.3.0. Just installed this week...

**Comment by rvyhmeister** [comment]
> Hello kantino169. What is your version of CRM ?

Version 5.3.0... installed clean this week....

**Comment by kantino169** [comment]
Hi, recently I discovered that the roundcube library is missing
<img width="1376" alt="Screen Shot 2020-04-12 at 7 11 57 PM" src="https://user-images.githubusercontent.com/30265449/79073874-a119b300-7cf1-11ea-9c9d-05ce4ae9abcc.png">
I don't know if this can be the cause of the problem but also whenever I try to update the library, it tells me again that it has not been downloaded, I download it and the cycle continues.
I have downloaded the library as zip and tried to install it from file and it tells me this
<img width="852" alt="Screen Shot 2020-04-12 at 7 17 26 PM" src="https://user-images.githubusercontent.com/30265449/79073968-49c81280-7cf2-11ea-9207-f6d32a47a56f.png">
I went inside the zip and it contains the en_US language.
What should I do?

**Comment by mariuszkrzaczkowski** [comment]
attach all logs

**Comment by rskrzypczak** [comment]
show me what you get when you ask the database `SHOW VARIABLES LIKE "version%"`

**Comment by kantino169** [comment]
> show me what you get when you ask the database `SHOW VARIABLES LIKE "version%"`

This is what I get
<img width="366" alt="Screen Shot 2020-04-14 at 6 08 17 PM" src="https://user-images.githubusercontent.com/30265449/79241038-2bd9e980-7e7b-11ea-96c0-8ee6b68caeca.png">

**Comment by kantino169** [comment]
I tried following this for the installationhttps://github.com/YetiForceCompany/YetiForceCRM/issues/7286#issuecomment-408243674
didn't work

**Comment by kantino169** [comment]
> I tried following this for the installationhttps://github.com/[/issues/7286](https://github.com/YetiForceCompany/YetiForceCRM/issues/7286)#issuecomment-408243674
> didn't work

I found the following coming up on the apache logs
PHP Warning:  ZipArchive::close(): Invalid or uninitialized Zip object in /var/www/html/app/Zip.php on line 127
The version of php I'm running is 7.4, is this a known problem?

**Comment by kantino169** [comment]
> attach all logs

These are the logs I currently have
[cron.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4486466/cron.log)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4486470/system.log)

**Comment by rskrzypczak** [comment]
Show us and verify your server configuration (`Software configuration/Logs/Server configuration`)
I suppose there might be errors.

Errors from your first comment result from the MySQL version. YetiForce can't correctly download information about the MySQL server on Ubuntu.
However, this applies only to reporting, so it shouldn't have a greater impact on the operation of the system.
Anyway, please correct the error_raporting configuration! You shouldn't have errors like `notice` / error_reporting E_ALL & ~ E_NOTICE /

**Comment by rvyhmeister** [comment]
Interesting that YetiForce has issues with Ubuntu... is there a better recommended distro?

**Comment by mariuszkrzaczkowski** [comment]
This is not a problem with Ubuntu, we have clients from Ubuntu and they have no problem
We prefer Debian, we will provide a docker soon

**Comment by vovpff** [comment]
@rvyhmeister there is no probkems with ubuntu if your server well-tuned

**Comment by simple-AMS** [comment]
I personanlly prefer CentOS and have NEVER had server related issues with any version of Yeti
