### ISSUE TITLE
[Feature] Use URL when location is URL

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12862]
### Describe the solution you'd like

Currently the system generates a link to Google map for the location of an activity.

In the current home-office world, the location of an activity is often a link (e.g. a link to a zoom.us meeting or webex or ...). It would be great if Yetiforce could, if the location of an activity is a link (if it contains, for example http:// or https://), open that link, rather than redirect the user to the location specified on Google maps.

This would impact at least CalendarActivitiesCurrent.tpl, RelatedActivities.tpl

### Is your feature request related to a problem? Please describe.
The feature would allow for web-based locations in addition to physical locations.

### Additional context

Here is one of the screens that would be affected (red circled area).

**Comment by diderich** [comment]
My workaround to address the issue:

`                                {if $ACTIVITY->getDisplayValue('location') !== ''}
                                    {if (strpos($ACTIVITY->getDisplayValue('location'), 'http:') !== false || strpos($ACTIVITY->getDisplayValue('location'), 'https:') !== false)}
                                        ,&nbsp;<a target="_blank" href="{($ACTIVITY->getDisplayValue('location'))}" title="{\App\Language::translate('URL', 'Calendar')}: {$ACTIVITY->getDisplayValue('location')}"><span class="fab fa-internet-explorer"></span></a>&nbsp;<a target="_blank" href="{($ACTIVITY->getDisplayValue('location'))}" title="{\App\Language::translate('URL', 'Calendar')}: {$ACTIVITY->getDisplayValue('location')}">{$ACTIVITY->getDisplayValue('location')}</a>
                                    {else}
                                        ,&nbsp;<a target="_blank" rel="noreferrer noopener" href="https://www.google.com/maps/search/{urlencode ($ACTIVITY->getDisplayValue('location'))}" title="{\App\Language::translate('Location', 'Calendar')}: {$ACTIVITY->getDisplayValue('location')}"><span class="far fa-map"></span></a>&nbsp;<a target="_blank" rel="noreferrer noopener" href="https://www.google.com/maps/search/{urlencode ($ACTIVITY->getDisplayValue('location'))}" title="{\App\Language::translate('Location', 'Calendar')}: {$ACTIVITY->getDisplayValue('location')}">{$ACTIVITY->getDisplayValue('location')}</a>
                                    {/if}
                                {/if}
`

**Comment by bpabiszczak** [comment]
Integration with Jitsi has been added in the new version
![image](https://user-images.githubusercontent.com/10197525/94624764-7e875080-02b7-11eb-8eb5-45117f327b08.png)
