### ISSUE TITLE
POST relation ServiceContracts and Assets

### ISSUE THREAD

**Issue by CesareD** [YetiForceCompany/YetiForceCRM#12866]
using the follwing RestAPI endpoint I'm able to GET all the related Assets to a ServiceContract with recordId=Cx
{{baseUrl}}/webservice/ServiceContracts/RecordRelatedList/Cx/Assets 

What is the RestAPI endpoint for (POSTing) or adding a relation between a ServiceContractId=Cx and an existing asset with recordId=Ay ?

Is there a way  to modify(PUT), Add(POST) or delete(DELETE) Assets related do a ServiceContract?

Thank's in advance.
CesareD

**Comment by CesareD** [comment]
Any Hint about the question?
if you follow this url https://www.vtiger.com/docs/rest-api-for-vtiger#/Endpoint
and go to 
"Add Related
Establish relation between two records."
how can add a relation between a ServiceContract Cx and an Asset Ay in YetiForce?
Do you have an example with Postman?

Can you suggest a starting point on the YetiForce's php code for examining the way i can add, or delete Assets related to a Service Contract or viceversa (add or delete a ServiceContract related to an Asset) ?

Thanks,
Cesare

**Comment by rskrzypczak** [comment]
https://doc.yetiforce.com/api/

**Comment by CesareD** [comment]
Hi rskrzypczak,

can you specify the endpoint in https://doc.yetiforce.com/api/ i should use for adding (via POST) a related Asset to a ServiceContract.

![ServiceContract](https://user-images.githubusercontent.com/6525652/81669684-d88d9380-9446-11ea-8feb-c8ec5ec6bf91.jpg)

![SC_Assets](https://user-images.githubusercontent.com/6525652/81669710-e04d3800-9446-11ea-9276-386fd00a12fb.jpg)


Thank you,
Cesare

**Comment by KatarzynaUlichnowska** [comment]
We do not provide programming advice on GitHub. We recommend buying the 5h package [https://yetiforce.com/pl/marketplace/wsparcie-development]. You will support the project, and in return, we will be able to spend 5 hours on programming for you.

**Comment by mariuszkrzaczkowski** [comment]
> What is the RestAPI endpoint for (POSTing) or adding a relation between a ServiceContractId=Cx and an existing asset with recordId=Ay ?
> 
> Is there a way to modify(PUT), Add(POST) or delete(DELETE) Assets related do a ServiceContract?

Currently, the API does not have this option


> if you follow this url https://www.vtiger.com/docs/rest-api-for-vtiger#/Endpoint

This is Vtiger, the API is pretty new
