### ISSUE TITLE
[Feature] Rounded photos of contacts

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12860]
### Describe the solution you'd like

The photo of the contact display in the header would look nicer if it were round, rather than rectangular. I would recommend adding the following style function in Main.css:

```
.o-detail__record-img img {
  border-radius: 50%;
  height: 5rem; }
```

**Comment by simple-AMS** [comment]
@diderich Hi there. Is the code addition that you recommended what you did personally to achieve the result you inquired about?

**Comment by diderich** [comment]
Yes, that is what I did. Add 'border-radius: 50%'. And it is only a suggestion to make the layout more compatible with current UI trends.

**Comment by simple-AMS** [comment]
@diderich Gotcha, thanks mate
