### ISSUE TITLE
[Question] How could we help building Wiki/documentation ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#12874]
Hi All,
First, I would like to say how thankful I am to YF Team.
IMO, Yetiforce is the best Open Source CRM I've ever seen, so powerful and so impressive with tons of new features on each version.
I would be more than happy to become a backer and support the project by giving money but unfortunately, I can't because my startup do not earn any money for now.
However, by then I can give time.
As you know, even if YF is easy to use and allow to do so many things using GUI, it lacks of good documentation. 
Why ? Probably because this is really time consuming and we could all understand that YF Team have to take care of and build features based on the needs of their clients first.
So at least I think community users like me (and I hope many others) could help by compiling and contribute building wiki/documentation based on all the informations available here, on YF Github.
I also think that this should be done here and stay under control of YF Team, not on an external site because the goal is to give back to YF, help new users to find resources and so reduce already answered recurring questions here.
So the question to YF Team is : why not using Github wiki and let community users contribute ? 
If you think it's a bad idea, how could we help when we have no money to support the project (for now) ?
Regards and once again, thanks again for this awesome software.

**Comment by diderich** [comment]
Good idea! In addition having a repository where users could offer reports that they have customized and summary block code would be great.

**Comment by bpabiszczak** [comment]
Documentation:
1. At the moment, we aren't planning to use wiki/GitHub, it would require commitment and numerous changes and we don't have time for that.
2. Unfortunately, creating documentation is complicated, nearly every place in the system requires either consultation with a developer or verification of how something works. Recently, when I was analyzing the user module, I handed over 10 fields to the developers to verify whether these fields are still used and why they don't work as I think they should. The amount of work that needs to be invested in it is several times greater than in the case of translations. Unfortunately, the current Community isn't engaged enough and I think the transfer of documentation to the wiki wouldn't have measurable benefits.
3. The good news is that I am currently working on documentation. It is going to change, just like the descriptions/titles/tabs in the system.


How you can help us:
First of all, recommend YetiForce on the pages below
https://www.capterra.com/p/159123/Yetiforce/
https://www.g2.com/products/yetiforce-sp-z-o-o-yetiforce-crm/reviews
https://reviews.financesonline.com/p/yetiforce-crm/#user-review
https://www.softwaresuggest.com/yetiforce-crm
https://www.gartner.com/reviews/market/sales-force-automation/vendor/yetiforce/product/yetiforce-crm?pid=69524
https://www.trustradius.com/products/yetiforce-crm/reviews
https://crozdesk.com/customer-service-crm/crm-software/yetiforce

Secondly, write something good about us on social media.

Thirdly, donate through the Marketplace. I can't believe you can't support us with at least 1 Euro a month, which is the equivalent of one beer. Every day, our system is installed by 50 companies, if at least one of them supported our project with the amount of 10 Euro/month , we would already have €100,000/month for support and help for users.

**Comment by apcloic** [comment]
@bpabiszczak 
Thanks. 
Regarding point 2, I still think that community contributions to YF documentation could be useful, more as an addition, something complementary with the official one but I understand you when you write that we are not engaged enough.
For the recommendation, sorry to say but except Capterra I don't think that those sites are really popular in France. 
Maybe a good and detailed review written in french could be more helpful because unfortunately, YF is not very well-known in my country.
For the donation, of course you're right, I can give 1€/month for sure but it will come from my own personal money, not from my business...so Ok, it's better than nothing and I will do it today.
Regards,

**Comment by ggriffin** [comment]
@apcloic There's nothing preventing the community from creating a repo for sharing sample code and documentation.

AWS certainly has a lot more resources, but I have enjoyed their [documentation repos](https://github.com/awsdocs).

A Discord or Gitter community could also be created for the benefit of sharing experiences. Vue.js has a [Vue Land](https://vue.land/) community, for example.

**Comment by apcloic** [comment]
@ggriffin Yes, I know I could create a repo but as I wrote in my first post, I think it's better to help here, in the official YF repo.
I'm glad to be a *tiny YF backer now, I did through [OpenCollective](https://github.com/YetiForceCompany/YetiForceCRM/issues/10839). I suppose it's better through YF marketplace but sorry to say, I don't like Paypal :)
@bpabiszczak My previous job was sysadmin so I have some skills regarding server configuration I could write here a detailed tutorial for some kind of perfect Ubuntu Server setup for Yetiforce including SSL config (Let's Encrypt), Postfix (with Spf, Dkim & Dmarc).
I think it could be useful as YF requirements are a little more complicated than other software.

**Comment by blu-IT** [comment]
I would contribute to documentation.

**Comment by saosangmo** [comment]
Hello,
I am translating Yetiforce into Vietnamese language and then I want to write a simple document for Vietnamese community.
Like this: https://saosangmo.gitbook.io/yetiforcecrmvn/

I wonder if it is legal for me to maintain a Vietnamese document?
Thank you for a great software.

**Comment by apcloic** [comment]
@saosangmo 
Hi, I think Crowdin is the right place regarding translation contributions.
https://crowdin.com/project/yetiforcecrm
