### ISSUE TITLE
Unable to install , plugin not found:mysqlnd

### ISSUE THREAD

**Issue by fireon89** [YetiForceCompany/YetiForceCRM#12877]
Hey, 

I am a core hardware person trying to install this CRM software and was unable to complete is it showed an error: "Required PHP extension not found: mysqlnd "  

I have zero experience in scripts and coding. It will be of great help if anyone can help me to fix this.

**Comment by mariuszkrzaczkowski** [comment]
![Uploading github.jpg…]()

**Comment by fireon89** [comment]
Hello Mr. mariuszkrzaczkowski, 
Somehow the description explaining the issue went missing on the previous post. I have made it available now and mentioning that here onceagain : 

I am a core hardware person trying to install this CRM software and was unable to complete is it showed an error: "Required PHP extension not found: mysqlnd "

I have zero experience in scripts and coding. It will be of great help if anyone can help me to fix this.

**Comment by mariuszkrzaczkowski** [comment]
https://www.google.com/search?q=install+php+mysqlnd
