### ISSUE TITLE
[Feature] Copy filters

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12873]
### Describe the solution you'd like

Add a functionality "(+) Copy Filter" in 'Filters - Configuration' and 'Filters List' that makes a copy of an existing filter.

This would be useful to create multiple filters that display identical fields but differ in the selection conditions and/or availability.

### Is your feature request related to a problem? Please describe.
The problem (if one can call it problem) is the lost time from creating similar filters over and over again.

### Describe alternatives you've considered

Currently a filter with identical fields and different conditions, for example, has to be recreated manually. When doing this for multiple filters, e.g., different filters for leads with different status or assigned to different roles, is tedious as the filter has to be re-created each time manually, selecting all fields and putting them in the required order.

**Comment by apcloic** [comment]
@diderich 
Hi, this feature is already available in YF. 
However, I don't remember if it required to be activated in config file.
Regards

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/79188358-1931c700-7e1f-11ea-80f0-3a2b495db5c6.png)
