### ISSUE TITLE
mapping from one module to another

### ISSUE THREAD

**Issue by MixTecnico** [YetiForceCompany/YetiForceCRM#12872]
To map a field, for example from employees to incidents, do you have to do something specific, or should it work when configuring mapping?

**Comment by vovpff** [comment]
Pls give mode ritailed description of your task

**Comment by MixTecnico** [comment]
it is a question to know if it is possible

**Comment by vovpff** [comment]
I don't undersrand what do you want. Looks like you need mapping or data from related module field. If you give detailed description chances to get right solution.

**Comment by MixTecnico** [comment]
example I have a field in the incidence module, and I would like to update these fields when creating an employee ... or vice versa

I tried with field mapping but nothing happens ...

**Comment by vovpff** [comment]
In case automatic update you need to use workflows (update relatred record) from admin panel and selfwritten handlers.

**Comment by KatarzynaUlichnowska** [comment]
Hello @MixTecnico! Did @vovpff answer your question?
