### ISSUE TITLE
[Question] How sold service renewal is supposed to work?

### ISSUE THREAD

**Issue by zazy** [YetiForceCompany/YetiForceCRM#12875]
I'm not able to understand how renew of renewable service is supposed to work. I create a service and set it as **Renewable**. Then I create a _Sold service_ instance for a client. Now suppose the service should be renewed. How to do it? The **Renew** field in the _Sold services_ record is always disabled and I'm not able to change it's value so I can't assign a renewal status to the instance. Any advice?

**Comment by simple-AMS** [comment]
@zazy I would just create your own custom field for the status you need and disable the one that is pre-filled and not changeable. It's a workaround that I have used in several modules throughout the years. Not ideal, but it should get the job done.

**Comment by zazy** [comment]
Thankyou @acsinsurancegroup  for your reply. I know I can add a custom field but if there is a dedicated field that can't even be modified it let me think that there is some sort of mechanism to let the value of that field to be changed somehow. 
This is one of lots of reasons that makes me feel that YetiForce is unreliable. I'm an IT consultant and a software developer and I'm studying several crm software to let my clients have a good software to work with. CRM is not a wordprocessor that you can change once you found it's not as good as you need. CRM is that king of software that you will live with for long time so it can't leave my customers with that feelings of unreliability. YetiForce is a wonderful piece of software but with too many inconsistencies that makes me look at other solutions. For now I have installed also EspoCRM and SuiteCRM. The first one is great and have a really clean UI but is more expensive than Salesforce. The other is full of bug...

**Comment by bpabiszczak** [comment]
You should write a script that will automatically create sales opportunities.
