### ISSUE TITLE
create mail from incidents button does not work?

### ISSUE THREAD

**Issue by MixTecnico** [YetiForceCompany/YetiForceCRM#12880]
![mail_link](https://user-images.githubusercontent.com/29989839/79132392-9f4b0080-7d80-11ea-829a-e1119942dade.png)

the icon to send mail from incident does not work, there is a way to enable it to be able to load a template and to load the correct data of the incident!

version yeti 5.3

**Comment by rskrzypczak** [comment]
Yes.
![image](https://user-images.githubusercontent.com/10221999/79189760-e2f64680-7e22-11ea-812c-9f9259435fcc.png)
and [Email templates](https://gitdeveloper.yetiforce.com/index.php?module=EmailTemplates&view=List&mid=146&parent=76)

**Comment by MixTecnico** [comment]
it is activated it still does not work

**Comment by rskrzypczak** [comment]
Have you downloaded the roundcube library?
check: Software configuration/Standard modules/Modules – Installation

**Comment by MixTecnico** [comment]
Yes of course

where could I solve it, any ideas

**Comment by bpabiszczak** [comment]
This has to be checked by the developer on your server.
