### ISSUE TITLE
Project Gantt chart not show Milestones and Tasks

### ISSUE THREAD

**Issue by lucnham** [YetiForceCompany/YetiForceCRM#12882]
Hello,
I'm a PHP developer, I spent a lot of time learning about the Yetiforce - A great CRM system.
I am having trouble with the Project module. Milestones and Tasks of Projects not show although I have tried configuration in many ways. I'm not sure if I am missing something. Can anyone give me advice.
Thanks,
![gantt chart](https://user-images.githubusercontent.com/45326848/79176456-77b07280-7e2a-11ea-97f6-2410af95a8ec.jpg)

**Comment by adudekyeti** [comment]
Hi,
Could you reproduce this bug on [gitstable](https://gitstable.yetiforce.com/) or [gitdeveloper](https://gitdeveloper.yetiforce.com/)?
I try to figure it out, but in my opinion everything is working fine:

![image](https://user-images.githubusercontent.com/39482453/79206209-4bebb780-7e3f-11ea-8510-adcfa468449e.png)

**Comment by lucnham** [comment]
I tried recreating it on [gitdevelop ](https://gitdeveloper.yetiforce.com/index.php?module=Project&view=Detail&record=4146&mode=showGantt&tab_label=Gantt) and it worked fine. I have not been able to determine what is causing the problem in my site.
Basically, my site is installed auto from Softaculous since version 5.2.0 with Gantt chart has the same problem. I have upgraded to the latest version of 5.3.0 but nothing has changed.

**Comment by lucnham** [comment]
> Hi,
> Could you reproduce this bug on [gitstable](https://gitstable.yetiforce.com/) or [gitdeveloper](https://gitdeveloper.yetiforce.com/)?
> I try to figure it out, but in my opinion everything is working fine:
> 
> ![image](https://user-images.githubusercontent.com/39482453/79206209-4bebb780-7e3f-11ea-8510-adcfa468449e.png)

I tried recreating it on [gitdevelop ](https://gitdeveloper.yetiforce.com/index.php?module=Project&view=Detail&record=4146&mode=showGantt&tab_label=Gantt)and it worked fine. I have not been able to determine what is causing the problem in my site.
Basically, my site is installed auto from Softaculous since version 5.2.0 with Gantt chart has the same problem. I have upgraded to the latest version of 5.3.0 but nothing has changed.

**Comment by perronmedia** [comment]
Having the same problem on my greengeeks reseller hosting. Works ok with alternate host.

Could be down to server configuration.

**Comment by MexasPT** [comment]
Having the same problem in 4 different hosting resellers.
