### ISSUE TITLE
Need to perform SLA Actions or Tasks on Tickets

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#12889]
We are able to create SLA on ticket. But we are not able to perform any action or task before and after SLA violation of tickets. We have to perform an action against to SLA violation of the ticket.

![Yetisla](https://user-images.githubusercontent.com/47585969/79186086-4ccc1b80-7e36-11ea-8e3d-3bc9c5c0a176.PNG)

I need to send an email alert before SLA violation (Email alert) and escalate all tickets after SLA  violation (Email alerts and Re-assign). How can we get this functionality in the SLA module?. Please check the below reference.
![high](https://user-images.githubusercontent.com/47585969/79192158-cfa8a280-7e45-11ea-97ef-6fd0d40e51a2.jpg)

**Comment by bpabiszczak** [comment]
This can be done by a developer.
