### ISSUE TITLE
[bug] syntax error, unexpected ''=>1586540401];' (T_ENCAPSED_AND_WHITESPACE)

### ISSUE THREAD

**Issue by namaneko** [YetiForceCompany/YetiForceCRM#12881]
### ⁉️ Describe the bug
Hello. I did a search and saw that someone else encountered the same error.

I have fresh installation of YetiForce, maybe only two days old. I have added one record to it. I noticed that the map module wasn't working so I clicked the gear/settings icon at the top right corner and it took me to the settings page but in the right frame, it gives me this error:

syntax error, unexpected ''=>1586540401];' (T_ENCAPSED_AND_WHITESPACE)

I am not able to access/change any of the settings from this space. 

It occurs at this URL:
https://yeti.domainname.com/index.php?module=Vtiger&parent=Settings&view=Index#

### 🔥 How to trigger the error

Click the settings icon at top right corner from any part of Yeti.

### 👎 Actual Behavior

syntax error, unexpected ''=>1586540401];' (T_ENCAPSED_AND_WHITESPACE)

I am not able to access/change any of the settings from this space. 

### 👍 Expected Behavior

Settings/control panels are accessible.

### 👷 Testing 
- [X ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ X] I confirm that I tested it at https://gitdeveloper.yetiforce.com

No video because I don't have anywhere to upload them to.

### 📷 Screenshot of configuration

Can't click the desired button but I can access whatever via FTP. Please let me know what you need!

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Sent!

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  LATEST
| Web server (name and version)|	Apache 2.4.41	| 
| PHP  |				7.2.29				|  7.2.29
| Browser (name and version)  | 	Mozilla Firefox LATEST	| 
| Operating System (name and version)  | Manjaro LATEST 		|
| Database (name and version) | 	MySQL 10.3.22	|
| Service Pack version | 	?	|

### ❓ Additional context
I believe that's it. Happy to upload/send over whatever else is needed. Thanks!

### ❗️ Inform the community if you solve the problem
[pending]

**Comment by lucnham** [comment]
In my experience, after updating some cron records there will be a wrong syntax. You can try deleting the app_data/cron.php file. Don't worry you will lose it, this file will automatically be created on the next Cron job.

**Comment by MixTecnico** [comment]
asi soluciono mucho de mis errores!

**Comment by MixTecnico** [comment]
> In my experience, after updating some cron records there will be a wrong syntax. You can try deleting the app_data/cron.php file. Don't worry you will lose it, this file will automatically be created on the next Cron job.

asi soluciono mucho de mis errores!

**Comment by namaneko** [comment]
That did not resolve the issue.

**Comment by namaneko** [comment]
> In my experience, after updating some cron records there will be a wrong syntax. You can try deleting the app_data/cron.php file. Don't worry you will lose it, this file will automatically be created on the next Cron job.

Appreciate the tip. That did not resolve the issue.

**Comment by vovpff** [comment]
@namaneko try php 7.3.

**Comment by mariuszkrzaczkowski** [comment]
you have sent incorrect logs,
show screenshot of configuration and show what's in php error log (just check if you have it turned on)

**Comment by namaneko** [comment]
@vovpff Switched to 7.3 and that didn't help either.

I have two separate installs of Yeti on two different servers and now both are showing the same error message though with different digits (1586964602 on the other installation).

@mariuszkrzaczkowski I can't show a screenshot of configuration because the error message is preventing me from loading anything in the control panel. Which debugging should I enable? 

This what I'm seeing when trying to access the system settings:

![Screenshot from 2020-04-20 12-17-56](https://user-images.githubusercontent.com/51968355/79774277-9a49fc00-8300-11ea-808e-cd3873bd1e4d.png)

**Comment by mariuszkrzaczkowski** [comment]
do it this way:
1. enable and attach all logs, description here https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/debugging#quick_start, it is important to enable error logs for PHP and CRM
https://github.com/YetiForceCompany/YetiForceCRM/issues/9261#issuecomment-458959230

2. Delete the app_data/cron.php file and go to __crm_url__/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65
3. Send us the app_data/cron.php file
4. check exactly what version of PHP you have in CLI, e.g. script with code and call it from CLI
`
<?php
echo PHP_VERSION;
`
