### ISSUE TITLE
[Feature] [PL] Pole 'Kontynuacja na kolejnej stronie' w dokumentach PDF / 'Continue on next page' field in PDF documents

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#12898]
## 🚀 feature request

Dodanie funkcjonalności na stronach w edytorze PDF, która umożliwia stawienie napisu "kontynuacja na kolejnej stronie", w sytuacji gdy ilość stron przekracza jedną stronę, a sam napis nie byłby dodawany na ostatniej stronie.

**Comment by rskrzypczak** [comment]
example please

**Comment by vdpawel** [comment]
![Adnotacja 2020-04-15 155029](https://user-images.githubusercontent.com/62466142/79345050-e5df5d00-7f30-11ea-8538-ee925d8446c7.png)

Czy jest jakaś zmienna, którą informuje o numerze aktualnej strony, którą można wykorzystać w TextParser?

(przepraszam za mało szczegółowy opis, przez przypadek opublikowałem zgłoszenie przed napisaniem całości)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/12110#issuecomment-591267560

> You can use :
Page {p}/{a} or Page $(custom : CurrentPage)$/$(custom : AllPages)$
Są dostępne w polu "Zmienne dodatkowe" przy tworzeniu szablonu PDF. 

Jeżeli chciałbyś funkcję warunkującą czy wyświetlić np. komunikat 'Kontynuacja na kolejnej stronie', to nie ma.

**Comment by vdpawel** [comment]
Dziękuję za odpowiedź. 
Dlatego moją propozycją na nową funkcjonalność jest dodanie nowego placeholderu, np. {k}, który byłby interpretowany przez generator PDFów i po spełnieniu warunków, zamieniany na napis "Kontynuacja na kolejnej stronie", podobnie jak działa wstawianie numerów stron.

**Comment by bpabiszczak** [comment]
Pomysłów mam 100 dziennie ;) Na razie wrzucam do zamkniętych, jak będą środki z crowdfundingu to można powrócić do jakiś starych tematów i je zrealizować.

**Comment by vdpawel** [comment]
Dziękuję za odpowiedź, okazało się, że właściwie podałem przepis jak to zrobić i tym sposobem udało mi się zrealizować tą funkcjonalność. 
Dodałem kolejny placeholder "{k}" wraz z odpowiednimi warunkami, który zmienia "{k}" na "Ciąg dalszy na kolejnej stronie".

`				if (mb_stripos($child->getTextContent(), '{k}') !== false) {
					$pageNumber_k = $this->document->getCurrentPage()->getPageNumber();
					$pages_k = $this->document->getCurrentPage()->getPageCount();
					if (($pages_k > 1) and ($pageNumber_k != $pages_k)) {
						$child->setText(preg_replace('/{k}/ui', 'Ciąg dalszy na kolejnej stronie', $child->getTextContent()));
					}
					else {
						$child->setText(preg_replace('/{k}/ui', '', $child->getTextContent()));
					}
					$child->getClosestByType('BlockBox')->layout();
				}
`
