### ISSUE TITLE
Cron job fails

### ISSUE THREAD

**Issue by TomReed123** [YetiForceCompany/YetiForceCRM#12902]
Setup new installation and cron log reports:
<br />
<b>Parse error</b>:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in <b>/home1/datacenter/yf.winecountry-bbq.com/cron.php</b> on line <b>91</b><br />

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/79535162-edac1800-807c-11ea-9120-dc37f915bd02.jpg)

**Comment by rskrzypczak** [comment]
You probably have the wrong PHP version
you must have at least version 7.2

**Comment by TomReed123** [comment]
https://yf.winecountry-bbq.com/phpinfo.php = php 7.2.26

**Comment by TomReed123** [comment]
Looking at the php code around line 91, it looks like there is an error in the error code.

**Comment by mariuszkrzaczkowski** [comment]
check php versions for CLI
no screenshot of configuration verification, I close
