### ISSUE TITLE
[bug] ModComments: number of answers and reply buttons

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#12906]
# 🐞 bug report

### ⁉️ Describe the bug

Comments module functionality became better but now in 5.3 reply and view replies buttons hidden under wrench key button. This is uncomfortable for users because you need ewery time click to wrench to reply or see replies

5.2

![image](https://user-images.githubusercontent.com/8545791/79544689-0fff5f00-8098-11ea-93b5-b77365198176.png)

5.3

![image](https://user-images.githubusercontent.com/8545791/79544776-332a0e80-8098-11ea-912b-3e9e68c27ef8.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski any suggestions?

**Comment by vdpawel** [comment]
Is it possible to return to the previous version of the comments module?

I tried to copy the tpl files from the 5.2 version but without any changes. Perhaps the new configuration is in js.
