### ISSUE TITLE
Error when selecting a record

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1290]
I'm logged in as a user, not an administrator. And I selecting a record in Leads in related modules -campaings
![Error trigger](https://cloud.githubusercontent.com/assets/3193498/8474119/6fe371f8-20ae-11e5-9121-b479ad88df71.png)
The error: 
![rowcount](https://cloud.githubusercontent.com/assets/3193498/8474170/b08e22ca-20ae-11e5-9a1c-ff89822d696d.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/7fe5886416ff27378742f253b38b404cb3b626bb
