### ISSUE TITLE
[bug] PDF brak funkcji custom : GrossAmountInWords

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#12914]
Witam,
w wersji: YetiForce CRM 5.3 Service Pack v4 brak funkcji custom : GrossAmountInWords
Nie ma jej do wyboru w zmiennych dodatkowych przy edycji szablonu, a po wpisaniu "z ręki" system wstawia puste miejsce. W wersji YetiForce CRM 5.2 Service Pack v19 wszystko działa bez problemu.
Jak mam wstawić teraz kwotę słownie?
Sprawa dosyć pilna bo brakuje tej informacji teraz na fakturach...

**Comment by Sall2** [comment]
Sprawdziłem, po dokumentach, że problem pojawił się po aktualizacji do 5.3

Brakuje też kilku innych zmiennych np.: daty wystawienia dokumentu

**Comment by rskrzypczak** [comment]
Nie jest to błąd. Ta opcja została celowo usunięta z systemu.
https://github.com/YetiForceCompany/YetiForceCRM/issues/10315#issuecomment-591341439
