### ISSUE TITLE
[Feature] Restrict access to ModTracker records about creation of related records

### ISSUE THREAD

**Issue by svdaru** [YetiForceCompany/YetiForceCRM#12915]
Hello!

For records that users have shared access to, it is possible to  see that other users added Records at Related modules (comments, phone calls, etc.). In case when access to related record is not permited by any rule (hierarchy, group, share, etc.) this history record can be compromising.

The feature is to make it is possible to show ModTracker relation records only about those related records, that actual user has access to.

**Comment by bpabiszczak** [comment]
The user cannot see or access to the related record.

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/93430435-f5d5e100-f8c2-11ea-85bd-ca466307256e.png)

**Comment by bpabiszczak** [comment]
We are not planning to change this at the moment.
