### ISSUE TITLE
Unusual Bandwidth Usage

### ISSUE THREAD

**Issue by mmsayeed** [YetiForceCompany/YetiForceCRM#12928]
Hello,

I have a yetiForce Installation. But this consume most of the bandwidth of the server. 
For example, On 20 April it consumes 2 GB of bandwidth.

The awstats shows Most of this are NON-HTTP Visits.

**Comment by mariuszkrzaczkowski** [comment]
CRM only works over HTTP / HTTPS, so it is not CRM
