### ISSUE TITLE
[Security] Certificate SSL

### ISSUE THREAD

**Issue by draboluk** [YetiForceCompany/YetiForceCRM#12922]
Hi,

Company website is in domain with a certificate ssl (www.name.com).
I created a new catalog and installed the YetiForce (www.name.com/catalog/).

How to force ssl certificate by YetiForce?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/a76c39d2d040c222c96059e0273525d95b27bb0b/config/Security.php#L111

**Comment by draboluk** [comment]
public static $forceHttpsRedirection = true; 

result:
"ERR_TOO_MANY_REDIRECTS"

when:
public static $forceUrlRedirection = false;
works only "dashboard", other url "Illegal request"

**Comment by mariuszkrzaczkowski** [comment]
config/Main.php
![image](https://user-images.githubusercontent.com/10198654/79716928-6d81ee80-82d8-11ea-8ae1-ebc8d5ddbfe1.png)
