### ISSUE TITLE
[Question] Grant modify access only to assigned user

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12921]
### Description

Is there a possibility to configure the system in such a way that only the person a record is assigned to can modify it?

I would like users to create 'Time Control' records assigned to themselves such that only they can modify them.

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/93410766-e3937d00-f899-11ea-8740-66ae3e2f9001.png)
