### ISSUE TITLE
[bug] Error message when posting a comment in tickets module

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#12925]
I get this error when posting a comment in tickets module in 5.3.0 service pack 4. Looks like it's only happening with ticket comments. Please see below.

![79701024-c5ccd800-8267-11ea-8f14-b2b2e0515851](https://user-images.githubusercontent.com/38298689/79773674-bdc07700-82ff-11ea-9a3e-114af316a008.png)

**Comment by acoolov** [comment]
Anyone?

**Comment by vovpff** [comment]
@acoolov pls modify 4.3 sp4 to 5.3 sp4 at first post.
vtiger_senotesrel table? What is it? Correct name of table with comments should be vtiger_modcomments (modcomnentid, commentcontent columns for example). This is fresh 5.3? Or updated?

**Comment by acoolov** [comment]
Done. Sorry about that.

**Comment by acoolov** [comment]
It does it on both 5.3 and 5.3 service pack 4 update.
I installed this instance of Yeti through one click Softaculus installation.

**Comment by mariuszkrzaczkowski** [comment]
check on https://gitstable.yetiforce.com/ and https://gitdeveloper.yetiforce.com/

**Comment by acoolov** [comment]
I just installed it on Plesk + Softaculus and the issue is not present anymore.
