### ISSUE TITLE
[Question] Setting the displayed columns when selecting a record from a dependent module

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#12936]
After selecting the button to indicate the record from the dependent module (in this case: Opportunity), 
![obraz](https://user-images.githubusercontent.com/62466142/79928748-17ca5500-8444-11ea-9d32-ad3ec9fb657f.png)

is it possible to choose the columns that are displayed on the list?

![obraz](https://user-images.githubusercontent.com/62466142/79928826-519b5b80-8444-11ea-9688-4c175b7ded4d.png)

I tried to change it in filters, but without success.

**Comment by vovpff** [comment]
modules/SSalessProcess/SSalessProcess.php

**Comment by rskrzypczak** [comment]
Fields from the default filter in Opportunities module (list view)
