### ISSUE TITLE
Missing translation. Contacts - Transfer Ownership

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1293]
In concats in transfer ownership is missing translation 
![Missing translation](https://cloud.githubusercontent.com/assets/3193498/8474552/2b752694-20b1-11e5-915a-457402980a8a.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/da97a3665e7bc3d29718d6a48144bf0e188df63c
