### ISSUE TITLE
[bug] Can't save profile

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#12939]
# 🐞 bug report

### ⁉️ Describe the bug

I need to add access for some Role to module.For example ideas:

![image](https://user-images.githubusercontent.com/8545791/79973756-c7cdab80-84a0-11ea-887c-c30f5f163b1e.png)

After click Edit and clicking 4 check-boxes and saving profile not saved with new access parameters.

How to understand what is wrong?

![ConfReport_200422](https://user-images.githubusercontent.com/8545791/79974983-e2088900-84a2-11ea-9db1-23b30a1593e4.png)

**Comment by rskrzypczak** [comment]
run:
`\App\Db\Fixer::baseModuleTools();
\App\Db\Fixer::baseModuleActions();
\App\Db\Fixer::profileField();`
and check again

**Comment by vovpff** [comment]
@rskrzypczak how to run it?

**Comment by rskrzypczak** [comment]
You have many options, but the easiest way is edit index.php in root directory

> require __DIR__ . '/include/main/WebUI.php';
> require __DIR__ . '/include/RequirementsValidation.php';
> // this add
> \App\Db\Fixer::baseModuleTools();
> \App\Db\Fixer::baseModuleActions();
> \App\Db\Fixer::profileField();
> echo 'end'; exit;

:)

**Comment by vovpff** [comment]
@rskrzypczak after adding this and F5 on my system I get 500 error. After that I commented your code and refreshed page. It works. Profile saving also works.

What is the porblem?

**Comment by rskrzypczak** [comment]
Apparently, you once had an error saving the profile and there were gaps in the database. These functions complement them.

**Comment by vovpff** [comment]
@rskrzypczak error 500 - normal condition?
