### ISSUE TITLE
Disable Section like Accounting?

### ISSUE THREAD

**Issue by andrewteg** [YetiForceCompany/YetiForceCRM#12941]
I have gone into "System Settings => Modules" and disabled all the Accounting modules (Invoices, Payments, etc) and I expected to see the "Accounting" header disappear but it is still there.

Is there a way or trick to getting that to not show up since there are no modules, and it simply just changes the + and - when I click on it now.

Thanks,
Andrew

**Comment by rskrzypczak** [comment]
Remove from menu (Software configuration/Standard modules/Menu - Configuration)
