### ISSUE TITLE
Automated Email Marketing Campaigns?

### ISSUE THREAD

**Issue by andrewteg** [YetiForceCompany/YetiForceCRM#12940]
Is there a way to add prospects to a campaign and have them be automatically emailed a series of emails?  I'm looking for something like the basic functinoality of a phpList or MailChimp where a user can be added and emailed a series of "welcome" emails over a few weeks.  I've looked around for drip campaign or newsletter and seen a few things like https://github.com/YetiForceCompany/YetiForceCRM/issues/7515 but nothing recent and could not tell what the current status of email marketing was for YetiForce.

Thanks for any clarifications.

**Comment by bpabiszczak** [comment]
There is no such functionality. You need to add workflows.
