### ISSUE TITLE
[bug] Roundcube losowy brak przycisków wyboru kontrahenta, kontaktów itp

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#12942]
Witam,
mam taki problem, że czasami są, a czasami nie ma przycisków wyboru kontrahenta, kontaktów itp przy tworzeniu wiadomości w roundcube. Jeśli ich nie ma, to nie działa też wyszukiwanie adresów email po nazwie, tzn. system nie podpowiada adresów z kontaktów. Jest na to jakaś rada?
![poczta](https://user-images.githubusercontent.com/58420665/80082734-0fae0a80-8555-11ea-9e11-750554a69cb7.jpg)

**Comment by svdaru** [comment]
I do not speak your language, but translator says that i have the same problem.
While debugging i discovered that \App\User::getPrivilegesFile($userId) at \App\Privilege returns Null, that is why is \App\Privilege::isPermitted at yetiforce rouncube plugin does not permit adding Modules at composing interface. At the moment i see that there is no variables (user_id, baseuserid) at Session, witch are demanded for getPrivilegesFile. And it happens i dont know
![image](https://user-images.githubusercontent.com/13922774/80107431-b9a48b80-8583-11ea-97d9-d3e5c0c8d975.png)
![image](https://user-images.githubusercontent.com/13922774/80107887-56ffbf80-8584-11ea-9e2f-45e4eb3eb3d2.png)

**Comment by bpabiszczak** [comment]
wersja yetiforce?

**Comment by svdaru** [comment]
YetiForce CRM 5.3 Service Pack v4

> wersja yetiforce?

**Comment by bpabiszczak** [comment]
Czy problem występuje na gitstable i gitdeveloper?

**Comment by svdaru** [comment]
> Czy problem występuje na gitstable i gitdeveloper?

it seems it doesn't. i am not able to reproduce problem at gitstable

**Comment by svdaru** [comment]
gitdeveloper also doesn't have this problem

**Comment by Sall2** [comment]
5.3 service pack 4

**Comment by svdaru** [comment]
as i see something wrong with auto login functions

**Comment by Sall2** [comment]
> as i see something wrong with auto login functions

Yes, i have issues with autologin myself.

**Comment by svdaru** [comment]
it is all about that rouncube and crm have different session drivers.

**Comment by svdaru** [comment]
It is all about that rouncube and crm having different session drivers.
The problem is that $_SESSION['crm']['id'] is set only with autologin functions.  I've made a pull request at lib_roundcube to fix it.
[https://github.com/YetiForceCompany/lib_roundcube/pull/48](https://github.com/YetiForceCompany/lib_roundcube/pull/48)

**Comment by Sall2** [comment]
Now it gets really weird, when i check this "default" option i have no buttons and autologin not works, when unchecked i have it all (buttons and autologin)
<img width="960" alt="poczta2" src="https://user-images.githubusercontent.com/58420665/80142819-161ba100-85ac-11ea-8b59-49fbddf7e7e2.png">

**Comment by svdaru** [comment]
> Now it gets really weird, when i check this "default" option i have no buttons and autologin not works, when unchecked i have it all (buttons and autologin)

It should not be the main reason. Buttons will appear when you successfully autologon to mailbox.
Autologon is working in a strange way. If you are not logged in, you should click button at the top bar, and then refresh page or click link to mail module at the main menu.

**Comment by svdaru** [comment]
@bpabiszczak What do you think about this issue?

**Comment by rskrzypczak** [comment]
Same reason: https://github.com/YetiForceCompany/YetiForceCRM/issues/12982
