### ISSUE TITLE
[bug] Calendar is broken after 5.3 upgrade

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12948]
# 🐞 bug report

### ⁉️ Describe the bug
After upgrading to 5.3 and service pack 4, when I open the calendar, instead of seeing a new blank event on the right side, I see a list of companies, and when I click on a date, the app hangs and I have to close the windows. I can add an activity through a contact record, but it does not show on the calendar. My old activities are still there, as I can see notifications, but the calendar is blank.

![Capture](https://user-images.githubusercontent.com/58600791/80229396-44e75500-8648-11ea-8505-b790b252af1d.JPG)
### 🔥 How to trigger the error
Open Calendar and try to create an activity.

### 👷 Testing 

- [x] I confirm that I tested it at https://gitstable.yetiforce.com 
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|
| Service Pack version | 		|

**Comment by vovpff** [comment]
Are you cleaned browser cache after update?

**Comment by asperitigroup** [comment]
Many thanks vovpff, yes, it was as simple as clearing the browser cache - I had it starting as a Chrome app. So I deleted the app shortcut, cleared the Chrome cache, and recreated the shortcut and the app window and it all appears to be fine now.  Perhaps a note could be made in the upgrade instructions for us less technical users that a browser cache clear is required after upgrade?

Many thanks

Steve

**Comment by vovpff** [comment]
Cache clear needed after every update. In case of updating js files manually you also need to clear cache every time after modifications.
