### ISSUE TITLE
[Question] I have an error message saying "Exceeded the maximum text size in bytes 1024" when pasting a small graphic into a rich text field, but when I created the field I specified no upper size limit.

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#12946]

**Comment by asperitigroup** [comment]
![image](https://user-images.githubusercontent.com/58600791/80206830-f2e10800-8624-11ea-8e26-dfb70c552caf.png)

**Comment by rskrzypczak** [comment]
The image is converted to base64 and the number of characters is too large for the field type.
You have two options: either you paste a smaller image or you modify the field type in the database so that it can save more characters

**Comment by asperitigroup** [comment]
Do you mean directly edit the field in the database using PHPMyAdmin?  Or use Standard Modules, Edit Fields in TF settings?

**Comment by asperitigroup** [comment]
In Edit Field in Settings, it says field type text (UiType: 300) Length 65535, and max text length shows as 0, which I thought meant no limit.
![Capture](https://user-images.githubusercontent.com/58600791/80289512-bbfb1700-8736-11ea-80f8-0eb37dd47a05.JPG)

**Comment by rskrzypczak** [comment]
> Length 65535, and max text length shows as 0, which I thought meant no limit.

not at all :)
Text type may be too small for large images.
`65535 -> 16777215
text -> mediumtext`

> Do you mean directly edit the field in the database using PHPMyAdmin? 

Yes. [example](https://github.com/YetiForceCompany/YetiForceCRM/commit/cbbe4319251f82ae8e725ff7bbd3014056d78a9b)
