### ISSUE TITLE
[Question] creation of advanced module

### ISSUE THREAD

**Issue by scherieble** [YetiForceCompany/YetiForceCRM#12945]
### Description

I try to create a new module with an advanced block similar to the "Goods Received Note".
Unfortunately the advanced block data does not synchronize with the data from the Products module like it does in the "Goods Received Note" module.

If I select a product in my newly created module the fields of EAN, Unit and Subunit are not synchronized with the data from the product. The other fields like "Unit price" are synchronized.
I tried to create the fields EAN, Unit and Subunit as Text fields because they look like text fields in the "Goods Received Note" module and I named them exactly the same. 
I also tried to create The fields as reference but that also does't seem to work.
What am I missing?

Here how it looks in the  "Goods Received Note" module:
![goodsrecievednote](https://user-images.githubusercontent.com/25403007/80203686-39882f80-8630-11ea-9e00-765ce61bc4c7.png)
And here in my newly created module:
![new_module](https://user-images.githubusercontent.com/25403007/80203857-810ebb80-8630-11ea-8136-3c6444e41dea.png)

**Comment by vovpff** [comment]
@scherieble you need to fill `_invmap` table for your module in database. As example you can use `_invmap` table of IGDN

**Comment by scherieble** [comment]
Ok, thank you. It worked.
