### ISSUE TITLE
[Question] How to create a "workflow" that would allow to create a "Time Control" entry for a meeting entry in a "Calendar"

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#12954]
### Description

I would like to create a "workflow" that would allow to create a "Time Control" entry for a meeting entry in a "Calendar". I want to be able to execute the workflow manually for certain meetings. The goal is to be able to have a list of time control entries that I can invoice to clients.

Unfortunately, as show the steps below, It is not possible to create an entity based on a calendar record. Would it eventually be possible to do so by tweaking the database (which tables to consider).

**Step 1**
![step-1](https://user-images.githubusercontent.com/10230144/80273863-4f503000-86d6-11ea-8bc6-ff6989c6728f.png)

**Step 2**
![step-2](https://user-images.githubusercontent.com/10230144/80273864-5bd48880-86d6-11ea-800c-153e275ee7a4.png)

**Step 3**
![step-3](https://user-images.githubusercontent.com/10230144/80273872-62630000-86d6-11ea-9949-cfe2d6a9eb75.png)

Currently I have to manually re-enter the data from a held meeting (by copy-paste) to a new time control record.

**Comment by vovpff** [comment]
Idea. Try mapping feature. Maybe this available for calandar and time control.

**Comment by diderich** [comment]
Mapping unfortunately does not allow to map the start date of an appointment to the start date of a time control. Neither does it allow to map the associated process :-(

**Comment by bpabiszczak** [comment]
You need a developer to extend existing functionalities.
