### ISSUE TITLE
[Question] Multiple RoundCube SMTP servers

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#12958]
Hello! 

I would like to ask if your CRM-system supports adding multiple STMP servers in RoundCube to be able to log-in in to `My Mailbox` through for example `gmail.com`, `yahoo.com`, and custom SMTP at the same time? 

If so, could you please provide any instructions on how to do it?

Thanks for the answer!

**Comment by bpabiszczak** [comment]
Yes, as long as they use the same protocol and port.
We can extend it to completely different configurations, but it takes 1-2 developer working days.

![image](https://user-images.githubusercontent.com/10197525/91657755-c0a85100-eac3-11ea-9a49-59dbecedf5a0.png)

**Comment by simple-AMS** [comment]
> Yes, as long as they use the same protocol and port.
> We can extend it to completely different configurations, but it takes 1-2 developer working days.
> 
> ![image](https://user-images.githubusercontent.com/10197525/91657755-c0a85100-eac3-11ea-9a49-59dbecedf5a0.png)

@bpabiszczak I get the part on how to setup the Imap servers by just keep adding them. However, the SMTP server though how do you add all the ones to match all the new IMAP servers that have been added?
