### ISSUE TITLE
[Feature] New comment notification to shared users on ticket

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#12950]
Hello all! 

Right now it looks like when you create a ticket, assign it to someone, as well as select shared users, it is possible to send ticket create/change/close workflows to both assigned to and shared users. 

But..

It looks like when you comment on that ticket, the notification can only be sent to the assigned to user or account. 

How can I configure so that the ticket comment can also be sent to shared users on that ticket?

**Comment by vovpff** [comment]
You need to change workflow what sends emails

**Comment by acoolov** [comment]
For comments, the workflow looks different than for ticket create/change/close. 
You can't change who to send notifications to with comments. There is only 3 options to send comment notifications to and they are: account, owner, contact. It's some type of custom function that is triggered, and you can't change it for some reason.

**Comment by vovpff** [comment]
Sorry. My mistake.

**Comment by acoolov** [comment]
This seems to be pretty important feature since it is already possible to share ticket notifications with users. It sends the ticket update notifications to shared users but it won't send the ticket comment to shared users. Can we implement this feature in the next update?

**Comment by acoolov** [comment]
Anyone?

**Comment by acoolov** [comment]
Can anyone help push this through? Seems like sometimes unnecessary features are getting implemented while this basic and essential feature is not even being looked at. 
I can't even comment on the ticket so that everyone receives a notification with that comment.

**Comment by bpabiszczak** [comment]
You need a developer to expand the basic functionality.
https://yetiforce.com/en/marketplace/development-support
