### ISSUE TITLE
[bug]  Error 500 after install - redirect to /install/install.php works but get error 500 ??

### ISSUE THREAD

**Issue by rail3r** [YetiForceCompany/YetiForceCRM#12951]
Installed Yetisoftware 5.3.0 complete on CentOS 8 server using this tuttorial:
https://computingforgeeks.com/install-yetiforce-crm-on-centos-centos-linux/

Im getting error 500 when it redirects to /install/install.php

Tried everything including the requirements on this site : https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

I tought maybe it is CentOS 8, so tried the same thing on my Ubuntu 18.04 LTS server and got exactly the same problem.

What am i doing wrong ?

**Comment by mariuszkrzaczkowski** [comment]
show full logs

**Comment by rail3r** [comment]
[Fri Apr 24 22:00:21.607037 2020] [php7:error] [pid 4904] [client 127.0.0.1:41406] PHP Fatal error:  Uncaught Exception: The imap library is missing in /var/www/yetiforce/include/RequirementsValidation.php:15\nStack trace:\n#0 /var/www/yetiforce/install/Install.php(24): include_once()\n#1 {main}\n  thrown in /var/www/yetiforce/include/RequirementsValidation.php on line 15

**Comment by rail3r** [comment]
above is my Ubuntu bellow is my CentOS 8 

[Fri Apr 24 15:53:34.036820 2020] [cgid:error] [pid 5010:tid 139911579531008] [client 5.182.211.76:43434] AH01264: script not found or unable to stat: /var/www/cgi-bin/ViewLog.asp

**Comment by mariuszkrzaczkowski** [comment]
> The imap library is missing

```
THIRD PARTY LIBRARIES CONFIGURATION
IMAP Mandatory
PDO Mandatory
MySQL Native Driver (mysqlnd) Mandatory
GD Mandatory
OpenSSL Mandatory
Curl Mandatory
PCRE Mandatory
XML Mandatory
JSON Mandatory
SESSION Mandatory
DOM Mandatory
ZIP Archive Mandatory
MBSTRING Mandatory
SOAP Mandatory
FILEINFO Mandatory
ICONV Mandatory
INTL Mandatory
SPL Mandatory
Reflection Mandatory
SimpleXML Mandatory
bcmath Mandatory
filter Mandatory
LDAP Optional
EXIF Optional
APCU Optional
OPCACHE Optional
IMAGICK Optional (but recommended)
```

**Comment by rail3r** [comment]
Ok that works, thanks :) but now my Centos 8 - still dont get it why it is not working there

**Comment by bpabiszczak** [comment]
These are not problems with YetiForce, but with your server configuration. We can help if you purchase paid support. https://yetiforce.com/pl/marketplace/wsparcie-development

It is best for you to buy hosting or VPS where the environment is set up for YetiForce and you have support.
