### ISSUE TITLE
Missing translation. Contacts edit view

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1295]
![Translation](https://cloud.githubusercontent.com/assets/3193498/8474797/1c8755b0-20b3-11e5-9590-3ff5392748ef.png)
In contacts edit view is missing translation

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/87c8d9f03f1dd259145fe4ef9c9a0bdd0fe4c175
