### ISSUE TITLE
[Question] [PL] Zmienna obcina string

### ISSUE THREAD

**Issue by kjakobczak** [YetiForceCompany/YetiForceCRM#12957]
### ⁉️ Describe the bug
Problem z Podpisem globalnym dla e-maili.
Zmienna $(record : roleid)$ obcina część roli użytkownika.

![obraz](https://user-images.githubusercontent.com/64394971/80346310-d6cea800-886a-11ea-81a5-32338a86f6c5.png)

Natomiast w samym podpisie wygląda to już następująco:

![obraz](https://user-images.githubusercontent.com/64394971/80347842-2a41f580-886d-11ea-9303-564cc786f38f.png)

**Comment by vdpawel** [comment]
Czy sprawdzałeś, czy ma na to wpływ konfiguracja poniżej?

![obraz](https://user-images.githubusercontent.com/62466142/81475997-b231e300-920f-11ea-8b2c-4f57288c84e3.png)

**Comment by kjakobczak** [comment]
Zmiana długości tekstu w widoku listy rozwiązała problem.
@vdpawel Dziękuję za pomoc
