### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ehasnik** [YetiForceCompany/YetiForceCRM#12979]
### Description
Witam, 
potrzebuję na fakturze sprzedaży umieścić kwotę Brutto do zapłaty słownie.
Czy Yetiforce 5.3 posiada taką funkcjonalność? 

pozdrawiam

**Comment by bpabiszczak** [comment]
W YetiForce można umieszczać własne funkcje, a gotowych funkcji na przeliczanie kwoty jest wiele w internecie. Programista powinien sobie z tym poradzić w 1-4 godziny. Kwota słownie nie jest wymagana w PL.
