### ISSUE TITLE
[Question] Problem z importem kontrahentów

### ISSUE THREAD

**Issue by mateuszrudyk** [YetiForceCompany/YetiForceCRM#12977]
Strona główna->Firmy i Kontakty->Kontrahenci->Import
Po wybraniu pliku i wciśnięciu "Dalej" pojawia sie komunikat:
"Plik importu nie ma możliwości zapisu"
Co on oznacza? 
Pozdrawiam
Mateusz Rduyk

**Comment by bpabiszczak** [comment]
Zapewne, że plik importu nie ma możliwości zapisu :) 
Przypuszczam, że są nieodpowiednie uprawnienia do folderu, gdzie aplikacja zapisuje plik.
Proszę sprawdzić, czy problem występuje na gitstable i gitdeveloper.

**Comment by mateuszrudyk** [comment]
instalacja jest na linuksie i (w celu diagnostyki) nadałem maksymalne uprawnienia do całego katalogu yetiforce. Wersja 5.2.0...

**Comment by mateuszrudyk** [comment]
na gitstable nie ma tego komunikatu...

**Comment by bpabiszczak** [comment]
a więc to nie problem CRM-a i pliku, lecz tak jak mówi komunikat, uprawnień do zapisu :)

**Comment by bpabiszczak** [comment]
Gitstable to 5.3, więc zalecamy aktualizację do 5.3 + najnowszy SP.

**Comment by mateuszrudyk** [comment]
po aktualizacji (udanej) to samo... Na który folder w instalacji mam zwrocic uwagę?

**Comment by rskrzypczak** [comment]
Pokaż swoją konfigurację.
tu masz przykład: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65
znajduje się tam blok z uprawnieniami do plików i kataogów

**Comment by mateuszrudyk** [comment]
Uprawnienia zapisu do plików i folderów
--
app_data/cron.php | Nie | Nie | - | 0644
app_data/registration.php | Tak | Tak | 33 | 0777
app_data/moduleHierarchy.php | Tak | Tak | 1000 | 0777
app_data/shop.php | Tak | Tak | 33 | 0644
app_data/icons.php | Tak | Tak | 1000 | 0777
app_data/LanguagesUpdater.json | Tak | Tak | 33 | 0644
app_data/SystemUpdater.json | Tak | Tak | 33 | 0644
app_data/libraries.json | Tak | Tak | 1000 | 0777
user_privileges/tabdata.php | Tak | Tak | 1000 | 0777
user_privileges/menu_0.php | Tak | Tak | 1000 | 0777
user_privileges/user_privileges_1.php | Tak | Tak | 1000 | 0777
app_data/ | Tak | Tak | 1000 | 0777
app_data/shop/ | Tak | Tak | 1000 | 0777
cache/ | Tak | Tak | 1000 | 0777
cache/addressBook/ | Tak | Tak | 1000 | 0777
cache/images/ | Tak | Tak | 1000 | 0777
cache/import/ | Tak | Tak | 1000 | 0777
cache/mail/ | Tak | Tak | 1000 | 0777
cache/pdf/ | Tak | Tak | 1000 | 0777
cache/logs/ | Tak | Tak | 1000 | 0777
cache/session/ | Tak | Tak | 1000 | 0777
cache/templates_c/ | Tak | Tak | 33 | 0755
cache/upload/ | Tak | Tak | 1000 | 0777
cache/vtlib/ | Tak | Tak | 1000 | 0777
cache/vtlib/HTML | Tak | Tak | 1000 | 0777
config/ | Tak | Tak | 1000 | 0777
config/Components | Tak | Tak | 1000 | 0777
config/Modules | Tak | Tak | 33 | 0777
user_privileges/ | Tak | Tak | 1000 | 0777
languages/ | Tak | Tak | 1000 | 0777
modules/ | Tak | Tak | 1000 | 0777
storage/ | Tak | Tak | 1000 | 0777
storage/Products/ | Tak | Tak | 1000 | 0777
storage/Users/ | Tak | Tak | 1000 | 0777
storage/Contacts/ | Tak | Tak | 1000 | 0777
storage/OSSMailView/ | Tak | Tak | 1000 | 0777
public_html/modules/OSSMail/ | Tak | Tak | 1000 | 0777
public_html/libraries/ | Tak | Tak | 33 | 0755
public_html/layouts/resources/Logo/ | Tak | Tak | 1000 | 0777

**Comment by mateuszrudyk** [comment]
już doszedłem, o którry folder chodzi - niestety spoza instalacji yetiforce: /temp

**Comment by mariuszkrzaczkowski** [comment]
Masz nieprawidłową  konfigurację serwera
