### ISSUE TITLE
[Question] Maximum number of files exceeded

### ISSUE THREAD

**Issue by MexasPT** [YetiForceCompany/YetiForceCRM#12978]
Hello everyone!
How can I change the "Maximum number of files exceeded"?
I need to upload 12 images, but the system only allows 10.

![multi image file1](https://user-images.githubusercontent.com/17734465/80611733-e993d900-8a32-11ea-8546-42410b86df61.png)
This situation refers to the "Multi Image files" field

Can you help me?

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/33d5791770b5e8f92f87af0b786334c07045f788/modules/Vtiger/files/MultiImage.php#L29-L34

but this is a global setting.
It is not possible to change this option from the GUI
