### ISSUE TITLE
Massive creation in a related module

### ISSUE THREAD

**Issue by Itc2020** [YetiForceCompany/YetiForceCRM#12976]
Hello everybody, 
I'm creating a CRM with yetiforce, I created a relation M:M between accounts and campaigns. All seems working, but I would like to select (in the module of Accounts) the records that I need, and through a massive creation put them inside a campaign. 
Is this possible? How could I do it?
Thanks

**Comment by apcloic** [comment]
Hi,
What does massive creation mean ?

**Comment by Itc2020** [comment]
Sorry, i think i was wrong. I would like to know if i could do it through the section "actions" in the module of accounts. The gif will show what I mean

![Gif Yeti](https://user-images.githubusercontent.com/64258336/80500250-3eb9e700-896e-11ea-85ed-bbd9e2f68f83.gif)

**Comment by apcloic** [comment]
@Itc2020 I think you should do the opposite, create a campaign, then go to the account tab and use filters to select your list of accounts.
No need to create a relation m:m between accounts and campaigns.

**Comment by Itc2020** [comment]
@apcloic Hi, Yes, I know that I could do the opposite. However, I would  like to know if I can fo it also from the accounts' module

**Comment by rskrzypczak** [comment]
If you are a developer, everything is possible :)
Currently, the system does not have this option.
You would have to create a new action and add what you need there.
However, I'm afraid that you won't avoid modifying the source files, which will complicate the process of later system updates.
