### ISSUE TITLE
[Question] Email templates not working Roundcube

### ISSUE THREAD

**Issue by NickLFP** [YetiForceCompany/YetiForceCRM#12982]
Hello, 

I have just setup yetiforce for our company as a simple crm system. At this point all is working good except one thing; i can't use emailtemplates. Mail is setup and functioning (roundcube) and even plugins working business data, search etc the onyl thing is not working is email templates in roundcube. How can i activate this? So no module and template is possible see the picture below. 

![yetiforce email](https://user-images.githubusercontent.com/64595144/80716492-00503380-8af8-11ea-883e-cbbbccf31e55.jpg)

**Comment by jimlee213** [comment]
I have the same problem, let me know if you find solution

**Comment by apcloic** [comment]
@NickLFP @jimlee213 
Did you check if you email template's type is properly set as 'message' ?
https://github.com/YetiForceCompany/YetiForceCRM/issues/9647#issuecomment-467435771
Regards

**Comment by jimlee213** [comment]
> @NickLFP @jimlee213
> Did you check if you email template's type is properly set as 'message' ?
> [#9647 (comment)](https://github.com/YetiForceCompany/YetiForceCRM/issues/9647#issuecomment-467435771)
> Regards
![image](https://user-images.githubusercontent.com/44873199/80745977-22918380-8aef-11ea-8005-455717fe1333.png)

**Comment by apcloic** [comment]
@jimlee213 
My email template is related to Contacts module but I've tried with Corporate emails and it works as well.
However, I'm still using YF 5.2, what is your version ?

**Comment by C-G-White** [comment]
Has anyone made any progress with this issue.  I have just done 2 installations one on HostPapa which was done with their installation system through cPanel and another one on Siteground from scratch.   Both of these installations are using 5.3.0 YF and neither of them allow mail templates to be used in Roundcube.  I have ensured that there are templates set to "Message" to no avail.

Any assistance with this would be a great help.

Regards, Chris.   Stay Safe.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13203#issuecomment-647282372
https://github.com/YetiForceCompany/YetiForceCRM/issues/13203#issuecomment-648831367
Fix autologin for 5.3: https://github.com/YetiForceCompany/YetiForceCRM/commit/839097e9daafd6038e31ab0c9545cc728c443b50
