### ISSUE TITLE
[Question] Internal server error

### ISSUE THREAD

**Issue by jimlee213** [YetiForceCompany/YetiForceCRM#12980]
Hello, 
I am using Yetifoce V5.2.0
when I try to compose an email it shows:
![image](https://user-images.githubusercontent.com/44873199/80646674-28c62800-8a3b-11ea-84d7-6eaa7cc1fe22.png)
an error occurred
server error ( internal server error)
and I did google search, someone said I need to have the permission of template.
but my email template is blank. ( not clickable)

I am not sure if it is email template permission cause the problem, how to assign permission to the user? BTW, I am a system admin.

update:
error log:
[29-Apr-2020 17:41:51 America/New_York] PHP Fatal error:  Uncaught Error: Call to a member function getRoleDetail() on null in C:\Program Files\Ampps\www\oootest.com\yeti\app\PrivilegeQuery.php:70
Stack trace:
#0 C:\Program Files\Ampps\www\oootest.com\yeti\app\PrivilegeQuery.php(48): App\PrivilegeQuery::getPrivilegeQuery(Object(App\Db\Query), 'EmailTemplates', Object(App\User), NULL)
#1 C:\Program Files\Ampps\www\oootest.com\yeti\app\QueryGenerator.php(991): App\PrivilegeQuery::getConditions(Object(App\Db\Query), 'EmailTemplates', Object(App\User), NULL)
#2 C:\Program Files\Ampps\www\oootest.com\yeti\app\QueryGenerator.php(806): App\QueryGenerator->loadWhere()
#3 C:\Program Files\Ampps\www\oootest.com\yeti\app\Mail.php(95): App\QueryGenerator->createQuery()
#4 C:\Program Files\Ampps\www\oootest.com\yeti\public_html\modules\OSSMail\roundcube\plugins\yetiforce\yetiforce.php(658): App\Mail::getTemplateList('', 'PLL_MAIL')
#5 C:\Program Files\Ampps\www\oootest.com\yeti\public_html\modules\OSSMail\roundcube\program\lib\Roundcube\rcube_plugin_api.php(493): yetiforce->getE in C:\Program Files\Ampps\www\oootest.com\yeti\app\PrivilegeQuery.php on line 70

thanks

**Comment by bpabiszczak** [comment]
Check if you can cause the bug on test versions [if so, record the movie].
