### ISSUE TITLE
[Question] syntax error, unexpected ''=>'' (T_CONSTANT_ENCAPSED_STRING)

### ISSUE THREAD

**Issue by microstrategies** [YetiForceCompany/YetiForceCRM#13006]
Hi all,

I've installed YetiForce 5.3.0 on my own VPS and it was working fine until yesterday. When I go to settings, I keep getting this error and cannot access any settings unfortunately. Has anyone had a similar issue and knows the fix please? 

![Screenshot 2020-05-08 at 12 20 30](https://user-images.githubusercontent.com/65020292/81401565-df0ec900-912f-11ea-93fd-b9df8eff8349.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/81401836-6f4d0e00-9130-11ea-9353-d1f6114e2a29.jpg)
