### ISSUE TITLE
[Question] Syntax error, unexpected ''=>'' (T_CONSTANT_ENCAPSED_STRING)

### ISSUE THREAD

**Issue by microstrategies** [YetiForceCompany/YetiForceCRM#13005]
Hi all,

I've installed YetiForce 5.3.0 on my own VPS and it was working fine until yesterday. When I go to settings, I keep getting this error and cannot access any settings unfortunately. Has anyone had a similar issue and knows the fix please? 

![Screenshot 2020-05-08 at 12 20 30](https://user-images.githubusercontent.com/65020292/81401565-df0ec900-912f-11ea-93fd-b9df8eff8349.png)

**Comment by kalle3e** [comment]
How about try checking the php log or php error log.

**Comment by kalle3e** [comment]
cache/logs/phpError.log

**Comment by reinhardtl** [comment]
This is very simple to fix temporarily. I have not checked what is causing it.
Delete the app_data/cron.php file. It contains something like 'rt'=>1592576404];' at the end of the file, which is what causes the above error. I have the same problem and have to delete that file once every day.

**Comment by gkankstech** [comment]
I have the same thing happening. All the system setting seem to make Yeti gods happy (have a few optional things off and it flags a few things in the System headers section but nothing that triggers an actual System or Security warnings/errors.

The error seem to be in how the cron.php file is being built. 

Perhaps there's a variable that needs to be set higher or something as it seems to be an incomplete file. 

Although looking at the syntax we can see that the first bracket after the keyword "return" is properly closed and there's another value set with a closing bracket that does not seem to correlate to anything:

;rt'=>1596060602]

I've attached the cron.php file in case it helps with reviewing the issue.
[cron.php.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/5019457/cron.php.zip)



The only error from error cache/logs/cron_error.log is:

2020-08-03 20:00:01 - syntax error, unexpected ''=>1596060602];' (T_ENCAPSED_AND_WHITESPACE)

**Comment by rskrzypczak** [comment]
This should fix the problem: https://github.com/YetiForceCompany/YetiForceCRM/commit/b14961d1e19d6b1c10a61777bc288fcd93c21b4c

**Comment by rskrzypczak** [comment]
No response, so I assume the issue no longer occurs.
