### ISSUE TITLE
[Pytanie] Faktury sprzedaży z numerem "wstecz"

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#13001]
Witam,
mam pytanie odnośnie faktur, mam numerację miesięczną, zeruje nr z nowym miesiącem, czy jest możliwość wystawienia faktury z numerem na poprzedni miesiąc wtedy kiedy jest już nowy miesiąc?
Lub proszę o informację gdzie zapisywana jest lista faktur, abym mógł "ręcznie" dopisać w bazie rekord

Z góry dziękuję

**Comment by vdpawel** [comment]
Rozumiem, że chodzi o to, żeby numer miesiąca w numerze faktury odpowiadał miesiącowi z daty wystawienia dokumentu.
Czyli jeżeli fakturujemy coś sprzedanego np. 28 kwietnia, a robimy to 4 maja. Wtedy numer faktury powinien być jeszcze kwietniowy.
Może jest jakiś lepszy sposób... możesz poradzić sobie z tym problemem tworząc nowe pole i do niego przepisywać w wyzwalaczach nr faktury generowany automatycznie. Jeżeli potrzebujesz zmienić ten numer po prostu edytujesz pole. Niestety nie jest to metoda idealna i może rozsypać Ci się cała numeracja faktur.
Można też wygenerować parę faktur "roboczych" do przodu i ew. później je skasować.

Dane z faktur sprzedażowych są przechowywane m.in. w tabeli: "u_yf_finvoice", ale mocno **nie polecam dodawania ręcznie rekordów lub robienia zmian**.

**Comment by Sall2** [comment]
Ok, informacja na przyszłość, zrobiłem to tak:
Nowa faktura bieżąca i później zmiana danych w u_yf_finvoice (nr faktury, daty sprzedaży i wystawienia), wszystko zadziałało elegancko, mam nadzieję, że system to wytrzyma ;)\
Jedyny minus jest taki, że faktura jest na liście w majowych już, zapewne przez parametr finvoiceid, ale tego to już nie ruszam.

Pozdrawiam
