### ISSUE TITLE
[Question] Validation check of field size in database

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#13002]
In reference to #12946 I changed the type of fields in the database, but the message pops up
![obraz](https://user-images.githubusercontent.com/62466142/81282475-7e15c100-905b-11ea-878e-ea0e0e98111a.png)

Where can I change the validation check?
If it changes the field size correctly, will the correctness check detect it?

**Comment by rskrzypczak** [comment]
I don't think you looked too closely at this [issue](https://github.com/YetiForceCompany/YetiForceCRM/issues/12946#issuecomment-625009481).
https://github.com/YetiForceCompany/YetiForceCRM/commit/cbbe4319251f82ae8e725ff7bbd3014056d78a9b#diff-c68a4e9329987315e0b2a54b0803fa4cR4469
vtiger_field -> maximumlength

**Comment by vdpawel** [comment]
Indeed, all that was needed was in that issue.
I will only add that after changing the size of some fields, it is also worth resizing the `prevalue` and ` postvalue` fields in the table `vtiger_modtracker_detail`
