### ISSUE TITLE
[bug]  Cannot see results of workflow "Update fields"

### ISSUE THREAD

**Issue by joao-penguin** [YetiForceCompany/YetiForceCRM#13010]
When a field is updated through workflow Update fields, result is not displayed to the user
Nevertheless update is properly performed as a refresh enables user to see the change. I think that after workflow task execution, Yetiforce should read data from database to get & display last version of data.

**Hereafter test configuration**
 
![Screenshot from 2020-05-11 11-59-40](https://user-images.githubusercontent.com/58401743/81554895-803f8e80-937f-11ea-82b8-e3d8e19e73ea.png)

![Screenshot from 2020-05-11 12-00-03](https://user-images.githubusercontent.com/58401743/81554978-98171280-937f-11ea-99f0-15ebee4cf906.png)

![Screenshot from 2020-05-11 12-00-15](https://user-images.githubusercontent.com/58401743/81554981-99e0d600-937f-11ea-947b-fb38dca1d782.png)

**Hereafter test**
I create a correspondance
After create, field "date of receiving" is empty: normal
![Screenshot from 2020-05-11 12-00-49](https://user-images.githubusercontent.com/58401743/81554988-9c433000-937f-11ea-9db0-d7d019c0fe16.png)

After update, field "date of receiving" is empty: this is not the expected value
![Screenshot from 2020-05-11 12-01-09](https://user-images.githubusercontent.com/58401743/81554996-9ea58a00-937f-11ea-9526-3e9385644469.png)

After refresh, date is set
![Screenshot from 2020-05-11 12-01-25](https://user-images.githubusercontent.com/58401743/81555000-9fd6b700-937f-11ea-8ae7-dc8ef61717fe.png)

**Comment by apcloic** [comment]
@joao-penguin 
I suppose you are using quick edit instead of full edit record.
I don't think it's a good idea to do a refresh in this case because then it will slower the process while the goal is to be quick.
Regards,

**Comment by joao-penguin** [comment]
Thanks for the quick answer.
I agree that refresh the page will slower the process and should be done with caution. 
But in my use case, to see the result, user has to refresh the page, either by F5 or by going to full edit (that generates a full refresh).

A workaround would be to use a "custom function" Is there a way to force yeti to refresh the page content ?

**Comment by KatarzynaUlichnowska** [comment]
Hello, thanks for submitting an issue, as far I know, you are in contact via e-mail with one of our team members and you are waiting for a quote. Therefore, I will close the issue.
