### ISSUE TITLE
[Error] Call to a member function get() on null.

### ISSUE THREAD

**Issue by federico0100** [YetiForceCompany/YetiForceCRM#13023]
![SharedScreenshot1](https://user-images.githubusercontent.com/62551450/81737747-dfdd8d00-9498-11ea-8a91-afb23dfdc47b.jpg)
[errors.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4618015/errors.log)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4618017/system.log)

# 🐞 bug report

What happened?

**Comment by federico0100** [comment]
Help please, it no longer allows me to access the system and displays the error message with all users.

**Comment by rskrzypczak** [comment]
First try removing all sessions from `cache/session`

if that doesn't work then you can try to empty vtiger_module_dashboard, vtiger_module_dashboard_blocks tables in database.
however, this way you will remove all widgets on the dashboard :)

**Comment by federico0100** [comment]
I thank you for the answer!
I have deleted the sessions and emptied the tables but I still get the error after logging in and I cannot change the page.

**Comment by federico0100** [comment]
Help, Another Idea?

**Comment by federico0100** [comment]
Good morning.
The problem is not with the database, but with the folders or the files. In fact, I recovered a backup on which I restored the database, solving the problem of functionality.

**Comment by mariuszkrzaczkowski** [comment]
this is a problem with user roles,
maybe you deleted something
maybe the permissions didn't refresh properly
