### ISSUE TITLE
LBL_IMPORT_FILE_DIFFERENT_ENCODING

### ISSUE THREAD

**Issue by ruengdech** [YetiForceCompany/YetiForceCRM#13025]
I just Export Account data then import It self, It should pass but still have issue with this Error

![image](https://user-images.githubusercontent.com/15377403/81803875-75812700-9542-11ea-964b-b0ae3377f737.png)

 [ver. 5.3.0] [TMDHosting] 
http://www.bnhcrm.com/

#12658  #12136 #11762  Cannot solve @mariuszkrzaczkowski

**Comment by ruengdech** [comment]
https://github.com/mariuszkrzaczkowski
Need your help

**Comment by rskrzypczak** [comment]
try in n++ `Encoding -> Convert to UTF-8 BOM`

**Comment by ruengdech** [comment]
@rskrzypczak Great, Dziękuję Ci for your solution, It work.
