### ISSUE TITLE
[bug] new lead concat 2 variable

### ISSUE THREAD

**Issue by crawe1** [YetiForceCompany/YetiForceCRM#13032]
Błąd: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '121' for key 'PRIMARY' The SQL being executed was: INSERT INTO `u_yf_crmentity_label` (`crmid`, `label`) VALUES (121, '')

Dodałem automatyzację w postaci składania concatem z imienia i nazwiska nazwę leada. Błąd występuje za każdym razem kiedy automatyzacja jest włączona. Rekord jest poprawnie tworzony i dodaje do bazy mimo błędu połączona zmienna z imienia i nazwiska ale błąd występuje. 

Automatyzacja -> harmonogram obiegu informacji( tworzenie rekordu )-> dodaj zadania (aktualizuj rekord (concat(lead_first_name,' ',lead_surname))

Dodatkowo gdy kliknę w pole oznaczone żółtym kolorem dostaję błąd 404 - działa jedynie edytowanie poprzez naciśnięcie na ołówek z prawej strony.

![image](https://user-images.githubusercontent.com/61950059/81923314-c134de80-95dd-11ea-83b6-443d3c65ecd0.png)

![image](https://user-images.githubusercontent.com/61950059/81923405-e9244200-95dd-11ea-992b-307519292b39.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/81924634-a9f6f080-95df-11ea-9a9c-03316af6fe9a.jpg)

**Comment by vdpawel** [comment]
Odnośnie pierwszego problemu rozwiązaniem może być #12768.

Drugi problem związany z błędem 404, rzeczywiście występuje w nowej wersji, ale sprawdziłem, że w deweloperskiej został wyeliminowany.
