### ISSUE TITLE
[Error]  There is no record with identifier 1

### ISSUE THREAD

**Issue by federico0100** [YetiForceCompany/YetiForceCRM#13047]
### 📷 Screenshot of configuration
![1](https://user-images.githubusercontent.com/62551450/82185784-0e6cc500-98ea-11ea-8b42-65766ebbd510.jpg)
![2](https://user-images.githubusercontent.com/62551450/82185786-0f055b80-98ea-11ea-9017-97a3820c7a68.jpg)

**Comment by mariuszkrzaczkowski** [comment]
you have deleted the basic entry in MultiCompany which is used in roles and user because of that you have an error

https://gitdeveloper.yetiforce.com/index.php?module=MultiCompany&view=Detail&record=1
