### ISSUE TITLE
[Pytanie] Nagłówek PDF

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#13065]
Witam,
czy jest możliwość ustawienia nagłówka tylko na pierwszej stronie faktury?

**Comment by vdpawel** [comment]
Tak, wtedy nie ustawiasz nagłówka, tylko normalnie wstawiasz to co potrzebujesz w treści na samej górze - będzie tylko na pierwszej stronie.

**Comment by Sall2** [comment]
To wiem, aczkolwiek próbowałem sformatować tak górę strony aby wyglądała jak z nagłówkiem i chyba nie da rady. Nagłówek definiuje się tylko marginesem od góry i on "nakłada" się na treść, a w drugim przypadku logo powoduje przesunięcie tekstu, nie można użyć ujemnych marginesów we właściwościach obrazka.
Zupełnie inny jest też margines "od góry" strony.

**Comment by vdpawel** [comment]
Możesz spróbować zmodyfikować kod, na przykładzie tego zgłoszenia #12898 (tu akurat jest inna stopka) lub w plikach app/Pdf.
