### ISSUE TITLE
[bug] [PL] ModTracker - powielanie wpisów w historii zmian przez wyzwalacz: aktualizuj rekord

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#13062]
# 🐞 bug report

### ⁉️ Describe the bug

Po ustawieniu w wyzwalaczach funkcji: "aktualizuj rekord", w historii zmian jest multiplikowany wpis, tyle razy ile jest ustawionych powyższych funkcji.

![obraz](https://user-images.githubusercontent.com/62466142/82547338-dbc90380-9b59-11ea-9655-083aa9539426.png)

### 🔥 How to trigger the error

W wyzwalaczach w wybranym module, ustawić funkcję aktualizuje rekord.
Zapisać rekord, lub zmienić wartość w jego polu, np. status z jednej wartości na drugą.

### 👎 Actual Behavior

Wpis w historii zmian jest powielony wiele razy, co w ogóle nie jest przydatne oraz nie daje nowych informacji.
![obraz](https://user-images.githubusercontent.com/62466142/82547338-dbc90380-9b59-11ea-9655-083aa9539426.png)

### 👍 Expected Behavior

Po zmianie parametrów w historii zmian powinien być jeden wpis, niezależnie od ilości funkcji aktualizuj rekord w wyzwalaczach.
![obraz](https://user-images.githubusercontent.com/62466142/82547807-99ec8d00-9b5a-11ea-8ca7-082009c07a0a.png)

### 🌍 Your Environment

YetiForce CRM 5.3 Service Pack v4

**Comment by mariuszkrzaczkowski** [comment]
sprawdź na wersji deweloperskiej, ten mechanizm był przebudowany

**Comment by vdpawel** [comment]
W wersji deweloperskiej działa świetnie! (wcześniej nie mogłem ustawić wyzwalacza w wersji dev)
Dziękuję i pozdrawiam
