### ISSUE TITLE
[Question] Invoice - tax rate in product table?

### ISSUE THREAD

**Issue by csych** [YetiForceCompany/YetiForceCRM#13063]
I'd like to generate invoices including tax rate for each product or service inside product table. Is there any way to achieve that?

I've found this code to use in PDF template:
```
$(inventory : type=table columns=name,qty,price href=yes)$
$(inventory : type=table columns=seq,name,qty,unit,price,total,net href=no)$
```

It has everything I need except tax rate. I'd appreciate any help.

**Comment by vovpff** [comment]
Put tax to columns

**Comment by csych** [comment]
@vovpff I tried that. But "tax" returns tax amount (e.g. 100 EUR). What I need is product's tax rate (e.g. 22%).

**Comment by vdpawel** [comment]
Try tax_percent...

**Comment by csych** [comment]
@vdpawel doesn't work

**Comment by vdpawel** [comment]
Add Tax[%] in advanced block
![obraz](https://user-images.githubusercontent.com/62466142/82724147-4dc55800-9cd4-11ea-86f8-dc24e292afdf.png)

**Comment by csych** [comment]
@vdpawel I followed your advice. Unfortunately it didn't work.

**Comment by vdpawel** [comment]
this is not the best solution, I don't know if it works for you
in this file:
app/TextParser/ProductsTableNew.php

try to modify the lines 48 and 84 and add the value there: 'TaxPercent'

in the pdf template, add ProductsTableNew

result:
![obraz](https://user-images.githubusercontent.com/62466142/83327602-5e9a3e80-a27d-11ea-849e-3fb659662967.png)

**Comment by csych** [comment]
@vdpawel Thanks a lot!! I created new ProductTable file based on existing one. Then I modified it like you wrote (with small change only) and it's working now.
