### ISSUE TITLE
[Question] change Password

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#13066]
Hello everyone, I want to change the password in my personal settings, but nothing happens after clicking, I do n’t know what is going on, I hope to get help.
The version I use is 5.3. My default smtp is also set up and ready to use.

**Comment by blu-IT** [comment]
Is there any message or confirmation when changing your password?
Can you post a screenshot?

**Comment by copyyour** [comment]
I tested it, it should be the problem of sp4, I replaced the relevant files back to the original version of 5.3, this problem was solved. .

The previous problem was that after clicking Change Password, the complete password change interface was not displayed
