### ISSUE TITLE
[bug] Calendar widget, links for events are not available

### ISSUE THREAD

**Issue by nerimic** [YetiForceCompany/YetiForceCRM#13075]
# 🐞 bug report

### 👎 Actual Behavior

The events labels are visible but the link is not active

### 👍 Expected Behavior

A link to the event clicking in to the event's label

### ❗️ Inform the community if you solve the problem

Change:
            div class="fc-bg">' +^M
To:
            div class="fc-bg" style="pointer-events:none">' +^M
In:
             public_html/libraries/fullcalendar/dist/fullcalendar.js

**Comment by areksolek** [comment]
Please send me more information. Is the report related to the dashboard widget or the module summary widget?
I am asking for a possible screen.

**Comment by nerimic** [comment]
It's in the dashboard widget.

https://gitdeveloper.yetiforce.com/index.php "Test C"

Moving the cursor over an event's icon you could not see any link to

[image: Schermata 2020-08-31 alle 11.55.33.png]


I've implemented a fix that seems OK adding style="pointer-events:none" in '
public_html/libraries/fullc*alendar*/dist/fullc*alendar*.js'


    DayGrid.prototype.renderDayRowHtml = function (row, isRigid) {^M

        var theme = this.view.calendar.theme;^M

        var classes = ['fc-row', 'fc-week', theme.getClass('dayRow')];^M

        if (isRigid) {^M

            classes.push('fc-rigid');^M

        }^

        return '' +^M

            '<div class="' + classes.join(' ') + '">' +^M

            '<div class="fc-bg" style="pointer-events:none">' +^M

            '<table class="' + theme.getClass('tableGrid') + '">' +^M

            this.renderBgTrHtml(row) +^M

            '</table>' +^M

            '</div>' +^M

            '<div class="fc-content-skeleton">' +^M

            '<table>' +^M

            (this.getIsNumbersVisible() ?^M

                '<thead>' +^M

                    this.renderNumberTrHtml(row) +^M

                    '</thead>' :^M

                '') +^M

            '</table>' +^M

            '</div>' +^M

            '</div>';^M

    };^M






With this change the cursor change shape, the popup shows the event's kind
and a click in the icon badge jumps to the event's page

[image: image.png]

Il giorno lun 31 ago 2020 alle ore 11:45 Arek Solek <
notifications@github.com> ha scritto:

**Comment by nerimic** [comment]
Great!

Thank you

Il giorno mer 2 set 2020 alle ore 12:00 Mariusz Krzaczkowski <
notifications@github.com> ha scritto:
