### ISSUE TITLE
[Question] is it possible to create a link to a vue knowldge base record preview?

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#13077]
### Description

Before vue Knowledge Base it was possible to create a link for example:
`https://gitdeveloper.yetiforce.com/index.php?module=KnowledgeBase&view=FullScreen&record=435422`
As the module is completely rebuild seems like there is no such functionality.

**Comment by vdpawel** [comment]
After entering the hyperlink, an error occurred ...

![obraz](https://user-images.githubusercontent.com/62466142/82762426-3932ae00-9e01-11ea-8262-aba12fbab663.png)

**Comment by z0lo13** [comment]
@vdpawel yes that feature was available on older version of yetiforce (4.4.0)

**Comment by mariuszkrzaczkowski** [comment]
Currently there is no possibility, only you can call a window with JS
https://github.com/YetiForceCompany/YetiForceCRM/blob/c349c404027bfb78bb50be50320c37b5631dcfd5/public_html/layouts/basic/modules/KnowledgeBase/resources/Detail.js#L9-L17
