### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#13072]
Hello, I was confused as how to use yetiforce. Is all yetiforce just an admin panel? how can I link it to my main website?

**Comment by waran70** [comment]
If you are still confused the answer is: https://yetiforce.shop/index.php?option=com_djcatalog2&view=item&id=27:platinum-package&cid=8:technical-support&Itemid=1071

Otherwise pls avoid throwing such an "out of space" confusions.

**Comment by ghost** [comment]
What do you mean "out of space" ? I thought this was the place for the free support? sry if wrong.

**Comment by vdpawel** [comment]
Yetiforce consists of a section intended for users and a control panel.
In the control panel, as required, panels, modules, widgets and other functionalities should be designed to give users a data management tool.

In many solutions, Yetiforce is integrated with other systems, e.g. Magento for ecomerce.

Read about CRM systems.

Here you have some useful information:
https://yetiforce.com/en/knowledge-base/documentation

You can connect to an existing website, e.g. via the API.
