### ISSUE TITLE
[bug] Send email task WF, missing message sender (from).

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13081]
Hi,

I'm using YF 5.3.0 with SPv4 on a Ubuntu dedicated VPS.

CRON & SMTP (postfix) are OK.
Test email received, SPF, DKIM & Dmarc = pass.
Sending an email from Roundcube using my SMTP : OK, message received.

Then, I've tried to send email using a workflow :
- sending email using an Email Template : OK
- send a simple email using **"send email" task -> KO !**
I've tried with a fixed email and also with variable like $(organization : 1|email1)$ but still no message sent.

Here's the log when using 'send email' task (KO), there is an issue with "from" header :
`May 25 14:13:57 vps postfix/pickup[21945]: 7167D7ECC7: uid=33 from=<www-data>
May 25 14:13:57 vps postfix/cleanup[22705]: 7167D7ECC7: message-id=<YuL3aQvyykGBa2IMsaQwM8nEZomLtprMAGwpktpIw@YetiForceCRM>
May 25 14:13:57 vps opendkim[22671]: 7167D7ECC7: can't determine message sender; accepting
May 25 14:13:57 vps postfix/qmgr[20695]: 7167D7ECC7: from=<contact@myowndomain.com>, size=1425, nrcpt=1 (queue active)
May 25 14:14:03 vps postfix/smtp[22707]: 7167D7ECC7: to=<firstname.lastname@gmail.com>, relay=mx0.myhoster.net[XXX.XXX.XXX.XXX]:25, delay=6.1, delays=0.16/0.02/5.8/0.14, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 49VwxR3hnrzgrpmQ)
May 25 14:14:03 vps postfix/qmgr[20695]: 7167D7ECC7: removed`

So the problem is here :
**May 25 14:13:57 vps opendkim[22671]: 7167D7ECC7: can't determine message sender;**

Here's the log of the test message sent (OK) when you save your settings on MailSmtp module :
`May 25 14:16:15 vps postfix/pickup[21945]: 5972E7ECC7: uid=33 from=<www-data>
May 25 14:16:15 vps postfix/cleanup[22774]: 5972E7ECC7: message-id=<V2yngtVpdWRoMH2IcqwuhO6nxEo1restbMbf79B8nI@YetiForceCRM>
May 25 14:16:15 vps postfix/qmgr[20695]: 5972E7ECC7: from=<contact@myowndomain.com>, size=2808, nrcpt=1 (queue active)
May 25 14:16:21 vps postfix/smtp[22776]: 5972E7ECC7: to=<firstname.lastname@gmail.com>, relay=mx0.myhoster.net[XXX.XXX.XXX.XXX]:25, delay=6.2, delays=0.08/0.02/6/0.06, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 49Vx053k8bzgtKKP)
May 25 14:16:21 vps postfix/qmgr[20695]: 5972E7ECC7: removed`

As you can see, SMTP test email, email from roundcube and sending email template are working well.
So unless I missed some config settings, I think there is an issue with the send email task.

Regards,

**Comment by copyyour** [comment]
I also encountered the same problem. This problem caused a 436 error in workflow sending emails. The cause of the error was that the sending email account was inconsistent with the smtp email account. Please help the administrator to solve it, thank you very much.

**Comment by apcloic** [comment]
@copyyour 
You may try the following patch but bear in mind that I'm not a programmer ;)
https://github.com/apcloic/YetiForceCRM/pull/1

**Comment by mariuszkrzaczkowski** [comment]
show SMTP configurations and e-mail task

**Comment by apcloic** [comment]
@mariuszkrzaczkowski 

![image](https://user-images.githubusercontent.com/2930560/83622545-6ebd6100-a590-11ea-9e50-76a29e3a4dc8.png)

![image](https://user-images.githubusercontent.com/2930560/83622843-ceb40780-a590-11ea-848e-aaec3ce6aa8b.png)

**Comment by mariuszkrzaczkowski** [comment]
in English language

**Comment by apcloic** [comment]
![image](https://user-images.githubusercontent.com/2930560/83624315-bfce5480-a592-11ea-9dec-f6f142caf69b.png)


![image](https://user-images.githubusercontent.com/2930560/83624121-8269c700-a592-11ea-868a-6c84379b292e.png)

**Comment by mariuszkrzaczkowski** [comment]
Delete from mail from task

it depends on the mail server configuration or allows you to send other domains or users in your name, so you probably have a problem

**Comment by apcloic** [comment]
@mariuszkrzaczkowski 
Yes, for sure deleting from mail from task works but this is just a workaround.

The issue occured whatever domain used, I don't think it's related to my MTA configuration because if I make the following changes, then it works as expected.
https://github.com/apcloic/YetiForceCRM/pull/1

I think the issue is due to the format used to store "from" data in s_#_mail_queue table.
If you fill the from field in your workflow email task, then "from" column  in s_#_mail_queue table always contains the word "Array" and nothing else.

I believe that from column in s_#_mail_queue table should be stored using Json format.
