### ISSUE TITLE
[Bug] Adding data widget does not work

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1308]
Version: 2.0.299
When adding a data widget to the summary page of a given module, nothing happens
1. Select 'Leads' module
2. Select 'Widgets'
3. Select '+ Add Widget'
4. Select widget type 'Data Summary'
5. Execute command 'Select'
=> Widget creation windows is closed and nothing happens, i.e., widget is not created

Note: This does work on test.yetiforce.com 2.0.0RC

**Comment by eptapsyxos** [comment]
Confirmed by me too.

**Comment by mariuszkrzaczkowski** [comment]
Did you check for the latest version?
I checked, and in my work complete correctly.
https://gitdeveloper.yetiforce.com/index.php?module=Leads&view=DashBoard

**Comment by diderich** [comment]
No, it does not work. I am talking about the widgets associated with the summary page, not the one on the dashboard!

**Comment by mariuszkrzaczkowski** [comment]
Show screenshot because for me correctly inserted.
See https://gitdeveloper.yetiforce.com/

**Comment by diderich** [comment]
We are not talking the same widgets! See screenshots below:
![img01](https://cloud.githubusercontent.com/assets/10230144/8495122/463fe94a-216b-11e5-9be8-696aaf4eb088.jpg)
![img02](https://cloud.githubusercontent.com/assets/10230144/8495124/4995c2b8-216b-11e5-90b7-38200bf857bd.jpg)

**Comment by diderich** [comment]
Still does not work on https://gitdeveloper.yetiforce.com!

**Comment by bpabiszczak** [comment]
This version updates automatically at 15:00, then check
