### ISSUE TITLE
[Question] error when adding record

### ISSUE THREAD

**Issue by martin-crockett** [YetiForceCompany/YetiForceCRM#13080]
hello i have a problem. when i create a new record in my custom module, it gives me this error message. but when i go back in my module the record is there and i can modify it and the error does not show when i save it. the error is only there when a new record is added. 

what could be the problem ?

![image](https://user-images.githubusercontent.com/45770116/82833352-c28ec280-9e8b-11ea-940c-a3233e822ac5.png)

**Comment by martin-crockett** [comment]
u_yf_crm_entity_label table (nobody touched this)
![image](https://user-images.githubusercontent.com/45770116/82833661-a8091900-9e8c-11ea-83ad-fcf5cb292f6a.png)

**Comment by martin-crockett** [comment]
vtiger_crmentity table (nobody touched this)

![image](https://user-images.githubusercontent.com/45770116/82833747-f28a9580-9e8c-11ea-8ef2-1b2cf10bfc04.png)

**Comment by vdpawel** [comment]
Here is the same problem #12768

**Comment by rskrzypczak** [comment]
install [serviece pack v4](https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.3.0)
