### ISSUE TITLE
[Question] Change status & priority of ticket (field is grey)

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13090]
Hello,

I am testing on V. 5.3 SP4.

I have some support tickets (Mails) in my queue (all waiting for validation/ "awaiting verification") and when trying to **change the status**, it isn't possible because the field is grey. 

![Screenshot_2020-05-26 Tickets Test 9](https://user-images.githubusercontent.com/13665806/82908858-da884400-9f68-11ea-9dbe-6befe1dd2f92.png)

Even with a new self created ticket... Also the **priority field** is affected.

![Screenshot_2020-05-26 Tickets Hinzufügen](https://user-images.githubusercontent.com/13665806/82908890-e4aa4280-9f68-11ea-9ab8-69f0c24844fb.png)

Thanks!

**Comment by vdpawel** [comment]
I may be wrong, but this field may be gray because it is changed by triggers when the appropriate conditions are met and the user should not change this field.

**Comment by blu-IT** [comment]
@vdpawel Thanks for your suggestion! 

Well, I did not define any conditions that ticket should be locked that way. Is this the "out of the box" behavior of yetiforce crm?
And where can I control conditions to see if anything has been set.

Thanks!

**Comment by blu-IT** [comment]
OK, I switched back with my vm snapshot on a fresh v 5.3 SP4 installation and status, priority etc. can be changed without any problems!

So it must be some problem with the imported data from my other system (maybe see also here https://github.com/YetiForceCompany/YetiForceCRM/issues/13064 )

I still would like to use my database import, but with the effect described above I can't test and use the system any more.

Any idea why these fields are grey and can't be changed?

**Comment by rskrzypczak** [comment]
You probably have values ​​in the gray fields that do not exists in the picklist.

```sql
SELECT `status` FROM `vtiger_troubletickets` WHERE `status` NOT IN (SELECT ticketstatus FROM `vtiger_ticketstatus`)
```
If this query returns something to you, it must be changed in the database or added to the picklist.

**Comment by blu-IT** [comment]
@rskrzypczak 

O.K. thanks, I tried that
 
```
MariaDB [yetiforce]> SELECT `status` FROM `vtiger_troubletickets` WHERE `status` NOT IN (SELECT ticketstatus FROM `vtiger_ticketstatus`);
Empty set (0.00 sec)
```

but there is no output and that's right, because I did not define/change anything for ticket status or priority in the picklist.
I remember I did some additional entries for customer/conatct type in the picklist, but I think this should not affect ticket status or priority.

So I guess something has happend to my database during upgrade to V. 5.3 or Update with SP4... - very strange.
Also a way to unlock these fields via database command would be a nice try, but I don't know how...

**Comment by rskrzypczak** [comment]
The only thing that comes to my mind is that you do not have permission to these picklist values.
check
![image](https://user-images.githubusercontent.com/10221999/83994049-911afa00-a955-11ea-9f15-d1ae7bc51194.png)

**Comment by blu-IT** [comment]
@rskrzypczak 

Hi, wow THANKS!!! 

This seems to be the point - looking at my testsystem **every picklist** and **every value is not accessible vor anyone anymore!**

![Screenshot_2020-06-08 Auswahlliste System Einstellungen](https://user-images.githubusercontent.com/13665806/84021978-d820e380-a985-11ea-9231-aa759dbb75d9.png)

Something must be gone very bad with the upgrade... 
I also compared these values also with my fresh installed vm snapshot and the settings are like form your screenshot, accessible. So it must habe been the upgrade that has gone wild...

OK, but now I am able to help myself. Thanks again!
