### ISSUE TITLE
[Question] Multiple assigned

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#13092]
Hello everyone, I want to set up multiple responsible persons in the project management, but in the related fields in the added field, the person responsible is not found. How can I solve this problem, thank you very much.

**Comment by blu-IT** [comment]
Do you have defined groups/departments in your systemwide config? If so, you should be able to define a group as responsible.

**Comment by copyyour** [comment]
thank you

**Comment by copyyour** [comment]
thank you
