### ISSUE TITLE
Bug - Campaign/Mass Email For Accounts not working

### ISSUE THREAD

**Issue by Andrew-W-Robinson** [YetiForceCompany/YetiForceCRM#13095]
Hi support, I'm using Yetiforce 5.3.0 and am creating a marketing campaign.
I have many accounts with primary email and I have configured the SMTP and the email is working.
Campaigns/Mass email works for both Leads and Contacts but not Accounts

The problem occurs when I tried to send email from the campaign module in Tabs Accounts,
when I select some accounts with the primary email address and click the button "Send Via Email" and click Send button in the Mass Email popup.

After I click it and I go to the Emails to Send menu, there is no email queue to be sent,  and no emails are sent.
Expected behaviour is emails are sent.
![ConfReport](https://user-images.githubusercontent.com/44470210/83015960-25fa2b00-a019-11ea-8806-6a7aa3c60c33.png)

**Comment by mariuszkrzaczkowski** [comment]
start by improving the server configuration, it can cause a lot of errors
