### ISSUE TITLE
[bug] 5.3 Whole products list when adding to Price Books

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#13099]
# 🐞 bug report

### ⁉️ Describe the bug

I has noticed lags when I add products to Price Book. Cause of bug - all products loaded to page instead standard 30 items per page.

![image](https://user-images.githubusercontent.com/8545791/83109151-8b0d5980-a0c9-11ea-85a5-deaf73e53b41.png)

### 👷 Testing

- [х] I confirm that I tested it at https://gitstable.yetiforce.com
Works well
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com
Products can't be selected to Price Books.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | local 5.3 SP4, gitdev 5.3.74, gitstable
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by vovpff** [comment]
@mariuszkrzaczkowski Where to dig?

**Comment by mariuszkrzaczkowski** [comment]
where does this modal appear?

**Comment by vovpff** [comment]
just one difference between my prod and fresh 5.3 in Products
```
--- ./modules/Products/Products.php     2019-10-22 11:24:48.000000000 +0300
+++ /home/f53/modules/Products/Products.php       2020-03-13 19:34:36.000000000 +0300
@@ -42,18 +42,7 @@
                'Part Number' => ['products' => 'productcode'],
                'Unit Price' => ['products' => 'unit_price'],
        ];
-       public $search_fields_name = [
-    // vov mod
-               'Product Name' => 'productname',
-               'Part Number' => 'productcode',
-               'Product quantity' => 'qtyinstock',
-               'LBL-QTYALLW' => 'vqtyallw',
-               'Vendor' => 'vendor_id',
-               'Manufacturer' => 'manufacturer',
-               'Sales terms' => 'etprodsalesterms',
-               // 'Unit Price' => 'unit_price',
-       // vov mod
-       ];
+       public $search_fields_name = [];

        /** @var string[] List of fields in the RelationListView */
        public $relationFields = [];
```

**Comment by vovpff** [comment]
@mariuszkrzaczkowski Select Records button in Products tab of Price Book
![image](https://user-images.githubusercontent.com/8545791/83112005-2b657d00-a0ce-11ea-91fd-c5530bff75f4.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski Any solution?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks!
