### ISSUE TITLE
Error CSRF!!!

### ISSUE THREAD

**Issue by JeRRimix** [YetiForceCompany/YetiForceCRM#1309]
In few days ago Yeti was begun not understanding error displayed on a picture below. I can't to enter to any items of top navigation ;( 

![image](https://cloud.githubusercontent.com/assets/13039836/8479074/ea737ad8-20c4-11e5-8b56-266963e676d8.png)

Protection CSRF - what is it???  Pls help!!!

**Comment by bpabiszczak** [comment]
Please check site_url in config/config.inc.php. Please use this same site to logon.

**Comment by JeRRimix** [comment]
I checked, it all right URL. The problem is that on one computer I entered into CRM without this error, but on another at the entering to the system displayed Protection CSRF- attempt to huck. It's very stranger :(((

**Comment by JeRRimix** [comment]
Additional information: I use two computers a regular workstation in the office, the second computer is a mini laptop Asus. In both cases, a browser Google Chrome of last version. The problem only occurs on a laptop when entering the same data. Maybe the problem with the mobile version?

**Comment by bpabiszczak** [comment]
Just like in my previous comment, I think that you use an incorrect address [e.g. you have / at the end of siteurl] and that’s the reason. If you describe your problem properly [include logs, screenshots, info about site_url from config.inc.php] and you check whether this problem exists also on local WAMP, you can open a new issue and we will take care of it.

**Comment by JeRRimix** [comment]
I think you are prejudiced!!!

In my first message I presented screenshot of problem. You recomend me check of site_url on config files. I was checked it is right. If you want to see here are strings of config file:

// backslash is required at the end of URL
$site_URL = 'http://crm.shopavenue.ru/';

// root directory path
$root_directory = '/var/www/vhosts/shopavenue.ru/crm.shopavenue.ru/';

// cache direcory path
$cache_dir = 'cache/';

// tmp_dir default value prepended by cache_dir = images/
$tmp_dir = 'cache/images/';

// import_dir default value prepended by cache_dir = import/
$import_dir = 'cache/import/';

// upload_dir default 
$upload_dir = 'cache/upload/';

What logs you talking about? Logs of server or logs of CRM? 
I have httpd on CentOs ver. 6 with Nginx. The server log files no contain errors beacuse probably it's scripting error and not a server.

The main question is why on one computer all right, and on other protection triggered???

**Comment by bpabiszczak** [comment]
Please change site url:
wrong: $site_URL = 'http://crm.shopavenue.ru/';
good: $site_URL = 'http://crm.shopavenue.ru';
[without /]

**Comment by bpabiszczak** [comment]
and if you enter site url, please dont use http://www [only http://]

**Comment by JeRRimix** [comment]
Good info! Thank you! It's work! I think you need add this info to manuals and change installation script that use slash "/" in end of site_url

**Comment by bpabiszczak** [comment]
Manual already has this information, waiting for the translation. I'm glad it helped. For the future give more details, we will help faster.
