### ISSUE TITLE
[Feature] Please remove ugly gray area in the comments

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#13091]
Hello friends, 

Can you guys please remove that ugly gray area from the comments? It looked so much better without the gray square in the comments. Just regular white background. 

Thanks.

**Comment by vdpawel** [comment]
Gray areas are cool for me, you should look for a solution where to change it on your system.
![obraz](https://user-images.githubusercontent.com/62466142/82980451-cd5f6980-9fe9-11ea-88d2-7e49bbaf48a8.png)

**Comment by blu-IT** [comment]
Well, I must admit grey is irritating - reminds me of my problem here ;-)

https://github.com/YetiForceCompany/YetiForceCRM/issues/13090

**Comment by JEEVAN28** [comment]
Thanks this helped me also
