### ISSUE TITLE
[bug] Workflow module - missing 'is empty' condition for multi-select combo box

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13094]
Hi,

Some conditions like 'is empty' or 'is not empty' are missing on Workflow module for multi-select combo box.

[X] I confirm that I tested it at https://gitstable.yetiforce.com

Temporary workaround fix : 
- edit workflow directly from the database in com_vtiger_workflows table.
- replace existing with the following part "operation":"is empty","value":null

Regards,

**Comment by vovpff** [comment]
@apcloic check `/modules/Vtiger/helpers/AdvancedFilter.php` and try to add missing conditions.

**Comment by apcloic** [comment]
@vovpff Thanks for you suggestions.

**Comment by mariuszkrzaczkowski** [comment]
create pull request 🙂

**Comment by apcloic** [comment]
@vovpff Thanks for the pull request! 👍
I definitely need to learn how to do pull requests 😉

**Comment by mariuszkrzaczkowski** [comment]
https://www.youtube.com/results?search_query=github+pull+request
