### ISSUE TITLE
[Error] Cron: syntax error, unexpected end of file, expecting ']'.

### ISSUE THREAD

**Issue by federico0100** [YetiForceCompany/YetiForceCRM#13106]
![SharedScreenshot](https://user-images.githubusercontent.com/62551450/83247130-671e4680-a1a3-11ea-8e78-ef163e678761.jpg)

This message appears when I try to enter the yeti administration. I believe it is a consequence of the end of the free disk space. Now I have added 30GB of space.

Thanks

**Comment by mariuszkrzaczkowski** [comment]
duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/12299
