### ISSUE TITLE
[Question] Change field label on Accounts screen

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#13104]
How do I change the field label from "Comments" to "Notes" on the Account Details page?

![image](https://user-images.githubusercontent.com/58600791/83158276-7eeebf80-a0fc-11ea-82a6-8460448730f4.png)
![image](https://user-images.githubusercontent.com/58600791/83158416-a9407d00-a0fc-11ea-88b9-b8f71ca8ba1e.png)

**Comment by vovpff** [comment]
@asperitigroup this is good question. You can easy change translation of `Desription` label by Language Management but `Comments` not replaced with standard tools

**Comment by asperitigroup** [comment]
Is it possible to edit a php file to "hard code" this change? I realise that this would not survive a system update, but the fix could be re-applied after update.  Which php file would I need to edit to do this?

**Comment by rskrzypczak** [comment]
Change or add (if there is no translation in the language settings) and everything will be fine.
![image](https://user-images.githubusercontent.com/10221999/83238484-c9bd1580-a196-11ea-9607-d50bdaa3ca34.png)
![image](https://user-images.githubusercontent.com/10221999/83239075-99c24200-a197-11ea-9c64-80ff23e5412d.png)

**Comment by asperitigroup** [comment]
Works perfectly, many thanks.
