### ISSUE TITLE
[bug] 5.3 bug with products category and Products and Services tab

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#13100]
# 🐞 bug report

### ⁉️ Describe the bug

Now in my local system I has 3 products `pr1`, `pr2` and `pr3`

Screenshot from `vtiger_products` table

![image](https://user-images.githubusercontent.com/8545791/83138509-91b0c680-a0f3-11ea-88d0-721427871b18.png)

Screenshot from `vtiger_trees_templates_data` table

![image](https://user-images.githubusercontent.com/8545791/83138990-51057d00-a0f4-11ea-9a4b-701538d9a344.png)

Screenshot from visible result In Leads Products and Services tab

![image](https://user-images.githubusercontent.com/8545791/83139072-772b1d00-a0f4-11ea-818e-0664cbdf2274.png)

Why `pr3` invisible in `Опции` group?

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |  5.3 SP4
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by bpabiszczak** [comment]
You have to show a video on how to trigger to on the test environment step by step.

**Comment by vovpff** [comment]
@bpabiszczak 
![interested in products](https://user-images.githubusercontent.com/8545791/91540296-44770780-e923-11ea-9c1b-5ddcc474f5d4.gif)

**Comment by adudekyeti** [comment]
Hi,
On this gif product named "pr3" is inactive, so that's why is not showing on the list under category "CRM applications".  That list show only active products.
Please verify if you have it active in your CRM. If the problem still persists, please write more info how to reproduce this bug.

**Comment by vovpff** [comment]
@adudekyeti on my system (gif in my first message) all products active but situation the same...
