### ISSUE TITLE
[Layout Bug] Setting 'Row height' to 'narrow' has no effect in editing mode

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1310]
Version 2.0.299

When setting the user property 'Row height' to 'narrow', the data in view mode is displayed in narrow mode.When switching to edit model, the display is identical to 'medium' mode. 

This works correctly under 2.0.0 RC

**Comment by mariuszkrzaczkowski** [comment]
Changing the appearance is working properly.
The difference between "wide" and "medium" is very small

**Comment by diderich** [comment]
Disagree. See picture.
Display mode: Both are the same.
Editing mode: In 2.0.0, 5 lines take the same space as 4 lines in 2.0.327
![narrow](https://cloud.githubusercontent.com/assets/10230144/8498671/cad2da8c-2189-11e5-81ad-fb9e92158c8d.jpg)
