### ISSUE TITLE
[Question] Trouble locating "attention" field in vtiger_account

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#13101]
I'm trying to change the field type of a field in vtiger_account from text to mediumtext but I can't locate the required field in myphpadmin! The field is from the Description details section of accounts and the field name is "attention", but I can't find this anywhere in vtiger_account or vtiger_accountaddress. Where is this field located?

**Comment by vovpff** [comment]
@asperitigroup fields `description` and `attention` located in `vtiger_crmentity` table for all records in the system.
