### ISSUE TITLE
[bug] Payments status is grey

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#13105]
# 🐞 bug report

### ⁉️ Describe the bug

I found solution of but what known from 5.2 for example on this issue https://github.com/YetiForceCompany/YetiForceCRM/issues/11664#issuecomment-541436836

I never used `Payments In` before but found what every new payment has Created status what can't be changed.

Cause of problem what status default value is `Created` instead `PLL_CREATED`

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3 SP4
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

### ❗️ Inform the community if you solve the problem

Bug can be solved with SQL query:

```
UPDATE `vtiger_field` SET `defaultvalue` = 'PLL_CREATED' WHERE `columnname` = 'paymentsin_status' AND `tablename` = 'vtiger_paymentsin';
```

**Comment by rskrzypczak** [comment]
Thanks but you should change default value only for paymentsin_status.
I think you can't change the status in the Payments Out module now :)

**Comment by vovpff** [comment]
@rskrzypczak yes you right! My mistake
