### ISSUE TITLE
[Question] Changing field type to mediumtext in table using phpmyadmin

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#13102]
I changed the field type of a notes field in the contact table to mediumtext using phpmyadmin, but when I edit the record, it still warns me that the maximum permitted size is 65535, not 16777215. If I use the YF edit fields module, I can't change the maximum field length, it keeps reverting to 65535. How do I get the field to accept more than 65535 characters?

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13002#issuecomment-625243698
