### ISSUE TITLE
[Question] Adding Products/Invoices block is not visible in Sales Invoices - YetiForce - self hosted

### ISSUE THREAD

**Issue by Ahm3dsay3d** [YetiForceCompany/YetiForceCRM#13113]
Adding Products/Invoices block (Image below) is not visible in Sales Invoices.... It was working perfectly a day ago. Until I changed something in the settings( do not know which) that caused this problem.
Any way that I can retrieve it back.

Version: YetiForce CRM 5.3 Service Pack v4

![image](https://user-images.githubusercontent.com/31971854/83330753-a925b600-a291-11ea-820e-59c8bbec3c15.png)

**Comment by vdpawel** [comment]
Software configuration -> Standard modules -> Edit fields -> Managing an advanced block -> Item name -> Edit -> add Modules: Products, Services

![obraz](https://user-images.githubusercontent.com/62466142/83354021-d1c3b380-a356-11ea-9de5-fbbd525b0da7.png)
