### ISSUE TITLE
[Question] I have trouble setting up smtp

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#13112]
I have trouble setting up smtp

When the setting is completed, you can receive a reminder email of the successful setting
However, when the email is triggered through the workflow, the following error message appears

The following From address failed:: MAIL FROM command failed, "MAIL FROM" doesn't conform with authentication [@ sm060104] (Auth Account: peng@pkuw.vip | Mail Account :)
, 436, SMTP server error: MAIL FROM command failed Detail: "MAIL FROM" doesn't conform with authentication [@ sm060104] (Auth Account: peng@pkuw.vip | Mail Account :)
SMTP code: 436SMTP server error: MAIL FROM command failed Detail: "MAIL FROM" doesn't conform with authentication [@ sm060104] (Auth Account: peng@pkuw.vip | Mail Account :)
SMTP code: 436

I don't know how to solve this. thank you very much

**Comment by apcloic** [comment]
@copyyour 
I also have problems with email function through workflow while smtp test email works great. 

Did you try using an email template instead of a simple send email task ?

**Comment by copyyour** [comment]
Thank you
I set up a simple email to send, and did not use the template

**Comment by apcloic** [comment]
@mariuszkrzaczkowski 
I don't understand why you close this issue.
Does it mean that you are aware of this issue and it will be resolved in YF 5.4 ?

**Comment by vdpawel** [comment]
I'm guessing, because the content matched the pattern of the solved issues:
1. Question
2. Answer
3. Thanks: "Thank you"

:)

**Comment by apcloic** [comment]
@copyyour 
https://github.com/YetiForceCompany/YetiForceCRM/commit/1517f86c2a01bb1cd2bafcf9784d61042205c317

**Comment by LjxFaighting** [comment]
没解决呀，这个到底怎么解决呢？
