### ISSUE TITLE
[Question] Annoying one

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#13119]
When 5.4 may eventually happen? 

Cheers

**Comment by simple-AMS** [comment]
@waran70  5.3 is working just fine for me so why would you want another version that breaks what's working good on 5.3 my friend lol

**Comment by TonyM15** [comment]
acsinsurancegroup enjoy your 5.3 and lol in your bedroom. The guy asking simple and reasonable question which (from point of view of those who pay respect to this project) keeps themselves and community on track of dynamic development which not happen in many projects as such.

**Comment by acsinsurancegroup** [comment]
@TonyM15 Glad you got that off your chest? @waran70 and I have helped each other on several occasions previously so we have a sorta of rapport if you will. I'm glad to know however that you are around to serve as everyone's Johnny Cochran should they need assistance. Now go play in your sandbox and STFU!

**Comment by waran70** [comment]
Are you talking to me? And if not why you so rude anyway?

**Comment by JohnMaverick** [comment]
The boy abusing teenager's forums abbreviations,  so probably 17+ max 20
No use to bother with.

**Comment by acsinsurancegroup** [comment]
> Are you talking to me? And if not why you so rude anyway?

No @waran70 I was telling DA Tony that you and I had interacted several times previously since he wanted to get all smart on my original comment. What started out as a joke has turned into a bunch of butt hurt overly sensititive pu$$i3$ getting riled up over nothing. Wow!
