### ISSUE TITLE
[Question] searching for Chinese

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#13114]
Hello everyone, I am a Chinese user. When I was using it, I found that searching for Chinese characters did not work. How should I set it up? Thank you very much

**Comment by mariuszkrzaczkowski** [comment]
give an example and a place to search

**Comment by copyyour** [comment]
<img width="450" alt="截屏2020-06-09 下午6 15 29" src="https://user-images.githubusercontent.com/27992939/84136005-47c5ca00-aa7d-11ea-9eeb-578a568f0fb1.png">

Entering Chinese here is invalid, the search result is always 0

<img width="1068" alt="截屏2020-06-09 下午6 16 58" src="https://user-images.githubusercontent.com/27992939/84136115-6f1c9700-aa7d-11ea-9e22-27329762c855.png">

**Comment by bpabiszczak** [comment]
I doubt we'll take care of it until the first Chinese customer comes to us. Maybe you have the wrong encoding set in the table.
