### ISSUE TITLE
[Question] Need to style differently 3 related lists in one pdf

### ISSUE THREAD

**Issue by IanMuller** [YetiForceCompany/YetiForceCRM#13111]
Guys, created PDF template and embedded related records lists (three)
I need to style those related records list separately (different table dimensions, text size etc)
What would be the shortest way to do so?
Thank you for help

**Comment by apcloic** [comment]
@IanMuller 
I think you have to create your own textparser script. 
#11491
Regards,

**Comment by konadrian** [comment]
You should create a three different text parser for each related list
