### ISSUE TITLE
[Question] Comments Contacts badge counts not shown for RelatedListCount

### ISSUE THREAD

**Issue by kalle3e** [YetiForceCompany/YetiForceCRM#13117]
### Description

In the version 5.3 I downloaded
Comments and Contacts badge counts not shown for RelatedListCount on the header.
![Screenshot from 2020-06-02 00-32-51](https://user-images.githubusercontent.com/64237549/83419840-13dd1a00-a469-11ea-8ffe-fd5ebd766693.png)
![Screenshot from 2020-06-02 00-31-41](https://user-images.githubusercontent.com/64237549/83419919-353e0600-a469-11ea-938a-52dd9ac0ce24.png)
![Screenshot from 2020-06-02 00-31-15](https://user-images.githubusercontent.com/64237549/83419993-48e96c80-a469-11ea-8e3d-de20671614c9.png)
This from the demo shows the badge counts
![Screenshot from 2020-06-02 00-38-27](https://user-images.githubusercontent.com/64237549/83420133-86e69080-a469-11ea-8d5a-f71349b90b82.png)

Would someone please tell me if I have missed something?

**Comment by vovpff** [comment]
`/config/Relation.php`

```
public static $SHOW_RECORDS_COUNT = true;
```
