### ISSUE TITLE
[Question] Newly setup of YetiforceCRM on Ubuntu causing problems 

### ISSUE THREAD

**Issue by kalle3e** [YetiForceCompany/YetiForceCRM#13128]
I just can't work out why adding comments work at one point then it doesn't. Also the count badges also disappear. Help! I thought it's got to do with file and user permissions but they seem to look in order so still can't figure it out.
![add comment doesnt work here](https://user-images.githubusercontent.com/64237549/83525435-5154ac80-a528-11ea-8055-c6c198229160.png)
![add comment doesnt work from commnent when its a part of](https://user-images.githubusercontent.com/64237549/83525476-5fa2c880-a528-11ea-8f06-605c5bf49d6e.png)
Update: I just look at log file and see that public_html off. This is probably where I need to fix ?

Update: Here's something I found and added to my /etc/apache2/apache2.conf
<VirtualHost *:80>
  ServerName localhost
  ServerAlias localhost
  DocumentRoot /var/www/html/yeti/public_html
   <Directory  "/var/www/html/yeti/public_html/">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    #Require local
    Require all granted
   </Directory>
</VirtualHost>
not too sure all this is correct for ubuntu

### Description

Update: Also attempted with these and didn't work
<Directory /var/www/html/yeti/public_html>
        AllowOverride FileInfo AuthConfig Limit
        Options Indexes SymLinksIfOwnerMatch IncludesNoExec ExecCGI
</Directory>

Need to mention I'm working on ubuntu 20.04 .

Update: As it turns out, what I'm experiencing above is part if a bug. Apprently my installation setup is OK. So  I'll close this and the issue I opened as I thought was relating to this.

**Comment by blu-IT** [comment]
I don't know if this helps, but when I installed yetiforce on Ubuntu I had to define a IP in my apache2.conf, e.g.:

ServerName 192.168.1.10
ServerAlias 192.168.1.10

So look what the IP of your system is and try defining it in your apache2.conf **and** yeti/config/Main.php

/** Backslash is required at the end of URL */
public static $site_URL = 'http://yeti/';

For additional information you may check here:

https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/migration-to-a-new-server
