### ISSUE TITLE
[Question] Date Text in calendar column headers in week view.

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#13126]
Is it possible to change the date format to UK style DD/MM in the calendar headers?  At the moment, Monday 8th June is displayed as Mon 6/8.  I would like it to show as Mon 8/6.
![image](https://user-images.githubusercontent.com/58600791/83500499-bec7f500-a4b6-11ea-9af4-ad5581234caf.png)

**Comment by asperitigroup** [comment]
Does anyone have a suggestion for the resolution of my question?

**Comment by vovpff** [comment]
@asperitigroup I think you can check .tpl files for extended calendar and rebuild rendering as you need. Maybe some additional function should be written to avhieve this.

**Comment by asperitigroup** [comment]
Thanks for your help, where are the .tpl files located? Can I edit them directly?

**Comment by vovpff** [comment]
@asperitigroup check here /path/to/crm/layouts/basic/modules/Calendar/
Yes. This is smarty

**Comment by asperitigroup** [comment]
Many thanks for your help, I'll have a look and see if I can modify the layout.
