### ISSUE TITLE
Calendar view Uneven lines iin header calendar. 

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1312]
In calendar view (month, week, day) are uneven lines 
![Error](https://cloud.githubusercontent.com/assets/3193498/8493424/17b060c0-215a-11e5-9dfd-8b06f14735f0.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/27fa2619569ce55c041525cccfa7e13f0d861f05
