### ISSUE TITLE
[Question] Installed Yetiforce using Softaculous on subdomain not loading

### ISSUE THREAD

**Issue by bambatha** [YetiForceCompany/YetiForceCRM#13129]
Hello,

I attempted to install Yetiforce using Softaculous on subdomain however the software doesn't load and gives HTTP ERROR 500 yeti.domain.com is currently unable to handle this request.

**Comment by vovpff** [comment]
Check server configuration

**Comment by KatarzynaUlichnowska** [comment]
Hello,
please report the issue to Softaculous https://softaculous.deskuss.com/open.php
