### ISSUE TITLE
Yetiforce CRON setup

### ISSUE THREAD

**Issue by UNITE-Man** [YetiForceCompany/YetiForceCRM#13130]
I'm struggling getting Yetiforce "Cron mechanism status" to change to be working.
Does anyone have some examples of what the cron.sh & crontab configs should look like?
I'm a complete newbie at Linux!

**Comment by blu-IT** [comment]
@UNITE-Man 

Have you already looked here?

https://yetiforce.com/en/component/zoo/item/enable-cron

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/crons.conf

**Comment by UNITE-Man** [comment]
> @UNITE-Man
> 
> Have you already looked here?
> 
> https://yetiforce.com/en/component/zoo/item/enable-cron

Yes I've read that - but to be honest its not very clear - I was hoping to get some examples of working configs so I could check against mine ;-)

**Comment by UNITE-Man** [comment]
> https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

Yes I've read that - but to be honest its not very clear

**Comment by UNITE-Man** [comment]
> https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

Yes I've read that - but to be honest its not very clear

**Comment by UNITE-Man** [comment]
> https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/crons.conf

Thanks - I'll see how that compares with what I have - much appreciated

**Comment by UNITE-Man** [comment]
I know this is going to make people roll eyes but I'm stuck at the simple task of where do I create the crontab? The default is in tmp/ which obviously doesn't persist - but wherever I create the file Yetiforce still insists that crontab isn't running. Apologies if this is a stupid question - I'm really new at Linux.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/Dockerfile#L52

**Comment by UNITE-Man** [comment]
> https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/Dockerfile#L52

Really appreciated. I have a crontab file in that location & still Yetiforce says cron is not activated. But it is! I've obviously got something wrong in my setup. I can't even get a simple test cron to work!

**Comment by blu-IT** [comment]
Are you logged in as root?
Type `crontab -e` and copy this line into your crontab
`*/5 * * * * sh /path-to-crm/cron/cron.sh > /path-to-crm/cache/logs/cron.log 2>&1` 

**[pay attention to a correct path to the YetiForce system]** and also follow the other steps in the documentation https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

That's all!

**Comment by mariuszkrzaczkowski** [comment]
this is not an error in the CRM system, you must ask the administrator for help
