### ISSUE TITLE
[Question] Adding Modules Comments issues

### ISSUE THREAD

**Issue by kalle3e** [YetiForceCompany/YetiForceCRM#13133]
### Description

Adding Modules Comments issues
This is not a problem in the developer/demo version

My setup: Version 5.3 Newly setup on Ubuntu 20.04 on localhost
Unable to add Comments to Modules until it has been properly initialised

Update of point 1.) below

1. When you first enter the Detail Page from the List of Accounts, and accessing the Comments in the Comments Widget and try to add a comment here, it doesn’t work.
Solution: WIth a bit of fidgiting - instead of scrolling down to the comment widget and click on the down arrow and start typing in  a comment and then save, you need to click on another tab other than the 'Comments' - as this initialise some vars and badge counts are displayed tthen now  you click on 'Comments' tab then at this stage you can scroll down and type in a comment and hit 'save' and it now works. Similarly for 2) below

2. When in open an Account and go  to Detail, Click on Comment tab the function to add comment or reply to comment are not working. 
Solution: Have to click on another tab, then clicking on the Comments (now it shows the badge count, it seems to only initialise vars at this stage) then now adding or replying to comments will now work.

The developer/demo version doesn’t have this issue. Just wondering if someone could have any ideas about something that I might have missed. Thank you
![Doesnt work when first coming here](https://user-images.githubusercontent.com/64237549/83593907-32dec780-a5a1-11ea-8243-3b7c79d71872.png)
![Cant add comments  from here](https://user-images.githubusercontent.com/64237549/83593942-4722c480-a5a1-11ea-9bbc-a296041f230f.png)

**Comment by mariuszkrzaczkowski** [comment]
Before reporting an issue, check if your server has been properly configured. 
Please include a screenshot of your configuration.

![github](https://user-images.githubusercontent.com/10198654/83599648-fdb88200-a56c-11ea-8c7e-65107dfbb455.jpg)

**Comment by kalle3e** [comment]
Thanks @mariuszkrzaczkowski 
I have attached the server config as requested.
![ConfReport (1)](https://user-images.githubusercontent.com/64237549/83861290-bd6f2480-a763-11ea-89db-b9d00c605816.png)

Also, as seen from  the server config attached, incorrect are the character_set_server  and character_set_database are not utf8 (as the settings in the cnf file are not successful). - not sure if this can cause any problems as they are quite similar.

![Screencast-from-05-06-20-132353](https://user-images.githubusercontent.com/64237549/83834417-a0b9f900-a731-11ea-98f5-49f36aaf7666.gif)

**Comment by TonyM15** [comment]
Why you reporting errors while your server config doesn't meet required conditions?
You wasting your time - and mine as I cannot stay still and not comment it :/

**Comment by kalle3e** [comment]
I've been trying to match a few server settings with those on gitdeveloper
Outstanding are still: user_dir, open_basedir, sql server - character_set_server utf8, (AND settings for the CRON(CLI)) - this I'll get to
Please help me! Anyone?
Attached here are - server config, apache.conf, php.ini (very partial- just the lines added)

From /etc/php/7.4/apache2/php.ini
![Screenshot from 2020-06-07 01-44-27](https://user-images.githubusercontent.com/64237549/83948439-90ed0280-a860-11ea-8c4a-704cf50838eb.png)
![Screenshot from 2020-06-07 01-31-24](https://user-images.githubusercontent.com/64237549/83948441-92b6c600-a860-11ea-9697-2cb46bb2f32f.png)

local apache.conf located at /var/www/html/yeti which is included in the main /etc/apache2/apache2.conf
![Screenshot from 2020-06-07 01-54-29](https://user-images.githubusercontent.com/64237549/83948722-79167e00-a862-11ea-93f2-efc19e76ca69.png)
memory_limit too low ?
![Screenshot from 2020-06-07 02-14-46](https://user-images.githubusercontent.com/64237549/83949027-d0b5e900-a864-11ea-8853-ce222683a364.png)

Server config
![ConfReport](https://user-images.githubusercontent.com/64237549/83949125-736e6780-a865-11ea-8018-b77150e40aa2.png)

settings for the CRON(CLI)) - are these settings of the php.ini in CLI dirs ? 
  under the CRON (CLI) headings they're all empty. What do I need to do please?

Thanks

**Comment by vovpff** [comment]
@kalle3e I'm not an linux guru but maybe my advice help you.

Apache2 should hook php setting from `.user.ini` in `crmroot/` or `crmroot/public_html` folder. Maybe some wed server tuning needed to achieve this.

Other lifehack - you can use custom `.ini` file for CRON by this `cron.sh`. I'm not sure what this is proper configuration but works well and php params for Apache2 and CLI equal an this case and can be changed in `crmroot/public_html/.user.ini`

```
export CRM_ROOT_DIR=`dirname "$0"`/..
export USE_INI=crmroot/public_html/.user.ini
export USE_PHP=php7.3

cd $CRM_ROOT_DIR

#       TO RUN ALL CORN JOBS
$USE_PHP -q -c $USE_INI -f cron.php
```

**Comment by kalle3e** [comment]
@vovpff 
Very sweet of you for the pointers.  Now there's something for me to work on. Thanks so much.

**Comment by kalle3e** [comment]
@vovpff I tried. I tested in both dirs -
.user.ini placed in crmRoot  being equal to /var/www/html/yeti as well as crmRoot/public_html
![Screenshot from 2020-06-07 04-41-29](https://user-images.githubusercontent.com/64237549/83952060-75dabc80-a879-11ea-9f6d-4f479587a089.png)
![Screenshot from 2020-06-07 04-40-32](https://user-images.githubusercontent.com/64237549/83952063-77a48000-a879-11ea-86a4-769b6a9eaa07.png)
restarted apache, .user.ini didn't seem to pick up the config for user_dir or open_basedir  > no changes :(
What to try next? If someone has set up their own environment would surely remember!

**Comment by vovpff** [comment]
run

```
php7.4 -v
```

output should be

```
PHP 7.4.6 (cli) (built: May 14 2020 10:02:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies
```

if `php7.4` correct then try to run  

```
php7.4 -q -c /var/www/html/yeti/.user.ini -f /var/www/html/yeti/cron.php
```

and check output

**Comment by kalle3e** [comment]
@vovpff 
so here's output
[output6.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/4740906/output6.txt)

**Comment by vovpff** [comment]
You have troubles with permissions. Try

chown -R www-data:www-data /path/to/crm

**Comment by kalle3e** [comment]
@vovpff already is
![Screenshot from 2020-06-07 06-02-02](https://user-images.githubusercontent.com/64237549/83953556-7593ee80-a884-11ea-9ba1-de266c56941f.png)

**Comment by kalle3e** [comment]
@vovpff there seems to be alot of files created and populated here aren't there?
![Screenshot from 2020-06-07 06-06-40](https://user-images.githubusercontent.com/64237549/83953648-3dd97680-a885-11ea-86ac-546d52b1e931.png)

**Comment by vovpff** [comment]
@kalle3e what you mean?

Check system configuration now.

**Comment by kalle3e** [comment]
@vovpff Oh yes there's CRON(CLI) now
![ConfReport (2)](https://user-images.githubusercontent.com/64237549/83953859-65314300-a887-11ea-9241-082b1e9a0663.png)
Thanks so much! 
....there's still the user_dir - this is problably stop the scripts to work, is that why I still can't add 'Comments' without fidgeting to get initialisation

**Comment by kalle3e** [comment]
@vovpff did you see the new server config?

**Comment by kalle3e** [comment]
I still have the issue with adding comments. I need help with config user_dir (and open_basedir); SQLD character_set_server still utfmb4. Anyone ?

**Comment by mariuszkrzaczkowski** [comment]
PHP 7.4 is not yet officially supported.

**Comment by kalle3e** [comment]
@mariuszkrzaczkowski So I need to download php7.3 or something lower? And then use the php. ini relating to that version?

**Comment by mariuszkrzaczkowski** [comment]
7.3 is ok
