### ISSUE TITLE
[bug] Workflow - send emails to related list not working

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13136]
On YF 5.3, I've created a workflow that send emails to related list.
For example, send emails to related contacts of an account.
It doesn't work and throw the following error :
![image](https://user-images.githubusercontent.com/2930560/83639476-092a9e00-a5ab-11ea-8cf5-c49b25d7014c.png)

In order to make it work, I had to do the following changes in app/Mailer.php
https://github.com/apcloic/YetiForceCRM/pull/2/files

As I'm not a programmer, I don't know if it's the right way to solve the issue.
Regards

**Comment by apcloic** [comment]
Also, it looks like using conditions on related list is not working.
`$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]||2)$`

I've tried to use related list as recipient (To:), it gets truncated like this:
`Contacts|firstname,lastname|[[[`

(tested on my system **and gitstable YF**).

I've tried inside body email, it is sent as simple text.
$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]||2)$

However, using the basic $(relatedRecordsList : Contacts)$ works on both (with patched Mailer.php) but it's quite limited.

**Comment by mariuszkrzaczkowski** [comment]
Does the problem still exist in the newest version?

**Comment by apcloic** [comment]
@mariuszkrzaczkowski 
Hi, I've just give a try.
It looks like using conditions on related list is still not working but maybe it's not supposed to work.
I mean using trying to filter recipient (To:) related list like this :
 $(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]||2)$
Because it's truncated after saving the task :
$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[[
However, it works as expected when using $(relatedRecordsList : Contacts)$
