### ISSUE TITLE
[bug] Search doesn't work for accounts with short names

### ISSUE THREAD

**Issue by zazy** [YetiForceCompany/YetiForceCRM#13137]
# 🐞 bug report

### ⁉️ Describe the bug

When searching for an account using the search field in the top left, if you are looking for an account with a short name with 3 letters it will not be found.
This happens with every search criteria: words begin with, word, Begins with etc.

### 🔥 How to trigger the error

1. Add an account with name ABC Trading
2. Click on the search field in the top left corner of the screen and start typing ABC
3. The "loading" icon appears and then disappears revealing no results

### 👎 Actual Behavior

No result list appears and account is not found

### 👍 Expected Behavior

See the account in the pop-up search results

### 👷 Testing

- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3 SP4
| Web server (name and version)       | Apache 2.4                |
| PHP                                 | FPM 7.2               |
| Browser (name and version)          | Chrome 83.0.4103.61 |
| Operating System (name and version) | Linux Ubuntu 20.04               |
| Database (name and version)         |  MySQL  5.7.30             |
| Service Pack version                |  4              |

**Comment by rskrzypczak** [comment]
Check your mysql configurations: `SHOW VARIABLES LIKE 'ft_min_word_len'`
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/db/mysql.cnf#L31

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/83758629-a7ce0200-a672-11ea-9dac-387ba550c087.jpg)
