### ISSUE TITLE
[Question] How to turn on public_html

### ISSUE THREAD

**Issue by kalle3e** [YetiForceCompany/YetiForceCRM#13131]
### Description

HIi I'm running on Ubuntu 20.04  on my localhost, public_html is currently off and its need to be turned on. Tried a few settings but alas none has been working referenced here #13128 . Would someone please point me in the right direction to get this sorted, thanks. :) :) 
I feel that this could be  problem to my issues over here #13128  

Any help is much appreciated.

Update: As it turns out, what I'm experiencing in #13128 is part if a bug.  Apprently my installation setup is OK. So I'll close this as well. I'll open a new issue for the bug.

**Comment by blu-IT** [comment]
See my comment https://github.com/YetiForceCompany/YetiForceCRM/issues/13128#issuecomment-637800757
