### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by jjbautist1** [YetiForceCompany/YetiForceCRM#13143]
Hi, 

In module relationships the create relationship  does not appear button, how can I create a relationship between modules?
![Imagen1](https://user-images.githubusercontent.com/64044693/83797377-2bcebc80-a668-11ea-847f-9ef839ba8c33.jpg)

**Comment by vovpff** [comment]
`/config/Developer.php`

```
public static $CHANGE_RELATIONS = true;
```

**Comment by jjbautist1** [comment]
Thank you

**Comment by vovpff** [comment]
@jjbautist1 no problem!
