### ISSUE TITLE
[Question] Workflow data sending logic, hope to get help

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#13149]
I want to send all the collection data of an employee to his mailbox regularly, how do I set it up?
Or I will warn the collection data, and automatically send the collection data to his mailbox in the next seven days.
I am so clueless and need help, thank you very much

**Comment by vovpff** [comment]
What you nean for collection data

**Comment by copyyour** [comment]
My needs are like this:
For example, if the estimated time for a payment is within 30 days, I will send a warning message of this payment through the workflow every week, but currently I can't achieve it by configuring the workflow.

Hope to get help. Thank you

**Comment by vovpff** [comment]
@copyyour you can do it by self-written handler. For this you need a programmer.

**Comment by copyyour** [comment]
I am still trying to see if there is an easy way
