### ISSUE TITLE
copy field Unit Price

### ISSUE THREAD

**Issue by jjbautist1** [YetiForceCompany/YetiForceCRM#13144]
how can i add the unit price field in a new module with the same characteristics of the existing one in services and products?

![campo](https://user-images.githubusercontent.com/64044693/83808054-afdd7000-a679-11ea-9b51-e8e9f1f15702.png)

**Comment by vovpff** [comment]
@jjbautist1 what is your target? 

i'm not sure what this this will work but you can try

- backup database
- add new field text to custom module
- change manually field uitype in database in vtiger_field table, also check other params
- change field params in your custom module table
- test carefully before use this in your prod

**Comment by vovpff** [comment]
@jjbautist1 also you can try to use vtlib to add field but I can't help you here

**Comment by bpabiszczak** [comment]
You can use in
Software configuration > Standard modules > Edit fields > "Advanced button"

![image](https://user-images.githubusercontent.com/10197525/91488646-e230ef00-e8af-11ea-87ba-8f7aceebaa9f.png)
