### ISSUE TITLE
[Question] Robienie zgloszenia z maila

### ISSUE THREAD

**Issue by sliwa08** [YetiForceCompany/YetiForceCRM#13153]
Witam,
podsiadam Yetiego w wersji 5.1.0 i wiem ze kiedys w poczcie roudcube jak dostawalem maila, moglem z niego utworzyc zgloszenie. Wyskakiwal taki pasek z opcjami co chce zrobic z danym mailem. Teraz mi ten pasek zniknal i nie wiem czemu.
Dodam,  ze mam opcje tworzenia zgloszenia nadane w panelu administracyjnym, tylko ten pasek od opcji mi sie nie wyswietla.

**Comment by bpabiszczak** [comment]
Zalecamy aktualizację do 5.3. 
Pasek działa poprawnie o ile konfiguracja jest poprawna. Brak logów i brak informacji o konfiguracji, więc nie mamy jak pomóc.
