### ISSUE TITLE
[Question] Vendor Balance after receiving products

### ISSUE THREAD

**Issue by Ahm3dsay3d** [YetiForceCompany/YetiForceCRM#13160]
How can we add credits to vendors after they supply a product/Service to the inventory?
Example: Let's say VendorX supplies ProductA at cost of 100USD.... after he supplies a quantity of 10 of productA, we need to track that we owe him 100*10 = 1000USD of that product!
is that possible in Yetiforce ?

The same applies to services>
Example: Let's assume a vendor provide me a service that I will add to a sales invoice to my customer, how can we track the amount that we owe to the vendor?

Thank you!

**Comment by vovpff** [comment]
@Ahm3dsay3d you can calculate total credits by self-written handler.

**Comment by Ahm3dsay3d** [comment]
@vovpff  Can you please elaborate further?
Thank you.

**Comment by vovpff** [comment]
@Ahm3dsay3d this is difficult to describe. You can check exists handlers in `module/modulename/handles` folder to understand what I mean

**Comment by Ahm3dsay3d** [comment]
@vovpff  Thank you ... I do not code in PHP. but thanks though

**Comment by vovpff** [comment]
@Ahm3dsay3d you can charge for this to yetiforce crew

**Comment by Ahm3dsay3d** [comment]
I can't afford to do this now...
