### ISSUE TITLE
[Question] Rounding total invoice & Payment status ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13167]
Hi,

We have an issue with invoice status on some records.

$sumOfGross : 499.99615 (PaymentsIn/models/PaymentStatus.php) 
Total invoice : 500€ (automatically rounded because of 2 currency decimals config)

Now, we add the related PaymentIn with the 500€ as value.
Wait for cron task to run.
-> Then invoice Status turns to OVERPAID

Question : Is there any way to configure YF to update invoice status based on rounded total ?

**Comment by vovpff** [comment]
My solution to round $sumOfGross for 2 decimals before comparison to change status.

**Comment by apcloic** [comment]
@vovpff thanks a lot for your suggestion.
I can do this for sure in PaymentsIn/models/PaymentStatus.php
However, I still think that it may not be very clear for YF users because from the GUI, you see an invoice which sum_gross is 500€ (rounded value) and a PaymentIn with value 500€ (real amount paid by the client)...so it looks perfect and not OVERPAID ;p

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/e908a1745d8d72f01c3bb7b3aa02a6b8731f5542/modules/PaymentsIn/models/PaymentStatus.php#L107

Change from 8 to 2

**Comment by apcloic** [comment]
Thanks @mariuszkrzaczkowski
