### ISSUE TITLE
[bug] SQuotes account and Status are readonly

### ISSUE THREAD

**Issue by ad1rie1** [YetiForceCompany/YetiForceCRM#13178]
# 🐞 bug report

### ⁉️ Describe the bug

in a clean install, i'm on the administrator account  and account and Status are readonly 

![image](https://user-images.githubusercontent.com/1949622/84648181-eda58880-af04-11ea-819a-b435a01a9faf.png)

as you see, you cannot do modification , on the html, the flag readonly is set
![image](https://user-images.githubusercontent.com/1949622/84648368-3e1ce600-af05-11ea-9338-04f33bd91aab.png)

in the database, the fiels is not readonly : 
![image](https://user-images.githubusercontent.com/1949622/84648573-820feb00-af05-11ea-9680-8c37349407dd.png)

i am superadmin, but in profil, the field is not readonly : 

![image](https://user-images.githubusercontent.com/1949622/84648751-bedbe200-af05-11ea-8d17-31c93a03dcb1.png)

i dont understand because, in all other module, picklist working fine.

### 🔥 How to trigger the error

1. on clean install Go to Quote
2. Try edit status or Account
3. the field is readonly

### 👎 Actual Behavior

readonly

### 👍 Expected Behavior

Editable :)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |  5.3
| Web server (name and version)    : apache 2
| PHP                                 : php 7.2
| Browser (name and version)         google chrome
| Database (name and version)       MarriaDB

**Comment by ad1rie1** [comment]
I forgot, this bug is present on Demo website, dev and stable ;)

**Comment by vovpff** [comment]
This is not a but. You need to select opportunity first and this two fields will be filled automatically with data from opportunity

**Comment by konadrian** [comment]
This "bug" is not exists in dev and stable version. As @vovpff said you should select first the opportunity. Status field is editable. I suppose that you have in record status value that not exists in picklist
