### ISSUE TITLE
Automatic Detecting Vhost Instance

### ISSUE THREAD

**Issue by wnunezc** [YetiForceCompany/YetiForceCRM#13173]
i have setting up some instance demos or dev:

```
<VirtualHost *:80>
	ServerAdmin icarosnet@gmail.com
	DocumentRoot "\xampp\htdocs\dev\demo"
	ServerName demo.local
	ServerAlias *.demo.local
	<Directory "\xampp\htdocs\dev\demo">
		Options Indexes	
		AllowOverride All
		Require all granted
		Allow from all
	</Directory>
</VirtualHost>
```

but i am getting some errors :

> Directory not found: vendor/rmccue/requests. For more information, visit https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/category/installation-updates

> Warning: require_once(C:\xampp\htdocs\dev\t2/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\dev\t2\include\ConfigUtils.php on line 12
> 
> Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\dev\t2/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\dev\t2\include\ConfigUtils.php on line 12

And i cant find the vendor folder; I believe that the installation instance must be dynamic and detect the working path; recreate the variables related or suggested to the installation instance, so that the setup is more friendly.

**Comment by rskrzypczak** [comment]
> Automatic Detecting Vhost Instance

This is not a problem.

**Download the "complete" version** (https://github.com/YetiForceCompany/YetiForceCRM/releases).
If you don't download the "complete" version, you will have to install the libraries using yarn and composer before installing the system. After that you will have the vendor folder.
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/crm-installation

**Comment by arcanisgk** [comment]
this not an issue; is a feature:
i want to set this html code example and make output a pdf file with same structure:

https://codepen.io/pablojgarea/pen/XbMEjR
