### ISSUE TITLE
disable branding 

### ISSUE THREAD

**Issue by SaGaKSA** [YetiForceCompany/YetiForceCRM#13177]
hello every one 
i have bought the disable branding and I don't Know how to install it or active it any ideas ?
thank you

**Comment by simple-AMS** [comment]
@SaGaKSA You will receive an email once the YF team processes your information along with the instructions on how to disable the branding. Be patient as it could take up to a few weeks as they are extremely busy. You can also email them and be sure to include your transaction information to possibly speed up the process. Hope that helps :)
