### ISSUE TITLE
[Question] Yetiforce on PostgresDB

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#13175]
Hi,
I have a rquest to install Yetiforce on a Postgres Database.
I found some Info that someone tried it with YF version 3.4 but  since then there is no mention of it.

What is the status? 
Make it sense to try it?

Thanks,
Stefan

**Comment by bpabiszczak** [comment]
Database engines other than MySQL and MariaDB recommended for corporations that have the resources for patches and tests.

**Comment by ghost** [comment]
Hi @bpabiszczak,
my client would be such corporation! 
Can you give me any guidence or share your knowledge on how to get started with Yetiforce on Postgres?
Being able to demonstrate that YF is running on Postgres, at least Login & Dashboard, would help to bring the client on board.

Thank you, for your help in advanced

**Comment by bpabiszczak** [comment]
The programmer needs to improve some queries to the database, and test the system. We estimate it for 100-200h depending on the database engine.
