### ISSUE TITLE
[bug] <style> stripped from RoundCube

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#13188]
# 🐞 bug report

### ⁉️ Describe the bug

The responsive email templates are not supported as style tag is completely stripped when trying to save. The <style> tag is working absolutely out of box on plain Roundcube. Please provide the information on where exactly this tag is sanitized, i was not able to find any commits related to this. 
### 🔥 How to trigger the error

sample html email template:
```
<style type="text/css">#message-htmlpart1 div.rcmBody { color:#666666; }</style>
<div id="message-htmlpart1" class="message-htmlpart">
<div class="rcmBody">
<table>
<tbody>
<tr>
<td>This is body text in html part</td>
</tr>
</tbody>
</table>
</div>
</div>
```

### 👎 Actual Behavior
![image](https://user-images.githubusercontent.com/23143958/84822462-b1e4ee80-afea-11ea-8888-4cf084b42205.png)

css is striped
### 👍 Expected Behavior

![image](https://user-images.githubusercontent.com/23143958/84822500-c1fcce00-afea-11ea-8572-6eb1f7635720.png)

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by davide-alghi** [comment]
Hi @z0lo13,
if I understand you are
- creating an email template with <style> tag
- including the email template into RoundCube email editor via import button
- <style> tag is no more available
If this is correct, the sanitizer is the email template editor (on saving), not RoundCube.
I discourage to change sanitizing code.
I suggest you to create a custom Textparser function including style (inside <style> html tags) and then call the new function in you email template.
More: you can create a textparser function with many different styles and select the required style by parameter. An example.

- create a custom textparser function eg named z0loCustomStyles(.php)
- in z0loCustomStyles.php you have your styles into a switch($style) {...} - let's suppose five styles, so $style is in [1...5] range
- $style come from $this->params: $style = $this->params(0)

in email template you have to call the new function with
**$(custom : z0loCustomStyles||x)$**
where x is the needed style to use - x in [1...5]

**Comment by z0lo13** [comment]
Hi @davide-alghi,
Thanks for taking a look into it.

yes and no, for newsletters yes we are using email template.
However, we also have usual email signature (Roundcube->Settings->Identitities->Signature->Source Code) in html as an initial email template. So when employee is composing a new email the template is already pre populated. In this scenario i suppose it striped in Rouncube. As i checked a clean Roundcube instance and it is working just fine.
I am definitely will use you suggestion for the templates.

**Comment by ArniSamano** [comment]
THis is pretty weird. System have functionality which cannot be used in some certain areas. 
For me roundcube work OK but designing workflow email template completely gets out of space.
Wondering why is like that



> Hi @z0lo13, if I understand you are
> 
> * creating an email template with <style> tag
> * including the email template into RoundCube email editor via import button
> * <style> tag is no more available
> 
> If this is correct, the sanitizer is the email template editor (on saving), not RoundCube. I discourage to change sanitizing code. I suggest you to create a custom Textparser function including style (inside <style> html tags) and then call the new function in you email template. More: you can create a textparser function with many different styles and select the required style by parameter. An example.
> 
> * create a custom textparser function eg named z0loCustomStyles(.php)
> * in z0loCustomStyles.php you have your styles into a switch($style) {...} - let's suppose five styles, so $style is in [1...5] range
> * $style come from $this->params: $style = $this->params(0)
> 
> in email template you have to call the new function with **(custom:z0loCustomStyles||x)** where x is the needed style to use - x in [1...5]
