### ISSUE TITLE
[bug] Notifications title  $(record : RecordLabel)$

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13193]
my notifications come like this for some modules like contacts, project tasks, and comments.

Admin owner added $(record : RecordLabel)$ 

where as the  " $(record : RecordLabel)$ '  should display what was added like other modules link or comment link or status change link etc.  as it happens when we add lead a proper notification comes or accounts or opportunity..

any help would be deeply appreciated

**Comment by konadrian** [comment]
The variable $ (record: Record Label) $ holds the value of the record label. For example for the Yetiforce account it will be "Yetiforce". If would like to display link for leads in crm you should pick another variable for example 
$(relatedRecord : pssold_id|CrmDetailViewURL)$

**Comment by rioshaz** [comment]
@konadrian so where and what i have to change ... i didnt alter any code... 
this is happening on its own.. its a bug in yetiforce i guess..
all info here 👍 
[https://github.com/YetiForceCompany/YetiForceCRM/issues/13318]

**Comment by bpabiszczak** [comment]
Issue 13318 has fixed
