### ISSUE TITLE
[bug] OSSMailScanner  ERR_NOT_ALLOWED_VALUE

### ISSUE THREAD

**Issue by Andr198** [YetiForceCompany/YetiForceCRM#13195]
### Scanner stopped working 
Cron error MailScanner

App\Exceptions\IllegalValue: ERR_NOT_ALLOWED_VALUE||<EmailQueueID_e26eff92-72f4-47e5-b193-b2c5f0a42ed3_https://PSP006.onventis.com/@onventis.com> in /var/www/html/YetiForce2/app/Purifier.php:456
Stack trace:
#0 /var/www/html/YetiForce2/modules/OSSMail/models/Record.php(241): App\Purifier::purifyByType('<EmailQueueID_e...', 'MailId')
#1 /var/www/html/YetiForce2/modules/OSSMailScanner/models/Record.php(384): OSSMail_Record_Model::getMail(Resource id #399, 24032, 419)
#2 /var/www/html/YetiForce2/modules/OSSMailScanner/models/Record.php(546): OSSMailScanner_Record_Model::mailScan(Resource id #399, Array, 'INBOX', 101935, 0)
#3 /var/www/html/YetiForce2/modules/OSSMailScanner/crons/Action.php(27): OSSMailScanner_Record_Model->executeCron('cli - ')
#4 /var/www/html/YetiForce2/cron.php(89): OSSMailScanner_Action_Cron->process()
#5 {main}

**Comment by Andr198** [comment]
![ConfReport](https://user-images.githubusercontent.com/62097187/85136840-c4039e80-b22f-11ea-9715-9020bc81090f.png)

**Comment by Andr198** [comment]
Fixed by myself
Added to file Purifier.php in line 441  `\:`
```
$value = preg_match('/^[\sA-Za-z0-9\<\>\_\[\.\]\=\-\+\:\@\$\!\#\%\&\'\*\+\/\?\^\_\`\{\|\}\~\-]+$/', $input) ? $input : null;

```
if possible correct this error

**Comment by mariuszkrzaczkowski** [comment]
good job
