### ISSUE TITLE
[Question] How to setup CRM yeti local directory 

### ISSUE THREAD

**Issue by kalle3e** [YetiForceCompany/YetiForceCRM#13192]
### Description

I've been following #6801  to make CRM yeti local directory to point to /var/www/html/yeti and haven't been able to make this work. I'm using php 7.2 on Ubuntu 18.04 on localhost
Screenshots showing the config for apache with the main /etc/apache2/apache2.conf pointing to the one at /var/ww/html/yeti
![Screenshot from 2020-06-18 22-08-02](https://user-images.githubusercontent.com/64237549/85018907-48fba300-b1b1-11ea-9615-18414aea26f5.png)
![Screenshot from 2020-06-18 21-58-19](https://user-images.githubusercontent.com/64237549/85018914-4a2cd000-b1b1-11ea-98c8-5028577e17e5.png)
![Screenshot from 2020-06-18 21-57-24](https://user-images.githubusercontent.com/64237549/85018916-4ac56680-b1b1-11ea-9c18-f0ad2ace864e.png)

**Comment by mariuszkrzaczkowski** [comment]
```
<VirtualHost *:80>
	ServerName yeti
	ServerAlias yeti
    ErrorLog "c:/www/__vhost_logs/YetiForceCRM_apache_error.log"
    CustomLog "c:/www/__vhost_logs/YetiForceCRM_access.log" common
	DocumentRoot c:/www/YetiForceCRM/public_html
	<Directory  "c:/www/YetiForceCRM/public_html/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
		<ifModule mod_headers.c>
		Header unset X-XSS-Protection
		Header unset Strict-Transport-Security
		Header unset X-Frame-Options
		Header unset X-Content-Type-Options
		Header unset X-Permitted-Cross-Domain-Policies
		Header unset Referrer-Policy
		Header unset Expect-CT
		Header unset X-Robots-Tag
		Header unset Cache-Control
		Header unset Server
		Header unset X-Powered-By
		Header unset Access-Control-Allow-Origin

		Header always set X-XSS-Protection "1; mode=block"
		Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		Header always set X-Frame-Options SAMEORIGIN
		Header always set X-Content-Type-Options nosniff
		Header always set X-Permitted-Cross-Domain-Policies "none"
		Header always set Referrer-Policy "no-referrer"
		Header always set Expect-CT 'enforce; max-age=3600
		Header always set X-Robots-Tag none
		Header always set Access-Control-Allow-Origin: *

		Header always set Cache-Control "private, no-cache, no-store, must-revalidate, post-check=0, pre-check=0"
		<FilesMatch "\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt|ttf|woff2)$">
		Header always set Cache-Control "max-age=86400, public"
		</FilesMatch>

		</ifModule>
		AddDefaultCharset UTF-8
		<ifModule ModSecurity.c>
			SecServerSignature ''
		</ifModule>
		<IfModule mod_autoindex.c>
			Options -Indexes -MultiViews
		</IfModule>
	</Directory>
</VirtualHost>
```

**Comment by kalle3e** [comment]
Made the change- replaced with yours above 
-no errors reported, access.log attached. Still CRM local dir not pointing correctly to /var/www/htm/public_html
![Screenshot from 2020-06-19 02-39-33](https://user-images.githubusercontent.com/64237549/85049423-ff727e80-b1d7-11ea-924a-160a7006bd21.png)
![Screenshot from 2020-06-19 02-41-31](https://user-images.githubusercontent.com/64237549/85049436-013c4200-b1d8-11ea-8e46-116ad7616d24.png)
![Screenshot from 2020-06-19 02-41-52](https://user-images.githubusercontent.com/64237549/85049441-026d6f00-b1d8-11ea-9970-658a7439bf23.png)

**Comment by mariuszkrzaczkowski** [comment]
show file list from public_html directory

**Comment by kalle3e** [comment]
![Screenshot from 2020-06-19 20-58-32](https://user-images.githubusercontent.com/64237549/85125843-af46fb00-b26f-11ea-9038-c95cab71558e.png)

**Comment by kalle3e** [comment]
@mariuszkrzaczkowski 
Did you have a chance to work out what's happening with this issue that I have? There's no real chance for working on the code as it's unreliable as for the problem here #13133. It's been going on for a while and can't resolve it.
