### ISSUE TITLE
[Question] how to add comments with manual workflow ?

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#13194]
Oh hi there! 😄
Hi company !!

Is it possible to add a comment with a workflow on opportunities module ? i am interesting manual workflow
For an example when i sent a quote with pdf i want to add comments on opportunities as well

**Comment by konadrian** [comment]
Hello,
Of course it's possible but it requires some knowledge about programming and yetiforce. We could add this functionality but it require buy a support package
https://yetiforce.com/en/marketplace/development-support
