### ISSUE TITLE
[Question] where is the button Add relation on modules ?

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#13205]
Oh hi there! 😄 Hi company !!

i would like to know where is the button Add relation on modules-relations or how to enable it?

![image](https://user-images.githubusercontent.com/50912403/85228650-3a99cb00-b3ed-11ea-8f30-07a65e50f9d6.png)

That button there is on gitdeveloper.yetiforce.com/

**Comment by vovpff** [comment]
```
/config/Develorer.php
```

There are should be param to activate this button

**Comment by Giorgos-Hellene** [comment]
@vovpff Thank you very much !!!!
