### ISSUE TITLE
[Question] email  enquiry form to lead in crm

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13204]
can anyone guide on how can an email automatically gets converted to crm leads and status is pending..
Whats the process to get this functionality.. I tried wf but no sucess. 

can any one help,,,

i know i can manually go to my mailbox and create a lead out of an email.

**Comment by apcloic** [comment]
@rioshaz I think you have to write your own custom action in MailScanner :
https://gitstable.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=Index&block=8&fieldid=44

**Comment by rioshaz** [comment]
thanks for your response @apcloic 
how to write that custom action in mail scanner ?

well all crm in the market offers such a simple solution of web forms. why is such a basic feature lacking in yetifroce...
this is the first step in using a crm and if this isnt simple i dont think people will opt for yetiforce much.

your help is appreciate 👍

**Comment by apcloic** [comment]
@rioshaz You need programming skills or hire a programmer if not.
YF does not lack really this feature, you could easily write your own web forms solution.
For example, I've just finished to write my own web forms solution based on Google Forms and Google Sheets API.
It may be **your** first step in using a CRM but AFAIK it's not the case for all.
Also, bear in mind that YF is much more than a basic CRM and it's extremely powerful and customizable.
Regards

**Comment by bpwane** [comment]
@apcloic that isn't really a helpful response. Can you please provide instructions or at least a starting point.  I agree that this is a pretty basic feature request. Just telling people that YF is powerful doesn't really make the point.

**Comment by apcloic** [comment]
@bpwane 
Yes for sure, here's how I did my web form 
1 - you need a google account
2 - Create your form using [Google Forms](https://docs.google.com/forms/u/0/)
3 - Enable Sheets API, documentation [here](https://developers.google.com/sheets/api)
4 - Register/Create a YF [custom workflow](https://github.com/YetiForceCompany/YetiForceCRM/issues/10667)
5 - Write your custom php script and do what you want.

My script starts like this :

`<?php

require_once '/path/to/google-api-php-client/vendor/autoload.php';

$client = new \Google_Client();
$client->setApplicationName('My_CRM');
$client->setScopes([\Google_Service_Sheets::SPREADSHEETS]);
$client->setAccessType('offline');

/*
 * The JSON auth file can be provided to the Google Client in two ways, one is as a string which is assumed to be the
 * path to the json file. This is a nice way to keep the creds out of the environment.
 *
 * The second option is as an array. For this example I'll pull the JSON from an environment variable, decode it, and
 * pass along.
 */

$client->setAuthConfig(__DIR__ . '../path/to/your_credentials.json');

$sheets = new \Google_Service_Sheets($client);
/*
 * To read data from a sheet we need the spreadsheet ID and the range of data we want to retrieve.
 * Range is defined using A1 notation, see https://developers.google.com/sheets/api/guides/concepts#a1_notation
 */
$spreadsheetId = 'REPLACE_WITH_YOUR_SPREADSHEET_ID';

$range = "'YOUR_SHEET_NAME'";
$rows = $sheets->spreadsheets_values->get($spreadsheetId, $range);

$data = $rows->getValues();

foreach($data as $key => $value) {

//do your stuff

}`

[Integrating Google Sheets API with PHP](https://www.srijan.net/blog/integrating-google-sheets-with-php-is-this-easy-know-how)
I'm not a programmer so there may be a better way but it works very well for me.
Regards

**Comment by rioshaz** [comment]
@apcloic thanks for your help but i am not a programmer & i agree YF could be much more capable but i just want a simple thing done.  

What i need is like mail scanner scan emails and add to tickets .. i want same functionality for leads... 

i assign an email address and it scans and creates a lead out of every email.

body of the email can be included in lead description box as its with tickets too .

is it simple to do ?

**Comment by apcloic** [comment]
@rioshaz It's not so difficult but it requires programming skills and it also depends on your needs.
You should ask YF for a quote.

**Comment by rioshaz** [comment]
@apcloic well if u can guide i cam do it... 
if such n basic things needs a quote its not an opensource spirit.

can u help

**Comment by apcloic** [comment]
@rioshaz  
I already did, I took some time and gave you some guidance.
I am not a programmer, I'm just learning how to code.
IMO, if you want someone to do the job for you, then you have to pay / ask for a quote.
If you want it for free, then you have to learn PHP.
Regards,

**Comment by bpwane** [comment]
Thanks for this guidance.

**Comment by waran70** [comment]
@rioshaz
> if such n basic things needs a quote its not an opensource spirit.

It is open source. Code is not encrypted and you can do whatever you want.  Having someone  spending own time
on your own issue is totally different story.

**Comment by rioshaz** [comment]
@waran70 well its not my own issue its an issue with many people who might want to use yeti... emails to lead is pretty basic.. if they dont have it streamlined, i doubt YF future adoption rate..

**Comment by bpabiszczak** [comment]
Below you have a link to a function that downloads your email, parses it and creates a ticket from it.
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/OSSMailScanner/scanneractions/CreatedHelpDesk.php

**Comment by rioshaz** [comment]
@bpabiszczak question here is ,,, how to  create a lead from email..
tickets can be created by using mail scanner, with create helpdesk option,,,

**Comment by bpabiszczak** [comment]
> how to create a lead from email.

You need to create a script similar to the ticket script.
