### ISSUE TITLE
No modules and templates

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#13203]
Disabled icons for templates and modules, also no icons for Accounts, Leads, Contacts. Is this an error in the application or server system settings ???

![email no template](https://user-images.githubusercontent.com/25682437/85204445-d4417980-b314-11ea-9423-195daf062282.gif)

![email no template1](https://user-images.githubusercontent.com/25682437/85204454-df94a500-b314-11ea-9b47-89ca6c5065ea.gif)

**Comment by rskrzypczak** [comment]
These are only available in the auto-login option, so if you logged in manually by entering your login and password, the items will not be available.
![image](https://user-images.githubusercontent.com/10221999/85250833-f42d8600-b457-11ea-8fc2-78b3ce69daa0.png)

**Comment by apcloic** [comment]
@rskrzypczak I'm using auto-login option but templates & modules remains disabled.

FYI, I see the following error in logs:

`[24-Jun-2020 12:03:26 +0200]: <kk5l0idf> DB Error: [1062] Duplicate entry 'kk5l0idf1inj0q2oqjmmu5cfci' for key 'PRIMARY' (SQL Query: INSERT INTO `roundcube_session` (`sess_id`, `vars`, `ip`, `changed`) VALUES ('kk5l0idf1inj0q2oqjmmu5cfci', 'bGFuZ3VhZ2V8czo1OiJmcl9GUiI7c2tpbnxzOjk6InlldGlmb3JjZSI7aW1hcF9uYW1lc3BhY2V8YTo0OntzOjg6InBlcnNvbmFsIjthOjE6e2k6MDthOjI6e2k6MDtz*********************************M6Njoic2hhcmVkIjtOO3M6MTA6InByZWZpeF9vdXQiO3M6MDoiIjt9aW1hcF9kZWxpbWl0ZXJ8czoxOiIvIjt1c2VyX2lkfHM6MToiMyI7dXNlcm5hbWV8czozMDoibGVzYXRlbGllcnNmcmFuY29ldXJAZ21haWwuY29tIjtzdG9yYWdlX2hvc3R8czoxNDoiaW1hcC5nbWFpbC5jb20iO3N0b3JhZ2VfcG9ydHxpOjk5MztzdG9yYWdlX3NzbHxzOjM6InNzbCI7cGFzc3dvcmR8czo0NDoicTEzdGVSeFdJc0lkL2ZPYjI0Y3MrcXdXNk5jb3ZRbVlqV1B6WW9CcEVCWT0iO2xvZ2luX3RpbWV8aToxNTkyOTkzMDA1O1NUT1JBR0VfU1BFQ0lBTC1VU0V8YjoxOw==', 'MY_IP_ADDRESS', now())) in /var/www/html/yfcrm/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_db.php on line 543 (GET /public_html/modules/OSSMail/roundcube/?_autologin=1&_autologinKey=**********AutoLoginKey**********)`

**Comment by rskrzypczak** [comment]
did you add templates?
![TemplateForRecord](https://user-images.githubusercontent.com/10221999/85568328-e0d61280-b631-11ea-9b3b-16f47b6d1ecb.gif)

**Comment by apcloic** [comment]
@rskrzypczak Yes, of course I've created a template (type: message).
Also, I've noticed that it works as expected on another YF instance but it's a 5.2 version.
Regards,

**Comment by apcloic** [comment]
@rskrzypczak 
Hi,
I've just checked email templates once again today and I don't know how but it's working now.
Afaik, the only thing I did is creating a template using another admin account but I can't guarantee if it helps or not.
Nevermind, no more issue on my side 👍 
Ty

**Comment by fbojan** [comment]
Thanks !

**Comment by samuelsituma** [comment]
Any work around this issue #14493 ?
