### ISSUE TITLE
Reading data from MSSQL database

### ISSUE THREAD

**Issue by Cooperdale** [YetiForceCompany/YetiForceCRM#13207]
Hello, my company has all customer data on a MSSQL database, used by our accounting software. Is it possible to read this data and use it in YetiForce, without having to maintain two separate databases? I couldn't find anything specific about this.

**Comment by davide-alghi** [comment]
Hi @Cooperdale,
no it's not possible. Currently the specified database is MySql.
Assuming that YetiForce can interface with MSSQL, your database should be structured exactly with YetiForce schemes, but this we both know is not the case.
However, for any ERP-CRM you consider, a data migration is necessary.

**Comment by mariuszkrzaczkowski** [comment]
The engine can communicate with the mssql database, but is not yet ready to run CRM on mssql completely. You can write a script in CRM that will synchronize data

**Comment by Cooperdale** [comment]
> 
> 
> The engine can communicate with the mssql database, but is not yet ready to run CRM on mssql completely. You can write a script in CRM that will synchronize data

Thanks. So I'd need to write a script in PHP, modifying the core files, or is there a YetiForce module which I should use for creating the script?

**Comment by bpabiszczak** [comment]
Buy programming hours, then we can create a script for you.
https://yetiforce.com/en/marketplace/development-support
