### ISSUE TITLE
User preferences. Added user photo

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1321]
I added user phtoto which name "Bez tytulu.png". The image isn't show. 

![Image missing](https://cloud.githubusercontent.com/assets/3193498/8494267/88a9ca88-2163-11e5-8b32-88206b872956.png)

**Comment by MaciejStencel** [comment]
This occures only on windows in wamp environments. Files with utf8 names needs to have characters withing windows codepage.

On Linux machines this does not occur.

**Comment by JeRRimix** [comment]
I additional want to say that I think necessary add functions of change photo and delete photo and auto abjust resize
