### ISSUE TITLE
[Question] Status of Backup Manager "LBL_BACKUP_MANAGER" in V. 5.3. -> Bug?  

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13216]
Hello,

on my fresh YF 5.3 installation the Backup Manager (in the system settings) is shown as "LBL_BACKUP_MANAGER"

![Screenshot_2020-06-24 Datensicherung System Einstellungen(1)](https://user-images.githubusercontent.com/13665806/85559699-3c9c9d80-b62a-11ea-9819-7b297aefcc58.png)

and calling the Backupmanager shows:

![Screenshot_2020-06-24 Datensicherung System Einstellungen](https://user-images.githubusercontent.com/13665806/85559845-605fe380-b62a-11ea-9a0e-7da2c0ef1254.png)

This behavior is even on the Demo-Installation on https://gitstable.yetiforce.com/ 

but **NOT on https://gitdeveloper.yetiforce.com/**

![Screenshot_2020-06-24 Datensicherung System Einstellungen(2)](https://user-images.githubusercontent.com/13665806/85561091-92be1080-b62b-11ea-8637-f7e2f9995291.png)

Is this a bug in 5.3? Could not find any issue...

Thanks!

Regards

**Comment by vovpff** [comment]
@blu-IT Are you updated langpack?

**Comment by blu-IT** [comment]
@vovpff Yes.

**Comment by davide-alghi** [comment]
https://gitstable.yetiforce.com/ works fine.

Did you install service pack?
https://gitstable.yetiforce.com/index.php?parent=Settings&module=Updates&view=Index&block=14&fieldid=63

**Comment by blu-IT** [comment]
@davide-alghi When I log in with german (!) language selection, on https://gitstable.yetiforce.com the behavior described above is still present:  "LBL_BACKUP_MANAGER"

On my personal system I have the latest service pack installed. So I think it may be a translation issue?

**Comment by vovpff** [comment]
Check bug using other languages on your system. Maybe in German translation is missing. You can try to add translation to LBL_BACKUP_LIST to German by yourself trough Language Manager and check result. Maybe this part of system not fully translated to German. In this case you can take a part in Yetiforce Crowdin engine to improve your language translation of system. This is simple if you can spend some time for this.

**Comment by davide-alghi** [comment]
Yes Ivan, you're right.
On https://gitdeveloper.yetiforce.com/ it works fine (in German) so the problem was fixed.

The problem is (was) the filename in German translation. If you wanna fix on your instance, please rename

```languages/de-DE/Settings/BackUp.json```

in 

```languages/de-DE/Settings/Backup.json```

(U => u)

**Comment by blu-IT** [comment]
@davide-alghi YES!

Fine, thanks a lot! It resolved the problem the way you described above.

Should I open a separte bug report for this for gitstable?

**Comment by davide-alghi** [comment]
> Should I open a separte bug report for this for gitstable?

Ivan,
that's not required. the problem has already been fixed.
gistable is the last YF version released, as yours. gitdeveloper YF version is the new one that YF team will release. So if gitdeveloper works, everything is ok: into next release / update the problem will be fixed for all end-users.

**Comment by blu-IT** [comment]
OK, thanks again!
