### ISSUE TITLE
Fetch Price Rate from Account Linked Price Book for product

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#13214]
I have installed YetiForceCRM-5.3.0-complete.zip, created Product and Price Book. In Account Module, specified default price book. Now when making Sales Quote facing problem

Expectation: for product selected in Quote, rate must be from Account Linked Price Book

Actual: Rate from Product master is fetched.

Am I doing anything wrong ?

Thanks in Advance.

**Comment by JEEVAN28** [comment]
Any update

**Comment by bpabiszczak** [comment]
Change price for product/services

![image](https://user-images.githubusercontent.com/10197525/91486333-64b7af80-e8ac-11ea-895e-4fd2d1ff653f.png)

Set pricebook on quoutes

![image](https://user-images.githubusercontent.com/10197525/91486466-96307b00-e8ac-11ea-8e55-32dbd1472220.png)

Set pricebook on Account

![image](https://user-images.githubusercontent.com/10197525/91486559-be1fde80-e8ac-11ea-86e5-b0471a1af932.png)
