### ISSUE TITLE
5.3 installation challenges

### ISSUE THREAD

**Issue by bambatha** [YetiForceCompany/YetiForceCRM#13219]
Hello 
I need step by step instructions configuring my server to load the YETI CRM. We are using a shared server on bluehost--if that is relevant. We have followed instructions to the best of our (limited) abilities but can't get the program to load

Any tips/ instructions would be greatly appreciated

thanks to all

**Comment by vovpff** [comment]
You can google around every server parameter and tune it by yourself. In this case you will get great experience!

**Comment by mariuszkrzaczkowski** [comment]
look here
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/Dockerfile

https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/tests/setup
