### ISSUE TITLE
[Question]  pdf template variables document or guide

### ISSUE THREAD

**Issue by chenjeff622** [YetiForceCompany/YetiForceCRM#13215]
### Description

some variables bleow
**$(record : issue_time)$    
$(organization : 1|addresslevel8a)$ $(organization : 1|buildingnumbera)$
$(custom : TableDiscountSummary)$**
i know $ can be insert to html and it is variable . 
But what does **record** or **organization**  or **custom** mean?   what is **:1|XXXXXX** ? 
Does PDF module have any document or guide for this?

**Comment by apcloic** [comment]
@chenjeff622 
Hi, 

Record - > variables of the module

Organization 1 - > variable related to Departments module, 1 is the ID of the department and addresslevel8a if the name of an address field
https://gitstable.yetiforce.com/index.php?module=MultiCompany&view=List&mid=152&parent=76

Custom is used for special set of fields that require a different formatting, etc.
