### ISSUE TITLE
Set Rss Feed set as default

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1322]
After added rss feed I want set it as default but I get the error 
![Error](https://cloud.githubusercontent.com/assets/3193498/8494545/3d4546fa-2166-11e5-987f-9488b1fdede9.png)

**Comment by MaciejStencel** [comment]
In latest YF 2.0.323 this error does not occur.

**Comment by MaciejStencel** [comment]
Fixed error in console log, wrong variable name used to display message.
