### ISSUE TITLE
[bug] notifications not showing

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13224]
Notifications only come when the user is online within (2-5 min) if you are logged out and you had notifications they automatically get read and move to the notifications list.

I have a junior he adds leads and if we both are online i get notifcation and if i am not online and logs in after 1 hr after of his adding he lead.. i see nothing in the pop up.

**Comment by z0lo13** [comment]
@rioshaz 
![image](https://user-images.githubusercontent.com/23143958/85911086-ae264880-b7f0-11ea-8cc3-86ca84ddb891.png)
It is a notification cron which marks them as read.
To disable please go to config/Modules/Notification.php
and change line 24 to false
![image](https://user-images.githubusercontent.com/23143958/85911160-6522c400-b7f1-11ea-9459-086b6db796d6.png)

**Comment by rioshaz** [comment]
@z0lo13 thanks a million buddy... i have made the changes and will wait to see how it works out.

meanwhile, for some modules notifications come coded,, see an attachment like for contacts, comments, project task etc .other modules notifications are coming fine... what could be the issue sir.... why it says " user added $(record : RecordLabel)$" it should say give comment or contact etc... please help if u can.
![notifications error](https://user-images.githubusercontent.com/54880467/85919826-6a811c80-b88c-11ea-8a77-df79039fe379.png)

**Comment by rioshaz** [comment]
@KatarzynaUlichnowska @mariuszkrzaczkowski  can u guys help and also is there any duplicate check function ? when  i enter a new lead or account.. instant check.. before form submission like in vtiger or joforce ?

**Comment by z0lo13** [comment]
@rioshaz Have you tried to repeat the issue on gitdeveloper?

**Comment by rioshaz** [comment]
@z0lo13 there u go see 
![bug yeti notifications](https://user-images.githubusercontent.com/54880467/87719368-e22dd180-c7d0-11ea-9cec-3270a241d6c2.png)
