### ISSUE TITLE
[Question] How to backup Yetifore?

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13222]
Hello,

I have searched all open and closed issues with "backup" and was also searching the documentation, but could not find anything how to trigger a backup.

The only information I found is this: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/data-archiving

Backup path is configued. Cron-Job for "archiving" is activated, but I can't find any backup in my configured directory.

Thanks!

**Comment by davide-alghi** [comment]
here Ivan,
https://github.com/YetiForceCompany/YetiForceCRM/issues/11323#issuecomment-524041529

**Comment by blu-IT** [comment]
@davide-alghi 

Ciao Davide, mille grazie - thanks again for your help! ;-)

Indeed I saw that issue and comment, but while searching through 10 or 15 closed issues with "backup" I was too fast and did not understand.
So what is the sense of a "Backup Manager" that does not allow to configue backups? I understand from the postings, that there is work in progress, but for a "newbie" like me with YF it is rather confusing... maybe renaming that function would help until you can not really configure or trigger backups there?

OK, but a part that fact - I only just can repeat my offer to contribute to documenation here https://github.com/YetiForceCompany/YetiForceCRM/issues/12874#issuecomment-650111441

because I had (and probably still will have) a lot of tipical beginner/starter questions due the lack of documentation and I think a part of my questions are posted repetitive here. 
So to give something back to the great community here and also thinking that all of you experts here have more important things to do, as to always answer to the same "basics", I would like to give something back.

**Comment by davide-alghi** [comment]
> Ciao Davide, mille grazie - thanks again for your help! ;-)

:+1:


> OK, but a part that fact - I only just can repeat my offer to contribute to documenation here [#12874 (comment)](https://github.com/YetiForceCompany/YetiForceCRM/issues/12874#issuecomment-650111441)

I'm a supporter of the idea that "Documentation is the source". But we all know that documentation has high costs both creating and maintaining it. Certainly the availability of documentation is a fundamental key for the product spreading. It would already be a good result to have the possibility to catalog many of the contents here on GitHub by index and to have a sort of primitive manual powered by the community

**Comment by jimlongo56** [comment]
Agreed, documentation is lacking.
