### ISSUE TITLE
[Feature] Import and create field

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#13228]
Would it be hard to add option to create new field (if not exists) while importing data?

**Comment by waran70** [comment]
To extend this question.... I imagine that moving from let say vtiger is a major blocker for not wealthy, penny-pinching or inexperienced users.  If, that is allowed. the scope of YF users might jump rapidly up. It could bring some coins for developer, and boost fame of this system.

**Comment by bpabiszczak** [comment]
It is very simple, you buy 30-40 hours and we will add you this option!
https://yetiforce.com/en/marketplace/development-support

**Comment by waran70** [comment]
I gave you the advice to get things working better for the project but the response to it is to pay for my advice. All ok there? 
;-) Do you want to take over the users of the competition? Yes? No?

**Comment by vdpawel** [comment]
Simply wrong classification of a "feature" issue,
instead of ❔ question
should be 💹 enhancement
(But that's just my opinion :) )
