### ISSUE TITLE
[Question]  how to set it to integer(Rounding) ?

### ISSUE THREAD

**Issue by chenjeff622** [YetiForceCompany/YetiForceCRM#13221]
### Description

Is that possible to set it to be integer(rounding)?
![圖片](https://user-images.githubusercontent.com/19267137/85819637-ddb06300-b7a6-11ea-887e-f257afbf915b.png)

**Comment by vovpff** [comment]
Trailing zeros in user preferences

**Comment by chenjeff622** [comment]
I got it . thank you!
