### ISSUE TITLE
[Question] Configure fields on summery tab for organizations, contacts, etc.

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13223]
Hello.

I would like to know, if it is possible to configure the summay view when I click on a organization or contact.
For example in the summary is shown the _"industry"_ of the organization, but I don't need that field - I would like to see the _"type"_ for example.

I know how/where to configure the shown fields in general for organizations, contacts, but this has no impact on the summary view.

Thanks!

Regards

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/85860073-d600b680-b7c6-11ea-962e-85e1e2e318e8.png)

![image](https://user-images.githubusercontent.com/8545791/85860093-e153e200-b7c6-11ea-9aa3-44a01cdf3149.png)

**Comment by blu-IT** [comment]
@vovpff 

Ahhhh, sure - already saw this. Thanks!!!
