### ISSUE TITLE
[Question] Separate services and Products sums and blocks on PDF

### ISSUE THREAD

**Issue by merckaa** [YetiForceCompany/YetiForceCRM#13234]
Can someone help me achieve separated Total Sum of Services and Total Sum of Products in Quotes/Invoices e etc?
I tought I could do two custom fields to calculate only the sums of each one on the fly, but I could not find the right variable to use an if statement.

In PDF I tought I could do it too, to retrieve only Services/Products Line Itens in Custom TextParser but once again I could not find the right variable in recordmodel to filter it,to retrieve respective Line Itens.

Can someone help?

**Comment by merckaa** [comment]
Done it.

**Comment by waran70** [comment]
@merckaa here is not a personal blog :-) If you cracked on something let us know the way too

**Comment by merckaa** [comment]
Well, Very sorry.

I was going to share, but it's kinda of a javascript hack, done some custom coding.

The code is not very friendly and was designed specifically for my needs, it may break something.

So I created two custom fields in the quote module, one for the sum of all products and the other for the sum of all services.

`{strip}
     <script type="text/javascript">
	 
	var rows = [...$('.inventoryRow')];
    var total = 0;
    var totalap = 0;
    $('form').submit(function(){
		rows = [...$('.inventoryRow')];
	});
    $('form').submit(function(){
        total = 0;
        totalap = 0;
        rows.forEach(e => {
        isService = $(e).find('.yfm-Services').length > 0;
        qty = $(e).find('input.qty');
        unitPrice = $(e).find('input.unitPrice');

        if (isService) {

            if (qty.length > 0) {
                qty = qty[0].value;
                qty = qty.replace(',','.');
            }

            if (unitPrice.length > 0) {
                unitPrice = unitPrice[0].value;
                unitPrice = unitPrice.replace(',','.');
            }

            if (qty.length > 0) {
                total = total + (qty * unitPrice);
            }

        }
            if (!isService) {

            if (qty.length > 0) {
                qty = qty[0].value;
                qty = qty.replace(',','.');
            }

            if (unitPrice.length > 0) {
                unitPrice = unitPrice[0].value;
                unitPrice = unitPrice.replace(',','.');
            }

            if (qty.length > 0) {
                totalap = totalap + (qty * unitPrice);
            }

        }
    });
        vlrplano = total.toString().replace('.', ',');
        vlraparelho = totalap.toString().replace('.', ',');
	    $('#SQuotes_editView_fieldName_vlr_total_plano').val(vlrplano).attr('readonly', true);
	    $('#SQuotes_editView_fieldName_vlr_total_aparelhos').val(vlraparelho).attr('readonly', true);
    });
</script>
{/strip}`

Edit these for you needs:

`	    $('#SQuotes_editView_fieldName_vlr_total_plano').val(vlrplano).attr('readonly', true);
	    $('#SQuotes_editView_fieldName_vlr_total_aparelhos').val(vlraparelho).attr('readonly', true);`

put inside a tpl file in /layouts/basic/modules/Vtiger

and add this line in EditView.tpl

`{include file=\App\Layout::getTemplatePath('Script.tpl', $MODULE)}`

Not sure if it's the right approach. But It's working for me.

**Comment by merckaa** [comment]
You may not need to replace , to . in decimal as it's about currency formatting.
