### ISSUE TITLE
[Question] How to set up existing resources for the reservation system?

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13232]
Hello,

I am testing on YF 5.3 and have some questions regarding the reservations (and fixed assets) module:

When trying to book a meeting room in the calendar, I can choose **any title** for that booking and a type (vehilce, meetingroom, etc.) but there is no selection of the **existing resources**. 
So, where do I configure, that I have 3 meetingrooms, but only 2 beamers for example to avoid overbooking?
I looked in the "fixed assets" but what I put in here, is not shown/availabe in the ressources module.

I hope my intention is clear: I want to define some existing ressources for my company and expected that the reservations module only shows me these possible/existing ressources, but for the moment I can **book anything**, because title allows anything - even things that do not exist in my company as a ressource.

Thanks!

Regards

**Comment by blu-IT** [comment]
None any idea?

**Comment by blu-IT** [comment]
OK, seems I got a little step ahead. I found this in 

`Software configuration -> Standard modules -> Fields – Folders -> System settings`

Select Template "Reservations" and I can configure type of things that can be booked, but **not exact name** (e.g. Room 1, Room 2) or even **amount of things** (e.g. 3 Beamers).

![Screenshot_2020-07-10 Tree manager System settings](https://user-images.githubusercontent.com/13665806/87097939-8c907c80-c246-11ea-83c7-bc3cf0e79727.png)

**Comment by bpabiszczak** [comment]
You can add any resources as you showed it yourself. There is no other option at the moment.
