### ISSUE TITLE
[How-To] Custom function to update multiple records

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13231]
Hi,

Use case : let's say I want to update the "description" field with the word "Hello" for Contacts.

1 - Create your script like this and put it on your web server, for example in modules/Contacts/workflows/MyCustomClassName.php :

`<?php

/* +**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * ********************************************************************************** */

class MyCustomClassName

{

function myCustomMethod(Vtiger_Record_Model $recordModel)

	{

		$recordModel->set('description', 'Hello');

		$recordModel->setHandlerExceptions(['disableWorkflow' => true]);

		$recordModel->save();

		}

}
`

2 - Register your custom function #10667 where myCustomMethod is the method name and MyCustomClassName is the function name.

3 - [Create/Activate a workflow](https://gitstable.yetiforce.com/index.php?module=Workflows&parent=Settings&view=List&block=15&fieldid=24)

That's it, it should work either for updating a single records, mass edit or execution schedule.

**Comment by apcloic** [comment]
Here's another example : let's say I want to update a custom field which count the number of related records.

class MyCustomClassName

{

function myCustomMethod(Vtiger_Record_Model $recordModel)

{

		$relatedModuleName = 'Replace_With_Related_Module_Name';
		
		$relationListView = Vtiger_RelationListView_Model::getInstance($recordModel, $relatedModuleName);

		$count = $relationListView->getRelatedEntriesCount();

		$recordModel->set('replace_with_your_custom_field_name', $count); 

	$recordModel->setHandlerExceptions(['disableWorkflow' => true]);

	$recordModel->save();

	}

**Comment by IgorRSU** [comment]
Hi,
Thanks for Your examples. I have question - in second example workflow will calculate all related records. Can I define custom value - fo example if checkbox Status is TRUE - so, it will calculate this related record, if FALSE - go to next record ?

**Comment by vovpff** [comment]
@IgorRSU yes

**Comment by IgorRSU** [comment]
@vovpff but how? Create a new function like getRelationQuery() in modules/Vtiger/models/RelationListView.php ?

**Comment by vovpff** [comment]
@IgorRSU by applying conditions before updating records

**Comment by IgorRSU** [comment]
@vovpff when creating workflow in system?

**Comment by vovpff** [comment]
@IgorRSU no. You need programmer for this. You need to write some custom function for workflow mechanism and put there some conditions to update only related records what you need instead all related records.
