### ISSUE TITLE
[bug] Call to a member function isActive() on boolean error after successful login.

### ISSUE THREAD

**Issue by roro1168** [YetiForceCompany/YetiForceCRM#13248]
Hello, I am receiving the following error after a successful login that I have not seen in other posts. Please see screenshot below. 
![image](https://user-images.githubusercontent.com/67708100/86281195-269f5780-bbab-11ea-87cd-95e117e605a6.png)

I have also included the inspect element with the errors. I am new to programming and coding and would greatly appreciate the guidance. 

Thanks,

**Comment by rskrzypczak** [comment]
You probably have a data mismatch between the files and the database.
Update the data in the files which should fix the problem (https://github.com/YetiForceCompany/YetiForceCRM/issues/12515)
