### ISSUE TITLE
[bug] Error when navigating to 'Modules - Installation'

### ISSUE THREAD

**Issue by 2techcomputing** [YetiForceCompany/YetiForceCRM#13247]
Hello, I went into the 'Modules - Installation' section and disabled a few of the categories that where not needed. Once i saved changes and attempted to go back to the 'Module - Installation' section i am now receiving the error message 'Call to a member function get() on boolean'

I have checked to see what might be causing the error and cannot see what the issue is, I have attached a screenshot of the error as well as a few logs from what i can find, any help would be appreciated.

[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/4859677/system.log)
![maximumpower yetiforce](https://user-images.githubusercontent.com/60716615/86277822-39eefa80-bb8c-11ea-8d2b-e8d553d15430.PNG)

**Comment by rskrzypczak** [comment]
There are already many reports of this error.
https://github.com/YetiForceCompany/YetiForceCRM/issues/12082#issuecomment-561496658
