### ISSUE TITLE
[Question] [PL] Czy jest możliwość wyłączenia wyświetlania kolumn w wykresie Gantt? Czy jest możliwość ustawienia zmiennej w wartości domyślnej?

### ISSUE THREAD

**Issue by kominekjacek** [YetiForceCompany/YetiForceCRM#13242]
**Pytanie:** Czy jest możliwość wyłączenia wyświetlania kolumn w wykresie Gantt? Czy jest możliwość ustawienia zmiennej w wartości domyślnej?

**Przykład:** Chce wyłączyć wyświetlanie kolumn Właściciel i Dni
![image](https://user-images.githubusercontent.com/61247039/86099851-5457a400-bab8-11ea-8ec8-682a520f075e.png)

Przykład: Chce aby wartością domyślną w: Nazwa etykiety: Rzeczywista data zakończenia Nazwa systemowa: enddate była pobierana data z Nazwa etykiety: Data rozpoczęcia Nazwa systemowa: startdate. Czyli aby data zakończenia automatycznie ustawiała się na taką samą jak data rozpoczęcia.
![image](https://user-images.githubusercontent.com/61247039/86100218-d47e0980-bab8-11ea-8cd4-1f1ca47bcdb1.png)

**Środowisko:**
YetiForce | 5.3.0
Web server | Apache/2.4.29 (Ubuntu)
PHP | 7.2.27-6+ubuntu18.04.1+deb.sury.org+1
Browser | Chrome
Operating System | Linux crm 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64
Database | mysql \| 10.1.44 \| mysqlnd 5.0.12-dev

**Comment by bpabiszczak** [comment]
Jeżeli nie chcesz widzieć kolumn, to je wyłączasz [wyłączasz opcje "show list".:
![image](https://user-images.githubusercontent.com/10197525/91381410-9f2b3900-e827-11ea-9d0f-d8c730440f14.png)

Jeżeli chcesz zmienić pola w sposób jaki opisałeś, to potrzebujesz programisty:.
