### ISSUE TITLE
Yetiforce file migration

### ISSUE THREAD

**Issue by slomus** [YetiForceCompany/YetiForceCRM#13244]
Witam

Mam 1 pytani 

1. Jakie pliki bazy danych muszę przenieść z starej bazy na nową? Jak one się nazywają?
Mógłby ktoś pomóc?

**Comment by slomus** [comment]
Hi

I have question

Which file I need to move from myphpadmin in Yetiforce to my new server to work. How are they called

**Comment by vovpff** [comment]
@slomus myphpadmin doesn't comtains any files. This is just web based application to work with database

You need to dump your database

```
mysqldump -uusername -ppassword dbname > path/to/file/dump.sql
```

and import to new server database

```
mysql -uusername -ppassword dbname < /path/to/file/dump_.sql
```

**Comment by slomus** [comment]
yes i have one question

Can I take this file from phpmyadmin on yetiforce because i need to export database no file on linux(centos)?

**Comment by vovpff** [comment]
@slomus what you mean?
