### ISSUE TITLE
[Question] [PL] Problem z masową edycją

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#13243]
Witam,
na wersji 5.2.0 mam problem z masową edycją rekordów:
![MassiveEdition](https://user-images.githubusercontent.com/21024857/86102620-080e6300-babc-11ea-89eb-0323dbc97c92.gif)

Jak na gifie, zaznaczam rekordy, wybieram masową edycję i nic. Przemieli, po czym nic nie wyświetla. Nie mam żadnego błędu w consoli przeglądarki, nie mam nic w system.log ani w errors.. Gdzie i co mogę sprawdzić żeby poszukać błędu?

**Comment by KatarzynaUlichnowska** [comment]
Dzień dobry, 
czy testował Pan to samo na https://gitdeveloper.yetiforce.com? Proszę również zapoznać się z artykułem o [debugowaniu](https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-programistyczna/item/debugowanie) i poszukać jeszcze w logach serwera. Jeśli błąd występuje, to w logach zawsze widać przyczynę. Jeśli nie może Pan znaleźć lub nie wie gdzie szukać, to zachęcamy do wykupienia naszego pakietu wsparcia w Marketplace.
