### ISSUE TITLE
Web service - users Storage* field

### ISSUE THREAD

**Issue by sAleksander** [YetiForceCompany/YetiForceCRM#13246]
![screen](https://user-images.githubusercontent.com/22557935/86233639-01ecb500-bb96-11ea-8c97-6f8e89c8bc05.png)
I am trying to get access token from Web service API. In order to do that i need to set up new application in Web service — Applications and new user in Web Service users.

I had no problem with creating app However in case of web service users is a different story.

There is this required field **Storage** that I have no clue how to fill.
I have read through documentation, tutorials However not even once have I encountered this field anywhere.
In terms of autocompletion/suggestions Yeti appears to be stuck in constantly searching for matched word if i try to type something.
Clicking at magnifier or anywhere does not show any suggestions either.

Could anyone explain what this field is for and how can I create such a storage?

If I repeated issue or missed something in documentation, please guide me in a right direction because have not found anything.

Thank you in advance!

**Comment by konadrian** [comment]
Hello, 
Please first try add a record in https://gitdeveloper.yetiforce.com/index.php?module=IStorages&view=List&mid=132&parent=131
IStorages module and then try to add a record in webservice
