### ISSUE TITLE
 [How to automatically add records with emails to individual modules?]

### ISSUE THREAD

**Issue by utp-proj-sztuczna** [YetiForceCompany/YetiForceCRM#13249]
How to automatically add records with mail messages to individual modules?

**Comment by apcloic** [comment]
@utp-proj-sztuczna 
Hi, 
You have to configure MailScanner
https://gitstable.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=Index&block=8&fieldid=125
