### ISSUE TITLE
app_data/cron.php malformed

### ISSUE THREAD

**Issue by pietro559** [YetiForceCompany/YetiForceCRM#13251]
I have cron enabled.
The file app_data/cron.php is malformed. At the end of file appears 'tart'=>1593372602];', wich seems to be the last element of array, repeated in a wrong way.
This bug freezes the admin panel and cron.

... 'label'=>'FOOTER','mode'=>'onlyText','status'=>true],'premiumModules'=>['type'=>'PremiumModules','testCli'=>false,'label'=>'PREMIUM_MODULES','mode'=>'onlyText','status'=>true]],'last_start'=>1593372602];tart'=>1593372602];

**Comment by mariuszkrzaczkowski** [comment]
try this change, app/Cron.php
```php
	public static function generateStatusFile()
	{
		$all = Utils\ConfReport::getAll();
		$all['last_start'] = time();
		return file_put_contents(ROOT_DIRECTORY . '/app_data/cron.php', '<?php return ' . var_export($all, true) . ';');
	}
```

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski 
doesnt help buddy..
still getting error : syntax error, unexpected '' => 1593831903,' (T_ENCAPSED_AND_WHITESPACE)

once i delete app_data/cron file its gets fine.. 

please help

**Comment by mariuszkrzaczkowski** [comment]
And try it, attach all the files you tested
```php
	public static function generateStatusFile()
	{
		$all = Utils\ConfReport::getAll();
		$all['last_start'] = time();
		return file_put_contents(ROOT_DIRECTORY . '/app_data/cron.php', '<?php return ' . json_encode($all) . ';');
	}
```

**Comment by rioshaz** [comment]
cron cant run at all with your given two solutions.
 i was better before as the error used to come once in 4-5 days...


[cron.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/4874614/cron.zip)

**Comment by mariuszkrzaczkowski** [comment]
try it, if it doesn't work, without access to the code, we don't fix it, we have to be able to trigger this error to fix it
```php
	public static function generateStatusFile()
	{
		$all = Utils\ConfReport::getAll();
		$all['last_start'] = time();
		return file_put_contents(ROOT_DIRECTORY . '/app_data/cron.php', '<?php return ' . \yii\helpers\VarDumper::export($all) . ';');
	}
```

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13190#issuecomment-654417798
