### ISSUE TITLE
[Question] [PL] Dodanie numeru zgłoszenia do jego tematu

### ISSUE THREAD

**Issue by MountLee98** [YetiForceCompany/YetiForceCRM#13255]
Witam,

Wysyłane są wiadomości na maila, który jest skanowany przez skaner poczty, a następnie jego zawartość oraz tytuł są automatycznie dodawane jako nowe zgłoszenie ze statusem "Oczekuję na weryfikację". Czy jest możliwość, aby do tematu zgłoszenia oprócz tytułu maila dodać też numer zgłoszenia, który jest automatycznie generowany z każdym nowo utworzonym zgłoszeniem? Próbowałem już przez wyzwalacze dodać w nowym obiegu informacji zadanie "Aktualizuj rekord", który zmienia pole temat  i który wywołuje się podczas tworzenia rekordu, ale wtedy temat zgłoszenia jest pusty. To samo się dzieje kiedy ustawię wywołanie podczas modyfikacji rekordu.

Przykład: wysyłam maila z tytułem "x". Kiedy mail dojdzie, to dodawane jest nowe zgłoszenie z tematem "x" i ustawiany jest automatycznie numer zgłoszenia "Z16". Chciałbym, aby temat zgłoszenia w tym przykładzie wyglądał mniej więcej tak: "Z16 x".

Edit: Za pomocą wyrażeń i funkcji concat udało mi się połączyć numer z tytułem, ale efekt końcowy wygląda tak: "Z16x". Brakuje spacji między numerem a tytułem.

Wersja Yetiforce: 5.3.0

![IMG_20200703_141010](https://user-images.githubusercontent.com/46727312/86468064-eff64800-bd36-11ea-9cb5-6c74223d571f.jpg)

**Comment by bpabiszczak** [comment]
Nie rozumiem w jakim celu. Aktualnie odpisując na zgłoszenie [używając opcji odpowiedz lub nowa wiadomość email] system automatycznie do tematu dodaje numer zgłoszenia. To co chcesz może dopisać programista [~1h].
