### ISSUE TITLE
[Question] How to import account number in organizations?

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13256]
Hello,

I prepared a CSV-file to import a lot of organizations. Before that I exported a CSV-file from YF to check the right columns names and format. Some import test already went fine, but my **account number** is not imported because **I can't select the field** it has to be assigned:

![Screenshot_2020-07-03 Organisationen](https://user-images.githubusercontent.com/13665806/86466799-99880a00-bd34-11ea-85c7-2225873d5ebe.png)

The proposed field "Organization" is already occupied by the organizations name and this is correct.

So how can I assign the values to account number? 
I looked at the database itself and there should be no problem selecting own numbering for the accout number, because every organization has it's own internal accountid.

I am testing on YF 5.3. SP4.

Thanks!

Regards

**Comment by vovpff** [comment]
This is impossible trough standard import because account number is auto increment self generated value.

**Comment by waran70** [comment]
Create custom txt field in target module, pair it while importing with source Acc number. Once import completed go to mysql and do the right thing

**Comment by blu-IT** [comment]
OK thanks, I will try to do it the way @waran70 suggested.
