### ISSUE TITLE
[Question] [PL] Wyzwalacz/Workflow pobieranie daty z tematu zgłoszenia

### ISSUE THREAD

**Issue by kominekjacek** [YetiForceCompany/YetiForceCRM#13250]
**Pytanie:** Czy jest możliwość w wyzwalaczu/obiegu informacji przypisać datę z tematu zgłoszenia do pola "Oczekiwany czas rozwiązania"?

**Przykład:** Osoba X wysyła maila na adres zgloszenia@domena.pl, mail trafia do CRM yetiforce i jest dodany do zgłoszeń. 
W tytule maile/zgloszenia jest podana data w formacie np. 2020-07-02 ta data ma zostać za pomocą wyzwalacza przypisana do pola "Oczekiwany czas rozwiązania"

**Środowisko:**
YetiForce | 5.3.0
Web server | Apache/2.4.29 (Ubuntu)
PHP | 7.2.27-6+ubuntu18.04.1+deb.sury.org+1
Browser | Chrome
Operating System | Linux crm 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64
Database | mysql | 10.1.44 | mysqlnd 5.0.12-dev

**Comment by vdpawel** [comment]
Zwykłą konfiguracją, z mojej wiedzy jest to niemożliwe.

Można za to bardzo łatwo zaprogramować nową funkcję np. w com_vtiger_workflow, która będzie parsować pole temat wycinając z niego datę, skonwertuje ją do odpowiedniego formatu, a do którego pola zostanie przypasana to już można będzie wybrać w konfiguracji.

![obraz](https://user-images.githubusercontent.com/62466142/86398036-3dc27000-bca5-11ea-9e00-493bf4176dc4.png)

**Comment by bpabiszczak** [comment]
A po co ktoś dodaje datę do tematu? Stosując złe rozwiązanie potem szuka się dziwnych rozwiązań, aby wyeliminować skutki. 
Niezależnie od kierunku, wymagany będzie programista.
