### ISSUE TITLE
[Question] Converting a Quote to a Sales Invoice

### ISSUE THREAD

**Issue by 2techcomputing** [YetiForceCompany/YetiForceCRM#13253]
Hello, I am wondering if i is possible to convert a Quote to a Sales Invoice, i know there is an option to convert a Quote to a Sales Order but would like to be able to convert to a Sales Invoice instead. Any help appreciated, thanks.

**Comment by rskrzypczak** [comment]
Check mapping panel
![image](https://user-images.githubusercontent.com/10221999/86432768-28773100-bcf9-11ea-98e0-0ef2e255d68d.png)
![image](https://user-images.githubusercontent.com/10221999/86432828-565c7580-bcf9-11ea-9096-9d96abf04a92.png)
