### ISSUE TITLE
[Question] delete unconnected emails

### ISSUE THREAD

**Issue by DarioGui** [YetiForceCompany/YetiForceCRM#13252]
by enabling the email scanner is it possible to make sure that only the emails that are associated with a ticket or a project are imported?

Or

Is it possible with a daily/weekly workflow to delete all emails that are not combined with a ticket or a project?

the operation of mail scanner, if I understand correctly, imports all the messages and then proceeds with the matching if it meets the requirements.
I don't want to import all the messages to avoid taking up space with emails and attachments that don't interest me

does anyone know of a possible solution? 😄

**Comment by blu-IT** [comment]
I think you can configure in YF which IMAP-Folders to sync. So, if you have somekind of filters already implemented on your mailserver you can avoid to get them in YF.

**Comment by DarioGui** [comment]
solution as simple as it is ingenious.
I just hadn't thought of that.
Thanks so much
