### ISSUE TITLE
[Question] How to edit basic colors

### ISSUE THREAD

**Issue by kamiro16** [YetiForceCompany/YetiForceCRM#13264]
Hello! 

I have problem with changes colors. 
I try change value in _header.scss and main.css but the result dont work. 
also I delete cache. 

Where Can I change colors? 
I need to change, header, menu bg etc. 

Thanks you for advice!

**Comment by blu-IT** [comment]
Not sure if it helps you, but did you try to configure colors in?

`Software configuration-> Colors and calendar -> Colors -> Tab Modules`

![Colors](https://user-images.githubusercontent.com/13665806/86775837-fe56a380-c057-11ea-9f37-acf0ba54f741.png)

**Comment by kamiro16** [comment]
Thanks you for comment but I need another advice. 
I need to change color ex. left menu, top header or body color. 
I change main.css but the result is not visible... 

Maybe I must clean another cache?

**Comment by areksolek** [comment]
In System configuration / Colors and calendar / Colors
it is possible to change the colors:
- Modules - colors the name of the header in the Detailed View of a given module and the names of records in the widget (dasborad).
- Dictionaries - adds a backgroud to each picklist field value
- Fields colors - gives the color of labels in the indicated module

All other custom color change cases are done by css.
If you want to change the menu color you can change the value of the following variables in the _Variables.scss file:
- $ color-menu (text - menu)
- $ bg-menu (background - menu)
- $ color-navbar (text - submenu)
- $ bg-sub-menu (background - submenu)

or in public_html / layouts / basic / styles / layout / _Nav.scss

.c-menu -> & __ container -> & __ item -> a

.tpl-menu-SubMenu -> a

**Comment by rskrzypczak** [comment]
after modifications in * .css files, refresh the browser cache (Chrome Ctrl+Shift+R)

**Comment by kamiro16** [comment]
@areksolek @rskrzypczak  thanks! 
I preparing new css styles system.

**Comment by kamiro16** [comment]
@areksolek  @rskrzypczak i changed base color but I didnt saw any changes... 
I refresh the browser cache too...
I must delete somethink cache files in system?

**Comment by rskrzypczak** [comment]
You are probably modifying the Main.css file.
By default, the system loads the Main.min.css file
Set in config/Developer.php `$MINIMIZE_CSS = false`
and everything should work :)

**Comment by kamiro16** [comment]
@rskrzypczak BINGO! 

Thanks a lot!
