### ISSUE TITLE
Update related record not working

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#13269]
### Description

Anyone know workflow to do this.
When lead is created create To Do ( I Know how to do this)
When 'to do' is completed change status of lead.
(in yetiforce)

**Comment by essayboy** [comment]
anyone?

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/91380171-9b49e780-e824-11ea-9ab3-f1ffa5aa9dc0.png)
