### ISSUE TITLE
[Question] [PL/ENG] ticket number

### ISSUE THREAD

**Issue by utp-proj-sztuczna** [YetiForceCompany/YetiForceCRM#13263]
Mam skonfigurowany numer zgłoszenia, który inkrementuje sie automatycznie wraz z otrzymaniem nowego emaila o zgłoszeniu. W jaki sposób ustawic aby numer zgłoszenia nie inkremetował się i pozostał ten sam numer, w przypadku gdy ten sam klient odpowiada na to samo zgłoszenie.  

When customer send new mail message then new ticket with unique number is created automatically. How to configure yeti to a state when customer respond to mail, no new ticket is created but the content of ticket is overwrite and unique number is the same.

**Comment by utp-proj-sztuczna** [comment]
![zgłoszenia](https://user-images.githubusercontent.com/66875302/86571464-bf4e2280-bf71-11ea-8a7d-d1cc4b29cc27.png)

**Comment by bpabiszczak** [comment]
To się robi automatycznie... o ile klient odpowie na Twojego maila, który to już ten numer zawiera [domyślnie odpowiadając na maila z CRM system dodaje do tematu prefix]. Jeżeli klient pomimo tego często źle odpisuje, to najlepiej w cron ustawić akcje wysyłającą klientowi informacje o zarejestrowaniu zgłoszenia już z gotowym odpowiednim tematem i z informacje, że jeżeli ma uwagi to powinien odpowiadać właśnie na tego maila.
