### ISSUE TITLE
[Question] How-to: Sub-organizations of organizations (Accounts module)

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13267]
Hello,

have a small number of organizations that have different **locations** or **sub-organizations**.

Is there a way to **add a sub-organizations** account in the regular accounts module and **define a relationship to another organization** who is the "master"/mother of that sub-organisation?

I already thought about adding this sub-organizations as "contact" and assign them to a organisation, but it is not really a nice way and what I want.

Thanks!

Regards

**Comment by vovpff** [comment]
Member of field for accouts?

**Comment by blu-IT** [comment]
Oh, yes! Thanks!
