### ISSUE TITLE
[bug] Installation Failed (ver 5.3.0)

### ISSUE THREAD

**Issue by shanjbin** [YetiForceCompany/YetiForceCRM#13262]
hello,
i tried to install Yetiforce CRM on my fresh WP platform website (http://pro.101group.ca) from CPanel - Softaculous panel, 
it is a share-server from Hostupon.com, but it gives me the following error, whereas i never installed yetiforce on this website before
thanks,
​​​​​​​Shan

**Comment by KatarzynaUlichnowska** [comment]
Hello, thank you for submitting the issue but all Softaculous-related issues should be reported directly to them. Here is a link to open an issue: https://softaculous.deskuss.com/open.php
