### ISSUE TITLE
[Question] PHP Fatal error:  the zip library is missing

### ISSUE THREAD

**Issue by AllOnMyOhm** [YetiForceCompany/YetiForceCRM#13265]
Hello folks, I'm getting the following error when trying to run the install, I downloaded the (PHP PEAR Packages) Archive_Zip package, but I guess that wasn't the issue...

_________________________________________

[06-Jul-2020 08:51:23 UTC] PHP Fatal error:  Uncaught Exception: The zip library is missing in /home/x/public_html/yeti/include/RequirementsValidation.php:15
Stack trace:
#0 /home/x/public_html/yeti/install/Install.php(24): include_once()
#1 {main}
  thrown in /home/x/public_html/yeti/include/RequirementsValidation.php on line 15
[06-Jul-2020 08:55:43 UTC] PHP Fatal error:  Uncaught Exception: The zip library is missing in /home/x/public_html/yeti/include/RequirementsValidation.php:15
Stack trace:
#0 /home/x/public_html/yeti/install/Install.php(24): include_once()
#1 {main}
  thrown in /home/x/public_html/yeti/include/RequirementsValidation.php on line 15

**Comment by vovpff** [comment]
```
apt install phpX.X-zip
```

For ubuntu available modules:

```
apt install php7.3
php7.3            php7.3-curl       php7.3-gmp        php7.3-mbstring   php7.3-pspell     php7.3-sybase
php7.3-bcmath     php7.3-dba        php7.3-imap       php7.3-mysql      php7.3-readline   php7.3-tidy
php7.3-bz2        php7.3-dev        php7.3-interbase  php7.3-odbc       php7.3-recode     php7.3-xml
php7.3-cgi        php7.3-enchant    php7.3-intl       php7.3-opcache    php7.3-snmp       php7.3-xmlrpc
php7.3-cli        php7.3-fpm        php7.3-json       php7.3-pgsql      php7.3-soap       php7.3-xsl
php7.3-common     php7.3-gd         php7.3-ldap       php7.3-phpdbg     php7.3-sqlite3    php7.3-zip
```

**Comment by AllOnMyOhm** [comment]
> ```
> apt install phpX.X-zip
> ```
> 
> For ubuntu available modules:
> 
> ```
> apt install php7.3
> php7.3            php7.3-curl       php7.3-gmp        php7.3-mbstring   php7.3-pspell     php7.3-sybase
> php7.3-bcmath     php7.3-dba        php7.3-imap       php7.3-mysql      php7.3-readline   php7.3-tidy
> php7.3-bz2        php7.3-dev        php7.3-interbase  php7.3-odbc       php7.3-recode     php7.3-xml
> php7.3-cgi        php7.3-enchant    php7.3-intl       php7.3-opcache    php7.3-snmp       php7.3-xmlrpc
> php7.3-cli        php7.3-fpm        php7.3-json       php7.3-pgsql      php7.3-soap       php7.3-xsl
> php7.3-common     php7.3-gd         php7.3-ldap       php7.3-phpdbg     php7.3-sqlite3    php7.3-zip
> ```

I'm not sure how to go about this in Cpanel... T_T

**Comment by AllOnMyOhm** [comment]
I did the following:
in WHM -> Software -> EasyApache 4 clicked "Customize", then clicked "PHP Extensions", then wrote "zip" in the search box, enabled php**-php-zip for all PHP versions, then clicked "Review", and then "Provision".

Still nothing

**Comment by vovpff** [comment]
@AllOnMyOhm this is difficult because I work with my server direct by ssh without any admin panels. Your trouble related to your server. Request support from your hoster.
