### ISSUE TITLE
[bug] Can't import phone numbers from CSV (Accounts module)

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13261]
# 🐞 bug report

### ⁉️ Describe the bug

When trying to import organizations and here espacially phone number(s) for from CSV file, I get the message: 
**"Non vaild value for this field type was entered. Field: phone, module: accounts, value: 026185 ...."**

![Screenshot_2020-07-04 Organisationen](https://user-images.githubusercontent.com/13665806/86512856-dc65e280-be05-11ea-9542-4da10173ad9e.png)

All other columns like name, address etc. are accepted, but not the phone numbers. 
I also tried playing around with values like +49026185 ... or 26185 ..., but no way!

The import of CSV file only works when phone number is left blank.

### 🔥 How to trigger the error

1. Go to Companie and contacs
2. Click on Accounts
3. Click on Actions
4. Scroll down to Import
5. Select CSV file to import 
6. See error

### 👎 Actual Behavior

Import of complete CSV file is aborted.

### 👍 Expected Behavior

All columns including phone number are imported

### 👷 Testing

- [ X] I confirm that I tested it at https://gitstable.yetiforce.com
- [no - link not loading ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3 SP4
| Web server (name and version)       |         Apache2       |
| PHP                                 |       7.3         |
| Browser (name and version)          |         Firefox 78.01       |
| Operating System (name and version) |   Ubuntu Server 20.04 LTS      |
| Database (name and version)         |          MariaDB      |
| Service Pack version                |     SP 4           |

**Comment by waran70** [comment]
0049?

**Comment by blu-IT** [comment]
No, also doesn't work.

**Comment by rskrzypczak** [comment]
You have two options here:
- Disable phone number verification.
  This is a global procedure and requires modification of the /config/Main.php configuration file, in which 
  $phoneFieldAdvancedVerification = false should be set
- Correct all phone numbers in imported files, e.g.
   You can check the number on the GUI, but enter the file without spaces
   
![image](https://user-images.githubusercontent.com/10221999/86520366-ac3d3480-be43-11ea-994a-5622cdcb535c.png)

**Comment by Giorgos-Hellene** [comment]
Firstly, check if the number can be inserted to one simple record. If not you have problem with number.

Secontly, select one record which has this telephone number and export it. Open the csv file with Notepad ++ ,  check the format and supply the same format for all other records you want to import.
It had help me many times

Besides, if you want upload the exported csv file
i remember that the right format was +code of country and number

**Comment by blu-IT** [comment]
Thanks!

@rskrzypczak What kind of "phone number verification" / checks are done? What are the conditions for phone numbers format?

@Giorgos-Hellene I already tried different formats as +49026185, 0049026185, 26185, ... also exported a manually inserted number and I was not able to reimport. Only one time I was successful, but I can't get the point why. I have changed nothing.

I think I will disable phone number verification for the import process and after that reactivate the verification. I will report when everything went right.

**Comment by Giorgos-Hellene** [comment]
@blu-IT when i try to write the number +49026185 on my YetiForce i get error. ( i tried it with country as Germany )

which country does your number belong? Is it Germany number? It is important to know it

**Comment by blu-IT** [comment]
@Giorgos-Hellene 

Hi, yes it is a german number - but I did not post all digits for privacy reasons. 
So +49 would be right, but with the country code the number should look like this +4926185 (without "0").

**Comment by blu-IT** [comment]
> You have two options here:
> 
>     * Disable phone number verification.
>       This is a global procedure and requires modification of the /config/Main.php configuration file, in which
>       $phoneFieldAdvancedVerification = false should be set

OK, this worked for me now and I could import my CSV file.

But I would be very interesting to know, what YF expects when doing a phone number verification.
