### ISSUE TITLE
[Question] Shareable Widgets

### ISSUE THREAD

**Issue by jimlongo56** [YetiForceCompany/YetiForceCRM#13268]
Can I create a widget or chart that is available to all users on their homepage?
Please explain the steps. I can't find documentation on creating widgets.

**Comment by rskrzypczak** [comment]
Use the widget management panel
![image](https://user-images.githubusercontent.com/10221999/86705224-f37b1f00-c015-11ea-82ad-ecc03f7166a8.png)

**Comment by jimlongo56** [comment]
It's not clear how you got to that path in the screenshot.
I don't see any selection for `Dashboard - Widgets`.
Should I be looking somewhere else?

![Screen Shot 2020-07-08 at 10 15 06 AM](https://user-images.githubusercontent.com/6787988/86929684-1b48b080-c104-11ea-9993-d6752d5fc048.png)

**Comment by vovpff** [comment]
@jimlongo56 2nd one
