### ISSUE TITLE
No documentation for installation on macOS

### ISSUE THREAD

**Issue by zendevil** [YetiForceCompany/YetiForceCRM#13273]
Are there detailed step by step instructions how to install yetiforce on macOS? A web search didn't return anything for macOS installation.

**Comment by bpabiszczak** [comment]
Why do you want to install YetiForce on macOS [we don't recommend macOS]? We recommend linux or find a good hosting. 

- Hosting: https://yetiforce.com/en/marketplace/hosting-en
- Cloud VPS: https://yetiforce.com/en/marketplace/cloud
