### ISSUE TITLE
[Feature] Split git on 2 parts

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#13272]
What about splitting (somehow) yeti git on:

1. How to do: (use existing functionalities - beginners coders/not skilled users/spammers)
2. Contribute: (talk about errors and improvement - limited to approved guys with little sense of what is going on)
hmm?

**Comment by bpabiszczak** [comment]
And what will it change?

**Comment by waran70** [comment]
You going to spend more time on productive tasks rather than teaching kids how to use crm.
Community helps the community, developers help developers.

**Comment by bpabiszczak** [comment]
If you have to learn, it means you need to improve your CRM. This is a closed circle. Two communities mean more work for us.
