### ISSUE TITLE
How to buy support service

### ISSUE THREAD

**Issue by 99maoni** [YetiForceCompany/YetiForceCRM#13279]
Help me know how can I buy support services for self hosted version. I got this link (yetiforce.shop) somewhere but it does not work. Thank you.

**Comment by KatarzynaUlichnowska** [comment]
Hello, the easiest way to buy our services is to go to the Marketplace in your CRM system (if you have one of the latest versions). 
The link yetiforce.shop is no longer working as we are moving all products and services to our official website and next week it all should be up and running. You can see on the screenshot below how it will look like and where it will be located in the menu. 

![Zrzut ekranu 2020-07-09 o 11 53 32](https://user-images.githubusercontent.com/10218164/87025978-61247800-c1db-11ea-9eba-ccdf4fd066c4.png)
