### ISSUE TITLE
[Question] PDF custom textParser based on relatedRecordsList ?

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13278]
Hi,

I would like to customize relatedRecordsList function in app/TextParser.php but this function is protected.

So I simply change this function visibility to 'public' and all goes well but maybe there was a good reason for it to be protected ?

```
namespace App\TextParser;

/**
 * Amount to return.
 *
 * @copyright YetiForce Sp. z o.o
 * @license   YetiForce Public License 3.0 (licenses/LicenseEN.txt or yetiforce.com)
 * @author    Tomasz Kur <t.kur@yetiforce.com>
 */
class MyCustomClass extends Base
{
	/** @var string */
	public $name = 'LBL_CUSTOM_FUNCTION_NAME';

	/** @var mixed Parser type */
	public $type = 'pdf';

	/** @var array Allowed modules */
	public $allowedModules = ['MY_MODULE_NAME'];


	/**
	 * Process.
	 *
	 * @return string
	 */

	public function process()

	{

		$html = '';
		$html.= $this->textParser->relatedRecordsList('RELATED_MODULE_NAME');

// do your stuff...

	return $html;

	}

}

```

**Comment by rskrzypczak** [comment]
The TextParser Class, as the name suggests, is used for text parsing, this is why functions aren't public by assumption.
If you have to perform any operations you should initiate a new TextParser object and give it a variable that you will then parse, for example:
`
$html.= \App\TextParser::getInstanceByModel($this->textParser->recordModel)->setContent('$(relatedRecordsList : Contacts|firstname,lastname,email|[[["firstname","a","Tom"]]]||5)$')->parse()->getContent();`

**Comment by apcloic** [comment]
@rskrzypczak Thanks a lot !
