### ISSUE TITLE
SMTP Error (-1): Connection to server failed.

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#13275]
I didn’t do any updates or changes to the settings, but it just stopped working.
![Email](https://user-images.githubusercontent.com/25682437/86895129-50550300-c104-11ea-9a24-f25b8476a9e9.gif)

**Comment by bpabiszczak** [comment]
mail server logs? yetiforce crm logs?

**Comment by fbojan** [comment]
There was an error setting up the GMAIL server.
THANK YOU

V V sre., 30. sep. 2020 ob 11:59 je oseba Błażej Pabiszczak <
notifications@github.com> napisala:
