### ISSUE TITLE
[Question] Can't assign "Member of" in Account module (organizations)

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13270]
Hello,

now that I know how to assign a sub-organization or location to a organization https://github.com/YetiForceCompany/YetiForceCRM/issues/13267 I want to assign a value into **existing accounts** to in the **"Member of"** field. But I can't because there is no way to edit the field:

![Screenshot_2020-07-07 Accounts YetiForce Sp z o o ](https://user-images.githubusercontent.com/13665806/86749243-6055df80-c03d-11ea-9ae9-734cd9b5d72a.png)

Only when creating a new entry for an Account I can select a organization in that "Member of" field.

Any idea why? Screen shot is from gitstable but also my testsystem behaves like this.

Thanks!

**Comment by vovpff** [comment]
Relation 1:M fields can be edited only trough full edit view

![image](https://user-images.githubusercontent.com/8545791/86777813-4bd80e00-c062-11ea-8cfa-8767b5ce0545.png)

**Comment by blu-IT** [comment]
Oh, OK - thanks!!! I could have checked that before, I am sorry..!
But to be honest it is a little bit confusing, that some fields can only be changed through the full edit view.
