### ISSUE TITLE
Fatal error: Uncaught App\Exceptions\AppException: ERR_NO_JSON_DECODE in 

### ISSUE THREAD

**Issue by 99maoni** [YetiForceCompany/YetiForceCRM#13274]
Hello, I have been using YetiForce for about a month now, but I just opened my login page yesterday and got this error

Fatal error: Uncaught App\Exceptions\AppException: ERR_NO_JSON_DECODE in /home/onedayho/domains/onedayhost.com/public_html/crm/app/Json.php:40 Stack trace: #0 /home/onedayho/domains/onedayhost.com/public_html/crm/app/Language.php(353): App\Json::decode('{\n "php": {\n ...', true) #1 /home/onedayho/domains/onedayhost.com/public_html/crm/app/Language.php(306): App\Language::loadLanguageFile('en-US', 'Other/Exception...') #2 /home/onedayho/domains/onedayhost.com/public_html/crm/vtlib/Vtiger/Functions.php(363): App\Language::translateSingleMod('Class 'Locale' ...', 'Other/Exception...') #3 /home/onedayho/domains/onedayhost.com/public_html/crm/include/main/WebUI.php(199): vtlib\Functions::throwNewException(Object(Error), false, 'LBL_ERROR') #4 /home/onedayho/domains/onedayhost.com/public_html/crm/index.php(28): Vtiger_WebUI->process(Object(App\Request)) #5 {main} thrown in /home/onedayho/domains/onedayhost.com/public_html/crm/app/Json.php on line 40

I have checked here in previous issues but I could not find something like this. Please help me on how I can resolve the issue. Thank you

**Comment by 99maoni** [comment]
I am using version 5.3 and php 7, I tried to change it to 7.2 7.3, 7.4 but it did not work

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/86811698-7df76900-c07e-11ea-82e2-7c2db3322634.jpg)

**Comment by mariuszkrzaczkowski** [comment]
check the requirements carefully, your server does not meet the configuration requirements
