### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#13276]
## 🚀 feature request
Hi team 
From last 2 days regularly my team is getting  "This site can’t be reached" please let us why we are not able to access my CRM properly.
![Server bug](https://user-images.githubusercontent.com/47585969/86897086-9752f080-c124-11ea-8e6b-1b4b1aff0de0.PNG)

**Comment by mariuszkrzaczkowski** [comment]
this is a question for your admin not for us

**Comment by guide5232** [comment]
I am the admin for my CRM I am thinking this is for server-side problem. please let us know which problem is this.

**Comment by mariuszkrzaczkowski** [comment]
I meant server administrator

**Comment by guide5232** [comment]
My company is using yetiforce server.that is why i have posted here.

**Comment by KatarzynaUlichnowska** [comment]
Hello, if you purchased any of our services and have problems, please send us an e-mail to sla@yetiforce.com. Please include the address of your CRM and which service/product you purchased and when, so we can identify you. Unfortunately, your GitHub login doesn't tell us which company you are from.

**Comment by guide5232** [comment]
ok
