### ISSUE TITLE
Syntax error or access violation: 1118 Row size too large. [bug] 

### ISSUE THREAD

**Issue by 2techcomputing** [YetiForceCompany/YetiForceCRM#13289]
I was attempting to create some new custom fields and i am now getting the error message "SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
The SQL being executed was: ALTER TABLE `vtiger_account` ADD `test1` varchar(6) DEFAULT ''

I was able to create custom entries yesterday without issue but now when i go into any module to create a custom entry i am receiving the error, any idea on what may be needed to resolve it. Thanks.

![custom field error](https://user-images.githubusercontent.com/60716615/87209424-a5d90d80-c2c6-11ea-84da-50b20aa8cc76.png)

**Comment by mariuszkrzaczkowski** [comment]
what are these parameters set?

![20200716_211510](https://user-images.githubusercontent.com/10198654/87712791-800da600-c7a9-11ea-9a3a-25b9e7fb6534.jpg)

**Comment by 2techcomputing** [comment]
Here is a copy of my server configuration file, i cannot seem to find the section specified in the file.
![yetiforce_settings](https://user-images.githubusercontent.com/60716615/87819818-bc7ce880-c821-11ea-9044-7302601669f1.png)

**Comment by mariuszkrzaczkowski** [comment]
you have a lot to improve
- you have different php versions for CLI and www and they must be the same
- you have different cli and www configuration
- correct all incorrectly set configuration parameters PHP + DB
- we recommend upgrading to a stable version
- you have old crm version, therefore configuration verification report does not contain new parameters, show query result for Mysql:  SHOW VARIABLES

**Comment by mariuszkrzaczkowski** [comment]
If you don't change it, we have nothing to talk about

**Comment by 2techcomputing** [comment]
I will contact my hosting provider to get the required changes made and let you know once i hear back from them.

**Comment by 2techcomputing** [comment]
I am attempting to perform the update to version 5.3.0 but i am receiving the error "Wrong version of module, module version 5.2.0 but it should be greater than 5.2.2" any idea why its not proceeding.

![failed update](https://user-images.githubusercontent.com/60716615/87835831-278ae700-c843-11ea-82eb-c78ac4c8abda.png)

**Comment by bpabiszczak** [comment]
I don't see you solving the previous problems

**Comment by 2techcomputing** [comment]
He asked me to upgrade to a new stable version which is what i was trying to do and then i received the above error message. Updating the crm was one of the recommendations from @mariuszkrzaczkowski

**Comment by bpabiszczak** [comment]
The configurations must be corrected before the upgrade. Who will now fix errors caused by updating on a misconfigured server?
