### ISSUE TITLE
Adding Tax percentage to invoice template[Question] 

### ISSUE THREAD

**Issue by 2techcomputing** [YetiForceCompany/YetiForceCRM#13288]
I am looking to add the tax percentage or the tax name in front of the tax value that appears on an invoice. Would it be possible to get the code in order to modify the TableTaxSummary.php file to add the extra field in this line. Thanks.

td class="value" style="text-align:center;font-size:11px;font-weight:bold;padding:0px 0px;">'  . $currencyData['currency_symbol'] . ' ' . \CurrencyField::convertToUserFormat($tax, null, true) . '

**Comment by konadrian** [comment]
In one of our clients we added something like this in text parser
```
elseif ('Tax' === $field->getType()) {
$itemValue = $inventoryRow[$field->getColumnName()];
$html .= '<td style="font-size:8px;border:1px solid #ddd;padding:0px 4px;' . (\in_array($field->getType(), $fieldsTextAlignRight) ? 'text-align:right;' : '') . '">';
$percent = $this->textParser->recordModel->getTaxPercentValue($inventoryRow['taxparam']);
$html .= $field->getDisplayValue($itemValue, $inventoryRow) . " ({$percent}%)";
$html .= '</td>';
}
```
And this method in record model
```
	public function getTaxPercentValue($item)
	{
		$value = 0.0;
		$taxParam = \App\Json::decode($item);
		$types = (array) $taxParam['aggregationType'];
		if ($types) {
			foreach ($types as $type) {
				$value += $taxParam["{$type}Tax"];
			}
		}
		return $value;
	}
```
