### ISSUE TITLE
[Question] Nie mogę odpowiadać na emaile Zgłoszeń Kontrahentów /  I cannot reply to the e-mail address of Accounts Tickets

### ISSUE THREAD

**Issue by utp-proj-sztuczna** [YetiForceCompany/YetiForceCRM#13282]
W Yetiforce mam problem z modułem "Zgłoszenia", nie mogę w tym module odpowiadać na emaile kontrahentów, cały panel odpowiadania na emaile jest nie widoczny w module Zgłoszenia. W innych modułach jak Historia emaili czy Kontahenci mam możliwość odpowiadania na maile zgłoszeń i powinno tak samo działać odpowiadanie w Zgłoszeniach. W załączniku wysyłam całą konfiguracje modułów. 

In Yetiforce I have problem with module Tickets, I can't send any mails to Accounts, whole panel that have function to reply to mails in module Tickets isn't visible. In other modules like Email history or Accounts I have this function and theoretically it should also work in module Tickets. In attachment I send module configuration. 
![1](https://user-images.githubusercontent.com/66875302/87045342-12390b80-c1f8-11ea-87ac-979673e5a293.png)

**Comment by rskrzypczak** [comment]
Mechanizm pozwiązywania maili ze zgłoszeniami działa na podstawie prefix-ów, a nie adresów mailowych.
Mam nadzieję, że ten filmik trochę Ci to rozjaśni.
https://www.youtube.com/watch?v=0JBckYE9ZuI&list=PLX0lktP3Kukg_Da-TaEBys-aON68Yy2vh&index=10
