### ISSUE TITLE
instant duplicate check [Feature] 

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13284]
can yeti force team develop a instant duplicate checker for leads, contacts n accounts as in vtiger or joforce.
its a very very much anticipated feature and without this working with crm seems difficult.

**Comment by kamiro16** [comment]
Hello @rioshaz,

I think you search this -[https://github.com/YetiForceCompany/YetiForceCRM/issues/11965](url)

**Comment by rioshaz** [comment]
@kamiro16  thanks
