### ISSUE TITLE
[bug]Inspite of changing 'Record' to 'Messege', Email Template is not working on Yetiforce, Round cube Email

### ISSUE THREAD

**Issue by asktechchef** [YetiForceCompany/YetiForceCRM#13281]
# 🐞 bug report

### ⁉️ Describe the bug
I am not able to use Email Template in Yeti Force and the button is disabled on its Roundcube. I tried changing Template from 'Record' to 'Messege' but the issue still remains the same. 

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13203
https://github.com/YetiForceCompany/YetiForceCRM/issues/12982

**Comment by asktechchef** [comment]
@rskrzypczak Thank you so much. #13203 solved this issue.
