### ISSUE TITLE
What does that code mean? 

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#13283]
### Description

What does this mean?
**SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '391' for key 'PRIMARY' The SQL being executed was: INSERT INTO `u_yf_crmentity_label` (`crmid`, `label`) VALUES (391, 'jh')**

**Comment by vovpff** [comment]
Record with crmid 391 already available in u_yf_crmentity_laber table. Something working wrong

**Comment by ghost** [comment]
i dont undrstand. where can i find u_yf_crmentity_laber table? what is a crmind

**Comment by mariuszkrzaczkowski** [comment]
duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/12768
