### ISSUE TITLE
[Question] How to add reference (UIType10) field

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13297]
Hello,

I am trying to ad a custom field to the "Internal tickets" module / interface.
My goal is to link to another internal ticket like it is already possible in the "Trouble tickets" section -> parentid.
But when creating an new field, I can't find the type "reference (UIType10)". I tried some others like Text, Integer, etc. but this does not lead to success.

Thanks!

Regards

**Comment by rskrzypczak** [comment]
Select field type: "Related field 1:M"

**Comment by blu-IT** [comment]
Yes, thank you!
