### ISSUE TITLE
[Security] Not able to Install Yetiforce using SSL for MySQL Connection. This is inherently insecure as MySQL requests will be transported in http plain text. How to enable SSL for MySQL Connections from Yetiforce

### ISSUE THREAD

**Issue by isahuntercsggit** [YetiForceCompany/YetiForceCRM#13295]
I'm Not able to Install Yetiforce using SSL for MySQL Connection. This is inherently insecure as MySQL requests will be transported in http plain text. How to enable SSL for MySQL Connections from Yetiforce?

**Comment by blu-IT** [comment]
Can you post some more information please? 
E.g. where is your database located? On the same host?

**Comment by isahuntercsggit** [comment]
[cid:image007.jpg@01D659F8.AD9A7270]

Best Regards,


Isa Hunter
[cid:image002.png@01D659F8.AD8563D0]
isahunter@compsolglobal.com<mailto:ihunter@us.hanusoftware.com> | compsolglobal.com<https://compsolglobal.com/> | 518-335-8860
[cid:image003.png@01D659F8.AD8563D0][cid:image004.png@01D659F8.AD8563D0][cid:image005.png@01D659F8.AD8563D0][cid:image006.jpg@01D659F8.AD8563D0]

**Comment by blu-IT** [comment]
I am sorry, but no image is loaded...

**Comment by isahuntercsggit** [comment]
The Database is located on Azure MySQL Database.

Best Regards,


Isa Hunter
[cid:image001.png@01D65A97.8DAFF990]
isahunter@compsolglobal.com<mailto:ihunter@us.hanusoftware.com> | compsolglobal.com<https://compsolglobal.com/> | 518-335-8860
[cid:image002.png@01D65A97.8DAFF990][cid:image003.png@01D65A97.8DAFF990][cid:image004.png@01D65A97.8DAFF990][cid:image005.jpg@01D65A97.8DAFF990]

**Comment by mariuszkrzaczkowski** [comment]
This is not enough, a larger description is needed

**Comment by isahuntercsggit** [comment]
![YetiforceError](https://user-images.githubusercontent.com/40643383/87568110-1ef3ae80-c693-11ea-831a-da6a06a9fc8e.png)

**Comment by isahuntercsggit** [comment]
Essentially an Azure Linux WebApp and Azure MySQL Database with SSL Enforced Turned On

**Comment by blu-IT** [comment]
Is the YF installation on the same host as the database? Hostname seems strange to me...
If it's on the same host, maybe have to set 127.0.0.1 or localhost for hostname and than also data security / ssl won't be a problem any more.

**Comment by isahuntercsggit** [comment]
Azure MySQL Database  It is not on the local host. This is a Distributed N-Tier Architecture.

**Comment by mariuszkrzaczkowski** [comment]
This requires changes in the core (app/db.php)
Get to know the links
https://owendavies.net/articles/azure-php-mysql-ssl/
https://github.com/YetiForceCompany/yii2-framework/blob/yetiforce/db/Connection.php

**Comment by isahuntercsggit** [comment]
Thanks this is just what I was seeking. Is it possible to make it a feature like a check box use ssl and an upload CA that only takes .pem files

**Comment by mariuszkrzaczkowski** [comment]
sure it is possible, everything is possible, only that will pay for it
