### ISSUE TITLE
[bug] Field Values not working when mail is sent using any email template.

### ISSUE THREAD

**Issue by asktechchef** [YetiForceCompany/YetiForceCRM#13291]
# 🐞 bug report

### ⁉️ Describe the bug
Field Values not working when mail is sent using any template.

### 👎 Actual Behavior

Showing code records in the sent email

### 👍 Expected Behavior

Should show value against record code.

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by asktechchef** [comment]
can @KatarzynaUlichnowska you help?

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13360
