### ISSUE TITLE
[Question] [PL] Komendy dodawania zadań w Cron

### ISSUE THREAD

**Issue by utp-proj-sztuczna** [YetiForceCompany/YetiForceCRM#13296]
Jakie są komendy do ustawiania zadań w cron?

![image](https://user-images.githubusercontent.com/66875302/87298222-1f147280-c50a-11ea-8638-684677165fac.png)

**Comment by bpabiszczak** [comment]
W dokumentacji hostingu znajdziesz. Spytaj administratora serwera. 
Tutaj przykłady z innego hostingu: https://help.dreamhost.com/hc/en-us/articles/215767047-Creating-a-custom-Cron-Job
Tutaj przykłady podane na naszej stronie: https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/uruchamianie-crona
