### ISSUE TITLE
roundcube responsive theme 1.4 [Feature] 

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13292]
round cube has globally rolled out their new look n feel official theme 1,4 with responsive layout.. when can we the same included in yetiforce mailbox client ? any update  or can we implement it ourself some how ?

https://scdn1.plesk.com/wp-content/uploads/2018/06/24154541/kolab4.png

**Comment by KatarzynaUlichnowska** [comment]
We are planning to update RoundCube in 5.4 version. You can, of course, do it yourself but it requires programming knowledge and changes in the code.

**Comment by rioshaz** [comment]
@KatarzynaUlichnowska thats really great, when are you guys planning to release 5.4 table version ?
