### ISSUE TITLE
Project templates. Missing translation

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1330]
In project templates when I saving new template I get untranslated error 
![Error](https://cloud.githubusercontent.com/assets/3193498/8498872/964c37ce-218c-11e5-96c3-a65a150bbcc9.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/8fa7f8183efab29363cb8602061f86825d7c074d
