### ISSUE TITLE
[Question] Languages update cUrl timeout error 

### ISSUE THREAD

**Issue by MaxPegankin** [YetiForceCompany/YetiForceCRM#13306]
Greetings,

I need some help,

I can't update Languages from settings, have "Error while parsing server responses".

Yetiforce version 5.3.0

_System.log
====================================================================================================================================
2020-07-14 14:47:49.0221 [warning][App\Fields\File] - Checked URL is not allowed: https://github.com/YetiForceCompany/YetiForceCRMLanguages/raw/master/Developer/zh-CN.zip | cURL error 28: Operation timed out after 10001 milliseconds with 134358 out of 231303 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
2020-07-14 14:47:37.6776 [info][application] - 
$_GET = []
$_POST = [
    '_csrf' => 'sid:02b57e06ba172217b14912fb0a7ed9caf82d2ad4,1594709255'
    'module' => 'YetiForce'
    'parent' => 'Settings'
    'action' => 'DownloadLanguage'
    'prefix' => 'zh-CN'
]_

I can open the same link from the same server, so it is not a problem. But, because the server is in China it needs more time to download international files.

Can I increase that timeout somewhere? 

![ConfReport](https://user-images.githubusercontent.com/54612661/87408076-8fe48900-c5f5-11ea-8ddd-6aab00807d91.png)

**Comment by MaxPegankin** [comment]
I increased it here, it solved my problem.

/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php 

      $timeoutRequiresNoSignal = false;
        if (isset($options['timeout'])) {
            $timeoutRequiresNoSignal |= $options['timeout'] < 1;
            $conf[CURLOPT_TIMEOUT_MS] = $options['timeout'] * 100000; //1000
        }
        // CURL default value is CURL_IPRESOLVE_WHATEVER
        if (isset($options['force_ip_resolve'])) {
            if ('v4' === $options['force_ip_resolve']) {
                $conf[CURLOPT_IPRESOLVE] = CURL_IPRESOLVE_V4;
            } elseif ('v6' === $options['force_ip_resolve']) {
                $conf[CURLOPT_IPRESOLVE] = CURL_IPRESOLVE_V6;
            }
        }
        if (isset($options['connect_timeout'])) {
            $timeoutRequiresNoSignal |= $options['connect_timeout'] < 1;
            $conf[CURLOPT_CONNECTTIMEOUT_MS] = $options['connect_timeout'] * 2000; //1000

**Comment by mariuszkrzaczkowski** [comment]
limits are easier to change here
https://github.com/YetiForceCompany/YetiForceCRM/blob/78926e8dc8b6b759368890c7b38a6afa13b16b6c/app/RequestHttp.php#L32-L33
