### ISSUE TITLE
Sending mail from  service contract detail view doesn't work properly

### ISSUE THREAD

**Issue by pietro559** [YetiForceCompany/YetiForceCRM#13308]
When i want to send an email from service contract detail view, a pop-up window appears (without a mail filled).
If i want to choose one manually by pressing 'Lead' button, a list of leads appears in main window instead of the pop-up.
That happens if it's about any other module wich is not a 'contact module'.

![mail_error](https://user-images.githubusercontent.com/67751615/87514626-362aa000-c683-11ea-9a13-37593a770624.png)

**Comment by bpabiszczak** [comment]
1. I don't understand the problem, show me the video.
2. Also check the gitstable and gitdeveloper versions.
