### ISSUE TITLE
[Question] Combine other modules (Internal tickets) with Knowledge base

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13313]
Hello,

when entering new information/articles to the Knowledge base, there are different other modules like "similar entries, documents, tickets, projects" on the right side.
I would like to add the possibility also to map to related "Internal tickets" instead only "Tickets". I could not find where to configure in the system settings.

Thanks!

**Comment by KatarzynaUlichnowska** [comment]
Hello, you can add additional relations to modules if you go to Software configuration > Standard modules > Modules – Relations. See the screenshots below:

![Zrzut ekranu 2020-07-16 o 09 56 51](https://user-images.githubusercontent.com/10218164/87643370-165eaf00-c74b-11ea-8367-a79449b3ba4a.png)

![Zrzut ekranu 2020-07-16 o 09 57 09](https://user-images.githubusercontent.com/10218164/87643378-19599f80-c74b-11ea-9d14-f4895aff9aeb.png)

**Comment by blu-IT** [comment]
@KatarzynaUlichnowska 

Thanks a lot! I already saw that settings, but did not understand the functionality.

But my problem is now, that **I don't have the button to add relations**?! I am admin on that system.

![Screenshot_2020-07-16 Layout-Editor System Einstellungen](https://user-images.githubusercontent.com/13665806/87646760-617ac100-c74f-11ea-8bbc-8ee15d4cc83d.png)

**Comment by blu-IT** [comment]
I am testing on YF 5.3 SP4

**Comment by blu-IT** [comment]
Looking at **gitstable** it is the same behavior:

![Screenshot_2020-07-16 Layout Editor System settings](https://user-images.githubusercontent.com/13665806/87648440-0f866b00-c750-11ea-973d-c4da9f898597.png)

Is this a bug?

**Comment by KatarzynaUlichnowska** [comment]
No, it's not a bug. It is a stable version and therefore it is disabled by default because the operation requires knowledge. In order to enable the button, set the CHANGE_RELATIONS value to true in the configuration.

**Comment by blu-IT** [comment]
OK, thanks! 

```
YetiForceCRM/config/developer.php
'CHANGE_RELATIONS' => false, 
```

Found also this entry here: https://github.com/YetiForceCompany/YetiForceCRM/issues/7812#issuecomment-415358611
