### ISSUE TITLE
[Question] [PL][ENG] Is it possible to hide the "Add Record" button in the selected module?

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#13315]
Czy jest możliwość, aby ukryć przycisk "Dodaj rekord" w wybranym module?
_Is it possible to hide the "Add Record" button in the selected module?_

Chce zachować uprawnienia do tworzenia rekordu, dodawanie rekordu odbywa się tylko przez mapowanie, a nie bezpośrednio w module.
_I want to keep the record creation permissions, adding the record is done only through the mapping, not directly in the module._

![obraz](https://user-images.githubusercontent.com/62466142/87632095-f4f4c780-c738-11ea-9112-c344ca2d41ce.png)

**Comment by vovpff** [comment]
You need to change rights to profiles to disable ability to create records. This button will dissapear

**Comment by vdpawel** [comment]
Thanks for the answer, I can't do that because then I can't generate the record by mapping as well.

**Comment by vovpff** [comment]
@vdpawel in this case you need to change code of system to add condition of this button appearance like if module is `yourmodule` then button disabled. I think this can be done by templates modification.

**Comment by vdpawel** [comment]
Thank you, I have followed your advice.

In the file
/layouts/basic/modules/Vtiger/ListViewHeader.tpl

I put the appropriate condition into the line displaying the button:
{include file = \ App \ Layout :: getTemplatePath ('ButtonLink.tpl', $ MODULE) BUTTON_VIEW = 'listView' CLASS = 'mr-sm-1 mb-1 c-btn-block-sm-down'}

Works!

**Comment by vovpff** [comment]
@vdpawel could you share your code instead original?

**Comment by vdpawel** [comment]
**{if $MODULE != "SQuotes" && $MODULE != "SSingleOrders"}**
            {include file=\App\Layout::getTemplatePath('ButtonLink.tpl', $MODULE) BUTTON_VIEW='listView' CLASS='mr-sm-1 mb-1 c-btn-block-sm-down'}
**{/if}**
