### ISSUE TITLE
[Question] How to define a new ticket status (closed - internal tickets) correctly / translations

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13310]
Hello,

I missed a ticket status (closed) for the internal tickets module. So I defined a new one in the system settings, picklist -> (german: Geschlossen)..., so far everything fine at the first look.
Studying the database table "vtiger_internal_tickets_status" I saw now that a correct defined status would be "PLL_CLOSED", like the others e.g. "PLL_UNASSIGNED", but if I define it that way no translation is shown and users would see PLL_CLOSED in their dropdown.
I experienced some problems with widget filters for the tickets now for status closed and I guess it is, because I tested renaming the ticket status in "PLL_CLOSED" and then back in "Geschlossen".

So my first question is: How to define a new status correctly also having other languages in mind?
And what could be the problem now, when filtering for closed tickets in my widget that are not shown?

![Screenshot_2020-07-15 Meine Startseite(1)](https://user-images.githubusercontent.com/13665806/87533338-bf969e00-c694-11ea-8e36-7e0418c97f6c.png)

In the Ticket module / view itself the filters for closed tickets work correctly.

![Screenshot_2020-07-15 Tickets Liste](https://user-images.githubusercontent.com/13665806/87533355-c6251580-c694-11ea-8b9f-52c81874957c.png)

Thanks!

**Comment by blu-IT** [comment]
I should mention, that I added the ticket status "Closed / Geschlossen" to the picklist of the Internal tickets module and changed to "PLL_CLOSED" there and back.
But I did not touch the status of "normal" tickets, but the filter in the widget also does not work. For other status then closed it works:
![Screenshot_2020-07-15 Meine Startseite](https://user-images.githubusercontent.com/13665806/87534133-e86b6300-c695-11ea-8071-52369c665d9f.png)

**Comment by areksolek** [comment]
If you would like to add a translation to picklist value you should add a new value to proper file. Depending on place of translating you should add a new translation to _Base.json file - it will translate globaly new variable. Or if you would like to add new translate only in module area , then you should add a new translation in module translation file. For exaple if you would like add something new in Accounts in English you should edit this file \languages\en-US\Accounts.json.

Adding a translation can also be done from Software configuration / System tools / Language Management / Edit language
by selecting the appropriate language and module to be translated.

**Add new value:**
![AddPicklist](https://user-images.githubusercontent.com/25615135/91550585-0bda2c80-e929-11ea-8c4e-4d5c7faa242b.gif)
**Add filter:**
![AddFilter](https://user-images.githubusercontent.com/25615135/91550662-29a79180-e929-11ea-9065-01b65ddd8627.gif)

**Add widget:**
![AddWidget](https://user-images.githubusercontent.com/25615135/91550674-2d3b1880-e929-11ea-9425-9da4f3ce92a9.gif)
