### ISSUE TITLE
Products not available in Sales enquiries or other sales milestones

### ISSUE THREAD

**Issue by OrphLab** [YetiForceCompany/YetiForceCRM#13311]
Hi, 
I've added two products and two services to the system, all of them active, but they do not display when I'm trying to make a sales enquiries or quotes or calculations. 
I can add a product and service from the Sales enquiries tab, and those will appear in the product tab, but not the other way around. Any thoughts ?

**Comment by vovpff** [comment]
Active checkbox should be checked:

![image](https://user-images.githubusercontent.com/8545791/87539273-42742480-c6a6-11ea-9201-ca2d03b7ac9c.png)

**Comment by OrphLab** [comment]
![image](https://user-images.githubusercontent.com/15363459/87543082-5d459980-c6a4-11ea-9187-668900e67297.png)
They are - both the services and the products.

**Comment by OrphLab** [comment]
![image](https://user-images.githubusercontent.com/15363459/87543877-ca0d6380-c6a5-11ea-8b69-295544c36aef.png)

**Comment by vovpff** [comment]
Pls share configuration screenshot
