### ISSUE TITLE
Roundcube bag[bug] 

### ISSUE THREAD

**Issue by slomus** [YetiForceCompany/YetiForceCRM#13325]
Witam

Problem wygląda następująco posiadam Yetiforce na wersji 5.3. na którym nie działa prawidłowo roundcube 
![Przechwytywanie0](https://user-images.githubusercontent.com/67637171/88056490-ef481900-cb60-11ea-9bb9-06f7560d1f33.PNG)
Jak widac pokazują sie 2 ekrany logowania. Natomist podczas gdy zalaguje sie na swoje konto roundcube to wyskakuje bład graficzyn
![222](https://user-images.githubusercontent.com/67637171/88056725-4d74fc00-cb61-11ea-89da-3e4af31334a8.PNG)
i nie pokazują sie żadne maile 
logi błędu : 
2020/07/21 14:47:47 [error] 2433#0: *1964 FastCGI sent in stderr: "PHP message: PHP Warning:  filesize(): stat failed for /usr/share/nginx/html/yeti/storage/MultiImage$
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /usr/share/nginx/html/yeti/file.php:0
PHP message: PHP   2. App\Main\File->process() /usr/share/nginx/html/yeti/file.php:15
PHP message: PHP   3. MultiCompany_Logo_File->get() /usr/share/nginx/html/yeti/app/Main/File.php:42
PHP message: PHP   4. App\Fields\File->getSize() /usr/share/nginx/html/yeti/modules/MultiCompany/files/Logo.php:55
PHP message: PHP   5. filesize() /usr/share/nginx/html/yeti/app/Fields/File.php:244
PHP message: PHP Warning:  readfile(/usr/share/nginx/html/yeti/storage/MultiImage/MultiCompany/logo/2019/March/week1/7c59859ad238d3372b5f604a0100076595a62847vhHKax5T6H$
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /usr/share/nginx/html/yeti/file.php:0
PHP message: PHP   2. App\Main\File->process() /usr/share/nginx/html/yeti/file.php:15
PHP message: PHP   3. MultiCompany_Logo_File->get() /usr/share/nginx/html/yeti/app/Main/File.php:42
PHP message: PHP   4. readfile() /usr/share/nginx/html/yeti/modules/MultiCompany/files/Logo.php:56" while reading response header from upstream, client: 46.238.215.24,$

Zmiana nazwy pliku w katalogu /public_html/modules/OSSMail/ z roundcube na np; roundcube1 powodowała ze yeti dawał możliwość instalacji przez "MODÓŁY INSTALACJI" i tworzyły się wszystkie potrzebne pliki ale mimo to problem sie nie rozwiązywał bo cały czas był 2 ekrany logowania .

**Comment by rskrzypczak** [comment]
Przejrzyj to zgłoszenie: https://github.com/YetiForceCompany/YetiForceCRM/issues/12783
Prawdopodobnie postawiłeś serwer na CentOS i masz błędną konfigurację :)
Wyłącz rozszerzenie **uopz** oraz ustaw:

> request_order = GP 
> variables_order = GPCS 

Co powinno rozwiązać problem.
