### ISSUE TITLE
Tax on gross value

### ISSUE THREAD

**Issue by roberto722** [YetiForceCompany/YetiForceCRM#13328]
Hello,

there is the possibility to set a tax applied on the gross amount, instead of adding it on net amount?

**Comment by vdpawel** [comment]
As far as I know, this is not possible. 
The gross amount is not calculated until you enter the net amount.

It would be nice to extend the functionality of the system with this possibility.
![obraz](https://user-images.githubusercontent.com/62466142/88249500-f1b38b80-cca4-11ea-9ae6-44076f11cc52.png)

For example, if you enter the net amount first, the gross amount is calculated, and if you enter the gross amount first, the net amount is calculated.

**Comment by roberto722** [comment]
Yeah, it would be very useful, not all taxations apply on net amount

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/13254/files

I guess it won't be available in the new version, maybe later.
