### ISSUE TITLE
[Question] Changing the order of user and employee names in the interface

### ISSUE THREAD

**Issue by gkankstech** [YetiForceCompany/YetiForceCRM#13329]
All displays of user names and employee names seem to be displayed in last name first name order. I would like to change that. It becomes very confusing in places like widgets where it takes the last initial first so if your name is Bob Krampus the abbreviation is KB instead of BK. 

I'm guessing there's a simple setting to change this behavior I just did not see it.

**Comment by rskrzypczak** [comment]
I think that's what you are looking for.
![image](https://user-images.githubusercontent.com/10221999/88252719-84f1be80-ccaf-11ea-8bed-c2485e181113.png)
