### ISSUE TITLE
[bug] Calendar widget shows wrong starttime

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13326]
Hello,

I configured a litte widget to have a list of my tasks, appointments, etc. on my dashbord.
I discoverd now, that the starting time of every item is shown with 00:00, but when you mouseover the item the correct startingtime is shown.

![Screenshot_2020-07-20 Meine Startseite](https://user-images.githubusercontent.com/13665806/88067444-494fdb00-cb6f-11ea-8584-6fc923228798.png)

![MyCalendar](https://user-images.githubusercontent.com/13665806/88067336-26bdc200-cb6f-11ea-9bb3-565cc2a72af0.png)

Any ideas? Thanks!

**Comment by rskrzypczak** [comment]
Yes, this is a bug.
When it comes to calendar widgets, I recommend that you use the following ones, they are specially designed for the calendar.
![image](https://user-images.githubusercontent.com/10221999/88133468-6f629300-cbe2-11ea-81f4-4ed122039aac.png)
