### ISSUE TITLE
[Question] [PL] Problemy z CRON

### ISSUE THREAD

**Issue by utp-proj-sztuczna** [YetiForceCompany/YetiForceCRM#13331]
Po skonfigurowaniu CRON-a działał bez problemu przez około dwie godziny z interwałami co 5 min. Aktualnie nie chce się automatycznie uruchamiać, a po ręcznym odpaleniu nie chce się zatrzymać. 

![image](https://user-images.githubusercontent.com/66875302/88259536-c63f9980-ccc2-11ea-8f4f-afe3cdac72ad.png)
![image](https://user-images.githubusercontent.com/66875302/88259586-e66f5880-ccc2-11ea-82a8-ee2c4b98553e.png)

**Comment by mariuszkrzaczkowski** [comment]
włącz logi i zresetuj skaner

**Comment by utp-proj-sztuczna** [comment]
Reset przez Linuxa czy przez interfejs Yetiego i w jaki sposób?

**Comment by mariuszkrzaczkowski** [comment]
panel yeti

**Comment by utp-proj-sztuczna** [comment]
Chodzi o "Ręczne zatrzymanie skanowania" w Logi -> Maile - historia pobrań? Były próby takiego resetowania, ale niestety nie pomagały

**Comment by bpabiszczak** [comment]
Sam reset nie rozwiąże problemu, bo skoro na czymś się "zwiesił" to ponownie się "zwiesi", należy znaleźć przyczynę i problem rozwiązać. A do tego potrzeba programistę. Z tego co widzę, to cron przestał działać automatycznie i zacząłeś go puszczać ręcznie... a do tego uruchomiony został na użytkowniku admin_test a niestety nic oni nie wiemy [nawet to czy ma wszystkie uprawnienia].

Brak logów, więc nie bardzo mam jak pomóc. Jak przeanalizujesz logi i co ciekawsze wrzucisz tutaj, to ponownie otworzę zgłoszenie.
