### ISSUE TITLE
[Question] Migration from VTiger 7.x to YetiForce

### ISSUE THREAD

**Issue by DiReKToRje** [YetiForceCompany/YetiForceCRM#13332]
We are currently using VTiger 7.2 and would like to know what is the easiest way to migrate to the latest YetiForce.
I've been looking around a bit and can't seem to find anything about migration apart from it "being easy".
Is there any tool available, if not, what is the appropriate workflow to migrate and not miss anything?

Thank you in advance!
Regards,
S

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
the migration was built into one of the old versions of YetiForce but right now it would be too time-consuming to migrate to the latest version. 
If you send us an email at hello@yetiforce.com and provide information on how many modules you would like to migrate and how many records you have in each of them, we will estimate the price for preparing the migration script for you.
