### ISSUE TITLE
[CRON] [ERROR] [PL] Problem z Cronem reset nie pomaga

### ISSUE THREAD

**Issue by utp-proj-sztuczna** [YetiForceCompany/YetiForceCRM#13334]
1. Od jakiegoś czasu nie działa mi Cron, ustawiłam wszystko według konfuguracji na poniższym filmie, oraz resetowałam w panelu crona: 
https://www.youtube.com/watch?v=kTeRwM-b3Yg
2. Zgłoszenia nie dodają się automatycznie, przy dodawaniu ręcznym do zgłoszenia wyswietla się error związany z duplikacją klucza głownego zgłoszenia. 
3. Przed tymi problemami był ustawiony podwójny roundCube, który naprawilismy i jest teraz jeden działający

.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/12768
Być może masz dodane jakieś akcje obiegu informacji związane z aktualizacją pól.
Zobacz czy masz wgrany service pack: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.3.0
oraz wgraj tę poprawkę: https://github.com/YetiForceCompany/YetiForceCRM/commit/824b04fc2cbf60b2670b67cde28c06ca2df654fb
może to rozwiąże problem.

**Comment by slomus** [comment]
Witam 

Mam pytanie co do tego problemu czy te zmiany mam wprowadzić w pliku instalacyjnym czy w plikach które znajdują sie w yetim

**Comment by slomus** [comment]
I jak dokładnie dograc tą poprawkę

**Comment by bpabiszczak** [comment]
lepiej zleć to programiście.
