### ISSUE TITLE
[bug] Just noticed that older brother got load of mess

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#13330]
Funny is to see how those guys messing and crippling own users base. 
Blazej, drop some comment there to shrink their skin

**Comment by bpabiszczak** [comment]
?

**Comment by waran70** [comment]
https://code.vtiger.com/vtiger/vtigercrm/commit/cb17a1f4165ad458e0efd4ead79c37c1c296272b
