### ISSUE TITLE
Missing a temporary folder

### ISSUE THREAD

**Issue by matk34** [YetiForceCompany/YetiForceCRM#13333]
I am trying to import my Leads, Accounts, Contacts from CSV. When I click Next button I receive "Missing a temporary folder".
In debug console in Database tab I see: Base table or view not found: 1146 Table 'yetiforcedb.u_yf_import_6' doesn't exist

Can you help me please

**Comment by bpabiszczak** [comment]
What is your version of the system?
Have you migrated the system, if so, from what versions to what versions?
It is easiest if a developer checks it.
