### ISSUE TITLE
ETA for 5.4?

### ISSUE THREAD

**Issue by enoch85** [YetiForceCompany/YetiForceCRM#13335]
Simple question, when do you expect 5.4 to arrive?

I really need full PHP 7,4 support, like yesterday.

Thanks!

**Comment by enoch85** [comment]
ping @rskrzypczak and others. 

Thanks!

**Comment by rioshaz** [comment]
@rskrzypczak  any response dear ? we r waiting  maam...

**Comment by bpabiszczak** [comment]
soon

**Comment by enoch85** [comment]
> soon

Haha! "Soon" could be 5 minutes or 5 years. 🤷‍♂️

**Comment by rioshaz** [comment]
@bpabiszczak without a deadline one cant ever complete a task sir.. tentative date sir
