### ISSUE TITLE
[bug] contact import 

### ISSUE THREAD

**Issue by Zorgebi** [YetiForceCompany/YetiForceCRM#13345]
![yeti](https://user-images.githubusercontent.com/68855047/88552208-1cdf0780-d024-11ea-8e7f-069a4e62b057.png)

### hi there, i have issue importing contacts, it keep telling me error: The imported file is in a different encoding than it was selected (ASCII)
any solutions?

**Comment by vovpff** [comment]
Use notepad to change incoding of fike what you try to import.

**Comment by Zorgebi** [comment]
> Use notepad to change incoding of fike what you try to import.

i changed it to UTF-8 but it didnot work

**Comment by Zorgebi** [comment]
> Use notepad to change incoding of fike what you try to import.

heyy it worked with notepad, i changed it with excel but it didnot work, thank you

**Comment by vovpff** [comment]
No problem
