### ISSUE TITLE
QNAP Instalation

### ISSUE THREAD

**Issue by flipololi** [YetiForceCompany/YetiForceCRM#13346]
Dear

I have just downloaded the last version and I'd like to install it in a QNAP server. Is that possible?

**Comment by mariuszkrzaczkowski** [comment]
upload the installer, you will see
what version of PHP do you have?

**Comment by flipololi** [comment]
I current have 7.3.7
I have copied the files in the vtigercrm7 directory into my webserver and open de page : http://192.168.1.15/YetiForceCRM/install/Install.php

The messageI can show is 

192.168.1.15 no puede procesar esta solicitud en este momento.
HTTP ERROR 500

**Comment by flipololi** [comment]
I just install the last version into my windows 10 and I had the follow error:

Fatal error: Uncaught Exception: The intl library is missing in C:\Program Files\Ampps\www\YetiForce\include\RequirementsValidation.php:
15 Stack trace: #0 C:\Program Files\Ampps\www\YetiForce\install\Install.php(24): 
include_once() #1 {main} thrown in C:\Program Files\Ampps\www\YetiForce\include\RequirementsValidation.php on line 15

I Have :  Apache; Mysql and Php 7.3

**Comment by rskrzypczak** [comment]
> The intl library is missing..

Adjust the server configuration to the YetiForce application!
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron
