### ISSUE TITLE
Is there anyone who uses the crm YetiForce about Hotel? 

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#13352]
Oh hi there !!! 😄

i would like to know if there is someone who uses the YetiForce for hotel booking

i think i can do anything except booking. Is it right ?

Thank you !

**Comment by waran70** [comment]
you can do anything

**Comment by Giorgos-Hellene** [comment]
Could you give me more information?

is it possible with existed modules or it requires a new ?

Sure i need hotel (perhaps hotels) and rooms of this hotel. Each room has separate facilities

**Comment by waran70** [comment]
Look at thew Reservations module

**Comment by Giorgos-Hellene** [comment]
If YetiForce adds this feature then it can be implemented:

When we create or edit a date field we have the option BETWEEN. If we had the option NOT BETWEEN, then we can create the booking easily!

Please if it is possible add this function.
Thank you !

![εικόνα](https://user-images.githubusercontent.com/50912403/91689475-e2114780-eb6c-11ea-8feb-d020d6072706.png)

**Comment by vovpff** [comment]
@Giorgos-Hellene you can add this function by yourself

**Comment by Giorgos-Hellene** [comment]
> 
> 
> @Giorgos-Hellene you can add this function by yourself

wow ! this is wonderful !!

Could you tell me the way please?
how can i do it ?

**Comment by vovpff** [comment]
@Giorgos-Hellene php coding is solution! You can do a lot if you can php, mysql and js. If no - you can charge for developers.
