### ISSUE TITLE
Problemy z cronem

### ISSUE THREAD

**Issue by slomus** [YetiForceCompany/YetiForceCRM#13350]
Witam 

Mam małe problemy z cronem. Niestety nie wiem skąd one wynikają. 
Crona mam skonfigurowanego tak jak było napisane na stronie yetiego więc nie wiem skąd się bierze problem czy mógł by mi ktoś pomóc. Będe bardzo wdzięczny 
![cron](https://user-images.githubusercontent.com/67637171/88911166-bc3b0f00-d25d-11ea-83c2-5626c06b4396.PNG)

**Comment by mariuszkrzaczkowski** [comment]
możesz doprecyzować jakie problemy ??
po załączonym zrzucie nie widać błędów wszystko jest ok,

**Comment by rskrzypczak** [comment]
Ok, tylko gdzie tu problem?

**Comment by slomus** [comment]
Witam

Chodzi o to ze cron nie wiem nawet jak by to określic ma ze soba tak to nazwijmy "problem" i nie działa systematycznie 
![cron1](https://user-images.githubusercontent.com/67637171/88912618-cf4ede80-d25f-11ea-9c89-60ad2078f58b.PNG)

**Comment by slomus** [comment]
jest ustawiony i jak mówicie nie widać w nim żadnego problemu a mimo to jego działanie sie zawiesza i to dobrze widac bo wcześnij działął cyklicznie co 5 min a teraz ma jakis dziwny problem ze sobą i nie wiem dokońca skąd to wynika

**Comment by mariuszkrzaczkowski** [comment]
sprawdź logi

**Comment by slomus** [comment]
![cron2](https://user-images.githubusercontent.com/67637171/88913255-d9bda800-d260-11ea-876e-88bdadd5e56f.PNG)
nie wiem czy to bedzie dokładnie to ale chyba tak

**Comment by mariuszkrzaczkowski** [comment]
Proszę się zapoznać z opisem jak się zgłasza błędy i co jest wymagane do ich rozwiązania.
![github](https://user-images.githubusercontent.com/10198654/88913571-76804580-d261-11ea-8ac1-8d9ad62ee262.jpg)
