### ISSUE TITLE
[bug] Password is too short in Database > Password

### ISSUE THREAD

**Issue by saosangmo** [YetiForceCompany/YetiForceCRM#13357]
### ⁉️ Describe the bug

When input the password in Database zone. I can not input the password with 8 characters or less.

### 🔥 How to trigger the error

1. Go to 'Database'
2. Click on 'Password' -> 'Add new'
3. At the 'Password' field, fill: adds123
4. Press 'Save' button
=> The system warns 'Password is too short' and you will can not save the password.

### 👍 Expected Behavior
Do not check password rule at this screen.

### 👷 Testing
I see no function Passwords in 2 versions:
- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com
<img width="1209" alt="Screen Shot 2020-08-04 at 11 05 14" src="https://user-images.githubusercontent.com/4606931/89252253-6c848b00-d643-11ea-8a48-449649c07ed8.png">

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=OSSPasswords&view=ConfigurePass&parent=Settings
![image](https://user-images.githubusercontent.com/10198654/89258448-7fd62d00-d628-11ea-93ed-5089694929b1.png)
