### ISSUE TITLE
Integrate electronic signature and Customer replay for quotation 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#13356]
1. Integrate electronic signature
Can we integrate electronic signature in yetiforce CRM? if it is possible please tell us how can we do it in yetiforce CRM?.

2. Accept/Reject quotation
 I want to get a replay from customer by using accept/Reject button after we are sending the quote to customer, how can achieve this functionality in Yetiforce CRM.

**Comment by z0lo13** [comment]
Hello Guide5232,

1. Integrate existing Esign provider such as Doccusign or something else, create your own front end app, or expand customer portal functions.
2. Yetiforce using RestApi, you need to send a request over the API to change the status of a quotation record, search RestApi  on repo for examples.

Both requests will need a developer, it could be rather from Yeti team or any other developer who is familiar with PHP and JS
