### ISSUE TITLE
[bug] Installation - Fatal error

### ISSUE THREAD

**Issue by bagolybence** [YetiForceCompany/YetiForceCRM#13368]
After copying the YetiForce folder to my web storage and creating MySQL database I tried to install YetiForce but I got error message: 

Fatal error: Uncaught Exception: The mysqlnd library is missing in /web/tepenzed/yetiforce/include/RequirementsValidation.php:15 Stack trace: #0 /web/tepenzed/yetiforce/install/Install.php(24): include_once() #1 {main} thrown in /web/tepenzed/yetiforce/include/RequirementsValidation.php on line 15

What can be wrong?

**Comment by rskrzypczak** [comment]
>What can be wrong?

The mysqlnd library is missing :)
This is not a bug. Check system requirements before reporting a bug.
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

**Comment by fatmazayedsayed** [comment]
for me open php.ini
then update the last part it to be (remove some ;)



extension=bz2
extension=curl
;extension=ffi
;extension=ftp
extension=fileinfo
extension=gd
extension=gettext
extension=gmp
extension=intl
extension=imap
extension=ldap
extension=mbstring
extension=exif      ; Must be after mbstring as it depends on it
extension=mysqli
;extension=oci8_12c  ; Use with Oracle Database 12c Instant Client
;extension=oci8_19  ; Use with Oracle Database 19 Instant Client
extension=odbc
;extension=openssl
;extension=pdo_firebird
extension=pdo_mysql
;extension=pdo_oci
;extension=pdo_odbc
;extension=pdo_pgsql
extension=pdo_sqlite
;extension=pgsql
;extension=shmop
