### ISSUE TITLE
How to set http proxy to enable the system to access the internet [Question] 

### ISSUE THREAD

**Issue by tekkisse** [YetiForceCompany/YetiForceCRM#13362]
### Description

We need to install the CRM behind a corperate firewall and ALL outbound internet traffic must go thorugh a proxy server (Squid).   Is it possible or where is it possible to set the proxy setting so that the application is aware of these and will use them to connect out to the internet.
Thanks
Simon

**Comment by mariuszkrzaczkowski** [comment]
It is possible, but for now only on the development version.
https://github.com/YetiForceCompany/YetiForceCRM/blob/c4a90897e7468964143b6ec6da69f37036758458/config/Security.php#L162-L178

**Comment by Oxymoron290** [comment]
I was able to resolve my issue by simply changing `$forceUrlRedirection` to `false` in `YetiForceCRM/config/Security.php`. I was trying to set up an apache reverse proxy.
