### ISSUE TITLE
Object of class Vtiger_MappedFields_Model could not be converted to string

### ISSUE THREAD

**Issue by te-deum** [YetiForceCompany/YetiForceCRM#13369]
Hello,

I have a problem on an installation of YetiForce. When I create an account, I can't access to the Detail view. I have an empty page an the server report this error :
_[fcgid:warn] [pid 11966] [client 192.2.2.54:11476] mod_fcgid: stderr: PHP Recoverable fatal error:  Object of class Vtiger_MappedFields_Model could not be converted to string in /home/crm/public_html/modules/Vtiger/models/MappedFields.php on line 87_

 - **YetiForce :** 5.3 update 4
 - **Web server :** Apache 2.4.6
 - **PHP :** 7.2.33
 - **Browser :** Firefox 79.0
 - **OS :** CentOS 7 ( Linux crm 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 )
 - **Database :** MySQL MariaDb 10.2.32

Thank you for your help.

**Comment by rskrzypczak** [comment]
Show us the application logs (https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-programistyczna/item/debugging)
and your server configuration.
