### ISSUE TITLE
[bug] date in crone.php

### ISSUE THREAD

**Issue by Quiver92** [YetiForceCompany/YetiForceCRM#13363]
Hi! 
I have a problem with cron file
![image](https://user-images.githubusercontent.com/13777007/89299015-65bb3f80-d666-11ea-9c97-3863188f0544.png)
When I run crone.php file it shows me run time an hour earlier than it is now

**Comment by rskrzypczak** [comment]
Check the time zone set in CRM
.. and this is not a bug :)
