### ISSUE TITLE
[bug] Yetiforce.shop down

### ISSUE THREAD

**Issue by nebula2** [YetiForceCompany/YetiForceCRM#13365]
# 🐞 bug report
yetiforce.shop seems to be down. When I click on the button in the settings menu the page does not load.

I checked the address on "downforeveryoneorjustme"

https://downforeveryoneorjustme.com/yetiforce.shop?proto=https

![image](https://user-images.githubusercontent.com/5841525/89341636-dfbcea00-d6a1-11ea-858e-277a33e63312.png)

### ⁉️ Describe the bug

I am running Version 5.3.0

### 🔥 How to trigger the error
Click this button:
![image](https://user-images.githubusercontent.com/5841525/89341775-1c88e100-d6a2-11ea-8846-e19111bca431.png)

### 👎 Actual Behavior

Page does not load

### 👍 Expected Behavior

Page loads

**Comment by ghost** [comment]
is this issue wrong here or does nobody seem to care?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13279#issuecomment-656033641

**Comment by nebula2** [comment]
> [#13279 (comment)](https://github.com/YetiForceCompany/YetiForceCRM/issues/13279#issuecomment-656033641)
@mariuszkrzaczkowski thank you for pointing me in the right direction. A redirect would have been good but that's enough info for me.
