### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#13367]
I need a few short codes for invoice...
$(translate : Other.PDF|LBL_TO_PAY)$           |       **Gross = **sum_gross**
$(custom : TableDiscountSummary)$              |       **Discount = _________________ ?**    
$(custom : TableTaxSummary)$                      |      **Tax = ____________________ ?**

I use the gross short code on invoice which works... but I can not figure out what the **discount** and the **tax** short codes are. please help. Thank you.

**Comment by vovpff** [comment]
Gross and total this is basic fields what calculated every time when you chande something in table with products/services list.
Tax and discount - the part of products/services table and can't be called directly by short code without programming...

**Comment by hobejeans** [comment]
On the invoice, I would like to show only the tax amount and discount amount. I would like to hide the table. I do not want them to be shown in the current table with the title on top. How can I show only the currency value on the invoice form?

**Comment by bpabiszczak** [comment]
You need a developer.
