### ISSUE TITLE
Typo in german translation of FL_SALE_DATE

### ISSUE THREAD

**Issue by AndreasMuench** [YetiForceCompany/YetiForceCRM#13361]
#12638 🐞 bug report

### ⁉️ Describe the bug

There is a typo in the german translation of the token "FL_SALE_DATE" in the file languages/de-DE/FInvoiceProforma.json
    "FL_SALE_DATE": "Verkausdatum"  (missing f), the correct translation should be "FL_SALE_DATE": "Verkaufsdatum". 

### 🔥 How to trigger the error

1. Login in to Yetforce using 'Deutsch' as language
2. Go to Rehnungswesen ==> Proforma Rechnungen 
3. Click on 
![grafik](https://user-images.githubusercontent.com/48329233/89287129-a78eba80-d653-11ea-8fa9-3c9ee8f1e538.png)
in front of a proforma invoice and select the detail view
5. See incorrect translation

### 👎 Actual Behavior

![grafik](https://user-images.githubusercontent.com/48329233/89286716-fdaf2e00-d652-11ea-9293-86c0463960f0.png)

### 👍 Expected Behavior

correct translation of "FL_SALE_DATE" (Verkaufsdatum)
### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |  5.3.0
| Web server (name and version)       | Apache               |
| PHP                                 |     7.3.20            |
| Browser (name and version)          |        Firefox 68.1.0esr         |
| Operating System (name and version) |     CentOS 7           |
| Database (name and version)         |   mysql  5.7.31              |
| Service Pack version                |     Service Pack v4           |

**Comment by rskrzypczak** [comment]
Thanks, but please report translation problems to [Crowdin](https://crowdin.com/project/yetiforcecrm).
Fixed in: [crowdin.com](https://crowdin.com/translate/yetiforcecrm/all/en-de#q=FL_SALE_DATE)

**Comment by AndreasMuench** [comment]
In future I will report translation problens to https://crowdin.com/project/yetiforcecrm
