### ISSUE TITLE
Email Temlate

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#13360]
What am I doing wrong so that the data is not transferred automatically to the Email? I tested on [ver. 5.3.141] https://gitdeveloper.yetiforce.com/ and on mine
YF 5.3. 4. I have already tried everything, but unfortunately the data is not filled in.
![Email Template](https://user-images.githubusercontent.com/25682437/89274881-d0a64f80-d641-11ea-9ab5-3b1752947a7c.gif)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/12982
