### ISSUE TITLE
Access failed

### ISSUE THREAD

**Issue by OrphLab** [YetiForceCompany/YetiForceCRM#13378]
Suddenly the CRM does not recognize my password.
All is matching up in the database. 
User is not blocked nor is the ip

Is there anything I can see why it is being rejected?

login_id | user_name | user_ip | logout_time | login_time  1 | status | browser | userid | agent |  

| 57 | usrname| IP| NULL | 2020-08-11 00:17:28 | Failed login | Google Chrome 84 | NULL | NULL

-changing password through the database, doesn't work either.

**Comment by vovpff** [comment]
check bruteforce blocking in this table:

```
SELECT * FROM `a_yf_bruteforce_blocked`
```

>-changing password through the database, doesn't work either.

Password should be generated and encrypted by system.

[Check this!](https://github.com/YetiForceCompany/YetiForceScripts/tree/master/PasswordReset)

**Comment by OrphLab** [comment]
> check bruteforce blocking in this table:
> 
> ```
> SELECT * FROM `a_yf_bruteforce_blocked`
> ```
> 
> > -changing password through the database, doesn't work either.
> 
> Password should be generated and encrypted by system.
> 
> [Check this!](https://github.com/YetiForceCompany/YetiForceScripts/tree/master/PasswordReset)

my IP is not on the list in a_yf_bruteforce_blocked

the PasswordReset.php file did change the password, but the system still gives me an invalid username or password response.

**Comment by vovpff** [comment]
What about other users?

**Comment by OrphLab** [comment]
> What about other users?

I only have that one user.

**Comment by OrphLab** [comment]
Can I provide any log, that could be useful to solve this?
Also, is there a way I can add an additional user, just to see if its the user or the system?

**Comment by OrphLab** [comment]
Alright. Thank you. I think we tested this system enough and will move on to something else.

**Comment by waran70** [comment]
check capslock
