### ISSUE TITLE
[Question] Cron Jobs on Ubuntu Server 18.04 LTS

### ISSUE THREAD

**Issue by Cratos84** [YetiForceCompany/YetiForceCRM#13372]
Hi to all,

as we are new in Yetiforce we have installed this great CRM on a Self Hosted Ubuntu Server 18.04 LTS with Apache.

Everything at the moment is working well except of the Cron Mecahnism. 

We have followed this instructions here : https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

but they are not really helpfull. The Cron mechanism is not working.

Maybe someone could please give us the correct paths and commands to get yetiforce crm cron jobs running on a local Ubuntu 18.04 Server? the path of yetiforce at our server is the standard one on /var/www/yetiforce/ 

Thank you in advanced for your help!

**Comment by mariuszkrzaczkowski** [comment]
log show and check out https://github.com/YetiForceCompany/YetiForceCRM/issues?q=is%3Aissue+cron+is%3Aclosed
