### ISSUE TITLE
Adding an additional table

### ISSUE THREAD

**Issue by jacohelm** [YetiForceCompany/YetiForceCRM#13373]
Hi all

I hope someone can help me. Is there a way to add an extra DB table to YetiForce. To give a brief explenation, I basically want to add a "site" table, which can be linked to Companies and Contacts. For instance, Company A, will have SiteA, SiteB, SiteC. Each with a different contact. For the sites I would also like a multiple selectable and editable fields which must hold info such as Owner (Linked to a company) and Operator (Also linked to a company), and so forth. 

I hope it is possible and someone can just give me a rough idea of how to do it. I only started playing with YetiForce today, but it seems brilliant so far.

Thanks in advance.

**Comment by z0lo13** [comment]
@jacohelm 
Create a Module.
Settings->Standard Modules->Modules - Installation->Create a Module

**Comment by jacohelm** [comment]
@z0lo13 Thanks a bunch. Gonna go play around with it now.
