### ISSUE TITLE
[Question] [PL] Dynamiczne przełączanie między kontami pocztowymi

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#13371]
Witam,

Mam pytanie odnośnie użytkowania wielu kont pocztowych jednocześnie. Mam je w dropdown liście na nagłówku strony ale żeby przechodzić między kontami (pomimo ustawienia autologowania) muszę się najpierw wylogować z jednej skrzynki w roundcubie, potem wybrać z podpowiadanych login i hasło i dopiero wejść na skrzynkę. W innym wypadku niezależnie od wybranego konta widzę tą samą zawartość skrzynki. Nie przełącza mnie między nimi dynamicznie.

Czy da się tak ustawić by dynamicznie przełączał użytkownika między kontami?

**Comment by rskrzypczak** [comment]
Wersja CRM?

Być może jakiś z dodatków zainstalowanych w przeglądarce powoduje takie zjawisko.

**Comment by mrzewnicki** [comment]
Wersja 4.4, ale faktycznie dodatek w przeglądarce był winowajcą. Dzięki!!
