### ISSUE TITLE
Configuration editor. Data don't saved

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1337]
In settings -> other settins -> configuration editor. After saved data  get the message "Configuration Details Saved"  but the table is still empty. I
![Error](https://cloud.githubusercontent.com/assets/3193498/8499278/74a9b768-2191-11e5-8d1c-c99f38476e17.png)

**Comment by rskrzypczak** [comment]
This error could not be reproduced in newest version of YetiForce.

**Comment by waw555** [comment]
You can not set the Maximum Upload Size (Max 5MB) more than 5 Mb, although the setting is worth more php
