### ISSUE TITLE
Zaciąganie danych adresowych kontrahenta do FV przestało działać

### ISSUE THREAD

**Issue by Ola-St** [YetiForceCompany/YetiForceCRM#13383]
Pomocy! 
Przestał działać guzik, który wciąga dane adresowe Kontrahenta do faktury.
Dodatkowo, jeśli uzupełniamy je ręcznie, to nie generuje się nr lokalu do PDF, nawet jeśli dodamy go w to samo pole co nr budynku, na przykład po ukośniku, nadal generuje się jedynie nr budynku.
Prawdopodobnie ktoś przez przypadek coś wyłączył podczas edycji jako administrator, a teraz nie jesteśmy w stanie odnaleźć przyczyny i jej naprawić.

Z góry dzięki za pomoc :)

**Comment by bpabiszczak** [comment]
Najlepiej spytać tego który popsuł co zrobił ;)
Brak logów, brak informacji o konfiguracji... nie wiem jak mamy pomóc.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/90016463-4f3a6700-dcaa-11ea-964c-a7e2ed4bebd7.jpg)

**Comment by Ola-St** [comment]
![yetiforce_settings](https://user-images.githubusercontent.com/69586047/90016551-73964380-dcaa-11ea-8346-56469f34a417.png)
Przepraszam, kompletnie nie ogarniamy tematu. Zostaliśmy z tematem sami (laicy) i łapiemy się ostatniej deski ratunku.

**Comment by mariuszkrzaczkowski** [comment]
najpierw trzeba poprawić konfigurację serwera, 
masz PHP 7.4 na WWW i 7.1 dla CLI a nie mogą być różne
masz starą wersje 4.4.0 która na pewno nie działa na PHP 7.4 
zalecamy aktualizację, masz jakiś problem możesz skorzystać z naszego wsparcia 
https://yetiforce.com/pl/marketplace/wsparcie-development
