### ISSUE TITLE
ossmail [bug] 

### ISSUE THREAD

**Issue by SplashMediaLabs** [YetiForceCompany/YetiForceCRM#13387]
I have the next error

Internal Server Error
Directory "/home/tiendasa/domains/centrofr.com/public_html/clientes/public_html/modules/OSSMail" is writeable by group

suPHP 0.7.2

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/90234316-c6453c00-de1f-11ea-87e4-88780fd919e1.jpg)
