### ISSUE TITLE
[Question] is there a way to have a table with sum without a graph?

### ISSUE THREAD

**Issue by BraulioBracamonte** [YetiForceCompany/YetiForceCRM#13382]
### Description

Hi, for simplicity pourposes: I have a custom module with 3 fields ShotNumber, Shooter and Accuracy.
I can have a widget that shows how many good, med, and bad shots did each Shooter, but it creates a graph for each Shooter or Accuracy.
![image](https://user-images.githubusercontent.com/35633915/89930425-5b51f600-dbd0-11ea-81f8-6bc3f822799b.png)
This could be ok for small sets, but how about having 30 shooters and accuracy levels from 1 to 10 ?
then, is there a way to get the result in a widget or table like:
![image](https://user-images.githubusercontent.com/35633915/89930919-167a8f00-dbd1-11ea-8620-a60a4aaf35cc.png)
?

**Comment by bpabiszczak** [comment]
This has to be added by the developer.
https://yetiforce.com/en/marketplace/development-support
