### ISSUE TITLE
[Question] Yetiforce 5.3 how to change Payment status sales invoice

### ISSUE THREAD

**Issue by rkartal** [YetiForceCompany/YetiForceCRM#13385]
Hi, i am using 5.3 version. I am entering the payment on the bill, but the status has not been paid. how will I do

**Comment by vovpff** [comment]
Pls search for this on closed issues.

**Comment by rioshaz** [comment]
@rkartal you need to make a "payment-in" record against that invoice and it shall update the status accordingly..
