### ISSUE TITLE
[bug] [PL] [bug] [PL] Przy wskazywaniu zapytania ofertowego z maila widać tylko 2 kolumny (Temat, Właściciel rekordu) 

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#13397]
# 🐞 bug report

### ⁉️ Describe the bug

W nawiązaniu do #13395, bardzo dziękuję za szybką odpowiedź, jednak problem wydaje się inny, ponieważ na przykładzie modułu zamówień wyświetlanie działa poprawnie, a:
1. Plik YetiForceCRM/modules/SQuoteEnquiries/SQuoteEnquiries.php jest taki jak w zamówieniach (SSingleOrders.php - różnią się nazwy pól)
2. W zapytaniach ofertowych widok pól referencyjnych z innego modułu również działa poprawnie - pojawiają się różne kolumny zgodnie z filtrem domyślnym w module zapytań ofertowych:
![obraz](https://user-images.githubusercontent.com/62466142/90503054-1ccbb680-e14f-11ea-84c4-8c5917be6c8d.png)
3. uzupełnienie listy w pliku o dodatkowe pole (oraz innych pól w tym pliku) nic nie zmienia, np.:
	public $list_fields = [
		// Format: Field Label => Array(tablename, columnname)
		// tablename should not have prefix 'vtiger_'
		**'Numer' => ['squoteenquiries', 'squoteenquiries_no'],**
		'LBL_SUBJECT' => ['squoteenquiries', 'subject'],
		'Assigned To' => ['crmentity', 'smownerid'],
	];

### 🔥 How to trigger the error

Zgodnie z #13395
**Problem występuje tylko w okienku pojawiającym się z poziomu poczty. W innych odniesieniach referencyjnych problem nie występuje**

### 👎 Actual Behavior

Zgodnie z #13395

### 👍 Expected Behavior

Zgodnie z #13395

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com - **działa poprawnie**

### 📷 Screenshot of configuration

Zgodnie z #13395

### 🌍 Your Environment

YetiForce CRM 5.3 Service Pack v4

**Comment by rskrzypczak** [comment]
`search_fields_name` 
Wgraj to: https://github.com/YetiForceCompany/YetiForceCRM/commit/ae852816707a8a2140ee9c64cc4dd688d1c37f27

**Comment by vdpawel** [comment]
Działa - jakie to piękne! 
(Już poprzednim zgłoszeniu widziałem tą modyfikacje, ale nie spodziewałem się, że ma wpływ)

**Ślicznie dziękuję za pomoc!!!!**
