### ISSUE TITLE
[bug] [PL] Przy wskazywaniu zapytania ofertowego z maila widać tylko 2 kolumny (Temat, Właściciel rekordu)

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#13395]
# 🐞 bug report

### ⁉️ Describe the bug

Przy wskazywaniu zapytania ofertowego z maila widać tylko 2 kolumny (Temat, Właściciel rekordu)
**Czy ten problem występował wcześniej i został rozwiązany, czy występuje tylko u mnie? :)**
W wersji developerskiej działa poprawnie.

Dziękuję za pomoc lub jakiekolwiek sugestie naprowadzające na przyczynę błędu.

### 🔥 How to trigger the error

1. Z poziomu poczty, trzeba wybrać maila
2. Wskazać: Zapytanie ofertowe
3. Wybrać lupę - "Powiąż z istniejącym rekordem"
![obraz](https://user-images.githubusercontent.com/62466142/90481631-64901500-e132-11ea-97ec-92b1de38e494.png)

### 👎 Actual Behavior

4. Ukazuje się okno wyboru istniejących rekordów, zawierające tylko dwie kolumny: Temat i właściciel rekordu.
![obraz](https://user-images.githubusercontent.com/62466142/90481682-75d92180-e132-11ea-8145-39bccf5ed00c.png)

### 👍 Expected Behavior

5. Powinny sie pojawić kolumny z domyślnego filtra, np.:
![obraz](https://user-images.githubusercontent.com/62466142/90482134-129bbf00-e133-11ea-8e18-faac5c3cb825.png)

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com - **działa poprawnie**

### 📷 Screenshot of configuration

![ConfReport(1)](https://user-images.githubusercontent.com/62466142/90482883-2f84c200-e134-11ea-9f35-3e0763e2dca2.png)

### 🌍 Your Environment

YetiForce CRM 5.3 Service Pack v4

**Comment by bpabiszczak** [comment]
To nie jest błąd, tylko tak jest domyślnie w pliku konfiguracyjnym w tym module.

**Comment by bpabiszczak** [comment]
Spróbuj uzupełnić tą tablicę u siebie w systemie: 	https://github.com/YetiForceCompany/YetiForceCRM/blob/b607a56719d12f4119689b9a73b00677a11a7979/modules/SQuoteEnquiries/SQuoteEnquiries.php#L36
