### ISSUE TITLE
[Question] Edit field (related fireld 1:M) use  custom modules

### ISSUE THREAD

**Issue by ceoshop** [YetiForceCompany/YetiForceCRM#13402]
Edit field (related fireld 1:M)
use  Select module --> select custom modules
how can show all modules fireld

![image](https://user-images.githubusercontent.com/69898595/90621089-dc029900-e245-11ea-88fc-4f6c1f634ddd.png)

only one fireld

![image](https://user-images.githubusercontent.com/69898595/90621201-fb012b00-e245-11ea-8e5c-f71557760197.png)

**Comment by vdpawel** [comment]
Try to set the fields to be displayed in the default filter of a given module.

**Comment by ceoshop** [comment]
> Try to set the fields to be displayed in the default filter of a given module.

how to set the fields to be displayed in the default filter of a given module.

**Comment by apcloic** [comment]
@ceoshop 
#7160

**Comment by rskrzypczak** [comment]
and set this: https://github.com/YetiForceCompany/YetiForceCRM/commit/ae852816707a8a2140ee9c64cc4dd688d1c37f27

**Comment by ceoshop** [comment]
Thank You All .!
