### ISSUE TITLE
[Question] Can't select/assign Account when trying to create a Sales Order

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13401]
Hello,

I want to create Sales Orders manually (later the data will be imported from another system) and assign it to a Account (Organization **OR Contact without Organization**).
I think it is a missing understanding how _Sales Orders_ are created, because I saw now that I **can't even select Account** when creating a new _Quote_ or _Sales inquiry_.

How do I assign a Sales Order to an existing Account?

![Screenshot_2020-08-19 Sales enquiries Create](https://user-images.githubusercontent.com/13665806/90620098-54e7fd80-e212-11ea-8479-873c9092a60c.png)

**Comment by vovpff** [comment]
@blu-IT from the box you need to select Opportunity first. Account will be hooked from Opportunity.

To fix this you need to change Field Type

![image](https://user-images.githubusercontent.com/8545791/90621473-7221c980-e21c-11ea-8b9b-d687bf629322.png)

and you need to modify https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app_data/moduleHierarchy.php to avoid replacing Account if Opportunity changed

**Comment by blu-IT** [comment]
@vovpff Thanks! 

When I try to edit this field there is no entry for field type:

![Screenshot_2020-08-20 Layout-Editor System Einstellungen](https://user-images.githubusercontent.com/13665806/90810567-797fca80-e323-11ea-8e19-2068ef332196.png)

and what exactly do I need to change in 

https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app_data/moduleHierarchy.php ?

**Comment by vovpff** [comment]
@blu-IT 

change here `/config/Developer.php` false to true

```
        /** Change of fields visibility */
        public static $CHANGE_VISIBILITY = true;
```

I don't remember how to modify `moduleHierarchy.php` file. Let's play with them.

**Comment by blu-IT** [comment]
> 
> 
> @blu-IT
> 
> change here `/config/Developer.php` false to true
> 
> ```
>         /** Change of fields visibility */
>         public static $CHANGE_VISIBILITY = true;
> ```

OK, changed first part now and "Field type" to always visible and now I am able to set Account/Organization.

> I don't remember how to modify `moduleHierarchy.php` file. Let's play with them.

Sorry, I did not understand what the changes in `moduleHierarchy.php` file are for?

**Comment by vovpff** [comment]
@blu-IT 
```
		'SSingleOrders' => [
			'accountid' => ['Accounts' => ['company' => ['accountname']]],
// Next line automatically replace Account if Opportunity reselected (hooks Account ID from Opportunity)
			'salesprocessid' => ['SSalesProcesses' => ['accountid' => ['related_to']]],
// Next line automatically replace Account if Quote reselected (hooks Account ID from Quote)
			'squotesid' => ['SQuotes' => ['accountid' => ['accountid']]]
// You can comment lines to avoid automatic Account replacement
		],
```
