### ISSUE TITLE
[Question] [PL] Po aktualizacji do 5.3 problem z akcjami wiadomości email

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#13405]
Witam,

Po pomyślnym zaktualizowaniu do wersji 5.3 mam problem z akcjami powiązania wiadomości email z modułami: email, zgłoszenia, kontakty oraz z tworzeniem tych rekordów z maili.

Po pierwsze za każdym razem muszę importować maila ręcznie:
![image](https://user-images.githubusercontent.com/21024857/90729589-1d875880-e2c7-11ea-8b9d-4e2f201bc5ea.png)

Po drugie nie wąże się on z żadnym istniejącym rekordme lub tez nie tworzy sie nowy:
![image](https://user-images.githubusercontent.com/21024857/90729644-309a2880-e2c7-11ea-96e0-80540df15352.png)

Jeśli wyszukam Ticket ręcznie, powiązanie tworzy się poprawnie. 

Czy dodaliście w najnowszje aktualizacji plugin filtrów? Bo pojawiały mi się błędy że nie może go dołączyć.

**Comment by mrzewnicki** [comment]
Widzę ze w bazie pole searchlabel to jest varchar(255) .. czy jest możliwość zwiększenia tego w następnych aktualizacjach? Nawet jak sobie to zmienie lokalnie załóżmy to aktualizacja pewnie i tak nadpisze te ustawienia.

2020-08-20 09:35:05.9711 [error][MailScanner] - PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'searchlabel' at row 1 in /var/www/html/YetiForce/vendor/yetiforce/yii2/db/Command.php:1290
Stack trace:
#0 /var/www/html/YetiForce/vendor/yetiforce/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /var/www/html/YetiForce/vendor/yetiforce/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `u_...')
#2 /var/www/html/YetiForce/app/Record.php(251): yii\db\Command->execute()
#3 /var/www/html/YetiForce/modules/Vtiger/handlers/RecordLabelUpdater.php(19): App\Record::updateLabelOnSave(Object(OSSMailView_Record_Model))
#4 /var/www/html/YetiForce/app/EventHandler.php(323): Vtiger_RecordLabelUpdater_Handler->entityAfterSave(Object(App\EventHandler))
#5 /var/www/html/YetiForce/modules/Vtiger/models/Record.php(503): App\EventHandler->trigger('EntityAfterSave')
#6 /var/www/html/YetiForce/modules/OSSMailScanner/scanneractions/CreatedEmail.php(64): Vtiger_Record_Model->save()
#7 /var/www/html/YetiForce/modules/OSSMailScanner/models/Record.php(300): OSSMailScanner_CreatedEmail_ScannerAction->process(Object(OSSMail_Mail_Model))
#8 /var/www/html/YetiForce/modules/OSSMail/views/MailActionBar.php(40): OSSMailScanner_Record_Model::executeActions(Array, Object(OSSMail_Mail_Model), 'INBOX', NULL)
#9 /var/www/html/YetiForce/include/main/WebUI.php(187): OSSMail_MailActionBar_View->process(Object(App\Request))
#10 /var/www/html/YetiForce/index.php(28): Vtiger_WebUI->process(Object(App\Request))
#11 {main}

Next yii\db\Exception: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'searchlabel' at row 1
The SQL being executed was: INSERT INTO `u_yf_crmentity_search_label` (`crmid`, `searchlabel`, `setype`) VALUES (367196, 'M_110918  sbe@sbe-online.pl Re: [H18935] Re: zapytanie   &lt;div class=&quot;js-iframe-content&quot; &gt;Złozyłam ZZ czekam na odpowiedz. Odezwę się tylko jak dostanę odpowiedź.PozdrawiamKarolina GlińskaSt. Specjalista Sprzedaży i UsługSklep Mediaexpertul. Mickiewic', 'OSSMailView') in /var/www/html/YetiForce/vendor/yetiforce/yii2/db/Schema.php:674
Stack trace:
#0 /var/www/html/YetiForce/vendor/yetiforce/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `u_...')
#1 /var/www/html/YetiForce/vendor/yetiforce/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `u_...')
#2 /var/www/html/YetiForce/app/Record.php(251): yii\db\Command->execute()
#3 /var/www/html/YetiForce/modules/Vtiger/handlers/RecordLabelUpdater.php(19): App\Record::updateLabelOnSave(Object(OSSMailView_Record_Model))
#4 /var/www/html/YetiForce/app/EventHandler.php(323): Vtiger_RecordLabelUpdater_Handler->entityAfterSave(Object(App\EventHandler))
#5 /var/www/html/YetiForce/modules/Vtiger/models/Record.php(503): App\EventHandler->trigger('EntityAfterSave')
#6 /var/www/html/YetiForce/modules/OSSMailScanner/scanneractions/CreatedEmail.php(64): Vtiger_Record_Model->save()
#7 /var/www/html/YetiForce/modules/OSSMailScanner/models/Record.php(300): OSSMailScanner_CreatedEmail_ScannerAction->process(Object(OSSMail_Mail_Model))
#8 /var/www/html/YetiForce/modules/OSSMail/views/MailActionBar.php(40): OSSMailScanner_Record_Model::executeActions(Array, Object(OSSMail_Mail_Model), 'INBOX', NULL)
#9 /var/www/html/YetiForce/include/main/WebUI.php(187): OSSMail_MailActionBar_View->process(Object(App\Request))
#10 /var/www/html/YetiForce/index.php(28): Vtiger_WebUI->process(Object(App\Request))

**Comment by mrzewnicki** [comment]
usunałem większość pól z konfiguracji wyszukiwania żeby narazie tworzyły się ticety, ale w ten sposób nie można wyszukiwać po treści wiadomości. Czy można jakoś zwiększyć wielkość tego pola?

Jeśli ticket jest zamknięty a dzwoni klient to warto móc go szybko wyszukać a nie zawsze pamięta on np numer zgłoszenia. Ewentualnie rozpoczyna nową korespondencję w sprawię starego zamkniętego zgłoszenia.

**Comment by bpabiszczak** [comment]
Nie bardzo wiem jak pomóc... bo poruszasz kilka problemów.

1. Bez logów i testów na naszych środowiskach ciężko jest pomóc. Wygląda jakby nie był prawidłowo skonfigurowany skaner poczty [brak akcji tworzenia maila dla przykładu] lub brakuje czegoś w konfiguracji. 
2. Możesz wszystko zwiększyć, to open source. Tylko trzeba wiedzieć jak :) Można też wysłać do nas PR o ile jest OK. 
3. Ja bym do pola wyszukiwania nie wrzucał zbyt wiele, ewentualnie zwiększył to pole. Skoro rozszerzyłeś pole wyszukiwania o bonusowe pola, to musisz dopasować to pole do sumy pól które wybrałeś, jeżeli chcesz po wszystkim szukać.
