### ISSUE TITLE
[Question] [PL] Po aktualizacji do 5.3 problem przy dodawaniu rekordu

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#13406]
Witam,

We własnym module po aktualizacji do wersji 5.3 pojawia mi się komunikat na stronie:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '367814' for key 'PRIMARY' The SQL being executed was: INSERT INTO `u_yf_crmentity_label` (`crmid`, `label`) VALUES (367814, '509891358')

Rekord ostatecznie się dodaje do systemu.

**Comment by mrzewnicki** [comment]
W bazie powtarza się wartość label ale nie crmid

**Comment by vdpawel** [comment]
#12768

**Comment by mrzewnicki** [comment]
it work, thank you !
