### ISSUE TITLE
[Question] When responding to e-mail tickets recipient is empty and [ticket_no] in subject is [ticket_no]

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13403]
Hello,

I implemented mails to be processed by YF and incoming mails open sucessfully a new ticket.

![Screenshot_2020-08-19 Tickets Test CRM Support-System](https://user-images.githubusercontent.com/13665806/90652889-d786b200-e23e-11ea-9db4-f74a72737a80.png)

When responding to that mail, the mailprogramm **does not fill in recipient** and for the subject is inserted **[ticket_no]** **but there is no value** inside the brackets.

![Ticket-No](https://user-images.githubusercontent.com/13665806/90654098-4ca6b700-e240-11ea-904d-61078d1f173f.png)

Passing on the "Respond"-button with the mouse shows the link 

`mailto:?subject=Re: [ticket_no] Test CRM Support-System&body=thisisamail`

So there you can see that there are already missing the values.

Any idea? Did I missed to configure something?

How to reproduce:

1. Go to Support -> Tickets
2. Select the coresponding ticket
3. Click on "Respond" in the Summary-Tab

System: YF 5.3 SP 1

Thanks!

Kind regards

**Comment by blu-IT** [comment]
I also tested also on Gitstable now:

When triying to respond to the mail that is saved as ticket (via mailscanner), then the Subject does not create automatically a **[ticket_no]** an the **recipient (customer who send the mail) remains blank**.

Mouseover on the respond button the same: **mailto:?subject=[ticket_no] Testmail 4**

**Comment by blu-IT** [comment]
OK, I did some further tests:

When the e-mail adress is unknown (not registered in Organization or Contact), then the **recipient remains blank**. So data from this e-mail is **NOT** read - **also the e-mail body**, what I discoverd now.
When the e-mail adress is kown by the system (registerd as Organization or Contact), then clicking the **envelope** (see screenshot), will open the installed mailer and transfer recipient, but all other data (mail body!) and ticket_no still remain as the are.

![Mail](https://user-images.githubusercontent.com/13665806/91172984-5f583a80-e6dd-11ea-81ce-a032fe361e6f.png)

When clicking on the arrow to respond to the mail, the recipient still remains emtpy - even if the mail adress is known by the system. e-mail body and ticket_no still the same.

![Screenshot_2020-08-25 Tickets Testmail2 CRM](https://user-images.githubusercontent.com/13665806/91172677-d93bf400-e6dc-11ea-937d-05601db463b6.png)

This seems a bug to me, because the e-mail integration in the ticket overview is not usable this way!

**Comment by blu-IT** [comment]
@bpabiszczak Should I open a bug ticket for this? Do you need some other informations?

**Comment by blu-IT** [comment]
OK, it also tested the behavior on https://gitdeveloper.yetiforce.com/ .

When clicking on the "reply" button inside the ticket view, it opens an e-mail an the recipient is shown now!  

What still **does not work** is the assignment of a valid [ticket_no] in the subject as shown above:

![91172984-5f583a80-e6dd-11ea-81ce-a032fe361e6f](https://user-images.githubusercontent.com/13665806/94265264-7b4b3800-ff38-11ea-940f-9766a201b613.png)

**Comment by blu-IT** [comment]
OK, tested on YF 6.1 v7 now and while responding to mails now is working (recipient is inserted in e-mail now), still **ticket_no** is shown in e-mail subject, without any valid ticket number / value.

**Comment by mariuszkrzaczkowski** [comment]
fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/65f30dff0d0f19aef104e32d0077ccc45c92308e
