### ISSUE TITLE
[bug] Problem z dodawaniem załączników w Roundcube

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#13404]
Witam,
potrzebuję pomocy, mianowicie zmieniałem serwer i po przeniesieniu bazy, plików itp wszystko działa jak należy, oprócz tego, że nie dołącza mi załączników do maili.
Znalazłem w logach, że:
"[19-Aug-2020 20:54:18 +0200]: <3a44e1a5> PHP Error: biuro@rswsieci.pl **can't read /volume1/@tmp/rcmAttmntGFBKH4** (not in temp_dir) in /volume1/web/crm.rswsieci.pl/public_html/modules/OSSMail/roundcube/plugins/filesystem_attachments/filesystem_attachments.php on line 228 (POST /public_html/modules/OSSMail/roundcube/?_task=mail&_unlock=loading1597863255193&_lang=pl&_framed=1&_action=send)"

Ale ten plik znajduje się w @tmp po dodaniu załącznika do wiadomości przed wysłaniem
![image](https://user-images.githubusercontent.com/58420665/90677760-1d06a780-e25e-11ea-9d41-851a7aabcac4.png)

Czy ktoś może coś podpowiedzieć?
Przed migracją na innym serwerze (hosting) wszystko działało prawidłowo.

Aktualizacja:
Na testowym świeżo postawionym crm wszystko działa bez problemu, problem jest tylko na tym po przeniesieniu.

Czy jest możliwość, żeby do nowej instalacji zaimportować bazę danych i tylko niezbędne dane wprowadzić w plikach lokalnych? Bez przenoszenia całego starego katalogu.

**Comment by bpabiszczak** [comment]
Musi to sprawdzić programista. 
System składa się z plików i bazy, są rzeczy przechowywane w plikach [załączniki maili i dokumentów, cache uprawnień itd.], a więc obie rzeczy należy skopiować.
