### ISSUE TITLE
Mail Scanner

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1341]
When I go to Mail Scanner module I get the error
![Error](https://cloud.githubusercontent.com/assets/3193498/8499668/6521c26e-2195-11e5-851c-1ca5acbbceaf.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/17756fdd0495344c30653ed8109aeb1210fc91f0
