### ISSUE TITLE
Question about recurring invoices

### ISSUE THREAD

**Issue by nemerald-voip** [YetiForceCompany/YetiForceCRM#13411]
I'm currently using Vtiger and looking to switch to your platform. I looked a the online demo and read many posts here at GitHub and I can't figure out a couple of things. 
First, It looks like you modified the way way Vtiger's recurring sales orders work. In Vtiger they generate Invoices for me on a certain day of the month. In charge of this is a RecurringInvoice scheduler. I have worklow functions set to email those invoices when they generate. I programmed that myself.  Does it or does not work the same way here? Will I be able to generate Invoices on recurring basis?

Second, Is your Customer Portal 2 officially out? I couldn't see any demos or good documentation for deployment besides a few lines of code on GitHub. I did read a lot of posts saying that it wasn't out before and never saw any official word that it's completed. I don't want to install a buggy system.

**Comment by nemerald-voip** [comment]
Does anyone know?

**Comment by bpabiszczak** [comment]
1. You will not generate invoices automatically, because there is no such action in CRON.
2. The customer portal does not have a stable version.
