### ISSUE TITLE
[Question] YetiForceCRM behind reverse proxy?

### ISSUE THREAD

**Issue by BenLangers** [YetiForceCompany/YetiForceCRM#13416]
Hello everyone,
I have just been amazed by the installation process and initial configuration of YetiForceCRM. Incredible experience so far (and I've seen a few over the last couple of weeks). The only thing so far I have not been able to resolve is to publish YetiForceCRM behind a reverse proxy (adding SSL). This results in "The page isn’t redirecting properly" in the browser.
I am using nginx as reverse proxy, this is the location block I've tried last:

```
server {
    listen 443 ssl http2;
    include /etc/nginx/snippets/strong-ssl.conf;
    ssl_certificate /etc/letsencrypt/live/_fqdn_/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/_fqdn_/privkey.pem;

    server_name _fqdn_;

    root /var/www/html/yeti;

    error_page 401 403 404 /404.html;

    location / {
        proxy_pass              http://_internalIP_:8000;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Host $host;
    }
    location ~ /\.ht {
        deny all;
    }
    location ^~ /.well-known {
        allow all;
        autoindex on;
    }
}

```
I have tried changing the $site_URL variable in config/Main.php to the actual public URL, but this does not change the redirection error. It does prevent access via http://IP:port 😄 

Is it possible to host YetiForceCRM without SSL behind a reverse proxy for public access with SSL?

Thanks in advance!

Ben

**Comment by bpabiszczak** [comment]
Please check this: https://github.com/YetiForceCompany/YetiForceCRM/issues/13362
