### ISSUE TITLE
[bug]  Error linking the lead to the scheduled event

### ISSUE THREAD

**Issue by rezeyle** [YetiForceCompany/YetiForceCRM#13421]
See the video I attached as ZIP to demonstrate the error. Lead does not show at the scheduled event ... How can I solve this problem?
[Gravação de Tela 2020-08-24 às 12.26.53.mov.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/5119334/Gravacao.de.Tela.2020-08-24.as.12.26.53.mov.zip)

**Comment by rezeyle** [comment]
![Captura de Tela 2020-08-24 às 14 35 15](https://user-images.githubusercontent.com/28544752/91077278-2fdefa80-e617-11ea-977b-0dfe39a4b093.png)
![Captura de Tela 2020-08-24 às 14 34 32](https://user-images.githubusercontent.com/28544752/91077281-31a8be00-e617-11ea-8e14-faa9145023e6.png)

Even selecting the lead, it does not save.

**Comment by bpabiszczak** [comment]
I see that you modified the calendar and you probably "broke" something. It works fine in our test environment. This has to be checked by the developer.

https://yetiforce.com/en/marketplace/development-support

![image](https://user-images.githubusercontent.com/10197525/91378650-3e006700-e821-11ea-9f0c-c6ed75824d6b.png)
