### ISSUE TITLE
[bug]  How to use the Roundcube

### ISSUE THREAD

**Issue by rezeyle** [YetiForceCompany/YetiForceCRM#13426]
As shown below, the system does not allow me to change the Name of IMAP server. Where can I change or insert a new name server?
![Captura de Tela 2020-08-25 às 12 10 47](https://user-images.githubusercontent.com/28544752/91192289-219ee600-e6cc-11ea-8030-bfa1f0614ae1.png)
![Captura de Tela 2020-08-25 às 12 06 22](https://user-images.githubusercontent.com/28544752/91192360-37141000-e6cc-11ea-8c5c-53737a817a23.png)
![Captura de Tela 2020-08-25 às 12 05 15](https://user-images.githubusercontent.com/28544752/91192378-3bd8c400-e6cc-11ea-860a-b0787263d524.png)

Where can I insert the emails to be used on the Roundcube?

How many emails can I enter? Is there a limit?

**Comment by rezeyle** [comment]
https://www.youtube.com/watch?v=0JBckYE9ZuI

I can't match this video. I try but the system is not allowing it. Could you tell me how it can be solved?

**Comment by bpabiszczak** [comment]
This is not a picklist field, you can write whatever you want.

![image](https://user-images.githubusercontent.com/10197525/91375382-c7606b00-e81a-11ea-96ef-fd565f192f73.png)
