### ISSUE TITLE
[Question] [PL] Błąd 'syntax error, unexpected '0777' (T_LNUMBER)'

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#13431]
Witam,

Co mogę zrobić z takim błędem?
PHP Parse error:  syntax error, unexpected '0777' (T_LNUMBER) in /var/www/html/my_path/app_data/cron.php on line 44

![image](https://user-images.githubusercontent.com/21024857/91312677-ca287500-e7b4-11ea-9963-3b5ec06c6ce8.png)

Pokazuje się on kiedy próbuję przejść do Panelu Admina

**Comment by bpabiszczak** [comment]
Najlepiej to go naprawić :)
Wersja CRM, co logi pokazują?

**Comment by rskrzypczak** [comment]
To powinno rozwiązać problem: https://github.com/YetiForceCompany/YetiForceCRM/commit/b14961d1e19d6b1c10a61777bc288fcd93c21b4c
https://github.com/YetiForceCompany/YetiForceCRM/issues/13005
https://github.com/YetiForceCompany/YetiForceCRM/issues/13251
https://github.com/YetiForceCompany/YetiForceCRM/issues/13190

**Comment by mrzewnicki** [comment]
Pomogło, dzięki
