### ISSUE TITLE
[bug] Project error

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#13438]
When I create a Project record and save I receive this error. How do I fix?

![Screen Shot 2020-08-27 at 5 21 25 PM](https://user-images.githubusercontent.com/45261773/91627946-4673b180-e989-11ea-82b9-bcf2f73bbbfd.png)

**Comment by bpabiszczak** [comment]
![issue](https://user-images.githubusercontent.com/10197525/91657612-a1f58a80-eac2-11ea-9902-bcf1cfa344e3.jpg)
