### ISSUE TITLE
[bug] Automatyczne archiwizowanie starych rekordów

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#13434]
Witam,
jak w temacie, czy tą funkcję w cron można jakoś skonfigurować, tzn jak stare rekordy mają być przenoszone itp.
Nie bardzo widzę, żeby w ogóle działała ta funkcja.

Dodatkowe pytanie, czy można jakoś zarchiwizować wszystkie rekordy w module? Bo jak zaznaczam niby wszystkie to i tak archiwizuje tylko te aktualnie wyświetlane na ekranie, czyli maks 100.

Pozdrawiam

**Comment by vdpawel** [comment]
_Ad. Dodatkowe pytanie:_

Zaznaczasz rekordy na stronie checkboxem po lewej stronie, na środku pojawia się komunikat: "Zaznacz wszystko"
![obraz](https://user-images.githubusercontent.com/62466142/91551200-1648f600-e92a-11ea-80c5-c41659b1c146.png)

klikasz na niego i wybierasz: Akcje -> Masowa archiwizacja

Nie działa?

**Comment by bpabiszczak** [comment]
Można wszystko, lecz potrzeba do tego programistę najczęściej. 
Aby przenosić coś automatycznie, to należy to automatycznie zweryfikować, czy na pewno przenoszone być powinno. Sama "zmiana" to jedna linijka kodu, a więc łatwa do realizacji czy to skryptem czy workflow, trudnością jest weryfikacja wszystkich warunków. 

Gdy zaznaczasz całą stronę, pojawia się dodatkowa opcja z zaznaczeniem wszystkiego tak jak w poście powyżej.
