### ISSUE TITLE
Need some help to get Yetiforce configured 

### ISSUE THREAD

**Issue by iceghostx** [YetiForceCompany/YetiForceCRM#13430]
### Description

I am new to CRMs and Yetiforce. I like what I can see but I need some help to make sure system is setup properly.

I am sure there must be expert YetiForce techs out there - I need to find someone to assist us with final tweaking and config of the system in Ubuntu. The CRM is for 4 users only - so a small install. How do I find someone to help pleasE?

Ubuntu, with full console access.
Latest Yetiforce

**Comment by bpabiszczak** [comment]
It is cheaper to take web hosting: https://yetiforce.com/en/marketplace/hosting-en 
But you can also hire experts: https://yetiforce.com/en/marketplace/development-support
