### ISSUE TITLE
[Question] [PL] Nie funkcjonujące widżety w podsumowaniu modułu zgłoszeń

### ISSUE THREAD

**Issue by unununkwad** [YetiForceCompany/YetiForceCRM#13439]
Po przyjęciu maila przez pocztę generuje się zgłoszenie i powiązuje z mailem. Niestety w podsumowaniu zgłoszenia nie widać żeby przyjęło żadnego maila. W karcie "Historia maili" widać że go przyjęło. Tak samo sytuacja wygląda jeżeli chodzi o historię zmian. W karcie "Historia zmian" widać wszystkie zmiany, lecz w podsumowaniu nic nie ma. 

![image](https://user-images.githubusercontent.com/69234051/91715057-43e1a980-eb8d-11ea-9d6f-1fc4466dcc24.png)
Historia zmian jest tutaj rozwinięta.

![image](https://user-images.githubusercontent.com/69234051/91715169-77243880-eb8d-11ea-843e-a6357ad70a90.png)

![image](https://user-images.githubusercontent.com/69234051/91715344-b8b4e380-eb8d-11ea-868a-8a0c80a21e75.png)

W module kontrahenta problem nie występuje i maile wraz z historią zmian wyświetlają się normalnie.
![image](https://user-images.githubusercontent.com/69234051/91715783-b010dd00-eb8e-11ea-9a3b-f28c2a70a236.png)

Z panelu administratora nie można modyfikować widżetów, więc to chyba nie z powodu konfiguracji.

**Comment by rskrzypczak** [comment]
Jaka wersja aplikacji?
Włącz logi aplikacji.
Włącz konsole (F12) prawdopodobnie tam znajdziesz odpowiedź
![image](https://user-images.githubusercontent.com/10221999/91796276-07ab5900-ec20-11ea-9ae1-d90a42fbab19.png)

**Comment by unununkwad** [comment]
Wersja 5.3.0, ale wgrałem aktualizację service packa w module "Serwer - aktualizacje" i już działa.
