### ISSUE TITLE
[bug] Can't save Workflow's Task details

### ISSUE THREAD

**Issue by panos-stavrianos** [YetiForceCompany/YetiForceCRM#13443]
Hello Everyone!
### ⁉️ Describe the bug
I think this is an unexpected behavior of a workflow task, 
I am trying to create an event but whatever I do the `start date` field do not seems to change
![workflow_task_prob](https://user-images.githubusercontent.com/20128753/91861619-b62db900-ec75-11ea-90a6-79d14d3b082c.gif)

### 🔥 How to trigger the error

1. Go to Software configuration/Automation/Workflows
2. Pass on the `Schedule workflow` and `Add conditions` tabs 
3. Add to do -> Create event
4. Set the `start date` field to something other than start date 
5. Save it
6. Open it again and the settings will be  different

### 🌍 Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.2
| Web server (name and version)       |   Apache/2.4.29        |
| PHP                                 |         7.2       |
| Browser (name and version)          |     Chrome   85.0        |
| Operating System (name and version) |    Ubuntu 18.04            |
| Database (name and version)         |        mysql 10.1.44        |

**Comment by bpabiszczak** [comment]
First of all: upgrade your system to the latest version.
Second: check if the bug is on gitdeveloper.
