### ISSUE TITLE
[Question] [PL] Niepoprawna aktualizacja rekordu przez wyzwalacze/workflows

### ISSUE THREAD

**Issue by unununkwad** [YetiForceCompany/YetiForceCRM#13448]
Mam w planie dodawać w zgłoszeniach numer prefixu do tematu zgłoszenia. Problem polega na tym, że po aktualizacji rekordu przez wyzwalacze zmiana zostaje wprowadzona, lecz nie zapisana. W ten sposób traci powiązanie z mailem.

W taki sposób ustawioną mam aktualizację rekordu
![image](https://user-images.githubusercontent.com/69234051/91988732-e9348300-ed2f-11ea-9559-a3eed19cf6b2.png)

Prefix rzeczywiście został dodany do tematu
![image](https://user-images.githubusercontent.com/69234051/91989828-47ae3100-ed31-11ea-88da-7094ee721462.png)

Lecz w zgłoszeniu nie widać aby temat był zmieniony, a dodatkowo nie ma powiązania w wiadomości e-mail
![image](https://user-images.githubusercontent.com/69234051/91990507-1bdf7b00-ed32-11ea-9048-3b91393df4a2.png)

W historii zmian widać wyłącznie utworzenie rekordu, nie pojawia się żadna aktualizacja
![image](https://user-images.githubusercontent.com/69234051/91990740-6234da00-ed32-11ea-8667-c9b079cbdc91.png)

Wersja 5.3.0

**Comment by bpabiszczak** [comment]
ogólnie to nie rozumiem problemu. Temat nie ma nic wspólnego z powiązaniem z mailem [zmiana tematu nie wpływa na to, czy mail jest powiązany czy nie, może co najwyżej wpłynąć na kolejne powiązania ale nie na istniejące]. Po drugie nie rozumiem po co to robisz... po co zmieniać temat? Przecież przy wysyłce maila z CRM system automatycznie dodaje do wiadomości mail prefiks a gdy mail przychodzi, to powiązuje go nie po temacie zgłoszenia w CRM lecz po numerze w polu numeru.
