### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by alexynadamas** [YetiForceCompany/YetiForceCRM#13442]
Hi

I am trying to export all companies's data into a CSV file. In Yeti apperas 991 records but when I export it the file has only 623 records. 

https://i.imgur.com/EZRF6iK.png (YetiForce)

https://i.imgur.com/V6OQCMv.png (Excel)

What is the problem?

I can't find the table in the database either. What is his name?

Thanks

**Comment by bpabiszczak** [comment]
Most likely there is no required data in the mandatory fields or the data has been added incorrectly. You haven't uploaded your logs. You have not written what clients are missing [on the example of one client you may find a problem, e.g. a strange sign]

**Comment by davide-alghi** [comment]
@alexynadamas,
did you try to export data in XML format?
