### ISSUE TITLE
Call to a member function isActive() on bool

### ISSUE THREAD

**Issue by slomus** [YetiForceCompany/YetiForceCRM#13458]
Witam

Mam mały problem 
![Przechwytywanie](https://user-images.githubusercontent.com/67637171/92391430-fdf08c80-f11c-11ea-8239-522f1c1640e2.PNG)

Niestety nie wiem jak go moge rozwiązać. Wiem ze moze to byc wina złej conf serwera ale co dokładnie

**Comment by rskrzypczak** [comment]
Use a search engine: https://github.com/YetiForceCompany/YetiForceCRM/search?q=function+isActive&type=Issues
https://github.com/YetiForceCompany/YetiForceCRM/issues/13248
