### ISSUE TITLE
Class 'Locale' not found

### ISSUE THREAD

**Issue by slomus** [YetiForceCompany/YetiForceCRM#13457]
Witam

Mam mały problem.
![błąd](https://user-images.githubusercontent.com/67637171/92369129-e3a4b780-f0f8-11ea-949e-f512a72da319.PNG)
Stało się to po installacji php7.3 poprzednia wersja 7.1 

Czy wynika to przez instalacje php czy jest to jakis inny błąd związany z brakim pliku bądz odpowiedzniej konfiguracji

:)

**Comment by mariuszkrzaczkowski** [comment]
Serwer nie jest zgodny z wymaganiami
https://github.com/YetiForceCompany/YetiForceCRM/issues/9821

**Comment by slomus** [comment]
Ale w czym może byc dokładnie problem czy jest to wina php czy czegos innego

**Comment by mariuszkrzaczkowski** [comment]
brak biblioteki w php

**Comment by ammardun** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/60503484/116021638-28c32d00-a67b-11eb-9779-1e4c50b54adc.png)
how to solve this problem?
Class 'Locale' not found
Please Help Me!!!

**Comment by rskrzypczak** [comment]
install intl extension - https://github.com/YetiForceCompany/YetiForceCRM/issues/9482#issuecomment-471056759
