### ISSUE TITLE
[Question] Disappearing mails from mailbox

### ISSUE THREAD

**Issue by A3ANO** [YetiForceCompany/YetiForceCRM#13450]
Hi,

I have a question regarding the mailboxes inside the YetiForce CRM. I'm using a few mailboxes and recently I noticed that old mails are been removed automatically. If I link an e-mail to a contact or account, I can still see it in their history. However, the mail cannot be found in the mailboxes.
Is there some setting or cronjob that does this? I have been checking for a few days now, but I still cannot find what is causing this. I connect to the mailboxes via IMAP, and there is no limit on our mailboxes on the mailserver.

Can somebody help me with this?

Thanks

**Comment by blu-IT** [comment]
Hi,

can you please post a screenshot of your mailbox settings inside YF and also the folders sync settings?
Do you have some filters that may move mails on your mailserver?

**Comment by rskrzypczak** [comment]
YetiForce does not make any modifications to mailboxes by default.

**Comment by A3ANO** [comment]
Hi blu-IT, which settings would you like to see? There are a few menu items where you can add some settings (see screenshot).
![image](https://user-images.githubusercontent.com/9215711/93050230-caed5200-f662-11ea-8d5a-960c31877848.png)
I had a spam filter enabled to filter spam. The strange thing about my problem is that the mails are received and afterward disappear or are deleted.

Here is the mail scanner system settings:
![image](https://user-images.githubusercontent.com/9215711/93051106-43084780-f664-11ea-8cb6-b55c75516555.png)

Here are the screenshots for the mail settings
![image](https://user-images.githubusercontent.com/9215711/93051306-8cf12d80-f664-11ea-9a36-cc0efd1fb0bb.png)
![image](https://user-images.githubusercontent.com/9215711/93051359-a1352a80-f664-11ea-893f-2ca17307d0c3.png)

Thanks in advance

**Comment by blu-IT** [comment]
Did you check, if the mails were moved in a Junk- or Deleted-Folder?

Am 14. September 2020 08:32:50 MESZ schrieb A3ANO <notifications@github.com>:
>Hi blu-IT, which settings would you like to see? There are a few menu
>items where you can add some settings (see screenshot).
>![image](https://user-images.githubusercontent.com/9215711/93050230-caed5200-f662-11ea-8d5a-960c31877848.png)
>I had a spam filter enabled to filter spam. The strange thing about my
>problem is that the mails are received and afterward disappear or are
>deleted.
>
>Here is the mail scanner system settings:
>![image](https://user-images.githubusercontent.com/9215711/93051106-43084780-f664-11ea-8cb6-b55c75516555.png)
>
>Here are the screenshots for the mail settings
>![image](https://user-images.githubusercontent.com/9215711/93051306-8cf12d80-f664-11ea-9a36-cc0efd1fb0bb.png)
>![image](https://user-images.githubusercontent.com/9215711/93051359-a1352a80-f664-11ea-893f-2ca17307d0c3.png)
>
>Thanks in advance
>
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/YetiForceCompany/YetiForceCRM/issues/13450#issuecomment-691845112

-- 
Diese Nachricht wurde von einem mobilen Gerät versendet.

**Comment by A3ANO** [comment]
Hi,

Yes, but they are not there. They seem to vanish without a trace as if they where deleted.
Is there a cron or task that can be responsible for this? I did not change allot in the configuration of YetiForce.

**Comment by bpabiszczak** [comment]
You will find the answer in the mail server log.
