### ISSUE TITLE
[Question]  How to set a workflow to trigger birthday notification

### ISSUE THREAD

**Issue by suarezjg** [YetiForceCompany/YetiForceCRM#13468]
Hi, I hope you are doing well. I wonder if you know how to set a workflow to trigger birthday notification. I tried setting a condition like this: “Birthday is today”, but doesn’t work. I look forward to hearing your comments.

**Comment by bpabiszczak** [comment]
You need to create a new uitype that will only indicate the month and the day without the year. Or you can write a script that will do this in real time. You need a developer for this.

**Comment by suarezjg** [comment]
Thanks for your comment, Now, if I'd decide to use the first option "create a new uitype that will only indicate the month and the day without the year", How can I compare the new uitype with the date, I mean, I know how to compare, but I think Yetiforce can't extract day/month from date, I know Yetiforce has a function get_date ('today'), and that's it
