### ISSUE TITLE
[Question] CardDAV/CalDAV: I only can see my contacts and meetings - how to see ALL?

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13469]
Hello,

I tried configuring Mozilla Thunderbird addressbook (and calendar) via CardDAV/CalDAV to YF-CRM. 
So far everything went fine, **BUT I can see only my (test-)contact** an even no organizations. But I want to see **ALL organizations and contatcs** in the crm.

I'am using my normal YF account (with admin rights):
`https://myserver.com/dav.php/principals/ME/`

also tried 
`https://myserver.com/dav.php/addressbooks/ME/YFAddressBook/`

When importing all the organizations and contacs into YF I was using another admin account and so I also created a key for CardDAV/CalDAV access into the YF settings, but the table "sum of contacs" already shows only 1 contact to me.

So where are all the contacs? How do get them all shown via CardDAV?

I found that post here, where sombody had a vice verca problem - but unfortunately that did not help me.

https://github.com/YetiForceCompany/YetiForceCRM/issues/5992

Thanks!

Regards

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Users&view=PreferenceEdit&record=5
![image](https://user-images.githubusercontent.com/10198654/93425537-7e9c4f00-f8ba-11ea-8d49-191c19c94487.png)

**Comment by blu-IT** [comment]
@mariuszkrzaczkowski 

Thanks! I changed the settings, but still get only the contacts, **NOT** the organizations via CardDAV.

**Comment by Hammerman3000** [comment]
+1
Same question: How can I have all contacts available in the system synced via carddav?
The "Based on CRM permissions" is a mysterious option since I do not find any related setting in the role manager? I mean how to setup the permission for a user to see ALL contacts? @mariuszkrzaczkowski

**Comment by blu-IT** [comment]
@Hammerman3000 

Have you checked the ownership of your contacts? I can see contacts that I created in the system but not the organizations. 
I fear that this is not possible which would rend the CardDAV module useless.

**Comment by Hammerman3000** [comment]
@blu-IT 
Hey Ivan, 
yeah i do see contacts that are part of an account or lead as well as contacts that have been added in the system without any relationship.
Indeed I think it's easily possible, just the role management in yetiforce is not properly documented. 

I created an admin account with setting "Synchronize CardDAV contacts: Based on CRM permissions"
Then created the CardDav Key 
Then **waited** (seriously!) for an hour or so - and suddenly contacts would start to show up.

The next best question for me right now is rather how to get this prehistoric format somehow into an LDAP or similar format so it can sync with google contacts or anything modern other than local email clients ^^

**Comment by Hammerman3000** [comment]
When you say you don't see the "organizations" what are you referring to?
Did you actually check the vcf exports done by yetiforce if the desired values are included?
since the vcf exports are contact based they are of course on an "per contact" level

**Comment by blu-IT** [comment]
I mean the organizations stored in "Accounts" which are an essential part of the contact list here (contacts without specific contact).
