### ISSUE TITLE
How to close a running cron task? [Question] 

### ISSUE THREAD

**Issue by rvencu** [YetiForceCompany/YetiForceCRM#13478]
### Description
I try to import 7200 contacts. Of course, for such a big file I had a number of bad formatted phone numbers and such. The problem I face is that while the cron task fails with error (in cron.log) the Scheduled import keeps running for a long time doing nothing. I cannot find any way to stop that and retry the improved CSV import. Is there a way?

Of course, I cancel the current import, also when I retry to import again I cancel the current job once again in the contacts module import interface.

Still, the Settings-Automation-CRON lists the Scheduled Import still running even after one hour after the crash and it would not accept new import jobs because the previous one is not finished yet.

Even rebooting the server would not solve the problem.

**Comment by rvencu** [comment]
I found that editing the task and saving it updates the Status, hence it can be made Active again.

However, it is not normal after a crash not to reset the Status of the cron task automatically

**Comment by s2b-git** [comment]
Experiencing the same with Execution Schedule. It hangs and need to restart task to make it working.

**Comment by mariuszkrzaczkowski** [comment]
If you have a problem with CRON, checking the server configuration is a common problem.
![github](https://user-images.githubusercontent.com/10198654/119935297-910d7300-bf87-11eb-9a53-c45e3a36f0d6.jpg)
