### ISSUE TITLE
Normalizer.php

### ISSUE THREAD

**Issue by slomus** [YetiForceCompany/YetiForceCRM#13473]
Witam 

Mam taki bład i nie wiem co mogę z tym zrobic a nie chce edytowac kodu php
![Bład - generowanie pdfa - raport](https://user-images.githubusercontent.com/67637171/92927753-68b40780-f43e-11ea-87e0-47362f861033.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/92928135-f8f24c80-f43e-11ea-9dfd-287d477fad13.jpg)

**Comment by slomus** [comment]
Nie pisze ze to jest bug tylko mam pytanie wiec nie wiem czemu wyświetlasz mi jak mam napisac o bugu sprawdz moze najpierw co jest wrzucane a nie

**Comment by bpabiszczak** [comment]
Tutaj nie ma o czym dyskutować, każdy błąd należy sprawdzić w logach, opisać jak go wywołać, czy pojawia się na wersji stable i dev a na dodatek należy pokazać swoją konfigurację serwera. Szanuj nasz czas, jeżeli mamy się czymś zająć to musimy mieć pewność, że to o co prosimy, zostało zrobione, jeżeli nie, to nie zajmujemy się tematem... bo jak życie pokazuje, większość błędów wynika m.in. ze złej konfiguracji serwera.

**Comment by rskrzypczak** [comment]
Pewnie dodałeś jakiś styl w szablonie pdf, który biblioteka nie obsługuje.

**Comment by slomus** [comment]
Niestety w logach nic nie ma wiec nie ma sesnu aby logi wysyłał każa linijka loga ma zapisane coś takiego :
2020/09/11 15:18:33 [error] 12038#0: *2 FastCGI sent in stderr: "PHP message: PHP Warning:  Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) in Unknown on line 0" while reading response header fr$

**Comment by bpabiszczak** [comment]
Spójrz proszę na post od Mariusza i mój, dokładnie krok po kroku należy sprawdzić i wkleić dane o które prosimy, w przeciwnym wypadku nie zajmiemy się tym.
