### ISSUE TITLE
Portal

### ISSUE THREAD

**Issue by slomus** [YetiForceCompany/YetiForceCRM#13489]
Witam

Czy aby posiadac yeti portal musze miec wystationy serwer z taka samą konfiguracja jak do yetiforce crm ?

**Comment by bpabiszczak** [comment]
Aktualnie portal nie jest w wersji stabilnej, a więc nie musisz posiadać żadnej konfiguracji. Gdy zostanie opublikowana wersja stabilna, wówczas opublikujemy z nią wymagania.
