### ISSUE TITLE
[bug] Occurrences module, cannot load/add participants

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13485]
Hi,

FYI, this error is present on gitstable and gitdeveloper.
Participants tab only opens if there is no relation, as soon as you try to add or select a participant :
- error notification appears "Entered invalid value"
- the participant tab stops responding.
Example :
https://gitstable.yetiforce.com/index.php?module=Occurrences&relatedModule=Contacts&view=Detail&record=3188&mode=showRelatedList&relationId=624&tab_label=LBL_PARTICIPANTS

However, I don't have this issue on my YF.
Regards,

**Comment by bpabiszczak** [comment]
it works for me, show the movie on gitdeveloper.

![image](https://user-images.githubusercontent.com/10197525/93405940-b55c7000-f88e-11ea-9813-c8c3143698b5.png)

**Comment by apcloic** [comment]
@bpabiszczak Yes, the issue is gone on gitdeveloper but still exists on gitstable.

![bug_occurrences_yetiforce_gitstable](https://user-images.githubusercontent.com/2930560/93429195-0edd9280-f8c1-11ea-8666-16e2e159144f.gif)

**Comment by bpabiszczak** [comment]
It means that the bug has been fixed :)
