### ISSUE TITLE
[bug] I had igbinary serializer preinstalled, removing it locks me out of the application

### ISSUE THREAD

**Issue by rvencu** [YetiForceCompany/YetiForceCRM#13482]
# 🐞 bug report

### ⁉️ Describe the bug

My system had preinstalled igbinary PHP serializer. Later I discovered that session cleaner cron task issue this error

ERROR: LBL_SESSION_CLEANER - Cron task execution throwed exception.
App\Exceptions\NotAllowedMethod: Unsupported session.serialize_handler: igbinary. Supported: php, php_binary in /home/madinaf/app/Session/File.php:64

I tried to uninstall igbinary and then I was locked out of the system because of nonce/inline scripts refused to work in order to let me login into the system.

I had to revert to igbinary serializer and regain access to my app.

But I am stuck with the unworking cron task.

### 🔥 How to trigger the error

1. Install fresh system, setup igbinary serializer
2. Setup yetiforcecrm, remove all warnings
3. Remove igbinary. 
4. You cannot login anymore, follow console errors to see how to fix this if possible.

### 👎 Actual Behavior

Cannot login anymore

### 👍 Expected Behavior

Login should be possible AND session cleaner cron task should work without errors

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![image](https://user-images.githubusercontent.com/287411/93080755-e5d9b980-f696-11ea-998d-66ace1764e3a.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3
| Web server (name and version)       |   Apache 2.4             |
| PHP                                 |                | PHP 7.3.23
| Browser (name and version)          |  MS New Edge              |
| Operating System (name and version) |   Windows 10             |
| Database (name and version)         |    MariaDB 10.3            |
| Service Pack version                |      4          |

**Comment by mariuszkrzaczkowski** [comment]
Currently, the system does not support igbinary handler, someone would have to add it.
The easiest way is to change the default handler in the php.ini settings
```session.serialize_handler = php```
https://www.php.net/manual/en/session.configuration.php#ini.session.serialize-handler

**Comment by mariuszkrzaczkowski** [comment]
According to their documentation, this should work
app\Session\File.php
```php
	/**
	 * Deserialize session data from string, entry function.
	 *
	 * @param string $session
	 *
	 * @throws \App\Exceptions\IllegalValue
	 * @throws \App\Exceptions\NotAllowedMethod
	 *
	 * @return array
	 *
	 * @example http://php.net/manual/en/function.session-decode.php#108037
	 */
	public static function unserialize(string $session)
	{
		$method = ini_get('session.serialize_handler');
		switch ($method) {
			case 'php':
				return self::unserializePhp($session);
				break;
			case 'php_binary':
				return self::unserializePhpBinary($session);
				break;
			case 'igbinary':
				return igbinary_unserialize($session);
				break;
			default:
				throw new \App\Exceptions\NotAllowedMethod('Unsupported session.serialize_handler: ' . $method . '. Supported: php, php_binary');
		}
	}
```
