### ISSUE TITLE
Email campaign are not sent from the marketing module

### ISSUE THREAD

**Issue by Kancelaria2019** [YetiForceCompany/YetiForceCRM#13487]
My campaign and email are not sent from the marketing module.  All templates are connected 

Before sending, a message appears that e-mails are added in CRON.

However, in CRON nothing is sent and nothing is added to sending.

Should I add some trigger?

### Description
![image](https://user-images.githubusercontent.com/68275748/93308852-1a6a8400-f803-11ea-978d-a77808a79d09.png)

**Comment by apcloic** [comment]
@Koko-321 
Are you sure CRON is working ?
Did you check in Settings / Mail tools / Email to send if there is any error ?
https://gitstable.yetiforce.com/index.php?module=Mail&parent=Settings&view=List&block=8&fieldid=104

**Comment by Kancelaria2019** [comment]
CRON is working wery well. I haven't problem with sending email from enother modules. 
These Ttaska are not added to the queue. I THINK SO ;/

![image](https://user-images.githubusercontent.com/68275748/93319088-c023f000-f80f-11ea-9f2e-02f96597ce92.png)

**Comment by bpabiszczak** [comment]
brak logów, brak konfiguracji.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/93425587-983d9680-f8ba-11ea-97eb-3bbb8714fe13.jpg)

**Comment by Kancelaria2019** [comment]
![image](https://user-images.githubusercontent.com/68275748/93604814-31a59f00-f9c6-11ea-9763-d2af9c6ff44d.png)

![image](https://user-images.githubusercontent.com/68275748/93604985-73cee080-f9c6-11ea-94a2-124d60760777.png)

**Comment by Kancelaria2019** [comment]
I sent a bug report. What is the reason for the @ error?

**Comment by Kancelaria2019** [comment]
![image](https://user-images.githubusercontent.com/68275748/94127710-88452a00-fe59-11ea-9709-105c074d0a81.png)

**Comment by Kancelaria2019** [comment]
![ConfReport (2)](https://user-images.githubusercontent.com/68275748/94128397-6d26ea00-fe5a-11ea-85b0-7d20182c380b.png)

**Comment by z0lo13** [comment]
it was an existing issue already #12113

 it fixes if you add a field email without number after. However its not a solution. 

For some reason email1 is not recognized as email field but its recognized as Standard and purifier treats it like value and validation breaks.
