### ISSUE TITLE
[Question] Contacts with the same e-mail adress

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#13493]
Hi all, 

When I add a contact with an e-mail adress that is already in use by another contact then I receive the message "Duplicate email address". But some contacts use the same e-mail adress. For example families where the father and the mother of the family has a shared e-mail adress.
How can I make sure that I can save a contact with an e-mail adresses that is already in use?
![image](https://user-images.githubusercontent.com/16014524/93449872-9208e380-f8d5-11ea-964a-34be682148b1.png)

Thanks for the tips!

Laurens

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=EventHandler&view=Index
![image](https://user-images.githubusercontent.com/10198654/93450633-7a7e2a80-f8d6-11ea-8db5-2fc6160913ae.png)

**Comment by apcloic** [comment]
@LaurensCleyman As EventHandler module is not available yet, you can disable duplicate email handler directly from database.
Using phpmyadmin, search for the string 'Contacts_DuplicateEmail_Handler' and change 'is_active' to 0
