### ISSUE TITLE
[Question] How to get access to 'Event handlers'-menu item

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#13494]
Hi all, 

I noticed on the YetiForce demo that there are different menu items between 'Test Gitstable' and 'Test Gitdeveloper' 

How can I have acces to settings like 'Event handlers' and 'Conflict of interests'?

![image](https://user-images.githubusercontent.com/16014524/93454976-02b2fe80-f8dc-11ea-973e-54e11458154c.png)

Or there more 'hidden' options?

Kind regards, 

Laurens

**Comment by bpabiszczak** [comment]
Stable - stable version [5.3]
Developer - latest developer version [5.4/6.0]
stable != daveloper

These modules will be published in the new version.
