### ISSUE TITLE
[Question] I noticed PBX integration has vTiger to Asterisk connector. Will any Asterisk PBX integration work with YetiforceCRM as well?

### ISSUE THREAD

**Issue by rvencu** [YetiForceCompany/YetiForceCRM#13490]
### Description
For instance this 3CX integration will work out of the box or via Asterisk connector? https://www.3cx.com/docs/vtiger-crm-pbx-integration-server-side/

**Comment by mariuszkrzaczkowski** [comment]
There is integration but only limited to making connections, not tested so I don't know if it works.
https://gitdeveloper.yetiforce.com/index.php?module=PBX&parent=Settings&view=List
![image](https://user-images.githubusercontent.com/10198654/93425779-f4081f80-f8ba-11ea-978f-1be22db38384.png)
