### ISSUE TITLE
Mail conversion to Ticket not working properly - YetiForceCRM 4.4

### ISSUE THREAD

**Issue by butuemi** [YetiForceCompany/YetiForceCRM#13491]
I configured the Rouncube & Mail Scanner, singed-up in my Mailbox and tried to create a ticket from an email.
I am receiving "**_ERR_RECORD_NOT_FOUND_**" because in the creation request the **sourceRecord** field is wrong, +/- 3 than the real ossmailviewid of the record in vtiger_ossmailview table. 
Also, when trying to link an existing account to the ticket before generating it, I receive an error that says I don't have the permissions to do so "_**ERR_NO_PERMISSIONS_FOR_THE_RECORD**_".

I would really appreciate some support since the configuration went well, the table is populated but the request are broken.

Thank you very much!

**Comment by bpabiszczak** [comment]
First, upgrade your system.
