### ISSUE TITLE
Unable to access subdirectories during install

### ISSUE THREAD

**Issue by Trumanp014** [YetiForceCompany/YetiForceCRM#13505]
Hi There, 

While attempting to install 5.3 on a Centos 7.8 install, running nginx 1.16.1, mariadb 10.1.46, php 7.2.33, I am coming up with an error where the installer can not seem to write to the directories under the public_html directive in the nginx configuration.

Snippet from the nginx logs:

2020/09/18 00:13:23 [error] 21011#0: *116 open() "/var/www/yeti/public_html/config" failed (2: No such file or directory),
2020/09/18 00:13:23 [error] 21011#0: *117 open() "/var/www/yeti/public_html/cache" failed (2: No such file or directory), 
2020/09/18 00:13:23 [error] 21011#0: *118 open() "/var/www/yeti/public_html/app_data" failed (2: No such file or directory), 
2020/09/18 00:13:24 [error] 21011#0: *119 open() "/var/www/yeti/public_html/storage" failed (2: No such file or directory), 
2020/09/18 00:13:24 [error] 21011#0: *120 open() "/var/www/yeti/public_html/user_privileges" failed (2: No such file or directory),

The install directory has ownership by nginx's user, and is set to 755 permissions.

During install there are no red or yellow sections/warnings regarding anything.

If I switch the nginx directory pointer to just the /var/www/yeti directory instead of /var/www/yeti/public_html I get an unable to find license files error.

It's a bit perplexing, would anyone have a suggestion on where to look at this point?

**Comment by davide-alghi** [comment]
> The install directory has ownership by nginx's user, and is set to 755 permissions.

Hi @Trumanp014,
have all files/folders, into install directory, ownership by nginx's user?

**Comment by Trumanp014** [comment]
Indeed they have. This is what is most puzzling.

**Comment by davide-alghi** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/11421#issuecomment-530265830

Are these satisfied in your intall process?
