### ISSUE TITLE
[Question] How do i configure roundcube for Yetiforce

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13502]
### Description

I have trying configuring the SMTP as well as Roundcube module for Emails but i am unable to get it work .
Whenever i try to login to roundcube through Yetiforce CRM i get error message "504-Gateway Timeout"

Yetiforce version: v5.3.0

**Comment by mariuszkrzaczkowski** [comment]
Turn on logs and see what error message you have

**Comment by rohanjhanepal** [comment]
In which logs file , could i find the Error logs for Roundcube?

**Comment by mariuszkrzaczkowski** [comment]
turn on full logs and check all errors start with

https://yetiforce.com/pl/component/zoo/item/debugging

![github](https://user-images.githubusercontent.com/10198654/93708213-bca4a780-fb34-11ea-9c8e-62eae99693fb.jpg)

**Comment by rohanjhanepal** [comment]
Thanks i solved the problem by changing the SMTP host to appropriate value
