### ISSUE TITLE
[Question] How do i link roundcube emails to appear in the widget?

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13514]
### Description

I want emails that was sent from linked roundcube account to appear in email widget section.
Here i have attached a picture. 
There is email widget , where i need emails!
How do i do that?
![Screenshot (28)](https://user-images.githubusercontent.com/40380541/93840244-7d4e9600-fcaf-11ea-9441-dba99f779499.png)

**Comment by bpabiszczak** [comment]
1. Use the email scanner panel. [Software configuration > Mail tools > Mail – Scanner]
2. To manually bind e-mails, use the mechanism built into roundcube:

![image](https://user-images.githubusercontent.com/10197525/94673466-110b0c80-0317-11eb-8976-8059f8293ca4.png)
