### ISSUE TITLE
YetiForce CRM 5.3 SecurityFix v1 ... dont install

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13527]
installing 

YetiForce CRM 5.3 SecurityFix v1

 make all most picklist go away in all modules... 
can anyone tell me how to fix it back?

have to go to each module and manually reassign the role ....

**Comment by mariuszkrzaczkowski** [comment]
the package updates only the library does not change CRM files,
 turn on logs

**Comment by rioshaz** [comment]
where do i find logs, so i can share with u

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/component/zoo/item/debugging

**Comment by rskrzypczak** [comment]
as @mariuszkrzaczkowski mentioned - "the package updates only the library"
No answer, so I close.
If you still have a problem, open a new ticket and complete the information.
