### ISSUE TITLE
[bug] Cant' log in to my Yetiforce system

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#13520]
# 🐞 bug report

### ⁉️ Describe the bug

My Yetiforce CRM has been working fine since last year. I have three users set up.  When I open the login page at https://asperiti.uk/yetiforce I am prompted for my username and password, which are the same as they always have been and have not been changed. The same thing happens when I try to log in with any of the users. I enter the username and password, there is a brief pause and the login page just reloads with no error message, and does not proceed to my calendar page as it normally does. This started happening on Monday 21st September when I tried to log in for the first time after the weekend.

I can access my database using phpmyadmin, and it appears to be undamaged. As a precaution, I restored an earlier version of the database from the automatic backups provided by 1and1 Ionos. This was from the 19th September, when the system was working fine. After the restore, the login still fails.

### 🔥 How to trigger the error

Go to login page at https://asperiti.uk/yetiforce
Enter a valid username and password.

### 👎 Actual Behavior

Login page just reloads and application does not start.

### 👍 Expected Behavior

I expect to see my calendar page load as it always has done previously.

### 👷 Testing

- [ YES ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ YES] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

<Don't know how to do this, and system has been working fine for 9 months.

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |5.3
| Web server (name and version)       |                |
| PHP                                 |         7.4       |
| Browser (name and version)         Chrome, internet Explorer, Opera  |                |
| Operating System (name and version) |       windows 10, android       |
| Database (name and version)      MySql |                |
| Service Pack version                |                |

### ❓ Additional context

My Yetiforce system is hosted by 1and1 Ionos, and has been since I first installed it.

**Comment by davide-alghi** [comment]
Dear @asperitigroup,
as @mariuszkrzaczkowski wrote to you in https://github.com/YetiForceCompany/YetiForceCRM/issues/13518#issuecomment-696591480, you have to provide more info about your problem.
What you provided is not enough to help you.

Please follow @mariuszkrzaczkowski instructions in https://github.com/YetiForceCompany/YetiForceCRM/issues/13518#issuecomment-696591480 and append logs here.

Here how to manage logs: https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging

If you'll not provide those information, nobody will can help you.

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/issues/13518

**Comment by asperitigroup** [comment]
Marius, many thanks for helping me to troubleshoot this problem, I wouldn't have been able to solve it without you suggesting checking php logs - I had to upload phpinfo.php and so found the storage issue.
