### ISSUE TITLE
Como puedo importar un modulo de la version 4.3 a la version 5.3 del yetiforce?

### ISSUE THREAD

**Issue by cristobal82** [YetiForceCompany/YetiForceCRM#13521]
Estoy intentando importar mis módulos de la versión 4.3 a la versión 5.3 alguien tiene una idea de como se hace...

**Comment by davide-alghi** [comment]
Hi @cristobal82,
are you speaking about a **custom entity module**?

YF 4.3 - Migration and exporting:

1. migrate YF 4.3 instance to YF 5.3 version
2. export custom entity module (from migrated instance)
3. export custom module data (from migrated instance)

YF 5.3 - Importing

1. import custom entity module
2. import custom entity module data

**Comment by davide-alghi** [comment]
@cristobal82, alternatively

1. re-create custom entity module in YF 5.3 **exactly as-is** in YF 4.3 instance
2. export the data from the YF 4.3 instance
3. import data into YF 5.3 (just re-created module)

**Comment by cristobal82** [comment]
Hola :-) Gracias por responder, la verdad no me queda claro ya que exporte el modulo desde la versión 4.3 y la intente instalar nuevamente en la versión 5.3 y no deja hacerlo ya que dice que es una versión inferior.

[Example](https://www.youtube.com/watch?v=m1OzK8mCBlY)

**Comment by davide-alghi** [comment]
obviously: your method doesn't work.
please follow one of my procedures - the second one is the fastest

NB: run on an YF 5.3 **test** instance, before import into YF 5.3 **production** instance
