### ISSUE TITLE
[Feature] Webhook to push data to the third-party application

### ISSUE THREAD

**Issue by luongdq** [YetiForceCompany/YetiForceCRM#13526]
Hi Guys,

I'd like to integrate YetiforceCRM to other applications, I've tried to find a feature like webhook but could not.
I think that we can setup a workflow with webhook task.
Do you have an idea to add webhook task in the "Add To Do" task list ?

Thank you,
Luong.

**Comment by mariuszkrzaczkowski** [comment]
Two options:
1. Invoke custom function
https://github.com/YetiForceCompany/YetiForceCRM/search?q=helpDeskChangeNotifyContacts
![image](https://user-images.githubusercontent.com/10198654/93984037-9b85c600-fd83-11ea-87d6-6d9a5504a8ef.png)

2. Create a handler
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Vtiger/handlers/RecordLabelUpdater.php

**Comment by luongdq** [comment]
Thank you for your 2 options, I prefer option "1. Invoke custom function", but I don't know if we can add a task form like this:
![webhook-config](https://user-images.githubusercontent.com/22168846/93989412-15ce3e80-fdb4-11ea-9cd7-f84c94180532.png)

**Comment by mariuszkrzaczkowski** [comment]
there you attach the PHP script and in it you make the connection outside.
There is no ready panel (it would be nice, but there was no one willing to pay for it)
