### ISSUE TITLE
[bug] Invoice does not save all products/services selected

### ISSUE THREAD

**Issue by BasicComputers** [YetiForceCompany/YetiForceCRM#13528]
Hello, When i attempt to create an invoice or a quote and then go to add multiple services or products to the invoice/quote, It will only show one of the products or services once saved but the net and total costs will equal that of all the products selected but they do not appear in the invoice or when it is exported to a PDF. Any help would be appreciated. 

![yetiforce error 1](https://user-images.githubusercontent.com/71788238/94056644-6ed9aa80-fd93-11ea-8537-43c948a3ef44.PNG)

![yetiforce error 2](https://user-images.githubusercontent.com/71788238/94056652-739e5e80-fd93-11ea-8716-4be340f97072.PNG)

**Comment by vovpff** [comment]
Very strange situation...

**Comment by BasicComputers** [comment]
I found out that the issue is related to the update from 4.4 to 5.0, i noticed that once the update was performed that i had to go into the mysql database and change the id of u_yf_finvoice_inventory to crmid in order for invoices to even save without throwing and error but once that change was made I was then unable to view the additional services and products that are added to an invoice. I am thinking that more changes in the mysql database are needed to be made else where as well in order to solve the issue, any ideas?

![yetiforceissuemysql](https://user-images.githubusercontent.com/71788238/95550218-61d8d000-09bd-11eb-9557-4d6b38ddb538.PNG)

**Comment by mariuszkrzaczkowski** [comment]
You just damaged your CRM, without knowing the database structure you better not do it.
Your update did not complete properly, the update package adds new columns and changes data types, if you have no changes, it means that an error occurred.

https://github.com/YetiForceCompany/UpdatePackages/blob/02965af877fc925e5e5bfe16feea160ae1bd159a/YetiForce%20CRM%204.x.x/4.4.0_to_5.0.0/updates/init.php#L644-L682

https://github.com/YetiForceCompany/YetiForceCRM/blob/7af8f184d82f18328fab2fe2d69057d1fadb1007/install/install_schema/scheme.sql#L1844-L1868

Check logs

PS. I recommend updating to a stable version
