### ISSUE TITLE
[Question]  Roundcube Module Problem

### ISSUE THREAD

**Issue by gsportelli73** [YetiForceCompany/YetiForceCRM#13539]
<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

Oh hi there! 😄

I have a question about rouncube
System notify that i must update library after i applied the path on the link
https://github.com/YetiForceCompany/YetiForceCRM/issues/13440
When i try to update to roundcube yeti dosn't update library.
![roundcube_alter](https://user-images.githubusercontent.com/27689602/94231373-2b527e00-ff04-11ea-9195-8bc879532368.PNG)
![update_roundcube](https://user-images.githubusercontent.com/27689602/94231375-2beb1480-ff04-11ea-8e3b-e9ccc8aa5699.PNG)

I try do to update but nothing.
Now i have problem with roundcube configuration, system says "roundcube it is not installed"
![roundcube_configuration](https://user-images.githubusercontent.com/27689602/94231614-a5830280-ff04-11ea-8e9b-e446450ab3f9.PNG)
Thank you

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/94232546-84bbac80-ff06-11ea-9676-9e3bcebb2a20.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/13541
