### ISSUE TITLE
[bug] [PL] Zaokrąglanie wartości brutto

### ISSUE THREAD

**Issue by kamiro16** [YetiForceCompany/YetiForceCRM#13535]
Dzień dobry, 

czy spotkaliście się z problemem zaokrąglania na fakturach? 
System wyrzuca błąd jeśli pojawi się kombinacja cyfr: .075 

Komunikat to: 
Wprowadzono niedozwoloną wartość dla tego typu pola. Nazwa pola: gross, Moduł: FInvoiceCost, Wartość: 2094.075

![1](https://user-images.githubusercontent.com/65873917/94133198-a7938580-fe60-11ea-9985-8c7896dd30e2.png)

**Comment by rskrzypczak** [comment]
Kwestie zaokrągleń już poprawiano. Zweryfikuj czy zjawisko występuje na wersji [developerskiej ](https://gitdeveloper.yetiforce.com/) i [stabilnej](https://gitstable.yetiforce.com/).
