### ISSUE TITLE
[Question] Dodawanie plików w module dokumenty

### ISSUE THREAD

**Issue by acuglewski** [YetiForceCompany/YetiForceCRM#13536]
Dzień dobry,

od niedawna mam zainstalowany system YetiForce. Buduję Bazę Wiedzy i potrzebuję dodać m.in. pliki z szablonami w formacie svg, grafiki psd. Pewnie pojawią się jeszcze inne pliki w inny formatach, które będę chciał dodać.

System nie dodaje jednak takich plików. Co muszę zmienić w konfiguracji by dodawać takie pliki.

-- 
Adam Cuglewski

**Comment by bpabiszczak** [comment]
a w którym miejscu chcesz to dodać dokładnie [prześlij proszę zrzuty ekranu].

**Comment by acuglewski** [comment]
![Przechwycenie obrazu ekranu_2020-10-27_11-20-32](https://user-images.githubusercontent.com/71824800/97291628-7553ba00-184a-11eb-8733-dd1b33784c82.png)

Dodaje nowy dokument

![Przechwycenie obrazu ekranu_2020-10-27_11-22-45](https://user-images.githubusercontent.com/71824800/97291695-8d2b3e00-184a-11eb-8fd8-4dd8584b6183.png)

Wybieram plik z dysku, daję zapisz i dodaje się wpis ale bez załączonego pliku.

Jeśli dobrze rozumiem to nie ma znaczenia gdzie dodaję plik. Dodaję dokument korzystając z modułu dokumenty. Chciał bym móc określić jakie typy plików mogę dodać a jakie nie. 

PS.
Osoba, która pomaga mi w konfiguracji wyłączyła sprawdzanie jakie pliki mogę dodawać ale to nie jest najlepsze rozwiązanie. 

-- 
Adam Cuglewski

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/mimetypes.php

Możesz sprawdzić czy w tutaj znajduje się odpowiedni wpis

**Comment by acuglewski** [comment]
Przepraszam, że dopiero teraz piszę.

Tak sprawdziłem w tym pliku są wpisy dotyczące np. plkiów svg.
