### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by nebula2** [YetiForceCompany/YetiForceCRM#13538]
Is there a date for portal2?
I just tried to get the version from the dev branch to work but i am stuck with "There was an error communicating with the CRM" error. 
Due to the lack of documentation i am not able to figure out at which state this thing is and how to properly set up everything :/

I am running a small business and want to use the portal for incident management.

**Comment by nebula2** [comment]
Hey, it's been 16 days now. is there any chance I get an answer? 
Hard to contribute under these circumstances :/

**Comment by bpabiszczak** [comment]
The customer portal is not finished yet. It will be completed when some customer pays for this.
