### ISSUE TITLE
[bug]  Problem with roundcube 

### ISSUE THREAD

**Issue by gsportelli73** [YetiForceCompany/YetiForceCRM#13541]
# 🐞 bug report

### ⁉️ I go in configuration settings, system notify that roundcube must update.library-
I click to update but system doesn't update.
Now i try to configure roundcube but  system reports that library it isn't installed.

### 🔥 How to trigger the error
It is always presente

1. Go to '...Configuration'
2. Click on '....Minotring Section'
3. Scroll down  '.Roundcune altert'
4. Click to update
5- Click to roundcube configuration and error appearts 
![roundcube_alter](https://user-images.githubusercontent.com/27689602/94233290-f3e5d080-ff07-11ea-9e6b-34b55ce67755.PNG)
![update_roundcube](https://user-images.githubusercontent.com/27689602/94233313-fcd6a200-ff07-11ea-81ba-d7eb0afe546e.PNG)
![roundcube_configuration](https://user-images.githubusercontent.com/27689602/94233335-03651980-ff08-11ea-8fa2-1e1c90b4917a.PNG)

Enviroment OS and Software

Centos 7 con VPS 
PHP 7.3
Mysql 5.7
Browser all

Regards

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/94234587-3dcfb600-ff0a-11ea-8db6-a4b8bb0b562e.jpg)

**Comment by gsportelli73** [comment]
I have restored previus version of version.php in config  on line lib_roundcube


<?php

return [
	/*'appVersion' => '5.3.0',
	'patchVersion' => '2020.03.13',
	'lib_roundcube' => '0.0.87'*/
	'appVersion' => '5.3.139',
	'patchVersion' => '2020.08.04',
	'lib_roundcube' => '0.0.87'
	/* Modifica 25-09-2020 Giuseppe Sportelli */
	//'lib_roundcube' => '0.0.89'
];

Now i try to login with roundcube after config mail server for me and the webmail hangs on login.

**Comment by gsportelli73** [comment]
When i try to configure mailscanner it hangs  login in webmail
in error log i find

[error_log_mailscanner.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/5285009/error_log_mailscanner.pdf)
Thank for attention
Note i have replaced ip and domain for security reason.

**Comment by gsportelli73** [comment]
Hello again
Update if i set imap without tls/ss tcp port 143, login has success.
I'm sure, thath my mail server supports SSL/TLS, because i login with another client without problemi.
Thank for attnetion.
