### ISSUE TITLE
[bug] When I click "Settings" I get an error message.

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#13544]
# 🐞 bug report

### ⁉️ Describe the bug

When I click on the settings button, instead of opening up the first page of the settings, I get the following error message:

![image](https://user-images.githubusercontent.com/58600791/94246563-cd2d9700-ff13-11ea-88d6-4740bd063414.png)

None of the settings menu options work when clicked, my only option is to go back to my home page. All the menu options on the home page work as expected, and I can still schedule activities, add contacts etc.

### 🔥 How to trigger the error

Click on the settings button at the top right of the main YF screen.

### 👍 Expected Behavior

Settings first screen and menu would be activated.

### 👷 Testing

- [YES ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ YES] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
![image](https://user-images.githubusercontent.com/58600791/94246947-55ac3780-ff14-11ea-89db-ef5aa7527018.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

I have turned logging on in debug.php like this:
/** Enable saving logs to file. Values: false/true */
	public static $LOG_TO_FILE = true;

	/** Enable saving logs profiling. Values: false/true */
	public static $LOG_TO_PROFILE = false;

	/** Level of saved/displayed logs. Values: false = All / 3 = error and warning / ["error", "warning", "info", "trace", "profile"] */
	public static $LOG_LEVELS = ["error", "warning", "info", "trace", "profile"];

	/** Level of saved/displayed tracerts. // Values: int */
	public static $LOG_TRACE_LEVEL = 9;

There is one log file that shows todays date, it is cron_error.log

The contents are:

2020-09-25 09:45:08 - syntax error, unexpected ''' (T_ENCAPSED_AND_WHITESPACE), expecting ']'

Which is the same error I am seeing when I click on the settings button.

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3
| Web server (name and version)       |                |
| PHP                                 |   7.4             |
| Browser (name and version)          |   Chrome            |
| Operating System (name and version) |    Windows 10           |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by asperitigroup** [comment]
I also noted that my CalDav cron job does not run, and CalDav Synchronizer reports a sync error.

![image](https://user-images.githubusercontent.com/58600791/94249309-9b1e3400-ff17-11ea-96be-e76f213db05d.png)

This is my CalDav setup, which has worked for the last six months just fine.

![image](https://user-images.githubusercontent.com/58600791/94249424-cb65d280-ff17-11ea-979f-8902903802cd.png)

And when I click Test or Discover settings, I get the same error message as shown in the CalDav log.

![image](https://user-images.githubusercontent.com/58600791/94249561-fa7c4400-ff17-11ea-828c-75d2afe424a2.png)

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by asperitigroup** [comment]
No other recent log files created apart from this one:

[cron_error.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5282023/cron_error.log)

**Comment by mariuszkrzaczkowski** [comment]
no logs, we won't help

**Comment by asperitigroup** [comment]
These are all the log files that are in the cache/logs folder. Please let me know if there is anything else I can provide.

[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5282121/updateLogsTrace.log)
[cron_error.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5282128/cron_error.log)
[Importer.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5282126/Importer.log)
[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5282127/updateLogsTrace.log)

![image](https://user-images.githubusercontent.com/58600791/94256145-3a93f480-ff21-11ea-93ca-3fb4d8f16b11.png)

**Comment by asperitigroup** [comment]
I've got a little bit further. I still cant load the settings page, but I seem to have fixed the CalDav connection problem - it appears from cron.sh in yetiforce/cron that PHP 7.4 is not supported, so I changed my PHP version back to 7.3 and now the connection is successful.

cron.sh -
# ********************************************************************************
export CRM_ROOT_DIR=`dirname "$0"`/..

export USE_PHP=php
#export USE_PHP=/usr/local/php71/bin/php71
#export USE_PHP=/usr/local/php72/bin/php72
#export USE_PHP=/usr/local/php73/bin/php73

cd $CRM_ROOT_DIR

#       TO RUN ALL CORN JOBS
$USE_PHP -f cron.php

And now when I test my CalDav connection I get:
![image](https://user-images.githubusercontent.com/58600791/94271158-24922e00-ff39-11ea-8ac4-7daf2c39e08c.png)

I still get the same error message when I click the settings button however.

[cron_error.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5282957/cron_error.log)

**Comment by asperitigroup** [comment]
2020-09-25 14:00:11 - syntax error, unexpected ''' (T_ENCAPSED_AND_WHITESPACE), expecting ']'

from which file is this error being generated? The above line is from the cron_error.log file and is the same message I get when I click on the settings button.  Can I bypass that error message to get to the settings page? Maybe be editing the debug.php file?

**Comment by rskrzypczak** [comment]
This should fix the problem: https://github.com/YetiForceCompany/YetiForceCRM/commit/b14961d1e19d6b1c10a61777bc288fcd93c21b4c 

Similar threads:
https://github.com/YetiForceCompany/YetiForceCRM/issues/13005  
https://github.com/YetiForceCompany/YetiForceCRM/issues/13251 
https://github.com/YetiForceCompany/YetiForceCRM/issues/13190
