### ISSUE TITLE
YF 5.3 - Dynamic field dependency possible?

### ISSUE THREAD

**Issue by butuemi** [YetiForceCompany/YetiForceCRM#13545]
Hello !

I was wondering if any field relation would be possible without further development, example below: 

- changing a picklist to a certain value makes another filed of the same record required

Thank you!

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=PickListDependency&view=List 
?

**Comment by butuemi** [comment]
Thank you very much, this actually helps me in what I want to do! I don't know how I missed that! 
But is there a possibility to make it required as well? As I see, you can only add Industry and save the record without the need to select a sub-branch. 
Is there a way to, let's say, make "sub-branch" field Required only if Industry has the value "Finance"?

Thank you very much!

**Comment by rskrzypczak** [comment]
`Is there a way to, let's say, make "sub-branch" field Required only if Industry has the value "Finance"?`
No.
The system does not have such functionality by default.
