### ISSUE TITLE
[bug] I just added a workflow and it doesnt work

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13543]
# 🐞 bug report

### ⁉️ Describe the bug

I have been trying to add a workflow in yetiforce and the workflow is not working . The workflow needs to create a new entry whenever the status is changed in sales orders!

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment]
1. ![github](https://user-images.githubusercontent.com/10198654/94400417-64d7f300-0169-11eb-92c5-43e07c4f01ad.jpg)
2. Correct the server configuration first
