### ISSUE TITLE
[Question] How do i fix this server configuration issue?

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13554]
### Description

I am not able to find any configuration file to edit and modify that could solve this problem.
So where are the files for configuring in order to solve this issue . 
ISSUE IS SHOWN IN PICTURE.
![clip](https://user-images.githubusercontent.com/40380541/94361516-8509a280-00d4-11eb-9907-e4fc01db769e.jpg)

**Comment by vovpff** [comment]
You need to tune your webserver and php to solve this!

**Comment by davide-alghi** [comment]
> So where are the files for configuring in order to solve this issue .

HI @rohanjhanepal,
look at **PHP configuraton** (**Additional PHP configuration**) in **_Environment information_**
https://gitstable.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65
You'll find configuration file paths for your server: PHP-<webserver (usually Apache)> and PHP-CLI
As @vovpff said you, you need to tune PHP to cover YF requirements.

**Comment by rioshaz** [comment]
@rohanjhanepal u need a vps server minimum to fix all these issues as many of the settings are controlled by hosting company and are not available in shared hosting,... if u r on vps then go to whm n find php conf file n make changes... the location of ur php conf and database file depend on your server environment and os being used...

**Comment by paula-w** [comment]
This is @bpabiszczak's answer:

Unfortunately there is no single answer that would solve your problem, as it depends on your server configuration (@davide-alghi gave you solid advice). Configuration differs for operating systems (centos, ubuntu, debian), apache and nginx, and databases. If you’re using configuration panels (direct admin, cpanel, etc) then most of the parameters can be configured there. You have to consult your server admin. 

You can also use our hosting or VPS, in this case we take care of proper configuration and provide support:

- [VPS](https://yetiforce.com/en/marketplace/cloud)
- [Hosting](https://yetiforce.com/en/marketplace/hosting-en)
