### ISSUE TITLE
[Question] [PL] Od czego zależy "widoczność" bloku z włączonym przyciskiem: "Włączone dynamicznie"?

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#13552]
W konfiguracji systemu -> moduły-pola jest możliwość ustawienia bloku jako widocznego dynamicznie:
![obraz](https://user-images.githubusercontent.com/62466142/94340818-e7936d80-0004-11eb-919f-55be30b3fb26.png)

Jaki to daje efekt (kiedy jest widoczny, albo od czego to zależy)?
Czy za pomocą tej funkcjonalności jest możliwe pokazywanie bloku w zależności od aktualnego wyboru użytkownika (np. pól słownikowych) podczas edycji rekordu?

**Comment by bpabiszczak** [comment]
Służy do tego, że jeżeli użytkownik na podglądzie rekordu "zwinie blok" to po wyjściu np. na listę i powrocie do dowolnego rekordu blok ten będzie zwinięty [czyli dynamicznie zapamiętuje ostatnie ustawienie użytkownika] i to działa indywidualnie per użytkownik.
