### ISSUE TITLE
[Question] Pole: Rzeczywista sprzedaż

### ISSUE THREAD

**Issue by yetithebest** [YetiForceCompany/YetiForceCRM#13556]
Chciałbym się dowiedzieć z czego jest wyliczane pole rzeczywista sprzedaż, ponieważ nie znalazłem nigdzie tej zależności ani żadnych informacji na ten temat.

![rzeczywista sprzedaz](https://user-images.githubusercontent.com/72019135/94427546-8a77f300-018f-11eb-9c44-b092a3778026.png)

**Comment by bpabiszczak** [comment]
Fajny masz nick ;) Pole to nie jest skonfigurowane ponieważ dopiero na etapie analizy ustalamy z klientem, czy wartość ta wynika z zamówień, z ofert [np. o statusie zaakceptowana] czy może z faktur. Jest to kwestia indywidualna, dlatego domyślnie nie jest to "zautomatyzowane". Zapewne w przyszłości uzależnimy to domyślnie od Zamówień [o statusie zaakceptowane].
