### ISSUE TITLE
MailManager Vtiger

### ISSUE THREAD

**Issue by manuelnice** [YetiForceCompany/YetiForceCRM#13558]
In the MailManager module I have an error in the Drafts folder, when I open it and click on the email it does not open, after inspecting I verified that it has an error in the ID, the id is coming with a prefix, if you remove the prefix no inspect already opens the modal, does anyone know which is the php that sends the id, to see if I can remove the prefix.

**Comment by manuelnice** [comment]
and the search in drafts not work

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/94516206-957d6280-0225-11eb-9f06-9cba95bb338c.jpg)

**Comment by paula-w** [comment]
Vtiger's MailManager was removed from YetiForce years ago. We got rid of it because it had too many vulnerabilities. You can install Roundcube and use it as your email client.
