### ISSUE TITLE
[Question] 2nd installation page is blank and just shows yetiforce logo

### ISSUE THREAD

**Issue by merlinwoff** [YetiForceCompany/YetiForceCRM#13564]
Hi there,

I am trying to setup YetiForce 5.3 on a CentOS 8 linux virtual machine. I followed the installation guide:
https://computingforgeeks.com/install-yetiforce-crm-on-centos-centos-linux/

After setting all the permissions, I am able to access: http://crm.intranet.ch/install/Install.php

The first page shows the language selection and after I click on next step, the page is just blank with a yetiforce-logo as in:
https://github.com/YetiForceCompany/YetiForceCRM/issues/6465

I tried to install YetiForce 5.2 but got the same problem. I tried to run yarn install and composer install but they just generate errors. I also tried to set the debugging to show errors = true (in the php.ini file as well the debugging value for webservices in conf/Debug.php, but no errors are shown / the error log as defined in the /etc/httpd/conf.d/yetiforce.conf is non-existant.

What am I doing wrong? What information do you need to help me?

Thank you very much!

Best,
Merlin

**Comment by mariuszkrzaczkowski** [comment]
Run this file via WWW and send us file ConfReportTest_www.html
https://github.com/YetiForceCompany/YetiForceScripts/blob/master/TestRequirements/ConfReportTest.php

**Comment by PatriceKast** [comment]
When I run it by opening the url in my browser, I get:
`<h2>Errors:</h2><pre>`

If I run in on commandline, I get the following output:
```
[root@crm yetiforce]# php ConfReportTest.php
PHP Fatal error:  Uncaught yii\base\InvalidConfigException: Connection::dsn cannot be empty. in /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php:610
Stack trace:
#0 /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php(1015): yii\db\Connection->open()
#1 /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php(1002): yii\db\Connection->getMasterPdo()
#2 /var/www/html/yetiforce/app/Db.php(149): yii\db\Connection->getSlavePdo()
#3 /var/www/html/yetiforce/app/Utils/ConfReport.php(477): App\Db->getInfo()
#4 /var/www/html/yetiforce/app/Utils/ConfReport.php(430): App\Utils\ConfReport::init('all')
#5 /var/www/html/yetiforce/app/Utils/ConfReport.php(416): App\Utils\ConfReport::getByType(Array, true)
#6 /var/www/html/yetiforce/app/Utils/ConfReport.php(1392): App\Utils\ConfReport::getAll()
#7 /var/www/html/yetiforce/ConfReportTest.php(29): App\Utils\ConfReport::getAllErrors()
#8 {main}
  thrown in /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php on line 610
<h2>Errors:</h2><pre>
```

**Comment by merlinwoff** [comment]
When I run it by opening the url in my browser, I get:
`<h2>Errors:</h2><pre>`

If I run in on commandline, I get the following output:
```
[root@crm yetiforce]# php ConfReportTest.php
PHP Fatal error:  Uncaught yii\base\InvalidConfigException: Connection::dsn cannot be empty. in /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php:610
Stack trace:
#0 /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php(1015): yii\db\Connection->open()
#1 /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php(1002): yii\db\Connection->getMasterPdo()
#2 /var/www/html/yetiforce/app/Db.php(149): yii\db\Connection->getSlavePdo()
#3 /var/www/html/yetiforce/app/Utils/ConfReport.php(477): App\Db->getInfo()
#4 /var/www/html/yetiforce/app/Utils/ConfReport.php(430): App\Utils\ConfReport::init('all')
#5 /var/www/html/yetiforce/app/Utils/ConfReport.php(416): App\Utils\ConfReport::getByType(Array, true)
#6 /var/www/html/yetiforce/app/Utils/ConfReport.php(1392): App\Utils\ConfReport::getAll()
#7 /var/www/html/yetiforce/ConfReportTest.php(29): App\Utils\ConfReport::getAllErrors()
#8 {main}
  thrown in /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php on line 610
<h2>Errors:</h2><pre>
```

**Comment by mariuszkrzaczkowski** [comment]
Send full logs from the server

**Comment by merlinwoff** [comment]
I just managed to solve the issue. I had selinux turned on. After disableing it, it worked!

Thank you.

Cheers,
Merlin
