### ISSUE TITLE
create entity workflow not working

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13566]
i am unable to create an entity via WF. 

once a ticket status has changed it should create a lead.

Have already mapped tickets to lead and but create entity doesnt work.

WF----> tickets---> everytime a record is saved -----> condition (1. status has changed,  2. status has changed to approved)---> create entity---> get mapping from panel---> finished

but this flow doesn't work,.,,, what is wrong here...

YF is 5.3

have tested the same on gitstable version too its doesn't work..

please tell me what am i doing wrong..

is it  possible to have an WF for generate record ? 
is generate record comes under  modiying a record ?

please help.

**Comment by apcloic** [comment]
@rioshaz Hi, did you make sure that the mapping include all required fields ?

**Comment by rioshaz** [comment]
@apcloic  thanks a million that helps...

**Comment by rioshaz** [comment]
after upgrade to 6.0 from 5.3 .. all my workflows are not wotking... @mariuszkrzaczkowski  @apcloic  is ther enay fix you can just
