### ISSUE TITLE
Tickets to show in calendar PLEASE!

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#13579]
Hello all! Hope everyone is doing great.

After using Yetiforce for a year, we found that it is extremely inconvenient that there is no way to show tickets in the calendar. Even if it's just the Yetiforce built in calendar. Without this feature, you have to constantly go through open tickets, sort them by date etc. There is just got to be a way to view them in the calendar. It's just a basic essential feature for any schedule based platform. We might have to move away to a different platform because of that. 

Let me know if it will be possible any time soon.

**Comment by rskrzypczak** [comment]
I don't know what your problem is. You can add a workflow action that adds a calendar entry along with the ticket.
![image](https://user-images.githubusercontent.com/10221999/94890187-e6d45e80-047e-11eb-9d84-42d3d368f2da.png)

**Comment by davide-alghi** [comment]
Dear @acoolov,
it's not clear what the problem is.

1) do you need to "attach" a ticket to calendar event? (in this case @rskrzypczak gave you a solution, above)
2) or ... do you need a calendar in Tickets module?

**Comment by paula-w** [comment]
This is @bpabiszczak ’s answer:

Unfortunately I don’t understand why you want to see tickets in the calendar? I can’t think of any reason for that. Why do you have to sort anything (why isn’t it sorted by default?), why do you have to go through open tickets (why the ones that you need to take care of aren’t on top, and the ones that are waiting for clients’ replies at the bottom?). You’re most likely not taking advantage of the potential that the system offers you. If you really need the calendar then you have a calendar in tickets. If you add anything in there it will be visible in the calendar. 

We implemented the tickets module for 50 clients and none of them needed to display tickets in the calendar.

**Comment by waran70** [comment]
> We might have to move away to a different platform because of that.

Feel free boy. Run!

**Comment by acoolov** [comment]
> This is @bpabiszczak ’s answer:
> 
> Unfortunately I don’t understand why you want to see tickets in the calendar? I can’t think of any reason for that. Why do you have to sort anything (why isn’t it sorted by default?), why do you have to go through open tickets (why the ones that you need to take care of aren’t on top, and the ones that are waiting for clients’ replies at the bottom?). You’re most likely not taking advantage of the potential that the system offers you. If you really need the calendar then you have a calendar in tickets. If you add anything in there it will be visible in the calendar.
> 
> We implemented the tickets module for 50 clients and none of them needed to display tickets in the calendar.

All of the equestions you ask almost make no sense. Why would I use a system where I can't even layout all my support and service tickets in the calendar? Because it is so much easier if they all show in one calendar, where you can just see your whole month schedule. It seems like you're trying to force your personal understanding of how things should work onto everyone that is using this platform. Having one calendar that can show everything is way more convenient than constantly trying to sort out the tickets in the list view. We have many tickets scheduled for different people for different days in a week. Try not to force your understanding onto other people.

**Comment by acoolov** [comment]
> Dear @acoolov,
> it's not clear what the problem is.
> 
> 1. do you need to "attach" a ticket to calendar event? (in this case @rskrzypczak gave you a solution, above)
> 2. or ... do you need a calendar in Tickets module?

Thanks for suggesting a solution. It might work okay on ticket creation but if we change the ticket schedule, or delete the ticket, would there be a way to modify the corresponding event?

**Comment by mariuszkrzaczkowski** [comment]
Everything is possible, there are many ways, but who will pay for it, it is not easy and quick to do to make sense

**Comment by davide-alghi** [comment]
Hi @acoolov,
if I understand your need, it's to relate one or more calendar activities to ticket and, vice versa, a calendar activity must be related to a single ticket.
I suppose that, for each ticket, you have a start day/time and duration.

If this is right, we're able to create, via workflow and mapping, a new calendar activity related to ticket.
But here the first problem: how to, correctly, create a calendar activity avoiding calendar activity overlapping? So if you need schedule ticket on calendar, you must set calendar activity by calendar, by hand, and relate the just created calendar activity to the ticket.

The same problem is about ticket changing: schedule changing must be done on Calendar.
Pls give us some specs: we can try to understand together.

===========================================================

If I am allowed, I would like to say a few words about what software should and shouldn't do.
It's just my point of view, I don't want to defend or accuse anyone and I ask, kindly, not to misinterpret my words.

There are no specs on what a CRM should or shouldn't do. Certainly there are common structures and common features that all CRMs have.
Likewise, every company has common needs and custom needs.
We always keep in mind that we are in the Open Source context: what the community uses has no cost; on the other hand, the community offers a (very important) support / debugging service.

When choosing an important (and central) tool like a CRM, I need to have detailed specs on "AS-IS" and "TO-BE".
In my personal experience, the choice of CRM can take 4-6 months (just to choose) for a SME. I repeat: with detailed specs.
Once the CRM has been chosen, a demo is raccomended to simulate both the "AS-IS" and the "TO-BE".
Does this seem like a waste of time? No, not at all. It reduces the error margin in the future, although some adjustments will still need to be made.
If, in production, I realize that the CRM does not satisfy some of my needs, there are two cases: I did not include the features in the specifications, or I didn't check enough that the specs were met.
In any case I can't blame the software. The software is there to see, to use and to try. If, in production, I realize that I can't do something, or I can't do it exactly as I want, the responsibility is mine alone.

**Comment by mariuszkrzaczkowski** [comment]
A lot can be done, but the question is who will pay for it. There is one example that came to my mind quickly.
Create a new view in the module (near the record list, list with preview) which presents records in the form of a calendar if date fields are configured to show entries.
You can do the Kaban chart view and much more but the problem will be still the same...
