### ISSUE TITLE
Problema al crea run informe

### ISSUE THREAD

**Issue by cristobal82** [YetiForceCompany/YetiForceCRM#13589]
Quisiera saber como solucionar el siguiente problema mostrado en el video a continuación.

[example error](https://youtu.be/pta5JiNef1M)

**Comment by vovpff** [comment]
О чем речь?

**Comment by davide-alghi** [comment]
Hi @cristobal82,
please report your issue in English and fill out the Bug Report template in its entirety.

![YetiForceCRM-BugReportTemplate](https://user-images.githubusercontent.com/48508691/94989489-86741880-0575-11eb-8703-279d31bec638.jpg)

**Comment by bpabiszczak** [comment]
yetiforce 1.1.1????????????????????
