### ISSUE TITLE
[bug] syntax error, unexpected ''=>'' (T_CONSTANT_ENCAPSED_STRING)

### ISSUE THREAD

**Issue by melboss** [YetiForceCompany/YetiForceCRM#13588]
I've installed YetiForce. When I go to settings, I keep getting this error and cannot access any settings unfortunately. Has anyone had a similar issue and knows the fix please?

<img width="1213" alt="Screenshot 2020-10-02 at 16 20 24" src="https://user-images.githubusercontent.com/5950450/94934109-96372280-04cb-11eb-8c77-3bac04d06e8c.png">

**Comment by bpabiszczak** [comment]
system version, configuration, application logs??

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13005
