### ISSUE TITLE
[Question] There is an API docs more complete than swagger ones?

### ISSUE THREAD

**Issue by gianfabiopezzolla** [YetiForceCompany/YetiForceCRM#13583]
Hi there,

I'm new to yetiForce, and I need to integrate it with third party app.

I've seen your swagger API docs, and I've notice that is in progress... have you some resources with a more complete API or I need to use [this one](https://doc.yetiforce.com/api/#/BaseModule/Api)?

thanks in advance

**Comment by rskrzypczak** [comment]
There is nothing else

**Comment by mariuszkrzaczkowski** [comment]
Documentation "https://doc.yetiforce.com/api" is generated from the development version code.
Not all api methods have been documented yet so you can see https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/api/webservice/Portal
