### ISSUE TITLE
Open RSS Links In New Tab

### ISSUE THREAD

**Issue by sherazkhan1988** [YetiForceCompany/YetiForceCRM#13590]
Hi,

   I hope you are all healthy and well.

   I am trying to find a way so when I click on rss feed links in myhomepage in Yetiforce 4.4, it opens the link in a new tab.

  How can I do that?

  Any help would be very much appreciated.

Thank You.

**Comment by bpabiszczak** [comment]
4.4? 
https://superuser.com/questions/195419/google-chrome-is-there-a-keyboard-shortcut-to-open-a-link-in-a-new-tab
