### ISSUE TITLE
[bug] I am getting "Exceeds the maximum text size in bytes 65535" when adding image in text field

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13597]
# 🐞 bug report

### ⁉️ Describe the bug

When adding images on text editors, it returns the message: "Exceeds the maximum text size in bytes 65535".
See the red warning pop up

![Screenshot (46)](https://user-images.githubusercontent.com/40380541/95073413-8cf8c080-072c-11eb-9178-317e3b76e8b8.png)

### 🔥 How to trigger the error

1. Go to Database>Documents
2. Click on Add  record
3. Click on text field and add a image there
4. Then click save
5.See the error

### 👎 Actual Behavior

it returns the message: "Exceeds the maximum text size in bytes 65535".
### 👍 Expected Behavior
it should save image in text field

it should save image in text field
### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3.0
| Web server (name and version)       |                |
| PHP                                 |         7.3       |
| Browser (name and version)        googlechrome  |        85        |
| Operating System (name and version) |       WIndows 10         | 2020
| Database (name and version)         |        SQL        |
| Service Pack version                |                |

### ❓ Additional context

![ConfReport](https://user-images.githubusercontent.com/40380541/95073195-21aeee80-072c-11eb-8650-1e8bc3bd25b9.png)

**Comment by vdpawel** [comment]
it's not a bug
#13002

**Comment by rohanjhanepal** [comment]
How do i fix it? #13002 was no help for me. Where and what should i change to get it working?
