### ISSUE TITLE
 Error when adding a module to the home page settings

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#136]
EXAMPLE: If the Settings page, in the left pane Integrtsiya, select the customer portal and click on the button to attach, then the module is attached, and if you select in the left pane, Web Forms, then attach the button does not work.
WORK
![attache error](https://cloud.githubusercontent.com/assets/1402355/5934212/c2e3e30a-a6ed-11e4-87da-856da1208fdb.jpg)

DON'T WORK

![attache error 2](https://cloud.githubusercontent.com/assets/1402355/5934214/d5b2e094-a6ed-11e4-8e0d-1a46bc759551.jpg)

**Comment by konadrian** [comment]
Tested on version 1.2.51 RC, pins work fine on Chrome and Firexof. If the problem still exists, we need more specific information, such as: ajax logs from your browser, but the best solution will be to create a testing environment and give us access to it so we can test it ourselves.
