### ISSUE TITLE
[Question] Uprawnienia do magazynu/WZ

### ISSUE THREAD

**Issue by mateuszrudyk** [YetiForceCompany/YetiForceCRM#13607]
Witam.
Jak ustawić uprawnienia, aby podczas wystawiania WZ użytkownik mógł wybrać tylko magazyn/magazyny, którego jest właścicielem rekordu?

**Comment by bpabiszczak** [comment]
Ustawić magazyny jako prywatne i przydzielić go do tego magazynu do którego może mieć uprawnienia.
