### ISSUE TITLE
[bug] Duplicated entry when creating a record

### ISSUE THREAD

**Issue by Patriciawa** [YetiForceCompany/YetiForceCRM#13617]
# 🐞 bug report

### ⁉️ Describe the bug

When adding a record for a custom module (module built via the module builder) the entry appears twice (duplicate). This only happens when a Workflow is triggered and invokes a custom function.

### 🔥 How to trigger the error

Create a record in the custom module.

See GIF;

![duplicatentry](https://user-images.githubusercontent.com/49994443/95367919-a9842c80-08d5-11eb-985d-51be9d851718.gif)

1. Create a (basic) custom module,.
    1a. add some fields.
    1b. Create a custom function for the module for the Workflow.
    1c. Add the following code;
```
class myClass
{
	public function myFunction(Vtiger_Record_Model $recordModel)
	{
	$recordModel->setHandlerExceptions(['disableWorkflow' => true]);
	$recordModel->save();
   }
}
```
As you can see it's empty, it doesn't matter if i put some code in or not, when calling the function it creates a duplicate entry. When I disable the workflow I can the create the record just fine.

2. Create a workflow.
   1a. Select the option to only execute when a record has been created
   1b. In the 'Add tasks' menu from the workflow, select 'invoke custom function' and choose the function.
   1c. Save.
In my case, i've already added the function to the CRM, with the help of [this issue.](https://github.com/YetiForceCompany/YetiForceCRM/issues/10667) This works fine, I can see that the function gets executed, no problem on that part.

### 👎 Actual Behavior

Two entries instead of one

### 👍 Expected Behavior

One entry.

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
![ConfReport (1)](https://user-images.githubusercontent.com/49994443/95368073-e3edc980-08d5-11eb-9328-98f4411510f0.png)
Note: When changing `opcache.interned_strings_buffer` to 100, my server I am getting a 502 error, PHP produces the following output; `(10301): Fatal Error Zend OPcache cannot allocate buffer for interned strings`
Note: I've tried to change header in the example config, found [here.](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/nginx/vhost.conf) However, this has been made for Lua Nginx(?) nginx doesn't recognize line 20 to 30 (where the headers are set)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Please let me know if I need to send some logs.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | YetiForce CRM 5.3 
| Web server (name and version)       |   nginx/1.14.2             |
| PHP                                 |     7.2.33            |
| Browser (name and version)          |    Latest Chrome stable and Edge Stable            |
| Operating System (name and version) |         Windows 10 Pro       |
| Database (name and version)         |          10.3.17-MariaDB-0+deb10u1 - Debian 10      |
| Service Pack version                |     v4            |

### ❓ Additional context

PHP.ini has been copied from [here](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/php/prod.ini)

Best regards,

Patrick

**Comment by davide-alghi** [comment]
Hi @Patriciawa,
I just tested, on my YF 5.3.0 instance, but everything works fine, both built-in and custom modules. I cannot reproduce the issue.

1. about **opcache.interned_strings_buffer**: set it to lower value than 100. Maybe your server haven't got enough resources.
2. about **webserver headers**: that is not so easy to set, anyway it has no implications with your issue

Your logs are essential.

1. disable (temporarily) the chat module, in Standard modules / Modules – Installation
2. set (temporarily) CRON execution to 5 minutes or more
3. in config/Debug.php set
   - $LOG_TO_FILE = true;
   - $LOG_LEVELS = false;
4. reset contents for the files:
   - cache/logs/system.log
   - php_errors.log
5. create a new record by your custom module
6. check if record is duplicated
7. upload here the files
   - cache/logs/system.log
   - php_errors.log

**Comment by Patriciawa** [comment]
Hi @davide-alghi 

Apologies for not saying earlier, the following has to be in the function in order to trigger the duplicate;
```
	$recordModel->setHandlerExceptions(['disableWorkflow' => true]);
	$recordModel->save();
```

Anyway here's the log, I've redacted some info. I couldn't find a php_errors.log in one of YetiForce's directories. I could find one in my `/var/log` but it was empty.

Here's the log:

[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5348063/system.log)


Screenshot of duplicated records;


![image](https://user-images.githubusercontent.com/49994443/95463850-932fac80-0979-11eb-8dcb-e6557ebc030d.png)

Best regards,

Patrick

**Comment by davide-alghi** [comment]
ah ok, now is clear. it is not a bug.
if you put

```PHP
	$recordModel->setHandlerExceptions(['disableWorkflow' => true]);
	$recordModel->save();
```
what it happens:
1. you create a new record by GUI
2. then you save it
3. YF saves the new record, but the record is marked as new
4. the YF execs your workflow task: where you are saving (again) the record (still marked as new), so the second one (copy) is created

if you have to change values into record (and then save it), you have to work on one $recordModel clone

NB if you have to save, it's mandatory to avoid looping by

```PHP
$recordModel->setHandlerExceptions(['disableWorkflow' => true]);
```

**Comment by davide-alghi** [comment]
here how to manage record into workflow task

https://github.com/YetiForceCompany/YetiForceCRM/blob/8df9aaf68d2a5c0f9ad8e82838f6272ae3b1de29/modules/com_vtiger_workflow/tasks/VTUpdateFieldsTask.php#L29

**I.E.**

```CODE
$recordModel = \Vtiger_Record_Model::getCleanInstance($rawRecordModel->getModuleName());
$recordModel->setData($rawRecordModel->getData());
$recordModel->ext = $rawRecordModel->ext;
$recordModel->isNew = false;

// here your operations

$recordModel->setHandlerExceptions(['disableHandlerClasses' => ['Vtiger_Workflow_Handler']]);
$recordModel->save();
```

**Comment by Patriciawa** [comment]
@davide-alghi 

Many thanks for your response. Adding `$recordModel->isNew = false;` did the trick.

**Comment by Patriciawa** [comment]
@davide-alghi Do you know by chance how I can get the data from, for example, the Contacts module and place that data in a other module via a custom function?

**Comment by davide-alghi** [comment]
if I'm not mistaken, Vtiger_Record_Model has everything you need. on Monday I'll check

**Comment by davide-alghi** [comment]
Hi @Patriciawa,
I confirm. Vtiger_Record_Model class provides all you need.

create a new record
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L659

get a record
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L686

get entity field (field model)
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L451

set entity field value
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L67

set inventory data
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L1282

get inventory data
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L1185

save record
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L488

delete record
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L625

**Comment by Patriciawa** [comment]
Hi @davide-alghi,

Thanks, I was struggling to find this. I currently have the following in the method, for creating a record;

```
$moduleName = 'Accounts';
$focus = CRMEntity::getInstance($moduleName);
$module = Vtiger_Module_Model::getInstance($moduleName);
$modelClassName = Vtiger_Loader::getComponentClassName('Model', 'Record', $moduleName);
$instance = new $modelClassName();
$instance->setModuleFromInstance($module);
$instance->isNew = true;
$instance->setData($focus->column_fields);
$instance->setEntity($focus);
\App\Cache::staticSave('RecordModelCleanInstance', $moduleName, clone $instance);
return $instance;
```

My guess is that you can set the data in the following line: `$instance->setData($focus->column_fields);`

But how can I achieve this?

Thanks,

Patrick

**Comment by davide-alghi** [comment]
Hi @Patriciawa,
sorry but I cannot understand what your code is trying to do. It seems it's turning around to empty data :(
Are you trying to copy data from a record to another record?
```CODE
...
$accCrmId = <crmid account> // source record - int
$contCrmId = <crmid contact> // target record - int
...
$sourceRecordModel = Vtiger_Record_Model::getInstanceById($accCrmId);
$targetRecordModel = Vtiger_Record_Model::getInstanceById($contCrmId);
...
$sourceFieldValue = $sourceRecordModel->get($sourceFieldName);
$targetRecordModel->set($targetFieldName, $sourceFieldValue);
...
$targetRecordModel->save();
...
```

**Comment by Patriciawa** [comment]
Hi @davide-alghi,

Apologies for not clarifying. I'm trying to create a record. Thanks for the example above!

**Comment by crawe1** [comment]
Hi,
@davide-alghi 
How can I _create_ and _edit_ in one "custom function" in workflow ?
edit it's simple, enough add
$recordModel->setHandlerExceptions(['disableHandlerClasses' => ['Vtiger_Workflow_Handler']]);
$recordModel->isNew = false;
but when i want to create new record ? are there any check functions ?

**Comment by davide-alghi** [comment]
Hi @crawe1,
I'm, not sure I understand: do you wanna create a new entity record from scratch?
- get a clean instance of target module (new record):
```$myNewRecordModel = $recordModel->getCleanInstance($targetModuleName)```
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L659
- set entity values
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L67
- set lineitems (if it's an inventory entity)
https://github.com/YetiForceCompany/YetiForceCRM/blob/1006f9e4e8ff735283206df30717292718afcc99/modules/Vtiger/models/Record.php#L1282
- prevent loop
```$myNewRecordModel->setHandlerExceptions(['disableHandlerClasses' => ['Vtiger_Workflow_Handler']]);```
- save the new record
```$myNewRecordModel->save();```

**Comment by crawe1** [comment]
@davide-alghi 
I want to create in workflow, custom function that will be create new record or edit old. But i dont want to create twice custom function but one.
When i create record in module i want to joint other variable from related module to one. But how to create universal custom function to edit and create new record?

**Comment by davide-alghi** [comment]
in any case you have a saved record into your workflow:
- on creation YF saves new record before pass to your workflow code and ```isNew``` attribute is ```true```
- on modifying YF saves old record before pass to your workflow code and ```isNew``` attribute is ```false```

Is your need similar to "Update Related Record" workflow task. but does it reverse?
Maybe you need to get data from related record (child record) and store data into some fields of parent record?
_parent record is the one you are creating / modifying by YF GUI_

1) get the id of related record
```$relatedRecordId = $parentRecordInstance->get('fieldName');```
_get function comes from \App\Base class_
2) get instance of related record by id
```$relatedRecordInstance = $parentRecordInstance->getInstanceById($relatedRecordId);```
3) get value(s) from related record and store into parent record target field(s) - _use get and set functions_
4) prevent loop
```$parentRecordInstance->setHandlerExceptions(['disableHandlerClasses' => ['Vtiger_Workflow_Handler']]);```
6) set **always**
```$parentRecordInstance->isNew = false;```
5) save parent record
```$parentRecordInstance->save()```

**Comment by crawe1** [comment]
How can I know in YF if a record is new or edited in a workflow? then he will be able to write the condition  on my custom function $ recordModel-> isNew = false; or $ recordModel-> isNew = true;
:)

**Comment by davide-alghi** [comment]
> How can I know in YF if a record is new or edited in a workflow?

simply check $recordModel->isNew
```
if ($recordModel->isNew) {
    // it's a creation
} else {
    // it's an editing
}
```

> then he will be able to write the condition on my custom function $ recordModel-> isNew = false; or $ recordModel-> isNew = true;

sorry, what does this mean? I don't understand :(

**Comment by crawe1** [comment]
@davide-alghi 
I have a one Coustom Function in workflow when create or edit records in module. 
for example:
`

class FInvoiceWorkflowClass
{
function FInvoiceWorkflow(Vtiger_Record_Model $recordModel)
{

	$relatedModuleName1 = 'Kontabankowe';
	$recordId1 = $recordModel->get('faktury_konto');
	$relRecordModel1 = Vtiger_Record_Model::getInstanceById($recordId1, $relatedModuleName1);

	$komtowar = $recordModel->get('faktury_komtowar');
        $recordModel->set('faktury_kontoswift', $komtowar);

$recordModel->setHandlerExceptions(['disableWorkflow' => true]);
$recordModel->isNew = false;
$recordModel->save();
}
}
`
![image](https://user-images.githubusercontent.com/61950059/105156685-7411f080-5b0c-11eb-9ef6-7e77103d282b.png)

i want to use function for edited for old record and created record for new rocord. 
When use - `$recordModel->isNew = false; ` - not working for add new record, not duplicate record but its only when i edit records.

When use - `$recordModel->isNew = true; ` -> duplicate records

**Comment by davide-alghi** [comment]
Are you trying to create a custom task for workflow?
Is "FInvoiceWorkflowClass"  the new workflow tasks?
is the containing php file into ```modules/com_vtiger_workflow/tasks``` folder?
and did you added this custom task in com_vtiger_workflow_tasktypes table?

If all replies are 'Yes', please paste here full file code, so it is easier to understand, or attach it.

**Comment by crawe1** [comment]
4 x yes 
you can try add new workflow task (create (for new and edit task) and in your custom functions add this and tell me if you duplicate entry ?

class <yourclasname>Class
{
function <your function name>(Vtiger_Record_Model $recordModel)
{

$recordModel->set('<name of text field_name>', "testtesttest");   

$recordModel->setHandlerExceptions(['disableWorkflow' => true]);
$recordModel->isNew = false;
$recordModel->save();
}
}
when you add this please create new record in module and tell me if you have twice duplicate, but see it in module database table.

**Comment by crawe1** [comment]
![image](https://user-images.githubusercontent.com/61950059/105260538-3e155080-5b8e-11eb-8447-efc0d053cc12.png)
the custom function works when editing record but it doesn't work anymore when creating a new record, why?


---------------------------------------------




when creating a new one (workflow task only for create new):
![image](https://user-images.githubusercontent.com/61950059/105260474-25a53600-5b8e-11eb-9c10-5d7c4ef2aa51.png)
If I set $ recordModel-> isNew = true; duplicates the record (the first is empty, the second is fine) but
If I set $ recordModel-> isNew = false; I create a record without custom function.





-----------------------------------------





![image](https://user-images.githubusercontent.com/61950059/105260581-538a7a80-5b8e-11eb-84ea-f10064af7c56.png)
But if i change (workflow taks on force by user) everything works fine.

**Comment by davide-alghi** [comment]
Hi,
in my previous example I already showed you to use a clone.
```
public function doTask($rawRecordModel)
	{
		$recordModel = \Vtiger_Record_Model::getCleanInstance($rawRecordModel->getModuleName());
		$recordModel->setData($rawRecordModel->getData());
		$recordModel->ext = $rawRecordModel->ext;
		$recordModel->isNew = false;
...
```
start from here
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/com_vtiger_workflow/tasks/VTUpdateFieldsTask.php
and change only filename and classname (adjust values in com_vtiger_workflow_tasktypes table)
after change code about your needs.

PS "fieldValueMapping" are values from configuration GUI of task: maybe you can drop all about fieldValueMapping

**Comment by crawe1** [comment]
its amazing !
Think u so mutch !!! works well with create and edit.

**Comment by crawe1** [comment]
hi @davide-alghi 
I have a only one question tell me if it possible automatically create record every 5 minutes ? i create simple custom function and add to handler according to picture and simple code but now working with time shedulers.
I want to do raport automaticly generated.
![image](https://user-images.githubusercontent.com/61950059/109885178-62c91180-7c7e-11eb-8678-c3fbe1d6b851.png)

class RaportMagazynowyWorkflowClass
{
`	function RaportMagazynowyCyklicznyWorkflow(Vtiger_Record_Model $recordModel)
	{
		$recordModel = \Vtiger_Record_Model::getCleanInstance('RaportMagazynowy');
		$recordModel->isNew = true;

		$recordModel->setHandlerExceptions(['disableWorkflow' => true]);
		$recordModel->save();
	}
}`

**Comment by davide-alghi** [comment]
Hi @crawe1,
> I have a only one question tell me if it possible automatically create record every 5 minutes ?

it could but not exactly. Why do I say «it could»?

workflow task(s) frequency execution depends on

1. crontab frequency configuration
![Schermata da 2021-03-04 09-15-03](https://user-images.githubusercontent.com/48508691/109932727-de50b000-7cca-11eb-9fa7-31c77a9549e5.png)
2. "Workflow" cron-job frequency configuration
![Schermata da 2021-03-04 09-15-47](https://user-images.githubusercontent.com/48508691/109932737-e14ba080-7cca-11eb-8eb9-fe98de00ffae.png)
3. "Execution frequency" in "Execution schedule" (the one in your image: 5 mins)

**Premise**: it isn't recommended to set [crontab frequency to 1 minute] and ["Workflow" cron-job frequency to 1 minute] because there is a **very likely risk of overloading the server**

anyway ... some examples help.
____________________________
Suppose to set

- crontab frequency to 1 minute
- "Workflow" cron-job frequency to 1 minute

what it happens:
- web-server cron runs and call YF cron.php (after 1 minute from previous call)
- cron.php tries to run "Workflow" cron-job => it checks last running => have passed 59 secs => cron.php doesn't exec "Workflow" cron-job

surely "Workflow" cron-job will be executed on next web-server cron running: so "Workflow" cron-job is executed, approximately, after 2 minutes
____________________________
Another example including our workflow. Suppose to set

- crontab frequency to 1 minute
- "Workflow" cron-job frequency to 1 minute
- "Execution frequency" in "Execution schedule" to 5 minutes (like in you image)

this means that before the our workflow is run, they are required, at least, 5 crontab calls (cycles)

suppose we are on 5th call of crontab, what it happens:
- web-server cron runs and call YF cron.php
- cron.php tries to run "Workflow" cron-job => it checks last running => have passed 59 secs => cron.php doesn't exec "Workflow" cron-job (obviously our workflow is not executed)
- web-server cron runs and call YF cron.php
- cron.php execs "Workflow" cron-job
- "Workflow" cron-job checks last running of our workflow => have passed 4:59 mins => "Workflow" cron-job doesn't exec our workflow
- on next crontab calls, surely, our workflow will be executed, but about 7 minutes have passed since the previous execution

this means that real execution frequency is between
5 < execution frequency < 7
where 7 = 1 + 1 + 5
1 => crontab frequency
1 => "Workflow" cron-job frequency 
5 => "Execution frequency" in "Execution schedule"

this in the best condition

but, I repeat, set crontab frequency and "Workflow" cron-job frequency  to 1 minute is not recommended because due to the risk of overloading the server and get the exact opposite result.

**Comment by crawe1** [comment]
Hi @davide-alghi 
Ok i got it but tell me why duplicate my records:
show it on screen:
![image](https://user-images.githubusercontent.com/61950059/110117836-b8ee9f80-7db9-11eb-9756-f6c397e4b22c.png)
1st record must manual add (if i not add system not create new records but why ?),
2nd next 5 min later - system add 2 records by cron 5 minutes workflow task u can see system duplicate records
3rd next 5 min later - system add 6 records by cron 5 minutes workflow task u can see system duplicate records
but if table is empty system not add any record why ?
custom function is upper but its simple function mus created static records

	public function RaportMagazynowyCyklicznyWorkflow(Vtiger_Record_Model $recordModel)
	
	{
			
		$recordModel = \Vtiger_Record_Model::getCleanInstance('RaportMagazynowy');
		$recordModel->isNew = true;
		$recordModel->set('subject', 'test');

		$recordModel->setHandlerExceptions(['disableWorkflow' => true]);
		$recordModel->save();
	}
