### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13629]
### Description

I want to fix this:
 below are two pictures showing the issue.
 When in preview mode , some random HTML elements appear, how do i fix  it?
Look at the article/Introduction section
![Screenshot (49)](https://user-images.githubusercontent.com/40380541/95711072-bf04a800-0c81-11eb-85ea-bb4437c0bab4.png)

In preview mode:
![Screenshot (50)](https://user-images.githubusercontent.com/40380541/95711077-c3c95c00-0c81-11eb-8b22-141dd9cd6ab6.png)

i am using yetiforce 5.3.0

**Comment by mariuszkrzaczkowski** [comment]
You do not have a registered system

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/95711864-f06e7b00-0c63-11eb-8f87-a709c76ee757.jpg)
