### ISSUE TITLE
[Question]  Comment widget, in new module?

### ISSUE THREAD

**Issue by MixTecnico** [YetiForceCompany/YetiForceCRM#13625]
![widget-comentarios](https://user-images.githubusercontent.com/29989839/95625349-bbd5a600-0a4e-11eb-8187-4e1d4dce4ff1.png)

Could you tell me how to add the comments widget in a new module

![widget-comentarios2](https://user-images.githubusercontent.com/29989839/95625872-9c8b4880-0a4f-11eb-9757-2ee07cccc47c.png)

What should I enable to view comments in summary widget??

**Comment by davide-alghi** [comment]
Hi @MixTecnico,
you can't. You need an extension (to develop).
pls take a look at https://github.com/YetiForceCompany/YetiForceCRM/issues/10626
