### ISSUE TITLE
Update value of fields automatically

### ISSUE THREAD

**Issue by jjbautist1** [YetiForceCompany/YetiForceCRM#13637]
🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

How to update the product price in the calculation list automatically?
When a calculation is already set up and I change the price of a product it is not automatically updated.
Help!

🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

**Comment by bpabiszczak** [comment]
Need to add a handler [you need a developer]
