### ISSUE TITLE
[Question] How to display every recent changes / updates of Accounts, Tickets or Tasks on a Dashboard Widget

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13630]
Hello,

I need some widget on the dashboard that shows me recent changes in the system as a widget.
Especially Accounts and Tickets I would like to monitor:

![Screenshot_2020-10-12 Accounts List](https://user-images.githubusercontent.com/13665806/95726396-2cf8a180-0c79-11eb-9cb3-36419d5a3a4f.png)

So every time there is e new entry and displayed with the red counter in the screenshot, I would like to see this entry in a widget.

Is there a way? I am using YF 5.3 SF 1

Thanks!

Regards

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/95816669-ed38c500-0d1f-11eb-8325-008f92d54183.png)

or you can try to use watchdog

![image](https://user-images.githubusercontent.com/10221999/95816863-69330d00-0d20-11eb-8192-19e451c03922.png)

**Comment by blu-IT** [comment]
@rskrzypczak Thanks!!! That's exactly what I need! But how do I get that Updates-widget on my dashboard? How to create or activate it?

**Comment by blu-IT** [comment]
OK, I found the settings AND the preconfigured widget - did not know the existence of these preconfigured widgets - very helpful!

![Screenshot_2020-10-13 Widget management System settings](https://user-images.githubusercontent.com/13665806/95822790-dc428080-0d2c-11eb-9c4f-40dd27c81a0e.png)

Thanks again!
