### ISSUE TITLE
[Bug] Converting Leads to Accounts no longer works after Servicepack Update

### ISSUE THREAD

**Issue by Hammerman3000** [YetiForceCompany/YetiForceCRM#13634]
Hi there,

I recently updated to 5.3.0 ServicePack 4.

Now I am in trouble converting leads to accounts, even as an Admin.
![image](https://user-images.githubusercontent.com/45795852/95749613-23346580-0c9c-11eb-9450-52b311101291.png)

I found some weird behavior:
- A field "Short Name" exists without mapping
![image](https://user-images.githubusercontent.com/45795852/95749692-452de800-0c9c-11eb-8e4f-772ca620266d.png)

But it also can't be mapped as It doesn't show up anymore in the mapping overview
![image](https://user-images.githubusercontent.com/45795852/95749783-68589780-0c9c-11eb-9a1b-0ef649cafe46.png)

The same weird behavior goes for the "Active" checkbox - it can not be matched any longer to the "Active" checkbox of an Account.
![image](https://user-images.githubusercontent.com/45795852/95749967-b79ec800-0c9c-11eb-87b7-394768e35aec.png)

**Comment by mariuszkrzaczkowski** [comment]
Does the problem still exist in the newest version?

**Comment by konadrian** [comment]
The problem no longer exists. The ticket has been closed.
