### ISSUE TITLE
[bug] multiEmail field, 'consent to send' checkbox not working properly

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#13633]
Hi,

On gitstable, you can only check 1st email.

On gitdeveloper, you can select all but 1st entry.

Below screen recording was made on giststable.

![issue_multi_email_field](https://user-images.githubusercontent.com/2930560/95738338-59b4b500-0c89-11eb-9da5-448dad4627f6.gif)

Also, I've noticed that multiEmail field cannot be used as email address for Mass Email action.

Regards,

**Comment by davide-alghi** [comment]
I confirm. it works via keyboard, it doesn't via mouse.
This is a regression: in YF 5.2 works fine. I added in my bug-list: I'll try to fix it.

For inclusion in mass-email action, I'll investigate the complexity.
