### ISSUE TITLE
[Question] How can i create a filter which shows opportunities which have not been modified for more than X amount of days?

### ISSUE THREAD

**Issue by satty12** [YetiForceCompany/YetiForceCRM#13631]
[Question] How can i create a filter which shows opportunities which have not been modified for more than X amount of days?

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/95734416-b8773000-0c83-11eb-87de-ab4404361771.png)

**Comment by satty12** [comment]
this give me what was changed in last 30 days.. I need opportunities which have "NOT" been updated in last 30 days..
