### ISSUE TITLE
[Question] CardDAV/CalDAV: I only can see my contacts and meetings - how to see ALL?

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13635]
Hello,

I'am refering to this issue https://github.com/YetiForceCompany/YetiForceCRM/issues/13469 because it has been closed, but still not working.

After changing the settings, like mentioned here https://github.com/YetiForceCompany/YetiForceCRM/issues/13469#issuecomment-693923072 I still **can't see all** accounts/organizations via CardDAV.

I tried configuring Mozilla Thunderbird addressbook (and calendar) via CardDAV/CalDAV to YF-CRM.
So far everything went fine, BUT I can see only my (test-)contact an even no organizations. But I want to see ALL organizations and contatcs in the crm.

I'am using my normal YF account (with admin rights):
https://myserver.com/dav.php/principals/ME/

also tried
https://myserver.com/dav.php/addressbooks/ME/YFAddressBook/

When importing all the organizations and contacs into YF I was using another admin account and so I also created a key for CardDAV/CalDAV access into the YF settings, but the table "sum of contacs" already shows only 1 contact to me.

So where are all the contacs? How do get them all shown via CardDAV?

I found that post here, where sombody had a vice verca problem - but unfortunately that did not help me.

#5992

Thanks!

Regards

**Comment by Hammerman3000** [comment]
I gave you a reply in your previous post https://github.com/YetiForceCompany/YetiForceCRM/issues/13469#issuecomment-693923072

**Comment by mariuszkrzaczkowski** [comment]
Your user can see all contacts in CRM?

**Comment by blu-IT** [comment]
@mariuszkrzaczkowski 

Yes, I can see all contacts, but I also need to see the "Accounts" stored in the CRM via CardDAV- they are the basic part of my "Contacts" - customers and companys without a special/individual contact, but a general contact (like Secretary's Office):

![Screenshot_2020-10-13 Accounts List](https://user-images.githubusercontent.com/13665806/95821542-69380a80-0d2a-11eb-9125-e52c4fa745ab.png)

**Comment by mariuszkrzaczkowski** [comment]
How many records do you have in contacts and how many shows in the dav configuration panel?

**Comment by blu-IT** [comment]
Well, actually there are about 16 or 17 contacts in the YF and I can see 16 in Thunderbird address book.
DAV configuration panel says 18 contacts...

But I have more then 400 Accounts / Companys stored I would like to see via CardDAV...

**Comment by mariuszkrzaczkowski** [comment]
I don't understand something about what modules are you talking about?

**Comment by mariuszkrzaczkowski** [comment]
syncing only works with contacts and what do you want to sync?

**Comment by blu-IT** [comment]
> I don't understand something about what modules are you talking about?

I am talking about **"Companies and Contacts -> Accounts"** - this is the base for all general and unspecified contacts, like  Secretary's Office of every Company.

**Comment by blu-IT** [comment]
> syncing only works with contacts and what do you want to sync?

Accounts (Companies and Contacts -> Accounts) also have (**the primary!**) contact details for e-mail or phone for example. This is crucial for us. A customer/company that is stored in accounts is a Contact from my point of view.

**Comment by mariuszkrzaczkowski** [comment]
Currently, the system does not have the ability to synchronize the "Accounts" module.
If there is a client for it, we will expand the synchronization

**Comment by blu-IT** [comment]
@mariuszkrzaczkowski 

OK, thanks! You mean you need a customer who want's this function? OK, I will ask the client where I am implementing the system and I will need some costs I can tell him ;-)

**Comment by mariuszkrzaczkowski** [comment]
> OK, thanks! You mean you need a customer who want's this function? 

yes

**Comment by blu-IT** [comment]
> > OK, thanks! You mean you need a customer who want's this function?
> 
> yes

OK, maybe I have this customer for you ;-) Can you send me a offer for this impelemtation via pm or mail?

**Comment by Hammerman3000** [comment]
@blu-IT ok, now I understand your questions. You confuse accounts with contacts and expect them to sync via CardDav which they can't since they are just "lines" in the vcfs and not stand-alone contacts 👍

@mariuszkrzaczkowski wouldn't it generally speaking make more sense to enable yetiforce with a simple open source LDAP (like https://www.openldap.org/ or any other...) contact server? It's close to 0 work given the degree of work already put into the CardDav solution and would likely enable a way better sync to a lot of 3rd party services since LDAP is way more widely spread for this purpose.

**Comment by mariuszkrzaczkowski** [comment]
> OK, maybe I have this customer for you ;-) Can you send me a offer for this impelemtation via pm or mail?

send to e-mail hello@yetiforce.com
