### ISSUE TITLE
[Question] Best way to update from 4.4

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#13641]
Hello friends, simple question.

What is the best and most reliable way to update our system from 4.4 to the latest stable 5.3?

I'm not very good with using this github. Could someone just give me the proper links to the proper stable files to download and use to update our system? Do I first need to update it to some transition version and then to the latest one? I'm kind of lost in all the download files options here in github.

I would really appreciate it.

**Comment by bpabiszczak** [comment]
4.4 > 5.0 > 5.1 > 5.2 > 5.3
https://github.com/YetiForceCompany/YetiForceCRM/releases 
We can also do it for a fee for you [8h].
