### ISSUE TITLE
[Question] Why are we receiving this error when adding Oppertunity

### ISSUE THREAD

**Issue by jacohelm** [YetiForceCompany/YetiForceCRM#13654]
When creating a new Opportunity, no matter what the Subject is set to, we are bugged with this error.

![image](https://user-images.githubusercontent.com/2587812/96240523-4c593c80-0fa1-11eb-98b2-6bc4ba88a62f.png)

Although the Opportunity is still created, the error remains.

We did change the numbering system for Opportunities and each is a new number and even when ensuring the Subject field is something that has never been used before, we still get the error.

Any help or ideas on fixing

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/96242322-a4913e00-0fa3-11eb-817a-e5f91b475621.jpg)
