### ISSUE TITLE
Changing the landing tab from Summary to Details for Opportunities?

### ISSUE THREAD

**Issue by Yetilayman** [YetiForceCompany/YetiForceCRM#13650]
How does one change the landing tab from Summary to Details for Opportunities in YetiForce?

**Comment by mariuszkrzaczkowski** [comment]
Create a configuration file for this module example:
config\Modules\__Module_Name__.php

![image](https://user-images.githubusercontent.com/10198654/96222456-997ee380-0f8c-11eb-9db8-91db5e4c918a.png)
