### ISSUE TITLE
How to export to Excel with more than 12 attributes from YetiForce (e.g. Opportunities)

### ISSUE THREAD

**Issue by Yetilayman** [YetiForceCompany/YetiForceCRM#13651]
How does one export (to Excel) more than 12 fields / attributes from YF, e.g. from Opportunities?

**Comment by davide-alghi** [comment]
Hi @Yetilayman,
"Export to Excel" action exports selected filter fields, so you have to add needed fields to filter you are using to export.

**Comment by jacohelm** [comment]
Hi @davide-alghi 

The problem is when setting up a filter, you cannot add more than 12 columns. Is there any way to increase the number of columns per filter?

![image](https://user-images.githubusercontent.com/2587812/96239355-e28c6300-0f9f-11eb-8f7d-9d403fa26799.png)

**Comment by davide-alghi** [comment]
Hi @jacohelm,
pls believe me! pretend there is no limit! :innocent:
![Screencast_16-10-2020_11:55:52](https://user-images.githubusercontent.com/48508691/96245266-6c8bfa00-0fa7-11eb-98e7-43bf1798f96b.gif)

**Comment by jacohelm** [comment]
Hi @davide-alghi 

Thanks. Suppose that is what happens when you read the screen and adhere to the notes. :-)

**Comment by davide-alghi** [comment]
yes @jacohelm, and you're right to follow notes :thumbsup:
in YF 6.0 label is fixed
