### ISSUE TITLE
[bug] Images in KnowledgeBase are not displayed in browsers

### ISSUE THREAD

**Issue by Andr198** [YetiForceCompany/YetiForceCRM#13655]
# 🐞 bug report

### ⁉️ 
Images in KnowledgeBase are not displayed in browsers

![noimage](https://user-images.githubusercontent.com/62097187/96241050-33e12600-0f91-11eb-981b-2389d76930ce.JPG)

### 🔥 How to trigger the error

1. Go to 'Support FAQ Knowledge base Projekty'

### 👷 Testing

- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |Opera IE Firefox Google Chrome|
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

### ❓ Additional context

Browsers error
Refused to load the image 'https://yetiforce.com/images/1g2crowd.png' because it violates the following Content Security Policy directive: "img-src 'self' data:

**Comment by mariuszkrzaczkowski** [comment]
It works properly, by default the system blocks loading from external sites.
You must enter the list of trusted domains in the configuration.
https://github.com/YetiForceCompany/YetiForceCRM/blob/7f11a8ab41125a2e4e9f594ec9ec3a56bb2fcbf8/config/Security.php#L143-L144
