### ISSUE TITLE
[Question] API filtering by greater than or less than with x-condition

### ISSUE THREAD

**Issue by tonybyng** [YetiForceCompany/YetiForceCRM#13652]
### Description
I finally got my head around the x-condition filtering on the API but cannot see how to do a greater than or less than filter. I want to pick up any Accounts record that has been created today (or in fact, over the previous hour ideally) but there doesn't seem to be an operator for greater than or less than ? This means not only can I not do date searches but can't identify any record with a a credit_limit > 0 for example.  I figure I must have missed something but looking in the 

app/Conditions/QueryFields/BaseField.php

I see the operatorE and operatorY and operatorN etc but there is no operatorGT or operatorLT (or GTE / LTE) for example

I've temporarily added them in and prove they work for numbers (happy to do a PR if they really are missing) but I can't get the dates working with them. Im trying with a gmdate("Y-m-d H:i:s",strtotime("- 1 hour")); on the createdtime but I then get all records - which I think is Yeti not recognising the condition parameters and so ignoring it.

Any guidance would be appreciated

**Comment by davide-alghi** [comment]
maybe these? (dates)

https://github.com/YetiForceCompany/YetiForceCRM/blob/ff3d21326e54f8224bbcddcc104a770f6436d60b/app/Conditions/QueryFields/DateField.php#L126

https://github.com/YetiForceCompany/YetiForceCRM/blob/ff3d21326e54f8224bbcddcc104a770f6436d60b/app/Conditions/QueryFields/DateField.php#L136
