### ISSUE TITLE
[Feature] Show only open tickets in the widget

### ISSUE THREAD

**Issue by acoolov** [YetiForceCompany/YetiForceCRM#13656]
Hello friends, 

I was able to create a tickets widget for the Account module. So now when I click on any account, it shows all the tickets associated with that account right in the summary view, which is super convenient.

However, it is always showing all tickets, not just open tickets. And sometimes when there are too many tickets that have been done for the client, the widget would only show all the closed tickets, and there is not even a way to sort all the open tickets to the top, or just show open tickets only. Would be very nice, when you go to the client's account, and right away see all the open tickets associated with that client. But then if I needed to see all the tickets I'd just go to the Tickets tab for that account. 

Is that possible currently? I didn't see the option to only show open tickets in the Modules > Widgets.

Let me know. Thank you.

**Comment by davide-alghi** [comment]
Hi @acoolov,
a way to reach your need is to use filter or switch in widget.

_Premise: in YF 5.3 filter and switch have some problems, but in YF 6.0 issues are fixed._

I suggest you to use switch. How to?

1) create a new boolean field into Tickets module: "Is open"
2) create 2 workflow to set "Is open" field
   - WF 1 => Condition: Status = /include Status values in OR condition/ --- Task (Update fields): "Is open" = true
   - WF 2 => Condition: Status = /include Status values in OR condition/ --- Task (Update fields): "Is open" = false
3) add new widget (Related module) for Accounts module and set "Is open" as switch

______

create a new boolean field into Tickets module: "Is open"
![Screencast_19-10-2020_11:58:09](https://user-images.githubusercontent.com/48508691/96440472-4f099b00-1208-11eb-9059-a882bc1f99bc.gif)

create 2 workflow to set "Is open" field
![Screencast_19-10-2020_12:35:18](https://user-images.githubusercontent.com/48508691/96440483-529d2200-1208-11eb-8b81-db6c4891065b.gif)

add new widget (Related module) for Accounts module and set "Is open" as switch
![Schermata da 2020-10-19 12-36-31](https://user-images.githubusercontent.com/48508691/96440490-55981280-1208-11eb-80ff-30401fef5a21.png)

result
![Screencast_19-10-2020_12:36:59](https://user-images.githubusercontent.com/48508691/96440497-59c43000-1208-11eb-9193-1cae05fb8764.gif)
