### ISSUE TITLE
[Question]  whatsapp integrations 

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13678]
Can u guys help me or can u integrate whatsapp into campaigns.
So with just 1 click whatsapp is sent to all  in that campaign list.

I am willing to pay, let me know how much would that cost and time needes.. Really need it like yesterday..

**Comment by bpabiszczak** [comment]
~28-40h
https://yetiforce.com/en/marketplace/development-support
