### ISSUE TITLE
[bug] Updates widget not shown any more on Dashboard

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13672]
# 🐞 bug report

Hello,

as I already recieved a solution here https://github.com/YetiForceCompany/YetiForceCRM/issues/13630 I configured special widgets for all users in YF for their dashbord.
When configuring the "**Updates**" widget for a special role the first it was shown on dashboard for the users, then it was canceled by accident and I reconfigured and set it as **Mandatory widget**, but it does not appear again on the dashboard.

This **does not happen with other widgets** I canceled in the systems settings and activated again. It only happed to me with the Updates widget!

I can reproduce this behavior also on gitstable but **not on gitdeveloper**.

### 🔥 How to trigger the error

1. Go to "System settings -> Software configuration -> Standard modules -> Dashboard - Widgets".
2. If no role has been defined before, click on "Add role".
3. Click on "+ Predefined widgets".
4. In Select widget field, scroll down to "Updates" and select "Mandatory widget".
5. Go to Dashboard and control if "Updates" widgets appears (should be so the first time).
6. Go back to "System settings -> Software configuration -> Standard modules -> Dashboard - Widgets".
7. Cancel the "Updates" widget.
8. Go back to Dashboard and control if "Updates" widgets dissapeared.
9. Go back to "System settings -> Software configuration -> Standard modules -> Dashboard - Widgets".
10. Click on "+ Predefined widgets".
11. In Select widget field, scroll down to "Updates" and select "Mandatory widget".
13. Go back again to Dashboard and control if "Updates" widgets appears - **it does not**.

### 👎 Actual Behavior

"Updates" widgets does not appear again on the dashboard once it was canceled and reselected again.

### 👍 Expected Behavior

"Updates" widgets appears every time on the dashboard, when it was selected/configured in the system settings.

### 👷 Testing

- [ X] I confirm that I tested it at https://gitstable.yetiforce.com - **same behavior** as described above.
- [ X] I confirm that I tested it at https://gitdeveloper.yetiforce.com - could **not** reproduce it here.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3 SF 1
| Web server (name and version)       |       Apache         |
| PHP                                 |                |
| Browser (name and version)          |    Firefox            |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |       SP4         |

**Comment by rskrzypczak** [comment]
Fixed on the current development version, the bug will not appear in version 6.2.
