### ISSUE TITLE
[Question] Quantity field

### ISSUE THREAD

**Issue by pietro559** [YetiForceCompany/YetiForceCRM#13671]
Hello,

Is there the posibility to fill a decimal value in quantity field?

**Comment by vovpff** [comment]
Hmmm... What is the problem? What quantity field you mean?

**Comment by pietro559** [comment]
For example invoice module (or any other advanced module).

**Comment by pietro559** [comment]
I found out!!
Even if i set up comma as decimal separator, quantity field wants the point as decimal separator.
