### ISSUE TITLE
[Question] How do I make a condition true when the date in the field is before today

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#13674]
How to make the condition in Workflows, so that it is true, as the date of the field is before today?

![obraz](https://user-images.githubusercontent.com/62466142/96694467-cc5c1980-1388-11eb-83d9-ddd9ff553009.png)

eg If today is 21/10/2020, the date is in the field
  - 10/10/2020 will give the result TRUE
  - 20/10/2020 will give the result TRUE
  - 22/10/2020 will give the result FALSE
  - 29/10/2020 will give the result FALSE

Do I have to enter any formula in the "in less than" field?
![obraz](https://user-images.githubusercontent.com/62466142/96695021-750a7900-1389-11eb-9d9a-14c7638fe4fc.png)

I wonder if this effect can be achieved with the available functions?

**Comment by vdpawel** [comment]
![obraz](https://user-images.githubusercontent.com/62466142/96699893-13e5a400-138f-11eb-8118-1593f46c3b5f.png)

**Comment by davide-alghi** [comment]
Hi @vdpawel,

_1) =============================== with today excluded_ ===============================

![Schermata da 2020-10-21 14-16-11](https://user-images.githubusercontent.com/48508691/96718513-6c756b00-13a8-11eb-8509-b4cdbee0598a.png)





____________

_2) =============================== with today included_ ===============================

![Schermata da 2020-10-21 14-18-10](https://user-images.githubusercontent.com/48508691/96718520-6f705b80-13a8-11eb-9497-4dadeea612c5.png)

**Comment by vdpawel** [comment]
It works!!! 
@davide-alghi Thank you very much for your time

Can in a similar way, I can get the following effect, I can not find a solution.

**Case 1:**
![obraz](https://user-images.githubusercontent.com/62466142/96725174-ea3d7480-13b0-11eb-81a7-897f8941b065.png)

**Case 2:**
![obraz](https://user-images.githubusercontent.com/62466142/96725961-c9295380-13b1-11eb-8c62-3818c87cb7cd.png)


The solution for case 2 will be AND of your solution and case 1. Is there any simpler solution?

**Comment by davide-alghi** [comment]
Hi,
about your last two cases, for **case 1** is

![Schermata da 2020-10-21 15-54-41](https://user-images.githubusercontent.com/48508691/96730736-cd0ba480-13b6-11eb-9f70-de0be656d37e.png)

_____________
about **case 2**, it's not clear. Have you to run workflow if 

field_1 (02.10.2020) < TODAY (now) < field_2 (30.10.2020)

where field_1 and field_2 are two date fields into entity?

**Comment by vdpawel** [comment]
@davide-alghi Thank you very much for your answer, now the conditions are clear.
Case 2 is 2 fields, eg 

field_1 (02.10.2020) **<=**  TODAY (now)   <   field_2 (30.10.2020)
Start Data                **<=**  TODAY (now)    <   Target Date.

Referring to your examples, I would do it like this:

![obraz](https://user-images.githubusercontent.com/62466142/96819645-5f965d00-1424-11eb-9cf2-954f0dec4369.png)

**Comment by davide-alghi** [comment]
yes that's right :thumbsup:
