### ISSUE TITLE
[Question] Link in workflow list

### ISSUE THREAD

**Issue by gsportelli73** [YetiForceCompany/YetiForceCRM#13676]
Hi, when i open in system configuration workflow list and i click on a link of record for example description,  update, it opens a blnk page.
Is it normal ?

Watch video
[https://youtu.be/HqvmAStyksQ](url)

Thank for attention

**Comment by davide-alghi** [comment]
Hi @gsportelli73,
it doesn't, but that has already been fixed.
it's good practice to check the YF developer version

https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=List

**Comment by gsportelli73** [comment]
Hi, thank for answer, i have seem the fix on demo, but how to fix it on my version ?
System doesn't notify update.
my system report version 5.3.139
Thank

**Comment by davide-alghi** [comment]
you have to wait for the next system update/upgrade, for now click on icon pencil, for editing
