### ISSUE TITLE
[bug] Invoice Currency summary

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#13679]
I don't know why Polish zlotys are charged, otherwise Currency summary doesn't show up in the PDF report at all.
I can't delete Polish zlotys from the app at all.  ver. 5.3.311

![ne dela1](https://user-images.githubusercontent.com/25682437/96850887-a782a780-1457-11eb-85c3-b5fefd0e31f6.gif)

**Comment by davide-alghi** [comment]
Hi @fbojan,
maybe I cannot understand your issue :(
**Currency summary** shows the amounts in **System default currency**, not in **inventory entity currency**.
If the **inventory entity currency** is different from **System default currency**, the **Currency summary** is showed in **System default currency**, else if **inventory entity currency** is the same as **System default currency**, the **Currency summary** is not showed.

**Comment by fbojan** [comment]
First of all, I do not understand the value of Currency summary 437.96 zł, although I set everything in EUR.

![ne dela12](https://user-images.githubusercontent.com/25682437/96870229-e113dc80-1470-11eb-9206-ad5b054ebfb7.gif)

**Comment by davide-alghi** [comment]
Hi @fbojan,
maybe this can help

![Screencast_22-10-2020_14:42:52](https://user-images.githubusercontent.com/48508691/96873349-1de1d280-1475-11eb-8f8f-fd3fa9c2a32b.gif)

**Comment by davide-alghi** [comment]
Hi @fbojan,
[I remade the video]
Maybe this can help
![currencySummary](https://user-images.githubusercontent.com/48508691/96901416-82ac2580-1493-11eb-81d6-36dfa445f3d2.gif)

**Comment by fbojan** [comment]
It's hard to ask co-workers to complicate such simple things.
I believe that you have a lot of code written here and I don't want to complicate your work, and if you can't issue an invoice properly, it's app not useful, even though it's phenomenal.

![Untitled-2](https://user-images.githubusercontent.com/25682437/97078159-53f49300-15ea-11eb-8cd9-5af6aa50934e.gif)

**Comment by davide-alghi** [comment]
Hi @fbojan,
are you speaking about a PDF function to include the red (the one into your image)?
What's 9.5%? I don't see it in taxes.

**Comment by fbojan** [comment]
![Untitled-1](https://user-images.githubusercontent.com/25682437/97796650-ec0b0180-1c14-11eb-8bde-8646148967c2.gif)

TEST Copyright © YetiForce.com All rights reserved. [ver. 5.3.322] [Page loading time: 0.23s.]


The first table is good, in the table below in Excel tax summary, all the necessary data are without Polish zlotys.

Thank you and best regards
BOJAN![Untitled-2](https://user-images.githubusercontent.com/25682437/97796651-ee6d5b80-1c14-11eb-8893-323a36a9aee5.gif)

**Comment by davide-alghi** [comment]
Hi @fbojan,
I'm confused. Data and format into your last images are correct. What's "Excel tax summary"?
please, you have to be more detailed else nobody will be able to help you.

**Comment by mariuszkrzaczkowski** [comment]
It works properly,
![image](https://user-images.githubusercontent.com/10198654/183390297-194e7f74-f977-4b52-ac0a-2be64b8a1667.png)
![image](https://user-images.githubusercontent.com/10198654/183390312-9fa7a9ae-6688-431b-af39-daade5989014.png)


the summary of currencies is shown only when the currency of eg Invoices is different than the default CRM system
gitdeveloper has a default currency of PLN
![image](https://user-images.githubusercontent.com/10198654/183389527-c6197b7f-4f42-476d-8831-f8510e21e466.png)

NOTE, changing the default currency will require you to re-edit all records and will cause problems with the values, we do not recommend this on the production version
