### ISSUE TITLE
[Question] IStoragers and inventory

### ISSUE THREAD

**Issue by crawe1** [YetiForceCompany/YetiForceCRM#13675]
I have a question about the amount of storage products in stock.

Utylizacja -> Utilization. 

I added a new table "Utylizacja"  related to a given warehouse ( and I want the products in the main warehouse to be removed as I add to this new "Utylizacja" table.

![image](https://user-images.githubusercontent.com/61950059/96713127-69767c80-13a0-11eb-9698-d4f44f268d81.png)

![image](https://user-images.githubusercontent.com/61950059/96712866-0e448a00-13a0-11eb-8104-1d52c0bf5828.png)

I found relationships in files
modules / IStorages / models / Module.php
and added an entry:

         public static $ modulesToCalculate = ['add' => ['IGRN', 'IIDN', 'ISTRN', 'IGRNC'], 'remove' => ['IGDN', 'IGIN', 'IPreOrder', 'ISTDN' , 'IGDNC', 'Utylizacja']];

however, it had no effect of changing the value. Where can I find other relationships between tables?

Thank for your help
Tom

**Comment by vovpff** [comment]
@crawe1 you need to activate calculation handler for this module too

**Comment by crawe1** [comment]
OK, But can you tell me where ?

**Comment by vovpff** [comment]
@crawe1 check in database table what contains `eventhandler` in name. Here you can find list of handlers.

I'm not sure for 100%

**Comment by crawe1** [comment]
you're right there changed earlier in DB vtiger_eventhandlers 

table row from 

52 | EntityAfterSave | IStorages_RecalculateStockHandler_Handler | 1 | IGRN,IIDN,IGDN,IGIN,IPreOrder,ISTDN,ISTRN,IGRNC,IGDNC
-- | -- | -- | -- | --

on this

IGRN,IIDN,IGDN,IGIN,IPreOrder,ISTDN,ISTRN,IGRNC,IGDNC,Utylizacja

but can i anything else needs to be changed. 
Because it still won't work.

How do you think the statuses are important to recalculate new module? When i browse code im not see any  relationship.

**Comment by vovpff** [comment]
@crawe1 yes. Status is critical to trigger handler. You need to add status with PLL_ACCEPTED. This status means what trugger should calculate quantity values.

**Comment by crawe1** [comment]
Thank you so mutch **VOVPFF** every works!
For the other step by step:
1) add your module name in file 
modules/IStorages/models/Module.php 
in this line 
`public static $ modulesToCalculate = ['add' => ['IGRN', 'IIDN', 'ISTRN', 'IGRNC'], 'remove' => ['IGDN', 'IGIN', 'IPreOrder', 'ISTDN' , 'IGDNC', ]];` 
if you want  add or remove stack

1a) add on file 
modules/your_module_name/your_module_name.php
`        public $relationFields = [];`
2) on DB in table 
vtiger_eventhandlers 
add your module name in row 
EntityAfterSave | IStorages_RecalculateStockHandler_Handler
-- | --
on the end cell 
3) You must add pick list in files in module with value 
"PLL_ACCEPTED" 
- you can translate on your field_name in  
languages/your_country/your_module_name.json 
on "Approve"

**Comment by crawe1** [comment]
vovpff tell me,
Is it possible to get the data on the quantity of the product and the product name from the main table and not advanced? how to do it in simple way ?

**Comment by vovpff** [comment]
@crawe1 please describe more detailed what you want?

**Comment by crawe1** [comment]
> @crawe1 please describe more detailed what you want?

![image](https://user-images.githubusercontent.com/61950059/97300774-2fe9b980-1857-11eb-9dac-5304285b7609.png)

on screen you can see what i want to change. I want to use field in primary table not from advanced table to reduce param in stock.

![image](https://user-images.githubusercontent.com/61950059/97301536-2e6cc100-1858-11eb-8c80-fccf4a10dacf.png)

I see in file

`        public static function setQtyInStock($moduleName, $data, $storageId, $action)
        {
                $db = App\Db::getInstance();
                $qtyInStock = [];
                foreach ($data as $product) {

                if (!isset($qtyInStock[$product['name']])) {
                        $qtyInStock[$product['name']] = 0;
                        }
                        $qtyInStock[$product['name']] += $product['qty'];
                }
                $operator = self::getOperator($moduleName, $action);
`
in modules/IStorages/models/Module.php

you can see the variable "name" and "qty" is in DB on table u_yf_naprawy_inventory but i want to get data from  u_yf_naprawy this is possible ?

![image](https://user-images.githubusercontent.com/61950059/97302701-b30c0f00-1859-11eb-81eb-f9b783d8d90b.png)

![image](https://user-images.githubusercontent.com/61950059/97302876-eb135200-1859-11eb-8e66-ad46eb069575.png)

**Comment by vovpff** [comment]
@crawe1 I'm sorry but this is very difficult to understand what you need

**Comment by crawe1** [comment]
hmm its simple ;)

in standard workflow on primary table we have data:
- storage id,
- status,
on advanced table we have:
- productname,
- qty.

on thist params we change stock in storages. but i want to change i want to move productname and qty from advance to primary table. becouse in advanced i want to put other data not related with products.

In my module on basic table i want to add products to repair and i want to remove on time repait from stock qty when then the product it was repaired but on advanced tabel i want do add components of product whats need to repair.

**Comment by vovpff** [comment]
@crawe1 I understand what you mean. Your task is difficult to implement because arvanced modules mechanisms hardcoded in system core and you need to change a lot of code to achieve needed result.

I think what some kind of custom handler or workflow custom function can solve this but I can't describe how to  do them.

**Comment by crawe1** [comment]
@vovpff 
Thank you for everything
