### ISSUE TITLE
[Question] Root Web Directory on Apache Installation

### ISSUE THREAD

**Issue by sltmunky69** [YetiForceCompany/YetiForceCRM#13690]
I'm kind of confused here and hoping to shed some light on the situation. I've searched through the tickets and the documentation page is pretty weak and I'm not finding answers.

In regards to the basic installation of the software and the public_html directory setting in the installation requirements checklist, in order to run the software installer (install.php or whatever), you have to make the web root the unzipped directory, but the warning on the setting in the checklist is either confusing or misleading. 

After several tries, I eventually satisfied all of the other checklist requirements with apache directives except that one and was able to get the software actually installed using the unzipped directory, but the installer simply wouldn't run and I also get a 500 error if I move the webroot to the actual public_html directory. What is the webroot directory actually supposed to be? Is it really supposed to be the parent directory and is the point of the .htaccess files to deny access to and secure the directories above public_html?

I'm also using VestaCP with a subdomain, and it's a toss up as to whether that is actually part of this problem or not. When I try to make public_html the root directory, I get this message in the error log "....public_html/.htaccess: <IfModule not allowed here". Otherwise, the software runs fine if I leave the webroot on the parent directory. I just don't want to leave anything publicly accessible that isn't supposed to be. I intentionally haven't posted my apache config because I'm trying to keep this as simple as possible with just the questions above.

**Comment by davide-alghi** [comment]
Hi @sltmunky69,
it appears that .htaccess reading is not enabled in your Apache.

Please try to put **AllowOverride** directive

```
AllowOverride All
```
into your **Virtualhost** configuration

something like this
```
<IfModule mod_ssl.c>
  <VirtualHost *:443>
   ...
    <Directory /var/www/html/yetiforce/>
      Options Indexes FollowSymLinks MultiViews
      AllowOverride All
      Require all granted
      Allow from all
    </Directory>
   ...
  </VirtualHost>
</IfModule>
```

**Comment by sltmunky69** [comment]
.htaccess is enabled, and I had already tried your suggestion when I researched the "IfModule not allowed here message", which I don't believe is actually part of the issue. Per my original question, your example shows the parent directory yetiforce as being the wwwroot and NOT the yetiforce/public_html directory. The application runs fine if I place the directory on yetiforce, but I get this other error message when it try to use public_html, so which is correct? Why would the installer specifically say to use the public_html directory to prevent external access to the API and other components as a requirement if that weren't the case? I'm guessing that yetiforce is actually supposed to be the wwwroot and that the .htaccess file might be providing the extra layer of security for those components as to not allow external access, but I was hoping someone could provide a confirmation of this.

**Comment by davide-alghi** [comment]
> Per my original question, your example shows the parent directory yetiforce as being the wwwroot and NOT the yetiforce/public_html directory.

No. The path in my example 
```
<Directory /var/www/html/yetiforce/>
```
defines where the directive ```AllowOverride All``` is applied.
In example, the YF root (/var/www/html/yetiforce/) and all subdirectories: public_html folder included

To run public_html as document root, you have to set it via ```DocumentRoot``` directive
here a complete example (with fpm, http/2)
```
<VirtualHost *:80>
    ServerName yoursubdomain.yourdomain.com
    Redirect permanent / https://yoursubdomain.yourdomain.com
</VirtualHost>

<IfModule mod_ssl.c>
  <VirtualHost *:443>
    ServerAdmin youremail@yourdomain.com
    DocumentRoot /var/www/html/yetiforce/public_html/
    ServerName yoursubdomain.yourdomain.com
    Protocols h2 h2c http/1.1

    <Directory /var/www/html/yetiforce/>
      Options Indexes FollowSymLinks MultiViews
      AllowOverride All
      Require all granted
      Allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/yoursubdomain.yourdomain.com.error.log
    CustomLog ${APACHE_LOG_DIR}/yoursubdomain.yourdomain.com.access.log combined

    SSLEngine on

    SSLCertificateFile /etc/letsencrypt/live/yoursubdomain.yourdomain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/yoursubdomain.yourdomain.com/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/yoursubdomain.yourdomain.com/chain.pem

    <FilesMatch "\.(cgi|shtml|phtml|php)$">
      SSLOptions +StdEnvVars
    </FilesMatch>
    <Directory /usr/lib/cgi-bin>
      SSLOptions +StdEnvVars
    </Directory>

    BrowserMatch "MSIE [2-6]" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
    # MSIE 7 and newer should be able to use keepalive
    BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
  </VirtualHost>
</IfModule>

```

**Comment by davide-alghi** [comment]
Just a question: has Apache the mod_rewrite installed and enabled?

**Comment by bpabiszczak** [comment]
According to security standards, htaccess should not be used to configure the server.

**Comment by sltmunky69** [comment]
Ahh, I'm a dummy. Thank you for the example, that clears things up. I had the DocumentRoot and the Directory both set to the public_html folder which makes complete sense now.
