### ISSUE TITLE
Not able to add Comments in several modules

### ISSUE THREAD

**Issue by hdemendieta** [YetiForceCompany/YetiForceCRM#13694]
Issue
When I try to add a comment is several modules, I'm able to write at the field but the add button doesn't works.  This is happening in some widgests but even at the Comments Tab in some modules. 
I don't know how to fix it.  I did not find any configuration I can change for this. 
Yetiforce version: 5.3.0
PHP: 7.4  (I tested switching to version 7.3 and 7.2 but the issue persists) 

Thanks in advance for your help

**Comment by davide-alghi** [comment]
Hi @hdemendieta,
detailed info are essential.

**YF Logs - How To**

1. disable (temporarily) the chat module, in Standard modules / Modules – Installation
2. set (temporarily) CRON execution to 5 minutes or more
3. in config/Debug.php set
   - $LOG_TO_FILE = true;
   - $LOG_LEVELS = false;
4. reset contents for the files:
   - cache/logs/system.log
   - php_errors.log
5. reproduce the issue/bug/problem
6. upload here the files
   - cache/logs/system.log
   - php_errors.log

   
**Browser console - How To** - https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-s-console-file

1. open browser console
2. switch to "Console" tab
3. clean console
3. reproduce the issue/bug/problem
4. save console contents in a file
5. upload here the just created file


**Fill out the Bug Report**

![YetiForceCRM-BugReportTemplate](https://user-images.githubusercontent.com/48508691/97266421-baff8b00-1828-11eb-8a87-f9156f42c965.jpg)

**Comment by hdemendieta** [comment]
I fill out a new bug as requested with the issue number: 13711

Attached are the logs. 
[logs files.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/5466026/logs.files.zip)

Thank you!

**Comment by davide-alghi** [comment]
Bug report

https://github.com/YetiForceCompany/YetiForceCRM/issues/13711

**Comment by rskrzypczak** [comment]
Update the system with the latest servicepack(v4) which should fix the problem.
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.3.0
