### ISSUE TITLE
[Feature] Filter for Last X [Days | Months | Years]

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#13706]
### Describe the solution you'd like

The possibility the following filters:

- Last X days
- Last X months
- Last X years
- Next X days
- Next X months
- Next X years

X is an integer.

Currently we are limited to these values:
![image](https://user-images.githubusercontent.com/16014524/97587044-429cf380-19fb-11eb-9925-bf20a061e719.png)

### Is your feature request related to a problem? Please describe.
Yes, I need to filter contact persons on a date field with a range of 380 days from today.

**Comment by vovpff** [comment]
@LaurensCleyman you can do it by yourself

**Comment by LaurensCleyman** [comment]
@vovpff , how can I do that?

**Comment by vovpff** [comment]
Php coding I think

**Comment by bpabiszczak** [comment]
You have to outsource this to your developer.

**Comment by vdpawel** [comment]
I'm not sure, but you'll probably find the conditions you need here:
\app\Conditions\RecordFields\DateField.php
\app\Condition.php

**Comment by LaurensCleyman** [comment]
thanks @vdpawel to point me in the right direction ;-)
