### ISSUE TITLE
[Question] Description of a filter: Where is it used?

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#13700]
Hi all, 

**If I create a new filter and then give it a description then it is not visible in the front-end, so I don't know what is the use of the description:**
![image](https://user-images.githubusercontent.com/16014524/97435441-b4543f00-1920-11eb-9193-1c6aaaf8faf9.png)

**My Question: Is it possible to put it above the filter? On this place for example:**

![image](https://user-images.githubusercontent.com/16014524/97435664-05fcc980-1921-11eb-9041-531db21e241f.png)

I think it is useful to type a description about a filter that can then be read by someone who has access to that filter.

**Comment by vovpff** [comment]
@LaurensCleyman I'm not sure but I think what description visible in filters dropdown picklist.

You need to modify template of this part of UI

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/97531383-638e2600-19b4-11eb-97be-23e5f4973ad4.png)

Be sure to select this option
![image](https://user-images.githubusercontent.com/10221999/97531822-50c82100-19b5-11eb-8447-8ca5cb329502.png)
