### ISSUE TITLE
[bug] Comments cannot be published at any module

### ISSUE THREAD

**Issue by hdemendieta** [YetiForceCompany/YetiForceCRM#13711]
# 🐞 bug report

### ⁉️ Describe the bug

Publish button doesn't works at comments tabs or section in any YF module.  Just a few times it works, so I thought it was related with the Internet Browser, so I tried in different browsers, clean the cache but the issue persists.

### 🔥 How to trigger the error

1. Go to 'any comments tab at any module...'
2. Click on '.post button after writting a comment.'
3. The button doesn't works.
4. See the video screen capture  
![vokoscreen-2020-10-30_09-45-58](https://user-images.githubusercontent.com/31054251/97726397-c9ea7580-1a94-11eb-8d94-bf9558726cec.gif)

### 👷 Testing

- [x ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![ConfReport](https://user-images.githubusercontent.com/31054251/97726803-3e251900-1a95-11eb-892f-7244e5f7973b.png)
 -->

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Logs were sent to the email address: github@yetiforce.com. 

* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |    5.3.0
| Web server (name and version)       |                |
| PHP                                 |      7.4          |
| Browser (name and version)          |       Opera         |
| Operating System (name and version) |       Linux         |
| Database (name and version)         |        MySQL   5.6.47 - MySQL Community Server (GPL)        |
| Service Pack version                |                |

### ❓ Additional Server information

Nombre del servidor | s102
cPanel Versión | 88.0 (build 17)
Versión Apache | 2.4.46
Versión PHP | 7.2.33
Versión MySQL | 5.6.47
Arquitectura | x86_64
Sistema operativo | linux
Dirección IP compartida | 204.44.192.12
Ruta de acceso a Sendmail | /usr/sbin/sendmail
Ruta de acceso a Perl | /usr/bin/perl
Versión Perl | 5.16.3
Versión Kernel | 3.10.0-962.3.2.lve1.5.38.el7.x86_64

**Comment by davide-alghi** [comment]
Logs

https://github.com/YetiForceCompany/YetiForceCRM/files/5466026/logs.files.zip

**Comment by davide-alghi** [comment]
Hi,
@mariuszkrzaczkowski, maybe this is a problem with js plugin Tribute

**Comment by davide-alghi** [comment]
@hdemendieta,
you said that you tested on gitdeveloper, but there it seems the problem has been fixed.
please @hdemendieta, **can you try (again) on gitdeveloper**
https://gitdeveloper.yetiforce.com
to confirm the bug has been fixed or have you still the problem?

**Comment by mariuszkrzaczkowski** [comment]
The server configuration is incorrect, it is a waste of time without any improvement, in most cases such problems are caused by a wrong configuration.

**Comment by rskrzypczak** [comment]
Install ServicePack v4 ([link](https://github.com/YetiForceCompany/YetiForceCRM/releases))
