### ISSUE TITLE
[Question] Edit Fields is not working

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13721]
### Description

When i click on Edit fields in System settings >Standard modules , page doesnt fully load and no any buttons or actions work on the page , side bar works though.
Here is screen shot of the error :
![KakaoTalk_20201102_142312440](https://user-images.githubusercontent.com/40380541/97860043-92e0c200-1d29-11eb-81fd-ee8d19141ec6.jpg)

Version: Yetiforce 5.3.0

**Comment by rskrzypczak** [comment]
You will probably find the error information in the console (F12).
Also, check the log files.
From the information you provided I am not able to help you and as I think nobody is :)

**Comment by mariuszkrzaczkowski** [comment]
You have an unregistered system, unfortunately we cannot help.
![github](https://user-images.githubusercontent.com/10198654/97956841-00343780-1daa-11eb-847a-699c0adbf297.jpg)
