### ISSUE TITLE
[Question] Email History module is not working 

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13720]
### Description

I think email history should contain list of all emails sent form the system, but nothing appears there. 

Yetiforce 5.3.0 
SMTP and Round cube configured  , tested and working.

**Comment by rskrzypczak** [comment]
And so it will be when you set the mail scanner to also scan outgoing e-mails :)
https://github.com/YetiForceCompany/YetiForceCRM/issues/13719
