### ISSUE TITLE
Converting lead to account

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1372]
When I converting lead to account which enabled potentials I get warning, whithout enabled potential work fine.
![options](https://cloud.githubusercontent.com/assets/3193498/8519838/cfc79214-23d5-11e5-801d-ae666512c511.png)
![warning](https://cloud.githubusercontent.com/assets/3193498/8519847/de7733fa-23d5-11e5-8470-061ce984d160.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/d6c0b0a8c698f081f6c909011733df3f9b3ba68d
