### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by alexynadamas** [YetiForceCompany/YetiForceCRM#13728]
# 🐞 bug report

SQLSTATE[HY000]: General error: 1835 Malformed communication packet The SQL being executed was: SELECT * FROM `vtiger_tab`

### 🔥 How to trigger the error

The problem occurs when try to access to Yeti:
https://gestor.mediterjuridico.es

### 👷 Testing

I tested it configuring some MySQL parameters.

### 📷 Screenshot of configuration
PHP:
![image](https://user-images.githubusercontent.com/60443759/98117894-a6fffd00-1eaa-11eb-9843-e00cb2371f50.png)
![image](https://user-images.githubusercontent.com/60443759/98117910-ae270b00-1eaa-11eb-80ce-c2866f16bca3.png)
MariaDB:
![image](https://user-images.githubusercontent.com/60443759/98118003-d0b92400-1eaa-11eb-8e2d-ac1abaa0d34c.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Cache/logs:
[logs.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/5488141/logs.zip)
Apache:
https://drive.google.com/file/d/1Exi3gZX_tb8AkKLmFChJe-RuDwBJGEfk/view?usp=sharing
Console:
![image](https://user-images.githubusercontent.com/60443759/98118138-0b22c100-1eab-11eb-86b2-d7a7b9577ce3.png)

### 🌍 Environment

| Environment | Version / Name |
YetiForce: 5.1.0-complete
Web server: Apache 2.4.25-3+deb9u9
PHP: v7.2.34
Browser: any
OS: Debian 9.13‬
Database: 10.2.35-MariaDB

### ❓ Additional context

I got recently a MariaDB update:

The following packages were successfully updated:
 galera-3 25.3.31-stretch from MariaDB for by MariaDB repo (previous version: 25.3.30-stretch from MariaDB for by MariaDB repo)
 libmariadb3 10.2.35+maria~stretch from MariaDB for by MariaDB repo (previous version: 10.2.34+maria~stretch from MariaDB for by MariaDB repo)
 libmariadbclient18 10.2.35+maria~stretch from MariaDB for by MariaDB repo (previous version: 10.2.34+maria~stretch from MariaDB for by MariaDB repo)
 mariadb-client-10.2 10.2.35+maria~stretch from MariaDB for by MariaDB repo (previous version: 10.2.34+maria~stretch from MariaDB for by MariaDB repo)
 mariadb-client-core-10.2 10.2.35+maria~stretch from MariaDB for by MariaDB repo (previous version: 10.2.34+maria~stretch from MariaDB for by MariaDB repo)
 mariadb-common 10.2.35+maria~stretch from MariaDB for by MariaDB repo (previous version: 10.2.34+maria~stretch from MariaDB for by MariaDB repo)
 mariadb-server-10.2 10.2.35+maria~stretch from MariaDB for by MariaDB repo (previous version: 10.2.34+maria~stretch from MariaDB for by MariaDB repo)
 mariadb-server-core-10.2 10.2.35+maria~stretch from MariaDB for by MariaDB repo (previous version: 10.2.34+maria~stretch from MariaDB for by MariaDB repo)
 mysql-common 10.2.35+maria~stretch from MariaDB for by MariaDB repo (previous version: 10.2.34+maria~stretch from MariaDB for by MariaDB repo)

**Comment by mariuszkrzaczkowski** [comment]
duplicate  https://github.com/YetiForceCompany/YetiForceCRM/issues/13727
