### ISSUE TITLE
[bug] custom picklist with spaces don't save in values on marketing leads

### ISSUE THREAD

**Issue by shirou93** [YetiForceCompany/YetiForceCRM#13729]
# 🐞 bug report

### ⁉️ Describe the bug

When add new lead status values with spaces they don't save in Software configuration / Processes / Marketing / System settings > Leads Values. When lead status value no have spaces they save automaticly when add.

### 🔥 How to trigger the error

1. Click Software configuration / Standard modules / Fields - Picklists / System settings
2. Click and add value with spaces like "test value"
3. Go to Software configuration / Processes / Marketing / System settings > Leads Values
4. Click Leads and try add new with spaces. Changes will not be saved.
### 👎 Actual Behavior

Don't saved added value.

### 👍 Expected Behavior
Save like other values with no spaces.

### 👷 Testing

- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by davide-alghi** [comment]
Confirm. string with space is not saved in configuration / Processes / Marketing ... 

![Schermata da 2020-11-04 16-33-57](https://user-images.githubusercontent.com/48508691/98131958-234f0c00-1ebc-11eb-8968-9c828a1b8ca1.png)


![Schermata da 2020-11-04 16-35-18](https://user-images.githubusercontent.com/48508691/98131960-23e7a280-1ebc-11eb-9395-810b7d630c14.png)

**Comment by shirou93** [comment]
Polish characters also don't work.

**Comment by shirou93** [comment]
Polish characters also don't work.
