### ISSUE TITLE
[Question] Account Name for Private Individual in YF 6.0

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#13731]
I see that in YF 6.0 the Account Name field for Private Individual, in Accounts module, has been splitted in two parts: First Name and Last Name, two fields.
My question is: how to search for exactly Account Name of Private Individual account?
ie how to search for string "John Smith" in accountname field?

**Comment by mariuszkrzaczkowski** [comment]
you need to add a separator '|##|' , example:  John|##|Smith 
![image](https://user-images.githubusercontent.com/10198654/98222441-1e886780-1f51-11eb-9f6a-82617d682288.png)
![image](https://user-images.githubusercontent.com/10198654/98222449-21835800-1f51-11eb-8349-a83277ea3fb8.png)

**Comment by mariuszkrzaczkowski** [comment]
or you can that way 'John*Smith'
![image](https://user-images.githubusercontent.com/10198654/98223098-f1888480-1f51-11eb-8691-e17c5ad314f7.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski this is very uncomfortable

**Comment by mariuszkrzaczkowski** [comment]
do you have a better idea for it?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski really no :(

**Comment by davide-alghi** [comment]
When I saw, by phpMyAdmin, the separator (|##|) I decided to do this my question issue.

Why does the form give me 2 fields, if it merges values into one single field forcing me to search with special characters or separators?
This choice can lead to problems: e.g. changing of the legal form in detail view.
We take into account that even the "Sole proprietorship" has a "Last name" and a "First name", not just the "Private individual".

You can already manage the account, in YF current stable version, with first and last name: changing labels and adding a field for the first name.
Usually account is searched by filtering with (part of) company name or last name.

Case private individuals only
![Schermata da 2020-11-06 06-48-05](https://user-images.githubusercontent.com/48508691/98332196-8052db00-1ffe-11eb-88cf-a159c25f043b.png)



Mixed case: companies and individuals
![Schermata da 2020-11-06 06-47-37](https://user-images.githubusercontent.com/48508691/98332191-7cbf5400-1ffe-11eb-806a-c10eb7b987c0.png)

**Comment by apcloic** [comment]
Hi,
I've just install YF 6.0 and discover this strange **thing** 👎 
Frankly, I don't understand why you did this.

An account is definitely not a physical person, it's a corporation.
There is already a module for physical person, this is contact module.

Totally agree with @davide-alghi, if someone need a firstname field in Account module, he can simply create a custom field.

Plz, revert back to original account name, this change is really bad idea.

**Comment by apcloic** [comment]
> do you have a better idea for it?

Yes, imo you should revert back because there is no good reason to do this.
An account is a corporation, this is definitely not a physical person, even if there is only one person.
Give accounts a first name if you will but this should be done with custom field, not by design.
