### ISSUE TITLE
[bug] Goods Dispatched Note Correction - impossible to add

### ISSUE THREAD

**Issue by IanMuller** [YetiForceCompany/YetiForceCRM#13733]
You can reproduce it on the official demo.
Adding GDNC ending with error message "Error, please inform the Administrator"

**Comment by waran70** [comment]
In my 5.3 (fresh installation) when I create GDNC it instead of deducting from Storage, it multiplying product number in storage.

**Comment by mariuszkrzaczkowski** [comment]
Does the problem still exist in the newest version?

**Comment by konadrian** [comment]
The problem no longer exists. The ticket has been closed.

**Comment by konadrian** [comment]
The problem no longer exists. The ticket has been closed.
