### ISSUE TITLE
Infinite loading on mail scanner folder configuration[Question] 

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13758]
### Description

I am trying to map folders for mail scanner , and when i click on "Edit Folder" or folder icon there is an infinite loading screen that keeps on loading forever.
Here is screen shot of the problem: 

![Screenshot (77)](https://user-images.githubusercontent.com/40380541/98519715-43564500-2299-11eb-8355-5189568b8371.png)

I left this screen open for 4 hours , yet nothing happens!
How do i fix it?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/98520725-c31ce900-2272-11eb-9cf2-b6bef8cd3cf2.jpg)

**Comment by rskrzypczak** [comment]
duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/12694
