### ISSUE TITLE
[Question] Sold products - inventory

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#13769]
Not sure this is design or some my personal bug here, but:
When I create invoice with certain product, and its status is paid, the number of products in inventory 
is not changing. If this is design, than what is purpose of dealing with storages and all related modules?
I mean It can be used this way, but if system have included invoicing AND inventory management, it would be logical if those are connected out of the box. Maybe I missed something?

**Comment by vovpff** [comment]
Since from Logistic modules appears in yetiforce Invoice does not change products qty on stock. Now you need to add Goods Dispatched Note with Accepted status to recalculate quantities. This is more logical!

**Comment by JohnMaverick** [comment]
Then the warehouse manager has no idea how many items have been sold, and need to do manual inventory at the end of each day? 
OK.

**Comment by bpabiszczak** [comment]
You got the order wrong.

1. First, the warehouseman checks whether he has the goods in stock.
2. If he assembles an item, he creates an issue document from [Goods Issued Note].
3. Then an accounting document is created on the basis of Goods Issued Note [this can be done automatically].

**Comment by JohnMaverick** [comment]
>> Then an accounting document is created on the basis of Goods Issued Note [this can be done automatically].
Seems it won't work out of the box.  It would be very clever if invoice sourcing products not from the Products List but from available storages, so keeping eye on stock will get sophisticated. It looks for me like setting current relation logic has been done on the basis of traditional paperwork. Sure all can be done with the use of workflows/coding but the digital environment giving more opportunities, and setting them as a default solution will be an advantage to the overall project image.

**Comment by waran70** [comment]
Stock update on the basis of "Accepted" invoices looks for me like nice tie. Extending Accounts with Sold Products would create good reporting base

**Comment by deepti4666** [comment]
> Stock update on the basis of "Accepted" invoices looks for me like nice tie. Extending Accounts with Sold Products would create good reporting base

Would love this as well - helps with reporting

**Comment by deepti4666** [comment]
> You got the order wrong.
> 
> 1. First, the warehouseman checks whether he has the goods in stock.
> 2. If he assembles an item, he creates an issue document from [Goods Issued Note].
> 3. Then an accounting document is created on the basis of Goods Issued Note [this can be done automatically].

Any idea - if we can select the available warehouse stock instead of products? (Stock received via goods received note)

**Comment by CHILLTH** [comment]
This workflow is pretty complex. I willing to create a mobile app (sort of POS) and wondering how this can be simplified. Can developer help a bit? Maybe simplified process config can be included in admin settings?
