### ISSUE TITLE
yetiforce setup failure

### ISSUE THREAD

**Issue by scetin47** [YetiForceCompany/YetiForceCRM#13768]

**Comment by scetin47** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/crm-installation
https://www.osradar.com/how-to-install-yetiforce-on-centos-7/
https://computingforgeeks.com/install-yetiforce-crm-on-centos-centos-linux/
https://www.rosehosting.com/blog/how-to-install-yetiforce-on-centos-7/


I did all the bad things on the website, but the setup screen did not appear yet. Would you help me with this topic ?

**Comment by scetin47** [comment]
![Adsız](https://user-images.githubusercontent.com/73686543/98548968-3fcbb980-22ab-11eb-9c09-1ea60b43bea9.jpg)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/98549547-3a667300-229b-11eb-832e-1699ee4c4b69.jpg)

**Comment by scetin47** [comment]
PHP 7.4.12 (cli) (built: Oct 27 2020 15:01:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
[root@Project ~]# mysql --version
mysql  Ver 8.0.22 for Linux on x86_64 (MySQL Community Server - GPL)
-----------------------------------------------------------------------------------------------
[root@Project ~]# cache/logs/phpError.log
-bash: cache/logs/phpError.log: No such file or directory
[root@Project ~]# cache/logs/system.log
-bash: cache/logs/system.log: No such file or directory
[root@Project ~]# cache/logs/errors.log
-bash: cache/logs/errors.log: No such file or directory

**Comment by scetin47** [comment]
Static hostname: Project
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: c4322266e7ba494f9025058baf2aeb13
           Boot ID: 5fc2aab4a03247e0bd5143d0821dbe88
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1127.19.1.el7.x86_64
      Architecture: x86-64
----------------------------------------------------------------------------------------------------------------------
PHP 7.4.12 (cli) (inşa: 27 Ekim 2020 15:01:52) (NTS)
Telif Hakkı (c) PHP Group
Zend Engine v3.4.0, Telif Hakkı (c) Zend Technologies
with Zend OPcache v7.4.12, Telif Hakkı ( c), Zend Technologies
with Xdebug v2.9.8, Telif Hakkı (c) 2002-2020, Derick Rethans
-------------------------------------------------------------------------------------------------------------------------
[root @ Project ~] # mysql
--x86_64 üzerinde Linux için mysql Ver 8.0.22 sürümü (MySQL Community Server - GPL)
[root @ Project ~] # cache / logs / phpError.log
-bash: cache / logs / phpError.log: Böyle bir dosya veya dizin yok
[root @ Project ~] # cache / logs / system.log
-bash: cache / logs /system.log: Böyle bir dosya veya dizin yok
[root @ Project ~] # cache / logs / errors.log
-bash: cache / logs / errors.log: Böyle bir dosya veya dizin yok

**Comment by scetin47** [comment]
<VirtualHost *:80>
     ServerAdmin admin@10.0.0.4
     ServerName 10.0.0.4
     DocumentRoot /var/www/html/yetiforce
     ServerAlias 10.0.0.4

     <Directory /var/www/html/yetiforce/>
          Options FollowSymlinks
          AllowOverride All
          Require all granted
     </Directory>

     ErrorLog /var/log/httpd/yetiforce_error.log
     CustomLog /var/log/httpd/yetiforce_access.log combined
</VirtualHost>

**Comment by mariuszkrzaczkowski** [comment]
![Uploading github.jpg…]()

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/98563816-ea43dc80-22ab-11eb-88d8-f52c3130a81a.jpg)

**Comment by scetin47** [comment]
please, can you help with this?

**Comment by mariuszkrzaczkowski** [comment]
You have not provided the required information, without it we cannot help

**Comment by scetin47** [comment]
He wrote the information above. What other information should I write?

**Comment by scetin47** [comment]
I wrote the information above. What other information should I write?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/98671649-def8bb80-2354-11eb-8927-86197b13d31c.jpg)
