### ISSUE TITLE
[bug] Field order of 'Quick Create' is not saved properly

### ISSUE THREAD

**Issue by LaurensCleyman** [YetiForceCompany/YetiForceCRM#13788]
# 🐞 bug report

### ⁉️ Describe the bug

The field order of the 'Quick Create' fields is not always saved properly.

### 🔥 How to trigger the error

1 - Go to 'Fields - Quick Create'
2 - Change the order a few times and save
3- Result is not always saved correctly

### 👷 Testing

This is the field order that I saved at gitstable.yetiforce.com
![image](https://user-images.githubusercontent.com/16014524/99182749-2ad1a900-2737-11eb-8e3e-251f8e78dc67.png)

This is the field order that a user gets if he is using the quick create option:
![image](https://user-images.githubusercontent.com/16014524/99182766-4f2d8580-2737-11eb-8fd3-9fdfbc8ea7ef.png)

- [X] I confirm that I tested it at https://gitstable.yetiforce.com

**Comment by mariuszkrzaczkowski** [comment]
check on gitdeveloper

![github](https://user-images.githubusercontent.com/10198654/99184856-4bedc600-2746-11eb-9f64-fb5ba5adb7cc.jpg)

**Comment by LaurensCleyman** [comment]
Issue is not on gitdeveloper. I had to check first, sorry.. :-) 

This topic can be closed.
