### ISSUE TITLE
[bug] CSRF-Magic issue after YF5.2=>YF5.3 upgrade

### ISSUE THREAD

**Issue by butuemi** [YetiForceCompany/YetiForceCRM#13781]
Hello,

I upgraded YF 5.2 to 5.3 (ServicePackV4 + SecurityFix) and I encountered an issue when navigating in records detail view.

1. Go to any record Detail View
2. Click on a related module tab
3. Refresh the page
4. Try to click on another related modue tab
5. See error

### 👎 Actual Behavior
Invalid request - Response For Illegal Access (csrf magic related)

### 👍 Expected Behavior
Being able to navigate through a records' related module tabs after page refresh.

`[error] - Invalid request - Response For Illegal Access
App\Exceptions\AppException: Invalid request - Response For Illegal Access in /var/www/html/yetiprod/config/csrf_config.php:21
Stack trace:
#0 /var/www/html/yetiprod/vendor/yetiforce/csrf-magic/src/Csrf.php(243): CSRFConfig::{closure}('')
#1 /var/www/html/yetiprod/vendor/yetiforce/csrf-magic/src/Csrf.php(515): CsrfMagic\Csrf::check()
#2 /var/www/html/yetiprod/app/Controller/Base.php(40): CsrfMagic\Csrf::init()
#3 /var/www/html/yetiprod/modules/Vtiger/views/Detail.php(42): App\Controller\Base->__construct()
#4 /var/www/html/yetiprod/modules/HelpDesk/views/Detail.php(22): Vtiger_Detail_View->__construct()
#5 /var/www/html/yetiprod/include/main/WebUI.php(163): HelpDesk_Detail_View->__construct()
#6 /var/www/html/yetiprod/index.php(28): Vtiger_WebUI->process(Object(App\Request))
#7 /var/www/html/yetiprod/public_html/index.php(11): require('/var/www/html/y...')
`

From what I understand, the Csrf::check() function asks for "_csrf" header, but it is missing in the POST requests if I refresh the page...so it throws the exception. 

2 ajax requests(Notifications and Calendar - they have X-Requested-With header) have this issue, so from what I red on the library docs, the csrf token injection in the ajax request is not done.

Normal Detail View Loading of a problematic request (it has _csrf token, it's ok):
![image](https://user-images.githubusercontent.com/46193414/98825692-789b9800-243d-11eb-9239-6872065a8a7a.png)

Detail View Loading after refresh while on a related module tab (no _csrf token, error 500 and Illegal Acccess):
![image](https://user-images.githubusercontent.com/46193414/98825914-b8627f80-243d-11eb-8aac-506d109ab707.png)
![image](https://user-images.githubusercontent.com/46193414/98826140-08414680-243e-11eb-9424-b11da7d7bbcf.png)

**Comment by butuemi** [comment]
After lot of debugging managed to solve it for now. Nested buffers when request has related module (when refreshing on detail view from a related module tab for example). The Csrf::obHandler($buffer) function's logic failed and the csrf js script (that injects csrf in payloads) was not injected into the html. 

Please, just let me know if this is an issue on my end or if you can reproduce this on 5.3.

FYI, these are the update packages I have: 
![image](https://user-images.githubusercontent.com/46193414/98855922-7baa7e80-2465-11eb-8d63-ebe1586cdf3d.png)

I encountered this on TWO instances after upgrade. If it's not YF Core and is some config, please let me know.

Thank you!

**Comment by rskrzypczak** [comment]
Fix: https://github.com/YetiForceCompany/YetiForceCRM/commit/9eae679fbb1dbf40e1d2cf4d39de82d1fd122f2d

**Comment by butuemi** [comment]
Wow, great, thanks! I had a really nasty fix, this one is better. Cheers!
