### ISSUE TITLE
Why I can't sign in to my e-mail account on YetiForce ?

### ISSUE THREAD

**Issue by Szilard1999** [YetiForceCompany/YetiForceCRM#13789]
### Description
I have done with the email configuration, and when I want to first sign in with oss module, it is just loading and loading and do nothing. Please help.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/99232814-afcdc880-27f2-11eb-9774-15ead3682c64.jpg)

**Comment by davide-alghi** [comment]
Hi @Szilard1999,
it seems you missed the secure protocol in "Name of IMAP server": the format is
```
<protocol>://<imap_address>

where "<protocol>" is "ssl" or "tls"
```

![Schermata da 2020-11-17 10-44-37](https://user-images.githubusercontent.com/48508691/99374386-d0fdea00-28c2-11eb-8471-1a2bd867f789.png)

if you omit the secure protocol, RoundCube try to connect until default_socket_timeout value in you php.ini
then it stops and often it doesn't show any message.
