### ISSUE TITLE
Cant See List of Employees while searching Employee in Member of field

### ISSUE THREAD

**Issue by harshdoshihd** [YetiForceCompany/YetiForceCRM#13799]
Hi Team,

I have created list of few users in the employee module, I can see them in list view, I can even export the complete list in csv, excel format, But when I try to tag an employee to his senior from member of field, I cant see any employee in the search result, same thing happens in opportunity module where I have created an employee reference field using 1:M field to tag employee, there too i cant see any employee in the list.

PN: I have logged in as Administrator

Can you please help me with resolving the issue.

Best Regards,
Harsh
![employee_1](https://user-images.githubusercontent.com/61234565/99695181-46c8a800-2ab3-11eb-9352-de0664d71615.jpg)
![employee_2](https://user-images.githubusercontent.com/61234565/99695202-4defb600-2ab3-11eb-9ccc-c00e10274099.jpg)
![employee_3](https://user-images.githubusercontent.com/61234565/99695217-534d0080-2ab3-11eb-8a61-403054996a97.jpg)

**Comment by Giorgos-Hellene** [comment]
Are employees enabled ?

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/OSSEmployees/models/Module.php#L21
If you employee has status "Employee" than you can see him in this view. You can modified the code or change the status

**Comment by harshdoshihd** [comment]
Thanks Konadrian. it worked!
