### ISSUE TITLE
Products module display No records but the records exist

### ISSUE THREAD

**Issue by samuelsituma** [YetiForceCompany/YetiForceCRM#13795]
Am having a problem with the product module from my home page when i click on the products module i get the list of products as shown.
![Capturhahjae](https://user-images.githubusercontent.com/46498594/99451433-40132700-2933-11eb-907c-0f36c6ba8813.JPG)

But when i select the product from another module i get a table with no records  as shown
![Captujjjjre](https://user-images.githubusercontent.com/46498594/99451643-8a94a380-2933-11eb-82c1-c6f8af38a5ea.JPG)

Any solution to this problem please.

**Comment by davide-alghi** [comment]
Hi @samuelsituma,
without data it's hard (impossible) to help you.
________________
**YF Logs - How To**

1. disable (temporarily) the chat module, in Standard modules / Modules – Installation
2. set (temporarily) CRON execution to 5 minutes or more
3. in config/Debug.php set
   - $LOG_TO_FILE = true;
   - $LOG_LEVELS = false;
4. reset contents for the files:
   - cache/logs/system.log
   - php_errors.log
5. reproduce the issue/bug/problem
6. upload here the files
   - cache/logs/system.log
   - php_errors.log

   
**Browser console - How To** - https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-s-console-file

1. open browser console
2. switch to "Console" tab
3. clean console
3. reproduce the issue/bug/problem
4. save console contents in a file
5. upload here the just created file


**Fill out the Bug Report**
![YetiForceCRM-BugReportTemplate](https://user-images.githubusercontent.com/48508691/99492608-2e02aa00-296e-11eb-84cf-094c7087aee6.png)
