### ISSUE TITLE
[Pytanie] Inspektor uprawnień

### ISSUE THREAD

**Issue by mandrzej57** [YetiForceCompany/YetiForceCRM#13796]
Gdzie znajdę narzędzie "Inspektor uprawnień"? Nie jestem w stanie dostrzec. 

Chyba, że to nie element interfejsu i źle rozumiem opis "Mechanizm inspektora uprawnień (...) prezentuje również uprawnienia do przeglądania, edycji, tworzenia i usuwania co oznacza, że można w szybki sposób sprawdzić z poziomu użytkownika jakie uprawnienia ma przydzielone"

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/99649067-0be35780-2a54-11eb-91d1-cce51ca9f4d8.png)
![image](https://user-images.githubusercontent.com/10198654/99649084-10a80b80-2a54-11eb-8dc0-e7315928def3.png)
