### ISSUE TITLE
ver 1.2.22 - dashboard and modules summary view - there is no add widget button

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#138]
could not add widget to summary view.

**Comment by waw555** [comment]
In Settings, in the widget manager, add the role of

**Comment by bpibiza** [comment]
Reopen: 

![przechwytywanie](https://cloud.githubusercontent.com/assets/10252484/5935605/db94e202-a6dc-11e4-8576-4b56d4b37514.JPG)

**Comment by waw555** [comment]
Add Role

![addrole](https://cloud.githubusercontent.com/assets/1402355/5935678/49a3aafe-a6ff-11e4-8a7d-a4bd09df6f4d.JPG)
![addrole2](https://cloud.githubusercontent.com/assets/1402355/5935679/4be85850-a6ff-11e4-9a6a-9a0c41e3c80f.JPG)

**Comment by bpibiza** [comment]
thx, it works ! 
closed
