### ISSUE TITLE
[Question] Navigation in summary / detail view

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#13807]
Does no one feel that navigation buttons/shortcuts is extremely essential while editing larger set of data? 
Current state make CRM impossible to use with various call centers or other lead generation dudes.
What behind removal of this little useful thing?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/discussions/15466
