### ISSUE TITLE
[Question] new inventory sum_

### ISSUE THREAD

**Issue by crawe1** [YetiForceCompany/YetiForceCRM#13802]
Hello,

I have a question, 
I create a new column for inventory with a weight. 
on my inventory table new columnname is weighttotal.
I tried to grep code by the phrase "sum_total" "sum_gross" in the code but I don't know how they are created? How can I get into the new variable sum_weighttotal? 

![image](https://user-images.githubusercontent.com/61950059/99712681-b3d44180-2aa3-11eb-883e-2b65d02c22cd.png)

**Comment by vovpff** [comment]
For sum total weight there is 3 ways:
* you need to add new invintory field type (difficulty: hard) 
* updating this column by handler (difficulty: normal) 
* using third party pluging (difficulty: easy but need to charge some money for plugin)

**Comment by crawe1** [comment]
how u see 1-2 steps its made on right side colum in table,  but where can i find sum_total or sum_gross function ? i want to do same on example this function.

**Comment by vovpff** [comment]
@crawe1 this can be done by handler.
Or try to grep for them

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/fae267e50b6efdeea9611641319267fadfd5f545/modules/Vtiger/models/Record.php#L1263-L1270

**Comment by crawe1** [comment]
thank you so much !
