### ISSUE TITLE
Can't download new documents any more

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13804]
Hello,

I uploaded some documents as a single document (via Databases -> Documents) or connected to a support ticket or to account.
Everything went fine. These documents are still available in YF CRM and when browsing the document list and pointing with the cursor to document **I get a link shown** like this:

**https://mycrm/file.php?module=Documents&action=DownloadFile&record=1373&fileid=1374**

![Screen 1](https://user-images.githubusercontent.com/13665806/99688945-a78dbb80-2a86-11eb-99bf-b0b91004c486.png)

Two days ago I started creating folders (like IT or Sheets) for documents in _System settings -> Standard modules -> Fields folders_ and also changed the order of that folders.

Now I have the behavior that I still can upload documents, but when browsing to the document list and clicking on the document I only see the document description page in YF. 

![Screenshot_2020-11-19 Dokumente Import](https://user-images.githubusercontent.com/13665806/99689145-e91e6680-2a86-11eb-8ac5-96f066d52e39.png)

Normally the download of the document starts immediately. When clicking in the info page on download I get a blank page.

When browsing the document list and pointing with the cursor to the document name **it also does not show any link like above**.

**I am also not shure about the storage location of that docs?!**

 Found a path like this with some entries:

/var/www/yetiforce/storage/Documents/2020/November/week3

![Screen 2](https://user-images.githubusercontent.com/13665806/99689491-592cec80-2a87-11eb-9dc5-cc6077c5ecfc.png)

But this does not correspond to the file ids. I checked the error logs of apache now and found this now:

`tail -f /var/log/apache2/error.log
[Fri Nov 20 00:00:02.647679 2020] [ssl:warn] [pid 729] AH01909: crm:443:0 server certificate does NOT include an ID which matches the server name
[Fri Nov 20 00:00:02.648117 2020] [mpm_prefork:notice] [pid 729] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1g configured -- resuming normal operations
[Fri Nov 20 00:00:02.648136 2020] [core:notice] [pid 729] AH00094: Command line: '/usr/sbin/apache2'
[Fri Nov 20 08:48:45.006048 2020] [php7:warn] [pid 5940] [client 46.114.3.2:18254] PHP Warning:  move_uploaded_file(/var/www/yetiforce/storage/Documents/2020/November/week3/1698): failed to open stream: Permission denied in /var/www/yetiforce/app/Fields/File.php on line 676
[Fri Nov 20 08:48:45.006125 2020] [php7:warn] [pid 5940] [client 46.114.3.2:18254] PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phpfGD2Tj' to '/var/www/yetiforce/storage/Documents/2020/November/week3/1698' in /var/www/yetiforce/app/Fields/File.php on line 676
[Fri Nov 20 08:49:56.493784 2020] [php7:warn] [pid 13068] [client 46.114.3.2:13843] PHP Warning:  move_uploaded_file(/var/www/yetiforce/storage/Documents/2020/November/week3/1700): failed to open stream: Permission denied in /var/www/yetiforce/app/Fields/File.php on line 676
[Fri Nov 20 08:49:56.493890 2020] [php7:warn] [pid 13068] [client 46.114.3.2:13843] PHP Warning:  move_uploaded_file(): Unable to move '/tmp/php1lf4an' to '/var/www/yetiforce/storage/Documents/2020/November/week3/1700' in /var/www/yetiforce/app/Fields/File.php on line 676`

### 🔥 How to trigger the error

1. Got to Databases -> Documents 
2. Add new document
3. Browse document list and click on new document file name.

### 👎 Actual Behavior

It opens the information page of the document. Clicking on the download button turns a blank page

### 👍 Expected Behavior

Documents can be downloaded. For older documents that works, for new documents of the past 4 weeks it does not work.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3 SF 1
| Web server (name and version)       | Apache/2.4.41 (Ubuntu)                |
| PHP                                 |       7.2         |
| Browser (name and version)          |  Firefox 83.0              |
| Operating System (name and version) |      Ubuntu 20.04.1         |
| Database (name and version)         |          MariaDB  10.3.25    |
| Service Pack version                |          SP 1      |

**Comment by mariuszkrzaczkowski** [comment]
show confreport report

**Comment by blu-IT** [comment]
OK, looking at the rights on the file system something is weired.

Under the path /var/www/yetiforce/storage/Documents/2020/ there are months with access rights www-data and some with root. After a crash of the system in october, this seems to impact the access rights of the file system:

![Screen 1](https://user-images.githubusercontent.com/13665806/99777189-3d225d00-2b12-11eb-949c-97116cce05af.png)

**Comment by blu-IT** [comment]
WOW - OK, after granting/changing permissions to www-data to the folders, everything works fine again!

So, sorry for the huzzle - if someone expierences a similar problem - take a look here ;-)
