### ISSUE TITLE
[bug] Can't download documents any more

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13801]
# 🐞 bug report

### ⁉️ Describe the bug

Hello,

I uploaded some documents as a single document (via Databases -> Documents) or connected to a support ticket or to account.
Everything went fine. These documents are still available in YF CRM and when browsing the document list and pointing with the cursor to document **I get a link shown** like this:

**https://mycrm/file.php?module=Documents&action=DownloadFile&record=1373&fileid=1374**

![Screen 1](https://user-images.githubusercontent.com/13665806/99688945-a78dbb80-2a86-11eb-99bf-b0b91004c486.png)

Two days ago I started creating folders (like IT or Sheets) for documents in _System settings -> Standard modules -> Fields folders_ and also changed the order of that folders.

Now I have the behavior that I still can upload documents, but when browsing to the document list and clicking on the document I only see the document description page in YF. 

![Screenshot_2020-11-19 Dokumente Import](https://user-images.githubusercontent.com/13665806/99689145-e91e6680-2a86-11eb-8ac5-96f066d52e39.png)

Normally the download of the document starts immediately. When clicking in the info page on download I get a blank page.

When browsing the document list and pointing with the cursor to the document name **it also does not show any link like above**.

**I am also not shure about the storage location of that docs?!**

 Found a path like this with some entries:

/var/www/yetiforce/storage/Documents/2020/November/week3

![Screen 2](https://user-images.githubusercontent.com/13665806/99689491-592cec80-2a87-11eb-9dc5-cc6077c5ecfc.png)

But this does not correspond to the file ids.

### 🔥 How to trigger the error

See above.

### 👎 Actual Behavior

See above.

### 👍 Expected Behavior

Documents can be downloaded.

### 👷 Testing

- [X] I confirm that I tested it at https://gitstable.yetiforce.com - could **not** reproduce the error.
- [X] I confirm that I tested it at https://gitdeveloper.yetiforce.com -could **not** reproduce the error.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3 SF 1
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |      Ubuntu          |
| Database (name and version)         |          MariaDB      |
| Service Pack version                |          SP 1      |

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/99709072-fba49a00-2a9e-11eb-8130-20657fd64743.jpg)

**Comment by blu-IT** [comment]
Hello,

due to the fact, that I could not reproduce the error on gitstable and gitdeveloper and also found some messages in the apache2 log I will close this issue and open a "normal" ticket here #13804

Thanks!
