### ISSUE TITLE
[Question] Difference between "Encryption" and "Password Encryption" in System Settings

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13812]
### Description

Hello, 

I am wondering about the difference between the **"Encryption"** and **"Password Encryption"** in System Settings.

![Screenshot_2020-11-22 Passwords Configuration System settings](https://user-images.githubusercontent.com/13665806/99956759-d5287c80-2d86-11eb-884b-b25dcf34df8a.png)

![Screenshot_2020-11-22 Password Setup System settings](https://user-images.githubusercontent.com/13665806/99956776-da85c700-2d86-11eb-91ed-b07a473b017a.png)

While "Password Encryption" is obvoius, in the "Encryption" section is talked about _"sensitive data"_.
_But what is sensitive data?_ In my opinion these are at least database tables like _"vtiger_account"_ or _"vtiger_contactdetails"_

I expexcted the whole database to be encrypted, when turning Encryption on, but even the tables mentioned above **are not encrypted**, when turning Encryption in the System Settings on.

Thanks!

Regards

**Comment by davide-alghi** [comment]
Hi @blu-IT,
both encrypt passwords.

```Security / Passwords - Encryption``` encrypts the field ```password``` in ```Virtual desk / Passwords``` module.

```Security / Encryption``` encrypts following tables fields:
 - roundcube_users.password
 - s_yf_mail_smtp.password
 - a_yf_smsnotifier_servers.api_key
 - u_yf_github.token
 - w_yf_portal_user.password_t
 - w_yf_servers.pass
 - w_yf_servers.api_key
 - dav_users.key

**Comment by blu-IT** [comment]
@davide-alghi 

Thanks!

What about the tables "vtiger_account" or "vtiger_contactdetails"? Are there any plans to encrypt sensitive customer data in the future?

**Comment by davide-alghi** [comment]
Ivan, are you speaking about EU GDPR compliance?
Sorry but I cannot reply you. I don't know.

**Comment by blu-IT** [comment]
Yes, also about EU GDPR compliance - but first of all about enhanced data(base) security. ;-)

Grazie lo stesso, tanti saluti!
