### ISSUE TITLE
[Question] Updating from 5.3.0 to 6.0.0 fails

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#13822]
### Description

I tried to update my version from 5.3.0 to 6.0.0. 

![update](https://user-images.githubusercontent.com/10230144/100100518-3cb2fa80-2e61-11eb-881a-4009e0697738.png)

When trying to download, e.g. pressing the blue download button, I get the following error message:

![error](https://user-images.githubusercontent.com/10230144/100100923-d4b0e400-2e61-11eb-9b64-fbc337a2b238.png)

The URL that fails is

https://www.HIDDEN.net/crm5/index.php?parent=Settings&module=Updates&view=Index&download=4cb51ab06df969fff81d6035873e3824

The yetiforce_update database table contains the following data

![db](https://user-images.githubusercontent.com/10230144/100100888-c82c8b80-2e61-11eb-8150-27455e592bec.png)

I am running apache2 2.4.43 on Linux using php 7.4.12

**Comment by bpabiszczak** [comment]
?

**Comment by diderich** [comment]
> ?

I opened it as a bug using the recommended form!
