### ISSUE TITLE
[bug] Upgrade to YetiForce CRM 6.0.0 v2 - don't work

### ISSUE THREAD

**Issue by Badbagaj** [YetiForceCompany/YetiForceCRM#13829]
This is the alert

Argument 1 passed to App\YetiForce\Updater::download() must be of the type array, null given, called in /*****/*****/*****l/yeti/modules/Settings/Updates/views/Index.php on line 18

Any suggest?

Thx in advance

**Comment by diderich** [comment]
See https://github.com/YetiForceCompany/YetiForceCRM/issues/13823
