### ISSUE TITLE
[bug] Menu setting not open then submenu actived

### ISSUE THREAD

**Issue by caothuyen** [YetiForceCompany/YetiForceCRM#13824]
# 🐞 bug report

### ⁉️ Describe the bug
I update from 5.3.0 to 6.0.0 and setting menu not open then submenu actived.
![yeti1](https://user-images.githubusercontent.com/71112157/100300689-2162ff00-2fc9-11eb-9120-62f76c257b1e.png)
![yeti2](https://user-images.githubusercontent.com/71112157/100300696-245def80-2fc9-11eb-8287-51f8f9ce4ee1.png)

help me!

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |6.0.0
| Web server (name and version)       |         apache2 2.4.43       |
| PHP                                 |        7.4.12        |
| Browser (name and version)          |                |
| Operating System (name and version) |       openSUSE Linux         |
| Database (name and version)         |       mysql MariaDB 10.4.14         |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
I don't think the issue still occurring.
If you still see it, try logging in again and clearing the cache, if that doesn't help, re-create the ticket.
