### ISSUE TITLE
[bug] Recently viewed pages fails when CRM is not installed at the root of the web server

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#13835]
# 🐞 bug report

### ⁉️ Describe the bug

Recently viewed pages fails when CRM is not installed at the root of the web server. The application adds the root URL twice to the link.

In my case, the software is installed at `https://www.XXX.net/crm6/`. Normally accessing pages is done for example using `https://www.XXX.net/crm6/index.php?module=Home&view=DashBoard`. But when accessing recently viewed pages through the icon on the top right of the page, the URL include the root path `crm6` twice, i.e. `https://www.XXX.net/crm6/crm6/index.php?module=Home&view=DashBoard`

https://www.XXX.net/crm6/crm6/index.php?module=Home&view=DashBoard

### 🔥 How to trigger the error

1. Go to 'Recently viewed pages' icon
2. Click on any recently viewed page
3. See error 404, Object not found!

### 👎 Actual Behavior

Clicking on recently viewed page opens link of the form``https://www.XXX.net/crm6/crm6/index.php?module=Home&view=DashBoard` (double /crm6)

### 👍 Expected Behavior

Clicking on recently viewed page should open link of the form``https://www.XXX.net/crm6/index.php?module=Home&view=DashBoard` (single /crm6)

### 👷 Testing

Not applicable, as the test servers install the software in the root

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.0.0 v2
| Web server (name and version)       | apache2 2.4.43                |
| PHP                                 |  7.4.13              |
| Browser (name and version)          |  any              |
| Operating System (name and version) |  openSUSE LEAP 15.1              |
| Database (name and version)         |  10.4.14-MariaDB              |
| Service Pack version                |   YetiForce CRM 6.0.0 v2 |

### ❓ Additional context
None

### ❗️ Inform the community if you solve the problem

No solution known.

**Comment by diderich** [comment]
Problem is solved by replacing the following line
`			<a class="item dropdown-item" href="{$HISTORY['url']}" role="listitem">`
by
`			<a class="item dropdown-item" href="/{$HISTORY['url']}" role="listitem">`, adding `/` in front of the URL
in the file
`layouts/basic/modules/Vtiger/BrowsingHistory.tpl`

**Comment by asperitigroup** [comment]
Many thanks @diderich , I can confirm that the above correction fixes the recent items problem when YF is not installed in the root of the webserver.

**Comment by rskrzypczak** [comment]
@diderich Thanks.
