### ISSUE TITLE
[Question] Session timeout

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#13834]
### Description

How / where can I adjust (lengthen) the timeout before a session is automatically logged out? For me, the timeout in version 6.0.0 seems to be quite short.

![no-activity](https://user-images.githubusercontent.com/10230144/100325684-3e97cd80-2fc9-11eb-890e-cd3ba02bf8f3.png)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/fae267e50b6efdeea9611641319267fadfd5f545/config/Security.php#L89-L90

**Comment by diderich** [comment]
Thanks!
