### ISSUE TITLE
[bug] Language: Undefined labels in English language

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#13830]
# 🐞 bug report

### ⁉️ Describe the bug

The following labels are not defined in the English language

![warning](https://user-images.githubusercontent.com/10230144/100241051-91bf4100-2f33-11eb-88f5-78a607f49a34.png)

### 🔥 How to trigger the error

See above.

### 👎 Actual Behavior

Labels are not translated in English

### 👍 Expected Behavior

Labels are translated in English

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by zazy** [comment]
Got the same problem and solved this way: log out, clear all cookies related to CRM domain, login again ,update language from admin settings.
