### ISSUE TITLE
[bug][PL] Nie działa wybór szablonu maila w trybie odpowiedzi na maila z historii maili

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#13838]
# 🐞 bug report

Przy wejściu do maila przez "Moją Pocztę" można używać funkcji szablonów mailowych. I jest to dobre.
![image](https://user-images.githubusercontent.com/60872592/100397251-f3bd9a80-3048-11eb-881c-a11da496d151.png)

Przy odpisywaniu na maila z poprzez odpowiedź w detalach maila w "Historii maili" (ale też przy mailach powiązanych z kontrahentem, zgłoszeniem, itp) naciśnięcie przycisku "Szablony" nie powoduje żadnej reakcji, a powinien otworzyć popup z listą wyboru szablonów, tak jak w "Mojej Poczcie".
 
![image](https://user-images.githubusercontent.com/60872592/100397725-937c2800-304b-11eb-900c-8c334b851859.png)

 
Kroki do odtworzenia:
1. Wybór maila z "Historii maili"
2. Wywołanie funkcji "Odpowiedz"
2. Naciśnięcie przycisku "Szablony"

### 👎 Bieżące zachowanie
Brak reakcji
### 👍 Oczekiwanie zachowanie
1. Wyświetlenie listy szablonów
2. Wybór szablonu i zastosowanie jego treści w mailu

- [x] Przetestowane na https://gitstable.yetiforce.com w wersji 6.0.0
- [x] Przetestowane na https://gitdeveloper.yetiforce.com w wersji 6.0.2

Poza tym świetny program!

**Comment by espeoceka** [comment]
Mogę potwierdzić, jeżeli roundcube otwiera się w osobnym oknie traci kontekst i nie otwierają się żadne okna ( przyciski modułów oraz szablony ).

**Comment by ghost** [comment]
Także z maila utworzonego z widżetu "emaile" (w Leadach, Kontrahentach, Zgłoszeniach,...), jako odpowiedź ale też jako nowy mail , nie działają ani szablony, ani "Wybierz plik z CRM".

**Comment by mariuszkrzaczkowski** [comment]
Duplicate of #13979
