### ISSUE TITLE
[Question] Using a slightly different terminlogoy (how to)

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#13831]
### Description

I am using a slightly different terminology than YetiForce.

For example, I refer to "Project" as "Engagement", "Service Contract" as "Retainer", etc.

I have currently implemented these changes through editing the language .json files.

Now, when a new language pack is installed, my changes get overwritten.

I am looking for ideas that would allow to best (with minimal effort) synchronize updated languages files with my personal adjustments? Any thoughts how to do this?

**Comment by davide-alghi** [comment]
Hi @diderich,
something is not clear.
how do you edit language labels?

**Comment by diderich** [comment]
I edited the .json files in the languages/en-US directory.

**Comment by davide-alghi** [comment]
Why that? Why don't you use **Edit language** feature?
https://gitdeveloper.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index

**Comment by konadrian** [comment]
Hi!
You can enable the custom folder 
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/Performance.php#L93
If you set this value to true "system will additionally check whether the file exists in the custom directory. Ex. custom/modules/Assets/Assets.php."
So If you add a translation for example into custom/languages/en-Es/_Base.json then it should overwrite orginal value

Or you can use this tool which @davide-alghi mentioned!

**Comment by apcloic** [comment]
@diderich 
Fyi, I'm using @konadrian solution, it works very well.
https://yetiforce.com/pl/component/zoo/item/loader-and-autoloader-of-files
