### ISSUE TITLE
[bug] Update problem from 5.3 to 6.0

### ISSUE THREAD

**Issue by gsportelli73** [YetiForceCompany/YetiForceCRM#13839]
# 🐞 bug report

Error presets when i update CRM from 5.3 to 6.0 on my demo version.

After update i can't login. After it updates i see  error messages.
Error message reports some problem on duplicate name on db. 
I attach log files.

My system 
Shared Host Linux 
php 7.2 

[log_update.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/5607757/log_update.zip)

How do i resolve login problem ?

**Comment by mariuszkrzaczkowski** [comment]
https://public.yetiforce.com/clear.png
