### ISSUE TITLE
Select Price Book Record Shows no Records

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#13846]
I am trying to Select Price Book from Product View, Price Book Popup comes up but does not show any record related to price book. what can be wrong ?

![image](https://user-images.githubusercontent.com/12723595/100532732-03dca200-3222-11eb-9a16-80baf8c24a01.png)

Thanks in advance
Jeevan Pendhari

**Comment by vovpff** [comment]
At first you need to add price book. This price book should have relations for some products.

**Comment by JEEVAN28** [comment]
@vovpff Hi, Thanks for reply, Yes I have added price book. When I go to price book and try to add product same is working good but then when I select product and try to map price book with product, it does not work and shows blank pop up.

What am I doing wrong.

Regards

**Comment by vovpff** [comment]
@JEEVAN28 this is good question.

**Comment by mariuszkrzaczkowski** [comment]
Does the problem still exist in the newest version?
