### ISSUE TITLE
[bug] Inventory table. Difference between numbers on edit and detail view

### ISSUE THREAD

**Issue by aveblackmetalstudio** [YetiForceCompany/YetiForceCRM#13841]
# 🐞 bug report

### ⁉️ Describe the bug

Problem with inventory table. Difference between numbers on edit and detail view
![inventory table](https://user-images.githubusercontent.com/26859846/100460977-691c8000-30c8-11eb-880f-fbc4a80cda34.png)

### 🔥 How to trigger the error

1. Create record for module with enabled inventory table (**SSingleOrders** for example)
2. Fill table with such data as on image
**Discount in total** is group type and equal **11%**
**Tax mode** is group type and equal **23%**  

### 👎 Actual Behavior
As on image

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by apcloic** [comment]
@aveblackmetalstudio I don't think this is a bug, it's related to rouding settings for price, difference may be due to number of decimals parameter in user settings.

**Comment by aveblackmetalstudio** [comment]
> @aveblackmetalstudio I don't think this is a bug, it's related to rouding settings for price, difference may be due to number of decimals parameter in user settings.

Yes, but there is difference between edit table and detail table view in total gross value for example. I think it's not normal.

**Comment by wojturczyn** [comment]
In my opinion, the amounts are calculated differently in the Edit view, Summary view and in the tax and discount setting panel.

In the photo below (Edit) we have the values:
Discount summary 176, but the sum in the Discount column is 175.99
Tax summary 229.38, but the sum in the TAX column shows 229.39
Following this path, Gross does not comply with Price after Discount + TAX

![Edit](https://user-images.githubusercontent.com/39294802/101144715-07ed3300-3619-11eb-86dc-48b88737f130.png)


Now what we have in the photo below (Summary):
In both places, the discount is equal to 176.00
In both places, the tax is consistent 229.38
Gross does not match as sum Price after discount + TAX (sum equals 1226.69)

![SummaryView](https://user-images.githubusercontent.com/39294802/101144734-120f3180-3619-11eb-8a48-884765c9b1cf.png)


In my opinion, there is no consistency in the method of calculating amounts. Once it is counted as the sum from the column, once the amounts are calculated from the net sum / discount sum.

Currently, we have a problem that when entering the amounts and obtaining the gross amount (the last cell in the table under Gross), we encounter a situation where the amount crossover is over 0.01

Additionally, the tax setting panel below in the edit view:
here again, the discount is calculated from the price before discount and it gives 176.00 and we see that the table is 175.99

![Discount](https://user-images.githubusercontent.com/39294802/101144811-2bb07900-3619-11eb-8546-d493774ca21d.png)


Please let me know which amounts are good and why is there a difference between the table in the edition and the preview?
Tested on the latest version of gitstable 6.1.0 (on 12/03/2020).


Tests performed on the following parameters: 23% tax and 15% discount

Thank you

**Comment by wojturczyn** [comment]
I will be grateful if someone confirms whether the error occurs or not.

**Comment by waran70** [comment]
apcloic, try to talk to accountant about that. That will shade a little light :)  


>@apcloic commented 10 days ago
>aveblackmetalstudio I don't think this is a bug, it's related to rouding settings for price, difference may be due to number of >decimals parameter in user settings.

**Comment by rskrzypczak** [comment]
Thanks for the report and a clear description of the problem.
It indeed is an error, we will do our best to fix it before the new version is released.

**Comment by wojturczyn** [comment]
@rskrzypczak 
Thank you for confirming the error. We offer help if we get tips on where to modify the conversion functions and a suggestion what this may result from.

**Comment by rskrzypczak** [comment]
Fixed in YF7
