### ISSUE TITLE
[bug] 'Edit fields' function no longer works after updating to version 6.1.0

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#13859]
# 🐞 bug report

### ⁉️ Describe the bug

The system fails with the error message `Call to a member function get() on null.` when executing the administrative menu function Edit fields in Standard modules.

[https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index](url)

![error](https://user-images.githubusercontent.com/10230144/100759409-dc87ff80-33f0-11eb-832a-e9a98fc57496.png)

### 🔥 How to trigger the error

Go to administrative menu function Edit fields in Standard modules.

1. Go to administrative menu function Edit fields in Standard modules.
2. Error is displayed

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

```
Error: Call to a member function get() on null in cache/templates_c/basic/514042598f584e417ce66000b3cb768510b2f288_0.file.Index.tpl.php:56
Stack trace:
#0 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5fc653424505b9_07160998()
#1 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#3 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#4 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#5 include/runtime/Viewer.php(207): Smarty_Internal_TemplateBase->display()
#6 modules/Settings/LayoutEditor/views/Index.php(79): Vtiger_Viewer->view()
#7 modules/Settings/LayoutEditor/views/Index.php(30): Settings_LayoutEditor_Index_View->showFieldLayout()
#8 include/main/WebUI.php(189): Settings_LayoutEditor_Index_View->process()
#9 index.php(28): Vtiger_WebUI->process()
#10 public_html/index.php(11): require('/home/gitdevelo...')
#11 {main}#0 [error] Call to a member function get() on null
Error: Call to a member function get() on null in cache/templates_c/basic/514042598f584e417ce66000b3cb768510b2f288_0.file.Index.tpl.php:56
Stack trace:
#0 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5fc653424505b9_07160998()
#1 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#3 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#4 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#5 include/runtime/Viewer.php(207): Smarty_Internal_TemplateBase->display()
#6 modules/Settings/LayoutEditor/views/Index.php(79): Vtiger_Viewer->view()
#7 modules/Settings/LayoutEditor/views/Index.php(30): Settings_LayoutEditor_Index_View->showFieldLayout()
#8 include/main/WebUI.php(189): Settings_LayoutEditor_Index_View->process()
#9 index.php(28): Vtiger_WebUI->process()
#10 public_html/index.php(11): require('/home/gitdevelo...')
#11 {main}
```
### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0

**Comment by diderich** [comment]
A similar problem exists with `Fields - Quick Create`

**Comment by diderich** [comment]
The problem stems from the line `{assign var=BLOCK_ICON value=$BLOCK->get('icon')}` in file `layouts/basic/modules/Settings/LayoutEditor/Index.tpl` and `layouts/basic/modules/Settings/QuickCreateEditor/Index.tpl` referencing the not defined `$BLOCK` variable.

**Comment by diderich** [comment]
Replacing `$BLOCK` by `$BLOCK_MODEL` in `{assign var=BLOCK_ICON value=$BLOCK->get('icon')}` in the two mentioned `Index.tpl` files solves the problem.

**Comment by rskrzypczak** [comment]
Thanks a lot, 
but you know, you can push a pull request by yourself, I won't mind :)

**Comment by rioshaz** [comment]
![image](https://user-images.githubusercontent.com/54880467/100851478-4b299380-34ab-11eb-8fb3-3328082def59.png)


it does make the error go away but then u get this strange title on blocks.. see image

**Comment by vovpff** [comment]
@rioshaz I'm not sure but you replaced wrong code

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index
I do not see the error, probably upload the patch myself, this results in an error

**Comment by JEEVAN28** [comment]
I faced same issue and resolved with this help. Thanks
