### ISSUE TITLE
Portal 2.0 - ideas

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#1385]
One of our customers placed an order that involves the development of our Customer Portal and an enhancement of functionalities. This would include:

1. A possibility to view data in different companies [on the basis of hierarchy]. 
2. A greater control over search and sorting. 
3. An increased interaction from the Customer Portal level [e.g. a possibility to accept documents]. 
4. An upload of documents [not only in tickets]. 
5. A possibility to control which fields will be visible in the Portal.

At the moment we can see many drawbacks of the Customer Portal that is why we are planning to write it again. We are going to do it for the next 2-3 weeks and there should be a new version ready for tests by the end of July. If you would like to have any additional functionalities, we are eager to read about your suggestions.

**Comment by bpabiszczak** [comment]
New design:
![search](https://cloud.githubusercontent.com/assets/10197525/8616253/099c98b4-26fa-11e5-8fbd-bb5720ee4f09.jpg)
![login](https://cloud.githubusercontent.com/assets/10197525/8616256/09a1d554-26fa-11e5-96d2-0a27c33e99b1.jpg)
![help_desk](https://cloud.githubusercontent.com/assets/10197525/8616254/099d45fc-26fa-11e5-97f2-cba4eb8ad07b.jpg)
![calendar](https://cloud.githubusercontent.com/assets/10197525/8616255/099e56cc-26fa-11e5-8128-ac4560daed00.jpg)

**Comment by waw555** [comment]
Add the ability to change the background and logo

**Comment by eptapsyxos** [comment]
Wow!
Looking forward,to test it.
I think only in real action we could express a strong opinion.
The portal will work with custom modules too?

**Comment by reeid** [comment]
Neat and nice. 
What is behind curtain? Is it mobile devices friendly?
When will be pushed to testing?

**Comment by bpabiszczak** [comment]
1. The logo can be replaced with a custom one.
2. The background can be replaced or deleted.
3. The portal will support custom modules.
4. The portal is based on Bootstrap.
5. We will publish the portal when it is ready for testing. The progress can be observed here: https://github.com/YetiForceCompany/YetiForcePortal2/tree/developer

**Comment by mariuszkrzaczkowski** [comment]
we plan to use the library Snap.js what you do you think?
https://github.com/jakiestfu/Snap.js/

**Comment by eptapsyxos** [comment]
Seems smart and convenienced for the two sides of the menus of yetiforce.
In a quick test on iPad mini it works like a charm.

**Comment by reeid** [comment]
cool... but because menus looks attractive it would be great to keep it open as a default. 
How it will work with quick edit fields? If I click over field, it may just open it instead slide menu in/out..

**Comment by amicheals** [comment]
This is a great idea.

Be able to customize dashboard with widgits for customers

An area where we can write news or posts

Customer be able to order products/services. Like a store based on the "products" module with price sheets depending on the customer or group

Payment gateway for payments or recurring billing

Searchable FAQ

Form repository for customers to download standard forms

My suggestions

Thank you

**Comment by reeid** [comment]
amicheals, you gone fare man... fingers crossed it could be achieved :)

**Comment by amicheals** [comment]
I have a developer doing some of these now. Iet me know how to contribute to the project.

**Comment by bpabiszczak** [comment]
What does he do exactly?

1. He adds functionalities to the existing customer portal [if so, then to which version?]

2. He creates a completely new customer portal [if so, then what will be new in comparison to the current version?]

3. He creates a new template to the existing customer portal [if so, then at what stage is it and what does the new design look like?]

**Comment by amicheals** [comment]
Adds functions to the existing portal.
Fixes issues with any bugs.

Has not changed design of portal

Right now qorking on a global search for FAQ with a search box on top of FAQ

Listing FAQ buy contact group. I have sales people that will is the portal and i dont want customers seeing internal FAQ

Adding a link at yhe bittom of the FAQ to directly open a support ticket in case the faq disnt answer the question.

**Comment by amicheals** [comment]
Changing the answer box so I can add links, pictures, videos embeds.

**Comment by bpabiszczak** [comment]
Thank you for all your comments and ideas. We will take them into consideration while designing the portal [I hope we can realize most of them]. When we finish the first version we will publish it and you will be able to test it the same way you can test the gitmaster and gitdeveloper versions. By default, the portal will have the clean bootstrap appearance, after about 2 – 3 months we will create a new template according to the pictures above.

After the publication we will once again ask for your comments and ideas. I'm closing the issue.
