### ISSUE TITLE
Menu items displaying wrong

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13851]
Updated yf from 5.3 to 6.0..
many menu items show label name then actually name..
see image...
<img width="956" alt="error" src="https://user-images.githubusercontent.com/54880467/100642159-6fc42500-335e-11eb-8ac1-1d576beb5781.png">

<img width="953" alt="error" src="https://user-images.githubusercontent.com/54880467/100642322-a7cb6800-335e-11eb-88ea-584760adc125.png">

i have update rnglish language but still no change...

**Comment by davide-alghi** [comment]
Hi @rioshaz,
did you try this?
https://github.com/YetiForceCompany/YetiForceCRM/issues/13830#issuecomment-733840629

**Comment by rioshaz** [comment]
yes i tried that,, no help..

i deleted  "in-en" language and then added it again and it fixed my problem..
thanks a lot @davide-alghi
