### ISSUE TITLE
Mail Scanner not working after update 5,3 to 6.0

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13856]
HI guys,
My mailscanner has stopped working after the upgrade form 5.3 to 6.0..
Normal it was configured to "create helpdesk " but i cant see new emails into the tickets anymore..
can anyone help...

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/100721805-1a206480-33c0-11eb-98c5-67946dfcbcd6.jpg)

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski ,

My mail scanner has stopped working after the upgrade form 5.3 to 6.0..

i dont know the reason and cron logs i have attached,,, 

In the mail scanner section i have included "create email msg" and "create helpdesk".. so normally it should scan the email and create a ticket for all emails,.. as it use to do before.."

![ConfReport](https://user-images.githubusercontent.com/54880467/100731152-06412680-33f1-11eb-8887-478ffb1d47fa.png)

[cron.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5622011/cron.log)

**Comment by mariuszkrzaczkowski** [comment]
you need to turn on full logs,
saying that something is not working it will do nothing,
without a detailed description and analysis, we will not do anything

**Comment by rioshaz** [comment]
how to turn on full logs ?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/100738748-5a8add00-33d6-11eb-84ac-46665a12a5f9.jpg)

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski pls check
sry have posted in another thread 
https://github.com/YetiForceCompany/YetiForceCRM/issues/13861#issuecomment-737241006

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski  sry friend but the solutions doesnt work... scanner still not making tickets... pls help

**Comment by mariuszkrzaczkowski** [comment]
I tested the whole mechanism, I don't know what your bugs are,
I don't have enough information to diagnose it
you need to give more information

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski   it works now but I have to include both : "Create email message" and "create a helpdesk".
 if remove the "create email message" then it doesn't work..

before only "create helpdesk"  selected made tickets...
so what would be the issue..

![image](https://user-images.githubusercontent.com/54880467/100977907-a91bb100-3567-11eb-8dfe-f3fac176ec62.png)

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski i have to manually check a email and then it gets shows in ticket...doesnt happen automatically

anyways can u tell me how to clean cache manually ? because cron doesnt do it...
![image](https://user-images.githubusercontent.com/54880467/100985596-2f3cf500-3572-11eb-85c2-cfa4a5590122.png)

**Comment by rioshaz** [comment]
> @mariuszkrzaczkowski it works now but I have to include both : "Create email message" and "create a helpdesk".
> if remove the "create email message" then it doesn't work..
> 
> before only "create helpdesk" selected made tickets...
> so what would be the issue..
> 
> ![image](https://user-images.githubusercontent.com/54880467/100977907-a91bb100-3567-11eb-8dfe-f3fac176ec62.png)

when i manually go the email and check a email or msg and then when i go n refresh tickets the email is added to tickets ,, else its not adding automatically.. why buddy

**Comment by rioshaz** [comment]
> I tested the whole mechanism, I don't know what your bugs are,
> I don't have enough information to diagnose it
> you need to give more information

![image](https://user-images.githubusercontent.com/54880467/101090686-0bfb5f80-35dd-11eb-9953-c251d465a250.png)
![image](https://user-images.githubusercontent.com/54880467/101090728-1ae21200-35dd-11eb-81e5-30bd9d3e6c37.png)
![image](https://user-images.githubusercontent.com/54880467/101090860-4fee6480-35dd-11eb-9b22-57cd47e727fd.png)
![image](https://user-images.githubusercontent.com/54880467/101090891-5c72bd00-35dd-11eb-8571-6896690f8ed8.png)

@mariuszkrzaczkowski  same problem as git stable... email doesnt attach to tickets.... so how can u say its working fine...
please look into the matter sir.

I have sent an email subject : final ticket test and it wont show in tickets,, until i go the mailbox click n it and then when i go back an refresh it shows in tickets...

same things is happening with me.. pls look into..

![image](https://user-images.githubusercontent.com/54880467/101091994-f25b1780-35de-11eb-9586-ef1a012603cb.png)
 cron has ran but nothing in tickets.. it will show once u manually read the msg then it will show in tickets..

@mariuszkrzaczkowski 
@paula-w 
@KatarzynaUlichnowska 

pls help

**Comment by blu-IT** [comment]
I can confirm the problem with the mailscanner:

I have configured the actions "Create e-mail message" and "Create Helpdesk" and there are no new tickets listed, when the e-mail was not read before. Cron jobs are running an executed.

I am running latest YetiForce CRM 6.1 Service Pack v7. With V. 5.3 SP4 it was working. After the upgrade it is not working any more.
