### ISSUE TITLE
[Pytanie]  Uprawnienia do eksportu leadów dla konkretnego użytkownika

### ISSUE THREAD

**Issue by mandrzej57** [YetiForceCompany/YetiForceCRM#13865]
Jak dodać uprawnienia jak w temacie? 
Mam zdefiniowaną rolę "Dział spredaży", przypisany do niej profil. W nim nie zezwalam na eksport, no nie chcę, aby wszyscy użytkownicy z działu sprzedaży mogli eksportować. 
Ale jest potrzeba, aby jeden mógł. Czy można i jak nadawać takie uprawnienia dla konkretnego użytkownika, jakby nadpisujące ten aspekt uprawnień (eksport leadów) pochodzący z roli (a tam z kolei z profilu "ogólnego" przypisanego tej roli)?
Dziękuję z góry za pomoc.

**Comment by bpabiszczak** [comment]
Uprawnienia nadaje się "profilem" aby dwie różne osoby miały różne uprawnienia, muszę mieć różne role. 
Możesz przepisać kod, aby profil był przypisywany bezpośrednio do użytkownika, ale wówczas wymaga to wielu godzin prac programistycznych.
