### ISSUE TITLE
[bug] Can't download new documents any more / wrong ownship on storage filesystem

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#13869]
# 🐞 bug report

Hello,

I am refering to an old issue https://github.com/YetiForceCompany/YetiForceCRM/issues/13804 that I had fixed for myself, but now happend again:

After uploading some documents, I cant download them any more.
I saw now, that on the filesystem there is the same problem as last month. 

**New files & folders** in 

/var/www/yetiforce/storage/Documents/2020/

**are created with ownership root:root and not www-data:www-data**

/var/www/yetiforce/storage/Documents/2020/**December**

So first the upload from the YF interface seems to work, but when trying to download a file I get a blank page again.
After fixing the ownership of the filesystem (see here https://github.com/YetiForceCompany/YetiForceCRM/issues/13804 ) I can upload and download new documents. Documents uploaded while the filesystem was with wrong rights, are still not available (any more). Even if they seem to be stored stored on the file system. 

### 🔥 How to trigger the error

1.  Got to Databases -> Documents
2.  Upload new document
3. Browse document list and click on new document file name.

### 👎 Actual Behavior

It opens the information page of the document. Clicking on the download button turns a blank page

### 👍 Expected Behavior

Documents can be downloaded. For older documents that works, for new documents of the past 4 weeks it does not work.

### 👷 Testing

- [X ] I confirm that I tested it at https://gitstable.yetiforce.com - I cloud **not reproduce** here.
- [X ] I confirm that I tested it at https://gitdeveloper.yetiforce.com - I cloud **not reproduce** here.

### 🌍 Your Environment

Environment | Version / Name
-- | --
YetiForce | 5.3 SF 1
Web server (name and version) | Apache/2.4.41 (Ubuntu)
PHP | 7.2
Browser (name and version) | Firefox 83.0
Operating System (name and version) | Ubuntu 20.04.1
Database (name and version) | MariaDB  10.3.25
Service Pack version | SP 1

### ❗️ Inform the community if you solve the problem

After fixing the ownership of the filesystem (see here https://github.com/YetiForceCompany/YetiForceCRM/issues/13804 ) I can upload and download new documents.

**Comment by mariuszkrzaczkowski** [comment]
It's not a system error.
You have incorrectly configured permissions in the operating system, please contact your administrator.
The server must be correctly configured for the CRM to work properly.
Please read the https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements
