### ISSUE TITLE
[bug]  Status change hangs  system when in record preview mode

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13860]
I have tested the same error on your gitstable version too..

when we  view leads by "Record preview list " then when u change lead status on any lead the system hangs and doesnt complete, it keeps loading

<img width="953" alt="eroor" src="https://user-images.githubusercontent.com/54880467/100847756-372f6300-34a6-11eb-9495-b8ac36496e59.png">

**Comment by rioshaz** [comment]
changing public_html/layouts/basic/modules/Leads/resources/Detail.js  doesnt fix the problem...

![image](https://user-images.githubusercontent.com/54880467/100865672-a2d0fa80-34bd-11eb-95d3-8c30a8053605.png)

**Comment by mariuszkrzaczkowski** [comment]
test on https://gitdeveloper.yetiforce.com/

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski so how can i fix that in my 6.1 ?

**Comment by rskrzypczak** [comment]
`
changing public_html/layouts/basic/modules/Leads/resources/Detail.js doesnt fix the problem...
`

change in the file /config/Developer.php:
public static $MINIMIZE_JS = true;
to
public static $MINIMIZE_JS = false;

**Comment by rioshaz** [comment]
@rskrzypczak thanks a lot it fixes the issues....
