### ISSUE TITLE
[Question] Upgrade guide from 5.3 to 6.0

### ISSUE THREAD

**Issue by ciberfox** [YetiForceCompany/YetiForceCRM#13862]
Hello,
I am having several problems updating from version 5.3 to version 6.0.

Specifically, I get several errors in updating some tables on the database.
is it possible to have a guide to update?

I downloaded the zip package and uploaded it to the admin interface. After the first checks the system freezes giving a problem on the management of autoincrements on a table.

Thanks a lot

**Comment by rioshaz** [comment]
@ciberfox i wont suggest you to upgrade as of now..

as 6.0 has serious issues.... scanners stops, workflows dont work, frequent log outs (6.1 updates fixes it but then edit fields dont work then u have to search forum & find a fix) .. leads status dont change in record preview list ,,, these are some which i have noticed... yet to find  many more i guess...

does gives few new improvements but if scanner n wf dont work its no use...

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/100870037-3f83a000-349e-11eb-9d40-23c5659b47f6.jpg)

**Comment by rioshaz** [comment]
@MacarenaReina  please check
sry have posted reply in another thread :  https://github.com/YetiForceCompany/YetiForceCRM/issues/13861#issuecomment-737241006

**Comment by ciberfox** [comment]
![image](https://user-images.githubusercontent.com/22546170/100908906-5a6d0900-34cc-11eb-901c-769fa9debf43.png)

![image](https://user-images.githubusercontent.com/22546170/100908981-6e186f80-34cc-11eb-8542-bc7d7bb5c5ac.png)

![image](https://user-images.githubusercontent.com/22546170/100909246-c2235400-34cc-11eb-9206-e3b81415674a.png)

SQLSTATE[HY000]: General error: 3780 Referencing column 'attachmentsid' and referenced column 'crmid' in foreign key constraint 'fk_1_vtiger_attachments' are incompatible. The SQL being executed was: ALTER TABLE `vtiger_attachments` CHANGE `attachmentsid` `attachmentsid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

**Comment by ciberfox** [comment]
I get the following error, using the system update procedure. By uploading the 5.3.0_to_6.0.0_v3.zip file, after accepting the license you get the following

current installed version is 5.3.0 SP4 security update v1


![image](https://user-images.githubusercontent.com/22546170/100909659-4c6bb800-34cd-11eb-99d8-c7897f0c1cbe.png)


SQLSTATE[HY000]: General error: 3780 Referencing column 'attachmentsid' and referenced column 'crmid' in foreign key constraint 'fk_1_vtiger_attachments' are incompatible. The SQL being executed was: ALTER TABLE `vtiger_attachments` CHANGE `attachmentsid` `attachmentsid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

**Comment by mariuszkrzaczkowski** [comment]
attach full update logs

**Comment by Andrew-W-Robinson** [comment]
I have the same error.

**Comment by mariuszkrzaczkowski** [comment]
You don't submit the required information so how we are supposed to help?

**Comment by ciberfox** [comment]
I will provide the log this evening so that I can snap the machine and perform the update procedure again.
Thanks for support

**Comment by Andrew-W-Robinson** [comment]
![ConfReport(2)](https://user-images.githubusercontent.com/44470210/101191350-79e16e80-3651-11eb-82ad-0b5fa4b7661c.png)
[Upload Log.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/5644170/Upload.Log.txt)

I have uploaded version 6.0 and proceeded to accept terms, closed off all running crons and the update fails with the above error

**Comment by Andr198** [comment]
I have the same problem
![ConfReport (3)](https://user-images.githubusercontent.com/62097187/101881126-e09fe400-3b8b-11eb-99d3-bce0153011ce.png)
[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5678024/updateLogsTrace.log)
[Importer.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5678042/Importer.log)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5678086/system.log)

**Comment by ciberfox** [comment]
Hi I am attaching the log for the v5 update of the package.
I get the same error

![ConfReport](https://user-images.githubusercontent.com/22546170/101922167-12399f00-3bce-11eb-8a1f-3d56e930f700.png)



[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5679923/updateLogsTrace.log)
[Importer.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5679947/Importer.log)
Thanks for support
Best Reguards

**Comment by ciberfox** [comment]
Hi, I tried using the v6 update. The same error always occurs

**Comment by MaxPegankin** [comment]
SQLSTATE[HY000]: General error: 3780 Referencing column 'attachmentsid' and referenced column 'crmid' in foreign key constraint 'fk_1_vtiger_attachments' are incompatible. The SQL being executed was: ALTER TABLE `vtiger_attachments` CHANGE `attachmentsid` `attachmentsid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;.
![ConfReport](https://user-images.githubusercontent.com/54612661/103403248-6bbc3a80-4b8a-11eb-88da-a40f5b0e53cc.png)
[update.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5756859/update.log)
[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5756860/updateLogsTrace.log)
[errors.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5756861/errors.log)

**Comment by rohanjhanepal** [comment]
> 
> 
> @ciberfox i wont suggest you to upgrade as of now..
> 
> as 6.0 has serious issues.... scanners stops, workflows dont work, frequent log outs (6.1 updates fixes it but then edit fields dont work then u have to search forum & find a fix) .. leads status dont change in record preview list ,,, these are some which i have noticed... yet to find many more i guess...
> 
> does gives few new improvements but if scanner n wf dont work its no use...

how do i fix edit fields not working issue

**Comment by ciberfox** [comment]
@rohanjhanepal 
yes, i know version 6.0 has several bugs, but it is possible to upgrade an environment in production.
The fix could be, delete the query from the update file but not then run into further problems.
I'm not the only one with this update error.

**Comment by Andr198** [comment]
Problem because we use Mysql 
Foreing keys must be the same typr as the id they are referencing.

Еhere will be fixes or need to migrate to MariaDb ???

**Comment by mariuszkrzaczkowski** [comment]
> @rohanjhanepal
> The fix could be, delete the query from the update file but not then run into further problems.

I do not recommend

All your issues result from incorrect updates that YOU HAVEN'T FIXED but you keep using the CRM and keep blaming us!!!

> [ERROR] SQLSTATE[HY000]: General error: 1833 Cannot change column 'attachmentsid': used in a foreign key constraint 'fk_2_vtiger_salesmanattachmentsrel' of table 'buco_crm1.vtiger_salesmanattachmentsrel'
The SQL being executed was: ALTER TABLE `vtiger_attachments` CHANGE `attachmentsid` `attachmentsid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;|#0 /home/buco/domains/british-utilities.co.uk/public_html/crm1/vendor/yetiforce/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `vt...')

This issue only appears when the vtiger_salesmanattachmentsrel table exists. This table was removed in version 4.4.0, which means that the **update from 4.3 to 4.4 was unsuccessful.**

Another issue from the logs:
> E_WARNING: file_put_contents(/home/yetiforce/html/cache/security/dependency.json): **failed to open stream: Permission denied in** /home/yetiforce/html/app/Security/Dependency.php, line 71

The error results from incorrect server configuration, not all parameters can be verified in Server configuration (ConfReport), we're trying to develop it but not everything is possible to verify.


Show me a screenshot from Software configuration > Logs > Updates

**Comment by ciberfox** [comment]
Hi, my system was installed starting from version 5.2. I am attaching the screen

![image](https://user-images.githubusercontent.com/22546170/104742819-36e3e200-574b-11eb-99ba-826ffbddae77.png)

**Comment by rskrzypczak** [comment]
YetiForce version 5.3 is not fully compatible with MySQL 8 (mainly because of yii2, which is not compatible with it.) and PHP7.4.
I advise against performing the update on this configuration.
If you insist, upload this patch https://github.com/yiisoft/yii2/commit/f1aaa0de89c017d58afbd565d3ec3529fad6b4ea which should fix the problem https://github.com/YetiForceCompany/YetiForceCRM/issues/13862#issuecomment-737387345, but take it at your own risk.

**Comment by Andr198** [comment]
Thank you. Рatch worked.

**Comment by MaxPegankin** [comment]
Patch is really working! 
Replace Schema.php in vendor/yetiforce/yii2/db/mysql with patched one.
