### ISSUE TITLE
[Security] Access limitation to https://gitstable.yetiforce.com/ and the other one

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#13867]
Some certain countries as well as VPN IP's cannot access demo versions. 
Why?

**Comment by mariuszkrzaczkowski** [comment]
can you give an example
we don't limit access, maybe it's some other restrictions

**Comment by davide-alghi** [comment]
@waran70,
what does it mean ```cannot access demo versions```?
can't you reach login page or can't you login to YF?
