### ISSUE TITLE
Scroll issue on perfect-scrollbar items

### ISSUE THREAD

**Issue by zazy** [YetiForceCompany/YetiForceCRM#13863]
I'm having a problem with scroll speed on elements where perfectScrollbar is used. As an example I attach a demo gif where I scroll down the left menu of system configuration area. 

To reproduce the problem:
1. go to Configuration (the gear icon in the top right corner)
2. Make sure the left menu is visible by pinning it
3. expand a menu item with many entries like Standard modules. 
4. put the mouse cursor over the menu and track the wheel down as much as you can

As you can see only one more menu item become visible from the bottom. To scroll the whole menu you have to make a whole wheel round for 13 times (on this screen). I'm pretty sure this is not the intended behaviour and this makes scrolling a real pain.
It seems that wheelSpeed parameter is too low.

To furthermore explain what I mean at this page: http://www.jque.re/plugins/scrollbars-onscroll/perfect-scrollbar/index.html 
there are three examples. The first one is the way Yetiforce behaves, the second one is the desired behavior

I'm using Chrome 87.0.4280.66 (got the same problem for sure from version 78) and Firefox 83.0

Don't know if this is a bug or a feature request.
![Peek 02-12-2020 13-49](https://user-images.githubusercontent.com/10668286/100876058-2a5f3f00-34a7-11eb-8d2a-0a57abec1b7c.gif)

**Comment by rioshaz** [comment]
@zazy  mine moves 2-3 lines but its still slow and not fuild as it should be

**Comment by zazy** [comment]
Anyone have any idea on how to solve this? Can someone please point me at where the script is so that I can try to solve it by myself? I found it in a .map but I suppose it's in a minified js file or embedded somewhere else.
This issue makes Yetiforce menu really frustrating to use.

**Comment by konadrian** [comment]
The problem no longer exists. The ticket has been closed.
