### ISSUE TITLE
[Question] - Cel Wizyty

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#13864]

**Comment by zimart** [comment]
Coś uciekło. Mam pytanie, czy można wyłączyć jakoś wyskakujące okienko "podaj cel wizyty". Dosyć irytujące.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/20f376f9c8ea5866f80e7eb6e77c4fc246bcb10e/config/Security.php#L197-L198

**Comment by bpabiszczak** [comment]
Bo na koncie admina się nie pracuje :) Ono służy do administrowania systemem...
