### ISSUE TITLE
[bug]  missing email from field and auto search email 

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13876]
tested on gitdeveloper

lead name : Tommax. FHU
email id : jacob@tester.com  does show in drop-down list.. when composing a new email. normally it should auto-populate,,

![image](https://user-images.githubusercontent.com/54880467/101153589-a776e980-364a-11eb-9fad-255df11b8028.png)

Related email modules missing from field..see pic
![error](https://user-images.githubusercontent.com/54880467/101154132-53b8d000-364b-11eb-9c83-9aea39e372be.png)

also related emails dont show until reset manually...

please help

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski @paula-w  can anyone help pls

**Comment by mariuszkrzaczkowski** [comment]
We tested this on the current version and it appears that the bug doesn't exist anymore
