### ISSUE TITLE
[bug] Call to a member function get() on null on Module Field editing Yetiforce 6.1

### ISSUE THREAD

**Issue by kseibi** [YetiForceCompany/YetiForceCRM#13872]
# 🐞 bug report

### ⁉️ Describe the bug

Just installed Yetiforce 6.1, all seems good but whenever clicking on "edit any modules fields", I am getting this error, the exact same error exists on gitstable.yetiforce.com:

![Click1](https://user-images.githubusercontent.com/74230891/101112751-fc017100-3618-11eb-93b2-1014317899b4.png)

### 🔥 How to trigger the error

1. Go to 'Admin Panel'
2. Click on 'Standard Modules'
3. Scroll down to 'Edit Fields'
4. Above message appears, on all modules

### 👎 Actual Behavior

Cannot edit the fields on any module

### 👷 Testing

- [ ✔️ ] https://gitstable.yetiforce.com **NOT WORKING**
- [ ] I  https://gitdeveloper.yetiforce.com **WORKING**

### 📷 Screenshot of configuration

![click2](https://user-images.githubusercontent.com/74230891/101113574-a1691480-361a-11eb-9399-6404c829e889.jpg)
![click3](https://user-images.githubusercontent.com/74230891/101113580-a4640500-361a-11eb-8d54-6499d2e5e5b0.jpg)
![Click4](https://user-images.githubusercontent.com/74230891/101113583-a62dc880-361a-11eb-8dd3-00dab44c06ad.jpg)
![Click5](https://user-images.githubusercontent.com/74230891/101113586-a7f78c00-361a-11eb-9d17-2dd1a0bebec1.jpg)
![Click6](https://user-images.githubusercontent.com/74230891/101113591-aa59e600-361a-11eb-8ddd-01fe29039982.jpg)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Problem exists on gitstable.yetiforce.com too, I cannot seem to have the logs available at the moment.
![Click7](https://user-images.githubusercontent.com/74230891/101113722-f4db6280-361a-11eb-99b5-edab8dc56cd8.jpg)

### 🌍 Your Environment

| Environment                         | Godaddy Dedicated Server Hosting|
| YetiForce                           | 6.1
| Web server (name and version)       |                |
| PHP                                 |     7.2           |
| Browser (name and version)      Chrome    |                |
| Operating System (name and version) |    Linux            |
| Database (name and version)         |    MYSQL            |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment]
Fixed in 6.1.0_ServicePack_v1.zip

https://github.com/YetiForceCompany/YetiForceCRM/issues/13859

https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/6.1.0
