### ISSUE TITLE
email scanner not working on gitdeveloper or gitstable

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13873]
> I tested the whole mechanism, I don't know what your bugs are,
> I don't have enough information to diagnose it
> you need to give more information

![image](https://user-images.githubusercontent.com/54880467/101090686-0bfb5f80-35dd-11eb-9953-c251d465a250.png)
![image](https://user-images.githubusercontent.com/54880467/101090728-1ae21200-35dd-11eb-81e5-30bd9d3e6c37.png)
![image](https://user-images.githubusercontent.com/54880467/101090860-4fee6480-35dd-11eb-9b22-57cd47e727fd.png)
![image](https://user-images.githubusercontent.com/54880467/101090891-5c72bd00-35dd-11eb-8571-6896690f8ed8.png)

@mariuszkrzaczkowski  same problem as git stable... email doesnt attach to tickets.... so how can u say its working fine...
please look into the matter sir.

I have sent an email subject : final ticket test and it wont show in tickets,, until i go the mailbox click n it and then when i go back an refresh it shows in tickets...

same things is happening with me.. pls look into..

![image](https://user-images.githubusercontent.com/54880467/101091994-f25b1780-35de-11eb-9586-ef1a012603cb.png)
 cron has ran but nothing in tickets.. it will show once u manually read the msg then it will show in tickets..

@mariuszkrzaczkowski 
@paula-w 
@KatarzynaUlichnowska 

pls help

_Originally posted by @rioshaz in https://github.com/YetiForceCompany/YetiForceCRM/issues/13856#issuecomment-738333411_

**Comment by mariuszkrzaczkowski** [comment]
See I did a test on gitdeveloper

![image](https://user-images.githubusercontent.com/10198654/101134791-349a4e00-360b-11eb-9109-61767a7948c2.png)
![image](https://user-images.githubusercontent.com/10198654/101134907-57c4fd80-360b-11eb-9010-fbcc01926ca5.png)
![image](https://user-images.githubusercontent.com/10198654/101134936-627f9280-360b-11eb-903b-f084904621b5.png)
![image](https://user-images.githubusercontent.com/10198654/101134984-75926280-360b-11eb-81c6-4be6b1c2ef71.png)
![image](https://user-images.githubusercontent.com/10198654/101135027-8347e800-360b-11eb-998d-efcae2f4ca1d.png)

something you have to do wrong that doesn't work,
stable version + SP works fine

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski now its working i see,.
but why is mein not wokring.. see screenshot.. mail logs are different

![image](https://user-images.githubusercontent.com/54880467/101142519-b7d39800-363b-11eb-9f8e-b5daacbc68f3.png)

**Comment by mariuszkrzaczkowski** [comment]
your e-mail scanner keeps downloading e-mails until you see the results when it's finished.
You can increase the limit it will be faster eg. 1000

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/0f6ed64f7fe53a1b18aa63b6c04be131199f7a17/config/Performance.php#L68-L69

**Comment by rioshaz** [comment]
cool problem solved.. thank u so much...

.so if i have more then 1000 emails in my inbox. will it stop again ?

**Comment by mariuszkrzaczkowski** [comment]
/** The numbers of emails downloaded during one scanning */
