### ISSUE TITLE
[Question] Gantt not show Milestones and Tasks

### ISSUE THREAD

**Issue by igriberi** [YetiForceCompany/YetiForceCRM#13878]
Hi... first of all sorry for my English (im from Argentina).

I installed YF in my local pc and gantt works amazing but when i install, following exactly same steps, in a server, gantt not show milestone and tasks.

Could you help me? Thx

**Comment by mariuszkrzaczkowski** [comment]
We need more information to identify the problem.

**Comment by rskrzypczak** [comment]
I am closing the issue because there is no error here.
If you have any further questions, please open a discussion.
