### ISSUE TITLE
[bug] Sending e-mail from Email history list fails

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#13889]
# 🐞 bug report

### ⁉️ Describe the bug

When trying to send an e-mail from the "Email history List", as shown in figure below

![send-mail](https://user-images.githubusercontent.com/10230144/101238116-47318780-36de-11eb-8fc0-26c21e85975a.png)

the system fails with the error message `SMTP Error(-1): Connection to server failed` as show in figure below

![mail-send-error](https://user-images.githubusercontent.com/10230144/101238128-64feec80-36de-11eb-8991-0d1881218d9e.png)

The system is correctly configured for sending SMTP messages, i.e., the system confirmed the configuration by sending an e-mail message which was correctly received

![email](https://user-images.githubusercontent.com/10230144/101238187-d179eb80-36de-11eb-8fc9-09808f70e905.png)

### 🔥 How to trigger the error

1. Go to `https://gitdeveloper.yetiforce.com/index.php?module=OSSMailView&view=List`
2. Click on `+Send mail`
3. Enter mail receiver in the `To` field
4. Clock on `Send`
5. See error message `SMTP Error(-1): Connection to server failed`

### 👎 Actual Behavior

An error message is displayed.

### 👍 Expected Behavior

The email message is correctly send.

### 👷 Testing

- [ x] I confirm that I tested it at https://gitstable.yetiforce.com
- [ x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

See configuration on https://gitstable.yetiforce.com or https://gitdeveloper.yetiforce.com

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

![logfile](https://user-images.githubusercontent.com/10230144/101238333-cd9a9900-36df-11eb-917b-b3a8b3a5c3c4.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0 |
| Roundcube                           | 1.4.9 |
| Web server (name and version)       | apache2 2.4.43               |
| PHP                                 |  7.4.13              |
| Database (name and version)         |  MariaDB package|10.4.14              |
| Service Pack version                |  YetiForce CRM 6.1 Service Pack v1              |

### ❓ Additional context

None

**Comment by mariuszkrzaczkowski** [comment]
demo version has email sending disabled
