### ISSUE TITLE
[Question] how to disable Enter visit purpose 

### ISSUE THREAD

**Issue by johniexxx** [YetiForceCompany/YetiForceCRM#13883]
Hello,
how i can disable the "Enter visit purpose" 
![how-to-disable](https://user-images.githubusercontent.com/75033415/101206531-ecfddb80-3677-11eb-920b-804a6fe5f49a.jpg)

it started show after update to 6.0.0

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13864
https://github.com/YetiForceCompany/YetiForceCRM/blob/20f376f9c8ea5866f80e7eb6e77c4fc246bcb10e/config/Security.php#L197-L198

**Comment by simple-AMS** [comment]
Why would something this annoying ever be introduced in the first place. It became a serious nuisance the second time in.

**Comment by z0lo13** [comment]
> Why would something this annoying ever be introduced in the first place. It became a serious nuisance the second time in.

This feature actually amazing thing. Before that you never know why and for what reason admin been logged in in CRM, it was simple login log. And now it's getting more organized.

**Comment by simple-AMS** [comment]
> > Why would something this annoying ever be introduced in the first place. It became a serious nuisance the second time in.
> 
> This feature actually amazing thing. Before that you never know why and for what reason admin been logged in in CRM, it was simple login log. And now it's getting more organized.

So a regular user would of never gotten that annoying step? In other words Admin users were the only ones who saw it? Still though, I guess it depends on each server admin. It was quite the annoyance for me in my everyday use so it's disabled.
