### ISSUE TITLE
[bug] Poor layout of buttons on Calendar page

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#13881]
# 🐞 bug report

### ⁉️ Describe the bug

As shown in the figure below, the layout of the "Calendar" button looks poor (background does not span whole button).

![layout](https://user-images.githubusercontent.com/10230144/101178075-d3916b00-3648-11eb-92cd-eaf6bf676d1c.png)

### 🔥 How to trigger the error

Visualize calendar

1. Go to "Virtual Desk" -> "Calendar"
2. See poor layout

### 👍 Expected Behavior

Background color spawns the whole button.

### 👷 Testing

- [x ] I confirm that I tested it at https://gitstable.yetiforce.com
- [x ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

Not relevant.

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Not relevant.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0 / 6.1.6 |
| Browser (name and version)          | firefox 83.0 / edge 87.0 / opera                |

### ❓ Additional context

None

### ❗️ Inform the community if you solve the problem

None

**Comment by simple-AMS** [comment]
@diderich Yes sir, mine looks like that as well. The word Calendar is misaligned. With that said, I'm still running some production versions of version 5.3.0 with Service Pack 4 installed and it's an issue on those systems as well. It's still an issue on the new 6.1.0 version even with Service Pack 3 installed.

**Comment by mariuszkrzaczkowski** [comment]
Check the development version

**Comment by diderich** [comment]
It is solved on gitdeveloper, still a problem on gitstable and in YetiForce CRM 6.1 Service Pack v5.

**Comment by simple-AMS** [comment]
> It is solved on gitdeveloper, still a problem on gitstable and in YetiForce CRM 6.1 Service Pack v5.

@mariuszkrzaczkowski That's wonderful that it's a non issue on the Developer version. Any way we can get a fix for it for the actual user versions?
