### ISSUE TITLE
Delete Record from System not working for any module

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#13890]
I have deleted record and is transferred to recycle bin by application, now when I try to delete from system by clicking button, nothing happens.

![image](https://user-images.githubusercontent.com/12723595/101238790-88d72800-3708-11eb-8bc4-0ac98994f940.png)

Kindly assist.

Thanks in advance
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/101241061-4b1bd480-36f3-11eb-80b6-b104d0cfa0c7.jpg)

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski Thanks for reply, below is steps reproduced.

 
![image](https://user-images.githubusercontent.com/12723595/101629414-5189b380-3a47-11eb-9449-f874c52d96be.png)


I am on Account Module and selected record, which is opening as below

 
![image](https://user-images.githubusercontent.com/12723595/101629425-551d3a80-3a47-11eb-8625-1d59ea7e3b2a.png)


Then I clicked on Delete Record from System Button, it showed below querybox
 
![image](https://user-images.githubusercontent.com/12723595/101629437-59e1ee80-3a47-11eb-9a51-b0ffb33a1fc6.png)


I clicked on OK
Nothing happed, record is not deleted. 
 
![image](https://user-images.githubusercontent.com/12723595/101629445-5d757580-3a47-11eb-8879-df9501f3ebb9.png)


This is happening for each module

Please guide me.

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/101633450-8ab22b80-3a27-11eb-8700-916ba19fc3c1.jpg)

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski Hi, Thanks for replying. I solved issue with below set in MySQL,

 set global table_definition_cache = 4000;

Regards

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/155baa6fb2c5d1ff9df69ebdcf960e271fb6b1cd/tests/setup/db/mysql.cnf#L43-L44
