### ISSUE TITLE
Improvement: add some sounds to the system :) 

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#139]
for example if reminder is active or there is new incoming mail system could generate sound alert. 
I saw similar functionality in the other CRM like group-office and it was great functionality.

**Comment by waw555** [comment]
good idea


And Online Radio :)))
And Movie House

**Comment by waran70** [comment]
O.O
In busy company it may ding all the time... risk of shooting workstation

**Comment by bpibiza** [comment]
no way ! it could be depends of user's settings :)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
there are sound alerts in the system, e.g. in chat. In the future all alerts will be sent to mobile phones so it means that the sound of alerts will be configured in mobile phones. It seems to us that it is sufficient for now.
