### ISSUE TITLE
[bug] unusal high size system.log file

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13905]
sir the cache/logs/system.log is getting so big that it stops the server and i have to delete it...
what the solution ?

![image](https://user-images.githubusercontent.com/54880467/101641951-691d6800-3a58-11eb-8150-93ab6c395ea3.png)

**Comment by davide-alghi** [comment]
Hi @rioshaz,
maybe you have log to file for debugging enabled ($LOG_TO_FILE)

If you don't need to debug, set following variable to false
https://github.com/YetiForceCompany/YetiForceCRM/blob/8306e0569136c66168152907ee7d8e0f10c9f54c/config/Debug.php#L21
and empty ```cache/log/system.log``` file

**Comment by rioshaz** [comment]
okay thanks man...
also the crm goes blank 
![image](https://user-images.githubusercontent.com/54880467/101646511-a3d5cf00-3a5d-11eb-8934-b7febd77dfb5.png)

both front n setting pages
![image](https://user-images.githubusercontent.com/54880467/101647127-6160c200-3a5e-11eb-8f56-556ae3661598.png)

and after some time it revives... strange,, sometimes in 5 minutes some times in 15 minutes

**Comment by davide-alghi** [comment]
this after setting $LOG_TO_FILE to false?

**Comment by rioshaz** [comment]
no ... it was happening before... after setting it to false i dont know if it will come again.. if it comes i will update you..

also @davide-alghi just want to ask you if you know how do the calender events work..

like i create a calendar event (call, meeting or to-do) but when i mark it as complete or postpone then ...i dont see any place where i can put my notes on what happened on the call or whats the reason to postpone..

normally if i mark it as complete it should ask me what to do next... because in crm every action leads to another action starting..

please help if u can...

**Comment by davide-alghi** [comment]
> no ... it was happening before... after setting it to false i dont know if it will come again.. if it comes i will update you..

ok



> like i create a calendar event (call, meeting or to-do) but when i mark it as complete or postpone then ...i dont see any place where i can put my notes on what happened on the call or whats the reason to postpone..
> 
> normally if i mark it as complete it should ask me what to do next... because in crm every action leads to another action starting..

a note box is not available by default, but you can add one
1) go to backend (Standard modules / Edit fields => Calendar)
https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=Calendar
2) create a new block "Custom notes"
![Schermata da 2020-12-09 16-52-58](https://user-images.githubusercontent.com/48508691/101655210-a3c7d600-3a41-11eb-865f-ce06882d5d8d.png)
3) create a new field (text area) into the new block
![Schermata da 2020-12-09 16-54-12](https://user-images.githubusercontent.com/48508691/101653000-2ef39c80-3a3f-11eb-85e2-76482dc048c6.png)
4) set the new field as mandatory and set a default value (any char, like - )
![Schermata da 2020-12-09 16-56-27](https://user-images.githubusercontent.com/48508691/101655794-4da76280-3a42-11eb-95b4-63ad221c1b4c.png)
5) save
![Schermata da 2020-12-09 17-09-55](https://user-images.githubusercontent.com/48508691/101655249-af1b0180-3a41-11eb-9072-2eb4a3db77e4.png)
6) go to Calendar
![Schermata da 2020-12-09 17-00-24](https://user-images.githubusercontent.com/48508691/101653949-3c5d5680-3a40-11eb-98e6-d5f884bf8ef1.png)

**Comment by rioshaz** [comment]
@davide-alghi  of course we can make a custom text box that is no problem and we already have a description box..  but my question is when you click "postpone" or "complete" it should give birth to a new action,,, 

if i click "postpone" it goes in the event edit mode, where a new field should come and ask reason for postpone.

making custom notes mandatory is okay but when u create a fresh event it will also ask for custom notes box to be filled and when during "postpone" edit mode the custom notes will already be filled so it will not show any error and  easily skip of mind to write notes as its mandatory but it already has text...

marking it "complete"  makes the whole thing disappear and if u dont remember you lose track of the lead or event....it should ask what u want to do next.. create a to-do, create opportunity, convert lead  etc....

![image](https://user-images.githubusercontent.com/54880467/101672657-29687780-3a7c-11eb-8ac9-45393dd4ac97.png)

![image](https://user-images.githubusercontent.com/54880467/101674066-076ff480-3a7e-11eb-912e-11b98da0bcbe.png)


also there is no option to add comments in a call, meeting or to-do event

like u see this in suitecrm...

![image](https://user-images.githubusercontent.com/54880467/101675231-8e719c80-3a7f-11eb-92ab-6bb66946c512.png)

below image when i clck rescheule

![image](https://user-images.githubusercontent.com/54880467/101675868-5fa7f600-3a80-11eb-967b-5d629d9b8dab.png)
when i click close and create new
![image](https://user-images.githubusercontent.com/54880467/101675644-1a83c400-3a80-11eb-8188-f87e557d65c0.png)

**Comment by rioshaz** [comment]
omg again same crm has gone blank...
![image](https://user-images.githubusercontent.com/54880467/101676560-55d2c280-3a81-11eb-87cf-3a5f1558b171.png)

**Comment by davide-alghi** [comment]
Hi @rioshaz,
Suite is basically an Operational crm; for this the activities management is very detailed.
In YF that activity life-cycle is not expected and therefore not available.
The implementation choice of the type of crm (Operational, Analytical, Collaborative and so on) to be created defines specific functions/features and modules.

________


About blank page: the problem could be YF, webserver configuration or database
I suspect there is some problem with your database
anyway ... 

1) try to re-enable debugging and check log when the problem returns
2) check webserver log when the problem returns

if no errors were found, your problem is the database server

**Comment by rioshaz** [comment]
@davide-alghi thanks for your inputs however i think this is a basic necessity of any crm to have a complete flow....
if you cant track action, post events then what's the use of crm..... i think YF should think about it seriously ..

CRM is all about organizing information and i wonder with so much good functionality YF lacks basic features sometimes like you don't have lead validation either...  same mobile no, can be used in many leads ,, this is not right...

with 6.0 they have got this duplicacy issue fixed for accounts but still forms integration is not there... 

saying crm as operational or analytical or whatever doesnt excuse yf for such a basic funtioanlity.

anyways i will see what i can do...

its only my user  that is blank .. gives no data but other uses can access all info they have.. strange..
i have tried many different browsers too.
.

**Comment by rskrzypczak** [comment]
You really like to complain ;)
![100861957-cf235180-3492-11eb-90ee-277602cc27ef](https://user-images.githubusercontent.com/10221999/101733113-9b61b080-3abe-11eb-994f-0a9a9a29ca67.jpg)

**Comment by rioshaz** [comment]
can u tell em which file do i need to send u that has logs...

**Comment by mariuszkrzaczkowski** [comment]
Please take a look at our rules on how to report bugs, once you add all the missing information we will start investigating your problem. Right now we don't have enough details to do so.
https://yetiforce.com/en/component/zoo/item/how-to-report-bugs

**Comment by rioshaz** [comment]
i dont know what u guys want,, you dont even tell me which file do u want...

2020-12-10 17:20:13.0149 [info][yii\db\Command::query] - SELECT EXISTS(SELECT * FROM `vtiger_users` WHERE (`id`=1) AND ((`status`='Active') AND (`deleted`=0)))
2020-12-10 17:20:13.0213 [info][yii\db\Command::query] - SELECT * FROM `vtiger_tab`
2020-12-10 17:20:13.0292 [info][yii\db\Command::query] - SELECT `type` FROM `u_yf_chat_rooms` WHERE `active`=1 ORDER BY `sequence`
2020-12-10 17:20:13.0312 [info][yii\db\Command::query] - SELECT `C`.`roomid`, `C`.`userid`, `C`.`crmid` AS `recordid`, `CL`.`label` AS `name`, `C`.`last_message`, `CNT`.`cnt_new_message` FROM `u_yf_chat_rooms_crm` `C` LEFT JOIN `u_yf_crmentity_label` `CL` ON CL.crmid = C.crmid LEFT JOIN (SELECT `CR`.`crmid`, `CR`.`userid`, COUNT(*) AS `cnt_new_message` FROM `u_yf_chat_rooms_crm` `CR` INNER JOIN `u_yf_chat_messages_crm` `CM` ON CM.crmid = CR.crmid WHERE (`CM`.`id` > CR.last_message) OR (`CR`.`last_message` IS NULL) GROUP BY `CR`.`crmid`, `CR`.`userid`) `CNT` ON CNT.crmid = C.crmid AND CNT.userid = C.userid WHERE `C`.`userid`=1
2020-12-10 17:20:13.0335 [info][yii\db\Command::query] - SELECT `name`, `GL`.`global_room_id` AS `recordid`, `CNT`.`last_message`, `CNT`.`cnt_new_message`, `CNT`.`userid` FROM `u_yf_chat_global` `GL` LEFT JOIN (SELECT `CR`.*, (SELECT COUNT(*) FROM `u_yf_chat_messages_global` `CM` WHERE (`CM`.`globalid`=CR.global_room_id) AND (`CM`.`id` > CR.last_message)) AS `cnt_new_message` FROM `u_yf_chat_rooms_global` `CR`) `CNT` ON CNT.global_room_id = GL.global_room_id WHERE `CNT`.`userid`=1
2020-12-10 17:20:13.0356 [info][yii\db\Command::query] - SELECT `GR`.`roomid`, `GR`.`last_message`, `GR`.`userid`, `GR`.`groupid` AS `recordid`, `VGR`.`groupname` AS `name`, `CNT`.`cnt_new_message` FROM `u_yf_chat_rooms_group` `GR` LEFT JOIN (SELECT `CR`.`groupid`, `CR`.`userid`, COUNT(*) AS `cnt_new_message` FROM `u_yf_chat_rooms_group` `CR` INNER JOIN `u_yf_chat_messages_group` `CM` ON CM.groupid = CR.groupid WHERE `CM`.`id` > CR.last_message GROUP BY `CR`.`groupid`, `CR`.`userid`) `CNT` ON CNT.groupid = GR.groupid AND CNT.userid = GR.userid RIGHT JOIN `vtiger_groups` `VGR` ON VGR.groupid = GR.groupid WHERE `GR`.`userid`=1
2020-12-10 17:20:13.0361 [info][yii\db\Command::query] - SELECT `name`, `GL`.`private_room_id` AS `recordid`, `CNT`.`last_message`, `CNT`.`cnt_new_message`, `CNT`.`userid`, `creatorid`, `created` FROM `u_yf_chat_private` `GL` RIGHT JOIN (SELECT `CR`.*, (SELECT COUNT(*) FROM `u_yf_chat_messages_private` `CM` WHERE (`CM`.`privateid`=CR.private_room_id) AND (`CM`.`id` > CR.last_message)) AS `cnt_new_message` FROM `u_yf_chat_rooms_private` `CR`) `CNT` ON CNT.private_room_id = GL.private_room_id AND CNT.userid = 1 WHERE `archived`=0
2020-12-10 17:20:13.0368 [info][yii\db\Command::query] - SELECT `ROOM_PINNED`.`last_message`, `ROOM_SRC`.`userid`, `ROOM_SRC`.`reluserid`, `ROOM_SRC`.`roomid` AS `recordid`, (SELECT COUNT(*) FROM `u_yf_chat_messages_user` `MESSAGES` WHERE (`MESSAGES`.`roomid`=ROOM_PINNED.roomid) AND (`MESSAGES`.`id` > ROOM_PINNED.last_message)) AS `cnt_new_message` FROM `u_yf_chat_rooms_user` `ROOM_PINNED` LEFT JOIN `u_yf_chat_user` `ROOM_SRC` ON ROOM_PINNED.roomid = ROOM_SRC.roomid WHERE (`ROOM_PINNED`.`userid`=1) AND ((`ROOM_SRC`.`reluserid`=1) OR (`ROOM_SRC`.`userid`=1))
2020-12-10 17:20:13.0372 [info][yii\db\Command::query] - SELECT EXISTS(SELECT * FROM `vtiger_users` WHERE (`id`=6) AND ((`status`='Active') AND (`deleted`=0)))
2020-12-10 17:20:13.0454 [info][yii\db\Command::query] - SELECT * FROM `vtiger_role` WHERE `roleid`='H10' LIMIT 1
2020-12-10 17:20:12.9981 [info][application] - 
$_GET = []
$_POST = [
    '_csrf' => 'sid:2f385dce992f6a6642c9a51ce1176e2c1303a9ff,1607601000'
    'module' => 'Chat'
    'action' => 'ChatAjax'
    'mode' => 'getRoomsMessages'
]
$_FILES = []
$_COOKIE = [
    'YTSID' => 'bac918ba686627d95873dc0717ab0e66'
    'roundcube_sessid' => '4c29b5f72be250aee0aaa097fc3dd48d'
    'roundcube_sessauth' => '0uS4lC4P99CbnAuWGBv5SNWjyTIriRND-1607580000'
]
$_SESSION = [
    'CSP_TOKEN' => '693dab09e16d1de8a0bc7b2c66125e1923d1e31540f185a765f4e150e8b2158f'
    'last_activity' => 1607601006.3656
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => '32af08f5fbff9e491536153066658907ddcc305e'
    'user_name' => 'rohit'
    'full_user_name' => 'Sharma Rohit'
    'fingerprint' => 'be7125c7-c1a9-44b1-b1e8-f46e27b3b07e'
    'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
        'Leads' => [
            'LastDashBoardId' => 1
        ]
    ]
    'lvs' => [
        'Leads' => [
            'sortby' => [
                'createdtime' => 'DESC'
            ]
            'viewname' => 1
            1 => [
                'start' => 1
            ]
            'entityState' => 'Active'
        ]
        'Accounts' => [
            'sortby' => [
                'modifiedtime' => 'DESC'
            ]
            'viewname' => 4
        ]
        'Contacts' => [
            'sortby' => [
                'createdtime' => 'DESC'
            ]
            'viewname' => 7
        ]
        'SSalesProcesses' => [
            'sortby' => [
                'modifiedtime' => 'DESC'
            ]
            'viewname' => 80
        ]
    ]
]
HEADERS = [
    'Cookie' => 'YTSID=bac918ba686627d95873dc0717ab0e66; roundcube_sessid=4c29b5f72be250aee0aaa097fc3dd48d; roundcube_sessauth=0uS4lC4P99CbnAuWGBv5SNWjyTIriRND-1607580000'
    'Accept-Language' => 'en,fr;q=0.9'
    'Accept-Encoding' => 'gzip, deflate, br'
    'Sec-Fetch-Dest' => 'empty'
    'Sec-Fetch-Mode' => 'cors'
    'Sec-Fetch-Site' => 'same-origin'
    'Origin' => 'https://team.searchosis.com'
    'Content-Type' => 'application/x-www-form-urlencoded; charset=UTF-8'
    'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
    'X-Requested-With' => 'XMLHttpRequest'
    'Accept' => 'application/json, text/javascript, */*; q=0.01'
    'Content-Length' => '111'
    'Connection' => 'keep-alive'
    'Host' => 'team.searchosis.com'
    'Authorization' => ''
]
$security = [
    'display_errors' => 'On'
    '.htaccess' => 'Off'
    'session.use_strict_mode' => 'On'
]
$headers = [
    'Header: server' => 'Apache'
    'Header: referrer-policy' => 'no-referrer'
    'Header: expect-ct' => 'enforce; max-age=3600'
    'Header: x-frame-options' => 'sameorigin'
    'Header: x-xss-protection' => '1; mode=block'
    'Header: x-content-type-options' => 'nosniff'
    'Header: x-robots-tag' => 'none'
    'Header: x-permitted-cross-domain-policies' => 'none'
    'Header: strict-transport-security' => 'max-age=31536000; includeSubDomains; preload'
]
$database = [
    'table_definition_cache' => '400'
]
$environment = [
    'currentUser' => ' (uid:1001)'
    'openssl.cafile' => false
    'openssl.capath' => false

**Comment by rioshaz** [comment]
![image](https://user-images.githubusercontent.com/54880467/101769027-5d8b7900-3b0c-11eb-8fe0-9f636b497098.png)
now its not working at all... since 1 hr its not showing any records sir

**Comment by rioshaz** [comment]
> i dont know what u guys want,, you dont even tell me which file do u want...
> 
> 2020-12-10 17:20:13.0149 [info][yii\db\Command::query] - SELECT EXISTS(SELECT * FROM `vtiger_users` WHERE (`id`=1) AND ((`status`='Active') AND (`deleted`=0)))
> 2020-12-10 17:20:13.0213 [info][yii\db\Command::query] - SELECT * FROM `vtiger_tab`
> 2020-12-10 17:20:13.0292 [info][yii\db\Command::query] - SELECT `type` FROM `u_yf_chat_rooms` WHERE `active`=1 ORDER BY `sequence`
> 2020-12-10 17:20:13.0312 [info][yii\db\Command::query] - SELECT `C`.`roomid`, `C`.`userid`, `C`.`crmid` AS `recordid`, `CL`.`label` AS `name`, `C`.`last_message`, `CNT`.`cnt_new_message` FROM `u_yf_chat_rooms_crm` `C` LEFT JOIN `u_yf_crmentity_label` `CL` ON CL.crmid = C.crmid LEFT JOIN (SELECT `CR`.`crmid`, `CR`.`userid`, COUNT(_) AS `cnt_new_message` FROM `u_yf_chat_rooms_crm` `CR` INNER JOIN `u_yf_chat_messages_crm` `CM` ON CM.crmid = CR.crmid WHERE (`CM`.`id` > CR.last_message) OR (`CR`.`last_message` IS NULL) GROUP BY `CR`.`crmid`, `CR`.`userid`) `CNT` ON CNT.crmid = C.crmid AND CNT.userid = C.userid WHERE `C`.`userid`=1 2020-12-10 17:20:13.0335 [info][yii\db\Command::query] - SELECT `name`, `GL`.`global_room_id` AS `recordid`, `CNT`.`last_message`, `CNT`.`cnt_new_message`, `CNT`.`userid` FROM `u_yf_chat_global` `GL` LEFT JOIN (SELECT `CR`._, (SELECT COUNT(_) FROM `u_yf_chat_messages_global` `CM` WHERE (`CM`.`globalid`=CR.global_room_id) AND (`CM`.`id` > CR.last_message)) AS `cnt_new_message` FROM `u_yf_chat_rooms_global` `CR`) `CNT` ON CNT.global_room_id = GL.global_room_id WHERE `CNT`.`userid`=1 2020-12-10 17:20:13.0356 [info][yii\db\Command::query] - SELECT `GR`.`roomid`, `GR`.`last_message`, `GR`.`userid`, `GR`.`groupid` AS `recordid`, `VGR`.`groupname` AS `name`, `CNT`.`cnt_new_message` FROM `u_yf_chat_rooms_group` `GR` LEFT JOIN (SELECT `CR`.`groupid`, `CR`.`userid`, COUNT(_) AS `cnt_new_message` FROM `u_yf_chat_rooms_group` `CR` INNER JOIN `u_yf_chat_messages_group` `CM` ON CM.groupid = CR.groupid WHERE `CM`.`id` > CR.last_message GROUP BY `CR`.`groupid`, `CR`.`userid`) `CNT` ON CNT.groupid = GR.groupid AND CNT.userid = GR.userid RIGHT JOIN `vtiger_groups` `VGR` ON VGR.groupid = GR.groupid WHERE `GR`.`userid`=1
> 2020-12-10 17:20:13.0361 [info][yii\db\Command::query] - SELECT `name`, `GL`.`private_room_id` AS `recordid`, `CNT`.`last_message`, `CNT`.`cnt_new_message`, `CNT`.`userid`, `creatorid`, `created` FROM `u_yf_chat_private` `GL` RIGHT JOIN (SELECT `CR`._, (SELECT COUNT(_) FROM `u_yf_chat_messages_private` `CM` WHERE (`CM`.`privateid`=CR.private_room_id) AND (`CM`.`id` > CR.last_message)) AS `cnt_new_message` FROM `u_yf_chat_rooms_private` `CR`) `CNT` ON CNT.private_room_id = GL.private_room_id AND CNT.userid = 1 WHERE `archived`=0
> 2020-12-10 17:20:13.0368 [info][yii\db\Command::query] - SELECT `ROOM_PINNED`.`last_message`, `ROOM_SRC`.`userid`, `ROOM_SRC`.`reluserid`, `ROOM_SRC`.`roomid` AS `recordid`, (SELECT COUNT(*) FROM `u_yf_chat_messages_user` `MESSAGES` WHERE (`MESSAGES`.`roomid`=ROOM_PINNED.roomid) AND (`MESSAGES`.`id` > ROOM_PINNED.last_message)) AS `cnt_new_message` FROM `u_yf_chat_rooms_user` `ROOM_PINNED` LEFT JOIN `u_yf_chat_user` `ROOM_SRC` ON ROOM_PINNED.roomid = ROOM_SRC.roomid WHERE (`ROOM_PINNED`.`userid`=1) AND ((`ROOM_SRC`.`reluserid`=1) OR (`ROOM_SRC`.`userid`=1))
> 2020-12-10 17:20:13.0372 [info][yii\db\Command::query] - SELECT EXISTS(SELECT * FROM `vtiger_users` WHERE (`id`=6) AND ((`status`='Active') AND (`deleted`=0)))
> 2020-12-10 17:20:13.0454 [info][yii\db\Command::query] - SELECT * FROM `vtiger_role` WHERE `roleid`='H10' LIMIT 1
> 2020-12-10 17:20:12.9981 [info][application] -
> $_GET = []
> $_POST = [
> '_csrf' => 'sid:2f385dce992f6a6642c9a51ce1176e2c1303a9ff,1607601000'
> 'module' => 'Chat'
> 'action' => 'ChatAjax'
> 'mode' => 'getRoomsMessages'
> ]
> $_FILES = []
> $_COOKIE = [
> 'YTSID' => 'bac918ba686627d95873dc0717ab0e66'
> 'roundcube_sessid' => '4c29b5f72be250aee0aaa097fc3dd48d'
> 'roundcube_sessauth' => '0uS4lC4P99CbnAuWGBv5SNWjyTIriRND-1607580000'
> ]
> $_SESSION = [
> 'CSP_TOKEN' => '693dab09e16d1de8a0bc7b2c66125e1923d1e31540f185a765f4e150e8b2158f'
> 'last_activity' => 1607601006.3656
> 'UserAuthMethod' => 'PASSWORD'
> 'authenticated_user_id' => 1
> 'app_unique_key' => '32af08f5fbff9e491536153066658907ddcc305e'
> 'user_name' => 'rohit'
> 'full_user_name' => 'Sharma Rohit'
> 'fingerprint' => 'be7125c7-c1a9-44b1-b1e8-f46e27b3b07e'
> 'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
> 'DashBoard' => [
> 'Home' => [
> 'LastDashBoardId' => 1
> ]
> 'Leads' => [
> 'LastDashBoardId' => 1
> ]
> ]
> 'lvs' => [
> 'Leads' => [
> 'sortby' => [
> 'createdtime' => 'DESC'
> ]
> 'viewname' => 1
> 1 => [
> 'start' => 1
> ]
> 'entityState' => 'Active'
> ]
> 'Accounts' => [
> 'sortby' => [
> 'modifiedtime' => 'DESC'
> ]
> 'viewname' => 4
> ]
> 'Contacts' => [
> 'sortby' => [
> 'createdtime' => 'DESC'
> ]
> 'viewname' => 7
> ]
> 'SSalesProcesses' => [
> 'sortby' => [
> 'modifiedtime' => 'DESC'
> ]
> 'viewname' => 80
> ]
> ]
> ]
> HEADERS = [
> 'Cookie' => 'YTSID=bac918ba686627d95873dc0717ab0e66; roundcube_sessid=4c29b5f72be250aee0aaa097fc3dd48d; roundcube_sessauth=0uS4lC4P99CbnAuWGBv5SNWjyTIriRND-1607580000'
> 'Accept-Language' => 'en,fr;q=0.9'
> 'Accept-Encoding' => 'gzip, deflate, br'
> 'Sec-Fetch-Dest' => 'empty'
> 'Sec-Fetch-Mode' => 'cors'
> 'Sec-Fetch-Site' => 'same-origin'
> 'Origin' => 'https://team.searchosis.com'
> 'Content-Type' => 'application/x-www-form-urlencoded; charset=UTF-8'
> 'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
> 'X-Requested-With' => 'XMLHttpRequest'
> 'Accept' => 'application/json, text/javascript, _/_; q=0.01'
> 'Content-Length' => '111'
> 'Connection' => 'keep-alive'
> 'Host' => 'team.searchosis.com'
> 'Authorization' => ''
> ]
> $security = [
> 'display_errors' => 'On'
> '.htaccess' => 'Off'
> 'session.use_strict_mode' => 'On'
> ]
> $headers = [
> 'Header: server' => 'Apache'
> 'Header: referrer-policy' => 'no-referrer'
> 'Header: expect-ct' => 'enforce; max-age=3600'
> 'Header: x-frame-options' => 'sameorigin'
> 'Header: x-xss-protection' => '1; mode=block'
> 'Header: x-content-type-options' => 'nosniff'
> 'Header: x-robots-tag' => 'none'
> 'Header: x-permitted-cross-domain-policies' => 'none'
> 'Header: strict-transport-security' => 'max-age=31536000; includeSubDomains; preload'
> ]
> $database = [
> 'table_definition_cache' => '400'
> ]
> $environment = [
> 'currentUser' => ' (uid:1001)'
> 'openssl.cafile' => false
> 'openssl.capath' => false

@mariuszkrzaczkowski @davide-alghi  does it help u find the problem ? 
not is working and after sometiem it will stop working then works again automatically..

pls help

**Comment by mariuszkrzaczkowski** [comment]
> i dont know what u guys want,, you dont even tell me which file do u want...

If you read the description of how to report issues in its entirety you would know.
The required information is still missing

**Comment by rioshaz** [comment]
@i read it all n it says send logs.. but which logs to send i dont know... it frustrating at this point now buddy...

**Comment by rioshaz** [comment]
if u can tell me which logs u want i can provide
