### ISSUE TITLE
[Question] Disable Enter visit purpose

### ISSUE THREAD

**Issue by igriberi** [YetiForceCompany/YetiForceCRM#13902]
Hi... how could i disable "Enter visit purpose" modal?

It appear after every time i login.

Thx

**Comment by vovpff** [comment]
Check  configs

**Comment by igriberi** [comment]
im asking here because i cant find in config where is the option that i have to disable...

**Comment by davide-alghi** [comment]
Hi @igriberi,
Pls take a look here 
https://github.com/YetiForceCompany/YetiForceCRM/issues/13883#issuecomment-738992853

**Comment by igriberi** [comment]
thx
