### ISSUE TITLE
[bug] I think it's a bug.... Failure when updating from 5.3 to 6.0 from the UI

### ISSUE THREAD

**Issue by gkankstech** [YetiForceCompany/YetiForceCRM#13901]
# 🐞 bug report

### ⁉️ Failure when updating from 5.3 to 6.0 from the UI

When trying to update through the web ui (Software configuration / Logs / Updates / System settings) from 5.3 with SP4 and SF 1 to 6v4 we get the following error:

"Argument 1 passed to App\YetiForce\Updater::download() must be of the type array, null given, called in /home/username/public_html/crm/modules/Settings/Updates/views/Index.php on line 18"

### 🔥 How to trigger the error

1. Login in as an admin
2. Click System Settings
3. Click Logs and Updates
4. Click the "Download package" button

![image](https://user-images.githubusercontent.com/449715/101549473-be377c00-397b-11eb-8530-9a87b800a7d3.png)

![image](https://user-images.githubusercontent.com/449715/101549500-cabbd480-397b-11eb-90d5-0480da31a33f.png)

### 👎 Actual Behavior

An error is presented

### 👍 Expected Behavior

The Install option would become available after downloading

### 👷 Testing

Don't think i can test on the demo sites

### 📷 Screenshot of configuration

![image](https://user-images.githubusercontent.com/449715/101549520-d7d8c380-397b-11eb-9227-11257d991f2b.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Checked Apache logs and all of the logs in the ./cache/logs folder and there's nothing related.

### 🌍 Your Environment

On a CPanel/WHM server with the following attributes:

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3, SP4, SF1
| Web server (name and version)       |     Apache 2.4           |
| PHP                                 |       7.2         |
| Browser (name and version)          |        Firefox        |
| Operating System (name and version) |         CentOS 7.9       |
| Database (name and version)         |        MySQL 5.7.32        |
| Service Pack version                |                |

### ❓ Additional context

I could probably manually download and install but wanted to get feedback before trying that.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13829
https://github.com/YetiForceCompany/YetiForceCRM/issues/13823
