### ISSUE TITLE
[bug]  notification bug again

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13909]
hi sir the issue fixed in this link is now again not working in 6 yf version
https://github.com/YetiForceCompany/YetiForceCRM/issues/13318#issue-658534493

projects task show the below image.. contacts, project milestone, leads, projects, account notification are working fine.. only project task showing this...

![image](https://user-images.githubusercontent.com/54880467/101874905-bb24d180-3baf-11eb-995d-53b64341ad08.png)

pls fix

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/101875745-7c7d2000-3b8b-11eb-8493-e597b7112cd9.jpg)

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski  if u check the link  https://github.com/YetiForceCompany/YetiForceCRM/issues/13318#issue-658534493 u can get the required information... just closing issues like this won't make the issue go away buddy ,

the problem is with  : /modules/Notification/models/Record.php

**Comment by rioshaz** [comment]
ok i made a test on gitstable so i hope now u can help me. now

creating a "project task" from demo yetiforce and assigning to to "sales yetiforce" users gives notifcation in worng way..

YetiForce Demo $(translate : ModTracker|LBL_CREATED)$ $(record : RecordLabel)$
it shoudl display task name and details...

![image](https://user-images.githubusercontent.com/54880467/101878774-27a2cf00-3bb6-11eb-8483-93fe966bda91.png)

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski can u please fix it...

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski now can u check it sir
