### ISSUE TITLE
[Question] posisble to export all modules data

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13916]
Hi Sir,
I would like to export all data leads, calender, accounts, opportunities, sales invoice, accounting, support etc all in 1 click go and then import them into in a new yf installation is that possible? i know i can manually go to each module and export all records...

any help will be greatly appreciated..

**Comment by apcloic** [comment]
@rioshaz Export database and import into the new YF instance.

**Comment by rioshaz** [comment]
@apcloic shouldnt the yf version be same for that... ?

**Comment by apcloic** [comment]
@rioshaz Yes, you didn't tell us that YF versions were differents.

**Comment by rioshaz** [comment]
@apcloic 
i had 5.3 installed and i took files and db backup and updated it to 6.0 but 6.0 does work fine so i have placed 5.3 and db back on server. but path is same...
but now i am getting error:

Forbidden
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
![image](https://user-images.githubusercontent.com/54880467/102004349-ee916880-3d35-11eb-9667-4d7521ccee07.png)

shall i do.. any help buddy

**Comment by rskrzypczak** [comment]
> I would like to export all data leads, calender, accounts, opportunities, sales invoice, accounting, support etc all in 1 click go and then import them into in a new yf installation is that possible?

No.
