### ISSUE TITLE
Calculactions. Dashboard. Js error

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1391]
I'm in dashboard in calculactions module I get 
![error](https://cloud.githubusercontent.com/assets/3193498/8540511/c7a8a508-2486-11e5-9a14-e0e7d7251e6e.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/17207d2fb4407ddf78b0fed943e2308e88d20b8a
