### ISSUE TITLE
[bug] PDF engine adds new lines at the bottom of cell

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#13929]
# 🐞 bug report

### ⁉️ Describe the bug

PDF engine: for each paragraph (```<p>```) in text into a table, PDF engine adds a new line at the bottom of cell

_the PDF template is attached_

### 🔥 How to trigger the error

1. Create a new PDF template
2. In content set a top marker like ==================
3. insert a table
4. in one cell insert a text with some paragraph (```<p>```) - shift+return
5. insert a bottom marker, outside the table like ==================
6. render the PDF

### 👎 Actual Behavior

added lines/space at the end of the text 

### 👍 Expected Behavior

no ending spaces

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

________________________________

[38_pdftemplate.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/5702347/38_pdftemplate.zip)

![Screencast_16-12-2020_12:24:26](https://user-images.githubusercontent.com/48508691/102343172-7e375100-3f9a-11eb-99ca-5f44833df7c8.gif)

**Comment by konadrian** [comment]
Try to set margins and paddings to 0  or you can use <span> for this
![image](https://user-images.githubusercontent.com/3193498/183604588-bcce82be-1c47-45a2-b91b-dc175a553d53.png)

![image](https://user-images.githubusercontent.com/3193498/183604256-2746da62-85ab-4b3e-8947-2c2c71f5c02c.png)
