### ISSUE TITLE
[bug] Settings :: System tools :: PDF - click on row goes to download

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#13926]
# 🐞 bug report

### ⁉️ Describe the bug

in Settings :: System tools :: PDF - click on row runs download instead of edit

**hint** https://github.com/YetiForceCompany/YetiForceCRM/blob/d3ec878c66bc62533533968a053ce92aeed8683d/public_html/layouts/basic/modules/Settings/PDF/resources/List.js#L38

```var editUrl = jQuery(e.currentTarget).find('.actions a:first').attr('href');```

### 🔥 How to trigger the error

1. Go to Settings :: System tools :: PDF
2. Click on any rows

### 👎 Actual Behavior

open download

### 👍 Expected Behavior

opening edit

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by davide-alghi** [comment]
maybe it's better remove edit-click on row: it conflicts with action buttons into last cell

**Comment by rskrzypczak** [comment]
It's one of the options, but it's better to make it meet the standard, that is - base mostly on the object LINK 
It requires some small fixes in  .tpl, .js, and .php files

**Comment by davide-alghi** [comment]
sorry, but what is the standard on BE row click?

- sometimes it goes to details (Users, Company details)
- sometimes it goes to details only on no-first-column click (Profiles, Groups)
- sometimes it does nothing (Auto assign records, Admin access, Dependent Fields, Fields – Picklists/Relations, Mapping, Web service - Applications, Web service - Users, Currencies)
- sometimes it goes to edit only on no-first-column click (Fields – Folders, Fields – Hide Blocks, Business hours)
- sometimes if goes to edit (Workflows)

**Comment by rskrzypczak** [comment]
Thanks.
