### ISSUE TITLE
[bug] Incorrect request Error while Export Users

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#13927]
checked it at https://gitdeveloper.yetiforce.com

![image](https://user-images.githubusercontent.com/12723595/102293732-aeb4c600-3f6d-11eb-9be2-0982bedce9fa.png)

![image](https://user-images.githubusercontent.com/12723595/102293750-b5dbd400-3f6d-11eb-878e-9ddea76b984e.png)

![image](https://user-images.githubusercontent.com/12723595/102293765-baa08800-3f6d-11eb-8f1f-701c27aa84da.png)

![image](https://user-images.githubusercontent.com/12723595/102293775-c1c79600-3f6d-11eb-8ae9-9b63172fd802.png)

Regards
Jeevan Pendhari

**Comment by harshdoshihd** [comment]
I am also getting the same error; I turned on the error reports too but the detail log of error is also not visible
![image](https://user-images.githubusercontent.com/61234565/103075565-d94bf200-45f1-11eb-8e32-a4a907e8854d.png)

**Comment by harshdoshihd** [comment]
> checked it at https://gitdeveloper.yetiforce.com
> 
> ![image](https://user-images.githubusercontent.com/12723595/102293732-aeb4c600-3f6d-11eb-9be2-0982bedce9fa.png)
> 
> ![image](https://user-images.githubusercontent.com/12723595/102293750-b5dbd400-3f6d-11eb-878e-9ddea76b984e.png)
> 
> ![image](https://user-images.githubusercontent.com/12723595/102293765-baa08800-3f6d-11eb-8f1f-701c27aa84da.png)
> 
> ![image](https://user-images.githubusercontent.com/12723595/102293775-c1c79600-3f6d-11eb-8ae9-9b63172fd802.png)
> 
> Regards
> Jeevan Pendhari

Temporary work around is: (Crl+click) on the side menu bar

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/14043
