### ISSUE TITLE
[Question] php memory_limit

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#13931]
Hi,
I'm trying to generate a PDF but a ```PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted``` is issued
I pushed up the PHP memory limit (image from my info.php)

![Schermata da 2020-12-16 17-16-56](https://user-images.githubusercontent.com/48508691/102375996-717b2300-3fc3-11eb-9f7f-53466ffb9987.png)

but in YF still is 1G

![Schermata da 2020-12-16 17-32-06](https://user-images.githubusercontent.com/48508691/102377305-ccf9e080-3fc4-11eb-8c7f-b9f190a54e84.png)

and it seems that my change has not effect on PDF generation: again the same error limit
```PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted```

both YF 5.3 and YF 6.1
same with memory limit to 3G ... always 1073741824 is the limit

**Comment by davide-alghi** [comment]
![ConfReport](https://user-images.githubusercontent.com/48508691/102379421-219e5b00-3fc7-11eb-8d41-3d2f51c6a275.png)

system.log is empty and in php_errors.log
```
[16-Dec-2020 17:51:32 Europe/Rome] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 135168 bytes) in /var/www/html/development/yf_5.3/AA/vendor/yetiforce/yetiforcepdf/lib/Layout/Box.php on line 683

```

**Comment by mariuszkrzaczkowski** [comment]
check .user.ini update the entry or delete the file

**Comment by mariuszkrzaczkowski** [comment]
.user.ini and public_html/.user.ini

**Comment by davide-alghi** [comment]
yes, I forgot ... you're right Mariusz, it works tnx

**Comment by davide-alghi** [comment]
resolved
