### ISSUE TITLE
Why is MySQL DB size too Big - 3 months of usage and the SQL DB size has become approx 20GB  

### ISSUE THREAD

**Issue by harshdoshihd** [YetiForceCompany/YetiForceCRM#13939]
Hi There, 

We have implemented Yetiforce as a pilot and the SQL db size has gone up to 25GB in just 3 months of usage.

We are not uploading and pdf, images, docs, we are just working on typed data.

![yetiforce db](https://user-images.githubusercontent.com/61234565/102583607-03ea0680-412b-11eb-84bf-48571ff4b776.png)

Attached herewith is the screenshot of db files which are consuming lots of space. I think one of he file is related to history tracking, other i didnt understood. Can I get a documentation of what are these directories for and how do I reduce the disk usage.

**Comment by mariuszkrzaczkowski** [comment]
I see notifications or Track Changes are on, do you need this?

**Comment by harshdoshihd** [comment]
I am currently deleting notifications, with regards to track changes, I need something like track changes only for contacts

**Comment by harshdoshihd** [comment]
Hi Mariusz,

I am currently deleting all notifications. 

But for Track changes, I just need it for Contacts, precisely for phone numbers and emails - to keep a track if any employee purposely changes the data.

**Comment by mariuszkrzaczkowski** [comment]
Maybe you have something redundantly configured that you have 16 million notifications,
you can disable the history of changes for the Notifications module
and when you delete it, delete it permanently, not to the trash
