### ISSUE TITLE
Call to a member function getTableName() on boolean

### ISSUE THREAD

**Issue by te-deum** [YetiForceCompany/YetiForceCRM#13937]
# 🐞 bug report

### ⁉️ Describe the bug

I add related modules to the CRM Project and some of them give the error "Call to a member function getTableName() on boolean" when I try to show the tab in the Project page.

### 🔥 How to trigger the error
1) Got to a project
2) Try to open the tab Expertise
3) Get a wait icon that never disapear and serveur respond with an 500 error

### 📷 Screenshot of configuration
When I try to go into Settings, I get this error : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crm.s_yf_mail_rbl_list' doesn't exist Failed to prepare SQL: SELECT * FROM `s_yf_mail_rbl_list` WHERE `ip`=:qp0 ORDER BY `type`

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
CRM Logs are attached.

### 🌍 Your Environment
YetiForce 5.3.0 SP 4
Apache 2.4.6
PHP 7.2.34
MySQL MariaDb 10.2.36
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5708794/system.log)

**Comment by rskrzypczak** [comment]
This is not an application error. The table rightly does not exist in version 5.3. 
Presumably you were updating your application to version 6.0, but something went wrong and you rolled back the changes incorrectly.
As I mentioned, this is not an application error, so I'm closing the issue.

**Comment by te-deum** [comment]
You are right for the second message... I re-apply v6 and it work.
But for the main problem (Call to a member function getTableName() on boolean), it still occur.
