### ISSUE TITLE
[bug] "Call to a member function getTableName() on boolean"

### ISSUE THREAD

**Issue by te-deum** [YetiForceCompany/YetiForceCRM#13941]
# 🐞 bug report

### ⁉️ Describe the bug

I add related modules to the CRM Project and some of them give the error "Call to a member function getTableName() on boolean" when I try to show the tab in the Project page.

### 🔥 How to trigger the error
1) Got to a project
2) Try to open the tab Expertise
3) Get a wait icon that never disapear and serveur respond with an 500 error

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
CRM Logs are attached.
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/5714469/system.log)

### 🌍 Your Environment
YetiForce 6.1.0 SP 1
Apache 2.4.6
PHP 7.2.34
MySQL MariaDb 10.2.36

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version

**Comment by te-deum** [comment]
Hello,

This error came in version 5.3.0 and still persists whenever I update to 6.0, 6.1, 6.1 SP1.
How do I check dev-version ? Should I copy dev files over my current install ?

Thank you for your help.

**Comment by mariuszkrzaczkowski** [comment]
here try to trigger the error https://gitdeveloper.yetiforce.com/

**Comment by mariuszkrzaczkowski** [comment]
From what i can see this is a custom relation you created and maybe it was created in a wrong way or something broke it

**Comment by te-deum** [comment]
After digging into the code, I suspect a problem with _vtiger_relatedlists_fields_.
The data for my tabid are not in the datatable !?

**Comment by mariuszkrzaczkowski** [comment]
Your database is corrupted, I suppose some update wasn't performed properly.

**Comment by te-deum** [comment]
Here is why I may leave Yetiforce CRM !! A trouble that break database when migrating from a version to another and no more help than this ! The product is not stable enough to work with it in a production enterprise.

I loosed so much time with YetiForce... I am very disappointed.
