### ISSUE TITLE
SalesOrder. Saving in detail view

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1396]
When I saving some filed in detail view I get the message
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/8544675/ace60faa-24a7-11e5-8917-454773d445c3.png)

In edit view it works fine. Shouldn't this field be mandatory after enabling recurring?

**Comment by bpabiszczak** [comment]
Ta funkcjonalność będzie przebudowywana w wersji 2.2 całkowicie..
