### ISSUE TITLE
How do i install roundcube module[Question] 

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13968]
### Description

whenever I try to import roundcube_master.zip which I downloaded from github , I get this error message saying 
"Failed
Module does not contain default language (en-US). "
how do I fix it???

![Screenshot (96)](https://user-images.githubusercontent.com/40380541/102901380-a68ce700-4495-11eb-802c-2110dc72631f.png)

**Comment by z0lo13** [comment]
to manually install it, replace the content of 'roundcube' folder in public_html/modules/OSSMail/ with a contents of archive

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?q=Module+does+not+contain+default+language
