### ISSUE TITLE
Edit fields not working, how to fix it?[Question] 

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13969]
### Description

From a few days, I am not able to do any actions in the edit field section.
Whenever I select that module, suddenly nothing works, not able to click any button.
Non of buttons such as "Add custom block" works.
below is a screenshot of the menu I am talking about.
how do I fix this?

yetiforce version: 6.0

![Screenshot (97)](https://user-images.githubusercontent.com/40380541/102967059-3a53c700-4519-11eb-8df1-1cf668d1f70d.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/discussions

**Comment by mariuszkrzaczkowski** [comment]
Are you reporting a bug?
yes - choose a different template and fill in the required information
no - write it in https://github.com/YetiForceCompany/YetiForceCRM/discussions

**Comment by harshdoshihd** [comment]
> ### Description
> From a few days, I am not able to do any actions in the edit field section.
> Whenever I select that module, suddenly nothing works, not able to click any button.
> Non of buttons such as "Add custom block" works.
> below is a screenshot of the menu I am talking about.
> how do I fix this?
> 
> yetiforce version: 6.0
> 
> ![Screenshot (97)](https://user-images.githubusercontent.com/40380541/102967059-3a53c700-4519-11eb-8df1-1cf668d1f70d.png)
seems your company's verification is not yet completed - check a triangle red alert next to search bar

**Comment by rohanjhanepal** [comment]
what more info do you need?? lots of people are facing the same problem. To simplify for you, whenever I go to edit field section, none of the buttons works, for example clicking on "Add custom block" does nothing at all

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/103915262-45a71500-510b-11eb-84e4-085df5c3ac15.jpg)

**Comment by rioshaz** [comment]
@rohanjhanepal go to admin setting then logs then update... n update the system it will fix the problem.... 6.0 has this bug....
