### ISSUE TITLE
Time not getting imported properly

### ISSUE THREAD

**Issue by harshdoshihd** [YetiForceCompany/YetiForceCRM#13973]
Hi Team,

I migrates from a old Yetiforce set-up to a fresh set-up in the same server, but while trying to import time there seems to be some issue. 

The time automatically got changed when I imported the same:
Old Server date and time:
 
![old server](https://user-images.githubusercontent.com/61234565/103159006-314d4900-47ea-11eb-8586-a13d4b7e8280.jpg)

New Serve Date and time:
![new server](https://user-images.githubusercontent.com/61234565/103159014-41fdbf00-47ea-11eb-8715-2aab411d4fe3.jpg)

Can you please help me with the same.

Best Regards,
Harsh

**Comment by harshdoshihd** [comment]
I just figured it that the data is converted from IST to PST. Is there any way where it imports as well in IST.

PS: Timezone for all users in new setup as well as old setup is set to IST

**Comment by harshdoshihd** [comment]
Additional Updates:

We selected start date and time  as 28th Dec 10: 20 AM 
End date and time as 28th Dec 18:35 PM

The entry got saved as below:
![timecontrol](https://user-images.githubusercontent.com/61234565/103219131-e4c95100-4942-11eb-915b-027eaadbc844.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/103264818-1d514500-49ac-11eb-8e3d-27c34daf503e.jpg)

**Comment by mariuszkrzaczkowski** [comment]
1. complete the required information
2. What is the user's and system time zone?

**Comment by harshdoshihd** [comment]
Thanks Marius. 

While finding the detail info of the problem, came across the solution. Same is the solution for case [#13978](https://github.com/YetiForceCompany/YetiForceCRM/issues/13978)
