### ISSUE TITLE
Roundcube installation issue after yetiforce system update

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13977]
I am getting following errors while trying to install roundcube although I already have it installed , still yeti is suggesting me to install it again..
ERRORS:
E_WARNING: disk_free_space(): No such file or directory in /home/customer/www/office.koreabazar.com/public_html/app/Utils/ConfReport.php, line 1356

E_WARNING: disk_total_space(): No such file or directory in /home/customer/www/office.koreabazar.com/public_html/app/Utils/ConfReport.php, line 1357

E_WARNING: Division by zero in /home/customer/www/office.koreabazar.com/public_html/app/Utils/ConfReport.php, line 1360

Screenshot of the errors:
![Screenshot (98)](https://user-images.githubusercontent.com/40380541/103211679-f73a8f00-4930-11eb-9e00-28c8f9925cd7.png)
![Screenshot (99)](https://user-images.githubusercontent.com/40380541/103211686-fbff4300-4930-11eb-819a-05cb5a1b3bf1.png)
![Screenshot (100)](https://user-images.githubusercontent.com/40380541/103211797-454f9280-4931-11eb-8e3a-c8be34897401.png)

System information:
![Screenshot (101)](https://user-images.githubusercontent.com/40380541/103211960-b000ce00-4931-11eb-87dc-7322bee639a7.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/103214488-cfd3ca00-4910-11eb-937c-2fb454cac526.jpg)
