### ISSUE TITLE
Edit fields section not working[bug] 

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#13975]
# 🐞 bug report

### ⁉️ Describe the bug

From a few days, I am not able to do any actions in the edit field section.
Whenever I select that module, suddenly nothing works, not able to click any button.
Non of buttons such as "Add custom block" works.
below is a screenshot of the menu I am talking about.
how do I fix this?

### 👍 Expected Behavior

should let me edit fields of each and every modules.

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![Screenshot (97)](https://user-images.githubusercontent.com/40380541/103205260-437dd300-4921-11eb-96e2-cc9aafe426b2.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                    | 6.0
| Web server (name and version)       |      Sitegrounds          |
| PHP                                 |        7.3        |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |       v4         |

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/103205867-d6574700-48fa-11eb-9c95-1b620433efc5.jpg)
