### ISSUE TITLE
[bug] 'Edit fields' page broken on ver. 6.1.0

### ISSUE THREAD

**Issue by camposfajardo** [YetiForceCompany/YetiForceCRM#13983]
Hi there,

After the last update to ver. 6.1.0, the page 'Edit fields' has stopped working. The page loads properly but the buttons and fields do not respond. If I change the Module to be edited, it remains on the same page, doesn't update to the fields of another module. If I open it on Brave browser, I receive a message: "Sorry the page is missing."

Any ideas on what could  be causing it?

Cheers, and many tnx,

**Comment by davide-alghi** [comment]
Hi @camposfajardo,
did you install all Service Packs?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/103348933-bf038f80-4a9b-11eb-8186-9a7c60ba7ec9.jpg)
