### ISSUE TITLE
How to get Value of specific field from record

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#13981]
Hi,

We are trying to use CRM and really working for most of requirements. for one of my rquirement, I am trying to write code for custom widget

I am trying to work on copy of Vtiger_RelatedModule_Widget file, where I need to get the parent_id value. I tried to code, but no success. Please assist how do I get parent_id value from record.

Module: Contact
below is code to get record value, I am trying.
**$parentRecordId = $this->Record['parent_id'];**

Result is no Value, I tried writting **$parentRecordId = $this->Record->get('parent_id');** but same give error.

![image](https://user-images.githubusercontent.com/12723595/103278808-61ffcf00-49f2-11eb-9057-36f454e36a3a.png)

Your kind assistance will help me to solve my problem.

Thanks In Advance.
Jeevan Pendhari

**Comment by z0lo13** [comment]
Hello,

$parentRecordId = $this->Record['parent_id']; -  is not valid code to begin with

Tutorial:
**First** you need a Vtiger_Record_Model Instance, there are multiple way of calling it, please consult code.
**Second** with a record Model you can get the value of field. 
**Third** your issue is having too less context, but lets say you are creating a widget as it should be, in that case you will need to work with a request.

```
$recordId = $request->getInteger('record'); // Get RecordId
$recordModel = Vtiger_Record_Model::getInstanceById($recordId); // Initialize Record Model
$parentRecordId = $recordModel->get('parent_id'); // Get the parent_id value
```

IMHO you need to hire a developer, this project is not for beginners.

**Comment by JEEVAN28** [comment]
> Hello,
> 
> $parentRecordId = $this->Record['parent_id']; - is not valid code to begin with
> 
> Tutorial:
> **First** you need a Vtiger_Record_Model Instance, there are multiple way of calling it, please consult code.
> **Second** with a record Model you can get the value of field.
> **Third** your issue is having too less context, but lets say you are creating a widget as it should be, in that case you will need to work with a request.
> 
> ```
> $recordId = $request->getInteger('record'); // Get RecordId
> $recordModel = Vtiger_Record_Model::getInstanceById($recordId); // Initialize Record Model
> $parentRecordId = $recordModel->get('parent_id'); // Get the parent_id value
> ```
> 
> IMHO you need to hire a developer, this project is not for beginners.

Hi,
Thanks for help, I recognized this later as record variable is containing only record id value and not entire record set. Done this later.

Regards
Jeevan Pendhari
