### ISSUE TITLE
[bug] PAssword module dont accept password longer then 14 characters

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#13992]
when u try to enter a new password in the password module its gives the error that password is too long.. 
i have tested this in gitdeveloper and it also has the same problem.. pls check below..

![image](https://user-images.githubusercontent.com/54880467/103458027-2c2c5480-4d2a-11eb-8818-2c51ba54d779.png)

please share a possible fix... i have already checked admin, security, password configurations.. max length is set to 32 ,,,

**Comment by diderich** [comment]
Strange!

Configuration in the database does not match configuration displayed in the password setup screen. Changing the data in the password setup screen does not modify the database (although system says that data is saved).

DATABASE
![pwd-db](https://user-images.githubusercontent.com/10230144/103459189-98e52600-4d0d-11eb-9557-d19849fdb5b6.png)

PASSWORD SETUP SCREEN
![pwd-set](https://user-images.githubusercontent.com/10230144/103459190-9b478000-4d0d-11eb-85e8-6679468ae18b.png)

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=OSSPasswords&view=ConfigurePass&parent=Settings
