### ISSUE TITLE
[bug] Po aktualizacji nie można się zalogować (czyszczenie cookies nic nie daje)

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#13997]
Witam,
po aktualizacji z 5.3.0 do 6.0.0 system nie przyjmuje danych logowania, po wpisaniu nazwy użytkownika i hasła próbuje wczytać jednak po ułamku sekundy wraca do ekranu logowania.
Na zmyślone dane logowania reaguje tak samo.
Logi błędów nie generują się, powstają tylko pliki session w cache\session
Nie generują się żadne cookies ani dane lokalne

Po przywróceniu plików na serwerze można się zalogować ale jest błąd, prawdopodobnie z powodu aktualizacji bazy.

Mogę liczyć na jakąś podpowiedź?

**Comment by bpabiszczak** [comment]
Należy włączyć logi i sprawdzić czemu system odrzuca logowania. 
Ewentualnie można zresetować hasło.

**Comment by Sall2** [comment]
Zamiast poprawnych danych prywatnych są XXXXXXXXXX:
System.log:
"2021-01-04 17:13:07.6687 [info][yii\db\Connection::open] - Opening DB connection: mysql:host=XXXXXXXXXXX;dbname=XXXXXXXXXX;port=3307
2021-01-04 17:13:07.6699 [info][yii\db\Command::query] - SELECT * FROM `a_yf_bruteforce` LIMIT 1
2021-01-04 17:13:07.6717 [info][yii\db\Command::query] - SELECT `id` FROM `a_yf_bruteforce_blocked` WHERE (`time` > '2021-01-04 16:58:07') AND (`ip`='188.47.70.48') AND (`blocked`=1) LIMIT 1
2021-01-04 17:13:07.6399 [info][application] - 
$_GET = []
$_POST = []
$_FILES = []
$_COOKIE = []
$_SESSION = [
    'CSP_TOKEN' => 'ef32784558e01d4e85ad66f980a1cf949c22f46595cdd443672b46737f0aa0f4'
    'last_activity' => 1609776787.6484
]
HEADERS = [
    'Accept-Language' => 'pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7'
    'Accept-Encoding' => 'gzip, deflate, br'
    'Sec-Fetch-Dest' => 'document'
    'Sec-Fetch-User' => '?1'
    'Sec-Fetch-Mode' => 'navigate'
    'Sec-Fetch-Site' => 'none'
    'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284'
    'Upgrade-Insecure-Requests' => '1'
    'Cache-Control' => 'max-age=0'
    'Connection' => 'keep-alive'
    'Host' => 'XXXXXXXXXXXXXX:8091'
    'Content-Length' => ''
    'Content-Type' => ''
]
$stability = [
    'error_reporting' => 'E_ALL & ~E_NOTICE'
    'default_socket_timeout' => '600'
    'memory_limit' => '1.00 GB'
    'post_max_size' => '50 MB'
    'upload_max_filesize' => '100 MB'
    'max_input_vars' => '10000'
    'auto_detect_line_endings' => 'On'
]
$security = [
    'display_errors' => 'Off'
    'session.use_strict_mode' => 'On'
    'disable_functions' => ''
]
$headers = [
    'Header: server' => 'nginx'
    'Header: referrer-policy' => 'no-referrer'
    'Header: expect-ct' => 'enforce; max-age=3600'
    'Header: x-frame-options' => 'sameorigin'
    'Header: x-xss-protection' => '1; mode=block'
    'Header: x-content-type-options' => 'nosniff'
    'Header: x-robots-tag' => 'none'
    'Header: x-permitted-cross-domain-policies' => 'none'
    'Header: strict-transport-security' => 'max-age=31536000; includeSubDomains; preload'
    'Header: content-security-policy' => 'default-src \'self\' blob:; img-src \'self\' data: a.tile.openstreetmap.org b.tile.openstreetmap.org c.tile.openstreetmap.org; script-src \'self\' \'unsafe-inline\' blob:; form-action \'self\' https://www.paypal.com; frame-ancestors \'self\'; style-src \'self\' \'unsafe-inline\'; connect-src \'self\';'
]
$libraries = [
    'imagick' => 'LBL_NO'
]
$database = [
    'table_open_cache' => '10'
    'table_definition_cache' => '400'
]
$performance = [
    'opcache.enable' => 'On'
    'opcache.enable_cli' => 'On'
    'realpath_cache_ttl' => '600'
    'mysqlnd.collect_statistics' => 'Off'
]
$environment = [
    'currentUser' => ' (uid:1023)'
    'error_log' => false
    'openssl.cafile' => false
    'openssl.capath' => false
]
====================================================================================================================================
2021-01-04 17:13:11.6827 [info][yii\db\Connection::open] - Opening DB connection: mysql:host=xxxxxxxxxx;dbname=xxxxxxxxxxx;port=3307
2021-01-04 17:13:11.684 [info][yii\db\Command::query] - SELECT * FROM `a_yf_bruteforce` LIMIT 1
2021-01-04 17:13:11.6875 [info][yii\db\Command::query] - SELECT `id` FROM `a_yf_bruteforce_blocked` WHERE (`time` > '2021-01-04 16:58:11') AND (`ip`='188.47.70.48') AND (`blocked`=1) LIMIT 1
2021-01-04 17:13:11.6937 [trace] - Entering getColumnFields(Users) method ...
2021-01-04 17:13:11.6952 [info][yii\db\Command::query] - SELECT * FROM `vtiger_field` WHERE `tabid`=29
2021-01-04 17:13:11.696 [trace] - Exiting getColumnFields method ...
2021-01-04 17:13:11.6986 [info][yii\db\Command::query] - SELECT * FROM `vtiger_tab`
2021-01-04 17:13:11.6993 [info][yii\db\Command::query] - SELECT * FROM `vtiger_entityname`
2021-01-04 17:13:11.7005 [info][yii\db\Command::query] - SELECT `id`, `deleted` FROM `vtiger_users` WHERE (`user_name`='xxxxxxxxxxx') OR (`user_name`='xxxxxxxxxxxxx') LIMIT 1
2021-01-04 17:13:11.7012 [info][yii\db\Command::query] - SELECT * FROM `yetiforce_auth`
2021-01-04 17:13:11.7526 [info][yii\db\Command::query] - SELECT * FROM `vtiger_eventhandlers` WHERE `is_active`=1 ORDER BY `priority` DESC
2021-01-04 17:13:11.7535 [info][yii\db\Command::query] - SELECT * FROM `vtiger_password`
2021-01-04 17:13:11.7538 [info][yii\db\Command::query] - SELECT `id` FROM `vtiger_users` WHERE `user_name`='xxxxxxxxxxxxx' LIMIT 1
2021-01-04 17:13:11.7556 [info][yii\db\Command::query] - SHOW FULL COLUMNS FROM `vtiger_loginhistory`
2021-01-04 17:13:11.7566 [info][yii\db\Command::query] - SELECT
    `kcu`.`CONSTRAINT_NAME` AS `constraint_name`,
    `kcu`.`COLUMN_NAME` AS `column_name`,
    `kcu`.`REFERENCED_TABLE_NAME` AS `referenced_table_name`,
    `kcu`.`REFERENCED_COLUMN_NAME` AS `referenced_column_name`
FROM `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc`
JOIN `information_schema`.`KEY_COLUMN_USAGE` AS `kcu` ON
    (
        `kcu`.`CONSTRAINT_CATALOG` = `rc`.`CONSTRAINT_CATALOG` OR
        (`kcu`.`CONSTRAINT_CATALOG` IS NULL AND `rc`.`CONSTRAINT_CATALOG` IS NULL)
    ) AND
    `kcu`.`CONSTRAINT_SCHEMA` = `rc`.`CONSTRAINT_SCHEMA` AND
    `kcu`.`CONSTRAINT_NAME` = `rc`.`CONSTRAINT_NAME`
WHERE `rc`.`CONSTRAINT_SCHEMA` = database() AND `kcu`.`TABLE_SCHEMA` = database()
AND `rc`.`TABLE_NAME` = 'vtiger_loginhistory' AND `kcu`.`TABLE_NAME` = 'vtiger_loginhistory'
2021-01-04 17:13:11.757 [info][yii\db\Command::execute] - INSERT INTO `vtiger_loginhistory` (`user_name`, `user_ip`, `login_time`, `logout_time`, `status`, `browser`, `userid`, `agent`) VALUES ('XXXXXXXXXXXXXXXXX', '188.47.70.48', '2021-01-04 17:13:11', NULL, 'Signed in', 'Google Chrome 73', 1, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284')
2021-01-04 17:13:11.6608 [info][application] - 
$_GET = [
    'module' => 'Users'
    'action' => 'Login'
]
$_POST = [
    'username' => 'XXXXXXXXXXXXXX'
    'password' => 'XXXXXXXXXXXX'
    'fingerprint' => 'be7125c7-c1a9-44b1-b1e8-f46e27b3b07e'
]
$_FILES = []
$_COOKIE = []
$_SESSION = [
    'last_activity' => 1609776791.669
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => '99fbbbf687c6f8cf77e1cc78deded69b28874087'
    'user_name' => 'XXXXXXXXXXXXXXXXX'
    'full_user_name' => 'XXXXXXXXXXXXXXXX'
    'fingerprint' => 'be7125c7-c1a9-44b1-b1e8-f46e27b3b07e'
    'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284'
    'showVisitPurpose' => true
]
HEADERS = [
    'Accept-Language' => 'pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7'
    'Accept-Encoding' => 'gzip, deflate, br'
    'Sec-Fetch-Dest' => 'document'
    'Sec-Fetch-User' => '?1'
    'Sec-Fetch-Mode' => 'navigate'
    'Sec-Fetch-Site' => 'same-origin'
    'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284'
    'Content-Type' => 'application/x-www-form-urlencoded'
    'Origin' => 'null'
    'Upgrade-Insecure-Requests' => '1'
    'Cache-Control' => 'max-age=0'
    'Content-Length' => '98'
    'Connection' => 'keep-alive'
    'Host' => 'XXXXXXXXXXX:8091'
]
$stability = [
    'error_reporting' => 'E_ALL & ~E_NOTICE'
    'default_socket_timeout' => '600'
    'memory_limit' => '1.00 GB'
    'post_max_size' => '50 MB'
    'upload_max_filesize' => '100 MB'
    'max_input_vars' => '10000'
    'auto_detect_line_endings' => 'On'
]
$security = [
    'display_errors' => 'Off'
    'session.use_strict_mode' => 'On'
    'disable_functions' => ''
]
$headers = [
    'Header: server' => 'nginx'
    'Header: referrer-policy' => 'no-referrer'
    'Header: expect-ct' => 'enforce; max-age=3600'
    'Header: x-frame-options' => 'sameorigin'
    'Header: x-xss-protection' => '1; mode=block'
    'Header: x-content-type-options' => 'nosniff'
    'Header: x-robots-tag' => 'none'
    'Header: x-permitted-cross-domain-policies' => 'none'
    'Header: strict-transport-security' => 'max-age=31536000; includeSubDomains; preload'
    'Header: content-security-policy' => 'default-src \'self\' blob:; img-src \'self\' data: a.tile.openstreetmap.org b.tile.openstreetmap.org c.tile.openstreetmap.org; script-src \'self\' \'unsafe-inline\' blob:; form-action \'self\' https://www.paypal.com; frame-ancestors \'self\'; style-src \'self\' \'unsafe-inline\'; connect-src \'self\';'
]
$libraries = [
    'imagick' => 'LBL_NO'
]
$database = [
    'table_open_cache' => '10'
    'table_definition_cache' => '400'
]
$performance = [
    'opcache.enable' => 'On'
    'opcache.enable_cli' => 'On'
    'realpath_cache_ttl' => '600'
    'mysqlnd.collect_statistics' => 'Off'
]
$environment = [
    'currentUser' => ' (uid:1023)'
    'error_log' => false
    'openssl.cafile' => false
    'openssl.capath' => false
]
====================================================================================================================================
2021-01-04 17:13:12.0654 [info][yii\db\Connection::open] - Opening DB connection: mysql:host=XXXXXXXXXXXXX;dbname=XXXXXXXXXXX;port=3307
2021-01-04 17:13:12.0666 [info][yii\db\Command::query] - SELECT * FROM `a_yf_bruteforce` LIMIT 1
2021-01-04 17:13:12.0682 [info][yii\db\Command::query] - SELECT `id` FROM `a_yf_bruteforce_blocked` WHERE (`time` > '2021-01-04 16:58:12') AND (`ip`='188.47.70.48') AND (`blocked`=1) LIMIT 1
2021-01-04 17:13:12.0372 [info][application] - 
$_GET = []
$_POST = []
$_FILES = []
$_COOKIE = []
$_SESSION = [
    'CSP_TOKEN' => 'ef1a5e68e55d13e8b4330db5dea68e133f8d1a9f20a07e063c61e6075e60fdf8'
    'last_activity' => 1609776792.0454
]
HEADERS = [
    'Accept-Language' => 'pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7'
    'Accept-Encoding' => 'gzip, deflate, br'
    'Sec-Fetch-Dest' => 'document'
    'Sec-Fetch-User' => '?1'
    'Sec-Fetch-Mode' => 'navigate'
    'Sec-Fetch-Site' => 'same-origin'
    'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284'
    'Upgrade-Insecure-Requests' => '1'
    'Cache-Control' => 'max-age=0'
    'Connection' => 'keep-alive'
    'Host' => 'XXXXXXXXXXXXXXXX:8091'
    'Content-Length' => ''
    'Content-Type' => ''
]
$stability = [
    'error_reporting' => 'E_ALL & ~E_NOTICE'
    'default_socket_timeout' => '600'
    'memory_limit' => '1.00 GB'
    'post_max_size' => '50 MB'
    'upload_max_filesize' => '100 MB'
    'max_input_vars' => '10000'
    'auto_detect_line_endings' => 'On'
]
$security = [
    'display_errors' => 'Off'
    'session.use_strict_mode' => 'On'
    'disable_functions' => ''
]
$headers = [
    'Header: server' => 'nginx'
    'Header: referrer-policy' => 'no-referrer'
    'Header: expect-ct' => 'enforce; max-age=3600'
    'Header: x-frame-options' => 'sameorigin'
    'Header: x-xss-protection' => '1; mode=block'
    'Header: x-content-type-options' => 'nosniff'
    'Header: x-robots-tag' => 'none'
    'Header: x-permitted-cross-domain-policies' => 'none'
    'Header: strict-transport-security' => 'max-age=31536000; includeSubDomains; preload'
    'Header: content-security-policy' => 'default-src \'self\' blob:; img-src \'self\' data: a.tile.openstreetmap.org b.tile.openstreetmap.org c.tile.openstreetmap.org; script-src \'self\' \'unsafe-inline\' blob:; form-action \'self\' https://www.paypal.com; frame-ancestors \'self\'; style-src \'self\' \'unsafe-inline\'; connect-src \'self\';'
]
$libraries = [
    'imagick' => 'LBL_NO'
]
$database = [
    'table_open_cache' => '10'
    'table_definition_cache' => '400'
]
$performance = [
    'opcache.enable' => 'On'
    'opcache.enable_cli' => 'On'
    'realpath_cache_ttl' => '600'
    'mysqlnd.collect_statistics' => 'Off'
]
$environment = [
    'currentUser' => ' (uid:1023)'
    'error_log' => false
    'openssl.cafile' => false
    'openssl.capath' => false
]
====================================================================================================================================
"

**Comment by Sall2** [comment]
Ok, mam dalsze informacje, miałem jeszcze jedną instancję na serwerze w ramach testu zrobioną. Wgrałem aktualizację do 6.0.0, weszła cała, następnie bez przelogowywania się zrobiłem update języków, i wszystkie aktualizacje aż do najnowszej. System działał bez problemu, aż do pierwszego wylogowania się. Później to już jak powyżej.
Log wygląda praktycznie tak samo.

Jak zresetować hasło? Przez bazę? Tam jest zaszyfrowane.

**Comment by bpabiszczak** [comment]
Weryfikacja i naprawa tego, to pewnie 15 min [o ile jest co naprawiać]. Ale aby to rozwiązać, trzeba się zalogować na serwer i programista musi sprawdzić problem. Możemy to zrobić o ile masz wykupione godzina wsparcia, jeżeli nie to będzie trzeba poczekać aż będziemy mieli chwilę czasu i na to zerkniemy na podstawie danych które tutaj podałeś.

**Comment by Sall2** [comment]
Ok, posprawdzam jeszcze, wykupionych godzin nie mam, ale postawiłem od nowa cały crm w celach testowych z wersji 6.1.0 complete i po instalacji jest to samo, nie można się zalogować, z poprzednimi wersjami nie było takich problemów, coś musiało się mocno zmienić.
Raczej wina konfiguracji serwera tak jak mówisz, ponieważ sprawdziłem na hostingu współdzielonym i jest wszystko ok, mimo, że tam parametry php dużo gorsze są.
Czy to może mieć związek z certyfikatami i bezpiecznym połączeniem?
