### ISSUE TITLE
[FEATURES] Kopiowanie- pobieranie adresu z danych kontrahenta - Copy-Get Adress from AccountID

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#13991]
Co stało się z funkcjonalnością kopiowania - pobierania adresu z adresu głównego kontrahenta np w ofertach, zamówieniach.
-
What happened to the copying functionality - retrieving the address from the address of the Account, e.g. in offers, orders.

**Comment by apcloic** [comment]
@zimart Hi, 
Check this #13943
Regards
