### ISSUE TITLE
[Pytanie-Question] Pobranie vartości pola typu "Picklist" do innego - Getting the value of a "Picklist" field to another

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#13990]
Czy ktoś podpowiedziałby mi, jak pobrać wartość z pola typu "picklist" lub "picklistfield" w tabeli "inventory - row".
Potrzebuję dodać własne pole o wartości : wartość z pola picklist + wartość innego pola (plik Inventory.js)

----
Could anyone tell me how to get value from "picklist" or "picklistfield" in "inventory - row" table.
I need to add my own field with the value: picklist value + another field value. (file Inventory.js)

---	

getvalue_from_picklist: function(row) ... :(

**Comment by apcloic** [comment]
@zimart
Hi, you'd better post your question on discussions tab, Issues section is now only for bugs. 
You may have missed the following announcement
#13908
Regards,
