### ISSUE TITLE
[bug][adding user] Typo in polish copy "kontaków"

### ISSUE THREAD

**Issue by klexit** [YetiForceCompany/YetiForceCRM#14003]
YetiForce.com [ver. 6.1.0]
1. Go to settings
2. Go to users
3. Add new user
4. Scroll to section: Integracja z DAV
5. Frist polish translation paragraph with typo 

> Synchronizacja **kontaków** CardDAV
> Określa, które rekordy z modułu Kontakty mają być synchronizowane przy użyciu protokołu CardDAV.

![image](https://user-images.githubusercontent.com/61927217/103636320-172e0c00-4f4a-11eb-92cb-f02dbdfcaad4.png)
![image](https://user-images.githubusercontent.com/61927217/103636382-2d3bcc80-4f4a-11eb-9f93-066158bfae8b.png)

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/103637853-61b08800-4f4c-11eb-84e9-a19bb6073159.png)

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Users&parent=Settings&view=Edit

**Comment by klexit** [comment]
https://www.loom.com/share/615118a0179f4a6fa2df4b4e4a1fe7be

**Comment by rskrzypczak** [comment]
Dzięki, aczkolwiek tłumaczenia realizowane są przez platformę [crowdin](https://crowdin.com/project/yetiforcecrm) i tam należy zgłaszać uwagi.

**Comment by KatarzynaUlichnowska** [comment]
Dziękujemy za zwrócenie uwagi na literówkę. Zachęcamy do dołączenia do naszej społeczności i korzystania z platformy Crowdin, gdzie samemu można sugerować poprawki lub dodawać całe tłumaczenia. Podaje link do języka [polskiego](https://crowdin.com/translate/yetiforcecrm/all/en-pl?filter=basic&value=0)
A [tutaj ](https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/dodawanie-tlumaczen-poprzez-crowdin) objaśnienia jak to wszystko działa.
