### ISSUE TITLE
[bug] Cant select a field that has a date type in widget

### ISSUE THREAD

**Issue by gogroupvn** [YetiForceCompany/YetiForceCRM#14028]
Cant select a field that has a date type in widget
🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅-->

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

https://user-images.githubusercontent.com/19627226/104091898-0b787780-52b3-11eb-82bf-bd073871c6ce.mov

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/6180568b419b0f267773079f0abce93fa0b5feb7
