### ISSUE TITLE
product list

### ISSUE THREAD

**Issue by e-instytucja** [YetiForceCompany/YetiForceCRM#14031]
Hi Team, 

when trying to add a product or service in the calculation or offer, I cannot select the available products, but only add a new product:
![image](https://user-images.githubusercontent.com/57725994/104185684-95405600-5415-11eb-9540-8a864bebc4be.png)

products:
![image](https://user-images.githubusercontent.com/57725994/104185600-78a41e00-5415-11eb-9114-1f4423352be4.png)

Is it possible to display products / services entered in the tables and in stock?

BR
Dominik

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13795 https://github.com/YetiForceCompany/YetiForceCRM/issues/13846
![github](https://user-images.githubusercontent.com/10198654/104285384-d6874300-54b3-11eb-9a0d-2d392ae090e1.jpg)
