### ISSUE TITLE
[Question] Update to PhpSpreadsheet (1.15.0)

### ISSUE THREAD

**Issue by johniexxx** [YetiForceCompany/YetiForceCRM#14041]
Hello
I tried to update the library to 1.16.0 and the XSS Vulnerability in HTML Writer and the issue still exists.
Can anyone give me guide with the update?

Thank you

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/discussions/13996
