### ISSUE TITLE
[bug] PDF watermark doesn't parse variables

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#14045]
# 🐞 bug report

### ⁉️ Describe the bug

Any variable what inserted to PDF watermark field rendered as usual text in generated PDF

### 🔥 How to trigger the error

Fill watermark content with variable 

![image](https://user-images.githubusercontent.com/8545791/104700600-7992c380-5725-11eb-803a-2558cb993785.png)

### 👎 Actual Behavior

Result

![image](https://user-images.githubusercontent.com/8545791/104700792-bf4f8c00-5725-11eb-9ea0-12260fa89144.png)

### 👍 Expected Behavior

Should be value returned by variable

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3, current gitdev 6.1

**Comment by vovpff** [comment]
@mariuszkrzaczkowski Any ideas?

**Comment by mariuszkrzaczkowski** [comment]
show HTML

**Comment by vovpff** [comment]
@mariuszkrzaczkowski do you mean source?
![image](https://user-images.githubusercontent.com/8545791/104905333-40f82180-5993-11eb-9d99-3918bc6e8a7d.png)

**Comment by mariuszkrzaczkowski** [comment]
Check if it works properly

**Comment by vovpff** [comment]
@mariuszkrzaczkowski now it parse variables but other bad thing found.
Line breaks ignored inside span

```
<span style="font-size:72px">$(record : subject)$<br />
$(record : subject)$<br />
$(record : subject)$</span>
```

If subject is `AAA` then watermark returned as

```
AAA AAA AAA
```

instead 

```
AAA
AAA
AAA
```

I need to add new issue?

**Comment by mariuszkrzaczkowski** [comment]
> I need to add new issue?

Yes

**Comment by vovpff** [comment]
Ok. I will post it tomorrow
