### ISSUE TITLE
[bug] Error when delete multiple categorie 

### ISSUE THREAD

**Issue by ad1rie1** [YetiForceCompany/YetiForceCRM#14046]
# 🐞 bug report

### ⁉️ Describe the bug

Error when you delete multiple categorie at the same time

### 🔥 How to trigger the error

When you go in Setting -> Standard Module -> Field - Folder -> Edit "Categorie of product  module". 

When you delete only one categorie and save, it's Ok

When you delete two or more categorie and save , go error 

### 👎 Actual Behavior

App\Exceptions\IllegalValue: ERR_NOT_ALLOWED_VALUE||new in app/Request.php:317
Stack trace:
#0 app/Request.php(362): App\Request->purifyMultiDimensionArray()
#1 modules/Settings/TreesManager/actions/Save.php(21): App\Request->getMultiDimensionArray()
#2 include/main/WebUI.php(189): Settings_TreesManager_Save_Action->process()
#3 index.php(28): Vtiger_WebUI->process()
#4 public_html/index.php(11): require('/home/gitdevelo...')
#5 {main}#0 [error] ERR_NOT_ALLOWED_VALUE||new
App\Exceptions\IllegalValue: ERR_NOT_ALLOWED_VALUE||new in app/Request.php:317
Stack trace:
#0 app/Request.php(362): App\Request->purifyMultiDimensionArray()
#1 modules/Settings/TreesManager/actions/Save.php(21): App\Request->getMultiDimensionArray()
#2 include/main/WebUI.php(189): Settings_TreesManager_Save_Action->process()
#3 index.php(28): Vtiger_WebUI->process()
#4 public_html/index.php(11): require('/home/gitdevelo...')
#5 {main}

### 👍 Expected Behavior

all good :)

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by areksolek** [comment]
The problem does not exist in the current version.

![2R1RxnieJI](https://user-images.githubusercontent.com/25615135/106139688-0732d200-616e-11eb-938f-dbb37061e0e1.gif)

**Comment by ad1rie1** [comment]
You need to delete two category, not only one ;)

**Comment by ad1rie1** [comment]
Ok , Delete one category, after, delete one more category, and after save 

**do not** multiple select and then delete
