### ISSUE TITLE
Tracking sales stage change

### ISSUE THREAD

**Issue by samuelsituma** [YetiForceCompany/YetiForceCRM#14057]
How can I know the period  it took for an opportunity to be closed in yetiforce CRM 

Thanks

**Comment by rskrzypczak** [comment]
You can use  'Field history and duration summary' widget.
![image](https://user-images.githubusercontent.com/10221999/104882078-b3044280-5962-11eb-8327-7b054a55278a.png)

Please use “Issues” only for reporting bugs, errors, and “Discussions” to everything else (https://github.com/YetiForceCompany/YetiForceCRM/issues/13908)

**Comment by samuelsituma** [comment]
Thank you so much for the response but I can't see Field history and
duration on the widget list where can I find it ?

Regards.

**Comment by rskrzypczak** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Widgets&parent=Settings&view=Index
Available: YF v.6+

**Comment by samuelsituma** [comment]
Thanks I have upgraded to v6+ ,I can I see the widget added to the module
but it's not displaying .. what's the procedure to help me display it on
the dashboard?

**Comment by vovpff** [comment]
Try to clear browser cache at first.

**Comment by samuelsituma** [comment]
I have cleared but still doesn't display

**Comment by samuelsituma** [comment]
Can you show me the procedure of how you are doing it maybe am doing
something wrong thank you

**Comment by vovpff** [comment]
@samuelsituma what procedure yo mean?
Are your update process was successful?

**Comment by samuelsituma** [comment]
yes it was successful but  the widget is not showing and i have added it i
want the steps you followed to show this widget
