### ISSUE TITLE
[bug] notification not working

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#14052]
Notification content is messed up..

Have tested on https://gitdeveloper.yetiforce.com/ and when assigning a project task to another user.. the system gives a strange error ..can anyone please help..

normal behaviour:  its should give proper notification with changes link and module name 

![image](https://user-images.githubusercontent.com/54880467/104811898-a083ef00-5824-11eb-878f-ebcd6da2882b.png)

**Comment by fbojan** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/12031

**Comment by rioshaz** [comment]
@fbojan what point r u trying to make ?
 your comment doesnt solve the bug... its a system-generated notification.. you cant find it in workflows...

**Comment by mariuszkrzaczkowski** [comment]
https://user-images.githubusercontent.com/10198654/104893415-b18f4600-5973-11eb-8506-3fa662c068e3.mp4

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski yes i know i can create a custom notification... but why do i need to create a workflow when this (project task notification) is a system notification.?

also workflows get executed after a fix interval of time but notifications are instant.... so i cant understand what are you trying to say here...

i dont know what more info you need here sir..

i have tested this on gitdeveloper and its very basic ....just create a project task and assign it to a user but the user gets notification with code... rather he should get it with content and link.. simple it is..

pls help..

**Comment by rioshaz** [comment]
can u please tell me how to fix this problem.. its very urgent sir...

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski @fbojan @prabhu @vctrin any solution guys ?

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski any help sir.... even if i create a wf for this notification then  this system notification comes.. so how can i disable it if we cant fix it.. pls help..

**Comment by Andr198** [comment]
If add $(record : CrmDetailViewURL)$ 
We get a non-clickable link
![n](https://user-images.githubusercontent.com/62097187/106761488-8aa46580-663d-11eb-9680-14f977e6c0a8.JPG)

**Comment by konadrian** [comment]
@rioshaz The problem no longer exists. The ticket has been closed.

@Andr198 you need put the variable into <a> tag
![image](https://user-images.githubusercontent.com/3193498/183629362-5b921a82-4b03-47a9-854e-df1b17c954f7.png)
![image](https://user-images.githubusercontent.com/3193498/183629621-15de444a-32a4-453e-9af9-179ff81a005e.png)
