### ISSUE TITLE
[bug] Entered Invalid Phone Number

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14068]
# 🐞 bug report

### ⁉️ Describe the bug
I am facing issue on my installation. I check this on gitdeveloper, but has same issue. I am trying to put phone number of account in primary phone field +88029822217 same is treated as Invalid. Not able to figure out what is the problem. 

![image](https://user-images.githubusercontent.com/12723595/105007056-808b4000-5a5d-11eb-8422-c52469b9bfdc.png)

![image](https://user-images.githubusercontent.com/12723595/105007082-8da82f00-5a5d-11eb-9858-a88fbf46af11.png)

![image](https://user-images.githubusercontent.com/12723595/105007130-9c8ee180-5a5d-11eb-9537-481566a06d0d.png)

Kindly assist.

Warm Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/giggsey/libphonenumber-for-php/issues/424#issuecomment-762701546

Google's demo also returns false for this number: https://libphonenumber.appspot.com/phonenumberparser?number=%2B88029822217&country=BD
