### ISSUE TITLE
[bug] PDF Watermark ignore line breaks inside span

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#14067]
# 🐞 bug report

### ⁉️ Describe the bug

Line breaks ignored inside span

```
<span style="font-size:72px">$(record : subject)$<br />
$(record : subject)$<br />
$(record : subject)$<br />
qqq<br />
qqq<br />
qqq</span>
```

### 👎 Actual Behavior

If subject is `aaa` then watermark returned as

```
aaa aaa aaa qqq qqq qqq
```

### 👍 Expected Behavior

```
aaa
aaa
aaa
qqq
qqq
qqq
```

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3, gitdev 6.1

### ❓ Additional context

If there is no span in watermark: 

```
$(record : subject)$<br />
$(record : subject)$<br />
$(record : subject)$<br />
qqq<br />
qqq<br />
qqq
```
rendering result is correct

```
aaa
aaa
aaa
qqq
qqq
qqq
```

**Comment by z0lo13** [comment]
@vovpff 
You have the wrong HTML.
span is an inline tag, it usually should not contain line breaks or any children.
Why don't you use simple div?

Just checked and it is working absolutely fine.

```
<div>
    <span style="color:#ff0000; font-size:150px">Line 1</span><br />
    <span style="color:#ff0000; font-size:150px">Line 2</span><br />
    <span style="color:#ff0000; font-size:150px">Line 3</span><br />
    <span style="color:#ff0000; font-size:150px">Line 4</span>
</div>

```

**Comment by vovpff** [comment]
@z0lo13 I tried as absolute stupid guy: Type some data, change font size, press enter, type more and repeat this couple times more.
Thanks for example with div. I will try it.
