### ISSUE TITLE
Upgrade code to higher ver

### ISSUE THREAD

**Issue by wildfox81** [YetiForceCompany/YetiForceCRM#1406]
Dear all,

We have done good amount of work on yeti force 1.4 in the form of modules. We are considering upgrade to a higher version of yeti force, and  we do not want to just copy and paste modules. We want to upgrade the current working version we do have.

What is the best way to do such move? what are the consideration we need to keep in mind?

**Comment by bpabiszczak** [comment]
Please read this: https://yetiforce.com/en/administrator-documentation/updates/176-system-update-not-verified.html

**Comment by wildfox81** [comment]
Thanks for your fast response :) have a great day :)
