### ISSUE TITLE
Error when editing fields  

### ISSUE THREAD

**Issue by samuelsituma** [YetiForceCompany/YetiForceCRM#14083]
I get this error when I try to edit fields in yetiforceCRM v 6.1 what could be the problem.
![CaptuJJKKSre](https://user-images.githubusercontent.com/46498594/105455118-0abce980-5c94-11eb-869c-7fdbba347df6.PNG)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/105456486-86fc0080-5c85-11eb-84a4-b96a605b41b6.jpg)

**Comment by shaunbrittle** [comment]
I am also having a problem with this.

I have setup the system as normal.

PHP Version: 7.3.26
Using XAMPP on Microsoft Edge - Windows

Unsure as to why I am getting this error.

When I click on Standard modules - Edit fields I get the error Call to a member function get() on null.

Any help?

**Comment by mariuszkrzaczkowski** [comment]
insufficient information to solve the problem

**Comment by shaunbrittle** [comment]
Hardly insufficient information. Not exactly a very helpful person!

**Comment by samuelsituma** [comment]
I actually solved it by installing updates check on Logs>updates do all the
necessary updates it might help you as well.

**Comment by mariuszkrzaczkowski** [comment]
Before writing anything please read this https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs

**Comment by mariuszkrzaczkowski** [comment]
I found a similar error see at https://github.com/YetiForceCompany/YetiForceCRM/issues/13859
Install 6.1.0_ServicePack_v5.zip
