### ISSUE TITLE
[Issue] Not able to configure Internal Mail Server in SMTP Configuration

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14080]
Hello,

I am trying to configure my Internal Mail Server (this server can not send email outside). Outlook settings worked with **Safety protocol none** but not working in YF. Error shown is 

ERROR!!!
LBL_NO_EMAIL_TEMPLATE

Screen shot of setting is as below
![image](https://user-images.githubusercontent.com/12723595/105299842-ae4cc200-5be0-11eb-940d-0ddf997ff956.png)

Kindly assist in the matter.

Regards
Jeevan Pendhari

**Comment by rskrzypczak** [comment]
You have deleted the email template that is required to verify the configuration ([link](https://gitdeveloper.yetiforce.com/index.php?module=EmailTemplates&view=List&viewname=105&page=1&orderby=%5B%5D&entityState=Active&search_params=%5B%5B%5B%22name%22%2C%22a%22%2C%22Test%20mail%20about%20the%20mail%20server%20configuration.%22%5D%5D%5D)).
You have to recreate it, but you won't only do it from the GUI level, so if you have the possibility, restore the system from before removing the e-mail templates.

**Comment by JEEVAN28** [comment]
Ohh, Yes your are right. Templates were deleted. Now restored.

Thanks for help
Jeevan Pendhari
