### ISSUE TITLE
Webservice - 401 wrong credentials [bug] 

### ISSUE THREAD

**Issue by kamiro16** [YetiForceCompany/YetiForceCRM#14092]
Hi, 
i have problem with wrong credentials (webservice).
I was created webservice and user. 
Trying to connect http://crm.pl/webservice/user/login
My integration cannot transmit data.

Below have logs:

Webserice debug: 

`-------------  Response  -----  2021-01-22 20:01:21  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Invalid api key
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:01:43  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response Headers -----------
WWW-Authenticate : Basic realm="YetiForceApi"
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Unauthorized
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:01:45  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response Headers -----------
WWW-Authenticate : Basic realm="YetiForceApi"
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Unauthorized
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:01:47  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Invalid api key
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:01:52  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response Headers -----------
WWW-Authenticate : Basic realm="YetiForceApi"
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Unauthorized
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:02:01  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Invalid api key
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:02:31  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response Headers -----------
WWW-Authenticate : Basic realm="YetiForceApi"
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Unauthorized
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:03:31  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response Headers -----------
WWW-Authenticate : Basic realm="YetiForceApi"
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Unauthorized
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:06:16  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response Headers -----------
WWW-Authenticate : Basic realm="YetiForceApi"
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Wrong Credentials
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:06:21  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response Headers -----------
WWW-Authenticate : Basic realm="YetiForceApi"
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Wrong Credentials
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:06:26  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Invalid api key
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:07:37  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response Headers -----------
WWW-Authenticate : Basic realm="YetiForceApi"
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Unauthorized
            [code] => 401
        )

)

-------------  Response  -----  2021-01-22 20:07:41  ------
Status: 401
REQUEST_METHOD: GET
REQUEST_URI: /webservice/user/login
QUERY_STRING: module=user&action=login
PATH_INFO: 
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Invalid api key
            [code] => 401
        )

)

`

Webserice error: 

`============ Error exception ====== 2021-01-22 20:01:21 ======
code: 401 | message: Invalid api key
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php (68)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#1 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-language: pl,en-US;q=0.7,en;q=0.3
accept-encoding: gzip, deflate
authorization: Basic Zm9ybXVsYXJ6OkthbWlybzE2IQ==
connection: keep-alive
cookie: language=en_US; YTSID=95c0b4d4556ea1e796f51fca77ac9493
upgrade-insecure-requests: 1
============ Request data : 

============ Error exception ====== 2021-01-22 20:01:43 ======
code: 401 | message: Unauthorized
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth/Basic.php (18)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth.php(22): Api\Core\Auth\Basic->authenticate('YetiForceApi')
#1 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php(58): Api\Core\Auth::init(Object(Api\Controller))
#2 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#3 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:01:45 ======
code: 401 | message: Unauthorized
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth/Basic.php (18)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth.php(22): Api\Core\Auth\Basic->authenticate('YetiForceApi')
#1 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php(58): Api\Core\Auth::init(Object(Api\Controller))
#2 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#3 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
cache-control: max-age=0
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:01:47 ======
code: 401 | message: Invalid api key
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php (68)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#1 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
cache-control: max-age=0
authorization: Basic dGVzdDp0ZXN0
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:01:52 ======
code: 401 | message: Unauthorized
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth/Basic.php (18)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth.php(22): Api\Core\Auth\Basic->authenticate('YetiForceApi')
#1 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php(58): Api\Core\Auth::init(Object(Api\Controller))
#2 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#3 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
cache-control: max-age=0
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:02:01 ======
code: 401 | message: Invalid api key
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php (68)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#1 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
cache-control: max-age=0
authorization: Basic dGVzdDp0ZXN0
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:02:31 ======
code: 401 | message: Unauthorized
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth/Basic.php (18)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth.php(22): Api\Core\Auth\Basic->authenticate('YetiForceApi')
#1 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php(58): Api\Core\Auth::init(Object(Api\Controller))
#2 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#3 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
cache-control: max-age=0
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:03:31 ======
code: 401 | message: Unauthorized
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth/Basic.php (18)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth.php(22): Api\Core\Auth\Basic->authenticate('YetiForceApi')
#1 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php(58): Api\Core\Auth::init(Object(Api\Controller))
#2 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#3 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
cache-control: max-age=0
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:06:16 ======
code: 401 | message: Wrong Credentials
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth/Basic.php (22)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth.php(22): Api\Core\Auth\Basic->authenticate('YetiForceApi')
#1 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php(58): Api\Core\Auth::init(Object(Api\Controller))
#2 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#3 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
cache-control: max-age=0
authorization: Basic YW50cmFuc19rYW1pbDpUamQ5VHIwZzZ1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:06:21 ======
code: 401 | message: Wrong Credentials
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth/Basic.php (22)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth.php(22): Api\Core\Auth\Basic->authenticate('YetiForceApi')
#1 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php(58): Api\Core\Auth::init(Object(Api\Controller))
#2 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#3 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
cache-control: max-age=0
authorization: Basic YW50cmFuc19rYW1pbDpUamQ5VHIwZzZ1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:06:26 ======
code: 401 | message: Invalid api key
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php (68)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#1 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
connection: keep-alive
cache-control: max-age=0
authorization: Basic dGVzdDp0ZXN0
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate
accept-language: pl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
============ Request data : 

============ Error exception ====== 2021-01-22 20:07:37 ======
code: 401 | message: Unauthorized
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth/Basic.php (18)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Core/Auth.php(22): Api\Core\Auth\Basic->authenticate('YetiForceApi')
#1 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php(58): Api\Core\Auth::init(Object(Api\Controller))
#2 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#3 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-language: pl,en-US;q=0.7,en;q=0.3
accept-encoding: gzip, deflate
connection: keep-alive
cookie: _ga=GA1.2.1205015490.1594216331
upgrade-insecure-requests: 1
============ Request data : 

============ Error exception ====== 2021-01-22 20:07:41 ======
code: 401 | message: Invalid api key
file: /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/api/webservice/Controller.php (68)
============ stacktrace: 
#0 /home/antrans/domains/antransinvest.stronazen.pl/public_html/kamil/webservice.php(13): Api\Controller->preProcess()
#1 {main}
============ Headers: 
REQUEST_METHOD : GET
host: kamil.antransinvest.stronazen.pl
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-language: pl,en-US;q=0.7,en;q=0.3
accept-encoding: gzip, deflate
connection: keep-alive
cookie: _ga=GA1.2.1205015490.1594216331
upgrade-insecure-requests: 1
authorization: Basic dGVzdDp0ZXN0
============ Request data : 

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3.0
| PHP                                 |   7.2.34        |
| Browser (name and version)       mozilla firefox   |                |
| Operating System (name and version) |  windows 10              |

**Comment by mariuszkrzaczkowski** [comment]
01-22 20:02:01 ======
code: 401 | message: Invalid api key

I recommend updating to the latest version

![github](https://user-images.githubusercontent.com/10198654/105630758-43eb8a00-5e4b-11eb-855c-b55382533b76.jpg)
