### ISSUE TITLE
Social Cron

### ISSUE THREAD

**Issue by MikeP1990** [YetiForceCompany/YetiForceCRM#14093]
![Screenshot_1](https://user-images.githubusercontent.com/1528466/105637486-b36e7300-5e65-11eb-9ad7-37d664bea7b0.png)

Hello,

I've searched high and low but can't seem to find anything, maybe I've missed something?

How does one enable the social cron?

Thanks!

**Comment by davide-alghi** [comment]
Hi @MikeP1990, (_please next time post in Discussions section_)
you have to enable required CRON tasks

![Schermata da 2021-01-25 16-11-39](https://user-images.githubusercontent.com/48508691/105724749-7cad6100-5f28-11eb-98e2-01446db8b22a.png)
