### ISSUE TITLE
Moduł Haseł.Niepoprawna wartość

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#1409]
W module hasła w pole adres www nie można wpisać wartości np:
https://serwer01:2222/test/
https://serwer01/era/
czy można zmienić maskę dla tego pola tak aby można wpisywać powyższe adresy url.

![password](https://cloud.githubusercontent.com/assets/10506580/8564601/07d380ae-254e-11e5-8b6e-2a01d01790fe.PNG)

**Comment by MaciejStencel** [comment]
Walidacja była ustawiona na zwykłe domeny, także sprawdzało np. czy jest subdomena i domena. W przykładach powyżej występowała tylko domena więc nie przechodziło walidacji.

Zmieniono walidację tak by przechodziły również inaczej zbudowane domeny, jeśli podstawa nie przejdzie to sprawdza czy tekst rozpoczyna się od "http://", "https://" lub "www.".

https://github.com/YetiForceCompany/YetiForceCRM/commit/a6ee4317cc30216960cb136797cdb4816435354d
