### ISSUE TITLE
unable to mass add document to module[bug] 

### ISSUE THREAD

**Issue by lelethered** [YetiForceCompany/YetiForceCRM#14108]
dear all,
we have implemented some module with same functionality of incoming and outcoming correspondence. We related Document module with our new ones, creating 1:m relation field in document module versus the new module.
The single "add document" functionality work great, but the "Mass Add Document" never add the document to module

Steps to reproduce the behavior single add document:
1. Go to 'Document'
2. Click on 'Add Document'
3. select document
4. All ok
<img width="1739" alt="Schermata 2021-01-27 alle 11 09 29" src="https://user-images.githubusercontent.com/29478429/105978883-4f30f680-6093-11eb-87a5-832289309dbb.png">

<img width="1739" alt="Schermata 2021-01-27 alle 11 16 21" src="https://user-images.githubusercontent.com/29478429/105976978-20b21c00-6091-11eb-8176-235f85fbbb4e.png">

Steps to reproduce the behavior mass add document:
1. Go to 'Document'
2. Click on 'Mass Add Document'
3. select document
4. Nothing appears under documents tab, but the file are present in Document list as "orphan"
<img width="1739" alt="Schermata 2021-01-27 alle 11 08 33" src="https://user-images.githubusercontent.com/29478429/105977006-2c054780-6091-11eb-8070-d4a897f32db2.png">
<img width="1739" alt="Schermata 2021-01-27 alle 11 17 27" src="https://user-images.githubusercontent.com/29478429/105977107-46d7bc00-6091-11eb-8412-731cc49dd768.png">

| YetiForce                           | 5.1.0
| Web server (name and version)       |      Linux yf 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64          
| PHP                                 |    7.2            |
| Operating System (name and version) |       nginx/1.10.3
| Database (name and version)         |      5.5.5-10.2.18-MariaDB-10.2.18+maria~stretch

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/105979870-750acb00-6094-11eb-8941-00422c1553db.jpg)

**Comment by lelethered** [comment]
Excuse me, i describe the issue, is not reproducible in gistable since are new modules. The functionality of document single is ok the problem is on mass add.
Our server and service is directly on yetiforce hosting, do you need more info related wich number (1 to 8)?

**Comment by mariuszkrzaczkowski** [comment]
If you have our hosting/cloud, bugs are reported to the e-mail (sla@yetiforce.com) and they are resolved in a different order.
We don't know who from GitHub is in our infrastructure.
The required information was not attached, therefore it was closed.

**Comment by lelethered** [comment]
ok thank's i send email
best regards
