### ISSUE TITLE
Outsourced Products. Share with users

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1412]
I want to adding two share users (test and admin) after save the record show only test user
![before](https://cloud.githubusercontent.com/assets/3193498/8565541/da9a25da-2556-11e5-9574-9b01a3d7a2ca.png)
After saved
![after](https://cloud.githubusercontent.com/assets/3193498/8565561/0289f1e2-2557-11e5-9e28-7cd0f080ccec.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/3bf13d7f6d803c5c8fdde22a4b020cdb1f67c0b3
