### ISSUE TITLE
[PL] Podczas edycji szablonu PDF (faktura) nie ładuje się strona w pełni, brak połowy kolumn i pola next i cacnel[bug] 

### ISSUE THREAD

**Issue by pavioja** [YetiForceCompany/YetiForceCRM#14140]
# 🐞 bug report

### ⁉️ Describe the bug

Podczas próby edycji szablonu pdf faktury sprzedaży i każdej innej, strona nie ładuje się do końca. Brak jest większości pół oraz pól next i cancel. Nie istnieje możliwosć poprawiania/tworzenia szablonów. Funkcjonalność ta działał jak najbardziej poprawnie w tym samym środowisku, w którym nie dokonałem żadnych zmian.

![ot from 2021-01-30 19-25-34](https://user-images.githubusercontent.com/78273936/106364656-f8e0e380-6330-11eb-9c39-f9fa03557f5a.png)

### 🔥 How to trigger the error

1. Go to 'Strona główna-Konfiguracja systemu-Narzędzia systemowe-PDF-Konfiguracja systemu' 
2. Click on 'edytuj (długopis) przy wybranej fakturze'
3. strona niepoprawnie się ładuje, brak możliwości dalszych akcji. 

### 👎 Actual Behavior

strona niepoprawnie się ładuje, brak możliwości dalszych akcji. 

### 👍 Expected Behavior

strona w pełni załadowana z "przyciskami" next i cancel

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

|

**Comment by rskrzypczak** [comment]
Błąd nie występuje w aktualnej wersji deweloperskiej oraz ostatniej stabilnej, więc zamykam.
Jeżeli wg Ciebie błąd nadal występuje, otwórz nowe zgłoszenie z pełnym opisem zjawiska.
