### ISSUE TITLE
Brak wymaganego pola NIP, brak walidacji NIP

### ISSUE THREAD

**Issue by MarZdanSoft** [YetiForceCompany/YetiForceCRM#14154]
Dzień dobry,
Mam (chyba) prawidłowo skonfigurowane pole NIP i wymóg walidacji ale po przejściu w "panel użytkownika" pole NIP jest nie widoczne i nie ma walidacji "Duplikuj NIP". 
Tydzień temu działało ale w między czasie była aktualizacja systemu, aktywacja modułów GUS i Outlook i ja też dokonfigurowywałem aplikację ale tylko z poziomu administratora (bez grzebania w kodzie). Proszę o pomoc 

Aktualne ustawienia:

![Zrzut ekranu 2021-02-02 131357](https://user-images.githubusercontent.com/78420211/106598847-966a2c00-6558-11eb-9278-f090bf337e31.png)

![image](https://user-images.githubusercontent.com/78420211/106598920-b00b7380-6558-11eb-8471-d978d6a42829.png)

![image](https://user-images.githubusercontent.com/78420211/106599060-d7fad700-6558-11eb-8e94-415a76f988d5.png)

i efekt:

![image](https://user-images.githubusercontent.com/78420211/106599797-daa9fc00-6559-11eb-9df6-1a0e4cb954d3.png)

**Comment by mariuszkrzaczkowski** [comment]
Pokaż konfigurację 
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=FieldsDependency&view=List

**Comment by MarZdanSoft** [comment]
Przyznaje że nie bardzo rozumiem, link prowadzi do strony demo, jak mam pokazać konfigurację?

**Comment by MarZdanSoft** [comment]
Porównałem możliwości edycji i są różnice, u mnie nie ma ustawiń "systemowe" "typ pola" i "anonimizacja"

![image](https://user-images.githubusercontent.com/78420211/106602108-d3382200-655c-11eb-83c1-9e7284edcfa6.png)

**Comment by rskrzypczak** [comment]
Nie podałeś jaką masz wersję aplikacji.
Niemniej sprawdź uprawnienia do pola w profilach.
.. a może masz dodane jakieś warunki w panelu _Pola zależne_ (o ile go posiadasz).
Trudo tu cokolwiek stwierdzić, coś musiałeś namieszać, bo pola same z siebie nie znikają :P

**Comment by MarZdanSoft** [comment]
Wersja systemu aktualna YetiForce CRM 6.1 Service Pack v6
Posprawdzam jeszcze raz uprawnienia / zależności 

Dziękuje za pomoc

**Comment by MarZdanSoft** [comment]
Faktycznie miałem wprowadzone warunki jak niżej, po ich usunięciu pole NIP wróciło :)
![image](https://user-images.githubusercontent.com/78420211/106617868-45b1fd80-656f-11eb-841c-f079cf66af25.png)

Walidacja działa wyłącznie dla "Kontrahenci" ale dla pozostałych modułów np "Leady" już nie, jak ustawić ograniczenie dla jednego nr NIP dla wszystkich rekordów w systemie?

**Comment by rskrzypczak** [comment]
Zgłoszeń używaj tylko dla błędów aplikacji, wszystko inne do dyskusji https://github.com/YetiForceCompany/YetiForceCRM/issues/13908

>jak ustawić ograniczenie dla jednego nr NIP dla wszystkich rekordów w systemie?

   Nie ustawisz tego z poziomu  GUI, musiałbyś napisać własne funkcje walidujące.
