### ISSUE TITLE
[bug] Vulnerability check fails

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#14157]
# 🐞 bug report

### ⁉️ Describe the bug

Vulnerability check no longer works:

![image](https://user-images.githubusercontent.com/10230144/106644893-fc23db80-658b-11eb-81fb-2b62d0051146.jpeg)

![image](https://user-images.githubusercontent.com/10230144/106644917-01812600-658c-11eb-8ef3-d3988aa3937e.jpeg)

### 🔥 How to trigger the error

1. Go to 'vulnerability' as administratir
2. See error

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment]
we know it, we are working on it

**Comment by mariuszkrzaczkowski** [comment]
Fixed, just replace this file
https://github.com/YetiForceCompany/YetiForceCRM/commit/94101388a9e2a33f28a455cef2ca7cd461d9445b
