### ISSUE TITLE
Homepage Widgets from filter - Edit, change size, save

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1415]
Currently we have no option to edit or even change size of widget added direcly from home page.

Mabye posibility to change size of every widget (form home and definied by adminstrator) will be good idea - then different employes can have different home page arrangement (as they wish).

other future could be widget with auto-refresh (ex. after 5, 30 sec.) - user will be up to date with their work (when is assigned by other user) and there is no need to remember to check/refresh dashboard.

**Comment by bpabiszczak** [comment]
Elements that require refreshing in the background [notifications, new mail] are refreshed every couple of seconds. Refreshing widgets all the time seems redundant and unnecessary. It would require a completely new approach to the desktop. At the moment we are not planning to implement these changes.

Currently, the possibilities of adjusting the main screen are great [I don't think any other system I happened to use before had these possibilities]. We are working on the responsiveness now, which will solve many issues connected to different screens. The offered solution isn't wrong, but we won't have the time for it for the next few months, it is of too low priority for us. Although, if there's someone who adds that functionality then I'm open to suggestions.
