### ISSUE TITLE
[bug] caldav sync wrong time

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#14165]
hello guys,
syncing with caldav sync's wrong "event time" in the mobile calender.

On the CRM is shows 11.55 am but on the mobile calendar, it shows 17.25 and so on..

all events are 4 & a half hours ahead on mobile.. i have checked time zone on both crm and mobile is same .. does the time of server on which yetiforce is installed also matters.

does anyone know whats the issue..

i am using opensync app on mobile to connect to caldav server .

pls help...

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/106813304-18e60f00-6671-11eb-81b6-828ba86aa2d8.jpg)
