### ISSUE TITLE
[bug] when create a record and i have set a workflow->creating record

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#14184]
Oh hi company !!

The bug concerns the workflow and creating a record. I get error on versions 5.2, 5.3, 6.1
It was working fine from 5.1 and before 

I have tested it on gitdeveloper and gitstable.

🔥 How to trigger the error:

![YF bug](https://user-images.githubusercontent.com/50912403/106995523-c3505600-6787-11eb-95ab-50e09e88946b.gif)

The same on gitstable with this error
![εικόνα](https://user-images.githubusercontent.com/50912403/106994339-3906f280-6785-11eb-86da-9e2041df3715.png)

I get the error: Argument 1 passed to App\User::isExists() must be of the type int, null given, called in /home/gitstable/domains/gitstable.yetiforce.com/public_html/modules/com_vtiger_workflow/tasks/VTCreateTodoTask.php on line 118

👍 Expected Behavior
it must create 3 events when we create an account.

**Comment by rskrzypczak** [comment]
This is not entirely a bug.
You have the wrong user option set.
anyway.. this option will no longer appear.
![image](https://user-images.githubusercontent.com/10221999/106998917-900cc780-6785-11eb-907e-33311b9116b7.png)

**Comment by Giorgos-Hellene** [comment]
@rskrzypczak Thank you for your quick response !

so if i change the value of Assigned to administrator it will be ok ?

**Comment by rskrzypczak** [comment]
It should be ok.
