### ISSUE TITLE
Email blocked by rbl-block.yetiforce.com (in reply to RCPT TO command)

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#14181]
Gents, customer reported as follows: Email blocked by rbl-block.yetiforce.com (in reply to RCPT TO command)
Looks like you need take care of email server. Email from legit domain, with perfect spam score.

**Comment by mariuszkrzaczkowski** [comment]
https://soc.yetiforce.com/

**Comment by waran70** [comment]
So, you want me to pay 5 Euro to send you message?  Just to let you know, I was responding to Paulina Walenczak and this is what she wrote to me:

------
Hi Ian,

Thanks for getting in touch with us.

Could you please provide us with some more details about the implementation? Do you want us to implement a new PDF library?

Thank you.
--------


![image](https://user-images.githubusercontent.com/6852348/107003700-c6ffcf00-67bf-11eb-8352-41353e95f183.png)

**Comment by waran70** [comment]
And hell, why it blocked me? I am trying to feed you guys with money, and got wiped ass... not good at all

**Comment by bpabiszczak** [comment]
write here the IP address from which the email came out.

**Comment by bpabiszczak** [comment]
We block for spam. If you don't write your IP address, I can't help you.

**Comment by waran70** [comment]
I don't think it would be wise to share email server IP here. Anyway no worries, got help from toptal. Maybe next time more luck. Cheers!

**Comment by bpabiszczak** [comment]
You can send information to this email address: b.pabiszczak@soc.yetiforce.com

PS: Maybe you can outsource all your questions / problems to toptal, if it's so good there?
