### ISSUE TITLE
[bug] CSV import

### ISSUE THREAD

**Issue by pietervanpta** [YetiForceCompany/YetiForceCRM#14199]
# 🐞 bug report

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by pietervanpta** [comment]
.

**Comment by deepti4666** [comment]
CSV import is not importing all the items, on either products, accounts, or vendors

**Comment by mariuszkrzaczkowski** [comment]
give sample file, more details.  what you wrote does not help others
