### ISSUE TITLE
[bug] CSV import check for existing fields not working

### ISSUE THREAD

**Issue by pietervanpta** [YetiForceCompany/YetiForceCRM#14200]
Recently updated to latest release (6.1).  While trying to update records using a .csv file it seems that Yeiforce is not detecting that the record already exists.  A new record is created does not matter if i tell Yeti to skip if exist on a certain field.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/108026001-cbca4b80-7027-11eb-9e3d-e6bc14ce0748.jpg)
