### ISSUE TITLE
[bug] Round Cube installation and configuration error

### ISSUE THREAD

**Issue by drakub** [YetiForceCompany/YetiForceCRM#14210]
Hi, Yetiforce team,

I could not download and install round cube  library in my local Yetiforce installation from the Standard Modules -> Module Installation section. When I tried it on the **gitstable** version, the same behavior persists. After a long work around, I manually downloaded it and uploaded it to /public_html/modules/OSSMail folder. But when I go to the Module Installation page and click on **update**, nothing happens - the library does not get updated. Can someone help me on this.

###  How to trigger the error

1. Go to 'settings/standard modules/module installation'
2. Click on 'download round cube or update round cube'

### Actual Behavior
When I click on the download or update button, nothing happens.

** Behavior on gitdeveloper **
![Screenshot (12)](https://user-images.githubusercontent.com/19745222/107199238-39162500-6a07-11eb-86db-bdf715c8c9f3.png)

** Behavior on gitstable **
![Screenshot (14)](https://user-images.githubusercontent.com/19745222/107199362-5fd45b80-6a07-11eb-9f70-e0efecd43df0.png)

** Behavior Local Installation **
![Screenshot (15)](https://user-images.githubusercontent.com/19745222/107199497-8eeacd00-6a07-11eb-8933-4f42d1ec703f.png)

### 👍 Expected Behavior
library status to change to downloaded or updated

### 👷 Testing

- [ ✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
![Screenshot (16)](https://user-images.githubusercontent.com/19745222/107199792-e5f0a200-6a07-11eb-9c78-d74343538c62.png)
![Screenshot (17)](https://user-images.githubusercontent.com/19745222/107199794-e721cf00-6a07-11eb-80f3-5912a0fbdd62.png)
![Screenshot (18)](https://user-images.githubusercontent.com/19745222/107199796-e7ba6580-6a07-11eb-97a7-40292f50bc00.png)
![Screenshot (19)](https://user-images.githubusercontent.com/19745222/107199798-e7ba6580-6a07-11eb-8cd3-987904768068.png)
![Screenshot (20)](https://user-images.githubusercontent.com/19745222/107199800-e852fc00-6a07-11eb-9e9e-137fe838ad65.png)
![Screenshot (21)](https://user-images.githubusercontent.com/19745222/107199802-e8eb9280-6a07-11eb-9aec-e35aacbf53b3.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.0.1
| Web server (name and version)       |     Apache           |
| PHP                                 |     7.3.1           |
| Browser (name and version)          |     Mozilla Fire Fox           |
| Operating System (name and version) |     Windows 10, Enterprise           |
| Database (name and version)         |      MariaDB          |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
You need to correct your server configuration, then I suppose the error should no longer occur.

**Comment by drakub** [comment]
> 
> 
> You need to correct your server configuration, then I suppose the error should no longer occur.

Which configuration exactly?

**Comment by simple-AMS** [comment]
@job-bob-draku You need root access to your server installation and you need to adjust your PHP settings as well as YetiForce User.ini files on main application path and public_html and correct all of the highlighted issues. You also need to adjust your mysql configuration file. That is why you're having issues.

**Comment by drakub** [comment]
Let me try this out and let you know

**Comment by drakub** [comment]
@mariuszkrzaczkowski why do you close the issue when its not confirmed resolved?

**Comment by mariuszkrzaczkowski** [comment]
Because your server has not been properly configured

**Comment by drakub** [comment]
> 
> 
> Because your server has not been properly configured

I have now corrected all the server issues. Everything is okay. I can now download the round cube library but I cannot update it. In addition, I also get this error on the server configuration page

![image](https://user-images.githubusercontent.com/19745222/107509195-39532380-6bb3-11eb-8472-d5bd609e7e84.png)
