### ISSUE TITLE
Dynamic fields not working

### ISSUE THREAD

**Issue by samuelsituma** [YetiForceCompany/YetiForceCRM#14221]
I have created a dynamic field for the sales invoices module but it's not working and the one for the account module works well what could be the issue.

This one for the sales invoices not working
![Casadpture](https://user-images.githubusercontent.com/46498594/107342388-3253e480-6ad1-11eb-93b3-4d4d6301d847.PNG)

the one for accounts working well
![Csdddapture](https://user-images.githubusercontent.com/46498594/107342639-819a1500-6ad1-11eb-8a57-4e9e5473b863.PNG)

**Comment by konadrian** [comment]
Please try this 
https://github.com/YetiForceCompany/YetiForceCRM/commit/56cf4992d6f4512855aae0b6b6989b46696a9567

**Comment by samuelsituma** [comment]
Thank you so much for the response I have tried it still getting the same
problem

**Comment by rskrzypczak** [comment]
Disable loading min.js files in config/Developer.php
`public static $MINIMIZE_JS = false;`

**Comment by samuelsituma** [comment]
Thanks I have disabled but still not solving the problem
