### ISSUE TITLE
server change

### ISSUE THREAD

**Issue by MixTecnico** [YetiForceCompany/YetiForceCRM#14236]
query change server, everything is fine ... but I have some example errors when deleting multiple records, and navigating between different records, etc ...

I do not have an error log, did you open any way to solve it?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/107987971-529f0a00-6fcf-11eb-9d9c-d5327405e4dc.jpg)

**Comment by MixTecnico** [comment]
It is not an error, it seems to me a migration problem which would be the correct way to migrate to another server
