### ISSUE TITLE
[bug] SMTP ERROR: Password command failed: 534-5.7.14 534-5.7.14 Please log in via your web browser and then try again. 

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#14235]
basically in perfect configuration cannot get gmail working. Wondering if I missed something. 
Cannot check in dev version as will not expose my password there.
Any clue or settings advice?

**Comment by apcloic** [comment]
@waran70 This is not a YF bug, you have to check/review [Gmail configuration](https://www.google.com/search?q=534-5.7.14+534-5.7.14+Please+log+in+via+your+web+browser+and+then+try+again&oq=534-5.7.14+534-5.7.14+Please+log+in+via+your+web+browser+and+then+try+again&aqs=chrome..69i57j69i61l2.489j0j7).

Enable 2FA and create application password then it should work.
Regards,
