### ISSUE TITLE
YetiForce Portal2 Installation

### ISSUE THREAD

**Issue by myanesdiazl9** [YetiForceCompany/YetiForceCRM#14237]
YetiForce Portal 2 failed to install. I appreciate any help you can give me 
![Screenshot from 2021-02-15 19-51-19](https://user-images.githubusercontent.com/68311999/108004056-14075080-6fcb-11eb-866a-4520504b63a5.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13870#issuecomment-738006519
