### ISSUE TITLE
How to Change column Text (<td>) while report Finvoice PDF

### ISSUE THREAD

**Issue by eissaweb** [YetiForceCompany/YetiForceCRM#14242]
Hi,

I want to edit the text of table columns while exporting Foinvoice into PDF.

the reason is: I want it to support Arabic, and I found the solution to make the text looks as expected, but I didn't no where to Change the columns name, like layout.tpl or something.. 

![image](https://user-images.githubusercontent.com/50566718/108063447-e6bab100-7063-11eb-871a-1ad4522aa390.png)

I just want to know where in the code these Column set.

I'm a PHP developer btw, so my issue is Iam new to this Great CRM.

Thanks.

**Comment by mariuszkrzaczkowski** [comment]
You can find all the translations in this file languages : 
languages/en-US/Other/PDF.json
https://github.com/YetiForceCompany/YetiForceCRM/blob/ab0807f6006f30ab47fcb9df70d37856cc16fbb7/languages/en-US/Other/PDF.json#L28
languages/en-US/_Base.json
https://github.com/YetiForceCompany/YetiForceCRM/blob/1ac3c53c17a8951a7861e36d2529b0054d5a6f2c/languages/en-US/_Base.json#L1005

You only have to add it in the file for your language and it's best to add it in crowdin
https://crowdin.com/project/yetiforcecrm/ar


https://crowdin.com/translate/yetiforcecrm/all/en-ar?filter=basic&value=0#q=LBL_UNIT_PRICE
https://crowdin.com/translate/yetiforcecrm/all/en-ar?filter=basic&value=0#q=LBL_SALE_DATE
https://crowdin.com/translate/yetiforcecrm/all/en-ar?filter=basic&value=0#q=FL_PAYMENT_DATE
https://crowdin.com/translate/yetiforcecrm/all/en-ar?filter=basic&value=0#q=Quantity

The added changes will only be visible when the language pack is generated in https://github.com/YetiForceCompany/YetiForceCRMLanguages

**Comment by eissaweb** [comment]
Thank you very much. it helped.

**Comment by iweb123** [comment]
it looks like it does not show Arabic words correctly after exporting to PDF @eissaweb @mariuszkrzaczkowski

**Comment by iweb123** [comment]
I think we should change the encoding of page which will be exported in PDF and the font family too
check this please I think we need to change this to export Arabic PDF correctly 
https://drive.google.com/file/d/1yob8bZeBnlotnvYWReIorM33E_tL7FVU/view?usp=sharing

**Comment by mariuszkrzaczkowski** [comment]
> it looks like it does not show Arabic words correctly after exporting to PDF @eissaweb @mariuszkrzaczkowski

> I think we should change the encoding of page which will be exported in PDF and the font family too
> check this please I think we need to change this to export Arabic PDF correctly
> https://drive.google.com/file/d/1yob8bZeBnlotnvYWReIorM33E_tL7FVU/view?usp=sharing

new problem, new issue

**Comment by iweb123** [comment]
Ok
Thanks
