### ISSUE TITLE
Documents. Sending file as attachment

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1424]
Don't add file as an attachment
![button](https://cloud.githubusercontent.com/assets/3193498/8592805/872f6568-2632-11e5-9df5-f6d5f4a7bb69.png)

![compose](https://cloud.githubusercontent.com/assets/3193498/8592821/a0a541ac-2632-11e5-8617-3365d0a6857a.png)

**Comment by bpabiszczak** [comment]
Work with new pdf module. 
https://pdf.yetiforce.com/ [admin/admin]
