### ISSUE TITLE
Mapping new supplier in new leads

### ISSUE THREAD

**Issue by gsportelli73** [YetiForceCompany/YetiForceCRM#14241]
Hello, 
i have a question, i have created a map between supplier and lead.
I want to create new leads when i create new supplier into CRM.
I have create the mapping match. Watch video 
[https://youtu.be/IV2nQ9q55Rg](url)

Now i think that is correct.
But it doesn't function.
For me best solution was create a workflow that when i create new supplier, it automatically creates new lead. 
This is important for passive cycle of my company, because sometime it must order a product or service for it.
Thank for attention

**Comment by apcloic** [comment]
@gsportelli73
Hi, 
Check if all required fields are mapped, including "assigned to" field otherwise it won't work. 

For this kind of issue, plz post your question in discussions section. 
#13908

Regards,
