### ISSUE TITLE
[bug] Email templatess stripped of hyperlinks

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#14263]
Email templates being stripped of any hyperlinks upon saving. This also make impossible to 
include basic html buttons etc. I should call it bug rather than limitation

Easy to test on dev and stable versions.

It should be allowed to get admins this flexibility of calling for instance scripts from emails templates.
If there is way around (instead of fixing it as a bug) I (and community I believe) will appreciate to learn how.

- [ X ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ X ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by mariuszkrzaczkowski** [comment]
Set domains in configuration will work
https://github.com/YetiForceCompany/YetiForceCRM/blob/2fbdbdc60dcb993246ef81ff507d7524286a646e/config/Security.php#L176-L177

**Comment by waran70** [comment]
did with localhost and IP and not working. Is TLD  mandatory? Can it be tricked somehow?

**Comment by rskrzypczak** [comment]
`public static $purifierAllowedDomains = false;`

**Comment by waran70** [comment]
Thanks Radek, 
How to allow  this?: `<button type="button" onclick="alert('You pressed the button!')">Click me!</button>`

**Comment by JohnMaverick** [comment]
Hyper links and formatting in emails sent via workflows never has been fixed. Not sure v.7 but here we come to mess. Once yeti release new version there is NO support for previous. I wish it is as per Ubuntu models or so...
