### ISSUE TITLE
Change in Basic Color

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14270]
I am trying to edit basic colors, I tried with https://github.com/YetiForceCompany/YetiForceCRM/issues/13264 but no luck.

I have modified below files
public_html/layouts/basic/styles/_Variables.scss 

$bg-navbar: #2A67B2; // #4a5364;

did cache refresh (Ctrl+Shift+R) but no luck

In config developer Minimize_CSS set to No

not able to get the result.

Please assist.

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
you need to generate a css file, see here
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/public_html/src/gulpfile.js

**Comment by rskrzypczak** [comment]
For simplicity, only modify Main.css file

**Comment by JEEVAN28** [comment]
@rskrzypczak Hi, thanks I am able to change font size but not able to change color, can you please help me to reach exact code to change color

![image](https://user-images.githubusercontent.com/12723595/108816647-8cc66800-75dc-11eb-82f8-3aae65ef9df3.png)

Thanks in advance
Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/108817638-80c8af00-75b8-11eb-916e-b2cfb4d28773.png)
