### ISSUE TITLE
Can some one upload following folder for yetiforce 6.1.0

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#14281]
some how the folder resources at public_html/layouts/basic/modules/Settings/LayoutEditor/resources/
was removed , 
could some one please upload and share link of resources folder @ 
public_html/layouts/basic/modules/Settings/LayoutEditor/resources

**Comment by vovpff** [comment]
Why you can't download it directly from github?
