### ISSUE TITLE
Hi, I just installed Yeti but it seems doesn't work. When i try to enter as administrator the brwoser page ask me to canel cookies. I can not enter[, could someone help me please?

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#14295]
# 🐞 bug report

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/109334870-914f8280-7861-11eb-9d00-038dcbcaec60.jpg)
