### ISSUE TITLE
How do i fix Call to undefined method App\RecordSearch::getSearchField().

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#14290]
the error is shown below :
Call to undefined method App\RecordSearch::getSearchField().

![Screenshot (2)](https://user-images.githubusercontent.com/40380541/109158199-28053c00-779b-11eb-9700-4ad3bc6789db.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/109160921-bca97300-7776-11eb-987d-16e330a476a0.jpg)
