### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by deepti4666** [YetiForceCompany/YetiForceCRM#14291]
# 🐞 bug report

### ⁉️ Describe the bug

Error
Argument 1 passed to App\User::isExists() must be of the type integer, null given, called in /home/boardroo/public_html/crm/modules/com_vtiger_workflow/tasks/VTCreateTodoTask.php on line 118

### 🔥 How to trigger the error

Created a Workflow with ToDo tasks for a new project (trying to create a default list of tasks for a project)

Workflow triggers when Project statues = "Planned"

1. Go to 'Opportunities'
2. Change status to 'Project Started'
3. Error shows, the workflow is not triggered

### 👎 Actual Behavior

Project is created, no tasks/to do's shown on the project

### 👍 Expected Behavior

The project is updated with the list of tasks for the user to follow

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 	YetiForce CRM 6.1 Service Pack v5
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
look at this: https://github.com/YetiForceCompany/YetiForceCRM/issues/14184
if the cause is elsewhere, provide more details.

**Comment by deepti4666** [comment]
Thank you - this worked on removing the error - but it still doesn't create the task for the project
