### ISSUE TITLE
Migration to ubuntu server not working

### ISSUE THREAD

**Issue by samuelsituma** [YetiForceCompany/YetiForceCRM#14300]
Hi I have set up a migrated Yetforce CRM on my ubuntu server the database and the URL in the Main.php file are OK but when I open the browser I get this error
![image](https://user-images.githubusercontent.com/46498594/109410243-0cbc4b80-79aa-11eb-8756-34e2b6f322c8.png)

My Error Logs looks like this
![image](https://user-images.githubusercontent.com/46498594/109410837-e77e0c00-79ae-11eb-80b9-23460993402d.png)

I have installed a fresh Yetiforce CRM and that works fine in this url
http://207.180.199.240/yetiforce/index.php

But we needed to migrate the one we are using now how do I solve this.

**Comment by bpabiszczak** [comment]
The log says you have incorrect file and directory permissions. This is a job for your Linux administrator.
