### ISSUE TITLE
 "Exceeds the maximum text size in bytes 65535".

### ISSUE THREAD

**Issue by rohanjhanepal** [YetiForceCompany/YetiForceCRM#14302]
When adding images on text editors, it returns the message: "Exceeds the maximum text size in bytes 65535".
I also tried uploading image of 2kb

Yetiforce: v6.1.0
service pack 7

CONFIG:

![ConfReport](https://user-images.githubusercontent.com/40380541/109420406-5cc2fe80-79fa-11eb-9da4-542849429cd4.png)

**Comment by rskrzypczak** [comment]
This is not a bug: https://github.com/YetiForceCompany/YetiForceCRM/issues/13597, https://github.com/YetiForceCompany/YetiForceCRM/issues/13002, https://github.com/YetiForceCompany/YetiForceCRM/issues/12946
and fix your configuration.
