### ISSUE TITLE
[bug] Mobile Number + Sign with Country Code is truncated

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14313]
Please refer my earlier issue raised, which was solved but not clear with reason
https://github.com/YetiForceCompany/YetiForceCRM/issues/14075

Now again I am facing same issue.

Please assist in the matter

Regards
Jeevan Pendhari

**Comment by blu-IT** [comment]
HI,

maybe this helps?

https://github.com/YetiForceCompany/YetiForceCRM/issues/13261#issuecomment-653806838

Regards

**Comment by konadrian** [comment]
I closed the ticked due to missing information. The problem no longer exists. The ticket has been closed.
![image](https://user-images.githubusercontent.com/3193498/183639399-617081f4-87d1-486d-a161-b7682f1d54e9.png)
