### ISSUE TITLE
language install error

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1432]
I have outport the language package from the language editor.I import it at another Yetiforce crm,it import successful,but last step,it display such error:
![snip20150709_1](https://cloud.githubusercontent.com/assets/12697896/8596057/980a76fa-267f-11e5-8bc2-20d320e9fe18.jpg)
but the language in fact install success.

**Comment by waw555** [comment]
Set in the English language by default, install the module, set your language.

**Comment by 1250572980** [comment]
I　do as you say,the result is success.

**Comment by 1250572980** [comment]
I　do as you say,the result is success.
