### ISSUE TITLE
[Docker] Synology Server Wrong Session Id

### ISSUE THREAD

**Issue by XavierPPacheco** [YetiForceCompany/YetiForceCRM#14332]
I am trying to install version 6.1.0 of yetiforce using Docker in my Synology NAS. When I click install it immediately displays:
Installation unsuccessful
Wrong session ID.

Exists in server configuration which causes loss of session data.
We recommend removing browser cache, in case it does not help please fix your server configuration.
//
I have already cleared the cache, tried another browser and scattered the web for answers. I have also tried to install version 6.0.0 just to get the same result.
I check the Synology logs and I don't have any errors, Do I need to change any config?
### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |6.1.0
| Web server (name and version)       |                |
| PHP                                 |       7.3         |
| Browser (name and version)          |       Firefox         |
| Operating System (name and version) |     Synology DSM           |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by jlnknz** [comment]
Could it be the same problem as mentioned at point 1 of https://github.com/YetiForceCompany/YetiForceCRM/issues/13917#issuecomment-768743505 ? Do you use a non-standard HTTP port? If so, the quick workaround is to use port 443 if you use HTTPS and 80 if you use HTTP. 

@mariuszkrzaczkowski apparently has already fixed the problem, but it is not released, yet.

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/the-installation-process-has-failed
