### ISSUE TITLE
[bug] Image field - can not delete once uploaded

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#14331]
Created image field, uploaded some pic, saved record, edited record, tried delete this image (so I can replace with another), and.. not working. Checked it out on git dev in Accounts module

**Comment by waran70** [comment]
Also download and preview down

**Comment by TonyM15** [comment]
I confirm that. Also gitstable not allowing for any mouse-over operations.
FF and chrome the same.

**Comment by garryatbrighton** [comment]
Noticed the same in my instance. Both image and multiimage not working

**Comment by rskrzypczak** [comment]
Does this error still occur in demos (gitdev.., gitstable..)?
I tried to reproduce it with no success.

**Comment by garryatbrighton** [comment]
It is still there, try to delete image from Departments. It not allowing... so single image and multi-image fields are not working

**Comment by rskrzypczak** [comment]
I dunno.
Give me more information.
Perhaps the problem is with the file you want to attach, but I don't see a problem with deleting the file itself.
![attachIntro](https://user-images.githubusercontent.com/10221999/113261854-40073880-92d0-11eb-98f3-a0d6bae110d3.gif)

**Comment by garryatbrighton** [comment]
Nope here is not working FF, Chrome, Opera.... cannot make it delete. 
Can someone else confirm status? I checked on 4 machines and it is the same.

**Comment by waran70** [comment]
Image field so far not working here on any windows system (7,10, Serv2012, Serv2019) in any popular browsers. 
However there is no problem on Ubuntu and FF. Local java?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/15388#issuecomment-987724523
