### ISSUE TITLE
[bug] Manual Update from 5.3.0 to 6.0.0 v8

### ISSUE THREAD

**Issue by cm-gswzm** [YetiForceCompany/YetiForceCRM#14357]
# 🐞 bug report

### ⁉️ Describe the bug

Hi yeti-Team,

we receive the following bug message when we try to update from yetiforce 5.3.0 to 6.0.0 with the suitable upgrade-package from https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%205.x.x/5.3.0_to_6.0.0

![Bildschirmfoto 2021-03-08 um 14 25 26](https://user-images.githubusercontent.com/80264219/110328512-ba1f0700-801b-11eb-990e-10f50da8ff6b.png)

Thanks for your help.

### 🔥 How to trigger the error

1. Downloaded the 5.3.0 to 6.0.0 package from abovementioned url.
2. YetiCRM Admin Panel > Logs > Updates > + Upload update > Choose the downloaded file and upload
3. Accept License agreement -> "Do you want to proceed with the import" -> Yes
4. After about 5 sec > See error

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
Excuse some of red lines due to backup machine
![Bildschirmfoto 2021-03-08 um 15 12 14](https://user-images.githubusercontent.com/80264219/110332772-120c3c80-8021-11eb-815c-fcd71ef1dbdc.png)
![Bildschirmfoto 2021-03-08 um 15 12 41](https://user-images.githubusercontent.com/80264219/110332859-31a36500-8021-11eb-902d-f9be2ade5b6f.png)
 ![Bildschirmfoto 2021-03-08 um 15 13 48](https://user-images.githubusercontent.com/80264219/110332873-3a943680-8021-11eb-8686-ee67b5044a81.png)
![Bildschirmfoto 2021-03-08 um 15 13 59](https://user-images.githubusercontent.com/80264219/110332929-4849bc00-8021-11eb-9004-a0d97748b7df.png)
![Bildschirmfoto 2021-03-08 um 15 14 34](https://user-images.githubusercontent.com/80264219/110332939-4d0e7000-8021-11eb-9a3b-37291b8b514e.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

In mysql/error.log
2021-03-08T12:10:03.370428Z 9 [ERROR] [MY-013134] [Server] Table './yetiforce/u_yf_crmentity_search_label' is marked as crashed and should be repaired
2021-03-08T12:10:03.370786Z 9 [Warning] [MY-010756] [Server] Checking table:   './yetiforce/u_yf_crmentity_search_label'

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 5.3.0
| Web server (name and version)       |     nginx 1.18           | 
| PHP                                 |       php 7.4.3         |
| Browser (name and version)          |       chrome/firefox         |
| Operating System (name and version) |        macos 11.2        |
| Database (name and version)         |        MySQL 8.0.21        |
| Service Pack version                |      4          |

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13862#issuecomment-761180307
https://github.com/YetiForceCompany/YetiForceCRM/issues/13823

> Table './yetiforce/u_yf_crmentity_search_label' is marked as crashed and should be repaired

before you do anything, fix the table u_yf_crmentity_search_label

**Comment by cm-gswzm** [comment]
table repaired but that doesn't change the error.
php and mysql error logs are empty, yeti update error still remains.
