### ISSUE TITLE
Install error v 2.0.423

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1435]
Version Apache	2.2.29
Version PHP	5.4.35
Version MySQL	5.5.42-cll
OS	linux

![installdeveloper](https://cloud.githubusercontent.com/assets/1402355/8611523/be81737c-26db-11e5-8678-cb968d720b78.JPG)

**Comment by waw555** [comment]
Master v 2.0.346 install normal

**Comment by MaciejStencel** [comment]
Error occurred in crm loader while trying to install crm. In already installed environment it loader worked properly. It is now fixed, please check if it is working for You.
