### ISSUE TITLE
Improved Translation Mail Scanner

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1437]
Remove variables when not in use

![mailscanner](https://cloud.githubusercontent.com/assets/1402355/8611916/dca40f76-26e1-11e5-8d04-efb7f46d9866.JPG)

**Comment by MaciejStencel** [comment]
Fix is live on gitdeveloper.yetiforce.com for testing.

**Comment by waw555** [comment]
All ok
