### ISSUE TITLE
Project Milestone and Project tasks not showing on gantt chart

### ISSUE THREAD

**Issue by samuelsituma** [YetiForceCompany/YetiForceCRM#14379]
Gantt chart doest show project milestones and tasks and I have the records

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/110633118-ac4abc80-81a8-11eb-875d-2660a5758542.jpg)

**Comment by MexasPT** [comment]
Same with me in 6.1... ;(

**Comment by samuelsituma** [comment]
Mine was something to do with server specs kindly check your server
specifications if they are correct and test again

**Comment by MexasPT** [comment]
Hi samuelsituma!
Do you have any idea what you changed?

**Comment by samuelsituma** [comment]
It was a space issue on my Cpanel so I moved the CRM to a bigger Linux
server and it worked well.
