### ISSUE TITLE
[bug] Wrong path in YetiForce-Documentation 

### ISSUE THREAD

**Issue by mad99** [YetiForceCompany/YetiForceCRM#14388]
# 🐞 bug report: in Documentation

### ⁉️ There (https://yetiforce.com/en/component/zoo/item/enable-cron) is the wrong path config/config.inc.php instead of /config/Main.php (I guess). 

Couldn't find the file config.inc.php also with search in the hole system...
So I was searching for app_key and found the «$application_unique_key» in different other Files.
I guess - and the try&error say, I'm right - the path should be /config/Main.php

Maybe there are also other places in the documentary also in the polish-version where this path is wrong communicating.

<img width="1127" alt="YetiForce_confi inc php_Cursor_und_Enable_cron_-_YetiForce" src="https://user-images.githubusercontent.com/6169308/110762551-33ec0600-8251-11eb-86c3-e44b99adc242.png">

**Comment by mariuszkrzaczkowski** [comment]
fixed
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-administratora/item/jak-uruchomic-cron-a-w-yetiforce-crm
