### ISSUE TITLE
Improved Translation Mail

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1438]
Remove variables when not in use

![mail](https://cloud.githubusercontent.com/assets/1402355/8611978/a9023caa-26e2-11e5-9b33-44bbf49c0e67.JPG)

**Comment by MaciejStencel** [comment]
This fix is live on gitdeveloper.yetiforce.com. You can check if it's correct.

**Comment by waw555** [comment]
All ok
