### ISSUE TITLE
[bug] Mailscanner not working after upgrade form YF 5.3 to 6.1 v7

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#14394]
# 🐞 bug report

### ⁉️ Describe the bug

Hello,

as already described in this issue here https://github.com/YetiForceCompany/YetiForceCRM/issues/13856 after YF Upgrade from v. 5.3. to 6.1 v7 doesn`t work any more.
New mails which should trigger actions like "Create e-mail message" and "Create Helpdesk" are not show in the tickets. Cron job is running. **You have to read that mails before in the inbox - then these tickets are created.**

Also the widget in the top of my dashboard is missing, which indicates that there are new unread e-mails in my inbox.

### 🔥 How to trigger the error

1. Upgrade YF from 5.3 to latest 6.1 v7
2. Send some mail to your mailaccount
3. Go to Support -> Tickets and look for the latest ticktets (no new ticket).
4. Go to inbox (Roundcube) and read mail
5. Go back to Support -> Tickets and look for the latest ticktets. The mail/ticket is shown.

### 👎 Actual Behavior

Incoming mails do not trigger new tickets in helpdesk.

### 👍 Expected Behavior

Incoming mails create new tickets in helpdesk, like in YF 5.3 before.

### 👷 Testing

- [ X] I confirm that I tested it at https://gitstable.yetiforce.com -> could not reproduce it / works here!
- [ X] I confirm that I tested it at https://gitdeveloper.yetiforce.com -> could not reproduce it / works here!

### 📷 Screenshot of configuration

![ConfReport](https://user-images.githubusercontent.com/13665806/110915846-7593b400-8318-11eb-8094-eba3e806578f.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1 v7
| Web server (name and version)       |  Apache/2.4.41 (Ubuntu)              |
| PHP                                 |     7.2           |
| Browser (name and version)          |       Firefox 86.0.1         |
| Operating System (name and version) |    Ubuntu 20.04 LTS            |
| Database (name and version)         |     mysql 10.3.25            |
| Service Pack version                |      7          |

**Thanks!**

**Comment by blu-IT** [comment]
Nobody any idea here? The problem still persits. New mails are not shown / do not trigger a new ticket, until the are read.
Also new mails are not shown in the widget on top of the site on the dashboard. The cron job is working!

**Comment by mariuszkrzaczkowski** [comment]
It's simple, the CRON is misconfigured so it doesn't work.
Correct the server configuration bya nothing was in red and it will work.
https://yetiforce.com/pl/component/zoo/item/enable-cron

**Comment by blu-IT** [comment]
But cron confuguration worked in V. 5.3 and was not touched!

If there have to be modifications for cron when updating form 5.3 to 6.1 it was not mentioned during the upgrade process.
Also the cron backend in YF does not show any error and says the emal scanner task has been completed successfully.

**Comment by mariuszkrzaczkowski** [comment]
It's strange that it worked, it shouldn't

**Comment by salvofan** [comment]
Did you manage to fix this? I have the same issue with 6.4.0. 
If i go to Logs-Download History, I can see the error in photo. 
The time at "start time" is when this stopped working and now only works if I click on the email on roundcube.

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/26599683/da5d2be3-8a36-407e-b8ef-65e4170e93af)
