### ISSUE TITLE
Email ticket response does not change status to "response received" #14390

### ISSUE THREAD

**Issue by fermic** [YetiForceCompany/YetiForceCRM#14395]
Good morning, I need help.

When the user responds to a ticket by e-mail, he only links to the ticket and does not change the status to "response received".

My previous help request has been finalized, but my settings are in accordance with what was reported.

I will greatly appreciate your help.

![imgem1](https://user-images.githubusercontent.com/80478401/110925082-871d9180-8301-11eb-8331-3b6fca78746a.png)
![imagem2](https://user-images.githubusercontent.com/80478401/110925090-8ab11880-8301-11eb-989f-347110cecd13.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/80478401/110925193-a5838d00-8301-11eb-943f-8041caa1417e.jpg)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/110926112-497e3000-8324-11eb-8a2c-2b2c37c6223b.jpg)

**Comment by drakub** [comment]
How do you guys get to configure this email module. I am on yetiforce 6.1.0
