### ISSUE TITLE
[bug] Responding to e-mails with external mail app does not show correct [ticket_no] in subject

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#14396]
# 🐞 bug report

### ⁉️ Describe the bug

Hello,

as I already reported here https://github.com/YetiForceCompany/YetiForceCRM/issues/13403#issuecomment-698893943 the [ticket_no] is not shown/filled in the subject of the e-mail.
Now I figured out that this problem seems to affect **only on external mail apps** (here Outlook).

I could not reproduce on gitstable, but on gitstable responding to a e-mail causes to open the build in roundcube mailer.
**How can I force my browser (Firefox) to open/respond to mails inside YF with roundecube by the way?**

### 🔥 How to trigger the error

1. Go to Support -> Tickets
2. Select the coresponding ticket
3. Click on "Respond" in the Summary-Tab

### 👎 Actual Behavior

![grafik](https://user-images.githubusercontent.com/13665806/110936881-d7144c80-8331-11eb-8dd3-5801c33ad2b0.png)

### 👍 Expected Behavior

External mail app is opend to respond email and ticket_no is filled in.

### 👷 Testing

- [ X] I confirm that I tested it at https://gitstable.yetiforce.com **-> could not reproduce, because YF opens roundcube mail** 
- [ X] I confirm that I tested it at https://gitdeveloper.yetiforce.com **-> could not reproduce, because YF opens roundcube mail** 

Environment | Version / Name
-- | --
YetiForce | 6.1 v7
Web server (name and version) | Apache/2.4.41 (Ubuntu)
PHP | 7.2
Browser (name and version) | Firefox 86.0.1
Operating System (name and version) | Ubuntu 20.04 LTS
Database (name and version) | mysql 10.3.25
Service Pack version | 7

**Thanks!**

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?q=ticket_no

**Comment by blu-IT** [comment]
> **How can I force my browser (Firefox) to open/respond to mails inside YF with roundecube by the way?**

Just to complete my found solution:

You can go in Roundcube to Settings > Preferences > User Interface > Browser Options and click the link "Register protocol handler for mailto: links"

**Comment by blu-IT** [comment]
> Hello,
> 
> as I already reported here [#13403 (comment)](https://github.com/YetiForceCompany/YetiForceCRM/issues/13403#issuecomment-698893943) the [ticket_no] is not shown/filled in the subject of the e-mail.
> Now I figured out that this problem seems to affect **only on external mail apps** (here Outlook).

Tested now again, but the problem still persits - even when responding to mails with roundcube.
