### ISSUE TITLE
[bug] Illegal Value when creating Entity through workflow

### ISSUE THREAD

**Issue by merckaa** [YetiForceCompany/YetiForceCRM#14413]
I'm setting up a workflow to auto creat an entity like Orders and I'm getting ILLEGAL VALUE ERROR for currency field.

![image](https://user-images.githubusercontent.com/15110035/111497884-3bfbe800-8720-11eb-8b2e-be3714e07a74.png)
![image](https://user-images.githubusercontent.com/15110035/111497947-4918d700-8720-11eb-846c-96567ebf7d43.png)

Reproduced this error in gitdeveloper.

**Comment by deepti4666** [comment]
Can you send the steps you did to get this error?

**Comment by merckaa** [comment]
I've created a workflow to generate a ORDER after client accepts a Quote, but when saving getting this error, i think it's about mapping currency field.
This problem occurs in every worlkflow to create an entity.

**Comment by deepti4666** [comment]
Have you tried creating a mapping first & then add it to a workflow?

**Comment by konadrian** [comment]
The problem no longer exists.
I closed the ticked due to missing information
