### ISSUE TITLE
[bug] Project task creation not working from workflow

### ISSUE THREAD

**Issue by deepti4666** [YetiForceCompany/YetiForceCRM#14417]
# 🐞 bug report

### ⁉️ Describe the bug

Created a workflow to create a started list of tasks for any new project.
I used 
"Create event - type = Todo" - this creates an activity for the project (a workaround for the project tasks)
"Create Entity" & mapped the fields, but it still doesn't create the tasks
Create a stand list of "Project milestones" for each set of projects

### 🔥 How to trigger the error

1. Go to "settings"
2. Automation > Workflows
3. New workflow > Projects - https://prnt.sc/10p2zdc 
4. Specify when to execute this workflow > Only once, when all conditions are met - https://prnt.sc/10p2zdc
5. Step 2 - rules - https://prnt.sc/10p30ap
6. Add a task workflow: Create entity - https://prnt.sc/10p33oo

### 👎 Actual Behavior

Nothing happens

### 👍 Expected Behavior

Project task created

### 👷 Testing

- [ ✔️ ] I confirm that I tested it at https://gitstable.yetiforce.com - doesn't work
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

Add a task workflow: Create entity - https://prnt.sc/10p33oo

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

No error showing

* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | YetiForce CRM 6.1 
| Web server (name and version)       |                |
| PHP                                 |      7.2.34          |
| Browser (name and version)          |   Microsoft Edge             |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |  Service Pack v5              |

**Comment by mariuszkrzaczkowski** [comment]
logs ?

**Comment by deepti4666** [comment]
Errors.log

E_WARNING: Invalid argument supplied for foreach() in /home/boardroo/public_html/crm/app/Log/FileTarget.php, line 139
#0 vendor/yetiforce/yii2/log/Target.php (152)  >>  App\Log\FileTarget->getContextMessage()
#1 vendor/yetiforce/yii2/log/Dispatcher.php (191)  >>  yii\log\Target->collect([array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array],false)
#2 vendor/yetiforce/yii2/log/Logger.php (177)  >>  yii\log\Dispatcher->dispatch([array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array],false)
#3 app/Log.php (212)  >>  yii\log\Logger->flush()
#4 app/Log.php (271)  >>  App\Log->log('Sorry! Attempt to access restricted file.',1,'')
#5 app/BatchMethod.php (105)  >>  App\Log->error('Sorry! Attempt to access restricted file.')
#6 modules/Vtiger/crons/BatchMethods.php (26)  >>  App\BatchMethod->execute()
#7 cron.php (98)  >>  Vtiger_BatchMethods_Cron->process()
E_WARNING: Invalid argument supplied for foreach() in /home/boardroo/public_html/crm/app/Log/FileTarget.php, line 139
#0 vendor/yetiforce/yii2/log/Target.php (152)  >>  App\Log\FileTarget->getContextMessage()
#1 vendor/yetiforce/yii2/log/Dispatcher.php (191)  >>  yii\log\Target->collect([array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array],false)
#2 vendor/yetiforce/yii2/log/Logger.php (177)  >>  yii\log\Dispatcher->dispatch([array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array],false)
#3 app/Log.php (212)  >>  yii\log\Logger->flush()
#4 app/Log.php (271)  >>  App\Log->log('vtlib\\Deprecated::checkFileAccessForInclusion(modules//.php) - Sorry! Attempt to access restricted file. realfilepath: ',1,'')
#5 vtlib/Vtiger/Deprecated.php (75)  >>  App\Log->error('vtlib\\Deprecated::checkFileAccessForInclusion(modules//.php) - Sorry! Attempt to access restricted file. realfilepath: ')
#6 include/CRMEntity.php (59)  >>  vtlib\Deprecated->checkFileAccessForInclusion('modules//.php')
#7 modules/Vtiger/models/Record.php (716)  >>  CRMEntity->getInstance(NULL)
#8 modules/Project/models/Module.php (110)  >>  Vtiger_Record_Model->getInstanceById(0)
#9 app/BatchMethod.php (99)  >>  Project_Module_Model->updateProgress(0)
#10 modules/Vtiger/crons/BatchMethods.php (26)  >>  App\BatchMethod->execute()
#11 cron.php (98)  >>  Vtiger_BatchMethods_Cron->process()
E_WARNING: file_put_contents(): Only 0 of 40 bytes written, possibly out of free disk space in /home/boardroo/public_html/crm/app/Cron.php, line 115
#0 app/Cron.php (115)  >>  file_put_contents('cache/logs/cron/20210318_0840.log','2021-03-18 08:40:03 [info] - File start
',8)
#1 app/Cron.php (94)  >>  App\Cron->log('File start','info',false)
#2 cron.php (23)  >>  App\Cron->__construct()
E_WARNING: file_put_contents(): Only 0 of 40 bytes written, possibly out of free disk space in /home/boardroo/public_html/crm/app/Cron.php, line 115
#0 app/Cron.php (115)  >>  file_put_contents('cache/logs/cron/20210318_0840.log','2021-03-18 08:40:03 [info] - File start
',8)
#1 app/Cron.php (94)  >>  App\Cron->log('File start','info',false)
#2 cron.php (23)  >>  App\Cron->__construct()
E_WARNING: file_put_contents(): Only 0 of 53 bytes written, possibly out of free disk space in /home/boardroo/public_html/crm/app/Cron.php, line 115
#0 app/Cron.php (115)  >>  file_put_contents('cache/logs/cron/20210318_0840.log','2021-03-18 08:40:03 [info] - SAPI: cgi-fcgi, User: 1
',8)
#1 cron.php (30)  >>  App\Cron->log('SAPI: cgi-fcgi, User: 1','info',false)
E_WARNING: file_put_contents(): Only 0 of 40 bytes written, possibly out of free disk space in /home/boardroo/public_html/crm/app/Cron.php, line 115
#0 app/Cron.php (115)  >>  file_put_contents('cache/logs/cron/20210318_0845.log','2021-03-18 08:45:02 [info] - File start
',8)
#1 app/Cron.php (94)  >>  App\Cron->log('File start','info',false)
#2 cron.php (23)  >>  App\Cron->__construct()
E_WARNING: file_put_contents(): Only 0 of 40 bytes written, possibly out of free disk space in /home/boardroo/public_html/crm/app/Cron.php, line 115
#0 app/Cron.php (115)  >>  file_put_contents('cache/logs/cron/20210318_0845.log','2021-03-18 08:45:02 [info] - File start
',8)
#1 app/Cron.php (94)  >>  App\Cron->log('File start','info',false)
#2 cron.php (23)  >>  App\Cron->__construct()
E_WARNING: file_put_contents(): Only 0 of 53 bytes written, possibly out of free disk space in /home/boardroo/public_html/crm/app/Cron.php, line 115
#0 app/Cron.php (115)  >>  file_put_contents('cache/logs/cron/20210318_0845.log','2021-03-18 08:45:02 [info] - SAPI: cgi-fcgi, User: 1
',8)
#1 cron.php (30)  >>  App\Cron->log('SAPI: cgi-fcgi, User: 1','info',false)
E_WARNING: file_put_contents(): Only 0 of 40 bytes written, possibly out of free disk space in /home/boardroo/public_html/crm/app/Cron.php, line 115
#0 app/Cron.php (115)  >>  file_put_contents('cache/logs/cron/20210318_0850.log','2021-03-18 08:50:02 [info] - File start
',8)
#1 app/Cron.php (94)  >>  App\Cron->log('File start','info',false)
#2 cron.php (23)  >>  App\Cron-

**Comment by deepti4666** [comment]
[cron.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6165470/cron.log)
[errors (1).log](https://github.com/YetiForceCompany/YetiForceCRM/files/6165472/errors.1.log)

There is an error with the system.log file - doesn't want to open/download

**Comment by mariuszkrzaczkowski** [comment]
E_WARNING: file_put_contents(): Only 0 of 40 bytes written, possibly out of free disk space 

check how much free disk space you have

**Comment by deepti4666** [comment]
I have cleared that error, but for some reason the systems.log file went to 12.58 gb today twice.

**Comment by rskrzypczak** [comment]
set `public static $LOG_LEVELS = ["error", "warning"] ;` only
delete system.log.

and about the issue.. it's basically no error here.
You cen't set value for reference field, like that.
![image](https://user-images.githubusercontent.com/10221999/111742079-d0348f00-8887-11eb-8a88-0d9742bbd58a.png)
It won't work.
.. and because the system cannot set this value, the mandatory field is empty and the task project is not created.
Fields of reference type is not fully supported in this type of workflow actions.
For now, if you want to set a value, you must enter the record ID, not its name.

**Comment by deepti4666** [comment]
@rskrzypczak thank you so much for your help.

> set `public static $LOG_LEVELS = ["error", "warning"] ;` only
> delete system.log.

I have set that setting and it hasn't bombed out as yet.

> and about the issue.. it's basically no error here.
> You cen't set value for reference field, like that.
> ![image](https://user-images.githubusercontent.com/10221999/111742079-d0348f00-8887-11eb-8a88-0d9742bbd58a.png)
> It won't work.
> .. and because the system cannot set this value, the mandatory field is empty and the task project is not created.
> Fields of reference type is not fully supported in this type of workflow actions.
> For now, if you want to set a value, you must enter the record ID, not its name.

What are the field values that I can use for it to work and create the project task, as there are a few tasks to add to each new project and some are dependant on certain other tasks being completed?

**Comment by sistemasnow** [comment]
We have the same problem here.

Please, @rskrzypczak: What do you mean exactly with this: 

_"Fields of reference type is not fully supported in this type of workflow actions.
For now, if you want to set a value, you must enter the record ID, not its name."_

We would like to know what are the right values we can use in order to create the project tasks. That would be great!

Thanks in advance.

**Comment by rskrzypczak** [comment]
As I mentioned before - record ID, for example:
![image](https://user-images.githubusercontent.com/10221999/116506193-0e789180-a8bd-11eb-8bb5-2b8e2f52b2c1.png)

**Comment by sistemasnow** [comment]
> As I mentioned before - record ID, for example:
> ![image](https://user-images.githubusercontent.com/10221999/116506193-0e789180-a8bd-11eb-8bb5-2b8e2f52b2c1.png)

Thanks for the answer, @rskrzypczak.
