### ISSUE TITLE
[Docker] PHP version mismatch prevents docker deployment

### ISSUE THREAD

**Issue by firestonem** [YetiForceCompany/YetiForceCRM#14415]
There are hardcoded references to PHP version 7.3 in 
- https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/nginx/vhost.conf#L76
- https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/fpm/www.conf#L36
- https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/docker_entrypoint.sh#L5

A docker build will install version 7.4 by default, breaking these references. As a result there is no backend for Nginx to serve so it throws a 502 error

**Comment by mariuszkrzaczkowski** [comment]
fixed
