### ISSUE TITLE
[bug] [PL] Usunięcie z folderu pola dwóch elementów drzewa wywołuje błąd nieprawidłowej wartości

### ISSUE THREAD

**Issue by hahyes** [YetiForceCompany/YetiForceCRM#14426]
# 🐞 bug report

### ⁉️ Describe the bug

Jak w tytule, zmieniając na przykład drzewo z kategoriami dla produktów, usuwając więcej jak jeden element drzewa, edycja nie powiedzie się i wyrzuci błąd "Wykryto niedozwoloną wartość, prosimy o kontakt z administratorem". Napotkałem ten problem na różnych hostingach i różnych konfiguracjach, więc wykluczam tutaj problem ze skonfigurowaniem.

### 🔥 How to trigger the error

1. Konfiguracja systemu: Moduły standardowe > Pola - foldery
2. Dla przykładu: Kategoria dla modułu Produkty
3. Usuń dwa elementy z drzewa wartości.
4. Zapisz zmiany.
5. Wyskakuje błąd.

### 👍 Expected Behavior

Powinno zapisać zmiany, oczywiście.

### 👷 Testing

- [X] I confirm that I tested it at https://gitstable.yetiforce.com
- [X] I confirm that I tested it at https://gitdeveloper.yetiforce.com

Na gitdeveloper pojawiło się trochę więcej informacji o błędzie. Generalnie błąd występuje on na obu wersjach. Myślę, że specjalnie OBSa do tego uruchamiać nie muszę.

![image](https://user-images.githubusercontent.com/37104952/111774147-5f08d200-88af-11eb-814e-efa0235c6455.png)

Konfigurację i logi dorzucę później, jeżeli będzie potrzeba. Stacktrace powinien pomóc.

W sumie mam jeszcze JSONa z zapisywania, może dojdziecie, która wartość jest niedozwolona tutaj: https://pastebin.pl/view/004ab553
### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1
| Web server (name and version)       |         Apache  2.4.38      |
| PHP                                 |        7.3.27.1        |
| Browser (name and version)          |       Chromium    81.0.4044.138      |
| Operating System (name and version) |        Debian 10        |
| Database (name and version)         |        MariaDB 10.3.27        |
| Service Pack version                |          v7      |

**Comment by areksolek** [comment]
W obecnej wersji problem nie występuje:
![TKQMO2k7bY](https://user-images.githubusercontent.com/25615135/159224694-5e9417b2-13f3-4c7e-b1d7-39f07e0f77f7.gif)
