### ISSUE TITLE
[bug] Cannot delete image from image field

### ISSUE THREAD

**Issue by IanMuller** [YetiForceCompany/YetiForceCRM#14428]
I have tested it on git dev. Once uploaded image cannot be deleted (custom image field)

Ian

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/14331

**Comment by garryatbrighton** [comment]
This bug relating to field in departments too. Users are unable to change once uploaded logo. Marius added duplicate issue but other respective issue has been closed. Are you gents planning to fix it before next release?
