### ISSUE TITLE
Call to a member function get() on null.

### ISSUE THREAD

**Issue by drakub** [YetiForceCompany/YetiForceCRM#14422]
Hi, I have been testing out the yetiforce CRM but when I click on the Edit Files Menu, I get the following error. Can anyone help ,me out with this;
![Screenshot (58)](https://user-images.githubusercontent.com/19745222/111744880-f153aa80-889c-11eb-9cfc-6fcea490ea6c.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/111745269-a3cf4180-888c-11eb-8022-b34b4b5199d6.jpg)

**Comment by drakub** [comment]
I am getting the attached error when wanted to edit fields or quick create a field. My installation is Yetiforce version 6.1.0 on XAMPP Server in Windows 10 64-bit.

**Steps to Reproduce the Error**
1. Go to settings module
2. Choose Standard Modules
3. Click 'Edit Fields' or 'Fields - Quick Create'
4. See the error

**Actual Result**
The actual result is the error shown in the screen shot

**Expected Result**
The expected result is to see a view of fields based on the module selected and edit /change the fields, with buttons to add blocks and new fields

**Testing**
This has been checked on gitstable and the error is not there; the error is also not available on the git developer version.

**Environment**
YetiForce                   6.1.0
Web server                Apache 2.4
PHP                           7.3.2
Browser                      Mozilla Firefox
Operating System       Windows 10
Database                     MariaDB

**THE ERROR SCREEN**
![Screenshot (58)](https://user-images.githubusercontent.com/19745222/111757071-fbc97080-88ab-11eb-9be7-de9ef6381d93.png)


**THE ERROR LOG**
![Screenshot (59)](https://user-images.githubusercontent.com/19745222/111757103-04ba4200-88ac-11eb-9d41-e8375672d10b.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13872

**Comment by drakub** [comment]
> 
> 
> #13872

This fix did not help me but I got the issue fixed. I opened the file **/layouts/basic/modules/Settings/LayoutEditor/index.tpl** and changed the line **{assign var=BLOCK_ICON value=BLOCK->get(‘icon’)}** to **{assign var=BLOCK_ICON value=BLOCK_MODEL->get(‘icon’)}**. Thanks, I know I got this solution on this platform but I forgot the issue number since I read it and slept over it before trying it out.
