### ISSUE TITLE
[bug] Email template - Crete URL

### ISSUE THREAD

**Issue by frato92** [YetiForceCompany/YetiForceCRM#14424]
Hi, I have a problem to create the email's template. When I create the link at my website, this link is create incorrectly because there isn't the hipertextual link on the website.I checked the source and before the saving, the <a> tag contains the link, but when i proceed to save it, the link isn't in the <a> tag.

thanks for the support.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/14263
