### ISSUE TITLE
Minor rendering bug in calendar dashboard widget in Grey theme[bug] 

### ISSUE THREAD

**Issue by nerimic** [YetiForceCompany/YetiForceCRM#14435]
# 🐞 bug report

### ⁉️ Describe the bug

When Grey theme is active the vertical lines of days' cells are interrupted when events are present in a row.

### 🔥 How to trigger the error

Activate Grey theme and look at Calendar widget (i.e. TEST C in gitdeveloper dasboard).

### 👎 Actual Behavior

The vertical lines of days' cells are interrupted when an event is present in the week.

### 👍 Expected Behavior

Continuous lines as in the Twilight theme.

### 👷 Testing

- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by mariuszkrzaczkowski** [comment]
Please attach a screenshot

**Comment by nerimic** [comment]
> Please attach a screenshot

![fullcalendar-widget](https://user-images.githubusercontent.com/45690654/111963484-df1f7980-8af3-11eb-82fa-a08763aa3ea4.png)
