### ISSUE TITLE
filename/www issue

### ISSUE THREAD

**Issue by Akaki-1991** [YetiForceCompany/YetiForceCRM#14437]
https://user-images.githubusercontent.com/75428743/111995604-8b805080-8b32-11eb-8f37-3b48005136c7.mp4

hello. what is the problem? cant upload files. version 6.1.0

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/111998665-8adcbf80-8b1c-11eb-89e5-d83799a768e1.jpg)

**Comment by Akaki-1991** [comment]
When I add a file to filename / www, it is not added and in the description no detailed view, no file appears, no file size,no file type

**Comment by rskrzypczak** [comment]
Can you verify it on test environments?
[GitStable](https://gitstable.yetiforce.com/)
[GitDeveloper](https://gitdeveloper.yetiforce.com/)

**Comment by Akaki-1991** [comment]
working :(

**Comment by MexasPT** [comment]
@Akaki29 

Hi!
Did you find the solution?
I have the same issue... :(
