### ISSUE TITLE
[bug] Import not workint at all

### ISSUE THREAD

**Issue by IanMuller** [YetiForceCompany/YetiForceCRM#14434]
In my last stable version import to account ends with message: "The imported file is in a different encoding than it was selected (ASCII)" All possible cobinations of csv has been tried.

In yeti dev import do nothing. 

Any fix for this bug?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/11762

https://github.com/YetiForceCompany/YetiForceCRM/issues/11762
