### ISSUE TITLE
Improved Translation Home

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1444]
![widget](https://cloud.githubusercontent.com/assets/1402355/8612469/7a9a10a6-26ea-11e5-9a22-0fbb7b8f2663.JPG)

**Comment by konadrian** [comment]
You can change this translation here
![translation](https://cloud.githubusercontent.com/assets/3193498/8696212/cb9888e4-2aea-11e5-8978-f7d3062c0e91.png)
If this is not a solution to your problem, please give more info
