### ISSUE TITLE
[Bug] Copy from Account button not showing

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14446]
Hello,

I have suddenly faced a problem where button to copy address from Account in Contact is not showing
I checked on git table and found that same is showing there. not able to understand what happened.

On Gitstable
![image](https://user-images.githubusercontent.com/12723595/112132154-4f132a00-8bf0-11eb-8152-cd1f2a72ed59.png)

On my local Server
![image](https://user-images.githubusercontent.com/12723595/112132251-66521780-8bf0-11eb-9ac4-5d81aa069a3e.png)

Please assist in the matter

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/112138642-0ea4b380-8bd2-11eb-9076-1b4cc752163c.jpg)

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski 
Sir details required is as below

# 🐞 bug report

### ⁉️ Describe the bug

**In contact module while creating contact feature is provided to copy address from Parent Account, till morning button to copy address from Account was coming but suddenly it disappeared. **

### 🔥 How to trigger the error
Steps to reproduce the behavior:

1. Go to Companies & Contact Menu -> Contact -> Add Record
2. Provide First name, Last name and select Account to map contact with organization
3. Scroll down to Primary Address Section

### 👎 Actual Behavior
I do not get button to copy address from Account Master

![image](https://user-images.githubusercontent.com/12723595/112142195-458fbf00-8bfc-11eb-97d2-0f85f4a389a1.png)



### 👍 Expected Behavior
Button to copy address from Account Master should come here (see gistable)
![image](https://user-images.githubusercontent.com/12723595/112142275-5c361600-8bfc-11eb-944c-789e75d4b576.png)



### 👷 Testing

- [✔️ ] I confirm that I tested it at https://gitstable.yetiforce.com **and button is shown here**
- [ ✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com **and button is shown here**

### 📷 Screenshot of configuration

![image](https://user-images.githubusercontent.com/12723595/112142537-b9ca6280-8bfc-11eb-89ca-544c03c6df1e.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

### 🌍 Your Environment




| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0
| Web server (name and version)       |    Apache 2.4.46            |
| PHP                                 |       7.3         |
| Browser (name and version)          |     Google Chrome **Version 89.0.4389.90 (Official Build) (64-bit)**           |
| Operating System (name and version) |  Linux              |
| Database (name and version)         |    MySql 8.0            |
| Service Pack version                |      YetiForce CRM 6.1 Service Pack v7          |

Regards

**Comment by JEEVAN28** [comment]
Hello,
While checking code from Chrome Inspect I noticed that below code is added

"<button class="btn btn-sm btn-primary c-btn-block-sm-down copyAddressFromAccount mr-2 mb-1 mb-md-0 d-none" ...</button>"

if I remove d-none from button class and make code like
<button class="btn btn-sm btn-primary c-btn-block-sm-down copyAddressFromAccount mr-2 mb-1 mb-md-0" ...

then button is visible but nothing happens on click.

please assist in the matter as this is important feature we are using.

Thanks in advance
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/discussions/13943

**Comment by JEEVAN28** [comment]
> #13943

Hi,
I made changes in Code but no Luck. Is there any settings from database as code files are same now.
Regards
Jeevan Pendhari

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski Hi, no luck in this matter, I tried updating original files for Edit.Js and also modified files from #13943 but both are not working. I suppose anything is need to be done from database ?

Please help in this matter

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski 
After some R&D, I realised the problem, I have disabled module for Vendors, Competition, Leads, Partners and only Account Module is On. In this case Option to select Member Of Type is not visible and then Button is also not visible as default is Account

Option to select Account / Lead / Vendor ....
![image](https://user-images.githubusercontent.com/12723595/114264889-389c0980-9a0b-11eb-8feb-8a9a797c0dad.png)

After deactivating modules, selection option is not visible and I think default is set to Account, now button is not visible
![image](https://user-images.githubusercontent.com/12723595/114264941-86b10d00-9a0b-11eb-9cba-4732d1b00c8d.png)

I think this need to be done from code handling. Please guide for modification

Regards
Jeevan Pendhari
