### ISSUE TITLE
[bug] Module widget Timeline throws error

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#14454]
# 🐞 bug report

### 🔥 How to trigger the error

![timeline_wid](https://user-images.githubusercontent.com/8545791/112151137-f2187380-8bf1-11eb-8a64-1d7982b60e9b.gif)

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | current gitdev

### ❓ Additional context

Pls take a look to buggy widget with opportunity

**Comment by rskrzypczak** [comment]
Fixed on the current development version, the bug will not appear in version 6.2.
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/14627
