### ISSUE TITLE
[BUG] Home Quick Create

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1445]
Text not included

![quickcreate2](https://cloud.githubusercontent.com/assets/1402355/8612490/cc558eb6-26ea-11e5-9dca-5e4175ba712f.JPG)

**Comment by konadrian** [comment]
We need more info about the problem

**Comment by waw555** [comment]
The text is not completely visible, you must expand the columns

#1143 
#751

**Comment by konadrian** [comment]
Added fix can be seen here https://gitdeveloper.yetiforce.com

**Comment by waw555** [comment]
Please, add widht +5 px for central column
![quickcreate3](https://cloud.githubusercontent.com/assets/1402355/8617004/0d907f5c-2719-11e5-8717-76b76cf9f5d7.JPG)
