### ISSUE TITLE
[BUG] Quick Create 

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1446]
When you create a business proposal, with the rapid establishment of the transaction, you can not select a company
![leads](https://cloud.githubusercontent.com/assets/1402355/8612704/5c969774-26ee-11e5-8acd-2ada923f5b24.JPG)

**Comment by rskrzypczak** [comment]
I didn't notice the error in the current version of the YetiForce system. Please check if the error occurs in https://github.com/YetiForceCompany/YetiForceCRM/issues/1446
