### ISSUE TITLE
[bug] Passwords are changed (!) when editing some other information

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#14466]
# 🐞 bug report

### ⁉️ Describe the bug

When editing a detail of an exiting entry in the passwords section, the password is changed in "************" when the password is hidden and an error is shown.

![Screenshot_2021-03-26 Yetiforce Fehler ](https://user-images.githubusercontent.com/13665806/112622496-64c06380-8e2b-11eb-9bea-8ebe0fc145ab.png)

### 🔥 How to trigger the error

1. Go to Databases -> Passwords.
2. Click on any already stored entry.
3. Edit or add something to the details (or any other field) while the password is hidden (*****).
4. Save the modifications in the detail field.
5. See error

### 👎 Actual Behavior

The password is overwritten with the ************* entry in the password field that indicates the password is hidden 

### 👍 Expected Behavior

Only the edited filed is touched when saving the entry. **The password field remains unchanged.**

### 👷 Testing

- [X ] I confirm that I tested it at https://gitstable.yetiforce.com
- [X ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![110915846-7593b400-8318-11eb-8094-eba3e806578f](https://user-images.githubusercontent.com/13665806/112622374-3c386980-8e2b-11eb-92f9-a0cd8abddc81.png)

### 🌍 Your Environment

Environment | Version / Name
-- | --
YetiForce | 6.1 v7
Web server (name and version) | Apache/2.4.41 (Ubuntu)
PHP | 7.2
Browser (name and version) | Firefox 86.0.1
Operating System (name and version) | Ubuntu 20.04 LTS
Database (name and version) | mysql 10.3.25
Service Pack version | 7

### ❓ Additional context

Tested on gitstable and gitdeveloper: Could not reproduce, because there, in the moment you click on "Save" the password is shown for a second and stored that way. 
Also on my system the password is shown for a second, but leads to the error page and ******* stored as new password.

**Comment by mariuszkrzaczkowski** [comment]
logs

**Comment by blu-IT** [comment]
Have sent them right now. Thanks!

**Comment by rskrzypczak** [comment]
Can you really reproduce it on the official demo?
I try it and I cen't.
anyway.. check the console(F12), maybe you will find some info there.
.. and look at this: [debug](https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging)
system.log file should contain some information.

**Comment by blu-IT** [comment]
> Can you really reproduce it on the official demo?
> I try it and I cen't.

No, I can't reproduce on the offial demo as I wrote under "Addional context".
But as descried there, the behavior of the system is differnt from mine.

> anyway.. check the console(F12), maybe you will find some info there.
> .. and look at this: [debug](https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging)
> system.log file should contain some information.

OK, I will have to check this and report.

**Comment by rskrzypczak** [comment]
Lack of activity and error not present in the current version, so I close.
Feel free to open a new ticket if in your opinion the problem persists and is related to the current version.
