### ISSUE TITLE
[BUG] Email template not working

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1447]
Tested on dev 149 and master 2.0.346 version:
Trying to build an Email template but can't get the variables working.

Example: create new email template, select contacts module, select first name and press the green button. Add the variable to the body text, in this case: Hello  #a#67#aEnd#,

Trying to send an email from contacts with this variable does not get replaced by the firstname.

**Comment by zebrahosting** [comment]
Let me add to this that email templates for example for projects or projects task work fine. It seems not a general issue but more specific to the Contacts module.

**Comment by konadrian** [comment]
Please see on http://gitdeveloper.yetiforce.com/ is error still occur.
I sended email with first name value and works fine.

**Comment by zebrahosting** [comment]
It's not that simple:
When setting up a email template for contacts in list mode and then trying to send a mass email, it fails to load.

In overview:

Choosing a contact in detailed mode and sending an email from template , it works with the vars.
Choosing a contact in list mode and sending an email from template , it fails, nothing shows up in mail template, nor is is pre-filled.

How I use or test the module and record mode for an email template (contacts) remains a mystery to me.

**Comment by bpabiszczak** [comment]
This is not an error. Creating this functionality we only coded the variables that work in the record view, for all the other views, like the list view for example, these variables don't work. Of course, templates can be used, but without variables. It will be extended in version 2.2 or 2.3, when we will expand the mass mailing module.
