### ISSUE TITLE
[bug] Purchase price total not updating when Qty is changed

### ISSUE THREAD

**Issue by deepti4666** [YetiForceCompany/YetiForceCRM#14481]
# 🐞 bug report

### ⁉️ Describe the bug

The purchase price does not update when Qty is changed on the Quotes, Invoices, or Calculations modules

### 🔥 How to trigger the error

![Purchase price not updating](https://user-images.githubusercontent.com/57940552/112884279-9c4f3a00-90cf-11eb-8f04-1c9ae0b53eb3.gif)

1. Go to Quotes
2. Click on Edit
3. Add a purchase price, if you don't have any
4. Scroll down to Quantity and change the quantity amount
5. The purchase price total doesn't change when you change the quantity

### 👎 Actual Behavior

The purchase price total doesn't change when you change the quantity

### 👍 Expected Behavior

The total purchase should update when the quantity changes, so the margin can be calculated correctly and you can see what is the total cost for the quote

### 👷 Testing

- [ ✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

No error in the logs

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |   YetiForce CRM 6.1 
| Web server (name and version)       |                |
| PHP                                 |   7.3.27             |
| Browser (name and version)          |   Microsoft Edge             |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |  Service Pack v7              |

**Comment by mariuszkrzaczkowski** [comment]
https://user-images.githubusercontent.com/10198654/112942671-c553e700-9130-11eb-9e71-da4c1b837834.mp4

**Comment by vovpff** [comment]
@mariuszkrzaczkowski he told about Purchase. Check your video on more time

**Comment by deepti4666** [comment]
>  2021-03-30_08-18-37.mp4

Hi, 

Thank you for the response, 

The Nett column works on my side.

I am talking specifically about the purchase price column

**Comment by MaxPegankin** [comment]
Margin % is calculated based on total Purchase, but when Purchase doesn't change on Quantity, then total Margin % is also incorrect.

**Comment by davide-alghi** [comment]
Hi all,
that is not a bug.
It's correct that **Purchase** (price) doesn't update on **Quantity** change, exactly as **Unit Price** doesn't update on **Quantity** change.
The problem are labels.
Please take a look here

https://github.com/YetiForceCompany/YetiForceCRM/discussions/12574

https://github.com/YetiForceCompany/YetiForceCRM/discussions/14307

**Comment by deepti4666** [comment]
Hi Davide,

The purchase price or unit price should not update, which is correct, but when you increase the quantity the purchase price total should, as it's calculating the total cost, with the different quantities for that quote.

> Hi all,
> that is not a bug.
> It's correct that **Purchase** (price) doesn't update on **Quantity** change, exactly as **Unit Price** doesn't update on **Quantity** change.
> The problem are labels.
> Please take a look here
> 
> #12574
> 
> #14307

**Comment by deepti4666** [comment]
@mariuszkrzaczkowski I don't think should be closed, as the "Purchase price total" column is not updating correctly.

**Comment by davide-alghi** [comment]
Hi @deepti4666,
**Purchase** field contains cost for unit, not the total.
