### ISSUE TITLE
why is email template not picking field values of several fields 

### ISSUE THREAD

**Issue by samuelsituma** [YetiForceCompany/YetiForceCRM#14493]
Am trying to send an email using a template in the CRM but it's not getting the field names this is what am getting in my email.
![image](https://user-images.githubusercontent.com/46498594/113417510-3b27af00-93cc-11eb-9529-156d2a1aa66b.png)

**Comment by mariuszkrzaczkowski** [comment]
describe and show exactly how you send the email

**Comment by samuelsituma** [comment]
I have created  an email template for the contact module
[image: image.png]

Then I have logged in to my mailbox and selected the contacts I want to
send an email to and I selected the template that I just created above
[image: image.png]

When i send an email the field values are not showing on the email.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13203#issuecomment-648831367
