### ISSUE TITLE
[BUG] Quotes

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1449]
When creating a commercial offer you can not select a company
![quote](https://cloud.githubusercontent.com/assets/1402355/8612897/ba974e1a-26f1-11e5-8ab8-95b1e29b4828.JPG)

**Comment by konadrian** [comment]
I tried to find this problem on https://gitdeveloper.yetiforce.com/ , but i couldnt see any problems. Can you check once more and try to recreate this error on current version https://gitdeveloper.yetiforce.com/

**Comment by waw555** [comment]
Check that all works on https://gitdeveloper.yetiforce.com/

Close
