### ISSUE TITLE
[question][api][bug] Webservice call giving 401 Unauthorized after 6.1 upgrade

### ISSUE THREAD

**Issue by willinmon** [YetiForceCompany/YetiForceCRM#14503]
### ⁉️ Describe the bug

We upgraded our Dev environment to 6.1 w/Servicepack and since then our API will not connect to the webservice. I keep getting a 401 unauthorized error. I've checked all the settings against our Live site and all of the Dashboard settings are the same, ex: Webservice-Applications(username and password are the same, so is the api-key), Webservice-Users( the unsername and password are the same), nothing seems to have changed settings wise but I cannot figure out what is causing the issue. The Dev and Live are on the same server and that has never been a problem, so the server settings didn't change. I am out of ideas.

### 🔥 How to trigger the error

Using Postman or RESTClient(in FireFox browser)
Method: Post
URL: (mysitename)/webservice/Users/Login also tried (mysitename)/webservice.php?module=Users&action=Login/
Headers: x-api-key:(key provided in Yeti)
Body: {"userName": "yetiforce", "password": "yetiforce", "params": []}

### 👎 Actual Behavior

    Status Code: 401 Unauthorized
    access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, x-api-key, x-encrypted, x-token
    access-control-allow-methods: POST
    access-control-allow-origin: *
    connection: Keep-Alive
    content-disposition: attachment; filename="api.json"
    content-encoding: gzip
    content-type: text/plain;charset=UTF-8
    date: Mon, 05 Apr 2021 20:00:28 GMT
    encrypted: 0
    keep-alive: timeout=5, max=99
    server: Apache/2.4.39 (Ubuntu)
    transfer-encoding: chunked
    vary: Accept-Encoding

Response:
{"status":0,"error":{"message":"Invalid data access","code":401,"file":"api\/webservice\/Portal\/Users\/Login.php","line":230,"backtrace":"#0 api\/webservice\/Portal\/Users\/Login.php (230)  >>  Api\\Core\\Exception->__construct('Invalid data access',401)\n#1 api\/webservice\/Controller.php (110)  >>  Api\\Portal\\Users\\Login->post()\n#2 webservice.php (16)  >>  Api\\Controller->process()\n#3 public_html\/webservice.php (11)  >>  require('webservice.php')"}}

### 👍 Expected Behavior

Status Code: 200 OK

{"status":1,"result":{"token":"2518fc5cd6dffdb79cd113dbdfba811a","name":null,"parentName":null,"lastLoginTime":"2021-04-05 16:25:12","lastLogoutTime":null,"language":true,"type":1,"logged":true,"preferences":{"activity_view":"This Month","hour_format":"12","start_hour":"08:00","date_format":"mm\/dd\/yyyy","date_format_js":"m\/d\/Y","dayoftheweek":"Monday","time_zone":"America\/New_York","currency_id":1,"currency_grouping_pattern":"123,456,789","currency_decimal_separator":".","currency_grouping_separator":" ","currency_symbol_placement":"1.0$","no_of_currency_decimals":2,"truncate_trailing_zeros":0,"end_hour":"17:00","currency_name":"USA, Dollars","currency_code":"USD","currency_symbol":"&#36;","conv_rate":"1.00000"}}}

### 👷 Testing

- [X] I confirm that I tested it at https://gitstable.yetiforce.com
- [X] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
Server configuration is the same in both our Dev and Live environments but this works in Live and not in Dev.
![ConfReport](https://user-images.githubusercontent.com/31772589/113624693-f1d69a00-962d-11eb-8455-c2254df28cb7.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

webserviceError.log :
============ Error exception ====== 2021-04-05 16:26:17 ======
code: 401 | message: Invalid data access
file: /var/www/crm/yeti_dev/api/webservice/Portal/Users/Login.php (230)
============ stacktrace: 
#0 /var/www/crm/yeti_dev/api/webservice/Controller.php(110): Api\Portal\Users\Login->post()
#1 /var/www/crm/yeti_dev/webservice.php(16): Api\Controller->process()
#2 /var/www/crm/yeti_dev/public_html/webservice.php(11): require('/var/www/crm/ye...')
#3 {main}
============ Request ======  2021-04-05 16:26:17  ======
REQUEST_METHOD: POST
REQUEST_URI: /webservice/Users/Login/
QUERY_STRING: module=Users&action=Login&record=
PATH_INFO: 
----------- Headers -----------
cookie: YTSID=gllcgv2f0r55keqp80h3ch7k78
connection: keep-alive
dnt: 1
content-length: 64
content-type: text/plain;charset=UTF-8
x-api-key: WtkN5G5MWu8tfCtrYYZQKRnTRQ8PWAeM
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.5
accept: */*
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
host: yeti-development.zoeller.com
authorization: Basic eWV0aWZvcmNlOnlldGlmb3JjZQ==
----------- Request data -----------
Array
(
    [module] => Users
    [action] => Login
    [record] => 
)
----------- _GET -----------
Array
(
    [module] => Users
    [action] => Login
    [record] => 
)
----------- _POST -----------
Array
(
)
----------- Request payload -----------
{"userName": "yetiforce", "password": "yetiforce", "params": []}

webserviceDebug.log :

============ Request ======  2021-04-05 16:26:17  ======
REQUEST_METHOD: POST
REQUEST_URI: /webservice/Users/Login/
QUERY_STRING: module=Users&action=Login&record=
PATH_INFO: 
----------- Headers -----------
cookie : YTSID=gllcgv2f0r55keqp80h3ch7k78
connection : keep-alive
dnt : 1
content-length : 64
content-type : text/plain;charset=UTF-8
x-api-key : WtkN5G5MWu8tfCtrYYZQKRnTRQ8PWAeM
accept-encoding : gzip, deflate, br
accept-language : en-US,en;q=0.5
accept : */*
user-agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
host : yeti-development.zoeller.com
authorization : Basic eWV0aWZvcmNlOnlldGlmb3JjZQ==
----------- Request data -----------
Array
(
    [module] => Users
    [action] => Login
    [record] => 
)
----------- _GET -----------
Array
(
    [module] => Users
    [action] => Login
    [record] => 
)
----------- _POST -----------
Array
(
)
----------- Request payload -----------
{"userName": "yetiforce", "password": "yetiforce", "params": []}
-------------  Response  -----  2021-04-05 16:26:17  ------
Status: 401
REQUEST_METHOD: POST
REQUEST_URI: /webservice/Users/Login/
QUERY_STRING: module=Users&action=Login&record=
PATH_INFO: 
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Invalid data access
            [code] => 401
            [file] => api/webservice/Portal/Users/Login.php
            [line] => 230
            [backtrace] => #0 api/webservice/Portal/Users/Login.php (230)  >>  Api\Core\Exception->__construct('Invalid data access',401)
#1 api/webservice/Controller.php (110)  >>  Api\Portal\Users\Login->post()
#2 webservice.php (16)  >>  Api\Controller->process()
#3 public_html/webservice.php (11)  >>  require('webservice.php')
        )
)

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                                               |6.1|
| Web server (name and version)              |apache2|
| PHP                                                      |7.3|
| Browser (name and version)                   |Firefox(latest)|
| Operating System (name and version)     |Linux|
| Database (name and version)                 |yetiforce_dev|
| Service Pack version                               |v7|

**Comment by mariuszkrzaczkowski** [comment]
1. correct the configuration
2. What type is "Web service - Applications"
![image](https://user-images.githubusercontent.com/10198654/113664050-5dab1800-96ab-11eb-998e-e603238a24a7.png)

**Comment by willinmon** [comment]
I thought I had matched the settings on the demo.
Webservice  - Applications
![image](https://user-images.githubusercontent.com/31772589/113707486-f773c480-96ad-11eb-9ba9-bc0472912e64.png)
![image](https://user-images.githubusercontent.com/31772589/113707568-15d9c000-96ae-11eb-8f87-06cf47178374.png)
![image](https://user-images.githubusercontent.com/31772589/113707596-20945500-96ae-11eb-80c1-655c0e73cd84.png)

Webservice - Users
![image](https://user-images.githubusercontent.com/31772589/113707689-402b7d80-96ae-11eb-922a-e58ea536766f.png)
![image](https://user-images.githubusercontent.com/31772589/113707735-51748a00-96ae-11eb-9f7f-420ba4bae5fd.png)

**Comment by mariuszkrzaczkowski** [comment]
You get an error because you are using "Manage consents", authorization is always required here

**Comment by willinmon** [comment]
What would you suggest to use instead? Or would it be better to not use anything? Basically I have an api call that simulates an incoming call to the Yetiforce system. That is what I am trying to accomplish at least.

I just tried turning Manage Consents off (inactive) but I am still getting the 401 Unauthorized error. Any idea what I am doing wrong?

**Comment by mariuszkrzaczkowski** [comment]
Use only the Portal https://doc.yetiforce.com/api/?urls.primaryName=api%2FPortal

**Comment by willinmon** [comment]
Do I need to delete the Manage consents? When I make it inactive it still gives me the 401 error.

**Comment by mariuszkrzaczkowski** [comment]
yes

**Comment by willinmon** [comment]
Unfortunately I am still getting the error after deleting Manage consents. This is my api. It is pretty simple.

{"userName": "yetiforce", "password": "xxxxxxx", "params": []}

It's just a connect to get a token.

**Comment by willinmon** [comment]
Could there be a server setting that is causing it?

**Comment by willinmon** [comment]
I figured out the problem but not what is causing it. In the File \api\webservice\Portal\Users\Login.php line 222 the function post() is not getting any parameters so it can't check them against the portal user in the database. Can you tell me where this function is being called from so I can trace it back to why the variables are not being loaded?
public function post()
	{
		$db = \App\Db::getInstance('webservice');
		$row = (new \App\Db\Query())
			->from('w_#__portal_user')
			->where(['user_name' => $this->controller->request->get('userName'), 'status' => 1])
			->limit(1)->one($db);

**Comment by mariuszkrzaczkowski** [comment]
it requires debugging API client communication with CRM without access it will be difficult.
There may be various header errors in the request, an error in json's construction.
What do you use to connect to the API?

**Comment by willinmon** [comment]
I think that I have figured out the problem. The site is no longer getting the body of the api. Did the layout change for 6.1? Does this code look correct for the body?
{"userName": "yetiforce2a", "password": "yetiforce2a", "params": []}

I use both Postman and RESTClient to simulate an api call.

**Comment by mariuszkrzaczkowski** [comment]
See https://doc.yetiforce.com/api/#/Users/Api%5CPortal%5CUsers%5CLogin%3A%3Apost
