### ISSUE TITLE
[bug] Record numbering not working

### ISSUE THREAD

**Issue by IanMuller** [YetiForceCompany/YetiForceCRM#14504]
Software configuration>Standard modules>Modules – Installation>System settings>Settings>Module sequence numbering
This is not working in GitStable and in GitDeveloper

https://gitstable.yetiforce.com/index.php?parent=Settings&module=Vtiger&view=CustomRecordNumbering&sourceModule=Products

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/113663561-8bdc2800-96aa-11eb-9aa3-15cef7298af2.jpg)

**Comment by vovpff** [comment]
@IanMuller why this is not working?

I has checked on gitdev and this mechanism works as usual

![image](https://user-images.githubusercontent.com/8545791/113665397-15452780-96b6-11eb-9cce-cd571ccec217.png)

![image](https://user-images.githubusercontent.com/8545791/113665615-6d7c2980-96b6-11eb-941a-e9a821326520.png)

**Comment by waran70** [comment]
Does anyone dare to click link provided in this issue? **Obviously there is bug.**
@mariuszkrzaczkowski  - Marius, the way issue/bug is reported in perfect in my opinion, don't you really think otherwise?
