### ISSUE TITLE
[BUG] Search in Quotes

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1450]
It does not work Search a product or service to create a commercial offer

**Comment by konadrian** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html. Can you get a more info, url or print screens. Are you use current version?

**Comment by waw555** [comment]
![animation 1](https://cloud.githubusercontent.com/assets/1402355/8651383/e26520fa-2991-11e5-866f-a5ab9683094e.gif)

**Comment by bpabiszczak** [comment]
For me working properly, please check for the latest version: https://gitdeveloper.yetiforce.com
