### ISSUE TITLE
[BUG] Selecting a product in the offer

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1451]
Not working range of goods in the offer
![selectinquote](https://cloud.githubusercontent.com/assets/1402355/8612932/49ac4920-26f2-11e5-8771-2acaf3f35f49.JPG)

**Comment by konadrian** [comment]
We need more info about the problem

**Comment by waw555** [comment]
I chose the goods, all the fields are filled, and the main field and, accordingly, no write, it is necessary to choose a product

**Comment by konadrian** [comment]
Can you try to trigger this error on https://gitdeveloper.yetiforce.com/

**Comment by waw555** [comment]
I check the error, perhaps because of the import of the goods it happens

**Comment by bpabiszczak** [comment]
If you import such. Products need to upgrade labels. Please use this tool: https://gitdeveloper.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=2&fieldid=56
