### ISSUE TITLE
[BUG] Import Organizations

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1452]
The user is hidden behind a field
![import](https://cloud.githubusercontent.com/assets/1402355/8615017/a779ceea-2708-11e5-9520-fe5f6e9e74af.JPG)

**Comment by mariuszkrzaczkowski** [comment]
![import](https://cloud.githubusercontent.com/assets/10198654/8724836/0fdd3338-2bd1-11e5-87ba-394ecd2f69fb.png)
I checked it and everything is alright.
The users list is correct.
The appearance is correct.
Check it from the latest version and if you see any problems describe them more precisely
