### ISSUE TITLE
[bug] Auto assign dont work

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#14529]
Hi sir,
pls see the below gif .. the auto-assign is not working.. but in my system auto assign works but creates two records at the same time.

![autoassign](https://user-images.githubusercontent.com/54880467/114030909-76c4ec00-9898-11eb-8ae7-af611e13c409.gif)

any help is greatly appreciated..

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/114032493-a534ce00-987c-11eb-9a35-ae1cd89d3565.jpg)

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski  this is on gitstable and i have made a video .. i dont know how can i report it in a more descriptive way sir... sry

**Comment by vovpff** [comment]
On your video at workflow modification you check Execute task checkbox. This mean what this workflow triggered but will be executed in some time what described at the left of this checkbox (something about date af birth on your video). This is main fault what I can see now

**Comment by rioshaz** [comment]
@vovpff  yes i thought so too   i changed it to created time but still it doesnt work.. ... but my main problem is in my system it works but creates 2 records instead of one...

one goes to the auto-assigned user and one record is assigned to the creating user... very weird....

**Comment by vovpff** [comment]
You need to debug thi by yourself. I don't have experience with auto-assign

**Comment by mariuszkrzaczkowski** [comment]
The mechanism was rebuilt, it had numerous errors.
