### ISSUE TITLE
[BUG] Import Contacts

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1453]
The user is hidden behind a field
![import2](https://cloud.githubusercontent.com/assets/1402355/8615085/26d7fa18-2709-11e5-9fa7-206250df13bb.JPG)

**Comment by konadrian** [comment]
I tried to find this problem on https://gitdeveloper.yetiforce.com/ , but i couldnt see any problems. Can you check once more and try to recreate this error on current version  ttps://gitdeveloper.yetiforce.com/

**Comment by waw555** [comment]
There is a problem, try the steps under the Russian language
![import3](https://cloud.githubusercontent.com/assets/1402355/8646769/fbf10e88-296b-11e5-8708-e1d3fcc59fc7.JPG)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1452
