### ISSUE TITLE
[Security] Logs printing passwords

### ISSUE THREAD

**Issue by IanMuller** [YetiForceCompany/YetiForceCRM#14545]
User password is printed in open text to logs. This is pretty unwanted I guess?

$_POST = [
    'username' => 'Admin'
    'password' => 'adminpassword'
    'fingerprint' => '9704c540-eafd-4c33-b72b-b1f499397828'
]

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/f5e89369495bc71d9bc151f8f2a09760183bb835#diff-810203c6b1550fab210d119ab7c8e8d3bfbba7db238b83c7629a201bcd2c65cb
![image](https://user-images.githubusercontent.com/10198654/114502398-01587300-9c2c-11eb-9644-ca83cc7c895c.png)

**Comment by waran70** [comment]
No UI 99 here...   O.o

**Comment by mariuszkrzaczkowski** [comment]
It will be enabled by default for the user after the update
