### ISSUE TITLE
[bug]  Duplicate Auto assign records being created

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#14544]
I cannot fins this issue..

🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅-->

# 🐞 bug report

### ⁉️ Describe the bug

i have made full video please see... below

it is a bug because it is making duplicate entry into the system..

### 🔥 How to trigger the error

i have made a complete video please see..

![autoassigndupl](https://user-images.githubusercontent.com/54880467/114456634-b5410a80-9bfa-11eb-8ab3-79f0073f453a.gif)

### 👎 Actual Behavior

Duplocate record being made when auto assign is on.
### 👍 Expected Behavior

auto assign should work but the duplicate records should not be made...

### 👷 Testing

- [✔️ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

the video itself is from gitstable.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski  hi buddy can u pls help and guide me on this... will be thank full..
@KatarzynaUlichnowska

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski please check the same and help me if u can buddy

**Comment by mariuszkrzaczkowski** [comment]
the module has been rebuilt, test the new version.
