### ISSUE TITLE
[bug] Wrong links inside dashboard widget charts for referenced field

### ISSUE THREAD

**Issue by nerimic** [YetiForceCompany/YetiForceCRM#14554]
# 🐞 bug report

### ⁉️ Describe the bug

Links inside dashboard widget charts for referenced fields are wrong

### 🔥 How to trigger the error

1. Create a new Filter i.e. for Contacts or modify the existing "Test 1" adding "Member of":
![image](https://user-images.githubusercontent.com/45690654/114730476-330f2e00-9d41-11eb-90ac-a8ceace4a1a1.png)

2. Create a new Pie chart widget in dashboard choosing "Member of" as "Group by Field":
![image](https://user-images.githubusercontent.com/45690654/114730704-65209000-9d41-11eb-885a-53fc58714751.png)

3. Click inside the chart i.e. for "YetiForce Sp. z o.o.":
![image](https://user-images.githubusercontent.com/45690654/114730871-8a150300-9d41-11eb-961a-dbca566cf6a6.png)

4. See error in Contact List. The search is wrongly set using the ID of the related field instead of the relative text:
![image](https://user-images.githubusercontent.com/45690654/114731058-b4ff5700-9d41-11eb-94d7-0cf4846a3c63.png)

### 👎 Actual Behavior

https://gitstable.yetiforce.com/index.php?module=Contacts&view=List&viewname=124&search_params=%5B%5B%5B%22parent_id%22%2C%22a%22%2C117%5D%5D%5D

### 👍 Expected Behavior

https://gitstable.yetiforce.com/index.php?module=Contacts&view=List&viewname=124&search_params=%5B%5B%5B%22parent_id%22%2C%22a%22%2C%22YetiForce%20Sp.%20z%20o.o.%22%5D%5D%5D

### 👷 Testing

- [X] I confirm that I tested it at https://gitstable.yetiforce.com
- [X] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### ❗️ Inform the community if you solve the problem
in:
modules/Vtiger/models/ChartFilter.php

change:
$params = array_merge($this->searchParams, [[$this->groupFieldName, $operator, $row[$this->groupName]]]);

to:
$params = array_merge($this->searchParams, [[$this->groupFieldName, $operator, $groupValue]]);

**Comment by ojimenezt** [comment]
I have the same error, what solution was applied?

**Comment by rskrzypczak** [comment]
works in YF7
