### ISSUE TITLE
[bug] recordId missing in Vtiger_PDF_Model instance

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#14556]
# 🐞 bug report

PDF template record needs "recordId" to correctly parse record variables

### 🔥 Hint

after

https://github.com/YetiForceCompany/YetiForceCRM/blob/ed20faa67061e0dd6976f5a8046bbe7cb9d76f70/modules/com_vtiger_workflow/tasks/VTSendPdf.php#L60

add something like this

```PHP
$templateRecord->setVariable('recordId', (int) $recordModel->getId());
```

### 👎 Actual Behavior

record variables are not parsed

### 👍 Expected Behavior

correct parsing

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
Feel free to do a pull request :)

**Comment by rskrzypczak** [comment]
Thanks.
