### ISSUE TITLE
Webform. Fields aren't saving

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1455]
I have a problem with webform fields, whenever I am trying to create webform, form fields are not saving in form.
![form-](https://cloud.githubusercontent.com/assets/3193498/8615921/4cc82b42-26f7-11e5-9757-f28942e42d11.png)

**Comment by vishupatil** [comment]
hi konadrian, 
thanks for adding my issue. I think there is some problem with database table. I found some vtiger discussions on their forum with same issue. can you please let me know how many database tables should be created after deployment?

regards,
vishwajeet

**Comment by rskrzypczak** [comment]
Please test it: https://gitdeveloper.yetiforce.com
