### ISSUE TITLE
[bug] IllegalValue exception

### ISSUE THREAD

**Issue by aveblackmetalstudio** [YetiForceCompany/YetiForceCRM#14560]
Better to use **button** tag insted of **a** tag because it`s causes exception:

App\Exceptions\IllegalValue
ERR_NOT_ALLOWED_VALUE||mid||164%25

https://github.com/YetiForceCompany/YetiForceCRM/blob/bb23c1d8fed53bac8e259df3e4945aef74ecc3db/layouts/basic/modules/Vtiger/Pagination.tpl#L15

https://github.com/YetiForceCompany/YetiForceCRM/blob/bb23c1d8fed53bac8e259df3e4945aef74ecc3db/layouts/basic/modules/Vtiger/Pagination.tpl#L63

https://github.com/YetiForceCompany/YetiForceCRM/blob/bb23c1d8fed53bac8e259df3e4945aef74ecc3db/layouts/basic/modules/Vtiger/Pagination.tpl#L70

https://github.com/YetiForceCompany/YetiForceCRM/blob/bb23c1d8fed53bac8e259df3e4945aef74ecc3db/layouts/basic/modules/Vtiger/Pagination.tpl#L75

https://github.com/YetiForceCompany/YetiForceCRM/blob/bb23c1d8fed53bac8e259df3e4945aef74ecc3db/layouts/basic/modules/Vtiger/ListViewHeader.tpl#L124

https://github.com/YetiForceCompany/YetiForceCRM/blob/bb23c1d8fed53bac8e259df3e4945aef74ecc3db/layouts/basic/modules/Vtiger/ListViewHeader.tpl#L129

https://github.com/YetiForceCompany/YetiForceCRM/blob/bb23c1d8fed53bac8e259df3e4945aef74ecc3db/layouts/basic/modules/RecycleBin/ListViewHeader.tpl#L48

https://github.com/YetiForceCompany/YetiForceCRM/blob/bb23c1d8fed53bac8e259df3e4945aef74ecc3db/layouts/basic/modules/RecycleBin/ListViewHeader.tpl#L53

**Comment by rskrzypczak** [comment]
I don't get it.
You showed an exception for the variable "mid", but I don't see any relationship between the elements you listed here.
Can you describe how to trigger this error?

**Comment by aveblackmetalstudio** [comment]
1. Open [https://gitstable.yetiforce.com/](url)
2. In menu click **Accounts**
3. Click **Get total amount of records** in right top corner or click **Select all Accounts**
4. Now try to paginate (next/previous page)

Actions **Get total amount of records** and **Select all Accounts** add **"#"** character to end of url, because of using links insted of buttons.

> I don't get it.
> You showed an exception for the variable "mid", but I don't see any relationship between the elements you listed here.
> Can you describe how to trigger this error?
