### ISSUE TITLE
Product Name list does not popup in Quotation

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14566]
I am trying to create quotation and facing problem that product name list does not popup for selection. Not able to understand the problem.

![image](https://user-images.githubusercontent.com/12723595/115221661-87daec00-a127-11eb-870f-8738fbfb910e.png)

I have products created in module
![image](https://user-images.githubusercontent.com/12723595/115221707-93c6ae00-a127-11eb-9ada-61c4d9d0be02.png)

I checked same on gitstable and its working
![image](https://user-images.githubusercontent.com/12723595/115221927-cb355a80-a127-11eb-9f7b-8a2477d76640.png)

Kindly assist in the matter

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/115223631-4be65d80-a10c-11eb-9590-b5523c14bf5f.jpg)

**Comment by rskrzypczak** [comment]
Are your products active?
![image](https://user-images.githubusercontent.com/10221999/115226263-548c6300-a10f-11eb-945a-4397bb2ce5ac.png)

**Comment by rskrzypczak** [comment]
No answer and I don't see an error here, so I'm closing.
https://github.com/YetiForceCompany/YetiForceCRM/issues/13908

**Comment by JEEVAN28** [comment]
@rskrzypczak I am sorry, I was offline completely due to covid positive, and hence could not reply. Answer to your question is Yes, products are active. But this issue is resolved, from settings where control is removed from Processes -> Sales -> Limit Products related to Selected Opportunity.

We are not selecting products in Opportunity hence the issue was faced.

Thanks for your help

Jeevan Pendhari
