### ISSUE TITLE
[Improved] Holidays

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1456]
You need to add the following types of holidays:

International holiday
Orthodox celebration
National holiday
Historical celebration
World Celebration
Catholic festival

**Comment by bpabiszczak** [comment]
Currently we have two types of holidays, either national or religious... and we consider these types sufficient.
Regardless of the holiday, you can always assign it to either of these types [it's possible that they are not translated properly in some language], so at the moment we are not planning to add any other types of holidays.
