### ISSUE TITLE
[bug] table not exists

### ISSUE THREAD

**Issue by bakhtari** [YetiForceCompany/YetiForceCRM#14577]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sortorderid' in 'order clause' Failed to prepare SQL: SELECT `baseidid`, `baseid` FROM `vtiger_baseid` ORDER BY `sortorderid`

**Comment by rskrzypczak** [comment]
You probably created the wrong database table for a picklist field by yourself.
Learn how to report bugs because no one can help you from your description.
[How to report bugs](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs)
