### ISSUE TITLE
[bug] table vtiger_userid doesn't exist

### ISSUE THREAD

**Issue by bakhtari** [YetiForceCompany/YetiForceCRM#14576]
Hi
'appVersion' => '6.1.223',
'patchVersion' => '2021.04.21',
php:  7.4
message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'y1.vtiger_userid' doesn't exist Failed to prepare SQL: SELECT `useridid`, `userid` FROM `vtiger_userid` ORDER BY `sortorderid`
![image](https://user-images.githubusercontent.com/17001331/115588853-6e32d380-a2e4-11eb-8363-6e0869ddb68e.png)

**Comment by rskrzypczak** [comment]
I really don't know what you messed with your CRM system instance, but I don't see this type of bug in the system.
Learn how to report bugs: [How to report bugs](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs)
Feel free to create a new issue if you are able to complete the missing information.
