### ISSUE TITLE
[bug] RoundCube template button doesn't work

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#14584]
# 🐞 bug report

Template button doesn't work on click, in RoundCube.

### 🔥 How to trigger the error

https://user-images.githubusercontent.com/48508691/115728220-9bcf5980-a384-11eb-9c77-289ae0fe0b9a.mp4

### 👎 Actual Behavior

it doesn't work

### 👍 Expected Behavior

open on click

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13979  duplicate

**Comment by davide-alghi** [comment]
@mariuszkrzaczkowski tnx, I missed that
I'm going to close this
