### ISSUE TITLE
Improved Translation My mailbox

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1458]
![mymailbox](https://cloud.githubusercontent.com/assets/1402355/8617313/fbbab9b6-271b-11e5-89e6-3f7ea961be04.JPG)

**Comment by waw555** [comment]
No Good

Reopen Issue

Delete Variable

Why are these variables? The module can be removed?

A module will be on site support?

The module will be paid?

**Comment by konadrian** [comment]
The modul will not be paid, I removed unnecessary translations
