### ISSUE TITLE
[bug] Emails templates no loading

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#14594]
When trying to send email from whatever module I am unable to use emails templates. Button death.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/116032938-cfe69b00-a660-11eb-8284-a2e316e7381e.jpg)

**Comment by waran70** [comment]
Marius, my description of issue is clear like diamond. If you overwhelmed with acknowledging  and testing, don't waste time for copying / pasting  this weird reporting guide (as an image!). Again, I am totally clear and to get it reproduced it takes couple of seconds. Stop discouraging those  who spending time reporting.

**Comment by mariuszkrzaczkowski** [comment]
These diamonds of yours are so bright they blinded me and i have absolutely no clue what I should fix. All jokes aside, our rules on how to report errors are simple and clear as a diamond so I don't know what you don't understand.
PS. a few seconds for you, I don't even know what your version is, what view you're trying to send an email from etc. It all makes a difference.

**Comment by waran70** [comment]
Obviously we talking always about latest dev version as you guys don't service any of stable releases, kicking people to check dev app for reported issue. Again Marius, it takes few seconds to reproduce.

**Comment by mariuszkrzaczkowski** [comment]
you have a few seconds
https://user-images.githubusercontent.com/10198654/116144875-d4509980-a6dc-11eb-88e4-c63dd83223cd.mp4

**Comment by TonyM15** [comment]
Indeed weird. I checked it in win and linux on various browsers and here also not working.
Attaching scrshot with console errors
![image](https://user-images.githubusercontent.com/35586696/116159183-fd434f80-a719-11eb-9905-8a146e715181.png)

**Comment by mariuszkrzaczkowski** [comment]
Duplicate of #13979
