### ISSUE TITLE
[bug] Email Widget not showing related emails

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#14595]
Tested on custom module. 
Emails sent to/from address embedded in email field of this module are tied correctly to Related tab, but email widget is not seeing those emails.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/116032895-bfcebb80-a660-11eb-8d8e-1a14e13a9081.jpg)
