### ISSUE TITLE
[bug] Custom module | fields history and summary | updates - not working

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#14596]
Custom module | fields history and summary | updates - not working
Added both to Summary widget and it doesn't seem like it works as expected. 
Bug or miss-configuration?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/116032849-af1e4580-a660-11eb-82e4-7eeba3b07499.jpg)

**Comment by rskrzypczak** [comment]
Have you active the track changes?
![image](https://user-images.githubusercontent.com/10221999/116356524-ad3cb980-a7fb-11eb-9876-01f7dddf0add.png)
