### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by myanesdiazl9** [YetiForceCompany/YetiForceCRM#14590]
This has been happening to me for a month, the workflow does not complete.
![image](https://user-images.githubusercontent.com/68311999/115883853-4181d780-a41c-11eb-9d6a-23dcde479327.png)
I appreciate the help you can give me

**Comment by rskrzypczak** [comment]
Sure, only at the moment we can only read on coffee grounds :) 

I suppose one of the workflow actions is causing an error here.
Disable workflow actions one by one and monitor if the error still occurs.
Otherwise, you'll have to start debugging, but that's a developer job.

**Comment by myanesdiazl9** [comment]
Thank you very much for your help.
I'm going to do the tests

**Comment by myanesdiazl9** [comment]
It worked for me, thank you very much
