### ISSUE TITLE
[bug] not sume value in storage table

### ISSUE THREAD

**Issue by crawe1** [YetiForceCompany/YetiForceCRM#14598]
Version 5.3

Hello, 
When i want clic to sum quantity of product in Storage previev
The column exists in the vtiger_products table. Has anyone had such a case?

![image](https://user-images.githubusercontent.com/61950059/116077142-6d5bc200-a695-11eb-8894-fa04f98d73f5.png)

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version

**Comment by crawe1** [comment]
Problem occurs on two versions dev and stable,

I will add that another module in the Storage view module works correctly, only the summation in products module does not work properly.


When i trying to sum another column in this screen. Maybe any permisions ? 

Query in log:
Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vtiger_products.produkt_cena' in 'field list'
Failed to prepare SQL: SELECT SUM(vtiger_products.produkt_cena) FROM (SELECT DISTINCT `vtiger_products`.`productid` AS `id`, `u_yf_istorages_products`.`qtyinstock` AS `qtyproductinstock` FROM `vtiger_products` INNER JOIN `vtiger_crmentity` ON vtiger_products.productid = vtiger_crmentity.crmid INNER JOIN `u_yf_istorages_products` ON u_yf_istorages_products.relcrmid = vtiger_crmentity.crmid WHERE (`vtiger_crmentity`.`deleted`=:qp0) AND (`u_yf_istorages_products`.`crmid`=:qp1)) `c` in /var/www/rusztowania/vendor/yetiforce/yii2/db/Command.php:264
Stack trace:
#0 /var/www/rusztowania/vendor/yetiforce/yii2/db/Command.php(1153): yii\db\Command->prepare(true)
#1 /var/www/rusztowania/vendor/yetiforce/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
#2 /var/www/rusztowania/app/Db/Query.php(143): yii\db\Command->queryScalar()
#3 /var/www/rusztowania/vendor/yetiforce/yii2/db/Query.php(372): App\Db\Query->queryScalar('SUM(vtiger_prod...', NULL)
#4 /var/www/rusztowania/modules/Vtiger/actions/RelationAjax.php(471): yii\db\Query->sum('vtiger_products...')
#5 /var/www/rusztowania/app/Controller/ExposeMethod.php(65): Vtiger_RelationAjax_Action->calculate(Object(App\Request))
#6 /var/www/rusztowania/app/Controller/ExposeMethod.php(78): Vtiger_RelationAjax_Action->invokeExposedMethod('calculate', Object(App\Request))
#7 /var/www/rusztowania/include/main/WebUI.php(187): Vtiger_RelationAjax_Action->process(Object(App\Request))
#8 /var/www/rusztowania/index.php(28): Vtiger_WebUI->process(Object(App\Request))
#9 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'vtiger_products.produkt_cena' in 'field list'
)

simple query 
![image](https://user-images.githubusercontent.com/61950059/116194795-9df13980-a731-11eb-90a5-7d418879e7de.png)

but I will say again that in the second tab everything works fine. The problem is only in the products tab in the storage module.

second tab:
![image](https://user-images.githubusercontent.com/61950059/116195395-70f15680-a732-11eb-9b3b-7a684016e010.png)

**Comment by crawe1** [comment]
Hello,

I install new clean yeti instance 5.3. and i must sed yours fix not work:

screen is this same:
![image](https://user-images.githubusercontent.com/61950059/116361715-8da88f80-a801-11eb-8e4d-218d3217d5f7.png)

1) i change uitype from 1 to 7 in vtiger_fields table -> not work
2) restore in table vtiger_fields previous value on 1,  add your fix (add ut type 1) getUIType(), [1, 71, 7, 317, 8] -> not work

Only on this module in this place:
Storage -> Products
in 
Storage -> WZ every is ok.

**Comment by mariuszkrzaczkowski** [comment]
it only works on the development version and probably 6.1

**Comment by crawe1** [comment]
Ok you have right in 6.1 is ok sume of products in products module 
but not sume value from storage module:
![image](https://user-images.githubusercontent.com/61950059/116375106-3d382e80-a80f-11eb-8ae0-3a4b97068b32.png)

**Comment by areksolek** [comment]
The introduced fix doesn't allow to sum the values for the qtyproductinstock field because it is a custom field. In the future we will look at the possibility to sum such fields.
![image](https://user-images.githubusercontent.com/25615135/116390066-f7369700-a81d-11eb-86e0-46122baa23e3.png)

**Comment by crawe1** [comment]
Ok, thank you for your help, do you know what to change before version 6.1 regarding the summation of fields (standard not custom) in storage module in products? In a foreign time I can't upgrade to version 6.1. (but try) I'd like to change that in version 5.3. Do you have any changelog? 

ok i found this in RelationAjax.php
