### ISSUE TITLE
License

### ISSUE THREAD

**Issue by myanesdiazl9** [YetiForceCompany/YetiForceCRM#14618]
We acquired the YetiForceDevelopmentSupport license, please could you tell me how it works.
I appreciate your help
![image](https://user-images.githubusercontent.com/68311999/116636968-34874b80-a928-11eb-8bcf-4d858958a608.png)

**Comment by rskrzypczak** [comment]
Send these types of questions directly to YetiForce: [Contact](https://yetiforce.com/en/company/contact)
