### ISSUE TITLE
[bug] add_time(timefield, minutes) function in workflows not working

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#14647]
I checked few scenarios and it seems like this date/time function dont want work

**Comment by waran70** [comment]
Confirmed add_time(createdtime, 5) is not triggering
createdtime is a system field, but it also stuck on custom time/date fields. 
No logs

**Comment by Marshal4582** [comment]
in both stable and git created workflows with add_time(timefield, minutes) and yes, it is NOT working.

**Comment by z0lo13** [comment]
You guys doing something wrong... it all works. Both dev & stable

add_time(createdtime, 5) - will not work as createdtime is not a time field, it does not make sense. 
It is datetime (UiType: 70) and you need time (UiType: 14)

https://user-images.githubusercontent.com/23143958/117844379-a11a1880-b24d-11eb-9dba-3231428f1500.mp4

**Comment by konadrian** [comment]
As @z0lo13 mentioned it works only with time fields. I closed the topic
