### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by M3rofio** [YetiForceCompany/YetiForceCRM#14646]
hello I have installed Softaculos in in-motion hosting dedicated server
I did a sub domain for yeti example.XXXX.com and filled the detail with the admin account and installed yetiforce 6.1.0  it when I log in with the user I filled it won't go thru it bounces back to the user login page

**Comment by vovpff** [comment]
Let's clean cookies and browser cache

**Comment by M3rofio** [comment]
I did that now and retry it and its the same  and now a did new installations fresh and used different name

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/117609599-9b92d480-b160-11eb-90e1-6eb1cab15245.jpg)

**Comment by z0lo13** [comment]
@M3rofio 
Most likely you have php misconfiguration, as you can't login to crm to provide system configuration you can find a list of php extensions in phpinfo and compare it to the one on gitstable/dev
