### ISSUE TITLE
Auto Assign created duplicate records[bug] 

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#14645]
hi isr,
when using the auto assign feature for creating new records ,, it creates two records at the same, time.
i have tested this on gitstable, made a video and the bug is there also..

![autoassigndupl](https://user-images.githubusercontent.com/54880467/117532711-7e49f300-b006-11eb-8ff0-4aa6b843e503.gif)

please help, as we trust in yetiforce dedicated team and their commitment for this project,

**Comment by mariuszkrzaczkowski** [comment]
the module has been rebuilt, test the new version.
