### ISSUE TITLE
[bug] [fix] HOW to DISABLE Yeti-RBL COMPLETELY? + Temp Solution for slow roundcube.

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#14650]
Hello Yeti Team,

Thank you for such an amazing project. 

We understand that introducing such a module as RBL is a very nice feature to have, however because of this integration the performance of loading emails and displaying them is dramatically low as pointed out by @mariuszkrzaczkowski in a few issues, as a solution for this is to wait until 6.2.0 which will have an option to turn off the RBL check.

However, today the Roundcube on all yeti instances (10 different instances, with +- different hardware) went very slow, we found out that it was due to attachments, specifically the ones more than 10 MB, some of the instances just hang up. The roundcube works blazingly fast after disabling yetiforce plugin for roundcube. At the same time from issues i have found out the possible solution to comment out the line 32 in yetiforce.php file. It does helps, the performance increase in about 5 times, however, it hangs the instances if an email with heavy attachments is loaded. 

I have commented out mail analysis and all similar functions which send requests to RBL,  however, it is definitely not the best way to do it.
Please expand the functionality of disabling the RBL service, in order for us to  be able to disable it completely (0 Request sent to RBL server)

After debugging below are the results:

**TEMP SOLUTION: or anyone having same issue**
1. The :32 line is commented out in yetiforce.php
2. After debugging I have determined that the issue of why the instance hangs when it contains a large attachment. 
    modules/OSSMail/views/MailActionBar.php :35 CheckMailExist function

3. as a result refers modules/OSSMailView/models/Record.php :321

4. Next investigation pointed out that OSSMail_Record_Model::getMail function does download attachments, and FullMode is enabled by default.  See below code as a reference. 
modules/OSSMail/models/Record.php
```
/**
	 * @param resource $mbox
	 * @param int      $id
	 * @param int      $msgno
	 * @param bool     $fullMode
	 *
	 * @return bool|\OSSMail_Mail_Model
	 */
	public static function getMail($mbox, $id, $msgno = false, bool $fullMode = true)
	{
		if (!$msgno) {
			\App\Log::beginProfile(__METHOD__ . '|imap_msgno', 'Mail|IMAP');
			$msgno = imap_msgno($mbox, $id);
			\App\Log::endProfile(__METHOD__ . '|imap_msgno', 'Mail|IMAP');
		}
		if (!$id) {
			\App\Log::beginProfile(__METHOD__ . '|imap_uid', 'Mail|IMAP');
			$id = imap_uid($mbox, $msgno);
			\App\Log::endProfile(__METHOD__ . '|imap_uid', 'Mail|IMAP');
		}
		if (!$msgno) {
			return false;
		}
		\App\Log::beginProfile(__METHOD__ . '|imap_headerinfo', 'Mail|IMAP');
		$header = imap_headerinfo($mbox, $msgno);
		\App\Log::endProfile(__METHOD__ . '|imap_headerinfo', 'Mail|IMAP');
		$messageId = '';
		if (property_exists($header, 'message_id')) {
			$messageId = $header->message_id;
		}
		$mail = new OSSMail_Mail_Model();
		$mail->set('header', $header);
		$mail->set('id', $id);
		$mail->set('Msgno', $header->Msgno);
		$mail->set('message_id', $messageId ? \App\Purifier::purifyByType($messageId, 'MailId') : '');
		$mail->set('to_email', \App\Purifier::purify($mail->getEmail('to')));
		$mail->set('from_email', \App\Purifier::purify($mail->getEmail('from')));
		$mail->set('reply_toaddress', \App\Purifier::purify($mail->getEmail('reply_to')));
		$mail->set('cc_email', \App\Purifier::purify($mail->getEmail('cc')));
		$mail->set('bcc_email', \App\Purifier::purify($mail->getEmail('bcc')));
		$mail->set('subject', isset($header->subject) ? \App\TextParser::textTruncate(\App\Purifier::purify(self::decodeText($header->subject)), 65535, false) : '');
		$mail->set('date', date('Y-m-d H:i:s', $header->udate));
		if ($fullMode) {
			$structure = self::getBodyAttach($mbox, $id, $msgno);
			$mail->set('body', $structure['body']);
			$mail->set('attachments', $structure['attachment']);

			$clean = '';
			\App\Log::beginProfile(__METHOD__ . '|imap_fetch_overview', 'Mail|IMAP');
			$msgs = imap_fetch_overview($mbox, $msgno);
			\App\Log::endProfile(__METHOD__ . '|imap_fetch_overview', 'Mail|IMAP');

			foreach ($msgs as $msg) {
				\App\Log::beginProfile(__METHOD__ . '|imap_fetchheader', 'Mail|IMAP');
				$clean .= imap_fetchheader($mbox, $msg->msgno);
				\App\Log::endProfile(__METHOD__ . '|imap_fetchheader', 'Mail|IMAP');
			}
			$mail->set('clean', $clean);
		}
		return $mail;
	}
```

5. I don't know is it a typo or intend use but line 323 of "modules/OSSMailView/models/Record.php" does not turn off the full mode and as a result, the attachments being downloaded. 
Replacing
  
`$mail = OSSMail_Record_Model::getMail($mbox, $uid, false);`   
with 
`$mail = OSSMail_Record_Model::getMail($mbox, $uid, false, false);`

6. Fixed the problem when the system hangs when previewing emails with large attachments, however, i am not sure if the other functions will be impacted by disabling "Full Mode"

7. What are the possible outcomes if fullMode disabled while calling checkMailExist from OSSMailView_Record_Model? Will the other functions won't work correctly? As I was not able to find any use of the attachment portion for checking if mail exists in the database.

I hope the above debugging and info will help you improve the yetiforce plugin for roundcube as well as RBL checks.

**Comment by waran70** [comment]
Don't disable! I think RBL pay commission ;-)
https://github.com/YetiForceCompany/YetiForceCRM/issues/14181

**Comment by z0lo13** [comment]
> Don't disable! I think RBL pay commission ;-)
> #14181

Your comment does not make sense, as 6.2.0 and dev version will have an option to disable the RBL check.
https://github.com/YetiForceCompany/YetiForceCRM/issues/14489#issuecomment-813052569

Also, I don't really know what was the point of the conversation in #114181, you've sent them an email, your IP got blocked for spam, @bpabiszczak offered to unblock your IP free of charge, (NO you don't need to pay 5Euro in cases when it was not intentional), which you denied and just said that Toptal freelance support is better :-D

I guess you just bored man.

P.S.
It is a point to have it enabled, but not when the email client non-usable if the attachment is more than 15 MB.

**Comment by waran70** [comment]
@z0lo13: It was response to email from yetiforce! Nobody spammed 'em, or even sent cold email. Totally legit and clean of any spam records address was dumped in RBL and we have been blackmailed with 5 Euro to get IP back on track, so yetiforce stuff can in their kindness read our business inquiry. 
In the next step offering me unblocking my IP for free is a sick thing. 
We talking about business case where customers (like mine)  don't bother with guys who creating blockers for them and who extending time of resolving case. 

Are you sure I am bored man? Little analysis and you got right picture.
