### ISSUE TITLE
[bug] Scheduled workflow set value dialog - various behaviour

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#14658]
I have catch up with https://github.com/YetiForceCompany/YetiForceCRM/issues/14649
and detected as follows:

# 🐞 bug report

Test on currency fields.
field1
field2

1. Create workflow with execution "Creating record" 
2. Choose condition on field1 - now when you click right column field "Set value" dialog pops-up where we can choose Raw text, Field, or Expression.
3. Choose field2 form "Field" option

Above scenario cannot be reproduced with workflow execution set on " Execution schedule (defined time intervals)"
dialog "Set value" would not popup and workflow will not trigger if we set in dialog fieldname (for instance here field2)

To check error you need to reproduce above scenario 
or 

check it on gitdev: https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=Edit&record=85

**Comment by konadrian** [comment]
I can't reproduce this error. The topic is closed
