### ISSUE TITLE
[bug] Workflow 'more than days ago' not work

### ISSUE THREAD

**Issue by MaxPegankin** [YetiForceCompany/YetiForceCRM#14672]
# 🐞 bug report

### ⁉️ Describe the bug

In workflow for Project Tasks when choose condition Target Date 'more than days ago' the task triggers for all Project Task, regardless of this condition. Project Tasks before Target Date and after Target Date are all triggered.    

### 🔥 How to trigger the error

The possible bug can only be triggered when Execution schedule (defined time intervals) is selected.
If use Every time a record is saved (eg. creating, modifying) the workflow works correctly.

1. Go to 'Workflows' for Project Tasks 
2. Use Execution schedule (defined time intervals) 
3. In "Choose filter conditions" use something like this:
![image](https://user-images.githubusercontent.com/54612661/118428789-cbaf1a00-b702-11eb-939d-d5c7f046de90.png)
4.  Send email with CRM link of the triggered Project Task
5.  On the sceduled time receive emails with All existing Project Tasks 

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
![ConfReport](https://user-images.githubusercontent.com/54612661/118429056-6576c700-b703-11eb-9880-82a363e69da2.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by davide-alghi** [comment]
Hi @Maxpeg,
'more than days ago' condition works fine.

**more than days ago**: it's executed if ("date field value" <= "workflow execution date" - "n-days")
**less than days ago**: it's executed if ("workflow execution date" - "n-days" <= "date field value") AND ("date field value" <= "workflow execution date")

in your case the workflow is executed if "Target End Date" <= a day ago [ie "workflow execution date" - 1]

pls also take a look here https://github.com/YetiForceCompany/YetiForceCRM/discussions/14635#discussioncomment-730176

if you are familiar with PHP you can "interpret" the behavior of the conditions here https://github.com/YetiForceCompany/YetiForceCRM/blob/38045d0fb40433cb5170475bdcfb80a18baf000f/modules/com_vtiger_workflow/VTJsonCondition.php#L401

**Comment by MaxPegankin** [comment]
@davide-alghi
**more than days ago** works fine itself, I have no bug when use it with **Every time a record is saved (eg. creating, modifying)**
But I have a bug when I use with **Execution schedule (defined time intervals)**

**Comment by davide-alghi** [comment]
@Maxpeg,
I just tried with **Execution schedule (defined time intervals) - 5 mins** and it works fine

YF 6.1 SP 8

**Comment by MaxPegankin** [comment]
@davide-alghi 
I just tried it too, and I have the bug. 
I run YF 6.1 SP **7** , can't find SP8.

It look like the problem is on my side, do you have any sugestions how I can fix it?
I suspect the system takes Target End Day wrongly, like zeros, so any date is later than it. Do you have ideas how I can check it?

**Comment by davide-alghi** [comment]
@Maxpeg first of all install SP8: Logs/Updates in the backend

**Comment by MaxPegankin** [comment]
@davide-alghi 
I upgraded up to SP8, unfortunatelly the problem remains. 



https://github.com/YetiForceCompany/YetiForceCRM/blob/38045d0fb40433cb5170475bdcfb80a18baf000f/modules/com_vtiger_workflow/VTJsonCondition.php#L144

This function you mentioned is not used, I renamed it like this, but workflow still works, looks like conditions don't execute here. 

public function checkCondition_false(Vtiger_Record_Model $recordModel, $cond, Vtiger_Record_Model $referredRecordModel = null)

Is there any other place where the conditions can be execute?

**Comment by davide-alghi** [comment]
Hi @Maxpeg,

> I upgraded up to SP8,

great

> unfortunatelly the problem remains.

a step at a time

> I renamed it like this, but workflow still works, looks like conditions don't execute here

this is not the best way to debug/check: to debug enable debugging in config/Debug.php
yes the workflow appears to be running correctly, but it is not so
if you wanna verify my words, rename "checkCondition()" function to "checkCondition_false()" and change "Specify when to execute this workflow" from "Execution schedule (defined time intervals)" to "Every time a record is saved (eg. creating, modifying)". Now edit, modify and save a Project Task: you'll receive this error
![Schermata da 2021-05-18 07-44-27](https://user-images.githubusercontent.com/48508691/118597416-ee960880-b7ac-11eb-9f60-00d0d41b0ffb.png)

assuming that condition is
![118428789-cbaf1a00-b702-11eb-939d-d5c7f046de90](https://user-images.githubusercontent.com/48508691/118598479-687ac180-b7ae-11eb-8d79-b4d20beb3847.png)

my questions are:

1. what is the "Target End Date" value of "Project Task" you're testing with?
2. what is the task(s) type you set in workflow? [I checked with "Send email template" workflow task]

**Comment by MaxPegankin** [comment]
@davide-alghi 
Correct, there is an error when use "Every time a record is saved (eg. creating, modifying)" with function name "checkCondition_false()" 
However, I see no errors in logs when use with "Execution schedule (defined time intervals)", like it goes around somehow, maybe via cron the trace is different. 

0. Complete condition is this:
![image](https://user-images.githubusercontent.com/54612661/118604201-76990400-b7e7-11eb-9fc4-ea3a0167edf6.png)
1. There are many records with "Target End Date", some records values are in the past, some in the future. I receive them all. 
   "Target End Date" Field type: date (UiType: 5)
2. Right,  "Send email template".

**Comment by mariuszkrzaczkowski** [comment]
you do not see errors because you do not save them, correct the server configuration

![image](https://user-images.githubusercontent.com/10198654/118605889-0e322e80-b7b7-11eb-8701-78109112abf6.png)

**Comment by MaxPegankin** [comment]
@mariuszkrzaczkowski 
My bad, how can I fix it?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/9ee77253f4cc5681dc4ccdd6a329338b60de74f4/tests/setup/php/prod.ini#L4

**Comment by MaxPegankin** [comment]
@mariuszkrzaczkowski 
Done, thank you for the hint.
![image](https://user-images.githubusercontent.com/54612661/118610592-810acc00-b7ee-11eb-8417-285af1d4b264.png)

**Comment by davide-alghi** [comment]
@Maxpeg,
I see you have many conditions there, so it is better to proceed by initially eliminating some conditions and adding them one at a time.

before all, enable debugging:

1. in config/Debug.php set
```public static $LOG_TO_FILE = true;```
and
```public static $LOG_LEVELS = 3;```
2. delete content from file
```cache/logs/system.log```
and save, if it exists 

here the steps:

1. choose a "Project Task" (in list view by filtering) with "Target End Date" value in the future
2. remove, temporary, all conditions on "Status" field
3. add a discriminant condition to work (only) with the chosen "Project Task" record: for example, append "XXXX" string to the "Project Task Name" of chosen record and then add, as first, the, temporary, condition
![Schermata da 2021-05-18 09-45-53](https://user-images.githubusercontent.com/48508691/118612241-e0041d00-b7bd-11eb-803a-6512cabf2c01.png)
4. wait the time required to CRON and Workflow execution: the email (template) **should not be sent** - check if in ```cache/logs/system.log``` there is any error
5. gradually add the other conditions on the Status field, one at a time

after try the same above steps choosing a "Project Task" record with "Target End Date" value in the past (2 or more days ago) - in this case the email (template) **should be sent**

at the end disable debugging with
```public static $LOG_TO_FILE = false;```

**Comment by MaxPegankin** [comment]
@davide-alghi 
![image](https://user-images.githubusercontent.com/54612661/118619961-a3551780-b7f7-11eb-8e70-d705c7c3ce8e.png)
I received an email from this XXXX task with Target End Date 2021-07-05
system.log have an error about it, can it lead somewhere?
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6499663/system.log)

**Comment by MaxPegankin** [comment]
@davide-alghi 
I really don't have operatorL(l) in  App\Conditions\QueryFields\DateField, should I add it?

**Comment by davide-alghi** [comment]
that is very very strange, no you shouldn't

just a question: have you done some hand customization of the YF core code in the past?

**Comment by MaxPegankin** [comment]
@davide-alghi 
Well, system is two years old, started from YF 5.1. 
I didn't make any global customizations, added some custom modules, some custom invoke functions, didn't touch the core, don't understand there, who calls who and from where.  
There were some problems with updates on the way from YF 5.1 to YF 6.1, which I fixed by hands, maybe some minor problems still exist.  

Probably if install YF6.1 anew it will help. Reinstall the system with every new version is remedy for any problem :)
I think it is already imposible to migrate, too many custom modules. I feel that after a migration attempt the new system will have more problem than the old one.

Is there any way I can fix that "operatorL(l)" error?


By the way, I have an error in php_error.log:
[18-May-2021 18:25:02 Asia/Brunei] PHP Fatal error:  require_once(): Failed opening required 'modules//.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/yetiforce/html/include/CRMEntity.php on line 60

It is looks serious, do you have any idea how I can fix it?

**Comment by davide-alghi** [comment]
> Probably if install YF6.1 anew it will help. Reinstall the system with every new version is remedy for any problem :)
> I think it is already imposible to migrate, too many custom modules. I feel that after a migration attempt the new system will have more problem than the old one.

I discourage this: it's a very big job

> Is there any way I can fix that "operatorL(l)" error?

this is very strange, because the operatorL() function is in another class
https://github.com/YetiForceCompany/YetiForceCRM/blob/3ddea8f3e0ca130546e83eeb7bb2132d9a4a5d70/app/Conditions/RecordFields/BaseField.php#L181


> By the way, I have an error in php_error.log:
> [18-May-2021 18:25:02 Asia/Brunei] PHP Fatal error: require_once(): Failed opening required 'modules//.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/yetiforce/html/include/CRMEntity.php on line 60

I think this is not related to the problem: time is different

what I can suggest you is

1. perform a fresh installation of YF 6.1 + SP8, then copy the (empty) fresh installation to the computer desktop
2. also make a copy of the YF production instance to the computer desktop
3. compare the two folders: production instance and fresh instance
4. in this way you can check if there is something wrong in folders, files and code

I can suggest Meld to compare folders - https://meldmerge.org/

**Comment by MaxPegankin** [comment]
@davide-alghi 
![image](https://user-images.githubusercontent.com/54612661/118784863-efb95980-b8c2-11eb-8484-d923bfcbf1e4.png)
Done, with this tool I cleared minor problems accumulated with time, unfortunately the main problem stays. 

Thank you for your help, if you have any further ideas how to fix it, please let me know.

**Comment by MaxPegankin** [comment]
@davide-alghi 
I copied operatorL() function into the DateField class and now it is working. I hope it won't affect other functionality.
