### ISSUE TITLE
Probably dead code

### ISSUE THREAD

**Issue by aveblackmetalstudio** [YetiForceCompany/YetiForceCRM#14675]
https://github.com/YetiForceCompany/YetiForceCRM/blob/068c292b8b18bd171537dbe8111e66a60586b7ed/modules/Notification/actions/Notification.php#L111

https://github.com/YetiForceCompany/YetiForceCRM/blob/068c292b8b18bd171537dbe8111e66a60586b7ed/modules/Notification/models/Module.php#L64

**Comment by rskrzypczak** [comment]
Thanks.
