### ISSUE TITLE
[bug] PDF Generation throws Error for Quote

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14704]
We have created PDF for Quote. While generating Quote it throws below error
![image](https://user-images.githubusercontent.com/12723595/119155203-8aa36680-ba70-11eb-8fb5-25ed5019b2d5.png)

I checked on https://gitdeveloper.yetiforce.com/index.php?module=SQuotes&action=PDF&mode=generate as per instruction on https://github.com/YetiForceCompany/YetiForceCRM/issues/12014

it also throws below error
![image](https://user-images.githubusercontent.com/12723595/119155345-b58dba80-ba70-11eb-9695-aecce324f6f8.png)

Kindly assist in the matter.

Regards
Jeevan Pendhari

**Comment by davide-alghi** [comment]
Hi @JEEVAN28,
it looks like some style is not interpreted by the YF PDF engine.
pls attach PDF template: that can help

**Comment by JEEVAN28** [comment]
@davide-alghi correctly said, issue was with styles. I corrected them properly and issue resolved. Thanks for the help.
