### ISSUE TITLE
[bug] Image cannot be deleted

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#14711]
I cannot use image field as I cannot delete uploaded image (cannot download too)

Image of standard quality, 800x600 jpeg.

Checked on yetiforce online demo and git

I work on windows 10 and server 2019

**Comment by rskrzypczak** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/14331.
You need to provide more info regarding your configuration, you see it works on the yetiforce demo: https://github.com/YetiForceCompany/YetiForceCRM/issues/14331#issuecomment-811722692

**Comment by s2b-git** [comment]
Hi :-)

I checked here: https://gitdevelo
![Uploading image-bug.gif…]()
per.yetiforce.com/index.php?module=MultiCompany&view=Edit&parent=76&mid=152&record=1

GIF attached. I not even allows upload image here.

**Comment by rskrzypczak** [comment]
Fix a broken links

**Comment by s2b-git** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=MultiCompany&view=Edit&parent=76&mid=152&record=1


![image-bug](https://user-images.githubusercontent.com/84110093/119315571-2a930700-bca0-11eb-9f75-70a43c46275a.gif)

**Comment by rskrzypczak** [comment]
This is not a bug.
As the message says, you can only have one file.
So delete the previous one if you want to add a new one.
![image](https://user-images.githubusercontent.com/10221999/119321709-39b48d80-bc7d-11eb-83dd-71937a1bcd18.png)

**Comment by s2b-git** [comment]
But there is no image in this field. It is empty, even-though it is returning error. Please try, and you can reproduce it :-) 
Well, there is something but invisible. Anyway if I try to delete it, it not allowing. Again: I am on Windows 10
