### ISSUE TITLE
[Bug] CRON_MAX_NUMBERS_SENDING_MAILS preference isn't working

### ISSUE THREAD

**Issue by aveblackmetalstudio** [YetiForceCompany/YetiForceCRM#14723]
**CRON_MAX_NUMBERS_SENDING_MAILS** preference isn't working

https://github.com/YetiForceCompany/YetiForceCRM/blob/4da92052133b8b2ff02fefa47d55d77e7fc28ea4/modules/Vtiger/crons/Mailer.php#L20-L21

**Comment by rskrzypczak** [comment]
I disagree. It works, it might look weird, but it works :)
If you have an idea for a better solution, feel free to do a pull request.

**Comment by aveblackmetalstudio** [comment]
> I disagree. It works, it might look weird, but it works :)
> If you have an idea for a better solution, feel free to do a pull request.

@mariuszkrzaczkowski 

How it could work, if there is limit 20 on query.
Otherwise, there is no sense in such preference.

**Comment by rskrzypczak** [comment]
I suppose you haven't tested it :)
I admit the code isn't perfect, but it more or less works.
P.S. this query is in a loop.

**Comment by aveblackmetalstudio** [comment]
@mariuszkrzaczkowski
@rskrzypczak
> I suppose you haven't tested it :) I admit the code isn't perfect, but it more or less works. P.S. this query is in a loop.

I was sure it didn't work without testing. It follows from the documentation of the batch method.
Now i tested it and CRON_MAX_NUMBERS_SENDING_MAILS preference isn't working.

You could fix it changing this line from:
`$query = (new \App\Db\Query())->from('s_#__mail_queue')->where(['status' => 1])->orderBy(['priority' => SORT_DESC, 'id' => SORT_ASC])->limit(20);`

to:
`$query = (new \App\Db\Query())->from('s_#__mail_queue')->where(['status' => 1])->orderBy(['priority' => SORT_DESC, 'id' => SORT_ASC])->limit($limit);`
