### ISSUE TITLE
Issue in SMTP Configuration

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14722]
Hello,

I am trying to add SMTP on my local server, when I set all parameters and press save button, system hangs up for longer time, no error is thrown.

I am trying for GMAIL configuration. I had earlier configured my another email id for gmail. Even mails are sent from this email id daily via workflow. but if I try to edit this configuration also on save system hangs up like below image.

![image](https://user-images.githubusercontent.com/12723595/119499715-9b135400-bd84-11eb-94e0-ff95c4d19268.png)

I tried to configure on gitdeveloper and I get below error (on local server no such error is shown)
SMTP ERROR: Failed to connect to server: Connection refused (111)

same settings used via roundcube is working on my local server, mail scanner is also working.

what can be the issue ?

Thanks
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d.jpg)

**Comment by JEEVAN28** [comment]
# 🐞 bug report

### ⁉️ **Add Record in SMTP Configuration Hangs up on Local Server for indefinite time**


I have used same ID and Password via RoundCube and for MailScanner, it works. but while configuring SMTP Configuration after save button, web page hang up and finally need to close. SMTP Configuration is not Saved. No error thrown.


This issue is related to GMAIL configuration only, when used other provider email id configuration saved properly.



### 🔥 How to trigger the error


![image](https://user-images.githubusercontent.com/12723595/119534711-d6257f80-bda4-11eb-9b62-58edbe6c4d8a.png)

Steps to reproduce the behavior:

1. Go to 'System Settings'
2. Click on 'Mail Tools'
3. Scroll down to 'SMTP Configuration'
4. Add SMTP Record for GMAIL with app password (we are not using less secure app due to security reasons)
5. SMTP connection is to setup


### 👎 Actual Behavior
On Save web page hangs up on Local Server, no error is shown
On gitdeveloper.yetiforce.com below error is shown
SMTP ERROR: Failed to connect to server: Connection refused (111)



### 👍 Expected Behavior
SMTP Configuration should save



### 👷 Testing



- [ Y] I confirm that I tested it at https://gitstable.yetiforce.com
- [ Y] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration



### 📝 PHP/Apache/Nginx/Browser/CRM Logs



### 🌍 Your Environment




| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0
| Web server (name and version)       |    apache 2.4.46            |
| PHP                                 |           7.3     |
| Browser (name and version)          |     chrome           |
| Operating System (name and version) |        linux        |
| Database (name and version)         |    mysql 8.0            |
| Service Pack version                |          6.10      |

### ❓ Additional context

Add any other context about the problem here.



### ❗️ Inform the community if you solve the problem

**Comment by JEEVAN28** [comment]
Don't know but this is working now. closing task.
