### ISSUE TITLE
[bug] problems viewing tickets from another user

### ISSUE THREAD

**Issue by MixTecnico** [YetiForceCompany/YetiForceCRM#14725]
good guys I have a problem that must be silly but I can't find a solution .... in the incident ticket system the main user creates these incidents, but for a month the other users have not seen the tickets created, the users. They are administrators too and the permissions are in the same group and role as the main user, any ideas?

# 🐞 bug report

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
If aminaistrotor does not see entries, you must have messed up the code yourself.
This is not a bug in the base application, so let's move on to the discussion.
