### ISSUE TITLE
[error] - Error OSSMail_Record_Model::imapConnect({outlook.office365.com:993/imap}): [CLOSED] IMAP connection broken (server response)

### ISSUE THREAD

**Issue by Jeroenleender** [YetiForceCompany/YetiForceCRM#14731]
Hello and first of all thx for the best open source crm project i could find!

After that being said i have been troubleshooting the install for some days to make sure the environment is as close to perfect as i can get it on CentOS 7.

System warnings show everything green!
Server configuration system settings show all good except for Error logs (error_log) which is empty for apache as well as cron.
Cronjob has been setup using curl since the other methods would use cli and different php version, after changing to curl even cron shows all good!

I have configured a mailbox for Roundcube option from office365 and that works all fine!
I have configured smtp server and the server sends every mail. (the only issue is that when i send an email to a test user i can't find back that email in the crm system anywhere except in the sent items folder in roundcube

I tried to setup mailscanner which is basically the same email as being used for smtp and roundcube and it fails with records created in the logs about them as shown below, hopefully anyone can shed a light on this issue(s) so i can fix emails not being saved and have a working emailscanner.

**errors.log**
`E_WARNING: imap_open(): Couldn't open stream {outlook.office365.com:993/imap} in /home/username/public_html/modules/OSSMail/models/Record.php, line 148
#0 modules/OSSMail/models/Record.php (148)  >>  imap_open('{outlook.office365.com:993/imap}','email@example.com','Password',0,0,[])
#1 modules/OSSMailScanner/models/Record.php (581)  >>  OSSMail_Record_Model->imapConnect('email@example.com','Password','outlook.office365.com','')
#2 modules/OSSMailScanner/models/Record.php (545)  >>  OSSMailScanner_Record_Model->isConnection([2,email@example.com,outlook.office365.com,2021-05-26 21:54:56,2021-05-26 21:54:56,,,en_US,a:2:{s:16:"message_sort_col";s:7:"arrival";s:11:"client_hash";s:16:"544Ga45Cxo0rN5tQ";},array,NUY5T3hCUFpCM3I4VG1TdUF3PT0=,0])
#3 modules/OSSMailScanner/crons/Action.php (27)  >>  OSSMailScanner_Record_Model->executeCron('fpm-fcgi - ')
#4 cron.php (98)  >>  OSSMailScanner_Action_Cron->process()
#5 public_html/cron.php (11)  >>  require('cron.php')
`

**system.log**
`WHERE `rc`.`CONSTRAINT_SCHEMA` = database() AND `kcu`.`TABLE_SCHEMA` = database()
AND `rc`.`TABLE_NAME` = 'vtiger_ossmails_logs' AND `kcu`.`TABLE_NAME` = 'vtiger_ossmails_logs'
2021-05-26 16:44:35.9701 [info][yii\db\Command::execute] - INSERT INTO `vtiger_ossmails_logs` (`status`, `user`, `start_time`) VALUES (1, 'fpm-fcgi - ', '2021-05-26 16:44:35')
2021-05-26 16:44:35.9723 [trace] - Start checking account: email@example.com
2021-05-26 16:44:35.9725 [info][yii\db\Connection::open] - Opening DB connection: mysql:host=localhost;dbname=username;port=3306
2021-05-26 16:44:35.973 [info][yii\db\Command::query] - SELECT * FROM `a_yf_encryption` LIMIT 1
2021-05-26 16:44:35.9736 [trace] - Entering OSSMail_Record_Model::imapConnect(email@example.com , Password , ) method ...
2021-05-26 16:44:35.9741 [trace] - imap_open(({{outlook.office365.com:993/imap}, email@example.com , Password. 0, 0, array (
)) method ...2021-05-26 16:45:45.2148 [error] - Error OSSMail_Record_Model::imapConnect({outlook.office365.com:993/imap}): [CLOSED] IMAP connection broken (server response)
`

Thanks in advance

**Comment by mariuszkrzaczkowski** [comment]
https://support.microsoft.com/pl-pl/office/ustawienia-pop-imap-i-stmp-8361e398-8af4-4e97-b147-6c6c4ac95353

https://github.com/YetiForceCompany/YetiForceCRM/issues/12133
https://github.com/YetiForceCompany/YetiForceCRM/issues/4584
https://github.com/YetiForceCompany/YetiForceCRM/issues/4002

**Comment by Jeroenleender** [comment]
Hello Marius and thanks for your reply, i looked into those 3 tickets and it looks to me they where unable to connect at all!

Could it be that we setup the roundcube mailbox with it's own user and password instead of %u and %p?
The user that configured the mailbox logs in using a different domainname and email address in the login name

I added below image to show u that my mailbox connects and that it works 100% as far as i can see it.

![My_mailbox](https://user-images.githubusercontent.com/47397626/119812750-c44cf500-bee8-11eb-8bc2-4b30ac32c5ad.png)

The error(s) that i posted in the logs are coming from the mail scanner which as far as i can see it takes the info from the roundcube mailbox.

![Mail_Scanner](https://user-images.githubusercontent.com/47397626/119814007-383bcd00-beea-11eb-9873-296250c5d899.png)

Roundcube config;

![roundcube_config](https://user-images.githubusercontent.com/47397626/119814053-45f15280-beea-11eb-9954-b6a922ff9571.png)

Thx in advance for your reply!

**Comment by rskrzypczak** [comment]
check this: https://github.com/YetiForceCompany/YetiForceCRM/issues/12589

**Comment by Jeroenleender** [comment]
Worked perfectly, thank you
