### ISSUE TITLE
[bug] Project task notification not working

### ISSUE THREAD

**Issue by rioshaz** [YetiForceCompany/YetiForceCRM#14739]
I have tested this on gitstable
project notification dont work and gives coded (ModTracker|LBL_UPDATED)$ $(record : RecordLabel)$) line rather then title n link to the created or edited record.

pls see below screenshot.. i created a project task n asisgned it to another user on gitsable. but the notification is messed up... 

![image](https://user-images.githubusercontent.com/54880467/120020161-fce2f080-c006-11eb-8b16-985cb6aafae8.png)

please help...
this doesnot help either.. https://github.com/YetiForceCompany/YetiForceCRM/issues/13910

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski hi sir .. any hope when can we find a solution to this problem...

**Comment by rioshaz** [comment]
any nws buddy

**Comment by rskrzypczak** [comment]
Fixed in: https://github.com/YetiForceCompany/YetiForceCRM/commit/740df2887f1c4775360ea3e65f678827345b4736, https://github.com/YetiForceCompany/YetiForceCRM/commit/58f5809f291220f47c6e3c5ea3fc3f0ffa38b301
