### ISSUE TITLE
[bug] Links to customer and vendor portals are broken (404)

### ISSUE THREAD

**Issue by rulotec** [YetiForceCompany/YetiForceCRM#14738]
Just click on these:

https://gitdeveloper.yetiforce.com/customerPortal

https://gitdeveloper.yetiforce.com/vendorPortal

![image](https://user-images.githubusercontent.com/36896420/120012196-d12f1e80-bfa4-11eb-8ea9-9924c9e53b44.png)

**Comment by mariuszkrzaczkowski** [comment]
corrected
https://github.com/YetiForceCompany/YetiForcePortal2#-demo
