### ISSUE TITLE
[Docker] ... Problem Installation

### ISSUE THREAD

**Issue by espe808** [YetiForceCompany/YetiForceCRM#14749]
Hello,
I have this problem during the installation.
(I have inserted ALL the information about the company).

![yeti](https://user-images.githubusercontent.com/85027316/120172297-2c5e4c80-c203-11eb-959b-7426858054f3.PNG)

**Comment by vovpff** [comment]
What is the problem? This is optional window with question why admin logged in.

**Comment by espe808** [comment]
This window appears when I am doing the installation and so I cannot proceed.
And so what I must to write in this window in order to proceed?

**Comment by rskrzypczak** [comment]
When logging in for the first time after installation, you must provide the reason, and then you can turn it off in the panel or change the settings in the file.
This is not a bug, so I close.

**Comment by espe808** [comment]
What reason I have to write?
Please suggest me the answer.

**Comment by rskrzypczak** [comment]
Whatever you want, it's local information. It is not sent anywhere, it is only available for viewing in the administration section in order to register the administrator's activity.

**Comment by espe808** [comment]
Whatever I write and click save, the window doesn't disappear and so I can't proceed.

**Comment by mariuszkrzaczkowski** [comment]
Provide the required information
![github](https://user-images.githubusercontent.com/10198654/120181266-1c4b6a80-c20d-11eb-8cb8-5f919e381d5e.jpg)

**Comment by waran70** [comment]
How easier would be for the developers to create community FAQ for managing a such? Paste link to FAQ here and if there is no answer show in FAQ link to paid support.

**Comment by espe808** [comment]
I have solved with local installation.
