### ISSUE TITLE
[bug] PDF Settings Edit mode not working

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14743]
# 🐞 bug report

### ⁉️ Describe the bug
When trying to Edit PDF from Settings, Documents basic options page does not load properly

Till few days back same was working, now not allowing to edit pdf

In Chrome Console, I checked and found below error

Uncaught TypeError: Cannot read property 'textContent' of null
    at HTMLDocument.errorLog (index.php?module=PDF&parent=Settings&view=Edit&record=40:117)

### 🔥 How to trigger the error
Go to Settings
System Tools
PDF
Edit any PDF row

### 👎 Actual Behavior
does not load entire page and not allow to move next

### 👍 Expected Behavior
should load entire page and allow to move next

### 👷 Testing

- [ Y] I confirm that I tested it at https://gitstable.yetiforce.com **works properly**
- [ Y] I confirm that I tested it at https://gitdeveloper.yetiforce.com **works properly**

### 📷 Screenshot of configuration
![image](https://user-images.githubusercontent.com/12723595/120058418-59c2c300-c068-11eb-8bb3-6eb2bbe71e2a.png)

![image](https://user-images.githubusercontent.com/12723595/120058517-02712280-c069-11eb-8a45-bf4bc5049bdc.png)

kindly help

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
1. Two important configuration errors, please correct and let me know
```
output_buffering = "On"
memory_limit = 1024M
```
2. You can try deleting the template and adding it again
3. run full logs

**Comment by rskrzypczak** [comment]
Try disabling the extensions you've added to your browser.

**Comment by JEEVAN28** [comment]
Disabled all extensions, but issue persist. I noticed error in Console

![image](https://user-images.githubusercontent.com/12723595/121057724-353fb700-c7dd-11eb-960a-7f3471a0124b.png)

This may be helpful to understand exact problem

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version and the last stable version

**Comment by JEEVAN28** [comment]
Hello,

Checked on dev version and found working properly
![image](https://user-images.githubusercontent.com/12723595/121141260-67422f00-c858-11eb-98cd-0b852c4a4391.png)

On stable version also it is working properly.
![image](https://user-images.githubusercontent.com/12723595/121141373-8476fd80-c858-11eb-99bc-bb745c56fda1.png)

Please assist.

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
This means your version is corrupted
