### ISSUE TITLE
Office 365 modern SMTP connection

### ISSUE THREAD

**Issue by kamcio2603** [YetiForceCompany/YetiForceCRM#14771]
Hello,

YetiCRM is using phpmailer which supports modern (aka SASL XOAUTH2 ) authentication for IMAP/SMTP email handling.

So, my question is, can CRM use/connect to office 365 via XOAUTH instead of old style login/pass.

Example link for google: https://phppot.com/php/sending-email-using-phpmailer-with-gmail-xoauth2/

**Comment by mariuszkrzaczkowski** [comment]
can use
only someone has to add the ability to CRM to be able to download the keys in the panel
