### ISSUE TITLE
[Request] Better mass mailing

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1478]
In vTiger I use EMAILmaker a lot to send emails to a small group (10-130) in one go, usually with a nice template created earlier.
This system lets you select a filtered list, select the contacts, write the email and then send them one by one (automatically). Each with a personal text. This often replaces our newsletter system for smaller groups.

There is nothing similar in Yeti as far as I know. WHen I use the mass email options, it uses/shows  all  addresses in the TO: field. Not a good idea! BCC I could live with but every email visible to other persons...

From within the Campaigns I see an option to choose email campaign but no way to create Contacts list to send it too.Hope this gets a bit of attention from the team.

**Comment by zebrahosting** [comment]
This happens when I choose mass mail in a contact list:
![massmail](https://cloud.githubusercontent.com/assets/10379403/8784206/101cf650-2f21-11e5-9dc1-1059bf4f4e83.png)

Of course bad practice that everybody can see each others email addresses.
Als not the best way to send multiple(mass)  email this way. Most mail servers will have a limit on this way of sending.

Better to do it like EMAILmaker and create a queue of singles mails.

**Comment by echemik** [comment]
+1

**Comment by zebrahosting** [comment]
A pity that it has been moved to 2.3. Such an important part of the CRM....
But I assume 2.2 will be out one of these days?

**Comment by bpabiszczak** [comment]
Version 2.2 will be published on 2015-08-31

**Comment by zebrahosting** [comment]
Great. Has been solid here. Looking forward to the next steps.

**Comment by bpabiszczak** [comment]
1. Rebuilt a huge part of roundcube integration.
2. Added the possibility to integrate with external mail clients via mailto.
3. Rebuilt mail campaigns [mails are sent all together, instead of being sent separately, but we also fixed and added a few things in there]

Happy testing. We're not planning any additional changes in 2.4 apart from bug fixes.

**Comment by zebrahosting** [comment]
Wow lots of work done. Fantastic work. Will test and report back.Thanks a lot.
