### ISSUE TITLE
[bug] Change in Account Assigned to adding user in Shared With of Contact

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14788]
Hello,
I need to disable auto assigning of Related Contact to previous owner user of Account. I checked on **GitDeveloper and found no issue**, but on **GitStable I found issue which I am facing on my local server**, I tried searching for code changed but could not found.

Below is current contact where no shared with user is assigned
![image](https://user-images.githubusercontent.com/12723595/120889932-493cba80-c61d-11eb-9794-6d6204b1d7da.png)

Below is current assigned to on Account of this contact
![image](https://user-images.githubusercontent.com/12723595/120889948-5e194e00-c61d-11eb-97bd-f6ea24a2a307.png)

I changed Assigned to on Account from YetiForce Portal to YetiForce Sales
![image](https://user-images.githubusercontent.com/12723595/120889962-7f7a3a00-c61d-11eb-8cb3-72ac684ab15a.png)

This has added Yetiforce Sales user on Related Contact of Account in Shared With User, where user is not in Assigned To
![image](https://user-images.githubusercontent.com/12723595/120889992-b2bcc900-c61d-11eb-9659-dd7240b98ee7.png)

**I need to stop this, please help**

Regards
Jeevan Pendhari

**Comment by rskrzypczak** [comment]
Remove this handler: https://github.com/YetiForceCompany/YetiForceCRM/commit/f10998dcf2cf88bb9321d141e7127e5559afd7b8#diff-6c1ecf2857599d07dbe8f7fbaaeae68350e57e60c25afa88bc62648e30cbc804L3366

**Comment by JEEVAN28** [comment]
Thanks, issue resolved
