### ISSUE TITLE
Roundcube - CRM details on email preview

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1479]
It would be great to see crm details on email preview in roundcube:

this header:
![mail2](https://cloud.githubusercontent.com/assets/4824588/8624602/59cd44ca-2739-11e5-84ae-b06c82358945.JPG)

in this view:
![mail](https://cloud.githubusercontent.com/assets/4824588/8624604/5f35656e-2739-11e5-8b7c-266beaa458df.JPG)

**Comment by nikdejan** [comment]
+1
