### ISSUE TITLE
Bug importing new Accounts or creating new Users

### ISSUE THREAD

**Issue by espe808** [YetiForceCompany/YetiForceCRM#14796]
Hi,
as previous discussion https://github.com/YetiForceCompany/YetiForceCRM/discussions/14780
and as @mariuszkrzaczkowski suggests,
in attachment there is my configuration report.

I cannot import new Accounts and also I cannot create new users.
Maybe there is a bug? 

![ConfReport (1)](https://user-images.githubusercontent.com/85027316/120991778-3d1e3d80-c782-11eb-8008-316578b96126.png)

**Comment by mariuszkrzaczkowski** [comment]
The problem is caused by a wrong server configuration

**Comment by espe808** [comment]
@mariuszkrzaczkowski thanks for your reply.
What is wrong in my server configuration?

**Comment by mariuszkrzaczkowski** [comment]
Everything that is in red
