### ISSUE TITLE
CRON (CLI) not change after php.ini change

### ISSUE THREAD

**Issue by espe808** [YetiForceCompany/YetiForceCRM#14805]
After changing the php.ini file to solve red line in attachment of CRON (CLI) column, the red lines not change their status.

Why?
![1234567](https://user-images.githubusercontent.com/85027316/121172203-bcca0c00-c857-11eb-8906-fb4180c082f5.JPG)

**Comment by waran70** [comment]
O.o
systemctl reload apache2

**Comment by espe808** [comment]
I have launched the apache2 command, but anyway it doesn't work
