### ISSUE TITLE
[BUG] Font and alignments are off in left menu's.

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1480]
Testing master ver. 2.0.346:

Looking at the menu's on the left side: fonts are bigger than normal and alignment is off. text and boxes below don't match. (tested on OSX CHrome and Safari.) THis happens in all 'colors' except the twilight version. (Top colors also don't change after selecting another color)
![screen shot 2015-07-11 at 21 26 28](https://cloud.githubusercontent.com/assets/10379403/8635065/8d5013b0-2813-11e5-8e66-62517d76d2c2.png)

**Comment by rcrrich** [comment]
I have also seen this and now just have a blue pointing on left menu somewhat off.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1169
