### ISSUE TITLE
[REQUEST] Port LSWYSIWYG to Yeti

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1481]
https://github.com/AlanBell/LSWYSIWYG

Terrific system for fast and clear exports. We use it a lot and even less tech people using the CRM like to use it above the complicate CSV export with too many fields.

Hope this can be ported to work in Yeti.

**Comment by waw555** [comment]
Good Idea

**Comment by AlanBell** [comment]
ooh, I must have a go with Yeti and see what needs doing to fix it, I imagine I would want the same code to run in both rather than port it as a separate thing.

**Comment by mariuszkrzaczkowski** [comment]
we are planning to add this solution by default in the yeti

**Comment by bpabiszczak** [comment]
We will add a functionality like this, it won't be a module, but a part of the system. Additionally, it'll work in a slightly different way than the original version. In YetiForce everything has to be controlled so export itself will be added in profiles as an option to add.

**Comment by AlanBell** [comment]
excellent, I look forward to seeing it, shout if you have any questions
