### ISSUE TITLE
[PL] Problem z wykresem

### ISSUE THREAD

**Issue by Nyshak** [YetiForceCompany/YetiForceCRM#14822]
Witam,

stworzyłem od zera nowy wykres. Po zakończeniu procesu pojawił mi się on na stronie głównej w formie "widgetu". Niestety cały czas jest w trakcie weryfikacji (wyświetla się napis "proszę czekać"), a po upływie paru/parunastu minut wyświetla się taki komunikat w polu widgeta, który miał być wykresem - "Fatal error: Maximum execution time of 300 seconds exceeded in C:\wamp64\www\datalabcrm\modules\Vtiger\models\ChartFilter.php on line 766" . Podczas weryfikacji wykresu korzystanie z CRM-u jest praktycznie niemożliwe - wszystko działa znacznie wolniej. Z pozycji administratora nie widzę tego widgetu - tak jakby nie został on nigdy dodany. Czy istnieje sposób na usunięcie tego wykresu?
YetiForce: 4.3
Z góry dziękuje za odpowiedź

**Comment by bpabiszczak** [comment]
Programista musi to zrobić z poziomu bazy danych. 
Zalecamy aktualizację systemu.

**Comment by Nyshak** [comment]
Dzień dobry,  dziękuję za odpowiedź. Czy jest Pan w dtanie wskazać gdzie dokładnie mam szukać błędu? 
            

     

       
        Dnia 11 czerwca 2021 09:55 Błażej Pabiszczak ***@***.***&gt; napisał(a):
       

       
         
 Programista musi to zrobić z poziomu bazy danych.  
Zalecamy aktualizację systemu.

**Comment by mariuszkrzaczkowski** [comment]
Trudno wskazać gdzie szukać błędu bo to wymaga analizy przez programistę.
Dziwne jest to że błąd występuje w wierszu 766 dla pliku "modules\Vtiger\models\ChartFilter.php" gdzie ten  plik w wersji 4.3 ma tylko 574 wierszy (https://github.com/YetiForceCompany/YetiForceCRM/blob/4.3.0/modules/Vtiger/models/ChartFilter.php).
Wygląda to albo na nieudaną aktualizację lub modyfikację systemu. 

Tak czy inaczej bez programisty i analizy z pełnym dostępem do serwera nic nie można zrobić.
