### ISSUE TITLE
[bug] installation unsuccessful.  Wrong session ID.

### ISSUE THREAD

**Issue by 548990** [YetiForceCompany/YetiForceCRM#14829]
Shown below: 
Wrong session ID.
Exists in server configuration which causes loss of session data.
We recommend removing browser cache, in case it does not help please fix your server configuration.

Removing browser cache does not work.

The error log shown below:
[Sat Jun 12 20:59:46.062852 2021] [core:warn] [pid 7560:tid 352] AH00098: pid file D:/phpstudy_pro/Extensions/Apache2.4.39/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sat Jun 12 20:59:46.062852 2021] [mpm_winnt:notice] [pid 7560:tid 352] AH00455: Apache/2.4.39 (Win64) OpenSSL/1.1.1b mod_fcgid/2.3.9a mod_log_rotate/1.02 configured -- resuming normal operations
[Sat Jun 12 20:59:46.062852 2021] [mpm_winnt:notice] [pid 7560:tid 352] AH00456: Server built: Mar 27 2019 11:06:20
[Sat Jun 12 20:59:46.062852 2021] [core:notice] [pid 7560:tid 352] AH00094: Command line: 'D:\\phpstudy_pro\\COM\\..\\Extensions\\Apache2.4.39\\\\bin\\httpd.exe -d D:/phpstudy_pro/Extensions/Apache2.4.39'
[Sat Jun 12 20:59:46.062852 2021] [mpm_winnt:notice] [pid 7560:tid 352] AH00418: Parent: Created child process 6292
[Sat Jun 12 20:59:46.641006 2021] [mpm_winnt:notice] [pid 6292:tid 400] AH00354: Child: Starting 1024 worker threads.

I read all the same problems issues, do not work.
Pls check what is the problems.

Furthermore,  would you yetiforce official could offer an entire solved installation package with the Web server environment together ?

Thank you.

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/121797837-05e8da00-cc23-11eb-997a-07b42d308325.jpg)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13917

**Comment by 548990** [comment]
Dear Sir, you suggestion #13917 does not work. 
pls review.

**Comment by mariuszkrzaczkowski** [comment]
without access to the environment it is impossible

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/the-installation-process-has-failed
