### ISSUE TITLE
accounts module

### ISSUE THREAD

**Issue by Akaki-1991** [YetiForceCompany/YetiForceCRM#14843]
version. 6.1.0

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/122378799-8f234800-cf66-11eb-902e-5f773b6d1af3.jpg)

**Comment by Akaki29** [comment]
![Uploading 1.PNG…]()

**Comment by Akaki29** [comment]
![3](https://user-images.githubusercontent.com/75428743/122380607-1b3e6b00-cf79-11eb-95a9-495419ebc296.PNG)

**Comment by Akaki29** [comment]
![3](https://user-images.githubusercontent.com/75428743/122380684-2d200e00-cf79-11eb-9fcb-e91b89ebb29d.PNG)
![2](https://user-images.githubusercontent.com/75428743/122380716-34471c00-cf79-11eb-9bf4-e62e8a65f9f5.PNG)
![1](https://user-images.githubusercontent.com/75428743/122380722-37420c80-cf79-11eb-83c4-58647c49d184.PNG)

**Comment by mariuszkrzaczkowski** [comment]
The error is in a wrong server configuration
