### ISSUE TITLE
[bug] Switching off Products module creeping Invoices

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#14848]
Switching off Products module (for completely service based mid-size entity) locking line items in invoices. Cannot add Services in this case at all.

You can test it in online dev and stable versions

**Comment by davide-alghi** [comment]
Hi @waran70,
yes it does. if you disable an inventory lineitem module like Prods or Servs, you have to reconfigure all inventory modules (extended modules) that use the disabled one.
the change of behavior is not only on Sales Invoices, but on ALL inventory modules (extended modules) that are using the disabled one
eg for Sales Invoices

1. go to Standard modules / Edit fields
2. select Sales Invoices
3. edit "Item name" field (only Services will be available in popup win Modules field)
4. save

**Comment by waran70** [comment]
Thanks Davide
