### ISSUE TITLE
[bug] the login page could not jump.

### ISSUE THREAD

**Issue by 548990** [YetiForceCompany/YetiForceCRM#14854]
Hi, 

Xampp with all Web server requirements
Apache 2.4.47, MariaDB 10.4.19, PHP 7.3.28, phpMyAdmin 5.1.0, OpenSSL 1.1.1

The installation was about 30minutes, 
When it was finish, 
i type the right user/password, but could not jump
Pls check what is the reasons.
![1624195428(1)](https://user-images.githubusercontent.com/85793374/122675843-da12b900-d20d-11eb-8a7a-7bb412615741.jpg)

**Comment by vovpff** [comment]
Let's clean cache and coockies for this website

**Comment by 548990** [comment]
> Let's clean cache and coockies for this website

I do, but it does not work.  Any other reasons ?

**Comment by mariuszkrzaczkowski** [comment]
Show a screenshot of the configuration verification during installation, make sure the server configuration is correct. 
Check the server and browser logs
This is not a CRM error

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/122712639-867f8a00-d264-11eb-87d4-8a8f666daa94.jpg)
