### ISSUE TITLE
[REQUEST] Rerun mailscanner on corporate mails

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1486]
When I add or import contacts their emails are not added to their account list.
It seems that when the mailscanner runs and adds the email to 'corporate' mails list, it never checks back for new contacts that might match.
Would be nice if we could run a (manual) check/workflow and let the scanner find emails already in the archive and match it with leads and contacts.

Double check: if I remove all emails in the corporate email list, will the scanner start all over again on the mailserver?

**Comment by bpabiszczak** [comment]
Please check this [on your test server]:

1. https://gitdeveloper.yetiforce.com/
2. https://gitdeveloper.yetiforce.com/index.php?module=OSSMailView&view=List&parent=84
3. Action on list view
4. Select all mails and use: Assign emails.

**Comment by bpabiszczak** [comment]
"Double check: if I remove all emails in the corporate email list, will the scanner start all over again on the mailserver?"

No. You must remove all emails and clear table `vtiger_ossmailscanner_folders_uid`

**Comment by zebrahosting** [comment]
Ok found that option and I have put it in my personal Yeti FAQ :-) Both good to know.

On my 2.0RC site the re-assign doesn't seem to do anything on fresh imported contacts. Does it follow the mailscanner rules or does it just looks for Primary / Secondary email address to match?

Can't test on master or dev-git version because of other problems but will run it again when those are both up and running.

**Comment by bpabiszczak** [comment]
Just to make it sure, because I might have described it in a wrong way:
1. If you want the CRM to download all your emails once again, you have to clean the vtiger_ossmailscanner_folders_uid table. I'm not sure, but the system won't add once again these emails that already are in the database, but it will bind them with the records in CRM [if it doesn't bind them, you will have to delete them though]
2. If you want them CRM only to bind them once again, then like I said, you will have to select all emails and launch action: Assign emails. 

Important: If you follow the 2nd step you have to remember that the system will select only the to-do records, cron has to be active in order for the system to start correcting them. If I'm not wrong the MailScannerBind is used for binding them.

**Comment by zebrahosting** [comment]
Appreciate the details but still struggling to get it properly working on our 'real world CRM' if needed I will need to move it to my 'Yeti optimized' test server.

For security I have tried to make a fresh start with the whole mailscanner. DB tables emptied, Logs emptied, CRM records deleted.

Simplified the mailscanner by only adding the 'SEND' and INBOX folders and in the ALL field placed the 'PROCESSED'  IMAP folder that is used for all emails answered.

Observations:
Running the CRON only found 13 mails in the SENT folder (out of 2500) dated on the 'today' date.
It seems it is not looking for older mails. Makes sense in a production environment but less if you want to 'catch up' the whole archive.

No INBOX or PROCESSED folders had any mail recognized.
Doing a manual selection in Roundcube placed them in the corporate list fine.

Checking the mail log showed 373 mails checked which means  it did not fully run on any folder. unless the  date restriction was there. I am able to stop the mailscanner but never able to start it manually. It always says it it busy with the CRON task. Seems a bit odd too.

No errors in the CACHE/logs or server logs.

Willing to compare it with the MASTER branche but have to wait for the bug fixing on the mailscanner.

![screen shot 2015-07-14 at 10 27 06](https://cloud.githubusercontent.com/assets/10379403/8669468/38a3f2ec-2a15-11e5-96fd-b17a61d43023.png)

**Comment by mariuszkrzaczkowski** [comment]
Check the amount of e-mails in the module Corporate emails

**Comment by mariuszkrzaczkowski** [comment]
check which folders are set up to scan Settings > Mail > MailScaner > Folder Configuration (Tab)

**Comment by zebrahosting** [comment]
Hi Mariusz, everything mentioned above about 'observations' came from there. The amount of emails in corp mails en de mailscanner folders.

**Comment by zebrahosting** [comment]
Just did another run on the dev version and there the mailscanner is running fine, including finding the thousands of emails and attaching them to contacts. Might be worth to wait for v2.1 and see from there what is working and what not.
