### ISSUE TITLE
[bug] In PDF inventory table, summation fields contains currency symbol regardless of type

### ISSUE THREAD

**Issue by TheVirtualMoose** [YetiForceCompany/YetiForceCRM#14865]
# 🐞 bug report

### ⁉️ Describe the bug

I have created a custom inventory field (TotalWeight) with summation enabled. In inventory tables in PDFs, the sums are shown with a currency symbol, which is not always desired.

Looking at app/TextParser.php, there is some plumbing already done to differentiate fields with and without currency ($fieldsWithCurrency in getInventoryTable function), but apparently it wasn't finished. Short term, a solution would be to change 
`$tb = \CurrencyField::appendCurrencySymbol(\CurrencyField::convertToUserFormat($sum, null, true), $currencySymbol);`
to
```
if (\in_array($field->getType(), $fieldWithCurrency)) {
    $tb = \CurrencyField::appendCurrencySymbol(\CurrencyField::convertToUserFormat($sum, null, true), $currencySymbol);
} else {
    $tb = $sum;
}
```
Long term, it would be best to move away from a hardcoded list of fields with currency to defining that as a property of an inventory field class.

### 🔥 How to trigger the error

1. Create a new inventory field class with $summationValue property set to true
2. Generate a PDF containing said field

### 👎 Actual Behavior

The sum of this field's column always has a currency symbol added, even if the values in rows above do not.
[PL - incorrect.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/6708131/PL.-.incorrect.pdf)

### 👍 Expected Behavior

The sum of this field's columns only has a currency symbol added, if the values in rows above also do.
[PL - correct.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/6708132/PL.-.correct.pdf)

### 👷 Testing

Present in 6.1. Unable to test on gitstable or gitdeveloper due to the need to create custom fields.

### ❗️ Inform the community if you solve the problem

The change above fixes the problem, as seen in the second PDF attached.

**Comment by konadrian** [comment]
It's not a bug if you created your own custom class you need to adjusts it to yours requirements. I closed the topic
