### ISSUE TITLE
Webservice problem

### ISSUE THREAD

**Issue by gsportelli73** [YetiForceCompany/YetiForceCRM#14876]
Hi, i have updated yeti to 6.1.2.
On my vps centros 7 php 7.3 
i have a webservice that until a few weeks ago, it get data from wordpress cms and storage in a lead data. 
Now i don't understand why doesn't function anymore. 
I think that apache doesn't forward to php athorization header with data. 
My logs
[webserviceDebug_25_06_021.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6728449/webserviceDebug_25_06_021.log)
[webserviceErrors_28_06_21.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6728450/webserviceErrors_28_06_21.log)
my .htacess is 
[htaccess txt](https://github.com/YetiForceCompany/YetiForceCRM/files/6728474/htaccess.txt)
The configuration 
![ConfReport](https://user-images.githubusercontent.com/27689602/123686286-f0dd8f00-d84f-11eb-869f-3daa5c743e0d.png)

Can you help me ?
Thank you !

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/123691292-baa30e00-d855-11eb-9273-dd8aeece4ee4.jpg)

**Comment by gsportelli73** [comment]
Hi, I have Yeti updated version 6.1.2 and i have a webservice on it
Webservice uses Rest API service to insert lead in yeti via wordpress website of custumer. 
Already in previus version after a few month webservice produced an error 401.
In the log file of webservice shows that autorization header is missing. 
My webservice is installed on crm
![webservice_1](https://user-images.githubusercontent.com/27689602/123744387-ff0ec800-d8ae-11eb-90b4-680b1824d5e2.png)
![webservice_2](https://user-images.githubusercontent.com/27689602/123744389-ff0ec800-d8ae-11eb-8558-76c654b4e046.png)

 Now my log files
[system_29_06_21.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6730949/system_29_06_21.log)
webservice log
[webserviceDebug_28_06_21.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6730966/webserviceDebug_28_06_21.log)
[webserviceErrors_28_06_21.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6730967/webserviceErrors_28_06_21.log)
My error log
[error_log_28_06_21.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6731051/error_log_28_06_21.log)
My configuration of yeto
![ConfReport](https://user-images.githubusercontent.com/27689602/123745542-b7893b80-d8b0-11eb-951a-b0d3b94ae9e7.png)

Server configuration
Yetiforce 6.1.2
Centos 7 +with cpanel
PHP 7.3
Apache 2.4
Beowser Mozilla or Chrome latest linux version on my client.
My htaccess configuration

Options Indexes FollowSymLinks MultiViews
Require all granted
RedirectMatch 403 (?i).*\.log$
<IfModule mod_env.c>
	SetEnv HTACCESS_TEST on
</IfModule>
<IfModule mod_autoindex.c>
	Options -Indexes -MultiViews
</IfModule>
<IfModule mod_rewrite.c>
	Options +FollowSymLinks
	RewriteEngine On	
	RewriteCond %{HTTP_HOST} ^officeadok.net$ [NC,OR]
	RewriteCond %{HTTP_HOST} ^crm.officeadok.net$
	RewriteCond %{REQUEST_URI} !public_html/
	RewriteRule (.*) /yeticrm/public_html/$1 [L]
	RewriteRule ^favicon.ico layouts/basic/images/favicon.ico [L,NC]
	RewriteRule ^webservice/(.*)/(.*)/(.*)/(.*)$ webservice.php?module=$1&action=$2&record=$3&param=$4 [QSA,NC,L]
	RewriteRule ^webservice/(.*)/(.*)/(.*)$ webservice.php?module=$1&action=$2&record=$3 [QSA,NC,L]
	RewriteRule ^webservice/(.*)/(.*)$ webservice.php?module=$1&action=$2 [QSA,NC,L]
	RewriteRule ^webservice/(.*)$ webservice.php?action=$1 [QSA,NC,L]

	RewriteRule ^\.well-known/carddav dav.php/addressbooks/ [R]
	RewriteRule ^\.well-known/caldav dav.php/calendars/ [R]
	RewriteRule /.well-known/carddav dav.php/addressbooks/ [R,L]
	RewriteRule /.well-known/caldav dav.php/calendars/ [R,L]
	RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
	RewriteRule .* - [E=HTTP_CONTENT_TYPE:%{HTTP:Content-Type},L]
</IfModule>
<IfModule mod_headers.c>
	Header unset Server
	Header unset X-Powered-By
	<IfModule mod_env.c>
		SetEnv modHeadersAvailable true
	</IfModule>
</IfModule>
<ifModule ModSecurity.c>
	SecServerSignature ''
</ifModule>
<IfModule mod_dir.c>
	DirectoryIndex index.php
</IfModule>
<Files dav.php>
	<IfModule mod_expires.c>
		ExpiresActive Off
	</IfModule>
</Files>
########################
# <FilesMatch "\.(inc|php|php3|php4|php5|php6|phtml|phps)$">
# AddHandler x-httpd-php56 .inc .php .php3 .php4 .php5 .php6 .phtml
# </FilesMatch>

# BEGIN cPanel-generated php ini directives, do not edit
# Manual editing of this file may result in unexpected behavior.
# To make changes to this file, use the cPanel MultiPHP INI Editor (Home >> Software >> MultiPHP INI Editor)
# For more information, read our documentation (https://go.cpanel.net/EA4ModifyINI)
<IfModule php7_module>
   php_flag display_errors Off
   php_flag session.use_only_cookies On
   php_value max_execution_time 600
   php_value max_input_time 600
   php_value max_input_vars 10000
   php_value memory_limit 1024M
   php_value post_max_size 105M
   php_value session.gc_maxlifetime 1440
   php_value session.save_path "/var/cpanel/php/sessions/ea-php73"
   php_value upload_max_filesize 100M
   php_flag zlib.output_compression Off
   php_flag auto_detect_line_endings On
   php_flag session.use_strict_mode On
</IfModule>
<IfModule lsapi_module>
   php_flag display_errors Off
   php_flag session.use_only_cookies On
   php_value max_execution_time 600
   php_value max_input_time 600
   php_value max_input_vars 10000
   php_value memory_limit 1024M
   php_value post_max_size 105M
   php_value session.gc_maxlifetime 1440
   php_value session.save_path "/var/cpanel/php/sessions/ea-php73"
   php_value upload_max_filesize 100M
   php_flag zlib.output_compression Off
   php_flag auto_detect_line_endings On
   php_flag session.use_strict_mode On
</IfModule>
# END cPanel-generated php ini directives, do not edit



Please can you help me ?
Thank you

**Comment by mariuszkrzaczkowski** [comment]
`I have Yeti updated version 6.1.2 and i have a webservice on it`
There is no update package for this version

You have a problem at the web server layer,
there you have to look in the logs

**Comment by mariuszkrzaczkowski** [comment]
Logs:

```
[29-Jun-2021 07:55:02 Europe/Amsterdam] PHP Warning:  session_set_save_handler(): Cannot change save handler when headers already sent in /home/___/public_html/yeticrm/app/Session.php on line 35
[29-Jun-2021 07:55:02 Europe/Amsterdam] PHP Warning:  session_start(): Cannot start session when headers already sent in /home/___/public_html/yeticrm/app/Session.php on line 37
```

```
[28-Jun-2021 13:20:02 Europe/Amsterdam] PHP Warning:  Unexpected character in input:  ' in /home/officeadok/public_html/yeticrm/app_data/cron.php on line 36
```
```
UnexpectedValueException: RecursiveDirectoryIterator::__construct(cache/mail): failed to open dir: No such file or directory in modules/Vtiger/crons/Cache.php:26
```
You have a lot of errors in the logs, you need an administrator to improve the server configuration

**Comment by gsportelli73** [comment]
Hi, this error i had before and the webservice it was ok.
I'm sure that warning it is important but not is the cause of problem.
Thank
