### ISSUE TITLE
[bug] roundcube library fails to download in 6.2.0

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#14887]
# 🐞 bug report

### ⁉️ Describe the bug

I updated my system to version 6.2.0. The I tried to update the roundcube library as suggested. When clicking on the butting [DOWNLOAD LIBRARY], nothing happens.

The error log file shows 

`[Sat Jul 03 10:34:33.708169 2021] [php7:warn] [pid 25404] [client xxx.xxx.xxx.xxx:xxxx] PHP Warning:  ZipArchive::close(): Invalid or uninitialized Zip object in /opt/crm6/app/Zip.php on line 129
`

### 🔥 How to trigger the error

1. Go as admin to '    Software configuration / Standard modules /  Modules – Installation'
2. Click on 'DOWNLOAD LIBRARY'
![df](https://user-images.githubusercontent.com/10230144/124348556-da865900-dbea-11eb-8d26-a410b78f7b32.jpg)
3. Nothing happens
4. Check web server log file to see
`[Sat Jul 03 10:34:33.708169 2021] [php7:warn] [pid 25404] [client xxx.xxx.xxx.xxx:xxxx] PHP Warning:  ZipArchive::close(): Invalid or uninitialized Zip object in /opt/crm6/app/Zip.php on line 129
`

### 👎 Actual Behavior

Latest roundcube library is not downloaded.

### 👍 Expected Behavior

Latest roundcube library is downloaded and can be installed.

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.2.0 v1
| Web server (name and version)       |   apache  2.4.43           |
| PHP                                 |  7.4.6              |
| Browser (name and version)          |   firefox 89.0.2             |
| Operating System (name and version) |  openSUSE Leap 15.3              |
| Database (name and version)         |   mysql 5.5.5-10.5.8-MariaDB-log             |
| Service Pack version                |   None             |

**Comment by mariuszkrzaczkowski** [comment]
Fixed, https://github.com/YetiForceCompany/lib_roundcube/releases
