### ISSUE TITLE
[BUG] (little detail ) wrong color display in server overview

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1489]
Master version: 2.0.346

<img width="1024" alt="overview" src="https://cloud.githubusercontent.com/assets/10379403/8649030/565497f6-2966-11e5-9cc2-4072cbd7c60c.png">

as you can see, the settings are identical but it still shows a red marker.....

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/5e9667e2c04f24fb6fef4daec3e6f760acc36ba5
