### ISSUE TITLE
[BUG] installing dev version 13/7

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1490]
Trying to install the dev version of today but get:

Notice: Undefined index: root_directory in /home/admin/web/devyeti.xxxx.info/public_html/include/runtime/Globals.php on line 21

Fatal error: Class 'Vtiger_EntryPoint' not found in /home/admin/web/devyeti.xxxx.info/public_html/include/main/WebUI.php on line 19

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1435

**Comment by bpabiszczak** [comment]
We fixed this problem. Check latest version.

**Comment by zebrahosting** [comment]
<img width="512" alt="dev-version" src="https://cloud.githubusercontent.com/assets/10379403/8673666/bf4a16d2-2a38-11e5-9118-a0c7da6450c5.png">

And thats only part of the screen....

Filtering out the errors:
Notice: Undefined index: root_directory in /home/admin/web/devyeti.zebrahosting.info/public_html/include/runtime/Globals.php on line 21

Notice: Undefined index: language in /home/admin/web/devyeti.zebrahosting.info/public_html/include/runtime/BaseModel.php on line 31

Notice: Undefined index: STYLES in /home/admin/web/devyeti.zebrahosting.info/public_html/libraries/Smarty/libs/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 36

Notice: Trying to get property of non-object in /home/admin/web/devyeti.zebrahosting.info/public_html/libraries/Smarty/libs/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 36

Notice: Undefined index: in /home/admin/web/devyeti.zebrahosting.info/public_html/include/runtime/LanguageHandler.php on line 150

**Comment by bpabiszczak** [comment]
Why u see notice? Please check this: https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html.

**Comment by zebrahosting** [comment]
<img width="1340" alt="screen shot 2015-07-14 at 15 22 13" src="https://cloud.githubusercontent.com/assets/10379403/8674160/4ac4e108-2a3c-11e5-83c0-a56de5e342ba.png">

Because I keep error reporting on. Want to see if something goes wrong in the code, and that seems the case.
All other settings are conform the sys req.

**Comment by bpabiszczak** [comment]
Please change error_reporting: E_WARNING & ~E_NOTICE & ~E_DEPRECATED

**Comment by bpabiszczak** [comment]
"Want to see if something goes wrong in the code, and that seems the case." please read this: https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by zebrahosting** [comment]
Of course did read that but won't go in discussion now. With errors of it installs fine.
Only get some Polish before the home screen opens in English. Need bug report for that?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1514
