### ISSUE TITLE
[Security] While registering getting error

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14915]
Hi,

I have upgraded to Release 6.2.0, I am facing below issues. 
![image](https://user-images.githubusercontent.com/12723595/124503309-e89eca00-dde2-11eb-876f-05c0fee9621b.png)

In above screen, Status shows No, what is the meaning ?

When trying to see Server Configuration or Dashboard from Settings, I get below error
![image](https://user-images.githubusercontent.com/12723595/124503371-0cfaa680-dde3-11eb-8960-3c41178126d9.png)

I am trying to register but get below error
![image](https://user-images.githubusercontent.com/12723595/124503490-50edab80-dde3-11eb-8390-309e851f3e12.png)

Please assist in the matter.

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/124507231-af0f9400-ddcd-11eb-9174-6cc1e6f277d9.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Logs logs logs ....

**Comment by rskrzypczak** [comment]
`In above screen, Status shows No, what is the meaning ?`
This means the update has failed. You should get a notification of this when updating.
Check the logs, restore the system from before the update, fix the application errors and perform the update again.
