### ISSUE TITLE
[bug] 403 Forbidden

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#14910]
Hi,

I am trying to access https://gitstable.yetiforce.com/ and getting below error

![image](https://user-images.githubusercontent.com/12723595/124448530-2fb79b80-dda0-11eb-8e36-52275c33a75f.png)

Please look into this.

Regards
Jeevan Pendhari

**Comment by rskrzypczak** [comment]
the demo for the stable version is not available yet. 
Use the development version: https://gitdeveloper.yetiforce.com/
