### ISSUE TITLE
[bug] Roundcube plugin still preventing email retrieval from Office 365

### ISSUE THREAD

**Issue by scotlad9** [YetiForceCompany/YetiForceCRM#14922]
Previously, I reported a bug when the Roundcube yetiforce plugin is enabled.  Email is not retrieved from an Office 365 server and the message 'loading' remains in the bottom right corner of the screen.  This was to be addressed in V6.2 but unfortunately it remains.

As before, if the default order is changed to 'ascending' the oldest 30 emails are displayed but still gets stuck 'loading' if the page is changed to display next 30 emails.

Emails are retrieved correctly if the yetiforce plugin is removed from the list of plugins in OSSMail.php.

The bug is present in a 6.1 to 6.2 migrated version and also in a clean, full system 6.2 install.

**Comment by scotlad9** [comment]
Does anyone have a solution for this please?  As we use Exchange 365 it's a show stopper preventing us changing over from another CRM.

**Comment by scotlad9** [comment]
**Update - Partial Solution:** 

Disable RBL in /config/Components/Mail.php by changing value from true to false (as described esleswhere):
		            public static $rcListCheckRbl = false;

Emails are now retrieved correctly with sort order "descending".  However, there still remains an issue with the email preview speed.

With the Roundcube Yetiforce plugin enabled it take more that 12 seconds to open an email and view its contents.  If the plugin is disabled the preview appears almost instantly.

**Comment by mariuszkrzaczkowski** [comment]
we are working on it to give greater configuration options

**Comment by gsbotes** [comment]
> we are working on it to give greater configuration options

How many years do you need? a massive number of people use 365...many other systems are now providing OAUTH through their CRM for years. This is making yeti useless.

**Comment by rskrzypczak** [comment]
YetiForce v7 support oauth2
