### ISSUE TITLE
[BUG] OSSMail Fatal error

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1492]
Fatal error: Cannot access empty property in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/OSSMail/views/compose.php on line 19

![animation 3](https://cloud.githubusercontent.com/assets/1402355/8651729/1def757e-2994-11e5-83a9-20066bd18a9c.gif)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1448
