### ISSUE TITLE
[BUG] Button Description

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1493]
Other descriptions of the buttons display

![animation 2](https://cloud.githubusercontent.com/assets/1402355/8651787/7d6dcc9e-2994-11e5-8b8b-439d4554c516.gif)

**Comment by konadrian** [comment]
Changes to see on https://gitdeveloper.yetiforce.com/

**Comment by waw555** [comment]
Very good, but could be increased width, as the text lines up vertically and not very readable turns
