### ISSUE TITLE
Call to a member function get() on null[bug] 

### ISSUE THREAD

**Issue by sltmunky69** [YetiForceCompany/YetiForceCRM#14937]
# 🐞 bug report

### ⁉️ Describe the bug

Immediately after upgrade to 6.2, can't even open the index page of the web interface whatsoever and receive the message: Error!!! Call to a member function get() on null. There are plenty of similar other bug reports with the same type of error, but not with the same info in the trace log.

### 🔥 How to trigger the error

Simply refresh the page, try to log in, or do any action.

### 👎 Actual Behavior

A big red Error!!! symbol, nothing else on the page whatsoever besides a <Go back and Dashboard button, neither of which do anything, and the error message "Call to a member function get() on null".
### 👍 Expected Behavior

A working interface
### 👷 Testing

- [x ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

The fact that a login screen comes up at all is more than I'm getting. Everything was fully functional before I ran the update.

### 📷 Screenshot of configuration

I wish I could, but that would require a working interface. I can tell you that it was passing all of the standard configuration tests without any errors before I ran the update and got this problem.

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

other logs are empty
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6794122/system.log)
### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.2
| Web server (name and version)    apache w/ nginx proxy   |     2.4.48           |
| PHP                                 |      phpfpm-7.4          | 
| Browser (name and version)          |          firefox 89.01     | 
| Operating System (name and version) |        ubuntu-server 20.04.2        | 
| Database (name and version)         |          mariadb   Ver 15.1 Distrib 10.5.10-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2   | 
| Service Pack version                |         n/a       |

**Comment by rskrzypczak** [comment]
> other` logs are empty
> system.log

I really doubt it, if you did an update, you should have at least a few entries in the **updateLogsTrace.log** file.
The update was probably unsuccessful.

Nevertheless, the error you describe is probably due to errors in the structure, be it on users, roles, groups, etc.
You must have messed up something before, but you were not aware of it :)
The only thing left for you to do is turn on debugging and try to fix it yourself, or buy support.

**Comment by sltmunky69** [comment]
I'm not sure I appreciate the tone or quality of your response. 
Nevertheless, the form didn't say to enter the update log, and so I 
answered the only questions given to me upon opening a ticket in the 
system. The fact the "I probably screwed something up" and just need to pay 
for support, not only displays arrogance, but is beyond aggravating seeing 
as how I just started demoing this software a few months ago and literally 
almost every time I've updated the software through the web interface, so 
that's at least the three out of 4 or 5 times, it has broken my system 
since version 5.3. I in fact had to completely reinstall the software from 
scratch one of those times and manually install the patches to get it to 
update because I didn't feel like dealing with this exact situation where 
you blame me and ask me to pay for support, because that tends to be the 
typical response I've seen on other support tickets when researching the 
multiple issues I've had in that little time. I'm definitely starting to 
see a pattern here. This last time was basically a fresh install with 
little to no modifications made. Certainly nothing deemed worthy of 
screwing something up like code base modification or ignoring some warning 
event notification for software configuration. To the best of my knowledge, 
I already did turn on debugging and have placed the applicable system log 
here. My searches for the exact lines where it failed in the system trace 
log tendered no useful results on github, so I'm just here trying to get 
help because I don't know where else to turn to fix it myself. Is there a 
community support forum somewhere that would be better suited?

I do have to say my patience, confidence with the software, and now any 
chances of getting support are dangerously low. I feel that software has a 
lot of potential, but I cannot handle the amount of trouble I've had thus 
far. Certainly not for a production system. I'll restore from backups and 
either take a VM snapshot first next time so I can roll everything back 
without the hassle, and I guess never update the software again, or scrap 
the project entirely.

**Comment by mariuszkrzaczkowski** [comment]
I recommend that you read the documentation
https://yetiforce.com/pl/component/zoo/item/debugging

attach update logs and full error logs, we cannot help without that

**Comment by sltmunky69** [comment]
Documentation was consulted before entering the ticket. I had already attached the full debug system log afaik.  Anyways, I restored the system from backups and tried to run the update again by uploading the patch file and it failed again for the same reason, with the same end result, a nonworking interface. Rerunning the update with full debugging on first this time and attaching every log file. It won't allow me to upload the empty update.log file. The two pics are the error directly after initiating the update and then the further errors where I cannot access the interface. Please let me know if you require anything further.
[errors.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6810320/errors.log)
[Importer.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6810321/Importer.log)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6810322/system.log)
[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6810323/updateLogsTrace.log)
![afterupdate](https://user-images.githubusercontent.com/10976587/125486057-423b3a84-60ad-4db5-b64b-98b44cc40e4a.jpg)
![afterupdate2](https://user-images.githubusercontent.com/10976587/125486058-ce23d05c-a0dc-493b-8e5f-043cc1d6ee44.jpg)
[cron.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6810324/cron.log)
[cron_error.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6810325/cron_error.log)

**Comment by rskrzypczak** [comment]
Now we can talk :)
You can see the error in the updateLogsTrace.log file

> ERR_RECORD_NOT_FOUND||1|#0 .../public_html/modules/Vtiger/models/Record.php(718): CRMEntity->retrieveEntityInfo(1, 'MultiCompany')

I don't know if you deleted all the module records or just a specific one.
Know that each role must be assigned to a department.
So..
Create a department, edit each role to assign it to the department and the problem should disappear.
![image](https://user-images.githubusercontent.com/10221999/125488958-3c9e1f6b-392d-4d59-8345-372f96846ee3.png)

However, do this before upgrading.

**Comment by rskrzypczak** [comment]
I am closing this ticket, if you have any other questions please consider creating a discussion.

**Comment by sltmunky69** [comment]
Unfortunately, I went through and checked all of the Roles and every single one of them had the primary department assigned. Anything else I can check? You mentioned something about deleted module records.

**Comment by rskrzypczak** [comment]
Edit and save each role, because if the role was assigned to a department that no longer exists, you will see the first picklist value, so you must click Save to make changes.
