### ISSUE TITLE
[BUG] Buttons do not work after you add the field

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1494]
Buttons do not work after adding the Russian-speaking field in the information about the organization
![animation 5](https://cloud.githubusercontent.com/assets/1402355/8652197/dfe15984-2996-11e5-9fc8-d1afe85de8ca.gif)

**Comment by konadrian** [comment]
4b5856269e7da94fac1fe914d7d22dcc3b15ddf0
