### ISSUE TITLE
Comments module - enable breaking lines

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [YetiForceCompany/YetiForceCRM#14950]
### Discussed in https://github.com/YetiForceCompany/YetiForceCRM/discussions/14948

<div type='discussions-op-text'>

<sup>Originally posted by **s2b-git** July 12, 2021</sup>
Comments (especially in tickets) are often used as a way of communication. In yetiforce here is little imperfection as we cannot break line while composing comment. html tag br also not working. It would be helpful if comments can be extended to this point.

Best</div>

**Comment by konadrian** [comment]
![image](https://user-images.githubusercontent.com/3193498/183045209-63788ada-c3af-41bd-aa8d-aacbd25d59f0.png)
The problem no longer exists. The ticket has been closed.
