### ISSUE TITLE
[bug] Advance-module Picklist values are not translating 

### ISSUE THREAD

**Issue by kseibi** [YetiForceCompany/YetiForceCRM#14959]
Hi, I am using Yetiforce 6.2 and have put a picklist field in the advance module section, and did add translations on language management in admin panel but it doesn't translate them, and this particular picklist is not visible in colors place to make colors for the advance module, could someone tell me how it is done? should I change something on the database? 

![expl](https://user-images.githubusercontent.com/74230891/125551839-3b165a5c-8499-4af5-b531-6951848b2776.jpg)

**Comment by kseibi** [comment]
I understand that it needs to be updated on Yetiforce 6.3, is there any easy method to achieve it for now? change some code or add the translation to databse manually?

**Comment by mariuszkrzaczkowski** [comment]
Does the problem still exist in the newest version?
