### ISSUE TITLE
[BUG] You can not use the characters in the enumeration data

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1496]
You can not use the Cyrillic alphabet, space, symbol number in the numbering of the data

![animation 7](https://cloud.githubusercontent.com/assets/1402355/8652448/31f84808-2998-11e5-9999-7bf2d476cdd8.gif)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1095
