### ISSUE TITLE
[bug] Call to a member function getRelationQuery() on bool

### ISSUE THREAD

**Issue by gonarich** [YetiForceCompany/YetiForceCRM#14979]
![image](https://user-images.githubusercontent.com/8708111/126077223-c0313dcc-3711-4a7d-8083-a0bb9a0cd103.png)

Any help?

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/126077419-9c76e511-7bd1-4827-a6c4-1d6dbb97e1e1.jpg)

**Comment by gonarich** [comment]
I just want to review my new project giving error Call to a member function getRelationQuery() on bool.

**Comment by rskrzypczak** [comment]
You messed up something in the relationships that the system does not detect a relationship with this module.
If you are a developer, check the correctness of the relationship, if not, better ask for support.

**Comment by gonarich** [comment]
I am not a developer.  
![image](https://user-images.githubusercontent.com/8708111/126102736-3a6f1ac0-7f70-4b04-a38c-83a13358c6a6.png)
here is log

**Comment by gonarich** [comment]
I installed a fresh Yetiforce system again and then tested add a new project giving the same error. Am I missing any Server configuration?

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/126169810-5f809459-3153-4643-b43f-e21d09b92fb1.jpg)

**Comment by gonarich** [comment]
It is not a server configuration bug. I checked on 3 different servers. Same error. 
![error](https://user-images.githubusercontent.com/8708111/126224288-6d6f3bd7-687e-4fcd-ab32-2623f2b6d6bd.gif)

**Comment by davide-alghi** [comment]
Hi @gonarich,
thanks for video, it's very useful, but there is a technical obstacle: if you don't upload all the necessary information, as @mariuszkrzaczkowski requested above, no one can help you. Please read and follow steps (1-8) and upload the necessary info for debugging.
