### ISSUE TITLE
[BUG] ERR_ILLEGAL_FIELD_VALUE on any date. Unable to save anything

### ISSUE THREAD

**Issue by zazy** [YetiForceCompany/YetiForceCRM#14974]
Hello all. My Yetiforce installation worked up to this morning, when I applyed latest update (6.2.0 SP 1; previous version was 6.2.0) I'm no longer able to save anything. Every time I try to save a record with a date field or I try to update a date field I get the error ERR_ILLEGAL_FIELD_VALUE. I'm Italian and my date format is dd/mm/yyyy. 
Up to yesterday I got no problems at all. Server configuration is not changed nor an update had been maed to the server operating system.
Seems that Yetiforce no longer "translates" data from local format to database format. Is there any new option I'm not aware of? How can I solve this? At the moment I'm unable to do anything with Yetiforce.

**Update:** If I input manually the date _19/09/2021_ I got the error. If I input the date _05/03/1925_ I got no error and the date is saved. This is e really strange behaviour. (Date format is still dd/mm/yyyy). I tryed to inser directly the DB date format like _2021-09-19_ but it's corrected from the UI in the dd/mm/yyyy format resulting in the string _13/03/25_.
**Update2:** The date _05/03/1925_ is accepted while _19/09/1925_ is not accepted. I'm really confused!

**Comment by vovpff** [comment]
Maybe real format is mm/dd/yyyy? 19th mounth can't be saved

This is just idea

**Comment by zazy** [comment]
Thank you for your suggestion. Tried your suggestion and it got even stranger. Using 09/19/2020 the date is saved successfully but the date saved is 9th july 2020 instead of 19th september 2020. Analyzing the HTML seems that the format is correct having the HTML a data-date-format attribute set to "dd/mm/yyyy". 
To exclude cache problems I tried also to clean the cache and even using the Incognito mode

**Comment by zazy** [comment]
Ok seems that there is a problem with the date format. I went in user settings and changed my date format. The only one that doesn't works is dd/mm/yyyy. If I use yyyy/mm/dd it works. If I use dd.mm.yyyy it works. I preferred the last one because it's closest to our national date notation.
Obviously this is only a workaround that let me use Yetiforce again. The problem with dd/mm/yyyy date format is still there.

**Comment by mariuszkrzaczkowski** [comment]
Check if the bug exists on gitedveloper

**Comment by zazy** [comment]
Bug exists on gitdeveloper. Logged in using italian language and english language. Changing the date format in dd/mm/yyyy in my profile preferences it will not save the record if date is 19th september 2021 in the format "19/09/2021". The date will be saved if the format is changed in dd.mm.yyyy
