### ISSUE TITLE
[BUG] File Size In Settings

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1497]
![animation 8](https://cloud.githubusercontent.com/assets/1402355/8652653/3ce6e386-2999-11e5-819d-3c1c01534e5b.gif)

**Comment by mariuszkrzaczkowski** [comment]
fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/5e9667e2c04f24fb6fef4daec3e6f760acc36ba5
