### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by butuemi** [YetiForceCompany/YetiForceCRM#14994]
Hello, guys!

I am experiencing an issue on YF 5.3.0 related to the webservice, at this point I am not sure if it is a bug or some misconfiguration related to user permission which I am not able to see, even though I triple checked User Roles&Profile.

**_No custom development was done, so it appears to be pure YetiForce CRM Core behaviour._**  

When trying to perform an action through the API on a Module record I get an error in the following case:
 - when any user has **Track changes in Module** (so at the Module level, not at record level)

In this case I receive _code 400_ with _Invalid permissions_ error as in the following image:

![image](https://user-images.githubusercontent.com/46193414/126482846-f0cb8257-1610-4adc-8bc2-7aad7aad3bd3.png)

I did a backtrace so I can follow the flow and see where it cracks. When  **Track changes in Module** is enabled for a user it goes from : 

- `/modules/ModTracker/handlers/ModTrackerHandler.php's addNotification() function` => `$notification->save();`
- ` modules\/Notification\/models\/Record.php's save() function` =>` if ($isNew && $relatedId && 'PLL_SYSTEM' === $notificationType && !\App\Privilege::isPermitted($relatedModule, 'DetailView', $relatedId, $userId))` 

_At the previous step the static method from` \App\Privilege::isPermitted()` is called inside a foreach of users, so it iterates through all the users and cracks when it hits a user that has tracking enabled. 'Detail View' permission seems to be missing for any user I test having "tracking changes for module" enabled._

_Printing the $user variable inside isPermitted() model appears to be empty, even though $userId seems to be passed correctly, but `\App\User::getUserModel($userId)` seems to be empty. _

Inside the `switch($user->get('permission_type'))` it falls under the default branch, returning` 'Invalid permissions' with code 400. `

This is the flow, I hope I explained this properly. I would really appreciate any input, what could be the issue. A recommendation about permission (but I think those are set right) or an idea about why is the $user variable empty {} inside the isPermitted static method even if $userId parameter exists.

**Comment by mariuszkrzaczkowski** [comment]
Check if the bug is on the development version

**Comment by mariuszkrzaczkowski** [comment]
in 5.3 API had bugs in the latest version have been fixed
