### ISSUE TITLE
[bug] Yetiforce Portal 2 can't connect to the Yetiforce CRM during the installation wizard

### ISSUE THREAD

**Issue by guanchgonzalez** [YetiForceCompany/YetiForceCRM#15002]
Hi,

After creating the Portal type API webservice and the user to login, as you can see on the image below:

![imagen](https://user-images.githubusercontent.com/73548289/126752485-a6b3cda3-d987-429d-89b4-f92f58638690.png)

The installation wizard fails at the first step:

![imagen](https://user-images.githubusercontent.com/73548289/126752569-2bc5b1eb-2ce2-4fca-8420-a3f58697c48c.png)

Where https://clientes.talecsystem.com is our testing CRM and https://clientesportal.talecsystem.com is our testing Portal2. Both are public domains and separate web server over the same Apache server in a sandbox machine.

**Comment by rskrzypczak** [comment]
Have you activated this service?
```
/**
 * Configuration file: Config\Api.
 */
class Api
{
	/** List of active services. Available: dav, webservice */
	public static $enabledServices = ['webservice'];
```

**Comment by guanchgonzalez** [comment]
Yes, I did it:

[apache@clientes clientes]$ grep enabledServices config/Api.php
	public static $enabledServices = [ dav, webservices, webservice ];
[apache@clientes clientes]$

**Comment by vovpff** [comment]
Maybe should be
```
public static $enabledServices = ['dav', 'webservices', 'webservice'];
```

**Comment by guanchgonzalez** [comment]
Same failure after including the single quotations.

**Comment by davide-alghi** [comment]
Hi @guanchgonzalez,
try to remove 'webservices'

**Comment by guanchgonzalez** [comment]
Same failure with these two different combinations:

- Test 1:
[apache@clientes clientes]$ grep enabledServices config/Api.php
	public static $enabledServices = ['webservice'];
[apache@clientes clientes]$

- Test 2:
[apache@clientes clientes]$ grep enabledServices config/Api.php
	public static $enabledServices = [ 'dav', 'webservice' ];
[apache@clientes clientes]$

**Comment by guanchgonzalez** [comment]
In /cache/logs/system.log:

2021-07-23 10:11:37 [error] App\Exceptions\AppException: ERR_SYSTEM_HAS_BEEN_INSTALLED in /var/www/clientesportal/modules/Install/Action/Install.php:29
Stack trace:
#0 /var/www/clientesportal/app/WebUI.php(70): YF\Modules\Install\Action\Install->checkPermission()
#1 /var/www/clientesportal/index.php(31): App\WebUI->process(Object(App\Request))
#2 /var/www/clientesportal/public_html/index.php(11): require('/var/www/client...')
#3 {main}
#0 app/WebUI.php:85  >>  App\Log->error('App\\Exceptions\\AppException: ERR_SYSTEM_HAS_BEEN_INSTALLED in modules/Install/Action/Install.php:29
Stack trace:
#0 app/WebUI.php(70): YF\\Modules\\Install\\Action\\Install->checkPermission()
#1 index.php(31): App\\WebUI->process(Object(App\\Request))
#2 public_html/index.php(11): require(\'/var/www/client...\')
#3 {main}')
#1 index.php:31  >>  App\WebUI->process()
#2 public_html/index.php:11  >>  require('index.php')
REQUEST = Array
(
    [_csrf] => sid:158defe939ead77a91770e0cd48ee3d54527a345,1627031065
    [mode] => Step3
    [lang] => es-ES
    [apiUrl] => https://clientes.talecsystem.com/
    [apiKey] => 8d7wY38rBHsnuMrRS5Ujj1tvTbNtrTKX
    [serverName] => apiyeti
    [serverPass] => Aw3535$$
    [module] => Install
    [action] => Install
)

**Comment by guanchgonzalez** [comment]
A new test, in /cache/logs/system.log:

2021-07-23 10:39:04 [warning] File not found: /var/www/clientesportal/public_html/layouts/Default/modules/Base/resources/Install.js
#0 app/Controller/View.php:121  >>  App\Log->warning('File not found: public_html/layouts/Default/modules/Base/resources/Install.js')
#1 app/Controller/View.php:296  >>  App\Controller\View->convertScripts([array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array],'js')
#2 app/Controller/View.php:225  >>  App\Controller\View->getFooterScripts()
#3 modules/Install/View/Install.php:94  >>  App\Controller\View->postProcess(true)
#4 app/WebUI.php:132  >>  YF\Modules\Install\View\Install->postProcess()
#5 app/WebUI.php:73  >>  App\WebUI->triggerPostProcess()
#6 index.php:31  >>  App\WebUI->process()
#7 public_html/index.php:11  >>  require('index.php')
REQUEST = Array
(
    [module] => Install
    [view] => Install
)

2021-07-23 10:39:38 [warning] File not found: /var/www/clientesportal/public_html/layouts/Default/modules/Base/resources/Install.js
#0 app/Controller/View.php:121  >>  App\Log->warning('File not found: public_html/layouts/Default/modules/Base/resources/Install.js')
#1 app/Controller/View.php:296  >>  App\Controller\View->convertScripts([array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array],'js')
#2 app/Controller/View.php:225  >>  App\Controller\View->getFooterScripts()
#3 modules/Install/View/Install.php:94  >>  App\Controller\View->postProcess(true)
#4 app/WebUI.php:132  >>  YF\Modules\Install\View\Install->postProcess()
#5 app/WebUI.php:73  >>  App\WebUI->triggerPostProcess()
#6 index.php:31  >>  App\WebUI->process()
#7 public_html/index.php:11  >>  require('index.php')
REQUEST = Array
(
    [module] => Install
    [view] => Install
    [_csrf] => sid:c0aa3b7301f583f6cd5949a5e299cf4d534795a4,1627033144
    [mode] => step2
    [lang] => es-ES
)


That's true, this file doesn't exists:

[apache@clientes clientesportal]$ ls -l /var/www/clientesportal/public_html/layouts/Default/modules/Base/resources/Install.js
ls: no se puede acceder a /var/www/clientesportal/public_html/layouts/Default/modules/Base/resources/Install.js: No existe el fichero o el directorio
[apache@clientes clientesportal]$ ls -l /var/www/clientesportal/public_html/layouts/Default/modules/Base/resources/
total 308
-rw-r--r-- 1 apache apache  1204 jul 14 09:32 Dashboard.js
-rw-r--r-- 1 apache apache  2168 jul 14 09:32 Dashboard.min.js
-rw-r--r-- 1 apache apache  2496 jul 14 09:32 Dashboard.min.js.map
-rw-r--r-- 1 apache apache  1815 jul 14 09:32 DetailView.js
-rw-r--r-- 1 apache apache    58 jul 14 09:32 DetailView.min.js
-rw-r--r-- 1 apache apache   100 jul 14 09:32 DetailView.min.js.map
-rw-r--r-- 1 apache apache  8141 jul 14 09:32 EditView.js
-rw-r--r-- 1 apache apache  5161 jul 14 09:32 EditView.min.js
-rw-r--r-- 1 apache apache 12835 jul 14 09:32 EditView.min.js.map
-rw-r--r-- 1 apache apache  4690 jul 14 09:32 Header.js
-rw-r--r-- 1 apache apache  3527 jul 14 09:32 Header.min.js
-rw-r--r-- 1 apache apache  9444 jul 14 09:32 Header.min.js.map
-rw-r--r-- 1 apache apache  4562 jul 14 09:32 ListView.js
-rw-r--r-- 1 apache apache  2471 jul 14 09:32 ListView.min.js
-rw-r--r-- 1 apache apache  4428 jul 14 09:32 ListView.min.js.map
-rw-r--r-- 1 apache apache  1059 jul 14 09:32 PasswordChangeModal.js
-rw-r--r-- 1 apache apache  1775 jul 14 09:32 PasswordChangeModal.min.js
-rw-r--r-- 1 apache apache  2277 jul 14 09:32 PasswordChangeModal.min.js.map
-rw-r--r-- 1 apache apache  1362 jul 14 09:32 Pdf.js
-rw-r--r-- 1 apache apache  2171 jul 14 09:32 Pdf.min.js
-rw-r--r-- 1 apache apache  2756 jul 14 09:32 Pdf.min.js.map
-rw-r--r-- 1 apache apache   741 jul 14 09:32 QuickCreateModal.js
-rw-r--r-- 1 apache apache  1527 jul 14 09:32 RecordList.min.js
-rw-r--r-- 1 apache apache  3971 jul 14 09:32 RecordList.min.js.map
-rw-r--r-- 1 apache apache  1703 jul 14 09:32 RecordListModal.js
-rw-r--r-- 1 apache apache  2140 jul 14 09:32 RelatedListView.js
drwxr-xr-x 2 apache apache    88 jul 14 09:32 Widget
-rw-r--r-- 1 apache apache 41189 jul 14 09:32 Widgets.js
-rw-r--r-- 1 apache apache 36065 jul 14 09:32 Widgets.min.js
-rw-r--r-- 1 apache apache 83021 jul 14 09:32 Widgets.min.js.map
[apache@clientes clientesportal]$

**Comment by guanchgonzalez** [comment]
By the way, both Yetiforce CRM and YetiPortal are in their last stable versions:

 - **CRM**:

[apache@clientes clientes]$ cat config/version.php
<?php

return [
	'appVersion' => '6.2.0',
	'patchVersion' => '2021.07.02',
	'lib_roundcube' => '0.1.29',
];
[apache@clientes clientes]$

**Comment by guanchgonzalez** [comment]
- **Portal**:

[apache@clientes clientesportal]$ cat config/Version.php
<?php
/**
 * System version class.
 *
 * @package Config
 *
 * @copyright YetiForce Sp. z o.o
 * @license   YetiForce Public License 4.0 (licenses/LicenseEN.txt or yetiforce.com)
 * @author    Mariusz Krzaczkowski <m.krzaczkowski@yetiforce.com>
 */

namespace Conf;

/**
 * System version class.
 */
class Version
{
	/**
	 * Application version.
	 */
	const APP = '6.2.0';
	/**
	 * Date of publication of the application.
	 */
	const DATE = '2021.07.02';
}
[apache@clientes clientesportal]$

**Comment by rskrzypczak** [comment]
Turn on debugging, you'll probably find the answer there.

https://github.com/YetiForceCompany/YetiForceCRM/blob/4a0bce46cfd89564b7c59f5ff0d8c513c969b6ef/config/Debug.php#L90-L103

https://github.com/YetiForceCompany/YetiForcePortal2/blob/728c88f246a738f6336ef0d08ea2132f37bcae97/config/Config.php#L72-L88

**Comment by guanchgonzalez** [comment]
In the Portal web server, in /cache/logs/api.log:

[apache@clientes logs]$ cat api.log 

--------------------------------------------------  2021-07-23 11:44:18  --------------------------------------------------
Trace: 
#0 app/Log/AbstractBase.php:40  >>  App\Log\Api->display([array,array],'info')
#1 app/Log.php:108  >>  App\Log\AbstractBase->log([array,array],'info')
#2 app/Log.php:90  >>  App\Log->log([array,array],'info','Api')
#3 app/Api.php:104  >>  App\Log->info([array,array],'Api')
#4 modules/Install/Model/Install.php:49  >>  App\Api->call('Install','{"data":"Install Wizard"}','PUT')
#5 modules/Install/Action/Install.php:46  >>  YF\Modules\Install\Model\Install->check()
#6 app/WebUI.php:72  >>  YF\Modules\Install\Action\Install->process()
#7 index.php:31  >>  App\WebUI->process()
#8 public_html/index.php:11  >>  require('index.php')
Method: [PUT] Install
Headers: Array
(
    [User-Agent] => YetiForce Portal | Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
    [X-Encrypted] => 0
    [X-Api-Key] => 8d7wY38rBHsnuMrRS5Ujj1tvTbNtrTKX
    [Content-Type] => application/json
    [Accept] => application/json
)

RawBody: 
Array
(
    [data] => Install Wizard
)

Body: {"data":"Install Wizard"}

Status: 405
Reason phrase: Method Not Allowed
Time: 0.32 sec.
Error: Invalid response content type
 Accept:application/json <> text/html; charset=iso-8859-1
Headers: Array
(
    [Date] => Fri, 23 Jul 2021 10:44:18 GMT
    [Server] => Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
    [Allow] => GET,HEAD,POST,OPTIONS,TRACE
    [Content-Length] => 235
    [Content-Type] => text/html; charset=iso-8859-1
)

RawBody: 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method PUT is not allowed for the URL /Portal/Install.</p>
</body></html>


--------------------------------------------------  2021-07-23 11:44:18  --------------------------------------------------
Trace: 
#0 app/Log/AbstractBase.php:40  >>  App\Log\Api->display([array,array],'info')
#1 app/Log.php:108  >>  App\Log\AbstractBase->log([array,array],'info')
#2 app/Log.php:90  >>  App\Log->log([array,array],'info','Api')
#3 app/Api.php:123  >>  App\Log->info([array,array],'Api')
#4 modules/Install/Model/Install.php:49  >>  App\Api->call('Install','{"data":"Install Wizard"}','PUT')
#5 modules/Install/Action/Install.php:46  >>  YF\Modules\Install\Model\Install->check()
#6 app/WebUI.php:72  >>  YF\Modules\Install\Action\Install->process()
#7 index.php:31  >>  App\WebUI->process()
#8 public_html/index.php:11  >>  require('index.php')
Method: [PUT] Install
Headers: Array
(
    [User-Agent] => YetiForce Portal | Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
    [X-Encrypted] => 0
    [X-Api-Key] => 8d7wY38rBHsnuMrRS5Ujj1tvTbNtrTKX
    [Content-Type] => application/json
    [Accept] => application/json
)

RawBody: 
Array
(
    [data] => Install Wizard
)

Body: {"data":"Install Wizard"}

Status: 405
Reason phrase: Method Not Allowed
Time: 0.33 sec.
Error: App\Exceptions\AppException: Invalid response content type in /var/www/clientesportal/app/Api.php:106
Stack trace:
#0 /var/www/clientesportal/modules/Install/Model/Install.php(49): App\Api->call('Install', '{"data":"Instal...', 'PUT')
#1 /var/www/clientesportal/modules/Install/Action/Install.php(46): YF\Modules\Install\Model\Install->check()
#2 /var/www/clientesportal/app/WebUI.php(72): YF\Modules\Install\Action\Install->process()
#3 /var/www/clientesportal/index.php(31): App\WebUI->process(Object(App\Request))
#4 /var/www/clientesportal/public_html/index.php(11): require('/var/www/client...')
#5 {main}
Headers: Array
(
    [Date] => Fri, 23 Jul 2021 10:44:18 GMT
    [Server] => Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
    [Allow] => GET,HEAD,POST,OPTIONS,TRACE
    [Content-Length] => 235
    [Content-Type] => text/html; charset=iso-8859-1
)

RawBody: 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method PUT is not allowed for the URL /Portal/Install.</p>
</body></html>


REQUEST = Array
(
    [_csrf] => sid:e175351d82659dd3926e81a20745bc958b015a52,1627037019
    [mode] => Step3
    [lang] => es-ES
    [apiUrl] => https://clientes.talecsystem.com/
    [apiKey] => 8d7wY38rBHsnuMrRS5Ujj1tvTbNtrTKX
    [serverName] => apiyeti
    [serverPass] => ********
    [module] => Install
    [action] => Install
)
[apache@clientes logs]

**Comment by guanchgonzalez** [comment]
How can I fix the 405 HTTP error?

I tried several ways to set the AllowMethods directive in the VirtualHost in Apache, but the CRM never get this configuration.

**Comment by guanchgonzalez** [comment]
| Environment                                           | Version / Name                                       |
| ---------------------------------------------------- | ----------------------------------------------------------------------- |
| YetiForce                                                | 6.2.0                                                                               |
| Web server (name and version)             | Apache/2.4.6 (CentOS)                                                 |
| PHP                                                        |  7.3.29                                                                           |
| Browser (name and version)                  | Google Chrome 92.0.4515.107 on Fedora 33 x86_64  |
| Operating System (name and version)   | CentOS Linux release 7.9.2009 (Core)                         |
| Database (name and version)                | 10.5.11-MariaDB Server                                               |
| Service Pack version                              | N/A                                                                                |

**Comment by guanchgonzalez** [comment]
And you have the same mismatch in your GitStable version of YetiForce CRM:

![YetiForceCRM_allowHTTPmethods_wrong](https://user-images.githubusercontent.com/73548289/127130614-51d4238e-2202-48b3-8995-92b0fb1702d3.jpg)

**Comment by guanchgonzalez** [comment]
Do you have any update?

**Comment by mariuszkrzaczkowski** [comment]
I updated the installation description and added debugging, attach all logs
https://github.com/YetiForceCompany/YetiForcePortal2#-installation
https://github.com/YetiForceCompany/YetiForcePortal2#-debug

**Comment by guanchgonzalez** [comment]
All these step you added to the README.md are already done in our sandbox after you proposed them 10 days ago.
As I told you, the same mismatch configuration exists in your GitStable version, [My Home Page > Software Configuration > Logs > Server Configuration](https://gitstable.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index)
Do you have available the right configuration for an Apache deployment of the two Virtual Hosts, the CRM and the Portal? Or is a code issue?

**Comment by mariuszkrzaczkowski** [comment]
you have a problem in apache configuration, look for something like this:
```
<Limit GET HEAD POST PUT DELETE OPTIONS>
# Deprecated apache 2.2 syntax:
# Order Allow,Deny
# Allow from all
# Apache > 2.4 requires:
Require all granted
</Limit>
```

```
AllowMethods GET HEAD POST PUT DELETE OPTIONS
```

https://www.google.com/search?q=the+requested+method+put+is+not+allowed+for+this+url+apache2

**Comment by guanchgonzalez** [comment]
Firstible, we don't use the Limit directive, due is drepecated in last versions of Apache. Instead of we use "AllowMethods" directive:

`<IfModule mod_ssl.c>
   <VirtualHost *:443>
      DocumentRoot /var/www/YetiForceCRM/public_html
      ServerName yetiforcecrm.talecsystem.com
      <Directory /var/www/YetiForceCRM/public_html>
         AllowMethods GET POST PUT OPTIONS PATCH PROPFIND REPORT LOCK DELETE COPY MOVE
         Require all granted
         AllowOverride All
      </Directory>
      ErrorLog /var/log/httpd/YetiForceCRM/error.log
      CustomLog /var/log/httpd/YetiForceCRM/access.log combined
. . .`

In the other hand, as we told you 7 days ago, you suffer the same issue in your demos.

If you check your access.log you can find several request respoonding with an 405 HTML errors for the same methods, while the rest of the request to other routes give a 200 OK response. You should inspect internally your code. The first failure appears during the YetiPortal2 Installation Wizard execution, but is not the only one.

**Comment by mariuszkrzaczkowski** [comment]
The wizard has been tested several times and even on the server where the demo is available, and all the errors that were found have been fixed.
Attach the full request (raw request) that gets a 405 error code

**Comment by guanchgonzalez** [comment]
The raw request is available in our comment 11 days ago:

_In the Portal web server, in /cache/logs/api.log:

[apache@clientes logs]$ cat api.log

-------------------------------------------------- 2021-07-23 11:44:18 --------------------------------------------------_

**Comment by guanchgonzalez** [comment]
The access.log:


[apache@clientes YetiForceCRM]$ grep PUT access.log | grep '" 40'
185.230.239.236 - - [27/Jul/2021:13:49:42 +0100] "PUT /Portal/Install HTTP/1.1" 405 235 "-" "YetiForce Portal | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36"
185.230.239.236 - - [27/Jul/2021:14:20:47 +0100] "PUT /Portal/Install HTTP/1.1" 405 235 "-" "YetiForce Portal | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36"
[apache@clientes YetiForceCRM]$


[apache@clientes YetiForceCRM]$ grep PUT access.log | grep '" 20'
185.230.239.236 - - [27/Jul/2021:11:17:13 +0100] "PUT /token.php HTTP/1.1" 200 8 "-" "YetiForceCRM/6.2.24"
185.230.239.236 - - [27/Jul/2021:12:40:09 +0100] "PUT /token.php HTTP/1.1" 200 8 "-" "YetiForceCRM/6.2.24"
. . .
185.230.239.236 - - [03/Aug/2021:09:06:02 +0100] "PUT /token.php HTTP/1.1" 200 8 "-" "YetiForceCRM/6.2.0"
185.230.239.236 - - [03/Aug/2021:09:06:03 +0100] "PUT /token.php HTTP/1.1" 200 8 "-" "YetiForceCRM/6.2.24"
[apache@clientes YetiForceCRM]$ 


[apache@clientes YetiForceCRM]$ grep '" 40' access.log | egrep -v "PUT|HEAD"
185.230.239.194 - - [27/Jul/2021:13:04:37 +0100] "POST /index.php HTTP/1.1" 401 72 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36"
185.230.239.236 - - [29/Jul/2021:09:56:27 +0100] "POST /Portal/Users/Login HTTP/1.1" 404 216 "-" "YetiForce Portal | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
185.230.239.236 - apicrm [29/Jul/2021:10:54:08 +0100] "POST /webservice/Portal/Users/ResetPassword HTTP/1.1" 404 644 "-" "YetiForce Portal | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
185.230.239.236 - apicrm [29/Jul/2021:11:00:02 +0100] "POST /webservice/Portal/Users/ResetPassword HTTP/1.1" 404 644 "-" "YetiForce Portal | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
. . .
91.218.65.239 - - [30/Jul/2021:14:45:46 +0100] "GET /db/index.php?lang=en HTTP/1.1" 404 210 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
91.218.65.239 - - [30/Jul/2021:14:45:47 +0100] "GET /pma2017/index.php?lang=en HTTP/1.1" 404 215 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
. . .
141.98.83.139 - - [01/Aug/2021:10:47:27 +0100] "GET /owa/auth.owa HTTP/1.1" 404 210 "-" "Spider"
192.241.216.29 - - [01/Aug/2021:11:05:03 +0100] "GET /owa/auth/logon.aspx?url=https%3a%2f%2f1%2fecp%2f HTTP/1.1" 404 217 "-" "Mozilla/5.0 zgrab/0.x"
205.185.115.135 - - [01/Aug/2021:11:07:16 +0100] "POST /boaform/admin/formLogin HTTP/1.1" 404 221 "http://185.230.239.236:80/admin/login.asp" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
. . .
45.146.164.110 - - [03/Aug/2021:04:42:29 +0100] "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 404 248 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
91.134.146.186 - - [03/Aug/2021:04:54:04 +0100] "GET //wp-includes/wlwmanifest.xml HTTP/1.1" 404 225 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
. . .
[apache@clientes YetiForceCRM]$

**Comment by mariuszkrzaczkowski** [comment]
>The raw request is available in our comment 11 days ago:

no, this is not what a RAW request looks like
see my example

```
PUT /webservice/Portal/Install HTTP/1.1
x-api-key: VMUwRByXHSq1bLW485ikfvcC97P6gJsz
Content-Type: application/json
x-token: a6ceaf8a37176c0b64d581ae49c61e22ef7d812afccba1b73dd6a0a95d2c8a86
Authorization: Basic cGFydG5lcjpwYXJ0bmVy
User-Agent: PostmanRuntime/7.28.2
Accept: */*
Cache-Control: no-cache
Host: yeti
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 25
 
{"data":"Install Wizard"}
 
HTTP/1.1 200 OK
Date: Tue, 03 Aug 2021 08:42:47 GMT
Server: Apache/2
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
Expect-CT: enforce; max-age=3600
X-Robots-Tag: none
Access-Control-Allow-Origin: *
Cache-Control: private, no-cache, no-store, must-revalidate, post-check=0, pre-check=0
Access-Control-Allow-Methods: PUT
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, x-api-key, x-encrypted, x-token
Encrypted: 0
Content-disposition: attachment; filename="api.json"
Content-Length: 38
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json
 
{"status":1,"result":"Install Wizard"}
```

**Comment by guanchgonzalez** [comment]
How can we generate a curl request simulating the Installation Wizard process?

**Comment by mariuszkrzaczkowski** [comment]
e.g. Postman  or another API client

**Comment by mariuszkrzaczkowski** [comment]
see documentation https://doc.yetiforce.com/api/?urls.primaryName=Portal#/BaseAction/02a0b167fa2ba08237b79041d6c2eb40

```
curl -X 'PUT' \
  'https://gitdeveloper.yetiforce.com/webservice/Portal/Install' \
  -H 'accept: application/json' \
  -H 'X-ENCRYPTED: 0' \
  -H 'Authorization: Basic cG9ydGFsOnBvcnRhbA==' \
  -H 'X-API-KEY: VMUwRByXHSq1bLW485ikfvcC97P6gJsz' \
  -H 'Content-Type: application/json' \
  -d '{"data":"Install Wizard"}'
```
![image](https://user-images.githubusercontent.com/10198654/127987086-30cbb590-cf64-44bf-9053-b557734e042e.png)

**Comment by guanchgonzalez** [comment]
Why this check fails in your own demo?

![YetiForceCRM_allowHTTPmethods_wrong](https://user-images.githubusercontent.com/73548289/127993899-37873316-c6da-4423-8f8b-38309484c6fb.jpg)

**Comment by guanchgonzalez** [comment]
We requested you twice by email a budget to execute a CRM+Portal2 installation on premise in our sandbox to get a functional deployment ASAP. Can you help with this?

**Comment by guanchgonzalez** [comment]
On this deployment we need to create contacts that can login into Customer Portal and access to its own account info: products, contracts, projects, documents, issues, etc.

**Comment by guanchgonzalez** [comment]
We sent both emails to devs@yetiforce.com

**Comment by mariuszkrzaczkowski** [comment]
> Why this check fails in your own demo?
> 
> ![YetiForceCRM_allowHTTPmethods_wrong](https://user-images.githubusercontent.com/73548289/127993899-37873316-c6da-4423-8f8b-38309484c6fb.jpg)

This is a bug in version 6.2 and has now been fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/68045b233de085ebfeca1035aa8daff91739cdea

**Comment by mariuszkrzaczkowski** [comment]
> We requested you twice by email a budget to execute a CRM+Portal2 installation on premise in our sandbox to get a functional deployment ASAP. Can you help with this?

We have not received an email

**Comment by mariuszkrzaczkowski** [comment]
> We sent both emails to [devs@yetiforce.com](mailto:devs@yetiforce.com)

**Comment by mariuszkrzaczkowski** [comment]
> We sent both emails to [devs@yetiforce.com](mailto:devs@yetiforce.com)

This address is for other purposes
You have the current data on the website https://yetiforce.com/en/company/contact

**Comment by KatarzynaUlichnowska** [comment]
Hello, please send us an e-mail with a detailed description of your requirements (attach screenshots if necessary) and the ConfReport file downloaded from the system (System settings -> Logs -> Server configuration -> Download configuration). The correct e-mail address for questions and quotes is hello@yetiforce.com.

**Comment by guanchgonzalez** [comment]
Please check your email.

**Comment by kassimg12** [comment]
Hello there, I have a related issue regarding yetiforce portal installation. when I try to install the portal it shows "An error occurred while communicating with the CRM"

I installed the latest version of yetiforce (6.20) and a portal which is available on the following link https://github.com/YetiForceCompany/YetiForcePortal2

my server is ubuntu 20.04 os.

please help.
Thank you!

**Comment by kassimg12** [comment]
![yeti portal](https://user-images.githubusercontent.com/65815933/128388558-40d4ee4d-e69b-45c0-95fb-0bfe3c79e441.JPG)
here is the screenshot of the above request.
