### ISSUE TITLE
[bug] Role profiles works bad

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#15016]
# 🐞 bug report

### ⁉️ Describe the bug

User permissions works bad. 

### 🔥 How to trigger the error

For example on gitdev I try to disable ability to remove relations in Opportunity module.

1) I duplicate `Administator` profile with no ability to remove relations:

![image](https://user-images.githubusercontent.com/8545791/127334028-2f57534f-b50f-4a71-bed9-d1a6fbe66467.png)
 
2) Modification of Secretary role. Profile changed from `Administarator` to brand new profile `Administrator1`

![image](https://user-images.githubusercontent.com/8545791/127334391-68ca4d99-c418-4993-b2c3-1521baddf3bb.png)

3) Login as `demo` user. Go to some Opportunity -> Contacts tab -> click to wrench 

![image](https://user-images.githubusercontent.com/8545791/127334627-7300086c-782c-419d-80f3-2e932de6b581.png)

### 👎 Actual Behavior

Profile values ignored

### 👍 Expected Behavior

User rights should be as set in profile

### 👷 Testing

- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | gitdev 6.2.25

### ❓ Additional context

I found this problem on my local 6.1 system. But I has inverse problem. I need to give ability to remove relations but this can't be done.

**Comment by vovpff** [comment]
I has checked what permission to action always `0` for working well profile/for bad profile/for admin profile.

```
SELECT *  FROM `vtiger_profile2utility` WHERE `profileid` = 81 AND `tabid` = 86 AND `activityid` = 46

81	86	46	0	

SELECT *  FROM `vtiger_profile2utility` WHERE `profileid` = 72 AND `tabid` = 86 AND `activityid` = 46

72	86	46	0	

SELECT *  FROM `vtiger_profile2utility` WHERE `profileid` = 1 AND `tabid` = 86 AND `activityid` = 46

1	86	46	0	
```

**Comment by vovpff** [comment]
After digging deep I found what user with ability to remove relation should have ability to delete record and to move record to trash.

```
			$privilegeToDelete = $relationModel->privilegeToDelete();
			if ($privilegeToDelete && $this->privilegeToMoveToTrash()) {
...
			}
```

Also there is function

```
	public function privilegeToDelete()
	{
		if (!isset($this->privileges['Deleted'])) {
			$this->privileges['Deleted'] = \App\Privilege::isPermitted($this->getModuleName(), 'Delete', $this->getId()) && false === Users_Privileges_Model::checkLockEdit($this->getModuleName(), $this) && !$this->isLockByFields();
		}
		return $this->privileges['Deleted'];
	}
```

This function deny ability to delete record and I can't understand how to reach all conditions for remove relation...

**Comment by rskrzypczak** [comment]
I  think that in this particular case there indeed is no point verifying the permissions to move to trash.
At the first glance the listed conditions should be enough.
This should, however, be globally set and verified for actions and views
https://github.com/YetiForceCompany/YetiForceCRM/blob/d0528ee00cbbb194b14cbab2203de8b93ced56da/modules/Vtiger/models/Relation.php#L521-L533
We'll think about it, and it will likely be improved in v6.3.

**Comment by vovpff** [comment]
@rskrzypczak yes. I think so.

I checked what actual code is little bit different than my local 6.1.

There is no logic what user need to have a lot of rights like delete record just for simple unlinking related record

P.S. To achieve possibility for unlinking contact from opportunity in 6.1 profile should have ability to delete, move to trash and remove relation for contact module, not for opportunity.
