### ISSUE TITLE
6.1 to 6.2 Update error 

### ISSUE THREAD

**Issue by kassimg12** [YetiForceCompany/YetiForceCRM#15013]
Hello there,

I recently updated my yetiforce installation from 6.1 to 6.2. after finalizing the update the page opens pages without CSS (no layout and list of modules, setting, and other links)
please help.

my installation is on ubuntu 20.04 server.

**Comment by rskrzypczak** [comment]
Try this: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-clear-browser-cache
and do a hard page reload: 
![image](https://user-images.githubusercontent.com/10221999/127095135-aba60cf6-c882-439d-a753-b036b260b4bb.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/127103212-bdf3cdbf-7873-4d7d-8d98-12a413b75bf3.jpg)
