### ISSUE TITLE
[BUG] Add Event in Calendar

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1501]
![animation 11](https://cloud.githubusercontent.com/assets/1402355/8653308/1b01cc50-299d-11e5-97fb-2d4fd55a1893.gif)

**Comment by rskrzypczak** [comment]
![held1](https://cloud.githubusercontent.com/assets/10221999/8667460/8b563988-2a00-11e5-9b2c-9d468a968605.jpg)
