### ISSUE TITLE
Cannot activate HTTP-METHOD

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#15014]
Hello Everyone!

Installing the last version of Yetiforce it seems we are not able to activate http-method on Centos 7 and Apache 2.4.6:

![image](https://user-images.githubusercontent.com/40429279/127121424-99750884-5daf-4e47-9735-bcfc191b9f20.png)

This is the code we are using at the vhost

`<IfModule mod_ssl.c>
   <VirtualHost *:443>
      DocumentRoot /var/www/clientes/public_html
      ServerName myhost.com
      <Directory /var/www/clientes/public_html>
         AllowMethods GET POST PUT OPTIONS PATCH PROPFIND REPORT LOCK DELETE COPY MOVE
         Require all granted
         AllowOverride All
      </Directory>
      SSLCertificateFile /etc/letsencrypt/live/myhost.com/cert.pem
      SSLCertificateKeyFile /etc/letsencrypt/live/myhost.com/privkey.pem
      Include /etc/letsencrypt/options-ssl-apache.conf
      SSLCertificateChainFile /etc/letsencrypt/live/myhost.com/chain.pem
   </VirtualHost>
</IfModule>`

![image](https://user-images.githubusercontent.com/40429279/127121878-768baa0c-bd08-4a59-a6f3-834337abe1e0.png)

The module is being loaded.

Do you have any procedure to solve this?

Thank you in advance,
Best regards
Santy

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/127124980-7b4804fc-cb48-44b9-bb99-e5586e3e0fa5.jpg)
