### ISSUE TITLE
Dashboard is not displaying widgets 

### ISSUE THREAD

**Issue by nvieth** [YetiForceCompany/YetiForceCRM#15025]
Hello, 
I just installed YetiForceCRM on my server. Everything seems to have installed correctly, however I went into settings and and went under standard modules and modified the dashboard widgets, however when I create the widget it is not displaying on the dashboard. Also I am still waiting for my registration to go through even though I filled out the registration form. Could this be causing the widgets not to load on my dashboard? If you can please help me with this issue I would greatly appreciate it. 

Thank you, 
~Nathan Vieth

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/127924677-68f457cd-b42f-40a5-ade6-9dc29ba2b899.jpg)

**Comment by rskrzypczak** [comment]
Are you sure you added the widget for the correct role?
Besides, remember that if you have not made the widget mandatory, it will not add itself to the desktop but it will appear under the button.
![image](https://user-images.githubusercontent.com/10221999/127955552-172467a7-dc5c-499c-947a-399076b6450e.png)

**Comment by nvieth** [comment]
Hello, 

I am sending you this message because I am having a major issue with my YetiForce, When I tried logging into the system today, I see this error message. The domain in question is https://www.netserv.biz/erp

 

Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". 

 

Can you please tell me how to resolve this issue? The system was running fine for about three weeks with no errors. 

 

Thank you. 

 

Nathan A. Vieth, B.S.

NetServ Solutions LLC

Level III Linux Systems Administrator 

Email:  ***@***.***> ***@***.***

Direct: 414-712-2257

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/131563941-cca9893a-f904-4e18-bc5d-3dc21d10bceb.jpg)

**Comment by nvieth** [comment]
So, I am getting this error in the error_log: 
[31-Aug-2021 14:41:49 America/Chicago] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 5.6.40. in /home2/netserv/public_html/erp/vendor/composer/platform_check.php on line 25

I just went and upgraded my php version. PHP Version 5.6.40 was upgraded to version PHP Version 7.3.29

I am still getting the error at https://www.netserv.biz/erp

**Comment by nvieth** [comment]
Please disregard last message, the server is working and the system is now up and running. Thank you for your assistance.
