### ISSUE TITLE
[bug] Call to a member function updateSession()

### ISSUE THREAD

**Issue by guanchgonzalez** [YetiForceCompany/YetiForceCRM#15038]
🐞 bug report

An error appears during any operation in cache/logs/system.log. After a while, the platform finish the operation, but a lot of error traces are logged.

Error: Call to a member function updateSession() on null in /var/www/YetiForceCRM/api/webservice/Controller.php:229

⁉️ Describe the bug

We installed the last version of the CRM platform yesterday from Git (with yarn and composer). A lot of times the same errors appears in log files. We guess they are triggered by user actions.

We don't faced this kind of errors never before.

### 🔥 How to trigger the error

Steps to reproduce the behaviour:

1. Go to Página Principal > Empresas y Contactos > Empresas
2. Click on +Añadir
3. Insert the mandatory data account into the form fields
4. Clik on Guardar
5. Check the errors in cache/logs/ path, in system.log, webserviceErrors.log y webserviceDebug.log files.

### 👎 Actual Behavior

The data become registered in database and the list screen appears after a while, but there are recurrent errors in log files.

### 👍 Expected Behavior

No errors should be appears.

 👷 Testing

We can't check the errors in your servers. We can't login on them.

 📷 Screenshot of configuration

![imagen](https://user-images.githubusercontent.com/73548289/128366076-2d21736c-5726-449b-b0da-32b7812d2259.png)

![imagen](https://user-images.githubusercontent.com/73548289/128366187-f6d893b0-9f11-4d27-aa26-36b4744cfaf1.png)

![imagen](https://user-images.githubusercontent.com/73548289/128366305-75c34e41-d913-4632-ba94-c6ecc145d224.png)

![imagen](https://user-images.githubusercontent.com/73548289/128366394-21db3f7d-9b58-43d4-88dc-f5023d2cb5bb.png)

![imagen](https://user-images.githubusercontent.com/73548289/128366497-2dc72a8a-5ffa-4599-b746-2547c4819be5.png)

 📝 PHP/Apache/Nginx/Browser/CRM Logs

cache/logs/system.log:

===============================================================================================
2021-08-05 08:16:59.8735 [error] - Unauthorized
Api\Core\Exception: Unauthorized in /var/www/YetiForceCRM/api/webservice/Core/Auth/Basic.php:24
Stack trace:
#0 /var/www/YetiForceCRM/api/webservice/Core/Auth.php(39): Api\Core\Auth\Basic->authenticate('YetiForceApi')
#1 /var/www/YetiForceCRM/api/webservice/Controller.php(87): Api\Core\Auth::init(Object(Api\Controller))
#2 /var/www/YetiForceCRM/webservice.php(23): Api\Controller->preProcess()
#3 /var/www/YetiForceCRM/public_html/webservice.php(13): require('/var/www/YetiFo...')
#4 {main}
2021-08-05 08:16:59.8735 [error] - Call to a member function updateSession() on null
Error: Call to a member function updateSession() on null in /var/www/YetiForceCRM/api/webservice/Controller.php:229
Stack trace:
#0 /var/www/YetiForceCRM/webservice.php(30): Api\Controller->handleError(Object(Api\Core\Exception))
#1 /var/www/YetiForceCRM/public_html/webservice.php(13): require('/var/www/YetiFo...')
#2 {main}
2021-08-05 08:16:56.2515 [info][application] -
$_GET = [
    '_container' => 'RestApi'
    'action' => ''
]
$_POST = []
$_FILES = []
$_COOKIE = []
HEADERS = [
    'User-Agent' => 'YetiForceCRM/6.2.33'
    'Host' => 'yetiforcecrm.talecsystem.com'
]
$stability = [
    'output_buffering' => '1'
    'max_input_time' => '600'
]
$security = [
    'session.cookie_secure' => 'Off'
]
$environment = [
    'openssl.cafile' => false
    'openssl.capath' => false
]
$functionalVerification = [
    'shop' => 'YetiForceApiPortal(32)'
]
$headers = [
    'Header: access-control-allow-methods' => false
    'Header: access-control-allow-origin' => false
    'Header: referrer-policy' => false
    'Header: expect-ct' => false
    'Header: x-frame-options' => false
    'Header: x-xss-protection' => false
    'Header: x-content-type-options' => false
    'Header: x-robots-tag' => false
    'Header: x-permitted-cross-domain-policies' => false
    'Header: strict-transport-security' => false
    'Header: content-security-policy' => false
]
$pathVerification = [
    'webservice/RestApi/' => false
]
===============================================================================================

cache/logs/webserviceErrors.log:

============ Error exception ====== 2021-08-05 08:17:00 ======
code: 0 | message: Call to a member function updateSession() on null
file: /var/www/YetiForceCRM/api/webservice/Controller.php (229)
============ stacktrace:
#0 /var/www/YetiForceCRM/public_html/webservice.php(13): require()
#1 {main}
============ Request fbac5ef4 ======  2021-08-05 08:16:59  ======
REQUEST_METHOD: HEAD
REQUEST_URI: /webservice/RestApi/
QUERY_STRING: _container=RestApi&action=
PATH_INFO:
IP: 185.230.239.236
----------- Headers -----------
user-agent: YetiForceCRM/6.2.33
host: yetiforcecrm.talecsystem.com
----------- Request data -----------
Array
(
    [_container] => RestApi
    [action] =>
)

----------- _GET -----------
Array
(
    [_container] => RestApi
    [action] =>
)

cache/logs/webserviceDebug.log:

============ Request fbac5ef4 (Response) ======  2021-08-05 08:16:59  ======
REQUEST_METHOD: HEAD
REQUEST_URI: /webservice/RestApi/
QUERY_STRING: _container=RestApi&action=
PATH_INFO:
IP: 185.230.239.236
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Unauthorized
            [code] => 401
            [file] => api/webservice/Core/Auth/Basic.php
            [line] => 24
            [backtrace] => #0 api/webservice/Core/Auth/Basic.php (24)  >>  Api\Core\Exception->__construct('Unauthorized',401)
#1 api/webservice/Core/Auth.php (39)  >>  Api\Core\Auth\Basic->authenticate('YetiForceApi')
#2 api/webservice/Controller.php (87)  >>  Api\Core\Auth->init()
#3 webservice.php (23)  >>  Api\Controller->preProcess()
#4 public_html/webservice.php (13)  >>  require('webservice.php')
        )

)

 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |      6.2.33 (   2021.08.04)               |
| Web server (name and version)       |       Apache/2.4.6 (CentOS)         |
| PHP                                 |       7.3.29         |
| Browser (name and version)          |       Google Chrome 92.0.4515.131 64bits         |
| Operating System (name and version) |       CentOS Linux release 7.9.2009 (Core)         |
| Database (name and version)         |       10.5.11-MariaDB MariaDB Server         |
| Service Pack version                |       N/A         |

 ❓ Additional context

❗️ Inform the community if you solve the problem

**Comment by guanchgonzalez** [comment]
These errors was logged until the first login into the CRM website:

MariaDB [yfcrm]> select cast(date_format(date, '%Y-%m-%d %H:%i:00') as datetime), count(1) from o_yf_access_for_api
    -> group by cast(date_format(date, '%Y-%m-%d %H:%i:00') as datetime)
    -> order by cast(date_format(date, '%Y-%m-%d %H:%i:00') as datetime);

+----------------------------------------------------------+----------+
| cast(date_format(date, '%Y-%m-%d %H:%i:00') as datetime) | count(1) |
+----------------------------------------------------------+----------+
| 2021-08-04 15:47:00                                      |        1 |
| 2021-08-04 18:40:00                                      |       84 |
| 2021-08-04 18:41:00                                      |       46 |
| 2021-08-04 18:42:00                                      |        8 |
| 2021-08-04 18:57:00                                      |      119 |
| 2021-08-04 18:58:00                                      |       28 |
| 2021-08-04 19:13:00                                      |      172 |
| 2021-08-04 19:14:00                                      |       47 |
+----------------------------------------------------------+----------+
8 rows in set (6.978 sec)

**Comment by mariuszkrzaczkowski** [comment]
Correct the server configuration two parameters are set incorrectly: output_buffering , max_input_time
Run API debugging and send logs to us
