### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by kassimg12** [YetiForceCompany/YetiForceCRM#15039]
# 🐞 Yetiforce Portal 2 installation error

Hello there, I have a related issue regarding yetiforce portal installation. when I try to install the portal it shows "An error occurred while communicating with the CRM"

### 🔥 How to trigger the error

installing yetiforce portal

### 👎 Actual Behavior

Shows error message "An error occurred while communicating with the CRM"

### 👍 Expected Behavior

install yetiforce portal

### 👷 Testing

- [ x] I confirm that I tested it at https://gitstable.yetiforce.com
- [ x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
![yeti portal](https://user-images.githubusercontent.com/65815933/128389146-4107489b-63c0-4325-8d49-a86b6fc075ec.JPG)

**Comment by mariuszkrzaczkowski** [comment]
Have you followed all the steps of the instruction: https://github.com/YetiForceCompany/YetiForcePortal2#-installation
Run debugging and check logs https://github.com/YetiForceCompany/YetiForcePortal2#-debug

**Comment by leo719044** [comment]
you should do it 

Activation of Webservice/API services (CRM file config/Api.php)
/** List of active services. Available: dav, webservice */
public static $enabledServices = [ 'webservice'];

**Comment by kassimg12** [comment]
Thank you for responding.
I could follow the steps as follows. Please check my steps

1. Put files on web server **(Done)**
2. Point web server document root to public_html directory (**i put the file on a subdomain for portal  'subdomainname/public_html' folder)**
3. Run:
yarn install --modules-folder "./public_html/libraries" --ignore-optional **(This is not working on my environment showing error message '**yarn: error: no such option: --modules-folder'**)**
composer install **(Done)**
4. Activation of Webservice/API services (CRM file config/Api.php) **(Done)**
       /** List of active services. Available: dav, webservice */
               public static $enabledServices = [ 'webservice'];
5. Add applications and API users **(Done)**
My home page / Software configuration / Integration / Web service - Applications
My home page / Software configuration / Integration / Web service - Users
6. Adjust configuration

Thank you!

**Comment by rskrzypczak** [comment]
Download complete version from here: https://github.com/YetiForceCompany/YetiForcePortal2/releases
 or development version: https://github.com/YetiForceCompany/YetiForcePortal2#where-else-can-you-find-yetiforce
`Complete` - with dependencies

Then you can skip step 3, i.e. yarn install, composer install
