### ISSUE TITLE
[bug] FieldsDependency don`t work for multipicklist field

### ISSUE THREAD

**Issue by aveblackmetalstudio** [YetiForceCompany/YetiForceCRM#15049]
FieldsDependency listener binds to this field insted of select field
https://github.com/YetiForceCompany/YetiForceCRM/blob/c31477b556b372c7fa8642509aedb2fafb0b4f49/layouts/basic/modules/Vtiger/Edit/Field/MultiPicklist.tpl#L23

https://github.com/YetiForceCompany/YetiForceCRM/blob/c31477b556b372c7fa8642509aedb2fafb0b4f49/public_html/layouts/basic/modules/Vtiger/resources/Edit.js#L1486

**Comment by s2b-git** [comment]
Is there a solution for this? Here is not working too. Thanks
