### ISSUE TITLE
[bug] comment of TICKET not showing in "ACCOUNT - > SUMMARY -> COMMENTS -> RELATED RECORDS"

### ISSUE THREAD

**Issue by leo719044** [YetiForceCompany/YetiForceCRM#15045]
# 🐞 bug report

Comment of TICKET not showing in "ACCOUNT - > SUMMARY -> COMMENTS -> RELATED RECORDS"

### 🔥 How to trigger the error

1. Add comment to the tickets. 
2. Go to the account which ticket belongs to. 
3. Go to the section ACCOUNT - > SUMMARY -> COMMENTS -> RELATED RECORDS. 
4. Comments of ticket was not found in RELATED RECORDS.

### 👎 Actual Behavior

Can not find the comments in  "ACCOUNT - > SUMMARY -> COMMENTS -> RELATED RECORDS" after adding comments to TICKET

### 👍 Expected Behavior

All comments should be showed in "ACCOUNT - > SUMMARY -> COMMENTS -> RELATED RECORDS" as far as I understood.

### 👷 Testing

Same problem was found at  https://gitstable.yetiforce.com

**Comment by vovpff** [comment]
I has the same in my 6.1. I think you can tune this in `app_data/moduleHierarchy.php` file.

**Comment by vovpff** [comment]
@leo719044 replace

```
'HelpDesk' => ['level' => 2, 'parentModule' => 'ServiceContracts'],
```

with

```
'HelpDesk' => ['level' => 1],
```

in `app_data/moduleHierarchy.php`

**Comment by leo719044** [comment]
thanks for your help. it works perfectly.
