### ISSUE TITLE
[bug] comments of ticket and opportunities not showing in "account->summary->comment->related records"

### ISSUE THREAD

**Issue by leo719044** [YetiForceCompany/YetiForceCRM#15044]
Bug 1. The comment of ticket is not showing in the section "Comment" of account summary 

Bug 2. When giving reply to the ticket or opportunities in the section "Comment" of account summary , the reply comment is not going to reflect to ticket or opportunities

**Comment by mariuszkrzaczkowski** [comment]
Each bug should be reported separately and with a full description

![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/128600823-80ab7a86-cd9c-4bcb-ad6b-393550d780e4.jpg)

**Comment by vovpff** [comment]
1st is tunable.

Difficult to understand what you mean for 2nd bug
