### ISSUE TITLE
[bug] Portal2 - wrong JS paths

### ISSUE THREAD

**Issue by vencatoitc** [YetiForceCompany/YetiForceCRM#15048]
# 🐞 bug report

## ⁉️ Can't perform "Forgot password" action

After a fresh install I enable a user to access the portal; then I'd like to reset the password but It stucks with "Internal Server Error" (405).

### 🔥 How to trigger the error

Simply inserting the e-mail address on the text field and clicking "Forgot password".

### 👎 Actual Behavior

Internal server error 405

### 👍 Expected Behavior

I don't know because I didn't went that further :-)

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

* cache/logs/system.log

```
REQUEST = Array
(
    [module] => Users
    [view] => LoginPassReset
)

2021-08-09 12:22:31 [warning] File not found: /var/www/yetiforce-portal/public_html/layouts/Default/modules/Base/resources/LoginPassReset.js
#0 app/Controller/View.php:121  >>  App\Log->warning('File not found: public_html/layouts/Default/modules/Base/resources/LoginPassReset.js')
#1 app/Controller/View.php:297  >>  App\Controller\View->convertScripts([array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array],'js')
#2 modules/Users/View/Login.php:66  >>  App\Controller\View->getFooterScripts()
#3 modules/Users/View/LoginPassReset.php:50  >>  YF\Modules\Users\View\Login->getFooterScripts()
#4 app/Controller/View.php:225  >>  YF\Modules\Users\View\LoginPassReset->getFooterScripts()
#5 modules/Users/View/Login.php:59  >>  App\Controller\View->postProcess()
#6 app/WebUI.php:132  >>  YF\Modules\Users\View\Login->postProcess()
#7 app/WebUI.php:73  >>  App\WebUI->triggerPostProcess()
#8 index.php:31  >>  App\WebUI->process()
#9 public_html/index.php:11  >>  require('index.php')
REQUEST = Array
(
    [module] => Users
    [view] => LoginPassReset
)
```

### ❓ Additional context

The problem seems to lie in View::convertScripts() called probably by View::getFooterScripts() which explodes because the wanted file are not in the path:

```
# ls -1 public_html/layouts/Default/modules/Base/resources/
Dashboard.js
Dashboard.min.js
Dashboard.min.js.map
DetailView.js
DetailView.min.js
DetailView.min.js.map
EditView.js
EditView.min.js
EditView.min.js.map
Header.js
Header.min.js
Header.min.js.map
ListView.js
ListView.min.js
ListView.min.js.map
PasswordChangeModal.js
PasswordChangeModal.min.js
PasswordChangeModal.min.js.map
Pdf.js
Pdf.min.js
Pdf.min.js.map
QuickCreateModal.js
RecordList.min.js
RecordList.min.js.map
RecordListModal.js
RelatedListView.js
Widget
Widgets.js
Widgets.min.js
Widgets.min.js.map
```

It just is in another one:

```
# find ./ -type f -name LoginPassReset.js
./public_html/layouts/resources/LoginPassReset.js
```

Perhaps the function constructs the wrong paths?

Thanks,
Alessandro

**Comment by mariuszkrzaczkowski** [comment]
attach full logs, this message is just "warning"

**Comment by vencatoitc** [comment]
Here they are. Beware that I edited "api.log" because **it contained username and password in plain sight**!

[api.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6954327/api.log)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/6954328/system.log)

**Comment by mariuszkrzaczkowski** [comment]
> Beware that I edited "api.log" because **it contained username and password in plain sight**!

very good !!

`Error: GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://crm.vencato.cloud/webservice/Portal/Install in /var/www/yetiforce-portal/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211`

The server configuration needs to be improved

**Comment by vencatoitc** [comment]
You have to read more carefully the log. That error was in the past and **not** in the last call which this bug is referred to.
Please refer to the **last** trace.

**Comment by mariuszkrzaczkowski** [comment]
Show logs from CRM

**Comment by vencatoitc** [comment]
Hi Marius,

here a clean version of both CRM and portal logs created doing a "password forgot" and a failed login try.
The CRM log show up empties.

Thanks,
Alessandro

[logs-20210811.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/6966254/logs-20210811.zip)

**Comment by mariuszkrzaczkowski** [comment]
it is not possible that the log files are empty, show configuration verification and the file config/debug.php

**Comment by vencatoitc** [comment]
Hi Marius,

i've the error from the webservice's debug whe I try the "forgot password" on the portal:

```
============ Error exception ====== 2021-08-11 14:09:49 ======
code: 405 | message: Invalid method
file: /var/www/yetiforce/api/webservice/Core/BaseAction.php (44)
============ stacktrace: 
#0 /var/www/yetiforce/api/webservice/Controller.php(121): Api\Core\BaseAction->checkAction()
#1 /var/www/yetiforce/webservice.php(25): Api\Controller->process()
#2 /var/www/yetiforce/public_html/webservice.php(11): require('/var/www/yetifo...')
#3 {main}
============ Request ======  2021-08-11 14:09:49  ======
REQUEST_METHOD: GET
REQUEST_URI: /webservice/Portal/Users/ResetPassword
QUERY_STRING: _container=Portal&module=Users&action=ResetPassword
PATH_INFO: 
----------- Headers -----------
host: crm.vencato.cloud
authorization: Basic cG9ydGFsOlBsQS14VjlCcDZBOEI3VTA=
user-agent: YetiForce Portal | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
x-encrypted: 0
x-api-key: XR4GtBZvrBQs5AchgDfkSvuUf4P27cJ4
content-type: application/json
accept: application/json
----------- Request data -----------
Array
(
    [module] => Users
    [action] => ResetPassword
)

----------- _GET -----------
Array
(
    [_container] => Portal
    [module] => Users
    [action] => ResetPassword
)

----------- _POST -----------
Array
(
)

----------- Request payload -----------
```

In modules/Users/* I don't see any "ResetPassword" method amongst the classes.

Thanks,
Alessandro

**Comment by mariuszkrzaczkowski** [comment]
The error is that the API / webservice / Portal / Users / ResetPassword method only supports POST and PUT and in your case sends GET https://doc.yetiforce.com/api/#/Users/1afb975ceee34717503a9e5403f49a58

The reason may be:
- some rule on vhost which changes that
- wrong CRM URL in the portal configuration file, you can have HTTP set and CRM works only over HTTPS

![image](https://user-images.githubusercontent.com/10198654/129028687-9809e618-1251-4653-ab0c-6a997e032591.png)

**Comment by vencatoitc** [comment]
I dig into web server access log and on the CRM side I noticed this one:

```
127.0.0.1 - portal [11/Aug/2021:14:53:11 +0200] "POST /webservice/Portal/Users/Login HTTP/1.1" 401 772
```

When I try to login from the portal... with this URL, does it try to load a Portal class under modules/ directory? If yes, I don't have it :-)


Tomorrow I'll dig more deeply into it revising the web server configuration and I'll let you know.

**Comment by mariuszkrzaczkowski** [comment]
Check crm url in portal configuration if it is https or http

**Comment by vencatoitc** [comment]
Hi Marius,

I did few steps back and decided to redo a plain installation from scratch... "guess what?":

- portal/cache/logs/system.log

```
2021-08-12 08:14:29 [warning] File not found: /var/www/yetiforce-portal/public_html/layouts/Default/modules/Base/resources/Install.js
#0 app/Controller/View.php:121  >>  App\Log->warning('File not found: public_html/layouts/Default/modules/Base/resources/Install.js')
#1 app/Controller/View.php:296  >>  App\Controller\View->convertScripts([array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array,array],'js')
#2 app/Controller/View.php:225  >>  App\Controller\View->getFooterScripts()
#3 modules/Install/View/Install.php:94  >>  App\Controller\View->postProcess(true)
#4 app/WebUI.php:132  >>  YF\Modules\Install\View\Install->postProcess()
#5 app/WebUI.php:73  >>  App\WebUI->triggerPostProcess()
#6 index.php:31  >>  App\WebUI->process()
#7 public_html/index.php:11  >>  require('index.php')
REQUEST = Array
(
    [module] => Install
    [view] => Install
    [_csrf] => sid:d8b3cec77657a2fdf5977ddee840f0173e9535e2,1628748864
    [mode] => step2
    [lang] => en-US
)
```

- crm/cache/logs/web

```
============ Error exception ====== 2021-08-12 08:18:10 ======                                                                            [2/1813]
code: 0 | message: Call to a member function updateSession() on null
file: /var/www/yetiforce/api/webservice/Controller.php (222)
============ stacktrace:                                                 
#0 /var/www/yetiforce/public_html/webservice.php(11): require()
#1 {main}
============ Request ======  2021-08-12 08:18:10  ======
REQUEST_METHOD: PUT
REQUEST_URI: /webservice/Portal/Install
QUERY_STRING: _container=Portal&action=Install
PATH_INFO: 
----------- Headers -----------
host: crm.vencato.cloud
authorization: Basic cG9ydGFsOlBsQS14VjlCcDZBOEI3VTA=
user-agent: YetiForce Portal | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
x-encrypted: 0
x-api-key: hb0FwhxwNz5VaWwCYK7w4KeJnhNtsvnb
content-type: application/json
accept: application/json
content-length: 25
----------- Request data ----------- 
Array
(
    [_container] => Portal
    [action] => Install
)

----------- _GET -----------
Array
(
    [_container] => Portal
    [action] => Install
)

----------- _POST -----------
Array
(
)

----------- Request payload -----------
{"data":"Install Wizard"}
```

I just followed the instructions at https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-install-yetiforce-portal from which it's a bit unclear what and what kind of web service applications and users have to be setup prior the portal installation.


Thanks,
Alessandro

**Comment by vencatoitc** [comment]
Hi Marius,

Eureka! I finally manage to login successfully :-)
You can close this case.

Thanks,
Alessandro

**Comment by mariuszkrzaczkowski** [comment]
What was the reason ?
How did you fix it?
