### ISSUE TITLE
[BUG] not ready for the new TLD's

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1504]
It seems the email field check is not ready for the newer domains.
![screen shot 2015-07-13 at 21 38 29](https://cloud.githubusercontent.com/assets/10379403/8658968/a08a1c10-29a7-11e5-9966-4a0cb085bf64.png)

My own domain: zebra.hosting does not get accepted in Mail log -> notification email.

**Comment by MaciejStencel** [comment]
It has been fixed to allow new long TLDs. In specification each label can have up to 63 characters so the last part of domain was set from 2-4 characters to 2-63 characters.

You can test it here:
https://gitdeveloper.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=logs&block=7&fieldid=45
