### ISSUE TITLE
[bug] Quick record creation on roundcube - javascript error

### ISSUE THREAD

**Issue by azorlone** [YetiForceCompany/YetiForceCRM#15068]
# 🐞 bug report

### ⁉️ Describe the bug

On roundcube, after importing a mail in the database, you can add relationships between the mail and existing records in modules, but the "+" button (a.k.a. "Quick create") is giving out a javascript error in the browser console: 
```
preview.js:383 Uncaught TypeError: headerInstance.quickCreateModule is not a function
   
```

![image](https://user-images.githubusercontent.com/88847415/129579300-09789b0c-be24-4b3c-bea8-4b496c20e4ec.png)

### 🔥 How to trigger the error

1. Go to Virtual Desk > My Mailbox
2. Select a mail
3. If the mail is not yet imported into the database, do so with the "import mail manually" button
4. In the top action bar, select a module (i.e. "Accounts") and hit on the "+" button

You may as well notice that clicking on the magnifier icon, the modal for selecting an exising record (from all accounts, in the aforementioned example) works fine 

### 👎 Actual Behavior

nothing happens when clicking. Chrome developer console shows this error:
`preview.js:383 Uncaught TypeError: headerInstance.quickCreateModule is not a function
    at rcube_webmail.showQuickCreateForm (preview.js:383)
    at HTMLButtonElement.<anonymous> (preview.js:245)
    at HTMLButtonElement.dispatch (jquery.min.js?s=1627911811:36)
    at HTMLButtonElement.v.handle (jquery.min.js?s=1627911811:36)`

### 👍 Expected Behavior

I would expect the quick creation form for the selected module in the actionbar to open.

### 👷 Testing

- [❗️] I confirm that I tested it at https://gitstable.yetiforce.com
_currently out of service with error "Warning: failed to open stream: No such file or directory in /home/gitstable/domains/gitstable.yetiforce.com/public_html/include/ConfigUtils.php on line 12"_
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.2.0
| Web server (name and version)       | apache    2.x           |
| PHP                                 |    7.4.20            |
| Browser (name and version)          | Chrome  92.0 (also tested with edge)              |
| Operating System (name and version) |   Ubuntu 20.04             |
| Database (name and version)         |   MySQL 5.7             |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment]
attach a screenshot

**Comment by azorlone** [comment]
> attach a screenshot

Updated the description with the requested attachment

**Comment by mariuszkrzaczkowski** [comment]
Fixed, 
update the library, just change the version number to 0.1.31 in the file:
https://github.com/YetiForceCompany/YetiForceCRM/blob/ccd620e9109b9a0f66ba879d4dc6ac45b8bb3f13/config/version.php#L6

update your mail client

![image](https://user-images.githubusercontent.com/10198654/129678537-e9e301e2-ab46-48f4-bcf0-c127a326c1e2.png)

NOTE: this will only work if you have version 6.2
