### ISSUE TITLE
installation is interrupted 

### ISSUE THREAD

**Issue by Abdallah-one** [YetiForceCompany/YetiForceCRM#1506]
I was trying to install yetiforce 2.0.0 on my local machine
every thing was good until the progress bar disappeared and when I try to login the login form was without logo and I check users table and I found it empty without any data

**Comment by bpabiszczak** [comment]
The problem must be described in detail [web environment information, error information, information from the logs] and everything else that might prove to be helpful, I recommend reading these articles:
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html 
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html
