### ISSUE TITLE
[REQUEST] Adjust checkbox value in Email templates

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1507]
When using a checkbox in a mail template it translates to 0 or 1. 
Email maker in vTiger makes it yes and no, which is much more useful in communication with clients.

Please do the same in Yeti. (and follow the language rules so I can use language specific answers)

**Comment by bpabiszczak** [comment]
Unfortunately, i don't understand what you're describing. Fist of all - show me in a screen shot which element we are talking about. Secondly, show me in a screen shot how this element was dealt with elsewhere, and describe it all once again.

**Comment by zebrahosting** [comment]
<img width="1344" alt="screen shot 2015-07-15 at 14 04 53" src="https://cloud.githubusercontent.com/assets/10379403/8698049/8e0942c4-2afa-11e5-9899-8848918c2263.png">

Each contact has some extra checkboxes to tell what training they follow. In the contact details it shows a YES and NO for selected / unselected boxes.

When I want to send an overview to the client, we use an Email template with those details.

In vTiger/Email maker that block will look like this:

<img width="300" alt="screen shot 2015-07-15 at 14 09 08" src="https://cloud.githubusercontent.com/assets/10379403/8698114/1ab0ddfe-2afb-11e5-8917-3ad6f3cc51c9.png">

Showing a clear YES/NO for the checkbox value.

When I use a mail template in Yeti and send it to the client they will only see 0 or 1 (zero or one).
 
<img width="318" alt="screen shot 2015-07-15 at 14 15 47" src="https://cloud.githubusercontent.com/assets/10379403/8698201/192b7812-2afc-11e5-8337-902155b1305e.png">

As an expresion for coders ok but not for client communication. Would love to have a language variable (as in vTiger/ Emailmaker) for the Checkbox value.

Hoop this is more clear.

**Comment by bpabiszczak** [comment]
Thank you
