### ISSUE TITLE
[REQUEST] Email template  and filter copy options

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1508]
Since Email templates can only be made per record or email but not both it would be nice to have a simple copy/duplicate  option to prepare the double work.
Of course a multi select box to select email, record and list would also be a big help and avoid a lot of duplicates.

Similar for filters everywhere. in vTiger there is a simple extension that makes a copy button inside the filter dropdowns. Might be nice to create this in Yeti too.

**Comment by bpabiszczak** [comment]
Unfortunately, i don't understand what you're describing. Fist of all - show me in a screen shot which element we are talking about. Secondly, show me in a screen shot how this element was dealt with elsewhere, and describe it all once again.

**Comment by zebrahosting** [comment]
It's kind of two questions in one. May be I need to separate them:

1. is the option to duplicate a filter: https://marketplace.vtiger.com/app/listings?id=110 

2. I would like to see the same for Email templates. Some of them take a lot of work to get right, would be nice to have a copy option there. ( and yes I copy now with the HTML source but that does not help for all other settings.)

Down the line I guess the same would be good for PDF's

**Comment by mariuszkrzaczkowski** [comment]
1. Add in https://github.com/YetiForceCompany/YetiForceCRM/commit/49517d85eaa303dcebd528b6414feffced965c83
