### ISSUE TITLE
[bug]  Mail scanner misses some emails

### ISSUE THREAD

**Issue by Andr198** [YetiForceCompany/YetiForceCRM#15093]
# 🐞 bug report

### ⁉️ Describe the bug
Mail scanner misses some emails  after update to version 6,2

### 📷 Screenshot of configuration

![ConfReport (3)](https://user-images.githubusercontent.com/62097187/130322838-545e65c2-5943-4110-b045-b8af38af2a70.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
errors.log

2021-08-21 16:04:05.0024 [error][IllegalValue] - purifyHtmlEventAttributes: <html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv=Content-Type content="text/html; charset=windows-1251"><meta name=Generator content="Microsoft Word 15 (filtered medium)">

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |6,2,0
| Web server (name and version)       |      Apache/2.4.41 (Ubuntu)          |
| PHP                                 |     7.4.22           |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |    MySQL 8.0.26            |
| Service Pack version                |           Service Pack v2     |

### ❓ Additional context
In version 6.1.0, the scanner works with these mail

**Comment by mariuszkrzaczkowski** [comment]
download the e-mail (.eml format) and send it to us at github@yetiforce.com, this requires an analysis of the e-mail content

**Comment by Andr198** [comment]
Sent to github@yetiforce.com mail 23.08.2021 12:26
Today a few more letters missed by the scanner
Today sent to github@yetiforce.com mail  with logs and e-mail (.eml format)

**Comment by Andr198** [comment]
In Roundcube
Mail not found in the database.

2021-08-30 15:22:37.144 [error][IllegalValue] - purifyHtmlEventAttributes: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div class="WordSection1"><p class="MsoNormal"><span style="color:#1F497D;mso-fareast-language:EN-US"> </span></p><p class="MsoNormal"><span style="color:#1F497D;mso-fareast-language:EN-US"> </span></p><div><p class="MsoNormal">......

2021-08-30 15:22:37.1447 [error][MailScanner] - Action: CreatedEmail  Folder: INBOX ID:39
App\Exceptions\IllegalValue: ERR_NOT_ALLOWED_VALUE|3|Array
(
    [0] => <a href="javascript:emxShowModalDialog(
    [1] => a href="
    [2] => 
)
||<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div class="WordSection1"><p class="MsoNormal"><span style="color:#1F497D;mso-fareast-language:EN-US"> </span></p><p class="MsoNormal"><span style="color:#1F497D;mso-fareast-language:EN-US"> </span></p><div><p class="MsoNormal"> .....
in /var/www/html/YetiForce/app/Purifier.php:263
Stack trace:
#0 /var/www/html/YetiForce/app/Purifier.php(196): App\Purifier::purifyHtmlEventAttributes('<!DOCTYPE html ...')
#1 /var/www/html/YetiForce/modules/OSSMailScanner/scanneractions/CreatedEmail.php(173): App\Purifier::purifyHtml('<!DOCTYPE html ...')
#2 /var/www/html/YetiForce/modules/OSSMailScanner/scanneractions/CreatedEmail.php(54): OSSMailScanner_CreatedEmail_ScannerAction->parseContent(Object(OSSMail_Mail_Model))
#3 /var/www/html/YetiForce/modules/OSSMailScanner/models/Record.php(300): OSSMailScanner_CreatedEmail_ScannerAction->process(Object(OSSMail_Mail_Model))
#4 /var/www/html/YetiForce/modules/OSSMail/views/MailActionBar.php(43): OSSMailScanner_Record_Model::executeActions(Array, Object(OSSMail_Mail_Model), 'INBOX', NULL)
#5 /var/www/html/YetiForce/include/main/WebUI.php(190): OSSMail_MailActionBar_View->process(Object(App\Request))
#6 /var/www/html/YetiForce/index.php(26): Vtiger_WebUI->process(Object(App\Request))
#7 {main}
2021-08-30 15:22:37.2099 [error][IllegalValue] - purifyHtmlEventAttributes: <html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas

**Comment by mariuszkrzaczkowski** [comment]
fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/d6e26b35f3c318d527e5da2129e8cdcae96370d1
