### ISSUE TITLE
[BUG] No DAV key screen in setup

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1509]
In both Master and Dev version, with an enabled caldav and carddav in the api.php, the setup screens don't show in the settings. Just blank screens.
The same seems to happen for the mobile keys.

**Comment by bpabiszczak** [comment]
Unfortunately, i don't understand what you're describing. Fist of all - show me in a screen shot which element we are talking about.
![image](https://cloud.githubusercontent.com/assets/10197525/8697841/d195b9f2-2af8-11e5-8640-301537e1120a.png)

**Comment by zebrahosting** [comment]
On both master and dev version I see this:

<img width="2554" alt="screen shot 2015-07-15 at 13 56 36" src="https://cloud.githubusercontent.com/assets/10379403/8697908/8a3c98a4-2af9-11e5-9cd0-c70843bdcd23.png">

Same for the mobile

**Comment by bpabiszczak** [comment]
This is a screen shot of the developer version. Change your browser, open it in incognito mode, clear your cache.

**Comment by zebrahosting** [comment]
Nope it is not the cache or cookies. Don't see any issues in the console but the body is just empty.

<img width="775" alt="screen shot 2015-07-15 at 14 27 40" src="https://cloud.githubusercontent.com/assets/10379403/8698387/00e0b888-2afe-11e5-9a93-a8f2904d751d.png">

Changed the webserver settings (removed the NGINX proxy) but that also does not make a difference.

Can I put some breakpoints or markers somewhere to see how far it loads?

**Comment by bpabiszczak** [comment]
From what I see this is not the gitdeveloper version, but you installed it on your own server?

**Comment by zebrahosting** [comment]
Yes this is the GIT dev version from yesterday. ver. 2.0.476
Will wait till tonight and install the version of today fresh again and see if it gives the same results.

**Comment by bpabiszczak** [comment]
From what I see it doesn't work for you in your version.

I don't know yet if it works for you if you go to our GitDeveloper version, does it work correctly there?

If our version works for you, but your own version doesn't, then you will have to describe how to recreate this error - if we can't recreate it we won't be able to fix it. I suggest starting from the logs, whether or not there is something to worry about.

**Comment by zebrahosting** [comment]
Found the issue: if you enable webservice(s) in the API config, it blanks the DAV key screen.

**Comment by bpabiszczak** [comment]
We will check it tomorrow or on monday.
