### ISSUE TITLE
[high priority bug]Problem z zapisem przy tworzeniu szablonu/ edycyji szablonów e-mail

### ISSUE THREAD

**Issue by doriandudzisz** [YetiForceCompany/YetiForceCRM#1510]
Problem polega na tym że w momecie klikniecia w przycisk zapisz wyskakuje okienko które normanie pojawia sie przy zamykaniu karty z wprowadzonymi danymi, po kliknieciu pozostan na stronie trwa ciagła informacja o zapisie

**Comment by doriandudzisz** [comment]
Problem występuje rózniwż na wersji demo yeti ;)

**Comment by konadrian** [comment]
Czy mógłbyś odtworzyć/sprwawdzić czy błąd pojawią się na https://gitdeveloper.yetiforce.com/

**Comment by doriandudzisz** [comment]
na tej gitowej wersji nie, czy ta wersja to jest lustrzana kopia tego co mozna pobrać z gita?

**Comment by bpabiszczak** [comment]
Tak, ale z tego miejsca: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer, jednakże nie polecamy instalacji tej wersji. Za 1-2 tygodnie udostępnimy aktualizacje do wersji 2.1 z wersji 2.0 i to rozwiąże Twój problem.
