### ISSUE TITLE
Webservice API error creating product with unit_price

### ISSUE THREAD

**Issue by noelhunter** [YetiForceCompany/YetiForceCRM#15128]
I receive a error:

 [message] => Illegal value has been entered for this field type. Field name: unit_price, Module: Products, Value: 1699.95
            [code] => 406

Regardless of what values I send (adding currency symbols, etc).  Other product fields work with no error.  I can enter unit_prices in the UI, and retrieve them through web service, but not send them back.

**Comment by mariuszkrzaczkowski** [comment]
give more details, full request, logs full api logs

**Comment by noelhunter** [comment]
`----------- _POST -----------
Array
(
    [productname] => redacted text only value
    [description] => redacted text only value
    [manufacturer] => redacted text only value
    [serial_no] => P0678
    [unit_price] => 1699.95
    [mfr_part_no] => 660600
    [productcategory] => G
    [website] => http://www.redacted text only value
    [tax2] => 0
    [qtyinstock] =>
    [qty_per_unit] => 1
    [active] => true
    [discontinued] => false
    [assigned_user_id] =>
    [nu] => N
    [ean] => redacted text only value
    [dsrp] => 1699.95
    [freight] =>
    [year] => 2018
    [model] => redacted text only value
    [color] => RED
    [cf_854] => none
)

----------- Request payload -----------

-------------  Response  -----  2021-08-31 15:04:48  ------
Status: 406
REQUEST_METHOD: POST
REQUEST_URI: /webservice.php?_container=RestApi&module=Products&action=Record
QUERY_STRING: _container=RestApi&module=Products&action=Record
PATH_INFO:
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Illegal value has been entered for this field type. Field name: unit_price, Module: Products, Value: 1699.95
            [code] => 406
        )

)`

If I remove the unit_price line from the posted data, the post processes without error (including our custom added fields).

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/b72cb35e06bd66d6b607d56d68d30d31f1a0b7f5
```
POST /webservice/Portal/Products/Record HTTP/1.1
x-api-key: VMUwRByXHSq1bLW485ikfvcC97P6gJsz
Content-Type: application/json
x-token: 0d26005d0c220acc02e351c0742e6a37bb1cf63e25948f538af18cedcb097a6d
x-raw-data: 1
Authorization: Basic cGFydG5lcjpwYXJ0bmVy
User-Agent: PostmanRuntime/7.28.4
Accept: */*
Cache-Control: no-cache
Host: yeti
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 130
 
{
"productname": "ffff",
"qty_per_unit": 1,
"unit_price": '{"currencies":{"1":{"price":"3333"}},"currencyId":1}'
}
```
