### ISSUE TITLE
[bug] "Got timeout reading communication packets." Error during install

### ISSUE THREAD

**Issue by BasicComputers** [YetiForceCompany/YetiForceCRM#15120]
Attempting to install an instance of Yetiforce 4.4.0 on Windows Server 2019 using Xampp and connecting it to a Mysql Server 8.0 instance. When I go through the install process I am receiving an error that states "Got timeout reading communication packets."
Any idea what might be causing these issues with the setup, I have gone through the my.ini file that was included with the Yetiforce Xampp folder and copied those settings to the my.ini instance of Mysql Server 8.0 but I still receive the error message. 

![Yetiforce Error](https://user-images.githubusercontent.com/71788238/131405941-ce192f4d-5561-4b71-9030-d914a0b9f316.PNG)

**Comment by bpabiszczak** [comment]
YetiForce 4.4 :o
Windows Server :o

Check this: https://youtu.be/IUB-wjXUREE
