### ISSUE TITLE
[BUG] Cannot convert lead when target organization already exists without creating a duplicate

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1513]
When converting a Lead to an Opportunity, I am required to create a new Organization. But the Organization associated with the lead already exists, only the opportunity is new. I expected to be able to unckeck the "Create New Organization", but this does not allow to proceed.

**Comment by bpabiszczak** [comment]
Do you see this? 
![marketing_processes](https://cloud.githubusercontent.com/assets/10197525/8697925/b0710050-2af9-11e5-9883-c13f92159cf1.png)

**Comment by diderich** [comment]
OK, with that it works.
But it has a drawback that I need to know the exact spelling of the organization and I don't have any feedback whether my lead will be attached to a new or existing organization. This is not very user friendly.

**Comment by bpabiszczak** [comment]
We will change this :]

**Comment by bpabiszczak** [comment]
We added a new functionality that lets us control whether we create a new Organization or we link it. If we link it, we can set fields, on the basis of which, the system should look for the links.
![new](https://cloud.githubusercontent.com/assets/10197525/8773848/f8d69684-2ed7-11e5-9170-614ce53a1ebb.png)
