### ISSUE TITLE
[BUG] Cannot create organization with same name as lead

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1515]
I have no organization created. I want to add an organization named Test. I get the error message shown in the figure below. I expect this is the case because I have a lead called Test, but it should be possible to have leads and organizations (anc contacts) with the same names.

![img01](https://cloud.githubusercontent.com/assets/10230144/8698158/93b01328-2afb-11e5-9799-fc9f4c0feeb2.jpg)
![img02](https://cloud.githubusercontent.com/assets/10230144/8698160/96bad864-2afb-11e5-96d2-0c9e3b2798c4.jpg)

**Comment by bpabiszczak** [comment]
Please check this action: https://gitdeveloper.yetiforce.com/index.php?module=DataAccess&parent=Settings&view=ActionConfig&did=8&aid=0&an=Vtiger!!unique_value&m=Accounts

Settings > Validation of access > Check for duplicate names > Check if entered field value is unique
