### ISSUE TITLE
[REQUEST] import contact image

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1516]
Importing contacts from vTiger with a contact images, will only give the file name.
It would help to convert such a file name to a proper link so they can show up in Yeti.
Now they manually need to be altered to show up again. 
Of course people will also have to copy the images to the right location.

**Comment by bpabiszczak** [comment]
Currently we're not planning to add a functionality like that, it's not easy to implement [requires thinking it through] and wouldn't be that beneficial [not many people need to import pictures; we deployed YetiForce and Vtiger over 300 times and we never had to import any pictures]. This can always be done from the script level [several code lines] so we won't be adding this to the system right now, there are some more important things waiting to be done.

**Comment by htakawira** [comment]
@bpabiszczak good point there on the script had you ever done anything, if so can i have a lead on the script... Have an offline vtiger where they capture contacts offline so i need to then import the offline contacts to the server..

Also looking for a way to capture the contact face directly from the new contact screen...
