### ISSUE TITLE
[bug] Custom filters sorting not saved

### ISSUE THREAD

**Issue by garryatbrighton** [YetiForceCompany/YetiForceCRM#15168]
While setting sorting on custom filter, system ignoring that settings and not saving sorting order.
Sorting checked on Create date and Last Name (Contacts module)
Checked on stable and dev app

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/133033523-86a93613-24e0-421b-bc55-f20034c9ee49.jpg)

**Comment by s2b-git** [comment]
I can confirm on demo versions it not saving :-)
