### ISSUE TITLE
Unable to update from 5.3.0 to 6.0

### ISSUE THREAD

**Issue by nikolafamit** [YetiForceCompany/YetiForceCRM#15162]
Im getting error:
Argument 1 passed to App\YetiForce\Updater::download() must be of the type array, null given, called in /home/superkor/public_html/administracija/modules/Settings/Updates/views/Index.php on line 18

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13901
https://github.com/YetiForceCompany/YetiForceCRM/issues/13823
etc.
and add a full description of the system

**Comment by nikolafamit** [comment]
Thank you, but not thank you. I fixed by myself.
