### ISSUE TITLE
YetiForcePDF\Style\NumericValue::setUnit() must be of the type string, null given

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [YetiForceCompany/YetiForceCRM#15171]
### Discussed in https://github.com/YetiForceCompany/YetiForceCRM/discussions/14942#discussioncomment-1310969

$(barcode : type=EAN13 class=DNS1D , value=12345678)$
 
@TonyM15

It returns:
Warning: Undefined array key 3 in \vendor\yetiforce\yetiforcepdf\lib\Style\Normalizer\Normalizer.php on line 100

Argument 1 passed to YetiForcePDF\Style\NumericValue::setUnit() must be of the type string, null given, called in /var/www/html/brd/vendor/yetiforce/yetiforcepdf/lib/Style/Normalizer/Normalizer.php on line 100

**Comment by konadrian** [comment]
![image](https://user-images.githubusercontent.com/3193498/136898487-563be7c3-49ba-4b96-8899-6044e68dff40.png)
GitDev version
