### ISSUE TITLE
[bug] PDF variables are not clickable

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#15182]
In the first screen (settings) of PDF system templates all variable selecting little icons (next to text fields) are not working.
Checked on Stable, developer and own installation. I will appreciate if someone else could confirm.

regards

**Comment by apcloic** [comment]
Post a screenshot please, it's not clear.

**Comment by s2b-git** [comment]
![image](https://user-images.githubusercontent.com/84110093/133348111-fccd2062-f854-4464-b5ae-1bb53475f085.png)

**Comment by rskrzypczak** [comment]
The elements indicated by you contain only information (popover), they had no other purpose.
So this is not a bug.
![image](https://user-images.githubusercontent.com/10221999/133371401-ae89f5a0-66cc-4b2a-bb2f-221e947f2982.png)

**Comment by s2b-git** [comment]
Au..! Sorry than, bit misleading :-)
Thank you
