### ISSUE TITLE
[BUG] Field Editor - no field delete

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1518]
Do not deleted when you delete a field
![animation 18](https://cloud.githubusercontent.com/assets/1402355/8700072/3cee7cf0-2b23-11e5-9818-be3ac68dc3de.gif)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/280f36db4870e104445a2a1366b11296e3ebaf6c
