### ISSUE TITLE
[bug] Menu type "Shortcut" don't displaying icons

### ISSUE THREAD

**Issue by garryatbrighton** [YetiForceCompany/YetiForceCRM#15192]
After creating menu type "Shortcut" and assigning some icon, this icon is not displayed in newly created menu:
Tested on https://gitstable.yetiforce.com/index.php

**Comment by vovpff** [comment]
Try to clean browser cache

**Comment by garryatbrighton** [comment]
Not helping

**Comment by s2b-git** [comment]
Same here. Newly creates in menu Shortcut, or Quick Create not showing icons.

**Comment by s2b-git** [comment]
Created custom module and shortcut in git developer version - no icons displayed :-)

**Comment by mariuszkrzaczkowski** [comment]
I tested on gitdev, i can’t see the problem.
