### ISSUE TITLE
[BUG] Field Editor - Delete Block

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1520]
Removing the unit only after removing the fields, and only after the field will be disabled and re-enabled.

![animation 20](https://cloud.githubusercontent.com/assets/1402355/8700312/7b1968d6-2b24-11e5-87cd-9ad8e20c25af.gif)

**Comment by bpabiszczak** [comment]
to remove the block you have to move all the fields [even the deleted ones] to another block. The other problem you're reporting has been fixed in a different issue.
