### ISSUE TITLE
cache clear 

### ISSUE THREAD

**Issue by MixTecnico** [YetiForceCompany/YetiForceCRM#15216]
I have this problem from previous versions, could you tell me where to verify it or could I activate it?

![cache](https://user-images.githubusercontent.com/29989839/134709390-0813c8cc-24a1-4151-b053-8b50b8c96369.png)

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/134728412-c5eeacc2-ff29-403a-a376-11647bb2c6bb.jpg)

**Comment by MixTecnico** [comment]
SOLVED

Change file permissions 

/crm/cron/cron.sh to 775

/crm/cache to 775
