### ISSUE TITLE
[bug] Missing isset in api/webservice/Core/Response.php:getReasonPhrase function?

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#15226]
In `api/webservice/Core/Response.php`, in function `getReasonPhrase`, shouldn't the return line read

`		return isset($statusCodes[$this->status]) ? $statusCodes[$this->status] : $statusCodes[500];
`

instead of

`		return ($statusCodes[$this->status]) ? $statusCodes[$this->status] : $statusCodes[500];
`

?

**Comment by mariuszkrzaczkowski** [comment]
thanks, fixed it https://github.com/YetiForceCompany/YetiForceCRM/commit/2e5e8f2f692ad2a49b81d5c5f99e39349b500020
