### ISSUE TITLE
[bug] Price book permission do not work

### ISSUE THREAD

**Issue by leo719044** [YetiForceCompany/YetiForceCRM#15236]
I created the price book, but it is always visible to all user who can access "price book" module (set in Module Access)

even I set price book to "private"

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/135269538-f1aad76f-5aa9-488b-9abb-89791bd562ed.jpg)

**Comment by leo719044** [comment]
# 🐞 bug report

### ⁉️ Describe the bug

I created the price book, but it is always visible to all user who can access "price book" module (set in Module Access)

even I set price book to "private"

### 🔥 How to trigger the error

1. Go to 'Price Book'
2. Create any price book
3. Set price book neither "Private" or not
4. See "Permission Inspector"
5. No matter what sharing rule, everyone(with Price book module access, set it Module access) can see "Price Book"

### 👷 Testing

- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com/index.php?module=PriceBooks&view=Detail&record=2950&parent=118&mid=62

I changed the permission of Portal profile to see the prick book module.

### 📷 Screenshot of configuration
in profile seeting
![image](https://user-images.githubusercontent.com/88583995/135281994-19ee5f05-8c05-4a68-9f7c-229f3e193cb3.png)

Permission inspector
![image](https://user-images.githubusercontent.com/88583995/135281521-5dbdb170-7724-42f9-9dfe-c272e26748d4.png)

### 🌍 Your Environment

https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index

**Comment by leo719044** [comment]
Hello？？

**Comment by konadrian** [comment]
Private fields weren't enabled by default, that may cause the problem with permissions. Now this option is enabled by default
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/Security.php#L51

The problem no longer exists. The ticket has been closed.
