### ISSUE TITLE
[bug] Quick Create menu for custom modules failed

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#15249]
Quick create menu fixed with custom module not showing up, I checked on three different installations (latest version). Logs showing nothing

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/135713926-64958a75-4f7b-4b24-bb83-f087e1b614d4.jpg)

**Comment by s2b-git** [comment]
Well, it shown up 24 h later. Is it something done by cron? O.o
