### ISSUE TITLE
[Docker] system reinstall everytime on restart

### ISSUE THREAD

**Issue by tekkisse** [YetiForceCompany/YetiForceCRM#15250]
# 🐞 bug report

### ⁉️ Describe the bug

Configuration not being held when docker-compose up / down

Using docker-compose with mysql as a separate container, however get same behaviour if just use the yetiforce container and embedded mysql server

### 🔥 How to trigger the error

1. docker-compose up -d
2. configure install through web browsers
3. docker-compose down
4. docker-compose up -d

### 👎 Actual Behavior

Prompted to go through install screens
If connect back to existing database then install fails (side issue)

### 👍 Expected Behavior

Once installed and configured then the system should continue prior to being taken down and back up

### 👨‍💻️ Command to launch docker

docker-compose up -d
docker-compose down

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

- /var/www/html/cache/logs/system.log
- /var/www/html/cache/logs/errors.log
- /var/www/html/cache/logs/cron.log
- /var/log/nginx/error.log
- /var/log/nginx/localhost_error.log
- /var/log/nginx/php{php version}-fpm.log
- /var/log/mysql/error.log

### 🌍 Your Environment

pull of latest git repo

### ❓ Additional context

Debian 10

**Comment by mariuszkrzaczkowski** [comment]
this is a development version, needs to be adjusted for production use
