### ISSUE TITLE
[bug] When a user changes password it then keeps asking them to change it again on every login

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#15257]
Hi, 

When a user's password is changed for the first time they then have to change it on every single login. I first mentioned this issue here:

### 🔥 How to trigger the error

Change a user's password in the backend then login. You will be presented with the change password form. You will also see the the Force password change under the user's permissions has been changed to Yes. 

There is no way to change this to No as the field isn't available when you go to the edit screen for the user. I tried changing the value in the database but when you log out then in again it resets it back to yes and you are also prompted to change password again.

### 👍 Expected Behavior

It should not force password change on every login.

**Comment by PercyP** [comment]
Hi,

I have temporarily fixed it. I had to go in to the database vtiger_field table and searched for the force password change field then set the default value which was empty to 0. This for some reason then showed the field in the user's edit screen and I could switch the force password change to off. 

I am sure this is not the correct solution  but at least it works for now.

**Comment by Gazzxy** [comment]
I also have this issues

**Comment by rskrzypczak** [comment]
Install the last service pack: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/6.2.0

**Comment by solarisdigital** [comment]
Using 6.4 and still having the issue.

**Comment by VictorTWB** [comment]
Anyone solved this issue? I am having the same problem on version 6.5 as well.

**Comment by rskrzypczak** [comment]
Currently, the problem does not occur (YF7).
password reset is not required if the user has changed their own password.
if someone else has made such a change, then they can force another change the first time the specific user logs in.
