### ISSUE TITLE
[bug] Cannot create PDF template fo Advaced Custom module

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#15256]
Converted custom module to Advanced, added line items etc and I am unable to create PDF template for this module. Previously created are not accessible too.
Tried reproduce it on Yetiforce test versions, but cannot convert Custom Module from basic to advanced
Logs doesn't show errors. 

Best regards

**Comment by TonyM15** [comment]
Checked - confirmed. Hanging

**Comment by garryatbrighton** [comment]
Would be helpful if Yetiforce allow for changing module to advanced, so we all can confirm

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/135765296-67dc90d8-fd38-4313-a9e0-0df96ce5f342.jpg)

**Comment by s2b-git** [comment]
What would be the best way to debug such?

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by rskrzypczak** [comment]
Now you can change the module type on the demo version (https://gitdeveloper.yetiforce.com/).
So please confirm, because I can't see the error by myself.

**Comment by s2b-git** [comment]
It was my error. Sorry for alarm
