### ISSUE TITLE
[Cache issue] Generated about 1Gb pdf cache in 'Cache'--->'pdf' folder

### ISSUE THREAD

**Issue by allyh12** [YetiForceCompany/YetiForceCRM#15258]
Hi there,

Recently, I found the backup file on server is quite large as almost 1 Gb. Finally I found there are a lot of cache file in 'Cache'--->'pdf' folder.

<img width="520" alt="Yetiforce pdf cache" src="https://user-images.githubusercontent.com/59724920/135811709-3f3bf176-3c9d-4d70-95f0-00cd0f31c83e.PNG">

Please advise if there is a function can clear pdf cache, or I have to delete the pdf cache files on server manually.

Thank you so much for the help.

Regards,
Allison

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/discussions/14148
