### ISSUE TITLE
[bug] Dependent fields - mandatory not working

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#15276]
When trying to make some field mandatory using Dependent Fields it not makes it mandatory but it hide field (create).
Checked on Git Dev and own instance

**Comment by mariuszkrzaczkowski** [comment]
it's not a bug, that's how it was designed

**Comment by JohnMaverick** [comment]
Maybe change naming structure than, as it misleading completely

**Comment by waran70** [comment]
According to attached gif, I would say this is bug:

![mandatory](https://user-images.githubusercontent.com/6852348/136372651-54a3e72c-4cec-4def-b4e5-97239821f044.gif)

**Comment by TonyM15** [comment]
Making fields mandatory based on given conditions is something common in business applications. It is common because it is basic  user-level record safety measure.

**Comment by Marshal4582** [comment]
Tried this function too hoping it works as it says. It will be great advantage to add managing mandatory/or not fields

**Comment by JohnMaverick** [comment]
Marius, thanks for label. It noting bigy to fix, but community eyeing essentials which will contribute to your pool of potentials what will translate to commercial success for sure. Respect!

**Comment by Marshal4582** [comment]
Morning, any update on this issue? Making fields mandatory is very useful functionality
