### ISSUE TITLE
Broken image at pdf setting

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1528]
I find two broken images at pdf setting,like following:
![qq 20150716114235](https://cloud.githubusercontent.com/assets/12697896/8715150/338e0f9e-2bb0-11e5-9853-0c133c5e051a.jpg)

**Comment by bpabiszczak** [comment]
Please check here [last dev version] https://gitdeveloper.yetiforce.com/index.php?module=OSSPdf&view=Index&parent=Settings&block=4&fieldid=35
