### ISSUE TITLE
[bug] Mass SMS does not work

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#15289]
# 🐞 bug report

### ⁉️ Describe the bug
We have enabled smsnotifier module

In Contact List View, selected record and from action menu, selected mass sms
![image](https://user-images.githubusercontent.com/12723595/136698779-9fc13f27-7323-43d8-b1ad-98c945504e71.png)

Then SMS modal form opened
entered details but on submit button even message is typed it shows required details message
![image](https://user-images.githubusercontent.com/12723595/136698815-3687396f-a92e-459b-b7a4-693e3a371eb4.png)

Not checked on developer and stable as not able to add custom provider.

Please assist in the matter.

**Comment by vovpff** [comment]
All mass actions can be applied to 2 or more records in one time. Maybe this is cause of your problem?

**Comment by JEEVAN28** [comment]
Hi @vovpff 

I checked on 2 contacts (records) but issue remains same.

![image](https://user-images.githubusercontent.com/12723595/136732242-53439bb3-302b-4a32-a5e7-ea899d780351.png)

Please assist.
Regards
Jeevan Pendhari

**Comment by apcloic** [comment]
@JEEVAN28 
I had this problem too when working on mass sms feature for a custom module.

Try the following workaround, not perfect but it should work.

Modify layouts/basic/modules/Vtiger/SendSMSForm.tpl (or in custom/layouts/basic/modules/Vtiger/SendSMSForm.tpl if you have enabled loading custom files) like this :

Replace :

````
<textarea name="message" class="c-textarea--completions" data-validation-engine="validate[ required]"></textarea>	
<div contenteditable="true" class="form-control js-completions" id="message" placeholder="{\App\Language::translate('LBL_WRITE_YOUR_MESSAGE_HERE', $MODULE)}" data-completions-textarea="true" data-js="html | tribute.js"></div>
````

with	:							

````
<textarea name="message" id="message" class="form-control" data-validation-engine="validate[ required]" placeholder="{\App\Language::translate('LBL_WRITE_YOUR_MESSAGE_HERE', $MODULE)}"></textarea>
````

Reference issue : #12496
Regards

**Comment by JEEVAN28** [comment]
Yes, this is done. Thanks.

**Comment by JohnMaverick** [comment]
Applied carefully changer to 6.2 but it hangs plus crippling fields quick edit. I guess there are some dependencies?
