### ISSUE TITLE
[Bug] PDF Templates  - cant use asian languages

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1529]
Japanese, Chinese, Thai can not be use within PDF templater.
Kind of limiting scope of users, so please address issue to 2.1

**Comment by bpabiszczak** [comment]
I wouldn't call it a bug. In order to handle different languages you may have to install some fonts that can handle them, there are no fonts so it doesn't work. It's marked as a new functionality and  it will be introduced in the 2.2 version [maybe 2.3]

**Comment by reeid** [comment]
Thanks. From the marketing point of view it seems to be important to let millions of millions Asian people contribute in code/use Yetiforce. If we have in MS Word only Courier font, I guess OpenOffice will eat words processors market alone :-)

**Comment by bpabiszczak** [comment]
I suggest starting from adding a language pack for these languages, when a new language pack appears and is developed, then naturally all the other elements of the system will be developed for these languages
