### ISSUE TITLE
[BUG] Share with users

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1531]
Why responsible to share with myself?

![animation 29](https://cloud.githubusercontent.com/assets/1402355/8739629/65d436ac-2c57-11e5-8a79-798ea456802d.gif)

**Comment by bpabiszczak** [comment]
This is not an error. The owner of the record can change, then when we are in the sharing field we can still see this record. Another thing is that the way this field works will change a little, I don't yet know how, but we have several ideas how to improve this field.
