### ISSUE TITLE
Server configuration on Fully managed VPS on TMD Hosting 

### ISSUE THREAD

**Issue by naas1172** [YetiForceCompany/YetiForceCRM#15344]
Hello everyone.
We have a fully managed VPS Hosting in TMD Hosting.
Yetiforce is installed. The support team has helped me a lot, but there are still some issues. 
Yetiforce is up to date: YetiForce CRM 6.2 Service Pack v4.
Please check the images here below. 
In the last email Support wrote me: "Unfortunately, your application does not detect the rest of the changes we have made and the warnings are still present. However, these should not be preventing the application from working properly."
Do you think they should be able to fix the remaining issue? Is it safe to use the CRM with these issues?

Thank you!
Alessandro

![system_headers_YetiForce_6-2_Service-Pack-v4](https://user-images.githubusercontent.com/92877296/138132222-a48b9dd9-fa69-4c24-a4ff-ec33bc089fc6.jpg)
![system_path-verification_YetiForce_6-2_Service-Pack-v4](https://user-images.githubusercontent.com/92877296/138132226-141e7876-96e5-48df-8f80-2be1d09587fd.jpg)
![system_performance-verification_YetiForce_6-2_Service-Pack-v4](https://user-images.githubusercontent.com/92877296/138132229-57a4e095-8334-493a-b18e-a385f830222a.jpg)
![system_security_YetiForce_6-2_Service-Pack-v4](https://user-images.githubusercontent.com/92877296/138132235-f9c7a129-d5a3-483e-a2e3-b4432706c36e.jpg)

**Comment by vovpff** [comment]
You need to run cron once to check cron (cli) column parameters
