### ISSUE TITLE
[bug] export to Excel formats corrupted

### ISSUE THREAD

**Issue by Gazzxy** [YetiForceCompany/YetiForceCRM#15349]
# 🐞 bug report

### ⁉️ Describe the bug

Attempting to export to Excel  in any form results in a corrupted unreadable file

### 🔥 How to trigger the error

select some records and try to export

![image](https://user-images.githubusercontent.com/83064841/138311758-75f21b5c-94cb-47f9-aef0-c3c88982b997.png)
![image](https://user-images.githubusercontent.com/83064841/138311803-c9e355b7-d2c8-4321-8dfd-53ff706ad87c.png)
![image](https://user-images.githubusercontent.com/83064841/138311871-97ceecbc-c193-44d3-85b4-ca8153434e19.png)

### 👎 Actual Behavior

file do not export in any readable way except for pdf and csv though it did work original for excel formats it has stopped

### 👍 Expected Behavior

to be able to export a filtered Excel document

### 👷 Testing

- [yes - cannot reproduce] I confirm that I tested it at https://gitstable.yetiforce.com
- [yes cannot reproduce ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![ConfReport (1)](https://user-images.githubusercontent.com/83064841/138312366-0847ff73-4a5b-4cc2-af48-8e32d366c878.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.2 service pack 4
| Web server (name and version)       |         apache 2       |
| PHP                                 |                | 7.4
| Browser (name and version)          |       chrome  or edge       |
| Operating System (name and version) |      win10         |
| Database (name and version)         |          mysql 8      |
| Service Pack version                |                |4

**Comment by mariuszkrzaczkowski** [comment]
It looks (seems) your server is not properly configured and you have to fix it
