### ISSUE TITLE
[bug] SQLSTATE[42S02] Error

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#15361]
Hello,

I tried to upgrade from 6.1.0 to 6.2.0 v2 from Settings Update Menu. I took backup before upgrade. while upgrade failed. I restored my database and installation files.
 but now when i am trying to view any module i get below error
![image](https://user-images.githubusercontent.com/12723595/138739125-a1c5ec42-babd-4acc-bad0-751b476c08b3.png)

I checked database but no such table found.

I tried to create this table from my test installation but getting below error

CREATE TABLE `a_yf_record_converter` (
  `id` smallint(10) UNSIGNED NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `source_module` smallint(5) NOT NULL,
  `destiny_module` varchar(255) NOT NULL,
  `field_merge` varchar(50) DEFAULT NULL,
  `field_mapping` text,
  `inv_field_mapping` text,
  `redirect_to_edit` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `check_duplicate` tinyint(1) DEFAULT NULL,
  `show_in_list` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `show_in_detail` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `conditions` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

![image](https://user-images.githubusercontent.com/12723595/138739261-8e2f29e5-70f1-4f99-93a3-94423d34c072.png)

please help urgently.

regards
Jeevan Pendhari

**Comment by rskrzypczak** [comment]
This table exists in version 6.1 and even earlier.
It's hard to help you here, because you just didn't restore the database correctly.
Verify the copy of the database you made, because the errors may have arisen during the database dump.

**Comment by JEEVAN28** [comment]
I created this table manually and application started working correctly.
But issue persist with upgrade from 6.1.0 to 6.2.0. I am raising separate issue for the same for analysis
Thanks for reply

**Comment by mariuszkrzaczkowski** [comment]
the fact that you have created one table does not mean that everything works, if you have such an error, you will soon have another ...

you must either repair the entire database or restore the correct database from a backup

crm may look like it works, but there may be a lot of bugs not visible or some functions may not work
