### ISSUE TITLE
[DESIGN IMPROVEMENT] Currency

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1538]
Add symbol Russian Rubles

HTML CODE &#8381;

![animation 36](https://cloud.githubusercontent.com/assets/1402355/8740060/57ca9da2-2c5d-11e5-9187-c30812d2f29f.gif)

**Comment by konadrian** [comment]
After adding new currency you have to change currency in user settings
![currency](https://cloud.githubusercontent.com/assets/3193498/8771645/557492b0-2ec4-11e5-8f88-6502371b050d.png)


![currency](https://cloud.githubusercontent.com/assets/3193498/8771627/34eedece-2ec4-11e5-8bfe-f21be932c26f.png)

**Comment by waw555** [comment]
Нужно заменить текст (руб) на иконку валюты (₽)

**Comment by konadrian** [comment]
Changes see on https://gitdeveloper.yetiforce.com
![currency](https://cloud.githubusercontent.com/assets/3193498/8772927/6e04eb2a-2ed0-11e5-9f58-158abb94f0ae.png)

**Comment by waw555** [comment]
Yes, it's cool ))))
