### ISSUE TITLE
[bug] Unable to delete / download image

### ISSUE THREAD

**Issue by garryatbrighton** [YetiForceCompany/YetiForceCRM#15388]
Checked on gitdeveloper and own instances. On linux it work well but non windows installation allowing for deleting or downloading picture from image field. On windows it has been tested in four top browsers.
Attached gif
![image-bug](https://user-images.githubusercontent.com/80203589/139506754-869b9fec-a102-4eea-8f2a-245d633d5054.gif)

**Comment by Marshal4582** [comment]
It could be that images are converted to base64 - this causing issues with for instance WYSWIG fields when you want to limit number of characters. Converted image (even little) eating characters limit right away

**Comment by rskrzypczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/14331
You need to provide more info regarding your configuration, you see it works on the yetiforce demo: https://github.com/YetiForceCompany/YetiForceCRM/issues/14331#issuecomment-811722692

If it didn't work for you on the demo version (gitdeveloper), maybe one of the add-ons is the cause.

**Comment by s2b-git** [comment]
Radek, can you please try it on Windows? I use different Windows, no extension installed, tried in incognito mode, Tor browser - none works. Only on Ubuntu all is OK. Cofnig here is perfect. All PHP extensions in place, no errors. Should we install some java version, or so, on windows to make it work?

**Comment by rskrzypczak** [comment]
Yes i checked and i can't reproduce it.
Check the console(F12), maybe there will be an error message.
Try to debug the cause yourself.

**Comment by waran70** [comment]
Well, I am far away from the guy who opened this issue I believe, but here this is also not working. Maybe instead of closing case, it will be wise to check it on various computers?

**Comment by s2b-git** [comment]
Maybe we can reopen, and listen to experience of other users?

**Comment by apcloic** [comment]
@s2b-git @garryatbrighton 
No delete/download/upload issue with image field on gitdeveloper for me, lenovo_laptop/win10/chrome.
![download_image_yeti6 3](https://user-images.githubusercontent.com/2930560/140334901-999b5aca-66d3-412b-82b6-7538db11ec3d.gif)

**Comment by TonyM15** [comment]
In windows serv 2019 it seems to be java problem. Never fixed, working on different OS

**Comment by mariuszkrzaczkowski** [comment]
Record a video showing the error and show the browser consoles.

**Comment by reeidgce** [comment]
Just created new issue without checking and yes, it not works on Windows Server versions

**Comment by mariuszkrzaczkowski** [comment]
please send the required information, we do not have a windows server operating system to verify it

**Comment by reeidgce** [comment]
May I know email so I can send RDC credentials?

**Comment by mariuszkrzaczkowski** [comment]
github@yetiforce.com

**Comment by reeidgce** [comment]
Cannot upload images to demo servers (both).

**Comment by garryatbrighton** [comment]
Solution:

The "Enable Java Access Bridge" check box gets removed from the Control Panel (go to Control Panel -> Ease of Access Center -> Use the computer without a display) when the 64-bit JRE 8 is uninstalled, even if a 32-bit JRE version 7u6 or later exists. The workaround is to uninstall the existing 32-bit JRE and install it again. The "Enable Java Access Bridge" check box will appear after the 32-bit JRE version 7u6 or later is installed.

**Comment by s2b-git** [comment]
Just noticed that solution of garrybrighton stopped working suddenly. Reinstalling Java (both 32 and 64 bit) not helping.
What library is behind MultiImage.js? It is not working on windows servers
