### ISSUE TITLE
[Issue] Products & Services Search Treeview does not filter records

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#15413]
Hi,
I am struggling with Accounts Module -> Products & Services Tab -> when I click on search button I get the list of products which are around 3000 + in my case.
when I search for the products currently it only highlights the product name and not filter. it is very difficult to scroll 3000 list and see where same is highlighted.
![image](https://user-images.githubusercontent.com/12723595/140634156-8cc36643-6888-47b6-88b5-3614706297f3.png)

How to add filter in this so searching and selecting record can be easier

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
you can try it: https://www.jstree.com/api/#/?f=$.jstree.defaults.search.show_only_matches

**Comment by JEEVAN28** [comment]
Hi @mariuszkrzaczkowski its bit technical. not understood much. can you guide me file where i need to see for changes

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/public_html/layouts/resources/libraries/jstree.category.js

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski I could not able to do this, you may either close this or keep for development
