### ISSUE TITLE
Upgrade from 5.3 to v6.X

### ISSUE THREAD

**Issue by asperitigroup** [YetiForceCompany/YetiForceCRM#15418]
I am trying to use an upgrade package to upgrade from v5.3 to v6.2.  I have downloaded the 5.3.0_to_6.0.0_v8.zip file but when I try to "Import bundle from file" in system updates I get an error message saying "This site can't be reached"

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/13823 https://github.com/YetiForceCompany/YetiForceCRM/issues/13862 
https://github.com/YetiForceCompany/YetiForceCRM/issues/13839
![github](https://user-images.githubusercontent.com/10198654/140770010-e8defb60-fef7-41d8-8cbf-11750d11d021.jpg)
