### ISSUE TITLE
[bug] Upgrade from Release 6.1.0 to 6.2.0 v2

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#15414]
Hi,
I am trying to upgrade from 6.1.0 to 6.2.0 as per below screenshot
![image](https://user-images.githubusercontent.com/12723595/140635236-4e308cc7-94a1-490d-bd1e-48f0debe017b.png)

I have downloaded package and then clicked on install package button
I get below error
![image](https://user-images.githubusercontent.com/12723595/140635285-bd5a9b1a-dc9d-43f1-b9a6-1de1e9915755.png)

I had then clicked on Finish Button
went to System Settings -> Language Management
**done nothing here**
Then again went for update and clicked on download and install package
Now, I get below screen
![image](https://user-images.githubusercontent.com/12723595/140635389-82ee4fcb-c827-407f-82fa-b0b9e8d1466d.png)

I accepted license agreement and clicked on Yes button to upgrade
almost system had some script running for 30-45 seconds then I get below erro
![image](https://user-images.githubusercontent.com/12723595/140635462-4539a837-a21b-4103-95e2-e8c8de89eada.png)

if i refresh page then i see my dashboard page but not able to have any operations, clicking on any icon does not do any thing
even footer is also not visible
![image](https://user-images.githubusercontent.com/12723595/140635538-9824c389-ca91-4899-84ed-3f30e81a801f.png)

from this stage, i only need to restore my backup

my config screen shot is as below
![ConfReport (1)](https://user-images.githubusercontent.com/12723595/140635478-0a6576d4-ccbb-4e7f-90e2-c18331105a2c.png)

i checked my log files in chache\logs\updateLogsTrace.log file
it shows below data
YetiForceUpdate::update | 2021-11-07 12:19:39
YetiForceUpdate::updateBeforeImporter | 2021-11-07 12:19:39
YetiForceUpdate::updateBeforeImporter | 2021-11-07 12:19:39 | 0 mim.
YetiForceUpdate::searchTable | 2021-11-07 12:20:59
YetiForceUpdate::searchTable | 2021-11-07 12:21:00 | 0.01 min
YetiForceUpdate::updateDataImporter | 2021-11-07 12:21:00
YetiForceUpdate::updateDataImporter | 2021-11-07 12:21:00 | 0 mim.
YetiForceUpdate::addModules | 2021-11-07 12:21:00
YetiForceUpdate::addModules | 2021-11-07 12:21:05 | 0.1 min

In php log file i can see below data
[07-Nov-2021 11:43:01] WARNING: [pool www] child 30972 exited on signal 15 (SIGTERM) after 351041.069654 seconds from start
[07-Nov-2021 11:43:01] NOTICE: [pool www] child 234640 started
[07-Nov-2021 12:20:12] WARNING: [pool www] child 72895, script '/www/wwwroot/default/crm/yf/index.php' (request: "POST /crm/yf/index.php") executing too slow (36.704039 sec), logging
[07-Nov-2021 12:20:12] NOTICE: child 72895 stopped for tracing
[07-Nov-2021 12:20:12] NOTICE: about to trace 72895
[07-Nov-2021 12:20:12] NOTICE: finished trace of 72895
[07-Nov-2021 12:21:22] WARNING: [pool www] child 72895, script '/www/wwwroot/default/crm/yf/index.php' (request: "POST /crm/yf/index.php") execution timed out (106.712272 sec), terminating
[07-Nov-2021 12:21:22] WARNING: [pool www] child 72895 exited on signal 15 (SIGTERM) after 1088666.868857 seconds from start
[07-Nov-2021 12:21:22] NOTICE: [pool www] child 238117 started

**please help me to understand, what is wrong in update procedure so i can upgrade to 6.2.0 and stay latest**

Regards
Jeevan Pendhari

**Comment by rskrzypczak** [comment]
You have a problem with your server or database configuration.
Probably this configuration is not adapted to the size of your application and the operations it performs.

Your server logs showed your problem _..executing too slow.. execution timed out_.
Search google for these errors and try to correct your configuration.

**Comment by mariuszkrzaczkowski** [comment]
Please take a look at our rules on how to report bugs, once you add all the missing information we will start investigating your problem. Right now we don't have enough details to do so.
![github](https://user-images.githubusercontent.com/10198654/140699355-6e071666-f4c8-4f6d-9fc2-535653b034cf.jpg)
