### ISSUE TITLE
[bug] Import records of Leads to my category 

### ISSUE THREAD

**Issue by staniuuu** [YetiForceCompany/YetiForceCRM#15448]
Hi, 

I export my lead and import this records from csv to another category. 
My all records was removed, how Can I restore my previous data?

Best,
Adrian

**Comment by rskrzypczak** [comment]
Man, I really don't know what you're trying to say
https://yetiforce.com/pl/component/zoo/item/how-to-report-bugs

However, if you have put these records in the trash, you can restore them from there.
I am closing the issue due to the lack of data proving the error.
