### ISSUE TITLE
How to use pdf module

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1544]
In sales order,I use the pdf template at deault,like following:
![a](https://cloud.githubusercontent.com/assets/12697896/8744281/860391ec-2ca8-11e5-8f16-85c368275375.jpg)
but when I click the two button,I get a blank web.
![b](https://cloud.githubusercontent.com/assets/12697896/8744314/c2642250-2ca8-11e5-985e-d03d65fd6057.jpg)
How to use pdf ,or it is a bug?

**Comment by waw555** [comment]
See

![animation 42](https://cloud.githubusercontent.com/assets/1402355/8746842/e905fa0c-2ca6-11e5-9dd5-5568621e536a.gif)

**Comment by bpabiszczak** [comment]
The problem must be described in detail [web environment information, error information, information from the logs] and everything else that might prove to be helpful, I recommend reading these articles:
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html 
https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html
