### ISSUE TITLE
[Discussion] Email templates types

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1545]
To me it is not clear what tot do with the Email template type.
In VTiger I can select multiple options where to use the template. (list or detail or both)

Yeti only allows one type and makes more variations. Why is this necessary?

**Comment by bpabiszczak** [comment]
One type? I see:
1. Module
2. Record
3. List
4. Email message

**Comment by zebrahosting** [comment]
LOL, yes but only one can be selected. Meaning if I want to use the same template in lists and records I will need to redo the template. Most of the time it will be the same one.
Guess it might have to do with the variables being different?

**Comment by bpabiszczak** [comment]
Every type means a different place we can start sending emails from. Different places mean different variables that can be replaced, which have no purpose in other views. I don't see any need to change that. It's going to be more developed in the future.

**Comment by bpabiszczak** [comment]
Module – means generating the report from the main module view, it also applies to custom modules, such as the homepage; there will be an option to generate reports from there as well.

Record = summary and details
