### ISSUE TITLE
[Bug] Reservations wont save

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#1546]
When I try to save Reservation, I get the following message:

{"success":false,"error":{"code":"DateTime::__construct(): Failed to parse time string (17-2015-07 15:35:00) at position 0 (1): Unexpected character","message":"DateTime::__construct(): Failed to parse time string (17-2015-07 15:35:00) at position 0 (1): Unexpected character"}}

**Comment by bpabiszczak** [comment]
Please test here: https://gitdeveloper.yetiforce.com/

**Comment by nikdejan** [comment]
Looks OK on https://gitdeveloper.yetiforce.com/ Where can we download ver. 2.0.516?

**Comment by bpabiszczak** [comment]
7-14 days.
