### ISSUE TITLE
[bug] Record selection across lists is ereased

### ISSUE THREAD

**Issue by garryatbrighton** [YetiForceCompany/YetiForceCRM#15460]
As per gif below, it is impossible to select certain records across list view screens. It limiting for instance selective deletion or mass edit on larger number of records. This funcionality works well in other simillar systems (vtiger, SAP, Odoo)
![selection-bug](https://user-images.githubusercontent.com/80203589/142937071-f404f782-8f76-4230-837e-30e5144a4517.gif)

**Comment by mariuszkrzaczkowski** [comment]
this is not a bug, the system does not support it

**Comment by garryatbrighton** [comment]
It rather helpful and logical thing. 
Also moving between records in detail view should be in place.

**Comment by mariuszkrzaczkowski** [comment]
I know, that's why I marked it to keep it in mind
