### ISSUE TITLE
Email picture size issue

### ISSUE THREAD

**Issue by randysrs** [YetiForceCompany/YetiForceCRM#15474]
### Discussed in https://github.com/YetiForceCompany/YetiForceCRM/discussions/15472

<div type='discussions-op-text'>

<sup>Originally posted by **randysrs** November 25, 2021</sup>
having a issue with adding Pictures to emails for workflows.

if i add a image say a 600x600 96dpi image, it seems to work . but if its a 600x700 150 or large DPI the image imports fine 
but when it saves the task type and task title is then blank . 
i can then delete the workflow task and recreate it with the smaller picture then it saves correctly and has the task type and task title.

saved with a 96dpi image
![image](https://user-images.githubusercontent.com/58384233/143400670-1c31f5d9-10a9-4c67-a99b-a8ddc385a025.png)

saved with a larger image that fails

![image](https://user-images.githubusercontent.com/58384233/143405974-7dd9d9cb-3937-4585-b21d-080bbf03a4dc.png)
</div>

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/143546515-236402bd-bec5-4e53-a389-6f0099b13511.jpg)
