### ISSUE TITLE
[bug] Single quotes appears as html code | tree field (Documents module)

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#15488]
Hi,

YF 6.3, tested on developer version.

When adding a new option value containing a single quote character for folder name tree field on documents module, single quote appears as html code (ie. &#039;) on list/edit/detail view.

See screen recording below.

Regards,

![utf8_issue_folder_type_field_yeti6 3](https://user-images.githubusercontent.com/2930560/143889158-7bba6224-acb0-4a0e-bcb0-b91a9a25b664.gif)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/53688ed380fbac15ec300b9e8b019c0e4c987b95
