### ISSUE TITLE
Can't disable/deactivate field: Shared with users' in newly created module

### ISSUE THREAD

**Issue by QVinto** [YetiForceCompany/YetiForceCRM#15507]
# 🐞 Can't disable/deactivate field 'Shared with users' and 'Private' in newly created module (v6.2 rev4)

### ⁉️ Describe the bug 

When new module is created, there is no way in edit filed how to disable or deactivate file Shared with user and Private. In every other modul like accounts, tikets,... there is posibility to disable this field but not in custom module

### 🔥 How to trigger the error

1. Create new module
2. Go to edit fields and try to disable field: Shared with users and Private

### 👍 Expected Behavior

It should be possible to disable this field like in all modules after fresh install

### 👷 Testing

- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com - Private is possible to deactive

### 📷 Screenshot of configuration

doesnt matter

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

doesnt matter

-->

### 🌍 Your Environment

doesnt matter

### ❗️ Inform the community if you solve the problem

🔥

**Comment by mariuszkrzaczkowski** [comment]
The "Shared with users" field is a system field and cannot be disabled.
