### ISSUE TITLE
SalesOrder stock control

### ISSUE THREAD

**Issue by joebordes** [YetiForceCompany/YetiForceCRM#1550]
Product stock control using SO instead of Invoices does not work:
* update workflow is missing the necessary cases
* SO save, trash and restore changes are missing

In case this helps:
https://github.com/tsolucio/corebos/commit/d1731a2a6a177606d9bed4e24bab566aa0f521f6#diff-3cbd2e1ef2feed6ec62fdd1a702c94d9L121

https://github.com/tsolucio/corebos/commit/d1731a2a6a177606d9bed4e24bab566aa0f521f6#diff-4383ff97e2817a83e31b64e2edbd3da5R489

**Comment by bpabiszczak** [comment]
The stock control can't be done in the same way it's done in Vtiger. Namely “Purchase Order” adds to the stock and “Invoice” withdraws. The whole mechanism is illogical and deviates from the standards [it doesn't matter if it's a CRM system or ERP]. Therefore we are planning to introduce new documents in the nearest future, namely:

- Goods Received Note
- Initial Balance
- Material Returns Note
- Goods Issued Note
- Internal Delivery Notes
- Stock-taking Worksheets

they will, among others things, control the stock. Additionally, the system will be able to support many warehouses.

**Comment by bpabiszczak** [comment]
@joebordes says:
Stock update code (function updateProductQty) is being executed for lines with services in inventory modules.
This produces unneccessary incorrect SQL calls.
I solved it in coreBOS with an "inner join" to get only product lines:
tsolucio/corebos@7df99e8

**Comment by bpabiszczak** [comment]
Stock control will be added in 1 – 2 months and it will be a brand new functionality based on completely new product modules [coded from scratch] at the moment product modules, also the ones in Vtiger 5.4, are badly coded and they required a total code refactoring. I'm closing this issue.
