### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by AlexisZverev** [YetiForceCompany/YetiForceCRM#15514]
# 🐞 bug report

On the Yetiforce 6.3
After creating a new project in the Project Manager section, it shows an error: Call to a member function getRelationModel () on bool

Has anyone encountered a similar problem?
Perhaps there is a solution?
With what it can be connected?
I'm a beginner, and I don't even know where to dig yet

### 🔥 How to trigger the error
![Error1](https://user-images.githubusercontent.com/74072835/144706699-6f150920-3768-4620-8ce7-2898adfd21f1.gif)

1. Go to 'Project Management -> Projects'
2. Click on any project
3. See error

### 👷 Testing

- [ ✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.3.0
| Web server (name and version)       |        Apache        |
| PHP                                 |       7.4.26         |
| Browser (name and version)          |         Chrome       |
| Operating System (name and version) |      Windows 10          |
| Database (name and version)         |        MySQL        |
| Service Pack version                |         4       |

**Comment by mariuszkrzaczkowski** [comment]
We tested this on the current version and it appears that the bug doesn't exist anymore.
We need more details how to trigger the error.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/144803409-790d75ba-79bf-4690-9294-990d4e42dad1.jpg)

**Comment by AlexisZverev** [comment]
> We tested this on the current version and it appears that the bug doesn't exist anymore. We need more details how to trigger the error.

Could you clarify what information you need to provide?  Some of the information I have already indicated. What else is important to know in order to solve this problem? 
Thankful for the earlier
![ConfReport](https://user-images.githubusercontent.com/74072835/146249948-c2915261-a239-4631-8fca-4f55c1bcb7ba.png)
