### ISSUE TITLE
Product stock update for service lines

### ISSUE THREAD

**Issue by joebordes** [YetiForceCompany/YetiForceCRM#1551]
Stock update code (function updateProductQty)  is being executed for lines with services in inventory modules.
This produces unneccessary incorrect SQL calls.
I solved it in coreBOS with an "inner join" to get only product lines:
https://github.com/tsolucio/corebos/commit/7df99e8aa71a0e2c4ab863c7eb18db596e7a49a8

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1550
