### ISSUE TITLE
State and API key question

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#1553]
@zebrahosting says:
Wondering if this version is 'testable'. so far can't get it to work so questions:

In the portal2 config:
It needs an API key. Where does that one come from?
CRM ADMIN key or will there be a separate setting in the CRM?

Same config is asking for the portal path, not the URL, correct?

In the CRM config.inc I have set the portal URL
IN the api.php, enabled yetiportal. Does it need any additional settings?

**Comment by zebrahosting** [comment]
This question was moved from portal 2 thread and that's where the questions relate too.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1726
