### ISSUE TITLE
[bug] Recommended innodb_large_prefix=On is deprecated

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#15539]
# 🐞 bug report

### ⁉️ Describe the bug

Today I got the following e-mail message requesting to change the `innodb_large_prefix`  variable to On.

```
**Database**:

  innodb_large_prefix = 'cron: Off' (Recommended: 'On')
```

When doing so, `mysql 10.5.13-MariaDB-log` gives the following warning message:

`Dec 11 16:45:39 joshua mysql-systemd-helper[20938]: 2021-12-11 16:45:39 0 [Warning] The parameter innodb_large_prefix is deprecated and has no effect. It may be removed in future releases. See https://mariadb.com/kb/en/library/xtradbinnodb-file-format/
`

It is unclear what the impact is, if any on the system?

The message is automatically triggered via cron without human intervention.

1. Wait for the cron jobs to run
2. Read e-mail message from application
3. Change variable `innodb_large_prefix=On` in mysql configuration
4. See error in logfile

### 👎 Actual Behavior

E-mail message received indicating an issue.

### 👍 Expected Behavior

No e-mail message indicating an issue.

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

Not applicable!

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

There are no log entries, only the received e-mail messahe

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.3 v1
| Web server (name and version)       |  2.4.43              |
| PHP                                 |  8.0.3              |
| Browser (name and version)          | firefox               |
| Operating System (name and version) |   openSUSE Leap 15.3             |
| Database (name and version)         |   mysql 10.5.13-MariaDB-log             |
| Service Pack version                |     v1           |

**Comment by mariuszkrzaczkowski** [comment]
These are roundcube recommendations and they are right, see here:

https://github.com/roundcube/roundcubemail/blob/0c42af132e14b4869b4142921426ca90e647fcab/INSTALL#L112-L116

Confreport needs to be improved to check the database version.
