### ISSUE TITLE
[bug] Calendar issue after changing module type to advanced

### ISSUE THREAD

**Issue by antcorro** [YetiForceCompany/YetiForceCRM#15535]
# 🐞 bug report

### ⁉️ The form to create a new Todo/Event in Calendar view=CalendarExtended is disappeared after changing module type from Basic to Advanced. The error message is  "Call to a member function getFieldDataType() on bool.". The problem persist also after removing the custom block and fields.

screenshot from my instance
![YetiForce_Calendar_error_2021-12-10_18-58-23](https://user-images.githubusercontent.com/10244840/145629753-1d439410-1736-4db1-af0e-5827e20ab823.png)

### 🔥 How to trigger the error

Steps that I do before  the problem appears:

1. Go to Standard module -> edit fields
2. Select Calendar module
3. Click on Advanced
4. Wait the cron activity

In the User Panel, the Calendar view CalendarExtended is broken. The form does not appear, in the browser inspect console there is a javascript error

![Yetiforce_Calendar_error_browser_console_2021-12-10_20-17-32](https://user-images.githubusercontent.com/10244840/145629666-1a0559d7-d732-4ae3-b786-02aff211286d.png)

### 👎 Actual Behavior

 The form to create a new Todo/Event in Calendar view=CalendarExtended is disappeared 

### 👍 Expected Behavior

The Calendar working again.

### 👷 Testing

- [X ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ X] I confirm that I tested it at https://gitdeveloper.yetiforce.com

Right now, the demo instance on gitstable and gitdeveloper .yetiforce.com are broken.

screenshot from gitdeveloper.yetiforce.com

![Yetiforce_Calendar_issue_Istantanea_2021-12-10_20-01-46](https://user-images.githubusercontent.com/10244840/145629733-16be5e83-d96e-4124-9a0a-39c0a62fd4e6.png)

screenshot from gitstable.yetiforce.com

![YetiForce_calendar_error_stable_2021-12-10_20-42-46](https://user-images.githubusercontent.com/10244840/145632661-dc9d1d51-4003-4a26-b33d-78539a7d99ed.png)

### 📷 Screenshot of configuration

I don't think the problem is related to server configuration. It happens also on demo gitstable and gitdeveloper instances

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

*browser console log screenshot  attacched above.
*The error is visible also in the screenshot above from gitstable and gitdeveloper.yetiforce.com

this is the screenshot from settings panel. can see the tab "managing an advanced block"
![YetiForce_Calenda_issue_settings_2021-12-10_20-36-24](https://user-images.githubusercontent.com/10244840/145632004-d40a6d41-a4fe-4da7-a311-6f9a4544e871.png)

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.2 s.p. 2 (happens also in 6.1 and 6.3)
| Web server (name and version)       |     Apache           |
| PHP                                 |     7.4           |
| Browser (name and version)          |   Firefox  78.14.0            |
| Operating System (name and version) |   Debian 10           |
| Database (name and version)         |    Maria DB 10.1.48            |

### ❗️ Inform the community if you solve the problem

To solve the problem reset Calendar module type to Basic.

**Comment by vovpff** [comment]
Hm. Very interesting. Calendar layout should be non editable as devs said in the past

**Comment by mariuszkrzaczkowski** [comment]
you changed the module type, that's because the advanced module does not have a quick build view, you broke the module

**Comment by antcorro** [comment]
Hello @mariuszkrzaczkowski , 

thanks for your reply, but what's the fix? What it does mean that I have changed the module type? I have just added 2 custom fields to Calendar module from settings panel, and this is permitted by YetiForce. What is wrong with this action?
Can you please help me to fix this?

Thank you
Antonio

**Comment by rskrzypczak** [comment]
It means you changed the module type to _Advanced_, which you shouldn't be doing.
It will not be possible in the future.![image](https://user-images.githubusercontent.com/10221999/145717181-de4010ec-174a-47d5-86cd-c6ddddd987c2.png)
Set the module type to _Basic_ and see if the problem persists.

**Comment by antcorro** [comment]
Thank you guys!
So my info about the Bug was wrong :) I thought the problem was the custom fields, sorry.
I have updated the issue title and body with the correct info so that it will be useful to some one else in the future.

Thank you

**Comment by Marco31Bike** [comment]
Any plan to allow custom fields in Calendar module?

**Comment by rskrzypczak** [comment]
@Marco31Bike use [discussion](https://github.com/YetiForceCompany/YetiForceCRM/discussions) if you have a question.
but by the way, you can already add your own fields to the calendar, you just need to create a separate block first and add custom fields to it.
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/10221999/e1e78e6f-62af-4fe5-ac9e-4306583ed5a6)
