### ISSUE TITLE
[bug] Error after migration

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#15540]
After migration from 6.2 to 6.3 I cannot access menu config from the back-end.
Logs showing not much more than error dialog.
System is nicely optimized, unless upgrade required some extras?

![image](https://user-images.githubusercontent.com/84110093/145704621-6395eef5-3248-4b1a-bfbb-c6ab8cb372fa.png)

**Comment by mariuszkrzaczkowski** [comment]
logs, confreport etc.

![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/145707956-cf13a5c3-7df5-42a0-936c-591c6156e778.jpg)
