### ISSUE TITLE
wrong export to excel [bug] 

### ISSUE THREAD

**Issue by 07litra** [YetiForceCompany/YetiForceCRM#15553]
# 🐞 bug report

### ⁉️ Describe the bug
Create a new filter whith 2 fields. Go to Sales-Opportunities-List .Select some records  and then export to Excel . In exported excel file- all fileds from module Opportunities

### 🔥 How to trigger the error
![Анимация](https://user-images.githubusercontent.com/81667454/146381663-8e63f555-5403-4da7-8737-a63ee16e9a87.gif)

1. Go to 'Opportunities'

### 👷 Testing

- [✔️  ] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
![ConfReport(1)](https://user-images.githubusercontent.com/81667454/146382009-b62d018a-658f-4f0e-a891-2d2f6cab32ab.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |6.3.0
| Web server (name and version)       |     nginx/1.14.2            |
| PHP                                 |         7.3.29       |
| Browser (name and version)          |      FF95.0         |
| Operating System (name and version) |     Win10           |
| Database (name and version)         |         mysql 10.3.29        |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
There is no error here.
This type of export applies to all data in the record.
If you want to export specific fields, use the quick export function.
![image](https://user-images.githubusercontent.com/10221999/146387525-ed66a610-6c72-4d6a-9b16-a847360d2896.png)
![image](https://user-images.githubusercontent.com/10221999/146387682-4aa554cb-6bdb-480a-93b4-deb6db818ea8.png)
