### ISSUE TITLE
[BUG] Message

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1555]
Do not disappear warning

![animation 43](https://cloud.githubusercontent.com/assets/1402355/8769737/7bcedff8-2ebd-11e5-9461-56dbe57a073c.gif)

**Comment by bpabiszczak** [comment]
It's not an error, the notifications are set like that. The red notifications, informing you that something is wrong, won't be closed automatically, you have to press the X button to close them. The blue and yellow notifications will be closed automatically.
