### ISSUE TITLE
[bug] Time control not filtering time for graph and shows only minutes in total time

### ISSUE THREAD

**Issue by QVinto** [YetiForceCompany/YetiForceCRM#15560]
# 🐞 bug report

### ⁉️ Describe the bug

Time control not filtering time for graph and shows only minutes in total time

### 🔥 How to trigger the error

create some working time hours for any company and check time control via accounts->some account->time control

1. Go to accounts and open any account
2. click on time control tab
3. add  at least 1 record for at least 2 persons in time control (better to create more records for more persons to see more problem with it)
4. check graph in time control
5. filter 1 person (assigned to) and check graph, it should show only that person in graph but it doeasnt
6. Total time is only in minutes and always showing total times
7. in some cases time is not equal to real summary of all records
8. click on check box in filter and nothing shows
9. take a look on last screenshot below

### 👎 Actual Behavior
totaly meesed up

### 👍 Expected Behavior

in 6.2 everything working fine so it should be like in 6.2

### 👷 Testing

- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com

GITDEVELOPER.YETIFORCE>COM
wrong total time
![image](https://user-images.githubusercontent.com/4982986/146641436-11ed6f0b-42fc-4323-896d-686d381cffc2.png)

GITSTABLE.YETIFORCE.COM
![image](https://user-images.githubusercontent.com/4982986/146641451-f8868e51-ef5c-451e-ba6b-ccf668dd0663.png)
filter 1 day
![image](https://user-images.githubusercontent.com/4982986/146641461-480fcf3e-1ca3-43dc-b97d-421f7d398741.png)

private yetiforce server
filter with 1 person (assigned to)
![image](https://user-images.githubusercontent.com/4982986/146641636-5743ec12-fd38-4788-8471-9c3ff73c0fdd.png)

**Comment by mariuszkrzaczkowski** [comment]
It works fine so it's designed to always be the sum of the whole, it doesn't work with filters.

**Comment by QVinto** [comment]
It always worked with filters since 4.x till 6.2. we where using it 4 years. Now you changed it?

**Comment by QVinto** [comment]
Like i said. It worked till 6.3. It doeasnt make any sence what you wrote. When you filtering something then you expect that all data will be filtered right?

YF 6.2 with filter for assigned to
![image](https://user-images.githubusercontent.com/4982986/146761504-189cd85e-5386-4ff3-b5a6-23e5c93f7404.png)

YF 6.2 without filter
![image](https://user-images.githubusercontent.com/4982986/146761743-42c504b3-37f7-4a56-a975-0858444e432f.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/2c386e6b093b9218cdae39da012a53cf2fa9b65c
