### ISSUE TITLE
Update: Invalid datetime format: 1292 Truncated incorrect INTEGER value: ''

### ISSUE THREAD

**Issue by kpapastamatis** [YetiForceCompany/YetiForceCRM#15575]
Hello guys,

trying to update from 6.3.0 v1 and i'm keep getting same error on every new update.

Updating module
Some errors appeared during the update. We recommend verifying logs and updating the system once again.

    -------------   2021-12-23 15:30:25   -------------
    > start update tables (base)
      > alter column: vtiger_project:targetbudget ...  | Error(7) [SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: ''
    The SQL being executed was: ALTER TABLE `vtiger_project` CHANGE `targetbudget` `targetbudget` int(10) UNSIGNED] in  
    #0 /var/www/vhosts/site-name/vendor/yetiforce/yii2/db/Command.php(1307): yii\db\Schema->convertException()
    #1 /var/www/vhosts/site-name/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
    #2 /var/www/vhosts/site-name/app/Db/Importer.php(698): yii\db\Command->execute()
    #3 /var/www/vhosts/site-name/app/Db/Importer.php(154): App\Db\Importer->updateTables()
    #4 /var/www/vhosts/site-name/cache/updates/updates/init.php(105): App\Db\Importer->updateScheme()
    #5 /var/www/vhosts/site-name/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update()
    #6 /var/www/vhosts/site-name/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate()
    #7 /var/www/vhosts/site-name/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import()
    #8 /var/www/vhosts/site-name/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3()
    #9 /var/www/vhosts/site-name/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod()
    #10 /var/www/vhosts/site-name/include/main/WebUI.php(190): Settings_ModuleManager_ModuleImport_View->process()
    #11 /var/www/vhosts/site-name/index.php(26): Vtiger_WebUI->process()
    #12 {main} !!!
    # end update tables    (0.07s)
    > start drop tables
    # end drop tables (0 min)
    > start drop columns
    # end drop columns (0 min)
    > start drop indexes
    # end drop indexes (0 min)
    > start add data rows (base)
    # end add data rows (0 min)
    > start reset sequence
    # end reset sequence (0 min)
    > start update foreign key (base)
    # end update foreign key    (0s)

If error is correct about datetime, i cannot find how to empty **date.timezone** on my php config. I am attaching photo with mention part.
![image](https://user-images.githubusercontent.com/34310504/147289433-80075ac9-797b-43fd-85e1-69d0048f621e.png)

Any ideas ?

I didn't test update on your demo site based on your guidelines before opening ticket because you have already 3 updates above my installed version.

Thanks in advance,
Konstantinos

**Comment by mariuszkrzaczkowski** [comment]
It looks like you have a non-numeric value in the targetbudget field, show what the values in that database column are
```sql
SELECT targetbudget FROM `vtiger_project` WHERE targetbudget <> 0 ORDER BY `targetbudget` DESC; 
```

**Comment by kpapastamatis** [comment]
Thanks for your quickly response Mariusz.

I have only 2 records but i haven't used this field yet.

![Screenshot_20211223_231653_com.android.chrome.jpg](https://user-images.githubusercontent.com/34310504/147292259-a2db3fd9-ef54-4c03-a6cc-1c0f4d1f2338.jpg)

**Comment by mariuszkrzaczkowski** [comment]
I do not see the query results send a screenshot from the computer and attach the full server configuration report (ConfReport)

**Comment by kpapastamatis** [comment]
You cannot see them because fields were empty.
I didn't used this field because i am still testing the program and it wasn't required for submitting data.

I put some numerical values on both projects and tried again to update and voila! Update was successful!

Thanks a lot for your immediate help Mariusz. Appreciate that.
