### ISSUE TITLE
workflow doesnt have the fields from the products table (like qty, unit price) in the quotes module

### ISSUE THREAD

**Issue by Ilamparithi-Tamizhanangu** [YetiForceCompany/YetiForceCRM#15577]
Hi,

I am trying to create the workflow based for the quotes module.

When i try to create the update field value for the quotes modules, it doesnt have the options to add the fields  from the products table (like qty, unit price) .

Could you please share the procedure to add the fields from products table to workflow. 

Thanks in advance.

**Comment by vovpff** [comment]
This functionality unavailable in system. You can do anything with selfwritten handlers or can buy 3rd party extension

**Comment by Ilamparithi-Tamizhanangu** [comment]
thanks for the update.
