### ISSUE TITLE
[BUG INSTALL] Install error v 2.0.526

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1558]
Version Apache 2.2.29
Version PHP 5.4.35
Version MySQL 5.5.42-cll
OS linux
![animation 44](https://cloud.githubusercontent.com/assets/1402355/8775008/a50f3b84-2efd-11e5-9ee6-b8002b81fddb.gif)

![e1](https://cloud.githubusercontent.com/assets/1402355/8775074/20d55cbc-2efe-11e5-9530-be0a2c275768.JPG)
![e2](https://cloud.githubusercontent.com/assets/1402355/8775072/20d3643e-2efe-11e5-9a7c-9969443dfe18.JPG)
![e3](https://cloud.githubusercontent.com/assets/1402355/8775077/20d7a166-2efe-11e5-8d55-f68f4f1a93ba.JPG)
![e4](https://cloud.githubusercontent.com/assets/1402355/8775076/20d6bf76-2efe-11e5-8690-d36795de0b63.JPG)
![e5](https://cloud.githubusercontent.com/assets/1402355/8775073/20d3b4ac-2efe-11e5-9ffe-694ee27ec2ed.JPG)
![e6](https://cloud.githubusercontent.com/assets/1402355/8775075/20d5e722-2efe-11e5-8763-2bb0c3c50d5f.JPG)
![e7](https://cloud.githubusercontent.com/assets/1402355/8775078/20f026aa-2efe-11e5-8bff-b9404c495200.JPG)

**Comment by bpabiszczak** [comment]
Your configuration of the error_reporting parameter is incorrect

**Comment by waw555** [comment]
What do I need to specify?

Access to the php.ini in hosting no, htaccess blocked error_reporting causing an error 500

**Comment by bpabiszczak** [comment]
I don't understand your question. Your error_reporting configuration is incorrect. First of all, you shouldn't display the errors on the screen; secondly, "strict standard" errors should be suppressed in the error_reporting parameter.

Every hosting might have it configured in a different way. In some of them it is set in the php.ini file, which should be added to the main catalog, in some others it's set using htaccess, in others it's configured from the panel. The server administrator should provide all the necessary information. It has nothing to do with YetiForce, it's an incorrect server configuration.

**Comment by waw555** [comment]
Well, that's not a problem YetiForce, just strange that after installing all the bugs are gone, and the system does not display them again, I will try in the near future on the local server to try

**Comment by bpabiszczak** [comment]
If errors show up during the installation process, and after the installation the errors disappear, then it's an error. First of all please correct your configuration, and then if the error still occurs, describe it in detail so that we can recreate it in our system.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/5f407a83b23ad9be2d94de7172147a2be6bbdb09
