### ISSUE TITLE
Custom module in calendar

### ISSUE THREAD

**Issue by vinzdrance** [YetiForceCompany/YetiForceCRM#1559]
Hello

Yetiforce is great !!

Is it possible at this time to integrate a custom module in the calendar, like opportunities etc

I've a custom module with a date field which I would like to render in the calendar.

What is the best way ?

Thanks

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1055
