### ISSUE TITLE
Mail Client

### ISSUE THREAD

**Issue by phongih** [YetiForceCompany/YetiForceCRM#156]
I have problem with php.ini file. Can you help me to config it?

The next couple of extensions are optional and recommended to get the best performance:
ERROR - FileInfo | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/book.fileinfo.php
OK - Libiconv
OK - Multibyte
OK - OpenSSL
OK - Mcrypt
ERROR - Intl | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/book.intl.php
ERROR - Exif | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/book.exif.php
Checking available databases

Check which of the supported extensions are installed. At least one of them is required.

ERROR - MySQL | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/ref.pdo-mysql.php
ERROR - PostgreSQL | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/ref.pdo-pgsql.php
ERROR - SQLite | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/ref.pdo-sqlite.php
ERROR - SQLite (v2) | | http://www.php.net/manual/en/ref.pdo-sqlite.php
ERROR - SQL Server (SQLSRV) | | http://www.php.net/manual/en/ref.pdo-sqlsrv.php
ERROR - SQL Server (DBLIB) | | http://www.php.net/manual/en/ref.pdo-dblib.php
Check for required 3rd party libs

This also checks if the include path is set correctly.

ERROR - PEAR | Failed to load PEAR.php | http://pear.php.net
ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime

**Comment by waran70** [comment]
All seems OK :-)

**Comment by mariuszkrzaczkowski** [comment]
Show also the server configuration (Settings > About YetiForce > Server configuration)
