### ISSUE TITLE
YetiForce CRM 6.3 SecurityFix v4 patch issues

### ISSUE THREAD

**Issue by Jeroenleender** [YetiForceCompany/YetiForceCRM#15608]
Tried to run the update several times but keep running into this issue.

Other updates from YetiForce CRM 6.2 SecurityFix v2 and up all ran fine except this last one.

Updating module
Some errors appeared during the update. We recommend verifying logs and updating the system once again.

    -------------   2022-01-04 06:39:12   -------------
    > start update tables (base)
      > alter column: vtiger_project:targetbudget ...  | Error(7) [SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: ''
    The SQL being executed was: ALTER TABLE `vtiger_project` CHANGE `targetbudget` `targetbudget` int(10) UNSIGNED] in  
    #0 /home/hackprot/public_html/vendor/yetiforce/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `vt...')
    #1 /home/hackprot/public_html/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `vt...')
    #2 /home/hackprot/public_html/app/Db/Importer.php(698): yii\db\Command->execute()
    #3 /home/hackprot/public_html/app/Db/Importer.php(154): App\Db\Importer->updateTables(Object(Importers\Base))
    #4 /home/hackprot/public_html/cache/updates/updates/init.php(105): App\Db\Importer->updateScheme()
    #5 /home/hackprot/public_html/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update()
    #6 /home/hackprot/public_html/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate()
    #7 /home/hackprot/public_html/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import('cache/814cc8a54...')
    #8 /home/hackprot/public_html/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3(Object(App\Request))
    #9 /home/hackprot/public_html/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod('importUserModul...', Object(App\Request))
    #10 /home/hackprot/public_html/include/main/WebUI.php(190): Settings_ModuleManager_ModuleImport_View->process(Object(App\Request))
    #11 /home/hackprot/public_html/index.php(26): Vtiger_WebUI->process(Object(App\Request))
    #12 {main} !!!
    # end update tables    (0.02s)
    > start drop tables
    # end drop tables (0 min)
    > start drop columns
    # end drop columns (0 min)
    > start drop indexes
    # end drop indexes (0 min)
    > start add data rows (base)
    # end add data rows (0 min)
    > start reset sequence
    # end reset sequence (0 min)
    > start update foreign key (base)
    # end update foreign key    (0s)

Other updates from

**Comment by mariuszkrzaczkowski** [comment]
Duplicate of #15575
