### ISSUE TITLE
Pole słownikowe - wielkorotnego wyboru

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#1560]
Nie można użyć własnego pola w postaci pola wyboru (wielokrotnego oraz pojedynczego) - bug w wersji developerskiej. Nie pojawia się po próbie utworzenia.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1552

**Comment by zimart** [comment]
Niestety , u mnie nie działa w dalszym ciągu.

**Comment by bpabiszczak** [comment]
Bo jeszcze jest nieskończone, wgrana została 1 poprawka, jutro wgramy 2. Pierwsza rozwiązywała problem, że w ogóle nie było można tworzyć wartości w picklist, dodatkowo nie działa zapis tego pola, więc teraz musimy to poprawić. Na jutro będzie to gotowe.
