### ISSUE TITLE
[BUG] Creating PDF template with contact picture

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1562]
Trying to create a PDF template containing a contact picture.
Added the link variable as IMAGE url but that does error out the PDF creation:
TCPDF ERROR: [Image] Unable to get the size of the image: wendy-aarts.jpeg
(sizes are set in the image properties but I guess it does not find the image location)

Adding the plain link variable in the body only gives the link itself.

**Comment by rskrzypczak** [comment]
![Uploading Image4h.gif…]()
