### ISSUE TITLE
[bug] Filter List not visible

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#15647]
I have added Module in CRM and created Filter List, but same are not visible to user. Not able to understand why and for all other modules same is shown properly.

List not shown here
![image](https://user-images.githubusercontent.com/12723595/149932372-c3e902da-05d1-4e9f-88f6-afad610be1a5.png)

In settings if I check all added filters are shown
![image](https://user-images.githubusercontent.com/12723595/149932845-d934e681-9667-4d22-917d-b5f5f38fbf3b.png)

All filters are set to Public

Kindly assist in the matter

Regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/149935826-122685d9-65b5-4797-bbc8-1faedc169106.jpg)

**Comment by JEEVAN28** [comment]
**I have searched for the issue on Github but not found relevant information**

# 🐞 bug report

### ⁉️ Describe the bug


I have added new Module named as **Samples** In this module we have field named as **Status**
Module is functioning properly. On List view I have added filters based on Status Value. Same are added in system and can be seen from Settings Menu via admin panel, but they don't get displayed not even to creator.



### 🔥 How to trigger the error
Below are the recording of the error
![Issue_In_Filter_List](https://user-images.githubusercontent.com/12723595/150127048-61e9e3ff-d57a-45fd-8091-96140eb6cf12.gif)


### 👎 Actual Behavior
List Filter is not visible other than All



### 👍 Expected Behavior
List should be visible similar to other module. Problem is only with this module.



### 👷 Testing



- [X ] I confirm that I tested it at https://gitstable.yetiforce.com and it works
- [X ] I confirm that I tested it at https://gitdeveloper.yetiforce.com and it works

### 📷 Screenshot of configuration
![image](https://user-images.githubusercontent.com/12723595/150125856-0293b676-bb5e-461c-b1e0-451f7676b4df.png)

**Comment by Jianbin719** [comment]
Did you specific any filter in menu setting？

**Comment by JEEVAN28** [comment]
> Did you specific any filter in menu setting？

No, Settings are same as other modules

**Comment by JEEVAN28** [comment]
please assist in this matter

**Comment by JEEVAN28** [comment]
I have found the reason
In Setup Menu - > Go to
![image](https://user-images.githubusercontent.com/12723595/162927236-e0785b2a-b3e0-4d0f-afbc-11be6e064119.png)

and remove filter from edit menu option,
![image](https://user-images.githubusercontent.com/12723595/162927114-4456edbc-c113-4d86-a224-892bf41f3f79.png)

after this list started showing.

Thanks
Regards
Jeevan Pendhari
