### ISSUE TITLE
Are developers team at vacations?

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1565]
Hello.
As a see at yetiforce repo there is not any update a couple of weeks.
Are the dev team on vacations?
And when is estimated to update the yeti repo?

**Comment by mariuszkrzaczkowski** [comment]
Check here (developer branch ) https://github.com/YetiForceCompany/YetiForceCRM/commits/developer

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/milestones

**Comment by eptapsyxos** [comment]
Thank you very much.
