### ISSUE TITLE
[notice] YetiForceCRM and php 8.1.2

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#15653]
# 🐞 bug report

### ⁉️ Describe the bug

**Just a notice (as php 8.1. is not supported yet):** 
YetiForceCRM will generate a large number of warning messsages due to deprecated use of types, especially in the database library yii2, if using the latest version of php, i.e. 8.1.

I recommend to refrain from upgrading php to version 8.1, even though version 8.1. is faster than 8.0!

**Comment by mariuszkrzaczkowski** [comment]
we know about the warnings, you can see a lot in tests on 8.1
https://github.com/YetiForceCompany/YetiForceCRM/runs/4896083769?check_suite_focus=true
