### ISSUE TITLE
error (notice) in filter Accounts after permissions has been changed - yetiforce stable

### ISSUE THREAD

**Issue by QVinto** [YetiForceCompany/YetiForceCRM#15667]
# 🐞 bug report

### ⁉️ Describe the bug

![image](https://user-images.githubusercontent.com/4982986/151002240-cb9ff9a5-0b85-4b90-bc3d-8f6977cbf2bc.png)

### 🔥 How to trigger the error

I made some changes in groups and assigment for module account, also i made changes for user guest and demo and assigned owner permissions. I am not sure what could cause this.

1. Go to 'accounts' and you will see the error

- [✔️ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration
https://gitstable.yetiforce.com/

**Comment by mariuszkrzaczkowski** [comment]
Did you check on gitdeveloper.yetiforce.com? I think it's fixed already

**Comment by QVinto** [comment]
i did not. I am not sure how exactly i did this one only that i changed permissions on YF Demo and YF Guest and both set to same role secretary office. 

Also this notice showed me maybe 2-3 times but not always after i made changes.
