### ISSUE TITLE
[BUG] filtered list in mail templates

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1567]
When trying to create a filtered list in mail templates:
Trying to select a module:
Condition -> module -> contains 

does not show a list of modules.

**Comment by bpabiszczak** [comment]
Please describe in detail what is wrong and how it should work. It would be perfect if you added some screenshots.

**Comment by zebrahosting** [comment]
Open menu Database
Select Email templates
Create a new filter
Choose module in the conditions
IN the box on the right the currently available modules should show up to select but none appears.

![screen shot 2015-07-24 at 09 18 49](https://cloud.githubusercontent.com/assets/10379403/8869614/ff05df54-31e5-11e5-9adf-6d0fae39fc61.png)

**Comment by waw555** [comment]
It seems necessary to enter the name of the module handles ))))
