### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by kassimg12** [YetiForceCompany/YetiForceCRM#15688]
# 🐞 bug report

### 🔥 How to trigger the error

open pick list relation page

1. Go to 'setting>standard modules'
2. Click on 'Fields - picklists/relation'
3. See error

### 👎 Actual Behavior

shows an error message "ERR_NOT_MODULE"

### 👍 Expected Behavior

Open list of picklist relations

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

No log file is available

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.3.0
| Web server (name and version)       |                |
| PHP                                 |     8.0.14           |
| Browser (name and version)          |        any        |
| Operating System (name and version) |          ubuntu 20.04      |
| Database (name and version)         |    mysql            |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
Your description is insufficient.
The problem  does not occur on the test environments, and you didn't provide any logs.
