### ISSUE TITLE
[Question] How to deal with translations

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1568]
I started with a Dutch translation but everything is still changing a lot. What is the best way to make sure the newly created labels will be also in the (local) translated version?

If there would be a Dutch language folder in the dev version with (for now mainly English) labels, would the structure be updated when language strings change done by coders?

Or should I add the folders on my own Github version and send pus request when something is done?
(not very familiar with Github system yet)

**Comment by waw555** [comment]
Do translating in your branch and add pull request

**Comment by zebrahosting** [comment]
How does that deal with fields that are daily added and or changed in the US version?
Guess I need to notice them and copy by hand to the Dutch ones?

**Comment by waw555** [comment]
Add language in the system, begin translating

Then copy your folder to your branch and make github pull request, your translation is added to the system, then translate the text changes as the system

See Example:

![animation 45](https://cloud.githubusercontent.com/assets/1402355/8796290/1b6d0c3e-2fad-11e5-9406-8f5ee707084e.gif)

OR

Make a copy of any folder, make the transfer and add to github

![animation 46](https://cloud.githubusercontent.com/assets/1402355/8796439/474fdd58-2fae-11e5-8d9d-d2b0d2305502.gif)

**Comment by mariuszkrzaczkowski** [comment]
The language added to the system currently includes a copy of the English translation.https://github.com/YetiForceCompany/YetiForceCRM/commit/71fe0f3a16c0221831520b50f88ea2a374d7a5bd

**Comment by mariuszkrzaczkowski** [comment]
Thanks waw555, great tutorial :)

**Comment by waw555** [comment]
Do not forget to git pull before making changes - this is important !!!
