### ISSUE TITLE
Mysql error innodb_large_prefix

### ISSUE THREAD

**Issue by randysrs** [YetiForceCompany/YetiForceCRM#15703]
hey i just update to 6.3 gave me a configuration error Database:
  innodb_large_prefix = 'www: Off | cron: Off' (Recommended: 'On')

when adding the command to mysql i get this error .

 ERROR 1193 (HY000): Unknown system variable 'innodb_large_prefix'

system functions fine but i was reading that innodb_large_prefix was either being or already deprecated.

**Comment by rskrzypczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/15539
