### ISSUE TITLE
[bug] Dashboard widget | mobile devices | Link column non-clickable

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#15724]
Just short report here that when we go to Dashboard/Homepage the Linked columns are not clickable, so cannot go to the relevant record using finger. I am considering it as a bug, is it?

Best

**Comment by mariuszkrzaczkowski** [comment]
Attach additional information, screenshot, system version

**Comment by s2b-git** [comment]
O.o It seems to be something with cache. now working. Sorry for alarm. Closing
