### ISSUE TITLE
[bug] installation of 6.2.0 from 6.1.0

### ISSUE THREAD

**Issue by deepti4666** [YetiForceCompany/YetiForceCRM#15731]
# 🐞 bug report

### ⁉️ Describe the bug

E_WARNING: ZipArchive::getFromName(): Invalid or uninitialized Zip object in /home/boardroo/public_html/crm/vtlib/Vtiger/PackageImport.php, line 45

![image](https://user-images.githubusercontent.com/57940552/154670879-4f0ee064-ffa0-42ff-b532-7b55417ce9a5.png)

E_WARNING: ZipArchive::close(): Invalid or uninitialized Zip object in /home/boardroo/public_html/crm/vtlib/Vtiger/PackageImport.php, line 378

Failed
Module does not contain default language (en-US).

![image](https://user-images.githubusercontent.com/57940552/154670924-2a2fbdae-40ba-4afd-b65d-1ed8465ecbc0.png)

### 🔥 How to trigger the error

[My home page](https://boardroominabox.co.za/crm/)
[Software configuration](https://boardroominabox.co.za/crm/index.php?module=Vtiger&parent=Settings&view=Index)
Logs
[Updates](https://boardroominabox.co.za/crm/index.php?parent=Settings&module=Updates&view=Index)
System settings

1. Go to 'Admin'
2. Click on 'Logs'
3. Scroll down to 'Updates'
4. Select 'download package'
5. Select 'install package'

![image](https://user-images.githubusercontent.com/57940552/154671284-9a49e413-a034-4631-8a93-b32c08a290de.png)

![image](https://user-images.githubusercontent.com/57940552/154671388-2b043d37-856d-4535-83cc-c377a000b2ee.png)

### 👎 Actual Behavior

Errors

![image](https://user-images.githubusercontent.com/57940552/154671429-6f8a219e-4fb0-443d-9fd9-967081720afe.png)

### 👍 Expected Behavior

Yeti updated to new version

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![ConfReport](https://user-images.githubusercontent.com/57940552/154672789-92d30479-f62a-4225-b23f-9097aa63855d.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Email sent

![image](https://user-images.githubusercontent.com/57940552/154671780-0dde938c-1286-4b35-bab2-d1bde26aa35f.png)

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by snmin** [comment]
I also encountered this error and don't know how to fix it.

**Comment by mariuszkrzaczkowski** [comment]
1. correct the server configuration
2. what update package are you uploading?  where did you download it from?

**Comment by deepti4666** [comment]
From the server/software itself.

I didn't upload anything, 

I followed these steps on the system

Go to 'Admin'
Click on 'Logs'
Scroll down to 'Updates'
Select 'download package'
Select 'install package'

**Comment by deepti4666** [comment]
E_WARNING: ZipArchive::getFromName(): Invalid or uninitialized Zip object in /home/boardroo/public_html/crm/vtlib/Vtiger/PackageImport.php, line 45
#0 vtlib/Vtiger/PackageImport.php (45)  >>  ZipArchive->getFromName('manifest.xml')
#1 vtlib/Vtiger/PackageImport.php (279)  >>  vtlib\PackageImport->__parseManifestFile()
#2 vtlib/Vtiger/PackageImport.php (390)  >>  vtlib\PackageImport->checkZip('cache/aa5d2757f2a751577714a9e97caa26ca.zip')
#3 modules/Settings/ModuleManager/views/ModuleImport.php (98)  >>  vtlib\PackageImport->getModuleNameFromZip('cache/aa5d2757f2a751577714a9e97caa26ca.zip')
#4 app/Controller/ExposeMethod.php (65)  >>  Settings_ModuleManager_ModuleImport_View->importUserModuleStep2()
#5 modules/Settings/ModuleManager/views/ModuleImport.php (49)  >>  Settings_ModuleManager_ModuleImport_View->invokeExposedMethod('importUserModuleStep2')
#6 include/main/WebUI.php (189)  >>  Settings_ModuleManager_ModuleImport_View->process()
#7 index.php (28)  >>  Vtiger_WebUI->process()

E_WARNING: ZipArchive::close(): Invalid or uninitialized Zip object in /home/boardroo/public_html/crm/vtlib/Vtiger/PackageImport.php, line 378
#0 vtlib/Vtiger/PackageImport.php (378)  >>  ZipArchive->close()
#1 vtlib/Vtiger/PackageImport.php (390)  >>  vtlib\PackageImport->checkZip('cache/aa5d2757f2a751577714a9e97caa26ca.zip')
#2 modules/Settings/ModuleManager/views/ModuleImport.php (98)  >>  vtlib\PackageImport->getModuleNameFromZip('cache/aa5d2757f2a751577714a9e97caa26ca.zip')
#3 app/Controller/ExposeMethod.php (65)  >>  Settings_ModuleManager_ModuleImport_View->importUserModuleStep2()
#4 modules/Settings/ModuleManager/views/ModuleImport.php (49)  >>  Settings_ModuleManager_ModuleImport_View->invokeExposedMethod('importUserModuleStep2')
#5 include/main/WebUI.php (189)  >>  Settings_ModuleManager_ModuleImport_View->process()
#6 index.php (28)  >>  Vtiger_WebUI->process()

**Comment by mariuszkrzaczkowski** [comment]
start by improving your server configuration, this error about PHP problems
