### ISSUE TITLE
[bug] "Mass transfer ownership" in Profile

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#15738]
# 🐞 bug report

### ⁉️ Describe the bug

if "Mass transfer ownership" action has been disabled in Profile, the relative button, in details view, is still there.

### 🔥 How to trigger the error

1. Edit a profile
2. disable "Mass transfer ownership" action in any module
3. go in frontend (no admin user), in details view, for any module's record, the action button is still there

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment]
Tested on dev and can't see an error, did you test on a user without root privileges
![image](https://user-images.githubusercontent.com/10198654/160132589-70088a66-5bd1-47cb-a494-cbd5d01f4c81.png)

![image](https://user-images.githubusercontent.com/10198654/160132635-84654dd1-261b-4858-a586-4e5ffd4c0a30.png)

**Comment by davide-alghi** [comment]
sorry for the late. yes with `... (no admin user) ...`

in the profile, for Accounts module

![Schermata da 2022-03-26 09-59-50](https://user-images.githubusercontent.com/48508691/160232806-938d0c5b-0546-4434-94c6-c72f028440d7.png)

logged in as non-admin user and "transfer for related records" button (this too is a mass transfer action) is still there

![Schermata da 2022-03-26 10-06-47](https://user-images.githubusercontent.com/48508691/160232834-b332b2c0-1783-432d-8214-5ae0d0b93b2a.png)

if you click on it

![Schermata da 2022-03-26 10-05-40](https://user-images.githubusercontent.com/48508691/160232896-b150cd00-eee1-41e2-9731-7559bb749199.png)

just now I see additional JS error, in detail view

![Schermata da 2022-03-26 10-05-20](https://user-images.githubusercontent.com/48508691/160232920-309e1588-ffe5-4510-bbb5-9582e44677e6.png)

**Comment by rskrzypczak** [comment]
There is a separate action to verify the availability of this button:
![image](https://user-images.githubusercontent.com/10221999/160245519-9cdadddd-6650-46c8-8420-bf6c12ec6cf2.png)
However, we will take a closer look at this, thanks.

**Comment by davide-alghi** [comment]
thanks, I get it

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/160345966-f936cdd7-7683-48e9-afe9-8177d50dfdcf.png)
