### ISSUE TITLE
NEW ACCOUNT/CONTACT is not possible with clean installation - Still

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#1573]
Hello everyone,

i've tried the installation of Master & Developer release. After installing it an ADDING Organization/Contact etc i get: "{"success":false,"error":{"code":"There is no active transaction","message":"There is no active transaction"}}"

the installation process works fine!

Can somebody help me?

Best, Ralph

**Comment by bpabiszczak** [comment]
Please read this:
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

and test here:
3. https://gitdeveloper.yetiforce.com/

**Comment by ralphkretzschmar** [comment]
Hello Mr. Pabiszczak,

thank you for your reply – i’ll do my best in bug reporting.

If got some new information – does the follwing information help?

After setting up the database and trying to create a new company i get the following message:

Database ERROR: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'inheritsharing' at row 1

#0  PearDatabase->checkError() called at [C:\inetpub\wwwroot\yfm\include\database\PearDatabase.php:316]
#1  PearDatabase->pquery() called at [C:\inetpub\wwwroot\yfm\include\CRMEntity.php:299]
#2  CRMEntity->insertIntoCrmEntity() called at [C:\inetpub\wwwroot\yfm\include\CRMEntity.php:90]
#3  CRMEntity->saveentity() called at [C:\inetpub\wwwroot\yfm\include\CRMEntity.php:820]
#4  CRMEntity->save() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\models\Module.php:169]
#5  Vtiger_Module_Model->saveRecord() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\models\Record.php:260]
#6  Vtiger_Record_Model->save() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\actions\Save.php:49]
#7  Vtiger_Save_Action->saveRecord() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\actions\Save.php:26]
#8  Vtiger_Save_Action->process() called at [C:\inetpub\wwwroot\yfm\include\main\WebUI.php:204]
#9  Vtiger_WebUI->process() called at [C:\inetpub\wwwroot\yfm\index.php:25]


Attached you can find the log files - Does this help?? I’m really new to bug reporting.

Best regards,
Ralph


Von: Błażej Pabiszczak [mailto:notifications@github.com]
Gesendet: Mittwoch, 22. Juli 2015 12:30
An: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
Cc: Ralph Kretzschmar <Ralph.Kretzschmar@hoerer-flamme.com>
Betreff: Re: [YetiForceCRM] NEW ACCOUNT/CONTACT is not possible with clean installation - Still (#1573)


Please read this:
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

and test here:
3. https://gitdeveloper.yetiforce.com/

**Comment by ralphkretzschmar** [comment]
Hello everyone,

are there any news?

Best regards & thanks for helping me,
Ralph Kretzschmar

Von: Ralph Kretzschmar
Gesendet: Donnerstag, 23. Juli 2015 13:56
An: YetiForceCompany/YetiForceCRM <reply@reply.github.com>
Betreff: AW: [YetiForceCRM] NEW ACCOUNT/CONTACT is not possible with clean installation - Still (#1573)
Wichtigkeit: Hoch

Hello Mr. Pabiszczak,

thank you for your reply – i’ll do my best in bug reporting.

If got some new information – does the follwing information help?

After setting up the database and trying to create a new company i get the following message:

Database ERROR: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'inheritsharing' at row 1

#0  PearDatabase->checkError() called at [C:\inetpub\wwwroot\yfm\include\database\PearDatabase.php:316]
#1  PearDatabase->pquery() called at [C:\inetpub\wwwroot\yfm\include\CRMEntity.php:299]
#2  CRMEntity->insertIntoCrmEntity() called at [C:\inetpub\wwwroot\yfm\include\CRMEntity.php:90]
#3  CRMEntity->saveentity() called at [C:\inetpub\wwwroot\yfm\include\CRMEntity.php:820]
#4  CRMEntity->save() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\models\Module.php:169]
#5  Vtiger_Module_Model->saveRecord() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\models\Record.php:260]
#6  Vtiger_Record_Model->save() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\actions\Save.php:49]
#7  Vtiger_Save_Action->saveRecord() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\actions\Save.php:26]
#8  Vtiger_Save_Action->process() called at [C:\inetpub\wwwroot\yfm\include\main\WebUI.php:204]
#9  Vtiger_WebUI->process() called at [C:\inetpub\wwwroot\yfm\index.php:25]


Attached you can find the log files - Does this help?? I’m really new to bug reporting.

Best regards,
Ralph


Von: Błażej Pabiszczak [mailto:notifications@github.com]
Gesendet: Mittwoch, 22. Juli 2015 12:30
An: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com<mailto:YetiForceCRM@noreply.github.com>>
Cc: Ralph Kretzschmar <Ralph.Kretzschmar@hoerer-flamme.com<mailto:Ralph.Kretzschmar@hoerer-flamme.com>>
Betreff: Re: [YetiForceCRM] NEW ACCOUNT/CONTACT is not possible with clean installation - Still (#1573)


Please read this:
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

and test here:
3. https://gitdeveloper.yetiforce.com/

**Comment by ralphkretzschmar** [comment]
Now with the files ☺ sorry forgot it in my last mail today

Von: Ralph Kretzschmar
Gesendet: Freitag, 31. Juli 2015 14:05
An: 'YetiForceCompany/YetiForceCRM' <reply@reply.github.com>
Cc: 'YetiForceCRM@noreply.github.com' <YetiForceCRM@noreply.github.com>
Betreff: AW: [YetiForceCRM] NEW ACCOUNT/CONTACT is not possible with clean installation - Still (#1573)

Hello everyone,

are there any news?

Best regards & thanks for helping me,
Ralph Kretzschmar

Von: Ralph Kretzschmar
Gesendet: Donnerstag, 23. Juli 2015 13:56
An: YetiForceCompany/YetiForceCRM <reply@reply.github.com>
Betreff: AW: [YetiForceCRM] NEW ACCOUNT/CONTACT is not possible with clean installation - Still (#1573)
Wichtigkeit: Hoch

Hello Mr. Pabiszczak,

thank you for your reply – i’ll do my best in bug reporting.

If got some new information – does the follwing information help?

After setting up the database and trying to create a new company i get the following message:

Database ERROR: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'inheritsharing' at row 1

#0  PearDatabase->checkError() called at [C:\inetpub\wwwroot\yfm\include\database\PearDatabase.php:316]
#1  PearDatabase->pquery() called at [C:\inetpub\wwwroot\yfm\include\CRMEntity.php:299]
#2  CRMEntity->insertIntoCrmEntity() called at [C:\inetpub\wwwroot\yfm\include\CRMEntity.php:90]
#3  CRMEntity->saveentity() called at [C:\inetpub\wwwroot\yfm\include\CRMEntity.php:820]
#4  CRMEntity->save() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\models\Module.php:169]
#5  Vtiger_Module_Model->saveRecord() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\models\Record.php:260]
#6  Vtiger_Record_Model->save() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\actions\Save.php:49]
#7  Vtiger_Save_Action->saveRecord() called at [C:\inetpub\wwwroot\yfm\modules\Vtiger\actions\Save.php:26]
#8  Vtiger_Save_Action->process() called at [C:\inetpub\wwwroot\yfm\include\main\WebUI.php:204]
#9  Vtiger_WebUI->process() called at [C:\inetpub\wwwroot\yfm\index.php:25]


Attached you can find the log files - Does this help?? I’m really new to bug reporting.

Best regards,
Ralph


Von: Błażej Pabiszczak [mailto:notifications@github.com]
Gesendet: Mittwoch, 22. Juli 2015 12:30
An: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com<mailto:YetiForceCRM@noreply.github.com>>
Cc: Ralph Kretzschmar <Ralph.Kretzschmar@hoerer-flamme.com<mailto:Ralph.Kretzschmar@hoerer-flamme.com>>
Betreff: Re: [YetiForceCRM] NEW ACCOUNT/CONTACT is not possible with clean installation - Still (#1573)


Please read this:
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

and test here:
3. https://gitdeveloper.yetiforce.com/

**Comment by mf901** [comment]
In my case the error 
 General error: 1366 Incorrect integer value: '' for column...
was due to wrong mysql settings:
As mentioned in the webserver requirements (https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html) in /etc/mysql/my.cnf SQL_MODE should ***NOT*** contain STRICT_TRANS_TABLE
