### ISSUE TITLE
[bug] [PL] Interfejs pokazuje LBL zamiast poprawnych nazw

### ISSUE THREAD

**Issue by cedeka78** [YetiForceCompany/YetiForceCRM#15749]
Wersja 6.3.0
Problem występuje zarówno w wersji użytkowanej, jak i świeżo zainstalowanej w celu potwierdzenia występowania problemu.

Interfejs nie pokazuje poprawnych nazw tylko np.: LBL_EVENTS
![lbl](https://user-images.githubusercontent.com/15181660/155967672-1d8a369f-9c36-4d72-9d4c-56b8d0628282.png)

Problem rozwiązuje się jeśli w konfiguracji systemu ustawimy na "Tak" opcję "Pokaż wybór języka na stronie logowania"
![language_selection](https://user-images.githubusercontent.com/15181660/155969078-5ae8898a-40ac-4d7c-836d-8f6274638ad2.png)

Wówczas to samo okno kalendarza wygląda już poprawnie
![calendar](https://user-images.githubusercontent.com/15181660/155969688-dfa7ad8c-71dd-4d84-85d2-7300f1c21e62.png)

**Comment by mariuszkrzaczkowski** [comment]
załącz zrzut z ustawień użytkownika, sekcja  "Układ graficzny"
![image](https://user-images.githubusercontent.com/10198654/155972132-fd48df8f-817d-4d7f-b900-b4e2b6ce78df.png)
