### ISSUE TITLE
can't install it on my local server

### ISSUE THREAD

**Issue by toliano** [YetiForceCompany/YetiForceCRM#15743]
After the extraction to my local  sever directory. Then I tried installing it using the directory url "localhost/yeticrm/install" and all I could see was just a blank page and nothing more. I have tried it on both XAMPP and WAMP server with PHP version 7.3. Thanks

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/155294184-772d1987-23b2-47aa-8531-29caed861f75.jpg)
