### ISSUE TITLE
[bug] Batch selection or batch deletion bug

### ISSUE THREAD

**Issue by snmin** [YetiForceCompany/YetiForceCRM#15765]
There is a small bug. When the number of products exceeds 1000, it will become very embarrassing to delete all products. When selecting all products, it will prompt that the selection items cannot exceed 1000 items, and the single page display cannot exceed 100 items. So only 100 records can be deleted at a time.

**Comment by rskrzypczak** [comment]
There is no error here.
The maximum number of massively deleted records can be set in the configuration file.
https://github.com/YetiForceCompany/YetiForceCRM/blob/6db5d0ba6a121d5f8d5277d75982aa79744b4024/config/Performance.php#L56-L57
However, be aware that deleting a large number of records may take a long time, depending on your hardware and various limits set on the server, may result in inability to delete and errors.
