### ISSUE TITLE
Updateing from 4.4.0 to 5.0.0 --> SQL Error[bug] 

### ISSUE THREAD

**Issue by h2Entwicklung** [YetiForceCompany/YetiForceCRM#15782]
# 🐞 bug report
Hello all,
Thanks for the great project.

### ⁉️ Describe the bug

I try to upgrade a yetiforce installation from 4.3 to 6.3
The first step from 4.3.0 to 4.4.0 was great. it worked as expected. but when I try to upgrade to 5.0.0 I get the following SQL Error:

```SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'module' cannot be null The SQL being executed was: UPDATE `vtiger_crmentityrel` SET `module`=(SELECT `vtiger_crmentity`.`setype` FROM `vtiger_crmentity` WHERE `vtiger_crmentity`.`crmid`=vtiger_crmentityrel.crmid)```

When I fire up the SQL-Query in the database to select the data, which are coressponding to the Query I get an empty result.

### 🔥 How to trigger the error

![Update Error](https://user-images.githubusercontent.com/87967468/157417495-b62ef13f-61e0-4598-a2c0-6af5d855226a.gif)

### 👎 Actual Behavior

The Upgrade results in a SQL-error

### 👍 Expected Behavior

The upgrade works correct

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/157431387-90406bcb-0d1e-4309-82ee-2a7095bacc6b.jpg)
