### ISSUE TITLE
[BUG] Delete mail message

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1578]
![animation 51](https://cloud.githubusercontent.com/assets/1402355/8817415/80a4ba8a-304c-11e5-9d06-7401cbef3c2c.gif)

**Comment by mariuszkrzaczkowski** [comment]
This is not an error, the dafault folders are not set.
![mail](https://cloud.githubusercontent.com/assets/10198654/8901620/a67a7aae-344a-11e5-9650-5261569d957e.png)
