### ISSUE TITLE
[BUG] Mail - Label

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1579]
Dont wor'k label

![animation 52](https://cloud.githubusercontent.com/assets/1402355/8817484/36257e44-304d-11e5-9106-caf83fa59653.gif)

**Comment by paula-w** [comment]
What exactly are you reporting? What is not working? How should it work?

**Comment by waw555** [comment]
It does not change color when you select tags

**Comment by bpabiszczak** [comment]
It's not an error in fact. I don't know if you know, but this mechanism allows you to mark several labels for one mail, and the color you can see [in this skin] is the last color on the list. If you change your skin to the other one, then this email will be marked with different color dots [you' ll get how it works when you do that].
![test](https://cloud.githubusercontent.com/assets/10197525/8851806/ff74fc16-3151-11e5-971a-aa02cee55048.png)
