### ISSUE TITLE
Issue : Cron job returns error

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#15797]
I have setup cron job in centos 7 with following command

sh /www/wwwroot/default/crm/hasonjee/cron/cron.sh

when it runs log shows below error and cron is not running. 

PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /www/wwwroot/default/crm/hasonjee/vendor/yetiforce/yii2/db/Connection.php:723
Stack trace:
#0 /www/wwwroot/default/crm/hasonjee/vendor/yetiforce/yii2/db/Connection.php(723): PDO->__construct()
#1 /www/wwwroot/default/crm/hasonjee/app/Db.php(281): yii\db\Connection->createPdoInstance()
#2 /www/wwwroot/default/crm/hasonjee/vendor/yetiforce/yii2/db/Connection.php(638): App\Db->createPdoInstance()
#3 /www/wwwroot/default/crm/hasonjee/vendor/yetiforce/yii2/db/Connection.php(1063): yii\db\Connection->open()
#4 /www/wwwroot/default/crm/hasonjee/app/Utils/ConfReport.php(551): yii\db\Connection->getMasterPdo()
#5 /www/wwwroot/default/crm/hasonjee/app/Utils/ConfReport.php(503): App\Utils\ConfReport::init()
#6 /www/wwwroot/default/crm/hasonjee/app/Utils/ConfReport.php(489): App\Utils\ConfReport::getByType()
#7 /www/wwwroot/default/crm/hasonjee/app/Cron.php(145): App\Utils\ConfReport::getAll()
#8 /www/wwwroot/default/crm/hasonjee/app/Cron.php(92): in /www/wwwroot/default/crm/hasonjee/vendor/yetiforce/yii2/db/Connection.php on line 649
----------------------------------------------------------------------------
★[2022-03-20 13:22:01] Successful
----------------------------------------------------------------------------

please assist, what is wrong. my configuration is as below

Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
there is a problem in the database or in the connection to the database on the cli layer
