### ISSUE TITLE
Improve style - Border to a PDF

### ISSUE THREAD

**Issue by sistemasnow** [YetiForceCompany/YetiForceCRM#15793]
Hi Yeti,

I am trying to generate a pdf file from Helpesk module with a sentence like this:

$(recordsList : HelpDesk|ticket_no,ticket_title,ticketstatus,attention||214)$

It runs but the style its so poor. I would like to improve the style options like a grid, as if it was a table with border. I don´t know if is possible to do it. Perhaps, modifiying some php or similar...

Can you help me?

**Comment by mariuszkrzaczkowski** [comment]
Set params table=border
```
$(recordsList : $moduleName|$columns|$conditions|$viewIdOrName|$limit|$maxLength|$params)$
```
Example
$(recordsList : HelpDesk|ticket_no,ticket_title,ticketstatus,attention||214|||table=border)$
