### ISSUE TITLE
[bug] Non posso applicare modifiche ai profili YETIFORCE

### ISSUE THREAD

**Issue by alex-nap** [YetiForceCompany/YetiForceCRM#15809]
Buongiorno,
all'improvviso non riesco più a modificare i profili su Yetiforce.
Fino a qualche giornoo fa riuscivo a modificarli, adesso non riesco più ad attivare o disattivare nuove funzioni. Dopo il salvataggio, ritorna tutto come prima.
Esempio: provo ad attivare tutte le opzioni "Notifica"
![image](https://user-images.githubusercontent.com/102237839/159722404-12f6cf45-2cec-4584-824a-a924cf5bf3e9.png)

Dopo il salvataggio
![image](https://user-images.githubusercontent.com/102237839/159722617-f8d2974a-4e96-440b-9a7c-d56dcdfb7b64.png)

resta tutto bloccato.

Cosa posso fare?

**Comment by alex-nap** [comment]
il post di assistenza è riferito al Team @yetiforce-security

**Comment by davide-alghi** [comment]
Hi Alex, please post in English.
About your problem: "profile changes are not saved", try to follow these steps https://github.com/YetiForceCompany/YetiForceCRM/issues/12939#issuecomment-617745574

**run a backup first**

**Comment by mariuszkrzaczkowski** [comment]
Only this will work when the server has the correct configuration, because if it has too small limits, it means that the web server cuts the data

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/159858375-c155a6dd-a724-4f7d-9410-5a92c0467a07.jpg)
