### ISSUE TITLE
[BUG] Mail - Template

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1580]
Template Don't work
![animation 53](https://cloud.githubusercontent.com/assets/1402355/8817505/7b7c6c78-304d-11e5-9c45-7187f8f844c5.gif)

**Comment by bpabiszczak** [comment]
The recording does not imply if there are any templates in the system [because if they are not there then on what basis should they be presented]  and what types of templates  there are [certain templates are visible from different places].

**Comment by waw555** [comment]
All is well, I checked, and it works.
It is necessary to specify the module mail templates Mail
