### ISSUE TITLE
[Fatal Error] Mail - Contacts

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1581]
Contacts do not appear in the mail !!!!!!!!!!!!!!! ???????????

Imports, too, only from the file, the system can not be imported ?????????????

I think this is a very big mistake, you must synchronize contacts
![animation 54](https://cloud.githubusercontent.com/assets/1402355/8817561/054a2c92-304e-11e5-9d8f-7558acdbd46c.gif)

**Comment by bpabiszczak** [comment]
We don't use the address book in roundcube. CRON has to be running in order to find contacts while creating an email, because it generates contacts for roundcube in the field that suggests mails.
