### ISSUE TITLE
[bug] User can delete widgets

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#15817]
Admin creates widgets for certain Role and set them not mandatory. Role profile is set so cannot  create widgets.
Despite that, user can delete widget created by Admin. Role assigned to multiple users, so it create confusion.
Threatening it as a bug, as here admin created 30 widgets what should be seen by multiple users and one user deleted 10 of them, removing access to widgets for other users

**Comment by mariuszkrzaczkowski** [comment]
I tried to find a bug on gitdev and can't see
removed widgets are added to "Predefined widgets" they do not disappear from the system.
Include more information, screenshots, examples of what watergets, etc.
