### ISSUE TITLE
[bug] Contact Assigned to Group takes all users of group while sending Email

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#15838]
We have configured Email Template to send Birthday Emails daily. In Email Footer we have included First Name and Last Name of user based on assigned to id. Problem is when contact is assigned to group then it includes all names of users of that group in email.

**Email Template Screenshot**
![image](https://user-images.githubusercontent.com/12723595/161024076-7f29e3ef-c883-422d-8d18-3f7e0ce191e9.png)

Email sent as below output is highlighted
![Screenshot 2022-03-31 145621](https://user-images.githubusercontent.com/12723595/161024124-10513daa-7abe-4266-b6b3-b5657489a906.png)

🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅-->

# 🐞 bug report

### ⁉️ Describe the bug
System should not include all users from the group instead should provide Only Group Name Value or only first user of group.

### 🔥 How to trigger the error

- [No ] I confirm that I tested it at https://gitstable.yetiforce.com
- [No ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

**In Email Template can we set IF Condition and get Group Name**

Regards
Jeevan Pendhari

**Comment by rskrzypczak** [comment]
This is not a bug. You should use _"$(record : assigned_user_id)$"_
