### ISSUE TITLE
[BUG] Tickets

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1584]
![animation 57](https://cloud.githubusercontent.com/assets/1402355/8817756/dc6712ba-3050-11e5-8837-a781d50d4d94.gif)

**Comment by rskrzypczak** [comment]
This error doesn't exist in the current system version.
https://gitdeveloper.yetiforce.com

**Comment by waw555** [comment]
See


![animation 58](https://cloud.githubusercontent.com/assets/1402355/8821933/cf8e8378-307a-11e5-88fd-6e71065a8d82.gif)

**Comment by bpabiszczak** [comment]
Please clear cache and check again.

**Comment by bpabiszczak** [comment]
What screen recording software do you use? We'll start using it too, to make it easier.

**Comment by waw555** [comment]
ScreenToGif

**Comment by waw555** [comment]
It seems the reason for remote field ...

![animation 59](https://cloud.githubusercontent.com/assets/1402355/8824436/049e0840-308f-11e5-820d-b0a37f06e912.gif)
