### ISSUE TITLE
[Discussion] mass mailings

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1586]
In vTiger we use Emailmaker a lot to send emails out to filtered lists of contacts.
I can't find a proper way to do this in Yeti. Sending a mass mail exposes all email addresses to everyone (on the fix list for 2.2) and I see a campaign option for direct mail but no way to add contact lists to this.

How are people doing this and any suggestions how to improve and send announcements and newsletters etc from Yeti.

**Comment by reeid** [comment]
Mass mailing (don't read SPAM) is a crucial factor for marketing communication but not only. There is many of scenarios what need well designed mailing engine in system core.
Exposing all emails in mass correspondence should be threatened as a major bug, as it is shows weakness, not application, but organization - who from Customer point of view is not working in line with professional standards.
If fix is not very difficult I would suggest to smash it on 2.1 platform

**Comment by bpabiszczak** [comment]
The mass mailing functionality will be introduced in version 2.2 or 2.3. Until then you have to deal with the available ones.

**Comment by echemik** [comment]
For me also exposing all emails in mass correspondence should be threatened as a major bug

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1478
