### ISSUE TITLE
how to import language packages?

### ISSUE THREAD

**Issue by wildfox81** [YetiForceCompany/YetiForceCRM#1589]
Dear All,
How can I export then import language packages...

**Comment by bpabiszczak** [comment]
Export: https://gitdeveloper.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=10&fieldid=53
Import: https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8 [on our version we disable this option].
