### ISSUE TITLE
[bug] Duplicate Option not showing for custom added module

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#15912]
Hi,

I have added custom module and here list filter does not show option to duplicate

![image](https://user-images.githubusercontent.com/12723595/162582056-9a29350d-38fb-456c-a5d8-ecd47778f1d0.png)

what can be wrong ?

please assist

regards
Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/162674268-df7ae1ff-b0ea-4f44-a4b8-d4b2de906fb5.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Attach the missing information, and:
- attach a profile preview for this user who does not have access to the mirror action with tool permissions shown

**Comment by JEEVAN28** [comment]
Issue was resolved with Menu Configuration where only All was selected hence other items in list was ignored.
