### ISSUE TITLE
[PL] Import plików vCard i iCal

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#1591]
W mojej opinii import plików vCard powinien być możliwy tylko w module Kontaktów a rozszerzenie iCal powinno być dostępne tylko w module Kalendarza, przy czym format CSV powinien być dostępny wszędzie.

**Comment by MaciejStencel** [comment]
Poprawiono. Dodano również filtrację akceptowanych plików w okienku. Widać tylko foldery i akceptowany format plików, np. wybierając plik do importu z modułu Kontakty widać foldery i pliki o rozszerzeniu CSV i VCF.
