### ISSUE TITLE
Chat - indicator and history

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1592]
Hi, i was thinking about Chat in YF. Very user friendly will be notification about new message on chat (blinking icon and maybe number, like calendar reminder in gitdeveloper version) - currently we have only sound but if my PC is muted I need to check "if someone write to me".

Other great future will be chat history, where we can check previous messages.

Good example for chat is Google Hangouts.

**Comment by bpabiszczak** [comment]
The chat, as is it now, is "redundant" and at the same time "not integrated enough", that's why it will be written from scratch at some point, and the current module will be completely removed.

**Comment by florek41** [comment]
OK, any target date ?

**Comment by bpabiszczak** [comment]
2.4 maybe.

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
