### ISSUE TITLE
[Docker] ...

### ISSUE THREAD

**Issue by kseibi** [YetiForceCompany/YetiForceCRM#15925]
# 🐞 bug report

### ⁉️ Describe the bug

I migrated my CRM to a new server and configured it according to yetiforce server requirements, 

But this is an issue that I didn't face on the old server, is during generating and downloading pdf files from records, the CRM pages just keep loading waiting for a response, and start working right after the download finishes,

### 👎 Actual Behavior

CRM not functioning during download of record generated pdf files

### 👍 Expected Behavior

CRM working while download happens in the background

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/162904362-18d64446-3fdc-437d-91eb-23fa187fab89.jpg)
