### ISSUE TITLE
[bug] Limited access user - unable to trigger workflow

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#15945]
Limited access user
Custom advanced module
Products module  active
Services module active
User have full access to own services
Workflow should trigger on "Modified time" change
User changing value in line item (service), record Modified time has changed
Workflow not triggering, log shows:
2022-04-15 06:59:47.4735 [error][NoPermitted] - No permissions to the module: Products
 - 0 include/main/WebUI.php (250)  >>  App\Log->error('No permissions to the module: Products','NoPermitted')
 - 1 include/main/WebUI.php (185)  >>  Vtiger_WebUI->triggerCheckPermission()
 - 2 index.php (28)  >>  Vtiger_WebUI->process()
2022-04-15 06:59:47.477 [error] - ERR_NOT_ACCESSIBLE

**Comment by mariuszkrzaczkowski** [comment]
attach more information and full CRM logs
![github](https://user-images.githubusercontent.com/10198654/163526625-16cb790d-bd82-4fc2-ba72-f2333eb363db.jpg)

**Comment by rskrzypczak** [comment]
Due to inactivity, the issue has been closed.
