### ISSUE TITLE
[Improvements in version 2.1] Numbers with comma

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1596]
Please add the function to be able to use a point and comma in the amounts

https://github.com/swarnat/VtigerCRM-Tools

![comma](https://cloud.githubusercontent.com/assets/1402355/8848382/57e4fc0e-3150-11e5-8ef1-988ac0f03fda.JPG)

**Comment by bpabiszczak** [comment]
This functionality was added to the new module with products that will be published and ready for testing next week.
