### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by AlexSq20** [YetiForceCompany/YetiForceCRM#15971]
# 🐞 bug report

### ⁉️ Describe the bug
I am having an issue with setting up my YetiForce CRM.
I have installed the latest version and am running an apache2 server.
Port Forwarding is done and my server is accessible from the outside.
But when I go to my public IP from a device from outside my network it just goes to the apache landing page.
It works perfectly fine when going to my local ip address from inside the network.

### 🔥 How to trigger the error

1. Go to 'your local ip address the server is hosted on'
2. see its live on local network.
3. disconnect from the internet and reconnect to another network or use cellular data.
4. See the apache2 landing page and that you cant go to yetiforce/app or yetiforce/index.php

### 👎 Actual Behavior

Apache landing page

### 👍 Expected Behavior

Ability to access yetiforce from the internet. 

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | latest
| Web server (name and version)     Apache  |  latest              |
| PHP                             7.2   |
| Browser (name and version)       Various current versions browsers|
| Operating System (name and version) Ubuntu |  18.04              |
| Database (name and version)     mariadb    |    latest            |

**Comment by rskrzypczak** [comment]
The reported error does not apply to the YetiForce application, but the server configuration, so I'm closing it.
https://github.com/YetiForceCompany/YetiForceCRM/discussions/15965
