### ISSUE TITLE
PDF - VAT

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#1597]
Istnieje problem z wydrukiem tabeli jeżeli chodzi o stawkę VAT. Np w ofertach. 
Używam dwóch stawek - w zależności od rodzaju usługi - lub towaru - w podatkach mam aktywne pozycje 8 i 23 % - niestety na wydrukach mam  cały czas 31 % - nie ważne jaki jest wybrany :) 

Ogólnie przy ofertowaniu używam podatku indywidualnego.

Czy mogę prosić po pomoc w poprawce  funkcji pliku "replace Table...." ?

**Comment by bpabiszczak** [comment]
Problem zapewne stanowi to, że na samym produkcie/usłudze wprowadził Pan
dwie stawki podatku a system jest oparty na Vtiger a on domyślnie sumuje
stawki VAT. W przyszłości ma być to zmienione, proszę sprawdzić, czy to
jest przyczyną. 

>

**Comment by zimart** [comment]
Niestety potrzebuję takiej funkcjonalości... :(  Posiadam działającą wersję pliku do vtiger - niestety brakuje którejś funkcji dopisanej obecnie - lub zmienionej...   - starałem sie porównać pliki - ale niestety nie znalazłem problemu - ale tak sytuacja wyglada ,że muszę mieć możliwość wyboru stawki na poszczególnych produktach.. czy mogę liczyć na pomoc w tej kwestii ? Ewentualnie mogę gdzieś podesłać mój obecny - działajacy plik..

**Comment by bpabiszczak** [comment]
Niestety nie rozumiem: 
1. Czy błąd jest spowodowany tym co powiedziałem? 
2. Niezależnie od wszystkiego, będąc na dokumencie możemy zmienić stawkę na dowolną inną, nawet jak produkt ma 23% stawki podatku, to można sobie zmienić na 0, 8% czy dowolną inną wartość.

**Comment by zimart** [comment]
Przy edycji produktu - po zaznaczeniu jednej mozliwej stawki VAT - wydruk jest ok.. Natomiast przy zaznaczeniu przy tym produkcie dwóch możliwości stawki VATU - na wydruku sumuje - czy mam 31%  - bez względu na to jaką stawkę mam wybraną. Kwestia jest w sumowaniu stawek VAT - przy generowaniu pliku pdf. Niestety nie widzę możliwości wpisywania stawki z ręki - i powiem szczerze , że nie było by to wygodne... - rzecz w tym aby pobrać stawkę VAT przypisana do danej pozycji i wydrukować ją na dokumencie.Tak jak pisałem posiadam przerobioną wersje do vtigera - i tam wszytko jest OK.

**Comment by bpabiszczak** [comment]
Tak jak pisałem. System domyślnie sumuje stawki. W wersji 2.2 będzie można to konfigurować. Jeżeli potrzebujesz mieć rozwiązanie na już to proponuje samemu wprowadzić niezbędne ulepszenia lub zlecić to firmie zewnętrznej.

**Comment by zimart** [comment]
czy pozostaje czekać... - chociaż wydaje mi się że to nie jest kwestia systemu jako takiego :) tylko modułu pdf. Powalczę w takim razie - a jeżeli sie nie uda to poczekam.

**Comment by bpabiszczak** [comment]
Na chwilę obecną nie bardzo wiem jak Ci pomóc bo zbyt mało szczegółowo to opisałeś. Musisz opisać to jeszcze raz [krok po kroku] tak abym wiedział jak odtworzyć błąd. Zerknij na inne zgłoszenia, nie dość że dodają opis błędu krok po kroku to również dodają filmiki gdzie pokazują. 

Twój problem jest złożony, tzn. że zależy od wielu innych rzeczy i dlatego potrzebuje więcej szczegółów.

**Comment by zimart** [comment]
Rozumiem... w wersji developerskiej jest błąd - brak możliwości wpisania wartości VAT - przy założeniu podatku indywidualnego przy dodawaniu produktu do oferty . W wersi stabilnej 2.0 jest ok. Dołącze screeny.

**Comment by zimart** [comment]
Widzę małe zmiany już, jeżeli chodzi o mój problem.
Niestety jest jeszcze jeden błąd. Mianowicie, nawet przy jednej stawce VAT przy danym produkcie - po zapisaniu oferty nie jest możliwa edycja - powiedzmy że się pomyliłem :) w żaden sposób. 
Ps.. czy da się przywrócić przycisk "podatek" na lewą stronę :) jak było wcześniej - przy okazji - i szerokości kolumn też były chyba bardziej przejrzyste - szersza z nazwą artykułu.

**Comment by florek41** [comment]
spróbuj tym https://screentogif.codeplex.com/

**Comment by bpabiszczak** [comment]
Aby utrudnić jeszcze życie użytkownikom, to w wersji 2.2 wszystkie moduły z produktami będą oparte o nowy mechanizm... całkowicie nowy, i to dotyczy również wydruków.

**Comment by florek41** [comment]
Osobiście - jeśli tylko będzie to łatwiejsze / bardziej logiczne / intuicyjne / poprawione / cokolwiek - nie widzę problemu z takimi utrudnieniami.

**Comment by bpabiszczak** [comment]
Ze względu na to, że wydruki w nowej wersji [2.2] zostaną przebudowane, proponuję zamknąć zgłoszenie i wrócić do niego przy opublikowaniu wersji 2.2 o ile błąd nadal będzie istniał.

**Comment by agilisgmbh** [comment]
Why not speaking in english!?
Thought this is INTERNATIONAL forum, and maybe anyone else have same question/problem and want to know!??

**Comment by bpabiszczak** [comment]
We accept issues in Polish and English. The first post determines the language of the discussion.
