### ISSUE TITLE
Incorrect script username after upgrading to Yetiforce CRM 6.3 SecurityFix V8

### ISSUE THREAD

**Issue by krseguros** [YetiForceCompany/YetiForceCRM#15985]
Hello,

Please check if you can help me with this error that is presenting me the parameter "Incorrect Script username" after upgrading to Yetiforce CRM 6.3 SecurityFix V8 SecurityFix V8

Next, I show you capture before and after the update:

Before
![image](https://user-images.githubusercontent.com/96985476/165026858-31ddd616-5f2f-4463-85ae-77a11287e540.png)

Later
![image](https://user-images.githubusercontent.com/96985476/165026649-0c033c2c-3e40-41c5-bdb8-41880f516583.png)

**Comment by s2b-git** [comment]
Logs sometimes helps
