### ISSUE TITLE
[bug] #11956 still present - all picklist-roles assigment are lost, and all picklists are greyed-out 

### ISSUE THREAD

**Issue by azorlone** [YetiForceCompany/YetiForceCRM#16001]
# 🐞 bug report

### ⁉️ Describe the bug

There is a dangerous bug in the Picklist "Assign to roles" menu: there is a procedure that RESETS ALL AND ANY assigments to picklists, making ANY PICKLIST that can be role-assigned unusable.

### 🔥 How to trigger the error

1. Go to Fields - Picklist
2. Select a module and a picklist that has the "Values assigned to a Role" label (as an example: Tickets > Status)
3. Click on the "Assign Roles" button.
4. In the modal, do not add anything in the "Item value" field, and hit SAVE.

I recorded a video using your GitStable environment: https://vimeo.com/704077357 

### 👎 Actual Behavior

Boom - any and all assigments are lost in ALL MODULES, and ALL FIELDS.

### 👍 Expected Behavior

One of either of the following behaviours should occur:

- It "resets" the assigments for that specific Field of that specific module
- It "ignores" the operation, as there are no values to "ADD" to the selected role in that Field/Module

### 👷 Testing

- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com
_... and with disastrous effects, I should say..._

### 📷 Screenshot of configuration

Not necessary, as it happens very easily on your GitStable and GitDeveloper releases.

### 🌍 Your Environment

Same as above

**Comment by rskrzypczak** [comment]
Fix: https://github.com/YetiForceCompany/YetiForceCRM/commit/e4ee747db344139cf4a91febd5e745ed49f10fba
