### ISSUE TITLE
when i try to integrate yetiforce portal to the crm i found "Invalid api type" error 

### ISSUE THREAD

**Issue by kassimg12** [YetiForceCompany/YetiForceCRM#16019]
When I try to integrate yetiforce portal to the CRM I found an "Invalid API type" error. Could anyone help, please?

operating system: ubuntu 20.04
Apache 2
php8.1
CRM Version: 6.3
API type: standard Webservice
portal version: 2.63

Thank you!

**Comment by mariuszkrzaczkowski** [comment]
with php 8.1 will not work properly, check the error logs

**Comment by kassimg12** [comment]
Thank you for responding. In the log file i couldnt see any php version related issue. but it says "invalid api type". i assume it mandatory to have webservice premium to use the portal. i was hoping to tast the portal with webservice standart may be with minimal features of the portal.

Here is the api log message on portalfolder/catch/logs/
--------------------------------------------------  2022-04-30 15:05:21  --------------------------------------------------
Trace: 
#0 app/Log/AbstractBase.php:40  >>  App\Log\Api->display([array,array],'info')
#1 app/Log.php:108  >>  App\Log\AbstractBase->log([array,array],'info')
#2 app/Log.php:90  >>  App\Log->log([array,array],'info','Api')
#3 app/Api.php:247  >>  App\Log->info([array,array],'Api')
#4 modules/Install/Model/Install.php:49  >>  App\Api->call('Install','{"data":"Install Wizard"}','PUT')
#5 modules/Install/Action/Install.php:46  >>  YF\Modules\Install\Model\Install->check()
#6 app/WebUI.php:72  >>  YF\Modules\Install\Action\Install->process()
#7 index.php:31  >>  App\WebUI->process()
Method: [PUT] Install
Headers: Array
(
    [User-Agent] => YetiForce Portal | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36
    [X-Encrypted] => 0
    [X-Api-Key] => xxxxxxxxxxxxxxxxxxxxxx
    [Content-Type] => application/json
    [Accept] => application/json
)

RawBody: 
Array
(
    [data] => Install Wizard
)

Body: {"data":"Install Wizard"}

Status: 404
Reason phrase: **Invalid api type**
Time: 0.02 sec.
Headers: Array
(
    [Date] => Sat, 30 Apr 2022 15:05:22 GMT
    [Server] => Apache
    [Access-Control-Allow-Origin] => *
    [Access-Control-Allow-Methods] => 
    [Access-Control-Allow-Headers] => Origin, X-Requested-With, Content-Type, Accept, Authorization, x-api-key, x-encrypted, x-token
    [Encrypted] => 0
    [Content-disposition] => attachment; filename="api.json"
    [Transfer-Encoding] => chunked
    [Content-Type] => application/json
)

RawBody: 
{"status":0,"error":{"message":"Invalid api type","code":404,"file":"api\/webservice\/Controller.php","line":90,"backtrace":"#0 api\/webservice\/Controller.php (90)  >>  Api\\Core\\Exception->__construct('Invalid api type',404)\n#1 webservice.php (23)  >>  Api\\Controller->preProcess()"}}
Body: Array
(
    [status] => 0
    [error] => Array
        (
            [message] => **Invalid api type**
            [code] => 404
            [file] => api/webservice/Controller.php
            [line] => 90
            [backtrace] => #0 api/webservice/Controller.php (90)  >>  Api\Core\Exception->__construct('Invalid api type',404)
#1 webservice.php (23)  >>  Api\Controller->preProcess()
        )

)


REQUEST = Array
(
    [mode] => Step3
    [lang] => en-US
    [apiUrl] => https://crm.domainname.com/webservice/
    [apiKey] => xxxxxxxxxxxxxxxxxxxxxxxxxxx
    [serverName] => standard
    [serverPass] => XXXXXXXX
    [module] => Install
    [action] => Install
)

**Comment by kassimg12** [comment]
Additionally, I tested php7.4 and php8.0. The result is the same
if it helps this is an error message I found in the portal debug console>raw response section.

{"status":0,"error":{"message":"Invalid api type","code":404,"file":"api\/webservice\/Controller.php","line":90,"backtrace":"#0 api\/webservice\/Controller.php (90)  >>  Api\\Core\\Exception->__construct('Invalid api type',404)\n#1 webservice.php (23)  >>  Api\\Controller->preProcess()"}}

<img width="1397" alt="Screen Shot 2022-05-01 at 10 32 44 AM" src="https://user-images.githubusercontent.com/65815933/166136720-50b955e0-b098-4cfc-96df-dd1311503fbd.png">

**Comment by kassimg12** [comment]
Additionally, I tested php7.4 and php8.0. The result is the same
if it helps this is an error message I found in the portal debug console>raw response section.

{"status":0,"error":{"message":"Invalid api type","code":404,"file":"api\/webservice\/Controller.php","line":90,"backtrace":"#0 api\/webservice\/Controller.php (90)  >>  Api\\Core\\Exception->__construct('Invalid api type',404)\n#1 webservice.php (23)  >>  Api\\Controller->preProcess()"}}

<img width="1397" alt="Screen Shot 2022-05-01 at 10 32 44 AM" src="https://user-images.githubusercontent.com/65815933/166136720-50b955e0-b098-4cfc-96df-dd1311503fbd.png">

**Comment by mariuszkrzaczkowski** [comment]
This is a server side problem with CRM
![github](https://user-images.githubusercontent.com/10198654/166194257-f96c4831-e907-4800-8f42-88eb3a8cbf61.jpg)

**Comment by kassimg12** [comment]
# 🐞 bug report

### ⁉️ Describe the bug



**>> When I try to integrate yetiforce portal to the CRM I found an "Invalid API type" error. It failed to connect to the CRM which is why I consider it as a bug.**






### 🔥 How to trigger the error



**>> The error message is triggered by trying to install the portal in the portal installation wizard.**

**>> Steps to reproduce the behavior:

1. Go to 'portal website'
2. Click on 'install'
3. Fill all required fields of CRM url address, api key, name of the web service, and password
4. See the error message “Invalid API type”**

### 👎 Actual Behavior



- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration



<img width="1397" alt="Screen Shot 2022-05-03 at 9 52 31 PM" src="https://user-images.githubusercontent.com/65815933/166523133-a65200fa-f51b-44fe-a1ae-8adf68a7bae2.png">




### 📝 PHP/Apache/Nginx/Browser/CRM Logs



### 🌍 Your Environment




| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |**6.3**
| Web server (name and version)       |   **apache2  2.4.41**             |
| PHP                                 |   **7.4  both for CRM and portal**           |
| Browser (name and version)          |      **Google Chrome**          |
| Operating System (name and version) |   **Cloud server Ubuntu 20.04**             |
| Database (name and version)         |     **mysql  Ver 8.0.28-0**           |
| Service Pack version                |                |

### ❓ Additional context

Add any other context about the problem here.


**I hope the above is adequate information for this specific context. I tried to provide all information as much as i could**

### ❗️ Inform the community if you solve the problem



**Sure. I will do that**

**Comment by mariuszkrzaczkowski** [comment]
attach a set of logs from both servers (CRM + Portal)

**Comment by kassimg12** [comment]
here are the log files generated by the crm
[webserviceErrors.log](https://github.com/YetiForceCompany/YetiForceCRM/files/8618383/webserviceErrors.log)
[webserviceDebug.log](https://github.com/YetiForceCompany/YetiForceCRM/files/8618384/webserviceDebug.log)

here are the log files generated by the portal
[api.log](https://github.com/YetiForceCompany/YetiForceCRM/files/8618385/api.log)

**Comment by mariuszkrzaczkowski** [comment]
attach a screenshot of "Software configuration > Integration > Web service - Applications"

**Comment by kassimg12** [comment]
here is the screenshot of the web service configuration page. the highlighted text is my domain name.
![webservice](https://user-images.githubusercontent.com/65815933/166686535-534a90e0-2836-4a14-b7a7-e9efe9e2eadb.jpg)

here is the screenshot of the web service configuration detail page. the highlighted text is again my domain name.
![webservice detail](https://user-images.githubusercontent.com/65815933/166687047-b039effc-709d-4e98-b46f-ea11619f75c2.jpg)

Thank you!

**Comment by mariuszkrzaczkowski** [comment]
You are using "Webservice Standard" with this portal not working, you must have "Webservice Premium"
webserviceErrors.log
```
code: 404 | message: Invalid api type
```

**Comment by kassimg12** [comment]
Hello, webservice Premium is a paid version. I need to try it with a minimal or standard version if possible. I found the portal code as open-source but yet I couldn't install it.

**Comment by salvofan** [comment]
Did you find any solution for this?

**Comment by kassimg12** [comment]
No. i think it requires Webservice Premium which I could not purchase right
now. Thank you for checking.
