### ISSUE TITLE
[improvement] Creating the Module

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1601]
When you create a module, and add the field with data from another module, you must add the ability to select the field with data from another module, the choice which the other selected fields with the data from another module, will belong to this field.

Example:

I've created a module and created three data fields of the following modules

Contacts
Contracting parties
Projects

If I could assign Accounts module by default, selecting projects and contacts, I have seen only Projects and Contacts associated with the selected Contractor

Example:

I created

Contact 1 - 1 Contractor - Project 1
Contact 2 - Counterparty 2 - Project 2
Track 3 - Counterparty 3 - Project 3

When you create a new entry in the module by the Counterparty 1, and then selecting Contacts and references, I have to see only the contacts 1 and Project 1, now I see all the contacts and all projects

This function must necessarily be included in future versions

I think it will be useful not only for me.

![animation 62](https://cloud.githubusercontent.com/assets/1402355/8869041/d309d014-31f8-11e5-8ef8-f6b89e2d881a.gif)

**Comment by bpabiszczak** [comment]
It's not that easy. There are situations when data filtering is good, and there are other situations when it's bad. For example, when we create sales opportunities and then assign them to Account A, then should the possibility of linking contacts in sales opportunities be only limited to Account A's contacts? And what if this Account is served by an external company or he's got a central? 

It would be great to control it, but at the moment it has a low priority.

**Comment by nikdejan** [comment]
+1 to data filtering. It's very useful and it needs to be included, but also it need to be optional.

**Comment by bpabiszczak** [comment]
Some time ago we added a mechanism to automatically link fields, for example when you choose sales opportunity, and next to that you got an account, then the system will automatically fill that field. 

Check if that functionality is sufficient for you.
