### ISSUE TITLE
[PL] Dodawanie linków akcji w widokach DETAIL/LISTVIEW

### ISSUE THREAD

**Issue by bwiatrni** [YetiForceCompany/YetiForceCRM#1603]
Witam,
tworzę moduł pod VT który ma być również kompatybilny z YF. Moduł instaluje się w całości niestety problem pojawia się z linkami akcji DETAILVIEW/LISTVIEW które instalują się w bazie w tabeli vtiger_links natomiast działaja tylko częściowo. Kod z postinstalla:

// pierwszy link - zainstalowany i działa
$moduleInstance = Vtiger_Module::getInstance($moduleData['name']);
$moduleInstance->addLink('DETAILVIEWBASIC', 'Download XML', 'index.php?module=EDIXMLExport&action=DownloadXML&record=$RECORD$&relmodule='.$moduleData['name']);

// praktycznie taki sam - NIE DZIAŁA (nie ma nigdzie przycisku w detailview - w bazie vtiger_links jest zapisany)
$moduleInstance->addLink('DETAILVIEWBASIC', 'Export XML', 'index.php?module=EDIXMLExport&view=ExportXMLRemote&record=$RECORD$&relmodule='.$moduleData['name']);

// LISTVIEW - nie działa (nie ma go w dropdown akcji/narzedzi listview natomiast w bazie jest rekord)
$moduleInstance->addLink('LISTVIEW', 'Download Specification XML', 'index.php?module=EDIXMLExport&action=DownloadXMLSpecification&record=$RECORD$&relmodule='.$moduleData['name']);

// ten natomiast działa poprawnie i można go znaleźć w akcjach LISTVIEW
$moduleInstance->addLink('LISTVIEW', 'Import Remote XML', 'modules/EDIXMLExport/crons/importer.php?relmodule='.$moduleData['name']);

**Comment by bpabiszczak** [comment]
Tworzenie jednego modułu dla dwóch różnych systemów jest nieprawidłowe. Te systemy się znacznie od siebie różnią. W przeciwieństwie do Vtiger, u nas wszystkie przyciski są kontrolowane przez profile [a różnica pomiędzy działającym i niedziałającym zapisem jest sposób wywołania [akcja/widok]. 

Przypuszczam, że nie działa, ponieważ tak jak opisuje to powyżej, narzędzie należy dodać do profili, aby można było użytkownikowi nadać uprawnienia do tego narzędzia.

**Comment by bwiatrni** [comment]
Dziękuję za odpowiedź. To jak Pan może wyjaśnić dlaczego jeden link zadziałał drugi nie? Żaden nie był konfigurowany w profilach. Wygląda to raczej na jakiś bug. W przypadku DetailView potrzebuje dwa linki (dodały się dwa widoczny jest tylko jeden). Czy jest Pan w stanie dodać dwa do menu linków DetailView w YF?

**Comment by bwiatrni** [comment]
Sprawdziłem dokładnie bazę, jednak nie wszystkie zostały dodane. Używając metody $moduleInstance->addLink niektóre się nie dodają zależnie od modułu (w Kontrahencie dodał się tylko Download XML), w Fakturach żaden. Po zamianie na SQL myślę że będzie działać więc problem rozwiązany tak czy inaczej na pewno nie działa funkcja addLink poprawnie -  a przynajmniej logicznie.

**Comment by mariuszkrzaczkowski** [comment]
Sprawdziłem i wszystko poprawnie dodaje do systemu, poniżej przykładowe zrzuty.
![1](https://cloud.githubusercontent.com/assets/10198654/8904444/aade1e42-345f-11e5-81d3-2caa978e4e49.png)
![2](https://cloud.githubusercontent.com/assets/10198654/8904442/aadc0a76-345f-11e5-88f4-25919397dbb1.png)
![3](https://cloud.githubusercontent.com/assets/10198654/8904443/aadd23ca-345f-11e5-8699-05ff6318695a.png)

**Comment by bpabiszczak** [comment]
Wcześnie pomyliłem się, w sposób jaki dodajesz nie ma nic wspólnego z profilami, jednakże tak jak pisałem powyżej, prawidłowo powinno to być dodane do profili i kontrolowane uprawnieniami kto ma uprawnienia do eksportu XML a kto nie. 

Niestety coś takiego można zrobić tylko poprzez modyfikacje silnika.

**Comment by bwiatrni** [comment]
Przykładowe zrzuty po instalacji modułu
![yt1](https://cloud.githubusercontent.com/assets/5813880/8904641/947427e4-3461-11e5-8a99-baba067bbf6b.png)
![yt2](https://cloud.githubusercontent.com/assets/5813880/8904642/984caff8-3461-11e5-9a30-067cdfc8c117.png)

kod postinstall
```php
// linki dla wszystkich modułów entity
$modulesResult = $adb->pquery("SELECT * FROM `vtiger_tab` WHERE `vtiger_tab`.`isentitytype` = ?", array(1));
			$entityModules = array();

			if ($adb->num_rows($modulesResult) > 0) {
				while ($entityModule = $adb->fetchByAssoc($modulesResult)) {
					$entityModules[] = $entityModule;
				}
			} 

			if (count($entityModules)) {
				file_put_contents('install.log', print_r($entityModules,1), FILE_APPEND);
				foreach ($entityModules as $keyModule => $moduleData) {
					$moduleInstance = Vtiger_Module::getInstance($moduleData['name']);
					$moduleInstance->addLink('DETAILVIEWBASIC', 'Download XML', 'index.php?module=EDIXMLExport&action=DownloadXML&record=$RECORD$&relmodule='.$moduleData['name']);
					$moduleInstance->addLink('DETAILVIEWBASIC', 'Export XML', 'index.php?module=EDIXMLExport&view=ExportXMLRemote&record=$RECORD$&relmodule='.$moduleData['name']);
					$moduleInstance->addLink('LISTVIEW', 'Download Specification XML', 'index.php?module=EDIXMLExport&action=DownloadXMLSpecification&record=$RECORD$&relmodule='.$moduleData['name']);
					$moduleInstance->addLink('LISTVIEW', 'Import Remote XML', 'modules/EDIXMLExport/crons/importer.php?relmodule='.$moduleData['name']);
				}
			}
```

**Comment by bpabiszczak** [comment]
My sprawdziliśmy poprawność tworząc powiązania z pliku [ale przy użyciu vtliba]. Jeżeli mamy to sprawdzić w przypadku instalacji modułu to:
a) potrzebujemy taki moduł,
b) zrobimy to najwcześniej w przyszłym tygodniu.

**Comment by bwiatrni** [comment]
Dziękuję za pomoc. Na chwilę obecną rozwiązanie polegające na dodaniu linków za pomocą SQL a nie vtliba jest w zupełności wystarczające. Co do modułu produkcyjnej wersji wysłać nie mogę natomiast w wolnej chwili na przyszły tydzień podeślę coś na maila - generalnie chodzi jedynie o sprawdzenie kodu który załączyłem w postinstall w poprzednim komentarzu w dowolnym module w evencie postinstall.
