### ISSUE TITLE
Cannot login to Yetiforce test version

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1606]
Empty User and Password fields.

https://test.yetiforce.com/index.php

**Comment by bpabiszczak** [comment]
We'll fix it on Monday morning. Try admin / admin.

**Comment by florek41** [comment]
admin / admin works well !

**Comment by mariuszkrzaczkowski** [comment]
Fixed
https://test.yetiforce.com/
https://test.yetiforce.com/portal/
