### ISSUE TITLE
[question] Is something going to happen after disabling mandatory relation fields ?

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1608]
Ex. In quotes I don't need Requirement Cards or Opportunity is not mandatory in my case. Is something going to happen when I make them non mandatory in system ?

I know this is not good form business point of view, but this is only example.

**Comment by bpabiszczak** [comment]
At the moment unfortunately the answer is yes. In the future the interface will be separated and it will no longer be possible to do.
You can disable the fields you enumerated, nothing should happen after disabling them.

**Comment by florek41** [comment]
What do you mean by saying "yes" - it broke something or it's possible ? :)
And in the future disabling mandatory fields won't be possible ?

**Comment by bpabiszczak** [comment]
Tak, było do tego, że aktualnie system pozwala na usuwanie pól, których usuwać nie powinniśmy, co może skutkować zepsucie systemu, natomiast pola które wymieniłeś, że chcesz zmienić, nie powinny wpłynąć negatywnie na działanie systemu - sami je wielokrotnie wyłączamy]. 

Odnośnie przyszłości, to będą dwa panele, jeden administratora, drugi developera. Ten dotyczący administratora nie pozwoli na "wywalenie" systemu, ten developerski już tak.

**Comment by bpabiszczak** [comment]
Chyba do zamknięcia?
