### ISSUE TITLE
[bug] [PL/EN] The ticket number is incremented after answering it using the reply in the mail client

### ISSUE THREAD

**Issue by ciast** [YetiForceCompany/YetiForceCRM#16102]
# 🐞 bug report

### ⁉️ Describe the bug

[PL]
**CEL:** Każdy klient otrzymuje własną numerację zgłoszeń opartą o nazwę skróconą kontrahenta. Numer zgłoszenia resetowany co rok. Przykładowa numeracja:
H/TESTOWYKONTRAHENT/2022/3

Przy odpowiedzi na maila zgłoszeniowego treść maila powinna być zaczytywana do pierwotnego zgłoszenia, bez tworzenia nowego zgłoszenia.

**OPIS:**
W konfiguracji numeracji dla modułu zgłoszeń ustawiono jak poniżej:

![image](https://user-images.githubusercontent.com/42271888/170308736-605035f7-0c8d-4dcb-80ff-6e5075234a2d.png)

W chwili gdy zostanie wysłana wiadomość na maila zgłoszeniowego, tworzony jest prawidłowy nr zgłoszenia. 
W momencie gdy osoba zgłaszająca otrzyma powiadomienie mailowe z przypisanym numerem zgłoszenia i odpowie na nie to tworzony jest nowy ticket - nie następuje aktualizacja informacji w pierwotnym zgłoszeniu.

Przy ustawieniach domyślnych dla modułu zgłoszeń problem nie występuje (nr zgłoszenia przy odpowiadaniu nie inkrementuje się).
Zrzut poniżej dla maila zgłaszającego przypisanego do kontrahenta jak i bez przypisania do kontrahenta:

![image](https://user-images.githubusercontent.com/42271888/170311952-e0f31ebd-566e-41d3-b1ca-e196f1be85fa.png)

[EN]
** PURPOSE: ** Each client receives his own numbering of tickets based on the accounts short name. Ticket number reset every year. Sample ticket no:
H/TESTCONTRACTOR/2022/3

When replying to the notification e-mail, the content of the e-mail should be imported to the original ticket, without creating a new ticket.

**DESCRIPTION:**
In the numbering configuration for the ticket module, the following was set:

![image](https://user-images.githubusercontent.com/42271888/170308736-605035f7-0c8d-4dcb-80ff-6e5075234a2d.png)

When the message is sent to the e-mail, a valid ticket number is created.
When the reporting person receives an e-mail notification with an assigned ticket number and replies to it, a new ticket is created - the information in the original ticket is not updated.

With the default settings for the ticket module, the problem does not occur (the ticket number is not incremented when answering).
The screenshot below for the reporting e-mail assigned to the contractor and without being assigned to the contractor:

![image](https://user-images.githubusercontent.com/42271888/170311952-e0f31ebd-566e-41d3-b1ca-e196f1be85fa.png)

### 🌍 Your Environment
YetiForce CRM 6.3 SecurityFix v8

**Comment by s2b-git** [comment]
Noticed the same behavior here

**Comment by konadrian** [comment]
It was solved and a fix was added on the gitdeveloper version; here is a link for the commit https://github.com/YetiForceCompany/YetiForceCRM/commit/a278d185e1f0281da994519964a39e217b5b0ddd. You can apply these changes on your own or wait for version 6.4.
