### ISSUE TITLE
Using "Share with" in conditions - set as "currently logged in user"

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1610]
When creating filter, workflow, access validation etc we can select, as one of condition, *Share with users* but we cannot set value on *currently logged in user* - like for *Assigned to* field.

**Comment by bpabiszczak** [comment]
Unfortunately  I don't understand. Please describe it step by step in more detail, how it is and how you want it to be [you can do it in Polish if that's easier for you]

**Comment by florek41** [comment]
So, when I'd like to create filter which shows only assigned to, or shadred with *currently logged in user* records I cannot do this because in *Share with users* condition I can't select *currently logged in user* value.

Kiedy chcę stworzyć filtr który będzie wyświetlał tylko wpisy których właścicielem, lub które są współdzielone z *Aktualnie zalogowanym użytkownikiem* to nie mogę tego zrobić poniważ przy warunku *Współdzielone z użytkownikami* nie można wybrać *Aktualnie zalogowany użytkownik* (nie ma takiej możliwośći).

![share-condition-current-user](https://cloud.githubusercontent.com/assets/4824588/8896167/dc5015dc-33f3-11e5-89ea-11d70df5c1cf.jpg)
