### ISSUE TITLE
[bug] Filter sorting in Modules - relations not working

### ISSUE THREAD

**Issue by QVinto** [YetiForceCompany/YetiForceCRM#16117]
# 🐞 bug report

### ⁉️ Describe the bug
Filter sorting is working fine in module, but it is not sorting in other modules which you can manage via Modules - relations 

### 🔥 How to trigger the error
First create some record in time control for 1 company (account) with different days.
for example:
1. older date - 20.5.2022
2. older date - 19.5.2022
3. newer date - 22.5.2022
4. newer date - 23.5.2022

1. Go to 'System settings -> Labels, searching and labeling -> Filters - configuration -> Time control module'
2. Click on 'Sorting and set descending for Start Date '
![image](https://user-images.githubusercontent.com/4982986/170968673-3913b2a0-a72a-4a5f-b753-58b60a07435b.png)
3. Go to 'System settings -> Standard modules -> Modules - relations -> Accounts -> Check if you have set filter "All" in Time Control block'
![image](https://user-images.githubusercontent.com/4982986/170974277-4e58a6f5-0f24-467a-b030-50592674892f.png)
![image](https://user-images.githubusercontent.com/4982986/170974869-13aef4e2-cc8c-4096-a8d7-b57fcaadfb15.png)
4. Go to 'Home -> Company -> Time Control -> and set view to Record list'
![image](https://user-images.githubusercontent.com/4982986/170972483-cd5b3f30-b518-4862-a9e4-09bf344443ef.png)
5. Go to  'Home -> Companies and Contacts -> Accounts -> Pick the company with more records in time control -> Check Start Date sorting'
![image](https://user-images.githubusercontent.com/4982986/170973132-1c9afae3-bf4e-406e-ab0f-fc5473a3085d.png)

### 👎 Actual Behavior

Filter sorting in Modules - relations not working

### 👍 Expected Behavior

It should take all settings from filter and show the right filtering.

### 👷 Testing

- ✔️ I confirm that I tested it at https://gitstable.yetiforce.com
- ✔️ I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

gitdeveloper and git stable configurations

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/16118#issuecomment-1403166551
