### ISSUE TITLE
[Feature] Releated to Bug report #16117

### ISSUE THREAD

**Issue by QVinto** [YetiForceCompany/YetiForceCRM#16118]
# Feature report

### ⁉️ Describe the feature

When you are using Standards fields in Module - Relations, you are not able to set sorting function

### 👎 Actual Behavior

Not able to set sorting function automatically. You have to do it every time when you access the module in tabs
![image](https://user-images.githubusercontent.com/4982986/170978007-f782415c-4989-48f9-845a-60d9cd3b4d98.png)
![image](https://user-images.githubusercontent.com/4982986/170978239-24ccc78f-675c-4ebd-ae26-4dd80554f968.png)
![image](https://user-images.githubusercontent.com/4982986/170978397-9abe477e-893e-407c-bd6e-cdcf4f52b052.png)

### 👍 Expected Behavior

Create function for sorting in Modules - Relations when standard fields are added. Or you can make changes related to Bug report #16117 and we can create new filter with sorting which will be used when needed in Modules - Relations.

### 👷 Testing
No such function for Modules - Relations -> Standards fields

- ✔️ I confirm that I tested it at https://gitstable.yetiforce.com
- ✔️ I confirm that I tested it at https://gitdeveloper.yetiforce.com

**Comment by rskrzypczak** [comment]
Fixed in: https://github.com/YetiForceCompany/YetiForceCRM/commit/47a4e867a92d0146cce381ccd1cb11d28823ebfd
It will be available in version >6.4
