### ISSUE TITLE
Problem at installation moment!!!

### ISSUE THREAD

**Issue by JeRRimix** [YetiForceCompany/YetiForceCRM#1611]
I have the same problem at installation as it was on old version. See picture. Although many changes and fixed errors was made in last version but it remained. I have CentOS v. 6 + Nginx + Apache + PHP 5.6. I had tried to install with PHP as apache module, as Fast CGI and as PHP-FPM but it's problem in all cases. I  increased all timeout settings twice in PHP, in Apache and Nginx but the problem didn't solved. When I check MySQL database it's empty!!!   

![image](https://cloud.githubusercontent.com/assets/13039836/8893400/778df7b8-33a8-11e5-860f-bdaf4278020b.png)

**Comment by bpabiszczak** [comment]
This is server error. Check logs.

**Comment by JeRRimix** [comment]
File proxy_error.log:

2015/07/26 15:56:14 [error] 16371#0: *773 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 94.41.152.218, server: crm.shopavenue.ru, request: "POST /install/Install.php HTTP/1.1", upstream: "fastcgi://unix:/var/www/vhosts/system/crm.shopavenue.ru/php-fpm.sock", host: "crm.shopavenue.ru", referrer: "http://crm.shopavenue.ru/install/Install.php" 
2015/07/26 15:57:26 [error] 16371#0: *773 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 94.41.152.218, server: crm.shopavenue.ru, request: "POST /install/Install.php HTTP/1.1", upstream: "fastcgi://unix:/var/www/vhosts/system/crm.shopavenue.ru/php-fpm.sock", host: "crm.shopavenue.ru", referrer: "http://crm.shopavenue.ru/install/Install.php" 
2015/07/26 15:58:45 [error] 16371#0: *773 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 94.41.152.218, server: crm.shopavenue.ru, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/www/vhosts/system/crm.shopavenue.ru/php-fpm.sock", host: "crm.shopavenue.ru" 
2015/07/26 16:14:59 [error] 16371#0: *790 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 94.41.152.218, server: crm.shopavenue.ru, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/www/vhosts/system/crm.shopavenue.ru/php-fpm.sock", host: "crm.shopavenue.ru" 


Error.log of webserver not have errors

**Comment by JeRRimix** [comment]
You tell every time about the server and about the logs, but it have no errors. About similar problems with the installation are already written more than once at here. You say check logs or install the WAMP on Windows and check again. But I have a logical: who are running webserver on Windows? 
All normal and modern servers built on Linux, why I need to install a curve Windows? It's ridiculous If you work on Windows server :))))

**Comment by bpabiszczak** [comment]
Error 504 is an error returned by the server, which means only the server knows what the cause is. Of course, the application itself may cause the error, but only the server knows what is incorrect about the application itself. The fact that you can't see anything in your logs doesn't mean anything, consult a good administrator so he can tell you the cause of the problem. If the administrator cant help you find a new one.

**Comment by bpabiszczak** [comment]
http://rosalindgardner.com/blog/10-things-to-do-during-a-504-gateway-timeout/ 
http://stackoverflow.com/questions/26742580/504-gateway-time-out-the-server-didnt-respond-in-time-how-to-fix-it 
http://www.idganswers.com/question/11852/what-causes-a-504-error
