### ISSUE TITLE
[bug] Error SQLSTATE [22001]: String data, right truncated: 1406.... Ver. 6.0.3

### ISSUE THREAD

**Issue by alex-nap** [YetiForceCompany/YetiForceCRM#16125]
Hello, every time I save a change or insert a comment, this error message appears.

`SQLSTATE [22001]: String data, right truncated: 1406 Data too long for column 'content' in row 1 The running SQL was: INSERT INTO` l_yf_mail` (`smtp_id`,` from`, `cc` , `subject`, `content`,` date`, `owner`,` error_code`) VALUES (1, '{\ "email \": \ "no-reply@whooho.it \", \ "name \" : \ "no-reply@whooho.it \"} ',' [\ "aleterracciano84@gmail.com \"] ',' Hi, performance needs your attention;) ',' & nbsp; \ r \ n < table align = \ "center \" bgcolor = \ "# ffffff \" border = \ "0 \" cellpadding = \ "0 \" cellspacing = \ "0 \"> \ r \ n <tbody> \ r \ n < tr> \ r \ n <td height = \ "20 \"> & nbsp; </td> \ r \ n </tr> \ r \ n <tr> \ r \ n <td> \ r \ n <table align = \ "center \" border = \ "0 \" cellpadding = \ "0 \" cellspacing = \ "0 \"> \ r \ n <tbody> \ r \ n <tr> \ r \ n <td bgcolor = \ "#fcfcfc \"> \ r \ n <table align = \ "center \" border = \ "0 \" cellpadding = \ "0 \" cellspacing = \ "0 \"> \ r \ n <tbody> \ r \ n <tr> \ r \ n <td> <div style = \ "width: 100% \"> <img src = \ "data: image / jpeg; base64, iVBORw0KGgoAAAANSUhEUgAAAAJIAAACWCAYAAAA16tGYAAAAGXRFWZ9RTb2FBZYBYZ2FBZYBZ2FBYZ2BZYBZ2 NpVFh0bWE S5hZG9iZS54bXAAAAAAADw / eHBhY2tldCBiZWdpbj0i77u / IiBpZD0iVzVNME1wQ2Voa
etc ...... It is very long

I have version 6.0.3
Until 3 days ago, it didn't happen.  the system has been running for months.

My configuration Yetiforce:
![ConfReport (1)](https://user-images.githubusercontent.com/102237839/171203767-f4136335-6013-4290-9d9a-a1a62ed2f22b.png)

Thank you

**Comment by mariuszkrzaczkowski** [comment]
1.repair the configuration (if it complies with the requirements, you would not be wrong)
 https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements 
2. Upload the amendment

```sql
ALTER TABLE `l_yf_mail` CHANGE `content` `content` MEDIUMTEXT NULL; 
```
https://github.com/YetiForceCompany/YetiForceCRM/commit/49fc47ea6d35f2c0a32108a0d04c88af0cec1b6f#diff-8397623c29419bd80578a78b38aba912d18eb3d9b5d9c097c393bb361659be69R696
