### ISSUE TITLE
[bug] CRON run into problem, getCondition() must be of the type string, null given

### ISSUE THREAD

**Issue by Jianbin719** [YetiForceCompany/YetiForceCRM#16127]
CRON run into problem,
![image](https://user-images.githubusercontent.com/75652286/171534956-dfd415ee-0cf5-4639-9329-417f60aea99b.png)

# 🐞 bug report

### ⁉️ Describe the bug

Show error in CRON log

022-06-02 10:05:01 | LBL_WORKFLOW - Start task

TypeError: Argument 3 passed to App\QueryGenerator::getCondition() must be of the type string, null given, called in /www/wwwroot/Yetiforce/app/QueryGenerator.php on line 1131 and defined in /www/wwwroot/Yetiforce/app/QueryGenerator.php:1078
Stack trace:
#0 /www/wwwroot/Yetiforce/app/QueryGenerator.php(1131): App\QueryGenerator->getCondition('_VT_add_comment', '', NULL, false)
#1 /www/wwwroot/Yetiforce/modules/com_vtiger_workflow/WorkFlowScheduler.php(198): App\QueryGenerator->addCondition('_VT_add_comment', '', NULL, true)
#2 /www/wwwroot/Yetiforce/modules/com_vtiger_workflow/WorkFlowScheduler.php(50): WorkFlowScheduler->addWorkflowConditionsToQueryGenerator(Object(App\QueryGenerator), Array)
#3 /www/wwwroot/Yetiforce/modules/com_vtiger_workflow/WorkFlowScheduler.php(63): WorkFlowScheduler->getWorkflowQuery(Object(Workflow))
#4 /www/wwwroot/Yetiforce/modules/com_vtiger_workflow/WorkFlowScheduler.php(94): WorkFlowScheduler->getEligibleWorkflowRecords(Object(Workflow))
#5 /www/wwwroot/Yetiforce/modules/Vtiger/crons/Workflow.php(28): WorkFlowScheduler->queueScheduledWorkflowTasks()
#6 /www/wwwroot/Yetiforce/cron.php(99): Vtiger_Workflow_Cron->process()

1. Create workflow for TICKETS module,
![image](https://user-images.githubusercontent.com/75652286/171534046-b05d7706-4392-448d-8e71-a9faf2139216.png)

2. With conditions, comment is added
![image](https://user-images.githubusercontent.com/75652286/171534172-b7705f4f-9906-4a2f-b805-600ce3d0daa6.png)

3. if comment is added to the ticket, will update the custom field for logging date with lastest follow up.

**Comment by konadrian** [comment]
Hello 
This functionality isn't supported by Yetiforce. It's old code from Vtiger. 

You can try using workflow actions directly in Comments module and check if it has everything that you need.

I closed this topic.
