### ISSUE TITLE
[BUG] Organizations - Address

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1613]
Where should I choose an organization?

![animation 64](https://cloud.githubusercontent.com/assets/1402355/8898667/d2a03866-3441-11e5-8061-e349df4d98f0.gif)

**Comment by florek41** [comment]
In *Member Of* field.
I think description of copy button should be more intuitive

**Comment by waw555** [comment]
Ok, Thanks

**Comment by bpabiszczak** [comment]
So maybe suggest a better translation?  We are not very attached to it ;)
