### ISSUE TITLE
[Security] Mailscanner failed due to Roundcube update requirement

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#16136]
Suddenly mailscanner stops fetching emails. Checked Roundcube and it it happen it require update.
In my opinion it is serious security issue if yetiforce in background checking libraries updates. Without informing system admin
all connected to imap processes are failing. 
This is in 6.3 version
Bearing in mind above.... what other background connections are processed by yetiforce without consent of admin?

BEst

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/172307367-6865e101-5d04-4523-8d99-7156f0c8f002.jpg)
