### ISSUE TITLE
I can't be verified

### ISSUE THREAD

**Issue by admin-flaviomariarusso** [YetiForceCompany/YetiForceCRM#16175]
Hi everyone, I need your support because I can't be verified in the CRM system, and not being verified, I can't access the functions that CRM offers me only after verification. I tried to send an email containing all the information to registration@yetiforce.com. but I haven't received any feedback yet. I also tried to register online by filling out the form in the CRM but, after a week, I still haven't received anything.

Thanks a lot to everyone in advance.

**Comment by admin-flaviomariarusso** [comment]
I'm also attaching a screenshot of the email I sent to: registration@yetiforce.com
<img width="553" alt="Immagine 2022-06-19 141316" src="https://user-images.githubusercontent.com/107797556/174480437-65c2ef3a-ee4b-4ebe-8293-4b69aaee8411.png">

**Comment by paula-w** [comment]
Hi
we received your online registration 4 days ago and accepted it 3 days ago, then you modified some registration data yesterday and we accepted it again today. 

[This article](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/problems-with-system-registration) describes how to fix registration issues.

I also sent you an email with more information regarding your registration, please check your inbox.
