### ISSUE TITLE
[bug] When applying multiple profiles to a department. Create Record Button is not available in the modules assigned in the 2nd profiles and onwards

### ISSUE THREAD

**Issue by souravkumar4797** [YetiForceCompany/YetiForceCRM#16199]
# 🐞 bug report

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/175224589-44c1dd01-7edd-40a8-b0c7-a7cd6def5ea6.jpg)

**Comment by vovpff** [comment]
@souravkumar4797 as I checked in the past situation with profiles for roles:
You can choose one or more profile for role but really rules from different profiles don't combined for role.
@mariuszkrzaczkowski

**Comment by souravkumar4797** [comment]
Thanks @vovpff. but, suppose I have created profiles for 5 different type of work and finally I want to assign 2 profiles to one role and 3 to another. So everything works fine for 1 and onwards except the button to create the record in the module assigned in the second profile and onwards.
