### ISSUE TITLE
MailScanner prefix bind doesn't work

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#1619]
If I send and email from Opportunity, using Send Email button from email widget, with normal SS3 prefix in subject, mail is not being bind to SS3 opportunity. Binding to Leads, Contacts, Acocunt works ok, but it's based on email address of sender, while opportunity mail binding is based on subject prefix. The same goes for Tickets etc.
I tested on .500 something developer version and also on gitdeveloper demo and results are the same.

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/25c64ff7ea6f77f679d43d741d997570a98102a9
