### ISSUE TITLE
[bug]  at func recordsList 

### ISSUE THREAD

**Issue by ArniSamano** [YetiForceCompany/YetiForceCRM#16208]
Riding on v6.3

When I try to generate PDF report from the list or records (Services) I have to select at least one record.
Than report is generated correctly.
If I select two records, the same report is doubled in one PDF file.
If I select all 60 records I have in services, the system memory get exhausted throwing error.
Expected is that report is generated for all selected records (not all records in module multiplied by number of selected)

var used in PDF: $(recordsList : Services|pic1,servicename,subcategory,unit_price)$

Operating system here is configured perfectly in line with developer recommendation (Debian)

**Comment by apcloic** [comment]
@ArniSamano Did you check "Generate one PDF for many records" in general settings of your PDF template ?

**Comment by ArniSamano** [comment]
As I said it works when select only one record. No doubling. But selecting multiple records should print list of ONLY selected, but now it prints all and multiplied by number of selected records

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/11937#issuecomment-1166163159

**Comment by ArniSamano** [comment]
Marius, as I mentioned, PDF output should respect all records selected, so for instance user can create filter (or filter by column), or select manually and print all records included in filter. As for now 'recordsList' printing all records. This limiting reporting :-)

**Comment by mariuszkrzaczkowski** [comment]
I added a fix that fixes the display of photos in "$ (custom: RecordsList) $" and in "$ (recordsList: Products) $" fixes filtering
https://github.com/YetiForceCompany/YetiForceCRM/commit/7a29a99dc913dc07722cab2f7362e0f1f18c4a50
