### ISSUE TITLE
2.1 Updater testing

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1620]
This weekend I did some testing with the 2.1 dev updater (well 2.0596) and had no big issues.
All important parts seem to work. Few small things like Widgets on homepage (History) did not show but after deleting and re-assigning it was fine. Seems pretty normal with so many changes.
Guess some issues will surface while using but the actual update had no errors.

**Comment by bpabiszczak** [comment]
If you don't report the error [for example the one with history on the homepage] it won't be fixed. Report every smallest issue you encounter, we'll try to make the system stable, but the community's help is in this matter necessary. We constantly look for errors and fix them immediately [it's enough to look through the list of commits posted today https://github.com/YetiForceCompany/YetiForceCRM/commits/developer]. I hope we can publish the official update package from version 2.0 to 2.1 tomorrow or  day after tomorrow. This package will include all changes [even the ones we introduced today]. 

I'm happy you tested the test version of the package, it ensures us that the package doesn't contain any bigger errors and works properly, also thank you for writing about it.

**Comment by waw555** [comment]
I have not yet tested)))) Today I will try to install!

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.0.0_to_2.1.0/zip

**Comment by waw555** [comment]
Invalid request - Response For Illegal Access

![animation 67](https://cloud.githubusercontent.com/assets/1402355/8906534/e085846c-3488-11e5-80d5-80450862dc7f.gif)

**Comment by zebrahosting** [comment]
Make sure you only zip up the content of the 2.1 folder, not the folder itself.

Bastiaan Houtkooper
Zebra Hosting

From: Алексей
Reply-To: YetiForceCompany/YetiForceCRM
Date: maandag 27 juli 2015 14:57
To: YetiForceCompany/YetiForceCRM
Cc: Bastiaan
Subject: Re: [YetiForceCRM] 2.1 Updater testing (#1620)


Invalid request - Response For Illegal Access

[animation 67]<https://cloud.githubusercontent.com/assets/1402355/8906534/e085846c-3488-11e5-80d5-80450862dc7f.gif>

**Comment by waw555** [comment]
I checked the library, all at the root of the archive, as it should be.

**Comment by waw555** [comment]
v3 don't work  (((

**Comment by bpabiszczak** [comment]
Please test new version.

**Comment by waw555** [comment]
Invalid request - Response For Illegal Access

**Comment by bpabiszczak** [comment]
You test clear version 2.0.0.?

**Comment by waw555** [comment]
Yes

**Comment by bpabiszczak** [comment]
The problem is that we don't know how to trigger the error. We updated 3 system versions today, none of them generated your error. The only thing we found is that we don't update the template on user, which “destroys” the view [after user's edit/save everything works well]. You have to think what's the difference between your system/version and ours. We have to be able to trigger the error to be able to fix it.

If you want we can install a clean version of YetiForce 2.0.0. and you can try to update it on our server.

**Comment by waw555** [comment]
Let's try

Use https://github.com/YetiForceCompany/YetiForceCRM/archive/2.0.0.zip

and 

Use https://github.com/YetiForceCompany/UpdatePackages/blob/developer/YetiForce%20CRM%202.x.x/2.0.0_to_2.1.0/zip/2.0.0_to_2.1.0_RC_v4.zip

**Comment by mariuszkrzaczkowski** [comment]
![lab](https://cloud.githubusercontent.com/assets/10198654/8957770/f2c5336a-3600-11e5-9a41-f34dceedc1be.gif)

**Comment by waw555** [comment]
Normal Work's

I will check that with my server

![animation 91](https://cloud.githubusercontent.com/assets/1402355/8957904/fa5637c2-361a-11e5-936d-80fd291a1b7b.gif)

**Comment by waw555** [comment]
This can affect?

[29-Jul-2015 17:59:01 Asia/Yekaterinburg] PHP Notice:  Undefined variable: fldcache in /www/default/include/utils/VTCacheUtils.php on line 115

**Comment by waw555** [comment]
Only the parameters upload_max_filesize = 1000M ;1GB post_max_size = 1000M, I went update

**Comment by waw555** [comment]
After all updates some become small))))))))))))))))))

![animation 92](https://cloud.githubusercontent.com/assets/1402355/8958557/035297ae-361f-11e5-8861-65999b5cfacd.gif)

**Comment by bpabiszczak** [comment]
You have to increase one of these parameters:

post_max_size

upload_max_filesize

I don't know which one, because I'm neither a programmer nor an administrator. Check it, and see which one worked for you [I assume both will have to be increased- we got 64MB on our servers]. Additionally, we increased parameters during installation: https://github.com/YetiForceCompany/YetiForceCRM/commit/d136902de5f9c36c09742d5c53cb727b29730711 
As you see, logs give you the whole spectrum of the problem, use them more often.

**Comment by bpabiszczak** [comment]
New problem new ticket...

**Comment by zebrahosting** [comment]
And My first post was there Just to say I had zero issues..... :-)

**Comment by bpabiszczak** [comment]
Together we will achieve more. It is really good to cooperate with you.

**Comment by rskrzypczak** [comment]
zebrahosting
   "Few small things like Widgets on homepage (History) did not show.."

Fixed in 2.0.0_to_2.1.0_RC_v5.zip (https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.0.0_to_2.1.0/zip)

**Comment by waw555** [comment]
It would be nice if professional hosting give advice or instructions on installing and configuring apache php mysql for Yeti based on their knowledge and experience in working with the Yeti, not everyone can afford a hosting for money.
My house is a computer in 1997, which still stands as an experimental site and hosting for personal sites))))
And each time reinstalling Debian, configure it for a variety of links from the Internet and set different parameters specified therein))))

**Comment by waw555** [comment]
P. S. This is me zebrahosting

**Comment by zebrahosting** [comment]
waw555 make testing easy, install a bare Linux distro and use this: http://vestacp.com/ to setup an easy to handle environment. It will give you apache and nginx to test and all the tools to start properly.

**Comment by waw555** [comment]
Big Thanks
