### ISSUE TITLE
Ban Editing Mandatory Fields 

### ISSUE THREAD

**Issue by shawkatmarrouf** [YetiForceCompany/YetiForceCRM#16228]
Hello,

Working on yetiforce 6.3, In user permissions, How can I prevent a user profile who have "View, Edit" privilege only from editing mandatory fields?
In the following case I want a user to be able to edit just one field but I couldn't do it?
![yeti](https://user-images.githubusercontent.com/101041720/177004819-d77f645c-2a03-4401-9c96-500dc6273eb3.png)

Mandatory fields are disabled, I want to make them just read in this module for this user?

**Comment by shawkatmarrouf** [comment]
any reply please! @prabhu @vctrin @majkel89

**Comment by mariuszkrzaczkowski** [comment]
try to use "Dependent Fields"
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=FieldsDependency&view=List
