### ISSUE TITLE
MailScanner Cron Jobs

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#1622]
In Scheduler I see three cron jobs related to MailScanner:
1. MailScannerAction
2. MailScannerVerification
3. MailScannerBind
Can you explain to me (or provide a link toward explanation) what each of this processes is doing and what scripts executes? I'm especially confused about the difference between MailScannerAction and MailScannerBind, because most actions are binding.

**Comment by bpabiszczak** [comment]
This is the main action, which means the scanner uses it to download mails and performs all actions on it.

This action is used for verification whether or not the scanner stopped working properly, if yes then it sends a message informing about this fact.

This action works exactly like the first action, but it's triggered from the company mail level, there's a tool that allows us to “link” emails again. It's useful when we fix the mail scanner, then we can once again run the mechanism that links emails with other records. It works only for company mails, which means it doesn't download the mail again. The mechanism enters the table of selected records into a table and then the action in cron scans every record from the table.

**Comment by nikdejan** [comment]
Five months later, after learning a lot about YF, I finally understand your explanation. Thank you @bpabiszczak :-)
