### ISSUE TITLE
[BUG UI] Currency formatting not correct

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1624]
Realted to the service module (but probably also in other areas where currencies are displayed), the formatting
a) does not work correctly - digits after the decimal point are not displayed
b) currency symbot is inconsistent - sometimes it is displayed as (CHF) 9'999, sometines as CHF9'999

The user setting are such as to request two (2) digits after the comma for currencies / prices as shown
![img02](https://cloud.githubusercontent.com/assets/10230144/8907091/0a7faf46-3474-11e5-8711-4cd946f7f623.jpg)

Displaying the service does not format the price correctly. The VAT also does not show with two digits after the decima separator (should it?)
![img01](https://cloud.githubusercontent.com/assets/10230144/8907157/6e60d3fa-3474-11e5-935a-29da3ef2f753.jpg)

The list of all services also does not format the price correctly (in addition to using up a large amount of unnecessary space)
![img03](https://cloud.githubusercontent.com/assets/10230144/8907175/8a151408-3474-11e5-878f-64b7d89c3efd.jpg)

**Comment by bpabiszczak** [comment]
We tested this scenario. In the first test a similar error to yours occurred, however, in the following tests it didn't show up anymore and everything was alright [now we aren't able to recreate it]
Please, test this error once again using the newest gitdeveloper version, and describe in detail, what isn't right and how you'd want it to be.

**Comment by diderich** [comment]
Now it works for currencies. There is still a discrepancy in display. At some places the value is shown CHF1'400.00, at some others it is shown without the currency, the currency being added to the field name 'Field(CHF)' (see for example second figure above). I would prefer that the currency is systematically displayed CHF1'400.00 rather than have the two options. In addition I would recommend putting a space between the currency and the number, i.e., CHF 1'400.00.
But why are VATs, that is %, getting three digits rather than the configured two?
