### ISSUE TITLE
Theme dropdown shows only one (wrong) color

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1625]
Not a reason to delay the 2.1 update but in my v596 the dropdown box for the theme(color) shows only one color (twilight - blue) while the the topbar shows grey/black. No other colors seem to be working.
The skins are still in the directories....

**Comment by florek41** [comment]
I thing this is something similar as #1169

**Comment by zebrahosting** [comment]
Same area, but now in the latest dev version, the drop down does not even show colors anymore.
Could be one ticket/bug report indeed. I' ll close this one then.

**Comment by mykljohn** [comment]
This problem is related to YetiForceCRM/modules/Vtiger/helpers/Util.php

	public static function getAllSkins()
	{
		return array('twilight' => '#404952');
	}

I tried changing it, but it had no effect.  Just FYI

**Comment by mykljohn** [comment]
Also, twilight has the correct color defined, but the menu shows up as black, not 404952

**Comment by bpabiszczak** [comment]
Currently there's only one template in one color in the system, we changed its appearance so it looks like the original bootstrap. A new template will be available in 2.4 or 2.5 version. What you see now is intentional.

**Comment by mykljohn** [comment]
Ah, ok.   Gracias for that info.  I though I was crazy J
