### ISSUE TITLE
[Design BUG] Contact Create

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1626]
![animation 68](https://cloud.githubusercontent.com/assets/1402355/8923767/ae2710ae-350e-11e5-9f77-13224c19c11e.gif)

**Comment by konadrian** [comment]
Does it still occur? I checked on ff and chrome, I asked another programmer to check and this select look fine.
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/8926268/beb946c6-350e-11e5-95b1-4fc21bb7ddc9.png)
