### ISSUE TITLE
[Design BUG] Save Button

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1629]
Buttons are arranged, it is in the middle, the right or left side.
![animation 74](https://cloud.githubusercontent.com/assets/1402355/8924076/a3566ec8-3512-11e5-87d2-95bcfb795382.gif)

**Comment by konadrian** [comment]
What is wrong with this button ? 
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/8927411/97dabcac-3517-11e5-99d5-976bbd2e56e6.png)

**Comment by florek41** [comment]
I think it's about that each button has different position (left, right or middle).

**Comment by waw555** [comment]
Yes
