### ISSUE TITLE
[bug] [PL] Ilość wolnego miejsca

### ISSUE THREAD

**Issue by assaoffwm** [YetiForceCompany/YetiForceCRM#16305]
Dzień dobry,

wyświetla się nam komunikat w ostrzeżeniach o małej ilości miejsca na dysku. 
Komunikat jaki wyświetla się:

"Mało wolnego miejsca na dysku (6% | Wolnych: 90 GB | Zajętych: 6.13 GB), brak wystarczającej ilości miejsca na dysku spowoduje że system przestanie działać. Ścieżki do katalogów:

Katalog główny 6% | Wolnych: 90 GB | Zajętych: 6.13 GB
Katalog storage: 6% | Wolnych: 90 GB | Zajętych: 6.13 GB
Katalog tymczasowy: 6% | Wolnych: 90 GB | Zajętych: 6.13 GB"

Sprawdzałam przez SSH to mamy 91 GB wolnej przestrzeni na dysku a zajęte jest tylko 6.1 GB.
Czy to jakiś błąd YETI czy może gdzieś ustawia się przydzieloną przestrzeń YETIemu?

Bardzo proszę o pomoc w tej sprawie.

# 🐞 bug report

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |6.1
| Web server (name and version)       |        serwer VPS na nazwa.pl        |
| PHP                                 |      7.0          |
| Browser (name and version)          |     Opera           |
| Operating System (name and version) |        Windows 10        |
| Database (name and version)         |        14.14        |
| Service Pack version                |        8        |

**Comment by bpabiszczak** [comment]
Wersja 6.1? Zalecam aktualizację. Nie będziemy weryfikować takich rzeczy na starej wersji, jeżeli błąd wystąpi na najnowszej, wówczas możemy sprawdzać.

**Comment by assaoffwm** [comment]
Dziękuje za odpowiedź.
