### ISSUE TITLE
[bug] unable to get the same "modified time, ticket no, created time, last modified by ,assigned to ,and created by" system fields while importing from old tickets.

### ISSUE THREAD

**Issue by sreenathreddy9949362660** [YetiForceCompany/YetiForceCRM#16366]
# 🐞 bug report

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
Please create the issue correctly/legibly
![github](https://user-images.githubusercontent.com/10198654/185876242-286172ec-35d5-4d4f-84d4-b18a5b8afafb.jpg)
