### ISSUE TITLE
[bug] Updating from 6.3 to 6.4

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#16364]
# 🐞 bug report

### ⁉️ Describe the bug

When I am running the update script, I get the following error, where mail.didilan.net is the name of the SMTP server I am using:

![yeti_err_1](https://user-images.githubusercontent.com/10230144/185737472-7da1f73f-3f35-43a9-b900-44d498ed93e3.jpg)

The file `cache/logs/errors.log` does not exist (i.e., not errors are logged).

### 🔥 How to trigger the error

1. Update system from 6.3 zo 6.4

### 👎 Actual Behavior

See screenshot above.

### 👍 Expected Behavior

System is successfully updated.

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

The update cannot be tested on GIT.

I tried to run the update by replacing `mail.didilan.net` with `smtp.gmail.com` and the port by `465` and I get the same error:
![yeti_err_1a](https://user-images.githubusercontent.com/10230144/185737715-cb844bfd-dc9b-43c0-81cc-3d448f323a05.jpg)

### 📷 Screenshot of configuration

![config](https://user-images.githubusercontent.com/10230144/185738273-c7d082b6-04de-4ef0-a433-710b23572c66.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

None available.

### 🌍 Your Environment

`config/Modules/OSSMail.php`:

![mail_config](https://user-images.githubusercontent.com/10230144/185738118-be413540-1184-4df9-bb6c-6b694097d46a.jpg)

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.3.0 v8
| Web server (name and version)       | apache2     2.4.51           |
| PHP                                 |   8.0             |
| Browser (name and version)          |                |
| Operating System (name and version) |  openSUSE Leap 15.4               |
| Database (name and version)         |  mariadb 10.8.3|
| Service Pack version                |    Security Fix v8            |

**Comment by diderich** [comment]
Setting `$smtp_server = 'ssl://mail.didilan.net'` allows the update to run through.

**Comment by rskrzypczak** [comment]
Fixed in update pack v2: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/6.4.0
Thx
