### ISSUE TITLE
[bug] Warning in errors.log when saving OSSTimeControl entry

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#16377]
# 🐞 bug report

### ⁉️ Describe the bug

When saving a newly created or modified OSSTimeControl entry, the following warnings are reported in the `cache/logs/errors.log` file:
![errors-log](https://user-images.githubusercontent.com/10230144/185883210-b0d09503-afbe-45c7-a004-95fc86c075b6.jpg)

I have not identified (yet) any functional issue based on this warning

### 🔥 How to trigger the error

1. Go to 'Time Control' panel
2. Create new time control entry and save it
3. Display errors.log file to see the warning messages

### 👎 Actual Behavior

Warning messages are displayed.

### 👍 Expected Behavior

No warnings are recorded.

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com
- [x] As there is not access provided to the `errors.log` file, the issue cannot be tested on gitstable or gitdeveloper

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

See above for `cache/logs/errors.log` content. No other error files are produced

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4.0
| Web server (name and version)       |     apache2           |
| PHP                                 |     8.0.22          |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |     v1           |

**Comment by rskrzypczak** [comment]
Fixed in YF 7.0.x
