### ISSUE TITLE
[bug] Nie działa!? Po aktualizacji przestał działać Nominatim i OpenCage.

### ISSUE THREAD

**Issue by rbtm** [YetiForceCompany/YetiForceCRM#16374]
Dzień dobry, zrobiłem dziś aktualizację i przestały działać obie wyszukiwarki adresów jak w temacie. Przed aktualizacją a po wpisaniu fragmentu adresu uruchamiało się wyszukiwanie a obecnie nie mogę wymusić tego w żaden sposób?! Albo takiego sposobu nie znam, albo zostało coś popsute :-(

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/185876242-286172ec-35d5-4d4f-84d4-b18a5b8afafb.jpg)
