### ISSUE TITLE
[bug] Nie działa!? Dziękuję za sparaliżowanie pracy! Nie można zapisać nowego ani edytować wcześniej wprowadzonego kontrahenta!

### ISSUE THREAD

**Issue by rbtm** [YetiForceCompany/YetiForceCRM#16375]
Po podaniu wszystkich wymaganych informacji, w ogóle nie działa przycisk ZAPISZ pod formularzem kontrahenta! Niech Pan tylko nie zapomni upomnieć mnie, że potrzebne są dodatkowe informacje, żebym musiał się nad tym pół dnia spuszczać, bo przecież nie mam nic innego do roboty - A TO WASZA ROBOTA! Zrobiliście jakąś aktualizację a człowiek jak zwykle głupi zaktualizował a cały proces został przeprowadzony JAK ZWYKLE. Testuje się na użytkownikach!!??!!

**Comment by bpabiszczak** [comment]
Nie bardzo rozumiem o czym rozmawiamy i do kogo są pretensje. Jezeli jest sie naszym klientem to zapraszam na SLA, jezeli nie i oczekuje sie bezpkatnego wsparcia to zalecam zmienic ton bo nikt nie pomoze gdy dyskusja zaczyna sie od pretensji.

Po trzecie wszelkie zmiany (a w szczegolnosci aktualizacje) najpierw robi sie na srodowisku testowym.

Zalecam usuniecie cache, a nastepnie zgloszenie tego o co prosimy przy zakladaniu issue.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/UpdatePackages/blob/master/YetiForce%20CRM%206.x.x/6.3.0_to_6.4.0/license.txt#L8-L17
Proszę opróżnić pamięć podręczna przeglądarki i cookies: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-clear-browser-cache
Jeżeli to nie pomoże, to pozostaje Panu analiza zjawiska, a więc tzw. debugowanie.
W celu szukania wsparcia na GitHub-ie, proszę utworzyć nowe zgłoszenie zgodnie z zaleceniami.

**Comment by rbtm** [comment]
Ale przepraszam bardzo. Wprowadza Pan jakąś aktualizację, nie informując wprost, że aktualizacja całkowicie zablokuje możliwość zarządzania kontrahentami i uważa Pan, że to jest w porządku? W ten sposób Pan "zaprasza" do skorzystania z płatnego supportu? Mało tego naprawdę uważa Pan, że aktualizację użytkownik powinien na własną rękę przeprowadzać w środowisku testowym, bo przecież należało się spodziewać jak wyżej, czyli, że aktualizacja całkowicie zablokuje możliwość zarządzania kontrahentami?
