### ISSUE TITLE
Importing module Failed

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#16370]
[ver. 6.3.0] ---> [ver. 6.4.0] 

The server configuration is not compatible with the requirements of the upgrade package. Please have a look at the list of errors: max_execution_time = 300 < 600 max_input_time = 300 < 600
![ConfReport](https://user-images.githubusercontent.com/25682437/185782796-c006a326-19ea-457e-bdef-4e5197d5d77e.png)

**Comment by rskrzypczak** [comment]
I don't see any bug here and I don't know what you're reporting.
**Correct server configuration**, you will have no problem with starting the update.

**Comment by fbojan** [comment]
![Importing module Failed](https://user-images.githubusercontent.com/25682437/186112666-90519ef3-6781-41f2-95ba-610f190ffcf7.gif)

**Comment by fbojan** [comment]
Z góry dziękuję za wasze wysiłki

**Comment by rskrzypczak** [comment]
As I mentioned before, there is no error here.
Installation of the Update Package requires the appropriate configuration of the server in terms of these parameters, which you mentioned, to protect yourself against sudden termination of the script, i.e. update, which would lead to application damage.
There is nothing we can help you with.
Correct the mentioned configuration parameters on the server, you will have no problems updating the application.

**Comment by fbojan** [comment]
Thanks, I really missed something. I'm sorry.Now it works
