### ISSUE TITLE
[bug] After Update from 6.3 to 6.4  - Access to undeclared static property: Config\Modules\ModComments::$defaultSource

### ISSUE THREAD

**Issue by QVinto** [YetiForceCompany/YetiForceCRM#16379]
# 🐞 bug report

### ⁉️ Describe the bug

After updating to 6.4 from older version, there is a glitch when code is calling $defaultSource insted of old one $DEFAULT_SOURCE. It is autogenerated php in Config\Modules\ModComments

![image](https://user-images.githubusercontent.com/4982986/185894615-97a6f152-9415-47a6-ba1a-25a02959e786.png)

The actual ModComment.php after update is $DEFAULT_SOURCE
![image](https://user-images.githubusercontent.com/4982986/185894746-9f02f686-57b5-4e2e-89cf-9cfc3cb7aa4e.png)
 
After changing the code to $defaultSource, everything works fine
![image](https://user-images.githubusercontent.com/4982986/185894959-56d75ecd-bc22-4134-bc70-b2265c9beef7.png)

### 🔥 How to trigger the error

Probably you have to update step by step from very old version like 4.x to 5.x to 6.4 because that php was autogenerated a long time ago and uses old declaration. In my case it was from 5.1  - version after version -  till 6.4

- [✔️ ] I confirm that I tested it at https://gitstable.yetiforce.com - **everythong works fine**
- [ ✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com - **everything works fine**
- ✔️ own environment - **error occured**

### ❗️ Inform the community if you solve the problem

problem is solved after changing declaration in Config\Modules\ModComments.php from 'public static $DEFAULT_SOURCE' to 'public static $defualtSource'

There should be a process when upgrading/updating yetiforce to make new autogenerated ModComments.php with right declaration.

**Comment by rskrzypczak** [comment]
Probably the upgrade to 6.4 did not finish correctly for you.
One of the last steps of updating is reloading the application's configuration files, which did not happen for you.
Verify the updateLogsTrace.log file, or preferably attach to the ticket.

**Comment by QVinto** [comment]
[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/9393545/updateLogsTrace.log)

**Comment by rskrzypczak** [comment]
Just as I thought. The script was interrupted at the last stage of the update, namely when updating the configuration files.
There can be several reasons for this, e.g. file or directory permissions.
However, you should find more information in other log files (app, server).
You can try to enable application logs and update up to 6.4 one more time.

This is not an application or update package bug, so I close the issue.
If you have any comments, please include more information, the server configuration and logs.

**Comment by QVinto** [comment]
thank you for info. I will try to find reasons why it stoped.

**Comment by rskrzypczak** [comment]
I suppose the reason for your errors lies here: https://github.com/YetiForceCompany/YetiForceCRM/issues/16364
