### ISSUE TITLE
[bug] Nieaktywny przycisk ZAPISZ?! Nie można dodać nowego ani edytować wcześniej dodanego kontahenta/kontaktu.

### ISSUE THREAD

**Issue by rbtm** [YetiForceCompany/YetiForceCRM#16378]
# 🐞 bug report

### ⁉️ Describe the bug

Nieaktywny przycisk ZAPISZ?! Nie można dodać nowego ani edytować wcześniej dodanego kontahenta/kontaktu.

### 🔥 How to trigger the error

Wystarczy zaktualizować do najnowszej wersji.

### 👎 Actual Behavior

Nieaktywny przycisk ZAPISZ?! Nie można dodać nowego ani edytować wcześniej dodanego kontahenta/kontaktu. Pod zadaniami z kalendarza przycisk zapisz działa bez zmian, czyli po prostu działa.

### 👍 Expected Behavior

Byłoby miło z powrotem wrócić do pracy, bo na ten moment jest ona sparaliżowana.

### 👷 Testing

Nie ma tu czego testować, bo skoro nie działa, to nie działa. Czyszczenie cache nie ma z tym nic wspólnego.

### 📷 Screenshot of configuration
![Zrzut ekranu (49)](https://user-images.githubusercontent.com/58072546/185888574-de74c3f4-51a6-4ae2-b940-a604e6e78519.png)

### 🌍 Your Environment
![ConfReport](https://user-images.githubusercontent.com/58072546/185889144-efb10f78-efde-43e1-9e01-233b51fa8dae.png)

**Comment by rskrzypczak** [comment]
Prawdopodobnie masz ustawiony typ modułu na _zaawansowany_, co jest błędem.
Skoryguj ustawienie, jak pokazano poniżej. Zmiana nie zostanie wykonana w czasie rzeczywistym, tylko z opóźnieniem zgodnie z harmonogramem crona na Twoim serwerze (upewnij się więc, że cron u Ciebie działa _Konfiguracja systemu/Automatyzacja/CRON_), zazwyczaj trwa to kilka minut. 
![image](https://user-images.githubusercontent.com/10221999/185893820-a2166148-cfde-45da-9eeb-9f89d385c950.png)
Oczywiście ponownie załaduj pliki do pamięci podręcznej przeglądarki: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-clear-browser-cache

Zgłoszenie zostaje zamknięte.
Jeżeli powyższe nie rozwiązuje problemu, włącz [logi aplikacyjne](https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-programistyczna/item/debugowanie) i podeślij je.

**Comment by rbtm** [comment]
Dziękuję, pomogło.
