### ISSUE TITLE
[bug] Failed Module does not contain default language (en-US).

### ISSUE THREAD

**Issue by deepti4666** [YetiForceCompany/YetiForceCRM#16389]
# 🐞 bug report

### ⁉️ Describe the bug

Unable to update from 6.1
No errors given - only 
"Failed Module does not contain default language (en-US)."

### 🔥 How to trigger the error

Settings
Logs 
Updates

1. Go to 'Settings'
2. Click on 'Logs'
3. Scroll down to 'Updates'
4. Download Package or Upload
5. See error

![image](https://user-images.githubusercontent.com/57940552/186777448-a4cb849f-9f12-4e8b-9d2a-a5159eb6465a.png)

### 👎 Actual Behavior

E_WARNING: ZipArchive::close(): Invalid or uninitialized Zip object in /home/boardroo/public_html/crm/vtlib/Vtiger/PackageImport.php, line 378
#0 vtlib/Vtiger/PackageImport.php (378)  >>  ZipArchive->close()
#1 vtlib/Vtiger/PackageImport.php (390)  >>  vtlib\PackageImport->checkZip('cache/aa5d2757f2a751577714a9e97caa26ca.zip')
#2 modules/Settings/ModuleManager/views/ModuleImport.php (98)  >>  vtlib\PackageImport->getModuleNameFromZip('cache/aa5d2757f2a751577714a9e97caa26ca.zip')
#3 app/Controller/ExposeMethod.php (65)  >>  Settings_ModuleManager_ModuleImport_View->importUserModuleStep2()
#4 modules/Settings/ModuleManager/views/ModuleImport.php (49)  >>  Settings_ModuleManager_ModuleImport_View->invokeExposedMethod('importUserModuleStep2')
#5 include/main/WebUI.php (189)  >>  Settings_ModuleManager_ModuleImport_View->process()
#6 index.php (28)  >>  Vtiger_WebUI->process()

### 👍 Expected Behavior

Updates to 6.2.0

### 👷 Testing

- [ ✔️ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0
| Web server (name and version)       |                |
| PHP                                 |     7.4           |
| Browser (name and version)          |    Chrome            |
| Operating System (name and version) |                |
| Database (name and version)         |    MySQL 10.5.16-MariaDB-cll-lve            |
| Service Pack version                |                |

![image](https://user-images.githubusercontent.com/57940552/186778707-a3e652e9-f357-486e-8929-72d2999ce61e.png)

**Comment by mariuszkrzaczkowski** [comment]
What zip package are you installing?

**Comment by deepti4666** [comment]
Yetiforce 6.2 from this link https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%206.x.x/6.2.0/YetiForceCRM-6.2.0-complete.zip/download

Also tried to download through the system, but same issue.

**Comment by mariuszkrzaczkowski** [comment]
No, this is a bundle with an installation wizard.
You need an update package, see here:
https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%206.x.x
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%206.x.x/Update%20packages/
