### ISSUE TITLE
[bug] Upgrade 6.3 to 6.4 Switch user error

### ISSUE THREAD

**Issue by Jianbin719** [YetiForceCompany/YetiForceCRM#16387]
# 🐞 bug report
Error: Argument 1 passed to App\User::isExists() must be of the type int, string given, called in /www/wwwroot/Yetiforce/cache/templates_c/basic/5af61c354666bee008c76d18f9876904776130f6_0.file.SwitchUsers.tpl.php on line 35
![image](https://user-images.githubusercontent.com/75652286/186551385-62082384-a630-42fd-a822-bf416eadfe3f.png)

![ConfReport](https://user-images.githubusercontent.com/75652286/186552201-8038228f-19b0-45f8-b06f-443f63e8d18a.png)

**Comment by Jianbin719** [comment]
After upgrade to 6.4 from 6.3, it shows error in the pic above. 

is there the way to empty all switch user settings, and set it again.

**Comment by rskrzypczak** [comment]
You can upload the indicated patch directly (https://github.com/YetiForceCompany/YetiForceCRM/commit/adbfa89546ac61ec259d79e51ee0a8b4f6ee3f17) or wait for the release of the service pack, which will probably appear in days.

**Comment by mariuszkrzaczkowski** [comment]
Additionally, repair the configuration because your server does not meet the requirements.

**Comment by Jianbin719** [comment]
Thanks, problem solved
