### ISSUE TITLE
[bug] After update 6.4 - there is no log about update when installing via Upload file process

### ISSUE THREAD

**Issue by QVinto** [YetiForceCompany/YetiForceCRM#16380]
# 🐞 bug report
![image](https://user-images.githubusercontent.com/4982986/185898417-1c3518b2-93dc-490b-811a-e7d15425d893.png)

### ⁉️ Describe the bug

no info about finished update process

### 🔥 How to trigger the error
Update via Upload File
![image](https://user-images.githubusercontent.com/4982986/185898586-d370218d-1304-4b82-aaf0-f528631676e9.png)

### 👎 Actual Behavior

no info about 6.4 update

### 👍 Expected Behavior

new row with info about update

### 👷 Testing

- [no] I confirm that I tested it at https://gitstable.yetiforce.com
- [no] I confirm that I tested it at https://gitdeveloper.yetiforce.com
- [✔️] own environment 

If you need more info, then let me know which one.

**Comment by rskrzypczak** [comment]
If this information is missing, the update probably has failed.
The place where the update is triggered does not matter.
It looks like the update was interrupted at some point.
Verify the server configuration and retry the update.

This is not an application or update package bug, so I close the issue.
If you have any comments, please include more information, the server configuration and logs.
