### ISSUE TITLE
[PL] ADODB - jak użyć w zewnętrznym skrypcie?

### ISSUE THREAD

**Issue by bwiatrni** [YetiForceCompany/YetiForceCRM#1639]
```php
require_once 'config/config.inc.php';
require_once 'config/performance.php';
require_once 'include/database/PearDatabase.php';

$adb = PearDatabase::getInstance();
$result = $adb->query("SELECT * FROM `vtiger_account`");
$data = $adb->fetchByAssoc($result);
```

Warning: array_map() expects parameter 1 to be a valid callback, function 'to_html' not found or invalid function name in /home/niteamse/domains/yeti.niteamse.seo-linuxpl.com/public_html/include/database/PearDatabase.php on line 742

fetch zwraca NULL za każdym razem

**Comment by mariuszkrzaczkowski** [comment]
include_once 'include/main/WebUI.php';

$adb = PearDatabase::getInstance();
$result = $adb->query("SELECT * FROM `vtiger_account`");
$data = $adb->fetchByAssoc($result);
