### ISSUE TITLE
[bug] It is not possible to print lists in pdf from description/comment fields

### ISSUE THREAD

**Issue by dextras** [YetiForceCompany/YetiForceCRM#16408]
# 🐞 bug report

### ⁉️ Describe the bug
It is not possible to print lists in pdf from description/comment fields. 

### 🔥 How to trigger the error

1. Go to Sales Invoices
2. edit comments field and add list (either ol or ul)
3. Generate PDF

### 👎 Actual Behavior
Generated PDF does not contain list content at all.

### 👍 Expected Behavior
Lists are printed as visible in web.

### 👷 Testing

- ✔️ I confirm that I tested it at https://gitstable.yetiforce.com
- ✔️ I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![image](https://user-images.githubusercontent.com/7486027/187156014-b72aa846-23fe-4e97-8866-3dc2ac7483da.png)
![image](https://user-images.githubusercontent.com/7486027/187156066-beeb5e98-c722-4b0f-af53-a26ec48c39d7.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
N/A

### 🌍 Your Environment

My env does not matter that much as the problem also occurs on gitdeveloper and gitsable :)

**Comment by vovpff** [comment]
YF pdf doesn't support lists. This know bug

**Comment by dextras** [comment]
> YF pdf doesn't support lists. This know bug

Thanks for information. Now when you mentioned that I can see it in the list of TODOs:
![image](https://user-images.githubusercontent.com/7486027/187672029-aeedffff-9933-4d6c-87e3-59b9b46fd786.png)
