### ISSUE TITLE
[UpdatePackages] Error after the system update.

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#1640]
After the update finishes a message appears -” System has been updated successfully.” Upon clicking the finish button a white screen with an error message shows up - “ Invalid request - Response For Illegal Access.”
![update1](https://cloud.githubusercontent.com/assets/10221999/8930386/cd3d0d1c-352d-11e5-8652-ea3fa164f4e3.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/e4b4f7ab40b4913d32c0f8b4cce8233cb6f5527a
https://github.com/YetiForceCompany/UpdatePackages/commit/9e531280004a427b40b3ec83a4dc1809c9a79c91
