### ISSUE TITLE
[bug] Some modules still use the deprecated strfime

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#16421]
# 🐞 bug report

### ⁉️ Describe the bug

There are still some modules that use the deprecated function `strfime`, making the code not 100% php 8.1 compliant. Some can be corrected, some have to me addressed by class vendors.

This is how I found out:
![strftime-warning](https://user-images.githubusercontent.com/10230144/187416646-d3d0623e-cb59-45e0-8ee7-961a714ce170.jpg)

This is what php says:
![strftime-php](https://user-images.githubusercontent.com/10230144/187416725-f22b37d0-b744-4086-b87f-bb204cf84fb6.jpg)

This is where I found additional uses:
![strftime-php8](https://user-images.githubusercontent.com/10230144/187416763-e7c36dc6-52ec-4f2b-bd46-c4bd435ce64d.jpg)

### 🔥 How to trigger the error

1. Execute any command that calls any of the functions still using strftime, as shown above.
2. See error

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4.0|
| PHP                                 |     8.1.9           |
| Service Pack version                |  v2              |

**Comment by rskrzypczak** [comment]
Fixed in YF7
