### ISSUE TITLE
Cannot create Opportunities after update form 6.3.0 to YetiForce CRM 6.4 Service Pack v4[bug] 

### ISSUE THREAD

**Issue by bzyk667** [YetiForceCompany/YetiForceCRM#16428]
# 🐞 bug report

### ⁉️ Describe the bug

After upgrade i cannot add new Opportunities because after clicking on account search icon there is no request beeing made

![obraz](https://user-images.githubusercontent.com/17744321/187890632-9dd5d526-6ade-4620-bbec-fa86488ede76.png)

### 🔥 How to trigger the error

![YT](https://user-images.githubusercontent.com/17744321/187890088-a7c3e65a-5b99-4734-b91e-7bfb61d14c5f.gif)

1. Go to 'Sales -> Opportunities'
2. Click on 'Add record -> Accoount'

### 👎 Actual Behavior

No Acoou8nt list is displayed

### 👍 Expected Behavior

Account list displayed

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![obraz](https://user-images.githubusercontent.com/17744321/187891600-73127894-602d-4827-8c89-a31aeda9a3ba.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

there's nothing in logs 

* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4
| Web server (name and version)       |       Apache/2.4.37         |
| PHP                                 |     PHP 7.4.30           |
| Browser (name and version)          |        Firefox 104.0.1         |
| Operating System (name and version) |      4.18.0-348.20.1.el8_5           |
| Database (name and version)         |      MariaDB Server|10.3.32-MariaDB           |
| Service Pack version                |         YetiForce CRM 6.4 Service Pack v4       |

**Comment by mariuszkrzaczkowski** [comment]
logs

**Comment by rskrzypczak** [comment]
Did you reload the files into your browser's cache? https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-clear-browser-cache
Did you read the notes?https://github.com/YetiForceCompany/UpdatePackages/blob/master/YetiForce%20CRM%206.x.x/6.3.0_to_6.4.0/license.txt#L13

**Comment by bzyk667** [comment]
> Did you reload the files into your browser's cache? https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-clear-browser-cache 

Yes i reloaded browser's cache,

Did you read the notes?https://github.com/YetiForceCompany/UpdatePackages/blob/master/YetiForce%20CRM%206.x.x/6.3.0_to_6.4.0/license.txt#L13

Yes i read the notes and all mentioned modules there were in basic mode.

Bug is only it [Opportunities]

I rest of modules in sales like sales order  everything is working fine

**Comment by bzyk667** [comment]
> logs

 cat /var/www/html/cache/logs/update.log

YetiForce CRM 6.3 SecurityFix v8 - 2022-03-25 13:38:26
 |
2022-03-25 13:38:33 (6.21) |
YetiForce CRM 6.4.0 v3 - 2022-08-30 07:50:43
 |
2022-08-30 07:50:57 (14.52) |
YetiForce CRM 6.4 Service Pack v4 - 2022-08-30 07:52:26


 cat /var/www/html/cache/logs/updateLogsTrace.log
YetiForceUpdate::update | 2022-03-25 13:38:26
YetiForceUpdate::updateData | 2022-03-25 13:38:31
[INFO] batchUpdate: ['affected'=>40,'all'=>41]
YetiForceUpdate::updateData | 2022-03-25 13:38:31 | 0 mim.
YetiForceUpdate::createConfigFiles | 2022-03-25 13:38:31
YetiForceUpdate::createConfigFiles | 2022-03-25 13:38:31 | 0 mim.
YetiForceUpdate::update | 2022-03-25 13:38:31 | 0.08 min
YetiForceUpdate::postupdate | 2022-03-25 13:38:32
YetiForceUpdate::postupdate | 2022-03-25 13:38:32 | 0 min
YetiForceUpdate::update | 2022-08-30 07:50:43
YetiForceUpdate::removeModules OSSPasswords | 2022-08-30 07:50:43
YetiForceUpdate::removeModules | 2022-08-30 07:50:43 | 0 min
YetiForceUpdate::roundcubeUpdateTable | 2022-08-30 07:50:43
YetiForceUpdate::roundcubeUpdateTable | 2022-08-30 07:50:44 | 0.01 min
YetiForceUpdate::updateTargetField | 2022-08-30 07:50:44
YetiForceUpdate::updateTargetField | 2022-08-30 07:50:44 | 0 min
YetiForceUpdate::addFields | 2022-08-30 07:50:48
YetiForceUpdate::addFields | 2022-08-30 07:50:48 | 0 mim.
YetiForceUpdate::addActionMapping | 2022-08-30 07:50:48
YetiForceUpdate::actionMapp | 2022-08-30 07:50:48
YetiForceUpdate::actionMapp | 2022-08-30 07:50:49 | 0.02 mim.
YetiForceUpdate::addActionMapping | 2022-08-30 07:50:49 | 0.02 min
YetiForceUpdate::addModules | 2022-08-30 07:50:49
  [INFO] Add module:SMSTemplates
YetiForceUpdate::addModules | 2022-08-30 07:50:50 | 0.03 min
YetiForceUpdate::smsNotifier | 2022-08-30 07:50:50
  [INFO] Add picklist values:PLL_SENT,PLL_QUEUE,PLL_REPLY
  [INFO] Delete block: StatusInformation
  [INFO] Added new block: BL_SMS_CONTENT
YetiForceUpdate::addFields | 2022-08-30 07:50:51
YetiForceUpdate::addFields | 2022-08-30 07:50:51 | 0 mim.
YetiForceUpdate::smsNotifier | 2022-08-30 07:50:51 | 0.01 min
YetiForceUpdate::setRelations | 2022-08-30 07:50:51
YetiForceUpdate::setRelations | 2022-08-30 07:50:51 | 0 mim.
YetiForceUpdate::updateData | 2022-08-30 07:50:51
  [INFO] batchDelete: ['affected'=>3,'all'=>2]
  [INFO] batchInsert: ['affected'=>10,'all'=>10]
  [INFO] batchUpdate: ['affected'=>57,'all'=>196]
YetiForceUpdate::updateData | 2022-08-30 07:50:52 | 0.02 mim.
YetiForceUpdate::picklistDependency | 2022-08-30 07:50:52
  [INFO] dependencies were recreated: 2
YetiForceUpdate::picklistDependency | 2022-08-30 07:50:52 | 0 mim.
YetiForceUpdate::update | 2022-08-30 07:50:52 | 0.15 min
YetiForceUpdate::postupdate | 2022-08-30 07:50:56
YetiForceUpdate::createConfigFiles | 2022-08-30 07:50:56
YetiForceUpdate::createConfigFiles | 2022-08-30 07:50:57 | 0 mim.
YetiForceUpdate::updateMailConfiguration | 2022-08-30 07:50:57
YetiForceUpdate::updateMailConfiguration | 2022-08-30 07:50:57 | 0 min
YetiForceUpdate::postupdate | 2022-08-30 07:50:57 | 0 min

**Comment by mariuszkrzaczkowski** [comment]
1 Run full logs,
2 run error
3 attach logs
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging

**Comment by rskrzypczak** [comment]
Turn on the console (F12 chrome) and refresh the page, something should appear here.
Enable application logs as @mariuszkrzaczkowski mentioned.
Didn't you create any custom stuff for this module?
In your screenshot you can see that wysywig is not loading and probably styles, because the star is not red :)

**Comment by bzyk667** [comment]
I'm attaching logs:
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/9487222/system.log)

I have the same problem with datepicker in start date
![datepicker](https://user-images.githubusercontent.com/17744321/188374194-edc208e4-f611-46d1-9582-190f44f19357.gif)

also i have red dots 📦 
![obraz](https://user-images.githubusercontent.com/17744321/188374577-375c8607-2070-4074-be92-f95b32dd906f.png)

but rest of the switches works
![obraz](https://user-images.githubusercontent.com/17744321/188373798-fc5e978c-cf63-4d64-b492-eec720122809.png)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/16555#issuecomment-1268209117
