### ISSUE TITLE
[bug] Connection to IMAP in OSSMailScanner fails in php 8.1 because of change in imap_open return type

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#16429]
# 🐞 bug report

When running YetiForceCRM 6.4.0 v4 with php 8.1.10, the `OSSMailScanner` no longer works because the return type of function `imap_open` has changed from `resource` to `IMAP\Connection` and the code tests with `\is_resource` if a connection has been opened.

Rather than testing `\is_resource($mbox)` if the imap connection has been opened, the test should be `$mbox !== false`.

![type-change](https://user-images.githubusercontent.com/10230144/188141109-582b8f56-79c1-47a2-ad93-6928a8c33984.jpg)

This is twice the case:
![code](https://user-images.githubusercontent.com/10230144/188141410-bb224df0-638a-4d42-9428-42f541d35c8f.jpg)

**Comment by rskrzypczak** [comment]
Thanks, I will add just for the sake of clarity that YetiForce version 6.4 does not support php version 8.1 :)

**Comment by diderich** [comment]
You write on your website that it has been tested using 8.1 (I assumed that when it has been tested with a version, that the version
 is supported). You even mention 8.1.x on the configuration page.

![php-8 1](https://user-images.githubusercontent.com/10230144/188143374-5e098e29-7d3a-48b4-94a7-ea18abc85e6c.jpg)

![dev](https://user-images.githubusercontent.com/10230144/188143399-803ae781-1245-4987-bc03-e6f943adc605.jpg)

**Comment by mariuszkrzaczkowski** [comment]
I corrected the description on the home page,
as you can see in CRM it says that it is in the development stage
We know a few bugs in php 8.1 we will fix them.
We are developing tests to detect them, see: https://github.com/YetiForceCompany/YetiForceCRM/actions/runs/2978224375

**Comment by rskrzypczak** [comment]
Yes, it can be a little confusing :)
Note (dev), as I believe, is to inform here that it is for development environments, as it is still in the implementation phase.
So feel free to report bugs with php 8.1 :)

**Comment by diderich** [comment]
I read the `dev` as related to php (you were using a development version of php), not that the dev related to the crm system ;-)

**Comment by rskrzypczak** [comment]
That's why I mentioned it could be confusing :)
We will fix this in the next version.

**Comment by rskrzypczak** [comment]
Fixed in YF7 ;)
