### ISSUE TITLE
[bug] Json encoding is missing in Workflows / Step 2

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#16420]
# 🐞 bug report

### ⁉️ Describe the bug

As shown in the image below, the `\App\Json` encoding is missing for the field `schannualdates` (yellow), whereas it is correctly available for `schdayofweek` and `schdayofmonth`:

![bug](https://user-images.githubusercontent.com/10230144/187395029-da1fb304-1f53-45bc-aa14-8608faaf45dd.jpg)

### 🔥 How to trigger the error

1. Create a new or edit an existing workflow.
2. See warnings in `errors.log`

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com
- [x] this cannot be tested on https://gitstable.yetiforce.com or https://gitdeveloper.yetiforce.com as no access to `errors.log` is provided
### 📷 Screenshot of configuration

Not relevant.
### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4.0
| Web server (name and version)       |     8.1.9          |
| Service Pack version                |        v4        |

**Comment by mariuszkrzaczkowski** [comment]
It's not a bug, it's okay.
Look:
![image](https://user-images.githubusercontent.com/10198654/187402485-6c3b6583-bcad-4690-807d-89740da6579e.png)
![image](https://user-images.githubusercontent.com/10198654/187402320-acaee970-5dfb-4803-929a-59d4a3be4619.png)

and the saving action is explode, not json
https://github.com/YetiForceCompany/YetiForceCRM/blob/9dee1afd38fe4c250b2b326c73d077261624ecd0/modules/Settings/Workflows/actions/Save.php#L59

**Comment by mariuszkrzaczkowski** [comment]
Thanks that you watch over the code 
![image](https://user-images.githubusercontent.com/10198654/187403253-71851b70-c1af-4566-b0f6-488f668d9d38.png)

**Comment by diderich** [comment]
Then the solution may not be the Json encoding!

If I am executing the following workflow set-up
![step2](https://user-images.githubusercontent.com/10230144/187416063-15e88042-86ff-4f38-9a8b-a8a9a9cca1f3.jpg)

I get the following error/warning in the `errors.log` file.
![workflow-warning](https://user-images.githubusercontent.com/10230144/187416130-7488fb6e-270a-40a9-9197-e7872855aebb.jpg)

which I do not get when adding the Json encoding. That is the reason I though the encoding was the issue!?

**Comment by mariuszkrzaczkowski** [comment]
include the complete error message

**Comment by diderich** [comment]
Sorry, my mistake (used tail instead of less):
![error](https://user-images.githubusercontent.com/10230144/187421548-738ee407-6448-4747-bdb7-0fcec377a322.jpg)

In yellow the line on which the error occurs in the rendered tpl file:
![error2](https://user-images.githubusercontent.com/10230144/187421984-4048fd29-80e8-4639-a8e1-13d69f960fcb.jpg)
