### ISSUE TITLE
[bug] Update from Release 6.1.0 to 6.4.0

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#16436]
# 🐞 bug report

### ⁉️ Describe the bug

I am currently using YetiForce CRM 6.1 Service Pack v8. I want to upgrade to YetiForce CRM 6.4. I am first trying to upgrade to YetiForce CRM 6.2 via System Menu -> Logs -> Updates
http://192.168.1.244/crm/yf/index.php?parent=Settings&module=Updates&view=Index

![1](https://user-images.githubusercontent.com/12723595/188440527-2275f978-b0a1-4dc0-b6d3-2c2e7f657d99.png)

I have downloaded Package for YetiForce CRM 6.2
![image](https://user-images.githubusercontent.com/12723595/188440805-89bfa0f9-268a-4ede-9f93-1828731ccffe.png)

On Installation, I get below screen
![3](https://user-images.githubusercontent.com/12723595/188440933-2f6ac272-3ad6-4c10-977d-b82ed3a63f41.png)

It start updating but gives error after 45-60 seconds
![4](https://user-images.githubusercontent.com/12723595/188441004-0948c7b6-49e3-4068-9dc9-cc3189178fc3.png)

After this program stops working, top header and bottom footer does not load
![5](https://user-images.githubusercontent.com/12723595/188441149-c9abe4de-1048-4ba5-a237-645f8bb7fcab.png)

### 🔥 How to trigger the error

**Mentioned in above screen shots**

### 👎 Actual Behavior
![4](https://user-images.githubusercontent.com/12723595/188441629-3c0bb31c-692d-47d4-9896-ab3ad906b40c.png)

### 👍 Expected Behavior

**Expected to update system to 6.2.0**

### 👷 Testing

- [X ] I confirm that I tested it at https://gitstable.yetiforce.com - **Can not replicate here**
- [ X] I confirm that I tested it at https://gitdeveloper.yetiforce.com - **Can not replicate here**

### 📷 Screenshot of configuration
![6](https://user-images.githubusercontent.com/12723595/188441711-85491788-2c05-4428-9ff4-aa206d63b116.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0 Service Pack 8
| Web server (name and version)       |                |
| PHP                                 |     php 7.3           |
| Browser (name and version)          |   Google Chrome	105.0.5195.102 (Official Build) (64-bit) (cohort: 105_Win_102)    |
| Operating System (name and version) |       CentOS 7.9.2009(Py3.7.8)         |
| Database (name and version)         |     MySQL 8.0.20           |
| Service Pack version                |        8        |

### ❓ Additional context
**Can not figure out how to trace this issue**

I have also tried to copy files from 6.1.0_to_6.2.0_v3 directly, but failed. **is it right approach ?**

**Is there any manual steps / alternate way than above which i can do one by one and update system ?**

Please help me to solve this problem.

Regards
**Jeevan Pendhari**

**Comment by mariuszkrzaczkowski** [comment]
correct the server configuration, what is red
attach all required logs

**Comment by JEEVAN28** [comment]
Ok, I am cross verifying server configuration with https://gitstable.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index

I have noticed that 
opcache.revalidate_freq cron (CLI) value on my server is 3 and on gitstable same is 0. how to correct this value ?


As I have mentioned log files as required from catche folder are not generated, hence not provided, do i need to provide from any other folder ?

Regards
Jeevan Pendhari




</body>
</html>

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski I have tried to modify configuration, few red points are updated but few are not changing even though php.ini is updated.

I do not know how to update **System headers configuration**, please help in this.

![ConfReport (3)](https://user-images.githubusercontent.com/12723595/188614829-4a856133-551a-4d5f-888c-94de71862c44.png)


**Can you assist to update manually instead of using update method given in package, I think large database has issue to update**

Regards
Jeevan Pendhari

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski 

Can you assist to update manually instead of using update method given in package, your help will allow me to upgrade to new features.

Regards
Jeevan Pendhari

**Comment by JEEVAN28** [comment]
Can you please assist to update manually?

**Comment by mariuszkrzaczkowski** [comment]
Your server configuration still needs to be improved,
Manual update will be very difficult, you would have to have a developer who knows the system very well and the changes to be made,
Your error is definitely in the logs, check the logs carefully, but first make sure that they are active (because the attached report shows that they do not work).

**Comment by JEEVAN28** [comment]
Ok, will check

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski correcting FPM records solved this issue. https://github.com/YetiForceCompany/YetiForceCRM/issues/16616

Thanks for your help

Regards
Jeevan Pendhari
