### ISSUE TITLE
[BUG] Date Field

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1644]
The field can not be edited, it's systematic field
![animation 78](https://cloud.githubusercontent.com/assets/1402355/8933419/179580fa-355c-11e5-85e2-bf8d61a07846.gif)

**Comment by rskrzypczak** [comment]
fields such as 'Modified Time', 'Created Time' ect. should not be visible in edition. 
Added new parameter 'CHANGE_VISIBILITY' which allows setting the visibility.
This option will be turned off by default.
https://github.com/YetiForceCompany/YetiForceCRM/commit/0c2a8fd3a17c35175e740db621a0b6211297d697
