### ISSUE TITLE
[bug] Unbale to update from 6.3 to 6.4

### ISSUE THREAD

**Issue by Ilamparithi-Tamizhanangu** [YetiForceCompany/YetiForceCRM#16441]
Hi,

When i try to update the yetiforce from 6.3 to 6.4, i am getting the error as "Invalid or uninitialized Zip object".

![image](https://user-images.githubusercontent.com/96602176/189068451-cb2b30e3-bd68-4ff6-b38d-67e773c7b1b1.png)

Could you please guide me how to install the updates. 

Thanks & Regards,
Rajasekaran.

**Comment by Marco31Bike** [comment]
check if you have all php extensions
