### ISSUE TITLE
Calendar : Wrong day for the date since update to 6.4 [bug] 

### ISSUE THREAD

**Issue by jmginfor** [YetiForceCompany/YetiForceCRM#16440]
# 🐞 bug report

### ⁉️ Describe the bug

The date ( September 6th) doesn't match the day of the week. It's supposed to be Tuesday.

![2022-09-06 18_14_04-Calendar](https://user-images.githubusercontent.com/66257334/188749872-8b2f349b-f0e4-4aac-9ae3-087b989c74f7.png)

- [✔️  ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ✔️ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![2022-09-06 18_18_23-Server configuration](https://user-images.githubusercontent.com/66257334/188750370-17936f4b-fc19-49bf-b450-850b69457592.png)

**Comment by rskrzypczak** [comment]
What time zone do you have set on your computer?

**Comment by jmginfor** [comment]
Eastern time. (Montréal, Toronto, NewYork) how this is linked?

**Comment by rskrzypczak** [comment]
Browsers, including the calendar, take into account the time zone set in your operating system.
For example, I don't have this problem in my time zone :)
![image](https://user-images.githubusercontent.com/10221999/188791879-990d9cfb-c6a8-4df0-8cf4-94e4833d6dab.png)
Thanks for reporting, we'll take a closer look at it.

**Comment by jmginfor** [comment]
Oh ok. Thank for answering. I work on 2 differents instances and both are in Eastern time and have the same problem. 

In the meantime, can I do something to correct that? 

Thank you!

**Comment by rskrzypczak** [comment]
This is a bug of the fullcalendar library itself, see: https://github.com/fullcalendar/fullcalendar/issues/5854#issuecomment-1085724560
If you want to upload a quick fix, turn off .min for js (config/Developer.php) and modify the js files as indicated here: https://github.com/YetiForceCompany/YetiForceCRM/commit/02e2cdfda918e124602d489166e7824fc5e236d2

**Comment by Patrickg56** [comment]
It is over a year since this bug was reported, but it does not seem to be fixed. I have the exact same problem. My time zone is PDT Gmt -8 and my computer is set to that. The calendar seems to think I am in a eastern Europe timezone.
