### ISSUE TITLE
[bug] Generate one pdf file returning error

### ISSUE THREAD

**Issue by ArniSamano** [YetiForceCompany/YetiForceCRM#16457]
While generating PDF (selecting Generate one PDF file) system returning error: "Unable to find pointer to xref table"
Checked on latest stable version (git and local).

**Comment by s2b-git** [comment]
Same here. Cannot find why

**Comment by jmginfor** [comment]
Same here but only with a lot a files to be generated. If I export it in a Zip file, it's work fine, but if I export it in one single pdf file, I got this error.

**Comment by konadrian** [comment]
Fixed https://github.com/YetiForceCompany/YetiForcePDF/commit/38ce006a03e250821c25c4d3359fcb680e161f03
