### ISSUE TITLE
[bug] Issue with SMS Provider Server API Key

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#16479]
Hi,

I'm working on creating a new provider file for OVH SMS, I found 2 issues regarding API_KEY.

1- Problem with getAuthorization() function in /app/Integrations/SMSProvider/Provider.php. 
$this->getAuthorization() does not return correct API_KEY, it returns a string which looks like it's not properly decrypt.

2- When you edit your SMS Provider server info in order to check if the API KEY is correct, display button is greyed out and copy button generate an error, see attached video recorded on https://gitdeveloper.yetiforce.com/

![sms_provider_password_issue](https://user-images.githubusercontent.com/2930560/190387577-87dc0a36-fa46-4d19-98d6-c6710ef01045.gif)

**Comment by rskrzypczak** [comment]
Fixed in YF 7.0.x
