### ISSUE TITLE
[bug] Custom module - dashboard error

### ISSUE THREAD

**Issue by ArniSamano** [YetiForceCompany/YetiForceCRM#16482]
When  you create new module, and trying to access Dashboard view, system showing error as per screenshot below. Confirmed on gitstable and local installation
![image](https://user-images.githubusercontent.com/105257433/190729315-0548c351-5710-424f-9554-9bcaa289b877.png)

**Comment by andmz221** [comment]
Me also noticed similar error on gitdeveloper

![image](https://user-images.githubusercontent.com/113221503/190811949-962de745-ebc9-4801-9e0f-985a1358d8b7.png)

**Comment by rskrzypczak** [comment]
Fix https://github.com/YetiForceCompany/YetiForceCRM/commit/e97dea8f2af761011b3ce008dbb692ce2e379778
