### ISSUE TITLE
personal module error

### ISSUE THREAD

**Issue by MixTecnico** [YetiForceCompany/YetiForceCRM#16480]
adding icon to a label, it gave me the following error

![image](https://user-images.githubusercontent.com/29989839/190421713-d8a868b3-3f14-45d8-ac24-1b9b1c6dbadf.png)

LOG de sistema
2022-09-15 10:22:24.7897 [error][] - Return value of Vtiger_Field_Model::getIcon() must be of the type array, string returned
TypeError: Return value of Vtiger_Field_Model::getIcon() must be of the type array, string returned in /home/incot/helpdesk.incotech.com.ar/modules/Vtiger/models/Field.php:1572
Stack trace:
#0 /home/incot/helpdesk.incotech.com.ar/cache/templates_c/basic/53a9e64326183aee3290650d6b880e9990bdda40_0.file.DetailViewLayout.tpl.php(80): Vtiger_Field_Model->getIcon()
#1 /home/incot/helpdesk.incotech.com.ar/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_632280b1df6799_00027439()
#2 /home/incot/helpdesk.incotech.com.ar/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#3 /home/incot/helpdesk.incotech.com.ar/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#4 /home/incot/helpdesk.incotech.com.ar/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#5 /home/incot/helpdesk.incotech.com.ar/cache/templates_c/basic/677411a3c85b7bb09948f3b2dadc8dfe22a909e1_0.file.Index.tpl.php(53): Smarty_Internal_Template->_subTemplateRender()
#6 /home/incot/helpdesk.incotech.com.ar/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_632280b1db1d10_14001405()
#7 /home/incot/helpdesk.incotech.com.ar/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#8 /home/incot/helpdesk.incotech.com.ar/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#9 /home/incot/helpdesk.incotech.com.ar/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
#10 /home/incot/helpdesk.incotech.com.ar/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#11 /home/incot/helpdesk.incotech.com.ar/include/runtime/Viewer.php(210): Smarty_Internal_TemplateBase->display()
#12 /home/incot/helpdesk.incotech.com.ar/modules/Settings/LayoutEditor/views/Index.php(95): Vtiger_Viewer->view()
#13 /home/incot/helpdesk.incotech.com.ar/modules/Settings/LayoutEditor/views/Index.php(30): Settings_LayoutEditor_Index_View->showFieldLayout()
#14 /home/incot/helpdesk.incotech.com.ar/include/main/WebUI.php(188): Settings_LayoutEditor_Index_View->process()
#15 /home/incot/helpdesk.incotech.com.ar/index.php(26): Vtiger_WebUI->process()
#16 /home/incot/helpdesk.incotech.com.ar/public_html/index.php(13): require('/home/incot/hel...')
#17 {main}
 - 0 include/main/WebUI.php:191  >>  App\Log->error('Return value of Vtiger_Field_Model::getIcon() must be of the type array, string returned
TypeError: Return value of Vtiger_Field_Model::getIcon() must be of the type array, string returned in modules/Vtiger/models/Field.php:1572
Stack trace:
#0 cache/templates_c/basic/53a9e64326183aee3290650d6b880e9990bdda40_0.file.DetailViewLayout.tpl.php(80): Vtiger_Field_Model->getIcon()
#1 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_632280b1df6799_00027439()
#2 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#3 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#4 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#5 cache/templates_c/basic/677411a3c85b7bb09948f3b2dadc8dfe22a909e1_0.file.Index.tpl.php(53): Smarty_Internal_Template->_subTemplateRender()
#6 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_632280b1db1d10_14001405()
#7 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#8 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#9 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
#10 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#11 include/runtime/Viewer.php(210): Smarty_Internal_TemplateBase->display()
#12 modules/Settings/LayoutEditor/views/Index.php(95): Vtiger_Viewer->view()
#13 modules/Settings/LayoutEditor/views/Index.php(30): Settings_LayoutEditor_Index_View->showFieldLayout()
#14 include/main/WebUI.php(188): Settings_LayoutEditor_Index_View->process()
#15 index.php(26): Vtiger_WebUI->process()
#16 public_html/index.php(13): require(\'/home/incot/hel...\')
#17 {main}')
 - 1 index.php:26  >>  Vtiger_WebUI->process()
 - 2 public_html/index.php:13  >>  require('index.php')
2022-09-15 10:22:24.7035 [info][[application]] - 
$_GET = ['module'=>'LayoutEditor','parent'=>'Settings','view'=>'Index','sourceModule'=>'Service']
$_COOKIE = ['language'=>'es','YTSID'=>'mkpsl681m****3orfd7c','roundcube_sessid'=>'aubqog***07d5e1fciai']
$_SESSION = ['CSP_TOKEN'=>'7d367651549f24de5*******59397','last_activity'=>166****48144.70611,'UserAuthMethod'=>'PASSWORD','authenticated_user_id'=>5,'app_unique_key'=>'cd********caf02db7652d','user_name'=>'*******','full_user_name'=>'*****d','fingerprint'=>'d520c7a8-42******c56b97ec','user_agent'=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36','language'=>'es-ES','lvs'=>['HelpDesk'=>['sortby'=>['createdtime'=>'DESC'],'viewname'=>13],'Service'=>['sortby'=>['createdtime'=>'DESC'],'viewname'=>'148']],'SystemWarnings'=>true]
_HEADERS = ['X-Varnish'=>'591975','Accept-Encoding'=>'gzip','X-Forwarded-For'=>'192.168.88.55','Cookie'=>'language=es; YTSID=mkpsl681mk****orfd7c; roundcube_sessid=aubqo****d5e1fciai','Accept-Language'=>'es-US,es-AR;q=0.9,es-419;q=0.8,es;q=0.7,pl;q=0.6','Sec-Fetch-Dest'=>'document','Sec-Fetch-User'=>'?1','Sec-Fetch-Mode'=>'navigate','Sec-Fetch-Site'=>'none','Accept'=>'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9','User-Agent'=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36','Upgrade-Insecure-Requests'=>'1','Sec-Ch-Ua-Platform'=>'"Windows"','Sec-Ch-Ua-Mobile'=>'?0','Sec-Ch-Ua'=>'"Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"','X-Forwarded-Proto'=>'https','X-Forwarded-Server'=>'helpdesk.incotech.com.ar','X-Forwarded-Host'=>'helpdesk.incotech.com.ar','X-Real-Ip'=>'192.168.88.55','Host'=>'helpdesk.incotech.com.ar','Authorization'=>'']
$stability = ['error_reporting'=>'E_ERROR | E_WARNING | E_PARSE | E_NOTICE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_USER_ERROR | E_USER_WARNING | E_USER_NOTICE (22527)','default_socket_timeout'=>'60','max_input_vars'=>'1000','auto_detect_line_endings'=>'Off']
$security = ['session.use_strict_mode'=>'Off','expose_php'=>'On']
$libraries = ['ldap'=>'LBL_NO','OPcache'=>'LBL_NO','apcu'=>'LBL_NO','imagick'=>'LBL_NO']
$database = ['character_set_database'=>'latin1']
$performance = ['opcache.enable'=>'Off','opcache.enable_cli'=>'Off','realpath_cache_ttl'=>'120','mysqlnd.collect_statistics'=>'On']
$environment = ['error_log'=>false,'openssl.cafile'=>false,'openssl.capath'=>false]
====================================================================================================================================

the module works well, but I don't understand why it gives me an error when editing the fields, could you give me a hand!

![image](https://user-images.githubusercontent.com/29989839/190422003-96eea85a-5406-4a3f-ba6c-70e9440fec88.png)

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/190456513-136a48d4-f3b7-4c81-a111-76c9a5a60ca0.jpg)

**Comment by s2b-git** [comment]
Experienced before too. Delete icon entry in database and do it again. Worked for me.
