### ISSUE TITLE
[BUG] Add Contact (Field First Name)

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1650]
How to disable or hide this field treatment?

![animation 84](https://cloud.githubusercontent.com/assets/1402355/8934661/1edfca86-3562-11e5-9cb8-f4ddeed24de6.gif)

**Comment by waw555** [comment]
In Vtiger 6.0, this field can be disabled in the profile.

**Comment by paula-w** [comment]
Do you want to disable the field with honorifics (Mr / Mrs, etc) only?  Or do you want to disable the whole first name field? 
Hiding the field in the profile works correctly, but it will be visible for the admin.
