### ISSUE TITLE
[bug] import stuck on Thai characters

### ISSUE THREAD

**Issue by Marshal4582** [YetiForceCompany/YetiForceCRM#16504]
I am testing importing for a while and I can confirm, that built-in import cannot continue if Account name is written in: Japanese/Chinese/Thai characters.
I have tried 12 times on the set of very well structured Accounts data
Logs shows noting.
If all accounts are in Roman chars things are OK

M.

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/191465029-e3de490b-cf8d-4287-b39c-32915b28cdd7.jpg)
