### ISSUE TITLE
[bug] Import disturbed on random basis

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#16518]
Latest stable version
Powerful bare metal fully configured in line with Yetiforce recommendations (PHP, extensions, memory etc)

On random basis (what patter I have no idea) and when import is successful, table u_yf_import_1 is not removed automatically preventing subsequent imports.
This issue is a significant blocker, as users here importing data on daily basis. 
Imported data is always in necessary shape as it coming through import template.
Reporting it as a bug, but maybe I missed something?

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/192154187-a1f69fc5-de78-42a2-b943-50702425e515.jpg)

**Comment by mariuszkrzaczkowski** [comment]
in order to be able to fix a bug, we need to be able to cause it, without it, it's looking in the dark
