### ISSUE TITLE
[bug] When try to login with correct password and username don't redirect me to next page

### ISSUE THREAD

**Issue by GournieGR** [YetiForceCompany/YetiForceCRM#16515]
Hi, 

When i'm in login page and put my username and password (these credentials is correct) the site don't redirect me to the new page but hold me to login page. In my server don't produce error logs for solve that.

**Comment by rskrzypczak** [comment]
clear browser cache and cookies: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-clear-browser-cache

**Comment by GournieGR** [comment]
nothing happened

Στις Παρ 23 Σεπ 2022 στις 1:37 μ.μ., ο/η rskrzypczak <
***@***.***> έγραψε:

**Comment by rskrzypczak** [comment]
You probably have a problem with the session, maybe file permissions.
Check if session files are created in `cache/session`

**Comment by GournieGR** [comment]
Now i have this error after login
[image: image.png]

Στις Παρ 23 Σεπ 2022 στις 4:55 μ.μ., ο/η rskrzypczak <
***@***.***> έγραψε:

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/192023465-2448806f-5fc6-45ef-971f-5dbc4ee9adf1.jpg)
