### ISSUE TITLE
[BUG] Add Record

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1651]
Opens description, not top of the page
![animation 85](https://cloud.githubusercontent.com/assets/1402355/8934746/84f4896a-3562-11e5-9e9c-6b5891a38a91.gif)

**Comment by konadrian** [comment]
I checked it with another programmer, this kind of event doesnt exist in here. I checked it on chrome and ff agents

**Comment by waw555** [comment]
I just checked, there is no problem if I will again take up the issue.
