### ISSUE TITLE
[bug] [PL] Nie moge dodać filtrów po aktualizacji z 6.2 na 6.4 v6

### ISSUE THREAD

**Issue by Sall2** [YetiForceCompany/YetiForceCRM#16543]
Dzień dobry,
po wykonanej aktualizacji systemu mam następujący problem:
Po kliknięciu "Dodaj filtr" system zawiesza się na "Proszę czekać"

Debug w przeglądarce zgłasza błąd jak w załączniku, proszę o pomoc.

![Zrzut ekranu 2022-10-03 124652](https://user-images.githubusercontent.com/58420665/193560528-654ffd1b-622e-4714-ab3d-b8e85994b0f2.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/193561372-0d99962a-cc21-4e01-8743-0ef6b4898128.jpg)

**Comment by Sall2** [comment]
1. Nie znalazłem takiego problemu
2. Tak jak opisałem w oryginalnym poście, przed aktualizacją nie było problemu
3. Wywołać go można poprzez próbę dodania nowego filtru
4. Ten sam błąd występuje na gitstable.yetiforce.com i gitdeveloper.yetiforce.com
5. Serwer jest prawidłowo skonfigurowany, instancja w wersji 6.2 działa ok.

Myślę, że skoro nie działa na serwerach z pkt 4 to więcej nie musze pisać :)
![Zrzut ekranu 2022-10-03 193521](https://user-images.githubusercontent.com/58420665/193644711-6fdd43f4-d051-4790-b1d2-cbe4b02907e4.png)

**Comment by Sall2** [comment]
Dodatkowo sprawdziłem, że dodając nowy filtr z pozycji list wszystko działa poprawnie, szczegóły na screenach
![Zrzut ekranu 2022-10-03 204954](https://user-images.githubusercontent.com/58420665/193657116-f9d59cc2-8644-40c4-9005-324b2e37edfe.png)
![Zrzut ekranu 2022-10-03 205018](https://user-images.githubusercontent.com/58420665/193657127-7750aeb3-e1f8-4c10-87ee-acfedb9c6597.png)
![Zrzut ekranu 2022-10-03 205043](https://user-images.githubusercontent.com/58420665/193657138-77fa7aaa-744e-4bb1-80ac-b36d9b437b32.png)
