### ISSUE TITLE
[bug] Calendar / Time Control filtering not working correctly for activity types and groups

### ISSUE THREAD

**Issue by QVinto** [YetiForceCompany/YetiForceCRM#16549]
# 🐞 bug report

### ⁉️ Calendar / Time Control filtering not working correctly for activity type and groups

- When trying to filter working time/holiday/sick day/ ... then there are always all records not only what i want to filter
- filtering group doeasnt work
- Fitlerring accounts in time control works fine ✔️

![image](https://user-images.githubusercontent.com/4982986/193742845-b9961617-9f57-438d-936f-99f0f6eb3e58.png)

### 🔥 How to trigger the error

1. Go to 'Calendar / Time Control module'
2. Filter 'Holiday'
3. Filter 'Groups'

### 👎 Actual Behavior

ot filtering correctly

### 👍 Expected Behavior

Filter onnly Holidays or Sick Days or anything else. Also it should filter group.

### 👷 Testing

- [ ✔️ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ✔️ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com
- [ ✔️ ] I confirm that I tested it on own server

### 📷 Screenshot of configuration

doeasnt matter because It is not working on gitstable and github

**Comment by areksolek** [comment]
In the current version, the problem does not occur.
