### ISSUE TITLE
[bug] After the 6.4 update, I can't create new customers

### ISSUE THREAD

**Issue by hisakiyo** [YetiForceCompany/YetiForceCRM#16555]
# 🐞 bug report

### ⁉️ Describe the bug

The confirm button on the add customer page is disabled, and it's impossible to perform additional actions on the page.

### 🔥 How to trigger the error

1. Go to index.php?module=Accounts&view=Edit
2. Fill in the required fields
3. See that the validate button is still disabled

### 👎 Actual Behavior
Button is disabled
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/34187647/194028873-c50b118a-d6af-42dc-8568-10673d6a3f9e.png">

### 👍 Expected Behavior
Button can be clicked
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/34187647/194028983-1ff250f1-ac0d-42a6-b1d7-d84f432b073a.png">

### 👷 Testing

- [no] I confirm that I tested it at https://gitstable.yetiforce.com
- [no] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

![ConfReport](https://user-images.githubusercontent.com/34187647/194029474-b42b66b8-9340-482a-80ff-4b6085465f3a.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4.0 |
| Web server (name and version)       |      Apache 2.4.38         |
| PHP                                 |        8.0.23        |
| Browser (name and version)          |          Brave Version 1.44.105 Chromium: 106.0.5249.91 (arm64)      |
| Operating System (name and version) |      MacOS 12.6          |
| Database (name and version)         |    MariaDB            |
| Service Pack version                |       YetiForce CRM 6.4 Service Pack v6         |

### ❓ Additional context
Here is the Javascript error:
<img width="1868" alt="image" src="https://user-images.githubusercontent.com/34187647/194029786-2e64341b-8694-47f8-a5ae-3b2b6330122b.png">

**Comment by rskrzypczak** [comment]
Duplicate: #16378, #16428
https://github.com/YetiForceCompany/UpdatePackages/blob/master/YetiForce%20CRM%206.x.x/6.3.0_to_6.4.0/license.txt#L13-L14

You most likely set the module type to advanced, which is an error. 
Please verify and fix if needed according to the instructions below. The change won't happen in real time, there will be a delay in accordance with the cron schedule on your server (make sure Cron is enabled - System configuration/Automation/CRON), it usually takes a couple of minutes. 
![image](https://user-images.githubusercontent.com/10221999/194032930-61a00aca-6610-41a1-80ee-8798f680eadd.png)
Once you're done remember to reload files to browser cache https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-clear-browser-cache
