### ISSUE TITLE
Products modules refactoring.

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#1656]
The following product modules are available in the system at the moment:

1. SalesOrder
2. PurchaseOrder
3. Quotes
4. Invoices
5. Calculations
6. Costs

The problem with these modules is that creating them requires modification of the system files [and we want to give you the ability to create these modules from the panel], and all the modules store products in the same table [which has no factual explanation], which might generate serious efficiency problems while dealing with a great number of documents, it also amounts to many restrictions, since different modules have different requirements.
Additionally, we want to start introducing new modules to the system, such as:

1. ProForma Invoice
2. Correction Invoice
3. Acceptance into warehouse
4. Release from the warehouse
5. Warehouse transfer
6. Pre-order of the goods
7. Etc.

Therefore we have to standardize that, to make it easier to create PDF files, among others.
Do you have any thoughts on this matter?

**Comment by waw555** [comment]
Please write in their own language, something I have written poorly understood translator

**Comment by reeid** [comment]
"The problem with these modules is that creating them requires modification of the system files"
 - I am not sure I got it.. at the moment those modules are part of the system...
What steps in changes are proposed?

**Comment by nikdejan** [comment]
I think that would be a step in the right direction. I myself need to create custom module with connection to products, like those modules which you mentioned and right now I can't do that.
I would also need the possibility to customize Line Items, to be able to add some custom fields. That way I could add arrival/departure dates, and what I'd sell as my product would actually be hotel reservation.
So I think two things should be implemented:
1. The ability to connect particular newly created module with products (line items) 
2. Ability to customize product module itself, including the way it fields are displayed in item details of newly created custom module (module of type Quotes, Invoice, ProformaInvoices etc).
This way we could achieve more generic behavior with lot more possibilities. Any module could bi quotelike and connected to product (or something productlike).
Does this make any sense?

**Comment by bpabiszczak** [comment]
@waw555 for you, new version ;)

Refactoring of the “Product” modules.

The following "Product" modules are now available in the system:
1. SalesOrder
2. PurchaseOrder
3. Quotes
4. Invoices
5. Calculations
6. Costs

The problem with these modules is that we must modify the system files to create these modules [and we want to give you the ability to create these modules from the panel], and all the modules put products in the same table [there is no reason to keep them in one place]. It might cause serious efficiency problems if we have many documents. It also causes many restrictions, because different modules have different requirements.

Additionally, we want to add new modules to the system, such as:
1. ProForma Invoice
2. Correction Invoice
3. Acceptance into warehouse
4. Release from the warehouse
5. Warehouse transfer
6. Pre-order of the goods
7. Etc.

We must standardize that, to make it easier to, for example, create PDF files.
Do you have any thoughts on this matter?

**Comment by echemik** [comment]
For me is important :
1. Calculate and show price net and gross in every item, and in summary when create invoice (and similar documents)
2. Auto choose deafult vat wage after add item
3. Remember product name in invoice document (eg. I create invoice, I change product name, this product name should not change on invoice)
4. Good working Web services for add, retrive, and update.

**Comment by florek41** [comment]
In my case important is:

1. Product manufacturing / creator (in calculations) - Bill Of Materials, Made for client request. It should have ability to show or hide list of materials for clients (leave only main product name). If you are interested in I have not finished project with UI for this functionality - let me know.
So new module - Materials ( I want to sell it, not only for use in BOM )

2. Allow to select default type of taxes (group or individual) in system config

3. Default tax selecting for products / services (now i need to select product and additionally select tax, even when product have specified only one tax)

4. Customization of Line Items, to be able to add fields

Correction Invoice - must have for me !

**Comment by waw555** [comment]
For my type of company will be comfortable following modules
Attire - Payroll (In this module should be the only services)
Contract - Creation of contracts with contractors (This module will goods and services)

More needs to be a module for kickback)))) (Russian only)

**Comment by zebrahosting** [comment]
This is not something we have to deal with in our CRM (webshop -> Magento) but this all looks pretty over the top to me. Creating new modules for things that look to me as status settings. 
Cleaning up code and clarifying table structure seems a good idea. So much is changing from the original that a few more non system modifications should not matter anymore.
With all this it is becoming more ERP than CRM, while the CRM part is not yet finished properly.
Guess if there is a need for it, it can be justified but otherwise: https://www.odoo.com

**Comment by reeid** [comment]
For now on, it scary to put YetiForce on production. Indeed, new functions could be introduced slower but that is a developer decision. When you dealing with millions of records you dont wanna upgrade system every two months especially when it touch deep system changes.... it too serious responsibility.
Waiting for YetiForce not GA but stable version where no future great changes will be presented except minor, cosmetic and security changes. All new stuff should come as extensions/modules with option to uninstall it.

**Comment by diderich** [comment]
It would be great if there would be a generic "Calculation" module from which all the stated modues could be derived. Ideally the module creation function should allow to create such a calculation type module. This would mean standardization and simplification of the code.

To make it "perfect" a similar approach should be taken for the Products and Services modules by greating a generic product type module (with a number of mandatory fields, like for example price, unit, etc.). It should be possible to add similar modules, for example an Expenses module to be used when invoicing of tracking travel costs or an Consumables module track consumable costs incurred but not charged to custimers.

In addition for each calculation type module, it should be posible to select which product type modules are allowed. For example, an quote would allow products and services, an invoice products, services and expenses, a costs would allow expenses and consumables.

**Comment by nikdejan** [comment]
This was exactly what I had in mind, but diderich explained better. :-) Instead of creating a tone of modules of which people will use mostly two or three, it's better to create flexible, generic customizable system. That is where real power (yeti power :-)) resides.

**Comment by reeid** [comment]
I really want drag it to production, but every cool idea just extending waiting time.... anyway you got my vote for base modules with ability to develop it in various directions

**Comment by SkavenKF** [comment]
I have also the problem that i would update a vt5.4 productiv system to yf, since version 1.0. But every "stable" yf release have bugs, process changes (ex. lost of contact) and a lot of changes.

I think we need a update/bugfixing strategie for the stable version, similar to the following.
Stable Version is 2.0.n, next 2.2.n, next 2.4.n and so on
Master/Developer 2.1.n, next 2.3.n, next, 2.5.n and so on
Update from 2.0 to 2.2, 2.2 to 2.4, etc. (for all patches x.x.n)

I vote for a refactoring for base modules for the next stable release with a functional update module and more flexibilty in customizing the process framework.
New functionalitys should be planned after this stable release (flexible calculation module, excel/calc integration for a complex calculation)

**Comment by bpabiszczak** [comment]
SkavenKF - invalid issue, move here: https://github.com/YetiForceCompany/YetiForceCRM/issues/1760

**Comment by florek41** [comment]
Few things more:

- for product we should have possibility to set **Buying (unit) Price**, **Commission Rate** (% or $) and **Selling price**. All those fields should be connected and when user enter values in two fields third will be calculated.

- Product buying price can be auto updated from **Purchase Order / Invoice**

- Product / service units defined in Calculation / Sales Order / Invoice

- As I mentioned earlier - Bill Of Material - i think it could be possible to configure product in calculation - add materials/products/services with units, quantity and price (if isn't definied).

- When unit is square meter/inch it would be great to have two fields for width and height (in materials and products)

**Comment by reeid** [comment]
Is there any progress in changing core code in relation to this discussion?

**Comment by bpabiszczak** [comment]
The module has been finished and added to gitdeveloper. Soon we will publish an article describing all its features. Thank you for your ideas.
