### ISSUE TITLE
[bug / YetiForceCRM installer] strtolower() and Locale::acceptFromHttp() report null values

### ISSUE THREAD

**Issue by VishwaJay** [YetiForceCompany/YetiForceCRM#16574]
# 🐞 bug report
strtolower() and Locale::acceptFromHttp() both report null values under PHP 8.1.11.

### ⁉️ Describe the bug
A default value is null when looking at the `$_GLOBALS` superglobal. This is triggered during install.

Zend throws the following errors:

![2022-10-10-yeti_error](https://user-images.githubusercontent.com/3241421/194974442-aa4379b7-8096-4115-9e6f-7c9924895950.png)

All three of these lines rely on the `main()` function within `\App\Config.php` which attempts to obtain relevant information from the `$_GLOBALS` superglobal.

### 🔥 How to trigger the error
Under Windows, I've successfully reproduced the bug in both WAMPServer and XAMPP. The bug does not seem to appear under *nix installs at all. 

1. Install a Windows-based desktop webserver such as WAMPServer or XAMPP
2. Navigate to the root directory (it will redirect to the install script, as normal)
3. See error

### 👎 Actual Behavior
The error prevents communication with the database server. Installation can't complete.

### 👍 Expected Behavior
Normal installation experience was expected, but not obtained.

### 👷 Testing
- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

As neither of these URLs is apparently on a Windows platform, such testing is quite impossible

### 📷 Screenshot of configuration
Because this is during install, I don't even get to the configuration screen before this issue is thrown.

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Because this is an inherent change in PHP 8, rather than an actual oversight on any coder with YetiForce, the logs are unhelpful, and in fact offered less information than the screenshot (but still pointed to the error in the `$_GLOBALS` superglobal, as indicated).

### 🌍 Your Environment
YetiForce 6.4.0 
Windows 11
PHP 8.1.11
WAMPServer 3.2.5 or XAMPP 8.1.10 (the issue persists in both installs)
Tested the issue with Chrome, Firefox, and Edge

### ❓ Additional context
I don't have time to trace down more than that. My ideas are based on a 3-minute look at the files, and then writing this up while waiting for others on my project team to discuss the future of integrating an email server with an internal-facing web interface.

My initial thought is that simple ternary operators could bring up a redundancy check, returning something other than NULL when there's a null result, rather than doing the simple-and-direct thing of calling the functions directly from their source.

However, I wasn't able to find a suitable fallback that would work for everyone, because i18n is once again a tricky beast.

### ❗️ Inform the community if you solve the problem
Regrettably, I wasn't able to arrive at a solution that worked.

**Comment by rskrzypczak** [comment]
Thanks, great description 👍.
I will add just for the sake of clarity that YetiForce version 6.4 does not support php version 8.1 yet :) (https://github.com/YetiForceCompany/YetiForceCRM/issues/16429)
However, feel free to report bugs for 8.1 further :)

**Comment by rskrzypczak** [comment]
Fixed in YF 7.x
