### ISSUE TITLE
[Design BUG] Update 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1657]
After all updates some become small))))))))))))))))))

![animation 92](https://cloud.githubusercontent.com/assets/1402355/8958669/97b2961a-361f-11e5-9896-511531d1f93e.gif)

**Comment by rskrzypczak** [comment]
Please check last version https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.0.0_to_2.1.0/zip

**Comment by waw555** [comment]
Give a little time, I'm still at work))))

**Comment by waw555** [comment]
The update was successful, the design OK
