### ISSUE TITLE
[BUG] Unable to reactivate inactive field

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#1659]
Tested on gitdeveloper. In Fields and Layout Editor while editing Opportunites module (not sure about the others) if I deactivate any field (by unchecking Active checkbox for the field) I can't reactivate it. If I click Actions>Inactive fields, popup opens offering me the list of inactive fields in order to activate them. I choose whichever I want from them but when I click Reactivate nothing happens.
If I go again Actions>Inactive fields I get a message saying that all fields are active.

**Comment by waw555** [comment]
Screen please

**Comment by nikdejan** [comment]
![inactivefieldbug](https://cloud.githubusercontent.com/assets/13381850/8978298/2110c78e-36a1-11e5-88b6-5d9bb2f01e5d.gif)

**Comment by nikdejan** [comment]
It's slightly different behavior now, but the bug remains. [Tested on developer]
Reactivating inactive field process this time goes normal, except that field doesn't get activated, ie. it doesn't reappear. You can reactivate inactive field again and again, but nothing changes.

**Comment by nikdejan** [comment]
Guys, this Issue shouldn't be closed. Problem is not solved.

**Comment by rskrzypczak** [comment]
I can't see the error anymore. A small detail related to refreshing pages was fixed, it could've lead to confusion in some particular case.
![inactive4](https://cloud.githubusercontent.com/assets/10221999/9135671/200e1b6e-3d10-11e5-83ff-eca4deda7168.gif)

**Comment by nikdejan** [comment]
Yep!
