### ISSUE TITLE
[bug] Single quote appears as html code in different modules

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#16590]
Hi,

Tested on gitstable.yetiforce.com, french language.

On Workflow module :
![image](https://user-images.githubusercontent.com/2930560/196048514-85ef5d23-8e3b-4c09-b772-49060cc7156b.png)

On EmailTemplate module :
![image](https://user-images.githubusercontent.com/2930560/196048618-040b0296-d4cf-4d28-bd8b-1b014742898f.png)

On error page :
![image](https://user-images.githubusercontent.com/2930560/196048648-79ce47bb-dd87-4026-966f-5aa127d66885.png)

Regards,

**Comment by rskrzypczak** [comment]
Fixed in YF 7.0.2
