### ISSUE TITLE
Where do I change "Zmieniono" for ticket mail template

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#1660]
I have the ticket mail templates and I don't know where to edit the 
Zmieniono value on the email template.

ex: Zmieniono Status from Open To Closed

I need it to say 
Changed Status from Open to Closed.

Thank you

**Comment by konadrian** [comment]
I added a translation for this variable, please check if everything is alright. You can change the variable by adding a value to the language file.  For example, if you are using English then the path will be languages/en_us/HelpDesk.php , you should add there another array index. ->  'LBL_CHANGED' => 'YOURVALUE',
