### ISSUE TITLE
[bug] Issue in Installation of 6.4.0

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#16616]
# 🐞 bug report

### ⁉️ Describe the bug

I am trying to install new version 6.4.0 on local server. All configurations are ok as per requirement but while installing I get **503 Service Unavailable Error **

Screenshot of installation configuration and final error is as below
![Screenshot 2022-10-27 165701](https://user-images.githubusercontent.com/12723595/198273654-52d8b4f8-e85b-4f28-83c2-3a45fb78ff20.png)
![Screenshot 2022-10-27 165501](https://user-images.githubusercontent.com/12723595/198273662-a1a91507-4663-4a27-850d-9878d8b6fc98.png)
![Screenshot 2022-10-27 165426](https://user-images.githubusercontent.com/12723595/198273673-eea9d7dd-d359-44cb-8c23-9a922aba7eb5.png)
![Screenshot 2022-10-27 165414](https://user-images.githubusercontent.com/12723595/198273681-9fec413f-b210-4cad-9876-92239c74acf2.png)
![Screenshot 2022-10-27 165358](https://user-images.githubusercontent.com/12723595/198273698-79d7cfda-8786-4a3c-b162-4ca10b17ce4a.png)
![Screenshot 2022-10-27 165343](https://user-images.githubusercontent.com/12723595/198273727-1fcb46da-df16-4bfa-b8f4-5ad38d615978.png)
![Screenshot 2022-10-27 165332](https://user-images.githubusercontent.com/12723595/198273740-12cc861e-7004-441d-a2d1-72fd8e1d0a80.png)
![Screenshot 2022-10-27 165313](https://user-images.githubusercontent.com/12723595/198273760-0ac5fd02-942d-4ed0-89d2-8e0d38400fe0.png)
![Screenshot 2022-10-27 165101](https://user-images.githubusercontent.com/12723595/198273814-7d426553-0a61-400e-8d1b-27575b11d7db.png)
![Screenshot 2022-10-27 165013](https://user-images.githubusercontent.com/12723595/198273876-95086289-780d-46b7-b814-f344d1513edf.png)
![Screenshot 2022-10-27 164958](https://user-images.githubusercontent.com/12723595/198273894-f4af4a04-d233-468d-811e-f876c702c9d7.png)
![Screenshot 2022-10-27 164935](https://user-images.githubusercontent.com/12723595/198273904-c3f40566-9cf3-4f91-8cce-5a070299103d.png)
![Screenshot 2022-10-27 164918](https://user-images.githubusercontent.com/12723595/198273921-020c501e-c62e-4593-813a-6d0b5f7b96f2.png)
![Screenshot 2022-10-27 164903](https://user-images.githubusercontent.com/12723595/198273937-9fddc7c5-6a6f-470a-bb7f-cfecb69bb022.png)
![Screenshot 2022-10-27 164849](https://user-images.githubusercontent.com/12723595/198273958-188acaa6-d405-4248-9127-2f3fa7b3b5a4.png)
![Screenshot 2022-10-27 164837](https://user-images.githubusercontent.com/12723595/198273977-55a85472-5438-4148-aa6f-cdd33955a1f8.png)
![Screenshot 2022-10-27 164821](https://user-images.githubusercontent.com/12723595/198274008-88017c65-eebe-48fc-8f7f-53765802309c.png)
![Screenshot 2022-10-27 164804](https://user-images.githubusercontent.com/12723595/198274036-d4bde645-93db-4d99-8282-527075f22c79.png)
![Screenshot 2022-10-27 164747](https://user-images.githubusercontent.com/12723595/198274056-6fea7ab2-9558-47e3-82ae-b7ab408f439a.png)
![Screenshot 2022-10-27 164721](https://user-images.githubusercontent.com/12723595/198274066-6f347046-7769-4ddb-9bdd-b2dac02452c1.png)

Details of php Log file is as below
[27-Oct-2022 16:55:35] WARNING: [pool www] child 11788, script '/www/wwwroot/default/crm/install/Install.php' (request: "POST /crm/install/Install.php") executing too slow (30.743537 sec), logging
[27-Oct-2022 16:55:35] NOTICE: child 11788 stopped for tracing
[27-Oct-2022 16:55:35] NOTICE: about to trace 11788
[27-Oct-2022 16:55:35] NOTICE: finished trace of 11788
[27-Oct-2022 16:56:45] WARNING: [pool www] child 11788, script '/www/wwwroot/default/crm/install/Install.php' (request: "POST /crm/install/Install.php") execution timed out (100.751536 sec), terminating
[27-Oct-2022 16:56:45] WARNING: [pool www] child 11788 exited on signal 15 (SIGTERM) after 640.087326 seconds from start

**Additionally I have noticed, 250 tables are created in database but not all as required**
additional Error in Log File generated on server
[Thu Oct 27 16:56:45.167333 2022] [proxy_fcgi:error] [pid 11610:tid 139918811617024] [client 192.168.1.245:63952] AH01067: Failed to read FastCGI header, referer: http://192.168.1.226/crm/install/Install.php
[Thu Oct 27 16:56:45.213647 2022] [proxy_fcgi:error] [pid 11610:tid 139918811617024] (104)Connection reset by peer: [client 192.168.1.245:63952] AH01075: Error dispatching request to : , referer: http://192.168.1.226/crm/install/Install.php

Kindly assist in the matter

Jeevan Pendhari

**Comment by mariuszkrzaczkowski** [comment]
You need to fix your PHP fpm configuration,
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/tests/setup/fpm

**Comment by JEEVAN28** [comment]
Hi, I have changed PHP fpm as per your suggestion, post this I got below error

![Screenshot 2022-10-27 175005](https://user-images.githubusercontent.com/12723595/198282745-87356595-efbe-44a0-8c84-76c5cb3db767.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/198309114-cf4856f0-1efe-4441-b087-b5eed1d1012b.jpg)
