### ISSUE TITLE
How to display address book at email client

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1661]
I find the address book dispear,how to display it.the YetiForce v2.0.664

**Comment by florek41** [comment]
#1581 - YF doesn't use roundcube address book and it was removed.

**Comment by 1250572980** [comment]
only use the lead,contact etc email?

**Comment by 1250572980** [comment]
only use the lead,contact etc email?

**Comment by mariuszkrzaczkowski** [comment]
In creating an email  it is possible to  search for an email in the base , 2 examples below:
![1](https://cloud.githubusercontent.com/assets/10198654/8977281/e28c617a-3697-11e5-9d38-484359234bdb.png)
![2](https://cloud.githubusercontent.com/assets/10198654/8977282/e28e41fc-3697-11e5-8b4c-94e3b11d60ed.png)

**Comment by 1250572980** [comment]
thanks,I try it.
