### ISSUE TITLE
[bug] Switch users bug

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#16623]
If last name of user contains 'and' switching to this user from Admin profile returning error:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dusername' cannot be null The SQL being executed was: INSERT INTO `l_yf_switch_users` (`baseid`, `destid`, `busername`, `dusername`, `date`, `ip`, `agent`, `status`) VALUES (1, 357, 'Administrator', NULL, '2022-11-02 16:57:03', '110.78.149.13', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36', 'Switched')

This happen when 'and' stands alone between other words
ver 6.3

**Comment by Jianbin719** [comment]
The buy was solved with ver 6.4
