### ISSUE TITLE
How to use corporate email

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1662]
I can not understand the corporate email,when I send the email at following position as the pic showing:
![snip20150730_2](https://cloud.githubusercontent.com/assets/12697896/8972044/dd7c6162-3688-11e5-868e-5942816fc3be.png)
when I sent a email by using the sent email,but the email do not display at the corporate email.
at the 2.0.0 RC,maybe use the attach the relation at the email client,but at the v2.0.664,I get the following:
![snip20150730_1](https://cloud.githubusercontent.com/assets/12697896/8972018/9bc900d6-3688-11e5-9f2b-e6f4a2e8a3f7.png)
how to use the corporate email by the easy understanded way?
I think many function too complex,maybe profession can not understand.

**Comment by bpabiszczak** [comment]
Company mail is an independent module. In order for mail to appear in there it's necessary to send a message, using roundcube, for example, when cron is running the system will download the mail after a few minutes and place it in company mail [ it doesn't happen in real time, it depends on cron, usually every few minutes]

When you open mail and a message appears that mail is being imported, it means that you haven't configured the scanner and cron properly and mail isn't downloaded automatically, but you have to do it manually.
