### ISSUE TITLE
Unable to add related account when you select an opportunity [bug] 

### ISSUE THREAD

**Issue by Giorgos-Hellene** [YetiForceCompany/YetiForceCRM#16622]
# 🐞 bug report

### ⁉️ Describe the bug

Unable to add related account when you select any opportunity.

### 🔥 How to trigger the error

Go on module Sales invoice, create a new record, selecte any Opportunity and you will see that nobody related account added. 

The same issue there is on 6.3 version on module Quote.

### 👎 Actual Behavior

i have test it in my production instance as well.

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

![εικόνα](https://user-images.githubusercontent.com/50912403/199358438-96deb1ca-e356-4c7e-8c81-9f9ca8586a6a.png)

**Comment by areksolek** [comment]
In the current version, the problem does not occur.
![oK1YrGh95a](https://user-images.githubusercontent.com/25615135/226375787-d473efda-4f7e-455b-859e-f5da19c7b10d.gif)
