### ISSUE TITLE
Update 6.4.0 Problem Report Module

### ISSUE THREAD

**Issue by monebo90** [YetiForceCompany/YetiForceCRM#16640]
After updating the relations module returns the error "No related information"
Has anyone had this problem?
Relationships no longer work

**Comment by rskrzypczak** [comment]
![image](https://user-images.githubusercontent.com/10221999/200740296-3477a8e7-a0df-49db-b72d-40a6104bbecc.png)

**Comment by monebo90** [comment]
🐞 bug report

After updating the relations module returns the error "No related information"



### 🔥 How to trigger the error

<img width="1434" alt="Screenshot 2022-11-09 alle 09 08 19" src="https://user-images.githubusercontent.com/103499824/200774279-ae9b6c96-a353-451b-a4f0-c18564fabe7c.png">

<img width="1433" alt="Screenshot 2022-11-09 alle 09 08 54" src="https://user-images.githubusercontent.com/103499824/200789865-815ed222-03d6-45d6-a87f-1049752ff039.png">

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

[errors.log](https://github.com/YetiForceCompany/YetiForceCRM/files/9969412/errors.log)

-->

### 🌍 Your Environment




| Environment                         | 6.4.0 / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server        |       host.it         |
| PHP                                 |     7.4 - 8.0           |
| Browser (name and version)          |        crhome - opera - firefox        |


### ❓ Additional context

Has anyone had this problem?
Relationships no longer work
