### ISSUE TITLE
Testing updater RC5

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1665]
Just did another test upgrade on top of an existing 2.0 version with the latest RC5 updater and again all went fine. I can also confirm that the Homepage widget issue is fixed.
Not able to find any error or issue. All smooth and good. Time to look at 2.2?

**Comment by bpabiszczak** [comment]
We will publish versions 2.2 on Monday.

**Comment by zebrahosting** [comment]
I assume you mean 2.1
