### ISSUE TITLE
[bug] RoundCube / OSSMAIL returning http url

### ISSUE THREAD

**Issue by yeti92force** [YetiForceCompany/YetiForceCRM#16658]
Hi dear support, i'm unable to test the mailbox feature in your gitstable org.

# 🐞 bug report

We are trying to integrate RoundCube mailbox with Office365. 
Since basic auth is depreciated by Microsoft, we need to use OAuth to complete this project.

After configuring my config.inc.php and my azure portal following the instructions in defaults.inc.php
 `///// Example config for Outlook.com (Office 365)`

Yetiforce is returning a http URL instead a https url like seting up in our Azure portal.

How can we force Yetiforce to return a https url ?

1. Go to MailBox from this url : https://*****/fintake.lease/index.php?module=OSSMail&view=Index&mid=1313&parent=1268
2. Click on Connexion à Office365
3. Click next...

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/107400809/202118980-f36b10ab-c9e0-4838-8e4b-2cfe2a32d104.png)

however, we had correctly setting up our Azure portal with a https url

![image](https://user-images.githubusercontent.com/107400809/202120376-49768c28-080f-4b6b-b2d1-28d80b725e1e.png)

### 👍 Expected Behavior

Yetiforce is returning a https url and connexion with RoundCube and Office365 is working.

### 📷 Screenshot of configuration

![image](https://user-images.githubusercontent.com/107400809/202126308-912da7ab-276c-4ae7-a389-75b5a3683d3e.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

no logs with OAuth.
With basic Auth : 

`[16-Nov-2022 09:15:18 +0100]: <2a31mblv> IMAP Error: Login failed for mathieu.szymkiewicz@****.fr against outlook.office365.com from **.**.**.** (X-Real-IP: ****-Forwarded-For: **.**.**.**). **AUTHENTICATE PLAIN: AUTHENTICATE failed.** in /var/www/html/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_imap.php on line 211 (POST /public_html/modules/OSSMail/roundcube/?_task=login&_action=login)`

-->

### 🌍 Your Environment

| Environment                         | Version / Name |

NA

Regards,
Mathieu Skz

**Comment by mariuszkrzaczkowski** [comment]
The current stable version does not support OAuth, work is underway on the developer version.
