### ISSUE TITLE
[bug] Invoice -  payments in decimals incosistenccy 

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#16666]
Created invoice, entered payment in record (exactly the same sum as invoice) but invoice showing "Overpaid"
Problem is in decimals stored in database. Fixed directly in tables but that is dirty way and possibly could be done with fix.
Ref in #16664

**Comment by jmginfor** [comment]
It's a old prob. 

See this : 
https://github.com/YetiForceCompany/YetiForceCRM/issues/13167#issuecomment-643441049
