### ISSUE TITLE
[BUG] Unable to edit field in Summary View

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#1668]
tested in gitdeveloper.
![editsummeryview](https://cloud.githubusercontent.com/assets/13381850/8983095/812cbfa8-36c7-11e5-9862-190b5c611acd.gif)

**Comment by nikdejan** [comment]
Now I can edit fields, but after that I there is an error in commenting from summary view.
If I opet record in summary view I can post comments normaly. If I edit, for example, opportunity name, name gets edited but after that I'm not able to post comments form summary view. After refresh, I can comment again.

**Comment by bpabiszczak** [comment]
We don't have enough information. Clean your cache. Record the error once again, showing in the browser's console whether or not any error appears.

**Comment by nikdejan** [comment]
![summaryviewcomments](https://cloud.githubusercontent.com/assets/13381850/9004647/f8e1c7fe-3777-11e5-9df3-32f5dd29d0b9.gif)
In Opportunity Summary View, after editing opportunity name, I'm not able to post Comments.
