### ISSUE TITLE
Activation Isuue

### ISSUE THREAD

**Issue by MaxCarone70** [YetiForceCompany/YetiForceCRM#16695]
After 9 days I had no contact from the support team for the activation. Why? The Company configuration form is correctly fulfilled

**Comment by rskrzypczak** [comment]
It is best to report problems with registration to [registration@yetiforce.com](mailto:registration@yetiforce.com)
Send APP ID.
FYI: https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/problems-with-system-registration
https://yetiforce.com/en/marketplace/your-app-id
