### ISSUE TITLE
[QUESTION] What are summary_blocks?

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#1669]
some modules (Accounts, Leads, Potentials...) have them but not all. What are they for?

**Comment by bpabiszczak** [comment]
Unfortunately I don't understand the question. Take a screenshot of the block you are talking about. Describe in detail why you think something is wrong or what you don't understand or ask the question more precisely.

**Comment by nikdejan** [comment]
Sorry for not being clear enough.
In folder <yetiroot>/modules/Accounts there is a folder named summary_blocks. Also in Leads and Potentials. Other modules do not have summary_blocks folder. So my question is what do php files in that folder do? What is inside summary_blocks? Where it is displayed? Thank you.

**Comment by diderich** [comment]
Theses files contain the code to generate the summary block contents in the summary view of a record (for example show the number of e-mail messages associated with the displayed Lead. They are displayed by adding the widget 'data summary' to the module. Here is a sample (layout not the most recent) for Leads
![a1df3de8-404f-11e5-9577-5fe151a78982](https://cloud.githubusercontent.com/assets/10230144/9228882/cff1e5ac-411a-11e5-86c2-32d5e22ecfe8.jpg)

**Comment by nikdejan** [comment]
diderich, thank you very much.
