### ISSUE TITLE
[bug] Converted ticket module to advanced. Unit problem

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#16700]
I checked on git stable and local clean installation.
Case: Converting Tickets module from basic to advanced.
Issue: There is no way that services/products will show Unit in line items. System don't picking it up.

![image](https://user-images.githubusercontent.com/84110093/204919318-643a184d-5050-41e8-a03a-9a3470c3ef00.png)

Best

**Comment by garryatbrighton** [comment]
Noticed the same behavior. 

Garry

**Comment by rskrzypczak** [comment]
You need to manually add a mapping to the _invmap inventory tables for the modul:
https://github.com/YetiForceCompany/YetiForceCRM/discussions/15701
