### ISSUE TITLE
Small interface issue; refresh listing metrics

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1670]
Tested in dev version after upgrading from v2.0 -> 2.0.663

Filters select contacts, looks normal:
<img width="266" alt="screen shot 2015-07-30 at 15 30 12" src="https://cloud.githubusercontent.com/assets/10379403/8984155/12e594b2-36d0-11e5-9b43-febe3d47e4f6.png">

But when I click the refresh button, I see two times the number and the refresh button disappears:

<img width="282" alt="screen shot 2015-07-30 at 15 30 23" src="https://cloud.githubusercontent.com/assets/10379403/8984168/25f2efa0-36d0-11e5-88c1-08b78c721570.png">

Issue also shows on your https://gitdeveloper.yetiforce.com

**Comment by konadrian** [comment]
ba9cde4535803cc43a4050722db91595b0edf926
