### ISSUE TITLE
[ATTENTION] php variables

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1673]
After installing variable post_max_size and upload_max_filesize in the 1000M, the first time passed the installation from start to finish without errors. Previously always been an issue that the server is not responding.

Developers can check these parameters and establish new values

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/d136902de5f9c36c09742d5c53cb727b29730711
