### ISSUE TITLE
An error occurred in the documents module

### ISSUE THREAD

**Issue by krseguros** [YetiForceCompany/YetiForceCRM#16744]
Hello, In the documents module I have a website type field, after I add the icon (mdi mdi-folder-google-drive) to this field the system is throwing me the following error
It should be noted that before this everything worked perfectly:
![image](https://user-images.githubusercontent.com/96985476/208249590-c2bd33ad-c848-4c1a-8def-26b705d71824.png)
![image](https://user-images.githubusercontent.com/96985476/208249689-ff8ebe6e-e016-471e-9eda-b3b1232c62bf.png)

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/208265339-2a81d5f7-025a-4648-a269-4c68f634a76b.jpg)

**Comment by krseguros** [comment]
1. I checked several entries with the word documents, but I did not find anything related to what happened to me.
2 AND 3 Try to be as descriptive as possible including the images that show the error. video attached
[My home page - Google Chrome 2022-12-18 18-22-12.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/10255028/My.home.page.-.Google.Chrome.2022-12-18.18-22-12.zip)
4. Realice pruebas en https://gitstable.yetiforce.com y todo funciono correctamente.
A. Antes de agregar el campo e icono y B. Después de agregar el campo e icono:
![Screenshot of Documents jednolity rzeczowy wykaz akt,](https://user-images.githubusercontent.com/96985476/208327827-40da6dfd-2666-42f3-b8cf-7490f00a2311.jpg)
![Screenshot of Layout Editor](https://user-images.githubusercontent.com/96985476/208327831-92b2c03e-0257-4a15-8fd7-2d0b26a42adb.jpg)

expected behavior
![Screenshot of Documents jednolity rzeczowy wykaz akt, (1)](https://user-images.githubusercontent.com/96985476/208327907-ed246436-413b-4f97-9bc0-1b6e05817d01.jpg)
![Screenshot of Layout Editor (2)](https://user-images.githubusercontent.com/96985476/208327916-02dbe609-264d-4a73-98e2-87de3d3736a6.jpg)
your environment



| Environment | Version / Name |

**Comment by rskrzypczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/16480
Delete icon in database and wait for update.

**Comment by krseguros** [comment]
how do I get there?  please guide me

**Comment by rskrzypczak** [comment]
table: `vtiger_field`
column: `icon`
Find the entry for that field and empty the contents of said column
