### ISSUE TITLE
Workflow "Send PDF"  task doesnt deliver PDF

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#16745]
Send PDF task doesnt deliver PDF even this PDF is visible in  Mails to Send admin panel.
With one exception: when I click Manual Sending this attachment goes correctly, but when I leave this email for cron, the PDF template is not attached.

Latest stable 6.4
PHP 7.4.3
Server configuration 100% with developer recommendation
Bare metal machine with plenty of resources

Best

_Originally posted by @s2b-git in https://github.com/YetiForceCompany/YetiForceCRM/discussions/16743_

**Comment by TonyM15** [comment]
I think I see the same result. My app migrated from 3 previous versions.
Some error reporting trigger missing as no logs showing problem

**Comment by Marco31Bike** [comment]
Maybe some /config settings? It happened to me before. Now OK on new installation (without upgrade)

Marco

**Comment by s2b-git** [comment]
I hit bottleneck. Tried all possible debugging options and no error showed up. PDF template is still not sending with workflow. 
Hoping for some clue-bat gents

Best

**Comment by Marco31Bike** [comment]
Installed latest 6.4. All php extensions installed and all php app config nicely polished. PDF is not attached to email.
Previous 6,3 was working

**Comment by ManuIoan** [comment]
Hello, are there any updates on this? I have the same problem, the cron is not attaching the pdf but if i send manually, is attached

**Comment by butuemi** [comment]
Same issue here. Any updates?

**Comment by garryatbrighton** [comment]
6.5 - PDF in workflow also not attached.

**Comment by garryatbrighton** [comment]
So, file VTSendPdf.php

should have following to get it working:

Above class:
require_once 'modules/com_vtiger_workflow/VTWorkflowUtils.php';
require_once 'modules/com_vtiger_workflow/VTTask.php';


and:
$fileName = 'wf_'.time();
$filePath = 'storage/Pdf/'.$fileName.'.pdf';


Not sure why original in 6.5 is reinforced with this error

**Comment by rskrzypczak** [comment]
YetiForce version 7.x does not show the problems reported here.
