### ISSUE TITLE
[bug] Not able to create new filters

### ISSUE THREAD

**Issue by antcorro** [YetiForceCompany/YetiForceCRM#16780]
# 🐞 bug report

### ⁉️ It's not   possible to create new filters from "Filters - Configuration" page in yeti forfe v6.4.0 service pack 6. 
When I click on "add filter" the loader is shown and nothing happens, it freezes. An error appears in the firefox or chrome console: 
GET https://gitstable.yetiforce.com/index.php?module=CustomView&view=EditAjax&source_module=4
[HTTP/2 500 Internal Server Error 99ms]

### 🔥 How to trigger the error

1. Go to 'Filters Configuration' in 'System settings'
2. Click on 'Add filter' button

![YF_filters_issue_02-01-2023 21-43-min](https://user-images.githubusercontent.com/10244840/210277594-95dc71f2-7892-4a14-af2b-135cd29d0bf1.gif)

### 👎 Actual Behavior
It's not possible to add new filters from System settings section

### 👍 Expected Behavior

I need to add more filters

### 👷 Testing

- [X ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

It works on gitdeveloper

### 📝 Firefox and Chrome console shows an Internal server error
GET https://gitstable.yetiforce.com/index.php?module=CustomView&view=EditAjax&source_module=4
[HTTP/2 500 Internal Server Error 99ms]

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |6.4.0 ervice Pack v6 the same of gitstable

**Comment by mariuszkrzaczkowski** [comment]
check on https://gitdeveloper.yetiforce.com/
maybe it has already been fixed

**Comment by rskrzypczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/16543
Fixed in: https://github.com/YetiForceCompany/YetiForceCRM/commit/f6602e2c94ea39ad24304190ecb7d72e45602f7e

**Comment by antcorro** [comment]
Thank you. I don't understand Polish so I hadn't seen the duplicate. When the is the fix expected to be released? Or is there another way to update my system without waiting for update?

**Comment by rskrzypczak** [comment]
As I indicated previously, all the code related to the fix is here: https://github.com/YetiForceCompany/YetiForceCRM/commit/f6602e2c94ea39ad24304190ecb7d72e45602f7e.
You can wait for the update to be released, or manually transfer the changes.
