### ISSUE TITLE
[Bug] Webforms broken

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1679]
Tested on gitdeveloper.yetiforce.com - ver. 2.0.706
filled form returning: Fatal error: Class 'SysDebug' not found in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/logging.php on line 22

**Comment by rskrzypczak** [comment]
I didn't notice the described error. Please check once again if it still occurs, if so, please describe it in more detail:
-how to trigger the error in this specific location: https://gitdeveloper.yetiforce.com,
-a screenshot would be nice as well
