### ISSUE TITLE
bug workflows task

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#168]
there is no possibility to edit workflows task after saving it. Previously created items are not allowed to editing, only possibility is to create new items. In some cases only way is to delete taks and create new one. 
Could You active all the fields in time of editing taks?

**Comment by bpibiza** [comment]
![1](https://cloud.githubusercontent.com/assets/10252484/5981066/3871692e-a8b7-11e4-8da2-5e5e80f1a404.JPG)

**Comment by bpibiza** [comment]
O_O 
when I reopen task, it disappeared. something went wrong

**Comment by waran70** [comment]
this issue were in vtiger 6.1 and it was fixed with new update I guess

**Comment by MichalJanicki** [comment]
I couldn't test for the error. Please provide a detailed description(e.g. version number of YF or remote crm for test). On version 1.2.53 RC I wasn't able to test for this error.

**Comment by bpibiza** [comment]
not tested anymore on previous version
version 1.2.91 is free of this bug. 
please close issue.

**Comment by MichalJanicki** [comment]
Still i couldn't test for the error. Is there a possibility to create a remote version of YetiForce so I can test there for this bug?
