### ISSUE TITLE
[bug]globe search does not work

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1683]
YetiForce v2.0.683 ,when I use the globe search,it does not work.
![qq 20150803155400](https://cloud.githubusercontent.com/assets/12697896/9033225/d1eac7ea-39f7-11e5-8689-63c8a5240598.png)

**Comment by rskrzypczak** [comment]
I didn't notice the error in the current version of the YetiForce system. Please check if the error occurs in https://gitdeveloper.yetiforce.com".
![search2](https://cloud.githubusercontent.com/assets/10221999/9035987/736a796e-39dd-11e5-9542-73c66d9b0116.jpg)

Check search configuration.

**Comment by bpabiszczak** [comment]
If you import records, you should update labels.
