### ISSUE TITLE
[bug]Calculations import does not work

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1684]
When I select the file,click the next,a blank page display.the data exported from https://test.yetiforce.com/

**Comment by 1250572980** [comment]
My YetiForceCRM v2.0.683

**Comment by MaciejStencel** [comment]
This error was fixed. Except of that export of calculations records was fixed. Exported csv file did not have any informations regarding records blocks module.

You can test it on gitdeveloper.yetiforce.com. But keep in mind that YF 2.0 which is on test.yetiforce.com will still be exporting calculations csv file not correctly. There wont be any data about products block.

When importing records keep in mind that products, services and modules with product block aren't autocreated when importing records that reference to them. So for example if you have exported csv file with calculation record and 'Product A' product then firstly import 'Product A' record or create product with that name.
