### ISSUE TITLE
[bug] Email templates - filters error

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#16855]
Basically filter creation in Email templates hanging as per attached gif.
The same is in my 6.4 as well as in gitdev

Best
![filters-error](https://user-images.githubusercontent.com/84110093/216541011-5be6351b-a2da-4cd0-a657-44b4a5ab7d9e.gif)

**Comment by ghost** [comment]
Hello.

I have seen the issue at hand and would like to help contribute.

**Comment by rskrzypczak** [comment]
@skan654 feel free to do a pull request :)

**Comment by areksolek** [comment]
In the current version, the problem does not occur.
![XsG4QbBO51](https://user-images.githubusercontent.com/25615135/226378463-ae49e98d-45c4-491e-97fc-29ac465175ee.gif)
