### ISSUE TITLE
[Docker] `dockerfile` build issues

### ISSUE THREAD

**Issue by NorkzYT** [YetiForceCompany/YetiForceCRM#16852]
# 🐞 bug report

### ⁉️ Describe the bug

`dockerfile` build issues when running `docker-compose up` from the root directory of the repository following the docker documentation.
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/setup/docker.md

### 🔥 How to trigger the error

1. Run `docker compose up -d` in the root directory of this repository.

### 👎 Actual Behavior

I get the following error that is shown in the console.

![image](https://user-images.githubusercontent.com/53381649/216190179-5566cdf3-e265-4c92-b448-1a3961f6573e.png)

### 👍 Expected Behavior

The `dockerfile` would build without any issues to be able to use it for production.

### 👨‍💻️ Command to launch docker

```
docker compose up -d
```

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

- /var/www/html/cache/logs/system.log
- /var/www/html/cache/logs/errors.log
- /var/www/html/cache/logs/cron.log
- /var/log/nginx/error.log
- /var/log/nginx/localhost_error.log
- /var/log/nginx/php{php version}-fpm.log
- /var/log/mysql/error.log

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |  Latest
| Web server (name and version)       |       Latest          |
| PHP                                 |       Latest          |
| Browser (name and version)          |    Latest             |
| Operating System (name and version) |   Latest              |
| Database (name and version)         |      Latest           |
| Service Pack version                |          Latest       |

**Comment by ghost** [comment]
Perhaps there is an issue with code bits?

**Comment by oscardimanno** [comment]
I've just worked on this bug.
Pull request here: https://github.com/YetiForceCompany/YetiForceCRM/pull/17040

**Comment by oscardimanno** [comment]
Solved.
@mariuszkrzaczkowski you can close the issue

**Comment by NorkzYT** [comment]
Closing issue.
