### ISSUE TITLE
[Request] Project (tasks) in calendar

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1686]
We discussed this before but I really miss the overview of Projects and Projects tasks in the calendar. Hope that this could be an option in GA2.2
Without it I miss the overview what needs to be done and when, It could be the same as the user/activity slider on the right, simple to switch on 'Projects' with a block if choices Projects / Tasks / Milestone.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1055
