### ISSUE TITLE
[Docker] how to link 2 custom field

### ISSUE THREAD

**Issue by newminder** [YetiForceCompany/YetiForceCRM#16876]
I created a custom field PRODUCT SPEC in product, and a custom field PRODUCT SPEC in Quotes [advanced block],  want to choose the product name, then the PRODUCT SPEC show up like other field price....please advise how to make it... appreciate.

**Comment by newminder** [comment]
I tried reference field, but does not work

**Comment by mariuszkrzaczkowski** [comment]
1. question or error?
- question is discussion
- bug - see https://github.com/YetiForceCompany/YetiForceCRM/issues/new

3. why did you specify "Docker"? the question is about CRM
