### ISSUE TITLE
[bug]Asset import does not work

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1687]
I export the data of asset at v2.0.0 RC,when I import the date to v2.0.683,it crash.

**Comment by MaciejStencel** [comment]
Please refer to comment posted here: https://github.com/YetiForceCompany/YetiForceCRM/issues/1684 

There bug that crashed import was fixed and keep in mind that when importing records from csv file to firstly create/import referenced products alone. Referenced modules that have products block need to be imported firstly also, in this case Invoice field is mandatory so it needs to have reference to another record. Invoice has products block, so before importing asset you would have to first create/import that invoice.
