### ISSUE TITLE
[bug] Cant login after server upgrade [EN]

### ISSUE THREAD

**Issue by MonsterITServices** [YetiForceCompany/YetiForceCRM#16872]
# 🐞 bug report

### ⁉️ Describe the bug

After upgrading ubuntu server from 18.04 to 22.04 then importing the database and moving the files back on to the server we can no longer login. It just refreshes the login screen.

![login](https://user-images.githubusercontent.com/22075161/217806056-4bc91f0b-ab27-4813-8451-9e6cb8e1a3c2.gif)

### 🔥 How to trigger the error

1. Go to yeti.monster-it.co.uk
2. Click on login
3. See error just repeats login

### 👎 Actual Behavior

Just keeps refreshing the login screen

### 👍 Expected Behavior

Should login to the home screen

### 👷 Testing

- [✔️ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [✔️ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📷 Screenshot of configuration

Cant get in to download config

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

Only error i can see is this:
PHP Warning:  session_start(): Failed to read session data: user (path: /var/www/yeti.monster-it.co.uk/cache/session) in /var/www/yeti.monster-it.co.uk/vendor/yetiforce/csrf-magic/src/Csrf.php on line 447

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4 stable
| Web server (name and version)       |  apache2.4.52             |
| PHP                                 |  PHP7.4              |
| Browser (name and version)          |     edge,chrome           |
| Operating System (name and version) |  ubuntu 22.04 lts              |
| Database (name and version)         |       mysql 8.0         |
| Service Pack version                |         v6       |

**Comment by rskrzypczak** [comment]
It doesn't seem to be creating a session for you.
Check if you have a `cache/session` directory and clear your browser's cache and cookies ([link](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-clear-browser-cache))
