### ISSUE TITLE
[bug]Sold Services import does not work

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1688]
I export the data of Sold Services at v2.0.0 RC,when I import the date to v2.0.683,it crash.

**Comment by MaciejStencel** [comment]
Fixed here: https://github.com/YetiForceCompany/YetiForceCRM/issues/1684

When importing Sold Services you have to have referenced invoices in csv already in crm. Create them or import them before importing Sold Services.
