### ISSUE TITLE
[PL] Wysyłka maila - popup

### ISSUE THREAD

**Issue by bwiatrni** [YetiForceCompany/YetiForceCRM#1690]
Witam,
czy jest możliwość przywrócenia starego sposobu mailingu poprzez popup? Na chwilę obecną OSSMail przekierowuje do roundcuba co trochę jest nie spójne z resztą systemu CRM. Jest to bardzo istotna sprawa ponieważ w niektórych dedykowanych rozwiązaniach nie mogę użyć Roundcuba tak więc moje pytanie jest czy bardzo problematyczne będzie przywrócenie popupa, czy całkowicie został usunięty z YF?

**Comment by bpabiszczak** [comment]
Niestety nie rozumiem o czym piszesz. 

Obecnie [czyli np. wersja developerska] posiada pełną integrację na poziomie CRM <> Roundcube co umożliwia uruchamianie poczty w oknach popup z pełną integracją z CRM. Wcześniej działało tak jak teraz czyli zarówno popup jak i to samo okno, przy czym w popup nie działało połączenie CRM <> Roundcube. 

Natomiast wszystkie przekierowania będą kierowały do roundcube, w przyszłości możemy dodać opcje [klient poczty lokalny/zewnętrzny] i wtedy wszystko działa na zasadzie mailto czyli przeglądarka decyduje do jakiego programu przekierować np. outlook.

**Comment by bwiatrni** [comment]
Tak wygląda popup VT:
![email_send_vt6](https://cloud.githubusercontent.com/assets/5813880/9041384/039f7988-3a08-11e5-92c0-fb0746576e0d.png)

natomiast w YF moduł maila jak dobrze rozumiem został całkowicie zamieniony na Państwa autorski. Takie jest wymaganie do projektu, który obecnie poprawiam aby nie było Roundcuba stąd też moje pytanie czy uzyskanie starej wersji(jak na screenie) będzie w ogóle możliwe (np doinstalować stary moduł mailingowy VT)? CRM nad którym pracuje został wdrożony na wersji 2.0.0 YF + dedykowane modyfikacje, które nie zostały nawet spisane w dokumentacji także nie wiem jak by było z aktualizacją do wersji deweloperskiej.

**Comment by bpabiszczak** [comment]
To rozumiem [jak było w VT] nie rozumiem jednak samego problemu, o ile w VT było okno wyglądające w sposób A a u nas jest okno wyglądające w sposób B ale pełniące tą samą funkcje, to nie rozumiem biznesowej różnicy.

To czy coś się otworzy w tym samym oknie czy w innym, to tylko kwestia parametru target. W każdej chwili możecie również utworzyć własny moduł lub wgrać Vtiger-a i do niego "linkować". Oczywiście uzyskanie dowolnego wyglądu popup jest możliwe, lecz pracochłonne, współczuje temu, kto będzie to robił. 

Na pewno my nie będziemy tego cofać, ani nie będziemy dawali takiej opcji, bo nie miałoby to merytorycznego uzasadnienia.

**Comment by bwiatrni** [comment]
Nie chodzi tu o cofnięcie danej funkcjonalności :) biznesową różnicą (bardzo istotną i dlatego niektórzy klienci mogą nie chcieć Roundcuba) jest sposób masowej wysyłki maili. Tzn zaznaczamy kilka rekordów na liście kontrahentów, otwiera nam się okienko z wypełnioną listą maili i różnica polega w sposobie jaki maile są wysyłane przez Roundcuba tzn. Roudcube wysyła do wszystkich zaznaczonych kontrahentów w jednym mailu (przez co odbiorcy "widzą się" wzajemnie) natomiast natywny moduł VT do każdego kontrahenta osobno. Chyba że da się to jakoś ustawić w Roundcube?

**Comment by bwiatrni** [comment]
Jak można odblokować natywny moduł EmailTemplates? Na chwilę obecną jest w folderze modules ale na liście modułów się nie pojawia do włączenia.

**Comment by bpabiszczak** [comment]
Programistycznie można wszystko, nie pomagamy, jeżeli ktoś chce robić jakieś dziwne modyfikacje, pomagamy, gdy ktoś chce dodać nowe funkcjonalności do systemu go rozwijając i budując jeszcze lepszy produkt. A więc w takich udziwnieniach musisz sobie radzić sam lub może ktoś ze społeczności Ci pomoże, ale wtedy polecam listę mailową i pytać w języku EN. 

Kwestia wysyłania tak aby inni nie widzieli pozostałych adresatów to tylko kwestia wrzucania maili nie w  pole do tylko w pole UDW.

**Comment by bwiatrni** [comment]
No cóż rozumiem. Pomysł na ulepszenie dostaliście czyli dodać możliwość wyboru UDW a czy go wykorzystacie to już nie moja sprawa. Jakby ktoś jeszcze szukał informacji na ten temat moduł EmailTemplates został usunięty z bazy dlatego też zapewne nie pojawia się na liście managera. Pozdrawiam
