### ISSUE TITLE
Can not open cron.sh[bug] 

### ISSUE THREAD

**Issue by Patrickg56** [YetiForceCompany/YetiForceCRM#16904]
# 🐞 bug report

### ⁉️ Describe the bug

I am configuring CRON on my Hostinger server. Due to the age of the help system examples, I stumbled around getting the path right. Now I have the path right it appears that it cannot open the file. I am getting the cron output:
![CronError](https://user-images.githubusercontent.com/64174438/219101980-12cbea83-6f8c-484f-abb5-57cbc1736ff3.jpg)

### 👍 Expected Behavior

the Cron system to run correctly

### 👷 Testing

The Permissions were originally set to 744 I got this error
I changed the permissions to 755 and still got the error
- [ yes] I confirm that I tested it at https://gitstable.yetiforce.com

![cronshPermissions](https://user-images.githubusercontent.com/64174438/219101896-b4dbc290-fd61-4601-b6ad-10e244871c98.jpg)

### 📷 Screenshot of configuration

![ConfReport](https://user-images.githubusercontent.com/64174438/219146390-3dcd40ab-3964-42ce-aa96-f1ca4ab4cd34.png)

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

### ❗️ Inform the community if you solve the problem

![CronError](https://user-images.githubusercontent.com/64174438/219101387-4b5507e1-e52c-4eae-8c57-786c514cc99e.jpg)

**Comment by mariuszkrzaczkowski** [comment]
this error occurs only with you and without verifying the problem it will not be possible to solve it, see the documentation
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron
