### ISSUE TITLE
Saving Default Values Not Applying to Customer Portal

### ISSUE THREAD

**Issue by bfeddes** [YetiForceCompany/YetiForceCRM#16917]
Whenever I go to edit the fields for our portal (Webservice Premium), and want to set a default value, the default value does not apply in the Customer Portal. However, when I want to disable/enable fields, that does apply in the Customer Portal. The issue for this is that in the Ticket module, I want the default "Assigned To:" value to be our Support Group. However, even when I make that the default value and it says it was applied, when opening a ticket in the portal, the default value is not applied.

To trigger this error, all I did was simply go to **Software Configuration > Standard modules > Edit fields > portal (Webservice Premium) > Tickets > Assigned To > Checked the Default value box.** Even when closing out of the field configuration and returning, it says that the default value that I selected, in this case, Support Group, has been applied. The problem remains that when I create a ticket in the portal, that this default value is in fact not applied. This bug also persists in all other modules as well, not just Tickets.

1. Go to 'Software Configuration > Edit fields > Tickets > portal (Webservice Premium)'
2. Click on 'Assigned To'
3. Check the box 'Default Value'
4. Select the User/Group you want it to be assigned to by default
5. Save
6. Go to your customer portal
7. Create a Ticket
8. Look at who the Ticket is assigned to
9. In my case, it was assigned to Administrator, while it should have been assigned to Support Group.
10. See error

Here is the configuration:
![yeti1](https://user-images.githubusercontent.com/112420814/220410122-c9e1a3a0-ae4e-4fe5-bc97-1782e9238de1.PNG)

Here is the result:
![issuee](https://user-images.githubusercontent.com/112420814/220410255-6cd7c05e-eecb-4c6b-bb8a-b486e0bbb150.PNG)

As you can see, it is by default assigned to Administrator, while it should be assigned to Support Group. This issue has been persisting for over a week and I was hoping to get a solution to this.

**Comment by mariuszkrzaczkowski** [comment]
Check if you have a selected module in this group that you choose without it will not work because there will be no such group in the selection list
![image](https://user-images.githubusercontent.com/10198654/220555501-759da1fb-7e21-4d29-bfa5-4ac62861c5a4.png)
i did a test and it works on gitdev, portal inherits from logic in CRM
![image](https://user-images.githubusercontent.com/10198654/220555776-8b99b56a-c838-42b2-ad35-8f88f0573382.png)
