### ISSUE TITLE
How to use mail Scanner auto reation to Corporate email

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1691]
when I receive the email from the leads,I want to auto set the email to corporate email.I set up like following:
![qq 20150803230925](https://cloud.githubusercontent.com/assets/12697896/9040594/c74ccce6-3a35-11e5-84e3-34cd4210a645.jpg)
![qq 20150803231225](https://cloud.githubusercontent.com/assets/12697896/9040602/d2fb1eee-3a35-11e5-9f62-5a2e8be76891.jpg)
![qq 20150803231237](https://cloud.githubusercontent.com/assets/12697896/9040611/ddf2368e-3a35-11e5-97a9-e5803ada3102.jpg)
I have set up cron corretly,why the email not found at database?why only but manual import?

**Comment by bpabiszczak** [comment]
Please put screen from scheduler

**Comment by 1250572980** [comment]
![snip20150804_1](https://cloud.githubusercontent.com/assets/12697896/9049923/30b35ec2-3a7a-11e5-9943-7bbb263626d2.png)

**Comment by 1250572980** [comment]
I hope when i receive the replied email of leads contacts accounts,the replied email auto attached to corporate email.

**Comment by nikdejan** [comment]
There is something wrong with your scheduler. MailScannerAction should run every 3 minutes, and it last started 11 minutes ago. Looks like it has been manually executed only once. If everything was set up correctly you should have seen Last scan started 2 minutes, 1 minute (always less than 3).

**Comment by 1250572980** [comment]
I have set the crontab to 1 minutes,but it still no change.

**Comment by bpabiszczak** [comment]
Unfortunately your description of the problem isn't sufficient. Recreate the error in the gitdeveloper version and then describe step by step how to trigger it.

**Comment by 1250572980** [comment]
![snip20150810_2](https://cloud.githubusercontent.com/assets/12697896/9169263/415d7272-3f8d-11e5-8590-b9d461dfd5ae.png)
![snip20150810_3](https://cloud.githubusercontent.com/assets/12697896/9169301/621c0780-3f8d-11e5-9c3d-3bd2adf169ba.png)

**Comment by 1250572980** [comment]
![snip20150810_2](https://cloud.githubusercontent.com/assets/12697896/9169486/0e7f412c-3f8e-11e5-9d68-8f2b35e2da8d.jpg)
![snip20150810_3](https://cloud.githubusercontent.com/assets/12697896/9169492/13d5b430-3f8e-11e5-9612-12c6308780a9.jpg)
![snip20150810_4](https://cloud.githubusercontent.com/assets/12697896/9169497/1906b7f6-3f8e-11e5-902a-7390a933d7dd.jpg)

**Comment by bpabiszczak** [comment]
Sending an email doesn't mean that this email will immediately be linked to a contact/account related to that email. These are 2 independent mechanisms. In order for email mapping to work first you have to to properly configure the mail scanner. In the gitdeveloper version the scanner isn't configured, so no wonder it doesn't show you the email.

Read this article: : https://yetiforce.com/en/administrator-documentation/panel/mailbox/mail-scanner/135-mail-scanner.html
