### ISSUE TITLE
[Question] Does the mailscanner also checks BCC field?

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1692]
We need to send some message to people with their addresses in CC / BCC fields are they included in the scanning? (The still show in the page source).
If not, could this be an option in a later release?

**Comment by reeid** [comment]
Would be good to include all other email-type fields with selection option

**Comment by mariuszkrzaczkowski** [comment]
Yes, we do scan all address fields

**Comment by zebrahosting** [comment]
From what I have seen now, it does not work when there is more than one email address in the address field. Will do/need some further checks on this.

**Comment by mariuszkrzaczkowski** [comment]
We checked it and the mechanism works properly. Can you provide us with a more detailed description, preferably with screen shots?

**Comment by zebrahosting** [comment]
I will certainly try to test this further but at the moment the whole cron stopped working. (blank screen when running manual)
Don't see a manual stop like vTiger.

Here is an example:
![mailscanner](https://cloud.githubusercontent.com/assets/10379403/9056192/77b42d08-3a91-11e5-980b-f50304b18b5b.png)

You can see that it finds the sender and receiver but ignores the list in BCC (see on the right , it find only one contact, thats the one in from field.

Of course this is less likely to happen when there is a proper mass email system.

**Comment by bpabiszczak** [comment]
Your description didn't clarify anything, I still don't know if the functionality works properly or not. In order for the system to link an email to a contact/lead/account/vendor/employee several conditions have to be met, for example, the record has to be properly entered with the correct email. Send an email to the test address at gitdeveloper and then record a scenario showing how to trigger this error, then we can check it again.
