### ISSUE TITLE
Can not add/edit Opportunities Status

### ISSUE THREAD

**Issue by tquoc229** [YetiForceCompany/YetiForceCRM#16934]
Hi,
I got an error when I tried to add/edit Opportunities Status. Here is the error:

`{"success":false,"error":{"code":42,"trace":"#0 vendor\/yetiforce\/yii2\/db\/Command.php(1097): yii\\db\\Command->prepare(false)\n#1 app\/Fields\/Picklist\/Item.php(181): yii\\db\\Command->execute()\n#2 app\/Fields\/Picklist\/Item.php(131): App\\Fields\\Picklist\\Item->saveToDb()\n#3 modules\/Settings\/Picklist\/actions\/SaveAjax.php(172): App\\Fields\\Picklist\\Item->save()\n#4 app\/Controller\/ExposeMethod.php(68): Settings_Picklist_SaveAjax_Action->edit(Object(App\\Request))\n#5 app\/Controller\/ExposeMethod.php(81): Settings_Picklist_SaveAjax_Action->invokeExposedMethod('edit', Object(App\\Request))\n#6 include\/main\/WebUI.php(188): Settings_Picklist_SaveAjax_Action->process(Object(App\\Request))\n#7 index.php(26): Vtiger_WebUI->process(Object(App\\Request))\n#8 {main}","message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'time_counting' in 'field list'\nFailed to prepare SQL: UPDATE `vtiger_ssalesprocesses_status` SET `time_counting`=:qp0, `record_state`=:qp1 WHERE `ssalesprocesses_statusid`=:qp2"}}`

![Desktop-screenshot](https://user-images.githubusercontent.com/78257/222090251-c1f9d830-1dfe-4928-8625-68cfc349da70.jpg)

**Comment by rskrzypczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/16542
