### ISSUE TITLE
YetiForce CRM 6.3 SecurityFix v8 throws error

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#16935]
I am trying to update YetiForce CRM 6.3 SecurityFix v8 and shows below error,

please assist

['tableName'=>'vtiger_project','columns'=>['targetbudget'=>NULL],'conditions'=>['targetbudget'=>'']] PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: '' in /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php:1302 Stack trace: #0 /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php(1302): PDOStatement->execute() #1 /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute() #2 /www/wwwroot/default/crm/yf/app/Db/Updater.php(120): yii\db\Command->execute() #3 /www/wwwroot/default/crm/yf/cache/updates/updates/init.php(130): App\Db\Updater::batchUpdate() #4 /www/wwwroot/default/crm/yf/cache/updates/updates/init.php(118): YetiForceUpdate->updateData() #5 /www/wwwroot/default/crm/yf/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update() #6 /www/wwwroot/default/crm/yf/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate() #7 /www/wwwroot/default/crm/yf/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import() #8 /www/wwwroot/default/crm/yf/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3() #9 /www/wwwroot/default/crm/yf/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod() #10 /www/wwwroot/default/crm/yf/include/main/WebUI.php(188): Settings_ModuleManager_ModuleImport_View->process() #11 /www/wwwroot/default/crm/yf/index.php(26): Vtiger_WebUI->process() #12 {main} Next yii\db\Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: '' The SQL being executed was: UPDATE `vtiger_project` SET `targetbudget`=NULL WHERE `targetbudget`='' in /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Schema.php:678 Stack trace: #0 /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php(1307): yii\db\Schema->convertException() #1 /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute() #2 /www/wwwroot/default/crm/yf/app/Db/Updater.php(120): yii\db\Command->execute() #3 /www/wwwroot/default/crm/yf/cache/updates/updates/init.php(130): App\Db\Updater::batchUpdate() #4 /www/wwwroot/default/crm/yf/cache/updates/updates/init.php(118): YetiForceUpdate->updateData() #5 /www/wwwroot/default/crm/yf/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update() #6 /www/wwwroot/default/crm/yf/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate() #7 /www/wwwroot/default/crm/yf/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import() #8 /www/wwwroot/default/crm/yf/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3() #9 /www/wwwroot/default/crm/yf/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod() #10 /www/wwwroot/default/crm/yf/include/main/WebUI.php(188): Settings_ModuleManager_ModuleImport_View->process() #11 /www/wwwroot/default/crm/yf/index.php(26): Vtiger_WebUI->process() #12 {main} Additional Information: Array ( [0] => 22007 [1] => 1292 [2] => Truncated incorrect INTEGER value: '' )

**Comment by JEEVAN28** [comment]
please refer https://github.com/YetiForceCompany/YetiForceCRM/issues/15575

facing same issue

**Comment by octavian2204** [comment]
Facing the same issue. Adding integers into the targetbudget did not solve the issue.
```
mysql> SELECT targetbudget FROM `vtiger_project` WHERE targetbudget <> 0 ORDER BY `targetbudget` DESC;
+--------------+
| targetbudget |
+--------------+
|           11 |
|           11 |
+--------------+
```

even truncation of vtiger_project and vtiger_projectcf does not help.

**Comment by JEEVAN28** [comment]
same error reported by https://github.com/YetiForceCompany/YetiForceCRM/issues/16541
