### ISSUE TITLE
[bug] Comment edit has display problem

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#16942]
We have recently updated from 6.1.0 to 6.4.0, I have noticed issue related to comment module on our server, same then I have tried on GitStable and problem is seen but gitDeveloper does not show the problem. Below is details

Go to Account -> Select Account -> Go to Commens -> Add Multiline Comments -> Then Edit same Comment again, it will show in below manner, now if you again try o edit same comment, same is not coming in proper format.

![image](https://user-images.githubusercontent.com/12723595/223351362-b594e63d-3fe9-4cc7-ba82-b0ab7f81c110.png)

![image](https://user-images.githubusercontent.com/12723595/223351706-5c99c50d-619f-4b73-bfa0-be24ca3fbd15.png)

I suppose this bug is handled in GitDeveloper, I tried to search for the same but could not found solution.

Please assist.

Regards
Jeevan Pendhari

**Comment by JEEVAN28** [comment]
Hello any help in this.

Jeevan Pendhari

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski Please help in this matter

**Comment by JEEVAN28** [comment]
Please help in this matter

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/5a7d787c1546940c18e4604a57106490da0774eb

**Comment by JEEVAN28** [comment]
Thanks
