### ISSUE TITLE
[advice]how to lock the record which can only read not edit

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1694]
When a user whose role at the tree is higher check the record,his lower role user can not edit until his cancel the check or he has make some modify.
![snip20150804_2](https://cloud.githubusercontent.com/assets/12697896/9050220/fd7055c0-3a7d-11e5-8bb8-5c8fe985f90a.jpg)

**Comment by 1250572980** [comment]
this function is important at my country:Auditing.when the lower user submit the record,the higher user make the decision of agree or not agree.if agree,the higher user check the record and make it only read for lower user.or if not agree,give the lower user a message to remind he modify.

**Comment by bpabiszczak** [comment]
Please test workflow [Block edition]
