### ISSUE TITLE
Language translation: special signs within variable

### ISSUE THREAD

**Issue by maikst** [YetiForceCompany/YetiForceCRM#170]
in Vtiger.php you find the variable
       "Secretary's Office"    => 'Sekretariat',
in polish translation.

If you translate it with translation module..... this is the result:
        'Secretary's Office' => 'Sekretariat',

As you can see the ' ist the problem.
Yetiforce will stop working.

Translation module must be changed to work with this special signs also in the variablenames.

**Comment by waw555** [comment]
Change to"Secretary\'s Office" => 'Sekretariat',

**Comment by maikst** [comment]
That is not the problem.

We need a solution that normal users will not kill their installation when they change translations.

**Comment by averied** [comment]
We have this same issue. Technically I can edit the file and fix the problem, but a user that's using the translation functionality screws up the installation when apostrophes are in the label files. 

Was this fixed or closed as not resolvable?
