### ISSUE TITLE
[bug] Can't configure new (system wide) filters

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#17000]
# 🐞 bug report

### ⁉️ Describe the bug

When going to the **Software Configuration -> Labels, searching and filtering -> Filters** - Configuration I want to add new filters.
When clicking on "+Add new filter" the page says "Loading, please wait." and keeps staying way.

### 🔥 How to trigger the error

1. Go to 'Software Configuration -> Labels, searching and filtering -> Filters'
2. Click on '+Add new filter'

### 👎 Actual Behavior

See above, as described

### 👍 Expected Behavior

The page for adding new Filters appears (as it worked in the past).

### 👷 Testing

- [X ] I confirm that I tested it at https://gitstable.yetiforce.com
- [X ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

Worked there!

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

* cache/logs/system.log output sent to mail

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4
| Web server (name and version)       |     Apache 2.4.41           |
| PHP                                 |         7.4.33       |
| Browser (name and version)          |        Firefox 111.0.1        |
| Operating System (name and version) |          Ubuntu      |
| Database (name and version)         |       MariaDB 10.3.38          |
| Service Pack version                |         SP 6      |

**Comment by rskrzypczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/16780
