### ISSUE TITLE
[bug] Mailbox login issue

### ISSUE THREAD

**Issue by Ramzan-Ali12** [YetiForceCompany/YetiForceCRM#17007]
i want to login to Mailbox for personal crediential but it not wokrs and it displayed an error login failed.help me for this issue

**Comment by Ramzan-Ali12** [comment]
![Uploading Capture.PNG…]()

**Comment by Ramzan-Ali12** [comment]
![Capture](https://user-images.githubusercontent.com/103037323/229273788-a4ab38a1-b569-41d3-9806-3269c1b20bf6.PNG)

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/229273835-1e23225a-fdf0-44ff-8f94-cd6faded3d63.jpg)

**Comment by rskrzypczak** [comment]
gmail for oauth2 is not supported in the current stable version of YetiForce.
