### ISSUE TITLE
[bug] Can't update english language

### ISSUE THREAD

**Issue by blu-IT** [YetiForceCompany/YetiForceCRM#17001]
# 🐞 bug report

### ⁉️ Describe the bug

When going to the **Software Configuration -> System tools -> Language Management** the update of the english language (Code en-US) does not work. It says: "Error while parsing server responses"

Update of the german language (de-DE) works!

### 🔥 How to trigger the error

1. Go to 'Software Configuration -> System tools -> Language Management'
2. Click on 'Update'

### 👎 Actual Behavior

See above, as described

### 👍 Expected Behavior

The language file is updated, like it worked more than 7 months ago and like it still works for the german language file.

### 👷 Testing

- [X ] I confirm that I tested it at https://gitstable.yetiforce.com
- [X ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

Worked there!

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

* cache/logs/system.log -> no corresponding log entry found.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4
| Web server (name and version)       |     Apache 2.4.41           |
| PHP                                 |         7.4.33       |
| Browser (name and version)          |        Firefox 111.0.1        |
| Operating System (name and version) |          Ubuntu      |
| Database (name and version)         |       MariaDB 10.3.38          |
| Service Pack version                |         SP 6      |

**Comment by mariuszkrzaczkowski** [comment]
Logs? 
https://github.com/YetiForceCompany/YetiForceCRM/issues/9513

**Comment by rskrzypczak** [comment]
This bug is known to us and will be fixed in the next release, however, it is not necessary to update the English language pack as it is included in the update packs.

**Comment by blu-IT** [comment]
@mariuszkrzaczkowski 

> Logs? #9513

Good morning,

unfortunaltely there is no log entry, when I trigger the error.

**Comment by blu-IT** [comment]
@rskrzypczak 

> This bug is known to us and will be fixed in the next release, however, it is not necessary to update the English language pack as it is included in the update packs.

Good morning,

OK, thanks for the information!
