### ISSUE TITLE
[bug] Cannot filter by "Last modified by" column

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#17011]
In list view as well as in custom filters records cannot be filtered by "Last modified by" field. Below screenshot for reference

![last-modified](https://user-images.githubusercontent.com/84110093/229955811-eb792d6c-2cd0-4654-8603-505950b2081a.gif)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/230000276-98869c0a-40e3-4720-86c6-e3d36308bdeb.jpg)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/17156
