### ISSUE TITLE
[bug] Notifications cannot be shared

### ISSUE THREAD

**Issue by garryatbrighton** [YetiForceCompany/YetiForceCRM#17017]
If I try share Notifications records with users after saving Shared with users field is cleared and notification gets assigned to first on The Shared with users field list. Checked locally and on developer version

G.

**Comment by ghost** [comment]
May I handle this issue?

**Comment by rskrzypczak** [comment]
@skan654 Sure, if you understand what the problem is and know how it works.

The 'Share with users' field in the Notifications module works non-standard.
It will always be empty after saving.
Separate entries are created for the users selected in this field.

**Comment by ghost** [comment]
Can I know how the project was built?

**Comment by rskrzypczak** [comment]
https://doc.yetiforce.com/introduction/installation-manual
