### ISSUE TITLE
[bug] Profile Edit Field is Invisible

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#17036]
Hello,

I have renamed Pre-Order Module as Indent via Language. When User in certain profile try to create or edit record he can not see few fields, I checked Profile Edit and noticed that fields are locked and marked as Invisible.

![image](https://user-images.githubusercontent.com/12723595/233376954-b61e42e3-f2e8-4080-bba8-97cb043e1831.png)

What can be the issue ?

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/233432486-edae595d-55d6-4b56-b93b-9b8688472f1b.jpg)

**Comment by JEEVAN28** [comment]
# 🐞 bug report

### ⁉️ Describe the bug

I have renamed Pre-Order Module as Indent via Language. When User in certain profile try to create or edit record he can not see few fields, I checked Profile Edit and noticed that fields are locked and marked as Invisible.


![image](https://user-images.githubusercontent.com/12723595/233376954-b61e42e3-f2e8-4080-bba8-97cb043e1831.png)



### 🔥 How to trigger the error
Problem is on gitstable and gitdeveloper also

### 👎 Actual Behavior

Profile Edit does not allow to make field visible

### 👍 Expected Behavior

Should allow field to make visible / invisible

### 👷 Testing



- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com - same problem noticed here
![image](https://user-images.githubusercontent.com/12723595/233770158-1ebde90c-9468-4647-8d78-5945a42ff68e.png) 
![image](https://user-images.githubusercontent.com/12723595/233770144-5472a9fe-3e8f-4dcd-b537-4822e8940dac.png)

- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com - same issue here also

### 📷 Screenshot of configuration
![ConfReport](https://user-images.githubusercontent.com/12723595/233052558-a33bef7b-df4d-46c1-bcd3-81d0ec1a92b0.png)


### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Additionally, include a screenshot of your browser’s console (e.g. press F12 in Google Chrome).

* cache/logs/phpError.log - This file does not exist in this folder
* cache/logs/system.log - This file does not exist in this folder
* cache/logs/errors.log - I cleaned this file to see if anything is recorded here but does not record any thing.

-->

### 🌍 Your Environment




| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                              | 6.4.0
| Web server (name and version)       |      Apache 2.4.46          |
| PHP                                 |       7.4         |
| Browser (name and version)          |       Crome 112.0.5615.121        |
| Operating System (name and version) |     CentOS 7.9.2009(Py3.7.8)           |
| Database (name and version)         |      MySQL 8.0.20          |
| Service Pack version                |         YetiForce CRM 6.4 Service Pack v6       |

### ❓ Additional context
### ❗️ Inform the community if you solve the problem

**Comment by JEEVAN28** [comment]
Hi, Any help in this matter.

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski please assist in this issue

**Comment by JEEVAN28** [comment]
Now problem is with Internal Ticket Module also, I can not enable fields for the specific profile. @mariuszkrzaczkowski please assist in the matter

**Comment by mariuszkrzaczkowski** [comment]
it's hard to say what the problem might be, it requires an analysis of your CRM

**Comment by JEEVAN28** [comment]
But problem also faced on gitstable and gitdeveloper. Please look into the same

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski please help me in this, problem also faced on gitstable and gitdeveloper. Please look into the same. I have already shared screenshot for the same

**Comment by JEEVAN28** [comment]
@mariuszkrzaczkowski 

https://gitstable.yetiforce.com/ - same problem noticed here

https://user-images.githubusercontent.com/12723595/233770158-1ebde90c-9468-4647-8d78-5945a42ff68e.png

Please assist in the matter.

**Comment by ghost** [comment]
The solution to this problem in my case was simply duplicating the administrator profile and disabling what was unneeded.

**Comment by mariuszkrzaczkowski** [comment]
try this `php cli.php -m System -a reloadModule`
https://doc.yetiforce.com/developer-guides/cli/System/#reload-modules
