### ISSUE TITLE
[bug] Time control Comments bug

### ISSUE THREAD

**Issue by ArniSamano** [YetiForceCompany/YetiForceCRM#17038]
Whatever admin user create comment in Time Control module, this comment is not assigned to user but to administrator. No way to determine who was entered comment

**Comment by ArniSamano** [comment]
Issue got closed as completed. Any PR?

**Comment by mariuszkrzaczkowski** [comment]
It's not a bug, it's a new feature

**Comment by ArniSamano** [comment]
If that is not a joke, I may missing something? Any documentation?
Here is HR Department where people do checking employees timesheets and they need to often comment certain bits. Here is trouble with comments owners. 6 people working in HR and 57 users have to enter own time control record every day

**Comment by garryatbrighton** [comment]
Also interested, why all comments are assigned to administrator. Maybe community can help? Anyone?
