### ISSUE TITLE
Announcements bug 

### ISSUE THREAD

**Issue by ArniSamano** [YetiForceCompany/YetiForceCRM#17037]
If I assign announcement to Group, and one year later I add new user and assign it to this group, he will receive all historical announcements created through whole previous year.
Doesnt seems to be correct..

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/233910904-1d51d8d6-7666-43ae-b1db-1500c13eaf70.jpg)

**Comment by ArniSamano** [comment]
I believe I described precisely bug. It doesnt relay on my environment, as the same is on dev. 
To reproduce:

1. Create some group and assign to this group 2 users
2. Create announcement for above group (users will see it)
3. Add new user and assign to above group
4. Login as this new user and you will get announcement

Imagine you got new employee 3 years after first announcement has been posted, and announcements were posted 3 times a week? He gonna die clicking and admin will be embarrassed

**Comment by garryatbrighton** [comment]
This is not good. I have 4 users and been doing announcements (instructions) for 5 months and YES created new user with the same group I have been assigning announcements before and what I need to do from this user profile is to keep clicking not relevant popups until all gone.

**Comment by s2b-git** [comment]
Yes. Have been busy clicking old announcements too ;-)

**Comment by Marshal4582** [comment]
It is pretty annoying bug. We creating very often new users and before giving them access to system admin have to click-out all historical announcements, otherwise confusion and lots of unnecessary questions.

**Comment by Marco31Bike** [comment]
Ou!!! This is nasty bug!!!  Our new user spent 30 min clicking past announcements completely irrelevant to his duties. 
It should have top priority as it very shameful for companies

**Comment by konadrian** [comment]
I've tried to reproduce this problem. On current dev version, I can't reproduce this error.
![Notifications](https://github.com/YetiForceCompany/YetiForceCRM/assets/3193498/1dd59670-29bf-49c8-bc9a-dbb5d9f17a15)

**Comment by Marco31Bike** [comment]
Did you tried announcements? It not about notifications but Announcements

**Comment by konadrian** [comment]
A work of this functionality is programmed like you mentioned. This is a way how it was implemented. To manage with this, you can delete an announcement or change its status to different from `Published` it should solve your problem. Any other changes require programming work

**Comment by Marco31Bike** [comment]
This implementation is a clear bug. Regarding status... by default system locking edition of announcements once set Published (honestly no idea why this is like that).
The way it works now, doesn't go well with serious corporate system implementation. Please reconsider reworking this part. 
As an example: I have been asked to deal with migration from VT where admin have over 1000 users and they all the time changing (adding, activating, deactivating, erasing). Imagine you add 5 users to system with announcements running constantly for 6 months? Plus in this case, the only way is to use groups as a target of announcement as there are too  many users
