### ISSUE TITLE
[bug] Add record in Quote Module hangs system

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#17032]
# 🐞 bug report

### ⁉️ Describe the bug

I am facing this issue since morning, CRM is working properly for all modules except Quote Module. In case of Quote Module, if I edit / View record, it works perfectly OK. but when I try to Add record in Quote Module (Only) system hangs.

### 🔥 How to trigger the error
Error is only on my server. I checked with Stable and developer version, same is not replicable.

### 👎 Actual Behavior

System Hangs on Add Record in Quote Module (Only)

### 👍 Expected Behavior

Should allow to add record in Quote Module (Till yesterday same was working perfectly Ok)

### 👷 Testing

- [✔️] I confirm that I tested it at https://gitstable.yetiforce.com - Can not see any problem, I can create quote here
- [✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com - Can not see any problem, I can create quote here

### 📷 Screenshot of configuration
![ConfReport](https://user-images.githubusercontent.com/12723595/233052558-a33bef7b-df4d-46c1-bcd3-81d0ec1a92b0.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Additionally, include a screenshot of your browser’s console (e.g. press F12 in Google Chrome).

* cache/logs/phpError.log - This file does not exist in this folder
* cache/logs/system.log - This file does not exist in this folder
* cache/logs/errors.log - I cleaned this file to see if anything is recorded here but does not record any thing.

I checked error files in wwwlogs folder on my server. In this folder, i found file access_log file in which I noticed below error every time I try to add record in Quote Module

192.168.1.245 - - [19/Apr/2023:16:01:16 +0530] "-" 408 -
192.168.1.245 - - [19/Apr/2023:16:04:13 +0530] "-" 408 -

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                              | 6.4.0
| Web server (name and version)       |      Apache 2.4.46          |
| PHP                                 |       7.4         |
| Browser (name and version)          |       Crome 112.0.5615.121        |
| Operating System (name and version) |     CentOS 7.9.2009(Py3.7.8)           |
| Database (name and version)         |      MySQL 8.0.20          |
| Service Pack version                |         YetiForce CRM 6.4 Service Pack v6       |

### ❓ Additional context
Once CRM hangs then only when I close browser and re-login I am able to do other work in CRM.

**Comment by JEEVAN28** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/16994

Can this be issue as I remember before clearing log, i saw error related to currency.

**Comment by garryatbrighton** [comment]
check other inventory module. If the same effect, that it is currency blocker. It it design issue as system stability depends on connection to  third-party resources

**Comment by rskrzypczak** [comment]
> cache/logs/system.log - This file does not exist in this folder

enable CRM logs: 
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/Debug.php#L20-L33 _($LOG_TO_FILE and $LOG_LEVELS)_
https://doc.yetiforce.com/developer-guides/debug#yetiforce-system-logs

**Comment by merckaa** [comment]
After updating to 6.5 the system hangs when adding quotes

> 2024-01-04 13:48:16.3713 [error][] - Cannot access offset of type string on string
TypeError: Cannot access offset of type string on string in /home/aporteso/public_html/gestao/modules/Settings/CurrencyUpdate/bankmodels/NBP.php:137
Stack trace:
#0 /home/aporteso/public_html/gestao/modules/Settings/CurrencyUpdate/models/Module.php(83): Settings_CurrencyUpdate_NBP_BankModel->getRates(Array, '2024-01-03', false)
#1 /home/aporteso/public_html/gestao/modules/Settings/CurrencyUpdate/models/Module.php(316): Settings_CurrencyUpdate_Module_Model->fetchCurrencyRates('2024-01-03')
#2 /home/aporteso/public_html/gestao/vtlib/Vtiger/Functions.php(589): Settings_CurrencyUpdate_Module_Model->getCRMConversionRate('BRL', 'USD', '2024-01-03')
#3 /home/aporteso/public_html/gestao/modules/Vtiger/inventoryfields/Currency.php(65): vtlib\Functions::getConversionRateInfo(2)
#4 /home/aporteso/public_html/gestao/cache/templates_c/basic/bd1f5c1fff33a9333cc30425343ce751b85841c1_0.file.EditViewCurrency.tpl.php(37): Vtiger_Currency_InventoryField->getCurrencyParam(Array)
#5 /home/aporteso/public_html/gestao/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6595c14b82d159_37294177(Object(Smarty_Internal_Template))
#6 /home/aporteso/public_html/gestao/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#7 /home/aporteso/public_html/gestao/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#8 /home/aporteso/public_html/gestao/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render()
