### ISSUE TITLE
[bug] chrome-php/chrome crashes with Chrome ^111.*

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#17039]
Hi,
probably "YetiForce PDF Premium" crashes with Google Chrome ver. 111.* and higher.
Last working Chrome version was 110.*
bug was fixed in chrome-php/chrome v1.8.1, a month ago

https://github.com/chrome-php/chrome/issues/492

**Comment by mariuszkrzaczkowski** [comment]
there is already an up-to-date version in the development version

**Comment by DarioGui** [comment]
Morning everyone!
After countless edits... verifications etc. now I have come to the point that in the log I see:
2023-06-07 15:25:46.7884 [warning][[App\Pdf\Drivers\Chromium]] - Wrench\Exception\HandshakeException: No accept header receieved on handshake response in...

if i understand correctly it is a Chrome problem. say i can ask the hosting to update the chrome package?
Or should I have them downgrade it?

**Comment by mariuszkrzaczkowski** [comment]
look at this https://github.com/chrome-php/chrome/issues/492

**Comment by davide-alghi** [comment]
@DarioGui 
with last version of php-chrome you can work with the latest Google Chrome (endless)
you can update your 3rd-party packages by running a "composer update" in the root of your YF instance

make a backup before proceeding!

**Comment by DarioGui** [comment]
@davide-alghi my version is 112.0.5615.49 and not 111... I had understood that the problem was solved with versions after 111
I get to backup :)
But I'm having trouble (I'm no good) making "update your 3rd-party packages by running a "composer update" in the root of your YF instance"
Could you tell me in detail how to proceed?

**Comment by davide-alghi** [comment]
@DarioGui 
the problem is in php-chrome package.
up to version 110 it worked. if you use version 111.x.x.x you need to update php-chrome to the current latest one
if you are not expert skip my suggestion or get help from a senior developer
