### ISSUE TITLE
[BUG] Add Organizations

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1704]
![animation 107](https://cloud.githubusercontent.com/assets/1402355/9052997/0c494bb2-3a77-11e5-88ac-f52f8d55d9ee.gif)

![animation 108](https://cloud.githubusercontent.com/assets/1402355/9053041/c5a7ee6a-3a77-11e5-9e2d-31bb43ef9e78.gif)

**Comment by rskrzypczak** [comment]
Hello,
I could not see the presented error.
The cause of the missing "test" record on the record list are most likely some added filter conditions for this view.
