### ISSUE TITLE
[bug] Time control error after adding as a related tab o custom module

### ISSUE THREAD

**Issue by garryatbrighton** [YetiForceCompany/YetiForceCRM#17055]
Working on 6.4, checked on my two instances. System config is perfect.
When adding Time Control module to related list of Custom module, and trying to access this tab, system hangs and returning following:

2023-05-02 12:37:54.1415 [error][] - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vtiger_osstimecontrol.sum_time' in 'field list'
Failed to prepare SQL: SELECT SUM(vtiger_osstimecontrol.sum_time) FROM (SELECT DISTINCT `vtiger_osstimecontrol`.`sum_time` AS `sum_time`, `vtiger_osstimecontrol`.`name` AS `name`, `vtiger_osstimecontrol`.`date_start` AS `date_start`, `vtiger_osstimecontrol`.`time_start` AS `time_start`, `vtiger_osstimecontrol`.`due_date` AS `due_date`, `vtiger_osstimecontrol`.`time_end` AS `time_end`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_osstimecontrol`.`osstimecontrolid` AS `id` FROM `vtiger_osstimecontrol` INNER JOIN `vtiger_crmentity` ON vtiger_osstimecontrol.osstimecontrolid = vtiger_crmentity.crmid INNER JOIN `u_yf_mycustommodule_osstimecontrol` ON u_yf_mycustommodule_osstimecontrol.relcrmid = vtiger_crmentity.crmid WHERE (`vtiger_crmentity`.`deleted`=:qp0) AND (`u_yf_mycustommodule_osstimecontrol`.`crmid`=:qp1)) `c`
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vtiger_osstimecontrol.sum_time' in 'field list' in /var/www/html/vendor/yetiforce/yii2/db/Command.php:267

**Comment by CHILLTH** [comment]
Exactly the same here. It looks like time control is standard entity module, but someting is wrong. Anybody have idea?

**Comment by rskrzypczak** [comment]
Yes, this error occurs if, for example, an M:M relationship has been created with the Time control module.
By default, each relationship with the Time control module is on a 1:M relationship.

**Comment by s2b-git** [comment]
Interesting for me too. How to  extend relation type to MM in this module?
