### ISSUE TITLE
[BUG] Image in Quotes PDF Template

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1706]
![animation 110](https://cloud.githubusercontent.com/assets/1402355/9053328/6f88cf04-3a7c-11e5-87b1-517b48df6240.gif)

**Comment by rskrzypczak** [comment]
Please enable header :)
![pdf2](https://cloud.githubusercontent.com/assets/10221999/9078635/2daaffce-3b41-11e5-909d-46bdf79488b6.jpg)
