### ISSUE TITLE
[bug] Do not create new record, if related record exists - doesnt repect itself

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#17060]
Create entity record via workflow. If I mark "Do not create new record, if related record exists" it still creating new record.

Best

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/236550596-283b0813-3ef6-4054-98bf-71ae29c1c294.jpg)

**Comment by ArniSamano** [comment]
Hi It doesnt work for me either. If this is not a bug, can you guys explain how it does suppose to works?
