### ISSUE TITLE
Problem with DAV integration for calendar in Outlook

### ISSUE THREAD

**Issue by bfeddes** [YetiForceCompany/YetiForceCRM#17078]
# 🐞 bug report

**### ⁉️ Describe the bug**

When I create an event on the Outlook calendar, it then will integrate perfectly with the Yetiforce calendar, as expected, through CalDav Synchronizer. However, when I create an event on the Yetiforce calendar, and try to integrate it to the Outlook calendar, a NullException error occurs.I already read a discussion where a different Yeti user had this issue, and that discussion was unable to resolve my problem. I attached some screenshots along with a description of what isn't working.

**### 🔥 How to trigger the error**

1. Go to Yetiforce Calendar
2. Click on Create Event
3. Fill out the info
4. The event will be created, but when CROM runs and the CalDav synchronizes, the following error occurs:
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/112420814/186652a7-b9e2-4abd-a073-bfa68387fdbf)

**### 👎 Actual Behavior**

I get the error as shown in the screenshot above.

**### 👍 Expected Behavior**

I want the Synchronization from Yeti to Outlook to work the same way as the Synchronization from Outlook to Yeti, with the event I created in Yeti to be added to the calendar in Yeti, without an error.

### 📷 Screenshot of configuration
![ConfReport](https://github.com/YetiForceCompany/YetiForceCRM/assets/112420814/3d2e30e8-1bfa-41bf-b908-591b53730ff4)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

**Included in the email I sent**

**Comment by mariuszkrzaczkowski** [comment]
you have a problem with the configuration of the web server, check the rules
https://github.com/YetiForceCompany/YetiForceCRM/blob/7961448df37bf133aba558f831e7c5cd046381b2/.htaccess#L18-L23

**Comment by bfeddes** [comment]
My rules are configured identically to what you have above. Please let me know if I should change any of them, and if so what should I change them to? I included a screenshot of the configuration rules in the yetiforce/.htaccess directory below.

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/112420814/e1c166f1-e0b7-47f9-bbe1-1e3ef1f08fe5)

**Comment by mariuszkrzaczkowski** [comment]
looks like there is a problem with the authorization header, it would require a deeper analysis of more logs
