### ISSUE TITLE
[IMPROVE DESIGN] Product Descriptions in Calculations

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1707]
![animation 111](https://cloud.githubusercontent.com/assets/1402355/9053507/605a5370-3a7e-11e5-92f0-034966f59148.gif)

**Comment by bpabiszczak** [comment]
Product modules will be completely redesigned [we have basically finished it, soon you'll be able to test it]. The new modules will be introduced in 2.2 or 2.3. If you still dislike the description field then, you can open another issue.
