### ISSUE TITLE
Upgrade Yetiforce 6.4 failed [bug] 

### ISSUE THREAD

**Issue by aleterracciano** [YetiForceCompany/YetiForceCRM#17077]
Good evening, I tried to upgrade from 6.3.0 to 6.4 without success. Yetiforce gave me an error message.
Below is the error

**Error:**

SQLSTATE[HY000]: General error: 1005 Can't create table `compcrce22_yettest`.`roundcube_responses` (errno: 150 "Foreign key constraint is incorrectly formed") The SQL being executed was: CREATE TABLE `roundcube_responses` ( `response_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `user_id` int(10) unsigned NOT NULL, `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `data` longtext COLLATE utf8mb4_unicode_ci NOT NULL, `is_html` tinyint(1) NOT NULL DEFAULT 0, `changed` datetime NOT NULL DEFAULT '1000-01-01 00:00:00', `del` tinyint(1) NOT NULL DEFAULT 0, PRIMARY KEY (`response_id`), KEY `user_responses_index` (`user_id`,`del`), CONSTRAINT `user_id_fk_responses` FOREIGN KEY (`user_id`) REFERENCES `roundcube_users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

**My configuration is:**

![ConfReport (6)](https://github.com/YetiForceCompany/YetiForceCRM/assets/53528784/29cd4165-38c3-494f-b983-142bd2cf693f)

**Comment by aleterracciano** [comment]
Hi, today I tried again after reloading the database. The error message that Yetiforce shows me is as follows.

Error: 
SQLSTATE[HY000]: General error: 1005 Can't create table `compcrce22_yettest`.`roundcube_responses` (errno: 150 "Foreign key constraint is incorrectly formed") The SQL being executed was: CREATE TABLE `roundcube_responses` ( `response_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `user_id` int(10) unsigned NOT NULL, `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `data` longtext COLLATE utf8mb4_unicode_ci NOT NULL, `is_html` tinyint(1) NOT NULL DEFAULT 0, `changed` datetime NOT NULL DEFAULT '1000-01-01 00:00:00', `del` tinyint(1) NOT NULL DEFAULT 0, PRIMARY KEY (`response_id`), KEY `user_responses_index` (`user_id`,`del`), CONSTRAINT `user_id_fk_responses` FOREIGN KEY (`user_id`) REFERENCES `roundcube_users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

**Comment by ghost** [comment]
It seems there is a database issue, most notably within the foreign key.

Perhaps the foreign key and referencing columns are of different types?

**Comment by ciberfox** [comment]
check if you have same project not completed or not configured.
