### ISSUE TITLE
Creating Account / Fresh Setup - FAILED / Solution

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#1709]
Hello everyone,

after days and weeks i found the explaination why i was not able to create a new entity in a fresh setup of YF CRM.

I just wanted to create quickly a new contact an filled out all mandatory fields and try to save.
ERROR!!!
Now i found out that there is another mandatory field for saving the entity, but it is not mandatory set in the CRM - SO IT FAILS!!

the field has the name "Inheritsharing" in the DATABASE and in CRM (depends on translation) it is the field where you can SHARE the contact/company etc with other users.

THATS IT !!! - Now i was really happy finding out what prevents me from using YETI FORCE - until i found out that i can create reports (detailed) BUT it doesn't save the columns i've selected, so the REPORT is EMPTY.

Best regards,
Ralph

**Comment by bpabiszczak** [comment]
Please read this: https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
