### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Nibi-git** [YetiForceCompany/YetiForceCRM#17107]
Hello!
I'm trying to assign different pdf templates to different departments (organizations).
The simplest steps to reproduce the bug is to simply change the Organization for an already existing template.
Then click "Next" and you can see that the selected setting has not been saved.

The bug is equally reproduced in the stable and development versions.
Maybe it's not a bug, but I just don't know some settings?

I also looked at the contents of the mysql table a_yf_pdf and did not find a field to store the organization id. Very strange.

Best regards!
Roman

![1](https://github.com/YetiForceCompany/YetiForceCRM/assets/6334382/1ed11d69-4cd1-4ada-bb13-10fdf04ae7d9)
![2](https://github.com/YetiForceCompany/YetiForceCRM/assets/6334382/0e26a3d6-cdea-419c-85c0-96607585163f)

**Comment by rskrzypczak** [comment]
There is no error here.
The fields in the "Variables to copy" block are not saved anywhere.
They only serve as an aid for copying variables that are placed in subsequent blocks.
Same with the "Organization" field. Changing the value of this field changes the copied variables from the "Company details" field.
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/10221999/12d4b410-588c-4eb7-b1a0-0b9a0a784f29)
