### ISSUE TITLE
[bug] can not enter the app after installation via Softaculous 

### ISSUE THREAD

**Issue by avelinovavds** [YetiForceCompany/YetiForceCRM#17124]
Hi,

I am having an issue after installation of YetiForce via Softaculous . Once the installation completed i thry to log in and once i open the link i get following error 
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/135955929/f4fd0ea5-5601-4fe8-886a-013e1d84b2f9)

Please help me to solve this issue

**Comment by mariuszkrzaczkowski** [comment]
![github](https://github.com/YetiForceCompany/YetiForceCRM/assets/10198654/28298127-57fb-4ec2-b2cc-2c8e62b57106)
