### ISSUE TITLE
Php Warrning in  Financial summary group

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1713]
![phpwarning](https://cloud.githubusercontent.com/assets/4824588/9087796/28b4ace4-3b8d-11e5-9f06-543c7564200a.PNG)

gitdeveloper version, after create new opportunity without enter anything to Forecast Amountf field.

after edit can't save becouse:
![phpwarning_2](https://cloud.githubusercontent.com/assets/4824588/9087847/6cfe50ee-3b8d-11e5-8279-784922a09451.PNG)

**Comment by rskrzypczak** [comment]
The indicated error occurs only in the developer version. The lack of 'Number Of Currency Decimals' in user's settings is the cause of it.

**Comment by florek41** [comment]
I've just tested gitmaster version and error occurs too.
Even after change 'Number Of Currency Decimals' to 2.
How should I configure it ?
