### ISSUE TITLE
Update related record - not working

### ISSUE THREAD

**Issue by ArniSamano** [YetiForceCompany/YetiForceCRM#17144]
As for a weeks I dont have clarification on below, I assume this is bug as it not works in my local server as well as developer.

Cheers

### Discussed in https://github.com/YetiForceCompany/YetiForceCRM/discussions/17083

<div type='discussions-op-text'>

<sup>Originally posted by **ArniSamano** May 15, 2023</sup>
Hi All
Get a bit lost with system workflow and would appreciate little help.
I have two custom modules A,B
When I change value of text field in module A, in related Module B certain text field should grab text strings from Module A and set it in own text field.
Tied 1:M, M:M relations, mapped modules, but it doesn't seems to work as expected. Can anybody tell me what I missed?
What conditions should be met to successfully use "update related record" task in workflow? 

Thanks</div>

**Comment by Marshal4582** [comment]
I confirm the same

**Comment by Marshal4582** [comment]
Worth to mention that it doesn't work in developer either.
This one is pretty essential to keep some of business flow in automated manner


> I confirm the same

**Comment by JEEVAN28** [comment]
@ArniSamano I am facing same issue, can you write here what you have done regarding this ?
