### ISSUE TITLE
Cannot edit link in workflow task Send Email

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#17163]
### Discussed in https://github.com/YetiForceCompany/YetiForceCRM/discussions/17154

<div type='discussions-op-text'>

<sup>Originally posted by **Marshal4582** June 21, 2023</sup>
Hi

Cannot enter link url in dialog of workflow task Send Email. Dialog seems to be partially inactive and console says:
Duplicate form field id in the same form
Multiple form field elements in the same form have the same id attribute value. This might prevent the browser from correctly autofilling the form.
To fix this issue, use unique id attribute values for each form field.

Bug or config?

</div>

**Comment by ArniSamano** [comment]
Yes. same in my 6.4 x3.  Hindering work a lot...
