### ISSUE TITLE
Error in reports

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#1716]
array (
    'file' => '/home/yetiforce1/domains/test.yetiforce.com/public_html/modules/Reports/ReportRun.php',
    'line' => 3157,
    'function' => 'pquery',
  ),
  2 => 
  array (
    'file' => '/home/yetiforce1/domains/test.yetiforce.com/public_html/modules/Reports/models/Record.php',
    'line' => 675,
    'function' => 'GenerateReport',
  ),
  3 => 
  array (
    'file' => '/home/yetiforce1/domains/test.yetiforce.com/public_html/modules/Reports/views/Detail.php',
    'line' => 48,
    'function' => 'getReportData',
  ),
  4 => 
  array (
    'file' => '/home/yetiforce1/domains/test.yetiforce.com/public_html/include/main/WebUI.php',
    'line' => 71,
    'function' => 'preProcess',
  ),
  5 => 
  array (
    'file' => '/home/yetiforce1/domains/test.yetiforce.com/public_html/include/main/WebUI.php',
    'line' => 195,
    'function' => 'triggerPreProcess',
  ),
  6 => 
  array (
    'file' => '/home/yetiforce1/domains/test.yetiforce.com/public_html/index.php',
    'line' => 23,
    'function' => 'process',
  ),
)

Query Failed:select DISTINCT vtiger_account.accountname AS 'Accounts__Account__Name', (CASE WHEN vtiger_account.parentid NOT LIKE '' THEN (CASE WHEN trim(vtiger_accountAccounts.accountname) NOT LIKE '' THEN trim(vtiger_accountAccounts.accountname) ELSE '' END) ELSE '' END) AS Accounts__Member__Of, vtiger_account.account_type AS 'Accounts__Type', trim(CONCAT(vtiger_lastModifiedByAccounts.last_name,' ',vtiger_lastModifiedByAccounts.first_name)) AS Accounts__Last__Modified__By, case when (vtiger_crmentityAccounts.was_read='1')then 'yes' else case when (vtiger_crmentity.crmid !='') then 'no' else '-' end end AS 'Accounts__Was__read', vtiger_account.payment_balance AS 'Accounts__Payment__balance', vtiger_crmentity.crmid AS "Accounts__LBL_ACTION" from vtiger_account inner join vtiger_crmentity on vtiger_crmentity.crmid=vtiger_account.accountid left join vtiger_groups as vtiger_groupsAccounts on vtiger_groupsAccounts.groupid = vtiger_crmentity.smownerid left join vtiger_account as vtiger_accountAccounts on vtiger_accountAccounts.accountid = vtiger_account.parentid left join vtiger_users as vtiger_usersAccounts on vtiger_usersAccounts.id = vtiger_crmentity.smownerid left join vtiger_groups on vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_users on vtiger_users.id = vtiger_crmentity.smownerid left join vtiger_users as vtiger_lastModifiedByAccounts on vtiger_lastModifiedByAccounts.id = vtiger_crmentity.modifiedby WHERE vtiger_account.accountid > 0 AND vtiger_crmentity.deleted=0 and (( trim(case when (vtiger_usersAccounts.last_name NOT LIKE '') then CONCAT(vtiger_usersAccounts.last_name,' ',vtiger_usersAccounts.first_name) else vtiger_groupsAccounts.groupname end) = 'Test Test' and vtiger_crmentity.createdtime BETWEEN '2015-07-01 00:00:00' AND '2015-07-31 23:59:59' ) ) LIMIT 0, 1000::ADODB error Query Failed:select DISTINCT vtiger_account.accountname AS 'Accounts__Account__Name', (CASE WHEN vtiger_account.parentid NOT LIKE '' THEN (CASE WHEN trim(vtiger_accountAccounts.accountname) NOT LIKE '' THEN trim(vtiger_accountAccounts.accountname) ELSE '' END) ELSE '' END) AS Accounts__Member__Of, vtiger_account.account_type AS 'Accounts__Type', trim(CONCAT(vtiger_lastModifiedByAccounts.last_name,' ',vtiger_lastModifiedByAccounts.first_name)) AS Accounts__Last__Modified__By, case when (vtiger_crmentityAccounts.was_read='1')then 'yes' else case when (vtiger_crmentity.crmid !='') then 'no' else '-' end end AS 'Accounts__Was__read', vtiger_account.payment_balance AS 'Accounts__Payment__balance', vtiger_crmentity.crmid AS "Accounts__LBL_ACTION" from vtiger_account inner join vtiger_crmentity on vtiger_crmentity.crmid=vtiger_account.accountid left join vtiger_groups as vtiger_groupsAccounts on vtiger_groupsAccounts.groupid = vtiger_crmentity.smownerid left join vtiger_account as vtiger_accountAccounts on vtiger_accountAccounts.accountid = vtiger_account.parentid left join vtiger_users as vtiger_usersAccounts on vtiger_usersAccounts.id = vtiger_crmentity.smownerid left join vtiger_groups on vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_users on vtiger_users.id = vtiger_crmentity.smownerid left join vtiger_users as vtiger_lastModifiedByAccounts on vtiger_lastModifiedByAccounts.id = vtiger_crmentity.modifiedby WHERE vtiger_account.accountid > 0 AND vtiger_crmentity.deleted=0 and (( trim(case when (vtiger_usersAccounts.last_name NOT LIKE '') then CONCAT(vtiger_usersAccounts.last_name,' ',vtiger_usersAccounts.first_name) else vtiger_groupsAccounts.groupname end) = 'Test Test' and vtiger_crmentity.createdtime BETWEEN '2015-07-01 00:00:00' AND '2015-07-31 23:59:59' ) ) LIMIT 0, 1000::->Unknown column 'vtiger_crmentityAccounts.was_read' in 'field list'

**Comment by MaciejStencel** [comment]
Nie potrafiłem wygenerować błędu. Poprawnie buduje zapytanie sql z filtrem po polu "was_read".
