### ISSUE TITLE
Mail Scanner only download once then need manual interaction[bug] 

### ISSUE THREAD

**Issue by gsbotes** [YetiForceCompany/YetiForceCRM#17175]
# 🐞 bug report

### ⁉️ Describe the bug
Mail scanner works and downloads mail, but only does it once, Cron runs with no errors, server config has no errors.
When I stop mail scanner manually, it starts again, downloads and relates emails, but nothing...
Mail scanner keeps showing "realization | apache2handler -"
-- | --

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by mariuszkrzaczkowski** [comment]
logs ?

**Comment by gsbotes** [comment]
<img width="1143" alt="Screenshot 2023-07-04 at 16 55 50" src="https://github.com/YetiForceCompany/YetiForceCRM/assets/138553221/20f3f9a4-7a79-42c1-9474-02a6b16e8f30">

**Comment by mariuszkrzaczkowski** [comment]
![github](https://github.com/YetiForceCompany/YetiForceCRM/assets/10198654/fe12b693-d64c-482a-92ae-1799817322df)

**Comment by ArniSamano** [comment]
delete from vtiger_ossmails_logs where status = 1 limit 1;

**Comment by rskrzypczak** [comment]
Fixed long time ago ;)
Upgrade your system
