### ISSUE TITLE
[Enhancement] Active fields

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1718]
There should be a possibility to disable displaying fields in the dispay / edit masks without breaking the software logic. Especially, it should be possible to disable displaying any read-only field. For example, in "Opportunities", the field "Closed Time" must always be Active (i.e. displayed) although for specific business usages, this information is of no added value to display.

It is currently not clear if a field marked inactive (not marked active) may break the system.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1717
