### ISSUE TITLE
[Question/Issue] Translation Question/Issue

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1719]
1. Leads -> Create new filter
2. Name filter 'Dashboard'
3. Filter is shown as 'My Home Page' rather than 'Dashboard'

Open question: Should user specified names be translated?
Personal view: no
Alternative: user specified names are translated using a special translation table and not the generic one used for the modules
Current status: They are translated in the module context in which they are used

**Comment by bpabiszczak** [comment]
This is how it initially worked. We changed it because it gave more opportunities. Changing this mechanism on individual filters doesn't change anything because they often are public. 
I'm not sure if we should change it, I guess not.
