### ISSUE TITLE
Issue in SMTP Configuration

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#17199]
# 🐞 bug report

### ⁉️ **Add Record in SMTP Configuration Hangs up on Local Server for indefinite time**

I have used same ID and Password via RoundCube and for MailScanner, it works. but while configuring SMTP Configuration after save button, web page hang up and finally need to close. SMTP Configuration is not Saved. No error thrown.

This issue is related to GMAIL configuration only, when used other provider email id configuration saved properly.

### 🔥 How to trigger the error

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/12723595/04321841-caa5-45ab-b967-cc28ed34ef22)

1. Go to 'System Settings'
2. Click on 'Mail Tools'
3. Scroll down to 'SMTP Configuration'
4. Add SMTP Record for GMAIL with app password (we are not using less secure app due to security reasons)
5. SMTP connection is to setup

### 👎 Actual Behavior
On Save web page hangs up on Local Server, no error is shown
On gitdeveloper.yetiforce.com below error is shown
SMTP ERROR: Failed to connect to server: Connection refused (111)

### 👍 Expected Behavior
SMTP Configuration should save

### 👷 Testing

- [ Y] I confirm that I tested it at https://gitstable.yetiforce.com
- [ Y] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4.0
| Web server (name and version)       |    apache 2.4.46            |
| PHP                                 |           7.4     |
| Browser (name and version)          |     chrome           |
| Operating System (name and version) |        linux        |
| Database (name and version)         |    mysql 8.0            |

**Comment by ghost** [comment]
I had this issue too, I just manually added them to the database under table s_yf_mail_smtp

**Comment by mariuszkrzaczkowski** [comment]
logs

**Comment by ghost** [comment]
2023-10-26 20:21:30.3046 [info][[yii\db\Connection::open]] - Opening DB connection: mysql:host=localhost;dbname=yetiforce;port=3306
2023-10-26 20:21:30.3052 [info][[yii\db\Command::query]] - SELECT EXISTS(SELECT * FROM `vtiger_users` WHERE (`id`=1) AND ((`status`='Active') AND (`deleted`=0)))
2023-10-26 20:21:30.3056 [info][[yii\db\Command::query]] - SELECT EXISTS(SELECT * FROM `vtiger_users` WHERE `id`=1)
2023-10-26 20:21:30.3136 [info][[yii\db\Command::query]] - SELECT `name` FROM `a_yf_settings_modules` WHERE `status`=1
2023-10-26 20:21:30.3138 [info][[yii\db\Connection::open]] - Opening DB connection: mysql:host=localhost;dbname=yetiforce;port=3306
2023-10-26 20:21:30.3141 [info][[yii\db\Command::query]] - SELECT * FROM `a_yf_encryption` WHERE `target`=0 LIMIT 1
2023-10-26 20:21:30.3466 [error][] - Call to undefined method App\Mailer::test()
Error: Call to undefined method App\Mailer::test() in /var/www/html/modules/Settings/MailSmtp/actions/SaveAjax.php:58
Stack trace:
#0 /var/www/html/app/Controller/ExposeMethod.php(68): Settings_MailSmtp_SaveAjax_Action->updateSmtp()
#1 /var/www/html/app/Controller/ExposeMethod.php(81): Settings_Vtiger_Basic_Action->invokeExposedMethod()
#2 /var/www/html/include/main/WebUI.php(188): Settings_Vtiger_Basic_Action->process()
#3 /var/www/html/index.php(26): Vtiger_WebUI->process()
#4 /var/www/html/public_html/index.php(13): require('/var/www/html/i...')
#5 {main}
2023-10-26 20:21:30.3017 [info][[application]] -

**Comment by mariuszkrzaczkowski** [comment]
looks like an update error and server configuration problems
