### ISSUE TITLE
[bug] The field "Related to" is not displayed in the Project task creation form

### ISSUE THREAD

**Issue by Vic-Skr** [YetiForceCompany/YetiForceCRM#17196]
# 🐞 bug report

Hello.
The field «Related to» is not displayed in the Project task creation form (neither in the full form nor in the quick creation form). In the form of editing an already existing task, the «Related to» field is also not displayed. At the same time, in the field editor for Project tasks, the field «Related to»  is present and configured as mandatory with display in the quick creation form - and these settings, unfortunately, cannot be changed.
It would be ideal if the field «Related to»  is displayed in the form of creating a project task and in the settings it could be made optional, like the "Project milestones" field for example.
On your demo of the stable version https://gitstable.yetiforce.com/, this problem is also present, and on the demo version of the developer https://gitdeveloper.yetiforce.com/, everything works as expected.
I am attaching screenshots of the full and short form for creating a project task and field settings in the field editor - as is (from our system) and as it should be (from the developer's demo).
Since it is not possible to remove the «Related to» field for a Project Issue, therefore we cannot set up the association of Project tasks with projects ourselves.

### 🔥 How to trigger the error

1. Go to Project Management-Project tasks   or  Quick create-Project task
2. Click on Add record

### 👎 Actual Behavior
The field «Related to» is not displayed .
![As it is Project task Full form without Related to](https://github.com/YetiForceCompany/YetiForceCRM/assets/139356687/898cc81b-4a39-4f99-a340-3006bb2decf8)
![As it is Project task Quick form without Related to](https://github.com/YetiForceCompany/YetiForceCRM/assets/139356687/ccd3cbfb-aa62-48d3-aac8-eb217063a62f)
![As it is File Editor for Project task with Related to](https://github.com/YetiForceCompany/YetiForceCRM/assets/139356687/0767f6d4-a869-4faf-942a-120efc403f8b)

### 👍 Expected Behavior
The field «Related to» is displayed in the form and is available for filling.
![It should be Project task Full form with Related to](https://github.com/YetiForceCompany/YetiForceCRM/assets/139356687/2d02092c-5ceb-4a41-a17e-55d730d2ba40)
![It should be Project task Quick form with Related to](https://github.com/YetiForceCompany/YetiForceCRM/assets/139356687/0f6834ee-ab0d-4935-babe-23e13297e322)

### 👷 Testing

- [+] I confirm that I tested it at https://gitstable.yetiforce.com    -  the same problem
- [+] I confirm that I tested it at https://gitdeveloper.yetiforce.com    -    it works good

### 📷 Screenshot of configuration

added
![ConfReport](https://github.com/YetiForceCompany/YetiForceCRM/assets/139356687/62f51c30-2f91-4597-a8dc-e9631758e953)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Every time I edit the settings of the Project field in the Project tasks, an error is written to the log:
TypeError: Argument 2 passed to App\Cache::staticHas() must be of the type string, null given, called in /home/yfprod/html/modules/Vtiger/models/Module.php on line 182 and defined in /home/yfprod/html/app/Cache.php:141
Stack trace:
#0 /home/yfprod/html/modules/Vtiger/models/Module.php(182): App\Cache::staticHas('module', NULL)
#1 /home/yfprod/html/modules/Vtiger/models/Record.php(771): Vtiger_Module_Model::getInstance(NULL)
#2 /home/yfprod/html/modules/Project/models/Module.php(108): Vtiger_Record_Model::getInstanceById(0)
#3 /home/yfprod/html/app/BatchMethod.php(101): Project_Module_Model::updateProgress(0)
#4 /home/yfprod/html/modules/Vtiger/crons/BatchMethods.php(26): App\BatchMethod->execute()
#5 /home/yfprod/html/cron.php(100): Vtiger_BatchMethods_Cron->process()
#6 {main}

->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |     6.4.0
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

If the problem is present on the demo of the stable version, I don't think it's necessary to give details about our server and browser.

### ❓ Additional context

It is convenient to use project tasks as part of projects (associated with projects) and by themselves, without connection with projects and milestones. This requires the ability to make the "Related to" and Project milestones fields optional. On the other hand, if the "Related to"  field is not displayed in the quick creation form, and the Project milestones field is optional, it is impossible to create a task from the existing project view form through the plus sign in the Project Tasks widget, if you do not fill in the milestone, the task will be created, but it has there will be no connection with the project - because the Project field is not displayed in it and does not default to the value of the project from which the task is created.

**Comment by rskrzypczak** [comment]
Fixed in YF 7 version
