### ISSUE TITLE
[UI Bug] 'Row Height' preference not considered everywhere / consistently

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1721]
If the 'Row Height' preference is set to 'narrow', all buttons and input fields should be adjusted to the narrow size rather than remaining at 'medum' size (similarly for 'wide' size). This especially the case in the list view, but also in other areas (in create and edit mode, the actual field are correctly sized).

**Comment by bpabiszczak** [comment]
I wouldn't call it an error. It was designed this way by Vtiger, it requires changes in many places in the system and it's very time consuming, I'll initially set it to be achieved in 2.3 milestone.

**Comment by diderich** [comment]
I called it a bug because in earlier version of YetiForce (1.0 and 2.0), there was consistency between all fields. When selecting narrow, all button associated with displaying and editing the record were adjusted.
