### ISSUE TITLE
[bug] Issue while creating new user

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#17267]
I am using crm since last 2 years, suddenly got error while creating new user, when user account is created and saved, system gives below error

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/12723595/2fced6ce-afed-4658-aaac-c047fbd161ed)

my system configuration is as below

![ConfReport (2)](https://github.com/YetiForceCompany/YetiForceCRM/assets/12723595/a96ed4ab-4e24-4da8-98fb-9a07c990efff)

I checked on gitstable and gitdeveloper both are working ok and no error on creating user.

how do I debug the problem.

Jeevan Pendhari

**Comment by JEEVAN28** [comment]
I checked log and it shows error as below

Additional Information:
Array
(
    [0] => HY000
    [1] => 1364
    [2] => Field 'authtoken' doesn't have a default value
)

 - 0 include/main/WebUI.php:191  >>  App\Log->error('SQLSTATE[HY000]: General error: 1364 Field \'authtoken\' doesn\'t have a default value
The SQL being executed was: INSERT INTO `vtiger_users` (`id`, `date_modified`, `reminder_next_time`, `modified_user_id`, `user_name`, `is_admin`, `first_name`, `last_name`, `email1`, `status`, `activity_view`, `hour_format`, `start_hour`, `reports_to_id`, `date_format`, `description`, `time_zone`, `currency_id`, `currency_grouping_pattern`, `currency_decimal_separator`, `currency_grouping_separator`, `currency_symbol_placement`, `imagename`, `internal_mailer`, `theme`, `language`, `reminder_interval`, `phone_crm_extension`, `no_of_currency_decimals`, `truncate_trailing_zeros`, `dayoftheweek`, `othereventduration`, `default_record_view`, `leftpanelhide`, `rowheight`, `defaulteventstatus`, `defaultactivitytype`, `end_hour`, `emailoptout`, `available`, `auto_assign`, `records_limit`, `phone_crm_extension_extra`, `date_password_change`, `force_password_change`, `view_date_format`, `authy_methods`, `authy_secret_totp`, `login_method`, `sync_carddav`, `sync_caldav`, `sync_carddav_default_country`, `default_search_module`, `default_search_override`, `primary_phone_extra`, `primary_phone`, `mail_scanner_actions`, `mail_scanner_fields`, `secondary_email`, `default_search_operator`, `super_user`, `calendar_all_users_by_default`, `user_password`, `date_entered`) VALUES (319, \'2023-08-30 22:39:50\', \'2023-08-30 22:39\', \'1\', \'TestUser\', \'off\', \'Test\', \'User\', \'test@apbnb.com\', \'Active\', \'This Month\', \'24\', \'08:00\', 0, \'yyyy-mm-dd\', \'\', \'Asia/Kolkata\', 5, \'123,456,789\', \'.\', \' \', \'1.0$\', \'\', 0, \'twilight\', \'en-US\', \'15 Minutes\', \'\', \'2\', 0, \'Monday\', \'[{\\"activitytype\\":\\"Sales Call\\",\\"duration\\":\\"60\\"},{\\"activitytype\\":\\"LinkedIn Message\\",\\"duration\\":\\"60\\"},{\\"activitytype\\":\\"Internal\\",\\"duration\\":\\"60\\"},{\\"activitytype\\":\\"Purchases\\",\\"duration\\":\\"60\\"},{\\"activitytype\\":\\"Outstanding\\",\\"duration\\":\\"60\\"}]\', \'Summary\', 0, \'medium\', \'PLL_PLANNED\', \'Meeting\', \'16:00\', 0, 0, 0, 0, \'\', \'2023-08-30 22:39:50\', 0, \'PLL_ELAPSED\', \'\', \'\', \'PLL_PASSWORD\', \'PLL_OWNER\', \'PLL_OWNER\', \'\', \'\', 0, \'\', \'\', NULL, NULL, \'\', \'PLL_CONTAINS\', 0, 0, \'$2y$10$Dv8Ldz27PbX66pR5ujWgqOyZOw723/JGk5WrgbqmQd/gx8IZy6lJ2\', \'2023-08-30 22:39:50\')
PDOException: SQLSTATE[HY000]: General error: 1364 Field \'authtoken\' doesn\'t have a default value in vendor/yetiforce/yii2/db/Command.php:1302
Stack trace:
#0 vendor/yetiforce/yii2/db/Command.php(1302): PDOStatement->execute()
#1 vendor/yetiforce/yii2/db/Command.php(1102): yii\\db\\Command->internalExecute()
#2 modules/Users/models/Record.php(197): yii\\db\\Command->execute()
#3 modules/Users/models/Record.php(175): Users_Record_Model->saveToDb()
#4 modules/Vtiger/actions/Save.php(109): Users_Record_Model->save()
#5 modules/Users/actions/Save.php(71): Vtiger_Save_Action->saveRecord()
#6 include/main/WebUI.php(188): Users_Save_Action->process()
#7 index.php(26): Vtiger_WebUI->process()
#8 {main}


Please assist.

**Comment by mariuszkrzaczkowski** [comment]
There is no "authtoken" field, you probably have some additional changes
