### ISSUE TITLE
[Question] Portal 2

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1726]
Asked before but never a real answer:
Is it already possible to test portal 2 ? I would like to have an idea what is going on before I setup the portal 1.

I have installed the files in a subdir (portal.xxxx.xxx) set the config options:

$config['crmPath'] to the CRM (should that not be called crmURL ) the example shows an URL not a path...

apiKey set to the apiKey from the CRM

Not sure how to deal with the private and publickey files. They are both in the portal and crm.

In the CRM I have set the portal URL

When opening the portal page I get: No input file specified.

**Comment by zebrahosting** [comment]
"No input file specified."
OK this was due to some server issue. Seems critical on different servers/settings.
Finally found a way to get the install screenworking but did not get much further
After entering URL and APIkey I get:

"HANDLER_NOT_FOUND: Install, Action, Install"

**Comment by bpabiszczak** [comment]
be patient ;) Give me time to answer.

**Comment by bpabiszczak** [comment]
Portal 2 is waiting for a new product module to be completed [we'll finish it by Friday]. Additionally I'm thinking whether we should finish WebDAV before the portal. After that we'll finish the customer's portal. Portal 2 should be ready by the end of August, but I can't promise that [it'll be a bootstrap based version or without graphics].
