### ISSUE TITLE
I paid for the module but the payment wasn’t processed in the system

### ISSUE THREAD

**Issue by MichailSkrynnyk** [YetiForceCompany/YetiForceCRM#17288]
Good afternoon. 
Could you please help me to figure out the problem? I deployed your system on my side and purchased the Kanban Board plugin through your marker. But it appears in the system with status “Unpaid”. Help me to solve this issue.
The purchase was made by:
Name: M.skrinnik1
Mail: m.skrinnik@pc-service.ua
Payment date: 08/31/2023

**Comment by paula-w** [comment]
Hi
I emailed you regarding this issue, please check your inbox.
