### ISSUE TITLE
I am getting security configuration issue 

### ISSUE THREAD

**Issue by Aaqib-kk** [YetiForceCompany/YetiForceCRM#17287]
Detected errors in the configuration of parameters related to system security. There may be problems with the system, or the entered data may be damaged or deleted. More information can be found in the article [Web server requirements at yetiforce.com](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirement). Adjust the following parameters:

Security:
  public_html = 'www: Off' (Recommended: 'On')
  session.use_strict_mode = 'www: On | cron: Off' (Recommended: 'On')
  disable_functions = 'www: pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,pcntl_unshare,' (Recommended: 'shell_exec, exec, system, passthru, popen')
  allow_url_include = 'www: On | cron: Off' (Recommended: 'Off')
  
No file write rights:
  app_data/cron.php
  
  How to resolve this issue? i have hosted this in my AWS EC2 linux

**Comment by ghost** [comment]
Point your webserver to the public_html folder and read the following [https://doc.yetiforce.com/introduction/requirements/](https://doc.yetiforce.com/introduction/requirements/)

**Comment by Aaqib-kk** [comment]
thank you. This issue is resolved now. 
How to resolve this issue?
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/55081205/4b140062-3cc7-4170-8092-be585cce58c4)

**Comment by ghost** [comment]
did you read the documentation i linked?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://github.com/YetiForceCompany/YetiForceCRM/assets/10198654/4ee52d30-5de6-4a53-9cce-05d7566b9c3d)

**Comment by VictorTWB** [comment]
Hi, I have the same Issue here. 

Security:
public_html = 'www: Off' (Recommended: 'On')
session.use_strict_mode = 'www: On | cron: Off' (Recommended: 'On')

Not sure how to "Point your webserver to the public_html folder and read the following https://doc.yetiforce.com/introduction/requirements/" 

I am using cpanel, any kind soul here can share more on how to? Thank You!

**Comment by Aaqib-kk** [comment]
> Hi, I have the same Issue here.
> 
> Security: public_html = 'www: Off' (Recommended: 'On') session.use_strict_mode = 'www: On | cron: Off' (Recommended: 'On')
> 
> Not sure how to "Point your webserver to the public_html folder and read the following https://doc.yetiforce.com/introduction/requirements/"
> 
> I am using cpanel, any kind soul here can share more on how to? Thank You!

I am not sure about cpanel. I resolved this issue through my server configuration (Nginx), i point the root directory to public_html and for "session.use_strict_mode" i edited my php.ini file.

**Comment by VictorTWB** [comment]
> > Hi, I have the same Issue here.
> > Security: public_html = 'www: Off' (Recommended: 'On') session.use_strict_mode = 'www: On | cron: Off' (Recommended: 'On')
> > Not sure how to "Point your webserver to the public_html folder and read the following https://doc.yetiforce.com/introduction/requirements/"
> > I am using cpanel, any kind soul here can share more on how to? Thank You!
> 
> I am not sure about cpanel. I resolved this issue through my server configuration (Nginx), i point the root directory to public_html and for "session.use_strict_mode" i edited my php.ini file.

Managed to solve the first part. Can you show the php.ini file? Couldnt change "cron: Off" to On. TIA!

**Comment by stramosk** [comment]
@VictorTWB, how did you solve this issue?
Thank you!
