### ISSUE TITLE
Sign Out fails

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1729]
When trying to sign out, my browser asks me to open a file (rather than signing out). The file contains the following information (where WWW.EXAMPLE.COM is my server name):

 {"success":false,"error":{"code":"Could not open socket for ssl:\/\/WWW.EXAMPLE.COM at port 443","message":"Could not open socket for ssl:\/\/WWW.EXAMPLE.COM at port 443"}}

The logfile contains the following error message:
[06-Aug-2015 16:53:25 Europe/Amsterdam] PHP Warning:  fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /opt/yetiforce-2.1.0/modules/OSSMail/RoundcubeLogin.class.php on line 477
[06-Aug-2015 16:53:25 Europe/Amsterdam] PHP Warning:  fsockopen(): Failed to enable crypto in /opt/yetiforce-2.1.0/modules/OSSMail/RoundcubeLogin.class.php on line 477
[06-Aug-2015 16:53:25 Europe/Amsterdam] PHP Warning:  fsockopen(): unable to connect to ssl://WWW.EXAMPLE.COM:443 (Unknown error) in /opt/yetiforce-2.0.0/modules/OSSMail/RoundcubeLogin.class.php on line 477

The web server is accessible via https://WWW.EXAMPLE.COM
The IMAP and SMTP server are not using SSL and I have the ports in the mail client configuration to 143 (for imap) and 25 (for smtp).

**Comment by mariuszkrzaczkowski** [comment]
Does your CRM address include HTTPS or HTTP?

**Comment by diderich** [comment]
The CRM is accessible through both https and http. The configuration ($site_url) uses the https version, i.e.` $site_url = 'https://WWW.EXAMPLE.COM/crm2/';`, and `$forceSSL = FALSE`.

**Comment by bpabiszczak** [comment]
Is the certificate for “site_url” right or is it your own local certificate? From what I see this error is returned by your server, so you have to figure out the problem with your administrator, why it's returned, that the certificate is incorrect, and only on this basis you we can think about the solution.

**Comment by diderich** [comment]
Yes, it is a self-signed certificate.

What I find strange is that RoundCube tries to validate a certificate when existing the application, even when the OSSMail module is disabled.

**Comment by diderich** [comment]
I have re-installed the CRM through http rather than https. Then everything works fine.

**Comment by bpabiszczak** [comment]
re-install? you can change only site_url.
