### ISSUE TITLE
Add comments to the summary of a newly created module [bug] 

### ISSUE THREAD

**Issue by aleterracciano** [YetiForceCompany/YetiForceCRM#17295]
Italiano lenguage:
Ciao, ho creato un nuovo modulo su yetiforce per la creazione di un'anagrafica veicoli. Voglio inserire una relazione tra commenti e il modulo creato nel sommario ma non ci riesco. Non posso aggiungere commenti all'interno del sommario. 
Perchè?

Di seguito uno screen shot della sezione relazionamenti che non mi permette di scegliere commenti o documenti. 
Vi ricordo che il modulo è nuvo, l'ho creato io da zero.

English lenguage
Hi, I created a new module on yetiforce for creating a vehicle registry. I want to insert a relationship between comments and the created form in the summary but I can't. I cannot add comments within the summary.
Why?

Below is a screen shot of the reports section which does not allow me to choose comments or documents.
I remind you that the module is new, I created it from scratch.

--------------------------------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/53528784/e577e0fc-01e5-4104-821f-1ea23733ce1c)
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/53528784/ee76e1f5-fda9-4449-9566-66d397d4985c)
![ConfReport (10)](https://github.com/YetiForceCompany/YetiForceCRM/assets/53528784/9c5c68df-0734-4bfc-bde6-113beb2c71ec)

# 🐞 bug report

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by vovpff** [comment]
I think this is because comments doesn't have relation with your new module. You can check what comments tab unavailable too.

You can walk trough issues to find sql query to add this missing relation. Sorry I don't renember it by myself

**Comment by vovpff** [comment]
```
INSERT INTO yeti_demo.vtiger_fieldmodulerel (fieldid, module, relmodule, status, sequence) VALUES ('601', 'ModComments', 'MODULE_NAME', NULL, NULL);
```

Replace MODULE_NAME with your name

**Comment by aleterracciano** [comment]
Ciao, grazie per la query, ha funzionato. Ora vedo il relazionamento del modulo commenti. Ho solo un problema adesso, quando cerco di inserire un commento, questo non si salva. Non riesco a salvare i commenti.
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/53528784/2e73db65-2455-4161-b62c-c85dbb204005)

**Comment by aleterracciano** [comment]
Dopo aver cliccato sul pulsante invia, appare un caricamento veloce e poi niente. Nessun commento viene salvato. 
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/53528784/ce231cb0-7819-443b-8a7a-828063758b6f)

**Comment by aleterracciano** [comment]
Buongiorno, ho risolto. Funziona adesso. La prova è stata effettuata su un ambiente di test vecchio. Ora l'ho aggiornato con la versione in produzione del sito, e funziona correttaemnte. 
Grazie mille.
