### ISSUE TITLE
[Issue] Import directory is not writable

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#17306]
I suddenly started getting error while importing CSV file. I checked Issues previously reported and found one such reporting which is very similar to my issue.

"Import directory is not writable"

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/12723595/2b019fa3-68e1-426e-b6a9-6949b23df839)

I check permission on directory and same is 755.

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/12723595/73075965-f6b9-462b-948a-3c771c3daa4a)

I tried to remove this directory and created new also but no luck.

please assist in the matter.

Jeevan Pendhari

**Comment by JEEVAN28** [comment]
I tried to understand directory and found that Yetiforce is not attempting cache/Import directory. Instead same is /tmp/YetiForceTemp82a1aec8/

This i checked and found permission is set with root and has 755 permission level

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/12723595/2cdcb81c-6a20-4ad4-b2c5-7af88fd17973)

Please assist.

Jeevan Pendhari

**Comment by JEEVAN28** [comment]
I changed permission to 777 for above directory and problem solved. Not sure is this correct.

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://github.com/YetiForceCompany/YetiForceCRM/assets/10198654/0bc00278-f0fb-4b2d-9a9c-0ec2ad0b9558)
