### ISSUE TITLE
[BUG] Cron job not running

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1730]
If I run /cron/vigercron.php manually I get a blank page.
I have tracked it a bit with some echo's and it stopped in de include / logging.php

// Performance Optimization: Configure the log folder
if (SysDebug::getBoolean('LOG4PHP_DEBUG', false)) {
	define('LOG4PHP_DIR', 'libraries/log4php.debug');
} else {
	define('LOG4PHP_DIR', 'libraries/log4php');
}
// END

Server uses cgi-fcgi 
Yeti v2.1
PHP 5.5.9

**Comment by diderich** [comment]
I get the following error message in the phpError.log file:
[06-Aug-2015 17:46:26 Europe/Amsterdam] PHP Fatal error:  Class 'SysDebug' not found in /opt/yetiforce-2.1.0/include/logging.php on line 22
