### ISSUE TITLE
[bug] date and day does not match

### ISSUE THREAD

**Issue by kymwkl** [YetiForceCompany/YetiForceCRM#17308]
# 🐞 bug report

### ⁉️ Describe the bug
Start date of meeting is a day after the the meeting ends date.

### 🔥 How to trigger the error

From the contact's calendar widget, I clicked on the + button to create a Meeting.  I set the date as Tuesday Oct 24 2023 10:00 am and ends on Oct 24, 11:30 am.

After I saved the event, the contact's calendar widget showed the meeting to start on Oct 25 2023 at 10:00 am and ends on oct 24 2023 11:30 am.  The start date is later then the end date!

1. Go to 'Contact'
2. Click on ' + on the Calendar'
3. Set a meeting start date and end date
4. Click 'Save'
5. Go back to the same contact.
6. See error in the calendar widget.  The meeting date is one day later but the end date is correct.  But that also means the start date of a meeting is later than the end date!

Thank you.

**Comment by rskrzypczak** [comment]
The issue does not occur in YF version 7
