### ISSUE TITLE
[bug] Mail Integration Panel broken after switching to new domain

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#17302]
# 🐞 bug report

### ⁉️ Describe the bug

After switching domains the mail integration panel no longer works. Outlook displays the message in the image below, after clicking retry a few times I am able to forcefully start the add-in but only the dashboard is displayed, not the account linked to the email.

![Outlook](https://github.com/YetiForceCompany/YetiForceCRM/assets/144004250/c8dfadfd-c875-4e2c-84aa-534836ab462d)

### 🔥 How to trigger the error

1. Switch Domains
2. Download new outlook add-in
3. Upload it to outlook admin panel
6. See error

### 👎 Actual Behavior

MailIntegration Panel does not appear

### 👍 Expected Behavior

MailIntegration Panel should appear

### 👷 Testing

N/A

### 📷 Screenshot of configuration

![ConfReport](https://github.com/YetiForceCompany/YetiForceCRM/assets/144004250/976ed1fe-1421-4e34-8293-a1945c97c1ee)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

====================================================================================================

> 2023-10-12 13:43:38.0021 [info][[yii\db\Connection::open]] - Opening DB connection: mysql:host=localhost;dbname=yetiforce;port=3306
> 2023-10-12 13:43:38.0031 [info][[yii\db\Command::query]] - SELECT EXISTS(SELECT * FROM `vtiger_users` WHERE (`id`=1) AND ((`status`='Active') AND (`deleted`=0)))
> 2023-10-12 13:43:38.0036 [info][[yii\db\Command::query]] - SELECT EXISTS(SELECT * FROM `vtiger_users` WHERE `id`=1)
> 2023-10-12 13:43:38.0181 [info][[yii\db\Command::query]] - SELECT * FROM `vtiger_tab`
> 2023-10-12 13:43:38.019 [info][[yii\db\Command::query]] - SELECT * FROM `vtiger_entityname`
> 2023-10-12 13:43:38.0213 [trace][] - Entering getColumnFields(Notification) method ...
> 2023-10-12 13:43:38.0214 [info][[yii\db\Command::query]] - SELECT * FROM `vtiger_field` LEFT JOIN `s_yf_fields_anonymization` ON vtiger_field.fieldid = s_yf_fields_anonymization.field_id WHERE `tabid`=111
> 2023-10-12 13:43:38.0268 [trace][] - Exiting getColumnFields method ...
> 2023-10-12 13:43:38.0272 [info][[yii\db\Command::query]] - SELECT `vtiger_field`.*, `s_yf_fields_anonymization`.* FROM `vtiger_field` LEFT JOIN `vtiger_blocks` ON vtiger_field.block = vtiger_blocks.blockid LEFT JOIN `s_yf_fields_anonymization` ON vtiger_field.fieldid = s_yf_fields_anonymization.field_id WHERE `vtiger_field`.`tabid`=111 ORDER BY `vtiger_blocks`.`sequence`, `vtiger_field`.`sequence`
> 2023-10-12 13:43:38.0278 [info][[yii\db\Command::query]] - SELECT * FROM `vtiger_blocks` WHERE `blockid`=374 LIMIT 1
> 2023-10-12 13:43:38.0282 [info][[yii\db\Command::query]] - SELECT * FROM `vtiger_blocks` WHERE `blockid`=443 LIMIT 1
> 2023-10-12 13:43:38.0285 [info][[yii\db\Command::query]] - SELECT * FROM `vtiger_blocks` WHERE `blockid`=375 LIMIT 1
> 2023-10-12 13:43:38.029 [info][[yii\db\Command::query]] - SELECT * FROM `vtiger_ws_fieldtype`
> 2023-10-12 13:43:38.0294 [trace][] - Entering isPermitted(Accounts,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(Leads,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(Vendors,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(Partners,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(OSSEmployees,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(Project,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(ProjectMilestone,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(HelpDesk,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(FInvoice,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(SQuotes,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(SSingleOrders,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(ProjectTask,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0295 [trace][] - Entering isPermitted(Contacts,,,) method ...
> 2023-10-12 13:43:38.0295 [trace][] - Exiting isPermitted method ... - SEC_USER_IS_ADMIN
> 2023-10-12 13:43:38.0343 [info][[yii\db\Command::query]] - SELECT `vtiger_crmentity`.`description` AS `description`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `u_yf_notification`.`notificationid` AS `id`, `u_yf_notification`.`title` AS `title`, `u_yf_notification`.`link` AS `link`, `u_yf_notification`.`linkextend` AS `linkextend`, `u_yf_notification`.`process` AS `process`, `u_yf_notification`.`subprocess` AS `subprocess`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `u_yf_notification`.`notification_type` AS `notification_type`, `vtiger_crmentity`.`smcreatorid` AS `smcreatorid`, `u_yf_notification`.`subprocess_sl` AS `subprocess_sl` FROM `u_yf_notification` INNER JOIN `vtiger_crmentity` ON u_yf_notification.notificationid = vtiger_crmentity.crmid WHERE (`vtiger_crmentity`.`deleted`=0) AND ((`smownerid`=1) AND (`u_yf_notification`.`notification_status`='PLL_UNREAD')) AND (`u_yf_notification`.`notification_status`='PLL_UNREAD') LIMIT 200
> 2023-10-12 13:43:37.9945 [info][[application]] -
> $_POST = ['_csrf'=>'=>'Notification','view'=>'Reminders']
> $_COOKIE = ['YTSID'=>'']
> $_SESSION = ['CSP_TOKEN'=>'token','last_activity'=>1697132522.782532,'UserAuthMethod'=>'PASSWORD','app_unique_key'=>'key','user_name'=>'username','full_user_name'='fullname','fingerprint'=>'print','user_agent'=>'Mozilla/5.0 (Windows NT 10.0; rv:102.0) Gecko/20100101 Firefox/102.0','processEvents'=>[],'authenticated_user_id'=>1,'DashBoard'=>['Home'=>['LastDashBoardId'=>1]]]
> _HEADERS = ['Host'=>'domain','User-Agent'=>'Mozilla/5.0 (Windows NT 10.0; rv:102.0) Gecko/20100101 Firefox/102.0','Accept'=>'text/html, */*; q=0.01','Accept-Language'=>'en-US,en;q=0.5','Accept-Encoding'=>'gzip, deflate, br','Content-Type'=>'application/x-www-form-urlencoded; charset=UTF-8','X-Requested-With'=>'XMLHttpRequest','Content-Length'=>'96','Origin'=>'domain','Connection'=>'keep-alive','Cookie'=>'YTSID=','Sec-Fetch-Dest'=>'empty','Sec-Fetch-Mode'=>'cors','Sec-Fetch-Setch-Site'=>'same-origin']
> $stability = ['output_buffering'=>'1']
> $security = ['session.cookie_httponly'=>'Off','session.cookie_secure'=>'Off','session.cookie_samesite'=>'','session.name'=>'PHPSESSID']
> $environment = ['error_log'=>'/var/log/cli_error.log','openssl.cafile'=>'/etc/ssl/certs/ca-certificates.crt','openssl.capath'=>'/etc/ssl/certs/']
> $functionalVerification = ['shop'=>'YetiForceOutlook(32), YetiForceWidgets(32)']
> $headers = ['Header: access-control-allow-methods'=>false,'Header: access-control-allow-origin'=>false,'Header: referrer-policy'=>false,'Header: expect-ct'=>false,'Header: x-frame-options'=>false,'Header: x-xss-protection'=>false,'Header: x-content-type-options'=>false,'Header: x-robots-tag'=>false,'Header: x-permitted-cross-domain-policies'=>false,'Header: strict-transport-security'=>false,'Header: content-security-policy'=>false])
> $pathVerification = ['webservice/WebserviceStandard/'=>false,'robots.txt'=>false]

====================================================================================================

![Console](https://github.com/YetiForceCompany/YetiForceCRM/assets/144004250/393c9944-155a-4950-a060-e1ef19e4d186)

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |    6.4
| Web server (name and version)       |  Apache              |
| PHP                                 |          7.4      |  
| Browser (name and version)          |        Firefox/Chrome (error on both)        |
| Operating System (name and version) |     Linux/Windows (error on both)          |
| Database (name and version)         |      MariaDB 10.11          |
| Service Pack version                |       v6         |

### ❓ Additional context

I have already tried to delete the domains in settings, turn the module off and on in the store, and searched the database for the old domain.

What files / tables in the database do i have to replace to reset the outlook mail integration?

**Comment by mariuszkrzaczkowski** [comment]
https://doc.yetiforce.com/administrator-guides/integration/mail-integration-panel/outlook/#possible-issues

**Comment by just37** [comment]
I've already read that article, my security file matches the one linked. The issue still persists, does the mail integration panel have a special log file or is there any way for me to reset the panel?

**Comment by ghost** [comment]
My file matches the one linked and the issue persists, I think I may reinstall the crm sometime this weekend. Is there anywhere I can send more detailed logs beforehand.
