### ISSUE TITLE
Email not properly formatted when sent from automation workflow

### ISSUE THREAD

**Issue by salvofan** [YetiForceCompany/YetiForceCRM#17304]
Hi,
I've created a workflow to send an email to a particular email (taken from a custom module, email field). The email is sent, the content is also correct (with all parameters correctly processed).

Unfortunately the format is not working. I have tried to copy and paste the text from word (there is an option), I've tried to add directly the "source" and I get an error. (The same source works perfectly with email template).

As I need to send some informative emails, these need to be with a good look and feel, even with colours and on multiple lines.

To test:
create a worklow with manual trigger
open the custom module
trigger the workflow
Wait for the email (I currently have set up my personal email address for tests, so it doesn't even take the actual address from the module).
Look at the received email.

Unfortunately cannot test on gitstable as there are no smtp to send emails.

Kind regards,

**Comment by rskrzypczak** [comment]
probably fixed in YF 7. However, you can always use a workflow action that uses an email template ;)
