### ISSUE TITLE
[bug] Image missing in email body

### ISSUE THREAD

**Issue by mztechsnc** [YetiForceCompany/YetiForceCRM#17315]
Good morning, 
we encountered the following problem: 

when a message containing more than one image in the html text is captured by the mailscanner, the message is imported but only the first image is visible in the text. 
Unfortunately it is not possible to replicate the problem on gistable and gitdeveloper because the mail module is not working.

This is the version we are using: YetiForce CRM 6.4 Service Pack v6

To reproduce the problem:
1) send a message to a mailbox configured on the mailscanner that contains more than one image within the text.

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/112963243/664724a7-be2c-4e37-96c9-43b0241e5c9f)

2) Wait for the mailscanner to capture the message and then open it from the related ticket or from the email history
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/112963243/95f4a89d-5d17-4a93-b3ee-25d3be99acc3)

in the text of the message I only see one of the three images.
The images are actually there but as attachments
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/112963243/26fb4d70-605a-4d75-90ee-c424e8f440f4)

if I go to the mail module (Roundcube) and open the message, I see all three images:

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/112963243/b06f7bbc-a3c4-42c4-8679-16fef5a9106d)

# 🐞 bug report

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
Fixed in YF7
