### ISSUE TITLE
[bug] Send Mail Workflow - Formatting Issue

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#17316]
When creating a workflow task using the 'Send Mail' function. The task saves fine, however, any changes to text formatting do not save. If you try to enter the source code, the system spits out errors. This issue also occurs on gitstable.yetiforce.com.

**Comment by mariuszkrzaczkowski** [comment]
Does the error occur on gitdeveloper?  if not, it has already been fixed

**Comment by s2b-git** [comment]
Marius, lots of user may not be willing to install new version maybe for years (heavy customizations). When bug has been fixed, it should be done on current public version (service pack) and merged with dev too, so users can have feeling of code care.
Also, when bug is knocked, would be perfect to see what and where, so it can be individually managed

**Comment by ghost** [comment]
While I agree with you s2b, I was able to manually add the commit by heading to issues > milestones > YetiForce 6.5 and looking for the [pull request](https://github.com/YetiForceCompany/YetiForceCRM/pull/16722). In my case I opened this issue without checking gitdeveloper, thank you for pointing me in the right direction and apologies.
