### ISSUE TITLE
[bug] Creation of dynamic property HTMLPurifier_Lexer_DOMLex::$_entity_parser is deprecated in 

### ISSUE THREAD

**Issue by deepti4666** [YetiForceCompany/YetiForceCRM#17320]
We are not working on the CRM, but this error keeps repeating itself.

* cache/logs/errors.log

: Creation of dynamic property HTMLPurifier_Lexer_DOMLex::$_entity_parser is deprecated in /vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php, line 154
#0 vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php:38  >>  HTMLPurifier_Lexer->__construct()
#1 vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php:117  >>  HTMLPurifier_Lexer_DOMLex->__construct()
#2 vendor/ezyang/htmlpurifier/library/HTMLPurifier.php:153  >>  HTMLPurifier_Lexer->create()
#3 app/Purifier.php:149  >>  HTMLPurifier->purify('/crm/token.php')
#4 app/Purifier.php:154  >>  App\Purifier->purify('/crm/token.php',false)
#5 app/Purifier.php:543  >>  App\Purifier->purify('/crm/token.php')
#6 app/Request.php:538  >>  App\Purifier->purifyByType('/crm/token.php','Text')
#7 app/Request.php:757  >>  App\Request->getServer('SCRIPT_NAME')
#8 app/RequestUtil.php:131  >>  App\Request->__callStatic('_getServer',[])
#9 app/Controller/Headers.php:89  >>  App\RequestUtil->getBrowserInfo()
#10 app/Controller/Headers.php:81  >>  App\Controller\Headers->__construct()
#11 token.php:15  >>  App\Controller\Headers->getInstance()

-->

: Creation of dynamic property Users_Record_Model::$record_module is deprecated in /modules/Users/models/Record.php, line 436
#0 modules/Users/models/Record.php:417  >>  Users_Record_Model->getInstanceFromUserObject()
#1 app/Controller/View/Base.php:80  >>  Users_Record_Model->getCurrentUserModel()
#2 modules/Calendar/views/Reminders.php:25  >>  App\Controller\View\Base->getViewer()
#3 include/main/WebUI.php:188  >>  Calendar_Reminders_View->process()
#4 index.php:26  >>  Vtiger_WebUI->process()

-->

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.4.0
| Web server (name and version)       |                |
| PHP                                 |  8.1              |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

Cannot access server config - throws an error since the update.

**Comment by rskrzypczak** [comment]
This is a dependent library error.
Please update your YetiForce system which contains an update for this library.
