### ISSUE TITLE
[Bug?] Calendar only showing own items

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1733]
In the calender (month) view, I can only see myself as a user and not others. (only one name in de sidepanel)
In the list view I do see other people items.

Is this a setting or a bug?

v2.1

**Comment by bpabiszczak** [comment]
Unfortunately, you gave too little information about your calendar configuration, whether the error occurs in the gitdeveloper version, and how to recreate this error step by step.

**Comment by florek41** [comment]
I think it's about that when you are in calendar List view you can see all public (of all users) activities but in calendar view shows only yours, so in filters is only your user.

on gitdev:

list:
![calendar_1](https://cloud.githubusercontent.com/assets/4824588/9243087/34610b96-418c-11e5-8acf-aa9c5b27c03b.JPG)

caledar:
![calendar_2](https://cloud.githubusercontent.com/assets/4824588/9243086/345fd172-418c-11e5-8a1c-a51fbeb6d11a.JPG)

**Comment by bpabiszczak** [comment]
We add new option in role: https://gitdeveloper.yetiforce.com/index.php?module=Roles&parent=Settings&view=Edit&record=H10

Whether or not browsing other users' graphical calendars is possible: 
 I can only see myself [default]
 I can only see myself and groups
 I can see the users who result from the record list I can access

**Comment by rskrzypczak** [comment]
It is not an error. Displaying the number of users in the graphical calendar can be configured in the role settings.
![calendar4](https://cloud.githubusercontent.com/assets/10221999/9243961/c472f8b6-4196-11e5-98b3-ab00f5fdf370.jpg)
