### ISSUE TITLE
PHP 5.5

### ISSUE THREAD

**Issue by pmaxx** [YetiForceCompany/YetiForceCRM#1734]
Greetings;
I would like to try YetiForceCRM, but my VPS has PHP 5.5 installed. In the Yeti installation docs here https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html it says Yeti needs: "allow_call_time_pass_reference: on". The PHP docs here http://php.net/manual/en/ini.core.php says this was removed in PHP 5.4. So it seems to me that YetiForce requires php 5.3 to run. When I try to install I get a white screen full of error messages. I tried both 2.0.0 and 2.1.0.
Do I have to downgrade PHP to 5.3 to use YetiForce?
Thanks

**Comment by zebrahosting** [comment]
It runs fine on PHP 5.5

**Comment by mariuszkrzaczkowski** [comment]
I updated the requirements on the website, they should be correct now.
