### ISSUE TITLE
[bug] [PL] - Nie działa opcja "MODUŁY - POWIĄZANIA] 

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#17341]
Po aktualizacji do 6.5 - nie działa opcja moduły- powiązania.
Błąd występuje także na demo.
https://gitstable.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout

**Comment by rskrzypczak** [comment]
Added a fix to "YetiForce CRM 6.5 Service Pack v2"
