### ISSUE TITLE
[bug] Save Button Disabled

### ISSUE THREAD

**Issue by amtone1** [YetiForceCompany/YetiForceCRM#17343]
I am able to add a contact, but when I try to add a new vendor the save button is disabled. Can someone help with this. Please see screenshot. 

![savebuttondisabled](https://github.com/YetiForceCompany/YetiForceCRM/assets/783063/db116ee3-b372-474a-98a3-2a8e4f47b986)

# 🐞 bug report

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
Just revert the module type to Basic.
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/10221999/d43e9af9-74a7-4fc0-998e-f31a0e024ae6)
