### ISSUE TITLE
Email account verification code does not work

### ISSUE THREAD

**Issue by bbmachado** [YetiForceCompany/YetiForceCRM#17352]
When updating the system from version 6.4 to version 6.5 using the .zip file available here, the system asks to verify my email. I click on the send button and it goes to a screen asking for the verification code that was sent to my email, but the email with the code does not arrive. The System has an SMTP account configured and email is correct. What am I doing wrong?

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/26714028/006c2caf-e123-446b-b2ef-7abc60f6c468)

**Comment by paula-w** [comment]
The system uses API, not the SMTP configured in the system.
If your email address is incorrect or has some other restrictions related to receiving messages, the code won't be delivered. Try a different email address.

**Comment by bbmachado** [comment]
@paula-w Hi Paula, I've already tried changing the email, but it still doesn't work. Is there some kind of log or other place I can check to see what it could be? The email account is working correctly.

Looking at the requests in Chrome, I noticed the following request return message.

{"success":true,"result":{"success":true,"message":"","type":"error"}}

**Comment by bbmachado** [comment]
I changed the registration email to my personal gmail and it worked. Thank you for your help @paula-w 

Just waiting for registration approval now
