### ISSUE TITLE
[bug] - Regression - In "Related module" widget, "Selecting fields" only hides values

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#17350]
# 🐞 bug report
If you create a **Related module** widget, the field **Selecting fields** doesn't work: it only hides values, but columns depend on filters set in **Custom views** field

### 🔥 How to trigger the error

![Schermata del 2023-12-07 16-57-41](https://github.com/YetiForceCompany/YetiForceCRM/assets/48508691/935628a3-da1c-401d-b67d-1a5d5e732d98)

### 👎 Actual Behavior

![Schermata del 2023-12-07 16-58-14](https://github.com/YetiForceCompany/YetiForceCRM/assets/48508691/d9e3736b-d37d-4976-99a7-424480bad09d)

### 👍 Expected Behavior

Only columns set in Widget's **Selecting Fields** should be showed
### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
Fixed in YF7.0.2
