### ISSUE TITLE
[BUG] cannot create relationship opportunities - quotes etc.

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1735]
![opportunities_relations](https://cloud.githubusercontent.com/assets/4824588/9129795/624b78ac-3cdc-11e5-82b5-9a2620dea919.gif)

tested on test.yf and gitdeveloper.yf

**Comment by rskrzypczak** [comment]
Saving work properly. Choosing 'Requirement Cards' the 'Opportunity Name' value is overwritten by the valur of opportunity related to requirement cards. However, overwriting this value while creating quote from opportunity was blocked.
![related2](https://cloud.githubusercontent.com/assets/10221999/9160416/d1a5f0d8-3f39-11e5-85c3-aff40ae49b7c.jpg)
