### ISSUE TITLE
[Security] how to encrypt files of documents module

### ISSUE THREAD

**Issue by vslonska** [YetiForceCompany/YetiForceCRM#17362]
Hello,

I would like to enable encryption of files saved by the document module (in particular all the files auto saved from the emails) as I see that they are not encrypted on the server.
I find that very dangerous, so the options are to enable encryption or disable this module.
But I don't find any way to enable encryption...

Do you have information about that.

I also have "no encryption modules" printed in settings, but I don't know how to manage that. I can't add anything.
![Screenshot 2024-01-04 at 22-38-58 Parametrage du mot de passe](https://github.com/YetiForceCompany/YetiForceCRM/assets/24274243/1f1f26a2-0dff-4f26-8c34-497bfd6371ac)

Can you tell me ?

Thanks a lot,
Regards,

**Comment by konadrian** [comment]
This panel is for encryption password fields, not a whole module. 
CRM doesn't have a tool which can encrypted document attachments

**Comment by vslonska** [comment]
Hello,
Thank you for your answer.
Can you tell me how I can disable auto import of attached files in emails to Documents ? I didn't find where I can do that, and as there is no encryption possible of these files, it's not safe enough to do that.
Thanks a lot,
Regards,

**Comment by vslonska** [comment]
Hello,
Could you tell me please how I can disable auto import of attached files in emails to Documents ?
You closed the ticket, but it isn't quite solved...

Thank you very much,
Regards,
