### ISSUE TITLE
[bug] Błędna nazwa dnia tygodnia

### ISSUE THREAD

**Issue by RobertKlonowski** [YetiForceCompany/YetiForceCRM#17365]
Wygląda jakby dni tygodnia były przesunięte o 1 do przodu ... 

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/58693620/98149efa-4f2e-4bbe-8068-ec8ece2a7acf)

w konfiguracji, pierwszy dzień tygodnia mam ustawiony - poniedziałek 

Problem występuje zarówno na mojej wersji, jak i na demo.

**Comment by kjakobczak** [comment]
Problem da się rozwiązać odwracając zmianę która była prowadzona w kodzie jakiś czas temu.
https://github.com/YetiForceCompany/YetiForceCRM/commit/02e2cdfda918e124602d489166e7824fc5e236d2
Zmiana arg.date.getUTCDay() na arg.date.getDay() rozwiązuje problem.

**Comment by rskrzypczak** [comment]
Fixed in 7.0.x
