### ISSUE TITLE
[bug] System registration AGAIN

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#17363]
My system has been proprly registered and was working like a month without problem
Suddenly I have again issue without touching any registration data:

This functionality is available after registration.
The system has not been registered. Please register your YetiForce CRM to have access to this part of the system.

It effectively stopped me from crucial (time related)  to business operations.

**Comment by s2b-git** [comment]
Moreover in Company Details part it says that app IS REGISTERED:

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/84110093/5c2bd78d-8de3-4c40-9950-93721781aaa0)

**Comment by rskrzypczak** [comment]
where do you see this message?
only in one or many panels?

You haven't modified any files yourself?
I don't see any possibility of seeing in one place that the system is registered and in another place that it is not.

**Comment by s2b-git** [comment]
when trying to install extension from zip file. hooked it in code, but it seems that there might be some registration server issues

**Comment by vslonska** [comment]
Same type of problem. This registration obligation is really annoying and a bit contrary to the idea of open source software.

**Comment by Elton83** [comment]
Não consigo registrar a empresa!!!!

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/48302996/9106a545-ebae-4ce2-b8bc-0df4ec24fb36)

**Comment by paula-w** [comment]
@Elton83 
Your registration was declined because in the Entity Unique ID you provided a date instead of a tax number. Please read the [registration manual](https://doc.yetiforce.com/administrator-guides/company/company-details/#entitys-unique-identifier) that explains what to enter in each field.

**Comment by Elton83** [comment]
ok, entendi, no Brasil é diferente, mais já pedi a revalidação!!!

**Comment by paula-w** [comment]
Your corrected registration was accepted.

**Comment by noelhunter** [comment]
There is a more fundamental problem underlying this-- what seems to be happening is that added registration fields are invalidating the registration, and then the 14 day time period if being applied immediately, based on the original date.  If a re-registration is required, the 14 day timer should be reset, to prevent upgraded systems from becoming inoperable.
