### ISSUE TITLE
[bug] An error occurred while communicating with the CRM

### ISSUE THREAD

**Issue by djdiaguuu123** [YetiForceCompany/YetiForceCRM#17377]
# 🐞 bug report

### ⁉️ Describe the bug
When I try to connect client portal I get "An error occurred while communicating with the CRM"

### 🔥 How to trigger the error
Try to install Portal

### 👍 Expected Behavior
Work

### 👷 Testing

- [X ] I confirm that I tested it at https://gitstable.yetiforce.com
- [X ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Clear

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by FranziskaSom** [comment]
Wir haben das gleiche Thema mit webpremium

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForcePortal2?tab=readme-ov-file#-installation
