### ISSUE TITLE
Edit/Delete block

### ISSUE THREAD

**Issue by Elton83** [YetiForceCompany/YetiForceCRM#17376]
Consigo editar/ Excluir os blocos

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/48302996/3bbbc880-d2a7-42ba-8874-dda85d54efda)

**Comment by rskrzypczak** [comment]
You can only remove blocks if they do not contain fields.

Currently, editing block labels is only possible via the language editing panel
![image](https://github.com/user-attachments/assets/6e78ae23-8d12-4a53-b018-24ce092245e6)
