### ISSUE TITLE
[bug] Accounts records don't show related Contacts (and vice versa) on the Summary tab when viewing a record.

### ISSUE THREAD

**Issue by JbayCorum** [YetiForceCompany/YetiForceCRM#17375]
Like mentioned in the title, on the summary tab for accounts, I can't see any of the related contacts in the dropdown widget. Clicking the plus button creates a contact record related to the account but it doesn't display in the dropdown. I've tried similar things with the opportunities dropdown and I'm not getting the same issue. Notably the same thing happens for any accounts dropdown on the contacts page.

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/128181041/286a67bc-fe6b-4a91-8d12-08cd7284dc3b)

I was wondering if anybody had found a fix for this.

**Comment by rskrzypczak** [comment]
The error is not currently occurring. However, I suspect that your custom workflow actions may be the cause.
