### ISSUE TITLE
[bug] Calendar - first day of the week not consistent between views

### ISSUE THREAD

**Issue by vslonska** [YetiForceCompany/YetiForceCRM#17373]
Hello,

I set the first day of the week on monday in users settings.
In calendar, I have weeks starting on monday in the month view :
![Screenshot 2024-02-01 at 16-09-05 Calendrier](https://github.com/YetiForceCompany/YetiForceCRM/assets/24274243/7bc97c2b-b141-4d91-a8f1-c42a60fb1cdf)

But weeks start on sundays in the week view... : 
![Screenshot 2024-02-01 at 16-09-25 Calendrier](https://github.com/YetiForceCompany/YetiForceCRM/assets/24274243/a264a5ae-df59-43c0-8eb2-20b0966a2ada)

So I doesn't understand : how can I set the starting day also for the week view ?

Thank you very much,
Regards,

**Comment by rskrzypczak** [comment]
Fixed in YF v7
