### ISSUE TITLE
Workflow emails templates are always stripped out of format [bug] 

### ISSUE THREAD

**Issue by OkayashiM** [YetiForceCompany/YetiForceCRM#17387]
When creating email task in workflows, it loosing applied format converting email to pure text. I don't see way to fix it. As email template dialog consists of formatting options I believe this might be a design bug.
If there is a way to fix it please share otherwise deem it as a bug

**Comment by salvofan** [comment]
This is happening to me on version 6.4. Only workaround is to use email template and send an email template instead of preparing the email using the dialog available in workflow (send email template instead of send email).

**Comment by rskrzypczak** [comment]
This should be fixed in YF7.0.2. If you have any feedback, please create a ticket [here](https://github.com/YetiForceCompany/YetiForce/issues).
