### ISSUE TITLE
[bug] After upgrade to 6.5 system crapped.

### ISSUE THREAD

**Issue by slxcom** [YetiForceCompany/YetiForceCRM#17388]
# 🐞 bug report

After upgrading to version 6.5, I cannot log in to the system.
The website loads with a valid header but an empty body.

macOS Safari, chrome, winxx edge, chrome same issue.

**Comment by salvofan** [comment]
same issue for me. Rolled back to backup. Left 6.5 there...planning to skip upgrade and move straight to 7.0. (Current version is 6.4.0, service pack v6)

**Comment by mariuszkrzaczkowski** [comment]
1. check the logs 
3. is there an error message on the login page?

**Comment by salvofan** [comment]
Absolutely nothing on the login page...no errors.
What files would you suggest to look first for logs?

**Comment by mariuszkrzaczkowski** [comment]
> Absolutely nothing on the login page...no errors. What files would you suggest to look first for logs?

https://doc.yetiforce.com/developer-guides/debug#summary
