### ISSUE TITLE
[bug] Project Task -> Total Working Time. Not working?

### ISSUE THREAD

**Issue by KyobaMuratsu** [YetiForceCompany/YetiForceCRM#17391]
# 🐞 bug report

### ⁉️ Describe the bug

 I've been using the YetiForce CRM for a short time to record work time for employees at my company. I'm facing a problem where the total work time is not being registered. I'm not sure if there is a function for this or if I'm doing something wrong. 

### 🔥 How to trigger the error

Create a project task in YetiForce.
Go to the Time Control module.
Select the project task from the Task dropdown list.
Enter the start and end times for the work session.
Select the Working Time activity type.
Click Save 

### 👎 Actual Behavior

Not showing the sum of working time

### 👍 Expected Behavior

 Show the sum of working time 

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                        6.5.0   |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
The time control record must be in `Accepted` status
