### ISSUE TITLE
[bug]  $purifierAllowedDomains not working 

### ISSUE THREAD

**Issue by OkayashiM** [YetiForceCompany/YetiForceCRM#17395]
Setting in 6.4  $purifierAllowedDomains = false; doesnt change anything in email templates sent from workflows.
Emails are shaved from all customization. 
Considering it as a bug, as existing functionality is not working, unless here is something I missing?

Best

**Comment by s2b-git** [comment]
same here. Tried false, domain... by the way mentioned few times here and there. So far no help provided :-(

**Comment by rskrzypczak** [comment]
This should be fixed in YF7.0.2. If you have any feedback, please create a ticket [here](https://github.com/YetiForceCompany/YetiForce/issues).
