### ISSUE TITLE
Zloti sign in Organization screen

### ISSUE THREAD

**Issue by maikst** [YetiForceCompany/YetiForceCRM#174]
Look at the attachment.
Maybe it is in some more places.
Seems to be hardcoded?

Would be great to take the currency sign from the actual currency.
Thx

![bildschirmfoto vom 2015-02-01 18 15 51](https://cloud.githubusercontent.com/assets/9348629/5992965/0103bc50-aa40-11e4-9224-4ece13822d00.png)

**Comment by maikst** [comment]
It seems that you find the Zloti sign only shortly after installation.
It will change during usage to the configured currency....
Strange.

**Comment by MaciejStencel** [comment]
After installation Polish currency was cached and stored in users prvileges. Added recalculation of priviledges for all users at the end of systems installation.
