### ISSUE TITLE
[bug]   modules - relations just displays error

### ISSUE THREAD

**Issue by WMCyn** [YetiForceCompany/YetiForceCRM#17406]
when in back end configuration

open panel for "standard modules"
clicking on the "Modules - Relations"

just give a page saying error, inform administrator

Nothing shows in logs indicating any issues.

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/43242043/ec1298a4-9a36-4f33-9557-d6410db9012f)

**Comment by davide-alghi** [comment]
@WMCyn install YetiForce CRM 6.5 Service Pack v2
it fixes the problem

**Comment by WMCyn** [comment]
thank you that fixed it
