### ISSUE TITLE
[Enhancement] Allow customized icons for new activity types

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1740]
Currently if a new activity type is added for calendar events, for example 'Workshop', the calendar dashboard displays it using the call icon (coded in `layouts/vlayout/modules/Vtiger/dashboards/CalendarActivitiesContents.tpl` and `layours/vlayout/modules/Vtiger/RelatedActivities.tpl`)

It would be great if the application would check in the `custom/.../skin/images` directory if an icon (for example `Workshop.png`) associated with the new activity exists and use that icon rather than the default one.

This could be done by adding a function `vimage_path_default(image_name, defailt_image_name)` replacing the call to `vimage_path` in the mentioned files that would
1. search for `image_name` and different image extensions (i.e. .png, .gif, .jpg) in the custom location 
2. if not found, search for `image_name` in the default location
3. if still not found, search for `default_image_name` in the default location

    {if $ACTIVITY->get('activitytype') == 'Task'}
    	<image style="margin-left: 4px;" src="{vimage_path('Tasks.png')}" alt="{vtranslate('LBL_TASK')}" width="24px"/>&nbsp;&nbsp;
    {elseif $ACTIVITY->get('activitytype') == 'Meeting'}
    	<image style="margin-left: 4px;" src="{vimage_path('Meeting.png')}" alt="{vtranslate('LBL_METTING')}" width="24px" />&nbsp;&nbsp;
    {else}
    	<image style="margin-left: 4px;" src="{vimage_path('Call.png')}" alt="{vtranslate('LBL_CALL')}" width="24px" />&nbsp;&nbsp;
    {/if}

could probably then be replaced by someting like

    <image style="margin-left: 4px;" src="{vimage_path_default( $ACTIVITY->get('activitytype'),'Call')}" alt="{vtranslate( $ACTIVITY->get('activitytype'))}" width="24px"/>&nbsp;&nbsp;

I believe this would simplify the code and make it more generic.

**Comment by diderich** [comment]
With what additional information can I help?

**Comment by bpabiszczak** [comment]
It's a good idea, we can do it in 2.3 or 2.4 version, now we don't plan to introduce such modifications.

**Comment by diderich** [comment]
That would be great. Currently I have changed the source code and hard-coded the activity types that are relevant for me (fyi, I have bought the associated icons from https://www.iconfinder.com/). 

For whoever is interested, I use the following activity types (consulting business):
----
Call
Meeting
Landline Call
Mobile Call
Skype Call
Formal Meeting
Informal Meeting
Working Meeting
Seminar/Training
Workshop
Lunch/Dinner
Coffee
Travel
Other
