### ISSUE TITLE
[bug] adding "Select from field" in lineitems crashes

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#17409]
# 🐞 bug report

### ⁉️ Describe the bug

if you try to add the lineitem's field "Select from field", YF crashes

### 🔥 How to trigger the error

![Schermata del 2024-04-01 18-59-07](https://github.com/YetiForceCompany/YetiForceCRM/assets/48508691/d49b4b30-4223-4dbd-9cd1-7876e04e6053)

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### Fix
in line

https://github.com/YetiForceCompany/YetiForceCRM/blob/4b5e4244b8338c837a8132ff12686f29f222d89b/layouts/basic/modules/Settings/LayoutEditor/inventoryTypes/PicklistField.tpl#L19

replace 

`<option value="{$VALUE}" {if $PARAMS[$MODULE] == $VALUE} selected {/if}>{$NAME}</option>`

with

`<option value="{$VALUE}" {if $PARAMS && $PARAMS[$MODULE] == $VALUE} selected {/if}>{$NAME}</option>`

**Comment by rskrzypczak** [comment]
Fixed in YF7, thanks ;)

**Comment by davide-alghi** [comment]
Great, tnx ;)
