### ISSUE TITLE
[BUG] merging duplicates not working

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1741]
FInd (contact) duplicates, select the ones to merge, the window opens properly but when the final merge button is clicked, nothing happens.
v2.1

**Comment by konadrian** [comment]
You can check on https://gitdeveloper.yetiforce.com is everything work fine now.

**Comment by zebrahosting** [comment]
Well took your new code on my own site and all works fine. Thanks for the quick fix !
