### ISSUE TITLE
Work Flow Email Task not triggering

### ISSUE THREAD

**Issue by ojundi** [YetiForceCompany/YetiForceCRM#1742]
Outgoing server configuration tested, received test email.
Other tasks are triggering when added to the same work flow such as field updates.

Symptoms

Work flow on custom module that has an email task does not send an email, however other tasks are executed

**Comment by bpabiszczak** [comment]
Please read this:
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by ojundi** [comment]
were you able to confirm it ?
