### ISSUE TITLE
[bug] Error when trying to configure OSSMailScanner in 7.0.0

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#17428]
# 🐞 bug report

### ⁉️ Describe the bug

I successfully installed the latest version 7.0.0. Everything works fine, except when I try to configure the mail scanner. I get the following error message:

![error](https://github.com/YetiForceCompany/YetiForceCRM/assets/10230144/cea2da7d-5bc8-4438-bd5d-8e5a06a691c6)

### 🔥 How to trigger the error

Click in the settings on `Logs` / `Mail - Download History`.

### 👎 Actual Behavior

See error message above.

### 👍 Expected Behavior

Mail scanner works as in the previous version

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

These sites are not yet on 7.0.0, so I am unable to check.

### 📷 Screenshot of configuration

![ConfReport](https://github.com/YetiForceCompany/YetiForceCRM/assets/10230144/7ee7c7b7-27bf-44e0-922b-5bfba084c3b4)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

There are not messages in any error log file

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 7.0.0.
| Web server (name and version)       |   apache 2.4.51             |
| PHP                                 |   8.1.28             |
| Browser (name and version)          | firefox                |
| Operating System (name and version) |    openSUSE Linux 15.5            |
| Database (name and version)         |  mariadb 11.2.3              |
| Service Pack version                |   None             |

### ❓ Additional context

None

### ❗️ Inform the community if you solve the problem

 Currently none.

**Comment by diderich** [comment]
This is an update without errors from 6.5.0

**Comment by rskrzypczak** [comment]
Thanks @diderich, fixed in version 7.0.1
