### ISSUE TITLE
Cron not working again

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#1743]
Parse error: syntax error, unexpected '[' in debug.php and another files

**Comment by bpabiszczak** [comment]
Here it works well: https://gitdeveloper.yetiforce.com/index.php?module=CronTasks&parent=Settings&view=List&block=4&fieldid=26

https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by konadrian** [comment]
It might be by the wrong php version. In new php version arrays initialize by []. old version array()

**Comment by rskrzypczak** [comment]
Yetiforce system requires at least PHP 5.4 [recommended is 5.6].
https://yetiforce.com/en/administrator-documentation/panel/server-configuration/139-server-configuration.html

**Comment by negodiy** [comment]
I have the same problem. I have php 5.5
