### ISSUE TITLE
[bug] Error on PDF generation PHP8 & above

### ISSUE THREAD

**Issue by BKLTMS** [YetiForceCompany/YetiForceCRM#17430]
# 🐞 bug report

### ⁉️ Describe the bug

Version 6.5:  All works fine when generating a PDF with PHP7.4. However, when PHP is upgraded to PHP8 or above, PDF generation delivers the screenshot below.  Reverting back to PHP7.4 resolves this and generation works again.

![Screenshot 2024-04-18 115832](https://github.com/YetiForceCompany/YetiForceCRM/assets/137448162/4a34b581-4cd2-436b-8890-67d58c08dddb)

Logs not indicating anything on this error.

Any assistance is appreciated - thank you,

--------------------------------------------

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |           CentOS & Apache     |
| Database (name and version)         |     MariaDB 10.6           |
| Service Pack version                |                |

**Comment by davide-alghi** [comment]
@BKLTMS 
what is the engine? the built-in one (YetiForce engine) or Google Chrome engine?

**Comment by BKLTMS** [comment]
Yetiforce engine

**Comment by davide-alghi** [comment]
@BKLTMS 
YetiForce PDF engine is not a champion in memory management: if the PDF template has a lot of content it could crash.
Try generating a PDF, via YetiForce engine, with a very small PDF template: with only a small text in the "Content" field to see if the PDF is generated.

**Comment by BKLTMS** [comment]
Thank you for your response and assistance.
I did as suggested and the smaller template did generate under PHP 8.0.30.
We need to use the templates as they are; is there a solution to make the Yetiforce PDF engine more memory friendly with PHP 8 and above?
As indicated above, all our templates work and generate fine with PHP 7.4.33.

Much appreciated!

**Comment by Ilamparithi-Tamizhanangu** [comment]
Hi,

Please check the memory limit in the php.ini file.

When i changed the php version, it switched to default memory limit as 128MB and created the error in PDF generation. 
After  increasing the memory limit to 1GB, it was solved.  Please check the server configuration for php8, it may solve the error.

Thanks.

**Comment by BKLTMS** [comment]
Thanks for the suggestion.  Changed memory limit to 1GB.  Unfortunately getting the same error.
Any other advice or suggestions to troubleshoot?
Thanks and appreciated!

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi,

when my quotation having too many products or long descriptions, sometimes faced this error. 

Try to generate it the pdf with 1 or 2 products. if PDF generation is successful, increase the memory limit and / or maximum execution time. This worked for me. 

Please try this and share the results.

**Comment by davide-alghi** [comment]
@BKLTMS 
you have two ways: split the PDF template in smaller templates, or buy a Google Chrome PDF engine extension

**Comment by BKLTMS** [comment]
Thanks for the assistance and suggestions!

**Comment by BKLTMS** [comment]
As a follow-up after closing:  Found issue to be with the line-height code in the source.  They were using % for the value, once changed to a number value (i.e.- 1.5 or .9), all templates generated as expected with PHP 8.0.30.

**Comment by Ilamparithi-Tamizhanangu** [comment]
its nice to hear that issue was fixed.

Cloud you please share the column width and height adjustment section? 

and have you tried to change the fonts? if you succeed, could you please share the procedure for changing the fonts?

**Comment by BKLTMS** [comment]
Here is the section you were asking for:
<p style="font-family:Calibri,sans-serif; font-size:8px; line-height:0.9; margin-top:0em">

Hope this is of assistance.

**Comment by BKLTMS** [comment]
Reposting as an image as it is not being allowed to show as text in the previous comment:
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/137448162/45f737b9-a6eb-4ffc-86f3-6d95d9f43498)

**Comment by Ilamparithi-Tamizhanangu** [comment]
Hi,

Yes i required this syntax only and also could you please share the folder path to add the custom fonts? 

Thanks

**Comment by BKLTMS** [comment]
https://github.com/YetiForceCompany/YetiForcePDF#custom-fonts

**Comment by deepti4666** [comment]
my pdf export worked before the upgrade to Yetiforce 7.0 - now it doesn't want to accept the logo.

**Comment by Ilamparithi-Tamizhanangu** [comment]
> https://github.com/YetiForceCompany/YetiForcePDF#custom-fonts

hi,

Thanks for your inputs and now i can generate the quotes with custom fonts. But the PDF output doesnt display the indian currency symbol. 

![image](https://github.com/user-attachments/assets/396c481f-4341-4325-9a9e-0f9aed997536)

Now, i am generating the product table using below syntax. 
$(inventory : type=table columns=seq,comment1,qty,unit,total,tax , href=no , labels=SNo,Product Description,Qty,Unit,Product Price, Tax , width=10px,225px,50px,45px,105px,95px )$

sometimes the alignment is not working as expected. is there any alternative method available to generate the product table? 

Thanks & regards,
Rajasekaran.
