### ISSUE TITLE
[bug] Unable to update from 6.5 v1 to 7v1

### ISSUE THREAD

**Issue by Ilamparithi-Tamizhanangu** [YetiForceCompany/YetiForceCRM#17437]
Hi,

Currently running Yetiforce 6.5 v1 and it shown the update for the version 7.

![update available](https://github.com/YetiForceCompany/YetiForceCRM/assets/96602176/697698a0-45df-4ea0-b15e-8c41149fb240)

When i click the install package, always it shows the error page.

![update error](https://github.com/YetiForceCompany/YetiForceCRM/assets/96602176/29c5d9e4-1528-4c27-8c67-b692862ccec6)

Yetiforce Version: 6.5 v1
php version: 8.1.26
Database version: mysql 8.3
OS: Wamp server : 3.3.3

If i install the yetiforce 7 separately everything is working fine. 

Cloud you please share the procedure to update it without losing the data. 

Thanks & regards,
Rajasekaran.

**Comment by rskrzypczak** [comment]
I can't help here without logs.
share log data: `cache/logs/updateLogsTrace.log`, `cache/logs/Importer.log`, `cache/logs/system.log`

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi, 

please find the attached log files.

[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/15136257/system.log)

[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/15136260/updateLogsTrace.log)


[Importer.log](https://github.com/YetiForceCompany/YetiForceCRM/files/15136259/Importer.log)

Thanks.

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi,

I tried to setup the new test environment for testing the upgradation process. 

Installed 6.5 and tried to update to ver 7. This environment doesnt have any data or any customization. But still the upgradation was failed. 

please find the log files for the same. 

[webserviceErrors.log](https://github.com/YetiForceCompany/YetiForceCRM/files/15142773/webserviceErrors.log)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/15142774/system.log)
[update.log](https://github.com/YetiForceCompany/YetiForceCRM/files/15142775/update.log)
[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/15142776/updateLogsTrace.log)

kindly guide me to fix this upgrdation error. 

Thanks & Regards,
Rajasekaran.

**Comment by Andrew-W-Robinson** [comment]
I have the same issue on my test version.

**Comment by Ilamparithi-Tamizhanangu** [comment]
> I have the same issue on my test version.

Hi,

I updated using this link manually and it was updated from 6.5 to 7 successfully.
https://api.yetiforce.eu/download/crm/UpdatePackages/6.5.0_to_7.0.1_v1

Please try the same.

**Comment by Andrew-W-Robinson** [comment]
I tried the update using the link as you suggested, but after uploading the zip file it took me straight back to the Home page with no option to start the update, did I miss a step?
Thanks for the help though.

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi, 

After uploading the package, it will display the page silimar to shown below.

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/96602176/700bf814-f412-411b-afde-42a682ae2c5d)

After confirmation, it will update the package. I faced an issue with digit grouping. Pl try to change the digit grouping to none (123456789) and try it.

**Comment by Andrew-W-Robinson** [comment]
Hi, it has not worked for me, same issue persists.

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi, have you tried to do the same with separate installation of 6.5 version. (try to update it without doing any modification or importing the data).

**Comment by Andrew-W-Robinson** [comment]
Hi, I have uploaded a brand new copy of the 6.5 version and updated it to 7 v1 without issue.
