### ISSUE TITLE
[bug] Yetiforce 7 demo environment - Unable to create Good Received Note - error

### ISSUE THREAD

**Issue by Ilamparithi-Tamizhanangu** [YetiForceCompany/YetiForceCRM#17440]
hi,

While creating the Goods received note, facing following error in the local installation & yetiforce test environment available in this link ( https://demo.yetiforce.com/).

The error message shown in the demo environment is given below. 
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/96602176/c684798f-2580-492e-81c7-0ea7ccca0f3e)

kindly guide to fix this issue.

Thanks & regards,
Rajasekaran.

**Comment by rskrzypczak** [comment]
Fixed in version 7.0.1

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi,

When I try to update to 7.0.1, i am getting the error same error (which i faced while upgrading from 6.5 to 7).

https://github.com/YetiForceCompany/YetiForceCRM/issues/17437

**Comment by Ilamparithi-Tamizhanangu** [comment]
Hi,

Thanks for the update. 

Now i can able to set the digit grouping as 12,34,56,789. But when i add any product, by default the unit price and buying prices are added without digit grouping. So if i save them, again it shows the same error.

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/96602176/aad9a8a0-8464-4182-922f-a6c350b60db5)

in the 2nd product, i manually added the Comma (,) for digit grouping and save it. it was saved successfully. 

If i didnt add the comma, again it show the same error.  I am getting the same error in the demo version (created the new product with 5 digit unit price and added to the quote. It produce the same error.)

NOTE: This update 7.0.1, helped me to manually update from 6.5 v2 to 7.0.1 successfully. 

Kindly share the solution for the same.

Thanks & Regards,
Rajasekaran.

**Comment by joice-martins** [comment]
Having the same problem here

**Comment by rskrzypczak** [comment]
Fixed inYF7.0.2
