### ISSUE TITLE
[bug] After chaning the digit grouping, unable to edit the quotes (YF V7)

### ISSUE THREAD

**Issue by Ilamparithi-Tamizhanangu** [YetiForceCompany/YetiForceCRM#17446]
Hi,

The default settings for the user preference is 123456789 (without any grouping). 

if digit grouping is changed (123456789 to 12,34,56,789), it creates an error while editing or create the new quotes. (quotes + goods received note).

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/96602176/95ec50d6-d6e3-476c-a1af-18b132d54dfe)

Tested the demo YF7 demo environment and facing the same error.  YF 6.5 is working fine with changing the digit grouping. 

Kindly share the procedure to fix the same. 

Thanks & Regards,
Rajasekaran.

**Comment by deepti4666** [comment]
> Hi,
> 
> The default settings for the user preference is 123456789 (without any grouping).
> 
> if digit grouping is changed (123456789 to 12,34,56,789), it creates an error while editing or create the new quotes. (quotes + goods received note).

@RajasekaranJeni 

Where do I check this?

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi,

link: https://demo.yetiforce.com/index.php?module=Users&view=PreferenceDetail&record=5

User Preference > Digit Grouping pattern.

**Comment by deepti4666** [comment]
> hi,
> 
> link: https://demo.yetiforce.com/index.php?module=Users&view=PreferenceDetail&record=5
> 
> User Preference > Digit Grouping pattern.

Thank you.

This solved one of my issues of showing the zero's on the invoice/quote.

**Comment by rskrzypczak** [comment]
Fixed in YF7.0.2

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi,

Still this digit grouping issue in quotes is present and tested the same in 7.0.2 demo site (demo.yetiforce.com). Please check the below screenshots.

![image](https://github.com/user-attachments/assets/0447db13-ea6a-4311-afb4-94dbc1765bbc)

The digit grouping is set to 1,23,45,678 format and digit grouping seperator as "space".

The third product was already saved in the quotation and while editing, it displays the digit grouping properly. 

Now i added the new product in the quotation. (6th product -> named test product). while adding the new product, the price was added without digit grouping (115151 - instead of 1 15 151).  if i save the quotation, it displays the eror.

![image](https://github.com/user-attachments/assets/d08ee602-69e6-4741-a053-66ebc01e8345)

if i manually edit the 6th product price and add the appropreaiate spaces for digit grouping, it save the quote without any issues. 

While adding the product, the prices are not automatically updated for digit grouping or while saving its not saving the numbers automatically. it shows the error for mismatch in the digit grouping.

Please provide the solution for the same.

Thanks & regards,
Rajasekaran.
