### ISSUE TITLE
[PL][bug] Błąd powiązania w raportach - Rezerwacje -> Pozycja zamówienia

### ISSUE THREAD

**Issue by zielonekrzeslo** [YetiForceCompany/YetiForceCRM#17450]
Test wykonany na wersji developerskiej na której takze pojawia się błąd.
Błąd prawdopodobnie z powodu braku powiązania relacji pomiędzy Rezerwacjami, a pozycjami zamówień (także pozycjami ofert).

Kroki do otrzymania błędu:
Stwórz raport -> Podstawowe źródło danych (**Rezerwacje**) -> Wybierz referencje i relacje (**Zamówienia**) -> Dodaj kolumnę -> Zamówienia Blok zaawansowany (**[Zamówienia] Nazwa pozycji**) -> Zapisz

Po zapisaniu pojawia się błąd:
![obraz](https://github.com/YetiForceCompany/YetiForceCRM/assets/166414275/deba029e-e236-442f-a92b-0fa22c31f83f)

**Comment by rskrzypczak** [comment]
Fixed in version 7.0.1.
// Brak możliwości filtrowania po blokach zaawansowanych modułów relacyjnych
