### ISSUE TITLE
[Bug] Cron don't work. 

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1745]
I install stable 2.1,the Cron don't work,like the following:
I excute the vtigercron.sh directly but it do not work.
![qq 20150810085414](https://cloud.githubusercontent.com/assets/12697896/9157785/19e8563a-3f3d-11e5-8117-873556e47480.jpg)
I install vtiger crm at the same server,it work well.and YetiForceCRM v2.0.683 work well.

**Comment by bpabiszczak** [comment]
From what I can see in the screenshot CRON is working properly, what is wrong with it according to you?
In the gitdeveloper version cron is working properly, so you have to diagnose the problem with your administrator. I recommend reading this:  https://yetiforce.com/en/administrator-documentation/panel/cron/150-enable-cron.html

One comment – remember that the sh file should have the right formatting [UTF8, UNIX]
