### ISSUE TITLE
[bug] cant change comments or editing

### ISSUE THREAD

**Issue by FranziskaSom** [YetiForceCompany/YetiForceCRM#17452]
I or colleagues create a comment in the organization/contacts etc. 

Send button works. Creating new comments and clicking the send button works.
---
Changes in the comments are not possible because the send button does not perform any action. 
---
Replying to comments is not possible because the send button does not work.
---
Would be great if that worked.

See picture. See Config.

![ConfReport](https://github.com/YetiForceCompany/YetiForceCRM/assets/75488133/05ec3cc9-adbe-49fe-aa0e-f460e618fa8b)

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/75488133/85a58be4-a6f6-4096-8d51-e2f1b47d3e60)

**Comment by rskrzypczak** [comment]
Fixed in version 7.0.1

**Comment by FranziskaSom** [comment]
Many, many thanks for this and for your work. We are new to you, are delighted and have already booked the first modules.
