### ISSUE TITLE
[bug] Call to a member function validateAndSecure() on false

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#17463]
# 🐞 bug report

### ⁉️ Describe the bug

When running the mail scanner (interactively or via cron) and there is an issue with the attachments, the function `validateAndSecure()` may be called when the object does not exist, i.e. when the creating function in `app/Fields/File.php` `static::loadFromFile`or `static::loadFromUrl` returns `false` or `null`.

To correct this, ensure that `validateAndSecure()` is only called on a proper object, for example by replacing

```
if($fileInstance->validateAndSecure()) {
```
with 
```
if($fileInstance !== false && $fileInstance !== null && $fileInstance->validateAndSecure())
```
### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |  7.0.1
| PHP                                 | 8.3.7                |

**Comment by rskrzypczak** [comment]
Thenks! Fixed in YF7.0.2
