### ISSUE TITLE
[warning] Creation of dynamic property App\Fields\File::$validateAllowedFormat is deprecated in /opt/crm7/app/Fields/File.php, line 253

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#17462]
# 🐞 bug report

### ⁉️ Describe the bug

When using php 8.3 the following warning is shown

`Creation of dynamic property App\Fields\File::$validateAllowedFormat is deprecated in /opt/crm7/app/Fields/File.php, line 253`

is triggered by

```
foreach ($param as $key => $value) {
    $instance->{$key} = $value;
}
```

### 🔥 How to trigger the error

1. Run mail scanner on an e-mail that includes attachements
2. See error

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 7.0.1
| PHP                                 |  8.3.7              |

**Comment by rskrzypczak** [comment]
Thanks! Fixed in YF7.0.2
