### ISSUE TITLE
Aktualizacja

### ISSUE THREAD

**Issue by slawhodu** [YetiForceCompany/YetiForceCRM#1746]
Przy aktualizacji z wersji 2.0 do wersji 2.1 mam komunikat:
Błędna wersja modułu, wersja modułu 2.0.0 a powinna być większa niż 2.0.1
Jak mogę zaktualizować wersję?

**Comment by rskrzypczak** [comment]
https://yetiforce.com/pl/dokumentacja-administratora/aktualizacja/174-aktualizacja-yetiforce-crm.html

**Comment by slawhodu** [comment]
czyli 'oszukać' instalatora i wpisać to czego potrzebuje..., tak?

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%202.x.x/2.0.0_to_2.1.0/zip
i zmieniasz numer wersji w pliku version.php u siebie w CRM :)

**Comment by slawhodu** [comment]
Fatal error: Call to a member function FetchRow() on a non-object in /volume1/web/yetiforce2.0/include/database/PearDatabase.php on line 506

**Comment by bpabiszczak** [comment]
Co pokazały logi podczas aktualizacji systemu z wersji 2.0 do 2.1?

**Comment by slawhodu** [comment]
[10-Aug-2015 13:03:13 Europe/Sarajevo] PHP Fatal error:  Call to a member function FetchRow() on a non-object in /volume1/web/yetiforce2.0/include/database/PearDatabase.php on line 506

tylko tyle...

**Comment by bpabiszczak** [comment]
Ale to jest log co wypluwa Tobie przeglądarka? Jeżeli tak, to nie o takie logi chodzi:

Po pierwsze aktualizowałeś system [przynajmniej z tego co widzę powyżej] a więc pytanie brzmi, co Ci pokazały logi podczas aktualizacji [jeżeli tam były jakieś błędy to mogą one generować inne błędy później]

Po drugie należy włączyć debugowanie w samym systemie [tu jest dokumentacja: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/109-debugowanie.html i przesłać istotną część logów [z błędami]. 

Po trzecie ja nie wiem gdzie i kiedy ten błąd Ci się pojawia, więc powinieneś jasno opisać jak po kroku taki błąd wywołać np. na wersji testowej u nas.
