### ISSUE TITLE
[bug] errors in yetiforce 7.0

### ISSUE THREAD

**Issue by aleterracciano** [YetiForceCompany/YetiForceCRM#17478]
# 🐞 errors in navigation yetiforce 7.0

### ⁉️ Hi, I'm viewing the new version of Yetiforce, version 7.0 from your online demo. I would like to communicate two errors present in the navigation of the forms.

- in the first tab of the "CONTACTS" module, if I click on a contact, I am redirected to the administrator's "USER" tab. I logged in as ADMIN.

**Comment by rskrzypczak** [comment]
There is no error here, you must have clicked on the user's link (record owner, etc.).
