### ISSUE TITLE
[bug] Calculate Sum in Related module list view NOT Working yetiforce7

### ISSUE THREAD

**Issue by shawkatmarrouf** [YetiForceCompany/YetiForceCRM#17482]
# 🐞 bug report

### 🔥 How to trigger the error

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/101041720/e7e90e89-acfb-4f00-a87b-c6406dd19905)

and here is the console log:
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/101041720/ae42b1bc-e8c1-4460-8f37-668cf6faad67)

### 👎 Actual Behavior
when pressing the button in the related module list view it doesn't do any thing and console gives mentioned error!

### 👍 Expected Behavior

when pressing the button, it should sum the column. but it don't **In related Module list view**.

### 👷 Testing

The error appears on the yetiforce demo. and screen shots has been taken from the demo.

**Please advice to fix this cuz its critical issue**

**Comment by shawkatmarrouf** [comment]
@prabhu @majkel89 @vctrin

**Comment by rskrzypczak** [comment]
Thanks, fix in YF7.0.2
