### ISSUE TITLE
Problems with Scrollbar

### ISSUE THREAD

**Issue by agilisgmbh** [YetiForceCompany/YetiForceCRM#1749]
Hi Guys, dont know if it´s just on my PC, but in every Module I´ve got this horrible scrollbar, which is
unneccessary und dont looks fine. 
First of all: Just want to have it on top,
2nd: hot to only show if needed (many colums)?

Any Idea how to get rid of it?

<a href="http://imgs.url1y.com/#/view/photo/tk2ynjqjsigpo76x/Screenshot_2015.08.10_003.png" target="_blank"><img src="http://imgs.url1y.com/uploads/1/8/tk2ynjqjsigpo76x.png" alt="Screenshot_2015.08.10_003.png" /></a>

**Comment by rskrzypczak** [comment]
Improved the moment of displaying the Scrollbar.
Hiding the bottom Scrollbar is very complicated and you can't hide it in any simple way.
