### ISSUE TITLE
[bug] Słownik wielokrotnego wyboru 

### ISSUE THREAD

**Issue by TurzyRGD** [YetiForceCompany/YetiForceCRM#17524]
Jest zbyt duży odstęp pomiędzy wartościami pola słownikowego wielokrotnego wyboru, tak jak poniżej: 
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/69916900/d24002b8-0f40-4a02-bee8-628814921d33)

Czy da się to jakoś szybko i prosto naprawić?

**Comment by shawkatmarrouf** [comment]
I've posted this weeks ago ... https://github.com/YetiForceCompany/YetiForceCRM/discussions/17497

**Comment by rskrzypczak** [comment]
fix in YF7.0.2
