### ISSUE TITLE
[bug] Unbale to update from 6.3 to 6.4

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#17528]
Hello,

I am facing same issue as per Issue No. https://github.com/YetiForceCompany/YetiForceCRM/issues/16441
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/12723595/9b4c133f-1e1c-4d4b-8a26-d935709d1eb5)

What is the solution.

Jeevan Pendhari

**Comment by JEEVAN28** [comment]
Hi, any help in this matter, I would like to move to latest release

**Comment by rskrzypczak** [comment]
The update package file is probably corrupted.
- go to `/cache` folder and delete all zip files.
- go to `/app/RequestHttp.php` and increase the timeout
```php
	public static $timeout = 60;
```
- download the update package again
