### ISSUE TITLE
[Enhancement] Quick Edit - analogous to Quick Create

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#1753]
It would be nice if one could open related record in modal window similar to Quick Create. For example, while in Summary View or Detail View of Opportunity, I could click on a link in Calculations widget and open related Calculation in modal window, quickly edit and save calculation record, without leaving Opportunity.

**Comment by bpabiszczak** [comment]
This is how it works in my opinion. In Sales Opportunity, in the calculations tab I clicked "add record", I added the calculation and it moved me automatically to Sales Opportunity.

**Comment by nikdejan** [comment]
I suppose I wasn't clear enough. I know that it works OK when adding records. I would like it to work the same when EDITING record. I would like it like this: In Sales Opportunity, in the calculations tab, I click on Quick Edit button (should exist) for related Calculation, MODAL window, similar to Quick Create, opens, and in that window I can Quick Edit Calculation and than press Save, without leaving Opportunity.
Same could be useful when in Opportunity Summary View. Related Module Widget which shows related Calculations would have Quick Edit buttons for each Calculation (or any other related record). I click on a button, modal window opens, I edit calculation, click Save. Modal disappears, and I'm still in Sales Opportunity Summary View.
Basic Idea is to have new view, for every module that has Quick Create. And that view could be usefull in different occasions.

**Comment by bpabiszczak** [comment]
At the moment there's no quick edit for product modules and for the time being we don't plan to change that.

**Comment by nikdejan** [comment]
What I had in mind is similar to modal window of new modules. The most important thing is that we can preview record and change status from modal window. Being able to edit field values would be a nice addition.
