### ISSUE TITLE
[bug] Mail Scanner fails if not mails to import

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#17535]
# 🐞 bug report

### ⁉️ Describe the bug

`PHPIMAP` throws an exception stating `Empty response` when running the cron job to import e-mails (LBL_MAIL_SCANNER_ACTION).

```php
2024-07-08 08:25:02 | LBL_MAIL_SCANNER_ACTION - Start task
Webklex\PHPIMAP\Exceptions\ResponseException: Command failed to process:
Causes:
	- Empty response
Error occurred in /opt/crm7/vendor/webklex/php-imap/src/Exceptions/ResponseException.php:53
Stack trace:
#0 /opt/crm7/vendor/webklex/php-imap/src/Connection/Protocols/Response.php(318): Webklex\PHPIMAP\Exceptions\ResponseException::make()
#1 /opt/crm7/vendor/webklex/php-imap/src/Connection/Protocols/Response.php(308): Webklex\PHPIMAP\Connection\Protocols\Response->validate()
#2 /opt/crm7/vendor/webklex/php-imap/src/Query/Query.php(525): Webklex\PHPIMAP\Connection\Protocols\Response->validatedData()
#3 /opt/crm7/vendor/webklex/php-imap/src/Query/Query.php(573): Webklex\PHPIMAP\Query\Query->filter()
#4 /opt/crm7/app/Mail/Connections/Imap.php(163): Webklex\PHPIMAP\Query\Query->getByUidGreater()
#5 /opt/crm7/app/Mail/Scanner.php(126): App\Mail\Connections\Imap->getMessagesGreaterThanUid()
#6 /opt/crm7/modules/OSSMailScanner/crons/Scann.php(46): App\Mail\Scanner->run()
#7 /opt/crm7/cron.php(100): OSSMailScanner_Scann_Cron->process()
#8 {main}
```

### 🔥 How to trigger the error

1. Run `php cron.php`
2. See error

### 👎 Actual Behavior

The cron run raises an exception (as show above).

### 👍 Expected Behavior

The cron run completes successfully.

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com
- [x] cannot be tested on cloud solution

### 📷 Screenshot of configuration

![ConfReport](https://github.com/YetiForceCompany/YetiForceCRM/assets/10230144/84d4eb27-d4a5-4c6a-b554-29665df2d641)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

See above for log message in cache error file.

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 7.0.1
| Web server (name and version)       | apache2   2.4.58              |
| PHP                                 |    8.3.9            |
| Browser (name and version)          | n/a               |
| Operating System (name and version) | Linux               |
| Database (name and version)         | MariaDB 11.4.2 |
| Service Pack version                |                |

### ❓ Additional context

N/A

**Comment by diderich** [comment]
It seems that replacing
```php
public function getMessagesGreaterThanUid(string $folderName, int $uid, int $limit)
{
    return $this->getFolderByName($folderName)->query()->limit($limit)->getByUidGreater($uid);
}
```

in `app/Mail/Connections/Imap.php`

by
```php
public function getMessagesGreaterThanUid(string $folderName, int $uid, int $limit)
{
    try {
       return $this->getFolderByName($folderName)->query()->limit($limit)->getByUidGreater($uid);
    }
    catch(\Exception $err) {
      return new \Webklex\PHPIMAP\Support\MessageCollection();
    }
}
```
solves the  problem, but I don't know whether that is the right way of addressing the problem.

**Comment by joice-martins** [comment]
Having problems with the import here as well.
Any chance you could help with my issue #17565? :(

**Comment by rskrzypczak** [comment]
fix in YF7.0.2
