### ISSUE TITLE
[Customization enhancement] Allow customization of summary data

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1754]
Add customization logic (see also https://www.yetiforce.com/en/developer-documentation/engine/177-loader-and-autoloader-of-files.html) also to summary data configures through files in files in `summary_blocks` by adjusting the function `getSummaryInfo` in file `modules/Vtiger/models/Record.php`.

To remove a summary block (not display it), the customization directory could contain an empty file with the same name as in the original directory.

**Comment by paula-w** [comment]
Can you describe step by step what's wrong or what's missing? Because we don't quite understand this issue.

**Comment by diderich** [comment]
Currently, to customize the information displayed in the summary block has to be done in the core files of the CRM system.
It would be great if making a copy of the modified summary block files into the custom directory (see also https://www.yetiforce.com/en/developer-documentation/engine/177-loader-and-autoloader-of-files.html) and making the customization there rather than in the main system would be possible.
Currently the system only looks for summary block files in the main system but not in the custom directory.

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
