### ISSUE TITLE
I can't map advanced blocks/add products while creating new opportunities.[bug] 

### ISSUE THREAD

**Issue by joice-martins** [YetiForceCompany/YetiForceCRM#17547]
I created an advanced block in Opportunities. My goal is to add products while creating new opportunities. I managed to add the fields for products, but I'm unable to update the products module within opportunities. Currently, the information is saved in Details, but I want it to be saved in Products.
![image](https://github.com/user-attachments/assets/a798de08-fb6f-4c20-82b8-7c13107e0940)
I've searched everywhere, and the documentation on Yeti is very vague and lacks detailed information.

Here's where it's currently saved:
![image](https://github.com/user-attachments/assets/38cfedb3-8476-45c3-88bc-3e05e7f75298)

And here's where I'd like it to be saved:
![image](https://github.com/user-attachments/assets/5950dc80-b8ff-4ef8-a3b6-a58924c4b4ef)

Here is my attempt at mapping (though I'm not sure if mapping is the correct approach):
![image](https://github.com/user-attachments/assets/85b340db-b7c9-4dc0-86ea-69435995ddcf)

I tried to map it, but it doesn't let me map advanced blocks. I also attempted custom field mapping, but it only allows mapping leads to accounts.

Would anyone be able to help me with this?

Please note that I'm not a developer. Thank you in advance.

**Comment by rskrzypczak** [comment]
The M:M relation you're trying to add here is unavailable in the record creation view.
This kind of relations can only be added once the record is saved, which you showed on the screenshot.

I don't really understand what you're trying to do.
The advanced block was never meant to allow you to edit the products.
You're trying to create some strange sales process here.
Either way, you won't be able to edit products on the create/edit opportunity layer.

There are no errors here so I'm closing this ticket.
