### ISSUE TITLE
Yetiforce 7.1 installation failed [bug] 

### ISSUE THREAD

**Issue by aleterracciano** [YetiForceCompany/YetiForceCRM#17555]
Hi everyone, I'm trying to install Yetiforce version 7.0.1 on shared hosting to carry out import tests from an old version. After having correctly configured the database and administrator user, it gives me a failed result. No system logs and no useful information. I have set the server configurations to the maximum, since it is shared I cannot go further. Can you tell me where the problem might be?

# 🐞 bug report
![image](https://github.com/user-attachments/assets/ec3cf1fb-d59d-44ec-8698-a6e9d31300b2)

![image](https://github.com/user-attachments/assets/d425aeb2-949c-4b85-8066-bda4ec06dbab)

**Comment by rskrzypczak** [comment]
As far as the issues you're experiencing are concerned, you probably need to raise your database engine version. The YetiForce 7.0 version requires MySQL 8.0.13 or later, or MariaDB 10.6 or later. 

The sql-mode parameter in the database configuration must not contain STRICT_TRANS_TABLE and ONLY_FULL_GROUP_BY. To make it easier, sql-mode can even be empty. 

https://doc.yetiforce.com/introduction/requirements#core-server-software-lamplemp

**Comment by aleterracciano** [comment]
> As far as the issues you're experiencing are concerned, you probably need to raise your database engine version. The YetiForce 7.0 version requires MySQL 8.0.13 or later, or MariaDB 10.6 or later.
> 
> The sql-mode parameter in the database configuration must not contain STRICT_TRANS_TABLE and ONLY_FULL_GROUP_BY. To make it easier, sql-mode can even be empty.
> 
> https://doc.yetiforce.com/introduction/requirements#core-server-software-lamplemp

Hi, thanks for the reply. I checked my DB version and I see that the version is compatible. I'm using a shared server, so I can't and I don't think I can change the description of SQL MODE. Are you saying I should change it?

![image](https://github.com/user-attachments/assets/144ee6a9-5772-460e-aa64-3b1f1d3742ab)

**Comment by aleterracciano** [comment]
I thought about increasing the php version to 8.3, recommended by Yetiforce, but I end up with the same problem. Installation failed.
How do I produce error logs? There aren't any at the moment

![image](https://github.com/user-attachments/assets/fc10ed83-5aed-4692-ba89-a670f9097c1d)

**Comment by rskrzypczak** [comment]
https://doc.yetiforce.com/developer-guides/debug

**Comment by aleterracciano** [comment]
Thanks, I have enabled error logging. Below I have logs.
I can't understand what it depends on.

#0 [error][Install] PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist in /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:27
Stack trace:
#0 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Driver/PDO/Connection.php(27): PDO->exec()
#1 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(869): Doctrine\DBAL\Driver\PDO\Connection->exec()
#2 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(1131): Doctrine\DBAL\Connection->executeStatement()
#3 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(1071): Doctrine\DBAL\Connection->rollbackSavepoint()
#4 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/TransactionHelper.php(56): Doctrine\DBAL\Connection->rollBack()
#5 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(59): Doctrine\Migrations\Tools\TransactionHelper::rollbackIfInTransaction()
#6 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(136): Doctrine\Migrations\DbalMigrator->executeMigrations()
#7 /home/testcmcrv3/domains/test-company.crcema.it/public_html/app/Db/Migrations/Doctrine/Migrator.php(60): Doctrine\Migrations\DbalMigrator->migrate()
#8 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/models/InitSchema.php(67): App\Db\Migrations\Doctrine\Migrator->migrate()
#9 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/models/InitSchema.php(27): Install_InitSchema_Model->initializeDatabase()
#10 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/views/Index.php(359): Install_InitSchema_Model->initialize()
#11 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/views/Index.php(140): Install_Index_View->step6()
#12 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/Install.php(43): Install_Index_View->process()
#13 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist in /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28
Stack trace:
#0 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Driver/PDO/Connection.php(33): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(869): Doctrine\DBAL\Driver\PDO\Connection->exec()
#2 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(1131): Doctrine\DBAL\Connection->executeStatement()
#3 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(1071): Doctrine\DBAL\Connection->rollbackSavepoint()
#4 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/TransactionHelper.php(56): Doctrine\DBAL\Connection->rollBack()
#5 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(59): Doctrine\Migrations\Tools\TransactionHelper::rollbackIfInTransaction()
#6 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(136): Doctrine\Migrations\DbalMigrator->executeMigrations()
#7 /home/testcmcrv3/domains/test-company.crcema.it/public_html/app/Db/Migrations/Doctrine/Migrator.php(60): Doctrine\Migrations\DbalMigrator->migrate()
#8 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/models/InitSchema.php(67): App\Db\Migrations\Doctrine\Migrator->migrate()
#9 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/models/InitSchema.php(27): Install_InitSchema_Model->initializeDatabase()
#10 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/views/Index.php(359): Install_InitSchema_Model->initialize()
#11 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/views/Index.php(140): Install_Index_View->step6()
#12 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/Install.php(43): Install_Index_View->process()
#13 {main}

Next Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist in /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:90
Stack trace:
#0 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(1364): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()
#1 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(1306): Doctrine\DBAL\Connection->handleDriverException()
#2 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(871): Doctrine\DBAL\Connection->convertExceptionDuringQuery()
#3 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(1131): Doctrine\DBAL\Connection->executeStatement()
#4 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/dbal/src/Connection.php(1071): Doctrine\DBAL\Connection->rollbackSavepoint()
#5 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/TransactionHelper.php(56): Doctrine\DBAL\Connection->rollBack()
#6 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(59): Doctrine\Migrations\Tools\TransactionHelper::rollbackIfInTransaction()
#7 /home/testcmcrv3/domains/test-company.crcema.it/public_html/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(136): Doctrine\Migrations\DbalMigrator->executeMigrations()
#8 /home/testcmcrv3/domains/test-company.crcema.it/public_html/app/Db/Migrations/Doctrine/Migrator.php(60): Doctrine\Migrations\DbalMigrator->migrate()
#9 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/models/InitSchema.php(67): App\Db\Migrations\Doctrine\Migrator->migrate()
#10 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/models/InitSchema.php(27): Install_InitSchema_Model->initializeDatabase()
#11 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/views/Index.php(359): Install_InitSchema_Model->initialize()
#12 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/views/Index.php(140): Install_Index_View->step6()
#13 /home/testcmcrv3/domains/test-company.crcema.it/public_html/install/Install.php(43): Install_Index_View->process()
#14 {main}

**Comment by aleterracciano** [comment]
Thanks, I solved it. I created a new Database and tried the installation again.
