### ISSUE TITLE
Crashing on new invoice creation [bug] 

### ISSUE THREAD

**Issue by solarisdigital** [YetiForceCompany/YetiForceCRM#17557]
Good day, ever since I updated the system to version 7.0.1, I noticed that any time I try and create a new invoice, it crashes and tells me to contact admin, go back or go to dashboard.

![Server-configuration](https://github.com/user-attachments/assets/ac15f20c-743f-49f5-8c5a-117c4259902e)

 It basically happens with only some of the products that are in the system and any new one I add. Whether I add a symbol in the name like a dash or just plain words, it's the same crash.

# 🐞 bug report

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [x] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |
| Web server (name and version)       |                |
| PHP                                 |                |
| Browser (name and version)          |                |
| Operating System (name and version) |                |
| Database (name and version)         |                |
| Service Pack version                |                |

**Comment by rskrzypczak** [comment]
fix in YF7.0.2
