### ISSUE TITLE
[UI Enhancement] Data block looked much nicer in 2.0 than in 2.1

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1756]
I prefer the formatting used by the data block in 2.0 rather than in 2.1
* Line below the title (to be consistent with other widgets)
* Use same margin as in other widgets (do not align blocks to the left)
* Use space between boxes
* Do not use bold typespace

2.0: 
![imgold1](https://cloud.githubusercontent.com/assets/10230144/9201896/92ca33b2-404f-11e5-9b15-4c916e46a017.jpg)
2.1:
![imgnew1](https://cloud.githubusercontent.com/assets/10230144/9201914/a1df3de8-404f-11e5-9577-5fe151a78982.jpg)

**Comment by florek41** [comment]
In your case is not so bad, look how it looks in mine config:
![summary](https://cloud.githubusercontent.com/assets/4824588/9207456/0cc0f674-406e-11e5-8cdd-15b993d38555.JPG)

but I agree - design should be improved !
