### ISSUE TITLE
[bug] Unable to edit the imported contact records

### ISSUE THREAD

**Issue by Ilamparithi-Tamizhanangu** [YetiForceCompany/YetiForceCRM#17577]
Hi,

whenever i edit the imported contacts, it returns the error as "A contact with this email address already exists in the system".

![image](https://github.com/user-attachments/assets/16c035c1-be4b-45cb-b229-a43bc692eb02)

I tried the same with demo environment and returing the same issue. 

Procedure:

1. I created the new record. 
2. export the record as csv file
3. delete the contact record
4. import the record
5. edit the contact -> it generate the error as email id already exist.

Please provide the solution to fix the same.

Thanks & regards,
Rajasekaran.

**Comment by Ilamparithi-Tamizhanangu** [comment]
The same issue present in the yetiforce 6.5 & 7.0.1 version.

**Comment by rskrzypczak** [comment]
There is no error here.
You probably have duplicates in your trash.
You need to permanently delete them from your system (empty the trash)
If you don't care about this validation, you can always turn it off
![image](https://github.com/user-attachments/assets/e8d6eedb-8692-452c-90e1-8980d2451d8c)

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi,

Thanks for the guidance. 

After deleting it from the recycle bin, i can edit the records. :)
