### ISSUE TITLE
Error while migrating Vtiger 6.3 -> Yetiforce 2.1

### ISSUE THREAD

**Issue by nalancz** [YetiForceCompany/YetiForceCRM#1758]
While migrating from VT 6.3 to YF 2.1 following error occurs:
LBL_ERROR_WRONG_VERSION

It seems that only migration supported for now is VT 6.2 -> YF.

**Comment by paula-w** [comment]
Migration from Vtiger works only for full versions, so you should use the YetiForce 2.0 installation package, and after the migration update it to v2.1.

**Comment by nalancz** [comment]
Anyway, it is not a problem with Yetiforce version but with VT version supported during migration - 
launching YF 2.0.0 installation still does not do the job and error repeats.

**Comment by rskrzypczak** [comment]
In YetiForce v2.0.0 the migration is possible only from Vtiger v6.2. Migration from VT6.3 will be possible only in Yetiforce v3.0.0

**Comment by preexo** [comment]
since Yetiforce 3.0 is available now, will migration work from vtiger 6.4 to 3.0? Where can we find some documentation about the process?

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
the migration will be available for free in our online shop in about 1-2 weeks. We haven't managed to prepare it but we didn't want to delay the release of the system

**Comment by s6930064** [comment]
Migration from vtiger 6.4 to YetiForce when and how?

**Comment by bpabiszczak** [comment]
1 question = 1 issue.
