### ISSUE TITLE
WYSWYG editor HTML field

### ISSUE THREAD

**Issue by ojundi** [YetiForceCompany/YetiForceCRM#1761]
Symptoms

The html editor field in ticket or any custom module does not allow upload of any image.. error missing url appears.

**Comment by ojundi** [comment]
Can the image attachment in the html editor  be sent to email by work flow ?

**Comment by paula-w** [comment]
Can you tell us where exactly the images cant be uploaded? It would be best if you provided us with a  short clip showing that error, or described in detail how to trigger that error in the developer version.
