### ISSUE TITLE
[enhancement] Kaban board in ToDo and in Projects

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1763]
It would be great to see Kaban board in YF. I thing for start it will be very useful in ToDo's and in Projects (projects tasks). Maybe in other modules too. It's time-saver and the work progress is much more clear.

The most popular, commercial Kaban tool is Trello https://trello.com/ but there is a open-source https://github.com/libreboard/libreboard alternative and I can imagine it integrated with YF :)
We can have a different/new Wirtual Desk screen with Kaban (for ToDo's) and new view in other modules (like "List view" and "Dashboard")

**Comment by bpabiszczak** [comment]
What makes this functionality better than Gantt chart in your opinion? Of course, Gantt charts will be improved and developed, but I think they're clearer and have more potential.
