### ISSUE TITLE
[Improvement?] New calendar activity type not showing as new choices

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1766]
Related to #1733 
When you create new activity types, lets say you add 'holiday' to the list. It does now get added to to the slider list in the calendar itself. Then there is no way to see the 'holidays' in the overview. They do show up in the listing. Would be nice to have them in the overview too.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1766
