### ISSUE TITLE
Mail template tickets invalid variable

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1767]
Not a major issue but in the pre made templates for the helpdesk I see a non working variable all the time. Did not really find yet what it should represent but might be good to fix this anyway (last line):

![screen shot 2015-08-13 at 09 37 15](https://cloud.githubusercontent.com/assets/10379403/9244823/2ba545d6-419f-11e5-9868-7786d72615bf.png)

![screen shot 2015-08-13 at 09 40 03](https://cloud.githubusercontent.com/assets/10379403/9244843/517e6346-419f-11e5-9a4b-4fb30b5fa066.png)

**Comment by MaciejStencel** [comment]
This field was connected to removed contact id. Removed it from mail templates.
