### ISSUE TITLE
[Improvement] To allow assign one contact to multiple accounts

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1768]
Currently one contact can be assigned to only one company. In many life scenarios it is not enough and ability to assign more accounts would be useful. In my situation I have to create several time the same contact to let workflows send appropriate documentation to head office manager and subordinate entities across the world

**Comment by Dieter01** [comment]
It is right, many people work for, or own, multiple companies. So it should be possible, to have some kine fo n:n assignment.

**Comment by bpabiszczak** [comment]
We are not planning to add a functionality like that anytime soon. The change of logic would cause a variety of problems. We will only add the possibility to relate a contact to a contact.
