### ISSUE TITLE
[ISSUE] BRANCHES

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1769]
Something I'm confused, how am I going to pull branches to transfer files?

**Comment by MaciejStencel** [comment]
Can You be more specific? I'm not sure what do You mean?

You just want to download other YF branches, like for example "developer"?

**Comment by waw555** [comment]
in the master branch version of the system behind the developer version of what urgent likely not be that I change a file, do pull request, and he will not get in the assembly?

**Comment by MaciejStencel** [comment]
Still not sure what You mean but outside pull requests will be incorporated to whatever branch they were meant to be. If you send pull request to "developer" it will be added there, once every few days, one person reviews new changes to dev and send them to master. So your additions to developer would eventually end in master also.

Does that answer your question?

**Comment by waw555** [comment]
Yes
