### ISSUE TITLE
[NEW FUNCTIONAL] Custom Process

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1773]
Dear developers, please add a custom button to all modules.
The essence of the button is the same as in the treatment, only treatment converts the button and the button should perform the following operations according to the settings.

This button should be different from all the others indicate that the button leads to the next step sales

For example:

Created appeal - Next is the conversion to the Counterparty
Created Counterparty - Next you need to create a Transaction
Created Deals - Next you need to create Calculation
Created Calculator - Next, you must create an Offer

And so on

This sequence should be adjusted in the settings.

This feature is very convenient for those who do not use all of the modules and who have to do everything step by step.

**Comment by nikdejan** [comment]
This is so +1

**Comment by SkavenKF** [comment]
This is what i mean in my comment to #1656 when i wrote the following:

"... and more flexibilty in customizing the process framework. ..."
*

**Comment by florek41** [comment]
It would be great !
In my case I will be able to configure Sales Order -> Production Order process.

This feature extremely increase system flexibility and allow users to create custom way sale process.

+1

**Comment by nikdejan** [comment]
+1

**Comment by bpabiszczak** [comment]
-8 ;)

**Comment by reeid** [comment]
+9

**Comment by bpabiszczak** [comment]
Unfortunately I totally disagree.

The functionality you write about exists in the system and seems to be sufficient. The order of individual modules shouldn't be controlled by a button or some configuration like you suggested, but by fields and relations between them. The best example is "Calculation", which includes a field called "requirements card", it's a mandatory field, which enforces a certain order [it means that "the requirements card must be created before the calculation"] 
If in some particular company this process seems too extensive, the company can disable this field or make it non-mandatory in the module, and it will be possible to create calculations without the requirements card. We can build a sequence of events and enforce that sequence on the users if we use the fields properly. 
The second functionality is the possibility to generate records from module A in module B, for example from offer > orders. We added proper mechanisms, that automatically fill the fields in module B, to the system [you have to create a table in the right place] and you have to add an action button in module A, which will create a record in module B in edition mode. It requires a little programming knowledge to be able to do that.

The most important thing is that in most companies the processes are the same [they are called in different ways, or they aren't fully utilized]. Our goal is to create complete processes for:

Marketing
Sales
Logistics
Projects
Support

the end user can disable some of them [we added a safety mechanism lately – disabling a module disables uitype10 fields].

**Comment by florek41** [comment]
@bpabiszczak can you give us some tips about this function (generate record in module B form record in module A) ?

**Comment by bpabiszczak** [comment]
At the moment there is no mechanism that could create a button like that [create record B from module A], but it can be easily done from the  programming perspective... 
I don't understand the second question unfortunately.
