### ISSUE TITLE
[ISSUE] PDF Template Product Block

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1774]
Where to change the array of products and services in PDF templates

How to make a similar unit with products and services?

![animation 115](https://cloud.githubusercontent.com/assets/1402355/9252726/55ff3cd4-41f3-11e5-88e3-de2003ce52dc.gif)

**Comment by bpabiszczak** [comment]
Generating PDF will be improved after releasing the new product module. At the moment you can't change anything as far as products/services are concerned, without modifying files in this folder: : https://github.com/YetiForceCompany/YetiForceCRM/tree/stable/modules/OSSPdf/special_functions. Unfortunately, OSSPDF is a very old module and requires code refactoring, it will be improved soon.
Remember that part of the columns can be controlled in configuration:  https://test.yetiforce.com/index.php?module=OSSPdf&view=Index&parent=Settings&block=4&fieldid=35  but nobody has used it for a very long time, so some elements might not work as you'd expect them to.
