### ISSUE TITLE
[BUG] Marketing processes and Leads Converting

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1777]
![animation 117](https://cloud.githubusercontent.com/assets/1402355/9253167/d75b726e-41f5-11e5-9a65-90a4345d92c6.gif)

**Comment by MaciejStencel** [comment]
Problem with missing buttons is solved. Added new option in the configuration where You can set what statuses allow to convert lead, nothing set then lead can be always converted.

Please test it on gitdeveloper.yetiforce.com.
