### ISSUE TITLE
Pytanie odnośnie polskich znaków podczas importu UTF8

### ISSUE THREAD

**Issue by r0bertk** [YetiForceCompany/YetiForceCRM#1780]
Witam,
dlaczego jak u mnie wpiszę w CRM np w nazwa kontrahenta  polskie znakami to jest OK, natomiast jak wyeksportuję tego kontrahenta i próbuję zaimportować to yetiforce pokazuje mi na polskich znakch pytajniki??(w oknie importu pokazuje polskie znaki ale po zaimportowaniu już są pytajniki) próbowałem konwertować na UTF8 bez BOM itd., ale to nie przynosi rezultatu. 
Natomiast jak spróbowałem zrobić import na Państwa stronie testowej  yetiforce to system ładnie zaczytuje mi polskie znaki z tego samego pliku .csv który u mnie importuje bez polskich ogonków. 
Co może być powodem? Konfiguracja mojego serwera? jeśli tak to co mogę zmienić, aby było OK?

Z gory dziękuję za odpowiedź.

Pozdrawiam Robert

**Comment by bpabiszczak** [comment]
Przypuszczam, że najprawdopodobniej, ma Pan złe kodowanie w bazie danych, jakie kodowanie mają tabele?

**Comment by r0bertk** [comment]
Dziękuję za podpowiedź, rzeczywiście miałem złe kodowanie w bazie mysql.
Pomogł wpis:

ALTER DATABASE `nazwa` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

Jeszcze raz dziękuję i pozdrawiam
Robert

**Comment by bpabiszczak** [comment]
Polecamy się. Jak polubisz nasz system, to zawsze możesz polubić nas na GitHub i dać opinię na http://sourceforge.net/projects/yetiforce/
