### ISSUE TITLE
Import duplikaty

### ISSUE THREAD

**Issue by r0bertk** [YetiForceCompany/YetiForceCRM#1781]
Witam,
będę potrzebował importować dane do yetiforce i mam pytanie w tej kwestii, mianowicie będę importował dane które będą się duplikować np imię, nazwisko, miejscowość, telefon, email. W tej chwili z tego co przetestowałem to mogę sprawdzać duplikaty po kilku polach, ale jeśli wybiorę aby system sprawdzał duplikaty po Imię, Nazwisko, miejscowość, telefon, email to jak jedna z danych nie będzie wypełniona bądź będzie inna to system utworzy nowego kontrahenta.
Ja chciałbym zapytać czy jest taka opcja, aby system sprawdzał każde pole po kolei i jeśli np 3 pola (możliwość ustawienia ile pól) się pokryją to traktuje import jako duplikat. Np pokrywają się pola Imię, Nazwisko, e-mail (wtedy system wykrywa duplikat).

Pytam ponieważ będę miał sporo osób które mają tak samo na imię i nazwisko i potrzebuję dotakowej danej identyfikującej czy kowalski to napewno ten kowalski tylko problem w tym że nie wszyscy będą mieć wypełnione pola miejscowość, telefon, email.Mogą mieć wypełnione w róznej konfiguracji i z błędami typu literówki

Z gory dziękuję za odpowiedź.

Pozdrawiam Robert

**Comment by bpabiszczak** [comment]
Tak działa duplikat, wybiera Pan np. 3 pola jeżeli są one sobie równe oznacza to duplikat. Jeżeli któreś pole jest puste np. email to nie ma to dla niego znaczenia i dwie osoby o tym samym imieniu i nazwisku bez emaila oznaczy jako duplikat.
