### ISSUE TITLE
Scheduler Doesn't Works after 2.1 update

### ISSUE THREAD

**Issue by VSecurity** [YetiForceCompany/YetiForceCRM#1782]
Hello.

I had Yetiforce 2.0 and everything worked. After the update my scheduler stopped to work. How can I solve this?

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html
