### ISSUE TITLE
[DESIGN IMPROVED] Dublicate Button Search

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1783]
Remove one search button on the right, it will increase the space.
![animation 120](https://cloud.githubusercontent.com/assets/1402355/9266258/050f3580-4258-11e5-8ce4-9242d2559c9e.gif)

**Comment by florek41** [comment]
Maybe instead delete this button change it function to reset filter to default (remove all inserted data form fields) ?

**Comment by konadrian** [comment]
Deleted a duplicate search button, added a button to reset search. Changes see on https://gitdeveloper.yetiforce.com
