### ISSUE TITLE
[ISSUE] Leads Convert

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1785]
How to remove a tick by default Create Opportunity?
![animation 122](https://cloud.githubusercontent.com/assets/1402355/9266379/bf0708d6-4259-11e5-8499-4fe8d690f66f.gif)

**Comment by bpabiszczak** [comment]
In my opinion it's ok, it's enabled by default because it's logical, if someone wants to convert a lead it means that he talked to the lead and wants to begin a sales process. If he doesn't want to begin the sales process on this lead, then why convert it ?

**Comment by echemik** [comment]
Not every implementation uses Opportunity. For me it should be possible to uncheck. (eg. new lead send you order, why use Opportunity?

**Comment by nzi200779** [comment]
Hi , Im on version 4 and I dont not have the option to convert lead to opportunity, did this fall away sometime in the past?

**Comment by KatarzynaUlichnowska** [comment]
Yes, we deleted that a few versions ago.

**Comment by nzi200779** [comment]
oh, ok, Is there a way I can do this? I tried doing it via a workflow - create an entity, but no option to create an opportunity there.
