### ISSUE TITLE
[BUG] Update and Logs

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1787]
Established last clean system

Today went to see the logs

remarks

[14-Aug-2015 08:04:01 Asia / Yekaterinburg] PHP Fatal error: Class 'SysDebug' not found in /www/default/include/logging.php on line 22

I decided to upgrade to version 2.1.39

I got another error

![animation 124](https://cloud.githubusercontent.com/assets/1402355/9266591/a98d7b9a-425c-11e5-9af5-6f7329db8026.gif)

**Comment by bpabiszczak** [comment]
What kind of an error are you reporting? I can see that you didn't have syslog even before the update, and after the update you only only got notice [which you shouldn't have, because if you do have them, it means your error_reporting is not configured properly]
