### ISSUE TITLE
[Idea] To insert sample data to each newly uploaded test version (master,developer)

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1788]
Hi guys, it will be cool if every new version will be settled on server with sample data. I am so bored creating new service, account, contact again and again when trying to surf testing version.
Why not get some additional script and insert some sample data to allow us just click and enjoy?
Organization (account), lead, contact, quote, invoice, sales order, service & product as a minimum

**Comment by bpabiszczak** [comment]
This work, but now only on test: https://test.yetiforce.com/

**Comment by bpabiszczak** [comment]
We want to create a script like that in the future, but at the moment we don't have enough time. If you make it on your own and send it to us, we will gladly add it :]
