### ISSUE TITLE
[DESIGN BUG] Clear install v 2.1

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1792]
![animation 126](https://cloud.githubusercontent.com/assets/1402355/9287814/c6250c28-4342-11e5-8327-791b6e87d844.gif)

**Comment by rskrzypczak** [comment]
![row_height](https://cloud.githubusercontent.com/assets/10221999/9318067/5951c622-4540-11e5-9056-1eafb0d6511a.jpg)
