### ISSUE TITLE
[BUG] _UNTRANSLATED_ on delete related milestone from project

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1802]
![projects-delete-milestone](https://cloud.githubusercontent.com/assets/4824588/9294838/5e37b878-4459-11e5-8af0-f9a2a2ff3a61.PNG)

**Comment by konadrian** [comment]
Changes see on https://gitdeveloper.yetiforce.com

**Comment by bpabiszczak** [comment]
This is most likely not an error. This is how we mark the phrases that must be translated by a translator.
