### ISSUE TITLE
Connect Employees to Users

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1805]
I've just imported all of our Employees into Users (after configuring the Roles and Groups).

When I went to put them into Employees, I saw there was no association between the 2.  That might be a nice addition...the ability to move employees to users and link them

**Comment by bpabiszczak** [comment]
As far as I remember, relating an employee and a user is based on the 'owner of the record' field in employees.

**Comment by mykljohn** [comment]
Are you referring to the "Assigned To" field?  Should it be set to the User?  
for example: Employee Bob Smith > Assigned To Bob Smith
