### ISSUE TITLE
Mail Client Setup problems

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1806]
I've been trying to get the Mail Client working, but to no avail.  I followed the limited instructions, but I just get Login Failed.  I'm not sure if I'm doing it right. 

1.  In Mail client screen, is the Name field from YF, i.e. "admin", the email username, i.e. ventas@xyz.com, or just something to identify that email client, i.e. "Bobs Email"?
2.  from my mailbox, when I log in, what username and password do I use?
3.  In MySQL, the table roundcube_Users is empty, when does these records get created?
4.  I looked at the code for OSSRoundCude, and it says not to use SSL.  Does this mean I can't use SSL and should set up the mailserver as IMAP non SSL? i.e. mail.xyz.com port 25 (outgoing)   (incoming) 995

Here's a portion of the logfile:

Aug 16 15:29:41 gator2345 dovecot: imap-login: Aborted login (auth failed, 3 attempts in 14 secs): user=<ventas@xyz.com>, method=PLAIN, rip=198.0.207.140, lip=198.0.207.140, TLS, session=<3uqcinMdjQDGOfeM> 
Aug 16 15:29:51 gator2345 dovecot: imap-login: Aborted login (auth failed, 3 attempts in 10 secs): user=<ventas@xyz.com>, method=PLAIN, rip=198.0.207.140, lip=198.0.207.140, TLS, session=<whRyi3MdCgDGOfeM> 
Aug 16 15:34:20 gator2345 dovecot: imap-login: Login: user=<ventas@xyz.com>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=73385, secured, session=<adwVnHMdyAB/AAAB> 
Aug 16 15:34:20 gator2345 dovecot: imap(ventas@xyz.com): Disconnected: Logged out in=243, out=966, bytes=243/966

**Comment by mykljohn** [comment]
If you need more info from me let me know.  I would like to get this resolved asap being I just talked my boss into switching from vtiger.  I installed the latest version of YF (2.1)  I will also be translating it to Spanish at some point.

**Comment by mykljohn** [comment]
I didn't close this.  Still pending

**Comment by mariuszkrzaczkowski** [comment]
Send us your mail client configuration so we will check if you set everything properly

**Comment by mykljohn** [comment]
Name	ventas@thegloboworld.com
Validate certificate	yes
Add type and protocol to address	yes
Name of IMAP server	gator3176.hostgator.com
Port used to connect to IMAP	993
Name of SMTP server	gator3176.hostgator.com
Login to SMTP server ( "%u" - login of logged in user)	ventas@thegloboworld.com
Password to SMTP server ( "%p" - password of logged in user)	%p
SMTP port (default 25; 465 for SSL; 587)	465
Language (RFC 1766 code): en_US, pl_PL	
en_US
Domain (automatically added to login)	
Logo	
Check IP address of client while giving authorization	
Spell check module	
Level of access to identity	
many identities with possibility of editing all parameters
Lifetime of session in minutes

**Comment by mariuszkrzaczkowski** [comment]
Try these settings:
Validate certificate - NO
Name of IMAP server -  ssl://gator3176.hostgator.com
Name of SMTP server ssl://gator3176.hostgator.com
Login to SMTP server ( "%u" - login of logged in user) - %u
Password to SMTP server ( "%p" - password of logged in user) - %p
Check IP address of client while giving authorization - NO

**Comment by mykljohn** [comment]
Hi, I changed the setting as suggested, but the when I go to My Mailbox, put in ventas@thegloboworld.com <mailto:ventas@thegloboworld.com>  and the password “Yeti2015” it says Login Failed.

**Comment by mariuszkrzaczkowski** [comment]
I tested the login on the settings above and is working properly.
I think somewhere else is the problem, check the server configuration.

**Comment by mykljohn** [comment]
Hi, can you give me a bit more detail of how, I have this configuration setup.  When I go to My Mailbox, it asks for username and password.  What username and password to I put in there?  Is there anything else that has to be configured?   cheers, Mykl

**Comment by mariuszkrzaczkowski** [comment]
![mailconfig](https://cloud.githubusercontent.com/assets/10198654/9459910/25e13fae-4b01-11e5-8a73-0720072f92ae.png)
![maillogin](https://cloud.githubusercontent.com/assets/10198654/9459909/25e077ea-4b01-11e5-8b83-b54aae549ef3.png)
![mailloged](https://cloud.githubusercontent.com/assets/10198654/9459911/25e2421e-4b01-11e5-8d72-3e8a0e03b198.png)

**Comment by mykljohn** [comment]
I've got the Mail Client Setup, and the Auto Login configured, but when I click on My Mailbox, it displays this login screen.

![image](https://cloud.githubusercontent.com/assets/11919990/9459879/267a9842-4ac6-11e5-9952-27ac6fd7092a.png)

What username and password do I use?  I've tried everything.  And I've found another problem, my email server blocks access after 3 wrong tries

**Comment by mykljohn** [comment]
This is the error in the log;

[25-Aug-2015 01:49:30 -0500]: <9cb725e7> IMAP Error: Login failed for ventas@thegloboworld.com from 177.232.50.242(X-Real-IP: 177.232.50.242). AUTHENTICATE PLAIN: Authentication failed. in /home1/globo/public_html/YetiForceCRM/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_imap.php on line 198 (POST /YetiForceCRM/modules/OSSMail/roundcube/?_task=login?_task=login&_action=login)


This is the code from RoundCube.  It looks right.

    public function connect($host, $user, $pass, $port=143, $use_ssl=null)
    {
        // check for OpenSSL support in PHP build
        if ($use_ssl && extension_loaded('openssl')) {
            $this->options['ssl_mode'] = $use_ssl == 'imaps' ? 'ssl' : $use_ssl;
        }
        else if ($use_ssl) {
            rcube::raise_error(array('code' => 403, 'type' => 'imap',
                'file' => __FILE__, 'line' => __LINE__,
                'message' => "OpenSSL not available"), true, false);

            $port = 143;    ************************  Shouldn't this be 993???? *******************************
        }

        $this->options['port'] = $port;

        if ($this->options['debug']) {
            $this->set_debug(true);

            $this->options['ident'] = array(
                'name'    => 'Roundcube',
                'version' => RCUBE_VERSION,
                'php'     => PHP_VERSION,
                'os'      => PHP_OS,
                'command' => $_SERVER['REQUEST_URI'],
            );
        }

        $attempt = 0;
        do {
            $data = $this->plugins->exec_hook('storage_connect',
                array_merge($this->options, array('host' => $host, 'user' => $user,
                    'attempt' => ++$attempt)));

            if (!empty($data['pass'])) {
                $pass = $data['pass'];
            }

            $this->conn->connect($data['host'], $data['user'], $pass, $data);
        } while(!$this->conn->connected() && $data['retry']);

        $config = array(
            'host'     => $data['host'],
            'user'     => $data['user'],
            'password' => $pass,
            'port'     => $port,
            'ssl'      => $use_ssl,
        );

        $this->options      = array_merge($this->options, $config);
        $this->connect_done = true;

        if ($this->conn->connected()) {
            // check for session identifier
            $session = null;
            if (preg_match('/\s+SESSIONID=([^=\s]+)/', $this->conn->result, $m)) {
                $session = $m[1];
            }

            // get namespace and delimiter
            $this->set_env();

            // trigger post-connect hook
            $this->plugins->exec_hook('storage_connected', array(
                'host' => $host, 'user' => $user, 'session' => $session
            ));

            return true;
        }
        // write error log
        else if ($this->conn->error) {
            if ($pass && $user) {
                $message = sprintf("Login failed for %s from %s. %s",
                    $user, rcube_utils::remote_ip(), $this->conn->error);

                rcube::raise_error(array('code' => 403, 'type' => 'imap',
                    'file' => __FILE__, 'line' => __LINE__,
                    'message' => $message), true, false);
            }
        }

        return false;
    }

**Comment by mariuszkrzaczkowski** [comment]
Check the server configuration
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=9&fieldid=65

**Comment by mykljohn** [comment]
The only difference is register_globals	Enabled which I can't enable in PHP5.4.  Should I switch PHP?

**Comment by bpabiszczak** [comment]
As you see, your problem requires some analysis on your server. At the moment we don't offer that kind of support for free [I'm closing the issue]. If you want some paid support you can send me an email. We checked everything we could check for free, unfortunately we cant entirely solve every problem for free, because we wouldn't have the time to develop the system.

**Comment by mykljohn** [comment]
I reinstalled the new release and no more errors :)  HURRAH!
