### ISSUE TITLE
Error on Cron Job - Import Contacts

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1807]
I'm getting the following error in my Cron Job

Fatal error: Class 'PerformancePrefs' not found in /home1/globo/public_html/YetiForceCRM/include/database/PearDatabase.php on line 62

my vtigercron.sh has:
          export USE_PHP=/opt/php54/bin/php
and is set to 775 permissions

My php.ini is set to:
max_input_time 3000
memory_limit  2000
error_reporting  Off
display_errors  Off
display_startup_errors  Off
log_errors  Off
ignore_repeated_errors  Off
ignore_repeated_source  Off

My Cron job is:
/bin/sh /home1/globo/public_html/YetiForceCRM/cron/vtigercron.sh &>/home1/globo/public_html/YetiForceCRM/cache/logs/cron.log

**Comment by bpabiszczak** [comment]
In what versions of the system does this error occur?

**Comment by mykljohn** [comment]
Hi, I’m on version 2.1 the latest version.

**Comment by mykljohn** [comment]
Is there any way to run the Contact import without waiting for the Cron job?  Also, with regard to the import.  I can't import the Company Assoiciated with a Contact.  Is there any way around this?  I'm thinking I'll need to import the Contact Company and store it in an unused field; import the Companies separately;  and then go into MySQL and do and UPDATE to Contacts Parent_id by matching the company names.  No other way?

**Comment by mykljohn** [comment]
Any help on this?

**Comment by mykljohn** [comment]
I noticed that in the Configuration settings, register_globals = Off, I tried to set it On, but then I got a 500 Error.  I found that register_globals was eliminated in php5.4.  Should I use a differnet version of PHP?  Is this what is causing htis error?  because it appears that PHP Fatal error:  Class 'PerformancePrefs' not found in /home1/globo/public_html/YetiForceCRM/include/database/PearDatabase.php on line 62 could be a Global?

Not sure.  But I need some help with this ASAP.  I can work around the import problems, but not the others.  cheers, Mykl

**Comment by mariuszkrzaczkowski** [comment]
You tested the latest version?
https://github.com/YetiForceCompany/YetiForceCRM/tree/master

**Comment by mykljohn** [comment]
I just installed it and I get a 500 Error and this error in the Logfile:

Fatal error:  Class 'SysDebug' not found in /home1/globo/public_html/YetiForceCRM/include/logging.php on line 22

**Comment by mykljohn** [comment]
I just tried the Update in the Configuration Screen, and I got this message:

Module does not contain default language (en_us).

**Comment by mykljohn** [comment]
I just did a clean install of the new release, and everything seems to be working.   HURRAH!!!

**Comment by mykljohn** [comment]
Oops, I spoke too soon.  Everything but the Cron Job.

I got the following error in the YetiForceCRMnew/cache/logs/cron.log

Fatal error: Class 'SysDebug' not found in /home1/globo/public_html/YetiForceCRMnew/include/logging.php on line 22

this is from my php.ini:

error_reporting  =  E_WARNING & ~E_PARSE & ~E_NOTICE
display_errors = Off
display_startup_errors = Off
log_errors = Off

**Comment by bpabiszczak** [comment]
YetiForce version?

**Comment by mykljohn** [comment]
The latest, I did a clean install from the link I was sent https://github.com/YetiForceCompany/YetiForceCRM/tree/master

everything seemed to work, until the Cron job.

**Comment by bpabiszczak** [comment]
I don't know what "the latest version" means. You have to provide us with the exact system version.

**Comment by mykljohn** [comment]
ver 2.2

**Comment by setras** [comment]
had the same error on a new ver. 2.1.0 installation.
It was fixed by Marius on August,11th - commit 816b7ef
Check the file 'cron/vtigercron.php' - it should include the line 'require_once('include/ConfigUtils.php');'
 @@ -14,6 +14,7 @@
 require_once 'config/config.php';
 require_once 'config/debug.php';
 require_once 'config/performance.php';
<b>require_once('include/ConfigUtils.php');</b>
 include_once 'vtlib/Vtiger/Cron.php';
 require_once('modules/Emails/mail.php');

**Comment by mariuszkrzaczkowski** [comment]
Tested on the 2.2.0 version and the error doesn't occur.

**Comment by mykljohn** [comment]
Yes, sorry, forgot to remove this...In the latest 2.2 there's no error.  looking good!!
