### ISSUE TITLE
VAT is not added and saved on invoices

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#1808]
In Yeti 2.1.0 the invoices do not save the VAT value.
See atttachment.

highly critical, because no invoices can be issues.

Tested on both localhost updated to 2.1.0 and on test.yetiforce.com
![yeti-vat](https://cloud.githubusercontent.com/assets/10504154/9300140/34fbf4fa-44c3-11e5-88a3-5d813fdfeb4e.png)

**Comment by vinzdrance** [comment]
+1

**Comment by doriandudzisz** [comment]
Change on drop down menu Groupe to Individual and add tax to products, temp solution

**Comment by MaciejStencel** [comment]
Fixed. You can test it here:
https://gitdeveloper.yetiforce.com
