### ISSUE TITLE
[bug]add pdf to Organization 

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1809]
I add a pdf template to organization:
![qq 20150817175456](https://cloud.githubusercontent.com/assets/12697896/9302501/9be11646-4509-11e5-9dca-9b68990cc387.png)
I get a error,but I can export the pdf at quotes:
![qq 20150817175606](https://cloud.githubusercontent.com/assets/12697896/9302473/5aaabc7c-4509-11e5-9da8-36355219bdfd.png)
at the organization details,it can display the pdf template:
![qq 20150817175625](https://cloud.githubusercontent.com/assets/12697896/9302474/5ab22e76-4509-11e5-8624-8ad80f88869c.png)
![qq 20150817175532](https://cloud.githubusercontent.com/assets/12697896/9302475/5ab54688-4509-11e5-9de6-558cde1d2d8c.png)

**Comment by paula-w** [comment]
The PDF module is being rebuilt from scratch.
