### ISSUE TITLE
services "mass edit"

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#1810]
yeti 2.1.0 the function "mass edit" for "services" do no work.

I can see that it works on test.yetiforce.com (I assume this is a clean installation), but for an upgraded instance from 2.0.0 to 2.1.0 nohtin happens after clicked "mass edit", for "services" only.

all other table views it works just fine. (invoice, sales orders etc).

**Comment by bpabiszczak** [comment]
Unfortunately, I didn't notice this error, it works properly in the test version, in the migrating version [I tested now on 2.1.39]. Even if it doesn't work on 2.1.0 then update to 2.1.39.
However, if you claim that the error still occurs, then you have to describe how to trigger it in the test version step by step. [PS. test.yetiforce.com version is an updated version, not a clean one!]
