### ISSUE TITLE
Kolejna aktualizacja , te same problemy 

### ISSUE THREAD

**Issue by doriandudzisz** [YetiForceCompany/YetiForceCRM#1811]
Witam, powiem tak nie wiem czemu u was jest tak ze kazda akualizacja zmusza mnie do ponownej zabawy z portalem klienta. Wykonane juz dobry pare raz z instruckja dane do logowanie do panelu generuje.. a zalogowac sie nie mogę dalej, moja dociekliwość doprowadziła mnie do takich wniosków iz biblkiotek nosoap ktora stosujecie do komunkacj porta <-> crm  jest z roku 2005 i stwarza problemy, a u tutaj zalecacie najnowsza wersje php.

Robicie swietną robote ale kazda firma nie moze sobie pozwalac na co miesiecza zabawe po aktualizacji system. A moje doswiadczenia takie sa co miesiac nowa wersja i od nowa ustawianie.... paranoja..

Nie mniej może ktoś pomoc mi z uruchomienie portalu instrukcje podane na stronie sa nie wystarczajace ;]

**Comment by bpabiszczak** [comment]
Tylko tyle, że ten post niewiele wnosi. Proszę nauczyć się używać debugowania: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/109-debugowanie.html. Tylko prawidłowo zgłoszone błędy, której jesteśmy wstanie odtworzyć możemy poprawić, to że ktoś pisze, że coś mu nie działa, niczego nie zmienia, bo nawet się tym nie zajmiemy, jeżeli zgłoszony błąd nie jest zgodny z tym opisem: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html.

Pomoc możemy udzielić, lecz jest ona odpłatna.

**Comment by doriandudzisz** [comment]
Takie gadanie to tylko wymówki, problem tkwi w komunikacji portalu do crm. ale jak widze plan biznesowy objoł tylko suppoirt dla programistów, szary człowiek ma tylko placic,

**Comment by bpabiszczak** [comment]
"Szary człowiek" musi się nauczyć, jak zgłaszać błędy i jak używać debugowania. Takie same zasady obowiązują wszystkich, którzy chcą od nas jakiegoś wsparcia. Nie widzę, abyś dodał jakiegokolwiek ticketa związanego z tym, że nie działa Tobie portal [nie licząc tego], a więc skoro przez kilka miesięcy nie działał Tobie portal i tego nie zgłosiłeś, to do kogo masz pretensje? 

Nie będziemy reagować na to, że ktoś pisze, że coś mu nie działa, póki nam nie udowodni, że to rzeczywiście nie działa.

**Comment by bpabiszczak** [comment]
Niestety nie podałeś wersji których dotyczy problem więc nie bardzo można Tobie pomóc, to co może Ci się przydać to zerknij na ostatnią naszą poprawkę związaną z portalem: https://github.com/YetiForceCompany/YetiForceCRM/pull/1819/commits może to u Ciebie zadziała. 

Portal zawsze można testować tutaj: https://test.yetiforce.com/portal/

**Comment by doriandudzisz** [comment]
jednak fix pomogł ale oczywiscie swoim, dzis z rana jeszcze wasz system zachowal sie tak samo jak moj, warto rozgraniczyc support dla devow zostawic na gitcie, ale dla szarych uzytkowników forum.
