### ISSUE TITLE
RSS, Our sites?? Maybe better social networing

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1815]
Is it really needed? Anyway I can not set rss for cnn.
What about social networing and come configurable connection to FB, Twitter?
It easy to connect module with FB and in this way automate some posting process....

**Comment by bpabiszczak** [comment]
I think both, RSS and Our Sites, should be removed from the system [if they come back they will be definitely changed].

As far as Social is concerned – it's another issue and it needs a broader approach. We are planning an implementation with the basic platforms within the next few months; I don't want to provide a specific date because I don't know it.

**Comment by bpabiszczak** [comment]
We do not remove modules. Maybe in the future.

**Comment by PercyP** [comment]
I too would be interesting in purchasing things like Twitter integration from your shop. Has this progressed any further?

Percy

**Comment by sol2014** [comment]
Is there a module designer within the system?

**Comment by PercyP** [comment]
Hi sol2014,

I didn't think there was but have just checked and yes, under Standard Modules, Modules Installation there is an option to create Modules which look cool.

**Comment by bpabiszczak** [comment]
:smile:

**Comment by sol2014** [comment]
Hello bpabiszczak, I sent you an email yesterday. Did you get a chance to read it?

**Comment by bpabiszczak** [comment]
Yes, but i dont speak english ;) @KatarzynaUlichnowska & @paula-w will talk with you.

**Comment by sol2014** [comment]
What language do you speak?

**Comment by bpabiszczak** [comment]
PL

**Comment by sol2014** [comment]
Is there an advanced workflow creator like this one -> https://shop.stefanwarnat.de/vtiger-workflow-designer/ and if not, would it work for Yetiforce CRM?

**Comment by sol2014** [comment]
Reason for me asking is that I wanted to create a workflow where once the ticket is set to a specific status such as 'Closed' then an invoice would automatically be generated for that ticket.

**Comment by bpabiszczak** [comment]
ONE QUESTION ONE ISSUE!~!!!!!

**Comment by sol2014** [comment]
LOL, alright, got it.
