### ISSUE TITLE
[Design improvement] Add relation button

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1817]
All widgets have **+** button for create new record, but in activities have **Add**

for better system consistency would be better if all the buttons will be the same ( **+** )

![design_add](https://cloud.githubusercontent.com/assets/4824588/9323171/f146d660-457d-11e5-92f1-1debf0b4ce92.PNG)

**Comment by konadrian** [comment]
14ac148bf95128dbe5254752afec0d6b74c32594 Changes see on https://gitdeveloper.yetiforce.com
