### ISSUE TITLE
[bug] Missing Select2 in PDF module

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1818]
Why in PDF module fields in **Variables of document** section doesn't have filtering via select2 ?
It will be easier to find and select specified value.

![bug_missing-select2](https://cloud.githubusercontent.com/assets/4824588/9323274/2c835734-457f-11e5-93c8-2073853325c5.PNG)

**Comment by paula-w** [comment]
The PDF module is being rebuilt from scratch.
