### ISSUE TITLE
[question] funtion of Convert lead mapping

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#1820]
What is the idea with converting leads to contacts -function, when it obviously is not working? Or have I not understood the clue.

![conv](https://cloud.githubusercontent.com/assets/10330264/9326841/78a35936-45a5-11e5-977e-d46781a31983.png)

**Comment by bpabiszczak** [comment]
As far as I remember, even though the conversion changed, we still use mapping while converting... So this tab has to stay as it is. There's going to be a new mechanism responsible for mapping fields between modules and conversion in the near future.
