### ISSUE TITLE
MassDelete Products

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1830]
I'm trying to delete the Products that I just imported to reset the ProductID.

But when it starts the delete process, it never returns.  And it doesn't appear to delete anything in MySQL

![image](https://cloud.githubusercontent.com/assets/11919990/9365831/5a4c3316-4679-11e5-8a56-358c26501d99.png)

**Comment by bpabiszczak** [comment]
duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1824
