### ISSUE TITLE
[BUG] Wrong "Name" value in quick create from roundcube 

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1834]
![bug_quickcreateroundcube](https://cloud.githubusercontent.com/assets/4824588/9368635/b2838f70-46c4-11e5-90e6-6d55eec17e4a.JPG)

System suggest:
```Subject: Trzy wskazówki na temat efektywniejszego korzystania z Gmaila		var tb_labels_for_message = [4];		```
but in my opinion it should be only:
```Trzy wskazówki na temat efektywniejszego korzystania z Gmaila```

**Comment by waw555** [comment]
![animation 133](https://cloud.githubusercontent.com/assets/1402355/9375030/808d384e-4715-11e5-9f8c-71c9faa3db3a.gif)
