### ISSUE TITLE
[IMPROVED DESIGN] Select Module in Add Widget

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1835]
![animation 131](https://cloud.githubusercontent.com/assets/1402355/9374730/2f362f9e-4712-11e5-9a6d-a7e69b3f351b.gif)

**Comment by konadrian** [comment]
You can see the changes here:  https://gitdeveloper.yetiforce.com/

**Comment by waw555** [comment]
And it is possible, vertically on the center post?
