### ISSUE TITLE
Chat not sending or displaying messages

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1836]
Hi, when I enter a chat message to a co-worker, it does not display in the text area and it doesn't send the message.  Is there any configuration or settings that have to be set to enable Chat?

**Comment by mykljohn** [comment]
Any help with this?

**Comment by florek41** [comment]
it's enabled by default, without additional configuration.
Have you tested at https://gitdeveloper.yetiforce.com ?

any javascript errors ?

https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by mykljohn** [comment]
It works on the demo site, no javascript errors.  In our site, nothing gets posted to the ChatList

In going through the Conguration Doc, I see that register_globals should  be ON, but register_globals was removed in php5.4 and if I set it On in my php.ini, I get a 500 Error.  Is this related?  Is this related to any of my other errors?  Should I switch to a different version of PHP?  

![image](https://cloud.githubusercontent.com/assets/11919990/9458917/1f293492-4aba-11e5-89d3-3ad65d0e178d.png)

**Comment by florek41** [comment]
What about javascript on yours server, any errors after submit ?

**Comment by mykljohn** [comment]
I hadn't thought to check the server error log, just YF.

There were these errors;

[Wed Aug 26 14:27:35 2015] [error] [client 201.163.212.218] File does not exist: /home1/xyz.com/medios/com_foxcontact, referer: http://xyz.com/contacto
[Wed Aug 26 14:27:35 2015] [error] [client 201.163.212.218] File does not exist: /home1/xyz.com/medios/com_foxcontact, referer: http://xyz/components/com_foxcontact/css/neon.css

There appears to be a path error here.

**Comment by florek41** [comment]
I mean JS errors on your server, not yetiforce test version.

Have you checked js console - is there something ?
on default server send requests every ~1s with empty response. When you send/recieve message you have something like this:

![chat_js](https://cloud.githubusercontent.com/assets/4824588/9505222/6eb960a8-4c41-11e5-9aee-abc396487fde.jpg)

it's very difficult to help you when it's something wrong only in your version and in other places it works like a charm. You need to check everything on your own or outsource it.

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by mykljohn** [comment]
How do I do the Update?  I tried through the configuration menu, and I got an error, No default Language.

**Comment by mykljohn** [comment]
Can we get direct support from you guys to help me through the initial install and elimination of these errors?  I sent an email to info@yetiforce.com, but I figured I'd post it here as well.

**Comment by mykljohn** [comment]
I installed the new release clean and everything works correctly.  HURAH!!!!
