### ISSUE TITLE
[IMPROVED] Select Item

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1840]
Please, to the record is deleted in the selection, as in the marketing process, and it is not convenient to choose, press a chance on something that is already selected
![animation 136](https://cloud.githubusercontent.com/assets/1402355/9375647/d10952a6-471c-11e5-85f5-b87ec54ead65.gif)

**Comment by bpabiszczak** [comment]
We use both types of fields. We do not plan to change that.
