### ISSUE TITLE
[IMPROVE] Sort alphabet

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1841]
If you choose to sort alphabetically, you can not go back to all the records
![animation 137](https://cloud.githubusercontent.com/assets/1402355/9375896/796e1bd2-471f-11e5-9010-4e81af8132ee.gif)

**Comment by bpabiszczak** [comment]
U can use X button.

**Comment by waw555** [comment]
I do not know, the button is in line with the search for why she should reset the parameters of the sort? I have checked the operation of this button and it works, but logically I would not have thought it, as it is in the search bar instead of the alphabet
