### ISSUE TITLE
[QUESTION] Creating ToDo/Event in Projects via Workflow

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1842]
I wonder how can I create related ToDo/ Event for ex. in projects via Workflow manager ?

In Opportunities it's clear and easy:
![q_calendar](https://cloud.githubusercontent.com/assets/4824588/9376630/27a9f58c-4710-11e5-858d-5f552fdfbb09.PNG)

but for projects I have only:
![q_calendar2](https://cloud.githubusercontent.com/assets/4824588/9376636/4efbd740-4710-11e5-8dd0-89171f16056f.PNG)

Can you help me with this ?

**Comment by eptapsyxos** [comment]
Create to do and event for custom modules plz! #1967
