### ISSUE TITLE
[QUESTION] How Document Control should works ?

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1843]
Can you give me example of usage Document Control ? How it should works ?

additionally - have you planned documentation about all modules and functions in YF ?

**Comment by bpabiszczak** [comment]
This module blocks saving if a given document is required in the specific stage/status [shows a special widget with an information about the required documents]. This module is relatively old, and needs refactoring. We'll start completing the documentation once we finish working on all the huge changes [so the whole 2016 year will be a good moment to complete the documentation]. Currently, we change the system quite quickly and it makes it hard to create documentation.
