### ISSUE TITLE
Timesheets remarks

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1844]
Noticed a few things in dev 2.1:

1. When I work on a ticket and save it, I get a suggested working time of 15 minutes PAST the time I clock out. Should that not be counting backwards? If I save I am done would be my logic.

2. Can the default time of 15 min be altered and where?

3. 
<img width="565" alt="screen shot 2015-08-20 at 21 22 04" src="https://cloud.githubusercontent.com/assets/10379403/9393377/d94ee4b6-4781-11e5-98f7-6cb454dfea99.png">
Here it shows 15 min working time but the total shows 0.25, seems something off there.

4. if I create a timesheet report, the total, average etc don't show.

5 After I worked some time , which shows in the order time, the total time still shows 0.00. Bug or related to other things I missed?
<img width="618" alt="screen shot 2015-08-20 at 21 27 56" src="https://cloud.githubusercontent.com/assets/10379403/9393512/a89039be-4782-11e5-9e68-758d277c23e7.png">

**Comment by bpabiszczak** [comment]
Check status in time record....
