### ISSUE TITLE
[IMPROVED] Currency Update

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#1847]
Dear developers!

Please add the Central Bank of Russia on the list of banks

Maybe these articles and links to help you do this
http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx
http://blog.reddikh.com/how-to-get-currency-rates-from-cbr-ru/
http://accessblog.net/2007/10/using-httpxml-to-get-data-from-web.html

**Comment by bpabiszczak** [comment]
We'll add this bank because you put a lot of effort into the YetiForce project.

**Comment by MaciejStencel** [comment]
waw555 this commit should be titled "From Poland with love" :) (

YF now has connection to Central Bank of Russia, and from there You can grab current currency conversion rates. 

Please test it if it works correctly for You.

**Comment by waw555** [comment]
Dziękujemy !!!

**Comment by nikdejan** [comment]
I almost tried to click Like button to this conversation :-)
