### ISSUE TITLE
The "Generate PDF" button doesn't work

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#1850]
When adding a button in PDF configuration, in the detail view of the record a nonfunctional button appears.
![pdf3](https://cloud.githubusercontent.com/assets/10221999/9465984/75aa7e8a-4b31-11e5-9dc8-f20f457361be.jpg)

**Comment by bpabiszczak** [comment]
This module is being rebuilt from scratch.
