### ISSUE TITLE
[Feature Idea] Search for birthdays

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#1852]
It would be great if there were a possibility to generate a condition for searching for birthdays, that is, for a date within a range, ignoring the year.

For example, I would like to find all contacts that have birthday (a custom field of type date) in the next 30 days. Currently this is not possible as the year of the birthday is always considered in the search. For example, as of today 08/26/2015, such a search should show a person having birthday on 09/06/1974, 09/06 being within a 30-day window going forward from 08/26.

Use case: I can send an e-mail or gift card or small present to all clients that have, for example, bought a product from me in the last year, when their birthday comes up to remind them of my business and hopefully generate future sales.

**Comment by diderich** [comment]
Just fount out that the feature exists, for Contacts and the field being named birhday (hard coded).
Ideally this would be generic, probably by having a specific uitype for birthdays.

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
