### ISSUE TITLE
Ticket/Help Desk questions

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#1853]
Ticket/Help Desk

A ticket is opened 
customer reply's to ticket notification email

I want that reply to go to the comments of the ticket.
If I reply to the ticket via "ticket comments" the related mod_comments module, I want an email sent with my comments.

If I reply to the comment from my email program, I want the comments to go to the "ticket comments" module and also emailed to the customer

Can I do this?

Also,
We have a support site already built with wordpress. Can I integrate the customer portal with wordpress.

How?
I want to create a section of my wordpress site for Tickets. Customer clicks a button to open a ticket.  The new ticket form comes up and is added to the CRM. I don't want to do it from a webform because I want the customer to be able to log in and see the ticket status etc.

**Comment by bpabiszczak** [comment]
The client's answer to an email is an email itself, so it will be attached to the ticket as an email. Vtiger does something strange that you described, which is creating a comment out of the email and attaching it, but it's illogical, and in my opinion the current functionality is much better...

If we want to enter a private comment that the client can't see, then we write the comment; if we want to write something that the client can see, then we write an email [which will be linked to that ticket]; it seems natural and simple.

In my opinion, it works better as it is, and you are trying hard to make it weird. 
One topic per one issue. Describe the second point in detail and add as a separate issue.
