### ISSUE TITLE
[translation improvement] Polish translation in Project Templates

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1855]
Po angielsku mamy:
1. "Add Project Milestone"
2. "Add Project Tasks"
3. "Add Project Milestone"
![translate_en](https://cloud.githubusercontent.com/assets/4824588/9514435/48498106-4c9a-11e5-8a50-7d0154f612de.jpg)

A po polsku:
1. "Etapy Projektów"
2. "Zadania Projektów"
3. "Etapy Projektów"
![translate_pl](https://cloud.githubusercontent.com/assets/4824588/9514436/4b6149f0-4c9a-11e5-9e61-939beb51acb1.jpg)

Wg, mnie powinno być:
1. "Dodaj etapy projektu"
2. "Dodaj zadania projektu"
3. "Dodaj zadanie projektu"

**Comment by bpabiszczak** [comment]
Raczej byłbym za tym, że po polsku jest dobrze a źle jest po angielsku. Sugeruje się tym, że mamy również tryb edycji szablonu [czyli nie zawsze ma sens Dodaj].

**Comment by florek41** [comment]
Przekonałeś mnie, zgadzam się z Tobą. 
Jednak przy punkcie 3. opis powinien zostać zmieniony, bo przycisk służy do dodawania etapu i obecnie opis nie jest jasny i jednoznaczny.
