### ISSUE TITLE
[Design bug] Cancel button in project templates

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1856]
same as #1854 but in "Add Project Tasks" section.
![design_proj_tmpl_cancel2](https://cloud.githubusercontent.com/assets/4824588/9515155/d1f95f34-4c9f-11e5-882a-203f402e6b0a.PNG)

**Comment by konadrian** [comment]
You can see the changes here:  https://gitdeveloper.yetiforce.com/
