### ISSUE TITLE
Problem when updating 2.0 to 2.1

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#1857]
I have two 2.0 installations on different servers, when running update package 2.0.0_to_2.1.0_v7 it gives "Invalid request - Response For Illegal Access". ?

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by kpaulaha** [comment]
Tryed to install update package through module manager, got the error: "Invalid request - Response For Illegal Access" on a blank page.
On same server upgrading 2.1.0 ->2.1.xxx  with no problems. 

Updated one 2.0 installation some time a go on same server with one of earlier packages than v7 with no problems.

**Comment by bpabiszczak** [comment]
It doesn't work like that, you have to learn how to use debugging; I sent you a link above, there you can find all the necessary information that will let you diagnose the problem [regardless if its YetiForce's fault or your server configuration's fault]

**Comment by kpaulaha** [comment]
Well, I will debug the installation on monday when back from this trip, I know how to work with debuggers. Just wondered if some one else had same problems.

**Comment by kpaulaha** [comment]
Okay, got it working, was depending on server conf.

**Comment by bpabiszczak** [comment]
Can we close?

**Comment by kpaulaha** [comment]
Jup, close. Someone had changed max_size on server to 10M and v7 was bigger.
