### ISSUE TITLE
Widoczność kalendarzy przez administratora po aktualizacji do 2.1

### ISSUE THREAD

**Issue by slawhodu** [YetiForceCompany/YetiForceCRM#1860]
Po update z wersji 2.0 do 2.1 nie widzę (jako administrator. Wcześniej było widoczne) kalendarzy innych użytkowników. Nie mogę się także dodać do listy osób do udostępnienia kalendarza na użytkowniku...

**Comment by bpabiszczak** [comment]
W aktualnej wersji [2.2 a konkretnie 2.1.228 które można uaktualnić [testowo] pobierając paczkę z tego miejsca https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.1.0_to_2.2.0/zip zostało to poprawione. 

Przetestuj wersje https://gitmaster.yetiforce.com/ aby mieć pewność, czy problem jest rozwiązany.

**Comment by slawhodu** [comment]
niestety dalej  jest problem.
Dodatkowo w czasie zapisu na koncie użytkownika gdy zmieniam osoby, które mają mieć dostęp do kalendarza wyskakuje błąd:
Database ERROR: SQLSTATE[21000]: Cardinality violation: 1222 The used SELECT statements have a different number of columns
(aktualizacja przeszła poprawnie)

**Comment by slawhodu** [comment]
Na Państwa demo jest to samo.

**Comment by bpabiszczak** [comment]
sprawdziłem tutaj: https://gitdeveloper.yetiforce.com i działa prawidłowo. Proszę opisać krok po kroku, jak zaobserwować/wywołać oba błędy które opisujesz.

**Comment by MaciejStencel** [comment]
Może Pan spróbować z tą poprawką czy błąd nadal występuje. Poprawiłem taki błąd w jednym miejscu które znalazłem z podanym przez Pana Cardinal Violation: 1222

https://github.com/YetiForceCompany/YetiForceCRM/commit/ffb2188c699c63051f732616c7d6128810ae877f

gitdeveloper.yetiforce.com został zaktualizowany i można tam przetestować również.

**Comment by slawhodu** [comment]
witam,
problem z błędem wydaje się naprawiony, ale dalej wybrani użytkownicy nie
widzą w kalendarzu kalendarzy podwładnych

W dniu 28 sierpnia 2015 16:51 użytkownik Maciej Stencel <
notifications@github.com> napisał:

**Comment by bpabiszczak** [comment]
Proszę opisać krok po kroku jak błąd ten wywołać na wersji https://gitdeveloper.yetiforce.com/
