### ISSUE TITLE
[bug] Bug when editing event field v.2.1.228

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#1864]
ok in Full edit view.
![calendar](https://cloud.githubusercontent.com/assets/10330264/9562092/4f13d384-4e6a-11e5-9353-d46b60e07cb6.png)

**Comment by konadrian** [comment]
I can't receive the notification about an incorrect end date, please provide some more information on how to trigger this error.
![calendar](https://cloud.githubusercontent.com/assets/3193498/9573236/22afddbe-4fba-11e5-8aae-75969b275131.gif)

**Comment by konadrian** [comment]
In Chrome, if the end date is earlier than the start date, after trying to save the editing window disappears and an error pops up 
jquery.validationEngine.js?s=1439813566:1757 Uncaught TypeError: Cannot read property 'left' of undefined
. Everything works well in Firefox.
