### ISSUE TITLE
[improvement] Possibility to add field to user

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#1865]
If you could add field to user, e.g. phone number, it could be used in quotes pdf-templates, etc.

**Comment by diderich** [comment]
I believe the more general question is whether or not Employee and User should be one module or not? And if not, what is the role of User versus Employee in the system?

**Comment by reeid** [comment]
I guess not every employee can be a user?

**Comment by bpabiszczak** [comment]
They should be 2 different modules.

The Users module will not be visible from the user's level [it will ultimately be available only in the admin's panel].

Any information relevant to the contact should be in the Employees module, and all the other modules should base on that.

The Users module will soon be rebuilt to get rid of all the useless information.
