### ISSUE TITLE
Related Modules.

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1868]
I'm trying to test everything, and I created a test Campaign, but when I try to add Leads, it does nothing.  I turned on debuggin, and this is the System.log 

Sun Aug 30 18:59:12 2015,146 [21770] INFO DB - DB ->Query: SELECT DISTINCT vtiger_crmentity.crmid,vtiger_account.accountname, vtiger_crmentity.smownerid, vtiger_account.email1, vtiger_account.phone, vtiger_account.website FROM  vtiger_account
				INNER JOIN vtiger_campaignaccountrel ON vtiger_campaignaccountrel.accountid = vtiger_account.accountid
				INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_account.accountid
				INNER JOIN vtiger_accountaddress ON vtiger_accountaddress.accountaddressid = vtiger_account.accountid
				LEFT JOIN vtiger_groups ON vtiger_groups.groupid=vtiger_crmentity.smownerid
				LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid=vtiger_users.id
				LEFT JOIN vtiger_accountscf ON vtiger_account.accountid = vtiger_accountscf.accountid
				LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignaccountrel.campaignrelstatusid
				WHERE vtiger_campaignaccountrel.campaignid = 2824 AND vtiger_crmentity.deleted=0  ORDER BY vtiger_account.accountname ASC LIMIT 20 , 1
Sun Aug 30 18:59:12 2015,156 [21770] INFO DB - DB ->Query: SELECT vtiger_field.columnname, vtiger_field.fieldname FROM vtiger_relatedlists_fields INNER JOIN vtiger_field ON vtiger_field.fieldid = vtiger_relatedlists_fields.fieldid WHERE vtiger_relatedlists_fields.relation_id = ? AND vtiger_field.presence IN (0,2);
Sun Aug 30 18:59:12 2015,156 [21770] INFO DB - DB ->Query parameters: [88]
Sun Aug 30 18:59:12 2015,157 [21770] DEBUG System - Entering isPermitted(Accounts,EditView,) method ...
Sun Aug 30 18:59:12 2015,158 [21770] DEBUG System - Entering getActionid(EditView) method ...
Sun Aug 30 18:59:12 2015,158 [21770] INFO System - get Actionid EditView
Sun Aug 30 18:59:12 2015,159 [21770] INFO System - action id selected is 1
Sun Aug 30 18:59:12 2015,159 [21770] DEBUG System - Exiting getActionid method ...
Sun Aug 30 18:59:12 2015,159 [21770] DEBUG System - Exiting isPermitted method ...
Sun Aug 30 18:59:12 2015,159 [21770] DEBUG System - Entering isPermitted(Accounts,Delete,) method ...
Sun Aug 30 18:59:12 2015,159 [21770] DEBUG System - Entering getActionid(Delete) method ...
Sun Aug 30 18:59:12 2015,159 [21770] INFO System - get Actionid Delete
Sun Aug 30 18:59:12 2015,160 [21770] INFO System - action id selected is 2
Sun Aug 30 18:59:12 2015,160 [21770] DEBUG System - Exiting getActionid method ...
Sun Aug 30 18:59:12 2015,160 [21770] DEBUG System - Exiting isPermitted method ...

**Comment by konadrian** [comment]
Can you recreate this error on https://gitdeveloper.yetiforce.com
