### ISSUE TITLE
Feedback: updating v2.2

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1874]
Just did two upgrades from 2.1 to 2.2 and had no real issues. Everything seems to work fine.
Only little thing is that we setup one master CRM that got version 2.1.16 (I believe) and the updater refused to update. Of course I set it back manually to 2.1.0 and all went fine.
It means that people that are coming to the site and download the CRM for the first time, will be in trouble  when they update for the first time.
Guess the Stable or Master version number should not be updated over 2.1.0 or the updater should accept the minor changes and not stop.

**Comment by bpabiszczak** [comment]
Currently downloading the system from our website redirects the user to sourceforge, where only the stable version will be available. We don't link the github version anywhere at the moment, so the new users shouldn't face the problem you described. Apart from all that, your example is described and solved in the article about updates. I wouldn't change anything as far as that is concerned, all the currently available solutions seem to be sufficient.
