### ISSUE TITLE
Remove "Calendar Shared Type" from User

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [YetiForceCompany/YetiForceCRM#1875]
Remove "Calendar Shared Type" from User

**Comment by SkavenKF** [comment]
Why you would remove this from user?

**Comment by bpabiszczak** [comment]
This functionality does not work and is not necessary.

**Comment by SkavenKF** [comment]
Ok, i see you can administrate this in yf in the user role :-)
You can remove this also from Event.
