### ISSUE TITLE
Migration from vTiger 6.3

### ISSUE THREAD

**Issue by agilisgmbh** [YetiForceCompany/YetiForceCRM#1888]
Hi Guys, how to migrate from vtiger 6.3 as it seems it only supports migration from 6.2...

**Comment by vovpff** [comment]
I try to migrate a lot of times from vt 6.2.0. and all times mirgation was failed. I found only oe solution: export from vt, preparing for import and import to yeti.

**Comment by paula-w** [comment]
At the moment we support migration from Vtiger 6.2. Migration from 6.3 will be available either in 2.5v or in 3.0v.

**Comment by agilisgmbh** [comment]
Please as soon as possible. We need to migrate from 6.3 too.
We cant export and import - too much...

**Comment by raphinology** [comment]
Hi There, I'm also considering a port from vt6.3. I'm curious however, any eta on when 2.5 or 3.0 will be available?
