### ISSUE TITLE
[enhancement] Product list : Search in others product fields, like description, part number...

### ISSUE THREAD

**Issue by vtechnik** [YetiForceCompany/YetiForceCRM#189]
Product list : Search in others product fields, like product description, product category, sub category, vendor number, part number, vendor or any other(s) field(s) that you have configured, without opening the popup.
![quote](https://cloud.githubusercontent.com/assets/9847894/6019578/63768b2a-aba2-11e4-8dff-688ea708a639.jpg)

**Comment by bpabiszczak** [comment]
This functionality exists here: https://opensaas.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=2&fieldid=56

**Comment by vtechnik** [comment]
Thank for the link, 
but I can't enter (no password and login to enter)...
I can't see.

**Comment by bpabiszczak** [comment]
Check this: https://test.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=2&fieldid=56

**Comment by vtechnik** [comment]
This functionality doesn't work there :

an example 
create a product:

name :  Article one
part number : 123456789
description : this is my article description...

Goto to a new quote (or edit one), sell order, invoice...
Add a product.
When you type in the article line
arti or 345 or desc
it will have to display on the list (see the image above)  : Article one 

The search is made not only on product name.

I hope I was clear
(Thanks for your work)

**Comment by bpabiszczak** [comment]
It works very well. Search in "quotes" a product name: 234

**Comment by vtechnik** [comment]
Yes it works... I don't know, why it doesn't work before. 
I must have done something false. Sorry.
