### ISSUE TITLE
CurrencyUpdate error

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [YetiForceCompany/YetiForceCRM#1891]
![cur](https://cloud.githubusercontent.com/assets/10198654/9606659/fddce048-50c4-11e5-84d3-10498400ef54.png)

**Comment by MaciejStencel** [comment]
Jak wygenerować błąd?

Teoretycznie próbuje dodać zduplikowany wpis do tabeli, nie mogę go odtworzyć u siebie.

Występuje na gitdeveloper?
