### ISSUE TITLE
Does sourceforge is worth to mess with?

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1899]
YF stick to both GH and SF. Why?

**Comment by bpabiszczak** [comment]
1. We were on SourceForge before GitHub.
2. GitHub has this one disadvantage – we don't know who, when, and how many times downloaded our system. We can see all that on SourceForge.
3. SourceForge's advantage is its positioning and we are on the other CRMs lists, which makes us more popular
4. Generally SourceForge is bad, but we are there for the marketing reasons.
