### ISSUE TITLE
Common definition of lists

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#19]
Lists are used throughout YetiForce (module lists, lists in tab, lists in pop-up selectors, lists in module widgets, lists in reports). Ideally there should be 1) one place to manage lists and 2) another place where those lists can be associated with the individual usages. For example, I define a "project list" containing a given number of fields. Now I want to use that list when visualizing projects associated with a company (through the tab) and use the same list when associating a project to a contact. But in the summary view widget, when displaying a company, I would like to use a different list to visualize projects.
Such a list should have the following characteristics:
Be associated with one or more modules, e.g., Organization and Services
Contain an ordered lists of fields, e.g., Organization Name, Web address, Service Name, Service Type
Contain a sequence of fields applied for sorting the list by default, e.g. Organization Name, Service Type
Contain grouping clauses that would allow display lists using a hierarchy as shown below, e.g. Organization Name
Optionally, contain an exclusion / inclusion constraint, e.g., only include active services.
+---
+ Organization A
+---
+ Web address A | Service Name A | Service Type A
+ Web address A | Service Name D | Service Type A
+ Web address A | Service Name B | Service Type B
+ Web address A | Service Name C | Service Type C
+---
+ Organization B
+---
+ Web address B | Service Name F | Service Type B
+ Web address B | Service Name G | Service Type B
+---

**Comment by bpabiszczak** [comment]
We haven't received enough information about this issue, that's why we are closing it. If the problem appears in the future, please send us more detailed descriptions.
