### ISSUE TITLE
[Question] timesheets

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1900]
Hi Blazej, I am probably not understanding the concepts but I have trying to make the whole timemanagement work for me. Need some help there.

Simple setting: client has a maintenance contract, lets say for 5 hours. Its in the system.

Client adds a ticket through the portal (or email) I work on the ticket, record the time and at the end of the period I want to show / print / mail an overview of the hours worked / left on the contract.

In the tickets there is a time recorder, when saving the popup seems to be another one.
I can't see how those all work together. Can you shed some light on the 'official' workflow there?
Should I use both time recorders?

**Comment by paula-w** [comment]
Could you please describe how to trigger the error in the test version and add some screenshots/ record your screen?
