### ISSUE TITLE
Eliminate Steps in Sales Process

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1905]
I am looking at the sales process I have some questions.  Can we disable the required steps needs to complete a sales? 
 
We have some clients the will walk in and enroll, no quote issued.  So basically we would enter their contact info, and then a Sales Order.
 
Is this possible?  Or do we need to modify the system to do this?

**Comment by bpabiszczak** [comment]
You can turn off unnecessary fields:
1. https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&block=2&fieldid=33
2. https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9
