### ISSUE TITLE
Activating comments for Assets module

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1912]
Anybody can help me to activate comments for assets module?

**Comment by vovpff** [comment]
Maybe more comfortable to made possibility to switch on/off comnents to different modules. This can be useful in future!

**Comment by vovpff** [comment]
Maybe more comfortable to made possibility to switch on/off comnents to different modules. This can be useful in future!

**Comment by rskrzypczak** [comment]
At the moment it's not possible to add comments from the CRM to a module.

**Comment by vovpff** [comment]
What about this feature now?
