### ISSUE TITLE
Campaigns - Adding From - To Dates and times

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1915]
We've adapted the Campaign Module to function as a Class Schedule.  I've added the Start Date, Days Scheduled, and the Time Scheduled.   I would like to connect this to the Calendar, can you guys point me in the right directions, or talk to me about doing it for us.  cheers, Mykl

**Comment by paula-w** [comment]
Instead of the Campaign Module you should use the Projects Module for this.

**Comment by mykljohn** [comment]
Thank you Paula, Worked perfectly.
