### ISSUE TITLE
Question before investigation

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1918]
Hi, got custom module (migration from 1.16 to 2.2) what returning following:
Error!!!
DateTime::__construct(): Failed to parse time string (2015-09-07 2015-09-07 13:27:42) at position 11 (2): Double date specification\

Anybody met similar?

**Comment by bpabiszczak** [comment]
Unfortunately you didn't tell us much and we don't know how to help. First of all – read this:  https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html 

We need to know in which version exactly your error occurs [it's a long way from 1.16 to 2.2], and where it occurs [attach a short clip or a screenshot]. What can you find in the logs [whether or not any errors appeared in the log files]?
