### ISSUE TITLE
Manual for OSSPdf

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1920]
Are there manual or any documentation for OSSPdf available? Only pdf exporting stopped me to complete complete changing from vt to yetiforce.

My problem is customisation of products tables for PO, SO and INV.

**Comment by bpabiszczak** [comment]
The PDF module is currently being rebuilt from scratch, it'll be ready in 2 -3 weeks. We'll create the documentation together with releasing the new version. We don't have any documentation for the current OSSPDF version.
