### ISSUE TITLE
[Bug] Mail -> HelpDesk ticket - debug info in title

### ISSUE THREAD

**Issue by MaciejStencel** [YetiForceCompany/YetiForceCRM#1921]
When creating helpdesk ticket from email at the end of ticket title system appends debug informations.

 
![creating_ticket_from_mail](https://cloud.githubusercontent.com/assets/10218610/9730551/95f81256-5617-11e5-8a47-68688694bc9e.jpg)

Recreated on gitdeveloper.

**Comment by florek41** [comment]
this is the same as #1834
