### ISSUE TITLE
[Bug] Pagination in workflow settings is not updated when filtering

### ISSUE THREAD

**Issue by MaciejStencel** [YetiForceCompany/YetiForceCRM#1922]
When filtering workflow list by module, pagination is not updated:

![image](https://cloud.githubusercontent.com/assets/10218610/9731124/5679d3a4-561b-11e5-8a1a-3819103c7d94.png)

Only 3 workflows in contacts, pagination still shows 41 workflows.

**Comment by vovpff** [comment]
The same situation with pagination for Find Duplicates feature.
