### ISSUE TITLE
[Request] placeholders in email templates

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1923]
Would be nice to update the standard workflow emails like the one used for tickets, to set the support email as a variable instead of help@yetiforce. After every update I need to adjust all the templates and set our own helpdesk email address in there.
<img width="1375" alt="screen shot 2015-09-08 at 12 36 41" src="https://cloud.githubusercontent.com/assets/10379403/9732715/4a083bf0-5626-11e5-98fb-9a142085ef56.png">

**Comment by zebrahosting** [comment]
Just to add: I know the sentence is in the language files, but I hope you can change the email to the one given in de admin instead of a static one.

**Comment by bpabiszczak** [comment]
All the templates and workflows will be removed from the system and will be available by way of import/export, so the problem of overwriting will be solved.
