### ISSUE TITLE
[BUG] Recycle bin not working properly

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1924]
When you go to recycle bin module to empty bin or to recover deleted records this module works not so correct.
![image](https://cloud.githubusercontent.com/assets/8545791/9735112/09163794-5641-11e5-8402-aed38854932e.png)
There is Action and Empty Recycle Bin buttons works properly but if you change module to easily find deleted record there is appears error message:
![image](https://cloud.githubusercontent.com/assets/8545791/9735145/50d3bbba-5641-11e5-93aa-ac540629fc6b.png)
And GUI became crashed

**Comment by konadrian** [comment]
A fix that should solve the error.
You can see the changes here:  https://gitdeveloper.yetiforce.com/
