### ISSUE TITLE
[Request] Multi tree

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1925]
Is it possible to made by Yetiforce crew "multi tree" like "Multi-select Combo Box" picklist. Main idea to select several branches of tree in one field.

![image](https://cloud.githubusercontent.com/assets/8545791/9735292/678b15aa-5642-11e5-8c7c-bf2d8eb963b8.png)

**Comment by bpabiszczak** [comment]
There are no plans to add such functionality.
