### ISSUE TITLE
[BUG] Timesheet reports, filters not working

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1926]
Creating a report from Time sheets seems not to work
Setting a condition to filter does not pickup fields. EG choose an organisation would normally show a selection but not in this version.
Even adding a simple check with 'contains' and then a part of a name does not show any record.

**Comment by konadrian** [comment]
Could you attach a screenshot, a link or a video that shows where that error occurs, or/and describe step by step how to recreate it?

**Comment by zebrahosting** [comment]
Yes I will do this but cray busy this week, will try next week. Sorry for the delay.
