### ISSUE TITLE
New layout

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1927]
New layout looks good and fast. Takes a bit of getting used to but I think it is an improvement. 
Will it be part of GA 2.3?

**Comment by bpabiszczak** [comment]
which layout? This: https://layout.yetiforce.com/ [admin/admin]

**Comment by zebrahosting** [comment]
Yup installed it here locally to test and play.

**Comment by bpabiszczak** [comment]
1. We create a good bootstrap template [2.3 / 2.4]
2. We make good its own template [as an additional] [2.5 / 3.0]
