### ISSUE TITLE
To allow access to Picklist and Workflows from within the module

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1928]
This functions has been removed but they actually quite helpful - especially when we developing application (what sometimes last forever).

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by reeid** [comment]
I better leave decision to you whether is it bug or deliberate design. As I am not sure I will not raise "bug" ticket to not mess up. This issue simply make daily operations easier so I guess this should be threaten as enhancement  (even that functions was removed for some reason)

**Comment by florek41** [comment]
It's about button with list of link for edit fields/workflow/picklists on the list/edit view ?
I totally agree with reeid. Now we have to looking for this functions in admin panel - earlier it was easier to access.

**Comment by bpabiszczak** [comment]
A user won't be an admin, and an admin wont be a user. The admin's panel will be separated and they won't have anything to do with each other. We understand that the current form might be convenient for many people, yet for the safety reasons these mechanisms can't be merged.
