### ISSUE TITLE
[Bug] issue with sending qoute via email 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#1931]
Hi, tested version 2.2 on test.yetiforce.com.
Created qoutation I tried to send via eamil and got server error. 
It seems that email client do not have access to contact databased... 
1. step
![image](https://cloud.githubusercontent.com/assets/11491482/9760949/c3bf2f2a-56f9-11e5-924a-708c4264688a.png)

2. error
![image](https://cloud.githubusercontent.com/assets/11491482/9761049/73510454-56fa-11e5-83b5-408401cb7eae.png)

**Comment by bpabiszczak** [comment]
The error you see in the screenshot is not related to sending quotes via email, it appears sometimes when RoundCube can't establish a connection. It happens to me a couple of times everyday when I'm trying to send an email. When it appears I click "Send" once again and it works [the problem is somewhere in roundcube]. Does it happen every time ?

**Comment by witer30** [comment]
This I got when trying your DEMO. I got this error all the time when tried to send quote via email mentioned above. Thought that there is issue with non-existing email address of the contact which should received this quote but not. everything seems to be ok and error occurred every time I trying to send quote. Also it occurred when trying to  specify email address manually by clicking both contacts and accounts buttons...

**Comment by witer30** [comment]
any info regarding this issue..?

**Comment by mariuszkrzaczkowski** [comment]
![PDF](https://cloud.githubusercontent.com/assets/10198654/10426064/31efc066-70dd-11e5-8918-29150047a794.gif)

**Comment by mariuszkrzaczkowski** [comment]
Tested on the latest version and the error doesn't occur.

**Comment by witer30** [comment]
Perfect, thanks a lot...
but have one think which has to highlight that on version 2.2.304 template button is not active?

![image](https://cloud.githubusercontent.com/assets/11491482/10435932/759b06e0-7123-11e5-8fc6-644a2285bdbc.png)

**Comment by bpabiszczak** [comment]
New question new issue...

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2016
