### ISSUE TITLE
[BUG] SO address buttons

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1935]
In addresses section buttons for copying addresses from account or Primary/Delivery address in not working correct. Contact button is working perfect.

**Comment by vovpff** [comment]
![image](https://cloud.githubusercontent.com/assets/8545791/9791065/f4199a3c-57e1-11e5-8da8-95aa37b665e3.png)

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by vovpff** [comment]
This is demonstration of bug at test.yetiforce.com
![so address bug](https://cloud.githubusercontent.com/assets/8545791/9903117/307119e4-5c7c-11e5-8f8d-95d675c00ea6.gif)

**Comment by MaciejStencel** [comment]
This bug was fixed. Please test it on gitdeveloper.yetiforce.com
