### ISSUE TITLE
[BUG] 1:M field

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#1936]
I created additional 1:M fields in SO and INV modules to set contact name. After that there appears some bugs:
1) Duplicated related modules tab in contacts
![image](https://cloud.githubusercontent.com/assets/8545791/9790666/0189c964-57e0-11e5-9b5a-94164681c9d0.png)
How to remove duplicates?
2) This tabs not contain any records where this contact added to field.
![image](https://cloud.githubusercontent.com/assets/8545791/9790723/43f43afa-57e0-11e5-877f-2d63da9a297e.png)
How to establish relation between SO and Contacts (Invoice an contacts) module?
3) How to establish relation of contact name field when Invoice creates from Sales order? Now i'm must two times select the same contact when I create new Sales order record and after that new Invoice from Sales Order.

**Comment by vovpff** [comment]
In original vtiger when you choose accout and after than you click to contact name magifier button there is appears pop-up window with contacts what related to this account. Now clicking to magnifier button calls pop-up window with all contacts.

**Comment by paula-w** [comment]
1. A 1:M relation creates a related module automatically, you can disable it manually in the configuration. However, you should remember that there already is an M:M relation in these documents, so the 1:M relation should not appear there. 
2. One thread means one issue. Whether or not the list of all the contacts, or just the list of contacts  related to that record shows up, depends on what the variable says. If you think it should work in a different way than it currently works, then open a new issue.
