### ISSUE TITLE
Add fields to Item details block (List view) in quote window

### ISSUE THREAD

**Issue by wildfox81** [YetiForceCompany/YetiForceCRM#1938]
I added some fields (text and pick-list fields) in the Product and Service modules. 

In the Quote/sales order/invoice window there is block 'Item detail' where I select the product and the service to be quoted. I tried to call these added fields in the list view block but I failed. How could I pass parameters from the product/service search popup (exist in the block) to the caller window (Quote/sales order/invoice).

I appreciate ur help.

Thanks on advance

**Comment by vovpff** [comment]
+1

**Comment by paula-w** [comment]
You can't do that, it requires some programming work.

**Comment by vovpff** [comment]
@paula-w I don't have enought experience for proramming this...
