### ISSUE TITLE
[Advice]one user can only login in at one computer

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#1940]
YetiForceCompany now can login in at many computers by the same user at same time.Maybe add a setting option when need to login in only at one site.

**Comment by florek41** [comment]
In my opinion It should logout you from other session or notify about that you have other session.
But ONLY when admin want it.

**Comment by 1250572980** [comment]
yes,it is right.because if you login in at two computers,maybe some one take some error at one which it   is not by admin.

**Comment by bpabiszczak** [comment]
What do you need this for? To increase the security or maybe for some other reason?

**Comment by bpabiszczak** [comment]
There are no plans to add such functionality. Why? We have added this functionality https://gitdeveloper.yetiforce.com/index.php?module=Users&view=SwitchUsers&parent=Settings&block=4&fieldid=94
