### ISSUE TITLE
Ticket responses

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#1942]
How to handle tickets responses.

What is the proper way to setup workflow for tickets?

I am unable to get comments from the ticket module to send to the customer. 

I want the customer to be able to respond to the ticket comments.

**Comment by vovpff** [comment]
![image](https://cloud.githubusercontent.com/assets/8545791/9868739/2a217c02-5b85-11e5-81a4-cfb92ecaa95e.png)
the first let's try to activate all workflows what assigned to comments module.

**Comment by amicheals** [comment]
I am using the test server. I did activate workflows. Opened a ticket but did not receive the notification email that a ticket was created.

**Comment by vovpff** [comment]
sorry @amicheals I never used ticket in my system and can't advice something

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/user-documentation/support-process/140-automation-of-notifications-in-tickets.html
