### ISSUE TITLE
Question: How does mail/newsletter campaigns work

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#1947]
What is the method to send newsletters.

I create a campaign
Add targets (leads, accounts, vendors, etc)

Create an email template

Then what?
How do I send the emails.

I notice a setting in calendar where it asks for the campaign. Does that send the emails to the targets?

**Comment by reeid** [comment]
As CRM is a core of yetiforce, managing email campaigns i professional way would be an advantage. There is company called Its4You who do for vtiger EmailMaker. I wish I could see it here. Don't mean as a free extension, willing to pay for that some reasonable amount., and I believe it will be more interested soon.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1478
