### ISSUE TITLE
[Question] Mailscanner/Exceptions - how does it work

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#1952]
Hi,
please can you provide me an explanation/example on how the Mailscanner/Exceptions setting works? 
I tried to enter a mail address but it had no effect.

/Stefan

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/administrator-documentation/panel/mailbox/mail-scanner/135-mail-scanner.html

**Comment by setras** [comment]
sorry, but this article does not mention or explains how to use the exceptions feature

**Comment by bpabiszczak** [comment]
This tab is used for creating mails that the mailscanner should omit [not create messages downloaded via imap or not create a ticket]. In the new version these fields will be divided into smaller elements [from, to, cc, bcc]. You can enter email addresses there as well as domains in the form of @domain.xyz
