### ISSUE TITLE
Add new layout to test server

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1953]
1. Stable
2. GitMaster
3. GitDeveloper
4. GitDeveloper - new layout

**Comment by bpabiszczak** [comment]
4. https://layout.yetiforce.com/
5. https://pdf.yetiforce.com/

**Comment by vovpff** [comment]
@bpabiszczak What is  a login-password to test?

**Comment by waw555** [comment]
L:admin
P: admin
