### ISSUE TITLE
View Pdf in web browser instead of download

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#1957]
Hello,

When a pdf is generated or viewing from the documents module, is there a way we can view the pdf/file via browser instead of the file being downloaded to the computer?

**Comment by reeid** [comment]
configure browser?

**Comment by vovpff** [comment]
This issue looks like feature request for function by link above http://www.vtexperts.com/product/vtiger-document-preview/. @amicheals you mean something like this?

**Comment by amicheals** [comment]
Yes. That way I don't have to download the file to my computer. @vovpff

**Comment by witer30** [comment]
this would be nice to have in YF

**Comment by florek41** [comment]
I agree about that will be useful. It will be great to preview all types of files(document module) (doc, jpg, xls etc.) without downloading.
@vovpff this vtiger extension is crap in my opinion - it allow for access to your files (form documents module) form http - so everybody who know filename can access to it without login - this is not secure way.

**Comment by witer30** [comment]
agree, this will increase efficiency and productivity

**Comment by bpabiszczak** [comment]
At the moment we are not planning to add a functionality like this. I'd like to remind you that a new PDF module is being built, if somebody wants he can add this functionality there [we suggest contacting us about it].
