### ISSUE TITLE
To allow creating subprojects & subtasks

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1958]
to allow create subprojects and/or unlimited subtasks.
Current logic is not enough in many scenarios. Extending this functionality will allow to create application for more advanced end users (hospitals, labs, technical departments, automotive industry)
I believe use case don't need to be mentioned.....

**Comment by eptapsyxos** [comment]
+1

**Comment by vovpff** [comment]
+1

**Comment by bpabiszczak** [comment]
You can currently create a subtask...[?!?]. Before we start expanding the projects module, we should organize it first, and that's our priority as far as changes in this module are concerned. Of course, if someone has a ready expansion for the module we are open to changes.
