### ISSUE TITLE
Webservice on v. 2.2 not working

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#1960]
I can't work with webservices form YF 2.2 version. I have enabled webservices in api.php config. I'm getting 500 Error code when trying get http://host/webservice.php. How can I work with webservices on YF 2.2?

Fatal error: Call to a member function pquery() on a non-object in /public_html/include/Webservices/OperationManager.php on line 74

**Comment by mariuszkrzaczkowski** [comment]
Tested on the latest version and the error doesn't occur.
https://github.com/YetiForceCompany/YetiForceCRM/commits/developer

**Comment by wbnx** [comment]
PearDatabase::getInstance() fixes issue. It's not clean YF version so probably real error is somewhere else. Why you passing $adb in this function as method parameter?

**Comment by kabelo38** [comment]
This error seems to be re-introduced again 

it is related to this  issue https://github.com/YetiForceCompany/YetiForceCRM/issues/2282

![webservice error](https://cloud.githubusercontent.com/assets/5912376/18703951/52b7a712-7fe8-11e6-84de-b88d80976f7b.png)

**Comment by mariuszkrzaczkowski** [comment]
This is not a bug it does not work because it does not have a parameter.
 "Unknown operation requested"
Try this: http://gitdeveloper.yetiforce.com/webservice.php?operation=getchallenge

**Comment by kabelo38** [comment]
Fantastic just tested it again its working Thanks alot.
