### ISSUE TITLE
contact in Opportunities > Quotes > Sales Order

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#1961]
When I have a Contact in Opportinity and make of that a Quote, the contat is not tranferred, but when I make a Sales Order from a Quote with a Contact it is tranferring. Should it not work so the whole chain?

![opportunities](https://cloud.githubusercontent.com/assets/10330264/10021651/a78b3616-6151-11e5-88ba-6cbf59215a78.png)
![quotes](https://cloud.githubusercontent.com/assets/10330264/10021656/b2c143c2-6151-11e5-8437-96f318bc7663.png)
![sales order](https://cloud.githubusercontent.com/assets/10330264/10021666/bd397950-6151-11e5-8a9a-2d14792acab8.png)

**Comment by SkavenKF** [comment]
The same for me.
Testet with:
* https://gitdeveloper.yetiforce.com
* https://gitmaster.yetiforce.com/index.php

I have create a custom field "contact" (releated field 1:m) in the relevant modules, but it has not transfered.

**Comment by witer30** [comment]
+1

**Comment by bpabiszczak** [comment]
There are 3 data autofill types in the system:

1. Generating from record A to record B [eg. Quote > Order] – field mapping is determined by the code.
2. In edition/creating while selecting the uitype10 field [fields with a plus]. Automatic mapping is realized by encoded mechanisms in the file :  modules\Vtiger\models\Module.php: getMappingRelatedField().
3. In quick create, based on given parameters [the address has to properly constructed].

It doesn't work always and everywhere, as you can see above, it has to be configured and set.
