### ISSUE TITLE
[PL] dodanie rekordu przez webservice 2.2

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#1962]
Nie da się dodać rekordu przez webservice (Invoice). Permission to perform the operation is denied. W wersji 2.0.0 nie było problemu.
Logowanie jest ok. Config api.php odblokowany. Gdzieś trzeba jeszcze coś skonfigurować/włączyć?

**Comment by bpabiszczak** [comment]
Szczerze mówiąc, to nie używamy webservice, zastępujemy go REST API... Proszę o załączenie gotowego kodu do wykonania przez webservice to sprawdzimy problem.
