### ISSUE TITLE
invoice - summary view, picklist changes , zero invoice amount

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#1963]
There is a bug in invoice module.

If an invoice status value is changed from picklist in summary view, then invoice total is changed to zero.
You then have to go to edit invoice and do a change eg. click on Tax value (bottom of invoice) and save. Then correct invoice calcuation is made.
After saving invoice numbers are stored correct.
But if you change "status" from summary view, then total is set to 0,- again.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/14ce0d8bedf9bc5d0f4598f2369b8ae265965c93
