### ISSUE TITLE
error cron 

### ISSUE THREAD

**Issue by negodiy** [YetiForceCompany/YetiForceCRM#1964]
good afternoon!
when the scheduler crowns the following error:
[25-Sep-2015 15:03:16 Europe/Moscow] PHP Parse error: syntax error, unexpected '[' in /home/turistpr/domains/site.ru/public_html/crm/config/debug.php on line 4
php Version 5.5
the server is configured in accordance with the recommendations
![server](https://cloud.githubusercontent.com/assets/14295261/10099923/ce925d24-6396-11e5-8131-df67a187a119.png)

**Comment by mariuszkrzaczkowski** [comment]
The error occurs most likely because cron uses a different PHP version than apache
Set the correct path to PHP in the cron/vtigercron.sh file (export USE_PHP=php)

**Comment by negodiy** [comment]
work! 
hosting: sprinthost.ru

vtigercron.sh 
#*********************************************************************************
# The contents of this file are subject to the vtiger CRM Public License Version 1.0
# ("License"); You may not use this file except in compliance with the License
# The Original Code is:  vtiger CRM Open Source
# The Initial Developer of the Original Code is vtiger.
# Portions created by vtiger are Copyright (C) vtiger.
# All Rights Reserved.
#
# ********************************************************************************
#!usr/local/bin/bash
export VTIGERCRM_ROOTDIR=`dirname "$0"`/..
export USE_PHP=/usr/local/bin/php55
cd $VTIGERCRM_ROOTDIR
# TO RUN ALL CORN JOBS
$USE_PHP -f cron/vtigercron.php
