### ISSUE TITLE
[Question] Update related record via workflow ?

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1965]
Is it possible to update related field in related record (different or same module) ?
Ex. i want to change Sales Stage in Opportunities when Order status were changed.

 Can I do it by workflow or only by code ? Any tips ?

**Comment by reeid** [comment]
For now on custom function only, but in vtiger there is extension what do that. It could be deployed here too. Very useful thing

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/engine/170-types-of-event-handlers.html

**Comment by nikdejan** [comment]
+1

**Comment by berwerle** [comment]
Can u show me, how u implement a custom function for workflows?
