### ISSUE TITLE
Invoice Tax Mode need to select as Individual

### ISSUE THREAD

**Issue by krzychab** [YetiForceCompany/YetiForceCRM#1966]
Invoice Tax Mode need to select as Individual ?!

**Comment by paula-w** [comment]
Can you please specify your question a little?

**Comment by krzychab** [comment]
I thought :
 tax mode "Individual" as default .
I did not have to change every time.

**Comment by bpabiszczak** [comment]
This has been changed for a new type modules with products that can be tested on version gitdeveloper.

**Comment by florek41** [comment]
In which modules we can test it and how it should works ?
I've change settings Tax Config in https://gitdeveloper.yetiforce.com/index.php?module=Inventory&parent=Settings&view=TaxConfiguration&block=11&fieldid=92 and select my tax in product - I don't see any changes ex. in Purchase orders.

**Comment by bpabiszczak** [comment]
Please create new module [type: Extended module].

**Comment by bpabiszczak** [comment]
It is important to order what you set here. https://gitdeveloper.yetiforce.com/index.php?module=Inventory&parent=Settings&view=TaxConfiguration&block=11&fieldid=92

**Comment by florek41** [comment]
I've made quick look into this and it looks veeery promised - can't wait for instructions !

**Comment by krzychab** [comment]
How does it work ? 
---
Pozdrawiam 

Krzysztof Gajewski 

601918370 

     NIP: 946-000-51-56 

http://ab.net.pl 

W dniu 2015-10-07 07:10, Bartek Florczak napisał(a): 

> I've made quick look into this and it looks veeery promised - can't wait for instructions ! 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1966#issuecomment-146078760

**Comment by doriandudzisz** [comment]
i set one item vat... and i constant have group tax and idividual tax ;/

**Comment by bpabiszczak** [comment]
Wszyscy tu piszący są polakami, więc napisze w ojczystym języku, będzie szybciej. 

Mam wrażenie, że mylisz dwie różne funkcjonalności, czy podatek jest grupowy czy indywidualny nie ma nic wspólnego z tym ile stawek podatku ustawisz. Grupowy oznacza, że ustawiasz go na końcu dokumentu a indywidualny oznacza, że ustawiasz go na każdym produkcie/usłudze czy też innym elemencie [bo można podpiąć coś innego niż produkt czy usługę]. 

A to jaka opcja jest widoczna jako pierwsza, zależy od kolejności jaką ustawiliśmy w konfiguracji.

**Comment by krzychab** [comment]
W którym miejscu zmieniamy te opcje ?

**Comment by bpabiszczak** [comment]
Przypuszczam, że tutaj: https://gitdeveloper.yetiforce.com/index.php?module=Inventory&parent=Settings&view=TaxConfiguration&block=11&fieldid=92 choć to trzeba spytać programistę.

**Comment by krzychab** [comment]
Zmieniam, zmieniam i nie ma zmian po otwarciu nowego rekordu w fakturach wyświetla się grupowy

**Comment by bpabiszczak** [comment]
ale w jakich fakturach? Te narzędzia działają dla nowych modułów z produktami, nie działają na starych.

**Comment by krzychab** [comment]
Faktury sprzedażowe, przecież testuję na developerskim

**Comment by bpabiszczak** [comment]
Chyba się nie rozumiemy. Funkcjonalność o której mówimy działa dla nowych modułów z produktami [na developerskim nie ma ani jednego takiego modułu ale jest narzędzie, które pozwala taki moduł dodać] i mechanizm o którym mówimy czyli wybór podatku grupowy/indywidualny został rozwiązany dla nowego typu modułów.

Nie będziemy zmieniać już starych modułów, ponieważ w nowej wersji [pewnie 2.4] stare moduły zostaną usunięte a rekordy w nich zostaną przeniesione do nowych modułów [lub zostaną moduły do ręcznego przeniesienia danych].

**Comment by mykljohn** [comment]
How do I create an new module [type: Extended module]?  

I've set the Tax Calculations in the Other Settings Tab:
![image](https://cloud.githubusercontent.com/assets/11919990/10628515/e8317054-778b-11e5-84a9-ff40755db36c.png)

Taxes do not show up on Sales Orders or Invoices.  When I click on Tax, the popup opens, but there is no tax to select.  
![image](https://cloud.githubusercontent.com/assets/11919990/10628558/4dab1c14-778c-11e5-9a39-f9e67e4503d6.png)

We only have one standard Tax (IVA, 16%) can we set that to the default and automatically calculate?

**Comment by PercyP** [comment]
Did you manage to find a work around for this? 

I too only need one tax rate. Is it possible to switch off the alternatives so that when an invoice is created it just has one selection? The Group rate? I am assuming Group rate is the global tax rate?

Percy
