### ISSUE TITLE
More PowerFull Workflow

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#1967]
I have to mention some weak points of yetiforce workflow.

on the final stage of setuping the workflow ADD TASKS
on the drop down menu ADD TO DO

IT'S necesseracy to add as soon as possible two more options
1)Create Event
2)Create Task/To Do
and to be link it with the calendar

as it is on vtiger on demand and community i believe.
![shot](https://cloud.githubusercontent.com/assets/6897502/10117655/2706b2ae-6467-11e5-8c31-f2c4ff67c93b.jpg)

You Can find what i mean here https://wiki.vtiger.com/vtiger6/index.php/Create_Event_or_To_do

on yetiforce we have only this limited options:
Send Mail
Invoke Custom Function
Update Fields
Create Entity
Send SMS
Send Mail Template
Send PDF
Update Closed Time

and if you want to take the workflow a step further you can add a selection on the final step
if we want a pop up to appears when the action trigered.to inform at real time the user what is happening.

**Comment by florek41** [comment]
This is partially duplicated #1842.

You can create task/todo by workflow but not for all modules.
Instead of popup that you mentioned we have notifications about calendar tasks (ring icon on the right of menu bar)

**Comment by eptapsyxos** [comment]
Ok thank you very much that you have mentioned that.
And as i see is for version 2.3 
so we have to be a little more pantient :-) 

thanks florek41

**Comment by eptapsyxos** [comment]
Also i forget to mention that the functions i mentioned must be available and for the CUSTOM modules.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1842
