### ISSUE TITLE
Type::Question calls from the CRM level on mobile phones

### ISSUE THREAD

**Issue by ssstorm** [YetiForceCompany/YetiForceCRM#1970]
hi, I found (year-old)
"we're working on mobile
applications that will make it possible to generate calls from the CRM
level on mobile phones and then send a list of conversations and relate
them automatically to Organizations/Contacts/Employees.

BŁAŻEJ PABISZCZAK"

but I can't to find mobile applications, or any information about it, can you help me?

**Comment by florek41** [comment]
Isn't it https://github.com/YetiForceCompany/YetiForcePushCall and https://github.com/YetiForceCompany/YetiForceDialHistory ?

**Comment by ssstorm** [comment]
Thank you, but have you any manual for use it?

**Comment by bpabiszczak** [comment]
No, in the future we publish such instructions.

**Comment by ssstorm** [comment]
Hi, calls from crm with mobile possible or not?
