### ISSUE TITLE
https://layout.yetiforce.com/ - comment

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1971]
Menu should have second level as an accordion (pull submenus down) instead of opening another column what covers screen

**Comment by eptapsyxos** [comment]
can we have the possibility to log in to check it out?

**Comment by florek41** [comment]
it's available

http://layout.yetiforce.com/
u: admin
p: admin

**Comment by eptapsyxos** [comment]
Thank you very much

**Comment by bpabiszczak** [comment]
The default template will just act like you see today.
