### ISSUE TITLE
Problem z Mail Scanner-em

### ISSUE THREAD

**Issue by jaroow** [YetiForceCompany/YetiForceCRM#1972]
Po pobraniu i testowaniu wersji 2.2.0 napotkłaem na problem ze skanerem.
Po wybraniu uzytkownika pojawia się komunikat "Error: Brak userid".

Problem występuje zarówno w mojej instalacji jak i na stroniehttps://test.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=Index&block=8&fieldid=44.

Problemu nie ma na stronie https://gitdeveloper.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=Index&block=8&fieldid=44 gdzie zainstalowano wersję 2.2.199.

**Comment by florek41** [comment]
W nowszej wersji błąd nie występuje = został naprawiony, więc w czym problem ?

**Comment by bpabiszczak** [comment]
W tym, że ostatnia stabilna to 2.2.0 a więc pewnie chciałby fix-a ;P
W poniedziałek sprawdzimy czy błąd rzeczywiście występuje.

**Comment by jaroow** [comment]
Dokładnie tak - chodzi mi o wersję stabilną 2.2.0. Jak pisałem wcześniej w wersji wyższej tj. 2.2.199 problemu nie ma. Błąd, który znalazłem jest tylko tu: https://test.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=Index&block=8&fieldid=44 przy wyborze użytkownika.

**Comment by bpabiszczak** [comment]
Za 2-3 dni opublikujemy paczkę aktualizacyjną, która rozwiąże ten problem.

**Comment by bpabiszczak** [comment]
i pojawi się tutaj: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.2.0_to_2.3.0/zip
