### ISSUE TITLE
Rename menu "Companies and Contacts"

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1973]
I would suggest to rename default menu "Companies and Contacts" to be just  "Address book" .
More intuitive and shorter...

**Comment by jaroow** [comment]
Choose:
1. System Settings
2. Translations
3. Language Management
4. Edit language
5. Language: US English and Module menu (Modules)
Change the variable MEN_COMPANIES_CONTACTS with "Companies and Contacts" on "Address Book"

End :)

**Comment by reeid** [comment]
Thanks for your detailed instruction. I dont sacrify here time to make things good for myself only. Petition has been raised to improve default code. For everyone.

**Comment by bpabiszczak** [comment]
In my opinion the actual name is ok.
