### ISSUE TITLE
[Question] CalDAV and CardDAV integration with outlook and smartphone

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#1974]
Dear,
I would like to ask you for advice about integration of YF with outlook. i
have server in local network. From outside can connect to YF via VPN.
This works great. But also I use outlook and would like to synch contacts
and calendar. Can you provide some solution how to do it? I ask because MS
do not support card and calDAV synchronization.
And second question is how to sync contact and calendar with smartphone
automatically...?

I will be grateful for your advises...

**Comment by bpabiszczak** [comment]
1. https://www.google.pl/search?q=outlook+dav&oq=outlook+dav+&aqs=chrome..69i57.5927j0j4&sourceid=chrome&es_sm=0&ie=UTF-8
2. Soon we will prepare instructions.
