### ISSUE TITLE
Release date v2.3

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1976]
Is the release for 2.3 already in the planning? (Hoping to get the mass mail working again.) 

Second question: will the new layout version also get the same update cycle or will it remain dev up till 2.4?

**Comment by eptapsyxos** [comment]
according to the official milestone list

YetiForce 2.3 GA
 Due by October 12, 2015   Last updated 3 days ago

**Comment by bpabiszczak** [comment]
1. 2.3 [2015-10-12]
2. Bootstrap responsive design [2015-11-16] v. 2.4
3. New layout v. 3.0

**Comment by zebrahosting** [comment]
Useful to know when communicating to (possible) clients who are considering this CRM.

Bit disappointing that layouts seem more important than a 'core function' like mass mailing.

The current new layout is working pretty good so I assume you call that the bootstrap version?

**Comment by bpabiszczak** [comment]
It all depends on your point of view. Unfortunately not every programmer is suitable for designing new functionalities, therefore there are some programmers that work on the simple changes, ie. appearance. Our programmers have a lot of work, and they do the tasks ordered by our clients. No matter how many times you mention mass mailing it won't change out internal schedule.

Mass mailing requires rebuilding a number of mechanisms, such as campaign module, mail sending module, and expanding template creation, counting mechanisms etc. I assume it's enough work for 2 – 3 weeks and at the moment we don't have a specialist who has nothing to do for the following 2 – 3 weeks
