### ISSUE TITLE
What lab-pdf is about?

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1977]
What lab-pdf is about?
Does all branches has installed testing versions? If so, where?

**Comment by bpabiszczak** [comment]
It's a branch of the new PDF module.
This module has not been finished yet.
You can currently test the panel, import/export xml.
You can test here [admin/admin]:  https://pdf.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=194

**Comment by reeid** [comment]
Do you have list of functions what will be included in this module?

**Comment by bpabiszczak** [comment]
OSSPDF + PDFMaker

**Comment by florek41** [comment]
Nice !
So generation PDF with report for selected record will be included ?

**Comment by bpabiszczak** [comment]
We will include only the necessary functionalities in the first place. This module will be developed for many months, according to the needs. Ultimately, it will be equipped with all the key tools and functionalities.

**Comment by reeid** [comment]
Rapid development of this module (either paid or not) is crucial. People love PDF Maker from vtiger and going this way will be great. Of course introducing new functions will be an advantage. I personally willing to buy your paid version if it allow at lease similar functions as a PDF Maker. In my opinion introducing paid modules by Yetiforce will bring you more resources for development and assurance for Customers that modules comply your standards and all bugs will be squashed promptly.
