### ISSUE TITLE
DAV guide

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1978]
Hi, is there any news/guide related to webdav?
Seems like I need to deploy some functionality which will be working similarly to Dropbox. 
Can we have some more info form YF team please?

**Comment by witer30** [comment]
yes it would be nice to have some guide

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/1908
