### ISSUE TITLE
[PL] 2.2.0 relacje

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#1979]
Jak dodać relację pomiędzy modułami? We wcześniejszych wersjach był przycisk Stwórz relacje w modułach powiązanych w panelu admina. W 2.2 nie ma takiej możliwości?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/config/developer.php#L17 po zmianie tego parametru, opcja będzie dostępna w CRM.
