### ISSUE TITLE
Validation of access

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#1980]
Why is the Validation of access also locking the entry when the record has been earlier deleted? 

![accounts](https://cloud.githubusercontent.com/assets/10330264/10310856/c235e654-6c4c-11e5-8441-ea3eb4e32636.png)

**Comment by bpabiszczak** [comment]
That is correct. Empty the Recycle Bin, then the problem will disappear.

**Comment by kpaulaha** [comment]
Thanks, I noticed the same short after I sent the question.


-------- Alkuperäinen viesti --------
Lähettäjä: Błażej Pabiszczak <notifications@github.com> 
Päivämäärä: 06.10.2015  23.46  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] Validation of access (#1980) 

That is correct. Empty the Recycle Bin, then the problem will disappear.
