### ISSUE TITLE
[BUG ?] User preferences link in menu is missing

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1983]
in gitmaster we have:
![user_preferences_1](https://cloud.githubusercontent.com/assets/4824588/10329589/c5415a82-6cc3-11e5-8d7a-4eb105d3274f.JPG)

but in gitdeveloper this link is missing:
![user_preferences_2](https://cloud.githubusercontent.com/assets/4824588/10329591/d11f779e-6cc3-11e5-83e2-dd977837967a.JPG)

it's dissapeard or moved or removed ?

**Comment by bpabiszczak** [comment]
Removed.

**Comment by florek41** [comment]
Will it come back or is there other way to access to logged in user preferences ?

**Comment by bpabiszczak** [comment]
No going back. The only important element of this tab is to change your password.

**Comment by florek41** [comment]
So then - how non admin user can change their passwords ?
