### ISSUE TITLE
[request] Mass mailing with external providers

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#1985]
Would be nice if the mass mailing could work with an external mail server and/or provider like Amazon SES. 

A proper working mass mailing to contacts and leads is high on our list.

Of course there is an advanced wishlist:
reports for sending/receiving/clicks/opening
Bounce handling etc.

But just being able to send mails with templates to contacts without showing all their email addresses would be already be a big improvement.

**Comment by reeid** [comment]
+1

**Comment by bpabiszczak** [comment]
Dupliacet: https://github.com/YetiForceCompany/YetiForceCRM/issues/1478 
One topic enough. Add there what you think is important.
