### ISSUE TITLE
[Question] How do you empty the "wastebasket"

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1989]
I've deleted a bunch of duplicate records.  How can I remove them permanently form the database?
like an "Empty Wastebasket" function

**Comment by bpabiszczak** [comment]
Use recycle bin [on in menu] index.php?module=RecycleBin&view=List
https://gitdeveloper.yetiforce.com/index.php?module=RecycleBin&view=List&mid=118&parent=0

**Comment by mykljohn** [comment]
Sorry, It wasn't on my menu, I added it, but I get this error when trying to empty it for Accounts and Contacts 

Error!!!
Permission to perform the operation is denied for name

I'm logged in as Admin

**Comment by bpabiszczak** [comment]
Please check this on gitdeveloper version.

**Comment by mykljohn** [comment]
Here's the gitdeveloper version...notice there is no recyclebin

![image](https://cloud.githubusercontent.com/assets/11919990/10419655/87e48690-7043-11e5-9ad8-ae8a3728ad0c.png)

**Comment by bpabiszczak** [comment]
If you do not see this module on the menu, add it with this tool: https://gitdeveloper.yetiforce.com/index.php?module=Menu&view=Index&parent=Settings&block=2&fieldid=40

**Comment by mykljohn** [comment]
The error comes from /modules/RecycleBin/actions/RecycleBinAjax.php
      class RecycleBin_RecycleBinAjax_Action

		$currentUserPriviligesModel = Users_Privileges_Model::getCurrentUserPrivilegesModel();
	 	if(!$currentUserPriviligesModel->hasModuleActionPermission($moduleModel->getId(), 'Delete')) {
			throw new AppException(getTranslatedString('LBL_PERMISSION_DENIED'));
		}
	
If I comment out the Privilege check, It works.  I'm the Admin, I should have permission.

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/2035e788f3e59ab577ec7592421217fbaafd3542
