### ISSUE TITLE
[Question] recurring invoice

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#1991]
We would like the recurring invoice process to automatically send an email with the invoice attached.  Can this be done via the workflow and email templates?  Again is there any documentation on doing something like this?  cheers, Mykl

**Comment by reeid** [comment]
everything you need to start is here: https://wiki.vtiger.com/index.php/Invoke_Custom_Function

**Comment by bpabiszczak** [comment]
Look here: https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=Edit

**Comment by mykljohn** [comment]
Thanks, that's just what I was looking for :)

**Comment by amicheals** [comment]
@mykljohn How do you set a recurring invoice? I see how to set a recurring sales order, but not invoice.

**Comment by mykljohn** [comment]
@amicheals when you set up the recurring Sales Order, you have to create the first Invoice, from then on the Invoices will be automatically generated depending on the schedule you set in the Sales Order.
