### ISSUE TITLE
[Question] Values from the related module field

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#1992]
On gitdeveloper I've found **Values from the related module** field type
![values from related records](https://cloud.githubusercontent.com/assets/4824588/10372408/eed4f276-6de7-11e5-9f37-919a640bee24.JPG)

but after adding it to the module nothing happens (there is no field on the edit/create record)

It's under development now or this is bug ?

**Comment by bpabiszczak** [comment]
This field is only on list view, this field is amazing :P

**Comment by florek41** [comment]
Can I use it for workflows ? Or it's only for listview ?

Amazing ? I must test it ;)

**Comment by bpabiszczak** [comment]
Napiszę po polsku bo mi łatwiej... pole to pozwala na przeszukiwanie po modułach powiązanych, np. Jeżeli masz klienta w nim masz zakładke produkty i usługi, to jeżeli w produktach zainteresowany dodasz produkt np. drukarkę, to wtedy na liście kontrahentów masz pole select w którym możesz wybrać np. firmy zainteresowane drukarkami.... przy czym to działa wszędzie [można ustawić X pól w X modułach i działa niesamowicie szybko].

**Comment by bpabiszczak** [comment]
This field allows you to search by related modules, for example- you have a client, in it you got the products and services tab, then if you add for example a printer in the interested products, then on the list of Accounts you got a select field, where you can for example choose companies interested in printers .... It works everywhere [you can set a number of fields in a number of modules and it works incredibly quickly].

**Comment by florek41** [comment]
That's clear, thanks :)

And it works with multiple (ex. more than one product related to record) values ?

**Comment by bpabiszczak** [comment]
U can set meny calues but i dont remember how we search [&& or ||]

**Comment by rioshaz** [comment]
and where to finf the list view ?
