### ISSUE TITLE
[bug] Calendar and adjustments of user preferences 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#1993]
the parameters of "Day start at" and "Day ends at" are not coresponds with calendar....

**Comment by florek41** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

I've test on lastest version and it works.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/1995
