### ISSUE TITLE
[bug] Calendar and adjustments of user preferences 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#1996]
Sorry to open new issue but probably you didn't  understand me correctly.
When you set parameters Day starts at and Day ends at you should receive this time range in the calendar. There is useless to have timing range in the calendar from 1 till 12/24 hour...
User parameters adjustments
![image](https://cloud.githubusercontent.com/assets/11491482/10394810/d90abff4-6e99-11e5-972e-1d4bcd4fe995.png)

Calendar
![image](https://cloud.githubusercontent.com/assets/11491482/10394819/e299b39a-6e99-11e5-9d7f-3c8e860983f7.png)

hopefully now it's clear enough...

**Comment by bpabiszczak** [comment]
Problem nie jest w tym że my tego nie ustawiamy, tylko w tym, że ze względu na dwa paski przewijania, przeglądarka źle ustawia początek i koniec... 

Niezależnie od tego co jest źle, byliśmy zmuszeni zmienić widok dnia i tygodnia na taki bez godzin z lewej strony lecz na taki, który po prostu generuje wydarzenia dla danego dnia w sposób chronologiczny.

Wejdź na gitdeveloper i zobacz teraz jak to jest widoczne w tych widokach.

**Comment by witer30** [comment]
podoba mi się...

**Comment by bpabiszczak** [comment]
Zadowolenie społeczności przede wszystkim :]

**Comment by witer30** [comment]
jeśli mogę coś doradzić to bym zwiększył wysokość wiersza wpisu.. bo tak to jest malutkie... 
:-)
po za tym super z tymi godzinami....
