### ISSUE TITLE
[bug] composing mail and access to contact 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#1997]
tested gitmaster.yetiforce.com and issue occured
when composing new email I click contacts button then occure syntax error
![image](https://cloud.githubusercontent.com/assets/11491482/10395078/5232c42a-6e9b-11e5-9314-b8f7dd36fe27.png)

**Comment by witer30** [comment]
on test.yetiforce.com there is also issue... 

![image](https://cloud.githubusercontent.com/assets/11491482/10395272/4dc2f4ae-6e9c-11e5-9b96-7cf3e2285e84.png)

**Comment by konadrian** [comment]
You can see the changes here:  https://gitdeveloper.yetiforce.com/
