### ISSUE TITLE
Portal - extended ideas

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#1999]
Gathered some requests from previous posts and other, so don't let forget about portal. Nowadays this is crucial to let Customers access related data in professional and good looking form.  See below.

1. Cool design (seems now going to good direction)
2. Customer access control features similar to that of normal vtiger users
3. An increased interaction from the Customer Portal level [e.g. a possibility to accept documents].
4. An upload of documents [not only in tickets].
5. Responsive design
6. To allow simplified access to portal for employees module.
7. To allow time-sheets in portal (for version for employees)
8. To allow custom modules in easy way !!!
9.  Allow payment gateway so Customer can pay invoice in portal
10. searching, filtering list view of all data (in case of massive data amount it is crucial)
11. Better documents handling (with preview) and connection to WebDav with easy folders browsing/downloading/uploading
12. Portal should show their customers logo
13. Workflows triggering when customers had edited a record and to be able to identify the Customer who edited it (especially pick-lists)

**Comment by bpabiszczak** [comment]
Most of what you enumerated is going to appear in the system, but it will be added step by step. Thank you for collecting all of these thoughts, we have huge plans concerning the portal, we have more ideas than we are able to realize. 

I'm closing the issue. There's not point leaving it open forever.
