### ISSUE TITLE
[bug] mail scanner

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2001]
Version 2.2 
when configuring mail scanner and adding user then there is error of Error: Brak userid, can you please advice how to solve such issue...

**Comment by florek41** [comment]
Try this package: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.2.0_to_2.3.0/zip

Sholud fix your problem.

**Comment by witer30** [comment]
solved, thanks a lot... please closed ticket...
