### ISSUE TITLE
Translation PL change request

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2002]
Please change line 520 	from 'Mobile' => 'Telefon dodatkowy', to  'Mobile' => 'Telefon komórkowy',
in /languages/pl_pl/Vtiger.php...
thanks

**Comment by bpabiszczak** [comment]
Why?

**Comment by witer30** [comment]
Because Mobile is cell phone not additional phone but also addditional means not exactly mobile but to send sms it is good to clearly specify mobile...

**Comment by bpabiszczak** [comment]
Napiszę po polsku będzie szybciej. Oryginalnie to pole nazywa się mobile po angielsku, ale dla nas jest to drugi telefon. To do kogo wysłać SMS nie będzie kwestią tego w jakim polu dodasz telefon, system sam rozpozna czy to stacjonarny czy telefon komórkowy. 

Rozdzielanie pola na telefon stacjonarny i komórkowy rodzi wiele problemów, po pierwsze klienci w innych systemach mają jedno pole do tego, po drugie w widokach ustawienie dwóch pól zajmuje za dużo miejsca więc lepej jak mamy podział na podstawowy i dodatkowy. 

Nie widzę potrzeby zmiany.
