### ISSUE TITLE
[roundcube] Strange behaviour 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2003]
Here is something which I do not understand.
When pen mailbox I see mails and main icons are like below
![image](https://cloud.githubusercontent.com/assets/11491482/10413114/f8d173f4-6f9e-11e5-9f7e-36754f7c694a.png)
When i click on some email then some icons become active, like below
![image](https://cloud.githubusercontent.com/assets/11491482/10413121/28c0699e-6f9f-11e5-97cd-3c9330b3153d.png)
But when I open this mail all icons are inactive...
![image](https://cloud.githubusercontent.com/assets/11491482/10413136/b24368ba-6f9f-11e5-8d2e-8374389ded5c.png)

Also there is strange that cannot go back to inbox by roundcube,, when use mailbox button of the CRM then I am on the beginning (first screenshot)
any idea what can be responsible for such phenomenon? 

have the same mail adjustments as on demo of yeti...
This is happened for user, for admin mails works nice... 
I tried to assign user to admin privileges and have the same issue...

**Comment by bpabiszczak** [comment]
For me working properly. Tested on test version.
