### ISSUE TITLE
[bug] document module

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2004]
Use upgraded version of YF 2.2.289.
Before upgrade everything was ok with document module....
After upgrade there is error because receiving  message something like record doesn't exist... 
![image](https://cloud.githubusercontent.com/assets/11491482/10413882/5402f514-6fbc-11e5-9022-8d44ad218950.png)

additionaly some links from database menu doen't work as well...

**Comment by witer30** [comment]
adding doc from contact page via documents widget works... A doc is appearing in storage folder and it  is visible under contact... only displaing records of all documents doesn't work... in logs there is noting strange no errors... 
Can you support what can be responsible for such phenomenon...

**Comment by rskrzypczak** [comment]
Hello,
Most likely there are some errors in the DB. Check if the record actually exists in vtiger_notes (notesid = 7693) as well as in vtiger_crmentity (crmid = 7693), setype equal to "Documents" before the update, which is v2.2.0

**Comment by witer30** [comment]
well, now it started works, it seems that mail scanner during scanning mails (approx: 15000) saved all attachment into database as documents... Probably system was busy and has to melt all of data...
But my question now is how to filter all these attachments to avoid overloading database, because every logo (picture) whis is in the mail is store in document module...
Can you advice because no I save one document to test modu but have approx 9000 records...?
