### ISSUE TITLE
Request:Pushover App Integration Via Workflow

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2005]
Is that possible in feature release?
To set a trigger and a notification to be pulled to pushover app.

thank you very much.

**Comment by eptapsyxos** [comment]
Sorry I forgot to mention that the process must be scheduled through the workflow mechanism.
Thank you very much for your attention.

**Comment by bpabiszczak** [comment]
We do not plan to add this functionality.
