### ISSUE TITLE
[Question] Payments Out

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2006]
In implementing the Payments In and Payments Out modules, I noticed that they both point to the Accounts Module.  Shouldn't Payments Out Relate to Vendors instead?  Or do we need to create an Account record for each Vendor?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/398cd702a8d8933bcb4a6c3f1cbbf9e1bfe01b64
