### ISSUE TITLE
Problem z raportowaniem

### ISSUE THREAD

**Issue by slawhodu** [YetiForceCompany/YetiForceCRM#2008]
witam. 
na wersji 2.2.0 chcę zrobić raport wizyt przedstawicieli (z kalendarza, powiązani kontrahenci).
wybieram na początek kolumny nazwa kontrahenta i data realizacji i...:

Fatal error: Call to a member function rowCount() on a non-object in /crm/include/database/PearDatabase.php on line 283.

Pomocy!

**Comment by slawhodu** [comment]
Po aktualizacji do 2.3 (zrobiłem na nowo raport):
Błąd!!!
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/2063
