### ISSUE TITLE
[Bug] Binded emails

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2010]
Version 2.2.289
There is an small issue with binded email to contact... 
![image](https://cloud.githubusercontent.com/assets/11491482/10429425/bebec4b8-70f8-11e5-9d6b-932974ac9e75.png)
There is double name nad surnem of sender. When only email address is diplaying then evetything is ok... 
![image](https://cloud.githubusercontent.com/assets/11491482/10429458/04e52522-70f9-11e5-8b45-ce208d4d891c.png)

I also suggest to switch off an opening of contact details page when operator klik on the name of sender - we are on this page of contact....

**Comment by bpabiszczak** [comment]
The problem was solved in the new version, please update your system to the latest stable version 2.3+ install the fix marked as  2.3.0_to_2.3.49_v1.zip: 

https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip
