### ISSUE TITLE
[recomendation] Document module - external doc

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2013]
Very useful could be button to specified path to the file... By clicking doc and accepting choice the path to the file should be automatically appeared...
![image](https://cloud.githubusercontent.com/assets/11491482/10436886/ab3d17f6-7129-11e5-864a-af00ba3859c5.png)

**Comment by witer30** [comment]
is it possible to implement such solution?

**Comment by bpabiszczak** [comment]
We do not plan to add this functionality.
