### ISSUE TITLE
Brak tłumaczenia dla alertu konwertera lead-ów

### ISSUE THREAD

**Issue by jaroow** [YetiForceCompany/YetiForceCRM#2019]
Obecnie przy próbie konwersji leada na istniejącego kontrahenta pojawia się komunikat/alert:
Nie można wykonać konwertowania
Możliwe przyczyny:
Mapowanie pól nie zostało ukończone, przejdź do: (Administracja > Dostosuj moduły > Moduły > Leady > Zarządzaj mapowaniem pól)
Wymagane pola są puste
Lead is already converted

Proponuję poprawkę w pliku https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/include/Webservices/ConvertLead.php począwszy od linii 56.
Zamiast
		$log->error('Error converting a lead: Lead is already converted');
		throw new WebServiceException(WebServiceErrorCode::$LEAD_ALREADY_CONVERTED, "Lead is already converted");
Proponuję:
		$log->error('Error converting a lead: ' . vtws_getWebserviceTranslatedString('LBL_' . WebServiceErrorCode::$LEAD_ALREADY_CONVERTED));
		throw new WebServiceException(WebServiceErrorCode::$LEAD_ALREADY_CONVERTED, vtws_getWebserviceTranslatedString('LBL_' .
			WebServiceErrorCode::$LEAD_ALREADY_CONVERTED));

I dodanie do https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/languages/pl_pl/Leads.php kolejnej zmiennej - przykładowo dla pl_pl: 'LBL_LEAD_ALREADY_CONVERTED' => 'Lead był już konwertowany',

**Comment by rskrzypczak** [comment]
Thanks
