### ISSUE TITLE
Problem przy dodawaniu zamówienia od klienta przez szanse sprzedaży

### ISSUE THREAD

**Issue by jaroow** [YetiForceCompany/YetiForceCRM#2021]
Podczas dodawania zamówienia od klienta realizowanego przez szanse sprzedaży, tj. po jego zapisie zostajemy przekierowani na index.php (biały ekran) zamiast przykładowo index.php?module=Potentials&relatedModule=SalesOrder&view=Detail&record=126&mode=showRelatedList&tab_label=Sales%20Order.
Przy odświeżeniu dodają się kolejne zdublowane rekordy (zamówień od klienta).
W Vtiger 6.3 problem nie występuje.

**Comment by bpabiszczak** [comment]
U mnie działa poprawnie. 
Proszę zapoznać się z tym artykułem: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html
