### ISSUE TITLE
2.3.0

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2023]
Congrats on the version 2.3.0, a few questions about something I did not find.
1. where can the user change his/her password?
2. how will I get the language selection on the login page when uppdating from 2.2.0?

**Comment by waw555** [comment]
2. The file /config/config.inc.php change
// System language selection in the login window (true / false).
$ langInLoginView = true;

**Comment by waw555** [comment]
1. 
![animation 158](https://cloud.githubusercontent.com/assets/1402355/10532770/4dfef424-73db-11e5-9d59-8da511bd647d.gif)

**Comment by bpabiszczak** [comment]
Thank you @waw555
