### ISSUE TITLE
[Bug] records of email

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2024]
Version 2.3
there is issue as footer is hiding last row of emails bind to contacts. Issue noticed from widget module Email display from contact page...

![image](https://cloud.githubusercontent.com/assets/11491482/10459790/807ccc2a-71d1-11e5-8e79-31633a619765.png)

**Comment by konadrian** [comment]
The error doesn't occur in the latest version
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/10752025/d4ec323c-7c85-11e5-9098-1a3cc14870f3.png)
