### ISSUE TITLE
Update 2.3 : Module does not contain default language (en_us).

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2026]
trying to update but get the error above. Any idea what might go wrong?
Using Sourceforge version. Did a re-zip but that does not help.
Tried on different servers and most of them have this issue.

**Comment by zebrahosting** [comment]
Found it! my bad.

**Comment by PercyP** [comment]
hi,

I too am getting this same error, can you tell me how you overcame it?

Regards

Percy

**Comment by zebrahosting** [comment]
Thats because you try to install the full version. The download link only points to the full download.
Go to files and search for the update packages and go from there.
