### ISSUE TITLE
[bug] correlation of product field with quote - margin, tax VAT, price

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2028]
Version 2.3
Tested on https://test.yetiforce.com

I created product for test and defined price, margin, and vat tax (here is no possibility to set it as default)
![image](https://cloud.githubusercontent.com/assets/11491482/10466118/d5e8358e-71f2-11e5-926b-89b32b5058c4.png)

Then I create calculation - and of course use my product for it -> **there is no transfer margin from product.** No possibility to enter margin on calculation page as it is calculated based on price and purchase price. 
![image](https://cloud.githubusercontent.com/assets/11491482/10466233/884b1624-71f3-11e5-81d1-7671f30b6165.png)

This is really complicated as someone base on margin...
**It would be better to have on product specification an extra field "Purchase" which will calculate margin there and will be correlated with calculation and then with quote.**

The same is with quote, when you use calculation **there is not transferring price, tax and margin so manually you have to entered all necessary prices factors...** 
![image](https://cloud.githubusercontent.com/assets/11491482/10466591/47bfd7d2-71f5-11e5-852a-76165d03a589.png)

**The same is with tax not trasfered**- when defined on product page then you have to adjust it in calculation and also in quote... should be transfer automatically... 
![image](https://cloud.githubusercontent.com/assets/11491482/10466635/857e4bf8-71f5-11e5-87b2-200b3cee188c.png)

**Comment by witer30** [comment]
is it possible to increase priority of this part as selling is very important and has to be represent by CRM...

**Comment by bpabiszczak** [comment]
Odpowiem po polsku, bo tak szybciej.

1. W wersji 2.4 są już nowe mechanizmy dla modułów z produktami.
2. Stary mechanizm nie umożliwiał oznaczenia podatku jako domyślny. W nowej wersji o ile dobrze pamiętam jest to możliwe.
3. Nowy mechanizm umożliwia dodanie dowolnego pola z modułu produktu/usługi, nie wiem tylko, czy jest to konfigurowalne czy wymaga fragmentu kodu.

Rozumiemy niedoskonałości starego mechanizmu, lecz są to mechanizmy odziedziczone po Vtiger. Nowa wersja powinna większość tych problemów rozwiązać.

**Comment by witer30** [comment]
a kiedy będziemy zaszczyceni zabawą wersją 2.4...?
:-) 
PS. Dzięki za info o nowym module...

**Comment by bpabiszczak** [comment]
Mam nadzieje, że 14 dni. Musimy tylko podmienić stare moduły nowymi... 
A widziałeś to: https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95

**Comment by witer30** [comment]
noooo...
Powiem że spełniliście moje marzenie...
To rozwiąże sporo problemów i ułatwi życie... 
No moje wyrazy uznania...

**Comment by zimart** [comment]
No to super :) na vtigerze robiłem to na piechotę... :) troche masakra - jak miałem kilka własnych pól do przeniesienia między ofertą a zamówieniem - powiem szczerze że co chwilę testuję  funkcjonalności i jakby nie problem z VAT-em dalej - szczególnie przy własnym module - to już bym chętnie sie przesiadł na YETI. Wspaniała robota.

**Comment by florek41** [comment]
Niby ta funkcjonalność nie była jakoś specjalnie skomplikowana do dodania z poziomu kodu, ale teraz to po prostu bajka :) Właśnie przez takie rzeczy system zwiększa swoją przewagę nad protoplastą.
Jestem pod wrażeniem zarówno pracy jaką wkładacie w rozwój systemu jak i kierunku w którym to wszystko zmierza.
Świetna robota i oczywiście czekamy na więcej !
