### ISSUE TITLE
[Bug] Calculation search results from quote

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2029]
when trying to search calculation there is error... 
![image](https://cloud.githubusercontent.com/assets/11491482/10466787/57bf1c28-71f6-11e5-9935-687d3df92097.png)

**Comment by mariuszkrzaczkowski** [comment]
Tested on the latest version and the error doesn't occur.

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/2063
