### ISSUE TITLE
[Question] Adding extra field to quote

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2030]
how I can add an extra filed (contact name) to quote details section which will be related with account name...? Means that when quote will be assign to account 1 then I would be possible assign this quote also to contact 1 which is under that account. Is it possible... 
Thanks

**Comment by bpabiszczak** [comment]
If you call the contact selection window with correct parameters it will work, but it has to be done from the programmer's perspective.
