### ISSUE TITLE
Change Short name to last name

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2032]
Hi,

I am just familiarizing myself with Yetiforce and loving it so far!

However I am missing a Last Name field in my contacts, but see there is something called Short Name - should this be Last Name? If not, what is Short name supposed to be used for?

If so, I would like to change it to say Last Name or Full Name. I have gone through the language files and database fields but cannot find it anywhere? It is only the label I want to change.

**Comment by amicheals** [comment]
@PercyP short name is the field to put the last name.

**Comment by PercyP** [comment]
@amicheals 

Yes, I thought as much, I just want to change the label Short name to the word Last name as short name doesn't mean anything to us. Do you know where I change it?

Percy

**Comment by witer30** [comment]
system settings -> transtaltion -> 
![image](https://cloud.githubusercontent.com/assets/11491482/10490251/502f1dd2-72a0-11e5-8aa9-5ae5733f41b6.png)

and a little bit below
![image](https://cloud.githubusercontent.com/assets/11491482/10490271/70ab7cfe-72a0-11e5-9f2d-ed59482e381b.png)

**Comment by PercyP** [comment]
Ah thanks witer30, 
it doesn't show in that file via the settings, but I went to the actual language file on the server and changed it there. I had been thinking it would be in Contacts :)

I downloaded yetiforce 2 days ago, might it be you have a newer version than me?
Percy

**Comment by witer30** [comment]
i have 2.3
good that you manage 
Dnia 14 października 2015 18:37 PercyP napisał(a):
 Ah thanks witer30,
it doesn't show in that file via the settings, but I went to the actual language file on the server and changed it there. I had been thinking it would be in Contacts :)I downloaded yetiforce 2 days ago, might it be you have a newer version than me?
Percy—

**Comment by mykljohn** [comment]
It should be there.  Settings > Translations > Language Management.  Select the Edit Language Tab and Choose the language you want to modify and the module.  I just did the same thing, changed "Short Name" to "Last Name".

**Comment by PercyP** [comment]
I have just checked, I am on version 2.20, maybe thats why it isn't appearing in mine. I am just looking at the update process, do I have to run all the updates from 2.2 including the files the end in .md5?

**Comment by PercyP** [comment]
I update to latest version and when I view the vtiger language file via the CRM under translations for en_us it definitely doesn't have Short code in there at all. But if I view the actual file it is definitely in that. 

Very strange ... but at least I can amend it directly in the file :)

**Comment by amicheals** [comment]
@PercyP when you go to Settings > Translations > Language Management and edit your language, you have to choose the module name vtiger not contact. It's there.

**Comment by PercyP** [comment]
@amicheals 

yes, thats exactly what I did, here are the fields that are in it - definitely no Short name or even Last name etc. This is the vtiger module in en_us language file.

Mail
GlobalPermission
OSSCosts
LBL_ADDING_ERROR
LBL_ADDED_COMPANY_FIELD
LBL_FIELD_NOT_VALID
LBL_EXTENDED_MODULES
LBL_QUICK_CREATE_EDITOR
LBL_QUICK_CREATE_EDITOR_DESCRIPTION
LBL_API_ADDRESS
LBL_API_ADDRESS_DESCRIPTION
LBL_ACTIVITY_TYPES
LBL_ACTIVITY_TYPES_DESCRIPTION
LBL_BRUTEFORCE
LBL_BRUTEFORCE_DESCRIPTION
LBL_WIDGETS_DESCRIPTION
LBL_CREDITS_DESCRIPTION
LBL_CUSTOMVIEW_DESCRIPTION
LBL_SEARCH_SETUP_DESCRIPTION
LBL_GLOBALPERMISSION_DESCRIPTION
LBL_LANGMANAGEMENT_DESCRIPTION
LBL_DATAACCESS_DESCRIPTION
LBL_OSSPASSWORD_CONFIGURATION_DESCRIPTION
LBL_LICENSE_DESCRIPTION
LBL_PROJECT_TEMPLATES_DESCRIPTION
LBL_DOCUMENT_CONTROL_DESCRIPTION
LBL_MAIL_VIEW_DESCRIPTION
LBL_MAIL_LOGS_DESCRIPTION
LBL_WIDGETS_MANAGEMENT
LBL_WIDGETS_MANAGEMENT_DESCRIPTION
LBL_MDULES_COLOR_EDITOR
LBL_MDULES_COLOR_EDITOR_DESCRIPTION
LBL_MOBILE_KEYS
LBL_MOBILE_KEYS_DESCRIPTION
LBL_TREES_MANAGER
LBL_TREES_MANAGER_DESCRIPTION
LBL_MODTRACKER_SETTINGS
LBL_MODTRACKER_SETTINGS_DESCRIPTION
LBL_HIDEBLOCKS
LBL_HIDEBLOCKS_DESCRIPTION
LBL_PUBLIC_HOLIDAY
LBL_PUBLIC_HOLIDAY_DESCRIPTION
LBL_USER_COLORS
LBL_USER_COLORS_DESCRIPTION
LBL_CONVERSION_TO_ACCOUNT
LBL_DAV_KEYS
LBL_DAV_KEYS_DESCRIPTION
LBL_AUTOLOGIN
LBL_AUTOLOGIN_DESCRIPTION
LBL_MAIL_GENERAL_CONFIGURATION
LBL_MAIL_GENERAL_CONFIGURATION_DESCRIPTION
LBL_SUPPORT_PROCESSES
LBL_SUPPORT_PROCESSES_DESCRIPTION
LBL_REALIZATION_PROCESSES
LBL_REALIZATION_PROCESSES_DESCRIPTION
LBL_FINANCIAL_PROCESSES
LBL_FINANCIAL_PROCESSES_DESCRIPTION
LBL_MARKETING_PROCESSES
LBL_MARKETING_PROCESSES_DESCRIPTION
LBL_COLORS
LBL_COLORS_DESCRIPTION
LBL_MENU_BUILDER
LBL_MENU_BUILDER_DESCRIPTION
LBL_AUTHORIZATION
LBL_AUTHORIZATION_DESCRIPTION
LBL_CALENDAR_CONFIG
LBL_CALENDAR_CONFIG_DESCRIPTION
LBL_OSSPDF_INFO
LBL_BACKUP_DESCRIPTION
LBL_SCHEDULER_DESCRIPTION
LBL_OSSMAIL_DESCRIPTION
LBL_PBXMANAGER_DESCRIPTION
Mail Logs
Board of Management
Sales Department
Logistics Department
Project Management Department
Help Desk Department
Human Resources Department
Secretary's Office
Organization
Financial Department
Production Department
Marketing Department
OSSPassword Configuration
Document Control
Time control
Credits
LBL_PROCESSES
LBL_SALES_PROCESSES
LBL_SALES_PROCESSES_DESCRIPTION
INVENTORYTERMSANDCONDITIONS
LBL_SAVE_CONFIG
LBL_VIEW_LICENSE
LBL_VIEW_CONFIGEDITORDETAIL
LBL_VIEW_TAXINDEX
LBL_VIEW_CUSTOMRECORDNUMBERING
LBL_VIEW_TERMSANDCONDITIONSEDIT
LBL_VIEW_COMPANYDETAILS
LBL_VIEW_ANNOUNCEMENTEDIT
LBL_VIEW_OUTGOINGSERVERDETAIL
JS_ANNOUNCEMENT_SAVED
JS_CONFIGURATION_DETAILS_SAVED
JS_CONFIRM_DEFAULT_SETTINGS
JS_EDIT
JS_GROUP_DELETED_SUCCESSFULLY
JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO100
JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO5
JS_PLEASE_SELECT_ATLEAST_ONE_MEMBER_FOR_A_GROUP
JS_RECORD_NUMBERING_SAVED_SUCCESSFULLY_FOR
JS_RECORD_NUMBERING_UPDATED_SUCCESSFULLY_FOR
JS_SEQUENCE_NUMBER_MESSAGE
JS_TAX_DISABLED
JS_TAX_ENABLED
JS_TAX_SAVED_SUCCESSFULLY
JS_TERMS_AND_CONDITIONS_SAVED
LBL_MAXIMUM_SIZE_EXCEEDS
LBL_NO_LOGO_SELECTED
LBL_PREFIX_IN_USE
LBL_WRONG_IMAGE_TYPE
JS_COLUMN_ADDED
JS_COLUMN_EXIST

**Comment by paula-w** [comment]
So what's your question ultimately?
