### ISSUE TITLE
[Discussion] Timesheet approval

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2034]
I wonder how to best deal with time sheet approval.
Standard is is set to 'for approval' but I see no place to set it to default 'Accepted'
There seems no place to do a mass edit to set all to Accepted. 

I understand this default workflow but it is not handy for clients who don't want to be bothered with acceptance.
The timesheets don't show up if the status is not set to accepted so I have to do them all one by one now.

Any suggestions for improvements?

**Comment by florek41** [comment]
If you want to set "Accepted" as default you can do it by **Quick Create Editor** (https://gitdeveloper.yetiforce.com/index.php?module=QuickCreateEditor&parent=Settings&view=Index&sourceModule=OSSTimeControl)

You can view list of all timesheet records - https://gitdeveloper.yetiforce.com/index.php?module=OSSTimeControl&view=List - there you can Mass Edit and change status.

**Comment by zebrahosting** [comment]
Thanks for the help.
Quick editor does not allow editing the fields.
I was looking in the picklists to edit but it turns out that it can be done in the module settings -> edit fields (stupid me)
Timesheet list does allow mass edit but editing the status is not there.

Did you actually try this before posting?

**Comment by florek41** [comment]
All those problem you can solve using **Fields and Layouts Editor**

https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=OSSTimeControl

find your field - click on pencil (edit) button - there you can enable this field for mass edit and change default value:

![yf_timesheet](https://cloud.githubusercontent.com/assets/4824588/10509595/597d3868-732e-11e5-887c-974e66071ce1.jpg)

**Comment by zebrahosting** [comment]
Thanks, all clear and working now
