### ISSUE TITLE
product list price auto fill not correct in sales order

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#2037]
when pickup a product in sales order or cost and so on
System will auto fill the list price read from product database.
but after upgrade to 2.3, if user choose , as their Digit Grouping Separator and group by 123,456.00
system will cut off all number after ,
eg: the list price is 5000
then system will auto fill 50.00 in sales order  
![image](https://cloud.githubusercontent.com/assets/15126825/10487801/5ac5dc0e-72c8-11e5-9574-8cb21cc5ad09.png)
![image](https://cloud.githubusercontent.com/assets/15126825/10487807/61b3869c-72c8-11e5-9f60-8a3dc5ef3d1e.png)

**Comment by witer30** [comment]
look also this
https://github.com/YetiForceCompany/YetiForceCRM/issues/2028
think that products calculation quote should be improved, when you entered product with price, margin, and new field purchase price these factors should be transfer automatically to all modules...

**Comment by bpabiszczak** [comment]
Duplicate: #2028
