### ISSUE TITLE
Błąd - użytkownicy

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2039]
O oststniej wersji - 2.3.16 jest bład z zarządzaniem użytkownikami :( nie zauwazylkem jak bylo w 2.3 - nie można ani edytować siebie - ani dodać nowego - menu pod nazwą żuytkownika bylo ok - może niepotrzebnie znikneło.. :)

**Comment by witer30** [comment]
wejdź w ustawienia systemu oraz w zarządzanie użytkownikami i tam masz wszystko... tak również było w wersji 2.3... to jest zmiana..

**Comment by zimart** [comment]
ale brak uprawnień :) na waszym demo także :)

**Comment by witer30** [comment]
zgadza się, jest błąd systemu

**Comment by mariuszkrzaczkowski** [comment]
Błąd został już naprawiony, dodatkowo jest możliwość włączenia "Moje ustawienia" wystarczy w pliku
config/security.php ustawić parametr:
'SHOW_MY_PREFERENCES' => true,
