### ISSUE TITLE
Problem installing VTModuleDesigner

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2041]
When trying to install it, it fails with this message 
Failed
Module does not contain default language (en_us).  I've talked to the designer here on GitHub, and he hasn't testest it with YF.  I would like to test it if I can get some help with the install

**Comment by mykljohn** [comment]
Just a note, the language folder is there with the en_us folder and the language file.  I've attached the zipfile here (renamed as .png)  

![moduledesigner_1 0rc](https://cloud.githubusercontent.com/assets/11919990/10497134/f33cfc72-7289-11e5-8f4e-533b3b691dbd.png)

**Comment by mykljohn** [comment]
I completed the install, I had to re-zip the files. I copied the patch.  but when I open ModuleDesigner, it shows nothing.   here's the error log:

Database ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'globo_yeti.vtiger_parenttab' doesn't exist
Query: SELECT * FROM vtiger_parenttab ORDER BY parenttab_label ASC
#0  PearDatabase->checkError() called at [/yeti/include/database/PearDatabase.php:354]
#1  PearDatabase->pquery() called at [/yeti/modules/Settings/ModuleDesigner/views/Index.php:41]
#2  Settings_ModuleDesigner_Index_View->process() called at [/yeti/include/main/WebUI.php:220]
#3  Vtiger_WebUI->process() called at [/yeti/index.php:25]

**Comment by mykljohn** [comment]
was the parenttab table renamed in YF?  
the code is:
//		$query = "SELECT * FROM vtiger_parenttab ORDER BY parenttab_label ASC";
//		$result = $db->pquery($query, array());
		
//		$a_parent_tabs = array();
//		while($row = $db->fetchByAssoc($result))
//		{
//	        switch($row['parenttab_label'])
//	        {
//	            case 'Sales': case 'Marketing':
//	                $row['parenttab_label_string'] = 'MARKETING_AND_SALES';
//	            break;
//	            case 'My Home Page':
//	                $row['parenttab_label_string'] = 'MY_HOME_PAGE';
//	            break;
//	            case 'Settings':
//	                $row['parenttab_label_string'] = 'SETTINGS_TITLE';
//	            break;
//	            default:
//	                $row['parenttab_label_string'] = strtoupper($row['parenttab_label']);
//	            break;
//	        }

//	        $a_parent_tabs[] = $row;
//		}
		
		//Get modules
		$query = "SELECT * FROM vtiger_tab ORDER BY tablabel ASC";
		$result = $db->pquery($query, array());
		
		$a_modules = array();
so it's looking for the vtiger_parenttab table and then the vtiger_tab table which still exists.

**Comment by reeid** [comment]
Was it designed for Yetiforce? Yes? No? 
You looking for answer in wrong place. You should talk to extension developer.

**Comment by bpabiszczak** [comment]
This module doesn't belong to us, you should contact its developer.

This module can't be used in YetiForce because it doesn't take into account the changes that are introduced into the system!

What functionality are you missing that you want to use that module? If you're missing something, create a new issue for that.

**Comment by mykljohn** [comment]
Hi, I want to add the vTiger Subscription Module, which is a modification of the Sales Order Module.  This was made for vTiger.  I was testing it to see if it worked in YF.  (apparently not :) )
