### ISSUE TITLE
[translation] Karta wymagań - Nowy zamiast Nowa 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2042]
![image](https://cloud.githubusercontent.com/assets/11491482/10493963/1c0424bc-72b4-11e5-9cfe-bb883a9c1f3b.png)
![image](https://cloud.githubusercontent.com/assets/11491482/10493992/352dd23a-72b4-11e5-9d1e-f3882332b441.png)

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/8a0e9a2883580b8d2e1de18227c4848bb44d7371
