### ISSUE TITLE
Calculation in custom fields  "Project Module

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2043]
I have custom fields in the project module that requires currency.  Is there a way  to have a total calculation of these fields?  I may just be missing something here.

**Comment by florek41** [comment]
Where you want have those sum ?
Have you few fields with $$ in one record and you want to summarize it to different field(in same record) ?

**Comment by jbmcclain** [comment]
Here i thought an illustration may help this out.

![yetiforce project sum](https://cloud.githubusercontent.com/assets/1903662/10495585/a3d4b5b6-728a-11e5-9e3e-7cdd2d761be1.png)

**Comment by jbmcclain** [comment]
ill actually have about 15+ fields on each side. that will need totals and maybe future expansion.  Does that make since?  Thank you for your help.

**Comment by florek41** [comment]
IMO the easiest way is **Workflow** - calculations are made after saving (or changing record):
1. Create your fields.
![fields2](https://cloud.githubusercontent.com/assets/4824588/10496958/92e580ee-72c3-11e5-9200-93a565ab1020.JPG)
![fields](https://cloud.githubusercontent.com/assets/4824588/10496959/92e6e20e-72c3-11e5-8b30-8c868673af58.JPG)

2. Go to **settings -> Other Settings -> Workflows** and create new workflow
![workflow1](https://cloud.githubusercontent.com/assets/4824588/10496962/99e410ae-72c3-11e5-9df2-eada003b4285.JPG)

You can add extra conditions (ex. check if at least one field is filled)
![workflow2](https://cloud.githubusercontent.com/assets/4824588/10496966/9cd79db2-72c3-11e5-9f1e-f16675e33115.JPG)

![workflow3](https://cloud.githubusercontent.com/assets/4824588/10496967/9f0a9008-72c3-11e5-99a0-eabda8884f3a.JPG)

Select **add field** then select your TARGET (sum) field and click on empty input which open field editor
![workflow3-1](https://cloud.githubusercontent.com/assets/4824588/10497081/4d630d88-72c4-11e5-9760-93d6594b5edd.JPG)

then enter simple summary function ( fieldname1+fieldname2+fieldname4(...) ) )you can select your field form **Use Field** select)
![workflow4](https://cloud.githubusercontent.com/assets/4824588/10496968/a0925d02-72c3-11e5-8ec9-2e2295231778.JPG)

Save it and test it :)

you can check it on developer test version (for next few minutes)
Fields: https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=Project
Workflow: https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=Edit&record=63
Test record: https://gitdeveloper.yetiforce.com/index.php?module=Project&view=Edit&record=111

**Comment by witer30** [comment]
dear florek41,
Maybe you know if it is possible to conncet and trasfer such sum fields with/into qoute and calculation...

**Comment by jbmcclain** [comment]
This is great! i would never had seen this!!! Thank you so much!

**Comment by hijab03** [comment]
I followed the same steps but it is not working for me. I want to subtract agreed amount from Opportunity amount and save it in balance.
![image](https://user-images.githubusercontent.com/19935954/29546722-4fed52a8-8739-11e7-84b5-d912a0fb4a25.png)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
please open a new issue and describe in detail what you want to achieve and what isn't working.

**Comment by juniarsofyan** [comment]
how if i want to generate automatic transaction number,
for example i have form with 2 input (transaction number and date of transaction)
how to show generated transaction number in transaction number input field?

**Comment by cltvchannel** [comment]
Look at Modules - Prefixes in Admin Panel.
Maybe will help you.
