### ISSUE TITLE
[Question] regrading upgrading.

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2045]
I've made a bunch of changes to field labels.  If and when I upgrade, I have a feeling these will be overwritten...yes, no ???

**Comment by florek41** [comment]
Do you really want to make upgrade on production system without previously test it ?
Duplicate production to test server and then upgrade.

And give us know if it will be overwritten :)

**Comment by mykljohn** [comment]
No, this is just for future reference. :)  I know YF is continually evolving and in Dec there is supposed to be a new release.  I'm just curious if I'll have to change the labels again.  I know I can backup the language files and use them, I was just a wondering :)

**Comment by amicheals** [comment]
@mykljohn I think if the labels were changed in Language setting it should not be overwritten. But, I would test first

**Comment by mykljohn** [comment]
Thanks, fully plan on making a backup and testing before hand. :)

**Comment by bpabiszczak** [comment]
Will be overwritten! Read this: https://yetiforce.com/en/developer-documentation/engine/177-loader-and-autoloader-of-files.html

**Comment by mykljohn** [comment]
thanks, I knew that, but wanted to confirm.

**Comment by waran70** [comment]
Don't troll than...

**Comment by mykljohn** [comment]
wasn't trolling, just wanted to confirm.
