### ISSUE TITLE
Navigating 

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2049]
New layout is terribly difficult for navigating with mouse. It may work with finger but mouse is not perfect. Sliding menu on the left could be redesigned for sake of good user experience

**Comment by witer30** [comment]
Sorry do not agree with you... It is nice, easy to use for both method - mouse and finger...

**Comment by eptapsyxos** [comment]
it much better from the previous.

**Comment by bpabiszczak** [comment]
We've added support for multiple templates. Will be available both templates.
