### ISSUE TITLE
upgrade to 2.3.6 dashboard error

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#2050]
after upgrade to 2.3.16 I get SQL warning on dashboard:

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`yetiforce`.`vtiger_module_dashboard_widgets`, CONSTRAINT `vtiger_module_dashboard_widgets_ibfk_1` FOREIGN KEY (`templateid`) REFERENCES `vtiger_module_dashboard_widgets` (`id`) ON DELETE )

**Comment by mariuszkrzaczkowski** [comment]
Delete all data from the vtiger_module_dashboard_widgets table, it should fix the problem. For example:
DELETE FROM `vtiger_module_dashboard_widgets`

**Comment by lalord** [comment]
works!
