### ISSUE TITLE
Fe.Req:Document Preview

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2052]
Document to be previewed without to be download every time.

Even image crop or rotation would be great.

Yetiforce!

**Comment by waw555** [comment]
Good Idea

**Comment by witer30** [comment]
perfect idea

**Comment by bpabiszczak** [comment]
Google Chrome has built-in support previews of PDF files. In addition, we plan to implement WebDAV.

**Comment by florek41** [comment]
with PDF you have right but what with simply images or doc / excel documents ?
Nice popup (modal window) with preview will be very big UX improvement.

**Comment by bpabiszczak** [comment]
At the moment we are not planning to add a window to preview different file formats. You can order it from us for a fee, or do it on your own and submit for approval.
