### ISSUE TITLE
Task Managment Yeti

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2053]
For discussion or feature request

as appeared on the new vtiger layout.

![taskmanagment](https://cloud.githubusercontent.com/assets/6897502/10509627/ebec105e-7336-11e5-8c3b-63651c148794.jpg)

**Comment by bpabiszczak** [comment]
That's what the Gantt chart is for, and in my opinion it works better. It requires some improvements, but it's ideal to illustrate projects.
