### ISSUE TITLE
[BUG] Install Problem v 2.3.0

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2054]
Hello!!!

Flew from vacation, he saw a new version began to test and then immediately it?

ERR_NOT_AUTHORIZED_TO_PERFORM_THE_OPERATION

![animation 154](https://cloud.githubusercontent.com/assets/1402355/10512491/3b36107e-735a-11e5-8724-5ea74c817a74.gif)

**Comment by mariuszkrzaczkowski** [comment]
Try the latest stable version https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/2.3.16

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/2031

**Comment by waw555** [comment]
How to use the patch, if the system is not installed? Just replace the files from the update?

**Comment by mariuszkrzaczkowski** [comment]
This is not a patch, just Replace
