### ISSUE TITLE
[BUG] Edit Fields 

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2057]
![animation 157](https://cloud.githubusercontent.com/assets/1402355/10515458/03e88706-736d-11e5-94f1-fd90370d5ebb.gif)

**Comment by witer30** [comment]
Dear Alexiej,
I noticed that you are using advance layout editor...
Can you tell me what I can do by this editor - I wanted to combine few fields between product and quote... Is it possible...?
thanks in advance
Dnia 15 października 2015 15:46 Алексей napisał(a):

**Comment by waw555** [comment]
You want to box in the products were the same as the field in the offer?

To these fields were the same regardless of where they changed?

If so, then this kind do without interference to the code can not be!

**Comment by bpabiszczak** [comment]
Please check the latest versions
