### ISSUE TITLE
Calendar events does not show up on calendar

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2058]
This only happens for my username, but when I create an event, the event does not show on my calendar, only under calendar list. The event/call is saved but does not show. Is there a setting I am missing?

![image](https://cloud.githubusercontent.com/assets/11178457/10517670/c3eb2172-732b-11e5-9985-e6e06ab2bcd6.png)

**Comment by bpabiszczak** [comment]
Version? Work on dev ? Read this: https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by amicheals** [comment]
Version 2.3
This error does not show up on the test server.
Other user ids in the system is able to see their events, tasks on the calendar.

I'm wondering if there is a settings I'm missing ur didn't activate

**Comment by bpabiszczak** [comment]
Please upgrade system to 2.3.49 and check again. 
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip

**Comment by bpabiszczak** [comment]
On version 2.3.49 [https://test.yetiforce.com] work ok. Please upgrade system to 2.3.49 and check again. 
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip

**Comment by amicheals** [comment]
I upgraded to 2.49 and still an issue. Not sure what it is. Events do not show up on calendar. I will continue to test

**Comment by bpabiszczak** [comment]
Unfortunately I can't trigger this error, and if I can't trigger it then we can't fix it. Use this tool https://screentogif.codeplex.com/ to record a video and reopen the issue. Also check if the error occurs here: https://gitdeveloper.yetiforce.com/
