### ISSUE TITLE
[bug] Account summary

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2060]
Bug when filtering Contact emails in Account summary
![accounts](https://cloud.githubusercontent.com/assets/10330264/10520742/8aef3fea-7374-11e5-9b7b-f89020432153.png)

**Comment by bpabiszczak** [comment]
VERSION?

**Comment by kpaulaha** [comment]
2.3.16 & 2.3.25

**Comment by bpabiszczak** [comment]
Please upgrade system to 2.3.49 and check again. 
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip

**Comment by kpaulaha** [comment]
It still give the error in v.2.3.174 if the account do not have any contacts and you filter contact emails. If there are contacts it works.

**Comment by bpabiszczak** [comment]
Please use this https://screentogif.codeplex.com/ and show me this error on test/gitdeveloper version.

**Comment by kpaulaha** [comment]
![accounts](https://cloud.githubusercontent.com/assets/10330264/10849387/41bc0ed2-7f29-11e5-8066-2575266ce8d6.gif)
