### ISSUE TITLE
[question] jak dodać nowe pole słownikowe

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2062]
Czy istnieje taka możliwość? Jeśli tak to gdzie? Ponieważ w polach słownikowych nie ma opcji nowe...

**Comment by bpabiszczak** [comment]
TU: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9 ?

**Comment by witer30** [comment]
Blażej, 
Dzięki za odpowiedź ale nie mogę stworzyć nowego pola słownikowego tylko nową wartość... 
Np. dla modułu kontakt są 4 kategorie i mogę tylko w tych kategoriach się poruszać a ja potrzebowałbym dodać nową taką kategorię...
Dnia 15 października 2015 21:23 Błażej Pabiszczak napisał(a):
 Closed #2062.—

**Comment by florek41** [comment]
Błażej podał dobre linki tylko kolejność odwrotna - najpierw tworzysz, później możesz edytować, spójrz: 
![picklist_tutorial](https://cloud.githubusercontent.com/assets/4824588/10561419/0ad5bcb6-7528-11e5-9518-e7aca2e5e3a2.gif)

**Comment by bpabiszczak** [comment]
Nie sądziłem, że kolejność może wprowadzić w błąd ;P Dzięki za filmik...

**Comment by witer30** [comment]
dziękuję... przyznam że próbowałem tego ale nie sądziłem że wartości pola słownikowego można tak dodawać i po dodaniu pojawią się w module Pola słownikowe... 
Ok mam nauczkę żeby pogrzebać bardziej zanim coś napiszę... Przepraszam za problem
Dnia 17 października 2015 23:38 Bartek Florczak napisał(a):
 Błażej podał dobre linki tylko kolejność odwrotna - najpierw tworzysz, później możesz edytować, spójrz:
