### ISSUE TITLE
Error!!! SQLSTATE[42000]: Syntax error or access violation:

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2063]
When I click on Email, then click on the magnifying glass icon, the popup module displays this error message:

Error!!!
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND vtiger_project.projectid > 0 ORDER BY projectname ASC LIMIT 0,21' at line 1

**Comment by bpibiza** [comment]
I have the same problem: error comment is as follow: SQLSTATE[42000]: Syntax error or access violation: 1064 Something is wrong in your syntax obok 'AND vtiger_potential.potentialid > 0 ORDER BY potentialname ASC LIMIT 0,21' w linii 1

**Comment by bpabiszczak** [comment]
VERSION?

**Comment by PercyP** [comment]
2.3.16

**Comment by bpibiza** [comment]
the same version. 
When You click "plus" button (adding new record) everything is ok, but searching button occurs the error

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
Please send a description how to invoke an error screenshots

**Comment by PercyP** [comment]
Hi,

in my case it was as I stated:

1. Go to Roundcube email
2. Open an email in the Inbox
3. Choose one of the modules i.e. Leads to create a relationship 
4. Popup window appears with the error message and 2 buttons
![yetierro](https://cloud.githubusercontent.com/assets/10598886/10559999/1a3cdad2-74f5-11e5-83f5-3d2b81482691.png)

Is that what you mean?

**Comment by mariuszkrzaczkowski** [comment]
Did you check the https://gitdeveloper.yetiforce.com/ ?
![mail](https://cloud.githubusercontent.com/assets/10198654/10560062/c8d91d6c-74ff-11e5-8a4c-491437e10bb6.png)

**Comment by PercyP** [comment]
I have just checked. It works properly on there. Is there a difference?

How do I fix it?

**Comment by agilisgmbh** [comment]
Same error with v2.3.16

**Comment by PercyP** [comment]
I have created an additional Issue #2086 as it seems to produce a similar error for all instances of Member Of in Accounts and elsewhere when you use the browser search icon in the Member Of field.

**Comment by mariuszkrzaczkowski** [comment]
The bug has been fixed in the latest version
https://github.com/YetiForceCompany/YetiForceCRM/releases
