### ISSUE TITLE
[bug] you cannot change the admin profile in YF2.3.16

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#2064]
On a new installation YF2.3.16, the admin cannot change his profile
also see https://gitmaster.yetiforce.com

![error](https://cloud.githubusercontent.com/assets/10259801/10526031/8d63ec26-7388-11e5-91fa-6f18723c54aa.JPG)

I hope someone remember my comment: https://github.com/YetiForceCompany/YetiForceCRM/issues/1760#issuecomment-130824290 ;-)

SkavenKF

-----------------
Weeks of programming can save you hours of planning.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2039
