### ISSUE TITLE
Unable to add users Error!!! Permission denied

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2065]
When I try to add a new user I get the following error

 Error!!!
Permission denied

If I try to access my own user details I also get the same error. I am using version 2.3.16

**Comment by SkavenKF** [comment]
2 minutes faster ;-)

**Comment by PercyP** [comment]
I just tried it on your test version and I get the same error there if it helps

**Comment by witer30** [comment]
solution
https://github.com/YetiForceCompany/YetiForceCRM/commit/29a8c8e4f7309257b8023019ab2508cc8d958ddb

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2039
