### ISSUE TITLE
[Question] Mail scaner 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2067]
Short question. 
I have some emails which already have been checked. And now I create account / contact. Does mail scanner rechecked all mails to bind some of them with new contact/account?
I guessing not but is it possible to implement such rescan manually? 

and other question...
What in case if I delete mail form mailbox? I assume that it will not be deleted form CRM... 
thanks

**Comment by bpabiszczak** [comment]
Rescan: https://gitdeveloper.yetiforce.com/index.php?module=OSSMailView&view=List&parent=84 [use  tool Actions > Assign emails

Delete mail not work. U should clear this tabel: vtiger_ossmailscanner_folders_uid

**Comment by witer30** [comment]
thanks, clear
