### ISSUE TITLE
Question: Account number

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2068]
In our business, once you become a customer, an account number is created. 

How can I create a field where that account number can relate to tickets, contacts, service contracts etc. This account number is as important as business babe.

One account can have many account numbers. 

One account number can have many contacts, etc?

I'm looking for ideas on how to structure the system please

**Comment by bpabiszczak** [comment]
But why do you need this number? To search by it, or something else? If you want to search by it and see it next to the Account's name, then it's enough that you add a field in field editor, and then set this field in search configuration here:  https://gitdeveloper.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=2&fieldid=56

**Comment by amicheals** [comment]
It is mainly for attaching tickets, contacts, assets, and service contacts. It's the primary key for importing accounts and contacts tickets etc so everything maps correctly.

**Comment by amicheals** [comment]
I was able to work this out by using the service contracts module. I made the service contract subject my account number. That way it's searchable and linkable.
