### ISSUE TITLE
[Improving] Left and Right Panel Hide

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2069]
You can also add the ability to hide the right panel in the calendar, in future versions

![animation 159](https://cloud.githubusercontent.com/assets/1402355/10532939/0eebcb70-73dd-11e5-83c0-fbd55b8a1afc.gif)

**Comment by bpabiszczak** [comment]
https://layout.yetiforce.com/index.php?module=Calendar&view=Calendar&parent=44 [admin/admin]

**Comment by witer30** [comment]
very nice...
Dnia 30 października 2015 0:55 Błażej Pabiszczak napisał(a):
 https://layout.yetiforce.com/index.php?module=Calendar&amp;view=Calendar&amp;parent=44 [admin/admin]—
