### ISSUE TITLE
Version 2.3 Service

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2075]
Hello,
We have different types of products and services.
A type of service we have is charged on a percentage basis.
for ex.

Name: Service Name 1
Price: 2.0%

Can I change the field in Service name to a percentage? If that is done will that affect any other module like products?

I add a field called "Percentage rate". But that custom field does not show up in calculations. 

Does this need to be developed as a custom addon?

**Comment by amicheals** [comment]
I am thinking of creating a new module for products. 
Duplicate the products module and create a new field for my percentage. Then I can delete or add any fields I need. How do I duplicate a module with another name? @bpabiszczak

**Comment by bpabiszczak** [comment]
Q: Can I change the field in Service name to a percentage? If that is done will that affect any other module like products?
A: NO

Q: Does this need to be developed as a custom addon?
A: developer

Q: I am thinking of creating a new module for products. 
A: This is a very very very bad idea.
