### ISSUE TITLE
[improvement] notification 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2076]
in case of any notification a sound signal could be usefull as not continuously user can look into crm... 
![image](https://cloud.githubusercontent.com/assets/11491482/10551632/4598baea-744e-11e5-9715-5793c9712b9a.png)

**Comment by eptapsyxos** [comment]
+1

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/4f222576cf619c61239deb59a4fa140ec0bc485f
