### ISSUE TITLE
[Question] Multiple eMail Accounts

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2077]
I'm trying to setup multiple email accounts for some of our users.  I've gone into RoundCube Identities and set them up there, but they don't show in YF.  Any help please.  cheers.

**Comment by bpabiszczak** [comment]
1. Identities [in roundcube] is used to specify the SMTP accounts [when we create an email]
2. AutoLogin is used for configuring mailboxes that we want to log in independently from the menu bar: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Mail&view=Autologin&block=8&fieldid=78

To be honest – your description is quite vague, I don't really know what you mean exactly. Read this article carefully:  https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by mykljohn** [comment]
Hi, thanks for the quick response.  For example, my boss has 3 email accounts than he needs to access and only he accesses.  The Sales Manager has 3, one for Sales, one for Info, and his personal email.  The Customer Service clerks have 2 and the HR person has 3.  In Outlook, we automatically log into all of the accounts.  I understand the Auto Login, but I can't add another email account that someone hasn't logged into.  Do We need to log into an account, log out, log into the next account, log out and then log into the 3rd?  I don't want to tell them to do this unless it works.  I will create 2 test email accounts for myself to check this.

**Comment by bpabiszczak** [comment]
Here is the solution to your problem: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Mail&view=Autologin&block=8&fieldid=78

**Comment by mykljohn** [comment]
But there is only one email account...I don't need one account with multiple users, I need 1 user with multiple accounts

**Comment by bpabiszczak** [comment]
Do you know how add new email account?
