### ISSUE TITLE
Nie moge dodać userów

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#2079]
Zainstalowałem yetiforce w wersji 2.3.16 na dwóch różnych serwerach i na obu mam taki sam błąd przy próbie dodania użytkownika ( gdy klikam na + dodaj uzytkownika) pojawia sie błąd !!! brak uprawnień

**Comment by witer30** [comment]
tu masz rozwiązanie
https://github.com/YetiForceCompany/YetiForceCRM/commit/29a8c8e4f7309257b8023019ab2508cc8d958ddb
Dnia 17 października 2015 16:13 mmstrzelec napisał(a):
 Zainstalowałem yetiforce w wersji 2.3.16 na dwóch różnych serwerach i na obu mam taki sam błąd przy próbie dodania użytkownika ( gdy klikam na + dodaj uzytkownika) pojawia sie błąd !!! brak uprawnień—

**Comment by mmstrzelec** [comment]
Dzieki
