### ISSUE TITLE
Strict Standards in php 5.4

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#208]
Fix please! In php5.2 and 5.3 was normal, and now here is the php 5.4 here
![strictstandards](https://cloud.githubusercontent.com/assets/1402355/6123531/b0dd4f6a-b125-11e4-8c5d-bbe8d7b23538.JPG)

**Comment by mariuszkrzaczkowski** [comment]
What kind of operation performed that appeared to you this message?

**Comment by waw555** [comment]
I switched from version 5.2 to version 5.4 when installing YetiForceCRM, now is, of course, you can set in the file htacces line php_flag display_errors off and then everything will work.
