### ISSUE TITLE
[improvement] Pole województwo - moduł kontakty, leady, kontrahenci 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2080]
Dodać to pole jako pole słownikowe z możliwością wyboru województwa z listy...

**Comment by florek41** [comment]
Może i w Polsce miałoby to rację bytu ale jako, że system jest 'ogólnoświatowy' to musi być jakiś inny sposób ;)

**Comment by bpabiszczak** [comment]
Ja tam z listami nie mam problemu, tylko przygotujcie mi dla 180 krajów poszczególne regiony :dancers:

**Comment by florek41** [comment]
Dokładnie o tym mówię - jeśli wprowadzać to dla wszystkich, a nie tylko PL :)

**Comment by witer30** [comment]
przepraszam, macie racje jeśli chodzi o ten punkt widzenia...
nie pomyślałem
Dnia 17 października 2015 23:30 Bartek Florczak napisał(a):
 Może i w Polsce miałoby to rację bytu ale jako, że system jest 'ogólnoświatowy' to musi być jakiś inny sposób ;)—

**Comment by witer30** [comment]
jak pisałem, przepraszam nie pomyślałem o międzynarodowości systemu...
Dnia 18 października 2015 0:01 Błażej Pabiszczak napisał(a):
 Ja tam z listami nie mam problemu, tylko przygotujcie mi dla 180 krajów poszczególne regiony —

**Comment by bpabiszczak** [comment]
Dla ułatwienia podpowiem, że są już w systemie [w wersji testowej] mechanizmy integrujące z Google Maps i z Open Street Maps które wypełniają same pola, niestety nie są one doskonałe, ale ułatwiają wpisywanie danych...

**Comment by witer30** [comment]
Fajnie,
a czy to oznacza ze pracujecie nad czymś podobnym do geomaps jak do vtigera - wskazuje lokalizacje kontaktów...
Dnia 18 października 2015 21:47 Błażej Pabiszczak napisał(a):
 Dla ułatwienia podpowiem, że są już w systemie [w wersji testowej] mechanizmy integrujące z Google Maps i z Open Street Maps które wypełniają same pola, niestety nie są one doskonałe, ale ułatwiają wpisywanie danych...—

**Comment by florek41** [comment]
Z tego co sprawdzałem to o niebo lepiej działa to dla zagranicy niż dla PL :)

**Comment by bpabiszczak** [comment]
ale które Google Maps czy OSM?

**Comment by bpabiszczak** [comment]
GeoMaps służy do zupełnie czegoś innego.

**Comment by witer30** [comment]
a planujecie coś takiego...
fajna opcja która by pobiła wszystko to wyznaczeni trasy od A do Z i odszukanie wsyzstkich kontaktów w określonej odległości od tej trasy...
Dnia 19 października 2015 11:24 Błażej Pabiszczak &lt;notifications@github.com&gt; napisał(a):
GeoMaps służy do zupełnie czegoś innego.—

**Comment by bpabiszczak** [comment]
mieliśmy kiedyś moduł OSSMap za nim jeszcze GeoMap się pojawił, działał na Vtiger 5.4, na chwilę obecną nie jest to nasz priorytet...
