### ISSUE TITLE
[Qustion] - visibility of user records  

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2081]
Dear,
Can you be so kind and help to adjust visibility of record for user.
Let's say that I have 3 users. User 1 is member of Board managing. User 2 is a member of selling team. User 3 is member of other group. 
I need:
a. user 1 have access to all records
b. user 2 has access to his records plus record of user 3
c. user 3 has access to only to his records... 

I tied to play with roles without success... 
Do i need to set every module accordingly to my wish...?
the same rules i need to apply to binded emails. how I can set it up? 

Thanks a lot for help

**Comment by amicheals** [comment]
@witer30 

I was able to control user records by:
settings > User & Access control > Access to Records

For user 1 Choose profile and make that profile have access to all records regardless of Role
![image](https://cloud.githubusercontent.com/assets/11178457/10577064/f6cbdca0-7635-11e5-9881-1cbfa26a5a00.png)


If a suitable profile is available, you can choose it, if not then you will need to create it.

For User 2 Create a Role and fine tune role permissions on
settings > user & Access Control > Roles
Choose the role you would like to edit

For the Privileges option Choose: Assign privileges directly to role
For the Can Assign Records To: Choose
  Users having Same Role or Subordinate Role

![image](https://cloud.githubusercontent.com/assets/11178457/10577154/b7e725ac-7636-11e5-8e53-d03e442553a2.png)

Here you can choose what modules this role has access to.
You can choose if they can view, edit or delete values in each module

If you click the arrow next to Field and Tool privileges, you can choose determine what fields that role can view/edit.

Make User 3 a subordinate role of User 2 under

System Settings > User & Role > Roles

Drag or create a profile under user 2 profile

Try that and see if it works.

**Comment by bpabiszczak** [comment]
Thank you @amicheals
