### ISSUE TITLE
How to add a value from a related module's field in a custom module

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2082]
Hi,

I have create a new custom module and have created a 1:m field in it that is connected to Contacts. I am not sure if what I want to do is possible, but basically in my custom module, if I select a Contact from the 1:m Contacts field, I want it to populate another field with whatever value is in the corresponding field in my selected Contact's record. 

What I have tried so far is:

1. In Edit fields I have selected my Custom Module
2. I select Add Custom Field
3. I select the field type as Values from the related module
4. I add the values to the mandatory boxes
5. I selected the Related Module - nothing is displayed
6. There are also no fields to select from Related Field either

All I basically want to do is pull the Contact's age into my new form record. What step am I missing here? Is this the correct steps to do this?

I cannot find any documentation on how to do this - hence asking here.

Regards

Percy

**Comment by florek41** [comment]
What you want to do isn't possible form admin panel - you can do it only from code - if you want to display it in other place than list view.

with **Values from the related module** ( #1992 ) you can search and filter by this field.

**Comment by PercyP** [comment]
Ah so that is a search and filter field. I see. 

Thanks for response I will try and think of doing what I need another way :)
