### ISSUE TITLE
[BUG] v2.3 can't add users

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2083]
Tried two installs of a clean 2.3 and both can't add users.  
Went back to v2.2 and upgraded to 2.3 and all is fine. 
Tred both PHP 5.5. and 5.6 and the server check ticks all boxes. 

When clicking the button add user, I get a permission denied. (as admin) I get the same error when trying to edit my own (admin) user account.

Would be good to know if more people get this with a fresh install.

**Comment by kpaulaha** [comment]
Works ok with my fresh installs 2.3.16  and updates

**Comment by SkavenKF** [comment]
Look at https://github.com/YetiForceCompany/YetiForceCRM/issues/2064

**Comment by zebrahosting** [comment]
The interesting part is that the upgrades all work fine. To me it seems the installer does something (not) funny.
