### ISSUE TITLE
Nie mogę nic wyszukać

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#2084]
czy to brak odpowiedniej konfiguracji czy błąd. Kopiuje kawałek nazwy Lead-a wklejam w okno wyszukiwarki klikam lupe i 0 znalezionych. Właściwie cokolwiek wpisze niczego nie wyszukuje?

**Comment by bpabiszczak** [comment]
Pewnie importowany? 
Zerknij tutaj: https://gitdeveloper.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=2&fieldid=56
