### ISSUE TITLE
Error!!! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND vtiger_account.accountid > 0 ORDER BY accountname ASC LIMIT 0,21' at line 1

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2086]
Hi, 

I have just noticed that when I click on the Member Of within the Accounts I get this error:

Error!!!
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND vtiger_account.accountid > 0 ORDER BY accountname ASC LIMIT 0,21' at line 1

I have tried to do the same on your demo site and do not get this error.

Regards

**Comment by bpabiszczak** [comment]
Duplicate
