### ISSUE TITLE
Fatal error: Can't use method return value in write context in /home2/jballest/public_html/solarcrm/modules/Users/models/Record.php on line 284

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2087]
New YetiCrm version 2.3.16 present this error: Fatal error: Can't use method return value in write context in /home2/jballest/public_html/solarcrm/modules/Users/models/Record.php on line 284.

Is a fresh install php 5.4.

Please help me.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/29a8c8e4f7309257b8023019ab2508cc8d958ddb
