### ISSUE TITLE
[improvement] Payments In and Out Modules

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2088]
The Payments In module does not have a Related Tab to the Accounts or Invoice modules. 

The Payments Out module does not have a Related Tab to the Vendor module.  

These would be very logical and helpful additions.

**Comment by amicheals** [comment]
@mykljohn I am using version 2.3 and I have a related tab to accounts and invoices in payments in
![image](https://cloud.githubusercontent.com/assets/11178457/10671247/998b6b44-78b7-11e5-8473-11aed38118c1.png)

**Comment by mykljohn** [comment]
I may have stated it incorrectly, Yes you can enter the related Invoice and Account (which should be automatically loaded from the Invoice) But there are no Right Menu links to Accounts or Invoices:

![image](https://cloud.githubusercontent.com/assets/11919990/10672038/4ac000be-78b3-11e5-8d14-a210abe5eb86.png)

**Comment by amicheals** [comment]
@mykljohn 
I think if you edit fields in the Accounts module and add related field 1:M related field to Payments In, I think Accounts will show up on the side. For the related tab to show, I think the field needs to have the related field on both modules.

**Comment by mykljohn** [comment]
@amicheals Ahhh, good to know...I try that.  cheers
