### ISSUE TITLE
Issue while debugging

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2090]
When I turn on 'SQL_LOG_INCLUDE_CALLER' => true in /yeti/config/performance.php

only a blank screen is displayed.  using YF 2.3

**Comment by bpabiszczak** [comment]
This functionality is new, its used for logging queries to the log table [l_yf_sqltime]. In the current version the functionality works properly, today we are releasing the update package and you will be able to check it for yourself.

**Comment by mykljohn** [comment]
great, thanks

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip

**Comment by mykljohn** [comment]
I ran the upgrade and got this error:

Database ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'globo_yeti_tst.s_yf_multireference' doesn't exist
Query: SHOW COLUMNS FROM `s_yf_multireference` LIKE 'type';
#0  PearDatabase->checkError() called at [/home1/globo/public_html/yeti_test/include/database/PearDatabase.php:326]
#1  PearDatabase->query() called at [/home1/globo/public_html/yeti_test/cache/updates/init.php:142]
#2  YetiForceUpdate->databaseSchema() called at [/home1/globo/public_html/yeti_test/cache/updates/init.php:100]
#3  YetiForceUpdate->update() called at [/home1/globo/public_html/yeti_test/vtlib/Vtiger/PackageImport.php:1015]
#4  Vtiger_PackageImport->import_update() called at [/home1/globo/public_html/yeti_test/vtlib/Vtiger/PackageImport.php:590]
#5  Vtiger_PackageImport->import_Module() called at [/home1/globo/public_html/yeti_test/vtlib/Vtiger/PackageImport.php:543]
#6  Vtiger_PackageImport->import() called at [/home1/globo/public_html/yeti_test/modules/Settings/ModuleManager/views/ModuleImport.php:134]
#7  Settings_ModuleManager_ModuleImport_View->importUserModuleStep3()
#8  call_user_func_array() called at [/home1/globo/public_html/yeti_test/include/runtime/Controller.php:84]
#9  Vtiger_Controller->invokeExposedMethod() called at [/home1/globo/public_html/yeti_test/modules/Settings/ModuleManager/views/ModuleImport.php:32]
#10 Settings_ModuleManager_ModuleImport_View->process() called at [/home1/globo/public_html/yeti_test/include/main/WebUI.php:220]
#11 Vtiger_WebUI->process() called at [/home1/globo/public_html/yeti_test/index.php:25]
