### ISSUE TITLE
Błąd masowego usuwania maili firmowych po zaznaczeniu wszystkiego

### ISSUE THREAD

**Issue by cedeka78** [YetiForceCompany/YetiForceCRM#2091]
ver 2.3.45
błąd przy próbie masowego usunięcia maili z bazy maile firmowe
Przy zaznaczeniu pojedynczych maili lub maili z całej pojedynczej strony usuwanie działa poprawnie.
Problem pojawia się po wybraniu opcji Zaznacz wszystko Maile firmowe (tej na żółtym pasku).
Błąd wywołany na wersji testowej
https://test.yetiforce.com/index.php?module=OSSMailView&parent=&page=1&view=List&viewname=50&orderby=&sortorder=&search_params=&search_key=subject&search_value=
W załączeniu zrzut ekranu z konsoli
![masowe_usuwanie](https://cloud.githubusercontent.com/assets/15181660/10573777/3cc0ab16-7652-11e5-8de6-4ec3f6d2691f.jpg)

**Comment by bpabiszczak** [comment]
<b>Fatal error</b>:  Call to undefined method OSSMailView_Record_Model::deleteAllRecords() in <b>/home/yetiforce1/domains/test.yetiforce.com/public_html/modules/OSSMailView/actions/MassDelete.php</b> on line <b>43</b><br />
app.errorLog @ app.min.js:2
List.js:283 Error: parsererror
