### ISSUE TITLE
[BUG] Unable to install

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2092]
After I upload all yeti files and folders and after I direct browser to yeti directory I get blank screen.
I tried this with 2.3.43 and 2.3.45 versions (developer).
I installed yetiforce many times before and everything was OK

**Comment by florek41** [comment]
On fresh install 2.3.49 still exist.

while debugging i've go same error as #2087

**Comment by mariuszkrzaczkowski** [comment]
For me working properly
I attach the video below
We need more information
![install](https://cloud.githubusercontent.com/assets/10198654/10689363/f62be946-797a-11e5-9158-d33ee379e8a1.gif)

**Comment by nikdejan** [comment]
On which version does it work?

**Comment by mariuszkrzaczkowski** [comment]
2.3.49

**Comment by nikdejan** [comment]
My PHP version is 5.4.24. Is that a problem?

**Comment by mariuszkrzaczkowski** [comment]
Try to install the latest version from the developer
https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by mariuszkrzaczkowski** [comment]
So it was a problem with your version of PHP
We have introduced several amendment and already it should work

**Comment by florek41** [comment]
i've just test it on same server as previous and dev. version works like a charm !

**Comment by nikdejan** [comment]
I can confirm it works! Developer 2.3.88, PHP 5.4.24. Thanks guys!
