### ISSUE TITLE
Create project / service contract from opportunity

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#21]
In order to implement YetiForce for end-to-end client management, it would be great if there would be a function that transforms an opportunity into either a project or a service contract, the two objects that could result from a successful opportunity.

**Comment by bpabiszczak** [comment]
I understand that you try to create a universal mechanism aimed to create relations and copy data between them. Your idea is good in general, but it has no business justification. Every process is different; various relations exist and show various data depending on a situation. Some of the things are configured rigidly (e.g. mysql foreign key so search can work faster). It is impossible to eliminate a developer from a CRM project and it seems as if you are trying to achieve that.

This Issue should be closed in my opinion. You’re describing some kind of idea, but not a logically proven requirement / business functionality.
