### ISSUE TITLE
How to set up autologin to the OSSMail

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#210]
I can not adjust to autologin to the OSSMail, all the time necessary to enter username and password to log in to post. And if you change the user without leaving the mail, it will be almost another user.

**Comment by waran70** [comment]
Would be good. For now it is feeling that Roundcube is not completely integrated with CRM.

**Comment by bpabiszczak** [comment]
In order for the auto login to work properly, the following steps are necessary:

Correct configuration of the server with all required libraries installed. [https://test.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=9&fieldid=65]
Enable auto login in configuration [https://test.yetiforce.com/index.php?module=OSSMail&parent=Settings&view=index&block=8&fieldid=36]
Connect mailbox (it’s enough to login to it) and assign a user: https://test.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=index&block=8&fieldid=44
If it doesn’t work, it is necessary to check in logs why the auto login is not working (e.g. incorrect certificate). We use auto login and it works all right.

If it isn’t working on your installation, try to configure it on test.yetiforce.com on gmail test account and let us know, we will verify at which point you make a mistake.

**Comment by waw555** [comment]
Everything turned out, I do not have a user in the mail scanner, and now have earned autologin. Thank U!
