### ISSUE TITLE
How to create a field like the one in Contacts (dropdown with Accounts, Leads, Vendors)

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2102]
Hi,

I want to create a field in my custom module (exactly like the one in the Contacts form which has a dropdown for Accounts Leads Vendors that changes the input box depending on what is selected).

At the moment I can create a 1:M field type, but I cannot see how I can add more than one module selection in this field as in your form. 

Does this require a different type of field? Are there any instructions for creating theser?

Regards

**Comment by bpabiszczak** [comment]
You must use vtlib or add manually in DB [check this table: `vtiger_fieldmodulerel`].
Who will help you as you damage your system?

**Comment by mariuszkrzaczkowski** [comment]
![uitype10](https://cloud.githubusercontent.com/assets/10198654/10688105/22fb1248-7972-11e5-9b45-5980284348eb.png)
