### ISSUE TITLE
Loader zawiesił się

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#2108]
Podczas edycji Właściciela rekordu - zawiesił się

![299](https://cloud.githubusercontent.com/assets/11139594/10579353/da094462-7677-11e5-8893-eb87b66d44e6.png)

**Comment by rskrzypczak** [comment]
![privileges2](https://cloud.githubusercontent.com/assets/10221999/10810476/b3f1aad0-7e01-11e5-8ebe-ca1ac4c1e05e.gif)

..\modules\Vtiger\handlers\SharingPrivileges.php (line 35)
'....
Users_Privileges_Model::setSharedOwnerRecursively($recordId, [] , $addUsers, $moduleName);
...'
$addUsers jest równe null, a musi być tablicą. Brak przekazania do niej wartości.
