### ISSUE TITLE
Creating alternative mandatory field type during module creation

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2109]
When creating a new module, is it possible to create an alternative field type (other than default text box) or at least be able to delete it and replace it with another mandatory field of an alternative type? 

I have a custom module called Relationships, which only requires two 1:M fields, a picklist and a date field. I realise my module needs a mandatory field, so was hoping I could use the first picklist field as this. Is this possible? 
I cannot find a way of disabling the Mandatory field that has to be created when building new modules. I have tried doing this in the Edit fields section, firstly by creating an alternative mandatory field, then trying to disable/delete the one that was originally created. It will not let me delete it.

**Comment by bpabiszczak** [comment]
Use vtlib: http://community.vtiger.com/help/vtigercrm/developers/extensions/examples/entity-module.html
Or change uitype manually [if you know what you're doing]. 
If you mess up, it's only possible help is payable ;)
