### ISSUE TITLE
report can not get total and subtotal from invoice、sales order

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#2110]
I created a report based on invoice
the total、sub total、received always returns value 0.

sorry， i can not upload image right now.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
version?

**Comment by zelphar** [comment]
2.3.49

**Comment by bpabiszczak** [comment]
This module will be removed in version 2.4 and replaced with a new one. More info here: #2461
