### ISSUE TITLE
PDF- nowy moduł - pobranie listy produktów

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2112]
Witam, czy jest szansa na jakiś wzór przykładowej funkcji do wygenerowania "listy produktów" stworzonych za pomocą "nowego modułu" w trybie rozszerzonym ?

**Comment by bpabiszczak** [comment]
ale mówimy o nowym module PDF czy o starym module PDF ?

**Comment by zimart** [comment]
Pozwoliłem sobie zerknąc na nowy - chociaż nie jestem szczęśliwym posiadaczem - ale póki co nie widzę takiej funkcjonalności :( może istnieje gdzieś w czeluściach wzór - jak powinna wyglądać funkcja pobierająca dane w postaci tabeli - do starego PDF-a ?

**Comment by bpabiszczak** [comment]
Do starego chyba nie istnieje, bo obecnie moduł ten jest w wersji testowej... Nowy PDF powinien już mieć a jak nie ma będzie miał jutro/pojutrze.

**Comment by zimart** [comment]
Czyli pozostaje uzbroić się w cierpliwość :) Chociaż to niełatwe. Czy nowy będzie wkrótce dostępny ?

**Comment by bpabiszczak** [comment]
Można go testować tutaj: https://pdf.yetiforce.com/ [admin/admin] dostępny w konfiguracji.
