### ISSUE TITLE
Brak funkcji - własny moduł

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2113]
Bug - przy utworzeniu nowego modułu - próba wybrania podatku indywidualnego - 

Fatal error: Class 'Vtiger_Taxs_UIType' not found in /home/yetiforce1/domains/test.yetiforce.com/public_html/cache/templates_c/vlayout/cc5178daecc350e4bd2486d0af6c0b3533047447.file.InventoryTaxesType1.tpl.php on line 41

No i niestety źle przeliczane podatki - po zapisie ucina 

Ps. Wypełnienie własnych pól zaczęło działać pod mozillą - wcześniej były nieaktywne - pod np Chromem było OK.

**Comment by bpabiszczak** [comment]
Tylko nie bardzo wiem co mam z tym zrobić, brak podstawowych informacji, przeczytaj to: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html
