### ISSUE TITLE
Błąd przy próbie dodania Pracownika

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#2114]
Przy próbie dodania pracownika pojawia się błąd: Błąd!!!
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND vtiger_ossemployees.ossemployeesid > 0 AND vtiger_ossemployees.employee_stat' at line 1

yetiforce wersja 2.3.20

**Comment by bpabiszczak** [comment]
na wersji developerskiej lub testowej błąd się pojawia?

**Comment by mmstrzelec** [comment]
Sorka nie wiem o co pytasz. Sprawdzałem na Waszym demo i tam sie nie pojawił a u mnie tak

**Comment by bpabiszczak** [comment]
Jeżeli nie wiesz o co pytam, to przeczytaj to: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html

Stable: https://test.yetiforce.com
GitMaster: https://gitmaster.yetiforce.com/
GitDeveloper: https://gitdeveloper.yetiforce.com

**Comment by mmstrzelec** [comment]
pomimo tego błędu dane zapisują sie poprawnie

czy plik do aktualizacji z 2.3.26 ma poprawną nazwę? bo jest tam 2.2.16_to_2.3.49

**Comment by bpabiszczak** [comment]
hmm 2.3.26? A pobrałeś ten system z Github czy z SourceForge? Przeczytaj ten artykuł, napisane tam jest jak uaktualnić z "nietypowej" wersji: https://yetiforce.com/pl/wdro%C5%BCeniowiec/instalacja-aktualizacja/174-aktualizacja-yetiforce-crm.html
