### ISSUE TITLE
Creating New Webforms

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2115]
Any way to link the Project module to the webforms? 
![webform-for project module](https://cloud.githubusercontent.com/assets/1903662/10593967/2eb911ea-7696-11e5-9706-f8bc1af46e31.jpg)

**Comment by bpabiszczak** [comment]
use programmer ;)

**Comment by jbmcclain** [comment]
Understandable.. hopefully I will be able to figure it soon. Thanks again !
