### ISSUE TITLE
can set assign to automatic to user when create entity in workflow

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#2116]
I wanna to setup a workflow after user save a assets, automatic create a entity in its related module.
but the assign to field can only set a fixed user.
can we let this to be the user save the record?
![image](https://cloud.githubusercontent.com/assets/15126825/10596316/9dd53214-7715-11e5-9756-077cbe799001.png)

**Comment by paula-w** [comment]
It will be added in version 2.5

**Comment by paula-w** [comment]
I'm closing the issue, you can learn more about submitting new ideas and issued labeled as "ignored" from these two articles:
1. https://yetiforce.com/en/github/issues/206-system-development-ideas.html
2. https://yetiforce.com/en/github/issues/205-why-was-the-issue-ignored.html
