### ISSUE TITLE
Update packages - Wrong version number - 2.4.49 instead of 2.3.49

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2117]
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip

only in file names - system show correct.

or we have earlier update to 2.4 ? ;)

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/UpdatePackages/commit/7e8283352efcd7931c276937519af1ef29d7a77b
