### ISSUE TITLE
Błąd w Kontaktach

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#2118]
Na mojej instalacji wersja 2.3.49 gdy kliknę w kontakty pojawia się błąd:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'addresslevel5a' in 'field list'

nie pojawaia się on w wersji testowej

**Comment by bpabiszczak** [comment]
ale co klikniesz? 
skoro nie działa coś, to należy sprawdzić logi: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/109-debugowanie.html
