### ISSUE TITLE
How to create custom widget in yetiforce crm 2.2.0

### ISSUE THREAD

**Issue by koeaoe** [YetiForceCompany/YetiForceCRM#2119]
Hello, i am trying to create widget in yetifoce crm 2.2.0. I insert record to vtiger_links( with my custom linkurl), vtiger_module_dashboard and vtiger_module_dashboard_widget. Now i see link in dropdown menu "Add widget". After add widget to dashboard i see only  empty box. Is any way to creating the same but with default yetiforce widget ui like close button etc ?

**Comment by TomaszQr** [comment]
How to add a custom widget:

1. Add an entry to the “vtiger_links”, where:
→ linktype – "DASHBOARDWIDGET",
→ linklabel – the name visible in the system,
→ linkurl – widget's URL 
eg. index.php? module=Accounts&view=ShowWidget&name=History
→ module – name of the module
→ view - always ShowWidget
→ name – name of the widget (any)

2. Create “widget name”.php file in  /modules/"module name"/dashboards/
(If it doesn't exist you have to create it)

3. Add class Module name_Widget name_Dashboard inheriting after Vtiger_IndexAjax_View

4. Create a public function process in the class, where you'll get the data to display.

5. The widget consists of two *.tpl files
for example:

 $content = $request->get('content');
 if (!empty($content)) {
  $viewer->view('dashboards/TimeControlContents.tpl', $moduleName);
 } else {
  $viewer->view('dashboards/TimeControl.tpl', $moduleName);
 }

TimeControlContents.tpl is responsible for displaying the widget content
TimeControl.tpl is responsible for displaying the widget window and its header.
