### ISSUE TITLE
Update from 2.3.16 to 2.4x produces wrong version error

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2120]
Hi,

I am trying to run the upgrade package from 2.3.10 to latest 2.4x but it is producing the following error|:

Wrong version of module, module version 2.3.16 but it should be greater than 2.3.20

Regards

**Comment by bpabiszczak** [comment]
Please read this:  https://yetiforce.com/en/implementer/installation-updates/176-system-update-not-verified.html 

Change manually versions here: https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/config/version.php

**Comment by PercyP** [comment]
Hi brilliant - worked beautifully (and also no longer have other issues identified in 2.3.16 ) :)

Thanks
