### ISSUE TITLE
Mobile App or More Mobile Friendly

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2121]
Is there more of a mobile friendly theme or app that can be used so leads, Opportunities and logging information to an account can be done strait from the phone.  Also a way to sync contacts from yeti to outlook only. by directional task/calendar?

I know there is small work around that i have found using webforms built for each user but it seams a little counter productive.

Thanks!

**Comment by florek41** [comment]
looka at 
#1564 and #1974

**Comment by jbmcclain** [comment]
Sounds great thanks! Awesome feed back!

**Comment by bpabiszczak** [comment]
and check this: https://layout.yetiforce.com/ admin/admin

**Comment by jbmcclain** [comment]
WOW! the first one is awesome on the mobile end!  The second one is doable but the first one is great!!!

**Comment by jbmcclain** [comment]
anyway to test the layout on the current version? just wondering.Thanks!  Also if we go actually jump on board with this anyway to donate
