### ISSUE TITLE
Language in pdf editor

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2122]
The pdf -editor in v 2.3+ do not use the current language in special functions.

![pdf](https://cloud.githubusercontent.com/assets/10330264/10617005/c397f634-7770-11e5-8ab4-7ba4a8cde2ca.png)

**Comment by bpabiszczak** [comment]
We have new PDF module, u can test here: https://pdf.yetiforce.com/ [admin/admin], and here: https://github.com/YetiForceCompany/YetiForceCRM/tree/lab-pdf

**Comment by kpaulaha** [comment]
Great, I will test it.


-------- Alkuperäinen viesti --------
Lähettäjä: Błażej Pabiszczak <notifications@github.com> 
Päivämäärä: 20.10.2015  22.52  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] Language in pdf editor (#2122) 

We have new PDF module, u can test here: https://pdf.yetiforce.com/ [admin/admin], and here: https://github.com/YetiForceCompany/YetiForceCRM/tree/lab-pdf

**Comment by bpabiszczak** [comment]
Translations aren't generated dynamically, but they are predetermined. You can change it but it requires rebuilding a special function. It's not an error, it was designed this way. In the new version you can use labels that are translated to the language specified in a template, but it's predetermined as well. There should be different templates for different languages.
