### ISSUE TITLE
Webform linked to Quote or Quote inquiries

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2123]
Hi,

is it at all possible to have a webform that populates the Quote inquiries module? 

We currently have a quote builder (uses some 3rd party component that isn't linked at all to our CRM). It would be good if we could use a webform instead - so basically a site visitor could select the products or services we offer, which creates a quote inquiry that goes straight in to the Quote Inquiry module in yetiforce.

At the moment the closest thing is Opportunity module but this wouldn't work for us. 

I suppose this is a feature request/wishlist?

Regards

Percy

**Comment by bpabiszczak** [comment]
I think webforms will be removed from the system. Instead of that API will be availabe (it's being built for Portal2).

We are not planning to add the functionality you described.
