### ISSUE TITLE
Customer portal - no email

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2124]
I am just trying out Customer Portal and have followed the instructions as follows:

1. uploaded and extracted Customer Portal to root of my public_html alongside yeticrm

2. Gone in to portal/config/config.php and added the link to the crm as follows:
$vtiger_path = "http://www.mysite.com/yeticrm/"; (because when I open the crm in my browser that is the path as it appears

3. Deleted the // in yeticrm/config/api.php so it now looks like:
//List of active services. To enable you must uncomment the appropriate line.

$enabledServices = [
	'mobile',
	'yetiportal',
	'dav',
	'webservices',
	'mobileModule',
	'webservice',

4. Opened Workflows and then open Generate Customer Login Details and accepted the settings until it displayed the Active box and ticked it the clicked Finish

5. Did the same for Send Customer Login Details and activated the 2 boxes just before click Finish

6. Setup Outgoing Server then went to email to test send and receive - both worked

7. Went to Contacts and created a news contact - ticked permission to send mail and entered email address

8. Clicked is portal user and selected the language then clicked Save

9.; Checked URL for portal - shows login box fine

10.  Opened my external email client and clicked Send/Receive to see if portal details arrived. Nothing - no email. Tried this a number of times now and still nothing

Is there a missing step needed to get it working?

**Comment by mariuszkrzaczkowski** [comment]
Tested and working properly.
Uncomment the line and check what is the message.
https://github.com/YetiForceCompany/YetiForcePortal/blob/master/portal.php#L210

![portal](https://cloud.githubusercontent.com/assets/10198654/11476364/a232253c-9782-11e5-9bae-1142b7879ef7.gif)

**Comment by rprice1978** [comment]
Still not working for me, can any one help

**Comment by mariuszkrzaczkowski** [comment]
Add new issue
