### ISSUE TITLE
Pytanie filtr Lead

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#2125]
Witam
jak z filtru zdrfinoeanego na LEAD-ach zaciągnąc Lead-y do kampanii?
Jestem w kampanii w prawym menu klikam lead wybieram wcześniej zdefiniowany flitr zaznaczam wszystkie wyswietlone rekordy i tu nie wiem co dalej?

**Comment by mmstrzelec** [comment]
Nie ma też możliwości kasowania wybranych lead-ów w kampanii

**Comment by mmstrzelec** [comment]
Moim zadniem żeby rozwiazać doraźnie wystarczyło by dodac tę opcję w oknie wyboru Lead-ów
![screen2](https://cloud.githubusercontent.com/assets/15170959/10648583/7944f288-783f-11e5-98cf-90779ef57d61.jpg)

**Comment by bpabiszczak** [comment]
Nie ma podstawowych informacji takich jak wersja systemu, brak informacji z logów, brak informacji o tym czy działa na wersjach testowych. W mojej opinii to co opisujesz działa poprawnie więc zamykam, jeżeli jednak tak nie jest, proszę otworzyć nowy topic i tam prawidłowo opisać błąd.
![camp](https://cloud.githubusercontent.com/assets/10197525/10834731/272431b8-7e9c-11e5-8601-c009adf824e6.gif)
