### ISSUE TITLE
Fatal error: Can't use method return value in write context in /home2/jballest/public_html/solarcrm/modules/Users/models/Record.php on line 284

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2126]
Im still having Fatal error: Can't use method return value in write context in /home2/jballest/public_html/solarcrm/modules/Users/models/Record.php on line 284.  Im using php 5.4.  My webhosting let me upgrade to php 5.5 but if i do that it will have a lot more errors.

I already download every yeticrm 2.3.?? version and every one crash with the same error.

They only version i can install without problem is 2.2.  

Please help with this. Thanks a lot

**Comment by florek41** [comment]
same as #2092 and related (yours) #2087

**Comment by mariuszkrzaczkowski** [comment]
Error has been fixed.
This issue occurs only in versions of PHP 5.4.x

**Comment by easaw** [comment]
add 'AddHandler application/x-httpd-php55 .php' to your htaccess. No Quotes.
