### ISSUE TITLE
WYSIWYG warning error in summary page of ticket version 2.3

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2127]
WYSIWYG

Warning: DOMDocument::loadHTML() expects parameter 2 to be long, string given in /home/www/html/crm/vtlib/Vtiger/Functions.php on line 1112

**Comment by bpabiszczak** [comment]
For me work ok. Version [2.3.?]? PHP?

**Comment by amicheals** [comment]
Version 2.3
![shyetiforce](https://cloud.githubusercontent.com/assets/11178457/10691494/79a3f346-7957-11e5-93de-506eef6b7c5d.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/71fb1d9b963185db2778f024d4c0db1078b79f57
Check the latest version: https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip
