### ISSUE TITLE
[BUG] Pagination

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#2128]
![pagin](https://cloud.githubusercontent.com/assets/10221999/10628272/b87ba2c0-77c3-11e5-8738-e170e2cbf8df.gif)

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/3bb5858fc068ee560c271ffc861c7f8c5afadbc5

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/020e5c2ba23613f7280ac95a588cedcfcf556403
