### ISSUE TITLE
Version 2.3 Project Templates enhancement

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2129]
When creating project templates, is there a way to add tasks to milestones in the template creation.

Right now, You can add Project milestones
Then add tasks, but tasks are not connected to project milestones during the template creation.

Can you add a mechanism to add tasks to the corresponding milestone during project template creation?

**Comment by eptapsyxos** [comment]
It would be very useful.

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
