### ISSUE TITLE
version 2.3 delete a project does not delete project tasks or project milestones

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2130]
I created a project with project tasks and project milestones.
I then deleted the project.
However, the corresponding project tasks and project milestones were not deleted.

Is this by design or a bug?

**Comment by bpabiszczak** [comment]
Q: Is this by design
A: YES

Q: Is this correct?
A: NO

Q: In the future we will change this ?
A: YES
