### ISSUE TITLE
Delete custom module

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2131]
How can I delete a Custom module that I import or create?

**Comment by bpabiszczak** [comment]
Look here: https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8

**Comment by mykljohn** [comment]
But only Call History and List of Calls have a Delete Button.  I imported a custom module, but it doesn't work.  I disabled it, but it still shows up on the menu bar (left menu in studio).  I would like to delete it and start over, but there is no delete button.

**Comment by bpabiszczak** [comment]
Delete button show when in table vtiger_tab.customized u set value: 1. Default for new module created by module manager.

**Comment by mykljohn** [comment]
I set vtiger_tab.customized, but still no delete button.

**Comment by bpabiszczak** [comment]
for me work.

**Comment by mykljohn** [comment]
Great for you, not so much for me :)  Is there anything has has to be set?  

Here my MySQL

![image](https://cloud.githubusercontent.com/assets/11919990/10646629/b6c3aac8-77f9-11e5-9b17-763841243d41.png)

**Comment by mykljohn** [comment]
When I updated to 2.4 I got the following error:

Database ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'globo_yeti_tst.s_yf_multireference' doesn't exist
Query: SHOW COLUMNS FROM s_yf_multireference LIKE 'type';
#0 PearDatabase->checkError() called at [/home1/globo/public_html/yeti_test/include/database/PearDatabase.php:326]
#1 PearDatabase->query() called at [/home1/globo/public_html/yeti_test/cache/updates/init.php:142]
#2 YetiForceUpdate->databaseSchema() called at [/home1/globo/public_html/yeti_test/cache/updates/init.php:100]
#3 YetiForceUpdate->update() called at [/home1/globo/public_html/yeti_test/vtlib/Vtiger/PackageImport.php:1015]
#4 Vtiger_PackageImport->import_update() called at [/home1/globo/public_html/yeti_test/vtlib/Vtiger/PackageImport.php:590]
#5 Vtiger_PackageImport->import_Module() called at [/home1/globo/public_html/yeti_test/vtlib/Vtiger/PackageImport.php:543]
#6 Vtiger_PackageImport->import() called at [/home1/globo/public_html/yeti_test/modules/Settings/ModuleManager/views/ModuleImport.php:134]
#7 Settings_ModuleManager_ModuleImport_View->importUserModuleStep3()
#8 call_user_func_array() called at [/home1/globo/public_html/yeti_test/include/runtime/Controller.php:84]
#9 Vtiger_Controller->invokeExposedMethod() called at [/home1/globo/public_html/yeti_test/modules/Settings/ModuleManager/views/ModuleImport.php:32]
#10 Settings_ModuleManager_ModuleImport_View->process() called at [/home1/globo/public_html/yeti_test/include/main/WebUI.php:220]
#11 Vtiger_WebUI->process() called at [/home1/globo/public_html/yeti_test/index.php:25]

Does this mean the Update didn't run at all?  Could this be part of the problem?

**Comment by bpabiszczak** [comment]
Check on clear version. U have many not supported modules.

**Comment by mykljohn** [comment]
OK, trying to install the latest stable version, I get this error 


Fatal error: Can't use method return value in write context in /home1/globo/public_html/yeti_test/modules/Users/models/Record.php on line 284

**Comment by bpabiszczak** [comment]
version?

**Comment by mykljohn** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/tree/stable

**Comment by bpabiszczak** [comment]
New problem, new ticket. Check this: https://github.com/YetiForceCompany/YetiForceCRM/issues/2087

**Comment by mykljohn** [comment]
You told me to try deleting the modules on a new install.  Which is funny because I won't have these modules on a clean install.  I can't do a clean install because of this new error.  Definite catch 22.

You said I have many not supported modules, which really isn't true.  there are only 3, 2 of which I am trying to delete.

**Comment by bpabiszczak** [comment]
Try to put yourself in our situation. You report an issue, I check it on the same v2.3.49 and it works for me. Then you show me screenshots that suggest you have some unsupported modules that might have modified some system files. Then you report another problem [even though it should be done in a separate issue] and you get a solution almost immediately. And at the end you aren't happy about it... :/ 
So would it be better not to help at all?

I'm pointing out that our module uninstalling functionality won't work properly with any other module, only the developer of the module knows what to uninstall!

If it works for me and not for you, then you have to prove to us that this is our fault, not yours. If we can't trigger the error, then we can't fix it and verify whether or not it works after the fix.

**Comment by mykljohn** [comment]
I understand and appreciate your support and quick responses.  It just gets a bit frustrating.  Sorry if I came across as an ass, not my intention.  I was able to remove the said modules manually.
