### ISSUE TITLE
[bug] generating pdf from qoute

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2133]
version 2.3.49
tested on https://test.yetiforce.com/index.php?module=Quotes&view=Detail&record=776
when generating pdf from quote using marked button nothing happend... Only java error appeared... 
![image](https://cloud.githubusercontent.com/assets/11491482/10648707/5f3cb370-7840-11e5-8559-4810c26f5a63.png)

error:
![image](https://cloud.githubusercontent.com/assets/11491482/10648745/9447e486-7840-11e5-9040-a7d1d5c31677.png)

**Comment by bpabiszczak** [comment]
Please check new PDF module: https://pdf.yetiforce.com/ [admin/admin]
https://pdf.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=194

**Comment by witer30** [comment]
is it possible to install this new pdf module on my system...?

**Comment by bpabiszczak** [comment]
We public this module with 2.4. Now u can test :]

**Comment by witer30** [comment]
The new pdf module looks nice...
For your info, generation from left panel works ok, but using button under quote details is not working ok... 

using button from left panel
![image](https://cloud.githubusercontent.com/assets/11491482/10712921/51c57b8a-7aa9-11e5-8279-be5c30de1fec.png)

using button above quote details
![image](https://cloud.githubusercontent.com/assets/11491482/10712919/3b4f4692-7aa9-11e5-8e16-2ba7769112ef.png)

**Comment by witer30** [comment]
Well, can you check please because probably left pannel used old quote template... 
So above screen shots are not correct...

**Comment by bpabiszczak** [comment]
I don't even know how to refer to what you wrote. The screenshots are from the old pdf module. We don't develop the old one anymore, just the new one. In order for you not to confuse the old and new modules, it would be best if you deleted the templates from the old one and turned it off.

**Comment by witer30** [comment]
Well, 
sorry that wasn't clear enough. 
Shrotly speaking I did as you mentioned.
Here is result 
![image](https://cloud.githubusercontent.com/assets/11491482/10741768/b1a52dd0-7c29-11e5-9ba1-eec5fa20f88b.png)
and here is my template i used
![image](https://cloud.githubusercontent.com/assets/11491482/10741796/d2ce17e2-7c29-11e5-9e8e-6702b73de2b6.png)

**Comment by MaciejStencel** [comment]
Please check the template code now. I've added custom margins for header and footer (field "margines główny"). Changed a bit table code.

Old poroducts table is not supported in new pdf.

Browsing of folders + translations will sooon be fixed.

**Comment by witer30** [comment]
thanks
but receive this error
![image](https://cloud.githubusercontent.com/assets/11491482/10841178/5bd8588a-7ee7-11e5-8c6d-0ce14827a375.png)

**Comment by witer30** [comment]
probablly will be link with this as well https://github.com/YetiForceCompany/YetiForceCRM/issues/2201

**Comment by MaciejStencel** [comment]
This error was fixed. Try again.
