### ISSUE TITLE
[bug] missing button - quote

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2134]
there is missing button "Sent via mail" on quote page...
![image](https://cloud.githubusercontent.com/assets/11491482/10649077/50b521f0-7842-11e5-94fd-1950183665d2.png)

**Comment by bpabiszczak** [comment]
Please check new PDF module: https://pdf.yetiforce.com/ [admin/admin]
https://pdf.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=194
On rekord view u have new button, in modal view u can send via mail.
