### ISSUE TITLE
Custom Invoice numbers

### ISSUE THREAD

**Issue by janpsx** [YetiForceCompany/YetiForceCRM#2135]
Hey Guys,
ist der any option for a custom invoice number e.g / yyyy-mm-dd-001

Thanks

**Comment by witer30** [comment]
+1

**Comment by eptapsyxos** [comment]
+1 from me too.

**Comment by jucia** [comment]
+ 1

**Comment by MaciejStencel** [comment]
New fix added few functionality to numbering system.

First of all there is now also postfix. So you can add text before and after record id.

Second, in numbering sequence settings there is now new picklist which allows you to copy and paste into pre/postfix special variables which when record will be created will be replaced by proper value.

https://gitdeveloper.yetiforce.com/index.php?module=Vtiger&parent=Settings&view=CustomRecordNumbering&block=2&fieldid=22

Custom variables:
{{YYYY}} - Full year - 1999, 2003, 2015
{{YY}} - 2 digit year - 99, 03, 15
{{MM}} - month with leading zeros - 01, 05, 12
{{M}} - month without leading zeros - 1, 5, 12
{{DD}} - day with leading zeros - 01, 05, 25
{{D}} - day without leading zeros - 1, 5, 25


So for example when you want invoice to have number like:

FV/2015/12/14/23456

Then in Prefix type in: (variables you can paste using copy to clipboard functionality or type it in by hand):

FV/{{YYYY}}/{{MM}}/{{DD}}/

The last part is record id itself and postfix is not used here.

Please test it and for hints what more variables could be useful maybe create separate ticket and post there, like maybe if it would be usefull to pad record id to certain number of zeros, ex:

FV1 => FV0001
FV745 => FV0745

**Comment by eptapsyxos** [comment]
Thank you very much

**Comment by Alfreduco** [comment]
Hello, to me it will be usefull a way to reset the sequence numer to 1 each year... I need something like:

0001/2016
0002/2016
...
5678/2016
------------------- New year: restart invoice numer sequence from 1-------
0001/2017
0002/2017
....

Leading zeros are not important, but I really need to do this.

Thank you
