### ISSUE TITLE
Integracja z Joomla

### ISSUE THREAD

**Issue by jaroow** [YetiForceCompany/YetiForceCRM#2138]
Czy myślicie o integracji z Joomla! i ewentualnie dalej z Community Builder ?
Czy to działa/działało: https://github.com/JoomBridge ?
Czy będzie aplikacja na Androida i iPhona ?

**Comment by bpabiszczak** [comment]
TAK
Nie nasze, pytaj twórcę
W zależy w jakim znaczeniu. Jeżeli chcesz mieć responsywny system to zerknij z telefonu tutaj: https://layout.yetiforce.com/ jeżeli chcesz działać na CRM offline, to nie planujemy czegoś takiego. Mamy kilka appek na androida, ale dotyczą one połączeń telefonicznych.

**Comment by zebrahosting** [comment]
JoomBridge was made for vTiger to deliver support to our Joomla site clients. In does not work anymore with the recent versions of YetiCRM.
It did two way sync between Joomla users and CRM contacts incl user levels and easy password reset.
Would be nice if something similar would become available for Yeti but we don't have the capacity to let that happen at the moment.

**Comment by bpabiszczak** [comment]
Thank you for info.
