### ISSUE TITLE
Problem Installing Developer Version

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2140]
I'm trying to install the Developer version and if in PHP.ini (PHP5.4, PHP5.5 gives a slew of errors) I turn register_globals on I get this error:

Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

If I turn it off, I get this error:

Fatal error: Can't use method return value in write context in /home1/globo/public_html/yeti_dev/modules/Users/models/Record.php on line 284

**Comment by mykljohn** [comment]
I found that register_globals was depricated in php54...forgor about that.

**Comment by mariuszkrzaczkowski** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2153
https://github.com/YetiForceCompany/YetiForceCRM/issues/2126
