### ISSUE TITLE
[bug] type of tax and quote

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2141]
Test on developer demo version 2.3.77
There is issue with displaying tax mode during generating quote.
Tax set up:
![image](https://cloud.githubusercontent.com/assets/11491482/10678215/342c6884-7911-11e5-9991-2471ca308f1a.png)

new qoute creation stil there is Grup and individual but groupe should be off...  
![image](https://cloud.githubusercontent.com/assets/11491482/10678242/5a42bb5e-7911-11e5-8fa0-d9f96ab7476b.png)
![image](https://cloud.githubusercontent.com/assets/11491482/10678264/8007811c-7911-11e5-92d1-136c5d1cf524.png)

**Comment by bpabiszczak** [comment]
New configuration work only with new modules....
