### ISSUE TITLE
google maps api

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2142]
Maybe this is not the forum. Sorry for that.

I have a lattitude, longitud custom fields in the contact module.  I want to add a menu link in the right panel that i can send previos fields value via parms to show maps coordinate to google.

Thanks

**Comment by bpabiszczak** [comment]
For me it is a bit unclear ... The basic question is where do you want to take the latitude and longitude from? We have built-in Google Maps integration, it works in a way that if you enter the location in a “To Do”, then in a reminder or in a modal window, upon closing the “to do”, a link will appear, which will send the address to google maps and show you the destination.

If the answer is not enough for you, please describe the functionality step by step in a separate issue.
