### ISSUE TITLE
yeticrm 2.3.49 installed without problem but version number in the footer is 2.2.0

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2143]
Hi.

I installed version 2.3.49 without any FATAL ERROR. but in the footer i can read 2.2.0.  I download twice from sourceforge.net the version 2.3.49 and once installed the footer section reads 2.2.0.  Why this happen?

**Comment by bpabiszczak** [comment]
We uploaded v2.2.0 instead of v2.3.49 to SourceForge by mistake :/  We just fixed that
