### ISSUE TITLE
Error in summary view of account under the Emails Tab

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2144]
Error in summary view of account under the Emails Tab

Warning: DOMDocument::loadHTML() expects parameter 2 to be long, string given in /home/www/html/crm/vtlib/Vtiger/Functions.php on line 1112

**Comment by bpabiszczak** [comment]
Version? Screens? Movie? PHP? Please read this: https://yetiforce.com/en/developer-documentation/bugs.html

**Comment by amicheals** [comment]
This was fixed
Fixed in 71fb1d9
Check the latest version: https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by bpabiszczak** [comment]
Good :P
