### ISSUE TITLE
Generowanie ofert - nagłówek

### ISSUE THREAD

**Issue by jucia** [YetiForceCompany/YetiForceCRM#2146]
Witam,

Podczas generowania oferty - w przypadku zaznaczenia nagłówka:
1 strona - jest ok
2,3 itd - tekst wchodzi na nagłówek i jest nie czytelne

Pozdrawiam

**Comment by bpabiszczak** [comment]
Sprawdź działanie nowego modułu PDF: https://pdf.yetiforce.com/ [admin/admin]
https://pdf.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=194

**Comment by jucia** [comment]
Dodałem przykładową ofertę.
Dalej jest problem.

**Comment by bpabiszczak** [comment]
proszę o zrzuty ekrany... proszę o skonfigurowanie szablonu i link abym mógł go wygenerowac.

**Comment by jucia** [comment]
https://pdf.yetiforce.com/index.php?module=Quotes&view=Detail&record=115

**Comment by bpabiszczak** [comment]
Wysłałem Tobie linki do nowego modułu PDF, który działa z nowymi modułami z produktami. Podałeś link do starego modułu w którym jest stary moduł PDF, którego już nie wspieramy bo mamy nowy moduł PDF Oficjalnie będziemy go publikować za kilkanaście dni.

**Comment by jucia** [comment]
![oferta](https://cloud.githubusercontent.com/assets/12548243/10702282/07c732a2-79c9-11e5-9020-a743412a607e.png)

**Comment by jucia** [comment]
aaa,
moment sprawdzę na nowym.

**Comment by bpabiszczak** [comment]
Tu jest przykładowy dokument z faktury wygenerowany.
[fak (1).pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/19688/fak.1.pdf)

**Comment by jucia** [comment]
ooo super,
to bedzie w wersji 2.4 ?

**Comment by bpabiszczak** [comment]
Tak.

**Comment by jucia** [comment]
2.3.82 - jestem to w stanie wgrac na wersje 2.3.49 ?

**Comment by bpabiszczak** [comment]
Nie.

**Comment by zimart** [comment]
czy jest szansa podejrzeć gdzieś funkcję   "listy produktów ?" :)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/lab-pdf/modules/Settings/PDF/special_functions/ProductsTable.php

**Comment by zimart** [comment]
dziękuję :)

**Comment by bpabiszczak** [comment]
Tylko przypominam, że to działa dla nowego typu modułu z produktami z nowym PDF. Obie funkcjonalności pojawią się w wersji 2.4!

**Comment by zimart** [comment]
Funkcja działa także ze starym modułem - na ten moment wystarczy - z niecierpliwością czekam na aktualizację.
