### ISSUE TITLE
[Improvement] - quote pdf doc name - stored and sent (via email) 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2148]
Is it possible to change name of the pdf generate from quote as there is qoute number plus date.
This will improve appearance and then using this number with customer negotiation/contact... 
Look below - generate doc has very strange name (random digits) but if **CRM can do something like this Offer Q5 - 23.10.2015.pdf - looks better and easiter to speak with customer about such offer**... 

![image](https://cloud.githubusercontent.com/assets/11491482/10692791/153a1556-7994-11e5-9fe4-6e9a01da760c.png)

**Comment by amicheals** [comment]
@witer30
You can customize the pdf file name when you edit the pdf.

Under file name you can enter variables, dates etc

**Comment by witer30** [comment]
A yes, now it clear thanks...please closed
