### ISSUE TITLE
[Question] Looking for possibility to link doc with service contract

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2151]
Shortly speaking I would like to have possibility to link document upload to the system with record of service contract. Mean that when create service contract and sign physical doc with my customer I would like to have link between this record and scanned and upload signed contract...
Is it possible?
Thanks in advance

**Comment by amicheals** [comment]
@witer30 
I notice a related module for Documents after you create a service contract. If you click on documents You can either select a document that's currently in the CRM or Create a Document (quick upload) that you can upload.

**Comment by bpabiszczak** [comment]
Thank you @amicheals
