### ISSUE TITLE
errors installing version 2.3.49

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2153]
Hi.  First of all i have to said support team is an excelent resources for people like me.  I just see lot of petitions and youre checking all of it. one by one.  waoo.

I still having errors trying to install version 2.3.49.  If i use php 5.4 i had the following error:
Fatal error: Can't use method return value in write context in /home2/jballest/public_html/solarone/modules/Users/models/Record.php on line 284

If i upgrade to php 5.5 i had a lot of errors:

Strict Standards: Declaration of AntlrLexer::matchAny() should be compatible with BaseRecognizer::matchAny($input) in /home2/jballest/public_html/solarone/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::recover() should be compatible with BaseRecognizer::recover($input, $re) in /home2/jballest/public_html/solarone/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /home2/jballest/public_html/solarone/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /home2/jballest/public_html/solarone/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrParser::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /home2/jballest/public_html/solarone/libraries/antlr/AntlrParser.php on line 98

Strict Standards: Declaration of AntlrParser::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /home2/jballest/public_html/solarone/libraries/antlr/AntlrParser.php on line 98

Strict Standards: Declaration of Users::saveentity() should be compatible with CRMEntity::saveentity($module, $fileid = '') in /home2/jballest/public_html/solarone/modules/Users/Users.php on line 1691

Strict Standards: Declaration of Users::insertIntoEntityTable() should be compatible with CRMEntity::insertIntoEntityTable($table_name, $module, $fileid = '') in /home2/jballest/public_html/solarone/modules/Users/Users.php on line 1691

Strict Standards: Declaration of Users::save() should be compatible with CRMEntity::save($module_name, $fileid = '') in /home2/jballest/public_html/solarone/modules/Users/Users.php on line 1691

Strict Standards: Declaration of Users::get_column_value() should be compatible with CRMEntity::get_column_value($columnname, $fldvalue, $fieldname, $uitype, $datatype = '') in /home2/jballest/public_html/solarone/modules/Users/Users.php on line 1691

Strict Standards: Declaration of Vtiger_Module::unsetRelatedList() should be compatible with Vtiger_ModuleBasic::unsetRelatedList() in /home2/jballest/public_html/solarone/vtlib/Vtiger/Module.php on line 20

Strict Standards: Declaration of Vtiger_LanguageExport::__initExport() should be compatible with Vtiger_PackageExport::__initExport($module, $moduleInstance) in /home2/jballest/public_html/solarone/vtlib/Vtiger/LanguageExport.php on line 17

Strict Standards: Declaration of Vtiger_LanguageExport::export_Dependencies() should be compatible with Vtiger_PackageExport::export_Dependencies($moduleInstance) in /home2/jballest/public_html/solarone/vtlib/Vtiger/LanguageExport.php on line 17

Strict Standards: Declaration of Vtiger_LanguageImport::initImport() should be compatible with Vtiger_PackageImport::initImport($zipfile, $overwrite = true) in /home2/jballest/public_html/solarone/vtlib/Vtiger/LanguageImport.php on line 17

Strict Standards: Non-static method HTTP_Session::_init() should not be called statically in /home2/jballest/public_html/solarone/libraries/HTTP_Session/Session.php on line 803

Strict Standards: Non-static method HTTP_Session::localName() should not be called statically in /home2/jballest/public_html/solarone/libraries/HTTP_Session/Session.php on line 728

Strict Standards: Declaration of Vtiger_View_Controller::preProcessTplName() should be compatible with Vtiger_Action_Controller::preProcessTplName() in /home2/jballest/public_html/solarone/include/runtime/Controller.php on line 426

Strict Standards: Non-static method HTTP_Session::start() should not be called statically in /home2/jballest/public_html/solarone/include/http/Session.php on line 51

Strict Standards: Non-static method HTTP_Session::name() should not be called statically in /home2/jballest/public_html/solarone/libraries/HTTP_Session/Session.php on line 155

Strict Standards: Non-static method HTTP_Session::detectID() should not be called statically in /home2/jballest/public_html/solarone/libraries/HTTP_Session/Session.php on line 158

Strict Standards: Non-static method HTTP_Session::useCookies() should not be called statically in /home2/jballest/public_html/solarone/libraries/HTTP_Session/Session.php on line 291

Strict Standards: Non-static method HTTP_Session::name() should not be called statically in /home2/jballest/public_html/solarone/libraries/HTTP_Session/Session.php on line 292

Strict Standards: Non-static method HTTP_Session::name() should not be called statically in /home2/jballest/public_html/solarone/libraries/HTTP_Session/Session.php on line 293

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home2/jballest/public_html/solarone/libraries/antlr/AntlrLexer.php:297) in /home2/jballest/public_html/solarone/libraries/HTTP_Session/Session.php on line 161

Strict Standards: Non-static method HTTP_Session::id() should not be called statically in /home2/jballest/public_html/solarone/include/http/Session.php on line 52

Strict Standards: Non-static method HTTP_Session::isIdle() should not be called statically in /home2/jballest/public_html/solarone/include/http/Session.php on line 57

Strict Standards: Non-static method HTTP_Session::isExpired() should not be called statically in /home2/jballest/public_html/solarone/include/http/Session.php on line 57

Strict Standards: Non-static method HTTP_Session::get() should not be called statically in /home2/jballest/public_html/solarone/include/http/Session.php on line 76

Strict Standards: Non-static method HTTP_Session::get() should not be called statically in /home2/jballest/public_html/solarone/include/http/Session.php on line 76

Warning: Cannot modify header information - headers already sent by (output started at /home2/jballest/public_html/solarone/libraries/antlr/AntlrLexer.php:297) in /home2/jballest/public_html/solarone/include/main/WebUI.php on line 151

PLEASE HELP ME.

**Comment by florek41** [comment]
on 5.5
change error reporting to ```E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT``` and it should be fine.

on 5.4 YF team fix it - following #2092 :
>Try to install the latest version from the developer
https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by bpabiszczak** [comment]
Thank you @florek41
