### ISSUE TITLE
[BUG] PHP errors on php 5.4

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2155]
I've installed last dev version (2.3.88) on php 5.4 and if goes smoothly, but while trying run CRON i've got more fatal errors caused becouse same reason

```Can't use function return value in write context```

first:
```PHP Fatal error:  Can't use function return value in write context in /var/www/yf_test/cron/vtigercron.php on line 21```

after change *cron/vtigercron.php* form
```php
if (PHP_SAPI === 'cli' || PHP_SAPI === 'cgi-fcgi' || (!empty(Vtiger_Session::get('authenticated_user_id')) && !empty(Vtiger_Session::get('app_unique_key')) && Vtiger_Session::get('app_unique_key') == vglobal('application_unique_key'))) {
```
to
```php
$authenticated_user_id = trim(Vtiger_Session::get('authenticated_user_id'));
$app_unique_key = trim(Vtiger_Session::get('app_unique_key'));

if (PHP_SAPI === 'cli' || PHP_SAPI === 'cgi-fcgi' || (!empty($authenticated_user_id) && !empty($app_unique_key) && $app_unique_key == vglobal('application_unique_key'))) {
```

php throws next error:
```
PHP Fatal error:  Can't use method return value in write context in (...)/modules/Settings/CurrencyUpdate/cron/CurrencyUpdateCron.php on line 10
```

I know this is 5.4 specific error, but since it's supported it should works.

**Comment by bpabiszczak** [comment]
Please check EOL in cron file.

**Comment by florek41** [comment]
i've copied here without one ``)`` ;)

I add this issue becouse i'm afraid about what happend next on v5.4

**Comment by bpabiszczak** [comment]
Problem w tym, że używamy obiektów [chyba] w funkcji empty a niestety to źle działa dla wersji PHP 5.4 i niżej. a więc sztucznie obiekt wrzucamy w zmienną i w empty dajemy zmienną [niby to samo ale nie działa na każdej wersji]... 

Niestety nie mamy jak wyłapać każdego takiego miejsca, a więc mogą się dokładnie takie komunikaty pojawiać na wersji 5.4, każdy będziemy poprawiali ręcznie, chyba, że znajdziemy sposób na znalezienie wszystkich przypadków. 

Tu masz przykład jak to rozwiązać: https://github.com/YetiForceCompany/YetiForceCRM/commit/c5de10e6a4cc8ec666fbcf911707c0434c136f8e, niestety każdorazowo tak trzeba robić... W poniedziałek przygotujemy do tego poprawkę.

**Comment by nikdejan** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2165
