### ISSUE TITLE
add custom field values from related module does not work

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#2156]
I try to add 3 custome fields in invoice module with type values from related module, wanna to read total cost from related assets
and it does not work, not show in invoice
![image](https://cloud.githubusercontent.com/assets/15126825/10708357/3e6292b2-7a40-11e5-9e17-8f65aa3304c5.png)
![image](https://cloud.githubusercontent.com/assets/15126825/10708358/45d0c65e-7a40-11e5-802c-91b4e940c2e3.png)

**Comment by florek41** [comment]
It shows only on list view,
look at #1992

**Comment by bpabiszczak** [comment]
Thank you @florek41
