### ISSUE TITLE
12 hour format errors in calendar settin

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2158]
Hi.  

Im setting time format to 12 hours. the problem occurr when adding a new event/todo activity.  Once saved, the activity set to 8:00 PM is displayed as 8:00 AM.  Also, when i choose daily display, every hour on the screen has a doble T at on side of the hour. For example it shows 8tt, 9tt, 10tt ....

If i set to 24 hours format everything works fine.  Thanks for your help

**Comment by bpabiszczak** [comment]
Yeti version?

**Comment by josephballester** [comment]
2.3.88

**Comment by salimcmd** [comment]
I can also see same issue, and i am using the same version (2.3.88), Another issue i can find is that when we hover on that particular event from calendar view, it shows a popup with information like (Start Date, End Date, status,visibility). Even if i selected 12 hour format from my preference Still it shows in format of 24,   BTW It shows correctly in Detail view of Event.
![calendar](https://cloud.githubusercontent.com/assets/8142647/10723061/fcbe398a-7bdc-11e5-89fb-1056770c5abf.png)
![deatail view](https://cloud.githubusercontent.com/assets/8142647/10723087/3beb107e-7bdd-11e5-968c-9c5d8fa34c68.png)
