### ISSUE TITLE
Any Plans For Ipad Version?

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2159]
Hi 
Do you have any plans to release app for ipad?to synchronize data once and ready to go?

thank you very much.
General how you plan to expand the mobility of yeti?

**Comment by bpabiszczak** [comment]
Currently we create versions of responsive, we are not planning mobile version. If you have an iPad, phone, a tablet is go here and check out: https://layout.yetiforce.com/ [admin/admin]

**Comment by eptapsyxos** [comment]
I check it out but the problem i believe for a lot of users it will be that they can not work offline.
for two reasons 
1)the new layout needs online connection.and mobile providers doest have the same signal strength in all places...
2)second you dont have any app for mobile devices.
3)as you mentioned in another post you dont plan to connect the yeti with pushover or anyother external notification signal.

so you minimize your user base a lot and the usage of the yeti even more.
as it seems as far now
the only base group that can be useful yeti is people in offices with online wifi.
for people on the go its 70% useless.
except if they have an ipad and a very good mobile signal.

with some how you must do the yeti more outgoing crm.even with intergrations.think about zapier or something like that.

I believe that the real time data anywhere for everyone is the key success for a crm.

thank you very much.
