### ISSUE TITLE
[Question] functions mail

### ISSUE THREAD

**Issue by ssstorm** [YetiForceCompany/YetiForceCRM#2161]
Hi
I tested mailing on https://gitdeveloper.yetiforce.com/index.php
and have some questions
1.why I can't see outgoing letters, in the contact, only inbox letter?
http://screenshot.ru/c1b5623911bde35995ec37e3cfaabc09
2. I can create templates for letters, but I do not see how I can use them when I send a letter
3 If I unplug Roundcube, I can not use the standard module-mail (icon disappears, "send an email"), how can I use the default module
Thank you

**Comment by witer30** [comment]
check this conf especially folder conf of SENT
![image](https://cloud.githubusercontent.com/assets/11491482/10715221/a7c9d6d8-7b0e-11e5-8744-cf3fd0817498.png)

**Comment by witer30** [comment]
mail template
![image](https://cloud.githubusercontent.com/assets/11491482/10715230/f7292256-7b0e-11e5-9599-e8159eb0b0cb.png)

**Comment by ssstorm** [comment]
thanks, I tried configure, http://screenshot.ru/b24c90b5b94e5178674f237f66ebdea2 but did not understand how to configure the mail scanner associated with the display of outgoing messages to contacts
I sent a letter, but it still does not appear http://screenshot.ru/00d3a8a8d2be4fb2e1a0f3d97416ef62

I did a letter template, but the template button is inactive http://screenshot.ru/6103c151b9896e7ea75766b10173a363

**Comment by bpabiszczak** [comment]
1. Turn on the CRON
2. Configure the mail scanner [+ folder + actions]

**Comment by ssstorm** [comment]
Letters attached, ok How to activate the "Templates" button in the message editor?

**Comment by bpabiszczak** [comment]
New question = new issue. 
U should use this: https://gitdeveloper.yetiforce.com/index.php?module=OSSMailTemplates&view=List&parent=84
