### ISSUE TITLE
Installation breaks 2.3.49

### ISSUE THREAD

**Issue by agilisgmbh** [YetiForceCompany/YetiForceCRM#2162]
Hi,
I tried to install a new 2.3.49 in our server. Installation ends with a blank Screen and I dont know what to do.
Minimum req seems to be okay (on check-site), php 5 but it hangs up - and nothing happens...
I tried on 2 different servers - no chance...

Any hint?
![screenshot_2015 10 25_011](https://cloud.githubusercontent.com/assets/6077805/10715140/cfdeebee-7b0a-11e5-9091-398734dbfe3f.png)

**Comment by agilisgmbh** [comment]
I also tried install in different languages (maybe langfile prob) and also in different browsers (FF & Chrome, latest Versions)

**Comment by agilisgmbh** [comment]
After trying to reinstall I delete DB Tables and there are 780tables inside (maybe important for you).

**Comment by witer30** [comment]
check this
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
and this
https://yetiforce.com/en/implementer/installation-updates/101-crm-installation.html

look into folders priviliges

**Comment by bpabiszczak** [comment]
PHP version? If 5.4 try install on 5.5/5.6

**Comment by agilisgmbh** [comment]
php is 5.6 @bpabiszczak

**Comment by agilisgmbh** [comment]
@witer30
It seems it fits all needs.
:(

**Comment by bpabiszczak** [comment]
Can you send a server access [www, ftp, mysql] to my email [b.pabiszczak@yetiforce.com]?

**Comment by bpabiszczak** [comment]
Try install this version: https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by agilisgmbh** [comment]
I´ll try to install the Dev Version...

**Comment by agilisgmbh** [comment]
Did not work, too...
I dont understand, as I have previous Version (2.3.0) on my Server. Upgrading has also worked, but cant install the new version...
I think i´ll try something, if not works, Ill send you access @bpabiszczak 
regards

**Comment by agilisgmbh** [comment]
No I´ve installed 2.3.16 without any problems.
After that I migrated successfully to 2.3.49
Any Ideas?

**Comment by bpabiszczak** [comment]
You must check logs [yetiforce & server].

**Comment by agilisgmbh** [comment]
could be difficult, as error reporting / - log needs to be deactivated?

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by agilisgmbh** [comment]
Thank you Blazej,
I´ll have a look!

Von: Błażej Pabiszczak [mailto:notifications@github.com]
Gesendet: Sonntag, 25. Oktober 2015 14:19
An: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
Cc: agilis GmbH <agentur@agilisgmbh.com>
Betreff: Re: [YetiForceCRM] Installation breaks 2.3.49 (#2162)


https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by mf901** [comment]
Having also this issue shown in the screenshot. Error Reporting reports

 Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'www-data'@'localhost' (using password: NO)' in /var/www/YetiForceCRM-stable/include/database/PearDatabase.php on line 114
( ! ) PDOException: SQLSTATE[28000] [1045] Access denied for user 'www-data'@'localhost' (using password: NO) in /var/www/YetiForceCRM-stable/include/database/PearDatabase.php on line 114
Call Stack
#	Time	Memory	Function	Location
1	0.0000	229480	{main}( )	../Install.php:0
2	0.0177	3929744	Install_Index_view->process( )	../Install.php:22
3	0.0189	3930440	Install_Index_view->Step7( )	../Index.php:89
4	0.0324	3987856	Install_InitSchema_Model->initialize( )	../Index.php:233
5	96.3163	3989624	Install_InitSchema_Model->setDefaultUsersAccess( )	../InitSchema.php:28
6	96.3163	3989800	PearDatabase::getInstance( )	../InitSchema.php:90
7	96.3165	3994976	PearDatabase->__construct( )	../PearDatabase.php:84
8	96.3166	3995216	PearDatabase->connect( )	../PearDatabase.php:65
9	96.3167	3996488	__construct ( )

**Comment by agilisgmbh** [comment]
wwwdata Problem is afaik I know a problem with rights...
Seems, that php is installed as a module. SHould change this to cgi or fcgi or sth like that.
(please correct me, if I´m wrong)

**Comment by mf901** [comment]
have now installed the fcgi but the installer still fails

**Comment by bpabiszczak** [comment]
This is the problem: Access denied for user 'www-data'@'localhost' (using password: NO). You need to contact your server administrator.
