### ISSUE TITLE
Custom CSS?

### ISSUE THREAD

**Issue by agilisgmbh** [YetiForceCompany/YetiForceCRM#2164]
Hi YF Team!
Is there a way to use custom.css? Want (need) to change link colors.
Any Idea?
Want to use sth like custom.css as i dont want to make all new after an update.
thanks for your suggestions.

**Comment by bpabiszczak** [comment]
Please read this: https://yetiforce.com/en/developer-documentation/engine/177-loader-and-autoloader-of-files.html

**Comment by azorlone** [comment]
The link has moved to https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/loader-and-autoloader-of-files
