### ISSUE TITLE
[bug] diffrenet position of fields

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2166]
version 2.3.49
there are different position of fileds when displaying information and editing / creating quotes...
![image](https://cloud.githubusercontent.com/assets/11491482/10716497/9d2b931a-7b3b-11e5-8c41-6d3e8f0d5777.png)

![image](https://cloud.githubusercontent.com/assets/11491482/10716498/a9cd6080-7b3b-11e5-9e91-75665f72f3c9.png)

**Comment by florek41** [comment]
It's because  on detail view you have field which is hidden(inactive) on edit view. Ex. Quote number and created time.

You can change position of this fields in https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=Quotes
It's drag&drop editor.

**Comment by bpabiszczak** [comment]
Thank you @florek41
