### ISSUE TITLE
Bugi - własny moduł.. 

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2169]
Witam, kilka problemów przy korzystania z własnego rozszerzonego modułu.
Przetestowane na wersji stable..

Pierwszą rzeczą jest brak mozliwości wypełniania pól przez korzystanie z Mozilli - na Chrome działa... W screnie test przeprowadzony na mozilli.

Poza tym w sytuacji - po zapisaniu rekordu w bazie - przy zwykłej pełnej edycji wszystko jest poprawnie, natomiast wystarczy edytować któreś z pól przez szybką edycję i znika zawartośc całego bloku rozszerzonego.

Brak jeszcze możliwości korzystania z podatku indywualnego oraz rabatu grupowego.
![mozilla-bug-pola](https://cloud.githubusercontent.com/assets/11014419/10724533/af289e48-7bc5-11e5-948f-cc89f133bb54.gif)

**Comment by bpabiszczak** [comment]
Za mało klatek, bo tak skacze, że nie wiem za bardzo o co chodzi.  Po drugie opisy są niewystarczające ponieważ:

1. Z tego co widzę, wszystkie pola można wypełniać... więc nie wiem w czym problem. 
2. Zapisem na szybkiej edycji się zajmiemy i sprawdzimy co nie jest tak. Przy czym jeden błąd jeden ticket.... 
3. Odnośnie braku możliwości. Niestety nie wiem co ustawiłeś w konfiguracji modułu, więc ciężko mi się odnieść do tego co napisałeś. Nie wiem na ile to błąd a na ile błędna konfiguracja.
