### ISSUE TITLE
Send email to users automatically

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2171]
I dont know how to send mass email to user with the url they can access to change their password.

**Comment by paula-w** [comment]
We don't really know what you mean. Could you please add some details and attach some screenshots perhaps?

**Comment by josephballester** [comment]
sorry for that.  When i create a new contact or a new user, i want an automatic email sent by system.  This email should have a link that, once the user or contact click on it, gave the chance to change the or create a new password.

For example i create a new user named Joseph Ballester Feliciano with a specific email.  When i press SAVED, i want the system send a email with link to change or create the password for his account. Samething apply to contacts.

thanks a lot

**Comment by amicheals** [comment]
@josephballester Do you want this new user information to be sent for the CRM or the customer portal?

If for the customer portal
Install and Activate the customer portal https://yetiforce.com/en/implementer/installation-updates/129-customer-portal-instalation.html

Then,
Go to "Other Settings >> Workflow" (under the CRM admin menu)
Filter workflows by module (choose contacts)
activate each workflow by pressing the check mark when you hover over each record.

Then go to contacts.
Make sure permission to send emails is checked
Make sure portal user is checked.
Make sure language is chosen.

Once you save, the contact will get an email with username and password for the customer portal.

**Comment by amicheals** [comment]
@josephballester You can probably send automatic new user emails via the workflow.

Create an email template with the information you want.

Create a new workflow that sends new crm user information after a user is created.

**Comment by bpabiszczak** [comment]
Thank you @amicheals

**Comment by josephballester** [comment]
Everytime I add a new user (not contact) and press the save button, i want an automatic email sent to the USERS PRIMARY EMAIL  with url and credentials to have access to the system.  

I try to create a workflow but the USER MODULE is not available on the module picklist in the first step.

sorry for way i try to explain the errors. Im latin trying to explain my self in english.
