### ISSUE TITLE
Google calendar

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#2172]
Witam
czy jest możliwa synchronizacja z google calendar lub inny sposób dzięki, któremu zaplanowane terminy były by dostepne z telefonu (android)?

**Comment by bpabiszczak** [comment]
Użyj integracji CalDAV i CardDAV, nie potrzebujesz do tego Google. Tu masz panel do zarządzania tym: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Dav&view=Keys&block=5&fieldid=77 a tu plik, w którym trzeba to aktywować, aby w ogóle była ta integracja włączona: https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/config/api.php
