### ISSUE TITLE
The products are not added in the Quotes module

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#2173]
The added product in the item details block doesn't appear on the list (is not added).
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/10731000/744c8040-7bf3-11e5-9631-c4748383e2ad.png)

**Comment by nikdejan** [comment]
This should be of highest priority. This bug makes the whole system unusable for sales process. The same problem is with PO, SO, Calculations...

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/46f13f76b98eb9e3dab621a3993ef3a9291114d9
