### ISSUE TITLE
google map in the contact module showing a satellite map view of the address

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2175]
I want an option in the contact module or user module that show me a google map satellite view, showing the location of the address entered.

For example, If i add Joseph Ballester Feliciano in the contact module followed of his Physical or Residential Address.  Once i save the record i want a field or link that show me a satellite view of that address.

**Comment by bpabiszczak** [comment]
As far as I remember, the Google Maps license doesn't allow the map to be shown in CRM, since under this license, maps must be publicly available. In this case, we can either to link to Google maps, or we can use the open street map.
