### ISSUE TITLE
New Entities

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#2176]
Hello everyone,

we are not able to create entities.
in accounts /contacts etc we get: 
SQLSTATE[HY000]: General error: 1364 Field 'shownerid' doesn't have a default value

the crm doesn't show a field where to enter the data.

Best regards,
Ralph

**Comment by mf901** [comment]
to get rid of this after reading https://github.com/YetiForceCompany/YetiForceCRM/issues/2366 I did the following:
ALTER TABLE yeticrm.vtiger_crmentity MODIFY COLUMN shownerid VARCHAR(255) NULL;

**Comment by bpabiszczak** [comment]
Please read this: https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

!!! SQL_MODE should not contain STRICT_TRANS_TABLE  !!!
