### ISSUE TITLE
Should Emails be visible to others if sharing set to private?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2178]
Hi,

I am not sure if this is expected behavior, but I was testing the sharing rules for emails. I set sharing to Private then went to the email client and attached an email to a Project. I also attached another email to an Account. 

Then I logged out and logged in as a different user and found I could read both emails created by someone else.

I realise there is a need for people to share some emails i.e. relating to projects etc. But there are occasions where you might want to still attach the email to say a project, but for your eyes only - not viewable by other staff.

Is there an option to do this? If not it would be good to be able to select when attaching mails whether it can be viewed by self only, or public.

Regards

Percy

**Comment by bpabiszczak** [comment]
Mails, just like other modules, work using permissions. Whether or not they're visible for another user depends on the configuration. You can set them to be visible, you can set them to be invisible. Unfortunately your description tells me nothing about your permissions configuration, so this answer has to be sufficient - it is indeed possible to set it in a way that the people who shouldn't see it won't see it it...
