### ISSUE TITLE
cron setup

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2179]
How automatic email works in Yeti?
I follow the steps in this tutorial:
https://yetiforce.com/en/implementer/installation-updates/129-customer-portal-instalation.html
but im not reciving any email automatically.  

I think it have to be with cron configuration.  Can you help me please.?

**Comment by florek41** [comment]
an this is because #2180

**Comment by bpabiszczak** [comment]
Thank you @florek41 
@josephballester please read this: 
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html
3. https://yetiforce.com/en/administrator-documentation/panel/cron.html
