### ISSUE TITLE
Fatal error: Can't use function return value in write context in /home2/jballest/public_html/solarone/cron/vtigercron.php on line 21

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2180]
Hi.

I create a new cron job in my hostgator hosting service with the following syntax:
*/15 	* 	* 	* 	* 	/opt/php54/bin/php /home2/jballest/public_html/solarone/cron/vtigercron.php

when it runs i received an email with the following error.

Fatal error: Can't use function return value in write context in /home2/jballest/public_html/solarone/cron/vtigercron.php on line 21

my current yeticrm version is 2.3.88

**Comment by florek41** [comment]
duplicate: #2165

**Comment by josephballester** [comment]
sorry for that.  There was a new vtigercron.php version.  I download and installed eliminating the error.
