### ISSUE TITLE
[question] - new module likned under account and contact

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2181]
First of all sorry for this question but screened configuration and do not see this... 
how i can create new module (this i know) wchich will be located under contact and seen also under account as contact is assigned to account. 
would like to have something like below...
![image](https://cloud.githubusercontent.com/assets/11491482/10765129/a5ac0ce4-7cd1-11e5-8d97-8b9fa16222d8.png)

**Comment by bpabiszczak** [comment]
Unfortunately your description isn't clear enough, so I'll answer what I understood:

Setting the related module on the right side requires some programming work, the order below Updates can be configured here, and relations can be added:  https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&sourceModule=Accounts  just don't forget to enable the option here: https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/config/developer.php.

Widgets in record summary can be added here: https://gitdeveloper.yetiforce.com/index.php?module=Widgets&parent=Settings&view=Index&block=2&fieldid=58, if you want a new widget it will require some programming work.
