### ISSUE TITLE
Is Vtiger Android App will work with Yetiforce?.

### ISSUE THREAD

**Issue by salimcmd** [YetiForceCompany/YetiForceCRM#2183]
So i installed Yetiforce 2.3.88, And i am trying to connect with Vtiger Android application, I have enabled ```$enabledServices = ['mobile']``` in this file  ```https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/config/api.php```, But it just not loging.

**Comment by bpabiszczak** [comment]
Q: Is Vtiger Android App will work with Yetiforce?
A: NO

**Comment by esaw01** [comment]
@bpabiszczak 
There are about 6 vTiger apps on Google Play. Are you sure that non of them work?

Are you sure not even one will work? :(

Thank you.
