### ISSUE TITLE
Problem z usługami 

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#2186]
Jaśli do kalkulacji dodaję usługę ( ja dodałem tę usługę do bazy) to w kalkulacji ma poprawną cenę taka jaka jest zdefiniowana. Jeśli natomiast tę usługę do kalkulacji dodaje inny user to cena jest 1zł
![crmscreen_1](https://cloud.githubusercontent.com/assets/15170959/10783022/0a6f711a-7d55-11e5-8dd3-33736267c564.jpg)

przy okazji co oznacza RBH w kolumnie?

**Comment by mmstrzelec** [comment]
Sprawdziłem też na wersji testowej to samo cena 1
![crmscreen_2](https://cloud.githubusercontent.com/assets/15170959/10815667/d0efb9c0-7e2d-11e5-9811-bd259c721911.jpg)
gdzie jest błąd uprawnienia?

**Comment by bpabiszczak** [comment]
Błąd jest zapewne w formatowaniu liczby, ponieważ jest widoczna cena 1 500.00 więc obcina po 1. RBH to szacowane roboczogodziny. Sprawdzimy to, proszę tylko o informacje, z tego co widzę, dotyczy to starego typu modułu z produktami, jaki to moduł konkretnie?

**Comment by bpabiszczak** [comment]
Czy moja podpowiedź w czymś pomogła za nim sprawdzi to programista i poprawi?

**Comment by mariuszkrzaczkowski** [comment]
Błąd został naprawiony w nowych modułach zaawansowanych.
