### ISSUE TITLE
Preferences option for users (not contacts)

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2188]
Vtiger show a PREFERENCES OPTIONS for every user (not contact) to gave the chance to change color, reset password and other criterias.

Is there a way to gave same option to users in yeti?  the only option a user have is logout.

**Comment by diderich** [comment]
Interesting! This was possible in earlier versions of YetiForceCRM, but apparently was dropped at some point. No idea why :(

**Comment by kpaulaha** [comment]
It can be switched on: config --> security.php 	'SHOW_MY_PREFERENCES' => false,

**Comment by josephballester** [comment]
Thanks. Works perfect

**Comment by bpabiszczak** [comment]
Some time ago I tried to find a reason for this tab to be available, but I couldn't. 

You should remember that it's not the user who decides how the system works, regardless of whether we are talking about the currency, calendar, colors or personal data... The only useful thing in the whole tab would be the password change option, nothing more... Making this tab available for a user was one of vtiger's biggest mistakes, especially considering security.
