### ISSUE TITLE
[bug] - workflow - send mail with PDF

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2189]
Version 2.3.49

I wanted to send order confirmation when purchase order status is accepted and this works fine. So partially workflow works because email is sent but without pdf file which I wanted to attached and this was specified during creation of workflow. 
PDF template works and a pdf doc is manually generated... 
Problem is that attachment is missing...

**Comment by bpabiszczak** [comment]
Use this program:  https://screentogif.codeplex.com/  and record a clip that shows how you trigger this error in gitdeveloper. It will make it easier for us to find and fix this error if it exists.

**Comment by witer30** [comment]
is it possible to upgrade my CRM to version of developer...
It will be easier to show everything as I have all data in the system and gitdeveloper is "empty"...
my version is 2.3.49
Dnia 30 października 2015 15:34 Błażej Pabiszczak napisał(a):
 Use this program: https://screentogif.codeplex.com/ and record a clip that shows how you trigger this error in gitdeveloper. It will make it easier for us to find and fix this error if it exists.—

**Comment by bpabiszczak** [comment]
[TEST VERSION!!!] - https://github.com/YetiForceCompany/UpdatePackages/raw/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip/2.3.0_to_2.4.0_vRC3.zip

**Comment by witer30** [comment]
thanks 
But already started to do it on demo and have one issue that there is no possibility to choose pdf template which is active 
![image](https://cloud.githubusercontent.com/assets/11491482/10850560/a4ab71e8-7f26-11e5-8657-a41b5a764f29.png)
pdf template
![image](https://cloud.githubusercontent.com/assets/11491482/10850575/bf6a9d6a-7f26-11e5-9381-0fe260e0bc5a.png)
and movie which is not finish (no sales order created) as couldn't choose pdf template...
![animation 1](https://cloud.githubusercontent.com/assets/11491482/10850778/b2738c56-7f27-11e5-8def-d4c3229f6fd6.gif)

**Comment by witer30** [comment]
w wersji 2.3.49 mam tak wybrane opcje 
![image](https://cloud.githubusercontent.com/assets/11491482/10851925/1ba25152-7f2e-11e5-96b1-122312e7195a.png)

**Comment by witer30** [comment]
update fails
![image](https://cloud.githubusercontent.com/assets/11491482/10851966/6423b8d0-7f2e-11e5-9dbf-61faa2f6f940.png)

**Comment by witer30** [comment]
On the newest version have the same situation - workflow didn't see template of PDF... where template was created  
![image](https://cloud.githubusercontent.com/assets/11491482/10887064/655dc200-8185-11e5-8edf-e55a8eb85199.png)

**Comment by MaciejStencel** [comment]
It is filtering templates by module. So if You create workflow task for module X, it will show you pdf templates for module X.

If there are non then list is emtpy.

**Comment by MaciejStencel** [comment]
I think the problem lies also in that that you are using old pdf module. Sending PDF files is based now on the new pdf module.
