### ISSUE TITLE
[bug] - immpossible to change field after saving

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2190]
version 2.3.49
tested on test.yetiforce.com
the same is on 
version 2.3.144
developer.yetiforce.com

When order is created and saved with inactive option of recurring invoice the java is showing error
that Frequency is not filledin in case of any change of single field... When part of recurring invoice information is enabled then problem is absent...

![image](https://cloud.githubusercontent.com/assets/11491482/10791290/f2e8d65c-7d87-11e5-8e48-17642ead3ac8.png)

**Comment by bpabiszczak** [comment]
It works like that from the very beginning [inherited from Vtiger]; at the moment we are creating new modules with products that will be designed from scratch, and this problem will no longer exist.
