### ISSUE TITLE
[bug] - search product script in every module where exist

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2191]
Version 2.3.144

In every module where this product specyfing script is located it doesn't work. 
After selection of product noting is transfer to qoute or sales order... 
![image](https://cloud.githubusercontent.com/assets/11491482/10791780/325e439c-7d8a-11e5-929e-565886561594.png)

but when you strat typing product name na select it from the list this works...
![image](https://cloud.githubusercontent.com/assets/11491482/10791810/534dd52c-7d8a-11e5-80ae-6e86a327c6d2.png)
and after cliking it
![image](https://cloud.githubusercontent.com/assets/11491482/10791829/6e5f96e8-7d8a-11e5-8726-2586a0046ee9.png)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2173
