### ISSUE TITLE
Unable to add product to Quote

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2192]
In gitdeveloper.yetiforce.com, when I try to add a product to a quote, nothing happens. Everything is OK with test.yetiforce.com. Is it a bug, or do I need to configure something or enter more details into Product? 

![add_product](https://cloud.githubusercontent.com/assets/13381850/10817110/116531ec-7e38-11e5-98bc-3ec5677e4f2c.gif)

**Comment by witer30** [comment]
which soft do you use to make such video..
Dnia 29 października 2015 12:27 nikdejan napisał(a):
 In gitdeveloper.yetiforce.com, when I try to add a product to a quote, nothing happens. Everything is OK with test.yetiforce.com. Is it a bug, or do I need to configure something or enter more details into Product?—

**Comment by florek41** [comment]
this is same as #2173 , isn't it ?

@witer30 
this is screentogif https://screentogif.codeplex.com/

**Comment by nikdejan** [comment]
Yep, it's the same. And yep, software is screentogif.
