### ISSUE TITLE
products: mass edit quantity - also changes price

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#2193]
When using mass edit on products to change quantity, also the price field is changed.
eg. all quantity is changed to 500 items.
no value is added to "price" field.
then all selected products are updated with 500 items and price changed to zero.

**Comment by mariuszkrzaczkowski** [comment]
I tested it in the latest developer version and it works properly.
Tell me exactly which field and attach a screenshot with an example.

**Comment by lalord** [comment]
Please see 3 screenshots, when mass edit 2 products.
![products3](https://cloud.githubusercontent.com/assets/10504154/11453998/a307852e-961f-11e5-847f-61eb005cb739.png)
![products2](https://cloud.githubusercontent.com/assets/10504154/11453999/a30a9b2e-961f-11e5-9198-ba6962c15fa6.png)
![products1](https://cloud.githubusercontent.com/assets/10504154/11454000/a30ae49e-961f-11e5-8c46-37f55c4de7e8.png)

**Comment by bpabiszczak** [comment]
We fix this. Please check the last gitdeveloper version.
