### ISSUE TITLE
Improve Email widget

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2194]
In Opportunity module, on Summary View, in Email widget, if I click Reply button in order to reply to a mail I received, I have to manually add SS# prefix to Subject in order to keep my response related to current Opportunity. I think this should be automatic. It's logical that if I am replying to the email message which is related to current Opportunity (and I'm doing that from "withing" that opportunity), then certainly my response would be also related to the same Opportunity. Response should be automatically attached to current opportunity at the moment of sending, or, alternatively, subject should be prefixed with SS# and then Mail Scanner/Binder will attach email to current opportunity.

**Comment by florek41** [comment]
+1

**Comment by witer30** [comment]
+1

**Comment by nikdejan** [comment]
I was talking about Reply but same applies to Forward.

**Comment by mariuszkrzaczkowski** [comment]
Mail scanner has been redesigned, adding prefixes have been rebuilt and are now correctly added to the e-mail.
https://github.com/YetiForceCompany/YetiForceCRM/commit/6602e6333453068ecc2305e714f124b3920528c9

**Comment by nikdejan** [comment]
There is one small problem with adding prefix. 
When you click Reply (or Reply All or Forward) prefix is being added at the end of subject in the form [S-SP1], which is good. But, before you add [S-SP1] at the end of the subject, you need to check if S-SP1 is already contained in subject and should be added only if it is not already there.
It happens very often that you exchange many email messages with a customer. When you send your first email (either by clicking letter icon, or by clicking reply) subject of the email you sent will have S-SP1 in it. (If you click letter icon it will be S-SP1 - Subject text, and if you click Reply it will be Re: Subject Text [S-SP1]). Now if customer clicks reply, you will receive an email with S-SP1 in it's subject. So now, when you click Reply, there is no need to add prefix, because it is already in the subject.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/c814db5e30935ee92a982295ed83c1397a471b09
