### ISSUE TITLE
[Question] OSSPDF Background image

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2195]
How can I set a background image for the PDF template for Quotes and Sales Orders?  We have a pre-designed form that we want to use with letterhead and images.  I tried adding the images separately, but when it inserts the data, it distorts the images in the other table cells.

I tried body background="bgimage.jpg" to the source of the template, but when I save it, it removes the background.

I also tried body style="background-image:url(http://www/yeti/cache/upload/images/Quote1.jpg)"

**Comment by witer30** [comment]
with version 2.4 there will be new pdf module.
You can try it on pdf.yetiforce.com   admin/admin
current version is not support
Dnia 29 października 2015 19:39 mykljohn napisał(a):
 How can I set a background image for the PDF template for Quotes and Sales Orders? We have a pre-designed form that we want to use with letterhead and images. I tried adding the images separately, but when it inserts the data, it distorts the images in the other table cells.—

**Comment by mykljohn** [comment]
ok thanks

**Comment by bpabiszczak** [comment]
New PDF is now ready for testing. It is a preliminary version and not have all the functionality.

**Comment by mykljohn** [comment]
Great to hear, thanks for the update!!!
