### ISSUE TITLE
[Improvement] Emailing Quote

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2199]
When you click on the send Quote (pdf), when it opens up the email composer, it should load the email address and the Subject from the Quote.  This would save a lot of time.

**Comment by bpabiszczak** [comment]
But where exactly would it take the mail details from?

**Comment by witer30** [comment]
if you add related field link to contact module and then use email template and pdf template then you will be able to send this offer automaticly via workflow but there was reported issue that pdf is not attached...

**Comment by bpabiszczak** [comment]
It's a system modification that's far from what it works like right now. We are not planning to introduce the changes you described, you have to do it on your own...

**Comment by mykljohn** [comment]
witer30: That was my thought.  Can you help me out with the email template?  Is there any documentation on creating a template?  specifically the subject, send to, and attachments.  Could that Template then be issued from the Quote screen or does it have to be a Workflow?

**Comment by witer30** [comment]
Email template you can use via Roundcube or via automatization process mean workflows. 
Regarding documentation there is no instruction how to build emil templates but if you open existing ones then you will see that it is not too difficult... Almost every info which is in the module you can use in email template means label and value. 
For copy to clipboard it is enough to use orange or blue buttons after choosing info which you would like to use... 
The orange is for labels and blue is for value... 
please try and if you will need more info please ask... 
by the way, documentation will be created next year when system will be ready as I understood correctly..

**Comment by mykljohn** [comment]
witer30: Thanks, I created a template, but when I click on templates in Roundcube, it only puts a little dot underneath templates, nothing else.  any idea why?

**Comment by witer30** [comment]
can you show picture

**Comment by mykljohn** [comment]
Here it is.
![screenshot_1](https://cloud.githubusercontent.com/assets/11919990/10855982/3c2ca932-7f0a-11e5-9470-71f56413dc3d.png)

**Comment by witer30** [comment]
ok, check this  - it should be done like this
![animation 2](https://cloud.githubusercontent.com/assets/11491482/10856286/042571d0-7f47-11e5-8611-fa7991aa2f73.gif)

**Comment by mykljohn** [comment]
I've created the Template no problem. 

But when I try to open it in the email screen when I click on templates, there is no dropdown.  just that little dot.

**Comment by witer30** [comment]
if you use old system then please upgrade because it was changed in the past....
Dnia 30 października 2015 21:44 mykljohn napisał(a):
 I've created the Template no problem.But when I try to open it in the email screen when I click on templates, there is no dropdown. just that little dot.—

**Comment by mykljohn** [comment]
I tried to do the latest update, but got an error...has that been fixed?

**Comment by mykljohn** [comment]
OK got it working.  But it doesn't bring int the email address.  Will it in the Workflow?  Any help available re: Workflow?

**Comment by mykljohn** [comment]
@witer30 I'm having trouble with Workflows.  Is there anyway to debug / see what's happening?  I've turned debugging on and gone through the log, but everything looks fine.  It runs the workflow and executes the , but doesn't email the template.

**Comment by witer30** [comment]
I have version 2.3.193 and this works means email is sent. However without attachment... :-( 
you can see in system.log the logs of all actions which happening in yeti if you enabled developer mode... 
in system.log you cen see all yeti action in live...

**Comment by mykljohn** [comment]
@witer30 I could not get to 2.3 because my labels disappeared and I have not been able to resolve this problem.  Can you help me with that?  My heads on the chopping block with my boss if I can't show him results by the end of the week. :(

**Comment by witer30** [comment]
Well, 
I saw your tickets concerning labels but in my opinion it is link to server configuration as non-one had similar case... 
I would recommend to download last developer version of YF
https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip
and start with new installation. Before installing I would check documentation on yetiforce.com concerning server requirements and necessary adjustments.

**Comment by mykljohn** [comment]
Ok I will try once again :).  When I do the install, everthing shows go, no errors in php.ini (php5.5).  But I figure is has to be something with it.

**Comment by mykljohn** [comment]
I did find some settings that aren't in the php.ini, but don't show on the install sys check  

    suhosin.request.max_vars 5000
    suhosin.post.max_vars 5000
    suhosin.session.encrypt Off
    mbstring.func_overload
    max_allowed_packet 10M

**Comment by witer30** [comment]
I am using php 5.6 which is recommended...Check if you have all libraries installed...
look here to compare configuration your server esspecialy itn tabs -  Files/Folders and RoundCube Engine
https://test.yetiforce.com/index.php?parent=Settings&amp;module=ConfReport&amp;view=Index&amp;block=9&amp;fieldid=65

**Comment by mykljohn** [comment]
We're on HostGator which only supports to php5.5 and doesn't support suhosin. .  All the libraries are loaded except LDAP.  My configuration matches except on Demo session.gc_maxlifetime =1800

**Comment by mykljohn** [comment]
grrrrrrr!!!  Just finished fresh install of Dev of php5.5 
![screenshot_6](https://cloud.githubusercontent.com/assets/11919990/11515369/3294e09a-9843-11e5-9726-60ed5b290c1a.png)

**Comment by witer30** [comment]
Concerning this

``suhosin.request.max_vars 5000
suhosin.post.max_vars 5000
suhosin.session.encrypt Off
mbstring.func_overload
max_allowed_packet 10M``

simply add to php.ini
