### ISSUE TITLE
 Import data directly from vTiger db

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#22]
I like your idea and that, what you did with this system. I'm going to migrate the system from vtiger to yetiforce, but the transfer of data via CSV is cumbersome and prone to errors. In this situation, great option could be direct import data from the vtiger databases (leads, accounts, contacts and related item such as opportunities, todos, events, projects, etc.). Is it possible to do?

**Comment by bpibiza** [comment]
maybe could be possible to develop a tool that will import custom fields and relations created by user. Something like migration without lost of users data and schemes.

**Comment by waran70** [comment]
Partial migration tool would be great. I got need to switch 6.1 to YF but what I want is to move only organizations, contacts and invoices. Actually script for importing invoices would be convinient as accounts can go through csv

**Comment by bpabiszczak** [comment]
In the new 1.2 version there is a migration module from Vtiger 6.1. I'm closing this issue.

**Comment by crmtiger01** [comment]
You can Import multiple users in CRM by importing CSV file. for more information check out: http://goo.gl/YG37GB
