### ISSUE TITLE
[BUG] Currency and translate ver. 2.3.172

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2200]
![animation 163](https://cloud.githubusercontent.com/assets/1402355/10841385/9c4b5cd2-7f0a-11e5-95bb-bda10f7b6b84.gif)

**Comment by mariuszkrzaczkowski** [comment]
Default currency is selected/saved only during system installation

**Comment by waw555** [comment]
I chose when installing the ruble and Russian language

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2274
