### ISSUE TITLE
[bug] - Advance block - quote module

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2201]
pdf.yetiforce.com

coudn't save filed selection during working on advance block mode...
![animation 0](https://cloud.githubusercontent.com/assets/11491482/10841412/6a237bac-7ee9-11e5-9efe-ef08c40aa3ed.gif)

**Comment by nikdejan** [comment]
If I remember correctly, after you click Save values do get saved but the modal window remains open, ie it's not closed automatically. In order to close it you need to click cancel.

**Comment by bpabiszczak** [comment]
Please test here: https://gitdeveloper.yetiforce.com/

**Comment by nikdejan** [comment]
Looks OK on gitdeveloper.yetiforce.com (ver. 2.3.212)

**Comment by witer30** [comment]
Version 2.3.365
Issue still exist...
![animation 2](https://cloud.githubusercontent.com/assets/11491482/11188242/2bd13eb2-8c8a-11e5-853d-3cb11496dfa5.gif)

**Comment by rskrzypczak** [comment]
Hello,
I really don't know how to trigger the error you mentioned. You are doing something that I can't see in the gif you attached.

However, adding a block with products, which already has such block, is pointless. In any given module there could only be one block with products (old or new).
We will soon add modules similar to Quotes, Calculations, etc, which will support the new block with products.
