### ISSUE TITLE
Problem z logowaniem do poczty Google Apps

### ISSUE THREAD

**Issue by boolek** [YetiForceCompany/YetiForceCRM#2202]
Aktualnie mam wersję ver. 2.3.49 i nie mogę skonfigurować ustawień, aby możliwe było zalogowanie do poczty w domenie firmowej @firma.com (korzystamy z Google Apps)
Na standardowe konto @gmail.com wchodzi bez problemu.

"Domena (automatycznie dodawana do loginu)" - z wpisaną domeną i pustą - efekt bez zmian.

Porty i serwery dla Google Apps są dokładnie te same co dla Google - różnica polega na loginie:
- dla Google - user
- dla Google Apps - user@firma.com

W pierwszej wersji systemu nie było z tym problemu.

**Comment by bpabiszczak** [comment]
Pusta domena na pewno nie może być... a login w Google Apps musi być podany cały np. b.pabiszczak@yetiforce.com. 

Po drugie co na to logi?

**Comment by boolek** [comment]
Dość ciekawa sytuacja, bo tylko na moje konto pocztowe nie mogłem się zalogować.

errors.html zwrócił
[30-Oct-2015 11:26:53 +0100]: <bcffb543> IMAP Error: Login failed for user@firma.com from XX.XXX.XX.XXX. AUTHENTICATE PLAIN: Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure) in /home/.../public_html/jeti/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_imap.php on line 198 (POST /jeti/modules/OSSMail/roundcube/?_task=login?_task=login&_action=login)

Zmiana hasła nie pomogła. 
Pomogło dopiero ustawienie w Google Apps >> Dostęp dla mniej bezpiecznych aplikacji >> Włącz.
Co nie za bardzo mi odpowiada ;(

**Comment by bpabiszczak** [comment]
Nie odpowiada co? Niestety nie wiem co google ma na myśli "mniej bezpieczne aplikacje" o ile wiem, nigdzie nie podaje zasad jakie powinny aplikacje zewnętrzne spełniać aby były bardziej. Póki ktoś takiej listy nie poda, to będzie jak jest... 

Po drugie to Google, to znaczy, że dostęp do Twoich maili ma mnóstwo firm :P

**Comment by boolek** [comment]
Pytanie tylko dlaczego dla tej samej domeny jeden użytkownik może być na standardowych ustawieniach, a przy drugim trzeba "obniżyć" poziom zabezpieczeń...

Poza tym w pierwszej wersji nie trzeba było tego przestawiać i wpuszczało od nas wszystkich.

Dzięki za pomoc, bo by myślał, że problem leży po stronie Yeti ;)

**Comment by bpabiszczak** [comment]
Pewnie dlatego, że jedno z kont ma "dwuetapową" autoryzacje... 
My nic nie zmienialiśmy, to google zmienił.
