### ISSUE TITLE
two documents link in contact right menu.

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2203]
Hi.

Viewing a contact information, i see the Documents Link twice in the right menu.  See picture below

![documentlinkrepeated](https://cloud.githubusercontent.com/assets/12039062/10845961/63af8aa6-7ee2-11e5-8f47-35987c90f56b.jpg)

The only thing i do previos this error was adding a new field in the documents module.  But i already delete that field but problems still happening.

**Comment by bpabiszczak** [comment]
But you did you not put it to production versions? ;P
Try enable this: https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/config/developer.php ['CHANGE_RELATIONS' => true], and go to this tool: https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&block=2&fieldid=41
