### ISSUE TITLE
[Question] Documents control

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2204]
What is documents control doing...? 
will it be develope to manage folder location for documents uploading to CRM?

**Comment by bpabiszczak** [comment]
The module allows for enabling in several modules the widget in record summary [project, opportunity, ticket] and allows you to configure what documents are required for each stage; the system either informs about the missing documents, or won't let you proceed to the next stage, if those documents are not attached. 

The module is quite old, we'll most likely improve it soon.
