### ISSUE TITLE
Setting is not saved Save logs for sent messages

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#221]
Setting is not saved Save logs for sent messages
![mail error](https://cloud.githubusercontent.com/assets/1402355/6169009/33b169cc-b2ec-11e4-9b84-0b0cdeb9eee6.JPG)

**Comment by mariuszkrzaczkowski** [comment]
Add the following line to the file modules\OSSMail\roundcube\config\config.inc.php
$config['smtp_log'] = true;
