### ISSUE TITLE
[Problem] Mail Handler error

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2211]
I get the following error when I try to open the Mail Handler:

Error!!!
Handler not found

Any idea why?  ver 2.2 Server Settings are all correct

**Comment by bpabiszczak** [comment]
We take care with errors that occur in the latest version. Please update system.

**Comment by mykljohn** [comment]
Remember I tried to upgrade and had an error upgrading...Is that resolved?

**Comment by bpabiszczak** [comment]
2.2 > 2.3 - https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.2.0_to_2.3.0/zip
2.3 > 2.3.49 [stable] - https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip
2.3.0 > 2.4 [test version]: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip

If you have problem with update, please check server configuration [upload > 50MB] and read this: 
1. https://yetiforce.com/en/implementer/installation-updates/176-system-update-not-verified.html
2. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
3. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by witer30** [comment]
htere is need to increase post_max_size in php.ini because %)M  is too samll for this update.
Unfortunately in the and there was massage that updating files was failed.

**Comment by mykljohn** [comment]
Thx, I increased max_upload_size not post

**Comment by witer30** [comment]
And have you succeeded Update?
Dnia 31 października 2015 2:58 mykljohn napisał(a):
 Thx, I increased max_upload_size not post—

**Comment by mykljohn** [comment]
I get an error "Module does not contain default language (en_us)."  I'll rezip the files and try again.

**Comment by mykljohn** [comment]
We're running php5.4.45...don't know if that could be the problem.

**Comment by bpabiszczak** [comment]
Yes, 5.4 is a problem.

**Comment by mykljohn** [comment]
OK, you might want to change that in the Docs and the System Setting Check, it says PHP5.4

**Comment by mykljohn** [comment]
OK, that solved it thanks!

**Comment by mykljohn** [comment]
OK, Upgraded to 2.4 and got the error "Cannot create references to elements of a temporary array expression in /yeti_test/vtlib/Vtiger/Functions.php on line 275"

		foreach (explode(',', $info['fieldname']) as &$fieldname) {

**Comment by mykljohn** [comment]
Is there an upgrade from 2.3.49?  I've installed that and still get the Error!!!
Handler not found

**Comment by witer30** [comment]
https://github.com/YetiForceCompany/UpdatePackages/blob/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip/2.3.0_to_2.4.0_vRC3.zip

**Comment by mykljohn** [comment]
I tried to install this upgrade and I receive a message saying it has to be at least 2.3.49.
