### ISSUE TITLE
Accounts and Contacts

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2213]
I have only found this issue in accounts and contacts.  you can create each one, import a list this all works.  The issue is when going to the List and clicking on any contacts row or accounts row it opens a blank page.  No other error. if you would like a screen show just let me know and ill post one.  Sorry some how put this in the wroung place it needs togo under _new-Layout

**Comment by nikdejan** [comment]
use screentogif software

**Comment by jbmcclain** [comment]
![contacts and accounts](https://cloud.githubusercontent.com/assets/1903662/10859983/398a9db8-7f39-11e5-892c-b2ccef2b3129.gif)

**Comment by bpabiszczak** [comment]
ISE 500 = Server error. You should check server logs.
This version is not yet ready for testing.
