### ISSUE TITLE
[Question] - hiding blocks depend on owner

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2214]
I tried to hide block of fields of financial summary 
![image](https://cloud.githubusercontent.com/assets/11491482/10859689/30ffd510-7f60-11e5-8dcd-25f8983465e0.png)
for users which are not owner. But management board has to have access to it - few users... 
the rest information of accounts should be public 
I tied to use option of hiding blocks but couldn’t succeeded. 
can you help...

**Comment by bpabiszczak** [comment]
To manage the visibility of fields is a tool profiles.

**Comment by witer30** [comment]
I know but this tool will change visibility permanently and I need to hide fields or the whole block only for records which user is not owner, for his records I would like to have these fields visible...  
Dnia 31 października 2015 0:14 Błażej Pabiszczak napisał(a):
 To manage the visibility of fields is a tool profiles.—

**Comment by bpabiszczak** [comment]
You can not do this from the panel. You need for this programmer.
