### ISSUE TITLE
[bug] calendar

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2215]
vversion 2.3.49
Main calendar is not reading other users and groups...

![image](https://cloud.githubusercontent.com/assets/11491482/10860128/c838a7c8-7f64-11e5-8c1c-2c7cf7f892ff.png)

**Comment by bpabiszczak** [comment]
You must set option here: https://gitdeveloper.yetiforce.com/index.php?module=Roles&parent=Settings&view=Edit&record=H10

**Comment by witer30** [comment]
thanks, works...
Dnia 31 października 2015 0:22 Błażej Pabiszczak napisał(a):
 You must set option here: https://gitdeveloper.yetiforce.com/index.php?module=Roles&amp;parent=Settings&amp;view=Edit&amp;record=H10—
