### ISSUE TITLE
Filename field not visible create a workflow for document module

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2218]
I create a workflow to send an email everytime a document is added or modified.  Among the field i like to send in the email is FILENAME, but i can see it in the ADD FIELD PICKLIST when creating TASK.

![addtask](https://cloud.githubusercontent.com/assets/12039062/10864447/a6da91a8-7fc4-11e5-9b35-b0cb08b2d381.jpg)

**Comment by konadrian** [comment]
this field exists in current version
![title](https://cloud.githubusercontent.com/assets/3193498/15176018/73f5f8b2-1769-11e6-8ba9-3630b8a99f2e.png)
