### ISSUE TITLE
Problem z usługami

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#2219]
Nie wiem czy to błąd oprogramowania czy nieprawidłowe ustawienia albo zła obsługa ale mam dodadną uługę z ceną 1500 jeśli ja ją dodaję do kalkulacji to dodaje się z ceną 1500 jeśli inny użytkownik to cena jest 1
wersja 2.3.49 ten sam problem występuje na wersji testowej
![crm-uslugi](https://cloud.githubusercontent.com/assets/15170959/10864509/4049f70e-7ff0-11e5-9bc2-557f8e44add8.gif)

**Comment by bpabiszczak** [comment]
Wynika to ze źle obsługiwanego formatu ustawionego na użytkowniku [ma pewnie jako separator tysięcy ustawioną spację]. Już to ktoś zgłosił i czeka na poprawkę. Wystarczy na userze poprawić format na taki bez spacji...

**Comment by bpabiszczak** [comment]
Format poprawiliśmy dla nowego typu modułu z produktami....

**Comment by mmstrzelec** [comment]
Ok ale nie bez spacji tylko Cyfrowy wzorzec grupowania	musi być - 123456789
