### ISSUE TITLE
Latest Dev Version

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2220]
FYI...I just installed the latest Dev version, and the Menus aren't defined in Languages I guess

![screenshot_3](https://cloud.githubusercontent.com/assets/11919990/10865941/46e7efde-7fe2-11e5-994a-2f863c6169cf.png)

**Comment by mykljohn** [comment]
Sunday I upgraded our test system to 2.34 and everything went fine.  I tested and everything looked good, so I upgraded production (backed it up first)
Monday when I logged in, all the labels were gone.  This is really critical.  The production site has no labels.  so the menus are for example  MEN_SALESORDER
I looked in the translations and they are all there along with my custom Translations (which appear to show up).

**Comment by reeid** [comment]
chmod. chown?

**Comment by mykljohn** [comment]
We're hosted on HostGator...how can I check?  The permissions on the directories and files is 755

**Comment by mykljohn** [comment]
I just found these errrors coming up in the log file.

Line 755854: [06-Nov-2015 04:15:38 America/Mexico_City] PHP Strict Standards:  Non-static method Vtiger_Menu_Model::getParentMenu() should not be called statically in /home1/globo/public_html/yeti/modules/Vtiger/models/Menu.php on line 72
	Line 755857: [06-Nov-2015 04:15:38 America/Mexico_City] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /home1/globo/public_html/yeti/modules/Vtiger/models/Menu.php on line 41

**Comment by mykljohn** [comment]
@bpabiszczak  Any word on the label problem yet?

**Comment by bpabiszczak** [comment]
The problem has now been resolved. If reappears, open a new issue.

**Comment by mykljohn** [comment]
Great, which update do I need to install?

**Comment by bpabiszczak** [comment]
Why u need update :P This is dev version not stable.

**Comment by bpabiszczak** [comment]
Try this: 
1. https://github.com/YetiForceCompany/YetiForceCRM/commit/a134ff7fbf41088208f7b9dd18b8c259dad74e42
2. https://github.com/YetiForceCompany/YetiForceCRM/commit/3057cd6714347a57cb41b30117800e77b5c7213f

**Comment by bpabiszczak** [comment]
We repaired it before, but I do not remember where. The problem is in this revision: https://github.com/YetiForceCompany/YetiForceCRM/commit/5170efd08d9af845b3c4370249686ccc31cf9dc1 [probably]
