### ISSUE TITLE
[Problem] Upgrade 2.3.0_to_2.4.0_vRC3

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2221]
OK, Upgraded to 2.4 and got the error "Cannot create references to elements of a temporary array expression in /yeti_test/vtlib/Vtiger/Functions.php on line 275"

    foreach (explode(',', $info['fieldname']) as &$fieldname) {

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by mykljohn** [comment]
Sorry, I'll post it in Upgrades next time.

**Comment by mykljohn** [comment]
I think I figured out what's happening.  The upgrade is resting the php configuration on the server.  I had to go in and reset if to php5.5 and all's good.

**Comment by mykljohn** [comment]
Ok, this is weird.  When I logged in today, all the labels appear to be gone.

![screenshot_4](https://cloud.githubusercontent.com/assets/11919990/10891590/6b7e5eae-8164-11e5-91f3-e63a3e4ed572.png)
