### ISSUE TITLE
Upgrade issue - Warning 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2223]
When running update from 2.3.49 to 2.3.193 I got below warning 

Warning: copy(/home/xxx/public_html//.htaccess): failed to open stream: Permission denied in /home/xxx/public_html/vtlib/Vtiger/Functions.php on line 1202

my document root is (from php.ini)
DOCUMENT_ROOT	/home/xxx/public_html

Prawa dostępu do folderu 
drwxrwxrwx 17 www-data www-data 4096 paź 31 01:58 public_html

It is strange why it display like this
![image](https://cloud.githubusercontent.com/assets/11491482/10869266/eb9fec76-80a9-11e5-9416-242f23072cfa.png)

**Comment by witer30** [comment]
forgot to mentioned that upgrade was successful

**Comment by bpabiszczak** [comment]
1. To nie jest problem aplikacji tylko uprawnień na poziomie serwera, widocznie htaccess jest tam na innych uprawnieniach lub ma jakąś "flagę" ustawioną. Problem do omówienia z administratorem serwera.

2. Sprawdź plik config.inc.php może tam w root_directory masz dwa razy znak //. O ile wiem, nie stanowi to żadnego problemu [chyba] bo system działa poprawnie z tymi dwoma znakami.
