### ISSUE TITLE
[bug] - error durign eksporting to pdf

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2225]
Version 2.3.193
when trying to export quote to pdf from quotes records page 
![image](https://cloud.githubusercontent.com/assets/11491482/10870117/d2c67076-80c2-11e5-9aa5-f7e35cd4e703.png)
I got this error
![image](https://cloud.githubusercontent.com/assets/11491482/10870119/e4e1ca26-80c2-11e5-9911-29220bf6acb8.png)

but there is not chmod issue as I have 
![image](https://cloud.githubusercontent.com/assets/11491482/10870122/ffdf3976-80c2-11e5-8634-3e842852f068.png)

I checked code of the /modules/OSSPdf/PDFExport.php
nad there are records of 
chmod('storage', 0777);
which generate my errors.
Why it it happen when my storage folder has chmod 777. 

Additionally when I open this quote and use button to generate pdf it works
![image](https://cloud.githubusercontent.com/assets/11491482/10870140/79f5a6aa-80c3-11e5-89bb-a200a0fcba08.png)

I know that you are working on new PDF module but can you check this with new module...

**Comment by florek41** [comment]
As I know new module is being completely rewritten ,so this bug is not corresponding to it.

**Comment by bpabiszczak** [comment]
Please test new PDF module.
