### ISSUE TITLE
Path for storing all pdf-s

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2228]
After restoring backup manually all pdf-s generated via CRM are stored in main folder public_html instead of storage/.. ? 
How I can change default path for storing pdf-s... 

Thanks

**Comment by bpabiszczak** [comment]
Why do you want to change the path?

**Comment by witer30** [comment]
Because all pdf-s are stored in mail folder where CRm is installed. And I would like to have default location storage/...

**Comment by witer30** [comment]
I solved my problem it was link to server site...
