### ISSUE TITLE
Bootstrap.

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2230]
On yeticrm 2.2 i can see the main menu on my phone or tablet.

Now, i have 2.3.88 developer but i can see any menu on any phone or tablet.

Why this happen?

**Comment by bpabiszczak** [comment]
Please check this: https://layout.yetiforce.com [admin/admin]

**Comment by josephballester** [comment]
Its great. I download it but when try to install it remains in the following screen.
![mainpage](https://cloud.githubusercontent.com/assets/12039062/10910096/c4822b48-8213-11e5-9243-23650e0bb6aa.jpg)

Try to change language, to install and to migrate but its do not move forward. Just remain in that page.

**Comment by bpabiszczak** [comment]
This version is not a version for installation. You have to wait for the final version.
