### ISSUE TITLE
email ticket attachment

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2232]
version 2.3.49 php 5.5 centos
When a ticket is created from an email with an attachment, the attachment is not attached to the ticket in documents.

Also, the corporate email is not automatically attached to the ticket.

How can this be done

**Comment by nuno-robosavvy** [comment]
This is a bit annoying as you don't have any info from where the ticket came (no from) or any link to the original email

**Comment by nikdejan** [comment]
I also think than corporate email should be attached to the ticket as well as document (mail attachment).

**Comment by nuno-robosavvy** [comment]
To attach the email to the ticket I added the following code to the file
/modules/OSSMailScanner/email_actions/1_created_HelpDesk.php 

        $adb->pquery("UPDATE vtiger_crmentity SET createdtime = ?,smcreatorid = ?,modifiedby = ?  WHERE crmid = ? ", array($mailDetail['udate_formated'], $assigned_user_id, $assigned_user_id, $id));

        // start of robosavvy custom code
        
        if ($mailDetail['ossmailviewid'] == '') {
            $result_ossmailview = $adb->pquery("SELECT ossmailviewid FROM vtiger_ossmailview where uid = ? AND rc_user = ? ", [$mailDetail['message_id'], $user_id]);
            if ($adb->num_rows($result_ossmailview) == 0) {
                return FALSE;
            }
            $mailViewId = $adb->query_result($result_ossmailview, 0, 'ossmailviewid');
        } else {
            $mailViewId = $mailDetail['ossmailviewid'];
        }
        
        $adb->pquery('INSERT INTO vtiger_ossmailview_relation SET ossmailviewid=?, crmid=?, date=?', [$mailViewId, $id, $mailDetail['udate_formated']]);
        // end of robosavvy custom code
    }
    return Array('created_HelpDesk' => $id);

**Comment by nikdejan** [comment]
@nuno-robosavvy good job! And what about attachments? Can they also be attached to ticket as documents?
