### ISSUE TITLE
SMS Notifier

### ISSUE THREAD

**Issue by sangeetasoni19** [YetiForceCompany/YetiForceCRM#2234]
I cannot find the settings for SMS Notifier

**Comment by sangeetasoni19** [comment]
Howto add providers other than Clickatell?

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=SMSNotifier&parent=Settings&view=List

**Comment by sangeetasoni19** [comment]
Howto add providers other than Clickatell?

**Comment by bpabiszczak** [comment]
You need create new file here: https://github.com/YetiForceCompany/YetiForceCRM/tree/stable/modules/SMSNotifier/providers please check this file https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/modules/SMSNotifier/providers/MyProvider.php
