### ISSUE TITLE
yetiforce new layout remains on main installation page

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2235]
I just download YetiForceCRm New layout from githp.  When trying the installation it remains in this page.

![mainpage](https://cloud.githubusercontent.com/assets/12039062/10909697/37b84884-8211-11e5-98d7-522837cc547e.jpg)

I try use every option, TRY TO CHANGE LANGUAGE, PRESS INSTALL, PRESS MIGRATION, but it remains in this page. No loading icon or something is similar is displayed.

**Comment by bpabiszczak** [comment]
Try last version gitdevelope.
