### ISSUE TITLE
[Bug] - Calendar and timing issue

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2236]
tested on gitdevelorer
version 2.3.237

there is issue with time in the calendar. When you have to set 2 records started at the same time there is issue with time displaying. Let say that in the callendar there are some records which start at the same time...
1. creating another record from -  8:00 till 9:15
![image](https://cloud.githubusercontent.com/assets/11491482/10911113/80886c92-8243-11e5-8467-021ceeba91d4.png)
2. Result in the calendar - showing 9:00 instead of 8:00
![image](https://cloud.githubusercontent.com/assets/11491482/10911068/3c415e04-8243-11e5-8785-7b9ed97c59c8.png)
3. Displaying details of the record - here is strange - showing meeting from 9:11 till 10:11 instead of 8:00 till 9:15
![image](https://cloud.githubusercontent.com/assets/11491482/10911102/6cc90202-8243-11e5-9399-f440affc4057.png)
4. When refresh calendar - 8:00 in the calendar is ok, but on details cloud there is mistake as should be 8:00 till 9:15...  
![image](https://cloud.githubusercontent.com/assets/11491482/10911250/3d5aaa56-8244-11e5-9c96-0c948cfb2bfb.png)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/e36c785120ae8c0ddd2a3ea0cf39c6c0b3ef5163
