### ISSUE TITLE
[bug] pick product to invoice

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2237]
Picking product to invoice do not work
![invoice](https://cloud.githubusercontent.com/assets/10330264/10913796/2dd9909c-8258-11e5-90b8-aeb502879e09.gif)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/46f13f76b98eb9e3dab621a3993ef3a9291114d9
