### ISSUE TITLE
[bug] Reports

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2238]
Amounts (totals, sub totals, etc) of invoices and quotes does not print out on reports.

![reports](https://cloud.githubusercontent.com/assets/10330264/10914100/86a0ad90-8259-11e5-8005-d90919e2f5f1.png)

**Comment by bpabiszczak** [comment]
Dupliate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2110
