### ISSUE TITLE
Where a standard module Google?

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#224]
Why your system does not Google standard module, very convenient to use it to sync contacts with Google account and the phone respectively, to synchronize your calendar, and view a map with the address of the company address or contact or project

**Comment by bpabiszczak** [comment]
If you ask about a module that was available in Vtiger 6.0. and Vtiger 6.1., we think that it couldn’t be called a functionality. Nothing worked there as it should work, that’s why we removed the module. Vtiger made a new version of this module available for version 6.2., but unfortunately I don’t know how it works  and whether we would like to integrate it with Google. Probably we will use a standard format for calendar and contact data exchange, every software that supports standards will be able to be integrated (including Google).

We are going to publish new functionalities for mobiles soon.
