### ISSUE TITLE
[Bug] - Calendar notification

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2242]
developer version.
where there is notification and you click green button there window with status popup then you have to choose status 
![image](https://cloud.githubusercontent.com/assets/11491482/10923891/a8b1744e-8283-11e5-8e45-626301288d6c.png)
and and when click cancelled or completed or postponed then automatically window of create new event appears 
![image](https://cloud.githubusercontent.com/assets/11491482/10923906/bd5f7e7c-8283-11e5-9304-97df2ac3cd5e.png)
Only closed button works ok

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/04837569cf286f3cb46953403eefc413f31835a4
