### ISSUE TITLE
[Question] Regarding Leads

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2243]
I was just looking at Leads after upgrading and I noticed several things. 

1. The First Name field was removed from the module but still exists in the Table (all data still there)
2. How do you convert a Lead to a Contact?
3. When you click send email, it populates the Send To field in Roundcube with the email address.  Why can't it do that from other modules (i.e. Quotes, Sales Orders,  Etc.?)  What code is called to do this?  I will look into change Quotes.

**Comment by PercyP** [comment]
Hi,

Ref: 2. 

I too noticed we can no longer convert leads - in vtiger we used to be able to convert a lead to an account, contact or both. Is this not a possibility in yetiforce?

**Comment by PercyP** [comment]
I have been playing around with it - my error, you have to first set the lead status then save, and also select B2C or B2B then it allows you to convert.

One question, Is it possible to convert on Mass? Or do we have to do it one lead at a time?

**Comment by bpabiszczak** [comment]
1. One issue one question.

2. Conversion is available when the lead has the appropriate status. More specifically, the status that has been set in the configuration here:https://gitdeveloper.yetiforce.com/index.php?module=MarketingProcesses&view=Index&parent=Settings&block=6&fieldid=83

3. At the moment I don't think there's much sense to add mass lead conversion ... each case should be considered individually.
