### ISSUE TITLE
create invoice from sales order missing opportunity

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#2245]
when create invoice from sales order
or create assets from invoice
system will not pass the opportunity with maintained in source order or invoice to target fields in invoice or asset
Version 2.3.49
![image](https://cloud.githubusercontent.com/assets/15126825/10938892/f9f7548c-8340-11e5-90e5-e8ca697cbdd6.png)
![image](https://cloud.githubusercontent.com/assets/15126825/10938904/12b1f6d0-8341-11e5-8887-8f0049c497dc.png)

**Comment by paula-w** [comment]
Can you please rephrase it a little? We don't understand what you mean.

**Comment by florek41** [comment]
when you create invoice (form SO) you get empty **Oppotunity** filed in the invoice creating form. Even if in the SO **Opportunity** is selected.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2461
