### ISSUE TITLE
[Problem] Labels Disappeared

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2247]
Ok, this is weird. When I logged in today, all the labels appear to be gone. Everything was fine last night when I logged out.

![screenshot_4](https://cloud.githubusercontent.com/assets/11919990/10946308/3abe7928-82e7-11e5-9bd0-ce244a4ab61b.png)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2220
