### ISSUE TITLE
Request/enhancement: Purchase order

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#2248]
For Purchase orders.
We use this to record purchases we make to our suppliers than we then resell to our customers.

When entering a purchase order, there should be a bill to name and address, which is us.
There is also a ship to address. Can we have an option of choosing the account this goes to. So instead of the application asking to enter the vendor ship to address, it should be the accompying customer ship to or if it is a product used by us and not for resale, ship to self.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2461
