### ISSUE TITLE
Adding relation between modules

### ISSUE THREAD

**Issue by sangeetasoni19** [YetiForceCompany/YetiForceCRM#2249]
How to add relation between modules?
I cannot see any button that adds relation in Arrange related Tabs.

**Comment by mariuszkrzaczkowski** [comment]
Change in the config/developer.php file line:
// Adding/Deleting relations between modules.
'CHANGE_RELATIONS' => true,
See here: https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&block=2&fieldid=41

**Comment by sangeetasoni19** [comment]
Thanks a lot
