### ISSUE TITLE
[BUG] CalDav not working properly

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2252]
I need to sync calendar across few devices. My test devices/systems is:
- YF 2.3.88 (with working dav)
- Iphone IOS 7
- calendar with dav sync. (Horde webmail/calendar for tests)

When I finally configure Iphone to use YF dav (need to add full pricipal path, eg. www.domain.com/YFDIR/api/dav.php/principals/USER ) it do not sync to Iphone calendar but only to Iphonereminders (not visible in calendars).

When add same path in Horde it don't sync calendar too.

When I add anything to YFCalendar in Iphone it is visible in Horde but not in YF system. Same when add/change in Horde - it is visible on Iphone but not in YF.

Am I missing something ?

**Comment by florek41** [comment]
Caldav hangs on lastest dev version (tested on gitdeveloper)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2701

**Comment by mariuszkrzaczkowski** [comment]
Please test the CalDAV integration with the latest CRM version. 
We updated the library  responsible for communication to the latest version, and we improved debugging.
We added info about the configuration of DAV servers connection to the panel with DAV keys.
