### ISSUE TITLE
Access Rights in the Projects Module 

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2253]
I have custom fields in the project module that users will fill out.  Some of the fields are sensitive data,  only the creator and manager should be able to see.  I have about 5 users that will be interning in the sensitive data into some of the custom fields.  These 5 users should be able to see there sensitive  data as well as mangers but, the 5 users should not be able to see each others sensitive data in these fields but they should be able to see all the other fields within the project module.  Is there a way to hide the certain fields if you are not a manger and or the creator?

Thanks!

**Comment by witer30** [comment]
here you can hide even single field for user or groupe users base on the Profiles
https://test.yetiforce.com/index.php?module=Profiles&parent=Settings&view=Detail&record=2

**Comment by jbmcclain** [comment]
@witer30 Yes i know you can do that based on profiles. Thank you. The only way this method would work is duplicating each field for each user and give each user a different profile.  I think that would be bit much to manage.

**Comment by witer30** [comment]
or you can assign all users to one profile - if possible - less job...

**Comment by jbmcclain** [comment]
The solution i found was creating a new module and making the settings private and linking it to the project its self.  this way only the person who make the new entry has access and Managers.  Just incase someone comes along and needing a solution...
