### ISSUE TITLE
New layout - v. 2.3.267

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2254]
there are some issues with new version of layout.
![animation 0](https://cloud.githubusercontent.com/assets/11491482/11007333/7cfd2486-84c9-11e5-8842-a1229b40840d.gif)
by the way it is very nice...

**Comment by mykljohn** [comment]
@witer30 I just upgrade from 2.2x to 2.30 > 2.349...how can I see this new layout?

It looks very nice.  More importantly, all my menus have disappeared issue #2247, #2220 
any idea what would cause that and how can I fix it?

**Comment by bpabiszczak** [comment]
We need 1/2 days more to fix all bugs.

**Comment by mykljohn** [comment]
OK, I'll have to wait :)

**Comment by witer30** [comment]
new layout you can see here https://gitdeveloper.yetiforce.com/
during log on please choose YF - new layout... 
Concerning your issues I think you have to upgrade to version 2.3.193 as I saw in merge doc that some improvement was done with menus... 
https://github.com/YetiForceCompany/UpdatePackages/blob/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip/2.3.0_to_2.4.0_vRC3.zip
Please also see doc
https://yetiforce.com/en/implementer/installation-updates/176-system-update-not-verified.html

**Comment by reeid** [comment]
In old layout when I get to record detail I can see both right related tabs tree and left panel for various operations. New layout got only right related list. Am I overlooked something?

**Comment by bpabiszczak** [comment]
reed: one question one issue.
