### ISSUE TITLE
Record details - for every module 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2255]
![image](https://cloud.githubusercontent.com/assets/11491482/11007519/b543e838-84ca-11e5-9af2-e69315a9eb8e.png)

**Comment by rskrzypczak** [comment]
The button is unnecessary because there's a link to the records list.
![button1](https://cloud.githubusercontent.com/assets/10221999/11271793/c1986624-8ec8-11e5-964c-68d2433aef26.jpg)

**Comment by witer30** [comment]
ok, thanks now I see... maybe it is worth to underline it to show that is link...
