### ISSUE TITLE
[Improvement] - callendar and user records

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2256]
version 2.3.194
I have few users and want to see their calendar. 
I switch on this by right panel - every user is on to see entries in the calendar.
![image](https://cloud.githubusercontent.com/assets/11491482/11009417/fadc06e4-84d6-11e5-985b-d90c2fc278f8.png)

But when I move to another module and came back to calendar only current log on user remain on to show entries in the calendar. 
![image](https://cloud.githubusercontent.com/assets/11491482/11009507/c16aee2e-84d7-11e5-9a84-f0fa14a03139.png)

On new version means layout a right panel is hide so maybe it would be better to have situation when I switch on users to see them in the calendar than they should be constant on till moment when I decide to switch them off...

**Comment by bpabiszczak** [comment]
1. After enabling the users, be sure to click the refresh icon on the right side when choosing the user.

2. The system does not store the configuration information, so refreshing the page will bring back the original settings. In the future we want to store this information.
