### ISSUE TITLE
Add Attachment (docs, images, etc) in COMMENTS

### ISSUE THREAD

**Issue by josephballester** [YetiForceCompany/YetiForceCRM#2258]
Im wondering if there is a chance to add an upload option in COMMENT modules.  

I know it can be done in the document module, but adding documents or images in the comment module will be faster because you dont have to fill some extra fields. 

Document or images uploaded in comment should be a separate repository of the document module.  EspoCRM have both option and i think it would be greate if yeti have it because this is a great CRM.

**Comment by nikdejan** [comment]
+1

**Comment by florek41** [comment]
+1

**Comment by bpabiszczak** [comment]
Currently we aren't planning to implement a functionality like this.
