### ISSUE TITLE
synchronizacja CalDAV oraz CardDAV 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2259]
wersja 2.3.194
Znalazłem klienta do synchronizacji z Yeti oraz outlook... 
http://sourceforge.net/projects/outlookcaldavsynchronizer/
Pzeczytałem wszystkie tickety odnoszące się do protokołu DAV zaimplementowanego w YF. 
I zacząłem próbować potestować synchronizacje. No ale jak to bywa natrafiłem na problem. 
Oto moja konfiguracja
![image](https://cloud.githubusercontent.com/assets/11491482/11017300/d82bf496-859a-11e5-963f-7a1fb72d40b1.png)
Przy próbie testu połączenia dostaje taki błąd
![image](https://cloud.githubusercontent.com/assets/11491482/11017302/26b22932-859b-11e5-92e0-a58a3e5e60d7.png)
Mam prośbę czy może ktoś przetestować tego klienta synchronizacji tak aby sprawdzić czy on działa z YF...?

Z góry dzięki

**Comment by bpabiszczak** [comment]
1. ISE to błąd serwera nie aplikacji!
2. My [o ile dobrze pamiętam] używamy autoryzacji AUTH-BASIC więc trzeba ustawić [chyba] taką na kliencie. 
3. Wiem, że był jakiś błąd w DAV i był poprawiany, ale nie pamiętam w której rewizji.

**Comment by witer30** [comment]
Dzięki za odpowiedź...
Ponieważ server for DAV to SabreDAV 2.1.3  więc to jest błąd servera Sabre a nie Apache... 
Proszę zobacz wpis odnośnie klienta...
"
Hi,"(500) Interner Serverfehler." means that the Bug lies inside your Server (SabreDAV)Please turn on DEBUG log and retry it (Intructions can be found at https://sourceforge.net/p/outlookcaldavsynchronizer/code/ci/master/tree/README.md ) Then you can see the URI of the event which caused the error in the logfile. If you paste this URI into the address bar of your browser you should get the same error.
"
Cały wątek jest pod adresem
https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/58 
gdzie jest wyraźnie napisane że jest bug w wersji Sabre 2.1.3... 
Może to jakość pomoże rozwiązać i zlokalizować ten problem... 
Czy jest możliwość przetestowania servera Sabre przez www...?

**Comment by florek41** [comment]
Też aktualnie walczę z synchronizacją, ale raczej aplikacji mobilnych (iPhone, Android) zamiast Outlook.

spróbuj jako adres podać:
192.168.0.13/api/dav.php/principals/Krzysztof
z tego co wyczytałem to taki problem ma właśnie iOS z sabreDav, ale może i w tej sytuacji zadziała.

chociaż błąd 500 to co innego niż u mnie. #2252

**Comment by bpabiszczak** [comment]
Mariusz ostatnio wprowadzał poprawki do DAV fixujące jakiś problem. DAV jest włączony domyślnie na wersji GitDeveloper więc można się testowo podpiąć pod nią. Błąd 500 to błąd serwera i tu nie ma dyskusji. Za nim my coś zrobimy, to trzeba sprawdzić w logach APACHE czemu postanowił pokazać błąd 500.

**Comment by witer30** [comment]
Tu moje przeprosiny do zespołu YF, jednak błąd leży po stronie mojego serwera.
Przed chwilą sprawdziłem tego klienta z https://test.yetiforce.com/ no i działa, bo test łączności jest ok i wyświetla kalendarz oraz skrzynkę adresową... 
Moje przeprosiny jeszcze raz będę szukał dalej co to do cholery jest na moim serwerze bo ręce mi opadają już.....

PS. odnośnie logów Apache to sprawdze

**Comment by bpabiszczak** [comment]
Tutaj nie ma kogo i za co przepraszać. Już w pierwszym poście Tobie napisałem, że błąd jest po stronie Apache. Po to jesteśmy aby pomagać i odpowiadać.

O ile dobrze pamiętam, to do poprawnego działania książki adresowej, jest potrzebny włączony CRON, bo on generuje co jakiś czas taką książkę adresową do synchronizacji aby nie robić tego w czasie rzeczywistym.

**Comment by witer30** [comment]
A jeszcze takie szybkie pytanie,
Bo w logach Apache nic nie ma, jak zrobię literówkę to mi na zywo wywala 404 w logu ale jak jest url ok to błąd 500 bez żadnego wpisu w logu. To troche dziwne...
Czy jakies biblioteki w php powinny być zainstalowane do DAV? Może tu jest problem?
Reszta działa...

**Comment by mariuszkrzaczkowski** [comment]
Aby w logach pojawiły sie wpisy musisz ustawić w .htacces:
 php_flag log_errors On
