### ISSUE TITLE
Create Project Tasks from YetiForce Portal

### ISSUE THREAD

**Issue by MaciejStencel** [YetiForceCompany/YetiForceCRM#226]
Clients should be allowed to add Project Tasks and not only Help Desk tickets. 
Clients from portal can create new tickets for assigned project.

It would be great if it would be distinguished that clients can add new tickets for existing errors in project that needs to be fixed asap and for example project tasks for new features, new tasks, new modifications.

As of now clients are able to view and create only tickets. They cannot add or view project tasks.

What is our community thinking about that?

**Comment by waran70** [comment]
It is great idea what will extend functionality. Would be  perfect to be able to upload files to particular task and create tickets for existing tasks.

**Comment by waran70** [comment]
Another crucial function would be possibility to create access levels. For instance different portal for supplies, customers, employees or kind of "portal user profile" with more options to build privileges.
In vtiger here is thread: https://discussions.vtiger.com/index.php?p=/discussion/172996/customer-portal-business-requirements/p1 what can be a starting guidance. 
In my opinion contemporary portal dont need to be very different than yetiforce is. Therefore in could be an option to start from what we have build in crm itself. Not sure only about complexity of getting portal on crm engine basis. Probably privileges will be the most complicated

**Comment by MaciejStencel** [comment]
Thread pushed to mailing list.
