### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'price' in 'field list'

### ISSUE THREAD

**Issue by AndrGelmini** [YetiForceCompany/YetiForceCRM#2261]
Hello..

It is from a few days to try to find a solution to the above message in the subject.

So I explain to you what I did:

I created a custom module called Pippo (advanced)
After that, I created a sotruttura Basic verse composed as follows.

![img uno](http://res.cloudinary.com/studioaef/image/upload/v1446998106/Schermata_del_2015-11-08_16_40_09_b9ugx7.png)

The message appears when I go to careate a list of products and services and try to save the record.

![img due](http://res.cloudinary.com/studioaef/image/upload/v1446998106/Schermata_del_2015-11-08_16_39_23_eykkp4.png)

I do not think the list of products and services does not appear is the record is saved as usual.

I hope I can help.

**Comment by bpabiszczak** [comment]
version?

**Comment by AndrGelmini** [comment]
I forgot to give you this info.
Installed version: 2.3.49
branches: Developer

**Comment by AndrGelmini** [comment]
I wanted segnalare this thing :
I Deleted everything and I Put :

item name
quantity
price unit
net

 and now showing the error is :

SQLSTATE [ 42S22 ] : Column not found : 1054 Unknown column ' name ' in ' field list '

**Comment by bpabiszczak** [comment]
It is experimental functionality. See the last version of the developer.
