### ISSUE TITLE
[enhancement] Merge few sales orders into one invoice.

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2265]
Currently we have situation when one client have ex. 5 sale orders (and related projects/tasks/mails etc) and I want to merge it into one invoice with products/services form every sale order.
This is not only merging (in current way) but more like summarize all selected records into one.

Invoice is document telling us that sale is completed and closed - every sale order is completed same as related projects, tasks etc.

This is very important function for me and I think for many YF users too.

If we could merge Opportunities, Sale Orders etc into one of them it will be great.
Just another way of merging. Smoething like in php we have:

```
(current merge function)
field_x = A
field_x = B 
so we have field_x = B 
```
or
```
summarize
field_x = A
field_x += B
so we have field_x = AB
```

**Comment by nikdejan** [comment]
+1

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
