### ISSUE TITLE
[Bug] Quotes Enquires and Requirement Cards not related to Opportunity

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2267]
In the related tabs of Opportunity there are Calculations, Quotes, SOrders, but not Enquires and Req. Cards. Maybe there is some purpose behind this inconsistency, which I do not understand?
Also, if I want to display related Enquires in Opportunity Summary View widget, I can not do that.

**Comment by nikdejan** [comment]
I found a solution in other Issue. I enabled relations addition/deletion in config/developer.php 
I think Quote Enquires and Requiremend Cards should be related with Opportunities by default, though.

**Comment by bpabiszczak** [comment]
In the new process, we will see all the related modules from the sales process level.
