### ISSUE TITLE
[Improvement] Documents module

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2268]
In checking out Documents functionality...it would be nice to be able to view the document online without having to download it. (whether with PDF viewer or Word viewer.)

Since the doc in question was a word doc, I put the text into the note field to see it online.  worked fine, but then realized it would be nice to be able to print it from there.  just some thoughts.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2052
