### ISSUE TITLE
Error!!! DateTime::__construct(): Failed to parse time string (2015-11-11 10:41 AM AM) at position 20 (A): The timezone could not be found in the database  Go back 

### ISSUE THREAD

**Issue by noclav** [YetiForceCompany/YetiForceCRM#2269]
I get this error Error!!!
DateTime::__construct(): Failed to parse time string (2015-11-11 10:41 AM AM) at position 20 (A): The timezone could not be found in the database

When i click on Time Control > Add Record > Go to Full Form.  

Server Info 
Distributor ID: Debian
Description:    Debian GNU/Linux 7.9 (wheezy)
Release:        7.9

PHP 5.5.30-1~dotdeb+7.1 (cli) (built: Oct  1 2015 17:38:39)

MYSQL info
+-------------------------+---------------------+
| Variable_name           | Value               |
+-------------------------+---------------------+
| innodb_version          | 5.6.25              |
| protocol_version        | 10                  |
| slave_type_conversions  |                     |
| version                 | 5.6.25-1~dotdeb+7.1 |
| version_comment         | (Debian)            |
| version_compile_machine | x86_64              |
| version_compile_os      | debian-linux-gnu    |
+-------------------------+---------------------+

 Apache/2.2.22 (Debian)

From what i found this is a Joomla bug. Any update for this?

**Comment by bpabiszczak** [comment]
YF version?

**Comment by noclav** [comment]
ver. 2.3.49

**Comment by bpabiszczak** [comment]
Please check whether the problem appears on the gitdeveloper version.

**Comment by noclav** [comment]
Im installing the Developer version and during the install where i enter the database info. Pressing the install button doensnt do anything. I see in the error.log File does not exist: /                             var/www/devportal.domain.com/public_html/layouts/vlayout/resources
If i copy the resources folder from the stable version then it works. 

Also if i click on GitDeveloper (https://gitdeveloper.yetiforce.com/ on the README.md i get Error!!!
CSRF protection: Hacking attempt detected

**Comment by noclav** [comment]
Note: If i login to your https://gitdeveloper.yetiforce.com/index.php site i can do the timecontrol without error.

**Comment by noclav** [comment]
I installed the Developer Version 2.3.320 and the same issue with when the install finishes it shows a white page. If i refresh i get the login screen and doesnt take the password i set only the default of admin. But Timecontrol works without error.

**Comment by bpabiszczak** [comment]
Please install system on PHP 5.6.

**Comment by bpabiszczak** [comment]
We fixed this problem on DEV [please check].

**Comment by webmastergta** [comment]
pleaseeeeee helpme   



Error!!!

DateTime::__construct(): Failed to parse time string (04-2018-10 08:00:00) at position 0 (0): Unexpected character
