### ISSUE TITLE
[Bug] - CardDav - issue with scanning numbers of contacts 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2270]
I have 5 contacts in CRM...

![image](https://cloud.githubusercontent.com/assets/11491482/11100319/cd932ad6-88b0-11e5-934e-f8522096ca98.png)

but CardDAV scancer is showing only one contact - strange situation and seems to be similar to CalDAV issue
![image](https://cloud.githubusercontent.com/assets/11491482/11100303/b78ebc14-88b0-11e5-9908-ac9bbef86edb.png)

**Comment by bpabiszczak** [comment]
Niestety z tym nie da się nic zrobić, ponieważ nie wiem jaka wersja, nic nie wiem o konfiguracji, nie wiem czy jest włączony cron i działa poprawnie [bo on odpowiada za generowanie danych do synchronizacji] itd.

**Comment by witer30** [comment]
Versja 2.3.193
Cron działa prawidłowo
Brak błędów php

**Comment by bpabiszczak** [comment]
To jeszcze należy włączyć logi DAV :D

**Comment by florek41** [comment]
to samo na gitdeveloper. Cron nie kończy zadania CalDav.

**Comment by bpabiszczak** [comment]
Programista który się zajmuje DAVem wraca w przyszłym tygodniu z urlopu i na to zerknie, ale z tego co ostatnio sprawdzał, to u niego działało prawidłowo.

**Comment by witer30** [comment]
Ok, a gdzie te logi się włącza bo przeszukałem większość plików i nie widzę tego...
Przepraszam za to pytanie ale no nie mogę znaleźć...

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/109-debugowanie.html

**Comment by witer30** [comment]
ok, to przyznam że nie rozumiem...
Prosiłeś o logi dav.log a to co podrzuciłeś to logi debugowania, zapis do xml oraz debugowanie dav do pliku davdebug.log... 
ale nie wiem gdzie włączyć te logi do pliku dav.log - tego co znalazłem w pliku 
/api/dav.php

linia 13     
```
ini_set('error_log',$root_directory.'cache/logs/dav.log');
```
to jak są włączone logi php to z automatu powinien zapisywać logi dav do dav.log...

Więc czy potrzebne są logi debugowania czy dav.log... 
Jak dav.log to nie mam pojęcia czemu się nie zapisują bo mam ustawiene w .htaccess  aby zapisywał logi... W php.ini mam error_reporting = A_ALL

**Comment by bpabiszczak** [comment]
To co wysłałem to miejsce w którym włącza się wszystkie logi związane z YF. Jest tam również sekcja odpowiedzialna za DAV. Na tej podstawie są tworzone pliki logów. 

Za bardzo kombinujecie. Kilkukrotnie podajemy wam plik w którym macie wszystko do włączenia, a szukacie w dziesięciu innych miejscach i sobie komplikujecie.

**Comment by witer30** [comment]
oto moje ustawienia
```
$DEBUG_CONFIG = [
	/* +***************************************************************
	 * 	CRM 
	 * ************************************************************** */

	// Enable log4php -> cache/logs/system.log
	'LOG4PHP_DEBUG' => false,
	// Stop the running process of the system if there is and error in sql query
	'SQL_DIE_ON_ERROR' => false,
	// Displays information about the tracking code when an error occurs. Available only with the active SQL_DIE_ON_ERROR = true
	'DISPLAY_DEBUG_BACKTRACE' => false,
	// Debug Viewer => cache/logs/viewer-debug.log
	'DEBUG_VIEWER' => false,
	// Display Smarty Debug Console
	'DISPLAY_DEBUG_VIEWER' => false,
	// Sabre dav - This is a flag that allow or not showing file, line and code of the exception in the returned XML
	'DAV_DEBUG_EXCEPTIONS' => true,
	// Activate the plugin recording log in DAV
	'DAV_DEBUG_PLUGIN' => true,
```

**Comment by bpabiszczak** [comment]
Zmień jeszcze w .htaccess log_error na On.

**Comment by witer30** [comment]
logi do dav.log sie nie zapisują bo może nie ma błędów...
Ale zauważyłem jedna rzecz, jak mam klucze DAV wygenerowane dla usera i cron działa tzn cardDAV skanuje, to kontakty, dodane w CRM po momencie wygenerowania kluczy DAV, dodaje i wskazuje ich liczbę... Dodałem dwóch i w sumie wskazuje mi że mam 3... prawidłowo...
ale czemu nie przeszukuje całej bazy danych kontaktów i ich nie zapisuje jako dodanych do dav... 
Czy tak ma po prostu działać...?
Jeśli tak to do zamknięcia...
Pozostaje tylko sprawdzić synchronizacje i jakie dane przesyła...

**Comment by witer30** [comment]
w .htaccess mam ustawione log_error On...

**Comment by bpabiszczak** [comment]
Kontakty są generowane przez CRON [należy sprawdzić, czy on nie generuje jakiś problemów]. Logi działają tak, że gdy są włączone to rejestrują one również poprawną komunikacje... więc w logach zawsze coś być powinno jeżeli są włączone. Kwestia tylko w których logach. 

Od DAV jest programista, jak wróci sprawdzi.

**Comment by witer30** [comment]
Kontakty w Sabre też się pokazały... 
![image](https://cloud.githubusercontent.com/assets/11491482/11132554/d42ad318-8990-11e5-8ea2-36c18bdf8705.png)

Co do logów to kur... u mnie jest coś nie tak bo nic nie ma w dav
w php.ini mam ustawione 
```
display_errors = On
display_startup_errors = On
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
```
mój htaccess
```
<IfModule mod_autoindex.c>
	Options -Indexes
</ifModule>
########################
<IfModule mod_rewrite.c>
	Options +FollowSymLinks
	RewriteEngine On
	RewriteRule ^favicon\.(gif|ico|png|jpe?g)$ layouts/vlayout/skins/images/favicon.ico [L,NC]
	RewriteRule ^api/webservice/(.*)/(.*)/(.*)$ api/webservice.php?module=$1&action=$2&record=$3 [QSA,NC,L]
	RewriteRule ^api/webservice/(.*)/(.*)$ api/webservice.php?module=$1&action=$2 [QSA,NC,L]
	RewriteRule ^api/webservice/(.*)$ api/webservice.php?module=$1 [QSA,NC,L]
</ifModule>
<IfModule mod_php5.c>
	php_flag	log_errors					On
	php_flag	display_errors				Off
	php_value	memory_limit				1024M
	php_flag	output_buffering			On
	php_flag    zlib.output_compression		Off
	php_flag	file_uploads				On

	#php_value	max_execution_time			1200
	#php_value	max_input_time				1200

	php_flag	magic_quotes_gpc			Off
	php_flag	magic_quotes_runtime        Off

	php_value	suhosin.request.max_vars	5000
	php_value	suhosin.post.max_vars		5000
	php_flag	suhosin.session.encrypt		Off

	php_flag	session.auto_start			Off
	php_value	session.gc_maxlifetime		21600
	php_value	session.gc_divisor			500
	php_value	session.gc_probability		1
	php_value	error_log					cache/logs/phpError.log
</IfModule>
########################
# <FilesMatch "\.(inc|php|php3|php4|php5|php6|phtml|phps)$">
# AddHandler x-httpd-php56 .inc .php .php3 .php4 .php5 .php6 .phtml
# </FilesMatch>
```

no wszystko powinno być ok...

**Comment by bpabiszczak** [comment]
tu nie ma zasady że htaccess musi działać, zależy to od konfiguracji Apache, jeżeli Apache nie pozwala na zmianę parametrów poprzez htaccess to trzeba to zmienić w konfiguracji apache i tam włączyć logi. 

Normalnie dla programisty znalezienie i włączenie wszystkich opcji związanych z logowanie to 1-5 min.

**Comment by witer30** [comment]
Tylko tak dla informacji
.htaccess działa, 
Nie chce tu czasu zabierać bo to po stronie servera logi są odpowiedzialne... Logi znajduje w odpowiednich plikach ubuntu wiec nie ma tu problemu... dziwi mnie tylko to że nie zapisują się logi crona do wskazanego miejsca... 
Crona wywołuje jako root...
```
*/5 * * * * sh /home/nakon/public_html/cron/vtigercron.sh &>>/home/nakon/public_html/cache/logs/cron.log
```

prawa do folderu logów ma user1 (przypisany do grupy www-data) oraz grupa www-data - prawa rwx...

**Comment by bpabiszczak** [comment]
Skoro nie zapisuje, to widać w logach apache czemu. Tu nie ma magii, to jest proste, tylko trzeba to rozumieć i wiedzieć gdzie szukać. Temat zamykam, bo rozumiem, że problemu już nie ma z DAV?
