### ISSUE TITLE
[bug] - setting up cron intervals

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2271]
developer version
![animation 1](https://cloud.githubusercontent.com/assets/11491482/11100483/df140a9a-88b1-11e5-8e40-b474dfb320f6.gif)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/a134ff7fbf41088208f7b9dd18b8c259dad74e42
