### ISSUE TITLE
Calendar - not working days

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2272]
![image](https://cloud.githubusercontent.com/assets/11491482/11100717/1c003d4c-88b3-11e5-80f4-d10da1018904.png)

when adjusted that saturday and sunday are not working days still calendar include these days
![image](https://cloud.githubusercontent.com/assets/11491482/11100742/54ab4312-88b3-11e5-871f-c1f631cd8748.png)
![image](https://cloud.githubusercontent.com/assets/11491482/11100754/65fccc94-88b3-11e5-88be-ae8041ecb125.png)

**Comment by bpabiszczak** [comment]
Ta opcja służy dla widżetu czasu pracy a nie dla kalendarza. W przyszłości będziemy kalendarz rozbudowywać, lecz teraz nie ma to wysokiego priorytetu.
