### ISSUE TITLE
Currency and admin password not set properly

### ISSUE THREAD

**Issue by nuno-robosavvy** [YetiForceCompany/YetiForceCRM#2274]
While installing from the zip file (2.3.49) the admin password and the default currency are not set properly.

Admin password is set to admin and currency is Polish Zloty

A workaround to fix this is:
Install and you will have Polish Zloty as default currency
Add your currency of preference
Go to database table 'vtiger_currency_info' and set 'default_id' to '-11' to your new default currency
set 'default_id' to '0' on Polish Zloty

now you have your default currency working

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2274

**Comment by bpabiszczak** [comment]
Fixed. Please check latest version.
