### ISSUE TITLE
[PL] YetiForce integracja Office365

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#2276]
Czy przewidujecie w przyszłości stworzenie modułu do integracji z Office365 lub może jest już jakieś rozwiązanie kompatybilne z YetiForce umożliwiające synchronizację rekordów kalendarza i kontaktów z Office365?

**Comment by bpabiszczak** [comment]
Jest dostępna integracja kontaktów i kalendarza za pomocą standardów CalDAV i CardDAV. Nie wiem czy Office wspiera takie standardy ale z tego co czytałem, to wspiera on tylko swój własny standard. Nie planujemy nic dodatkowego wdrażać.
