### ISSUE TITLE
[13-Nov-2015 12:19:56 Europe/Sarajevo] PHP Warning:  Invalid argument supplied for foreach() in /home/nakon/public_html/modules/Contacts/Contacts.php on line 1030

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2278]
version 2.3.193

**Comment by bpabiszczak** [comment]
PHP?

**Comment by witer30** [comment]
PHP Version 5.6.4-4ubuntu6.3

**Comment by bpabiszczak** [comment]
i jeszcze poproszę:
1. Jak wywołać błąd krok po kroku.
2. Czy błąd występuje na wersji developerskiej.

**Comment by witer30** [comment]
Błąd pochodzi z logów php...
Został zarejestrowany podczas tworzenia nowego kontaktu...
Odnośnie pytania 2 to nie mam dostępu do logów php... Sam CRM nie wyświetla błędów podczas pracy...
