### ISSUE TITLE
[bug] - [13-Nov-2015 16:45:05 Europe/Sarajevo] PHP Fatal error:  Call to a member function delete() on boolean in /home/nakon/public_html/modules/Settings/SharingAccess/actions/IndexAjax.php on line 69

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2280]
php version 5.6
yf version 2.3.193

error recorded in log of phperror.log life after changes of Permision -> Module access

**Comment by mariuszkrzaczkowski** [comment]
Require more information https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
