### ISSUE TITLE
CSRF Errors

### ISSUE THREAD

**Issue by yodacohen** [YetiForceCompany/YetiForceCRM#2281]
I just had help from SiteGround hosting with installation of V2.3.49.  All php variables were adjusted.  SiteGround is hosting an earlier version which runs with no problems.  I also have VTiger installed on SiteGround.  Both of these instances are installed in subdomains. 

Today has been extremely frustrating for me.  The program ran ok for awhile while I was logged in as admin.  However, in going to the "assets" database, it says that the database is restricted.  All folders are set for full access in mysql.  There are no restrictions set on the admin id. And yet, I began getting CSRF errors.  Cleared browser cache.  No go.  Cannot log out.  Folks, if this is as easy to install and run as VTiger, I'm not seeing it.  

I also find it interesting that the Yetiforce organization home page says "If you would like us to install the system for you - send us an email!!! "  Last spring I found that to be not the case, at least not without paying a significant fee.  The verbage is still there.

I'm not sure where to turn at this point.  It seems to be rather absurd to pay significant dollars to get a system to run at all when it actually was installed by linux server specialists at SiteGround hosting and STILL does not run properly.  Yes, it is a shared hosting environment, but there is no problem running an earlier version of Yetiforce or running VTiger in same hosted environment.  I really would like to show this product here in Houston to some well-known companiies in the energy industry, but at this point I am frustrated, embarrassed, and "dead in the water".  Not certain how to proceed.  Any help or comments would be very much appreciated.

**Comment by yodacohen** [comment]
update:  modified config.ini.php file to set CSRF=false.  This stopped the CSRF errors.  I haven't a clue what was consistently triggering these errors.  My PC appears clean of malware.  Errors were occurring both in Firefox and IE.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/secutity/183-ochrona-przed-atakami-csrf-2.html
