### ISSUE TITLE
external\server API

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2282]
Hello, and whether there is an external API, for making or receiving information by third-party applications?
Perhaps there are any examples?
And as well as I can provide an improved translation for CRM?

**Comment by kjradv** [comment]
I tried to go through the standard VTiger, but when querying webservice.php get a 500 error:
>Fatal error: Uncaught exception 'WebServiceException' with message 'Unknown operation requested' in LOCAL_PATH/include/Webservices/OperationManager.php:89 Stack trace: #0 LOCAL_PATH/include/Webservices/OperationManager.php(63): OperationManager->fillOperationDetails('') #1 LOCAL_PATH/webservice.php(76): OperationManager->OperationManager(Object(PearDatabase), '', 'json', Object(SessionManager)) #2 {main} thrown in LOCAL_PATH/include/Webservices/OperationManager.php on line 89

**Comment by bpabiszczak** [comment]
Old API for CP: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/api/yetiportal.php
New API for CP [in construction] https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/api/webservice
