### ISSUE TITLE
[Bug] - Admin panel > users

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2284]
![animation 0](https://cloud.githubusercontent.com/assets/11491482/11186902/4e62c370-8c84-11e5-860b-750f55b6548c.gif)

**Comment by rskrzypczak** [comment]
FIxed in https://github.com/YetiForceCompany/YetiForceCRM/commit/a47df88446c00ec5037f2b5a919e15245fde0713
