### ISSUE TITLE
Problem z konfiguracją serwera SMTP

### ISSUE THREAD

**Issue by sith5** [YetiForceCompany/YetiForceCRM#2289]
Witam,
Zainstalowałem na czysto cała aplikację i próbuje skonfigurwać serwer SMTP. Niestety otrzymuje komunikat: 
**Status maila testowego  Nie można było wysłać wiadomości e-mail do administratora. Proszę sprawdzić ustawienia adresu e-mail administratora lub ustawienia serwera**

Wersja YetiForce 2.3.49
Serwer w nazwa.pl

Na tej samej konfiguracji serwera i poczty vTiger śmiga.

Na konto pocztowe zalogowałem się bez problemu przez panel webowy, inne konta pocztowe też nie działają na Yeti.

Poniżej log:
Tue Nov 17 13:44:48 2015,534 [58] DEBUG user - Entering Users() method ...
Tue Nov 17 13:44:48 2015,536 [58] DEBUG System - Entering getColumnFields(Users) method ...
Tue Nov 17 13:44:48 2015,536 [58] DEBUG System - in getColumnFields Users
Tue Nov 17 13:44:48 2015,536 [58] INFO DB - Query: SELECT tabid, name, ownedby FROM vtiger_tab
Tue Nov 17 13:44:48 2015,539 [58] INFO DB - Query: SELECT tabid, fieldname, fieldid, fieldlabel, columnname, tablename, uitype, typeofdata, presence
		FROM vtiger_field WHERE tabid in (?)
Tue Nov 17 13:44:48 2015,539 [58] INFO DB - Query parameters: [29]
Tue Nov 17 13:44:48 2015,544 [58] DEBUG System - Exiting getColumnFields method ...
Tue Nov 17 13:44:48 2015,544 [58] DEBUG user - Exiting Users() method ...
Tue Nov 17 13:44:48 2015,550 [58] INFO DB - Query: SELECT * FROM vtiger_tab
Tue Nov 17 13:44:48 2015,554 [58] INFO DB - Query: SELECT fieldname,modulename,tablename,entityidfield,entityidcolumn,searchcolumn from vtiger_entityname
Tue Nov 17 13:44:48 2015,567 [58] INFO DB - Query: SELECT * FROM vtiger_systems WHERE server_type=?
Tue Nov 17 13:44:48 2015,568 [58] INFO DB - Query parameters: [email]
Tue Nov 17 13:44:48 2015,572 [58] DEBUG System - Entering getColumnFields(OSSMailTemplates) method ...
Tue Nov 17 13:44:48 2015,572 [58] DEBUG System - in getColumnFields OSSMailTemplates
Tue Nov 17 13:44:48 2015,572 [58] INFO DB - Query: SELECT tabid, fieldname, fieldid, fieldlabel, columnname, tablename, uitype, typeofdata, presence
		FROM vtiger_field WHERE tabid in (?)
Tue Nov 17 13:44:48 2015,572 [58] INFO DB - Query parameters: [49]
Tue Nov 17 13:44:48 2015,574 [58] DEBUG System - Exiting getColumnFields method ...
Tue Nov 17 13:44:48 2015,585 [58] INFO DB - Query: SELECT * FROM vtiger_ossmailtemplates WHERE ossmailtemplatesid = ?
Tue Nov 17 13:44:48 2015,585 [58] INFO DB - Query parameters: [95]
Tue Nov 17 13:44:48 2015,587 [58] INFO DB - Query: SELECT notesid FROM vtiger_senotesrel INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid=vtiger_senotesrel.notesid WHERE vtiger_crmentity.deleted = 0 AND vtiger_senotesrel.crmid = ?
Tue Nov 17 13:44:48 2015,587 [58] INFO DB - Query parameters: [95]
Tue Nov 17 13:44:48 2015,590 [58] DEBUG user - Entering Users() method ...
Tue Nov 17 13:44:48 2015,590 [58] DEBUG System - Entering getColumnFields(Users) method ...
Tue Nov 17 13:44:48 2015,590 [58] DEBUG System - in getColumnFields Users
Tue Nov 17 13:44:48 2015,590 [58] DEBUG System - Exiting getColumnFields method ...
Tue Nov 17 13:44:48 2015,590 [58] DEBUG user - Exiting Users() method ...
Tue Nov 17 13:44:48 2015,590 [58] DEBUG System - Entering into retrieve_entity_info(1, Users) method.
Tue Nov 17 13:44:48 2015,590 [58] INFO DB - Query: select * from vtiger_users where id=?
Tue Nov 17 13:44:48 2015,590 [58] INFO DB - Query parameters: [1]
Tue Nov 17 13:44:48 2015,593 [58] INFO DB - Query: select * from vtiger_attachments where attachmentsid=?
Tue Nov 17 13:44:48 2015,593 [58] INFO DB - Query parameters: [1]
Tue Nov 17 13:44:48 2015,595 [58] INFO DB - Query: select * from vtiger_user2role where userid=?
Tue Nov 17 13:44:48 2015,595 [58] INFO DB - Query parameters: [1]
Tue Nov 17 13:44:48 2015,596 [58] INFO DB - Query: select * from vtiger_asteriskextensions where userid=?
Tue Nov 17 13:44:48 2015,596 [58] INFO DB - Query parameters: [1]
Tue Nov 17 13:44:48 2015,598 [58] INFO DB - Query: select * from vtiger_field where tabid=? and vtiger_field.presence in (0,2)
Tue Nov 17 13:44:48 2015,598 [58] INFO DB - Query parameters: [29]
Tue Nov 17 13:44:48 2015,602 [58] INFO DB - Query: select * from vtiger_currency_info where id=? and currency_status='Active' and deleted=0
Tue Nov 17 13:44:48 2015,602 [58] INFO DB - Query parameters: [1]
Tue Nov 17 13:44:48 2015,605 [58] DEBUG System - Exit from retrieve_entity_info(1, Users) method.
Tue Nov 17 13:44:48 2015,605 [58] INFO DB - Query: SELECT * FROM vtiger_field WHERE fieldid = 478
Tue Nov 17 13:44:48 2015,607 [58] INFO DB - Query: SELECT name FROM vtiger_tab WHERE tabid = 29
Tue Nov 17 13:44:48 2015,809 [58] DEBUG user - Entering Users() method ...
Tue Nov 17 13:44:48 2015,810 [58] DEBUG System - Entering getColumnFields(Users) method ...
Tue Nov 17 13:44:48 2015,810 [58] DEBUG System - in getColumnFields Users
Tue Nov 17 13:44:48 2015,810 [58] DEBUG System - Exiting getColumnFields method ...
Tue Nov 17 13:44:48 2015,810 [58] DEBUG user - Exiting Users() method ...
Tue Nov 17 13:44:48 2015,810 [58] INFO DB - Query: SELECT first_name FROM vtiger_users WHERE id = 1
Tue Nov 17 13:44:48 2015,811 [58] INFO DB - Query: SELECT * FROM vtiger_field WHERE fieldid = 479
Tue Nov 17 13:44:48 2015,813 [58] INFO DB - Query: SELECT name FROM vtiger_tab WHERE tabid = 29
Tue Nov 17 13:44:48 2015,814 [58] DEBUG user - Entering Users() method ...
Tue Nov 17 13:44:48 2015,814 [58] DEBUG System - Entering getColumnFields(Users) method ...
Tue Nov 17 13:44:48 2015,814 [58] DEBUG System - in getColumnFields Users
Tue Nov 17 13:44:48 2015,815 [58] DEBUG System - Exiting getColumnFields method ...
Tue Nov 17 13:44:48 2015,815 [58] DEBUG user - Exiting Users() method ...
Tue Nov 17 13:44:48 2015,815 [58] INFO DB - Query: SELECT last_name FROM vtiger_users WHERE id = 1
Tue Nov 17 13:44:48 2015,816 [58] INFO DB - To id => 'crm@xxx.nazwa.pl'
Subject ==>'Test mail about the mail server configuration.'
Contents ==> '<span style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;">Dear </span>Karol Niewiński<span style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;">, </span><br style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;" /><br style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;" /><b style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;">This is a test mail sent to confirm if a mail is actually being sent through the smtp server that you have configured. </b><br style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;" /><span style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;">Feel free to delete this mail. </span><br style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;" /><br style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;" /><span style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;">Thanks and Regards,</span><br style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;" /><span style="color:rgb(0,0,0);font-family:arial, sans-serif;line-height:normal;">Team YetiForce</span>'
Tue Nov 17 13:44:48 2015,816 [58] INFO DB - Query: select from_email_field from vtiger_systems where server_type=?
Tue Nov 17 13:44:48 2015,816 [58] INFO DB - Query parameters: [email]
Tue Nov 17 13:44:48 2015,818 [58] INFO DB - Inside the function setMailerProperties
Tue Nov 17 13:44:48 2015,818 [58] INFO DB - Query: select * from vtiger_organizationdetails
Tue Nov 17 13:44:48 2015,820 [58] INFO DB - Inside the function setMailServerProperties
Tue Nov 17 13:44:48 2015,820 [58] INFO DB - Query: select * from vtiger_systems where server_type=?
Tue Nov 17 13:44:48 2015,820 [58] INFO DB - Query parameters: [email]
Tue Nov 17 13:44:48 2015,821 [58] INFO DB - Mail server name,username & password => 'xxx.nazwa.pl','crm@xxx.nazwa.pl','hasło'
Tue Nov 17 13:44:48 2015,821 [58] INFO DB - Query: select first_name,last_name from vtiger_users where user_name=?
Tue Nov 17 13:44:48 2015,822 [58] INFO DB - Query parameters: [your-support name]
Tue Nov 17 13:44:48 2015,823 [58] INFO DB - Inside the functin setCCAddress
Tue Nov 17 13:44:48 2015,823 [58] INFO DB - Inside the functin setCCAddress
Tue Nov 17 13:44:48 2015,823 [58] INFO System - Inside of Send Mail function.
Tue Nov 17 13:44:48 2015,892 [58] ERROR System - Error in Mail Sending: 'SMTP Error: The following recipients failed: crm@xxx.nazwa.pl<p>SMTP server error: 5.7.1 <karol.xxx@gmail.com>: Sender address rejected: not owned by user crm@xxx.nazwa.pl
</p>
'
Tue Nov 17 13:44:48 2015,892 [58] INFO System - Inside the function getMailError
Tue Nov 17 13:44:48 2015,892 [58] INFO System - Error message ==> 
Tue Nov 17 13:44:48 2015,892 [58] INFO System - Mail error is not as connect_host or from_failed or recipients_failed
Tue Nov 17 13:44:48 2015,893 [58] INFO System - return error =>

**Comment by sith5** [comment]
Ok znalazlem problem

**Comment by bpabiszczak** [comment]
Lubię gdy problemy same się rozwiązują ;)
Fajnie jakbyś napisał dla innych co było problemem i jak sobie z nim poradziłeś, może komuś się przyda.

**Comment by sith5** [comment]
Problemem były ustawienia w zakładce Konfiguracja systemu-->Ustawienia pole Helpdesk email, z tego co zauważyłem standardowo pojawia sie tam email administratora. Więc jeśli konfigurujemy serwer SMTP to i w polu Helpdesk email musi być ten sam adres bo inaczej dostaniemy błąd SMTP server error: 5.7.1
