### ISSUE TITLE
Brak wysyłki maili z danymi do customer portal

### ISSUE THREAD

**Issue by sith5** [YetiForceCompany/YetiForceCRM#2290]
Witam,

Mam problem z brakiem wysyłki maili do osób które maja przydzielony dostęp do customer portal.
Zrobiłem wszystko zgodnie z dokumentacja czyli, odpalilem SMTP które działa prawidłowo, odpaliłem równiez zadania w workflow. Stworzylem usera dalem mu dostep do panelu klienta oraz możliwość otrzymywania maili. Niestety nic nie dostaje. Skonfigurowałem ównież crona ale to też nic nie zmieniło.

**Comment by bpabiszczak** [comment]
Proponuje od przeczytania tego: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html
