### ISSUE TITLE
Calculate fields from one module with another module

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2291]
i have two modules that keeps track of cost.  one is for the initial cost of a project the other is for change order cost.  I would like to be able to calculate these total cost.  Is there a way to do this across  multiple modules? or maybe a push into the right direction?

Thanks!

**Comment by bpabiszczak** [comment]
Read this: 
1. https://yetiforce.com/en/developer-documentation/engine/170-types-of-event-handlers.html
2. https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Accounts/handlers/AccountsHandler.php
