### ISSUE TITLE
dane usera w pdf

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#2292]
Jakich zmiennych muszę użyć w szablonie pdf aby w generowanej ofercie pdf podpis był zalogowanego usera?
#Users_first_name# #Users_last_name#
email: #Users_email1#

te zmienne dają dane pierwszego admina

i jak dodać zmienną tel wewnetrzny usera

**Comment by mmstrzelec** [comment]
Coś się zmieniło  - na wersji testowej też jest administrator a dwa tygodnie temu te zmienne dawały zalogowanego usera?

**Comment by mmstrzelec** [comment]
Coś pokombinowałem i znowu jest user a nie admin ale nie wiem jak to sie dzieje?

zmienna z tel usera chciałbym dodać tylko nie wiem co wpisac pomiedzy # #

**Comment by bpabiszczak** [comment]
Zmienne i etykiety które są obsługiwane przez system są dostępne w panelu tworzenia szablonu PDF, nic innego prócz funkcji specjalnych do systemu nie załadujemy.

Wersja gitdeveloper ma dwóch użytkowników, demo i admina.
Jeden ticket jedno pytania...
