### ISSUE TITLE
[BUG] Menu - can't enter a subcategory

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#2294]
![menu1](https://cloud.githubusercontent.com/assets/10221999/11237309/4cb6a2c4-8ddf-11e5-9325-8b5cfbd5f715.gif)

**Comment by TomaszQr** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/a66b4c2dc5ca48f466e5858513452660135d1526
It working only for chrome bowser
