### ISSUE TITLE
YetiForce.com is down

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2295]
I suppose there is some reason for this, but just in case you didn't notice.
"Error displaying the error page: Application Instantiation Error: Could not connect to MySQL."

**Comment by florek41** [comment]
same with demos

**Comment by bpabiszczak** [comment]
disk controller fails, tomorrow it will all work.

**Comment by eptapsyxos** [comment]
good to hear that!

**Comment by bpabiszczak** [comment]
Now work, thx.
