### ISSUE TITLE
page loading time 150sec!

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2297]
I have a problem with yetiforce on my server
all was good until i get i huge time to load every page
150 sec for every new page or refresh.
(plus the javascript loading widgets have the same issue)and some buttons they dont have translation too.
Can you give me a little help how to solve that please?
![proble](https://cloud.githubusercontent.com/assets/6897502/11247037/02c6c7c2-8e23-11e5-942c-3392db2f2f14.jpg)

Thank yoy very much !

**Comment by bpabiszczak** [comment]
Change the server, preferably with support. On our servers, the system comes very quickly.
