### ISSUE TITLE
[Question] - calculation and quote

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2299]
I have question which rise during speaking about YF...
For example, my product 1 contains subproducts A, B, C. 
And my question is: Is it possible to use calculation to specify subproducts and transfer them to quote and have them under Product 1 which is taken from stock but price of the Product 1 (total) should be calculated base on calculation...? So on the quote there will be only Product 1 and price will be sum of subproducts...
thanks

**Comment by florek41** [comment]
this is exactly what I need. I mentioned this during a conversation about the new product modules.
Materials module will be useful too (in addition to products and services).

**Comment by witer30** [comment]
can you provid link to this dicussion?

**Comment by florek41** [comment]
sure: #1656

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
