### ISSUE TITLE
yetiforce.com website: little change needed

### ISSUE THREAD

**Issue by maikst** [YetiForceCompany/YetiForceCRM#230]
yetiforce.com shows a picture and text and 3 buttons at the buttom...

The 3 boxes are not completly readable on a notebook with 1368x768
Take a look at the picture in the attachment.
![bildschirmfoto vom 2015-02-13 19 25 51](https://cloud.githubusercontent.com/assets/9348629/6192879/94fa9b52-b3b6-11e4-897f-55c631ccee2e.png)

**Comment by KatarzynaUlichnowska** [comment]
Hello Maik,
thanks for your comment. It's great that you visited our website. However, this content is only temporary and we are working on a new one. It should be published be the end of February (fingers crossed).
