### ISSUE TITLE
Removing language packs

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#2300]
We're planning to remove all language packs that are not being sufficiently developed with the system. They will still be available as separate repositories and you will be able to download and install them. We think it's better better to have 2/3 well translated languages, instead of translating part of languages using Google Translator like Vtiger does.

Default languages would be:

1. English
2. Polish

All the other languages will be moved to github as separate packs. 
Any ideas, suggestions for improvements, comments?

**Comment by agilisgmbh** [comment]
IMHO you should not remove german language. German language was a horror in vTiger itself, not supported and not funny to use.
German is a very big market so i think you should NOT remove it. Also if you need help with german translations for the future, we´re willing to help with that...
Do not remove it from core...

**Comment by bpabiszczak** [comment]
![language_stats](https://cloud.githubusercontent.com/assets/10197525/11575471/82df9570-9a11-11e5-9806-73462cdc9b48.png)

**Comment by waw555** [comment]
Russian language does not remove, I do it, soon upgraded to the latest version

**Comment by bpabiszczak** [comment]
Thank you for such a vivid discussion on an important matter like this ;) At first we'll remove one language, the one that gets the fewest updates. I'd like to ask you to work a little harder on all the remaining languages [it's a good idea to look for people who will take care of the translations together]. We want the system to support as many languages as possible, but we can't really force anything.

**Comment by waw555** [comment]
In a lot easier to work when the language is, as the saying goes, "Out of the box", or when it can be installed via the built installer language, such as it is arranged into Joomla, for when you want to search for packages or modules spoken languages, is a bit off-putting from the product.

**Comment by bpabiszczak** [comment]
Next week we will remove the language "Dutch" from the system.
