### ISSUE TITLE
unique entry fileds

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2301]
Any way to make a field a unique entry filed.  so when creating a record it will not allow duplicate names?

**Comment by florek41** [comment]
You can use Validation of access tool:
https://gitdeveloper.yetiforce.com/index.php?module=DataAccess&parent=Settings&view=Index&block=15&fieldid=52

create new condition - in 3 step you can add action **Field value is unique.** which is this what you need.

**Comment by jbmcclain** [comment]
that is awesome!  by the way which repository the version that is being used when logging into the demo with the responsive template.. can i download that anywhere?

**Comment by bpabiszczak** [comment]
U need wait for 2.4 version [1-2 weeks].
