### ISSUE TITLE
Right column calendar responsive

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2302]
Just took a snapshot from iPad mini and it's like this.
![image](https://cloud.githubusercontent.com/assets/6897502/11271783/18c2329c-8ed1-11e5-8c7b-c30db2d115be.png)
Does not expand properly

**Comment by TomaszQr** [comment]
Fixed f39843bb06024eeae37388fc1ea1bb2fdf5047a1
