### ISSUE TITLE
Sale Processes vs Opportunities

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2303]
These two look the same to me. Sale Processes is to new modules what Opportunities used to be to old modules. But right now (2.3.460) we have both: Opportunities with old modules ans Sale Processes with new modules. Is this only temporary, or is there any business logic behind this?

**Comment by florek41** [comment]
I think we should wait until new process will be finished.

**Comment by bpabiszczak** [comment]
The new version of the system won't the old process based on the opportunity module and old modules related to it. New modules will be created for the sales process and they won't interfere with the old ones. When migrating from version 2.3 to 2.4 the old modules remain [ they will only be disabled] with the option to uninstall them, the administrator will decide whether he wants to leave everything as it was, or if he wants to implement a new process. Future changes will only concern the new process. The new sales process introduced in version 2.4 will be in beta for 2 months, and will be expanded with new functionalities. We think it's a good idea not to interfere with key modules.

**Comment by echemik** [comment]
Is there any description of new process?

**Comment by bpabiszczak** [comment]
No. Instruction will be published together with version 2.5.

**Comment by witer30** [comment]
If i can ask, will you connect all module with product module - I mean that price, margin, purchase price entered in the product record will be transfer to all related modules?

**Comment by bpabiszczak** [comment]
Yes...

**Comment by nikdejan** [comment]
So, if I understood you correctly, Sale Processes together with new modules are going to replace Opportunities and old modules? Opportunities and old modules will be obsolete, but will be sill kept for a while, maybe because of backward compatibility? But we are expected to use opportunites OR sale processes, not both, right?

**Comment by bpabiszczak** [comment]
Yes and yes and NO [u can use both, but it does not make sense].

**Comment by nikdejan** [comment]
I understand the future. 
What would you recommend at this moment? Which way to go? Are new modules usable? Do old modules still have some advantages?
For example, I can see that Sales Processes still do not have Summary view? This is something I can see, but I guess there are many other things that one can see only when he starts working on details. So how good are sales processes and new modules at this very moment?

**Comment by nikdejan** [comment]
And what about other modules in the system? Looks like that everything is still connected to old modules, and not with new. For example, email_actions include Relate to Opportunity, but not Relate to Sales Process. You are creating totally new crm inside the old one, and it looks to me it is going to take a really, really long time before it becomes usable.

**Comment by nikdejan** [comment]
OK. Sales Processes actually have Summary view, but no widgets were added. So on this one I was wrong. But what about other functionalities visible and not visible?
