### ISSUE TITLE
Setting->Recording Control Bug

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2306]
Tried to add new condition

On step two 
you press the button to choose CONDITIONS 
and nothing happens.
https://gitdeveloper.yetiforce.com/index.php?module=DataAccess&parent=Settings&view=Index&block=15&fieldid=52

check out here.try to add new condition.
fill the first step fields.
and on the second step press ANY CONDITION.

**Comment by nikdejan** [comment]
I can confirm this bug. Version 2.3.463. Validation of access: Step 1 (Condition Details) is OK. Step 2 (Add Condition) you can't add any condition, because when you click Add Condition button, nothing happens.
