### ISSUE TITLE
Customer Portal - white screen for Accounts

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2308]
Hi,

I have installed and testing the Customer Portal v.2.2.

When I click on Accounts I get a white screen - all other modules seem to be working/opening fine. I have re-named my Accounts in the CRM to Organisations, so I am not sure if this would effect it?
Also on latest version of yetiforce.

Regards

Percy

**Comment by mariuszkrzaczkowski** [comment]
I checked the latest version of the portal and CRM version developer and everything is working properly.
I added a small correction for soup, test the latest development version.

**Comment by PercyP** [comment]
Thanks Mariusz,

where are the latest developer versions stored? I am checking here: http://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%202.x.x/Update%20packages/

But these don't seem to have changed

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by witer30** [comment]
how to use this full installation package to update my version to avoid loosing any data...?

**Comment by PercyP** [comment]
Hi witer30,

I too am unsure what to do with the developer zip file. Did you work it out?

**Comment by witer30** [comment]
sorry not...
Well this is full installation package. That's why i am afraid that when will use it all my data will be overwritten...

**Comment by bpabiszczak** [comment]
Update package: https://github.com/YetiForceCompany/UpdatePackages/tree/developer
