### ISSUE TITLE
[Question / Improvement] Email and PDF Templates - Calculated field

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2309]
I want to add a Calculated field to the Email / PDF templates.  For example #Invoice_duedate# + 30

or "If you pay within 5 days you will receive an additional 5% discount.  Your payment will be"  #Invoice_total# * .95

Is this currently possible?

**Comment by nikdejan** [comment]
AFIK it is not possible. You can not put any code expressions in the template, only different variable place holders. In order to achieve what you want you should use "Custom functionalities". 
Here is how authorities explained that: https://github.com/YetiForceCompany/YetiForceCRM/issues/2260

**Comment by bpabiszczak** [comment]
Thank you @nikdejan

**Comment by mykljohn** [comment]
Thank you @nikdejan that's just what I was looking for.  cheers
