### ISSUE TITLE
All Pop Up Windows Mesh Up 5,5 inch

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2310]
![s51121-145910](https://cloud.githubusercontent.com/assets/6897502/11318576/c2f7e9e2-9060-11e5-9058-9a80719f19f3.jpg)
On my phone 5,5 inch  Resolution, 1080 x 1920 pixels screen the responsive layout run like a charm
but all pop up windows as quick create events to do etc
are meshed up and squeezed.

you can checked it out

**Comment by eptapsyxos** [comment]
![s51122-233715](https://cloud.githubusercontent.com/assets/6897502/11326427/2bdd2b4a-9172-11e5-8fe3-48deb4bf3174.jpg)please add the ability to scroll the list left and right so we can see further details.

**Comment by eptapsyxos** [comment]
email also meshed up.
Chat is not functional because is oversized.
Gant chart on projects also can not handle because of lack of scrolling left and right.

**Comment by eptapsyxos** [comment]
![s51123-000005](https://cloud.githubusercontent.com/assets/6897502/11326554/3e91c8d8-9175-11e5-98f9-846da399456f.jpg)
Item details at all invoicing process modules are out of screen.

**Comment by TomaszQr** [comment]
0a002734d6b7f87e8dd7d21bfcfa64ad3f0f9602
240391ca7968bd0671886a8673df833da7ad6c94
90f0ab4494cc705fc24cef3579012fc7b69fcb54
bd567bc67e4195d0e5b6a488020c148bee75a4cb
985735ca90f8e589fd5b0d356727295f79c8d898
3bddd310804d32b72a8f8874994fda787e12ac9e
