### ISSUE TITLE
[Logic][Question] Field "Updated"

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2313]
Field "Updated" is described as "a system field that is filled in automatically and indicates that a record owner read all changes performed on this specific record." I think I understand the idea behind this field and I like it very much. (vTiger doesn't have it, I think).
I did some testing on gitdeveloper and value of field "Updated" remained "No" all the time, although I created new users and updated Opportunities, Tickets, added comments etc. with different user accounts. So how exactly is this field working? In which cases it's value becomes "Yes"?

**Comment by nikdejan** [comment]
I don't see field "Updated" in new modules? How do we know when some of new module records has been updated?

**Comment by bpabiszczak** [comment]
1. This field will be improved and modified.

2. The field works when someone else changes a record that belongs to you [when you update your own record then nothing happens, because the system won't inform you about your changes].

**Comment by nikdejan** [comment]
1. OK
2. I said that I did some testing "with different user accounts". So I understand how it is supposed to work, but it doesn't work that way. Simply, it's always "No", no matter who updates the record.

Powiedziałem, że zrobiłem kilka testów "z różnych kont użytkowników". Więc rozumiem, jak to ma działać, ale to nie działa w ten sposób. Po prostu, to zawsze "nie", bez względu na to, który aktualizuje rekord.

**Comment by bpabiszczak** [comment]
Mechanizm ten powinien być wyłączony w systemie, nie był skończony. W nowej wersji go nie widzę, więc pewnie testujesz na jakieś wersji, która ma to jeszcze włączone. 

PS: jak możesz twórz zgłoszenia w PL i dodawaj w temacie [PL] na początku. Skróci to czas reakcji na zgłoszenie, a teraz niepotrzebnie go wydłużamy...
