### ISSUE TITLE
[Improvement] Import of Reports

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2314]
I'm developing some custom Reports in our test system.  It would be a nice feature o be able to export them and import them into our Production site.  

Also what about generating reports from SQL Queries?

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
