### ISSUE TITLE
[Feature Request] Add some test data to gitdeveloper

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2315]
In order to test Sales Order I need to create a test record. But then, because field Quote is mandatory, I need to create Quote, and for Quote I need Requirement Card, and for Requirement Card I need Quote Enquiry and for all off them I need Sales Process, and for Sales Process I need Account. So I spend lot of time just to be able to do some simple test, and while I do all that yetiforce version goes from 2.3.678 to 2.3.679 and everything gets wiped off. And then we have to do it again.
Having some test data would save developers a lot of time.

**Comment by eptapsyxos** [comment]
Sounds logical.

**Comment by SkavenKF** [comment]
+1

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
