### ISSUE TITLE
Question - how to switch on Google map in Contacts?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2316]
Hi,

I read somewhere that a google map api is integrated in the contacts module, however I don't see it. Is this a separate download/install?

Kind regards

**Comment by bpabiszczak** [comment]
1. Currently we don't have Google Maps and contacts module integration.

2. There is a built-in mechanism for calendar notifications, when a location is entered a notification with the link to Google Maps location appears.

3. If something remains in the code, it's Vtiger leftovers, and it most likely doesn't work.
