### ISSUE TITLE
[Bug] - layout - user menu

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2318]
![image](https://cloud.githubusercontent.com/assets/11491482/11350884/1670513e-9234-11e5-9d28-12c19ce9681c.png)

**Comment by witer30** [comment]
![image](https://cloud.githubusercontent.com/assets/11491482/11541699/e97d344c-9933-11e5-9b57-1b7b7cc2d7cb.png)

**Comment by florek41** [comment]
Maybe additionally change font-size in menu to for example 14px ? All headings have max 15px but in menu we have 16px - after change to current row height for me line-height is to small, what you think ?
