### ISSUE TITLE
Installation Ends to blank page on ver. 2.3.49

### ISSUE THREAD

**Issue by noclav** [YetiForceCompany/YetiForceCRM#2319]
Server Info 
Distributor ID: Debian
Description: Debian GNU/Linux 7.9 (wheezy)
Release: 7.9

PHP 5.5.30-1~dotdeb+7.1 (cli) (built: Oct 1 2015 17:38:39)

MYSQL info
| innodb_version | 5.6.25 |
| protocol_version | 10 |

Apache/2.2.22 (Debian)

YetiCRM: 2.3.49

I set up permissions to be 777 on entire public_html folder and this is what i get

This is while installing.
![image](https://cloud.githubusercontent.com/assets/15483172/11352368/882d364e-9201-11e5-9948-2f46da5199e9.png)

![image](https://cloud.githubusercontent.com/assets/15483172/11352595/ebd1fd82-9202-11e5-9998-92efc165c7c8.png)

Then it ends with the blank screen and this the last lines of the system log where it ends.
insert  into `yetiforce_proc_sales`(`type`,`param`,`value`) values ('popup','limit_product_service','false')
Mon Nov 23 22:34:20 2015,615 [2970] INFO DB - Query: insert  into `yetiforce_proc_sales`(`type`,`param`,`value`) values ('popup','update_shared_permissions','false')
Mon Nov 23 22:34:20 2015,790 [2970] INFO DB - Query: insert  into `yetiforce_proc_sales`(`type`,`param`,`value`) values ('calculation','calculationsstatus','')
Mon Nov 23 22:34:20 2015,873 [2970] INFO DB - Query: insert  into `yetiforce_proc_sales`(`type`,`param`,`value`) values ('potential','salesstage','')
Mon Nov 23 22:34:20 2015,957 [2970] INFO DB - Query: insert  into `yetiforce_proc_sales`(`type`,`param`,`value`) values ('asset','assetstatus','')
Mon Nov 23 22:34:21 2015,040 [2970] INFO DB - Query: insert  into `yetiforce_proc_sales`(`type`,`param`,`value`) values ('potential','add_potential','false')
Mon Nov 23 22:34:21 2015,140 [2970] INFO DB - Query: /*Data for the table `yetiforce_proc_tc` */

insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('general','oneDay','false')
Mon Nov 23 22:34:21 2015,232 [2970] INFO DB - Query: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('general','timeOverlap','false')
Mon Nov 23 22:34:21 2015,315 [2970] INFO DB - Query: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('timeControlWidget','holidays','true')
Mon Nov 23 22:34:21 2015,565 [2970] INFO DB - Query: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('timeControlWidget','workingDays','true')
Mon Nov 23 22:34:21 2015,648 [2970] INFO DB - Query: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('timeControlWidget','workingTime','true')
Mon Nov 23 22:34:21 2015,731 [2970] INFO DB - Query: /*Data for the table `yetiforce_updates` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */
Mon Nov 23 22:34:21 2015,732 [2970] INFO DB - Query: /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */
Mon Nov 23 22:34:21 2015,733 [2970] INFO DB - Query: /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */
Mon Nov 23 22:34:21 2015,734 [2970] INFO DB - Query: /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
Mon Nov 23 22:34:21 2015,735 [2970] INFO DB - Query: SET FOREIGN_KEY_CHECKS = 1;

i have reinstalled many times same issue. I tried the developement version same issue. 

Any suggestions. I enabling the logging as suggested in the documentation and i didnt see the cache/logs/phpError.log file. I did check the /var/log/php/error.log and nothing showed up. 

any suggestions?

**Comment by mykljohn** [comment]
After install, check that your php configuration is still using a custom php.ini...I couldn't get it installed because my labels disappeared, but I did notice that on HostGator, after the update, The PHP config was cleared and needed to be reset to 5.5 and the custome php.ini.

**Comment by noclav** [comment]
The issue is during the install. Yetforce is built on Vtiger and i installed vtiger fine. Im wondering if YF doenst like the version of PHP im using. I hate to install a new version and find other issues. I have several other CRMs installed that im testing and dont want to mess them up with a new php version.

**Comment by mariuszkrzaczkowski** [comment]
Try to install the developer version https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by noclav** [comment]
same issue on developer version, But i tried with my webhost and the install went very fast and finished like it should it. My debian is on a Hyper V Host not sure if that has anything to do with it.

**Comment by mariuszkrzaczkowski** [comment]
Tested on version 2.3.526 and correctly installed.
Check the latest version for developer and check the error logs

**Comment by Bergdahls** [comment]
Did you set permissions to 777? Try to set folders to 755 and all files to 644 at start. After that you might have to change some folders and files permissions.

**Comment by bpabiszczak** [comment]
1. The server should be configured in such a way that you wouldn't have to tweak permissions to files/directories as @Bergdahls suggested. If you have permissions to 777 it's not good, both in terms of security and the LAMP server configuration.

2. Always test the system using the latest software, that is PHP 5.6, some people reported problems with PHP 5.4 and 5.5, we use 5.6 on our servers, so this version of PHP is well tested.

3. As far as the help is concerned – we can't do much. To solve these problems you need to hire a good linux administrator and a good YetiForce developer, and we don't provide such support for free. The logs you presented don't bring anything to the problem.
