### ISSUE TITLE
bug in Layout editor

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#232]
When adding a default value to a custom field, it doesn't stay visible in module edit view.

**Comment by bpabiszczak** [comment]
I checked it on 3 different types of fields and it works properly. Please send us a step by step description how we can test for this error at test.yetiforce.com.

**Comment by kpaulaha** [comment]
Just tested it on test.yetiforce. Made in contacts plain text field "test". Its ok, visible and editable. When I add default value, it is visible in details view, but not in edit view.
