### ISSUE TITLE
[BUG] Install Dev ver 2.3.492

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2320]
![error install dev](https://cloud.githubusercontent.com/assets/1402355/11359908/1ec8fe6c-92a2-11e5-9a3c-1c0a6e667ee6.jpg)

**Comment by nikdejan** [comment]
I'm not sure if I should have open another issue. In 2.3.519 installation goes seemingly normal but when it it is finished on login page there are only user and pass fields, while language and layout fields are missing. 
When I log in, every list view gives 502 Bad Gateway error. So, wherever there is view=List in the url, I get that error. Error in php log connected with 502 Bad Gateway is:  [error] 9534#0: *655028 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 12.12.12.12 (my website IP), server: my.website.com, request: "GET /yeti/index.php?module=SSalesProcesses&view=List&mid=119&parent=118 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "my.website.com", referrer: "http://my.website.com/yeti/index.php"
There are some errors in php log which are logged during installation. They look like this:
2015/11/26 22:03:24 [error] 9533#0: *654748 open() "/var/www/mywebsite.com/yeti/layouts/vlayout/resources/ProgressIndicator.js" failed (2: No such file or directory), client: 12.12.12.12, server: mywebsite.com, request: "GET /yeti/layouts/vlayout/resources/ProgressIndicator.js HTTP/1.1", host: "mywebsite.com", referrer: "http://mywebsite.com/yeti/install/Install.php"
There are several of this errors and obvious reason for this is that layout/vlayout/resources directory is missing.
My PHP is 5.4, and everything used to work fine on yetiforce 2.3.88.

**Comment by mariuszkrzaczkowski** [comment]
Tested on version 2.3.526 and correctly installed.
Check the latest version for developer.

**Comment by waw555** [comment]
ver. 2.3.595 normal install
