### ISSUE TITLE
[bug] [DEV2.3.501] Unable to load template file 'modules/Vtiger/RelatedListButtons.tpl'

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#2323]
When i choose a single object (ex. a contact).
![bug1](https://cloud.githubusercontent.com/assets/10259801/11392730/d35da53a-935b-11e5-9d27-3ce2241be07f.JPG)
![bug2](https://cloud.githubusercontent.com/assets/10259801/11392731/d47b314e-935b-11e5-9f25-a501f9fc9f05.JPG)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/0e5d865fbfd71c775ed28e0a8af1f809362ed539
