### ISSUE TITLE
List view No responsive

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2326]
One every module on list view resonsive theme is  note working. Tested on 5.5 Inch  Mobile Phone. 
![s51125-174230](https://cloud.githubusercontent.com/assets/6897502/11401673/674889d2-939c-11e5-8d1f-75b706b2a141.jpg)
![s51125-174234](https://cloud.githubusercontent.com/assets/6897502/11401681/6d4041c2-939c-11e5-9504-5292fad9b01d.jpg)
![s51125-174253](https://cloud.githubusercontent.com/assets/6897502/11401687/72fa2434-939c-11e5-83a2-c98df8bcb1e0.jpg)

**Comment by mariuszkrzaczkowski** [comment]
We know about this issue. At the moment we are rebuilding the new appearance. The work is still in progress so we would like to ask you for some more patience.
