### ISSUE TITLE
[BUG]  [REQUEST] Utwórz nowe pole :wprowadzono niedozwolony znak

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#2327]
Przy próbie dodania nowego pola dla modułu kontrahenci pojawia się błąd "wprowadzono niedozwolony znak"
Testowane na wersji demo https://test.yetiforce.com 2.3.49
![utworz nowe pole](https://cloud.githubusercontent.com/assets/10506580/11408951/e77d37f4-93bc-11e5-9c38-e8d7edca86f3.PNG)

**Comment by bpabiszczak** [comment]
Nie możesz wprowadzać nazwy systemowej ze spacjami bo on na tej podstawie tworzy kolumny!
A etykiety powinny być tworzone zgodnie z już istniejącą logiką np. LBL_PROJECT_STATUS a następnie w panelu z językami należy nadać odpowiednią nazwę.
