### ISSUE TITLE
[Improvement] Responsive Layout - 3 columns

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2328]
In new, responsive layout, with related tabs moved to the top and with thin left sidebar menu, we have a lot more space in the middle, which is a good thing. Because of all this space available, I think it would be nice if we could have widgets in three columns in Summary View, as an option.

**Comment by mariuszkrzaczkowski** [comment]
This possibility already is just move the widget to the third column
Software configuration > Standard Modules > Modules – Widgets

https://gitdeveloper.yetiforce.com/index.php?module=Widgets&parent=Settings&view=Index&block=2&fieldid=58

**Comment by nikdejan** [comment]
Wow, how did I miss that! Anyway, I'm glad it's there. :-) Thank you
