### ISSUE TITLE
recurring invoices

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#2331]
everytime I upgrade to new yeti version, the recurring invoice process stops working.
I assume it has to do with some custom fields.

But can anyone tell how to debug to the recurring invoicing process? To see why no invoices are created?
Also it would be great with a feature that showed in table view planned ned invoices... 
eg
3 days from now invoice xxxx, to organization, amount... will be created.

**Comment by lalord** [comment]
I can see that recurring invoicing from sales orders has been removed in Yeti 3.0.0,
do you plan to reimplement in future version inside sales orders or?

**Comment by paula-w** [comment]
Hi.
This is what the 'Recurring Sales Orders' module is for (Sales → Recurring Sales Orders).
It has not been completely finished yet, it will be fully functional in v3.1 (end of May).
The system will be able to automatically generate single orders from recurring orders, and then automatically generate invoices.

**Comment by jgonzalezgonzalez** [comment]
Hi there!

I´m currently working with v 3.1.0 and I´m not able to settle recurring invoicing. Where can I get more info about it? I´ve tried many things from Recurring Sales Orders but nothing seems to work.

Regards.

**Comment by mariuszkrzaczkowski** [comment]
Error still exists? Check out the latest versions
