### ISSUE TITLE
[bug] Quotes enguires

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2333]
Bug in Quotes Enquires v.2.3.519

![quotes_enquires](https://cloud.githubusercontent.com/assets/10330264/11428839/d7ff22e4-9478-11e5-9387-e8cb0c11c951.png)

**Comment by nikdejan** [comment]
Everything looks OK to me. Can you describe in more detail how you produced that bug?

**Comment by kpaulaha** [comment]
Got the error when saving a new quotes enquiry with minimun entries.

**Comment by kpaulaha** [comment]
If you click the made enquires on gitdeveloper.yetiforce.com you see the error

**Comment by nikdejan** [comment]
I can not replicate it.

**Comment by kpaulaha** [comment]
![qi](https://cloud.githubusercontent.com/assets/10330264/11430439/6302a3a0-948f-11e5-846c-352d522d7395.gif)

**Comment by nikdejan** [comment]
Oh, I see now. I couldn't replicate it because I was trying from Responsive layout, and everything was fine there. Now I can confirm that this bug exists but only in vlayout.
