### ISSUE TITLE
[Improvement] Money Layout

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2334]
The layout for money should always be the same whether it's 0 or > 0.

      0           $0.00    not just 0   ($ or whatever symbol)
      1           $1.00    not just 1
1000    $1,000.00    not just 1000

This is with regard to Quotes, Sales Orders, Invoices, PurchaseOrders, PaymentsIn & Out, PriceBooks, Products.  Where ever else.

**Comment by witer30** [comment]
If I am ok it was reported and fixed... please check on gitdeveloper demo if issue exist of not then updet your version.

**Comment by mariuszkrzaczkowski** [comment]
Please specific examples where is wrong value, a screenshot .

**Comment by mykljohn** [comment]
![salesorder](https://cloud.githubusercontent.com/assets/11919990/11447844/f70efebc-9512-11e5-9741-acea3f5d9f28.png)


I don't know if this has been fixed.  It looks ok in GitDev, but I don't have time right now to create records and switch currency, etcetera in GitDev and test it.

I can't update to the latest version until the issue with our disappearing labels is resolved #2311

**Comment by bpabiszczak** [comment]
We support only new modules with products.
