### ISSUE TITLE
[Improvement / Question] Display only "Active" Related

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2335]
When you click from Contacts to add a Project, It display all Projects.  Is there any way to display just ACTIVE Projects?  I'm guessing Custom Views or something, but no sure where or how to do it.

**Comment by mariuszkrzaczkowski** [comment]
Try to create functions getQueryByModuleField in Project 
ex. https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Products/models/Module.php#L22
