### ISSUE TITLE
[Bug] Warning: Invalid argument supplied for foreach() in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Accounts/models/DetailView.php on line 55

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2338]
When I go to Account Details (https://gitdeveloper.yetiforce.com/index.php?module=Accounts&view=Detail&record=110) I get the following warning:
Warning: Invalid argument supplied for foreach() in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Accounts/models/DetailView.php on line 55

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/7233d61d40dbbf7dfff817f5247a51251c117dbc
