### ISSUE TITLE
[BUG] Edit picklist for new modules PHP error

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2339]
while editing picklists for new modules if there is no picklist
![picklist_error](https://cloud.githubusercontent.com/assets/4824588/11448331/0c190224-9556-11e5-803d-441bbb346eb8.JPG)

**Additionaly:** States in new modules will be editable ? I need to extend/change several statuses.

**Comment by florek41** [comment]
Bug is fixed but question still without answer:

States in new modules will be editable ? I need to extend/change several statuses

**Comment by bpabiszczak** [comment]
Pola statusów będą domyślnie nieedytowalne [tak jak to jest w kalendarzu] i będą rozbudowywane i automatyzowane... oczywiście każdy może sobie zmodyfikować taki status, ale polecamy to raczej programistom.
