### ISSUE TITLE
[Question / Need Help] Recurring Invoice

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2342]
I'm having a bit of trouble with the scheduling logic.  

We do monthly billing for Classes sold.  The Student pays an Inscription Fee, and then monthly fees from then on.  So for example, Student Bob enrolls on 10/1.  The Sales Order is entered with the 

Recurring Invoice set to:       Enable Recurring  Yes          Frequency  Monthly  
                                              Start Period  10-1-2015        End Period  10-1-2016  
                                              Payment Duration  After 3 weeks  Invoice Status  Auto Created

The initial Invoice is created for the Inscription manually with the date of 10/1.
The Recurring Invoice Task will create the automatic Invoice with the date of 10/1.

My Workflow to send the Payment Notice is scheduled for Invoice Date + 25 and will be sent on 10/26

Is my logic correct so far?  It doesn't seem right to me.  I thought I could send the Notice 5 days before the Invoice Date, with the first auto-Invoice dated 11/1...

The problem I'm having is I need the Invoice to show that the Invoice is for November not October.

Anyone got anything...I'm getting a vicious headache racing this around.

**Comment by bpabiszczak** [comment]
I don't really know what the question is. Automatic generation from an order [if we're talking about v2.3.49] generates the invoice for the first time when the condition is met, and the next ones according to the schedule.

We removed the old mechanism in the new version, and we're designing a brand new one, that will base on periodically recurring orders and will be related to workflow.

**Comment by mykljohn** [comment]
OK, that sounds like what we need.  I'm waiting.  Good luck with everything and happy new year to all of you.
