### ISSUE TITLE
[Improvement] Workflow update field in Related Entity

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2343]
It woud be an excellent feature to be able to update a field in a related entity from a Workflow without having to write a php function to do it.

**Comment by florek41** [comment]
This is something about what I asked in #1965 . It will be time saver and make life easier, but this is not so difficult to add by code.

+1 :)

**Comment by nikdejan** [comment]
+1

**Comment by berwerle** [comment]
can you show me how to implement such a custom function?

**Comment by mykljohn** [comment]
@nikdejan +1....me too :)

**Comment by rskrzypczak** [comment]
There is a function to update fields in a related module, so there's no need to create custom functions. 
![updaterelentity](https://cloud.githubusercontent.com/assets/10221999/15350034/2b232cfe-1cd7-11e6-8ca3-9dae1a438ce2.gif)
Hope this solves your problem.
