### ISSUE TITLE
[BUG] "Values from the related module" doesn't updates to new values

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2345]
I've made some test of **Values from the related module** field and I noticed that the value doesn't change when is changed in the selected (related) record.
I put statuses of the project tasks on the projects list
Initial status for new tasks is good, by after change it's still same:
![related_field2](https://cloud.githubusercontent.com/assets/4824588/11453759/3292c0e4-9618-11e5-9665-e6c9d8ee0c32.JPG)
![related_field1](https://cloud.githubusercontent.com/assets/4824588/11453762/425d6312-9618-11e5-8ab9-51fb54d3de51.JPG)

BUT ! When edit or create new filter value is OK
![related_field3](https://cloud.githubusercontent.com/assets/4824588/11453770/753b3214-9618-11e5-8688-a0f465997938.JPG)

Something with cache ?

Additionally: I think if the fields has same value we don't need two same filters - user can be confused.

**Comment by bpabiszczak** [comment]
Gdy dodajesz zgłoszenie w języku angielskim to wydłuża to znacząco odpowiedź na takie zgłoszenie... i w mojej opinii komplikuje proces. Jak możesz dodawaj zgłoszenia w języku polskim, przy czym w temacie dodawaj na początku [PL]. 

Odnośnie Twojego zgłoszenia, nie bardzo wiem jak Ci odpowiedzieć bo nie rozumiem w całości przedstawianego problemu. Wartości zapisane w danym polu [np. dla pól picklist] nie muszą być zgodne z aktualnie dostępnymi wartościami. Dzieje się tak często przy imporcie, czy też zmianach wartości przy migracji.

Tak to zostało zaprojektowane przez Vtiger, czy słusznie, to szczerze powiedziawszy nie wiem, ma to niski priorytet.

**Comment by florek41** [comment]
W porządku, jeśli tak mówisz to i dla mnie będzie wygodniej - pytanie co na to społeczność ?

Jeśli chodzi o przedstawiony problem to nie chodzi tutaj w żadnym wypadku o Picklist etc. Chodzi o nowe pole **Wartości z powiązanego modułu**

W opisywanym przykładzie do Projektów dodałem to właśnie pole - chciałbym, żeby wyświetlany był status powiązanych zadań projektowych, nazwałem je "LBL STATUS"
Utworzyłem Projekt a w nim 3 zadania - 2 ze statusem "Open", 1 otrzymało status "In Progress".
Początkowo "LBL STATUS" wyświetlało wartość "Open, In Progres" - czyli prawidłowo.
Po zmianie statusów zadań pole nieststy nie uaktualniło się tak, jak miałby ono działać w domyśle - pozostała wartość "Open, In Progres" mimo, że zadań o takim statusie brak.

Jednak przy edycji filtrów widać, że wartości są uaktualnione:
![related_field3](https://cloud.githubusercontent.com/assets/4824588/11453770/753b3214-9618-11e5-8688-a0f465997938.JPG)

Dodatkowa sprawa, która wyszła przy testowaniu tej funkcjonalności to to, co widać na powyższym screenie:
Jeśli 2 rekordy powiązane mają taką samą wartość to przy tworzeniu filtra opierającego się na polu **Wartości z powiązanego modułu** mamy do wyboru 2 identyczne opcje.
Moim zdaniem powinna być tylko jedna, bo wyobraźmy sobie kiedy powiązanych rekordów będzie np. 20...

**Comment by florek41** [comment]
@bpabiszczak - błąd dalej występuje, więc zgłoszenie powinno być ponownie otwarte, bo na początku problem nie do końca został zrozumiany ;)

**Comment by bpabiszczak** [comment]
ale ja tutaj jeszcze nie widzę żadnego problemu... wartości w polu są generowane dynamicznie... jak usuniemy pole i je dodamy, system wygeneruje wartości w cronie jeszcze raz. Nie można tego przeliczać w czasie rzeczywistym, ponieważ u niektórych klientów trwa to kilkanaście minut... a więc musi to być odpalane czasowo. Można by się pokusić o przeliczaniu w cron-ie przy modyfikacji wartości... ale jak dla mnie ma to niski priorytet, pewnie dlatego, że pola te są bardziej developerskie i my sobie je "odświeżamy" na żądanie....

Nie jestem pewien co do tych dublujących się wartości, ale w mojej opinii na 95% pokazują się tam unikalne wartości [może masz spacje] gdyby tak nie było, to mielibyśmy w tym polu tysiące duplikatów u klientów a mamy listę pojedynczych wartości. 

Zrób filmik na gitdev to pomyślimy co można z tym zrobić.

**Comment by florek41** [comment]
Wszystko rozumiem i nie mam problemu, że jest to generowane przez cron, ale właśnie nie aktualizują się te pola - testowane na gitdev.
https://gitdeveloper.yetiforce.com/index.php?module=Project&parent=&page=1&view=List&viewname=45&orderby=projectname&sortorder=ASC&search_params=[[[%22projectname%22%2C%22c%22%2C%22Project+55%22]]]
na liście widzimy *tasksat* = Open kiedy to zadania mają dwa inne statusy https://gitdeveloper.yetiforce.com/index.php?module=Project&relatedModule=ProjectTask&view=Detail&record=110&mode=showRelatedList&tab_label=Project%20Tasks
Minęły 4godziny i wartość się nie zaktualizowała.

Jeśli chodzi o powielone wartości - na chwilę obecną nie jestem w stanie tego sprawdzić (ze względu na powyższe), ale jestem pewien, że w opisywanym przykładzie wartości były takie same - wybrane z listy pickilst ze statusem.

**Comment by reeid** [comment]
@florek41 at the end of cron command add: 
2>/path-to-your-logs-folder/cronlog.txt 1>&2
than see what cron says....

**Comment by bpabiszczak** [comment]
Nowe pole służy do pokazywania wartości z modułów powiązanych. Przy czym nie było one projektowane dla pokazywania wartości z pól typu picklist [nawet nie wiem jak dla tych pól się to zachowa, może prawidłowo a może nie]. Pola te wymagają większej uwagi, a więc będą dostępne w trybie developerskim, aby nie powodować jakiś problemów i niejasności. 

Zasada działania tego pola jest następująca [zakładamy, że mamy moduł A a w nim moduł powiązany B]:
a) jeżeli powiążemy rekord B do modułu A wówczas system uaktualnia pole relacji w module A. 
b) jeżeli usuniemy powiązanie rekordu B z modułu A, wówczas system uaktualnia pole relacji w module A. 
c) gdy z jakiegoś powodu potrzebujemy odświeżyć całą bazę przechowanych wartości, wówczas mamy skrypt w systemie, który za pomocą CRON-a uaktualnia całą bazę. To czy CRON działa czy nie, decyduje wartość w tabeli która powoduje wywołanie tego mechanizmu [wartość ta jest ustawiana np. przy tworzeniu pola]. 

Jak widać z listy powyżej, nie ma znaczenia to, że zmienisz coś na rekordzie B. Działa to trochę jak faktura, gdzie zmiana danych kontrahenta nie wpływa na fakturę wstecz. To czy jest to słuszne czy nie to kwestia sporna, ale nie jest to w mojej opinii błąd, ponieważ mechanizm został tak zaprojektowany i działa on poprawnie. 

Co do wartości w liście rekordów i filtrach, to są one pobierane dynamicznie i tworzona jest unikalna lista wartości [w przypadku pojedynczego rekordu, nie jest to lista unikalna]. Tu też nie widzę jeszcze problemu. Można by zrobić tak, że w obrębie rekordu lista również już jest unikalna, tylko co w momencie, gdy ktoś w relacji pozwala zapisać więcej niż jedną wartość? U Ciebie tak się stało, ponieważ my to projektowaliśmy pod produkty/usługi i tam nazwa jest unikalna... a Ty zbudowałeś to na polu nieunikalnym w obrębie modułu którego relacja dotyczy.

**Comment by florek41** [comment]
@bpabiszczak ogromne dzięki za wyjaśnienie działania tego pola. W takim razie masz rację, że działa ono poprawnie - zgodnie z założeniami projektowymi. Miałem swoje wyobrażenie tej funkcji, które niestykanie nie jest poprawne :)

Chciałem użyć tego w zamian funkcji, której po raz kolejny brakuje - możliwość aktualizacji powiązanego rekordu za pomocą workflow.

Tak czy inaczej - może warto wziąć pod uwagę to, że pole da się skonfigurować dla wartości z picklist.

**Comment by bpabiszczak** [comment]
ale z tego co rozumiem i z tego co piszesz to da się to ustawić dla pól typu picklisty... przy czym pytanie brzmi jaki jest tego sens biznesowy. Jak możesz wytłumacz mi sens biznesowy tego co chciałeś osiągnąć ze statusami zadań na projekcie.

**Comment by florek41** [comment]
Widzisz, dla mnie to pole miało sens w momencie kiedy jego wartość uaktualniałaby się wraz ze zmianą wartości z wybranego-powiązanego modułu.

Da się ustawić dla picklist, ale już filtru na tej podstawie nie możemy stworzyć, bo mamy np. 5 wartości "Completed".

Ważniejszy celem niż nawet samo wyświetlanie wartości na liście, była dla mnie możliwość stworzenia filtrów dzięki którym możliwe byłoby wybranie tylko rekordów w których powiązane zadania są zakończone/w trakcie/ect.
Oczywiście takie 'zabiegi' możliwe byłyby także np. w procesie sprzedażowym itd.
O podobnych filtrach (na podst. modułu powiązanego) wspominał @echemik w temacie o procesie sprzedażowym #2500

**Comment by bpabiszczak** [comment]
o ile przykłady @echemik były racjonalne [pokaż mi klientów, którzy mają więcej niż 3 szanse, albo pokaż mi klientów dla których nie było szansy dłużej niż x czasu] o tyle nadal nie rozumiem Twojego przykładu biznesowego. 

Bo jakie znaczenie ma to, że jeżeli na projekcie jest 100 zadań a jedno z nich ma status B a w przypadku drugiego projektu również jest 100 zadań z czego 99 ma ustawiony status B... W sensie jaką masz tu wartość biznesową. 

Nie wiem czy wiesz co daje nasze pole w zastosowaniu w jakim zostało zaprojektowane, ale zerknij sobie na ten filmik: 

![tree](https://cloud.githubusercontent.com/assets/10197525/12080051/ee72fe76-b24e-11e5-9575-c23d9b70523e.gif)

To wszystko bazuje na polu picklist do którego na każdej zmianie w module powiązanym jest aktualizowana lista wartości. Zobacz sobie np. na ten filmik, który pokazuje dokładnie to samo, ale z perspektywy listy rekordów:

![tree2](https://cloud.githubusercontent.com/assets/10197525/12080075/e1ea52de-b24f-11e5-8e60-706c1287762c.gif)

W zaprojektowanym przypadku ma to bardzo fajną użyteczna funkcjonalność polegającą:
1. Pokazaniu klientów mających/zainteresowanych danym produktem/usługą
2. Możliwość filtrowania danych po produkcie/usłudze.
3. Możliwość raportowania danych po produkcie/usłudze.
4. Wizualizacja danych na specjalnym widoku po kategoriach.

A więc pytanie brzmi:
1. Do czego ma służyć Twoja funkcjonalność [konkretne korzyści biznesowe]. 
2. Dlaczego nie dodasz tego do YetiForce :P
