### ISSUE TITLE
invoice table pdf

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#2348]
when creating pdf invoices we have error in table output.
Table output issue for invoice with page break.
I use #special_function#replaceProductTable2#end_special_function#
see attachment

heres is samlple from page1.
![table-issues](https://cloud.githubusercontent.com/assets/10504154/11474065/07a75aac-9776-11e5-8749-c7076fd67ab6.png)

here is output to show difference between page 1 and page 2.
![table-issue-page-break](https://cloud.githubusercontent.com/assets/10504154/11474066/09221d04-9776-11e5-8d62-81cfae4a2b84.png)

**Comment by bpabiszczak** [comment]
We support only new pdf module: https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35
