### ISSUE TITLE
[Question / Need Help] Birthdate

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2349]
We want to send a Birthday Greeting on our clients' Birthdays.  I created a Mail Template, and a Workflow, but how do I set the logic to check if the birthdate "Day" is today?

**Comment by florek41** [comment]
Isn't it duplicate: #1852 ?

**Comment by mykljohn** [comment]
Why don't these come up when I search for them?

**Comment by bpabiszczak** [comment]
At the moment there's no such option, you can for example create a widget that will show you anything you want, but it requires some programming work. We are going to add new mechanisms soon.

**Comment by mykljohn** [comment]
I found a php function for vTiger, SendBirthdayReminder.php.  It's based off of SendReminder.php.

Can this be called in the Scheduler the same as SendReminder (SendReminder.bat)?  Here's a copy (.txt)

[SendBirthdayEmail.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/50259/SendBirthdayEmail.txt)
