### ISSUE TITLE
problem z cennikami

### ISSUE THREAD

**Issue by ROBiBOB** [YetiForceCompany/YetiForceCRM#2352]
Brak możliwości wyboru cen na podstawie zdefiniowanego cennika
![cennik_brak_wybor_1](https://cloud.githubusercontent.com/assets/16098743/11502114/358ed4fe-9839-11e5-8fe1-13ff779c78c5.gif)

**Comment by bpabiszczak** [comment]
Proszę o weryfikacje w nowych modułach z produktami np.: https://gitdeveloper.yetiforce.com/index.php?module=SQuotes&view=List&mid=123&parent=118
