### ISSUE TITLE
brak zakładki dokumenty przy dostawcach

### ISSUE THREAD

**Issue by ROBiBOB** [YetiForceCompany/YetiForceCRM#2353]
Dostawcy bez możliwości podpięcia zakładki z dokumentami; np. cenniki, karty produktowe, ..
![dostawcy_brak_dokumenty_1](https://cloud.githubusercontent.com/assets/16098743/11503552/7a035738-9841-11e5-8226-6bd1a5d05afa.gif)

**Comment by witer30** [comment]
musisz włączyć "administrację" modułów powiązanych, będziesz mógł usuwać, dodawać moduły... Było w którymś poście 
Jeśli się nie mylę to tu
config/developer.php
// Adding/Deleting relations between modules.
	'CHANGE_RELATIONS' => false, 
zmień na true

**Comment by bpabiszczak** [comment]
ale tylko w relacji M:M [powinno wystarczyć] relacje 1:M robimy z modułu zarządzania polami. 
@witer30 dzięki.

**Comment by bpabiszczak** [comment]
Jak to rzekł mój programista: "Panel bazuje tylko na dwóch funkcjach: get_dependents_list, get_related_list, więc tworzenie powiązania z dowolnym modułem wymagającym innej funkcji nie będzie działać prawidłowo, a do nich zaliczają się dokumenty (get_attachments)". A więc trzeba dodać relacje ręcznie lub z vtlib.
