### ISSUE TITLE
[Question / Need Help] Reports

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2361]
I created a Report from SalesOrders (Enrollments) but the total is 0.  Why?  If I click View Details, the total is there.  

Account Name	Enrollment Number	Subject	Enrollment Date	Due Date	Assigned To	Total	Action
Bob Smith	SO190	enroll for bob	2015-11-18	2015-12-01	Administrator 	0	View Details

Come on guys...I need some help here and with the Mail Templates, otherwise my boss is pulling the plug and going with something else.  And I'm out of a job.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2110
