### ISSUE TITLE
Microsoft Exchange

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2362]
Is there anyway to integrate Exchange Server with yetiforce without enabling smtp and pop3 ? 

Best regards

**Comment by bpabiszczak** [comment]
You need IMAP & SMTP.

**Comment by yozhi** [comment]
thank you anyway, i have 1 more question, different from topic title, and my question is , how can i remove a module mannually ? because i created a module , but when i was importing record to the module i created it showed me a error "Error!!! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax bla bla..." , and now i cant remove the module from "module installation" , can you please tell me how can i do it ? and if im not abusing , can you tell why i got this error and where/how can i fix it

**Comment by bpabiszczak** [comment]
one problem one issue. Please open new.

**Comment by yozhi** [comment]
openning
