### ISSUE TITLE
Background Login

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2363]
How can i add a background on login page ? i checked jqueryBxslider.css and everything seems to be ok , where i have to change to enable my background image?

**Comment by nikdejan** [comment]
I guess you are talking about logo image.
If you develop for web you should already have installed Firebug add-on for Firefox. Right-click on the logo and then click Inspect Element with Firebug. You will see html code for logo image and it is something like this <img class="logo" height="" alt="" src="storage/Logo/logo_yetiforce.png" title="">
If you want to change logo you should create your own image, name it logo_yetiforce.png and put it in storage/Logo, replacing old logo. 
If you are talking about background than you can see that background color is defined in layouts/basic/skins/login.css (login.min.css) for Responsive Layout and in layouts/vlayout/skins/login.css (login.min.css) for Default, Vlayout.
Google Chrome can also inspect elements so you actually do not need Firebug for Firefox.

**Comment by bpabiszczak** [comment]
Thank You @nikdejan

**Comment by witer30** [comment]
logo can be change in the admin panel in Company details

**Comment by yozhi** [comment]
no, i dont mean the logo, the logo its easy to change, i mean the background, in this case he doesn't exist , or can say that its white

**Comment by nikdejan** [comment]
Well, I told you where relevant css file is. You need basic css knowledge to finish the job. If you don't know how, then you should ask on some other place, not here.

**Comment by yozhi** [comment]
ah ok , i had not seen that, sorry , i'm going to try to change it, thank you

**Comment by yozhi** [comment]
i got it, if any body want to add a background go to path nikdejan said(layouts/vlayout/skins/login.css and layouts/basic/skins/login.css), and in both files change "body{background:#f0f0f0}" to "body{background-image: url("blabla.jpg")}", hope it help you.

**Comment by ldgbc** [comment]
Newer version seem to have moved this file to:

\public_html\layouts\basic\modules\Users

**Comment by acsinsurancegroup** [comment]
@ldgbc 

> For me, I updated the .min file, you need to change this lines:
html,body{background:# }

What did you change in that area to display an actual background instead of just the plain blank login screen with adjustable color?

**Comment by walfs** [comment]
Yetiforce 2019: 

When making the change, and putting a background image the console throws the following error:

  Refused to load the image 'URL.jpg' because it violates the following Content Security Policy directive: "img-src 'self' data: a.tile.openstreetmap.org b.tile.openstreetmap.org c.tile.openstreetmap.org ".

For what is this? in which file "img-src" is authorized, is it safe?
