### ISSUE TITLE
Design several bugs 5.5 Inch mobile

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2364]
![s51202-140113](https://cloud.githubusercontent.com/assets/6897502/11530459/7508c49a-98fd-11e5-91b6-68aaec5da06a.jpg)
![s51202-140103](https://cloud.githubusercontent.com/assets/6897502/11530466/830773c0-98fd-11e5-971e-95455607880d.jpg)

**Comment by TomaszQr** [comment]
37893f4f926eee0c8f31e00d4ca250663caaa416
34b8dcf501b023e3f924ef8cbffb4fe0279892d6
532ad5784e78371334e5fbff60f1b767d10f3130
3b5b7b561ffe0f5c7f9bd21148aa8668116a11fc
f228590cd42fbe7503db14da9a1423c5f459ec41
