### ISSUE TITLE
[question] DataTime field in custom module

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2365]
Hello, how to create Datatime field in the generated module? When a module in the choice of the value of the field is absent. maybe there is a solution to this problem without changing the source code, or there is an example of how to add this type of field.

**Comment by nikdejan** [comment]
I think for that you need to edit code. I've read somewhere that people created text field and then changed field type in database, but never tried that myself.

**Comment by kjradv** [comment]
nikdejan, thanks for the information, now try to do it on a more convenient solution, on the basis of the calendar and booking module.
I think that will do everything at the module level, since classes have already been described. Strange that I did not think to go directly to the modules where it is implemented..

/include/utils/RecurringType.php
/modules/Calendar/uitypes/Datetime.php

thanks for the help, nikdejan.

**Comment by nikdejan** [comment]
Booking module? I guess you are talking about Reservations module or maybe there is something else?
I am trying to find/adapt a module which I could use for accommodation booking.

**Comment by kjradv** [comment]
Yes, it's a kind of reservation, only areas (conference rooms). Who Vtiger I have to do it using the library fullcalendar.io with Addenda scheduler.
as faster solution I can offer and create a module through api yetiforce work with Stronach calendar.

###### Dear developers may want to add support http://fullcalendar.io/scheduler/ or alternatives for booking module?

**Comment by nikdejan** [comment]
Have you tried Reservations module from yetiforce?
What is Stronach calendar?

**Comment by kjradv** [comment]
currently I am trying to do this on YetiForce, but while plugging in the data type DataTime.
Stronach - third-party solutions calendar

**Comment by bpabiszczak** [comment]
1. Currently we are able to create date and time fields separately.

2. You can create a date and time field together, but it requires the use of vtlib.

3. Normally, a new field type should be added, and it should be part of YetiForce. If something is not in the system then it should be added, instead of trying to "artificially" solve the problem
