### ISSUE TITLE
[ISSUES] User

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2367]
Installed version 2.3.595, the user why Yetiforce Demo?

**Comment by kjradv** [comment]
Поправь просто строчку кода в шаблонах правое меню

**Comment by yozhi** [comment]
go to layouts/vlayout/modules/Vtiger/TopMenusRight.tpl line 51 and delete what you got between <a </a> (line 51,52,53) and add it "{if !empty($src)}
				<a id="menubar_item_right_{$title}" class="dropdown-toggle" data-toggle="dropdown" href="#"><img src="{$src}" alt="{vtranslate($title,$MODULE)}" title="{vtranslate($title,$MODULE)}" /></a>
			{else}
				{assign var=title value=$USER_MODEL->get('first_name')|cat:' '|cat:$USER_MODEL->get('last_name')}
				<a id="menubar_item_right_{$title}"  class="userName dropdown-toggle" data-toggle="dropdown" href="#" title="{$title}"><strong>{$title}</strong><span class="caret"></span> </a>
			{/if}"

**Comment by bpabiszczak** [comment]
Fixed, check last dev version.

**Comment by yozhi** [comment]
where we can find it?

**Comment by waw555** [comment]
The development branch, the release has not yet been released

**Comment by nikdejan** [comment]
You can download dev version from here: https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by yozhi** [comment]
how can i update mine ? this is the main with all files
