### ISSUE TITLE
Error!!! SQLSTATE[42000]

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2368]
i created a new module and i got this issue when i was import records, so i tried to delete the module, but when i go to delete, the module still installed , so how can i remove the module mannualy and how can i fix the error or where "Error!!! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax "

**Comment by bpabiszczak** [comment]
The issue doesn't contain the minimum of info required to analyze your problem:

1. No information how the moduloe was added [vtlib, from panel, maybe purchased somewhere]
2. No logs information
3. No information whether the problem occurs in the test version

Please read this https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html and complete your issue.
