### ISSUE TITLE
[PL] logowanie za pomocą skryptu zewnętrznego

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#2369]
Czy można jakoś zalogować się dynamicznie do systemu z poziomu zewnętrznego skryptu który przyjmuje parametry jaki użytkownik ma się zalogować?

**Comment by bpabiszczak** [comment]
Tak, pod warunkiem, że skrypt znajduje się w katalogu głównym systemu. Jeżeli nie, to są na to metody [np. aplikacja mobilna pobierane dane z systemu, portal klienta pobiera dane z systemu], ale nie ma się pełnego dostępu tylko ograniczony.
