### ISSUE TITLE
Created module icon 

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2371]
I created a module and assigned a icon to the module on menu configuration with the name "userIcon-modulename" and i uploaded the image into "layouts\basic\skins\images" with the name "modulename" , but the icon only shows on "modules-installation", what can i do to show on menu and or into the module?

**Comment by rskrzypczak** [comment]
At the moment the name of the icon 'userIcon-...' is a specific name for the purpose of the module icons and they have a separate folder '..layouts\basic\skins\icons'. If you want to add your own picture, it's enough that you enter the file name, for example 'NewModule.png', in the field, and place the file in the location you specified.

**Comment by yozhi** [comment]
i didn't get it, can you be more specific ? thank you

**Comment by rskrzypczak** [comment]
At the moment
![icontomenu2](https://cloud.githubusercontent.com/assets/10221999/11802242/d3b6fe9e-a2ee-11e5-873b-516b431aca23.gif)

**Comment by yozhi** [comment]
thank you, i got it, you were very helpful thank you very much
