### ISSUE TITLE
[bug] Unable to delete relation to email

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2377]
![delete_email_relation](https://cloud.githubusercontent.com/assets/13381850/11589950/fd2809c2-9a8c-11e5-9e54-953c3dd84bd5.gif)
This has been recorded in test.yetiforce.com, but there is the same problem with gitdeveloper.
Relation of email with any other module can not be deleted. If I try from module (i.e. Opportunities) I can not delete related email (i.e. I can not delete relation). Also, if I try from Corporate Email to delete related Opportunity (i.e. to delete relation with Opportunity) I am unable to do that. 
If I want to delete related Opportunity from Account module, I can do that with no problem, i.e. I can actually delete Opportunity.

**Comment by MaciejStencel** [comment]
Deletion of this relation was fixed in all modules that show related emails.

You can test it in gitdeveloper.
