### ISSUE TITLE
[bug] Cannot create filter in responsive layout

### ISSUE THREAD

**Issue by rubichcube** [YetiForceCompany/YetiForceCRM#2378]
When in the default vlayout I can create a filter on the listview for that module. I cannot create a filter when in responsive layout.
![cantceratefilter](https://cloud.githubusercontent.com/assets/14298864/11596724/dd78be3a-9a84-11e5-8a8b-4e4b15441d26.gif)

**Comment by bpabiszczak** [comment]
Fixed, check new gitdeveloper version.
