### ISSUE TITLE
[BUG DESIGN] Fonts

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2380]
![animation 165](https://cloud.githubusercontent.com/assets/1402355/11605778/eb957792-9b29-11e5-8182-fe8e6b2e71c8.gif)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/2e173aa52fa76940ad24afa5c765c1e3ac7a93cb
