### ISSUE TITLE
[question] Field Mapping

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2384]
I suppose the Mapping -function is not working with the "old" modules e.g. Opportunities and Quotes?

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/086f5d4d25bfacd34c6ca843b059b7ef749a7171

In order to map fields you should use the mapping panel: https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95

**Comment by kpaulaha** [comment]
Great function, superb.


-------- Alkuperäinen viesti --------
Lähettäjä: Radosław Skrzypczak <notifications@github.com> 
Päivämäärä: 09.12.2015  11.06  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] [question] Field Mapping (#2384) 

Fixed in 086f5d4

In order to map fields you should use the mapping panel: https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95
