### ISSUE TITLE
[BUG] PHP warning & dav not enabled on gitdeveloper

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2385]
I want to test dav sync on gitdeveloper but on 2.3.628 i've got:
```
Warning: in_array() expects parameter 2 to be array, null given in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Settings/Dav/views/Keys.php on line 26
```

and info about that dav is not enabled:
```
DAV application is not active

DAV application has not been activated yet, enable it in config/api.php
```

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html
2. Please check on PHP 5.6

**Comment by florek41** [comment]
This is on yours gitdeveloper :) so it's php 5.6.6

https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Dav&view=Keys&block=5&fieldid=77

**Comment by bpabiszczak** [comment]
Sprawdzaliśmy ostatnio integracje na androidzie i działała poprawnie [i to kilka razy w zeszłym tygodniu bo klientów podpinaliśmy testowo], zauważyliśmy błąd z integracją z iPhone 5s który nadal występuje, podaj proszę z jakiego urządzenia się logujesz i w jakich godzinach, sprawdzimy w logach co się dzieje.

**Comment by florek41** [comment]
u mnie to iphone 4
Uruchomiłem ~10 min. temu.
Na chwilę obecną wygląda to tak, że zadanie dodane z poziomu tel. jest w kalendarzu YF, ale dodane w YF nie pojawia się w telefonie.
dam znać czy coś się zmieni w tej kwestii.

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/65323a8a81099ca8ae95595a604751de34fadf73

**Comment by florek41** [comment]
Dobra, poszło - najwidoczniej po ostatniej poprawce.
Teraz wygląda to tak, że każdy status inny niż zaplanowane w YF np. Zaległe w telefonie jest wyświetlane jako anulowane - nie do końca to poprawne wg mnie.

Może powinienem założyć nowe zgłoszenie ?

**Comment by bpabiszczak** [comment]
Tak, na pewno nowe zgłoszenie to dobry pomysł. Jeżeli masz możliwość, testuj również pod Androidem, wtedy nam pomożesz w szukaniu problemu [iphone i nadroid mają inny format danych].
