### ISSUE TITLE
Cannot view document list in module

### ISSUE THREAD

**Issue by sangeetasoni19** [YetiForceCompany/YetiForceCRM#2386]
When I add or select a document in a custom module I cannot see the document in the list. Even the count of document is shown 0.

**Comment by bpabiszczak** [comment]
Show it by using this tool: https://screentogif.codeplex.com/.
Example: https://github.com/YetiForceCompany/YetiForceCRM/issues/2392
Please read this: https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2353#event-486107869

'..The panel used to manage relations is based on standard functions get_dependents_list, get_related_list and therefore creating relations with any module that requires a different function won't work properly, and that includes documents (get_attachments)..'
