### ISSUE TITLE
going from stable to developer

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2388]
Is there an easy way to go from the stable version to developer.  Or do you think there will be a stable release soon? 
Thanks!

**Comment by bpabiszczak** [comment]
we need 1-2 weeks to public stable version. Now you can test this Update Package https://github.com/YetiForceCompany/UpdatePackages/blob/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0/zip/2.3.0_to_2.4.0_vRC4.zip
