### ISSUE TITLE
more then 25 fields in reports

### ISSUE THREAD

**Issue by networkpanic** [YetiForceCompany/YetiForceCRM#2390]
Is it possible to set more then 25 fields in reports?

is there any way to generate exports with more fields?

**Comment by ralphkretzschmar** [comment]
Or in Listviews more columns than 12?

Best regards,
Ralph

**Comment by networkpanic** [comment]
any suggestions where the limit is located?
we can try to fix it, in vtiger we was able to fix it in resources/app.js

**Comment by witer30** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Vtiger&amp;parent=Settings&amp;view=ConfigEditorDetail&amp;block=4&amp;fieldid=25
max entries per page i guess
Dnia 15 grudnia 2015 9:58 Martin napisał(a):
 any suggestions where the limit is located?
we can try to fix it, in vtiger we was able to fix it in resources/app.js—

**Comment by ralphkretzschmar** [comment]
We are interessted to remove the limit for columns in REPORTS & LIST-VIEWS.
List Views are currently limited to 12 columns and the Reports for 25 columns.
in vTiger we were able to patch the app.js to have a workaround for that.

We want to run a test with yetiforce but we need some more columns in List-Views & some more in our Reports. Especially to export customized report data.

Best Ralph

**Comment by networkpanic** [comment]
Limit increased to 100 by me

TODO: changing the value in frontend

**Comment by ezbank** [comment]
Is it possible to set more then 12 fields in listview? v4.3
