### ISSUE TITLE
Creating service order from ticket.

### ISSUE THREAD

**Issue by Bergdahls** [YetiForceCompany/YetiForceCRM#2391]
I have tried to make, create a service order for a internal repair shop from a customers filled in webforms. But I'm stuck. I don't really know how to make a form for that and get it to work in flow process. Trying to set ticketfield information but cant add correct fields for a good form. Any kind person who can just give me any start hints. Would be very glad.

Should I upgrade to DEV release?

**Comment by bpabiszczak** [comment]
1. I don't understand why should the form work in workflow?
2. To add something from the form, you either use a webform [not recommended] or use the webservice [we don't use it], or create your own file, that the form refers to, and the file does whatever we want it to do in the CRM [we do that].
3. You can also send the form to an e-mail and then create an action responsible for creating the respective things in the CRM.
4. When we create whatever we wanted in the CRM, then we can run the workflow.
5. Why are you asking us about the update to DEV version? An update like this requires testing, and most of all, estimation of the the benefits of this update. If there is something you need there, and the system is stable after the update, then why not.

**Comment by Bergdahls** [comment]
Dear Błażej Paraszczak,
Thanks a lot for your guidelines and explanations.
I realize that a external form is the best way to collect info for a
service order or to create a support ticket. Now I'm running 2.3.547 on a
test server and I seems to work well so far.


2015-12-09 11:36 GMT+01:00 Błażej Pabiszczak <notifications@github.com>:

>
>    1. I don't understand why should the form work in workflow?
>    2. To add something from the form, you either use a webform [not
>    recommended] or use the webservice [we don't use it], or create your own
>    file, that the form refers to, and the file does whatever we want it to do
>    in the CRM [we do that].
>    3. You can also send the form to an e-mail and then create an action
>    responsible for creating the respective things in the CRM.
>    4. When we create whatever we wanted in the CRM, then we can run the
>    workflow.
>    5. Why are you asking us about the update to DEV version? An update
>    like this requires testing, and most of all, estimation of the the benefits
>    of this update. If there is something you need there, and the system is
>    stable after the update, then why not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YetiForceCompany/YetiForceCRM/issues/2391#issuecomment-163183623>
> .
>



-- 
Med vänlig hälsning,
Tony



================================================================

Tony Bergdahl
Frötunagränd 17
19455 Upplands Väsby
Stockholm, Sweden

Skype: tonybergdahl
070-220 67 15

Huvudmailadress: tonybergdahl@hotmail.com

**Comment by witer30** [comment]
Can you share how you did it? some screenshoots would be nice to see... 
thanks in advance

**Comment by Bergdahls** [comment]
Dear Witer30,
Im not finish with this and just config now and then so it will take time. Anyway I found some good info in Vtiger manual online. I hope we can make an admin/user manual for YetiForce.
