### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2392]
Is there a way to hide detail fields if not used?  all fields would only be visible in the editable form?

**Comment by eptapsyxos** [comment]
Please Write  a proper post title. Help your self And us. No Hard fellings.

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

![2392](https://cloud.githubusercontent.com/assets/10197525/11666630/bc0db0f4-9ded-11e5-9d24-330aa3b3d05a.gif)

**Comment by jbmcclain** [comment]
What i was going for is that it would still be active, just not view-able if there was not any content in the field when a user would just look at the details.  But when they would edit the details the would see the empty fields and be able to add content.

**Comment by bpabiszczak** [comment]
At the moment the system either shows the filed, or it doesn't. There's no mechanism that would determine the field's visibility based on some specific conditions, like eg. no value.
