### ISSUE TITLE
[bug] - menu configuration 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2394]
After update from version 2.3.193 to 2.3.547 there is no possibility to switch between menus for groups...
![animation 0](https://cloud.githubusercontent.com/assets/11491482/11668611/66cc27d2-9df8-11e5-8d61-9ba132bb0753.gif)

**Comment by bpabiszczak** [comment]
work on gitdeveloper: https://gitdeveloper.yetiforce.com. Maybe you have some errors in logs.

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/8431df2dea71f55df2f883f815b7dedb06e7c9ef

**Comment by witer30** [comment]
thanks, works...
Can be closed...
