### ISSUE TITLE
Pricebook not available from SalesOrder, Invoice, or Quote 

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2397]
We moved to a new host with php 5.6 and the upgrade to 2.3.49 went fine and all the labels are visible, but when I click on the Pricebook from SalesOrders, Invoices, and Quotes, the popup is displayed, but no data to be selected.  It shows 1 of 12 in the top so the records found. 

![screenshot_1](https://cloud.githubusercontent.com/assets/11919990/11676869/ea4ec8ea-9dfc-11e5-9811-d38e2930c335.png)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2461

**Comment by rezaizadi** [comment]
I Fixed this problem
at this file: \modules\PriceBooks\models\Record.php
change function name getProductUnitPriceURL to getProductListPriceURL
