### ISSUE TITLE
[question] field mapping

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2399]
Hello, maybe someone experienced as you can to make their conditions for the fields?
![snimok](https://cloud.githubusercontent.com/assets/15871611/11677735/2b3849e4-9e52-11e5-9d4a-06813fff6c15.JPG)

**Comment by bpabiszczak** [comment]
This module will be removed in version 2.4 and replaced with a new one. More info here: https://github.com/YetiForceCompany/YetiForceCRM/issues/2461

**Comment by kjradv** [comment]
thanks for the answer.
And when it will be possible to look at a new module with the Dev branch?

**Comment by bpabiszczak** [comment]
1. CRM: https://gitdeveloper.yetiforce.com/
2. Field mapping: https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95
3. New module: https://gitdeveloper.yetiforce.com/index.php?module=SRecurringOrders&view=Edit - under construction, you can write a list of missing features.
