### ISSUE TITLE
Language translation module: "save" still not fixed

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#24]
When I open 3 languages (englisch, german, german old) and translate the one in the middle (german), the changes were always saved on the last (third, german old) language file.

**Comment by bpabiszczak** [comment]
Tu tak samo, brak komentarza jest tylko zamknięcie. 
---

Z poważaniem / Regards 

BŁAŻEJ PABISZCZAK 
_Chief Executive Officer_ 
M: +48.884999123
E: b.pabiszczak@yetiforce.com 
-------------------------

We created an innovative CRM system that is open and adapts perfectly to
your business. Find out about its capabilities by downloading it [3] or
testing [4]. Change your system to YetiForce [5]! 

W dniu 2015-01-21 10:23, Mariusz Krzaczkowski napisał(a): 

> Closed #24 [1]. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/YetiForceCompany/YetiForceCRM/issues/24
[2]
https://github.com/YetiForceCompany/YetiForceCRM/issues/24#event-222180332
[3] https://sourceforge.net/projects/yetiforce/
[4] https://test.yetiforce.com
[5] https://yetiforce.com/

**Comment by mariuszkrzaczkowski** [comment]
Bug fixed in the issue #43
