### ISSUE TITLE
[question] - top bar of search

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2400]
can you help me and provide solution for below issue with search bar in new layout... 
As I am correct it was solved but couldn't find it...
thanks a lot
![image](https://cloud.githubusercontent.com/assets/11491482/11680946/137988b8-9e5c-11e5-8760-6b71d6ce0445.png)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2356
