### ISSUE TITLE
hovering over Related field 1:M Dialog

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2405]
Is there anyway to add to the dialog that pulls up over a related 1:m Filed to see more info?
![contact info](https://cloud.githubusercontent.com/assets/1903662/11688205/25562666-9e59-11e5-89b8-7e2f8697400c.jpg)

**Comment by nikdejan** [comment]
When hovering you see fields from Summary View of the related model. So if you want to add some more fields you need to add them in Contacts summary view.

**Comment by bpabiszczak** [comment]
Thank you @nikdejan
