### ISSUE TITLE
Projects Module

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2406]
looking for a way to assigning multiple team members to a project.  Since every project could have different team members associated to it.  Kind of like multiple select combo box but it would pick users.

This way the work flow would notifies the users who have been assigned to the project.

**Comment by florek41** [comment]
**Shared with** field is what you looking for :)

**Comment by jbmcclain** [comment]
Is the shared with field in the version 2.3.49 version?  When i pick add custom filed this is not one of the options

**Comment by florek41** [comment]
**Share with users:** field exist in all modules.

![sharewith_field](https://cloud.githubusercontent.com/assets/4824588/11752344/5fdcc6b8-a03f-11e5-9800-9360e9d07015.JPG)

**Comment by jbmcclain** [comment]
Crap maybe i accidentally removed it long ago...anyway to bring it back?

**Comment by jbmcclain** [comment]
never mind i must of deactivated it.

**Comment by jbmcclain** [comment]
Is there a way to put shared with users in custom modules?

**Comment by bpabiszczak** [comment]
The principle of adding this field is the same as adding any other field using vtlib. And exactly the same as for the "Assigned To" field.
