### ISSUE TITLE
[Improvement] Widgets Remove Button

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2408]
Add and Select buttons are available on Widgets.  A remove button would be nice as well.

**Comment by bpabiszczak** [comment]
Put a screenshot

**Comment by mykljohn** [comment]
Actually, I think there is a delete button, just not on all related...not sure why.
![screenshot_6](https://cloud.githubusercontent.com/assets/11919990/11801171/067deae0-a2a9-11e5-8db2-4cd3bf72c8ef.png)

**Comment by konadrian** [comment]
This buttons exist in current version
![buttons](https://cloud.githubusercontent.com/assets/3193498/15242883/cbb851e0-18f8-11e6-8869-8bf8a6d273c6.png)
