### ISSUE TITLE
[Bug] Widgets - Select Button

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2409]
It appears that the Select Button can't be added without the Select Button.  In ver 2.2 when I check only the Select box and not the Add, the Widget freezes.

**Comment by bpabiszczak** [comment]
Does the problem exist on the dev version? Place a screenshot of the problem highlighted here.

**Comment by mykljohn** [comment]
Sorry, finally had a chance to check.  Yes it happens on Dev Version.  As you can see in the screenshoot, the widget is defined as Select only.  In the 2nd screenshot, YF freezes while loading the widget.

![screenshot_2](https://cloud.githubusercontent.com/assets/11919990/11875625/32826e32-a4ab-11e5-8ad7-2bda067e5db3.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/11919990/11875629/3809578a-a4ab-11e5-990b-5be19c29cc76.png)
