### ISSUE TITLE
add more fields for products to quotes PDF

### ISSUE THREAD

**Issue by jeremyrigby** [YetiForceCompany/YetiForceCRM#241]
Is it possible to include more fields in PDF for quotes. When I add a product I like to have the part number and its description displayed. I have been unable to find "Item Detail" section in fields

Thanks

Jeremy

**Comment by bpabiszczak** [comment]
Anything what cannot be done from the panel, can be achieved through special functions [but it requires adequate expertise in programming and applies only to PDF]. If you would like to display additional information in CRM in the block with products, it requires some programming in the engine of CRM. In the future we are going to redevelop the entire PDF module and there will be a possibility to enable particular columns.
