### ISSUE TITLE
[Improvement] Widgets Display Calculation

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2410]
I've created a Widget for Employees with their schedule.  Which shows their Hours.  It would be awesome to display the sum of that field at the bottom of the widget.

**Comment by bpabiszczak** [comment]
put the screen.

**Comment by mykljohn** [comment]
![screenshot_7](https://cloud.githubusercontent.com/assets/11919990/11801076/e6c82efa-a2a7-11e5-8fe3-9de0ed526b19.png)

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
