### ISSUE TITLE
[bug] - Kalkulacje

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2417]
versja 2.3.547
na stronie głównej widget Kalkulacje przy wyborze wszystkie wyświetla błąd... 
![image](https://cloud.githubusercontent.com/assets/11491482/11715068/301f2368-9f3f-11e5-988c-018df87c73d8.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/6db0a7d2ce10124bf83deb854570aa0f6ba5e245
