### ISSUE TITLE
[PL] Jak dodać pole typu picklist do Wydarzenia z kalendarza?

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#2419]
Czy można jakoś dodać pole typu picklist do rekordu eventu activity z kalendarza?

**Comment by bpabiszczak** [comment]
Moduł kalendarza jest dość specyficzny, modyfikacja pól w nim została wyłączona. Jednakże nowa wersja kalendarza [nowa w porównaniu do vtiger-a] zakłada możliwość dowolnej rozbudowy, zapewne trzeba dodać to z poziomu bazy danych lub za pomocą vtlib. 

Może napisz dokładny scenariusz biznesowy, może będzie na tyle istotny, że dodamy to domyślnie w systemie.

**Comment by wbnx** [comment]
Potrzebujemy dodać pole typu Efekt spotkania, które dało by nam informacje o statusie klienta po spotkaniu przykładowe opcje do wyboru dla tego pola (zainteresowany, negocjacje, czekamy na podpisanie umowy). Przez vtliba programowo nie udało się:

$moduleInstance = Vtiger_Module::getInstance('Events');
$block = Vtiger_Block::getInstance('LBL_EVENT_INFORMATION', $moduleInstance);

$field  = new Vtiger_Field();
$field->name = 'lead_status';
$field->label= 'Status leada';
$field->uitype= 16;
$field->column = $field->name;
$field->columntype = 'VARCHAR(100)';
$field->typeofdata = 'V~O';
$field->setPicklistValues(array('Zainteresowany', 'Negocjacje', 'Czekamy na podpisanie umowy'));
$block->addField($field);

**Comment by florek41** [comment]
Moim zdaniem takie informacje nie powinny być zawarte w notatce kalendarza, bo ona jest informacją o rzeczy do zrobienia - spotkaniu, więc po zakończeniu oznaczana jest jako wykonana/zakończona - nie wiem co miałoby na celu zmienianie wartości pola i późniejsze kończenie. Co w momencie kiedy chcesz sprawdzić na jakim etapie są rozmowy z klientem ? Przeglądasz wszystkie zakończone zadania ?

Według mnie do tego jest satus Leada i tam powinna znaleźć się informacja o etapie rozmów.


Jeśli mówimy o funkcjonalnościach to dla mnie ogromnym ułatwieniem byłaby możliwość nawet nie edycji istniejących pól, a możliwość dodania własnych, ew. rozszerzenia List wyboru o nowe wartości.

Przy ToDo moglibyśmy dodać typ zadania - np. w moim przypadku - Prace Graficzne, Przygotowanie do produkcji, Rozłożenie materiału itd. Podobnie przy Terminach mamy **Rodzaj zdarzenia** i można by go rozwijać w zależności od branży i potrzeb.

To istotne przy codziennej organizacji pracy, gdzie osoba mająca listę zadań może ją przefiltrować, ustalić priorytety i już na pierwszy rzut oka ocenić ile czasu potrzebuje i co ma wykonać.

**Comment by bpabiszczak** [comment]
W mojej opinii typy są oke [telefon, spotkanie, zadanie] co najwyżej dodać KATEGORIE którą każdy może dowolnie sobie rozbudować...

**Comment by florek41** [comment]
Dla mnie pasuje - kwestia tego, żeby była opcja jakiejkolwiek modyfikacji, bo w tym momencie Kalendarz jest jedynym elementem którego nie można w "łatwy" dostosować.

**Comment by bpabiszczak** [comment]
Co nie zmienia faktu, że idea rozbudowy nie ma nic wspólnego ze zgłoszeniem, więc zamykam...
