### ISSUE TITLE
Signitures

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#2420]
Any thoughts about adding a way for someone to use a tablet or phone to sign off on a quote, sales order or Purchase Order?

**Comment by bpabiszczak** [comment]
You gave little information, you didn't describe how you see this process as a whole. By 'signature' do you mean a digital signature with a certificate [the system would check the certificate's validity] or do you mean a simple OK button, that would mark the document as “accepted”, or do you mean something completely different, like a handwritten signature [would the system check its validity though?]

**Comment by jbmcclain** [comment]
sorry about that.  Handwritten signature with a normal save button as in every module. My thought this would work for the work order /service order.  It also would be able to work with custom modules as well.  

To give an example for the custom module.  

So for a custom module i would have several fields that could pick for each employee on the left.  on the right side they would be able to handwrite there signature.  Once this was saved it would be in the database assigned to the project.  We would also be able to export the Log for the whole project that had all the info and signatures maybe just create a pdfs to submit to the General contractors"  So it would have the project, description, Name and hand written signature side by side.

For Quotes. would there be a way for it to be a digital signature. with an accepted button.  That way when sales sends the quote via email.  The client would open the email see the quote or open an link from the email that goes to the quote "web based"  they can read it digitaly sign it with a digital signature and press the accepted button.  There would be a notification back to the sales team that the quote has been accepted. 

Does this make since?

**Comment by bpabiszczak** [comment]
It's an interesting idea, but who is going to write it? It requires integration with devices and support for different certificates. Creating a functionality like this is very expensive and we'd only realize it if there was a client who wanted to pay for it. We're not planning to add such a functionality in 2016.
