### ISSUE TITLE
[bug] - pdf templates

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2421]
version 2.3.547

![image](https://cloud.githubusercontent.com/assets/11491482/11727873/d577c918-9f86-11e5-92ce-f3b4d4d1c4a4.png)

**Comment by florek41** [comment]
This is old PDF module, new module is in the admin panel.

**Comment by reeid** [comment]
PDF templater is still very poor in functions. Is there any plan to improve it to be close to PDF Maker (Vtiger)?

**Comment by bpabiszczak** [comment]
@reeid https://github.com/YetiForceCompany/YetiForceCRM/issues/2452
