### ISSUE TITLE
[bug] - new module of quote - wrong margin calculation

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2422]
version 2.3.547
![image](https://cloud.githubusercontent.com/assets/11491482/11728744/da4989ae-9f8b-11e5-97e6-e14b6c69122f.png)

**Comment by rskrzypczak** [comment]
The marigin is calculated on the basis of the "price after discount" field, among others;  if you add it the margin should be calculated properly.
