### ISSUE TITLE
[bug] - new module of quote - set status button - bad appearance

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2423]
version 2.3.547
![image](https://cloud.githubusercontent.com/assets/11491482/11728852/7b20bcc6-9f8c-11e5-8af5-96b4e8fda290.png)

**Comment by florek41** [comment]
maybe collapse address fields into **primary address**, **secondary address** and so on ?

**Comment by bpabiszczak** [comment]
Please check the latest versions.
