### ISSUE TITLE
[bug] - new module of quote - set status button - deleting product details

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2424]
![animation 0](https://cloud.githubusercontent.com/assets/11491482/11729181/35abbc52-9f8e-11e5-8189-1f2ee5f27017.gif)

**Comment by witer30** [comment]
It is bug, sorry...

**Comment by rskrzypczak** [comment]
I can't see the issues you mentioned. It has most likely been already fixed.
![ofer](https://cloud.githubusercontent.com/assets/10221999/13172918/f24a4754-d6fa-11e5-8548-2ba3a608135c.gif)
