### ISSUE TITLE
[bug] - new module of quote - missing button of Generate sales order

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2425]
version 2.3.547

![image](https://cloud.githubusercontent.com/assets/11491482/11729282/d1bb56a2-9f8e-11e5-9783-222afa131506.png)

**Comment by witer30** [comment]
Myślę że to błąd bo jak wygenerować zamówienie z oferty bez tego buttonu?

**Comment by florek41** [comment]
Jeśli się nie mylę to po to został stworzony panel mapowania pól - https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95 - żeby można było taką funkcjonalność dodać.

Pytanie do drużyny YF - czy zamierzacie dodać standardowe (domyślne) mapowania do systemu ?

**Comment by bpabiszczak** [comment]
Oczywiście że tak. Domyślnie będzie zaszyta ciągłość procesu.
