### ISSUE TITLE
[improvement] - workflow - multiple selection of email receivers 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2427]
version 2.3.547
There is possibility to choose only single receiver of email generated via workflow. Multile selection would be ideal and will give more benefits for this part of the CRM...

![image](https://cloud.githubusercontent.com/assets/11491482/11729573/3df13264-9f90-11e5-8e6d-36846c0ab53a.png)

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
