### ISSUE TITLE
[Bug] Break while saving Lead - Prospect Obtained

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2428]
Trying to save a Lead I got the following error:

Database ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'

Query: SELECT company,phone,lastname,email, leadid AS id FROM vtiger_leaddetails WHERE leadid IN (?)
Params: 11088
#0  PearDatabase->checkError() called at [/public_html/yeti/include/database/PearDatabase.php:354]
#1  PearDatabase->pquery() called at [/public_html/yeti/vtlib/Vtiger/Functions.php:448]
#2  Vtiger_Functions::computeCRMRecordLabels() called at [/public_html/yeti/modules/Vtiger/handlers/RecordLabelUpdater.php:20]
#3  Vtiger_RecordLabelUpdater_Handler->handleEvent() called at [/public_html/yeti/include/events/VTEventTrigger.inc:158]
#4  VTEventTrigger->trigger() called at [/public_html/yeti/include/events/VTEventsManager.inc:125]
#5  VTEventsManager->triggerEvent() called at [//public_html/yeti/include/CRMEntity.php:836]
#6  CRMEntity->save() called at [/public_html/yeti/modules/Vtiger/models/Module.php:169]
#7  Vtiger_Module_Model->saveRecord() called at [/public_html/yeti/modules/Vtiger/models/Record.php:260]
#8  Vtiger_Record_Model->save() called at [/public_html/yeti/modules/Vtiger/actions/Save.php:49]
#9  Vtiger_Save_Action->saveRecord() called at [/public_html/yeti/modules/Vtiger/actions/Save.php:26]
#10 Vtiger_Save_Action->process() called at [/public_html/yeti/include/main/WebUI.php:220]
#11 Vtiger_WebUI->process() called at [/public_html/yeti/index.php:25]

Here's the log:

Thu Dec 10 17:11:20 2015,051 [61789] INFO DB - DB ->Query: SELECT * FROM com_vtiger_workflowtasks
							INNER JOIN com_vtiger_workflowtask_queue
							ON com_vtiger_workflowtasks.task_id= com_vtiger_workflowtask_queue.task_id
							WHERE workflow_id=? AND entity_id=?
Thu Dec 10 17:11:20 2015,051 [61789] INFO DB - DB ->Query parameters: [51,11298]
Thu Dec 10 17:11:20 2015,178 [61789] INFO DB - DB ->Query: SELECT company,phone,lastname,email, leadid AS id FROM vtiger_leaddetails WHERE leadid IN (?)
Thu Dec 10 17:11:20 2015,178 [61789] INFO DB - DB ->Query parameters: [11298]
Thu Dec 10 17:11:20 2015,179 [61789] ERROR DB - DB ->Query Failed: SELECT company,phone,lastname,email, leadid AS id FROM vtiger_leaddetails WHERE leadid IN (?) | Unknown column 'phone' in 'field list' | SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'(/yeti/vtlib/Vtiger/Functions.php : 448)
Thu Dec 10 17:11:23 2015,769 [62151] DEBUG user - Entering Users() method ...

**Comment by bpabiszczak** [comment]
Does the problem exist on the dev and test versions? What is your YF ver?

**Comment by mykljohn** [comment]
I found this problem.  you can't add the Lead Phone Number into the Search Display list because the Phone Number is stored in vtiger_leadscf.

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/33413d031b942aa999c90094b7989fc083a5ce23
https://github.com/YetiForceCompany/YetiForceCRM/commit/bc030e42fda2a36e76e00fcee67ee7c282a09cfe
https://github.com/YetiForceCompany/YetiForceCRM/commit/f1fd20575f443561eb5aa22f6c6204c7547eabf8
