### ISSUE TITLE
[BUG LANG] Credits

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2429]
Why Home?
![animation 168](https://cloud.githubusercontent.com/assets/1402355/11735238/d61fbf7e-9fe0-11e5-8eb9-32d400a32b88.gif)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/9702e971254fe4955275a9ff0e78080a36b8e2ac
