### ISSUE TITLE
[BUG LANG] HelpInfo

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2430]
What is this file and what unit he belongs? Do I need all this translation?
![animation 169](https://cloud.githubusercontent.com/assets/1402355/11735293/61a849d0-9fe1-11e5-82eb-839b25a70781.gif)

**Comment by rskrzypczak** [comment]
HelpInfo is a file that contains the help icon labels. To modify its contents you can use a separate tab - "Help icons"
