### ISSUE TITLE
[bug] - calendar - linking to process not working by field clicking 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2432]
![animation 2](https://cloud.githubusercontent.com/assets/11491482/11738995/2a5f4864-9fe8-11e5-8601-eb81541ecfda.gif)

**Comment by bpabiszczak** [comment]
Widać na filmie [choć słabo nagrany], że masz tam jakiś błąd w JS. Proszę, abyś zaczął podawać pełne informacje o YF [wersja, czy problem jest na wersji test/developer, co pokazują logi itd.]. Problem [o ile istnieje] zostanie rozwiązany razem z tym zgłoszeniem: https://github.com/YetiForceCompany/YetiForceCRM/issues/2453

**Comment by rskrzypczak** [comment]
At the moment reference fields are not available in quick edition.
