### ISSUE TITLE
Design Bug Home Page Widgets

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2434]
iPad mini safari browser ![image](https://cloud.githubusercontent.com/assets/6897502/11740047/9bbc7ef4-9ff8-11e5-9d46-19ac610d260c.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/70f8138217903e4d3b4e6909b535c779511336fe
