### ISSUE TITLE
[Bug] - Email template - document module assined 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2435]
why document module is assined to email templates
![image](https://cloud.githubusercontent.com/assets/11491482/11740331/0f4535ac-9ff2-11e5-920b-1119f4014b77.png)

**Comment by mariuszkrzaczkowski** [comment]
The documents module is related to the mail templates in order for the mail client to automatically attach a document to a mail, while selecting a template.
