### ISSUE TITLE
[bug] settings menu

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2447]
System settings menu is not working very well with Firefox and MS Edge

![menu](https://cloud.githubusercontent.com/assets/10330264/11761866/e8928528-a0db-11e5-907f-0799f4a762d6.gif)

**Comment by nikdejan** [comment]
Isn't this a duplicate #2294?

**Comment by kpaulaha** [comment]
Ok, had missed that.


-------- Alkuperäinen viesti --------
Lähettäjä: nikdejan <notifications@github.com> 
Päivämäärä: 12.12.2015  22.09  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] [bug] settings menu (#2447) 

Isn't this a duplicate #2294?

**Comment by florek41** [comment]
It's the same but still we don't have solution for Firefox etc.

**Comment by kpaulaha** [comment]
Ok, then it is Chrome.


-------- Alkuperäinen viesti --------
Lähettäjä: Bartek Florczak <notifications@github.com> 
Päivämäärä: 13.12.2015  0.05  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] [bug] settings menu (#2447) 

It's the same but still we don't have solution for Firefox etc.
