### ISSUE TITLE
[question] - update to version 2.3.697

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2450]
After update a chat stop working and discover that there are errors
![image](https://cloud.githubusercontent.com/assets/11491482/11764904/cf651936-a143-11e5-8238-ed1f5305a3fe.png)

what can be responsible for such errors?
Checked everything and no error in log are presented, 
Files are present on the server... 
any idea why my chat looks like below?
![image](https://cloud.githubusercontent.com/assets/11491482/11764912/39733c5e-a144-11e5-9e2e-869a80f9bc7f.png)

**Comment by TomaszQr** [comment]
Fix https://github.com/YetiForceCompany/YetiForceCRM/commit/8a45a89875c0ab09df4e3c078df6b8a678a5bb11
