### ISSUE TITLE
[bug] - Upgrade to version 2.3.697 - menu issue

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2451]
the menu hovering doesnt work for user, for admin works perfectly... 
user:
![image](https://cloud.githubusercontent.com/assets/11491482/11764922/8d5e9714-a144-11e5-8529-afd809b74cf5.png)
admin:
![image](https://cloud.githubusercontent.com/assets/11491482/11764976/408b40a6-a147-11e5-954f-bcdccec05d40.png)

**Comment by rskrzypczak** [comment]
try this
![leftpanel](https://cloud.githubusercontent.com/assets/10221999/11769785/a0353bbc-a1ef-11e5-9cce-15529b9e2886.jpg)

**Comment by witer30** [comment]
Please reopen as this is not solution...
![image](https://cloud.githubusercontent.com/assets/11491482/11804440/15945068-a304-11e5-8c99-65a1f894decc.png)
the funny is when seting up one user who is admin this menu hovering works only if user is entering into Uprawnienia-Użytkownik, see below
![image](https://cloud.githubusercontent.com/assets/11491482/11804480/6f91b2ae-a304-11e5-8915-4ab33676554b.png)

**Comment by witer30** [comment]
Ok problem resolve itself, do not know what was reason of such behaviour...
thanks and sorry for the problem
