### ISSUE TITLE
[BUG] Calendar - after change status of event system shows quick create for new calendar event

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2454]
Is this correct ?
What is this for ?

![calendar_quick-create-calendar](https://cloud.githubusercontent.com/assets/4824588/11767165/8b6d3f2c-a1a4-11e5-9eaf-176b00244c51.gif)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2242
