### ISSUE TITLE
[Question / Improvement] Webform / Custome Entry Screen

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2455]
Is it possible to put a webform on the Menu (in YetiForce), or create a custom entry screen for a module?  We want to create a separate Leads entry screen for some users with different Labels and additional text descriptions.

**Comment by paula-w** [comment]
Could you describe your idea in some detail?  Like what and where should be different.

**Comment by mykljohn** [comment]
Hi paula, I want to create a custom entry screen, like a webform, connected to the Leads table, but I want to put it on the YF menu.  It would just be to entry an Assessment for a Lead (Prospective Student) which would be stored in Description. (or Comments).
We want to do the same for Contacts so that our teachers can enter comments.   

I've already created the Webform to do this, but I can't put it on the menu.

**Comment by florek41** [comment]
Maybe you can create form in plain HTML and put there form generated with this tool: https://gitdeveloper.yetiforce.com/index.php?module=Webforms&parent=Settings&view=List&block=5&fieldid=31

And in menu insert link to this html file.
is this what you looking for ?

Or you want have a form directly in menu (fields in menu) ?

**Comment by mykljohn** [comment]
Yes, that's what I did, but I was hoping to just add it to the YF menu...no go.  not sure why.

**Comment by florek41** [comment]
how did you put it to the menu ?

**Comment by mykljohn** [comment]
I added a menu item as a shortcut to the Post Url
	http://www/yeti_test/modules/Webforms/capture.php

**Comment by paula-w** [comment]
The menu can redirect to just about any place on the Internet. If it's supposed to redirect the user to a specific form in the system, then a proper module must be created.
Is that what you meant?

**Comment by mykljohn** [comment]
No, I created a webform which I wanted to place on the Yetiforce menu.

**Comment by bpabiszczak** [comment]
The menu wasn't designed to add any forms in there... so we can't really help you. You're trying to do something “weird” so you will have to deal with it on your own.

**Comment by mykljohn** [comment]
I like that..."weird" :)  Is there any way to customize a module to reduce the fields visible for a given user?  I think I can block all the fields that I don't want them to see, but that seems like a complicated way to do it when I can just create a webform....I'll have to put the webform in a different location, not on the menu.

**Comment by florek41** [comment]
If you really want to put form in menu you have to edit this part of the layout.

Check the permissions and roles for disable/hide fields for group of users.
