### ISSUE TITLE
[Bug/Improvemenet] Roundcube - No. of unread messages in page title

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2456]
Normally, stand alone Roundcube displays number of unread email messages in page title. Unfortunately, in YetiForce title is My mailbox, and nothing can change it. 
Please fix this. It is very important to be able to see when new email arrives while you are working in some other tab.

**Comment by nikdejan** [comment]
I found a solution that works for me.
In /modules/OSSMail/roundcube/program/js/app.js, after line 6438 ( document.title = title; ) add this line:
parent.document.title = title;
I'm not closing this because YetiForce team might want to find some better solution, which does not hack the Roundcube core.

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
