### ISSUE TITLE
Important changes in the system, version 2.4 [2016-03-07]

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#2461]
Version 2.4 will bring a vast number of changes. Some of them will strongly affect the processes in the system, therefore it's important for you to read the description a month prior to the release of the new version. Below we present some key information for the implementation:

__New changes:__

1. Version 2.4 is postponed until 2016.01.11 >> [2016-03-07].
2. The logic of building prefixes for documents will be changed, the new version can be already tested in the developer version.
3. New modules, related to the sales process, will be added [during these next few weeks we will improve then and add functionalities; at the moment we have a general general outline, the process will appear soon].
4. A new PDF module will be added [you can already test it and report issues].
5. A new [responsive] layout will be added [you can already test it and report issues].
6. The naming of modules in configuration will be changed [first changes have already been uploaded].
7. New modules with products will be added [they can already be tested from the field management level] .
8. And thousands of minor changes, that will be announced in the notice.

__Critical changes:__

For many people these changes might seems confusing, but they are part of long-term changes planning in the system, and substituting the “old” solutions with “new” ones. First of all, we are forced to replace the old modules with products with the new modules. We not able to support two very different processes and develop them in many ways, as far as time is concerned. Remember, it's us who has to deal with most of the “problems” when it comes to huge changes like these, and we certainly don't do that because we are bored, but because we want this system to become the best open system in the word in a few months, which requires introducing a lot of changes, that sometimes might be perceived as radical.

1. We remove all the old sales modules:
●Opportunity
●Quote enquiries
●Requirement cards
●Calculations
●Quotes
●Sales order / PO
●Sales invoice
●Cost invoice

2. We remove all the elements related to the old modules [widgets, configuration, templates etc.].
3. We remove the old PDF module.

4. We remove the old layout.

The old modules won't work in the new version. That's why we will prepare a migrating script [after releasing YetiForce 2.4 RC – 2016-01-11] from the old modules to the new ones. The script will be free, you will also be able to purchase our support for a small amount of money in case you have problems migrating the data, or you experience some non-standard problems.

__Changes for version 2.5__

Version 2.5 will bring many optimizations for some other processes [Marketing, Realization, Support, Logistics, Bookkeeping]

**Comment by eptapsyxos** [comment]
Thank you very much for your informations.

Question: the new modules will have widgets? (i mean the whole widget mechanism to add widgets from admin panel)

**Comment by bpabiszczak** [comment]
Yes

**Comment by waran70** [comment]
Noticed that invoice module gone (dev ver). Can not get from this announcement - will it get back or what?

**Comment by zimart** [comment]
I jakieś widoki ? :)

**Comment by florek41** [comment]
z tego co widać (https://github.com/YetiForceCompany/YetiForceCRM/commits/developer) praca wre, ale wgląda na to, że będzie trzeba poczekać - https://github.com/YetiForceCompany/YetiForceCRM/milestones - Due by February 1, 2016 - wg. mnie nie ma co się spieszyć - lepiej przetestować jak najwięcej, żeby nie było rozczarowania ;)

[EN]
as you can see (https://github.com/YetiForceCompany/YetiForceCRM/commits/developer) YF team working hard, but i think we have to wait - https://github.com/YetiForceCompany/YetiForceCRM/milestones - Due by February 1, 2016 - for me there is no need to hurry - it is better to test as much as possible, so there will be no disappointment ;)

**Comment by bpabiszczak** [comment]
Testować, nie marudzić :P Na wersje końcową jeszcze przyjdzie poczekać do końca miesiąca...

**Comment by nikdejan** [comment]
Now when yeties came back home from skiing, development will probably go bit faster ;-)
Teraz, gdy yeties wrócił do domu od narciarstwa, rozwój będzie prawdopodobnie iść nieco szybciej;-)
![yeti-marble-mountain](https://cloud.githubusercontent.com/assets/13381850/12248571/9ace0b68-b8ba-11e5-8476-28471867c2d9.jpg)

**Comment by bpabiszczak** [comment]
heheh

**Comment by nikdejan** [comment]
I know that skiing is very popular in Poland :-)

**Comment by zimart** [comment]
Testuje... co chwila.. niestety nic się nie zmienia w tematach akurat potrzebnych mi :) - czyli oferty - zamówienia...
Z podatkami.. hmm - pasuje dorobić kolumnę procentowego VATU, brak możliwości wygenerowania zamówienia z oferty... :( , no i PDF... brak podsumowań w stylu : razem netto, razem rabat... razem do zapłaty... jaki VAT... oprócz braku możliwości tak naprawdę wyłączenia kolumn ( jak było w PDF do Vtigera...)  , no chyba ze zrobimy to na piechotkę..., czli pokazujemy listę z konkretnymi kolumnami.. a nie z widoku modułu..:( Ja więcej nie chcę :)

**Comment by bpabiszczak** [comment]
Podsumowanie podatków, rabatów itd. to jest. I jest obsługiwane przez PDF. Należy podsumowanie włączyć w module. Moduły finansowe będą dodawane w następnym tygodniu.

**Comment by florek41** [comment]
Możesz uchylić rąbka tajemnicy - czego możemy spodziewać się w modułach finansowych i czy będą jeszcze jakieś zmiany w samym procesie sprzedaży/jego modułach ?

**Comment by bpabiszczak** [comment]
Będzie do końca miesiąca cały proces finansowy [wersja podstawowa czyli np. faktury krajowe, faktury zagraniczne, korekty, proformy, i pewnie noty] a do tego moduł magazynowy [pz, wz, mm, rw, r, wielomagazynowość]. 

Proces sprzedażowy na pewno będzie dopieszczany przez najbliższe 2-3 tygodnie, bo obecna wersja jest jeszcze wersją roboczą.

**Comment by zimart** [comment]
OJ.. chyba nie doczekam się niczego stabilnego w miarę :)

**Comment by bpabiszczak** [comment]
Myśl pozytywnie :]

**Comment by eptapsyxos** [comment]
From november milstone to 11 january then 1 february.all milstones lost.or the milestones are not s.m.a.r.t either the team has not a good manager. A great example that great programming skills is not enough to create a product.good luck

**Comment by eptapsyxos** [comment]
![smartgoals](https://cloud.githubusercontent.com/assets/6897502/12727484/fc235e88-c925-11e5-9492-165b04d69f26.png)

**Comment by bpabiszczak** [comment]
You're trying very hard to make us ignore you for a couple of months. The deadlines are loose... if someone can't deal with that, then it's only his own problem. We don't really need any useless spam.

**Comment by zimart** [comment]
A mi trzeba tak niewiele do szczęścia:) Mam wrażenie ,że wersji oznaczonej jako stabilna nie zobaczę na oczy :)

**Comment by bpabiszczak** [comment]
Nie lepiej wziąć się do pracy i nam pomóc, niż pisać kilkukrotnie o tym, że wersja stabilna się nie pojawi...
