### ISSUE TITLE
[PL][BUG] Kalendarz - wyświetlanie zakończonych elementów jako zaplanowane

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2466]
Przy dodawaniu rekordu do kalendarza pojawiają się nam zadania dodane wcześniej, które są zaplanowane na ten sam dzień, ale wyświetlają się tam również el. wykonane.
Np:

![calendar-closed-tasks](https://cloud.githubusercontent.com/assets/4824588/11824881/6bf7c0c0-a37c-11e5-8292-b357c0cc45f3.jpg)

**Comment by bpabiszczak** [comment]
Chyba nie rozumiem, co jest problemem. Chodzi o to, że tam powinny się pojawiać tylko elementy "otwarte"?

**Comment by florek41** [comment]
Wg. mnie tak. Skoro to podpowiedź na temat elementów które mamy wykonać tego dnia to po do tam rzeczy, które zostały zamknięte ?
