### ISSUE TITLE
[PL][Design bug] Zbędny pasek przewijania w szybkim tworzeniu - Kalendarz

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2467]
![calendar-scrollbar](https://cloud.githubusercontent.com/assets/4824588/11824944/c6c7f844-a37c-11e5-84f6-48c2e3361d36.jpg)

Nie służy do niczego.

**Comment by bpabiszczak** [comment]
U mnie się nie pojawia [aktualna wersja dev], może zależy od rozdzielczości ekranu... więcej informacji potrzeba...

**Comment by florek41** [comment]
Zarówno w Firefox jak i w Chrome.
Rozdzielczość 1280x1024

**Comment by bpabiszczak** [comment]
to takie rozdzielczości jeszcze istnieją ;P? Pewnie problem nie jest w rozdzielczości, tylko w tym, że u Ciebie są już zaplanowane terminy i może to one "rozszerzają" obszar...

**Comment by florek41** [comment]
O dziwo u mnie nawet w ilości 2 sztuk i mają się nieźle - do internetu więcej nie jest potrzebne ;)
