### ISSUE TITLE
[PL] Integracja CalDav <-> IOS

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2469]
Kolejny raz testuję integrację kalendarza YF z IOS.
w IOS mamy 2 oddzielne aplikacja - jedna to kalendarz - do niego synchronizują się Terminy, oraz Przypomnienia (forma listy do odhaczania) gdzie widoczne są Zadania. Nie do końca mi pasuje to rozwiązanie bo wolałbym całość w jednym miejcu, ale to nie istotne na chwię obecną

Tym razem scenariusz wygląda następująco:
- Wpisanie do IOS danych autoryzacyjnych wg. standardowego schematu (gitdeveloper.yetiforce.com/api/dav.php) nic nie uruchamia - w kalendarzu brak nowych kalendarzy, w przypomnieniach tak samo.

- zmiana adresu api na gitdeveloper.yetiforce.com/api/dav.php/principals/demo (wyczytałem, że to znany bug SabreDav) spowodowała pojawienie się kalendarza oraz listy zadań. Zsynchronizowały się Zadania (można zobaczyć te wykonane), w kalendarzu też wygląda OK.

- Testowa zmiana daty terminu z poziomu YF i część stanęła - koniec z uaktualnieniem kalendarza.

- Po usunięciu synchronizacji i wpisów i po ponownym uruchomieniu w YF widoczne są 4 terminy - w IOS 2. Po dodaniu z poziomu IOS termin jest widoczny w YF, odwrotnie - wybiórczo.

- W IOS nie jest widoczny wpis wcześniej dodany z jego poziomu (przed usunięciem synchro)

- Zmiany wprowadzone w IOS są widoczne w YF

- W zadaniach sprawa wygląda tak, że po oznaczeniu w IOS jako wykonane w YF tworzony jest duplikat zadania z takimi samymi danymi - różni się status - tym sposobem mamy 2 zadania - jedno zrobione, drugie nie.
Kolejna sprawa to po usunięciu i utworzeniu synchronizacji na nowo oba zadania są jako niewykonane, mimo, że w YF jedno jest wykonane drugie nie.

- Element który w YF ma status `zaległe` w IOS widoczny jest jako anulowany (wyświetlony jako przekreślony i nieistotny)

Ciężko jest mi znaleźć jakąś konkretną przyczynę i jakąś stałą lub zmienną którą spowodowane jest to zachowanie.
Jeśli mogę coś więcej pomóc / przetestować to czekam na informację.

**Comment by bpabiszczak** [comment]
Jeżeli możesz, to sprawdź jeszcze na jakimś androidzie. Sprawdzaliśmy już problem z iOS, problem w tym, że nigdzie nie widać co jest problemem.... sprawdzaliśmy nawet na czystym sabre [główny silnik DAV] i problem jest ten sam :/ Będziemy szukać.

**Comment by florek41** [comment]
Na chwilę obecną jedyne co mam to IOS, ale postaram się dorwać coś z androidem i sprawdzę. Jedyne co mnie martwi to to, że potrzebuję DavDroid (niby GPL, ale kompilować trzeba i boję się, że to pochłonie mi trochę czasu) - chyba, że jest szansa na udostępnienie skompilowanej apk ? ;)

**Comment by mariuszkrzaczkowski** [comment]
Możesz zainstalować aplikację F-Droid i tam masz do pobrania już skompilowaną aplikację DAVdroid i zawsze najnowszą wersję. A jak nie chcesz instalować zbędnych aplikacji to wystarczy pobrać gotową aplikacje z https://f-droid.org/repository/browse/?fdfilter=dav&fdid=at.bitfire.davdroid

**Comment by florek41** [comment]
Dzięki ! :)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2252
