### ISSUE TITLE
Bug Mobile comments date and hour meshed up

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2472]
![s51216-112202](https://cloud.githubusercontent.com/assets/6897502/11837091/6f9b898a-a3e7-11e5-9e4a-37c9d5d159f9.jpg)

**Comment by TomaszQr** [comment]
Fix https://github.com/YetiForceCompany/YetiForceCRM/commit/3331045d0ce0e4709e5197f155968457e6e61f43
