### ISSUE TITLE
Wersja stabilna 

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2475]
Witam. Jakie są prognozy na wersję stabilną ? :) Czy layout normalny bedzie dostepny w wersji powiedzmy 2.4 ? Cyz juz tylko nowy panel ?

**Comment by florek41** [comment]
#2461 o !
Jeśli masz problem z angielskim - daj znać.

**Comment by zimart** [comment]
Kolego... Nie badź taki do przodu...z tego co czytam twoje posty to też masz spore problemy - np z szukaniem (https://github.com/YetiForceCompany/YetiForceCRM/issues/2454). Twoja odpowiedź nic tu nie wniosła...  O ile wiem nie jest problemem zgłaszanie bugów i zapytań po polsku... zresztą możesz sobie to znaleźć...w odpowiedziach na Pana Błażeja  - ponieważ jesteś pewnie biegły w wielu tematach - ale proszę - zawsze możesz przetłumaczyć ...i dodać tłumaczenie dla mniej biegłych.  Dzięki za linka - proponuję zamknąć.

**Comment by bpabiszczak** [comment]
Chyba źle go zrozumiałeś. On Tobie ładnie napisał, że tam jest odpowiedź [przy czym odpowiedź jest po EN i jak nie znasz EN to pomoże Ci i przetłumaczy] a więc nie było w jego wypowiedzi nic złośliwego.... przeczytaj jego post kilka razy :]

**Comment by zimart** [comment]
:) Z całym szacunkiem - trochę złośliwości w tym poście jest :) w kwestii wersji "stabilnej" - po prostu nie moge sie doczekać.. a mimo wszytko kilku rzeczy jeszcze brakuje - powiem wiecej ze kilka spraw teraz sie skomplikowało - liczyłem na te powiedzmy 14 dni :) jak było prognozowane w poście z 13 listopada.

**Comment by bpabiszczak** [comment]
Ja na prawdę nie widze nic złośliwego, wręcz przeciwnie. 
Ten post do którego linkuje odpowiada na wszystkie zadane pytania.

**Comment by florek41** [comment]
Przykro mi, że tak to odebrałeś - tak jak mówi Błażej - chciałem pomóc a Ty opacznie to zrozumiałeś i niepotrzebnie się nakręciłeś :)

**Comment by zimart** [comment]
:) może - w takim razie... zwracam honor. Pozdrawiam.

**Comment by bpabiszczak** [comment]
i tak jak pisałeś, wole posty w języku polskim niż angielskim, a po drugie żaden ze mnie Pan :]
