### ISSUE TITLE
Please do not remove Opportunities yet

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2476]
Please do not remove Opportunities until the last moment, when you create Opportunities->Sales Processes migration tool. 
I'm using Opportunities in dev version and I need to be able to further upgrade, in order to apply bug fixes.

**Comment by eptapsyxos** [comment]
From what module the opportunities will be replaced?and how will interact with the other modules?

**Comment by nikdejan** [comment]
Well, afaik the plan was to replace opportunities with sales processes. sp will interact with new s modules.

**Comment by bpabiszczak** [comment]
So wait for the script... https://github.com/YetiForceCompany/YetiForceCRM/issues/2461
