### ISSUE TITLE
Timeline JS3

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2477]
Timeline JS3 are "beautifully crafted timelines that are easy and intuitive to use". They are beautiful indeed but implementing them on comments history looks like a huge waste of time to me.
Or am I missing something? Are they going to be implemented elsewhere?

**Comment by eptapsyxos** [comment]
I agree that is not that necessary.i believe that this little graphical addition must be implement after more core functions.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/config.template.php

// default view in Comments (Timeline/List)
$defaultViewInComments = 'Timeline';
