### ISSUE TITLE
[BUG] - Bind Vendors missing

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2478]
In MailScanner configuration, in Email Actions there are Relate to HelpDesk, Potentials, Accounts, Projects etc. but there is no Relate to Vendors option. This is a bug, because in the tab General Configuration, under Search email configuration (Choose fields that will be used to search for recipient of email message) there is, among others, Vendors - Primary Email. It's obvious that bind vendors was planned but it's missing.
And since January 11th is not so far away, maybe it is time for Bind Sales Processes too :-)

**Comment by bpabiszczak** [comment]
1. This week we will improve relations to mails, as well as scanner actions.
2. Version 2.4 will be postponed by a month. We're adding some missing modules related to finances [invoices] and logistics.
