### ISSUE TITLE
[PL][BUG] Timeline w komentarzach - wolne ładowanie 

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2479]
Nad wyższością osi czasu czy jej brakiem nie mamy co dyskutować, skoro jest i w razie potrzeby można wyłączyć ( #2477 ) :)
Niestety przy ilości komentarzy większej niż 1 całość ładuje się niesamowicie wolno powodując zawieszanie się przeglądarki.
Po dodaniu drugiego komentarza czekałem ~3min. na wczytanie, ale nie wytrzymałem i wyłączyłem przeglądarkę (nie można zrobić nic innego). Tak samo wygląda sprawa kiedy komentarze już są dodane i wejdziemy w zakładkę żeby je wyświetlić.

Moja konfiguracja jest zdecydowanie lepsza niż przeciętny komputer biurowy:
i5, 8gb ram, SSD
Testowane na przeglądarce Firefox, tylko jedna, aktywna karta otwarta, w tle nic innego.

![comments_freez](https://cloud.githubusercontent.com/assets/4824588/11856059/6a1df58a-a44e-11e5-8393-576cb366d880.gif)
(film się nie zawiesza)

**Comment by bpabiszczak** [comment]
właśnie na DEV dodałem 25 komentarzy, chodzi jak burza :/

**Comment by bpabiszczak** [comment]
i to nie jest kwestia wolnego ładowania, Tobie się nie ładuje... czyli masz jakiś błąd JS zapewne.
