### ISSUE TITLE
Browser tab name

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2481]
Where can i change what is displayed on browser tab ? I really need to change it.
![tab](https://cloud.githubusercontent.com/assets/16100495/11866891/b3a93668-a4a5-11e5-94d2-20efb6c0362a.png)

**Comment by nikdejan** [comment]
@yozhi stop trolling.

**Comment by bpabiszczak** [comment]
@nikdejan 
Why he trolling?

**Comment by yozhi** [comment]
yes why im trolling ?

**Comment by nikdejan** [comment]
Well, sorry, maybe I'm wrong. But it seams to me that he asks questions that are two generic and not specifically related to yetiforce.

**Comment by yozhi** [comment]
if its generic questions , you can tell me how fix this.

**Comment by nikdejan** [comment]
OK. I am looking for a solution and I am going to share it here :-)

**Comment by yozhi** [comment]
ok thank you very much :)

**Comment by nikdejan** [comment]
Please tell me what exactly are you trying to do? Do you want to make changes in one module only, or throughout whole crm? 
There is a file /layouts/basic/Vtiger/Header.tpl which outputs page title on line 16:
<title>{vtranslate($PAGETITLE, $QUALIFIED_MODULE)}</title>
You could start from there.

**Comment by yozhi** [comment]
i already tried changing it , but nothing happens

**Comment by nikdejan** [comment]
Which version are you using? 
Why didn't you answer to my questions? What exactly are you trying to achieve?
How did you change it?
I can not replicate what you are talking about. When I change that line, page title normally changes.
That is why I (sometimes) think you are a troll ;-)

**Comment by yozhi** [comment]
I'm using 2.3.575 developer version.
im trying to change the name of page title for each module, because some modules have wrong names on page title, and most of them and i think this happens only with modules , that are not default modules, you know what i mean

**Comment by yozhi** [comment]
i think i fixed it , and don't know how i fixed , but i fixed , i changed many thing here and worked

**Comment by nikdejan** [comment]
:-))) I'm glad you did it.

**Comment by bpabiszczak** [comment]
You gotta be really careful when modifying the system. If something isn't working, then you shouldn't fix it yourself [unless you're certain what you're doing], instead, you should propose a change to the system via github, and if it's correct we will upload it. Every time you update your system your changes will either be overwritten or may cause the system to malfunction, but who will help you then?

I'm closing the issue because I see that problem has been [theoretically] solved.

**Comment by yozhi** [comment]
everytime i change a thing i save a backup with date and hours i modified a significant thing in system, so if something gone wrong i can back to when system was good :)

**Comment by yozhi** [comment]
i have a insignificant question to make you, can i make it here ?

**Comment by yozhi** [comment]
i have a insignificant question , that i think  it's desnecessary to open a new issue, and my question is, how can i update from developer ver.2.3.575 to ver.2.3.697? i can't found it on update packages.

**Comment by waw555** [comment]
And in the language file did not try to change it? Why change the code in the system?

**Comment by yozhi** [comment]
i don't know why , but didn't result, was the first thing i tried. but now its fixed
