### ISSUE TITLE
[PL][BUG] Próba wygenerowania PDF bez zaznaczonego rekordu

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2483]
Stworzyłem szablon PDF z wybranym przeze mnie warunkiem (Project type = internal). Wyświetlając listę rekordów widoczny jest button generowania PDF nawet kiedy żaden rekord nie został zaznaczony.
Po kliknięciu jest możliwośc wyboru szablony i wygenerowania rekordu. Kończy się to fiaskiem:

```
#0 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/utils/CommonUtils.php(402): Vtiger_Deprecated::checkFileAccessForInclusion('modules/Groups/...')
#1 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/CRMEntity.php(62): checkFileAccessForInclusion('modules/Groups/...')
#2 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/vtlib/Vtiger/Functions.php(460): CRMEntity::getInstance('Groups')
#3 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/vtlib/Vtiger/Functions.php(362): Vtiger_Functions::computeCRMRecordLabels('Groups', Array)
#4 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/vtlib/Vtiger/Functions.php(410): Vtiger_Functions::getCRMRecordLabels('Groups', Array)
#5 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/vtlib/Vtiger/Functions.php(393): Vtiger_Functions::getOwnerRecordLabels('')
#6 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/utils/CommonUtils.php(441): Vtiger_Functions::getOwnerRecordLabel('')
#7 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/uitypes/Owner.php(31): getOwnerName('')
#8 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/Field.php(108): Vtiger_Owner_UIType->getDisplayValue('', false, Object(Accounts_Record_Model), true)
#9 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/Record.php(226): Vtiger_Field_Model->getDisplayValue('', false, Object(Accounts_Record_Model), true)
#10 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/PDF.php(465): Vtiger_Record_Model->getDisplayValue('assigned_user_i...', 0, true)
#11 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/PDF.php(336): Vtiger_PDF_Model->replaceRelatedModuleFields('nag\xC5\x82\xC3\xB3wek', '112')
#12 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/pdfs/mPDF.php(330): Vtiger_PDF_Model->getHeader()
#13 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/PDF.php(576): Vtiger_mPDF_Pdf->export('112', 'Project', '2', '', '')
#14 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/actions/PDF.php(88): Vtiger_PDF_Model::exportToPdf('112', 'Project', '2')
#15 [internal function]: Vtiger_PDF_Action->generate(Object(Vtiger_Request))
#16 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/runtime/Controller.php(84): call_user_func_array(Array, Array)
#17 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/actions/PDF.php(32): Vtiger_Controller->invokeExposedMethod('generate', Object(Vtiger_Request))
#18 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/include/main/WebUI.php(215): Vtiger_PDF_Action->process(Object(Vtiger_Request))
#19 /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/index.php(22): Vtiger_WebUI->process(Object(Vtiger_Request))
#20 {main}
```

![pdf_unselected](https://cloud.githubusercontent.com/assets/4824588/11875387/a55c1424-a4e4-11e5-88c2-d3508ddf4a29.gif)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2484

**Comment by bpabiszczak** [comment]
Gdy nie ma zaznaczenia, to znaczy, że PDF generuje dla wszystkich rekordów z listy.

**Comment by florek41** [comment]
Dla wszystkich widocznych na danej stronie, czy ogólnie dla wszystkich, czy dla tych które są wyświetlone po przefiltrowaniu (jeśli aktywne) ?

Bardziej intuicyjne byłoby generowanie tylko po zaznaczeniu. Podobnie jak jest to np. z Masową edycją czy masowym usuwaniem.

**Comment by bpabiszczak** [comment]
Punkt widzenia zależy od punktu siedzenia :] 
O ile mi wiadomo to wszystkie w danym widoku [ze wszystkich stron]...

**Comment by florek41** [comment]
Oczywiście, ale zobacz co się dzieje - sam, jako osoba zarządzająca projektem i pracująca z systemem na co dzień, masz drobne wątpliwości jak to działa - a skąd ma to wiedzieć biedny użytkownik ? :)

Właściwie wszędzie, w każdej znanej mi aplikacji (chociażby gmail, OTRS, windows) działa to w ten sposób, że najpierw zaznaczasz a następnie wykonujesz akcję - jeśli chcesz dla wszystkich to zazaczasz wszystkie i ot co.
Szczególnie, że w YF mamy funkcję "Zaznacz wszystkie" po zaznaczeniu całej aktualnej listy.

W błąd może wprowadzać dodatkowo to, o czym mówiłem wcześniej - masowa edycja i usuwanie też działa tylko po zaznaczeniu rekordów.

**Comment by bpabiszczak** [comment]
Po to się robi szkolenia i testy aby wiedzieć jak coś działa.
Dla kogoś kto codziennie generuje PDF [np. raport czasu pracy] taka funkcjonalność oszczędza jego czas... i tak samo zostanie wprowadzone w innych elementach systemu tj. edycja masowa, wysyłka maili, smsów itd.

**Comment by florek41** [comment]
Trochę jakby uczyć jeżdżenia na rowerze z kwadratowymi kołami - oczywiście, że się da, ale wszyscy mają okrągłe ;)

Inna sprawa, że jednolitość i konsekwencja jest najważniejsza - istotne, żeby użytkowanie było intuicyjne i nie wprowadzało użytkowników w błąd.

Przyjmuję do wiadomości informację o widoczności pozostałych opcji dla zwykłych użytkowników i to dla mnie jest jakieś wytłumaczenie, chociaż nie ukrywam, że wolałbym w drugą stronę - ale nie jestem sam :)
Sprawa do przemyślenia.

**Comment by bpabiszczak** [comment]
Zgodziłbym się, gdybyśmy próbowali zmienić, czyli... A = B a B = A, my natomiast tylko dodaliśmy nową opcje. Skoro dla użytkownika to takie intuicyjne, że musi zaznaczyć za nim będzie generował, to czemu o tym zapomina i nic nie zaznacza...
