### ISSUE TITLE
[PL] Brak odświeżania listy akcji po szybkiej edycji

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2486]
Szablon PDF z warunkiem na Type = Interal
Na początku nie ma możliwości wygenerowania PDF (ze względu na inny typ), po zmianie warunków na spełnione (Type = Internal) lista akcji (górne ikony) nie zmieniają się - dopiero po odświeżeniu strony mamy możliwość wygenerowania PDF.
Moim zdaniem świetnie jeśli przycisk pojawiałby się po zapisaniu.

![pdf_refresh](https://cloud.githubusercontent.com/assets/4824588/11875679/23e1dc24-a4e6-11e5-93c0-4f8b12a15a20.gif)

**Comment by bpabiszczak** [comment]
Na chwilę obecną nie mamy czasu na tą funkcjonalność, gdy się pojawi jakiś klient, który za to zapłaci dodamy to do YetiForce. https://yetiforce.com/pl/github/issues/203-pomys%C5%82y-zwi%C4%85zane-z-rozwojem-systemu.html
