### ISSUE TITLE
[PL] Sugestia - Zmiana wielkości znaków w menu

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2487]
Jak pisałem w #2318
Może warto przemyśleć zmianę rozmiaru fontu w menu na np. 14px? Nagłówki w systemie mają max 15px a w menu mamy 16. 
Dodatkowo Interlinia, po zmianie na taką jaką mamy obecnie, jest wg mnie zbyt mała i dla lepszej czytelności większe odstępy byłyby wskazane. Ew. taką zmianę zrobić tylko na niższych - laptopowych rozdzielczości ( >1366px szerokości).

[EN]
Maybe additionally change font-size in menu to for example 14px ? All headings have max 15px but in menu we have 16px - after change to current row height for me line-height is to small, what do you think ?

edit:
Po zmianie na 14px interlinia wygląda ok :)

**Comment by reeid** [comment]
I would also amend view of horizontal menu/related tab list.
From my point of view it would looks better if all icons will be removed and each position will be highlighted with  light-grey tab (with little round corners) 
Now it seems to be too much gfx to look at,

**Comment by TomaszQr** [comment]
@reeid  The 'SHOW_RELATED_ICON' parameter is responsible for the icon's visibility on the list of related  modules. You can find this parameter in the 'config/relation.php' file.
@florek41 Sprawdź teraz czy menu jest teraz czytelniejsze.

**Comment by florek41** [comment]
Wydaje się być lepiej.
