### ISSUE TITLE
Some technical questions

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2490]
- How about migration from vtiger to new modules? Will you support it?
- will the tables naming be amended? vtiger_ prefix is awkward here 
- what about vtlib? Lib name change? Development?
- can we test portal somewhere?

**Comment by eptapsyxos** [comment]
#2461

**Comment by reeid** [comment]
@eptapsyxos  provided link don't explain any of my question.

**Comment by eptapsyxos** [comment]
@reeid  provides answer for question 1 . There will be a script for the migration.

**Comment by bpabiszczak** [comment]
Thank you @eptapsyxos
