### ISSUE TITLE
Slow working on Leads module after add 2 000 000 records

### ISSUE THREAD

**Issue by echemik** [YetiForceCompany/YetiForceCRM#2492]
Hi, I import 2 000 000 Leads to database, and page loading slowed : 
- Leads List View - over 40 sec.
- Lead Detail View - 7 sec.

- Account List View - 1 sec. (ok)
- Account Detail View - 1 sec. (ok)

Where can be a problem, its normal?, Do you guys test it on this part of records? Is any resolution?
Where I can track slow database Queries?

Thanks for help.

**Comment by bpabiszczak** [comment]
1. Jak umiemy to piszemy po polsku, szkoda naszego czasu na tłumaczenie. 
2. Debugowanie wolnych zapytań włącza się na poziomie mysql http://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html
3. Debugowanie YF włącza się w pliku: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/109-debugowanie.html
4. Za rejestrowanie wolnych zapytań w sql odpowiada pierwszy parametr w tym pliku: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/performance.php
5. Zerknij sobie tutaj: http://speed.yetiforce.com/yeti/ [admin/admin] tam jest wygenerowanych 1.1M kontrahentów + 0.6M kontaktów + 0.1M Leadów... ładowanie strony trwa 0.5s. 

Problem u was może wynikać z dwóch czynników:
a). Macie słaby niedostosowany sprzęt.
b). Sortujecie wyniki przed ich wyświetleniem.

**Comment by echemik** [comment]
Dzięki za info, sprawdzę i dam znać.

Doceniam wygodę pisania po polsku, ale mam obawy czy nie niszczymy tym społeczności. Dla ludzi z zagranicy moje pytanie a Twoja odpowiedź na pewno będzie pomocna.

**Comment by echemik** [comment]
Winne jest zapytanie poniżej które trwa 15 sekund. (prosto w SQL tyle samo). Serwer jest mocny. Sortowanie wyłączone w configu i nie ma założonego sortowania na liście. Ciężko mi stwierdzić co może być problemem.

Userów jest wlane 90 sztuk. Wszystkie leady są dopisane do jednego usera.

Obawiam się że leady mogą mieć inną wydajność niż Kontrahenci ze względu na inną strukturę tabel - jakieś pomysły?

"SELECT DISTINCT
	vtiger_crmentity.smownerid,
	vtiger_users.first_name,
	vtiger_users.last_name,
	vtiger_groups.groupname
FROM
	vtiger_leaddetails
INNER JOIN vtiger_crmentity ON vtiger_leaddetails.leadid = vtiger_crmentity.crmid
LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id
LEFT JOIN vtiger_groups ON vtiger_crmentity.smownerid = vtiger_groups.groupid
WHERE
	vtiger_crmentity.deleted = 0
AND vtiger_leaddetails.converted = 0
AND vtiger_leaddetails.leadid > 0"

**Comment by bpabiszczak** [comment]
99% zgłoszeń tutaj jest kierowanych do nas i wymaga naszej odpowiedzi... jak ktoś będzie bardzo chciał, to mu przetłumaczymy podsumowanie.... 

Na wersji speed do której dałem link jest 15k userów, więc to nie to... rozumiem, że tyle trwa zapytanie wykonane bezpośrednio w bazie danych ? Należy sprawdzić, czy są wszystkie klucze ustawione na kolumnach po których wyszukujemy.

**Comment by echemik** [comment]
Klucze są ustawione prawidłowo, (jest to nieruszana wersja 2.3.49). 

Na wersji speed nie jest dokładnie tak jak mówisz, pierwsze uruchomienie listy leadów trwa : 10 sekund : Copyright 2014 YetiForce.com All rights reserved. [ver. 2.3.578] [Page loading time: 9.695s.]

Potem jak kilka razy odświeżam to mam koło 0,005 sek - zapytanie jest w cache

U mnie jest podobnie, tylko że po 10-20 sekundach znów czekamy 14 sekund (na wersji speed jest tak samo)

Jak rozumiem zapytanie zwraca listę userów którzy są właścicielami choć jednego Leada, to powinno wyglądać tak :

SELECT  DISTINCT
	x.smownerid,
	vtiger_users.first_name,
	vtiger_users.last_name,
	vtiger_groups.groupname
FROM
	vtiger_leaddetails

inner join (select smownerid,deleted,crmid from vtiger_crmentity where setype='Leads' group by smownerid) as x on  vtiger_leaddetails.leadid = x.crmid
LEFT JOIN vtiger_users ON x.smownerid = vtiger_users.id
LEFT JOIN vtiger_groups ON x.smownerid = vtiger_groups.groupid
WHERE
	x.deleted = 0
AND vtiger_leaddetails.converted = 0
AND vtiger_leaddetails.leadid > 0

tylko że w tej chwili jest duży koszt where setype='Leads' bo setype jest wartością tekstową nie INTem.

To wygląda na grubszy problem. Jak proponujecie podejść do tego problemu? Ustawienia cache mysql?

**Comment by bpabiszczak** [comment]
Mi wejście w Lead zajęło 2.3s. Przy czym wersja speed to serwer gdzie mamy prawie 100 testowych instancji CRM, inny speed który generuje 100.000.000 rekordów a więc to nie jest serwer który nic nie robi... Odnośnie cache, to każde kolejne odpytanie [nowej strony w zakładce lead] trwa tylko 0.5s, a więc to dziwne, że mamy aż tak duże rozbieżności. 

Jeżeli widzicie problem u siebie [ja go u nas jeszcze nie widzę - na speed] to możecie dokładnie zdiagnozować zapytanie i zaproponować lepsze rozwiązanie, możecie również wysłać do nas poprawkę na github do wgrania. 

Będziemy zajmować się optymalizacją zapytań, ale to pewnie za kilka tygodni, jak skończymy inne elementy, po to teraz generujemy dużą bazę [100M rekordów] aby mieć na czym pracować.

**Comment by bpabiszczak** [comment]
jeżeli lista leadów [100. tyś] ładuje Ci 10s to ile ładuje Ci kontrahentów, których jest 10x więcej?

**Comment by echemik** [comment]
Pomyliłem się, to lista Accounts wchodzi na speedzie 10 sek. 

Problem jest już rozpoznany, wyżej go opisałem, problemem są dwa zapytania :

1 : 

SELECT DISTINCT vtiger_crmentity.smownerid, vtiger_users.first_name, vtiger_users.last_name, vtiger_groups.groupname FROM vtiger_leaddetails  INNER JOIN vtiger_crmentity ON vtiger_leaddetails.leadid = vtiger_crmentity.crmid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_groups ON vtiger_crmentity.smownerid = vtiger_groups.groupid WHERE vtiger_crmentity.deleted=0 and vtiger_leaddetails.converted=0 AND vtiger_leaddetails.leadid > 0

(14 sek)
2: 

SELECT count(*) AS count  FROM vtiger_leaddetails  INNER JOIN vtiger_crmentity ON vtiger_leaddetails.leadid = vtiger_crmentity.crmid INNER JOIN vtiger_leadaddress ON vtiger_leaddetails.leadid = vtiger_leadaddress.leadaddressid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_groups ON vtiger_crmentity.smownerid = vtiger_groups.groupid WHERE vtiger_crmentity.deleted=0 and vtiger_leaddetails.converted=0 AND vtiger_leaddetails.leadid > 0

(12 sek) (to czy pokazuje się suma rekordów powinno być w configu moim zdaniem definiowane) Szkoda tyle zasobów na tego counta. To powinno być włączalne.

Będziemy szukać rozwiązania na 1 zapytanie ale to jest głębszy problem.
Dam znać jak się uda coś zrobić, dobrze jakby Wasz programista na to rzucił okiem, być może jest jakiś prosty sposób rozwiązania tego problemu.

**Comment by bpabiszczak** [comment]
Ale w przypadku 1 to chyba nie jest to całe zapytanie? Ponieważ tam są m. in. limity ustawiane, więc on nigdy nie powinien odpytać całej tabeli [no chyba, że w pliku głównym modułu, mamy włączone sortowanie po kolumnie innej niż głównej].

**Comment by echemik** [comment]
Do tego jest zapytanie :1234: 

3:
SELECT vtiger_leaddetails.company, vtiger_leaddetails.vat_id, vtiger_leadaddress.addresslevel5a, vtiger_leadaddress.phone, vtiger_leaddetails.email, vtiger_leaddetails.leadstatus, vtiger_crmentity.smownerid, vtiger_crmentity.createdtime, vtiger_leaddetails.leadid FROM vtiger_leaddetails  INNER JOIN vtiger_crmentity ON vtiger_leaddetails.leadid = vtiger_crmentity.crmid INNER JOIN vtiger_leadaddress ON vtiger_leaddetails.leadid = vtiger_leadaddress.leadaddressid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_groups ON vtiger_crmentity.smownerid = vtiger_groups.groupid WHERE vtiger_crmentity.deleted=0 and vtiger_leaddetails.converted=0 AND vtiger_leaddetails.leadid > 0 ORDER BY modifiedtime DESC LIMIT 0,21

Które trwa 5 sek co da się jakoś tam wytłumaczyć

To jest zapytanie (1) które zwraca listę użytkowników wraz z przypisaną grupą, którzy mają chociaż jednego leada. Służy do podania ich do pola wyboru filtrowania na liście.

**Comment by bpabiszczak** [comment]
U nas każde z tych zapytań [gdy wywołujemy je bezpośrednio na bazie] zajmuje 5 krotnie mniej czasu niż u Ciebie. Po drugie zliczanie liczby rekordów jest realizowane niezależnie od ładowania listy rekordów, a więc nie ma wpływu na wyświetlanie. Po trzecie tak jak pisałem, sortujesz wyniki [zmień sobie w pliku głównym modułu, na kolumnę z kluczem głównym] i zapytanie będzie się wykonywać kilkukrotnie szybciej...

**Comment by echemik** [comment]
Sortowanie dotyczy zapytania 3 które nie jest problemem.

Problem powstaje kiedy na liście dodasz Właściciel, system żeby wyświetlić wybór w selectboxie potrzebuje zadać zapytanie 1 które jest zasobożerne przy większej ilości.

Podrzucam temat bo przy badaniu wydajności na pewno to wyjdzie.

Problem leży też w strukturze crmentity już w Vtiger. Pole Setype powinno być INTEM, wtedy klucz na nim założony pozwolił by szybko zwrócić rekordy ograniczone do pewnego modułu i zapytanie można by inaczej zbudować.

**Comment by bpabiszczak** [comment]
ale to jest open source, mamy problem, szukamy rozwiązania, wgrywamy poprawkę, nie mamy problemu... :] Każda zmiana wpływająca na wydajność to nie 5 min roboty, wymaga zmian w wielu elementach systemu.

**Comment by echemik** [comment]
Doskonale to rozumiem, więc podrzucam temat bo takie rzeczy lepiej zrobić wcześniej niż później.

**Comment by bpabiszczak** [comment]
System można w setkach miejsc zoptymalizować, to wiemy, po to robimy moduł generujący dane, ale na dzień dzisiejszy, ma to dla nas niski priorytet, tzn, chętnie zobaczymy paczkę optymalizacyjną, ale nie będzie na razie tego optymalizować, może za 4-8 tygodni.
