### ISSUE TITLE
MailScanner Settings loading time over 2s

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2493]
Gitdeveloper 2.3.767

**Comment by nikdejan** [comment]
At 2.3.927 it is actually 6.7 seconds. Not a big deal, but ... you know.

**Comment by mariuszkrzaczkowski** [comment]
Configuring the scanner was rebuilt problem no longer exists.
https://github.com/YetiForceCompany/YetiForceCRM/commit/6602e6333453068ecc2305e714f124b3920528c9
