### ISSUE TITLE
[BUG] MailScanner Prefixes

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2494]
Settings>MailScanner>Prefixes Tab. Looks like table of prefixes that appears in this tab is hardcoded, since I was unable to add Sales Processes prefix to the table.

**Comment by bpabiszczak** [comment]
Please check this: https://gitdeveloper.yetiforce.com/index.php?module=Vtiger&parent=Settings&view=CustomRecordNumbering
