### ISSUE TITLE
[Improvement] MailScanner to bind emails to Sales Process

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2496]
If you want to replace Opportunities with Sales Processes, than you have to integrate SP with email.
I think that primary channel of communication with a customerS for most YF users is email and I think that email integration should be of HIGHEST PRIORITY.

**Comment by bpabiszczak** [comment]
Soon we'll add it.

**Comment by nikdejan** [comment]
Now might be the right moment.
And I think it's better not to close issues until they are resolved. You might think there is nothing to talk about because you are eventually going to do it anyway, but tracking issues is useful for us, yf potential users, so we could track the progress of things that are important to us.

**Comment by bpabiszczak** [comment]
Please check last version.

**Comment by nikdejan** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13381850/12222512/fe28f3f0-b7be-11e5-9cfc-3168611e2d37.png)
