### ISSUE TITLE
[Design Bug/Improvement] Empty box in Roundcubes message-oss-header

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2497]
Remove the box or (better) add possibility to attach email to Sales Process. (gitdeveloper 2.3.767)
![untitled](https://cloud.githubusercontent.com/assets/13381850/11896338/ed7259de-a585-11e5-955d-1f384678fb59.png)

**Comment by bpabiszczak** [comment]
Soon we'll add it.
