### ISSUE TITLE
[Improvement] Dedicated Activities widget for Sales Processes module

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2499]
Like the one we have in Account module and like the one we had in old Opportunities module.

**Comment by nikdejan** [comment]
Widget is called Calendar, actually.

**Comment by bpabiszczak** [comment]
Soon we'll add it.

**Comment by nikdejan** [comment]
Cough, cough ...

**Comment by nikdejan** [comment]
Please reopen this issue, or add Activities/Calendar widget to Opportunities/
SSalesProcesses. 
Activities are most needed in Opportunities, because all the activities in sales process are naturally related to particular Opportunity.
I think it's easy to add a widget to a module, because it already exists on the system. Just add 'SSalesProcesses' to $allowedModules in /modules/Vtiger/widgets/Activities.php on line 12. And maybe somewhere else?
