### ISSUE TITLE
[Improvement] Sales Processes - Stage AND Status fields

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2500]
1. Opportunities used to have Sales Stage field. Sales Processes should also have that field and I think this is beyond discussion.
2. Additionally, I think that Sales Processes should have one more field, which I would like to call Sales Status, or Status only. Status should be picklist with values: Unread, Answered, Updated, Action needed etc. Sales Status should be something like Ticket Status. 
Why do we need one more field? Sales Process is a long term process which goes through many different stages and this stages should be expressed through Sales Stage field. But during that long term process, on daily basis you exchange many email, phone calls, sms with customer. You also schedule activities related to sales process. Status field should be used to reflect those DAILY CHANGES, SHORT TERM CHANGES. If I received new email from the customer, related to particular Sales Process, Status should be set to Unread, while Stage remains unchanged. When I answer all the questions, Status should be Answered. If I schedule a task or activity, Status should be set to Action needed. I should be able to manually change Status but workflows could be really useful. 
And here is google translate version of my request:
1. Możliwości użyte do sprzedaży pole Stage. Procesy sprzedaży powinny mieć tę rolę i myślę, że to nie podlega dyskusji.
2. Ponadto, myślę, że procesy sprzedaży powinien mieć jeden więcej pola, które chciałbym zadzwonić status sprzedaży lub status tylko. Status powinien być PickList z wartościami: nieprzeczytane, odpowiedział, aktualizacja, Akcja potrzebne itp status sprzedaży powinno być coś takiego jak status biletu.
Dlaczego potrzebujemy jeszcze jednego pola? Proces sprzedaży jest procesem długotrwałym, który przechodzi przez wiele różnych etapów i to etapy powinny być wyrażone przez pola Stage sprzedaży. Ale podczas tego długotrwałego procesu, codziennie wymieniać można wiele wiadomości e-mail, rozmowy telefoniczne, sms z klientem. Również zaplanować działania związane z procesem sprzedaży. Pole statusu powinien być stosowany w celu odzwierciedlenia tych dziennych zmian, krótkie zmiany kadencji. Gdybym otrzymał nową wiadomość e-mail od klienta, związane z konkretnym procesem sprzedaży, status powinien być ustawiony na nieprzeczytane, natomiast etap pozostaje bez zmian. Kiedy się odpowiedzieć na wszystkie pytania, status należy odpowiedzieć. Gdybym zaplanować zadanie lub działalności, status powinien być ustawiony na działanie potrzebne. Powinienem być w stanie ręcznie zmienić status, ale przepływy pracy może być bardzo przydatne.

**Comment by florek41** [comment]
Firstly - I think google translate version is realy poor - there is no need to use it. I understood  more from EN version than from translatePL ;)

Secondly - for me you have right and I agree with you.
For me Updated and Unread is enough for work, but I understand that different companies need more statuses.

I thought about something more and something different than you write - Sales Stage should be (or possible to configure) automatic.
for ex. if Quote/Order/Invoice changed status then sale process stage change automaticly to related status.
It will be great to have possibility to define What/When/etc is changed.

**Comment by nikdejan** [comment]
Well, sorry for clumsy google translate text :-) It was only a trick to get faster response ;-)
Updated and Unread etc - this should be user configurable so everyone could set it to their own needs.
I agree that Stage should be possible to configure automatic, but it also manual, I think. And same should be possible for Status. But I think that automation should be achieved through workflows. Sales automation is what workflows are invented for.

**Comment by witer30** [comment]
Sales automation is what workflows are invented for.Can you provide more info about this...?

**Comment by nikdejan** [comment]
What I said is nothing but a general statement concerning CRM world. One of the main benefits of CRM is sales automation, or sales force automation as somewhere is said. And automation means: "When I do this, system will automatically do something else". System should "understand" the logic of a sales process and should do automatically anything that can be done. I suppose you are familiar with workflows in YetiForce because that is exactly what workflows are doing. Go to Settings>Automation>Triggers (new name for workflows I suppose). Click New Workflow and you have three steps to define 1. When, 2. Under which condition and 3. What tasks should the system do for you.

**Comment by florek41** [comment]
You have right about workflows - if it will be able to update related record when current record is updated it was almost everything what I need :)

**Comment by nikdejan** [comment]
Yep. And I +1d that in #1965 and in #2343 and I'm giving it another +1 here :-)
Have you tried creating custom functions? I shouldn't be too difficult.

**Comment by bpabiszczak** [comment]
Czy możemy topic ten prowadzić w PL? EN wydłuża mój czas odpowiedzi... Z tego co kojarzę, każdy zna PL, więc szkoda mojego czasu na EN.

**Comment by nikdejan** [comment]
Nie mówię po polsku, ale mój przyjaciel google.translate mówi bardzo dobrze. :) Jeśli to będzie Ci łatwiej i szybciej można mówić po polsku, a ja staram się podążać za dyskusje z pomocą GT.

**Comment by florek41** [comment]
Jeśli jedyna osoba, która nie mówi po polsku, nie ma nic przeciwko temu to nie widzę problemu.

Ogólnie chodzi o to, że w module Procesy Sprzedaży mile widziane byłyby 2 rzeczy - Etap Sprzedaży oraz Status.
- Etap nawiązuje do całego procesu, który jest długi. Czyli informuje czy jest on na etapie tworzenia oferty, czy zaakceptowany czy np. w realizacji. Dobrze gdyby użytkownik mógł ręcznie zmieniać status, ale automatyzacja jest czymś, czego zdecydowanie potrzeba (niżej wyjaśnienie)
- Status opisywałby krótkotrwałą zmianę w procesie - np. kiedy pojawia się nowy mail to zmienia się na Nieprzeczytany, kiedy ktoś inny zmieni tam cokolwiek to mamy Uaktualniony etc.

Kolejną sprawą jest wspomniana wcześniej automatyzacja. W sytuacji idealnej działa to w sposób przykładowy:
Mamy Proces Sprzedaży i dodaną Ofertę - Status oferty to w przygotowaniu. Na podstawie tego statusu ustawiany jest Etap Sprzedaży w Procesie nadrzędnym na "Oferta w przygotowaniu".
Analogicznie kiedy w Ofercie zmieniamy status na "Zaakceptowana" to zmianie ulega etap SP na "Oferta zaakceptowana" etc. ect.

Świetnym rozwiązaniem byłaby możliwość konfiguracji tego np. za pomocą Workflow - Aktualizacja rekordu powiązanego to coś, czego szukamy (#1965 i #2343 ):)

Na chwilę obecną taka możliwość istnieje jedynie z poziomu programistycznego a Najlepszy na świecie CRM powinien, moim zdaniem, umożliwiać konfigurację tego typu rzeczy właśnie z poziomu workflow ;)

**Comment by bpabiszczak** [comment]
Moja pomyłka, bo myślałem, że on mówi po polsku... w poniedziałek odpiszę po angielsku na cały post, jak ktoś coś ma do dodania niech napisze, bo proces się tworzy, a więc na zmiany jest niewiele czasu :]

**Comment by florek41** [comment]
Jedna z rzeczy, które chętnie zobaczyłbym w YF (o której pisałem już przy okazji dyskusji o przebudowie modułów produktowych) to kalkulacje w których produkt można budować na potrzeby klienta/zamówienia a nie na stałe tak jak w chwili obecnej tworząc nowy produkt z powiązanymi podproduktami.
Mam jakąś swoją wizję tego - pytanie czy w ogóle jest szansa to zrealizować ?
Kalkulacja działałaby w sposób podobny do obecnego z tą różnicą, że każdy produkt/usługa byłaby możliwa do rozbudowania za pomocą podproduktów lub np. materiałów (oddzielny moduł) - cena końcowa ustalana byłaby na podstawie kosztu wszystkich podproduktów/materiałów + ich marża etc.

**Comment by nikdejan** [comment]
Status AND Stage was my idea but it is not original. Here is the competition:http://crmbook.powerobjects.com/basics/microsoft-dynamics-crm-sales-process/opportunities/

**Comment by echemik** [comment]
To co wg mnie jest potrzebne : 

1. Możliwość Tworzenia filtru na podstawie wartości rekordów z pól z modułów powiązanych (np. pokaż mi leady które nie mają powiązanego żadnego połączenia, ew. pokaż mi leadu które mają ostatnie połączenie dalej niż 30 dni)
2. Możliwość tworzenia filtrów na podstawie ilości rekordów powiązanych (np. pokaż mi kontrahentów którzy mają więcej niż 3 szanse sprzedaży)
3. Możliwość dodawania swobodnie pól do Aktywności z Kalendarza. Szereg procesów sprzedaży opartych o Telemarketing jest oparte na zdarzeniach w kalendarzu. Widzę dosyć oczywisty proces w którym Telemarketing dzwoni do bazy Leadów i po rozmowie ustawia status lub efekt rozmowy etc. na podstawie tego modyfikowany jest rekord Leada (np. status), bądź tworzone inne rekordy (workflow uruchamia konwersję na kontrahenta i dodaje Szansę sprzedaży) chodzi o to żeby sam Telemarketer nie musiał po rozmowie odwiedzić kilku modułów (np. Wejście w Leada i zmiana status na niezainteresowany etc.+ dodanie rozmowy)
4. Wspomniane wyżej workflow zmian w rekordach powiązanych

Całość z tych rzeczy można robić na okrętkę tj. na handlerach + harmonogramie i dodatkowych ukrytych polach.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
here is what @bpabiszczak says:
1. The system won't have two separate fields such as stage and status (Błażej says that he doesn't think they're necessary).
2. In the new version, there is a mechanism that shows changes in records. It appears to be better than all suggestions from this thread because it works independently for each user. 
3. We are planning further automation of processes but it requires a lot of time. 
4. We aren't planning to add filters that work with related modules. This can be achieved with a regular filter, you can simply add an indirect field that saves value from a related module. At the moment, this field can be added at the panel level. However, as far as I remember, it works only with list-type fields.
