### ISSUE TITLE
[Improvement] Comment/Attention field to Sales Processes

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2502]
Old Opportunities had a Comment field, and Sales Processes doesn't have it. I think that Sales Processes should have that field but it's name shouldn't be Comment, because it could be confused with ModComments. I think it should have name Attention and It would be used for special employees internal notes concerning particular Sales Process.

**Comment by nikdejan** [comment]
When I think again... I do need that field for Accounts and Opportunities (and now Sales Processes), but since this field can be easily added as a Custom field, than maybe it's not necessary to have it by default.

**Comment by bpabiszczak** [comment]
Please check again... https://gitdeveloper.yetiforce.com/

**Comment by nikdejan** [comment]
I checked again and Accounts have that field, why Opportunities don't have it. But do not bother adding it, because it can easily be added from Settings>Edit Fields in case anyone needed it.

**Comment by rskrzypczak** [comment]
Added description fields by default to the Opportunities module.
