### ISSUE TITLE
[Bug] Remove traces of Opportunities

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2503]
![untitled](https://cloud.githubusercontent.com/assets/13381850/11899330/6692b6d4-a59e-11e5-8fcf-a80731181789.png)
This should not be there, or (better) should be replaced with same function for Sales Processes.

**Comment by bpabiszczak** [comment]
Next week we will fix this tab so that it works with the new Sales Process.

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/72d49cf2f866e4b06d4eabdcb78807dc624d2539
