### ISSUE TITLE
[BUG] Fatal error - New S modules - Picklist editor

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2504]
![untitled](https://cloud.githubusercontent.com/assets/13381850/11899764/ab8500fa-a5a1-11e5-9253-333dbb7c7d51.png)
gitdeveloper 2.3.773

**Comment by florek41** [comment]
duplicate: #2339

**Comment by nikdejan** [comment]
Oops! Sorry!
