### ISSUE TITLE
[Improvement] Make Sales Processes part of a ... Sales Process

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2505]
Settings>Processes>Sales. Here we used to have Opportunities tab where we defined which Opp. stages determine that Opportunity is closed and some other settings. Same should be done for Sales Processes, off course after field Stage has been added to Sales Processes module.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2503

**Comment by nikdejan** [comment]
In #2503 you fixed the problem of old Opportunities remaining in Settings>Process>Sales.
What still remains to be done is defining closed statuses for new S modules.
Please reopen, or even better - fix it :-)
