### ISSUE TITLE
Bug Activities

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2507]
![image](https://cloud.githubusercontent.com/assets/6897502/11913865/ee3aa556-a67a-11e5-8248-b4622da6b951.png)

**Comment by rskrzypczak** [comment]
I can't recreate your error, can you give me some more details how to trigger it ?

**Comment by eptapsyxos** [comment]
Give me some time please to remember because me either rembering exactly how i trigger it

**Comment by nikdejan** [comment]
Here it is: https://gitdeveloper.yetiforce.com/index.php?module=Accounts&view=Detail&record=111
gitdeveloper 2.3.788
I created Account, went to related activities and created Activity. I left all fields default, only added few words in Subject field.

**Comment by eptapsyxos** [comment]
Thanks @nikdejan my head was going to blow from trying to recreate it.
