### ISSUE TITLE
Basic navigation improvement 

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2508]
It's very annoying when we are at a module list or inside a record and we can not move back to list view and we have to re open the responsive layout and select the same module so....
Quick solution here
![image](https://cloud.githubusercontent.com/assets/6897502/11913926/aa72c68a-a67c-11e5-9ae8-8dc203671121.jpeg)

**Comment by florek41** [comment]
have you try to click in "Contacts" in breadcrumbs? This is what you looking for.

**Comment by eptapsyxos** [comment]
Ok I did not tried.same on me.

**Comment by nikdejan** [comment]
you have six more souls left ;-)

**Comment by eptapsyxos** [comment]
Because I believe it's impossible to translate my nickname at Google and from there to find what does it mean(because it's a Greek word written in greeklish).i ll consider that you know the Greek language or you are Greek. :-)

**Comment by nikdejan** [comment]
Well, I'm not Greek but I do know some Greek. Not an expert, though :-) 
But you should never undermine the power of google translate. I made some native polish speakers think that I speak polish ;-) @bpabiszczak

**Comment by eptapsyxos** [comment]
Hahahahhahahahaa you make me laugh.you are genius!!!!!!!
