### ISSUE TITLE
[BUG] Checkbox in wired place on related Activities in Campaigns

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2512]
What is this for ?

![design_checkbox_campaigns](https://cloud.githubusercontent.com/assets/4824588/11915171/b85ac6c6-a69a-11e5-942f-db33bb1d3684.jpg)

**Comment by nikdejan** [comment]
There should be a switch Historical/Current, as it is in Activities widget. This is a bug.

**Comment by nikdejan** [comment]
Now I checked again and it is OK. In Chrome and in Firefox. Looks like it has been fixed.

**Comment by florek41** [comment]
You have right - on v. 2.3.778 look good
