### ISSUE TITLE
Calendar Improvement Ideas

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2513]
Hello again.
Because you said that you want to make the yeti the best crm on the world and the last 3 years I have tested over 100 crm I am posting you the best solutions I have found for certain modules design etc.
No one of them is the best but some of them have some good ideas that may help you to take a taste.

Because the enemy of the good is the best have a look here.
![image](https://cloud.githubusercontent.com/assets/6897502/11919753/d7fec382-a763-11e5-928d-82db22c92636.png)
![image](https://cloud.githubusercontent.com/assets/6897502/11919755/e432449e-a763-11e5-8964-23b89fccef8d.png)

**Comment by eptapsyxos** [comment]
LETS SAVE SOME MORE CLICKS HAVE A LOOK WHAT I MEAN
![calendarmousehover](https://cloud.githubusercontent.com/assets/6897502/11930275/9ca73bc0-a7ea-11e5-91af-94d19e8f337e.jpg)
![calendar2](https://cloud.githubusercontent.com/assets/6897502/11930278/a4d0afd4-a7ea-11e5-9038-fa9326fbf8a8.jpg)

**Comment by paula-w** [comment]
The calendar keeps changing and developing. Some of the options you presented are available in the new version of the system. We're planning to improve and simplify the interface even more in the future.
