### ISSUE TITLE
Dashboard ideas for improvement 

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2514]
With the same logic I mention in my previous post I am posting here a very useful dashboard I found on another crm
![image](https://cloud.githubusercontent.com/assets/6897502/11919788/86dd3604-a764-11e5-84eb-5809e1e09987.png)

![image](https://cloud.githubusercontent.com/assets/6897502/11919793/934a460c-a764-11e5-9dc9-c7025bb4eb98.png)
![image](https://cloud.githubusercontent.com/assets/6897502/11919795/9dbe9cd2-a764-11e5-9605-65158bec7037.png)

**Comment by bpabiszczak** [comment]
I don't understand what is so cool in here that YetiForce doesn't have? I'd suggest concentrating on useful widgets, instead of the configuration appearance...
