### ISSUE TITLE
Reports ideas for improvement 

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2515]
From the same crm I found a very good way to see and generate reports.
![image](https://cloud.githubusercontent.com/assets/6897502/11919803/d21d7412-a764-11e5-852d-690292f33943.png)
![image](https://cloud.githubusercontent.com/assets/6897502/11919805/dffab428-a764-11e5-847c-d8ebc71652a4.png)

**Comment by paula-w** [comment]
The reports will be definitely improved. Screenshots alone don't really bring anything to the project, we know how to make things more user-friendly or more transparent. The only problem is that there's nobody to develop it, because there are always some other tasks with higher priority.
