### ISSUE TITLE
Language Help

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2516]
Where can i help Yetiforce translating to pt_br ? i'm Portuguese(pt_pt) but its almost the same as pt_br.

**Comment by vctrin** [comment]
Hi yozhi

My name is Valmir and I'm responsable for the Yetiforce translation from
english to brazilian portuguese. How can I help you?

Valmir Trindade
valmir@ttcasolucoes.com.br
Em 21 de dez de 2015 8:19 AM, "yozhi" <notifications@github.com> escreveu:

**Comment by yozhi** [comment]
we many thing in yetiforce that are not translated to Brazilian Portuguese, so if you want i can help translating that things are missing

**Comment by bpabiszczak** [comment]
If you want to change something in YetiForce [eg. a translation] you should learn how to use GitHub [there are tons of instructions on the net]. In short – it's enough to make a fork, upload the changes and submit them for us to accept. If they're correct we will add them to the system. A good example of a user who adds translations is https://github.com/waw555?tab=activity. GitHub also lets you add changes from the website level, but it takes much longer. 
It would be best if you contact @vctrin and you discuss the terms of cooperation on the translation development.
