### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2517]
I know im being annoying with basic questions for you , but im new in this kind of things.
My question is, how can update my yetiforce CRM without a clean installation ?

**Comment by nikdejan** [comment]
As far as I know, you can update only from stable to stable version. The last stable version is 2.3.49 and when the next stable version comes out, Yeti team will make script for update. 
If you are using developer version you can not update by the script. You can do it manually if you are skilled enough, or you can hire a developer to do it for you. YetiForce team can do it for you, but it is a payed service.

**Comment by yozhi** [comment]
the hard thing to do , its working with mysql to update yetiforce, for example (https://github.com/YetiForceCompany/YetiForceCRM/commit/d955605da41075829c3eadfffb57eb89ee497848) , how can i add those record to my db if some records alreadys exists ?

**Comment by reeid** [comment]
@yozhi  This question is not suit to this stuff here. Navigate to place with beginners in programming/sql
Stop trolling mate. Enough that guys talks in Polish here. With aspirations to become leader in OS CRM/ERP/EDM or whatever, such a trends looks like joke in the eyes of professionals.
@yetiforce - pls dont take me racism or so, I guess you know what is international approach to business and so on..

**Comment by bpabiszczak** [comment]
@yozhi please read this article: https://yetiforce.com/en/implementer/installation-updates/176-system-update-not-verified.html
