### ISSUE TITLE
Unique Mobile Number

### ISSUE THREAD

**Issue by sangeetasoni19** [YetiForceCompany/YetiForceCRM#2518]
I have added a validation of access for unique mobile number but still I can add same number for two records.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by sangeetasoni19** [comment]
I want to put a validation for mobile number i.e. two opportunity records shouldn't have same contact number/mobile number.
I went to validation of access then created a new condition. I entered condition details. Then added a condition that contact number is not empty. Entered the action for field is unique
