### ISSUE TITLE
[Discussion] Roundcube, email and other beasts

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2519]
I would like to suggest an improvement here, but since there is more than one thing to improve and since there will be different opinions I marked this issue as [Discussion].
The main problem with current system as I see it (maybe I am missing something, so please correct me if I am wrong) is that it doesn't support multiple crm users using the same mailbox. And this kind of setup should be supported because it is very common, and if you have email like support@yourcompanu.com then it is quite natural that more than one person is opening the same mailbox and responding from it. Customers would normally receive emails from Employee1<support@yourcompany.com> and Employee2<support@yourcompany.com>, with respective signatures, and when customers reply, emails would go to Employee1<support@yourcompany.com> and Employee2<support@yourcompany.com>.
1. If you have more then one crm user using same mailbox account neither you nor your customers will ever know who sent en email. Partial solution to this problem is using multiple Roundcube identities so every employee could choose his own identity when composing an email. But here you have some small problems remaining: 1a) Security. Users can fake their identities if they want to make a trouble to their coworker ;-) 1b) Efficiency. Nobody want's an extra picklist to select. 1c) Customer can see the identity of the sender from signature and from from_name, but it is not saved in the ossmailview table and can not be seen from email widget and from other places in crm.
2. In MailScanner settings you can connect milboxes with crm users 1:1. But if more than one person is using the same mailbox, this doesn't make sense, because everything is always assigned to one person.
ToDo:
1. Relate crm users with roundcube identities in a separate table. Alternatively, as sender's identity we could use crm user email and name.
2. Make assigning user in MailScanner more clever. Sent messages should be assigned based on from_name, not only from_email. Received messages should be assigned based on to_name, not only to_email.
3. Add to_name and from_name to ossmailview table. This would help trace sender/receiver identity throughout crm.
Edit: No. 3 is pointless because there are already from_id and to_id fields in ossmailview table. They just need to be utilized more intelligent.

**Comment by eptapsyxos** [comment]
+1

**Comment by bpabiszczak** [comment]
The system allows multiple users to log into one mailbox  https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Mail&view=Autologin&block=8&fieldid=78 

It's not normal for many people to have an access to one mailbox. If it's for example a @support mailbox, then the system should eg. automatically create tickets in CRM. I've already seen companies where 30 people got general mails, but it turned out nobody read them and nobody knew who dealt with what.

You decide in the configuration whether the user is allowed to create identities or not. 

Generally for me the whole thing is chaotic, I don't really get what the question is. As far as I'm concerned the issue should be closed...

**Comment by nikdejan** [comment]
Simply put, if multiple crm users use the same mailbox, they will have to use same sender identity (or identities, if you have more than one, but list of identities is the same for all crm users), and this means not only the same from_email (which is ok), but also the same from_name (which is not ok) and same signature (which is extremely not ok).
there is a relation between crm users and roundcube users. There is also a relation between roundcube user and sender identities. What we need is relation between crm users and sender identities.
