### ISSUE TITLE
Option to add widgets non-admin users in home page

### ISSUE THREAD

**Issue by myexmyoki** [YetiForceCompany/YetiForceCRM#2520]
Kindly help.i installed yetiforce CRM but the problem is that while adding widgets is available for non-admin users in home page,when i set up a non-admin user with all other privileges,the home page is blank and the option for adding a widget isn't shown in the page.Im using the current version.Already tried uninstalling and re installating.
Kindly help how i can enable the option to add widgets in home page for non admin users,

**Comment by myexmyoki** [comment]
![crmscreenshot](https://cloud.githubusercontent.com/assets/16384194/11930560/8bda24dc-a7f5-11e5-90d8-6bd574862eed.PNG)

**Comment by florek41** [comment]
Have you try this tool: 
https://gitdeveloper.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&sourceModule=Home
?

Non-admin users can only enable widgets that admin add in this panel or create form filter on dashboard.

**Comment by myexmyoki** [comment]
Thank you.bt kindly help me on how to acess the same from my local
CRM.thanks in advance



*''Some decisions are difficult and hard to be made but they are very
important to make'' -J Maxwell*

**Comment by myexmyoki** [comment]
Thanks for the assist.i saw it

*''Some decisions are difficult and hard to be made but they are very
important to make'' -J Maxwell*

**Comment by bpabiszczak** [comment]
Thank you @florek41

**Comment by Sindhuja16** [comment]
@bpabiszczak Can't we add a particular widget to more than a single user at a time ?
I have to add same widget to many users, and doing it by adding their roles one by one  in widget configuration which is tedious, can I get it done in another way?

**Comment by bpabiszczak** [comment]
new question = new issue
