### ISSUE TITLE
[Improvement] Timeline widget

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2522]
It would be nice to have a widget which would display history of everything that is connected with certain sales process (and maybe other processes).  First of all, widget would include all the data from existing Update widget, plus comments history. And then, there would be histories of other related records, including email. Admin would be able to choose which related modules are going to be included, or there would be multiselect for filtering and user could choose which data he wants to see.

**Comment by paula-w** [comment]
We added a new notification module, it's fully configurable. Additionally, we made some improvements in the standard mechanism that deals with history of changes in records.
