### ISSUE TITLE
Widgets help

### ISSUE THREAD

**Issue by myexmyoki** [YetiForceCompany/YetiForceCRM#2523]
Im new to yetiforce CRM.Kindly help on how to add dashboard widgets with pictorial presentations
![yeti](https://cloud.githubusercontent.com/assets/16384194/11949261/51363476-a88e-11e5-92eb-cf1511994042.PNG)

**Comment by florek41** [comment]
You can add those widgets using this tool:
https://gitdeveloper.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67

On admin settings Standard Modules > Widgets – Configuration
From there you can add all widgets. On screen you have:
- Tickets by Status
- Leads by Status Converted

**Comment by myexmyoki** [comment]
Thanks.On that i get as attached.where exactly is the configuration panel
for the pictorial widgets.
Thanks in advance

*''Some decisions are difficult and hard to be made but they are very
important to make'' -J Maxwell*

**Comment by florek41** [comment]
see this:

![yf_widgets](https://cloud.githubusercontent.com/assets/4824588/11949957/a3b06dde-a884-11e5-9e0c-8c45b136bf48.gif)

Video is taken on current developer version: https://gitdeveloper.yetiforce.com/

**Comment by myexmyoki** [comment]
Thank you very much for the help.I appreciate

*''Some decisions are difficult and hard to be made but they are very
important to make'' -J Maxwell*

**Comment by bpabiszczak** [comment]
Thank you @florek41
