### ISSUE TITLE
[help] PDF parent=Settings ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2524]
Hello, I get an error when you trying to enter the setup module pdf.
(crm.local/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35)
This error occurs absolutely everywhere, when you install from the dev repository.
Error: ERR_EMPTY_RESPONSE

**Comment by bpabiszczak** [comment]
For me work ok: https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35

**Comment by kjradv** [comment]
bpabiszczak, on gitdeveloper its work.
If you install git developer or the local host vds then this error occurs.

**Comment by bpabiszczak** [comment]
The developer version is the same version you can download from here: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer. The only difference is the installation file that we generate dynamically. If you have an error that doesn't exist in https://gitdeveloper.yetiforce.com/ , then its cause by the server's configuration, so you have to start looking for the problem in your configuration and logs. Unfortunately I know nothing about your server [CRM version, PHP, etc.] which the detailed logs show.... so I have no way to help you.
