### ISSUE TITLE
[bad chat] on test site

### ISSUE THREAD

**Issue by SergeyDjam** [YetiForceCompany/YetiForceCRM#2526]
frame chat request is https://test.yetiforce.comlibraries/AJAXChat/index.php

**Comment by MaciejStencel** [comment]
Czat się odpala pełnoekranowo jeśli sesja zalogowanego użytkownika
istnieje. 

Na incognito lub innych przeglądarkach wyświetla: 

"ERROR 103" 

Także bezpieczne, można by co najwyżej zmienić komunikat, albo
przekierowywać na główną stroną systemu. 

-- 

Z poważaniem / Regards 

MACIEJ STENCEL 
Lead Programmer

M: +48.884949123
E: m.stencel@yetiforce.com 
-------------------------

We created an innovative open source project called YetiForceCRM. You
can test it here [2], download [3] it for free or read its documentation
[4]. Follow us on Twitter [5] to get real-time info about new
functionalities and articles. 

W dniu 22.12.2015 16:01, SergeyDjam napisał(a): 

> frame chat request is https://testyetiforcecomlibraries/AJAXChat/indexphp 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/YetiForceCompany/YetiForceCRM/issues/2526
[2] https://test.yetiforce.com
[3] https://github.com/YetiForceCompany/YetiForceCRM
[4] https://yetiforce.com/en/documentation.html
[5] https://twitter.com/YetiForceEN

**Comment by SergeyDjam** [comment]
chat d'nt work

**Comment by MaciejStencel** [comment]
English:
I don't know what are you issuing. I've checked if it is possible to fire chat straight thrue given URL without beign logged in in CRM.

Chat works only when someone is logged in session. Without it it gives error, so it is safe.

**Comment by SergeyDjam** [comment]
error in url refer URL frame

what upload in this picture?

**Comment by SergeyDjam** [comment]
At the bottom of the page of the test site has a frame. He does not work. Those. Frame does not display the chat window.

**Comment by SergeyDjam** [comment]
bad url: https://test.yetiforce.comlibraries/AJAXChat/index.php
nodad url: https://test.yetiforce.com/libraries/AJAXChat/index.php

**Comment by MaciejStencel** [comment]
This issue was fixed some time ago. test.yetiforce.com is updated every some time when new full version comes out.

For now you can check https://gitdeveloper.yetiforce.com/index.php which is the mirror of the newest developer version.

**Comment by SergeyDjam** [comment]
ok, on https://gitdeveloper.yetiforce.com/index.php all work
thanks
