### ISSUE TITLE
[Bug] Comments count not updated from related tab

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2531]
When I add comment from comment widget on summary page of account, comments count in Comments tab gets updated.
When I click Comments tab and add comments from there, comments count does not get updated.
Developer 2.3.808

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/11e3b698ac708b5df8f2e8ff849e90a8fb2a773a
