### ISSUE TITLE
[Bug] Accounts - Switching between tabs is very slow

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2532]
I tested on this record: https://gitdeveloper.yetiforce.com/index.php?module=Accounts&view=Detail&record=115&mode=showDetailViewByMode&requestMode=summary&tab_label=Summary
Developer 2.3.808
Click: Summary, Detail, Products&Services, Comments and then again P&S and then Detail etc. About every third time you have to wait a few seconds before page updates. The record I tested was related to two products: One in section "Interested in products" and one in section "Products outsourced".

**Comment by mariuszkrzaczkowski** [comment]
Fixed iin https://github.com/YetiForceCompany/YetiForceCRM/commit/11e3b698ac708b5df8f2e8ff849e90a8fb2a773a
