### ISSUE TITLE
[Design Bug] Add comment box too small in comments tab.

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2533]
On summary page of accounts Add comment box is three times bigger than it is in comments tab. 
I think this is a bug and not intentional, because you have plenty of space in comments tab, while you have much less space on summary page. 
Gitdeveloper 2.3.808

**Comment by bpabiszczak** [comment]
Please check now.

**Comment by nikdejan** [comment]
It is still quite small. On 1920px display resolution Add comment box on Summary page (2 columns) is 711px wide. In Comments tab, the same box is only 298px wide. And there is plenty of space (at least on large resolution) so I don't see why it's not bigger.

**Comment by bpabiszczak** [comment]
New question/problem = new ticket.

**Comment by nikdejan** [comment]
:-) It is the same issue
