### ISSUE TITLE
[error] gitdeveloper.yetiforce.com

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2535]
Error in Detail View

Fatal error: Class 'Accounts_Detail_View' not found in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/modules/Leads/views/Detail.php on line 12

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/bb685a6db4909b3be57cbe75d19e5a0f93e3fe9c
