### ISSUE TITLE
[error] ConvertLead

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2536]
Permission denied
https://gitdeveloper.yetiforce.com/index.php?module=Leads&view=ConvertLead&record=114

![snimok21](https://cloud.githubusercontent.com/assets/15871611/11975139/d517221c-a97b-11e5-953f-833015151b67.JPG)

**Comment by rskrzypczak** [comment]
The error was most likely fixed in this commit (https://github.com/YetiForceCompany/YetiForceCRM/commit/b4bc9c288f85937ac3b0e43d5016f8c5301c8c9c), check if it still occurs .

**Comment by kjradv** [comment]
![image](https://cloud.githubusercontent.com/assets/15871611/13848490/1de5a12e-ec63-11e5-9a74-44a43855c4b2.png)
![image](https://cloud.githubusercontent.com/assets/15871611/13848513/41b59410-ec63-11e5-9eeb-494a0fd29a91.png)

**Comment by rskrzypczak** [comment]
Sorry, the dev version hadn't been reset back then. Try again now. :)
