### ISSUE TITLE
Merry Christmas!

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#2539]
![l](https://cloud.githubusercontent.com/assets/13310141/11978488/3d7254b6-a98c-11e5-837d-a4755159bffd.jpg)

The YetiForce team would like to thank all our community members, clients, and friends for your cooperation in 2015, and wish you and your families a joyful Christmas season spent in pleasant family atmosphere, as well as a lot of success and prosperity in the coming New Year.

The past year has been filled with a lot of hard work, but also satisfaction. Our common effort in creating YetiForce has helped us achieve spectacular effects. Not only did we celebrate our first birthday, but we also started developing faster than ever before.

Thank you all for your support.

We will come back with even more energy and motivation after Christmas.

Happy Holidays from the YetiForce team.

**Comment by nikdejan** [comment]
Merry Christmas!

**Comment by ChristopheLux** [comment]
Merry Christmas

**Comment by eptapsyxos** [comment]
Merry christmas and thank you very much everything

**Comment by florek41** [comment]
Merry Christmas and keep going :)

**Comment by kpaulaha** [comment]
Merry Xmas and a Happy New Year from the Land of Santa Claus

**Comment by muthumahendran** [comment]
Merry Christmas :christmas_tree: :santa: & Welcome to 2016! :gift:
