### ISSUE TITLE
[Bug] Fatal Error - Click letter icon in Email widget in Accounts

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2542]
Fatal error: Class 'AppConfig' not found in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/config/config.inc.php on line 18
gitdeveloper 2.3.824

**Comment by mariuszkrzaczkowski** [comment]
Bug has been corrected, concerned only the trial version.
Already working properly, you may continue to test :)
