### ISSUE TITLE
[Bug] - Fatal Error - Corporate email list - Send mail

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2544]
On this page: https://gitdeveloper.yetiforce.com/index.php?module=OSSMailView&view=List&mid=96&parent=84
When I click +Send mail (https://gitdeveloper.yetiforce.com/index.php?module=OSSMail&view=compose) I get following error:
Fatal error: Class 'AppConfig' not found in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/config/config.inc.php on line 18
Gitdeveloper 2.3.824

**Comment by nikdejan** [comment]
Same error when I try to open My mailbox

**Comment by nikdejan** [comment]
Now I see that this is the same error as #2542. This could be considered a duplicate.

**Comment by mariuszkrzaczkowski** [comment]
Bug has been corrected, concerned only the trial version.
Already working properly, you may continue to test :)
