### ISSUE TITLE
[Question] Single field updated, whole record tracked

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2545]
I'm using this code to programmatically update value of a field. 

$record = new $ModuleName();
$record->retrieve_entity_info($id, $ModuleName);
$record->mode = 'edit';
$record->column_fields['my_field'] = "My_string";
$record->save($ModuleName, $id); 

Field updates OK. Problem is that in ModTracker table not only field whose value is changed is memorized, but all record fields. It looks very ugly on Updates widget, where you can see a total mess of field values which are actually not changed. 
What do I need to do in order for tracker to track only field whose value is changed, like in ajax edit?
If this is not possible, please consider this as feature request.

**Comment by mariuszkrzaczkowski** [comment]
Your example is not compatible with yetiforce.
Try this code:
```php
$record = Vtiger_Record_Model::getInstanceById($recordId, $moduleName);
$record->set('email', $email);
$record->save();
```

**Comment by nikdejan** [comment]
The code you provided creates a copy of existing record and updates it. I need only to update one field in existing record.

**Comment by bpabiszczak** [comment]
All you need is above.

**Comment by nikdejan** [comment]
Does the code you provided work only with new S modules or with all modules? It creates duplicate with old modules.

**Comment by bpabiszczak** [comment]
with all.

**Comment by mariuszkrzaczkowski** [comment]
```php
$record = Vtiger_Record_Model::getInstanceById($recordId, $moduleName);
$record->set('email', $email);
$record->set('mode', 'new');
$record->save();
```

**Comment by nikdejan** [comment]
Yep. I found it myself too. But what I needed was $record->set('mode', 'edit'); because I wanted to update existing record.
Anyway, now it works as expected and Updates history looks beautiful. Thank guys.
The code I pasted in my first post wasn't invented by me but was somewhere in the code and I picked it up. I guess it is some old vtiger way of doing things. 
I like your new code much more. It is shorter and more intuitive. Easier to remember and reuse.
Since there are still many instances of this old code, should we report it and help you fix it, or you are going to do that on your own, regularly and systematically?

**Comment by paula-w** [comment]
We see hundreds of things that need improvements and fixes, and we keep working on them all the time. There are so many of them, that it will require months of work, therefore reporting individual cases doesn't really make much sense. Once we're done fixing the system we'll ask you to test the code. However, it would be best if people submitted ready fixes for us to accept.
