### ISSUE TITLE
[Improvement] Vendors need Summary View and Comments tab

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2546]
Yep.
Or do you intend to replace Vendors with Partners?

**Comment by bpabiszczak** [comment]
Q: Or do you intend to replace Vendors with Partners?
A: NO

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/2cce151042c19dbcccba286e0db6e0989d03eac5
