### ISSUE TITLE
[Improvement] Relate Corporate Email to Activity

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2550]
It would be nice if we would be able to add activity to particular email message. This is important because sometimes you get an email from your partner or customer which calls for some kind of activity. Activity related with particular mail may not be related to the ongoing process (Opportunity or Ticket) and that is why you need to be able to relate that particular email with activity.

**Comment by nikdejan** [comment]
Now when you introduced Subprocesses in activities... Email could be one of those subprocesses.

**Comment by bpabiszczak** [comment]
We're not planning to add this functionality in the nearest future.

**Comment by nikdejan** [comment]
That's too bad :-(
