### ISSUE TITLE
GitDeveloper

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2553]
Its only for me that its showing a blank page when i try to login on your GitDeveloper ? 

![teste123](https://cloud.githubusercontent.com/assets/16100495/12032553/571c8fc4-ae11-11e5-9f59-bcd123590837.png)

**Comment by nikdejan** [comment]
It's ok for me. Version 2.3.842

**Comment by TomaszQr** [comment]
Try using a different browser, preferably Chrome.

**Comment by yozhi** [comment]
![image](https://cloud.githubusercontent.com/assets/16100495/12032912/6f825b1c-ae15-11e5-8c12-57a790756e24.png)

**Comment by yozhi** [comment]
i forgot , it only happens with pt_br language, some

**Comment by rskrzypczak** [comment]
I can't see the problem. It looks okay for me for any language. Maybe the error has already been fixed?

**Comment by yozhi** [comment]
yes , was fixed
