### ISSUE TITLE
[Bug] Activitiy Hanging on Completed

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2554]
![task](https://cloud.githubusercontent.com/assets/13381850/12033253/6125bd50-ae21-11e5-8f1c-0575b0cb3ac1.gif)
Calendar module is a nightmare. It is so not standard. You cannot edit layout, add fields, add relation...
I hope that you plan to redesign it soon.

**Comment by eptapsyxos** [comment]
Activities counter on records summary view  doesn't updated too.

**Comment by ChristopheLux** [comment]
Just off topic question...what tool do you use to make those little animated screenshots

Thanks

**Comment by bpabiszczak** [comment]
https://screentogif.codeplex.com/

**Comment by ChristopheLux** [comment]
Thansk
