### ISSUE TITLE
[Bug] Activity - Multimodule reference fields

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2555]
When editing ToDo or Event, when I click + sign or search sign in Relation or Process field, popup opens, but parent window automatically goes from Edit Activity to Activity Detail.
gitdeveloper 2.3.842
Activities = Nightmare

**Comment by nikdejan** [comment]
I can see that @mariuszkrzaczkowski is intensively working on calendar module so I doesn't make sense to open new issues. I hope you don't mind if I just write here whenever I notice some problem related to calendar.
Now, this problem with multimodule reference doesn't exist anymore but fields Process and Subprocess are disabled.
When adding ToDo from Accounts module, account is not preselected.
When adding ToDo from Opportunity, process is not preselected (but the field is blocked anyway).
Opportunity module doesn't have Activities widget.

**Comment by bpabiszczak** [comment]
plese check now on gitdeveloper.

**Comment by nikdejan** [comment]
@bpabiszczak, now everything is OK except: "Opportunity module doesn't have Activities widget."
gitdeveloper 2.3.885

**Comment by nikdejan** [comment]
And fields Process and Subprocess are still disabled. They are OK when you add ToDo from Opportunity, but when you go to Calendar module and then add ToDo (from list view or from graphical view) fields Process and Subprocess are disabled. Same on Edit view.
