### ISSUE TITLE
[Improvement] Related activities count

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2560]
In related tab title we have a count of all activities. But number of all activities is not so important. More important is the number of activities that need to be done. So count display should be improved in one of this two ways:
1) display both, finished and unfinished (like 2/5, or 2(5), or 5(2))
2) display unfinished only

**Comment by eptapsyxos** [comment]
Absolutely logical

**Comment by florek41** [comment]
Totally agree !

**Comment by KatarzynaUlichnowska** [comment]
Hello,
there is a new field in the system and it's called "Event" and it shows when the oldest activity will happen [it is possible to see in the Accounts list which of their Events are overdue or which have no Events at all).
Currently, we don't plan to add any other mechanism.
