### ISSUE TITLE
Server Error: UID COPY: No folder Trash (Failure)

### ISSUE THREAD

**Issue by raphinology** [YetiForceCompany/YetiForceCRM#2561]
Hi There, 

When tinkering with YF I noticed the following error:

"Server Error: UID COPY: No folder Trash (Failure)"

as I was trying to delete a message within roundcube.

Any idea on what the issue is here?

**Comment by bpabiszczak** [comment]
http://www.roundcubeforum.net/index.php?topic=8869.0

You need set trash folder in roundcube settings.

![trash](https://cloud.githubusercontent.com/assets/10197525/12063159/2235e270-afaa-11e5-88f8-7f44f3248974.png)

**Comment by raphinology** [comment]
@bpabiszczak - Thanks for the clarification, makes perfect sense...
