### ISSUE TITLE
[BUG] PHP error when try to access OSSMail / Roundcube

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2566]
When accesing roundcube / OSSMail i've got:

```
Fatal error: Class 'AppConfig' not found in /home/yetiforce1/domains/gitdeveloper.yetiforce.com/public_html/config/config.inc.php on line 18
```

current gitdeveloper

**Comment by nikdejan** [comment]
This is a duplicate: #2542
Although your description is better :-)

**Comment by mariuszkrzaczkowski** [comment]
Bug has been corrected, concerned only the trial version.
Already working properly, you may continue to test :)
