### ISSUE TITLE
[Discussion] Mail Templates: How are they used?

### ISSUE THREAD

**Issue by raphinology** [YetiForceCompany/YetiForceCRM#2569]
Hi There,

With documentation being short on YF, I figured I would ask a few questions about how mail templates are being used. When composing a message in roundcube I can see a "grayed out" option for "templates" as seen here:

![Roundcube Compose Menu](https://cloud.githubusercontent.com/assets/1151245/12060656/54ead300-af42-11e5-81ba-9ced95fed91c.PNG)

When I create a new mail template in YF, logically, it would seem as if the template would appear as a template option while composing a mail within roundcube. This is a something that you'd typically see in Vtiger (although the vtiger internal mailer sucks). However, it seems as if the mail templates are only available for use using the internal mailer when using workflows. 

Am I missing anything there? Is workflow the only way we can utilize mail templates?

I've been tinkering around with YF, and I like what I see. Hopefully at somepoint we'll venture away from VT.

Looking forward to some commentary.

**Comment by florek41** [comment]
You need to set "Type" on creating new mail template to "Email message" and it will be available to select.

**Comment by raphinology** [comment]
@florek41 - Ah, that makes more sense, and it works as you've described. Thanks for the clarification.

**Comment by bpabiszczak** [comment]
Thank you @florek41
