### ISSUE TITLE
Nie odświeża się menu po zmianie przez Konfigurację

### ISSUE THREAD

**Issue by echemik** [YetiForceCompany/YetiForceCRM#2570]
Wersja 2.3.49 - środowisko Xampp for windows, PHP 5.6.15

Mimo że edytuję menu i odświeżam stronę to menu się nie zmienia. 
W bazie w tabeli yetiforce_menu dodają się nowe rekordy.

Ta sama instancja działała na w innym środowisku i było ok.

Prośba o pomoc - może wyłączenie jakiegoś cache pomoże?

**Comment by bpabiszczak** [comment]
Menu jast cachowane o ile dobrze pamiętam, ale wrzuca on tam z automatu. Czy błąd występuje na wersji testowej? Co pokazują logi?
