### ISSUE TITLE
[Discussion] - API - Web Service Documentation 

### ISSUE THREAD

**Issue by raphinology** [YetiForceCompany/YetiForceCRM#2571]
Hi There, 

I was hoping that someone might be able to point me in the right direction for using web service in YF. Is YF using the same web service as VT6? Is there a wiki of some sort that discusses how the two differ? Perhaps with some examples?

For those of you who have transitioned from VT6 to YF. How was the transition in regards to web service?

Looking forward to the thoughts.

**Comment by bpabiszczak** [comment]
Unfortunately, we don't have the documentation for the system, it's our New Year's resolution to change it in 2016, but it will take a few months to create proper documentation. Currently every programmer should be able to deal with building an external application. It's enough to take a look at the customer portal communication, as well as the new communication mechanism we build in portal2.

We don't use the web service built in vtiger, but we actually try to abandon it... The system itself uses web service in many places, and it shouldn't, so we're trying to "fix" that.

**Comment by raphinology** [comment]
I'll take a look at the customer portal and start from there. Thanks for the insight.
