### ISSUE TITLE
[PL] UI/UX - brak poziomego paska przewijania w środku listy

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2572]
Na początku problem:
Jeśli mamy moduł w którym na liście rekordów wyświelamy więcej pól niż mieści się na szerokości strony do dostajemy poziomy pasek przewijania który jest widoczny na początku i na końcu listy. Jeśli na stronie znajduje się większa ilość rekordów to będąc w połowie listy nie możemy przewinąć w poziomie bo pasek zniknął z pola widzenia.

Może dobrym rozwiązaniem byłoby aby scroll+nazwy kolumn przypinały się u góry, pod nagłówkiem w momencie kiedy miałby zniknąć z pola widzenia.

Pasek u góry:
![ux_horizonal_scroll_1](https://cloud.githubusercontent.com/assets/4824588/12074988/3a31f878-b171-11e5-85b3-f6766efd1344.jpg)

Pasek u dołu:
![ux_horizonal_scroll_2](https://cloud.githubusercontent.com/assets/4824588/12074991/3fa486cc-b171-11e5-9bdb-5c4b403ab125.jpg)

i paska brak w środku lisy:
![ux_horizonal_scroll_3](https://cloud.githubusercontent.com/assets/4824588/12074994/4b34d64a-b171-11e5-99b1-4e977269ce82.jpg)

**Comment by florek41** [comment]
@TomaszQr na Chrome działa ok, ale na firefoxie górnego paska (tego, który się przypina) nie ma w ogóle :)
Ponadto jest opcja, żeby także nazwy kolumn podążały za scrollem ?

**Comment by bpabiszczak** [comment]
O ile wiem, błąd poprawiony.
