### ISSUE TITLE
update package to ver. 2.3.873

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2574]
after upgrade there is error for all users 
![image](https://cloud.githubusercontent.com/assets/11491482/12091009/03ff328c-b2f4-11e5-86af-a1e75991601e.png)

**Comment by witer30** [comment]
additionall info is that when enter to admin part (by direct copy of the link to one of the module) it works..
my site url is ok...
Previouse version of upgrade 2.3.6xx works fine... 
any ida what can cause such issue...

**Comment by witer30** [comment]
Hi, I used new update package till version 2.3.934 and stil have this issue...
Only this time it display in English...
![image](https://cloud.githubusercontent.com/assets/11491482/12209482/7ac3f198-b653-11e5-9215-f9bf7e77f750.png)
no possibility to switch off CSRF protection in config file

**Comment by bpabiszczak** [comment]
Please check last version: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%202.x.x/2.3.0_to_2.4.0

**Comment by witer30** [comment]
I have to close as after reinstalation of developer version 2.3.950 it works...
