### ISSUE TITLE
{Feature} Ability to Add Icons On Custom Modules

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2575]
For the responsive layout and the submenus.
Add the ability to upload icons  (with specific dimensions as the other icons) on the custom module creation mechanism in settings.

**Comment by florek41** [comment]
Look at #2371

**Comment by eptapsyxos** [comment]
Thanks

**Comment by bpabiszczak** [comment]
Thank you @eptapsyxos
