### ISSUE TITLE
Brak możliwości logowania do GITMASTER

### ISSUE THREAD

**Issue by boolek** [YetiForceCompany/YetiForceCRM#2576]
Nie można zalogować się do testów na:
https://gitmaster.yetiforce.com/

![yeti](https://cloud.githubusercontent.com/assets/11717529/12102020/6caf2320-b338-11e5-8582-59b779aadbbc.png)

**Comment by bpabiszczak** [comment]
pewnie nikt nie utworzył użytkownika... sprawdzimy to jutro... najlepiej testować gitmaster-a bo na nim jesteśmy cały czas i jak coś nie działa to szybko znajdujemy.

**Comment by bpabiszczak** [comment]
admin/admin
