### ISSUE TITLE
Problem z wyświetlaniem zadania projektu - "nieterminowe"

### ISSUE THREAD

**Issue by boolek** [YetiForceCompany/YetiForceCRM#2577]
Jak ustawić zadanie projektu, aby wyświetlało się jako "Zlecone zadanie projektu", a nie "Zlecone (nieterminowe) zadanie projektu" w widgetach na stronie głównej?
Zadanie zaplanowane z datą realizacji na 2016-01-25 (dziś jest 2016-01-04).

![yeti](https://cloud.githubusercontent.com/assets/11717529/12102357/7f86dbda-b33a-11e5-988d-0dbedf157ee1.png)

**Comment by florek41** [comment]
W.g mnie to błąd - sprawdziłem na aktualnej wersji developerskiej i każde zadanie ląduje w "nieterminowych".

**Comment by bpabiszczak** [comment]
ale może w tłumaczeniu a nie tego, gdzie to ląduje... w wolnej chwili na to zerkniemy.

**Comment by florek41** [comment]
@bpabiszczak sprawdziłem i faktycznie - tłumaczenie jest odwrotnie opisane (zarówno PL jak i EN).
Po zmianie daty, na wcześniejszą niż dziś, zadanie ląduje w Zleconych.

![zadania projektu](https://cloud.githubusercontent.com/assets/4824588/12151869/9dd5d474-b4b1-11e5-8163-00b3d26879bb.JPG)
