### ISSUE TITLE
Brak możliwości edycji statusu zadania/spotkania/telefonu w module Kalendarz

### ISSUE THREAD

**Issue by boolek** [YetiForceCompany/YetiForceCRM#2578]
Komórka z wyborem statusu zadania/spotkania/telefonu w module Kalendarza jest nieaktywna, co powoduje przypisanie wartości domyślnej z "Domyślny status terminu" z ustawień użytkownika.
Czy jest możliwość ręcznej edycji tego z poziomu użytkownika?
![yeti](https://cloud.githubusercontent.com/assets/11717529/12102673/a2a26eb6-b33c-11e5-84e3-c039ff91dd3f.png)

**Comment by florek41** [comment]
taką możliwośc daje przycisk zaznaczony na czerwono:

![calendar](https://cloud.githubusercontent.com/assets/4824588/12109944/59d6e694-b387-11e5-8a46-6ce0bbde3724.PNG)

po kliknieciu otwera się okno z możliwością zmiany statusu (przeznaczone do tego przyciski)

**Comment by boolek** [comment]
Chodziło mi o możliwość edycji "planowane" / "do realizacji".
Jest to dostępne tylko w parametrach użytkownika dla admina.
Co ciekawe domyślnie macie we wszystkich wersjach ustawione "nieodbyte" - którego nie ma na liście do wyboru.

Jest do dość istotne dla widgetu "Sprawy bieżące" ze strony głównej, gdzie przy źle ustawionym parametrze przez admina termin nie będzie widoczny bez przestawienia w widgecie "Do realizacji" na "Planowane".

**Comment by bpabiszczak** [comment]
Zmiany statusów pól słownikowych są realizowane na dwóch poziomach [profile i uprawnienia w polu słownikowym].
