### ISSUE TITLE
visit.pl

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2579]
Does yetiforce is connected in any way with domain visit.pl?

**Comment by bpabiszczak** [comment]
NO, way u ask?

**Comment by reeid** [comment]
somebody here noticed apache process related to visit.pl what eats significant resources. 
It appear to show up after logging to yetiforce git instance. a bit strange so I asked to confirm preliminary,,,

**Comment by bpabiszczak** [comment]
This is a hosting company. Sure some of their customer install YetiForce.
