### ISSUE TITLE
[Bug]Calendar Missing Hours in Day and Week View

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2581]
As the title describes that the hours are missing from calendar on day and week view.
![calendarhoursss](https://cloud.githubusercontent.com/assets/6897502/12114844/1780d6ea-b3b6-11e5-89f2-45cd6b55fb49.jpg)

**Comment by bpabiszczak** [comment]
This can be configured in fullcalendar parameters. In our opinion the version without division into hours [they will appear next to each calendar event] looks better and we will keep it this way, but you can change it, check in the fullcalendar documentation what your possibilities are.
