### ISSUE TITLE
[Question]How Difficult it is for a UX like this-->

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2582]
Really i dont have an idea of programming etc
so i can not imagine how difficult is to implement an admin template like this
( http://webapplayers.com/inspinia_admin-v2.4/index.html )
seems to have a lot of widgets etc that matching our here in yetiforce.

a tone of features that will boost yetiforce user experience and productivity too.

Please @TomaszQr or someone who has previous experience on such things to give me some answers :-)

**Comment by bpabiszczak** [comment]
2 months of work and cost about 5,000 euros

**Comment by eptapsyxos** [comment]
I am in
