### ISSUE TITLE
[PL] Błąd relacji do modułu Dokumenty w module Kontrahenci

### ISSUE THREAD

**Issue by bwiatrni** [YetiForceCompany/YetiForceCRM#2583]
DetailView kontrahenta po kliknięciu w zakładkę Dokumenty:

{"success":false,"error":{"code":"SQLSTATE[42000]: Syntax error or access violation: 1064 Something is wrong in your syntax obok 'ORDER BY vtiger_crmentity.createdtime DESC LIMIT 0,20' w linii 1","message":"SQLSTATE[42000]: Syntax error or access violation: 1064 Something is wrong in your syntax obok 'ORDER BY vtiger_crmentity.createdtime DESC LIMIT 0,20' w linii 1"}}

**Comment by florek41** [comment]
Wersja ?
Nie udało mi się odtworzyć błędu na ostatniej wersji developerskiej https://gitdeveloper.yetiforce.com/

**Comment by bwiatrni** [comment]
2.3.49

**Comment by bpabiszczak** [comment]
Na test działa [2.3.49] na dev działa... zamykam. Proszę przeczytać to: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html
