### ISSUE TITLE
Projects work time summary

### ISSUE THREAD

**Issue by Alexvw78** [YetiForceCompany/YetiForceCRM#2586]
When i add a timecontrol in projects or project tasks the work time summary is not updated.

**Comment by bpabiszczak** [comment]
YF version?

**Comment by Alexvw78** [comment]
2.3.927

**Comment by rskrzypczak** [comment]
Working time conversion works correctly but with a delay.
Action for working time conversion is enabled by Cron.
![cron1](https://cloud.githubusercontent.com/assets/10221999/13070765/31bdc3de-d48f-11e5-8ac3-bcae2cdc33f7.jpg)
