### ISSUE TITLE
Q: Cant save mail client settings  [ver. 2.3.547]

### ISSUE THREAD

**Issue by Bergdahls** [YetiForceCompany/YetiForceCRM#2588]
I made a clean install after a server management. Now i cant save client settings but it worked before. I have checked a lot but i can't find the problem. No error info and all permissions seems to be ok and parameters. Is there any update i can try? This is so far only a "going wild" test server.

**Comment by bpabiszczak** [comment]
547 is develeper version. Now we have 916. Please update system.

**Comment by Bergdahls** [comment]
Thanks for info. I now run [ver. 2.3.917] It will be fun!
