### ISSUE TITLE
[bug] Documents

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2591]
Bug in Ducuments temp. Every time edited/saved, new ampersand entity added.

![docs](https://cloud.githubusercontent.com/assets/10330264/12166602/d4c81914-b52f-11e5-9874-95c81f31d324.png)

**Comment by rskrzypczak** [comment]
Hello, I did not notice the error you described.
![savedoc](https://cloud.githubusercontent.com/assets/10221999/12198100/3ab3455e-b60d-11e5-81d7-a4f6529c4d44.gif)

**Comment by kpaulaha** [comment]
I'' still there. Edit and save it more than once.
![documents](https://cloud.githubusercontent.com/assets/10330264/12201717/980cfdc8-b62e-11e5-9bac-602298574e4a.png)

**Comment by florek41** [comment]
I think you need to describe more precisly how to recreate this bug, because i've just testet it and it seems to be ok.

**Comment by kpaulaha** [comment]
Like this
![doc](https://cloud.githubusercontent.com/assets/10330264/12215326/0af0fb00-b6c0-11e5-8602-264ddf6b311f.gif)

**Comment by rskrzypczak** [comment]
I keep trying and I'm not able to recreate the error you described. Maybe it's the file?
If you can, send this file to the test mail (yetiforcetestmail@gmail.com) you can send it directly from https://gitdeveloper.yetiforce.com/index.php?module=OSSMail&view=index 
because it keeps being deleted from the documents module.

**Comment by kpaulaha** [comment]
Its just an simple pdf -file with one word in it. Uploaded to gitdeveloper.yetiforce.com also an other pdf with same result. It seems to happend with application/pdf, not with other.

![doc](https://cloud.githubusercontent.com/assets/10330264/12238858/ad847732-b88e-11e5-92ec-f6a83b83eafb.png)

**Comment by bpabiszczak** [comment]
Please check other browser.

**Comment by kpaulaha** [comment]
I have tested with firefox/chrome/safari. Ie/edge I do not use. Well the problem must be at this end if nobody else have the same. Suppose you could close this ticket.

**Comment by kpaulaha** [comment]
I have tested with firefox/chrome/safari. Ie/edge I do not use. Well the problem must be at this end if nobody else have the same. Suppose you could close this ticket.

**Comment by florek41** [comment]
have you try to sen this document to yetiforcetestmail@gmail.com ?
maybe it is file-specific problem - worth to check it.

**Comment by bpabiszczak** [comment]
We have this file. For me work ok.
