### ISSUE TITLE
mobile scolling 

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2594]
mobile scrolling needs improvments
Its not running smoothly.
Lags.
Tested on mozila mobile meizu m2 note.
Compared to make your cloud responsive theme.

**Comment by TomaszQr** [comment]
Can you tell me where exactly the error occurs ?

**Comment by eptapsyxos** [comment]
Is not an error..just the scrolling is too laggy.i will try to make a gif or a video to show you tomas
