### ISSUE TITLE
menu renaming

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2596]
Do change as following please:
Single orders > Sales Orders
Periodically recurring orders >   Recurring Sales Orders

**Comment by reeid** [comment]
Also:
Quote enquiries > Sales enquiries 
Requirements Cards > Sales requirements

**Comment by MaciejStencel** [comment]
Hi reeid!

Your naming convention seems about right :)

Thanks, it is already changed in the system.

Here is the revision: https://github.com/YetiForceCompany/YetiForceCRM/commit/ad4c1628cef01b73e364f99b9a0ee0240c68199e

**Comment by reeid** [comment]
Thanks guys, Please also change "Quotes" to "Quotations".
Quotes are a bit different story :-)

**Comment by bpabiszczak** [comment]
Please open new issue.

**Comment by waran70** [comment]
Why open new issue? It seems to be the same thing O.o
I would just correct error instead of writing four words.... come on....!
