### ISSUE TITLE
[PL][Design bug] Błąd wyświetlania nowego panelu powiązań maila w Roundcube

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2601]
![mail_relation](https://cloud.githubusercontent.com/assets/4824588/12209268/261738e0-b652-11e5-9732-556222082495.JPG)

- Listy rozwijane i przyciski są wyższe niż cały pasek w którym się znajdują
- Zbyt duże odstępy pomiędzy opisami a elementami nawigacyjnymi których dotyczą (list/przyciski) i jednocześnie zbyt małe odstępy pomiędzy kolejnymi opisami bardzo utrudniają nawigację - są mylące - nie jest jednoznaczne do czego się odnoszą (np. spójrzmy na "Procesy")
- Treść maila wchodzi na pasek z detalami maila

Testowane na FireFox

**Comment by bpabiszczak** [comment]
Dziękuję... pasek jeszcze nie jest skończony [będzie skończony w poniedziałek]. Zaszły tam spore zmiany, mam nadzieje, że się wam spodobają.
