### ISSUE TITLE
[Question] Scanning large number of emails

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2605]
My gmail inbox is more than 10gb in weight. Would it be possible to transfer all these emails to YF database by using YF MailScanner?

**Comment by bpabiszczak** [comment]
At the moment we are dealing with one client's 50 inboxes, the number of all the emails exceeds 650.000, the attachments weigh 80GB. The system works well.

**Comment by nikdejan** [comment]
wow! that's fantastic!
