### ISSUE TITLE
[Translation] My Mailbox - YT Action Bar

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2606]
Almost all the labels untraslated.
![untitled](https://cloud.githubusercontent.com/assets/13381850/12217994/c8e6204e-b711-11e5-9331-bec19f43ed82.png)

**Comment by bpabiszczak** [comment]
Fixed. Please check the latest version.

**Comment by nikdejan** [comment]
cool
