### ISSUE TITLE
invoice export to excel - invoice no = 0

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#2609]
Bug in invoice Export to excel feature:

With a custom invoice filter, the field "invoice no" is exported  wit "0" as value in all columns.

all other columns seems to be exported correct.

![invoice-no-zero](https://cloud.githubusercontent.com/assets/10504154/12231947/83686d42-b85b-11e5-8ee1-a8d29c0ce66d.png)

**Comment by bpabiszczak** [comment]
2.3.49?

**Comment by bpabiszczak** [comment]
The invoice module will be written from scratch in the new version. After we release the new version [2.4] please verify the problem once again.
