### ISSUE TITLE
Pionowa oś czasu w Kalendarzu

### ISSUE THREAD

**Issue by boolek** [YetiForceCompany/YetiForceCRM#2612]
W wersji 2.3.969 (gitdeveloper.yetiforce.com) nie ma pionowej osi czasu dla widoku kalendarza "tygodniowy" i "dniowy".
W wersji 2.3.49 (test.yetiforce.com) ta funkcjonalność była.

Dodanie nowego zadania/spotkania/telefonu z osią czasu można było realizować poprzez przeciągnięcie w kalendarzu między wybranymi godzinami, a te automatycznie były wpisane w formularzu.
W aktualnej wersji developerskiej za każdym razem trzeba ręcznie wpisywać w formularzu godzinę rozpoczęcia i zakończenia, co powoduje moim zdaniem wydłużenie czasu dodania terminu prawie dwukrotnie.

W 2.3.969 przy dwóch terminów w jednym czasie np. deleguję komuś zadanie, albo podglądam kalendarz pracownika i swój - wydarzenia są dodawane pod sobą zamiast obok siebie (przy tej samej godzinie).
Sugerowałbym dodanie osi czasu i troszkę miejsca obok wydarzeń, tak aby można było dodać nowe w tym samym czasie (przez przeciągnięcie przez kalendarz).
Moim zdaniem fajnie funkcjonuje to w kalendarzu Google nawet przy kilku osobach (kalendarzach).
![yeti-calendar](https://cloud.githubusercontent.com/assets/11717529/12263491/ce0bb212-b92f-11e5-8736-37f4b6a3af19.png)

**Comment by bpabiszczak** [comment]
My bazujemy na bibliotece fullcalendar. Za pomocą jej konfiguracji, możesz sobie dowolnie manipulować widokiem kalendarza [polecam dokumentacje fullcalendar]. Domyślnie był widok taki jak opisujesz, ale dla klientów którzy mieli więcej wpisów [czasem po 30-40 dziennie] widok był całkowicie nieczytelny [widok dnia i tygodnia], dlatego zmieniliśmy domyślną konfiguracje i dlatego nie planujemy tego zmienić. 

Zmiana tego widoku z tego co pamiętam, to kwestia 1/2 parametrów w 2/3 plikach konfiguracyjnych kalendarza [po jednym dla każdego modułu który z tego korzysta a jest ich 3].
