### ISSUE TITLE
[BUG] Manual mail import from roundcube

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#2614]
![mim2](https://cloud.githubusercontent.com/assets/10221999/12266996/4fece984-b946-11e5-911b-a94f897213eb.gif)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/6602e6333453068ecc2305e714f124b3920528c9
