### ISSUE TITLE
[Improvement] Requesting Annual holiday entitlement

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2615]
A module called Requesting Annual holiday Entitlement related with the existing module Annual holiday entitlement or incorporate with Annual holiday entitlement, that The CRM users can request holidays to Human resources department and then they can accept , change the proposal days, propose new days or simple reject. What do you think ?

**Comment by paula-w** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in [this article](https://yetiforce.com/en/github/issues/206-system-development-ideas.html).
