### ISSUE TITLE
[Bug/Improvement] MailScanner - Fields for email bind

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2616]
Bug: 
Settings>MailScanner>Email Accounts Tab - Actions field. There are options like Bind Partners, Bind competition, Bind Potentials and others.
Settings>MailScanner>General configuration Tab - Search email configuration fields. Missing Potentials, Partners, Competition.
Improvement:
We don't need this two fields. We need only one.
In actions field we could have Bind Potential Primary Email, Bind Potential Secondary Email etc.
Maybe this is not the right moment, because you just finished MailScanner reconstruction, but it's now that I got the idea.

**Comment by mariuszkrzaczkowski** [comment]
All mail fields from the system are always available in the folder configuration. If someone is missing a field it's enough to make a new one and select it in the field configuration for scanning.
Added missing fields in Parners and Competitors modules https://github.com/YetiForceCompany/YetiForceCRM/commit/94e7d0653d4e46d9c82b79079d09e28830c2d280
In the Opportunity module there's no mail address field and it won't be added. Records in this module are related basing on prefixes.
