### ISSUE TITLE
[PL][Improvement] Mail scanner - attachments Folder

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2617]
Widzę, że pracujecie nad skanerem maili. Przy tej okazji może będzie opcja dodania możliwości aby skaner zapisywał załączniki maili do określonego folderu w dokumentach.
Aktualnie zapisywane są w katalogu domyślnym, a dobrze byłoby je rozdzielić ponieważ ciężko przedzierać się przez moduł dokumentów wśród załączników mailowych.
Ew zapisywanie ich w innym miejcu, dostępnym tylko dla maili, żeby nie mieszać dokumentów - w których dobrze żeby były przechowywane ważne pliki, oraz załączników które często są zbędne.

[EN]
I see that you are working on Mail Scanner. It might be an opportunity to add the possibility to save  mail attachments to a specific folder in documents module.
Currently they are stored in the default directory, and it would be good to split them because its hard to find anything in this module because of attachments.
If necessary, store them in a different place, which is available only for e-mails and do not mix with documents - which were we store important files and attachments are often unnecessary there.

**Comment by witer30** [comment]
super pomysł był już zgłaszany dawno temu...

**Comment by bpabiszczak** [comment]
To nie takie proste... wrócę do tego tematu jak skończymy pocztę [to co mamy zaplanowane], bo to co opisujesz musi po części się połączyć z czymś takim jak webdav i z czymś takim jak wyszukiwanie kontekstowe...

**Comment by florek41** [comment]
W branżach w których praca głównie opiera się na mailach + załączniki to taki podział może okazać się dużym ułatwieniem - szczególnie jeśli dodamy możliwość podejrzenia załącznika (wystarczą pliki graficzne + pdf) bez potrzeby pobierania - tzw. lightbox. W tej chwili maile widoczne są na stronach modułów ale zerknięcie na załącznik to spora procedura: otwarcie szczegółów maila - pobranie załącznika, otworzenie go lokalnie.

Druga sprawa to sytuacja w której do np. maila chcemy dodać plik z CRM i otwieramy moduł z załącznikami które dostaliśmy zmiksowanymi razem z powiedzmy wzorami dokumentów itp.

**Comment by mariuszkrzaczkowski** [comment]
Changed documents directory https://github.com/YetiForceCompany/YetiForceCRM/commit/7532307c4961d81450f054e5b44472ec2f74fe22
