### ISSUE TITLE
[PL][Improvement] Enter key in comments

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2618]
@TomaszQr dodał do modułu komentarzy możliwość zatwierdzania ich enterem - właśnie zauważyłem na gitdeveloper takie komentarze ;) : 
![comments_enter](https://cloud.githubusercontent.com/assets/4824588/12277296/e52cbd24-b97a-11e5-804e-e010cd29b8ef.JPG)

Może przy SHIFT+ENTER będzie dodawać nam łamanie wiersza ? Tak jest np w Wordzie, tinyMCE itp.
Dodatkowo świetnie byłoby powiększające się automatycznie pole komentarza jeśli jego długość przekracza jedną linię.

[EN]
@TomaszQr add to comments module possibility to confirm by enter key - i've just noticed comments on gitdeveloper ;) : 
![comments_enter](https://cloud.githubusercontent.com/assets/4824588/12277296/e52cbd24-b97a-11e5-804e-e010cd29b8ef.JPG)

Maybe SHIFT+ENTER will be good for line break ? Like that it works in MS Wordzie, tinyMCE etc.
Additionaly will be great if the textarea will automaticly resize when comment in longer than one line.

**Comment by bpabiszczak** [comment]
Nie będzie zatwierdzania ich enterem...

**Comment by florek41** [comment]
W tej chwili jest, czyli zostanie to usunięte ? :)

**Comment by bpabiszczak** [comment]
TAK

**Comment by florek41** [comment]
Wszystko jasne, dzięki !
