### ISSUE TITLE
[PL][BUG?] Możliwość dodania pola w kalendarzu

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2619]
Przy edycji pól mamy możliwość dodania dodatkowego pola w kalendarzu oraz usunięcie pola "Zadanie powiązane" - wygląda na pozostałość po ostatnich zmianach, ale pytanie czy na pewno tak ma zostać ?
![kalendarz_nowe pole](https://cloud.githubusercontent.com/assets/4824588/12277770/83d1e894-b97d-11e5-8c9e-0c11e1ec3e6c.JPG)

Tak czy inaczej - świetnie byłoby mieć możliwość dodania dodatkowego bloku/pól do kalendarza.

**Comment by bpabiszczak** [comment]
A nie lepiej zbudować tak całą zakładkę, aby nie trzeba było dodawać nic? Po drugie kalendarz jest dość wrażliwy, bo działa z synchronizacją DAV, więc musi być ograniczony. Nadal jest możliwość jego modyfikacji ale z poziomu prostych skryptów vtlib.

**Comment by florek41** [comment]
Oczywiście że tak byłoby najlepiej - tylko czy da się zbudować tak, żeby zaspokoić potrzeby społeczności ?
Jeśli chodzi o synchronizację - oczywiście pola standardowe zostają, ale po dodaniu pól użytkownika nie będą one synchronizowane i zostaną widoczne tylko w CRM.

Tak jak pisałem wyżej - aktualnie właśnie jest możliwość dodania pola do kalendarza (w bloku "Poziązany z") - jak na screenie - i wygląda w.g mnie jako nie do końca celowy zabieg - chyba, że tak ma zostać ?

**Comment by bpabiszczak** [comment]
Celowy nie, tak domyślnie jest w Vtiger, na sztywno oni zaszyli [wyłączyli] dla konkretnych nazw bloków mechanizm dodawania pól [bo on tam jest] a my dodaliśmy nowy blok z poziomu skryptu i niezauważyliśmy tego, że w panelu mamy opcje. 

Samo dodawanie pól nie jest problemem, gorzej, gdy ktoś oznaczy pole jako wymagane... albo jeszcze coś wymyśli, co nie przychodzi mi jeszcze do głowy.
