### ISSUE TITLE
[PL][Question] Pole produktowe - Cena zakupu

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2621]
W polach produktowych mamy możliwość wyświetlenia ceny zakupowej, ale przy dodawaniu produktu nie widzę możliwości dodania takiej wartości. Gdzie powinienem wprowadzić tą cenę ?
![buying price](https://cloud.githubusercontent.com/assets/4824588/12279146/cb87441a-b985-11e5-9d96-a3d172531dd2.JPG)

**Comment by bpabiszczak** [comment]
Nie wiem czemu to pole jest nieedytowalne, ale w pierwszej wersji [chyba, nie wiem na ile nam czasu starczy] będzie wprowadzane ręcznie a docelowo będzie pobierało z dokumentu kosztowego.

**Comment by florek41** [comment]
Chciałem zapisać rekord z 0 ceną zakupu ale niestety validacja nie przechodzi ponieważ "Akceptuje tylko dodatnie liczby".

**Comment by bpabiszczak** [comment]
zawsze pole można wyłączyć... to dopiero wersja wstępna. Trochę potrwa za nim będzie gotowy ten moduł.

**Comment by florek41** [comment]
Zdaję sobie z tego sprawę i dla tego zgłaszam to tutaj :)

**Comment by witer30** [comment]
A nie powinno być pobierane bezpośrednio z produktu tak jak była informacja wcześniej o zmianach w wersji 2.4....?
Według wcześniejszych wypowiedzi w tym temacie to wprowadzjąc produkt miało pojawić się to pole i oferta oraz kalkulacje miały pobierać sobie koszt zakupu produktu. To samo miało być z marżą na produkcie, wprowadzana w karcie produktu i pobierana przez wszystkie moduły...

**Comment by bpabiszczak** [comment]
Napisz to jeszcze raz, ale tym razem po polsku :]

**Comment by witer30** [comment]
Błażej, może skrótowo napisałem...
chodzi o pole zakup i marża, według wcześniejszych rozmów wypowiadałeś się że te pola będa pobierane przez każdy modół z produktu bo wprowadzając nowy produkt bedziemy wprowadząc wartość marży (Czy będzie ona obliczana na podstawie ceny sprzedaży i zakupu) oraz cenę zakupu... 
to miałem na myśli...

**Comment by bpabiszczak** [comment]
Obecnie zakup wprowadzany jest ręcznie, marża wylicza się z automatu na podstawie wprowadzanych wartości. Nie planujemy na razie tego zmieniać, gdy dodamy nowe moduły, to zakup będzie pobierany z dokumentu zakupowego lub z dokumentu zapytania do dostawcy.
