### ISSUE TITLE
Conditional layout

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#2624]
http://www.vtexperts.com/extension/vtiger-conditional-layouts/

Such a useful extension can be implemented in YF

**Comment by iRainSystem** [comment]
We are waiting for the blocks too  👍 
for example: https://www.vgsglobal.com/extensions/vtiger-dynamic-blocks/

**Comment by bpabiszczak** [comment]
We are planning to add such a functionality in the future [if a client orders a process like this]. 
You can read more about ideas for new YetiForce features in this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
