### ISSUE TITLE
[Question] Invoices 

### ISSUE THREAD

**Issue by yozhi** [YetiForceCompany/YetiForceCRM#2629]
Sorry , but i couldn't find it by my self , so i decided to ask you guys, which module corresponding with old invoice module ?

**Comment by florek41** [comment]
As I know Invoice module is under construction and will be added soon.

**Comment by bpabiszczak** [comment]
True. Thank you @florek41

**Comment by yozhi** [comment]
ok i was just confused , because yetiforce almost on version 2.4 and i couldn't see anything about invoices module
