### ISSUE TITLE
[BUG] Sending mail - the buttons to get mail addresses don't work

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#2630]
![getmailaddress2](https://cloud.githubusercontent.com/assets/10221999/12291529/294aec84-b9e8-11e5-8f01-b14e43ee10f5.gif)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/5c7c38f638d085e8cd51be470b8d98f61d26d9b1
