### ISSUE TITLE
[BUG] Import broken if a field match the name ID

### ISSUE THREAD

**Issue by networkpanic** [YetiForceCompany/YetiForceCRM#2633]
I found a bug while importing some data

If a precreated field matches the name ID the import will fail

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html

**Comment by networkpanic** [comment]
sry for missing infos, latest dev version
i create a field that names ID, if i try to import data from csv into this field the import stops at this point
