### ISSUE TITLE
[BUG] Automatic E-Mail export outputs non UTF-8 encoded csv

### ISSUE THREAD

**Issue by networkpanic** [YetiForceCompany/YetiForceCRM#2638]
Automatic E-Mail export outputs non UTF-8 encoded csv

I tried to set the output format in libraries/PHPExcel/PHPExcel/Writer/CSV.php but no change happens

a option to set the delimiter would be nice

**Comment by KatarzynaUlichnowska** [comment]
Hello,
could you please explain in details what you mean? We don't quite understand what you would like to achieve.
