### ISSUE TITLE
[Bug] Gitdeveloper broken - Fatal error

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2639]
https://gitdeveloper.yetiforce.com
Fatal error: Directive 'allow_call_time_pass_reference' is no longer available in PHP in Unknown on line 0

**Comment by nikdejan** [comment]
Now it's ok.

**Comment by nikdejan** [comment]
Now it happens again

**Comment by bpabiszczak** [comment]
For me work ok.

**Comment by reeid** [comment]
use porntab or clear browser cache

**Comment by nikdejan** [comment]
I tried deleting cache and it doesn't get any better.
When I type https://gitdeveloper... then it's ok. If I type http://git.. or only git... then I get the error.
From what I read on the internet, this error is well known and it is not browser connected. It appears if you have 'allow_call_time_pass_reference' in php.ini, with php version newer then 5.3. Please check php.ini and comment out 'allow_call_time_pass_reference' if it's there.

**Comment by florek41** [comment]
I have the same problem.
On gitdeveloper, gitmaster and test too.
Different browser/pc/system.

**Comment by nikdejan** [comment]
Now it doesn't work neither with http nor with https.

**Comment by florek41** [comment]
and now everything is OK - wired!
