### ISSUE TITLE
campaign's list of Accounts status can not be modified

### ISSUE THREAD

**Issue by limor1** [YetiForceCompany/YetiForceCRM#2643]
If I understand the purpose of the Campaign module, it is to make lists of Accounts or Leads or Contacts and call/email each one and track progress.

However, there is no way to see what is the status of each of the leads/accounts/contacts in the campaign. So there is no way to visualize the progress of the campaign.

There is a field called "Status" but it can not be edited. Is this field intended for tracking the lists status ?

![image](https://cloud.githubusercontent.com/assets/10811472/12362743/e6f5f05a-bbbc-11e5-9f80-65df8aef9261.png)

**Comment by bpabiszczak** [comment]
I don't know what this field is used for, because we don't use this module, our client's don't use it either, we inherited it from vtiger.

We're rebuilding sending mails in this module [it doesn't work like it should], ultimately – from the perspective of the following months – this module will keep changing and being expanded, in order to make it a thought through and useful functionality.

**Comment by limor1** [comment]
Glad to hear you are rebuilding this "Campaign" module.
The most important feature:
1) good filtering of leads/contact/account sets - also based on associated products and other tags
2) link back the campaigns to the contact/account (currently there is no back link)
3) good tracking and visualization of *status* of the campaign set - when you have 5000 leads in one campaign and a group of sales people, you want to be able to see how well the campaign performed and how well each sales person performed

Thanks!

**Comment by bpabiszczak** [comment]
In the last days we have rebuilt the mechanisms quite significantly, we also checked the status field which is going to be modified from the email scanner level [we will add such info in a few days]. There will be no new changes related to the mailing campaign until 2.4v. We plan it for 2.6.v or 3.0.v.
