### ISSUE TITLE
[ISSUE] Settings Shortcuts ver. All

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2649]
How do I create shortcuts?

![animation 186](https://cloud.githubusercontent.com/assets/1402355/12370779/d694eb02-bc3f-11e5-910c-263e4a7d473a.gif)

**Comment by paula-w** [comment]
We don't really know what you want to achieve. Can you describe it somehow?

**Comment by paula-w** [comment]
Okay, we figured out what you wanted to show us. 
Right now there's no option to add shortcuts. We will add this option soon though.

**Comment by rskrzypczak** [comment]
For now
![shortcuts](https://cloud.githubusercontent.com/assets/10221999/14584295/257a5e9e-0440-11e6-87f2-468ebb492442.gif)
