### ISSUE TITLE
[bug] Campaign

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2654]
Calendar icon does not open the calendar in Campaigns v. 2.3.1013

![campaigns](https://cloud.githubusercontent.com/assets/10330264/12386979/192eba4a-bdd2-11e5-83ed-19840025e394.png)

**Comment by rskrzypczak** [comment]
related https://github.com/YetiForceCompany/YetiForceCRM/issues/2642

**Comment by kpaulaha** [comment]
Ok, had not noticed

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/9f8e84f5bd7f4f9837567c31cb1a872d56e1505e
