### ISSUE TITLE
[question] Taxes

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2659]
Where to edit default values for taxes (vat, sales, service)? Or are they going to be removed in the way of new Taxes function? Why do not Services have similar?
![products](https://cloud.githubusercontent.com/assets/10330264/12390601/3c9de768-bdea-11e5-8be5-b1c41c13d6b0.png)

**Comment by ChristopheLux** [comment]
Hackin the tax question

Here you say you can have global individual regional
![taxe_config1](https://cloud.githubusercontent.com/assets/11833461/12509596/d7eff230-c103-11e5-8f28-b0857c86e22f.png)

but when creating tax you can not tell if they should be global or regional or...
![taxe_config2](https://cloud.githubusercontent.com/assets/11833461/12509612/ee60c24c-c103-11e5-80fa-ec72ea4342a8.png)

Thanks

**Comment by TomaszQr** [comment]
All taxes set in the admin's panel are global taxes.
Group taxes are taxes that are set for a particular account's product.
Individual tax is set individually for particular records.
Regional tax is related to the tax that has been set for an account.

**Comment by ChristopheLux** [comment]
Thanks @TomaszQr for your explanation....
