### ISSUE TITLE
dataPicker

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2661]
datepicer in ful form not worked
![gif1](https://cloud.githubusercontent.com/assets/15871611/12392754/662d4462-be02-11e5-99d2-794ace12ce13.gif)

**Comment by kjradv** [comment]
#2642

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/9f8e84f5bd7f4f9837567c31cb1a872d56e1505e
