### ISSUE TITLE
help icon

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2665]
when editing icons aid box "Show in" preserved and field tips - no
![gif1](https://cloud.githubusercontent.com/assets/15871611/12443679/9b041602-bf6a-11e5-8f7e-b74c0144acdd.gif)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/f3bf42dd516993ca040fc6a6c6f41cdc86be25aa
