### ISSUE TITLE
[Request] project template task dates

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2666]
The project template system is a very cool feature. But there is one request:
When adding a task, the dates can be chosen from the record creation day.
For us most of the time we have a Milestone / Project end date and calculate back when tasks should be started to be finished on time. 
Would it be possible to add an option x days from project end date?

**Comment by paula-w** [comment]
Hello,
Project templates are a very old functionality that must be written from scratch. Unfortunately, right now we don't have enough time for that, and therefore we're not planning to expand this mechanism.

**Comment by zebrahosting** [comment]
Fair enough, thanks for explaining. For us it was perfect (with 25 similar projects with about 50 of the same tasks each) but might be less important for others. We can deal with the current setup and will do the dates all manually.

**Comment by waran70** [comment]
Make sure it will not be removed in next version.... :-) nobody knows....

**Comment by zebrahosting** [comment]
LOL, had the same thought.....
