### ISSUE TITLE
Duplicate error

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2667]
When you combine duplicate error:
```
Uncaught ReferenceError: Vtiger_List_Js is not defined
```
![gif2](https://cloud.githubusercontent.com/assets/15871611/12445466/78c40790-bf75-11e5-9392-beccee11ce53.gif)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/46001f888bffc66c354a6228c87d5bea83810598
