### ISSUE TITLE
[design] Firefox ESR

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2669]
menu bug in Firefox ESR 38.5.2
![gif2](https://cloud.githubusercontent.com/assets/15871611/12450084/ac2d38c8-bf92-11e5-9cc6-5b65bd1bb51a.gif)

**Comment by kjradv** [comment]
\layouts\basic\skins\twilight\style.css
```
.leftPanel  .slimScrollDiv{
	/*overflow: unset !important;*/
	position: static !important;
}
```

**Comment by TomaszQr** [comment]
Can you check now if the error still occurs ?

**Comment by kjradv** [comment]
![gif3](https://cloud.githubusercontent.com/assets/15871611/12817844/366d4d24-cb65-11e5-9580-672d92162a4b.gif)

**Comment by mariuszkrzaczkowski** [comment]
Can you give me some more info about the hardware and the operating system, like the system, version, resolution for example.

**Comment by kjradv** [comment]
it happens in Firefox ESR 38.7.1 (https://www.mozilla.org/en-US/firefox/organizations/faq/)
This problem occurs only in the browser, in principle, it is not critical

**Comment by bpabiszczak** [comment]
Please check the latest versions.
