### ISSUE TITLE
caldav

### ISSUE THREAD

**Issue by negodiy** [YetiForceCompany/YetiForceCRM#2670]
Dear colleagues!
Trying to connect to caldav and carddav and having problems.
When connecting through http and so on

<code>
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>2.1.3</s:sabredav-version>
<s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
<s:message>Incorrect username</s:message>
</d:error>
</code>

**Comment by florek41** [comment]
Please give us more details.
https://yetiforce.com/en/developer-documentation/bugs/126-issues.html
System version, how you connect to dav, what device, what login and pass itp. ?

Now i can only say that you have wrong username.

**Comment by negodiy** [comment]
version 2.3.49
connect via browser http://site.net/api/dav.php
enter login and key

**Comment by negodiy** [comment]
please give exact instructions on connecting DAV

**Comment by mariuszkrzaczkowski** [comment]
Not enough data to verify the problem, describe what exactly you set up and what they show logs?
