### ISSUE TITLE
[Bug] External email client - empty email subject

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2671]
In https://github.com/YetiForceCompany/YetiForceCRM/commit/cc4f1ef5dee6c2f8968bb1aaa197fd4ab4708376 @mariuszkrzaczkowski  added support for external email client, which is great.
When I click email icon in Email list widget I get an empty email subject or, in case I'm doing it from Opportunities, I get only s-sp1, without Opportunity subject added.

**Comment by paula-w** [comment]
In which module was the subject empty?

**Comment by nikdejan** [comment]
In Accounts module subject is completely empty. (When I think again, maybe it should be empty?)
In Opportunities module it only has S-SP1.

**Comment by paula-w** [comment]
Hello @nikdejan 
The subject in Accounts module should remain empty, and the bug in the Opportunity module has been fixed by Mariusz in here: https://github.com/YetiForceCompany/YetiForceCRM/commit/ee58a86048f7466d6d73de2a5575b254e56ca418

**Comment by nikdejan** [comment]
Thanks!

**Comment by nikdejan** [comment]
I checked again and there is still one small problem. 
In Opportunities module, when I click Reply (or Reply All, or Forward) I get compose email windows with subject populated. But field is populated with only subject of a message I am replying to. Instead of "Some message subject text", subject field should be populated with: Re: Some message subject text [S-SP1].
It should be as it is when we use Roundcube.
