### ISSUE TITLE
[Improvement] Use external email client to Reply and Forward message

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2672]
Now external email client can be used only when you click email icon in Email list widget. 
The same logic should be implemented to Reply, Reply All, Forward buttons in the same widget.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/291930dea88a7bb577a45fd27a6d052385d1b290
https://github.com/YetiForceCompany/YetiForceCRM/commit/b574277ac01763585603d2b931db6e4ab317e4f6
