### ISSUE TITLE
[improve] chat

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2673]
perhaps for a chat is to make notification of a new message?
as a variant of HTML 5 Notifications API, or you can do for example reminder

**Comment by kjradv** [comment]
https://github.com/alexgibson/notify.js

**Comment by florek41** [comment]
look at #1592 :)

**Comment by kjradv** [comment]
ok )
however, I have almost completed the notification chatting ....

**Comment by paula-w** [comment]
Currently we're not planning to introduce any changes in the chat module because we don't have enough time for that.

**Comment by kjradv** [comment]
I forgot to share notifications ...
/libraries/AJAXChat/js/chat.js
find: playSoundOnNewMessage
`
	playSoundOnNewMessage: function(dateObject, userID, userName, userRole, messageID, messageText, channelID, ip) {
		if(this.settings['audio'] && this.sounds && this.lastID && !this.channelSwitch) {
			switch(userID) {
				case this.chatBotID:
					var messageParts = messageText.split(' ', 1);
					switch(messageParts[0]) {
						case '/login':
						case '/channelEnter':
							this.playSound(this.settings['soundEnter']);
							break;
						case '/logout':
						case '/channelLeave':
						case '/kick':
							this.playSound(this.settings['soundLeave']);
							break;
						case '/error':
							this.playSound(this.settings['soundError']);
							break;
						default:
							this.playSound(this.settings['soundChatBot']);
					}
					break;
				case this.userID:
					this.playSound(this.settings['soundSend']);
					break;
				default:
					this.playSound(this.settings['soundReceive']);
					break;
			}
			//Notification
        var permission,
                timer = setTimeout(function () {
                    permission = "default"
                });
        Notification.requestPermission(function (state) {
            clearTimeout(timer);
            permission = state
        });
        var notify = new Notification(userName, {
            tag: channelID,
            body: messageText
        });
        notify.onerror = function () {
            console.log("permission state = default or denied");
        };
		}
		
	},
`
