### ISSUE TITLE
Zaokraglanie ... cen

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2674]
Witam, czy jest to błąd systemu , czy mogę gdzies ustalić format przeliczania - zaokraglania cen... 
Widzę ,że niby tabele są ok.. , gdzie mogę znaleźć funkcję obliczania ceny po rabaci , i po podatku...

przykladowo: netto 102, rabat 1% - powinno być = 100,98 , zamiast 101

**Comment by zimart** [comment]
hmm.. nikt nie podpowie ? :) czy jest to bug , czy funkcja gdzieś do ustawienia ? :)

**Comment by witer30** [comment]
A nie masz ustawine 0 w ilości miejsc po przecinku 
https://gitdeveloper.yetiforce.com/index.php?module=Users&parent=Settings&view=Edit&record=5

**Comment by zimart** [comment]
Nie.. sprawdzilem wczesniej..

**Comment by bpabiszczak** [comment]
Nie wiele wiadomo z tego postu... 
Jakiej wersji to dotyczy, czy można odtworzyć błąd na gitdeveloper jeśli tak to jak... 
O co pytasz... bo zadajesz wiele różnych pytań.

**Comment by zimart** [comment]
Trochę problematyczne było dzisiaj na wersji  git.. nie działało nic :)
Wydaje mi się że jasno zostało opisane :
Tworząc ofertę, czy zamówienie jednorazowe... dodając produkt i dając cenę jednostkową np : 102,00 netto/szt, dodając rabat 1% - powinno wyjść 100,98 netto - niestety zaokrągla do 101,00

A to już jest problem :)

> przykladowo: netto 102, rabat 1% - powinno być = 100,98 , zamiast 101

**Comment by zimart** [comment]
hmm. nie wiem co jest problemem.. przeszukałem.. ale nie potrafię znaleźć..

**Comment by zimart** [comment]
załączam screena.. może ktoś pomoże - wg mnie jedna z najbardziej ważnych kwestii ... nie tylko dla mnie...
![rabaty-yeti](https://cloud.githubusercontent.com/assets/11014419/12868455/d7d81394-cd07-11e5-99af-d519c6f2ec6e.gif)

**Comment by mariuszkrzaczkowski** [comment]
Sprawdź czy ta poprawka rozwiązuje problem u mnie działa.

**Comment by zimart** [comment]
przy rabatach wygląda na to że jest w porządku, natomiast jeszcze jest bład przy podatku.

**Comment by mariuszkrzaczkowski** [comment]
Już powinno działać.
