### ISSUE TITLE
mailscaner - Handler not found

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2676]
mail scanner is not possible to go into the configuration

![image](https://cloud.githubusercontent.com/assets/15871611/12532975/97e429ce-c232-11e5-8510-dcf41115cf63.png)

**Comment by kjradv** [comment]
Upd: If you turn off the unit and then turn it on, only if this error occurs.

**Comment by bpabiszczak** [comment]
version? Please check on https://gitdeveloper.yetiforce.com
