### ISSUE TITLE
[PL] [Wishlist] Dostęp do profilu dla użytkownia

### ISSUE THREAD

**Issue by boolek** [YetiForceCompany/YetiForceCRM#2678]
Użytkownik nie ma dostępu do swojego profilu w tym do zmiany hasła.
Każda tego typu zmiana wymaga kontaktu z adminem.

Podobnie na stronie logowania nie ma opcji przypomnienia hasła.

**Comment by bpabiszczak** [comment]
Proponuje abyś zerknął w ten plik: https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/config/security.php
