### ISSUE TITLE
[PL] Nie działa workflow

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#2679]
Czysta instalacja ostatniej wersji stabilnej stąd:
https://github.com/YetiForceCompany/YetiForceCRM/archive/2.3.49.zip

Nowe zadanie workflow:
Automatyzacja -> nowy obieg informacji -> Kontrahenci -> Za kazdym razem gdy rekord jest zapisywany -> brak warunków -> nowe zadanie wyslij maila (z helpdesk mial, na mail podstawowy)

zadanie nawet się nie wykonuje mimo że jest aktywowane. Cron jest ustawiony choć nie powinien być chyba wymagany w przypadku tego typu obiegu informacji. 

W kodzie po przedebugowaniu model task ma wartośc pola executeImmediately = false więc nie zostaje wykonane doTask ani nie zostaje dodane do kolejki - a powinno zostać dodane. Po hardkodzie tego pola na true i przejściu dalej do doTask i tak nie działa bo nie pobiera danych przez metodę getContents z VTTask. Mail skonfigurowany poczty wychodzącej wszystkie potrzebne dane do tego zadania są w entity kontrahenta.
php: 5.6

**Comment by bpabiszczak** [comment]
Proszę o weryfikacje, czy działa prawidłowo na wersji developerskiej.

**Comment by wbnx** [comment]
na dev tez nie dziala
