### ISSUE TITLE
Opportunity / Accounts / Contact Reports

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#2680]
Hello everyone,

in the past it was possible to create an Opportunity Report with the modules Contacts & Accounts attached.

What we want to get is a detailed report with:

Opportunity Information / Account Information / Contact information

We need to export this information for our customers.

How can we get this?

Best regards
Ralph

**Comment by bpabiszczak** [comment]
The key question is what the report's format is supposed to be. If PDF is acceptable then it's enough to write a small special function :]

**Comment by ralphkretzschmar** [comment]
The Export should be in Excel format - would be wonderful to have this function again :)
