### ISSUE TITLE
Need to add columns on the leads list page

### ISSUE THREAD

**Issue by Seitrafficonline** [YetiForceCompany/YetiForceCRM#2682]
How can i add extra column on the leads list page? example: i have now 	
Lead name  
Primary Phone  
Website  
Primary Email  
Assigned To

i want to cancel Website and add Country
anyone can help me?
thanks

**Comment by bpabiszczak** [comment]
Check this tool: https://gitdeveloper.yetiforce.com/index.php?module=CustomView&parent=Settings&view=Index&block=13&fieldid=57

**Comment by Seitrafficonline** [comment]
How can i install the tool?

**Comment by reeid** [comment]
@bpabiszczak  - imagine you have 2000 members here and they mess such like that? I believe you need to reconsider setting public forum and leave this list here for devs and power users only (moderation would welcome). Devs can help in public forum or target their leads, and here should be wise conversation rather thank bag for everything...

**Comment by Seitrafficonline** [comment]
done thanks. i found it on my yeti 2.3.49
thanks

**Comment by bpabiszczak** [comment]
I don't mind answering simple questions... and if they don't bother me then everyone can ask about anything they consider important.

If we get to 2000 members we'll think about that. So far it's 30 ~ 40 active people so... we still got some time :)
