### ISSUE TITLE
Integration with wordpress

### ISSUE THREAD

**Issue by Seitrafficonline** [YetiForceCompany/YetiForceCRM#2683]
There is anyway to integrate wordpress formcraft data (leads registration) that will go directly to the crm? look at slider form on the site www.elittebinary.com

**Comment by florek41** [comment]
The easiest way - WEBFORMS - https://gitdeveloper.yetiforce.com/index.php?module=Webforms&parent=Settings&view=List&block=5&fieldid=31

Vtiger manual (similar to YF) https://wiki.vtiger.com/vtiger6/index.php/Webforms

**Comment by bpabiszczak** [comment]
Thank You @florek41
