### ISSUE TITLE
[Bug] Bookkeeping record Save - SQL Error

### ISSUE THREAD

**Issue by nikdejan** [YetiForceCompany/YetiForceCRM#2684]
Accounting>Bookkeeping>Add Record 
Enter necessary data and click Save. I get the following error:
![untitled](https://cloud.githubusercontent.com/assets/13381850/12598215/26f25962-c489-11e5-8960-e925ab2ba67f.png)

**Comment by bpabiszczak** [comment]
Please check latest dev version...

**Comment by nikdejan** [comment]
ver. 2.3.1102 
Bug is still there
