### ISSUE TITLE
[question] PBX

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2687]
To connect the test version of PBX and I have a few questions:
1. Asterisk Connector will be written under the YetiForce crm?
2. Is it possible now to link YetiForce and Asteriks?

**Comment by kjradv** [comment]
2. Everything is working. You can use vtiger asterisk connector.
P.s. When an incoming call is not a pop-up window (if it has an internal employee number and the number of Account) in the module is PBXManager log of all calls. But not having any record in Account

**Comment by epsilonsc** [comment]
Hi can you write short guide how to integrate yetiforce with asterisk.

**Comment by kjradv** [comment]
@epsilonsc , I will do manual, but it will take some time, as in the testing process encountered some difficulties with the connector itself.

**Comment by bpabiszczak** [comment]
1. At the moment there's no mechanism in YetiForce that would connect to Asterisk.
2. There's something we inherited after Vtiger, but we have no idea if it works [I doubt it does]
3. At the moment we aren't able to provide you with any reliable date when or if this can be implemented.

**Comment by reeid** [comment]
Crm without asteriskx (or simillar) is like PC without Internet. I thought it obvious here but seems it not. How you can even dream to get to large firms without developing this option?

**Comment by kjradv** [comment]
@bpabiszczak 
vtiger connector works, but only for outgoing calls, for this purpose it is to add a class

**Comment by zwieja** [comment]
@bpabiszczak
PBX Manager and Vtiger Asterisk Connector not working at all in YetiForce ?
Something changed in this subject ?

**Comment by amitjoti3** [comment]
Dear team,

Can we have now salutation on asterisk connector.

I'm not able to configure the pbx with crm
