### ISSUE TITLE
Email Templates lose HTML formatting

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#269]
Hi,
Email Templates with HTML formatting and pictures lose all their formatting when selected/inserted into Roundcube. Only the pure text is inserted.

**Comment by setras** [comment]
Found the problem.

In file: "layouts/vlayout/modules/OSSMail/resources/mailtemplate.js" replace line 91 
    var html = jQuery("<div/>").html(data.result['content']).text();
with 
    var html = jQuery("<div/>").html(data.result['content']).html();

**Comment by zebrahosting** [comment]
Works fine for me. Please include in next update.
