### ISSUE TITLE
[BUG] Discount summary/Tax summary

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#2690]
![invbug](https://cloud.githubusercontent.com/assets/10221999/12637612/fa42f624-c596-11e5-96e4-d8f6f62c12f4.gif)

+ Typo
'Podsumowanie podatu' - 'Podsumowanie podatku'

**Comment by mariuszkrzaczkowski** [comment]
Error does not exist in latest version
