### ISSUE TITLE
PDO Error

### ISSUE THREAD

**Issue by AndrGelmini** [YetiForceCompany/YetiForceCRM#2693]
Hello.

For a couple of days I have this problem.

When I try to open the crm comes out this error:

Fatal error: Class 'PDO' not found in ... / include / database / PearDatabase.php on line 75

to be honest I would not know what may be due. I would avoid making a thousand tests.

and I was wondering if there is a way. make a beckup database .. so as not to lose everything and then groped to reinstall everything.

The scriti is the latest version of Yeti rilascaita for developers. and it is hosted on the web server, linux, with php version 5.2 (to be confirmed)

What do you recommend?

**Comment by kjradv** [comment]
Hi, I had this error only when decided http://stackoverflow.com/questions/13375061/installing-pdo-driver-on-mysql-linux-server

**Comment by bpabiszczak** [comment]
1. PHP 5.2 ????? The system should run on 5.6 version.
2. I don't know your version of the system so it's hard to say anything.
3. Your error requires proper server configuration.
4. You can make a database backup copy and try to run it on clean crm, but it requires some programming knowledge.
