### ISSUE TITLE
[PL] Nie działa widok detail view rekordu z kalendarza

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#2695]
wersja mobile
czysta wersja 2.3 widok podgladu rekordu z kalendarza nie działa, inne moduły działają

edit: błąd jest w cachedModuleLookupWithRecordId w modułach zapisanych w sesji brakuje modułu eventów o id 18

**Comment by bpabiszczak** [comment]
Proszę o aktualizacje do wersji 2.3.49...

**Comment by wbnx** [comment]
testowane na wersji 2.3.49 a także 2.4 dev

**Comment by bpabiszczak** [comment]
Użyj tego [https://screentogif.codeplex.com/] aby nagrać problem, ponieważ ja go nie widzę.

**Comment by wbnx** [comment]
Na wersji mobile sprawdzałeś? screen brak danych rekordu w innych modułach jest ok
![mobile_calendar_detailview](https://cloud.githubusercontent.com/assets/14766421/12697919/bebf2e84-c78e-11e5-95ec-578e9b3566ac.png)

**Comment by bpabiszczak** [comment]
ale wersja mobilna jest wyłączona [a domyślnie zostanie całkowicie usunięta] ponieważ nie jest przez nas to już wspierana [po to udostępniamy wersje responsywną].
