### ISSUE TITLE
[PL] Bląd przy relacji pola w module OSSEmployees

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#2696]
Pole pracownik nadrzedny w okienku popup nie pojawia się lista pracowników
a przy próbie wyszukania taki błąd:
`{"success":false,"error":{"code":"SQLSTATE[42000]: Syntax error or access violation: 1064 Something is wrong in your syntax obok 'vtiger_ossemployees.ossemployeesid<>111 AND vtiger_ossemployees.ossemployeesid ' w linii 1","message":"SQLSTATE[42000]: Syntax error or access violation: 1064 Something is wrong in your syntax obok 'vtiger_ossemployees.ossemployeesid<>111 AND vtiger_ossemployees.ossemployeesid ' w linii 1"}}`

**Comment by wbnx** [comment]
Zapytanie jest niepoprawnie generowane przy wyszukiwaniu - brakuje 'and' więc jest syntax err (być może tyczy się to też innych modułów lub relacji tego samego modułu do tego samego) natomiast popup filtruje na sztywno w przypadku tego modułu metoda _getQueryByModuleField_ po status = Active co jest błędne bo nawet nie ma tej opcji w pickliście do wyboru w ostatnim stabilnym wydaniu.

**Comment by bpabiszczak** [comment]
wbnx nie bardzo rozumiem rozżalenie... najlepiej od razu przesłać do nas poprawkę skoro przyczyna jest znana.

**Comment by wbnx** [comment]
Panie bpabiszczak nie jest to rozżalenie.. ja wykonałem u siebie poprawkę na szybko(co wcale nie rozwiązuje całkowicie problemu który znajduje się gdzieś głębiej w kodzie więc nie poszedł pull request) ze względu na to że nie mam czasu tego wszystkiego debugować zgłaszam to wam aby ktoś z dev się temu przyjrzał + info gdzie można zacząć szukać powodu błędu więc w zasadzie nie wiem czemu się Pan doszukuje rozżalenia zamiast podziękować za zgłoszony błąd(bo to ja Panu wyświadczam przysługę poświęcają swój cenny czas na zgłoszenie tego) i przekazać dalej do deweloperów a to że stabilnym wydaniem oznaczacie coś czego nie testujecie nawet do końca to już nie jest mój problem.

**Comment by bpabiszczak** [comment]
Wszyscy jesteśmy tu na TY... 
Posta napisałeś tak, jakbyś miał do nas żal, że w ogóle błąd istnieje... w ostatnim masz do nas żal, że coś nie powinno być opublikowane bo są jakieś błędy... a na końcu że nie podziękowałem, że dodałeś coś na GitHub. 

Issue nie posiada informacji które powinien posiadać czyli:

1. numer wersji
2. czy błąd występuje na wersji developerskiej

skoro masz częściowe rozwiązanie, to je wklej, może nakieruje nas na właściwe...

i proponuje abyś zmienił ton rozmowy.

.

**Comment by wbnx** [comment]
2.3.49/dev - może wypadałoby napisać gdzieś o zasadach zgłaszania błędów? ja akurat zapomniałem dopisać w tym zgłoszeniu ale nie pisze tu aby komuś wytykać błędy tylko w dobrej wierze że kolejna wersja tego systemu będzie doskonalsza bo i tak dużo zrobiliście z tego czegoś czym jest VT. Informacje z mojego drugiego posta w zupełności wystarczą deweloperowi więc nie wklejam kodu z hackami który nie powinien na pewno się znajdować w oficjalnej wersji jeśli sam będę miał czas to rozwiązać we właściwy sposób to podeślę fix z forka.

**Comment by boolek** [comment]
26.03.2015 https://yetiforce.com/pl/dokumentacja-programisty/błędy.html ;)

**Comment by wbnx** [comment]
Większość społeczności tego nie przeczyta nawet wydaje mi się że taka informacja mogłaby być po ang w readme z głównego folderu, w większości issue nie ma tej informacji w pierwszym poście na jakich wersjach testowane było. Większość zgłoszeń i tak będzie się odnosić do wersji oficialnej więc nie ma co ignorować błędu tylko dlatego że ktoś nie napisał że sprawdził na najnowszej wersji.
Ten błąd został sprawdzony na ostatnich wersjach systemu można na pewno już teraz oznaczyć jako bug :)

**Comment by bpabiszczak** [comment]
1. Jeżeli zostało coś poprawione w wersji DEV a błąd jest w wersji STABLE to osoba zgłaszająca musi poczekać na nową wersje, albo sobie samemu wgrać poprawkę, albo musi zlecić tą poprawkę komuś innemu... i na chwilę obecną tak będzie, no chyba, że wydamy wersje LTS.
2. Skoro błędu nie ma w DEV to nikt nie ignoruje, błąd został rozwiązany. Natomiast my nie będziemy za każdego użytkownika sprawdzać to, co on sam powinien sprawdzić. 
3. Specjalnie po to dopisaliśmy możliwość dodawania błędów z poziomu YetiForce, aby użytkownik za nim coś doda do GitHub zapoznał się z instrukcja dodawania na GitHub.
