### ISSUE TITLE
[BUG minor] WYSIWYG fields have no labels

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2698]
WYSIWYG fields have no labels in edit view.

![contacts - edit](https://cloud.githubusercontent.com/assets/10330264/12702604/bdd05d1a-c836-11e5-9add-962530cfcc6f.png)

**Comment by KatarzynaUlichnowska** [comment]
Hello,
that's not a bug. The label takes too much space, if you want to separate both fields, it's best to put them in two separate blocks and name them.
