### ISSUE TITLE
[Feature request] To allow connection and usage of OwnCloud

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#270]
It was discussed before but to track and blend ideas I am raising this ticket-request. Please share your observations/requirements/solutions to allow developer bring it on track with benefit to everybody

**Comment by zebrahosting** [comment]
Yes would be very nice and important addition.
Every user its own space + a shared one

**Comment by SergeyDjam** [comment]
It is necessary functionality

**Comment by bpabiszczak** [comment]
We are currently in the process of implementing webdav [https://github.com/YetiForceCompany/YetiForceCRM/commit/5378ce55ca76ddba24a0161e910ad209c0054464]
