### ISSUE TITLE
Front office for customers

### ISSUE THREAD

**Issue by Seitrafficonline** [YetiForceCompany/YetiForceCRM#2700]
Hi
i need a login page with password for our customers to see their account. How can it be done? Can you guide me please?
Many thanks

**Comment by kjradv** [comment]
Hi,
https://github.com/YetiForceCompany/YetiForcePortal2/tree/developer

**Comment by Seitrafficonline** [comment]
That is great, but where should i install it in the YetiForce CRM folder or in a new folder?
can you guide me please. I have now crm10.elittebinary.com for the crm

**Comment by zebrahosting** [comment]
You can use a (sub)domain or subfolder. Just add it to the config.inc.php file. ( I use subdomain portal.domain to keep it clean) 
Be aware that the original portal is quite old and that the portal2 option will be more in line with the current Yetiforce but hasn't been worked on for a while and I could not get it too work.
Might be worth to check with the Yeti team before you commit to one or the other.

**Comment by Seitrafficonline** [comment]
Hi
i did everything as described on client.elittebinary.com connected to crm10.elittebinary.com and is not working. I believe that there is no need to database connection.
thanks

**Comment by zebrahosting** [comment]
You need to be more precise what you did.

Which portal did you use?
Set the config.inc.php from the CRM to the right URL?
Set the config of the portal to match the CRM version?
etc.

**Comment by Seitrafficonline** [comment]
i used the 2.2.0 version
i setted the config.inc.php the http://client.elittebinary.com
i setted also the config to match the crm version (regarding this point, should i add any port ext. ex. domain:80)

**Comment by bpabiszczak** [comment]
All you need is here:  https://github.com/YetiForceCompany/YetiForcePortal.

We don't offer free assistance [we can only give some small tips]

**Comment by Seitrafficonline** [comment]
Hi
now everything is working smoothly. the only issue is the login for the customer to the portal client.elittebinary.com . is not working. we generated an account on crm and we configured the email on the crm10.elittebinary.com but we dont get a new password from the client page.
