### ISSUE TITLE
CalDav with OSX

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2701]
Have been trying to get CalDav and CardDav working with OSX apps, Calendar, Contacts and  Thunderbird lightning.
When it was first implemented, I got it working for a while but now can't get it going again.

All options in config are set.
I can open the dav.php page in the browser, login and and see all the items. Seems all is fine there.

What I can't figure out is what server link to use. Tried:
domain/api/dav.php
domain/api/dav.php/principals/admin/
domain/api/dav.php/calendars/admin/YFCalendar/
domain/api/dav.php/calendars/admin/
domain/api/dav.php/calendars/

Some seems to connect but never syncs the calendar. With most links there is an error about a home setting. "The server specified an invalid calendar home"
Since I know that Apple is not the best when it comes to standards, I 've tried Thunderbird too but it seems to give the same issues. Teste non-ssl and ssl.

Tested with 2.3.49 / 2.3.1072

Google showed that there might be a .htaccess redirect setting missing.
Any suggestions?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2252
