### ISSUE TITLE
 Instalacja - jakie chmody? 

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2705]
Witam,

Pragnę przetestować YetiForce, gdyż wersja demo mi się naprawdę bardzo spodobała.
Skopiowałem standardowo pliki na serwer, ale po wejściu przez przeglądarkę zarówno do głównego katalogu, jak i katalogu install(również install.php i index.php) nic się nie dzieje...
Jakie powinny być granty na poszczególne katalogi?
Serwer to VPS.

**Comment by bpabiszczak** [comment]
Ogólnie system sprawdza przy instalacji dostęp do folderów i plików ale robi to na którymś etapie instalacji, jeżeli nie dochodzimy do tego momentu to proponuje ustawić konfiguracje taką jak ma większość hostingów na świecie, wgrywając pliki użytkownik:grupa domyślnie ma już ustawione odpowiednie uprawnienia na odczyt/zapis dla wszystkiego co wgrane np. tak jak jest na home.pl 

Oczywiście możemy wyciągnąć listę folderów i plików na które należy nadać odpowiednie chmody ale powoduje to wiele problemów w przyszłości [o ile dobrze pamiętam, to część ludzi miała problem przy generowaniu PDFów bo on robił wiele tymczasowych plików].

Należy pamiętać, że mająć hosting np. home.pl często aplikacja nie widzi folderu sesji [domyślnie wskazujemy cache/sessions] wówczas należy utworzyć odpowiedni folder [potem można go zmienić].

A podsumowując problem: pokaż logi :D

**Comment by bpabiszczak** [comment]
Configuration directory	config/	Allowed
Configuration file	config/config.inc.php	Allowed
User privileges directory	user_privileges/	Allowed
Tabdata file	user_privileges/tabdata.php	Allowed
Menu file	user_privileges/menu_0.php	Allowed
User privileges file	user_privileges/user_privileges_1.php	Allowed
Parent tabdata file	config/parent_tabdata.php	Allowed
Cache directory	cache/	Allowed
Address book directory	cache/addressBook/	Allowed
Cache backup directory	cache/backup/	Allowed
Image cache directory	cache/images/	Allowed
Import cache directory	cache/import/	Allowed
Logs directory	cache/logs/	Allowed
Session directory	cache/session/	Allowed
Cache templates directory	cache/templates_c/	Allowed
Cache upload directory	cache/upload/	Allowed
Cron modules directory	cron/modules/	Allowed
Vtlib test directory	cache/vtlib/	Allowed
Vtlib test HTML directory	cache/vtlib/HTML	Allowed
Modules directory	modules/	Allowed
Storage directory	storage/	Allowed
Product image directory	storage/Products/	Allowed
User image directory	storage/Users/	Allowed
Contact image directory	storage/Contacts/	Allowed
Logo directory	storage/Logo/	Allowed
MailView attachments directory	storage/OSSMailView/	Allowed

**Comment by amdziak** [comment]
Hmmm,

Logi apache'a czy samej aplikacji(gdzie takowe są?)

**Comment by bpabiszczak** [comment]
To zależy, jak mamy biały ekran to od apache był zaczął, logi aplikacji włącza się tak: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/109-debugowanie.html

Listę folderów można znaleźć tutaj bo post powyżej jest nieczytelny: 
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65

**Comment by amdziak** [comment]
no to logi apache'a na poczatek:

`[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Warning:  session_start(): open(/var/www/cache/session/sess_i7bgb7o5j96q729gpumflk9jv3, O_RDWR) failed: Permission denied (13) in /var/www/libraries/HTTP_Session/Session.php on line 161
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: forceSSL in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: csrfProtection in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: authenticated_user_id in /var/www/include/main/WebUI.php on line 54
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: translated_language in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Fatal error:  Can't use method return value in write context in /var/www/modules/Users/models/Record.php on line 284
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Warning:  Unknown: open(/var/www/cache/session/sess_i7bgb7o5j96q729gpumflk9jv3, O_RDWR) failed: Permission denied (13) in Unknown on line 0
[Wed Feb 03 10:02:35 2016] [error] [client 89.76.150.225] PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/www/cache/session) in Unknown on line 0
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Warning:  session_start(): open(/var/www/cache/session/sess_i7bgb7o5j96q729gpumflk9jv3, O_RDWR) failed: Permission denied (13) in /var/www/libraries/HTTP_Session/Session.php on line 161
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: forceSSL in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: csrfProtection in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: authenticated_user_id in /var/www/include/main/WebUI.php on line 54
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: translated_language in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Fatal error:  Can't use method return value in write context in /var/www/modules/Users/models/Record.php on line 284
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Warning:  Unknown: open(/var/www/cache/session/sess_i7bgb7o5j96q729gpumflk9jv3, O_RDWR) failed: Permission denied (13) in Unknown on line 0
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/www/cache/session) in Unknown on line 0
[Wed Feb 03 10:02:40 2016] [error] [client 89.76.150.225] script '/var/www/install.php' not found or unable to stat
[Wed Feb 03 10:02:52 2016] [error] [client 89.76.150.225] script '/var/www/install/install.php' not found or unable to stat
[Wed Feb 03 10:13:24 2016] [error] [client 89.76.150.225] script '/var/www/install/install.php' not found or unable to stat
`

**Comment by amdziak** [comment]
a i nie ważne gdzie wejdę to mam biały ekran (Przeglądarka Safari)

**Comment by bpabiszczak** [comment]
Na początek to skonfiguruj serwer pod wymagania CRM bo masz błędy których być nie powinno https://yetiforce.com/pl/wdro%C5%BCeniowiec/instalacja-aktualizacja/99-wymagania-dla-serwera-www.html

**Comment by bpabiszczak** [comment]
a i z logów mamy błąd, nie może utworzyć pliku sesji :d Sprawdź czy istnieje ten folder: /var/www/cache/session/

**Comment by amdziak** [comment]
folder istnieje :)
biorę się za konfigurację serwera... (nie widziałem wcześniej tej strony :( )

**Comment by bpabiszczak** [comment]
błąd jest podany, nie może utworzyć pliku sesji... z jakiegoś powodu. Może wynikać to z konfiguracji serwera... tzn. np. serwer nie pozwala zapisać sesji w innej lokalizacji [a aplikacja ustawia sobie folder sesji] w takim wypadku albo należy zmienić konfiguracje serwera albo zmienić w aplikacji domyślną ścieżkę.

**Comment by amdziak** [comment]
wyedytowalem php.ini.
zrestartowalem apache'a
cache/session ma 755
aktualne bledy w logu to:
`[Wed Feb 03 10:24:44 2016] [error] [client 89.76.150.225] File does not exist: /var/www/favicon.ico, referer: http://tech-cast.eu/install/index.php
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Warning:  session_start(): open(/var/www/cache/session/sess_6036758a56b21bc4d3ba7, O_RDWR) failed: Permission denied (13) in /var/www/libraries/HTTP_Session/Session.php on line 161
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: forceSSL in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: csrfProtection in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: authenticated_user_id in /var/www/include/main/WebUI.php on line 54
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: translated_language in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Notice:  Undefined index: root_directory in /var/www/include/runtime/Globals.php on line 22
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Fatal error:  Can't use method return value in write context in /var/www/modules/Users/models/Record.php on line 284
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Warning:  Unknown: open(/var/www/cache/session/sess_6036758a56b21bc4d3ba7, O_RDWR) failed: Permission denied (13) in Unknown on line 0
[Wed Feb 03 10:24:52 2016] [error] [client 89.76.150.225] PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/www/cache/session) in Unknown on line 0
[Wed Feb 03 10:33:40 2016] [error] [client 5.39.222.159] File does not exist: /var/www/rom-0
[Wed Feb 03 11:10:33 2016] [notice] caught SIGTERM, shutting down
[Wed Feb 03 11:10:34 2016] [notice] Apache/2.2.22 (Debian) PHP/5.4.45-0+deb7u2 configured -- resuming normal operations
[Wed Feb 03 11:12:37 2016] [notice] caught SIGTERM, shutting down
[Wed Feb 03 11:12:38 2016] [notice] Apache/2.2.22 (Debian) PHP/5.4.45-0+deb7u2 configured -- resuming normal operations
`

**Comment by amdziak** [comment]
przeinstalowałem sobie VPS-a, bo tam wcześniej było sporo innych skryptów, zainstalowałem wszystkie moduły zgodnie z instrukcją instalacji, przekopiowałem pliki i zarówno poprzez wejście tak:
http://91.196.50.15/install/
jak i:
http://91.196.50.15/install/Install.php (I jest duże :) )
mam czystą stronę.
W logach apache'a nie ma nic(pusto).
Co to może być?
System to Debian 7...

**Comment by bpabiszczak** [comment]
Czyli kompletnie nic się nie zmieniło:
1. Serwer nie jest prawidłowo skonfigurowany.
2. Serwer nie może zapisać plików sesji do folderu bo nie ma uprawnień lub folder nie istnieje

Zgłoś się do swojego administratora. Administrator bez problemu powinien sobie poradzić.

**Comment by amdziak** [comment]
Zmieniłem w php.ini folder na /var/www/cache/session i w dalszym ciągu jest to samo.
Dodatkowo podniosłem chmoda na 777.

**Comment by bpabiszczak** [comment]
To tak nie działa :] Tak jak pisałem, potrzebujesz administratora do pomocy...

**Comment by amdziak** [comment]
A można prosić o jakieś wskazówki?
Nie wiem gdzie i kiedy znajdę administratora, a muszę to przetestować jutro do południa...

**Comment by bpabiszczak** [comment]
Skoro trzeba przetestować jutro do południa to polecam zwykły hosting, wczoraj np. instalowałem dwie instancje na home.pl i wszystko działa prawidłowo [musiałem tylko utworzyć folder sesji ręcznie]. 

My nie udzielamy wsparcia w zakresie administracji serwerami, są od tego inne fora [odpowiednie dla każdej z dystrybucji] i przypuszczam, że społeczność Ci pomoże. Ja podałem Tobie rozwiązanie, ale nie wpiszę i nie sprawdzę za Ciebie serwera, tak jak pisałem powyżej, masz do zrobienia to: 

1. Serwer nie jest prawidłowo skonfigurowany [zgodnie z wymaganiami na naszej stronie www].
2. Serwer nie może zapisać plików sesji do folderu bo nie ma uprawnień lub folder nie istnieje.

Możemy Ci podesłać do pomocy naszego administratora, ale to kosztuje...

**Comment by amdziak** [comment]
Wasz asministrator pewnie też dopiero jutro rano? :)

**Comment by bpabiszczak** [comment]
I o ile będzie miał czas... proponuje telefon o 8:00 i zobaczymy co da się zrobić.

**Comment by amdziak** [comment]
zainstalowałem sobie na home - bardzo ładnie działa (nie musiałem tworzyć katalogu).
Tylko mam pytanie: dlaczego wygląd po instalacji jest identyczny jak w VTigerze, a demo na Waszej stronie ma zupełnie inny wygląd i funkcje (chociażby szablony PDF i moduł Magazynu(ten akurat już sobie doinstalowałem)).
Moja wersja to 2.3.49

**Comment by bpabiszczak** [comment]
Wersja 2.3.49 to wersja stabilna. To co widać na naszej stronie to wersja developerska [a więc nieukończona] i można ją pobrać tutaj: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer [Download ZIP z prawej strony].

**Comment by amdziak** [comment]
Poradziłem sobie z instalacją.
Zeby nie zakładać nowego wątku mam kilka pytań natury technicznej dotyczących wersji stabilnej.
1) W jaki sposób można tworzyć własne szablony PDF?
2) W jaki sposób można dodać powiązanie modułów (chodzi mi np. o powiązanie modułu Produkty z Modułem Magazyn, tak aby każdy produkt można było przypisać do dowolnego magazynu).

Z góry dzięki za odpowiedzi.

**Comment by bpabiszczak** [comment]
Koniecznie założyć nowy wątek. 
W wersji stabilnej to inaczej działa niż w wersji dev.

**Comment by amdziak** [comment]
Ok.
Założyłem nowy wątek.
Czekam na odpowiedzi.

Pzdr.

**Comment by mailo86** [comment]
Hej, możesz mi pomóc z konfiguracja serwera ?

**Comment by amdziak** [comment]
napisz na zaras.pawel@gmail.com to pomogę.
