### ISSUE TITLE
New mass email testing

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2707]
Looking at the newly made mass email system I see that choosing that option it uses a mailto: function to open a local mailer, not the internal Roundcube. Is this something that can be configured or is this a fixed choice?
This way I can't send / use email templates to reach a group of people with mailmerge options.
The only other option I see is opening a new mail in Roundcube, select contacts one by one and use the template but that will not fill in the variables. Guess I miss something here. Can someone enlighten me?

I will give an example to show what I am after:
You have contacts and want them to check the records on file. I create a mail template, with variables like first name en lastname and many more.
Then I go to the contacts, use a filter to select a group and select all to send the mass mail.
Each of them receives a personal email with their details.

**Comment by bpabiszczak** [comment]
1. The kind of client that is used [internal {roundcube} or external {eg.outlook}] can be set in user's configuration.
2. When you start using roundcube [see #1] you can start using tempates.
3. Remember that this version of mass mailing sends the same mail to everyone, so personalized variables, such as name and surname, don't work. We're planning to add the option of sending mails to each person individually in the future- then you'll be able to use templetes the way you intend to.
