### ISSUE TITLE
Enable comments in custom module

### ISSUE THREAD

**Issue by sangeetasoni19** [YetiForceCompany/YetiForceCRM#2709]
How to enable Comments in custom module?

**Comment by mariuszkrzaczkowski** [comment]
Use the vtlib:
```php
include_once('vtlib/Vtiger/Module.php');
include_once 'modules/ModTracker/ModTracker.php';
$tabid = Vtiger_Functions::getModuleId($moduleName);
ModTracker::enableTrackingForModule($tabid);
```

**Comment by sangeetasoni19** [comment]
Comment widget cannot be seen in the custom module even after enabling it

**Comment by mariuszkrzaczkowski** [comment]
I made a mistake I gave the example of turning history already is correct.

**Comment by sangeetasoni19** [comment]
Thanks I can see history but I wanted to enable comments

**Comment by maeglin4** [comment]
so whats the real solution to add the comments widget to my custom module ?
