### ISSUE TITLE
Widgets on dashboard don't appear

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#271]
It seems that widgets don't show up on the dashboard on instances that are upgrade step by step.
Testing on a fresh install works fine but several older systems don't want to show any widgets.
No errors as far as I can see, just empty dashboards.

**Comment by bpabiszczak** [comment]
In order for us to do something with this error, we need to be able to test for it. Please describe step by step what we should do. If the error doesn’t appear on test.yetiforce.com, then describe step by step how to test for it on a system, e.g. on a migration system. We are not able to do anything without this basic information.
