### ISSUE TITLE
Kilka pytań o wersję stabilną - powiązanie modułów, szablony PDF

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2710]
Mam kilka pytań natury technicznej dotyczących wersji stabilnej(aczkolwiek nie mogę się doczekać kiedy będzie nowa, bo jest naprawdę ciekawa i funkcjonalna).
1) W jaki sposób można tworzyć własne szablony PDF?
2) W jaki sposób można dodać powiązanie modułów (chodzi mi np. o powiązanie modułu Produkty z Modułem Magazyn, tak aby każdy produkt można było przypisać do dowolnego magazynu(moduł magazyn pobrałem z wersji demo i zainstalowałem)).
3) Faktury - czy istnieje moduł, który dostosowuje faktury do polskich wymagań? (podatek przy każdej pozycji faktury, a nie tylko sumaryczny?)

Z góry dzięki za odpowiedzi.

**Comment by amdziak** [comment]
Nikt nie wie?

**Comment by bpabiszczak** [comment]
Dobre dobre :P po 4h oczekujesz odpowiedzi :D Wiesz ile SLA na takim poziomie kosztuje?

**Comment by amdziak** [comment]
Myślałem, że skoro nie ma jako takiego howto, to jest ktoś kto wszystko wie :)
W takim razie poczekam :)
Aczkolwiek będę wdzięczny chociaż za odpowiedź na pytanie 2 i 3 :)

**Comment by bpabiszczak** [comment]
Ja nie piszę o odpowiedziach, lecz o czasie reakcji

**Comment by bpabiszczak** [comment]
O jakiej wersji systemu rozmawiamy. Stabilna czy Developerska? Bo to dwa różne systemy - każdy z tych punktów o które pytasz został przebudowany...

**Comment by amdziak** [comment]
Wszystkie pytania dotyczą wersji stabilnej (2.3.49).

**Comment by bpabiszczak** [comment]
W stabilnej nie ma magazynu :D Faktury są dostosowane do PL, trzeba sobie zmodyfikować szablon. Do szablonów jest wbudowane w system narzędzie PDF.

**Comment by amdziak** [comment]
Z fakturami częściowo doszedłem, więc nie ma pytania.
Magazyn sobie doinstalowałem (bardzo ładnie działa ten z wersji developerskiej :D ) - więc jak można dodać powiązany moduł? Chodzi mi o sytuację, kiedy mam kilka magazynów i chce móc na fakturze wybrać z którego ma pójść produkt...
Niestety nie mogę namierzyć narzędzia do szablonów, a chciałbym dodać szablony WZ-ek...

Btw: na jakim etapie jest wersja developerska? :)

**Comment by bpabiszczak** [comment]
Magazyn nie działa nawet na dev :D bo nie jest zrobiony jeszcze [jest to zwykły moduł z kilkoma polami] będziemy tam dopisywali dopiero cały mechanizm liczący stany magazynowe, więc nie wiem jak może Tobie to działać

Chyba za bardzo kombinujesz....

**Comment by amdziak** [comment]
Pomijając magazyn.
Jak można dodać powiązany moduł?
Gdzie dokładnie jest narzędzie do tworzenia szablonów PDF? (W Narzędzia->PDF, niestety nie ma możliwości stworzenia szablonu, ani edycji szablonu "Invoice PDF")?

**Comment by bpabiszczak** [comment]
W wersji stable o ile dobrze pamiętam szablony robi się z poziomu user-a a nie panelu, w wersji nowej jest całkowicie nowy moduł. 
Moduł powiązany dodaje się z narzędzia modułów powiązanych, ale aby móc dodać, należy w pliku developerskiego w konfigu to aktywować.

**Comment by amdziak** [comment]
Co do szablonów - będę próbował, ale nigdzie nie widzę takiej opcji...
A kojarzy Pan jak się nazywa parametr do aktywacji tworzenia modułów?

**Comment by bpabiszczak** [comment]
Jesteśmy tu na TY... 
Tworzenia modułów? Czy relacji?

**Comment by amdziak** [comment]
OK :)
relacji oczywiście :)
co do szablonów z poziomu Usera jest tylko możliwość wyboru szablonu...

**Comment by amdziak** [comment]
Szablony PDF znalazłem :) są w zakładce Bazy Danych...

**Comment by bpabiszczak** [comment]
Nie ma tu zbyt wiele parametrów :P https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/developer.php

**Comment by amdziak** [comment]
Chyba jednak znalazłem małego buga w wersji stabilnej...
Przy dodawaniu nowego pola, jako pole do modułu powiązanego, pole się pojawia, ale nie ma możliwości edycji go...
