### ISSUE TITLE
Grand Total and Items total wrong on quotes

### ISSUE THREAD

**Issue by offtopic242** [YetiForceCompany/YetiForceCRM#2712]
Hi,

When i create a quote and choose a product and fill in prices (with or without discount) the Grand total and item total gets updated in the correctly. When saving the record and returned to the preview of the quote the items total and grant total shows as zero. 

Another problem is that when trying to have more than one product or service only the first product or service gets saved. Still with the wrong grand total and items total.

Version: 2.349

**Comment by mariuszkrzaczkowski** [comment]
Send some screenshots of the problem so we can see the problem.

**Comment by offtopic242** [comment]
![details view](https://cloud.githubusercontent.com/assets/9818626/12869551/6a4adb74-cd23-11e5-8867-60d9972eb239.jpg)
![edit view](https://cloud.githubusercontent.com/assets/9818626/12869552/6a4ca6fc-cd23-11e5-8f50-706e706f3ff4.jpg)

**Comment by offtopic242** [comment]
It seems there may also be a bug when changing currency from SEK to EUR (seems like there may a problem with decimal delimiter). Maybe the same problem causing this.

**Comment by mariuszkrzaczkowski** [comment]
It is an old module offers the latest version of it is gone.
Check if the problem occurs on a new version of this module.
https://gitdeveloper.yetiforce.com/index.php?module=SQuotes&view=List&mid=123&parent=118
