### ISSUE TITLE
PDF- PROBLEM

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2713]
Co może być przyczyną nieprawidłowego działania PDF.. 
Na wersji DEVELOPOERSKIEJ DZIAŁA....

Jak mogę zlokalizować , określić przyczynę ?

Ustawienia mojego serwera...
MAP	Tak	Obowiązkowe
Zlib	Tak	Obowiązkowe
PDO	Tak	Obowiązkowe
openssl	Tak	Obowiązkowe
cURL	Tak	Obowiązkowe
GD	Tak	Obowiązkowe
LDAP	Tak	Opcjonalne
PCRE	Tak	Obowiązkowe
XML	Tak	Obowiązkowe
JSON	Tak	Obowiązkowe
SESSION	Tak	Obowiązkowe
DOM	Tak	Obowiązkowe
ZIP	Tak	Obowiązkowe
Parametr	Zalecana konfiguracja	Aktualna konfiguracja
PHP	5.4.0	5.6.17
error_reporting	E_WARNING & E_ERROR & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT	
output_buffering	Włączony	Włączony
max_execution_time	600	1200
max_input_time	600	1200
default_socket_timeout	600	
mysql.connect_timeout	600	
memory_limit	512 MB	512 MB
safe_mode	Wyłączony	Wyłączony
display_errors	Wyłączony	Wyłączony
log_errors	Wyłączony	Wyłączony
file_uploads	Włączony	Włączony
register_globals	Włączony	Wyłączony
short_open_tag	Włączony	Włączony
post_max_size	50 MB	100 MB
upload_max_filesize	50 MB	80 MB
max_allowed_packet	10 MB	4.0 MB
max_input_vars	5000	10000
magic_quotes_gpc	Wyłączony	Wyłączony
magic_quotes_runtime	Wyłączony	Wyłączony
zlib.output_compression	Wyłączony	Wyłączony
zend.ze1_compatibility_mode	Wyłączony	Wyłączony
session.auto_start	Wyłączony	Wyłączony
magic_quotes_sybase	Wyłączony	Wyłączony
session.gc_maxlifetime	21600	21600
session.gc_divisor	500	1000
session.gc_probability	1	1
mbstring.func_overload	Wyłączony	Wyłączony

Jedynie zgłasza mi to : max_allowed_packet	10 MB	4.0 MB

**Comment by bpabiszczak** [comment]
Wiemy tylko tyle, że nic nie wiemy... 
https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-issues.html

**Comment by zimart** [comment]
Dlatego chciałem prosić o instrukcje jakąś zlokalizowania problemu. :) Mam tylko pustą stronę i nie generuje się PDF. Czy jakiś logi , debugowanie mogę włączyć ? - jest to na 100% wina serwerka... na innym działa bez problemu. Ale zależy mi aby był na tym. Podałem konfigurację obecną - niby wszystko jest ok..ale niestety nie działa..

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/109-debugowanie.html

**Comment by zimart** [comment]
Niestety czysto :) Walczę z adminem serwera...

**Comment by bpabiszczak** [comment]
Tu nie ma magii, albo w logach serwera albo w logach aplikacji, gdzieś informacje o błędzie powinna być.

**Comment by zimart** [comment]
Chętnie udostepnię wszelki dostęp :) Jeżeli tylko ktoś będzie chciał pomóc.. .

**Comment by bpabiszczak** [comment]
Odpłatnie możemy pomóc, bezpłatnie nie udzielamy indywidualnego wsparcia.
