### ISSUE TITLE
[bug] Documents

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2715]
Saving document (v. 2.3.1153) gives
![docs](https://cloud.githubusercontent.com/assets/10330264/12882509/c37afc3c-ce5a-11e5-9e4b-04354ad674d2.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/0f98a9e98cc939bbb0e1898bd7ea90c42d5c7e93
