### ISSUE TITLE
[Stable] Błąd w czasie generowania PDF-a

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2716]
W czasie generowania PDF-a do zamówienia od klienta dostaje następujący błąd:

`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`19498389_soms`.`vtiger_senotesrel`, CONSTRAINT `fk_2_vtiger_senotesrel` FOREIGN KEY (`notesid`) REFERENCES `vtiger_notes` (`notesid`) ON DELETE CASCADE)

`
Błąd pojawia się tylko w czasie, kiedy PDF jest generowany z samego zamówienia, a nie z listy zamówień...

**Comment by bpabiszczak** [comment]
Proszę sprawdzić, czy błąd występuje w nowej wersji. 
Błąd SQL mówi w czym jest problem i z tego co pamiętam, trzeba usunąć to powiązanie pomiędzy tabelami, bo było błędnie wprowadzone.
