### ISSUE TITLE
CRM + Portal communication

### ISSUE THREAD

**Issue by Seitrafficonline** [YetiForceCompany/YetiForceCRM#2717]
Hi
now everything is working smoothly. the only issue is the login for the customer to the portal client.elittebinary.com . is not working. we generated an account on crm and we configured the email on the crm10.elittebinary.com but we dont get a new password from the client page.

**Comment by Seitrafficonline** [comment]
any answer?

**Comment by offtopic242** [comment]
Have a look at your workflows. Make sure you also have ticked permission to "send e-mail" and take a closer look at your e-mail configuration.

**Comment by Seitrafficonline** [comment]
i did it. but is not working. not sending mail. there is any way even by paying to get assistance?

**Comment by Bergdahls** [comment]
Dear Seitraffic,
You have probably an configuration problem. Check your settings path in CRM config.inc.php and portal config.php so you have the correct url. Try to remove you top domain, it can be wrong depends of you dns config in server. For example remove www or what you have so you got just domain $PORTAL_URL = 'http://yourdomain.com';. Very important that you really can get generated password for login via your mail so your mail are correct configured as described above.
