### ISSUE TITLE
RFE: Add possibility to create calculated field

### ISSUE THREAD

**Issue by ChristopheLux** [YetiForceCompany/YetiForceCRM#2719]
Hello

Would be create to create calculated field (and not to go through workflow) so that field is updated when the user is editing the record

Maybe would be worth to have a look at http://dev.mensfeld.pl/bootstrap-calculator/index.html for the calculated field editor
or https://github.com/zoul0813/jquery-calc

Thanks for taking this into consideration
Regards

**Comment by offtopic242** [comment]
This would be great. +1.

**Comment by bpabiszczak** [comment]
We're not planning to introduce this functionality in the nearest future.

**Comment by ldgbc** [comment]
An application for this would be Age/Birthdate. Currently I just export to Excel then use it formula function to calculate.
