### ISSUE TITLE
Define a schedule for execution not working

### ISSUE THREAD

**Issue by sangeetasoni19** [YetiForceCompany/YetiForceCRM#2725]
I am trying to create a workflow to send SMS with option "Define a schedule for execution". But didn't receive SMS on the scheduled  time.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
we didn't receive basic information about this issue, please refer to the article: https://yetiforce.com/en/developer-documentation/bugs/126-issues.html
You haven't verified whether this mechanism works or not in gitdeveloper version.
We don't support the SMS module, it will be re-written and re-designed. It will probably appear in 3.1/3.2.
