### ISSUE TITLE
Emails not linking to Contacts in OSSMail

### ISSUE THREAD

**Issue by vtigerdevel** [YetiForceCompany/YetiForceCRM#2726]
I am using the developer branch. When sending a mail from contacts, it does not link the mail to the contact. Also, if i try sending a mail from the "Corporate Mails" module, it does not allow to select any contacts.

**Comment by mariuszkrzaczkowski** [comment]
Check the following things:
-is your mail scanner running?
-are any actions set eg. creating a mail and relating it to a contact?
-are there any folders set for scanning in mail scanner (eg. sent and received mails folders)?
-are fields to search the address by set?
-is your mail scanner enabled in Cron?
-are any exceptions set?
