### ISSUE TITLE
Text messages

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2728]
In the old interface there is a button for sending text messages to contacts. We use that a lot for example if people send support emails but we can't send something back because their mailbox is full.

In the newer interface (v.1072) I am unable to find this option. Can someone tell me how to send text messages in the new interface?

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
the mechanism has been removed (in fact, only the buttons because we rebuilt them) as we inherited this  module from Vtiger and we haven't rebuilt it yet. Soon, we will bring the buttons back (ver. 3.1/3.2) or you can do it yourself.
