### ISSUE TITLE
Lead to contact coversion

### ISSUE THREAD

**Issue by Seitrafficonline** [YetiForceCompany/YetiForceCRM#2731]
Hi
how can i convert a lead to contact so i can activate is access to the portal. Or, there is anyway to activate directly the lead to portal?
Thanks

**Comment by Seitrafficonline** [comment]
im adding a picture to show that there is no button on it to convert lead to client
![leads](https://cloud.githubusercontent.com/assets/16775027/13201976/ec68c47c-d890-11e5-94e7-2bc6631c7ecb.jpg)

**Comment by paula-w** [comment]
The mechanism in the system only lets you convert to account, not contact. 
We're not planning to change it.
