### ISSUE TITLE
Fatal error in Projects module

### ISSUE THREAD

**Issue by Alexvw78** [YetiForceCompany/YetiForceCRM#2733]
![project](https://cloud.githubusercontent.com/assets/16573997/13072945/4bcaed1c-d49c-11e5-8be0-d0b410d2f6e9.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/d2fec6d98087cc82a410738897a891b5090839cc
