### ISSUE TITLE
[Stable version]Dodanie bloku o produktach w innym module

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2740]
Witam,

W jaki sposób można dodać blok o produktach(tak jak jest w fakturach przykładowo) w module oferty?

**Comment by florek41** [comment]
W nadchodzącej wersji (2.4) moduł ofert ma blok produktowy. Względem wersji 2.3 moduły sprzedażowe zostały zmienione i dodanie bloku z produktami odbywa się poprzez zmianę typu z Podstawowego na Zaawansowany (https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=SQuotes)

![advanced_block](https://cloud.githubusercontent.com/assets/4824588/13201969/35d90b5c-d888-11e5-815a-4b0bc8546bce.JPG)

**Comment by amdziak** [comment]
Chodzi mi o wersję stabilną i możliwość edycji pól, a także dodawania całego bloku w innych modułach(jeśli nie ma możliwości wyklikania tego z panelu to prosiłbym o jakieś wskazówki dotyczące developowania tego obszaru i ewentualnego dodawania go w innych modułach).
Chodzi o ten blok:
![produkty](https://cloud.githubusercontent.com/assets/11409255/13221992/347067be-d97e-11e5-9804-65d6c24e7cfc.PNG)

**Comment by florek41** [comment]
W tej kwestii Ci nie pomogę - mogę jedynie powiedzieć, że nie da rady tego wyklikać.
Weź pod uwagę że następna wersja stabilna (przewidziana na 7 marca) będzie miała ten mechanizm przebudowany.

**Comment by amdziak** [comment]
Tak myślałem - już zacząłem to implementować :)
Czy data jest już pewna?
Czy w nowej wersji będą przesunięcia międzymagazynowe(z wystawieniem WZ-ki)?

**Comment by florek41** [comment]
A co, oprócz śmierci, jest pewne? ;)
Wygląda na to, że tak.
Aktualna wersja rozwojowa jest dostępna pod adresem: https://gitdeveloper.yetiforce.com/

**Comment by bpabiszczak** [comment]
Podatki są pewne :D 
Data nie jest pewne, ale trzeba być optymistą :)
A poco MM z WZ jednocześnie....

**Comment by amdziak** [comment]
MM, czyli chodzi o ruchy miedzy magazynowe?
99% firm wymaga WZ przy takich ruchach :)
Wyobraźmy sobie firmę, która wytwarza produkt X z podproduktów, ale nie wytwarza tego sama, ale u poddostawców - produkt surowy idzie do pierwszego(przesuniecie z magazynu glownego na magazyn poddostawcy) i potrzebujemy do tego WZ-ki...

**Comment by bpabiszczak** [comment]
Rozumiem tzw. MM+ i MM-, nie rozumiem, po co robić MM a do tego WZ i PZ [czyli 3 dokumenty zamiast 2)

**Comment by amdziak** [comment]
Bo tego praktycznie rzecz biorąc wymaga wiele firm i w wielu przypadkach przepisy prawa polskiego :)

**Comment by bpabiszczak** [comment]
Poproszę o te przepisy prawa

**Comment by bpabiszczak** [comment]
"O zasadach obiegu dowodów księgowych, wyborze stosowanych rodzajów dowodów decyduje kierownik jednostki, kierując się specyfiką i rozmiarem prowadzonej działalności, mając na uwadze potrzebę wiarygodnego i obiektywnego przedstawienia zachodzących w niej zdarzeń gospodarczych. Organizacja obiegu dowodów księgowych powinna być ujęta na piśmie w formie zarządzenia wydanego przez kierownika jednostki.

Podstawą zapisów w księgach rachunkowych są dowody księgowe stwierdzające dokonanie operacji gospodarczej (art. 20 ust. 2 ustawy o rachunkowości). Wśród dowodów księgowych ustawa o rachunkowości wymienia dowody:

a) zewnętrzne obce - otrzymywane od kontrahentów,

b) zewnętrzne własne - przekazywane w oryginale kontrahentom,

c) wewnętrzne - dotyczące operacji wewnątrz jednostki.

Wz jest dowodem magazynowym dokumentującym wydanie towaru na zewnątrz, a faktura sprzedaży jest dowodem dokumentującym sprzedaż i należność od kontrahenta.

Ustawa o rachunkowości nie reguluje szczegółowo rodzajów i wzorów dowodów księgowych, za pomocą których jednostki mają dokumentować obrót magazynowy. Większość jednostek zwyczajowo stosuje do ujęcia ruchów w magazynie takie dokumenty jak Wz i Pz, ponieważ zapewniają one realizację przez kierownika jednostki odpowiedniej organizacji rachunkowości i kontroli wewnętrznej, które zostały nałożone przepisami ustawy o rachunkowości.

Dozwolonym rozwiązaniem jest również wprowadzenie przez jednostkę własnych wzorów dowodów księgowych dokumentujących poszczególne rodzaje operacji gospodarczych, pod warunkiem, że będą one spełniać warunki dla dowodów księgowych określone w art. 21 oraz art. 22 ustawy o rachunkowości i będą realizować zasadę rzetelnego obrazu wynikającą z art. 4 ust. 1 ustawy o rachunkowości. 
 

Jednostka może przyjąć w swoich zasadach obiegu dokumentów, iż podstawą do wydania towarów z magazynu jest faktura sprzedaży pod warunkiem, że data wystawienia faktury jest tożsama z datą wydania towaru.

W sytuacji jednak, gdy termin wydania towaru z magazynu nie pokrywa się z datą wystawienia faktury, to zgodnie z zasadą zawartą w art. 20 ust. 1 ustawy o rachunkowości do ksiąg rachunkowych okresu sprawozdawczego należy wprowadzić, w postaci zapisu, każde zdarzenie, które nastąpiło w tym okresie sprawozdawczym. Oznacza to, że należy osobnym dowodem źródłowym udokumentować wydanie towaru z magazynu, a wystawioną później fakturą VAT potwierdzić dokonanie sprzedaży towaru."

**Comment by amdziak** [comment]
Ja ich nie znam - wiem tylko co wielu klientów ode mnie wymaga :)
Ale wiem, że w wielu przypadkach WZ są księgowane w KPiR, w momencie gdy towar trafia do obrotu(sprzedaży) przed wystawieniem FV.

**Comment by bpabiszczak** [comment]
Ale ja nie dyskutuje o potrzebie wystawiania WZ, ja zadałem pytanie po co ktoś wystawia MM a do tego następnie WZ i PZ.

**Comment by amdziak** [comment]
W dalszym ciągu nie rozumiem czym jest MM, MM+ i MM-.

**Comment by bpabiszczak** [comment]
"Dokument MM (a właściwie MM+/MM-) jest papierem towarzyszącym przesunięciom 
pomiędzy magazynami w ramach tego samego podmiotu gospodarczego.
Gdy sprzedawca pralek z Warszawy ma za dużo towaru to może wysłać go do 
swojej filli w Krakowie i zdejmie to ze stanu dokumentem o przykładowym 
numerze MM-/0133/2007 a magazynier w Krakowie przyjmie te pralki na swój 
stan dokumentem MM+/0133/2007.

Między osobnymi podmiotami gospodarczymi powinny krążyć WZ-tki (do wiedzy 
spedytora, kierowcy, magazyniera) a do rąk księgowej, i/lub innej osoby 
fakturującej powinna przyjść faktura VAT."

**Comment by amdziak** [comment]
Więc teraz rozumiem - można powiedzieć, że dokument MM jest szczególnym przypadkiem WZ-ki - czyli jest to wydrukowane potwierdzenie operacji magazynowej.
Teraz jest dla mnie wszystko jasne :)

**Comment by amdziak** [comment]
Jak w aktualnej wersji softu (gitdeveloper.yetifocre.com) wygenerować WZ-kę - w sensie jako PDF-a?
BTW: czy dzisiejsza data wydania nowej wersji jest aktualna? :)

**Comment by bpabiszczak** [comment]
Raczej nie aktualna, ale na dniach pojawi się nowa wersja. 
PDFy są domyślnie w systemie, na gitdevelop należy dodać usera demo do uprawnionych w szablonie.

**Comment by amdziak** [comment]
A można wiedzieć co zostało jeszcze do zrobienia?
I skąd można ściągnąć aktualną (zgodną z gitdevelopem) paczkę (nie wyznaje się na githubie - zawsze omijałem go z daleka :))?

**Comment by bpabiszczak** [comment]
Brakuje wykończenie procesów [np. finansowy], przetestowania porządnego tego co jest [np. proces sprzedażowy i magazynowy] zrobienie porządnie eksportu/importu aby umożliwić migracje z wcześniejszej wersji...

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer
