### ISSUE TITLE
[PL][BUG] Kalendarz - błąd przy szybkim tworzeniu  + dodatkowy checkbox

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2742]
Przy korzystaniu z funkcji 'szybkie tworzenie' (niezależnie czy wybierając "+" jak na zrzucie, czy np. tworząc nowe zdarzenie z poziomu kontrahenta itp) wyrzuca błąd. Dodatkowo pojawił się niepotrzebny (?) checkbox.

![calendar](https://cloud.githubusercontent.com/assets/4824588/13205386/3ce59938-d8e7-11e5-88fe-212514480743.gif)

``
{"success":true,"result":{"subject":{"value":"test2","display_value":"test2"},"reminder_time":{"value":"","display_value":""},"assigned_user_id":{"value":"5","display_value":"<a href=index.php?module=Users&parent=Settings&view=Detail&record=5>YetiForce Demo<\/a>"},"date_start":{"value":"2016-02-21","display_value":"2016-02-21"},"time_start":{"value":"20:57:00","display_value":"20:57"},"time_end":{"value":"21:02:00","display_value":"21:02"},"shownerid":{"value":"","display_value":""},"due_date":{"value":"2016-02-21","display_value":"2016-02-21"},"recurringtype":{"value":"","display_value":""},"activitystatus":{"value":"PLL_IN_REALIZATION","display_value":"Do realizacji"},"taskpriority":{"value":"Low","display_value":"Niski"},"sendnotification":{"value":"","display_value":""},"modifiedtime":{"value":"2016-02-21 20:58:01","display_value":"2016-02-21 20:58"},"createdtime":{"value":"2016-02-21 20:58:01","display_value":"2016-02-21 20:58"},"created_user_id":{"value":"","display_value":""},"activitytype":{"value":"Meeting","display_value":"Spotkanie"},"visibility":{"value":"Public","display_value":"Publiczne"},"duration_hours":{"display_value":"0","value":"0"},"was_read":{"value":"","display_value":""},"duration_minutes":{"value":"5","display_value":"5"},"state":{"value":"PLL_OPAQUE","display_value":"Zaj\u0119ty"},"location":{"value":"","display_value":""},"notime":{"value":"","display_value":""},"modifiedby":{"value":"5","display_value":"YetiForce Demo"},"closedtime":{"value":"","display_value":"2016-02-21"},"allday":{"value":"0","display_value":"Nie"},"description":{"value":"","display_value":""},"link":{"value":"","display_value":""},"process":{"value":"","display_value":""},"subprocess":{"value":"","display_value":""},"followup":{"value":"","display_value":""},"_recordLabel":"test2","_recordId":125}}
``

**Comment by bpabiszczak** [comment]
checkbox służy do automatycznego wyznaczania kolejnego wolnego terminu :]
