### ISSUE TITLE
[Improvement] Module Products Reservation/Pre-Order in Calendar View

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2748]
I have a **suggestion** to add a **Module**: **Produtcs Reservation** similar to Reservation of the Secretary. So adding a new record in the **Calendar View**. 

Use: rental of Products / equipment company, usage of Products / equipment company by employees, eg. for the presentation (MM does not fix the problem).

I tried to add additional fields in the  Reservations / Advanced Blocks (as it is in the Pre-Order) but no effect. 
Tested on ver. developer
https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=Reservations

**Comment by paula-w** [comment]
We're not planning to add this mechanism to the calendar. Rentals will be supported primarily by the storage modules. We'll also create a new module for equipment rental in the future.

**Comment by blu-IT** [comment]
Hallo.

any news on this function?

Thanks!

**Comment by bpabiszczak** [comment]
No
