### ISSUE TITLE
[Bug] Advanced Blocks in the Module Secretary > Reservations

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2749]
I tried to add additional fields (Product List) in the **Reservations** / Advanced Blocks (as it is in the Pre-Order) but no effect on the full form Create Reservation.  

It may not be ready yet? ;)

Tested on ver. developer
https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=Reservations
![reservations1](https://cloud.githubusercontent.com/assets/17315868/13353851/7269b1d0-dc97-11e5-8bf7-0a90f830448a.png)

**Comment by paula-w** [comment]
This mechanism wasn't designed to be used with the Reservations module. It has not been tested there, and might generate errors. This tool is designed for developers, not regular users. In case you spot an error we recommend sending a fix to our GitHub. 
We're not planning to verify the validity of this mechanism for all the modules (there are simply too many of them), you should use it with caution.
