### ISSUE TITLE
[Bug YF ver. 2.3.49] File does not exist, error

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2752]
Hi,

I think where is the problem. On the hosting I have several scripts PHP (joomla, wordpres, vtiger, dolibarr, suitecrm, zurmo, glpi ... and the two instances **YetiForce ver. 2.3.49** - one new installation without modification, and the other configured). All errors that are reported refer only to yetiforce (both installations). And after turning display_errors, the screen is flooded with errors. 
I'm not a programmer, and I'm not sure if these errors are important, or may result from configuration server, or maybe the problem is in yetiforce?

**web server conf.**: **PHP v.5.6.18** Current configuration = Recommended configuration ~output_buffering =OFF, ~max_execution_time =30
Support for libraries: ALL ~LDAP

examples of errors:
_[Sat Feb 27 13:33:21 2016] [error] [client xx.xxx.xxx.149] File does not exist: /public_html/doemna/500.shtml, referer: http://domena/yeti/index.php?module=Products&view=Detail&record=112
[Sat Feb 27 13:29:54 2016] [error] [client xx.xxx.xxx.149] File does not exist: /public_html/doemna/500.shtml, referer: http://domena/yeti/index.php?module=Products&view=List
[Sat Feb 27 13:22:30 2016] [error] [client xx.xxx.xxx.149] File does not exist: /public_html/doemna/500.shtml, referer: http://domena/yeti/index.php_

display_errors=On 
![yeti_error_display2](https://cloud.githubusercontent.com/assets/17315868/13375915/2dd1f6a6-ddad-11e5-8527-46f354f012db.png)

**Comment by florek41** [comment]
First of all you need display only errors, not info and warnings. Change error_reporting to _E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT_

**Comment by Remi007** [comment]
Thx for your quick response. 
I can't change to E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT... on this hosting. I can set up E_ALL or E_ALL & ~E_NOTICE or ~E_ALL. But this is not a problem and I hope that these warnings and messages such as E_STRICT/E_DEPRECATED/E_WARNING are not a problem or are not related to with the error? If not problem, the issue is closed.
