### ISSUE TITLE
[PL][Improvement] Filters and sorting order 

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2753]
Widzę, że aktualnie pracujecie nad filtrami i ich konfiguracją (szczególnie @rskrzypczak :wink: ) Może to dobry czas, żeby pomyśleć o możliwości zdefiniowania kolejności i kolumny sortowania przy edycji filtru ?

EN.
I see that you are currently working on the filters and their configuration. Maybe it's a good time to think about the possibility of defining the order and the sort column when editing a filter?

**Comment by bpabiszczak** [comment]
Sortowanie było, jest i będzie. Co prawda nie per filtr a per moduł ale jest [konfiguruje się z poziomu głównego pliku]. Problem jednak polega na tym, że sortowanie ZABIJA bazę danych i coś co mogło trwać 0.05s może trwać 100x dłużej.

**Comment by bpabiszczak** [comment]
Można testować w najnowszej wersji [dostępne tylko z poziomu panelu, aby użytkownikowi się w głowie nie poprzewracało].
