### ISSUE TITLE
[bug] DataAccess condition not work

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2755]
![gif](https://cloud.githubusercontent.com/assets/15871611/13461995/1e956e66-e096-11e5-8343-0751431b4527.gif)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/29e7c549d26b511b4e5bcfd5204fdb60c5dd7321
