### ISSUE TITLE
Change sliding menu

### ISSUE THREAD

**Issue by silverskysoft** [YetiForceCompany/YetiForceCRM#2757]
Hi,
I'm looking at the demo on developer branch. 
This has changed to sliding menu when we hover over -- this also moves the center main page to the right. This shifting is distracting for many users we have. Is there way we can go back to the original menu on the top. Or at the least, slide out the menu over current page instead of sliding?

![yetiforceslidingmenu](https://cloud.githubusercontent.com/assets/13212511/13516283/994238c4-e16d-11e5-82bd-16a2d0632a35.gif)

Thanks.

**Comment by silverskysoft** [comment]
Any comments on if this is possible? Some setting perhaps I'm missing?

**Comment by reeid** [comment]
In my opinion submenu should be opened in the vertical main menu section (accordion),
Current state indeed distracting by covering area what we usually like to focus on.
Also opening menu on hoover is not good. Should be activated by click. Different behavior can be set depending device, but majority works on PC so, optimization needs to be focused on that part.

**Comment by diderich** [comment]
For those interested, please find a screenshot of the SAP CRM user interface
- Main meun on the top
- Sub-menu just below
- Icons on the left as shortcuts to specific items
- Configuration and user information on the top-right
No hovering, only clicking. To me their user interface uses the full screen very wisely.

![sap-lead](https://cloud.githubusercontent.com/assets/10230144/13709054/42b587f4-e7b2-11e5-9983-96bb59b8a906.png)

**Comment by silverskysoft** [comment]
@diderich, Thanks for that reference screenshot. One question, if you click on left hand menu items - say calendar or dialer, how does the UI look?

**Comment by diderich** [comment]
Here is how the screen looks, when creating a new appointment through clicking on an icon on the left side of the screen:
![new-appointment](https://cloud.githubusercontent.com/assets/10230144/13721489/83f29dfc-e829-11e5-8edf-be0121249d9b.png)

**Comment by diderich** [comment]
Although not menu specific, here is a screen shot when looing at a lead. Information which YetiForce has on multiple pages, is consolidated on one page and the focus is on that information (appointments, tasks, calls, e-mails) rather than on the lead data (account information, contact information, ...).
![lead](https://cloud.githubusercontent.com/assets/10230144/13721501/cc078cec-e829-11e5-834f-5ee591420b8a.png)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
we don't plan to change the menu. The system has a built-in support for many templates, you can send us a ready template which changes the functionality of the main menu.
