### ISSUE TITLE
Error!!!  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yeti.vtiger_organizationdetails' doesn't exist

### ISSUE THREAD

**Issue by stealsinc** [YetiForceCompany/YetiForceCRM#2760]
Error!!!
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yeti.vtiger_organizationdetails' doesn't exist

Does not work with both home server XAMPP Install, and paid shared hosting server Softaculous install

**Comment by kpaulaha** [comment]
I have one installation on XAMPP 5.6.3, working fine with no problems.

**Comment by stealsinc** [comment]
I have 5.6.15, I will try  5.6.33. I need a solution for my paid shared hosting server.

**Comment by stealsinc** [comment]
Results from install on XAMPP 5.6.3 
http://localhost/yeti/install/Install.php
![yetiforce 2016-03-09 01-43-17](https://cloud.githubusercontent.com/assets/17715500/13628541/871a1638-e598-11e5-832c-af9b8db78d49.png)

**Comment by waw555** [comment]
I have the same problem in conjunction Debian 8.3 + Vestacp. (All Debian and Vestacp default settings)

**Comment by waw555** [comment]
in my.cnf comment 
#wait_timeout=10
#interactive_timeout=50

its work )))

**Comment by stealsinc** [comment]
So where is the my.cnf file?

**Comment by amdziak** [comment]
This is the configuration file for MySQL. In Linux, the most common is /etc/mysql/my.cnf or /etc/my.cnf

**Comment by stealsinc** [comment]
Thanks, I forgot ot mention that I am on XAMPP with WIN 7... I can't seem to find my.cnf

**Comment by amdziak** [comment]
In your XAMPP control panel click config and select my.cnf or my.ini - i don't remember.
And the best type in google XAMPP + my.cnf :)

**Comment by stealsinc** [comment]
For Windows/XAMPP it should be my.ini ~
The reference to my.cnf is due to MySQL's *nix hertitage, It is devloped on Unix derivatives then ported/compiled for Windows.

**Comment by stealsinc** [comment]
Ok, I've tried everything, all the tricks and fixes, developer version... etc., etc.,... Paid support install or or stick with vtiger. How much is a install? Do I get a refund if it's a Yeti issue/bug/problem?

**Comment by stealsinc** [comment]
kpaulaha: did you follow the Yeti setup specs? or default everything? On Win7? Did you drop it into htdocs and run localhost/yetiforce?

**Comment by kpaulaha** [comment]
Well, currently it's running on win10, but has been on win7 also. The translation are made on that computer, so yf has been installed on it tens of times, latest couple minutes ago. First had some time-out problem, but after fixing php-conf, nothing.

**Comment by stealsinc** [comment]
Wow! maybe it does not work in North America... Did you have to follow the Yeti setup specs exaclty?
It's odd that the Softaculous demo works that comes with my hosting Cpanel. I emailed Yeti for a install consultation.

**Comment by paula-w** [comment]
1. The users don't acquire any warranty or support when they download YetiForce. We provide support on GitHub, but we do it in our free time, provided that the issue is well described.
2. It is possible to purchase paid support, then no matter what the problem is [server, YetiForce, or configuration] we always charge for the time our developers spent working on the solution. 
3. We don't recommend Windows as the web environment for YetiForce.

**Comment by kpaulaha** [comment]
Mainly followed the yeti specs, but had to do some mods. This is the only win we have it running on and just for translating language files. Production is always on linux. Don't think so much difference between NA and N Europe. Check the time-out, we have the xampp running on a quite powerful comp, one older one could not have yf installed with the default time-outs.

**Comment by stealsinc** [comment]
Great, thanks... So I will will try my luck with a Linux install. Which Linux do you recommend?

**Comment by kpaulaha** [comment]
We have it on both debian and ubuntu. If you still try on xampp, configure the php.ini as yeti install requirements and also try changing the .htaccess on yeti, we had problem with that. Now Yeti works fine for us on xampp for local/test use. 


-------- Alkuperäinen viesti --------
Lähettäjä: stealsinc <notifications@github.com> 
Päivämäärä: 15.03.2016  20.42  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] Error!!!  SQLSTATE[42S02]: Base table or view not
  found: 1146 Table 'yeti.vtiger_organizationdetails' doesn't exist (#2760) 

Great, thanks... So I will will try my luck with a Linux install. Which Linux do you recommend?

**Comment by stealsinc** [comment]
Great, thanks. Is it possible to translate Yeti to Spanish.

**Comment by kpaulaha** [comment]
Well, maybe you have to begin with it your self? My Spanish knowledge is not much more than "Hasta la vista, baby". We have translated yf to Finnish and soon to Swedish, but we had translated vtiger to same languages, so it was easy to continue thom that. There is a great tool in yf for translations.

**Comment by stealsinc** [comment]
lol... Thanks, I'll use the Yeti tool.

**Comment by stealsinc** [comment]
Installed on Ubuntu... It works.
