### ISSUE TITLE
Opportunity Report

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#2761]
Is it possible to following in the future in the REPORT MODULE?:

Main Report Module: Opportunities
Select related modules: Accounts

Best Ralph

**Comment by ralphkretzschmar** [comment]
In the MASTER/STABLE is it still available but not in the DEVELOPER version :)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2708
