### ISSUE TITLE
Kilka pytań odnośnie procesów magazynowych...

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2763]
Pytania dotyczą wersji 2.3.1449.

1) Chce zrobić kilka magazynów nadrzędnych - w jaki sposób to zrobić? Przy dodawaniu drugiego i kolejnych magazynów muszę wypełnić pole Magazyn nadrzedny - inaczej nie mogę zapisać zmian...
2) W jaki sposób wykonać przeniesienie magazynowe produktu z magazynu A do B? Nie mogę znaleźć takiej funkcji...
3) Przy tworzeniu WZ nie aktualizuje się stan magazynowy. Zrobiłem najpierw Przyjęcie z zewnątrz do magazynu A, następnie WZ z magazynu A dla połowy produktów - w zakładce Produkty dalej jest pełna ilość produktów.

Wszystkie procesy mają status Zaakceptowany.

I tak jeszcze z innej beczki: dlaczego nie można stworzyć własnego modułu? Po wypełnieniu formularza podstawowego opcja Zapisz nie jest dostępna.

**Comment by bpabiszczak** [comment]
1. Obecnie obsługiwane są tylko magazyny wewnętrzne [jeden główny i wszystkie inne muszą być niżej w hierarchii]. Do czego potrzebujesz magazyny nadrzędne? 
2. Używając modułów MW i MP. 
3. U mnie się zaktualizował. Napisz dokładnie krok po kroku jak wywołać ten błąd na gitdeveloper, a najlepiej nagraj filmik aplikacją screen2gif

**Comment by amdziak** [comment]
1. Chciałbym mieć kilka głównych magazynów (różne lokalizacje) i do niego podpięte po dwa poboczne - reklamacyjny i produkcyjny.
2. Ok - potestuję.
3. Nad ranem udało mi się dojść do tego - więc pytanie nie aktualne :)

A co z tworzeniem modułów z panelu administracyjnego?

**Comment by bpabiszczak** [comment]
Jeden problem jeden wątek. Obecnie nie ma obsługi magazynów zewnętrznych.
