### ISSUE TITLE
Text in PDF cut off (quotes)

### ISSUE THREAD

**Issue by ghost** [YetiForceCompany/YetiForceCRM#2764]
the description is saved in the following tables:
 yeticrm.vtiger_crmentity
 yeticrm.vtiger_inventoryproductrel

But on the PDF the description is cut off.
I'have already changed the field to TEXT (mysql) but it didn't help

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
please read the following article: https://yetiforce.com/en/developer-documentation/bugs/126-issues.html
You didn't provide the necessary information, such as: version number and where exactly and what you changed in the data base.
