### ISSUE TITLE
[Bug] SQLSTATE[42000] in YF developer / module=OSSTimeControl

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2768]
Action Performed
1. Go to https://gitdeveloper.yetiforce.com/index.php YF ver. 2.3.1464 (GitDeveloper)
2. Hoover over Main Menu: "Human Resources" and click on menu link: "Time Control" [**module=OSSTimeControl**]
3. Change view to Records List
4. Select single row and click on button "Action" and click on menu link "Export"
5. Click on button "**Export Time Control**" (option Export Selected Records was selected) 

Actual Result / Error Message:
**SQLSTATE[42000]**: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
![animation](https://cloud.githubusercontent.com/assets/17315868/13710569/894cba86-e7ba-11e5-9fab-dd019fb389d1.gif)
![skjermbilde 30](https://cloud.githubusercontent.com/assets/17315868/13710584/9815bf86-e7ba-11e5-884f-27981b3d277b.png)

**Comment by TomaszQr** [comment]
Fix https://github.com/YetiForceCompany/YetiForceCRM/commit/9f544bb1baeceed112aa3dc82fb5d3aef3db5d1f
