### ISSUE TITLE
Nie można stworzyć modułu z panelu

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2769]
Witam,

Dlaczego nie można stworzyć własnego modułu z panelu administracyjnego? Po wypełnieniu formularza podstawowego opcja Zapisz nie jest dostępna.
Wersja 2.3.1449

**Comment by bpabiszczak** [comment]
Ale gdzie to próbujesz zrobić u nas na serwerze czy u siebie?

**Comment by amdziak** [comment]
U siebie na serwerze.
Serwer spełnia wszystkie wymagania instalacji.

**Comment by bpabiszczak** [comment]
Nagraj film za pomocą screen2gif

**Comment by amdziak** [comment]
Rozwiązane - mój błąd.
Pole podświetla się trochę z opóźnieniem...
