### ISSUE TITLE
Błąd - funkcjonowanie własnego modułu

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2770]
Piszę po polsku, aby łatwiej przekazać zauważony problem.
Testowane na wersji developerskiej i master.

Przy testach wcześniejszych nie zauważyłem problemu - tak więc nie wiem po jakich zmianach problemy się zaczęły.

Chcę posiadać moduł z wyborem pozycji z modułu także własnego - niekoniecznie z produktów, wraz z dodatkowymi polami wartości.

Tworzę moduł - dodaję dwie, trzy wartości...
Tworzę moduł kolejny - już wyborem pozycji z wcześniej utworzonego plus dodatkowe pola - ceny , ilości, podatku i własnych wartości.

Przy pierwszym zapisie wszystko wygląda - że jest ok.. niestety po edycji - np po usunięciu pozycji - pozostaje jako pusta. 

Co może być problemem.

Utworzenie modułu i pozycji do wyboru w drugim module.

![modul-wybor](https://cloud.githubusercontent.com/assets/11014419/13728542/7dff2a70-e91c-11e5-983c-be1c93edb99f.gif)

Niepoprawne działanie.

![modul-wybor-blad](https://cloud.githubusercontent.com/assets/11014419/13728549/bfffb55c-e91c-11e5-9766-2a825e5df017.gif)

**Comment by zimart** [comment]
Po kolejnym przeklikiwaniu problemu, wydaje mi się że problem jest w polu " komentarz" - przy pozycji..

**Comment by bpabiszczak** [comment]
Trzeba zerknąć w logi :] Tam jest odpowiedź na każde pytanie.
