### ISSUE TITLE
Search feature, incorrect labels if UItype 10 field is included

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#2771]
If fields which are shown is search result display contains an UItype 10 field, labels are incorrect.

Steps to reproduce the issue, go to Search Setup :
- set Accounts with accountname and Primary Email as labels and searchable fields
- set Contacts with Firstname and Member Of as labels and searchable fields
Try to search for a contact record --> search result display as 'Firstname + Member Of + (related account) Primary Email' instead of 'Firstname + Member Of'

Related to #2732

**Comment by rskrzypczak** [comment]
Hi, 
What you described is completely alright. You set the Account to display as name + email and so the system displays it this way.
![searchlabel6](https://cloud.githubusercontent.com/assets/10221999/14953847/c1b7e8ec-106d-11e6-9177-0705e47aec20.gif)

**Comment by apcloic** [comment]
Hi,
No I set the Account to display as name + email only on search results, not everywhere on the CRM.
On a contact detail view, Member Of should display account name only and not "account name + email"
