### ISSUE TITLE
Search feature, incorrect labels sequence

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#2772]
Step to reproduce the issue :
Go to Search Setup --> Account --> set Primary Email + Account Name as fields which are shown is search result display and columns for search mechanism
Try to search an Account --> search result display 'Account name + Primary Email' instead of 'Primary Email + Account name'
So it looks like search results do not take fields order/sequence into account.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2771
