### ISSUE TITLE
Jak zdjąć wymagalność pola

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2774]
Przykładowo Pole Pytanie w module Instrukcje - z poziomu GUI nie można zdjąć wymagalności tego pola, ani tym bardziej go usunąć - w jaki sposób można to zrobić?
Wersja 2.3.1464

**Comment by amdziak** [comment]
Nieaktualne.
Dla potomnych:
W tabeli vtiger_field zmieniamy wartość pola typeofdata dla danego pola z V~M na V~O.

Ticket do zamknięcia.

**Comment by bpabiszczak** [comment]
Tylko miej świadomość konsekwencji... system wówczas może generować błędy w wielu miejscach.

**Comment by amdziak** [comment]
Z tego co czytałem na forum vtigera nie powinno być problemów, ale będę pamiętał :)
Zresztą robię to w mało znaczącym module...

**Comment by bpabiszczak** [comment]
Wyłączasz pole oznaczone jako systemowe którego nie należy zmieniać. Nie wiem gdzie to pisali... ale Vtiger to nie YetiForce.
