### ISSUE TITLE
[bug] - Pirce book - export

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2775]
![animation 6](https://cloud.githubusercontent.com/assets/11491482/13872304/da4af608-ece9-11e5-8bc8-ca80d15d8843.gif)

**Comment by TomaszQr** [comment]
Fix https://github.com/YetiForceCompany/YetiForceCRM/commit/9f544bb1baeceed112aa3dc82fb5d3aef3db5d1f
