### ISSUE TITLE
[bug] - product quantity 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2776]
There is issue of entering quantity of product during creating product record. I understand that it is link with storage but in case when product is produced...
![animation 0](https://cloud.githubusercontent.com/assets/11491482/13872452/121c5454-eceb-11e5-8b87-0c60fa849110.gif)

**Comment by vovpff** [comment]
You need to add new storage after that use storage module to add increase or decrease qty of goods.
