### ISSUE TITLE
[Explanation needed] Storage (logistics) module and fuctions

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2781]
I tried storage module in develorer ver. It is very usefull but i sometimes I don't understand logics. Somebody can give explanations for this module and additional functions in logistics tab?

**Comment by paula-w** [comment]
This module is used for multistorage purposes, we can add multiple storages [for now only internal ones], and this way we can select the proper storage in other storage documents.
