### ISSUE TITLE
[Bug] Default field mask not working

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2782]
![image](https://cloud.githubusercontent.com/assets/8545791/13904498/f376ad7c-eeb3-11e5-90cf-2833c2548696.png)
Default field mask isn't work for fields with UItype "phone"

**Comment by paula-w** [comment]
Why should the "Unit price" field have a mask? We don't quite understand what the problem here is.

**Comment by vovpff** [comment]
Sorry. This is not so good screenshot. Field mask not working with phone numbers
