### ISSUE TITLE
[Feature request] Preview header copy button

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2783]
There is possibility to made some fields previewed in header by activationg this option.
![image](https://cloud.githubusercontent.com/assets/8545791/13904509/543115a8-eeb4-11e5-8c8c-20014070b12c.png)
This is a good idea to made in priviewed field copy text botton ![image](https://cloud.githubusercontent.com/assets/8545791/13904524/becd67d6-eeb4-11e5-998a-f14218332dbf.png) to quick copy information to clipboard.
One more great feature is a copy all header information by clicking special botton.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
we don't plan to add such functionality. However, if you write such functionality based on privileges, we can add it to the system but for now we don't see any business justification behind it.

**Comment by vovpff** [comment]
Sorry too much for my issue. I don't have experience in programming and can only help to your project only by testing but i'm very interested in YetiForce CRM system. Now I use vT 6.4 and quick copy of some field data gets 3 clicks (for example description of product) but my idea (copy botton or copy by click) can be very usefull
