### ISSUE TITLE
[bug] Tracking changes

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2784]
If ![image](https://cloud.githubusercontent.com/assets/8545791/13904590/ec40c346-eeb6-11e5-8da6-f45a5c98d1bd.png) botton is activated for module or record there is no notifications appears after record modification by differen user

**Comment by paula-w** [comment]
The notifications can be configured from the workflow level. By default, there are no predefined notifications, so there's nothing to track.
