### ISSUE TITLE
Scheduled Reports

### ISSUE THREAD

**Issue by proyectosit** [YetiForceCompany/YetiForceCRM#2790]
Do you know how to send scheduled reports in XLS format? 
I've tried doing some changes on "ScheduledReports.php" without success.

Thanks for your advice;
Regards,
GP

**Comment by acidhunter** [comment]
We wrote a little page for vTiger that allow to send xls files via Scheduled Reports
it is located at  /modules/Reports/models/ScheduleReports.php


[ScheduleReports.php.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/248641/ScheduleReports.php.txt)

**Comment by acidhunter** [comment]
in detail, we added

line 14
	var $scheduledFormat = 'EXCEL';

line 209 	
	if ($reportFormat == 'EXCEL') {
			$fileName = $baseFileName.'.xls';
			$filePath = 'storage/'.$fileName;
			$attachments[$fileName] = $filePath;
			$oReportRun->writeReportToExcelFile($filePath);
		}

**Comment by proyectosit** [comment]
Thanks Martin! (Sorry for the delay on my response).
Regards,
GP
