### ISSUE TITLE
Limit zdjęć do produktów - jak go zwiększyć?

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2791]
Pytanie jak w temacie, aktualnie z tego co widzę jest to 10, a potrzebuje 12...

**Comment by amdziak** [comment]
Czy jest ktoś w stanie odpowiedzieć na to pytanie?

**Comment by bpabiszczak** [comment]
Jest to zaszyte w kodzie, programista musi poszukać... my będziemy wkrótce przebudowywać ten mechanizm i wówczas dodamy ten parametr do konfiguracji.
