### ISSUE TITLE
[bug] - Settings>Automation>Triggers do not work

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#2793]
choose "Every time a record is saved (eg. creating, modifying)", Сhoose condition (step 2), Add To Do "Upate fields" end "Add task for workflow: Update fields" end when substitution raw text -> task not saved :(((

**Comment by iRainSystem** [comment]
[
![error_automat](https://cloud.githubusercontent.com/assets/17310158/14040083/3888fcc4-f26c-11e5-8e1f-a396e55d6dde.gif)
](url)

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2805
