### ISSUE TITLE
Sprawdzanie salda

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2796]
Czy jest szansa wyłączyć gdzieś sprawdzanie salda kontrahenta ? Nie jest to dla mnie konieczne, a tylko przeszkadza.. :)

**Comment by bpabiszczak** [comment]
a próbowałeś wyłączyć pole? O ile dobrze pamiętam, kazałem uzależnić to od tego, czy pole jest włączone czy nie.
