### ISSUE TITLE
Warning: array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by michelmarques1** [YetiForceCompany/YetiForceCRM#2798]
Hello my friends, how are you?

I have the following problem. He started for no reason. When I clear the browser cache the system back to normal but when I do logout recurs.

Does anyone know how to solve?

![image](https://cloud.githubusercontent.com/assets/18095104/14063600/9ec498b0-f3af-11e5-8c7a-b786d052633c.png)

**Comment by bpabiszczak** [comment]
Try use PHP 5.6.
