### ISSUE TITLE
[bug] paymentscurrency field not working correctly

### ISSUE THREAD

**Issue by orsab** [YetiForceCompany/YetiForceCRM#2799]
Hey, the field 'paymentscurrency' do not work properly when the field is updated through web service in 'PaymentIn' module (Invalid reference specified for paymentscurrency),  and the request for field - is always empty. Thanks for the help

**Comment by paula-w** [comment]
You didn't give us enough info, and we're not able to trigger this error.
However - we don't support changes made via webservice. Ultimately this functionality will be entirely substituted by API.
