### ISSUE TITLE
Feature: PDF Template - improve usability

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#28]
1. Add functionality to be able to use standard PHP calculation functions, date/time and other.
2. Add options to attach records form related modules (1:m. m:1, 1:1 and m:m) in the form of blocks (simillar as PDF Maker for vtiger)
3. Write detailed manual

**Comment by bpabiszczak** [comment]
1. This possibility already exists; you just have to use special functions. I don’t see any reason to move it to the editor [too time consuming and there will be no benefits from it].
2. This possibility already exists; you just have to use special functions (alternatively use functions generating records from reports).
3. Creating such a manual would take weeks. Currently we have plans to develop a PDF module. In the meantime, we fill in a new website and the documentation will be there.
