### ISSUE TITLE
[Enhancement] - Module "Hide Blocks" working events

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#2800]
Module "Hide Blocks" is working on an event save the entry. It may work for other events?

**Comment by iRainSystem** [comment]
for example [https://www.vgsglobal.com/extensions/vtiger-dynamic-blocks/](url)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2624
