### ISSUE TITLE
Failed to install: Module does not contain default language

### ISSUE THREAD

**Issue by brunabites** [YetiForceCompany/YetiForceCRM#2801]
I'm trying to install a module created with Module Manager in Yetiforce (same version I have now), but I keep getting this message "Module does not contain default language (en_us)".

**Comment by paula-w** [comment]
Can you check if this problem exists in the developer version as well? 
And what version or YetiForce are you using?

**Comment by kpaulaha** [comment]
Had the same problem with module with Finnish language, worked when changed manually the Finnish language file to UTF8 in the exported module.

**Comment by manojsubudhi** [comment]
Failed
Module does not contain default language (en-US).

I also getting same issues here

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=%22Module+does+not+contain+default+language%22
