### ISSUE TITLE
Test CRM gitdeveloper Different Layout than  2.3.49 

### ISSUE THREAD

**Issue by stealsinc** [YetiForceCompany/YetiForceCRM#2803]
Hello, why does Test CRM gitdeveloper have a Different Layout than 2.3.49?
Where do I get the Test CRM gitdeveloper version?

![1](https://cloud.githubusercontent.com/assets/17715500/14135474/c29a3b38-f61a-11e5-87ed-91d4133f0a34.png)
![2](https://cloud.githubusercontent.com/assets/17715500/14135476/c425f1d6-f61a-11e5-868f-1abb9ad0407e.png)

**Comment by kpaulaha** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by stealsinc** [comment]
Thank you, is developer going to be the new future layout... More information please on developer.

**Comment by paula-w** [comment]
The new stable version is going to include this layout.

**Comment by stealsinc** [comment]
Thanks... When will the new stable version be available?

**Comment by paula-w** [comment]
You can check all current and future Milestones and their release dates in here: https://github.com/YetiForceCompany/YetiForceCRM/milestones

**Comment by stealsinc** [comment]
Excellent, thank you.
