### ISSUE TITLE
[bug] Field editor

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2804]
Not able to change status of some fields in invoices, e.g. po box in delivery address. 

![edit_field](https://cloud.githubusercontent.com/assets/10330264/14168177/6741e26c-f729-11e5-86c5-4e71e276701b.gif)

**Comment by kpaulaha** [comment]
Forget the above, just noticed the way it is shown in invoices, my mistake.

**Comment by paula-w** [comment]
The fields, whose values you can't change, are system fields and they're intentionally blocked.

**Comment by kpaulaha** [comment]
I know that, but I think po box is not one of those.

**Comment by rskrzypczak** [comment]
Thanks for your report, the problem has been solved here https://github.com/YetiForceCompany/YetiForceCRM/commit/91543385b2dafc1bdbb2ca12a05ef8974fc921b8    https://github.com/YetiForceCompany/YetiForceCRM/commit/841aebc93e689d961a35824ad7f0d54f7be57c74
