### ISSUE TITLE
[BUG] Total Time - Total Unit

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#2807]
Hi, what is the difference in "Total Time" and "Used Units". in my lab Total Unit never updated. The label Progress, It should automatically update?. Why the "End Date" never updated?

I did test in https://gitdeveloper.yetiforce.com/

Thanks!

![image](https://cloud.githubusercontent.com/assets/3030997/14177603/6bac1b48-f72d-11e5-9e5e-7e2daaa916bf.png)

**Comment by skramanzia** [comment]
Sorry, "Used Units" not Total Units.

**Comment by skramanzia** [comment]
Did Create ticket and closed. With 57 min Worked Time, Accepted.
![image](https://cloud.githubusercontent.com/assets/3030997/14496768/ae3557da-016a-11e6-9322-ea0215676d4d.png)

After Cron and Workflow was finished, Used Units and progress not update.
![image](https://cloud.githubusercontent.com/assets/3030997/14496814/e04fdd9e-016a-11e6-9597-fb35b5390f2e.png)

Total Time[he] was Updated but display 0.95 (0.95*60 = 57) may be have a issue with format.
![image](https://cloud.githubusercontent.com/assets/3030997/14496864/0dd7f832-016b-11e6-97d7-2762673ba8e3.png)

- "Used Unit" is subtract to "Total Units" and "Total Time" ?
- "Progress" depends of "Used Units" or "Due Date"?

"End Date" is not updated yet
![image](https://cloud.githubusercontent.com/assets/3030997/14496999/a30ab34a-016b-11e6-8b5e-ac9a738c1aa3.png)

I am available for any test

Thanks!

**Comment by paula-w** [comment]
Hi.
Processes [support process included] will be optimized in May. Documentation for processes should be released together with v3.1. The fields you mentioned will undergo some changes.
