### ISSUE TITLE
add event

### ISSUE THREAD

**Issue by rezaizadi** [YetiForceCompany/YetiForceCRM#2813]
when edit Calendar event and enter save button automatic make a  duplicate event.
and after set complete status but yet show remember notification every time at page.

![untitled](https://cloud.githubusercontent.com/assets/11961062/14227951/64b7893e-f91d-11e5-8b25-d6d74e0715e4.jpg)

**Comment by rezaizadi** [comment]
my version is 2.3.49

**Comment by rezaizadi** [comment]
add other record at "vtiger_activity_reminder_popup"  table after save edit.

**Comment by rezaizadi** [comment]
i change file (modules\Calendar\models\Module.php) this line:
SELECT reminderid, recordid FROM vtiger_activity_reminder_popup 
to
SELECT DISTINCT recordid FROM vtiger_activity_reminder_popup 

and ok.
please check.

**Comment by rezaizadi** [comment]
can i enter to your team ?

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
our team works here - on GitHub. If you would like to help us, it's the best place for cooperation and communication.

**Comment by mariuszkrzaczkowski** [comment]
The change has been introduced to the system. 
https://github.com/YetiForceCompany/YetiForceCRM/commit/456d27e335b29981a98e3e5a1cf16fd55cc2d5bc
If you wanna help us then upload the changes to GitHub and send us "pull requests", it will be much easier and quicker.
https://help.github.com/articles/using-pull-requests/
