### ISSUE TITLE
Whats Wrong With your Milestones?

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#2816]
Seriously guys what is going on ?
from 17 november you are trying to release the responsive version...
you have missed at least 5 milestones for this version...

and i see again that from 4 april you are moving to 8 april...
Be sure that 8 april will be cancelled for another date of course..

Be honest with your selfs and with your community...
Do you want to release it someday?or you will test  it forever?

**Comment by PercyP** [comment]
Your comments seem a little harsh given that this is an open source product. I am sure they have their reasons for delay and sure its just ironing out remaining bugs - maybe that testers are posting on here (if you look at the milestone posts).

Everyone is as keen as you are to see their new release, but cut them some slack and just accept that there may be delays - would you rather they released it on the day knowing there are bugs they know about, or wait some extra time whilst they correct and perfect it. I can imagine it must be very demotivating to see comments like this. I also imagine people will moan if they released it on the specified date with bugs. Whatever they do there will be those who complain.

I used to use Vtiger, and their releases were dreadfully slow. Yetiforce has taken Vtiger (in such a small space of time) and drastically improved it, their releases are far more frequent, and their support of their open source version is by far, so much better).

**Comment by eptapsyxos** [comment]
if your forecast is for 17 november and we have 4 april and still nothing is an issue..at least not commit or dont set so aggresive targets.
even its an opensource (at least for now) its a big missing of milestones.

as for the vtiger the community version has been abandoned long time ago so you can not compare a dead crm with an active one.

And when someone commited to deliver a service or a product on time at least must be honest with the clients-community why they are missed it.

In developers vtiger forum i see huge posts from yetiforce team members...but here silence..
Keeping changing the dates...

Hoping once again to achieve the 8 april milestone.

**Comment by bpabiszczak** [comment]
@eptapsyxos

Riddle me this:

- how many bugs have you fixed this year?
- how many functionalities have you written?
- how many lines of the code have you optimized?
- how much money have you spent on developing the system?


Then answer this question:
- Who cares more about releasing the next stable version? We or you?

The version change from 2.3 to 3.0 follows the version change policy described here: https://yetiforce.com/en/implementer/installation-updates/138-yetiforce-number-system.html

"X - represents the release of a new version of the software that contains innovative changes in comparison to the last version".

We will change the stable version release date as many times as we consider it necessary. It would be best if you set the date to 2020, then we will surely make it on time :]

Concentrate on how to help with the system's development. Complaining won't help you, us, or the community.

**Comment by playmono** [comment]
Totally agree with @bpabiszczak . I'm so impatient waiting for this version but I accept is very hard to develop an app like this.

**Comment by eptapsyxos** [comment]
15 april another delay for the release...another missed milestone.you ve just confirmed me.thank you very much.
