### ISSUE TITLE
When will be released the new stable versiom?

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#2818]
I have talked with someone from YetiForce Team and she tell me that the new version will be released today? it's true? someone can tell me if this will hapen today?

Thanks.

**Comment by bpabiszczak** [comment]
1. https://github.com/YetiForceCompany/YetiForceCRM/milestones
2. https://github.com/YetiForceCompany/YetiForceCRM/issues/2816
