### ISSUE TITLE
Workflow - nie można dodać nowego zadania

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2819]
Przy dodawaniu nowego zadania i kliknieciu zapisz okno zadań się zamyka, a nowego zadania nie ma...
Przy tej okazji chce dodać zadanie do modułu kalkulacje (pomnożenie dwóch wartości i przypisanie jej do pola trzeciego).
W loga mam coś takiego:
PHP Notice:  Undefined index: Workflows in /home/admin/web/yeti/public_html/include/runtime/LanguageHandler.php on line 154

Moja wersja to: 2.3.1467

**Comment by amdziak** [comment]
Widzę, że nie tylko ja mam taki problem ( #2805 ).
Kiedy można się spodziewać poprawki?

**Comment by bpabiszczak** [comment]
Duplikat: https://github.com/YetiForceCompany/YetiForceCRM/issues/2805
Pewnie jutro... optymistycznie myśląc.
