### ISSUE TITLE
Tworzenie szablonu PDF - brak modułu powiązanego

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2820]
Stworzyłem powiązanie między modułami Produkty i Zapytania ofertowe(powiązanie jest w obie strony).
Tworzę nowy szablon PDF dla Zapytań ofertowych i chcę, aby z pola z modułu Produkty została pobrana wartośc, jednak w polu Powiązane moduły nie ma modułu Produkty...
Wydaje mi się, że we wcześniejszych wersjach to działało...
Jest to bug, czy zamierzona funkcjonalność?
Jak można to szybko naprawić?

**Comment by bpabiszczak** [comment]
W jaki sposób zrobiłeś powiązanie?

**Comment by amdziak** [comment]
Moduły standardowe -> Moduły - powiązania -> Dodaj relację.
Kiedyś pisałeś mi który parametr trzeba zmienić w konfiguracji...

**Comment by bpabiszczak** [comment]
Nadal nie rozumiem.

Produkty są powiązane z zapytaniami ofertowymi ale w relacji niestandardowej [innej niż 1:M i M:M] do obsługi produktów jest napisany od nowa cały mechanizm inventory. A więc po co powiązałeś produkty skoro są one widoczne na dokumencie zapytania oferty w podglądzie i edycji? A po drugie o ile wiem, wydruki domyślnie nie obsługują tego typu relacji, trzeba sobie napisać prostą funkcje specjalną która to obsłuży.

**Comment by amdziak** [comment]
Produkty są oczywiście widoczne, ale nie to pole które potrzebuje (jest dostepna tabelka, a ja potrzebuje oprocz niej jeszcze co najmniej jedno pole).
Można poprosić o jakąś wskazówkę co i gdzie napisać? Ewentualnie na czym się wzorować?

**Comment by bpabiszczak** [comment]
Nie rozumiem nadal... proszę to zademonstrować na gitdeveloper, dokładnie opisać jakie pole, po co i dlaczego i załączyć zrzuty ekranu lub nagrać film. 

Marnujemy w ten sposób czas.

**Comment by amdziak** [comment]
<img width="1552" alt="zrzut ekranu 2016-04-04 o 22 23 50" src="https://cloud.githubusercontent.com/assets/11409255/14262069/f77dac8e-fab3-11e5-8941-0becda9371b4.png">
W rozwiniętej liście (Powiązane moduły) chciałbym dodać możliwość wyboru modułu Produkty i dalej w liście Pola z powiązanego modułu mieć możliwość wyboru wszystkich pól z modułu Produkty.

**Comment by bpabiszczak** [comment]
To tak nie działa, ponieważ ten typ relacji nie jest obsługiwany, cała tabelka z produktami jest generowana za pomocą funkcji specjalnej, jeżeli ktoś chce wygenerować sobie inaczej całą tabelkę, to powinien skopiować funkcje specjalną i ją zmodyfikować. 

Funkcja specjalna aktualnie używana jest dynamiczna, czyli dodając lub usuwają jakieś pole w obrębie produktów/usług powinna ona przy wydruku pokazać tylko aktualną strukturę kolumn/pól.

**Comment by amdziak** [comment]
A jak zrobić żeby działało tak jak chcę?
Nie interesuja mnie dane z tabelki produktowej, tylko dane z całego modułu.

**Comment by bpabiszczak** [comment]
Ale którego modułu? Jeżeli z zapytań ofertowych to wówczas są one dostępne tak jak widać na Twoim zrzucie ekranu w polu "Pola z modułu głównego", jeżeli jednak chciałbyś obsłużyć pola z modułu produktów który jest powiązany z modułem zapytań ofertowych, to wówczas trzeba dodać taki mechanizm do panelu, bo obecnie panel nie daje takiej możliwości.

**Comment by amdziak** [comment]
I tu jest pytanie:
Na czym można się wzorować (chociażby plik, czy tabela) aby to osiągnąć?

**Comment by bpabiszczak** [comment]
aby móc z poziomu panelu wybierać pola z bloku produktów? Tylko i wyłącznie rozbudowując panel, czyli musi to zrobić programista a najlepiej dobry programista, a dobry programista jak wejdzie w kod sam będzie wiedział jak to zrobić, bo przecież jest dobrym programistą :]

**Comment by amdziak** [comment]
Czyli żadnych wskazówek nie dostanę?
Na chwilę obecną nie chcę w to angażować programistów, gdyż sam muszę przetestować wszystkie funkcjonalności, a dopiero potem dam to programistom...

**Comment by bpabiszczak** [comment]
Ale jakie wskazówki chciałbyś otrzymać? Taka zmiana wymaga prac programistycznych, nie da się tego wyklikać ani nie da się tego opisać, bo zmiany w kodzie będą dotyczyć z setki linijek kodu. 

W 100% rozumiem, gdy osoba/firma nie chce lub nie ma środków aby zainwestować w dostosowanie danego mechanizmu, jednakże nie zwalajmy tego na chęć przetestowania... testuje się to co jest a nie to czego nie ma i się kombinuje aby to jakoś zastąpić.
