### ISSUE TITLE
[Improvement] Module Projects and Project Tasks - images gallery

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2822]
Hi,
I suggest: in the modules Projects, Project Tasks add the ability to add images to project and task. Currently, you can add files in the Documents module, but it is not optimal to adding photos in my opinion. 

My proposition:
- images gallery - as an additional tab in the project and tasks of the project
- Quick and easy to create photo-documentation project / task
- *a hyperlink on a page to add images that cause the camera option on your smartphone android/iphone/windows (photo taken smartphone is automatically loaded to the gallery).
- Thumbnail preview in the photo gallery and ability to view / preview large / fullsize image in the browser,
- Ability to add multiple images under a single title (as opposed to a document where you have to load each file separately)
- (extra: - Saving GPS location tag photos and display values with the possibility of preview on google maps.)

Application, e.g.: all kinds of projects in the construction industry, where is the need for photo documentation of the investment process.

*When adding a document option "Choose file" on the android 4.4.4/chrome camera starts but after taking a picture refreshes the page and save NOT the file.

**Comment by Remi007** [comment]
Przykładowe rozwiązanie:
1. Osobny moduł do dodawania zdjęć "Skjema/Bilde - Sende inn bilde" (dzięki osobnemu modułowi jest możliwość ograniczenia dostępu do danych projektu i zdjęć dodawanych przez innych użytkowników)
2. Moduł do podglądu miniatur, przeglądania dużych obrazów, usuwania wgranych zdjęć z opcją wyświetlania z filtrem wg projektu.
3. Z poziomu projektu podobnie można wyświetlać miniatury i duże zdjęcia przypisane do projektu oraz wyświetlić na mapie (google maps) lokalizację w której wykonano zdjęcia.
Poniżej gif:
![photogallery project](https://cloud.githubusercontent.com/assets/17315868/14581175/cecf8d9e-03e5-11e6-8bfc-cf5a5009f333.gif)

**Comment by bpabiszczak** [comment]
Nie planujemy dodanie takiej funkcjonalności w najbliższym czasie.
