### ISSUE TITLE
[Improvement] Module Projects - deleting projects

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2823]
Currently, **projects** can be **removed with two clicks**. I think** it's dangerous** for the company for an employee to "1-click selects" delete the data, eg. Several weeks or several months of implementation of the hit project. Currently, there are not deleted tasks and milestone, but I do not know what is the plan to redesign the future.

My suggestion is to remove the projects require read the the information about the effects and to require confirmation. In addition, it should not be the possibility of permanent removal of the project, along with the tasks and milestones. I would recommend the creation of a **trash / archive**.

**Comment by vovpff** [comment]
you can add user rights only for project manager to remove project.

**Comment by florek41** [comment]
Or you can prohibit deleting for everyone so the only way will be set "Archived" status.

**Comment by kpaulaha** [comment]
If you delete a project it will be moved to the Recycle Bin, from where it can be restored. But when you delete a project, the milestones and tasks will remain. Could maybe be convenient to have a possibility to delete those at the same time also.

**Comment by paula-w** [comment]
There's a trash bin in the system, but it's not enabled by default in menu. It can be added from the panel. And just like @vovpff  said, you can take away users' permissions for deleting.
