### ISSUE TITLE
[PL][BUG] Brak obliczania bieżącej wartości podatku i rabatu

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2826]
W momencie kiedy ustawimy podatki i rabaty na indywidualne i podamy ich wartośćti to nie są one uaktualniane na bieżąco po zmianie ilości/ceny produktu.
Tutaj akutar moduł faktur proforma, ale w każdym module z blokiem produktowym jest tak samo.

![rabaty_podatki](https://cloud.githubusercontent.com/assets/4824588/14341096/a2a35920-fc8e-11e5-8502-19f3253b8b84.gif)

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/ecc09e3d51558526f315f2bf754ce9bcf203ff7b
