### ISSUE TITLE
[PL][BUG] Limit kredytowy - błąd podczas włączania/wyłączania

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2827]
Po dodaniu imitu kredytowego checkbox na liście jest odznaczony jednak opcja jest aktywna (sprawdzając podczas edycji wpisu).
Wygląda na to, że checkbox na liście ma wartość odwrotną niż checkbox podczas edycji.

![limit_kredyt-onoff](https://cloud.githubusercontent.com/assets/4824588/14341263/7b3e7f0c-fc90-11e5-9778-fb2d1797a497.gif)

**Comment by TomaszQr** [comment]
Fix https://github.com/YetiForceCompany/YetiForceCRM/commit/dc73a384d602428620ca1af6d44f40f01677e225
