### ISSUE TITLE
[PL] Powiadomienia - wysyłanie powiadomienia do samego siebie

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2829]
Aktualnie mamy powiadomienia (! :open_mouth: ), które możemy wysyłać do innych.
Uważam, że dobrym pomysłem byłaby możliwość wysłania powiadomienia również do samego siebie :) Zauważyłem, że sporo osób ma nawyk wysyłania informacji do siebie (czy to sms, czy mail) jako forma "TODO" czy przypomnienia.

**Comment by bpabiszczak** [comment]
Hehe, kazałem usunąć wczoraj to ograniczenie :D

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/33d2b92f1174d16bcb2788e7781dda2dd331bf36
