### ISSUE TITLE
[PL][TŁUMACZENIE] Konfiguracja powiadomień - osoby WSPÓŁDZIELĄCE

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2830]
W konfiguracji powiadomień możemy zarządzać osobami obserwującymi moduły a w nagłówku mamy "osoby WSPÓŁDZIELĄCE". Dla mnie jest to bardzo mylące, myślę, że powinno być "osoby OBSERWUJĄCE".

**Comment by bpabiszczak** [comment]
Do obserwowania służy "oko"... a to pole służy do współdzielenia.

**Comment by florek41** [comment]
@bpabiszczak dokładnie tak, dlatego to o czym mówię uznałem jako błąd, poniżej screen:

![yf_osoby_wspoldzielajace](https://cloud.githubusercontent.com/assets/4824588/14365870/385159d2-fd10-11e5-9da0-774f16f770ba.JPG)

Po dodaniu do tej listy "oko" w danym module jest zaznaczone.

**Comment by bpabiszczak** [comment]
aaa no to do poprawki :D
