### ISSUE TITLE
[PL] Aktualizacja rekordu powiązanego - nie wszystkie powiązania są obsługiwane ?

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#2832]
Mam pytanie odnośnie aktualizacji rekordów powiązanych za pomocą workflow.
Obecnie nie mogę ustalić takiego zadania dla np. pola w zadaniach projektowych "Powiązane zadanie":

![yf_powiazanie](https://cloud.githubusercontent.com/assets/4824588/14348786/05f6b42e-fcbf-11e5-97fc-38dcde43fef1.PNG)

Na jakiej zasadzie działa ten workflow, jakie powiązania można aktualizować?
Może jest szansa aby zmodyfikować to w ten sposób była możliwa aktualizacja każdego z rekordów ?

**Comment by bpabiszczak** [comment]
Ale gdzie nie możesz użyć tego w workflow? W warunkach? właśnie testowałem i mi działa na wersji gitdeveloper. Nie będę się rozpisywał na pytania na jakiej zasadzie działa workflow bo można książkę o tym pisać. 

Na chwilę obecną nie mamy w planach dodawania funkcjonalności do workflow [ostatnio dodaliśmy automatyczne generowanie rekordu z rekordu]. Jak jakiś klient będzie miał taką potrzebę lub gdy ktoś ze społeczności doda taką funkcjonalność to wrzucimy ją do YF.
