### ISSUE TITLE
[question] Calendar

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2834]
Several issues on the calendar:
1. How do I display information about the projects \ Project Milestones  in the calendar?
2. In the calendar settings presentedin nasyki color for each omdulya, what does it do? or it is broken functionality?

**Comment by KatarzynaUlichnowska** [comment]
Hello,
1. Projects cannot be displayed in the Calendar - there is a Gantt chart.
2. The color of modules can be changed in Settings and if you do it, the links to these modules will also have the same color as well as many other small elements in the system. It has nothing in common with the Calendar.
