### ISSUE TITLE
OSSMail

### ISSUE THREAD

**Issue by rezaizadi** [YetiForceCompany/YetiForceCRM#2838]
Hi , my ver 2.3.49
I send more email for one contact but not added history.
![email](https://cloud.githubusercontent.com/assets/11961062/14404619/92941408-fe90-11e5-9250-f846342d6a0c.jpg)

**Comment by bpabiszczak** [comment]
Now we have YetiForce 3.0
Please read this: https://yetiforce.com/en/administrator-documentation/panel/mailbox/mail-scanner/135-mail-scanner.html

> The scheduler [cron]
> Cron must be configured properly in order for the scanner to work. To verify cron configuration, proceed to the page tab available in the panel.
