### ISSUE TITLE
[bug] PriceBook

### ISSUE THREAD

**Issue by rezaizadi** [YetiForceCompany/YetiForceCRM#2839]
Hi my ver 2.3.49
After select product item at invoice or Quotes not show price book list at popup.

**Comment by rezaizadi** [comment]
i have this problem at ver 2.3.49:
https://cloud.githubusercontent.com/assets/11919990/11676869/ea4ec8ea-9dfc-11e5-9811-d38e2930c335.png

**Comment by rezaizadi** [comment]
I Fixed this problem
at this file: \modules\PriceBooks\models\Record.php
change function name getProductUnitPriceURL to getProductListPriceURL

**Comment by paula-w** [comment]
Can you please test it on the developer version and let us know if the error occurs there as well?

**Comment by rezaizadi** [comment]
i install developer  version and test, but have this problem at developer version too.

**Comment by rskrzypczak** [comment]
Version 3.0 includes new Invoice and Quotes modules. Please check if the error occurs also on that version. In case you think it does -  provide me with more details (screenshots are welcome).

**Comment by rskrzypczak** [comment]
The issue has not been updated for a long time, I don't see this error in 3.0, so I'm closing.

**Comment by mykljohn** [comment]
I have this error in 3.0 as well.
