### ISSUE TITLE
Invoke Custom Function not Working

### ISSUE THREAD

**Issue by anjaan123** [YetiForceCompany/YetiForceCRM#2841]
Not able to register the php file with entitymanager. 
php file containing the below does not work.
require_once 'include/utils/utils.php';
require 'modules/com_vtiger_workflow/VTEntityMethodManager.inc';
$emm = new VTEntityMethodManager($adb); 
//$emm->addEntityMethod("Module Name","Label", "Path to file" , "Method Name" );
$emm->addEntityMethod("Quotes", "Update Currency", "Include/InventoryHandler.php", "updatecurrency");
Couldn't able to connect utils.php

**Comment by mariuszkrzaczkowski** [comment]
Try this:

include_once 'include/main/WebUI.php';
require 'modules/com_vtiger_workflow/VTEntityMethodManager.inc';
$emm = new VTEntityMethodManager(PearDatabase::getInstance()); 
$emm->addEntityMethod('Quotes', 'Update Currency', 'Include/InventoryHandler.php', 'updatecurrency');

**Comment by WalterLuis** [comment]
I just tested and runs smoothly
Thx
