### ISSUE TITLE
2.3.49 install false

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#2842]
I use centos 6.5,I install 2.0 success.but 2.3.49 false/

**Comment by bpabiszczak** [comment]
Please install YetiForce 3.0 and read this: 

1. https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
2. https://yetiforce.com/en/implementer/installation-updates/101-crm-installation.html 
3. https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html
4. https://yetiforce.com/en/developer-documentation/bugs/126-issues.html

**Comment by 1250572980** [comment]
3.0 work well.
