### ISSUE TITLE
Help with installing YetiForce on Bitnamui Stack

### ISSUE THREAD

**Issue by ayoogh** [YetiForceCompany/YetiForceCRM#2843]
Hello

 I was very impressed with you product demo and wanted to congratulate you on developing such a complete, comprehensive, thorough and what looks like a easy to use CRM system.

 So I downloaded the program to use on my Windows 7 computer. However there seems to be a problem with Win7 ( a common one judging by the search results) in it not working at localhost - tried WAMP and XAMMP with no success.

 So I finally installed the Bitnami WAMP Stack which works with the applications stacks that they have developed but unfortunately not yours as yet. (Version 5.6.20 ....bitnami-wampstack-5.6.20-0-windows-installer.exe)

 In their documentation (https://wiki.bitnami.com/Applications/BitNami_Custom_PHP_application) it explains how to install a custom application using a Native Installer but I am confused as to what to include in the folders they ask you to create with regards to YetiForce:

This is the basic directory structure:
apps/myapp
 |- htdocs
 |- conf
 |- data (optional)

apps/myapp/htdocs: This folder should contain your PHP application's files.

 I have created those but not sure which files need to be moved where and that is the reason why I am contacting you for your help so as to get right the first time.

Presumably these files and folders go into the created htdocs folder:
 admin; api; backup; cache; cron; include; install; languages; layouts; libraries; modules - .gitattributes; .gitignore; .htaccess; api.php; index.php; README.md.

 And the config folder goes the created conf folder. And licenses folder stay at the root folder.

 It then describes what do to do with apps/myapp/conf/httpd-prefix.conf; apps/myapp/conf/httpd-app.conf which I presume need to be created. Plus what do do about htaccess and The Apache configuration file.

 Once done to access the installer you would type in http://localhost/yetiforce/ install/install.php?

 i know that you have details on your web site for the installation procedure but it does not cover Bitnami WAMP Stacks so I would really appreciate your advice and recommendations.

Thanking you in advance for your help and assistance.

**Comment by stealsinc** [comment]
Hello ayoogh, don't bother, it does not work, I tried everything... It only works on Linux. Here are all the links that you need. I installed it on vmware but it is a trial version. I had problems with virtualbox but it is free, and you might not have any problems like I did... Good Luck!
https://www.apachefriends.org/download.html
http://www.wikihow.com/Install-XAMPP-on-Linux
http://www.ubuntu.com/download/desktop
https://www.virtualbox.org/
https://my.vmware.com/en/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/12_0

**Comment by SkavenKF** [comment]
Hi, i use Vtiger and Yetiforce on W7, W8.1 and W10 computers with XAMPP Version 5.6.xx.
Do know the following tutorial?
https://wiki.vtiger.com/index.php/Vtiger_CRM_6_Installation

**Comment by ayoogh** [comment]
Thanks stealsinc - have uninstalled all Bitnami stacks and replaced it with XAMMP. Too complicated.

SkavenKF - thanks yes I followed the instructions and have installed  YetiForceCRM 2.3.49 and vtigercrm6.4.0 on xampp-win32-5.6.19-0-VC11 but for some reason at the end of the installation they both hang on a blank Installation Wizard page and don't take me to the CRMS. Using Firefox 45.0.2.

With vtiger, I am able to log in but accessing any modules a page comes up saying Illegal request - Go back. and it takes me back to the login page. When I try logging in again this comes up:

{"success":false,"error":{"code":"Illegal request","message":"Illegal request"}}

With YetiForce, (http://127.0.0.1/YetiForceCRM%202.3.49/) takes me to the login page and when I login it goes to http://127.0.0.1/YetiForceCRM%202.3.49/index.php?module=Users&action=Login and a blank page.

With Opera browser(http://127.0.0.1/YetiForceCRM%202.3.49/index.php?module=Users&action=Login)  or localhost says:

The 127.0.0.1 page isn’t working
127.0.0.1 is currently unable to handle this request.

I am completely puzzled and have no idea why this is happening. My host file is OK ( only 127.0.0.1       localhost) and added localhost as an ignored address in Avast Redirect settings. No other program is using port 80. If it's of any help here is the Apacjhe error log:

> 
[Fri Apr 15 15:07:31.618420 2016] [:error] [pid 5084:tid 1676] [client 127.0.0.1:2946] #0 D:\\xampp\\htdocs\\vtigercrm6.4.0\\vtigercrm\\includes\\http\\Request.php(193): Vtiger_Request->validateReferer()\n#1 D:\\xampp\\htdocs\\vtigercrm6.4.0\\vtigercrm\\modules\\Vtiger\\views\\Index.php(98): Vtiger_Request->validateReadAccess()\n#2 D:\\xampp\\htdocs\\vtigercrm6.4.0\\vtigercrm\\includes\\main\\WebUI.php(171): Vtiger_Index_View->validateRequest(Object(Vtiger_Request))\n#3 D:\\xampp\\htdocs\\vtigercrm6.4.0\\vtigercrm\\index.php(18): Vtiger_WebUI->process(Object(Vtiger_Request))\n#4 {main}, referer: http://127.0.0.1

Nothing is shown for YetiForce.
> 

Just to test that the server is working OK, i installed SugarCRM without any problems.

**Comment by ayoogh** [comment]
Sorry - inadvertently closed the thread.

**Comment by stealsinc** [comment]
You're welcome Ayoogh... Make life easy... Yeti works with xampp for Linux on a Linux machine.

**Comment by paula-w** [comment]
YetiForce works in every web environment that's properly configured according to the requirements listed on our website. It doesn't matter what operating system or what application [WAMP, XAMPP, MAMP]  we use.  This environment must be well configured by someone who knows what they're doing. 

You can also try downloading the latest version from the developer branch.

**Comment by stealsinc** [comment]
Paula, how much would it cost to have an expert try to install Yeti on my Win 7 64 bit machine with xampp?

**Comment by SkavenKF** [comment]
Can you check the following parameters in your php.ini  (i used this not only for YF):

allow_call_time_pass_reference=Off
safe_mode=Off
max_execution_time=600
max_input_time=5000
max_input_vars = 5000
memory_limit=512M
error_reporting=E_WARNING & E_ERROR & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
display_errors=On
register_globals=Off
post_max_size=50M
magic_quotes_gpc=Off
upload_max_filesize=20M

extension=php_bz2.dll
extension=php_curl.dll
extension=php_mbstring.dll
extension=php_exif.dll
extension=php_gd2.dll
extension=php_gettext.dll
extension=php_imap.dll
extension=php_ldap.dll
extension=php_mbstring.dll
extension=php_mysql.dll
extension=php_mysqli.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_pdo_sqlite.dll
extension=php_soap.dll
extension=php_sockets.dll
extension=php_sqlite3.dll
extension=php_xmlrpc.dll
extension=php_xsl.dll

**Comment by paula-w** [comment]
@stealsinc  - There are 2 options, depending on your server configuration. If it's already configured according to our requirements, and our only job is to install YetiForce, then it's 29,99€. If we first have to configure your server and then install YF, then the price goes up to 209,99€.

**Comment by ayoogh** [comment]
Hi SkavenKF - many thanks for your help.

Yes to the majority of your settings. Changes made:
max_input_time=5000  -- was max_input_time=60 --- changed to 5000
upload_max_filesize=20M ---- set to upload_max_filesize=50M
extension=php_mysql.dll -- was ;;extension=php_mysql.dll - removed ;;
extension=php_openssl.dll  -- was ;extension=php_openssl.dll - removed ;
extension=php_soap.dll --- was ;extension=php_soap.dll - removed ;
 extension=php_sockets.dll--- was ;extension=php_sockets.dll - removed ;
 extension=php_sqlite3.dll --- was ;extension=php_sqlite3.dll - removed ;
 extension=php_xmlrpc.dll --- was ;extension=php_xmlrpc.dll - removed ;
 extension=php_xsl.dll ---- ;extension=php_xsl.dll - removed ;
 
I am concentrating on the vtiger installation which once solved will no doubt apply to YF.. Reinstalled vtiger and when completed it came up with this error - no idea what it means:
result is not an object
Go back

And this one when going to http://localhost/vtigercrm/index.php?module=Users&action=Login:
Sorry! Attempt to access restricted file.

On forums.vtiger.com it seems that this may be caused by the vtiger  config.inc.php root_directory value. Mine says:

$root_directory = 'D:\xampp\htdocs\vtigercrm/';

Is yours similar? In the XAMMP httpd.conf file it uses forward slahes and reads for instance:
Directory "D:/xampp/php" .

Should it be: $root_directory = 'D:/xampp/htdocs/vtigercrm/'; ?

Or maybe this could be causing the problem in the mysql  config.inc.php:

$cfg['Servers'][$i]['extension'] = 'mysqli'; - should it be 'mysql'?

Apart from that I am stuck as what to do next.

@paula-w - yes I have double checked all the  requirements listed on your website.and everything is compliant according to php info and php.ini. and  properly configured. If it was not then I presume that the install would not work at all. It passes all the configuration checks when installing.

And it is not appropriate for you to close the discussion when you have not even attempted to offer any solution to the problem, Downloaded and installed "the latest version from the developer branch - YetiForceCRM-developer" and  the problem still persists and yes believe you me,  I do know what I am doing.

After login in http://localhost/YetiForceCRM-developer/index.php?module=Users&action=Login - results in a blank page.

Any suggestions?

Cheers.

**Comment by SkavenKF** [comment]
**@ayoogh**: Ok, I would install WAMP 5.6.20 with YF3.0 on my W10 and give you information about the configuration ;-)

**Comment by SkavenKF** [comment]
Hmm, i doing the following steps:
1. install WAMP 5.6.20 on windows 10 in d:\server\wamp (the firewall settings for Apache generate it automatically) i set the port for db to 3309 (i used the standard port for a other db ;-)
2. i extract the yf version 3.0.0 into htdoc/yf3
3. i go to url "localhost/yf3 in Firefox" and do the following steps (see pic 1-6)
3.a i changed ONLY the php.ini parameters wich are listed (pic1)
3.b i restart the apache server and checked the parameter again (pic2)
3.c i filled the settings (pic3)
3.d i checked the parameters and install (pic4)
3.e the only problem thát i have is the following (endless) screen (pic5). I checked after 30minutes the db for the tables. i found all tables, so i go to url  localhost/yf3
3.f i see the logon page and log on with admin user (pic6)

... so i have no problem with the installation and logon (ok 3.e is not optimal ;-)

Please can you do the same steps ...

**Comment by ayoogh** [comment]
SkavenKF - thanks again.

Sorry about the delay in responding - have had a series of problems with my win7 which drove me crazy - all now seems to be running OK.

Gave up on WAMP - could be problem with my pc but it would not start any of the services and back to XAMMP  and when you say "2. i extract the yf version 3.0.0 into htdoc/yf3" that would be an XAMMP folder not WAMP as  their project folder is www.

YF3 installed in D:\xampp\htdocs\yf3\ with the usual "following (endless) screen (pic5)" - at least is is installed - however I have a new problem.  It does not happen when using Opera or Vivaldi browser ( Opera like browser).

Using Firefox 45.02  and after I log in it displays this error message:

> Error!!!
> CSRF protection: Hacking attempt detected
> Go back Home Page

I go back and I am logged in into the CRM but when I click on any of the links to the modules, Firefox again displays the error - which means that I can't even log out of the program. And sends the computer crashing. Very odd.

if anyone has a similar problem the solution is o the found here:
http://cafe.elharo.com/privacy/privacy-tip-3-block-referer-headers-in-firefox/

Setting referers to "0" in about:config seems to have solved and fixed the problem.

May I thank you for all your help and assistance - much appreciated. Looking forward to exploring all the aspects of the YF with much anticipation.

Cheers, ayoogh.
