### ISSUE TITLE
Ticket and Used Units

### ISSUE THREAD

**Issue by vsappel** [YetiForceCompany/YetiForceCRM#2844]
Please help-me,
Im trying for days to do a relationship between time spent in a ticket and Used Units (hours) in a contract.

How i can make this control? I wanna insert time spent on a ticket and this time need be updated in Used Units. There is a way?

**Comment by paula-w** [comment]
It must be coded by a programmer, because right now it's not coded.

**Comment by vsappel** [comment]
Thank you, im afraid i don't have enough skill for that, all i can do is give a susgestion. It will be fine if we have a field on tickets (and in others modules) where we can manually add the spent units. Will be easier to manipulate than if related with worktime.

**Comment by paula-w** [comment]
You're welcome, and thanks for the suggestion.
We are planning to add it in 3.1. (Estimated release dates can be found [here](https://github.com/YetiForceCompany/YetiForceCRM/milestones))
