### ISSUE TITLE
[PL] [logic] Project Milestones, Project Task, Project 

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2849]
Hej, 

dot. wersji develop./ [ver. 2.3.1733]

Wg mnie można poprawić logikę w module Projects / Project Milestone.
_In my opinion could be improved logic in Projects / Project Milestone._

teraz jest / _now is:_
[Project Y] _created_ [Project Task 1] _result_: [Project Task 1] _auto-related to_ [Project Y]
[Project Task 1] _created_ [Project Milestone A] _result_: [Project Milestone A] _**not** auto-related to_ [Project Y]

oczekiwany / _expected result:_
[Project Y] _created_ [Project Task 1] _result_: [Project Task 1] _auto-related to_ [Project Y]
[Project Task 1] _created_ [Project Milestone A] _result_: [Project Milestone A] _**auto-related to**_ [Project Y]

Dodając Project Milestones z poziomu Project Task (będącego w relacji z Project), wydaję się właściwe automatyczne przypisanie relacji Project Milestones do Project. Tak jak ma to miejsce przy dodawaniu Project Task - auto przypisanie do Project.

1. Tworzę Project - nazwijmy go "Project Y"
2. Z poziomu "Project Y" wybieram zakładkę Project Task i tworzę na szybko Project Task: "Task 1" 
3. "Task 1" jest przypisany auto do "Project Y", a że nie utworzyłem Project Milestones wcześniej ...
...4 . otwieram full form w "Task 1" by dodać + Project Milestones
5. Otwiera się okno  Quick Create Project Milestone i tu tworzę "Project Milestones A"
W polu *Project brak jest auto przypisania do "Project Y".

PS> do tej pory zgłoszenia pisałem po ang. ze względu na wielonarodową  społeczność, ale gdzieś w odp. na zgłoszenie Błażej pisał, że szybsza reakcja jest jednak na zgłoszenia po naszemu :)

**Comment by bpabiszczak** [comment]
Ale społeczności nie pomaga tylko w 99% zadaje pytania, to my odpowiadamy i rozwiązujemy problemy, a więc pisanie po polsku przyspiesza...

**Comment by Remi007** [comment]
dobre pytania nie są złe ;) ...tzn. też mogą pomóc. 
A'propos pomagania i pytań...powoli zbieram się do opracowania nowej wersji językowej. Dosłownie powoli. Gdybym chciał się podzielić nową wersją .... to jak to najlepiej zrobić? Po prostu <> Code / upload files ?

**Comment by bpabiszczak** [comment]
Jaką wersją językową? Polską?

**Comment by Remi007** [comment]
norweską

**Comment by Remi007** [comment]
wracając do tematu.... ten sam problem występuję przy dodawaniu czasu pracy np dla Zadania przypisanego do Projektu. Ponownie w formularzu czasu pracy muszę odszukać i wskazać Projekt.

**Comment by waran70** [comment]
> Ale społecznoś nie pomaga tylko w 99% zadaje pytania, to my odpowiadamy i rozwiązujemy 
> problemy, a więc pisanie po polsku przyspiesza...

Blazej, without community "testing and questioning",  YF development will run in snail mode. 
Without community you will never know what user need (your customers are the community too)
So, I will suggest again, don't mix languages here. Separate git for Polish speaking people or ban other languages than English (I think this is totally clear for those who understand such projects).

Alternatively, if you don't think seriously about international success - do what you want to do.

**Comment by paula-w** [comment]
Hi.

Here's @bpabiszczak's answer:

“I don't see any difference between separating community and labeling the issues as PL/EN. We prefer to communicate in Polish, but everyone who writes in English will also get all the support they need. If you don't like Polish on GitHub then don't open the issues labeled as PL.

- We provide support in both PL and EN. 
- Don't tell us in what language we should speak to our community, we decide about it on out own.
- Please, don't lecture us. If you want to have a bigger impact on what's going on in YetiForce and its community, then focus on YetiForce's development. There's several people who give us pearls of wisdom every week.”
