### ISSUE TITLE
Yetiportal module Products

### ISSUE THREAD

**Issue by PW0131** [YetiForceCompany/YetiForceCRM#2851]
Why is not the list of products in the portal?
What all possibilities in this module in the portal?
Is it possible to create an application with a list of products?
 How? 
  Thank you!

**Comment by mariuszkrzaczkowski** [comment]
Do you have added the product on a Accounts?
![crm](https://cloud.githubusercontent.com/assets/10198654/14914962/2fa08622-0e0f-11e6-8d98-83f4a3eb0d2d.png)
![portal](https://cloud.githubusercontent.com/assets/10198654/14914965/3284f36e-0e0f-11e6-83a1-369651717a23.png)
