### ISSUE TITLE
Модуль "база товаров". 

### ISSUE THREAD

**Issue by PW0131** [YetiForceCompany/YetiForceCRM#2852]
Подскажите пожалуйста, где верстка этой таблицы? Модуль "база товаров". 
Необходимо вставить ещё 1 input type для поиска по коду в таблицу, а исходник таблицы найти не могу. Спасибо.

**Comment by bpabiszczak** [comment]
English please.

**Comment by eptapsyxos** [comment]
Thats the felling when we read polish posts..

**Comment by waw555** [comment]
Please tell me, where table mysql module for product.
It Insert More Search 1 input type code in the table of the route Thank you.

**Comment by vovpff** [comment]
Let's add additional text field by field editor to products module. After that made filter for "Product" module with needed columns.

**Comment by PW0131** [comment]
**vovpff** thank you! )
