### ISSUE TITLE
Instalacja aktualnej wersji developerskiej kończy się błędem 500

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2854]
Wszystkie biblioteki są skonfigurowane zgodnie z Instrukcją (instalator wszystkie ma zaznaczone na Tak) + chmody na foldery po 775 (session ma 777).
Próbowałem instalacji 3-krotnie i za każdym razem kończyła się niepowodzeniem.

Pliki z logami nie stworzyły się...

**Comment by bpabiszczak** [comment]
Aby pliki się tworzyły trzeba włączyć debugowanie [info w na naszej stronie].
Błąd 500 to błąd serwera a nie aplikacji, to oznacza, że to serwer zdecydował o tym że przerwał działanie, a więc to w logach serwera [np. apache] należy sprawdzić dlaczego tak serwer zdecydował. Może błąd generować aplikacja, ale to serwer decyduje kiedy coś jest błędem a kiedy nie i to w nim znajduje się odpowiedź.

**Comment by amdziak** [comment]
Jedyny niepusty plik w folderze log to system.log (co ciekawe, nawet po wywaleniu się skryptu dalej rośnie...).
W logach Apache'a nie ma nic - gdyby coś było sam bym sobie z tym poradził.
Wydłużyłem max_execution_time'a do 6000, ale w dalszym ciągu dostaje 500.
500 Nie zawsze jest błędem serwera :)

Jakie są prawidłowe chmody?
W instrukcji na stronie znalazłem tylko zdawkową informację, że katalogi mają mieć 775, a pliki bodajże 664...

**Comment by bpabiszczak** [comment]
500 to błąd Apache... i nie ma znaczenia czy masz logi czy nie, czy to wina YF czy nie, to o tym co się stało wiadomo w logach Apache i jeżeli ich nie ma to należy je włączyć. Proszę sobie poczytać w internecie, możemy pomóc ale tylko odpłatnie bo to wymaga administratora. 

http://stackoverflow.com/questions/4731364/internal-error-500-apache-but-nothing-in-the-logs
