### ISSUE TITLE
[Bug] - qoute

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2856]
![animation 3](https://cloud.githubusercontent.com/assets/11491482/14579415/a308d77a-03a8-11e6-99d7-c582ce123c71.gif)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/bdfc611eab7c83d3ae8633c4d1c62ec1e9da1237
