### ISSUE TITLE
Quote - PDF, sending via email

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2857]
dear,
What of the condition/statuses/parameters have to be fulfill to be able to see active buttons of generating quote to PDF and sending it via email?

Wasn't able to do it in current dev version - 2.3.1771

**Comment by mariuszkrzaczkowski** [comment]
![pdf1](https://cloud.githubusercontent.com/assets/10198654/14915927/b075ed3a-0e16-11e6-8f35-a95d4f4b4345.png)
![pdf2](https://cloud.githubusercontent.com/assets/10198654/14915929/b2f86290-0e16-11e6-891e-2bf50ee7810c.png)
![pdf3](https://cloud.githubusercontent.com/assets/10198654/14915930/b60dfde6-0e16-11e6-8652-b21891e2edfb.png)

**Comment by witer30** [comment]
thanks
