### ISSUE TITLE
Simplify sales process

### ISSUE THREAD

**Issue by elmarbransch** [YetiForceCompany/YetiForceCRM#2859]
Hello,

currently it looks like, that I am forced into a lengthy sales process, that would be a serious blocker for our company.
https://yetiforce.com/en/user-documentation/sales-process.html

Unfortunately the system doesn't seem to allow me to skip certain steps in the process
* A quote has "Opportunity" (SSalesProcess)  and "Calculation" (SCalulations) as required relations, then
* a calculation has "Opportunity" (SSalesProcess)  and "Sales Requirement" (SRequirementCards) as required relations, then
* a sales requirement has a required relation to "Quote Analysis" (SQuoteEnquiries), then
* a quote analysis is related to the "Opportunity" (SSalesProcess) again, then
* all of them - of course - require a company / client record (Accounts)

So, in order to create a new quote for new customer it requires to add at least 5 complete forms/entities. That sounds really complex to me and far more complex than required.

I tried to remove the "required" status from the fields in the Module Editor, but that did not work as expected.

I would be great to hear if there are any plans to optimize this.

thanks
-Elmar

**Comment by witer30** [comment]
these fileds you can easilty change mean mendatory of these fileds
![image](https://cloud.githubusercontent.com/assets/11491482/14580220/162c0f38-03c7-11e6-934a-75a987f8e4e6.png)

here is link
https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=SQuotes

only you should choose the module for each you would like to change these parameters

**Comment by elmarbransch** [comment]
Hi writer30,
thanks for the quick reply. As written in my text, that's one thing a I already tried and run into trouble somewhere else ;-) But I didn't recorded so the problem, so I am unable to replicate it here.
If this is a way to go I should try this again and test.
Thaks
-Elmar
