### ISSUE TITLE
[PL] [Improvement UX] Project / Project Task

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2860]
Hej,

Ciekawe (wg mnie) rozwiązanie do prezentacji postępu realizacji zadań przydzielonych do projektu  zastosowano w zurmoCRM (http://zurmo.org/). Zadania wyświetlane są w kolumnach. W każdej kolumnie znajdują się zadania o innym statusie, np. Planowane, W realizacji, Zakończone. Dla wzrokowców bardzo dobre rozwiązanie. Dodatkowo status zadania / przeniesienie do innej kolumny można realizować metodą Drag&Drop. Poniżej printscreen.
![zurmo_ux_projects](https://cloud.githubusercontent.com/assets/17315868/14580786/b5af7d6c-03d9-11e6-80bd-b0acd1cbc7ff.png)

**Comment by bpabiszczak** [comment]
I w czym to jest lepsze od tego co mamy?

**Comment by Remi007** [comment]
Wg mnie rozwiązanie zurmo jest obok wykresu Gantt-a czytelną formą prezentacji danych, choć nie pozbawioną wad. 
Aktualnie w YF mamy wykres Gantt i filtry. Z poziomu Realizacja / Zadań Projektów można ustawić niemal dowolne filtry by wyświetlić określone rekordy. - i to jest OK...choć uważam, że przydałaby się też taka możliwość filtrowania listy rekordów zadań do projektu wyświetlanych z poziomu Projekty / Podgląd /  Zadania projektu.
Jednak dla mnie i części użytkowników możliwość rzucenia okiem na tablicę ze wszystkimi zdaniami poukładanymi w kolumnach wg statusu pozwala szybko i łatwo zorientować się w sytuacji. W zurmo aktualnie też nie jest to w pełni optymalne rozwiązanie, gdyż brak zróżnicowania wizualnego dla poszczególnych zadań w zależności od czasochłonności / czasowego udziału zadania w projekcie. - np oczekiwane byłoby zróżnicowanie wielkościowe - tak jak to jest prezentowane w wykresie Gantt-a.
Także w mojej ocenie rozwiązanie zurmo jest prostszym a pod względem oceny ilościowej czytelniejszym rozwiązaniem dla przeciętnego użytkownika, szczególnie gdy zadania nie różnią się względem siebie bardzo co do czasu realizacji. Dodatkowo gdy za zmiany statusu zadań odpowiada jeden operator i robi to hurtowo - wyświetlenie zadań w tabeli z możliwością użycia Drag&Drop do szybkiej zmiany statusu jest znacznym ułatwieniem. (choć być może zwiększa szanse pomyłki).

**Comment by bpabiszczak** [comment]
Obecnie ma to niski priorytet... i wątpię czy w najbliższych miesiącach będziemy chcieli się czymś takim zajmować. Zamykam.
