### ISSUE TITLE
Is it possible to have 2 different invoices (2 companies in one)

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2861]
Hi, 

this is a usage question. Is it possible to create 2 separate invoices for 2 companies in yetiforce? If an individual has 2 small unrelated businesses, but wants to manage them both from one crm, so that when he creates an invoice, he would be able to select one for either his first or second business which will have the company name and address details for the chosen company, or can it only handle one business?

I hope that makes sense

Kind regards

Percy

**Comment by florek41** [comment]
You can add different PDF templates but how do you want deal with invoices numbers (continous numbering)?

Other way it is to duplicate INVOICE module but i'm not sure if it will work.

**Comment by PercyP** [comment]
Hi Florek41,

thanks for replying. The numbering wouldn't matter so much as its only used as a reference, I basically only need to be able to produce invoices from 2 separate business names. I shall look at the PDF maker

**Comment by florek41** [comment]
So in this way you sholud use PDF module (YF has it's own) - it's here https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&page=1&view=List

**Comment by paula-w** [comment]
Right now YF supports a variety of different PDF templates, but it doesn't support different numbering within one module. The ideal solution would be to add multi-company feature, but that would take around 2 work days. We will add it  if we have a customer who wants to pay for it.
