### ISSUE TITLE
[PL] [BUG] Human resources > Time Control > Graphical calendar

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2862]
Hej,

 Kadry > Czas pracy > Kalendarz graficzny > Dzień - dodałem czas pracy pracownika trwający ciągiem kilka dni. W przypadku podglądu "Dzień/Day" nie jest wyświetlany "czas pracy" w przedostatnim dniu trwania czasu pracy. Czyli jeśli czas pracy trwa od pon. do niedzieli. to w sobotę w kalendarzu w podglądzie :"dzień" nie będzie widoczny czas pracy.

testowane na develop/[ver. 2.3.1772].

**Comment by bpabiszczak** [comment]
O ile pamiętam, to czas pracy nie może lub nie powinien być dłuższy niż 24h... Jak nie jest to blokowane to będzie domyśłnie.

**Comment by Remi007** [comment]
Nie wiem czy dobrze jest blokować czas pracy, np. w przypadku zarządzania zasobami...pracownik w delegacji tygodniowej w systemie będzie oznaczony jako pracujący/zajęty/niedostępny przez 168 godz. :). Gdy to zablokujesz, operator zamiast wykonania jednego wpisu będzie musiał powtórzyć/duplikować wpis w kalendarzu wielokrotnie

**Comment by bpabiszczak** [comment]
I tak być powinno. Co najwyżej dać narzędzie do generowania masowego, ale nie można dawać zaznaczać więcej niż 24h.

**Comment by Remi007** [comment]
A np. takie rozwiązanie dla dodawania czasu pracy/zajętości zasobów (ludzkich) w widoku kalendarza:
- po kliknięciu w pole daty otwiera się formularz z opcją wyboru godziny startu i zakończenia pracy (bez opcji wyboru dat), 
- po zaznaczeniu kilku dni w kalendarzu otwiera się identyczne okno form jak w powyższym przypadku. Efekt : czas pracy maks. 24godz. Jednak automatycznie skopiowany na zaznaczone dni. 

Czyli jeżeli chce zaznaczyć, że pracownik pracował w ciągu 4 dni od g. 8 do g. 15 to zaznaczam odpowiednie 4 dni w kal. Następnie podaje godz. startu i końca pracy. I w ramach zaznaczonych dni generowane są wpisy na każdy z 4dni z czasem pracy 8/ do 15.

**Comment by bpabiszczak** [comment]
Do realizacji:
1. Zablokowanie wpisanie czasu dłuższego niż 24h. 
2. Sprawdzić wyświetlanie czasu pracy w widżecie czasu pracy.
