### ISSUE TITLE
[PL] [Improvement UX] Human resources > Time Control > Graphical calendar

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2863]
Hej,

Kilka moich spostrzeżeń w sprawie zarządzania zasobami:
1. Firmy konstrukcyjno - projektowe, korporacje budowlane itp, w przypadku planowania i zarządzania projektami, zasobami w celu określenia czasu posługują się generalnie numerami tygodni w skali roku., Np. czas trwania projektu  - od 14 tygodnia 2016 do  32 tygodnia 2016r.
2. Zarządzanie zasobami zarówno ludzkimi jak i parkiem maszyn realizowane jest podobnie, ogólnie ujmując na zasadzie dostępności. Poniżej zrzuty z jednego z lepiej zrealizowanych kalendarzy (w mojej ocenie). Cechy:
- możliwość zarządzania zasobami ludzkimi jak i parkiem maszyn (filtr - lista rozwijana pracownicy/maszyny)
- prezentacja numery tygodni
- projekty rozróżnione kolorami 
- drag&drop
- możliwość zmiany wyświetlanego zakresu dat od tygod. do kwartału \
- możliwość edycji z poziomu kalendarza
- filtry np. wybór projektu/zadania/kategorii/typu/oddziału firmy
- możliwość wyłączenia wyświetlania weekendów
- możliwość wyświetlania braku dostępności zasobów / choroby, awarie,przeglądy  wakacje, itp/
- wyświetlanie legendy kolorów - projektów
- możliwość wydruku / eksportu do PDF  [Planx.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/222640/Planx.pdf)

PS. Może warto rozważyć połączenie modułów lub stworzenie nowego... aby zarządzanie zasobami ludzkimi i wyposażeniem/maszynami firmy było realizowane w jednym miejscu za pomocą właśnie kalendarza? 

![skjermbilde 346](https://cloud.githubusercontent.com/assets/17315868/14586962/09df1558-04a9-11e6-8f1f-4706aee80aed.png)
![skjermbilde 347](https://cloud.githubusercontent.com/assets/17315868/14586963/0bc5aa4e-04a9-11e6-9855-f448625b013c.png)
![skjermbilde 348](https://cloud.githubusercontent.com/assets/17315868/14586965/0cf45f46-04a9-11e6-900f-0bb42bb17bc9.png)
![skjermbilde 349](https://cloud.githubusercontent.com/assets/17315868/14586966/0df141c0-04a9-11e6-906e-7aadc33c8e49.png)
![skjermbilde 345](https://cloud.githubusercontent.com/assets/17315868/14586967/10af5a78-04a9-11e6-87a6-eaae3d256232.png)
![skjermbilde 344](https://cloud.githubusercontent.com/assets/17315868/14586968/120a15d4-04a9-11e6-97b1-21d7bc364cd8.png)
![skjermbilde 351](https://cloud.githubusercontent.com/assets/17315868/14587006/1befb954-04aa-11e6-842b-47a1efbf824b.png)

**Comment by bpabiszczak** [comment]
A jakbyś opisaną funkcjonalność realizował za pomocą dostępnych narzędzi w YF?

**Comment by bpabiszczak** [comment]
Na chwilę obecną projekt i czas pracy są mechanizmami niezależnymi. W przyszłości możliwe będzie generowanie grafiku pracy właśnie na podstawie projektu. Odnośnie uwag dotyczących innego systemu, fajnie :] ale to nic nie wnosi. Aby jakiekolwiek zmiany w YetiForce się pojawiły, ktoś je musi wcześniej u nas zamówić w szczególności jeśli mówimy o tak dużej rozbudowie systemu. Więcej tutaj: 
https://yetiforce.com/pl/github/issues/203-pomys%C5%82y-zwi%C4%85zane-z-rozwojem-systemu.html
