### ISSUE TITLE
[PL] funkcjonalność YF a branża konstrukcyjna/budowlana

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2864]
Wiem, że YF to generalnie CRM, jednak już teraz możliwości YF są ponad przeciętne w tej kategorii, z powodzeniem może być stosowany w znacznie szerszym aspekcie zarządzania w firmie. Proponowane przeze mnie rozwiązania to informacja zwrotna od firm z dużej branż budowlanej, konstrukcyjnej i projektowej. Funkcjonalność YF w szerokim zakresie pokrywa się z rozwiązaniami dedykowanymi dla wspomnianej branży: CRM, HRM, Zarządzanie projekatmi, inwentaryzacja majątku/obrót towaru, ewidencja czasu pracy.... Największa różnica jest w ofertowaniu/kosztorysowaniu (współpraca dedykowanych aplikacji z programami do kosztorysowania), zarządzaniu zaopatrzeniem, BHP, obiegu dokumentów (umowy, protokoły, mapy/geodezja, pisma urzędowe, specyfikacje itp - w przeciwieństwie do YF w dedykowanych są dokumenty / formularze podzielone na kategorie / lub/i są obsługiwane przez dodatkowy moduł).

**Comment by bpabiszczak** [comment]
A jakie tutaj jest pytanie?

**Comment by Remi007** [comment]
Pytania brak. To bardziej nawiązanie do wcześniejszych sugestii, wyjaśnienie skąd pomysły i ewentualnie pokazanie gdzie sugerowane rozwiązania mogą się przydać. Pozdrawiam.

**Comment by bpabiszczak** [comment]
Ogólnie z pomysłami to my problemu nie mamy, ja sam ma z 10 na godzinę, problem jest z tym, kto będzie te pomysły realizował :D
