### ISSUE TITLE
[BUG] Unable to create reports in Master&Dev

### ISSUE THREAD

**Issue by networkpanic** [YetiForceCompany/YetiForceCRM#2872]
In Yetiforce Master & Dev branch, it isnt possible to create reports

Nothing happens when pressing new report button

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/6fcd1e947f5d87e657a220ca6b9db7025a980c47

Refreshed test versions check now.
