### ISSUE TITLE
v3.0.0 

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#2876]
Congrats folks for v. 3.0.0.

**Comment by PercyP** [comment]
Brilliant!!!

Well done from me too! Looks amazing!

**Comment by paula-w** [comment]
Thanks! :smile: 
The official release notes will be published tomorrow, we still wanna fix a few things here and there, and  make sure everything works flawlessly.

**Comment by PercyP** [comment]
Hi Paula, 

just testing and its working flawlessly so far!! Would it mean that we would have to re-install the official release or will it be possible run an update package?

it is very exciting :)

**Comment by skramanzia** [comment]
Hi Paula, do have any news about this issue #2807,, this is very important to deploy the new release. :(

**Comment by playmono** [comment]
Same here,

Great job guys :)
