### ISSUE TITLE
[PL] [Improvement UX] [logic / BUG] Human resources > Employees vs. Users and Time Control

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2877]
Hej,

## Gratuluje drużynie YetiForce stabilnej v.3 :)

testowane na  [ver. 3.0.0]

Właściwie nie jestem pewien czy to ja już się zapętliłem czy jednak jest w YF jakaś pętla logiczna ;)
Do rzeczy. Chciałem zgłosić temat dot. modułu Czas pracy/Time Control, w relacji do Pracowników i Użytkowników systemu. 
Pierwotnie wydawało mi się, że działa to tak, że **moduł czas pracy służy do kontroli czasu pracy Pracowników z modułu Pracownicy.** Czyli nie ma nic wspólnego z Użytkownikiem zalogowanym do YF. I tu chciałem zgłosić **propozycję zmiany logiki,** tzn.**aby Pracownik z modułu Pracownicy był powiązany z Użytkownikiem zalogowanym do systemu.**
Aby po zalogowaniu Użytkownik mógł:
dodawać w module Czas Pracy swoje godziny pracy, które automatycznie będą również wyświetlane w module Pracownik w zakładce Czas Pracy.

**Ideałem wg mnie jest aplikacja np. na tel/smartfona, która po zalogowaniu Użytkownika, pozwala 1-kilk. wejść w moduł rejestracji czasu pracy, z możliwością wyboru procesu/projektu/zadania/godziny start/stop** i dodatkowo np. dodania maszyny/pojazdu wraz z czasem pracy. Dodatkowo z możliwością oznaczenia nadgodzin (rejestracja czasu pracy nie tylko do planowania ale i do wyliczenia wynagrodzenia czy specyfikacja/kosztorys do faktury sprzed.). Pomijam temat integracji z system. automatycznej rejestracji czasu.

**Jednak** testując Moduł Czas Pracy widzę, że po części tak jest to realizowane: choć nie jest to klarowne dla mnie. Tzn. w module Kadry > Pracownicy > Podgląd wyświetlany jest czas pracy Pracowników, w których ustawiono jako właściciela rekordu aktualnie zalogowanego Użytkownika. Ustawienie powiązanego modułu Pracownicy na wartość określonego Pracownika A nie wpływa na stan wyświetlenia rekordu  w Podglądzie czasu pracy tego Pracownika A.

**Comment by bpabiszczak** [comment]
Cel jaki sobie wyznaczamy dla wersji 3.1 to optymalizacja i poprawa procesów. Wersja 3.0 to przebudowa silnika i nowe moduły, dlatego 3.1 wniesie wiele jeżeli chodzi o logikę działania. W tym proces czasu pracy i cały HR będzie ulepszany.

**Comment by bpabiszczak** [comment]
Wszystkie procesy są ulepszane i w tym również czas pracy, jednakże kiedy "ulepszenia" się pojawią zależy przede wszystkim od tego, kiedy zostaną przez klientów zamówione, a więc na niektóre będzie trzeba czekać miesiąc a na inne rok. 

Odnośnie Twojego pomysłu. To czy czas pracy jest przypisany do użytkownika czy pracownika to element wtórny, dla większości firm musi być zachowana funkcjonalność konieczna do realizacji celu a droga jak to osiągniemy nie ma większego znaczenia. 

Moduł Pracowników jest "nieskończony" i wymaga dopracowania... istnieje powiązania pomiędzy pracownikiem a użytkownikiem, ale wszystkie jest przypisywane do użytkownika i na chwilę obecną nie będziemy tego zmieniać.
