### ISSUE TITLE
[PL] [BUG] Human resources > Employees vs.Time Control

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#2878]
v.3.0.0.
 Kadry > Pracownicy > Podgląd > Czas pracy 

**Urlop jest sumowany do czasu pracy**

(roczny wymiar urlopu - czy planowane jest pomniejszanie dostępnego urlopu w zależności od wykorzystania?)

**Comment by bpabiszczak** [comment]
Można powiedzieć, że obecny proces HR jest dość ubogi, aby go ulepszyć to musimy mieć klienta, który będzie chciał z niego w pełni korzystać wówczas dokonamy optymalizacji. Jest nadzieja, że będzie to niedługo, jednakże ktoś musi w to zainwestować za nim ten proces ulepszymy.
