### ISSUE TITLE
Error Install v 3.0.0

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2879]
When you install a clean sheet with the logo. Upon entering the site, a blank page with background.

v 3.0.0

![animation 188](https://cloud.githubusercontent.com/assets/1402355/14628486/0111c5fe-0618-11e6-9ed5-372bcfb20b3d.gif)

**Comment by kpaulaha** [comment]
Works here, 2 on ubuntu, 3 on debian, one on win10

**Comment by waw555** [comment]
Established pure Debian 8.3 and the control panel vestacp

**Comment by SkavenKF** [comment]
Works on Windows 10 with WAMP, see:
 https://github.com/YetiForceCompany/YetiForceCRM/issues/2843#issuecomment-211487681

**Comment by paula-w** [comment]
Please give us more details on your server and its configuration

**Comment by ayoogh** [comment]
Have had the same problem with last page of Installation wizard taking ages to finish and showing a blank page. It also does not take you to the CRM  automatically when install is completed as stated in the documentation. See (https://github.com/YetiForceCompany/YetiForceCRM/issues/2843). One does know what is happening.

Server : XAMPP Version 5.6.19 on Windows 7. - configuration as per documentation.

Suggestion: create a page that advises the user that the installation is complete  with a link to the CRM login page.

**Comment by lalord** [comment]
after running module update  "Update package 2.3.49 → 2.3.1072 "
just get this page:


Error!!!

Permission to perform the operation is denied for name

Go back Home Page

**Comment by mariuszkrzaczkowski** [comment]
@ayoogh
If you get blank screen you have to check PHP and Apache error logs

@lalord
Install the fix before upload and check what the logs say
I tested the update for this version and I can't see the error
https://github.com/YetiForceCompany/YetiForceCRM/commit/a9c32efe510cfb95318ebcb5556d5cfbab647f7a

**Comment by waw555** [comment]
Version v 3.1.0 also not installed. A blank screen and all. The log file is empty. I can not continue translating and testing, until set (((((

**Comment by mariuszkrzaczkowski** [comment]
Do you set the appropriate php_flag ?
https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html#phplogs

**Comment by waw555** [comment]
`109.195.102.150 - - [20/May/2016:08:12:01 +0500] "GET / HTTP/1.0" 200 9465 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:17 +0500] "GET / HTTP/1.0" 302 231 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:17 +0500] "GET /install/Install.php HTTP/1.0" 200 7660 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:17 +0500] "POST /install/index.php HTTP/1.0" 200 197 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:20 +0500] "POST /install/Install.php HTTP/1.0" 200 10600 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:21 +0500] "POST /install/index.php HTTP/1.0" 200 197 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:22 +0500] "POST /install/Install.php HTTP/1.0" 200 29540 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:22 +0500] "POST /install/index.php HTTP/1.0" 200 197 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:23 +0500] "POST /install/Install.php HTTP/1.0" 200 10789 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:23 +0500] "POST /install/index.php HTTP/1.0" 200 197 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:25 +0500] "POST /install/Install.php HTTP/1.0" 200 15714 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:12:26 +0500] "POST /install/index.php HTTP/1.0" 200 197 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:13:02 +0500] "POST /install/Install.php HTTP/1.0" 200 10930 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:13:02 +0500] "POST /install/index.php HTTP/1.0" 200 197 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
109.195.102.150 - - [20/May/2016:08:13:04 +0500] "POST /install/Install.php HTTP/1.0" 200 9376 "http://crm.kartellinni.ru/install/Install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"`

**Comment by waw555** [comment]
file included debug.php

// Enable log4php -> cache / logs / system.log
'LOG4PHP_DEBUG' => true,

Got system.log file

Errors found on database Mysql, now I will understand

`insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('general','oneDay','false')
Fri May 20 04:28:16 2016,794 [28699] ERROR DB - Query Failed: /*Data for the table `yetiforce_proc_tc` */

insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('general','oneDay','false') | MySQL server has gone away | SQLSTATE[HY000]: General error: 2006 MySQL server has gone away(/home/admin/web/crm.kartellinni.ru/public_html/install/models/InitSchema.php : 70)
Fri May 20 04:28:16 2016,794 [28699] INFO DB - Query: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('general','timeOverlap','false')
Fri May 20 04:28:16 2016,795 [28699] ERROR DB - Query Failed: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('general','timeOverlap','false') | MySQL server has gone away | SQLSTATE[HY000]: General error: 2006 MySQL server has gone away(/home/admin/web/crm.kartellinni.ru/public_html/install/models/InitSchema.php : 70)
Fri May 20 04:28:16 2016,795 [28699] INFO DB - Query: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('timeControlWidget','holidays','true')
Fri May 20 04:28:16 2016,795 [28699] ERROR DB - Query Failed: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('timeControlWidget','holidays','true') | MySQL server has gone away | SQLSTATE[HY000]: General error: 2006 MySQL server has gone away(/home/admin/web/crm.kartellinni.ru/public_html/install/models/InitSchema.php : 70)
Fri May 20 04:28:16 2016,795 [28699] INFO DB - Query: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('timeControlWidget','workingDays','true')
Fri May 20 04:28:16 2016,795 [28699] ERROR DB - Query Failed: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('timeControlWidget','workingDays','true') | MySQL server has gone away | SQLSTATE[HY000]: General error: 2006 MySQL server has gone away(/home/admin/web/crm.kartellinni.ru/public_html/install/models/InitSchema.php : 70)
Fri May 20 04:28:16 2016,795 [28699] INFO DB - Query: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('timeControlWidget','workingTime','true')
Fri May 20 04:28:16 2016,795 [28699] ERROR DB - Query Failed: insert  into `yetiforce_proc_tc`(`type`,`param`,`value`) values ('timeControlWidget','workingTime','true') | MySQL server has gone away | SQLSTATE[HY000]: General error: 2006 MySQL server has gone away(/home/admin/web/crm.kartellinni.ru/public_html/install/models/InitSchema.php : 70)
Fri May 20 04:28:16 2016,795 [28699] INFO DB - Query: /*Data for the table `yetiforce_updates` */`

**Comment by waw555** [comment]
That this option interferes with the installation

etc/mysql/my.cnf

wait_timeout=600 (value of 10 was found)

**Comment by mariuszkrzaczkowski** [comment]
Check the php.ini settings
mysql.connect_timeout
default_socket_timeout

**Comment by waw555** [comment]
Directive	Local Value	Master Value
default_socket_timeout	6000	60

Directive	Local Value	Master Value
mysql.connect_timeout	6000	60
