### ISSUE TITLE
Fatal error: Can't use method return value in write context in /modules/Users/models/Privileges.php on line 438

### ISSUE THREAD

**Issue by averied** [YetiForceCompany/YetiForceCRM#2883]
I'm getting this error after a fresh intallation. When I open the index page it throws

Fatal error: Can't use method return value in write context in /modules/Users/models/Privileges.php on line 438

This belongs to this line of code:

`$permissionsRelatedField = empty($role->get('permissionsrelatedfield')) ? [] : explode(',', $role->get('permissionsrelatedfield'));
`

My hosting provider has 5.4.45, So I guess this is the problem, as it's the first time I get this error.

**Comment by mariuszkrzaczkowski** [comment]
Check the requirements, the minimum PHP version is 5.5
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html#server

**Comment by easaw** [comment]
Add 'AddHandler application/x-httpd-php55 .php' to your htaccess
