### ISSUE TITLE
examle special funcions... for PDF - wzór funkcji do nowych modułów...

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2884]
Czy istnieje gdzieś dostępna funkcja - wzór do PDF ? Tak która jest jako examle pobiera wszytskie rekordy z danej tableli - jak pobrać rekordy produktów z danego rekordu ... Po prostu potrzebuję ukryć niektóre kolumny w poszczególnych wydrukach - :( - ps.. fajnie by było mieć możliwość wklejenia także pól typu  "sumgross" w modułach specjalnych - a już cudownie byłoby mieć możliwość jak starym module OSSPDF mieć możliwość włączania i wyłączania poszczególnych kolumn w poszczególnych wydrukach. Gratuluję 3 !!! :)

**Comment by bpabiszczak** [comment]
Ogólnie, to wszystko to jest zarządzalne. System domyślnie drukuje całą tabelkę, ale można sobie to kontrolować modyfikując funkcje specjalną np.: https://github.com/YetiForceCompany/YetiForceCRM/tree/5020feec05d4b21f2a4b9207d1fe59bdc6a3bf1e/modules/Vtiger/pdfs/special_functions tu jest zestaw funkcje które można używać, po nazwie dojdziesz która to jest ta którą użyłeś w szablonie, jak coś zmieniasz to utwórz własną funkcje i na niej zmieniaj bo inaczej Ci ją nadpiszemy przy aktualizacji.

**Comment by zimart** [comment]
Próbowałem :) nie poradziłem sobie :( potrzebuje wyłączyć np 2 kolumny z wydruku...ewentualnie gdzie mogę znaleźć funkcje odpowiedzialne... Może chociaż jakiś wzór :) żeby pobrać rekordy tylko te które potrzebuję z tabeli inventory... Z danego rekordu np zamówienia ... :( czyli korekta example...

**Comment by bpabiszczak** [comment]
Wykracza to poza ramy bezpłatnego wsparcia...

**Comment by zimart** [comment]
Rozumiem.
Jakoś sobie poradziłem :) W razie potrzeby pomogę - jeżeli ktoś potrzebuje - troche na piechotkę ale działa.
