### ISSUE TITLE
Menu icons - change dollar symbol

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2886]
Hi,

is it at all possible to change the dollar symbol to a GB pound - the one that is used for accounting?

I cannot see where I might do this. 

Percy

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2371

**Comment by PercyP** [comment]
Thank you!

that was amazingly simple. Basically, just go to the Modules, Menu Configuration, then right click on desired menu and select your new glyph icon via the dropdown.

The more I am working with Yetiforce, the more I am seeing just how much hard work has gone in to improving and streamlining it. It is very very impressive and a joy to work with. |Can't wait to see more in the store!

Percy
