### ISSUE TITLE
Unable to scroll to sub-menu links if not visible on screen i.e. Databases-Reports

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2888]
Hi,

I am not sure if this is a device issue or Yetiforce, so thought I would notify you just in case. 

I have a Windows Surface Pro 3 tablet, and when I click on any menu item that has more sub-menus than fit on the screen, I cannot scroll to those that are not visible - including not using the arrow down as this does nothing. The only way to view additional menu links is to rotate table to portrait mode. 

I have tried this in both Google Chrome and Firefox so far.

Percy

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/c5b0ddd1881abab17a9847c41dddd067fd9418b0
