### ISSUE TITLE
Obroty magazynowe - przesunięcie

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2889]
Do czego służy ta funkcja?
Początkowo myślałem, że agreguje ona w sobie dwie funkcjonalności: MW i MP, ale chyba nie wiem jak do tego dojść, albo służy do czegoś innego...

**Comment by bpabiszczak** [comment]
a czym są przesunięcia? Proszę o link.

**Comment by amdziak** [comment]
Jasne:
Screen z gitdevelopera poniżej:
![przesuniecia](https://cloud.githubusercontent.com/assets/11409255/14735154/9ee0a95e-086f-11e6-9db4-47d40305124a.PNG)

**Comment by amdziak** [comment]
NIkt nie potrafi wytłumaczyć działania procesu systemowego?

**Comment by bpabiszczak** [comment]
No nikt nie potrafi wytłumaczyć, czyli co zamykamy?

**Comment by amdziak** [comment]
To skoro nikt nie potrafi wytłumaczyć działania procesu systemowego który ktoś:
1) zaprojektował
2) zakodował
3) przetestował
To po co tworzyć coś takiego?

**Comment by bpabiszczak** [comment]
A kto powiedział, że nikt nie potrafi. Nie przypominam sobie, abyśmy mieli to jakiś SLA na GitHub. Odpowiadamy jak mamy czas a nie wtedy kiedy ktoś od nas tego oczekuje.

**Comment by amdziak** [comment]
Ok - w takim razie poczekam.

**Comment by bpabiszczak** [comment]
Obroty magazynowe są tym samym czym są szanse sprzedaży. Jako takie szanse sprzedaży nie są do niczego potrzebne, ponieważ wszystkie informacje możemy przypisywać bezpośrednio do kontrahenta [np. kalendarz, komentarze, zamówienia, oferty itd.]. Szanse sprzedaży wprowadzają pewnego rodzaju porządek i zdarzenia dotyczące tej samej sprzedaży przyporządkowują do jednej szansy. 

To samo mają robić obroty magazynowe, wszystko co jest powiązane z obrotem magazynowym ma być porządkowane w jednym miejscu np. aby towar dostarczyć do klienta należałby np.:

1. Zamówić u dostawcy
2. Dodać awizo dostawy. 
3. Przyjąć na magazyn. 
4. Dekompletacja towaru
5. Następnie kompletacja gdy wszystko dojdzie od różnych dostawców. 
6. Wydanie z magazynu. 
7. Korekty
8. itd.

Obroty mają to porządkować i pokazywać ciągłość zdarzeń i na jakim etapie jesteśmy. Powyżej to tylko przykład i może niekoniecznie trafiony. Chodzi o samą idee.
