### ISSUE TITLE
whats new, asterisk

### ISSUE THREAD

**Issue by teratronik** [YetiForceCompany/YetiForceCRM#2892]
Hi! Where i can read about what is new in Yeti, and what about Asterisk integration?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2881

**Comment by teratronik** [comment]
I'm sorry, but i can't find nothing about Asterisk integration in your topic.

**Comment by paula-w** [comment]
There's nothing about Asterisk because right now we're not planning to do anything with it. We get a lot of questions about this integration, but so far nobody ordered it, and the new functionalities we add result from what our clients order.

**Comment by teratronik** [comment]
Okh, i'm very dissapointed. This is the last thing, that obstructs migration from vtiger. I will wait your progress in this direction.
