### ISSUE TITLE
Customer Portal adding ticket problem

### ISSUE THREAD

**Issue by iaiox** [YetiForceCompany/YetiForceCRM#2893]
When customer try to add a ticket from customer portal, Severity, Contract, Category and Priority are empties (select list don't have any options).

Sorry for my english.
![customer](https://cloud.githubusercontent.com/assets/5320970/14741631/144db486-086e-11e6-8390-c0611fc729b7.png)

**Comment by mojtabajml** [comment]
I have same problem, is there any patch to sove this problem?
