### ISSUE TITLE
Some errors in your public demo

### ISSUE THREAD

**Issue by playmono** [YetiForceCompany/YetiForceCRM#2895]
Hi YetiForce team,

I have some doubts about yours (and a fresh installation i did) of new YetiForce 3.0 since I dont know if there is a bug or I dont know how works.

1. NaN-NaN-NaN NaN:NaN:NaN error:
I dont know if there is some test you did before developing the feature or maybe is a bug.
![2016-04-22_15h33_58](https://cloud.githubusercontent.com/assets/1773174/14744421/03acb4a4-08a7-11e6-8eb9-e2d013057caa.png)

2. Add Widget:
What's supossed to be in "Add Widget" button? If it's empty because there arent widgets or something like this, a text displaying "Empty widgets" would be nice.
![2016-04-22_15h34_56](https://cloud.githubusercontent.com/assets/1773174/14744460/2c891f48-08a7-11e6-88c8-8986b8ef34e7.png)

3. Whats supossed to be after clicking in Calendar icon? If it's empty because there arent events or something like this, a text displaying "Empty Events" would be nice.
![2016-04-22_15h34_41](https://cloud.githubusercontent.com/assets/1773174/14744486/4faf5dca-08a7-11e6-9110-8d2cb7999c12.png)

4. Statics from Language Statics works pretty bad.
I just tested Payments Out, and module is 100% translated:
![2016-04-22_16h47_23](https://cloud.githubusercontent.com/assets/1773174/14745114/0637d066-08aa-11e6-939f-6d415fb239bc.png)

Thank you guys.

**Comment by mykljohn** [comment]
Correcting Invoice is misspelled (Corecting) in the Tabs from Accounts.  Looks great!

**Comment by paula-w** [comment]
1. In our opinion the error doesn't occur in the latest version. 
2. One issue = one problem. You can open a new issue and describe this error.
3. One issue = one problem. You can submit a new issue.
4. One issue = one problem. We think the statistics are okay.
5. We strongly believe in our "one issue = one problem" rule, and we would like to ask all our users to follow that rule. You can read more about reporting bugs in [here](https://yetiforce.com/en/github/issues/126-issues.html)
