### ISSUE TITLE
Barcode generator

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#2896]
Hello. How i can integrate a barcode generator for EAN-13 code?
Please help me.

**Comment by bpabiszczak** [comment]
1. https://omig.ny.gov/data/MPDF573/examples/show_code.php?filename=example37_barcodes.php
2. https://github.com/YetiForceCompany/YetiForceCRM/blob/5020feec05d4b21f2a4b9207d1fe59bdc6a3bf1e/modules/Vtiger/pdfs/special_functions/ProductsTableNew.php
