### ISSUE TITLE
Customer Portal : product and services not displayed 

### ISSUE THREAD

**Issue by PW0131** [YetiForceCompany/YetiForceCRM#2899]
Why are not displayed in the customer portal sections of products and services? Whether it is not geniriruet list, all is well with access. The rest is normal sections . 
Where to dig? Thank you

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2907

**Comment by bpabiszczak** [comment]
![git_1](https://cloud.githubusercontent.com/assets/10197525/16170200/fd823722-354a-11e6-87f3-f736d72c4dc1.gif)
