### ISSUE TITLE
[question] help text 

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#290]
Is there a place where to edit the content of help for a custom field when the help icon is added.

**Comment by kpaulaha** [comment]
Noticed the new way to edit help icon content. Looks fine, great!

**Comment by bpabiszczak** [comment]
Tomorrow I'll post a link to the manual.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/administrator-documentation/panel/translations-editor/114-help-icons.html
