### ISSUE TITLE
widgets and chart 

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#2900]
hi
did yetiForce  have any chart widgets in home page like vtiger ?
and how can i add widgets to my home page.

**Comment by bpabiszczak** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67

**Comment by billygoat-trump** [comment]
Thanks @bpabiszczak i found that, It has been covered by <div class="infoUser">Administrator The </div>
