### ISSUE TITLE
[Question] Invoice

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2901]
Is there a way to have the Invoice to start with Service field rather than Product?

**Comment by mariuszkrzaczkowski** [comment]
Do you have added the product on a Accounts?
![crm](https://cloud.githubusercontent.com/assets/10198654/14914945/01185e06-0e0f-11e6-8c08-ed89bc12c596.png)
![portal](https://cloud.githubusercontent.com/assets/10198654/14914947/03969210-0e0f-11e6-9123-9df9b547b22c.png)

**Comment by mariuszkrzaczkowski** [comment]
You need to change the order of modules in u_yf_finvoice_invfield. Default module is the first in the list
![serv](https://cloud.githubusercontent.com/assets/10198654/14915046/dba8d294-0e0f-11e6-93f4-85597045c97a.png)

**Comment by mykljohn** [comment]
Thanks, that's very convenient!!!  great job on the new design!
