### ISSUE TITLE
Data Transfer from 2x to 3.0

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2904]
I have just installed 3.0 and it's looking GREAT!!!  Good job everyone.  Seriously!  

But we had a "Bad" installation of 2x, running into problems with the upgrades, so we want to import the data from the 2x version into the new 3.0 system.  But I'm concerned with the relationships between Accounts, Contacts, Invoices, and Payments, because I know some of these fields are stored in the vtiger_crmentity and vtiger_crmentityrel tables.

What is the best way to achieve this?

Cheers,  Mykl

**Comment by eptapsyxos** [comment]
The best way is to pay a service pack for 299 euros to migrate.

**Comment by mykljohn** [comment]
I can appreciate that, but I'd have to get approval from my boss and he's not so agreeable.  Any other help?   What would be the next best way? :)

**Comment by paula-w** [comment]
Hi @mykljohn 
Glad to hear you like 3.0 :)

We prepared a package for 2.3.49, that adds an export mechanism to XML files, and  version 3.0 includes an import mechanism for XML files. We can also use CSV, but unfortunately it doesn't work for relations. 

The best solution would be migration 2.x → 3.x, you can do it using the update package. All of the necessary packages and descriptions can be found here: https://github.com/YetiForceCompany/YetiForceCRM/issues/2881 (descriptions in UPDATE section)

If you want us to do it for you, then you can purchase the migration service:  https://shop.yetiforce.com/en/migration/14-migration-v23-v30.html

**Comment by zebrahosting** [comment]
The XML export does not include contacts?
We have a lot of custom fields, is there a way to bring them over in a 'clean' setup?

**Comment by paula-w** [comment]
@zebrahosting The only right way is to migrate the whole system. XML is used to migrate only modules with products – invoices, orders, quotes.
