### ISSUE TITLE
Dodanie własnego modułu

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2905]
Szukałem w Instrukcji developerskiej, ale tam nic takiego nie ma...
Napisałem sobie prościutki moduł - jak zgodnie z regułami panującymi w YF dodać go do pracującego systemu?
Tak jak w VTiger poprzez vtlib, czy jakoś specjalnie?
W sumie to samo pytanie jeśli chodzi o nowe pola tak już na przyszłość.

**Comment by bpabiszczak** [comment]
W systemie naszym jak i Vtiger są dwie metody dodawania modułu:
1. Poprzez paczkę ZIP.
2. Poprzez Vtilib

choć w rzeczywistości ZIP jest obsługiwany przez vtlib. My używamy paczek ZIP, vtlib używamy gdy chcemy zmienić coś w module np. dodać pole z poziomu skryptu.

**Comment by amdziak** [comment]
Dziękuję za błyskawiczną odpowiedź!

**Comment by bpabiszczak** [comment]
ZIP-a dodajemy z zarządzania modułami. Możemy sobie nawet utworzyć moduł z poziomu edytor w konfiguracji i go wyeksportować.

**Comment by amdziak** [comment]
Wiem, że ZIP'a dodajemy z zarządzania modułami.
No można tak stworzyć moduł, ale ten moduł jest wtedy dość okrojony, a mi zależy żeby wykonał jeden update i jeden update na innych tabelach :)

**Comment by amdziak** [comment]
Hmm - a jak wywołać samego vtliba?
Vtigerowe adres/vtlib.test.html nie dziala...

**Comment by mariuszkrzaczkowski** [comment]
Tu jest jest przykład użycia vtlib https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Settings/ModuleManager/models/Module.php#L118

**Comment by amdziak** [comment]
Wiem jak go uzyć(mam już taki skrypt), tylko nie wiem jak go potem wywołać, aby moduł się dodał...

**Comment by bpabiszczak** [comment]
http://community.vtiger.com/help/vtigercrm/developers/vtlib/
