### ISSUE TITLE
Which update should i use for  YetiForce_current_version = '2.3.1741

### ISSUE THREAD

**Issue by noclav** [YetiForceCompany/YetiForceCRM#2909]
I would like to test version 3. I see that im on 2.3.1741. Can i use the update 2.3.1072 to 3.0.0 to do the update? 

thanks

**Comment by noclav** [comment]
I edited the version.php file in the config and set the version to 2.3.1072 and the update worked. Not sure if that was ok to do.

**Comment by bpabiszczak** [comment]
Good :]
