### ISSUE TITLE
 Warning: array_key_exists() expects parameter 2 to be array, null given in ..../modules/Vtiger/models/Menu.php on line 41

### ISSUE THREAD

**Issue by aylanet2** [YetiForceCompany/YetiForceCRM#2910]
We try to port a vtiger translation of Greek Language to YetiForce, the forms looks ok but the menu is broken with that message, any ideas?

Thanks in advance

**Comment by mariuszkrzaczkowski** [comment]
Check if the file exists in your language pack
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/languages/en_us/Menu.php

**Comment by aylanet2** [comment]
That Solved the Isuue, It was the missing PHP
Now it works in Greek Language, However still some translation to de done :)
Thx
