### ISSUE TITLE
Customer Portal 3.0 doesn't send password 

### ISSUE THREAD

**Issue by noclav** [YetiForceCompany/YetiForceCRM#2911]
Im on Yetiforce ver. 3.0.0 and portal version 3.0 when i create a portal user i receive the email but the password is blank.

**Comment by noclav** [comment]
i receive everything else but this #s#ContactsPortalPass#sEnd#
any logs i can check to see why this is not working. Also could it be im missing a php module? This is a new install of Debian 8.

**Comment by kpaulaha** [comment]
Have you activated the trigger "Generate customer login details" in workflow? Works fine on here.

**Comment by noclav** [comment]
wow that was it. It would be nice if they had a section of video tutorials. I bet it would cut the issues in half. 

Thanks

**Comment by kabelo38** [comment]
Seem to be stuck here

I can get an email but the email does not contain a password value.
Couldn't find the 'Generate customer login details' in the current release.
Email contents goes as follows.

Dear First name last name,
Created for your account in the customer portal, below sending data access
Login: email@gmail.com
Password:

I use Portal 2  found here https://github.com/YetiForceCompany/YetiForcePortal2 and I use YT 4.0

**Comment by PercyP** [comment]
@kabelo38 

I will also try portal 2 as portal 3 doesn't even send emails. I too am on yetiforce version 4.0 All I get is the login screen. They seem to have removed the workflows for Generate customer login details.

**Comment by octavian2204** [comment]
Version 4 does not have password generator as well. Even generateRandomPassword function is not mentioned in no files.

**Comment by PercyP** [comment]
I heard that the previous versions don't work with yetiforce v.4x. They are looking to release the new portal in August/Sept time. This can be sooner up if someone orders its development which is fair enough. Maybe if we group together to raise the development fee it can be moved forward? I would fund it myself only I am already having some custom work done by Yeti team so don't have the cash (yet).

**Comment by octavian2204** [comment]
Hi, how much does the fee costs?

**Comment by PercyP** [comment]
@octavian2204 

Not sure. Maybe the yetiforce team can tell us @bpabiszczak . But if we all chip in it will be less of an outlay individually.

**Comment by paula-w** [comment]
We still need around 100 hours to finish the portal. A significant part of it has already been finished, but there is still a lot to do.
We understand that 100h is a lot to pay for, but every donation helps speed up the portal development.

**Comment by PercyP** [comment]
That works out roughly at 3000 euros, how many of you would be prepared to chip in?

**Comment by centoasa** [comment]
Some news about this issue?

**Comment by octavian2204** [comment]
Nope.. I gave up

**Comment by PercyP** [comment]
Hi @centoasa @octavian2204 

I believe they have been working on this for some time as it was ordered by a client. There was some news update about the new portal here: https://github.com/YetiForceCompany/YetiForceCRM/issues/5447

which says:

"The portal will be released together with version 5.0, which will be published at the beginning of next year." 

That was posted early November time when they were hoping to release version 4.3 YF, but that has gone back so it looks like it will be released Feb 19th (when YF5 is supposed to be released).

**Comment by octavian2204** [comment]
They had partially released somehow portal2 also, which is not working..
and afterwards they wrote that it will be finished someday...
Imho, they should do one working product and not releasing half made
solutions...
