### ISSUE TITLE
phpError.log is too large

### ISSUE THREAD

**Issue by MexasPT** [YetiForceCompany/YetiForceCRM#2912]
The Error.log php file is taking giant dimensions ... 300MB.

I commented the following line in config.inc.php file:
// AppConfig :: INISET ('error_log' $ root_directory cache / logs / phpError.log. ');
But now the file is being created in the root without the extension file.

How do I prevent the creation of this file?

**Comment by mariuszkrzaczkowski** [comment]
Log files are growing because your error registration level might not be set properly.
Check your error_reporting in php.ini, should be "E_WARNING & E_ERROR & E_NOTICE & E_DEPRECATED & ~E_STRICT"
Check what types of events are registered in logs, eg. NOTICE,STRICT,WARNING.

**Comment by MexasPT** [comment]
I have "STRICT" and "NOTICE" events.
How do I prevent the creation of this file? It can be disable?

Eg.:
[27-Apr-2016 12:04:03 Europe/London] PHP Strict Standards:  Declaration of AntlrLexer::matchAny() should be compatible with BaseRecognizer::matchAny($input) 
[27-Apr-2016 12:04:03 Europe/London] PHP Notice:  Undefined variable: profileGlobalPermission in /home/vitaplus.com/public_html/yetiforce/modules/Vtiger/helpers/Util.php on line 726

**Comment by mariuszkrzaczkowski** [comment]
Change error_reporting in php.ini to "E_WARNING & E_ERROR & E_NOTICE & E_DEPRECATED & ~E_STRICT"
