### ISSUE TITLE
sync caldav with davdroid

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#2914]
Sync error with davdroid and caldav.

exception: Sabre\DAV\Exception\UnsupportedMediaType
message: This resource only supports valid iCalendar 2.0 data. Parse error: End of document reached prematurely

config/api.php

$enabledServices = [
        //'mobile',
        //'yetiportal',
        'dav',
        //'webservices',
        //'mobileModule',
        //'webservice',
];
/* +***************   DAV   **************** */
$enableBrowser = true;
$enableCardDAV = true;
$enableCalDAV = true;
$enableWebDAV = false;

/* +*********   Webservice config  ********* */
$API_CONFIG = [
        'ENCRYPT_DATA_TRANSFER' => false,
        'AUTH_METHOD' => 'Basic',
        'PRIVATE_KEY' => 'config/private.key',
        'PUBLIC_KEY' => 'config/public.key',
];

cache/logs/davDebug.log:

============ 2016-04-27 17:50:19 ====== Request ======
PUT /api/dav.php/calendars/admin/YFCalendar/51d28abb-f710-413a-9ce0-218dc2bc8431.ics HTTP/1.1
Authorization: Digest REDACTED
If-None-Match: *
Content-Type: text/calendar;charset=utf-8
Content-Length: 3135
Host: 192.168.3.30
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: DAVdroid/1.0.7 (2016/04/14; dav4android; okhttp3) Android/5.0.2
Accept-Language: it-IT, it;q=0.7, *;q=0.5

BEGIN:VCALENDAR
VERSION:2.0
PRODID:+//IDN bitfire.at//DAVdroid/1.0.7 ical4android ical4j/2.x
BEGIN:VEVENT
DTSTAMP:20160427T155019Z
UID:51d28abb-f710-413a-9ce0-218dc2bc8431
DTSTART;TZID=Europe/Rome:20160428T160000
DTEND;TZID=Europe/Rome:20160428T170000
SUMMARY:Tezttttt
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:Test
END:VALARM
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Rome
TZURL:http://tzurl.org/zoneinfo/Europe/Rome
X-LIC-LOCATION:Europe/Rome
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+004956
TZOFFSETTO:+004956
TZNAME:RMT
DTSTART:18660922T000000
RDATE:18660922T000000
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+004956
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:18931101T000000
RDATE:18931101T000000
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19160603T010000
RDATE:19160603T010000
RDATE:19170401T010000
RDATE:19180310T010000
RDATE:19190302T010000
RDATE:19200321T010000
RDATE:19400615T010000
RDATE:19430329T030000
RDATE:19440403T030000
RDATE:19450402T030000
RDATE:19460317T030000
RDATE:19470316T010000
RDATE:19480229T030000
RDATE:19660522T010000
RDATE:19670528T010000
RDATE:19680526T010000
RDATE:19690601T010000
RDATE:19700531T000000
RDATE:19710523T000000
RDATE:19720528T000000
RDATE:19730603T000000
RDATE:19740526T000000
RDATE:19750601T000000
RDATE:19760530T000000
RDATE:19770522T000000
RDATE:19780528T000000
RDATE:19790527T000000
RDATE:19800406T020000
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19161001T010000
RDATE:19161001T010000
RDATE:19170930T010000
RDATE:19181006T010000
RDATE:19191005T010000
RDATE:19200919T010000
RDATE:19421102T030000
RDATE:19431004T030000
RDATE:19440917T010000
RDATE:19450915T010000
RDATE:19461006T030000
RDATE:19471005T010000
RDATE:19481003T030000
RDATE:19660925T000000
RDATE:19670924T000000
RDATE:19680922T000000
RDATE:19690928T000000
RDATE:19700927T000000
RDATE:19710926T010000
RDATE:19721001T000000
RDATE:19730930T000000
RDATE:19740929T000000
RDATE:19750928T010000
RDATE:19760926T010000
RDATE:19770925T010000
RDATE:19781001T010000
RDATE:19790930T010000
RDATE:19800928T030000
RDATE:19810927T030000
RDATE:19820926T030000
RDATE:19830925T030000
RDATE:19840930T030000
RDATE:19850929T030000
RDATE:19860928T030000
RDATE:19870927T030000
RDATE:19880925T030000
RDATE:19890924T030000
RDATE:19900930T030000
RDATE:19910929T030000
RDATE:19920927T030000
RDATE:19930926T030000
RDATE:19940925T030000
RDATE:19950924T030000
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19440701T000000
RDATE:19440701T000000
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19800101T000000
RDATE:19800101T000000
END:STANDARD
END:VTIMEZONE
END:VCALENDAR

============ 2016-04-27 17:50:19 ====== Error exception ======
**exception: Sabre\DAV\Exception\UnsupportedMediaType
message: This resource only supports valid iCalendar 2.0 data. Parse error: End of document reached prematurely**
file: /libraries/SabreDAV/CalDAV/Plugin.php
line: 866
code: 0
stacktrace: 
#0 /libraries/SabreDAV/CalDAV/Plugin.php(818): Sabre\CalDAV\Plugin->validateICalendar('', 'calendars/admin...', false, Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), true)
#1 [internal function]: Sabre\CalDAV\Plugin->beforeCreateFile('calendars/admin...', '', Object(Sabre\CalDAV\Calendar), false)
#2 libraries/SabreDAV/Event/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#3 libraries/SabreDAV/DAV/Server.php(1051): Sabre\Event\EventEmitter->emit('beforeCreateFil...', Array)
#4 libraries/SabreDAV/DAV/CorePlugin.php(513): Sabre\DAV\Server->createFile('calendars/admin...', Resource id #4, NULL)
#5 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 libraries/SabreDAV/Event/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#7 libraries/SabreDAV/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#8 libraries/SabreDAV/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#9 api/dav.php(79): Sabre\DAV\Server->exec()
#10 {main}

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/f034e6193b329c2bf1c5df9f9a9d40a871d5e48f
