### ISSUE TITLE
User Password v3.0.0

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#2915]
Where the user can modify your password?

**Comment by kpaulaha** [comment]
Set 'SHOW_MY_PREFERENCES' => true, in security.php

**Comment by skramanzia** [comment]
Great!!, work for me!.. But, is the official troubleshooting? why not enable by default?

**Comment by paula-w** [comment]
Hi.
This mechanism requires some code refactoring and it will soon be enabled by default. We recommend using LDAP.
