### ISSUE TITLE
Comment Mod

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#2917]
Hi, how to enabled or add comment to custom module?? and Document?.. i am use vtiger and need to enable this options to have a complete migration..

thanks!

**Comment by skramanzia** [comment]
I am use this..

INSERT INTO `yeti_demo`.`vtiger_fieldmodulerel` (`fieldid`, `module`, `relmodule`, `status`, `sequence`) VALUES ('601', 'ModComments', '**MODULE_NAME**', NULL, NULL);

**Comment by rskrzypczak** [comment]
At the moment there's no option to add comments to modules at the CRM level, but what you did is enough to make the comments work in a given module.
This functionality has a low priority and we don't know when or if it's going to be added.

Adding relation with document is possible at the CRM level.
Steps:
- in config\developer.php change value of CHANGE_RELATIONS to true
![addeddocumentrelations](https://cloud.githubusercontent.com/assets/10221999/14882232/d60baa56-0d37-11e6-93b0-8ea1d553c96d.gif)
