### ISSUE TITLE
breadcrumbs home link goes to webroot, not crm root

### ISSUE THREAD

**Issue by averied** [YetiForceCompany/YetiForceCRM#2918]
For example if you install Yetiforce in a subfolder of your webroot, When I click the home link in the breadcrumbs it links to the webroot

if my CRM home is http://myhost/crm/index.php, the home link goes to myhost

![image](https://cloud.githubusercontent.com/assets/10140930/14871042/c59f44b8-0cd6-11e6-84b3-4399e082147f.png)

**Comment by bpabiszczak** [comment]
please check config/config.inc.php 

// backslash is required at the end of URL
$site_URL = '_SITE_URL_';
// root directory path
$root_directory = '_VT_ROOTDIR_';
