### ISSUE TITLE
browser Iceweasel 38.7.1 menu overflow issue

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#2919]
Left menu not show, maybe overflow issue in twilight/style.css

![schermata da 2016-04-28 11 38 17](https://cloud.githubusercontent.com/assets/18703633/14881878/4aead786-0d36-11e6-9e16-e67dbc264ab3.png)

**Comment by kabelo38** [comment]
Any progress on this issue? it works well on chrome the problem is on Firefox

**Comment by bpabiszczak** [comment]
1. Please check the latest versions.
2. Clear the cache in the browser or use the incognito mode.

**Comment by cadre15** [comment]
I am using the latest version (3.1) of Yeti and this problem still exist when using firefox

**Comment by cadre15** [comment]
Chrome works perfectly though
