### ISSUE TITLE
Wydruk dokumentów

### ISSUE THREAD

**Issue by slawhodu** [YetiForceCompany/YetiForceCRM#2920]
witam,
czy można wydrukować dokumenty magazynowe? Jak?

**Comment by bpabiszczak** [comment]
Musi być dla danego modułu aktywny szablon i spełnione warunki w nim ustawione [wszystko z panelu tutaj: https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35].

**Comment by slawhodu** [comment]
Mam ustawiony szablon, ale nie wiem jak wydrukować.
Szablon przypięty i na listę i na wydruk.
Na bazie z linka nie mam możliwości dodania nowego dokumentu (w moim przypadku przyjęcia)
