### ISSUE TITLE
Customer Portal Login details don't work

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2921]
Hi,

I have set up the |Customer Portal version 3, and it correctly sends the login details, however, when I try to log in, it doesn't do anything - just resets itself. 

I have activated the Triggers in the CRM, and have removed the // from config/api.php file. I have also added the portal url to the CRM config-inc.php and added the CRM path to the portal config.php file. 

Is there another step I have overlooked?

Percy

**Comment by bpabiszczak** [comment]
logs?

**Comment by PercyP** [comment]
Hi,

my apologies, what do you mean by logs?

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html

**Comment by bpabiszczak** [comment]
Install instruction: https://yetiforce.com/en/implementer/installation-updates/129-customer-portal-instalation.html

**Comment by mariuszkrzaczkowski** [comment]
I tested generating portal access, sending data via email, logging into the portal and everything works just fine. Please give us some more details, like error logs, video or your configuration and how you create the access. 
Test version of the portal can be found here: https://gitdeveloper.yetiforce.com/portal
Make sure you turned on the workflow:
"Generate customer login details" and "Send customer login details"
![triggers](https://cloud.githubusercontent.com/assets/10198654/14914923/d13e9e84-0e0e-11e6-89e9-c162e70db7de.png)

**Comment by PercyP** [comment]
My apologies for delay responding (thanks for replying). I am still working through your suggestions to fix. I am sure the problem is my end and incorrect settings. Everything works in terms of setting up portal user, and I do receive the email with login details, I just cannot log in. I tried logging in to the email on yetiforce, and it doesn't like it - I get a message saying 

Connection to storage server failed

So I am just working through your debug link which you kindly sent. 

I will post back if I can identify the issue and potential solution in case others have the same issue.

**Comment by PercyP** [comment]
Hi bpabiszczak,

as promised, I finally got it working :)  so posting the solution in case others have same issue.

My problem was because my installation is on shared hosting. It required different values for both the mail settings, and in the config files for the crm and portal. 

In the mail settings I had to use the following:

1. Mail Server settings (SMTP) - mail123.mysite.co.uk
2. Name of IMAP server - mail123.mysite.co.uk
3. Port used to connect to IMAP - 587 to replace 933 and 143 to place the other setting near the bottom of roundcube configuration
4. Name of SMTP server - mail123.mysite.co.uk

Then, in the config.inc.php It needed the secure web address which was:

$PORTAL_URL = 'https://web56.secure-secure.co.uk/mysite.com/portal/';

And in the portal/config/config.php it was

$vtiger_path = "https://web56.secure-secure.co.uk/mysite.com/yetiforce/";

I tried installing on a Virtual Private Server and the settings provided by yetiforce work exactly as specified, it seems shared hosting has to be done differently - in my case at least. 

Now works beautifully!

Thanks for your guidance

Percy

**Comment by drakub** [comment]
> 
> 
> Hi,
> 
> I have set up the |Customer Portal version 3, and it correctly sends the login details, however, when I try to log in, it doesn't do anything - just resets itself.
> 
> I have activated the Triggers in the CRM, and have removed the // from config/api.php file. I have also added the portal url to the CRM config-inc.php and added the CRM path to the portal config.php file.
> 
> Is there another step I have overlooked?
> 
> Percy

Can you show me how you did this in a step by step way? I am just starting and I needed to also configure my portal
