### ISSUE TITLE
email To field empty when clicking on contact's primary email 

### ISSUE THREAD

**Issue by averied** [YetiForceCompany/YetiForceCRM#2922]
When I open a contact's card, I can click on the primary email field that is in the Summary tab. RoundCube opens correctly, but the "To" field is not filled with the contact's email address.

Additionally:
- the contacts, accounts, leads, etc. buttons are not working when calling roundcube this way, nor the attach file from crm
- The "close" link on the top right corner doesn't work, cancel button does nothing
- The YetiForce menu is not available in this mode. There isn't a clean way to return to the main menu
- Maybe the idea was to open roundcube in a new browser window, but it's opened in the same active tab after clicking the contact's primary email

Finally I need to do some more testing, but I've not been able to get the mails sent to the contact under the "corporate emails" tab, neither in the summary view "email" widget of the contact. Cron jobs are running and  user's mail scanner configuration has the "relate with contacts" enabled.

Using version  [ver. 3.0.36] for testing purposes.

Thanks.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
have you also verified it on our testing version at gitdeveloper.yetiforce.com? 
We don't understand all of the points that you listed. Maybe you could make a video or attach screenshots?
