### ISSUE TITLE
How to update Actual sale, Balance and so on

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#2923]
i found several fields such as Actual sale\ balance\ payment balance
and seems no rule to update these fields automatic?
is there will be function to do this in future ?
or we can only do this by ourselves like make a enhancement

**Comment by paula-w** [comment]
Part of these fields will be definitely improved in 3.1, because we are going to optimize processes in 3.1 (release dates and milestones: https://github.com/YetiForceCompany/YetiForceCRM/milestones)

**Comment by zelphar** [comment]
now is 4.2, but seems these fields are still not working.
wondering why?

**Comment by KatarzynaUlichnowska** [comment]
At the moment, we aren't planning to change these fields. We will organize the processes when optimizing them. Currently, it is common that fields are changed manually to suit customer requirements and it often happens during the integration with ERP systems. 
In the future, everything will be automated, but we don't know the date, so there is no point in keeping this issue open. If someone wants to have a field automatically calculated, it usually needs to be adjusted by a developer.
