### ISSUE TITLE
Office365 EMail Account

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#2924]
Hello together,

in vtiger we were able to send an email with

server: tls://smtp.office365.com:587
user & pw

it fails when i try it with yetiforce.
Does anyone know how to configure it with yetiforce?

It is working with my personal gmail account but not with office365 what we need.

Best Regards,
Ralph

**Comment by paula-w** [comment]
Can you create a test account for us, and send us the login info? We will check it.

**Comment by networkpanic** [comment]
test account is created, send the logindetails to help@yetiforce

**Comment by paula-w** [comment]
Can you send the details again? We didn't receive them

**Comment by acidhunter** [comment]
0o okay

**Comment by acidhunter** [comment]
help@yetiforce.com, right?

**Comment by acidhunter** [comment]
sent it again, did u recieve the mail?

**Comment by paula-w** [comment]
We got it now, thanks. We're looking into your issue.

**Comment by mariuszkrzaczkowski** [comment]
Incorrect email address im confid.inc.php file $HELPDESK_SUPPORT_EMAIL_ID 
I changed it to the one from SMTP configuration and it's working now.
