### ISSUE TITLE
Custom Module Actions "Mass Edit"

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#2926]
Hi Team!!

I  made a Custom Module, but dont have action "Mass Edit". I try to modify Roles, etc.. only work "mass edit" in "Administrator" Role.

![image](https://cloud.githubusercontent.com/assets/3030997/14918823/3f89f05e-0dfc-11e6-94e2-10c9f83e1f5a.png)

In Profile dont have "mass edit" Check box.

![image](https://cloud.githubusercontent.com/assets/3030997/14918863/62942e52-0dfc-11e6-9363-b48494ab5475.png)

Thanks 4 all!!

**Comment by paula-w** [comment]
Hi.
The fact that you see these 4 actions is a security error we inherited from vtiger. You shouldn't see anything that was added to the profile at the script level.

**Comment by skramanzia** [comment]
Hi Paula,
Is there any way to enable "edit mass"?

**Comment by mariuszkrzaczkowski** [comment]
I corrected the creation of modules should now work correctly. Create a module, or call the function enableTools

**Comment by skramanzia** [comment]
I changed that to fix it.. but doesn't work

![image](https://cloud.githubusercontent.com/assets/3030997/15019616/1eb3e87e-11f5-11e6-8e6a-ac370fc8f1bc.png)

After change:

![image](https://cloud.githubusercontent.com/assets/3030997/15019680/5fb3ae5e-11f5-11e6-8af6-e1cf73aded1e.png)

**Comment by skramanzia** [comment]
I checked and work only from New Module.. Can i enable in current custom module? sorry, but i dont know how to call functions. :(

**Comment by mariuszkrzaczkowski** [comment]
try this
```php
		$module = new Vtiger_Module();
		$moduleInstance = $module->getInstance('ModuleName');
		$moduleInstance->enableTools(['Import', 'Export', 'DuplicatesHandling', 'CreateCustomFilter',
			'DuplicateRecord', 'MassEdit', 'MassDelete', 'MassAddComment', 'MassTransferOwnership',
			'ReadRecord', 'WorkflowTrigger', 'Dashboard', 'CreateDashboardFilter',
			'QuickExportToExcel', 'TagCloud', 'DetailTransferOwnership', 'ExportPdf',
			'RecordMapping', 'RecordMappingList', 'FavoriteRecords', 'WatchingRecords',
			'WatchingModule', 'RemoveRelation']);
```

**Comment by skramanzia** [comment]
Thanks!, It Worked!... Only needed add "require_once" on the first line.

`require_once 'vtlib/Vtiger/Module.php';
   $module = new Vtiger_Module();
        $moduleInstance = $module->getInstance('ModuleName');
        $moduleInstance->enableTools(['Import', 'Export', 'DuplicatesHandling', 'CreateCustomFilter',
            'DuplicateRecord', 'MassEdit', 'MassDelete', 'MassAddComment', 'MassTransferOwnership',
            'ReadRecord', 'WorkflowTrigger', 'Dashboard', 'CreateDashboardFilter',
            'QuickExportToExcel', 'TagCloud', 'DetailTransferOwnership', 'ExportPdf',
            'RecordMapping', 'RecordMappingList', 'FavoriteRecords', 'WatchingRecords',
            'WatchingModule', 'RemoveRelation']);`
