### ISSUE TITLE
Customer Portal Themes

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2929]
Hi,

this is a question - not an issue. Has the Customer Portal been changed much from the Vtiger version? 

Why I ask, is I would like to use one of www.makeyourcloud.com themes as it matches the style of your new yetiforcecrm and is very slick. 

Do you plan to produce and sell your own themes? I just want to have a dark them that matches your crm.

Kind regards

Percy

**Comment by bpabiszczak** [comment]
1. You can check here: https://gitdeveloper.yetiforce.com/portal/
2. Do you plan to produce and sell your own themes? now not, maybe in the future.

**Comment by PercyP** [comment]
Many thanks, look forward to seeing some themes in the store in the future.

Percy
