### ISSUE TITLE
Email enhancement - Lovely skins for the Yetiforce email

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2931]
Hi,

for anyone interested, if you would like an alternative look for the yetiforce email (which uses Roundcube) then there is a lovely free skin called Litecube. The free version for desktop works beautifully (I have just installed it) and it looks more like Microsoft outlook. 

You can find it here:

http://roundcubeskins.net/

Kind regards

Percy

**Comment by bpabiszczak** [comment]
Free only for personal use. All the other skins are available under the commercial license only.
