### ISSUE TITLE
Advanced workflow for YetiforceCRM?

### ISSUE THREAD

**Issue by sol2014** [YetiForceCompany/YetiForceCRM#2932]
Is there an advanced workflow creator like this one -> https://shop.stefanwarnat.de/vtiger-workflow-designer/ and if not, would it work for Yetiforce CRM?

Reason for me asking is that I wanted to create a workflow where once the ticket is set to a specific status such as 'Closed' then an invoice would automatically be generated for that ticket. There's only a few entities that we can create with the basic version

**Comment by bpabiszczak** [comment]
The best tool in the world: https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=List&block=15&fieldid=24

**Comment by sol2014** [comment]
Actually, I've tried but this workflow is the same as vTiger, it ONLY allows the creation of specific entities like --> Comments, Passwords, Call History, Reservations. You can check it out and see what I mean by following the steps below:

Create Workflow: Select Module: Tickets
Name it: Test
Specify when to execute this workflow: Only once, when all conditions are met.
Click 'Next'
All Conditions: Status is Closed
Click 'Next'
Add To Do: Create Entity: (You will only see 4 entity creation possibilities.) The Invoice entity option is not there.

**Comment by bpabiszczak** [comment]
You need to practice more. Workflow can do more than you think.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/2928

**Comment by sol2014** [comment]
You said I "need to practice" but I also see that it was added to 3.1 milestone. Does this mean the capability is not there or is there but I'm just not seeing it? I have a test of another system and that's the steps I took to create the same workflow.

**Comment by paula-w** [comment]
Hi.
Labelling it as "milestone 3.1" only means when the issue will be closed. 
As far as workflow is concerned - it's a very powerful tool, and it indeed needs some practice to master it. Everything that's missing can be added using special functions, that can be executed in workflow, and that can do pretty much whatever you want.
