### ISSUE TITLE
Where is the favicon stored?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2933]
Hi,

can you tell me where the favicon is stored?

Kind regards

Percy

**Comment by acidhunter** [comment]
/layouts/basic/skins/images/favicon.ico

**Comment by PercyP** [comment]
Hi acidhunter,

I don't have one in that location. I have checked as many image folders as I can but cannot find it.

**Comment by acidhunter** [comment]
in version 3.0 the file is @ /layouts/basic/skins/images/favicon.ico
are u on the latest version?

**Comment by acidhunter** [comment]
on unix based systems u can use locate to find the favicon
locate favicon.ico | grep /var/www

point grep to the location where your yetiforce setup is located

**Comment by PercyP** [comment]
Hi, thanks for getting back.

Yes I am on latest version. I am on shared hosting, so I don't have access to anywhere that I could use grep to find the file. I am assuming it is stored in a different location on my hosting. I uploaded a test favicon.ico to the original location you suggested but it has no effect, so i am guessing its stored somewhere else on shared hosting.

**Comment by PercyP** [comment]
Aha! you were correct in your first answer, it just wasn't in that location so I added it, and it appeared after I cleared my browser cache. 

Thanks for your help.

**Comment by acidhunter** [comment]
u are welcome ;-)
