### ISSUE TITLE
[Question 3.0] PDF background Image

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2938]
How can I set a background image for the PDF template for Quotes? We have a pre-designed form that we want to use with letterhead and images. I don't see an option for background image.  Should I set it in source?

**Comment by zimart** [comment]
Manual - mPdf

**Comment by mykljohn** [comment]
cheers, checking now.

**Comment by bpabiszczak** [comment]
Use pdf editor: https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35
