### ISSUE TITLE
Issue in german calendar translation

### ISSUE THREAD

**Issue by acidhunter** [YetiForceCompany/YetiForceCRM#2940]
![image](https://cloud.githubusercontent.com/assets/8077558/14988711/630392ea-1155-11e6-9af7-04a3eea8659c.png)

The Days are in wrong order, should be Mo, Di, Mi, Do, Fr, Sa, So
DI and Do are wrong ;-)

**Comment by acidhunter** [comment]
3.0 stable is our version

**Comment by SkavenKF** [comment]
Ups, kleiner Fehler beim Übersetzen passiert :-) Hab die Stelle auch schon gefunden ....

I will fix it.

**Comment by acidhunter** [comment]
thanks you :-)

**Comment by SkavenKF** [comment]
fixed in developer:
https://github.com/YetiForceCompany/YetiForceCRM/commit/bfc7ed3c8d57f1579887fd988e12910a2f7ce9b2
