### ISSUE TITLE
Add todo or event from tab Activities of related module - javascript error

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#2943]
tested on gitstable.yetiforce.com:

1) create project
2) open project
3) open tab Activities
4) Click on "add to do" or "add event" and save
5) error on variable hiddenDays = null in layout/basic/modules/Vtiger/resources/header.js

no error on gitdeveloper.yetiforce.com/
but after save "to do" if click another time on "add to do" i see two activity created

**Comment by rskrzypczak** [comment]
related: https://github.com/YetiForceCompany/YetiForceCRM/issues/2963 https://github.com/YetiForceCompany/YetiForceCRM/issues/2965 https://github.com/YetiForceCompany/YetiForceCRM/issues/2964

Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/01fe6c099e78cbf502cdcc0ebf03a3e998e70641
