### ISSUE TITLE
Add module fields on SMS Task Workflow

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#2944]
tested on: https://gitdeveloper.yetiforce.com

not add module fileds to sms text area on SMS task on Workflow.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
you provided too little information and we are not sure what you want. 
Did you mean that we should add an enhancement? Or did you want to submit a bug?

**Comment by nic86** [comment]
![gifrecord_2016-06-10_114401](https://cloud.githubusercontent.com/assets/18703633/15960648/16907b52-2f01-11e6-8be3-36fb4bd8d975.gif)
