### ISSUE TITLE
Import of line items are broken for all modules

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2945]
Today I prepared a lot of data for importing to my 3.0.0 crm. But I was stopped because there is no possibility to import item lines to Sales and Logistics modules:
IDN import
![image](https://cloud.githubusercontent.com/assets/8545791/15016651/dcdbe0a2-121a-11e6-8624-aff36aff6079.png)
Quotes import
![image](https://cloud.githubusercontent.com/assets/8545791/15016677/f90555f6-121a-11e6-82c1-22870f2781a6.png)
The same situation with import at dev 3.0.58

**Comment by rskrzypczak** [comment]
Hello,
Line items can be imported. You probably didn't export it properly. Quite correct import is only possible from xml format, so it should also be exported to that format.
![import2](https://cloud.githubusercontent.com/assets/10221999/15038505/8efbfb6c-12a4-11e6-83f9-44875c545b7e.gif)
Small hint:
For a user whose language is the same while exporting and importing, the fields in mapping will be automatically set.

**Comment by vovpff** [comment]
What about CSV?

**Comment by paula-w** [comment]
Hi. 
Right now transferring data is only supported using XML.
Import and export to XML will be the first thing we are going to develop. CSV is not really a priority for us.
