### ISSUE TITLE
Nowy moduł - pole typu DropDownList

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2948]
Chciałbym zrobić w nowym module pole w którym w DDL będą widoczne wszystkie np. Produkty Obce.
Jakie powinno być uitype takiego pola?
Jak wrzucić tam te dane? Normalnie wyselectować i podpiąć do zmiennej?
Szukałem w dokumentacji Vtigera, ale takiego uitype nie znalazłem... Może takiego nie ma? :)

**Comment by bpabiszczak** [comment]
aby coś było, musi mieć biznesowe uzasadnienie... do czego ma to służyć aby zrozumiał cel, wtedy dam informacje zwrotną jak można coś takiego rozwiązać.

**Comment by amdziak** [comment]
Do czego dokładnie ma to służyć:
Potrzebuję bardzo prostego modułu do przenoszenia produktów między magazynami.
Dwa pola z listami magazynów + pole z nazwą produktu + pole z ilością produktów.
Samą logikę (gdzie insert, update, delete) mam ogarniętą, brakuje mi tylko informacji jakie uitype ma posiadać pole  z lista Magazynów.
Wiem, że taki proces biznesowy istnieje w YetiForce, ale jest za długotrwały :)
Dlatego potrzebuje takiego prostego modułu :)
Potem oczywiście, jeśli będziecie chcieli bardzo chętnie się nim podzielę :)

**Comment by bpabiszczak** [comment]
ale po co Ci to, skoro produkty między magazynami przenosi się za pomocą dokumentów tj. Magazyn przyjął i Magazyn wydał.

**Comment by amdziak** [comment]
wiem, ale potrzebuje tego do zupełnie innych celów.
Pomijając cel biznesowy.
W jaki sposób stworzyć takie pole?

**Comment by bpabiszczak** [comment]
rozumiem, że chcesz mieć multiselect z pełną lista produktów czy zwykly select?

**Comment by amdziak** [comment]
Zwykły select - tylko jedna rzecz do zaznaczenia.

**Comment by bpabiszczak** [comment]
to najlepiej dodać sobie z panelu pole uitype10 które ma lupkę i możemy produkt wybrać z pełnej listy...

**Comment by amdziak** [comment]
a programistycznie gdybym chciał to zrobić?
W sensie jak przy tworzeniu nowego pola o uitype = 10, wskazać odrazu że w tym polu mają być wszystkie produkty?

**Comment by bpabiszczak** [comment]
Przy tworzeniu pola uitype wskazujemy z jakim modułem jest powiązany, jak powiążemy go z produktami to pod lupką będą wszystkie produkty. Zobacz sobie tutaj: https://gitdeveloper.yetiforce.com/index.php?module=HelpDesk&view=Edit jak działa pole product name...

**Comment by amdziak** [comment]
Rozumiem to doskonale :)
chodzi mi jednak o fakt, gdy tworzę nowy moduł z vtliba i tam chciałbym odrazu okreslić do jakiego modułu pole ma być powiązane - można coś takiego zrobić?

**Comment by bpabiszczak** [comment]
Tak, poszukaj w Google np.: 
1. https://discussions.vtiger.com/index.php?p=/discussion/171378/how-to-create-ui-type-10-field-for-any-module-/p1
2. https://forums.vtiger.com/index.php?p=/discussion/comment/1185144

**Comment by amdziak** [comment]
Super - bardzo dziękuję za informację! :)
