### ISSUE TITLE
Feature: Full Recurrent Events

### ISSUE THREAD

**Issue by playmono** [YetiForceCompany/YetiForceCRM#2951]
Hi YetiForce team,

Would be great as a feature,   having full recurrent events. What I mean for full recurrent events? Today we cant:

-Change name of event massively to all my recurrent events.
-Delete massively all my recurrent events.
-We can change dates, but "old" recurrent events remains in the system.

References: http://code.vtiger.com/vtiger/vtigercrm/issues/8#note_1230

Maybe would be great, analyse how Gmail Calendar works and try to implement all of their functions.

**Comment by bpabiszczak** [comment]
4.0.0
