### ISSUE TITLE
Import.... 2.3.49

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2952]
Witam, czy mogę w jakis sposób zmusić system, aby przy próbie importu z np.. Vtigera... nie gubil mi rekordów o np. tym samym temacie.. - troszkę walczyłem ale jednak potrzebuję pomocy - czy jest szansa na to...żeby zrobić import bez żadnych kryteriów (rekord po rekordzie... - wiem że domyślnie wspieranie kryteriów importu jest wyłaczone...) mam dużo ofert o np tym samym temacie - no i lipa...

**Comment by bpabiszczak** [comment]
Jeszcze raz ale tym razem po polsku. Po kolei opisz co robisz jak robisz i czym robisz.

**Comment by zimart** [comment]
Po kolei : potrzebuję zaimportować rekordy - dokładniej oferty i zamówienia z Vtigera do Yeti. Przy próbie importu do czystej wersji 2.3.49 ( aby pózniej importowac do Yeti 3) mam problem z brakiem rekordów po imporcie - a dokładniej tych w których temat jest taki sam. Z produktami i kontrahentami nie zauważyłem problemów. W imporcie ofert i zamówień w 2.3.49 i zauważyłem że w poprzedniej także domyślnie zaawansowane funkcje importu są wyłączone. Tak więc potrzebuję w mojej ocenie wyłączyć domyślne ustawienia  konfiguracji importu ( pomija mi rekordy o takim samym temacie) - lub może jest jakiś inny sposób szybkiego importu. Inaczej pozostaje mi na piechotę zmiana tematów ofert w Vtigerze - i dopiero import ( przyznam że trochę niewygodne - powiedzmy ze do przejrzenia z 2000 ofert i tyle samo zamówień).

**Comment by zimart** [comment]
Po kilku próbach.. uważam .. że problem raczej tkwi w Vtigerze - w eksporcie... tak wiec myślę że można zamknąć temat .. ps.. w pliku szablonu exportu do XML- a po update 2,3.49 jest mały błąd - nie importuje pola komentarza .. linia 385 w pliku ExportToXml.php - inna nazwa tabeli ( comment1)
