### ISSUE TITLE
Yetiforce consumer portal username and password creation problem

### ISSUE THREAD

**Issue by logixbytes** [YetiForceCompany/YetiForceCRM#2953]
Hi,

I have installed YETIFORCE and Connected CONSUMER PORTAL also. Everything is working, even sending emails etc inside YETIFORCE. But i am not to get PORTAL Username and password email to the accounts. 

I have been trying this since last one week, can anyone help me here please.

Warm Regards,

Venkatesha

**Comment by konadrian** [comment]
Did you set correct path to the portal in config.inc file. $PORTAL_U variable

**Comment by logixbytes** [comment]
Hi,

Yes. I have done that. $PORTAL_URL is configured. 

I have installed the CRM & PORTAL as given below:
/public_html
/public_html/crm -> YETIFORCE CRM
/public_html/portal -> YETIFORCE CUSTOMER PORTAL

Can you help me this work has been stuck since last 10 days.

Warm Regards,

Venkatesha

**Comment by PercyP** [comment]
I had issues too connecting to portal. My problems was I was on shared hosting. Here is how I resolved it - you need to enable ssl on your hosting account - under extend control panel select the ssl under e-commerce, then use the urls it gives you for your config and portal details as per my post:

https://github.com/YetiForceCompany/YetiForceCRM/issues/2921

Percy
