### ISSUE TITLE
multi select combobox permission issue?

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#2955]
On an upgraded 3.0 site I can not edit the multiselect combobox (only tested in contacts).
You can create a new record, then add items to it and save but when returning for editing it is not possible to change the selection again.
I have seen the same behaviour on your gitmaster demo.
Is this a bug or a feature that needs enabling somewhere?
When doing a 'mass edit' I can change the values but not in individual edits.

How to test:
Go to the admin and create a multi select combobox in contacts, add some values.
Go contacts, create a new contact and select some values in the test box. THis works
Save and go back to edit mode and see that you are unable to change the previous selections.

All test done as admin.
v 3.0
php 5.6 with mysql

PS this issues does not occur in the dev demo version, but can't see a patch for it.

**Comment by ldgbc** [comment]
This bug can be found on v3.4 still. I used the "Multi-box" in Employee and now it bugged permanently. 
I tried using Module Editor to delete the field but is unable to. Not sure how I can fix it manually, was hoping that by Disable/Enable the Employee module it will reset the preference or something but that did not work.

To replicate I tried using https://gitstable.yetiforce.com/ and see if it just my system or it Yetiforce issue.

1. https://gitstable.yetiforce.com/ and log in
2. https://gitstable.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=OSSEmployees
3. Add Custom Field > Multi-select combo > add field, label and option.
4. Click save.
5. Bug occur, cannot edit/delete the Multi-select. 
6. https://gitstable.yetiforce.com/index.php?module=OSSEmployees&view=Edit Opening this page will show: 
"Fatal error: Call to a member function fetchColumn() on boolean in /home/gitstable/domains/gitstable.yetiforce.com/public_html/include/database/PearDatabase.php on line 266"
