### ISSUE TITLE
PDF - zawartość pola komentarza

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#2957]
Witam, czy ktoś może pomóc poprawić funkcję wydruku tabeli (ProductTable) - aby pobierało komentarz do pozycji artykułu do wydruku ? - widzę że w wersji developerskiej PDF nie działa na ten moment  - dlatego nie potestujemy.
`
 foreach ($inventoryRows as $key => &$inventoryRow) {
				$rowNo = $key + 1;
				$html .= '<tr>';
				foreach ($fields[1] as $field) {
					if ($field->isVisible($inventoryRows)) {
						$itemValue = $inventoryRow[$field->get('columnname')];

						$html .= '<td style="font-weight:normal;font-size:13px;padding-top:4px;padding-bottom:4px;" ' . ($field->getName() == 'Name' ? 'width="45%;" ' : '') . ' class="' . (in_array($field->getName(), $fieldsTextAlignRight) ? 'textAlignRight ' : '') . 'tBorder">';
						switch ($field->getTemplateName('DetailView', $module)) {
							case 'DetailViewName.tpl':
								$html .= '' . $field->getDisplayValue($itemValue) . '';
								if (isset($fields[2]['comment' . $rowNo])) {
									$COMMENT_FIELD = $fields[2]['comment' . $rowNo];
									$html .= `'<br/>'` . $COMMENT_FIELD->getDisplayValue($inventoryRow[$COMMENT_FIELD->get('columnname')]);
								}
								break;

							case 'DetailViewBase.tpl':
								$html .= $field->getDisplayValue($itemValue);
								break;
						}
						$html .= '</td>';
					}
				}
				$html .= '</tr>';
			}
			$html .= '</tbody>
					<tfoot>
						<tr>';

`Dodam... że pobiera w pierwszej pozycji produktu... a dlaczego - nie bardzo wiem :) - bardzo proszę o pomoc ....

**Comment by zimart** [comment]
Nie uda sie tego poprawić ? :(

**Comment by bpabiszczak** [comment]
Wsparcie bezpłatne świadczymy w wolnych chwilach jak nie mamy obłożenia pracą...

**Comment by zimart** [comment]
:) hmm chętnie zapłacę - a miało być tak pięknie

**Comment by bpabiszczak** [comment]
Wsparcie płatne można kupić tutaj: https://shop.yetiforce.com/en/17-support

**Comment by zimart** [comment]
oj. tam :) to tylko poprawka funkcji - nie potrzebuję aż takiego - może na PRV - to tak czy inaczej pewnie zostanie poprawione :(
