### ISSUE TITLE
Critical Bug - Calendar records duplicated in recurring events

### ISSUE THREAD

**Issue by playmono** [YetiForceCompany/YetiForceCRM#2958]
Hi YetiForce team,

Create a Calendar Record with the following setup:
![2016-05-09_13h54_58](https://cloud.githubusercontent.com/assets/1773174/15112325/a91a250e-15ed-11e6-9d5d-695d862d464e.png)

and then save, 7 records are created like this:
![2016-05-09_13h57_18](https://cloud.githubusercontent.com/assets/1773174/15112367/fd02a876-15ed-11e6-8fe5-58b7d1c9c433.png)

Then, I edit this record and save again, and 6 more records are created:
![2016-05-09_14h00_23](https://cloud.githubusercontent.com/assets/1773174/15112420/699ce604-15ee-11e6-9e78-e63b1a8ef4e2.png)

This is related to #2951 . But I think this needs to be fixed ASAP.

**Comment by TomaszQr** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/2951
