### ISSUE TITLE
Bug z workflow dla zadań 

### ISSUE THREAD

**Issue by dkrakowski** [YetiForceCompany/YetiForceCRM#2962]
Stworzone obiegi informacji dla modułu zgłoszenia, na triger dodanie rekordu powodują błąd "Invalid reference specified for process" zarówno w pobranej wersji deweloperskiej jak i w demo na państwa stronie.

**Comment by bpabiszczak** [comment]
a więc zacznijmy od tego: https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/125-issues.html
