### ISSUE TITLE
Continous loading for event

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2963]
At ver.3.0.0 whet I try to add new event for account/contact at top of quick create popup always loading circle appears
![image](https://cloud.githubusercontent.com/assets/8545791/15145543/e2bb25de-16be-11e6-823b-83ff8b742978.png)
Installation are fresh

**Comment by vovpff** [comment]
![due date](https://cloud.githubusercontent.com/assets/8545791/15145763/342e235c-16c0-11e6-8dd4-94c277e3089e.gif)

**Comment by vovpff** [comment]
#2965

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/01fe6c099e78cbf502cdcc0ebf03a3e998e70641
