### ISSUE TITLE
End time of event

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2964]
At my user record standard duration for event is 30 minutes. If i try to add new event at quick qreate popup appears *Start date & time is now, end time is 30 minutes later than now. If i changed manually start time there is no automatically changes at end time. Is it correct?
![due date](https://cloud.githubusercontent.com/assets/8545791/15145758/2af171b8-16c0-11e6-8da8-9b8cdb56d9bf.gif)

**Comment by playmono** [comment]
Hi,

As I see, your javascript is very broken since all of your errors become to this. Can you press F12 before Save and post a screenshot with console errors?

**Comment by vovpff** [comment]
@playmono try this https://gitstable.yetiforce.com/

**Comment by vovpff** [comment]
@playmono what tab screenshot you need?

**Comment by vovpff** [comment]
![image](https://cloud.githubusercontent.com/assets/8545791/15148006/1ca99f66-16cc-11e6-8800-7a08d0d9105c.png)
![image](https://cloud.githubusercontent.com/assets/8545791/15148057/45ae4b28-16cc-11e6-80bf-d85fe36fce0d.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/01fe6c099e78cbf502cdcc0ebf03a3e998e70641

**Comment by vovpff** [comment]
What about auto end time according user settings?
