### ISSUE TITLE
After event creating

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2965]
ver. 3.0.0
After event creating there is appears index.php page with code for Chrome/IE try to save index.php file:

`{"success":true,"result":{"subject":{"value":"124","display_value":"124"},"reminder_time":{"value":"","display_value":""},"assigned_user_id":{"value":"1","display_value":"<a href=index.php?module=Users&parent=Settings&view=Detail&record=1>vov \u041f\u043e\u0442\u0430\u043f\u043e\u0432 \u0412.\u042e.<\/a>"},"date_start":{"value":"2016-05-10","display_value":"2016-05-10"},"time_start":{"value":"01:05:00","display_value":"01:05"},"time_end":{"value":"12:05:00","display_value":"12:05"},"shownerid":{"value":"","display_value":""},"due_date":{"value":"2016-05-10","display_value":"2016-05-10"},"recurringtype":{"value":"","display_value":""},"activitystatus":{"value":"PLL_OVERDUE","display_value":"Overdue"},"taskpriority":{"value":"Low","display_value":"Low"},"sendnotification":{"value":"","display_value":""},"modifiedtime":{"value":"2016-05-10 14:41:06","display_value":"10.05.2016 14:41"},"createdtime":{"value":"2016-05-10 14:41:06","display_value":"10.05.2016 14:41"},"created_user_id":{"value":"","display_value":""},"activitytype":{"value":"Meeting","display_value":"Meeting"},"visibility":{"value":"Private","display_value":"Private"},"duration_hours":{"display_value":"11","value":"11"},"was_read":{"value":"","display_value":""},"duration_minutes":{"value":"0","display_value":"0"},"state":{"value":"PLL_OPAQUE","display_value":"Busy"},"location":{"value":"","display_value":""},"notime":{"value":"","display_value":""},"modifiedby":{"value":"1","display_value":"vov \u041f\u043e\u0442\u0430\u043f\u043e\u0432 \u0412.\u042e."},"closedtime":{"value":"","display_value":"10.05.2016"},"allday":{"value":"0","display_value":"No"},"description":{"value":"","display_value":""},"link":{"value":"111","display_value":"<a class='moduleColor_Accounts' href='index.php?module=Accounts&view=Detail&record=111' title='Accounts'>UNKNOWN<\/a>"},"process":{"value":"","display_value":""},"subprocess":{"value":"","display_value":""},"followup":{"value":"","display_value":""},"_recordLabel":"124","_recordId":179602}}`

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/01fe6c099e78cbf502cdcc0ebf03a3e998e70641
