### ISSUE TITLE
[Problem/Question 3.0] Export 

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2967]
I installed the export update to my 2x version, but when I try to export it just goes to a blank screen.  

Does each record need to be in a separate file?  because when I exported 2 test quotes from 3.0 it created a zip file with 2 xml files in it, one for each quote.

I've converted the CSV file from 2x to XML and it the layout matches the export from 3.0, but in the import screen it repeats the fields in the extended block.

Is there any chance I can get the XML layout for the import to work in 3.0?  I have everything imported except our quotes and sales orders.  This would help me immensely.

**Comment by vovpff** [comment]
@mykljohn please made screenshot for this for better understanding

> I've converted the CSV file from 2x to XML and it the layout matches the export from 3.0, but in the import screen it repeats the fields in the extended block.
