### ISSUE TITLE
Improvement for advanced modules (example IDN)

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2968]
There are ability to add different types of field to product table. Very interesting field is Value. If you add it you can input any value for some purposes. For my target field EAN not needed but needed different  data from some product picklist as read-only.
Please made ability to relay read-only Value field to some field in Product module. Now this is possible to mabe manually in database by changing by this scripts:

`INSERT INTO `u_yf_iidn_invfield` (`id`, `columnname`, `label`, `invtype`, `presence`, `defaultvalue`, `sequence`, `block`, `displaytype`, `params`, `colspan`) VALUES (n, 'NAME', 'LABEL', 'Value', 0, '', m, 1, 10, NULL, 10);`

n - check last at u_yf_iidn_invfield table
m - check last at u_yf_iidn_invfield table

`INSERT INTO `u_yf_iidn_invmap` (`module`, `field`, `tofield`) VALUES ('Products', 'NAME at products table', 'NAME from previous code');`

**Comment by KatarzynaUlichnowska** [comment]
Hello,
we aren't currently planning to add this functionality. You can write it and then send it to us via a pull request (https://help.github.com/articles/using-pull-requests/), or you can order and pay us for adding it.
