### ISSUE TITLE
Index.php load time is very slow

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2969]
Hi,

I recently moved my shared hosting account to another, and have noticed that loading the Home page dashboard (first screen that comes up when you log in) is painfully slow. The widgets take forever to load. I have checked the logs section and applied any differences that are recommended in the settings to a php.ini file as follows:

max_execution_time = 600
memory_limit = 3000M
max_input_vars = 5000
output_buffering = On
max_input_time = 600
log_errors = Off
default_socket_timeout = 600 	
mysql.connect_timeout =	600
error_reporting = E_WARNING & E_ERROR & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT

When I look at the log section, it shows nothing under my php settings for error_reporting, default_socket_timeout and mysql.connection_timeout, but nor does it highlight in pink after I added them to php file. 

In Firefox console I see these errors after the dashboard finally loads:

unreachable code after return statement 
![errorfirefox](https://cloud.githubusercontent.com/assets/10598886/15179436/9cd1dd0a-1773-11e6-95fa-c1124c0f72d8.png)

I can't test this on yetiforce.com as there are no widgets to load on the dashboard.

Is this a file settings issue?

Percy

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/implementer/optimization/102-mysql-optimization.html
2. https://yetiforce.com/en/developer-documentation/bugs/126-issues.html 
3. https://gitdeveloper.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67
