### ISSUE TITLE
[Bug] Sharing Calendar Sharing Rules doesnt works

### ISSUE THREAD

**Issue by playmono** [YetiForceCompany/YetiForceCRM#2970]
This dont works.
![2016-05-11_14h55_56](https://cloud.githubusercontent.com/assets/1773174/15181621/8e138d8a-1788-11e6-8e0d-e30afc2d9bc5.png)

You can try it at: https://gitstable.yetiforce.com/

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/bugs/126-issues.html

**Comment by playmono** [comment]
Ok, "dont works" for me means that:

Result I expected: If I create to dos / events with Production Department, I should see them with users belonging Marketing Department.
What actually happens: When I log with an user from Marketing Department I cant see any records beloging Production Department in Calendar grill.

**Comment by paula-w** [comment]
Could you record a short clip on the dev version and show us the configuration?  It would be very helpful.

**Comment by vovpff** [comment]
@paula-w 
![rules bug](https://cloud.githubusercontent.com/assets/8545791/16558387/0a66c836-41ee-11e6-99d5-d27df8a17a5a.gif)

**Comment by bpabiszczak** [comment]
Please check role.

**Comment by vovpff** [comment]
@bpabiszczak you mean hierarchy?

**Comment by bpabiszczak** [comment]
![calendar](https://cloud.githubusercontent.com/assets/10197525/16563977/5e2cd250-4205-11e6-9c20-a8db8d89e5ec.png)
