### ISSUE TITLE
Help needed with autocommenting

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2971]
How to made automatically comments by some rule? My target example: when state of activity changed to Completed system automatically post comment contained activity description to activity related Contact/Account by activity Assigned user.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
why would you need it? Could you elaborate?

**Comment by vovpff** [comment]
@KatarzynaUlichnowska This is needed for checking of CRM user activity with customer (Account/Contact).

**Comment by KatarzynaUlichnowska** [comment]
There is a module in our shop that is designed to present user activity: https://shop.yetiforce.com/en/products/11-analyzer.html
Additionally, in the new version, when a user changes something, the info is visible in record view.

**Comment by vovpff** [comment]
@KatarzynaUlichnowska is it possible to try demo of analyser?

**Comment by KatarzynaUlichnowska** [comment]
Of course, I've just sent you an email with access data to our demo. Enjoy!
