### ISSUE TITLE
[PL] Połączenie kalendarza z nowym modułem.

### ISSUE THREAD

**Issue by pkacprzyk** [YetiForceCompany/YetiForceCRM#2972]
Witam
Ktoś wie jak połączyć kalendarz z nowo utworzonym modułem?

Pozdrawiam

**Comment by bpabiszczak** [comment]
Ja wiem! Należy to zaprogramować:D 
A tak poważniej, to wiele zmian w wielu miejscach, wątpię czy ktoś tu napiszę coś gotowego do użycia, trzeba być programistą a programista sobie z tym poradzi.

**Comment by pkacprzyk** [comment]
Dodałem wpis do vtiger_fieldmodulerel i vtiger_relatedlists. Niestety w podsumowaniu projektu kalendarz jest, ale nie chcę się załadować. Będę próbował dalej. Dzięki za odpowiedź :+1:

**Comment by bpabiszczak** [comment]
Chyba nie rozumiesz problemu, jeżeli dodasz coś w jednym miejscu a nie dodasz w dziesięciu innych to przestanie działać np.:

1. Pasek integracyjny w poczcie.
2. Integracja z CalDAV
3. Zakładki powiązane
itd. 

Aby cokolwiek zmieniać w systemie od strony kodu trzeba być programistą i być świadomy tego co się robi.
