### ISSUE TITLE
Okno powiązanych produktów/usług - dodanie pola

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#2975]
Chciałbym zmienić jedno z pól w poniższym module na inne - jak to zrobić, chodzi mi głównie o jakieś nakierowanie na plik/linię kodu, gdzie można zacząć cokolwiek analizować...
Szukałem w Products.php, ale nic nie znalazłem...
![zrzut ekranu 2016-05-12 o 13 15 03](https://cloud.githubusercontent.com/assets/11409255/15212910/e77add5e-1843-11e6-81f1-70737fc9d64c.png)

**Comment by bpabiszczak** [comment]
Tym zarządza się z poziomu edytora pól [zarządzanie blokiem zaawansowanym]. Jeżeli panel nie będzie wystarczający, to wówczas trzeba być programistą.

**Comment by rskrzypczak** [comment]
Ogólnie w chwili obecnej nie ma możliwości ustawienie tego co wydaje mi się, że chcesz z poziomu CRM.
Zwróć jednak uwagę na tablicę u_yf_NAZWAMODUŁU_invmap (np. u_yf_finvoice_invmap) w niej są mapowane pola.
