### ISSUE TITLE
Update Stable Question.

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#2976]
Hi all!, can i update to the latest stable version?, can i use this Yeti menu?

![image](https://cloud.githubusercontent.com/assets/3030997/15221871/9a4cb4e4-1843-11e6-847b-7fc676599898.png)

My Version is:
![image](https://cloud.githubusercontent.com/assets/3030997/15221914/c2c9707e-1843-11e6-8f40-240eec1a0e07.png)

Thanks!

**Comment by vovpff** [comment]
@skramanzia it seem you need special update package prepared by yetiforce crew. There is some update packages. Let's try to find them on sourceforge. Sorry, i dont know where you can find this update packages on github

**Comment by skramanzia** [comment]
In Sourceforge i can not find the "Update packaged", because the latest uploaded version date to 2016-04-18. it is not the latest.

![image](https://cloud.githubusercontent.com/assets/3030997/15226444/1a6e9a9c-1859-11e6-8790-079f7c9e7f97.png)

**Comment by vovpff** [comment]
@skramanzia you have last stable version now

**Comment by bpabiszczak** [comment]
● ● ● Roadmap ● ● ● 
YetiForce 3.1 [2016-05-31]
