### ISSUE TITLE
Calendar reports not able to use relation between contact and accounts

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2978]
This is my report (dev 3.0.134)
![image](https://cloud.githubusercontent.com/assets/8545791/15239587/822e61a6-18ec-11e6-8af2-4d475937e5c9.png)
Conditions
![image](https://cloud.githubusercontent.com/assets/8545791/15239607/a223bee8-18ec-11e6-81b9-20e02110be9a.png)
Report
![image](https://cloud.githubusercontent.com/assets/8545791/15239627/c9310018-18ec-11e6-9df7-0bf13eb4c571.png)
But I need to see account of contact in table. I added Member of field to column field
![image](https://cloud.githubusercontent.com/assets/8545791/15239672/15000796-18ed-11e6-87c0-9ecdb9d1c807.png)
This is result of report
LBL_SQL_ERROR
LBL_ERROR_MASAGE:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vtiger_leaddetailsRelContacts.company' in 'field list'`
LBL_SQL_QUERY:
`select DISTINCT vtiger_activity.subject AS 'Calendar__Subject', cast(concat(vtiger_activity.date_start,' ',vtiger_activity.time_start) as DATETIME) AS Calendar__Start__Date__and__Time, (CASE WHEN vtiger_activity.link NOT LIKE '' THEN (CASE WHEN trim(vtiger_accountRelCalendar.accountname) NOT LIKE '' THEN trim(vtiger_accountRelCalendar.accountname) WHEN trim(CONCAT(vtiger_contactdetailsCalendar.firstname,' ',vtiger_contactdetailsCalendar.lastname)) NOT LIKE '' THEN trim(CONCAT(vtiger_contactdetailsCalendar.firstname,' ',vtiger_contactdetailsCalendar.lastname)) WHEN trim(vtiger_leaddetailsRelCalendar.company) NOT LIKE '' THEN trim(vtiger_leaddetailsRelCalendar.company) WHEN trim(vtiger_vendorRelCalendar277.vendorname) NOT LIKE '' THEN trim(vtiger_vendorRelCalendar277.vendorname) WHEN trim(u_yf_partnersRelCalendar277.subject) NOT LIKE '' THEN trim(u_yf_partnersRelCalendar277.subject) WHEN trim(u_yf_competitionRelCalendar277.subject) NOT LIKE '' THEN trim(u_yf_competitionRelCalendar277.subject) WHEN trim(vtiger_ossemployeesRelCalendar277.last_name) NOT LIKE '' THEN trim(vtiger_ossemployeesRelCalendar277.last_name) ELSE '' END) ELSE '' END) AS 'Calendar__FL_RELATION', case when(vtiger_usersCalendar.last_name NOT LIKE '' and vtiger_crmentity.crmid!='' ) THEN CONCAT(vtiger_usersCalendar.last_name,' ',vtiger_usersCalendar.first_name) else vtiger_groupsCalendar.groupname end AS 'Calendar__Assigned__To', (CASE WHEN vtiger_contactdetails.parentid NOT LIKE '' THEN (CASE WHEN trim(vtiger_accountContacts.accountname) NOT LIKE '' THEN trim(vtiger_accountContacts.accountname) WHEN trim(vtiger_leaddetailsRelContacts.company) NOT LIKE '' THEN trim(vtiger_leaddetailsRelContacts.company) WHEN trim(vtiger_vendorRelContacts.vendorname) NOT LIKE '' THEN trim(vtiger_vendorRelContacts.vendorname) WHEN trim(u_yf_partnersRelContacts.subject) NOT LIKE '' THEN trim(u_yf_partnersRelContacts.subject) WHEN trim(u_yf_competitionRelContacts.subject) NOT LIKE '' THEN trim(u_yf_competitionRelContacts.subject) ELSE '' END) ELSE '' END) AS 'Contacts__Member__Of', vtiger_crmentity.crmid AS "Calendar__LBL_ACTION" from vtiger_activity inner join vtiger_crmentity on vtiger_crmentity.crmid=vtiger_activity.activityid left join vtiger_contactdetails as vtiger_contactdetailsCalendar on vtiger_contactdetailsCalendar.contactid= vtiger_activity.link left join vtiger_groups as vtiger_groupsCalendar on vtiger_groupsCalendar.groupid = vtiger_crmentity.smownerid left join vtiger_users as vtiger_usersCalendar on vtiger_usersCalendar.id = vtiger_crmentity.smownerid left join vtiger_groups on vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_users on vtiger_users.id = vtiger_crmentity.smownerid left join vtiger_account as vtiger_accountRelCalendar on vtiger_accountRelCalendar.accountid=vtiger_activity.link left join vtiger_leaddetails as vtiger_leaddetailsRelCalendar on vtiger_leaddetailsRelCalendar.leadid = vtiger_activity.link left join vtiger_vendor as vtiger_vendorRelCalendar277 on vtiger_vendorRelCalendar277.vendorid = vtiger_activity.link left join u_yf_partners as u_yf_partnersRelCalendar277 on u_yf_partnersRelCalendar277.partnersid = vtiger_activity.link left join u_yf_competition as u_yf_competitionRelCalendar277 on u_yf_competitionRelCalendar277.competitionid = vtiger_activity.link left join vtiger_ossemployees as vtiger_ossemployeesRelCalendar277 on vtiger_ossemployeesRelCalendar277.ossemployeesid = vtiger_activity.link left join vtiger_crmentityrel as vtiger_crmentityreltmpContacts ON (vtiger_activity.activityid=vtiger_crmentityreltmpContacts.relcrmid OR vtiger_activity.activityid=vtiger_crmentityreltmpContacts.crmid) left join vtiger_reptmptbl_5573571336d4056943795610 as vtiger_contactdetails on (vtiger_contactdetails.contactid=vtiger_crmentityreltmpContacts.relcrmid OR vtiger_contactdetails.contactid=vtiger_crmentityreltmpContacts.crmid) left join vtiger_crmentity as vtiger_crmentityContacts on vtiger_crmentityContacts.crmid = vtiger_contactdetails.contactid and vtiger_crmentityContacts.deleted=0 left join vtiger_account as vtiger_accountContacts on vtiger_accountContacts.accountid = vtiger_contactdetails.parentid left join vtiger_crmentityrel as vtiger_crmentityreltmpAccounts ON (vtiger_activity.activityid=vtiger_crmentityreltmpAccounts.relcrmid OR vtiger_activity.activityid=vtiger_crmentityreltmpAccounts.crmid) left join vtiger_reptmptbl_5573571336dd4e5629455041 as vtiger_account on (vtiger_account.accountid=vtiger_crmentityreltmpAccounts.relcrmid OR vtiger_account.accountid=vtiger_crmentityreltmpAccounts.crmid) left join vtiger_crmentity as vtiger_crmentityAccounts on vtiger_crmentityAccounts.crmid=vtiger_account.accountid and vtiger_crmentityAccounts.deleted=0 WHERE vtiger_activity.activityid > 0  AND vtiger_crmentity.deleted=0 and (vtiger_activity.activitytype != 'Emails') and (( CAST((CONCAT(date_start, " ", time_start)) AS DATETIME) BETWEEN '2016-05-07 00:00:00' AND '2016-05-13 23:59:59' ) ) order by `Calendar__Assigned__To`  LIMIT 0, 1000`
LBL_SQL_TRACE:
```
#0 PearDatabase->query() in include/database/PearDatabase.php(360): 
#1 PearDatabase->pquery() in modules/Reports/ReportRun.php(2540): 
#2 ReportRun->GenerateReport() in modules/Reports/models/Record.php(718): 
#3 Reports_Record_Model->getReportData() in modules/Reports/views/Detail.php(48): 
#4 Reports_Detail_View->preProcess() in include/main/WebUI.php(82): 
#5 Vtiger_WebUI->triggerPreProcess() in include/main/WebUI.php(219): 
#6 Vtiger_WebUI->process() in index.php(24): 
```

**Comment by bpabiszczak** [comment]
Please check the latest versions: https://gitdeveloper.yetiforce.com. We fixed a lot of mistakes in the reports.
