### ISSUE TITLE
Sync Caldav and IOS 9.3.1

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#2980]
tested on: https://gitdeveloper.yetiforce.com

Ipad IOS Version: 9.3.1

1) create new Account caldav on IOS with this settings:

Server: http://gitdeveloper.yetiforce.com/api/dav.php/principals/demo/
User: demo
password: demo
Port: 80
SSL: false

When I add an event on the IOS calendar it is properly Synchronized with Yeti Calendar 
after cron Caldav execution. 
But when I add an event on the Yeti calendar it is not Synchronized with IOS Calendar, even using manual synchronization.

tested on local demo
cache/log/davDebug.log
```
============ 2016-05-13 13:19:57 ====== Request ======
PROPFIND /api/dav.php/calendars/admin/inbox/ HTTP/1.1
Authorization: Digest REDACTED
Host: localhost
Accept: */*
Brief: t
Accept-Language: it-it
Accept-Encoding: gzip, deflate
Content-Type: text/xml
Content-Length: 181
Depth: 0
Connection: keep-alive
User-Agent: iOS/9.3.1 (13E238) dataaccessd/1.0
Prefer: return=minimal

<?xml version="1.0" encoding="UTF-8"?>
<A:propfind xmlns:A="DAV:">
  <A:prop>
    <C:getctag xmlns:C="http://calendarserver.org/ns/"/>
    <A:sync-token/>
  </A:prop>
</A:propfind>

============ 2016-05-13 13:19:57 ====== Response ======
HTTP/1.1 207 Multi-Status
X-Sabre-Version: 2.1.3
Content-Type: application/xml; charset=utf-8
Vary: Brief,Prefer
DAV: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, calendar-access, calendar-proxy, calendarserver-subscribed, calendar-auto-schedule

<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:response><d:href>/api/dav.php/calendars/admin/inbox/</d:href><d:propstat><d:prop><cs:getctag/><d:sync-token/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
```

It could be wrong that searches the calendar in this destination: /api/dav.php/calendars/admin/inbox/
but in IOS there is no possibility of defining the calendar name (YFCalendar)

**Comment by zebrahosting** [comment]
I can confirm the same behavior on my own CRM's.

**Comment by mariuszkrzaczkowski** [comment]
Fixed  in https://github.com/YetiForceCompany/YetiForceCRM/commit/8a297a444f516c4a28afe782f0fb28cee4381a85

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/aa7a987418466dffc136690e1bc7bb08d5726d9c

**Comment by nic86** [comment]
tested on developer version 3.1.390

Continues to give problems on synchronization of appointments from yeti to ios, shows only canceled and overdue appointments but not planned and completed.

from ios to yeti it seems ok.
