### ISSUE TITLE
Functionality explanation yeti force (Document Template, Document Flow, Trigger system)

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#2982]
You can have a brief explanation of the operation and use of:
Document Template
Document Flow
Trigger when - Specify when to execute this workflow is: "System"

I know it would be better to talk about one thing at a time , but it would be useful to create guides for individual modules.
thanks
best regards

**Comment by KatarzynaUlichnowska** [comment]
Hello!
1. Triggers [or Workflows in other words] are the mechanisms that allow for the automation of tasks within the system. Workfrow works in two situations (depending on the configuration): it can be triggered by CRON in regular time intervals or it is triggered by a user or action. Thanks to this tool, it is possible to perform many actions within the system and you can view its tasks in step three of its configuration. This tool allows for the automation of the entire system. However, remember that it works after triggering of an action or on the basis of time intervals. If you want to do something before action triggering, you need to use this mechanism: https://gitdeveloper.yetiforce.com/index.php?module=DataAccess&parent=Settings&view=Index&block=15&fieldid=52 
2. Document Template [the translation is incorrect, it should be Project Templates] is used for creating templates of projects. It allows to create a project template together with milestones and project tasks. When a template is created, a single click opens a project with hundreds of preconfigured tasks. However, this module requires to be rewritten. 
3. Document Flow - used for creating templates for the flow of documents in modules [Projects and Tickets by default but it should also in Opportunities, Accounting, Logistics]. For example, this module shows what documents are required at a given stage of a process and it may block proceeding to the next stage if you don't provide a necessary document. This module also requires to be rewritten.
