### ISSUE TITLE
[bug] not attach email from Accounts

### ISSUE THREAD

**Issue by jjoloka** [YetiForceCompany/YetiForceCRM#2985]
tested on: https://gitdeveloper.yetiforce.com

If send Email on Accounts -> "Primary email", in widget Accounts - Emails and Accounts tab "Company Email" does not display sent message.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
firstly, your description of a problem is insufficient. It would be best if you could record a video.
Secondly, please check out this tool - the Scanner https://gitdeveloper.yetiforce.com/index.php?module=OSSMailScanner&parent=Settings&view=Index&block=8&fieldid=44. Did you enable it?
