### ISSUE TITLE
error in assets  relation List module time control

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#2986]
in asset module when click in time control tab an error happen 
![screenshot from 2016-05-15 14 10 22](https://cloud.githubusercontent.com/assets/18072100/15273207/d544c50e-1aa6-11e6-8137-0fa631b4de8d.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/46fa876281e30d8ff552e959c0aae8e505dd3f77
