### ISSUE TITLE
Recording control - global Coloring of lines 

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2987]
This is a wery usefull tool but it works only in list view. Example: i made rule if calendar record has high priority than line (and icon) must be colored to some color. This is works well here:
![image](https://cloud.githubusercontent.com/assets/8545791/15273906/424aaa12-1aaf-11e6-9684-a338f9ead054.png)
But from another point this tool not works:
![image](https://cloud.githubusercontent.com/assets/8545791/15273914/68077816-1aaf-11e6-99aa-7ed3aa64ee87.png)
![image](https://cloud.githubusercontent.com/assets/8545791/15273916/74fbbdb6-1aaf-11e6-94bf-ae98a12b0bbe.png)
![image](https://cloud.githubusercontent.com/assets/8545791/15273921/81faf7a2-1aaf-11e6-80f0-c3b823077f73.png)
This is a good idea to made this tool applicable for all types of view of record.
If apply some rule for product there is no coloring for product name at sales or logistic modules when saerch or at popup list of products.

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/74d6007fb74309c7982283ad0d8a5229652769ca
https://github.com/YetiForceCompany/YetiForceCRM/commit/d04f16b1a97d046c079fd974682f3e3a06a65474
