### ISSUE TITLE
Recording control - Coloring of lines - Coloring priority

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2989]
There  is no ability to set coloring of lines rules priority. If some record satisfies the conditions of multiple coloring rules every time works only last added condition.

maybe possible to made some mixing of rules

**Comment by vovpff** [comment]
@KatarzynaUlichnowska sorry, wgat means Cat::Question?

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/202-descriptions-of-labels-for-github-issues.html

**Comment by vovpff** [comment]
@bpabiszczak @KatarzynaUlichnowska thx!
Ok. Now situation is next. Example. We have two rules for Products. R1 colors to red if qty=0. R2 colors to green if category is Antivirus. If rule R2 added after R1 we newer can see red text and icon for product with category antivirus and qty=0. This product would be every time green. Idea to made priority of rules or mixing. Mixing is more comfortable. Example: all line is green if categoty=antivirus but qty field or column are red because qty=0.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
color appearance can be defined in conditions. Currently, we don't have any plans to develop this functionality.
