### ISSUE TITLE
Filtering of updates

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2991]
Are there possibility to filter updates tab/widget? If a lot of users works with one record there is a lot of "displayed by username" lines appears and important information can be lost.

**Comment by vovpff** [comment]
But for some modules "displayed by username" lines can be very usefull too.

**Comment by bpabiszczak** [comment]
![yetiforce - history review](https://cloud.githubusercontent.com/assets/10197525/15800649/42f01a44-2a7f-11e6-9c2a-029fb6cc76f4.gif)

**Comment by bpabiszczak** [comment]
![yetiforce - history review 2](https://cloud.githubusercontent.com/assets/10197525/15800702/e0977f7a-2a80-11e6-872d-0b3f254dfb84.gif)
