### ISSUE TITLE
What is the difference between Bookkeeping and Payments In/Out?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#2993]
Hi,

what is the difference between Bookkeeping and Payments In/Out Modules? Are they linked in any way i.e. for reporting purposes?

I once used an accounting package in Vtiger and it was one module, but had a field called payment type (Income/Expense). 

My question is, could I incorporate payment details in the bookkeeping module and delete the payments in and out? Or are they needed for some internal processing. Or could I get rid of Bookkeeping and keep payments in/out? Would there be any implications with doing either of these?

Percy

**Comment by KatarzynaUlichnowska** [comment]
Hello,
you can disable modules and everything should work properly (in theory). The Bookkeeping module is the same as the Opportunities module and is used for the sole purpose of organizing the financial process. Payments In and Payments Our record all deposit/withdrawal operations from your bank. On the basis of these modules the system will estimate the balance of a customer and will send notifications in case of delays in payments for invoices.
