### ISSUE TITLE
[Improvement suggestion] Databases -> Our sites: Tagging bookmarks

### ISSUE THREAD

**Issue by ElectricTyphoon** [YetiForceCompany/YetiForceCRM#2994]
It would be great to be able to:
- add tags to links we bookmark (since right now the only thing we can use to distinguish them is the title. It's useful because sometimes you'd want to categorize a link as more than one thing, but don't want to double it in the database)
- be able to sort the links by the tags assigned

(loving yetiforce so far!)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
thank you for your suggestions but we don't have enough time to implement every idea. There is a new article that we recommend reading https://yetiforce.com/en/github/issues/206-system-development-ideas.html.
