### ISSUE TITLE
[problem] PriceBook doesn't appear in quotes or invoices.

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#2996]
![screenshot_2](https://cloud.githubusercontent.com/assets/11919990/15280176/01bda172-1af3-11e6-9597-b96e9cce3a71.png)

I changed the code as rezaizadi suggested in his earlier post. 
    I Fixed this problem
    at this file: \modules\PriceBooks\models\Record.php
    change function name getProductUnitPriceURL to getProductListPriceURL

but it still doesn't appear.

I'm on version 3.0

**Comment by mykljohn** [comment]
Any idea on this?  It's the last obstacle I've hit.  cheers, Mykl

**Comment by mykljohn** [comment]
@rskrzypczak Hi, I'm having trouble getting the Pricebook to show in Invoices and Quotes and I'm wondering if I've missed something on setup.  I'm on 3.0 latest.

**Comment by bpabiszczak** [comment]
Please check the latest versions. We fixed a lot of mistakes.
