### ISSUE TITLE
How quick create activity from activity

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#2999]
How to made activity (1) related to activity (2) from activity (2) window with autofilled company/contact and assigned to fields? Any ideas?

**Comment by vovpff** [comment]
@bpabiszczak @KatarzynaUlichnowska ok. I will try to explain. For me critical to have and control chain of activitys. For example: I plan a call to my customer (some contact). I add activity A1 (call event) for this. After call I have some new information and need to add new one activity A2 (event or to-do) what related to the same contact and activity A1.
For this time I can change status of activity to completed or to postponed.
If status changed changed to completed than activity goes to history with no information. I solved this with status postponed: after clicking postponed button there is appears quick create window for calendar what contais subject of A1. I change this subject to another one, time, activity type and save record.
Detailed view of A2 contains relation to contact and to A1 in subprocess field.

**Comment by vovpff** [comment]
This is needed to get A1 completed but A2 must contain link to A1

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
at the moment, there is a button "Postpone", which allows to create another activity from the one that already exists. When you click the button, a new window appears and there are filled in fields in it and a relation to the previous activity. When you save this new activity, the old one changes the status automatically to "Postponed". If you don't save the second activity, the first activity remains open. 

We consider it as a good solution and aren't currently planning to change it.

**Comment by vovpff** [comment]
Ok. In this case solution is changong translation of Postponed button
