### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by gokkstudio** [YetiForceCompany/YetiForceCRM#3000]
Hi, Yeti is awesome.
I simply can't create role with custom permissions, everything I create (as admin) or modify existing roles I get modules locked; ie. how would I create something like this with only "pre-order" permissions:
Board of Management > Sales Department > Sellers (sellers only have "pre-order")???

**Comment by gokkstudio** [comment]
While editing and saving profile that is assigned to user "Sellers" I get this - attached.
![issue1](https://cloud.githubusercontent.com/assets/19394068/15305476/a962f62c-1bc3-11e6-8c09-626bf98f745a.jpg)
![issue2](https://cloud.githubusercontent.com/assets/19394068/15305477/a97b0992-1bc3-11e6-896d-74339de0ffb3.jpg)

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

Please check this: max_input_vars 5000 [or more 10000, 20000].

**Comment by gokkstudio** [comment]
Thank you very much!

**Comment by gokkstudio** [comment]
Hello again, I need your advice.
What module should I use for something like this:
Internal Stock order from central warehouse - store salesman orders goods
from headquarters for sale.
Pre-order? or Quote or??

Thanks again.

**Comment by bpabiszczak** [comment]
New question = new issue
