### ISSUE TITLE
Mapping Calendar to Comments

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3004]
dev 3.0.15
If Calendar to Comment mapping already addet there is no possibility to edit this rule^
![image](https://cloud.githubusercontent.com/assets/8545791/15313929/5b607dec-1c17-11e6-8fd7-6eee0be78784.png)
XML exported file of mapping contains:
`<?xml version="1.0" encoding="utf-8"?>
<mf_template>
  <tabid>Calendar</tabid>
  <reltabid>ModComments</reltabid>
  <conditions><![CDATA[[]]]></conditions>
  <status>active</status>
  <params><![CDATA[[]]]></params>
  <permissions></permissions>
  <fields>
    <field>
      <type>V</type>
      <default></default>
      <source></source>
      <target>commentcontent</target>
    </field>
    <field>
      <type>V</type>
      <default>0</default>
      <source></source>
      <target>assigned_user_id</target>
    </field>
  </fields>
</mf_template>`

**Comment by rskrzypczak** [comment]
There should not be an option to create mapping templates involving the Comments module.
