### ISSUE TITLE
Widgets in Polish

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3008]
Hi,

I am just testing the widgets modules on home dashboard and notice that although I have selected English as default during install, for user setup etc. things like the Calendar pending, leads etc. on dashboard are in Polish.

Is this a bug or does it just require a settings change somewhere?

Percy
![history](https://cloud.githubusercontent.com/assets/10598886/15317285/b0f6b8ba-1c18-11e6-80fd-8e1e372f86c5.png)

**Comment by vovpff** [comment]
@PercyP you installed system or yse stable/master on yetiforce website. Looks like somebody already added this record with polish names.

**Comment by PercyP** [comment]
Hi vovpff,

i installed stable system on own server. These messages seem to be created automatically from some triggers. I created some test leads, then it populates those widgets with the polish texts.

**Comment by vovpff** [comment]
@PercyP sorry, no ideas

**Comment by PercyP** [comment]
@vovpff 

thanks for trying to help anyway. If I figure out what is causing it will post back - in case others have same issue.

**Comment by PercyP** [comment]
@vovpff 

hi as promised, I found what is causing it. It is the triggers under Automation/Triggers, the language in these i.e. in the task titles are not changing. I have changed these manually now.
