### ISSUE TITLE
[PL] Powiązanie modułu BazyWiedzy jako pole 1:M w innym module

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#3011]
Testowane na wersji 3.0.0 oraz dev.
Po stworzeniu nowego pola powiązanego 1:M np. w module Kontrahenci powiązanego do modułu Baza wiedzy występuje błąd podczas próby wyboru rekordu w okienku popup (powiązanego pola baza wiedzy)
![bazawiedzy](https://cloud.githubusercontent.com/assets/14766421/15326851/c6f73e78-1c4f-11e6-8d89-162d739c9d26.png)
błąd dotyczy tylko powiązananych pól do modułu Baza wiedzy.

**Comment by bpabiszczak** [comment]
Nie rozwiązujemy problemów związanych z modyfikacją systemu [w szczególności dodawanie własnych modułów, czy też zmiana relacji] ponieważ to może wiele popsuć w systemie i to co należy zrobić to przede wszystkim analizować logi. 

W takim wypadku mogę co najwyżej zaproponować płatny pakiet wsparcia. Może ktoś ze społeczności Ci pomoże bezpłatnie, ale wtedy najlepiej napisać dodatkowy opis w EN.

**Comment by wbnx** [comment]
Zarówno moduł Kontrahenci jak i KnowledgeBase są to moduły YetiForce'a z czystych instancji. Test wykonany na czystej instancji wykorzystując funkcjonalności powiązywania pół z innych modułów bez żadnych dedykowanych ingerencji w kodzie systemu czy modułu. Błąd jest najprawdopodobniej w module KnowledgeBase ale zrobicie z tym co chcecie.

**Comment by mariuszkrzaczkowski** [comment]
Błażej miał namyśli, że każde takie zmiany są "kruche" i powodują problemy i dobrze mieć wiedzę programistyczną lub wsparcie kogoś kto pomoże. 

Odnośnie problemu to:

1. Brak informacji o wersji. 
2. Brak informacji o logach. 
3. Brak informacji o tym jak dokładnie krok po kroku wywołać błąd [np. czy dodane z vtlib czy z panelu, jak nazywają się pola i kolumny w bazie bo one też mogą stanowić problem]. 
4. itd. zalecamy dokumentacje jak zgłaszać błędy

Z ciekawości dodałem takie pole w bazie wiedzy linkujące do kontrahenta i nam działa...

**Comment by mariuszkrzaczkowski** [comment]
![image](https://cloud.githubusercontent.com/assets/10198654/15360542/4433bca4-1d0e-11e6-8c42-996961b6272b.png)

**Comment by wbnx** [comment]
Wersje podałem w pierwszym poście testowane na 3.0.0 i dev z dnia wczorajszego. Info o lagach nie napisałem za brak dokładności sry (tworzenie pola odbywało się tylko i wyłącznie za pomocą kretora/edytora pól z poziomu administracji systemu - nie vtlib). Zrobiłeś odwrotnie niż opisałem. Dodaj do modułu Kontrahenci nowe powiązane pole do modułu Baza wiedzy :)

**Comment by bpabiszczak** [comment]
rozumiem, że chodzi o powiązanie 1:M? I tak z ciekawości po co takie powiązanie, bo to niezgodne z zaszytą obecną filozofią...

**Comment by wbnx** [comment]
Tak 1:M. Tu już pytanie do PMa lub wdrożeniowca który to wykonywał dlaczego ten moduł został wybrany do użycia przy logice biznesowej klienta. Ja jestem dev ale nie miałem czasu tego dokładnie debugować bo mam dużo tasków do roboty ale w tym wypadku utworzenie nowego podstawowego modułu entity wystarczyło. Tak czy inaczej jakiś drobny błąd jest przy powiązywaniu KnowledgeBase jako pole 1:M do innych modułów z poziomu panelu admina.

**Comment by bpabiszczak** [comment]
Już chłopaki coś tam znaleźli i pewnie będą fix-ować w wolnej chwili... dziękuję za informacje.
