### ISSUE TITLE
[Improvement 3.0] PDF background Image

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#3012]
You might want to make this a bit easier with regard to backgrounds and other advanced features.   mpdf has some nice features with regard to gradients, backgrounds, borders, etc.  But when you add a background image in to source, it disappears the next time you edit it.  I save it in notepad and re-copy it in when I re-edit the source.  Just a suggestion.

Great job with everything.

**Comment by konadrian** [comment]
I tried to trigger your error (" But when you add a background image in to source, it disappears the next time you edit it"), but i didn't succeed. Results below:
![animation](https://cloud.githubusercontent.com/assets/3193498/16043475/1c720152-3240-11e6-9a8e-573b425787dd.gif)

**Comment by mykljohn** [comment]
I don't want the background image as a watermark though.  I want it full color.  Is there a way to do that?

**Comment by bpabiszczak** [comment]
http://stackoverflow.com/questions/20828776/mpdf-full-page-background

**Comment by bpabiszczak** [comment]
http://stackoverflow.com/questions/10414663/can-not-get-background-color-in-pdf-generated-from-html
