### ISSUE TITLE
autocomplete "to" in send mail roundcube

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3019]
tested on: https://gitdeveloper.yetiforce.com   version 3.1

When creates a contact is trigger the task add to addressbook and update the file located in the cache /addressBook/mail_[user_id].php that contain the list of email.
But in the  file /modules/OSSMail/roundcube/program/steps/mail/autocomplete.inc is rebuilt the file name with the property [crm_user_id] that is only updated if you set user for the mailbox in mailscanner module. 
It would be better also set the value at the creation of roundcube users or add the possibility to set it manually.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
could you please describe it again as we don't understand what you mean?
