### ISSUE TITLE
Changelog and download links to YetiForce 3.1

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#3021]
Hello,
today we released a new version. Below you will find an overview of the most important changes that have been introduced over the last month.

**SECURITY:**
• secured and optimized loading of data from requests,
• blocked permissions to actions that don’t exist,
• improved permissions mechanism,
• optimized the mechanism that loads information about users.

**ADDED:**
• new permissions to remove relations between records,
• new language - French,
• global change tracking ,
• ICS support for Calendar Import, 
• changes to API ,
• mapping from Accounts to Vendors .

**IMPROVED:**
• DAV integration, 
• filtering in the widget history ,
• creating records via workflow,  
• error registration,  
• functions in API, 
• sending documents via email ,
• widgets, 
• logs in sending mail, 
• function getRangeTime(), 
• notifications ,
• variety of appearance improvements,  
• a ton of translations,  
• updated SabreDav library. 

**FIXED:**
• permissions in Webservice, 
• scrolling on mobile devices, 
• Mass edit action in a custom module, 
• references to system fields,  
• hierarchy of Accounts. 

**NEW COMMERCIAL MODULES:**
• POS 
• Analyzer 
• PrestaSync
• Permission Inspector 

Here are all download links that you may need:

**YetiForceCRM 3.1**
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%203.x.x/3.1.0/YetiForceCRM-3.1.0.zip/download

**YetiForceCRM update package 3.0 --> 3.1**
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%203.x.x/Update%20packages/3.0.0_to_3.1.0_v1.zip/download

**YetiForcePortal 3.1**
https://sourceforge.net/projects/yetiforce/files/YetiForce%20Portal%203.x.x/3.1.0/YetiForcePortal-3.1.0.zip/download

**YetiForcePortal update package 3.0 --> 3.1**
https://sourceforge.net/projects/yetiforce/files/YetiForce%20Portal%203.x.x/Update%20packages/3.0.0_to_3.1.0.zip/download

**Comment by acidhunter** [comment]
Please stay on github, sourceforge is something unprofessional, know for infecting projects with malware

**Comment by acidhunter** [comment]
http://www.howtogeek.com/218764/warning-don%E2%80%99t-download-software-from-sourceforge-if-you-can-help-it/
