### ISSUE TITLE
[Problem] Holiday and Day Absences at work

### ISSUE THREAD

**Issue by MexasPT** [YetiForceCompany/YetiForceCRM#3023]
99% of companies use HR programs only for control of employees who missed work or took vacation days.
The Yeti allows the first part of the work, registration, but I can not create a pdf with the list of work absences and vacations.
I tried to use the functions defined in the system but are inapplicable.

Is there any way to create the following PDF:
Name of Employees  |  Subject  |  Start Date  |  End Date  |  Number of days

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
PDF can generate any information you need if a developer writes a special function. You issue also requires a special function. In future, we will optimize it if there is a customer eager to pay for it.
