### ISSUE TITLE
Po aktualizacji systemu: Brak uprawnień

### ISSUE THREAD

**Issue by r0bertk** [YetiForceCompany/YetiForceCRM#3024]
Witam, po zaktualizowaniu systemu do wersji 3.0 (We wcześniejszych wersjach 2.. nie miałem tego problemu) po wejściu na stronę główną Wirtualne biurko->Home Page pojawia się komunikat:
Brak uprawnień
Permission to perform teh operation is denied for name: Quotes

Aktualizacja do wersji 3.1 nic nie zmieniła w tej kwestii. 
Pozostałe funkcje systemu działają tylko przy wejściu na Home Page pojawia się ten błąd.
Jak można go naprawić proszę o jakieś wskazówki.

**Comment by bpabiszczak** [comment]
a gdzie logi? 
co widać w profilach?

**Comment by r0bertk** [comment]
A które logi mam wkleić: phperror.log?
Poniżej printscreen z profili:
![yeti](https://cloud.githubusercontent.com/assets/13787190/15373410/c91d1690-1d45-11e6-8e27-36fe5e674ba4.jpg)

**Comment by bpabiszczak** [comment]
Czy do końca widoku profilu widać "ptaszki"...

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/dokumentacja-programisty/b%C5%82%C4%99dy/109-debugowanie.html

// Enable log4php -> cache/logs/system.log
'LOG4PHP_DEBUG' => false,

**Comment by r0bertk** [comment]
Ok, już uruchamiam logowanie.
Jeśli chodzi o profile to "ptaszków" niema w:
Strona główna
Maile
RSS
Raporty
Strony WWW
Kosz
Formularze WWW
Moja poczta
Hasła
Skaner wiadomości mail
Przepływ dokumentów
Szablony projektu
Chat
Api Address

**Comment by bpabiszczak** [comment]
pokaż mi zrzut ekranu z całego profilu. 
skoro nie ma ptaszka na stronie głównej to jak strona główna ma działać :p ?

**Comment by r0bertk** [comment]
Poniżej cały profil Administratora, zauważyłem również że jak dodam nowego użytkownika to mogę wejść na stronę główną, jednak ja wejdę do Moduły standardowe->Widgety konfiguracja i dodam rolę to od tego momentu przestaje działąć strona główna dla dodanego użytkownika.
![yeti5](https://cloud.githubusercontent.com/assets/13787190/15374390/720178d8-1d4a-11e6-8979-5030508e50b6.jpg)
![yeti4](https://cloud.githubusercontent.com/assets/13787190/15374389/7200b4c0-1d4a-11e6-9f38-d575f2f7f255.jpg)
![yeti3](https://cloud.githubusercontent.com/assets/13787190/15374391/720357c0-1d4a-11e6-83a4-622cab8bde7e.jpg)
![yeti2](https://cloud.githubusercontent.com/assets/13787190/15374392/72046656-1d4a-11e6-85b9-2a228d89ca45.jpg)
![yeti1](https://cloud.githubusercontent.com/assets/13787190/15374393/72084d8e-1d4a-11e6-9c9b-c9256ed073aa.jpg)

logi:
[system.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/271385/system.txt)

**Comment by r0bertk** [comment]
W logach wyrzuca błąd:
ERROR System - Permission to perform the operation is denied for name: Quotes =>
/var/www/crm/include/Webservices/VtigerWebserviceObject.php:65

w tej lini jest zapis:
throw new WebServiceException(WebServiceErrorCode::$ACCESSDENIED, 'Permission to perform the operation is denied for name: ' . $entityName);

**Comment by bpabiszczak** [comment]
a jak to się stało, że w 15 modułach nie było ptaszków a potem widać je na profilach? 
co pokazują logi przy migracji do nowej wersji z 2.x do 3.x?

**Comment by mariuszkrzaczkowski** [comment]
Błąd powodują pozostałości po starym module ofert(Quotes) pewnie zostały nie usunięte jakieś filtry/widoki lubi widgety na pulpicie lub coś skonfigurowane odwołujące się do modułu Quotes który już nie istnieje. Trzeba poszukać w bazie wpisów o Quotes i je usunąć.

**Comment by r0bertk** [comment]
Dziękuję za pomoc usunąłem z bazy wszystkie wpisy zawierające Quotes, poźniej wyrzucił bląd o Invoice, ale jak je również usunąłem z bazy to wszystko zaczęło działać.
Mam nadzieję, że przez to usuwanie nie przestanie działąć coś innego, na razie wygląda że jest wszystko w porządku.
Jeszcze raz dziękuję za wskazówki i pozdrawiam

**Comment by mariuszkrzaczkowski** [comment]
Proszę o informacje w jakich tabelach były pozostałości to dodamy to do paczki aktualizacyjnej.

**Comment by r0bertk** [comment]
Witam, Quotes były w tabelach:
2 dopasowania wewnątrz tabeli com_vtiger_workflow_tasktypes
1 dopasowań wewnątrz tabeli com_vtiger_workflows
2 dopasowania wewnątrz tabeli vtiger_blocks
1 dopasowań wewnątrz tabeli vtiger_customview
1 dopasowań wewnątrz tabeli vtiger_entityname
39 dopasowań wewnątrz tabeli vtiger_field
6 dopasowań wewnątrz tabeli vtiger_fieldmodulerel
1 dopasowań wewnątrz tabeli vtiger_modentity_num
5 dopasowań wewnątrz tabeli vtiger_modtracker_basic
15 dopasowań wewnątrz tabeli vtiger_modtracker_detail
1 dopasowań wewnątrz tabeli vtiger_module_dashboard
3 dopasowania wewnątrz tabeli vtiger_relatedlists
1 dopasowań wewnątrz tabeli vtiger_relatedlists_rb
1 dopasowań wewnątrz tabeli vtiger_relcriteria
1 dopasowań wewnątrz tabeli vtiger_reportmodules
1 dopasowań wewnątrz tabeli vtiger_reporttype
1 dopasowań wewnątrz tabeli vtiger_tab
1 dopasowań wewnątrz tabeli vtiger_ws_entity

Natomist Invoice były w tabelach:
3 dopasowania wewnątrz tabeli vtiger_customview
1 dopasowań wewnątrz tabeli vtiger_cvcolumnlist
3 dopasowania wewnątrz tabeli vtiger_entityname
98 dopasowań wewnątrz tabeli vtiger_field
9 dopasowań wewnątrz tabeli vtiger_fieldmodulerel
2 dopasowania wewnątrz tabeli vtiger_import_maps
1 dopasowań wewnątrz tabeli vtiger_lin_type_doc
2 dopasowania wewnątrz tabeli vtiger_links
1 dopasowań wewnątrz tabeli vtiger_lout_type_doc
3 dopasowania wewnątrz tabeli vtiger_modentity_num
7 dopasowań wewnątrz tabeli vtiger_modtracker_basic
7 dopasowań wewnątrz tabeli vtiger_modtracker_detail
3 dopasowania wewnątrz tabeli vtiger_module_dashboard
6 dopasowań wewnątrz tabeli vtiger_picklist
4 dopasowania wewnątrz tabeli vtiger_relatedlists
3 dopasowania wewnątrz tabeli vtiger_tab
3 dopasowania wewnątrz tabeli vtiger_ws_entity
