### ISSUE TITLE
aktualizacja z 3.0 do 3.1

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#3029]
Podczas aktualizacji z wersji 3.0 do 3.1 pojawia się błąd brak domyślnego języka pl
![image](https://cloud.githubusercontent.com/assets/11491482/15408284/b527bcf6-1e0f-11e6-9120-a507cdadc2b1.png)
Paczka updetu pobrana z https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20Portal%203.x.x/3.0.0_to_3.1.0/zip

Natomiast paczka aktualizacyjna pobrana z 
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%203.x.x/Update%20packages/3.0.0_to_3.1.0_v1.zip/download
przeszła update pomyślnie...

**Comment by bpabiszczak** [comment]
My często "aktualizujemy" paczki gdy zawierają jakieś błędy. Aktualna paczki migracyjna z 3.0 do 3.1 jest dostępna tutaj: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x/3.0.0_to_3.1.0/zip

**Comment by mariuszkrzaczkowski** [comment]
> Paczka updetu pobrana z https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20Portal%203.x.x/3.0.0_to_3.1.0/zip

To jest paczka aktualizacyjna do portalu klienta więc na pewnie nie będzie działać w CRM.
