### ISSUE TITLE
Errors installing - tried everything suggested

### ISSUE THREAD

**Issue by LexPetkov** [YetiForceCompany/YetiForceCRM#3031]
Hi

I am trying to install Yeti on a dedicated managed server of ours to no success. I have also tried all suggested code to put in php.ini again to no success
 
Have tried:
error reporting to E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
and
error reporting to E_ERROR
and in the .htaccess file

<IfModule mod_php5.c>
php_value error_reporting 30711
</IfModule>

Although i can now see the install wizard , there are still many PHP errors showing before it

I have also contacted the hosting support and they couldn't help either and have suggested to get in touch with you with the following question:

"Are you able to confirm with the developers that these problems are ones that need to be addressed? I can see in their requirements that they say to actually turn off showing errors and before doing anything drastic you may want to get them to check this out just to be sure. Thanks!"

Best Regards,

Lex

**Comment by waw555** [comment]
.htaccess

`<IfModule mod_autoindex.c>
	Options -Indexes
</ifModule>
########################
<IfModule mod_rewrite.c>
	Options +FollowSymLinks
	RewriteEngine On
	RewriteRule ^api/webservice/(.*)/(.*)/(.*)$ api/webservice.php?module=$1&action=$2&record=$3 [QSA,NC,L]
	RewriteRule ^api/webservice/(.*)/(.*)$ api/webservice.php?module=$1&action=$2 [QSA,NC,L]
	RewriteRule ^api/webservice/(.*)$ api/webservice.php?module=$1 [QSA,NC,L]

	RewriteRule ^\.well-known/carddav /api/dav.php/addressbooks/ [R]
	RewriteRule ^\.well-known/caldav /api/dav.php/calendars/ [R]
	RewriteRule /.well-known/carddav /api/dav.php/addressbooks/ [R,L]
	RewriteRule /.well-known/caldav /api/dav.php/calendars/ [R,L]
	RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
</ifModule>
<IfModule mod_php5.c>

	php_flag 	safe_mode 					off
	php_flag	log_errors					Off
	php_flag	display_errors				Off
	php_flag	register_globals			On
	php_flag	short_open_tag				On
	php_value	memory_limit				1024M
	php_flag	output_buffering			On
	php_flag    zlib.output_compression		Off
	php_flag	file_uploads				On

	php_value	max_execution_time			6000
	php_value	max_input_time				6000
	php_value	default_socket_timeout		6000
	php_value	mysql.connect_timeout		6000
	
	php_value 	error_reporting				"E_WARNING & E_ERROR & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT"
	php_flag	magic_quotes_gpc			Off
	php_flag	magic_quotes_runtime        Off
	php_flag	magic_quotes_sybase 		Off
	php_value	post_max_size				500M
	php_value	upload_max_filesize			500M
	php_value	max_input_vars				5000
	php_value	max_allowed_packet 			100M
	
	php_value mbstring.func_overload 		2
	php_value mbstring.internal_encoding 	UTF-8
	php_value allow_url_fopen 				On

	php_value	suhosin.request.max_vars	5000
	php_value	suhosin.post.max_vars		5000
	php_flag	suhosin.session.encrypt		Off

	php_flag	session.auto_start			Off
	php_value	session.gc_maxlifetime		21600
	php_value	session.gc_divisor			500
	php_value	session.gc_probability		1
	php_value	error_log					cache/logs/phpError.log
</IfModule>
<IfModule fcgid_module.c>
	FcgidIOTimeout 600
	FcgidConnectTimeout 600
	FcgidBusyTimeout 600
	FcgidIdleTimeout 600
</IfModule>
########################
# <FilesMatch "\.(inc|php|php3|php4|php5|php6|phtml|phps)$">
# AddHandler x-httpd-php56 .inc .php .php3 .php4 .php5 .php6 .phtml
# </FilesMatch>
`

**Comment by LexPetkov** [comment]
I forgot to paste the errors, so here it is:

`Strict Standards: Declaration of AntlrLexer::matchAny() should be compatible with BaseRecognizer::matchAny($input) in /home/lht/public_html/yeti/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::recover() should be compatible with BaseRecognizer::recover($input, $re) in /home/lht/public_html/yeti/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /home/lht/public_html/yeti/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /home/lht/public_html/yeti/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrParser::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /home/lht/public_html/yeti/libraries/antlr/AntlrParser.php on line 98

Strict Standards: Declaration of AntlrParser::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /home/lht/public_html/yeti/libraries/antlr/AntlrParser.php on line 98

Strict Standards: Declaration of Users::saveentity() should be compatible with CRMEntity::saveentity($module, $fileid = '') in /home/lht/public_html/yeti/modules/Users/Users.php on line 1642

Strict Standards: Declaration of Users::uploadAndSaveFile() should be compatible with CRMEntity::uploadAndSaveFile($id, $module, $file_details, $attachmentType = 'Attachment') in /home/lht/public_html/yeti/modules/Users/Users.php on line 1642

Strict Standards: Declaration of Users::insertIntoEntityTable() should be compatible with CRMEntity::insertIntoEntityTable($table_name, $module, $fileid = '') in /home/lht/public_html/yeti/modules/Users/Users.php on line 1642

Strict Standards: Declaration of Users::save() should be compatible with CRMEntity::save($module_name, $fileid = '') in /home/lht/public_html/yeti/modules/Users/Users.php on line 1642

Strict Standards: Declaration of Users::get_column_value() should be compatible with CRMEntity::get_column_value($columnname, $fldvalue, $fieldname, $uitype, $datatype = '') in /home/lht/public_html/yeti/modules/Users/Users.php on line 1642

Strict Standards: Declaration of Contacts::save_related_module() should be compatible with CRMEntity::save_related_module($module, $crmid, $withModule, $withCrmid, $relatedName = false) in /home/lht/public_html/yeti/modules/Contacts/Contacts.php on line 977

Strict Standards: Declaration of Vtiger_LanguageExport::export_Dependencies() should be compatible with Vtiger_PackageExport::export_Dependencies($moduleInstance) in /home/lht/public_html/yeti/vtlib/Vtiger/LanguageExport.php on line 17

Strict Standards: Declaration of Vtiger_LanguageImport::initImport() should be compatible with Vtiger_PackageImport::initImport($zipfile, $overwrite = true) in /home/lht/public_html/yeti/vtlib/Vtiger/LanguageImport.php on line 17

Strict Standards: Declaration of Vtiger_View_Controller::preProcessTplName() should be compatible with Vtiger_Action_Controller::preProcessTplName() in /home/lht/public_html/yeti/include/runtime/Controller.php on line 506

Strict Standards: Declaration of Install_Index_view::preProcess() should be compatible with Vtiger_View_Controller::preProcess(Vtiger_Request $request, $display = true) in /home/lht/public_html/yeti/install/views/Index.php on line 391

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/lht/public_html/yeti/libraries/antlr/AntlrLexer.php:297) in /home/lht/public_html/yeti/libraries/HTTP_Session/Session.php on line 160

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/lht/public_html/yeti/libraries/antlr/AntlrLexer.php:297) in /home/lht/public_html/yeti/libraries/HTTP_Session/Session.php on line 160`

**Comment by mariuszkrzaczkowski** [comment]
Make sure you set output_buffering = On

**Comment by LexPetkov** [comment]
Hi,
Thanks all.

@waw555 Added to the .htaccess file but now i get Internal Server Error. BTW the server is running PHP 5.4 so i changed the last line to "AddHandler x-httpd-php54"

@mariuszkrzaczkowski Yes, i have it set at "On"

**Comment by waw555** [comment]
This is my file, you it may be another, I showed your variables, including

`php_value error_reporting "E_WARNING & E_ERROR & ~ E_NOTICE & ~ E_DEPRECATED & ~ E_STRICT"`

**Comment by waw555** [comment]
Strict Standards 

It is precisely because of the version of php, and how the parameter is turned off, this error

**Comment by mariuszkrzaczkowski** [comment]
Check requirements
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.#server

> PHP 5.6 - works also fine with previous versions, i.e. 5.5.x (the latest versions are recommended).

**Comment by LexPetkov** [comment]
I've updated to PHP Version 5.6.21 still the same errors.

I have split @waw555 file into two. All "RewriteRule" is in htaccess and all the "php_flag/value" i have put in the php.ini

I am out of ideas

**Comment by paula-w** [comment]
The errors you see, Strict Standards for example, are caused by incorrect webserver configuration. It doesn't matter what and where you changed, because depending on the configuration, it requires settings in a different place. To make sure the server is well configured it's best to check the php configuration using php_info in the file where you install your system. You will see the current parameter configuration for the folder, and where these parameters are taken from.

We can help you solve the problems with your server, but it's a paid service.
