### ISSUE TITLE
Calendar - Hours displays incorrect after ajaxSave

### ISSUE THREAD

**Issue by playmono** [YetiForceCompany/YetiForceCRM#3032]
1/ When I create an event, date hour is wrong.
![sin titulo](https://cloud.githubusercontent.com/assets/1773174/15424778/c3c9840e-1e84-11e6-979a-dc508d8c2ad5.png)
![sin titulo2](https://cloud.githubusercontent.com/assets/1773174/15424798/d803a13e-1e84-11e6-9d6f-4c3a65b3f36d.png)
NOTE: When I refresh browser, hour displays correctly.

**Comment by paula-w** [comment]
Hi. 
You didn't give us any info about the version or configuration.
We checked 3.0 and it works as it should.

**Comment by playmono** [comment]
Has https://gitdeveloper.yetiforce.com or https://gitstable.yetiforce.com the last modifications?

**Comment by paula-w** [comment]
You're right, there's an issue there! 
My mistake, sorry :)
We'll take care of it, thanks a lot.
