### ISSUE TITLE
Notification error

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#3034]
![animation 189](https://cloud.githubusercontent.com/assets/1402355/15427454/aa7c678a-1eae-11e6-8b64-9a7892524e72.gif)

**Comment by KatarzynaUlichnowska** [comment]
Hello waw555, 
could you please check the notifications on gitdeveloper because there's been a lot of modifications related to this issue?
Additionally, it would be easier for us if you could make videos in the English version of gitdeveloper.

**Comment by rskrzypczak** [comment]
Notifications icon is refreshed more or less every 10 seconds.
