### ISSUE TITLE
Github error

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#3035]
![animation 190](https://cloud.githubusercontent.com/assets/1402355/15428022/7d358bfe-1eb2-11e6-87ff-50ff84615288.gif)

**Comment by TomaszQr** [comment]
Check it on the latest version, I could add a ticket with no problems. Also use the English version to record clips. I added support for HTML tags to a created issue.
https://github.com/YetiForceCompany/YetiForceCRM/commit/bf9adf1db27b5defa9bea4bf77c1983c30b3e030
