### ISSUE TITLE
Label error

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#3036]
How to return a shortcut back?

![animation 191](https://cloud.githubusercontent.com/assets/1402355/15428233/8fea347e-1eb3-11e6-8d32-9fef6e77ae36.gif)

**Comment by vovpff** [comment]
@waw555 Перетащи нужные ярлыки драгдропом из меню слева.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2649

**Comment by vovpff** [comment]
En: drag'n'drop needed shortcuts from menu on the left
