### ISSUE TITLE
Where is the free or paid for invoice template?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3037]
Hi,

I read in an earlier post about the future of yetiforce and there being free or paid for invoice templates. I am learning it at the moment, but getting a little stuck with the order of things and also creating an invoice template. Is there any kind of process flow chart that shows how the Marketing, Sales etc. should work? I.e. first create an Opportunity, next create a Quote, next create a Sales Invoice and so on ...

I am testing the different modules, and tried to create a Sales Order earlier, but it asks me for a calculation - I am not sure yet what this field is for or where its data comes from. So, I back track and see there is a module called Calculations in the Sales process. What is this for?

Sorry if I am being an idiot here, but I can't be the only one who doesn't understand how yetiforce new processes works. 

In addition, I am trying to create a basic invoice, and playing around with the inserting of labels and values, but all my outputs show only the code and no details. Are there any pointers as to how to create one?

Percy

**Comment by vovpff** [comment]
@PercyP You can add a lot of templates for different modules by yourself.
![invoice pdf](https://cloud.githubusercontent.com/assets/8545791/15429676/bb3be004-1eaa-11e6-850d-1bda983bdac7.gif)
At step 2 of Template creation you need to fill "Available in views" field. If this field are emply there is no  button appears in Module.
To made your style table and columns you need to add new .php file to \modules\Vtiger\pdfs\special_functions with function to get data from database. You can use ProductTableNew.php as sample.

**Comment by galciu** [comment]
Little correction: 
not step 2, but 3-5 or probably just  4 (not sure about that)

Is there any explanation what for are fields like:

- step1: additional name
- step2: name of generated file

- what format should be file to add a watermark (.jpg, .pdf .png doesn't works - maybe must be some special size?) (btw: text also doesn't show)

**Comment by PercyP** [comment]
@vovpff 

thank you for the demonstration. I still cannot get it to work. It just shows the code. We didn't have to do this in the 2.3.49 version, it was already there. In the news they said there would be one free and some paid templates, but I cannot find either. Al I want is a working invoice exactly like the old one in terms of a basic layout. Do you know where there might be a paid version just so I can use the system?

**Comment by vovpff** [comment]
@PercyP i don't understand what you need. Sorry. Let's explain
maybe your 2.3.49 ver has broken PDF module?

**Comment by vovpff** [comment]
@galciu I'm never not used watermark and can't advice you something.

**Comment by PercyP** [comment]
@vovpff 

sorry, I seem to be confusing you. What I meant was, in the old version of yetiforce 2.3.49 there was an invoice template already installed that was perfect for my needs - very simple layout. In the latest versions of yetiforce (I have 3.1) it does not come with an invoice template, so I cannot print invoices. I tried copying and pasting the code from the body content of the old invoice (on the 2.3.49 version of yetiforce) into the new system but it doesn't work (because it is a completely new pdf component). 

Yetiforce put out a message when they released version 3 and mentioned the changes to the new version 3 and that there would be a free invoice template and some paid template versions. I cannot find either and nor do they exist on the yetiforce demo site.

I basically just want a simple invoice template like the old one.

**Comment by vovpff** [comment]
@PercyP let's make it by ourself. It's very simple.

**Comment by galciu** [comment]
@PercyP I can't tell about Yeti v2 (because we are just trying it now)
What issue do You have?
Start with filling in step 4 this:

#ProductsTable#

And than You should have this icon for creating .pdf (like in presentation done by vovpff).
And it will create empty invoice with only table,
than go back to creator and add other fields that You need.

Let me know if that helped.
When I'll finish my invoice template I can share with You the code :)

**Comment by PercyP** [comment]
@galciu 

I think there is a bug in the pdf creator. I have managed to create a basic template - here is my code:

`<table border="0" style="line-height:20.8px;width:1101px;">
	<tbody>
		<tr>
			<td><span style="font-size:16px;"><span style="font-family:tahoma, geneva, sans-serif;"><strong><img alt="" src="cache/upload/images/mylogo.png" style="width:200px;height:95px;" /></strong></span><br />
			<strong>My Company Ltd</strong><br />
			<span style="line-height:20.8px;">My Company</span><br />
			London, UK<br />
			Tel: 01234 56789<br />
			Email: me@mycompany.com<br />
			Website: www.mycompany.com<br />
			Company No.: 12345&nbsp;<br />
			<span style="line-height:20.8px;">VAT No.: &nbsp;</span>&nbsp;<br />
			&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></td>
			<td>
			<div style="text-align:center;"><span style="font-size:16px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <strong>Invoice Reference Number: &nbsp;$number$&nbsp;</strong><span style="line-height:20.8px;text-align:right;"><strong>&nbsp;</strong></span></span><br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			&nbsp;</div>
			<br />
			<br />
			<br />
			<br />
			<br />
			<span style="font-size:16px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></td>
			<td>
			<div style="text-align:center;"><span style="font-size:16px;"><strong>Invoice Date<span style="font-family:tahoma, geneva, sans-serif;">:</span></strong><span style="text-align:right;"><strong><span style="font-family:tahoma, geneva, sans-serif;">&nbsp;</span></strong><span style="line-height:22.4px;">#CreatedDateTime#</span></span></span><br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			&nbsp;</div>

			<div><br />
			<br />
			<br />
			<br />
			<br />
			&nbsp;</div>
			</td>
		</tr>
	</tbody>
</table>

<div style="line-height:20.8px;text-align:right;"><span style="font-size:16px;"><strong>&nbsp;&nbsp;</strong></span></div>

<table border="0" style="width:100%;">
	<tbody>
		<tr>
			<td>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td>
			<td>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</td>
			<td>
			<div style="text-align:right;"><span style="text-align:right;"><strong>Invoice To:</strong></span><br />
			<span style="line-height:20.8px;text-align:right;">$accountid+Accounts+accountname$</span><br />
			<span style="line-height:20.8px;text-align:right;">$Company+organizationname$</span><br />
			<span style="line-height:20.8px;text-align:right;">$accountid+Accounts+addresslevel5a$</span><br />
			<span style="line-height:20.8px;text-align:right;">$accountid+Accounts+addresslevel3a$</span><br />
			<span style="line-height:20.8px;text-align:right;">$accountid+Accounts+addresslevel3a$</span><br />
			<span style="line-height:20.8px;text-align:right;">$accountid+Accounts+vat_id$</span></div>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td style="text-align:right;">&nbsp;</td>
		</tr>
	</tbody>
</table>

<p style="text-align:center;"><br />
&nbsp;</p>
<br />
#ProductsTableNew#<br />
<br />
<br />
&nbsp;
<table border="0" style="width:100%;">
	<tbody>
		<tr>
			<td style="text-align:center;"><span style="line-height:20.8px;">#TableDiscountSummary#</span></td>
			<td style="text-align:center;">&nbsp;</td>
			<td>
			<div style="text-align:center;"><span style="line-height:20.8px;">#TableTaxSummary#</span></div>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</tbody>
</table>
&nbsp;<br />
<br />
&nbsp;
<table border="0" style="line-height:20.8px;width:1101px;">
	<tbody>
		<tr>
			<td style="text-align:center;"><span style="font-size:16px;"><strong>Terms &amp; Conditions</strong></span>

			<div style="text-align:left;"><br />
			<span style="font-size:16px;">Unless otherwise agreed in writing by My Company Ltd, all invoices are payable within fourteen (14) days of the date of invoice. Our preferred method of payment is by BACS. Bank Account details for BACS payment: &nbsp; Account name: My Company Ltd Account No.: to be added Sort code: to be added.</span></div>
			</td>
		</tr>
	</tbody>
</table>
<span style="line-height:20.8px;">&nbsp;</span>`

I had to insert the terms and conditions manually, as unlike the old pdf creator, it doesn't seem to insert automatically any more. 

I have a second issue (raised in another post) in that the icon for saving or sending the pdf, that appears in record or list view, is only available to Administrators - regardless of what is put in the Permissions section at step 7 of creating the pdf.

Percy

**Comment by PercyP** [comment]
Apologies, I did use the insert code thing but its not added it correctly

**Comment by galciu** [comment]
After creating this template, you get icon for administrator, and than you
are able to make .pdf invoice?

PS
In permissions step don't put anything and than check.


Pozdrawiam
Bartosz Gala
+48 501 737 737

Pomyśl o środowisku naturalnym zanim wydrukujesz ten email / Please
consider the environment before printing this e-mail.

2016-05-25 9:04 GMT+02:00 PercyP <notifications@github.com>:

**Comment by PercyP** [comment]
@galciu 

Yes, it is only Administrator who can create PDF invoice after creating this template. 

I removed everything from permissions as you suggested, and as Administrator I can still see PDF icon, but as another user it still doesn't appear. I am at a loss as to why it won't show.

**Comment by galciu** [comment]
I have no idea :(

I've doubled checked my settings, and in step 7 (permissions) I have empty
field and other user than admin can generate .pdf.
step 6 also has empty fields (I know it's not related but just in case :)

Maybe try fresh install and see if than You'll be able to do it?




Pozdrawiam
Bartosz Gala
+48 501 737 737

Pomyśl o środowisku naturalnym zanim wydrukujesz ten email / Please
consider the environment before printing this e-mail.

2016-05-25 17:58 GMT+02:00 PercyP <notifications@github.com>:

**Comment by paula-w** [comment]
Hi,

**We strongly believe in our "one issue = one problem" rule, and we would like to ask all our users to follow that rule.** 

When it comes to your questions:
First of all, @vovpff gave you a great tutorial on how to create templates in the system. 
Secondly, processes are described here: https://yetiforce.com/en/user-documentation/sales-process.html. It's not completely up to date, but it should be enough.
If there's a module you don't want to use you can always disable the module and all the fields related to that particular module.
