### ISSUE TITLE
Import CSV not trigger vtiger.batchevent.save

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3038]
When import csv file, the event vtiger.batchevent.save isn't trigger.

In the file modules/Vtiger/views/Import.php at line 163, CREATE_RECORDS_BY_MODEL is set only for xml and zip, but csv there isn't.

`$viewer->assign('CREATE_RECORDS_BY_MODEL', in_array($request->get('type'), ['xml', 'zip']));`

It is reflected on file modules/import/actions/Data.php in line 346 

```
if($this->type){
	$entityInfo = $this->createRecordByModel($moduleName, $fieldData, $this->user);
	$handlerOn = true;
} else {
	try {
		$entityInfo = vtws_create($moduleName, $fieldData, $this->user);
	} catch (Exception $e) {

	}
}
```

in the same file condition at line 392 is always false:

```
if (empty($handlerOn) && $this->entityData) {
	$entity = new VTEventsManager($adb);
	$entity->triggerEvent('vtiger.batchevent.save', $this->entityData);
}
```

I could be wrong but in modules/Vtiger/views/Import.php at line 163 I would change the code:
`$viewer->assign('CREATE_RECORDS_BY_MODEL', in_array($request->get('type'), ['xml', 'zip','csv']));`

**Comment by rskrzypczak** [comment]
CSV import logic has not been changed.
The triggerEvent you mentioned will be executed while importing only when it's necessary to create records in modules related to imported one. 

While importing records from XML all handlers, workflow actions, etc are launched, everything that is launched while creating a record in the crm manually. 

CSV import always skipped these actions and it still skips them. 
It has its pros and cons.
We won't modify the CSV import anytime soon.
