### ISSUE TITLE
[PL] Problem z zapisem raportu typu wykres

### ISSUE THREAD

**Issue by wbnx** [YetiForceCompany/YetiForceCRM#3039]
Nie mogę utworzyć raportu typu wykres testowane na wersji dev i stable:

![raportwykres](https://cloud.githubusercontent.com/assets/14766421/15435946/8425b990-1ebf-11e6-8a27-84b0d146f7ec.gif)

Linki do logów z ustawieniami pliku debug i sposób odtworzenia błędu SCR2GIF:
http://yfdev.1crm.pl/raportwykres.gif
http://yfdev.1crm.pl/raportwykres_logs.zip

**Comment by konadrian** [comment]
Błąd nie występuje w obecnej wersji
![reports](https://cloud.githubusercontent.com/assets/3193498/16040853/9535a976-3232-11e6-8e57-3ea3411576dc.png)
