### ISSUE TITLE
[Feature Request] Calendar Real Day Number

### ISSUE THREAD

**Issue by vtechnik** [YetiForceCompany/YetiForceCRM#304]
![calendar_001](https://cloud.githubusercontent.com/assets/9847894/6409740/d3f1d1f2-be67-11e4-95c4-366677da7fe7.jpg)

Could it be possible to make the real day number instead the 10 calendar's icon.
(Today, it would be :  27)

**Comment by bpabiszczak** [comment]
It is only an icon, we don’t plan to show there a real day number, because there are different views (e.g. a week or moth view). We can only change the icon in the future, so it won’t suggest any specific day.
