### ISSUE TITLE
[bug] notification not show for  shared group or users

### ISSUE THREAD

**Issue by rezaizadi** [YetiForceCompany/YetiForceCRM#3041]
Hi,
After create a task and set shared for a "group" or "assign" to one group popup will not show.
i test a ver 3.0 and 2.3.49.
please check.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
unfortunately, we don't understand what the issue is. 
Please describe it again according to this article: https://yetiforce.com/en/developer-documentation/bugs/126-issues.html or make a video. Additionally, please verify if it also exists on gitdeveloper.
