### ISSUE TITLE
Unable to create invoice in yetiforce demo - says credit limit is exceeded

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3044]
Hi,

when trying to create an invoice in your demo site I get an error saying credit limit has been exceeded and it wont save. I went into the Company account and tried to add a credit limit and it wouldn't accept the value I entered. I did a Jing screen capture video to show you but it wont upload as is unsupported file type.

Percy

**Comment by vovpff** [comment]
@PercyP Let's try to change credit limit in system settings

**Comment by PercyP** [comment]
@vovpff 

I have gone through the system configuration and there does not appear to be a credit limit section. Personally I will never need to assign a credit limit, so would prefer to switch it off or at least make it none mandatory. Did you manage to find it under settings?

**Comment by PercyP** [comment]
I have now been able to create an invoice without error in yetiforce demo.

**Comment by witer30** [comment]
you have to switch off field of credit limit and it will work, as know it is not finish yet...

**Comment by mariuszkrzaczkowski** [comment]
There are two ways to disable limits:
1. Disable the limit field in Account
2. Disable checking limits in field configuration
![limit](https://cloud.githubusercontent.com/assets/10198654/15462086/614e92f4-20c0-11e6-9b06-c477616da58d.png)

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

thank you.

**Comment by densousuds** [comment]
muito obrigado,
Thanks a lot broth
