### ISSUE TITLE
Cannot delete PDF templates - delete icon doesn't work

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3045]
Hi,

I have also tested this in your demo. I created a test invoice pdf template and then tried to delete it using the delete icon. When clicked, it just opens the template in the edit view - there is no way of deleting it.

Percy

**Comment by PercyP** [comment]
I have just tested in your demo. This now works.

How do we get it to work in our own copy?

**Comment by vovpff** [comment]
@percyp you try stable ver 3.0 or 3.1 at your server. Lets try to ibstall latest dev ver.

**Comment by PercyP** [comment]
@vovpff 

I have version 3.1 which still takes me to edit rather than deleting
