### ISSUE TITLE
How to add Terms & Conditions in Invoice PDF template

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3048]
Hi,

I am trying to create a new Invoice template and trying to add the Terms & Conditions like in the old version of yetiforce. The following values were used inside the template:

#label_terms_conditions#:#terms_conditions#

But having gone through the various fields in the template I cannot find a value for terms and conditions. I have added the details via athe administrator section, but they don't show up on the invoices. I tried using the above but I am guessing it is different code now?

How do we add this?

Kind regards

Percy

**Comment by TomaszQr** [comment]
This functionality no longer exists in the PDF module, you can add it using special functions though. If you don't know how to do that we can do it for you, but we will have to charge you for that.
