### ISSUE TITLE
Create new module Error

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3049]
tested on: https://gitdeveloper.yetiforce.com   ver. 3.1.75

when create new module and click on save button, javascript return this error:

<b>Fatal error</b>:  Uncaught Error: Call to undefined function split() in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vtlib/Vtiger/Filter.php:157

possible solution:
http://code.vtiger.com/vtiger/vtigercrm/commit/db3ef7f986ab667ce9f7919a080eedfaad5dcb47
http://code.vtiger.com/vtiger/vtigercrm/commit/7ba54539b3d9a0b5fd2b782eb4c1a7cc660551c2

**Comment by mariuszkrzaczkowski** [comment]
The commits that you sent aren't a good solution, they only hide the problem, and the code is still outdated.
Currently we are working on cleaning up old functions from the code and PHP7 full compatibility.
https://gitdeveloper.yetiforce.com/ uses PHP7 therefore some difficulties might occur. Please report any errors that you may find.

**Comment by nic86** [comment]
I understand, I think your the best choice . I will inform you when I find compatibility issues.
