### ISSUE TITLE
[Feature Request] Little calendar to navigate to a day directly

### ISSUE THREAD

**Issue by vtechnik** [YetiForceCompany/YetiForceCRM#305]
Would'nt it be good to have an little calendar to go directly to another view?

Like that :
![calendar_002](https://cloud.githubusercontent.com/assets/9847894/6409902/c32b5850-be69-11e4-96ba-79d05e1c0f6f.jpg)

or that :
![calendar_003](https://cloud.githubusercontent.com/assets/9847894/6409907/ccced760-be69-11e4-941a-b43a419b0dd8.jpg)

**Comment by bpabiszczak** [comment]
It is a good idea. The new version [last on github] changed completely calendar, test it and let me know what we have to change.

**Comment by vtechnik** [comment]
My opinions: I find it was better with the coloured eventype like the image above (Events in green, to do in blue) and the couloured user's calendar...  The rest seems better.

I find there is a lot to do to make the calendar really usefull :
1) Quickcreate : 
 - add the contacts (with more then one contact possible) 
 - add description

2) Quickcreate and full form.

- add a different way to make a event/task related 
  to one or more organization (or no organization),
  and to one or more opportunity (or no opportunity)
  and an  one or more ticket (or no campain) 
  and...

Perhap's something individual for every module like the contact(s) choice field
(the choosen modules shoud be configured in settings)


3) Calendarview : 
- Click on an event that exist, should open something like that :
  http://www.vtexperts.com/extension/vtiger-calendar-popup-preview/

but with the existent multi-contacts, multi-opportunities...

- all tabs could be saved (single or in one shot)
  (an  example  : to change a phone number without going in the contact module...)
  a new tab could be added
  an existent tab could be deleted

- The one shot "save all" button shoud update all related to fields.
  event to organization(s), event to contact(s), event to ticket(s), event to opportunity...
  but also contact(s) to oppotunity, to tickets...

-  All  fields to edit in a tab shoud be choosen in settings...


4) Follow up :
- to follow up an event 
  you have only to add a follow up button like the "save all" button in the event tab.

- The follow-up button do not destroy the existent meeting
  but affect the new changements (made in the others tabs) on a new choosen date in the event tab.

- In the follow up event, you shoud have a link to the parent event (to navigate between the linked  events, directly on calendarview)

I don't know if i'm clear (english isn't my native language)

Here is my vision.

**Comment by bpabiszczak** [comment]
1. In the latest version of YetiForce CRM system there is a possibility to select colors for events as well as users. In the configuration there is a special panel to manage colors. Please have a look at it and maybe you will like it.

2. It will be possible to manage a few contacts when we create a new functionality for notifications [a possibility to add many participants and mark who accepted your invitation and who didn't]. I don't know yet when this will be available, but we will try to add it as soon as possible [in a few weeks]. We changed the logic in the new version of the system, an Event might be added to a company [Lead, Organization, Contact, Vendor, Employee] or to the process [Opportunity, Project, Ticket, Campaign, Service Contract]. We had to rebuilt loads of queries in many modules in order for this change to work properly. We hope that it will be a successful change. Unfortunately, we don't plan to bind calendar events with many processes, we consider it as illogical [however, we might be wrong].

3.Unfotunately, I don't understand what are the advantages of using vTiger Calendar Popup/Preview. What you wrote about this module and its changes is unnecessarily complicated for me. If you would like to come back to this issue, please describe what you would like to change in YetiForce.

4. As well as with point nr 3, I don't understand this one.

PS. The Calendar is developed and improved all the time, we added a few new elements :]

**Comment by rlstanek** [comment]
In accessing the test instance and the latest git version I am not finding where a user syncs the calendar to their preferred calendar. For example user B wants to sync his calendar with his Gmail calendar. Thank you in advance for your assistance!

**Comment by bpabiszczak** [comment]
https://test.yetiforce.com/index.php?parent=Settings&module=Dav&view=Keys&block=5&fieldid=77
