### ISSUE TITLE
Ticket Warning after update to 3.1

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3050]
After update to latest version with "upgrade packaged" in ticket view or when create a new tk, display this error.

LBL_NO_ACCOUNTS_IN_HELPDESK

![image](https://cloud.githubusercontent.com/assets/3030997/15474851/204d6290-20dd-11e6-8497-a6f4a844b92e.png)

**Comment by skramanzia** [comment]
I use uncheck "account" field in ticket module

**Comment by skramanzia** [comment]
I  need "hide" Account, but when i do it, appears the error messages

**Comment by paula-w** [comment]
Hi.
This is not an error, it's just a message. In this process we assume that the Account should be there. You can disable it in the configuration in this file: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/HelpDesk.php.

**Comment by skramanzia** [comment]
Thanks Paula!!
