### ISSUE TITLE
Error: Can' edit settings in Yetiforce 3.1 PBX Manager module

### ISSUE THREAD

**Issue by zwieja** [YetiForceCompany/YetiForceCRM#3053]
After click in edit button all I can see is loading circle and YetiForce hangs and I got this error:

jquery.min.js?s=1463658048:2 
Uncaught Error: Syntax error, unrecognized expression: {"success":false,"error":{"code":"LBL_NO_PERMISSIONS_FOR_THE_RECORD","message":"LBL_NO_PERMISSIONS_FOR_THE_RECORD"}}

In YetiForce 3.0 I haven't any problems with this module.

**Comment by nic86** [comment]
#2981 

in the file modules/PBXManager/models/Module.php at line 29 comment this line:

```
public function isPermitted($actionName) {
//if($actionName == 'EditView' || $actionName == 'CreateView')
//      return false;
//else
      return ($this->isActive() && Users_Privileges_Model::isPermitted($this->getName(), $actionName));
}
```

will activate the record editing and creating in the module call list(PBXManager).
Remove the comments after you configure the settings for asterisk if you want to disable this action in frontend.
