### ISSUE TITLE
PDF template not available to other users

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3054]
Hi,

I have created a new PDF template as Administrator, and now trying to print it for an invoice as a test user who has none administrator access. When I create an invoice, I do not see the Generate PDF icon. I have checked in roles and permissions and there isn't anything obvious in there. I also set the permissions during creation to both the Administrator and the new test user's profile. 

I have tested this on the yetiforce demo:

1. I created a new user called demo 2 with Board of Management role and password of Password1
2. I created an invoice template as Administrator and assigned permissions to Both Administrator and the Board of Management role. 
3. I logged out then in as demo2 Password1
4. I created a new invoice and saved
5. No icon to generate PDF or email

I am not sure if this is a bug or I have missed another crucial setting.

How do i correct this?

Percy

**Comment by vovpff** [comment]
@PercyP check step no.7
![image](https://cloud.githubusercontent.com/assets/8545791/15506788/9baaa304-21d1-11e6-8bac-f44a29ea220f.png)

**Comment by PercyP** [comment]
@vovpff 

I have tried adding everything from the select list under group permissions, then also tried just the user by name, then just by the user's group, then Administrator etc. and none of them result in the pdf icon.

I am sure I have overlooked something here?

**Comment by PercyP** [comment]
@vovpff

If I set the user to an Administrator, then the icon is visible. However, it is not good practice to give users Administrator rights. So I created a second copy of the PDF as the user (now with Administrator status) check the Invoice and it shows the icon. I de-select Administrator in the users profile, and again ncheck the Invoice and it is no longer visible. It would seem only Administrators can currently see the newly created PDF icon, which was the same problem I experienced in the yetiforce demo.

**Comment by vovpff** [comment]
Looks like bug

**Comment by PercyP** [comment]
Hi,

is there a short term fix I can apply just to get this working until yetiforce 3.2 is released?

Kind regards

Percy

**Comment by bpabiszczak** [comment]
Information for the developer [PL]: brakuje w kilku modułach w profilach akcji, dlatego nie działa.

**Comment by PercyP** [comment]
Any update on this? I am only starting out with yetiforce and using the Contacts, Organisations, Products, Services and Quote/Invoicing modules. At the moment I can't use it (yetiforce) because the invoices can't be printed / sent which is the most important for me.

I don't want to keep posting (annoying the developers) but just want to know if I can apply a fix until the new release comes. 

Percy

**Comment by vovpff** [comment]
@PercyP keep waiting. According @bpabiszczak comment Yetiforce crew now the cause of problem

**Comment by PercyP** [comment]
@vovpff 

thanks for responding - most appreciated.
