### ISSUE TITLE
Brak powiadomień - usunięty rekord

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#3055]
![powiadomienia](https://cloud.githubusercontent.com/assets/10506580/15504121/b7c40044-21bd-11e6-974f-805508ce33e3.PNG)

Po usunięciu jakiegokolwiek rekordu np ze zgłoszeń nie pojawiają się kolejne powiadomienia.
Testowane na ver. 3.1.0

**Comment by bpabiszczak** [comment]
Proszę opisać to bardziej szczegółowo jak wywołać to na gitdeveloper.

**Comment by zimart** [comment]
Mogę podpowiedzieć :) wystarczy skasować rekord z kalendarza - nie odznaczając najpierw powiadomienia... wtedy już tylko phpmyadmin... kasowanie z tabeli notification..

**Comment by epsilonsc** [comment]
Dodajemy nowy rekord np w zgłoszeniach a następnie go usuwamy.W powiadomieniach pojawi powyższy błąd na screenie.
Brak uprawnień.Rekord, który chcesz podejrzeć, jest usunięty.
Nie ma możliwości podejrzenia nowych powiadomień.

**Comment by mariuszkrzaczkowski** [comment]
Testowane na najnowszej wersji i błąd nie występuje, proszę sprawdzić na wersji   https://gitdeveloper.yetiforce.com
