### ISSUE TITLE
Moduł zgłoszenia - hasła

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#3056]
Witam dodając rekord w module haseł dla kontrahenta nie wyświetla się on w module zgłoszenia (zakładka hasła jest pusta) (podpiętego pod tego samego kontrahenta).
![hasla zgloszenia](https://cloud.githubusercontent.com/assets/10506580/15504462/6fa8db66-21bf-11e6-885f-c857e2e46d4a.PNG)

![hasla kontrahent](https://cloud.githubusercontent.com/assets/10506580/15504468/72df108e-21bf-11e6-95f3-ea0a9363f84d.PNG)

**Comment by bpabiszczak** [comment]
Należy dodać SELECT-a z domyślnym filtrem aby pokazywał te przypisane do kontrahenta w ticket z możliwością przełączenia na pełną listę.

**Comment by rskrzypczak** [comment]
Dodano możliwość zawężania listy haseł do powiązanych z kontrahentem.
![pass2](https://cloud.githubusercontent.com/assets/10221999/15845993/151b45c0-2c79-11e6-8ad2-6e0785576dcf.jpg)
