### ISSUE TITLE
Blank fields on report editor

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3058]
Hi,

I can't generate charts with the editor, but that's ok for detail report.

I got blank fields instead of my criteria
![image](https://cloud.githubusercontent.com/assets/1357727/15509913/879ce008-21d5-11e6-933c-56ff3a564f51.png)

Did anyone solved this?

**Comment by vovpff** [comment]
Looks like report are broken from ver 3.0.0

**Comment by PercyP** [comment]
@Raggazzoo @vovpff 

I too cannot create reports, I am using version 3.1. In both cases creating charts or tables I cannot select anything for Primary module - there is nothing there.

I tried to check in the yetiforce demo but reports doesn't appear as an option so I guess they are working on it?

Percy

**Comment by Raggazzoo** [comment]
I tried to install the developer, the master and the stable branches with no result...

The demo version reports module doesn't work on the three branches.

If it can help I used to see this problem on vTiger 6.4 when in click "modify condition" directly from the chart page.

**Comment by Raggazzoo** [comment]
Is it possible to replace the report engine by chart.js?

**Comment by ezbank** [comment]
I too, please fix
