### ISSUE TITLE
calDav sync problem

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3064]
Hi,

I try to sync calendars from YF to Oulook/Thunderbird but after adding the calDav link and entering the credentials I got no events or tasks in my calendar.

The caldav plugin is enabled because I can see it on my browser.

I also test with the `https://gitdeveloper.yetiforce.com/api/dav.php/calendars/demo/YFCalendar/` with no more result.

Thank's =)

**Comment by Raggazzoo** [comment]
It seems there is two differents calendars because on calendars/admin/YFCalendar I see my events create in Outlook or Thunderbird but not the events create on YF.

When I browse the DAV server I can't find the events create on YF.

Is it a way to configure the sabreDAV directory?

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/github/issues/126-issues.html
2. https://yetiforce.com/en/developer-documentation/engine/115-debugging.html

**Comment by mariuszkrzaczkowski** [comment]
I tested the integration of Outlook / Thunderbird / DAVdroid everything works, you need to give more information

**Comment by Raggazzoo** [comment]
I updated to 3.1.357 and now I get this on thunderbird
![image](https://cloud.githubusercontent.com/assets/1357727/16229314/5f6a6e8c-37bc-11e6-9ff1-f0310202244f.png)
When I enter the key generated by the DAV Integration module the authentification failed.

It's the last bug I have to resolve before launch Yetiforce in production!

**Comment by Raggazzoo** [comment]
On my calendar I got one event
![image](https://cloud.githubusercontent.com/assets/1357727/16229784/96364074-37be-11e6-8fa8-3202c0789525.png)
And he doesn't appear on the DAV configuration module.
![image](https://cloud.githubusercontent.com/assets/1357727/16229833/c81a0b48-37be-11e6-87c7-4e822abe023e.png)

I already try to modify the cron with no result.

**Comment by Raggazzoo** [comment]
I edited the config/api.php like this
![image](https://cloud.githubusercontent.com/assets/1357727/16229860/ed041700-37be-11e6-8b45-3f753e1385a6.png)

**Comment by mariuszkrzaczkowski** [comment]
I checked authorization, summing the quantity and everything  works fine.
You have to enable debugging and check the error messages in logs.
In order for CalDav and CardDav to work properly cron has to be working. 
if it doesn't display the quantity then something is wrong, it requires a deeper analysis of the problem on a version where the error occurs.
https://shop.yetiforce.com/en/17-support

**Comment by Raggazzoo** [comment]
I applied two things

chmod -Rvf 755 yetiforce_folder
chown -Rvf www-data:www-data yetiforce_folder

Can this have a link?

**Comment by mariuszkrzaczkowski** [comment]
This is not a problem with file permissions, check error logs

**Comment by Raggazzoo** [comment]
Ok thank's I will check that =)

**Comment by Raggazzoo** [comment]
I checked the debug file and I don't understand why my events don't appear in the YF web calendar.

On the web calendar I got one event
![image](https://cloud.githubusercontent.com/assets/1357727/16383310/e27d9124-3c84-11e6-9e01-cf4403d4cb37.png)
And on my outook I got two other events
![image](https://cloud.githubusercontent.com/assets/1357727/16383353/11097abc-3c85-11e6-875e-3e714b879006.png)

It seems there is two different calendars...

In the configuration module it seems that my outlook events are in YF
![image](https://cloud.githubusercontent.com/assets/1357727/16383377/2d0e73ac-3c85-11e6-9a19-fff6f2758d2d.png)

We can see these two events on the web interfarce of sabreDAV
![image](https://cloud.githubusercontent.com/assets/1357727/16383253/a9a5b48a-3c84-11e6-98f0-d796bb37106d.png)

Does anyone have the same issue?

**Comment by Protocorewebcreative** [comment]
Same issue here any answer to this yet I get the exact same issue?

**Comment by Protocorewebcreative** [comment]
?
