### ISSUE TITLE
Fields - Quick create -> Lead fields (bug) 

### ISSUE THREAD

**Issue by kerncore** [YetiForceCompany/YetiForceCRM#3065]
![image](https://cloud.githubusercontent.com/assets/4957937/15580536/c34b2518-2371-11e6-8651-f4dd363d1c50.png)

PHP Fatal error:  Call to a member function getId() on boolean in /var/www/YetiForceCRM-3.1.0/modules/Settings/Vtiger/models/MenuItem.php on line 105

**Comment by kerncore** [comment]
Fixed by updated setting MAIL from NULL to boolean=1.

**Comment by ezbank** [comment]
Hi. Please give more details. thanks

**Comment by konadrian** [comment]
Please read this article and add all the missing information we need to investigate your issue: https://yetiforce.com/en/github/issues/126-issues.html
