### ISSUE TITLE
upgrading ver. 2.3.909 to latest version

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#3066]
any suggestions on how to upgrade to latest developer version from 2.3.909?

**Comment by vovpff** [comment]
export from old ver. and import to new.

**Comment by jbmcclain** [comment]
is there an export feature for the data base within yeti force that i have not come across?

**Comment by rskrzypczak** [comment]
There's no option to update the CRM to the current dev version, but you can try updating it to the stable version using an update package ([link](https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%202.x.x/2.3.0_to_3.0.0/zip))
If you want to try it then it would be best to read this : [link](https://yetiforce.com/en/implementer/installation-updates/176-system-update.html)
In your case you'd have to change the value in \config\version.php to 2.3.1072 and download the right update package and install it. 
Then you download the next package from 3.0 to 3.1 and install it, etc.
