### ISSUE TITLE
[Type::Bug] [Type::Enhancement] Multiselect is not available for product selection when using popup window from Invoice or other modules.

### ISSUE THREAD

**Issue by dextras** [YetiForceCompany/YetiForceCRM#3069]
In original vTiger solution when you click "Select" button on the list of products when creating new invoice, you are able to select multiple products at the same time and add them to your product list.

In case of Yeticrm it is impossible. Why did you remove this very useful option?

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/206-system-development-ideas.html
