### ISSUE TITLE
[Question] PDFs

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#3071]
I would like to send a PDF to all Contacts related to a Project upon the closing of the Project.  Is this possible?  When I go into PDF designer, and use Project module, Contacts does not appear as a related module.  Any ideas?

**Comment by mykljohn** [comment]
@vovpff I saw your messages to Percy, any idea on doing this or what the problem is?

**Comment by vovpff** [comment]
@mykljohn I don't tested this function for this time.

**Comment by mykljohn** [comment]
@skramanzia The problem isn't the trigger, I'm familiar with them, it with creating the PDF itself.  I can't show the related table Contacts for the Projects module.

**Comment by vovpff** [comment]
My opinion. There is a lot of relation missed for PDF module now...

**Comment by mykljohn** [comment]
@skramanzia @vovpff @bpabiszczak Do you know how to add the relation for the PDF modules?  It obviously doesn't use the standard relation.

**Comment by vovpff** [comment]
@mykljohn This is possible by Yeti crew but need some time

**Comment by mykljohn** [comment]
ok, we can do them from the contact module in the meantime.  cheers

**Comment by KatarzynaUlichnowska** [comment]
You can use a new method from workflow to do whatever you need but it may require some programming knowledge. When you create this method, please send it to us, so it will become a part of YetiForce, and it would be best if you could add a possibility to configure it in workflow. We aren't currently planning to add this functionality unless someone orders and pays for it.

**Comment by mykljohn** [comment]
@ @KatarzynaUlichnowska Will do, but can you tell me where the related modules for PDFs is stored?
