### ISSUE TITLE
Chart report generate error

### ISSUE THREAD

**Issue by kerncore** [YetiForceCompany/YetiForceCRM#3072]
Reports_Detail_Js is not defined(anonymous function) @ ChartDetail.js?s=1464186962:10

**Comment by ezbank** [comment]
me too. please help. im use v 3.1.0

**Comment by Raggazzoo** [comment]
On the git developer version I got this
![image](https://cloud.githubusercontent.com/assets/1357727/15773894/d28f4b04-2979-11e6-9de6-07ba3e52ac22.png)

It is the same on local for me

**Comment by ezbank** [comment]
It is the same on Yetiforce 3.1.239
![nh ch p man hinh 8](https://cloud.githubusercontent.com/assets/19627226/15774721/07ce0ae8-29a8-11e6-83ec-589cec99c89a.png)

**Comment by immhub** [comment]
Same here,

Please help.

**Comment by immhub** [comment]
Can somebody help with this bug please ?

**Comment by ezbank** [comment]
help me please

**Comment by immhub** [comment]
ChartDetail.js:10 Uncaught ReferenceError: Reports_Detail_Js is not defined

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/324b1fe66fbcbc6d79cdd315b40fd587263235ef
https://github.com/YetiForceCompany/YetiForceCRM/commit/b5e83d5e3d529805c1a56957f31d74cbfbbcb9af
