### ISSUE TITLE
[PL][BUG] błąd JS przy próbie wyświetlenia faktur powiązanych z kontrahentem

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#3073]
Przy próbie wyświetlenia faktur/korekt (korzystając z zakładek w module kontrahenci) dostajemy błąd JS

Aktualna wersja gitdeveloper

`Error: Syntax error, unrecognized expression: {"success":false,"error":{"code":{"message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM  u_yf_fcorectinginvoice INNER JOIN vtiger_crmentity ON vtiger_crmentity.crm' at line 1","trace":"#0 PearDatabase->checkError() in include\/database\/PearDatabase.php(340): \n#1 PearDatabase->query() in modules\/Vtiger\/models\/RelationListView.php(270): \n#2 Vtiger_RelationListView_Model->getEntries() in modules\/Vtiger\/views\/RelatedList.php(49): \n#3 Vtiger_RelatedList_View->process() in modules\/Vtiger\/views\/Detail.php(471): \n#4 Vtiger_Detail_View->showRelatedList() in (): \n#5 call_user_func_array() in include\/runtime\/Controller.php(89): \n#6 Vtiger_Controller->invokeExposedMethod() in modules\/Vtiger\/views\/Detail.php(188): \n#7 Vtiger_Detail_View->process() in include\/main\/WebUI.php(220): \n#8 Vtiger_WebUI->process() in index.php(24): \n","query":"SELECT DISTINCT vtiger_crmentity.crmid, FROM  u_yf_fcorectinginvoice INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = u_yf_fcorectinginvoice.fcorectinginvoiceid LEFT JOIN vtiger_users ON vtiger_users.id = vtiger_crmentity.smownerid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid WHERE vtiger_crmentity.deleted = 0 AND u_yf_fcorectinginvoice.accountid IN (116)  LIMIT 0,20","params":false},"message":{"message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM  u_yf_fcorectinginvoice INNER JOIN vtiger_crmentity ON vtiger_crmentity.crm' at line 1","trace":"#0 PearDatabase->checkError() in include\/database\/PearDatabase.php(340): \n#1 PearDatabase->query() in modules\/Vtiger\/models\/RelationListView.php(270): \n#2 Vtiger_RelationListView_Model->getEntries() in modules\/Vtiger\/views\/RelatedList.php(49): \n#3 Vtiger_RelatedList_View->process() in modules\/Vtiger\/views\/Detail.php(471): \n#4 Vtiger_Detail_View->showRelatedList() in (): \n#5 call_user_func_array() in include\/runtime\/Controller.php(89): \n#6 Vtiger_Controller->invokeExposedMethod() in modules\/Vtiger\/views\/Detail.php(188): \n#7 Vtiger_Detail_View->process() in include\/main\/WebUI.php(220): \n#8 Vtiger_WebUI->process() in index.php(24): \n","query":"SELECT DISTINCT vtiger_crmentity.crmid, FROM  u_yf_fcorectinginvoice INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = u_yf_fcorectinginvoice.fcorectinginvoiceid LEFT JOIN vtiger_users ON vtiger_users.id = vtiger_crmentity.smownerid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid WHERE vtiger_crmentity.deleted = 0 AND u_yf_fcorectinginvoice.accountid IN (116)  LIMIT 0,20","params":false}}}`

**Comment by TomaszQr** [comment]
Błąd w aktualnej wersji już nie występuje
