### ISSUE TITLE
[PL] [Improvement] Products

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#3074]
Hej,

Z poziomu produktu proponuję  powiązanie do dokumentów magazynowych zawierających ten produkt. Natomiast na dokumentach magazynowych w zakładce szczegóły utworzenie hiperłączy do wylistowanych produktów.

pozdr.Remi

**Comment by bpabiszczak** [comment]
Nie wydaje mi się to istotne, ponieważ w zakładce produktów powstanie kilkanaście zakładek z których nikt nie będzie korzystał.
