### ISSUE TITLE
PDF Template Permissions - Bug or My Issue?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3076]
Hi,

I submitted an issue over a week ago now and wondered if the developers could tell me if this is a bug or a problem with my own settings?

https://github.com/YetiForceCompany/YetiForceCRM/issues/3054

I did re-create this problem in the yetiforce demo (as specified in the original thread).

Basically only administrators can see the Export PDF icon in list and record view.

Can you offer any insight into what the cause/solution is?

Kind regards

Percy

**Comment by skramanzia** [comment]
In PDF Templates remove any group members, like that.

![image](https://cloud.githubusercontent.com/assets/3030997/16019717/ca8cb55e-3180-11e6-8307-14666a52863d.png)

**Comment by bpabiszczak** [comment]
Duplicate: #3054
