### ISSUE TITLE
Portal....

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#3077]
Czy jest szansa aby w portalu działały moduły ofert i zamówień ?

**Comment by mojtabajml** [comment]
Is it possible to use vtiger customer portal with yetiforce?

**Comment by bpabiszczak** [comment]
@zimart 
Jak tylko ktoś nam to zleci :] Albo będzie czekało w kolejce do realizacji jak tysiące innych rzeczy... 

@mojtabajml 
Test this: http://gitdeveloper.yetiforce.com/portal/
Download here: https://github.com/YetiForceCompany/YetiForcePortal/releases 
Upload this patch: https://github.com/YetiForceCompany/YetiForceCRM/issues/2893
