### ISSUE TITLE
Documents 

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#3078]
How ukazayvat path to the file that is on file storage on the LAN?
p.s. The module rm / modules / Documents / Documents.php have $ filename = "\\ $ filename";
But after saving way to have /10.8.../filepath/filename.xls, instead //10.8.../filepath/filename.xls

**Comment by kjradv** [comment]
The very answer to the question: "double quotes"
Correctly: $ filename = "\\\\ $ filename";

**Comment by paula-w** [comment]
Hi,
we don't really understand your question. 
Also - in your second comment - do you mean you found the solution to your problem? 
if you still have the problem, please describe it in more detail.

**Comment by vovpff** [comment]
Sorry Yeti crew for Russian
@kjradv Напиши по русски, что ты хочешь спросить и в чем проблема? Я вот ничего не понял...

**Comment by kjradv** [comment]
I was talking about a link to the local file.
Since the indication of the type of fillets is necessary to specify four backslashes instead of two.

**Comment by bpabiszczak** [comment]
http://stackoverflow.com/questions/18246053/how-can-i-create-a-link-to-a-local-file-on-a-locally-run-web-page

**Comment by kjradv** [comment]
@bpabiszczak, Thanks, I figured out a long time and know the basic data.
