### ISSUE TITLE
Dodawanie nowego pola z wartością z modułu powiazanego

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#3079]
Scenariusz z gitdevelopera:
1) Dodaje nowe pole typu Wartość z modułu powiązanego w module Kontakty
2) Wybieram przykładowo Projekty i pole Budżet
3) Zapisuje i pole jest widoczne
4) Przechodzę do dodawania nowego Kontaktu - pola nie ma...
5) Wracam do Edytora pól - tam również pole zniknęło...

Bug, czy ja coś źle robię?

**Comment by amdziak** [comment]
Robię to dobrze i myślę, że jest to bug, czy coś robię źle?

**Comment by bpabiszczak** [comment]
a może jakieś logi?

**Comment by amdziak** [comment]
W logach czysto - sprawdzałem u siebie.
Podałem scenariusz z gitdevelopera a tam nie mam dostępu do logów...

**Comment by bpabiszczak** [comment]
W sumie prawidłowo, ponieważ ten mechanizm pokazuje pola tylko na widoku listy.... można to zmienić sobie w tabeli vtiger_fields i zmienić w jakich widokach pola ma być widoczne.
