### ISSUE TITLE
[Feature request] Filter Roundcube templates

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#308]
It is a nice and strong feature to be able to place complete (HTML )templates into mails but the 'template' button / list now shows all email templates. Lots of them not relevant. Would be nice to be able to filter the list.
Checkbox in the email template to make it visible in Roundcube or an option in Roundcube settings?

**Comment by bpabiszczak** [comment]
The templates module has be redeveloped. Please check a new version of the system because it has a possibility to filter templates depending on the view from which an email is generated.
