### ISSUE TITLE
Workflow - nie wylicza aktualizacji rekordu

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#3080]
Sytuacja wygląda tak:

1) Mam trzy pola (stworzone przeze mnie) o typie liczbowym dziesiętnym i chcę aby 3 się wyliczyło na podstawie 2 pozostałych
2) dodaje nowe zadanie Workflow dla modułu np Kalkulacje, z czasem wykonania Każdy zapis rekordu
3) dodaje zadanie bez żadnych filtrów
4) dodawanie zadania -> Aktualizuj rekord i tam wybieram pole 3 i daje wyrazenie pole 1 + pole 2

Po zapisaniu zadania i przejsciu do kalkulacji, dodaniu nowej kalkulacji nic się nie przelicza.
Na wersji przed 3.0 (nie pamiętam dokładnie numerku) to działało...
Aktualnie mam zainstalowaną wersję 3.1.150

**Comment by amdziak** [comment]
Nikt nie ma podobnego błędu?

**Comment by bpabiszczak** [comment]
ten sam błąd w tym samym momencie.... życzę powodzenia :D

**Comment by amdziak** [comment]
??

**Comment by amdziak** [comment]
To nie jest ten sam błąd(nie wiem czy to ta sama funkcjonalność co w #3079 ).
W logach nic nie ma.

**Comment by bpabiszczak** [comment]
Przede wszystkich istotne są szczegóły. Na przykład dodając zadanie na workflow istotny jest typ inaczej działa edycja rekordu a inaczej tworzenie rekordu dla systemu to dwie różne operacje. Po drugie nie ma nigdzie logów.... po trzecie nagraj filmik za pomocą screen2gif wywołując błąd na gitdeveloper.

**Comment by mariuszkrzaczkowski** [comment]
Testowałem aktualizację i wszystko działa poprawnie, brak dokładnych informacji jakie wartości ustawiona w zadaniu obiegu informacji "Aktualizuj rekord".
Ps. sumowanie działa tylko gdy w zadaniu aktualizacji wybierzemy typ "Wyrażenie"
