### ISSUE TITLE
 How to create a chart widget?

### ISSUE THREAD

**Issue by jjoloka** [YetiForceCompany/YetiForceCRM#3084]
Hi. Interested precisely chart sales funnel or other chart widgets?

**Comment by Raggazzoo** [comment]
It could be nice, I try to integrate a chart.js webpage on the Our Sites section.

It is not very convenient but I can display a lot of different chart..

**Comment by bpabiszczak** [comment]
1. Create chart in reports
2. Add new widget [type: chart] here: https://gitdeveloper.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67
