### ISSUE TITLE
[Type::Enhancement] A function for automatically writing the totals in words for Invoice

### ISSUE THREAD

**Issue by dextras** [YetiForceCompany/YetiForceCRM#3085]
In Poland it is a good practice to put the total sum to the invoice in numbers and in words. It is no longer required by law (from 2009), although it is still frequently used in practice.

It is quite easy to implement. The way I do it right now is to add a special function in /modules/Vtiger/pdfs/specialfunctions/ that is giving me the total in words in Polish. The same could be done in any language by writing the function accordingly. I am using the php implementation from: http://4programmers.net/PHP/FAQ/Jak_zamieni%C4%87_liczb%C4%99_na_jej_posta%C4%87_s%C5%82own%C4%85_ (in Polish). It works very well.

Maybe this functionality could be integrated into the main branch?

BTW. can you create a user forum, where such community enhancements/issues could be solved/discussed?

**Comment by paula-w** [comment]
Hi,

If you made a function that you find useful then you can always send it to us in a pull request (here's a short manual just in case - https://help.github.com/articles/using-pull-requests/). 
We appreciate all community contributions that we receive!

We decided to use GitHub to discuss ideas for improvements and new functionalities etc. We even made a special label for that – "Category::Discussion"
