### ISSUE TITLE
Calendar visibility

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3087]
Tested on: https://gitdeveloper.yetiforce.com   ver 3.1.241

1) create a user with subordinated role "Sales Department" and no admin

2) login with new user credentials and create an event with visibility "private" and show us "busy".

3) login with user higher role "Board of Management" and no admin. In calendar list view the event is appears right with subject "busy*" and no display other info but in graphical calendars view i can see the event subject instead of "busy*"

**Comment by rskrzypczak** [comment]
The feature you described was removed from YetiForce. There's no option to change the topic of a calendar event in any view.
