### ISSUE TITLE
[Feature request] Gantt view in Projects

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#309]
https://www.vgsglobal.com/extensions/downloads/vtiger-gantt-chart-extension-module/
Seems a very nice solution. Something similar in Yeti would be nice.

**Comment by mariuszkrzaczkowski** [comment]
We plan to add to the chart, we have two choices:
http://fullcalendar.io/timeline/
http://taitems.github.io/jQuery.Gantt/

**Comment by zebrahosting** [comment]
Hi Mariusz, first one looks more mature and clear. Bit more options too. Would be my pref.

**Comment by bpabiszczak** [comment]
We added this functionality to the latest version of YetiForce CRM. We will be testing it for the next two weeks, it you have any comments about a new version, please add them as a new issue.
