### ISSUE TITLE
date and time

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3091]
where date change in database format and inserted to database?

in vtiger DateTimeField.php file do this . but in yetiforce only display date  is convert in DateTimeField.php file but when i want to change date in database format and insert to databse  DateTimeField.php not working .

i want to chage date to jalaali in yetiforc.
i  get gregorian date from database and change it to jalaali and when i want to insert date to database change it to gregorian date.

**Comment by paula-w** [comment]
Modifying one of the key elements of the system is very dangerous without the proper knowledge on how to do it and what the consequences can be. We don't know anything about the format you mentioned, and what the differences are between this one and the one we know. This modification requires a ton of other changes, in displaying functions as well, and only a good programmer should change it, someone who understands the problem. 
We don't introduce changes like this for free.
