### ISSUE TITLE
[Type::Bug] [Type::Enhancement] Incorrect calculation of Totals and taxes in Invoice module.

### ISSUE THREAD

**Issue by dextras** [YetiForceCompany/YetiForceCRM#3092]
It is somehow related to the issue which I closed recently:  #3086. The problem remains but it is a little different.

Similarly as in #3086 : If you add many products to the invoice (I've got a list of 40), then add a discount of some sort (e.g. 15%). Then add tax of some sort (e.g. 8%). As a result you receive:

1) Two different Tax summations in your Invoice:
- Sum at the end of the list of products.
- Sum in the Table tax summary.

2) When you calculate the Total after tax (invoice brutto) assuming the tax given in the Table tax summary (sum of netto after discount + tax from the table), it will not give you the total after tax.

This problem is visible when you want to create PDF template for Invoice. There are two fields: which might be of interest (in polish version):
- Netto - gives you the sum of the netto(before tax and **before discount**) prices from the products given in the table,
- Brutto - gives you the sum of the brutto(after discount and tax) prices from the products given in the table,

From those two you are unable to create proper invoice template and as a result you are forced to create your own special pdf functions. This is what i did at least. It works but I used an ugly hack to do it :)

Anyway how it should be done to meet general needs:
In the Invoice module when creating PDF template we should have several fields available:
- total netto before discount (total before discount and before taxes - current "netto")
- total netto after discount (total after discount - currently not available)
- total brutto (after discount after taxes - current "brutto")
- total tax

"total netto after discount","total tax" and "total brutto"should be calculated in one of the ways according to the additional "switch"(from netto/from brutto/sum of unit) available in the Invoice module:
1) from netto:
- netto (per tax type) = sum of **netto** from the products table(per tax type); 
- total tax = sum[(sum of **netto** from the products table(per tax type)) x (tax type %)] - in the same way as the "Table TaxSummary" is calculated but with the rounding mentioned in #3086;
- total brutto = netto + tax;

2) from brutto:
- brutto = sum of sum of **brutto** from the products table(per tax type); 
- tax = sum[(sum of **brutto** from the products table(per tax type) x (tax type %) / ( 1+ (tax type %))]
- netto = brutto - tax;

3) sum of unit :
- brutto = sum of **brutto** from the products table(per tax type);
- tax = sum of **tax** from the products table(per tax type);
- netto = sum of **netto** from the products table(per tax type);

In each case the rounding should be done on a table row level before doing any summation.

[Here](https://drive.google.com/file/d/0B8wnn8AG8T3XVl9xOWZyaS1ROTA/view?usp=sharing) you will find an example in Excel of how I see all three methods of calculating taxes.

source: http://ksiegowosc.infor.pl/podatki/vat/faktura/697566,Metody-obliczania-kwoty-VAT-podawanej-na-fakturze.html (in Polish)

**Comment by mykljohn** [comment]
@dextras Question...have you gotten the Pricebook to work in Invoices?  it doesn't display for me and I'm wondering if I've missed something in setting it up.

**Comment by dextras** [comment]
@mykljohn I do not use Pricebooks in my organization but i can test them. I will come back to you soon.

**Comment by dextras** [comment]
@mykljohn Honestly I have no idea on how to use pricebooks in Invoices. I am not sure if currently it is possible. If i understand correctly you would like to use a pricebook's price to generate an invoice? If yes maybe it would be better to use Quotes? Then from quotes you should be able to easily generate an invoice. What is your use case?

I think it would be a great idea to implement a possibility of selecting a pricebook that should be used for particular invoice. Then depending on that selection product netto prices would be set accordingly.

**Comment by mykljohn** [comment]
The pricebook allows you to set up different prices for products depending on whatever category you specify.  we offer languages classes, with pricing based on whether weekdays or saturday, group classes or private,  etc.  so each category has the specific price.

**Comment by dextras** [comment]
I think a solution here to use different prices would be just to create several products with almost the same name but with different prices. In order to get the pricebooks to work in the way I wrote in the previous post some additional programming would have to be done. You could contact the yetiforce so they can implement it  (for $) or try to do it yourself. 

I think that such function could be easily added by first adding a new field to invoices: "Pricebook". Then you would have to change some javascript functions in layout folder to act appropriately, when adding a new produkt to the product list:

1) Check what is the current selection regarding pricebook.
2) If nothing then use price from product details.
3) if one of the pricebooks is selected:

   -- (a) if product exists in pricebook - use price from pricebook
   -- (b) if product does not exist in pricebook - use price from product details
4) finish

**Comment by mykljohn** [comment]
Yes, We may have to do that.  But the pricebook was great and worked in 2.3.  It was supposed to be working in 3.0.  I was thinking maybe I configured something wrong.

**Comment by dextras** [comment]
Ok ... I did not use 2.3.I have just checked how it works in vtiger. It turns out that there might be regression then if it worked in 2.3 but does not work in 3.1. Can you create a new issue with title [Type::Bug] [Regression] pricebooks do not work in 3.1 but they worked in 2.3 ? Then maybe somebody else will notice it.

**Comment by mykljohn** [comment]
thanks, I was just wondering if you had gotten it working.  I will pursue your suggestion.
