### ISSUE TITLE
[Type::Bug] GDN is mass editable after in accepted state

### ISSUE THREAD

**Issue by dextras** [YetiForceCompany/YetiForceCRM#3093]
To reproduce:
1. Create new GDN.
2. Change its state to accepted.
3. Go to the list of GDNs.
4. Use "select all" checkbox in the left top corner of the list.
5. Click on the yellow field "Select all Goods to Dispatch Note".
![image](https://cloud.githubusercontent.com/assets/7486027/15819277/8d0bf27e-2be2-11e6-977f-0e8eea8885d2.png)
6. Select Action -> Mass Edit.
7. Edit whatever you want.
8. Result?  Even Accepted GDN's are edited.

Expected result? Accepted GDNs are not selectable.

**Comment by konadrian** [comment]
You can create a filter that will select all records, whose status is different than "accepted", then select that filer, and then select all records.
![status](https://cloud.githubusercontent.com/assets/3193498/16044104/54d57c42-3243-11e6-9561-bc382860e581.gif)
