### ISSUE TITLE
mail chimp integration

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#3094]
would be great with mailchimp integration.
So on each contacts profile, it would be possible to select one or more newsletters lists via mailchimp API.

And then the contacts where automatically added to these lists in Mailchimp.

Do you have some documentation on how to create modules / plugins for Yetiforce?

**Comment by bpabiszczak** [comment]
About mailchip: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
About modules: we do not have any documentation, You can test here 

1. https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8
2. https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&block=2&fieldid=33
