### ISSUE TITLE
customer portal not display Tickets 

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3096]
in customer portal a ticket was created but then show a page only white  'NOT AUTHORIZED' message.
in  tickets list display nothing.but ticket was created.

**Comment by mojtabajml** [comment]
You should define account for portal user.

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/github/issues/126-issues.html
2. https://yetiforce.com/en/developer-documentation/engine/115-debugging.html
