### ISSUE TITLE
[Type::Bug] When creating invoice, the tax details are not taken from the product details

### ISSUE THREAD

**Issue by dextras** [YetiForceCompany/YetiForceCRM#3097]
When you create an Invoice and start adding products you have to manually set the taxes used for each product or at least use the "Global taxes" option to set one tax for all products in the invoice. 

The way it should work (at least this is the way it works in vtiger) is that the tax details are automatically taken from product details (VAT field). Then if you need other treatment you can change it manually.

**Comment by novateco** [comment]
the automatic calculation of global taxes on invoice (for example VAT), this feature is functional in 3.2 version? or i need click in button set for add the tax vat always on create invoices?

thanks

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/3c9dd72befb3e970a6e57bca3b93dd8838816419
