### ISSUE TITLE
recurrent invoices payment date

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#31]
Here is one missing admin item:
When an invoice is created automatically from sales-order. Only option is to select "payment due" to 30, 60 or 90 days.
I assume it is old vtiger setup that has no settings option to changes these numbers.

For recurrent paymens we need to reduce no of days:
A. 0 days (instant payment)
B. 8 Days
C. 1st of Next month

Or can someone tell me where to make this change directly from database?

Cheers

Jack

**Comment by MaciejStencel** [comment]
Fixed various bugs from vtiger engine when generating recurring invoice.
Invoices are generated only in business days, not on Saturday or Sunday. 

Fixed bug when going to next month would generate wrong month, ex. 2015-01-31 + 1 month is now last working day of february and not 2015-03-03. 

Fixed wrong generation of dates when the year is a Leap year. 

Added various new options for recurring future date or payment due date, which includes:
* +0 days (only in invoice due date payment selection)
* +1 day
* +7 days
* +14 days
* +21 days
* +30 days
* +60 days
* +90 days
* +180 days
* +360 days
* After 1 month
* After 3 months
* After 6 months
* After 1 year
* Beginning of next month
* End of next month
* Beginning of next quarter
* End of next quarter
* Beginning of next week
* End of next week
