### ISSUE TITLE
Cyrillic documents names

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3100]
I tested documents uploading to system. This is very nice but if you upload file what name contains cirillic names documents saves at storage folder at Yeti root with damaged names (encoding)

My sample:
- 179726_Р?С?С'Р?С?РёС?_РїРчС?РчРїРёС?РєРё_Р Р?Р?Р?Р РЎ.docx
- 179728_Р?С?С:_14_0217__Р Р?Р?Р?Р РЎ.pdf
- 179730_Р?С?С:_14_0232__Р Р?Р?Р?Р РЎ.pdf
- 179732_Р Р°С?С╪С'С'_С?С'Р?РёР?Р?С?С'Рё.xlsx
- 179734_Р?Р?Р>Р°.pdf
- 179736_Р?Р?Р>Р°.pdf
- 179738_Р?С?С'Р?С?РёС?_РїРчС?РчРїРёС?РєРё_Р Р?Р?Р?Р РЎ.docx
- 179739_Р Р°С?С?С╪С'С'_С?С'Р?РёР?Р?С?С'Рё.xlsx
- 179740_Р?С?С'Р?С?РёС?_РїРчС?РчРїРёС?РєРё_Р Р?Р?Р?Р РЎ.docx

How to solve it?

Maybe it is possible to made tranliteration?

Usual transliteration for Russian language is:

`ж=zh
ч=ch
ш=sh
щ=sh
ю=yu
я=ya
а=a
б=b
в=v
г=g
д=d
е=e
ё=e
з=z
и=i
й=y
к=k
л=l
м=m
н=n
о=o
п=p
р=r
с=s
т=t
у=u
ф=f
х=h
ц=c
ъ='
ы=i
ь='
э=e`

**Comment by paula-w** [comment]
Hi,
There's a special function to clear that - https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vtlib/Vtiger/Functions.php#L1531 
You can add the missing characters and send us a pull request.
I will mail you our Contributor Level Agreement with more info.
