### ISSUE TITLE
Ampps (softaculous) issue

### ISSUE THREAD

**Issue by JunyaB** [YetiForceCompany/YetiForceCRM#3101]
I am using yetiforce on [ampps ](http://www.ampps.com/)in windows 10. I have no remote access to the installation. does not resolve with ip or hostname all other app. installs I tried work fine.
So I tried a virtual machine this time I got the ip to resolve but not the hostname, hacking attempt error shows up after login with hostname. Am I missing something?

**Comment by vovpff** [comment]
Check your config\config.inc.php file at line what starts from `$site_URL`
There is must be real IP abress or hostname. Port if not usual 80. Example: `$site_URL = 'http://111.111.111.111:1234/yeti/';`

**Comment by JunyaB** [comment]
thank you it works
