### ISSUE TITLE
Is it possible to install the developer version over 3.1 or will this cause issues upgrading in future?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3104]
Hi,
would installing the developer version over 3.1 cause any issues both with installing it, and on ability to upgrade going forward? 

There seem to be many of the bugs fixed, so I am hoping it has corrected an issue I am having with Invoice permissions as we still can't export the invoice unless we are an administrator: https://github.com/YetiForceCompany/YetiForceCRM/issues/3054

My issue is now closed so I am assuming it might be fixed and so my thinking is to install the developer version to get the fix.

Any advice would be greatly appreciated.

Percy

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/implementer/installation-updates/176-system-update.html

**Comment by PercyP** [comment]
Hi thanks, but these are for the main updates, I think I am wondering if there are patch versions wherby we can install interim fixes.
