### ISSUE TITLE
Workflow Action "Send Mail" not working

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3105]
Hello,

The function "Send Mail" is not working in workflow. 
I use 3.1.300

![untitled](https://cloud.githubusercontent.com/assets/19652526/15968829/0f7f8094-2f36-11e6-90b0-8da83ea15bf4.png)

My SMTP server is working

**Comment by BlaqJaq** [comment]
I had the same issue in vTiger. I had to create a cron job to run every 5 min (15min is the preferred time). I have a cpanel so it was easy to set one up.

sh /home/**path-to**/cron/vtigercron.sh

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/github/issues/126-issues.html
2. https://yetiforce.com/en/developer-documentation/engine/115-debugging.html
