### ISSUE TITLE
[Type::Bug] [Regression] pricebooks do not work in 3.0 but they worked in 2.3 

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#3106]
pricebooks worked in 2.3 on Quotes and Invoices, stopped in 2.4 but I was told they would be working in 3.0.   Are they working and I'm missing something, or are they still pending?   [screenshot_2](https://cloud.githubusercontent.com/assets/11919990/15969651/8677a414-2ef6-11e6-9a1a-b5f29d4ab644.png)

**Comment by mykljohn** [comment]
@konadrian @bpabiszczak I have $patch_version = '20160518'
$YetiForce_current_version = '3.1.0' installed...I see this change is on $patch_version = '20160614'

Can I update to this now?  Is there an install patch available?

**Comment by bpabiszczak** [comment]
Only this https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x/3.1.0_to_3.2.0/zip 11 days ago.

**Comment by mykljohn** [comment]
Thanks.  I see if I can get there...is there another patch release for 3.1 planned?

**Comment by bpabiszczak** [comment]
soon...

**Comment by mykljohn** [comment]
Thanks...you guys are doing great work!
