### ISSUE TITLE
How to create new tab in module contacts ?

### ISSUE THREAD

**Issue by zwieja** [YetiForceCompany/YetiForceCRM#3107]
Like title says I would like to create new  tab in Contact module which show call  log per contact record from pbx manager in contact detail view. 
When I click on contact details called for example "qwerty" I would like to see call record tab in this contact in detail view

**Comment by paula-w** [comment]
Hi,
There is a tab for mobile calls already, and you can also use it for PBX Manager calls. 
You can add a new module at the module configuration level, and at the field configuration level you can add a uitype10 field (this field also creates a tab in its related module).
You can use vtlib as well : https://discussions.vtiger.com/index.php?p=/discussion/171378/how-to-create-ui-type-10-field-for-any-module-/p1
