### ISSUE TITLE
Nie działa autouzepełnienie adresu odbiorcy email

### ISSUE THREAD

**Issue by r0bertk** [YetiForceCompany/YetiForceCRM#3109]
Witam,
chciałbym, aby w roundcube działało autouzupełnianie odbiorcy, znajdujacego się w książce adresowej. Aby podcza wpisywania pierwszych liter w polu "Do" były podpowiadane adresy email (Tak jak to działa w outlooku).
Czy jest taka opcja?

**Comment by bpabiszczak** [comment]
Domyślnie taka funkcjonalność jest włączona [musi działać cron]. Dane są pobierane z kontaktów, kontrahentów i chyba leadów. Na pewno będziemy dodawać jeszcze pozostałe [np. pracownicy].
