### ISSUE TITLE
email sent did not relate to lead

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#311]
I created a lead. Then clicked sent email from the lead. The email was sent. But when I go back to the lead the sent email is not under the emails tab. Under summary.

Is there something else I need to do?

**Comment by bpabiszczak** [comment]
You need to use and active mail scanner: http://dev.yetiforce.com/1_3_160/index.php?module=OSSMailScanner&parent=Settings&view=index&block=8&fieldid=44
