### ISSUE TITLE
invoice  pdf

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#3110]
When generating invoice pdf using "#ProductsTableNew#" the table heading are not part of translation system.

See here: http://www.screencast.com/t/RVsch6UgoE

I have searched the translation system in both "invoice" and "pdf" modules. But theadings like:
- Item name
- unit
-subunit
- quantity
- unit price 
etc.
are not to be find.

Can can you point how to translate, or where to find these in the source?

Using yetiforce 3.1.0

**Comment by skramanzia** [comment]
Hi, check in " Software configuration > System tools > Language Management". "Edit Language Tab", use module like "vTiger".

![image](https://cloud.githubusercontent.com/assets/3030997/16016843/5c446ebe-3173-11e6-8703-b16b2ee33a2b.png)
