### ISSUE TITLE
Sales Order/Quote Discount Question

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3111]
I can not apply discounts. 
![image](https://cloud.githubusercontent.com/assets/3030997/16012992/26b5afee-3162-11e6-8891-a4aa0973da9f.png)

![image](https://cloud.githubusercontent.com/assets/3030997/16013014/35ead4e4-3162-11e6-94d6-0666dbe683a5.png)

Click on SET
![image](https://cloud.githubusercontent.com/assets/3030997/16013025/443d51f2-3162-11e6-8968-983cfa3fb422.png)

![image](https://cloud.githubusercontent.com/assets/3030997/16013035/4d9d25ce-3162-11e6-8648-5ad5b1e4249c.png)

![image](https://cloud.githubusercontent.com/assets/3030997/16013052/61c38e3a-3162-11e6-8ba7-5174afee4725.png)

Thanks!

**Comment by skramanzia** [comment]
@bpabiszczak can you help me?

**Comment by konadrian** [comment]
Can you try to  show me that error on http://gitdeveloper.yetiforce.com/
![animation](https://cloud.githubusercontent.com/assets/3193498/16107829/279211de-339f-11e6-9611-7d3007792af5.gif)

**Comment by skramanzia** [comment]
@konadrianI tested In your gitdev Lab and discounts work fine. Do you know if a release improvement? i use version "ver. 3.1.0" and your lab is "ver. 3.1.330".
