### ISSUE TITLE
invoice item comments gone

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#3113]
Invoice pfds the "ProductTableNew" has some issues.
most important is that product comment is missing.

1. first column in pdf should be left aligned.
2. the products comments are not added to pdf anymore.

3. would be great to adjust the total area to be more clean
4. too many columns, maybe we could make a ProductTableNewSlim with showed columns.

please see here:
http://www.screencast.com/t/L3VdnYmiudL

**Comment by vovpff** [comment]
Function "ProductTableNew" is editable by system admin and you can modify https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Vtiger/pdfs/special_functions/ProductsTableNew.php as you need or add another one. There is a simple sample of this product table.

**Comment by skramanzia** [comment]
@lalord if you need remove some columns, try remove field in advanced block.


![image](https://cloud.githubusercontent.com/assets/3030997/16050766/3cb21d74-3233-11e6-91d6-4c235479ed92.png)
