### ISSUE TITLE
Producttable

### ISSUE THREAD

**Issue by sherirao** [YetiForceCompany/YetiForceCRM#3114]
Hi
While creating Quote template for PDF  I dont know where to go to edit this table (producttable)
I want to remove colums like subunit
2- purchase
3- margin % etc

Please help

**Comment by vovpff** [comment]
Same as #3113. If you establish server with YetiForce you can manually change code of ProductTableNew fuction here https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Vtiger/pdfs/special_functions/ProductsTableNew.php 
For this time there is no possibility to change this table from GUI.
