### ISSUE TITLE
[PL] [BUG] copy and paste

### ISSUE THREAD

**Issue by Remi007** [YetiForceCompany/YetiForceCRM#3115]
Edycja np. produktu lub projektu. Nie ma możliwości wklejenia wartości przechowywanej w schowku systemowym do pól poza polem "Edytor WYSIWYG" 
testowane na ver.developer 3.1.310 (problem nie występował w v 2.3.49 i chyba w 3.0)

**Comment by konadrian** [comment]
Próbuję wywołać ten błąd - bezskutecznie. Być może była włączona opcja blokowania wklejania. Poniżej przedstawienie jej działania
![animation](https://cloud.githubusercontent.com/assets/3193498/16072324/94d4b0cc-32e0-11e6-8633-2a6fb72b1efa.gif)

**Comment by witer30** [comment]
o ile dobrze pamietam zostaly wprowadzone zabezpieczenia kopiowania itp ktore wlacza sie w panelu sterowania... poszukaj moze masz aktywne 
                
              
               
                 
                  Dnia 14 czerwca 2016 22:30 Remi &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   Edycja np. produktu lub projektu. Nie ma możliwości wklejenia wartości przechowywanej w schowku systemowym do pól poza polem &#34;Edytor WYSIWYG&#34;   
testowane na ver.developer 3.1.310 (problem nie występował w v 2.3.49 i chyba w 3.0)

**Comment by Remi007** [comment]
Ok, faktycznie @konadrian, @witer30 mają rację. Test robiłem na demo https://gitdeveloper.yetiforce.com i ktoś pewnie włączył blokadę ;) . Sprawdziłem dzisiaj - brak blokady i wklejanie działa. Temat do zamknięcia - dzięki Wam za szybką reakcje :)
