### ISSUE TITLE
[Enhancements] Update Languages

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#3116]
A nice feature would be if on the update, it didn't overwrite the language files....if it could some how append them or, maintain custom language files so that they don't get overwritten each update.

actually, that would probably be an easy way to go for customization. Have 2 language files for each module, the primary (set by YF) and the addendum for customized labels.  and then just append the custom file to the end of the language file.  Just an idea.  :)  Good luck guys...you're doing great work!

**Comment by skramanzia** [comment]
@mykljohn You can export and Import Languages,if you lose changes after update . Check this area.

 Software configuration > System tools > Language Management > Start

**Comment by mykljohn** [comment]
Yes I know, but that's just a pain :)  and then you still have to manually add any changes.

**Comment by mariuszkrzaczkowski** [comment]
Custom modification mechanism already exists. see the documentation (at the bottom)
https://yetiforce.com/en/developer-documentation/engine/177-loader-and-autoloader-of-files.html
