### ISSUE TITLE
[problem] Update

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#3117]
@bpabiszczak Hey, I have a problem...I tried to update to the version you messaged me but it didn't work (returned to menu and nothing).  When I refreshed, I got a 500 error :+1: 

The www:mysite.org page isn’t working

www.mysite.org is currently unable to handle this request.
HTTP ERROR 500

Nothing in the error log, so I restored the backup I made, and still no go.  Any idea why?  The backup should have at least set the server back to where it was before (I made the backup immediately before doing the update.

**Comment by skramanzia** [comment]
@mykljohn please check this Server requirements documentation.

https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by bpabiszczak** [comment]
Check this: https://github.com/YetiForceCompany/YetiForceCRM/issues/2185
