### ISSUE TITLE
Implement Sales Funnel

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3119]
Hello,

How can i implement a sales funnel widget on homepage?

**Comment by ezbank** [comment]
yeah. i want it.

**Comment by MexasPT** [comment]
Me too! :)

**Comment by immhub** [comment]
Vtiger 6.4, allready has the Funnel implemented as a widget, and it has filters and diferent tipes of customization. 

Please help.

**Comment by ezbank** [comment]
Widget Sales comparison by user dont work.

**Comment by natpicone** [comment]
+1

**Comment by bpabiszczak** [comment]
1. Add chart in reports.
2. Add widget [type: chart] on homepage https://gitdeveloper.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67

**Comment by MexasPT** [comment]
Can you explain to me ?

**Comment by immhub** [comment]
I have 3.1.300 installed, what do i have to do, so that "chart" apears in widget management?

**Comment by MexasPT** [comment]
Please....

**Comment by TomaszQr** [comment]
![charts](https://cloud.githubusercontent.com/assets/14273211/16257248/8daa4c22-3857-11e6-8f9b-9ba6ac51c45f.gif)

**Comment by immhub** [comment]
Thank you very much, but in my version 3.1.300 this does not works.... i copied the 17 fiels that have been modified, but still no success

**Comment by paula-w** [comment]
In a few days we are going to release v3.2. You'll be able to use this mechanism after the update.
Release dates available here : https://github.com/YetiForceCompany/YetiForceCRM/milestones

**Comment by immhub** [comment]
Thank you very much Paula.

Will the update contain a sales funnel like the one in vtiger?

**Comment by paula-w** [comment]
You're welcome.
The sales funnel won't be exactly the same as the one in Vtiger.
