### ISSUE TITLE
Can't add service to a quote

### ISSUE THREAD

**Issue by offerlam** [YetiForceCompany/YetiForceCRM#312]
Hi all,

I have created 4 services and are now trying to add one of them to a quote which also have some products to it.

I can't.. i get this error:

![udklip](https://cloud.githubusercontent.com/assets/5847757/6437595/3afeacf2-c0c1-11e4-9743-b8587ef0dbad.PNG)

**Comment by offerlam** [comment]
oh it happens when i search with blank to get all the service up. And it happens no matter what group i search in or if i try to search on text

**Comment by MaciejStencel** [comment]
I have tried to replicate Your problem but without success. On my end everything works ok. 
It was tested on newest yetiforce revision 1.3.95 RC

I've created few services, added them to quote and saved.

Can You write some more info, for example what revision are You using?

**Comment by offerlam** [comment]
If i make a new quote and start with service it works.. but if make a new one and start with a product i get the error...

where do i see the revision?

**Comment by MaciejStencel** [comment]
You can find it under /config/version.php

Line #13: $YetiForce_current_version = 'x.y.zz';

**Comment by offerlam** [comment]
$patch_version = '20150120';
$YetiForce_current_version = '1.2.0 RC';
$_SESSION['yetiforce_version'] = $YetiForce_current_version;

**Comment by MaciejStencel** [comment]
It is highly advised that advised that You will update crm to 1.3 using our update module.
Backup all files and database and update. Update should work perfectly and You will get rid of that error.

We try to do such update packages that will smoothly upgrade crm. Give it a try.

**Comment by offerlam** [comment]
what is the backup procedure? just overwrite the originals with the new ones or?

**Comment by offerlam** [comment]
sorry i ment update procedure

**Comment by waran70** [comment]
Just install update like other modules. You will see update history in the System Settings/About YetiForce/Updates

**Comment by offerlam** [comment]
im sorry this is the first time i play around with yeti force... so i have no experince how to update like other models

**Comment by bpabiszczak** [comment]
Use these packages update: https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%201.x.x
Install them using the Module Manager in the control panel in CRM. Soon on our website will be manual. Follow us on twitter: https://twitter.com/YetiForceEN we write when the manual will be ready.
