### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '=) )) AND vtiger_leaddetails.leadid > 0 ORDER BY modifiedtime DESC LIMIT 0,21' at line 1

### ISSUE THREAD

**Issue by rezaizadi** [YetiForceCompany/YetiForceCRM#3120]
ver 2.3.49

not work "greater or equal " for filters.

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/implementer/installation-updates/176-system-update.html
2. Please update your system to the new version.

**Comment by rezaizadi** [comment]
Hi
How can use "greater or equal" at filters without update version?
