### ISSUE TITLE
invoice - services issues

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#3121]
When creating new invoices with several services "product" rows. First row is not stored upon saving.

when edit invoice and add new "service" row, first row is saved successfully.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by vovpff** [comment]
This is a real bug!
![3121](https://cloud.githubusercontent.com/assets/8545791/16129300/f2e43b24-340c-11e6-9412-a3a4a8285f95.gif)
