### ISSUE TITLE
create new invoices - services autocomplete

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#3122]
When adding new services to invoices, the search / autocomplete feature is not working.

You have to click on "magnify" icon so search in popup for service to add to invoice.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by vovpff** [comment]
What version? Let's see gif at #3121 There is no problem with autocomplete. Your trouble can apperars if you imported some service records data to system. If you really imported data lets try to click "Ubdate labels" for services
https://gitdeveloper.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=13&fieldid=56
