### ISSUE TITLE
invoice - product rows description missing in pdf

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#3124]
the invoice "product row" the  description is no longer added to invoice pdf product-table.
Is there a way to fetch this information to add into table?

**Comment by dextras** [comment]
Which field from product row do you mean as "product description"?

**Comment by lalord** [comment]
please take a look here from yetiforce 2.49 invoice product/service table.

http://www.screencast.com/t/ErL9NnCD2

**Comment by dextras** [comment]
In general the only way to modify the contents of the product table is to change the ProductsTable special pdf function. You will find it in /modules/vtiger/pdf/specialfunctions/.......
