### ISSUE TITLE
delete all invoices - DB

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#3126]
the invoice DB structure is completely rewritten from vtiger. 
I can see that deleted invoices from GUI are not deleted in DB.

How to delete all invoices and related data in order to re-import from older yeti versions or vtiger.

DB table 	"u_yf_finvoice" contains the actual invoice information except product/services information.
But no information is defining if the actual invoice has been deleted.

Which tables should be truncated in order to clean yeti invoices?

**Comment by rskrzypczak** [comment]
try to use  [Recycle Bin](https://gitdeveloper.yetiforce.com/index.php?module=RecycleBin&view=List&mid=145&parent=0)

**Comment by lalord** [comment]
sounds like a good idea :)

Where is it located?

**Comment by rskrzypczak** [comment]
You have to add this module to [menu](https://gitdeveloper.yetiforce.com/index.php?module=Menu&view=Index&parent=Settings&block=2&fieldid=40)

**Comment by lalord** [comment]
Recycle bin flush did not solve it. Recycle bin do not remove deleted invoices from db.

**Comment by lalord** [comment]
which tables can be emptied to completely remove all invoice data?
