### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by BlaqJaq** [YetiForceCompany/YetiForceCRM#3128]
Hello,

I am new to YetiForce and not sure if this is where my question goes. I noticed the google map is not available as it is in vTiger.

![google map widget](https://cloud.githubusercontent.com/assets/19979297/16125144/5043c8e0-33c0-11e6-9e8a-0028dda049ff.PNG)

Is there a way to get this feat back.That would be extremely useful. 

Thank you.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/206-system-development-ideas.html

**Comment by bpabiszczak** [comment]
This feature can't be added to YetiForce because the Google Maps license doesn't allow for that.

**Comment by StaggerLeee** [comment]
@bpabiszczak can you explain it a bit more ? Thanks.

As I know WordPress backend can be full of different Google Maps and nobody makes problem about it..
You install one plugin and suddenly all Posts even if there are hundreds of them have one Google map, in backend and frontend. But here is backend more interresting to compare it with YetiForce.

**Comment by paula-w** [comment]
Google maps can only be used if the map is publicly available, and in case of YetiForce it's not possible. We have integrated GoogleMaps  in YetiForce, but only in a form of a link with the location that directs you to GoogleMaps.
What you are trying to achieve can only be done using GoogleMaps commercial license or OpenStreetMap.

**Comment by StaggerLeee** [comment]
Ok, thanks for answer. But have to say I dont get it.
Then WordPress is breaking Google Terms because WP backend is not accessible to public.

**Comment by paula-w** [comment]
We might be wrong. 
If you ever stumble upon the license and have some time to read through it, you can check it and later let us know. Some regulations might have changed.

**Comment by witer30** [comment]
well, salesforce.com is using GoogleMaps and it is not public as well....

**Comment by bpabiszczak** [comment]
Maybe they purchased licenses? I think they can afford?

**Comment by StaggerLeee** [comment]
Seems as it is OK. Just ask them and you will be granted permission.

- Your project is publicly there to download and inspect code.
- You dont charge for project.

Just send them a message with all links to project and they will grant you allowance.


> **Can I use Google Maps in my non-Web application?**
> Yes, the Google Maps APIs can now be used in desktop applications, provided that they adhere to the other restrictions of the Terms of Service. Note that in order for a desktop application to be deemed "publicly accessible", **there must be a publicly accessible webpage from which it can be downloaded**. See Section 9.1 of the Terms of Service for more information.
> 
> The Google Maps JavaScript API is only supported when run in one of the supported browsers.

> **Can I use the Google Maps APIs on a site that is password protected?**
> Yes, you can, though you should consult the Terms of Service before using the Google Maps APIs on a password protected website. **If consumers can easily sign up for a password without charge** or if the purpose of the password protected map is to enhance the publicly available map (ie. administration), then your site is likely within the Terms of Service. If this is not the case, you will need to use Google Maps APIs Premium Plan.

**Comment by KatarzynaUlichnowska** [comment]
There seemed to be no clear answer, so we analyzed the license and spoke with Google. 
Systems such as CRM or ERP need to buy a license even if they are open source.
