### ISSUE TITLE
Invoice Status

### ISSUE THREAD

**Issue by sherirao** [YetiForceCompany/YetiForceCRM#3129]
In vtiger we had sent credit and paid status etc. I wonder how to add same status in invoice and how marking invoice to status PAID will affect accounting module (entry) ? Please advise

**Comment by waran70** [comment]
Why dont you try it yourself?

**Comment by vovpff** [comment]
@sherirao Let's check it by yourself.
https://gitdeveloper.yetiforce.com/index.php
