### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by MexasPT** [YetiForceCompany/YetiForceCRM#3130]
I deleted unintentionally button to create new products and now I do not know what changed to appear again.

![add product](https://cloud.githubusercontent.com/assets/17734465/16145712/08a741e4-3472-11e6-9eef-cd7b56e89360.jpg)
Quotes module.

Can you help me?

**Comment by bpabiszczak** [comment]
Check the permissions of the module:
1. https://gitdeveloper.yetiforce.com/index.php?module=SharingAccess&parent=Settings&view=Index&block=1&fieldid=5
2. https://gitdeveloper.yetiforce.com/index.php?module=Profiles&parent=Settings&view=List&block=1&fieldid=3

**Comment by WhyNotCrazyTrain** [comment]
Same problem, can't fix through permissions tweaking.
@MexasPT Did you solve it?
