### ISSUE TITLE
[BUG] Unable to select Opportunities in Email workflows

### ISSUE THREAD

**Issue by acidhunter** [YetiForceCompany/YetiForceCRM#3131]
In latest dev we are unable to select Opportunities & Contacts in email workflow editor

We need to send emails with opportunities, organisations and contacts at once

**Comment by bpabiszczak** [comment]
https://wiki.vtiger.com/index.php/Invoke_Custom_Function

**Comment by acidhunter** [comment]
Sry but my description was not clear enough
There are no fields from the opportunities module
In old versions we was able to select fields from all modules, so i think its a bug

When i create a Workflow for opportunities i only get Field from Type Contacts & Organisations
![image](https://cloud.githubusercontent.com/assets/8077558/16196484/77b9e3be-36fe-11e6-8e4a-8e75a9aaa121.png)

![image](https://cloud.githubusercontent.com/assets/8077558/16196562/c5f69a40-36fe-11e6-8a17-d7b7a7839e93.png)

**Comment by ralphkretzschmar** [comment]
Hello everyone - it seems that there was a small missunderstanding so i included a video for you and hope to make it clearer.

in the video we try to setup a workflow for OPPORTUNITIES which sends a email with content from CONTACT-Fields.

Best regards Ralph

![animation](https://cloud.githubusercontent.com/assets/12951699/16485625/40d119de-3ec0-11e6-9495-df87d8c683fa.gif)
