### ISSUE TITLE
Future functionality changes 

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#3135]
Hi, wondering if you guys (Yetiforce) planning to introduce some radical changes to the current state?
The answer I need is to understand level of risk of building serious system over the Yetiforce.
The most important will be inventory management as plan is to add accounting modules
creating environment for managing couple of hundreds of accounting clients (with all related accounting records). Appreciate clarification on this matter

**Comment by bpabiszczak** [comment]
Unfortunately the question isn't precise enough and it will be hard to give you an answer. 
"Radical changes" mean something else to everyone. YetiForce is the fastest developing open system in the world, we introduce changes to the system everyday, sometimes minor fixes, sometimes major functionalities. If someone wants to use a system that doesn't introduce any changes then the best choice would be coreBOS or Vtiger, they haven't really changed anything for the past 2 years. 

You want to develop mechanisms that we will sooner or later develop anyway, so the best idea would be to either order these features from us, or to work with us on these features. Otherwise these changes might collide with each other, which will case the standard update packages not to work properly and require a ton of modifications.

**Comment by SkavenKF** [comment]
Hi, a question about the 3.0 LTS (long time support) Version. The Patches for this version are the monthly releases (without functionally changes, see #2881), is this correct? 
If so, what are the next Ideas, Moduls,Funktionally changes, etc. for Version 4.0?

excerpt from  #2881 
> ● ● ● LTS ● ● ●
> The 3.0 version is marked as LTS [Long-term support], which in practice means that for 12 months we will release critical fixes for the system. It concerns only fixes related to security issues and problems with using all the tools available in the system.
> Unfortunately the LTS version does not mean that we will fix everything, like change statuses because they are incorrect, automate processes that have not been automated, or improve tools that do not necessarily work according to the end user expectations. All these small issues will be fixed on a regular basis, and they will appear in new 3.x versions.
> We hope to release new versions once a month, and new LTS versions once a year, at the end of the year [that is why 3.0 will be supported until the end of 2016, but we can extend that until April 2017 if there is great interest in this version].

**Comment by paula-w** [comment]
@SkavenKF 
The LTS version will be supported for a longer time, however, whether or not an update package appears will depend on the community. In case of a critical error, like this one for example:  https://github.com/YetiForceCompany/YetiForceCRM/issues/3125 , the user will be able to download the fixes directly from GitHub, or ask us to prepare a fix for 3.0. From what we noticed, everyone uses update packages [3.2 will show up next week], and wants to have an updated system – we think it's the right direction. 
This is the first time we launch LTS, so it's not yet exactly a fully refined mechanism of releasing update packages for this version. 

We are not really planning the contents of the 4.0 version, becuse we introduce changes on a regular basis. Together with releasing 3.2 we will announce our plans for 3.3; version 4.0 will be published most likely at the end of the year, which means thousands of changes in comparison to 3.0.

**Comment by SkavenKF** [comment]
@paula-w 
Thanks for your answer. I understand that you will normaly develop on the 3.x codeline and it can be happen that you have a "radical change". 
So, your comment in #2881 is false :-(
> Unfortunately the LTS version does not mean that we will fix everything, like change statuses because they are incorrect, automate processes that have not been automated, or improve tools that do not necessarily work according to the end user expectations. All these small issues will be fixed on a regular basis, and they will appear in new 3.x versions.

**Comment by bpabiszczak** [comment]
I can't see any connection between Paula's statement and your quote...
