### ISSUE TITLE
Brak paska integrującego  w Roundcube

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#3141]
PL. Brak paska integrującego  w Roundcube, brak możliwości dodawania zdarzeń z poziomu 
klienta pocztowego.

**Comment by mariuszkrzaczkowski** [comment]
Proszę o przesłanie zrzutów ekranu z konsolą przeglądarki oraz informacji której skórki z Roundcube dotyczy problem

**Comment by mariuszkrzaczkowski** [comment]
Brak wersji systemu
Brak informacji o przeglądarce
https://yetiforce.com/pl/github/issues/125-issues.html

**Comment by hipernet** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/20052436/16231103/f27e05c8-37c4-11e6-9452-32506cb77ca8.png)

Firefox i Safari  nie ma znaczenia

**Comment by bpabiszczak** [comment]
Jak nie ma paska skoro jest :/ Proszę sobie kliknąć zaimportuj maila....
