### ISSUE TITLE
Functions error LOG

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3143]
PHP Fatal error:  Cannot create references to elements of a temporary array expression in /home/path-to/vtlib/Vtiger/Functions.php on line 1141

Please help

**Comment by mariuszkrzaczkowski** [comment]
You have the wrong version of PHP please refer to the requirements https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html and 
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by immhub** [comment]
Fatal error: Call to a member function rowCount() on a non-object in /home/user/public_html/crm/include/database/PearDatabase.php on line 286
I get this when i try to generate a chart in the reports section

**Comment by mariuszkrzaczkowski** [comment]
Can you please read this article : https://yetiforce.com/en/github/issues/126-issues.html and add all the missing info, so that we can investigate your problem?
