### ISSUE TITLE
Issues with fresh install

### ISSUE THREAD

**Issue by TanujHans** [YetiForceCompany/YetiForceCRM#3144]
I am trying to install a fresh copy of YetiForce CRM ver. 3.1.0 (https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/3.1.0) on my Linux web server. I also verified the web server requirements. I placed all the source code present at the above location to a new folder on my web server. As soon as  I try to run the installation from web UI it gives 

![image](https://cloud.githubusercontent.com/assets/13776863/16263840/80cc4a1e-38ca-11e6-9cf3-3ec840c4cdc0.png)

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by kabelo38** [comment]
this is caused by permissions issue you can get away with making cache dir writtable with chmod -R 777 /cache this is however not a best solution

**Comment by WalterLuis** [comment]
I think the best option would be this:

sudo chmod -R 755 /var/www/html/
sudo chmod -R 644 /var/www/html/YetiForceCRM/config/
APACHE in Linux -> sudo chown -hR apache:apache /var/www/html/
NGINX in Linux -> sudo chown -hR nginx:nginx /var/www/html/
XAMPP in MAC -> sudo chown -hR daemon:daemon /Applications/XAMPP/xamppfiles/htdocs/

**Comment by TanujHans** [comment]
As this installation is to setup a development environment for a production website, I have tried giving the file permission 777 to /httpdocs  but still getting the same error page. (To be noted: I am installing a fresh copy of CRM downloaded from Github page). Also I have tried installing YetiForce Portal, SugarCRM, Wordpress on the same server (but in different folders) and they work fine.

**Comment by acidhunter** [comment]
Did u set the correct owner&group?

Please supply errorlogs from httpd & php

**Comment by acidhunter** [comment]
Contact me, i can give u some live support

Telegram:
Nick: @networkpanic
https://telegram.me/networkpanic

xmpp:
networkpanic@jabber.de

**Comment by waran70** [comment]
>  a production website, I have tried giving the file permission 777 to
/httpdocs but still getting
If somebody tell you to change permission to 777 please change adviser...
this is very bad idea man!
Instead try to install using porn tab, so no temps will mess procedure
