### ISSUE TITLE
Question - how to mapp contact field from opprtunity to quote

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#3145]
As my topic was closed I reopen new one with my explanation...
Here is link to privouse discussion https://github.com/YetiForceCompany/YetiForceCRM/issues/3043

Dear Paula,
Why are you telling that my need is illogical from business point of view...? I didn't ask for this but for possibility of YetiForce and mapping module... 

I need contact person in quote because quote is sent to contact not account... If you have several purchasers under account I would like to know who receives my quote to know with whom to follow up... As sales process starts with opportunity I ask for linking contact in opportunity and then by mapping move it to quote... 
This is logic... Can it be done in YF via mapping module?
So can you tell me how I can use mapping module to reach my need?

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/3043
