### ISSUE TITLE
Valid Date of Quote

### ISSUE THREAD

**Issue by sherirao** [YetiForceCompany/YetiForceCRM#3146]
There is no valid date of Quote In Vtiger we used this field and this feild can be shown on template. How to do in yetiforce?
Am i missing something or I have to add valid date field in Quote module ?

**Comment by rskrzypczak** [comment]
This field was just added. 
Of course, you can add almost any field in YetiForce, and it will also be visible in templates ([link](https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=SQuotes)).
