### ISSUE TITLE
[Bug] - cardDAV - text coding issue

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#3147]
Version 3.1.364
Tested on demo of gitdeveloper

There is issue with coding of informaton during cration of card by sabre server...
**Contact data in **YF****
![image](https://cloud.githubusercontent.com/assets/11491482/16270072/3b384f6e-3895-11e6-9000-27a8c0ddcaf4.png)

**Data in vcf card of sabre server ready to synch**
![image](https://cloud.githubusercontent.com/assets/11491482/16270050/22cb4350-3895-11e6-9dd0-6a474afe186f.png)

**Comment by mariuszkrzaczkowski** [comment]
Problem with coding lies in the synchronization app, the error has to be reported to them.
I tested it on different environments and on the DAV server everything is alright.

**Comment by witer30** [comment]
well,
I didnt test synchronisation, simply create contact and check on web access to sabre server so there is no impact of synchronisation app. Please reopen as issue is still exist, just check and it is present...

**Comment by mariuszkrzaczkowski** [comment]
The problem lies in the synchronization client, not in the CRM or DAV. I checked in DAV and in database, and the coding is correct.
