### ISSUE TITLE
Report Module error with date parameter

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3148]
When I create a report with a date parameter the graph is not genrated and the two fields are blank.
It is the same issue than the #3058 ticket.

![image](https://cloud.githubusercontent.com/assets/1357727/16274375/a6bf38d2-38a5-11e6-8f94-a45d67fe9cdd.png)

Thank's =)

**Comment by paula-w** [comment]
For which module were you trying to generate the report? What's your system version? We need to know these things to be able to help you solve the issue. 
Also, please take screenshots of the English version of the system.

**Comment by Raggazzoo** [comment]
I tried with Leads / Accounts / Opportunities modules.
It's the same for chart and report.

Since I updated to 3.1.404 I got this
![image](https://cloud.githubusercontent.com/assets/1357727/16407550/98b9ca9a-3d14-11e6-8563-36d52bb1b6da.png)

**Comment by Raggazzoo** [comment]
I updated to 4.1.417 and I already have the date issue on reports.

**Comment by TomaszQr** [comment]
Provide us with the exact configuration how to trigger the error, we checked it in Leads/Accounts/Opportunities, you can also check if the error exists in the current version.
