### ISSUE TITLE
[Question] Remove Create Button 

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#3149]
![screenshot_1](https://cloud.githubusercontent.com/assets/11919990/16287026/e634430e-38a5-11e6-8f69-43689566ba50.png)
I would like to remove the Create Button in the HelpDesk module (only allow clerk to select from existing Products and Accounts).  Because they keep creating new accounts and products.  I did this before, but can't remember how and I can't find it in the existing issues...sorry.

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Profiles&parent=Settings&view=Edit&record=2

**Comment by mykljohn** [comment]
@mariuszkrzaczkowski This will change the permission for the whole system.  I don't want to eliminate their permission to create Accounts.  I just want them to only be able to choose and existing account from the ticket module.

**Comment by bpabiszczak** [comment]
We aren't going to change this mechanism. In my opinion it's okay as it is now.

**Comment by mykljohn** [comment]
I did this before, can you point me in the right direction to block the "create" button?

**Comment by mykljohn** [comment]
And just to be clear in my reasoning, in theory, a ticket would only be created for an existing account or product.  There really is no need for the create button on the ticket screen.
