### ISSUE TITLE
Roundcube - compose - error typing in email to field

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#315]
Hi,
i installed a clean installation of version 1.3. When I want to compose an email and manually enter an email address into the "to" field, on every character I enter an error pop-up 'Server Error! (ok)' get displayed.
Roundcube log shows message:
PHP Error: Error loading template for  in /var/www/clients/client3/web31/web/crm/modules/OSSMail/roundcube/program/include/rcmail_output_html.php on line 494 (GET /crm/modules/OSSMail/roundcube//?_task=mail&_action=autocomplete)

**Comment by witer30** [comment]
I have the same issue, when composing new email and starting typing email address after each letter there is popup window describing server error (OK)... It seems that there is bug with searching contact's email database...

**Comment by bpabiszczak** [comment]
We have updated Roundcube to the latest version, check the newest version on GitHub or wait for 1.4 that will be published soon. Try to test for this error on our testing version. In order for us to fix it, we have to be able to find it and test it so please try to do it at test.yetiforce.com.

**Comment by bpabiszczak** [comment]
Fix: https://github.com/YetiForceCompany/YetiForceCRM/commit/f850d693cb3813e4a08de92ea75010fb6b98e20b
