### ISSUE TITLE
[Question] Remove Create Button ref #3149

### ISSUE THREAD

**Issue by mykljohn** [YetiForceCompany/YetiForceCRM#3150]
@mariuszkrzaczkowski Your suggestion of using permissions would be fine if I wanted to not allow them to create any Accounts, but I don't want to eliminate their permission to create Accounts. I just want them to only be able to choose an existing account from the ticket module (HelpDesk).

**Comment by paula-w** [comment]
Hi.
Right now there's no option to do that. If you know how to do that, you can add a mechanism like this to the configuration and send it to us.

**Comment by mykljohn** [comment]
OK, to block the create button, I changed line 57-61 in /layouts/basic/modules/Vtiger/uitypes/Reference.tpl to:

`			{if ($MODULE_NAME eq 'HelpDesk') }
			{elseif (($VIEW eq 'Edit') or ($MODULE eq 'Webforms')) && $REFERENCE_MODULE_MODEL && $REFERENCE_MODULE_MODEL->isQuickCreateSupported()}
				<button class="btn btn-default createReferenceRecord" type="button" {if $FIELD_MODEL->isEditableReadOnly()}disabled {/if}>
					<span id="{$MODULE}_editView_fieldName_{$FIELD_NAME}_create" class="glyphicon glyphicon-plus" title="{vtranslate('LBL_CREATE', $MODULE)}"></span>
				</button>
			{/if}`
