### ISSUE TITLE
Shipping & Handling Charges

### ISSUE THREAD

**Issue by AngeLinuX99** [YetiForceCompany/YetiForceCRM#3151]
Hi : 

We are evaluating YetiForce 3.2 for production, partially migrating our vtiger data and we have noticed that on Quotes (and also on Invoices and maybe another modules) we cannot add Shipping & Handling Charges values and Taxes For Shipping and Handling values. It's important for us when deliver goods to a final customer, and the quote must reflect this values detailed.

Any clue about this ?

Thanks for develope YetiForce, it's a high quality product.

**Comment by paula-w** [comment]
In Poland services related to shipping are listed as separate services on the document [we don't know about other countries, we can only assume it's a similar situation]. Shipping costs are a regular service and they don't work the  same way they do in Vtiger. As far as costs fields in VT are concerned – our invoice reflects the reality, if the client paid something partially, eg. an advance payment, then it has to be registered using other documents. We removed that field, but if you want you can add it  [some programming knowledge is required].

**Comment by waran70** [comment]
> we can only assume it's a similar situation

Paula, so Yetiforce is for Polish market only? Yes/No?

**Comment by bpabiszczak** [comment]
No.
