### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by johntonji** [YetiForceCompany/YetiForceCRM#3152]
I have installed and it is blank. I refreshed it and it will give me the attached screen

![blank](https://cloud.githubusercontent.com/assets/16850688/16296451/56f25b54-38fa-11e6-8202-480aea5173ab.jpg)
![df](https://cloud.githubusercontent.com/assets/16850688/16296477/761d7676-38fa-11e6-918d-a571e522c2d2.jpg)

**Comment by florek41** [comment]
LOGS!

https://yetiforce.com/en/github/issues/126-issues.html
