### ISSUE TITLE
Kampania marketingowa 

### ISSUE THREAD

**Issue by r0bertk** [YetiForceCompany/YetiForceCRM#3154]
Witam,
w kampani marketingowej w zakładce Kontrahenci, jeśli wybierzemy filtr listy, a nastepnie zaznaczymy checkboxa wszystkie pola z listy i klikniemy wyślij pocztą to system zamiast wysyłać do osób zgodnie z użytym filtrem, chce wysłać do wszystkich kontrahentów posiadających e-mail.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/github/issues/125-issues.html

**Comment by mariuszkrzaczkowski** [comment]
Testowane na najnowszej wersji i zgłoszony problem nie występuje.
