### ISSUE TITLE
Slow working crm. Help needed to identify problem.

### ISSUE THREAD

**Issue by zwieja** [YetiForceCompany/YetiForceCRM#3156]
YetiForce crm is installed on vmachine with 4GB of RAM and MariaDB 10.1.14 with php 5.6.
On some users accounts some pages load very long, loading times over 10 sec. e.g Leads, Accounts.
What could be the reason ?

When I installed yetiforce on local pc I haven't any problems.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/implementer/optimization/102-mysql-optimization.html

**Comment by mariuszkrzaczkowski** [comment]
Enabling the count of unread emails significantly slows down the crm.
