### ISSUE TITLE
How to use module Mobile Applications

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3161]
I saw module call history, but did not see its user guide, How to use it.

**Comment by vovpff** [comment]
Install local Yeti and activate in file \config\api.php needed features:

$enableBrowser = false;
$enableCardDAV = true;
$enableCalDAV = true;
$enableWebDAV = false;

After that download apks for your mobile from here https://github.com/YetiForceCompany/YetiForcePushCall and here https://github.com/YetiForceCompany/YetiForceDialHistory

Setup key and made connection between yeti mobile apps and yeti system

**Comment by ezbank** [comment]
thanks, but not support iOs?

**Comment by vovpff** [comment]
@ezbank this is question for YetiForce team.
I never used iOs in the past.

**Comment by bpabiszczak** [comment]
CalDAV, CardDAV support all OS.
WebDAV is not finished
YetiForcePushCall, YetiForceDialHistory only works on Android.

**Comment by ldgbc** [comment]
@vovpff @ezbank 
with regarding to Mobile YetiForcePushCall, YetiForceDialHistory

Hi, do you know if it working on v3.4 or v4?

When I click the refresh key it just say '

> Service is not available on the server or network connection is turned off!

Initially I thought it only support Wifi but when I enable it, still got that. Either I configure it incorrect or it not longer supported on v3.4+.

Thank you.
