### ISSUE TITLE
[bug] creating email template

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3162]
YetiForce CRM: 3.1.404 (developer)
![error-emailtemplate](https://cloud.githubusercontent.com/assets/18419851/16408501/ffdf1f3a-3d10-11e6-95a0-fc03a1651deb.gif)

**Comment by TomaszQr** [comment]
The error doesn't exist in Chrome, if somebody uses Firefox it will be necessary to install adobe flash player addon.

**Comment by WalterLuis** [comment]
Okey, thanks and I'm sorry for the inconvenience
