### ISSUE TITLE
[Bug] Search broken

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3167]
![search bug](https://cloud.githubusercontent.com/assets/8545791/16440661/b58a26e8-3dcc-11e6-8a76-84c3b5636ee8.gif)

- There is no possibility to save filter
- No possibility to modify filter from search window. After first search if search conditions modified search results windows appears for small time and turned back to search conditions
- Gray background when search conditions window closed. Ony Refresh helps
- If module changed during search Search button became not working

**Comment by TomaszQr** [comment]
There is no possobility to save filter - Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/43b7fc9d797f81f66d591d52047b23cf1f6c3111

**Comment by vovpff** [comment]
@TomaszQr no problem. Looks like "save filter" grows from old versions of yeti.
