### ISSUE TITLE
[bug] broken install???

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#3169]
**about the time of installation**
first step message:

`Notice: Undefined variable: root_directory in /Volumes/B_data/WWW/domains/YetiForceCRM/include/ConfigUtils.php on line 142`

`Notice: Undefined index: STYLES in /Volumes/B_data/WWW/domains/YetiForceCRM/cache/templates_c/basic/53fe7743a7dc07cef99f5b63d0caebf019c408a8_0.file.Header.tpl.php on line 28`

`Notice: Trying to get property of non-object in /Volumes/B_data/WWW/domains/YetiForceCRM/cache/templates_c/basic/53fe7743a7dc07cef99f5b63d0caebf019c408a8_0.file.Header.tpl.php on line 28`

**After install (login page)**
`Notice: Undefined index: authenticated_user_id in /Volumes/B_data/WWW/domains/YetiForceCRM/include/main/WebUI.php on line 47`

**After login**
`Notice :  Undefined index: LBL_CUSTOM_INFORMATION in /Volumes/B_data/WWW/domains/YetiForceCRM/modules/CustomView/CustomView.php  on line 1437`

ver3.1.417

**Comment by mariuszkrzaczkowski** [comment]
check requirements in:
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by iRainSystem** [comment]
Oh. requirements сomply, but in .htaccess why two rows changed?
`php_flag	log_errors				On
php_flag	display_errors				On` 

I set "Off", and all is well.
