### ISSUE TITLE
inventory mangment

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3171]
how to add the barcode and serial number field to any Entity or product which send or receive in inventory? in the other word how could i add this feature to my Inventory process to logistic modules.

Note : in our logistic process  we consider different barcode and serial number for each product for example if we have 20 pcs from product A we have 20 different serial number and barcode .and in every receive and send note this serial and barcode must added .

**Comment by vovpff** [comment]
@vahid-jml you can use assets module. You can establish relation between a lot of assets with one product.

**Comment by vahid-jml** [comment]
thank you @vovpff . but i think this is not  good idea to use assets modules because i want to know what product with serial number received in warehouse  and  what product  with serial number sent from warehouse.

**Comment by vovpff** [comment]
@vahid-jml maybe my answer not so correct, but you can made additional advanced field for inventory modules where you can select reference record in items list, for example to assets.

**Comment by bpabiszczak** [comment]
We have to separate two pieces of information. First of all, for most companies the EAN-13 code is enough to define a product, it's the same for each product in a given batch. This information is most often sufficient, however some information store more info about the product using EAN-128, for example they store the expiration date. As far as I know [and I'm not an expert] even by using different codes than EAN-13, the batch info is the same for these products. The FIFO, LIFO, EFO method is crucial in the whole storage process, that the entire storage is based on. First question is what EAN you use in your company.

In case of longer codes, EAN -128 for example, the info about the product can be found on the document that is used to receive the product in the storage, for example Goods Received Note, but the stock is general for the batch. When it comes to displaying EAN in CRM then you have to write a proper UITYPE, that will change a string of characters into a barcode. As far as printouts are concerned, Yetiforce's built-in PDF editor handles barcodes, you can read more about it here:  https://omig.ny.gov/data/MPDF573/examples/show_code.php?filename=example37_barcodes.php  or in mpdf documentation.

Assets do have info about the serial number, but they don't have anything to do with storage transfers, and just like @vahid-jml said, they are used for something else.

**Comment by crawe1** [comment]
Hello,

I don't want to create a new issue but i see your comment @bpabiszczak. You sed "The FIFO, LIFO, EFO method is crucial in the whole storage process, that the entire storage is based on." tell me wthat method is implemented od storage in yeti ? 
I have a problem with situation:
1) I bought this same product from twice other provider 
2) once thist product cost 100 dolars, once thist product cost 200 dolars
3) i add on storage via [PZ]module. 
4) when i add product on stock, first qty and seconcd qty is a sume but is not the same cost.
5) how i know how muth stock on storage this same product and how method use yeti to sell and out of storage stock ? How can i know what this same product sell first.
I must to know full total cost of thist product stock what i have on storage and what product sell first by the method.
