### ISSUE TITLE
Multiple users relation for one account

### ISSUE THREAD

**Issue by natpicone** [YetiForceCompany/YetiForceCRM#3173]
Hi,
in the account details I need to have different users, one for each business line.
I was wondering to add to the accounts one custom field for each business line with a 1:N relation with the users.
Is there a way to archive this ?

Thanks a lot

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
there is already a field like that in the system. It can be found in every module and it's called "Share with users".

**Comment by natpicone** [comment]
Hi,
With shared users I don't know which is the business line.
I need something good like:
- logistic -> user1
- delivery -> user2
- support -> user2
- sales mechanic -> user3
- sales adv -> user4

Thanks a lot
