### ISSUE TITLE
[Question] Module Password to do?

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3176]
![nh ch p man hinh 5](https://cloud.githubusercontent.com/assets/19627226/16479407/466fdf92-3eca-11e6-911e-a2dbece01274.png)

**Comment by paula-w** [comment]
What is the question?

**Comment by ezbank** [comment]
i see its apearance here, but i dont know what is it reasons, could you give me its meanning to use effectively

**Comment by paula-w** [comment]
The module is used for storing passwords. 
If your company doesn't store your Accounts' passwords then you don't need the module and you can disable it.
