### ISSUE TITLE
[BUG] Error when send notification

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3177]
test on https://gitdeveloper.yetiforce.com/index.php
I tried to send one notice, and now I can not access it anymore
![animation](https://cloud.githubusercontent.com/assets/19627226/16486461/0c22ab9c-3eef-11e6-8208-594a3c6dcab0.gif)

**Comment by paula-w** [comment]
I can't trigger that error on the dev version. 
Can you tell us what you did before you recorded the clip?

**Comment by ezbank** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Home&view=NotificationsList
access error

**Comment by ezbank** [comment]
![animation1](https://cloud.githubusercontent.com/assets/19627226/16487678/92788818-3ef6-11e6-8c00-7729cf7eeddf.gif)
