### ISSUE TITLE
Cron Sorry! Attempt to access restricted file. ''

### ISSUE THREAD

**Issue by rezaizadi** [YetiForceCompany/YetiForceCRM#3180]
ver 2.3.49
Create WorkFlow Scheduler

after start cron/vtigercron.php show this Error:
Sorry! Attempt to access restricted file. ''

just run one task workflow without update next trigger time.

if (stripos($realfilepath, $rootdirpath) !== 0 || in_array($filePathParts[0], $unsafeDirectories)) {
die("Sorry! Attempt to access restricted file.");
}

This is inside Vtlib/vtiger/Deprecated.php

**Comment by skramanzia** [comment]
1- Check file permissions chmod "755". 
2- Check This related TK : https://github.com/YetiForceCompany/YetiForceCRM/issues/2155

**Comment by rezaizadi** [comment]
I set chmod "755" for files and check this TK : #2155 but i have this problem yet  (Sorry! Attempt to access restricted file. '')

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by rezaizadi** [comment]
This function checkFileAccessForInclusion at file Vtlib/vtiger/Deprecated.php  search for ' ' (null) directory. 
Sorry! Attempt to access restricted file. ' '

**Comment by WalterLuis** [comment]
If you use apache in linux try with `sudo chown -R apache:apache /var/www/html/yetiforce`

**Comment by rezaizadi** [comment]
after set  sudo chown -R apache:apache /var/www/html/yetiforce problem for login
but work with root:root

please help for correct set group and owner files and folders

**Comment by rezaizadi** [comment]
why check filepath       modules\\.php       at function checkFileAccessForInclusion?

**Comment by mariuszkrzaczkowski** [comment]
Check logs
