### ISSUE TITLE
error in storage 

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3181]
after creating first storage ,parent storage became a mandatory fields for creating other storage but whenever i remove firs storage we con not create another storage .
![storage4](https://cloud.githubusercontent.com/assets/18072100/16544251/cfe78f4a-4113-11e6-9fc5-5de660ff1740.png)
![storage5](https://cloud.githubusercontent.com/assets/18072100/16544252/d351f1e8-4113-11e6-8664-866ec5c20769.png)

**Comment by kpaulaha** [comment]
Empty the trash bin

**Comment by vahid-jml** [comment]
@kpaulaha how to Empty the trash bin?

**Comment by kpaulaha** [comment]
Add recycle bin to menu in Menu configurator, it's not there as default.
