### ISSUE TITLE
Unable to select Contact fields in opportunity workflow emails

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#3183]
Hello everyone - it seems that there was a small missunderstanding so i included a video for you and hope to make it clearer.

in the video we try to setup a workflow for OPPORTUNITIES which sends a email with content from CONTACT-Fields.

Best regards Ralph (was not sure if you saw it in another ticket)
![animation](https://cloud.githubusercontent.com/assets/12951699/16555521/62e50068-41d5-11e6-9dec-246df685c630.gif)

**Comment by TomaszQr** [comment]
Opportunity and contacts have the 1:M relation, and right now reading fields from this kind of relation is not possible.

**Comment by ralphkretzschmar** [comment]
That is sad, because we were able to do it in vTiger. :(
The contacts have been added to the opportunity - isn't there a link in between to get those contact details in an email?

Best Ralph
