### ISSUE TITLE
3.2 Update PLS

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3184]
Hello,

When will the update for 3.2 be released.

Plus ... i made the Romanian translation for Yetiforce 3.1.3 (where shoud i send you the files)?

**Comment by SkavenKF** [comment]
Under Milestones, you see the planned Releasedate.
![milestones](https://cloud.githubusercontent.com/assets/10259801/16558188/3488b778-41e4-11e6-97b5-0db4fdb95544.JPG)

**Comment by skramanzia** [comment]
@immhub check this link " https://github.com/YetiForceCompany/YetiForceCRM/milestones"

![image](https://cloud.githubusercontent.com/assets/3030997/16560874/5b51a97c-41cc-11e6-9a2a-10c44509387d.png)

**Comment by bpabiszczak** [comment]
https://help.github.com/articles/using-pull-requests/
