### ISSUE TITLE
add search menu on the relations tab

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3187]
it would be interesting to have the search fields in the related fields list view as in the module list view.

![yeti3](https://cloud.githubusercontent.com/assets/18703633/16563851/a3196366-4204-11e6-99d5-4363df9a1516.png)

**Comment by rskrzypczak** [comment]
Added this option in this commit: https://github.com/YetiForceCompany/YetiForceCRM/commit/e009963570d4f342ce0a16d95cc6f75e40938b1c
+ minor fixes: https://github.com/YetiForceCompany/YetiForceCRM/commit/e4330fe53eb65e19035671770cf99a14aaca4c7d  https://github.com/YetiForceCompany/YetiForceCRM/commit/0770d07677f835148f1add7225555b7ef95d84c0
