### ISSUE TITLE
[URGENT] Uppercase letter error at user creation

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3189]
Since the 3.1.452 the user creation form returns an error of uppercase letter.

![image](https://cloud.githubusercontent.com/assets/1357727/16583067/583af36e-42b3-11e6-9b40-8380103e6fe6.png)

**Comment by nic86** [comment]
It is a message which indicates to insert a capital letter in the password field. the issue is that not highlight the field that generates the error

**Comment by Raggazzoo** [comment]
Thank's nic86!
