### ISSUE TITLE
[BUG] Cant select filter all - v3.1.460

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3192]
![animation1](https://cloud.githubusercontent.com/assets/19627226/16593524/e2ad9eb4-430f-11e6-8cd7-5ee7b6e3811b.gif)

**Comment by rskrzypczak** [comment]
this is not a bug.
![dashboard2](https://cloud.githubusercontent.com/assets/10221999/16595505/be5f9a8c-42ef-11e6-9864-8a9cb48e94b3.gif)
