### ISSUE TITLE
[bug] don't load page "Currency Update"

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3195]
Version: 3.1.465 (developed)
![yetiforce currency update](https://cloud.githubusercontent.com/assets/18419851/16612185/8e5b5394-435d-11e6-81db-5d167db28a5b.gif)

**Comment by TomaszQr** [comment]
I couldn't trigger the error, I tested it on gitdeveloper, if the error still exists please send additional information about your browser and operating system.

**Comment by WalterLuis** [comment]
Solved! :D

Windows 8.1 pro in virtualBox with 4Gb assigned
Server LAMP with XAMPP 5.6.21

Activating 
-error_reporting E_ALL
-display_errors On

I can see: 
"Fatal error: Class 'SoapClient' not found in C:\xampp\htdocs\YetiForce\modules\Settings\CurrencyUpdate\models\bankmodels\CBR.php on line 38"

I had commented in 'php.ini' the next extension 'extension=php_soap.dll', uncomment the line and it works.

it would be nice to put on the page requirements [https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html](url) this extension [http://php.net/manual/es/book.soap.php](url)

Thanks and sorry for the inconvenience.
