### ISSUE TITLE
Quick search doesn't work on Account/Lead/Opportunity

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3196]
Hi,

When I try to use the easy search of 3 characters to find an Account/Lead/Opportunity it returns no result.
![image](https://cloud.githubusercontent.com/assets/1357727/16612571/ee4e0404-4367-11e6-9bca-75e57daa84f5.png)
Thank's

**Comment by vovpff** [comment]
How records of Account/Lead/Opportunity created? If this records are imported you need to update labels here: https://gitdeveloper.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=13&fieldid=56

**Comment by SkavenKF** [comment]
When you imported via CSV, you can look at #3038 
In modules/Vtiger/views/Import.php at line 163 you can expand the code with csv:
$viewer->assign('CREATE_RECORDS_BY_MODEL', in_array($request->get('type'), ['xml', 'zip','csv']));

I use this for Migration from vTiger.

**Comment by Raggazzoo** [comment]
It's works perfectly!

Thak's!
