### ISSUE TITLE
[BUG] Incorrect calculation of related campaigns in Account

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#3201]
![campaign2](https://cloud.githubusercontent.com/assets/10221999/16645556/0cfa16a0-4425-11e6-88e4-442502cb919a.gif)

**Comment by vovpff** [comment]
@rskrzypczak sorry for offtopic. How you made related records calculation in in tabs?
![image](https://cloud.githubusercontent.com/assets/8545791/16652059/9110693c-4450-11e6-9099-6183e58e221c.png)

**Comment by rskrzypczak** [comment]
The value of SHOW_RECORDS_COUNT parameter should be changed to true in config/relation.php file

**Comment by vovpff** [comment]
@rskrzypczak Thanks!
