### ISSUE TITLE
Unable to select filter in chart widget creation form

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3202]
When I try to create a chart widget on the home page, I can't select filter.

There is a screenshot of the gitdevelopper version
![image](https://cloud.githubusercontent.com/assets/1357727/16645878/50fe66ce-4427-11e6-89e6-83c8932ecac0.png)

**Comment by ezbank** [comment]
#3192

**Comment by Raggazzoo** [comment]
Nice thank's!
