### ISSUE TITLE
Is the update package still coming out today?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3203]
Hi,

is the next update release still coming out today -  Yetiforce 3.2?

Kind regards

percy

**Comment by paula-w** [comment]
Hi Percy. It will most likely be postponed until 20 ~22.07, we won't manage to release it by tomorrow, and next week the person responsible for the publication won't be available, so you will have to wait a bit. The version for testing will be available next week, because we're about to finish it.
