### ISSUE TITLE
Testing color in demo not working

### ISSUE THREAD

**Issue by simonetravaglini** [YetiForceCompany/YetiForceCRM#3204]
Hello,
don't know if I'm doing something wrong but I can't use setting to color line of listview.
I try to set in this way:
![image](https://cloud.githubusercontent.com/assets/6990139/16653997/07965f28-4454-11e6-974c-29a74add0371.png)

but:
![image](https://cloud.githubusercontent.com/assets/6990139/16654025/2b196102-4454-11e6-8bcc-b1a4a4d371b7.png)

**Comment by TomaszQr** [comment]
![datacces](https://cloud.githubusercontent.com/assets/14273211/16654982/9376ea9a-4458-11e6-9558-c243c9f9aacb.gif)

**Comment by simonetravaglini** [comment]
Thomas thanks for sharing solution, but now my question is what color setting menu does?

**Comment by bpabiszczak** [comment]
This configuration changes the colors on the charts [on dashboard]
