### ISSUE TITLE
bug widget from filter

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3205]
tested on developer 
add widget key metric and remove it from dashboard after create a filter(test) with option list in metric and add widget from filter(test) to the dashboard and remove the filter from the module list view, the dashboard crash.
![gifrecord_2016-07-07_153756](https://cloud.githubusercontent.com/assets/18703633/16656194/0dd71472-445e-11e6-84b1-658eba907f12.gif)

**Comment by ezbank** [comment]
this bug
