### ISSUE TITLE
menu enhancement

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3206]
recommend to change the main menu with only the icons and replace the transition to the right with the tooltip to display labels, same for sub menu (only icon and tooltip for labels) but start from height of icon parent

**Comment by paula-w** [comment]
You can modify the menu as much as you want using HTML5/CSS3 and templates, if you come up something cool and ready, you can upload it to YetiForce. Right now we're not planning any appearance changes, [we got some more important things to take care of] unless a client pays for a change like that. 

More info available at: [Why was the issue ignored](https://yetiforce.com/en/github/issues/205-why-was-the-issue-ignored.html)
