### ISSUE TITLE
[bug] crash javascript in users module

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3208]
Version: 3.1.501(developed)
![yeti user](https://cloud.githubusercontent.com/assets/18419851/16670661/2a34a870-4493-11e6-9c9e-1ebf6a3c26bc.gif)

tested in: https://gitdeveloper.yetiforce.com/index.php?module=Users&parent=Settings&view=List&block=1&fieldid=1

**Comment by Raggazzoo** [comment]
It's the same for the report module
