### ISSUE TITLE
[Question] How to config "Values assigned to a Role" at picklist in SSalesProcesses (status)

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3209]
![untitled](https://cloud.githubusercontent.com/assets/19627226/16679208/f72d56b6-450f-11e6-844e-3a09ac357bab.JPG)

**Comment by ezbank** [comment]
pls help me

**Comment by vovpff** [comment]
@ezbank I have no idea how to made it.
This "Status" picklist field not usual picklists and manual modification of batabase can't help.

**Comment by KatarzynaUlichnowska** [comment]
There are two types of picklist fields in YetiForce (as well as in Vtiger) - one with permissions and one without. In this case, it is a field without permissions and changing uitype in vtiger_fields is only half of the job. It is also necessary to add start values in tables with permissions for fields. We do not recommend changing it if you don't know how it works and how to do it properly at the system level - there is a risk of breaking the system.
