### ISSUE TITLE
[BUG] Unable to edit an event

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3211]
I create an event but when I try to edit it I got an error
![image](https://cloud.githubusercontent.com/assets/1357727/16688133/c8c22326-451c-11e6-8d71-f134bd7b0007.png)

![image](https://cloud.githubusercontent.com/assets/1357727/16687477/3041d932-4519-11e6-990c-9a4688f91bcc.png)

gitdeveloper version 3.1.510

**Comment by TomaszQr** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/39b8c44a0adc3947ed93ef50dd041ec1483ad22c
