### ISSUE TITLE
type of calendar view

### ISSUE THREAD

**Issue by simonetravaglini** [YetiForceCompany/YetiForceCRM#3213]
Hello,
despite vtiger I see you opted for "Agenda View". But it's possible also to set standard calendar view, with all hours of the day?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/Calendar.php#L9

**Comment by simonetravaglini** [comment]
Could be a good idea give the possibility from setting to make this choise!
