### ISSUE TITLE
[PL] config/api.php

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#3215]
Proszę o info jak poprawnie ma być ten plik skonfigurowany 

//List of active services. To enable you must uncomment the appropriate line.
$enabledServices = [
	//'mobile',
	//'yetiportal',
	//'dav',
	//'webservices',
	//'mobileModule',
	//'webservice',
];
/* +***************   DAV   **************** */
$enableBrowser = true;
$enableCardDAV = true;
$enableCalDAV = true;
$enableWebDAV = true;

/* +*********   Webservice config  ********* */
$API_CONFIG = [
	'ENCRYPT_DATA_TRANSFER' => true,
	'AUTH_METHOD' => 'Basic',
	'PRIVATE_KEY' => 'config/private.key',
	'PUBLIC_KEY' => 'config/public.key',
];

**Comment by hipernet** [comment]
Aplikacja DAV nie została jeszcze aktywowana, proszę o włączenie usuługi "DAV" w pliku config/api.php

**Comment by hipernet** [comment]
CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '401' ('Unauthorized'). Message:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.1.3</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured</s:message>
  <s:file>/home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/libraries/SabreDAV/DAV/Auth/Plugin.php</s:file>
  <s:line>188</s:line>
  <s:code>0</s:code>
  <s:stacktrace>#0 [internal function]: Sabre\DAV\Auth\Plugin-&gt;beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#1 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/libraries/SabreDAV/Event/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#2 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/libraries/SabreDAV/DAV/Server.php(446): Sabre\Event\EventEmitter-&gt;emit('beforeMethod', Array)
#3 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/libraries/SabreDAV/DAV/Server.php(248): Sabre\DAV\Server-&gt;invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#4 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/api/dav.php(82): Sabre\DAV\Server-&gt;exec()
#5 {main}</s:stacktrace>
</d:error>

   w CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__10.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w CalDavSynchronizer.DataAccess.CardDavDataAccess.<GetAllVersions>d__13.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w CalDavSynchronizer.Implementation.Contacts.CardDavRepository.<GetAllVersions>d__5.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w GenSync.Synchronization.Synchronizer`7.<SynchronizeNoThrow>d__17.MoveNext()

**Comment by bpabiszczak** [comment]
Przykład pliku z GitDeveloper gdzie domyślnie jest włączona komunikacja caldav i carddav. 
<?php
/* +***********************************************************************************************************************************
 * The contents of this file are subject to the YetiForce Public License Version 1.1 (the "License"); you may not use this file except
 * in compliance with the License.
 * Software distributed under the License is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * See the License for the specific language governing rights and limitations under the License.
 * The Original Code is YetiForce.
 * The Initial Developer of the Original Code is YetiForce. Portions created by YetiForce are Copyright (C) www.yetiforce.com. 
 * All Rights Reserved.
 * *********************************************************************************************************************************** */
/* +********   active services   *********** */
//List of active services. To enable you must uncomment the appropriate line.
$enabledServices = [
	'mobile',
	'yetiportal',
	'dav',
	'webservices',
	'mobileModule',
	'webservice',
];
/* +***************   DAV   **************** */
$enableBrowser = true;
$enableCardDAV = true;
$enableCalDAV = true;
$enableWebDAV = false;

/* +*********   Webservice config  ********* */
$API_CONFIG = [
	'ENCRYPT_DATA_TRANSFER' => false,
	'AUTH_METHOD' => 'Basic',
	'PRIVATE_KEY' => 'config/private.key',
	'PUBLIC_KEY' => 'config/public.key',
];

**Comment by bpabiszczak** [comment]
![gitdeveloper](https://cloud.githubusercontent.com/assets/10197525/17157286/ac4dfa1e-538e-11e6-9b79-29c140138361.png)

**Comment by bpabiszczak** [comment]
z tego co widzę u Ciebie to w pierwszej tablicy należy odblokować DAV a dodatkowo zablokować webdav [false] bo webdav jeszcze nie działa poprawnie...

**Comment by hipernet** [comment]
Co masz na myśli z odblokowaniem włączone opcja true czy coś jeszcze wykonać?

Od:  Błażej Pabiszczak <notifications@github.com>
Odpowiedź do:  YetiForceCompany/YetiForceCRM <reply@reply.github.com>
Data:  środa, 27 lipca 2016 00:13
Do:  YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
DW:  Zdzisław Oracz <z.oracz@hipernet.com.pl>, Author <author@noreply.github.com>
Temat:  Re: [YetiForceCompany/YetiForceCRM] [PL] config/api.php (#3215)


z tego co widzę u Ciebie to w pierwszej tablicy należy odblokować DAV a dodatkowo zablokować webdav [false] bo webdav jeszcze nie działa poprawnie...

**Comment by hipernet** [comment]
Tak widze chyba slash nie usunięty  

Od:  Błażej Pabiszczak <notifications@github.com>
Odpowiedź do:  YetiForceCompany/YetiForceCRM <reply@reply.github.com>
Data:  środa, 27 lipca 2016 00:13
Do:  YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
DW:  Zdzisław Oracz <z.oracz@hipernet.com.pl>, Author <author@noreply.github.com>
Temat:  Re: [YetiForceCompany/YetiForceCRM] [PL] config/api.php (#3215)


z tego co widzę u Ciebie to w pierwszej tablicy należy odblokować DAV a dodatkowo zablokować webdav [false] bo webdav jeszcze nie działa poprawnie...

**Comment by hipernet** [comment]
Pojawił się problem z updatem Błędna wersja modułu, wersja modułu 3.1.0 a powinna być większa niż 3.1.247

Od:  Błażej Pabiszczak <notifications@github.com>
Odpowiedź do:  YetiForceCompany/YetiForceCRM <reply@reply.github.com>
Data:  środa, 27 lipca 2016 00:13
Do:  YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
DW:  Zdzisław Oracz <z.oracz@hipernet.com.pl>, Author <author@noreply.github.com>
Temat:  Re: [YetiForceCompany/YetiForceCRM] [PL] config/api.php (#3215)


z tego co widzę u Ciebie to w pierwszej tablicy należy odblokować DAV a dodatkowo zablokować webdav [false] bo webdav jeszcze nie działa poprawnie...

**Comment by bpabiszczak** [comment]
Może warto przeczytać instrukcje aktualizacji?

**Comment by hipernet** [comment]
Przeczytałem, ale chyba  problem z oceną bo nic tam specjalnego nie widzę ,

Może jakaś podpowiedź z twojej strony , jestem chyba za stary

**Comment by bpabiszczak** [comment]
Aby zainstalować aktualizacje dla wersji częściowej tj. 3.1.X wówczas trzeba ręcznie w CRM zmienić wersje systemu na 3.1.0 a można to zrobić w config/version.php. 

Pamiętaj tylko, aby każdą aktualizacje robić najpierw na środowisku testowym i przed wykonaniem na produkcji zrobić kopię zapasową.

**Comment by hipernet** [comment]
Dziękuje , poszło 

Od:  Błażej Pabiszczak <notifications@github.com>
Odpowiedź do:  YetiForceCompany/YetiForceCRM <reply@reply.github.com>
Data:  piątek, 29 lipca 2016 14:07
Do:  YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
DW:  Zdzisław Oracz <z.oracz@hipernet.com.pl>, Author <author@noreply.github.com>
Temat:  Re: [YetiForceCompany/YetiForceCRM] [PL] config/api.php (#3215)


Aby zainstalować aktualizacje dla wersji częściowej tj. 3.1.X wówczas trzeba ręcznie w CRM zmienić wersje systemu na 3.1.0 a można to zrobić w config/version.php. 

Pamiętaj tylko, aby każdą aktualizacje robić najpierw na środowisku testowym i przed wykonaniem na produkcji zrobić kopię zapasową.
