### ISSUE TITLE
Fatal Error when installing

### ISSUE THREAD

**Issue by Blooregard1984** [YetiForceCompany/YetiForceCRM#3216]
Hi all,

I have run into the following error when trying to install YetiForce. I'm unsure as to what it relates to.

Fatal error: session_start(): Failed to initialize storage module: memcache (path: cache/session/) in /var/sites/l/lapetitebijou.co.uk/public_html/YetiForce/libraries/HTTP_Session/Session.php on line 160

Any help would be greatly appreciated.

Thanks

**Comment by WalterLuis** [comment]
Hi,
first of all sorry for the delay, I just saw him :D

to report issues: https://yetiforce.com/en/github/issues/126-issues.html

and for you to see the requirements: https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

NOTE: if you're with CentOS you should disable SELinux to avoid problems with the use of the site and sending emails
