### ISSUE TITLE
[bug] create or edit or access or delete custom module

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3219]
Version: 3.1.528 (developed)
Creating:
![errormodule 1](https://cloud.githubusercontent.com/assets/18419851/16710641/d881da10-462d-11e6-8094-2e3ce259247f.gif)

Accessing or deleting:
![errormodule 2](https://cloud.githubusercontent.com/assets/18419851/16710643/db071da4-462d-11e6-994e-51a3c70e4573.gif)

Fatal error:
![fatal error](https://cloud.githubusercontent.com/assets/18419851/16710678/3478547e-462f-11e6-9296-51064655cf1f.PNG)

**Comment by mariuszkrzaczkowski** [comment]
If there is no main file of the module, the module was incorrectly created.
Tested and works on gitdeveloper
