### ISSUE TITLE
YetiForceDialHistory - Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by efernau** [YetiForceCompany/YetiForceCRM#3221]
I am getting this error:

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

Android Version: 6.0.1

**Comment by paula-w** [comment]
Right now we don't provide support for these applications. They were made for a client for a certain version of the system, and only when the client orders an update will we update the applications to work with the latest version of YetiForce.
