### ISSUE TITLE
[bug] Install new Module

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3222]
When i trying to install a module, it fails with this message "Failed: Module does not contain default language"

you can do the following test:
Create a module on gitdeveloper or gitmaster with on field. You cannot import this modul in another instance (i test this with differents version of 3.1.xxx)

**Comment by paula-w** [comment]
Can you send us the zip? You can even attach it here.

**Comment by kpaulaha** [comment]
Open the default language files of exported module in editor and change to utf8. Zip and import, works with Finnish.

**Comment by kpaulaha** [comment]
Although from v 3.1.5xx importing of any module has been broken.

**Comment by SkavenKF** [comment]
@kpaulha: my files are UTF-8 ...
something is strange
the following usecase:
in stable 3.1. i create a modul and would import this in 3.2 (3.1.5xx) 
(export from 3.1.529 and import in 3.1.0 works!)

**Comment by kpaulaha** [comment]
v. 3.1.590 import of custom modules works ok.

**Comment by SkavenKF** [comment]
great, i will check this ;-)

**Comment by SkavenKF** [comment]
Sorry, Paula. I don't know which files you test, but i test it with the files from above. (rename into zip: Test_from_yf31_0.txt => Test_from_yf31_0.zip)
I cannot import anything (from v3.1.0 / v3.1.247 / v3.1.529)
![import1](https://cloud.githubusercontent.com/assets/10259801/16893834/61924a18-4b44-11e6-93a4-eeab2f8e2bfb.JPG)

**Comment by kpaulaha** [comment]
Well, tested my own modules in Finnish language which made with 3.0. Have not tested your ones, but as the message shows, you should upgrade the version of the module.

**Comment by SkavenKF** [comment]
how can i upgrade the version of the module?

**Comment by kpaulaha** [comment]
Change vtiger_version in manifest.xml

**Comment by SkavenKF** [comment]
Ok, now we are on the beginning :-(see my first post)
![import2](https://cloud.githubusercontent.com/assets/10259801/16895531/dab05c7a-4b79-11e6-9551-dc934c12b7dd.JPG)

**Comment by kpaulaha** [comment]
Installed your module, no problem, but I had EN as default language.

![2016-07-16 21_00_29-test - luo](https://cloud.githubusercontent.com/assets/10330264/16896316/9509430c-4b98-11e6-959d-35a1236ba4a7.png)

**Comment by SkavenKF** [comment]
Thank you kpaulaha. The last error was my mistake ;-)
With 590 i can import my modules :-)
