### ISSUE TITLE
Quotes module broken

### ISSUE THREAD

**Issue by readago** [YetiForceCompany/YetiForceCRM#3224]
Hello,

I got a blank page when trying to export a quote to pdf.
In the quote details view, Products related blocks have disappeared (although the are still in quote advanced blocks configuration)
When I try to create a new quote, i get blank page after saving it.
When I'm on a qoute details page, I can't use the left side submenu (slider doesn't work).

Thank you for your support.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by readago** [comment]
Hello,

It happens with the latest version 3.1.247.
Despite the log is turned on, i haven't foud anything which can explain the real cause of the bug.

![yetiforce-issue2](https://cloud.githubusercontent.com/assets/20316038/16730047/e5648068-4770-11e6-9f89-71f7f3ecfad6.gif)
Thank you

**Comment by skramanzia** [comment]
Same in Integration->Currency Update. Is not the first time, Random modules are affected in diferent time. The only solution is clean install and importar new data.
 
![image](https://cloud.githubusercontent.com/assets/3030997/17750811/b5c63724-649a-11e6-8176-50e7bf8d9953.png)

![image](https://cloud.githubusercontent.com/assets/3030997/17750860/e81cc0e4-649a-11e6-9b12-7bf61cf2d874.png)

**Comment by konadrian** [comment]
I can't reproduce the error in the current version. Can you check if you're able to do it at https://gitdeveloper.yetiforce.com/ ?

@skramanzia we believe in the “one issue = one problem” rule. If you want to report an error please create a new issue.
