### ISSUE TITLE
[bug] Error code replacing in "Mail Template"

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3225]
Version: 3.1.529 + f4aad5e

![email template - error reemplacing code](https://cloud.githubusercontent.com/assets/18419851/16725495/689380f0-474f-11e6-8f96-a3adc766549b.gif)

and when i receive the mail in gmail, you can see a new label automatically generated "[Imap]/Sent"

**Comment by WalterLuis** [comment]
Is there any estimated date for this issue?
I tried in previous versions and does not work (3.1.0) (2.3.49)

**Comment by paula-w** [comment]
The variables work when you use the mail properly, which means that for the variables to work for the Contacts module, and for it to paste the name, you have to click Send email right from the contact record. Otherwise it won't work.
