### ISSUE TITLE
Can't install in branches Developer.

### ISSUE THREAD

**Issue by vanloc0301** [YetiForceCompany/YetiForceCRM#3229]
I tried to install YetiForceCRM, but it has problem like a loop in the install.

**Comment by WalterLuis** [comment]
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by vanloc0301** [comment]
Problem that I have is the following (endless) screen. I tried waiting about 1 hours but not have anything.

https://cloud.githubusercontent.com/assets/10259801/14613296/084ed270-059c-11e6-8b96-c4d36821d709.jpg

**Comment by skramanzia** [comment]
@vanloc0301 check this link.
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by bpabiszczak** [comment]
Logs, logs, logs...
