### ISSUE TITLE
Installing the system and result is not an object

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#323]
Need to do to install the system are checked on entry to the folders and files, and the necessary modules. Check for write permission to the folder is in the Settings CRM, but when the system is not installed, as they determine whether the right to put files and folders.

Now faced with the problem that after installation, when you log on I get an error and no logo.

![crm euro-lock ru](https://cloud.githubusercontent.com/assets/1402355/6503391/5a20c18a-c34e-11e4-944d-b4d4581449d8.JPG)
![login crm euro-lock ru](https://cloud.githubusercontent.com/assets/1402355/6503393/60e8cbb6-c34e-11e4-9fa1-b3bcddfb0c0b.JPG)

**Comment by waw555** [comment]
v 1.3.0

**Comment by bpabiszczak** [comment]
Too little time for executing scripts is probably at fault. It is necessary to enable debugging of the application and the server and check the cause. The information that you sent is insufficient, we are not able to do anything without more details.

**Comment by waw555** [comment]
What further information do you want?

What settings or logs show?

What debugging is enabled to make it more fully to find the cause?


Installed Debian 7.8, see the default settings
Of the components during the installation only selects SSH

the rest through apt-get install php, apache, mysql

Further options php and mysql changed on the recommendations on your site

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/ideas,-changes,-bugs/bugs/126-how-to-report-bugs.html
