### ISSUE TITLE
Dav not working probably

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#3230]
Hello together :)

we've tried DAV one month ago and it was working really good.
Now we've tried the stable and the developer version and we get the following result:

![image](https://cloud.githubusercontent.com/assets/12951699/16736822/f370af60-478e-11e6-9b2c-1d4f8d3781fa.png)

We can login with the generated key, but nothing more.
Did we miss something??

Best regards,
Ralph

**Comment by ezbank** [comment]
so many bug

**Comment by mariuszkrzaczkowski** [comment]
This error is when you do not turn on the plugin to your browser. Check https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/api.php#L22
Error does not mean that the DAV does not work.

**Comment by ralphkretzschmar** [comment]
Thank you a lot!! Sorry for the wrong spelling - i thought by working not correctly = maybe i forgot something to activate :+1: Thank you very much.
