### ISSUE TITLE
Portal download PDF Invoice From osspdf

### ISSUE THREAD

**Issue by rezaizadi** [YetiForceCompany/YetiForceCRM#3231]
Hi
How can download PDF at portal from osspdf formats?

**Comment by rezaizadi** [comment]
my yeti ver 2.3.49
and portal 3.1

How i can download a invoice PDF from portal ?

**Comment by rezaizadi** [comment]
How download  a PDF osspdf with soap at portal?

**Comment by paula-w** [comment]
In the latest version we don't support downloading PDFs from the portal.
