### ISSUE TITLE
[BUG] Create an event from an account 

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3232]
There is an error of redirection after the validation of an event creation form from an account.

It returns an error 500 but the event is successfully created.

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by Raggazzoo** [comment]
I upgraded to the 3.1.562 and that's ok.
But I can't import any package language #3223.

Thank's!
