### ISSUE TITLE
I get Sorry! Attempt to access restricted file when i try to delete a ticket

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#3233]
![tickets list](https://cloud.githubusercontent.com/assets/5912376/16760062/5db63594-481a-11e6-893a-7bc3ef41286f.png)

I have set up server config according to the documentation found here https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html but still

All the files on the server are owned by www-data user which is a default user for the server

**Comment by skramanzia** [comment]
@kabelo38 check your files permissions.. may be try to "sudo chmod 755 -Rf *" in yf root folder.

**Comment by kabelo38** [comment]
nah its not related to the file permissions the thing is i did a git pull and re-ran the installation using the existing db values so along those lines something got screwed but for now it works well
