### ISSUE TITLE
storage process

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3238]
hi 
how can i add consumables in storage  process  . for example our products needs some cables that we use them but we do not sales them.

**Comment by vovpff** [comment]
@vahid-jml let's try to use Calculations fot this purposes

**Comment by vahid-jml** [comment]
@vovpff we store this consumables in the warehouse . for example if our production group need this consumables must ask storage group .

**Comment by vahid-jml** [comment]
how to blocked  number of some product  in stock so that sales team can't sales them but for example project manger can use them .

**Comment by vovpff** [comment]
@vahid-jml you can made more substorages. One substorage for sales another one for production. When  you use "Storage Transfer Dispatched Notes" and select consumables storage.
And you can try to made quick mapping from calculation to STDN.

**Comment by bpabiszczak** [comment]
This mechanism would have to be written and added to the system... right now you can try to achieve it, but it has to be done well, and a new module with materials has to be created, with the possibility to relate it to different modules, and with the possibility to also create products from materials.

**Comment by vahid-jml** [comment]
@bpabiszczak  How do I block a number of products in stock .this is more important to me because some time we need some product to another part like projects and we wont sale them but  sales team sees the number of all products in stocks.
