### ISSUE TITLE
Custom View no found error.

### ISSUE THREAD

**Issue by averied** [YetiForceCompany/YetiForceCRM#3242]
Using version [ver. 3.0.36] for testing purposes.

I was trying to add widgets to my home page, and now I get this error.

![image](https://cloud.githubusercontent.com/assets/10140930/16807006/cd0a2a00-490e-11e6-87e0-ee9efcbbc2e1.png)

How can I troubleshoot this error?

- php error log file has nothing
- log files at Yetiforce cache folder have nothing
- All controls are disabled, so I cannot remove or add any widgets, or navigate to other modules with this user.

**Comment by skramanzia** [comment]
@averied check that https://github.com/YetiForceCompany/YetiForceCRM/issues/3234.

Do you have the Spanish language ? where you found the package?

**Comment by paula-w** [comment]
The view that this widget uses has been removed. 
You should remove the widget at the database level. If you enable logs you will see which widget it's about [which one the system can't find] and for which widget the problem exists [5-10 mins of work for a programmer]. As far as I remember in the latest version we avoid it, by not loading widgets whose filters can't be found. 

If the problem occurs on the gitdeveloper version please let us know, someone will fix it.

**Comment by rskrzypczak** [comment]
Cleaning vtiger_module_dashboard table might solve your problem, but you'll delete all wigets as well :)

**Comment by cadre15** [comment]
Hit the same issue on version 2.2.0

**Comment by cadre15** [comment]
I will try 3.1 as 3.2 is not yet on sourceforge

**Comment by InAppDesigns** [comment]
Hello,

This will solve the problem.

Simply delete the widget that is causing the issue located under "vtiger_module_dashboard"

![dashboard](https://cloud.githubusercontent.com/assets/5784818/18023941/1c16e692-6bce-11e6-8dad-d16319d9171d.PNG)

Best of luck!
