### ISSUE TITLE
Please help with cron

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3246]
I have the next cron schedule on a apache web hosting 
*/15	*	*	*	*	crm/cron/vtigercron.sh

and this is the error that i recive.

/home/*****/public_html/crm/cron/vtigercron.sh: line 17: /usr/local/php56/bin/php56: No such file or directory

Can you tell me what shoud i do .... so i can get my cron operation in the crm working?
Or help me with the code to insert into cron operations.

Vers. 3.1.3

**Comment by skramanzia** [comment]
@immhub try to use "Full Path" (absolute path) and add "sh" for example:

*/15 * * * * sh /var/www/sites//crm/cron/vtigercron.sh

**Comment by immhub** [comment]
sh: /var/www/imhubro/public_html/crm/cron/vtigercron.sh: No such file or directory :(

**Comment by skramanzia** [comment]
if you run in linux console: sh /var/www/imhubro/public_html/crm/cron/vtigercron.sh. It executed properly ?.

 Crontab only execute in scheduled a linux command, if you run in console and not work, please check files permissions.

**Comment by immhub** [comment]
I have permision to all my files in corn folder 775.
I dont have access to the linux console, on my webhost.
Is there any other command that i can use?

**Comment by immhub** [comment]
From what i understand, my webserver www.romarg.ro supports all the instalation specified in https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

what am i doing wrong ?

**Comment by skramanzia** [comment]
Only to verify, replace sh to /bin/sh. If not work, should contact the administrator to check logs and linux permissions.

**Comment by immhub** [comment]
/bin/sh: /var/www/imhubro/public_html/crm/cron/vtigercron.sh: No such file or directory

Thank's for trying :(

**Comment by nic86** [comment]
try /bin/bash

**Comment by immhub** [comment]
My web admin said de the corect code is : 
*/15 * * * * sh /home/imhubro/public_html/crm/cron/vtigercron.sh

But i still get the error 
/home/imhubro/public_html/crm/cron/vtigercron.sh: line 17: /usr/local/php56/bin/php56: No such file or directory

**Comment by skramanzia** [comment]
you copy the vtigercron.sh content?

**Comment by immhub** [comment]
#*********************************************************************************
# The contents of this file are subject to the vtiger CRM Public License Version 1.0
# ("License"); You may not use this file except in compliance with the License
# The Original Code is:  vtiger CRM Open Source
# The Initial Developer of the Original Code is vtiger.
# Portions created by vtiger are Copyright (C) vtiger.
# All Rights Reserved.
#
# ********************************************************************************

export VTIGERCRM_ROOTDIR=`dirname "$0"`/..
export USE_PHP=php
export USE_PHP=/usr/local/php56/bin/php56

cd $VTIGERCRM_ROOTDIR
# TO RUN ALL CORN JOBS
$USE_PHP -f cron/vtigercron.php

**Comment by skramanzia** [comment]
Ok, thats the problem.. comment line like this

#export USE_PHP=/usr/local/php56/bin/php56

**Comment by immhub** [comment]
<br />
<b>Fatal error</b>:  Cannot create references to elements of a temporary array expression in <b>/home/imhubro/public_html/crm/vtlib/Vtiger/Functions.php</b> on line <b>1141</b><br />

**Comment by immhub** [comment]
the cron worked, thank you very much :+1: 

that's the eror that i get now

**Comment by skramanzia** [comment]
Check this https://github.com/YetiForceCompany/YetiForceCRM/issues/3143

**Comment by immhub** [comment]
Hello,

I've just updated to 3.1.844 and now the eror that i'm reciving at cron run is : 

<br />
<b>Warning</b>:  session_start(): Cannot send session cookie - headers already sent in <b>/home/imhubro/public_html/crm/libraries/HTTP_Session/Session.php</b> on line <b>160</b><br />
<br />
<b>Warning</b>:  session_start(): Cannot send session cache limiter - headers already sent in <b>/home/imhubro/public_html/crm/libraries/HTTP_Session/Session.php</b> on line <b>160</b><br />
<br />
<b>Fatal error</b>:  Cannot create references to elements of a temporary array expression in <b>/home/imhubro/public_html/crm/vtlib/Vtiger/Functions.php</b> on line <b>906</b><br />


Can you help me with that please?

**Comment by mariuszkrzaczkowski** [comment]
You have the wrong version of PHP please refer to the requirements https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html and 
https://yetiforce.com/en/github/issues/126-issues.html

https://www.google.pl/?ion=1&espv=2#q=Cannot+create+references+to+elements+of+a+temporary+array
