### ISSUE TITLE
Question - Opportunitie Block

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3247]
Hi, Why that opportunities are blocked ?
 
![image](https://cloud.githubusercontent.com/assets/3030997/16850863/4eabb4b6-49d7-11e6-8fa1-e67d19cb729c.png)

**Comment by skramanzia** [comment]
The first OP, not check or modify.

**Comment by skramanzia** [comment]
please tell me if so . When the status is completed or has failed, after a time the task has blocked

whats is this time? can i change?

thanks!

**Comment by ezbank** [comment]
cant change when opportunitie was close

**Comment by bpabiszczak** [comment]
You need set action in profile to add yourself permission to unblock record.
