### ISSUE TITLE
[enhancement] Possibility of creating an custom field 'image' in any module

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3248]
![captura de pantalla 2016-07-15 a las 7 47 55](https://cloud.githubusercontent.com/assets/18419851/16866010/0a41fbe8-4a61-11e6-9d7b-3411771816bc.png)

a field of this type

![captura de pantalla 2016-07-15 a las 7 51 11](https://cloud.githubusercontent.com/assets/18419851/16866065/65596c6e-4a61-11e6-8abc-986ce1748277.png)

and if possible, to be saved in 'YetiForceCRM/storage/image/'

**Comment by paula-w** [comment]
We only add features like that when a client orders them from us.

**Comment by Imaginocharme** [comment]
+1
