### ISSUE TITLE
Calendar Entry

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#3250]
Hello Yetiforce Team,

would it be possible to have an option in the workflow tool, to create calendar events filled with information from custom & standard fields in the crm (Time / Date / Text)?
Maybe you already have the option in the crm, but i didn't find it?

e.g.:
1. an account is set on a certain status then
2. workflow makes a calendar entry with information from certain fields (e.g: Timefield / Datefield)

Best regards,
Ralph

**Comment by paula-w** [comment]
When you create a To Do in the calendar at the workflow level, you get the option to set fields available in the calendar module, eg. setting the start and end date to X days from the creation date. 
The fields that can be set in workflow are hard-coded, it can be improved in the future, but right now it has a low priority for us, until somebody orders that from us.

**Comment by ralphkretzschmar** [comment]
Hi Paula,

just thought it could be useful - thank you a lot for the update.
i'll try the newest developer version today :)

Best regards,
Ralph
