### ISSUE TITLE
Roundcube - Błąd połączenia z serwerem!

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#3251]
Działało i przestało. Przy próbie zalogowania do serwera pocztowego taki komunikat dostaję
Błąd połączenia z serwerem!
nic nie zmieniałem działało i przestało. Gdzie szukać przyczyny?

**Comment by bpabiszczak** [comment]
W LOGACH !!!! To jest magiczne miejsce z odpowiedziami na wszystkie nasze pytania, jeżeli logi aplikacji nie odpowiedzą nam na pytanie wówczas logi serwera pocztowego to zrobią :]
