### ISSUE TITLE
Create a ticket using Workflows

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#3253]
Okay so i got mail scanner working and mails can be found on the mail box 

![workflow](https://cloud.githubusercontent.com/assets/5912376/16875186/5a28a2fa-4a9e-11e6-96b5-d1c4d41f9184.png)
![workflow_filter](https://cloud.githubusercontent.com/assets/5912376/16875184/5a246078-4a9e-11e6-9f9e-8a1c547296c3.png)
![workflow_todo](https://cloud.githubusercontent.com/assets/5912376/16875185/5a258192-4a9e-11e6-8ed2-e3a37493b830.png)

So i want when a user sends a mail to disemail@domain.com, mail scanner finds the mail but now i want whenever mail scanner finds any new mail on coporeate mail to automatically create a new ticket i tried workflows but when i get to the last step on the to-do functionality i get limited options someone please help.

**Comment by rskrzypczak** [comment]
Mail scanner doesn't search for new emails in corporate mail, it only adds them there using actions set in configuration.
In configuration you can also set whether or not a ticket should be created.
![image](https://cloud.githubusercontent.com/assets/10221999/17548767/a7d04536-5eed-11e6-85ff-5037979bfdc9.png)
