### ISSUE TITLE
storage process

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3254]
hi 
How do I block a number of products in stock .this is more important to me because some time we need some product to another part like projects and we wont sale them but sales team sees the number of all products in stocks.

**Comment by rskrzypczak** [comment]
I don't completely understand what you mean, but if you want to remove the field "Quantity of product in stock" then it's not an option. 
![image](https://cloud.githubusercontent.com/assets/10221999/18003489/2c1d480a-6b8e-11e6-83e9-8ccc68a3423f.png)
All you can do is comment the code here ..
**Storages**
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/IStorages/models/RelationListView.php#L13
and function getHeaders() - all
**Products**
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Products/models/RelationListView.php#L15
and lines 41-49

Remaining fields can be configured [here](https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&block=2&fieldid=41).

However, if you want to disable counting stock for individual modules, then they are listed here ([link](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/IStorages/handlers/RecalculateStockHandler.php#L16))
