### ISSUE TITLE
Invoice, Tax Problem

### ISSUE THREAD

**Issue by CobaJashi** [YetiForceCompany/YetiForceCRM#3255]
Hello :)

Step 1. We add new tax

![fireshot capture 127 - erweiterte module_ - http___crm megabutler eu_index php](https://cloud.githubusercontent.com/assets/20491699/16895524/8583043c-4b79-11e6-96d7-8347fa7215d7.png)

Step 2. We add under the Taxes Customization - Individual

![fireshot capture 126 - erweiterte module_ - http___crm megabutler eu_index php](https://cloud.githubusercontent.com/assets/20491699/16895620/3f4b6604-4b7d-11e6-9e59-1553fe374336.png)

Step 3. We create an invoice and add a product with 19% vat, but nothing happened. Ideas?

![fireshot capture 135 - rechnungen - hinzufugen_ - http___crm megabutler eu_index php](https://cloud.githubusercontent.com/assets/20491699/16895598/9a5a4688-4b7c-11e6-9bf2-4147afb317ff.png)

additional question, where can i find and change it these vats 

![fireshot capture 132 - produkte - hinzufugen_ - http___crm megabutler eu_index php](https://cloud.githubusercontent.com/assets/20491699/16895615/104781c6-4b7d-11e6-8e5b-77d9491b4432.png)

Thank you in advance :)

**Comment by kpaulaha** [comment]
You have to set the tax and choose group or individual. Sorry, image in Finnish.

![tax](https://cloud.githubusercontent.com/assets/10330264/16896395/fd9e3060-4b9a-11e6-8411-b4b176398642.png)

**Comment by dextras** [comment]
@CobaJashi 
First answering your additional question: When you select the tax you will be able to change it inividually on every product. Unless you are asking about the change of the default values. Then I do not know ;)

Regarding your original question: I believe that you want to see the same functionality as I am expecting in #3097? If yes than it is currently (probably) work in progress and will be out with 3.2.

**Comment by CobaJashi** [comment]
Thank you for your Answers, the first solution helps for first :)
