### ISSUE TITLE
[BUG] Widget chart from filter, only pie chart can show

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3261]
![animation](https://cloud.githubusercontent.com/assets/19627226/16955009/54c4cb92-4dfd-11e6-983c-a1e5b6a5a391.gif)

**Comment by skramanzia** [comment]
Test in the the latest version. Related bugs was corrected

**Comment by ezbank** [comment]
This is latest version. 3.1.620

**Comment by ezbank** [comment]
ok but widget Lead by status, Lead by source not show 
![nh ch p man hinh 13](https://cloud.githubusercontent.com/assets/19627226/16955608/803229da-4dff-11e6-915d-880bfdbc2934.png)
