### ISSUE TITLE
Lincense in YetiForeCRM?

### ISSUE THREAD

**Issue by vanloc0301** [YetiForceCompany/YetiForceCRM#3264]
I'm a developer; I want to fork your project and custom to my case. Have I been allowed to do it?

YetiForceCRM is free or commerce?

Add other:

I see about 250 table in a database installed YetiForce, all table is necessary?

Thanks.

**Comment by bpabiszczak** [comment]
this is open source [100% free]: https://yetiforce.com/en/github/license.html
