### ISSUE TITLE
Activity type 

### ISSUE THREAD

**Issue by CobaJashi** [YetiForceCompany/YetiForceCRM#3266]
Hello :)
Those looking for does not ...
Where can I Activity type add?
We need other types

Thank you in advance :)

![fireshot capture 136 - calendar - edit_ - http___crm megabutler eu_index php](https://cloud.githubusercontent.com/assets/20491699/16980696/9880a4ae-4e67-11e6-875a-eae8778bf60a.png)

**Comment by nic86** [comment]
Software configuration  > Standard modules >  Fields – Picklists 

select module(events) and picklist in Events(activity type)

click on button add value.

**Comment by CobaJashi** [comment]
Thanks :+1:
