### ISSUE TITLE
Image uploading issue

### ISSUE THREAD

**Issue by pathegs** [YetiForceCompany/YetiForceCRM#3267]
I can not upload image when adding or editing contact, after saving all data appear correctly but image doesn't appear.

Samething when editing company information, I can not change the logo image, it says "Invalide image", (used image format: 256x256 png)

The site is hosted on production linux server with cpanel.

Please help

**Comment by StaggerLeee** [comment]
I had this problem but you can kill me now dont remember how was it fixed.

Try to hard reset your browser and delete cache.

**Comment by pathegs** [comment]
@StaggerLeee 
I fixed it just by enabling fileInfo (PHP config) 
Thanks

**Comment by StaggerLeee** [comment]
Yes, it was that. Bravo.
