### ISSUE TITLE
Is there any way to clear history

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3269]
I have just updated to the latest version of 3.1x in the update area. 

I think in a previous version of Yetiforce there was a Clear History button that allowed us to clear the recent history widget. At the moment I am playing around with the system, but once I start using it, I would really like to start with a clean slate - with no previous history. 

For the same reason, is there any way to remove other test data (i.e. when testing the setup of the email it adds the latest email messages in a most recent emails box). I saw somewhere that clearing the CRMEntity table would do this, but would this also wipe out for example, any new PDF templates I have created?

Kind regards

Percy

**Comment by paula-w** [comment]
Hi.
When you do something in the system that you then plan to delete, then the best option would be to do it on the test version. YetiForce doesn't have any built-in mechanisms used to revert changes.
