### ISSUE TITLE
Variables, invoices

### ISSUE THREAD

**Issue by CobaJashi** [YetiForceCompany/YetiForceCRM#3270]
Hello :)
there is a list of variables?
We want to create the invoice PDF.
We have served us the variables from the sales order but they do not work.

for example:

![bild](https://cloud.githubusercontent.com/assets/20491699/17021887/222b459a-4f4b-11e6-9d3f-d044bc30b3cb.jpg)

Ideas?

**Comment by konadrian** [comment]
I can't reproduce the error, please check if the error still exists, and if so then :
1. Let me know what language the user is using in crm
2. Please pay attention to the capitalization of letters in variables - correct "%accountid+Accounts+accountname%"; incorrect "%ACCOUNTID+ACCOUNTS+ACCOUNTNAME%".
