### ISSUE TITLE
EMail do not apeear as sent

### ISSUE THREAD

**Issue by CobaJashi** [YetiForceCompany/YetiForceCRM#3271]
Hello :)
We send e-mails, but they do not appear in crm as sent.

![fireshot capture 139 - kontakte - details_ - http___crm megabutler eu_index php](https://cloud.githubusercontent.com/assets/20491699/17026999/5c2b1c40-4f62-11e6-83a0-1d9b78c4f3aa.png)

also not relationships for partners

![fireshot capture 140 - meine mailbox_ - http___crm megabutler eu_index php](https://cloud.githubusercontent.com/assets/20491699/17027674/18f6da9c-4f65-11e6-9bbd-5fa23919652c.png)

notice: mail doesn´t found in the database

![fireshot capture 142 - meine mailbox_ - http___crm megabutler eu_index php](https://cloud.githubusercontent.com/assets/20491699/17029754/c161384c-4f6c-11e6-8f85-b27d60476c53.png)

Ideas :)

**Comment by kpaulaha** [comment]
And you have konfigured cron?

**Comment by CobaJashi** [comment]
Thanks for the answer :)
as I see it, yes. 

![fireshot capture 144 - cron aufgaben_ - http___crm megabutler eu_index php](https://cloud.githubusercontent.com/assets/20491699/17031454/9546d9f8-4f74-11e6-8810-bf825ee089f1.png)


Configured I also MailScanner see below

https://yetiforce.com/en/administrator-documentation/panel/mailbox/mail-scanner/135-mail-scanner.html

more ideas like :)

**Comment by kpaulaha** [comment]
I meant cŕon on server

**Comment by CobaJashi** [comment]
It works. Thanks :)
