### ISSUE TITLE
Unable to Upload images in email workflow designer

### ISSUE THREAD

**Issue by acidhunter** [YetiForceCompany/YetiForceCRM#3275]
Version 3.1.622

The size of the file i tried to upload is 4kb
![image](https://cloud.githubusercontent.com/assets/8077558/17056673/395c8a60-5015-11e6-8fa4-119b042086c0.png)

Where are the images located?

**Comment by konadrian** [comment]
Can you show exactly where you upload pictures into the crm (screen, gif), it would be very helpful in order to give you an answer.
