### ISSUE TITLE
Sms configuration

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3277]
Hi everyone, 

I am new to YF and it is a great product.  I am only typical user,  and it is very intuitive.

I  have question  about sms configuration.  I looked at all modules,  settings and could not find configuration for sms. 

Can I add custom provider with its api parametars.?

**Comment by vahid-jml** [comment]
hi
go to setting and click on module shortcut and find Text messages module
![smsnotification](https://cloud.githubusercontent.com/assets/18072100/17099031/ffec3dc6-527a-11e6-92ea-6e2ca0f8eb84.png)
and then click on 'server configuration' 


![provider](https://cloud.githubusercontent.com/assets/18072100/17099128/9648eb2a-527b-11e6-80c4-80e756528025.png)

for adding custom provider you have to write your own provider . 
go to yetiforce directory and go to modules/SMSNotifier/provider . in this directory you can see two file 1-ClickATell.php  and  2 - MyProvider.php  . for creating your own provider you have to create a php file like MyProvider.php .

**Comment by ldgbc** [comment]
I'm trying to figure out if there is a better in-house alternative. I found this and it something that too advance for me. Hopefully someone more technical skill can help. This is something I'll consider looking into 1 year time in future.

https://github.com/typpo/textbelt
