### ISSUE TITLE
Photo field -to make foto gallery? 

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3278]
Is there any way to add photos that are related to account?  There is no photo (image)  field as I can see. 
I see that I can add url of photo,  but it would be great to have previw of it,  and able to write some description. 

I want to make "gallery" (in custom module, and relate it to account). 
Is this possible??

Is there any language pack for Serbian language (or Croatian,  Bosnia)? 

Please help.  Regards from Serbia

**Comment by serbiaserbia** [comment]
Does this field  (photo-image) can be expected in version YF 3.2?

Best regards

**Comment by bpabiszczak** [comment]
NO

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/3248
