### ISSUE TITLE
Cron job -on shared server - no comand line available

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3279]
Hi everyone,

How to set cron job if I dont have access thru command line to the server?? I am on shared server.

In other experiance with SuiteCRM I deleted some lines in cron file and used web site to start cron jobs (like crondash.com, cron-job.org etc.). It worked very well.

Best regards from Serbia

**Comment by vahid-jml** [comment]
you can use vtigercron.php in  cron directory . but you have to add some changes to it .

**Comment by serbiaserbia** [comment]
Ok, do you have any suggestion for changes?

**Comment by serbiaserbia** [comment]
I registered on crondash.com for cron jobs. 
Made connection with http://myhostname/yeti/cron/vtigercron.php

In YF at Cron Jobs it writes they are active.
here is screenshot
![yf cron](https://cloud.githubusercontent.com/assets/19521910/17078679/529c098a-50f9-11e6-889a-06656e8954a3.png)

crondash.com properties for cron job, screenshot:
![cronweb](https://cloud.githubusercontent.com/assets/19521910/17078682/76c15fd6-50f9-11e6-8b14-35eff6d8eeb8.png)

What do you think about this ways of launching cronjobs?
Does this meet the needs of YetiForce?

**Comment by vahid-jml** [comment]
cron job work properly with no problem . and that's all that  YetiForce need .

**Comment by serbiaserbia** [comment]
Awesome! Much easier to adjust than in SuiteCRM & SugarCRM

**Comment by bpabiszczak** [comment]
![campare_suitecrm_vs_yetiforce](https://cloud.githubusercontent.com/assets/10197525/17086814/e094cfd0-51fb-11e6-8685-cd38b69f48a8.png)
