### ISSUE TITLE
[BUG] Searching users dont work

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3280]
![animation](https://cloud.githubusercontent.com/assets/19627226/17076036/cc7aaf90-50d1-11e6-87bf-71d4016f38f8.gif)

**Comment by bpabiszczak** [comment]
I tested today GitDeveloper and working properly.

**Comment by ezbank** [comment]
Testing on ver. 3.1.651 dont work. 
![animation](https://cloud.githubusercontent.com/assets/19627226/17088052/34f3556c-5240-11e6-89c2-122bac20b98d.gif)

**Comment by WalterLuis** [comment]
I tried it and it works well in 3.1.651.
try to re-install it again

**Comment by ezbank** [comment]
Help me :(
![screenshot 1](https://cloud.githubusercontent.com/assets/19627226/17093775/6f32c660-5275-11e6-873b-f872270a26cc.png)

![screenshot 2](https://cloud.githubusercontent.com/assets/19627226/17093804/9a8f6fd4-5275-11e6-9f67-3f19a7276815.png)

**Comment by paula-w** [comment]
Hi,
We can't help you because the error only exists in your system. 
The first screenshot tells you that you don't have the database access, you should check that. 
We can check it for you, but we would have to charge for that.

**Comment by WalterLuis** [comment]
apparently the user (equrzutl) that use of the database does not have permissions.
try to use the user (root) from your database editing file in
"/home/equrzutl/public_html/ezwork/dev3/config/config.inc.php" 
$dbconfig['db_username'] = 'root';
$dbconfig['db_password'] = 'your-password';

**Comment by ezbank** [comment]
it works well in 3.1.664. Thanks all. :)
