### ISSUE TITLE
Values assigned to a Role (Opportunities)

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3281]
How to add values assignment
![nh ch p man hinh 19](https://cloud.githubusercontent.com/assets/19627226/17083801/43818754-51d5-11e6-8090-b936dd2c7a46.jpg)

**Comment by CobaJashi** [comment]
right side > add value

**Comment by bpabiszczak** [comment]
https://wiki.vtiger.com/index.php/UI_Types
16 > 15
