### ISSUE TITLE
[BUG] History Widget Errror

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3282]
Since the 3.1.662 the module widget doesn't display actions related to account, leads or opportunities. (red rectangles)
Howerver it works for events.

![capture](https://cloud.githubusercontent.com/assets/1357727/17102262/1dc79432-5279-11e6-862f-6452b303cf25.PNG)

**Comment by Raggazzoo** [comment]
On account, lead or opportunity page the bug doesn't display the name of the occurence.
![sans titre](https://cloud.githubusercontent.com/assets/1357727/17131056/d4a9338e-531b-11e6-8cc5-69d9f62d472c.png)
(I hide the assignation)

**Comment by Raggazzoo** [comment]
It seems to be linked to my ticket on global search #3305, It is really hassle because I can't create organisation or contacts too.

I was forced to downgrade to 3.1.629.

**Comment by konadrian** [comment]
This error doesn't exist in a new version
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/17888800/f6e37cee-692c-11e6-8bc3-5c72400b135e.png)

**Comment by Raggazzoo** [comment]
Yes but with my 3.1.629 database the problem is still here... #3404
