### ISSUE TITLE
[ENHANCEMENT] "Select all" from 1:M list

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3285]
It could be nice to have a "select all" link like in account or leads in 1:M popup lists

![image](https://cloud.githubusercontent.com/assets/1357727/17105867/41c96666-5289-11e6-9cb3-0f9a7f6a2571.png)

**Comment by paula-w** [comment]
Right now we're not planning to add this feature.
More info on [why issues are ignored](https://yetiforce.com/en/github/issues/205-why-was-the-issue-ignored.html), and [development ideas](https://yetiforce.com/en/github/issues/206-system-development-ideas.html).
