### ISSUE TITLE
[BUG] Display chat on PHP 7

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3288]
![animation](https://cloud.githubusercontent.com/assets/19627226/17112088/abf1a9aa-52ce-11e6-9b8b-dce7e8b237b0.gif)

**Comment by konadrian** [comment]
As @skramanzia said, this chat version doesn't support PHP7

**Comment by paula-w** [comment]
The chat in the current version will be removed from the system. It's way too complex and includes tons of useless options, it will be quite soon substituted by a simple and integrated chat.
