### ISSUE TITLE
Make questionnaire (survey) related to record

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3289]
Is there a way and if anybody has an idea how to make a questionnaire (survey) which will be linked to the account?

I want to make many surveys that employees must complete for certain clients that we have in the database. The survey would be more kind, and they would be exchanged in accordance with the goals.

Best regards from Serbia.

**Comment by vahid-jml** [comment]
hi 
you can create custom module for yourself and create any fields you want .
for example go to setting and click in module shortcut and then click on 'create module' button and create a module 
![module](https://cloud.githubusercontent.com/assets/18072100/17115162/55cb60f4-52c7-11e6-824e-a8b98d612a89.png)

then you can create fields for module.

![createfiled](https://cloud.githubusercontent.com/assets/18072100/17115192/7ef414a8-52c7-11e6-9ac5-cfb8a651f263.png)

**Comment by serbiaserbia** [comment]
Ok for new module,  that is clear I have to made.  I will make new task for each account and questionaire  that have to be filled by employee. 
But how to make for example 20 different surveys with 10 different questions for each survey. 
It is a lot of fields in one page -module.  It cant be logic to make 20 different modules. 
How to displey only survey that employee have to fill? 

Regards

**Comment by serbiaserbia** [comment]
Ok for new module, that is clear I have to made. I will make new task for each account and questionaire that have to be filled by employee. 
But how to make for example 20 different surveys with 10 different questions for each survey. 
It is a lot of fields in one page -module. It cant be logic to make 20 different modules. 
How to displey only survey that employee have to fill?

Regards
