### ISSUE TITLE
Install v3.1

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#3290]
Error

`
Strict Standards: Declaration of AntlrLexer::matchAny() should be compatible with BaseRecognizer::matchAny($input) in /home/public_html/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::recover() should be compatible with BaseRecognizer::recover($input, $re) in /home/public_html/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /home/public_html/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /home/public_html/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrParser::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /home/public_html/libraries/antlr/AntlrParser.php on line 98

Strict Standards: Declaration of AntlrParser::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /home/public_html/libraries/antlr/AntlrParser.php on line 98

Strict Standards: Declaration of Users::saveentity() should be compatible with CRMEntity::saveentity($module, $fileid = '') in /home/public_html/modules/Users/Users.php on line 1496

Strict Standards: Declaration of Users::uploadAndSaveFile() should be compatible with CRMEntity::uploadAndSaveFile($id, $module, $file_details, $attachmentType = 'Attachment') in /home/public_html/modules/Users/Users.php on line 1496

Strict Standards: Declaration of Users::insertIntoEntityTable() should be compatible with CRMEntity::insertIntoEntityTable($table_name, $module, $fileid = '') in /home/public_html/modules/Users/Users.php on line 1496

Strict Standards: Declaration of Users::save() should be compatible with CRMEntity::save($module_name, $fileid = '') in /home/public_html/modules/Users/Users.php on line 1496

Strict Standards: Declaration of Users::get_column_value() should be compatible with CRMEntity::get_column_value($columnname, $fldvalue, $fieldname, $uitype, $datatype = '') in /home/public_html/modules/Users/Users.php on line 1496

Strict Standards: Declaration of Contacts::save_related_module() should be compatible with CRMEntity::save_related_module($module, $crmid, $withModule, $withCrmid, $relatedName = false) in /home/public_html/modules/Contacts/Contacts.php on line 978

Strict Standards: Declaration of Vtiger_LanguageExport::export_Dependencies() should be compatible with Vtiger_PackageExport::export_Dependencies($moduleInstance) in /home/public_html/vtlib/Vtiger/LanguageExport.php on line 17

Strict Standards: Declaration of Vtiger_LanguageImport::initImport() should be compatible with Vtiger_PackageImport::initImport($zipfile, $overwrite = true) in /home/public_html/vtlib/Vtiger/LanguageImport.php on line 17

Strict Standards: Declaration of Vtiger_View_Controller::preProcessTplName() should be compatible with Vtiger_Action_Controller::preProcessTplName() in /home/public_html/include/runtime/Controller.php on line 506

Warning: Cannot modify header information - headers already sent by (output started at /home/public_html/libraries/antlr/AntlrLexer.php:297) in /home/public_html/include/main/WebUI.php on line 110`

> Apache	2.2.31
PHP	5.6.22
MySQL	5.5.50-cll
linux x86_64
Sendmail	/usr/sbin/sendmail
Perl	/usr/bin/perl
Perl	5.10.1
Core 2.6.32-573.22.1.el6.x86_64

**Comment by mariuszkrzaczkowski** [comment]
Check the server configuration, output_buffering
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html#server

**Comment by waw555** [comment]
Oh, please forgive me, not copied, apologize when copying htaccess. Hurry)))
