### ISSUE TITLE
[BUG] Blank page when export - PHP 7

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3291]
![animation](https://cloud.githubusercontent.com/assets/19627226/17127650/6e218a6a-5331-11e6-8a63-22c159c2f3ce.gif)

**Comment by TomaszQr** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/a8931ad396d8382b2b9b9f527b2e107639c5b99e
