### ISSUE TITLE
[ENHANCEMENT] Add mass edit option in action menu for events list

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3296]
Is it possible to add an option "Mass edit" in the menu actions for the list of events?

![image](https://cloud.githubusercontent.com/assets/1357727/17129831/95413508-5315-11e6-97e7-44d4570675dc.png)

Thank's !
note : YF is unbelievable :+1:

**Comment by KatarzynaUlichnowska** [comment]
This function is far down the list of our priorities. It can be added faster if someone pays for it. Please read this article: https://yetiforce.com/en/github/issues/206-system-development-ideas.html
