### ISSUE TITLE
[enhancement] possibility of sending email marketing

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3297]
Good Morning,

Is it planned? or Is there a possibility that the mailing be oriented also to mail marketing?

Currently using 'RoundCube' if you select multiple contacts groups all contacts in a single message. If they are customers, also you would be showing each client mail that was sent this email (and in my opinion would be nice to avoid that).
Currently (at least that I was wrong in something), in the hypothetical case where you want to send a mass mailing to multiple contacts with personalized content for each contact you can not.

P.D: in 'roundcube_users' the password is stored in plain text when you sign in 'RoundCube' (image)
![mail](https://cloud.githubusercontent.com/assets/18419851/17130156/032dbaca-530f-11e6-9bf2-cc2799d7176e.PNG)

**Comment by KatarzynaUlichnowska** [comment]
1. In the future, we are planning to add a very complex marketing module, but we are waiting for someone to pay for it, so you will have to be patient as we don't know when it will be ordered. 
2. In the future, passwords and connections will be encrypted.
