### ISSUE TITLE
[BUG] Assets

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#3299]
![animation 193](https://cloud.githubusercontent.com/assets/1402355/17130691/4a43cfac-5333-11e6-9837-4654d177df41.gif)

**Comment by vovpff** [comment]
@waw555 there is no Time control at dev version:
![image](https://cloud.githubusercontent.com/assets/8545791/17167735/52048e3e-53e7-11e6-92b5-b3c031df1ab9.png)

**Comment by waw555** [comment]
v 3.1

**Comment by rskrzypczak** [comment]
@waw555 you're right, it's an error in 3.1, but we fixed it already. 

Actual relation between Assets and Time Control is missing.  Can't relate a time control record with Assets, no 1:M relation. The only thing that remains is a tab that should be removed (https://github.com/YetiForceCompany/YetiForceCRM/commit/46fa876281e30d8ff552e959c0aae8e505dd3f77).
