### ISSUE TITLE
[QUESTION] Concatenate fields

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3300]
Is it possible to make an autofill field which concatenate two other fields?
I want to format the opportunity subject field with the type and add the opportunity number.

Thank's!

**Comment by vovpff** [comment]
@Raggazzoo check this:
![concat oppo name](https://cloud.githubusercontent.com/assets/8545791/17153384/2db1426e-5385-11e6-9f40-9df8325c32ab.gif)
To avoid subjects lise s-sp# pll_new_sales you can made more hardest expression like this:
`if ssalesprocesses_type == 'PLL_NEW_SALES' then concat(ssalesprocesses_no,' New Sales') else if ssalesprocesses_type == 'PLL_AFTERSALES' then concat(ssalesprocesses_no,' Aftersales')  else end` and etc.

**Comment by vovpff** [comment]
@Raggazzoo every time you must fill subject manually because there is no possibility to uncheck mandatory field status.

**Comment by Raggazzoo** [comment]
Nice Thank you !

**Comment by ldgbc** [comment]
Thank you @vovpff these thing are pretty hidden away. You should contribute these tips to Wiki (if one exist) in the future.

Thank you again.

**Comment by vovpff** [comment]
@ldgbc I have some experience with additional Functions applicable to expression for examle concat with separator.
