### ISSUE TITLE
[ENHANCEMENT] Widget note

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3303]
To simplify taking note, it should has automatic recording fuction if has any change, instead of doing manualy

![animation](https://cloud.githubusercontent.com/assets/19627226/17136204/4124b8f2-535e-11e6-9ad2-773902865883.gif)

**Comment by paula-w** [comment]
You want it to save, without having to click the "save" button? Please clarify.

**Comment by ezbank** [comment]
Hii. That's it :)
