### ISSUE TITLE
[BUG] Quick search doesn't work anymore

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3305]
The quick search doesn't work anymore on 3.1.676, it returns no result.

I try to update the labels manually but there is no change.

**Comment by mariuszkrzaczkowski** [comment]
Global search engine was rebuilt check for the latest version

**Comment by Raggazzoo** [comment]
I applied the 3.1.686 and the problem is not fix for me.

Thank"s

**Comment by Raggazzoo** [comment]
I make a fresh install and I still got that problem.

Now I'm on 3.1.698.
![image](https://cloud.githubusercontent.com/assets/1357727/17174646/4a20cc16-5403-11e6-9e6a-3e2e9c65e77a.png)

**Comment by Raggazzoo** [comment]
I returned to 3.1.671 because after this version my accounts and leads do not appear in history widget and I got no quick search. #3282

Does it could be a database update problem?

In 3.1.698 with my database I could not add  an account or edit an event...

Thank's!

**Comment by mariuszkrzaczkowski** [comment]
We're rebuilding global search right now, you have to wait until we finish.

**Comment by Raggazzoo** [comment]
Ok I will wait !

Thank you!

**Comment by Raggazzoo** [comment]
Hi !

I updated to 3.1.756 and my problem is still here.

Thank's !

**Comment by Raggazzoo** [comment]
There is the error when I try to edit a lead
![image](https://cloud.githubusercontent.com/assets/1357727/17288469/968e677c-57d5-11e6-838a-9845fe51ec35.png)

I only get the fatal error when I edit an organisation.

**Comment by Raggazzoo** [comment]
Is anyone got the same issue? I can't move forward because of this error...

**Comment by jstorchia** [comment]
Check , https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html and your server configuration coincide with the requirements

**Comment by Raggazzoo** [comment]
It perfectly works before, there is my configuration
![image](https://cloud.githubusercontent.com/assets/1357727/17299689/a2c4b994-580f-11e6-8ab5-b180830d5e1e.png)
![image](https://cloud.githubusercontent.com/assets/1357727/17299699/b16d8fd4-580f-11e6-861a-6baa58b16ab8.png)
![image](https://cloud.githubusercontent.com/assets/1357727/17299709/c11148b8-580f-11e6-82a7-a56e7560f399.png)
![image](https://cloud.githubusercontent.com/assets/1357727/17299795/04292b34-5810-11e6-9032-13a9846d8a3c.png)

**Comment by Raggazzoo** [comment]
Is it innodb_lock_wait_timeout ?

**Comment by Raggazzoo** [comment]
I will try to rebuild my database...

**Comment by Raggazzoo** [comment]
I successfully export and import leads, organisations, contacts and campaigns but I can't do it for events import failed.

How can I move to my new crm the history of changes?

PS : search still doesn't work in my new configuration after update labels

**Comment by jstorchia** [comment]
you have to wait  , check here .

https://github.com/YetiForceCompany/YetiForceCRM/milestone/15

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3348
