### ISSUE TITLE
Again - Make questionnaire (survey) related to record - related to #3289

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3307]
my previous question - issue #3289

I need some more help. Previously issue (#3289) is closed. I did not had time to continue the discussion.

My additional question is:

Ok for new module, that is clear I have to made. I will make new task for each account and questionaire that have to be filled by employee. 
But how to make for example 20 different surveys with 10 different questions for each survey. 
It is a lot of fields in one page -module. It cant be logic to make 20 different modules. 
How to display only survey that employee have to fill?  I'm confused :-(

Regards...

**Comment by vovpff** [comment]
@serbiaserbia quick solution is to add 20 Custom Blocks to custom module. Every block is contains 10 fiels (questions) and collapsed by default. Your empoyee open needed block and fill all fields what available fot his block.
Sorry for advertisement of commercial vtiger teams but great idea to add features in future like this modules:
https://www.vgsglobal.com/extensions/vtiger-dynamic-blocks/ this is great solution for @serbiaserbia task
and
http://www.its4you.sk/en/vtiger-extensions/dynamic-fields

**Comment by nic86** [comment]
it's already possible hide block in edit and detail view for one or more conditions:
https://gitdeveloper.yetiforce.com/index.php?module=HideBlocks&parent=Settings&view=List&block=2&fieldid=72

**Comment by vovpff** [comment]
@nic86 thx a lot! I never tried this in a past. This is too usefull
