### ISSUE TITLE
[BUG] YetiForce Portal v 3.1.2

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#3309]
It does not work Cyrillic

The branch with the portal could not add

![animation 194](https://cloud.githubusercontent.com/assets/1402355/17163447/e6f7c22c-53d8-11e6-9a19-88b1a5f13a7a.gif)

**Comment by vahid-jml** [comment]
i had the same error.
this is because soapclient encoding , in YetiForce Portal/index.php line 23 . comment this line and it work.
i think this is because  characters had twice encoded .

**Comment by rskrzypczak** [comment]
and https://github.com/YetiForceCompany/YetiForcePortal/commit/1995b0c2a90c5dbc95bfacb8d98207b507c720df
