### ISSUE TITLE
ossmail slowing down system

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#331]
What do I need to do to find out why oss mail is slowing down the system so much?

I read your article but it didn't give me specifics. Where should I look?

**Comment by bpabiszczak** [comment]
"If the above test will not be successful, we suggest something different. It is necessary to enable debugging in Roundcube so you will be able to track every enquiry sent to the server and its response time. If the response time of Roundcube is taking longer and longer, it means that the server cannot cope with the work. Most often the enquiries will take over 90% of the loading time for the entire CRM."
