### ISSUE TITLE
[BUG] - Dupicated field for update field workflow (Opportunity)

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3310]
Yesterday evening I found this bug in dev version:
![dup add field 2](https://cloud.githubusercontent.com/assets/8545791/17168326/824df942-53ea-11e6-9c3a-63b647a8a82a.gif)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/fa392137754e194c8459d3ec32d20039ab56ff84
