### ISSUE TITLE
default record owner

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3313]
hi
how to add default record owner to some module .
for example i want to support team will be the owner of all tickets records that create in the crm.

**Comment by bpabiszczak** [comment]
First set on role [Can assign records to: = From panel]
Second go here: https://gitdeveloper.yetiforce.com/index.php?module=RecordAllocation&view=Index&parent=Settings&type=owner&block=1&fieldid=101
