### ISSUE TITLE
customizing the default theme

### ISSUE THREAD

**Issue by mutchris5** [YetiForceCompany/YetiForceCRM#3314]
hi i would like to change the default logo and upload my company logo and also change the general company information please help me out on this subject

**Comment by mutchris5** [comment]
hi how would i configure the customer portal the link on https://yetiforce.com/en/implementer/installation-updates/129-customer-portal-instalation.html doesnt explain it well please be specific espacially at what is changed in the config/config.php file and Config/API.php....i have very much liked the tool but configuring the customer portal and change the default logo and footer are a big problem

**Comment by ezbank** [comment]
System setting >> Company Information >> Company Details >> Edit
Link: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Vtiger&view=CompanyDetails&block=3&fieldid=14

**Comment by paula-w** [comment]
Please open a new issue about portal configuration. We like to follow the rule of one question per issue. Otherwise it gets messy.

**Comment by mutchris5** [comment]
hi how would i configure the customer portal the link on https://yetiforce.com/en/implementer/installation-updates/129-customer-portal-instalation.html doesnt explain it well please be specific espacially at what is changed in the config/config.php file and Config/API.php....i have very much liked the tool but configuring the customer portal and change the default logo and footer are a big problem

**Comment by nzi200779** [comment]
HI what settings do I need to change for my side menu to look as the example below

System setting >> Company Information >> Company Details >> Edit
Link: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Vtiger&view=CompanyDetails&block=3&fieldid=14
