### ISSUE TITLE
[BUG] Kalendarz 

### ISSUE THREAD

**Issue by ROBiBOB** [YetiForceCompany/YetiForceCRM#3315]
Tworzenie Terminów  i  Zadań 
![jul-28-2016 12-14-06](https://cloud.githubusercontent.com/assets/16098743/17209495/8eaccc1c-54bd-11e6-8e06-b447e9ac140a.gif)

**Comment by bpabiszczak** [comment]
a co na to wersje demonstracyjne? Zalogowałem się tutaj: https://gitstable.yetiforce.com i to ta sama wersja co u Ciebie, czy umiesz wywołać ten błąd na tej wersji, ponieważ mi działa prawidłowo.

**Comment by ROBiBOB** [comment]
Wersja demonstracyjna podobnie;
Wprawdzie jakiś ślad w kalendarzu zostaję ale nie z tymi danymi
które były wpisywane;
![jul-28-2016 22-28-01](https://cloud.githubusercontent.com/assets/16098743/17228429/3a017f40-5513-11e6-9827-b9b8f81fa57a.gif)

**Comment by ROBiBOB** [comment]
Z demo na stronie;
![jul-29-2016 09-47-23](https://cloud.githubusercontent.com/assets/16098743/17241390/a2b5a986-5571-11e6-9a89-aff6bd28f415.gif)

Charakterystycznym jest również to, że termin/zadanie zostaje dodane tylko bez opisu
i zawsze jako spotkanie;
![jul-29-2016 09-47-42](https://cloud.githubusercontent.com/assets/16098743/17241461/14c406f8-5572-11e6-980a-51e2eed37d85.gif)
