### ISSUE TITLE
Abort error, loader freezes

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3316]
Tested on gitdeveloper.yetiforce.com, version: 3.1.702 

1. Go to Competition and preview a record.
2. Hover over an Edit icon in Assigned To field.
3. Change Assigned To a few times.
4. The loader freezes and an error message appears.

[PL] 
Tytuł: Błąd abort, loader ciągle się kręci

Testowane na gitdeveloper.yetiforce.com, wersja: 3.1.702 

1. Przejdź do Konkurenci. Zrób podgląd tego rekordu. 
2. Najedź na ikonkę edycji w polu Właściciel rekordu.
3. Zmień kilka razy właściciela rekordu.
4. Loader się zawiesza, pojawił się czerwony błąd.

Ten błąd występuje też w Kampanii w liście 
rys 87 b

![87](https://cloud.githubusercontent.com/assets/11139594/17209794/58e4c9b6-54bf-11e6-8830-ad752f032421.png)
![87 b](https://cloud.githubusercontent.com/assets/11139594/17209829/79e36578-54bf-11e6-82ee-b5657a29dd60.png)

**Comment by konadrian** [comment]
The error didn't occur again
