### ISSUE TITLE
New version? 

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3317]
when we can expect to be available version 3.2 for download? And when through Softaculous?
Waiting for the new version to customize it for our company :-)

Regards

**Comment by ezbank** [comment]
![zalo_screenshot_30_7_2016_1138803](https://cloud.githubusercontent.com/assets/19627226/17268124/29e80790-564a-11e6-8e76-0c3cc7fafe22.jpg)

**Comment by bpabiszczak** [comment]
Version 3.2 will be published on 2016-08.08. You can now test the update pack: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x/3.1.0_to_3.2.0/zip
