### ISSUE TITLE
[PL] Invoice numbers

### ISSUE THREAD

**Issue by miriampl** [YetiForceCompany/YetiForceCRM#3321]
#### Issue
Witam, Chciałem zrobić ciekawe numerowanie dla YetiForceCRM ale nie do końca mi wyszło to co chciałem.

(Generalnie nowa wersja CRM 3.x super - wszystko działa jak natura chciała. :D)

#### Actual Behavior
Używaj prefiksu: NR 
Początek sekwencji*: 1
Używaj postfiksu: /{{MM}}/{{YY}}

Wygląda to tak, że mam:
NR 1/07/2016
NR 2/08/2016

#### Expected Behavior
Potrzebna mi jest zmienna dla resetowania automatycznie numeracji w każdym nowym miesiącu
Faktura VAT NR 1/07/2016
Faktura VAT NR 1/08/2016

#### Your Environment
* YetiForce Version used:3.1.0

**Comment by dextras** [comment]
Z tego co widzę to tak to teraz działa bo tak zostało zaprogramowane. Możesz sprawdzić w pliku /include/CRMEntity.php funkcja setModuleSeqNumber().

Wydaje mi się, że żeby to działało tak jak ty chcesz (i w sumie to wiele innych osób w tym ja :) ) chcesz to trzeba by:
- w konfiguracji numeracji modułu dodać opcję "resetuj w każdym okresie" (czyli jeśli mamy zmienną miesięczną to nam się resetuje co miesiąc, jeśli mamy tylko zmienną roczną to po całym roku, jeśli zmienną roczną, miesięczną i dzienną to codziennie itp). Jej zaznaczenie skutkuje ustawieniem odpowiedniej (nowej) kolumny w tabeli vtiger_modentity_num , niech to będzie kolumna o nazwie "period" na aktualny dzień/miesiąc/rok, (e.g. 23/01/2016 lub samo 01/2016 - w zależności od zmiennych użytych w prefiksie bądź w postfiksie).
- Przy wystawianiu nowej faktury, w funkcji setModuleSeqNumber sprawdzać, czy pole resetowania jest zaznaczone (również nowa kolumna w tabeli vtiger_modentity_num) i jeśli tak to sprawdzić który mamy aktualnie dzień/miesiąc/rok i jeśli różni się od tego co jest w tabeli vtiger_modentity_num w kolumnie "period" to zacząć nową numerację od "1" i odpowiednio zaktualizować pola w tabeli vtiger_modentity_num.

Powinno działać, chyba, że zespół yetForce ma jakiś inny pomysł na dodanie tej funkcjonalności?

**Comment by bpabiszczak** [comment]
Tak to właśnie działać powinno...
