### ISSUE TITLE
[ENHANCEMENT] MAIN MENU

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3322]
I think it is a necessary improving, it is modern, simple and clear. (Material design)
![123123](https://cloud.githubusercontent.com/assets/19627226/17287096/d3918e34-57f7-11e6-8519-2d82cfb226bf.jpg)

**Comment by MexasPT** [comment]
I Don't Like It, I Love It

**Comment by vovpff** [comment]
Original Yetiforce menu more comfortable for me but material not bad

**Comment by simonetravaglini** [comment]
Hi also think it's necessary change menu to a new menu type like this or similar. This for usability.

**Comment by waran70** [comment]
NIce

**Comment by paula-w** [comment]
Quick question:
How many people would be interested in this menu, and how many would be able to pay for it?

**Comment by ezbank** [comment]
i am ready to pay for a flatform which uses material design and compatible with mobilephone
![zalo_screenshot_7_9_2016_01779](https://cloud.githubusercontent.com/assets/19627226/18283684/9a814912-7490-11e6-8233-90e5cdf13b53.png)

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/205-why-was-the-issue-ignored.html
