### ISSUE TITLE
LBL_PERMISSION_DENIED, loader never stops

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3325]
[EN] Tested on dev.yetiforce.com, version: 3.1.759 

Instructions:
1. Go to the database. Select 'Announcements'. Create 2 records.
2. Select records, click 'Actions'. Select tab 'Mass edit announcements'
3. Enter name in Subject field, and change second status field. Click 'Save'
4. An error pops up, loader doesn't stop.
Similar error was 3323
Error tested without Admin's permissions.

LBL_PERMISSION_DENIED, loader cały czas się kreci.
[PL] Testowane na dev.yetiforce.com, wersja: 3.1.759 

Instrukcje:
1. Przejdź do Bazy danych. Wybierz Komunikaty. Utwórz 2 rekordy.
2. Zaznacz rekordy, kliknij na przycisk Akcje. Wybierz zakładkę Masowa edycja Komunikaty.
3. Wprowadź nazwę w pole Temat oraz zmień drugie pole Status. Kliknij Zapisz.
4. Pojawia się błąd, loader cały czas się kreci.

Podobny błąd był nr 3323
Błąd testowany bez uprawnień admina
![x](https://cloud.githubusercontent.com/assets/11139594/17291527/c5477018-57e4-11e6-832c-ee7f6702dac0.png)

**Comment by rskrzypczak** [comment]
Most likely, in the heat of the fight with yetiforce, the error has been already fixed :)
