### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined 

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3326]
[EN] Tested on dev.yetiforce.com, version: 3.1.755 
Instructions:
1. Go to system settings. Select Standard Modules tab. Next select Modules – fields.
2. Pick Accounts from the list and go to the copy icon (first row) next to the Account name.
3. Click F12 and there is an error.

[PL] Testowane na dev.yetiforce.com, wersja: 3.1.755 
Instrukcje:
1. Przejdź do Konfiguracji systemu. Wybierz Moduły standardowe. Następnie wybierz Moduły – pola.
2. Z listy wyboru kliknij na rekord Kontrahenci i najedź na ikonkę kopiuj (pierwszy wiersz) obok pola nazwa kontrahenta
3. Kliknij na F12 i jest błąd.
![10](https://cloud.githubusercontent.com/assets/11139594/17293055/334c02fa-57ee-11e6-91b2-5a79322b5375.png)

**Comment by TomaszQr** [comment]
[PL] Testowane na aktualnej wersji systemu i błąd ten nie występuje. Przypominam że do prawidłowej pracy w przeglądarce musi być zainstalowany plugin do obsługi flash'a
[ENG] Tested on the current version and that error didn't occur.
Just a reminder - for it to work properly, the plugin to support flash has to be installed in your browser.
