### ISSUE TITLE
Custom user field

### ISSUE THREAD

**Issue by natpicone** [YetiForceCompany/YetiForceCRM#3327]
Hi,
which is the best way to archive this using yetiforce ?
https://forums.vtiger.com/index.php?p=/discussion/170369/creating-custom-field-under-tickets-with-picklist-showing-users-in-dropdown/p1

Thanks

**Comment by vovpff** [comment]
@natpicone UI type 10 or 53 works in vTiger 6.x. Maybe 1:M field + manual database changes?

**Comment by paula-w** [comment]
This field already exists in this (and any other) module, and is called "share with users".

**Comment by natpicone** [comment]
"share with users" is a different thing.
I need a field to indicate who is responsible to a the delivery process (for example).
Why the users table is missing in the related 1:M fields form  ?

**Comment by paula-w** [comment]
You didn't really explain what is wrong with the solution we offered you, why it is not enough, and why you don't want to use it. 
As long as you don't provide us with all the business details related to the effect you want to achieve, and explain why the current solutions aren't enough, we won't be able to help.
