### ISSUE TITLE
How to send email to user??  Relate: #1805 Connect Employees to Users 

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3328]
Employees module have function to add empleyees of Company. Ok. **But some of employees use CRM.** **How to establish connection between Employees and Users?**
I don't understand point of this module without connection.

In issue #1805 / andswer is / "relating an employee and a user is based on the 'owner of the record' field in employees. "  Where is 'owner of the record field'?

**In employees module>>** 

   **Assigned to >>** To set who is superior to employee? Or it should be set to related user account?
   **Share with user >>>** I don't get point what to share? Records of empleyee, their documents, their profile?
   **First name, last name, Emails >>>** all of these field are filled in user account. Just to copy all.

Best regards from Serbia :+1:

**Comment by serbiaserbia** [comment]
Maybe any documentation  about this quation??

**Comment by KatarzynaUlichnowska** [comment]
In order to send an email to an employee, you need to add him/her as a Contact. 
"Owner of the record" means the same as "Assigned to".

**Comment by KatarzynaUlichnowska** [comment]
If you add records in the Employees module, you will be able to send emails to these addresses. Emails can be sent to all addresses but these addresses added to the module will be automatically suggested while typing.
