### ISSUE TITLE
[BUG] Workflow: Execution schedule (defined time intervals)

### ISSUE THREAD

**Issue by michelmarques1** [YetiForceCompany/YetiForceCRM#3333]
Hello friends!

I have a problem in the workflow " Execution schedule (defined time intervals)".

All workflows are generated.

But with this workflow CRON returns error.

Can you help me?

Log:

 
---------------  2016-08-02 23:00:03 | Start CRON  ----------
2016-08-02 23:00:03 | Workflow - Start task
<br />
<b>Fatal error</b>:  Uncaught exception 'WebServiceException' with message 'Permission to perform the operation is denied for name: ' in /home/olharcri/public_html/crm/gestao/corpore/include/Webservices/VtigerWebserviceObject.php:65
Stack trace:
#0 /home/olharcri/public_html/crm/gestao/corpore/modules/com_vtiger_workflow/VTSimpleTemplate.inc(239): VtigerWebserviceObject::fromName(Object(PearDatabase), NULL)
#1 /home/olharcri/public_html/crm/gestao/corpore/modules/com_vtiger_workflow/VTSimpleTemplate.inc(42): VTSimpleTemplate-&gt;transformToUserFormat(NULL, '_DATE_FORMAT_', NULL)
#2 [internal function]: VTSimpleTemplate-&gt;matchHandler(Array)
#3 /home/olharcri/public_html/crm/gestao/corpore/modules/com_vtiger_workflow/VTSimpleTemplate.inc(134): preg_replace_callback('/\\$(\\w+|\\((\\w+)...', Array, '&lt;div style=&quot;out...')
#4 /home/olharcri/public_html/crm/gestao/corpore/modules/com_vtiger_workflow/VTSimpleTemplate.inc(20): VTSimpleTemplate-&gt;parseTemplate()
#5 /home/olharcri/public_html/crm/gestao/corpore/modules/com_vtiger_workflow/tasks in <b>/home/olharcri/public_html/crm/gestao/corpore/include/Webservices/VtigerWebserviceObject.php</b> on line <b>65</b><br />

![image](https://cloud.githubusercontent.com/assets/18095104/17351829/55662788-5908-11e6-8ebb-31a212ff4c85.png)
![image](https://cloud.githubusercontent.com/assets/18095104/17351834/62d38708-5908-11e6-904b-e34d10511f89.png)
![image](https://cloud.githubusercontent.com/assets/18095104/17351844/7765c4e2-5908-11e6-8ffe-178d90a6e3c1.png)

**Comment by rskrzypczak** [comment]
The error was most likely fixed in this commit https://github.com/YetiForceCompany/YetiForceCRM/commit/ac88949565b4339ad239795b483f4363ad5ba5b5. It doesn't occur in the current crm version (3.1.944).
