### ISSUE TITLE
Mail Scanner and Mail to Module Relations not working

### ISSUE THREAD

**Issue by rage1985** [YetiForceCompany/YetiForceCRM#3334]
#### Issue
Hi, Yetiforce Team,
first of all congratulations to your beautiful System.

Unfortunatly i have some Issues with the Mail Scanner and Mail to Module Relations.

#### Actual Behavior
Mail Scanner does not relate Mails. Mails composed with Action from the Contact or Account Module do not relate to the selected Record. Mails composed within Detail-View of a record do not relate.

Also i have am Error Message in Mail Scanner Config which says no folder configuration. I had a look into your Master Demo CRM and found the same.

Found the PHP Error Log filled with nearly 1 Million Lines.... i snipped 2k of them and attached them, ads they repeated over and over. 

#### Expected Behavior
Mails should relate, when composed within a Record´s Detail-View or via Module Action. Also Mail Scanner should work and Auto-Relate matching Mails to Records.

Mail Scanner should accept Folder Configuration.

#### How to trigger the error

1. Compose Mail from within Detail-View
2. Compose Mail from Module Action
3. Configure and Run Mail Scanner

#### Your Environment

* YetiForce Version used: 3.1.0
* Browser name and version: Firefox ESR 45.2.0
* Environment name and version: Apache2.4.7-1ubuntu4.13 & PHP 5.5.9+dfsg-1ubuntu4.17
* Operating System and version: Ubuntu LTS 14.04.4

[phpError.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/398863/phpError.zip)
![import_mail_manually](https://cloud.githubusercontent.com/assets/4996570/17359173/b397fbd0-5965-11e6-8423-b1656a8e9a9b.gif)
![mail_scanner_no_folder_conf](https://cloud.githubusercontent.com/assets/4996570/17359188/cdf6b41c-5965-11e6-95a1-941a2970a70d.JPG)
![mail-download_log](https://cloud.githubusercontent.com/assets/4996570/17359192/d2d4a94e-5965-11e6-8fa2-814f77a12055.JPG)
![compose_from_detail_view](https://cloud.githubusercontent.com/assets/4996570/17359196/db325866-5965-11e6-84c2-bcb680c15dc7.gif)

**Comment by rage1985** [comment]
Had a look into the Documentation and closed Issues with Mail Scanner and Relations twice.

- Cron is running.
- Scanner is configured.
- imap and smtp works.
- switched on every kind of relation and mail scanner action.

**Comment by rage1985** [comment]
Ok found out that in Table "vtiger_ossmailscanner_folders_uid" column "user_id" is not be filled properly.
It set the Roundcube User Id instead of CRM User Id.

**Comment by mariopmoura** [comment]
Hi,
I'm having the same problem. How did you fixed it? In Yeti or in database?

**Comment by rage1985** [comment]
I had the build the from Sourceforge, it seems corrupted/unstable. I made a now isntallation from the stable github repository and everything works fine for me now. BTW: There can be several different caveeats depending on your Mailserver/Mailbox/Mail-Authentication/Protocol(TLS/SSL).

I personally had to tweak Mail-Autologin because i had the Yetiforce Site on https.
