### ISSUE TITLE
[ENHANCEMENT]  Move buttons to the left of the list view

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3337]
Version: 3.1.793

recommend moving buttons to the left of the list view for better usability . 
Now if the list has a horizontal scrolling is inconvenient to use the buttons on the right.

![gifrecord_2016-08-03_131113](https://cloud.githubusercontent.com/assets/18703633/17363856/330a257a-597d-11e6-8e35-35c0a7ea51f1.gif)

**Comment by bpabiszczak** [comment]
Please check latest version :]
