### ISSUE TITLE
[QUESTION] vTiger modules

### ISSUE THREAD

**Issue by natpicone** [YetiForceCompany/YetiForceCRM#3342]
Can vTiger modules be used with YF?
For example https://itsapiens.eu/solutions/vtiger-crm-advanced-reporting-tool/

Thanks a lot

**Comment by waran70** [comment]
Why don't you ask developer?
By the way Yetiforce is not Viger

**Comment by natpicone** [comment]
I'm a dev and I know the diffs between YF e VT.
My question was about the compatibility between YF and VT.
YF Staff will try to make YF compatible with VT extension or not ?

I need better reporting (standard reporting sucks) and I was looking around before starting developing something by myself..

**Comment by KatarzynaUlichnowska** [comment]
In order for Vtiger's modules to work in YetiForce, you need to make some adjustments, e.g. we changed paths for 2-3 files, which are hard coded in some Vtiger's modules. Only the authors of modules decide whether they want to adjust them to YetiForce or not. 
If you need better reports in YetiForce, you can order them and pay for it. When you buy a Vtiger's module, you don't support YetiForce's development.
