### ISSUE TITLE
[Bug] Update package from 3.1.0 to 3.1.691

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3343]
I try the update package from 3.1.0 to 3.1.691 by importing it 
![image](https://cloud.githubusercontent.com/assets/1357727/17433344/6480be06-5b04-11e6-905b-e7fc639c84f3.png)
And I can't add lead, organisation or opportunity or use the quick search like in my ticket #3305 

I hope this will be fixed in 3.2.0

Thank's for your job =)

**Comment by PercyP** [comment]
Hi,

I have just used the 3.1.0 - 3.2.0_vRC5 update and the quick search issue is still there in that it returns 0 results.

Kind regards

Percy

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3348

**Comment by Raggazzoo** [comment]
I still got my problems...

- No quick search
- History widget LBL_DISPLAYED nothing and on organisation page the name doesn't display (It seems that the name of the field change during an update)
- And I still cannot add an organisation
![image](https://cloud.githubusercontent.com/assets/1357727/17850436/7f427e26-685d-11e6-9245-df34d5cee994.png)

Thank's!

**Comment by Raggazzoo** [comment]
Do I have to rebuild my database with the latest version?

I can export organisations, leads, contacts and opportunities vut how can I export history, events and relations between modules?

**Comment by bpabiszczak** [comment]
Please check gitdeveloper version and this latest update packege: https://github.com/YetiForceCompany/UpdatePackages/commits/developer

**Comment by Raggazzoo** [comment]
Yes I have done it and the result is the same.
I am on 3.1.629 on my production app.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
please open a new issue because your initial question was different. We strongly believe in "one issue = one question" rule.

**Comment by Raggazzoo** [comment]
Ok I will do it thank's
