### ISSUE TITLE
How Do I restore a Backup

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#3347]
How do I restore a backup?
I am moving my yetiforce installation from one server to another and I would like to know how do I restore the backup or is there a better way to move over the information.

**Comment by nic86** [comment]
1) install same yeti version on new server
2) Copy and overwrite /storage folder from old server to new server
3) Copy and overwrite /user_privileges folder from old server to new server
4) export and import yeti database from old server to new server
5) edit config/config.inc.php with new server parameters

**Comment by paula-w** [comment]
The built-in backup mechanism is only recommended for small databases, and only when we don't have any other tools. It's best to use the operating system built-in tools.
