### ISSUE TITLE
[BUG] Global search don't work

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3348]
![animation](https://cloud.githubusercontent.com/assets/19627226/17472982/28550b82-5d78-11e6-8cb5-306c36614ce7.gif)

**Comment by vovpff** [comment]
@ezbank Yeti crew now renew global search mechaism

**Comment by rskrzypczak** [comment]
Theoretically it's not an error. 
The record will be visible in global search after executing the permission cron 'Privileges updater'. After that the record will be visible in the search engine for people who have the permissions.
![image](https://cloud.githubusercontent.com/assets/10221999/17475019/36a12ae6-5d59-11e6-9de0-edf28dff5f8e.png)
