### ISSUE TITLE
[bug] manual password cannot save

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3351]
#### Issue
1. go to gitdeveloper (v.3.1.850)
2. go to Account and select "YetiForce Sp. z o.o."
3. go to tab "Passwords"
4. add record and fill the password manual "abc123ABC!"

#### Actual Behavior
![password](https://cloud.githubusercontent.com/assets/10259801/17493672/a3e4ba8e-5db1-11e6-816a-d0717a5b84ac.png)

#### Expected Behavior
i can save my password

#### How to trigger the error
see issue

#### Your Environment
* YetiForce Version used: gitdeveloper v 3.1.850
* Browser name and version: chrome

**Comment by bpabiszczak** [comment]
Your new password is ...... ?
