### ISSUE TITLE
[enhancement] possibility of setting a custom filter on Calendar and Reservations

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3353]
Hi,

Do you have planned the Possibility of setting a custom filter on "Calendar" and "Reservations"?

Greetings and thank you

![reservas](https://cloud.githubusercontent.com/assets/18419851/17510357/7597d9f8-5e16-11e6-944e-9a78c2b0ce41.PNG)
![calendario](https://cloud.githubusercontent.com/assets/18419851/17510358/77444a52-5e16-11e6-9cab-422d81db2b1f.PNG)

**Comment by mariuszkrzaczkowski** [comment]
Already exists, create a file ex. modules\Calendar\calendarfilters\Test.php
With a content
```php
class Calendar_Test_CalendarFilter
{

	public $type = 'checkbox';
	public $name = 'Test';
	public $value = 'Test';
	public $searchParams = '"subject","c","Test"';

	public function getCondition($value)
	{
		if ($value == 1) {
			return "AND vtiger_activity.subject LIKE '%Test%'";
		}
		return '';
	}
	
	public function checkPermissions()
	{
		return true;
	}
}
```
