### ISSUE TITLE
Is today the "big day" - Version 3.2?

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3356]
With enthusiasm we expect version 3.2 to implement in our business model.

Will today be released YF version 3.2?
Will be also available via Softaculous installer? What is your practice for realeses via Softaculous, same day as the official?

Regards

**Comment by PercyP** [comment]
I am waiting patiently too - there is a new update package to test which was put there about half hour ago.

**Comment by serbiaserbia** [comment]
thnx for updates, but now would like to install latest stable version and to be peaceful for one or two months without update.

**Comment by PercyP** [comment]
@serbiaserbia 

As it turned out the updates are not suitable so we just have to wait and hope it is today, but the milestone is still on 93%

**Comment by serbiaserbia** [comment]
@PercyP 
Milestone is always 92-93%...  I guess developer will relate it with YF3.3 and leave "clean" 3.2 with no open issue.

**Comment by serbiaserbia** [comment]
I have an idea. Let's bring some fun into this expectation.
Let's **make a vote** when the thoughts that will come out a new release. At the end we will see who was closest.
I hope that it will be today :-)

My prediction date is **14.08.2016**

**Comment by PercyP** [comment]
@serbiaserbia 

:) Ok - mine is 18th as it always goes back 7 days. Hope its today too :+1:

**Comment by SkavenKF** [comment]
My vote: 29.08.   :tired_face:

... but i hope its today too  :pray:

**Comment by MexasPT** [comment]
Mine is 19th... But I'm an optimist... :)

**Comment by bpabiszczak** [comment]
:( we need few days

**Comment by jstorchia** [comment]
thanks for all the work they do

**Comment by ezbank** [comment]
maybe is 16th :)

**Comment by serbiaserbia** [comment]
@jstorchia 
developers really doing an amazing job

**Comment by PercyP** [comment]
I am excited - it says 16th - thats today. Fingers crossed :dancers:

**Comment by serbiaserbia** [comment]
Yeaaaaa, 🕚
something seems to me that it will not be today. I have a feeling....

💡💡let's raise some money and hire someone who knows how to look in tarot cards ... maybe we'll get an answer   🎃🎃

**Comment by serbiaserbia** [comment]
let's turned a new round of predictions  🙌🙌🙌
My date is 20.08.2016 
a little bit pesimistic 😎

**Comment by serbiaserbia** [comment]
accidentally closed the discussion ... it is perhaps a sign, spooky 🎃🎃

**Comment by iRainSystem** [comment]
we are waiting :date:

**Comment by PercyP** [comment]
Me too ... 

Don't suppose there is any news about the update?

Percy

**Comment by waw555** [comment]
And I'm still doing the translation. Can have time to release)))

**Comment by serbiaserbia** [comment]
it would be good to have the Approximate real date for release 3.2.

**Comment by paula-w** [comment]
Hi guys :)
We're still conducting some final code tests. We'll release once everything is ready.

**Comment by PercyP** [comment]
@paula-w

Thanks for updating us :)

**Comment by skramanzia** [comment]
@paula-w Great news!, may be today?. :) sorry i am eager.

**Comment by serbiaserbia** [comment]
My champagne is ready....

![partying](https://cloud.githubusercontent.com/assets/19521910/17856274/f4fc8b7e-687c-11e6-98ac-9e92c45056c4.gif)

Should I open it?
Or should I leave it to cool down?

**Comment by PercyP** [comment]
I am waiting patiently too :dancers: 

Is it likely to be today?

**Comment by johntonji** [comment]
Can't wait!

**Comment by Raggazzoo** [comment]
License updated! It smells good!

**Comment by jstorchia** [comment]
95%  ! :+1:

**Comment by paula-w** [comment]
Hi again :)
**Believe us, nobody wants the new version as much as we want it.** 
We checked all changes [we do that to make sure no dev made a huge mistake], now we're adding changes from the past 2 ~ 3 days and we're finishing the update package... but it all takes time. Especially that we immediately fix all mistakes we find, and we want to fix some GitHub issues as well, to make the system as stable as possible. 

Nobody introduces as many changes as we do. Just to give you some examples: in comparison to SuiteCRM -  for the past month we've added more than twice as many changes, additionally our changes were more significant. Vtiger hasn't introduced any changes for the past month. 

Give us 1 ~ 2 more days, we need it to refine this version. Keep testing the system and reporting issues, we'll fix whatever you report before we release 3.2.

**Comment by waw555** [comment]
I just finished translating

**Comment by paula-w** [comment]
Guys, be ready for Monday :wink:

**Comment by serbiaserbia** [comment]
Juhuuuuu.... 

@paula-w    Will 3.2 instalation be ready via Softaculous too?  😇

**Comment by paula-w** [comment]
@serbiaserbia it's up to Softaculous when they release the new version, so I can't really answer this question. You can follow us on [Twitter](https://twitter.com/YetiForceEN), we always inform our followers when Softaculous releases an updated version of YetiForce.

**Comment by SkavenKF** [comment]
:stuck_out_tongue_closed_eyes:  Winner  :tada:
but ... let's talk about on monday  :neutral_face:

**Comment by serbiaserbia** [comment]
@SkavenKF    Congratulations! :-)  Probably you have some supernatural powers - when you hit the exact date  :+1:   Every competition have a prize! :innocent:
All peple from this discussions must find an appropriate gift for you.
@PercyP @MexasPT @waw555  @skramanzia Come give some suggestions for prize for @SkavenKF 
@bpabiszczak @paula-w  Have any sugestion? Something symbolic and fun :-)

**Comment by waw555** [comment]
Let's not rush things, and give developers the ability to fix as many bugs as possible. After all, get a version with errors and wait for the next, much worse than to wait a little and get a version with a minimum of errors. Identify the error, to squeeze the most from the current version, the more errors we find, the more stable the system is.

Remember - the developers to work for us for free!
Want to time - pay the money, as in any other system!

**Comment by serbiaserbia** [comment]
@waw555  you are absolutely right. Very great respect should have for developers and people who are involved in this project (see that you're involved in a lot of improving YF).

As they reward us with great enhanced software (for free) I think that whole community in some time must come together and make a donation. Individual donations in principle does not mean anything (20,30, 50eur etc.), but if more people (20-30 people who have benefit from YF) come together with its "small donations" that would mean the entire developer team to do something great.

Best regards.

**Comment by PercyP** [comment]
@serbiaserbia 

I 100% agree to a donation - where / how would we do this? 

@paula-w says it will be today the update - I hope so :)

**Comment by paula-w** [comment]
There's the "DONATE!" button on our [website](https://yetiforce.com/en/), but so far there haven't been any donations.

**Comment by PercyP** [comment]
@paula-w 

Hi Paula, thanks for the link. I have just donated via your website - I hope it was received. Hopefully some of the other members will contribute too as the work you guys do has been exceptional. Just downloaded updated and excited to finally start using it. Congratulations and thank you.

**Comment by skramanzia** [comment]
@PercyP are now available the latest update pkg?.. i cant find in sourceforge

**Comment by bpabiszczak** [comment]
easy....

**Comment by PercyP** [comment]
@skramanzia 

I think it is here https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%203.x.x/3.2.0/

**Comment by paula-w** [comment]
Thanks @PercyP for our first donation :D
We really appreciate that!

**Comment by Raggazzoo** [comment]
I made my donation! You really deserve it!

**Comment by paula-w** [comment]
Thank you @Raggazzoo !
