### ISSUE TITLE
[ENHANCEMENT] Attach files into Comment

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3358]
I think this will be a worthwhile improvement.
<img width="365" alt="comment-w-attachment" src="https://cloud.githubusercontent.com/assets/19627226/17599526/c4521dd2-6029-11e6-9ecc-9cdc4fd8693f.png">

**Comment by serbiaserbia** [comment]
+1

**Comment by ezbank** [comment]
+2 :)

**Comment by vovpff** [comment]
+3 but file must be added to record related document list too

**Comment by paula-w** [comment]
Right now we're not planning to implement this feature [none of our clients needed it], and what's even worse – when we added the option to add comments there together with wysiwyg, we were asked to disable it, because people wanted a simple tool. 
We might add it if some of our clients request that feature.

**Comment by ezbank** [comment]
I want this feature on my system and send me it's price. Curently, on vtiger 7.0 has this feature so I suspect it's not too difficult to create a similar option.

**Comment by waran70** [comment]
Paula,

What if your client wish to remove invoice module? Will you cut it out?
Just for your reference - making OS system depended on your clients, and
speaking it out to open source community, discouraging serious developers
to  contribute to the source. Why don't you release various modifications
as an extensions and sell them out? Sell to your clients and all others.
Manage core to be stable, and keep in one shape.
Rest stuff separate, so we all know where we going to. I know that was
mentioned here several times, but as this is logical and wise (what I am
saying) I get it
here again.

**Comment by bpabiszczak** [comment]
@waran70 https://github.com/YetiForceCompany/YetiForceCRM/issues/3840
@ezbank 6-8h [https://shop.yetiforce.com/en/support/8-silver-package.html]
