### ISSUE TITLE
[Question] How to - can print pdf invoice?

### ISSUE THREAD

**Issue by jjoloka** [YetiForceCompany/YetiForceCRM#3360]
Please, sign for steps on how to create PDF invoce for save on PC? I not see button generate invoice in pdf? Or how to print another document (I do not see pdf print button in menu)?
use: https://gitdeveloper.yetiforce.com/

**Comment by rskrzypczak** [comment]
![pdfinstr](https://cloud.githubusercontent.com/assets/10221999/17614707/a615cb72-6068-11e6-93da-6182b64351f1.gif)
