### ISSUE TITLE
Workflow not working on System - run on all records automatically?

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3362]
Would anyone could clarify my doubts about triggering vorkflov.
I made one simple test, and no result (in 3.1 and in latest developer) - Guess I am doing something wrong or not understand the logic of workflow.
    - select module Account
    - Spec when to execute: System
    - Condition: If one field (Posal code) value is "21000"
    - Udate field: Update another field (Street) in record
          - account -Manualy updated Postalcode in exiting record to 21000 - to set condition 
          - account - Manualy created new record with postalcode - 21000 - to set condition
    - Wait for 15min, 30 min... and nothing happends
![animated3](https://cloud.githubusercontent.com/assets/19521910/17614055/4d6c9b86-6063-11e6-8c85-b146ea67b51c.gif)
 
*** **System** - I dont know when this will be executed? Only once? It will apply to all record, only modified, only new records?

*** Can Workflow be executed **on all record**s - I see there is on create, on modifying... I thought System- means all records, automaticaly with cron (15min.)?
*** Can Workflow be executed **only once on all record**?

In other CRM there is clear adjustment - all records, only new, on modifying.
![animated4](https://cloud.githubusercontent.com/assets/19521910/17614090/ab0b2898-6063-11e6-93aa-e839dafa488e.gif)

**Comment by vovpff** [comment]
@serbiaserbia lets try   Every time a record is saved (eg. creating, modifying) and use conditions for postL code

**Comment by serbiaserbia** [comment]
@vovpff 
Ok.  It will work corectly.  User enter new record,  click save -after that new record is created and new survey is created.  It work. 
But,  I want to it runs on all old record prevuislly saved.  For example, in the middle of this month we figure new survey for all account created on february this year. We didnt know it will be needed in moment of creating record. 
I need workflow automation to pass throught all record,  check condition and do all tasks.  Is that possible with cheking execution "System"?

**Comment by vovpff** [comment]
@serbiaserbia I nevervtried this in a past but you can try "manually triggered by user" workflow type.

Another one idea - lets make checkbox an wokflow with conditions: if checkbox is on, postal code is ABCDEF then update field street field and uncheck checkbox. This works cool in vtiger and yeti.

System workflow type undiscovered by me now... More information needed from developers.

**Comment by serbiaserbia** [comment]
@vovpff 
**"manually triggered by user"** is working properly, but it is semi-automated workflow. User must click, and automation will begin. It is very usefull but a user must be included.
**"Everytime record is saved", "on creation", "on modifiying", "delatating records"** is  semi automated  (almost full automated). User must click save or create. 
**"Execution schedule (defined time intervals)" and "System" options** - I assume that these options are for complete automation. It would be good to be clarified by developers. These options sure have great potential and be very usefull.

**Comment by dextras** [comment]
@serbiaserbia It is just a workaround to run a workflow one for each record.

I do not think there is a straightforward way to accomplish what you are asking for. The way I deal with the issue is by:
1. generating a workflow to run "on modify",
2. selecting all the records I want to run the workflow on.
3. going to Actions menu and selecting "mass edit".
4. Change some variable that has no meaning for you.
5. Voila! The workflow is run once for every record.
6. Remember to remove the workflow from the workflow list or at least disable the actions in it.

Hope it helps.

**Comment by serbiaserbia** [comment]
@dextras  👍👍 thanks for your help.  👍👍
Yes,  that is full logic and corectly, but it is semi-automatic. But do you have an idea what is purpose of these workflow execution  options:
1. System
2. "on schedule"

How do you use it?  Have any expeience? 

I think -it must fill the gap in meaning of full automatisation of CRM, without human touch - only to set condition and todo. 
Offcourse,  to stop that automation,  we can allways add to change some variable (in condition) that will be condition to stop trigger.

Any experience is welcome,  thanks...  🎓🎓👓👓

**Comment by dextras** [comment]
Hi! 
I am glad I could help ;)
Regarding your question:
1. System - I have no idea. We would have to ask developers e.g. @bpabiszczak . I can only quess that maybe somewhere in code you could implement a trigger for that particular workflow. It would mean that it will never run until a trigger in the system (also defined by you) would be fired. 
2. on Schedule - it means you can run some workflow for example every day at 5:00 am etc. It is quite useful for example if you would like to send some pdf (like e.g. reports) to your email address, or to generate a record at the end of every month of some type (like summary or sth). Or anything that would require an action every some period.

For the second to work you have to have cron configured in your webserver. Please refer to https://yetiforce.com/en/administrator-documentation/panel/cron/150-enable-cron.html.

**Comment by bpabiszczak** [comment]
System = in the script you decide when to run.

**Comment by serbiaserbia** [comment]
@dextras  Thanks for your time... 
@bpabiszczak  Thank for answer....
1. "system" - ok,  need coding and programming....  I will leave it in my minds 🍹🍹
2. But "on schedule" what is the trigger to run workflow - to "create it" or to "modify it" or it will check only condition regardless whether user touched record or not? Do I have to do someting with record to triger it "on schedule" except to set condition?

Answer on 2nd question will  solve all my mistery forever 😀🎃🎃

**Comment by dextras** [comment]
Just try it out ;)

The trigger is the **time**. If you set it to run every day at 5:00 pm it should run on all records matching the conditions you specified every single day at 5:00 pm.

**Comment by serbiaserbia** [comment]
@dextras   Mistery is solved, very usefull 🍹🍹thanks

To try...  I have some problem with cron,  can't catch admin to fix it in right way... On my test server enviroment  can't test it. Grrrr,  angry on myself. 
On dev version -  I tried many things that I got tangled up, and nothing. Now I'm going to test it again. Thnx
