### ISSUE TITLE
[bug] creating custom fields in Calendar module

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3363]
#### Issue
The buttons to create custom fields do not appear.
The only button allows you to create the field but when you are going to create a record, the field is not displayed.

### How to trigger the error
![error calendar](https://cloud.githubusercontent.com/assets/18419851/17618427/a754f472-6077-11e6-9105-76c37e56c702.gif)

#### Your Environment
* YetiForce Version used: 3.1.925, 3.1.794 and 3.1.650
* Browser name and version: Firefox(48.0) and Chrome(52.0.2743.116 m (64-bit))
* Environment name and version: XAMPP (php 5.6.21) and GitDeveloper(gitdeveloper.yetiforce.com)
* Operating System and version: Windows 10 and Windows 8.1(virtualBox)

**Comment by konadrian** [comment]
In the calendar module the option to add new fields is disabled. It's not an error, it's been done purposely.
