### ISSUE TITLE
[BUG] Notifications button is missing

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#3364]
If user not admin Notifications button is missing.
Why?

**Comment by iRainSystem** [comment]
look [issues 3366](https://github.com/YetiForceCompany/YetiForceCRM/issues/3366)

**Comment by rskrzypczak** [comment]
This is not an error. Action permissions are granted in profiles.
![image](https://cloud.githubusercontent.com/assets/10221999/17697543/b568fb8a-63b5-11e6-8d60-c1ba3825b2c3.png)
