### ISSUE TITLE
define permission to any folders in document module

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3365]
How to define permission to any folders in document module ???

**Comment by vovpff** [comment]
+1

**Comment by KatarzynaUlichnowska** [comment]
Currently, permissions exist on the record level, not folder level and in our opinion, it is the only right way. In the future we may add an option to show only these folders that contain a document, so it would solve the problem of too large folders. Obviously, it is possible to add permissions on the folder level, but we don't have a customer who would like to pay for it... and for us it isn't of the highest priority right now.
