### ISSUE TITLE
[BUG] Notifications could not be sent .

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3366]
Notifications from user could not be sent to any users. 
tested in version 3.1.941 .

**Comment by ezbank** [comment]
it's true

**Comment by serbiaserbia** [comment]
tested on developer ver., true

**Comment by serbiaserbia** [comment]
on ver. 3.1.0 not working too.
If I set created notification todo in workflow to inactive - not working
I have to complete delete used workflow where was notification.

**Comment by iRainSystem** [comment]
BodyHeader.tpl 
{if Users_Privileges_Model::isPermitted('Dashboard', 'NotificationPreview')}

table: a_yf_notification_type.role=0 - ???

table: `vtiger_actionmapping` (`actionid`, `actionname`, `securitycheck`) VALUES(45, 'NotificationPreview', **0**);
but in the user_privileges don't record '45=>0' in ActionPermission?

in edit pemisions->role  or pemisions->user i don't see checkbox 'NotificationPreview'

**Comment by KatarzynaUlichnowska** [comment]
Please record a video on a current version of [gitdeveloper](https://gitdeveloper.yetiforce.com/index.php). This way we will be able to see what your actions are and what might be wrong, because we cannot reproduce it. Everything appears to be working fine.
