### ISSUE TITLE
Opportunity have a relation with contacts. Contacts relation to opportunity is missing

### ISSUE THREAD

**Issue by hamzka** [YetiForceCompany/YetiForceCRM#3367]
#### Issue

Thank you for working on YetiCRM. I am now testing this environment. 

I find it productive to create an opportunity and also open the opportunity page from the contact page.

#### Actual Behavior

  Currently the flow is that when we contact a client and encounter an opportunity, we have to open the accounts page or the opportunity page to create an opportunity and relate the account to the opportunity on the creation screen. 

Only when the opportunity is created then we can go to the opportunity and add the contact to the opportunity. 

#### Expected Behavior

It will be productive when we are in the contact page we can create the opportunity.

When on sales call we should be able to see the opportunity that we have with him and his organisation. then click right into it to work with the opportunity. 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.1.898
* Browser name and version: chrome
* Environment name and version: 
* Operating System and version: Windows 10( server Ubuntu)

**Comment by skramanzia** [comment]
Hi @hamzka you can add a "Related Fielde 1:M" in Opportunities module from "Edit Fields" to add Contact when create the OP.
 If you need to see the relation in contact module, you must create that in "Standard Module-->Modules-Realations". to perform that check this link previously. https://github.com/YetiForceCompany/YetiForceCRM/issues/2249

**Comment by hamzka** [comment]
Hi sorry I dd not understand the first part of your reply. 
I tried the 2nd item in your reply was able to create the relation, it shows a block for opportunities in the contact form however it is empty. 

I found out also that the quick create contact now shows no fields.. I believe I might have messed up. 
are the changes in the database or in the file system. Please advise.

**Comment by KatarzynaUlichnowska** [comment]
Opportunities are related to Accounts and that's where you can see a relation. This could be added in Contacts (that's not a bad idea), but we won't add it because we aren't sure if we want to see it there as Contacts are treated as an address book. You can add it yourself as it takes a few minutes or you can pay someone to do it for you.
