### ISSUE TITLE
[BUG] sort users in include/fields/Owner.php

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#3368]
`289: sort($users);`
`290: $log->debug('Exiting getUsers method ...');`
`290: return $users;`

maybe use **asort($users); ???!!!** 
**sort()** - This function assigns new keys to the elements in array. It will remove any existing keys that may have been assigned, rather than just reordering the keys!!!!

**Comment by paula-w** [comment]
Hi
Next time you can just send us a pull request and we will merge your changes.
