### ISSUE TITLE
Portuguese translations

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#3369]
There are many missing translations in Portuguese, some modules are entirely in English.

If anybody wants to consistently and regularly work on the translations please let us know, otherwise we will have to remove the language from the system.

**Comment by vctrin** [comment]
Hi Paula,


I will return with translation in the next week.


Best regards,


Valmir Carlos Trindade
TTCA Soluções
+55 41 3203-9951 | 9924-9370
valmir@ttcasolucoes.com.br
Skype: ttcasolucoes

Curta a TTCA Soluções no Facebook Curtir no Facebook 
<http://www.facebook.com/ttcasolucoes/?sk=likes>

Em 16-08-2016 08:01, Paula W escreveu:

**Comment by paula-w** [comment]
Portuguese translation will be removed in the new version.

**Comment by MexasPT** [comment]
This will apply to version 3.3 ?

**Comment by MexasPT** [comment]
how long were the files available?

**Comment by paula-w** [comment]
What do you mean how long the files were available?

**Comment by MexasPT** [comment]
I want to know when will be removed from the stable installation files for the language in Portuguese.

**Comment by bpabiszczak** [comment]
maybe tomorrow :]

**Comment by MexasPT** [comment]
I was willing to translate all modules ... but ok... :(

After the files are deleted it is possible to manually add a new language?

**Comment by vctrin** [comment]
If it is possible to maintain the translation, I will perform the files 
update until tomorrow. I had particular problems that prevented the 
maintenance of updated files in recent months. Please, confirm your 
decision.


<http://www.facebook.com/ttcasolucoes/?sk=likes>

Em 31-08-2016 14:01, MexasPT escreveu:

**Comment by paula-w** [comment]
@vctrin @MexasPT For us, when translations aren't completed on a regular basis, it means that no company in a given country/countries actually uses the system, because if they did,  they would want to have the system properly translated. And if nobody needs the translation then why should we keep it in the system? When we add something, we add new labels to all language files, not just PL and EN, so we spend our time doing that, and nobody uses it. If you are able to translate the system consistently, on a regular, ongoing basis, then the language can stay. The language has been neglected ever since we added the translation, not just for the past week or month. 

If you create decent translation more people and companies will come along and help you fix and refine  translations. Don't do it for us, do it for your clients. Remember that translating any language in the system is an ongoing process, and it requires constant work [it's not a whole lot of work, but we add some new translations every day]. We can wait for a month, if nothing changes - the language will be removed.

**Comment by paula-w** [comment]
Thank you for the current Portuguese translation, unfortunately we are forced to remove it since it's no longer being developed.

**Comment by vctrin** [comment]
According with the decision of the Yetiforce CRM project's coordination, of removing the Portuguese translation, I am providing the complete code here for those interested: https://github.com/vctrin/YetiForceCRM_PT_BR.

**Comment by torresnet** [comment]
I used YetiForce to manage my clients. Some were in the process of initialization, but with the desistence of native support to the Portuguese language BR .. We chose to look for other alternatives.
Should you keep the language support and work on publicizing the system in this region, with the lack of Portuguese language, how do you expect to grow in Brazil?

**Comment by paula-w** [comment]
The community in a given country is responsible for maintaining certain language pack. If there’s nobody in that country who could prepare the package, then it means that you guys have to start giving something instead of only taking. We only develop EN and PL packages and they’re updated every day.

**Comment by genesis-wp** [comment]
Hello there!

I need this system in pt_BR. Where can I find the file translated?

**Comment by genesis-wp** [comment]
But I can help translate if this it's needed.

**Comment by ezbank** [comment]
Setting > Systems tool > Language Management

**Comment by genesis-wp** [comment]
I haven't seen the lenguage pt_BR.
