### ISSUE TITLE
Scale Out Yeti Lamp stack

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3372]
Do you plan to add codes to separate the reads and writes operations towards database, without the use of a proxy, in a system like this: https://dev.mysql.com/doc/refman/5.7/en/replication-solutions-scaleout.html
or do you have any advices on what is the best method to scale out lamp stack for Yeti. 
Thanks

**Comment by bpabiszczak** [comment]
1. How much data do you have in your system or how many users use it that you need such solutions? Our delay with the release of 3.2 is the result of the fact that we optimize the system and it is one of the requirements, which we received from a very large company in Poland. They test the system for 12.000 users, including 2.000 users online and we added over 45.000.000 records to the system. The result the application needs to receive is loading time below 1s for each tab [most tabs do that, but we need to improve the system in a few more locations, however, we get closer and closer to achieve incredible performance]. In a few days we will present you the system and you will be able to see how fast it is and how much it can do - I doubt that any system in the world will achieve the performance we want YetiForce to have. Scale-out solutions [I read the link you sent] are used when one server cannot cope and, in my opinion, there aren't many companies in the world that would need scaling. The question is whether your company needs it. Regardless of you answer, in the future, we are planning to support other engines such as MsSQL, so we will probably also add ORM and scaling. 

2. Unfortunately, I don't know why you need proxy. We may separate read and write operations but it would rather be for security purposes?

**Comment by nic86** [comment]
I meant a solution designed to separate the read and write using the software as mysqlproxy or HAProxy.
We need to design a structure which includes the use of a hundred or more yeti installations with an average of ten users for installation. we have in mind to use a physical server ( Xeon 2.9 GHz - RAM 100 GB - 8hd300gb raid50 with VM-ESX) with two virtual Debian  system containing a hundred virtual host apache and HAProxy for load balancing , and two debian physical servers ( xeon 2.7 GHz - ram 44 GB - 8HD 300gb raid10) with a hundred mysql database with replication master/slave. 
For storage we were thinking of a third physical NAS server shared with the two virtual server apache.
To have an idea: https://assets.digitalocean.com/articles/high_availability/ha-diagram-animated.gif

Do you have comments about this strutcture, could you help us to best design the enviroment for Yeti?

**Comment by bpabiszczak** [comment]
1. What you have suggested here is a casual load balancing with application server and database segmentation. That's not a question to us, we have an administrator who configures such things for our customers but it's a side effect of the fact that we produce the software. We don't advise on it because we are a software company, not a data center. For the thing you want to configure doesn't matter whether you upload YetiForce or any other app. 
2. Please read carefully this article: https://yetiforce.com/en/implementer/optimization/102-mysql-optimization.html  In my opinion, it isn't a good idea to configure it on RAID50 and from what I can see you're using SAS disks and that's another mistake. 
3. What you have [or want to achieve] on IOPS for write and save?
4. We know nothing about your system, the number of users doesn't say much, it would be necessary to perform some performance tests... define bottle necks... Now it appears that you are trying to blindly seek for the solution but you shouldn't do that.

**Comment by nic86** [comment]
We thought of a load balancing for high availability but with good reliability and we were hoping that someone with more experience could help in scaling one lamp stack.
We read your article on the database server configuration, our database server will be, as you described, a physical server with raid 10, of course we know that we must monitor the queries that do not use indexes.
We thought of a raid 50 for the dedicated web server because it allows us similar performance to raid 10 but more space to use for other services. 
We were thinking of use SAS HDD, not SATA SSD, as a matter of cost and reliability, for now we thought it was not necessary to have more than ~1000 IOPS but if in the future it will be necessary, we will update the system with SATA SSD, you think it is better to use immediately SATA SSD or a mix of both?
We will do tests as you suggest in order to understand where are the bottlenecks (there would be grateful if you have any solutions to suggest or link to recom

thanks for your time.

**Comment by bpabiszczak** [comment]
I fully understand you but before you start planning load balancing, you should first verify which resources you need to use for the traffic and the number of users that you planned and tools such as jmeter can be used for that. After these tests you will know what kind of machine you need and you will be able to plan other segments of the structure. I don't know how much load you will have for 1000 users, so I'm not sure whether the processor, memory and disks, which you planned, are good or not and what is your supply of resources. What you submitted looks good, but to me it seems as pure guesswork.

Secondly, I don't know what you want to achieve business-wise. Why are you thinking of a data center? You could take e.g. a cloud like OVH where you have continuity of operations and you can dynamically upgrade cloud resources. Clouds in such data centers guarantee a much better scaling, accessibility and higher quality of solutions than you can achieve with load balancing with two www servers. Please bare in mind that it's only my opinion and I'm not an expert in this field. 

You consider 1000 IOPS as enough and we have 250.000 IOPS on read and 144.000 on write on our testing servers. I suppose that the server we use for testing and fun [where gitdeveloper is located] will be much faster that your solutions planned for 100 clients. Obviously, it's the consequence of an attempt to offer hosting at the lowest possible cost...

**Comment by nic86** [comment]
Thanks for the feedback.
We decided to buy our server because we already have our own space in a datacenter. We are forced  to go a little bit blind because we have never designed a lamp stack so important , so we tend to oversize the hardware to not fall into bottlenecks.
Will use as you indicated a software for the web server benchmark to track the bottlenecks, if IOPS (tps in iostat) should not be enough, we will update the hard disk with SSD and we will publish the results.
