### ISSUE TITLE
SQL MERGE

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3373]
Hello,

I will like to know if there is any way to connect my 4 sql databases to the database of yetiforce, so i can see the field's from my databases into a module and i can change the information on that. 
I'm willing to pay what it takes if it needs some more development.

**Comment by vovpff** [comment]
@immhub you can mademanuall import of databases data directly to yetiforce. This is greatest way.
If you wanna pay - I think you can buy migration service at [Yeti Shop](https://shop.yetiforce.com/en/)

**Comment by immhub** [comment]
Tks,

But i want to write the databases from yetiforce .... something like database warehouse.

**Comment by vovpff** [comment]
@immhub please explain more edtailed what you need?

**Comment by immhub** [comment]
I have 4 sql db and i want to acces and edit the tables from those sql with yetiforce . And i am looking for a solution to unite those db into one so than i will have 5 db .... (4 that i allready have and 1 that is for yetiforce sistem). Yetiforce will have to write all the databases in realtime or something like CRON.

**Comment by vovpff** [comment]
@immhub Thx for explanation. I don't have experience with this. Maybe somebody advic you something.

**Comment by dextras** [comment]
Maybe database (table) replication? http://dev.mysql.com/doc/refman/5.7/en/replication.html. The yetiforce DB would be the master and the other 4 would be slaves. It would work if the 4 DB's are only used for reading.

**Comment by KatarzynaUlichnowska** [comment]
What you're trying to do is a difficult integration process of two different systems. These operations shouldn't be handled by DB, but API. What you want to achieve requires a dedicated approach and many days of work.
