### ISSUE TITLE
Nie znaleziono maila w bazie.Zaimportuj maila ręcznie

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#3374]
Nie działa opcja importuj nie pojawia  się dodatkowe menu w roundcube używam wersji  3.1.6 ,

**Comment by hipernet** [comment]
niby pobiera emaila ale okno się nie pojawia  przy poprzedniej wersji było ok

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/github/issues/125-issues.html

**Comment by hipernet** [comment]
Invalid request - Response For Illegal Access

**Comment by hipernet** [comment]
![2](https://cloud.githubusercontent.com/assets/20052436/17821554/7ad93706-6652-11e6-9cee-39aacc2dbfe0.gif)
pobiera email ale nie rozwija menu

**Comment by hipernet** [comment]
Jest szansa na jakies wskazowki

**Comment by bpabiszczak** [comment]
Sprawdź wersje gitdeveloper... i sprawdź wersje gitstable... Pokazujesz to na jakieś wersji modyfikowanej, a takiej to my nawet nie dotykamy :D

**Comment by hipernet** [comment]
można zrobić downgrade?

**Comment by bpabiszczak** [comment]
Nie :] bo i po co...

**Comment by hipernet** [comment]
to jak mam wrócić do funkcjonalności roundcube backupa nie mam  korzystam z wersji 3.1.67
zniknęło rozwijanie menu w poczcie

**Comment by bpabiszczak** [comment]
Najlepiej uaktualnić do nowszej wersji :] Jutro/pojutrze publikujemy wersji 3.2 wówczas rozwiąże to Twój problem.

**Comment by hipernet** [comment]
dzięki ,

**Comment by hipernet** [comment]
czy będzie dziś nowa wersja ? chciałbym zrobić update

**Comment by bpabiszczak** [comment]
Nie.

**Comment by hipernet** [comment]
Po upgrade chwile pracowało poprawnie teraz znowu błąd
Invalid request - Response For Illegal Access

**Comment by hipernet** [comment]
nie ma juz do tego cierpliwości , system fajny ale ciągle się coś rozjeżdża

**Comment by bpabiszczak** [comment]
To nie używaj :]

**Comment by hipernet** [comment]
przeprosiłem sie z systemem , trzeba  być optymistycznie nastawiony

**Comment by bpabiszczak** [comment]
Najlepiej sprawdź czy problem występuje na naszej wersji https://gitdeveloper.yetiforce.com/
