### ISSUE TITLE
[Question] How Transfer Ownership works?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3375]
#### Issue

I tried "Transfer Ownership" feature.

#### Actual Behavior

There is no possibility transfer ownership for all contacts related to account to another user.

But there is no problem to change ownership from contact for related account (member of).

After actions on gif below there is appears next errors

![image](https://cloud.githubusercontent.com/assets/8545791/17748357/a1806484-64c1-11e6-9769-82e4c073b6eb.png)
![image](https://cloud.githubusercontent.com/assets/8545791/17748364/aa8e33d0-64c1-11e6-8ba6-30e92d646188.png)

After clicking "check updates read and refreshing page I get error

![image](https://cloud.githubusercontent.com/assets/8545791/17748401/dee48242-64c1-11e6-9a35-1bc741d891f5.png)

#### Expected Behavior

Checking how this feature works

#### How to trigger the error

1. ![trans owner](https://cloud.githubusercontent.com/assets/8545791/17748416/f8cbfcb2-64c1-11e6-961e-0c120aee9304.gif)

#### Your Environment

* YetiForce Version used: dev [ver. 3.1.96
* Browser name and version: Chrome last ver.
* Environment name and version:
* Operating System and version: Win 10 x64

**Comment by paula-w** [comment]
Can you check it on the dev version again?  It should work now.

**Comment by vovpff** [comment]
@paula-w I checked this. Account contacts transfer works but there is some bugs:
There is previous assigned user missed:
![image](https://cloud.githubusercontent.com/assets/8545791/17813349/ba86d166-6633-11e6-9d11-15e38a3c6f1b.png)
Strange but at updates tab there is no data about assigned user changes:
![image](https://cloud.githubusercontent.com/assets/8545791/17813416/ee0ceeb2-6633-11e6-9e25-e11262f54097.png)
After turning back to summary record about assigned user was changed dissapears too:
![image](https://cloud.githubusercontent.com/assets/8545791/17813459/1e5884dc-6634-11e6-8643-4a4f7a3d2ada.png)
Contact what changed has next error:
![image](https://cloud.githubusercontent.com/assets/8545791/17813485/3aaf3e1e-6634-11e6-81ba-fff9419cebb6.png)
`#0 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/Record.php(351): CRMEntity->retrieve_entity_info(113, 'Accounts')
#1 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/ModTracker/models/Record.php(185): Vtiger_Record_Model::getInstanceById(113, 'Accounts')
#2 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/ModTracker/models/Record.php(48): ModTracker_Record_Model->setParent(113, 'Accounts')
#3 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/views/Detail.php(388): ModTracker_Record_Model::getUpdates('113', Object(Vtiger_Paging_Model), 'changes')
#4 [internal function]: Vtiger_Detail_View->showRecentActivities(Object(Vtiger_Request))
#5 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/include/runtime/Controller.php(89): call_user_func_array(Array, Array)
#6 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/views/Detail.php(194): Vtiger_Controller->invokeExposedMethod('showRecentActiv...', Object(Vtiger_Request))
#7 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/include/main/WebUI.php(220): Vtiger_Detail_View->process(Object(Vtiger_Request))
#8 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/index.php(24): Vtiger_WebUI->process(Object(Vtiger_Request))
#9 {main}`

**Comment by vovpff** [comment]
@paula-w pls check gif
![trans owner 2](https://cloud.githubusercontent.com/assets/8545791/17813804/861759b2-6635-11e6-85cd-70c6d254f92a.gif)

**Comment by TomaszQr** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/0dd55570a8e45b54aeecb1c5075fac30d09c135f

**Comment by TomaszQr** [comment]
Can you check if the error still exists ?

**Comment by vovpff** [comment]
@TomaszQr looks like issue bug are fixed but at updates section information not correct:
After transfer from demo to admin and one more time from admin to demo there are next updates
![image](https://cloud.githubusercontent.com/assets/8545791/17854666/e19d3704-687c-11e6-8e69-16a8924ad024.png)

**Comment by vovpff** [comment]
@TomaszQr Thx! Very nice!
