### ISSUE TITLE
[PL] Propozycja branchowania w repozytorium

### ISSUE THREAD

**Issue by majkel89** [YetiForceCompany/YetiForceCRM#3376]
Proponuje aby zastosować model branchowania jaki stosuje się w większości projektów open-source. A mianowicie tworzyć oddzielny branch na każdy release.

Np.:

```
v3
v3.1 (ostati tag v3.1.14)
v3.2 (ostati tag v3.2.1)
v3.3 (ostati tag v3.3.3)
```

W ten sposób jak ktoś znajdzie błąd w wersji 3.0.0 to będzie można zrobić forka poprawić go tam i zmergować do pozostałych gałęzi.

Końcowi użytkownicy zazwyczaj siedzą cały czas na wersji na której został postawiony projekt np 3.1 i z obawy przed zepsuciem czegoś nie aktualizują systemu do wyższych wersji. Zastosowanie powyższego schematu branchowania pozwoli im na aktualizowanie systemu w celu wyeliminowania drobnych usterek lub krytycznych błędów bezpieczeństwa.

**Comment by bpabiszczak** [comment]
Nie jest to jakiś zły pomysł, w końcu wiele projektów z niego korzysta... ale jakoś dobrze nam z tym co mamy obecnie. Do każdej wersji udostępniamy paczki aktualizacyjne z wersji A do B, do tego mam 3 dostępne branche cały czas które sami testujemy i weryfikujemy. 

Nawet jeżeli ktoś używa starszych wersji [prócz LTS] to i tak pierwsze co usłyszy przy dodawaniu błędów to aby uaktualnił do nowej wersji. Jeżeli ktoś nie chce mieć najnowszej wersji to już jego problem, jeżeli widzi tam jakieś błędy, to niech poprawi je tak aby ich nie było, jeżeli musi nadpisać jakiś plik systemowy, to niech rozbuduje tak mechanizm composera aby nie musiał tego robić. 

Wychodzimy z założenia, że każdy powinien używać ostatniej stabilnej wersji. Paczki aktualizacyjne są tak robione, że w każdym momencie z wersji X.Y.1 możemy zmigrować X.Y.Z a więc nie ma znaczenia którą wersje pośrednią ktoś ma. 

Całość jest opisana tutaj: https://yetiforce.com/pl/wdro%C5%BCeniowiec/instalacja-aktualizacja/137-numeracja-systemu-yetiforce.html.

W mojej opinii na pewno to lepiej wygląda niż ten bajzel z wersjami tutaj: https://github.com/salesagility/SuiteCRM

**Comment by bpabiszczak** [comment]
Zamykamy skoro nie ma nikt nic do dodania :]
