### ISSUE TITLE
Error while adding any condition: Fatal error: Array ( [message] => SQLSTATE[23000]

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3382]
Tested on gitdeveloper.yetiforce.com, version: 3.1.963
Instructions:
1. Go to system configuration → automation → recording control
2. Go to tickets preview. Click “next”
3. Add condition as Any condition. From the list select "Report time" field. Click next.
4. Error pops up. Check the screenshot. 

[PL]
Błąd dodawania dowolnego warunku: Fatal error: Array ( [message] => SQLSTATE[23000]
Testowane na gitdeveloper.yetiforce.com, wersja:  3.1.963
Instrukcje:
1. Przejdź do Konfiguracji systemu. Wybierz Automatyzację. Następnie wybierz Kontrolę zapisu.
2. Przejdź do podglądu pierwszego wiersza – Zgłoszenia. Kliknij na przycisk Dalej.
3. Dodaj warunek jako Dowolny warunek. Z listy wyboru wybierz pole: Czas zgłoszenia. Kliknij  - Dalej.
4. Pojawia się błąd. Zobacz zrzut ekranu.
![80 wykonanie](https://cloud.githubusercontent.com/assets/11139594/17768316/c7370c42-6533-11e6-81a3-e1caf2c78f2f.png)
![80](https://cloud.githubusercontent.com/assets/11139594/17768321/cb68b5d6-6533-11e6-99a2-a2cb67bd7fed.png)

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3381
