### ISSUE TITLE
[BUG] Invoice from breaks when system currencies are changed

### ISSUE THREAD

**Issue by majkel89** [YetiForceCompany/YetiForceCRM#3384]
#### Issue

When system currency configuration is changed, invoice form breaks when trying to change currency to new one.
#### Actual Behavior

Invoice form breaks when trying to change currency to the newly added.
#### Expected Behavior

Currencies in invoice should adapt properly to changes in system currency configuration.
- when new currency is added old invoices should be able to change to newly created currency
- when currency is deleted invoices using that currency should be valid and still display that currency
#### How to trigger the error
1. Some currencies should be defined in the system
2. Some invoices should be present in the system
3. Add new currency in system configuration
4. Edit any of the previously created invoices
5. Change currency to the newly added - the form breaks due to js error
#### Your Environment
- YetiForce Version used: stable, develop
#### Pull request

I'm unable to make pull request due to error https://github.com/YetiForceCompany/YetiForceCRM/issues/3383

**Comment by majkel89** [comment]
There is still a problem. Lets begin with currencies $, EURO. I add invoice with those curencies, than i remove EURO from the system. When i open invoice agine i will not be able to change it to $ properly.

Also when I add new currency and open invoice that already been in the system the only coversion rate i will bet will be "one". I think conversion rate should be taken from the system.

**Comment by bpabiszczak** [comment]
You can not delete the currency that is being used.
