### ISSUE TITLE
[Issue] [PL] Działanie pola Zaproszeni użytkownicy 

### ISSUE THREAD

**Issue by dkrakowski** [YetiForceCompany/YetiForceCRM#3386]
Po wybraniu userów w polu zaproszeni użytkowników, nie mają oni żadnego zadania w kalendarzu ani powiadomienia z kalendarza. Identyczna sytuacja na gistable.

**Comment by bpabiszczak** [comment]
Funkcjonalność ta nie została jeszcze ukończona... będzie skończona w wersji 3.3.
