### ISSUE TITLE
[Question] How can I change the default values to create a user?

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3387]
Good afternoon,

mainly, I would like to change these fields:
'Default Lead view', 'Date format', 'Default Calendar view'
especially
'Internal mail composer'
to use by default roundcube

![user](https://cloud.githubusercontent.com/assets/18419851/17809618/ba533cd0-660f-11e6-8ec7-74507cf93662.gif)

Thanks in advance

**Comment by konadrian** [comment]
We don't have any panel to change these settings, you can set default values directly in the database, in the vtiger_field table "defaultvalue" column.
For example, in the vtiger_filed table find a record where columnname = lead_view, and instert the value from select into the defaultvalue column.
It will change the default value for the Default Lead view field

**Comment by dextras** [comment]
To be more specific: You can run this sql command to get the list of all the fields that belong to users database: SELECT fieldlabel,defaultvalue FROM `vtiger_field` where tablename='vtiger_users' ORDER BY `fieldlabel` ASC  (you can use for example phpmyadmin for that purpose). Then just change the values indicated by  the column defaultvalue as konadrian mentioned. 

To be sure you do not do any mistakes check in the table vtiger_users how the actual values are stored in the database for some example user.
