### ISSUE TITLE
Adding Process in Events/To Do is inactive

### ISSUE THREAD

**Issue by liberox** [YetiForceCompany/YetiForceCRM#3389]
#### Issue
Adding Process in Events/To Do is inactive. I want to relate Event/To Do with a project.

#### Actual Behavior
Process field is inactive

#### Expected Behavior
I expect to be able to choose related modules

#### How to trigger the error
Gif file is attached 
![animation](https://cloud.githubusercontent.com/assets/21132169/17823464/eff531f2-665c-11e6-93e3-205731ac7348.gif)

#### Your Environment

* YetiForce Version used: YetiForce test version og githubdeveloper
* Browser name and version: Firefox 47.0
* Environment name and version:
* Operating System and version: Windows 10

**Comment by kpaulaha** [comment]
You have to select first company/contact.

**Comment by konadrian** [comment]
as @kpaulaha sadi you have to selecet companty/contact first, then this field will be enabled
