### ISSUE TITLE
[Question] Change the user name structure.

### ISSUE THREAD

**Issue by michelmarques1** [YetiForceCompany/YetiForceCRM#3390]
Hello Community Colleagues,

The CRM user name structure is:

Clinton Richard (Surname and Name)

But I need to change:

Richard Clinton (name and surname)

There is no such option in the system settings (unlike Vtiger).

Which CRM file should I change?

![image](https://cloud.githubusercontent.com/assets/18095104/17835247/7bd47782-6739-11e6-9ab6-799b895eb680.png)

**Comment by bpabiszczak** [comment]
Check here: `vtiger_entityname`. This change can break your system.
