### ISSUE TITLE
got  Non-static method should not be called statically error

### ISSUE THREAD

**Issue by bashayerar** [YetiForceCompany/YetiForceCRM#3391]
#### Issue
In every page I got 
PHP Strict Standards: Non-static method Config::getData() should not be called statically, assuming $this from incompatible context in 16 line error

#### Expected Behavior
not showing that msg error

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: last ver. 3.1.0
* Browser name and version: chrom 
* Environme2nt name and version:
* Operating System and version: windows 8

**Comment by majkel89** [comment]
I suggest to disable `E_STRICT` in error reporting

````php
error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED);
````

Btw something like that should be included out of the box in `index.php` or some config file.

**Comment by bashayerar** [comment]
I think of that but I do you know if that will affect performance later or not ?

**Comment by majkel89** [comment]
This will not affect performance. The only thing this might affect is ability to debug potential errors. Sometimes notices are useful.

**Comment by bashayerar** [comment]
Thank you a lot that was helpful.
