### ISSUE TITLE
Set Crob job on 15, 5 or 1 min. frequency? 

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3392]
What is best time to set Cron frequency?  15, 5 or 1 minute? 

As I saw in soft.config->>automation->>cron   we have some jobs on 1min, 3min, 5min etc. 
If I set cron on 5min, jobs setted to 1min will execute only once on five minute instead five times. 

Is it ok to set Cron job to 1min on server? Members how offten did you set Cron? 
I dont see logic to set it on15min or 5min if we have some cron jobs that should be able to execute every 1min (eg. Mail Scanner Verification) ?

In documentation https://yetiforce.com/en/administrator-documentation/panel/cron/150-enable-cron.html   is 5min

In some issues on github is  advised on 15min or 5min.

Regards 🍻
What to do?

**Comment by florek41** [comment]
I think it all depends on the server performance. if CRON has a lot of tasks it can slow down server and your 1 minute will take ex. 2min. so all resources will be exhausted really fast.

On the other hand it depends how fast you need update from for ex. Mail Scanner Verification - if it is 1 minute set CRON to 1minute but be sure about that there is no unnecessary tasks on every minute.

**Comment by paula-w** [comment]
It doesn't really matter, since even if cron hasn't finished before another one is supposed to start, then the system won't launch it for as long as the first one isn't done.
