### ISSUE TITLE
[BUG] Lang Editor Partners

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#3393]
![animation 2](https://cloud.githubusercontent.com/assets/1402355/17843563/e4eee3f0-6848-11e6-950b-1d408707c528.gif)

**Comment by konadrian** [comment]
![animation](https://cloud.githubusercontent.com/assets/3193498/17849051/2ac3f902-6857-11e6-853c-0c557f3a4a23.gif)
I can't reproduce the error in the current version

**Comment by waw555** [comment]
in version 3.2.34 don't work
