### ISSUE TITLE
[bug] Mapping

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3394]
Not quite sure if I got all the permissions right, but I should think so

#### Issue
If a user is not a admin, although he is a member to a role, that has permission to the mapping, he is not able to use the mapping.
![mapping](https://cloud.githubusercontent.com/assets/10330264/17847438/a7540436-6856-11e6-9951-1f4eedeaac19.png)

#### Actual Behavior
Not admin, but should have rights
![map2](https://cloud.githubusercontent.com/assets/10330264/17847423/8838d2b6-6856-11e6-8e30-b41f3e2aeeed.png)

When opening record not made by you (not admin)
![program manager](https://cloud.githubusercontent.com/assets/10330264/17849795/1e34fd7e-6863-11e6-8fdd-d0adcc207940.png)

#### Expected Behavior

![map1](https://cloud.githubusercontent.com/assets/10330264/17847408/74c8635e-6856-11e6-8464-ac6073595530.png)

#### How to trigger the error

1. Two users, other admin, other not, both members of same role
2. Give permission to mapping
3. Go to ISTDN or other with mapping

#### Your Environment

* YetiForce Version used: 3.1.994
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by TomaszQr** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/5161576d58e92390e76816312061a3ba49e99db6
Can you check if the error still exists ?

**Comment by kpaulaha** [comment]
Jup, seems work now. But when opening any record that is not assigned to that user gives: 
![permission denied](https://cloud.githubusercontent.com/assets/10330264/17858134/28b41ba2-688d-11e6-90d8-02c446f7e139.png)

**Comment by bpabiszczak** [comment]
Please open new issue.
