### ISSUE TITLE
Recurring invoices

### ISSUE THREAD

**Issue by jgonzalezgonzalez** [YetiForceCompany/YetiForceCRM#3395]
Hi there!

I´m currently working with v 3.1.0 and I´m not able to settle recurring invoicing. Where can I get more info about it? I´ve tried many things from Recurring Sales Orders but nothing seems to work.

Regards.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/2331

**Comment by jgonzalezgonzalez** [comment]
Good morning



I see you´ve closed 3395 issue referring to my post on 2331 issue, but with
no answer by your side.

Is there any way you can help me?



Best regards




*JUAN GONZÁLEZ GONZÁLEZ*COO

[image: Iberia Group] <http://www.iberiatechnologies.com/>

Musgo, 2 Bajo F
C.P. 28023-MADRID
Tel: +34 913918435
Fax: +34 912901850

www.iberiatechnologies.com

Este correo electrónico y la información contenida en el mismo es de
carácter confidencial, dirigiéndose exclusivamente al destinatario
mencionado en el encabezamiento, cuyos datos forman parte de un fichero
responsabilidad de la empresa con domicilio en la dirección indicada
anteriormente, con la única finalidad de gestionar y mantener los mismos,
como medio paracanalizar las oportunas comunicaciones que se produzcan como
consecuencia de la relación que mantiene con la empresa o alguno de sus
empleados. La empresa le garantiza la posibilidad de ejercitar sus derechos
de acceso, rectificación, cancelación y oposición al tratamiento de sus
datos, dirigiendo una comunicación por escrito a la dirección indicada
anteriormente. Si el receptor de la comunicación no fuera el destinatario,
le rogamos nos comunique de inmediato y proceda a destruir el mensaje
recibido. Cualquier divulgación, copia, distribución o utilización no
autorizada de la información contenida en el mismo está prohibida por la
legislación vigente.

[image: www.iberiagroup.com]

Before you print this message please consider if it is really necessary
Antes de imprimir este mensaje, por favor compruebe que es necesario
hacerlo.



*De:* Błażej Pabiszczak [mailto:notifications@github.com]
*Enviado el:* lunes, 22 de agosto de 2016 23:27
*Para:* YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
*CC:* jgonzalezgonzalez <jgonzalez@iberiagroup.com>; Author <
author@noreply.github.com>
*Asunto:* Re: [YetiForceCompany/YetiForceCRM] Recurring invoices (#3395)



Closed #3395 <https://github.com/YetiForceCompany/YetiForceCRM/issues/3395>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/YetiForceCompany/YetiForceCRM/issues/3395#event-763660744>,
or mute the thread

**Comment by paula-w** [comment]
According to what we wrote in https://github.com/YetiForceCompany/YetiForceCRM/issues/2331 the module has not yet been finished, it will most likely be finished in the next version.

**Comment by jgonzalezgonzalez** [comment]
Thank you Paulina,



According to what you wrote in #2331,  “it will be fully functional in v3.1
(end of May).”

I am currently using v 3.1.0, that´s why I asked.



Could you please confirm that, as you posted, the system (in v3.1) is able
to automatically generate single orders from recurring orders, and then
automatically generate invoices? If so, could you please help me with that



Best regards




*JUAN GONZÁLEZ GONZÁLEZ*COO

[image: Iberia Group] <http://www.iberiatechnologies.com/>

Musgo, 2 Bajo F
C.P. 28023-MADRID
Tel: +34 913918435
Fax: +34 912901850

www.iberiatechnologies.com

Este correo electrónico y la información contenida en el mismo es de
carácter confidencial, dirigiéndose exclusivamente al destinatario
mencionado en el encabezamiento, cuyos datos forman parte de un fichero
responsabilidad de la empresa con domicilio en la dirección indicada
anteriormente, con la única finalidad de gestionar y mantener los mismos,
como medio paracanalizar las oportunas comunicaciones que se produzcan como
consecuencia de la relación que mantiene con la empresa o alguno de sus
empleados. La empresa le garantiza la posibilidad de ejercitar sus derechos
de acceso, rectificación, cancelación y oposición al tratamiento de sus
datos, dirigiendo una comunicación por escrito a la dirección indicada
anteriormente. Si el receptor de la comunicación no fuera el destinatario,
le rogamos nos comunique de inmediato y proceda a destruir el mensaje
recibido. Cualquier divulgación, copia, distribución o utilización no
autorizada de la información contenida en el mismo está prohibida por la
legislación vigente.

[image: www.iberiagroup.com]

Before you print this message please consider if it is really necessary
Antes de imprimir este mensaje, por favor compruebe que es necesario
hacerlo.



*De:* Paula W [mailto:notifications@github.com]
*Enviado el:* martes, 23 de agosto de 2016 10:26
*Para:* YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
*CC:* jgonzalezgonzalez <jgonzalez@iberiagroup.com>; Author <
author@noreply.github.com>
*Asunto:* Re: [YetiForceCompany/YetiForceCRM] Recurring invoices (#3395)



According to what we wrote in #2331
<https://github.com/YetiForceCompany/YetiForceCRM/issues/2331> the module
has not yet been finished, it will most likely be finished in the next
version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/YetiForceCompany/YetiForceCRM/issues/3395#issuecomment-241661781>,
or mute the thread

**Comment by paula-w** [comment]
It was not added in 3.1, which is why that issue is still open.

**Comment by jgonzalezgonzalez** [comment]
Thank you Paulina



When do you plan to add it?

On the other hand, which is the latest downloadable versión?



Regards,




*JUAN GONZÁLEZ GONZÁLEZ*COO

[image: Iberia Group] <http://www.iberiatechnologies.com/>

Musgo, 2 Bajo F
C.P. 28023-MADRID
Tel: +34 913918435
Fax: +34 912901850

www.iberiatechnologies.com

Este correo electrónico y la información contenida en el mismo es de
carácter confidencial, dirigiéndose exclusivamente al destinatario
mencionado en el encabezamiento, cuyos datos forman parte de un fichero
responsabilidad de la empresa con domicilio en la dirección indicada
anteriormente, con la única finalidad de gestionar y mantener los mismos,
como medio paracanalizar las oportunas comunicaciones que se produzcan como
consecuencia de la relación que mantiene con la empresa o alguno de sus
empleados. La empresa le garantiza la posibilidad de ejercitar sus derechos
de acceso, rectificación, cancelación y oposición al tratamiento de sus
datos, dirigiendo una comunicación por escrito a la dirección indicada
anteriormente. Si el receptor de la comunicación no fuera el destinatario,
le rogamos nos comunique de inmediato y proceda a destruir el mensaje
recibido. Cualquier divulgación, copia, distribución o utilización no
autorizada de la información contenida en el mismo está prohibida por la
legislación vigente.

[image: www.iberiagroup.com]

Before you print this message please consider if it is really necessary
Antes de imprimir este mensaje, por favor compruebe que es necesario
hacerlo.



*De:* Paula W [mailto:notifications@github.com]
*Enviado el:* martes, 23 de agosto de 2016 10:46
*Para:* YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
*CC:* jgonzalezgonzalez <jgonzalez@iberiagroup.com>; Author <
author@noreply.github.com>
*Asunto:* Re: [YetiForceCompany/YetiForceCRM] Recurring invoices (#3395)



It was not added in 3.1, which is why that issue is still open.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/YetiForceCompany/YetiForceCRM/issues/3395#issuecomment-241666473>,
or mute the thread
