### ISSUE TITLE
Question: Where do I change the language for the Tax types?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3396]
hi

#### Issue
I am trying to change the language strings for the tax labels of Global, Individual etc. and have gone through the language files but cannot find where this is. I have also gone through the fields on the MySql database. I did manage to change the string in the Vtiger language file, but this has no effect on the picklist in the Invoice creation form (at bottom where it asks you to select tax mode.

Are these language strings in another file that is not so obvious?

* YetiForce Version used: 3.1.xxx

Kind regards

Percy

**Comment by vovpff** [comment]
@PercyP try this: module Vtiger
![image](https://cloud.githubusercontent.com/assets/8545791/17854742/6215af1a-687d-11e6-9ab9-59b990edd2c7.png)

**Comment by PercyP** [comment]
@vovpff 

thanks for response. The bits I am looking to change don't appear in that vtiger language file section. Basically I want to change the language in the invoice module (and elsewhere it may appear) see image:
![mode](https://cloud.githubusercontent.com/assets/10598886/17856579/20723e22-6876-11e6-98da-d52c67113de5.png)

But its proving impossible to track down :(

**Comment by nic86** [comment]
for search label on linux shell using this command from the root of yeti:

`grep -i 'label to find' languages/en_us/* -R`

eg. find the tax Label:

`grep -i 'Tax Mode' languages/en_us/* -R`

result:
languages/en_us/Vtiger.php:	**'LBL_TAX_MODE' => 'Tax Mode'**,

copy the line in bold in your languages file that find under language folder

**Comment by vovpff** [comment]
@PercyP let's check this:
```
\languages\en_us\Vtiger.php (8 hits)
	Line 340: 	'LBL_INDIVIDUAL' => 'Individual',
	Line 340: 	'LBL_INDIVIDUAL' => 'Individual',
	Line 984: 	'LBL_INDIVIDUAL_DISCOUNTS' => 'Individual',
	Line 984: 	'LBL_INDIVIDUAL_DISCOUNTS' => 'Individual',
	Line 1004: 	'LBL_INDIVIDUAL_TAX' => 'Individual',
	Line 1004: 	'LBL_INDIVIDUAL_TAX' => 'Individual',
	Line 1050: 	'individual' => 'Individual',
	Line 1050: 	'individual' => 'Individual',
```

```
\languages\en_us\Vtiger.php (27 hits)
	Line 173: 	'LBL_ADD_GROUP' => 'Add Group', //Duplicated key-value pairs
	Line 173: 	'LBL_ADD_GROUP' => 'Add Group', //Duplicated key-value pairs
	Line 326: 	'LBL_GROUP' => 'Group', //Duplicated key-value pairs
	Line 326: 	'LBL_GROUP' => 'Group', //Duplicated key-value pairs
	Line 327: 	'LBL_GROUPS' => 'Groups',
	Line 327: 	'LBL_GROUPS' => 'Groups',
	Line 328: 	'LBL_GROUP_TAX' => 'Group Tax',
	Line 328: 	'LBL_GROUP_TAX' => 'Group Tax',
	Line 856: 	'LBL_TOTAL_DISCOUNT' => 'Group discount',
	Line 943: 	'LBL_CV_GROUP_MINE' => 'Mine',
	Line 944: 	'LBL_CV_GROUP_SYSTEM' => 'System',
	Line 945: 	'LBL_CV_GROUP_OTHERS' => 'Shared',
	Line 946: 	'LBL_CV_GROUP_PENDING' => 'Pending',
	Line 954: 	'Support Group' => 'Support Group',
	Line 954: 	'Support Group' => 'Support Group',
	Line 955: 	'Marketing Group' => 'Marketing Group',
	Line 955: 	'Marketing Group' => 'Marketing Group',
	Line 983: 	'LBL_GROUP_DISCOUNTS' => 'Group',
	Line 983: 	'LBL_GROUP_DISCOUNTS' => 'Group',
	Line 1005: 	'LBL_GROUP_TAXS' => 'Group',
	Line 1005: 	'LBL_GROUP_TAXS' => 'Group',
	Line 1049: 	'group' => 'Group',
	Line 1049: 	'group' => 'Group',
	Line 1069: 	'Groups' => 'Groups',
	Line 1069: 	'Groups' => 'Groups',
	Line 1244: 	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'You have to select the records in the same groups for merging',
	Line 1244: 	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'You have to select the records in the same groups for merging',
```

**Comment by PercyP** [comment]
@nic86 @vovpff 

thanks both. I have actually changed all of those, but they don't have an effect on those strings in the dropdown boxes. I assumed they may be picklists but they don't even appear in the picklist manager.

Can I ask, if you changed those values in your system do they change on the front end (within invoices)?

Percy

**Comment by nic86** [comment]
if you mean the label of picklist "Group" and "Individual"  they are in the file vtiger.php
line 326: 'LBL_GROUP' => 'Group',
line 340: 'LBL_INDIVIDUAL' => 'Individual',

**Comment by PercyP** [comment]
@nic86 

aha! thank you all. When I go in to the Language section to edit the file within the Yetiforce it does not display all the language strings in there. I event tried searching for them but came back as zero. Now when I go to the file on my server /languages/vtiger.php I can see the extra strings I need to change. I have now made those last 2 changes you pointed me to and it worked :)

Once again thanks

**Comment by vovpff** [comment]
@PercyP 

![image](https://cloud.githubusercontent.com/assets/8545791/17863222/8a2ce68e-68a1-11e6-9e3d-a6a82da3cd53.png)
latest dev. versuion!
