### ISSUE TITLE
Nie można zrobić update [PL]

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#3397]
Nie można zaktalizować programu z pliku zipa. Nie przechodzi do strony głównej.

#### Your Environment

* YetiForce Version used:3.1.691
* Browser name and version: Firefox
* Environment name and version:
* Operating System and version:Linux

**Comment by bpabiszczak** [comment]
Link do pliku...

**Comment by hipernet** [comment]
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x/3.1.0_to_3.2.0/zip

**Comment by bpabiszczak** [comment]
O ile dobrze pamiętam, to w wersji jakieś tam pojawiła się zmiana w plikach vtlib... i ona nie umożliwia wgranie tej samej paczki ponownie [znaczy takiej, która aktualizuje od początku czyli 3.1.0]... jutro się programista na ten temat odezwie.

**Comment by rskrzypczak** [comment]
W chwili obecnej aktualizacja systemu jest możliwa za pomocą paczki aktualizacyjnej najpóźniej w wersji 3.1.247. W czasie późniejszym dokonano znaczących zmian w kodzie źródłowym CRM i skrypt zawarty w paczce aktualizacyjnej jest nieaktualny.
Dlatego pojawiają Ci się błędy przy próbie aktualizacji CRM z wyższych wersji systemu.

**Comment by bpabiszczak** [comment]
hipernet Ty masz produkcje do tej wersji uaktualnioną?

**Comment by hipernet** [comment]
mam wersje  3.1.691

**Comment by bpabiszczak** [comment]
a więc na chwilę obecną, będziesz musiał poczekać do momentu wydania paczki dla tych "szczęśliwców" który mają wersje wyższe niż 3.1.247.
