### ISSUE TITLE
Special function in invoices dont shows summary

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#34]
This function: #special_function#replaceProductTable2#end_special_function# 
Dont show summary in the bottom of table when I style it with some core font and size in PDF template.
Seems like size of fonts in table is hardcoded. Would be convenient to be able to style tables at least with fonts size/style/color within editor
--------
Seems like 16pt working but not 14 O.o

**Comment by rskrzypczak** [comment]
"Please send us detailed information. Screenshots would be helpful.

Size/style/color of fonts in tables can be modified in a PDF templete."
