### ISSUE TITLE
[bug] calendar quick create

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3403]
v. 3.1.1008
Looking for the available start date causes never ending loading.

![calendar](https://cloud.githubusercontent.com/assets/10330264/17883063/fda371c4-6918-11e6-9e27-8ff1ea89dbba.gif)

**Comment by TomaszQr** [comment]
I need more info. Prove me with the user's settings, date and time format, start time, day start time, day end time, time zone. Also let me know what browser and system you use.

**Comment by kpaulaha** [comment]
I made in gitdeveloper.yetiforce.com a new user, default settings, not admin (with admin it works). Just have it to find the first available date. Same with installation on our server, with admin ok, not admin no.
