### ISSUE TITLE
Update problem since 3.1.629 on Quick search, Organisations and Leads

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3404]
I updated from 3.1.629 to 3.1.1009 and I got
- No quick search
![image](https://cloud.githubusercontent.com/assets/1357727/17886634/081331a8-6923-11e6-8933-f723f91e3004.png)

-  In the History widget LBL_DISPLAYED nothing and in organisation or lead page the name doesn't display (It seems that the name of the field change during an update)
![image](https://cloud.githubusercontent.com/assets/1357727/17886615/eeadc336-6922-11e6-915d-dce4fe9ef650.png)

- And still cannot add an organisation or a lead
![image](https://cloud.githubusercontent.com/assets/1357727/17886645/0ff92120-6923-11e6-8c6c-2e1346e71e3a.png)

I also tried to downgrade to 3.1.0 and apply the update package to 3.1.998 and the result is the same.

* YetiForce Version used: 3.1.629 - 3.1.1009
* Browser name and version: Chrome Version 52.0.2743.116 m (64-bit)
* Environment name and version: Debian 8
* Operating System and version: Windows 10

**Comment by paula-w** [comment]
You couldn't update from a version higher than  3.1.247 because the mechanism changed, which means that:
- You don't enable logs while updating, and you don't check the logs to verify whether or not the update was executed correctly!
- You can update the package, but from eg. v3.1.0 to the latest one, and only as a test! You should wait for the production package.

**Comment by Raggazzoo** [comment]
Okay, is it possible to downgrade my database to 3.1.247 or 3.1.0?

If it is possible I can apply the update package to 3.1.998.

**Comment by paula-w** [comment]
After releasing 3.2 [or together with 3.2 release] we'll publish an additional package for people whose version is higher than 3.1.247.

**Comment by Raggazzoo** [comment]
Ok thank you =)
