### ISSUE TITLE
[Enhancement] Database - Add way to clean up crmentity and module tables

### ISSUE THREAD

**Issue by rage1985** [YetiForceCompany/YetiForceCRM#3405]
#### Issue
Trash Records will pile up in crmentity table.

#### Actual Behavior
This is a weakness from vTiger Core which made its way into Yeti also.
If you delete a record anywhere in the System, the record gets flagged as deleted in crmentity_table, and deleted in its module table.

If you are running the System for some Years many trash records will pile up in your crmentity table,
thus slowing down the system, becaue iteration will take longer.

#### Expected Behavior
Script/Button/Tools to finally cleanup the crmentity table with a Sql delete statement.  Perhaps even a global Trashcan for Records where an Admin can decide to finally send them into Nirvana.

#### How to trigger the error
Make several thousand record imports to your favorite module and delete them afterwards.
See how your crmentity table grows, and grows, and grows.

**Comment by dextras** [comment]
Isn't there a trash already available in yeticrm? Doesn't deleting an item from a trash remove it from database? Just curious. I did not test it.

**Comment by vovpff** [comment]
@rage1985 there is [Recycle Bin](https://gitdeveloper.yetiforce.com/index.php?module=RecycleBin&parent=&page=1&view=List&orderby=&sortorder=&sourceModule=Accounts&viewname=Accounts&search_value=&search_params=) but now this module not activated for users.

**Comment by PercyP** [comment]
I too would like to see this. I wanted to clear all current history and notifications so in the end resorted to clearing crmentity table manually, but this deletes everything, including products/services etc. which I would want to keep (it was only on a test site so was not a problem). It would be good if we had a way to select the sections we want to permanently delete from the crmentity table. 

I haven't been able to find a trash can in my version of 3.1 where is it?
Percy

**Comment by rage1985** [comment]
@vovpff I had a look as admin and couldn´t find can you tell us where it is?

**Comment by vovpff** [comment]
@rage1985 @PercyP go to Accounts and change `Accounts` in browser adress bar to `RecycleBin`

**Comment by PercyP** [comment]
@vovpff @rage1985 

Ah - thanks @vovpff just realised after your post, it is there, we just needed to create the menu item link to it. Go to Admin - Standard modules > Menu - Configuration and create a new module menu link (selecting the recycle bin).

**Comment by rage1985** [comment]
@vovpff @PercyP Ahh know i see why the links have been deactivated. The pagination Buttons seem to be broken... and only the Devs know what else.. 

I will have a look at the functions in this Module to see if it is what we want :D

If you truly consider to put Yeti into production clean and "small as can be" crmentity table is a must have.
The RecycleBin is nice to have, but i rather have them deleted once a week, by workflow. I think it depends on how many Records you have deleted in a short time frame.

**Comment by vovpff** [comment]
@rage1985 @PercyP @bpabiszczak I tried recycle Bin in a past on ver.2.2. This module was broken #1924 and 
I think this module and possibility to periodical permanent cleaning of database are very usefull feature for companies with a lot of unusefull stuff what stored in CRM system.
My example: I have database with 50k contacts and 180k related comments in old CRM with no possibility for automatical/manual cleaning. Now I plan to migrate to Yeti. This is very difficult to clean some data manually.  If I find possibility to clean data by some conditions after import this will be great deal!
