### ISSUE TITLE
Image thumbnail on documents

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3406]
Can i add image thumbnail  to all image documents?

like img scr

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/ea2687aeb2870c310feee79da56677001865e016

**Comment by konadrian** [comment]
3946dc76f0751c90fb8445bd874c4875a556a1e7

**Comment by immhub** [comment]
TKS konadrian, but the ideea was if the file is an img file, to show it as an img scr :)

**Comment by paula-w** [comment]
We're not planning to add thumbnails, we added info about extensions in the form of icons.
