### ISSUE TITLE
You don't have permission to access

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3409]
/modules/OSSMail/roundcube/&_task=mail&_action=compose&_extwin=1&_composeKey=185f3a9b546856298bd38ac221a8a0cf on this server. Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Tested on gitdeveloper.yetiforce.com, version:  3.1.1023
Instructions:
1. Go to Quote, preview any Quote record.
2. Select Export to PDF icon. A window will open.
3. Click green arrow, a tab will open called "Send by mail". Click it.
4. An error shows up immediately. It's shown in screenshot number 2.

[PL]
Testowane na gitdeveloper.yetiforce.com, wersja:  3.1.1023
Instrukcja:
1. Przejdź do Oferty. Zrób podgląd dowolnego rekordu Oferty.
2. Wybierz ikonkę Eksportuj do PDF. Otworzy się okno.
3. Kliknij na zieloną strzałkę. Rozwinie się zakładka z nazwą „ Wyślij pocztą”. Kliknij na nią.
4. Od razu pojawia się błąd. Został przedstawiony na zrzucie ekranu rys. nr 2.
![103 wykonanie github](https://cloud.githubusercontent.com/assets/11139594/17925933/411e2120-69ef-11e6-8cb7-c02ecbfbcd9e.png)
![103 blad](https://cloud.githubusercontent.com/assets/11139594/17925936/487da670-69ef-11e6-95e1-13ca7042b29c.png)

**Comment by mariuszkrzaczkowski** [comment]
Błąd nie istnieje w najnowszej wersji.
