### ISSUE TITLE
 Setup or bug in the menu?

### ISSUE THREAD

**Issue by torresnet** [YetiForceCompany/YetiForceCRM#3414]
the side menu , it appeared full , but now appears only the icon of the "dashboard " .. is a bug or configuration ? .. If configuration, how to do it

**Comment by paula-w** [comment]
Take a look at https://yetiforce.com/en/github/issues/126-issues.html and provide us with the missing info.  Sticking to the template we created for new issues is also a good idea.

**Comment by torresnet** [comment]
Sorry , my language is Portuguese ... I am using a translator to communicate with you .
But I think the print screens should help with my doubts .

my screen
http://i.imgur.com/4xRJC5M.png 

screen a demo version
http://i.imgur.com/AkvheNx.png

I want my menu becomes equal to demo version.
Therefore I questioned whether it was a bug or configuration

tks

**Comment by bpabiszczak** [comment]
Please check this tool: https://gitdeveloper.yetiforce.com/index.php?module=Menu&view=Index&parent=Settings&block=2&fieldid=40

**Comment by torresnet** [comment]
bpabiszczak, look

My screen
http://i.imgur.com/aAdrErV.png

Demo screen
http://i.imgur.com/SagAPkX.png

tks

**Comment by paula-w** [comment]
There is a tab "Default menu" in the menu, and if a role has no added menu positions, then the system will take menu from this tab. If you remove everything from the "Default Menu" tab, then there will be no menu at all. Then you can design a new menu, or copy it manually at the database level.
Look at how our menu is built in GitDeveloper version. There is the access to panel there, and your configuration should be similar. 

Please switch the system language to English when you take screenshots, it will be easier for us to understand what you mean and what your settings are.

**Comment by torresnet** [comment]
the "Default Menu" is ok , appears all the menu items , but does not go to the others.
The copy button menu does not appear , as shown in the image .. can not copy the menu ...
The version I use is stable 3.1.0 and the version of the demo is another ... " 1.3.1057 " .. is that if I update the version of the copy button menu will appear ?

**Comment by vovpff** [comment]
@torresnet looks like some errors at installation.

**Comment by torresnet** [comment]
So how to solve ??? I think re-installing , maintaining the same database will not solve ..

**Comment by paula-w** [comment]
Yes, because it is a new option, but you have to wait for version 3.2. Second of all, the option only makes copying easier, because you can add everything manually from the panel.

**Comment by torresnet** [comment]
ok , but manually add is a lot of work ... which is the date for the release of version 3.2 ?

**Comment by bpabiszczak** [comment]
2016-08-29
