### ISSUE TITLE
Error while adding Time control. 

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3416]
Tested on gitdeveloper.yetiforce.com, version:  3.1.1045
Instructions:
1. Go to Human resources. Select Employees. Preview Employee's record.
2. Select related module Time control. Click "add record"
3. Enter values and save.
4. See the screen shot for error message.

[PL]
Błąd podczas dodawania Czasu pracy

Testowane na gitdeveloper.yetiforce.com, wersja: 3.1.1045
Instrukcje:
1. Przejdź do Kadry. Wybierz zakładkę Pracownicy. Zrób podgląd rekordu Pracownika.
2. Wybierz moduł powiązany Czas pracy. Kliknij na przycisk "Dodaj rekord".
3. Wprowadź wartości i zapisz.
4. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu. 
![113](https://cloud.githubusercontent.com/assets/11139594/17962720/66712bd4-6ab2-11e6-86ed-df29cf232294.png)

**Comment by TomaszQr** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/0346dbc2ac14205adb712da0974c5077d7ee4d55
