### ISSUE TITLE
Error occurs while editing Date of receiving

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3417]
Tested on gitdeveloper.yetiforce.com, version:   3.1.1050
Instructions:
1. Go to Secretary, select tab Letters incoming. Preview this record
2. Click on a related module Details. In full edit view change the date - click on any days in the calendar
3. The error pops up immediately
4. See the screen shot for error message.

[PL]
Błąd występuje podczas edycji Daty przyjęcia
Testowane na gitdeveloper.yetiforce.com, wersja:  3.1.1050
Instrukcje:
1. Przejdź do Sekretariat. Wybierz zakładkę Listy przychodzące. Zrób podgląd tego rekord.
2. Kliknij na moduł powiązany Szczegóły. Najedź na ikonkę szybkiej edycji. Zmień datę - (klikaj na dowolne dni w kalendarzu).
3. Od razu pokazuje się błąd.
4. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![115](https://cloud.githubusercontent.com/assets/11139594/17964511/ded5be08-6ab9-11e6-8f93-1eb8a7b9caf8.png)

**Comment by TomaszQr** [comment]
Error doesn't exist in current version
