### ISSUE TITLE
Error while editing field - Response time

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3418]
Tested on gitdeveloper.yetiforce.com, version:  3.1.1051
Instructions:
1. Go to Secretary, select tab Letters incoming. Preview this record
2. Click on a related module Details. Go to quick edition - field Response time - click on any days in the calendar
3. The error pops up immediately
4. See the screen shot for error message.

[PL]
Błąd podczas edycji pola Termin odpowiedzi
Testowane na gitdeveloper.yetiforce.com, wersja:  3.1.1051
Instrukcje:
1. Przejdź do Sekretariat. Wybierz zakładkę Listy przychodzące. Zrób podgląd tego rekord.
2. Kliknij na moduł powiązany Szczegóły. Najedź na ikonkę szybkiej edycji – pole Termin odpowiedzi. Zmień datę - (klikaj na dowolne dni w kalendarzu).
3. Od razu pokazuje się błąd.
4. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![116](https://cloud.githubusercontent.com/assets/11139594/17965357/7288dc50-6abc-11e6-966a-0027b1400171.png)

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/d4115858d9344ff0f7bbe45c4b841e8dfbf8ae90, https://github.com/YetiForceCompany/YetiForceCRM/commit/523d0d3b50e8c3ed5ca4f3a361451b7231c9bd8d
