### ISSUE TITLE
[Question:] How delete a value in Product Category Tree?

### ISSUE THREAD

**Issue by rage1985** [YetiForceCompany/YetiForceCRM#3419]
Does anybody know how to delete a value in the Product Category Tree?

I want to start from scratch here and there are somewhat IT related entrys/values like Hardware Software.

**Comment by kpaulaha** [comment]
Standard modules >  Fields – Folders

**Comment by rage1985** [comment]
I found it. But the Module lacks basic functionality in my opinion. There is no way to modify or delete the template records. I had to write a Sql Command to get rid of the existing Template Records.

At least it would be nice to have unique ID´s on the records for easier targeting. What would be even better is standard CRUD. 

Best regards and keep up the good work!

**Comment by vovpff** [comment]
@rage1985 just right click on tree item:
![image](https://cloud.githubusercontent.com/assets/8545791/17970403/1f4ccf1a-6adf-11e6-861d-344aa557b17b.png)
dev.3.1.1051

**Comment by rage1985** [comment]
-.- you must be kidding... Thank you so much! XD

**Comment by rage1985** [comment]
Woah, you Guys even build the Bootstrap Glyphicon Library into this thing... now i am impressed...

**Comment by manwenick** [comment]
Hello everyone, 

I have similar issue:

I added new categories --> no problem.
I tried to delete IT categories, because of no need. It doesn't work. Notification popup: You cannot delete parent item. 

How to do it?

I use admin Panel in english, to employees should use it in russian. 
I can't find the strings to translate the added categories under System Tools --> Language Management. 
Is it possible to translate new added categories in different languages?

System: YetiForce 4.3.0

**Comment by vovpff** [comment]
@manwenick maybe you need to remove folded categories before deleting parent?

**Comment by manwenick** [comment]
@vovpff yes, I did it first. Folded categories cannot be deleted before the are assigned to another category. I did it to all of them. Till I had a parent category. After this I tried to delete this parent category, but there was no question to assign it another category, but how I discriped above, only a notification: You cannot delete parent item.

**Comment by vovpff** [comment]
@manwenick Try here https://gitdeveloper.yetiforce.com/index.php?module=TreesManager&parent=Settings&view=Edit&record=2

Works well but some GUI artefacts

![image](https://user-images.githubusercontent.com/8545791/43327832-27cdb8a2-91c5-11e8-8d67-30a7c131f585.png)

@mariuszkrzaczkowski What is purpose of play button in pop up notifications?

![image](https://user-images.githubusercontent.com/8545791/43327895-4fc1ec0c-91c5-11e8-9b76-235494cab10d.png)
