### ISSUE TITLE
[PL] mała pomoc - Pdf - ProducttableNew - label from fields in block 2 

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#3420]
Witam wszystkich ... Mam problem z przebudowaniem widoku tabeli na wydruku - własny moduł.
W jaki sposób mogę pobrać "label" tabeli - przeniesionej do bloku 2.

``

	foreach ($inventoryRows as $key => &$inventoryRow) {
				$html .= '<tr>';
				foreach ($fields[1] as $field) {
					if ($field->getName() == 'ItemNumber') {
						$html .= '<td><strong>'.$inventoryRow['seq'].'</strong></td>';
					} else if ($field->get('columnname') == 'ean') {
						$code = $inventoryRow[$field->get('columnname')];
						$html .= '<td><barcode code="' . $code . '" type="EAN13" size="0.5" height="0.5" class="barcode" /></td>';
					} else if ($field->isVisible($inventoryRows)) {
						$itemValue = $inventoryRow[$field->get('columnname')];
						$html .= '<td class="' . (in_array($field->getName(), $fieldsTextAlignRight) ? 'textAlignRight ' : '') . 'tBorder">';
						switch ($field->getTemplateName('DetailView', $module)) {
							case 'DetailViewName.tpl':
								$html .= '<strong>' . $field->getDisplayValue($itemValue) . '</strong>';
								foreach ($fields[2] as $commentKey => $value) {
									$COMMENT_FIELD = $fields[2][$commentKey];
									$html .= '<br>LABEL - FIELDS FROM BLOCK 2<br/>' . $COMMENT_FIELD->getDisplayValue($inventoryRow[$COMMENT_FIELD->get('columnname')]);
								}
								break;

							case 'DetailViewBase.tpl':
								$html .= $field->getDisplayValue($itemValue);
								break;
						}
						$html .= '</td>';
					}
				}
				$html .= '</tr>';
			}

``
Bardzo proszę o pomoc. Niestety za dużo pól własnych aby móc je zmieścić w standardowym widoku.

**Comment by dextras** [comment]
Co masz na myśli pisząc  

> "label" tabeli - przeniesionej do bloku 2.

?

**Comment by bpabiszczak** [comment]
Takiego wsparcia udzielamy odpłatnie... może ktoś ze społeczności się tym zajmie.

**Comment by zimart** [comment]
Na to liczyłem... pozostało próbować - poradziłem sobie :)

**Comment by bpabiszczak** [comment]
Skoro sobie poradziłeś, to napisz jak i podaj rozwiązanie... może komuś się przyda. Po drugie skoro sobie poradziłeś to zamknij zgłoszenie.

**Comment by zimart** [comment]
Taki miałem zamiar.... :) Nie zdążyłem ...
U mnie wyglada to tak..
` ($field->getTemplateName('DetailView', $module)) {
							case 'DetailViewName.tpl':
							$html .= '<span style="text-align:center;font-weight:bold;">' . $field->getDisplayValue($itemValue) . '</span><br><br></font>';
							foreach ($fields[2] as $commentKey => $value) {
						    $COMMENT_FIELD = $fields[2][$commentKey];
							if ($field->bezrabatu($commentKey)) {
					        $html .= '</strong><span style="font-size:10px;">' . vtranslate($COMMENT_FIELD->get('label'), $module) . '</span>' . $field->getDisplayValue($columnname) . '</span>';
				            }					
				            $html .= '<span style=padding-left:3px;padding-right:3px>  :  </span><span style="font-size:10px;"><strong>' . $COMMENT_FIELD->getDisplayValue($inventoryRow[$COMMENT_FIELD->get('columnname')]);
				            $html .= '<br>';
`
