### ISSUE TITLE
[Question] Multi tree

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3422]
This explanation request

Some time ago I found next field at products module
![image](https://cloud.githubusercontent.com/assets/8545791/17982106/27753d46-6b0f-11e6-997f-2f62bb7054a5.png)

Field name is category_multipicklist. If I understand correct this fild must has functionality what I requested at #1925.

There is no possibility to change tree values and test this fild. How to test it? How this field works?

**Comment by serbiaserbia** [comment]
If it is multipick for tree, it could be great feature.

**Comment by paula-w** [comment]
The field is used for the POS application, it's related to the categories in the Sales Orders module.

**Comment by vovpff** [comment]
@paula-w @bpabiszczak is it possible to add field with multi tree fuctionality to another or custom module?

**Comment by paula-w** [comment]
You can add this field in any module, but there's no option to add it from the panel, for now it can only be added at vtlib level.

**Comment by vovpff** [comment]
@paula-w thanks a lot for explanation
