### ISSUE TITLE
[Question] Tree records list view

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3423]
dev.3.1.1066.
There are list view type called "Tree records" for products
![image](https://cloud.githubusercontent.com/assets/8545791/17982480/9ee5d1a0-6b10-11e6-95e0-e3813e469492.png)
I added some products with differents values for category tree but at "tree records" no record appears at general part of screen.
![image](https://cloud.githubusercontent.com/assets/8545791/17982534/e00aa052-6b10-11e6-84c4-2ec05e7bbf84.png)
![image](https://cloud.githubusercontent.com/assets/8545791/17982549/ef7e394a-6b10-11e6-8129-8c6f599939c8.png)
How to check this feature?

**Comment by vovpff** [comment]
@TomaszQr at some version there are appears list of product but user hasn't any available actions with this records list.

**Comment by bpabiszczak** [comment]
![products_tree](https://cloud.githubusercontent.com/assets/10197525/18234606/7c8ec55a-730b-11e6-85b4-3c9fdb3b76a8.gif)

**Comment by vovpff** [comment]
@bpabiszczak thx for explanation!
