### ISSUE TITLE
[Question] What is on picture at Main YetifocreCRM github page

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3424]
There are picture on main page:
![image](https://cloud.githubusercontent.com/assets/8545791/17982784/24fbb1c8-6b12-11e6-8723-4542c39bf0ce.png)
What is it?
![image](https://cloud.githubusercontent.com/assets/8545791/17982766/119624a6-6b12-11e6-8ceb-bd7ae61f104a.png)

**Comment by bpabiszczak** [comment]
![ulubione](https://cloud.githubusercontent.com/assets/10197525/17983050/f264d76e-6b0a-11e6-9549-94a6044d3a85.png)

**Comment by vovpff** [comment]
@bpabiszczak Thx a lot for explanation. I never tryed this in a past
