### ISSUE TITLE
Bug when adding Document to Account

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3431]
Tested on gitdeveloper.yetiforce.com, version: 3.1.1073 

Instructions: 
1. Go to Accounts and Contacts. Select Accounts. Preview a record.
2. Go to a related module - Documents.
3. Click Select record.
4. Attach a previously created Document (png).
5. See the screen shot for error message.

[PL]
Błąd pojawia się po dodaniu Dokumentu w Kontrahencie.
Testowane na gitdeveloper.yetiforce.com, wersja: 3.1.1073 

Instrukcje:
1. Przejdź do Firmy i Kontakty. Wybierz zakładkę Kontrahenci. Zrób podgląd tego rekordu.
2. Przejdź do modułu powiązanego Dokumenty.
3. Kliknij na przycisk Wybierz rekord.
4. Załącz utworzony wcześniej Dokument (png).
5. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![125](https://cloud.githubusercontent.com/assets/11139594/18003104/0187f8f8-6b8c-11e6-95e7-02b6ccc5ef4d.png)
![125 b](https://cloud.githubusercontent.com/assets/11139594/18003109/06a2f374-6b8c-11e6-9970-d31a86f12ddc.png)

**Comment by konadrian** [comment]
Fixedby 5e3aa024d6c498c5596a4a38c7cfcf06960e1091
