### ISSUE TITLE
[BUG] Muli tree manual selection

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3432]
There are no possibility to select more than one category by category name typing

![milti tree bug 1](https://cloud.githubusercontent.com/assets/8545791/18004372/27b2ae0a-6b9c-11e6-80fa-0fc9d30e825d.gif)

**Comment by vovpff** [comment]
@bpabiszczak you are not right. #3501 isn't same issue.

**Comment by konadrian** [comment]
This field was deleted a while ago, right now we don't support a field that allows you to select more than one category

**Comment by vovpff** [comment]
@konadrian ok. No problem but this feature was very useful
