### ISSUE TITLE
Problem po instalacji

### ISSUE THREAD

**Issue by ScAArY** [YetiForceCompany/YetiForceCRM#3433]
Po zainstalowaniu odpala się ekran logowania ale po zalogowaniu wyskakuje mi błąd:

Strona mojAdres.pl nie działa

Serwer mojAdres.pl nie może teraz obsłużyć tego żądania.

Co moze byc przyczyną? Macie jakieś sugestie??

**Comment by bpabiszczak** [comment]
Twój serwer postanowił, że Ci strony nie pokaże i tylko on wie dlaczego. Dlatego trzeba zerknąć w logi serwera i odczytać co ma nam do powiedzenia. Najpierw zacząłbym szukać w logach www a dopiero potem w logach yetiforce bo przypuszczam, że zainstalowałeś to na jakimś hostingu mocno limitowanym.

**Comment by ScAArY** [comment]
Już wszystko dobrze, błąd po stronie konfiguracji serwera.
