### ISSUE TITLE
Mail Scanner - No Folder Configuration

### ISSUE THREAD

**Issue by mariopmoura** [YetiForceCompany/YetiForceCRM#3434]
HI

I'm still having problems with Mail - Scanner. I did all the roudmail configuration and everything seems to be ok because I can access to email. However we lost some icons like a creat a new lead from an email.
I believe the problem still be in mail scanner configuration. I still have the error No Folder Configuration. We cant associate emails to leads

I already read all the documentation.

<img width="1280" alt="captura de ecra 2016-08-28 as 01 25 01" src="https://cloud.githubusercontent.com/assets/21124117/18030831/11a71f1e-6cbf-11e6-832a-f4a2906a33d2.png">

**Comment by bpabiszczak** [comment]
The first action must always be "Create email message"!

**Comment by mariopmoura** [comment]
What you mean by "create email message"? When we creat the icons "lead" "account" are ok. That's not the problem. 

--
Mario Moura

No dia 28/08/2016, às 01:46, Błażej Pabiszczak <notifications@github.com> escreveu:

**Comment by bpabiszczak** [comment]
![github1](https://cloud.githubusercontent.com/assets/10197525/18033503/5350f3e6-6d27-11e6-8d03-d62692a7404d.png)

**Comment by KarenNL** [comment]
I Have the same issue with Yetiforce folders and I can't see the blue balk of companies/contacts....

**Comment by ratedtye** [comment]
I seem to be having the same issues: "No Folder Configeration" although I can clearly see my folders and have mapped them out. in the indentity details it says: "Folder configuration: --None--"

**Comment by mariuszkrzaczkowski** [comment]
> No Folder Configeration
This has been fixed in the developer version

@mariopmoura 
Is there a quick creation lead in the records list view?
Did not you write what version of the system etc. did you check the logs?
