### ISSUE TITLE
No description info in RSS widget added to Dashboard.

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3438]
Tested on gitdeveloper.yetiforce.com, version: 3.1.1087
Instructions:
1. Add Rss channel from the admin panel. 
2. Go to Home page. Add Rss widget to Dashboard.
3. See the screen shot for error message.

[PL]
Brak informacji opisowych w dodanych widżetach RSS na pulpicie
Testowane na gitdeveloper.yetiforce.com, wersja: 3.1.1087
Instrukcje:
1. Dodaj kanał Rss od strony administratora.
2. Przejdź na Stronę główną. Dodaj widżet kanał Rss na pulpicie.
3. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![128](https://cloud.githubusercontent.com/assets/11139594/18049476/d3196b78-6de8-11e6-8845-423446dd0f3c.png)

**Comment by rskrzypczak** [comment]
Nie spostrzegłem opisanego błędu. Prawdopodobnie dodany kanał rss był uszkodzony bądź pusty.

**Comment by bpabiszczak** [comment]
Niech Ci poda kanały które wklejała... bo część działa a część nie, więc przypuszczam, że to problem z parsowaniem.
