### ISSUE TITLE
[BUG] Sharing privileges

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#3439]
There are 3 user
Each has its own role
The module has the right Privat (Software configuration> Permissions> Module access)
But custom rules are not appointed
Watch a video
![error_sharing](https://cloud.githubusercontent.com/assets/17310158/18050184/b64b9680-6df5-11e6-8f3f-01499a422162.gif)

**Comment by vovpff** [comment]
@iRainSystem I checked this too with new Logistic user. I can't see any records what assigned for different roles or different users with same role.
This is new rule
![image](https://cloud.githubusercontent.com/assets/8545791/18051041/df6bc260-6dfa-11e6-9987-a73c271ba0f0.png)
This from demo user
![image](https://cloud.githubusercontent.com/assets/8545791/18051070/011da6c6-6dfb-11e6-8880-4854a08d4808.png)
This is from log2 user
![image](https://cloud.githubusercontent.com/assets/8545791/18051085/1f52112c-6dfb-11e6-91ab-7332c88566a3.png)

**Comment by vovpff** [comment]
@iRainSystem for this rule:
![image](https://cloud.githubusercontent.com/assets/8545791/18051133/4ca5da3c-6dfb-11e6-87ea-354f142566cb.png)
I can see all record in list 
![image](https://cloud.githubusercontent.com/assets/8545791/18051159/6f6ea22e-6dfb-11e6-950f-a070c63ec80b.png)
but detailed view available for only record what assigned to log2 user. All another records:
![image](https://cloud.githubusercontent.com/assets/8545791/18051195/b053b4b4-6dfb-11e6-93c6-6c48adaa556b.png)
```
#0 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/include/main/WebUI.php(70): Vtiger_Detail_View->checkPermission(Object(Vtiger_Request))
#1 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/include/main/WebUI.php(205): Vtiger_WebUI->triggerCheckPermission(Object(Vtiger_Detail_View), Object(Vtiger_Request))
#2 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/index.php(24): Vtiger_WebUI->process(Object(Vtiger_Request))
#3 {main}
```

**Comment by iRainSystem** [comment]
@vovpff 
This is a bug? Or need to use the other buttons? what kind?

**Comment by vovpff** [comment]
@iRainSystem I think previlegues system are broken. I think fresh installation of system needed to check this but but no free time for this.

**Comment by iRainSystem** [comment]
@vovpff 
Well I'll try to check it local host. And write results.

**Comment by vovpff** [comment]
@iRainSystem i checked at dev. 3.1.1089. The same situation. If you wanna try one more time: passwords for users qwe1 and qwe2 is 123456Aa

**Comment by iRainSystem** [comment]
@vovpff 
i checked at 3.2 version installed on the local host. The same situation. :( I'm sad. it's bag. 
all as in the first message.

**Comment by nic86** [comment]
check user_privileges/shared_privileges files 
restart web service for refresh cache

**Comment by iRainSystem** [comment]
@nic86 
checked, does not work
I did a clean install from last version in develop branch (v3.2.0)

**Comment by iRainSystem** [comment]
@nic86 
how i see file sharing_privilegesX.php - correct
....
`$Vendors_share_read_permission=['ROLE'=>['H14'=>[6,],],'GROUP'=>[6=>[0=>6,],]];
$Vendors_share_write_permission=['ROLE'=>['H14'=>[6,],],'GROUP'=>[6=>[0=>6,],]];`

**Comment by nic86** [comment]
then you need to analyze log php:
set  'LOG4PHP_DEBUG' => true, in config/debug.php
restart webservice
navigate to the page that not show the shared record
and analyze cache/logs/system.log

**Comment by iRainSystem** [comment]
I have file, but I don't understand, no request for tables: vtiger_datashare_rs2rs  vtiger_datashare_role2role vtiger_datashare_us2us 
it's all right?
I can send a log.
after install my branch this: [3.2 clean install branch](https://github.com/iRainSystem/YetiForceCRM/tree/install)
[system.log.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/442787/system.log.zip)

**Comment by nic86** [comment]
this is the query that generate list view:

SELECT vtiger_vendor.vendorname, vtiger_vendor.phone, vtiger_vendor.email, vtiger_vendor.category, vtiger_crmentity.smownerid, vtiger_vendor.vendorid FROM vtiger_vendor  INNER JOIN vtiger_crmentity ON vtiger_vendor.vendorid = vtiger_crmentity.crmid WHERE vtiger_crmentity.deleted=0 AND (( vtiger_crmentity.smownerid = '5' OR vtiger_crmentity.smownerid IN (SELECT vtiger_user2role.userid AS userid FROM vtiger_user2role INNER JOIN vtiger_users ON vtiger_users.id=vtiger_user2role.userid INNER JOIN vtiger_role ON vtiger_role.roleid=vtiger_user2role.roleid WHERE vtiger_role.parentrole like 'H1::H2::H10::%')) OR (vtiger_crmentity.crmid IN (SELECT DISTINCT crmid FROM **u_yf_crmentity_showners** WHERE userid IN (5)))) LIMIT 0,21

in this table should be the users with shared privileges: u_yf_crmentity_showners

the class should write to that table is located in this file : modules/Users/models/Privileges.php

you should do the debugging ( activating display_errors in .htacces ) using the var_dump followed by exit within the code or even better with xdebug

**Comment by nic86** [comment]
sorry this is the shared owner not shared privileges.
shared privileges are in include/CRMEntity.php
function getUserAccessConditionsQuery

**Comment by iRainSystem** [comment]
@nic86 
You are the BEST!!!!
Look here:
----------- 
if (isset($sharingPrivileges[$moduleName])) {
				$sharingPrivilegesModule = $sharingPrivileges[$moduleName];

must be
--------
if (isset($sharingPrivileges['permission'][$moduleName])) {
				$sharingPrivilegesModule = $sharingPrivileges['permission'][$moduleName];

%)))))

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/a3cd28331fc328a547c3acde3f88512662db6a66
