### ISSUE TITLE
[QUESTION] Is the Update Package to 3.2.0 is compatible with 3.1.629?

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3441]
Congratulations for the release of 3.2.0!

Can I launch my upgrade from 3.1.629?
Thank's !

**Comment by rskrzypczak** [comment]
Probably YES :)

**Comment by Raggazzoo** [comment]
Yes! But quick search doesn't work, is it a cron issue?

**Comment by bpabiszczak** [comment]
quick search work only if you run CRON!

**Comment by Raggazzoo** [comment]
Okay! Thank's! What is the way to run it? Manually add a line on the crontab file?
