### ISSUE TITLE
YetiForce 3.2.0 [comments]

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#3445]
We welcome your comments and suggestions.
More info: https://github.com/YetiForceCompany/YetiForceCRM/issues/3444

**Comment by skramanzia** [comment]
Great Job!!.. the update packaged, work perfect!!.

 Realy is the best crm ever

**Comment by PercyP** [comment]
I love it!
After years of Vtiger (which I loved, but not as much) I am now an avid fan of Yetiforce as it has overcome so many of the niggles I had with Vtiger. I also love Yetiforce's approach to development and the rapidness of it. OK, I know their milestone deadlines kept going back, but that was necessary to ensure they could iron out as many of the bugs as possible. I love its clean, sophisticated design, its feel, it is so intuitive.

I am excited about the future of Yetiforce, and looking forward to their store and new modules that we can purchase to help them grow. 

In the meantime, everyone who uses it for free should consider supporting them with a small donation - every little helps, and it can be a great motivation (at least I believe that). 

I have also dabbled with Salesforce which I think is awful - this CRM is definitely the best I have experienced so far. Thank you! :)

**Comment by PercyP** [comment]
FUTURE FEATURE REQUESTS/SUGGESTIONS:

These are just some ideas.

1. Themes we can purchase for Yetiforce CRM and matching themes for the Customer Portal
2. Integration with Virtuemart
3. Integration with a Newsletter mailing solution - i.e. ACYMailing is brilliant (see www.acyba.com) or if possible, features added to yetiforce own mailing solution - possibly a new module we could purchase?
3. A job board module (that can be integrated with a website?)

Kind regards

**Comment by iRainSystem** [comment]
you are the best!!! congratulation!!!

p.s. waiting when will work on php7 ;)

**Comment by bpabiszczak** [comment]
http://www.softaculous.com/news/scripts/updated-yetiforce-to-3-2-0-10259.html

**Comment by serbiaserbia** [comment]
The whole system is much faster.
My subjective feeling about 30% - but really - I am sure it is not Placebo effect :-)

Regards for ALL Team!!!!!!!!
