### ISSUE TITLE
PDF Files are not exporting 

### ISSUE THREAD

**Issue by Denz55** [YetiForceCompany/YetiForceCRM#3446]
I am attemting to export my quotes to pdf can someone assist.​Generated by YetiforceCRM ver. 3.1.0PHP: 5.6.21Server configuration errors:error_reporting: E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_USER_ERROR | E_USER_WARNING | E_USER_NOTICE | E_STRICToutput_buffering: Offmax_execution_time: 30max_input_time: 60log_errors: Onupload_max_filesize: 2.0 MBmax_input_vars: 1000session.gc_divisor: 100Library errors:ldap_connect

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by Denz55** [comment]
When attempting to export a document to PDF it gives me an error.

Error - mPDF requires mb_string functions. Ensure that PHP is compiled with php_mbstring.dll enabled.

**Comment by vovpff** [comment]
@Denz55 let's check are mbstring.dll enabled at your server php.ini
