### ISSUE TITLE
Częstotliwość wywołania  "MailScannerAction" powinna być większa przynajmniej dwa razy od czestotliwości wywołania zadania "MailScannerVerification"[PL]

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#3447]
Poproszę o wskazówki w jaki sposób ustawić crona

#### Your Environment

* YetiForce Version used:3.2
* Browser name and version:Firefox
* Environment name and version:
* Operating System and version:Linux

**Comment by bpabiszczak** [comment]
a jakie konkretnie jest pytanie...

**Comment by hipernet** [comment]
jak ustawic crona nie działa

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/dokumentacja-administratora/panel/cron/149-uruchamianie-crona.html

**Comment by hipernet** [comment]
dzięki  może sie uda uruchomić

**Comment by bpabiszczak** [comment]
Gdy ktoś zna swoje środowisko [serwer, oprogramowanie i YetiForce] to ustawienie takiego crona zajmuje całe 30 sekund. Praktyka czyni mistrza.

**Comment by hipernet** [comment]
problem był w ustawieniach serwera poszło
