### ISSUE TITLE
Autouzepełnianie adresów w roundcube

### ISSUE THREAD

**Issue by r0bertk** [YetiForceCompany/YetiForceCRM#3449]
Witam, 
jak mogę uruchomić autouzupełnianie adresów w poczcie roundcube? Sprawdzałem na stronie demo i podpowiada się tylko jeden adres mianowicei Tom Kowalski inne adresy również się nie podpowiadają.
Bardzo proszę o wskazówki jak mam ustawić system, aby działało autouzupełnianie adresów.

Pozdrawiam Robert

**Comment by bpabiszczak** [comment]
Adresy są uzupełniane na podstawie danych wprowadzonych w CRM i włączonego CRON-a. Gdy dodasz kilka kontaktów i masz włączonego cron-a system zacznie sam uzupełniać adresy.

**Comment by r0bertk** [comment]
Mam włączonego Crona, przynajmniej tak mi się wydaje. Ale na stronie demo jak dodłem nowy kontakt to system też nie podpowiadał adresów chyba że to działa po jakimś czasie?. jak mogę sprawdzić czy mam uruchomionego crona?

**Comment by bpabiszczak** [comment]
Tu masz workflow za to odpowiedzialny: https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&page=1&view=List&sourceModule=Contacts nazywa się: generuj książkę adresową. 

Tu masz CRON i informacje czy działa: https://gitdeveloper.yetiforce.com/index.php?module=CronTasks&parent=Settings&view=List&block=15&fieldid=26

a nawet jeżeli z jakiegoś powodu coś nie działa, to należy przeczytać ten artykuł: https://yetiforce.com/pl/github/issues/125-issues.html i sprawdzić co pokazują logi i czy na pewno nie działa na gitdeveloper.

**Comment by r0bertk** [comment]
Ok dziękuję za linki

**Comment by bpabiszczak** [comment]
Mi zadziałało na gitdeveloper:
![image](https://cloud.githubusercontent.com/assets/10197525/18069355/e10230b8-6e46-11e6-89d6-cce8c0a39ab5.png)

**Comment by r0bertk** [comment]
Ja na gitdeveloper dodałem swój kontakt i się nie pojawia nie wiem co robię żle?

**Comment by r0bertk** [comment]
Już się pojawiłem na gitdeveloper, ok muszę coś z cronem zrobić bo widzę że chyba jednak u mnie nie działa

**Comment by r0bertk** [comment]
Ok już mi wszystko działa. Jednak Cron był winien. Dziękuję za wskazówki i pozdrawiam Robert

**Comment by r0bertk** [comment]
Witam, autouzupełnianie działa mi tylko na jednym koncie mailowym jak dodałem drugi to autouzupełnianie na nim nie działa. Co może być przyczyną?
