### ISSUE TITLE
[bug] Mapping v 3.2.0

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3450]
#### Issue
Mapping not working for non admin users, reported  #3394 and then fixed

#### Actual Behavior

![map2](https://cloud.githubusercontent.com/assets/10330264/18080052/5b22a490-6e9c-11e6-87ef-5f4c367d178a.png)

#### Expected Behavior
![map1](https://cloud.githubusercontent.com/assets/10330264/18080059/65220198-6e9c-11e6-8d4e-aefa4d48aacf.png)

#### How to trigger the error

1. Open e.g. Storage Transfer Dispatched Notes with a Non Admin user

#### Your Environment
* YetiForce Version used: 3.2
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rskrzypczak** [comment]
It works fine for me. You have to have permissions for actions in profiles, and in the mapping panel record itself.
![image](https://cloud.githubusercontent.com/assets/10221999/18080773/206ccf6a-6e97-11e6-8e13-642f4ee9c010.png)
![image](https://cloud.githubusercontent.com/assets/10221999/18080804/433d79ae-6e97-11e6-901c-0e9ba7afd5a2.png)

**Comment by kpaulaha** [comment]
Damn, you are so right, thanks. One question, how do I add this privileges in profiles to a custom module, if there is a mapping made from that to an other module. There are only Import and Export although the user/role has permissions for the mapping.

**Comment by kpaulaha** [comment]
I got it working, great.

**Comment by rskrzypczak** [comment]
What matters here, are the actions automatically added while creating a new module in CRM. 
If you updated the system via the update package, then these actions were added as well, but without any permissions, which you can change.

**Comment by kpaulaha** [comment]
I had in 3.1. a few custom modules with mapping between, after updating to 3.2 the modules got the mapping permission selection in profiles, but the users did not get the mapping permissions. So I had to delete the custom modules, add the new actions list to the manifest and re-install the modules, now it works.
