### ISSUE TITLE
[Question] Where is activate cron task

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#3451]
I added new cron task
CRON - add task
I received a new record in the table vtiger_cron_task
ok, but CRON not worked, where enable it?
UPD: file and file path valid

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/administrator-documentation/panel/cron/150-enable-cron.html

**Comment by iRainSystem** [comment]
@bpabiszczak 
Thank you!
