### ISSUE TITLE
[BUG] UpdatePackage 3.1.0 to 3.2.0

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3456]
after update YetiForce CRM 3.1.44 to 3.2.0 by using UpdatePackage 3.1.0_to_3.2.0 search system of crm not working .
update was successful and without any error or warning .

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3348 https://github.com/YetiForceCompany/YetiForceCRM/issues/3441

**Comment by vahid-jml** [comment]
thanks a lot @rskrzypczak .
