### ISSUE TITLE
Unable to create Lead/Organisation on 3.2.6

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3457]
I upgrade my 3.1.629 to 3.2.0 without problem, a lot of things are solved but I still can't create a Lead or an Organisation.

After validate the form I got "HTTP ERROR 500".

In #3404 @paula-w talks about an additional package for people whose version is higher than 3.1.247.
When do you think It could be available?

I got a lot of pressure in my company for the features of the 3.2!

Thank's!

**Comment by Raggazzoo** [comment]
No one have a clue?

**Comment by Raggazzoo** [comment]
There is the console output on dashboard
![image](https://cloud.githubusercontent.com/assets/1357727/18161743/8c3a52ba-7033-11e6-8b58-aac16010894e.png)

And  after validation of the creation form
![image](https://cloud.githubusercontent.com/assets/1357727/18162697/c571fb10-7037-11e6-9014-84af80b0e623.png)

**Comment by nic86** [comment]
active log php:
set 'LOG4PHP_DEBUG' => true, in config/debug.php
restart webservice
navigate to the page that not show the shared record
and analyze cache/logs/system.log

the error also appears as an administrator?
the problem may be in the files in user_privileges folder

**Comment by Raggazzoo** [comment]
I activated apache log display
`Fatal error: Call to a member function rowCount() on boolean in /var/www/yetiforce/include/database/PearDatabase.php on line 446`

There is the file cache/logs/system.log
[https://owncloud.apexenergies.fr/index.php/s/7GSyMIENmrzKlF1](url)

The problem is also here in administrator, I will check user_privileges thank's!

**Comment by Raggazzoo** [comment]
I don't see the value 0(0=>0) on my fisrt user
![image](https://cloud.githubusercontent.com/assets/1357727/18168536/7c8c1862-7056-11e6-96a5-a3bc77cc034f.png)

My admin got this
![image](https://cloud.githubusercontent.com/assets/1357727/18168559/a735a0f6-7056-11e6-8d1d-f40bffe62e90.png)

**Comment by nic86** [comment]
this is your error:

> Thu Sep  1 14:05:58 2016,314 [27295] ERROR DB - Query Failed: INSERT INTO `u_yf_crmentity_search_label` (`crmid`,`searchlabel`,`setype`) VALUES (?,?,?) | Unknown column 'setype' in 'field list' | SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setype' in 'field list'(/var/www/yetiforce/include/database/PearDatabase.php : 445)
> Thu Sep  1 14:05:58 2016,314 [27295] ERROR DB - 
> #0 LoggerCategory->error('Query Failed: INSERT INTO `u_yf_crmentity_search_label` (`crmid`,`searchlabel`,`setype`) VALUES (?,?,?) | Unknown column 'setype' in 'field list' | SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setype' in 'field list'(/var/www/yetiforce/include/database/PearDatabase.php : 445)') in include/database/PearDatabase.php(175): 
> #1 PearDatabase->log('Query Failed: INSERT INTO `u_yf_crmentity_search_label` (`crmid`,`searchlabel`,`setype`) VALUES (?,?,?) | Unknown column 'setype' in 'field list' | SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setype' in 'field list'','error') in include/database/PearDatabase.php(377): 
> #2 PearDatabase->pquery('INSERT INTO `u_yf_crmentity_search_label` (`crmid`,`searchlabel`,`setype`) VALUES (?,?,?)',[12916,TEST,Leads]) in include/database/PearDatabase.php(445): 
> #3 PearDatabase->insert('u_yf_crmentity_search_label',[12916,TEST,Leads]) in include/Record.php(230): 
> #4 includes\Record->updateLabel('Leads','12916','') in modules/Vtiger/handlers/RecordLabelUpdater.php(20): 
> #5 Vtiger_RecordLabelUpdater_Handler->handleEvent('vtiger.entity.aftersave') in include/events/VTEventTrigger.inc(158): 
> #6 VTEventTrigger->trigger() in include/events/VTEventsManager.inc(125): 
> #7 VTEventsManager->triggerEvent('vtiger.entity.aftersave') in include/CRMEntity.php(849): 
> #8 CRMEntity->save('Leads') in modules/Vtiger/models/Module.php(181): 
> #9 Vtiger_Module_Model->saveRecord() in modules/Vtiger/models/Record.php(294): 
> #10 Vtiger_Record_Model->save() in modules/Vtiger/actions/Save.php(81): 
> #11 Vtiger_Save_Action->saveRecord() in modules/Vtiger/actions/Save.php(58): 
> #12 Vtiger_Save_Action->process() in include/main/WebUI.php(220): 
> #13 Vtiger_WebUI->process() in index.php(25): 


Unknown column 'setype' in table `u_yf_crmentity_search_label

**Comment by nic86** [comment]
$profileactionpermission= [idtab=>[idaction=>(0=true,1=false),ecc],idtab=>[idaction=>(0=true,1=false),ecc],ecc];

**Comment by Raggazzoo** [comment]
I have alter the table structure on my old database ![image](https://cloud.githubusercontent.com/assets/1357727/18172742/0493a09e-7067-11e6-8342-801cf9ce1290.png)
But it don't seems to be enought

**Comment by nic86** [comment]
see the cache/logs/system.log

**Comment by Raggazzoo** [comment]
I done an alter table on vtiger_modentity_num
![image](https://cloud.githubusercontent.com/assets/1357727/18173505/1d2edeb8-706a-11e6-9fb9-7a4e90edeed8.png)
And it seems to be good!!!

**Comment by Raggazzoo** [comment]
I will continue to test all functions to check if everything is OK.

Thank's a lot @nic86 !

**Comment by Raggazzoo** [comment]
I was too optimistic, now I can't open a lead or an organisation...

On system.log I got this
`Thu Sep  1 17:49:25 2016,787 [29650] ERROR System - LBL_NOT_ACCESSIBLE => /var/www/yetiforce/include/main/WebUI.php:73
Thu Sep  1 17:49:25 2016,787 [29650] ERROR System - 
#0 LoggerCategory->error('LBL_NOT_ACCESSIBLE => /var/www/yetiforce/include/main/WebUI.php:73') in include/main/WebUI.php(226): 
#1 Vtiger_WebUI->process() in index.php(25): `

**Comment by Raggazzoo** [comment]
When I click on a lead I got an error 500.

This is my system.log
[system.log](https://owncloud.apexenergies.fr/index.php/s/9OXJl9OPBLO8w5i)

**Comment by nic86** [comment]
the error throw in function:

```
protected function triggerCheckPermission($handler, $request)
        {
                $moduleName = $request->getModule();
                $moduleModel = Vtiger_Module_Model::getInstance($moduleName);

                if (empty($moduleModel)) {
                        throw new \Exception\AppException(vtranslate($moduleName) . ' ' . vtranslate('LBL_HANDLER_NOT_FOUND'));
                }

                $userPrivilegesModel = Users_Privileges_Model::getCurrentUserPrivilegesModel();
                $permission = $userPrivilegesModel->hasModulePermission($moduleModel->getId());

                if ($permission) {
                        $handler->checkPermission($request);
                        return;
                }
                throw new \Exception\NoPermitted('LBL_NOT_ACCESSIBLE');
        }

```

this return false: 
`$permission = $userPrivilegesModel->hasModulePermission($moduleModel->getId());`

**Comment by Raggazzoo** [comment]
Hum... I must wait a database patch no?

**Comment by nic86** [comment]
you've probably had some updating errors in database.
I suggest, if you have a backup, to go back to the previous version, or install a fresh version 3.2 and migrate the database data.

**Comment by Raggazzoo** [comment]
Ok, which tables have I to import on new database?

**Comment by nic86** [comment]
it depends if you have maintained the same id of records (table crmentity) during import to the new database. You may install version 3.1 and overwrite your old database and try a new upgrade to 3.2.
It is not an easy job if you do not know how to do, you can ask for help to the shop of yetiforce.

**Comment by Raggazzoo** [comment]
Do you planned to make the DB patch on the 3.3 release ?

**Comment by bpabiszczak** [comment]
Such errors require developer's analysis. It would be solved within 1-2 hours and a fix would be uploaded to YetiForce, but you prefer to discuss it for about a week, although it doesn't bring any results. Isn't it a waste of time?

**Comment by Raggazzoo** [comment]
I will buy a support package you're right.

**Comment by paula-w** [comment]
It might take 15 minutes, but it might take 2 hours as well. We have to access the system, enable logs, and verify the problem. We'll need up to 1h for verification and assessment. If it's something simple then we can fix it right away; if it requires more time to fix we'll send you an explanation and ask for instructions on how to proceed.

**Comment by Raggazzoo** [comment]
Ok I will purchase One Man Hour in this case, is it possible to work on it tomorrow?

**Comment by bpabiszczak** [comment]
Yes.

**Comment by Raggazzoo** [comment]
Allright let's go =)

**Comment by paula-w** [comment]
Full analysis of the problem was sent directly to your email. In our opinion all the problems  result from incorrectly executed updates.
