### ISSUE TITLE
User Filter

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3460]
#### Issue

I do not see the option "+Create New Filter" when try to create User Filter in for example "OP Module".

Only can see when the user is "admin"

#### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/3030997/18098613/6216aa90-6eb9-11e6-8955-f86f8d33048e.png)

#### How to trigger the error

1. Create a User
2. NOT set to "admin"

#### Your Environment

* YetiForce Version used: Latest Stable 3.2.0
* Browser name and version: Chrome (latest), Firefox (latest), Safari (latest).
* Environment name and version: 
* Operating System and version: Mac OS X El Capitan

**Comment by nic86** [comment]
see in Software configuration  > Permissions >  Profiles  > Profile Name
under the field privileges in section **Privileges to actions and views** if the action **Custom filters creation** is selected

**Comment by skramanzia** [comment]
I do not have that option in the module "Opportunities"


![image](https://cloud.githubusercontent.com/assets/3030997/18099346/758f8332-6ebc-11e6-9a81-b2f93f49b21f.png)

**Comment by iRainSystem** [comment]
It does not work it's true

**Comment by skramanzia** [comment]
Update:

same in "Quote", "Sales Order" modules.

**Comment by skramanzia** [comment]
@rskrzypczak, Thanks to resolve this issue. It´s possible apply this change in current stable version?, can i run some script or add fields in DB?.

**Comment by natpicone** [comment]
@skramanzia 
Here is a sql script for the missing permissions.
Please take in mind that:
a) this will not add the missing permissions to non default YF roles
b) you'll need to edit / mass edit users to apply the new permissions (you can just made a fake mass edit)

Hope this helps.

[yeti32_permission_fix.sql.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/464064/yeti32_permission_fix.sql.zip)
