### ISSUE TITLE
CurrencyUpdate Bank Question

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3461]
#### Issue

Question:
It is possible to add new Banks, in condition to check other currency? My country (Argentina) are not available in Europe Bank..

#### Actual Behavior

 -

**Comment by majkel89** [comment]
You have to implement it yourself. Take a look at https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/modules/Settings/CurrencyUpdate/models/bankmodels
