### ISSUE TITLE
After importing Accounts record can not be accessed - 3.2

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#3463]
After importing records to Accounts from CSV I can not access those records.
Message is: 

Permission denied
Record you are trying to access is not found
Home page

**Comment by rskrzypczak** [comment]
Could you give me some more info ([link](https://yetiforce.com/en/github/issues/126-issues.html))? I personally don't see the problem with importing contacts via csv. Check if you have permissions for imported records and if these records were created in the crm at all.
