### ISSUE TITLE
Error when adding a picture.

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3465]
Tested on gitdeveloper.yetiforce.com, version: 3.2.13
Instructions:
1. Go to Support. Select Tickets.
2. Go to full edition view.
3. Go to "Description details", click on the icon for adding pictures, then click "Send ">      "Select file" and attach previously created picture > again click "Send".
4. See the screen shot for error message.

[PL]
Błąd występuje podczas dodawania obrazka.
Testowane na gitdeveloper.yetiforce.com, wersja: 3.2.13
Instrukcje:
1. Przejdź do Wsparcie. Wybierz zakładkę Zgłoszenia.
2. Przejdź do widoku pełnej edycji tego rekordu.
3. Zejdź niżej do pola „Informacje opisowe”. Kliknij na ikonkę obrazek. Następnie przycisk „Wyślij” > przycisk „Wybierz plik” > załącz utworzony wcześniej obrazek > ponownie  przycisk „Wyślij”.
4. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![140](https://cloud.githubusercontent.com/assets/11139594/18118907/0750355a-6f58-11e6-97ae-61b2dffdc7ff.png)

**Comment by TomaszQr** [comment]
This feature has been removed from the current version
