### ISSUE TITLE
There is an error after logging into portal.

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3467]
Portal: https://gitdeveloper.yetiforce.com/portal 
 version: 3.2.0 

[pl]
Po zalogowaniu do portalu wysypuje błąd
Portal: https://gitdeveloper.yetiforce.com/portal 
wersja: 3.2.0 
![144 png b](https://cloud.githubusercontent.com/assets/11139594/18122695/e8da89f0-6f6a-11e6-8877-422b3e34296a.png)

**Comment by konadrian** [comment]
bc2feaaedf4531da6e370f65e3e95908fee67071
