### ISSUE TITLE
[bug][with solution] Error when clicking on a mailto link

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3468]
#### Issue

Error when clicking on a mailto link
#### How to trigger the error

1. ![error1](https://cloud.githubusercontent.com/assets/18419851/18123203/c0e9637c-6f64-11e6-8568-5e2b8a3b57d2.PNG)
#### Solution

modules\OSSMail\views\compose.php:20
`$this->mainUrl .= '&_task=mail&_action=compose&_extwin=1';`
replace by
`$this->mainUrl .= '?_task=mail&_action=compose&_extwin=1';`
#### Your Environment

- YetiForce Version used: 3.2.0 stable
- Browser name and version: Chrome 52
- Environment name and version: php 5.6
- Operating System and version: Windows 10

**Comment by mariuszkrzaczkowski** [comment]
Error has been fixed
