### ISSUE TITLE
[PL] There is no active transaction

### ISSUE THREAD

**Issue by ScAArY** [YetiForceCompany/YetiForceCRM#3470]
Przy dodawaniu użytkownika wyswietla mi blad:

Błąd!!!
There is no active transaction

Pytanie czy to problem po stronie moich ustawien PHP lub Apache2?

PHP 7.0
Version of Yeti Force 3.2.0

**Comment by paula-w** [comment]
Prosimy o zapoznanie się z https://yetiforce.com/pl/github/issues/125-issues.html i uzupełnienie brakujących informacji.

**Comment by Dmaric108** [comment]
I have the same problem:

Version of Yeti Force 3.2.0

[Smarty Debug Console.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/447180/Smarty.Debug.Console.pdf)
[Yetiforce_ Error!!!.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/447181/Yetiforce_.Error.pdf)

**Comment by Dmaric108** [comment]
Maybe the problem is that that there is  STRICT_TRANS_TABLE in SQL_MODE, currently checking with support.

**Comment by Dmaric108** [comment]
No, not that, still same error.

**Comment by bpabiszczak** [comment]
@ScAArY Problem w tym, że masz PHP w wersji 7 bo na dzień dzisiejszy nie jest on wspierany.
@Dmaric108: You should have PHP 5.6.

**Comment by Denz55** [comment]
I have the same problem:
Server version: 5.6.31 - MySQL Community Server (GPL)
Protocol version: 10

What version is needed

**Comment by kabelo38** [comment]
go to phpmyadmin and execute this query SET GLOBAL sql_mode = ''; should get rid of that error
