### ISSUE TITLE
Error after adding an attachment.

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3471]
Tested on:
- gitdeveloper.yetiforce.com, version: 3.2.25
- gitdeveloper.yetiforce.com/portal/index.php, version: 3.2.0 

Instructions:
1. At gitdeveloper.yetiforce.com add a ticket with attachments as Document (related module)
2. Go to portal. Preview the ticket. Add attachments added as Document (1.png)
3. See the screen shot for error message.

[PL]
Błąd po dodaniu Załącznika.
Testowane na:
- gitdeveloper.yetiforce.com, wersja: 3.2.25
- gitdeveloper.yetiforce.com/portal/index.php wersja: 3.2.0 

Instrukcje:
1. Na gitdeveloper.yetiforce.com dodaj zgłoszenie wraz z załącznikiem jako Dokument (moduł powiązany).
2. Przejdź do Portalu. Zrób podgląd tego Zgłoszenia. Dodaj załącznik dodany jako Dokument (1.png).
3. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![154](https://cloud.githubusercontent.com/assets/11139594/18127729/7f97c8c8-6f82-11e6-9d64-8a377d4d08f9.png)

**Comment by konadrian** [comment]
Fixed https://github.com/YetiForceCompany/YetiForcePortal/commit/bc2feaaedf4531da6e370f65e3e95908fee67071
