### ISSUE TITLE
Underscore in custom field name

### ISSUE THREAD

**Issue by paulprisacaru** [YetiForceCompany/YetiForceCRM#3472]
Hello,

In YetiForce 3.2 I can't use underscore in custom field name.
![underscore_field_name](https://cloud.githubusercontent.com/assets/11438273/18128221/69518b8e-6f8d-11e6-807b-b1bda36826e9.png)

Tested on: gitdeveloper.yetiforce.com
In the previous version (3.1.0) I could use underscore in field name. This "feature" was planned?

Regards,
Paul

**Comment by bpabiszczak** [comment]
> This "feature" was planned?
NO. You can not use an underscore.
