### ISSUE TITLE
Records do not delete from sql database and no recycle bin

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3474]
Hi,

I created some test contact records in version 3.2 then I deleted them. I tried to create a new test contact using the same email account and it would not let me proceed as said it already existed. When I check the Contacts the record does not exist. When I check mysql the contact is still there. 

Expected behaviour
When I delete a record anywhere in the CRM it is deleted from the table. If not, then there needs to be an option to both view and delete from a recycle bin.

**Comment by nic86** [comment]
not a solution but for add module recycle bin to the default menu:

Software configuration  > Standard modules >  Menu - Configuration  > Start

click on "add menu item"
Select menu type: Module
click next
Select module: type Recycle Bin
click add

reload or restart webservice

**Comment by PercyP** [comment]
@nic86 

Thanks Nic, I now have the recycle bin :)
