### ISSUE TITLE
Only administrators can download Invoice PDF

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3475]
#### Issue
I have created an invoice template and set its permissions to all users. When I create an invoice, I can as Administrator select the icon to download/export. As a regular user I do not see the icon.

#### Actual Behavior
I log in as a regular (none administrator) user. Go to Invoices, search for option to download - it is not there. 

#### Expected Behavior
As a regular user when I go to Invoices I have the option to download

**Comment by kpaulaha** [comment]
On our installations it works ok when the permissions for the pdf are correct, and the "Export to PDF" is checked in the profile

**Comment by PercyP** [comment]
@kpaulaha 
thanks - that seems to be the problem. However when I edit the profile, and select to export to pdf and save - it doesn't actually save and instead, it disables other modules like Sales etc. It is not allowing me to save changes to profiles.

**Comment by PercyP** [comment]
I cannot enable any of the following modules in Profile Permissions:
 Sales Orders					
Recurring Sales Orders					
Partners					
Competition					
Bookkeeping					
Invoices					
KnowledgeBase					
Storage Turnover Notes

Also, if I open an existing Profile i.e. Sales and save it, then it disables those modules for that profile too.

![recordscannotbeenabled](https://cloud.githubusercontent.com/assets/10598886/18137068/e383a804-6f9e-11e6-9268-942a4a1dbd79.png)

Is there a quick fix for the profile permissions?

**Comment by bpabiszczak** [comment]
Please check max_input_vars [5000 or more]

**Comment by PercyP** [comment]
@bpabiszczak 

THANKYOU!!! It was down to my server settings. They have all been corrected (apart from innodb_lock_wait_timeout which I cannot find on WHM PHP configuration - but working on this). 

Kind regards
