### ISSUE TITLE
[BUG] Update from 3.1 to 3.2

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3477]
error in cache/logs/system.log

ERROR DB - Query Failed:  select \* from vtiger_announcement inner join vtiger_users on vtiger_announcement.creatorid=vtiger_users.id AND vtiger_users.is_admin='on' AND vtiger_users.status='Active' AND vtiger_users.deleted = 0 | Table 'databasename.vtiger_announcement' doesn't exist | SQLSTATE[42S02]: Base table or view not found: 1146 Table 'databasename.vtiger_announcement' doesn't exist(/var/www/yetiroot/include/database/PearDatabase.php : 360)

but after a refresh the system seems to work properly.
It gave error in init.php script( after line 170) in function postupdate():

```
$className = $this->getClassName('Functions');
if ($className) {
    $className::recurseDelete($dirName);
    $className::recurseDelete('cache/templates_c');
}
if (headers_sent()) {
    die('<div class="well pushDown">System update completed: <a class="btn btn-success" href="' . $siteUrl . '">Return to the homepage</a></div>');
} else {
    exit(header('Location: ' . $siteUrl, true, 301));
}

```

**Comment by rskrzypczak** [comment]
From what version did you update the system?  From stable 3.1, or some version between 3.1.0 and 3.2.0?

**Comment by nic86** [comment]
from stable 3.1

**Comment by paula-w** [comment]
An error like this requires an individual approach and verification in the system each time it occurs. We can fix it within the support hours. It’s most likely outdated now, so I’m going to close the issue.
