### ISSUE TITLE
In PDF Creator Back, Next buttons hidden behind footer Yetiforce 3.2

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3478]
Hi,

In PDF creator the buttons are barely visible at the bottom of the page as they are partly hidden by the footer bar that displays the user details. 
Yetiforce 3.2
See image.
![pdfcreatorbuttonshidden](https://cloud.githubusercontent.com/assets/10598886/18138392/5bcafb6e-6fa4-11e6-8b05-c465b1833cfb.png)

This footer section also covers other screens:
![hidesscreen](https://cloud.githubusercontent.com/assets/10598886/18138464/b4481c18-6fa4-11e6-978f-02915dbabd81.png)

**Comment by skramanzia** [comment]
Same in User Edit settings and main menu.

![image](https://cloud.githubusercontent.com/assets/3030997/18143377/23014060-6f98-11e6-953d-f4242c312766.png)

**Comment by konadrian** [comment]
@PercyP the error doesn't occur in the current version
@skramanzia the error has been fixed

**Comment by StaggerLeee** [comment]
Just updated today and see same problem.

**Comment by skramanzia** [comment]
@StaggerLeee @konadrian 

I had to modify "/layouts/basic/modules/Vtiger/Body.tpl" also

-		<div class="baseContainer {if AppConfig::main('isVisibleUserInfoFooter')}userInfoFooter{/if}">
 +		<div class="baseContainer {if AppConfig::module('Users','IS_VISIBLE_USER_INFO_FOOTER')}userInfoFooter{/if}">

**Comment by konadrian** [comment]
@everyone – since this issue originally only related to PDF,  we'd like to ask you to open a new issue and enumerate there all the places where the error occurs. First make sure you have the necessary styles, and proper values set in config.

**Comment by PercyP** [comment]
@skramanzia 

I jst spotted your solution. Mine still wasn't working with the original fix, but now I also changed the file you pointed to and it has fixed the problem in both the pdf and elsewhere. Thanks
