### ISSUE TITLE
Decimal Sep PDF

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3479]
#### Issue

Total Margin and gross decimal. Not appear

![image](https://cloud.githubusercontent.com/assets/3030997/18144513/5eaee28e-6f9d-11e6-9ec8-e46fac601edf.png)
#### How to trigger the error

1. Create PDF
2. Set total_margin and gross 
#### Your Environment

- YetiForce Version used: 3.2.0
- Browser name and version: Chrome Latest
- Environment name and version:
- Operating System and version: MAC OS X El Capitan

**Comment by skramanzia** [comment]
More Information: Currency and number field configuration 

![image](https://cloud.githubusercontent.com/assets/3030997/18173745/2ae47ce4-7041-11e6-89c4-5dfd3335151c.png)

**Comment by skramanzia** [comment]
Hi @konadrian and @TomaszQr the problem persists in the current latest version (v3.4)

Thanks!

![image](https://cloud.githubusercontent.com/assets/3030997/19251996/ac39dd0c-8f18-11e6-9a5e-a4c74cb937aa.png)

**Comment by konadrian** [comment]
I set exactly the same values in user settings, for me values in the products block and net&gross  prices look the same
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/21383276/2c31f39e-c765-11e6-9beb-bae68beddfe8.png)
