### ISSUE TITLE
[BUG?] Field Mask

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#3482]
Maybe it should be, that if you use the 9 Digits put a dash, and if you use a different number, it remains overlooked. In fact, now, any number 9 is replaced by a dash. Then it seems to me instead tsyfry 9 must use the same dash, or any other character. And to add the information in the FAQ.

![animation 5](https://cloud.githubusercontent.com/assets/1402355/18158898/83b288b8-703f-11e6-835b-6786b310fa33.gif)

**Comment by paula-w** [comment]
Take a look at this: https://github.com/RobinHerbots/Inputmask 
Also give us more details because we don't understand your description.
