### ISSUE TITLE
3.10->3.20 upgrade issue: Admin locked out

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#3485]
Most upgrades went fine so far but we have one site where we get locked out. (this one had several upgrades already)

Normal behavior is to get redirected to the homepage automatically. In this case we get a button: Return to Homepage. When clicked it logs out and we are not able to login again, not as admin, not as users.
In vTiger sometimes a 'repair' script for user rights was needed but never had this issue before.

Tested with MYSQL / MariaDB and we kept the setup at 5.6 (and looking forward tot the full PHP7 support)

Any clue how to debug / fix this? I will leave it for a few days on the test site like this

**Comment by zebrahosting** [comment]
Copying the latest dev version over solved the issue. (3.2.55) hope nothing changed in the DB in between....

**Comment by bpabiszczak** [comment]
1. Debugging: https://yetiforce.com/en/developer-documentation/engine/115-debugging.html
2. "hope nothing changed in the DB in between" - then you're reporting errors ... wow

**Comment by zebrahosting** [comment]
DB changes between 3.20 release and 3.2.55 in case you misunderstood.

I left this open since it needed more testing and indeed now the whole mail and calender setup don't open anymore. Still can't upgrade the live site.  Hope to find time to debug more.

**Comment by bpabiszczak** [comment]
There is only one right way to do it - enable debugging. A developer needs to have a look into the system, see what is wrong and fix it. We cannot suppose what is wrong and what you've done, we enable debugging and fix a problem when we identify it.
