### ISSUE TITLE
No Option for user to change password 

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3492]
#### Actual Behavior

No option
#### Expected Behavior

User Profile option, where user can add this photo, change password, style, themes, etc.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.1
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
config > security.php > SHOW_MY_PREFERENCES

**Comment by basanthagarwal** [comment]
Thanks .. Got it. !! :)
