### ISSUE TITLE
Cant add new Profile -  80% module privileges is unavailable.

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3493]
Yeti 3.2 tried to add new Profile, but I cant customize. More than 80% module is unavailable.
On git dev it works good.
I do not know whether it is Bug or any of my adjustment is not good.  I belive my confing must be adjusted.

![profilesssss](https://cloud.githubusercontent.com/assets/19521910/18229679/78676e84-7282-11e6-9a49-9a8d7b018ee8.gif)

![privil](https://cloud.githubusercontent.com/assets/19521910/18229687/ad15ffa6-7282-11e6-9053-a77c4517bf13.png)

![privil2](https://cloud.githubusercontent.com/assets/19521910/18229688/b0a0bec2-7282-11e6-8b98-1c6013dec161.png)

**Comment by serbiaserbia** [comment]
As I remember someone had a similar problem, but I can not find Issue on Github.

**Comment by SkavenKF** [comment]
Hi, i have tested on a new installation 3.2.0 on my server with admin user and the same parameters.
I have no problems with the new Profile!

**Comment by bpabiszczak** [comment]
Please check server requirements: max_input_vars 5000 [or more]

**Comment by serbiaserbia** [comment]
I found same issue: Related to #3000

**Comment by serbiaserbia** [comment]
@SkavenKF  thanks for update testing

Solved  -  max_input_vars = 8000   works great
