### ISSUE TITLE
Unable to connect to My Mailbox

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3495]
#### Issue

Unable to connect to My Mailbox

#### Actual Behavior

When email id and password is added, it is showing as "Connection to Storage Server Failed"
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/126-issues.html
