### ISSUE TITLE
Migrate from 3.1 to 3.2

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3496]
#### Issue

How to Migrate from 3.1 to 3.2 without disturbing my existing setting and my customised features. 
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/implementer/installation-updates/176-system-update.html
