### ISSUE TITLE
Records are accessed by other employees with same role. 

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3498]
#### Issue

Records are accessed by other employees with same role. 

#### Actual Behavior

Example:

Roles are as follows: Vice President -> Team Leader -> Relation Manager

Suppose there are Vice President - VP1, VP2, Team Leaders - TL1 , TL2 and suppose there are Relation Managers RM1, RM2, RM3, RM4, RM5.

RM1, RM2 reports TL1
RM3, RM4 reports TL2
TL1, TL2 reports to VP1
RM5 reports to VP2

Now, TL1 can see all records of RM1, RM2, RM3, RM4, RM5 
same with TL2 can see all records of RM1, RM2, RM3, RM4, RM5
VP1 is able to see TL1, TL2, RM1, ..... RM5
also, VP2 is able to see TL1, TL2, RM1, ..... RM5

#### Expected Behavior

TL1 should access his own records and that of RM1, RM2
TL2 should access his own records and that of RM3, RM4
VP2 should access his own records and that of RM5
VP1 should access his own records and TL1, TL2, RM1 .. .RM4

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by basanthagarwal** [comment]
I have tested on latest version. Problem is still there .

**Comment by paula-w** [comment]
Please read the article that describes how to add issues to our repository. 

Unfortunately from what you wrote we don't know much about the permissions configuration - they are configured in many different places, and whether or not someone can access something depends on many factors. 

If you want us to verify it then you have to record a gif on the gitdeveloper version, which will show us exactly what and where was configured, this way we will be able to check whether your problem results from an actual error, or you don't know how it works.

**Comment by skramanzia** [comment]
@basanthagarwal please read the article that describes how to add issue.

 I dont know if your problem is a real issue, maybe is a concepts error or permissions. Check in "permissions->module access" you have a lot of tools to make your config, you can start to set  "private" your module.

Good luck

**Comment by basanthagarwal** [comment]
What i understand is - - above mentioned issue is related to Users, we have field called "Reports to " 
in vTiger, when we add name of senior employee user, access permissions are set accordingly. 
However, in YetiForce, ALL TeamLeaders are able to access ALL RM records. 

Thanks for concern, will follow pattern of raising issue from next time onwards.
