### ISSUE TITLE
changelog 3.2 missing

### ISSUE THREAD

**Issue by galciu** [YetiForceCompany/YetiForceCRM#3499]
Hello,
where we can find changelog for latest version (it's not on the site as described)?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3444

**Comment by KatarzynaUlichnowska** [comment]
It's been also added on our [website](https://yetiforce.com/en/developer-documentation/changes/213-yetiforce-3-2.html).
You can also find all previous lists of changes in the same category - [Changes](https://yetiforce.com/en/developer-documentation/changes.html).
