### ISSUE TITLE
Udostępnienie kalendarza.

### ISSUE THREAD

**Issue by zwieja** [YetiForceCompany/YetiForceCRM#3500]
Proszę o pomoc krok po kroku jak udostępnić kalendarz innemu użytkownikowi.

YF 3.1

**Comment by bpabiszczak** [comment]
Najlepiej wykupić sobie szkolenie :o albo zapłacić za wdrożenie :] 
Do udostępnienia użytkownikowi A kalendarza użytkownikowi B najlepiej sprawdzi się to narzędzie: https://gitdeveloper.yetiforce.com/index.php?module=SharingAccess&parent=Settings&view=Index&block=1&fieldid=5 
Należy pamiętać, że użytkownik na roli powinien móc widzieć innych kalendarze w trybie graficznym.

**Comment by zwieja** [comment]
@bpabiszczak 
Ostatnie pytanie.  Jak dodać użytkownika do wyboru w polu Użytkownik w kalendarzu ?

**Comment by bpabiszczak** [comment]
Lista generowana jest automatycznie na podstawie tego co użytkownik widzi [trzeba tylko w roli wyłączyć opcje aby widział tylko siebie]. Gdy udostępnisz mu terminy innych, wówczas będzie mógł sobie filtrować per użytkownik.

**Comment by hipernet** [comment]
filtrować per użytkownik -udostępnione dla grupy zarzad nie działa
