### ISSUE TITLE
[Enchancement] Multi tree field edit

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3501]
I checked multi trees at my local 3.2 system. I'm added multi tree field to products module with product categories. It's very cool but there is no possibility to edit already filled field. You can close pick popup window (no changes) or select nodes from from scratch (new selection will be saved). This is not flexible if you have big tree with a lot of categories and subcategories.

**Comment by vovpff** [comment]
@bpabiszczak let's check gif
![multi no edit](https://cloud.githubusercontent.com/assets/8545791/18471963/f9a0499e-79bc-11e6-8aa9-b5708a183eff.gif)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/3432

**Comment by vovpff** [comment]
@bpabiszczak why you checked as duplicate? There are bug with no possibility of editing from already saved data
