### ISSUE TITLE
[QUESTION] number of columns in listwiev

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#3502]
Hi.
I need to change the maximum number of columns in the listview on 14?
there is a variable in the configuration, or is in the code?
I did not find. :(

**Comment by vovpff** [comment]
@iRainSystem maximum is 12. This limitation grows from vtiger core.

**Comment by iRainSystem** [comment]
@vovpff Thank you, I will have to think about it.

**Comment by paula-w** [comment]
The limit is hard coded in system files, if there's a client who's willing to pay for moving it to the configuration then we can do it, we'll need 15~60 minutes to do that.
