### ISSUE TITLE
Error while adding a widget, no widget added.

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3505]
Tested on gitdeveloper.yetiforce.com, version: 3.2.95
Instructions:
1. Go to Software configuration, then to Standard modules. Select "Widgets - configuration".
2. Click a "+widget" button.
3. A window will appear, so select a widget and save.
4. See the screen shot for error message.

[PL]
Błąd podczas dodawania widżetu, brak dodanego widżetu.
Testowane na gitdeveloper.yetiforce.com, wersja: 3.2.95
Instrukcje:
1. Przejdź do Konfiguracji systemu. Następnie do Moduły standardowe. Wybierz z menu „Widżety konfiguracja”.
2. Kliknij na przycisk „+widget”.
3. Otworzy się okno, wybierz widżet i zapisz.
4. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![170](https://cloud.githubusercontent.com/assets/11139594/18304041/625df2ec-74e0-11e6-8a8c-d2a036e47a58.png)

**Comment by nkzach** [comment]
If refresh page, widget appears.

**Comment by lslotow** [comment]
Thank you for the quick response. I think that my problem exists as I do not have many icons under the home icon in settings. I only have Home, Shop and Permissions. Where can I find the other icons for settings?
