### ISSUE TITLE
Add new data in a multi selection custom field

### ISSUE THREAD

**Issue by Imaginocharme** [YetiForceCompany/YetiForceCRM#3507]
## Issue

Probably as a simple one, but i can find a place here i can add new data to a multi selection custom field.

#### Actual Behavior

i import to a multi selection custom field data whith format " Var1 |##| Var2 |##| Var3 |##| ...." and after importation my multi selection field only have the original data, like for ex. "Var0" 

#### Expected Behavior
After importation the custom field must have all Var's imported 

#### How to trigger the error

I thinks is not and error. 

#### Your Environment

* YetiForce Version used: 3.2
* Browser name and version: Firefox
* Environment name and version: Apache / Linux 
* Operating System and version: Windows 10

**Comment by vovpff** [comment]
@Imaginocharme try import with comma (,) separator between vars.

**Comment by Imaginocharme** [comment]
It was my first attempt , I tried also with ";" and  "#" and  "| ## |" nothing ;(

**Comment by Imaginocharme** [comment]
the problem as this, i import 15 / 20 itens to filed Tags like this 
![6b95a1ccbb21d94f2628fbf23116d3f4](https://cloud.githubusercontent.com/assets/18466761/18346245/2cadb358-75b7-11e6-9d52-2c2bfae47c7d.png)
and after import in combo only have 2 ( who had originally)
![52f96761eff72218bb763ea9283116c5](https://cloud.githubusercontent.com/assets/18466761/18346295/61d6d794-75b7-11e6-9db9-e7806496ab81.png)

**Comment by bpabiszczak** [comment]
In the field configuration you can add a lot of value. In the field, you can only choose [should not work paste].
