### ISSUE TITLE
Synchronizacja kalendarza [PL]

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#3508]
Mam taki problem są wpisy w api a nie ma ich w kalendarzu YF 
jeżeli chodzi o logi to nic specjalnego tam nie ma 
synchronizacja z poziomu programu klienta nie wykazuje żadnych błędów.

[07-Sep-2016 20:15:01 Europe/Sarajevo] PHP Fatal error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /home/serwis/domains/crm.hipernet.com.pl/public_html/include/database/PearDatabase.php on line 114
[07-Sep-2016 20:20:01 Europe/Sarajevo] PHP Fatal error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /home/serwis/domains/crm.hipernet.com.pl/public_html/include/database/PearDatabase.php on line 114

#### Your Environment

* YetiForce Version used:3.2.0
* Browser name and version:Firefox
* Environment name and version:
* Operating System and version:OS

**Comment by bpabiszczak** [comment]
fajnie... ale czy testowałeś z gitdeveloper?

**Comment by hipernet** [comment]
tak , problem bardziej złożony z tunderbirdem działa z outlook  poprzez caldav synchronizer nie koniecznie
cron działa poprawnie błędów nie wyspuje , sam nie wiem będę grzebał dalej

**Comment by bpabiszczak** [comment]
logi, logi i jeszcze raz logi... nam nie wystarczy, że napiszesz że testowałeś, tylko skoro uruchamiałeś to z gitdeveloper to opisz co i jak skonfigurowałeś, pokaż co widać w logach po stronie aplikacji i napisz w jakich godzinach, wówczas my sprawdzimy po stronie CRM czy coś w logach nie widać.

My potrzebujemy "dowód", że to wina jest po stronie YetiForce a nie np. po stronie aplikacji, sieci, firewall, tylko gdy mamy pewność, że to błąd CRM to dopiero wówczas się tym zajmujemy.

**Comment by hipernet** [comment]
ok, czy synchronizacja działa w obie strony czy tylko w jedną

**Comment by bpabiszczak** [comment]
domyślnie w obie

**Comment by hipernet** [comment]
gitdeveloper.yetiforce.com  zrobiłem 2 wpisy  przeszły do outlook ale trzeci zrobilem na otlloku nie przeszedł do YF

**Comment by hipernet** [comment]
czy opóznienie jest ?

**Comment by hipernet** [comment]
jest opóźnienie ale u Was działa

**Comment by hipernet** [comment]
logi klienta: 
INFO  2016-09-08 16:56:18,608 [ VSTA_Main]    CalDavSynchronizer.ComponentContainer . MoveNext                       - Synchronization manually triggered
 INFO  2016-09-08 16:56:18,686 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Starting 'Running synchronization profile 'crm''
 INFO  2016-09-08 16:56:18,686 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`7 . MoveNext                       - Entered. Syncstrategy 'TwoWayInitialSyncStateCreationStrategy`6' with Atype='AppointmentItemWrapper' and Btype='IICalendar'
 INFO  2016-09-08 16:56:18,686 [ VSTA_Main] ementation.Events.OutlookEventRepository . GetAll                         - Using Outlook DASL filter: @SQL="http://schemas.microsoft.com/mapi/proptag/0x001A001E" = 'IPM.Appointment' And "urn:schemas:calendar:dtstart" < '08.03.2017 00:00' And "urn:schemas:calendar:dtend" > '10.07.2016 00:00'
 INFO  2016-09-08 16:56:18,702 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Starting 'CalDavRepository.GetVersions'
 INFO  2016-09-08 16:56:18,952 [ VSTA_Main] onizer.Implementation.CalDavRepository`1 . MoveNext                       - Duration of 'CalDavRepository.GetVersions': 00:00:00.2377834
 INFO  2016-09-08 16:56:18,952 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`7 . MoveNext                       - Atype delta: Unchanged: 10 , Added: 0 , Deleted 0 ,  Changed 0
 INFO  2016-09-08 16:56:18,952 [ VSTA_Main]   GenSync.Synchronization.Synchronizer`7 . MoveNext                       - Btype delta: Unchanged: 10 , Added: 0 , Deleted 0 ,  Changed 0
 INFO  2016-09-08 16:56:18,952 [ VSTA_Main] .Scheduling.SynchronizationProfileRunner . MoveNext                       - Duration of 'Running synchronization profile 'crm'': 00:00:00.2753751

**Comment by hipernet** [comment]
Efekt jest taki wpis w kalendarzu  tunderbird przenosi się poprzez synchronizacje na otlooka  i odwrotnie też na na Yeti nie ma zmian ani w jedną ani w druga stronę  napewno coś jest źle ale co ?

**Comment by mariuszkrzaczkowski** [comment]
Nagraj film pokazujący w czym jest problem bo po tych logach nic nie widać.

**Comment by bpabiszczak** [comment]
Po opisach ja nic nie rozumiem, raz działa raz nie :D Testuj to z 1-2 dni i po testach napisz do jakich wniosków doszedłeś.

**Comment by hipernet** [comment]
Po testach :
nie działa mi udostępnienie kalendarza graficznego w grupie  nie działa synchronizacja  z outlookiem 
nie mogę znaleźć przyczyny problemu
