### ISSUE TITLE
Cant upload images

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3511]
#### Issue

When trying to upload logos I am getting the error "Invalid image" I have checked the correct image size and tried all flavours of extension with to no avail.
#### Actual Behavior

I click on upload select the image it shows the image fine as its being attached but when i click save I get the error then just fav.png text in the top left and no image
#### Expected Behavior

Image to be uploaded and shown on the site
#### How to trigger the error

1.screen to gif 
![error](https://cloud.githubusercontent.com/assets/22075161/18347908/43683416-75c0-11e6-8ba8-81483d0e22d3.gif)

2.
3.
#### Your Environment

- YetiForce Version used: 3.2.0
- Browser name and version: chrome latest, ie 11
- Environment name and version: apache hosting with php 5.6
- Operating System and version: windows 7 64 bit pro

**Comment by novateco** [comment]
any update of this bug?¿

**Comment by paula-w** [comment]
We tested it on the current version and the bug doesn't seem to exist anymore. 
Can you test it on gitdev once again and let us know?

**Comment by alextovey** [comment]
@paula-w

Close away issues gone with the new one

**Comment by alextovey** [comment]
@paula-w

Close away issues gone with the new one
