### ISSUE TITLE
Rename modules - Accounts and contacts

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3512]
How can I rename accounts to clients and contacts to managers? I've done the menu but quick create and module names are still the same.

**Comment by paula-w** [comment]
Don't do that... Even though there are tools for that [translations editor, loader and composer] it requires changes in numerous system files. If you don't want it to be overwritten when you update to a new version you should do it via loader.

**Comment by alextovey** [comment]
You say loader? Where can I find that?

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/engine/177-loader-and-autoloader-of-files.html

**Comment by alextovey** [comment]
I did create a contacts module but no fields show up when in relations. I did follow this tutorial but it didnt work for me

**Comment by alextovey** [comment]
Will try again.

**Comment by alextovey** [comment]
Okay, Strange It's not let me edit calendar or events module either. :S
