### ISSUE TITLE
Invoices not being marked against accounts

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3513]
Hi,

When trying to create invoices I cannot input the amounts and therefore it does not go against my accounts. Im using the latest stable version 3.2.0 any help would be awesome.

**Comment by dextras** [comment]
Can you give some more info?prepare an animated gif or explain the issue in more details.  
https://yetiforce.com/en/github/issues/126-issues.html

**Comment by alextovey** [comment]
![image](https://cloud.githubusercontent.com/assets/22075161/18430806/0deb2e3c-78d2-11e6-9191-a3eeff9b6b0c.png)
![image](https://cloud.githubusercontent.com/assets/22075161/18430832/29344dc2-78d2-11e6-8454-900786d7a622.png)


When I create an invoice filling in all the pre req's such as quote, po number etc When i finally go to submit the invoice there is nowhere for me to input the actual amount even when I click on accpeted on quote the amount does not display on their account. Happy todo a skype or web session to show full length if thats needed.

**Comment by dextras** [comment]
The best thing for you to do would be to generate a gif with https://screentogif.codeplex.com/ with all the steps to reproduce the bug. I am still not sure what exactly do you mean by "the amount is not shown on the account".

**Comment by alextovey** [comment]
5 mins and i'll post its just loading frames at the moment.

**Comment by alextovey** [comment]
![problem01543](https://cloud.githubusercontent.com/assets/22075161/18435550/de7aeb82-78eb-11e6-8fc2-24249a27265a.gif)

**Comment by dextras** [comment]
I've noticed that you did not add any products to the invoice. So the invoice amount is 0. I am also not sure weather the "Balance" field works in yetiforce yet. It did not work in 3.1 at least or I just did not know how it should behave.

**Comment by alextovey** [comment]
I cannot see a products section to add it too? Or am I being thick?

**Comment by dextras** [comment]
Did you change sth in the fields? I believe you did and accidentally set the module to be "Basic" rather than "Advnaced". Go to Configuration -> Stadard modules -> Edit fields and then select the invoice module. Then set the switch to "Advanced" 
![image](https://cloud.githubusercontent.com/assets/7486027/18436442/9fa21450-78f8-11e6-81fe-de2f751128e9.png).

**Comment by alextovey** [comment]
done that but still not products section.

**Comment by alextovey** [comment]
ah got it thank you.

**Comment by dextras** [comment]
I made similar mistake few months ago and it took me several hours to figure out the problem ;) I am glad i could help.

**Comment by alextovey** [comment]
I've got another ticket, for editing events/calendar options have you done anything with this before? it's locked down and I cant add any modules or change any pick lists or anything
