### ISSUE TITLE
No related Ticket created

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3515]
Tested on dev.yetiforce.com/developer/portal, version:  3.2.2
Instructions:
1. Go to the Portal.
2. Select the Projects tab.
3. Block - related Tickets. Click the "Add Ticket" button.
4. Enter data and save.
5. No Ticket has been created.

[PL]
Brak utworzonego Powiązanego zgłoszenia.
Testowane na dev.yetiforce.com/developer/portal, wersja: 3.2.2
Instrukcje:
1. Przejdź do Portalu.
2. Wybierz zakładkę Projekty.
3. Blok - Powiązane zgłoszenia. Kliknij na przycisk „Dodaj Zgłoszenie”.
4. Wprowadź dane i zapisz.
5. Brak utworzonego zgłoszenia.
![179](https://cloud.githubusercontent.com/assets/11139594/18349147/04688ae4-75d0-11e6-935b-ec9333c71784.png)

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForcePortal/commit/37fdd6c73655dc15e888b86a13b482a71740eadb
