### ISSUE TITLE
Report Error when the field "assigned to" is selected for Opportunities

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3516]
#### Issue

On git developer version I try to make a report with the field "assigned to" but it returns no result.
#### Actual Behavior

The report returns no result
#### Expected Behavior

List opportunities assigned to yetiforcedemo
#### How to trigger the error

![gif](https://cloud.githubusercontent.com/assets/1357727/18358310/bf62586a-75f4-11e6-8804-5622e5633edf.gif)
#### Your Environment

- YetiForce Version used: 3.2.134
- Browser name and version: Chrome
- Environment name and version: Git Dev
- Operating System and version:

**Comment by TomaszQr** [comment]
Error doesn't exist in current version
