### ISSUE TITLE
[Question] Add Logo (Picture) to a Lead !

### ISSUE THREAD

**Issue by Imaginocharme** [YetiForceCompany/YetiForceCRM#3517]
Any way to create a custom field to put a logo/picture in Lead? ( and preview in detail ) 

Today, it is critical that functionality...

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3248
https://github.com/YetiForceCompany/YetiForceCRM/issues/3406
https://github.com/YetiForceCompany/YetiForceCRM/issues/3241
