### ISSUE TITLE
1:M - Cant establish new reationship

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3518]
Yetiforce 3.2
Tried on developer 3.2, but there is no possibilities to add relationship, it is not enabled.

What I am trying:
   - Establish new relationship Accounts to NewModule (bank account)

Whats happend:
   - In Accounts there is NewModule, but when click on new relation - I have no possibilities to work with it. It look like stopped loading. There is no footer "copyright....etc". Please see gif.

![new relationship](https://cloud.githubusercontent.com/assets/19521910/18376720/c3b87bde-7661-11e6-88d9-a1c32ddce83b.gif)

**Comment by serbiaserbia** [comment]
I search in phperror.log and found something interesting>>

[09-Sep-2016 10:24:47 Europe/Belgrade] PHP Fatal error:  Call to a member function fetch() on boolean in /var/sentora/hostdata/admin/public_html/mojposao_ga/yeti/include/database/PearDatabase.php on line 309

**Comment by serbiaserbia** [comment]
And also in system.log found this>>>

Fri Sep  9 10:31:42 2016,847 [19665] ERROR DB - 
#0 LoggerCategory->error('Query Failed:   LIMIT 0,20 | You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0,20' at line 1 | SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0,20' at line 1(/var/sentora/hostdata/admin/public_html/mojposao_ga/yeti/modules/Vtiger/models/RelationListView.php : 303)') in include/database/PearDatabase.php(175): 
#1 PearDatabase->log('Query Failed:   LIMIT 0,20 | You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0,20' at line 1 | SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0,20' at line 1','error') in include/database/PearDatabase.php(346): 
#2 PearDatabase->query('  LIMIT 0,20') in modules/Vtiger/models/RelationListView.php(303): 
#3 Vtiger_RelationListView_Model->getEntries() in modules/Vtiger/views/RelatedList.php(85): 
#4 Vtiger_RelatedList_View->process() in modules/Vtiger/views/Detail.php(482): 
#5 Vtiger_Detail_View->showRelatedList() in (): 
#6 call_user_func_array([object(Vtiger_Detail_View),showRelatedList],[object(Vtiger_Request)]) in include/runtime/Controller.php(89): 
#7 Vtiger_Controller->invokeExposedMethod('showRelatedList') in modules/Vtiger/views/Detail.php(194): 
#8 Vtiger_Detail_View->process() in include/main/WebUI.php(220): 
#9 Vtiger_WebUI->process() in index.php(25):

**Comment by SkavenKF** [comment]
Can you check your field names in the new module? I have the same problem on some field names (i think it was "from", "to" and some others, i'm not sure). 
At the moment i use a prefix for my field names.

**Comment by serbiaserbia** [comment]
@SkavenKF 
I made one test module with no special fields, only Type: Base module.
I think it is maybe server configuration problem, because it look like it stoped loading page.
Can you screenshot your server config. What kind of server do you using? (Shared, VPS, dedicate...)

GitDev server conf. screeshot:
![developer server config](https://cloud.githubusercontent.com/assets/19521910/18401575/654caa32-76db-11e6-9ebb-49ae6fc5f66b.png)
My server conf. screenshot:
![my server config](https://cloud.githubusercontent.com/assets/19521910/18401583/761611d2-76db-11e6-9aff-fd8d1a6b5781.png)

difference is max_input_time

**Comment by SkavenKF** [comment]
i create a test modul and do a relation with account (at gitdeveloper)
![test_jpg](https://cloud.githubusercontent.com/assets/10259801/18401861/f52eab9a-76dc-11e6-95fb-b1824575a8d1.JPG)

**Comment by SkavenKF** [comment]
i use a wamp installation on windows 10. 
![config](https://cloud.githubusercontent.com/assets/10259801/18401959/6a5ffaae-76dd-11e6-82d2-e58e79e075aa.JPG)
