### ISSUE TITLE
Create Reporting Access

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3520]
#### Issue

cant see modules with User accounts. Only admin Works
#### Actual Behavior

ADMIN
![image](https://cloud.githubusercontent.com/assets/3030997/18402274/0d129794-76b5-11e6-8c95-89bcfd68132c.png)

Cant set ALL options
![image](https://cloud.githubusercontent.com/assets/3030997/18402434/b5e4f93e-76b5-11e6-867d-faae0dea4751.png)

User
![image](https://cloud.githubusercontent.com/assets/3030997/18402288/20ec5b56-76b5-11e6-8722-018597d48268.png)

#### Expected Behavior

See modules
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.2
* Browser name and version: Chrome Lastest
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
#3506

**Comment by konadrian** [comment]
I created user which is not admin and I get all modules in list. Could you check is error still occurs 
![module_reports](https://cloud.githubusercontent.com/assets/3193498/18429702/2dca8c5e-78d5-11e6-8685-fb89cc67d0b4.png)

**Comment by skramanzia** [comment]
Hi @konadrian after apply https://github.com/YetiForceCompany/YetiForceCRM/commit/c17e85d2e1568e774dce728b47c2c3f9035f4314 and "Save" again profiles, works correctly.

Thanks @kpaulaha and @konadrian
