### ISSUE TITLE
Is it possible to hide administrator from all users?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3522]
Hi,

I would like to hide the administrator from regular users so that for example when creating a new record, the administrator cannot be selected from the Assign to dropdown box.

We will never have a situation where a record wold be assigned to the administrator by a member of staff. Is there a way of hiding the admin user from all regular users?

I have gone through the sharing permissions and adjusted the settings but the admin user still appears. 

In content management systems the Admin user is hidden from regular users, is it possible to do this in Yetiforce?

Kind regards

**Comment by vovpff** [comment]
@PercyP let's make new role for admin user with no ability to assign this role to any record

**Comment by PercyP** [comment]
@vovpff 

that sounds like a good idea, it would be good to at least have an option to hide admins from regular user views.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/performance.php#L25

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

thank you! I have changed that to false but it doesn't hide the admins, does it hide for you?

**Comment by konadrian** [comment]
It's work for me, I have change only 	'SHOW_ADMINISTRATORS_IN_USERS_LIST' => false, this
This is admin user
![hideadmin1](https://cloud.githubusercontent.com/assets/3193498/18501819/69669436-7a53-11e6-9f17-ed76ed83409b.png)
Not admin user
![hideadmin2](https://cloud.githubusercontent.com/assets/3193498/18501825/72a3a5d4-7a53-11e6-83bc-7654a58d5938.png)

**Comment by PercyP** [comment]
@konadrian 

Can I ask what version you are using? I am on 3.2 - changes to those settings seem to be ignored in my instance of yetiforce

**Comment by konadrian** [comment]
I tested this on the latest version

**Comment by PercyP** [comment]
@konadrian 

I suppose that is a clean version? Unfortunately I can move to a clean version as have made so many changes to meet my needs and there is no way to add those back to a clean version (that I know of).

**Comment by alextovey** [comment]
that should work on a unclean version too. Just a config change. Backup before you attempt it and have a go.

**Comment by PercyP** [comment]
@alextovey 

I have just downloaded a clean version and yo are correct it works with no other alterations. I am now just going through the settings on both the clean and my customised version to see if maybe it is something in the permissions etc.

**Comment by PercyP** [comment]
Thanks everyone. I figured it out. It was a Role permissions error. If you make sure the role permissions match those in the clean download it works.

**Comment by alextovey** [comment]
@PercyP 

If i helped can you like my reaction please :)
