### ISSUE TITLE
Webform triggers an error is currently unable to handle this request

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3523]
#### Issue
I created a webform on 2 different test sites (one on a shared hosting the other on a VPS) both produce errors when I try to submit the form from my Joomla site. Webforms have always worked on previous versions. I have checked the permissions on the webforms folder which is 755 and 644 for capture.php

#### Actual Behavior
After completing the details in my newly created webform and hitting the submit button I get the following error page: 

The www.yoursite.com page isn’t working 
www.yoursite.com is currently unable to handle this request.
HTTP ERROR 500

The url in my address bar points to: http://www.yoursite.com/yetiforce/modules/Webforms/capture.php

#### Expected Behavior
The form submits and the details appear in my Leads table in CRM

#### How to trigger the error
Create a webform and add it to a website and try to submit it.

#### Your Environment

* YetiForce Version used: 3.2
* Browser name and version: Google Chrome, Firefox, Microsoft Edge
* Environment name and version: Windows 10
* Operating System and version:

**Comment by PercyP** [comment]
An update.

Firstly, I realised I hadn't added the correct access key into the webforms config file. Once I did this the error changed on sbmitting the webform to:

Fatal error: Class 'AppConfig' not found in /home/sites/mysite.com/public_html/yetiforce/config/config.inc.php on line 18

When I open the config file that line 18 code is as follows:

AppConfig::iniSet('memory_limit', '512M');

Hopefully I am getting closer to the solution :)

**Comment by kpaulaha** [comment]
Yup, it's not working. In fact last version I have seen it working without problems is 2.3.49, but have forgotten to report it as a bug.

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/384e2ed733e564d4d8a3d3fc2841c0b9882fad3f
