### ISSUE TITLE
Logo/image is not displaying in exported/generated PDF

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3531]
#### Issue
I have created a basic pdf for invoices. I have inserted the logo manually as using the file browser on the image insert produce a missing image icon in the PDF. To insert my logo I clicked on image and added the full url to the image as follows:

htpp://www.mysite.com/myimage.png

This inserts the image into the PDF and it is visible. However, when I export a newly created invoice, the image in the pdf is replaced with the missing image icon (the little cross).

I noticed that the current yetiforce has an issue with images in that it displays the missing image icon within the pdf.

#### Actual Behavior
No image is displayed in Generated PDF

#### Expected Behavior
Image to appear in generated pdf.

#### How to trigger the error
Create a new pdf and try to insert an image then try to generate a PDF. You can also open an existong pdf in yetiforce and see they are not displaying there.

#### Your Environment

* YetiForce Version used: 3.2
* Browser name and version: Chrome latest
* Environment name and version:
* Operating System and version: windows 10

**Comment by alextovey** [comment]
@PercyP 
Its a permission issue within your cache folder. I've had this and now it works change cache > uploads all to 777 and it will work

**Comment by PercyP** [comment]
@alextovey 

That did the trick - thank you!

**Comment by alextovey** [comment]
Glad we are helping each other out on these issues :)

**Comment by PercyP** [comment]
Me too - its a big learning curve without much documentation, but can see they are working on this.
