### ISSUE TITLE
Report Not Data Available.

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3533]
#### Issue

When created a custom Report with 2 Relations fields (one to Account and other to Contacts), the Total Record are 4. and not display thats.

 If I remove "Account Contact" Related Fields, displayed correctly.
#### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/3030997/18443486/8266ae8a-78eb-11e6-8f53-c0063b1a6056.png)
#### Your Environment

- YetiForce Version used: 3.2.262
- Browser name and version: Chrome
- Environment name and version:
- Operating System and version:

**Comment by skramanzia** [comment]
Hi @bpabiszczak, i update this "Issue" status.

 I did the test in the latest version and the issue continues. When created a report that include a custom field with "contacts" relations, not display result.

thanks !!

![image](https://cloud.githubusercontent.com/assets/3030997/19251633/ad33f618-8f16-11e6-8188-9f8ad53da5b6.png)

**Comment by skramanzia** [comment]
Related Issue, in stable version not see error

#3608

**Comment by paula-w** [comment]
1. In which module did you add the fields?
2. Does the error exist in the current version?

**Comment by skramanzia** [comment]
Hello @paula-w the error was resolved in current version (DEV).

Thanks!
