### ISSUE TITLE
Invoices - no adjustment field for discounts or a shipping field

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3534]
Hi,

In Vtiger, when creating an invoice we used to be able to add a discount or adjustment where we could add or subtract a specif value based on an amount or a percentage. We also could add Shipping and it also displayed summaries.

I*s this not possible in yetiforce?

**Comment by alextovey** [comment]
@PercyP 
Not there yet :( was looking myself

**Comment by PercyP** [comment]
Hope they haven't removed this functionality as this was excellent (at least for us). I wonder if there is any way of re-adding it? When you say not there yet, are you aware at all if it is in the pipeline?

**Comment by alextovey** [comment]
I'm not no, but was looking at tiger modules and thinking I wonder if I can intergrate that such as PDF editor and viewer plus a few others :-)

**Comment by PercyP** [comment]
If I remember correct. yetiforce originally had the same as vtiger invoicing and pdf (In an earlier version before 3x the invoicing was much better. If you download and install one of the earlier ones you will see what I mean

**Comment by bpabiszczak** [comment]
This field has been removed. We do not plan to add it. You can add the service delivery to the invoice.
