### ISSUE TITLE
[bug] Can't add related data from a Relation Widget on Summary page

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3535]
#### Issue
On summary page i can't create data with "add", which are linked to the module.

#### Actual Behavior
It create data which not linked to the module

#### Expected Behavior
It create data which linked to the module

#### How to trigger the error
1. create a simple new module (eg. Test)
2. in this modul, create a linked field to a standard module (eg. Projects)
3. in standard module, add a widget (related module) to the new module and enable "Add Button"
![bug](https://cloud.githubusercontent.com/assets/10259801/18452187/42d52db0-793a-11e6-900e-174d6fda1a33.gif)

#### Your Environment
* YetiForce Version used:  3.2.169 (gitdeveloper) and 3.2.0
* Browser name and version: chrome, firefox
* Operating System and version: Windows

**Comment by konadrian** [comment]
You should enable new 1:M field in quick create in edit fields and then adding new records should  working. 
![newmodule](https://cloud.githubusercontent.com/assets/3193498/18540389/a3b435be-7b1e-11e6-9146-4b9ffcf878ea.png)
![newmodule](https://cloud.githubusercontent.com/assets/3193498/18540410/ccebade0-7b1e-11e6-8b49-a3f1895cda13.png)
