### ISSUE TITLE
1:M - Cant establish new reationship

### ISSUE THREAD

**Issue by MexasPT** [YetiForceCompany/YetiForceCRM#3536]
Yetiforce 3.2.177
Tried on developer 3.2.177, but it's ok enabled.

What I am trying:
When I am creating an opportunity in related field with the "accounts" it is inactive and it is not possible to choose or search accounts.

Whats happend:
Select an account when I am creating an Opportunity.
I also tried to create Field 1: M for the accounts but without success

I just installed from scratch and I think that is an option that I can not remember how to change.
Can you help me?

Please see gif.

![1 m](https://cloud.githubusercontent.com/assets/17734465/18472401/2fdf23a8-79af-11e6-943d-8895827a0028.png)

**Comment by bpabiszczak** [comment]
When you modify the system, you need to know how to debug core/system. 
https://yetiforce.com/en/github/issues/126-issues.html
https://yetiforce.com/en/developer-documentation/engine/115-debugging.html.

**Comment by MexasPT** [comment]
I did not change the system. I just installed from scratch .
