### ISSUE TITLE
Multiple Columes

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#3538]
Version 3.1.0 When creating a module and adding fields.  Is there a way to customize the  layout so we can have multiple columns and not just 2 columns?  

Thank you

**Comment by skramanzia** [comment]
@jbmcclain could you explain it better ? may be with screen shots to make it easy.

**Comment by SkavenKF** [comment]
@jbmcclain: Unfortunatly you have only 2 columns. 
![columns](https://cloud.githubusercontent.com/assets/10259801/18508835/2c886d3c-7a76-11e6-8d00-d6f495b92b22.JPG)

**Comment by dextras** [comment]
I believe you would have to modify css files for such a change to take effect. The thing is that the layout adjusts itself  to the size of the screen and for example on phones you will have only one column instead of two. How to increase? Maybe somebody else has more knowledge about css.

**Comment by bpabiszczak** [comment]
You can not change this from the panel.

**Comment by JunyaB** [comment]
my 2 cents:
when add custom block is selected we get to choose the type of block 2 column or 3 column instead of sending us to directly a 2 column block.
because sometimes a 3 column is what is needed.
