### ISSUE TITLE
[bug?] Online forms

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3539]
#### Issue
v. 3.2.xx /modules/Webforms/capture.php returns 
![capture](https://cloud.githubusercontent.com/assets/10330264/18510244/a6f386c4-7a85-11e6-894f-a1337028a301.png)

v. 2.3.xx  /modules/Webforms/capture.php on same server returns, as it should:  
{"success":false,"error":{"message":"Webform not found."}}

Bug or server issue?

**Comment by PercyP** [comment]
@kpaulaha 

I think it is a bug. I too having problems:
