### ISSUE TITLE
Template not able to move item

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3540]
Hi,

I've got an issue with the invoice template. I cannot move an item under VAT and Gross.

![image](https://cloud.githubusercontent.com/assets/22075161/18514000/a4a5220e-7a87-11e6-86c9-78ebadace8e4.png)

This is under editing the template but Is it possible to add each field individually?

So Item's/product unit price net vat and gross then VAT summary underneath.

**Comment by PercyP** [comment]
@alextovey 

Is this a template yo created as there doesn't appear to be one that comes with the installation. Where do yo want them to sit? Can yo do a mockup of how you want it to look?

**Comment by alextovey** [comment]
@PercyP

Will do one later today and post it just about to head out.

**Comment by dextras** [comment]
This kind of changes require the creation/modification of special pdf functions. Check #3370.  Normally yetiforce team charges for such modifications (they are always very personal and for one time only).

**Comment by PercyP** [comment]
The PDFs (invoices in my case) seem to have taken a backward step. I liked the old style that included the ability to add discounts, and also how it displayed totals, subtotals and VAT. If we could have invoices like in Vtiger it would be brilliant.

DO others prefer this new invoice style?

**Comment by alextovey** [comment]
I've got a developer my side working on changing a few things for me and will post the code up for you once its done

**Comment by PercyP** [comment]
Hi Alex brilliant! Thank you

**Comment by alextovey** [comment]
Why was it closed still would be nice to know???

**Comment by PercyP** [comment]
It probably looks like we have resolved it. Agree, it wold be nice to know.

**Comment by alextovey** [comment]
Right i've managed to edit a few things to get it just sort of what i want. so I've added it here.

**Comment by PercyP** [comment]
Hi Alex,

was excited then. Where is 'here' :)

**Comment by alextovey** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<pdf_template>
  <fields>
    <field>
      <module_name>FInvoice</module_name>
      <status>active</status>
      <primary_name>Main Invoice</primary_name>
      <secondary_name>Invoice1</secondary_name>
      <meta_author/>
      <meta_creator/>
      <meta_keywords/>
      <metatags_status>1</metatags_status>
      <meta_subject/>
      <meta_title/>
      <page_format>A4</page_format>
      <margin_chkbox>1</margin_chkbox>
      <margin_top>0</margin_top>
      <margin_bottom>0</margin_bottom>
      <margin_left>0</margin_left>
      <margin_right>0</margin_right>
      <header_height>0</header_height>
      <footer_height>0</footer_height>
      <page_orientation>PLL_PORTRAIT</page_orientation>
      <language>en_us</language>
      <filename>Invoice00</filename>
      <visibility>PLL_LISTVIEW,PLL_DETAILVIEW</visibility>
      <header_content><![CDATA[]]></header_content>
      <body_content><![CDATA[<table border="0" style="width:100%;"><tr><td><img alt="" src="/home/claregolding/public_html/live/cache/upload/images/invislogo.png" style="width:250px;height:125px;"></td>
			<td style="width:33%;"> </td>
			<td>Project Start Recruitment Solutions Ltd<br>
			4 Maisemore,<br>
			Yate,<br>
			Bristol,<br>
			BS37 8UP,<br>
			Telephone: 01454 52900<br>
			Email: accounts@projectstart.co.uk </td>
		</tr></table><hr> 
<table border="0" style="width:100%;"><tr><td><span>$accountid+Accounts+accountname$</span><br><span>$accountid+Accounts+buildingnumbera$ $accountid+Accounts+addresslevel8a$</span><br><span>$accountid+Accounts+addresslevel6a$</span><br><span>$accountid+Accounts+addresslevel5a$</span><br><span>$accountid+Accounts+addresslevel7a$</span></td>
			<td style="width:33%;"> </td>
			<td><span>Invoice Number:$number$</span><br><span>Invoice Date:$invoicedate$</span><br><span>Due Date: $paymentdate$</span></td>
		</tr></table><hr><br>
#ProductsTableNew#
<div style="text-align:right;">
<table border="0" style="width:100%;"><tr><td style="width:33%;"> </td>
			<td style="width:34%;"> </td>
			<td style="width:33%;height:200px;">#TableTaxSummary#</td>
		</tr></table></div>

<div> 
<table border="1" style="height:250px;width:400px;"><tr><td>Candidate Name: $candidatename$<br>
			Job Title: $jobtitle$</td>
		</tr></table></div>
]]></body_content>
      <footer_content><![CDATA[<span style="font-size:12px;">Payable within 30days of invoice being issued.<br />
Payments by bank transfer to Project Start Recruitment Solutions Ltd<br />
Sort Code:30-90-89  Account Number: 28395468</span>]]></footer_content>
      <conditions><![CDATA[[]]]></conditions>
      <default>1</default>
      <watermark_type>text</watermark_type>
      <watermark_text/>
      <watermark_size>0</watermark_size>
      <watermark_angle>0</watermark_angle>
      <template_members>Users:1,Users:5</template_members>
      <watermark_image/>
    </field>
  </fields>
</pdf_template>
`

**Comment by alextovey** [comment]
Cant upload so heres the code

**Comment by PercyP** [comment]
@alextovey 

Thank Alex, although it is hard to see what is going on with it pasted like that. Are you able paste the content source? (that little <> icon on the toolbar when in the Content part of the pdf? That should paste ok on here if you also use the <> above to insert it.

**Comment by alextovey** [comment]
@PercyP There you go sorted it :)
