### ISSUE TITLE
A Question...

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3541]
Can Yeti force pick out field and fill it in from a cv yet? Just wondering as that would really help in what i'm trying to achieve?

**Comment by PercyP** [comment]
Hi Alex, 

do you mean from a webform, or maybe from an RSS feed or something else. Where does the CV data originate from?

**Comment by alextovey** [comment]
From pdf or a word doc

**Comment by PercyP** [comment]
Are they uploaded to a website first, or straight into yetiforce? Are you not able to capture cv details straight into a webform that then goes in yetiforce?

**Comment by alextovey** [comment]
So uploaded to the site then want the site to translate them i know sap does it well.

**Comment by PercyP** [comment]
What platform is your site on?

**Comment by alextovey** [comment]
apache mysql and php 5.5 you?

**Comment by PercyP** [comment]
Apologies, I meant your pdfs and word, what is the process i.e. do yo have a jobboard website, if so what platform i.e. Joomla, Drupal, Wordpress is that website on and again, what jobboard component (if it is on a website) is used.

**Comment by alextovey** [comment]
ah yeah recruitment agency using wordpress

**Comment by PercyP** [comment]
If the recruitment agency is running a jobsboard, then (on most job sites) when a candidate submits their details they fill in a form version of their CV and also have the option to upload it in word, pdf as an extra. Do you know if the agency you are dealing with captures details in this way too? Why I ask, is if they are already capturing form details then this might be easier for you as it will contain all they key information from the documnet cv (there are lots of tools, bridges etc. out there that can help automatically update i.e. yetiforce tables when a new record is added - or existing cv record updated)in the cv form.

Unless you are already aware of an easier way - hense asking the question "Can Yeti force pick out field and fill it in from a cv yet?" Like their is a tool in yetiforce (or vtiger) that can possibly do this?

**Comment by alextovey** [comment]
all she has on her job board is a cv upload with a name and email. But is uploading name etc worth it.

**Comment by PercyP** [comment]
Hi Alex,

I am probably thinking you are asking for something more complex. When you asked your original question, what exactly are you wanting to happen? Are you wanting Yetiforce CRM to scan through a word or pdf document that you upload (no interaction with her website) and pick out fields such as name, address, experience etc. and put it inside some custom module on the crm? Or for there to be some interaction between her website and the crm - its not clear to me.

**Comment by alextovey** [comment]
So upload the cv and it creates a candidate entry putting name address, email, phone and skill set into fields in the module. 

Sorry if I'm unclear but it's hard to put down what they need.

**Comment by PercyP** [comment]
I think you need to start with their website. If they want their content to populate a module in yetiforce then they need to get that set up right first. Like I said once you do that, there are loads of tools that work with vtiger to update vtger tables, so sure if you speak to those developers they will be able to build you a tool to import your cv details into yetiforce. It seems a big ask on here to expect a crm system to do that with a pdf/doc file - unless you know something I dont?

**Comment by dextras** [comment]
A simple answer to that question is ... it can not. Yetiforce has no module to, as PercyP said, scan through the pdf/doc and extract data directly to a database record. There has to be some additional tool that does it.

**Comment by waran70** [comment]
Search  for abbyy api. Integration with abbyy could be an interesting
milestone for YF.
Various archiving system would be interested: police, libraries, revenue
departments, translation companies
and many more

**Comment by PercyP** [comment]
The simple be to swap her existing form that captures name, email. Create a new webform that includes additional boxes (to capture the additional information she wants i.e. DOB, Career History, Education etc. (the candidate can paste text from cv) and finally an upload attachment/document field. This way new details will automatically go into the Leads or other table as desired. I am not sure if it is possible for webforms to work with custom modules? If yes, then that would be a good solution.

There are online tools that I know work with excel whereby you can scan documents into excel, but as you know, no 2 cvs are ever structured the same, so it would be difficult to automate for every single potential layout. If someone is interested enough to submit a cv, I am sure they will be willing to paste details into the form fields, after all it is them who want something out of the process.

**Comment by alextovey** [comment]
That Abby API might work nicely. :)

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/206-system-development-ideas.html
