### ISSUE TITLE
Feature request - ability to save PDFs at any stage

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3542]
Currently when creating a PDF we have to click on the Next button through to Finish when creating or editing a PDF. 

This is obviously necessary when creating a new PDF, but can be quite frustrating when trying to edit just one part of an existing PDF. 

It would be good to have a Save Changes button that saves the update and takes us back to the PDF menu.

It would also be good to be able to click on the section you want to edit and not have to click Next Next Next to get to the body for example

**Comment by dextras** [comment]
It would be all very very useful. Currently the pdf is saved after you press next. So the way i solve it is that when I change one section and do not want to mess with anything else I just click next and then Cancel. Changes are saved and I do not have to go until the end ;)
But -  In my opinion your proposal is a must have option for better usability. It also should not take much to code.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/206-system-development-ideas.html
