### ISSUE TITLE
Where in the database are the Invoice Columns?

### ISSUE THREAD

**Issue by RedMoon27** [YetiForceCompany/YetiForceCRM#3544]
I'm looking to alter the columns that appear on an invoice (_PDF generated with ProductsTable.php_) and after trying to tweak with the _ProductsTable.php_ file itself I've decided that the easiest and most reckless way to do so is to remove the fields from the database completely. Now I can't find them. I know they are under a _vtiger__ prefix but this database is enormous.

I am referring to fields like:
* _Unit_
* _Subunit_
* _Unit Price_
* _Tax_

Any help on the issue will be appreciated.

**Comment by PercyP** [comment]
@RedMoon27 

Are they not in vtiger_fields?

**Comment by vovpff** [comment]
@RedMoon27 `vtiger_subunit`, `vtiger_usageunit`, `vtiger_taxclass`, `vtiger_inventorytaxinfo`. Price you can find at unit price column at `vtiger_products` table.
I think price isn't possible to remove or this actions can be cause of big problems with all system workability.

**Comment by dextras** [comment]
I do not thing that removing fields from database is the best solution. Depending on what you want to achieve of course. If you are only thinking about modifying the pdf layout, and do not care baout those columns then remove them, indeed, but with the GUI in the backend

1. go to Settings -> Standard Modules -> Edit Fieds.
2. Choose "Invoices"
3. Switch to "Managing an advanced block" 
![image](https://cloud.githubusercontent.com/assets/7486027/18568849/8870d8e4-7b9f-11e6-89b5-3d076067b214.png)
4. Remove the columns you do not need.

The columns you do not need will not be shown in the invoice when it is generated with ProductsTable.php.
Is this what you needed?
