### ISSUE TITLE
[Question] Importing data

### ISSUE THREAD

**Issue by lamontef** [YetiForceCompany/YetiForceCRM#3545]
I have a large amount of data to import into my YetiForce installation and I've read in numerous places (YetiForce docs, vTiger posts, etc.) that using the built-in import function isn't the best option, using a custom script is. I had been using the built-in function, but have found that the import results are very inconsistent (duplicate data, even when using the duplicate check option).

What I'm looking for is options/opinions on how to get millions of records imported into the system with accuracy. I've been working on a custom script, but ran into issues with relationships (a foreign key preventing data to be inserted into the leaddetails table). I've been researching and experimenting with this for weeks and can't find any solid answers/options, so thought I'd check with the community...

According to the documentation, this statement seems to be a key to the success of an import project: 

"Whether the data imported is in the right order. "
(from YF documentation -> Custom Data Import -> 5. Optimization -> 2. The Script)

Is this ordered list available anywhere? If I had this list, I'd have a much better idea of what to do as it would also tell me what tables need to be populated and what relationships need to be created.

Thanks much

LaMonte M. Forthun

**Comment by PercyP** [comment]
@lamontef 

I may be wrong, but my approach would be:

1. first make sure your version of yetiforce has all the additional fields you need (as per your existing system - you will need to add custom fields if they don't exist - you might also want to change the any labels of yetiforce fields to match your own (will make the import easier for you)
2.. Then add a couple of dummy records to each of the modules you want to import data in to. 
3. Next export those tables (this should give you an idea as to how the fields are structured)
4. Take a couple of hundred records from your own system (possibly with duplicates) and structure them like the tables you exported (I think dates have to be structured in a very precise way - at least in vtiger they did as the install failed)
5. Run some test imports, making changes to your test data if it fails

I haven't imported millions of records, usually only thousands, but if it is different when dealing with such large volumes hopefully someone with more knowledge will post the proper solution

**Comment by alextovey** [comment]
@lamontef You can directly import data using csv or excel into yetiforce from others as long as its in those formats. To do this goto accounts then click on the actions then import. You will need to check and match the relevant fields when importing but that will be in the steps.

**Comment by lamontef** [comment]
@alextovey - Thank you for your feedback, but the issue is that importing using YF's import routine is, based on personal experience and from the YF documentation, not very efficient when you have large amounts of data to import. It's recommended to use a custom script to do the import, which I've been working on. My hope was that someone had some insight as to the proper order to import the fields needed and what fields were required.

I've been able to get to the point where I know what fields need data and which have to be imported before others due to dependencies (foreign keys, etc.), I just need to write the code to do those imports properly.

**Comment by alextovey** [comment]
Ah I understand. May be worth purchasing a support bundle so they can write the script for you. I have found them really good. Plus you get dedicated 1 to 1 so you know it's time set aside just for you

**Comment by krobin8** [comment]
Can anyone share with me the correct date / time import format? I am trying to import time control records so I have a start date, start time, end date, end time mandatory field. I've tried just about everything I can imagine and the imports fail. I know it's got to be based on my format. Thanks in advance.

**Comment by PercyP** [comment]
@krobin8 

Have you tried creating a dummy record in time control then exporting it? Yo will at least then be able to see how the time/date fields need to be structured. I used to have to do this with vtiger to get the correct formats.

**Comment by krobin8** [comment]
No, but that is a great idea. I am headed out for the day but will try tomorrow and report results.

**Comment by vovpff** [comment]
@krobin8 I use YYYY-MM-DD hh:mm:ss

**Comment by krobin8** [comment]
Thanks everyone! The dates are importing now, but I think the problem never was that. It is that the time control records have both an "Account" and "Project". I have both of those records already in the database but I cannot seem to import the project field. If I test the records with just the account field mapped it does work. When I add the project field, or ONLY import the project field with the record it imports the record but has the relationship is not made... any ideas?

**Comment by bpabiszczak** [comment]
The import mechanism has been rewritten.

**Comment by littledove22** [comment]
Where is the import feature to add clients?  The documentation is useless.  Its not searchable, and there seems to be no easy-to-follow User Instructions.

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Accounts&view=List&mid=51&parent=47
![image](https://user-images.githubusercontent.com/10198654/71655006-165e0b00-2d35-11ea-9047-ecdf366b0f01.png)
