### ISSUE TITLE
Advanced Sharing Rules - not working

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3546]
Advanced Sharing Rules not working

#### Issue

In Permissions -> Module Access -> Advanced Sharing Rules, option is not working
#### Actual Behavior

There are no records access by user even after enabling Advanced Sharing Rules
#### Expected Behavior

Permissions given under Advanced Sharing Rules, users allows should be able to access record. 

#### How to trigger the error

1. 
2.
3.

#### Your Environment

* YetiForce Version used: 3.2
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version: Windows 7

**Comment by kpaulaha** [comment]
True, but I think it's working with later dev. versions #3439

**Comment by basanthagarwal** [comment]
But, it was working absolutely fine in 3.1 version.

**Comment by kpaulaha** [comment]
Well, there has a lot changed in the code since that. You get it working if you copy-paste the patch.

**Comment by basanthagarwal** [comment]
which patch are you referring to.. ? and which files do i have to replace ?/

Thanks a lot for instant feedback. 
i'm grateful.

**Comment by vovpff** [comment]
@basanthagarwal let's check your cron settings and activate it!

**Comment by bpabiszczak** [comment]
Now work ok, please check latest version. 
https://github.com/YetiForceCompany/YetiForceCRM/commit/a3cd28331fc328a547c3acde3f88512662db6a66
