### ISSUE TITLE
[Bug] Change mail box

### ISSUE THREAD

**Issue by michelmarques1** [YetiForceCompany/YetiForceCRM#3547]
Hello fellow Community

Currently I use the 3.2.0 version of CRM and in my installation use 3 email boxes:

sac @ ...
supervisao.sac @ ...
falefornecedor @ ...

I noticed that after upgrading, can not access the e-mail boxes:

supervisao.sac @ and @ falefornecedor

Every time I click on one of them, I am directed to e-mail box sac @ ...

![image](https://cloud.githubusercontent.com/assets/18095104/18612761/f552513c-7d38-11e6-8cdc-2c16bec12f7b.png)

![image](https://cloud.githubusercontent.com/assets/18095104/18612765/1318351a-7d39-11e6-8cb3-11a102d5f1ac.png)

**Comment by bpabiszczak** [comment]
Please check latest dev version.

**Comment by rskrzypczak** [comment]
The error was most likely fixed in [this ](https://github.com/YetiForceCompany/YetiForceCRM/commit/5da339544bf83da029bb93b28e52e8ec0051b78c)commit.
