### ISSUE TITLE
[BUG] Price

### ISSUE THREAD

**Issue by varlog11** [YetiForceCompany/YetiForceCRM#3548]
![price](https://cloud.githubusercontent.com/assets/1807261/18623631/b5983dcc-7e50-11e6-971d-cd51344b68b7.gif)

**Comment by rskrzypczak** [comment]
I cannot recreate the problem you described, check once again if the error exists.
Most likely, in the heat of the fight with yetiforce, the error has been already fixed.

**Comment by TomaszQr** [comment]
Duplicate #3563
