### ISSUE TITLE
[ENHANCEMENT] Time Format - Service Contract, Tickets, Projects,etc.

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3551]
#### Issue

 Service Contract, Ticket Hours.

I create Service Contract, related to Account and Open New ticket.
Add 2 "Time Control" Task.
![image](https://cloud.githubusercontent.com/assets/3030997/18639838/e04167ae-7e6b-11e6-901e-bb0f43f4a638.png)

Total Real Time: 2Hs 21Min

in Service Contract see this.
![image](https://cloud.githubusercontent.com/assets/3030997/18639876/0e0fd45e-7e6c-11e6-98ca-8b1cda518a9b.png)

Total Time (h): 2.35
#### Expected Behavior

In "Service Contract"
Total Time (h): 2Hs 21 Min

User Units 2Hs 21 Min

Total Units: 665Hs 0Min

- YetiForce Version used: 3.2
- Browser name and version: Chrome / Firefox - both Latest
- Environment name and version:
- Operating System and version: MAC OSX - El Capitan

**Comment by skramanzia** [comment]
Hi Team, I am consider this "Enhancement" is critical for Reports. If manager or Boss require a report of how many hours are consumed for support or whatever module,  the information is not real or legible for users.

**Comment by bpabiszczak** [comment]
Please check the latest versions.
