### ISSUE TITLE
Błąd po dodaniu widgetu - „Czas pracy użytkownika”.

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3553]
Testowane na gitdeveloper.yetiforce.com, wersja: 3.2.270
Instrukcje:
1. Dodaj widget „Czas pracy użytkownika” po stronie administratora.
2. Przejdź do użytkownika.
3. Dodaj go na Stronie głównej.
4. Błąd widoczny na zrzucie ekranu.
![190](https://cloud.githubusercontent.com/assets/11139594/18659927/f2e8f1cc-7f0d-11e6-8719-481c88bf2ce7.png)

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/ed2056582b7bb91c81c9037c6bef8991a56031f6
