### ISSUE TITLE
Brak możliwości dodania kanału Rss na Stronie głównej.

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3554]
Testowane na gitdeveloper.yetiforce.com, wersja: 3.2.270
Instrukcje:
1. Dodaj widget kanał rss >po stronie administratora (rys. 1).
2. Przejdź do użytkownika. Odśwież.
3. Spróbuj dodać go na Stronie głównej. Pojawia się informacja - Brak
4. Błąd widoczny na zrzucie ekranu (rys. 2).
![191](https://cloud.githubusercontent.com/assets/11139594/18660180/64b019f6-7f0f-11e6-8036-2e548a3669e7.png)
![192](https://cloud.githubusercontent.com/assets/11139594/18660185/6ac7aa66-7f0f-11e6-96fa-949627b6b47e.png)

**Comment by konadrian** [comment]
Nie mogę uzyskać "błędu". Są dostępne adresy rss jakie dodawałaś? Być można widżety były zaznaczone jako obowiązkowe wtedy pojawia się na stronie ale nie będzie do w liście
