### ISSUE TITLE
Nieprawidłowy zapis dodanego wykresu z filtru  –  przy mniejszej rozdzielczości

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3555]
Testowane na gitdeveloper.yetiforce.com, wersja: 3.2.270
Instrukcje:
1. Po stronie administratora dodaj wykres z filtru (kołowy) dla kontrahenta  (rys 1).
2. Dodaj ten widżet na Stronie głównej.
3. Błąd widoczny na zrzucie ekranu (rys. 2).
![193 wykres kolowy](https://cloud.githubusercontent.com/assets/11139594/18661466/3a6393e2-7f16-11e6-98f8-c92836dc9fa2.png)
![193 blad](https://cloud.githubusercontent.com/assets/11139594/18661474/42268c92-7f16-11e6-846d-5f0b4286581c.png)

**Comment by bpabiszczak** [comment]
Wykresy niestandardowe [na których trzeba umieścić bardzo dużą ilość danych] należy projektować indywidualnie. https://yetiforce.com/en/github/issues/206-system-development-ideas.html
