### ISSUE TITLE
Can a client reply to or update a helpdesk ticket via email ?

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#3557]
#### Issue

Strange behavior with the HelpDesk ticket response via emails.

I believe this issue is related to  https://github.com/YetiForceCompany/YetiForceCRM/issues/1853.

I just want to find out if a user/contact can reply to ticket comments via email? or is there any possibility to have this functionality implemented.?

#### Actual Behavior

Create a new Helpdesk Ticket.

#### Expected Behavior

Add an email reply/content to ticket comments.

#### How to trigger the error

1.Send an email to helpdesk get automated email from the helpdesk with all relevant ticket information including a link to the portal.
2.Whenever a CRM user adds a comment The client receives a notification with the message but when a user/contact attempts to reply back to that ticket comment the CRM creates a new Ticket.

#### Your Environment

* YetiForce Version used:  [ver. 3.2.0] stable
* Browser name and version: Chrome Version 53.0.2785.116 (64-bit) /Firefox
* Environment name and version:
* Operating System and version: Fedora Core 24 / Ubuntu 13

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/user-documentation/support-process/140-automation-of-notifications-in-tickets.html
