### ISSUE TITLE
Brak nazw statusów pod wykresem

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3562]
Testowane na dev.yetiforce.com/developer/portal, wersja: 3.2.2
Instrukcje:
1. Dodaj kilka Zgłoszeń.
2. Zmień ich statusy.
3. Zobacz zrzut ekranu, widoczna wiadomość błędu.
![199](https://cloud.githubusercontent.com/assets/11139594/18700609/80e7da9a-7fd8-11e6-9fb2-911de7126ca8.png)

**Comment by konadrian** [comment]
To nie jest błąd w przypadku gdyby nazwy nachodziły na siebie są one chowane, po najechaniu na odpowiedni słupek pojawia nam się nazwa statusu
