### ISSUE TITLE
Brak nazw użytkowników.

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3563]
Testowane na gitdeveloper.yetiforce.com, wersja: 3.2.296
Instrukcje:
1. Dodaj widżet „Porównanie sprzedaży po użytkownikach” po stronie administratora.
2. Przejdź do Strony głównej dodaj ten widżet.
3. Błąd widoczny na zrzucie ekranu.
![196](https://cloud.githubusercontent.com/assets/11139594/18700921/2748e040-7fda-11e6-91b9-76365146b650.png)

**Comment by rskrzypczak** [comment]
To nie jest błąd. Użytkownicy się pojawią po najechaniu myszką na danych słupek wykresu i to tylko wtedy, gdy zaznaczono opcję pokazywania użytkowników w konfiguracji wykresu.
![image](https://cloud.githubusercontent.com/assets/10221999/18778941/2773ed50-8177-11e6-8664-1da42bc78abc.png)
