### ISSUE TITLE
Two icons aren't working

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3564]
Tested on gitdeveloper.yetiforce.com, version: 3.2.297
Instructions:
1. Go to Leads > List.
2. Mark any record.
3. Select a map icon.
4. Enter an address. Search.
5. Hover over an icon and click. Nothing appears.
6. See the screen shot for error message.

[PL]
Nie działają 2 ikony.
Testowane na gitdeveloper.yetiforce.com, wersja: 3.2.297
Instrukcje:
1. Przejdź do Leady > Lista.
2. Zaznacz dowolny rekord.
3. Wybierz ikonę mapy.
4. Wprowadź adres. Wyszukaj.
5. Najedź na ikony i kliknij. Nic się nie pokazuje.
6. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![206](https://cloud.githubusercontent.com/assets/11139594/18704462/432a34ac-7fea-11e6-9c0f-3d736b034f5a.png)

**Comment by konadrian** [comment]
To nie jest błąd zaznaczanie wartości odbywa się poprzez kliknięcie w "szpilkę" i wybranie czy ma być to początek czy koniec trasy 
![mapa](https://cloud.githubusercontent.com/assets/3193498/18785875/327f0ff8-819b-11e6-84d0-4aa60533098f.png)
