### ISSUE TITLE
Error while creating a report

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3565]
Tested on gitdeveloper.yetiforce.com, version: 3.2.297
Instructions:
1. Go to Reports.
2. Add a Charts report.
3. Enter values and proceed.
4. See a screenshot for an error message.

[PL]
W trakcie tworzenia Raportu pojawił się błąd
Testowane na gitdeveloper.yetiforce.com, wersja: 3.2.297,  angielska
Instrukcje:
1. Przejdź do Raporty.
2. Dodaj raport Wykresy.
3. Wprowadź wartości i przejdź dalej.
4. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![209](https://cloud.githubusercontent.com/assets/11139594/18706065/b6c404f0-7ff0-11e6-92bd-dfeef8c74a39.png)

**Comment by skramanzia** [comment]
Same problem related to, https://github.com/YetiForceCompany/YetiForceCRM/issues/3532
