### ISSUE TITLE
[BUG] User numeric format options breaks workflow

### ISSUE THREAD

**Issue by natpicone** [YetiForceCompany/YetiForceCRM#3566]
While mapping opportunity estimated value to a custom field in project I found that changing user number formatting breaks mapping.
Tested on both gitdeveloper & gitmaster

![ezgif com-resize](https://cloud.githubusercontent.com/assets/4753402/18716862/8942416c-801e-11e6-8f3e-c3b9ecfbc97f.gif)

**Comment by TomaszQr** [comment]
Error doesn't exist in current version
