### ISSUE TITLE
[Question] Workflow related module

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3567]
I try to create Workflow to send EMAIL, for example in module "Opportunities" i have a relation to Products and Assets (by default), but when i create Workflow cannot see relation to Products or Assets, only see to Accounts, Customers and Partners. 

there are some possibility to related this?

Thanks in advanced!

**Comment by skramanzia** [comment]
Hi @paula-w It's possible relate "Products and Assets" and use this to Workflow?.

Any idea? or whats is the function to see in OP if i cant use.

![image](https://cloud.githubusercontent.com/assets/3030997/19041089/19ee6ffa-895d-11e6-94e3-e35653532ed8.png)


Thanks!!

**Comment by paula-w** [comment]
It has to be done by a programmer. 
More info about why we can't implement all the features our community suggests: [Development ideas](https://yetiforce.com/en/github/issues/206-system-development-ideas.html) & [Ignored issues](https://yetiforce.com/en/github/issues/205-why-was-the-issue-ignored.html)
