### ISSUE TITLE
Import / Export modules

### ISSUE THREAD

**Issue by JunyaB** [YetiForceCompany/YetiForceCRM#3568]
#### Issue

One of the things we love about YetiforceCRM is the ability to create and customize modules as we see fit. Once this is done I see no avenue to export to a production unit, or to import a pre-configured module.

#### Question

Can someone share a quick way to move /export/ import a module?

**Comment by vovpff** [comment]
There are ability to export module (down arrow in curcle)
![image](https://cloud.githubusercontent.com/assets/8545791/18778768/a84611d6-817e-11e6-993b-d9ef71fadad6.png)
But module installation/import is missed now...

**Comment by vovpff** [comment]
@JunyaB at my local 3.2.1 system installation available
![image](https://cloud.githubusercontent.com/assets/8545791/18783388/2caffae4-8194-11e6-95b3-505312f57324.png)
https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8

**Comment by JunyaB** [comment]
@vovpff 
Install from file is not in the current dev. (but in 3.2)
how did you get to that screen in your previous (1st) reply?

Thanks for the reply

**Comment by vovpff** [comment]
@JunyaB https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8 here
![image](https://cloud.githubusercontent.com/assets/8545791/18789997/ccedb138-81b5-11e6-9270-f4ca29f613ba.png)
Looks like module import to dev version are blocked

**Comment by JunyaB** [comment]
@vovpff 
I forgot that thanks, but the download link only shows up for modules you create from scratch what about the  original modules that are reconfigured? that's missing and that's  what I was referring to.
Thanks

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/faq-en.html
