### ISSUE TITLE
Dodawanie wiget strona główna[PL]

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#3569]
Mam problem z dodaniem  wigetu z filtru czy to wykresu z filtru mam do wyboru 
tylko filtr moje którego nie mogę wybrać co nie umożliwia dodanie go do strony głównej.

#### Your Environment

* YetiForce Version used: 3.2
* Browser name and version:Firefox
* Environment name and version:
* Operating System and version:Linux

**Comment by bpabiszczak** [comment]
Na filtrze trzeba zaznaczyć taką ikonkę co się nazywa "Pokaż na tablicy" , wówczas będzie on dostępny w innych miejscach.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3192

**Comment by hipernet** [comment]
dzięki
