### ISSUE TITLE
Workflow "owner" Change

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3572]
#### Issue

When i create Workflow to notify by email the change of "assigned to", the task not seen in queue ,i check this in "com_vtiger_workflowtask_queue" table.

 Its not possible send notifications to "owner" with workflow. Only can select Users or groups, not set from field.
#### Actual Behavior

 The Workflow works properly but when i configure "send email" task, the field "To" with ",$(assigned_user_id : (Users) email1)" the value take the "old" assigned user not the current after change.
#### Expected Behavior

When set in "Send Email" task the ",$(assigned_user_id : (Users) email1" send email to the actual owner.
#### How to trigger the error

1.
2.
3.
#### Your Environment

- YetiForce Version used: 3.2 Stable
- Browser name and version: Chrome latest
- Environment name and version:
- Operating System and version:

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/9fe4c4b4f8f2ec970240e9ab05b8315a097eedea
