### ISSUE TITLE
Any ideas for Products Summary

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3573]
How to activate Summary tab for products module? Anybody has ideas?

**Comment by skramanzia** [comment]
i can't see "Products" in module widget to add summary tab.

**Comment by vovpff** [comment]
@skramanzia this is possible to add widgets but not possible to activate summary tab. Maybe somebody can advice something?

**Comment by SkavenKF** [comment]
you must change/delete the coding in "modules\Products\models\module.php
![summary](https://cloud.githubusercontent.com/assets/10259801/18797900/5b971b3a-81d0-11e6-8c28-f668f37c86b7.JPG)

**Comment by vovpff** [comment]
@SkavenKF if this function is true or code quoted there are summary tab appears but contains details tab data and not possible to use widgets.

**Comment by vovpff** [comment]
My idea to get more simple view of product data and necessarily storage contents be "Related module Widget"

**Comment by vovpff** [comment]
Ok. I will try to explain. Our company contains some sales and some engineers guys. For engineers detailed view is very usefull because there are all possible information about product at one webpage. This is possible to quick find any data about product.
Our sales don't need all this information. Whey need summary view of product record what contains product name, part number, desription, comments, actual quantity at different storages.
I tried to activate an "modules\Products\models\module.php" but summary tab has the same information than detiled tab. There is no flexibility for products summary view.
How to made summary foe pruducts like at Projects/Accouns/Contacts/Opportunity module?

**Comment by paula-w** [comment]
This has to be done by a programmer. If you want us to do that for you, you will need one of the [support packages](https://shop.yetiforce.com/en/17-support).
