### ISSUE TITLE
Yeti 3.1 - search bar problem: doesn't search contractors

### ISSUE THREAD

**Issue by galciu** [YetiForceCompany/YetiForceCRM#3574]
#### Issue
in the top search bar, when we input contractor (any data) it doesn't search for it, even if I choose "contractor" group. Others modules searches works fine.

#### Your Environment
* YetiForce Version used: 3.1
* Browser name and version: chrome 52
* Environment name and version: 
* Operating System and version: win 10

**Comment by skramanzia** [comment]
@galciu It's resolved in 3.2 version. Please update or test in the latest

**Comment by bpabiszczak** [comment]
CRON must be enabled
