### ISSUE TITLE
Passwords Module

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3576]
#### Issue

I'm not able to save any new records in Password Module

#### Actual Behavior

Error coming up is - "Password too Long "
While importing records through csv, it is working fine.. where as, while adding records - it is not allowing to save record with even 5 character length of password

#### Expected Behavior

Should be able to save records. 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.2
* Browser name and version: Crome
* Environment name and version: Stable, 3.2
* Operating System and version: Windows

**Comment by paula-w** [comment]
[Here](https://gitdeveloper.yetiforce.com/index.php?module=Password&parent=Settings&view=Index&block=7&fieldid=38) is the option to set the minimal and maximal number of characters in a passwod. Please check if it solves your issue and in case it doesn't – trigger the error on the gitdeveloper version.
