### ISSUE TITLE
Tickets - no way to close it - ver 3.2

### ISSUE THREAD

**Issue by ivanmar** [YetiForceCompany/YetiForceCRM#3578]
Hi,
Trying to enter Yetiforce 3.2 in production but I have problem with tickets.
I can create it and do all kind of stuff, but I can't find way to close it from CRM web interface. 
There is no "Closed" status in picklist when I want to edit it as admin and only creator of ticket. 
I have created custom status in picklist of ticket, then in Processes > Support, I defined that status as closed ticket...but nothing - closed time in ticket detail is still empty. Please check is this a bug or I have overlooked something (if later...please need help)

**Comment by skramanzia** [comment]
@ivanmar Checks Workflows. See "Update closed time" in "Tickets" you can change it

**Comment by ivanmar** [comment]
Thanks,
justfor refference for others:
enable task "update closed time" in Software configuration  > Automation >  Workflows
