### ISSUE TITLE
Advanced module Value field

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3582]
Are anybody has ideas how to made Value for advanced modules related to different storages.
For this time I made additional read-only field what get qty of product from Products table. 
![image](https://cloud.githubusercontent.com/assets/8545791/18835876/03664584-8406-11e6-98db-94afee5dcb4d.png)
But i don't have idea how to get qty from one static storage for examle first line on picture below
![image](https://cloud.githubusercontent.com/assets/8545791/18836022/c6b92236-8406-11e6-8449-be18e5e01241.png)

**Comment by bpabiszczak** [comment]
This requires a developer.
