### ISSUE TITLE
VAT not showing

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3583]
Hi Guys, 

VAT is not showing on the invoices on ProductsNew table. any ideas?
![calendar issue](https://cloud.githubusercontent.com/assets/22075161/18841511/ee4a8ad0-8409-11e6-8ce7-6569701f7adb.gif)

**Comment by alextovey** [comment]
also total is not showing. Any ideas why?

**Comment by alextovey** [comment]
@PercyP

**Comment by dextras** [comment]
Well... You did not add a product...

**Comment by alextovey** [comment]
Even when adding a product its still the same. :(

**Comment by dextras** [comment]
I am checking it in gitdeveloper just now...

**Comment by dextras** [comment]
In gitdeveloper it just works. Even if you do not add a product. There might be something with your installation. Did you change any core files?

**Comment by alextovey** [comment]
No, I did remove some fields in the advanced module. of invoices so it doesn't show on the invoice. would that cause it?

**Comment by dextras** [comment]
Just for testing - can you add the field price after discount?

**Comment by dextras** [comment]
I've tried to do it on gitdeveloper but there seems to be some other customizations and it ... stopped working for now.

**Comment by alextovey** [comment]
no still the same. How do I get the current version. i'll do a verson reinstall over the database

**Comment by alextovey** [comment]
anyone help?

**Comment by paula-w** [comment]
To correctly calculate VAT the “Price after discount” field is needed. If you don't want the field to be visible you can hide it. 

![gh](https://cloud.githubusercontent.com/assets/13310141/18986785/c68927d4-86fe-11e6-99fd-a04349e12fd6.png)

**Comment by alextovey** [comment]
Issue resolved thank you
