### ISSUE TITLE
[BUG] Owner By Ajax Reports

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3584]
#### Issue

When enable option 'SEARCH_OWNERS_BY_AJAX' => true, Report cannot find the owner in assigned to.

![image](https://cloud.githubusercontent.com/assets/3030997/18844332/3e8a902e-83f3-11e6-95ff-8b5d4224b290.png)
#### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/3030997/18844332/3e8a902e-83f3-11e6-95ff-8b5d4224b290.png)
#### Expected Behavior

When are written 2 or more letters find the User
#### How to trigger the error

1. Enable 'SEARCH_OWNERS_BY_AJAX' => true, in config/performance.php
2. Create a report and set filter to "assigned to"
#### Your Environment

- YetiForce Version used: 3.2 Stable
- Browser name and version: Chrome Latest
- Environment name and version:
- Operating System and version:

**Comment by skramanzia** [comment]
Hi @bpabiszczak the problem persists in the current stable version (v3.4).

![image](https://cloud.githubusercontent.com/assets/3030997/19251793/80cabe6c-8f17-11e6-8b58-ce6c106b2fb4.png)

**Comment by ezbank** [comment]
it still exist?

**Comment by mariuszkrzaczkowski** [comment]
Duplicate #3704
