### ISSUE TITLE
no custom function UpdateInventory in WorkFlow

### ISSUE THREAD

**Issue by ivanmar** [YetiForceCompany/YetiForceCRM#3586]
I am trying to update stock quantity in storage after creating invoice. That is handy if you don't need/want to go through all procedure. In Vtiger we had UpdateInventory custom function in WF. I can't find something similar or some other way to do this in YetiForce. Can you point me in right direction
Regards
ivan

**Comment by ousidahou** [comment]
hi me too i can't update stock quantity in storage after creating invoice.
