### ISSUE TITLE
Error when logging into gitdeveloper.yetiforce.com

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3589]
Error doesn't allow to go to tabs in the menu, e.g. to Accounts, Leads (rys 1)
Tested on gitdeveloper.yetiforce.com, version 3.3.12

[PL]
Po zalogowaniu się na gitdeveloper.yetiforce.com jest widoczny błąd (rys 1)
Błąd nie pozwala na przejście do zakładek z menu np. do kontrahenta, leada
Przypuszczam, że błąd spowodowało dodane pole DEFAULT (rys nr 2)
Testowane na gitdeveloper.yetiforce.com, wersja: 3.3.12
![270](https://cloud.githubusercontent.com/assets/11139594/18867050/e950c65e-84a2-11e6-9467-5dbe7c87bb58.png)
![270 przyczyna](https://cloud.githubusercontent.com/assets/11139594/18867308/0613ecca-84a4-11e6-97c9-851a6cba94d3.png)

**Comment by TomaszQr** [comment]
#3595
