### ISSUE TITLE
Get updated version

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#359]
Hello,
How do I get the updated version through git without having to reinstall the application? I tried git pull but there were conflicts (I had updated some files) and git wouldn't override it.

**Comment by waw555** [comment]
I also interested in this issue ???

**Comment by bpabiszczak** [comment]
If you want to upgrade CRM, please use these packages [https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%201.x.x]. It will never be possible to upgrade directly from git.

**Comment by amicheals** [comment]
How do you upload the update? via ftp? or is there somewhere in the system to perform upgrades

**Comment by bpabiszczak** [comment]
Update from git [try this: https://plus.google.com/u/0/+JoeBordes/posts/aGAgcdNoGMD]
