### ISSUE TITLE
[bug] Master V3.3.0 - Problem with new users

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3590]
#### Issue
New user cannot find any data with the search function!

#### Actual Behavior
When i create a new user, this user have no rights to find some data.
Old User before i updated the system to 3.3.0 have the correct rights.

#### Expected Behavior
The user can find any data.

#### How to trigger the error
![bug](https://cloud.githubusercontent.com/assets/10259801/18868086/376550f4-84a7-11e6-94d4-bb244e556bb6.gif)

#### Your Environment
* YetiForce Version used: gitmaster v3.3.0
* Browser name and version: chrome, ff

**Comment by SkavenKF** [comment]
I tested again on gitmaster and i can change data. (eventually i have a problem with the update files from 3.1.0 to 3.3.0)
The only problem that exists is that a new user cannot find any data. 
![bug](https://cloud.githubusercontent.com/assets/10259801/18869858/79057500-84ae-11e6-965c-544ed2c7d5e6.gif)

**Comment by vovpff** [comment]
@SkavenKF let's check your cron

**Comment by SkavenKF** [comment]
@vovpff: thanks, this was the solution (i must wait some time;-). Is this a new functionality, i can't remember that i have this problem before 3.2.0

**Comment by vovpff** [comment]
@SkavenKF this is userprivileguesupdate cron task from 3.1.xxx. The rame situation with search.

**Comment by SkavenKF** [comment]
@vovpff thanks, for the information  :thumbsup: i became a little panic after the update  :fearful:

**Comment by SkavenKF** [comment]
@bpabiszczak i see you added this to 3.3. milestone but actually we have already 3.3.28. (dev). The 3.3 milestone is still open!?

**Comment by bpabiszczak** [comment]
No. We will public YF 3.3 on Friday.
