### ISSUE TITLE
[bug] Master V3.4.0 - Show no inactive Users

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3591]
#### Issue

When i set a user "inactive", it would not be show in the list
#### Actual Behavior

inactive users are not shown
#### Expected Behavior

inactive users should be shown
#### How to trigger the error

![bug](https://cloud.githubusercontent.com/assets/10259801/18868294/f18133ae-84a7-11e6-9d3c-b1a04cba08ea.gif)
#### Your Environment
- YetiForce Version used: gitmaster v3.3.0
- Browser name and version: chrome ff

**Comment by bpabiszczak** [comment]
show me english interface....

**Comment by SkavenKF** [comment]
![bug1](https://cloud.githubusercontent.com/assets/10259801/19172048/2cacce00-8c20-11e6-8049-9082c3741224.gif)

**Comment by SkavenKF** [comment]
@bpabiszczak: Please can you check this issue. The bug also exist in 3.4  :weary:

**Comment by SkavenKF** [comment]
any news ????

**Comment by paula-w** [comment]
It works in the current version

**Comment by zeostravelling** [comment]
@SkavenKF I read everything... but is there a solution yet?

**Comment by SkavenKF** [comment]
Unfortunately not for the current release 3.4.0(21) 😞
