### ISSUE TITLE
in calendar settings starting day of the week not working

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#3592]
Hi
in calendar settings starting day of the week not working .
i changed to saturday and still graphical calendar starting on monday .
tested on ver 3.3.20

**Comment by konadrian** [comment]
If you select Saturday as the first day of the week, and set days visibility in calendar as "all", does the calendar still show the wrong first day? If so, please recreate the error in the latest  version, or send us a gif.
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/19228314/62c9291a-8ec4-11e6-9c02-d15311d86d17.png)
