### ISSUE TITLE
[bug][3.3.23] fatal error finalizing our setup

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3593]
in 3.3.0 is all ok

### How to trigger the error

1.
![captura0](https://cloud.githubusercontent.com/assets/18419851/18874843/441bb202-84bb-11e6-8bf6-3978945a50b0.PNG)

2.
![captura](https://cloud.githubusercontent.com/assets/18419851/18873973/baea2104-84b9-11e6-8291-729ee6c6888a.PNG)

#### 3. apache/logs/access.log
![captura2](https://cloud.githubusercontent.com/assets/18419851/18874609/54f8638c-84ba-11e6-8a1e-a58b8a3c3a9f.PNG)

### Your Environment

* YetiForce Version used: 3.3.23
* Browser name and version: Firefox 49.0.1
* Environment name and version: php 5.6 (XAMPP)
* Operating System and version: Windows 10 x64

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/e67e69e8df3f8ffe5fab8392e8d844276ae76e27 https://github.com/YetiForceCompany/YetiForceCRM/commit/cc8dc02c1cc87e24384dbaee042b1a51ef5c1ce9
