### ISSUE TITLE
Mail scanner - no binding email to any relations in CRM. Pleaseeee helpppppp

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3594]
#### Issue
I have problem with automatic relating recived/send email with CRM elements (contacts, account etc). It does not relate anything automatically, only have option for "Import mail manually" - and everything with manual works fine.
This is problem: 
![rimport manuallz](https://cloud.githubusercontent.com/assets/19521910/18875031/5b87276a-84c4-11e6-9114-b350ae0c8fce.png)
#### Actual Behavior
***I can send/recive emails regullary, can relate it but only manually, automatic dont work. 
***If I send email directly from contact, in Roundcube it will not be automatically related with that contact!
Cron job running regullary
![cron](https://cloud.githubusercontent.com/assets/19521910/18874825/91e2be42-84c3-11e6-9791-8627530db1d0.png)
Scanner config - In my opinion everything is set. But I guess that might be a difference
![scanner config](https://cloud.githubusercontent.com/assets/19521910/18874857/b6a262b4-84c3-11e6-84b0-995e50fe4a30.png)
![scanner](https://cloud.githubusercontent.com/assets/19521910/18874868/bf7e2f30-84c3-11e6-8104-1947195a94ee.png)

#### Expected Behavior
When email is recived, it automatically relate with contact and/or account or with other elements in CRM.

I dont know what else to do. 
Does anyone have any idea to resolve this issue..... Please helpppppppp.

#### Your Environment
* YetiForce Version used: YF 3.2 updated to RC2
* Browser name and version: Chrome, latest

Best regards

**Comment by kabelo38** [comment]
this commit worked for us https://github.com/YetiForceCompany/YetiForceCRM/commit/cdce701c873ff562816bdff7dcfe094b1d4c08a3

**Comment by mariuszkrzaczkowski** [comment]
Test latest version, yesterday were commit important changes to the scanner

**Comment by serbiaserbia** [comment]
@mariuszkrzaczkowski thanks, I will check tonight later, and bring results... Thanks again

@kabelo38  thanks for info.... I will try to update that commit
