### ISSUE TITLE
[BUG][PL]Przełączanie kont mailowych - autologowanie

### ISSUE THREAD

**Issue by nnewrulez** [YetiForceCompany/YetiForceCRM#3596]
W firmie funkcjonuje kilka kont i zgodnie z instrukcjami dodałem dla każdego z użytkowników kontra wraz z konfiguracją, problem pojawia się gdy jeden użytkownik ma posiadać dostęp do więcej niż jednego konta, bo pomimo prawidłowo skonfigurowanego autologowania i dostępu do kont po wybraniu z górnej belki innego konta mailowego zostaje konto główne. Testowane było to na naszych 2 wersjach lokalnych oraz waszej wersji developerskiej (dodalismy konto testyeti123@gmail.com) 

Testowaliśmy na waszej dev od 00:00  28-09-2016

**Comment by bpabiszczak** [comment]
Proszę o nagranie filmu za pomocą https://screentogif.codeplex.com/. W mojej opinii mechanizm ten działa poprawnie w najnowszej wersji na gitdeveloper.
