### ISSUE TITLE
Incorrect value of date format in the graphic calendar

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3599]
Tested on gitdeveloper.yetiforce.com, version:  3.3.30 
Instructions:
1. Go to Users. Preview a record.
2. Quickly edit date format to dd/mm/yyyy.
3. Go to calendar. Hover the cursor over added event.
4. See the screen shot for error message.

[PL]
Nieprawidłowy zapis „Formatu daty” w kalendarzu graficznym
Testowane na gitdeveloper.yetiforce.com, wersja:  3.3.30
Instrukcje:
1. Przejdź do Użytkowników. Wykonaj podgląd rekordu.
2. Wykonaj szybką edycję Formatu daty na dd/mm/yyyy.
3. Przejdź do kalendarza. Najedź kursorem myszy na dodane wydarzenie w nim.
4. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
![275](https://cloud.githubusercontent.com/assets/11139594/18905798/1dcba634-8565-11e6-80f1-2984336edb3b.png)

**Comment by rskrzypczak** [comment]
duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/3609
