### ISSUE TITLE
OSS Mail dont Conect with my webmail server.

### ISSUE THREAD

**Issue by VSecurity** [YetiForceCompany/YetiForceCRM#36]
I use roundcube to read my emails, when I configure my server email on OSSMail and try to login on My Mail Box 	It doesn't work, stay loading and after some minutes nothing happens

**Comment by mariuszkrzaczkowski** [comment]
Please call an error at test.yetiforce.com so we will be able to find it.

**Comment by amicheals** [comment]
I am starting to have this problem now. Is there a log I can check?

**Comment by amicheals** [comment]
I fixed this by opening the correct ports through the firewall. I have csf configured and I needed to open gmail's ports in TCP In and oUt
