### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by Jibe9191** [YetiForceCompany/YetiForceCRM#360]
I create a new custom module and added Widgets but the widget are not showing when data is create with the custom module.

kindly advise.

Thank you.

**Comment by bpabiszczak** [comment]
Unfortunately, I don’t quite understand this issue. I request the following:

A step-by-step description how I can test for this error [which widget was added to which module].
Please send links [where did you add the widget and where are you trying to see it].
Test for the error on our testing version: https://test.yetiforce.com/
Add screenshots if possible.
We are not able to help without this info.

**Comment by waw555** [comment]
Example

Add new module

![newsmodule1](https://cloud.githubusercontent.com/assets/1402355/6800175/f60d327e-d23d-11e4-9ede-6448bc3ac0af.JPG)

Enabled

![newsmodule2](https://cloud.githubusercontent.com/assets/1402355/6800179/fcfcb186-d23d-11e4-8413-0781569cecfe.JPG)

Add Widget for home page

![newsmodule3](https://cloud.githubusercontent.com/assets/1402355/6800188/0d8c5934-d23e-11e4-93a3-7d581c21a2d1.JPG)

Add Widget for Details Summary page

![newsmodule4](https://cloud.githubusercontent.com/assets/1402355/6800201/211547cc-d23e-11e4-8c1c-5c9aeb49e7b0.JPG)

Don't Work Details Summry Page

![newsmodule5](https://cloud.githubusercontent.com/assets/1402355/6800207/353f8410-d23e-11e4-9e38-60ccb6f52d15.JPG)

Infinity Load Home Page

![newsmodule6](https://cloud.githubusercontent.com/assets/1402355/6800223/50a8c4be-d23e-11e4-9c09-d685cfdf1603.JPG)

**Comment by Jibe9191** [comment]
I have followed the steps, however the widget do not show on custom module that i have created. Please see image attached
![gith](https://cloud.githubusercontent.com/assets/3746986/6806824/63a79a2e-d24b-11e4-96bf-5419def35b3c.png)
![organizations](https://cloud.githubusercontent.com/assets/3746986/6806825/63e29e76-d24b-11e4-865d-2047c8f60694.png)
![sim](https://cloud.githubusercontent.com/assets/3746986/6806827/63e939c0-d24b-11e4-8acb-99e456caa481.png)
![sim2](https://cloud.githubusercontent.com/assets/3746986/6806826/63e2e002-d24b-11e4-8f4d-ff92b681cf6e.png)

**Comment by bpabiszczak** [comment]
waw555

Adding a new module doesn't create "Details Summary Page" automatically. We will check that and delete this view or add a possibility to create this view when creating a module. So it will not work for new modules because they don't have such view!

Jibe9191

Please update your version and check it on the new one. Additionaly, please add such widget on our testing version and describe in details what you add, where and what is wrong.

**Comment by Jibe9191** [comment]
Am currently testing with ver. 1.4.217 RC and having the same issue

**Comment by bpabiszczak** [comment]
"Additionaly, please add such widget on our testing version and describe in details what you add, where and what is wrong."
