### ISSUE TITLE
Email account is viewable by anyone who logs in to yetiforce

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3600]
I am not sure if this problem is just with my system so if others could check it would be appreciated.
#### Issue

I have just discovered that if I don't log out of my email, anyone who logs into the crm (from anywhere) can view my email on their system - regardless of what application they use.
#### Actual Behavior

If I log in to my email, then log out of yetiforce, then log in on another device as a different user, when I click on email, it is already logged in to the other user's email account.
#### Expected Behavior

When I log in to yetiforce and also log in to the email, only I should be able to see my emails. Even if I don't log out, no other user should be able to see my emails. In addition, When I log out of yetiforce, it should also log me out on the email system.
#### How to trigger the error

Open your crm and email in Chrome as one user then log out, then open another instance up in say Firefox as a different user and click on email - the last opened email account is still available on screen.

**Comment by PercyP** [comment]
Is this issue only with my setup? Has anyone else found they have this problem?

**Comment by paula-w** [comment]
Can you check if the error also exists in the gitdeveloper version?

**Comment by PercyP** [comment]
@paula-w 

I have just tried it on the demo site and the problem is with that too. It was already logged in to email. Next I created a new user account, then I logged out of the demo account and logged back in with the new user details, then I clicked on Virtual Desk and My Email and it was already open with the same account as in Demo.

Percy

**Comment by nic86** [comment]
same error in version: 3.1

**Comment by PercyP** [comment]
Update: I have now installed Yetiforce 3.4 plus hotfix and now testing this mail issue on latest version. It still appears to be a problem. 

I have also tried turning off autologin, and in mail scanner, ensuring that only the user of the Username email address is selected in the User section. None of these settings have any impact.

When in email, I am able to select any email address from the dropdown at top right of email window. Whichever I select, it displays the last opened email account whether I am signed in as admin or regular user.

Also, there doesn't appear to be a logout button like on older versions inside email.

**Comment by nic86** [comment]
![gifrecord_2016-10-13_154117](https://cloud.githubusercontent.com/assets/18703633/19351353/bacc1f16-915b-11e6-81ef-88666b470991.gif)

email autologin is active for user demo but not for user demo2(role sales manager - no admin).
when logout with user demo and relogin with user demo2 i can see the email of user demo.

**Comment by PercyP** [comment]
I have tried with other email accounts - logging in and the logging off and signing in as someone else, it seems to open the same email account every time - basically whoever is currently logged in to an email account.

**Comment by PercyP** [comment]
Hi,

is there any update/feedback on this?

Kind regards

Percy

**Comment by bpabiszczak** [comment]
The problem has been resolved in version 4.0.

**Comment by akiyoshik** [comment]
I am having the same issue with version 4.4.0 as well. If I don't logout from my email, next user who just login to Yetiforce can see my email.

**Comment by mariuszkrzaczkowski** [comment]
fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/8589
