### ISSUE TITLE
Cannot change data format in Emails

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3603]
Tested on gitdeveloper.yetiforce.com, version: 3.3.30 
Instructions:
1. Change data format to dd-mm-rrrr
2. Go to Accounts > Emails > magnifying glass icon (second)
3. See the screen shot for error message: 2016-10-05.

[PL]
Nie działa zmiana formatu daty w Emaile
Testowane na gitdeveloper.yetiforce.com, wersja:  3.3.30
Instrukcje:
1. Zmień format daty poprzez szybką edycję na: dd-mm-rrrr.
2. Przejdź do Kontrahenta > emaile> ikona lupa (druga).
3. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu: 2016-10-05.
![280](https://cloud.githubusercontent.com/assets/11139594/18909152/c7ffeed2-8572-11e6-8b58-69082e5493c4.png)

**Comment by TomaszQr** [comment]
Duplicate #3606
