### ISSUE TITLE
Error appears when you click on the buttons: Forward, Reply all

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3605]
Tested on gitdeveloper.yetiforce.com, version: 3.3.33 
Instructions:
1. Go to Accounts > Emails > magnifying glass icon (second)
2.  See the screen shot for error message:  HTTP ERROR 500

[pl]
Błąd pojawił się po kliknięciu na przyciski: Przekaż, Odpowiedź wszystkim
Testowane na gitdeveloper.yetiforce.com, wersja:  3.3.33
Instrukcje:
1. Przejdź do Kontrahenta > Emaile> ikona lupa (druga).
2. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu: HTTP ERROR 500
![282](https://cloud.githubusercontent.com/assets/11139594/18910063/a41eea5a-8576-11e6-81aa-d9cd4acb6904.png)

**Comment by TomaszQr** [comment]
The error doesn't exist in the current version
