### ISSUE TITLE
[BUG] Detail Report Error

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3608]
#### Issue

Similar error was corrected in Chart Report. https://github.com/YetiForceCompany/YetiForceCRM/issues/3565
#### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/3030997/18926020/8846488a-858c-11e6-8cfd-6407b5543760.png)
#### How to trigger the error

1. Go to Reports.
2. Add a Detail Report.
3. Enter values and proceed.
#### Your Environment

- YetiForce Version used:  3.3.39
- Browser name and version: Chrome Latest
- Environment name and version: Dev
- Operating System and version:

**Comment by ezbank** [comment]
So many bugs. Hjx hjx

**Comment by paula-w** [comment]
Can you show us what values you entered in each stage?

**Comment by skramanzia** [comment]
Sure @paula-w 

Create A Realted field with Contact in Tickets for example 

![image](https://cloud.githubusercontent.com/assets/3030997/18994505/8207ac20-86fe-11e6-9e1c-ac797cf2eb2d.png)
---------

Set Tom Contact (i write Tom) in some ticket.
![image](https://cloud.githubusercontent.com/assets/3030997/18994536/af7bd97e-86fe-11e6-9d21-7729a0f04e5e.png)

if I click on the magnifying glass
![image](https://cloud.githubusercontent.com/assets/3030997/18994552/bda069a2-86fe-11e6-8e24-ed67b6762e26.png)

Create Report to Ticket
![image](https://cloud.githubusercontent.com/assets/3030997/18994585/da79cc4e-86fe-11e6-899c-205f18f63cfe.png)

and when generated it

![image](https://cloud.githubusercontent.com/assets/3030997/18994603/ebc3b334-86fe-11e6-86e2-3bc7bf49a5c9.png)

**Comment by skramanzia** [comment]
Hi @bpabiszczak and @paula-w here more information

![m0subdjgnv](https://cloud.githubusercontent.com/assets/3030997/19359806/24439992-9152-11e6-9fbd-33941d064691.gif)
