### ISSUE TITLE
Error test.yetiforce.com

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#361]
![test yetiforce com](https://cloud.githubusercontent.com/assets/1402355/6626465/8ba430d2-c918-11e4-93ac-6600d1926591.PNG)

**Comment by mariuszkrzaczkowski** [comment]
Fixed

**Comment by waw555** [comment]
another error

Open User Settings
![test yetiforce com user](https://cloud.githubusercontent.com/assets/1402355/6627178/fe926c80-c91d-11e4-911f-4f7b1b59d862.PNG)

Click Breadcrumbs

Result

![test yetiforce com user2](https://cloud.githubusercontent.com/assets/1402355/6627191/1773f502-c91e-11e4-9554-09024b1c6206.PNG)

**Comment by waw555** [comment]
https://test.yetiforce.com/My%20Home%20Page

Not Found

The requested URL /My Home Page was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Apache/2 Server at test.yetiforce.com Port 443

**Comment by waw555** [comment]
![test yetiforce com calculation](https://cloud.githubusercontent.com/assets/1402355/6627238/934e459c-c91e-11e4-9f72-4c87e060c641.PNG)

**Comment by waw555** [comment]
![test yetiforce com project diagramm](https://cloud.githubusercontent.com/assets/1402355/6627299/1506edaa-c91f-11e4-9277-521d6b05904d.PNG)

**Comment by SergeyDjam** [comment]
back
