### ISSUE TITLE
Cannot change data, time format in Letters incoming, Letters outgoing

### ISSUE THREAD

**Issue by GorskaAnna** [YetiForceCompany/YetiForceCRM#3610]
Tested on gitdeveloper.yetiforce.com, version: 3.3.41
Instructions:
1. Change data format to: yyyy/mm/dd.
2. Go to Letters incoming, Letters outgoing.
3. See the screen shot for error message.

[PL]
Nie działa zmiana formatu daty, godziny  w listach przychodzących, wychodzących.
Testowane na gitdeveloper.yetiforce.com, wersja:  3.3.41
Instrukcje:
1. Zmień format daty poprzez szybką edycję np. na: yyyy/mm/dd. 
2. Przejdź do listy przychodzące, listy wychodzące.
3. Zobacz zrzut ekranu, na którym widoczna jest wiadomość błędu.
W listach – nie działa żadna zmiana formatu daty i godziny
![287 lis wych](https://cloud.githubusercontent.com/assets/11139594/18946248/58969de0-862e-11e6-890b-e15b840ad2dd.png)
![287 lis prz](https://cloud.githubusercontent.com/assets/11139594/18946259/5e7f4c16-862e-11e6-9310-3b9c2b121d04.png)

**Comment by TomaszQr** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/2954cd28f4348ac2d3c9930a8feae4fae31e98ba
