### ISSUE TITLE
Version 3.3 download?

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3611]
I think I missed something. 

Installed 29.08  version 3.2, and waiting for 3.3ver for clean install, but dont see milestone and no  download in Releases.  Am I missed something? 

Before 3day I updated 3.2to3.3rc2.  Now I see update 3.2to3.3rc3 ,   and update 3.3 to 3.4rc3.
I dont know what to update,  download, install?  Fresh clean 3.3?

**Comment by PercyP** [comment]
Hi,

where are those updates? I am working from this folder:

https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x 

I only see v3.3.0RC and v3.4.0RC 

I can't get the upgrade to work. Is this where you are downloading yours from? Have yours installed successfully?

Percy

**Comment by serbiaserbia** [comment]
Hi @PercyP 

Before about 10 days was only available RC2 and upgraded from same web address 3.2 to 3.3RC2.

The only difference between you and me is that I had upgrade 3.3RC2

After that I tried to upgrade to 3.3RC3 but it reported an error because it is already installed version 3.3 and version 3.2 is required.
I skipped 3.3RC. Then upgraded to version 3.4RC and it was successful. Now works as a version 3.4RC.

Do we need to wait for version 3.3 without the RC? What is the milestone for it? Do you have any idea?

I have the impression that something is messed up with versions.


Regards.

**Comment by bpabiszczak** [comment]
Version 3.3 and 3.4 will be published on Monday.
