### ISSUE TITLE
[PL]Powiązanie Kampania marketingowa - > Szansa sprzedaży

### ISSUE THREAD

**Issue by yetitest** [YetiForceCompany/YetiForceCRM#3614]
#### Issue

Brak powiązania prowadzonych kampanii marketingowych z szansami sprzedaży. Przez co działania marketingowe nie przekładają się na prowadzone lub nowe szanse sprzedaży.  Powiązanie występowało wcześniej w systemie vTiger. 

#### Your Environment

* YetiForce Version used: 3.2.0
* Browser name and version: Chrome 55

**Comment by bpabiszczak** [comment]
Już jest w nowej wersji. https://gitdeveloper.yetiforce.com/index.php?module=SSalesProcesses&view=Edit
