### ISSUE TITLE
[PL]Jedna Szansa sprzedaży przypisana do wielu kontrahentów

### ISSUE THREAD

**Issue by yetitest** [YetiForceCompany/YetiForceCRM#3615]
#### Issue

Możliwość przypisania do jednej szansy sprzedaży kilku kontrahentów którzy wspólnie uczestniczą w projekcie. Istnieje możliwość przypisania wielu kontaktów, czy byłaby możliwość również przypisania wielu kontrahentów?

Najlepiej, aby jednocześnie tworzyło się powiązanie każdego z tych kontrahentów z daną szansą sprzedaży.

#### Your Environment

* YetiForce Version used: 3.2.0.

**Comment by bpabiszczak** [comment]
Nie planujemy dodania takiej funkcjonalności na chwilę obecną.
https://yetiforce.com/pl/github/issues/203-pomys%C5%82y-zwi%C4%85zane-z-rozwojem-systemu.html
