### ISSUE TITLE
Missing Excel export

### ISSUE THREAD

**Issue by acidhunter** [YetiForceCompany/YetiForceCRM#3616]
Version Latest stable 3.3.21

There is no button anymore to export excel files in list view and reports

Excel export is important because the csv files are not correct rendered in excel

**Comment by mcules** [comment]
You have to manualy load the PHPExcel library to your /libraries Folder.

**Comment by WalterLuis** [comment]
check lib_PHPExel in https://github.com/YetiForceCompany

**Comment by paula-w** [comment]
Hi guys, please wait for the official announcement about new releases, it will include a manual and all the basic info.

**Comment by bpabiszczak** [comment]
Look at new panel on git version: https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8
