### ISSUE TITLE
Moving location of the currency symbol

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3617]
Hi all, For some reason the currency appears at the right side of the invoice after the amount. I know in the some countries this is normal but in the UK it's before the Amount.

Here is a picture to show you.
![capture](https://cloud.githubusercontent.com/assets/22075161/18995830/ef569102-8725-11e6-9710-ff307d6fbe23.GIF)

**Comment by alextovey** [comment]
Hi @bpabiszczak any luck with the movement of the £ symbol? I've did a fresh install and almost all my errors have gone using your dev version but the £ symbol is still in the wrong position?

**Comment by alextovey** [comment]
Why was this closed? I'' reporting a bug?

**Comment by bpabiszczak** [comment]
solution: https://github.com/YetiForceCompany/YetiForceCRM/commit/032af2b53aa7d5025a2a33545d50a2a7ce0e7a21

**Comment by alextovey** [comment]
That didn't fix the issue. still have it.

**Comment by mariuszkrzaczkowski** [comment]
Check 
![image](https://cloud.githubusercontent.com/assets/10198654/19494596/26733146-9580-11e6-8fda-5f6460cf5446.png)

https://gitdeveloper.yetiforce.com/index.php?module=SQuotes&view=Detail&record=1235&mode=showDetailViewByMode&requestMode=full&tab_label=LBL_RECORD_DETAILS

**Comment by alextovey** [comment]
![capture](https://cloud.githubusercontent.com/assets/22075161/19494781/8b22f872-9578-11e6-969a-605e08f61b11.GIF)

On the invoice its not showing the correct way. I've checked 3 times on different browsers and user settings. Also It's missing the £ from the amounts too. Is there some code I can inject to fix this please? I appreciate the help and quick response.

**Comment by alextovey** [comment]
@bpabiszczak @mariuszkrzaczkowski fixed it by editing modules/Vtiger/pdfs/special_functions/TableTaxSummary.php
Below is what i've changed.`										<td class="textAlignRight tBorder" width="70px">' . $key . '%</td>
										<td class="textAlignRight tBorder">' . CurrencyField::convertToUserFormat($tax, null, true) . ' ' . $currencySymbolRate['symbol'] . '</td>
									</tr>';
				}
				$html .= '<tr>
									<td class="textAlignRight tBorder" width="70px">' . vtranslate('LBL_AMOUNT', $module) . '</td>
									<td class="textAlignRight tBorder">' . CurrencyField::convertToUserFormat($tax_AMOUNT, null, true) . ' ' . $currencySymbolRate['symbol'] . '</td>
								</tr>
							</tbody>
						</table>
					</div>';

				if (in_array('currency', $columns) && $baseCurrency['id'] != $currency) {
					$RATE = $baseCurrency['conversion_rate'] / $currencySymbolRate['rate'];
					$html .= '<br /><table class="pTable colapseBorder">
								<thead>
									<tr>
										<th colspan="2" class="tBorder noBottomBorder tHeader">
											<strong>' . vtranslate('LBL_CURRENCIES_SUMMARY', $module) . '</strong>
										</th>
									</tr>
								</thead>
								<tbody>';
					foreach ($taxes as $key => &$tax) {
						$currencyAmount += $tax;
						$html .= '<tr>
									<td class="textAlignRight tBorder" width="70px">' . $key . '%</td>
									<td class="textAlignRight tBorder">' . CurrencyField::convertToUserFormat($tax * $RATE, null, true) . ' ' . $baseCurrency['currency_symbol'] . '</td>
								</tr>';
					}
					$html .= '<tr>
								<td class="textAlignRight tBorder" width="70px">' . vtranslate('LBL_AMOUNT', $module) . '</td>
								<td class="textAlignRight tBorder">' . CurrencyField::convertToUserFormat($currencyAmount * $RATE, null, true) . ' ' . $baseCurrency['currency_symbol'] . '</td>
							</tr>
						</tbody>
					</table>';`

**Comment by alextovey** [comment]
Lines 68 - 101

**Comment by paula-w** [comment]
@alextovey Could you send us these changes in a pull request?

**Comment by alextovey** [comment]
@paula-w Done. also If i purchase support does it allow custom building of modules the way I'd like it to work?

**Comment by paula-w** [comment]
Yes, but the best idea in this case is to send us an email to either info@yetiforce.com or help@yetiforce.com, and describe in detail what your requirements are. Then we'll be able to provide you with the estimated time needed to complete the task.

**Comment by z0lo13** [comment]
why dont you make any changes regarding that? the position of symbol is still not changable.
