### ISSUE TITLE
Password Module  unable to save records

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3618]
![error_password](https://cloud.githubusercontent.com/assets/21319919/19001744/579231aa-8766-11e6-88e6-7f3eea63f11c.gif)

#### Issue

Password Module - not working
#### Actual Behavior

![error_password](https://cloud.githubusercontent.com/assets/21319919/19001765/79cf0ae0-8766-11e6-9ae9-4b6c2a55b470.gif)
While filling up fields in password module - it is showing as "Password too long"

#### Expected Behavior

It should be able to accept and save record

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.2
* Browser name and version: Chrome
* Environment name and version: 3.2
* Operating System and version: windows

**Comment by jstorchia** [comment]
i have the same issue

**Comment by kpaulaha** [comment]
At least in v. 3.2.308+ it works ok.
