### ISSUE TITLE
Upgraded from 3.2.0 to 3.3.0RC and get white screens

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3619]
Hi,

I have just tried to upgrade to version 3.3. I have ensured the version.php is set to 3.2.0 and then uploaded the 3.3.0RC. After it uploads and installs it goes to the home page but with a white page, no widgets etc. Same when I click on any other screen. 

I also noticed there is an update package for 3.4.0RC should we be upgrading to this straight after? 

Kind regards

Percy

**Comment by serbiaserbia** [comment]
Does the major versions (eg. 3.4RC3) have all code changes as in the lower versions (eg. 3.3RC3)?
  whether it is necessary to go 3.2**->**3.3**->**3.4RC or be directly 3.2**->**3.4RC

It is good to know.

**Comment by PercyP** [comment]
@serbiaserbia 

I have tried both options. Going from 3.2 to 3.3RC produces the white screen and then no option to upgrade over that as the configuration areas also have white screens - only the menus remain working. I then tried to go straight to 3.4rc this at least goes through to say it was successfully installed but then throws an error 500.

Neither options work for me. I am guessing we must need to upgrade one version at a time, but its unfortunately not allowing me to do that. 

Did you change the version numbers to do your upgrade? I jst left mine at 3.2.0 maybe I should try it by changing it to 3.3.0RC?

**Comment by rskrzypczak** [comment]
if you have white screen - upgrade is not complete(probably).
In order to verify problems or errors it is necessary to enable logs and the display of server messages ([info](https://yetiforce.com/en/developer-documentation/engine/115-debugging.html)).
[link](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/.htaccess#L23) - log_errors, display_errors - on
[link](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/debug.php#L13) - DISPLAY_DEBUG_BACKTRACE, SQL_DIE_ON_ERROR (LOG4PHP_DEBUG) - true

**Comment by PercyP** [comment]
Hi @rskrzypczak 

This what I have done so far, and do not see any errors on the front end still:

1. **Changed the debug.php as follows:**

`<?php
/* {[The file is published on the basis of YetiForce Public License that can be found in the following directory: licenses/License.html]} */

$DEBUG_CONFIG = [
	/* +***************************************************************
	 * 	CRM 
	 * ************************************************************** */
	// Enable log4php -> cache/logs/system.log
	'LOG4PHP_DEBUG' => true,
	// Stop the running process of the system if there is and error in sql query
	'SQL_DIE_ON_ERROR' => true,
	// Displays information about the tracking code when an error occurs. Available only with the active SQL_DIE_ON_ERROR = true
	'DISPLAY_DEBUG_BACKTRACE' => true,
	// Debug Viewer => cache/logs/viewer-debug.log
	'DEBUG_VIEWER' => false,
	// Display Smarty Debug Console
	'DISPLAY_DEBUG_VIEWER' => false,
	// Display Main Debug Console
	'DISPLAY_DEBUG_CONSOLE' => false,
	/* +***************************************************************
	 * Configure a user-defined error handler function
	 * ************************************************************** */
	'EXCEPTION_ERROR_HANDLER' => false,
	// Save logs to file (cache/logs/errors.log)
	'EXCEPTION_ERROR_TO_FILE' => false,
	// Display errors
	'EXCEPTION_ERROR_TO_SHOW' => false,
	// Set the error reporting level. The parameter is either an integer representing a bit field, or named constants.  
	// https://secure.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting
	// All errors - E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
	// Critical errors - E_ERROR | E_WARNING | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR
	'EXCEPTION_ERROR_LEVEL' => E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED,
	/* +***************************************************************
	 * 	API 
	 * ************************************************************** */
	// Sabre dav - This is a flag that allow or not showing file, line and code of the exception in the returned XML
	'DAV_DEBUG_EXCEPTIONS' => false,
	// Activate the plugin recording log in DAV
	'DAV_DEBUG_PLUGIN' => false,
	// Show errors messages in web service
	'WEBSERVICE_SHOW_ERROR' => false,
	// web service logs
	'WEBSERVICE_DEBUG' => false,
	/* +***************************************************************
	 * 	ROUNDCUBE MAIL
	 * ************************************************************** */
	// System error reporting, sum of: 1 = log; 4 = show, 8 = trace
	'ROUNDCUBE_DEBUG_LEVEL' => 1,
	// Devel_mode this will print real PHP memory usage into logs/console and do not compress JS libraries
	'ROUNDCUBE_DEVEL_MODE' => false,
	// Activate this option if logs should be written to per-user directories.
	// Data will only be logged if a directry cache/logs/<username>/ exists and is writable.
	'ROUNDCUBE_PER_USER_LOGGING' => false,
	// Log sent messages to cache/logs/sendmail or to syslog
	'ROUNDCUBE_SMTP_LOG' => false,
	// Log successful/failed logins to cache/logs/userlogins or to syslog
	'ROUNDCUBE_LOG_LOGINS' => false,
	// Log session authentication errors to cache/logs/session or to syslog
	'ROUNDCUBE_LOG_SESSION' => false,
	// Log SQL queries to cache/logs/sql or to syslog
	'ROUNDCUBE_SQL_DEBUG' => false,
	// Log IMAP conversation to cache/logs/imap or to syslog
	'ROUNDCUBE_IMAP_DEBUG' => false,
	// Log LDAP conversation to cache/logs/ldap or to syslog
	'ROUNDCUBE_LDAP_DEBUG' => false,
	// Log SMTP conversation to cache/logs/smtp or to syslog
	'ROUNDCUBE_SMTP_DEBUG' => false,
];`

2. **my .htaccess I changed as follows:**

`RedirectMatch 403 (?i).*\.log$

<IfModule mod_autoindex.c>
	Options -Indexes
</ifModule>
########################
<IfModule mod_rewrite.c>
	Options +FollowSymLinks
	RewriteEngine On
	RewriteRule ^favicon.ico layouts/basic/skins/images/favicon.ico [L,NC]
	RewriteRule ^api/webservice/(.*)/(.*)/(.*)$ api/webservice.php?module=$1&action=$2&record=$3 [QSA,NC,L]
	RewriteRule ^api/webservice/(.*)/(.*)$ api/webservice.php?module=$1&action=$2 [QSA,NC,L]
	RewriteRule ^api/webservice/(.*)$ api/webservice.php?module=$1 [QSA,NC,L]

	RewriteRule ^\.well-known/carddav /api/dav.php/addressbooks/ [R]
	RewriteRule ^\.well-known/caldav /api/dav.php/calendars/ [R]
	RewriteRule /.well-known/carddav /api/dav.php/addressbooks/ [R,L]
	RewriteRule /.well-known/caldav /api/dav.php/calendars/ [R,L]
	RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
</ifModule>
<IfModule mod_php5.c>
	php_flag	log_errors					On
	php_flag	display_errors				On
	php_value	memory_limit				512M
	php_flag	output_buffering			On
	php_flag    zlib.output_compression		Off
	php_flag	file_uploads				On

	#php_value	max_execution_time			600
	#php_value	max_input_time				600

	php_flag	magic_quotes_gpc			Off
	php_flag	magic_quotes_runtime        Off

	php_value	suhosin.request.max_vars	5000
	php_value	suhosin.post.max_vars		5000
	php_flag	suhosin.session.encrypt		Off

	php_flag	session.auto_start			Off
	# 86400 = 3600*24
	php_value	session.gc_maxlifetime		86400 
	# 1440 = 60*24
	php_value	session.cache_expire		1440
	php_value	session.gc_divisor			500
	php_value	session.gc_probability		1

	php_value	session.save_path			cache/session
	php_value	error_log					cache/logs/phpError.log
</IfModule>
<IfModule fcgid_module.c>
	FcgidIOTimeout 600
	FcgidConnectTimeout 600
	FcgidBusyTimeout 600
	FcgidIdleTimeout 600
</IfModule>
########################
# <FilesMatch "\.(inc|php|php3|php4|php5|php6|phtml|phps)$">
# AddHandler x-httpd-php56 .inc .php .php3 .php4 .php5 .php6 .phtml
# </FilesMatch>
`
3. **My php in the root of my website folder (outside of yetifircecrm) folder looks like:**

`upload_tmp_dir = /home/mysite/public_html/tmp
magic_quotes_gpc = Off
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
log_errors = On
display_startup_errors = Off
upload_max_filesize = 1000M
post_max_size = 2000M
memory_limit = 2000M
max_execution_time = 30000
safe_mode = Off
max_input_time = 6000 
max_input_vars = 6000 
connect_timeout = 120
display_errors = On
file_uploads = On
output_buffering = Off
register_globals = Off
short_open_tag = Off
magic_quotes_sybase = Off
magic_quotes_runtime = Off
extension=pdo.so
extension=pdo_sqlite.so
extension=sqlite.so
extension=pdo_mysql.so`


My version number in version.php is set to 3.2.0

When I run the upgrade, I am presented with a blank screen on all pages - no error messages.

I am not sure what else I should do to display the errors. I noticed when I looked in cache/the only log file that has any content is the system.log

**Comment by Raggazzoo** [comment]
I had the same problem, it is solved with 3.3.0 RC5 update package.

**Comment by PercyP** [comment]
@Raggazzoo 

I just tried, its sadly not resolved for me.

**Comment by jstorchia** [comment]
same here after update 3.3 
![image](https://cloud.githubusercontent.com/assets/20776230/19163670/4b17af6a-8bd3-11e6-951d-999979f8f059.png)

**Comment by bpabiszczak** [comment]
http://stackoverflow.com/questions/4731364/internal-error-500-apache-but-nothing-in-the-logs

**Comment by bpabiszczak** [comment]
Without logs we cannt help.
https://yetiforce.com/en/developer-documentation/engine/115-debugging.html

**Comment by serbiaserbia** [comment]
@PercyP 
I did not change version anywhere. I did not know where I should do it.
When is important to change version number? When downgrade example from 3.4RC to 3.3Final?
Where is file where is need change? It is good to know?

**Comment by PercyP** [comment]
@serbiaserbia 

I dont think you need to change the version if it is already on 3.2.0 and then you are upgrading to 3.3.0RC5 it should just upgrade.

I have just tried with a totally fresh 3.2.0 then used the upgrade - still white screen and no errors reporting. Now I am just trying to upgrade php from 5.5 to 5.6 to see if that makes a difference. What version php do you have?

**Comment by PercyP** [comment]
forgot, version.php in config folder is what you need to change if you on none major version

**Comment by hipernet** [comment]
u mnie 3.2 do 3.3.0 rc5 nie aktualizuje sie zablokowany po aktualizacji

**Comment by hipernet** [comment]
http://crm.hipernet.com.pl/index.php#

**Comment by PercyP** [comment]
Ok,

finally got it working. It was PHP errors in my case. I was also on php.5.5. Here is what I did:

1. Updated my EasyApache to php 5.6
2. Made sure my php.ini was set exactly as specified in yetiforce instructions:

safe_mode: off
display_errors: off
file_uploads: on
register_globals: on
output_buffering: on
max_execution_time: 600 - the more, the better.
max_input_time: 600 - the more, the better.
default_socket_timeout: 600
mysql.connect_timeout: 600
memory_limit: 512M - the more, the better.
error_reporting: E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
log_errors: off
short_open_tag: On
register_globals: On
max_input_vars 5000
post_max_size 50M
upload_max_filesize 50M
max_allowed_packet 10M
magic_quotes_gpc Disabled
magic_quotes_runtime Disabled
zlib.output_compression Disabled
zend.ze1_compatibility_mode Disabled
session.auto_start Disabled
magic_quotes_sybase Disabled
session.gc_maxlifetime 21600
session.gc_divisor 500
session.gc_probability 1
suhosin.request.max_vars 5000
suhosin.post.max_vars 5000
suhosin.session.encrypt Off

Now it works perfectly. Note if adding to php.ini you need to replace Disabled with = Off and there needs to be an = before the other values i.e.:
suhosin.session.encrypt = Off
magic_quotes_runtime = Off

**Comment by PercyP** [comment]
I just tried updating on a shared host package and have managed to get error reporting to work. In this I get a blank screen with the following error:

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /home/sites/mysite.com/public_html/yetiforce/modules/Settings/ModuleManager/models/Library.php on line 18

This is what is on line 18 and I can't see an error:

public static $tempDir = 'cache' . DIRECTORY_SEPARATOR . 'upload';

**Comment by rskrzypczak** [comment]
The error you showed is not an error in php5.6
Minimal php version for YetiForce 3.3.0 and higher is 5.6

**Comment by hipernet** [comment]
Mam ten sam problem 3.2 do 3.3 update  podczas aktualizacji system się blokuje

**Comment by hipernet** [comment]
# pojawia sie na końcu odnośnika

http://............#
