### ISSUE TITLE
[PL]Tworzenie własnych filtrów

### ISSUE THREAD

**Issue by yetitest** [YetiForceCompany/YetiForceCRM#3622]
#### Issue

Tworzenie własnych filtrów użytkowników w modułach Szanse Sprzedaży oraz Oferty
Użytkownik nie ma opcji stwórz filtr:
![bez tytulu1](https://cloud.githubusercontent.com/assets/22539294/19030559/efa29fd6-894e-11e6-87ad-8d0be237b02e.png)

Jeśli wybierzemy w jego profilu że jest administratorem
![bez tytulu3](https://cloud.githubusercontent.com/assets/22539294/19030575/fea07594-894e-11e6-90ff-12b9959dda93.png)

Wtedy ma możliwość stworzenia swojego filtru
![bez tytulu2](https://cloud.githubusercontent.com/assets/22539294/19030585/0d4a0a1a-894f-11e6-8e0d-77ac29836f44.png)

#### Expected Behavior

Nadanie możliwości zwykłym użytkownikom systemu tworzenia własnych filtrów w Szansie Sprzedaży oraz Ofertach.

#### Your Environment

* YetiForce Version used: 3.2.0
* Browser name and version: Chrome 55
* Operating System and version: Windows 10

**Comment by bpabiszczak** [comment]
Definiuje się to w profilach kto może a kto nie.

**Comment by yetitest** [comment]
Ustawienia z profilu:

![profil](https://cloud.githubusercontent.com/assets/22539294/19030810/91c45786-8950-11e6-8f8c-9aad47560c19.png)

**Comment by bpabiszczak** [comment]
![image](https://cloud.githubusercontent.com/assets/10197525/19030920/2f847faa-8951-11e6-800a-648d28eba1a4.png)

**Comment by yetitest** [comment]
U nas brak takiej opcji w profilu:

![profil](https://cloud.githubusercontent.com/assets/22539294/19031160/b984439c-8952-11e6-9ebe-2e14ce8d3710.png)

**Comment by bpabiszczak** [comment]
zostało to dodane w nowej wersji [można samemu dodać od strony programistycznej ale trzeba wiedzieć jak], po aktualizacji do nowej wersji [dzisiaj lub jutro publikujemy dwie wersje jednocześnie 3.3 i 3.4] pojawią się te narzędzia.

**Comment by yetitest** [comment]
Ok, dzięki.
