### ISSUE TITLE
Missing possibility to ul images to PDF

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3623]
#### Issue
When creating pdf, you got not possibility to upload images

#### Actual Behavior 
(Sorry, Finnish browser)
![2016-10-03 11_50_41-pdf](https://cloud.githubusercontent.com/assets/10330264/19032184/fd532d78-8960-11e6-89c5-3fd85de70be4.png)

#### Expected Behavior
![2016-10-03 12_01_44-asetukset](https://cloud.githubusercontent.com/assets/10330264/19032252/4d2154e2-8961-11e6-9f8a-4e87237c6140.png)

#### How to trigger the error

1. create pdf, add image
2.
3.

#### Your Environment

* YetiForce Version used: 3.2.xx
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
Noticed CKFinder is payable now. What about KCFinder?

**Comment by bpabiszczak** [comment]
It's Not a Bug, It's The Future :) 
We removed this library, in the future we will write a plugin.

**Comment by PercyP** [comment]
Hi,

using direct links isn't practical. When you say 'in the future' how long into the future would that be? 

Because there isn't a field type for images, I use the text editor to add associated images to records. Other users will not have an option to upload their images outside of yetiforce i.e. to the server (as this is what it would entail if the wanted to add images), and even then, they would need to know the full path to the image file). 

Can this functionality not be re-instated until a plugin is developed? If not, are you able to tell us which files/folders have been deleted so those of us who want the image uploader can re-install it ourselves?

Kind regards

Percy

**Comment by kpaulaha** [comment]
I think the reason why it is removed is that the price for ckfinder is now 99usd. Maybe could use kcfinder instead, free open source.

**Comment by PercyP** [comment]
@kpaulaha 
It was actally kcfinder that was installed and this is what it says about it "KCFinder is free open-source replacement of CKFinder web file manager". 

I have just been looking on ckeditor website and there are lots of useful plugins I wouldn't mind installing, including an image gallery. However it doesn't seem that straight forward to install via this integrated version of ckeditor.

**Comment by kpaulaha** [comment]
Damn, you are right, it was kcfinder, had not checked in the libraries of old versions. Well, in that case as you said, if could get that back until getting something new. We have no problems with direct links on our servers, but others might have.

**Comment by PercyP** [comment]
@kpaulaha 

I have been trying to re-add for the last few hours, basically as follows:

1. took a download of yetiforce 3.2
2. Copied the file for kcfinder from libraries/ to my version /libraries
3. Opened the kcfinder folder and changed the upload permission to 777
4. Opened /libraries/jquery/ckeditor/config.js
5. re-added (just below this line: config.shiftEnterMode = CKEDITOR.ENTER_P; 

the following 2 lines:

	config.filebrowserBrowseUrl = 'libraries/kcfinder/browse.php?type=images'; 
	config.filebrowserUploadUrl = 'libraries/kcfinder/upload.php?type=images'; 

Then added filebrowser here

config.plugins = 'dialogui,dialog,about,a11yhelp,dialogadvtab,basicstyles,bidi,blockquote,clipboard,button,panelbutton,panel,floatpanel,colorbutton,colordialog,menu,contextmenu,div,resize,toolbar,elementspath,enterkey,entities,popup,**filebrowser**,find,fakeobjects,floatingspace,listblock,richcombo,font,format,horizontalrule,htmlwriter,wysiwygarea,image,indent,indentblock,indentlist,justify,link,list,liststyle,magicline,pagebreak,preview,removeformat,selectall,showborders,sourcearea,specialchar,menubutton,scayt,stylescombo,tab,table,tabletools,undo,wsc'; 

However I am obviously missing some additional steps as this still doesn't load the upload button. Any ideas?

**Comment by kpaulaha** [comment]
@PercyP 
Seems ok at a quick look. Have to dive into it later with time.
