### ISSUE TITLE
Textfield

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#3625]
### Issue
Would be nice to disable WYSIWYG Editor mode - because in export the text field ist formated with html which is absolutely right.
But it is not so easy when you make an export to handle it for another person...

OR

If we can create an own textarea with predefined width and height - full size width.
At the moment it looks like the selfcreated textarea always have colspan2 - small width and a lot of space to the right side.

Best regards,
Ralph

**Comment by bpabiszczak** [comment]
Try use XML import/export. 
https://yetiforce.com/en/github/issues/206-system-development-ideas.html

**Comment by ralphkretzschmar** [comment]
Hello again,

how can i export reports with XML? i can just see .CSV
Nothing found in the help link.

Best regards,
Ralph
![image](https://cloud.githubusercontent.com/assets/12951699/19237216/0f639002-8efc-11e6-8ae7-efefe46d0cbc.png)
