### ISSUE TITLE
PDF not run

### ISSUE THREAD

**Issue by novateco** [YetiForceCompany/YetiForceCRM#3633]
i used the system tools - PDF option all the time correct, but now i can't continue of the 3 step in any template of my system, and i can't generate any PDF file, this is the error:

![image](https://cloud.githubusercontent.com/assets/22615680/19148572/9bfaf970-8bbd-11e6-985c-793ad19084a2.png)

I try to other BD and the problem persist, and i try to desactive the csrf-magic but problem persist too (in this case the problem is in the jquery library file)

Any ideas  for solve the problem?

Thanks

System: YF 3.2.0 and Windows Bitnami WAMP

**Comment by novateco** [comment]
i reinstall the yf files with the same DB of the installation with error, and now run, i not know because it produced this error, :( thanks

**Comment by bpabiszczak** [comment]
To analyze the errors you should use this: https://yetiforce.com/en/developer-documentation/engine/115-debugging.html
