### ISSUE TITLE
the search products on invoces not run

### ISSUE THREAD

**Issue by novateco** [YetiForceCompany/YetiForceCRM#3634]
Hello, in my installation and the installation on your servers not run this feature

![image](https://cloud.githubusercontent.com/assets/22615680/19161769/6bb8032e-8bf5-11e6-985b-210fb5019379.png)

can help me to solve, thanks

YF version 3.2 stable

**Comment by novateco** [comment]
![037d9504c42b9910db2a497ec9753a30](https://cloud.githubusercontent.com/assets/22615680/19161889/e14c6774-8bf5-11e6-879d-28de3cc97d6d.gif)

**Comment by SkavenKF** [comment]
check #3305

**Comment by novateco** [comment]
ok thanks in the https://gitstable.yetiforce.com now run, (the product is not active) but on my installation (the same version 3.2) not run, is the same version and files on https://gitstable.yetiforce.com and download sourceforge?

Thanks

**Comment by bpabiszczak** [comment]
On gitdeveloper work good. Use WinMerge to see the differences in files.
