### ISSUE TITLE
[PL] Brak możliwości wysyłki masowych maili.

### ISSUE THREAD

**Issue by slawekkow** [YetiForceCompany/YetiForceCRM#3636]
Dzień dobry,
proszę o pomoc w rozwiązaniu problemu
ver. YF 3.2.0
Brak możliwości wysyłki masowych maili.

Wybieram zakładkę Firmy i Kontakty>Leady (lub Kontrahenci). Zaznaczam kilka rekordów lub tylko jeden rekord. Z Menu Akcje wybieram polecenie Masowa wysyłka maili. Wyskakuje okno z podsumowaniem (ilość znalezionych maili). Klikam Wyślij i nie otwiera się okno Roundcube i nic więcej się nie dzieje, żadnego komunikatu.

W pliku phpError.log brak informacji o błędach
W logach serwera także brak błędów

Poniżej Konfiguracja systemu  > Logi >  Serwer - konfiguracja  > Start
RoundCube Engine
Widać tu kilka błędów, ale nie mam pojęcia, czy mogą one mieć jakiś wpływ za opisaną sytuację
Checking PHP extensions
The following modules/extensions are required to run Roundcube:
OK - PCRE
OK - DOM
OK - Session
OK - XML
OK - JSON
OK - PDO

The next couple of extensions are optional and recommended to get the best performance:
ERROR - FileInfo | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/book.fileinfo.php
OK - Libiconv
OK - Multibyte
OK - OpenSSL
OK - Mcrypt
ERROR - Intl | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/book.intl.php
OK - Exif

Checking available databases
Check which of the supported extensions are installed. At least one of them is required.
OK - MySQL 
ERROR - PostgreSQL | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/ref.pdo-pgsql.php
OK - SQLite 
ERROR - SQLite (v2) | | http://www.php.net/manual/en/ref.pdo-sqlite.php
ERROR - SQL Server (SQLSRV) | | http://www.php.net/manual/en/ref.pdo-sqlsrv.php
ERROR - SQL Server (DBLIB) | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/ref.pdo-dblib.php

Check for required 3rd party libs
This also checks if the include path is set correctly.
OK - PEAR
ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime

Checking php.ini/.htaccess settings
The following settings are required to run Roundcube:
OK - mbstring.func_overload
OK - suhosin.session.encrypt

The following settings are optional and recommended:
OK - allow_url_fopen
OK - date.timezone

Pozdrawiam,
Sławomir Kownacki

**Comment by bpabiszczak** [comment]
Proszę najpierw sprawdzić czy działa na GitDeveloper. Następnie jeżeli nie działa, proszę za pomocą ScreenToGIF nagrać całą operacje.,

**Comment by slawekkow** [comment]
Na GitDeveloper (ver. 3.4.0) wszystko działa poprawnie
Na GitStable (ver. 3.2.0) nie działa masowa wysyłka maili - opisany przeze mnie problem

Na https://github.com/YetiForceCompany/UpdatePackages/tree/master nie ma paczki aktualizacyjnej do ver. 3.4.0
w załączeniu nagrana operacja na GitStable.
![masowa wysylka maili](https://cloud.githubusercontent.com/assets/22636658/19232604/f3fb6a30-8ee0-11e6-839a-22eaeae7df52.gif)

**Comment by bpabiszczak** [comment]
Gdy się pojawi wersja 3.4 proszę system uaktualnić do tej wersji.
