### ISSUE TITLE
Error 500 on Plesk 

### ISSUE THREAD

**Issue by tuxxos** [YetiForceCompany/YetiForceCRM#3637]
Hello,
 
I allow to contact you because when I try to install Yeti on my server, I obtain an error 500 after the validation of the license agreement. 

This error 500 arrives either when I throw(launch) the script of installation, or when I throw(launch) the installation (if I modify the file $modules / Users / models / record.php by that of vtiger)

Would you have a solution? 

Yeti version : 3.2.0
Server Operating System : Debian 7.0‬ with Plesk 12.5.30
PHP Version : 7.0.11

**Comment by paula-w** [comment]
Hi,
The system doesn't fully support PHP7 yet, we're still working on the compatibility.

**Comment by tuxxos** [comment]
Hello,
It is exactly similar with the version of PHP under 5.6.10

**Comment by paula-w** [comment]
Check your logs.
You might also want to refer to this comment: https://github.com/YetiForceCompany/YetiForceCRM/issues/3619#issuecomment-252057881
