### ISSUE TITLE
Net amount wrong

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3638]
The net amount on invoices are removing any trailing numbers except for the first one. so 4200 its just showing 4. As seen in my screen shot below.

![capture](https://cloud.githubusercontent.com/assets/22075161/19186388/f183ca1e-8c7d-11e6-9b4e-f4aa93570559.PNG)

**Comment by paula-w** [comment]
What's your system version?
Does the error also exist in the gitdeveloper version. 
[How to report bugs](https://yetiforce.com/en/github/issues/126-issues.html) - for future reference.

**Comment by PercyP** [comment]
@alextovey 

just tried on 3.4RC and it works fine for me, however mine doesn't have a space between the thousands which is the only difference I can see:

![invoice](https://cloud.githubusercontent.com/assets/10598886/19220316/ada72006-8e22-11e6-9198-f6c3b18a2c82.png)

**Comment by TomaszQr** [comment]
Formatting numbers can be set in users configuration
![users](https://cloud.githubusercontent.com/assets/14273211/19228469/d934ae66-8ec5-11e6-8fd0-c2be71651c34.png)

**Comment by alextovey** [comment]
Still does it. Even if i change it then the DB changes it back.

**Comment by alextovey** [comment]
Please find the gif to explain. 
![calendar issue](https://cloud.githubusercontent.com/assets/22075161/19232181/54ed7442-8ed6-11e6-9213-f05d4530b599.gif)

**Comment by skramanzia** [comment]
@TomaszQr do you considere to reopen the case? it's not resolved yet.

Formatting Num.
![image](https://cloud.githubusercontent.com/assets/3030997/19361653/ebaa3db8-9159-11e6-9a11-df908fa713e9.png)

Sum in Report
![image](https://cloud.githubusercontent.com/assets/3030997/19361673/048fe3f0-915a-11e6-8027-bfc68560bf42.png)

Records 
![image](https://cloud.githubusercontent.com/assets/3030997/19361708/246238a4-915a-11e6-869e-02ad80a4cf0c.png)

-------
Change Digit pattern
![image](https://cloud.githubusercontent.com/assets/3030997/19361760/44f6fafa-915a-11e6-883e-bb5d05054852.png)

After change digit pattern 
![image](https://cloud.githubusercontent.com/assets/3030997/19361773/4e9da608-915a-11e6-8f59-ed4b3f0397d8.png)

Records
![image](https://cloud.githubusercontent.com/assets/3030997/19361784/5b2b853e-915a-11e6-9e85-2874d4e720da.png)

**Comment by alextovey** [comment]
Changed for the dev version and it works in that. You can close the bug if you wish.

**Comment by skramanzia** [comment]
@alextovey @TomaszQr @bpabiszczak please see the gif
![nl2oe8vmbr](https://cloud.githubusercontent.com/assets/3030997/19523954/893a076a-95f2-11e6-841a-2382fe095b24.gif)
