### ISSUE TITLE
YetiForce 3.3 & 3.4

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#3642]
We present to you the latest version of YetiForce, which - as always - brings numerous changes, fixes, and new features. Please follow the information below in order to facilitate the update process. 
We would like to thank everyone for testing the system and reporting all issues since 3.2.0 release. We hope you will keep up the good work and help us develop and improve YetiForce for you.

Considering the type of the license [mPDF & Roundcube] and the quality of the code [PHPExcel & AJAXChat], we separated part of the libraries from the main engine. Low code quality libraries will soon be substituted by new ones. Libraries are no longer available in the system by default, that's why we added a new mechanism to make downloading them easier. Library status info can be found for example in Software configuration → System warnings tab.
The library update mechanism has not been completely finished in v3.3, in case you are currently using v3.3 we recommend updating YetiForce to v3.4.

As many of you noticed, apart from the fact that our system is the most efficient one in the world, we also keep growing much faster than any other open projects, such as VtigerCE, SugarCE, SuiteCRM, OroCRM, ODOO, coreBOS, or EPESI, among others.

We were able to achieve all that only thanks to our innovative product building strategy, our community, and amazing clients – YetiForce wouldn't exist without you.

If you want to support us – you can find the DONATE! button on our website - https://yetiforce.com/en/. We're a small company, and any donation means a lot to us. You can also buy one of our modules. Remember that all funds collected from selling modules are going to be spent on the development of new features in the system.

Huge thanks to @PercyP @Raggazzoo for your donations!

● ● ● Links ● ● ●

[YetiForceCRM 3.3.0](https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/3.3.0)
[YetiForceCRM 3.4.0](https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/3.4.0)
[YetiForce CRM update package 3.2.0 --> 3.3.0](https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%203.x.x/3.2.0_to_3.3.0/zip)
[YetiForce CRM update package 3.3.0 --> 3.4.0](https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%203.x.x/3.3.0_to_3.4.0/zip)
● ● ● Update ● ● ●
In the links above you can find update packages that will allow you to update your system from v3.2.0 to v3.3.0; and from v3.3.0 to v3.4.0. The installation process will be described in detail in here: https://yetiforce.com/en/implementer/installation-updates/176-system-update.html and within the next couple of days we will complete the update description to include v3.4.0.

We would like to remind everyone that updates should first be executed on a test version, and only then on the production version [you should always have a backup copy of your environments].
If you want us to update your system, we encourage you to purchase this package – https://shop.yetiforce.com/en/migration/14-migration-vtiger-yetiforce.html.

● ● ● Changelog ● ● ●
3.3

ADDED:
- Added Integration with OpenStreetMap
- Added route calculation in map
- Added missing action 'Custom filters creation' in profiles 
- Added default visibility in CalDAV integrating
- Added button to save and close activity in calendar
- Added exclusion for DAV synchronization
- Added mechanism to download missing libraries
- Added checking for installed libraries
- Added consoles used for code debugging

FIXED:
- Fixed switching mail users
- Improved Homepage
- Optimized database
- Optimized system
- Fixed database error 1:M duplicate in "Reservations"
- Rebuilt unit tests
- Moved available record actions to the left in related module list view 
- Rebuilt creating address book
- Improved PHP7 compatibility
- Fixed encoding messages
- Fixed quick edition
- Improved code quality
- Improved Dashboard

REMOVED:
- Removed global variables and functions 
- Removed mail scanner module from profiles
- Removed Roundcube library
- Removed mPDF library
- Removed PHPExcel library
- Removed AJAXChat library
- Removed CKFinder
- Removed the Mobile module 

3.4:

ADDED:
- Added Yii library 
- Added a new mechanism for database communication
- Added new logger
- Added unread e-mails quantity 
- Added the option to group arguments in sectors in filter charts 
- Added advanced permissions
- Added Notifications as a module
- Added “closed tickets by priority” widget
- Added “closed tickets by users” widget 
- Added “Accounts by industry” widget 
- Added “Estimated Opportunity value” widget
Updated HTML Purifier 4.8.0

FIXED:
- Rebuilt database connection 
- Fixed sales funnel
- Fixed system installer
- Fixed a bug in Document Flow
- Fixed DAV synchronization
- Rebuilt and expanded the permissions update mechanism
- Fixed mobile version appearance
- Added missing actions to profiles
- Fixed downloading libraries

REMOVED:
- Removed the Portuguese language
- Removed log4php library

**Comment by PercyP** [comment]
Congratulations! Looks even better, in fact it just keeps getting better! As soon as my company starts earning we will certainly be donating much more towards the project. I hope others who are using it do donate. Once again well done and thanks for a superb product and service.

Percy

**Comment by basanthagarwal** [comment]
Great affords ..Great job.. Great Application.

**Comment by netinteractive** [comment]
Congratulations!

**Comment by michelmarques1** [comment]
Congratulations!

I am very happy for the evolution of CRM. It is one of the best programs around.

But I have a question: Why in version 3.4 the Portuguese language was removed?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3369

**Comment by StaggerLeee** [comment]
No need to open new issue. How to use OpenStreetMaps ?
