### ISSUE TITLE
404 error when trying to access Roundcube mail

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3643]
Hi,

I have upgraded to 3.4 and just in the process of setting up Roundcube as see it isn't automatically installed any more. 

I saw that I had to download libraries:
![libraries](https://cloud.githubusercontent.com/assets/10598886/19246058/517dc4ec-8f1c-11e6-8e17-11ca29d9a0d3.png)

So clicked on each of the buttons in turn and they come back saying the have installed. I have gone to mail settings and completed the boxes. Then I click on my menu link in yetiforce to open up the mail but I am instead presented with my website's 404 error page. 

As there are not yet any instructions for the new way of setting up roundcube, are you able to advice how I get it to display correctly? I don't even get the login screen now. Is there another stage I am missing in the setup?

Kind regards

**Comment by serbiaserbia** [comment]
I have the same problem. Nothing happend when it download package.
Only mPDF is showed as installed in menu.
Chat and excel I dont see anywhere. Spooky

**Comment by bpabiszczak** [comment]
Go here https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8 and check your library version. 

> Considering the type of the license [mPDF & Roundcube] and the quality of the code [PHPExcel & AJAXChat], we separated part of the libraries from the main engine. Low code quality libraries will soon be substituted by new ones. Libraries are no longer available in the system by default, that's why we added a new mechanism to make downloading them easier. Library status info can be found for example in Software configuration → System warnings tab.
The library update mechanism has not been completely finished in v3.3, in case you are currently using v3.3 we recommend updating YetiForce to v3.4.

**Comment by serbiaserbia** [comment]
@PercyP    HAVE SOLUTION!!!!!

In modules menu - SELECT "My Mailbox"

**Comment by PercyP** [comment]
@serbiaserbia @bpabiszczak 

I have enabled the module My Mailbox, however I can no longer save any settings. I tried it on 2 separate instances under different domains and same problem in each. I tried saving the settings under Mail/Roundcube settings, but nothing saves - defaults back to yetiforce settings. Also tried changing the settings under the Module - Installation by clicking on the settings for the Module, but that doesn't save either.

**Comment by bpabiszczak** [comment]
in the morning we will check the problem.

**Comment by PercyP** [comment]
Thanks @bpabiszczak

**Comment by serbiaserbia** [comment]
@PercyP 
the same problem with my saving. Nothing saved. Everything back to default.
In config/modules/ossmail.php you can change it manually.
I hope it will be not painfull to fix.
