### ISSUE TITLE
Roundcube - CONFIG - does not save settings ---- BUG

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3644]
New fresh Install YF 3.4 and all modules inside.

When enter configuration detail to Mail tools - Mail Roundcube, click Save configuration, it say saved.
But when chek again, configuration is not saved.
See giff.
![mail roundcube](https://cloud.githubusercontent.com/assets/19521910/19249366/79903546-8f35-11e6-894c-432e24c614cd.gif)

**Comment by serbiaserbia** [comment]
I tried to save new configuration in YF Developer (only change the name) and it is the same situation - didnt save new config.

**Comment by PercyP** [comment]
Same for me

**Comment by zebrahosting** [comment]
Same for updated CRM's

**Comment by serbiaserbia** [comment]
@mariuszkrzaczkowski   Thannxxxx

**Comment by zeostravelling** [comment]
@mariuszkrzaczkowski how to implement this update? Got the problem here. Using pt-br language on my system.

> 	Fixed mail client configuration  …
