### ISSUE TITLE
How do we install the hotfix? Is it via the Log-uploads?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3646]
Hi,

I have just seen the hotfix for 3.4. A quickie, is this installed via the usual Logs-Uploads like when we upgrade?

**Comment by paula-w** [comment]
We're adding some missing translations and minor fixes. The hotfix will be officially released once we're done.

**Comment by PercyP** [comment]
To answer my own question, hotfixes get installed via module manager - install.
