### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by jimmyteir** [YetiForceCompany/YetiForceCRM#3647]
#### Issue

Can’t set main currency to EURO (currently only USD)

FIXED: (Can’t turn lead into an opportunity and on down.. am I supposed to enter information again and again for each step?)
#### Your Environment

- YetiForce Version used: ver. 3.2.0
- Browser name and version: Safari Version 10.0
- Environment name and version: - 
- Operating System and version: -

**Comment by skramanzia** [comment]
Hi @jimmyteir you can change currency in "admin mode" add the new currency and remove old one

![image](https://cloud.githubusercontent.com/assets/3030997/19269935/a94959d0-8f93-11e6-8bfb-e8618a01ba16.png)

**Comment by jimmyteir** [comment]
skramanzia,

I've explored that option earlier, and here is my issue:

- I don'f find a way to set euro as the base currency, as this is set to $. I cannot remove the Dollar currency

![screen shot 2016-10-11 at 4 05 53 pm](https://cloud.githubusercontent.com/assets/22728366/19271295/beede858-8fcc-11e6-8d3b-87718980fefd.png)

**Comment by skramanzia** [comment]
It's true, can't change the "Currency" installed.
 Only to test, you can try modify "vtiger_currency_info" table

**Comment by jimmyteir** [comment]
skramanzia,

Thank you for pointing me in the right direction! 

I managed to get Euro as the primary currency **by moving the "defaultid" value from the dollar row to the euro row.** (see attached picture) 

![screen shot 2016-10-12 at 12 35 40 pm](https://cloud.githubusercontent.com/assets/22728366/19305389/4ed81cfc-9079-11e6-9758-b393a3691706.png)

Will check back in here if I bump into problems further down the line, but everything appears to be ok.

Thanks again, skramanzia!

**Comment by PDMeira** [comment]
To create a new currency that was not on the list, I had to

1. Change vtiger_currencies table, adding a new country and a new currency

To change my default currency to euros (by default was US$) I had to:

1. Change vtiger_currency_info table, setting euro row defaultid column to -11 and the US$ one to 0

Yeti should have a configuration interface to do these operations.
