### ISSUE TITLE
I am unable to add leads

### ISSUE THREAD

**Issue by morewebsolutions** [YetiForceCompany/YetiForceCRM#3648]
Unable to add leads. Showing unable to found LBL RecordsGenerated by YetiforceCRM ver. 3.1.0PHP: 5.6.25

**Comment by PercyP** [comment]
@morewebsolutions 

you probably need to upgrade: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x

**Comment by alextovey** [comment]
@morewebsolutions as @PercyP said you need to upgrade as this was fixed in the current version.
