### ISSUE TITLE
No functionalities of Roundcube after adding patch 4c40bd7 

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3649]
Yesterday Installed YF 3.4 and had problem with saving settings for Roundcube.
Now I write all modification of files from  4f3c759 commit, and get this - please see gif. Previous I had downloaded and instaled Roundcube module, but with saving setting Bug.

![mail patch](https://cloud.githubusercontent.com/assets/19521910/19274657/163de104-8fd1-11e6-8efd-a2fbdc6218d5.gif)

@PercyP  @zebrahosting  
did you fixed problem with saving Roundcube settings? Tried this fix  4f3c759 ? It is not working for me.... maybe I am doing something wrong....

**Comment by serbiaserbia** [comment]
I applied commit with changing file per file.... "6 changed files  with 24 additions and 23 deletions"
Deleted some lines and some lines added. Does this works that way? Manually?
Tried with fresh new install, but all same.

**Comment by kpaulaha** [comment]
I had it working with adding the same as you plus [this](https://github.com/YetiForceCompany/YetiForceCRM/commit/c3b81cbcde97532a93cf2542e4ef5350bc1cdf0d)

**Comment by PercyP** [comment]
@serbiaserbia I was waiting for the hotfix to be officially released with instructions as per Paulas response to my thread about hotfix. Maybe I too will go through the suggestion by @kpaulaha to get it working now. Will let you know how I get on

**Comment by kpaulaha** [comment]
I have installed the hotfix-1 on a couple different installations, works ok.

**Comment by serbiaserbia** [comment]
@kpaulaha  @PercyP 
I am not so tech guy.... what is hotfix? where to download it? how to apply it? 
sorry for asking this stupid question :-(

**Comment by PercyP** [comment]
@kpaulaha how do you install it? via logs-updates?

**Comment by PercyP** [comment]
@serbiaserbia 

sorry meant to post - it is here: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x

**Comment by kpaulaha** [comment]
via modules installation in admin panel

**Comment by serbiaserbia** [comment]
what do you suggest: to install via module or via update?

**Comment by kpaulaha** [comment]
![2016-10-11 18_56_11-](https://cloud.githubusercontent.com/assets/10330264/19278014/71e7ec9e-8fe4-11e6-8cf7-c5b4bd5be494.png)

**Comment by serbiaserbia** [comment]
tanananananaaaa

![succesfull](https://cloud.githubusercontent.com/assets/19521910/19278067/44b411d8-8fdc-11e6-89a9-db89aab0803f.png)

now to test it

**Comment by serbiaserbia** [comment]
Buttons are changes to Downloaded and Upadate library.  Different than previous without this Fix.
And it saves settings now.
![modules](https://cloud.githubusercontent.com/assets/19521910/19278146/8e271eb4-8fdc-11e6-8f53-8f172884347e.png)

**Comment by PercyP** [comment]
@serbiaserbia 

can you now access after running the hotfix? I can now save my settings, but I am still getting a 404 error:

Failed to load resource: 
the server responded with a status of 404 (Page not found)  http://wwwmysite.com/crm/modules/OSSMail/roundcube/
 Do you get this or are you now seeing the login page? Very strange ...

**Comment by kpaulaha** [comment]
Strange, I got it running on one updated from yf 3.2 and other clean 3.4, other even on win server

**Comment by serbiaserbia** [comment]
@PercyP    strange behavior...
I dont get that massage on login. Only regular login page to enter username and pw.

yes, I can access to roundcube mail... 
but I cant get work folder configuration. grrrrrrrr

**Comment by serbiaserbia** [comment]
Now worked folder config.... Magiccccccccc

**Comment by serbiaserbia** [comment]
First test.
   - when recive email from entered contact it bind email to contact.
  - in Document folder I have attachment from email
But I dont have document in relation with contact.  Is this ok? What do you think, whether it should automatically connect in Contact module email+Document?

**Comment by kpaulaha** [comment]
You need cron working

**Comment by serbiaserbia** [comment]
@PercyP 
did you get your instance to work?

**Comment by PercyP** [comment]
@serbiaserbia 

no unfortunately, I can't get past the 404 error. I am wrestling with whether I should start all over again, but I really don't want to do that as have added tons of new fields etc.

**Comment by Raggazzoo** [comment]
version.php is not update to 3.4.21 with the hotfix package, is it wanted?

**Comment by TomaszQr** [comment]
@Raggazzoo 
Yes, the version file should not be changed
@PercyP 
It's weird, you have to check your logs, the answer is usually there.

**Comment by Raggazzoo** [comment]
Ok thank you =)

**Comment by PercyP** [comment]
Hi,

I just checked, and roundcube is not downloading/installing. This is strage, the folders were there before I upgraded

**Comment by PercyP** [comment]
Aha! I deleted everything, re-installed my pre-updated v3.2 then went through the process again and it now works :dancing_men:

**Comment by PercyP** [comment]
Spoke too soon. It failed after running the 4 updates under module manager - see https://github.com/YetiForceCompany/YetiForceCRM/issues/3653

**Comment by kabelo38** [comment]
I also experienced this after updating to 3.4.20 I had to reset head to 3.4.0 and all started working i think i will stick to this version everything works well.

**Comment by PercyP** [comment]
@kabelo38 
When you say reset, do you mean moving back to 3.4.0? pre- hotfix? 

I don't think we have any option but to apply the hotfix to fix those 500 errors as I was having those too. If we resign ourselves to sticking on a version that works, we may never be able to move forward with new upgrades, so unfortunately we need to find and fix the problems. The hotfix fixed my 500 errors. 
My outstanding problem is just with roundcube email. I am thinking now it is because I upgraded to php version 5.6 (are you on this?) apparently there are changes that affect mail etc. see here: http://stackoverflow.com/questions/30371910/phpmailer-generates-php-warning-stream-socket-enable-crypto-peer-certificate

**Comment by kabelo38** [comment]
Yep i had to perform following command
$ git log
$git reset --hard  5d095dca5c9fdb4272506bb9db74f794b0c8ff5a

and after that everything worked well for us.

We are currently have this php version installed. 

PHP 5.6.26-2+deb.sury.org~xenial+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

Ubuntu 16

I will stick with 3.4.0 until i can fully test any new versions We cannot afford to mess the current install we already running a risk of running a developer version on our production server so the risk is too high, but yet again YetiForce's response time is indeed overwhelming.

**Comment by PercyP** [comment]
@kabelo38 

I finally fixed mine using 3.4. hotfix see here: 

https://github.com/YetiForceCompany/YetiForceCRM/issues/3653#issuecomment-253305476

It may help - maybe try your version on a spare domain to see if it works (that is what I had to do).

**Comment by witer30** [comment]
In my case it does't work. 
I had fresh install of version 3.4.1387 and it doesn't work...
There is a bug for sure...
