### ISSUE TITLE
LDAP/AD integration

### ISSUE THREAD

**Issue by SergeyDjam** [YetiForceCompany/YetiForceCRM#365]
Hello, guys

Business users need to integrate with LDAP/AD. How worked is?

**Comment by SergeyDjam** [comment]
Tutorial http://adminberlin.de/vtiger-crm-6-active-directory-authentication/ 
But no worked is...

**Comment by bpabiszczak** [comment]
At the moment, we have a ready integration with LDAP. When the opportunity occurs and we will be deploying something for a customer that uses AD, we will try to add this solution as a standard solution in YetiForce [we don’t have our own AD server to test it and someone has to pay for the devoted time]. I’m going to close this issue for now, but we will certainly add this solution in the next few months.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/d2273a2779326ff0fff9dec552d3f1cf33bfa8ed

**Comment by networkpanic** [comment]
it seems that config a bind dn is missing in gui&code
can i help with setting up a active directory and ldap for testing?
