### ISSUE TITLE
Bind email attachment to Account Documents on recived email

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3650]
#### Issue

When I recive email from CRM Contact, I dont see attached file when I enter in Account or Contact detail. 
In Account or Contact module when I enter to record there is no relations in Documents

![2 contact email attachment](https://cloud.githubusercontent.com/assets/19521910/19289079/45371dda-9009-11e6-8f3a-3c87b47b5faf.png)

![account no document binded](https://cloud.githubusercontent.com/assets/19521910/19288858/5c7c084e-9008-11e6-8183-eff203087231.png)

But emails have attachment
![1 contact email attachment](https://cloud.githubusercontent.com/assets/19521910/19288831/38edccdc-9008-11e6-8ae7-7cbe11ec2a64.png)
#### Actual Behavior

Document EXIST and downloaded in Document module
![3 document folder is full](https://cloud.githubusercontent.com/assets/19521910/19288741/bef628ca-9007-11e6-93ff-fd41546ccac2.png)

When I click on file there is no relation
![document detail](https://cloud.githubusercontent.com/assets/19521910/19288776/efb7c5e0-9007-11e6-9537-8e518d0c6e22.png)

In Email there is downloaded attachment
![corporate email relation ok](https://cloud.githubusercontent.com/assets/19521910/19288919/991add7a-9008-11e6-80ea-33d92f3f293f.png)
#### Expected Behavior

I think it have to be when I enter to record (Accounts or Contact) be able to see all documents from our comunication
#### How to trigger the error
1. When recive email, it bind with contact and/or Account
2. I dont see documents from Email in Account or Contact module 
3. Only see attachment in Document module, or Corporate email Module
#### Your Environment
- YetiForce Version used: YF 3.4 with HotFIX
- Browser name and version: Chrome
- Environment name and version: php 5.6.2
- Operating System and version: VPS
  CRON is running very well (setted on 1 MINUTE)
  ![cron](https://cloud.githubusercontent.com/assets/19521910/19288982/dfd25054-9008-11e6-8669-7e6981a3c7f6.png)

I have in my mind that I did not set some SETTING to let him to bind. Any idea?

**Comment by bpabiszczak** [comment]
I think mail attachments mustn’t be automatically added to records because the attachments often are:

single pixels [tracking]
logos in footers
other
and it would generate too much redundant info. In the future we will add the option to easily add an attachment at the roundcube or record level, but it has low priority for now.
