### ISSUE TITLE
Save option missing in Scan Mail

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3651]
#### Issue

Save option missing in Scan Mail
#### Actual Behavior

I'm unable to save setting made in Mail Scanner - option
#### How to trigger the error

1.
2.
3.
#### Your Environment

- YetiForce Version used: 3.4
- Browser name and version:
- Environment name and version:
- Operating System and version:

**Comment by serbiaserbia** [comment]
Did you install  HOTfix3.4 from:
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x

see #3649

**Comment by basanthagarwal** [comment]
Thanks !! Got it!
