### ISSUE TITLE
[PL]Brak informacji w module lista połączeń o użytkowniku crm, który wykonał połączenie.

### ISSUE THREAD

**Issue by zwieja** [YetiForceCompany/YetiForceCRM#3652]
#### Issue

Brak informacji na liście połączeń o użytkowniku crm, który wykonał połączenie.
#### Expected Behavior

Pojawienie się informacji o użytkowniku crm na liście połączeń, który wykonał połączenie.
#### How to trigger the error

1. Wykonać połączenie.

![tr](https://cloud.githubusercontent.com/assets/11053085/19304489/3216b3a0-906d-11e6-8365-ba2acc8d757b.PNG)
#### Your Environment

- YetiForce Version used: 3.3.0
- Browser name and version: Chrome 53.0.2785.143

**Comment by bpabiszczak** [comment]
Nie używamy obecnie tego modułu [ani nasi klienci których my obsługujemy], jak któryś zacznie używać wówczas to poprawimy. Na chwilę obecną ma to niski priorytet, ponieważ klient który zacznie tego używać zapewne będzie miał szersze oczekiwania i wówczas moduł ten zostanie przepisany...
