### ISSUE TITLE
[PL] Obsługa zamówień przez crm 

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#3655]
Witam interesuje mnie funkcjonalność która by poprzez ograniczenie dostępu do określonych modułów  dała możliwość złożenia zamówienia on line przez klienta na bazie cennika i produktów.

W portalu widzę działają tylko zgłoszenia brak obsługi zamówień

Your Environment

    YetiForce Version used: 3.4.0
    Browser name and version: Firefox

**Comment by bpabiszczak** [comment]
Portal klienta obecnie nie ma takiej funkcjonalności. Można taką funkcjonalność zrealizować na wiele sposobów [np. integracje ze sklepem internetowym] ale każdy ze sposobów w mniejszym lub większym stopniu wymaga prac programistycznych a więc trzeba to zlecić. 

Jeśli chodzi o nowe funkcjonalności w systemie, to polecam ten artykuł:
https://yetiforce.com/pl/github/issues/203-pomys%C5%82y-zwi%C4%85zane-z-rozwojem-systemu.html
