### ISSUE TITLE
CalDAV 3.4 problem

### ISSUE THREAD

**Issue by netinteractive** [YetiForceCompany/YetiForceCRM#3657]
On fresh install (on php 7.0, i also try on next server with 5.6 with the same effect) i try to get CalDAV info on url : /api/dav.php

after put login and password I get : 

```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.1.3</s:sabredav-version>
<s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
<s:message>
There was no plugin in the system that was willing to handle this GET method. Enable the Browser plugin to get a better result here.
</s:message>
<s:file>
public_html/libraries/SabreDAV/DAV/Server.php
</s:file>
<s:line>467</s:line>
<s:code>0</s:code>
<s:stacktrace>
#0 public_html/libraries/SabreDAV/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) #1 public_html/api/dav.php(80): Sabre\DAV\Server->exec() #2 {main}
</s:stacktrace>
</d:error>
```

On gitdeveloper it work properly.

**Comment by PercyP** [comment]
@netinteractive 

I am not sure, but does it not first need to be activated here: /config/modules/API.php removing the trailing // from appropriate app?

**Comment by netinteractive** [comment]
Thanks, I forgot about that. Now on DAVDroid i have error message, its known issue?
 
`Authority: com.android.calendar

HTTP REQUEST:
REPORT /api/dav.php/calendars/admin/YFCalendar/
Depth: 1

<?xml version='1.0' encoding='UTF-8' ?><CAL:calendar-query xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav"><prop><getetag /></prop><CAL:filter><CAL:comp-filter name="VCALENDAR"><CAL:comp-filter name="VEVENT"><CAL:time-range start="20161008T140001Z" /></CAL:comp-filter></CAL:comp-filter></CAL:filter></CAL:calendar-query>

HTTP RESPONSE:
http/1.1 403 Forbidden
Connection: Keep-Alive
Content-Length: 360
Content-Type: text/html; charset=iso-8859-1
Date: Thu, 13 Oct 2016 12:00:01 GMT
Keep-Alive: timeout=2, max=9998
Server: Apache

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">[LF]
<html><head>[LF]
<title>403 Forbidden</title>[LF]
</head><body>[LF]
<h1>Forbidden</h1>[LF]
<p>You don't have permission to access /api/dav.php/calendars/admin/YFCalendar/[LF]
on this server.</p>[LF]
<p>Additionally, a 404 Not Found[LF]
error was encountered while trying to use an ErrorDocument to handle the request.</p>[LF]
</body></html>[LF]

EXCEPTION:
at.bitfire.dav4android.exception.HttpException: 403 Forbidden
at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:317)
at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:290)
at at.bitfire.dav4android.DavCalendar.calendarQuery(DavCalendar.java:90)
at at.bitfire.davdroid.syncadapter.CalendarSyncManager.listRemote(CalendarSyncManager.java:126)
at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.java:160)
at at.bitfire.davdroid.syncadapter.CalendarsSyncAdapterService$SyncAdapter.sync(CalendarsSyncAdapterService.java:67)
at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.java:85)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)

SOFTWARE INFORMATION
Package: at.bitfire.davdroid
Version: 1.3.2.2-gplay (120) Wed Oct 05 11:19:52 GMT+02:00 2016
Installed from: com.android.vending
JB Workaround installed: no

CONFIGURATION
System-wide synchronization: automatically

  Address book sync. interval: manually
  Calendar     sync. interval: 60 min
  OpenTasks    sync. interval: manually
  WiFi only: false
  [CardDAV] Contact group method: GROUP_VCARDS
            RFC 6868 encoding: false
  [CalDAV] Time range (past days): 5
           Manage calendar colors: false

SQLITE DUMP
android_metadata
|  locale |
|  pl_PL |
----------
settings
|  setting | value |
|  hint_BatteryOptimizations | 0 |
|  hint_OpenTasksNotInstalled | 0 |
|  distrustSystemCerts | 1 |
|  logToExternalStorage | 0 |
----------
sqlite_sequence
|  name | seq |
|  services | 2 |
|  homesets | 3 |
|  collections | 3 |
----------

SYSTEM INFORMATION
Android version: 6.0.1 (MMB29K.G903FXXU1BPD3)
Device: Samsung SM-G903F (s5neolte)`

**Comment by PercyP** [comment]
@netinteractive 

are you still working without applying the hotfix?

**Comment by netinteractive** [comment]
Where I can find hotfix? J

 

Od: PercyP <notifications@github.com>
Odpowiedź do: YetiForceCompany/YetiForceCRM <reply@reply.github.com>
Data: czwartek, 13 października 2016 14:08
Do: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
DW: Jan Pisula <janpawelpisula@gmail.com>, Mention <mention@noreply.github.com>
Temat: Re: [YetiForceCompany/YetiForceCRM] CalDAV 3.4 problem (#3657)

 

@netinteractive 

are you still working without applying the hotfix?

**Comment by netinteractive** [comment]
I see hot fix - but its not related to this case in my opinion.

**Comment by PercyP** [comment]
I had white screen errors prior to hotfix, when applied everything but roundcube worked. Now roundcube also works. 

maybe put a copy of your crm on another domain and work through the process including hotfix on that. For me at least, its worth persevering through the upgrades so you have the most uptodate version of the system.

**Comment by netinteractive** [comment]
I install hotfix succesfully but 403 on my DAVDroid still apears:)

**Comment by PercyP** [comment]
@netinteractive 

have you tried fixing the folder permissions? I did this by using filezilla ftp (or another of your choice) - make all folders 755 and all files 644 this fixed those forbidden access issues for me - try it on a copy first.

**Comment by PercyP** [comment]
Note: when I viewed folder permissions in file manager they showed as correct - but it wasn't, so I still had to do the above

**Comment by bpabiszczak** [comment]
[PL]
Jeżeli działa na wersji developerskiej to nie zajmujemy się tym bezpłatnie. 
Błąd 403 to brak uprawnień do wyświetlenia pliku który generuje Apache, nie ma to nic wspólnego z aplikacją.
