### ISSUE TITLE
Question: How to get colors in Listview like in the Promo-Screenshots?

### ISSUE THREAD

**Issue by rage1985** [YetiForceCompany/YetiForceCRM#3660]
Hey Mates!

How to get that fancy colors in Listview like in your Promo-Screenshots?
I think you made it based on Account-Type in the Screenshot.

Pretty cool, i want that too ^^

I roamed the settings pages up and down and couldn`t find where to set this up.
Any suggestions?

**Comment by skramanzia** [comment]
You can configure Colors in Software configuration > Automation > Recording Control
