### ISSUE TITLE
Bug - Condition in Recording Control 

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3661]
#### Issue

Can not select the option "is not" in "Recording Control"
#### Actual Behavior

![0unwbiokmg](https://cloud.githubusercontent.com/assets/3030997/19359312/08ba9c9a-9150-11e6-9296-5ff3d17e47c5.gif)
#### Your Environment

- YetiForce Version used: Latest Dev and Latest Stable
- Browser name and version: Chrome Latest
- Environment name and version:
- Operating System and version: OSX Sierra

**Comment by mariuszkrzaczkowski** [comment]
The error doesn't occur in the latest version

**Comment by ezbank** [comment]
it still exists ver. 3.4.1267

**Comment by ezbank** [comment]
![error 1](https://cloud.githubusercontent.com/assets/19627226/21495974/9319a164-cc4d-11e6-938e-59b3001fb0c8.gif)
