### ISSUE TITLE
[PL] CRON nie wykonuje zaplanowanych działań

### ISSUE THREAD

**Issue by slawekkow** [YetiForceCompany/YetiForceCRM#3662]
Dzień dobry,
Problem:
CRON nie wykonuje samoczynnie cyklicznie zaplanowanych działań pomimo, że wszystkie wyzwalacze są aktywowane.
Ne serwerze w Crontab dodano polecenie wget -q -O /dev/null http://www.yeti.mojastrona.pl/public_html/yeti/cron/vtigercron.sh z ustawieniami */5****

Rzeczywiste zachowanie:
Dopiero, gdy odświeżę otwarty w przeglądarce plik cron/vtigercron.php to CRON wykona zaplanowane działania

Środowisko:
YetiForce: v3.4.0 HOTfix3.4
Przeglądarka: Chrome 53.0.2785.143
PHP: 5.6

Mój plik cron/vtigercron.sh (775) wygląda nastepująco
export VTIGERCRM_ROOTDIR=`dirname "$0"`/..
export USE_PHP=php
#export USE_PHP=/usr/local/php53/bin/php
#export USE_PHP=/usr/local/php56/bin/php56

cd $VTIGERCRM_ROOTDIR
# TO RUN ALL CORN JOBS
$USE_PHP -f cron/vtigercron.php 

Wystąpiłem do admina serwera o podanie ścieżki do pliku php56 na serwerze.
Otrzymałem następującą odpowiedź:

"To co Pan wskazuje to zmienne systemowe i ich ustawianie co na koncie hostingowych nie jest przez nas wspierane.
Dodatkowo nawet gdyby je Pan ustawił nie otrzyma Pan gwarancji że w przypadku np. aktualizacje parsera PHP nie ulegną one zmianie.
Tego typu konfiguracje które wymagaja wskazania dodatkowych zmiannych systemowych powinny być wykonywane na serwerach VPS lub dedykowane a nie serwerach hostingowych.
Dodatkowo potrzebuje Pan uruchamiać w cronie skrypt basha czego również nie wspiera bezpośrednio hosting. Do tego typu działań możemy zaproponować serwer VPS lub dedykowany."

Na razie nie mogę zakupić VPS'a więc pytanie do Was, czy istnieje może jakieś inne rozwiązanie problemu?

**Comment by bpabiszczak** [comment]
To skoro działa cron/vtigercron.php z przeglądarki to dodać wywołanie tego adresu w CRONie :]

**Comment by slawekkow** [comment]
zrobiłem , jak radziłeś. Zamieniłem w CRONie plik  cron/vtigercron.sh na  cron/vtigercron.php, ale nic to nie zmieniło.

**Comment by bpabiszczak** [comment]
hosting na którym masz CRM udostępnia na pewno instrukcje jak uruchamia się CRON poprzez wywołanie adresu. Inaczej uruchamia się na serwerach pliki sh a inaczej pliki php,

**Comment by slawekkow** [comment]
to jest instrukcja uruchomienia zgodnie z którą postępowałem
wget -q -O /dev/null http://www.strona.pl/strona.php
gdzie http://www.strona.pl/strona.php to adres skryptu, który ma zostać wykonany.

**Comment by bpabiszczak** [comment]
Ogólnie sprawa jest prosta... wchodzi programista i administratorem na kilkanaście minut i problem zapewne rozwiązują. Ty natomiast sam próbujesz rozwiązać problem, a więc polecam np. taką lekturę, tutaj opisują podobny problem i podają rozwiązanie: https://forums.vtiger.com/index.php?p=/discussion/comment/1190246.

Takie problemy zawsze wymagają analizy i my to wykonujemy odpłatnie, może ktoś inny Ci pomoże [ale wtedy najlepiej napisać w EN] bo my nie mamy czasu na analizowanie bezpłatnie każdego przypadku.

**Comment by slawekkow** [comment]
ok, dzięki

**Comment by slawekkow** [comment]
niestety jest to ponad moje siły. Powiedz, proszę, ile kosztowałaby taka usługa wykonana przez Was?

**Comment by bpabiszczak** [comment]
Należy najpierw kupić to: https://shop.yetiforce.com/pl/wsparcie/20-sla-1-roboczogodzina.html 
Następnie podpisujemy NDA
Następnie otrzymujemy dane dostępowe do systemu i serwera.
Następnie po 1h wiemy czy to większy problem [i dajemy wycenę] czy mniejszy problem i przy okazji go poprawiamy jak się zmieści w tej 1h.
