### ISSUE TITLE
Nie wykonywane są kopie zapasowe

### ISSUE THREAD

**Issue by slawekkow** [YetiForceCompany/YetiForceCRM#3663]
Cześć,
Pomijając wątek #3662 i problemy z CRON'em.

Problem:
Nie wykonywane są kopie zapasowe

Rzeczywiste zachowanie:

W CRON jest informacja o starcie ostatniego skanowania i końcu ostatniego skanowania. Należałoby zatem sądzić, że kopia została utworzona. Jednakże nie tworzy sie ona. Folder backup oraz utworzony później folder ftp jest pusty.
W logach także nie ma żadnej informacji o utworzonej kopi.

Jak wywołać błąd:
1.chcę utworzyć kopię ręcznie.  Konfiguracja systemu > Bezpieczeństwo > Kopia zapasowe > Start
2.Klikam na "wykonaj kopię systemu"
3.Pokazuje się komunikat "Kopia zapasowa została zaplanowana"
4. i nic się nie dzieje

Skonfigurowałem także serwer ftp i także folder jest pusty bez względu na to czy klikam ręcznie, czy wykona to CRON

Środowisko:
YetiForce: v3.4.0 HOTfix3.4
Przeglądarka: Chrome 53.0.2785.143
PHP: 5.6

Gdzie popełniam błąd?

**Comment by bpabiszczak** [comment]
Szczerze powiedziawszy... to my nie używamy tego systemu backup-u bo jest niedoskonały [za wolny bo działa, powinien być wykonywany na poziomie systemu operacyjnego a nie aplikacji] oraz działa tylko dla małych baz [pod średnie i duże się nie nadaje] w związku z powyższym w wersji 3.5 nie będzie już tego modułu. 

Będziemy za to udostępniali skrypt sh którym my wykonujemy kopie zapasowe na serwerach.

**Comment by slawekkow** [comment]
OK, fajnie, Kiedy można się spodziewać v. 3.5?

**Comment by bpabiszczak** [comment]
Może wtedy: https://github.com/YetiForceCompany/YetiForceCRM/milestones ale nie obiecujemy.

**Comment by dextras** [comment]
Nie wiem czy dobrym pomysłem jest wycofanie całkowicie możliwości robienia kopi zapasowej na poziomie aplikacji. Jak dla mnie jest to krok wstecz. Nie każdy klient będzie miał dostępny hosting z dostępem ssh, choć jest to oczywiście wskazane. Uważam, że taka "furtka", mimo, że nie jest doskonała i nie nadaje się na średnie i duże projekty, to przy małych sprawdza się w sam raz. Osobiście nie korzystam z tej funkcjonalności, ale nie uważam, żeby jego usunięcie było dobrym posunięciem. Może lepiej go pozostawić jako moduł opcjonalny? Może przydałaby się ankieta do osób udzielających się na tym forum?

**Comment by bpabiszczak** [comment]
Nie znam żadnego naszego klienta który z tego korzysta, dodatkowo ten mechanizm działa w wielu przypadkach niepoprawnie [za duże bazy jak dla niego] i co najważniejsze za długo. Jak moduł zostanie usunięty, wówczas możecie sobie zrobić jego forka i niezależnie utrzymywać/rozwijać. My nie planujemy poświęcać mu więcej czasu.
