### ISSUE TITLE
[PL] Skórka blue  a skórka podstawowa brak wyświetalania niektórych pozycji menu

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#3665]
Pytanie do twórców : nie rozwija wszystkich  pozycji menu czy to z poziomu konfiguracji czy
widoku podstawowego czy takie było zamierzenie czy można to zmodyfikować.

#### Your Environment

* YetiForce Version used:3.4
* Browser name and version:firefox
* Environment name and version:
* Operating System and version:linux

**Comment by bpabiszczak** [comment]
Nie wiem o czym rozmawiamy... poproszę o zrzuty ekranu.

**Comment by hipernet** [comment]
![zrzut ekranu 2016-10-15 12 51 30](https://cloud.githubusercontent.com/assets/20052436/19409549/38ebfe54-92d6-11e6-99cb-6ceec487e96e.png)

**Comment by hipernet** [comment]
![zrzut ekranu 2016-10-15 12 54 13](https://cloud.githubusercontent.com/assets/20052436/19409562/8cad40e8-92d6-11e6-9031-2fa90a9a5380.png)

**Comment by bpabiszczak** [comment]
Blue jest nieskończone... będziemy to jeszcze poprawiać, w szczególności menu :]
