### ISSUE TITLE
Save option is missed in Outgoing Server

### ISSUE THREAD

**Issue by speakerua1** [YetiForceCompany/YetiForceCRM#3667]
![video_2016-10-21_095329](https://cloud.githubusercontent.com/assets/16084556/19589437/e8655ebe-9774-11e6-8df6-3958a32fec9f.gif)

#### Issue
When I'm trying to change name of outgoing server and click on save button I see the error:
Статус тестового сообщения:  Письмо не может быть отправлено. Пожалуйста, проверьте настройки адреса и сервера
Than after refreshing page nothing has changed in the forms.

#### Expected Behavior
It would be great if even after bad results I could see that in my form another smtp that I've written to change that was before.

#### How to trigger the error
1. Mail
2. Outgoing server setup
3. Change Name (outgoing SMTP)
4. Save
5. Error.
6. Refreshing
7. Nothing has changed

#### Your Environment

* YetiForce Version used: 3.4 + Hotfix
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by speakerua1** [comment]
Fixed it

**Comment by Pietrox** [comment]
Hello,
I have the same problem and I'm forced to edit the php directly (OSSMail.php) but i would rather use the built in form.
How did you fix it?

**Comment by speakerua1** [comment]
I haven't fixed it yet.
Because I don't have a clue what was written in the code.
I've tested previous versions and didn't find that file.

Please could You comment my issue on github.
Thanks.


>Четверг, 27 октября 2016, 11:19 +03:00 от Pietrox <notifications@github.com>:
>
>Hello,
>I have the same problem and I'm forced to edit the php directly (OSSMail.php) but i would rather use the built in form.
>How did you fix it? 
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением
Яременко Евгений
+380 66 343 6555
