### ISSUE TITLE
[BUG]Interface errors

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3668]
when used on a mobile touch screen, the operation is not smooth. Exceptions to quickly create "Events/To Do" are doing well, the other did not.
Tested on Note 5
Loading image...
https://cloud.githubusercontent.com/assets/19627226/19414811/ef0d8844-9383-11e6-9971-5c0e1a58273e.gif
![animation](https://cloud.githubusercontent.com/assets/19627226/19414811/ef0d8844-9383-11e6-9971-5c0e1a58273e.gif)

**Comment by ezbank** [comment]
Loading image...
https://cloud.githubusercontent.com/assets/19627226/19414811/ef0d8844-9383-11e6-9971-5c0e1a58273e.gif

**Comment by ezbank** [comment]
Change `if(i>300){app.showScrollBar(jQuery(".quickCreateContent"),{height:"300px"})}` to `if(i>300){app.showScrollBar(jQuery(".quickCreateContent"),{height:"100%"})}`

**Comment by skramanzia** [comment]
@bpabiszczak It's possible add this change in the current version?

**Comment by bpabiszczak** [comment]
it has a low priority
