### ISSUE TITLE
[Question] How to generate PDF File from Template

### ISSUE THREAD

**Issue by pmontanez** [YetiForceCompany/YetiForceCRM#3669]
First of All, I want to thanks the entire dev team for such a great piece of Software Dziękuję bardzo!!
Now I Just playing around after reading manual, But still confuse with a couple things particularly on the creation of the PDF files for Invoices, Orders, etc.

Can you explain the process?  My Goal is to be able to 

- Create the PDF template
- Create the Workflow ( Although I don't see any action that actually creates the file)
- Email PDF to Customer
- Save the PDF on customer document

Thanking in advance for any help!

**Comment by PercyP** [comment]
@pmontanez 

To create PDF you need to go to Configuration (little cog at top of side menu) then System Tools then select PDF - you will see example templates in there. I basically took a copy of the sales invoice and adapted it. You can click on the export button then re-import it or just copy and paste the details from one open screen to another. 

Make sure you select the correct fields (for Invoices). When you have finished, jst go to your Invoice and create a test one. The PDF options are integrated automatically and you will see a little icon when in Invoice List or actual invoice (next to Add Record in list view or Top right in record view) click on that and it will reveal the Export PDF, click on that then click on the dropdown on the Generate button and it will give you an option to download or email.

![invoiceicon](https://cloud.githubusercontent.com/assets/10598886/19442603/c3a32ebc-9481-11e6-8846-7befda9e9d0b.png)

![emailinv](https://cloud.githubusercontent.com/assets/10598886/19442697/23c8af2e-9482-11e6-8986-437125d4065e.png)

**Comment by slawekkow** [comment]
Hi @PercyP
translated by Google

On my installation or the https://gitdeveloper.yetiforce.com/index.php?module=FInvoice&view=List&mid=129&parent=71 not have icons that allow you to generate a PDF file. They are not on the list or invoice or view an invoice.
Tell me please, whether it involves perhaps the status of an invoice? If so, what should statuses must enter?
Or something else?
All modules have installed.
I will be grateful for your help.

My version YT is 3.4.0 + hotfix
