### ISSUE TITLE
Automatically bind Documents with Account

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3670]
#### Issue

How to see all documents related to Account??
Can recived attachment (from email) be automatically bind with Account and related Document tab??
#### Actual Behavior

If I recive Invoice by email from Account record, I create Payment Out and bind it with document (recived invoice by email)

I dont see documents in Document tab in Account record (recived from Email and binded to Payment out)
![docum tab in acc](https://cloud.githubusercontent.com/assets/19521910/19417512/402b0014-93af-11e6-9902-b37db75c192d.png)
In payment out there is relation with document
![pazmentout document](https://cloud.githubusercontent.com/assets/19521910/19417552/24b93f20-93b0-11e6-9c7c-4085f0be14b8.png)
#### Expected Behavior

To see all documents (related with record) when enter to Account and related Document tab.
#### How to trigger the error
1. when recive email with attachment, it does not bind atachment with Account record to see it in Document tab
2. 
3. 
#### Your Environment
- YetiForce Version used: 3.4
- Browser name and version: chrome latest
- Environment name and version: vps
- Operating System and version:

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3650
