### ISSUE TITLE
Feature request - related block in PDF templater

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#3676]
Mentioned before but maybe worth repeating.
PDF templater will be much more functional with option to create related blocks similar to PDFMaker in vtiger. If such function could be developed I am happy to donate 20 USD.
Here I would suggest to create "donation buckets" for particular demanded functions, so more focus & performance can be achieved in development.
Guys who voting for new function adding to bucket particular amount. Developer can estimate workload and assign to bucket some value. 
Practical or not?

**Comment by PercyP** [comment]
@reeid 

I love the idea of Paid Feature Request/Donation Bucket - I would certainly be up for it. For example I would love to see the following integrations:

1. A method of creating invoices (including recurring invoices) that have a built in Paypal payment button (that sets up automatic subscriptions in paypal for recurring invoices) and possibly other payment methods
2. Integration with more open source shopping carts i.e. Virtuemart
3. Integration with Newsletter mailing i.e. Acyba
4. Ability for customers to see Gaant charts in Customer Portal and have a print / export function
5. Ability to add photo galleries in modules
6. An image field for uploading single images
7. A multi image field for adding multiple images

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3679

**Comment by bpabiszczak** [comment]
@reeid 
https://yetiforce.com/en/github/issues/206-system-development-ideas.html
