### ISSUE TITLE
Paid Feature Request/Donation Bucket

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#3679]
@PercyP

> @reeid
> 
> I love the idea of Paid Feature Request/Donation Bucket - I would certainly be up for it. For example I would love to see the following integrations:
> 
> A method of creating invoices (including recurring invoices) that have a built in Paypal payment button (that sets up automatic subscriptions in paypal for recurring invoices) and possibly other payment methods
> Integration with more open source shopping carts i.e. Virtuemart
> Integration with Newsletter mailing i.e. Acyba
> Ability for customers to see Gaant charts in Customer Portal and have a print / export function
> Ability to add photo galleries in modules
> An image field for uploading single images
> A multi image field for adding multiple images

**Comment by bpabiszczak** [comment]
@PercyP

Let’s be realistic. Right now the donations don’t exist, as far as I remember the donations altogether were 60€ for the past 12 months. We as a company invest $1.000 daily in the development. Don’t get me wrong - we are very grateful and appreciate every amount of donations, but they can’t have any real bearing on what we do. The problem is that many companies use it, but not many are willing to give something.

Some of you make money on this system, or deployed it in your companies without having to pay for other commercial systems, or save money on modules that in SuiteCRM, SugarCRM, coreBOS, or Vtiger aren't free. Unfortunately it doesn't translate into benefits for YetiForce itself, and as long as this imbalance remains, your donations won't really help that much.

**Comment by PercyP** [comment]
@bpabiszczak 

I get were you are coming from 100%. 

My understanding here was that say the community wanted a specific feature/functionality that wasn't planned by yourselves, that we could post it here, then, if a member of Yetiforce team thought it was a viable request (and/or that would also be a good add on to their paying customers) then Yetiforce would come back with an estimated cost for developing it, and that we (those community members who wanted it) could club together to purchase it somehow (I think donation system was mentioned as that is the only option here in this sort of community).  

60€ is pretty poor! I understand donations don't help. But I would expect there to be a little more appreciation from the community. Everyone knows it takes time and money to develop these things. Even a small subscription fee like other developers run i.e. 3 months, 6 months, 12 months etc. would be a start.

**Comment by kpaulaha** [comment]
I very much understand the difficulties Błażej adduce, as with every open source producer, where to get the incomes, it seldom is only a hobby. I also understand that YF cannot produce integrations to all possible systems as well as all wanted functions. @PercyP seems to be a Joomla fan, we use other programs and it would be nice to have integrations to them also, but I think it will be impossible to have them done by YF as open source just for us. We have been working with vtiger (and some others) for years and want finally to get rid of it and move over to YF. We are trying hard to get first deals with YF, it is not very easy with a new solution on the market, in spite of how good it is, needs local references. Anyhow, we have decided to pay a “commission donation” depending on profit, for every closed deal with YF to them who earns it, the yfcompany, worse targets of spending money have I seen. Sure it will not cover their costs, but something to show our respect for their work and try to keep it open source.
The donation bucket might work as above mentioned if there is enough of them who needs the requested function (and depending on the size of the community).

**Comment by PercyP** [comment]
@kpaulaha 

I suppose the 'commission function' would be kind of like licensing i.e. for every install a fee goes back to yetiforce? I too am starting out with yetiforce, having been with vtiger. I did love vtiger, but there was just something missing for me that yetiforce has - more ability to customise etc. and much better features and more rapid development. I only used it for myself and one small charity thats gone now, but when other small businesses see it, they want it themselves. So I am potentially looking to integrate it with the various Joomla components and then add the yetiforce support packages as part of it for any business I can get signed up - that's my plan. As you correctly identified, I am primarily Joomla, and prefer to focus on that. 

I love the concept of open source, but I do think it gets abused a bit. I don't like that. I would like to see more support for companies like this - particularly from its community, as it can be a win win situation if we all work in partnership (in a sense of everyone gets a slice of the pie - in particular the developers of the product). I too don't earn at the moment, as moved from a secure job into a risky idea of doing something for myself. So I do empathise with the guys here. 

Other ways I suppose that can generate income for them is for others to develop products for their marketplace i.e. add ons, and for yetiforce to take a percentage of those - I think vtiger does that already but not 100% sure?

What I am 100% sure about though, is if you are using this software, then make a contribution, these guys work hard on this, and it is kind of insulting that to date they have only received 60 euros!

**Comment by kpaulaha** [comment]
Well, it's only our style to do it, but as you said, if you use the program and if you have benefit of it, why not reward somehow the people behind it.

**Comment by pmontanez** [comment]
My two cents on this discussion is to start  building  a strong community, On many different open source projects that I had participate (Podio, Joomla, Zurmo, cp vesta etc) the difference between failure and success ( E.i being acquired by Citrix or Gravity4 etc..)  is the development of a strong community. With thousand of Yetiforce Evangelist and thousands of installations all around the world, the monetarize opportunities will be endless.  Keep it up guys, thanks for such a nice project...

**Comment by alextovey** [comment]
@bpabiszczak @PercyP How can we donate. I love this project and would like to donate some money.

**Comment by paula-w** [comment]
@alextovey on our [website](https://yetiforce.com/en/) in the upper right corner there's the "Donate" button.

**Comment by bpabiszczak** [comment]
To have more impact on our decisions, the community would have to generate more benefits – not for us, but for the product per se. Each question submitted to GitHub takes some of our time, which in return leaves us with less time to develop YetiForce. So it would be great if some of you could help the users who are new to YetiForce, answer their questions, and so on. Right now we invest a lot of money into the development, and even more time. All we add or change in the system is to make YetiForce the best open source CRM class system in the world [if it isn't already].

Right now we're adding a mechanism that no other open CRM that i know of can offer, namely multi database support [MySQL, PostgreSQL, MsSQL, MariaDB, Oracle etc]; it requires thousands of changes in core, and rebuilding many mechanisms, but it will ultimately result in an advantage when it comes to attracting large companies. Whenever we bring something new to the system we think about long-term results; you look at it in terms of Me & Now. Many of you won't understand why we now introduce changes related to database, even though nobody mentioned it on GitHub and the majority of you won't need it, but for some reason we spent 25.000 € on it, because in 5 years the benefits will outweigh the costs.

Together we can achieve so much more, that's why we consider our community extremely important. The donations are more important for you than they are for us, because if the community can collect let's say $1.500 per month, then we'll permanently assign a programmer who will and add features that you consider important and help you fix problems on an ongoing basis. It's up to you how dynamically the community grows, we will also help, but only as much as we can afford to do so.

Check how YetiForce keeps on growing [number of changes] compared to other projects:
![comparison_12m_per_week](https://cloud.githubusercontent.com/assets/10197525/19766793/0d2c58bc-9c50-11e6-85ec-7998aeb6f0ae.png)
![comparison_12m_sum](https://cloud.githubusercontent.com/assets/10197525/19766798/1120e668-9c50-11e6-90f3-1b60f8311b3e.png)

**Comment by alextovey** [comment]
Very nice. Well once I get this yetforce sorted for a customer I'll happily start buying support packages. As for helping out I will gladly help out if I can to help others to reduce time for yourselves to continue your excellent work.

**Comment by kpaulaha** [comment]
We try to help, when we can. Now running some local tests with a few companies (future customers?) on different servers. Will have all functions tested thoroughly for our own know-how too.

**Comment by alextovey** [comment]
I'm putting a few dedicated servers up for yetiforce testing and dev for myself. I'm not 100% up on centos/debian but its a learning curve.

**Comment by PercyP** [comment]
Hi,

sorry only just read this as been away for a couple of days. It would be good to know the following:

1. how many members on here are using yetiforce
2. how many members would be interested in signing up to a support package (so we can see how much each would need to pay to reach say the 1500 a month target)

If we can pull together enough members then I too would definitely be interested in paying in to a support for community users.

As I learn more about Yetiforce, I too pass back my knowledge and try to help others wherever I can, so I will keep doing this. 

The database support sounds amazing!

Percy

**Comment by cadre15** [comment]
Wow, I would love to help with database layer modifications to allow deployment in any database environment.

**Comment by paula-w** [comment]
Błażej’s response:

@PercyP 
It doesn’t work this way… if you can support the project then do so, don’t pay attention to what others do [you can set the donations to be automatic, even if it’s $5 - it’s better than nothing]. 
We don’t know how many people use it, but we got around 1k downloads weekly. We would like to know who and how uses the system, but we don’t want to force anything. In reality only a dozen or so companies  start working with the system weekly. The remaining downloads, I assume, result from curiosity. 
In the future we’ll try to add some kind of a form to send us feedback on the purpose of using YF – whether it's for production, demonstration, testing, and so on. 

@cadre15
You can help us, here’s an example:  https://github.com/YetiForceCompany/YetiForceCRM/commit/e1b72498bb0f70ce5af9f856f5ce97b13d5d8de1
Around 1.800 queries more have to be rewritten.
