### ISSUE TITLE
[PL]Brak funkcjonalności Roundcube przy próbie wysyłki masowych maili

### ISSUE THREAD

**Issue by slawekkow** [YetiForceCompany/YetiForceCRM#3680]
Problem:
Brak funkcjonalności roundcube przy próbie wysyłki masowych maili. 
Na https://gitdeveloper.yetiforce.com jest takie samo zachowanie.

Rzeczywiste zachowanie:
Roundcube niewłaściwie zachowuje się przy próbie wysyłki masowych maili (Kontakty > Akcje > Masowa wysyłka maili), (Kontrahenci > Akcje > Masowa wysyłka maili), (Lead > Akcje > Masowa wysyłka maili). Wystarczy nawet, że do wysyłki wybiorę 1 rekord. 
1. Okno Roundcube otwiera się w tym samym oknie, co YF, pomimo że w ustawieniach Roundcube jest zaznaczone "tworzenie wiadomości w nowym oknie"
2. Brak mozliwości zamknięcie okna Roundcube. Nie działa przycisk "Anuluj". Jedyną możliwością wyjścia z tego okna to klikanie "Wstecz"
3. Brak możliwości dodawania nowych adresów e-mail. Nie działają przyciski "Accounts", "Contaks" itd.
4. Po wysłaniu wiadomości okno Roundcube nie zamyka się.

Jak wywołać błąd:
1. zakładka "Kontakty", lub "Kontrahenci" lub "Leady"
2. zaznacz 1 lub 2 lub więcej rekordów
3. z zakładki "Akcje" wybierz "Masowa wysyłka maili"
4. Sprubuj: anulować wysyłkę, dodać nowe adrsy e-mail do wysyłki i zamknąć okno
   ![brak funkcjonalnosci roundcube przy probie wysylki masowych maili](https://cloud.githubusercontent.com/assets/22636658/19498628/5f782c5a-9592-11e6-82c2-2fb8337a8dd9.gif)

Środowisko:
YetiForce: v3.4.0 HOTfix3.4
Przeglądarka: Chrome 53.0.2785.143

Linuks
PHP: 5.6

**Comment by bpabiszczak** [comment]
1. Jeden problem jedno zgłoszenie. 
2. Konfiguracja roundcube dotyczy tylko poczty roundcube a nie przycisków w CRM, są to niezależne mechanizmy. 
3. Nie wiem czy błąd występuje na GitDeveloper, proszę sprawdzić. 
4. Brak jakichkolwiek logów...
