### ISSUE TITLE
[Bug] Customer Portal Not Showing Service/ Products Module

### ISSUE THREAD

**Issue by pmontanez** [YetiForceCompany/YetiForceCRM#3681]
#### Customer Portal Not Showing Service/ Products Module

Customer portal is not showing services nor Product related to the account, matter fact it does not show even the table frame or any indication that the web page is bound to the appropriate module.
![yeti-products-service-no show](https://cloud.githubusercontent.com/assets/22821273/19502997/adb957cc-957e-11e6-8f46-608b10b65fcf.png)
![yeti-products-service-no show-portal](https://cloud.githubusercontent.com/assets/22821273/19503007/bb16ccf6-957e-11e6-87d0-4ca293dbffbc.png)
#### Actual Behavior

I created some services and product and linked to the account,  I also check user permissions, then when logging into the Customer Portal, all other information is shown ( Account, Tickets, Projects..etc) except for services and products.

I also tried under the gitDeveloper site / portal environment with the same outcome. 
#### Environment
- YetiForce Version used: 3.4 + Hotfix 
- Browser name and version: Chrome latest Build 
- Operating System and version: Ubuntu 12.4  PHP 5.6

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/3681
