### ISSUE TITLE
Adding tabs to the top of a new module

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3682]
Hi, I'm running 3.4.121 Is it possible to add tabs such as documents, activites, emails, list of calls, service contracts to the top of candidates so we can see which documents are attached to the "Candidates" here is two screen shots, first one is the default module with all i need and the 2nd is the one without "custom module"
![tabs1](https://cloud.githubusercontent.com/assets/22075161/19511346/d435de4c-95de-11e6-8416-25e76f2c293c.GIF)
![tabs2](https://cloud.githubusercontent.com/assets/22075161/19511347/d438ec40-95de-11e6-8801-5f61bfb23d3d.GIF)

**Comment by skramanzia** [comment]
You tried to set relations in "Software configuration > Standard modules > Modules – Relations "??

**Comment by alextovey** [comment]
I've tried too but it doesn't allow it for some reason.

**Comment by florek41** [comment]
have you enable this in config file?
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/developer.php#L13

do it and then go to "Software configuration > Standard modules > Modules – Relations " like @skramanzia said.

**Comment by alextovey** [comment]
Brill, But it's not showing the attachments i've added to the documents section. :S 

Thank you @florek41
