### ISSUE TITLE
[Bug] Internal server error when try to login to roundcube

### ISSUE THREAD

**Issue by barra** [YetiForceCompany/YetiForceCRM#3683]
#### Internal server error when try to login to roundcube

when try to login to roundcube i get this error
![selezione_020](https://cloud.githubusercontent.com/assets/1047619/19513329/d7eaa228-95ef-11e6-83ae-543239d31c9b.jpg)
#### Actual Behavior

Clean Yetiforce with only admin user. I check php settings, and when enable debug, here phpError.log: 

[19-Oct-2016 11:28:18 Europe/Amsterdam] PHP Catchable fatal error:  session_regenerate_id(): Failed to create(read) session ID: user (path: /var/www/virtual/xxxxx/phptmp) in /var/www/virtual/xxxxx/htdocs/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_session.php on line 436
#### Your Environment
- YetiForce Version used: 3.4
- Browser name and version: Chrome Versione 54.0.2840.59 (64-bit) 
- Operating System and version: Ubuntu 16.04 64 bit

**Comment by PercyP** [comment]
@barra 

have you installed the hotfix? It is in the updates folder and needs to be installed after upgrading to 3.4

**Comment by barra** [comment]
@PercyP Yes, hotfix1 was installed.

**Comment by barra** [comment]
with php7 it was necessary update roudncube. For fix:
1- copy /modules/OSSMail/roundcube folder to /modules/OSSMail/roundcube_backup
1- replace content of folder /modules/OSSMail/roundcube with latest release get here: https://github.com/roundcube/roundcubemail
2- copy /modules/OSSMail/roundcube_backup/config/config.inc.php to  
 /modules/OSSMail/roundcube/config/
3- copy /modules/OSSMail/roundcube_backup/plugins to  
 /modules/OSSMail/roundcube/plugins

**Comment by barra** [comment]
i will try in few days.

**Comment by alextovey** [comment]
@barra Ah php 7 does not currently support ioncube. This is noted and they are currently working for a fix so im afriad you'll have to stick with php 5.6

**Comment by bpabiszczak** [comment]
Error 500 is an error Apache and not YetiForce.
Please check apache logs and please use only php 5.6.
