### ISSUE TITLE
Scheduled CSV Import

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3684]
Hello,

Can i Schedule a import from a csv file with reccurency at 1 hour?

I want to populate the account module and rewrite it with the info in the csv file every 1 hour, with a cron job or any orher automation.

**Comment by immhub** [comment]
Any Idea :)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
importing over 1000 records will be automatically swopped to CRON mode and import will be performed as CRON tasks.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Import/models/Config.php#L29
