### ISSUE TITLE
No Currency in Invoice

### ISSUE THREAD

**Issue by mcules** [YetiForceCompany/YetiForceCRM#3686]
I wrote some invoices and found out that i have no currency symbols in them.
All prices are without any currency.

System Currency is set to Euro. In the Services currencys are set also.
- YetiForce Version used: 3.4
- Operating System and version: Debian PHP5.6.25

**Comment by skramanzia** [comment]
@mcules Did you Test in the current development version??

Please see this link: https://yetiforce.com/en/github/issues/126-issues.html

**Comment by mcules** [comment]
Hi skramanzia,

i used the developer Version: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x/3.3.0_to_3.4.0

**Comment by skramanzia** [comment]
Hi @mcules This is the latest dev version

https://gitdeveloper.yetiforce.com/

**Comment by mcules** [comment]
Cant test it in your Demo, because PDF Export is not enabled.

**Comment by skramanzia** [comment]
Work fine PDF Export in Dev. you can change permission to remove, administrator user, to enable to all users(second image)

![image](https://cloud.githubusercontent.com/assets/3030997/19576832/fafe2ffe-96ea-11e6-99ad-8713c5cfaa8b.png)


![image](https://cloud.githubusercontent.com/assets/3030997/19576887/3fb78122-96eb-11e6-84ff-ddbac5287160.png)

**Comment by mcules** [comment]
Okay, i think there is no template for Invoice or i wrong?

**Comment by skramanzia** [comment]
Yes, no have invoice templates. You need create to test

**Comment by mcules** [comment]
Okay, i created an template in the demo and exported an pdf. Same behavior likes in my installation.

https://www.dropbox.com/s/x1gcgjsl6jthuxi/Screenshot%202016-10-20%2022.46.23.png?dl=0

**Comment by skramanzia** [comment]
Ok, check this link to update the issue to continue and evaluate the Label.

https://yetiforce.com/en/github/issues/126-issues.html

**Comment by mcules** [comment]
Dont know which information you need?
Think all informations are allready there?

**Comment by mcules** [comment]
Any News about this trouble?

**Comment by mcules** [comment]
Sorry for the push, but is there something new?
I need to send invoices to my customers ;)

**Comment by mcules** [comment]
Still no new News for that big Trouble?
It can not be that I am the only one who has this problem and that none of the Core developers would like to look at.
I can not write invoices for weeks and just think seriously again to switch to Vtiger.
Have you left any interest in this system?
Sorry but im a bit angry :(

**Comment by konadrian** [comment]
Can you give us more details on where the currency symbols are missing? For example mark it on a screenshot of a table.
