### ISSUE TITLE
SQL ERROR: SQLSTATE[42S02] Missing Table from DB

### ISSUE THREAD

**Issue by piercarlo62** [YetiForceCompany/YetiForceCRM#3687]
#### Issue

When I try to go in Modules fields modification I get  following SQL Error:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'b11_18957543_Yeti.vtiger_activity' doesn't exist

So in DB is missing the table vtiger_activity. (I check in DB and really missing)

And this error happen every where need to use the the missing table.

I would like to know the model of table to insert manually in DB.

Thankyou
#### How to trigger the error

1. Modules Insallation
2. Setup
3. ModifyFields
#### Your Environment

- YetiForce Version used: 3.4.0 + 3.4.X last hot fixes
- Browser name and version: Chrome last version - on windows 10 PC
- Environment name and version: PHP 5.6.23 - MySql 5.6.30
- Operating System and version: Linux - kernel version 3.2.40

**Comment by konadrian** [comment]
Links to the table model below:
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/install/install_schema/scheme.sql#L3101
