### ISSUE TITLE
[Bug] Software configuration > Security > Backup / not working

### ISSUE THREAD

**Issue by ABaumruck** [YetiForceCompany/YetiForceCRM#3688]
#### Issue

Backup function is not working
#### Actual Behavior

cron is activated, "Automation > Cron > Backup" = active
ftp is set up and running (tested from the command line)
no backup is created. 
Manual (first time) backup cannot be started, no mather if cron is enabled or not.
status message: "backup is scheduled"
#### additional information

I used YetiForce 3.2 before I switched to a clean 3.4 installation
There, a Backup was created (at least log entries where shown) but it was not transferred to the ftp.
In addition to this I am unable to find the .zip file on the local server (true for V3.2). Where should the file be?
#### additional question

When I enter the ftp credentials and hit save the connection is shown as green (hopefully means ok).
When I reenter the ftp settings page the connection is always shown as red. What does that mean?
What is the purpose of the "active" checkbox in the ftp settings? Checked or not it seems to make no difference.
#### Expected Behavior

backup should be created and transferred to the ftp server
#### How to trigger the error
1. enable Backup and backup-cron and wait
- YetiForce Version used: 3.4.21 -> clean install
- Browser name and version: Chrom V 53.0.2785.143
- Environment name and version: vServer
- Operating System and version: Ubuntu 16.04.3 LTS / PHP 7.0.8

BR Andreas

**Comment by serbiaserbia** [comment]
Same issue on my instalation yf 3.4

"When I enter the ftp credentials and hit save the connection is shown as green (hopefully means ok). When I reenter the ftp settings page the connection is always shown as red. What does that mean?" 
I tried everything the same as you,  and same issue.  No backup created. 
When reenter ftp connection is red again.  Cron active. In old 3.2 version I hade backup created with all same settings.

**Comment by paula-w** [comment]
The backup module has been removed from the system because the backup should be realized on the operating system layer, not on the application layer.
