### ISSUE TITLE
How to establish relation between Products and Storages submodules?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3689]
I need to establish relation between Product record and all GRN/GDN what contains this product as line item. How to make it?

**Comment by KatarzynaUlichnowska** [comment]
Could you please elaborate a bit more on the question, make a gif or add screenshots that would give us a bigger picture? We don't quite understand what you would like to achieve.

**Comment by vovpff** [comment]
@KatarzynaUlichnowska @bpabiszczak sorry for my late reply. I written some code in my local system and achieve needed result. I will post my sample code here after new year selebration.

Happy new year for Yeti crew!

**Comment by KatarzynaUlichnowska** [comment]
Great news! Happy celebrations :)
Yeti crew also wishes all the best for 2017!
