### ISSUE TITLE
Install: Blank page

### ISSUE THREAD

**Issue by barra** [YetiForceCompany/YetiForceCRM#3690]
#### Issue
Install: Blank page
After first page i get blank page

#### Actual Behavior
log: 
Notice: Use of undefined constant ROOT_DIRECTORY - assumed 'ROOT_DIRECTORY' in /var/www/virtual/xxxxxx.it/htdocs/include/ConfigUtils.php on line 161 Notice: A session had already been started - ignoring session_start() in /var/www/virtual/xxxxxx.it/htdocs/libraries/HTTP_Session/Session.php on line 160 Parse error: syntax error, unexpected '.', expecting ',' or ';' in /var/www/virtual/xxxxxx.it/htdocs/vendor/yetiforce/Purifier.php on line 16 

#### For fix: 
edit this: /vendor/yetiforce/Purifier.php line 16: 
```
	private static $htmlEventAttributes = 'onerror|onblur|onchange|oncontextmenu|onfocus|oninput|oninvalid|onreset|onsearch|onselect|onsubmit|onkeydown|onkeypress|onkeyup|' 
		'onclick|ondblclick|ondrag|ondragend|ondragenter|ondragleave|ondragover|ondragstart|ondrop|onmousedown|onmousemove|onmouseout|onmouseover|' .
		'onmouseup|onmousewheel|onscroll|onwheel|oncopy|oncut|onpaste';

```
to:

`	private static $htmlEventAttributes = 'onerror|onblur|onchange|oncontextmenu|onfocus|oninput|oninvalid|onreset|onsearch|onselect|onsubmit|onkeydown|onkeypress|onkeyup|onclick|ondblclick|ondrag|ondragend|ondragenter|ondragleave|ondragover|ondragstart|ondrop|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|onmousewheel|onscroll|onwheel|oncopy|oncut|onpaste';`

#### Your Environment

* YetiForce Version used: developer branch & 3.4
* Browser name and version: anyone
* Operating System and version: ubuntu14.04, imsc-p ad hosting panel.

**Comment by barra** [comment]
Sorry, error due to old php version.

**Comment by Jedwards-Eric** [comment]
Same issue here with Ubuntu and PHP 5.5.9.  I removed the unneeded concatenation dots and it works.

**Comment by ldgbc** [comment]
Yetiforce 3.4

I initially tried the method mention above and it does not work. It was due to using PHP7, which I thought 3.4 was compatible with but I guess it wasn't. Switched back to PHP5.6 and it work.
