### ISSUE TITLE
[PL]Tworzenie procesów sprzedażowych z poziomu wiadomości e-mail

### ISSUE THREAD

**Issue by slawekkow** [YetiForceCompany/YetiForceCRM#3694]
**Problem:**
W dokumentacji jest napisane, że w przypadku tworzenia procesów sprzedażowych takich jak: szanse sprzedaży, zapytania ofertowe, czy karty wymagań z poziomu wiadomości email, pole temat zostanie automatycznie wypełnione na podstawie tematu wiadomości.
Niestety ani na na https://gitdeveloper.yetiforce.com v3.4.213 ani na mojej instalacji tak się nie dzieje.

**Jak wywołać błąd:**
1. otwórz wiadomość e-mail
2. spróbuj dodać któryś z wyżej wymienionych procesów sprzedażowych.
3. zobaczysz, że pole Temat nie zostało automatycznie uzupełnione

Środowisko:
YetiForce: v3.4.0 HOTfix3.4
Przeglądarka: Chrome 53.0.2785.143
Linuks
PHP: 5.6

**Comment by bpabiszczak** [comment]
Temat i tak by było trzeba zmazywać i ręcznie wprowadzać poprawny. Obecnie ma to niski priorytet a jeśli by się pojawiło to tylko jako opcja domyślnie wyłączona. Dokumentacja w 2017 będzie uaktualniana.
