### ISSUE TITLE
Create custom page

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3695]
Hello,

How can i create a custom page in yetiforce?
I want to add next to the modules in the menu, a page with custom html functions.
When i click on that menu link the page will open in yetiforce just like a module.

Can it be done?

**Comment by mariuszkrzaczkowski** [comment]
Create a simple view, examples:
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/modules/Vtiger/views
