### ISSUE TITLE
[BUG] Record Numbering displayed incorrectly

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3697]
v.3.4.200
Record Numbering displayed incorrectly
Tested on vtiger v6.5 is works well.

![screenshot 11](https://cloud.githubusercontent.com/assets/19627226/19638596/df351f46-99fe-11e6-90b8-002afe25acc2.png)
![screenshot 12](https://cloud.githubusercontent.com/assets/19627226/19638599/e143d534-99fe-11e6-8e97-c507c4f96f2d.png)
![screenshot 13](https://cloud.githubusercontent.com/assets/19627226/19638602/e508a460-99fe-11e6-9c10-0d04efd26653.png)
![screenshot 14](https://cloud.githubusercontent.com/assets/19627226/19638606/e6d07dc2-99fe-11e6-821f-7c8f5510abbb.png)

**Comment by paula-w** [comment]
Right now we are not going to realize it, because it's a new matter. We might change it in the future.
