### ISSUE TITLE
[How to] relate documents from email attachment to Account record?

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3699]
When I recive email with attachment,  how to relate it with Account record? 
I know possibility go to Account -> Document tab -> Select document -> and find it on long,  long list. Plus I have to remember document name (sometimes it could be difficult,  for example doc15659prop.doc)
Is there any automation for this? Cron,  Workflow, setting, to bind all recived attached documents?

Regards

**Comment by KatarzynaUlichnowska** [comment]
The system downloads emails and attachments by default and creates an email in the "Corporate emails" module and adds attachments. You can change it and create a possibility to add documents directly from Rouncube. Any other change is also possible but they require some programming and currently, we don't have any orders for such changes.
