### ISSUE TITLE
Customer portal doesnt send username informations

### ISSUE THREAD

**Issue by VSecurity** [YetiForceCompany/YetiForceCRM#37]
What can i do? My workflows works normally but I don't receive the customer portal login and password. I already configurated URL Path on Portal/Config/Config.php.

**Comment by vjstyla** [comment]
Hello All,

I have created the contact and I dont know why the CRM only sents User name but not the password to login to the Portal...Please help

**Comment by bpabiszczak** [comment]
New problem new issues. Please read this: https://yetiforce.com/en/ideas,-changes,-bugs/bugs/126-how-to-report-bugs.html
