### ISSUE TITLE
[How to] Where to place products for purchase? 

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3700]
Currentlly we are recive a lot of quotation from our suppliers for products we plan to purchase. 
We have 50 potential suppliers,  potential 150 products with specifications and prices. 
Have to choose about 10 products from 2-3 supplier.

Where to put these all product proposal and potential supplier?  In Product module,  and make new field "purchase" to separate products from our product portfolio for selling?

It good to have in database all potential products for buying, prices and suppliers. 

Have any proposal?  What is your practise in use?

**Comment by PercyP** [comment]
Hi,

you need to have a play with yetiforce. All these things you ask for are already in the system. Look under Databases for products and services and look under contacts for suppliers etc.
