### ISSUE TITLE
BUG - Service Contract Status

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3702]
#### Issue

When the state of the service contract is not "In Progress" should not appear to select.
#### Actual Behavior

All Service Contract see to select

![untitled](https://cloud.githubusercontent.com/assets/3030997/19658697/43d434d2-99ff-11e6-9d99-86dc9478f87f.gif)
#### Expected Behavior

 See Only Active Service Contracts (In Progress)
#### Your Environment

- YetiForce Version used: Latest GIT Dev
- Browser name and version:
- Environment name and version:
- Operating System and version:

**Comment by skramanzia** [comment]
They need more information?

thanks

**Comment by bpabiszczak** [comment]
any arguments?

**Comment by skramanzia** [comment]
@bpabiszczak When a service contract is overdue or in any state other than the "Ongoing", it should not be available for selection as it would not be active.

**Comment by bpabiszczak** [comment]
![image](https://cloud.githubusercontent.com/assets/10197525/24323658/35e6e012-1179-11e7-9756-dbf7e33792b7.png)
