### ISSUE TITLE
[BUG] SEARCH OWNERS BY AJAX ERROR

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3704]
#### Issue

Search use ajax does not work when set value 'SEARCH_OWNERS_BY_AJAX' => true
Related Modules: Global search, workflows, recording control
#### Actual Behavior

![anh123](https://cloud.githubusercontent.com/assets/19627226/19673650/0933f26a-9aac-11e6-9d1d-b1108c71f2d0.gif)
![workflows](https://cloud.githubusercontent.com/assets/19627226/19673653/0b30fe3c-9aac-11e6-8fb3-b14e5f87750e.gif)
![recording control](https://cloud.githubusercontent.com/assets/19627226/19673654/0e38a706-9aac-11e6-9789-915aca648f38.gif)
#### Your Environment
- YetiForce Version used: 3.4.235
- Browser name and version: Chrome 53
- Operating System and version: PHP7

**Comment by skramanzia** [comment]
Same in stable version and with PHP5.6

**Comment by ezbank** [comment]
:(

**Comment by serbiaserbia** [comment]
@ezbank
How did you made this customisation in colors of your YF? 
Did you do some programming or somewhere in confog menu? 
It looks very fresh.  :-)

**Comment by ezbank** [comment]
it's theme modern :)
This bug not important??

**Comment by serbiaserbia** [comment]
@ezbank 
Yes it is modern,  how did you get color customisation,  with code modification or in menu somewhere? 
I would like to help with this bug but I am not competent and have no big experience, sorry.   😉

Regards
