### ISSUE TITLE
[BUG] YetiforcePortal v3.2 create.php module is missed

### ISSUE THREAD

**Issue by speakerua1** [YetiForceCompany/YetiForceCRM#3705]
![create_php](https://cloud.githubusercontent.com/assets/16084556/19678597/123984b0-9aa7-11e6-804e-40f6de1779ef.gif)

#### Issue

YetiforcePortal create.php module is missed
#### Actual Behavior

YetiforcePortal create.php module is missed
#### Expected Behavior

YetiforcePortal create.php module is missed
#### How to trigger the error

YetiforcePortal create.php module is missed
#### Your Environment

- YetiForce Version used: 3.4.21 + YetiforcePOrtal 3.2
- Browser name and version:
- Environment name and version:
- Operating System and version:

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/3681
