### ISSUE TITLE
[Question] How to add 10 latest comments to PDF

### ISSUE THREAD

**Issue by rage1985** [YetiForceCompany/YetiForceCRM#3706]
Hi Mates,

i created a PDF-Template for a Customer/Account Report which should be exportable from Record view.
Fields from Account and linked Contact Records are selectable which is awesome ^^.

But i can´t seem to make the last 10 Comments from ModComments Module regarding the Account exportable/linkable. You can seem to make a Template for Comments and Link the Account-Fields but this Template does not show up anywhere ;-(

Am i missing something here?

**Comment by mariuszkrzaczkowski** [comment]
$(record : Comments 10)$
