### ISSUE TITLE
[PL] Kontakty w podglądzie szansy sprzedaży

### ISSUE THREAD

**Issue by yetitest** [YetiForceCompany/YetiForceCRM#3708]
#### Issue

![aa](https://cloud.githubusercontent.com/assets/22539294/19718138/4ff90bf0-9b64-11e6-85f0-0ad0919715e8.JPG)

Jak na zrzucie w sekcji kontakty po dodaniu kontaktu do szansy wyświetla się tylko Imię tego kontaktu.

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Chrome

**Comment by bpabiszczak** [comment]
Ponieważ tak jest skonfigurowany widżet, można w nim zmienić ilość wyświetlanych kolumn.
