### ISSUE TITLE
[critical bug] Need a hotfix for 3.4.0(21) - Problem with wrong amount

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3709]
#### Issue

When you enter a "estimated value" in Opportunites or the "Campaign budget" in Campaign. The System remove some numbers and save a wrong Amount!
In the actual developer version (3.4.275), the problem not exists. But we need a hotfix for the actual stable version (3.4) or a hint what we must fix! I found no ticket for this :-(
see also #3638 (comment skramanzia 19.10.16 16:53)
#### Actual Behavior

The system save the wrong amount!
#### Expected Behavior

The system save the correct amount!
#### How to trigger the error

![bug1](https://cloud.githubusercontent.com/assets/10259801/19720522/c4f8f802-9b6e-11e6-801b-ddfb3e3f319b.gif)
#### Your Environment

- YetiForce Version used: 3.4.0 with hotfix 3.4.21
- Browser name and version: firefox & chrome
- Operating System and version: windows 10

**Comment by SkavenKF** [comment]
I don't understand Polish, but i think this is the same problem #3678

**Comment by yetitest** [comment]
Ticket for this in PL ->  https://github.com/YetiForceCompany/YetiForceCRM/issues/3678

**Comment by yetitest** [comment]
I think it is related to Report Currency formating #3701

**Comment by SkavenKF** [comment]
When i remember, the problem in the report already exists in 3.3.

**Comment by SkavenKF** [comment]
I think i found the solution. See ticket #3659 and the https://github.com/YetiForceCompany/YetiForceCRM/commit/f0972daae406336f183451618029ec6a650b16c0

In my opinion, this should be a hotfix for the actual "stable" version.

**Comment by yetitest** [comment]
it would be nice to have a hotfix for this

**Comment by alextovey** [comment]
I've had this issue. it appears there is a issue when removing sections from the advanced section in the invoice. The Dev version works and this is hotfixed.

**Comment by SkavenKF** [comment]
@alextovey: We are talking about a stable version, not a developer version. In my opinion, when you would have a stable release (3.4.0), you need patches or hotfixes for critical bugs (and i think the problem with the currency field, was a critical bug). You cannot change to a developer version (with many new bugs, not tested features, ...), you have no update files and no garantue for the update to the next "official" release. Without a hotfix you cannot name this release stable, when you not repair bugs. 
No Management would use a production system, when the system stability is not secured!
