### ISSUE TITLE
problem with Language management

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#371]
Editing language with Language management not worked from ab. version 1.3.151. With earlier versions worked fine.

//kpa
![2015-03-13 16_51_09-langmanagement](https://cloud.githubusercontent.com/assets/10330264/6640754/1388f8d2-c9a2-11e4-815a-26ac5d7e88f4.png)

**Comment by bpabiszczak** [comment]
I'm using version  1.3.160 and it works fine. Please send me more details.

**Comment by kpaulaha** [comment]
Well, we have on same server version 1.3.82, 1.3.96, 1.3.115 and they work fine. Then the new installations above 1.3.151 on the same server do not work. I can delete, set as default, export but not edit the language files or the help icons. 

console says: 
Uncaught NotSupportedError: Failed to execute 'animate' on 'Element'
Failed to load resource

**Comment by bpabiszczak** [comment]
please check last version.

**Comment by kpaulaha** [comment]
There was a missing comma in en_us\Settings\BackUp.php on line 32. Works now.

//kpa

-------- Alkuperäinen viesti --------
Lähettäjä Błażej Pabiszczak <notifications@github.com> 
Päivämäärä: 14.03.2015  13.04  (GMT+02:00) 
Vas. YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio kpaulaha <kimmo@tigersoft.fi> 
Aihe Re: [YetiForceCRM] problem with Language management (#371) 
 
please check last version.
