### ISSUE TITLE
[BUG] Calendar config color

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3710]
#### Issue

The color setting  of labels in activities calendar is not correct. It is only work with "Task", but "Call" and "Meeting" are not showed. This is not entered into the  database.
#### Actual Behavior

![calendar](https://cloud.githubusercontent.com/assets/19627226/19761360/cc846ed4-9c5f-11e6-9f92-5f40905d92bf.gif)
![screenshot 18](https://cloud.githubusercontent.com/assets/19627226/19761663/141bcfd4-9c61-11e6-885c-52d06c806468.png)
#### Expected Behavior

![screenshot 17](https://cloud.githubusercontent.com/assets/19627226/19761380/df53ccd0-9c5f-11e6-8bd0-22d97d574f76.png)

- YetiForce Version used: 3.4.315
- Browser name and version: Chrome 54

**Comment by alextovey** [comment]
I've noticed chrome for some reason caches the changes. try doing them in IE and then clear cache in Chrome if you can.

**Comment by ezbank** [comment]
I think this is the problem of the database.
