### ISSUE TITLE
[PL]Powiązanie Szansa sprzedaży - > Kampania marketingowa

### ISSUE THREAD

**Issue by yetitest** [YetiForceCompany/YetiForceCRM#3711]
#### Issue

W nawiązaniu do zgłoszenia [3614](https://github.com/YetiForceCompany/YetiForceCRM/issues/3614)
czy istnieje możliwość powiązania modułu szans sprzedaży z modułem kampanii tak aby prezentować z jaką kampanią jest/była powiązana dana szansa.

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Chrome

**Comment by bpabiszczak** [comment]
w nowej wersji powiązanie powinno działać.
