### ISSUE TITLE
[question] workflow problem

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3713]
Anybody else having problem with workflow sending emails with v. 3.4? It has worked with earlier versions, on same servers, but not with 3.4. Sends smtp test-mail, all other workflow tasks working, but not sending email template or sending email. Just wondering if it is a common "feature" or issue with our servers. 

#### How to trigger the error

1. workflow with manual trigger sending email

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version:
* Environment name and version:
* Operating System and version: Debian 8.5 and ubuntu server 10.04

**Comment by speakerua1** [comment]
It works on mine.

**Comment by kpaulaha** [comment]
ok, just noticed that customer portal login-info mail is sent, but the one with manual trigger not. Well, needs studying.

**Comment by kpaulaha** [comment]
Hmm, now it works with no changes, really do not know what the reason was. But noticed that when removed condition "Portal user  > has changed" the portal login information was sent.
