### ISSUE TITLE
Use "relative fields" in reports module

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3716]
It could be nice to have the possibility to use "relative fields" in reports module.
For example campaign membership of an account or a lead.

I made a gif on gitdev version to be more explicit.
![gif](https://cloud.githubusercontent.com/assets/1357727/19803187/a0346034-9d07-11e6-9012-0d3c626e5770.gif)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
you can't see relative fields because you didn't select in the first screen.
