### ISSUE TITLE
Yeti portal issues

### ISSUE THREAD

**Issue by cogitologue** [YetiForceCompany/YetiForceCRM#3718]
#### Issue

Portal installation issues
#### Actual Behavior

Only english language is displayed 5 times as an option
then next screen
Fatal error: Call to undefined method UserTimeZones::userTimeZones() in /home/(ftpname?)/portal.(mydomain).com/install/views/Index.php on line 156
#### Expected Behavior

I would like to see my language or the list of langaues (english, french, polish...)
then
I would like to go to the portal !
#### How to trigger the error
1. unzip portal
2. ftp to my portal.domain.com
3. go to Url portal.domain.com
#### Your Environment
- Yetiforce 3.4.0 + last hotfix 3.4x-hotfix
- YetiForce portal last version 'YetiForceCRM-developer.zip)
  ![yeti4](https://cloud.githubusercontent.com/assets/7788771/19827687/d00cd056-9db2-11e6-8dd6-db01571c050e.gif)

**Comment by kpaulaha** [comment]
The portal releases are found here https://github.com/YetiForceCompany/YetiForcePortal/releases. 
You do not install it, unzip and configure the config-files. https://yetiforce.com/en/implementer/installation-updates/129-customer-portal-instalation.html

**Comment by cogitologue** [comment]
ok...Thks for the answer ...I setup according to the doc now...I waited for my https to be activated...
I created a contact and received a mail with email/password to connect to portal...then I got this error

Error!!!
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'khyozcom_yeti979.a_yf_bruteforce' doesn't exist Failed to prepare SQL: SELECT * FROM `a_yf_bruteforce`

![yeti6](https://cloud.githubusercontent.com/assets/7788771/19834618/e24d08e4-9e66-11e6-8d66-567abc2cbb38.gif)

**Comment by kpaulaha** [comment]
Seems to me that you are trying to log in to the  crm, not to the portal.

**Comment by cogitologue** [comment]
Set the address - modify config/config.php file and change a path for the CRM system [$vtiger_path]. That's how the portal will detect CRM and know from where to download data, which is displayed to a user.

what do you mean by that ?
file config.php has no variable [$vtiger_path]
and I copied the file config.inc.php from CRM because it was empty when unzipped. Is that incorrect ?

I tried to find examples on the net...but without success...Not as easy as that to set up...
If you have some idea, I would appreciate. Thks

**Comment by cogitologue** [comment]
ok, I believe I didn't download the right portal package. My mistake. I will redo the installation. I can see the [$vtiger_path] in this one...I will keep you updated. Sorry !
