### ISSUE TITLE
Email Notification to new users

### ISSUE THREAD

**Issue by brijeshkeni** [YetiForceCompany/YetiForceCRM#3719]
#### Issue

When i create a new user with all the credentials, no email is sent to the user that his account is created with his username and password.
#### Actual Behavior

When a new user account is created; no email is sent to the user to notify his credentials.
#### Expected Behavior

email should be sent to the user with his access credentials and link to start with using the CRM
#### How to trigger the error

just create new user 
#### Your Environment
- YetiForce Version used: YetiCRM 3.4.0
- Browser name and version: Google Chrome Version 54.0.2840.71 m (64-bit)
- Operating System and version: Windows Server 2008 R2

**Comment by kabelo38** [comment]
Which User a system user or a portal user

Check if you have enabled workflows

Software configuration > Automation > Workflows

![workflow](https://cloud.githubusercontent.com/assets/5912376/19845900/0d220082-9f44-11e6-9ddf-3f8d41fb0857.png)

**Comment by brijeshkeni** [comment]
I am creating a system user. what I want to achieve is when a system user is created; he should be sent an email with the credentials such as the username and password and the link from where he can access the YetiForce CRM. I did try to create a workflow but i did not see any option where i can trigger an email when a new system user is created. Can you please advise if there is such an option?

Best Regards,
Brijesh

**Comment by brijeshkeni** [comment]
Dear Team,

Can anyone please help on issue above.

Best Regards,
Brijesh

**Comment by paula-w** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/3749
