### ISSUE TITLE
[bug] Customer portal

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3720]
#### Issue

Not able to add tickets through customer portal. Customer portal not showing related projects, documents.
![portal](https://cloud.githubusercontent.com/assets/10330264/19828280/ad0d6ce2-9dca-11e6-9e77-686db5a5e689.gif)
#### Your Environment

- YetiForce Version used: 3.4 + hotfix, portal 3.2.2
- Browser name and version:
- Environment name and version:
- Operating System and version:

**Comment by speakerua1** [comment]
Same problem #3705

**Comment by pmontanez** [comment]
Same problem #3681 -

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/3681
