### ISSUE TITLE
Can not add records

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#3722]
#### Issue
Cant add records.

#### Actual Behavior
After adding Account or Contact I am diverted to error page with: 

Permission denied
Record you are trying to access is not found
Home page

#### How to trigger the error
This is second installation on server which is running php 5.6 and all preinstallation requirements are fulfilled.

#### Your Environment

* YetiForce Version used: 3.4 master
* Browser name and version: Chrome, FF
* Operating System and version: centos

Vtiger 6.5 on the same server running fine.
Test app is chmoded to 777 and group/user is apache:apache

**Comment by waran70** [comment]
I run in similar problem with one of customer. He is on Centos and php 5.6
No time yet to look closer but exactly the same behavior - Can not add record, or record is not accessible

**Comment by PercyP** [comment]
I had similar problems. First I had to make sure all criteria was met in yetiforce configuration requirements - this is important. 

Second I had to change permissions using an ftp client as the changes made directly on the server were not applying.

I am using yetiforce 3.4 (WITH HOTFIX - IMPORTANT!!) php 5.6 on 2 test sites - one a shared hosting the other a VPS with Centos.

Settings vary depending on which of those your yetifirce is installed on

**Comment by waran70** [comment]
The strange is that it sometimes work sometimes is not!! 5 min ago I can add products and accounts but now I can not! O.O

But, when I reboot system all going well for some time....  for some short time and than again can not create or access records. 

Server configuration is in line with recommendation.  No modifications to the system at all.
Permissions to files OK

**Comment by bpabiszczak** [comment]
Błąd braku uprawnień do rekordu to informacja generowana przez YetiForce. System operacyjny, wersja i konfiguracja PHP nie ma z nim nic wspólnego. Takie problemy należy weryfikować indywidualnie po weryfikacji konfiguracji uprawnień. Niestety nie opisałeś jak można błąd wywołać na gitdeveloper więc nie mamy Tobie jak pomóc.
