### ISSUE TITLE
Debugging issue

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#3724]
As per https://yetiforce.com/en/developer-documentation/engine/115-debugging.html
In "config/performance.php" should be line with: 'LOG4PHP_DEBUG' 
but is not. Is there different way in latest master?

**Comment by bpabiszczak** [comment]
All you need is here: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/debug.php
