### ISSUE TITLE
Quick create of bookkeeping record fail

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#3725]
### Issue
Quick create from organization module of bookkeeping record fail

#### Actual Behavior

 Fatal error: Call to a member function fetch() on boolean in /home/mydomain/domains/mydomain.com/public_html/crm/include/database/PearDatabase.php on line 271

**Comment by waran70** [comment]
i actually create records but with above mentioned error

**Comment by paula-w** [comment]
Take a look at [this article]( https://yetiforce.com/en/github/issues/126-issues.html ) and please add all the missing info.
