### ISSUE TITLE
Activity Report

### ISSUE THREAD

**Issue by zwieja** [YetiForceCompany/YetiForceCRM#3728]
There is a way to create report from user activity from past days ?
I know there is a widget but it is insufficient.

#### Your Environment

* YetiForce Version used: 3.3
* Browser name and version: Chrome latest

**Comment by zwieja** [comment]
@nic86 Can you help me ?

**Comment by galciu** [comment]
Or is it possible to create report where we can list what user has done for last week/month?
We also can't find way to do it. :(

**Comment by galciu** [comment]
Hello again, can we please get answer for this problem?

**Comment by paula-w** [comment]
[Analyzer](https://shop.yetiforce.com/en/products/11-analyzer.html) can display users' activity, but it doesn't generate reports. 
We can always create a new functionality for you, but it will be a paid one.
