### ISSUE TITLE
[IDEA] Always up to date version of the system

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#373]
Write module to update the system with manual and automatic updating via the scheduler.

In the settings add function updated to the latest stable version is not to github or only update to the stable version, as usual in many programs do

**Comment by bpabiszczak** [comment]
It’s not a notepad, but a business application with a high priority. There is not way such application could update itself. In practice, in professional deployments, the server on which the application is, doesn’t even have the Internet connection! Our update pack is so simple that we think that any additional mechanisms are unnecessary! We don’t have any plans for the future that would include such solutions.
