### ISSUE TITLE
BUG - Report Current GIT Stable and Dev

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3730]
#### Issue

![ezgif com-optimize 1](https://cloud.githubusercontent.com/assets/3030997/19935708/c2283f6c-a0f9-11e6-9a6d-0e6198e78ba8.gif)

#### Your Environment

* YetiForce Version used: GIT Stable 3.4
* Browser name and version: Firefox Latest
* Environment name and version:
* Operating System and version:

**Comment by skramanzia** [comment]
Hi @TomaszQr , I've seen that you've fixed the problem number 3. It is possible to solve problems in the reports of the stable version?. The reports are the main tool of a CRM

**Comment by skramanzia** [comment]
Same in Current Dev 3.4.385

**Comment by skramanzia** [comment]
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/3030997/19981712/cecb3ca4-a1e1-11e6-916d-cc2caa83b576.gif)

**Comment by paula-w** [comment]
The rowCount error no longer exists. 
If there's anything else please provide us with a description, because we can't figure out what you're showing us in the gifs.

**Comment by skramanzia** [comment]
@paula-w I can't verify Report because have a other critical issue. See the gift please. Thanks!

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/3030997/21543628/016e6884-cda7-11e6-8de1-3ccdd0732cf9.gif)

**Comment by paula-w** [comment]
The error that made it impossible for you to check it again has been fixed.
