### ISSUE TITLE
Standard modules> Fields - Dictionaries

### ISSUE THREAD

**Issue by slawekkow** [YetiForceCompany/YetiForceCRM#3732]
Hi everyone,
whether there is any way to mass import industry and subindustry?
Thank you in advance for your help.

**Comment by PercyP** [comment]
@slawekkow 

what do you mean by dictionaries?

You should be able to import industries/sub industries through the normal import process - just make sure you select the correct parent fields

**Comment by slawekkow** [comment]
@PercyP 
thanks. I worked it out

**Comment by PercyP** [comment]
@slawekkow 

are you able to tell us how you worked it out? Just in case others have the same problem and saves the developers having to keep answering same questions

**Comment by slawekkow** [comment]
I thought that the ability to import industry and subindustry should be placed directly against the System Configuration> Standard Modules> Fields - Dictionaries> Contractors and Lead. Unfortunately, there can only add single value.
It turned out that in order to add new in bulk industries and Parent to import or contractors Leads
