### ISSUE TITLE
Menu not displayed on Firefox

### ISSUE THREAD

**Issue by cadre15** [YetiForceCompany/YetiForceCRM#3733]
#### Actual Behavior

Launch latest version of Firefox browser to https://gitdeveloper.yetiforce.com/

The menu on the left is hidden. This is not correct.
#### Expected Behavior

The menu should appear on the left panel. 
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:3.4.0
* Browser name and version:Firefox 49.0.2
* Environment name and version: GNU/Linux
* Operating System and version:Debian 8.5

I installed a fresh copy of YetiForceCRM ver 3.4.0.

I have connected to gitdeveloper and it still not fixed.

The Solution is to update the CSS from line 3557 in layouts/basic/skins/style.css

Add before line 3560
position: fixed !important;

That's it. This fix works for all versions of Firefox 38.0.1 to 49.0.2

**Comment by paula-w** [comment]
Can you check it once again? I just checked it in Firefox, same version as yours, and it works for me with no problems.
In case you still experience the issue please attach some screenshots.
And if you could, please instead of the lines let us know to which class the line should be added.

**Comment by cadre15** [comment]
It's in class .leftPanel  .slimScrollDiv on line 3557.

**Comment by cadre15** [comment]
Oh. Further careful tests reveal that Firefox is ok from ver 43.0.1 to latest 49.0.2.
