### ISSUE TITLE
No edit access to Sold Services records

### ISSUE THREAD

**Issue by xparadell** [YetiForceCompany/YetiForceCRM#3734]
After creating Sold Services records with a user with "admin profile" I'cant edit Sold Services Records.
"Admin profile" has defined full permission to Sold Services Module.
When trying to edit the record by clicking inline edit icon (up-right edit menu icon do not appear) i get the following message:

**Permission denied
You don't have the permissions required to view/edit this record. Contact the administrator if you should have the permission to view it.**

I previously translated some strings for that module to catalan language, using the built-in translation interface. I guess that has no influence to this bug.

* YetiForce Version used: 3.4.0
* Browser name and version: Google Chrome 54.0.2840.71 m

**Comment by mariuszkrzaczkowski** [comment]
Check what your logs say
