### ISSUE TITLE
[bug] Time Control Reports

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3735]
#### Issue
Adding "Assigned to" in report of Time Control don't work

#### How to trigger the error
![report](https://cloud.githubusercontent.com/assets/10330264/20004074/c4d926dc-a292-11e6-9722-d01e78c57908.gif)

#### Your Environment

* YetiForce Version used: 3.4.0 gitstable.yetiforce.com
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by skramanzia** [comment]
Same Error when add this field.

![image](https://cloud.githubusercontent.com/assets/3030997/20005182/73bbcdae-a26f-11e6-8fda-bfa8541eae90.png)

And in Current Dev
![image](https://cloud.githubusercontent.com/assets/3030997/20005162/527471d2-a26f-11e6-80d8-11f8795cd5f3.png)


Related Issue (Not resolved yet)
https://github.com/YetiForceCompany/YetiForceCRM/issues/3533

https://github.com/YetiForceCompany/YetiForceCRM/issues/3608


Please @bpabiszczak Its possible to resolve this? I know they are working a lot on improvements. I believe that the reports are a fundamental part of any system. In my case it is the tool to justify the implementation of the new CRM.

Thanks in advanced

**Comment by kpaulaha** [comment]
Tried the fix for "Assigned to" in report of Time Control, not working on 3.4.0. Shows a blank page.

**Comment by skramanzia** [comment]
Its true, after apply the commited change i can see the"users" but filters not working.

**Comment by skramanzia** [comment]
@TomaszQr Its works in your environment? may be is a query issue

**Comment by krobin8** [comment]
The fix for Assigned To does work, but if you add any other related field such as "Process" or "Company/Contact" you have the same issue.
