### ISSUE TITLE
[BUG] Currency

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3739]
v 3.4.0

![demo](https://cloud.githubusercontent.com/assets/19627226/20050119/f684911c-a4f9-11e6-8947-e3cd27840916.gif)

**Comment by Raggazzoo** [comment]
I have the same issue for weeks it is very annoying because it corrupts already existing data...

**Comment by kpaulaha** [comment]
For us it works on clear installation of 3.4 +hotfix, but not when updated from earlier versions.

**Comment by SkavenKF** [comment]
@kpaulaha: it is fixed with #3659 (version 3.4.218) and not with the hotfix. Also see my ticket #3709 !!!

**Comment by kpaulaha** [comment]
@SkavenKF suprise, it works v. 3.4.0
![currency](https://cloud.githubusercontent.com/assets/10330264/20063658/afea851a-a510-11e6-9203-51754f715226.gif)

**Comment by SkavenKF** [comment]
@kpaulaha: interesting  :confused:  Have you patched your file, see https://github.com/YetiForceCompany/YetiForceCRM/commit/f0972daae406336f183451618029ec6a650b16c0?
At the official gitstable or gitmaster it don't work  :cry: 

At yf. tigersoft .fi it is also wrong ... i entered 500000,-
![bug](https://cloud.githubusercontent.com/assets/10259801/20064324/94d0e608-a50a-11e6-8058-f8eaa36f3da1.JPG)
... you can test it

**Comment by kpaulaha** [comment]
@SkavenKF Jup, when you are not admin. Its the Digit grouping pattern that messes it up, if you remove that of the user, it works. I have reported that some months ago, thought it was fixed. Now the same:
![currency](https://cloud.githubusercontent.com/assets/10330264/20064723/57d06d82-a514-11e6-858b-de3c1e7e2775.png)

**Comment by SkavenKF** [comment]
@kpaulaha: Hmmm, ok, we have a problem with 3.4.0(21) and no "official" patch (also with a new installation)!

![bug2](https://cloud.githubusercontent.com/assets/10259801/20065024/ee1b5110-a50c-11e6-8a77-fbbee2de2778.JPG)

**Comment by kpaulaha** [comment]
@SkavenKF I have reported the same bug concerning currency calculations in invoices, etc in September, was fixed then. Seems to have the same problem elsewhere. Well, so it is when you don't manage to test all small details, and not dare to have it done by possible customers before you self can rely on it.

**Comment by konadrian** [comment]
In the current version adding works well on user with admin permissions and without them

**Comment by SkavenKF** [comment]
@konadrian: not in master or stable version! Only in the "unstable" developer version 😢
