### ISSUE TITLE
[question] Configuration of VirtualHost <Directory> statement Ubuntu

### ISSUE THREAD

**Issue by ABaumruck** [YetiForceCompany/YetiForceCRM#3744]
Hello!
Could someone please help me to get the correct configuration for my virtual host?

This is what it looks today, but as I coudn't find anything in the official documentation I'm not sure that this is correct.

<VirtualHost *:80>
	ServerAdmin admin@mydomain.com
	DocumentRoot /var/www/html/myCRM
	ServerName my-domain.com
	ServerAlias www.my-domain.com

	<Directory /var/www/html/myCRM/>
	  Options FollowSymLinks
	  AllowOverride All
	  Order allow,deny
	  allow from all
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/my-domain.com-error_log
	# Possible values include: debug, info, notice, warn, error, crit, alert, emerg.
	LogLevel warn

	CustomLog ${APACHE_LOG_DIR}/my-domain.com-access_log common
</VirtualHost>

THX in advance Andreas

**Comment by florek41** [comment]
Here you are: https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by ABaumruck** [comment]
Thank you florek41!
Unfortunately I've been following these instructions very carefully over the last 2 weeks (with lots of searching, trying, failing,...).
And I couldn't find any clear answer throughout the web to my specific question (and nothing from YetiForce itself).

I read that when I want to use "mod_rewrite" within .htaccess the VirtualHost (pointing to your CRM) needs to have "AllowOverride All" set. And this is quite similar to what I read here [http://idroot.net/linux/install-yetiforce-crm-ubuntu-16-04/](url)


But I could figure out a couple of other things related to the instructions you mentioned
And here are the ones I think should be updated/removed/explained in the documentation: 

**Requirements for data base engine [MySQL]**
- ENGINE=InnoDB -> the docu says "should be available and enabled by default (enable --skip-innodb)" and since MySQL 5.5 it is already default. But "enable --skip-innodb" does the total opposite it disables InnoDB -> I found that really confusing

**"my.cnf" (MySQL configuration file)** 
- innodb_lock_wait_timeout = 600 -> you will only find out that you need to alter this parameter after installation of YF in the "logs/server configuration" section 
- max_allowed_packet=10M -> in the docu it is placed in the "php.ini / .htaccess" section which is wrong

**Requirements for php.ini / .htaccess**
(despite the "suhosin" part all other values/flags are clear for me)
- save_mode ->  removed since PHP 5.4.0
- magic_quotes_gpc -> removed since PHP 5.4.0
- magic_quotes_runtime -> deprecated since PHP 5.3.0
- zend.ze1_compatibility_mode -> removed since PHP 5.4.0
- magic_quotes_sybase -> removed since PHP 5.4.0
- mbstring.func_overload -> (enable) they do no provide to what it should be set to. Possible values = 0+1+2+4 -> very likely it should be set to 2 (I found it somewhere in the code but I do not remember where)

**Parameters enabled**
- They all go into php.ini/.htaccess section -> so why put them seperately?

**Third party libraries configuration**
- suhosin -> I would also consider this a 3rd party library and in php.ini/.htaccess suhosin values are required to be set -> but there is no word in the docu if suhosin is mandatory or not -> I assumed it to be optional. If you are running a hosted environment you might check the presence of suhosin at the bottom of the  Zend Engine section from your **<? phpinfo(); ?>**.
- PEAR -> (01.10.1) For me this is a 3rd party library as well, because when I installed Ubuntu on my vServer it was not included. The following packages are shown as PEAR packages, that is why I assumed that PEAR is necessary to install them
- Net_SMTP -> (1.7.2) there are two packages on which Net_SMTP depend -> Net_Socket-1.0.14 and Auth_SASL-1.0.6 (which might be optional).
- Net_IDNA2 -> (0.1.1) is marked as beta
- Mail_Mime -> (1.10.0) there is a Mail_Mime2 as well, but it seems that rouncube has issues
- With PEAR there is one more thing that I like to mention. When I installed Ubuntu 16.04.01 LTS it came with PHP 7.0.8 I couldn't get YetiForce to work properly (to be honest it could also be my fault and not PHP 7). Then I decided to move to PHP5.5/5.6 and first I had PHP7 and PHP5.6 installed in parallel with PHP7 deactivated. But when I installed PEAR it still relied on (the deactivated) PHP7 and to avoid any flaws I finally decided to completely remove PHP7

**Correct path configuration to third party libraries**
- does it mean that the path is added to the "PATH" variable? Sounds obvious, but it is not clearly mentioned  

**Folder Privileges** 
That is how I cofigured it (and I post it, because it was quite a journey to find all the information)
**"chown -R www-data:www-data /var/www/html/your-crm-folder/"**
**"find /var/www/html/your-crm-folder/ -type d -exec chmod 755 {} +"**
**"find /var/www/html/your-crm-folder/ -type f -exec chmod 644 {} +"**
and with **"ls -al /var/www/html/your-crm-folder/"**
folder should look like this **"drwxr-xr-x"** [755]
files should look like this show **"-rw-r--r--"** [644]


A final note.
I'm quite new to Linux and YetiForce and you might find mistakes in my explanations, I am still learning,  so please let me know. 
In terms of YetiForce I've read comments asking to build a strong community. I agree.
On the other hand it is a real journey (as it is for me) to get YetiForce properly installed, and I believe that there are quite some people leaving the project because they are frustrated.


BR Andreas

**Comment by slater101** [comment]
@ABaumruck I agree with your last comment. I feel documentation is very bad and after spending a solid 48 sleepless hours learning how to build my own VPS server just to run yeti force and running into the same issue the system had on a shared host with auto install. I'm pretty darn furious with the documentation.

I honestly just wish I could get it to work. It looks amazing, I'm afraid that if a client liked it, I would have to install it for them again. lol

Heres some questions that might help me,

Did you use both of these for cron
*/5 * * * * sh /var/www/crm/cron/vtigercron.sh
*/5 * * * * >/var/www/crm/cache/logs/cron.log 

or just this one
*/5 * * * * sh /var/www/crm/cron/vtigercron.sh

if both should this one 
*/5 * * * * >/var/www/crm/cache/logs/cron.log 

Just be like this
>/var/www/crm/cache/logs/cron.log 

My cron is running fine, but I feel that this
>/var/www/crm/cache/logs/cron.log  

Is part of my issue , maybe because I have a timing at the beginning of it?

also yetiforce website documentation says to Set a path in the file /var/www/crm/cron/vtigercron.sh to PHP: export USE_PHP=/usr/local/php56/bin/php ,

But one of their team told me to not have that and comment it out.?

So which is it?

Thanks,
Kyle
