### ISSUE TITLE
Deductions by payment method and flat rate taxes and discounts.

### ISSUE THREAD

**Issue by slavamartin** [YetiForceCompany/YetiForceCRM#3745]
Hi There. I'm trying to figure out some abilities of YetiForce and might need someone's help as I couldn't find any detailed documentation about it.

I'm trying to find a way to setup interests on invoices. for example, I create an invoice and as a payment method I choose PayPal, than software must know to deduct 2.9% and $0.3 from the whole invoice. (Would be great having this ability) as well as, is there an option to associate my expenses with a customer invoice ?

Another thing that I couldn't find is create flat rate taxes and discounts.

I would appreciate any help as I'm now looking into different applications and if YetiForce works for me, I'll be promoting it to my customers.

Or perhaps someone can suggest an URL with detailed documentation

Regards

**Comment by slavamartin** [comment]
The idea is awesome, but you guys SUCK with support and there absolutely no documentation on that. No response for 3 days. Software has great potential but lack of support is disgusting. I won't be using it and won't be recommending it to anybody. This software is JUNK without proper documentation. Wasted a week on trying to figure it out, asked one question and no response, great!!!

Thank you so much for wasting my time.

**Comment by waran70** [comment]
Don't cry kid. Pay for support if you are weak in programming.

**Comment by slavamartin** [comment]
I will definitely NOT pay for support "GRANPA" if I don't even get an answer here. If I would of gotten an answer here, I would consider paying for support for future customization.

Having an open source project is about helping people use it, NOT to show off about how great are you and other suck because they don't know how to use a software that is meant to be "FREE" but has zero documentation, because they want people to pay for support. F*CK, why am I even replying to you? You are one of those sick GEEKS with a "GOD" syndrome. You have to go see a psychologist.

**Comment by waran70** [comment]
@all - 馬鹿
@馬鹿 - We all hope you will reply again ....  quite funny...

**Comment by ronald1090** [comment]
The whole world was waiting for your answer and nobody gave you a 
solution.....

I think that the Support your is absolutely great. Thank you.



Am 10.11.2016 um 10:03 schrieb waran70:
> @all - 馬鹿
> @馬鹿 - We all hope you will reply again .... quite funny...
>
>
>

**Comment by bpabiszczak** [comment]
@Slavamartin
Thank you for the enormous support you provided for the YetiForce community, as far as programming and substantial aspects are concerned. We appreciate that before you give something, you first have demands.
Unfortunately the YetiForce team won’t help you, because we love sincere people, and we ignore the rude ones.

**Comment by PercyP** [comment]
Just stumbled across this post. How rude @slavamartin is. To go in to such a rage after waiting just a couple of days! Anyway, the rest of us appreciate what Yetiforce are doing, and we know it takes time to produce documentation etc. etc. etc. 

It makes me mad when I see things like this as people just want everything for free and not prepared to give back in any way - just let others do all the hard work and continuously take take take. Well good riddance to him, we can do without leeches like that dragging down our community! I wonder if he enjoys working for free to benefit others? I can guarantee not.  Sorry, this sort of thing just pisses me off!!!
