### ISSUE TITLE
[bug minor] Language variable

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3746]
#### Issue
Both buttons have same language variable: LBL_SEND_NOTIFICATION
![program manager](https://cloud.githubusercontent.com/assets/10330264/20092495/2c37ac66-a5a1-11e6-90eb-5c97ee87f35d.png)

**Comment by kabelo38** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=4&fieldid=53

**Comment by kpaulaha** [comment]
@kabelo38 I know that, but it don't much help when there is only one variable and both uses it.
