### ISSUE TITLE
Issues with Document Flow

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#3747]
#### Issue

Sql Error

#### Actual Behavior

  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'doc_folder' cannot be null The SQL being executed was: INSERT INTO `vtiger_ossdocumentcontrol` (`module_name`, `summary`, `doc_folder`, `doc_name`, `doc_request`, `doc_order`) VALUES ('HelpDesk', 'ttte', NULL, 'dfgdfgd', 0, 1)

#### Expected Behavior

Save Document flow record

#### How to trigger the error

1. Click settings
2. Automation
3. Document Flow
4. Fill related info

#### Your Environment

* YetiForce Version used: 3.4.237
* Browser name and version: chrome Version 54.0.2840.90 (64-bit)
* Environment name and version:
* Operating System and version: Ubuntu 16

**Comment by TomaszQr** [comment]
Error doesn't exist in current version
