### ISSUE TITLE
file from CRM

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#3750]
#### Issue

Not add file rom CRM with mail
![gif](https://cloud.githubusercontent.com/assets/15871611/20130257/a51f3e3a-a666-11e6-9ee1-356b69e9994b.gif)

#### How to trigger the error

1. go to "OSSmail" module
2. Click "Compose"
3. Click "File from CRM"

#### Your Environment

* YetiForce Version used: ver. 3.4.478
* Browser name and version: Crome
* Environment name and version:  
* Operating System and version: W7

**Comment by mariuszkrzaczkowski** [comment]
Check the logs in the browser,
F12 in chrome

**Comment by kjradv** [comment]
when choosing a console file remains the same
![console](https://cloud.githubusercontent.com/assets/15871611/20557621/3f66b290-b17d-11e6-8680-4c3173cde911.PNG)
