### ISSUE TITLE
improved file attachment to CRM

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#3751]
#### Actual Behavior

File is attached, but most e-mail services are limited 15 MB file

#### Expected Behavior

If the file is larger than 15 MB to send a link to it in CRM

#### Your Environment

* YetiForce Version used: lasted
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version: W7

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/206-system-development-ideas.html
