### ISSUE TITLE
[Question] How to create association between an account and a product or service using API

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#3752]
I tried the following query but does not work to my expectation

I thought by updating the products field on Accounts would link the two.

$fields = array('accountname' => 'Test',  'id' => '11x117', 'email1' => 'something@example.co.za', 'products' => '|#|Standard Web hosting|#|');
$data = array('operation' => 'update', 'sessionName' => $this->sessionName, 'element' => json_encode($fields), 'elementType' => 'Accounts');

$data = http_build_query($data);
$service_url = $this->crm_base_url."/webservice.php";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $service_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );
$data2 = json_decode(curl_exec($ch));
$data2 = json_decode(json_encode($data2), TRUE);

**Comment by kabelo38** [comment]
hi @paula-w  any workaround this question ?

**Comment by kabelo38** [comment]
@s

**Comment by KatarzynaUlichnowska** [comment]
Hello,
your API version is outdated. In the latest API version, this function needs to be added - if you know how, you can do it on your own, if you don't know, you need to hire someone to do it for you.
