### ISSUE TITLE
Email scanner can't setup folders

### ISSUE THREAD

**Issue by Pietrox** [YetiForceCompany/YetiForceCRM#3753]
#### Issue
Error while trying to setup email scanner folders.

#### Actual Behavior
![screenshot491](https://cloud.githubusercontent.com/assets/22810723/20136644/3a1455d4-a676-11e6-8787-47b8f17c3438.jpg)

#### Expected Behavior
Ability to setup the the scanner folders

#### How to trigger the error
1. By clicking edit folders

#### Your Environment
* YetiForce Version used: 3.4 + Hotfix
* Browser name and version: Chrome 54.0.2840.71
* Environment name and version: PHP 5.6 - CloudLinux 
* Operating System and version: Win10  64bit

**Comment by mariuszkrzaczkowski** [comment]
Check what your logs say

**Comment by Pietrox** [comment]
After long time with zero logs info we fixed it - practically after we gave up.
The reason for this was new email server where we stopped using no auth by ip so "%p" and "%u" was back again in the settings.
So in this case authentication has to be set to on or it will not detect/login to account to list folders.
