### ISSUE TITLE
[ENHANCEMENT] Current and Dev - Time Format

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3754]
#### Issue

Time Format in Project, Project task, Service Contract, Time Control, **REPORTS** Etc has bad type, only seen in decimal hours.

I propose function like this. To change Ej. 17.5 to the real -> 17:30

```

function Decimal_To_Hs($in){
    $h = intval($in);
    $m = round((((($in - $h) / 100.0) * 60.0) * 100), 0);
    if ($m == 60)
    {
        $h++;
        $m = 0;
    }
    $retval = sprintf("%02d:%02d", $h, $m);
    return $retval;
}


Decimal_To_Hs("17.5"); // **17:30**
```

#### Actual Behavior

Ej. Project or Reports.

Total Time [h] = 17.5

#### Expected Behavior

Total Time [h] = 15:30 Hs

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4 Stable
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by skramanzia** [comment]
Its posible use the fuction "decimalTimeFormat" in the fields Total Time [h]  and in reports?

**Comment by skramanzia** [comment]
I dont know who applied fuction to Field.

**Comment by skramanzia** [comment]
Hi Team, I am consider this "Enhancement" is critical for Reports. If manager or Boss require a report of how many hours are consumed for support or whatever module,  the information is not real or legible for users.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/a5e47cb0a2ba82224b8f0de14ecb0c3b6470e72b
