### ISSUE TITLE
Portal not showing any details

### ISSUE THREAD

**Issue by stoke3380** [YetiForceCompany/YetiForceCRM#3757]
I followed all the instructions to install Yeti and the customer portal. I created a contact. I received the username and password for this user to access the portal. I have managed to login in the customer portal. Nothing shows in the portal. The accounts page is blank. None of the dashboard in the customer portal show any information from yeti.I have attached some images.

![screenshot_61](https://cloud.githubusercontent.com/assets/23377745/20173421/277cd4da-a731-11e6-9f27-b52cb761d43c.png)
![screenshot_62](https://cloud.githubusercontent.com/assets/23377745/20173428/2d9992f4-a731-11e6-81de-2b1dc4b2c1a4.png)
![screenshot_63](https://cloud.githubusercontent.com/assets/23377745/20173433/3427c19a-a731-11e6-9e1d-5028323f1d28.png)

**Comment by krobin8** [comment]
I have the same result. I have information on the dashboard page (see tickets dashboard), but no records are found under each module. 

![image](https://cloud.githubusercontent.com/assets/12663988/20188405/26f794fc-a73e-11e6-88a4-7e2a562e6d24.png)

![image](https://cloud.githubusercontent.com/assets/12663988/20188416/335ab418-a73e-11e6-92d2-d5f098cc8503.png)

**Comment by pmontanez** [comment]
Please use the search function before posting a new threat - This portal issue has been reported several times -

**Comment by mariuszkrzaczkowski** [comment]
Tests portal and everything works, check logs
https://gitdeveloper.yetiforce.com/portal/

**Comment by pmontanez** [comment]
Mariusz, The service and  products module are not bound to  the portal.

**Comment by krobin8** [comment]
@mariuszkrzaczkowski , The link you have is v3.2.2; I have installed 3.2.0 which may be my issue. Where is the latest?

![image](https://cloud.githubusercontent.com/assets/12663988/20217635/5af3db0a-a7e6-11e6-82e5-6d6e54408d8a.png)

**Comment by speakerua1** [comment]
In the helpdesk module, missed file create.php.
Path to file: modules/Module/create.php

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForcePortal/tree/developer

**Comment by kabelo38** [comment]
getting a blank password 

Dear Kabelo Matsoso,

Below are the details you will need to gain access to our customer portal.
Link : https://portal.something.co.za/
Login: email@gmail.com
Password: 
 
I use Portal2 and YT4.0
