### ISSUE TITLE
Detailed Documentation availability?

### ISSUE THREAD

**Issue by capriole** [YetiForceCompany/YetiForceCRM#3759]
Hello

I am trying to find a more detailed user guide for YetiForceCRM than the documentation provided at YetiForce https://yetiforce.com/en/documentation.html. I am looking something similar to the guide provided for vtiger (https://wiki.vtiger.com/vtiger6/index.php/Main_Page) which will allow me to understand the relationship between modules, etc and how I could setup views/fields in order to customise the product for the needs of my company. 

Thanks in advance

**Comment by vovpff** [comment]
@capriole for this time there is no domentation. You can try to understand system mechanisms by yourself at local stable system.

**Comment by kabelo38** [comment]
@capriole look at vtiger's documentation YetiForce is a fork of vtiger
