### ISSUE TITLE
Portal development

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#3760]
Have been discussed but maybe we can refresh it... Portal is still quite poor in interactions. One of the basic function is to allow Account holder, to change company/contact details. 
Another files upload... 
This is what I think should be included. Any other ideas?

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/github/issues/203-pomys%C5%82y-zwi%C4%85zane-z-rozwojem-systemu.html
