### ISSUE TITLE
how to display project tasks in calendar

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#3761]
#### Actual Behavior
Can only display event\to do\ in calendar.

#### Expected Behavior
display project tasks in calendar too

#### How to trigger the error

1. in calendar setting page, active the project task display in calendar.
2. click visual desk->calendar
3. no project task displayed

#### Your Environment

* YetiForce Version used: 3.40
* Browser name and version: chrome
* Environment name and version: nginx+mysql on ubuntu with php 5.6
* Operating System and version: ubuntu 14.10

**Comment by paula-w** [comment]
Project tasks are shown in the Gantt charts, we're not planning to display them in the calendar.
