### ISSUE TITLE
Question - Updates/HotFIXs

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3763]
Do you think it is possible to have a Hotfix with recent modifications?

 According to the Tickets were modified several queries of database, this solved critical problems of reports, in the stable version it is not possible to perform metrics.

 I know that they are working hard for improvements and new version, but would be very useful since they were reported and solved a lot of Bugs.

Thanks for all the work!

**Comment by ezbank** [comment]
yeah

**Comment by paula-w** [comment]
An update package will be published in 2~3 weeks.
Right now we’re working on system stabilization after introducing some significant changes in the database engine. Many elements of the system aren’t working properly due to these changes. 
Please bear with us.

**Comment by SkavenKF** [comment]
Update to 3.5 or Hotfix for 3.4 ?

**Comment by paula-w** [comment]
At first we will release 3~4 packages between 3.4 and 3.5.
The 3.5 package will be released at the end of the year.

**Comment by SkavenKF** [comment]
Great 😄 
Are these provided in gitmaster before they released in gitstable? So the community can also test the package/hotfix.

**Comment by paula-w** [comment]
We use gitmaster in order to move the code from gitdeveloper to gitstable, and verify each line. 
The packages will be available here: https://github.com/YetiForceCompany/UpdatePackages  and they will work for the latest stable version, namely 3.4 [right now]

**Comment by SkavenKF** [comment]
My question is, where can the community test the package/hotfix **before** it become stable? Look at the following picture. 
In my opinion, currently the arrows only go from gitdeveloper to gitstable to gitmaster but not back. 

![gitflow-orig-diagram](https://cloud.githubusercontent.com/assets/10259801/20387798/2a39a892-acc2-11e6-91b6-f13787c4e20b.png)
