### ISSUE TITLE
Connect offer and invoice items

### ISSUE THREAD

**Issue by dataviper** [YetiForceCompany/YetiForceCRM#3764]
#### Issue
It would be preferable to create an invoice from an offer with the exact same items as offered.

In our company we adjust pricing for all customers, so a price like "100" for this and "200" for that won't apply. To keep our billing in line we would need to create an invoice from the offer so we won't have to look up prices each time.

#### Actual Behavior
Products and/or services have to be applied new at each sales step. 

#### Expected Behavior
Based on a previous record (calculation, chance, offer, etc...) should be items with price, quantity, etc... filled in.

#### Your Environment
* YetiForce Version used: 3.x
* Browser name and version: Doesn't matter
* Environment name and version: Doesn't matter
* Operating System and version: Doesn't matter

**Comment by vovpff** [comment]
@dataviper let's check mapping at dev version at admin menu. You can made automatic data moving from offer to invoice by mouse 2 clicks.
