### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ancestorexperts** [YetiForceCompany/YetiForceCRM#3766]
I use Godaddy.com as my hosting provider.  
I have Mysql 5.5 
I am trying to install the Yetiforce software.

I get the following message, after I initiate the  install process:

**Fatal** error: Can't use method return value in write context in /home/content/43/11577243/html/ERPProjects/modules/Users/models/Record.php on line **328**

What Do I have to do, to resolve this problem?

Are there any read/write/execute permissions I need to change before I install the software?
If so, what files and directories and what permissions have to be set?  

Thank you for your time.

**Comment by bpabiszczak** [comment]
PHP?

**Comment by ancestorexperts** [comment]
Yes, I have PHP 5.4

**Comment by bpabiszczak** [comment]
You need PHP 5.6

**Comment by ancestorexperts** [comment]
Thanks for letting me know.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
