### ISSUE TITLE
Unable to install - yetiforce 

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3767]
#### Issue

I'm unable to install - 

i have also paid (25 euro) for Service - Installation Lite version, not getting any response from them. 

Please help --- it is very urgent. 

#### Actual Behavior

Installation is starting - after 50 seconds, it is stopped in middle. 
All said config setting are setting as per requirement. 

## # **Apache Error Log** 

[Tue Nov 15 19:42:38.019717 2016] [ssl:warn] [pid 2816:tid 228] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 15 19:42:38.078720 2016] [core:warn] [pid 2816:tid 228] AH00098: pid file D:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Nov 15 19:42:38.248730 2016] [ssl:warn] [pid 2816:tid 228] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 15 19:42:38.295733 2016] [mpm_winnt:notice] [pid 2816:tid 228] AH00455: Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.24 configured -- resuming normal operations
[Tue Nov 15 19:42:38.295733 2016] [mpm_winnt:notice] [pid 2816:tid 228] AH00456: Apache Lounge VC11 Server built: Jul  7 2016 11:13:22
[Tue Nov 15 19:42:38.295733 2016] [core:notice] [pid 2816:tid 228] AH00094: Command line: 'd:\\xampp\\apache\\bin\\httpd.exe -d D:/xampp/apache'
[Tue Nov 15 19:42:38.296733 2016] [mpm_winnt:notice] [pid 2816:tid 228] AH00418: Parent: Created child process 3876
[Tue Nov 15 19:42:38.874766 2016] [ssl:warn] [pid 3876:tid 240] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 15 19:42:39.072777 2016] [ssl:warn] [pid 3876:tid 240] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 15 19:42:39.120780 2016] [mpm_winnt:notice] [pid 3876:tid 240] AH00354: Child: Starting 150 worker threads.

**# And SQL Error log** 

2016-11-15 19:42:39 948 [Note] d:\xampp\mysql\bin\mysqld.exe: Normal shutdown

2016-11-15 19:42:39 948 [Note] Event Scheduler: Purging the queue. 0 events
2016-11-15 19:42:39 2136 [Note] InnoDB: FTS optimize thread exiting.
2016-11-15 19:42:39 948 [Note] InnoDB: Starting shutdown...
2016-11-15 19:42:40 948 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
2016-11-15 19:42:41 948 [Note] InnoDB: Shutdown completed; log sequence number 93420613
2016-11-15 19:42:41 948 [Note] d:\xampp\mysql\bin\mysqld.exe: Shutdown complete

2016-11-15 19:42:43 db8 InnoDB: Warning: Using innodb_additional_mem_pool_size is DEPRECATED. This option may be removed in future releases, together with the option innodb_use_sys_malloc and with the InnoDB's internal memory allocator.
2016-11-15 19:42:43 3512 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

2016-11-15 19:42:43 3512 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2016-11-15 19:42:43 3512 [Note] InnoDB: The InnoDB memory heap is disabled
2016-11-15 19:42:43 3512 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
2016-11-15 19:42:43 3512 [Note] InnoDB: _mm_lfence() and _mm_sfence() are used for memory barrier
2016-11-15 19:42:43 3512 [Note] InnoDB: Compressed tables use zlib 1.2.3
2016-11-15 19:42:43 3512 [Note] InnoDB: Using generic crc32 instructions
2016-11-15 19:42:43 3512 [Note] InnoDB: Initializing buffer pool, size = 16.0M
2016-11-15 19:42:43 3512 [Note] InnoDB: Completed initialization of buffer pool
2016-11-15 19:42:43 3512 [Note] InnoDB: Highest supported file format is Barracuda.
2016-11-15 19:42:44 3512 [Note] InnoDB: 128 rollback segment(s) are active.
2016-11-15 19:42:44 3512 [Note] InnoDB: Waiting for purge to start
2016-11-15 19:42:44 3512 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.32-79.0 started; log sequence number 93420613
2016-11-15 19:42:44 3744 [Note] InnoDB: Dumping buffer pool(s) not yet started
2016-11-15 19:42:44 3512 [Note] Plugin 'FEEDBACK' is disabled.
2016-11-15 19:42:44 3512 [Note] Server socket created on IP: '::'.
2016-11-15 19:42:44 3512 [Note] d:\xampp\mysql\bin\mysqld.exe: ready for connections.
Version: '10.1.19-MariaDB'  socket: ''  port: 3306  mariadb.org binary distribution

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by skramanzia** [comment]
@basanthagarwal Please decribe your environment and check this link to deploy the correct environment.

https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by basanthagarwal** [comment]
Though, installation is completed successfully, First time login is going fine, 


However, after logging out -  and  on re-login - it is showing same login page - ; in case i'm typing invalid userid - password - it is displaying login error ; 
But in case of Valid login details - it is not able to login at all 

Please try this link with 
Link:       http://c.basanonline.com/basancrm 
User ID:  basanth
Password: Basan123


I'm struggling with this problem since 10 days ... please help me resolve.. 




and access.log error is as follows .. 




183.82.105.124 - - [16/Nov/2016:00:50:09 +0530] "GET /yeti/storage/Logo/logo.png HTTP/1.1" 404 1228 "http://c.basanonline.com/yeti/index.php" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
183.82.105.124 - - [16/Nov/2016:00:50:12 +0530] "GET /yeti/index.php HTTP/1.1" 200 22934 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
183.82.105.124 - - [16/Nov/2016:00:50:12 +0530] "GET /yeti/storage/Logo/logo.png HTTP/1.1" 404 1228 "http://c.basanonline.com/yeti/index.php" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
183.82.105.124 - - [16/Nov/2016:00:50:22 +0530] "POST /yeti/index.php?module=Users&action=Login HTTP/1.1" 302 - "http://c.basanonline.com/yeti/index.php" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
183.82.105.124 - - [16/Nov/2016:00:50:22 +0530] "GET /yeti/index.php HTTP/1.1" 200 22934 "http://c.basanonline.com/yeti/index.php" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
183.82.105.124 - - [16/Nov/2016:00:50:22 +0530] "GET /yeti/storage/Logo/logo.png HTTP/1.1" 404 1228 "http://c.basanonline.com/yeti/index.php" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"

**Comment by bpabiszczak** [comment]
Please send me access [ftp address, port, login, pass] [email: SLA@yetiforce.com]

**Comment by skramanzia** [comment]
Check this link to upload logs.

https://yetiforce.com/en/github/issues/126-issues.html

**Comment by SkavenKF** [comment]
I see you run Windows Server 2008 R2 and a XAMPP Installation. I have a similar problem on one server with this constallation, and after i chance to a WAMP Installation i haven't no problem with the user login ...

**Comment by paula-w** [comment]
Windows requires additional libraries (it will tell you what libraries you need when you download WAMP) and only then should you install WAMP, and then YetiForce on it. 
We don’t recommend installing the system on Windows, because right now we’re not testing whether or not all functions in the system work properly.

**Comment by vovpff** [comment]
@paula-w before WAMP installation I insatller all needed libraries but every installation of dev version fineshed with frosen Installation page. After refresh (F5) there are appear login page but every time password incorrect. With stable 3.4 sersion all ok!

**Comment by SkavenKF** [comment]
@basanthagarwal: which yetiforce version do you use?

**Comment by basanthagarwal** [comment]
i have tried with both version == 3.2 & 3.4 .. receiving same error ..

**Comment by basanthagarwal** [comment]
right now ... i'm updating windows 7 -> then installing wamp ..

**Comment by SkavenKF** [comment]
I have used ms server 2003 and windows  7, 8, 8.1 and 10 with xampp 5.6.xx since vtiger 5.3 without problems with the operation system windows. 
Only with server 2008 r2 i have a problem with xampp 5.6.xx. now i changed to wamp 5.6.xx. (actual 5.6.26)

For the installation ...
* You must check the [webserver requirements](https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html)
* Change the parameters that checked at the installation

And for a better performance on a windows machine, change your "hosts" file in C:\Windows\System32\drivers\etc and delete the # in the line "# 127.0.0.1      localhost" to "127.0.0.1       localhost" :astonished:

**Comment by basanthagarwal** [comment]
Now, ... after WAMP & Yetiforce installation .., login in issue is resolved ... but problem prevails. .. 

I'm unable to add or edit any records..

**Comment by vovpff** [comment]
@basanthagarwal start your cron tasks!

**Comment by bpabiszczak** [comment]
one problem = one issue
