### ISSUE TITLE
[Bug] Workflow - Update Related Record

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3768]
Version: stable 3.4

workflow not update related record
e.g. from account update contact firstname

![gifrecord_2016-11-16_143958](https://cloud.githubusercontent.com/assets/18703633/20349500/07356474-ac0b-11e6-99a4-eee49317839a.gif)

**Comment by waran70** [comment]
Not working in developer too

**Comment by paula-w** [comment]
We just checked it on the current version and it’s working properly. CRON updates fields in a related module. By default the CRON action is launched every 15 minutes.

**Comment by waran70** [comment]
Manual triggering should not be tied to cron but should take effect
immediately.

**Comment by nic86** [comment]
@paula-w Thanks for the explanation, but I agree with @waran70 regarding the manual trigger.
