### ISSUE TITLE
How to use Time Control

### ISSUE THREAD

**Issue by mcules** [YetiForceCompany/YetiForceCRM#3770]
Not really an issue, but help needed ;)
Im using the Time Control for documentation and invoice.
How can a get the recordings into the invoice? Is there a function which i can use or do i have to wrote it manual in the invoice?
I didn't found anything about it.

Thanks in advance.

**Comment by vsappel** [comment]
SaSame here, i started adding a contract on an account.
Contract based in Hours.
After that, i've created a ticket but the field "work time" still disabled. How i can discount time worked from a account contract?

**Comment by skramanzia** [comment]
@vsappel The field "Total Time" always is disabled, you can set the worked time in "Time Control" in created Ticket.

**Comment by mcules** [comment]
Do you know how I can bill the hours too?

**Comment by mcules** [comment]
No Information if it is possible to invoice the Time Control Items?

**Comment by KatarzynaUlichnowska** [comment]
In order to sum all records from Time Control, it is required to set a proper status on every record and enable cron.
In regards to Time Control on Invoices, there might be a special function created in the PDF module, which sums it all up.

**Comment by mcules** [comment]
Thank you for your Answer Katarzyna,

which Cron should be enabled? Checked the Cron Module und see that all are enabled.
How is the name of the Special function in the PDF Module?

**Comment by rskrzypczak** [comment]
You have to enable the following options:
![image](https://cloud.githubusercontent.com/assets/10221999/21538807/0d2b9b5c-cda1-11e6-897a-b1ca71e15758.png)

**Comment by mcules** [comment]
Those settings are allready activated.
But what is the special function and how can i get it for invoice?
Is it just showing the Times as Text or should it invoiced as items?
