### ISSUE TITLE
[Bug] Workflows - Update fields

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3771]
Version: stable 3.4

the "shared with users" field is not set through the update fields task by workflow.

![gifrecord_2016-11-17_152623](https://cloud.githubusercontent.com/assets/18703633/20393134/039e0444-acdb-11e6-8469-74d3318c27d4.gif)

**Comment by konadrian** [comment]
The error doesn't occur in the latest version
