### ISSUE TITLE
[PL]Pole procentowe

### ISSUE THREAD

**Issue by yetitest** [YetiForceCompany/YetiForceCRM#3773]
#### Issue
Czy pole procentowe może być wyświetlane razem ze znekiem "%" tj. po wpisaniu wartości 10 aby pole w podsumowaniu wyświetlało "10%" a nie 10.00

![aa1](https://cloud.githubusercontent.com/assets/22539294/20422878/54d7cce0-ad6d-11e6-97c1-da0fe1d1c764.JPG)

![aa2](https://cloud.githubusercontent.com/assets/22539294/20422880/575a8c82-ad6d-11e6-8f60-42f04aee93f4.JPG)

#### Your Environment

* YetiForce Version used: 3.4.0

**Comment by bpabiszczak** [comment]
Wystarczy dodać od strony kodu nowego uitype.
