### ISSUE TITLE
how to add linking modules?

### ISSUE THREAD

**Issue by slawekkow** [YetiForceCompany/YetiForceCRM#3774]
Hi
I created a new module and do not quite know how to link it with other modules.
I will be grateful for your help

YetiForce: v3.4.0 HOTfix3.4

**Comment by bpabiszczak** [comment]
try add new "related field 1:M"

**Comment by slawekkow** [comment]
I mean the values associated with the module
like the screenshot
![modul](https://cloud.githubusercontent.com/assets/22636658/20428081/8b87610a-ad87-11e6-902e-f102a0d8c49d.gif)

**Comment by slawekkow** [comment]
please again
