### ISSUE TITLE
How to add new font into PDF template Editor

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#3775]
i checked mPDF document, and add a new font.
but i dont know how to add the font into PDF template editor.
![image](https://cloud.githubusercontent.com/assets/15126825/20457329/d4011f74-aec3-11e6-9a5c-8a4520ccfa96.png)
and right now the generated PDF can not display the asia character correctly. display asia characters as a box
![image](https://cloud.githubusercontent.com/assets/15126825/20457343/4ed0af94-aec4-11e6-8d86-72345d237864.png)

#### Your Environment

* YetiForce Version used:3.4
* Browser name and version:Chrome
* Environment name and version:PHP5.6+MYSQL5.6+nginx
* Operating System and version:Ubuntu 10.14

**Comment by kjradv** [comment]
Hello, @zelphar .
**Add new font into CKeditor**

> /libraries/jquery/ckeditor/config.js ##Config 
> http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-font_names ##how to add custom font

**And add custom font in mPDF**

> /libraries/mPDF/config_fonts.php ##Config
> https://mpdf.github.io/fonts-languages/fonts-in-mpdf-6-x.html ##how to add custom font

After these actions all works fine
