### ISSUE TITLE
Can`t login on roundcube mail

### ISSUE THREAD

**Issue by olasovidiu** [YetiForceCompany/YetiForceCRM#3776]
#### Issue

Hello, i`m a new user to YetiForce and its awesome!. but somehow i cannot login on e-mail via roundcube. 

 Note: All modules are working corectly and no system errors.
 I also edited OSSMail.php with the correct login credentials

#### Actual Behavior

On the login window after credentials are inserted its just "loading" and after 20 seconds nothing happens, no error, doesnt login.

1. 
![yeti force mail](https://cloud.githubusercontent.com/assets/23511545/20467088/2808dc64-af88-11e6-92d6-0c53be0744cc.png)

2.
![yeti force mail 2](https://cloud.githubusercontent.com/assets/23511545/20467089/2e9bd626-af88-11e6-95e4-59f2dec11e33.png)

3.
![yeti force mail 3](https://cloud.githubusercontent.com/assets/23511545/20467091/34089982-af88-11e6-9b16-05cad8546221.png)

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Chrome latest
* Environment name and version: 
* Operating System and version: Win 7

**Comment by efernau** [comment]
Have you you installed this HOTfix3.4 from:
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/developer-documentation/engine/115-debugging.html

**Comment by olasovidiu** [comment]
Thanks efernau for your answer after i updated the fix now its working.
Thank you
