### ISSUE TITLE
[PL]Waluty - kolejne problemy

### ISSUE THREAD

**Issue by yetitest** [YetiForceCompany/YetiForceCRM#3777]
#### Issue

Kolejne problemy z kwotami. Z modułu szansy został wykonany  Akcje - > Eksport do Excel
Poniżej zrzut jak prezentują się tam pola kwotowe.

![aaa](https://cloud.githubusercontent.com/assets/22539294/20480601/88183cac-afe3-11e6-9167-edf8bf486c95.png)

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version: Chrome

**Comment by rskrzypczak** [comment]
Prawie wszystkie problemy z walutami zostały rozwiązane [tutaj ](https://github.com/YetiForceCompany/YetiForceCRM/commit/2fb711b6bebb6b532ce71f670b8c97758ff3b64e).
Błąd, który zgłaszasz nie występuje na obecnej wersji developerskiej ([link](https://gitdeveloper.yetiforce.com)). Oznacza to tyle, że błąd prawdopodobnie został poprawiony i nie będzie występował w następnej wersji CRM YetiForce.
