### ISSUE TITLE
Unable to add new records: "Error: There is no active transaction."

### ISSUE THREAD

**Issue by masterGH** [YetiForceCompany/YetiForceCRM#3779]
When attempting to add new records of any kind, accounts, employees, etc, it fails with message: "Error: There is no active transaction."  This is a brand new installation on a CentOS server with everything but LDAP in passing proper configuration checks.

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Chrome 54.0.2840.99 m (64-bit)
* Environment name and version: Application hosted on CentOS Linux webserver with Apache, PHP5.6, MySQL
* Operating System and version: Accessed from my desktop (Windows 10 64-bit Pro), Application hosted on Linux web server (configuration above.)

**Comment by SkavenKF** [comment]
CRON Jobs active?

**Comment by masterGH** [comment]
All defaults say 'Active' inside Yeti except Backup.

**Comment by SkavenKF** [comment]
look like this (last scan started/ended recently or at installation time?) 
![cron](https://cloud.githubusercontent.com/assets/10259801/20569702/4d26138e-b1a1-11e6-8549-ef3483fcf155.JPG)

https://yetiforce.com/en/administrator-documentation/panel/cron/150-enable-cron.html

**Comment by masterGH** [comment]
Thank you.  I have not added a CRON file (per the article).  I'm confused as the to the first instruction:
"Add a file to the crontab, e.g. in such format: */5 * * * * sh /var/www/crm/cron/vtigercron.sh &>/var/www/crm/cache/logs/cron.log [pay attention to a correct path to the YetiForce system]. "

What is the */5**** ?  Is that part of the path?  Is the '&>' also part of the path?  Could you give me examples of the actual path to use?  I know I will have to change them to my actual path.
Also, in the file: vtigercron.sh do I just simply put 'PHP: export USE_PHP=/usr/local/php56/bin/php' in the file and that's all?  I know I have to correct the path to my PHP installation.

Thanks for your help.

**Comment by paula-w** [comment]
CRON has nothing to do with adding records. If you are not able to add records then you have to check the logs to see what’s wrong.

**Comment by skramanzia** [comment]
@masterGH If your Question is for Schedule task in Crontab, you only need to add this line.

*/5 * * * * sh /var/www/crm/cron/vtigercron.sh 

This path /var/www/crm/cache/logs/cron.log is That's where it's stored logs.

If you whant know how to use Crontab see this information

*     *     *   *    *        command to be executed
-     -     -   -    -
|     |     |   |    |
|     |     |   |    +----- day of week (0 - 6) (Sunday=0)
|     |     |   +------- month (1 - 12)
|     |     +--------- day of        month (1 - 31)
|     +----------- hour (0 - 23)
+------------- min (0 - 59)

Example 
min	hour	day/month	month	day/week	Execution time
30	0	1	1,6,12	*	                      — 00:30 Hrs  on 1st of Jan, June & Dec.
0	20	*	10	1-5	                              –8.00 PM every weekday (Mon-Fri) only in Oct.
0	0	1,10,15	*	*	                       — midnight on 1st ,10th & 15th of month
5,10	0	10	*	1	                               — At 12.05,12.10 every Monday & on 10th of every month

**Comment by ahmido** [comment]
Go to Database and use this query


 SET GLOBAL sql_mode='';

**Comment by masterGH** [comment]
@ahmido That works!  Thank you sir.  However, just fyi, you will lose the global change when you restart the MySQL server, so you should add: `sql_mode=""` to your my.cnf file under [mysqld] for permanent changes.

@skramanzia Thanks for the explanation on CRON jobs.  I had done some research right before you posted that and saw the same diagram.  I do understand more about them now.  Thank you.  In terms of the log file, that log file doesn't exist in that directory currently on my system.  Is it created when I first run the CRON?  Thanks again.

@paula-w Which logs should I have checked?  Thanks for your help.  Checking the log interface inside Yeti showed nothing.  The solution was @ahmido 's above with a slight modification noted in this post (see first section of this post.)
