### ISSUE TITLE
Profile, role of the user

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#378]
Hi, 
Fresh installation of yetiforce 1.3 RC. 
There is issue of defining profile and role for user. Shortly I wanted to switch off some module and filed for one user. So I created:
1. new groupe and add user to new groupe 
2. new profile where specified modules which shouled be off for my user  
3. new role under CEO and assigned it to  new profile 
4. In user properties I assined correct role - point 1.
Shortly it doesn't work.... User has only access to ideas module. Rest is not accesiable. 
I have installed fresh vtiger 6.2 and perform the same action like with yeti and this works so there is a bug in yetiforce... 
Can you advice where should we look for solution...

**Comment by witer30** [comment]
check this on test.yetiforce.com - user: test, password: Test@1904 and you will see that roles and profiles doesn't work properly

**Comment by bpabiszczak** [comment]
Permissions for profiles and for the menus are independent. I do not understand your problem. Check on the screenshot, what you should not see.

**Comment by witer30** [comment]
Well, so how can I,for example, switch off sales opportunities for one user when rest have access to it...? 
I followed the same way in vtiger and it works... Everything what was switch off didn't appeared after log in.

**Comment by waw555** [comment]
Add role in menu
![menu](https://cloud.githubusercontent.com/assets/1402355/6799858/206e79fe-d23b-11e4-9d84-429cf72b9365.JPG)
