### ISSUE TITLE
PDF configuration

### ISSUE THREAD

**Issue by Luxx99** [YetiForceCompany/YetiForceCRM#3781]
#### Issue
I'm setting up a new template for Quotes and I'm using the special functions ProductsTable and ProductsTableNew.

#### Actual Behavior

These functions return a table where there are also the columns Purchase, Margin (%) and Margin.

#### Expected Behavior

Of course these fields must not be displayed to customers.

#### How to trigger the error

1.
2.
3.

#### Your Environment

YetiForce Version used: 3.4.0
Browser name and version: Chrome 54.0.2840.99 m (64-bit)
Environment name and version: Application hosted on SiteGround Linux webserver with Apache, PHP5.6, MySQL
Operating System and version: Accessed from my desktop (Windows 10 64-bit Pro)

**Comment by skramanzia** [comment]
@Luxx99 Try remove "Basic Line" in "Managing and advanced block" of "Edit Field" in Quote Module

![image](https://cloud.githubusercontent.com/assets/3030997/20576731/e48b1426-b19d-11e6-9153-c08b77fb110a.png)

**Comment by Luxx99** [comment]
Hi skramanzia,
I followed your hint, setting the fields unwanted as "hidden" in the basic line and it works perfectly.
Thank you a lot for your support

**Comment by Luxx99** [comment]
Hi bpabiszczak
I was double thinking on what you wrote me, but I have an additional question: I understand how to hide the unwanted fields, but if I want to include other fields, like the discount amount in the table, how can do it? Note that in the advanced block/basic line the field is already set to "always visible" ...

**Comment by paula-w** [comment]
You can configure PDF in the following places:
1. at the panel level – in field management you can define the available fields that will be visible in the template
2. at the PDF panel level – create PDF templates
3. at the database level
4. at the special functions level – here you can change whatever you want

If something is missing in the panel (2nd point) then you need a developer who will adjust the template to your needs; it's easy but you have to know how to do that. 
You can order it from us, then we will also create a panel useful for everyone.
