### ISSUE TITLE
How should i complete Yetiforce Github authorization?

### ISSUE THREAD

**Issue by rajukiran** [YetiForceCompany/YetiForceCRM#3783]
Hi,

I would like to authorize yetiforce with github for accessing all modules.

When i try to do that i have 3 fields need to be filled up.
1. User name
2. Client ID
3. Token

I generated new token with respect to that i got Token id and i have github username, now how could get **Client ID**?

* YetiForce Version used: 3.4.0
* Browser name and version: Chromium
* Environment name and version: 
* Operating System and version: Ubuntu 14.04 LTS

Regards

**Comment by paula-w** [comment]
The GitHub module is used to add/answer tickets at the CRM level, and it also allows us to read the server configuration, which makes it easier to verify problems. 

In order to get Client ID you should open settings, go to the OAuth Application tab, and register new developer application.

**Comment by rajukiran** [comment]
Thanks.

It seems to be in latest version of Yetiforce 3.4.0 doesn't have PurchaseOrder module.

Regards,

**Comment by paula-w** [comment]
If you have any other questions/problems to report please open a new issue, it makes it much easier for us to coordinate issues.
