### ISSUE TITLE
Taxes and discount 

### ISSUE THREAD

**Issue by Luxx99** [YetiForceCompany/YetiForceCRM#3785]
#### Issue

I'm setting up a Quote, and I'd like to add both a tax and a discount.

I configured YetiForce with the following values:
- Discount - summation type: cascade and available discont: global, group, individual and I added 1 discount applicable
- Taxes - summation type: cascade and available discont: global, group, individual and I added 2 tax rates

#### Actual Behavior

In the quote I add the product and the price list. All the other fields are disabled and I do not see any link to click to add a tax or diwscount

#### Expected Behavior

what I do wrong?

#### Your Environment

YetiForce Version used: 3.4.0
Browser name and version: Chrome 54.0.2840.99 m (64-bit)
Environment name and version: Application hosted on SiteGround Linux webserver with Apache, PHP5.6, MySQL
Operating System and version: Accessed from my desktop (Windows 10 64-bit Pro)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
could you please record your actions with screen2gif at [GitDeveloper](https://gitdeveloper.yetiforce.com/)?
