### ISSUE TITLE
Does YetiForce 3.4.0 has PurchaseOrder module?

### ISSUE THREAD

**Issue by rajukiran** [YetiForceCompany/YetiForceCRM#3786]
Hi,

I'm keep searching from almost a day. Finally, I got to notified that there is no PurchaseOrder module for Yetiforce 3.4.0

Is there any opensource setup for PurchaseOrder module in YetiForce 3.4.0?

I think without purchase order few of the modules are useless. If PO is there with a little bit newer which I didn't identify... please help me to find out.

* YetiForce Version used: 3.4.0
* Browser name and version: Chromium
* Environment name and version: Yetiforce
* Operating System and version: Ubuntu 14.04 LTS

Thanks & Regards,

**Comment by paula-w** [comment]
This module exists in our system under a different name - https://gitstable.yetiforce.com/index.php?module=SSingleOrders&view=List&mid=124&parent=118

**Comment by rajukiran** [comment]
Hi,

The link what you provided directing me to SalesOrder. I was speaking about PurchaseOrder. I looked into it clearly ... 

If possible suggest me with a scenario how one can create a PurchaseOrder record with that URL.

Thanks

**Comment by paula-w** [comment]
Try Goods Received Note then https://gitdeveloper.yetiforce.com/index.php?module=IGRN&view=List&mid=133&parent=131. It's used for the same purpose as PurchaseOrder was used in Vtiger. We'll also add a module called "Quote from Vendor" at some point, it'll take part in the sales process as well.
