### ISSUE TITLE
[PL]Moduł Umowy wsparcia SLA

### ISSUE THREAD

**Issue by yetitest** [YetiForceCompany/YetiForceCRM#3787]
#### Issue

Czy istnieje możliwość dodania widoku podsumowania do modułu "Umowy wsparcia SLA" , zależy nam na uruchomieniu widżetu komentarzy w tym module, aby można było prowadzić własne zapiski/notatki do podpisywanych umów SLA.

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
Można dodać [i nawet od strony logiki biznesowej to dodamy w przyszłości], ale to trzeba robić od strony programistycznej.

**Comment by yetitest** [comment]
Tak rozumiem, chciałem wiedzieć czy planujecie taką rozbudowę. Dzięki.
