### ISSUE TITLE
Not allow Product quantity is negative

### ISSUE THREAD

**Issue by huyencodon** [YetiForceCompany/YetiForceCRM#3791]
Please help me how i can config for "Product quantity" is not allow negative?

![negative](https://cloud.githubusercontent.com/assets/16998531/20656905/ca960476-b563-11e6-9382-4e4c590280cc.jpg)

**Comment by vovpff** [comment]
@huyencodon i this is impossible. You can made trigger with notification of values less than 0

**Comment by huyencodon** [comment]
@vovpff please help me how i can do that? where i can made a trigger? thank you so much!

**Comment by vovpff** [comment]
@huyencodon step by step. This is very simle example.
![image](https://cloud.githubusercontent.com/assets/8545791/20755003/70c0c208-b71e-11e6-890c-611aa28f02a4.png)
![image](https://cloud.githubusercontent.com/assets/8545791/20755027/8245d3ce-b71e-11e6-9029-39ebb140ae87.png)
![image](https://cloud.githubusercontent.com/assets/8545791/20755044/93ca5a70-b71e-11e6-816f-93dea1550921.png)
![image](https://cloud.githubusercontent.com/assets/8545791/20755057/a36cfd70-b71e-11e6-8233-15384ccb25c5.png)
![image](https://cloud.githubusercontent.com/assets/8545791/20755071/b11d0d84-b71e-11e6-8850-61611810caeb.png)
I made this on dev version. Last stable don't have possibility to notify record owner.

One more simpliest way is to made filter for products where you will see only <0 qty products and check this filter somtimes or list them in metrics. For greater solution you can try any different things.

**Comment by huyencodon** [comment]
@vovpff thank you so much. I'll try this!

**Comment by vovpff** [comment]
@huyencodon there are a lot of tools to get needed result by different ways. Checka all possible things and you will find greatest solution.
