### ISSUE TITLE
BUG??- One to many relation error

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3792]
#### Issue
Maked module "NEW MODULE", making relation one to many with ACCOUNTS. **Tried with NEW to ACC and ACC to NEW - display fatal error:** 
"Fatal error: Call to a member function getTableName() on null in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/Relation.php on line 349"

ALSO: tried with relation "Attachments" it display error too.
**By the way:** HOW TO USE relations "M2M with separation of data" and relation "Attachments"

Tired on DEVELOPER [ver. 3.4.814] and on YF 3.4.0 with hotfix

#### Expected Behavior
make relationship

#### Your Environment

* YetiForce Version used: DEVELOPER [ver. 3.4.814] and on YF 3.4.0 with hotfix
* Browser name and version: chrome

**Comment by paula-w** [comment]
It was fixed in the latest version. Can you please check it again and let me know if it's working for you now?

**Comment by serbiaserbia** [comment]
What is latest version? Is it DEVELPER version on Github?

I checked on DEV version before one hour ago.

**Comment by paula-w** [comment]
you checked  3.4.814, current gitdev is  3.4.815, that's why I asked you to check again and let us know.

**Comment by serbiaserbia** [comment]
Ok, I will check.

Please check #3793, maybe it is related with this issue.

**Comment by serbiaserbia** [comment]
Checked on ver. 3.4.815

"Novooo" relation with existing module>
   > "NOVOOO" Many2Many  to Contacts / working ok
   > "NOVOOO" One2Many to Accounts / same problem display error
   > "NOVOOO" Many2Many with separation to Leads / working ok
   > "NOVOOO: Attachments to Partners / same problem, display error

"Newsecond" module>
   > Accounts One2Many with "NewSecond" / same problem, display error

/////////////////////
### Fatal error: Call to a member function getTableName() on null in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/Relation.php on line 349

//////////////////////////
{"success":false,"error":{"code":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vtiger_notes.notesid' in 'on clause'\nFailed to prepare SQL: SELECT `u_yf_partners`.`subject` AS `subject`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `u_yf_partners`.`partnersid` AS `id` FROM `u_yf_partners` INNER JOIN `vtiger_crmentity` ON u_yf_partners.partnersid = vtiger_crmentity.crmid INNER JOIN `vtiger_senotesrel` ON vtiger_senotesrel.notesid= vtiger_notes.notesid INNER JOIN `vtiger_crmentity` `crm2` ON crm2.crmid = vtiger_senotesrel.crmid WHERE (vtiger_crmentity.deleted=0) AND (((`crm2`.`crmid`=:qp0))) LIMIT 21","message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vtiger_notes.notesid' in 'on clause'\nFailed to prepare SQL: SELECT `u_yf_partners`.`subject` AS `subject`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `u_yf_partners`.`partnersid` AS `id` FROM `u_yf_partners` INNER JOIN `vtiger_crmentity` ON u_yf_partners.partnersid = vtiger_crmentity.crmid INNER JOIN `vtiger_senotesrel` ON vtiger_senotesrel.notesid= vtiger_notes.notesid INNER JOIN `vtiger_crmentity` `crm2` ON crm2.crmid = vtiger_senotesrel.crmid WHERE (vtiger_crmentity.deleted=0) AND (((`crm2`.`crmid`=:qp0))) LIMIT 21"}}
#0 vendor/yii/db/Command.php(900): yii\db\Command->prepare(true)
#1 vendor/yii/db/Command.php(368): yii\db\Command->queryInternal('fetchAll', NULL)
#2 vendor/yii/db/Query.php(217): yii\db\Command->queryAll()
#3 modules/Vtiger/models/RelationListView.php(219): yii\db\Query->all()
#4 modules/Vtiger/views/RelatedList.php(80): Vtiger_RelationListView_Model->getEntries(Object(Vtiger_Paging_Model))
#5 modules/Vtiger/views/Detail.php(495): Vtiger_RelatedList_View->process(Object(Vtiger_Request))
#6 [internal function]: Vtiger_Detail_View->showRelatedList(Object(Vtiger_Request))
#7 include/runtime/Controller.php(89): call_user_func_array(Array, Array)
#8 modules/Vtiger/views/Detail.php(195): Vtiger_Controller->invokeExposedMethod('showRelatedList', Object(Vtiger_Request))
#9 include/main/WebUI.php(222): Vtiger_Detail_View->process(Object(Vtiger_Request))
#10 index.php(24): Vtiger_WebUI->process(Object(Vtiger_Request))
#11 {main}

**Comment by serbiaserbia** [comment]
now I tested on ver. 3.4.818
same problem

**Comment by TomaszQr** [comment]
Improved via https://github.com/YetiForceCompany/YetiForceCRM/commit/ba25f890d1e0c7b9fe9a8e9a03f89aa2f9d91d5a
Removed the possibility to add 1:M relation. This relation is based on a field that should be added to the module.
