### ISSUE TITLE
BUG??- many to many with separation 

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3793]
#### Issue
New module created "NEW MODULE"
tested with two relations (only m2m with separation)
1. NEW MODULE with ACCOUNT
     does not display ADD and SELECT button
2. ACCOUNT with NEW MODULE
    display ADD and SELECT button

On DEVELOPER version it all works
On STABLE and MASTER cant test because cannot make relations
On my YF 3.4.0 problem exist.

#### How to trigger the error
making new realtion

#### Your Environment

* YetiForce Version used: dev, master, stable and hosted YF 3.4.0
* Browser name and version: chrome
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
The relations were rebuilt in the dev version. We tried to make a M2M relation at vtlib level and we didn’t notice any problems. 
The names for relations were changed, so please take a look at it. In 3.4 the relation was called get_many_to_many and now it’s called getManyToMany. You should check the entries in vtiger_relatedlists table. 
Also please either describe how you add relations, or show us in a screenshot/gif.

**Comment by serbiaserbia** [comment]
I tried to make relations from the menu.
Sorry, but I am not have any programming lavel experience,  I am just classic consumer :-(
I will make gif, later on my installed YF 3.4. Everything I tried is from menu.

I there any way to add changes to my installed version? Do I have to make some changes?

**Comment by serbiaserbia** [comment]
@paula-w sorry for late for my screenshot gif.
YF 3.4 my installation
NEW MODULE tested with all relations. Only M2M is working properlly
![yf3-4](https://cloud.githubusercontent.com/assets/19521910/20706844/80f6e8be-b629-11e6-9821-28f1d2851acd.gif)

YF 3.4.834 developer
NEW MODULE tested with all relations. M2M, M2M wit separation is working properlly
![yfdev newmod to all rel](https://cloud.githubusercontent.com/assets/19521910/20706865/a7f12a10-b629-11e6-8700-aedfcb9cf6f5.gif)

By the way> please can you explain how to use these 2 relations and what is their purpose
1. M2M with separatio
2. Attachment relation

best regards

**Comment by TomaszQr** [comment]
1. Relation M2M with separation is a relation based on a new table in the database.
2. Relation Attachment relations is used to relate modules to documents.
