### ISSUE TITLE
[Question] Help required -> howto transfere YetiForce on VirtualBox to vServer

### ISSUE THREAD

**Issue by ABaumruck** [YetiForceCompany/YetiForceCRM#3794]
#### Description
For testing and upgrading purposes I've set up YetiForce on VirtualBox running under NAT
After it was working (almost) without problems I decided to move the image to my vServer.

The switch was flawless with the exeption of one nasty error. 

#### Actual Behavior
Whenever I try to access the YF installation on the vServer I get pushed back to my former localhost page/subdirectory (e.g. http://localhost:8080/yf01)

#### Expected Behavior
YF on the vServer should be accessible in the same way as when I use the VM running locally on VirtualBox

#### additional information
I'm pretty sure that this has something to do with the configuration of YF during the setup but I'm unable to either find the config file related or any other related information

To make sure that this is a YF related behaviour I've set up two different apache VirtualHosts with only the subdirectory to be different ("yf01" -> "yf02").
The folder without YF installed is accessible as expected, YF itself still not

#### Your Environment
* YetiForce Version used: YetiForce 3.4 + Hotfix
* Browser name and version: Chrome 54.0.2840.99 m
* Environment name and version: vServer
* Operating System and version: Ubuntu Server 16.04.1 LTS

any help or idea is highly appreciated
BR Andreas

**Comment by vovpff** [comment]
@ABaumruck check your configuration files at /config folder and fill new values for vServer

**Comment by bpabiszczak** [comment]
If you change the location of the system, you need to change configurations [config/config.inc.php].
