### ISSUE TITLE
BUG? Costumer portal undefined variable $onlymine

### ISSUE THREAD

**Issue by forreggbor** [YetiForceCompany/YetiForceCRM#3796]
#### Issue
If you open on Tickets there is a PHP Notice in the log: 
PHP Notice:  Undefined variable: onlymine in /modules/HelpDesk/index.php on line 27

Same issue with Documents, Services, Products modules:
/modules/Module/index.php on line 42
/modules/Services/index.php on line 24
/modules/Products/index.php on line 23

#### How to trigger the error
Open Tickets menu.

#### Possible solution?
Replace code in /modules/HelpDesk/index.php line 27 and 28
		if ($allow_all != 'true') 
			$onlymine = "true";

with this code:
		if ($allow_all != 'true') {
			$onlymine = "true";
		} else {
			$onlymine = "false";
		}

#### Your Environment
* YetiForce Version used: 3.4.0+fix - portal: 3.2.0

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

Please check: error_reporting
