### ISSUE TITLE
BUG? Costumer portal undefined variable $data

### ISSUE THREAD

**Issue by forreggbor** [YetiForceCompany/YetiForceCRM#3797]
#### Issue
If you open Tickets' list there is a PHP Notice in the log:
PHP Notice:  Undefined variable: data in /modules/HelpDesk/index.php on line 38
It looks like the $lmod variable is not set in line 32: 
$lmod = $GLOBALS["sclient"]->call('get_tickets_list', $sparams);

Same issue with Documents, Services, Products modules.

#### How to trigger the error
Open Tickets's list on customer portal

#### Your Environment
YetiForce Version used: 3.4.0+fix - portal: 3.2.0

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

Please check: error_reporting
