### ISSUE TITLE
Value from related module

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#3798]
Idea "Value from Related module" is great, but I dont see how to properlly to use it

#### Issue
**EDITING**
When editing record who have field "Value from RM" , related field become empty
![valuefromrelediting](https://cloud.githubusercontent.com/assets/19521910/20711646/0a769abe-b641-11e6-8a6e-edcf65adb942.gif)

**DELETE**
When record have related module and selected  records from there / In case that in related module record been deleted or changed/ field is not updated!
![valuefromreldelating](https://cloud.githubusercontent.com/assets/19521910/20711679/3a6c943a-b641-11e6-9065-eb4b748cd367.gif)

#### Expected Behavior
I expect that field "Value from Related module" to be updated and refreshed on every change.

#### How to trigger the error
I tried to wait CRON to see it will be somethnig updated, but nothing.

Tried on my YF 3.4 and developer 3.4.840 / Everything is the same, maybe I dont sufficiently understand this option.

* YetiForce Version used:  YF 3.4 and developer 3.4.840
* Browser name and version: chrome

**Comment by KatarzynaUlichnowska** [comment]
Hello,
could you please check the latest version at [GitDeveloper](https://gitdeveloper.yetiforce.com/) and record how you configure it?
