### ISSUE TITLE
How can I change Widget Color Graphs of YF CRM?

### ISSUE THREAD

**Issue by VSecurity** [YetiForceCompany/YetiForceCRM#38]

**Comment by VSecurity** [comment]
I would like to change all graphics color. It is possible?



On January 5, 2015 at 6:18:13 PM, Mariusz Krzaczkowski (notifications@github.com) wrote:

Please inform us in which the chart?

**Comment by KatarzynaUlichnowska** [comment]
Hello,
could you please send us screenshots and highlight the elements which you would like to change?
