### ISSUE TITLE
Version 3.4.0 There is no active transaction when adding any record

### ISSUE THREAD

**Issue by ninijka** [YetiForceCompany/YetiForceCRM#3800]
After installation of 3.4.0 version, when trying adding any record (Contact, Lead, Competition ...) foloowing message appears: There is no active transaction

Below following stack is reported:
#0 D:\Git\yetidemo\include\database\PearDatabase.php(235): PDO->rollBack()
#1 D:\Git\yetidemo\include\database\PearDatabase.php(152): PearDatabase->rollbackTransaction()
#2 D:\Git\yetidemo\include\database\PearDatabase.php(336): PearDatabase->checkError('SQLSTATE[22001]...', false, 'INSERT INTO `o_...', Array)
#3 D:\Git\yetidemo\include\database\PearDatabase.php(402): PearDatabase->pquery('INSERT INTO `o_...', Array)
#4 D:\Git\yetidemo\include\exceptions\NoPermitted.php(29): PearDatabase->insert('o_yf_access_for...', Array)
#5 D:\Git\yetidemo\include\exceptions\NoPermittedToRecord.php(14): Exception\NoPermitted->__construct('LBL_RECORD_NOT_...', 0, NULL)
#6 D:\Git\yetidemo\include\CRMEntity.php(781): Exception\NoPermittedToRecord->__construct('LBL_RECORD_NOT_...')
#7 D:\Git\yetidemo\include\events\VTEntityData.inc(47): CRMEntity->retrieve_entity_info(119, 'Competition')
#8 D:\Git\yetidemo\include\events\VTEntityDelta.php(52): VTEntityData::fromEntityId(Object(PearDatabase), 119, 'Competition')
#9 D:\Git\yetidemo\include\events\VTEntityDelta.php(92): VTEntityDelta->fetchEntity('Competition', 119)
#10 D:\Git\yetidemo\modules\ModTracker\handlers\ModTrackerHandler.php(38): VTEntityDelta->getEntityDelta('Competition', 119, true)
#11 D:\Git\yetidemo\include\events\VTEventTrigger.inc(154): ModTrackerHandler->handleEvent('vtiger.entity.a...', Object(VTEntityData))
#12 D:\Git\yetidemo\include\events\VTEventsManager.inc(124): VTEventTrigger->trigger(Object(VTEntityData))
#13 D:\Git\yetidemo\include\CRMEntity.php(842): VTEventsManager->triggerEvent('vtiger.entity.a...', Object(VTEntityData))
#14 D:\Git\yetidemo\modules\Vtiger\models\Module.php(181): CRMEntity->save('Competition')
#15 D:\Git\yetidemo\modules\Vtiger\models\Record.php(294): Vtiger_Module_Model->saveRecord(Object(Vtiger_Record_Model))
#16 D:\Git\yetidemo\modules\Vtiger\actions\Save.php(80): Vtiger_Record_Model->save()
#17 D:\Git\yetidemo\modules\Vtiger\actions\Save.php(58): Vtiger_Save_Action->saveRecord(Object(Vtiger_Request))
#18 D:\Git\yetidemo\include\main\WebUI.php(215): Vtiger_Save_Action->process(Object(Vtiger_Request))
#19 D:\Git\yetidemo\index.php(26): Vtiger_WebUI->process(Object(Vtiger_Request))
#20 {main}

Guide me please in order to find a root cause.

**Comment by vovpff** [comment]
@ninijka check your cron and webserver requirements.

**Comment by ninijka** [comment]
Thank you for your quick feedback.
I installed it on Windows 10 (no cron) with Wamp web server: PHP 5.6.25 and MySQL 5.7.14
All setting in php.ini I set up according to installer requirements.

For me it looks like database permission problem.
But I'm connected with user root to MySQL database and I've got all priviledges: 
#2 D:\Git\yetidemo\include\database\PearDatabase.php(336): PearDatabase->checkError('SQLSTATE[22001]...', false, 'INSERT INTO o_...', Array) #3 D:\Git\yetidemo\include\database\PearDatabase.php(402): PearDatabase->pquery('INSERT INTOo_...', Array)
#4 D:\Git\yetidemo\include\exceptions\NoPermitted.php(29): PearDatabase->insert('o_yf_access_for...', Array)
#5 D:\Git\yetidemo\include\exceptions\NoPermittedToRecord.php(14): Exception\NoPermitted->_construct('LBL_RECORD_NOT...', 0, NULL)

What exactly do you advice to check?

**Comment by SkavenKF** [comment]
look at [my comment](https://github.com/YetiForceCompany/YetiForceCRM/issues/3779#issuecomment-262562013)
On Windows you need an entry in the task scheduler (example from my win10 dev installation):
![task](https://cloud.githubusercontent.com/assets/10259801/20794201/490bc386-b7cb-11e6-82fa-88bb4bd8b147.jpg)

**Comment by ninijka** [comment]
Yhank you for your support.
I've checked and I don't have any task in task scheduler.
I've started vtigercron.bat manually and no effect.
Still have problems with creation of data.
I don't think that this cron job is related to my problem.

**Comment by vovpff** [comment]
@ninijka check your WAMP setting for MySQL. Let's repeat settings like on screenshot below. Check **sql-mode -> user mode**.
![image](https://cloud.githubusercontent.com/assets/8545791/20796909/9d48d2cc-b7e9-11e6-8fa6-ec882a15c0d3.png)

For correct cron workability you need to configure rigth paths for next lines at `vtigercron.bat`
```
set VTIGERCRM_ROOTDIR="C:\wamp\www\ys"
set PHP_EXE="C:\wamp\bin\php\php5.6.25\php.exe"
```

**Comment by ninijka** [comment]
Exactly STRICT_TRANS_TABLES was a root cause.
I found it earlier in following issue: https://github.com/YetiForceCompany/YetiForceCRM/issues/1573
and fixed.
But thank you very much for great help.
Stay cool.
