### ISSUE TITLE
Quick create Contact from Account

### ISSUE THREAD

**Issue by huyencodon** [YetiForceCompany/YetiForceCRM#3802]
Hi all,

Can i have a field for select or quick create new Contact when i create Account?

I think it's necessary and convenient!

Thanks!

**Comment by SkavenKF** [comment]
![account](https://cloud.githubusercontent.com/assets/10259801/20834794/5de70406-b897-11e6-9827-ed9b306015d2.JPG)

or Tab "Contacts"

**Comment by huyencodon** [comment]
ok, tks u! @SkavenKF
