### ISSUE TITLE
update stock quantity in storage after creating invoice

### ISSUE THREAD

**Issue by ousidahou** [YetiForceCompany/YetiForceCRM#3803]
I am trying to update stock quantity in storage after creating invoice. That is handy if you don't need/want to go through all procedure. In Vtiger we had UpdateInventory custom function in WF. I can't find something similar or some other way to do this in YetiForce

**Comment by vovpff** [comment]
@ousidahou for quantity update you must use Goods Received Note (PO in vtiger) and Goods Dispatched Note (like Invoice in vtiger) at Logistics tab. When this modules records status changed to Accepted quantity will be automatically update and record became uneditable.
