### ISSUE TITLE
Filter problem with new modules

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3804]
Hey all, i'm using 3.4.1 and have an issue with a new module i've created.

The Filter just keeps saying loading when trying to change the filter type on it.

here is the gif below for this.
![filterfault](https://cloud.githubusercontent.com/assets/22075161/20884715/ddd6a334-bae4-11e6-88f4-1ff277d2a1e6.gif)

**Comment by kpaulaha** [comment]
I have made several custom modules without such problems. Maybe something with your module?

**Comment by alextovey** [comment]
Well, i've recreated the module and still the same. On a custom module what files is yetiforce supposed to create along with it?

**Comment by vovpff** [comment]
@alextovey maybe cron activation can help. Try this.

**Comment by konadrian** [comment]
We need more info regarding this issue, please try to trigger it at https://gitdeveloper.yetiforce.com/. It's working ok for me
![animation](https://cloud.githubusercontent.com/assets/3193498/21494308/c3b45dce-cc10-11e6-8e25-ebcdccd35a0f.gif)

**Comment by alextovey** [comment]
This was resolved by having cron jobs setup
