### ISSUE TITLE
upload, download problem

### ISSUE THREAD

**Issue by efernau** [YetiForceCompany/YetiForceCRM#3805]
When we upload a jpg file and download it the image file is corrupt. The same with docx or txt. 
Pdf files can be downloaded without problems. 

Does anyone have a solution, or an idea ? 

We use  YetiForce ver. 3.4.0

Many thanks for the excellent ideas and suggestions.

**Comment by ABaumruck** [comment]
@efernau 
made a short check on my (clean) YetiForce 3.4.21, no noticable problems.
Tried small and large jpeg as well as a .docx file

I recommend that you check within your YetiForce installation:

- "Software configuration > Logs > Server configuration" and there the "YetiForce Engine" tab 
(of course the others as well)
- might be something within the PHP.ini settings that prevents the file from uploading properly. If you are able to locate the file on the server check the uploaded filesize against the original.

And please provide a little more details about your environment!!

Regards,
Andreas
