### ISSUE TITLE
[PL]Format daty w komentarzu

### ISSUE THREAD

**Issue by yetitest** [YetiForceCompany/YetiForceCRM#3806]
#### Issue

Czy istnieje możliwość przestawienia gdzieś w systemie formatu kiedy został wpisany komentarz. Teraz wyświetla że komentarz był np. 5 dni temu 8 dni temu 21 dni temu. Czy możliwe jest aby wyświetlana była data tego komentarza np. 11.11.2016, gdzie i czy można przestawić to samemu ?

![asas](https://cloud.githubusercontent.com/assets/22539294/20925512/bc0b30b6-bbb7-11e6-9cf2-a6c5ac880c09.png)

#### Your Environment

* YetiForce Version used: 3.4.0

**Comment by bpabiszczak** [comment]
Po najechaniu na datę np. 21 dni temu, pojawia się data w standardowym formacie...
