### ISSUE TITLE
text lenght on Additional line

### ISSUE THREAD

**Issue by YorgoB** [YetiForceCompany/YetiForceCRM#3807]
First of all congrats for this great product !
#### Issue

In Sales section, Sales/Sales enquiries, the text length of **Additional line** of **Products or Services** has a limit close to 70 words. 

#### Actual Behavior

As result when I save a text with more than 70 words the rest of the words are gone .
#### Expected Behavior

Is there a way to remove this limit ? 
#### How to trigger the error

1.  Sales enquirie
2. Add a record
3.Add a service or product and text to additional line ,more than70 words ,save. Then edit 

#### Your Environment

Yeti 3.4.0
Chrome 54.0.2840.99
Windows 7

**Comment by YorgoB** [comment]
After installation of the fix version, when I'm trying to add a record at sales section (esquires, requirements etc ) I'm receiving first error 1.png and then when I try to go again to add a record I'm receiving error 2.png.

Thank you !

![1](https://cloud.githubusercontent.com/assets/24439715/22510986/b8b330e6-e89c-11e6-9ad4-4561cd6338c8.png)
![2](https://cloud.githubusercontent.com/assets/24439715/22510985/b8b1f76c-e89c-11e6-8316-6729c6d351d4.png)

**Comment by paula-w** [comment]
This is a different error, please open a separate issue and describe it. Let us know whether the error occurs on a clean version as well.
