### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by ninijka** [YetiForceCompany/YetiForceCRM#3810]
I'd like to ask you to guide me in installation of CRM on public server.
It works on local environment, but when I copy db and CRM files 1:1 to public server,
when displaying any screen I get amount of following messages "undefined index...".
Example:
Notice: Undefined index: VIEWNAME in /home/crmdemo/public_html/cache/templates_c/basic/8f50f29a69d89640da3242656f6a7508db2dd7c5_0.file.Pagination.tpl.php on line 26 Notice: Trying to get property of non-object in /home/crmdemo/public_html/cache/templates_c/basic/8f50f29a69d89640da3242656f6a7508db2dd7c5_0.file.Pagination.tpl.php on line 26

What could be possible root cause or where to search it (in db i config)?
Maybe some files (like translation) cannot be found due to filesystem priviledges?

Thank you for help

**Comment by skramanzia** [comment]
Hi @ninijka, please check Web Server Requirements guide. https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

Whats php version has yours public provider?
