### ISSUE TITLE
Widget Assigning to Multiple Users

### ISSUE THREAD

**Issue by Sindhuja16** [YetiForceCompany/YetiForceCRM#3812]
Widget Assigning to Multiple Users

#### Issue
Can't we add a particular widget to more than a single user at a time ?
I have to add same widget to many users, and doing it by adding their roles one by one in widget configuration which is tedious, can I get it done in another way?

 

#### Actual Behavior
 one widget to one user

#### Expected Behavior
 same widget to multiple users

#### Your Environment

YetiForce Version used: 3.4.0

**Comment by bpabiszczak** [comment]
Right now the widgets can be added in two ways:
1. in the panel for many people in a given role [https://gitdeveloper.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67] 
2. Individually, at the user level

For us these options are sufficient for now, and we’re not planning to develop it.

**Comment by ldgbc** [comment]
That a rather weird decision. I hope that changed in the future. Preferable with default widget that can be assigned to "All Role"
