### ISSUE TITLE
Not emailing contact or login credentials

### ISSUE THREAD

**Issue by slater101** [YetiForceCompany/YetiForceCRM#3814]
#### Issue
system is not emailing clients login data to portal. I have followed all manuals, cron is running, smtp is working and test works. portal is setup and config.inc / config and api.php have all been set correctly.

**In location Software configuration > Automation > Workflows

Generate customer login details (All tasks 1) (Active tasks 0)
Send customer login details (All tasks 2) (Active tasks 0)**

After I clicked the checkbox to the right it became

Generate customer login details (All tasks 1) (Active tasks 1)
Send customer login details (All tasks 2) (Active tasks 2)

But still no emails sent

In config.inc

`// url for customer portal (Example: https://portal.yetiforce.com/)
$PORTAL_URL = 'https://myportal.mysite.com';

// helpdesk support email id and support name (Example: 'support@yetiforce.com' and 'yetiforce support')
$HELPDESK_SUPPORT_NAME = 'LOFD Client Portal';
$HELPDESK_SUPPORT_EMAIL_REPLY = 'kyle@litonfire.design';`

In api.php

`$enabledServices = [
	//'mobile',
	'yetiportal',
	//'dav',
	//'webservices',
	//'webservice',`

In 

CRM config.php

`$vtiger_path = "https://CRM.mywebsite.com";`

Cron lines

*/5**** sh /home/litafire/portal.litonfire.design/cron/vtigercron.sh
*/5**** >/home/litafire/portal.litonfire.design/cache/logs/cron.log

Permissions set to 755 for all folders and files in /cron

Cron is working

SMTP is working

#### Actual Behavior
Create contact, system creates. No emails received by contact.

#### Expected Behavior
Send Emails, find contacts again via search

#### How to trigger the error
1.create contact
2.contact is made
3.no emails sent even with cron running and smtp on and working.

#### Your Environment

* 3.4.0
* All Web browsers
* linux (version unknown but probably latest)

NOTE: in  Software configuration > Logs > Server configuration > Start It is showing that ZIP library and LBL_SOAP_LIBRARY are not installed. But I installed both "archive zip" and "soap" for php on my server... why would this be this way? am I missing some files?

**Comment by skramanzia** [comment]
Hi @slater101 you have to enable workflow to send email. In workflow -> Contacts

![image](https://cloud.githubusercontent.com/assets/3030997/21083587/351078b8-bfd2-11e6-9164-dd7aa518b869.png)

**Comment by slater101** [comment]
I have clicked on send customer login details, then whent through the process and see that a condition is "if permission to send emails is set to yes" but How do I set permission?

I can't find where I turn the permission to send emails on.

Thanks,
Kyle

**Comment by skramanzia** [comment]
@slater101 is a check in the contact module when you select a contact.

![image](https://cloud.githubusercontent.com/assets/3030997/21084419/0f99525c-bfe2-11e6-87cb-5465d0974dd7.png)

**Comment by slater101** [comment]
Skramanzi,

I have done this the whole time with all of my testing.

This does not fix the issue.

Regards.
Kyle

**Comment by skramanzia** [comment]
Are you enable active task in Workflow?, Can test again creating a new contact?. Email only send the first time. You can check if user create in database table "w_yf_portal_users"

**Comment by slater101** [comment]
Yes in workflow it is set to active for all tasks related to contacts.

I have tested again with new contact.

No email sent.

Will check if database user created now, will respond with table info.

Thanks.
Kyle

**Comment by slater101** [comment]
w_yf_portal_users is not there?

I have no tables that even start with a W_

Thanks,
Kyle

**Comment by skramanzia** [comment]
Sorry my bad.. the table is "vtiger_portal"

**Comment by skramanzia** [comment]
In my system the table is correct. I am not use portal in this environment, but the information save iit in the table.

![image](https://cloud.githubusercontent.com/assets/3030997/21084653/9da73eda-bfe5-11e6-8cd5-2061f28cd4f3.png)

**Comment by slater101** [comment]
@skramanzia I did find w_yf_portal_users, sorry.

It is empty, no rows.

Thanks,
Kyle

**Comment by slater101** [comment]
Could this be why?

NOTE: in Software configuration > Logs > Server configuration > Start It is showing that ZIP library and LBL_SOAP_LIBRARY are not installed. But I installed both "archive zip" and "soap" for php on my server... why would this be this way? am I missing some files?

What is LBL_SOAP_LIBRARY? I cannot find anything on google, I thought it was SOAP for PHP so I activated it in my PHP environment and also Activated "Archive ZIP" for php environment but Yeti still says both missing.

**Comment by slater101** [comment]
Is there an example setup of how custom .htaccess should be? I saw it on the knowledgebase but cannot find it now. I think its my database timeout.

Thanks,
Kyle

**Comment by skramanzia** [comment]
@slater101 The two libraries you mention are mandatory to use Yetiforce. what's your S.O? and php version?

**Comment by slater101** [comment]
@skramanazia

Apache Version	2.4.18
PHP Version	5.6.17
MySQL Version	10.0.27-MariaDB-cll-lve

Thanks,
Kyle

**Comment by skramanzia** [comment]
Ok, check the Web server requirement to apply all the recommendation.

https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

However you can install missing libraries like this (if you use centos for example). after download epel.

yum install php-soap

For ZIP, you can install php-pecl-zip or install php common. If you compile php remember add "--enable-zip" to enable zip library.

**Comment by slater101** [comment]
I installed php SOAP via pear, does Yetiforce work with Pear installs?

Thanks

**Comment by skramanzia** [comment]
Install SOAP via pear is not the same. I tried this in other time, but only works when install php-soap. It's important check in Logs > Server configuration to confirm the correct instalation of library

**Comment by slater101** [comment]
Ok, thanks so much @skramanzia I have asked my server admins to handle this since I do not have access to root.

You have been super helpful hopefully this will fix the issue,

I have also asked them to increase timeouts to the following

max_execution_time 600
max_input_time 600 -1
default_socket_timeout 600
mysql.connect_timeout 600
innodb_lock_wait_timeout 600

I am on shared hosting though so I dont know if they will do it.

Regards,
Kyle

**Comment by slater101** [comment]
@skramanzia 

I have fixed everything with the php settings and it is all working now, but I am still not getting any rows created in `w_yf_portal_users`. Im not sure why :(

Thanks.
Kyle

**Comment by slater101** [comment]
Wait, I just saw that innodb_lock_wait_timeout is set to 50 and not 600, maybe thats it?

Will change and see.

Regards,
Kyle

**Comment by slater101** [comment]
@skramanzia in **vtigercron.sh** If,  export USE_PHP=/usr/local/bin/php was wrong would it have anything to do with it?

Or should export USE_PHP=/usr/local/bin/php be commented out?

Thanks,
Kyle

**Comment by skramanzia** [comment]
innodb_lock_wait_timeout is a MySQL parameters, check all parameters before go ahead, is too important. Msql and PHP.

 Check this example.
![image](https://cloud.githubusercontent.com/assets/3030997/21086358/9cb1a5fa-bffa-11e6-9e47-11b7d01b18f6.png)

![image](https://cloud.githubusercontent.com/assets/3030997/21086361/ab1eb70e-bffa-11e6-9227-beeca31131ca.png)


**vtigercron.sh** like this.
![image](https://cloud.githubusercontent.com/assets/3030997/21086387/ddac925e-bffa-11e6-87d0-66d88fad68fc.png)


**Crontab** like this to run every five minutes
*/5 * * * * sh /var/www/yetiforce/cron/vtigercron.sh

**Comment by slater101** [comment]
Ok I had vtigercron.sh wrong I had this

export VTIGERCRM_ROOTDIR=`dirname "$0"`/..
export USE_PHP=php
export USE_PHP=/usr/local/bin/php
#export USE_PHP=/usr/local/php56/bin/php56

How can I set innodb_lock_wait_timeout via htaccess? I have tried every option I know.

innodb_lock_wait_timeout 600

Tried setting this in htaccess but couldn't get the following to work.

php_value innodb_lock_wait_timeout "600"
or
innodb_lock_wait_timeout "600"
or
innodb_lock_wait_timeout = 600

**Comment by skramanzia** [comment]
innodb_lock_wait_timeout and max_allowed_packet are mysql parameters, you need to set in /etc/my.cnf.

**Comment by slater101** [comment]
Ok, 

I have done everything except innodb_lock_wait_timeout 600, Since I am waiting on my server admin to handle it I wanted to see if that was the cause. 

Testing showed that without innodb_lock_wait_timeout 600 set to 600, currently "50" and tigercron.sh that my system did not make any rows in w_yf_portal_users.

So basically if after that is fixed and set to  innodb_lock_wait_timeout 600 and it works, we will know that was the cause of this issue. Just wanted to add this in for anyone that googles this problem in the future and trouble shoots all of the above steps.

Will update if innodb_lock_wait_timeout 600 fixes my issue and allows Yetiforce to create rows in table w_yf_portal_users.

Regards,
Kyle

**Comment by skramanzia** [comment]
Great, please after set parameters, test with create a new Contact and then set check in "portal user"

You can see internal Workflow email queue in "com_vtiger_workflowtask_queue" table.

Good luck.

**Comment by slater101** [comment]
They will not set it for me because I am on shared hosting. :-(

Might get dedicated IP to fix the issue.

What are some recommended hosts that Yetiforce works well on? Something that uses Cpanel.

Thanks
Kyle

**Comment by slater101** [comment]
Seems like with those requirements would have to have a VPS to make this work.

Might get a vps.

Will see really want to use this app. 

For now, thanks for all the help and take care @skramanzia

**Comment by slater101** [comment]
@skramanzia If I host my yeti system at example.com and my portal at example2.com will that work?

**Comment by ABaumruck** [comment]
Hello slater101!
I would recommend that you use a dedicated VPS or root server which allows you to install your preffered linux OS and you have full control over all settings including the "cron" job which normally is a killer criteria for simple hosting environments.

After a several  month long journey I ended up with [netcup.de](https://www.netcup.de/) and I am using their "RS 1000 G7 SE" root server. The reason why I found it to be the best is:

- you can upload your own images 
(I used ubuntu with VirtualBox to test YF 3.4 on my local computer, the I exported the VM converted the file to qcow2 format and uploded it to my root server. This worked nearly flawlessly exept for [this](https://github.com/YetiForceCompany/YetiForceCRM/issues/3794))
- you are able to make snapshots of your server (in case you are trying some updates/changes and you are not sure how it behaves)
- and it is good value for the money

If you need some further explanation on the required YF settings you might also like to [read this](https://github.com/YetiForceCompany/YetiForceCRM/issues/3744). It explains some of the poorly documented parts from the [YetiForce webserver requirements](https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html)
To be honest, this still not covers everything (no Portal, no webdav, ...)

Let me add one more thing. If you cannot get the "innodb_lock_wait_timeout = 600" setting correct **before** you install YetiForce there is a good chance that not all the db-tables are set up correctly. And my strong advise is to reinstall YetiForce. 
For example I noticed that when I had set it badly:
- the YF installation routine did not give a "finished" message
- I was unable to save some of the basic settings (like language, etc)
- And I was unable to configure some of the modules (aka add custom fields)

But the really odd thing was that YetiForce still "kind of" worked.

I hope this will help to shorten your journey to a proper YF installation
BR Andreas

**Comment by slater101** [comment]
@Abaumruck

Thanks so much for the great details.

Wow netcup.de has amazing servers for the price!

I have chosen a VPS server, and srarted learning linnux, I have been doing webdesign professionally for years but have only scratched the surface on server setup and maintenance, this is because most of my clients prefer a fully managed service wich I have never had the time to provide to them. But now that I am transitioning over to full setup, I have to say, its alot of fun! I love linnux, so powerful, easy, and I find learning the commands and operation is incredibly fast. Linnux is quite amazing. I am starting with the basics for now, practicing safe setup and standard security measure, have done a full lamp, multiple times now and getting better. Had issues running centos7 with php 5.6 and phpmyadmin, but am working the kinks of where I whent wrong. Might just go to centos6 for stability, but prefer going with the newest stuff first, so will see. Once I get my full lamp, plan to snapshot it, then explore how to configure everything. The host im using is very nice and great customer support so it has been perfect for the process of learning. They always help right away from livechat and are always willing to help out.

Thanks for all the notes and pointers, when I get there, I will make sure to have requirements set before I progress to installing.

Yetiforce is awesome, so awesome that I have decided to learn all of this just because of yetiforce.

I still havnt got to see what the inside of the client portal looks like but I trust that it is as awesome.

Can I run yetoforce and the portal on 2 different donmains? That is the plan.

Because I have my website on a cloud host since it is just html / css and like the speed, then I run my file and cloud management (subdomains) on a shared host for the space I am given since it does not require tons of speed and yeti on the vps for the power I need. I think this gives me the best (bang for the buck) plus keeps each piece of my website seperated for easy managment and flexibility.

Thanks for the help!

Regards,
Kyle

**Comment by slater101** [comment]
Also, on another note,

Should make something to steer people away from this host A2hosting
https://www.a2hosting.com/yetiforce-crm-hosting

False advertising hosting of yetiforce.

They cannot allow innodb_lock_wait_timeout 600 on the shared hosting plans they are advertising yetiforce on.

So they are false advertising and pulling people in with non functional yetiforce adds.

Just thought Id let you know that was going on.

**Comment by slater101** [comment]
@skramanzia @ABaumruck 

Not going to believe this, I built a server from the ground up on Centos7 Minimum, Had all requirements met before install.

Everything flawless, running fine... Still not creating any tables in w_yf_portal_users!

I don't know what it is?

Have all requirements met, cron running perfect, smtp works fine. Activated "Generate customer login details" and " Send customer login details" by setting them to "active" in workflows. 

Nothing, no users in tables?

What else could it be?

Please help, just spent two full days getting it all set up from scratch to be right back where I started...

Thanks,
Kyle

**Comment by slater101** [comment]
Look at this, the setting is right, but it is still showing up red... What does that mean?

Have reinstalled 2x and this still is like this.

![crazy](https://cloud.githubusercontent.com/assets/23393559/21222611/acecc452-c290-11e6-8c0e-b5c4aa596208.jpg)

**Comment by slater101** [comment]
OMG!!! I GOT IT!! HAHAHAA! lol

I am so happy right now..

I fixed it with this

export USE_PHP=/usr/lib64/httpd/modules/libphp5.so

In vtigercron.sh

It is because I am using an Rpm.

So freaking happy right now I cant even tell you... so happy..

Have this working with php 5.6.29 with this line.

Close this bad boy out!

Thanks everyone that helped. @skramanzia @ABaumruck you guys rock!

I will be doing a full right up on the full setup for Centos7 minimal with php 5.6 for anyone who wants to copy the install in the future, will be a step by step, should help some people.

Regards,
Kyle

**Comment by ABaumruck** [comment]
@slater101 
Had a look at your "cron job" entry, not sure that this will help you, but here is mine.

```
Sudo crontab -e
*/5 * * * * sh /var/www/html/yourYetiForce/cron/vtigercron.sh &>/var/www/html/yourYetiForce/cache/logs/cron.log
```
You have to keep in mind that
- I am running YF on Ubuntu 16.04 LTS, so you might have a different installation path
- the commands might be different as well
- As long as I understand this is the one and only cronjob you need to setup for YetiForce CRM. There is a chance that you will need another cronjob for the YetiForce portal (sorry I cannot help you much with the portal, since now I've never used it).

In terms of the "max_allowed_packet" I set this in the php.ini and I still get the same "red" failure message. For the moment I assume that to be a "minor bug" in YetiForce

On my VPS I am currently running PHP 5.6.29-1 without a (noticable) problem

Regards, 
Andreas

**Comment by slater101** [comment]
@ABaumruck 

For some reason, to get my cron to run, I had to do it like this inside of /etc/crontab file like so.
Wouldnt run in the "root" users crontab file.

I dont even think that cron.log is doing anything. Always stays empty.

As far as yeti goes, its running fine. But when it comes to users in the portal. It doesn't create any rows for them in the user tables.

Hasn't worked on either setup I did, Im starting to think this is an issue with the new release and they are not aware of it because so few people have installed it or maybe most upgraded and that's why it didn't effect them.

I think someone from the team should try doing a fresh install of the newest 3.4 yeti and the 3.2 user portal and see if they can get it to work.

`*/5 * * * * root sh /var/www/mysite/public_html/cron/vtigercron.sh
*/5 * * * * root >/var/www/mysite/public_html/cache/logs/cron.log`

Now I have the issue where crontab only runs 1 time, then it never runs again.

Don't get it.

Frustrating.

**Comment by kpaulaha** [comment]
Creating/sending login data do not need cron. You can test it by adding a task e.g. notification to that workflow and edit contact.

**Comment by slater101** [comment]
@kpaulaha 

Im aware,
But cron just ended up being one of my many issues during this journey to solving my issue with the portal. So I got sidetracked,

To end the story, I got it to send login credentials one time by changing the path to my php executable file, but when I did that, it broke everything.

Taking a break for a while lol, but I will be back and find out why its not working for me.

When I do, Ill share it here and hopefully one day someone that has the same issue will google it and get resolved.

Regards,
Kyle

**Comment by ldgbc** [comment]
@slater101 Hi Slater, how is your journey? I'm trying to play with Yetiforce and eventually founded your issue here. You seem to share quite a lot of similarity with my issue and @PercyP. Perhaps we can learn from each other somehow.

You say that you want "newest stuff first". Just wanted to know if you test out the Developer version? Are you able to get it to work with default setting (Apache httpd.conf in particular)
