### ISSUE TITLE
Wordpress API

### ISSUE THREAD

**Issue by immhub** [YetiForceCompany/YetiForceCRM#3816]
Hello,

I have a real estate website, on wordpress with wpresidence themplate (and plugins), and i want to bring the data from the website (properties, agents) to the Yetiforce CRM.
How can i do this? Can anyone help?

**Comment by speakerua1** [comment]
By hands

**Comment by immhub** [comment]
Very smart :)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
it should be performed by us or any other developer. There are a few built-in APIs in the system and they are available here: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/api. Unfortunately, we don't have any documentation for that but a professional developer will handle that.
