### ISSUE TITLE
Unable to edit permissions for profile

### ISSUE THREAD

**Issue by USTMarketing** [YetiForceCompany/YetiForceCRM#3818]
Hello! I've been using Yetiforce for a while now and I can say it really helped my entire team organize their tasks and daily activities better and for that I would like to thank you for making Yetiforce free and easy to use. 

#### Issue
However I recently came across an issue that has no possible explanation on why it wouldn't work, so I was hoping you could shed some light on this. I'm trying to change permissions for one of my profiles, more specific I would like to enable Chat for the "Recruiter" profile, but whenever I save the changes it just wouldn't work, it takes me back, but nothing changes. I tried other modules, some of them work, some of them don't. It should be noted that this issue only appears on this one profile. I have attached a screenshot to explain better what my issue is. Creating a new Profile doesn't work either, it just sticks to the same permissions as before. 

#### Actual Behavior
Refuses to work.

#### Expected Behavior
I want to be able to edit permissions once again as I really need some of those modules up and running for that group of people.

#### How to trigger the error
Simply trying to edit the permissions does it. It won't work no matter what I try.  Screenshot attached.

 ![chatenable](https://cloud.githubusercontent.com/assets/23361655/21227698/b8db0f96-c2e3-11e6-89c4-0a72ed08f0d9.png)

#### Your Environment
* YetiForce Version used: 3.20

* Browser name and version: Any (Currently on Google Chrome) 
* Environment name and version: PHP 5.6
* Operating System and version: Any (Currently on Windows 8.1)

Thank you in advance and keep up the good work!

**Comment by KatarzynaUlichnowska** [comment]
Hello,
please first read this [article](https://yetiforce.com/en/github/issues/126-issues.html) which explains how to report issues properly, so it becomes easier for us to help you. As the second thing we recommend increasing the following parameter in PHP: max_input_vars.

**Comment by manwenick** [comment]
Hello Katarzyna, 
unfortunatelly is the article wich explains how to report issues lands on 404 page. 
Can you please provide current version of this.
Thank you!

**Comment by bpabiszczak** [comment]
http://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs
