### ISSUE TITLE
Installation Stuck on (users page)

### ISSUE THREAD

**Issue by aramxalil** [YetiForceCompany/YetiForceCRM#3819]
Dears 
Greeting 

I have a strange problem with installation yetiforce CRM, installing on (WAMP SERVER V 3.0.4 On win 8 and WIN SERVER 2008 R2 ) at the first every thing goes fine till the the installation wizard , it stuck in middle process and the it shows me white page with no title and no notification , I also tryied
![3](https://cloud.githubusercontent.com/assets/24459816/21235659/c358941e-c308-11e6-92d1-763ebbef07cf.JPG)

1-I Customized My PHP setting as Yetiforce CRM requirement 
2-Changed the sql mode to > USER MODE
3-DB engine is Innodb

for more info please check attached problem screen shot
...Thank For Your Help ...

![1](https://cloud.githubusercontent.com/assets/24459816/21235415/b1f0bf54-c307-11e6-9621-c033d0db57c4.jpg)
![2](https://cloud.githubusercontent.com/assets/24459816/21235416/b1f41bd6-c307-11e6-98dc-2a8399f57285.JPG)
![3](https://cloud.githubusercontent.com/assets/24459816/21235662/c580c450-c308-11e6-99e7-3e1bf78bc4a9.JPG)

**Comment by SkavenKF** [comment]
Look at my [comment](https://github.com/YetiForceCompany/YetiForceCRM/issues/3767#issuecomment-260971558) to #3767

**Comment by aramxalil** [comment]
Thank you @SkavenKF  your comment is helpful
