### ISSUE TITLE
What is the different between Calculations - Quotes - Pricebooks?  

### ISSUE THREAD

**Issue by KarenNL** [YetiForceCompany/YetiForceCRM#3824]
Hi, 

I can't understand what the different is between calculations, quotes and pricebooks. Can someone explain it to me? 

Regards, 
Karen

**Comment by skramanzia** [comment]
Hi @KarenNL please check this Official Link.

https://yetiforce.com/en/user-documentation/sales-process.html

**Comment by KarenNL** [comment]
Thank you! 
Can I delete some processes? I have a small company, I need this structure
1 Lead
2 Account 
3 Quote 
4 Invoice
5 Client

**Comment by skramanzia** [comment]
Yes sure!.. disable modules and check the "mandatory fields" requirements in enabled modules.

**Comment by KarenNL** [comment]
Thank you. How can I add here (Accounts) Quote link
<img width="657" alt="schermafbeelding 2016-12-19 om 14 35 31" src="https://cloud.githubusercontent.com/assets/24546765/21314659/8318c4c6-c5f8-11e6-86ac-a91fd138e6fa.png">

**Comment by skramanzia** [comment]
You can use module relation or Mapping. I recommend the last.

 It`s good idea for you install a dev environment to try all functions and tools that  Yetiforce Include.

**Comment by KarenNL** [comment]
What is dev environment?
I have  [ver. 3.4.0]. Is this the last version?

**Comment by skramanzia** [comment]
@KarenNL Dev environment for you to try all functions and tools in "NO production" environment.

And remember one issue one ticket. @bpabiszczak and team is responsible for moderating orders, if they do not meet the requirements will be closed.

**Comment by KarenNL** [comment]
I understand. Thank you! I am translating Yetiforce to Dutch. When I finish, I will send it to Yetiforce as a support :).
