### ISSUE TITLE
Which files add the email binding in Roundcube?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3825]
Hi,

I wonder if anyone would know the answer to this. 

I want to use a different commercial roundcube skin in my yetiforce. I have installed it, but it doesn't display the email binding to Contacts, Leads, Projects etc. In a very early version of yetiforce I am sure I was able to display this, so not sure what has changed. 

Is there an extra setting or file I need to change so this is displayed in my new skin?

**Comment by paula-w** [comment]
For each skin you should add bar support and display. It doesn’t work automatically.

**Comment by PercyP** [comment]
Hi Paula,

is this a big job? Can I ask how much would support cost to add these?

**Comment by bpabiszczak** [comment]
4-8h * 30 euro.

**Comment by PercyP** [comment]
Hi, 

how would I progress from here? What would you need from me in terms of files? A copy of the entire skin folder?

**Comment by PercyP** [comment]
Would you be willing to share with the skin developers how they can make their templates compatible with yetiforce/roundcube integrations? They are keen to do this and surely the more developers build in terms of extensions and plugins for yetiforce, the more of a draw it becomes to others to move to your system?

**Comment by paula-w** [comment]
In order for us to start you’d first have to purchase 8h of support [eg. 2X [silver package](https://shop.yetiforce.com/en/support/8-silver-package.html)], then we’ll ask you to send us the template, and we’ll add a panel to integrate with YetiForce.  Using this, you and the developer will be able to see how to add the panel in different templates.

**Comment by PercyP** [comment]
Hi Paula,

I just tried to purchase but I cannot get beyond the address details as it doesn't like UK addresses/postcode. Can I send payment straight from Paypal and bypass this or do I have to do it via your order process?

**Comment by bpabiszczak** [comment]
paypal@yetiforce.com

**Comment by PercyP** [comment]
Hi @bpabiszczak 

I have sent the payment, however I did not have the option to add comments or a reference. Can you tell me if you have received it? Paypal ref is: Unique Transaction ID 9GB93007X10832745. Can you advise what I do next i.e. where to submit my files?

**Comment by paula-w** [comment]
Mail us directly at SLA@yetiforce.com, you can also send the zipped files there.

**Comment by PercyP** [comment]
Hi paula,

I have sent details. Please let me know if you don't receive them.

**Comment by paula-w** [comment]
I got them, thanks. I'll send you an email in a couple of minutes.

**Comment by PercyP** [comment]
Hi Paula, will I still be getting the customisation today?

**Comment by paula-w** [comment]
Hi, I just sent all the files via email.
