### ISSUE TITLE
Update Yetiforce stable version to dev version

### ISSUE THREAD

**Issue by KarenNL** [YetiForceCompany/YetiForceCRM#3826]
Hi, 
How can I update Yetiforce dev version from the stable version? 

Regards,
Karen

**Comment by bpabiszczak** [comment]
1. https://yetiforce.com/en/implementer/installation-updates/176-system-update.html
2. https://yetiforce.com/en/implementer/installation-updates/138-yetiforce-number-system.html 
3. https://github.com/YetiForceCompany/UpdatePackages
