### ISSUE TITLE
[ENHANCEMENT] list view usability

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3827]
some of my impressions to improve the list view usability:

- Remove the links on words and add a button for the link to the related record so when you click at any point of the line it opens the record summary view (now sometimes it happens to be inside a related record unintentionally).
- Add multiple selection of records by holding down the shift key.

![aggiunta boottone](https://cloud.githubusercontent.com/assets/18703633/21346053/f2c6e1b8-c6a2-11e6-9f82-d32854b0cfed.png)

**Comment by KatarzynaUlichnowska** [comment]
Hello,
if you would like us to add these functions to the system, you can order them.

**Comment by nic86** [comment]
> Remove the links on words and add a button for the link to the related record so when you click at any point of the line it opens the record summary view (now sometimes it happens to be inside a related record unintentionally


for anyone who is interested in adding this change:

change [at line 89](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Vtiger/uitypes/Reference.php#L89) in file modules/Vtiger/uitypes/Reference.php, with this two line:

```
$title=App\Language::translate($referenceModuleName, $referenceModuleName);
$linkValue ="<a class='btn btn-default btn-sm' role='button' href='index.php?module={$referenceModuleName}&view={$referenceModule->getDetailViewName()}&record={$value}' title='{$title}'><span class='glyphicon glyphicon-link' aria-hidden='true'></span></a>&nbsp;&nbsp;<span class='moduleColor_{$referenceModuleName}'>{$name}</span>";
```

**Comment by ezbank** [comment]
@nic86 I tried it but it does not work. can you help me .v4.3
