### ISSUE TITLE
[BUG] Wrong date format when export to Excel

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3829]
When Date format is dd/mm/yyyy
ver. 3.4.1207
...
![nh ch p man hinh 43 _li](https://cloud.githubusercontent.com/assets/19627226/21354743/d7d56644-c6fd-11e6-8480-93cb077b87b5.jpg)
![nh ch p man hinh 44 _li](https://cloud.githubusercontent.com/assets/19627226/21354797/049c481e-c6fe-11e6-8fae-61ccf0e24ea8.jpg)
![nh ch p man hinh 45 _li](https://cloud.githubusercontent.com/assets/19627226/21354835/247ee736-c6fe-11e6-826e-b9a12b062a32.jpg)

...

**Comment by paula-w** [comment]
In the current version the dates are correct, but the format is wrong. 
If you want the format to be correct you have to change it in excel.
