### ISSUE TITLE
[QUESTIONS] How to add new field to tooltipcontent

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3830]
how to add new field to tooltipcontent.
help me ^^!
![nh ch p man hinh 46](https://cloud.githubusercontent.com/assets/19627226/21356800/7dcb71d6-c705-11e6-9d4b-0a7b8df92dd7.png)

**Comment by rskrzypczak** [comment]
Add field to summary view.
![image](https://cloud.githubusercontent.com/assets/10221999/21367630/27538e66-c6ff-11e6-9576-78150d1de314.png)
![image](https://cloud.githubusercontent.com/assets/10221999/21367681/57c2e1be-c6ff-11e6-965f-ba3d979a2c86.png)
