### ISSUE TITLE
[bug] date format 

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3832]
#### Issue
Using date format dd.mm.yyyy 

![2016-12-21 10_13_05-invoices - detail](https://cloud.githubusercontent.com/assets/10330264/21382031/39768284-c767-11e6-986b-313202381300.png)

![2016-12-21 10_15_39-reports](https://cloud.githubusercontent.com/assets/10330264/21382000/0c31b550-c767-11e6-899f-55d37a8693fc.png)

#### Your Environment

* YetiForce Version used: 3.4.1212
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/21494006/b9c175f6-cc0e-11e6-8dfe-c85b81aeae10.png)
The error doesn't occur in the latest version
