### ISSUE TITLE
Issues showing documents in the tab of module

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3833]
Seasonal greetings everyone.

I've got an issue where the document tab is not showing attached documents the correct candidates. The module is a custom module but they are showing everywhere else. So I am a bit stumped on this.

There is a cron job running which is working fine but I cannot figure this out please see the screen gif below.

![problem](https://cloud.githubusercontent.com/assets/22075161/21386411/97df7b34-c76a-11e6-8e5d-23672d9a1f76.gif)

Expected Behaviour: So the documents when clicking on the document tab in the module.

![expected](https://cloud.githubusercontent.com/assets/22075161/21386447/c13dbed2-c76a-11e6-8319-decac12f8deb.gif)

I have tried this on both windows and mac, on the following browsers, Chrome, Safari, Edge, IE 11, Firefox and opera. All still having the same effect.

**Comment by nic86** [comment]
go to: Software configuration > Standard modules > Modules – Relations > Start

click on button "Add Relation" (to activate this button, you need to edit value of CHANGE_RELATIONS in the file config/developer.php)

set this parameters:
Relation type: Attachment
Action: select,add
Source module: your cutom module
Target module: Documents
Label: your cutom label

**Comment by alextovey** [comment]
No still not showing.

**Comment by nic86** [comment]
test with new module

**Comment by bpabiszczak** [comment]
Please check latest version.

**Comment by alextovey** [comment]
No, Still not working even with a new module!!!!!
