### ISSUE TITLE
index.php doesn't load unless it's typed at the end of the url

### ISSUE THREAD

**Issue by NginUS** [YetiForceCompany/YetiForceCRM#3834]
Installing as per the tutorial here:
https://www.rosehosting.com/blog/install-yetiforce-crm-on-ubuntu-16-04/

It says to enter the following in the Nginx server block:

```
    location / {
      try_files $uri $uri/ /index.php$is_args$args;
    }
```

-----

When I open the url without index.php at the end, I get a "403 Forbidden" error.

I expected to see the "Welcome to YetiForce CRM setup wizard" page load.

-----

I was able to resolve the issue by replacing the aforementioned code with the following:

```
	location / {
		index index.php index.html index.htm;
		try_files $uri $uri/ =404;
	}
```

-----

-YetiForce Version 3.4.0
-Chrome 55.0.2883.87 (64-bit)
-Ubuntu 16.04 LTS
--Installed with package presets checked:
---LAMP Server
---standard system utilities
---SSH Server
--Installed the following packages afterward:
---fail2ban iotop htop lshw ntp ufw ubuntu-drivers-common php php-fpm php-cli php-json php-curl php-imap php-gd php-mysql php-xml php-zip python-software-properties bind9 denyhosts libapache2-mod-security2 libapache2-modsecurity libapache2-mod-evasive libsasl2-modules git apparmor apparmor-profiles nginx
--All aptitude upgrades current

**Comment by skramanzia** [comment]
Hello @NginUS this is a NGINX configuration issue not Yetiforce. I am not recommend use tutorial to configure NGINX, if you dont have nginx skills please use apache or other webapp.

 However, check this:
- Use PHP version 5.6 not 7.X
- Check user and group nginx folder and Yetiforce Folder
- Check with a simple html or php file.
- In nginx you use php-fpm.

This is a crm.domain.com example.

```
server {
    server_name YOUR_URL_DOMAIN_ACCESS;
    access_log off;
    error_log /var/log/nginx/error.log;  #YOUR LOG FILE

    set $web_path /var/www/sites/yetiforce/crm.domain.com; #PATH TO WEB FILES

    location / {
        index index.php index.html index.htm;
        root $web_path;
    }

    location ~ .php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass  127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $web_path$fastcgi_script_name;
        fastcgi_read_timeout 600;
        proxy_send_timeout  600;
        proxy_read_timeout  600;
        proxy_connect_timeout    600;
        send_timeout    600;
    }
}
```
