### ISSUE TITLE
How Update to dev version?

### ISSUE THREAD

**Issue by KarenNL** [YetiForceCompany/YetiForceCRM#3835]
Hi,
I use Yetiforce 3.4.0 stable version. Can I update it to Dev version? If Yes, How chen I do that? I can't find any tutorial/documentation on the internet. 

Regards,
Karen

**Comment by skramanzia** [comment]
Hi @KarenNL the Dev version is not the final and its not stable yet. You need to wait to the new stable version to update. When release 3.5 finished you have to update with the "update packet"  created for that.

 Check Milestone to verify release due date
https://github.com/YetiForceCompany/YetiForceCRM/milestones

Update PKG link.
https://github.com/YetiForceCompany/UpdatePackages

**Comment by StaggerLeee** [comment]
Can someone put this info inside readme.md ?

**Comment by bpabiszczak** [comment]
Done.
