### ISSUE TITLE
apache security modul detect CSRF attack

### ISSUE THREAD

**Issue by forreggbor** [YetiForceCompany/YetiForceCRM#3836]
#### Issue
If I enable security modul in apache it detects CSRF attack.

#### Actual Behavior
I see this in the log files:
ModSecurity: Warning. Match of "eq 1" against "&ARGS:CSRF_TOKEN" required. [file "/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_43_csrf_protection.conf"] [line "31"] [id "981143"] [msg "CSRF Attack Detected - Missing CSRF Token."]

#### Expected Behavior
Shouldn't filter out as attack.

**Comment by bpabiszczak** [comment]
Is this a YetiForce problem? If i understood it right – the error message is related to Apache, not YetiForce, so you should change the Apache configuration, not ours. As far as I remember, the Secure flag doesn’t work properly with our system, we will take care of it in the next few weeks.

**Comment by forreggbor** [comment]
I use Apache's libsecurity CSRF protection modul (with default settings) which is globally used on every server. So it is not a customized settings but a generally used protection against cross-site request forgery attack.

**Comment by bpabiszczak** [comment]
Right now we support CRSF protection that’s built-in in YetiForce, it’s enabled by default and works properly in our opinion.
