### ISSUE TITLE
Unable to use YetiForce CRM via internet

### ISSUE THREAD

**Issue by aramxalil** [YetiForceCompany/YetiForceCRM#3839]
Dear Yetiforce Support Team 
Greetings 

I  Installed Yeti force CRM v:3.4.0 on windows server 2008,and capable to use it from local network with no problem but I can't use CRM from the internet.
I also configured the port forwarding and every network requirement for that propose    

* YetiForce Version used: 3.4.0
* Browser name and version: google chrome V: 52.0.0.11657
* Environment name and version: wamp server 3.0.4
* Operating System and version: windows server 2008 R2 Enterprice

to further information please check screen shot 
kindly please check attached file
1- attached photo shows when i entered my public IP
![c81098f2-c935-11e6-94f7-ff085d92d62d](https://cloud.githubusercontent.com/assets/24459816/21470910/6c405142-caad-11e6-90ba-51c587d45275.JPG)
![c2c977b0-c935-11e6-8c94-925abed089eb](https://cloud.githubusercontent.com/assets/24459816/21470911/71a8fd14-caad-11e6-96cd-243d03f85934.JPG)

 with assigned port
2-attached photo shows when i click on the yetiforce project

**Comment by skramanzia** [comment]
Hi @aramxalil do you use Yetiforce with port 80 in local network and port 5000 with NAT to internet forward?  

First try to FWD to port 80 to internet (Default Port). What we can observe is a WAMP server configuration error.

Yetiforce Team not recommend using the WAMP server or Windows for productive environments.

https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by paula-w** [comment]
The problem is not related to YetiForce, it’s related to ports configuration on the server and on the router. Try to google it.
