### ISSUE TITLE
Why don't you release various modifications as an extensions and sell them out?

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#3840]
waran70 commented 16 hours ago
Paula,

What if your client wish to remove invoice module? Will you cut it out?
Just for your reference - making OS system depended on your clients, and
speaking it out to open source community, discouraging serious developers
to  contribute to the source. Why don't you release various modifications
as an extensions and sell them out? Sell to your clients and all others.
Manage core to be stable, and keep in one shape.
Rest stuff separate, so we all know where we going to. I know that was
mentioned here several times, but as this is logical and wise (what I am
saying) I get it
here again.

**Comment by basanthagarwal** [comment]
Your team is doing really great work. 
I appreciate your skills and spirit. 
For any commercials, please let me know .. i'm ready to purchase on customised basis.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/3772
