### ISSUE TITLE
Adding Filter Widget

### ISSUE THREAD

**Issue by popothemes** [YetiForceCompany/YetiForceCRM#3841]
#### Issue
Now able to create filter and selection from Widget Filter

#### Expected Behavior
It Should allowed to select filter

#### How to trigger the error
1.  Add Widget Filter Form and Selecting Module and selection of Filter
Please Refer Screen Shot
<img width="617" alt="screen shot 2016-12-26 at 7 49 12 pm" src="https://cloud.githubusercontent.com/assets/22867569/21483264/36680756-cba5-11e6-83d9-cadae8298034.png">

#### Your Environment

* YetiForce Version used: [ver. 3.4.1264]
* Browser name and version: Safari 10.0.2
* Environment name and version: Centos 7.0
* Operating System and version: Mac OS Sierra 10.12.2

**Comment by SkavenKF** [comment]
![pic1](https://cloud.githubusercontent.com/assets/10259801/21485731/abc5ce78-cba7-11e6-9e1d-da3bf2ec7cab.JPG)
![pic2](https://cloud.githubusercontent.com/assets/10259801/21485732/adeca9d8-cba7-11e6-9f89-c9becfe3df49.JPG)

**Comment by popothemes** [comment]
Solved Thank you
