### ISSUE TITLE
[QUESTION][3.4.0] How to edit the "RelatedList" view of a custom module

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3842]
Good morning, 

I had a question, how can I edit the RelatedList view of a created module?
I currently do it from "layouts/basic/modules/Vtiger/RelatedList.tpl" using "{if {$RELATED_MODULE->get('name') == 'NewModule' && $MODULE == 'Contacts'}}" to load in the module that i want but it is the generic file, my question is, is there any way to attach the "RelatedList" file inside the module that I want to customize?

![chrome_2016-12-27_09-38-08](https://cloud.githubusercontent.com/assets/18419851/21496745/97b14824-cc18-11e6-812b-1dc786f781b7.png)

Thank you very much and greetings

**Comment by mariuszkrzaczkowski** [comment]
Here's an example:
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Calendar/views/InRelation.php
