### ISSUE TITLE
[BUG] Recording Control - disappeared the modal content to set value

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3845]
ver. 3.4.1273

![animation](https://cloud.githubusercontent.com/assets/19627226/21504616/0c5830aa-cc93-11e6-9839-0b06d9c78628.gif)

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/github/issues/205-why-was-the-issue-ignored.html
https://yetiforce.com/en/github/issues/206-system-development-ideas.html
