### ISSUE TITLE
[BUG][3.4.1296] Systemsettings ->System tools -> Testdata -> Fatal error

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3851]
#### Issue

I become a Fatal error, when i select Systemsettings ->System tools -> Testdata

#### Actual Behavior

become fatal error
#### Expected Behavior

no fatal error

#### How to trigger the error

![bug1](https://cloud.githubusercontent.com/assets/10259801/21547110/40eacf74-cde4-11e6-94ec-56bcf80f1428.gif)

#### Your Environment

* YetiForce Version used: 3.4.1296
* Browser name and version: chrome, firefox
* Environment name and version: gitdeveloper
* Operating System and version: windows 10

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/1fcd3200cc1750b522e6bf6d3e7be6dd1a042053
