### ISSUE TITLE
[BUG][3.4.1299][ModuleManager] Parse error to create a module with the name "New"

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3857]
#### Issue

https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=LayoutEditor&sourceModule=New

#### How to trigger the error

1.
![parse_error_module_1](https://cloud.githubusercontent.com/assets/18419851/21555840/ae3e6142-ce13-11e6-98d2-e7033747ffe2.PNG)

2.
![parse_error_module_2](https://cloud.githubusercontent.com/assets/18419851/21555841/b0eaa07c-ce13-11e6-9b26-21009a7ff322.PNG)

3.
![parse_error_module_3](https://cloud.githubusercontent.com/assets/18419851/21555842/b32b4ac6-ce13-11e6-8a82-a7c10f8be290.PNG)

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
You can’t create a module with a name that is a reserved keyword in PHP.
We will secure that in the future by adding appropriate validation.
The list of reserved words can be found here: https://secure.php.net/manual/en/reserved.keywords.php
