### ISSUE TITLE
Stock Valuation

### ISSUE THREAD

**Issue by YESMUN** [YetiForceCompany/YetiForceCRM#3860]
Hi

I am trying to find where to get the value of all the stock / products you have in your inventory.
I have managed to generate reports that will show you a product listing but not the value of all the stock you have.

Ideally I would like this to be a widget that I can place on the home screen so when I log in I can see the value of stock on hand right away.

Is there a way to do this?

Thank you for your help.

**Comment by WalterLuis** [comment]
Hello,

![widgets](https://cloud.githubusercontent.com/assets/18419851/21562203/dd5afa66-ce6e-11e6-8120-a77f7fc6da62.PNG)

![widgets_2](https://cloud.githubusercontent.com/assets/18419851/21562206/e66420d8-ce6e-11e6-90d7-5dfabd103340.PNG)

![widgets_3](https://cloud.githubusercontent.com/assets/18419851/21562209/ebd35ab6-ce6e-11e6-8614-81baa9cfa58c.PNG)

**Comment by YESMUN** [comment]
Hi Walter

Thank you for that information.

I have tried creating a filter and adding it to the key metrics but then it just tells me how many products I have in stock and not the total value of those products:

![image](https://cloud.githubusercontent.com/assets/24837231/21562934/7fd440ca-ce85-11e6-9afe-dccd4df04e12.png)

![image](https://cloud.githubusercontent.com/assets/24837231/21563003/10dff47e-ce86-11e6-9d10-8e12d36b761d.png)


I Have also managed to create a widget that will give me the product name, unit price and quantity in stock, but what I'm after is for one of the widgets, either in the Key Metrics, or the product widget to tell me the total value.
Two values I'v manage to get is the total products in stock (69), the total amount of units there are in stock (715) and then the total value if there were only 1 of each product in stock (I did this in the reports), but I cant find anywhere where it will say, you have 10 x $15 of product a so that value is $150, and then do that for all the products and say the total value of all products in stock is $xx.

Ideally I would like it to be a widget on the home page, but even if I can create it in the reports or anywhere else that would work to.

Currently I have to export the product list into excel and add in a column that just multiplies the unit cost by the quantity and then sum it in order to get the stock value.

Please let me know if anything is unclear.

**Comment by WalterLuis** [comment]
Hi again :D

Try using the "Reports" module, you will not have it on the main page but it is saved and you can access it and extract it in excel

**Comment by kpaulaha** [comment]
Adding value in stock / product in widget can be done by adding a custom field in product and having workflow to calculate quantity x price. Then using this in widget. Of course total quantity of whole stock is not calculated.

**Comment by WalterLuis** [comment]
Can be another option, but you have to keep in mind that to do a workflow you need to be an advanced user and if you do not know how to do it but you know PHP you can look for information, although if you are in a hurry or you can not think of how to do it you can always contract a YetiForce service and you make sure that you do well and as you want.
https://shop.yetiforce.com/en/17-support

**Comment by kpaulaha** [comment]
Well, 3 steps in Workflow plus widget, 10 min. Not so difficult.
![vid](https://cloud.githubusercontent.com/assets/10330264/21564321/ee1842d4-ce94-11e6-9827-4b466d0c39ef.png)

**Comment by gerstavros** [comment]
Hello. How to add stock counted using barcode scanner?
