### ISSUE TITLE
PDF Invoice problem

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3869]
#### Issue
Can't upload exsisting xml invoice to the system or cant create new invoice just have "Loading, Please Wait"
Or blank screen for upload exsisting

#### Actual Behavior

I just seem to be getting the above no matter how i try. Cron Jobs is enabled also.

#### Expected Behavior
To create invoice without "loading, please wait" constantly showing or upload an invoice without a blank screen.

#### How to trigger the error
[createinvoice](https://cloud.githubusercontent.com/assets/22075161/21605389/e7486330-d1a0-11e6-949c-de663dd049b1.gif)

#### Your Environment
 YetiForce Version used: 3.4.0
Browser name and version: Chrome, FF, Opera, IE 11, Edge
Environment name and version: Cpanel using Cloub Linux with php 5.6
Operating System and version: Windows 7 64bit,

**Comment by konadrian** [comment]
In case of creating a new PDF, can you trigger the error at http://gitdeveloper.yetiforce.com/, I keep trying to recreate the error in the current version and in 3.4, and the PDF saves properly.
