### ISSUE TITLE
Time control displays blank page

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#3870]
#### Issue

Time Control displays a blank page on helpDesk module

#### Actual Behavior

![time control](https://cloud.githubusercontent.com/assets/5912376/21636747/7c787398-d26c-11e6-8fff-cd9f0065f1f7.png)

#### Expected Behavior

Display Time records

#### How to trigger the error

1.Click on Support
2.Navigate to Time Control tab or try to change the status of a ticket

#### Your Environment

* YetiForce Version used: ver. 3.4.237
* Browser name and version: Chrome
* Environment name and version: Linux
* Operating System and version: Ubuntu 16

**Comment by konadrian** [comment]
The error doesn't occur in the latest version
