### ISSUE TITLE
Cutting off Job titles

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3871]
Morning all, I'm using 3.4.0 but something strange is happening to the records i've input. They are showing only as 15 charters and cutting the rest off.
see screen shot.

The database is showing 50 charters but its only doing 15? any ideas where I can possibly change this?

![jobtitle](https://cloud.githubusercontent.com/assets/22075161/21677085/76a17f04-d330-11e6-8386-2e2f993c1feb.gif)

**Comment by WalterLuis** [comment]
Hi,
I understand it's a custom module, right?
I created a new module, I created a field with a length of 50 characters and I can see it well in version 3.4.0
![jobtitle](https://cloud.githubusercontent.com/assets/18419851/21680973/c1f4ff8a-d344-11e6-83d5-
4801ffeeda6a.PNG)
