### ISSUE TITLE
Roundcube no chance to change defaults

### ISSUE THREAD

**Issue by weidamar** [YetiForceCompany/YetiForceCRM#3872]
Hello,

I have problem to set up EMail.
Understanding to create first roundcube default (gmail) to my own serverconfiguration.

I have edited and saved new configuration.
After refreshing roundcubeconfiguration I get the old configuration of gmail default.

Please help me.

Thank you
Markus Weidauer

**Comment by ldgbc** [comment]
You probably have to install the hotfix patch update. Please see: https://github.com/YetiForceCompany/YetiForceCRM/issues/3649
https://github.com/YetiForceCompany/YetiForceCRM/issues/3653

For reference.

**Comment by mariuszkrzaczkowski** [comment]
Test the latest version
