### ISSUE TITLE
[BUG][3.4.1374][AJAXChat] Chat does not appear when button is pressed

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3873]
#### How to trigger the error

1.
![chat_error](https://cloud.githubusercontent.com/assets/18419851/21679864/2941eccc-d33e-11e6-8993-8d84a0ac0c29.PNG)

#### Your Environment

* YetiForce Version used: 3.4.1374
* Browser name and version: Chrome 55 
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: gitdeveloper.yetiforce.com

**Comment by ahmido** [comment]
hi which php version do you use?
cheers

**Comment by aramxalil** [comment]
Hello There I have same problem :( 
My php Version is 7.1.0  and my yetiforce version is 3.4 , beffore upgrade to 3.4  the Chat was working on version 3.4.0 stable version

**Comment by bpabiszczak** [comment]
You should use PHP 5.6. Please read this: https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by WalterLuis** [comment]
Hi,
I only tried it from the page: "gitdeveloper.yetiforce.com", now I tried it on the version [ver. 3.4.1524] with PHP ver. 5.6 and works without problems, actually, in "gitdeveloper.yetiforce.com" using PHP ver. 7.1 does not load the chat, showing only the border:

![onlyborder](https://cloud.githubusercontent.com/assets/18419851/22067544/a0d9a644-dd89-11e6-98f7-f22e0b6be257.PNG)

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/lib_AJAXChat/commit/6ddf716eba5d625fe76d445465a4c64a7982403f
