### ISSUE TITLE
error 403 when trying to add new Account from MyMailBox

### ISSUE THREAD

**Issue by clauswz** [YetiForceCompany/YetiForceCRM#3874]
#### Issue

Hello,
When I try from an email in My Mailbox to Add a Account, the 403 Forbidden message is shown. I believe is a permission problem, but I have checked and al files and folders seem to have the right permissions. I'm new to YetiForce, maybe you could suggest a more specific check.

#### How to trigger the error

1.receive an email from somewhone who is not a Contact or Account
2.Try to use the Relate to existing record button
3.

#### Your Environment

* YetiForce Version used:3.4
* Browser name and version:Chrome
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by clauswz** [comment]
The problem was solved yesterday by the Shared Host Admin, explaining that it was a security plugin that was blocking something.

**Comment by crpak** [comment]
I have met the same problem. How does your host admin do for this issue?
