### ISSUE TITLE
Menu issue on iPad [Partially Solved]

### ISSUE THREAD

**Issue by easaw** [YetiForceCompany/YetiForceCRM#3875]
#### Issue
Menu doesn't appear, may be due to z-index. Menu should also fold down to mobile menu in portrait mode because of responsive web design, but stays at full size. Appears to detect lower than  #767px.

#### Actual Behavior
When selecting a menu item from the left vertical menu, no actual menu appears

#### Expected Behavior
Menu should appear from the left so sub-menu items can be selected.

#### How to trigger the error
1. Log into a YF account on an iPad
2. press an item on the left menu

#### Your Environment
* YetiForce Version used: 3.4
* Browser name and version: Safari iPad (iOS7), Chrome iPad 39.0.2171.50
* Operating System and version: iOS 7.1.2 (Jailbroken, Cydia installed)
*Screen: 1024x768 (landscape), 768x1024 (Portrait)

**Possible solution:**

Change CSS Media Query to detect iPad and use mobile menu, rather than detect width as iPad 2 needs the mobile menu.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/4615
