### ISSUE TITLE
[BUG] Web Install Issue with Purifier.php when installing after Language selection.

### ISSUE THREAD

**Issue by easaw** [YetiForceCompany/YetiForceCRM#3878]
#### Issue
Parse error: syntax error, unexpected '.', expecting ',' or ';' in vendor/yetiforce/Purifier.php on line 16

#### Actual Behavior
After selecting the language (only tested English), this error pops up 

> Parse error: syntax error, unexpected '.', expecting ',' or ';' in /vendor/yetiforce/Purifier.php on line 16

These are the lines of code causing the issues:

`private static $htmlEventAttributes = 'onerror|onblur|onchange|oncontextmenu|onfocus|oninput|oninvalid|onreset|onsearch|onselect|onsubmit|onkeydown|onkeypress|onkeyup|' .
'onclick|ondblclick|ondrag|ondragend|ondragenter|ondragleave|ondragover|ondragstart|ondrop|onmousedown|onmousemove|onmouseout|onmouseover|' .
'onmouseup|onmousewheel|onscroll|onwheel|oncopy|oncut|onpaste';`

#### Expected Behavior
Expect to go to next level of web install

#### How to trigger the error
1. unpackage YetiForce 3.4 Master or Developer
2. Ensure PHP 5.5 or above is running
3. Go to relevant domain and run install.php
4. Select Language

#### Install Environment
* YetiForce Version used: 3.4 (Master & Developer)
* Environment name and version: Shared Hosting, PHP 5.5.38
* Operating System and version:  CentOS

#### My Environment
* Browser name and version: Chrome 55.0.2883.95 (64-bit)
* Operating System OS X 10.10

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3690
