### ISSUE TITLE
[BUG] Values from the related module

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3881]
ver. 3.4.1387

![animation](https://cloud.githubusercontent.com/assets/19627226/21705978/0907a290-d3f6-11e6-9189-e2d3d6feaab6.gif)

**Comment by ezbank** [comment]
it still exists
 ver. 3.4.1397
![nh ch p man hinh 57](https://cloud.githubusercontent.com/assets/19627226/21767491/17d1c45a-d6a7-11e6-871e-54de074168f1.png)

**Comment by ezbank** [comment]
what about update?

**Comment by ezbank** [comment]
what about update?
it still exists ver. 4.0

**Comment by mariuszkrzaczkowski** [comment]
Check changes
https://github.com/YetiForceCompany/YetiForceCRM/commit/bdb2d9a200a7d685835679c6e59130f4e7d60af2
https://github.com/YetiForceCompany/YetiForceCRM/commit/ed558e8c4b48ec87fb6ecc28a7287ea810a1733c

**Comment by ezbank** [comment]
I tried it but it does not work
v 4.0.98
![112](https://cloud.githubusercontent.com/assets/19627226/23829147/98372c76-071b-11e7-9efd-b4a55218edfd.gif)

**Comment by ezbank** [comment]
it still exists

**Comment by nic86** [comment]
the field "Values from the related module" is auto update from cron "Multireference fields update" and is  only displayable from list view from a custom filter.
