### ISSUE TITLE
Workflow (Assigned to: & Share with users:)

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#3882]
When creating a new workflow
when selecting field "Assigned To" I see the users and groups users and several conditions but if I selected field "Share with users" I see only users and one condition "None". Why?

![error_shareforusers](https://cloud.githubusercontent.com/assets/17310158/21714342/25243ebe-d407-11e6-860d-7a3f65d8a378.gif)

**Comment by KatarzynaUlichnowska** [comment]
Hello,
thank you for that. It wasn't added when this field was created, so one of our devs will fix that.

**Comment by TomaszQr** [comment]
Plese check if it's working properly

**Comment by WalterLuis** [comment]
It seems to work well :D

![chrome_2017-01-12_15-12-09](https://cloud.githubusercontent.com/assets/18419851/21895264/f43bee14-d8d9-11e6-8c97-64e6562517db.png)
