### ISSUE TITLE
Fixing system requirement on web hosting 

### ISSUE THREAD

**Issue by aramxalil** [YetiForceCompany/YetiForceCRM#3883]
Dear Yetiforce CRM Team 
Greeting 

Please guide me how to fix (Server Configuration) on web hosting service. I installed The system Via softaculous auto installer
 
![capture1](https://cloud.githubusercontent.com/assets/24459816/21733053/9f0466e4-d46d-11e6-8550-a32da332c18e.JPG)

**Comment by waran70** [comment]
What yetiforce got to do with your hosting provider?

**Comment by aramxalil** [comment]
@waran70  I use  Siteground.com as a web hosting service

**Comment by vovpff** [comment]
@aramxalil this parameters can be changed in php.ini file if you have access to this fike
