### ISSUE TITLE
Roundcube installation fails

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3884]
Downloading/updating Roundcube -library not working
![rc](https://cloud.githubusercontent.com/assets/10330264/21748732/07dfca0a-d595-11e6-8c68-c61c45c9b1a1.png)

log says: 
[08-Jan-2017 11:17:35 Europe/Helsinki] PHP Warning:  file_get_contents(https://github.com/YetiForceCompany/lib_roundcube/archive/0.0.15.zip): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found

#### Issue
Downloading/updating Roundcube

#### Your Environment

* YetiForce Version used: 3.4.1388
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
There's no published official stable version like this. Which means either you changed the version number in configuration yourself, or you downloaded the latest version from GitHub. 
0.0.15 is a dev version and requires the crm to be set to developer mode, which is why it doesn't work for you.

**Comment by kpaulaha** [comment]
Ok, clear, thanks.

**Comment by witer30** [comment]
@kpaulaha 
have you fix roundcube installation...?
thanks for help

**Comment by kpaulaha** [comment]
@witer30 better to wait for the stable 3.5 first.
