### ISSUE TITLE
[BUG] ver. 3.4.1389 Reminders Notice Container not display on iPad

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#3885]
#### Issue
Reminders Notice Container not display on iPad
#### Actual Behavior

![error 1](https://cloud.githubusercontent.com/assets/19627226/21761068/24c327c2-d683-11e6-9c06-f47f40e19978.gif)

#### Expected Behavior
![screenshot 21](https://cloud.githubusercontent.com/assets/19627226/21761044/0654069e-d683-11e6-981a-e7d15b41aa67.png)

ver. 3.4.1389

**Comment by konadrian** [comment]
Can you check it the window shows up correctly now?
