### ISSUE TITLE
[QUESTION] how create a custom module with something similar to inventory?

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3887]
#### Quetion
I edited "layouts/basic/modules/Vtiger/EditView.tpl" and the value of the database "vtiger_tab.type" to 2 for load another .tpl
my problem is when i create a new file with their respective "Class" in "modules/Vtiger/models/" called "Vtiger_IndicadoresField_Model", I load the edit view of the custom module with the custom tpl and I get the following error: "Fatal error: Class 'Vtiger_IndicadoresField_Model' not found in /var/www/html/cache/templates_c/basic/4...6_0.file.EditViewIndicadores.tpl.php on line 26"
How could I create a new class and detect the system?
For what I was looking at, I think this is the step to create what I need. Taking into account that I have to create something similar to what you have created for the inventory in "modules/Vtiger/inventoryfields/" and creating tables in the database "vtiger_objetivo_indicador", "vtiger_objetivo_indmap" and "vtiger_objetivo_indfield" related to the model I want it to look and to get a relationship with two modules N:N instead of 1:N

#### Expected Behavior

![resultado1](https://cloud.githubusercontent.com/assets/18419851/21762532/21fc3df8-d651-11e6-8cfb-395c5171620f.PNG)

**Comment by skramanzia** [comment]
Hi @WalterLuis Use "Module Manager".

![image](https://cloud.githubusercontent.com/assets/3030997/21767498/52a6deac-d653-11e6-89b9-cc287943fe52.png)

**Comment by KatarzynaUlichnowska** [comment]
Unfortunately, we cannot advice you for free on that because it is very complex and we don't have time for that. It is a very unusual relation. This problem requires some in-depth analyses and only afterwards it should be approached.

**Comment by WalterLuis** [comment]
Ok, no problem :D
