### ISSUE TITLE
[Question]: How can i see all Projects with "Target end date" in Future  

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3888]
Use case: The management would like to see all active or planned Projects with a target end date in the future as a filter.

Example:
![condition](https://cloud.githubusercontent.com/assets/10259801/21765316/5a9774fe-d668-11e6-952e-c055686203ce.JPG)

How can i do this?

**Comment by bpabiszczak** [comment]
You need a programmer.
