### ISSUE TITLE
Report Condition Error

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3889]
#### Issue

When create a Report (Ticket Module) and select a condition to "account Name" or "SLA" the field not display Accounts or SLA to create a Filter.

#### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/3030997/21767996/f25e0e3c-d655-11e6-942b-951edf92ebf0.png)

#### Expected Behavior

When type in field auto find accounts or SLA.

#### Your Environment

* YetiForce Version used: 3.4.1397
* Browser name and version: latest Chrome
* Environment name and version: Dev
* Operating System and version: Mac OSx

**Comment by skramanzia** [comment]
@TomaszQr still not working I tested in 3.4.1439

![image](https://cloud.githubusercontent.com/assets/3030997/21874543/45d65ae2-d854-11e6-83b6-1220c6749a34.png)

**Comment by paula-w** [comment]
If there’s a reference type field in conditions you have to enter the name. Eg. if the field refers to an Account then you have to enter the Account’s name, if it refers to Contacts then you have to enter the first and last name.

**Comment by skramanzia** [comment]
@TomaszQr @paula-w Check this.

![untitled](https://cloud.githubusercontent.com/assets/3030997/21932169/eea89192-d97d-11e6-9c11-77baeac1fd32.gif)

**Comment by TomaszQr** [comment]
Problem has been fixed
