### ISSUE TITLE
[QUESTION] Customer Portal Fields

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3890]
How to add Field in "Add Ticket" of Portal User. I created custom fields in Helpdesk module and need to see in Customer Portal when "add new ticket".

**Comment by mariuszkrzaczkowski** [comment]
You need to modify files portal
https://github.com/YetiForceCompany/YetiForcePortal/blob/developer/modules/HelpDesk/layouts/create.php#L32
https://github.com/YetiForceCompany/YetiForcePortal/blob/developer/modules/HelpDesk/index.php#L110

**Comment by skramanzia** [comment]
great!, thank @mariuszkrzaczkowski
