### ISSUE TITLE
User Change Password

### ISSUE THREAD

**Issue by johntonji** [YetiForceCompany/YetiForceCRM#3892]
Hello,
I need users to be able to change their own password and I am using 3.1 version. Any help?

**Comment by WalterLuis** [comment]
Hi, this is the file that you have to edit
https://github.com/YetiForceCompany/YetiForceCRM/blob/3.1.0/config/security.php

**Comment by johntonji** [comment]
Thanks for your prompt response, I can see that admin can change password, however user with sales role have the change password button but when I click nothing happens

**Comment by WalterLuis** [comment]
I can not help you there anymore. If you upgrade to 3.4.0, the password change option is working
