### ISSUE TITLE
[BUG] Roundcube library not install (v3.4.1410)

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#3894]
YetiForce Version used: 3.4.1410
Browser name and version: Google Chrome 55.0.2883.87 m
Environment name and version:
Operating System and version: Windows 10
![animation 1](https://cloud.githubusercontent.com/assets/1402355/21793068/ff0a69e0-d70f-11e6-8e8c-9b7a171e0838.gif)

**Comment by mariuszkrzaczkowski** [comment]
Duplicate #3884
