### ISSUE TITLE
[question] mail scanner and workflows - cron jobs

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#390]
Can someone advice how to start mailscaner and workflows on Ubuntu OS?
Which parameters of cron jobs are the best for CRM...

**Comment by bpabiszczak** [comment]
To enable CRON in YetiForce CRM it is enough to add sh file (to be triggered e.g. every 5 min) in CRON on the operating system. When this file is added https://github.com/YetiForceCompany/YetiForceCRM/blob/master/cron/vtigercron.sh to the CRON of the operating system it is neccesary to check a path in export USE_PHP parameter. If it's correct, CRON will work properly in the CRM system.
