### ISSUE TITLE
Micro level Filter - Drop down selection

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#3900]
Can we use create Drop Menu option in Modules - while retriveing records. 
#### Issue

As number of Records are increasing, to retrieve specific Record with specific Condition seems to be difficult even after using Filter Option. 

#### Actual Behavior

Maximum of 12 fields can be seen in filters, also - as Data size may varies from field to field ... not more than 5-6 fields are seen in monitor screen size available . 

However, creating filters as per  requirement is helpful option, but finding difficult to identify specific record. 

#### Expected Behavior

Can you give Picklist options in Modules on top (above filter names are seen) or may be drop down selection box option for few of fields to users to choose types of records he is looking for, to easy access.
In this way, with help of available filter options and Drop Down Selection, Micro Filter can be done, which will be user friendly for users. 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4 (with hotfix)
* Browser name and version: Chrome
* Environment name and version: Stable
* Operating System and version: Linux

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/github/issues/206-system-development-ideas.html
