### ISSUE TITLE
[Question] help needed: Software configuration > Mail tools > Mail – SMTP Server > Outgoing Server

### ISSUE THREAD

**Issue by ABaumruck** [YetiForceCompany/YetiForceCRM#3901]
Hello Everybody!
I'm currently running out of ideas. From my vServer I managed to run an imap mailbox through RoundCube (sending and receiving). But when I enter the same credentials into "Mail - SMTP Server settings" in YetiForce I always get this generic error message.

> Test mail status :  Mail could not be sent to the admin user. Please check the admin emailid/Server settings

I'm pretty sure RoundCube handles emails a little differentely than YetiForce, but as said before, I do not know where to start digging. It would be great If someone could point me into the right direction.

At the moment I think that I've missed to set up something in Ubuntu, but I'm unable to find it.

I've varied some of the SMTP setting below (e.g. "tls//", "port", "authentication", ... )  as well as user name with and without domain name attached ("crm1@myDomain.com" <-> "crm1") but without any success.
I've also successfully used this mailbox with the same settings locally on Thunderbird

Here are my current settings:

setting | RoundCube | Mail - SMPT Server
------------ | ------------- | -----------------
Name | my name | n.a.
Validate certificate |	no | n.a.
Add type and protocol to address	| yes | n.a
Name of IMAP server | tls://imap.myDomain.com | n.a
Port used to connect to IMAP	| 143
Name of SMTP server | tls://smtp.myDomain.com | tls://smtp.myDomain.com:587
Login to SMTP server ("%u" - login of logged in user) | crm1 | n.a.
user name | n.a. | crm1@myDomain.com
Password to SMTP server ("%p" - password of logged in user) | **** | ****
SMTP port (default 25; 465 for SSL; 587) | 587 | n.a.
Language (RFC 1766 code): en_US, pl_PL | de_DE | n.a.
Domain (automatically added to login) | myDomain.com | n.a.
Logo | /images/null.png | n.a.
Check IP address of client while giving authorization | no | n.a.
Spell check module | yes | n.a.
Level of access to identity | many identities with possibility of editing all parameters | n.a.
Lifetime of session in minutesOutgoing mail server | 10 min | n.a.
From Email | n.a. | crm1@myDomain.com
Requires authentication | n.a. | no (also tried yes)

THX in advance
BR Andreas

YetiForce Version used: 3.4.21 -> clean install
Browser name and version: Chrom V 53.0.2785.143
Environment name and version: vServer
Operating System and version: Ubuntu 16.04.1 LTS / PHP 5.6.29

**Comment by easaw** [comment]
Try 'Validate your certificate'

Worked for me, though i'm on SSL.

**Comment by mariuszkrzaczkowski** [comment]
Sending SMTP mails has been rebuilt, and PHPmailer has been updated to the latest version. Check if the mail works for you now (and logs), if you have a problem we can help you with the configuration with 1h support. https://gitdeveloper.yetiforce.com/index.php?module=MailSmtp&parent=Settings&view=List&block=8&fieldid=105
