### ISSUE TITLE
[BUG] [DEVELOPER BRANCH] Can't Log In At All

### ISSUE THREAD

**Issue by easaw** [YetiForceCompany/YetiForceCRM#3902]
#### Issue
Can't Login

**Please note: The Stable version (d0cb31c) does run on this same environment.**

#### Actual Behavior
Type in correct admin username & password, does not access YF.

#### Expected Behavior
Access the Homepage

#### How to trigger the error
1. Install Dev version (unpack zip in cPanel file viewer)
2. Run install.php
3. Add MySQL and other info
4. try to login

#### Your Environment

* YetiForce Version used: Developer 1f1afa5
* Browser name and version: Firefox 50.1.0, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
* Environment name and version: Apache, Zend Engine v3.1.0, PHP 5.6.29
* Operating System and version: CentOS (unknown)

More PHP/ Server Info on request

Notes: Tried various DBs, various passwords for Admin and Various versions of PHP (5.5 - 7.1).

**Comment by easaw** [comment]
Spreadsheet of tried Developer Commits [Google Sheets](https://docs.google.com/spreadsheets/d/1_WtL_1CTXMbCgnGy8289yCKiJB6AAYqLrUFOWSMdgz8/edit?usp=sharing)

**Comment by kpaulaha** [comment]
Installs fine on both win and debian. Check your server configuration.

**Comment by easaw** [comment]
@bpabiszczak @kpaulaha 
This is precisely my point. You can install it fine on WAMP or offline server settings that are 'perfect'.

But most people **aren't** going to have 'perfect' settings/ environments, I was installing via cPanel on Shared Hosting.

I spent about **4 Hours** trying to figure out the issue and why almost all of the developer releases won't install.

Most people with shared hosting **can't change the PHP settings** required to install YF. That is why I created the issue.

For more information, please see my Spreadsheet [here on google docs](https://docs.google.com/spreadsheets/d/1_WtL_1CTXMbCgnGy8289yCKiJB6AAYqLrUFOWSMdgz8/edit?usp=sharing).

**Comment by kpaulaha** [comment]
@easaw what is your point? To have a CRM that you can install on any hosted server with minimum requirements? I do not belive yf will ever be that and good so. On the other hand we have the dev version running on one CentOS and installed through Plesk Onyx with quite basic php conf possibilities, it complained a bit in the beginning, but up and running. That was only for testing to see how it works on hosted, we do not spend much time trying to install the dev version on other than our own servers, which are most online. 4 hours is not so much spending with such programs/problems.
What are your options, to ask your provider for more permissions to conf the php, choose an other hosting or buy the whole package as service. Sure people from yf or others will sell you such service. Must allways remember we are now talking about an open source product.
