### ISSUE TITLE
Questions and docs about taxes

### ISSUE THREAD

**Issue by decioschmitt** [YetiForceCompany/YetiForceCRM#3903]
Hello,

I liked to know if you have any document to config taxes to version 3.4 yetiforce, i had used the version 2.4 and upgrade to version 3.4. My Country is Brasil, do you can help with anywhere doc or tip about this?

Thanks for you time.

**Comment by decioschmitt** [comment]
Hello,

I liked to know if you have any document to config taxes to version 3.4 yetiforce, i had used the version 2.4 and  upgrade to version 3.4. My Country is Brasil, do you can help with anywhere doc or tip about this?

Thanks for you time.

**Comment by KatarzynaUlichnowska** [comment]
Unfortunately, we don't have any documentation about it and we don't know what kind of taxes you have in your country and how they work. If a customer orders a function, e.g. an invoice, we configure all necessary elements in the system - taxes, fields in modules, PDF templates.

If you would like us to prepare documents for you, we can tell you which support package would be required for that. If not, you need to learn YetiForce in depth and know how to solve the problems when they arise.

**Comment by decioschmitt** [comment]
Ok;

Thanks you for you time.
