### ISSUE TITLE
[Feature Request] Incremental Savings Tracking- Future Budget Target

### ISSUE THREAD

**Issue by NginUS** [YetiForceCompany/YetiForceCRM#3904]
I'd like to find a way to track savings to meet a target in the future. I don't see it in any financial management product anywhere. Would be nice to have in YetiForce.

eg.
I need $100.00 on June 1, 2017.
Today is January 1, 2017.
Target date is 21 weeks away.
I'd need to save $4.76 weekly.
If I miss setting aside the $4.76 one week, I'd need to save $5/week instead if I'm to meet the target.
Adjust as needed like GPS directions, if I save less or more some weeks.

**Comment by waran70** [comment]
Absolutely outstanding and very useful for everyone idea!!!!
This should be enough, but not really sure: https://shop.yetiforce.com/en/support/9-gold-package.html

**Comment by paula-w** [comment]
First of all - the feature would have to be very well described.
The question is who would pay for that. If nobody, then we can close the issue.

**Comment by NginUS** [comment]
Ok, glad to know a solution is possible, hopefully I'll be successful enough in my endeavours to be able to afford to have this implemented. Everyone wish me luck!

In the meantime, I'll be happy to close this.

Thanks!
-N
