### ISSUE TITLE
[BUG][3.4.1451][LangManagement] The default language does not appear in login page

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3905]
#### How to trigger the error

1.
![chrome_2017-01-12_12-31-36](https://cloud.githubusercontent.com/assets/18419851/21890087/ef84cbae-d8c3-11e6-8cc5-f76b6e332628.png)

2.
![chrome_2017-01-12_12-33-59](https://cloud.githubusercontent.com/assets/18419851/21890089/f113fb52-d8c3-11e6-878e-480d22d96817.png)

#### Your Environment

* YetiForce Version used: 3.4.1451
* Browser name and version: Chrome 55
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: gitdeveloper.yetiforce.com

**Comment by bpabiszczak** [comment]
Please check $default_language in config/config.inc.php.

**Comment by WalterLuis** [comment]
I had problems installing the developed version from 0, and at the end I could install it in a XAMPP with version 3.4.1829
The error still persists
![bug_lang](https://cloud.githubusercontent.com/assets/18419851/22925827/0ddab206-f2a2-11e6-89c6-3b1f69f1a4cf.gif)
