### ISSUE TITLE
Aktualizacja wymagań do instalacji

### ISSUE THREAD

**Issue by amdziak** [YetiForceCompany/YetiForceCRM#3908]
W wymaganiach do instalacji -> https://yetiforce.com/pl/wdrożeniowiec/instalacja-aktualizacja/99-wymagania-dla-serwera-www.html
nie ma nic na temat parametru **innodb_lock_wait_timeout** natomiast jest on sprawdzany przez instalator.

**Comment by konadrian** [comment]
Wymagania zostały zaktualizowane, proszę sprawdzić jeszcze raz stronę
