### ISSUE TITLE
Roundcube - attach from documents module

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#391]
how can I attach a document from the document module to an email?

**Comment by bpabiszczak** [comment]
You can not. You can attach a file from your desktop.
We will add this functionality in version 1.5 or 1.6.

**Comment by waran70** [comment]
Quite important to not duplicate documents (in case of scanner is running)

**Comment by waran70** [comment]
Would be cool to delete green label :-)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/0ecb6299b1a85fe59d5c091dec84887cb36f3160
