### ISSUE TITLE
Question about Customer Portal

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#3911]
Hi Team, the "Customer Portal" works in the latest stable version?. I tried a couple time and have a lot of problem when customer create Tickets and when seen all related tickets.

Thanks!

**Comment by bpabiszczak** [comment]
Customer Portal does not work in version 3.4. A few days ago we removed it from the system. Currently, we create a new version, which can be tested here: https://gitdeveloper.yetiforce.com/portal2/. The stable version will be version 4.0 or 4.1.
