### ISSUE TITLE
GitHub Authorization

### ISSUE THREAD

**Issue by jorgemarte** [YetiForceCompany/YetiForceCRM#3914]
Hi all,

I am trying to set up the GitHub authorization with my YetiForce but it's not working. The YetiForce version that I have is ver. 3.4.0. I am not sure if it's supposed to work like this, but when I put my GitHub username, Client ID, and Token and press Save it doesn't do anything. Completely nothing. It doesn't show me if the settings are wrong or right. It absolutely doesn't do anything or show anything. I tried doing it with google chrome and IE and the same thing. What am I doing wrong? 

Jorge

**Comment by zeostravelling** [comment]
Same problem here 3.4.0
