### ISSUE TITLE
Widgets on the dashboard, by default only shows "assigned to mine"

### ISSUE THREAD

**Issue by infoTopcloudxl** [YetiForceCompany/YetiForceCRM#3920]
#### Issue
All the widgets on the dashboard always show "mine", i would like to have this changed by default to all, every time i change this, and refresh the page they automatically fall back to the filer "mine"

image; http://i.imgur.com/X45bMT8.png

#### Expected Behavior
If i change the filter in the dashboard widgets, then i would like to have this changed, so if i choose "assigned to all". This should be saved. 

#### Your Environment

* YetiForce Version used: 3.4.0.
* Browser name and version: Chome, firefox
* Environment name and version: Dedicated Linux server
* Operating System and version: Cpanel/Linux/Whm

**Comment by rskrzypczak** [comment]
![image](https://cloud.githubusercontent.com/assets/10221999/22100210/ea986f40-de2e-11e6-938d-4a4e9c348fed.png)
