### ISSUE TITLE
OSSMail not working on fresh install Yetiforce 3.4.0

### ISSUE THREAD

**Issue by zeostravelling** [YetiForceCompany/YetiForceCRM#3922]
Hi,

OSSMail not working on fresh install Yetiforce 3.4.0

Roundcube module is intalled.

When I click to real mail on desktop I get a 500 internal error.

Can you help me?

![server_error](https://cloud.githubusercontent.com/assets/25207269/22108392/1ae935ac-de3a-11e6-96c4-672778fcd4fa.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Logs....

**Comment by WalterLuis** [comment]
This work in 3.4.0, check these requirements:

1. https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
2. The following modules/extensions are required to run Roundcube:
- PCRE
- DOM
- Session
- XML
- JSON
- PDO
- PEAR
    - Net_SMTP
    - Net_IDNA2 
    - Mail_mime
3. The next couple of extensions are optional and recommended to get the best performance:
- FileInfo
- Libiconv
- Multibyte
- OpenSSL
- Mcrypt
- Intl
- Exif
4. Checking php.ini/.htaccess settings
The following settings are required to run Roundcube:
- mbstring.func_overload
- suhosin.session.encrypt
The following settings are optional and recommended:
- allow_url_fopen
- date.timezone

**Comment by zeostravelling** [comment]
It was server about server file writing permission.

My webhost support fixed the permission and solved. 

Thank you.
