### ISSUE TITLE
403 Access Denied on select Contacts in OSSMail

### ISSUE THREAD

**Issue by zeostravelling** [YetiForceCompany/YetiForceCRM#3924]
Hi,

I´m getting this erros when clicking on Contacts (and every other button related to the YF)

403 Access Denied

I searched the issues repository and found nothing about it.

Searched all over the administration in YF.

What could it be?

Thank you.

**Comment by mariuszkrzaczkowski** [comment]
Logs...

**Comment by zeostravelling** [comment]
It was a problem on the webhost. They solved already.
