### ISSUE TITLE
[ENHANCEMENT][3.4.1580][Assign owner & Assign sharing users] Add roles by modules

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3925]
#### Actual Behavior

Currently you can only select users, if you have more than 500 users who want to control with these modules ... would be a very long process. If they are added by roles, you would just have to add "X" users to a role and reduce the work considerably, instead of adding them one by one

![1](https://cloud.githubusercontent.com/assets/18419851/22147480/b28a311a-df00-11e6-99c2-cedf89b8a191.PNG)

#### Expected Behavior

![2](https://cloud.githubusercontent.com/assets/18419851/22147770/2c24c7be-df02-11e6-981b-a80faff55343.PNG)

**Comment by paula-w** [comment]
There are many places in the system where managing or viewing data is inconvenient if there are many users. We are aware of this, and each new feature is designed properly. A change in only one place won't do much, it requires numerous changes in many places at the same time.

We're currently working on a 12.000 users deployment, but our client buys the intellectual property for the code we produce, we fixed a lot of mechanisms there but we can't move them here. Writing them again requires a lot of time and resources. We're not planning to change it until there is a client who is willing to pay for it.
