### ISSUE TITLE
admin interface does not allow editing of related modules fields

### ISSUE THREAD

**Issue by cadre15** [YetiForceCompany/YetiForceCRM#3926]
#### Issue

This bug/challenge affects all versions. 
There is no provision to edit the sort order of related modules. For example, In the Tickets Module, The Account Name is of type "Related fielde 1:M" (ie. uitype=10) and the admin user interface does not allow editing of the sort order of items(related modules) in the drop down. The picklist editor does not manage those fields either! While investigating how to change the order of the Account Name so that Accounts is default instead of Vendors. 
#### Actual Behavior

 I discovered that the database table (vtiger_fieldmodulerel) has a sequence column which is not adequetly used. Unfortunately the stored data was inconsistent as it allows NULL values as per screenshot.
![screenshot from 2017-01-20 12 49 24](https://cloud.githubusercontent.com/assets/19981351/22147350/ce6a388e-df10-11e6-8df1-8264f7b98804.png)

#### Expected Behavior

After modifying the data manually from the DB console:
`UPDATE vtiger_fieldmodulerel set sequence=2 WHERE fieldid=157 and relmodule='Vendors'`

Now the user interface defaults to Accounts in the Account Name field of the Tickets module.

> The solution to the above is to allow the related modules to be editable from the admin interface. and add the following modification to allow sort order to be recorded in the vtiger_fieldmodulerel table during creation in vtlib/Vtiger/Field.php from line 178 to 188:

`
    foreach ($moduleNames as $sequence=>$relmodule) {
      $checkres = $adb->pquery('SELECT * FROM vtiger_fieldmodulerel WHERE fieldid=? && module=? && relmodule=?', Array($this->id, $this->getModuleName(), $relmodule));

      // If relation already exist continue
      if ($adb->num_rows($checkres))
        continue;

      $adb->pquery('INSERT INTO vtiger_fieldmodulerel(fieldid, module, relmodule,sequence) VALUES(?,?,?,?)', Array($this->id, $this->getModuleName(), $relmodule,$sequence));

      self::log("Setting $this->name relation with $sequence:$relmodule ... DONE");
    }

`
Basically, the sequence field is populated properly henceforth. but the Admin interface must still allow editing of the sort order!

#### How to trigger the error

1. The problem is: How to change the default display value of "Account Name" field from "Vendors" to "Accounts" as most clients are likely to be Account holders than Vendors.
![screenshot from 2017-01-20 14 07 44](https://cloud.githubusercontent.com/assets/19981351/22149169/0317072e-df1b-11e6-94a2-7812bce3a9df.png)

2. We tried In Admin Mode Menu -> `Standard modules -> Edit Fields and Select Tickets`
3. Then click on the edit button of the Account Name field: As per screenshot below,  it is impossible to edit the sequence or display order:
![screenshot from 2017-01-20 13 56 43](https://cloud.githubusercontent.com/assets/19981351/22148778/cd1b344e-df18-11e6-9967-a406f4ff4545.png)
4. There is clearly a need to allow modification of related module fields

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: 50.1.0
* Environment name and version: (web= NginX 1.6.2-5+deb8u4), (app= PHP-FPM 5.6.29+dfsg-0+deb8u1), and (database= MariaDB 10.0.27-0+deb8u1)
* Operating System and version: Debian 8.6 stable

**Comment by alextovey** [comment]
Hi @cadre15

|This does not allow this at the moment. From what I gather as I asked this it may well be released in some new version but not the next one. It's all about the database and how it handles the code. You are right it would be nice but if you are wanting a custom version with editing fields may I suggest buying some credits from them and having the team dedicated some time to your request.

You can purchase credits here. [https://shop.yetiforce.com/en/](url)

**Comment by cadre15** [comment]
Thanks. I will attempt to contribute code perhaps it can help.

**Comment by alextovey** [comment]
If you can contribute I think they would appreciated that as they all have jobs as well so it's hard for them to dedicated pure time into fixing issues, they are doing a great job but as you know life can be extremely busy.

**Comment by alextovey** [comment]
Not sure, @bpabiszczak can you help him out please?

**Comment by ldgbc** [comment]
Be great if it was possible to do. Note for future user, just delete the Custom Relate to Field and Re-add it if you have the opportunity to.

**Comment by cadre15** [comment]
You see, if u just delete the field, the vtlib does not currently clean up
the database: follow details in issue #3928.

**Comment by cadre15** [comment]
This can be closed since the bug in #3928 has been closed. Solution of recreating the field everytime seems doable for now.
