### ISSUE TITLE
Zapier Integration via MYSQL or other connector

### ISSUE THREAD

**Issue by ilocalpro** [YetiForceCompany/YetiForceCRM#3927]
#### Issue

Question - trying to connect YF to Zapier using mysql to add leads automatically when google sheet is updated

#### Actual Behavior

Having difficulty finding the correct data element in the mysql structure.  Has anyone used the mysql to connect to 3rd party applications?  If so, please share process

**Comment by cadre15** [comment]
Integration at DB level is always a problem. The best is to use the yetiforce webservice API or search google for "opensource integration suite"

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/api
