### ISSUE TITLE
[bug] Company details

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3930]
#### Issue
Not able to edit the current nor add a new company
![company details](https://cloud.githubusercontent.com/assets/10330264/22174615/5ecf4c90-dfeb-11e6-81f3-b2d05d635a65.png)

#### Your Environment

* YetiForce Version used: 3.4.1588
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by alextovey** [comment]
Okay, have you applied the patch? also added the cron job to run every 5 mins as suggested?

**Comment by kpaulaha** [comment]
@alextovey  I do not think cron has anything to do with editing content of one field, on the other hand I belive https://gitdeveloper.yetiforce.com/index.php has cron up and running.
