### ISSUE TITLE
Using Postgres and eventually clustering

### ISSUE THREAD

**Issue by cadre15** [YetiForceCompany/YetiForceCRM#3932]
#### Issue

It has been great to see adoption of PDO database framework in yetiforce. With PDO, multiple database backends are supported and stable. I would like to install postgresql backend is there a config file switch?

#### Actual Behavior

changing the db_type from mysql to pgsql in the config spews out errors on database connection - The application cannot continue to function until revert back to mysql db_type.
#### Expected Behavior

It should be simple to change database type from mysql to postgres or any other db by simply changing the db_type in the config file config.inc.php.

I will start working on it if there are currently no efforts to ensure postgres support otherwise I would like to contribute...
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:3.4.0
* Browser name and version:Firefox 50.1.0
* Environment name and version: NginX 1.6.2-5+deb8u4
* Operating System and version: Debian 8.6 GNU Linux 3.16.36-1+deb8u2

**Comment by bpabiszczak** [comment]
Hello,

this is your blog: http://yetiforceonpostgresql.blogspot.com/ ?

**Comment by cadre15** [comment]
Yes it is. This is my blog.

I want to have a focus in this aspect to allow YetiForce CRM to scale and
fault tolerance improved. I think this will help YetiForce CRM in the
enterprise.

**Comment by umbz** [comment]
great idea, i want postgres on yeti :D

**Comment by umbz** [comment]
@cadre15 do you want Postgresql to make use with cockrockdb as backend? what's means?

but i think there's a lot of code in yf with hard coded mysql queries ...

**Comment by cadre15** [comment]
Happy to announce, Yetiforce can now install and run on PostgreSQL! see the blog  (http://yetiforceonpostgresql.blogspot.com) for details/discussion

**Comment by cadre15** [comment]
Here is the patch on 3.4.0
`
diff -r -u0 yt340/install/models/ConfigFileUtils.php yt340-pgsql/install/models/ConfigFileUtils.php
--- yt340/install/models/ConfigFileUtils.php	2016-10-10 16:08:41.000000000 +0200
+++ yt340-pgsql/install/models/ConfigFileUtils.php	2017-01-22 20:22:20.935368528 +0200
@@ -66,0 +67,3 @@
+		if (Install_Utils_Model::isPgSQL($dbType)) {
+			return "5432";
+		}
diff -r -u0 yt340/install/models/InitSchema.php yt340-pgsql/install/models/InitSchema.php
--- yt340/install/models/InitSchema.php	2016-10-10 16:08:41.000000000 +0200
+++ yt340-pgsql/install/models/InitSchema.php	2017-01-28 19:15:23.840455682 +0200
@@ -43 +43,3 @@
-		$this->db->query('SET FOREIGN_KEY_CHECKS = 0;');
+		if ($_SESSION['config_file_info']['db_type'] == 'mysql') {
+			$this->db->query('SET FOREIGN_KEY_CHECKS = 0;');
+		}
@@ -50 +52,5 @@
-			$sql_file = $location . $name . '.sql';
+			$sql_file = $location . $name . '.' . $_SESSION['config_file_info']['db_type'];
+			if (!file_exists($sql_file)) {
+				echo 'Missing file: ' . $sql_file;
+				return false;
+			}
@@ -77 +83,3 @@
-		$this->db->query('SET FOREIGN_KEY_CHECKS = 1;');
+		if ($_SESSION['config_file_info']['db_type'] == 'mysql') {
+			$this->db->query('SET FOREIGN_KEY_CHECKS = 1;');
+		}
diff -r -u0 yt340/install/models/Utils.php yt340-pgsql/install/models/Utils.php
--- yt340/install/models/Utils.php	2016-10-10 16:08:41.000000000 +0200
+++ yt340-pgsql/install/models/Utils.php	2017-01-22 20:22:20.963368528 +0200
@@ -20,0 +21 @@
+			'db_types' => array('mysql'=>'MySQL Server 5.5+','pgsql'=>'PostgreSQL Server 8.2+'),
@@ -50,0 +52,9 @@
+	/**
+	 * Function checks if its pgsql type
+	 * @param type $dbType
+	 * @return type
+	 */
+	static function isPgSQL($dbType)
+	{
+		return (stripos($dbType, 'pgsql') === 0);
+	}
@@ -75 +85,4 @@
-		if ($db_type) {
+		$options = array(
+			PDO::ATTR_EMULATE_PREPARES => false,
+			PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
+		);
@@ -78,2 +91,9 @@
-				$dsn = $db_type . ':host=' . $db_hostname . ';charset=utf8' . ';port=' . $dbconfig['db_port'];
-				$conn = new PDO($dsn, $db_username, $db_password);
+				$dsn = $db_type . ':host=' . $db_hostname  . ';port=' . $dbconfig['db_port'].';dbname='.$db_name;
+				if (self::isMySQL($db_type)) {
+					$dsn .= ';charset=utf8';
+					$options[PDO::MYSQL_ATTR_INIT_COMMAND] = 'SET NAMES utf8';
+				} else
+				if (self::isPgSQL($db_type)) {
+					$dsn .= ";options=--client_encoding=UTF8";
+				}
+				$conn = new PDO($dsn, $db_username, $db_password,$options);
@@ -81,0 +102,3 @@
+				$dbCheckResult['error_msg'] = $e->getMessage();
+				$dbCheckResult['flag'] = true;
+				return $dbCheckResult;
@@ -89,0 +113,4 @@
+				} else if (self::isPgSQL($db_type)) {
+					$stmt = $conn->query("SHOW server_version");
+					$res = $stmt->fetch(PDO::FETCH_ASSOC);
+					$pgsql_server_version = $res['Value'];
@@ -93 +120,5 @@
-					$stmt = $conn->query("SHOW DATABASES LIKE '$db_name'");
+					if (self::isMySQL($db_type)) {
+						$stmt = $conn->query("SHOW DATABASES LIKE '$db_name'");
+					} else if (self::isPgSQL($db_type)) {
+						$stmt = $conn->query("SELECT datname FROM pg_database WHERE upper(datname) LIKE upper('$db_name')");
+					}
@@ -95 +126,5 @@
-						$conn->query("DROP DATABASE `$db_name`");
+						//Surely this can be a bit serious! How can we just DROP the DB?
+						//$conn->query("DROP DATABASE `$db_name`");
+						$dbCheckResult['error_msg'] = "Database Already EXISTS! Please rename existing or use new name";
+						$dbCheckResult['flag'] = true;
+						return $dbCheckResult;
@@ -111 +146,7 @@
-				$stmt = $conn->query("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '$db_name'");
+
+				if (self::isPgSQL($db_type)) {
+					$stmt = $conn->query("SELECT datname FROM pg_database WHERE upper(datname) LIKE upper('$db_name')");
+				} else {
+					$stmt = $conn->query("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '$db_name'");
+				}
+
@@ -116 +156,0 @@
-		}
@@ -128,0 +169,2 @@
+		} elseif (self::isPgSQL($db_type) && $pgsql_server_version < 8.0) {
+			$error_msg = $pgsql_server_version . ' -> ' . \includes\Language::translate('ERR_INVALID_PGSQL_VERSION', 'Install');
diff -r -u0 yt340/install/tpl/Step4.tpl yt340-pgsql/install/tpl/Step4.tpl
--- yt340/install/tpl/Step4.tpl	2016-10-10 16:08:41.000000000 +0200
+++ yt340-pgsql/install/tpl/Step4.tpl	2017-01-22 20:22:20.967368528 +0200
@@ -29 +29,6 @@
-									<td>{vtranslate('MySQL', 'Install')}<input type="hidden" value="mysql" name="db_type"></td>
+									<td><select name="db_type" class="select2" style="width:20px;">
+											{foreach key=DB_TYPE item=DB_DESC from=$DB_TYPES}
+												<option value="{$DB_TYPE}" {if $DB_TYPE eq 'mysql'} selected {/if}>{$DB_TYPE} ({$DB_DESC})</option>
+											{/foreach}
+										</select>
+									</td>
@@ -32,0 +38,3 @@
+								</tr>
+								<tr><td>{vtranslate('LBL_HOST_PORT', 'Install')}<span class="no">*</span></td>
+									<td><input type="text" class="form-control" value="3306" name="port"></td>
diff -r -u0 yt340/install/tpl/Step5.tpl yt340-pgsql/install/tpl/Step5.tpl
--- yt340/install/tpl/Step5.tpl	2016-10-10 16:08:41.000000000 +0200
+++ yt340-pgsql/install/tpl/Step5.tpl	2017-01-22 20:22:20.967368528 +0200
@@ -44 +44 @@
-									{vtranslate('MySQL','Install')}
+									{vtranslate({$INFORMATION['db_type']},'Install')}
diff -r -u0 yt340/install/views/Index.php yt340-pgsql/install/views/Index.php
--- yt340/install/views/Index.php	2016-10-10 16:08:41.000000000 +0200
+++ yt340-pgsql/install/views/Index.php	2017-01-28 21:34:37.360455682 +0200
@@ -157,0 +158 @@
+		$viewer->assign('DB_TYPES', $defaultParameters['db_types']);
@@ -193 +194,2 @@
-		$dbConnection = Install_Utils_Model::checkDbConnection('mysql', $request->get('db_hostname'), $request->get('db_username'), $request->getRaw('db_password'), $request->get('db_name'), $createDataBase, true, $rootUser, $rootPassword);
+		//PHP 5.5+ pgsql is even better.
+		$dbConnection = Install_Utils_Model::checkDbConnection($request->get('db_type'), $request->get('db_hostname'), $request->get('db_username'), $request->getRaw('db_password'), $request->get('db_name'), $createDataBase, true, $rootUser, $rootPassword);
@@ -245 +247 @@
-			$db = new PearDatabase($configParams['db_type'], $configParams['db_hostname'], $configParams['db_name'], $configParams['db_username'], $configParams['db_password']);
+			$db = new PearDatabase($configParams['db_type'], $configParams['db_hostname'], $configParams['db_name'], $configParams['db_username'], $configParams['db_password'],$configParams['port']);
@@ -248 +250 @@
-			$dbPort = 3306;
+			$dbPort = $configParams['db_port'];
@@ -258 +260 @@
-				'dsn' => 'mysql:host=' . $dbHostname . ';dbname=' . $configParams['db_name'] . ';port=' . $dbPort,
+				'dsn' => $configParams['db_type'].':host=' . $dbHostname . ';dbname=' . $configParams['db_name'] . ';port=' . $dbPort,
@@ -264 +266 @@
-				'type' => 'mysql',
+				'type' => $configParams['db_type'],
diff -r -u0 yt340/languages/en_us/Install.php yt340-pgsql/languages/en_us/Install.php
--- yt340/languages/en_us/Install.php	2016-10-10 16:08:41.000000000 +0200
+++ yt340-pgsql/languages/en_us/Install.php	2017-01-23 19:00:07.425837730 +0200
@@ -16,0 +17 @@
+	'ERR_INVALID_PGSQL_VERSION' => 'PgSQL version is not supported, kindly connect to MySQL 8.1.x or above',
@@ -31,0 +33 @@
+	'LBL_HOST_PORT' => 'Host PORT',

`

**Comment by cadre15** [comment]
Eish, is there a better way to submit the patch?

**Comment by cadre15** [comment]
Also attaching the scheme and data source files. The mysql.txt files are to renamed to .mysql and pgsql.txt to be renamed to .pgsql file extensions in the install/install_schema/ folder

[data.mysql.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/737128/data.mysql.txt)
[data.pgsql.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/737131/data.pgsql.txt)
[scheme.mysql.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/737129/scheme.mysql.txt)
[scheme.pgsql.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/737130/scheme.pgsql.txt)

**Comment by cadre15** [comment]
We are now running tests:
1. User CRUD (Lead->Account {Contact,Opportunity} etc)
2. Admin CRUD (Custom Field,Custom Module etc)

**Comment by cadre15** [comment]
2. Admin: We can ADD and manage users

**Comment by cadre15** [comment]
Is there a better way to test yetiforce CRM?

**Comment by bpabiszczak** [comment]
What do you mean?

**Comment by cadre15** [comment]
a CLI tool could be useful too

**Comment by bpabiszczak** [comment]
but what you want to test?

**Comment by cadre15** [comment]
For now, Basically to test database calls and assert coverage? We need to ensure postgresql does not cause errors.

**Comment by bpabiszczak** [comment]
The system works correctly on postgreSQL [requires testing and minor fixes]. Full support for the PostgreSQL database engine, you will be together with the release of version 5.0.0 LTS.

**Comment by cadre15** [comment]
Wow great. I thought you could consider the patch I submitted to avoid waiting for ver 5?

**Comment by cadre15** [comment]
quick check in 3.4.0 for mysql specific queries  = 48 hits on queries with SHOW commands

**Comment by cadre15** [comment]
quick check in 3.4.1812 for mysql specific queries = 18 hits on queries with SHOW commands

**Comment by cadre15** [comment]
We are trying to find common queries for both pgsql and mysql at least. Good news is that both db engines support the SQL information_schema albeit at bit different.

**Comment by cadre15** [comment]
The affected files are:
include/database/PearDatabase.php
install/models/Utils.php
modules/Reports/ReportRun.php
mysql_show_commands.hits
vendor/yii/CHANGELOG.md
vendor/yii/db/cubrid/Schema.php
vendor/yii/db/cubrid/QueryBuilder.php
vendor/yii/db/mysql/Schema.php
vendor/yii/db/mysql/QueryBuilder.php
vtlib/Vtiger/Utils.php

**Comment by cadre15** [comment]
we note that yii has its own pgsql implementation - interesting too

**Comment by cadre15** [comment]
Fatal error: Uncaught PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "FROM" LINE 1: SHOW COLUMNS FROM vtiger_users ^ in /var/www/php7/yt3.4.1812/include/database/PearDatabase.php:527
 Stack trace: 
#0 /var/www/php7/yt3.4.1812/include/database/PearDatabase.php(527): PDO->query('SHOW COLUMNS FR...', 5) 
#1 /var/www/php7/yt3.4.1812/modules/Users/Users.php(430): PearDatabase->getColumnNames('vtiger_users') 
#2 /var/www/php7/yt3.4.1812/modules/Users/Users.php(221): Users->get_user_crypt_type() 
#3 /var/www/php7/yt3.4.1812/modules/Users/Users.php(514): Users->encrypt_password('admin', NULL) 
#4 /var/www/php7/yt3.4.1812/modules/Users/Users.php(475): Users->verifyPassword('admin') 
#5 /var/www/php7/yt3.4.1812/install/models/InitSchema.php(102): Users->change_password('admin', 'sfSfDfgHhj112233', false) 
#6 /var/www/php7/yt3.4.1812/install/models/InitSchema.php(24): Install_InitSchema_Model->setDefaultUsersAccess() 
#7 /var/www/php7/yt3.4.1812/install/views/Index.php(208): Install_InitSchema_M in /var/www/php7/yt3.4.1812/include/database/PearDatabase.php on line 527

**Comment by cadre15** [comment]
There are still errors caused by mysql specific database calls in the latest 3.4.1812

**Comment by mariuszkrzaczkowski** [comment]
Yes I know to run fully compatible with Postgres is still a lot of work to do.
