### ISSUE TITLE
Copy address from related field as primary

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3933]
#### Issue
Can't seem to copy the address from a related field such as clients to managers

#### Actual Behavior
Click on the button to copy the address across.

#### Expected Behavior
related fields missing information but should show the information

#### How to trigger the error
![address](https://cloud.githubusercontent.com/assets/22075161/22198007/78a91bf2-e14c-11e6-9d39-f5b61b69c409.gif)

#### Your Environment

* YetiForce Version used: 3.4.2
* Browser name and version: ff, chrome, ie 11, edge

**Comment by mariuszkrzaczkowski** [comment]
Are there two new modules or standard ones?
You need to give more details about the modules and the relationships between them.
