### ISSUE TITLE
[bug] deleting users

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3934]
#### Issue
Deleting users do not work.
![users](https://cloud.githubusercontent.com/assets/10330264/22205093/fe8fc3fc-e17d-11e6-90b1-21cca3548575.png)

* YetiForce Version used: 3.4.1603
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by TomaszQr** [comment]
Fixed via https://github.com/YetiForceCompany/YetiForceCRM/commit/7de23e9e95467c9405997337885f2bb9c75947c9
