### ISSUE TITLE
Mantaining Languages with pootle server?

### ISSUE THREAD

**Issue by umbz** [YetiForceCompany/YetiForceCRM#3935]
Hi, i want to contribute with italian transaltion, but the legacy system  about of yetiforce  is boring :D.
if is possible , it can be prepared a system like pootle (http://pootle.translatehouse.org/).

SuiteCrm do this  (with crowdin i think).

Regards

**Comment by bpabiszczak** [comment]
What does this system have, that our built-in solution doesn’t?

**Comment by ldgbc** [comment]
I noticed that some user have language that is not currently in Yetiforce. Is there some documentation that user can upload and share Translation?
For example this user:
https://github.com/YetiForceCompany/YetiForceCRM/issues/3361

**Comment by paula-w** [comment]
How is this related to the first question in this issue?
1. If someone translated the system to another language and didn’t send it to us then it’s their choice, whether we use pootle or not doesn’t change anything.
2. The translation must be updated on an ongoing basis, and must be developed simultaneously with the system. If these requirements are not met, then the translation is useless.
3. The translation has to be supervised as far as the content is concerned, but also from the legal point of view [every contributor must sign the CLA – Contributor Level Agreement].
4. Adding translations via GitHub is pretty simple -  https://help.github.com/articles/about-pull-requests/

**Comment by umbz** [comment]
with pootle there are some practical advantages:

1) you can add commentfor an existent translation

2) you can review the translations that another user want to be reviewed

3) you can read the other translation committed for the same term.
http://prntscr.com/e0rs9u

3) you can control the % of terms translated. 
http://prntscr.com/e0rstn

**Comment by umbz** [comment]
so there is a reason if suitecrm use a similar system :)
