### ISSUE TITLE
[bug] [dev 3.4.1607] fatal error in Report Modul

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3936]
#### Issue
I cannot generate a report.

#### Actual Behavior
fatal error

#### Expected Behavior
no error

#### How to trigger the error
![fatalerror](https://cloud.githubusercontent.com/assets/10259801/22240093/c66ebfcc-e219-11e6-849e-3ce43c74d912.gif)

#### Your Environment

* YetiForce Version used: dev 3.4.1607
* Browser name and version: chrome / firefox
* Environment name and version: 
* Operating System and version: W10

**Comment by TomaszQr** [comment]
Fixed via https://github.com/YetiForceCompany/YetiForceCRM/commit/7de23e9e95467c9405997337885f2bb9c75947c9
