### ISSUE TITLE
Hi,  How can I use euros as my base currency on Yeti? also, I need to create Angola Kwanza (AOA), and the system doesn't allow me to do that. Is there a turnaround solution that I don't see it right?

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#3937]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@PDMeira You can install local sysytem on your server or PC and select euros as base currency.
What iz Angola Kwanza (AOA)???

**Comment by PDMeira** [comment]
angola Kwanza it's a local currency that is not listed on available currencies.

How do I configure euros as base currency for everything? Any documentation? US dollar symbol is everywhere

**Comment by skramanzia** [comment]
@PDMeira In the installation wizard you can set the default currency. If you select US Dollar symbol it will be the default. Check in "Software configuration > System tools > Currencies"

**Comment by alexgogan** [comment]
Hi, 

We jsut set up the deployment via Softalicous and there is no option in the set up, can you advise how we edit this as I have gone via the gui and seen nothing like this, and in the core DB neither

**Comment by PDMeira** [comment]
The same with me. I did with Softaculous and don't see any option to do it. It doesn't allow me to define euros as default currency. I also don't see how I can setup a currency that it's not listed on "Software configuration > System tools > Currencies". Please advise.

**Comment by mariuszkrzaczkowski** [comment]
try this
```sql
UPDATE `vtiger_currency_info` SET `defaultid` = '0';
UPDATE `vtiger_currency_info` SET `defaultid` = '-11' WHERE `currency_code` = 'EUR'; 
```
