### ISSUE TITLE
Importing Greek Char Files 

### ISSUE THREAD

**Issue by aylanet2** [YetiForceCompany/YetiForceCRM#3941]
#### Issue

Greek Char Issue on CSV Import Fails

#### Actual Behavior

When you using Importing tools (e.g on Leads Module) Greek Character on Files Displayed as ???

#### Expected Behavior

Since we exporting for yeti or vtiger as csv (utf-8) character encoding should be correct

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
Can you add a sample file?

**Comment by nkzach** [comment]
Choose **Windows-1253** as **Character encoding** on yeti import options.

**Comment by aylanet2** [comment]
@nkzach I had tried that as well same result diferent symbols

**Comment by aylanet2** [comment]
The following file contains a csv file with 20 records utf exported from another yetiforce instllation 
[Leads_5.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/733070/Leads_5.zip)

**Comment by nkzach** [comment]
Importing (as UTF8) from your own file works fine in Yetiforce 3.4 and in current developer version. Just now i tried it.

**Comment by aylanet2** [comment]
@nkzach Please take a look here
![leads list](https://cloud.githubusercontent.com/assets/18685093/22344475/062860ae-e405-11e6-894f-066eeef835fa.png)

**Comment by nkzach** [comment]
From the site Stable version. Records are there. Take a look and delete.

![untitled-1](https://cloud.githubusercontent.com/assets/22010748/22345841/6c48f196-e40a-11e6-9bc8-2be018bac6e4.jpg)

**Comment by aylanet2** [comment]
I see so what you think is causing that in my case?

**Comment by nkzach** [comment]
It's encoding problem. Take a look at  **character set** and **collation** in MYSQL database server? Is utf-8 and utf8_general_ci?

**Comment by mariuszkrzaczkowski** [comment]
Check default_charset 
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/config.template.php#L116

**Comment by aylanet2** [comment]
@nkzach Yes both are as noted
@mariuszkrzaczkowski It was exactly the same as your file, i even hardcoded utf-8 as charset same issue

**Comment by bpabiszczak** [comment]
Please check new version with this fix. https://github.com/YetiForceCompany/YetiForceCRM/commit/3a842b63d5540b57c4f5fb9d39b5ce23397e37ab
