### ISSUE TITLE
[Question] New type of Tax?

### ISSUE THREAD

**Issue by WhyNotCrazyTrain** [YetiForceCompany/YetiForceCRM#3942]
I wanted to know if I can create a custom type of tax in the inventory field which will calculate taxes not from the gross but from the margin field...
Could you help me and tell where I can find the tax calculation files?

**Comment by PercyP** [comment]
Hi,

can this not be done in the Administrator area under Advanced Modules?

**Comment by WhyNotCrazyTrain** [comment]
@PercyP 
I can add more types of taxes there but it will only calculate it from the gross anyways, the only difference is a name of a tax and its' value(%) =\
