### ISSUE TITLE
[Question] Searched permission

### ISSUE THREAD

**Issue by iRainSystem** [YetiForceCompany/YetiForceCRM#3943]
![search_permission](https://cloud.githubusercontent.com/assets/17310158/22361661/a341faee-e464-11e6-945d-54b91d972c37.gif)

Question.
**to the role of "Sales Departement"**
1. Modules that can be searched without permission = Accounts and Contacts
2. Module access for Accounts and Contacts = private

user test1 add new Account test1
user test2 add new Account test2
but when you use the advanced search, each user sees only their entries

**What is the meaning properties "Modules that can be searched without permission" in a Role settings?**

#### Your Environment

* YetiForce Version used: 3.4.0
https://gitstable.yetiforce.com/ - Stable version

**Comment by bpabiszczak** [comment]
You can search in global search but you dont have access to preview, edit, delete.
