### ISSUE TITLE
[QUESTION] Do you plan to convert to multi-company CRM?

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#3945]
I've seen that have changed the module "Companies" to insert more than one.
![chrome_2017-01-27_10-45-25](https://cloud.githubusercontent.com/assets/18419851/22368792/5b95e108-e480-11e6-9547-336ba3482021.png)

like this module to vtiger?
http://www.its4you.sk/en/vtiger-extensions/crm-vtiger-extension-multicompany

I would like to know if they will convert it to multi-company, and if you are going to do it, which version would be expected

Thanks in advance

**Comment by bpabiszczak** [comment]
We will add it in our free time. I do not know when. You can order this functionality :P

**Comment by douglasfabianospecht** [comment]
Hello..
Would also be interested in the multi-company option, do you have this functionality forecast?

**Comment by paula-w** [comment]
We've already implemented some of these mechanisms. If you describe your requirements we will be able to provide more info.

**Comment by douglasfabianospecht** [comment]
So I wish I could have a Yeltiforge source and several client databases, or another way to completely separate them.
Example contact information, leads, company 01 opportunities can not appear in the company 2.
Would be the yeltiforge as you leave practically.
