### ISSUE TITLE
Status - Completed

### ISSUE THREAD

**Issue by infoTopcloudxl** [YetiForceCompany/YetiForceCRM#3946]
#### Issue
Status - Completed

When the status of an opportunity/sales order / task/ ticket / appointment etc is put on COMPLETED the field is not accessible and adjustment cannot be made. Once set on COMPLETED no possibilities to change status. Field is closed.

#### Expected Behavior
I still would like to be able to edit the opportunity/sales order / task/ ticket / etc if the status is set completed. Sometimes later on the process we see something is not completed 100%.

**Comment by skramanzia** [comment]
@infoTopcloudxl Check in "Software configuration > Automation > Workflows", you can set "Block" in modules.

**Comment by infoTopcloudxl** [comment]
tnx !

**Comment by bpabiszczak** [comment]
You should delete values from this array https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/SSalesProcesses/SSalesProcesses.php#L14
