### ISSUE TITLE
New Server

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3947]
Hi all, I've setup a new server to cope with yetiforce load. I'm struggling setting this up correctly wonder if anyone can help.

The server is ubuntu 16.04.1php version 7.0.13
ioncube loader v6.0.9
also running mariadb (mysqlnd 5.0.12)
Running apache2.

I've set most of the other items its just this bugging the hell out of me.

Also How can I transfer yetiforce over from one server to a new one with a different  url/ip? as it keep returning me to the other server when it's installed.

**Comment by skramanzia** [comment]
@alextovey If you change the URL and SQL credentials and database, you need to change "config/config.inc.php" file.
 If you change IP, no thing to change in YF, only check your public DNS Server to resolved the new.

Please check this URL to confirm the requirements, YF doesn't support PHP 7 yet.

https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html

**Comment by alextovey** [comment]
Right, I'm running php 5.6 how can I view the debug log as I'm getting error 500.
