### ISSUE TITLE
[Question] Attention message on top of page

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3948]
This is a question. How to made red popup attention message what used now at dev?

I mean this one:

![image](https://cloud.githubusercontent.com/assets/8545791/22381336/44b66992-e4d2-11e6-8fc0-f07f94e04f9b.png)

**Comment by skramanzia** [comment]
@vovpff I dont know if the correct way.  You can add this item in the end of Index.php file. thus:

?>
<span class="alert" style="position:fixed; top: 8px; left:60%; z-index: 100000000000; color:#fff;background-color: #ff2f00;padding: 0 10px;"><h5>Version Dev VR4IT. <button type="button" style="margin-left: 10px;" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button></h5></span><?php

**Comment by vovpff** [comment]
@skramanzia Thx. But this message can't be closed.

**Comment by skramanzia** [comment]
Yes, after Login you can Close.

**Comment by vovpff** [comment]
@skramanzia I checked this. Thanks one more time
