### ISSUE TITLE
[Question]  Guide - Manual - Wiki - implementation

### ISSUE THREAD

**Issue by canomogollon** [YetiForceCompany/YetiForceCRM#3949]
You can recommend a site, guide or manual to implement this crm correctly, I have it installed and I want to customize it for my clients

**Comment by vovpff** [comment]
@canomogollon for this time there is no wiki or mannual with full functionalty. Let's check this git. Thereare a lot of usefull information.

**Comment by ldgbc** [comment]
@canomogollon @vovpff 
In the meantime I guess I'll use this place as a dropoff point as I discover more about Yeti. This way when we do have a Wiki, at least there some references point.

1. /index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&block=2&fieldid=41
In here there is this "Star" next to Visible. If you click on them it will show a Star when you viewing it in Detail/Record view. These star are Favourite. Not sure where the favourite goes to though.
For example, Enable Star on Contact > Activities. Then go open your Contact > Contactname1 > Click Activities > Left hand side, there is a Star, Hover over that and it say "Favourite"

**Comment by ldgbc** [comment]
6. CalDav CardDav DavDroid Sync Calender and Contact. See these for references: #3510  #3064 
work in progress until I figure this out.
