### ISSUE TITLE
Need Integrated POS system

### ISSUE THREAD

**Issue by saikatkoley** [YetiForceCompany/YetiForceCRM#3950]
We need a integrated POS system. Or just tell me any open source POS system which can be work or be integrate with yaticrm.

**Comment by vovpff** [comment]
@saikatkoley there are [POS module](https://shop.yetiforce.com/en/products/18-pos.html) available but this module costs some money

**Comment by easaw** [comment]
Yes... Why **does** it cost €990? €99 Would be a better price and they would sell more - especially to new businesses.
