### ISSUE TITLE
Meeting with multiple "contacts" ?

### ISSUE THREAD

**Issue by edmundhumenberger** [YetiForceCompany/YetiForceCRM#3952]
#### Issue

I had a meeting with serverlal people from several accounts. But I can only attach one contact to the meeting.
 

![yeti meeting with several people](https://cloud.githubusercontent.com/assets/10908608/22406943/ee3b9cea-e65c-11e6-8dbf-c1db5af52bdd.png)

#### Actual Behavior

this limits the usefullness of this to coordinate and document meetings

#### Expected Behavior

it would be great to be able to add multiple contacts and accounts to one meeting.

#### How to trigger the error

Just try to make a news event with multiple participants from different accounts.

2.
3.

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version: Firefox
* Environment name and version:
* Operating System and version: Linux Ubuntu

**Comment by bpabiszczak** [comment]
![image](https://cloud.githubusercontent.com/assets/10197525/22409456/425e5cc2-e68a-11e6-9f33-42246ddaec05.png)

**Comment by edmundhumenberger** [comment]
I dont see in your screenshot how I could add several contacts to one meeting.

What do you try to tell me?

**Comment by bpabiszczak** [comment]
Do you see "Invite users"? It works in new version.
