### ISSUE TITLE
@ not recogniced in email field

### ISSUE THREAD

**Issue by edmundhumenberger** [YetiForceCompany/YetiForceCRM#3953]
#### Issue

In this field I can not enter a @  as it is not recognized by the field.

Everywhere else it is working to enter a email address.

![bugyeti](https://cloud.githubusercontent.com/assets/10908608/22406972/955450a8-e65d-11e6-8e15-bc079c85e2b5.png)

#### Actual Behavior

unable to enter a @ for a valid adress

#### Expected Behavior

I want to be able to enter a valid address including a   @ with the keyboard

#### How to trigger the error

Just call the mask as shown in the screen and try to enter a email address in the field.
its just not possible for me as it does not recognize @

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version:  firefox 49.0
* Environment name and version: Ubuntu 16.10
* Operating System and version:

**Comment by bpabiszczak** [comment]
For me working properly.
![image](https://cloud.githubusercontent.com/assets/10197525/22409487/a67e8f2e-e68a-11e6-984f-36ada9425747.png)

**Comment by edmundhumenberger** [comment]
![worksforme](https://cloud.githubusercontent.com/assets/10908608/22409561/95514600-e68b-11e6-82a1-2fd2204e574f.png)

Outsch.
