### ISSUE TITLE
Type to serach not finding existing entry in Contacts

### ISSUE THREAD

**Issue by edmundhumenberger** [YetiForceCompany/YetiForceCRM#3954]
#### Issue

I type 3 letters "pra"  and the message i get is "no results found"

But as you can see on the right side, there is the person "Prammer"

![type to search not working](https://cloud.githubusercontent.com/assets/10908608/22407260/57146d40-e663-11e6-806d-c4850cfa9ca7.png)

#### Actual Behavior

Type to search does not work.

#### Expected Behavior

Type to search should find contact Prammer

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:  3.4
* Browser name and version: Firefox 49
* Environment name and version: Ubuntu 16.10
* Operating System and version:

**Comment by SkavenKF** [comment]
CRON active?
Other names found?

**Comment by edmundhumenberger** [comment]
No, no other name is found.

Where Can I check if CRON is active?  WHy would that matter?

**Comment by SkavenKF** [comment]
look at [3590](https://github.com/YetiForceCompany/YetiForceCRM/issues/3590)

zu 3.3 wurde einiges auf CRON umgestellt 😄

**Comment by edmundhumenberger** [comment]
I do not understand why all my CRON jobs are active, but there is no time written at "Last time started"

![cron](https://cloud.githubusercontent.com/assets/10908608/22408860/c69450aa-e680-11e6-945e-7166115e60f3.png)

**Comment by bpabiszczak** [comment]
no time = cron does not work

**Comment by ldgbc** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3910

You can get some idea here.
