### ISSUE TITLE
Is it possible to re-create the Contacts Primary Address Block in a custom module

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3955]
Hi,

I want to create an exact copy of the Primary Address block from Contacts into a custom module. I have tried using the 'Values from related module' and linking my custom module field to the Contacts primary address fields, but this isn't any good to me as this displays the addresses for a contact and not for my custom module. I basically want to create addresses for premises that are not related to the contacts. 

If I create the fields for Building, street, postcode etc. How do I add the search box and the copy buttons so they work like the Contacts address form?

I have gone through the configuration sections and cannot see any option in the development areas to do this. Is there an option to copy an entire block?

**Comment by PercyP** [comment]
Hi,

I am not sure if this is the correct solution but it seems to work for me in that the search and Copy from Contact etc. work now in my custom module. 

1. I created a custom block and in the block name I added:

LBL_ADDRESS_INFORMATION

2. I created a 1:M field to another block and connected it to (in my case) the Contact module

3. I added custom text fields that had the same address field names as the Contacts Primary Address block

Now the search and the Add from buttons appear.

I think if you want to include addresses i.e. from the COmpanies module you just add a 1:m link field to Companies - it seems to have picked that up in mine. 

And if you want multiple blocks as per the Companies address fields then the block names i.e. for Delivery Address, Mailing Address need to have the labels given to those i.e.

LBL_ADDRESS_MAILING_INFORMATION
LBL_ADDRESS_DELIVERY_INFORMATION

The only thing I can't change is the label for the block (as Ideally I want it to say something like Private Address, but if I change this, the search and buttons do not display. 

If anyone happens to know how to get round that I would be happy to hear the solution :O)

**Comment by PercyP** [comment]
Ah,

scrap the above. It does display the button and search box, but when you click on the Contact it doesn't do anything. Back to the drawing board!

**Comment by mariuszkrzaczkowski** [comment]
It is built into the engine to add it you need to modify many files. The easiest way to do it on a workflow is to copy the values when editing

**Comment by PercyP** [comment]
I looked at the workflow but couldn't get it to work.

**Comment by rioshaz** [comment]
> It is built into the engine to add it you need to modify many files. The easiest way to do it on a workflow is to copy the values when editing

@mariuszkrzaczkowski yes but workflow can only do it when a new contact has been added or  modified.. it cannot work if an existing contact is selected..
there is no workflow to run if contact is not modified or new created..  

we can only run schedule workflow thats runs every 5 mins.. which is not instant for critical business, which need instant dtata...
