### ISSUE TITLE
To-Do Activity without a date

### ISSUE THREAD

**Issue by edmundhumenberger** [YetiForceCompany/YetiForceCRM#3956]
#### Issue

Having to give a date and time to a to-do is a very unpractical thing.

You should look more at Trello how people plan tasks.

#### Actual Behavior

![to-do without date](https://cloud.githubusercontent.com/assets/10908608/22408645/9d6684ae-e67c-11e6-8329-c6162d79f3ab.png)

#### Expected Behavior

A Task has a livescycle. It is born just with a subject in the status idea, then gets planned, then gets scheduled, and then waits and then gets "done"

especially in the first stages there is no need to add a time and date.
So please make it non mandatory.

But there might be a need for adding the possibility to add the following dates to a task

Task has to be started before
Task has to be finished until
Task can not be started before
Task has the following planned duration
Task has been started at
Task has been finished at 

#### How to trigger the error

Try to really use the Task object for a real project, and you will find out that is is currenlty not very usefull

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
We do not plan to change this functionality.
