### ISSUE TITLE
depreciated messages popping up

### ISSUE THREAD

**Issue by edmundhumenberger** [YetiForceCompany/YetiForceCRM#3957]
#### Issue

this "Depreciated"  messages popping up all the time.

![depreciated](https://cloud.githubusercontent.com/assets/10908608/22408806/c4b69028-e67f-11e6-9f46-c700737c5d95.png)

#### Actual Behavior

just annoying

they appear in many places.

#### Expected Behavior

no error messages

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
You have incorrect server configurations. Please check this: https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html [error_reporting: E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT]
