### ISSUE TITLE
Dashboard Mini List Filter Not showing filters

### ISSUE THREAD

**Issue by rbloodworth** [YetiForceCompany/YetiForceCRM#3958]
Hi,

When trying to create a Mini List From Filter on the dashboard, no filter elements are listed in the selector. I have Tried the ALL element and also added custom filters from the settings section. No filters are present in the selector except a listing for (Mine), which is not selectable.

Thanks.

#### Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Chrome
* Environment name and version: Linux with PHP 7.1
* Operating System and version: Windows 7 64-bit

**Comment by konadrian** [comment]
Have you selected the List in metrics option while creating the filter?
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/22420279/013838f0-e6e2-11e6-90ee-0b02ea4b7071.png)

**Comment by rbloodworth** [comment]
Konadrian, 
Thanks for your suggestion. That was the issue. I did not know about the List in Metric option.

Also, Do you know if More than one Tab can be placed on the Homepage? I know this is an option in Vtiger, but did not see an option to create the new tab's in Yetiforce.

Thanks..

**Comment by konadrian** [comment]
You can have several tabs, below screenshots on how to do that. Next time one question per issue please.
![1](https://cloud.githubusercontent.com/assets/3193498/22456150/f8e9d41a-e790-11e6-9b0a-305977b8cfac.png)
![2](https://cloud.githubusercontent.com/assets/3193498/22456154/fdb02210-e790-11e6-8307-bf11aff8aaa3.png)
