### ISSUE TITLE
configure list of products&services

### ISSUE THREAD

**Issue by edmundhumenberger** [YetiForceCompany/YetiForceCRM#3959]
#### Issue

I want to change the content of the list from where user can select what accounts are interested in.
![list of products services](https://cloud.githubusercontent.com/assets/10908608/22440179/b3728ad4-e732-11e6-87ec-1d0ea308d82d.png)

#### Actual Behavior

I dont know where to change this list. I could not find it.

#### Expected Behavior

At the same location where I can configure the pull up menus to change this list.

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version: Firefox
* Environment name and version: ubuntu 16.10
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=TreesManager&parent=Settings&view=Edit&record=3
