### ISSUE TITLE
Sell for some little coins VM OS 

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#3960]
What if you install and configure Centos, Ubuntu etc.  with Yetiforce current stable version, on VM and sell such for like 5-10 Euro? New YF, updated VM...
Lots of guys will be happy to donate this way... do test and lets see?

**Comment by bpabiszczak** [comment]
Lots of guys means how many? How much time does an admin need to configure and then update on an ongoing basis a VM like that? We’ve never used VMs [images], and when we install it for a client it always is a dedicated environment [usually RHEL].

**Comment by easaw** [comment]
@waran70 - So basically do what Sugar and Suite are? (SaaS)?
