### ISSUE TITLE
[Question] How can a user change his password?

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#3962]
Same problem #3892, but no solution.
Users should change their password not the preferences, but only user with Administrator profile can change the password!

Which permission (in profile?) is relevant to change the password?

Following configuration in security.php:
	// Possible to reset the password while logging in (true/false)
	'RESET_LOGIN_PASSWORD' => false,
	// Show my preferences
	'SHOW_MY_PREFERENCES' => false,
	// Changing the settings by the user is possible true/false
	'CHANGE_LOGIN_PASSWORD' => true,

In menü i add the profil item.

![profil](https://cloud.githubusercontent.com/assets/10259801/22502270/88abf822-e86c-11e6-8fd7-075c80a891f8.JPG)

**Comment by kpaulaha** [comment]
If you chanfe SHOW_MY_PREFERENCES' => true, user can change password in user details

![users - detail](https://cloud.githubusercontent.com/assets/10330264/22511945/fc6e9afc-e89f-11e6-8aa0-124014ceb724.png)

**Comment by SkavenKF** [comment]
This is correct, but the user should NOT change his preferences! I think for this is the menu item "profile".

**Comment by kpaulaha** [comment]
If you set RESET_LOGIN_PASSWORD' => true, 'SHOW_MY_PREFERENCES' => false, user can reset the password and only that, using the profile in menu. 
![my home page](https://cloud.githubusercontent.com/assets/10330264/22512636/60bbd338-e8a2-11e6-9b07-ee6b45ed919d.png)

**Comment by SkavenKF** [comment]
Ok, my mistake. Yesterday i think i tested as admin (change user). Today when i tested with user, i have no problem.
