### ISSUE TITLE
Customer Portal Issue

### ISSUE THREAD

**Issue by allamericangroup** [YetiForceCompany/YetiForceCRM#3963]
#### Issue
Directly above the Login box on the login page you see an script. It shows the following;

Strict Standards: Non-static method AppRequest::isEmpty() should not be called statically in /home/XXXX/public_html/portal/portal.php on line 157

Strict Standards: Non-static method AppRequest::has() should not be called statically in /home/XXXX/public_html/portal/portal.php on line 164

Strict Standards: Non-static method AppRequest::has() should not be called statically in /home/XXXX/public_html/portal/portal.php on line 171

Strict Standards: Non-static method AppRequest::has() should not be called statically in /home/XXXX/public_html/portal/portal.php on line 173

#### How to trigger the error

1. https://dl.dropboxusercontent.com/u/41007170/Capture.PNG
2.
3.

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Any Browser
* Environment name and version: cPanel Shared
* Operating System and version: CentOS 6

**Comment by aramxalil** [comment]
I'm although having this problem and even I cant login with any account please help ..

**Comment by slawekk87** [comment]
It look like environment problem, still exists on current version?
php display_errors should be disabled, only logging to files should be enabled.
