### ISSUE TITLE
Permission Denied error message

### ISSUE THREAD

**Issue by YorgoB** [YetiForceCompany/YetiForceCRM#3964]
#### Issue

After installation(from scratch , not update) - of the fix version (3.4.1047), when I'm trying to add a record at sales section (esquires, requirements etc ) I'm receiving first error 1.png and then when I try to go again to add a record I'm receiving error 2.png.

In a clean version I do not face similar issue. The reason I proceed to 3.4.1047 is to resolve this [issue](https://github.com/YetiForceCompany/YetiForceCRM/issues/3807
![1](https://cloud.githubusercontent.com/assets/24439715/22524839/8824dcf0-e8cd-11e6-8352-2f09786e49be.png)
![2](https://cloud.githubusercontent.com/assets/24439715/22524840/882892fa-e8cd-11e6-9f50-28c73136aab7.png)

)

#### Actual Behavior

Can not use the sales functionality 

#### Expected Behavior

Use the sales 
#### How to trigger the error

1. Sales enquirie
2. Add a record 
3.

#### Your Environment

* YetiForce Version used:3.4.1047
* Browser name and version: Mozilla - 51.0.1 
* Environment name and version: Windows
* Operating System and version:

**Comment by vovpff** [comment]
@YorgoB check your CRON and database parameters.

**Comment by YorgoB** [comment]
Thank you for your response but could you be more specific ? 
I;m attaching a PrtScn of CRON parameters
![cron](https://cloud.githubusercontent.com/assets/24439715/22541615/0f07c810-e930-11e6-9115-8b120502e1ce.jpg)

**Comment by SkavenKF** [comment]
look at [CRON Doku](https://yetiforce.com/en/administrator-documentation/panel/cron/150-enable-cron.html)

**Comment by YorgoB** [comment]
Unfortunatelly I'm not that familiar with that !
Any other help appreciated .
Thank you !

**Comment by vovpff** [comment]
@YorgoB you need to activate cron with some time interval. To get greatest result cron activation must be every 1 minute (minimal frequency at your sreenshot). If you use OS Windows i can prepare for ypou small cron manual.

**Comment by SkavenKF** [comment]
for windows look at [Windows CRON](https://wiki.vtiger.com/index.php/Cron)

**Comment by YorgoB** [comment]
@vovpff Should I create a cron procedure locally ?

**Comment by mariuszkrzaczkowski** [comment]
The error occurs in the latest version?

**Comment by vovpff** [comment]
@YorgoB check @SkavenKF manual for os windows cron
