### ISSUE TITLE
[question] Removal of Customer portal

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#3965]
Noticed that you removed Customer portal from the modules, reason for that? Is it final?

**Comment by PercyP** [comment]
Maybe they are creating something better inside the CRM?

Regardless, it would be nice to know the direction they are going in so we can assess whether future yetiforce is right for us and to prevent investing any more time (and money going forward) on going with it 100%. 

I am not using it yet in production as just working with it to see if it can do all the things I will need. I have invested a little financially to improve things for myself (mostly aesthetically i.e. integrating more modern theme for Roundcube etc.) 
At the moment functions/modules are being removed (without warning which is worrying). For example, webforms: I invested lots of time setting up these for my website and now they will be unusable. Ability to upload images in the WYSWYG editor - images are crucial to us, Customer Portal - also invested a lot of time in etc.

I am wondering if the Open Source element is slowly being phased out? It is a shame, as although the core product is free, there is a huge amount of money to be made from extensions (including 3rd party extensions) subscriptions etc. Maybe there is a reason why they prefer not to go down that route?

What is certain, is I personally now need to consider whether to stay with this project, or abandon it to find something that has less uncertainty.

**Comment by kpaulaha** [comment]
@PercyP  Yes, we have also looked for altenatives when, as you said, you do not know the direction of the future. It's pity I like YF, but we have not dared to use it in any serious cases so far when you do not know what updates brings you. Belived it to be good alternative for vtiger and so it of course is, but, but.
We started 2004 with sugarcrm and now we have slided back to that direction, testing also a few other, vtiger we do not much use more. Anyhow I really hope we could work with yf, it came as a shining from the sky some years ago when vtiger begun to be a big mess.

**Comment by PercyP** [comment]
@kpaulaha 

yes, I was extremely excited with YF after being with vtiger for many years. I still am, I look forward to their releases. I don't want to move away, as love what they are doing., but I also worry that all my hard work might be undone each time they remove a component without warning. I am effectively stuck with 3.4 now (if 1: if I can't upgrade and 2: if many of the modules I use are being removed). I have started from scratch with YF and was hoping this was something I could stick with, grow and invest in.

**Comment by kpaulaha** [comment]
@PercyP Same here, and now having a few companies testing 3.4, but they would also use webforms and customer portal and now they seem to be gone and what else in the future. The webforms we can get around using Mautic forms and push contacts to yf, but CP is more difficult if it is removed.

**Comment by waran70** [comment]
Can anybody from Yetiforce team tell us here, where this is going to? Any roadmap?

**Comment by easaw** [comment]
@kpaulaha @PercyP @waran70

There does seem to be a portal 2
[https://github.com/YetiForceCompany/YetiForcePortal2](https://github.com/YetiForceCompany/YetiForcePortal2)

**Comment by waran70** [comment]
I am not worrying of issues shown in development version, but I worrying of development speed itself.  Guys planning release LTS on February 14 BUT, on March 31 version 4.1 !!!
How it is possible? LTS is chased with another release in few weeks and this is their designed milestone? So here is the question about STABILITY and PREDICTABILITY.  Yetiforce.... where are you going hmm?

**Comment by kpaulaha** [comment]
Yup, found also the portal2 last night when roaming around, that was a great relief, so it was only a panic reaction of me in the beginning. 
Working years with open source has learned that the milestones are not much to rely on. More worries me that is there time to test RC good enough before the stable is published, 
We have been running test on other OS CRM, some known from past and some new, and must say that with most of them you miss many features YF has. But some kind of  roadmap should be nice to have avoiding extra heart attacs in the future if you have it in production use and why not leave removed good function as options e.g. webforms so one could take it in use knowing the risks. Collecting leads is anyhow quite important feature in CRM.

**Comment by PercyP** [comment]
Ah ... bad me, I didn't even verify for myself that the portal had been removed - thats a relief ;-) @kpaulaha   I agree that it would be good to have the option to keep older modules (if there is nothing to replace them). Or, if all it requires is a new script to create something to replace the webform to capture leads, and YT are not planning on adding it as a core, why not create one for the extension store for those who want it, to download for a small fee - after just a couple of downloads they would cover their development cost and some.

**Comment by bpabiszczak** [comment]
I will answer on Monday.

**Comment by PercyP** [comment]
@bpabiszczak 

thank you! Just took a peek. Looks brilliant - now same theme as crm with more features too. Apologies for panicking.

**Comment by easaw** [comment]
I have yet to get it working though. It never seems to show in Yeti, even though I change the **three** required config files (only says about **two** in the Documentation)

**Comment by easaw** [comment]
@bpabiszczak the GitDeveloper portal shows Polish when selecting English 👎

**Comment by PercyP** [comment]
@easaw if you leave the language as is when logging in, it should then offer to translate to english - at least it did for me. 

I don't think the developer version is for installing, think he was just showing us that it was work in progress of what is to come.

Think its just the configs in both the portal and the crm

**Comment by PercyP** [comment]
@kpaulaha 

> Yup, found also the portal2 last night when roaming around, that was a great relief, so it was only a panic reaction of me in the beginning.

Ha ha ... and in  me too

**Comment by easaw** [comment]
@PercyP I did let it translate, but obviously it's an issue so I was letting @bpabiszczak know.

I did change the configs correctly. The portal showed up, it just doesn't connect...

**Comment by reeid** [comment]
Hi... how is progress in portal project? Will it be available with 4.1?

**Comment by waran70** [comment]
Any news please gents? Not sure if looking at portal git files mirroring real status of work

Tnx for any info in advance

**Comment by paula-w** [comment]
The new portal will be released in about 6 – 8 weeks. One of our clients ordered development of the feature, so next week we begin working on a broader integration between the portal and CRM.

**Comment by cltvchannel** [comment]
@paula-w The portal is released now ?

**Comment by PercyP** [comment]
@cltvchannel 
I think I read somewhere it would be available with v5 - maybe yetiforce team can confirm?

**Comment by bpabiszczak** [comment]
Yes, April/May.
