### ISSUE TITLE
[Discussion] How to create a module that shows an iframe?

### ISSUE THREAD

**Issue by easaw** [YetiForceCompany/YetiForceCRM#3967]
Using inspect on Chrome I created a quick example of what I want to achieve.

[http://prnt.sc/e3u6p4](http://prnt.sc/e3u6p4)

I put the YetiHost main website in an iframe and deleted everything else inside the div:

```
<div class="mainBody userInfoFooter">
<iframe src="http://yetiforce.com" width="100%" height="99%"></iframe>
</div>
```

How can I create a module (I assume with a php file and manual install) that displays the iframe rather than a module view?

I have tried looking at the Github page in the Summary
`/modules/Settings/Github`
But with no luck as I can't fully understand everything that is written there. As it's not a straight import, but obviously goes through a filter to blend in with the YF theme.

**Possibly using a tpl file?**

Thank you.

**Comment by liberox** [comment]
Hi, any luck with iframe?

**Comment by mariuszkrzaczkowski** [comment]
You need to create an extension type module and create one view

**Comment by vovpff** [comment]
@mariuszkrzaczkowski can you explain more detailed what you mean?

**Comment by mariuszkrzaczkowski** [comment]
> You need to create an extension type module and create one view
I think that is enough description :)
If you do not need this technical support

**Comment by vovpff** [comment]
@mariuszkrzaczkowski i need more detailed description

**Comment by KatarzynaUlichnowska** [comment]
We can do it only within the support hours: https://shop.yetiforce.com/en/17-support
