### ISSUE TITLE
[Question] 'Module does not contain default language (en_us).'

### ISSUE THREAD

**Issue by easaw** [YetiForceCompany/YetiForceCRM#3968]
When installing custom, or overwriting old modules. I often get

**Module does not contain default language (en_us).**

What does this **specifically** mean? Where would I put such files and which files are they?

I tried getting the relevant language file `ModuleName.php` from `/languages/en_us` from a newer version and putting it in the module's folder in a new:
`ModuleName/en_us/ModuleName.php`
folder, as well as in:
`ModuleName/languages/en_us/ModuleName.php`

Zipped them up, tried to install and nothing...

Thank you :)

**Comment by kpaulaha** [comment]
Do not know the language you use, but in our language we have to change the language files (also en-us) of custom modules to utf-8 (content, encoding) before installing.

**Comment by SkavenKF** [comment]
Is your ZIP File correct?
When you open, you must see the following:
![zip](https://cloud.githubusercontent.com/assets/10259801/22586366/a1e78c52-e9fc-11e6-946c-03a3e976ae3a.JPG)

**Comment by easaw** [comment]
@SkavenKF
Yes, I have the language folder, but what is the filename of the language file - I assumed it was ModuleName.php and then put that in the Languages folder?

Or is it simply en_us.php?

**Comment by SkavenKF** [comment]
you need a language folder, look at my zip structure, from my SkillDB (a simple Module)
![grafik](https://cloud.githubusercontent.com/assets/10259801/22602896/6a417418-ea45-11e6-81ea-05a14cfdf4cc.png)

"ZSkills_2016-07-26-1257_0" => ZIP File / folder
- "languages" => folder without files
-- "en_us" => folder
--- "ZSkill.php" => File with the translation of my module
- "modules" => folder without files
-- "ZSkill" => folder
--- "ZSkill.php" => File with module
- manifest.xml => file with informations about the module and db

**Comment by natpicone** [comment]
Try to parse the manifest.xml file through https://www.xmlvalidation.com.
Mine had some "bad" encodings which blocked the module import....
