### ISSUE TITLE
New Server issue

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3969]
Morning, I am running ver. 3.4.0. on a ubuntu server with 8gb ram 4 core processor using php7 with all modules and plugins attached.

PHP configuraton	/etc/php/7.0/apache2/php.ini
Logs	/var/www/html/yetiforce/cache/logs/phpError.log
CRM Local directory	/var/www/html/yetiforce

the only thing i cannot set is innodb_lock_wait_timeout = 600 i've tried in sql and php.ini

But im facing this issue when trying to change users details.

![userissue](https://cloud.githubusercontent.com/assets/22075161/22589338/b59c7064-ea01-11e6-91bc-956f7818236b.gif)

any help would be great. ( I Know its not on php 7 yet but having major issues with php 5.6.)

**Comment by vovpff** [comment]
@alextovey this is parameter of MySQL database. Lets check my.ini at line ~178

**Comment by vovpff** [comment]
@alextovey this is good parametes for MySQL
![image](https://cloud.githubusercontent.com/assets/8545791/22593543/1c4c4dc4-ea30-11e6-8b8e-6f02be042584.png)

**Comment by alextovey** [comment]
@vovpff theres no my.ini file on the server just did a locate my.ini

**Comment by alextovey** [comment]
@vovpff so its my.cnf but there is no lines of code in there. Just two which is commented out.

**Comment by alextovey** [comment]
Okay, so i've reverted to 5.6 and all the system checks out but still getting that error "There is no active transaction."

Any help would be great on this one please.

**Comment by alextovey** [comment]
@vovpff i've set it to your settings also and still the same.

**Comment by vovpff** [comment]
@alextovey  no idea. 
CRON enabled?

**Comment by alextovey** [comment]
@vovpff tried but it was the change path that got me....

**Comment by vovpff** [comment]
@alextovey what you mean?

**Comment by alextovey** [comment]
so when i run this manually i get this error.
`2017-02-05 10:45:30 | LBL_MARK_RECORDS_AS_REVIEWED - Not ready to run as the time to run again is not completed`

This happens to all of the records. so a bit lost.

**Comment by alextovey** [comment]
anyone? I've got the cron job working i think but yet I still get this error from the original? @bpabiszczak

**Comment by alextovey** [comment]
Ok resolved now by changing the sql from strict to normal.
