### ISSUE TITLE
[question] How to add "Add service" botton to GRN/GRN modules?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#3970]
There are no "Add service" near "Add product" botton for GRN/GDN modules. If record of module with advanced fields  converted by YF mapping tool to GRN/GDN there are all list items appears in table after mapping: products and services but no possibility to add service manually.

**Comment by mariuszkrzaczkowski** [comment]
Can you give some sample screenshots?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski for example this is screenshot from Invoice module from dev version
![image](https://user-images.githubusercontent.com/8545791/27425536-6cb93fa0-5741-11e7-99e2-e6c810e1a36e.png)
There are two buttons: add product and add service to line items.
I use YetiForce for simple stock management system and sometimes I need some additional lines what don't partisipate in product quantity calculation mechanism. Like some product what not added to product list as record by some reasons (for example very rare or exclusive product).
In my old vtiger stock version I used services as some fake ploduct line at Invoices.
Will be cool to have ability to add some fake lines or services to items line table for Logistics modules.

**Comment by mariuszkrzaczkowski** [comment]
Product comment can not be?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski comment related to some product what is participate in quantity calculation. There are neede some like Services or separation line with ability to add comment.

**Comment by mariuszkrzaczkowski** [comment]
You have an example
https://github.com/YetiForceCompany/YetiForceCRM/blob/409acbe42be3bb150832a83ba72221ca48000f98/install/install_schema/Base1.php#L4243

**Comment by vovpff** [comment]
@mariuszkrzaczkowski how I must change this line
`[1, 'name', 'LBL_ITEM_NAME', 'Name', 0, '', 0, 1, 0, '{"modules":["Products","Services"],"limit":" "}', 20],`
to get button?

**Comment by mariuszkrzaczkowski** [comment]
Yes  modules":["Products","**Services**"]

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks a lot for solution!
