### ISSUE TITLE
SalesOrder outside a oppertunity

### ISSUE THREAD

**Issue by infoTopcloudxl** [YetiForceCompany/YetiForceCRM#3971]
#### Issue
Is it posible to bypass the oppertunities part when creating a sales order? We run a few webshops and things are getting messy in the CRM, I remember that in the original Vtiger you could create a sales order without adding a oppertunity.

#### Actual Behavior
I can only add sales orders in a oppertunity

#### Expected Behavior
I would like to be able to create a sales order directly in the account section, without first the creation of a oppertunity.

**Comment by konadrian** [comment]
You have to login to admin account and next following the instructions from gif
![animation](https://cloud.githubusercontent.com/assets/3193498/22738510/038e7c5e-ee08-11e6-8c4e-e78cef2d5eac.gif)

**Comment by infoTopcloudxl** [comment]
Oke i followed the instructions, But now im not able to add a account to the Sales order, how to fix this?

**Comment by konadrian** [comment]
![animation](https://cloud.githubusercontent.com/assets/3193498/22741130/6ae5a06c-ee12-11e6-8333-7fa7a501597a.gif)

**Comment by infoTopcloudxl** [comment]
I dont see the option "Field type" in my backend @ this tab.

**Comment by nic86** [comment]
@infoTopcloudxl to active 'field type' set the value of 'CHANGE VISIBILITY' to true in this file:

[config/developer.php](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/developer.php#L11)
