### ISSUE TITLE
Probleme on delivery note

### ISSUE THREAD

**Issue by chocman45** [YetiForceCompany/YetiForceCRM#3972]
Hello, how can I do to remove the columns or change the column name of the products of the delivery note (pdf format)

**Comment by vovpff** [comment]
@chocman45 you can edit columns here: https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=IIDN by managing advanced blocks. To change colum name you need to change translation of column name or change ProductsTableNew specilal PDF function by yourself

**Comment by vovpff** [comment]
@mariuszkrzaczkowski it will be cool have ability to made differnt types of product tables without PHP programming experience.
For exaple now I use VT v6.4 with PDF Maker Pro module to make a lot of different types of tables.
This is table for default invoice:
![image](https://cloud.githubusercontent.com/assets/8545791/22649497/3e20aec8-ec8c-11e6-8847-32bf12d03bd7.png)
This is another one table what contains only products records with some tag:
![image](https://cloud.githubusercontent.com/assets/8545791/22649563/89c2b2a4-ec8c-11e6-8bad-89aae460e109.png)
Now for YF I can't reproduce same tables without experience or it takes a lot of time.

**Comment by mariuszkrzaczkowski** [comment]
Of course it would be cool, just let somebody pay for it :)
