### ISSUE TITLE
Cron issue - Task omitted and task timedout

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#3977]
Hello,

I got a cron issue with my Yetiforce server, the task CarDAV return a timeout and the task CalDAV return an endless scan.

There is my cron setup page :
![capture](https://cloud.githubusercontent.com/assets/1357727/22651911/c52160d2-ec84-11e6-941a-3f8c36f97971.PNG)

And the cron log file :
![image](https://cloud.githubusercontent.com/assets/1357727/22651630/0480abbc-ec84-11e6-8a9c-23aac049425a.png)

It seems to happened after the 3.4 update.

My environment is : Debian 8 / Apache 2.4 / PHP 5.6

Thank's !

**Comment by mariuszkrzaczkowski** [comment]
Wrongly you have set php.ini 
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by Raggazzoo** [comment]
Thank's for yout reactivity !

I can't see what's wrong in my setup, it works perfectly like this for 3 months ago...

Could you take a look at my phpinfo?
[phpinfo.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/755080/phpinfo.pdf)

The PHP NOTICE ROOT_DIRECTORY is set in php.ini? 

Thank you so much =)

**Comment by vovpff** [comment]
@Raggazzoo are you solved PHP NOTICE ROOT_DIRECTORY problem?
