### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by chocman45** [YetiForceCompany/YetiForceCRM#3979]
How i can delete user? Whene i delete i can not create the user again with the same email address

**Comment by rskrzypczak** [comment]
You have to completely remove the user from the database in order to create another one with the same email address.

P.S.
Next time at least let us know what CRM version you're using.
![image](https://cloud.githubusercontent.com/assets/10221999/22727673/727e8a88-edda-11e6-85db-0a9d8547c5d9.png)
