### ISSUE TITLE
[bug?] Error in Workflow expression

### ISSUE THREAD

**Issue by nkzach** [YetiForceCompany/YetiForceCRM#3980]
#### Issue

Error appears with most comparison operators "<", ">", "<=", ">=".
No problem with "==". 
No problem with Arithmetic Operators "+", "-", "*", "/".

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Latest GitDeveloper, 3.4
* Browser name and version: Chrome latest version
* Environment name and version: Yetiforce
* Operating System and version: Mac OS Siera

![2017-02-07 21_46_47](https://cloud.githubusercontent.com/assets/22010748/22708461/fb3e8f32-ed7e-11e6-8289-0de70e8fa37e.gif)

**Comment by nkzach** [comment]
@TomaszQr 
Sorry, not work
I try all comparison operators (now and "=="), without brackets, and the result of expression is null. No errors but null.

But if the expression has brackets the result is:
"Fatal error: Uncaught Error: Function name must be a string in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/com_vtiger_workflow/expression_engine/VTExpressionEvaluater.php:276 Stack trace: #0 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/com_vtiger_workflow/expression_engine/VTExpressionEvaluater.php(256): VTFieldExpressionEvaluater->exec(Object(VTExpressionTreeNode)) #1 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/com_vtiger_workflow/tasks/VTUpdateFieldsTask.php(54): VTFieldExpressionEvaluater->evaluate(Object(Products_Record_Model)) #2 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/com_vtiger_workflow/VTWorkflowManager.php(400): VTUpdateFieldsTask->doTask(Object(Products_Record_Model)) #3 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/handlers/Workflow.php(90): Workflow->performTasks(Object(Products_Record_Model)) #4 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendo in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/com_vtiger_workflow/expression_engine/VTExpressionEvaluater.php on line 276"

**Comment by TomaszQr** [comment]
Could you write expression which you tested?

**Comment by nkzach** [comment]
@TomaszQr

I created a custom field named "Test" in module "Products".
For update field "Test" firstly i tried  this expression "if qtyinstock < 1000 then 1 else 2 end" and the result was null. Same result with all comparison operators "==", "<" "<=" ">" ">=".
(Before your fixed action the operator "==" and only this one worked properly.)

Then i tried this  "if (qtyinstock < 1000) then 1 else 2 end" and the result was "Fatal error...."

By the way i finally found that there is another solution for that problem. The solution is that can be used two workflows using different conditions.
For example one workflow with  condition "Test less than 1000" and update field Test to 1.
Second workflow with  condition "Test greater than or equal to  1000" and update field Test to 2.

Thanks your support.

**Comment by TomaszQr** [comment]
Try this:
if qtyinstock < 1000 then '1' else '2' end

**Comment by nkzach** [comment]
@TomaszQr
Yes, it works perfectly!!!

Thank you very much.
