### ISSUE TITLE
[Question] PBX Module

### ISSUE THREAD

**Issue by easaw** [YetiForceCompany/YetiForceCRM#3981]
Any hope for a replacement PBX?

Here it says there will be, but isn't the current one, the same as the old one mentioned here?:
[https://github.com/YetiForceCompany/YetiForceCRM/issues/2059](https://github.com/YetiForceCompany/YetiForceCRM/issues/2059)

**Comment by ldgbc** [comment]
It is planned, but like many other Internal Todo list, Yetiforce put it on low priority until (1) customer request or (2) have sufficient manpower to add it.

Considering the changed between v3 and v4, I would expect PBX replacement sometime end of the year.
