### ISSUE TITLE
Cron job errors

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#3982]
Morning chaps.

My cron jobs are not running correctly. I'm running 3.4.1 yetiforce on ubuntu 16.06 with 4 core cpu and 8gb ram. all settings are correct. But this is the error from my cronjob output

monster-it@web:~$ sudo sh /var/www/html/yetiforce/cron/vtigercron.sh
---------------  2017-02-08 09:16:47 | Start CRON  ----------
2017-02-08 09:16:47 | Workflow - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | SendReminder - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | LBL_CURRENCY_UPDATE - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | Scheduled Import - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | ScheduleReports - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | MailScannerAction - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | MailScannerVerification - Start task
2017-02-08 09:16:47 | MailScannerVerification - End task (0.01 s)
2017-02-08 09:16:47 | MailScannerBind - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | CardDav - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | CalDav - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | Activity state - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | LBL_MULTI_REFERENCE_VALUE - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | LBL_CRMACTIVITY_DAYS - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | Assets Renewal - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | SoldServices Renewal - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | LBL_SEND_NOTIFICATIONS - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | RecordLabelUpdater - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | PrivilegesUpdater - Task omitted, it has not been finished during the last scanning
2017-02-08 09:16:47 | UpdaterRecordsCoordinates - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | LBL_ADDRESS_BOOCK - Not ready to run as the time to run again is not completed
2017-02-08 09:16:47 | LBL_MARK_RECORDS_AS_REVIEWED - Not ready to run as the time to run again is not completed

Any help will be great thank you.

**Comment by Raggazzoo** [comment]
Good morning !

I got the same issue #3977 ... My php.ini has been configured by the Yetiforce team so I don't think it is the problem.
If someone got an idea...

**Comment by alextovey** [comment]
AH okay, So after visiting the vtiger forum as it's similar in cron job output. This is working correctly (acccording to them) the cron should be set to every 5 mins. and it will output all.

Have you ran the job manually? sudo sh /var/www/html/yetiforce/cron/vtigercron.sh

and post input here for me :)

**Comment by Raggazzoo** [comment]
This is the output
![image](https://cloud.githubusercontent.com/assets/1357727/22778126/1436e218-eeb6-11e6-8aec-150c98c8918f.png)

I set my cronjobs to 5 minutes but it changes nothing.

I have seen two commits about Cron, maybe it is relative to our issue
![image](https://cloud.githubusercontent.com/assets/1357727/22778178/513d2ff0-eeb6-11e6-804d-83ad88b76bd0.png)

**Comment by alextovey** [comment]
@Raggazzoo right do this.
sudo updatedb
cd /usr/bin/
dir

then do a screen shot of the php folders please

**Comment by Raggazzoo** [comment]
Allright.

There is my output
[output.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/763286/output.txt)

Thank's !

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/3977
Wrongly you have set php.ini
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by mariuszkrzaczkowski** [comment]
Check https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65

**Comment by alextovey** [comment]
@Raggazzoo not sure what hes about. Okay so you need to locate your php core file. whats the o/s and version your using?

For instance i'm running ubuntu 16.06 and the php output is /usr/bin/php7.0.

You need to find the running php file for cron execution. is the system live?

`#******************************************************************************$
# The contents of this file are subject to the vtiger CRM Public License Versio$
# ("License"); You may not use this file except in compliance with the License
# The Original Code is:  vtiger CRM Open Source
# The Initial Developer of the Original Code is vtiger.
# Portions created by vtiger are Copyright (C) vtiger.
# All Rights Reserved.
#
# *****************************************************************************$

export VTIGERCRM_ROOTDIR=`dirname "$0"`/..
export USE_PHP=php
#export USE_PHP=/usr/local/php53/bin/php
export USE_PHP=/usr/bin/php7.0

cd $VTIGERCRM_ROOTDIR
# TO RUN ALL CORN JOBS
$USE_PHP -f cron/vtigercron.php
`

**Comment by alextovey** [comment]
thats my example for /var/www/html/yetiforce/cron/vtigercron.sh

So from your output I would change this line export USE_PHP=/usr/bin/php7.0
to export USE_PHP=/usr/bin/php5

and try running it manually again and let me know.

**Comment by Raggazzoo** [comment]
I have try to replace USE_PHP by /usr/bin/php5, reboot, and run vtigercron.sh.
It didn't change anything.

I got some errors in my php.ini...
![image](https://cloud.githubusercontent.com/assets/1357727/22780341/b6ec2740-eebe-11e6-98f6-6e7230cf99f3.png)
![image](https://cloud.githubusercontent.com/assets/1357727/22780367/c5114954-eebe-11e6-932c-e2fa44103af7.png)

I will try to resolve all.

**Comment by alextovey** [comment]
ah okay. so here you go. if you use nano type sudo nano /etc/php5/apache2/php.ini

then use ctrl + w to find and type display_errors hit enter and find that. if you want I can login via ssh if you pm me and i;ll sort it for you.

**Comment by Raggazzoo** [comment]
I really don't understand why this variable is set on because in my php.ini it is set off
![image](https://cloud.githubusercontent.com/assets/1357727/22780588/86015500-eebf-11e6-9cf2-990c28e1c7af.png)

**Comment by Raggazzoo** [comment]
It is the same for log_errors
![image](https://cloud.githubusercontent.com/assets/1357727/22780662/bd456ab0-eebf-11e6-8b03-425f8ee1f018.png)

**Comment by alextovey** [comment]
ah wrong php.ini you are editing.

**Comment by alextovey** [comment]
create a info.php and place the code in it.

`<?php

// Show all information, defaults to INFO_ALL
phpinfo();

?>`

Then visit the url/info.php and give me a screen shot :)

**Comment by alextovey** [comment]
just need this the top bit as a screen shot

**Comment by Raggazzoo** [comment]
There it is
![image](https://cloud.githubusercontent.com/assets/1357727/22780899/a3936972-eec0-11e6-8e2c-60d97c92eb8a.png)

I made a pdf with the all configuration.
[phpinfo.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/763456/phpinfo.pdf)

Thank you so much !

**Comment by alextovey** [comment]
give me this output please
`php -i | grep 'Configuration File'`

**Comment by mariuszkrzaczkowski** [comment]
You must change php config for cron [CLI]
http://stackoverflow.com/questions/3057110/where-can-i-find-the-php-ini-for-php-cli

**Comment by alextovey** [comment]
its already set, he's having issues with the php.ini

**Comment by Raggazzoo** [comment]
Sorry I went to lunch =)
There it is the output of php -i | grep 'Configuration File'
![image](https://cloud.githubusercontent.com/assets/1357727/22785109/389495e8-eed3-11e6-82de-560c00ded7e9.png)

**Comment by alextovey** [comment]
Okay can you send me the php.ini file in that path and i'll alter it for you and send back. the INNODB function wont change as mysql never let's it change now it is stuck at 50. @Raggazzoo

**Comment by Raggazzoo** [comment]
Okay there is the php.ini from /etc/php5/cli
[php.ini.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/763796/php.ini.txt)

Thank's =)

**Comment by alextovey** [comment]
@Raggazzoo  give me an hour as got to pop out now but will be back in 45 mins.

**Comment by alextovey** [comment]
try this. 
[php.ini.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/763820/php.ini.txt)

**Comment by Raggazzoo** [comment]
Thank you so much I try this

**Comment by Raggazzoo** [comment]
It is OK when I manually launch the script but not in Yetiforce
![image](https://cloud.githubusercontent.com/assets/1357727/22789369/0e9922ee-eee3-11e6-81c1-a5010340d899.png)
![image](https://cloud.githubusercontent.com/assets/1357727/22789832/9040c8dc-eee4-11e6-8b12-f243a865b75e.png)

**Comment by alextovey** [comment]
make sure your sql table is not strict

**Comment by Raggazzoo** [comment]
I added sql_mode="" at the end of my.cnf and reboot the server but this is not very effective...
![image](https://cloud.githubusercontent.com/assets/1357727/22790627/1f1c95fc-eee7-11e6-9988-c02a4509749c.png)

The php.ini isn't loaded in Yetiforce conf.
![image](https://cloud.githubusercontent.com/assets/1357727/22790542/d33592d8-eee6-11e6-9e91-084e7ac37fc5.png)

**Comment by alextovey** [comment]
is this a fresh install of yetiforce?

**Comment by Raggazzoo** [comment]
No, I installed a 3.2.90 at first, then I update it to 3.4.21
![image](https://cloud.githubusercontent.com/assets/1357727/22792082/ca369858-eeeb-11e6-8bf1-0d20d671f628.png)

The issue seems to appear after the 3.4.21

**Comment by alextovey** [comment]
We do resell VPS Servers for Yetiforce. is it a production or live server?

**Comment by Raggazzoo** [comment]
This is the production server that's why I'm worried =(

**Comment by alextovey** [comment]
oh :S right. What os you running for it @Raggazzoo

**Comment by nic86** [comment]
check hidden file .htaccess in the yeti root directory

**Comment by alextovey** [comment]
its the php.ini file @nic86 its not reading it correctly.

**Comment by nic86** [comment]
the htaccess can overwrite directive in php.ini

**Comment by alextovey** [comment]
@Raggazzoo post your .htaccess file up then we'll take a look

**Comment by nic86** [comment]
`[yeti htacces](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/.htaccess)`

uncomment this line:
```
#php_value	max_execution_time			600
#php_value	max_input_time				600
```

**Comment by nic86** [comment]
and add 
php_flag mbstring.func_overload off

**Comment by Raggazzoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1357727/22792644/be9c2560-eeed-11e6-9669-097f26b5271d.png)
![image](https://cloud.githubusercontent.com/assets/1357727/22792703/eb036a0a-eeed-11e6-9142-bb200dcfa54a.png)
![image](https://cloud.githubusercontent.com/assets/1357727/22792728/0067981c-eeee-11e6-8a04-0ae15bd21bb2.png)

Okay I will try that.

Thank you

**Comment by nic86** [comment]
from apache doc:
https://httpd.apache.org/docs/2.4/howto/htaccess.html

add this directive to your apache conf
<Directory "/www/htdocs">
    AllowOverride All
</Directory>

"/www/htdocs" = your yeti root

**Comment by Raggazzoo** [comment]
I have edit the .htacces, it's OK for display_errors and log_errors but not for mbstring.func_overload.
![image](https://cloud.githubusercontent.com/assets/1357727/22793124/37c65072-eeef-11e6-8629-c843725487e4.png)

I have already add the AllowOverride
![capture](https://cloud.githubusercontent.com/assets/1357727/22793050/f86dad30-eeee-11e6-9d0d-1e4ded695bbd.PNG)

**Comment by nic86** [comment]
the page Software configuration > Logs > Server configuration > Start

present the value from /etc/php5/apache/php.ini and all overwrite from htacces

This page has nothing to do with cron and /etc/php5/cli/php.ini

**Comment by Raggazzoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1357727/22793401/0634b9d0-eef0-11e6-9432-bd6c2020fd99.png)
![image](https://cloud.githubusercontent.com/assets/1357727/22793426/152c92aa-eef0-11e6-9eaa-25aa6eab4fc4.png)
![image](https://cloud.githubusercontent.com/assets/1357727/22793461/31e36e1e-eef0-11e6-8b8f-d9bcc959858c.png)

There is my php.ini from /etc/php5/apache2
[php.ini.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/764351/php.ini.txt)

What do you mean by All Overwrite fromhtaccess, all .htacces of Yetiforce in each folder?

**Comment by nic86** [comment]
to set inno_db_look_wait_timeout without restart mysql
http://stackoverflow.com/questions/28735473/innodb-lock-wait-timeout-increase-timeout

instead write the directive in my.cnf and restart mysql

**Comment by nic86** [comment]
to func_overload directive try:

**php_value** mbstring.func_overload 0

**Comment by alextovey** [comment]
See i wouldn't use .htacccess to run it. I would run all from php.ini file as the server becomes unstable when overloading the .htaccess file. But Not my best subject is the .htaccess.

Hope fully nic can talk you through it.

**Comment by Raggazzoo** [comment]
When I try to setup the innodb_lock_wait_timeout it returns NULL
![image](https://cloud.githubusercontent.com/assets/1357727/22794613/09643dca-eef4-11e6-8b22-8b5231cc72e7.png)

I set the php_value mbstring.func_overload to 0 and restart apache but nothing change in Yetiforce.
![image](https://cloud.githubusercontent.com/assets/1357727/22794432/7a367a5a-eef3-11e6-9f6e-05ba97e0a8f9.png)

**Comment by alextovey** [comment]
From 5.6 onwards for mysql it's locked you can only set the session timeout but have to enable the module first in order to see it.

**Comment by Raggazzoo** [comment]
Thank you so much Alex, I'm so grateful of you help =)

**Comment by Raggazzoo** [comment]
Ok everything is fine in my Server Configuration page aside mbstring.func_overload

**Comment by nic86** [comment]
> See i wouldn't use .htacccess to run it. I would run all from php.ini file as the server becomes unstable when overloading the .htaccess file. But Not my best subject is the .htaccess.

you can disable .htaccess and set all directive in php.ini
```
<Directory "/www/htdocs">
    AllowOverride None
</Directory>
```

probably .htaccess slow the server, but from my experience I have not yet noticed them

**Comment by Raggazzoo** [comment]
As you asked @nic86, there is each .htacces file part1
[htacces_files.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/764497/htacces_files.zip)

**Comment by Raggazzoo** [comment]
Do you need all of these?
![image](https://cloud.githubusercontent.com/assets/1357727/22795464/157b01b8-eef7-11e6-9d53-d83def2602bb.png)

**Comment by nic86** [comment]
> Do you need all of these?
i think so

> You should avoid using .htaccess files completely if you have access to httpd main server config file. Using .htaccess files slows down your Apache http server. Any directive that you can include in a .htaccess file is better set in a Directory block, as it will have the same effect with better performance.

if you have access to httpd main server you can rewrite all htaccess in the directory block
otherwise you keep active .htaccess

**Comment by Raggazzoo** [comment]
Ok I'm lost...

**Comment by mariuszkrzaczkowski** [comment]
we just updated the requirements https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by Raggazzoo** [comment]
I installed the 3.4.1427 and it's OK thank's for everything
