### ISSUE TITLE
Accounts colour coding 

### ISSUE THREAD

**Issue by vinci4352** [YetiForceCompany/YetiForceCRM#3983]
#### Issue
How to apply colour coding to account as shown in the example 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
Here you have an example, how you can color list of records 
![animation](https://cloud.githubusercontent.com/assets/3193498/22736175/47765488-edfd-11e6-8271-05a7a1a08135.gif)
