### ISSUE TITLE
[Question] Export with related information.

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#3984]
I'm interested in Exporting information from related to module. from the record. To explain what I mean, please see example below:

1. Contact: John Smith, is a Member of: ABC Company
2. ABC Company is an Account/Company/Vendor.
3. ABC Company's address is 100 Road, City, Country.

If I export John Smith, it will only only show, "John Smith, ABC Company"
What I want is,
"John Smith, ABC Company,  100 Road, City, Country"

Is there anyway to do that? This is one example of it application,  for example, I can exact the Company Phone or Primary email.

Alternative a "related to: contact" field call Emergency. I could export (whether it to PDF, Excel, Report) their Emergency Contact Phone Number rather than just name.

Currently I know it is "semi-possible" using the "Search Configuration", "UIType" in particular. Where it display extra field rather than the default First Name Last Name.

#### Your Environment

* YetiForce Version used 3.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

update: rewording and making it more clear.

**Comment by lcuevastodoit** [comment]
Hi, we think here the same thing about exporting the related info, example: If we need to export products, we want to get the pricebook list related too at least, Is there anyway to do that?

**Comment by waran70** [comment]
I wish Stefan Warnat can get here with his WorkflowDesigner. Many lives will get better :/

**Comment by mariuszkrzaczkowski** [comment]
@ldgbc 
You can do without a problem with the report

@waran70 
Why you need a WorkflowDesigner in yeti

**Comment by waran70** [comment]
Mariusz, many of us comparing YF PDF generator with VT PDFMaker. I believe you understand that here is fundamental differences in end user experience and usability. Obviously everything can be done with programming, but there are many cases where easy access to GUI functions (such as we can observe it in PDF Maker)  are crucial for the comfort, speed and again overall experience. I wish we can find the way to re-develop this module, or convince you to write paid more advanced version of this module.

**Comment by mariuszkrzaczkowski** [comment]
All functionality of the PDF module has been ordered by our customers, you can freely expand it and I agree with you that it only costs it. Describe what you are missing in the new application, we will add it to the waiting queue for execution.
Maybe someone will order it as well as you describe what you can add.

**Comment by waran70** [comment]
Related blocks (so called in PDFMaker) missing - it gives opportunity to print out all related to "leading" module records in the form of list (with use of filters of course)
It is crucial function to deal easily with various reports without calling programmer for each report user wanna create.
Simply printing out Account and all related Contacts should be easy to achieve....

**Comment by mariuszkrzaczkowski** [comment]
I added new features to the parser text, the ability to list related records. See here
https://github.com/YetiForceCompany/YetiForceCRM/commit/c5a78668fd098ef59d619ecf6cdeafc2e9a4954f
List all records from the system:
https://github.com/YetiForceCompany/YetiForceCRM/commit/75f2b92c622f9da17e32219f0d60e568e6d9aa17
Here are some examples:
$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]|)$
$(recordsList : Contacts|||All)$
$(recordsList : Contacts)$

parameters: ModuleName|Columns|Conditions|CustomViewIdOrName|Limit
