### ISSUE TITLE
Roles and user

### ISSUE THREAD

**Issue by chocman45** [YetiForceCompany/YetiForceCRM#3987]
Hi, I would like to create a user but he should not have access to modules (should not show up) so he will just have the reader alone on parts. How to do?

**Comment by PercyP** [comment]
Hi,

if you go to the administrator/configration section then look under Permissions, you will see lots of options for setting access levels. There is also one for modules.

**Comment by konadrian** [comment]
You have to create new profile with new permissions, assign profile to role and connect role with the user
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/22929847/f7b3dfd6-f2bd-11e6-9e3a-472f750efa9b.png)
