### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#3989]
We noticed that the French language in the system is no longer being improved, some modules are entirely in English. 

If anybody wants to consistently and regularly work on the translations please let us know ASAP, because we are about to release version 4.0, and if nobody wants to contribute to the French translation we will have to remove it from the system.

**Comment by Raggazzoo** [comment]
Hi Paula,

I can do it but I need time for that.
I already done our own translation but a lot of fields are translate for our business.

Can I send you my translate files to you to take a look at it?

Thank's

**Comment by paula-w** [comment]
Sure, we'll get in touch with you on Monday.

**Comment by paula-w** [comment]
Hello @Raggazzoo, please send us a pull request with your translations.

**Comment by Delaballe85** [comment]
Hello Paula

I send you the translation by mail info@yetiforce.com

Regards,

**Comment by paula-w** [comment]
Without a signed CLA we won't be able to add any translations to the system.
