### ISSUE TITLE
[Bug] [ver. 3.4.1801] Asset Status Permission Denied

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#3991]
#### Issue
If the Assets status is set, I cannot make any change to the Assets.

#### Actual Behavior
Permission Denied. Contact Administration

#### Expected Behavior
Allow user or Admin account/role to make change.

#### How to trigger the error
1. https://gitdeveloper.yetiforce.com/index.php
2. https://gitdeveloper.yetiforce.com/index.php?module=Assets&view=Edit&record=964
2a. Or Database > Assets > Choose any asset > Full Edit
3. Under status, change it from Draft to Accepted
4. Press Save
5. Now you are in the Detail View. 
6. Click Full Edit. 

The following error appear.

`Permission denied

You don't have the permissions required to view/edit this record. Contact the administrator if you should have the permission to view it.

Home page
`

`#0 include/main/WebUI.php(78): Vtiger_Edit_View->checkPermission(Object(Vtiger_Request))
#1 include/main/WebUI.php(214): Vtiger_WebUI->triggerCheckPermission(Object(Vtiger_Edit_View), Object(Vtiger_Request))
#2 index.php(24): Vtiger_WebUI->process(Object(Vtiger_Request))
#3 {main}`

#### Your Environment
* YetiForce Version used:  ver. 3.4.1798
* Browser name and version: Firefox 51
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
It's not an error. In module files you have $lockFields variable which menas block edit view, delete action on this record if a field in record will have a specific value In this case var $lockField containst your status value.
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Assets/Assets.php#L17
