### ISSUE TITLE
Error on Importing data in modules

### ISSUE THREAD

**Issue by zeostravelling** [YetiForceCompany/YetiForceCRM#3992]
When importing data in any module I get this error (image) and none of the data is imported.

![sem titulo-3](https://cloud.githubusercontent.com/assets/25207269/22826528/14bf11a0-ef7a-11e6-8549-416820c9a0aa.png)

The page keeps reloading itself and nothing happens. I contacted my host support (Kualo) and they didn't find anything wrong on the server side. Here is the logs but was not much help as it just repeats the following:

2017-02-09 17:36:42.7913 [error] - Error => /home/zeostrav/public_html/z8/modules/Import/views/Main.php:96
2017-02-09 17:36:42.4257 [info][application] - $_GET = [
'module' => 'Cities'
'view' => 'Import'
]

$_COOKIE = [
'PHPSESSID' => '17ad87b589cf0310cb5f'
]

$_SESSION = [
'__HTTP_Session_Info' => 2
'language' => ''
'layout' => ''
'AUTHUSERID' => '9'
'authenticated_user_id' => '9'
'app_unique_key' => '79a25928c784dab0623247c9bd41228d'
'authenticated_user_language' => 'pt_br'
'user_name' => 'kualo'
'full_user_name' => 'Support Kualo'
'lvs' => [
'Cities' => [
'sortby' => ''
'sorder' => ''
'viewname' => '108'
108 => [
'start' => '1'
]
]
]
'Cities_listquery' => 'SELECT vtiger_cities.city, vtiger_cities.number, vtiger_crmentity.createdtime, vtiger_crmentity.smownerid, vtiger_cities.citiesid FROM vtiger_cities INNER JOIN vtiger_crmentity ON vtiger_cities.citiesid = vtiger_crmentity.crmid WHERE vtiger_crmentity.deleted=0'
'PHPDEBUGBAR_STACK_DATA' => []

No other error logs were generated on the server for this.
Any clue?

**Comment by ldgbc** [comment]
Wow, 10,000 cities is quite many. I suggest you test it with a few first. Say 10 or so and see if that is any better.

Secondly, you create a module called "Cities" right? Is this an issue only for this custom module or for all module? For example: Contacts or Account (where Yeti probably most supported at the moment).

Putting that aside. may I inquire on what is are these "Cities" information? Just a general answer if you worry about privacy. I'm still trying to make use of CRM and to be honest, with the default setup, most of the module is the same with little differences.

**Comment by zeostravelling** [comment]
@ldgbc I split the file into 1,000 cities each and it worked. Files with more than 1,000 records doesn't work.

At the end there is still a error message: (after import process complete)

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Vtiger_Import_View' does not have a method 'continueImport' in /home/zeostrav/public_html/z8/include/runtime/Controller.php on line 89

I noticed also that the the error occur when the file has more than 1,000 records. Looks like the system tries to schedule the import to start within 15 minutes but you can click OK and wait forever  that nothing happens.

![sem titulo-1](https://cloud.githubusercontent.com/assets/25207269/22834101/35e617cc-ef9b-11e6-93b2-c03c2c3616e6.jpg)

For me it's a problem to keep splitting files to import because it's wasted time, don't you agree?

Can it be a cronjob problem? Because of the schedulling?

**Comment by zeostravelling** [comment]
The file contains only the names and states of cities of Brazil.

![image](https://cloud.githubusercontent.com/assets/25207269/22834369/08f606d6-ef9c-11e6-8219-7b03180156ec.png)

**Comment by dkostya** [comment]
I have the same error.
Yetiforce version 3.4.21
The problem appears when importing >500 Accounts.
I think it is related to the planned imports.
At the same time, the import process occurs without problems.
But in the final of import, I do not see any messages about how to import completed and passed it to complete or cancel.
Sorry for my English
