### ISSUE TITLE
Probleme on buton for delivery note

### ISSUE THREAD

**Issue by chocman45** [YetiForceCompany/YetiForceCRM#3995]
Hello, after creat the user on the CRM; the user can creat a delivery note but he cant show the bouton for download the delivery note.

![image](https://cloud.githubusercontent.com/assets/25324706/22844331/a3681f4a-efd5-11e6-99c1-e1da97b996f9.png)

**Comment by vovpff** [comment]
@chocman45 for functionality you need to activate cron

**Comment by chocman45** [comment]
@vovpff how i can activate cron?

**Comment by WalterLuis** [comment]
try this
https://yetiforce.com/en/administrator-documentation/panel/cron/150-enable-cron.html
