### ISSUE TITLE
Update from 3.4.1427_to_3.4.1780_v1 does not install

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#3996]
#### Issue
I have successfully updated 3.4.0_to_3.4.1427_v2 and then went on to run the second update from 3.4.1427_to_3.4.1780_v1 and it failed.

#### Actual Behavior
1. I go to Logs-Updates and upload the update package: from 3.4.1427_to_3.4.1780_v1
2. I see the update notes and accept the licence terms
3. I can see the package uploading
4. It throws me right out of the crm and goes to my main domain url (minus yetiforcecrm)
5. I log back in and it is still displaying 3.4.1427 as the version in the footer and in the Logs-Updates, also no changes have been made to the CRM

#### Expected Behavior
For the new update to work like the previous version I just did.

#### How to trigger the error
Install first update then try to install second update

#### Your Environment

* YetiForce Version used: 3.4.1427 
* Browser name and version: Chrome 
* Environment name and version: Windows 10
* Operating System and version:

Why would the first update be successful and the second fail? I haven't changed a single thing.

Kind regards

**Comment by ldgbc** [comment]
Hi @PercyP Good to see you again. Saw your post and I thought I give updating a try. I don't know what was changed in 1427_v2 (compared to v1) but the update worked on a fresh install.

I got a Internal error 500 pages when I update it to v1780_v1 like you did (hopefully v2 fixed it again). Anyway I check Error Logs and saw this

`[Mon Feb 13 04:50:53 2017] [error] [client (my IP address] SoftException in Application.cpp:313: File "/home4/(username)/public_html/(websitename).com/cache/updates/init2.php" is writeable by group, referer: http://(websitename).com/`

So I went to my File Manager, went to that path and look for init2.php, I saw that file along with a few others was with Permission 7 7 5, which is meant for Folder only. So I changed it to 6 6 4. Refresh my website with the domain name only so it worked. The version is still v1427 though, so the update fail but at least my website didn't die.

Next I try update again. Same thing happen (500 internal error). I tried refreshing the page right before I click "Accept" but these files doesn't appear until you click Accept.

![yetiforce update package 3 4 1427_to_3 4 1780_v1 failed](https://cloud.githubusercontent.com/assets/1805303/22880915/2f846d94-f238-11e6-8f6a-c0563c75aba8.jpg)

Next I'll trying FTP/Extracting Update files and see if that work.
Anyway wish me luck. Going to try v1427 update on my Live server.

**Comment by SkavenKF** [comment]
Hi, the update v1427 v2 works for me too (you can ignore the Hotfixes for Currency Bug 😄 ). No error with the v2 version.
![grafik](https://cloud.githubusercontent.com/assets/10259801/22882722/cc80c878-f1ec-11e6-8475-372f01b57cfd.png)

But with the 3.4.1427_to_3.4.1780_v1 update, i become a white screen 😞

**Comment by PercyP** [comment]
@ldgbc 

hello again to you too :O) thanks for posting your tests - it is really helpful. I will give it another go bearing in mind what you have done. With regards to Roundcube, I had some custom work done by yetiforce as wanted a fresher looking email interface, so but some new roundcube themes and had them integrated. I did try running the roundcube download and it didn't work, basically when I clicked on the email icon in the CRM it opened up the Home page of my actual website inside the yetiforce crm window. So I reverted back to my old version of yetiforce, then ran the first update again so I got all my old roundcube settings back. I don't think I will install the roundcube updates going forward for this very reason. 

I was also thinking of maybe taking a copy of my crm and installing it on a shared hosting account to see if that update goes through - then I will definitely know I suppose, if it is my server settings that are at fault. However, It doesn't make sense that the first one went through fine then the second update broke. 

Is your working on the latest release now? 

Well done for persevering - it will hopefully pay off with all the things you have learnt!

**Comment by ldgbc** [comment]
With the 1427 there is less bug and more thing are working now (and new option/feature). So I'm going through the menu one by one. Anyway I noticed that there are new PHP/Server requirement and recommendation configuration.

So you might want to change that and maybe it might help. It too late for me to try now, I'm way pass my bedtime.

See: /index.php?parent=Settings&module=ConfReport&view=Index

**Comment by PercyP** [comment]
@ldgbc 

I worked through some of those yesterday but cannot find the session.cookie_httponly in my server settings (I am looking in both EasyApache settings and also the PHP configuration settings (Advanced mode) but this isn't there and not yet sure where else to look for it. 

Here are screen shots of my server configuration - The file/folder permissions settings have no errors with all showing as Allowed:

![1](https://cloud.githubusercontent.com/assets/10598886/22886416/ae8e2bea-f1f5-11e6-8c3d-36420c3a525f.png)
![2](https://cloud.githubusercontent.com/assets/10598886/22886418/ae9023dc-f1f5-11e6-8f1a-984c67c23508.png)
![3](https://cloud.githubusercontent.com/assets/10598886/22886419/ae9486f2-f1f5-11e6-80eb-9c355f937815.png)
![sysincorrect](https://cloud.githubusercontent.com/assets/10598886/22886417/ae8f20f4-f1f5-11e6-993c-4123d9dfab35.png)

**Comment by ldgbc** [comment]
@PercyP You have to open up the "php.ini" in your server, and add this line somewhere
session.cookie_httponly = 1
That will enable it, it not there by default I think. I did a Ctrl+F and it wasn't there. However adding it will enable it (I assume).

**Comment by PercyP** [comment]
Just to say, I was never able to upgrade. I took @ldgbc advice and added session.cookie_httponly = 1 but it had no effect. 

In addition, on the 3.4.1427 version, I could no longer create new menu links as it crashed the system. In the end I decided to do a fresh install of version 4 and rebuilt all my modules and new fields etc. Then I go to create a new menu link and system crashes again! Will post the details under a new thread.

**Comment by ldgbc** [comment]
That session.cookie thing seem to only for Login issue. Those crashes would usually mean an incomplete installation or a missing requirement, such as Library, Permissions or Files. Looking forward to install-able version in the future.

**Comment by mariuszkrzaczkowski** [comment]
check 3.4.1427_to_4.0.0_v3.zip

**Comment by SkavenKF** [comment]
@mariuszkrzaczkowski: i checked the new upgrade file with the following result:
- Upgrade from 3.4.21 to 3.4.1427 => success
- Upgrade from 3.4.1427 to 4.0.0 => white screen
- after a Browserefresh (F5) i see 3.4.1427 (this was new)
- second try to upgrade from 3.4.1427 to 4.0.0 => success 😃 

and the best, i don't change the server parameters .... 😉

**Comment by mariuszkrzaczkowski** [comment]
Enable full logs and add them to githuba
I suppose there is a problem with adding fields.
