### ISSUE TITLE
Probleme on user role

### ISSUE THREAD

**Issue by chocman45** [YetiForceCompany/YetiForceCRM#3997]
Hello, after having created several users, users arrive have created vouchers of deliveries but they are unable to download the pdf file (the button does not appear for their account but for the administrator account yes)

**Comment by konadrian** [comment]
Have you changed the permissions in pdf?
![bez tytulu](https://cloud.githubusercontent.com/assets/3193498/22925594/9a131914-f2a9-11e6-8b46-2a12f3cb4d04.png)
