### ISSUE TITLE
Update on YetiForce 4.0 LTS

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#3998]
Hi... what is the expected date of releasing YetiForce 4.0 LTS?
Will it be together with Customer Portal?

Cheers

**Comment by bpabiszczak** [comment]
YetiForce 4.0 LTS = 2017-02-13 = 99,99%
CP = YF 4.1

**Comment by waran70** [comment]
I guess CP will be working with LTS well?

**Comment by bpabiszczak** [comment]
YetiForce 4.0 LTS = 2017-02-14 = 100% ;)
CP = YF 4.1 = will be working with LTS version.
