### ISSUE TITLE
What does bookkeeping module do actually?

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#3999]
Should not it be called "Journal" ? If so, we have here incomplete information.
Journal gathers day t day business operations events and should allow posting it to ledger - in this case Payments In and Payments Out.
Would be convenient to think of some sort of Accounting module, or maybe extension what allowing standard accounting operations (including double entry) - see Odoo
If Yetiforce like idea we could gather some accountants here to discuss options.

**Comment by waran70** [comment]
Financial records management, stability and clarity in ERP-like Yetiforce should be improved.
Sure Odoo is a good example. Enough to create basic Accounting system in line with some international standards (everybody can extend it anyway).  Transactions booking method and some general ledger accounts at first would be good start. Anyone else got some experience here?

**Comment by bpabiszczak** [comment]
Right now this module doesn’t do anything, it’s only a starting point for the bookkeeping process, and has the same role as the sales opportunity has in the sales process. This module will be responsible for controlling whether everything that was supposed to be done has actually been done. Ultimately the system will be expanded by ERP elements, but it requires time. Maybe in 3 – 6 months we can start working on it.

The need for ERP slowly arises in our company, so it might be the right time to develop this feature.
