### ISSUE TITLE
Leads - Salutation & firstname fields

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#400]
Hi I saw in the latest version that you added a B2B/B2C field and the company field is back. That is great but if you use the system in B2C mode like we do, we need the satutation and firstname fields as well.

In the version 1.3  I changed the 'vtiger_field' table to dispay the satutaion and firstname fields but only the firstname is shown.

It would be good to have the option to easily dispaly or hide this fields, dependent on the B2B/B2C mode, in the settings pages or at least a short discription on how to do it in the documentation

**Comment by bpabiszczak** [comment]
B2C has nothing in common with a first name and a surname. YetiForce allows to enter companies as well as private individuals, I suggest you to read our documentation:

https://yetiforce.com/en/business-processes/marketing-process.html

The logic of fields will be changed in v.1.4. and later there will be v.2.0 which will have all the processes organized and there will be a full documentation. Version 2.0 will be released in mid May and will be marked as a stable version. We designed the processes in such a way that there will be no need to hide fields; entering a first name and a surname doesn’t seem to be optimal in the Leads module [might add an infinite number of contacts]. I suggest you to read the articles one more time.
