### ISSUE TITLE
[Discussion] PHP IDE

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#4000]
I open a discussion to talk about our favorite IDE for PHP.
It would be interesting to share ideas for improving our programming and debugging skills.
I work in gnu-linux environment with debian 8 Distribution. My personal configuration is:

- (Shell) Vim-gnome + [PHP QA Tools](https://github.com/joonty/vim-phpqa) (Mess Detector and Codesniffer) + [vdebug](https://github.com/joonty/vdebug) (DBGP debugger for Xdebug) + Ctrl-P + EasyMotion + SuperTab + exuberant-ctags

- (GUI) Eclipse + PDT(php development tools) + RSE(remote system explorer) + Xdebug

these are some links from which I was inspired:
[vim packages](http://askubuntu.com/questions/281886/what-are-the-differences-between-the-different-vim-packages-available-in-ubuntu?answertab=active#tab-top)
[vim configuration](http://blog.joncairns.com/2012/05/using-vim-as-a-php-ide/)
[xdebug installation](https://xdebug.org/docs/install)

I hope will be helpful for someone, any suggestions would be appreciated.

**Comment by bpabiszczak** [comment]
Notepad :P

**Comment by nic86** [comment]
I hope it is at least ++ ;)

**Comment by acidhunter** [comment]
phpstorm+xdebug

**Comment by kabelo38** [comment]
Sublime

**Comment by mariuszkrzaczkowski** [comment]
NetBeans + xdebug + Google Chrome NetBeans Connector
