### ISSUE TITLE
Office 365 and yetiforce

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4002]
Morning guys and Gals,

Is there a specific way to setup the office 365 mailboxes on yetiforce. This is my current settings however it says "Connect to IMAP server failed".
![email](https://cloud.githubusercontent.com/assets/22075161/22880071/abe5ca5a-f1d8-11e6-8837-b00d4ce82b6c.png)
![email2](https://cloud.githubusercontent.com/assets/22075161/22880072/abe75bea-f1d8-11e6-8b55-b27ca42ece49.png)

any help will be great.

**Comment by ldgbc** [comment]
Can't help you. However looking at this page and your screenshot, you might have gotten the Port wrong.

Please see: https://support.office.com/en-us/article/POP-and-IMAP-settings-for-Outlook-Office-365-for-business-7fc677eb-2491-4cbc-8153-8e7113525f6c

**Comment by acidhunter** [comment]
we got a similar ticket some months before

edit your config.inc.php to match your sender adress

**Comment by alextovey** [comment]
I did and it matches.

**Comment by metastatic** [comment]
You IMAP settings are wrong. The correct settings are as follows-:

Name of IMAP server: outlook.office365.com
Port used to connect to IMAP: 993
Name of SMTP server: smtp.office365.com
SMTP Port : 587

You can confirm this by logging into Office 365 > Mail Settings > Pop and IMAP

**Comment by alextovey** [comment]
Still notworking can you send me a screen shot please

**Comment by alextovey** [comment]
Ok this is the screen shots of how to get it to work for anyone looking in the future.
![roundcube settings](https://cloud.githubusercontent.com/assets/22075161/24039300/9732d7be-0afc-11e7-8ffc-9a30377d703b.GIF)
![smtpconfig](https://cloud.githubusercontent.com/assets/22075161/24039301/973506e2-0afc-11e7-81f2-21d416ef2f56.GIF)
