### ISSUE TITLE
[Question] OpenStreetMap Module - Default Zoom Level

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#4003]
#### Issue
The default zoom level when you click "Map" is too high.

#### Actual Behavior
Map zoom level is only appropriate for State/Country size.

#### Expected Behavior
Map should zoom in within the Suburb/District/City range.

#### How to trigger the error
1. Open Contact.
2. Add contact's address if not already with "Home/Office" address
3. Open Contact.
4. Click Map
5. Map by default is Zoom at level 10(?), which you can see other State of the country.

#### Your Environment
* YetiForce Version used: ver. 3.4.1427
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by ldgbc** [comment]
I found this code:
 YetiForceCRM/layouts/basic/modules/OpenStreetMap/resources/Map.js
`	registerMap: function (startCoordinate, startZoom) {`

There a few line with StartZoom, the = I assume higher = closer to map. Currently it seem to be set at 2 and 6.
but not sure how to change it.

**Comment by merckaa** [comment]
Account details don't use this script itself, it uses a minifyed version in the same folder called Map.min.js

You can bypass this, by deleting the minifyed version of the script or just make a copy and rename Map.js to Map.min.js **with your changes to startzoom parameter.**

This should work, but it was not tested extensively, I'm using this hack right now and I'll post if something go wrong.

**Comment by mariuszkrzaczkowski** [comment]
Does the problem occur in the latest development release?
