### ISSUE TITLE
Getting 3 fields from one module when choosing one field in the other

### ISSUE THREAD

**Issue by zeostravelling** [YetiForceCompany/YetiForceCRM#4005]
I created a module called CITIES and imported all brazilian cities (with state, country, continent).

When I add a CONTACT I get the city from CITIES module.

Is there a way to CONTACT module automatic gets state, country and continent when I choose a city from the CITIES module?

I tried every kind of module relations and didn't find a solution for that.

**Comment by vovpff** [comment]
@zeostravelling try to find at this git some gifs with update field examples

**Comment by nic86** [comment]
when you create a field 1: m you can set which fields are displayed from the related records:

Software configuration > Search and filters > Search - Configuration > Start

-->Mains column for a module(including a label for uitype 10)

**Comment by ldgbc** [comment]
I think it too early for you to do that. Currently the Map feature only read default field, if you use picklist field you probably lose the map feature.

Furthermore the Picklist have it weaknesses, it can only use Picklist value (unless you import it), this mean that your Cities database need to be completed or user cannot fill in Cities that your database don't have.

**Comment by mariuszkrzaczkowski** [comment]
Just add the entry here and when you choose the values will automatically be downloaded
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/user_privileges/moduleHierarchy.php#L28
