### ISSUE TITLE
Question: What is the new Private checkbox for?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4006]
Hi,

I noticed in all the modules there is now a Private checkbox. Can I ask what this is for? Is it important as I can't seem to disable or hide it.

Kind regards

**Comment by ldgbc** [comment]
My guess is that enabling it will make the record view-able only to you/assigned/creator.

I'm not sure if upper management (e.g. admin) can still view it. But I guess it so that other equal level or group won't be able to view Private record.

**Comment by paula-w** [comment]
This mechanism will only allow access to people who have the permission to do so, nobody else will be able to access the record, apart from superadmin and people added in the "owner" and "share with" fields.
The mechanism will soon be finished, but for the time being we're still working on it.

**Comment by paula-w** [comment]
Correction – this mechanism actually already works in the system but advanced permissions must be enabled. This mechanism is disabled by default. 

It has some great options, apart from deciding whether or not a record is private it can also display records on the list that we can access by permission inheritance [eg. we set in the configuration that a user can see everything related to Account, eg invoices, normally when we open invoices we don’t see the invoices that aren’t assigned to us, and in the new mechanism they will be instantly visible].

Unfortunately the mechanism is a bit slow if there are more than 1k users, additionally, it works in CRON so there are some delays. The private field should not be visible in standard configuration [we’ll fix it] and it should appear only with advanced configuration.

We will do something about this issue before the next release, not sure what, we will have to think about it.

**Comment by PercyP** [comment]
@paula-w 

thanks for the updates/explanation - it sounds like it will be quite useful once it is finished
