### ISSUE TITLE
[Question] [Bug] Cannot login in. Username not found. v1472

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#4007]
#### Issue
I recently update from 3.4.21 to 3.4.1472, now I cannot log in anymore. It always give me, "Invalid Password or Username".

#### Actual Behavior
Should be able to log in at the login screen but CRM deny you always.

#### Expected Behavior
Log in no problem. Password is correct.

#### How to trigger the error
1. I have yet to find out how to trigger this so I'll tried it later. But see the logs below.
2. I have used the Login Logs (in Admin Panel) and notice that the login was "Login fail" for everyone. Even my own account.
3. Initially I thought it was incorrect password so I reset other people account password but it wasn't.
4. My account worked fine until I logged out.
5. Based on my guess it could be one of the following reason:

- Inactive user couldn't be enable in the Admin panel. So I re-active using myphpadmin.
- Incorrect update from v1472.
- Username field disappeared in the Edit User/Detail view.
- I added the "Profile" menu in Menu.
- HTTP Cookie only session - setting in PHP. I disabled it that while I thought it was the culprit but it doesn't work.

### How I tried to repair it ###
1. Reset password using myphpadmin and Admin panel
2. Checked that the column name is correct.
3. Compared the column/field name to a untouched database.
4. Looked at Errors Logs
5. Ctrl+F through the "/cache/logs/System Log" for the error. Only one is, "username not found". I checked and the username is there.

With that said, I'll do some testing to see if I can trigger the error on other server. Please find attached logs with sensitive info filter out (IP address and password) 

#### Your Environment
* YetiForce Version used: 3.4.1427
* Browser name and version: Firefox 51
* Environment name and version: PHP 5.6. 
* Operating System and version: Linux CentOS

--------

Not sure if it related but here is the PHP logs:
`[(time) ] PHP Strict Standards:  Only variables should be passed by reference in /home4/(username)/public_html/(website name)/vendor/yetiforce/Log/FileTarget.php on line 111`

Specifically this part.
`2017-02-13 12:30:12.6 [info][yii\db\Command::query] - SELECT `id`, `deleted`, `user_password`, `crypt_type`, `status` FROM `vtiger_users` WHERE `user_name`='test'`

![username in admin](https://cloud.githubusercontent.com/assets/1805303/22923440/921bd538-f2f5-11e6-8873-93e31c1771e8.jpg)
Please note: the password and username was hashed before. I tried that and it doesn't let me log in. So I used unhashed password like that.

Download the log here. [system.log.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/773642/system.log.txt)

**Comment by ldgbc** [comment]
Well that didn't take long to find out. It seem the bug is due to the update of version 1472.
Here how to trigger.

1. Install v3.40
2. Go Admin Panel > Update > Upload and install Update Package 3.4.0_to_3.4.1427_v2.
3. Go Admin Panel > User > Add Record > Add any user you want.
4. Top left corner. Hover over Admin > Log Out using the power button
5. Try to log back in > Invalid username or password.

I tried @kpaulaha server to test the server see if I can replicate on it. I used the default "demo / demo" that worked yesterday when I test his server for Roundcube error and that work. Either he changed the password/changed his server setting. Or I already bugged his yesterday.

https://github.com/YetiForceCompany/YetiForceCRM/issues/3910#issuecomment-279138007

**Comment by kpaulaha** [comment]
@ldgbc Just updated my yf -installation to 3.4.1829v3 with no problems.

**Comment by ldgbc** [comment]
I got a 500 page for with 3.4.1829v3.

Putting that aside @kpaulaha do you know how to restore database?
I can't seem to find any step for it. And my current method doesn't seem to work. I used 
"Restore a MySQL Database" that didn't worked. Still got invalid.

I exacted a v3.40 and restore the database, copy the config.inc.php files over but that didn't work. Got a blank page.

Not sure what to do.

**Comment by kpaulaha** [comment]
@ldgbc I "allways" export a dump of the db with phpmyadmin and zip the program files before upgrading a working installation. Easier than dig from server bup.

**Comment by kpaulaha** [comment]
@ldgbc Just updated to 4.0.0. Now downloading roundcube etc libraries worked ok.

**Comment by ldgbc** [comment]
Thank you. I have been dumping the database but I didn't Zip the www folder. So it regrettable.

I installed a fresh v4 complete version, and at least that one it can install. However there are this error persist in v4 also. It seem like the  "MYSQLND libraries" is the culprit as it was the only Libraries that I do not have and it was Mandatory.

`2017-02-14 12:00 [trace] - Exiting getColumnFields method ...
2017-02-14 12:00 [info][yii\db\Command::query] - SELECT `id`, `deleted`, `user_password`, `crypt_type`, `status` FROM `vtiger_users` WHERE `user_name`='admin'
2017-02-14 12:00 [error] - User not found: admin`

**Comment by nic86** [comment]
try this in development server:

http://stackoverflow.com/questions/13159518/how-to-enable-mysqlnd-for-php

**Comment by ldgbc** [comment]
Thank you @nic86, I would certainly do that if I moved to a VPS/Dedicated Server. At the moment I'm using shared hosting and that is out of option. 

As far as I'm aware there isn't any Hosting Provider/Company that support Yeti v4.0 requirement on Shared Hosting. If you do know one, let me know but currently I'm not technically confident enough to run/admin VPS/Dedicated Server yet so shared hosting is ease of mind.

**Comment by kabelo38** [comment]
I got it working check here https://github.com/YetiForceCompany/YetiForceCRM/issues/4028

**Comment by ldgbc** [comment]
Found this info here: #4160 

I'll try to see if this setting is something I can changed on my share hosting.

**Comment by thesxw** [comment]
Passwords should looks like this ...
$1$Ha000000$uBzPqCAyGTi2uqZa9TPgX/
for 123123123 there will be totally different password in database ...

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/5459#issuecomment-347555387
