### ISSUE TITLE
Fatall Error Update 3.4.1427 to 3.4.1829

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#4008]
#### Issue

> It was established YF 3.4.0 => updated 3.4.0_to_3.4.1427_v3 => updated 3.4.1427_to_3.4.1829_v3

When you install the update 3.4.1427 to 3.4.1829 fatal error:
`Fatal error: Call to a member function addField() on boolean in /var/www/html/cache/updates/init2.php on line 685`

#### Your Environment

* YetiForce Version used: ver. 3.4.1427
* Browser name and version: Firefox ESR
* Environment name and version: LAMP php5.6
* Operating System and version: W10

**Comment by ldgbc** [comment]
I have this error on mine: please see: https://github.com/YetiForceCompany/YetiForceCRM/issues/3996 maybe there something in there that might help.
`Application.cpp:313: File "/home4/(username)/public_html/(websitename).com/cache/updates/init2.php" is writeable by group, referer: http://(websitename).com/`

**Comment by rskrzypczak** [comment]
The block where the field was supposed to be added  most likely doesn't exist.
It might happen if you modify system names or you remove them, or the new block for some reason isn't added to the CRM.
