### ISSUE TITLE
[QUESTION] upload an image to the mail templates

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#4009]
In the vTiger you can select an image of the server or upload one from the local computer using the icon to add image of the WYSIWYG Textarea, but in the yetiforce you can not from there.

Do you have implemented a way to upload a file to put it in the mail template without having to upload it to an external repository?

**Comment by konadrian** [comment]
Here you have example how you can include an img in your email template
![animation](https://cloud.githubusercontent.com/assets/3193498/22928746/5476f6be-f2b8-11e6-968f-7743403c14bb.gif)

**Comment by WalterLuis** [comment]
Thanks for your answer, I was referring to if there is any similar way to upload a file and have it implemented. Example from vTiger.

translation from gif:
- "Ver Servidor" => Search the server
- "Cargar (tab)" => Upload file
![info_uplad](https://cloud.githubusercontent.com/assets/18419851/22930642/2ed05a8a-f2b9-11e6-82ee-74633c35f08f.gif)
