### ISSUE TITLE
Multiple errors on fresh install of YetiForce CRM 4.0.0

### ISSUE THREAD

**Issue by rxstriker** [YetiForceCompany/YetiForceCRM#4014]
#### Issue
When I tried to fresh install a test version of YetiForce CRM, a bunch of errors showed up:

- Notice: Use of undefined constant ROOT_DIRECTORY - assumed 'ROOT_DIRECTORY' in C:\xampp\htdocs\aliartalentos-yeti\include\ConfigUtils.php on line 165
- Notice: Undefined variable: default_charset in C:\xampp\htdocs\aliartalentos-yeti\include\ConfigUtils.php on line 33
- Notice: Undefined variable: defaultLayout in C:\xampp\htdocs\aliartalentos-yeti\include\ConfigUtils.php on line 33
- Notice: Undefined index: STYLES in C:\xampp\htdocs\aliartalentos-yeti\cache\templates_c\27053dfb40f536fc002f7daae2975d30929ecb28_0.file.Header.tpl.php on line 29
- Notice: Trying to get property of non-object in C:\xampp\htdocs\aliartalentos-yeti\cache\templates_c\27053dfb40f536fc002f7daae2975d30929ecb28_0.file.Header.tpl.php on line 29

#### Actual Behavior
![untitled](https://cloud.githubusercontent.com/assets/23050598/22935677/2dcebad4-f2cb-11e6-899f-1f47656777e8.png)
![untitled2](https://cloud.githubusercontent.com/assets/23050598/22935837/a870a02c-f2cb-11e6-91e0-1d68a3f460af.png)
![untitled3](https://cloud.githubusercontent.com/assets/23050598/22935836/a86d7d70-f2cb-11e6-8a50-c30b46901bb1.png)

#### How to trigger the error

1. Try to fresh install YetiForce CRM 4.0.0

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43.0.2442.806 (PGO)
* Environment name and version: XAMPP PHP 7.1.1
* Operating System and version: Windows 10 64-bit

**Comment by mariuszkrzaczkowski** [comment]
Read the requirements carefully

https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
