### ISSUE TITLE
Update 4.0 v1 LTS Error.

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4015]
#### Issue

![image](https://cloud.githubusercontent.com/assets/3030997/22942719/5e992124-f2c9-11e6-8cdf-03aa61b64987.png)

![image](https://cloud.githubusercontent.com/assets/3030997/22942756/91208448-f2c9-11e6-9c11-7742f2eb1b71.png)

Error when update from 3.4.1427 to 4.0.0_v1. A similar error occurred in the last update package 3.4.0_to_3.4.1427_v1

https://github.com/YetiForceCompany/UpdatePackages/blob/developer/YetiForce%20CRM%203.x.x/3.4.0_to_4.0.0/zip/3.4.1427_to_4.0.0_v1.zip

#### Expected Behavior

Work like 3.4.0_to_3.4.1427_v2 update.

#### Your Environment

* YetiForce Version used: 3.4.1427
* Browser name and version: Chrome
* Environment name and version: Dev-Test
* Operating System and version:

**Comment by kpaulaha** [comment]
Here no problems updating 3.4.1427 to 4.0.0v1.
CentOS + PHP 5.6.30. Also clean install of 4.0.0 without problems

**Comment by SkavenKF** [comment]
I have the same error when i update from 3.4.1427v3 to 4.0.0v1!
Browser: FF + Chrome
Operating System: Windows 10
PHP 5.6.20

**Comment by bpabiszczak** [comment]
500 is server error, not YetiForce.

**Comment by SkavenKF** [comment]
I retest it with a back up. Now i have a white screen and found no errors in logs.

Next i will test a fresh 3.4 installation ...

**Comment by bpabiszczak** [comment]
ehm

http://stackoverflow.com/questions/4731364/internal-error-500-apache-but-nothing-in-the-logs
http://stackoverflow.com/questions/7149030/php-return-500-error-but-no-error-log
http://stackoverflow.com/questions/9429616/apache-500-server-error-logs-showing-nothing

**Comment by SkavenKF** [comment]
@bpabiszczak : thanks for the information 👍  but all yf versions until 3.4 run on this server without problems (installation+updates), so i think some requirements have been changed.

my test result:
* fresh 3.4 installation => Ok, update to 3.4.27v3 => OK; update to 4.0.0v1 => WHITE SCREEN

* fresh 4.0.0 installation => not possible 😢 
   => Installation Process - new requirement:  max_input_vars 10000

   => Installation Process - Industry Details
![grafik](https://cloud.githubusercontent.com/assets/10259801/22948391/9a819060-f2fe-11e6-9cd8-27f198444383.png)

   => and stopped with the following screen (no db actions)
![grafik](https://cloud.githubusercontent.com/assets/10259801/22948196/de27b87c-f2fd-11e6-9c4b-e002d014d6e1.png)

**Comment by kpaulaha** [comment]
I belive the requirements was updated a few weeks ago. At least the installation worked when we changed server configurations meeting those.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
we have an article describing the causes of error 500: https://yetiforce.com/en/administrator-documentation/errors/227-apache-500-internal-server-error-2.html
Installations and updates are always tested numerous times. 
Your problem might be also caused by the wrong server configuration. If you had an error message, we would know what was wrong but without it, we aren't able to help. 
You can also check this article as it was updated on Friday: https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by rxstriker** [comment]
Ok, so the weirdest thing happened. I was trying to get around the blank installation screen problem and had an idea. 
What if I use my local environment (fully configurable following the web configurations guide provided in the yetiforce website) to install the DB information and structure on my remote server (in which I have little to no configuration access) until I reach the blank screen, and then I try to install YetiForce CRM again with the exact same info through my remote server?
Ok, so has expected I reached the blank screen on my local server, but on my remote server the installation proceeded as expected and I was thrown into the expected User Login screen as it was should be. Login credentials failed on my remote server, but on my local server I actually managed to login as normal.
Any thoughts on this?

**Comment by skramanzia** [comment]
@KatarzynaUlichnowska I understand what you say, but the variables are correct in my system and the permissions are also correct. YF is running and I never had problems with the updates, the new parameters were loaded on my server and I still have problems with the update to 4.0.0. The same thing happened with previous updates, that after getting version 2 or 3 worked correctly.

**Comment by paula-w** [comment]
Have you checked the php and crm logs? Without complete logs and info about the error we are not able to help.
It might be a problem that wasn’t included in the update package, but this requires an individual approach to you crm and we charge for this service.

**Comment by skramanzia** [comment]
Hi @paula-w, My server works correctly. I can not find any errors in the web server logs.

**Comment by paula-w** [comment]
Hi @skramanzia. The fact that you don’t have errors in your logs doesn’t mean that they are not there. You just can’t see them. Without logs we can’t help. You can buy support, then we’ll log in and check the problem.

**Comment by rxstriker** [comment]
Has I've said in #4017 these were the only logs that YetiForce CRM outputted, after turning on every debug option for error logging and displaying I could find:
[system.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/777386/system.txt)
[viewer-debug.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/777387/viewer-debug.txt)

**Comment by SkavenKF** [comment]
1. I installed a new XAMPP (for Windows) parallel to my old xampp installation.
2. i set the requirements
3. i install yf 4.0.0 
=> Ok

Requirements for yf are the same, but the old installation is with PHP 5.6.20 and the new installation PHP 7.1.1 .

Next i test the upgrade ....

**Comment by kpaulaha** [comment]
I have noticed the same, we have one CentOS server with yf4.0.0 which did not install on php 5.6.30 but with no problems and clean logs on 7.1.1 and same configurations.
