### ISSUE TITLE
[question] Where are the online git versions v4.0.0 LTS/RC?

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#4016]
#### Issue

I would test the new version of yf.

#### Actual Behavior

I cannot found the v4.0.0 versions of
![grafik](https://cloud.githubusercontent.com/assets/10259801/22966491/ab8bb41c-f362-11e6-9aad-2ecbe75cc35f.png)

I hope you have no problem with update to v4.0.0 :stuck_out_tongue_winking_eye:

**Comment by ldgbc** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.0.0/YetiForceCRM-4.0.0-complete.zip for "LTS/RC".

For Developer version: https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by SkavenKF** [comment]
@ldgbc: thanks, but i mean':
gitdeveloper.yetiforce.com (v3.4.1773) 
gitmaster.yetiforce.com (v3.4.0)
gitstable.yetiforce.com (v3.4.0)

**Comment by ldgbc** [comment]
So you want to test on their (Yetiforce) server? I guess it not updated yet to those version. Since the process is automated with the Developer version. I don't know how many hours must pass before it get "rebuild it" or updated.

This version is still a possible "Release Candidate". Although many people seem to have issue with installing (probably due to new server requirement). There is also no Announcement or Change logs yet.

In another words, just have to wait. I suppose v4.1773 is the closest you get to v4. Ignoring the new Theme, I think that is 4.1 or something.

**Comment by KatarzynaUlichnowska** [comment]
We are currently moving these versions to the new servers and the mechanisms for automatic update haven't been updated yet. That's why they aren't working. When we finish, we will let you know.

**Comment by kabelo38** [comment]
i just downloaded v4 from this link https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.0.0/YetiForceCRM-4.0.0-complete.zip

and encountered this error message after step 2 of the installation process.

( ! ) Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.0 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci' at line 1' in /var/www/yeti_dev/html/install/models/Utils.php on line 129
( ! ) PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.0 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci' at line 1 in /var/www/yeti_dev/html/install/models/Utils.php on line 129

**Comment by mariuszkrzaczkowski** [comment]
What entered the database name?

**Comment by kabelo38** [comment]
I Think its my screw up i made the DB name yeti4.0 sorry renaming the table everything went well

**Comment by SkavenKF** [comment]
Great, all releases are v4.0.x 😄 
I see that all run on PHP 7.0.11.

@mariuszkrzaczkowski: run YF 4.0.0 with PHP 5.5 or 5.6 ? 
![grafik](https://cloud.githubusercontent.com/assets/10259801/23019412/7fba372e-f442-11e6-8558-1901c19fa0bc.png)

**Comment by mariuszkrzaczkowski** [comment]
Prod 5.6
Test and Dev 7.0., 7.1

**Comment by mariuszkrzaczkowski** [comment]
gitstable, gitmaster, gitdeveloper already work
