### ISSUE TITLE
Fresh installation, installation bar disappears showing a blank installation screen

### ISSUE THREAD

**Issue by rxstriker** [YetiForceCompany/YetiForceCRM#4017]
#### Issue

During a fresh installation the installation bar disappears after a short while only to show a blank installation screen and nothing happens.
Followed every step, every web server requirement is filled with the exception of display_errors and log_errors.

#### Actual Behavior

Descriptions can be provided in English or Polish (remember to add [PL] for Polish in the title). -->
I was trying to fresh install YetiForce CRM 4.0.2, filled all the fields, after confirming the submitted data the installation begins by showing the installation bar and after a short while the bar disappears only to show a blank installation screen.
Followed every step, every web server requirement is filled with the exception of display_errors and log_errors.
![untitled](https://cloud.githubusercontent.com/assets/23050598/22971862/1dc182ee-f36f-11e6-95b8-ee2319e4fdba.png)

I'm gonna provide the logs here, passwords and security details have been masked and the DB is empty with no relation whatsoever with any other data on my system.
[system.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/776820/system.txt)
[viewer-debug.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/776821/viewer-debug.txt)

#### How to trigger the error

1. Fresh install on XAMPP PHP 7.0.15, use the data provided in viewer-debug.log to fill fields
2.
3.

#### Your Environment

* YetiForce Version used: 4.0.2 (developer)
* Browser name and version: Opera 43.0.2442.806 (PGO)
* Environment name and version: XAMPP 7.0.15
* Operating System and version: Windows 10 64-bit

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/4015#issuecomment-279830664
