### ISSUE TITLE
Missing Ldap Documentation

### ISSUE THREAD

**Issue by acidhunter** [YetiForceCompany/YetiForceCRM#4018]
Missing field to configure bind DN and password

Activated debug log does not give any errors about ldap auth

How does the ldap integration works?

* YetiForce Version used: 4.0
* Browser name and version: All
* Operating System and version: Debian 8, apache2 / php5.6

**Comment by alextovey** [comment]
Have you instal the php5.6-ldap module from the updated debian list?

**Comment by acidhunter** [comment]
sure

the module is there, other ldap applications on my host work well

it cannot work without setting the bind dn or a search string. this option is missing.

**Comment by mariuszkrzaczkowski** [comment]
This is unnecessary,
Because the access data is checked based on the login and password that the user enters (of course the user must exist in the crm)
