### ISSUE TITLE
Custom data access with advanced module

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#4019]
Version: stable 3.4 and developer 4

when override data access class in folder /modules/CUSTOMMODULE/data_access/test.php

```
Class CUSTOMMODULE_test
{
	public $config = true;
	public function process($ModuleName, $ID, $record_form, $config)
	{
            //my custom instructions
            if($error){
		return Array('save_record' => false, 'type' => 0, 'info' => Array('title' => mycustomtitle, 'text' => mycustomtext, 'type' => 'info'));
           }
           else
           {
              return Array('save_record' => true)
           }	
        } 
	public function getConfig($id, $module, $baseModule)
	{
		return Array('tpl' => 'test', 'type' => 0);
	}
}
```

if the process function return 'save_record' => false,  the save of the record is stopped, but triggers the function "registerInventorySaveData" in [inventory.js](https://github.com/YetiForceCompany/YetiForceCRM/blob/stable/layouts/basic/modules/Vtiger/resources/Inventory.js#L615-L624)  anyway.

```
var table = container.find('#blackIthemTable');
table.find('[name]').removeAttr('name');
```

this two line causes malfunction of the 'Add Product' button when another product is added to the list.

possible workaround is to extend the javascript class Vtiger_Inventory_Js in layout/basic/modules/CUSTOMMODULES/resources/Inventory.js and invoke custom action from /modules/CUSTOMMODULE/actions/Inventory.php 
or create custom handler with [registerHandler](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/EventHandler.php#L84-L100) for the event 'vtiger.entity.beforesave' (not sure)

**Comment by mariuszkrzaczkowski** [comment]
Does the bug exist in the latest development version?
