### ISSUE TITLE
Question about Dispatch Note and products/items population

### ISSUE THREAD

**Issue by capriole** [YetiForceCompany/YetiForceCRM#4020]
Hello, 

I would like to ask a question in regards to the operation of the Dispatch Note. When a Dispatch order is created and is linked to an existing sales order (Single Order field) then why the products (already listed in the Sales Order) are not added to the Dispatch Order?

A possible scenario could be because some products might be part of an sales order but they are not in stock so they can't be dispatched but assuming that all products are in stock then is it possible to have the items from the Sales Order added automatically to the dispatch note upon selection of a sales order?

**Comment by ldgbc** [comment]
Hi capriole, 

Don't quote me on this, but based on memory v4 removed Dispatch Order module.

**Comment by capriole** [comment]
Hi ldgbc, 

I can't find any messages describing this change, do you know where the features/changes list of v4.0 are listed?

**Comment by ldgbc** [comment]
Hi @capriole I had a look and that module is still in v4. So I apologize for the incorrect information. It was some other module that got removed/replaced.
