### ISSUE TITLE
Reminder keep coming back

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4021]
#### Issue
Reminder keep coming back

#### Actual Behavior
Reminder keep coming back

#### Expected Behavior
Reminder should not come back after marking as read

#### How to trigger the error
Just use https://gitstable.yetiforce.com

**Comment by nic86** [comment]
probably it is connected with cron. 
cron is not yet active in demo.

**Comment by ldgbc** [comment]
It seem to be fixed now.
