### ISSUE TITLE
[Question] Many to Many Relationship, Relate to, One to Many

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#4025]
#### Issue
How to create One to Many, or Many to Many relationship/ related to?
I tried searching on Issue but couldn't find anything about it. Was it removed or hidden elsewhere?

#### Actual Behavior
Menu/option does not appear.

#### Expected Behavior
Option to be available.

#### How to trigger the error
#3793 - I saw this post and try to find it but could not find it anywhere. I even check v4.0 on https://gitstable.yetiforce.com/ but it wasn't there.
Has it been remove or moved elsewhere?

#### Your Environment

* YetiForce Version used: 3.4 and 4.0
* Browser name and version: Firefox
* Environment name and version:
* Operating System and version:

**Comment by nic86** [comment]
Software configuration > Standard modules > Modules – Relations > Start

[config/developer.php](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/developer.php#L13)

set highlight value to true

**Comment by ldgbc** [comment]
Thanks @nic86 . Just to clarify this for future references or user.

You have to edit these two value:
// Change of fields visibility
	'CHANGE_VISIBILITY' => false,
	// Adding/Deleting relations between modules.
	'CHANGE_RELATIONS' => true,

The Relations will make that option appear. It not what I expected, I thought it would allow me, for example to add One Contact to under many Account. Or one Event to many Contact. 
Maybe it can and I'm creating it wrong. Anyway you want to "true" on Visibility, it will display a "x" next to the Visible button.

This way you can delete them as you test out what you need.

**Comment by ldgbc** [comment]
I recently discover that it will be a long time before this is possible. See #1913 specifically:

> We are not planning to introduce such functionality at the moment. This is due to many factors, first of all changing the relation requires rebuilding the entire system, it also creates a problem while maintaining the continuity of history, and separating the history between accounts. We will not change that for the time being.
