### ISSUE TITLE
[Bug] Quick Create option disappear/remove when Advanced Block is enable v4.0

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#4026]
#### Issue
[Bug] Quick Create option disappear/remove when Advanced Block is enable v4.0
Ref:  #3993 

#### Actual Behavior
Cannot Quick Create that advanced block module.

#### Expected Behavior
Option should still be available, else a warning should be display.

#### How to trigger the error
1. https://gitstable.yetiforce.com/
2. Login > System Setting > Edit Field > Contact (top right)
3. Click from Basic to Advance > press Ok
4. Press + (quick create). Contact no longer can be quick create.

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: Firefox 51
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
It's not a bug, so it was always, even in vtiger. Can not create record without selecting products / services.
