### ISSUE TITLE
email workflow - can't send emails

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#4027]
#### Issue
Sending eMail in eMailworkflow is crashing "from can't be NULL" error

#### Actual Behavior
sending an email in an workflow quits with an error "FROM" should not be "NULL" - seems that the sender as not handed over correctly

#### Expected Behavior
workflow which sends an email when creating a contact.

#### How to trigger the error
![image](https://cloud.githubusercontent.com/assets/12951699/23036084/bc02fc68-f481-11e6-945d-0f430ef19170.png)

#### Your Environment

* YetiForce Version used: latest stable
* Browser name and version: chrome
* Environment name and version: linux based ispconfig
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
It needs more details as it is configured workflow, make screen shots of the configuration

**Comment by ahmido** [comment]
I have the same problem

**Comment by ralphkretzschmar** [comment]
Here we go:
after the screenshots below the next step creating a contact results in the error screenshot from my first mail

one additional question:
in vtiger it was possible to click on a contact and send a email directly to the contacts email address. And there was also a tracker for this email if it was opened (counter)
Is this to be planned for yetiforce as well? this was an AWESOME feature and we really miss it :)


![image](https://cloud.githubusercontent.com/assets/12951699/23467488/85c12892-fe9e-11e6-9852-e295f9683d91.png)

![image](https://cloud.githubusercontent.com/assets/12951699/23467531/97bcf760-fe9e-11e6-9993-13f8be50bbf1.png)

![image](https://cloud.githubusercontent.com/assets/12951699/23467572/b54eba02-fe9e-11e6-95e1-282a900dbf48.png)

![image](https://cloud.githubusercontent.com/assets/12951699/23467716/11ef9ccc-fe9f-11e6-9b5d-6c76df746332.png)

![image](https://cloud.githubusercontent.com/assets/12951699/23467736/1e404a76-fe9f-11e6-952d-6557157e07d7.png)
