### ISSUE TITLE
[bug] decimal fields and grouping

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#4029]
#### Issue
Selecting other than point to decimal separator do not work in decimal and percent fields
Grouping selection doesn't work
![dec](https://cloud.githubusercontent.com/assets/10330264/24187119/3c645b46-0ee4-11e7-86e9-3bfe2840dcab.gif)

![fields](https://cloud.githubusercontent.com/assets/10330264/23058143/3356be4c-f4fc-11e6-8577-995e4a227a81.png)

#### How to trigger the error

1. Change desimal selector, add value to field, save, edit
2. Select grouping pattern and separator
3.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Does the bug exist in the latest development version?

**Comment by kpaulaha** [comment]
Still the same, don't accept decimal values with comma, although set in user settings. Same with grouping.
![dec2](https://user-images.githubusercontent.com/10330264/27419330-f6c97408-5728-11e7-99c1-6e6fa1414289.png)
![dec1](https://user-images.githubusercontent.com/10330264/27419333-fd0ca088-5728-11e7-9f1a-d83b1e2d3bf6.png)

**Comment by kpaulaha** [comment]
Thank's @mariuszkrzaczkowski, means a great deal for us using YF

**Comment by kpaulaha** [comment]
@mariuszkrzaczkowski 
Not working more on the dev version. Not even accepting existing decimal values.
![dec](https://user-images.githubusercontent.com/10330264/30024361-16962f8c-917c-11e7-8166-5f278344f82f.png)

![dec1](https://user-images.githubusercontent.com/10330264/30024365-1bde7e18-917c-11e7-9cb3-6e714bfe7117.png)
