### ISSUE TITLE
[PL] Problem z udpatem do wersji 4

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#4030]
#### Issue

Witam.
Mam spory problem z update do wersji 4.0.
Za każdą próbą mam 👍 /public_html/update/cache/updates/init2.php" is writeable by group
Co może być przyczyną.
Doda, że czysta wersja po zmianach w konfiguracji serwera działa poprawnie, da się zainstalować.. i możliwe jest zalogowanie.

nie pomoże zmiana chmodów - ponieważ po każdej próbie mam znowu to samo... nawet w momencie - kiedy przejdę pierwszy krok .. zmienię chody na 644 .. akceptuję i daję dalej ... mam cały czas błąd...
Czy mogę zakomentować to gdzieś --- nie znalazłem.

w Logach apache:
Failed loading /usr/local/ioncube/ioncube_loader_lin_5.6.so:  /usr/local/ioncube/ioncube_loader_lin_5.6.so: undefined symbol: zval_update_constant_inline_change, referer: http://XXXXX.XX/update/index.php

Czy tutaj tkwi problem ?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4.1427 do 4.0
* Browser name and version: mozlilla
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
ale to nie do nas pytanie, błąd pokazuje błąd ładowania biblioteki ioncube [której nasz system nie używa], a więc to nalezy omówić ze swoim administratorem. 

Może zainstalowaliście jakiś moduł Vtiger [a one używają tego do szyfrowania] a więc wówczas problem należy rozwiązać z dostawcą modułu nie z nami.

**Comment by zimart** [comment]
Problem raczej nie leży w tym... wcześniejsze wersje aktualizują się bez problemu ... Problem jest przy aktualizacji z  3.4.1427 do 4.0 - podałem z logów tylko dlatego że nie wiem ,czy to jest problem - Jeżeli nie to raczej problem tkwi w instalatorze. Czy jest ktoś komu udało się przeprowadzić update poprawnie ? 
W załączeniu historia aktualizacji.. wersja 3,2 była czysta...
![akualizacje](https://cloud.githubusercontent.com/assets/11014419/23068367/a5118522-f523-11e6-9df9-5d89bd85f25c.jpg)

**Comment by bpabiszczak** [comment]
Wszystkie update które my wykonywaliśmy były poprawne. Nie ma znaczenia to, że wcześniej działało a teraz nie działa. Z tego co rozumiem masz jakieś indywidualne zmiany [bo po co Tobie ioncube] i masz jakąś specyficzną konfiguracje.... 

a więc trzeba włączyć logi i po kolei rozwiązywać problemy, pierwszy który masz to to, aby nie pojawiał się błąd ioncube.

**Comment by zimart** [comment]
Przeprowadziłem ponownie próbę - od czystej wersji 3.2 po kolei - całkiem czysta wersja - i przy próbie do 4 dalej to samo...  Problemem podejrzewam nie jest ioncube - (nie przeszkadza przy próbie instalacji czystej wersji systemu w wersji 4 ) tylko nadawanie przez skrypt instalatora uprawnień plikom - co przy moim serwerze robi jakiś problem.
dlaczego po uploadzie przez instalator - pliki otrzymują chmody 755 ? 

Internal Server Error

File " xxxx/public_html/32/cache/updates/init2.php" is writeable by group
suPHP 0.7.1

**Comment by zimart** [comment]
Usunięte wszystkie pliki...z katalogu "updates" - uruchomienie inastalatora ---> błąd ----> zmiana chmodów plików 775 ---- nie wiadomo z jakiego powodu ustawiają się takie na 755 --- poszło.

**Comment by bpabiszczak** [comment]
Musisz spytać administratora czemu Twoje pliki otrzymują 755 ale w mojej opinii prawidłowo, bo wszystkie pliki powinny mieć 755 a foldery 644. Niezależnie co jest błędem, poprawia się je po kolei, gdybyśmy my zostawiali błędy bo "przypuszczalnie" nic złe nie robią, to dopiero byłoby zabawnie. 

Po drugie ISE to błąd serwera nie aplikacji, a więc trzeba się zgłosić do administratora a nie tutaj.

**Comment by zimart** [comment]
Witam... Na serwerze wszystko jest git...  Pliki normalnie otrzymują poprawne uprawnienia... 644 ...Napisałem że nie 755 ...tylko po uploadzie plików 4 pliki maja 775 ... Ps... Przy drugiej próbie aktualizacji systemu roboczego nie udało się... Błąd taki sam...  Nie pomaga także zakomentowanie "IF... " w pliku init2.PHP...  Zostaja mi w tym momencie jedynie proby na localu

**Comment by zimart** [comment]
Ps...  Doczytałem post wyzej i chyba troszke nie tak jak piszesz z tymi chmodami ... Dokladnie na odwrot :)

**Comment by bpabiszczak** [comment]
Tak dla folderów 755 a plików 644 ale to szczegół... nie rozumiem dlaczego ignorujesz to jak masz ten problem znaleźć i usunąć. Szukasz dookoła zamiast włączyć porządnie logi i wyeliminować wszystkie błędy.

**Comment by zimart** [comment]
Nie ignoruję.. szukałem już różnymi sposobami przyczyn... Dlatego proszę o pomoc. Reasumując : 
Problemem jest u mnie to, że w momencie "kopiowania/rozpakowywania plików" - nie wiadomo z jakiej przyczyny niektóre otrzymują złe uprawnienia - 775 
W logach http: nic co by by mnie naprowadziło na dobrą drogę -  logi http- czyste, 
logi suPHP: [Sat Feb 18 21:48:19 2017] [warn] File "/home/panel2/domains/xxxxx.pl/public_html/cache/updates/init2.php" is writeable by group
tyle razy ile prób..
Logi Yeti:
PHP Notice:  Undefined index: exclude in /home/panel2/domains/panel2.biznes.sanok.pl/public_html/vtlib/Vtiger/Unzip.php on line 85

Dodatkowo: zrobiłem fix uprawnień na serwerze... i nie widze żeby przy rozpakowywaniu czy kopiowaniu innych plików zmieniało chmody na niewłaściwe -  wcześniejsze wersje aktualizacji idą bez problemu...
Tutaj mam różnie.. załączam screeny .. Ewentualnie czy jakiś ręczny update jest możliwy ? Załączam screeny co mam po odpaleniu instalatora.
![chmody-1](https://cloud.githubusercontent.com/assets/11014419/23096991/364be8a6-f629-11e6-9dcc-ed46909bb967.jpg)
![chmody-2](https://cloud.githubusercontent.com/assets/11014419/23096992/364e0f82-f629-11e6-8a7c-a02a76b29c51.jpg)
![chmody-3](https://cloud.githubusercontent.com/assets/11014419/23096989/36497a62-f629-11e6-985c-1781bc46d192.jpg)
![chmody-4](https://cloud.githubusercontent.com/assets/11014419/23096990/364a2318-f629-11e6-8f1f-4a4d75ac118a.jpg)

**Comment by zimart** [comment]
Witam, kolejny raz próbuję podejść do tematu...inny serwer.. myślę a nuż się uda...
i Mam - 
Fatal error: Uncaught exception 'Exception\NoPermittedToRecord' with message 'LBL_RECORD_DELETE' in /usr/home/kobiecowo/domains/xx.sanok.pl/public_html/include/CRMEntity.php:243 Stack trace: #0 /usr/home/kobiecowo/domains/xxxx.sanok.pl/public_html/modules/Vtiger/models/Record.php(509): CRMEntity->retrieve_entity_info(35, 'OSSMailTemplate...') #1 /usr/home/kobiecowo/domains/exx.sanok.pl/public_html/vtlib/Vtiger/ModuleBasic.php(516): Vtiger_Record_Model::getInstanceById(35, 'OSSMailTemplate...') #2 /usr/home/kobiecowo/domains/xxx.sanok.pl/public_html/cache/updates/init2.php(370): vtlib\ModuleBasic->deleteFromCRMEntity() #3 /usr/home/kobiecowo/domains/exxxxxx.sanok.pl/public_html/cache/updates/init2.php(207): YetiForceUpdate2->removeModules(Array) #4 /usr/home/kobiecowo/domains/xxxx.pl/public_html/cache/updates/init2.php(6): YetiForceUpdate2->update() #5 {main} thrown in /usr/home/kobiecowo/domains/xxxk.pl/public_html/include/CRMEntity.php on line 243


Czy może ktoś pomóc ?

**Comment by rskrzypczak** [comment]
Przed aktualizacją opróżnij kosz lub skorzystaj z ostatnio wypuszczonej paczki aktualizacyjnej v4

**Comment by zimart** [comment]
niestety..
Warning: Illegal offset type in isset or empty in /usr/home/kobiecowo/domains/xxx.sanok.pl/public_html/vendor/yii/db/TableSchema.php on line 76 Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'subject'' in /usr/home/kobiecowo/domains/xxx.sanok.pl/public_html/vendor/yii/db/Command.php:850 Stack trace: #0 /usr/home/kobiecowo/domains/ehost.sanok.pl/public_html/vendor/yii/db/Command.php(850): PDOStatement->execute() #1 /usr/home/kobiecowo/domains/xxxx.sanok.pl/public_html/vtlib/Vtiger/Utils.php(198): yii\db\Command->execute() #2 /usr/home/kobiecowo/domains/xxx.sanok.pl/public_html/vtlib/Vtiger/FieldBasic.php(188): vtlib\Utils::AddColumn(Object(SimpleXMLElement), Object(SimpleXMLElement), 'varchar(255)') #3 /usr/home/kobiecowo/domains/xxxx.sanok.pl/public_html/vtlib/Vtiger/FieldBasic.php(259): vtlib\FieldBasic->__create(Object(vtlib\Block)) #4 /usr/home/kobiecowo/domains/xxxx.sanok.pl/public_html/vtlib/Vtiger/Block.php(146): vtlib\FieldBasic->save(Object(vtlib\Block)) #5 /usr/home/kobiecowo/domains/xxxx.sanok.pl/public_html/vtlib/Vtiger/PackageImport.php(770): vtlib\Block->addField in /usr/home/kobiecowo/domains/xxxx.sanok.pl/public_html/vendor/yii/db/Schema.php on line 602

**Comment by zimart** [comment]
po kolejnej próbie .. i jeszcze małych zmianach konfiguracji php  poszło.... tak więc dziękuję i zaczyna się od nowa ustawianie swoich dodatków..

**Comment by mariuszkrzaczkowski** [comment]
jak możesz to napisz co musiałeś zmienić to może innym pomoże to z tym problemem
