### ISSUE TITLE
Server configuration system message

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4032]
Warning dialog box popup (as per below) without reason whiles all required libraries are installed. Only optional are not. Anyway is there an option that standard user will not get ANY warnings, but ONLY administrator? 

"System warnings
Server configuration
The server has not been properly configured. The system may malfunction, or the entered data may be corrupted or removed. More information in the article on server requirements at yetiforce.com"

**Comment by mariuszkrzaczkowski** [comment]
This only sees the administrator, check that you have all the parameters set correctly?
Test the latest developer version
