### ISSUE TITLE
Default price list selection in invoice module

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#4034]
Is it possible to set up a default price list when creating an invoice (or any other advanced module)?
I would like that the previously defaulted price list prices apply to the products or services selected within the invoice creation form.

**Comment by paula-w** [comment]
The prices are loaded directly from the product/service, and these are default prices. In the future we’re planning to add the option to select default price list directly on the client. 
If this is not what you mean then we need a more detailed description to be able to help.
