### ISSUE TITLE
upgrading doe not seem to work!

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4035]
#### Issue
When applying update from 3.4.1427 to 4.0 it comes up with error 500 page not found.

#### Actual Behavior

Error 500 page on when applying the upgrade

#### Expected ####
The upgrade to 4.0 should work without issue.

#### How to trigger the error

1.upload the patch within the admin update section
2.tick box and then click yes
3.Upload not working.

#### Your Environment

* YetiForce Version used: 3.4.1427
* Browser name and version: chrome, ie 11, firefox.
* Environment name and version:dedicated server
* Operating System and version: ubuntu 16.06 > 8g ram > 4 core xeon processor 500gb ssd.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/administrator-documentation/errors/227-apache-500-internal-server-error-2.html

**Comment by SkavenKF** [comment]
You are not alone, see #3996

**Comment by alextovey** [comment]
Clearly an install problem with the system not with the servers. I've tried this on several servers for updating. none of them works.

**Comment by StaggerLeee** [comment]
This is error when updating to 4.0.0:

```
Fatal error: Uncaught Error: Call to a member function getMessage() on array in D:\Neard\www\some-site\vtlib\Vtiger\Functions.php on line 848
( ! ) Error: Call to a member function getMessage() on array in D:\Neard\www\some-site\vtlib\Vtiger\Functions.php on line 848
```

**Comment by skramanzia** [comment]
@bpabiszczak here the log to update, after error

2: rmdir(cache/updates/EmailTemplates): No such file or directory in /var/www/sites/demo.com/crm_dev.demo.com/cache/updates/init2.php, line 988
#0  ()  >>  exception_error_handler(2,'rmdir(cache/updates/EmailTemplates): No such file or directory','cache/updates/init2.php',988,[EmailTemplates,object(App\Db),cache/updates/EmailTemplates,cache/updates/EmailTemplates.zip,array])
#1 cache/updates/init2.php (988)  >>  rmdir('cache/updates/EmailTemplates')
#2 cache/updates/init2.php (213)  >>  YetiForceUpdate2->addRecords('EmailTemplates')
#3 cache/updates/init2.php (6)  >>  YetiForceUpdate2->update()
