### ISSUE TITLE
History of recent visited pages

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#404]
A complaint of my users is that they can't go back to pages/records they have visited before.
For example:
They open a calendar activity item, then go via the related field link to the contact record and from there the click on the email address link to open Roundcube and send an email. It is not possible to go back to the contact record or the calendar activity without performing a search/starting from the beginning.

I created a javascript function that adds a drop-down button with the last visited pages to the system (see screenshot below).
Before going ahead and creating an installable module my question is if you are intrested to include this functionality into the core system as this would be the better solution for this kind of feature.

To install this feature upload the javascript file 'webStorageRecentPages.js' to the server and add it to the layout 'JSResources.tpl' file.
File download link: https://www.dropbox.com/s/3e7ip82ex6o9zl5/webStorageRecentPages.js?dl=0

![image](https://cloud.githubusercontent.com/assets/10443220/6743939/5daa1cf8-cea1-11e4-8aeb-9d9cfcf9a7fe.png)

**Comment by mariuszkrzaczkowski** [comment]
It's nice and simple solution for history of recently viewed websites, thanks, good job. I added it already to YetiForce and it can be tested from the revision: https://github.com/YetiForceCompany/YetiForceCRM/commit/68f5bf143bbb0a1c8b524f987aed6ed6e5b0dbb2
