### ISSUE TITLE
[Question] I can't delete Notifications

### ISSUE THREAD

**Issue by ahmido** [YetiForceCompany/YetiForceCRM#4042]
Hello @all,

is there a way to delete notifications?

i can't see a button to delete a notification.
![cpcvhskj8q](https://cloud.githubusercontent.com/assets/7672820/23124802/0e92cfcc-f76f-11e6-9926-46ec13251aee.gif)

**Comment by konadrian** [comment]
https://yetiforce.com/en/github/issues/126-issues.html
Please give us more information, for me on current version everything work fine. Please record gifs in English
![animation](https://cloud.githubusercontent.com/assets/3193498/23125250/1d2088de-f771-11e6-9bed-73d27918c7c0.gif)
