### ISSUE TITLE
install 4.00 issues

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#4043]
When trying to install yeti 4.0 I get this error:
(This is showed before yeti GUI installation steps  are showed.

Warning: require(/home/crm/vendor/composer/../smarty/smarty/libs/bootstrap.php): failed to open stream: No such file or directory in /home/crm/vendor/composer/autoload_real.php on line 67

Fatal error: require(): Failed opening required '/home/crm/vendor/composer/../smarty/smarty/libs/bootstrap.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/crm/vendor/composer/autoload_real.php on line 67

Any idea what this is related to?

**Comment by WalterLuis** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases

install: YetiForceCRM-4.0.0-complete.zip

**Comment by lalord** [comment]
tried again with that link, but same issue.

**Comment by WalterLuis** [comment]
You should not receive the same error,
The error that you show is that there is no "smarty" folder in the path of your CRM "/home/crm/vendor/" and in the full version if you have them.
Check it
