### ISSUE TITLE
Reports all time reload popup

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#4044]
#### Issue

not retract report

#### How to trigger the error

1. Go to Reports module
2. Create new Report and set the status of approved

#### Your Environment

* YetiForce Version used: 4.0.36
* Browser name and version: chrome
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: w10

**Comment by mariuszkrzaczkowski** [comment]
Test the latest version of the system
