### ISSUE TITLE
[BUG] Error sending mails with workflow 

### ISSUE THREAD

**Issue by ahmido** [YetiForceCompany/YetiForceCRM#4046]
Hello @all i have created a worklow to send mails.

i have configured the SMTP and it works, but as worklow i get this error message:
`Error!!!
SQLSTATE[HY000]: General error: 1364 Field 'from' doesn't have a default value The SQL being executed was: INSERT INTO `s_yf_mail_queue` (`smtp_id`, `to`, `subject`, `content`, `status`, `owner`, `date`) VALUES (1, '[\"test@geco-energie.de\"]', 'test', 'test', 1, 1, '2017-02-20 19:20:15')`

System: Apache2.4 Php 5.6 Yetiforce 4.0(fresh install)

**Comment by mariuszkrzaczkowski** [comment]
ficek in https://github.com/YetiForceCompany/YetiForceCRM/commit/58eb22eb123108fbfc24840d8dd275e8c4096977
