### ISSUE TITLE
Not working product selection from the price books in YF 4.0.0

### ISSUE THREAD

**Issue by lcuevastodoit** [YetiForceCompany/YetiForceCRM#4047]
#### Issue
From the pricebook is not working the "Add to Pricebooks" button to select a product

And selecting record "pricebook" from "product detail page" is not working either
I love YF
Please help
View the gif
![pricebook_problemyf](https://cloud.githubusercontent.com/assets/25910807/23143896/ff5c7d78-f791-11e6-90a2-4b9e0d21de38.gif)

YF 4.0.0

**Comment by mariuszkrzaczkowski** [comment]
The error does not occur in the latest version of the developer

**Comment by lcuevastodoit** [comment]
Thanks, How Could I Install the developer version?
