### ISSUE TITLE
PHP performance tips

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#4053]
Some tricks to speed up and clean up the php code:

[google php tips](http://web.archive.org/web/20140625191431/https://developers.google.com/speed/articles/optimizing-php)

[Thiemo Mättig benchmark](http://maettig.com/code/php/php-performance-benchmarks.php)

[PHPyths Buster](https://jonczyk.me/2016/10/23/phpyths-buster-great-string-performance-test/)

two interesting things:
- Avoid writing naive setters and getters
- Concatenating strings: 
it is better to use
 `$string = "some {$var} concatenation";` 
instead of
 `$string = sprintf('%s %s %s', 'some', $var, 'concatenation');`

**Comment by bpabiszczak** [comment]
Thank you. 
We are constantly improving performance.
https://yetiforce.com/en/developer-documentation/standards/231-performance-comparison-of-php-5-2,-5-3,-5-4,-5-5,-5-6,-7-0-2.html
