### ISSUE TITLE
Email Notification

### ISSUE THREAD

**Issue by vinci4352** [YetiForceCompany/YetiForceCRM#4055]
#### Issue

 
Is there any way to get notifications regarding planned tasks to be sent on user's email ? Notification sent only within the system has a limitation to have system constantly open to see notification in real time coming.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by migoi** [comment]
there is a cron to be configured. Done that?

**Comment by mariuszkrzaczkowski** [comment]
Notifications work in cron, and must be active
