### ISSUE TITLE
[Bug] PDF creation from Invoice doesnt work properly

### ISSUE THREAD

**Issue by nkzach** [YetiForceCompany/YetiForceCRM#4056]
#### Issue

PDF generation from **existed** invoice (without editing) works fine.

But if create a new invoice or edit an existed one, the PDF generation doesnt work.

In GitStable the result is a blank page while in GitDevelopment the result is:
"Warning: explode() expects parameter 2 to be string, array given in /modules/Vtiger/actions/PDF.php on line 71

Warning: Invalid argument supplied for foreach() in /modules/Vtiger/actions/PDF.php on line 175"

In both versions the invoice page freezes as it is shown in next screenshot:
![screenshot 2017-02-21 14 52 04](https://cloud.githubusercontent.com/assets/22010748/23165762/5ada6250-f846-11e6-9e7a-80da7ca4cd4e.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by nkzach** [comment]
Here i am again.
The above issues apearing, if after saving the invoice, we press immediately  the button "export to pdf".
If after saving close the page and reopen the invoice from the list everything works properly.

**Comment by waran70** [comment]
Here we can not create any new template. Just "Loading, please wait." - infinity.....
