### ISSUE TITLE
Can you share with us your php.ini?

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#4058]
Our system meet all requirements as recommended. 
Centos 7, php 5.6... all libraries are in place. Still here are some issues with YF 4
I would like to compare php.ini, so I may detect some additional settings we omitted here... 
Appreciate help

**Comment by PercyP** [comment]
I would be interested in this too. Mine meets all the requirements too in yetiforce configuration yet I am having problems so it would be interesting to know if it is actually down to a php.ini settings.

**Comment by migoi** [comment]
what PHP version?

for apache or commandline (cli)?

**Comment by reeid** [comment]
here is centos 7, php 5.6
apache installed

**Comment by migoi** [comment]
i've PHP 7 

I can upload the apache version if you want.

But maybe its better you specify "some issues" a little bit.

**Comment by reeid** [comment]
The point is I want to save your, mine and others here time by soft debugging/comparison. 
Once I detect that there is something what helped me I will share it immediately.
Current issue is pdf templates - can not create. But I am sure I will get more as we plan to mirror vtiger to yetiforce system (not moving yet). We using extensively this CRM. For instance WorkflowDesigner (extension) has created 230 workflows. PDFMaker - 70 templates.... etc....  so I wanna start from scratch, and from exactly the same point (if possible) as yetiforce demo/dev versions.

**Comment by reeid** [comment]
Thee was cool idea  #3960  with virtual instances.... would love to get one from YF to see how they cope with system stuffs

**Comment by migoi** [comment]
This is mine (PHP7) -> https://github.com/migoi/Foobar/blob/master/php.ini

**Comment by reeid** [comment]
TNx

**Comment by mariuszkrzaczkowski** [comment]
I created a ready-made package to run and install YetiForce. It's xamp with a ready PHP and MySQL configuration, it's the dev version, not the production version. 
You can test all problems related to update and installation on it. 
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%204.x.x/4.0.0/?upload_just_completed=true
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.0.0

**Comment by skramanzia** [comment]
@mariuszkrzaczkowski, I Use NGINX with php 5.6, in all versions works correctly, but i cannot update to 4.0 Update package, after change all variables always displayed "ERROR 500", really all server configuration, variable and permissions was correctly added. phpinfo displayed all configuration fine. a couple of weeks  ago the uptate to 3.4.1427 displayed the same error, after release v3 worked perfectly.

**Comment by migoi** [comment]
Error 500 says: internal server error. 

in 99% its an error inside your php application. So what is in the log files:

/var/log/nginx/error.log
or 
/path/to/yetiforve/cache/log/phpError.log

**Comment by skramanzia** [comment]
**phpError.log**, blank.

**error.log**

2: rmdir(cache/updates/EmailTemplates): No such file or directory in /var/www/sites/demo.com/crm_dev.demo.com/cache/updates/init2.php, line 988
#0  ()  >>  exception_error_handler(2,'rmdir(cache/updates/EmailTemplates): No such file or directory','cache/updates/init2.php',988,[EmailTemplates,object(App\Db),cache/updates/EmailTemplates,cache/updates/EmailTemplates.zip,array])
#1 cache/updates/init2.php (988)  >>  rmdir('cache/updates/EmailTemplates')
#2 cache/updates/init2.php (213)  >>  YetiForceUpdate2->addRecords('EmailTemplates')
#3 cache/updates/init2.php (6)  >>  YetiForceUpdate2->update()

**view_debug.log**, a lot of lines

**Comment by migoi** [comment]
so this one seems to be filesystem related. 

<your YF path>/cache/updates/EmailTemplates

does this one exists?

One hint: I've started with nginx too, but switched to apache2 because YF makes use of some rewrite rules in the .htaccess file - nginx cannot handle those or better: they must be converted to nginx conf syntax.

**Comment by skramanzia** [comment]
Hi, "/cache/updates/EmailTemplates" exist, I try delete files, folder and change chmod and chown.

**Comment by migoi** [comment]
may your installation does not know the filepath (ROOT_DIRECTORY) so it does not see the complete path and thus it fails

**Comment by ldgbc** [comment]
Hi. Over the week I recently learn something new, there is this thing call "phpinfo.php" (see link for more  info: ). Which basically say what your PHP server/setting is. With that info I should be able to (hopefully) finally track down why I'm getting Error 500 while most people don't have this issue.

`https://www.inmotionhosting.com/support/website/php/create-phpinfo-page-to-see-php-settings`

So I would like to request that someone with a working (fresh v4.0 install and/or Update from 3.4 > 3.4.1427 > 4.0) post their "phpinfo.php". More contribution more data I suppose. 

You probably want to remove sensitive information before posting it though. I appreciate the help. 

I'm aware of the version Yeti posted but the filesize is rather large for me currently.

**Comment by kpaulaha** [comment]
phpinfo of server running fresh installation of 4.0
[phpinfo.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/821328/phpinfo.zip)

**Comment by ldgbc** [comment]
Thanks kapula. I'm slowly going through it and trying to see the differences.

Will report back.

**Comment by easaw** [comment]
I run MAMP Pro
PHP 7.0

I get these errors and no tables added to my DB

[11-Mar-2017 22:27:52 Europe/London] PHP Notice:  Use of undefined constant ROOT_DIRECTORY - assumed 'ROOT_DIRECTORY' in /Applications/MAMP/htdocs/y/include/ConfigUtils.php on line 165
[11-Mar-2017 22:27:52 Europe/London] PHP Stack trace:
[11-Mar-2017 22:27:52 Europe/London] PHP   1. {main}() /Applications/MAMP/htdocs/y/install/Install.php:0
[11-Mar-2017 22:27:52 Europe/London] PHP   2. require_once() /Applications/MAMP/htdocs/y/install/Install.php:19
[11-Mar-2017 22:27:52 Europe/London] PHP   3. require_once() /Applications/MAMP/htdocs/y/include/main/WebUI.php:12

**Comment by easaw** [comment]
I mean: the interesting thing is if you look at the Minimum Server Requirements, then look at the  image below, in the **GitStable demo** you get completely different results...

_Why have server requirements if the Stable Demo ignores them?_

![gitstable_php](https://cloud.githubusercontent.com/assets/17411112/23827426/330dcc62-06ab-11e7-8889-7040fddfcf46.jpg)

**Comment by easaw** [comment]
Add to that the **Git Master** demo which has yet again different settings, it's completely confusing!

**Please can someone recommend PHP settings for YetiForce 4.0?**

![gitmaster-yeti](https://cloud.githubusercontent.com/assets/17411112/23827471/10b3c1fc-06ac-11e7-89db-b1df89a26cec.jpg)

**Comment by easaw** [comment]
@idgbc @reeid @PercyP 

Please see this for PHP 7.0.0 (Some settings are for MAMP) INI which I can confirm working with YetiForce 4.0

Some sections will read 
`error_log = "MAMP_php_error_log_MAMP"`
or
`extension_dir = "MAMP_extension_dir_MAMP"`
for example

**You will need to adjust this if you aren't using MAMP**

I will attempt to configure it for my Ubuntu server and re-upload when it's working.

[phpini_7.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/836233/phpini_7.txt)
