### ISSUE TITLE
How to create a currency that is not on Yeti list?

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#4066]
#### Issue

I will need to create a price list using a currency that is not on yeti list. 
Also, the currency symbol are three letters, not a sign. 
How can I make this thing happen.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
In which place? Take a screenshot

**Comment by PDMeira** [comment]
We just need to create a new currency on Yeti that is not on the list, and be available on the price list and on the sales opportunities.

<img width="1274" alt="currency_e_info_advancedmd_com_rs_802-zjp-486_images_advancedmd-eguide-macraguide_pdf_mkt_tok_eyjpijoiww1obu5uqtbzv0l5wtjvdyisinqioijvngxyzw96k29qsdzoyw4wquthxc9xve1pr3bvk0tkvny1nhzctwnscdnnzugztwywrdh6wlnpbjjtdxo0vdnztgpkdjfpmnc0ynnwbghzd0" src="https://cloud.githubusercontent.com/assets/12361370/23233042/88adda74-f91b-11e6-9ab6-7b5f5e68406e.png">
<img width="1268" alt="products_-_list" src="https://cloud.githubusercontent.com/assets/12361370/23233043/88af4724-f91b-11e6-8fa1-612c480a8830.png">

**Comment by PDMeira** [comment]
anyone can help on this?

**Comment by PDMeira** [comment]
More information needed?

**Comment by mariuszkrzaczkowski** [comment]
duplicate
https://github.com/YetiForceCompany/YetiForceCRM/issues/3647
