### ISSUE TITLE
[API] new method "Query" or add criteria to "RecordList"

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#4068]
#### Actual Behavior

Currently, "RecordList" returns all records.

#### Expected Behavior

Wish for API / webservice:
Have a method or additional parameter for RecordList, to return only row based on a criteria (WHERE part of SQL)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by ezbank** [comment]
.

**Comment by mariuszkrzaczkowski** [comment]
Added https://github.com/YetiForceCompany/YetiForceCRM/commit/714fa5ba2d2d47c013de10705147ab018b7163d9
