### ISSUE TITLE
[bug] - priviliges of user 

### ISSUE THREAD

**Issue by deko33** [YetiForceCompany/YetiForceCRM#407]
I installed fresh YetiForce 1.3 and try to use "profile" to control actions that users can perform on records and also restrict his access to specific modules/fields. This doesn't work. 
So I checked once again instruction how it was in Vtiger (https://wiki.vtiger.com/vtiger6/index.php/Profiles#Defining_permissions) and follow it. The same issue. 
Can you check this... In my organization there is several levels of people which have to have different privileges so can’t work with Yetiforce...

By the way, it is nice piece of work and your CRM is magnificent, still needs a lot of work but I thing that is going to be number one on open license...

**Comment by bpabiszczak** [comment]
1. Privileges work differently in YetiForce than they do in Vtiger.
2. Many mechanisms were not described in Vtiger, some of them were changed, improved and fixed.
3. Unfortunately, I don’t understand what kind of problem you described, if you would like us to check it, I ask you to:
 - Login to https://test.yetiforce.com/
 - Set privileges according to your needs.
 - Describe which user sees which data differently or doesn’t see at all [a link with data and screen shots]

**Comment by witer30** [comment]
Thanks for your feedback. Simply followed Vtiger as Yetiforce base on vtiger. 
I did as you advised. Please check as below:
user: test
password: Test1234
I wanted to switch off module invoices and opportunities for tests as it is in profile name "Test-user".
When login to yeti user do not see anything besides "database/call history" and "groupcard"...
But should be much more options.
So it is doesn’t work... 
Notice here that others have similar issue...

**Comment by waw555** [comment]
Add role in menu
![menu](https://cloud.githubusercontent.com/assets/1402355/6795524/ec298310-d202-11e4-9fc7-8f181a99ffbb.JPG)

**Comment by witer30** [comment]
thanks, sorry for the problem
