### ISSUE TITLE
Projecttemplates - revive the module

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#4083]
With 4.0 the module "project templates" is gone. 

Can I export it from 3.x series, so I can integrate it back on my own?

And btw.: why was it removed?

**Comment by paula-w** [comment]
All the modules that were badly designed and needed to be rewritten, but are not used by us, were removed. We will never bring this module back, and if we add it again it will work in a different way, and won’t really have anything to do with the old module.
