### ISSUE TITLE
[PL]Faktury nierozliczone

### ISSUE THREAD

**Issue by nnewrulez** [YetiForceCompany/YetiForceCRM#4092]
Jedną z najważniejszych funkcjonalności w systemach sprzedażowych jest kontrolowanie płatności za faktury. W yetiforce wpłaty i wypłaty nie można spiąć z żadnym dokumentem sprzedażowym/zakupowym, ale to dosyć łatwo można sobie zrobić w konfiguracji. Problem zaczyna się pojawiać w momencie gdy chcemy klientowi wyrzucić faktury nierozliczone na podstawie wpłat. Może się pojawić sytuacja płatności częściowych lub płatności jednorazowych. Czy macie może pomysł w jaki sposób wyrzucić klientowi faktury nierozliczone?

**Comment by bpabiszczak** [comment]
Wpłaty muszą być połączone z fakturą. NA fakturze mamy kwotę należności i saldo. Na kliencie mamy kwotę należności i saldo. Proste generowanie raportami i wszystko wiemy :]
