### ISSUE TITLE
Welcome to YetiForce 4.0!

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#4093]
## We proudly present to you YetiForce 4.0 LTS.
After long months of hard and intensive work we created a system so unique and innovative, that no other open source system can compete. The list of all new changes, features, and fixes we introduced is impressive, and YetiForce is, as always, entirely free and available for everyone. No limitations, no hidden fees.

We were able to achieve all of this thanks to our innovative product building strategy, our community, and amazing clients –  we thank you, YetiForce wouldn't exist without you.

### LTS
Version 4.0 is marked as LTS [Long-Term Support], which in practice means that for 12 months we will release critical fixes for the system. It applies only to fixes related to security issues and problems with using all the tools available in the system.
We plan to release new versions once a month, and new LTS versions once per year at the end of each year [that is why 4.0 will be supported until the end of 2017, but we can extend that period if there is great interest in this version].
We encourage you to to check all the [release dates](https://github.com/YetiForceCompany/YetiForceCRM/milestones) for new versions.
Please bear in mind these are only assumptions, and therefore the dates might change.

### LINKS
- YetiForce 4.0 – [GitHub]( https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.0.0)
- YetiForce 4.0 – [SourceForge](https://sourceforge.net/projects/yetiforce/) 
- YetiForce update package [3.4 → 4.0](https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%203.x.x/3.4.0_to_4.0.0) 

### UPDATE & REQUIREMENTS
We would like to remind everyone that **updates should first be executed on a test version**, and only then on the production version [you should always have a backup copy of your environments].
- The list of current web server requirements necessary for version 4.0 to work properly can be found [here](https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html). 
- A detailed description of the installation process can be found [here](https://yetiforce.com/en/implementer/installation-updates/176-system-update.html). 
- If you want us to update your system, we encourage you to purchase [this package](https://shop.yetiforce.com/en/migration/14-migration-vtiger-yetiforce.html).

### CHANGELOG
- Due to it’s size, the list of all [changes introduced in version 4.0](https://yetiforce.com/en/developer-documentation/changes/219-yetiforce-4-0.html) can be found on our website.

If you want to support us – you can find the **DONATE!** button on [our website](https://yetiforce.com/en/). We're a small company, and all donations are important to us. You can also buy one of our modules. Remember that all funds collected from selling modules are going to be spent on the development of new features in the system.

**Comment by reeid** [comment]
Paula, is it updated version comparing to the one published on 14 Feb?

**Comment by paula-w** [comment]
@reeid - no, it's about the one published on the 14th, sorry for the delay.
