### ISSUE TITLE
Not showing custom field label generating a PDF model

### ISSUE THREAD

**Issue by Alfreduco** [YetiForceCompany/YetiForceCRM#4095]
#### Issue
Hello. I'm trying to generate a PDF model for a custom module I created, but label field tags are not shown in the final pdf. 

Everything else seems to work well, including value field tags, but not the custom fields label tags.

#### Actual Behavior
%customfieldname% it's replaced by nothing in the final PDF (including in default modules PDF models)

#### Expected Behavior
I expect to find the corresponding Custom Field Label in the generated PDF

#### How to trigger the error
Generating a PDF with a custom field label tag.

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Anyone
* Environment name and version: PHP Version 5.6.4-4ubuntu6.3
* Operating System and version: Ubuntu 15.0.4

**Comment by mariuszkrzaczkowski** [comment]
Does the bug exist in the latest development version?
