### ISSUE TITLE
How to make an custom last activity date in contact?

### ISSUE THREAD

**Issue by medotron** [YetiForceCompany/YetiForceCRM#4096]
1 I would like to create an "last activity date" in contact module. YT4, try to use "value from related module" related cooperation email create time, but it got multiple value from there. 

Is there any other way to make it?

2 how to calculate email contact count, use cooperation email module?

**Comment by mariuszkrzaczkowski** [comment]
Each question in a separate issue

**Comment by mariuszkrzaczkowski** [comment]
1. It already exists and the field is called "Event"
