### ISSUE TITLE
cannot edit webservice application

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#4098]
#### Issue

after creating a webservice application a click on the edit button will show the "new record" window

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by ldgbc** [comment]
I believe v4.0 removed Webservice. You have to use API/Rest now.

**Comment by migoi** [comment]
Yes I know. But this is the part where you create login for that API/Rest. So it should work to edit already defined entries.

**Comment by konadrian** [comment]
Fixed by https://github.com/YetiForceCompany/YetiForceCRM/commit/6fac403b615f6018b0fa9eba5bd47a43af09e7d0
