### ISSUE TITLE
Cannot send mass email. SQLSTATE[HY000]: General error: 1364 Field 'from' doesn't have a default value

### ISSUE THREAD

**Issue by medotron** [YetiForceCompany/YetiForceCRM#4099]
#### Issue

Cannot send mass email, check chrome error show----SQLSTATE[HY000]: General error: 1364 Field 'from' doesn't have a default value↵The SQL being executed was: INSERT INTO `s_yf_mail_queue` (`to`, `subject`, `content`, `smtp_id`, `status`, `owner`, `date`) VALUES ('..........

#### Actual Behavior

Click send button does not occur any thing. 

#### Expected Behavior

Click send button does not occur any thing. I already setup 2 email smtp server configuration. one is set as default. 

#### How to trigger the error

1.
![image](https://cloud.githubusercontent.com/assets/25944878/23299820/fef423f2-fabd-11e6-8806-729b214742e1.png)

2.
![image](https://cloud.githubusercontent.com/assets/25944878/23299849/14a51b3e-fabe-11e6-9c64-df618cb05e07.png)

#### Your Environment

* YetiForce Version used:yetiforce 4
* Browser name and version:chrome 56
* Environment name and version:digitaloncean ubuntu 16.04 php7+apache
* Operating System and version:mac 10.11

**Comment by kpaulaha** [comment]
Works fine on our server, both with cron and manual sending.

**Comment by medotron** [comment]
it seems the checked item does not work.  Am I right? Or I can revise database directly?

**Comment by medotron** [comment]
did I missing some configuration??? Where can I set the from address ??

**Comment by medotron** [comment]
I test it in my local ubuntu 16.04, that works the same, display same error, so I just guess, it was my fault ,missing some configuration about mass email sending. So is there anyone who can help, I need set from email address?

**Comment by kpaulaha** [comment]
![smtp](https://cloud.githubusercontent.com/assets/10330264/23329254/ba33957e-fb3d-11e6-8fe7-546fa330f3e4.png)
