### ISSUE TITLE
[Bug] Change sequence field - custom module - block "Basic Information"

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#4103]
Version 3.4 and 4 stable - developer

when you move all the system fields from the "basic information" block to another block the module "LayoutEditor" crashes.

![gifrecord_2017-02-24_170310](https://cloud.githubusercontent.com/assets/18703633/23311085/17fc5cf6-fab5-11e6-8447-d925080109fb.gif)

**Comment by PercyP** [comment]
@nic86 

what application do you use to create these video clips to show issues?

**Comment by nic86** [comment]
[byzanz](https://github.com/GNOME/byzanz)
[ubuntu byzanz](https://wiki.ubuntu.com/CreatingScreencasts)
[man byzanz](https://linux.die.net/man/1/byzanz-record)

**Comment by kpaulaha** [comment]
An other is http://www.screentogif.com/
