### ISSUE TITLE
Send email templates directly from leads/contacts/organisations

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#411]
My users mentioned that going to Roundcube before sending email templates is a unnecessary step. Because in most cases the templates do not need editing they would prefer to send them directly from the contact record via a pop-up select menu.

**Comment by bpabiszczak** [comment]
Today we added an option of manual start for workflows. It allows to do many things, including the ones you described - automatic sending of emails whithout the need to go to the Mailbox. It also allows to generate To Dos from the Calendar which will be added after a click.
