### ISSUE TITLE
YF v4 - Picklist: Save Order is not working

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4112]
I have also tested this in the yetiforce demo and the problem exists there too.

When adding new items to a picklist via the Standard Modules/Picklist and then moving the new items around (i.e. to put them in the correct alphabetical position) then clicking 'Save Order' the changes are not implemented. The item remains in the order it was added - in this case at the bottom of the list - see image. 
![sortproblem](https://cloud.githubusercontent.com/assets/10598886/23331158/0756a7a0-fb58-11e6-8ced-1f6f2f567813.png)

In my test example I moved my 2 new entries to the top of the picklist and then clicked Save Order. Then went to the Leads module and opened the Lead Source picklist and the items stilled showed at the bottom of the list. When Save Order is selected it should keep the new ordering.

**Comment by nic86** [comment]
see this #4022
