### ISSUE TITLE
MYSQLND cannot be installed on popular web hosting servers

### ISSUE THREAD

**Issue by klw-sc** [YetiForceCompany/YetiForceCRM#4136]
#### Issue
The use of the PHP library MYSQLND is not supported on some of the larger hosting sites - for example SiteGround. That mean YetiForce version 4.x will not run on their shared servers but require a dedicated server which is considerably more expensive (from around $5/mth for a shared server to a minimum of $329 /mth, so a show stopper for me if I stay with SiteGround (which hosts all my sites, domains etc)).

https://www.siteground.com/dedicated-hosting.htm

The official SiteGround response is copied below:

"PHP module MYSQLND libraries is not present on our shared and Cloud servers and can not be installed due to the level of access needed."

"This module can only be installed on Dedicated Server with root access, which will allow you to set it up. Note, that you will need to add the module and libraries required for your project. "

Is there any option or work around using the MYSQLND library? I expect when the latest Softaculous release 4.x is available it will also fail on several hosting providers sites as a result of using this lib. I would really like to use YetiForce over VTiger, but for me, this is becoming a show stopper. Any help or options much appreciated.

Have others installed V4.x successfully on shared web hosting sites successfully ? If so which ones? I am located in Australia, so prefer servers closer by if possible. Thanks!

#### Actual Behavior
Unable to login to the server. I can install version 4.x I just cannot login (there was a previous thread on this see below:

https://github.com/YetiForceCompany/YetiForceCRM/issues/4028

#### How to trigger the error

1. Install version 4.x - you will note one of the dependencies is not supported, MYSQLND not available
2.
3.

#### Your Environment

* Version 4.0
* Doesn't matter
* SiteGround shared server
* Linux

**Comment by ldgbc** [comment]
Hi @klw-sc good (bad) to see another soul trap in the v3.4 loop. 

I'm in the same condition as you where my shared hosting does not have MYSQLND libraries which break the website from my experience.

Did you manage to update to v3.4.1427? If you did, try logging out and back in, it should bugged like my one is.

As for the work-around, please this thread: https://github.com/YetiForceCompany/YetiForceCRM/issues/4100 where I am manually trying to cheat the system into a Update patching. Not progressing so far because my coding is limited to English skill and pattern I can see in the coding.

If you follow the trail of issue other and I have posted you might be able to find some clue that could work on your hosting, Siteground and not mine or others hosting.

Anyway with that said, don't choose Hostgator. My experience with them has been terrible. Come near end of the year I be looking for an alternative that hopefully isn't as bad as they are.

**Comment by medotron** [comment]
Mybe you can try VPS, like digitalocean etc, also very cheap and stable.

**Comment by klw-sc** [comment]
Thanks, but my concern is if the developers do not resolve this then the source may be forked again or have some patch added by a user that will create an ongoing maintenance issue as the code develops and this can loose momentum for this program.  Either the developers want YetiForce to be able to run on shared  web hosting sites or not, if they don't care or or targeting only for high end or self hosted users (supporting their paid customer base) then I expect the take up of YetiForce will drop quickly (not good) and with VTiger 7 opensource to be released very soon, will mean less migration to YetiForce for anyone still using VTiger (like me). There is a great opportunity to get YetiForce into the masses but this lib issue is a dead end for many, I can't risk my business on an app that cannot natively run on most shared web hosting platforms and will already need a work around/patch just to install it or a $300/mth dedicated server from a $5/m plan I am currently on. 

Hopefully the core dev team can include an option in their official release to retain the old lib so we don't need to try and work around this issue, perhaps release a high performance version (using MYSQLND)  and a standard version (using the previous libs)?

**Comment by klw-sc** [comment]
Sorry, meant to add comment, not close this issue...

**Comment by mariuszkrzaczkowski** [comment]
Library mysqlnd is required from version 2.1 but has not been checked. I presume that your problem is elsewhere only you You can not find it. this error requires analysis programmer and full access to the server, and paid support

**Comment by mariuszkrzaczkowski** [comment]
ps.
CRM is a free, pay at least as good and safe hosting

**Comment by klw-sc** [comment]
Got is working on www.bluehost.com on their shared server. If anyone wants to know what is needed let me know, steps are not straight forward. But this is their standard shared hosting plan, so good news if you want to keep costs down.

**Comment by ldgbc** [comment]
@klw-sc After 3 months of hiatus I decide to give Yeti another go with hope that these issue is resolved and it didn't. I tried a few method listed by other user but all fail in the end and end up with the same result 3 months ago.

Version 4.1 doesn't seem to solve it either for me (development version). But it good to hear that bluehost version is working, it work fine for v4 and v3.4 upgrade to v4 for you @klw-sc ?

On their front page it state: Starting at $7.99 $3.95/month* 

Is that one good enough or will I have to use some other plans/account? Two more month till my current expire so looking forward to getting rid of Hostgator. I haven't learn how to move server yet though, hopefully my new host will provide free transfer service or something.

**Comment by energylevels** [comment]
the community and number of users would be a lot bigger if you didn't use the mysqlnd library.

**Comment by bpabiszczak** [comment]
We improve it.

**Comment by energylevels** [comment]
yes but a lot of hosts still don't support mysqlnd unfortunately

**Comment by Affan-Arshad** [comment]
@klw-sc How did you get mysqlnd working on bluehost?

**Comment by Britford** [comment]
I too would like to try out YetiForce, but am blocked by mysqlnd.

**Comment by ldgbc** [comment]
@Britford I'm using the offline XAMPP solution. Either that or you have to pay for Delicate or VPS hosting.
Then I just Port Forward for Internet access.

**Comment by okridgway** [comment]
@klw-sc How did you finally manage to get it working?

**Comment by acsinsurancegroup** [comment]
@klw-sc I've used old and new versions on 1&1 cloud and dedicated servers and have never had issues. Instead of only paying $5 maybe upgrade to a cloud VPS with them as they are very reasonable. Mine is like $50 per month just a thought.

**Comment by IntenseHosting** [comment]
A web host, or web hosting service provider, is a business that provides the technologies and services needed for the website or webpage to be viewed in the Internet. Websites are hosted, or stored, on special computers called servers. ... If you do not have a domain, the hosting companies will help you purchase one.
