### ISSUE TITLE
How to use auto assign records??

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#4138]
Pls explain.. how to use auto assign records..??

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by basanthagarwal** [comment]
The real problem is ... when i'm are uploading records in any module, it is getting assigned to me only, even though there is field .. which indicates "Assign To" username ... version 4.0 is ignoring username and assigning all records to person who is uploading. 


This is very crucial as record owners cannot be assigned manually.

**Comment by migoi** [comment]
i think i may already fixed this. I was in the same need for creating records from API.

**Comment by ezbank** [comment]
.

**Comment by mariuszkrzaczkowski** [comment]
Check this patch should fix your problem
https://github.com/YetiForceCompany/YetiForceCRM/pull/4552
