### ISSUE TITLE
Typical Hierarchy Setup for Salesrep

### ISSUE THREAD

**Issue by Felodriozola** [YetiForceCompany/YetiForceCRM#4143]
The Scenario

My company has 1 sales teams; and the Admin, , should be able to see everything this is working. But the rest of the sales reps  should only be allowed to see their own records for example in the module accounts , invoices etc.
theres is a way to achieve that? 
Ive tried changing the permissions but not worked because they still can see others records names for example . 

thanks in advance!!

**Comment by kpaulaha** [comment]
![sharing rules](https://cloud.githubusercontent.com/assets/10330264/23364261/02709218-fd07-11e6-9783-8b80ebbfd246.png)

**Comment by Felodriozola** [comment]
@kpaulaha thanks, but ive already do that and the sales user still can see the admin and other accounts. 
![1](https://cloud.githubusercontent.com/assets/5709632/23364716/774c25d6-fd00-11e6-8930-0c7ab0b3c4be.jpg)

**Comment by kpaulaha** [comment]
@Felodriozola Then you have assigned teh users some other rights. Belov same contacts for 2 users and admin set as private.
![contacts - list1](https://cloud.githubusercontent.com/assets/10330264/23365903/83d05b8a-fd0d-11e6-926d-5b99b7f7a446.png)
![contacts - list3](https://cloud.githubusercontent.com/assets/10330264/23365911/89a19d1c-fd0d-11e6-82e3-90222af4d008.png)
![contacts - list2](https://cloud.githubusercontent.com/assets/10330264/23365915/8ff00262-fd0d-11e6-92a0-c028bcf608df.png)

**Comment by Felodriozola** [comment]
@kpaulaha yeah its strange but still not working for me, i´ve just created a fresh installation and follow the the same steps and still happening the same  .thanks again 👍

**Comment by kpaulaha** [comment]
@Felodriozola That is strange. As I remember that's a feature that has been working without problems during all yf versions.

**Comment by mariuszkrzaczkowski** [comment]
Check the configuration requirements and send screenshots.
 Test it on gitdeveloper.yetiforce.com
Check logs when I enable permissions may be some error
