### ISSUE TITLE
[Question] change dateformat for date('today') from yyyy-mm-dd to dd.mm.yyyy

### ISSUE THREAD

**Issue by ahmido** [YetiForceCompany/YetiForceCRM#4145]
Hello @all,

is there a way to add a dateformat parameter like dd.mm.yyyy to the date('today') function?
thanks for help

<img width="906" alt="error_yf" src="https://cloud.githubusercontent.com/assets/7672820/23374274/e29c370e-fd23-11e6-9dc2-f0605b3e4c67.PNG">

**Comment by kpaulaha** [comment]
Change the date format in user details #4147

**Comment by ahmido** [comment]
Thanks for reply. I have changed the date format in user details but still not working.

**Comment by mariuszkrzaczkowski** [comment]
This can only be done by modifying the code
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/com_vtiger_workflow/expression_engine/VTExpressionEvaluater.php#L179
