### ISSUE TITLE
Custom Widgets don't work since 4.0.0

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#4149]
Hi guys,

I paid a suport package to make some custom widgets and since the 4.0.0 upgrade they don't work anymore.
I got this kind of error
![image](https://cloud.githubusercontent.com/assets/1357727/23412343/88713aba-fdd5-11e6-861f-7aa0c6d26d3d.png)
![image](https://cloud.githubusercontent.com/assets/1357727/23412384/a4ce85a0-fdd5-11e6-9f41-e41ed0092bde.png)
![image](https://cloud.githubusercontent.com/assets/1357727/23412408/b23f86e4-fdd5-11e6-8a60-66bb51c32361.png)

Any idea?
Thank you

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/843959c50cc518b468821371f530b25ef1b8efbf

**Comment by rskrzypczak** [comment]
replace:
 includes\fields\Owner => \App\Fields\Owner
 includes\Language => \App\Language

**Comment by Raggazzoo** [comment]
Thank you so much =)
