### ISSUE TITLE
Mass sms - relation parent record

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#4153]
Version: 3.4 - 4 stable and develop

when a mass sms is sent (eg to multi contacts) the relation with parent record is not created.

[MassSaveAjax.php](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/SMSNotifier/actions/MassSaveAjax.php#L54)

it would be changed with this:

```
$sourceModule=$request->get('source_module');
SMSNotifier_Record_Model::SendSMS($message, $toNumbers, $currentUserModel->getId(), $recordIds, $sourceModule);
```

**Comment by migoi** [comment]
do you need this in a pull request?

**Comment by nic86** [comment]
as you wish.
