### ISSUE TITLE
[question][api][4.0.58] How to configure htaccess for webservice (API)?

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#4154]
YetiForce installed in... "/var/www/html/objetivos/"

User created from the module: "Web service - Applications" (WebserviceApps), and the user is correctly identified when I send directly to "api/webservice.php"

1. ![image](https://cloud.githubusercontent.com/assets/18419851/23456784/ca230fbe-fe6c-11e6-9f6b-541e8c13a0da.png)

The problem I have is when I put the url:
- /api/webservice/Users/Login
- /api/webservice/Methods
- /api/webservice/Contacts/RecordsList
with the following error...

2. ![image](https://cloud.githubusercontent.com/assets/18419851/23456751/a7779408-fe6c-11e6-9491-f2b45d095e1f.png)

Redirection does not work and the redirection module is installed "mod_rewrite"

3. ![image](https://cloud.githubusercontent.com/assets/18419851/23457867/95a9dd9e-fe71-11e6-991c-ab634cd4a66d.png)

#### Your Environment

* YetiForce Version used: 4.0.58
* Browser name and version: Chrome 56 Extension - Postman
* Environment name and version: Apache 2.4.25, PHP 5.6.30, MariaDB 10.1
* Operating System and version: CentOS 7.3

**Comment by nic86** [comment]
get list of module active in apache2 server on debian/linux:
```
apache2ctl -M
```

Enable rewrite module on debian/ubuntu:
```
a2enmod rewrite
service apache2 reload
```

**Comment by migoi** [comment]
please show your apache config for this domain. As default the .htaccess rewrite rules would not be used (or allowed) so something like:

~~~
	<Directory /var/www/yeti>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride All
	        Require all granted
	</Directory>
~~~
must be added

**Comment by WalterLuis** [comment]
Thank you for your answers,

The problem was that I had "AllowOverride None", I changed it to "AllowOverrride All" and it works.
