### ISSUE TITLE
fix typo - search mail - default workflow helpdesk

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#4155]
version: 3.4 and 4 stable,develop

fix typo "heldDesk => helpDesk" in all function
[helpdeskworkflow](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/HelpDesk/workflows/HelpDeskWorkflow.php#L36)

in the same file [helpdeskworkflow](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/HelpDesk/workflows/HelpDeskWorkflow.php#L20), if a MM relation is created (get_related_list) from Contact to HelpDesk, the query for search email would be:

```
$sql = '(SELECT `relcrmid` as contactid FROM `vtiger_crmentityrel` WHERE `module` = ? && `relmodule` = ? && crmid=?) UNION (SELECT `crmid` as contactid FROM `vtiger_crmentityrel` WHERE `relmodule` = ? && `module` = ? && relcrmid=?) LIMIT 50;';
$result = $db->pquery($sql, ['HelpDesk', 'Contacts', $id,'HelpDesk', 'Contacts', $id]);
```

**Comment by migoi** [comment]
that would affect a lot of database updates. On a quick scan there would be ~50 places to fix that typo

**Comment by nic86** [comment]
you are right, it would be better to fix it even if it doesn't affects the way the program works.
