### ISSUE TITLE
[PL] Usuwanie operatora

### ISSUE THREAD

**Issue by slawhodu** [YetiForceCompany/YetiForceCRM#4156]
Po usunięciu operatora dalej jest w bazie (np. w rolach) i nie można wprowadzić na nowo użytkownika o tym samym adresie.
Na rolach jest stan 'Nieaktywny'. W operatorach na 'nieaktywni' - pusto.

Jak 'do końca' usunąć operatora?

**Comment by bpabiszczak** [comment]
A czym jest operator? [SMS?]

**Comment by slawhodu** [comment]
Operator czyli użytkownik, user.
Po zmianie na 'nieaktywny' znika zupełnie z widoku. Nie widać na liście nieaktywnych.
A ja potrzebuję takiego jednego przywrócić a innego zupełnie usunąć (błąd przy zakładaniu).
I jeszcze nie da się ZUPEŁNIE usunąć użytkownika.

**Comment by bpabiszczak** [comment]
Jaka wersja systemu?
Co w logach widzisz? 
Czy błąd występuje na wersji Stable i Geveloper?
