### ISSUE TITLE
[Question] Migrating local yeti instance to shared hosting

### ISSUE THREAD

**Issue by rxstriker** [YetiForceCompany/YetiForceCRM#4160]
Hello, I'm trying to migrate my local instance of YetiForce CRM to a shared hosting, but it's failing to login the existing user. System log indicates that the user 'admin' was not found in 'vtiger_users' but I've checked and the user exists in database
I've set up my local instance with the exact settings that would be used in the shared hosting. Same database name, port, user and password. User 'admin' hashes are identical, I've checked the resulting encrypted passwords and they are also identical.
The migration process was done by sending all the file of my local instance to my shared hosting through FTP, and then exporting the local database to a SQL file and importing it into my shared hosting.

Any idea about what's happening? Is there something I should clear? A database table or cache maybe?

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version: 
* Operating System and version:

**Comment by bpabiszczak** [comment]
Check if you have mysqlnd library in PHP

**Comment by rxstriker** [comment]
Yes I do.
![capture](https://cloud.githubusercontent.com/assets/23050598/23516235/89ac5438-ff64-11e6-81e1-b4eaae16ec24.PNG)

**Comment by bpabiszczak** [comment]
Try turn on nd_pdo_mysql.

**Comment by rxstriker** [comment]
That's it! Thank you @bpabiszczak 
It seems that nd_pdo_mysql conflicts with pdo_mysql and both can't be on that the same time. But by turning off pdo_mysql and turning on nd_pdo_mysql, it worked and I was able to login.

**Comment by ldgbc** [comment]
I see these setting in myphp.ini setting but not sure how to enable it.

[Pdo]
; Whether to pool ODBC connections. Can be one of "strict", "relaxed" or "off"
; http://php.net/pdo-odbc.connection-pooling
;pdo_odbc.connection_pooling=strict

;pdo_odbc.db2_instance_name

```
[Pdo_mysql]
; If mysqlnd is used: Number of cache slots for the internal result set cache
; http://php.net/pdo_mysql.cache_size
pdo_mysql.cache_size = 2000

; Default socket name for local MySQL connects.  If empty, uses the built-in
; MySQL defaults.
; http://php.net/pdo_mysql.default-socket
pdo_mysql.default_socket=
```

**Comment by rxstriker** [comment]
Supposedly, to enable pdo you just need to follow this guide:
http://php.net/manual/en/pdo.installation.php

On my shared hosting this was all done through GUI.
