### ISSUE TITLE
Import Workflow Error

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#4161]
Hi,

One of my workflow doesn"t work since 4.0.0 so I exported it with the exporting tool.
After the import I got this error in the workflow manager
![image](https://cloud.githubusercontent.com/assets/1357727/23518493/e556edf2-ff73-11e6-9ee7-0f62b49c8f1c.png)

What can I do?
Thank's

**Comment by migoi** [comment]
does this file exist and can be accessed by webserver?
e.g. show us output of 
~~~bash
ls -la /var/www/yetiforce/modules/com_vtiger_workflow/
~~~

**Comment by Raggazzoo** [comment]
Hi,

Thank's for the answer =)

There is the output
![image](https://cloud.githubusercontent.com/assets/1357727/23544218/60449532-fff6-11e6-83cb-f0ac75c44075.png)

**Comment by Raggazzoo** [comment]
No idea? I'm stuck because my users cannot create Opportunities

**Comment by Raggazzoo** [comment]
Please Help =(

**Comment by Raggazzoo** [comment]
Can I just delete the workflow in my database?

**Comment by migoi** [comment]
Sorry, didn't notice the follow up.

Next is:
~~~bash
ls -la /var/www/yetiforce/modules/com_vtiger_workflow/tasks
~~~

since it is missing the file
tasks/stdClass.php


However:
This does not exists here for me, so it would ran into the very same problem here.

**Comment by Raggazzoo** [comment]
Thank's for the answer !

Finally I have deleted the workflow in the mysql table and create it manually in the workflow manager instead instead of import my XML.

And it works fine !
