### ISSUE TITLE
[Question] Get fields from other modules in PDF-Module

### ISSUE THREAD

**Issue by ahmido** [YetiForceCompany/YetiForceCRM#4162]
Hi @all 

is there a way to get fields from other modules in the PDF-Module?

Example:

We want to create PDFs in the module Accounts/Organisations, but we need fields like salutation from module contacts and other fields from module "products".

**Comment by ldgbc** [comment]
Currently no I believe.  Similar topic here: #3984

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3706

**Comment by paula-w** [comment]
You can only generate these fields from the modules that the system can automatically display based on the main modules. If some fields or modules are missing, then you have to implement it in the engine.
