### ISSUE TITLE
[Wish] integrate YetiForce with Elasticsearch

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#4164]
#### Idea

What about a module to use Elasticsearch as engine?

**Comment by bpabiszczak** [comment]
http://vtiger-crm.2324883.n4.nabble.com/Vtigercrm-developers-Email-marketing-scenario-td19362i40.html

**Comment by umbz** [comment]
So,   another's crm  have implemented this function. 
 You can define if a field is #elastic searchable# and you can set a priority.
