### ISSUE TITLE
Fatal Error: Class Linfo not found

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#4165]
#### Issue

In current developer branch:
~~~
PHP Fatal error:  Uncaught Error: Class 'Linfo\Linfo' not found in modules/Settings/ConfReport/models/Module.php:323
~~~

Seems the vendor/linfo stuff is missing for me.

How do I install / download this lib from inside YetiForce?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by nic86** [comment]
this is the repository in github:

[linfo library](https://github.com/jrgp/linfo)

**Comment by WalterLuis** [comment]
The easiest way for you to install the necessary libraries is to use the composer

step 1:
```
cd /var/www/html/YetiForceCRM
```
step 2:
install Composer from -> https://getcomposer.org/download/
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

step 3:
```
php composer.phar update
```

with that should work :)

**Comment by migoi** [comment]
:+1: 

Thx
