### ISSUE TITLE
[Bug] Add Service button still present in item lists after module is removed

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4166]
#### Issue

Add Service button is still present in item lists after module is removed. Adding a service to the list via button adds a field that searches for inexistent services and causes an error (access denied):
`
#0 include/main/WebUI.php(207): Vtiger_WebUI->triggerCheckPermission(Object(Services_Popup_View), Object(Vtiger_Request))
#1 index.php(21): Vtiger_WebUI->process(Object(Vtiger_Request))
#2 {main}
`

#### Expected Behavior

Button should disappear if module is removed. Optionally there should be an Add Item button to add an item to list that isn't a service or product.

#### How to trigger the error

1. Disable Service Module
2. Open the new Quote Form
3. Click Add Service on item list
4. Search for a Service

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Add screenshot where this button is
