### ISSUE TITLE
Problem, jump into fullscreen after click on LBL_SHOW_PREVIEW_E-MAIL

### ISSUE THREAD

**Issue by worldwidehigh** [YetiForceCompany/YetiForceCRM#4167]
#### Issue
No pop-up after click on LBL_SHOW_PREVIEW_E-MAIL Button. It immediately jumps into the fullscreen.

![unbenannt](https://cloud.githubusercontent.com/assets/20869581/23577966/54ea290a-00cc-11e7-918f-758d57e62264.png)

![unbenannt](https://cloud.githubusercontent.com/assets/20869581/23578007/d4154e26-00cc-11e7-98f0-eff5fb128885.png)

#### Your Environment

YetiForce Version used: Yetiforce 4.0 stable
Browser name and version: Chrome latest
Environment name and version: PHP 5.6
Operating System and version: Win 10

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/c198584fb81757220c73da63a4a5731a6e2ab208
