### ISSUE TITLE
Roundcube - use Sendmail instead of SMTP

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#4172]
#### Issue
Hi, I installed Yetiforce 4.0 on a 1&1 Webhosting account and discovered that 1&1 blocks all SMTP traffic.
While the SMTP configuration has an option for Sendmail, the Roundcube configuration has not and allways relies on SMTP.

Roundcube itself has a build-in feature to use Sendmail which is enabled if all SMTP statements are commented out or deleted in the configuration file.

#### Actual Behavior
Cannot save the Roundcube configuration if SMTP Server field is empty.

To enable Roundcube Sendmail, I had to manually delete the following statements in the configuration file “config/modules/ OSSMail.php”:
- $config['smtp_server'] 
- $config['smtp_port'] 
- $config['smtp_user'] 
- $config['smtp_pass'] 

#### Expected Behavior
Modify the Roundcube configuration module to allow the use of Roundcube Sendmail without manually modifying the configuration file.

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: Mozilla latest version
* Environment name and version: Apache / PHP 5.6.30
* Operating System and version: Linux

**Comment by mariuszkrzaczkowski** [comment]
Currently sending only work with smtp. 
You can try to modify the configuration file to send via sendmail should work although I did not test it

**Comment by setras** [comment]
sendmail works when I modify the config file.

I suggest an enhancement on the settings page to allow using sendmail without the need to manually modify the config file.

**Comment by joelbcampos** [comment]
Good morning.

The same thing happened to me.
I contacted the hosting administrator and had ip blocked, since the shared hosting firewall rules give false positives.

**Comment by paula-w** [comment]
@setras this is an idea for system development, you can order this feature if  your want. More info [here](https://yetiforce.com/en/github/issues/205-why-was-the-issue-ignored.html) & [here](https://yetiforce.com/en/github/issues/206-system-development-ideas.html).  
@joelbcampos if your problem still exists please open a new ticket, we can only help with one problem per issue.
