### ISSUE TITLE
I can not remove the notification

### ISSUE THREAD

**Issue by Zzik** [YetiForceCompany/YetiForceCRM#4189]
I can not remove the notification
<a target="_blank" href="http://radikal.ru/big/9w8oo2rms1ez4"><img src="http://s018.radikal.ru/i507/1703/c6/a6e95baa068dt.jpg" /></a>

**Comment by ahmido** [comment]
I think you can't delete notifaction if you marked it as read

**Comment by konadrian** [comment]
As @ahmido said you can't delete record markerd as read you can change this here:
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Notification/Notification.php#L15
@Zzik for the future please send gif in English and send yours gifs by github not externals websites
