### ISSUE TITLE
Kontakt Pole zgoda na mailing nieprawidłowa definiacja

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#42]
W anlizy tego pola wynika, że jest to pole opt out. To oznacza, że jeśli pole to jest niepuste (zaznaczone). mailing nie będziem możliwy. adres mailowy w takim przypadku nie przenosi się jako koipia ukryta do formatki maila. testowane na kontakcie. konieczna zmiana opisu pola na "brak zgody na mailing"

**Comment by bpabiszczak** [comment]
Nie sugerowałbym się tutaj tłumaczeniem EN które zostało odziedziczone. O ile dobrze pamiętam, to zmienialiśmy logikę działania tych pól kilka tygodni temu, a więc najprawdopodobniej nazwa EN jest nieprawidłowa.

Sprawdzimy to wkrótce.

**Comment by bpibiza** [comment]
W dniu 2015-01-03 o 14:27, Błażej Pabiszczak pisze:
>
> Nie sugerowałbym się tutaj tłumaczeniem EN które zostało 
> odziedziczone. O ile dobrze pamiętam, to zmienialiśmy logikę działania 
> tych pól kilka tygodni temu, a więc najprawdopodobniej nazwa EN jest 
> nieprawidłowa.
>
> Sprawdzimy to wkrótce.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/YetiForceCompany/YetiForceCRM/issues/42#issuecomment-68594891>.
>
Sprawdzałem funkcjonalność na zasadzie włącz -> wyślij; wyłącz -> wyślij.
Obawy potwierdzone.
Wymaga ponownego testu przez developera.

**Comment by waran70** [comment]
Any chance guys to write in EN? it will help community understanding issues :-)

**Comment by KatarzynaUlichnowska** [comment]
No problem, at the end of this ticket will write a summary in English.

**Comment by konadrian** [comment]
Testowane na wersji 1.2.58. Sprawdziłem wysyłanie e-maili w dwóch przypadkach: aktywowania portalu klienta dla użytkownika, oraz dodawania/zmieniania zgłoszeń (moduł HelpDesk). Jeśli opcja „Zgoda na kontakt mailowy” dla kontaktu/kontrahenta była włączona e-maile zostały wysyłane. Jeśli opcja była odznaczona to np. w przypadku zmian w zgłoszeniu,  e-mail nie był wysyłany. 
„To oznacza, że jeśli pole to jest niepuste (zaznaczone). mailing nie będziem możliwy.” Jeśli pole jest zaznaczone oznacza to wyrażenie zgody na wysyłanie e-maili.
Proszę o podanie szczegółów w jakim wypadku dochodzi do błędu.

ENG:
Tested on version 1.2.58. I checked sending e-mails in two cases: activated user portal for customer and added/changed tickets (HelpDesk module). If option “Permission to send emails” was marked for customer/account, e-mails were send. If option was unmarked, and some changes were done, then an e-mail wasn’t sent. 
If checkbox "Permission to send emails" is marked then e-mails will be send to this account.
Please provide more details about this error.
