### ISSUE TITLE
MailScanner - email binding missing 

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#420]
I am testing now email scanner, run cron and it works. In Scheduling there are information about timings as it should be...
Also email scanner is setup properly, action bind to email so it should work... But when send email from mail (contact email address) to user there is not binding - couldn't see it under contact.
Manual bind works properly, abut automatic way not... 

Can you advice what can I check to definitely exclude YetiForce bug?

**Comment by bpabiszczak** [comment]
Please check the latest version (under development) and see if it solves your problem. We fixed and improved a few things in the scanner and the changes also include automatic binding.
