### ISSUE TITLE
When Version 4 avalible on softaculous

### ISSUE THREAD

**Issue by aramxalil** [YetiForceCompany/YetiForceCRM#4204]
Hello Their 
when yeforce new version  avalible on  softaculous ?

**Comment by esaw01** [comment]
It won't be until it's stable for shared hosting. Which it isn't at the moment. I can't even upgrade my 3.4 install. Which I installed from Softaculous.

I.e. it's up to Softaculous, not YetiForce when it goes on there, maybe contact them.

**Comment by aramxalil** [comment]
thank you @esaw01

**Comment by KatarzynaUlichnowska** [comment]
Hello,
YetiForce 4.0 is finally available at Softaculous: https://www.softaculous.com/apps/erp/YetiForce
