### ISSUE TITLE
[PL] Pola słownikowe - Dodanie nowych wartości v.4.0.85

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#4211]
Przy próbie dodania nowych wartości w polach słownikowych występuje poniższy błąd :
 
Fatal error: Uncaught Error: Call to a member function getName() on boolean in /modules/Settings/Picklist/views/IndexAjax.php:110 Stack trace: #0 /include/runtime/Controller.php(90): Settings_Picklist_IndexAjax_View->getPickListValueForField(Object(Vtiger_Request)) #1 /modules/Settings/Picklist/views/IndexAjax.php(30): Vtiger_Controller->invokeExposedMethod('getPickListValu...', Object(Vtiger_Request)) #2 /include/main/WebUI.php(218): Settings_Picklist_IndexAjax_View->process(Object(Vtiger_Request)) #3 /index.php(21): Vtiger_WebUI->process(Object(Vtiger_Request)) #4 {main} thrown in /modules/Settings/Picklist/views/IndexAjax.php on line 110

Testowane na wersji gitdeveloper
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9

#### How to trigger the error

1. Konfiguracja systemu > Moduły standardowe > Pola - słowniki > Start
2. Wybrać z listy Wybierz moduł jakikolwiek moduł 
3.

#### Your Environment

* YetiForce Version used: 4.0.85
* Browser name and version: Mozilla 51.0.1
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
w najnowszej wersji deweloperskiej nie występuje ten błąd
