### ISSUE TITLE
[Bug] Custom field, entered illegal character

### ISSUE THREAD

**Issue by rxstriker** [YetiForceCompany/YetiForceCRM#4213]
#### Issue

Was trying to add custom field to a module (Goods Dispatched Notes), field name doesn't accept underscores "Illegal character"
![screenshot-yeti aliartalentos com-2017-03-06-11-55-07](https://cloud.githubusercontent.com/assets/23050598/23608985/cc7b2ba2-0263-11e7-9bbe-6f7a96284e64.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
check whether the end of the space, sometimes the copy is added

**Comment by rxstriker** [comment]
There is no end space, I typed the field name manually

**Comment by mariuszkrzaczkowski** [comment]
I checked on gitdeveloper and it works

![image](https://cloud.githubusercontent.com/assets/10198654/23969546/219e2df4-09c7-11e7-9ef2-3c6920eb8c8a.png)

**Comment by natpicone** [comment]
![schermata 2017-06-22 alle 14 34 27](https://user-images.githubusercontent.com/4753402/27434175-13204fd0-5758-11e7-91df-4f0984450342.png)

@bpabiszczak bug is still present on gitdeveloper ...
