### ISSUE TITLE
[PL] Problem z upgrade 3.4.1427 do 4.0 v2

### ISSUE THREAD

**Issue by ResqIT** [YetiForceCompany/YetiForceCRM#4214]
Podczas aktualizacji po wgraniu paczki przy próbie aktualizacji (...cache/updates/init2.php?from_version=3.4.1427&to_version=4.0.0)pojawia się info o błędzie serwera apache -błąd 500 w logach php - 
PHP Notice:  Undefined index: include in /var/www/html/vtlib/Vtiger/Unzip.php on line 80
PHP Notice:  Undefined index: exclude in /var/www/html/vtlib/Vtiger/Unzip.php on line 85(wiele razy te 2)
PHP Fatal error: Call to a member function addField() on boolean in /var/www/html/cache/updates/init2.php on line 713

log error apache
[Mon Mar 06 15:57:32.594577 2017] [:error] [pid 24500] [client ...:54560] PHP Notice:  Use of undefined constant ROOT_DIRECTORY - assumed 'ROOT_DIRECTORY' in /var/www/html/include/ConfigUtils.php on line 165, referer: http://...../index.php

#### Actual Behavior
HTTP ERROR 500
#### Expected Behavior
Update zakończony powodzeniem

#### How to trigger the error
1. Konfiguracja systemu > Moduły standardowe > Moduły - instalacja > Import
2.Akceptuję warunki licencji /TAK

#### Your Environment
* YetiForce Version used: świeżo postawione YetiForce 3.4 wraz z aktualizacją do 3.4.1427 v3
* Browser name and version: Google Chrome Wersja 56.0.2924.
* Environment name and version: Apache 2.4.18/PHP 5.6.30-7+deb.sury.org~xenial+15.6/mariadb 10.1
* Operating System and version: Ubuntu 16.04

Dodatkowo: Środowisko typowo testowe, świeża instalacja 4.0 przebiega bez problemu. Próbowałem wcześniej na nginx oraz php5.6-fpm niestety podobny rezultat (dlatego próba na apache2 teraz)

**Comment by zimart** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/4030 pisałem już o moich problemach...  Dobrze że nie tylko ja mam problem...

**Comment by bpabiszczak** [comment]
a dlaczego widać błędy PHP Notice, z tego wynika, że serwer jest źle skonfigurowany. Nie wiem czy błąd PHP Fatal error: jest konsekwencją błędu 500. Ktoś to musi zobaczyć i sprawdzić, proponuje najpierw poprawić u siebie ten błąd PHP Fatal error: Call to a member function addField() on boolean in /var/www/html/cache/updates/init2.php on line 713.

**Comment by ResqIT** [comment]
po zmianie error_reporting na zalecane wartości brak błędu w log, błąd 500 apache

**Comment by mariuszkrzaczkowski** [comment]
Sprawdź wersje  3.4.1427_to_4.0.0_v3.zip

**Comment by ResqIT** [comment]
Udało się :) 👍 🥇

**Comment by mariuszkrzaczkowski** [comment]
czyli miałeś problem z dodaniem pół sprawdź w logach co powodowało błąd i dodaj pole ręcznie

**Comment by ResqIT** [comment]
Problem polega na tym, że podczas testów robiłem to na czystych instalacjach, tj. bez dodatkowych własnych pól.... Konfiguracja tylko ta wymagana przez instalator..

> Your Environment:
YetiForce Version used: świeżo postawione YetiForce 3.4 wraz z aktualizacją do 3.4.1427 v3
Browser name and version: Google Chrome Wersja 56.0.2924.
Environment name and version: Apache 2.4.18/PHP 5.6.30-7+deb.sury.org~xenial+15.6/mariadb 10.1
