### ISSUE TITLE
[Bug] Deleting custom block Forwarding Address in Contacts module

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4215]
#### Issue

The Contact module has a custom block named Forwarding Address that I want to remove. But I cannot remove it because it says that the custom block has fields, fields that are built-in and I can't remove only disable. Is there a way to remove to block entirely?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
Easiest way to "remove" this block is to just hide it. You can do it in  Software configuration > Standard modules > Fields – Hide Blocks
