### ISSUE TITLE
purging / cleaning the CRM

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#4225]
We have some CRM's running since v1 and they are getting very big. We process more than 10.000 mails a year so it all adds up in the DB. Upgrading and backing up becomes a big task.

Wondering what the best option would be to slim down the CRM without loosing the mails on the IMAP mail server it self. Will removing them from from the corporate email list remove them from the mail server too or just in Yeti?

I assume that alle the notes connected to the contacts will remain there except we can not directly open the mails any more in the CRM?

Looking at the folders than OSSmailview is huge. An option to remove attachements would also help.

Any other suggestions to clean up after a few years?

**Comment by mariuszkrzaczkowski** [comment]
I added some important optimization, check that will help you

**Comment by zebrahosting** [comment]
Sounds good Mariusz, in which version are these and what are the solutions?
We are thinking of installing a clean 4.0LTS from scratch and import/export to get things clean again.

**Comment by bpabiszczak** [comment]
We will public Service Pack.

**Comment by zebrahosting** [comment]
Great and big thank you!
