### ISSUE TITLE
Size of item fields in Quotes

### ISSUE THREAD

**Issue by rxstriker** [YetiForceCompany/YetiForceCRM#4226]
#### Issue

Item name field, where you lookup products and services is too large for the Quote items table column.
The field overlaps with the unit column, preventing the user from correctly viewing the item they added to the table.
![screenshot-yeti aliartalentos com-2017-03-07-15-45-10](https://cloud.githubusercontent.com/assets/23050598/23664416/68d8ae04-034d-11e7-8989-9076981d1681.png)

It would be great if the field size or table could be adjusted to fit. I know that removing table columns can help with the issue, I'm asking for an alternative approach.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by TomaszQr** [comment]
Try this
![quotes](https://cloud.githubusercontent.com/assets/14273211/23670621/a0e5dcde-0368-11e7-991b-6353d4d7de3e.gif)
