### ISSUE TITLE
Idea - email binding to organisation/contact

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#423]
I have idea about email binding mechanism. 
When you have organisation and contact assigned to it and you or mailscanner bind email under contact that mail correspondence should be visible under organisation details page, email part. Normally a mail exchanging is done with contact not organisation...

Also to preview email from organisation details page a roundcube client should be used not build in mail client...

**Comment by bpabiszczak** [comment]
1. Soon we will add a possibility to view related elements from the main processes level [organization, opportunity, project, ticket etc.] so, for example, when a user will be on a page with an organization, he will be able to view comments bound to tickets, emails bound to contacts or a calendar bound to opportunities. The mechanism that you described is being designed and it will be even more complex than the one you described.

2. I don't understand the last sentence.

**Comment by nikdejan** [comment]
+1 to No. 1 That would be really great and much needed.
