### ISSUE TITLE
[bug] saving a pdf template 

### ISSUE THREAD

**Issue by garikHakopian** [YetiForceCompany/YetiForceCRM#4233]
Hi, I cant seem to get this bug fixed. There are no errors being reported in the console, anyone any ideas?
https://www.youtube.com/watch?v=cVa_hpYeqMU

**Comment by KatarzynaUlichnowska** [comment]
Thank you for using YetiForce. 
We hope that our team has helped you solve the problem. Keep in mind that the support we provide at Github is free, we do not require from you any fees but if you like our work, we kindly ask that you submit a review at one of the following sites:

[Capterra](http://bit.ly/2mCCEmw) (no need to register)
[Softaculous](https://www.softaculous.com/apps/erp/YetiForce) (no need to register)
[Sourceforge](https://sourceforge.net/projects/yetiforce/reviews?source=navbar) (you need an account)

If you want, you can of course add a review on more than one ;)
If you still have a need for more, you can visit our [homepage](https://yetiforce.com/en/) and the [online shop](https://shop.yetiforce.com/en/).
