### ISSUE TITLE
[Question/Enhancement] Mapping 'Employees' to 'Users' or vice-versa, or even mapping 'Assigned To' fields to 'Users' for auto-filling

### ISSUE THREAD

**Issue by rxstriker** [YetiForceCompany/YetiForceCRM#4235]
#### Issue

Title says it all. Is it possible? Is there a currently implemented workaround?
This could be useful in the 'Mileage log book' module for example, I need to add a custom field 'VAT' to the module. It would be great if the auto-filled capability of YetiForce CRM could automatically fill that field with the VAT of the 'Assigned To' user, instead of the user having to fill that field all the time.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by ldgbc** [comment]
Currently no. It not capable of doing that and probably won't be for quite a long time since it probably low priority or require large coding changed.

The workaround is to use Workflow and your Web Browser- autofill

**Comment by rxstriker** [comment]
Ah is that so... well ok, closed. Thank you for clarifying @ldgbc
