### ISSUE TITLE
[Bug] Company details 'Industry' field not saving

### ISSUE THREAD

**Issue by rxstriker** [YetiForceCompany/YetiForceCRM#4236]
#### Issue

After changing and supposedly saving the 'Industry' on 'Company details' to 'Power Industry', it reverts to 'Administration' if I try to edit again.

#### How to trigger the error

1. Create a company
2. Change the field 'Industry' value to 'Power Industry' and save
3. Try to edit again

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
Not able to copy that. Works ok on our installations.

**Comment by rxstriker** [comment]
Maybe I should've shown you the exact problem with a gif from the start:
![yeti_company-details_industry](https://cloud.githubusercontent.com/assets/23050598/23703601/a474b5ce-03f8-11e7-9074-c69782a440be.gif)

**Comment by kpaulaha** [comment]
ok, I see it now. It happens with all, not only power ind.

**Comment by rxstriker** [comment]
Thank you for fixing the issue @migoi
