### ISSUE TITLE
[Question] Adding fields to 'Company details' and changing 'Company details' table headers

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4237]
Adding fields to 'Company details' and changing 'Company details' headers. Is it possible? How?

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
You can do modifying files and database. There was a possibility but during the rebuild it was not added.
