### ISSUE TITLE
Faktury cykliczne [PL]

### ISSUE THREAD

**Issue by galciu** [YetiForceCompany/YetiForceCRM#4238]
#### Issue
Witam,
czy istnieje możliwość ustawienia faktury cyklicznych (abonamentowych, wystawianych raz w miesiącu)?

Pozdrawiam.

#### Your Environment

* YetiForce Version used: 4.0.0

**Comment by bpabiszczak** [comment]
Należy najpierw skonfigurować cykliczne zamówienia, a następnie za pomocą workflow generować automatycznie faktury. Do tego zapewne należy dodać automatyczną wysyłkę PDF i dodatkowo dostęp do faktur z poziomu panelu klienta. W teorii wszystko się da, pytanie co można zrobić prosto z poziomu panelu a co wymaga programowania.
