### ISSUE TITLE
[Enhancement] Discount field (when setting individual in 'Quotes') does not accept commas

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4239]
#### Issue

Discount field (when setting individual in 'Quotes') does not accept commas. It calculates correctly but in the Quote form it show as NaN.

#### Actual Behavior

![yeti_quotes_commas](https://cloud.githubusercontent.com/assets/23050598/23704462/0209fe0c-03fd-11e7-88cf-771a2f61e726.gif)

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
Same with decimal and percent fields #4029
