### ISSUE TITLE
[Question] Is it possible to autofill 'Sales Order' fields when a 'Quote' is selected?

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4240]
Like the title says. Is it possible to autofill 'Sales Order' fields when a 'Quote' is selected? 
If so, how?

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
też 
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/user_privileges/moduleHierarchy.php#L28
