### ISSUE TITLE
[QUESTION] How to get inventory rows using retrieve API ?

### ISSUE THREAD

**Issue by natpicone** [YetiForceCompany/YetiForceCRM#4241]
Retrieve operation in webservice API doesn't return inventory details

example on SQuotes module
curl -sS 'http://yeti.dev:8080/webservice.php?sessionName=768ec74e58c069e12181f&operation=retrieve&id=71x46422' | jq

{
  "success": true,
  "result": {
    "subject": "adhjkadsghasdhj",
    "salesprocessid": "68x46421",
    "squotes_status": "PLL_IN_REALIZATION",
    "accountid": "11x41961",
    "assigned_user_id": "19x47",
    "shownerid": "",
    "response_time": "0.00",
    "createdtime": "2017-03-07 16:24:00",
    "squotes_no": "Q102",
    "modifiedtime": "2017-03-07 16:24:00",
    "closedtime": "",
    "sum_time": "0.00",
    "crmactivity": "",
    "sum_total": "600.00000000",
    "sum_marginp": "0.00",
    "sum_margin": "0.00000000",
    "sum_gross": "0.00000000",
    "sum_discount": "0.00000000",
    "valid_until": "",
    "private": "",
    "id": "71x46422"
  }
}

* YetiForce Version used: ver. 4.0.0
* Browser name and version: Chrome
* Environment name and version: php 5.6.29

**Comment by mariuszkrzaczkowski** [comment]
You are using an old web service protocols that is no longer being developed. try new

https://gitdeveloper.yetiforce.com/api/webservice.php

https://github.com/YetiForceCompany/YetiForceCRM/issues/4023
