### ISSUE TITLE
[Question] Best Server Settings

### ISSUE THREAD

**Issue by esaw01** [YetiForceCompany/YetiForceCRM#4242]
@bpabiszczak 

Please could you (creators of YetiForce) let us know the best server settings, Linux OS, nginx/ Apache etc. etc. for YF?

I've tried with my shared hosting and 3.4 works but 4.0 won't work, I've tried PHP 5/7/7.1 and many other settings. I also can't upgrade 3.4-4.0.

Please could you list the best server OS and software that runs YF 4.0?

Thank you! :)

**Comment by ldgbc** [comment]
Please see #4058 
There is also the "web server requirement" link you can find somewhere in other issue.

I'm in the same position as you are. And all I can tell you is, you a stuck with 3.4 until you upgrade your server.

**Comment by epsilonsc** [comment]
Hi you can use this article
https://www.rosehosting.com/blog/install-yetiforce-crm-on-ubuntu-16-04/

**Comment by easaw** [comment]
I can confirm that this PHP 7 INI file works.

**HOWEVER**
I used MAMP, so some sections will read 
`error_log = "MAMP_php_error_log_MAMP"`
or
`extension_dir = "MAMP_extension_dir_MAMP"`
for example

**You will need to adjust this if you aren't using MAMP**

I will attempt to configure it for my Ubuntu server and re-upload when it's working.

[phpini_7.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/836233/phpini_7.txt)
