### ISSUE TITLE
Roundcube  - Responses template only in text - not html

### ISSUE THREAD

**Issue by klw-sc** [YetiForceCompany/YetiForceCRM#4247]
#### Issue
Want to be able to have email templates that support HTML. If I understand correctly, email templates are now managed inside the email client, not a function of YetiForce. Inside Roundcube there is a function called 'Responses'. Inside Responses I can create canned email responses.
However, these are only in text format, I cannot find any setting to allow for inclusion of html, url links etc. I am looking for a function similar to VTiger called 'Email Templates'. Other than Responses inside Roundcube with this text limitation, I cannot find any equivalent methods.

Is there a way to setup html Email Templates in YetiForce?

#### Actual Behavior
In Roundcube - open the settings 
Go to Responses - then create new label and some text
If you embed html it is sent as text. 
No mechanism to create html email Responses

#### Expected Behavior
Ability to create rich canned email responses, with images, hyperlinks etc, formatting capabilities

#### How to trigger the error

1. Inside Yeti open email
2. Create new email
3. Select the Compose new email
4. Responses tab is visible (provided you have activated it inside the Roundcube config settings)
5. Email is sent with the Reponse - but limited to text format only

#### Your Environment

* YetiForce Version used:  4.0
* Browser name and version: Doesn't matter - Chrome, ie, Firefox
* Environment name and version:
* Operating System and version: Unix

**Comment by migoi** [comment]
there are databases -> email templates

Those are also just text?

**Comment by klw-sc** [comment]
If I open a contact and then select the option to send them an email using 'send notification' there are no options I can find to use a stored email template. For my business we currently have a number of standard email templates we use to reply to customers during various parts of the sales cycle. 

For the email templates in the database I cannot access these for contacts, Quotes or Invoices?

Similarly, if I open a Quote or Invoice and want to email it to a client, with a standard email template, I cannot work out how to do that using the 'send notification' . Only option is to type a reply every time and not use a stored template.

If I then open a Quote then select 'Export to PDF' I get a new dialog box. From here I have the drop down option under 'Generate' to select 'Send via email'.

This last option opens opens Roundcube and the Quote in this e.g. is attached ready to send. I now only have access the the 'Responses' templates which as I mentioned above are in text, not html.

So I am unsure how I can send html type email templates for Contacts, Quotes, Invoices etc from inside YetiForce. Is this possible?

Any help much appreciated.

**Comment by mariuszkrzaczkowski** [comment]
look at this
![1](https://cloud.githubusercontent.com/assets/10198654/23787391/14131ae0-0572-11e7-8884-c4f93c7d806a.png)
![2](https://cloud.githubusercontent.com/assets/10198654/23787394/17559ab6-0572-11e7-8c1f-24b418a85652.png)

**Comment by liberox** [comment]
Hi Mariusz,

Can you help me to find out why templates menu is not active in my system?
![email-templates-screenshot_1](https://cloud.githubusercontent.com/assets/21132169/25621678/54c86f9a-2f52-11e7-8d27-c228b46985cd.jpg)

**Comment by liberox** [comment]
Hi again,

I found out that I have to first create a template. And only these created templates are selectable in the compose window. How do I make other templates that are already in the system selectable?

**Comment by MotazHakim** [comment]
> ![email-templates-screenshot_1](https://cloud.githubusercontent.com/assets/21132169/25621678/54c86f9a-2f52-11e7-8d27-c228b46985cd.jpg)

Hi,
can i ask what skin is that?
