### ISSUE TITLE
How can I to translate for the pt_BR. I would like know the step-for-step.

### ISSUE THREAD

**Issue by genesis-wp** [YetiForceCompany/YetiForceCRM#4248]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by migoi** [comment]
click System settings > System tools -> language management

click add new language
fill in the language details

next click on tab "Edit language"

Now in the "Language" Field select at least two language e.g. en_us and pt_br. Those language content is compared to each other. Fill in your translation for each module you select.

OK?
