### ISSUE TITLE
[bad interface] edit contact

### ISSUE THREAD

**Issue by SergeyDjam** [YetiForceCompany/YetiForceCRM#425]
![screen_106](https://cloud.githubusercontent.com/assets/11427162/6826470/bc751f2e-d312-11e4-8f16-4de8db296fb0.png)

https://test.yetiforce.com/index.php?module=Contacts&view=Edit&record=109

**Comment by waw555** [comment]
Will be fixed in the near future

**Comment by SergeyDjam** [comment]
ok
