### ISSUE TITLE
Can't Login YTF v4 on shared host

### ISSUE THREAD

**Issue by aramxalil** [YetiForceCompany/YetiForceCRM#4255]
Hello Dears 
Please review this problem 
1- I installed yeti force version 4 on my shared host wich is (siteground)
2- everything goes fine untill the user page loads  but i cant login 
3- i although checked the yeti force db > v tiger_users > the admin user is created 
but can't login  

* YetiForce Version used: 4
* Browser name and version: chrome : 56.0.2924.87 (64-bit)
* Environment name and version: 
* Operating System and version:

**Comment by ezbank** [comment]
Add extension: nd_pdo_mysqlnd

**Comment by aramxalil** [comment]
@ezbank  I don't it available on shared host services
:(

**Comment by aramxalil** [comment]
I talked to my hosting support team they said "We have the extension pdo_mysql available on our servers by default"  :(

**Comment by bpabiszczak** [comment]
You cant set nd_pdo_mysql and pdo_mysql at the same time. Try disabled pdo_mysql.

**Comment by aramxalil** [comment]
I added extension
1-pdo.so
2-pdo_sqlite.so
3-pdo_mysql.so

**Comment by mariuszkrzaczkowski** [comment]
nd_pdo_mysql???
