### ISSUE TITLE
creating new db problem v4

### ISSUE THREAD

**Issue by aramxalil** [YetiForceCompany/YetiForceCRM#4256]
Dear support team
I get below error when try to create new db 
![dw](https://cloud.githubusercontent.com/assets/24459816/23812847/3bdf2674-05ed-11e7-9f0a-6fb0204ca015.png)
![341](https://cloud.githubusercontent.com/assets/24459816/23812857/4290b294-05ed-11e7-83b9-b6cedec09394.png)

thanks for answer

**Comment by migoi** [comment]
error is the almost empty page?

what is in the logs?

**Comment by aramxalil** [comment]
I didn't check logs @migoi 
but it freezes in this page

**Comment by migoi** [comment]
for me the install process needs some time - its not "instant ready"

Without some error message its too hard to diagnostic what might happened here

**Comment by mariuszkrzaczkowski** [comment]
Start with
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
and 
https://yetiforce.com/en/developer-documentation/engine/115-debugging.html
