### ISSUE TITLE
Asterisk modules/PBXManager/ Yetiforce 4.0 PHP Notice

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#4257]
#### Issue
PHP Notice:  Undefined variable: recordIds in /var/www/crm/modules/PBXManager/models/Record.php on line 52
PHP Notice:  Undefined variable: calls in /var/www/crm/modules/PBXManager/actions/IncomingCallPoll.php on line 101

#### How to trigger the error

1. Ustawić adres ip asteriska w Konfiguracja systemu > Integracja > PBXManager >
2.
3.

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: Mozilla Firefox
* Environment name and version:
* Operating System and version: Linux Ubuntu 16.04 LTS Php7.0-fpm mariadb

**Comment by migoi** [comment]
thx, but both are already fixed in latest developer code.

**Comment by epsilonsc** [comment]
@migoi Thx, for that now i find this solutions.
We have lots of logs.
https://github.com/YetiForceCompany/YetiForceCRM/commit/7173cda18e5f0fa43150b90cfe7dc84b164dfec0
