### ISSUE TITLE
[idea] view tree accounts, groups accounts

### ISSUE THREAD

**Issue by SergeyDjam** [YetiForceCompany/YetiForceCRM#426]
Consider the idea of a tree accounts, as well as the idea of grouping accounts

**Comment by bpabiszczak** [comment]
Use "Member of" in accounts [organizations] module. 
![image](https://cloud.githubusercontent.com/assets/10197525/6835769/308a4414-d33d-11e4-8801-e6e1c3071dbf.png)

**Comment by SergeyDjam** [comment]
No. View tree

**Comment by bpabiszczak** [comment]
Use organization hierarchy

**Comment by SergeyDjam** [comment]
No, it's not about this... 
The point is not a simple group of clients and a visual representation in the form of a tree

**Comment by SergeyDjam** [comment]
e.g.

root dir (My Organization 1)
 - dir "My favorite firms"
   -- firm 1
   -- firm 2
 -  dir "Potential"
   -- potential firm 1
   -- potential firm 2
...
root dir (My Organization 2)
 - dir "Potential clients"
    -- good account 1
    -- best account
...
  ...

**Comment by bpabiszczak** [comment]
If it's not a hierarchy (embedded into the system) that you are talking about, than please send a detailed business description and explain how it should work step-by-step. At the moment I don't understand your idea from a business and logics perspective.

**Comment by SergeyDjam** [comment]
1. View tree in left panel
2. hierarchy whith multilevel

**Comment by bpabiszczak** [comment]
You still haven’t described the business logic.

Currently, the system allows to create a hierarchy as well as view it as a tree. The only thing that I understood from your last post is that you would like to see a tree view in the list of organizations/accounts. If that’s what you meant, then it’s possible that we will add it in the future, but at the moment is a low priority request. However, if you meant something different, then please describe it in details.

**Comment by SergeyDjam** [comment]
Do not understand it correctly.
There is no hierarchy of needs rather grouping

**Comment by SergeyDjam** [comment]
hierarchy
Company 1 
<ul> Subocmpany 
      <ul> Subsubcompany</ul>
</ul></ul>

Rather grouping
<ul> My group company 1
       <ul> My sugroup 1 
              <ul> My subsubgroups 2 </ul>
       </ul>
</ul>

**Comment by bpabiszczak** [comment]
This is an artificial tree and we don't like the artificiality:

1. If you would like to mark customers as favoirite, use tags or a field to do it.

2. If you would like to mark customers as partners, use a field to do it.

3. If you would like to mark customers as potentials, use a field to do it.

If you would like to search for a favourite partner, use filters on the list.

**Comment by SergeyDjam** [comment]
All this is not about
