### ISSUE TITLE
YF4.0.0 [bug] custom fields, search

### ISSUE THREAD

**Issue by ABaumruck** [YetiForceCompany/YetiForceCRM#4265]
#### Issue
After creating a custom field "Branche" within the organisation module (table vtiger_accountcf) I've enabled the search function. After that I received an SQL error when I tried to access the organisation

#### Actual Behavior
Organisation data is not accessible when search is enabled for a custom field -> SQL error is created
When the search for the custom field is removed the error disappears

#### Expected Behavior
Search for custom field data should be possible no error should be dropped

#### How to trigger the error
![custom field search bug](https://cloud.githubusercontent.com/assets/22656356/23832770/35b6a9d4-073c-11e7-8ed8-67fcd6669361.gif)

#### One thing to mention
As I was unable to update from YF 3.4.21 to YF 4.0.0 I decided to go for a clean install into the same directory. The CRON job remained the same (but it looks as it is working)

#### Your Environment
YetiForce Version used: 4.0.0 -> clean install
Browser name and version: Chrom V 53.0.2785.143
Environment name and version: vServer
Operating System and version: Ubuntu 16.04.1 LTS / PHP 5.6.29

**Comment by ABaumruck** [comment]
Is there no one who has an idea about that?

The custom field behaviour is total strange for me
When I try to add a custom field to "vtiger_account" table it always says I am using bad characters and it won't let me create a field
I'm able to create a field within the "vtiger_accountcf" table but it crashes when I turn on the search for this specific field

BR Andreas

**Comment by mlorencik** [comment]
Pull new versions, problem solved in da219a3
