### ISSUE TITLE
Cannot delete Webservice App keys

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4266]
Hi,

I was playing with the WebserviceApp and created a couple of test keys to see what it did. However I cannot delete them from within yetiforce. I click on the delete icon and select delete then it closes but the record is still there. 

Where are these records stored in the datasbase? As I was thinking I could delete the records from there. I have looked at the WSApp fields but there doesn't appear to be anything related there.

Kind regards

**Comment by PercyP** [comment]
Ah,

found where they are stored:

yf_servers

Now deleted

**Comment by migoi** [comment]
cannot confirm with latest developer: app and user could be deleted via webui
