### ISSUE TITLE
[question] how to set field order for global search

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#4268]
Hi,
for the contact module I added the global search to include the [contact_no] field and would like to have the following order
 - contact_no
 - firstname
 - lastname
 - primary email

but the [firstname] field is always positioned before the [contact_no] field.

Is there a possibility to define the display order.

![searchorder](https://cloud.githubusercontent.com/assets/10443220/23837015/bc6ffa58-0781-11e7-85be-cb474dbde91d.gif)

Your Environment

YetiForce Version used: 4.0.0 -> clean install
Browser name and version: Chrom V 53.0.2785.143
Environment name and version: vServer
Operating System and version: Ubuntu 16.04.1 LTS / PHP 5.6.29

**Comment by mariuszkrzaczkowski** [comment]
Test the latest developer release

**Comment by setras** [comment]
same problem
