### ISSUE TITLE
YetiForce needs your help

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#4269]
Hello guys.

We have a favor to ask you. It won't cost you any money, and you don't need any tech knowledge to help us out. All it requires is a couple of minutes of your time. Sounds good?

We just registered YetiForce at Capterra and we're looking for reviews. Capterra is an extremely useful website for finding business software. We believe that YetiForce is an amazing alternative to commercial CRMs, and we want more people to learn about our software, our team, and our values. The bigger our community grows the faster and more efficient the development of YetiForce gets.

No registration is required to post your review of YetiForce, the only requirement is the language of the reviews – all of them must be in English, otherwise they will be removed.

If you decide to help us please visit [YetiForce's profile](http://www.capterra.com/customer-relationship-management-software/reviews/159123/Yetiforce%20/YetiForce/new?utm_source=vp&utm_medium=none&utm_campaign=vendor_request) and fill in all the required fields.

We appreciate your time and support!
Thanks!

**Comment by esaw01** [comment]
will do once we've been using it for a few months, just installing during March :)

**Comment by PercyP** [comment]
@paula-w 

I added my review last week - the least we can do!

**Comment by slawekkow** [comment]
I added a brief, but of course favorable review

**Comment by aramxalil** [comment]
I Just gives a 5 star and some cool text @paula-w please Answer my email that i sent  to shop@yetiforce.com  ...

**Comment by bpabiszczak** [comment]
Thank you for the references, we have them already 11.
