### ISSUE TITLE
[idea] give up directory of suppliers

### ISSUE THREAD

**Issue by SergeyDjam** [YetiForceCompany/YetiForceCRM#427]
There is an idea to give up a single directory of suppliers. It is better to have the status of the counterparty or type of customer, supplier, partner, etc.

**Comment by bpabiszczak** [comment]
Currently, we are dividing the functionalities, not joining them. Suppliers/Vendors will be a separate module, as well as Partners and Accounts/Organizations will be separate. We don't have any plans that would involve joining these modules.

**Comment by SergeyDjam** [comment]
This is a very bad idea

**Comment by SergeyDjam** [comment]
Partners, Supplies, Vendors, etc. are all counterparties. Why duplicate and multiply entities?

**Comment by bpabiszczak** [comment]
It’s a bad idea for one person, but it is great for someone else. Everyone can criticize so I suggest you to use specific arguments.

All large and powerful systems that I know [SAP, Symfonia] separate organizations/accounts from suppliers/vendors. We won’t change our point of view if you don’t explain us the advantages of this solution and tell us why they overbalance the disadvantages.

**Comment by SergeyDjam** [comment]
I do not know with SAP but I know with 1C
