### ISSUE TITLE
Outlook Integration - Corrensa (vTiger)

### ISSUE THREAD

**Issue by esaw01** [YetiForceCompany/YetiForceCRM#4270]
Hello,

I would be very grateful for any help on this issue.

Corrensa (www.corrensa.com) - the Outlook/ Gmail plugin for vTiger is freely available and works great with vTiger 6.5 (though not vTiger 7).

The plugin **does** install in YetiForce, however it has some issues actually displaying the plugin settings.

I get this error in the console:

```
Uncaught TypeError: $(...).modal is not a function

at Settings.js:207
at Settings.js:721
```

It references line **207** in **layouts/basic/modules/Corrensa/resources/js/Settings.js**

Which seems to be a jQuery issue?
Anyone know how I can solve it?

**Comment by waran70** [comment]
Would be cool if you start understanding that YF is NOT vt


Kisses
---------

**Comment by esaw01** [comment]
It's based on it (specifically 6.5) I understand. So,  is it so far different that a VT plugin couldn't be adapted?

Of course I'm no php or JS coder, but the file structures seem similar, though i notice some things are quite different. 

I'm just asking if it is possible? 

If no, please explain further? E.g. Nusoap has now gone etc. etc.

**Comment by esaw01** [comment]
Plus i wouldn't need ongoing development. Just a one off to work with YF as it is now, updates are unlikely if plugins would die as a result.

How hard is LDAP to get working, what does it offer?
Anyone?
Bueller?

I basically need complete synchronisation with Outlook. That's literally my only criteria and I'd be using YetiForce tomorrow! 

Just wondering why it's not a feature or even a planned feature? :/

**Comment by migoi** [comment]
looks like something like the Portal is displayed inside Gmail or Outlook ... and that would be a much better approach.

**Comment by esaw01** [comment]
Okay, close this please
