### ISSUE TITLE
[Bug] I've disabled storage in Goods Received/Dispatched/Issued note, now I can't reactivate

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4271]
#### Issue

Initially I disabled the storage module, because in my company we only deal with a central storage, until I realized that all products transactions need the Storage module.
Before re-enabling the Storage module, I added a custom field to the Goods Received Note that was related to the Goods Issued Note module. This because we wanted to relate a note that had the products that we received from our suppliers/vendors (Received note) to the products note we actually ordered from our suppliers/vendors (Issued Note). The related module appeared in the "Module - Relations" configuration and also in the tab of a selected Receive Note, all was well (except for auto-fill when I selected an Issued Note, view #4240 for similar question).
However when I tried to re-enable the Storage field in the Goods Received/Dispatched/Issued Notes modules, the field appeared in the layout editor but it could not be activated thus note appeared on record creation across the various Notes modules.
Any idea has to what the problem is?

#### Actual Behavior
![yeti_goods_fields](https://cloud.githubusercontent.com/assets/23050598/23855937/896fb95e-07ef-11e7-91f5-5711bd435acd.gif)

#### How to trigger the error

1. It's described in Issue section above.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Check logs
