### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4272]
#### Issue
White screen or error 500 on the install page

#### Actual Behavior
No install page for yetiforce

#### Expected Behavior
Get the install screen

#### How to trigger the error
1. goto live.projectstart.co.uk
2. Blank screen

#### Your Environment
Ubuntu 16.04 php 7.0 with all modules. (currently running three other yetiforce install's one production and two development. (all installed correctly and working)

There is no error output in my error logs.

**Comment by migoi** [comment]
this will be impossible to fix.

Unless you can identify what the 500 error (internal server error) causes it could be one of millions of reasons.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/administrator-documentation/errors/227-apache-500-internal-server-error-2.html
