### ISSUE TITLE
Adding a menu crashes frontend

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#4275]
#### Issue

Adding a menu in the admin (contacts to root with different name) gives a blank frontend and an admin where the menu's show but don't work.

#### Actual Behavior
crashed frontend and not working backend

#### Expected Behavior
Adding a menu to the frontend root menu as admin.

#### How to trigger the error

1. admin -> standard modules -> menu configuration
2. add menu -> module version -> next -> contact and fill in the fields. finish and try to return to front end. 
3.Blank internal error screen on front, not working menu in admin.

Can't find details in the error logs, not in Yeti not in Server logs. But replacing the 'user_privilage' folder with a fresh one seems to repair the issue. (New menu item not working but at least access again to frontend.)

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: chrome OSX (latest)
* Environment name and version: PHP 7.0  MYSQL 
* Operating System and version: OSX latest

Tested with PHP 7.0 and 5.6 and same behaviour. Could replicate this everytime but not on the demo site.

**Comment by zebrahosting** [comment]
I have been checking a bit more: The problem seems in the menu_0.php file.
When I create an additional menu, there is a table change and to my surprise also a change in this menu_0.php file. But after the change it does not work. Replacing the menu_0 with the original one solves the access issue but does not bring back a working menu. 
In the overview there is the new menu name and can be removed, hence it functions properly in the DB but something goes wrong in writing the file. I can see the menu added but probably a small bug in there? When I remove the filter and leave the rest of the menu changes things start to work again.
Attached the file with a 'New Menu" added and the filter set to ALL.

**Comment by PercyP** [comment]
@zebrahosting 

I had this same issue and the attached shows the solution:

https://github.com/YetiForceCompany/YetiForceCRM/issues/4039
