### ISSUE TITLE
4.0 Missing Generate Customer Login Details workflow

### ISSUE THREAD

**Issue by locutus2999** [YetiForceCompany/YetiForceCRM#4276]
#### Issue
In the customer portal installation instructions, it states:

Generate Customer Login Details - this workflow generates a password to the Customer Portal. This password is in the first step [before it is sent to a customer] in plain text [unencrypted]. 

#### Actual Behavior
This workflow is not available in 4.0

#### Expected Behavior
This workflow should be available under workflows

#### How to trigger the error
1 Select Automation.
2. Select Workflows.
3. Selects "Contacts"

#### Your Environment
* YetiForce Version used: 4.0
* Browser name and version: Chrome
* Environment name and version: 
* Operating System and version: AWS EB, PHP7

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3998
https://github.com/YetiForceCompany/YetiForceCRM/issues/3913
