### ISSUE TITLE
[idea] Auto-filter contact list when creating a new contractor

### ISSUE THREAD

**Issue by SergeyDjam** [YetiForceCompany/YetiForceCRM#428]
Auto-filter contact list when creating a new contractor

**Comment by bpabiszczak** [comment]
contractor?

**Comment by SergeyDjam** [comment]
Account, client

**Comment by bpabiszczak** [comment]
Describe step by step, because I do not understand your ideas.

**Comment by SergeyDjam** [comment]
1. create new account
2. autocreate filter contacts by this account

**Comment by bpabiszczak** [comment]
I don't think it's a good idea. There is no need to create automatic filters in the described example because the same result can be achieved by typing company name into a column or in the main search. It wouldn't make sense for someone with 100.000 customers to create so many filters [even with 200 hundred companies it doesn't make sense].

**Comment by SergeyDjam** [comment]
Every time typing company name into a column or in the search?

**Comment by bpabiszczak** [comment]
I don’t understand your question. If you search contacts then you usually search by names, emails or other parameters, but not company names. If you don’t know who you search for and you search by a company name of all contacts [what shouldn’t happen too often], then you have the following tools:

1. the main search [narrowed down to contacts, you enter a company name – it’s good to add a possibility to search by company name  in contacts in search configuration].
2. List of contacts – search by columns – enter a company name and you will see contacts from this company.
3. Enter a company and you will see all related contacts there
I don’t understand why these tools are insufficient if they are quicker than narrowing down the filters from hundreds of automatically created ones.

**Comment by SergeyDjam** [comment]
Let's look at the business model. I need to say to work with one company and only customer of this company. Or do I need to do email newsletter for contacts companies. In this case, when you click on the menu items lost my selection. So, in each case I need to enter your company again in the search? This is extremely convenient. Or do I need to create a filter that too

**Comment by bpabiszczak** [comment]
Unfortunately, I don't understand. Please describe it one more time.
