### ISSUE TITLE
[PL] Szybkie tworzenie brak kontaku 

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#4280]
Na liście szybkiego tworzenia rekordów brak możliwości dodania kontaktu.
![szybkie tworzenie brak kontaktu](https://cloud.githubusercontent.com/assets/10506580/23973473/a0d5316c-09d6-11e7-90ee-0bd62da4cc41.PNG)

Testowane 
https://gitstable.yetiforce.com/

#### Your Environment

* YetiForce Version used: 4.0

**Comment by mariuszkrzaczkowski** [comment]
Bo ktoś ustawił moduł kontaktów jako zaawansowany a takie moduły nie są widoczne na liście szybkiego tworzenia.
