### ISSUE TITLE
[Enhancement] UTF-8 characters support in CSV export of lists

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4283]
#### Issue

I recently exported my products in csv format, and all UTF-8 characters like "ç" were not correctly displayed. Is it possible to correctly format the output csv?

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
I tested and characters is correct
[Kontrahenci.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/862973/Kontrahenci.zip)
