### ISSUE TITLE
Sending email via contact button does not close window after sending

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#4284]
It seems to work fine in Roundcube to send an email but when I use the email button inside a contacts page , I can send the email (and is send) but the autoclose does not work and there is no way to kill it other then retyping the home URL.

Console error:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. 
Scripts may close only the windows that were opened by it.
(anonymous) @ app.min.js?s=1489497222:206

**Comment by mariuszkrzaczkowski** [comment]
What version of the system? Have you tested the developer version?
