### ISSUE TITLE
[QUESTION] How to integrate between Yetiforce and Asterisk or Elastix?

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4286]
Hi. Im very like Yetiforce CRM. And i have a question.
How to integrate between Yetiforce v4 and Asterisk or elastix?
as the introduction, module PBXManager in vtiger could intergrate with asterisk. so in  yetiforce, does it work in that way?
or if it doesn't work like that with yetiforce. How much that user might pay for it, if it's possible?

**Comment by epsilonsc** [comment]
We can get some money for this function's.
In version 4.0 function click to call is disable.

**Comment by migoi** [comment]
for outbound calls, at least one template must be changed to have a clickable phone number.
Inbound call notification should work out of the box - most effort is to have your pbx listen / send the phonenumber.

**Comment by migoi** [comment]
@bpabiszczak Do you want the .tpl change as PR or has it been intentionally removed?

**Comment by epsilonsc** [comment]
@migoi Hi can you public modification's.

**Comment by mariuszkrzaczkowski** [comment]
We have added new call handling functionality.

https://github.com/YetiForceCompany/YetiForceCRM/commit/60ab5caa42c853eaf340fb7857438f9a7a87653b

https://gitdeveloper.yetiforce.com/index.php?module=PBX&parent=Settings&view=List&block=5&fieldid=15

Asterisk is not available but we are waiting for the customer who will order it.

**Comment by mariuszkrzaczkowski** [comment]
Here is a sample file for another PBX integration
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/Integrations/Pbx/Mixpbx.php

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/vendor/yetiforce/Integrations/Pbx

**Comment by MicroSolve** [comment]
Good Day for all 

if there is any DOC help to integration with asterisk or freepbx 

thanks !!
