### ISSUE TITLE
The  Opportunities is not displayed in the Accounts.

### ISSUE THREAD

**Issue by Zzik** [YetiForceCompany/YetiForceCRM#4287]
The  Opportunities is not displayed in the Accounts. In the category of the Opportunities, it exists, and disappears from the Accounts. 

PS: Sorry for my BAD English
<a target="_blank" href="http://radikal.ru/big/retaqefwpmgji"><img src="http://s12.radikal.ru/i185/1703/d2/c2a40c3fe9eet.jpg" /></a>

**Comment by mariuszkrzaczkowski** [comment]
What version do you have?
I tested on the latest version of the development and there is no error
