### ISSUE TITLE
[QUESTION] PDF special_functions in Yeti 4.0, how to extend ?

### ISSUE THREAD

**Issue by natpicone** [YetiForceCompany/YetiForceCRM#4288]
Which is the best way to add special pdf functions in Yeti 4.0 ?
I'm referring to the old pdf special_functions which now they have been moved to TextParser.

**Comment by mariuszkrzaczkowski** [comment]
Just as before we create a new file here you have an example
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/vendor/yetiforce/TextParser
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/TextParser/ProductsTable.php#L17

**Comment by natpicone** [comment]
Thanks Mariusz I already found this.
I was asking for the best way to add new textparser to the codebase.
Should I put my file inside the vendor/yetiforce/TextParser or you have a better location/way (ex: via composer) to do this ?

**Comment by mariuszkrzaczkowski** [comment]
You have two options:
- if the function is to be globally available then add here: vendor/yetiforce/TextParser
- if the function is only for one module, modules/module_name/textparsers eg. https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/modules/IStorages/textparsers
