### ISSUE TITLE
Cannot open related tab of modules with fields created in "additional tables"

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4289]
#### Issue

I created a field related to the "Accounts" module in the "Quotes" module with the additional table instead of basic.
All was fine, "Quotes" opened normally. But when I went to a created account and clicked on the "Quotes" tab, Yeti entered a "Loading" loop. And the console showed an SQL error, see screenshots below.

![capture](https://cloud.githubusercontent.com/assets/23050598/24051115/f6cb364a-0b28-11e7-891f-121112804a11.PNG)

![screenshot-yeti aliartalentos com-2017-03-17-15-40-43](https://cloud.githubusercontent.com/assets/23050598/24051120/fb4956fc-0b28-11e7-91bd-6387be2325f4.png)

![screenshot-vs14 rede1024 com-2083-2017-03-17-15-39-09](https://cloud.githubusercontent.com/assets/23050598/24051123/fde2ccfe-0b28-11e7-8638-9b952044c474.png)

Here is the system.log:
[system.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/851490/system.txt)

#### Your Environment

* YetiForce Version used: 4.0.103
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
The Accounts module does not have defaults associated with Quotes. You need details about this relationship.

**Comment by ruistrecht-alt** [comment]
Yes, I know that it is not related by default. In the company I work in, we have a particular way of doing things and we wanted to use the workflow that is implemented by default in YetiForce, particularly the "Quotes" and "Sales Order" module, in a custom way by adding some custom fields that added extra relations.
Do note that does not happen with only the "Quotes" module, any module that I relate to another with a custom related 1:M field that uses the "additional table" (u_yf_modulecf) will output this error.
That being said, if do this by using the "basic table" (u_yf_module), this will not occur.

![yeti_cf_rel](https://cloud.githubusercontent.com/assets/23050598/24094950/dbef34f8-0d52-11e7-8b7d-382752c28f5d.gif)

**Comment by infoTopcloudxl** [comment]
Hi I exerience the same isseu with Goods received notes in the Sales order, since we updated to 4.0 we have this problem, how can we solve this?

**Comment by ruistrecht-alt** [comment]
You have to update your YetiForce CRM to the latest develop version, if possible.
Or wait until an official update is released.

**Comment by RustemHesenov** [comment]
Is there any progress on the subject?
