### ISSUE TITLE
Quotes duplicating on status change

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4290]
#### Issue

![yeti_quote_status](https://cloud.githubusercontent.com/assets/23050598/24052610/fee03f1a-0b2d-11e7-9e2d-0fcb26aad749.gif)

Like the title says and is shown in the gif above. However, issue does not occur if you:

- Before changing the status you open the quote record list, open the quote and change the status
- Change the status through the record list directly

#### Your Environment

* YetiForce Version used: 4.0.114
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/2770092d9683ea4ad139212bdb463f5a36274306
