### ISSUE TITLE
USD Currency Format wrong

### ISSUE THREAD

**Issue by locutus2999** [YetiForceCompany/YetiForceCRM#4291]
#### Issue
v4.0 displays USD as 999,00 $

#### Expected Behavior
This should be displayed as $999.00 or just $999

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
It can be changed in user details.

![accounts - detail](https://cloud.githubusercontent.com/assets/10330264/24070393/370e3238-0bc5-11e7-8bd6-90cc2f6d2019.png)
