### ISSUE TITLE
[PL]Raport sprzedaży produktów

### ISSUE THREAD

**Issue by nnewrulez** [YetiForceCompany/YetiForceCRM#4293]
Witam,
Próbuje od dłuższego czasu stworzyć raport sprzedaży produktów lecz z poziomu raportów po połączeniu z fakturami nie widzę możliwości wybrania pól z bloku zaawansowanego. Jak mogę to osiągnąć?

**Comment by mariuszkrzaczkowski** [comment]
Na chwilę obecną nie ma takiej możliwości, moduł raportów wymaga przebudowy bo nie obsługuje bloku zaawansowanego.
