### ISSUE TITLE
Module does not contain default language (en_us)

### ISSUE THREAD

**Issue by Diverse500** [YetiForceCompany/YetiForceCRM#4296]
#### Actual Behavior
Module does not contain default language (en_us)

#### Expected Behavior:
Upload modules and function in order to configure parameters.

#### Your Environment

* YetiForce Version used: 4, Fresh Install.
* Browser name and version: All
* Environment name and version: Centos 7 cPanel
* Operating System and version: Centos 7 cPanel
Thanks

**Comment by mariuszkrzaczkowski** [comment]
What is the structure of your package looking from a ZIP file?

**Comment by Diverse500** [comment]
Hello, 
I got the ZIP files from where It  pointed to:
https://github.com/YetiForceCompany/lib_mPDF
https://github.com/YetiForceCompany/lib_roundcube
https://github.com/YetiForceCompany/lib_PHPExcel
https://github.com/YetiForceCompany/lib_AJAXChat
https://github.com/YetiForceCompany/lib_gantt
Do you provide a service to get us up and running so we can get to work?
Thanks, Bob

**Comment by Diverse500** [comment]
Hello,

I got the ZIP files from where It pointed to:
https://github.com/YetiForceCompany/lib_mPDF
https://github.com/YetiForceCompany/lib_roundcube
https://github.com/YetiForceCompany/lib_PHPExcel
https://github.com/YetiForceCompany/lib_AJAXChat
https://github.com/YetiForceCompany/lib_gantt

Do you provide a service to get us up and running so we can get to work?
Thanks, Bob

Mar 19, 2017 06:43:30 AM, reply@reply.github.com wrote:

===========================================


What is the structure of your package looking from a ZIP file?

**Comment by mariuszkrzaczkowski** [comment]
It does not update the file, only from the panel
https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List

**Comment by Diverse500** [comment]
Hello,
Yes...I could have told you that. Whats the fix ???

Do you provide a service to get us going?



Mar 20, 2017 11:05:27 AM, reply@reply.github.com wrote:

===========================================


It does not update the file, only from the panel

https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List
