### ISSUE TITLE
Digital signature field - is this possible?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4297]
I need a digital signature box for my crm and found a vtiger developer who has created exactly the sort of thing I am after (only problem is it is specifically designed for vtiger). I was wondering if something similar could be created for Yetiforce?

Here are the details of what they have created:

https://vtigress.wordpress.com/2016/08/10/digital-signature-for-vtiger-crm/

If this is a possibility, how much would it cost to have it implemented? Also, is anyone else interested in such a feature?

I saw a similar post on here: https://github.com/YetiForceCompany/YetiForceCRM/issues/2420

**Comment by PercyP** [comment]
Update for anyone interested:

I have just spoken with the vtiger developer and they think they can probably do this.

**Comment by waran70** [comment]
What is the point of mentioning it here?

**Comment by PercyP** [comment]
@waran70 

Because others have inquired about digital signatures for yetiforce, and at the time the developers said they had no plans to introduce it - unless a customer asked for it. I contacted the 3rd party developer to see if their solution could be adapted to work in yetiforce, and they believe it can. 

So, I mentioned it hear firstly to see if yetiforce themselves could do it, secondly because others might also want this feature and thirdly, there is an option of having it built.

**Comment by epsilonsc** [comment]
Hi @PercyP you can add signature in My mailbox module 
https://gitstable.yetiforce.com/index.php?module=OSSMail&view=index&mid=113&parent=44
![screen2](https://cloud.githubusercontent.com/assets/10506580/24086019/8846bccc-0d07-11e7-9545-1d5354194ef9.PNG)
![screen](https://cloud.githubusercontent.com/assets/10506580/24086021/8a8ec5e2-0d07-11e7-811b-98445acef3ab.PNG)

**Comment by PercyP** [comment]
Hi @epsilonsc 

thanks for that - Unfortunately it wouldn't meet my needs. It does have other uses though so thanks for highlighting it.
