### ISSUE TITLE
Constant login page

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4298]
#### Issue
Everytime I try to login i get it redirecting back to the login page. No matter which user I use.

#### Actual Behavior
Constant login page even with admin users

#### Expected Behavior
Login to dashboard

#### How to trigger the error
![userissue](https://cloud.githubusercontent.com/assets/22075161/24083773/8a7c4944-0cd5-11e7-8f47-d565d832d966.gif)

#### Your Environment
yetiforce 3.4.2
ubuntu 16.06
running apache and all modules requested by yetiforce.

**Comment by alextovey** [comment]
@mariuszkrzaczkowski @paula-w any ideas please? production has stopped because of this error. no error logs in apache about this error or php error log and the cron is showing normal activity. :( i'm baffled. I've restarted apache and it is working i've rebooted the machine.

**Comment by mariuszkrzaczkowski** [comment]
look at this:
https://github.com/YetiForceCompany/YetiForceCRM/issues/4136
https://github.com/YetiForceCompany/YetiForceCRM/issues/4255
https://github.com/YetiForceCompany/YetiForceCRM/issues/4007
https://github.com/YetiForceCompany/YetiForceCRM/issues/4028

**Comment by alextovey** [comment]
@mariuszkrzaczkowski Thanks i've tried them but still getting it. Is there any log's which I can give you to help aid this please?

**Comment by alextovey** [comment]
Okay so i've solved it. Apparently Ubuntu 16.06 has an issue with apache2 with the latest upgrade I reverted back and it's working. I've put in a patch request with ubuntu for this. Strangly no error logs for it. 

Thank you for your help @mariuszkrzaczkowski
