### ISSUE TITLE
[PL]Mail scanner

### ISSUE THREAD

**Issue by jacojashi** [YetiForceCompany/YetiForceCRM#4299]
#### Czy skaner skanuje pocztę w podfolderach? Na skrzynkach, które chciałbym podpiąć nie ma funkcjonalności jak na gmail czyli folder ALL. Dodając folder INBOX skaner nie wchodzi głębiej. Jasne, że można dodać każdy folder pojedyńczo ale charakter używania skrzynek można by nazwać dynamiczny - foldery użytkownicy tworzą, przenoszą, usuwają itp to samo dotyczy samych wiadomości. Załóżmy, że mamy główny INBOX i podfolder "a" i "b".
Mam je wszystkie dodane do skanera. Jak zachowa się skaner jak przerzucę mail'a do folderu "a" a za jakiś czas trafi do "b". Czy zeskanuje go 3 razy i doda 3 maile do crm? Nie ogarniam do końca schematu działania skanera.

---
Pozdrawiam J.

**Comment by bpabiszczak** [comment]
Maile zawsze wpadają do jednego folderu a potem co najwyżej są ręcznie przenoszone. 
Jeżeli ktoś ma jakieś reguły np. w Outlook to nic nie stoi na przeszkodzie, aby zmienić tak skrypt aby skanował zawsze wszystkie foldery. To open source :]
