### ISSUE TITLE
PDF editor - clickable settings sections

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4300]
While creating PDF template headers of each section are not clickable
Clickable headers will make easy jumping across settings
See scrns
![capture](https://cloud.githubusercontent.com/assets/6852348/24085902/a2735d4c-0d36-11e7-98b0-16dd18de8526.JPG)

**Comment by PercyP** [comment]
I agree - like tabs work

**Comment by migoi** [comment]
There is more behind that. Every single page is a single form.

Possible, but not that easy to implement.

**Comment by paula-w** [comment]
Every time we open this module it annoys us that we have to go through all the tabs one by one. Unfortunately, right now we don't have time for this kind of improvements, this module is not used very often, and even if someone uses it some of these tabs take hours when you design a template. 

We will change it someday, but we are not able to tell you exactly when, so we're closing the issue for now.
