### ISSUE TITLE
PDF performance [question]

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4301]
Any plan to make PDF template products table to be editable in the same way as it is in PDF Maker (vtiger)?

**Comment by bpabiszczak** [comment]
No.

**Comment by epsilonsc** [comment]
Hi 
@waran70  @bpabiszczak  
Yes you can edit, but in small functionality 
https://gitstable.yetiforce.com/index.php?parent=Settings&module=LayoutEditor&sourceModule=SQuotes
Change the module type from basic to advanced
![advanced](https://cloud.githubusercontent.com/assets/10506580/24086195/5f499ed0-0d0b-11e7-8589-d8c1e2b20088.PNG)
