### ISSUE TITLE
[PL] Mail scanner zapisuje ustawienia folderów tylko dla Administratora

### ISSUE THREAD

**Issue by Derikus** [YetiForceCompany/YetiForceCRM#4302]
#### Issue
Mail scanner zapisuje tylko ustawienia dla administratora, jeżeli podamy innego użytkownika mimo wskazania folderów mamy informację "No folder configuration".
![nagywanie_2017_03_20_10_02_30_211](https://cloud.githubusercontent.com/assets/25840164/24093614/0335785e-0d55-11e7-8813-4ad94881f18a.gif)

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Błąd nie występuje w najnowszej wersji developerskiej.
