### ISSUE TITLE
Merge of Invoice and Dispatch Note

### ISSUE THREAD

**Issue by capriole** [YetiForceCompany/YetiForceCRM#4303]
Hi, 

I would like to ask if its possible to 'merge' the Invoice and Dispatch Note in one action (for example will taht be possible by using the mapping function?). In our company we use 'Delivery Note' also as an invoice (small sales process) so I would like to find a way to simplify the tasks in YetiForce also. 

Thanks

**Comment by mariuszkrzaczkowski** [comment]
You can add record creation actions to a workflow
