### ISSUE TITLE
Question about SMS Configuration

### ISSUE THREAD

**Issue by zeostravelling** [YetiForceCompany/YetiForceCRM#4304]
I have a ClickATell account and I'm trying to config SMS on Yetiforce 3.4.0

What does it mean this last field "mo"?

![2017-03-20 10_29_48-](https://cloud.githubusercontent.com/assets/25207269/24101875/b293cde8-0d58-11e7-9a95-b0fd4b0a9326.png)

Without filling it I'm getting the following error on SMS sending:

Fatal error: Class 'ISMSProvider' not found in /home/zeostrav/public_html/z8/modules/SMSNotifier/SMSNotifier.php on line 178

Thank you

**Comment by mariuszkrzaczkowski** [comment]
Rebuilt texting, Test the latest developer version
