### ISSUE TITLE
Hiding the phone field for different profiles

### ISSUE THREAD

**Issue by Zzik** [YetiForceCompany/YetiForceCRM#4305]
Hello. All of the managers can see counterparties. There is a sales department profile and there we can only see the name and the phone number of the counterparties. Have a profile of the shared clients - the neutral manager in it whose name the Common Base. How can we hide the phone number for the sales department from the Common base? So that visible would be only the Name - and the phone number appeared when the Manager becomes responsible for the counterparty. Best regars, Konstantin.

**Comment by mariuszkrzaczkowski** [comment]
You can add a new user "shared clients" appropriately set permissions and by switching users give access to the selected person to log on to this user
