### ISSUE TITLE
[BUG] mail skaner nie zmienia statusu zgłoszenia na "Oczekuje na odpowiedź"

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#4306]
#### Actual Behavior
Pomimo ustawienia w skanerze poczty Otwórz zgłoszenie i ustaw status "Oczekuje na odpowiedź" w przypadku zgłoszenia ze statusem zamknięte ,mail z odpowiedzią od klienta podpina się pod zgłoszenie ale status zgłoszenia nadal zostaje zamknięty.
![1](https://cloud.githubusercontent.com/assets/10506580/24106893/91ccd86c-0d89-11e7-8f28-6c9108406dd4.PNG)

#### Expected Behavior
Zamykamy zgłoszenie ustawiając status na zamknięte, klient dostaje maila z informacją o rozwiązaniu zgłoszenia odpowiada na maila i zmienia się status na oczekujące na odpowiedz. 

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version:
* Environment name and version: 
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
A jakie są ustawione statusy w 
https://gitdeveloper.yetiforce.com/index.php?module=SupportProcesses&view=Index&parent=Settings&block=6&fieldid=80

**Comment by epsilonsc** [comment]
![obraz](https://cloud.githubusercontent.com/assets/10506580/24141391/9ae3d91a-0e23-11e7-9d95-2e8f467ae7aa.png)
