### ISSUE TITLE
Recording Control - Colors

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4307]
#### Issue

NOt work "Recording Control" when use "More Than Hours XXXX". If i try other conditions like "has change", works OK.

![image](https://cloud.githubusercontent.com/assets/3030997/24122055/3bd03d72-0d99-11e7-810a-df77fa218947.png)

![image](https://cloud.githubusercontent.com/assets/3030997/24122155/895c9e78-0d99-11e7-8631-d43c0289ada8.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Stable 4.0
* Browser name and version: chrome
* Environment name and version: Dev
* Operating System and version:

**Comment by skramanzia** [comment]
@TomaszQr Is possible display "Recording Controls - Colors" in Dashboard with the widgets?.

**Comment by epsilonsc** [comment]
@TomaszQr Czy mogę prosić o krótka instrukcję w jakie sposób skonfigurować powyższe kolorowanie rekordu.
Dodałem w Konfiguracja systemu > Automatyzacja > Kontrola zapisu > Start nową Walidacje dostępu jak poniżej.
![1](https://cloud.githubusercontent.com/assets/10506580/24254527/70287020-0fe3-11e7-8425-3a52f7e3e924.PNG)
![2](https://cloud.githubusercontent.com/assets/10506580/24254531/71cf79d2-0fe3-11e7-906d-44a45b008a12.PNG)
![3](https://cloud.githubusercontent.com/assets/10506580/24254534/7415a248-0fe3-11e7-8f1d-853e1a0054a9.PNG)

Testowałem na wersji 
https://gitdeveloper.yetiforce.com/index.php?module=HelpDesk&view=List&mid=64&parent=63
