### ISSUE TITLE
[Question] Changing secret_keys.php after installation

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4311]
#### Issue

Is it possible to change the values of secret_keys.php after installation? What is the procedure?
I've added some users, how do I change their passwords after changing encryption has changed?

#### Your Environment

* YetiForce Version used: 4.0.136
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Currently, this functionality is not yet supported in the system. This will be implemented in subsequent versions of the system.
