### ISSUE TITLE
[Bug] Wrong date format in calendar record list

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4312]
#### Issue

Wrong date format in calendar record list. 
My chosen format is dd-mm-yyyy, the default format in the calendar record list filter is yyyy-mm-dd.

![untitled2](https://cloud.githubusercontent.com/assets/23050598/24143333/4b879d7c-0e21-11e7-81c8-6dcc3180f8a4.png)

![untitled](https://cloud.githubusercontent.com/assets/23050598/24143096/7d57e376-0e20-11e7-825e-9220047000f7.png)

#### Your Environment

* YetiForce Version used: 4.0.136
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by mlorencik** [comment]
On a stable version of the system everything works fine: https://gitstable.yetiforce.com/
