### ISSUE TITLE
[Question] How do you autofill related modules?

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4313]
#### Issue

How do you autofill related modules? I've been trying the last few days through field mapping and/or workflows, and I can't seem to make it work.
For example, the "Goods Dispatched Note" module is related to the "Sales Order" module through the "ssingleordersid" field. 

![untitled](https://cloud.githubusercontent.com/assets/23050598/24146384/60accab8-0e2d-11e7-93a4-c0e249b290d0.png)

How do you autofill a "Good Dispatched Note" form with information from a selected "Sales Order" on "ssingleordersid" change?

#### Your Environment

* YetiForce Version used: 4.0.136
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/user_privileges/moduleHierarchy.php#L28
