### ISSUE TITLE
[Bug] Duplicate entries in "Fields - Folders" and 

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4314]
#### Issue

Duplicate entries appear in "Fields-Folders" and also in dropdown box of some related fields.

#### Actual Behavior

![yeti_duplicate_select](https://cloud.githubusercontent.com/assets/23050598/24192299/55c76f5e-0ee6-11e7-8c01-74d1688c8fe0.gif)

![yeti_fields_folders](https://cloud.githubusercontent.com/assets/23050598/24192300/55c99cfc-0ee6-11e7-9039-409b25df1037.gif)

#### Your Environment

* YetiForce Version used: 4.0.142
* Browser name and version: Opera 43
* Environment name and version:
* Operating System and version:

**Comment by mlorencik** [comment]
Tree elements may have the same names in different locations, so do not block the possibility of adding a duplicate name

**Comment by mariuszkrzaczkowski** [comment]
The error does not exist in developer version.
check the https://gitdeveloper.yetiforce.com/
