### ISSUE TITLE
Files Upload/Download

### ISSUE THREAD

**Issue by CostasChro** [YetiForceCompany/YetiForceCRM#4315]
#### Issue
After a clean setup, I cannot upload files for example the logo of the company or download for example the libraries that are requested by the CRM. 

#### Actual Behavior
Company Logo: After selecting the files that are following the specs of the files allowed, there is now upload of any file and in addition, the name of the file appears instead of the default. It looks like the registration in the DB to be successful, but not any file available to be retracted in order to be shown.

![c2 company logo default](https://cloud.githubusercontent.com/assets/26404040/24192519/ea88c26c-0ef7-11e7-971c-22b4515350f0.JPG)
![c3 company logo default](https://cloud.githubusercontent.com/assets/26404040/24192524/ee5e4b82-0ef7-11e7-925f-2d9d13dc4392.JPG)

Contact Photo: Similar to the Company logo behavior.

Libraries: After following the prompts on the screen, i am lead to the modules installation page. I press the "Download Library", something starting to be processed but after no action is executed.  

![l3 library](https://cloud.githubusercontent.com/assets/26404040/24192597/2e25625a-0ef8-11e7-8eaa-7b8768eab1bf.JPG)

#### Expected Behavior
To download and upload normally the files

#### How to trigger the error
In the online demo, none of those behaviors are replicated

#### Your Environment
* YetiForce Version used: 4.0.0
* Browser name and version: Google Chrome Version 56.0.2924.87
* Environment name and version: N/A
* Operating System and version: MS Windows 10 x64 bit

**Comment by waran70** [comment]
Server configuration. Apart of that, Windows is not recommended environment
for critical server software

**Comment by StaggerLeee** [comment]
If I put ext libraries in right folders and click "Update library" they get deleted.

**Comment by mariuszkrzaczkowski** [comment]
Test the latest development version
