### ISSUE TITLE
Dashboard Reporting Colors

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4317]
#### Issue

I am was configuring Recording colors in Opportunities module, works OK in OP module, but in dashboard Colors not displayed.

![image](https://cloud.githubusercontent.com/assets/3030997/24208871/83d66aae-0f03-11e7-9dc9-7d3377ba0dd6.png)

![image](https://cloud.githubusercontent.com/assets/3030997/24208886/8adf1120-0f03-11e7-8bbb-94a21c022d91.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: ver. 4.0.142
* Browser name and version: Chrome
* Environment name and version: Dev
* Operating System and version:

**Comment by rjblancos** [comment]
Hello. I need your help. How you make that?. I am trying to put colors to opprtunities module and i cant. What i need to make that?. Thankyou!

**Comment by skramanzia** [comment]
@rjblancos you can configure Color in https://gitdeveloper.yetiforce.com/index.php?module=DataAccess&parent=Settings&view=Index&block=15&fieldid=52

If you have an issue or some Questions, please open a new Ticket.

**Comment by rjblancos** [comment]
Thankyou! @skramanzia you save my life.

**Comment by paula-w** [comment]
The DataAccess module will be removed from YetiForce and won’t be available in v4.3. It results from a new security policy (this functionality was badly designed which doesn’t allow us to fix the problem, we will have to write the entire functionality from scratch).
Some of the features will be added in a new place, some other will require more time or someone to pay for them in order for them to come back. We will definitely want to add record coloring, but right now we don’t know what the mechanism will look like.
