### ISSUE TITLE
[EN]Lost password: how to reset or receive a new Password?

### ISSUE THREAD

**Issue by matteoraggi** [YetiForceCompany/YetiForceCRM#4318]
Hi, I have just installed yetiforce trough softaculous on fastcomet, and I get this error: "Invalid username or password." but I can't find the reset or lost password functiona. what should I do to enter with my admin user if I lost the password?

**Comment by Felodriozola** [comment]
Hi Matteo , how you resolved it ? 
thanks!!

**Comment by matteoraggi** [comment]
I moved to suitecrm.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3962

**Comment by cybernet** [comment]
just installed 4.0 and when i try to login i get **invalid username or password**

awesome ...
