### ISSUE TITLE
[Question] I Need Help!! Pls.How edit calendar and Filters?

### ISSUE THREAD

**Issue by Zzik** [YetiForceCompany/YetiForceCRM#4319]
How to make comments in the filter group of counterparties.
![screenshot_1](https://cloud.githubusercontent.com/assets/26189213/24213960/cbe28e70-0f3c-11e7-9432-047db8b905e5.png)

You can edit the calendar module? If yes, how? 
And - 
![screenshot_3](https://cloud.githubusercontent.com/assets/26189213/24213963/cdfaf256-0f3c-11e7-862c-695306fd227d.png)

**Comment by mariuszkrzaczkowski** [comment]
Each question should be in a separate issues.The description is not sufficient to fully understand the problem.
