### ISSUE TITLE
admin username

### ISSUE THREAD

**Issue by matteoraggi** [YetiForceCompany/YetiForceCRM#4320]
From years all the online software for security reasons are suggesting a user with a username different from admin (wordpress is a big teacher about in it, for eyars was suggesting the admin username and they stopped from years to do that). I suggest to stop to force the administrators to have username "admin".

**Comment by bpabiszczak** [comment]
You're right. We plan to change that.

**Comment by alextovey** [comment]
You could change it in the database. that would sort that issue out. But all entries for admin would need changing not just the username

**Comment by kjradv** [comment]
Hi, that would not climb into the base, before installing enough to change
`<td>admin<input type="hidden" class="form-control" name="{$ADMIN_NAME}" value="admin" /></td>`
to
`<td><input type="text" class="form-control" name="{$ADMIN_NAME}" /></td>`
in /install/tpl/Step4.tpl:87
Everything is installed and working, maybe requires a test

**Comment by mariuszkrzaczkowski** [comment]
Added
https://github.com/YetiForceCompany/YetiForceCRM/commit/169d81e9ceccb223f56a59d1f01b616afbc973achttps://github.com/YetiForceCompany/YetiForceCRM/commit/9fb030cf77767dd490eb29d95595a9195f09dced
https://github.com/YetiForceCompany/YetiForceCRM/commit/bbee430e5564a9ea35d564032075b0b6cbd99819
