### ISSUE TITLE
"Update library" button has no effect [4.0.0]

### ISSUE THREAD

**Issue by NginUS** [YetiForceCompany/YetiForceCRM#4321]
#### Issue

Clicking the "Update library" button on the "Module Management" page does nothing.

#### Actual Behavior

After clicking "Download" & getting green "Downloaded" check icon in the "Status" button, I click the "Update library" button in the "Actions" column, & there's a brief progress indicator, then no change anywhere on the page.

#### Expected Behavior

Expected for the "Update library" button to cause the line item to disappear upon successful update, & for the function to appear in the list of modules in the 2 checkbox-columns below.

#### How to trigger the error

1. Open "System settings > Modules - Installation" page
2. Click "Download" button in "Status" column
3. Click "Update library" button in "Actions" column

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Chrome Version 57.0.2987.110 (64-bit)
* Environment name and version: php 5.6, nginx 1.10.0-0ubuntu0.16.04.4, mysql-server-5.7
* Operating System and version: Linux Mint 18 (Ubuntu 16.04)

Screenshot:
https://imgur.com/a/WxbCH

**Comment by mariuszkrzaczkowski** [comment]
You have the latest version of the library so you can not update it
