### ISSUE TITLE
Since update to 4.0 My PDF's are showing up wrong!

### ISSUE THREAD

**Issue by infoTopcloudxl** [YetiForceCompany/YetiForceCRM#4323]
#### Issue
Since i Updated the CRM from version 3.4.1 to 4.0 I have  a problem with the PDF's Generating. Here a example of how it looks like now: http://i.imgur.com/tfo0H37.png

The pdfs are giving the Slugs, not the actual details it needs to do.
#### Your Environment
Version 4.0
All the modules and libarys are up to date: http://i.imgur.com/TBRbEeU.png

**Comment by nkzach** [comment]
Try to open the old pdf, copy the source code, create a new pdf, paste the source code and change all the fields with the new ones.

**Comment by mariuszkrzaczkowski** [comment]
The engine for the variables has changed and you need to change the code
