### ISSUE TITLE
Virtual Desk | Question - Enhancement

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4324]
The latest version of YF incorporates multiple panels in "Virtual Desk". Is it possible for the user to select his / her preferred window?.

 For example if are four tabs like: Principal - Sales - Marketing - Support

The user can select if "Sales" tab displayed for default

**Comment by mariuszkrzaczkowski** [comment]
Currently, there is no such possibility,
Nice idea waiting for order.
