### ISSUE TITLE
[BUG] When creating Standard modules> Fields - Folders

### ISSUE THREAD

**Issue by Zzik** [YetiForceCompany/YetiForceCRM#4326]
#### How to trigger the error

1. ![screenshot_2](https://cloud.githubusercontent.com/assets/26189213/24351237/9a16183a-12ed-11e7-8d23-755487d07525.png)

After this error, the global search has ceased to work.

#### Your Environment

* YetiForce Version used: Latest version
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version: Windows 10

**Comment by mariuszkrzaczkowski** [comment]
Not enough information

**Comment by mlorencik** [comment]
Pull new versions and check, problem is smilar to #4265 and solved in da219a3
