### ISSUE TITLE
How to add existing field from Products to Sales order products view

### ISSUE THREAD

**Issue by capriole** [YetiForceCompany/YetiForceCRM#4327]
#### Issue
How can I add a new column in the products/services area of the Sales Order and Invoice?

#### What I want to do and where I have looked 
I want to add/display the 'Serial no' column from Products to the Sales Order product header(?) view. I edited the Sales Orders layout in advance block and in particular in basic line but that field/column is missing from there, so my question is how can I display that in the Sales Orders and Invoice product item lists.

![add_serialno_ticket](https://cloud.githubusercontent.com/assets/23354141/24370578/8f9d2ed2-1330-11e7-9ca9-82596d3cbb97.gif)

PS Sorry for my lame video/gif but its my first attempt to use it :)

Thanks

**Comment by alextovey** [comment]
Do you want to see it in the main view or in the actual view when creating entries?

**Comment by capriole** [comment]
Hi Alex, 

I would like to see it in both views and if possible to have it auto-populated as this value is already present in the products table. I want to work similar to the unit or price field which are also populated upon the selection of a product in the sales order.

**Comment by worldwidehigh** [comment]
Same Question!

**Comment by mariuszkrzaczkowski** [comment]
In the panel you can add a new column.
Automatic value copying can be set in the database
See how it is done in other places
