### ISSUE TITLE
Faktura kosztowa bez numeru faktury [PL]

### ISSUE THREAD

**Issue by ennoct** [YetiForceCompany/YetiForceCRM#4329]
#### Issue

Wystawiając fakturę kosztową w **Księgowość >Faktury kosztowe > Dodaj rekord** brakuję pola do wprowadzenia numeru faktury. Ta sama sytuacja podczas edycji, brakuje możliwości edycji/dodania jej numeru.
W jaki sposób mogę uaktywnić to pole do edycji w YetiForce 4.0.0 ?

#### Your Environment

* YetiForce Version used: **4.0.0** 
* Browser name and version: **Chrome 56.0.2924.87 (64bit)**
* Environment name and version:
* Operating System and version: **Windows 10**

**Comment by mariuszkrzaczkowski** [comment]
To pole jest nie edytowalne i generowane automatycznie i to nie jest błąd tak powinno być

**Comment by bpabiszczak** [comment]
Chodzi pewnie o pole numeru faktury dla której korekta jest realizowana? Jeśli tak, to powinien ten numer być pobierany do PDF-a automatycznie na podstawie pola uitype10 do faktury.

**Comment by galciu** [comment]
Nie chodzi o korekty, tylko o faktury KOSZTOWE.
czyli "numer faktury":
![image](https://cloud.githubusercontent.com/assets/19497690/24509942/154d73b4-1568-11e7-8676-03f00047916d.png)

to nie jest realnyh numer faktury (z dokumentu) tylko numer w systemie?

Więc realny numer faktury oraz od kogo jest faktura wpisujemy w polu "temat"?
(w sensie tak to zostało przemyślane?)

Serdecznie pozdrawiamy.

**Comment by bpabiszczak** [comment]
Za szybko odpisałem :] Numer na fakturze kosztowej to numer systemowy, możemy dodać sobie nowe pole gdzie możemy wprowadzić numer dokumentu oryginalnego.
