### ISSUE TITLE
Brak możliwości wygenerowania faktury cyklicznej z zamówienia okresowego [PL]

### ISSUE THREAD

**Issue by ennoct** [YetiForceCompany/YetiForceCRM#4331]
#### Issue

Brak możliwości wygenerowania faktury z zamówienia okresowego. 

#### Actual Behavior

Dodając rekord w zamówieniach okresowych w rubryce **Okresowe generowanie > Moduł docelowy** do wyboru jest tylko opcja "Zamówienie jednorazowe". W jaki sposób mogę wygenerować fakturę cykliczną z zamówienia okresowego? 

![zamowienia okresowe](https://cloud.githubusercontent.com/assets/26719341/24400200/d29b568a-13af-11e7-9958-2a4bfcad6c76.jpg)

#### Expected Behavior

Brakuje opcji generuj fakture z zamowienia okresowego.

#### Your Environment

* YetiForce Version used: **4.0.0**
* Browser name and version: **Chrome 56.0.2924.87 (64bit)**
* Environment name and version:
* Operating System and version: **Windows 10**

**Comment by bpabiszczak** [comment]
Nie brakuje, tak to zostało zaprojektowane, że musi powstać zamówienie a ewentualnie z zamówienia faktura :]

**Comment by ennoct** [comment]
Tak właśnie myślałem ale nie mogłem wygenerować faktury z zamówienia.  po kliku dniach klikania niestety nadal nie udało mi się tego zrobić. 
Proszę o jakieś wskazówki jak mam wygenerować fakturę z zamówienia.

**Comment by bpabiszczak** [comment]
Nie prościej było zamówić pakiet wsparcia i byśmy to skonfigurowali w kilka chwil?

**Comment by ennoct** [comment]
A ile kosztowałoby te kilka chwil pomocy w konfiguracji modułu faktur. :)

**Comment by bpabiszczak** [comment]
Potrzebny byłby pełen opis biznesowy jak to ma działać [może ktoś od nas zadzwonić i "wyciągnąć" to od kogoś jeżeli nie możecie sami tego opisać. Wówczas podamy czas i koszt realizacji.

**Comment by ennoct** [comment]
Witam,
jasne można dzwonić, spróbujemy też opisać:

Mamy kilkunastu klientów którym wystawiamy cykliczne faktury (raz w miesiącu).
Klient otrzymuje fakturę za monitoring pojazdu lub kilku pojazdów.
Fakturujemy również raz w roku za hosting.

Potrzebujemy w systemie na karcie klienta zdefiniować za jaką usługę i co jaki okres klient ma otrzymać fakturę, oraz wystawić te faktury automatycznie, a jeszcze lepiej wysłać je mailem.

**Comment by bpabiszczak** [comment]
To nie jest pełen opis biznesowy. Proszę napisać maila na info@yetiforce.com z zapytaniem, wówczas prześlemy pytania aby dopytać o pełen zakres biznesowy.
