### ISSUE TITLE
Can't save SMTP configuration

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4332]
#### Issue

YetiForce won't save my SMTP configuration, it sends the confirmation email successfully though.

#### Actual Behavior

![untitled](https://cloud.githubusercontent.com/assets/23050598/24416187/dab4c51e-13db-11e7-80b0-baeceada3b2b.png)

#### Your Environment

* YetiForce Version used: 4.0.154
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Logs???

**Comment by ruistrecht-alt** [comment]
Here it is, sorry
[system.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/878312/system.txt)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/4111
