### ISSUE TITLE
Subaccount and hierarchy 

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#4333]
Can not find hierarchy showing account subsidiaries. It rather essential ...

**Comment by PDMeira** [comment]
Yes, it's an essential issue

**Comment by nic86** [comment]
![schermata da 2017-03-30 12 13 53](https://cloud.githubusercontent.com/assets/18703633/24499711/dd12f070-1542-11e7-9a87-791357dafe8e.png)

**Comment by reeid** [comment]
O.o a bit surprising.... i would suggest to add it to  MORE menu? Or create hierarhy as a related tab... some accounts may have lots of independent departments, or whtever ...

**Comment by bpabiszczak** [comment]
We do not plan changes in this functionality.
