### ISSUE TITLE
No widgets are avalable - Virtual desk > My home page > Summary

### ISSUE THREAD

**Issue by lslotow** [YetiForceCompany/YetiForceCRM#4335]
#### Issue

When I select the drop down option 'Add Widget' from the Virtual desk > My home page > Summary screen, I can see no widgets in the drop down window. I need to arrange my home screen with widgets

#### Expected Behavior

I would like to see a list of widgets

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Where do I find the version? I downloaded and installed today so I imagine that this is the latest version.
* Browser name and version: Microsoft Edge
* Environment name and version: 
* Operating System and version:

**Comment by skramanzia** [comment]
@lslotow You need to configure the Widgets in .

https://gitdeveloper.yetiforce.com/index.php?module=WidgetsManagement&parent=Settings&view=Configuration&block=2&fieldid=67

**Comment by lslotow** [comment]
Thank you for the quick response. I think that my problem exists as I do not have many icons under the home icon in settings. I only have Home, Shop and Permissions. Where can I find the other icons for settings? I think that perhaps the widget configuration is hidden from me.
