### ISSUE TITLE
Contact could not belong to two or more accounts

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#4336]
#### Issue

A contact could not belong to two or more accounts. As an example, a Doctor could work in two or more clinics. A Director could manage two or more companies. The contact is the same, the context changes (relationship with the account).

#### Actual Behavior

I didn't find a way of doing this relationship.

#### Expected Behavior

On the account form, a way assigning an existing contact, besides the possibility of creating it that already exists;
On the contact form, a way of assigning one or more accounts for the contact, plus the possibility of viewing all account relationship that the contact has.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Softaculous
* Environment name and version: Sofocoulous 
* Operating System and version: MACOS

**Comment by reeid** [comment]
How you gonna manage such contact and this new relation in customer portal? 
There will be mess I guess...

**Comment by PDMeira** [comment]
No, just internally, this relation should be in the core product.
We had got that way in Siebel and in the old Pivotal CRM

**Comment by mariuszkrzaczkowski** [comment]
Currently it is correct, since there are other functional dependencies.
You can add a contact relation but it will not integrate with the rest of the system
