### ISSUE TITLE
Contact could not have more then one Job

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#4337]
#### Issue

Contact could not have more then one Job. As an exemple, a Doctor could be a Clinic Director and a Decision Maker, as his member of the board role.

More, if a contact works for more then one organization, a contact can have a role (job) in one account and another role in the other. 

#### Actual Behavior

As far as I notice, job (role) is singe text field.

#### Expected Behavior

If you support more then one account to contact relationship, job should be a context in that relation (triangulation object). If you don't support, job should be a multi-entry field.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Safari
* Environment name and version: Softaculous
* Operating System and version: MacOs

**Comment by paula-w** [comment]
We're not planning to change this feature. It would require coding hundreds of elements in different places. It can be solved in many ways from the business perspective, for example by adding a few contacts. Relating contacts to each other could be added.
