### ISSUE TITLE
Quick search doesn't work properly

### ISSUE THREAD

**Issue by Derikus** [YetiForceCompany/YetiForceCRM#4338]
#### Issue

Quick search doesn't work properly. 

#### Actual Behavior

When i select module and i am clicking search button. Quick search don't give any results, but when i click in button more and search with this method this works properly.

![nagywanie_2017_03_30_14_54_05_343](https://cloud.githubusercontent.com/assets/25840164/24505791/869f4eaa-155b-11e7-9e9c-b73d4e9efe25.gif)

#### Your Environment

* YetiForce Version used: 4.0.0 https://gitstable.yetiforce.com
* Browser name and version: Opera

**Comment by bpabiszczak** [comment]
Show me your cron view.

**Comment by SkavenKF** [comment]
In gitstable, cron is inactive 😃
