### ISSUE TITLE
[Suggestion] Why not use Transifex for future language translations?

### ISSUE THREAD

**Issue by ruistrecht-alt** [YetiForceCompany/YetiForceCRM#4339]
YetiForce CRM could use https://www.transifex.com for future translations, that way the community could pitch in translating every single language. It doesn't require a significant change in code.

**Comment by skramanzia** [comment]
Transifex is not an Open Source solution, may be Pootle is an alternative. 

https://github.com/translate/pootle

**Comment by paula-w** [comment]
We don't plan to use an external platform, we don't see any benefits in doing that. The current translating method is very simple and can be done at the GitHub level even by a non-tech person. It can also be done in the panel for translations, exported, and sent to GitHub.
