### ISSUE TITLE
[Question] Mail-Scanner don't bind Project Mails?

### ISSUE THREAD

**Issue by worldwidehigh** [YetiForceCompany/YetiForceCRM#4340]
#### Issue
The mail scanner does not connect my emails to my projects. The project number was specified in the email subject. All other scanner functions run perfectly.

In the mail scanner options:
- all actions have been activated
- Prefixes are used

#### Actual Behavior
Mails are not connected to the project.

#### Expected Behavior
Mails should be linked to the project.

#### Your Environment
YetiForce Version used: Yetiforce 4.0 stable
Browser name and version: Chrome latest
Environment name and version: PHP 5.6
Operating System and version: Win 10

**Comment by kjradv** [comment]
hello,
If cron is started?
When was the last run Mail Scanner Action  ?

**Comment by worldwidehigh** [comment]
Yes, cron startet corectly. Last run was for 39 seconds.

Kirill <notifications@github.com> schrieb am Fr., 31. März 2017 um
16:39 Uhr:

**Comment by mariuszkrzaczkowski** [comment]
Not enough information, check the changes made in the developer version.
We need more details about mail scanner configuration, numbering in the module, a sample message subject that has not been properly linked ...

https://github.com/YetiForceCompany/YetiForceCRM/commits/developer/modules/OSSMailScanner

**Comment by worldwidehigh** [comment]
Here are my configurations:
![02](https://cloud.githubusercontent.com/assets/20869581/24639967/b4f934be-18f3-11e7-831a-a4cb6f5ad24d.png)

![01](https://cloud.githubusercontent.com/assets/20869581/24639972/bdd14d42-18f3-11e7-87f7-01d82c66c775.png)

![03](https://cloud.githubusercontent.com/assets/20869581/24639974/c161c504-18f3-11e7-89a8-b49df44f2d94.png)

![04](https://cloud.githubusercontent.com/assets/20869581/24639977/c5362be8-18f3-11e7-94dd-bbfaca7bc029.png)

I hobe this are the Infos that you need. Another problem is that the project emails are entered twice and under the project nothing.

**Comment by mariuszkrzaczkowski** [comment]
You are using non-standard prefixes and this has been fixed in the developer version.
https://github.com/YetiForceCompany/YetiForceCRM/commit/1347f7d4efac2a22e7d9f2df1740c9e948b33ac2
