### ISSUE TITLE
Brak przycisków nawigacji w imporcie zgłoszeń

### ISSUE THREAD

**Issue by Derikus** [YetiForceCompany/YetiForceCRM#4341]
#### Issue

Brak przycisków nawigacji podczas importu zgłoszeń (Tickets)
![brak_nawigacji](https://cloud.githubusercontent.com/assets/25840164/24606189/3d48f6d4-186c-11e7-9425-171860e48b12.png)

#### Actual Behavior

Dodatkowo jak się przejdzie do importu w zgłoszeniach to system trochę się przywiesza. No chyba że ja coś źle robię ale z importem w kontrahentach i kontaktach nie miałem problemu, poza powiązaniem między modułami.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Opera
* Operating System and version: Win10

**Comment by mariuszkrzaczkowski** [comment]
Duplikat https://github.com/YetiForceCompany/YetiForceCRM/issues/4530
