### ISSUE TITLE
Check When click Save or Change status

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4342]
#### Issue

Its possible to display popup when change status for example "In Progress" to "Complete" for remember some action for example complete "Description" if not doesn't save and close.
 In this moment only have "Recording Control" to check mandatory field, but this is different.

#### Actual Behavior

Save Record or change Status in whatever module

#### Expected Behavior

validation check with popup, If it does not apply do not continue

#### Your Environment

* YetiForce Version used: V.4
* Browser name and version:Chrome latest
* Environment name and version: Dev
* Operating System and version: OSx

**Comment by mariuszkrzaczkowski** [comment]
Check Recording Control  and Block edit view

**Comment by skramanzia** [comment]
Hi @mariuszkrzaczkowski, The Recording Control and Block edit View, only block or not if condition meet, Does't display warning or popup to remember complete some fields.

Thanks

**Comment by mariuszkrzaczkowski** [comment]
You can do this but you have to write your own file to "Recording Control"
