### ISSUE TITLE
IMAP and LDAP authentication

### ISSUE THREAD

**Issue by rehanjade** [YetiForceCompany/YetiForceCRM#4343]
I want to authenticate through IMAP rather than LDAP because for LDAP I need dedicated IP.

#### Your Environment

* YetiForce Version used: 3.2.0
* Browser name and version: Chrome 57.0
* Environment name and version: bluehost.com
* Operating System and version:

**Comment by alextovey** [comment]
emails or users?

**Comment by alextovey** [comment]
your question is very vague

**Comment by rehanjade** [comment]
I want to authenticate users through IMAP.

**Comment by alextovey** [comment]
It's not possible at the moment, however you can always send a support request for custom module intergration to the team and they will give you a price for it.
