### ISSUE TITLE
contact find duplicate got error http 500

### ISSUE THREAD

**Issue by medotron** [YetiForceCompany/YetiForceCRM#4345]
contact find duplicate got error http 500
#### Issue

Already met all requirement that system show me in Software configuration.

#### How to trigger the error

![bug](https://cloud.githubusercontent.com/assets/25944878/24688973/31aba930-19f6-11e7-84b2-a4c59812350f.gif)

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

yeti 4.0
chrome 57
ubuntu 16.04 php7.0-fpm nginx mysql 5.7

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/administrator-documentation/errors/227-apache-500-internal-server-error-2.html

**Comment by medotron** [comment]
unfortunately there is no error alert in my nginx error log file.  my error_reporting is set as --E_WARNING & E_ERROR & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT

**Comment by alextovey** [comment]
whats the folder permissions? all folders should be 755 and files 644. I had this when the folders were set incorrectly and the owner was not www-data:www-data this caused major problems.

try sudo chmod -R www-data:www-data /var/www/html/ 
Or what ever the group is for the webserver.

**Comment by medotron** [comment]
I made the chmod -R 775.

**Comment by alextovey** [comment]
did you do the ownership of the files and folders?

**Comment by medotron** [comment]
yes, I made it.

**Comment by alextovey** [comment]
post your php.ini here let's have a look a the settings. Could be that php is timing out. Also did you setup the cron job correctly?

**Comment by medotron** [comment]
oh... finally I find the problem is nginx user is www! but my seting is www-data. that is wired. Thanks @alextovey

**Comment by alextovey** [comment]
no problem. :)
