### ISSUE TITLE
Importing Documents from another yetiforce system

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4346]
Morning, Not a problem just a question. Is there a way to import documents from the old CRM to the new version? I'm moving my test server over and have lot's of documents for testing relations but cant see an import function like the other modules.

Many Thanks

Alex

**Comment by alextovey** [comment]
anyone? i've tried to import the database fields but the ID's conflict with ID's elsewhere on the database

**Comment by alextovey** [comment]
@mariuszkrzaczkowski @paula-w 
Would you know how to migrate?

**Comment by bpabiszczak** [comment]
You need to create a script.

**Comment by alextovey** [comment]
Do you have a script? Would be really helpful I'm sure I'm not the only one in the same boat

**Comment by bpabiszczak** [comment]
Unfortunately, we do not have.
