### ISSUE TITLE
Sorry! Attempt to access restricted file.

### ISSUE THREAD

**Issue by keytechno** [YetiForceCompany/YetiForceCRM#4347]
#### Issue

My website www.keytechno.com is hosted on Arvixe which also hosts 2 of my other sites

keytechno.com is located in www folder

I installed Yetiforce in keytechco.com/yeti

I have configured roundcube in yeti but when i try to access http://keytechno.com/yeti/index.php?module=OSSMail&view=index&mid=113&parent=44

#### Actual Behavior
it comes up with the following error

Sorry! Attempt to access restricted file. - /home/shivaco/public_html/keytechno.com/includes/../includes/runtime/EntryPoint.php

#### Your Environment

* YetiForce Version used: [ver. 4.0.0]
* Browser name and version: Chrome Version 54.0.2840.87 m
* Environment name and version: 
* Operating System and version:

**Comment by PercyP** [comment]
Hi,

I had this. I fixed mine by changing all the folder permissions. You can do this via SSH, or Filezilla changing files to 644 and folders to 755 - at least that is what fixed my problem.
