### ISSUE TITLE
E-mail scanner folder not found

### ISSUE THREAD

**Issue by KarenNL** [YetiForceCompany/YetiForceCRM#4348]
Hi,<br />On my mailscanner I get the error: No folder configuration. When I click on folder icon, I get: ERR_INCORRECT_ACCESS_DATA<br />Is this a bug or problem with my server settings? <br />​​​​​​​<br /><hr />Generated by YetiforceCRM ver. 4.0.0<br />PHP: 5.6.30<br /><br /><strong>Server configuration errors:</strong><br />default_socket_timeout: 60<br />max_input_vars: 1000<br />expose_php: On<br />mysql.connect_timeout: 60<br />innodb_lock_wait_timeout: 50<br />wait_timeout: 60<br />interactive_timeout: 120<br />suhosin.request.max_vars: 1000<br />suhosin.post.max_vars: 1000<br />suhosin.post.max_value_length: 1000000

**Comment by alextovey** [comment]
More than likely server settings. Is all your folders set to chmod 755 and files 644? Also do you actually have the folder if not then download the installer again from the website and ftp the folder over to the site.

**Comment by KarenNL** [comment]
I have reset the CMOD (Maps: 755) (files: 644) and the problem presist. Witch folder? Where can I download it and where in FTP can I put it?

**Comment by alextovey** [comment]
@KarenNL https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.0.0/YetiForceCRM-4.0.0-complete.zip

This is the complete source

**Comment by KarenNL** [comment]
Yes! It's work.
