### ISSUE TITLE
Not able to create reports

### ISSUE THREAD

**Issue by infoTopcloudxl** [YetiForceCompany/YetiForceCRM#4349]
#### Issue
When I want to create a report it keeps loading the page at step 2, so im not able to run or save the report.

see screenshots: 
![image001 1](https://cloud.githubusercontent.com/assets/18213240/24756214/4ab72ffc-1add-11e7-957e-baa5a20a9b13.jpg)
![image001](https://cloud.githubusercontent.com/assets/18213240/24756215/4abb3e76-1add-11e7-9b8f-b4cc862d0e72.jpg)
![8nfwypd 1](https://cloud.githubusercontent.com/assets/18213240/24756976/0a1e657c-1ade-11e7-9920-1d7de5ece373.png)

#### Expected Behavior
I would like to have a report being generated.

#### How to trigger the error
1. Run reporting tool in the backoffice
2. go thru the wizzard
3. Click at step 2 at next. Here it keeps loading

#### Your Environment
Yeti 4.0
Linux ubuntu server

**Comment by skramanzia** [comment]
Its Webserver Issue, check the link, and verify if all requirements meet.

https://yetiforce.com/en/administrator-documentation/errors/227-apache-500-internal-server-error-2.html

https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by alextovey** [comment]
@skramanzia you say that but my server is 100% with inline the requirements but I get a whirling generating pdf when trying too with 4.0

**Comment by infoTopcloudxl** [comment]
Yes same problem here.. Our service is 100% inline with the requirements aswell, is there already a fix for? or how much if you will fix it with profesional support? I need to get this fixed ASAP!!!

**Comment by mariuszkrzaczkowski** [comment]
Add screenshots of all steps and larger sizes
