### ISSUE TITLE
[Question] Finding duplication in selected records. 

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4350]
At the moment, finding duplication is implemented within all records and there is noway to check a specific area. I'm looking for a solution for this issue, such as creating a tool action to check duplication in a selected record.

**Comment by mariuszkrzaczkowski** [comment]
It would be possible to add the possibility of always looking in the selected filter but someone had to order it

**Comment by ezbank** [comment]
I will probably order it and you tell me the price I will pay?

**Comment by KatarzynaUlichnowska** [comment]
Hello, it will take us about 6 hours and you can pay via https://shop.yetiforce.com/en/
