### ISSUE TITLE
help about views

### ISSUE THREAD

**Issue by ousidahou** [YetiForceCompany/YetiForceCRM#4351]
hi there, 

i'm trying to delete this, {please look at the attachement},

thank you.

![sans titre](https://cloud.githubusercontent.com/assets/22946462/24797403/02fb130c-1b89-11e7-9b1a-4b62c779ec18.png)

**Comment by nic86** [comment]
only in version 4 you can change this value 
[HIDE_SUMMARY_PRODUCTS_SERVICES](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/Accounts.php#L14)  
equal true

**Comment by ousidahou** [comment]
so should delete all the project & start a new one :(

But Thanks For you help

**Comment by nic86** [comment]
If you have an older version should work on this line of code

https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Accounts/models/DetailView.php#L67-L83
