### ISSUE TITLE
Installation Timeout & PHP Error

### ISSUE THREAD

**Issue by Rockyuk** [YetiForceCompany/YetiForceCRM#4352]
I have been trying to Install Yetiforce for the past three days and have been unsuccessful. I am installing it on a sub domain on my Cpanel & CloudLinux platform. I am using the latest version of Cpanel & CloudLinux and i am trying to install Yetiforce on a dedicated server.

Yetiforce version 4
Google Chrome Version 57.0.2987.133 (64-bit) (Linux)
Linux Mint 18.1 64Bit

Everytime i try to install the installation times out, my server meets all the scripts requirements perfectly. I get the following error below everytime i try to install. Private info has been changed for security reasons.

[07-Apr-2017 21:15:41 UTC] PHP Notice:  Use of undefined constant ROOT_DIRECTORY - assumed 'ROOT_DIRECTORY' in /home/username/mysubdomain/include/ConfigUtils.php on line 165

**Comment by mlorencik** [comment]
Please check the server requirements, mayby change max_execution_time in php.ini to more than 600 and display_errors to off
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by Rockyuk** [comment]
Yeah my server requirements are fine i think it is an issue with CageFS with CloudLinux. I have installed it on another Cpanel server fine with no issues.
