### ISSUE TITLE
Yetiforce version 4 - 504 Gateway Time-out

### ISSUE THREAD

**Issue by midotka** [YetiForceCompany/YetiForceCRM#4353]
I am installing Yetiforce version 4 on my vserver:
- CENTOS 6.9 x86_64 virtuozzo – server WHM 62.0 (build 20)
- Running WHM on it

**After about 10 Minutes I am getting a timeout (504 Gateway Time-out - nginx)**
I have installed all the required modules and configured the php.ini in a way that I get no warnings during installation.

I have tied on different vServers and also on another provider Gigawebhost - with the same configuration (WHM, cPannel). All other scribts (vtiger, sugar, ...) I was able to install. 

Has someone experienced and solved the same issue?
Thanks a lot for your help, Michael

P.s. The installation of Version : 3.4.0 is working - 
Updating to 3.4.1427 and 4.0.0 ends up in a timeout again.

**Comment by mlorencik** [comment]
Please check the server requirements, mayby change max_execution_time in php.ini to more than 600
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by midotka** [comment]
Thank you, I tried max_execution_time 600, 6000, 10000 and even 20000 - same result (504 Gateway Time-out - nginx).
vTiger is installing without problems. However, I would like to use Yetiforce.
Please tell me if you have any more recommendation

**Comment by mlorencik** [comment]
Have you changed the max_execution_time to 6000 and after one hours and 40 minutes you still see this code, or do you still see 504 code after 10 minutes?

**Comment by skramanzia** [comment]
@midotka try this in your nginx site file config. And check files and folder permissions 

fastcgi_read_timeout 600;
        proxy_send_timeout  600;
        proxy_read_timeout  600;
        proxy_connect_timeout    600;
        send_timeout    600;
