### ISSUE TITLE
Problem with notifications

### ISSUE THREAD

**Issue by rjblancos** [YetiForceCompany/YetiForceCRM#4354]
#### Issue
Hello, i have a problem i dont see my automated notifications.
I create a Ticket, and the ticket is comented or actualizated and nothing in the superior right website side.

And the admin i dont see the notifications web:

Gitdeveloment:
Software configuration > System tools > Notifications - configuration > Configuration view
![image](https://cloud.githubusercontent.com/assets/24235856/24881883/d44c7400-1e04-11e7-8694-c7238a058e39.png)

My Site:
Configurar Software > System tools > Notifications - configuration > Configuration view
![image](https://cloud.githubusercontent.com/assets/24235856/24881911/edc05bcc-1e04-11e7-8895-0a15693f09c4.png)

I need if someone update a support ticket or a Internal Ticket that Generate a Notification automatic in the User panel:
![image](https://cloud.githubusercontent.com/assets/24235856/24881996/3438b2d4-1e05-11e7-8136-a3881834fc27.png)

Thanks for the patience.

Rafael Blanco

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version: CentOs

**Comment by ezbank** [comment]
My system is similarly faulty

**Comment by konadrian** [comment]
For me it's works fine
![bez tytulu](https://user-images.githubusercontent.com/3193498/29060657-02091c4e-7c1b-11e7-8f80-6ffc96521b02.png)
![bez tytulu1](https://user-images.githubusercontent.com/3193498/29060658-020923b0-7c1b-11e7-8d1b-7a3122c40fb8.png)

**Comment by ezbank** [comment]
not works for me. v4.1.108
![screenshot 34](https://user-images.githubusercontent.com/19627226/29066465-7a81cf3e-7c59-11e7-82ff-73b6c6ab429b.png)
This is my configuration, I missed something?
![screenshot 31](https://user-images.githubusercontent.com/19627226/29066502-8f310c1a-7c59-11e7-9129-be07638f5fcc.png)
![screenshot 32](https://user-images.githubusercontent.com/19627226/29066507-910cc6b4-7c59-11e7-9421-d1820ae61bde.png)
![screenshot 33](https://user-images.githubusercontent.com/19627226/29066510-93802486-7c59-11e7-9a5a-7922295beee1.png)

**Comment by konadrian** [comment]
Can you add members into notifications ?

**Comment by ezbank** [comment]
no. When clicked but not effective

**Comment by konadrian** [comment]
Even on gitdev version?

**Comment by ezbank** [comment]
On gitdev, it works correctly
