### ISSUE TITLE
Roundcube Spellchecker add to dictionary

### ISSUE THREAD

**Issue by Rockyuk** [YetiForceCompany/YetiForceCRM#4355]
I am unable to add to dictionary when spell checking emails in Roundcube there is no function.

YetiForce Version used: 4.0
Browser name and version: Chrome
Environment name and version:
Operating System and version: CentOs/Cpanel

**Comment by mariuszkrzaczkowski** [comment]
We need more details how to trigger the error.
Please send us a screenshot or gif which will show how to trigger the bug
