### ISSUE TITLE
Question: Is there a way to increase the size of a default value in a WYSWYG Editor custom field?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4358]
Hi,

I need to add a block of text inside a custom module/custom block that is automatically displayed on every record. I couldn't see a way to do this with any of the current field types.

However, I realised that if I used the custom field WYSWYG Editor, I could add the text I needed to display as default into the Default text box in the field settings, and set it to not be editable - great - this meets my needs to a point.

However, my block of text is an A4 page long, and in my record it only displays the first 160 words. 

Is there a way to get this one field to show the entire text in the WYSWYG Editor field in my record? I tried changing the max text length value to much higher settings i.e. 6000 but it doesn't have any effect on what is displayed in the record view.

Is there a way to show my entire form in the WYSWYG Editor field in my record? It needs to be in the default field so it is part of every record automatically in my custom module - unless there is a better way to do this?

Kind regards

**Comment by mariuszkrzaczkowski** [comment]
Take a screenshot with an example
