### ISSUE TITLE
[improve]  global footer for all outgoing emails

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#4361]
Perhaps it's worth adding field insertion from the user module. I think it would be convenient to create a signature for the co-worker on a single template, but with their personal data

**Comment by mariuszkrzaczkowski** [comment]
It's already in the system, see
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Mail&view=Config&block=8&fieldid=79
