### ISSUE TITLE
CC mail admin [BUG]

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4363]
#### Issue

When schedule a report to send email, all mails include administrator in CC.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Latest stable version
* Browser name and version: chrome and firefox
* Environment name and version:
* Operating System and version:

**Comment by skramanzia** [comment]
Always scheduled reports add in CC the administrator email.

**Comment by skramanzia** [comment]
User 1 (admin) is not on the mailing list, but all reports add in CC the admin email.

![image](https://cloud.githubusercontent.com/assets/3030997/25664798/1de82894-2ff2-11e7-8781-872d68378fec.png)

![image](https://cloud.githubusercontent.com/assets/3030997/25665018/c538a146-2ff2-11e7-89d8-d0773a45026a.png)

**Comment by ezbank** [comment]
Yes

**Comment by mariuszkrzaczkowski** [comment]
Does the problem still exist in the newest version?

**Comment by skramanzia** [comment]
@mariuszkrzaczkowski Yes, still continues
