### ISSUE TITLE
Roundcube/EMail does not work ...

### ISSUE THREAD

**Issue by CobaJashi** [YetiForceCompany/YetiForceCRM#4364]
Hello :)
We have just installed version 4.0.0.

Roundcube / Email does not work. Ideas where the error is found? We can call him via modules / OSSMail / roundcube / ...

![modules](https://cloud.githubusercontent.com/assets/20491699/25096969/cf036be0-23a2-11e7-90e2-dd796230b263.png)

![roundcube](https://cloud.githubusercontent.com/assets/20491699/25096970/cf03b884-23a2-11e7-86a5-80cfbf10f683.png)

![mail](https://cloud.githubusercontent.com/assets/20491699/25096971/cf063028-23a2-11e7-8257-13cfe98eed8b.png)

**Comment by sirwinston1** [comment]
make sure you activate My Mailbox in the module list.

![mailbox](https://cloud.githubusercontent.com/assets/6587713/25104342/1f9afbb6-237d-11e7-8525-bb3be84ef071.JPG)

**Comment by CobaJashi** [comment]
Thanks: D ... not seeing the forest in front of loud trees: D
