### ISSUE TITLE
[Question] Multiple offices with separate permissions?

### ISSUE THREAD

**Issue by tkome** [YetiForceCompany/YetiForceCRM#4365]
#### Issue
I'm wondering if it's possible to configure roles / permissions to organize users in separate offices where they share data within office, but no sharing between offices ? Maybe some behavior based on 'Reporting to' field (user details) and role?

Let's assume following organization structure:
Headquarters (role: headquarters) -> Office (role: office) -> Employee (role: employee)

#### Actual Behavior
- office as superior to employee accesses all employees within office (works fine)
- one office can't share with another office (works fine)
- headquarters have administrative privileges and access to all offices (works fine)

#### Expected Behavior
- employees share access within office but not between offices

#### Your Environment

* YetiForce Version used: 4.0.0

**Comment by tkome** [comment]
The only workaround I've found so far is to define role per office and in module access define sharing between this role itself. This is rather uncomfortable solution, not the only one I hope.

**Comment by KatarzynaUlichnowska** [comment]
There is a tool that allows you to create exceptions [e.g. people in the same office see all their data] and it can be found here: https://gitdeveloper.yetiforce.com/index.php?module=SharingAccess&parent=Settings&view=Index&block=1&fieldid=5 - use an "Advanced sharing rules" option.

**Comment by untecnologo** [comment]
@KatarzynaUlichnowska Where I can find it in the 5.0 version? I mean "Advanced sharing rules" option. I have this problem, we are a multinational company in every country exist different branches and they can share nothing between them but the region supervisor can access to all of them.
