### ISSUE TITLE
Is there a way to force Text area custom field to 100%

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4366]
Hi,

I have some custom fields (Text Area type) and want them to display all the content. At the moment (even though I set the width to 100% it still remains the same size as other custom fields. The WYSWYG Editor field does display 100% if this is set, but the text area field doesn't. I would use the WYSWYG editor but I would need the toolbar to be hidden and guessing this isn't possible on a field by field basis?

As it has the option to change the width in the field settings, I am assuming it just be able to do this? Is there a way for me to force the field to accept the dimension I set?

It would also be good if we could specify a height for custom Text Area and WYSWYG fields.

Any help would be most appreciated.

**Comment by mariuszkrzaczkowski** [comment]
Set in fieldparams value {"class":"ckEditorBasic ckEditorSmall"} for uitype 300
You will get the effect
![image](https://user-images.githubusercontent.com/10198654/29030260-bc85484a-7b8a-11e7-9b48-f9ea637c92ea.png)
