### ISSUE TITLE
To Do List & Notifications

### ISSUE THREAD

**Issue by Rockyuk** [YetiForceCompany/YetiForceCRM#4367]
Hi Everyone,
I have the latest version 4 of Yetiforce installed and seem to be finding more and more bugs. Maybe i am missing something but i can't get the following to work.

![to do list](https://cloud.githubusercontent.com/assets/26884071/25128609/2ca3d318-2432-11e7-8ea2-f0077b54d479.jpg)

The above three buttons don't work when they are pressed!

![notification config](https://cloud.githubusercontent.com/assets/26884071/25128660/57c771da-2432-11e7-8e1e-ac3124b9a7a8.jpg)

I cannot seem to configure the above notifications configuration options. I have the cron running but do not receive any notifications via email.

#### Your Environment
CentOS 7.0
cPanel Version
64.0 (build 12)
Apache Version
2.4.25
PHP Version
5.6.30
MySQL Version
5.6.35
Architecture
x86_64
Operating System
linux
Path to Sendmail
/usr/sbin/sendmail
Path to Perl
/usr/bin/perl
Perl Version
5.16.3
Kernel Version
3.10.0-229.1.2.el7.x86_64

**Comment by skramanzia** [comment]
You can configure SMTP Server to send emails.

https://gitdeveloper.yetiforce.com/index.php?module=MailSmtp&parent=Settings&view=List&block=8&fieldid=105

**Comment by Rockyuk** [comment]
Hi Skramanzia,
I have already configure the sendmail option which sends me an email to confirm it has successfully been setup. Still no notifications.

**Comment by rjblancos** [comment]
I have the same problem. https://github.com/YetiForceCompany/YetiForceCRM/issues/4354

**Comment by vovpff** [comment]
@Rockyuk are you use latest stable 4 version or developer?
