### ISSUE TITLE
Error Under Permissions

### ISSUE THREAD

**Issue by Rockyuk** [YetiForceCompany/YetiForceCRM#4368]
When trying to create groups under permissions i get the following error

Software configuration > Permissions > Groups > Create

Error!!!
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ttwebhos_yetiforce`.`vtiger_group2modules`, CONSTRAINT `vtiger_group2modules_ibfk_2` FOREIGN KEY (`tabid`) REFERENCES `vtiger_tab` (`tabid`) ON DELETE CASCADE) The SQL being executed was: INSERT INTO `vtiger_group2modules` (`groupid`, `tabid`) VALUES (7, 0)

Your Environment

CentOS 7.0
cPanel Version
64.0 (build 12)
Apache Version
2.4.25
PHP Version
5.6.30
MySQL Version
5.6.35
Architecture
x86_64
Operating System
linux
Path to Sendmail
/usr/sbin/sendmail
Path to Perl
/usr/bin/perl
Perl Version
5.16.3
Kernel Version
3.10.0-229.1.2.el7.x86_64

**Comment by mariuszkrzaczkowski** [comment]
I tested the development version and it works.
https://gitdeveloper.yetiforce.com/index.php?module=Groups&parent=Settings&view=List&block=1&fieldid=4
