### ISSUE TITLE
Roundcube  update 

### ISSUE THREAD

**Issue by hipernet** [YetiForceCompany/YetiForceCRM#4370]
Nie znaleziono wymaganej biblioteki roundcube. Część funkcjonalności została zablokowana. Aby pobrać należy przejść do Moduły - instalacja

Przechodzę do konfiguracji i wymagana aktualizacja kilkam nie aktualizuje się  
Przechodzę do  poziomu moja poczta pojawia się komunikat:

Forbidden

You don't have permission to access /modules/OSSMail/roundcube/ on this server.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

* YetiForce Version used:  [ver. 3.4.1427
* Browser name and version: Firefox
* Environment name and version: 
* Operating System and version:Windows 10

**Comment by bpabiszczak** [comment]
Proszę uaktualnić system do wersji stabilnej i wówczas pobierać biblioteki, dla wersji częściowych należy ręcznie dograć sobie biblioteki.

**Comment by hipernet** [comment]
problem w tym że  4.0 też nie wchodzi  z poziomu update

**Comment by bpabiszczak** [comment]
to proszę otworzyć oddzielny wątek z pełnymi logami, wówczas postaramy się pomóc.

**Comment by hipernet** [comment]
ok
