### ISSUE TITLE
Question - can Web Service Users & Web Service Applications be used to post yetiforce form data to a website?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4373]
Hi,

I want to post form data from my custom module into my website and just wanted to know if this is what Web Services Users, and Web Services Applications is for?

Basically I want to be able to save field values from within my module to a component on my website which has the same fields. Each user on my website has their own unique login and subscription level, so they would need to login/or be logged in to the website before posting, under their own unique login details. 

At the moment I am thinking the post is a one time only (so the user selects something in yetiforce i.e. a Save to website button, or just a checkbox) and it triggers the save process. Ideally it would be nice to update the website if any changes are made to the yetiforce record.

My question is this:

Is Webservice users for creating such a connection (where the user login details for a external website are set)
Are Web applications the tool we use to create the above process to save the form data?

Are there any instructions anywhere that explain what these 2 components do?

Kind regards

**Comment by kabelo38** [comment]
Wordpress??

**Comment by mariuszkrzaczkowski** [comment]
When writing data in CRM you want to send data to a web page, you need to write a script to workflow.
Web Service allows you to get and save data.

**Comment by PercyP** [comment]
Is there any guidance you know of that could help me do this? I did send a custom work request to yetiforce but never heard back so guessing it is something they don't do.

**Comment by kabelo38** [comment]
you have to use callback function

**Comment by PercyP** [comment]
Would you know of any guidance to get me started or even a sample?

**Comment by kabelo38** [comment]
Starting point https://wiki.vtiger.com/index.php/Invoke_Custom_Function but outdated please below code to make it work with YetiForce


      Create file called DocumentsHandler.php put it in the root dir folder add the following contents

      include_once 'include/main/WebUI.php';
      require 'modules/com_vtiger_workflow/VTEntityMethodManager.inc';
      $emm = new VTEntityMethodManager(PearDatabase::getInstance()); 

      //uncomment this line to enable custom function for Documents Module
      $emm->addEntityMethod('Documents', 'Create a sales order', 'include/DocumentsSalesHandler.php', 'CreateSalesOrder');

On your browser click https://host/DocumentsHandler.php to register your custom function




       then create a file called DocumentsSalesHandler under include directory
        function CreateSalesOrder($entity) {
        //Your Logic Comes here
        Should you wish to access values posted from the CRM user $entity->get('Field name'); record ID = $entity->get('id')
       } 

![workflow](https://user-images.githubusercontent.com/5912376/27321250-bdea5b10-5599-11e7-9d98-f043dee9ce24.gif)


Hope this helps.
