### ISSUE TITLE
[BUG] Timeline

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4375]
v 4.0.188
![error](https://cloud.githubusercontent.com/assets/19627226/25274758/ca5b7af8-26bb-11e7-919c-fb154e5f61ce.gif)

**Comment by paula-w** [comment]
Can you explain what exactly you mean?

**Comment by ezbank** [comment]
this misstake is that when i do a record, after few seconds, i change a field of information. 2 action adding record and changing are two different time but the history shows that they act at the same moment (both are 13s before)
