### ISSUE TITLE
Changes in the license

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#4376]
We are planning to modify the YetiForce License and we want to know what you think.
Below you can find the new addition to our license, let us know your opinion in the comments. 

> Additional` Terms applicable to the YetiForce License.
>
> I. Effect.
> These additional terms described in this YetiForce License – Additional Terms shall apply to the Covered Code under this License.
> 
> II. YetiForce and logo.
> This License does not grant any rights to use the trademarks "YetiForce" and the "YetiForce" logos even if such marks are included in the Original Code or Modifications.
> 
> However, in addition to the other notice obligations, all copies of the Covered Code in Executable and Source Code form distributed must, as a form of attribution of the original author, include on each user interface screen the "Fueled by YetiForce" copyright notice in the same form as the latest version of the Covered Code distributed by YetiForce Sp. z o.o. [Ltd] at the time of distribution of such copy. In addition, the "Fueled by YetiForce" notice must be written in a font of the same size as the font of this notice in the latest version of the Covered Code, must be visible to all users, and be located at the very bottom center of each user interface screen.

**Comment by PercyP** [comment]
Hi Paula,
Should it be Fueled or Powered By? It is normally powered by. And by bottom of user interface screen do you mean where it is currently displayed?

Kind regards

**Comment by paula-w** [comment]
Hi Percy,
"Fueled by" was my idea because I wanted it to sound different than all other projects that use "powered by". For now it's a draft, it might still change, so thanks a lot for your comment!
And yes, it will be displayed where the copyright notice is currently displayed.
