### ISSUE TITLE
Custom module with 2 address blocks each with a 1:m Contact field - Problem: both Contacts have to be selected before first block will work

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4377]
#### Issue
I need to display 2 contacts and their addresses in a custom module (these details have to be displayed in full on the screen). The second contact details are optional, so this block might quite often be empty. The first block will always contain values. 

So, I have created 2 address blocks in this custom module. The block labels for these 2 blocks are:
LBL_ADDRESS_INFORMATION (block 1)
LBL_ADDRESS_MAILING_INFORMATION (block 2)

They both contain a Contact name field (1:m field to select the contact) and they both contain address fields. These will be 2 different names/addresses.

Block 1 uses addresslevel1a etc. 
Block 2 uses addresslevel1b etc.

Both work great in that the address search box and the Copy from buttons work. However there is a small issue in that I cant populate block 1 (the first block in my layout) until a block 2 Contact has been selected. 

If I move block 2 above block 1 the same problem occurs - the second block's Contact needs to be selected before the top block's Copy from button works in the top block. I get an error message saying: Please select Contact to copy address (even though a Contact is selected in top block) I am guessing it means select the second contact field also, as when I select it, the error goes away.

Is there a valid reason why both Contact fields have to be selected (in block 1 and 2) before the copy from button works in the top block?

Is there any way I can change this behavior so I can populate the first block regardless of whether anything is selected in the second block? 

#### Expected Behavior
If I select a Contact from the 1:m field in block 1 I can then use the Copy from button to populate block 1 address fields. 

I can then move to block 2 and select Contact2 and then click Copy from button and populate the address fields for Contact2

#### How to trigger the error
1. Create a custom module with 2 blocks naming the labels as above so the copy from buttons appear
2. Add a Contact1 field with 1:m to Contacts to block1 and add another to block2.
3. Add a couple of address fields (for block1 use those ending in 'a' i.e. addresslevel1a and for block2 use those ending in 'b' i.e. addresslevel1b)
4. Now go to the form and select a contact from the contacts table and try to copy Contact or another - nothing happens
5. Try the same with block2 - select a different contact and then click a Copy from button - it now adds address to block2
6. Now re-select a contact in block1 and select a Copy from button - it now populates

#### Your Environment
* YetiForce Version used: 4.0

Is there a way to fix this so it will populate the boxes in any order of selection (or at least allow for the first block to be selected first?, then block 2 etc.?

**Comment by KatarzynaUlichnowska** [comment]
First of all, the question is, how does the system know which contact field corresponds to the selected address fields? The system won't relate it because you placed these fields in the same block - this mechanism doesn't work like that. As far as I can remember, the mapping is performed in the main module file (but I might be wrong). 
Secondly, the problem may also exist because these are the same types of fields and we didn't program it in such a way that there can be any number of fields with the same uitype. 
Regardless of the real reason, this requires programming analysis and we charge money for that. Maybe someone from the community will help you for free.
