### ISSUE TITLE
[PL] Realizacja zadań, zmiana statusu

### ISSUE THREAD

**Issue by slawhodu** [YetiForceCompany/YetiForceCRM#4378]
Po aktualizacji do wersji 3.4.1427 nie mam możliwości zmiany statusu zadań przy nowych i zmiany starych... Co się stało? Jakieś nowe uprawnienia?

**Comment by bpabiszczak** [comment]
Proszę uaktualnić do wersji 4.0. Nikt już nie pamięta co było w wersji 3.4.1427.

**Comment by slawhodu** [comment]
przy wgrywaniu aktualizacji mam komunikat:
Fatal error: Class 'App\GetGroupUsers' not found in /firmacrm/vendor/yetiforce/PrivilegeUtil.php on line 771
i 'wskakuje wersja 3.4.1427, czyli jakby nie było update...

**Comment by slawhodu** [comment]
pomogło usunięcie cache....

**Comment by bpabiszczak** [comment]
Dziękuję za przesłanie rozwiązania, pewnie się komuś za chwilę przyda :]

**Comment by slawhodu** [comment]
tak, ale problem ze zmiana statusu dalej istnieje dla użytkownika (właściciela kalendarza). Ja jako admin mogę zmieniać statusy zadań w kalendarzu, użytkownik swoich nie może...

**Comment by bpabiszczak** [comment]
w sensie dla wersji 4.0 czy innej? 
jak dla wersji 4.0 to należy sprawdzić czy problem występuje na wersji stable i developer i dokładnie opisać jak go wywołać na wersji developerskiej.

**Comment by slawhodu** [comment]
wersja 4.0
pytanie - czy nie dodaliście jakichś uprawnień co do zmiany statusu.
Dla użytkownika.

**Comment by bpabiszczak** [comment]
Jak coś "popsuliśmy" to naprawimy i podamy Tobie link abyś u siebie też poprawił, ale za nim to zrobisz, musisz dokładnie sprawdzić czy błąd występuje na wersji np. stable i najlepiej nagrać film jak błąd wywołać, ponieważ nie mamy czasu aby "szukać" błędu, dlatego musisz go dobrze opisać i udokumentować, wówczas my go naprawimy.

**Comment by slawhodu** [comment]
na bazie demo (z Państwa strony) user - tester
robimy z jego poziomu nowe spotkanie w kalendarzu - status 'planowane' (nie może zmienić na inny w czasie tworzenia). Po zapisie zadanie jest jako już 'wykonane'.

**Comment by bpabiszczak** [comment]
czyli prawidłowo :] Przy tworzeniu nie można zmienić statusu [jest ustawiany automatycznie przez system] ale można automatycznie zamknąć nowo dodany termin - o ile dobrze pamiętam są dwa przyciski do zapisania czy wiesz który do czego służy?

**Comment by slawhodu** [comment]
tak, są dwa ale tylko w przypadku wprowadzania zdarzeń 'do tyłu'. Mnie chodzi o spotkania o statusie 'zaległe'. Wczoraj na demo system zachowywał się tak jak u mnie, czyli był problem. dzisiaj jest OK.
Jak klikam na pozycję w kalendarzu pojawia się okno 'ustaw status' i można go zmienić. U mnie pojawia się okno i można tylko je zamknąć...

**Comment by slawhodu** [comment]
Sprawa chyba dotyczy uprawnień bo admin może zmienić status spotkania. Niestety nie mogę znaleźć takiego uprawnienia. Musiało się coś przestawić w czasie aktualizacji...

**Comment by hipernet** [comment]
na czystym systemie na tym samym serwerze poszło  bez błędów

**Comment by bpabiszczak** [comment]
tyle dyskusji tylko dlatego, że nie nagrałeś filmu jak wywołać błąd na gitstable.

**Comment by slawhodu** [comment]
na czystym systemie. Ja aktualizowałem więc MUSI być jakiś nowy parametr w aktualnej wersji bo dotąd wszystko chodziło...

**Comment by slawhodu** [comment]
![image](https://cloud.githubusercontent.com/assets/12712615/25740635/a3f275ac-3187-11e7-9fe9-1c81fc0ad545.png)
nie mam możliwości wybrania statusu

**Comment by slawhodu** [comment]
na gitstable błąd nie występuje! Użytkownik należący do grupy sprzedawcy
nie może sobie zmieniać statusu zadania.
Grupa ma przydzielone widoczności statusów i statusy. Po zmianie wersji na
4.0 tylko ja jako administrator mogę zmieniać status zadań.

Może weszło jakieś nowe uprawnienie...? Nie mam pojęcia...



[image: Obraz w treści 1]

_______

Sławomir Hodur

2017-04-26 21:13 GMT+02:00 Błażej Pabiszczak <notifications@github.com>:
