### ISSUE TITLE
[BUG] Error OpenStreetmap

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4383]
When search for leads, an error occurs.
The location of other modules is not shown on the map
https://gitdeveloper.yetiforce.com
dev v4.0.209

![112](https://cloud.githubusercontent.com/assets/19627226/25465795/af5a19c2-2b2e-11e7-9117-d28740e2c9af.gif)

**Comment by TomaszQr** [comment]
In current version it work properly (dev v4.0.446)
