### ISSUE TITLE
sendmail messy code

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#4384]
#### Issue
When receiving the mail theme and content are messy code
Whether the mail can use UTF-8 coding

I use Chinese

thanks
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.0
* Browser name and version:safari
* Environment name and version:
* Operating System and version:Windows2008

**Comment by copyyour** [comment]
![snip20170427_1](https://cloud.githubusercontent.com/assets/27992939/25475202/8b39b784-2b68-11e7-978f-64752a904bd6.png)

**Comment by mariuszkrzaczkowski** [comment]
Test it on the developer version
