### ISSUE TITLE
Receiving notification

### ISSUE THREAD

**Issue by chocman45** [YetiForceCompany/YetiForceCRM#4386]
Hello, I would like to know if it is possible to receive a notification in my mail whene someone creat a delivery form (with file attached) and how I can activate this option.

Thank you

Version: 3.4.0

**Comment by vovpff** [comment]
@chocman45 let's try workflows for your target

**Comment by mariuszkrzaczkowski** [comment]
Use workflow, there are special actions from the mail delivery
