### ISSUE TITLE
[BUG] No result when choose search by modun

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4387]
v4.0.213
Only when searching all records, it works correctly 
![error](https://cloud.githubusercontent.com/assets/19627226/25565278/ae5ccef8-2dee-11e7-9a3f-51f94167c110.gif)

**Comment by ssehonda** [comment]
SAME ISSUE IN MY SYSTEM TOOOOO.....

**Comment by sirwinston1** [comment]
Same here. My corns seems to be working as well
![crons](https://cloud.githubusercontent.com/assets/6587713/26121759/8b8a5602-3a32-11e7-941d-5be3128c71ee.PNG)

**Comment by mariuszkrzaczkowski** [comment]
Logs....
https://yetiforce.com/en/developer-documentation/engine/115-debugging.html

**Comment by sirwinston1** [comment]
This is the only error I can get it to log

[16-May-2017 15:07:38 America/Denver] PHP Notice:  Undefined variable: trace in /home/wloyphba/public_html/vtlib/Vtiger/Functions.php on line 729

**Comment by sirwinston1** [comment]
@ezbank Did you figure out a solution to this issue?

**Comment by mariuszkrzaczkowski** [comment]
update permissions did not work. Look at the time

**Comment by sirwinston1** [comment]
Wow how did I miss that, its the same on mine.  Cron has been stuck for month.  Thanks for the help!
