### ISSUE TITLE
mail IMAP config

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#4388]
#### Issue
I use vtiger in the email configuration as shown, can send and receive mail, but I do not know how to configure the yeticrm, set up a lot of ways are not, can help? Thank your

![snip20170428_2](https://cloud.githubusercontent.com/assets/27992939/25575487/8334671c-2e8a-11e7-8c01-9cdd5c84dec3.jpg)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.0
* Browser name and version:Safari
* Environment name and version:
* Operating System and version:macos

**Comment by sirwinston1** [comment]
Hey,

Were you able to setup the SMTP config correctly and if so did you receive the confirmation email?

**Comment by mariuszkrzaczkowski** [comment]
What error message do you have?
Check logs.

**Comment by copyyour** [comment]
Failed to connect to IMAP

**Comment by kabelo38** [comment]
I get this error trying to connect to my exchange server any help?

[15-May-2017 15:58:31 +0200]: <37tehb7u> IMAP Error: Login failed for ad\kabelo from xxx.xxx.xx.xxx. The krb5 extension is required for GSSAPI authentication in /var/www/development/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_imap.php on line 193 (POST /modules/OSSMail/roundcube/?_task=login&_action=login)

**Comment by mariuszkrzaczkowski** [comment]
Where are your problems in the mail client or in SMTP?

**Comment by kabelo38** [comment]
Trying to log in on roundcube  it used to work well with YT 3.4 i upgraded to YT 4.0 now i get that error

**Comment by kabelo38** [comment]
Don't know downfalls for this action i took. 

I made the following changes to make it work.
$config['imap_auth_type'] = LOGIN;

on config/modules/OSSMail.php
