### ISSUE TITLE
Sync of contacts and calendar with Google/Outlook 365

### ISSUE THREAD

**Issue by liberox** [YetiForceCompany/YetiForceCRM#4389]
Hi,
Are you planning to introduce Google module in YetiForce, similar to that in Vtiger? Or how does the sync work now in YetiForce?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by Protocorewebcreative** [comment]
You have CalDav API with you can using by enabling caldav by removing // from /config/api.php this is a really powerful tool when it works right... @bpabiszczak

**Comment by projakethomas** [comment]
This been in update yet?

**Comment by Gazzxy** [comment]
also wondering about this.. cant seem to get google calendar to accept the yetiforce one at all
