### ISSUE TITLE
Download Library Does Nothing - Module does not contain default language (en_us).

### ISSUE THREAD

**Issue by shieldselectronics** [YetiForceCompany/YetiForceCRM#4390]
![moduleinstall](https://cloud.githubusercontent.com/assets/28299747/25618105/8f3fff2e-2f13-11e7-8c9c-ab0d3107cb2b.gif)

#### Issue
Unable to install:
mPDF
roundcube
PHPExcel
AJAXChat
Gantt

Clicking the download library link does nothing. Downloading and attempting to install the files manually from the repository ends with the following error:

Failed
Module does not contain default language (en_us).

#### Actual Behavior
clicking the download library link does nothing. 

#### Expected Behavior
Installing the modules?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Chrome - Version 58.0.3029.81
* Environment name and version: cPanel & WHM 64.0 (build 19)
* Operating System and version: CENTOS 6.9 x86_64

![moduleinstall](https://cloud.githubusercontent.com/assets/28299747/25618086/7761467e-2f13-11e7-8a2c-19efcad7e75c.gif)

**Comment by liberox** [comment]
Hi,
I have installed 4.00 today and downloading libraries was not a problem. Check if your server meets system requirements.

**Comment by shieldselectronics** [comment]
Server meets all system requirements. The only server library not installed is APCu which is labeled "Optional"

**Comment by MexasPT** [comment]
Same error...

**Comment by MexasPT** [comment]
**Issue**
Unable to install:
roundcube
AJAXChat

Clicking the download library link does nothing. 
If I put ext libraries in right folders and click "Update library" they get deleted.

**Actual Behavior**
clicking the download library link does nothing.

**Expected Behavior**
Installing the modules?

**How to trigger the error**


**Your Environment**
YetiForce Version used: 4.0.288
Browser name and version: Chrome - Version 58.0.3030.97 / Edge 38.14393.1066.0 / IE 11.10.66
Environment name and version: 
Operating System and version: Linux EDT 2017 x86_64

![yeti error](https://cloud.githubusercontent.com/assets/17734465/26307282/af433a56-3eeb-11e7-939a-388571adaf6b.png)

**Comment by gkArvindr** [comment]
did you get the solutions, I too have the same issue

**Comment by shieldselectronics** [comment]
No solution...no response. Never a good sign. Hence the reason we have not implemented this solution for our company yet. And at this rate probably won't.

**Comment by mariuszkrzaczkowski** [comment]
No replies since you have not provided the requested information, please read the article first https://yetiforce.com/en/github/issues/126-issues.html

If we have to help you then you need to give more information:
- full logs
- show the configuration

The problem may be in your server configuration not in CRM.
Manual installation is not performed by the module installer only by copying the file to the appropriate directory

**Comment by shieldselectronics** [comment]
"No replies since you have not provided the requested information, please read the article first https://yetiforce.com/en/github/issues/126-issues.html"

So let me break down this article for anyone reading this. The article is entitled "How to report bugs?"

Section 1) We'll answer questions in English and Polish. If you don't speak one of those two languages we probably won't respond and ignore your question.  For some reason they felt a whole paragraph was required to explain this.

Section 2) Use the latest version. If you're having problems, it's probably you not us. 

Section 3) Is your problem in a development version? It's probably you not us. Is there a problem in the logs? The logs are innumerable and require a Master's Degree in programming to figure out which one is related to your error.. At no point are we going to suggest which log may be relevant nor do we want ALL the logs. To Quote **_" Please provide us only with the information related to the bug. Pasting all logs is unnecessary and will only exceed our response time. Remember that logs contain confidential information about your system, so be careful when pasting the data. "_**
Ie....parse the logs and spend countless hours trying to decipher what they mean in the hopes that you'll see something that probably makes no sense to anyone except the original coders in the vain hope that something will "jump out at you".

4) We'll respond to your question whenever we get around to it and will provide no meaningful system for ACTUALLY submitting bugs or support requests. Nor will we give you any guidance in our rambling article posts about the nature of submitting a bug report or support request. Instead we will post snarky comment replies blaming the user for not following our support protocols that we have in no way defined or published.  Please see our vaguely worded and completely unhelpful guide to understanding error logs called Debugging. In this guide you will find one useful piece of information written thusly: **_"To enable recording of logs to files set true for 'LOG_TO_FILE' [9 line] parameter in the config/debug.php file and then set a level of recording changes LOG_LEVELS. Below are the levels of log4php debugging (from the one that shows the least to the one showing the most):

profile
trace
info
warning
error_**

**Comment by gkArvindr** [comment]
current Ver. 3.4.0
(If you are asking me to install latest Version 4, I tried brand new installation  but it does not create the database schema, All I get is a blank screen during installation menu. ) 

[viewer-debug.log.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/1027611/viewer-debug.log.zip)

Trace : 
Entering getColumnFields(Users) method ...trace
Exiting getColumnFields method ...trace
Language file does not exist, module:ModuleManager ,language: en_uswarning
Start DateTimeField:__convertToUserFormat a:1:{i:0;s:9:"2017-5-24";} | yyyy-mm-ddtrace
End DateTimeField:__convertToUserFormattrace
Entering getColumnFields(Announcements) method ...trace
Exiting getColumnFields method ...trace
Entering CustomView::CustomView::getViewId (Announcements) method ...trace
Entering CustomView::CustomView::getDefaultCvId method ...trace
Exiting CustomView::CustomView::getDefaultCvId method ...trace
Entering isPermittedCustomView(77,List,Announcements) method....trace
Entering when status=0trace
Permission @@@@@@@@@@@@@@@@@@@@@@@@@@@ : yestrace
Exiting isPermittedCustomView(77,List,Announcements) method....trace
Exiting CustomView::CustomView::getViewId method ...trace
Entering CustomView::CustomView::getViewId (Announcements) method ...trace
Entering CustomView::CustomView::getDefaultCvId method ...trace
Exiting CustomView::CustomView::getDefaultCvId method ...trace
Entering isPermittedCustomView(77,List,Announcements) method....trace
Entering when status=0trace
Permission @@@@@@@@@@@@@@@@@@@@@@@@@@@ : yestrace
Exiting isPermittedCustomView(77,List,Announcements) method....trace
Exiting CustomView::CustomView::getViewId method ...trace
Entering CustomView::CustomView::getColumnsListByCvid method ...trace
Exiting CustomView::CustomView::getColumnsListByCvid method ...trace
Entering isPermitted(Notification,DetailView,,) method ...trace
Entering getActionid(DetailView) method ...trace
Exiting getActionid method ... - 4trace
Exiting isPermitted method ...trace
Entering isPermitted(Accounts,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Leads,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Contacts,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Campaigns,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(HelpDesk,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Products,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Documents,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Calendar,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Vendors,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(ServiceContracts,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Services,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Assets,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(ProjectMilestone,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(ProjectTask,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Project,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSTimeControl,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OutsourcedProducts,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSPasswords,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSEmployees,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(PaymentsIn,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(PaymentsOut,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Reservations,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSMailTemplates,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSOutsourcedServices,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSSoldServices,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(HolidaysEntitlement,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(LettersIn,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(LettersOut,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Announcements,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(SSalesProcesses,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(KnowledgeBase,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(IStorages,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(ISTN,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Language file does not exist, module:Settings.LoginHistory ,language: en_uswarning
Language file does not exist, module:Settings.OSSMailView ,language: en_uswarning
Entering isPermitted(Notification,DetailView,,) method ...trace
Entering getActionid(DetailView) method ...trace
Exiting getActionid method ... - 4trace
Exiting isPermitted method ...trace
Entering isPermitted(Accounts,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Leads,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Contacts,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Campaigns,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(HelpDesk,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Products,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Documents,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Calendar,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Vendors,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(ServiceContracts,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Services,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Assets,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(ProjectMilestone,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(ProjectTask,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Project,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSTimeControl,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OutsourcedProducts,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSPasswords,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSEmployees,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(PaymentsIn,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(PaymentsOut,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Reservations,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSMailTemplates,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSOutsourcedServices,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(OSSSoldServices,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(HolidaysEntitlement,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(LettersIn,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(LettersOut,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(Announcements,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(SSalesProcesses,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(KnowledgeBase,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(IStorages,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Entering isPermitted(ISTN,CreateView,,) method ...trace
Entering getActionid(CreateView) method ...trace
Exiting getActionid method ... - 7trace
Exiting isPermitted method ...trace
Language file does not exist, module:Dashboard ,language: en_uswarning
Language file does not exist, module:Webforms ,language: en_uswarning
Language file does not exist, module:Password ,language: en_us

**Comment by shieldselectronics** [comment]
Just to add to this...

> No replies since you have not provided the requested information, please read the article first https://yetiforce.com/en/github/issues/126-issues.html

If we have to help you then you need to give more information:

full logs
show the configuration


If you'll reread my original post you will find that I DID in fact post my server configuration and I dind't post any of the logs because your "Submitting Bugs" article specifically says NOT to post full logs but nowhere does anyone explain which logs we SHOULD post. In FACT, you make the statement that posting full logs will only INCREASE a delay in  response. So which is it?

**Comment by gkArvindr** [comment]
i installed the YetiForceCRM-4.0.0-complete.zip it ends in a blank page, with no errors , 
on refreshing  the screen, i get the below screen - any suggestion 

Server Information
Item	Detail
Hosting Package	Unlimited 
Server Name	gains
cPanel Version	62.0 (build 8)
Apache Version	2.4.25
PHP Version	5.6.30
MySQL Version	5.6.35
Architecture	x86_64
Operating System	linux
Shared IP Address	184.171.164.163
Path to Sendmail	/usr/sbin/sendmail
Path to Perl	/usr/bin/perl
Perl Version	5.10.1
Kernel Version	2.6.32-673.26.1.lve1.4.20.el6.x86_64
Service Information
Service	Details	Status
ftpd	up	
spamd	up	
imap	up	
named	up	
lfd	up	
ipaliases	up	
nscd	up	
dnsadmin	up	
rsyslogd	up	
httpd (2.4.25 (cPanel))	up	
cpsrvd	up	
p0f	up	
mysql (5.6.35)	up	
apache_php_fpm	up	
pop	up	
cpdavd	up	
lmtp	up	
sshd	up	
Server Load	10.82 (24 cpus)	
Memory Used	23.84 %	
Swap	12.91 %	
Disk / (/)	30 %	
![screenshot from 2017-05-26 11-08-09](https://cloud.githubusercontent.com/assets/24363648/26482197/a7425a06-4203-11e7-8334-023a8e27a730.png)

**Comment by mariuszkrzaczkowski** [comment]
@gkArvindr please open a new issue for each new error
@shieldselectronics Does your problem still exist? For the library update to work properly a few conditions must be met:
-crm must have the Internet access
-only latest stable versions are downloaded
-libraries cannot be installed via "Modules - Installation"
-if the crm doesn't have the Internet access you can download a zip and upload it to cache/upload directory, eg. cache/upload/lib_roundcube.zip
-the cache/upload directory must have the write permission and must have the same file owner as crm

If all conditions above are met you should check logs in cache/logs/system.log file. Description how to enable them: https://yetiforce.com/en/developer-documentation/engine/115-debugging.html

The log mechanizm was designed in a way that it doesn't show any personal data, all paths are cut short to only show the path inside crm, and not to show full paths on the server or the domain.
