### ISSUE TITLE
[BUG] [PL] dodawanie usług do cennika

### ISSUE THREAD

**Issue by oidnus** [YetiForceCompany/YetiForceCRM#4391]
#### Issue
Nie można dodać usługi do cennika. Dodanie usługi działa tylko jak tworzymy usługę i z niej tworzymy cennik. Wybierając cennik i później z listy zaznaczam usługi i nie dodaje do cennika. Tak samo jest z produktami. Nie działa to też na waszym demo

#### Your Environment
* YetiForce Version used: 4.0.0
* Browser name and version: chrome
* Operating System and version: linux

**Comment by mariuszkrzaczkowski** [comment]
Nagraj film lub pokaż błąd na zrzutach ekranu
