### ISSUE TITLE
Negative numbers in invoice

### ISSUE THREAD

**Issue by liberox** [YetiForceCompany/YetiForceCRM#4392]
Hi,

Can someone help me to find out how to create Invoice with negative numbers (Credit note)?
And what is the Corrective Invoice for ?

**Comment by mariuszkrzaczkowski** [comment]
look at this

https://gitdeveloper.yetiforce.com/index.php?module=Vtiger&parent=Settings&view=CustomRecordNumbering&block=2&fieldid=22

**Comment by mad99** [comment]
Hi, 
The Link from @mariuszkrzaczkowski ist dead.
How is it possible to use also negative  numbers in invoice/quotes.

Would be great to get a working solution. 
Thanks a lot
![Bildschirmfoto 2019-10-01 um 08 34 14](https://user-images.githubusercontent.com/6169308/65939464-4c35df80-e426-11e9-8fb8-6af869b6d9a2.png)

**Comment by mariuszkrzaczkowski** [comment]
which says in the message that you must log in first

**Comment by mad99** [comment]
Hey @mariuszkrzaczkowski 
Thank you for help.
But if I have logged in, (changed to german) there is a screen for contacts and to set prefixes for different modules.

**Would be great to get the point to where we can choose to switch between «only positive value for invoice/quotes allowed»|«also negative values for invoice allowed»?**
![Bildschirmfoto 2019-10-01 um 08 45 59](https://user-images.githubusercontent.com/6169308/65940239-4fca6600-e428-11e9-9430-74ffdbb30718.png)

**Comment by mad99** [comment]
@mariuszkrzaczkowski,
is negative value really possible? I looked in the code and there is a check about 
$CURRENCY_PATTERN_THOUSAND_GROUPING
But also with change in database to -123...
I can't choose this in user-setting.
And so I can't use negative value ...

What do I wrong?
Thanks anyway
