### ISSUE TITLE
Calendar sharing outside of yeti

### ISSUE THREAD

**Issue by jbmcclain** [YetiForceCompany/YetiForceCRM#4393]
#### Issue
Any way to create an ics file so outlook or any other calander applications can pull the data as it is being changed in Yeti?

Looking to have custom types of events to pick from

#### Expected Behavior
to be able to share a calander outside of yeti and be updated as changes are made

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: firefox and chrome
* Environment name and version: xampp
* Operating System and version: 2008R2

**Comment by nic86** [comment]
software configuration > Integration > DAV Applications > DAV keys

- click on button "add key" and create your user login and key
- add caldav account in your preferred calendar (use login and key created before)

Examples of DAV server connection configuration for different apps and systems:
DAVdroid
Address: https://gitdeveloper.yetiforce.com/api/dav.php
Preventive authorization NO
Thunderbird CalDAV
Address: https://gitdeveloper.yetiforce.com/api/dav.php/calendars/demo/YFCalendar/
iOS
Address: http://gitdeveloper.yetiforce.com/api/dav.php/principals/demo/ 
For SSL connections: 
http://gitdeveloper.yetiforce.com:443/api/dav.php/principals/demo/

**Comment by jbmcclain** [comment]
Thank you when I try to look that the dav server connections. i get the 401 page
![dav](https://cloud.githubusercontent.com/assets/1903662/25704844/1d83bcee-30a9-11e7-8b84-2c85d3c06553.JPG)

**Comment by nic86** [comment]
set to true [$enableBrowser](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/api.php#L19)

**Comment by jbmcclain** [comment]
Thanks! so close I think have you seen issues when logging in with Active directory?

**Comment by jbmcclain** [comment]
is there any way to make it so it does not need authentication? I think it is having issues with authenticating off of active directory.  Thank you for your help! it is greatly appreciated!

**Comment by nic86** [comment]
comment [these two lines](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/api/dav.php#L59-L60) for disables ACL and Authentication plugins on the [sabreDav server.](http://sabre.io/dav/plugins/)

**Comment by KatarzynaUlichnowska** [comment]
If you do that, you will make your calendar visible to everyone in the world. Each person, who knows the link, will have full access and will be able to read/modify/delete events. We do not recommend that as it hasn't been tested, so we cannot guarantee that it will work properly.

**Comment by Protocore-Hosting** [comment]
Hi guys, I love your work... but I've set up the caldav with outlook but yeti is not creating the ics file when a todo or event is created, is there a cron job for this?

Thanks

**Comment by jbmcclain** [comment]
you need to set your cron for yetiforce its self.  then go to to automation and cron. there you can set your time frequency.

**Comment by jbmcclain** [comment]
Does this caldav require a 3rd party caldav plugin to work with outlook?  I  know I could not get it to work till I used a plugin for caldav in outlook and when it does sync it does have an issue with multi-day events

**Comment by Protocore-Hosting** [comment]
Hi JBMCCLAIN 

I have installed CalDav sync for this [https://sourceforge.net/projects/outlookcaldavsynchronizer/](https://sourceforge.net/projects/outlookcaldavsynchronizer/)

But when I do it two way all my elements go to the API from outlook but not from yeti to out?

Why?

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
