### ISSUE TITLE
Urgent Invoice Wrong label Bills 

### ISSUE THREAD

**Issue by CobaJashi** [YetiForceCompany/YetiForceCRM#4394]
Hello, 

We are just testing the bills/invoice (German). Version 4. We add $ (custom: ProductsTableNew) $ to the PDF Invoice and get incorrect labels. Where and how can we change these and / or what is the reason for this? In the management language everything looks good

![rechnung](https://cloud.githubusercontent.com/assets/20491699/25673065/61b3682e-3036-11e7-99d3-3a0b14461a36.png)

Thank you in advance :)

**Comment by worldwidehigh** [comment]
Hallo,

ich antworte mal auf Deutsch. Ich hatte dasselbe Problem. Im Modul PDF - im "Bearbeiten Modus", kann man unter Dokument Einstellungen die Sprache wählen. Ich hoffe das Hilft weiter.

**Comment by CobaJashi** [comment]
Ich danke dir vielmals. Wir hatten schon alle Datenbankeinträge und den Code gescannt und nichts gefunden :1st_place_medal: 

Einen schönen Tag aus Nürnberg

**Comment by worldwidehigh** [comment]
Gerne kein Problem
