### ISSUE TITLE
Workflow Expression ERROR [BUG]

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4395]
#### Issue

Workflow update no work in 4.0 Version, for example when add 7 days to current date and update Due Date.
#### Actual Behavior

![untitled](https://cloud.githubusercontent.com/assets/3030997/25721991/d84f5ab2-30e8-11e7-9e9f-e4d001692f57.gif)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0 Stable
* Browser name and version: Chrome and Firefox latest version
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Does the bug exist on the development version?
