### ISSUE TITLE
Invoice Copy address From [QUESTION]

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4396]
Is possible add a new Field or remove in "Copy address from" Account button?
![image](https://cloud.githubusercontent.com/assets/3030997/25724142/3be8bc8c-30f1-11e7-8970-caa4faa9587c.png)

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/layouts/basic/modules/Vtiger/BlockHeader.tpl
You can remove in this file
