### ISSUE TITLE
Błąd skrzynki pocztowej po włączeniu podglądu wiadomości

### ISSUE THREAD

**Issue by cedeka78** [YetiForceCompany/YetiForceCRM#4397]
Po zaznaczeniu w ustawieniach poczty Pokaż podgląd wiadomości w folderze Odebrane w skrzynce pocztowej nie wyświetlają się żadne wiadomości. Wyłączenie podglądu przywraca widok wiadomości.
Błąd wywołany w YetiForce 4.0.0. w wersji testowej zamieszczonej na stronie yetiforce.com

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Czy problem nadal występuje w nowej wersji?

**Comment by cedeka78** [comment]
Witam, 

problem nadal występuje. 

Łatwo go wywołać, chociażby w demo zamieszczonym na Państwa stronie ver.
4.2.134 

https://gitdeveloper.yetiforce.com/index.php 

Wchodzimy w ustawienia roundcube, Widok skrzynki pocztowej, zaznaczamy
Pokaż podgląd wiadomości i już jest problem, gdyż 

Jak przejdziemy do skrzynki odbiorczej, to nie widać żadnych wiadomości.


Pozdrawiam, 

Tomasz Kołodziej

W dniu 2017-08-08 09:09, Mariusz Krzaczkowski napisał(a):

> Czy problem nadal występuje w nowej wersji? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/YetiForceCompany/YetiForceCRM/issues/4397#issuecomment-320870196
[2]
