### ISSUE TITLE
LEADs import not storing mapping

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#44]
As the title says, doing several LEADS imports and saving the mapping of the fields adds a name to the mapping listing but selecting the mapping does not fill in the fields names the next time you use it.

Tested with RC01

**Comment by rskrzypczak** [comment]
Hello, we haven't found any errors when doing templates of mapping during the import of records. Please describe this bug in detail. Screenshot would be helpful.
