### ISSUE TITLE
Imported Contacts and Projects are not relating to existing Accounts

### ISSUE THREAD

**Issue by notmydayjob** [YetiForceCompany/YetiForceCRM#4401]
#### Issue
I have configured a test environment for Yetiforce. The application seems to be functioning properly. I can manually create Accounts and related Contacts and Projects. The next step was to import a test batch of existing Accounts, these appeared to be created correctly. Next I tried to import some contacts related to those accounts, I mapped the appropriate fields, including the "member of" field mapped to the organization name previously imported. The import proceeds without error however the Contacts are created without any relationship to the Account. Likewise when I try to import projects that are related to an Account not relationship is created.

#### Actual Behavior
Imported Contacts are not related to existing Accounts

#### Expected Behavior
Contacts should be correctly mapped to existing Accounts

#### How to trigger the error

1. Import Accounts
2. Map and import Contacts

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Chrome
* Environment name and version: Php 7.0.15-0ubuntu0.16.04.4
* Operating System and version: Ubuntu 0.16.04.4

**Comment by sirwinston1** [comment]
I believe I got this to work by updating the import coding with the dev coding and it worked for the relations fields.  it still didnt fix the assigned to field though.

**Comment by notmydayjob** [comment]
Thanks, @sirwinston1 I reinstalled using the dev code and my issue appears to be resolved.

**Comment by vovpff** [comment]
@notmydayjob what dev version you use?

**Comment by notmydayjob** [comment]
I downloaded the code from the Dev branch 2 days ago (just downloaded the zip). I'm new to using Git and kind of clueless so I'm sorry I can't give you a better answer.

**Comment by notmydayjob** [comment]
According to the version.php

'appVersion' => '4.0.238',
	'patchVersion' => '2017.05.09',

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/3a842b63d5540b57c4f5fb9d39b5ce23397e37ab
