### ISSUE TITLE
Question: How to update Actual sale in module Opportunities?

### ISSUE THREAD

**Issue by martinprog7** [YetiForceCompany/YetiForceCRM#4402]
In the Opportunities module, how do I update the "Actual Sales" field?
The field can not be edited manually, unlike the Estimated value field.
I tried to create a Sales Order, but the "Actual Sales" value of the Opportunities did not change.
Is the "Actual Sales" field auto-filled? Thank you

**Comment by konadrian** [comment]
The field is calculated automatically, but its configured for each client separately. Depending on what we calculate the value of. We are planning to automate that field, and calculate it based on invoices.

**Comment by PDMeira** [comment]
how can we change the calculation formula?

**Comment by yusronhilmy** [comment]
Hi @martinprog7 : you can make actual_sale field editable by update vtiger_field table :
update vtiger_field set displaytype = 1 where columnname = 'actual_sale';

Hope this helps.
