### ISSUE TITLE
Pricebooks is broken

### ISSUE THREAD

**Issue by merckaa** [YetiForceCompany/YetiForceCRM#4404]
#### Issue
Cannot add any product or service in price books
Tested in my server and every hosted branch in yetforce.com

#### Actual Behavior
not adding any product or service at price books

#### Expected Behavior
To be adding it

#### How to trigger the error
![yetiforcepricebooks](https://cloud.githubusercontent.com/assets/15110035/25870795/cbf5525c-34db-11e7-8b99-aa3225d00b28.gif)

#### Your Environment
Yetiforce 4.0.0
Shared Host
Windows 10 with Chrome

**Comment by TomaszQr** [comment]
In current version, it work properly
