### ISSUE TITLE
Pop up System Warning

### ISSUE THREAD

**Issue by frankhzp** [YetiForceCompany/YetiForceCRM#4408]
#### Issue

everytime I login into the system , when go to System configuration , the system warning pop up always come out .

#### Actual Behavior

![issue](https://cloud.githubusercontent.com/assets/28562781/25927068/cf638ae4-3625-11e7-92d6-371039a1963f.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: V4.0.0
* Browser name and version:  Chrome 60
* Environment name and version:  Xampp 
* Operating System and version: Window 10    1703

**Comment by vovpff** [comment]
@frankhzp ignore them here: https://gitdeveloper.yetiforce.com/index.php?module=Vtiger&parent=Settings&view=Index
