### ISSUE TITLE
Upgrading to 4.0 error displayed

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4409]
#### Issue
when trying to upgrade to 4.0 from 3.4.1427 I get an error

#### Actual Behavior
This is the error `Warning: rmdir(cache/updates/EmailTemplates): No such file or directory in /var/www/html/yetiforce/cache/updates/init2.php on line 1032

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users' in 'field list' in /var/www/html/yetiforce/vendor/yii/db/Command.php:231 Stack trace: #0 /var/www/html/yetiforce/vendor/yii/db/Command.php(231): PDO->prepare('INSERT INTO `vt...') #1 /var/www/html/yetiforce/vendor/yii/db/Command.php(844): yii\db\Command->prepare(false) #2 /var/www/html/yetiforce/modules/Vtiger/models/Record.php(391): yii\db\Command->execute() #3 /var/www/html/yetiforce/modules/Vtiger/models/Module.php(230): Vtiger_Record_Model->saveToDb() #4 /var/www/html/yetiforce/modules/Vtiger/models/Record.php(370): Vtiger_Module_Model->saveRecord(Object(Vtiger_Record_Model)) #5 /var/www/html/yetiforce/cache/updates/init2.php(1091): Vtiger_Record_Model->save() #6 /var/www/html/yetiforce/cache/updates/init2.php(1057): YetiForceUpdate2->addRec(Array) #7 /var/www/html/yetiforce/cache/updates/init2.php(213): YetiForceUpdate2->addRecords('EmailTemplates') #8 /var/www/html/yetiforce/cache/updates/init2.php(6): YetiForceUpdate2 in /var/www/html/yetiforce/vendor/yii/db/Command.php on line 236`

#### Expected Behavior
Upgrade without issues

#### How to trigger the error
Update normal way

#### Your Environment
Ubunutu 16.4 running all versions needed for the system to work as per https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
* YetiForce Version used: 3.4.1427
* Browser name and version: Chrome, FF, Opera, IE, Edge
* Environment name and version: Ubunutu 16.4, php 5.6 and php 7
* Operating System and version: Windows 7 64bit pro

**Comment by alextovey** [comment]
@paula-w @bpabiszczak

**Comment by skramanzia** [comment]
@alextovey Whats is the version do you use?, I use v4 and I had no problems.

https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x/3.4.0_to_4.0.0/zip

**Comment by alextovey** [comment]
Not sure how do i find which version i'm using.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/version.php

**Comment by alextovey** [comment]
i;m using 3.4.1427

**Comment by KatarzynaUlichnowska** [comment]
We have migrated dozens of systems. If your problem still exists, it requires an individual approach. Unfortunately, individual support isn't free.
