### ISSUE TITLE
Workflow subtraction

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4411]
#### Issue

When I do a subtraction through a workflow, the result is incorrect

#### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/3030997/25956755/f5728e7a-3642-11e7-98fb-f508b313131c.png)

=> 50.000,00 - 3.500,00 - 10,00

The result of the subtraction is field "Rentabilidad"

Workflow
![image](https://cloud.githubusercontent.com/assets/3030997/25956815/20bea8c0-3643-11e7-849a-53fea3f7b245.png)

#### Expected Behavior

Restabilidad = $46.490,00

#### Your Environment

* YetiForce Version used: 4.0 Stable
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by TomaszQr** [comment]
I trigger this bug in version 4.0 but in developer version it work properly.
We recommend using brackets in expression, for this case: (estimated - comm_op) - thirdopp
