### ISSUE TITLE
Module Sequence Numbers mask

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#4413]
#### Issue

Hi, I would like to format our module sequence numbers appereance mask to  : CU1705-0001 (I am using Accounts modules, as an example).  In my Module Sequence Numbering, in Use Prefix field I have the following CU{{YY}}{{MM}}-.

#### Actual Behavior

CU1705-1

#### Expected Behavior

CU1705-0001

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4.0 (from Softaculous) 
* Browser name and version: Chrome and Safari
* Environment name and version: 
* Operating System and version: MACOS Sierra

**Comment by ezbank** [comment]
#3697

**Comment by nkzach** [comment]
I use 10001 instead of 0001.
