### ISSUE TITLE
REST API - mobile platform

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#4414]
Does Yeti's planning to do some changes in API? 
Is current API 100% inherited from vtiger without amendments to the code?
Considering writing some mobile app, so seeking for any possible scenarios.
By the way, anybody here connected iOS or Android app with Yetiforce yet?

**Comment by umbz** [comment]
I colloqui this 3d

**Comment by umbz** [comment]
I follow this 3D

**Comment by mariuszkrzaczkowski** [comment]
> Does Yeti's planning to do some changes in API?
New API has been created
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/api
https://github.com/YetiForceCompany/YetiForceCRM/issues/4023
https://github.com/YetiForceCompany/YetiForceCRM/issues/4154

> Is current API 100% inherited from vtiger without amendments to the code?
100% new code and functionality

> Considering writing some mobile app, so seeking for any possible scenarios.
> By the way, anybody here connected iOS or Android app with Yetiforce yet?
Yes https://yetiforce.com/images/64-thickbox_default.jpg
