### ISSUE TITLE
Manual trigger workflow hung screen

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4415]
#### Issue
While creating workflow with "manual trigger by the user"  system stop responding.

#### How to trigger the error

Create new workflow with Manual trigger by the user, and try to pass over condition screen (no conditions provided) 
Triggered on "today's" dev test application

Actually it hanging on any form of triggering

**Comment by mariuszkrzaczkowski** [comment]
Does the problem still exist in the newest version?
