### ISSUE TITLE
Ticket Closure

### ISSUE THREAD

**Issue by scsikid** [YetiForceCompany/YetiForceCRM#4417]
I'm new to yetiforce, I've used vitger crm. I'm looking for help with two things.
1. How can I manually add time to a trouble ticket?
2. How do I close a trouble ticket? Or is "Status: To close" meant to be "closed"

I have looked in the documentation and read as much as I could online to find answers but can't seem to find anything specific to what I've mentioned.

**Comment by konadrian** [comment]
Here you can add a new field to module
https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&block=2&fieldid=33
here you can select which values mean that a ticket is closed
https://gitdeveloper.yetiforce.com/index.php?module=SupportProcesses&view=Index&parent=Settings&block=6&fieldid=80
