### ISSUE TITLE
FL_IS_PRIVATE check box

### ISSUE THREAD

**Issue by ousidahou** [YetiForceCompany/YetiForceCRM#4419]
hello,

is there any way to hide or delete FL_IS_PRIVATE check box on every modules??
we don't need this option on our company

thank you again for your work.

**Comment by vovpff** [comment]
@ousidahou try to made them 'hidden' for every role

**Comment by ousidahou** [comment]
thank you @vovpff I'm going to try it on a demo session.

**Comment by ousidahou** [comment]
hello again sorry, no way I didn't find it we can't hide it on role!!!


can you please give us more information ????

**Comment by vovpff** [comment]
@ousidahou sorry. My mistake. You can hide this field thru Profiles nor Roles. Example here https://gitdeveloper.yetiforce.com/index.php?module=Profiles&parent=Settings&view=List&block=1&fieldid=3
Click to edit any profile and make invisible private field as on picture (red arrow):
![image](https://cloud.githubusercontent.com/assets/8545791/26057775/a6a58ba0-3983-11e7-9a3c-58886ce05d7b.png)

**Comment by ousidahou** [comment]
thank you so much for your help

**Comment by vovpff** [comment]
@ousidahou no problem!
