### ISSUE TITLE
Module does not contain default language (en_us) installing Hotfix 3.4.0

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#4421]
#### Issue

Trying to install hotfix 3.4.0 to solve a problem with roundup configuration. When updating the round cube configuration form, says that form update but it comes again to default values.

I downloaded the hotfix zip from GitHub and try to import it from Software configuration > Standard modules > Modules – Installation > Import

#### Actual Behavior

Error message: 

dUnzip2: File 'manifest.xml' is not compressed in the zip.
dUnzip2: File 'manifest.xml' is not compressed in the zip.

Failed
Module does not contain default language (en_us).

![module_manager_e_manifest_xml](https://cloud.githubusercontent.com/assets/12361370/26062224/23dadb86-3982-11e7-9b2c-3e90a9a6f239.png)

#### Expected Behavior

Installed successfully 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4.0 
* Browser name and version: Safari and Chrome 
* Environment name and version: 
* Operating System and version: MAC OS Sierra

**Comment by mariuszkrzaczkowski** [comment]
Where did you download the file?

https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/3.4.0
