### ISSUE TITLE
Updates Section is duplicating results

### ISSUE THREAD

**Issue by sirwinston1** [YetiForceCompany/YetiForceCRM#4422]
#### Issue

The updates view is duplicating the results
![dup](https://cloud.githubusercontent.com/assets/6587713/26072443/c04343e2-3968-11e7-8c85-d325593dfe7e.PNG)

#### Your Environment

* YetiForce Version used: ver. 4.0.0
* Browser name and version: Google Chrome
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
This error not occur in current version
