### ISSUE TITLE
Issues with CalDav Synchronizer - Specified issues below

### ISSUE THREAD

**Issue by projakethomas** [YetiForceCompany/YetiForceCRM#4423]
Hi All 

#### Issue
I have enabled CalDAV module inside of config/api.php

#### Actual Behavior
but the ICS file are creative inside of  /api/dav.php

#### How to trigger the error

1. Log in caldav nothing
2. Log in Yetiforce shell I enable debug

#### Your Environment
But not inside of yeti any reason for this guys?

**Comment by Protocorewebcreative** [comment]
No response yet?

**Comment by mariuszkrzaczkowski** [comment]
We need more details how to trigger the error.
Can you try to trigger it on gitdev?

**Comment by projakethomas** [comment]
This been in update yet?

**Comment by paula-w** [comment]
The issue was closed due to no response to our question from Aug 8
