### ISSUE TITLE
WorkFlow Scheduled not work

### ISSUE THREAD

**Issue by pippomix70** [YetiForceCompany/YetiForceCRM#4424]
Issue
I have built a workflow for updating a field, with execution option to create / modify the workflow works correctly but with scheduled options the workflow does not work.

Actual Behavior
system.log:
0 vendor/yii/db/Command.php (877)  >>  yii\BaseYii->info('SELECT `vtiger_activity`.`activityid` AS `id` FROM `vtiger_activity` INNER JOIN `vtiger_crmentity` ON vtiger_activity.activityid = vtiger_crmentity.crmid LEFT JOIN `vtiger_activity` `vtiger_activityfollowup` ON vtiger_activity.followup = vtiger_activityfollowup.activityid WHERE ((vtiger_crmentity.deleted=0) AND (((`vtiger_activity`.`priority`<>\'Non Pubblicato\') AND (`vtiger_activityfollowup`.`location`=\'get_date(\\\'tomorrow\\\')\') AND (`vtiger_activity`.`activitytype`<>\'Task\')))) AND (`vtiger_crmentity`.`users` LIKE \'%,1,%\')','yii\\db\\Command::query')

* YetiForce Version used: 4.0.0 - 3.4.0 - 3.3.0
* Browser name and version: firefox
* Environment name and version:PHP7
* Operating System and version: Ubuntu Server 16.04

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
