### ISSUE TITLE
SQL Error - Ambiguous Fields

### ISSUE THREAD

**Issue by sirwinston1** [YetiForceCompany/YetiForceCRM#4426]
#### Issue
When trying to add a Partner record to a lead I get the following error:

![sqlerror](https://cloud.githubusercontent.com/assets/6587713/26166631/566f8cb6-3af1-11e7-9daa-6202e6437a2c.PNG)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by sirwinston1** [comment]
Issue was caused by me adding two fields to the search configuration that contained duplicate information. I removed my created filed and then updated the labels and waited for cron to run.  Now everything works like it should.

I will keep this open in case devs want to look further into this to build in a prevention

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
