### ISSUE TITLE
fresh yetiforce 4.0 Install : Invalid username or password

### ISSUE THREAD

**Issue by ousidahou** [YetiForceCompany/YetiForceCRM#4427]
After completing the installation, automatically redirected to link http://abc.xyz/index.php?module=Users&view=Login&error=1.
Then, when you enter the account to log in, an error message appears on the wrong account information.
"Invalid username or password."

how we can resolve this one???

**Comment by ousidahou** [comment]
this is my configuration for .htaccess


`RedirectMatch 403 (?i).*\.log$

<IfModule mod_autoindex.c>
	Options -Indexes
</ifModule>
########################
<IfModule mod_rewrite.c>
	Options +FollowSymLinks
	RewriteEngine On
	RewriteRule ^favicon.ico layouts/basic/skins/images/favicon.ico [L,NC]
	RewriteRule ^api/webservice/(.*)/(.*)/(.*)$ api/webservice.php?module=$1&action=$2&record=$3 [QSA,NC,L]
	RewriteRule ^api/webservice/(.*)/(.*)$ api/webservice.php?module=$1&action=$2 [QSA,NC,L]
	RewriteRule ^api/webservice/(.*)$ api/webservice.php?module=$1 [QSA,NC,L]

	RewriteRule ^\.well-known/carddav /api/dav.php/addressbooks/ [R]
	RewriteRule ^\.well-known/caldav /api/dav.php/calendars/ [R]
	RewriteRule /.well-known/carddav /api/dav.php/addressbooks/ [R,L]
	RewriteRule /.well-known/caldav /api/dav.php/calendars/ [R,L]
	RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
</ifModule>
<IfModule mod_php5.c>
	php_flag	log_errors					Off
	php_flag	display_errors				Off
	php_value	memory_limit				512M
	php_flag	output_buffering			On
	php_flag    zlib.output_compression		Off
	php_flag	file_uploads				On

	php_value	max_execution_time			600
	php_value	max_input_time				600
	php_value default_socket_timeout 600
	php_value log_errors on
	php_value post_max_size 50M
	php_value max_input_vars 10000
	php_value upload_max_filesize 100M
	php_value session.cookie_httponly	on

	php_flag	magic_quotes_gpc			Off
	php_flag	magic_quotes_runtime        Off

	php_value	suhosin.request.max_vars	5000
	php_value	suhosin.post.max_vars		5000
	php_flag	suhosin.session.encrypt		Off

	php_flag	session.auto_start			Off
	# 86400 = 3600*24
	php_value	session.gc_maxlifetime		86400
	# 1440 = 60*24
	php_value	session.cache_expire		1440
	php_value	session.gc_divisor			500
	php_value	session.gc_probability		1
	php_value	session.save_path			cache/session
	php_value	error_log					cache/logs/phpError.log
</IfModule>
<IfModule fcgid_module.c>
	FcgidIOTimeout 600
	FcgidConnectTimeout 600
	FcgidBusyTimeout 600
	FcgidIdleTimeout 600
</IfModule>
########################
# <FilesMatch "\.(inc|php|php3|php4|php5|php6|phtml|phps)$">
# AddHandler x-httpd-php56 .inc .php .php3 .php4 .php5 .php6 .phtml
# </FilesMatch>
`

**Comment by rskrzypczak** [comment]
Do you have mysqlnd?

**Comment by ousidahou** [comment]
hello again, 

yes it's activated 
![capture d ecran 2017-05-19 a 10 07 19](https://cloud.githubusercontent.com/assets/22946462/26241000/03f78480-3c7b-11e7-998e-80f946a76606.png)

**Comment by ousidahou** [comment]
![capture d ecran 2017-05-19 a 10 08 56](https://cloud.githubusercontent.com/assets/22946462/26241046/37124f76-3c7b-11e7-84b2-e23db8b8e316.png)

**Comment by ousidahou** [comment]
???? any other idea ???

**Comment by mariuszkrzaczkowski** [comment]
Show configuration verification in crm?

**Comment by mariuszkrzaczkowski** [comment]
turn on  nd_mysql and nd_pdo_mysql

**Comment by ousidahou** [comment]
hi thanks for your support again;

there is a pop up showing a conflict when I try to activate nd_mysql and nd_pdo_mysql
i will turn on juste nd_mysql

**Comment by mariuszkrzaczkowski** [comment]
Turn off all and then turn on

**Comment by ousidahou** [comment]
thank you it work now by activating nd_pdo_mysql thank you #mariuszkrzaczkowski for your help.

I like the new version off yetiforce

**Comment by rafamacedo** [comment]
Hello, how are you?

I read all the history and tried to do the same, but my error message is different. Need help...

![2017-05-31_02h19_28](https://cloud.githubusercontent.com/assets/26890198/26616828/d4367928-45a7-11e7-9767-d56861919891.png)

**Comment by rafamacedo** [comment]
Just to complement the information I'm running PHP 5.6 because I still have WHMCS running on this domain and it does not run with 7.0.

![image](https://cloud.githubusercontent.com/assets/26890198/26616862/0f38daf2-45a8-11e7-802f-ae35fbaaa481.png)
