### ISSUE TITLE
[BUG] Cant create report

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4429]
v4.0.287
![screenshot 4](https://cloud.githubusercontent.com/assets/19627226/26239232/612131b2-3ca6-11e7-9c21-2f9c484e6fc4.png)

**Comment by mariuszkrzaczkowski** [comment]
You need a better description of how to call the error what parameters are reported. Describe more accurately

**Comment by ezbank** [comment]
@mariuszkrzaczkowski hi
![error](https://cloud.githubusercontent.com/assets/19627226/26750460/40f2658e-484d-11e7-876c-117374f083d6.gif)

**Comment by TomaszQr** [comment]
Fixed via https://github.com/YetiForceCompany/YetiForceCRM/commit/42a9b67398a539521b50205953b8f999e60dd3d5
