### ISSUE TITLE
how we can hide products & Services in lead module

### ISSUE THREAD

**Issue by ousidahou** [YetiForceCompany/YetiForceCRM#4430]
![capture d ecran 2017-05-19 a 11 35 37](https://cloud.githubusercontent.com/assets/22946462/26244441/8d11dfac-3c87-11e7-9c0c-0c87b9e42fae.png)

**Comment by sirwinston1** [comment]
I am not sure about the unattended consequences of going this route but here is a solution for you.  
in   config/developer.php  edit 'CHANGE_RELATIONS' to be to true.   You can then go into the module-relations screen and delete or add relations.

**Comment by ousidahou** [comment]
Thnks i will try it in a test version

**Comment by mariuszkrzaczkowski** [comment]
Try changing this parameter
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/Accounts.php#L19
