### ISSUE TITLE
Download library fails - Roundcube and AjaxChat

### ISSUE THREAD

**Issue by MexasPT** [YetiForceCompany/YetiForceCRM#4434]
**Issue**
Unable to install:
roundcube
AJAXChat

Clicking the download library link does nothing. 
If I put ext libraries in right folders and click "Update library" they get deleted.

**Actual Behavior**
clicking the download library link does nothing.

**Expected Behavior**
Installing the modules?

**How to trigger the error**

**Your Environment**
YetiForce Version used: 4.0.288
Browser name and version: Chrome - Version 58.0.3030.97 / Edge 38.14393.1066.0 / IE 11.10.66
Environment name and version: 
Operating System and version: Linux EDT 2017 x86_64

![yeti error](https://cloud.githubusercontent.com/assets/17734465/26307282/af433a56-3eeb-11e7-939a-388571adaf6b.png)

Help me please.

**Comment by sirwinston1** [comment]
Try going into the file config/developer.php and changing 'MISSING_LIBRARY_DEV_MODE' to true

**Comment by MexasPT** [comment]
Problem solved!

Thanks sirwinston1 !

**Comment by MexasPT** [comment]
The problem is not solved.
Although it indicates that I have the libraries, it causes an error when opening the chat.

![erro chat_roundcube](https://cloud.githubusercontent.com/assets/17734465/26362156/0ed5ad84-3fd5-11e7-9379-e23ebd4365e0.jpg)

**Comment by sirwinston1** [comment]
Check the permissions on your files and folders for the chat. Make sure
files are set to 644 and folders to 755

**Comment by MexasPT** [comment]
Done... but the problem remains.
The files are all there... :(

**Comment by sirwinston1** [comment]
I see you are on version 4.0.288.  I had problems with the chat when I would try to move to the dev builds so I just went back to 4.0.0 until they release the newest update.  

Did it log any errors?

**Comment by gkArvindr** [comment]
I have almost the same problem 

![screenshot from 2017-05-24 23-15-22](https://cloud.githubusercontent.com/assets/24363648/26417519/0efd433c-40d7-11e7-9932-fc41b036c430.png)

**Comment by kabelo38** [comment]
rename folders and download again should work.

**Comment by gkArvindr** [comment]
Why do you want me to rename folders on a plain vanilla installation

**Comment by lcuevastodoit** [comment]
Hi, I have a similar problem, in mi Yeti ver 4.0.475 there is not AjaxChat module option even  changing 'MISSING_LIBRARY_DEV_MODE' to true

**Comment by bpabiszczak** [comment]
Downloading library works only with stable version. For other versions, manually upload the appropriate version of the library.
