### ISSUE TITLE
Random deletion of items

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4435]
Hi All, I'm running 3.4.0 on ubuntu 16.04 running php 7.0.

I have all the items installed which the system ask's optional and required. However the system keeps deleting files from the documents folder, for instance, we are missing lots of .docx files and .pdf. No error logs of them being deleted but they keep disappearing we are now missing 132 files from the past three months.

I'm the only one with admin access and ssh access to the server.

**Comment by mariuszkrzaczkowski** [comment]
This requires a programmer's analysis
