### ISSUE TITLE
Unable to Upgrade from v3.4.1427 to version=4.0.0

### ISSUE THREAD

**Issue by aramxalil** [YetiForceCompany/YetiForceCRM#4437]
Dear Support Team When I want to upgrade from V3.4.1427 to version=4.0.0
I get Bellow errors 
![v4](https://cloud.githubusercontent.com/assets/24459816/26355232/8e5b002c-3fd0-11e7-9408-08af2b5ca412.JPG)

in the cpanel page (error logs) it shows this below error
[2017-05-23 07:35:29]: error: file is writable by others: (/home/public_html/cache/updates/init2.php)

#### Your Environment

* YetiForce Version used:  V3.4.1427
* Browser name and version: google chrome v57.0.2987.110
* Environment name and version: softaclus via siteground.com 
* Operating System and version: php version 7.1

**Comment by mariuszkrzaczkowski** [comment]
Do you have the correct permissions on the directories? Are all system requirements correct?

**Comment by aramxalil** [comment]
Yes @mariuszkrzaczkowski  the folder's Permission is above 755 and the php version is 7.1 
, also after updating from 3.4 to V3.4.1427 no longer able to login, i think the update  disconnected application from the DB

**Comment by mariuszkrzaczkowski** [comment]
Show server configuration
https://github.com/YetiForceCompany/YetiForceScripts/blob/master/TestRequirements/TestRequirements.php

**Comment by alextovey** [comment]
i get the same issue, if your not running v4 on 3.4.1427 it will die! i've found no way of migrating safely to version 4.0 even trying to move the database it still wig's out :(

**Comment by mariuszkrzaczkowski** [comment]
You have a problem with permissions you need to show the problem of the administrators of your server without problem it will fix it

**Comment by alextovey** [comment]
Nope, permissions are correct and still the same issue.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/administrator-documentation/errors/227-apache-500-internal-server-error-2.html
