### ISSUE TITLE
create manual conversion from leads module to accounts module

### ISSUE THREAD

**Issue by ousidahou** [YetiForceCompany/YetiForceCRM#4438]
how to create manual conversion from leads module to accounts module

**Comment by ousidahou** [comment]
i don t get convert button when change lead statut

**Comment by vovpff** [comment]
@ousidahou you need to add some mappings here https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95 or here https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Leads&view=MappingDetail&block=2&fieldid=87
