### ISSUE TITLE
Change Table List View - Products

### ISSUE THREAD

**Issue by visitekasia** [YetiForceCompany/YetiForceCRM#4439]
Hello,
How can I change the table list on any modules, like in products list, I want to change which fields to show on the list.
Thank you.

![image](https://cloud.githubusercontent.com/assets/28915574/26387591/11b5b342-4079-11e7-8d8d-764fc82209d6.png)

Regards,
Nando

**Comment by skramanzia** [comment]
Check this module --> https://gitdeveloper.yetiforce.com/index.php?module=CustomView&view=Index&parent=Settings&sourceModule=14

**Comment by visitekasia** [comment]
@skramanzia 
Thank you so much!!!
This is exactly what I was looking for...
Didn't realize that menu is placed under filter configuration.

> Enter "System Settings"
> Move over to "Search and filters"
> And choose "Filters - Configuration"

![table list edit](https://cloud.githubusercontent.com/assets/28915574/26418877/0a051e70-40e8-11e7-8624-83969e7f571c.jpg)
