### ISSUE TITLE
Integrate New API with external Services

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#4442]
#### Issue

Having troubles signing in using new API, can someone please point me to the right direction

#### Actual Behavior

![screenshot from 2017-05-24 14-14-06](https://cloud.githubusercontent.com/assets/5912376/26403549/fa20dc6e-408e-11e7-9698-93d41ff8adc8.png)

![screenshot from 2017-05-24 14-16-07222222222](https://cloud.githubusercontent.com/assets/5912376/26403558/ff063e7c-408e-11e7-9922-0b580b25111d.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: 
* Environment name and version:
* Operating System and version: Ubuntu 16.10

**Comment by mariuszkrzaczkowski** [comment]
Run the logs and verify that you entered the data correctly. You can add another user and check on it

**Comment by kabelo38** [comment]
Tried new user and gave it another try and got this in my logs

cache/logs/webserviceErrors.log
============ Error exception ====== 2017-06-05 16:13:50 ======
code: 401 | message: Invalid data access
file: /var/www/development/api/webservice/Portal/Users/Login.php (46)
============ stacktrace: 
#0 [internal function]: Api\Portal\Users\Login->post()
#1 /var/www/development/api/webservice/Controller.php(86): call_user_func(Array)
#2 /var/www/development/api/webservice.php(17): Api\Controller->process()
#3 {main}
============ Headers: 
REQUEST_METHOD : POST
HOST: development.imagine.co.za
CONNECTION: keep-alive
CONTENT-LENGTH: 0
USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
CACHE-CONTROL: no-cache
ORIGIN: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
X-ENCRYPTED: 1
AUTHORIZATION: Basic dGVzdDp0ZXN0
X-API-KEY: QKf0CDBWVOiu4oecA6rjJ1dqa2mHzFsI
POSTMAN-TOKEN: 383e831e-a356-1c3b-8946-902fdd702d6f
ACCEPT: */*
ACCEPT-ENCODING: gzip, deflate
ACCEPT-LANGUAGE: en-US,en;q=0.8
============ Request data : 




and i get this on cache/logs/webserviceDebug.log

============ Request ======  2017-06-05 16:13:50  ======
REQUEST_METHOD: POST
Headers: 
HOST : development.imagine.co.za
CONNECTION : keep-alive
CONTENT-LENGTH : 0
USER-AGENT : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
CACHE-CONTROL : no-cache
ORIGIN : chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
X-ENCRYPTED : 1
AUTHORIZATION : Basic dGVzdDp0ZXN0
X-API-KEY : QKf0CDBWVOiu4oecA6rjJ1dqa2mHzFsI
POSTMAN-TOKEN : 383e831e-a356-1c3b-8946-902fdd702d6f
ACCEPT : */*
ACCEPT-ENCODING : gzip, deflate
ACCEPT-LANGUAGE : en-US,en;q=0.8
----------- Request data -----------
Array
(
    [module] => Users
    [action] => Login
)

-------------  Response  -----  2017-06-05 16:13:50  ------
Status: 401
Headers: 
----------- Response data -----------
Array
(
    [status] => 0
    [error] => Array
        (
            [message] => Invalid data access
            [code] => 401
        )

)

**Comment by kabelo38** [comment]
Working all i had to do is pass form data array('userName' => my 'username', 'password' => 'my password')

     <?php
      
     $curl = curl_init();
     curl_setopt_array($curl, array(
     CURLOPT_URL => "http://HOST/api/webservice/Users/Login",
     CURLOPT_RETURNTRANSFER => true,
     CURLOPT_ENCODING => "",
     CURLOPT_MAXREDIRS => 10,
     CURLOPT_TIMEOUT => 30,
     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
     CURLOPT_CUSTOMREQUEST => "POST",
     CURLOPT_POSTFIELDS => "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-
     Disposition: form-data; name=\"userName\"\r\n\r\nUsernameHere\r\n------
     WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; 
     name=\"password\"\r\n\r\nPasswordhere\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--",
     CURLOPT_HTTPHEADER => array(
    "authorization: Basic SW1hZ2luZVdlYkFQSTpvbGRiMEI5OQ==",
    "cache-control: no-cache",
    "content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW",
    "postman-token: 87f66ebe-b1c6-72da-1c61-232e22e1f33a",
    "x-api-key: Your API KEY HERE",
    "x-encrypted: 0"
    ),
     ));

     $response = curl_exec($curl);
     $err = curl_error($curl);

     curl_close($curl);

      if ($err) {
       echo "cURL Error #:" . $err;
       } else {
      echo $response;
      }




My response is 
           {"status":1,"result":{"token":"9d54d2d76a0cbacbea3179f24a13b026","name":null,"parentName":null,"lastLoginTime":null,"lastLogoutTime":null,"language":"en_us","type":1,"logged":true}}

**Comment by kabelo38** [comment]
here is the improved version of the code above. 


            $url = "http://YOURhost/api/webservice/Users/Login";
		$username = 'YourUsername';
		$password = 'YourPassword';
		$api_key = 'YourAPIKEY';
		
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL,$url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
		curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
		curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
		curl_setopt($ch, CURLOPT_POSTFIELDS, array('userName' => $username, 'password' => $password) );
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
		curl_setopt($ch, CURLOPT_HTTPHEADER, array(
			"x-api-key: $api_key",
			"x-encrypted: 0"
			)
		);
		$curl_response = json_decode( json_encode(curl_exec($ch), true) );
		curl_close($ch);  

		print_r($curl_response);
