### ISSUE TITLE
Glitch found on  Web service - Applications

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#4443]
#### Issue

1. I cannot delete  Web service - Applications users
2. I cannot Edit Web service - Applications  it ads new user instead of editing existing user

#### Actual Behavior

![yeti4](https://cloud.githubusercontent.com/assets/5912376/26405113/9b2f9168-4094-11e7-974f-13b5e73aa72b.gif)

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Chrome Version 58.0.3029.110 (64-bit)
* Environment name and version: Ubuntu 16.10
* Operating System and version: Fedora core 24

**Comment by sirwinston1** [comment]
I had the same problem. If you want a quick fix, delete them out of your database and then recreate them in yeti.

**Comment by kabelo38** [comment]
fixed here https://github.com/YetiForceCompany/YetiForceCRM/commit/6fac403b615f6018b0fa9eba5bd47a43af09e7d0
