### ISSUE TITLE
Installing Version 4 lands in bank page 

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#4451]
#### Issue
I have tried to install YetiForceCRM-4.0.0-complete.zip, All requirement were satisfied and installation proceed, then it landed in a Blank Page with out any error, then on refreshing got the below error, further checking release the  fact that the database was not populated 

![screenshot from 2017-05-26 14-47-15](https://cloud.githubusercontent.com/assets/24363648/26488801/70462ea0-4222-11e7-99c2-0452f725a29a.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4 
* Browser name and version: Chrome Version 56.0.2924.87 (64-bit)
* Environment name and version:
Hosting Package 	10GB
Server Name 	gains
cPanel Version 	62.0 (build 8)
Apache Version 	2.4.25
PHP Version 	5.6.30
MySQL Version 	5.6.35
Architecture 	x86_64
Operating System 	linux
Shared IP Address 	184.171.164.163
Path to Sendmail 	/usr/sbin/sendmail
Path to Perl 	/usr/bin/perl
Perl Version 	5.10.1

* Operating System and version:
Linux : Kernel Version 	2.6.32-673.26.1.lve1.4.20.el6.x86_64

**Comment by collibear** [comment]
I join the content of my predecessor. After the installation of the script, an error appeared:
`Błąd!!!
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'collibeargro_1.s_yf_companies' doesn't exist Failed to prepare SQL: SELECT * FROM `s_yf_companies` WHERE `default`=:qp0
`
Link to PHP: http://logibear.eu/yeti/phpinfo.php

Best Regards!

**Comment by mariuszkrzaczkowski** [comment]
"YetiForce Version used: 4" 4.0.0 or 4.0.346 ?
You need to check the server logs (PHP, apache) it's not possible that the logs are empty.

**Comment by alextovey** [comment]
that seems like your sql settings are incorrect have you opened the firewall port if sql is on another server or even typed the password incorrectly?

**Comment by gkArvindr** [comment]
I am closing this because I don't have a solution for this and moved to a new setup
