### ISSUE TITLE
Problem with OSSMailView Detailview - email body is shown in redirected window

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#4455]
#### Issue
on a clean Yetiforce 4.0 installation
when viewing an email in module OSSMailview/Corporate emails detail view, the email body is not shown inline instead the browser window is redirected and the email body text is shown without any yetiforce layout wrapper.

#### Actual Behavior

![ossmailview](https://cloud.githubusercontent.com/assets/10443220/26614650/f2036794-45c1-11e7-885e-5e3ebc8250c4.gif)

#### Expected Behavior
gitstable.yetiforce.com has the correct behaviour

![mailinline](https://cloud.githubusercontent.com/assets/10443220/26614622/e1bec2d4-45c1-11e7-8f86-db0e9fa18a6a.PNG)

Any pointer on how to troubleshoot this problem is very much appriciated.

#### Your Environment

* YetiForce Version used: 4.0 LTE
* Browser name and version: Firefox latest
* Environment name and version:  nginx Fastcgi php 5.63
* Operating System and version:  Debian 7

**Comment by Protocorewebcreative** [comment]
Far play getting to this stage every time I complete the install on version 4.0 keep saying password is wrong, I've tried about 4-5 times now still same thing?

**Comment by setras** [comment]
your message is off topic but anyway
Make sure your password is at least 8 charachters long, contains uppercase letters,  lowercase letters and numbers.

**Comment by mariuszkrzaczkowski** [comment]
Test development version that has already been repaired.

**Comment by setras** [comment]
Great, is there a patch available?

- Master branch still has the problem
- development branch has erorr 500

**Comment by mariuszkrzaczkowski** [comment]
We have plans to release an update package which will include this patch
