### ISSUE TITLE
Problems with the search field

### ISSUE THREAD

**Issue by rafamacedo** [YetiForceCompany/YetiForceCRM#4457]
Hello

I am using YetiForce CRM 4.0.0 in PHP 5.6 environment. The problem occurs in the search field where no result is displayed, but the search term is wisely existing in the records.

![image](https://cloud.githubusercontent.com/assets/26890198/26659186/529c466a-4645-11e7-92e6-09f30ba53a4e.png)

In this case how can I solve this problem in the YetiForce search field. I have already ported versions 3.4 to the latter and the problem is the same. I also noticed that this occurs in any module to be searched.

Thanks for listening!

**Comment by vovpff** [comment]
@rafamacedo let's check your CRON

**Comment by rafamacedo** [comment]
Hello @vovpff  

Thanks for your interest in helping me ... below is the image of the cron scenario.

![image](https://cloud.githubusercontent.com/assets/26890198/26678203/c7be705c-46a5-11e7-8b4e-7eb991f63c66.png)

**Comment by alextovey** [comment]
You've not got a cron job running in there. That is why.

**Comment by alextovey** [comment]
Should be 
*/5 * * * * sh /home/belemaui/public_html/yetiforce/cron/vtigercron.sh >>/home/belemaui/public_html/yetiforce/cache/logs/cron.log

Or something similar to that obvisouly your home directory for yetiforce in place to /yetiforce/

**Comment by rafamacedo** [comment]
Friend @alextovey I did according to your orientation...

![image](https://cloud.githubusercontent.com/assets/26890198/26684837/b38d7a56-46be-11e7-92f8-9fc27663c7c0.png)

I also checked the folders corresponding to this CRON command line and realized that the "cron.log" file does not exist in the "\cache\logs" folder.

![image](https://cloud.githubusercontent.com/assets/26890198/26685010/34e23600-46bf-11e7-8d49-57d3a912a576.png)

This is normal? Through this command when executed, will it automatically create this missing file?

Thank you for your help!

**Comment by alextovey** [comment]
have you followed the guide.
Change file permissions /var/www/crm/cron/vtigercron.sh to 775 [or to other permissions that are compatible with an internal security policy in a company]. 
Set a path in the file /var/www/crm/cron/vtigercron.sh to PHP: export USE_PHP=/usr/local/php56/bin/php [here it is also required to pay attention to the file, because it can be located differently on each server and also keep an eye on a path to PHP that is different for various servers. An administrator can provide information about this path or it can be checked in phpinfo].

**Comment by rafamacedo** [comment]
@alextovey with the first guide I already managed to see the search field work. I tested it with several records and it worked perfectly.

I'm very grateful for your help. You are a YetiForce expert. Congratulations!!!!

Strong hug!

**Comment by mariuszkrzaczkowski** [comment]
I have a better command for cron:
/var/www/cron/vtigercron.sh > /var/www/cache/logs/cron.log 2>&1

**Comment by gkArvindr** [comment]
I have the Cron running, but still the search is 0, what are the other parameter I need to check 
![screenshot_20170715_192110](https://user-images.githubusercontent.com/24363648/28239839-ccb8cc64-6992-11e7-9ac1-d41612e67351.png)

**Comment by paula-w** [comment]
We can't see anything in this picture, please check your logs

**Comment by gkArvindr** [comment]
Which logs do you want me share ?

**Comment by paula-w** [comment]
All of them,  more info here : https://yetiforce.com/en/developer-documentation/engine/115-debugging.html

**Comment by paula-w** [comment]
Also add a screenshot of your system requirements verification
