### ISSUE TITLE
error in YetiREST demo create function

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#4461]
Hi @migoi - thank you ver ymuch  for your YetiREST demo, it was a live saver for me

your demo script create function uses a flat array  #4023 
 $recorddata = array(
    'accountname' => 'Foobar',
    'active' => 1,
    'assigned_user_id' => $yr->userId, // preset current users id based on login information
  );

but it need to be a nested one

  $recorddata = array(
    'recordData' => array(
		'accountname' => 'Foobar',
		'active' => '1',
	),
    'assigned_user_id' => '19x1',
  );

BTW - where you able to create records in the ModComments module? 
I can't get it working.?
Any help is very much appriciated.

**Comment by setras** [comment]
got create ModComments working

1.  in vtlib/Vtiger/Functions.php line 117
    remove ModComments from array 
    $restrictedModules = ['SMSNotifier', 'Dashboard', 'ModComments'];

2. set create data array
  $recorddata = array(
    'recordData' => array(
		'commentcontent' => 'Foobar',
		'related_to' => '3368',
	),
    'assigned_user_id' => '19x1',
  );

**Comment by mariuszkrzaczkowski** [comment]
What webservice do you use? Because it does not create in new yt webservice

**Comment by setras** [comment]
I use the new one api/webservice.php. Attached is the file I use to add records
[webapi.php.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/1074462/webapi.php.txt)

P.S.: The Notification module is breaking the API, I'll open a new issue for that

**Comment by waran70** [comment]
What about creating users? does this new API allowing that?

**Comment by setras** [comment]
No, you can not create users.
Have a look at https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST the demo_yetiforce_api.php file give you a good overview how to use the api

**Comment by mariuszkrzaczkowski** [comment]
Creating users is impossible because it is too dangerous.
Documentation is not yet available but we have plans to create it.

**Comment by waran70** [comment]
Marius, can you point me function to create user with use of workflow?

**Comment by mariuszkrzaczkowski** [comment]
I do not have a sample code for workflow. Here is an example of creating a user

https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/phpunit/02_AddUser.php
