### ISSUE TITLE
How to hide the Modtracker and OSSMailview marker

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#4462]
Hi, how can I control the Modtracker & Email marker 

![marker](https://cloud.githubusercontent.com/assets/10443220/26707203/642101e2-4743-11e7-948d-1e47e3f1fe69.PNG)

- Email marker shows 1 new/unread. How/Where can I acknowledge that I've read the email and hide the marker

- same for the Modtracker marker. One Contact has 30 modification, what is the best way to hide this marker

**Comment by mariuszkrzaczkowski** [comment]
Try changing this parameter
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/ModTracker.php#L17

**Comment by setras** [comment]
sorry, looks like my question was not specific enough.
A user asked me under what conditions or user action is a record/email marked as reviewed and are no longer counted in the marker.
I couldn't answer his question and also couldn't find the code that is responsible for this logic.

Please, can you give me a short explaination or point me to the responsible function location.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/ModTracker/models/Record.php#L112

**Comment by setras** [comment]
thanks!
