### ISSUE TITLE
Webservice - is there a find/lookup record function

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#4464]
I want to connect a webform where the user can unscubscribe from a newsletter to the new webservice api but it seems like the api has no function where I can lookup a record based on a field value other than record id.
In order to unsubscribe I need to 
1.  get the record ID based on the email address.
2. modify the emailoptout field (or any other field).

Do you have plans to add this functionality?

**Comment by mariuszkrzaczkowski** [comment]
This functionality is already there you can search for a record based on the mail then you will get the record ID and you can edit the record

**Comment by setras** [comment]
Mariusz,
I must be blind ,I search the RecordList.php but cannot find a function where I can filter by Field-name/-value pair.

Can you give me a short excample on how to get the record id by email field/value, please.

thanks

**Comment by mariuszkrzaczkowski** [comment]
Sory my mistake, I have already added
![image](https://user-images.githubusercontent.com/10198654/26900767-99537a90-4bd3-11e7-8150-a283c168694f.png)

**Comment by setras** [comment]
super, thanks!!

You're my hero
