### ISSUE TITLE
Multiimage field disabled?

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#4465]
Does anyone know why multimage field is disabled? Maybe developer could give best answer.

https://github.com/YetiForceCompany/YetiForceCRM/commit/416560747c19b04c2f5e21845ac0bd3d99151648

Is left as an option to reactivate this important and useful field?

thanx

**Comment by mariuszkrzaczkowski** [comment]
Field temporarily disabled, not yet completed
