### ISSUE TITLE
Error in PDF relations

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#4466]
When creating pdf template for 'Projects' module there is no option to chose records from projects tasks or milestones. 

Expected that: in whatever module there is a related list from other module, this related module fields obviously should show up in the pdf template to allow create consistent pdf template.
Tested on ver. 4.0.361

**Comment by mariuszkrzaczkowski** [comment]
It's not a bug, just a new functionality

**Comment by waran70** [comment]
O.O You call regression as a new functionality?!

**Comment by waran70** [comment]
Field in pdf templater called  "Fields from related modules" might mislead
users (dependent or related).
Actually this would be good idea to allow kind of list functionality where
between some "hook variable" all fields from related modules
will be represent as a records set (with filtering option). See vtiger
PDFMaker.

**Comment by mariuszkrzaczkowski** [comment]
"Fields from related modules" The field displays a list of fields based on reference fields included in the base module

**Comment by waran70** [comment]
So they dependent in this case NOT related. Relation 1:M shows base records
and all related.

**Comment by mariuszkrzaczkowski** [comment]
I corrected the translation.
If you want to show information from related records then you need to create special functions. Here's an example:
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/TextParser/OverdueDeadlines.php

**Comment by mariuszkrzaczkowski** [comment]
I added new features to the parser text, the ability to list related records. See here
https://github.com/YetiForceCompany/YetiForceCRM/commit/c5a78668fd098ef59d619ecf6cdeafc2e9a4954f
List all records from the system:
https://github.com/YetiForceCompany/YetiForceCRM/commit/75f2b92c622f9da17e32219f0d60e568e6d9aa17
Here are some examples:
$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]|)$
$(recordsList : Contacts|||All)$
$(recordsList : Contacts)$

parameters: ModuleName|Columns|Conditions|CustomViewIdOrName|Limit
