### ISSUE TITLE
[BUG][4.0.367] Calendar's notifications

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#4468]
#### Issue

In a clean installation, the "Calendar" module with or without registers shows the following error from "Calendar notifications"

![firefox_2017-06-07_10-59-27](https://user-images.githubusercontent.com/18419851/26874600-2833631e-4b76-11e7-86bb-4b54995671b4.png)

    "success":false,
    "error":{
      "code":0,
      "message":"SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, 
        references column 'crm_prueba2.vtiger_activity_reminder_popup.datetime' which is not in SELECT list; 
        this is incompatible with DISTINCT
        
        Failed to prepare SQL: 
        SELECT DISTINCT `recordid` 
        FROM `vtiger_activity_reminder_popup` 
        INNER JOIN `vtiger_activity` ON vtiger_activity_reminder_popup.recordid = vtiger_activity.activityid 
        INNER JOIN `vtiger_crmentity` ON vtiger_activity_reminder_popup.recordid = vtiger_crmentity.crmid 
        WHERE (((`vtiger_activity_reminder_popup`.`status`=:qp0) 
        OR (`vtiger_activity_reminder_popup`.`status`=:qp1)) 
        AND ((`vtiger_crmentity`.`smownerid`=:qp2) 
        AND (`vtiger_crmentity`.`deleted`=:qp3) 
        AND (`vtiger_activity`.`status` IN (:qp4, :qp5, :qp6)))) 
        AND (`vtiger_activity_reminder_popup`.`datetime` <= :qp7) 
        ORDER BY `vtiger_activity_reminder_popup`.`datetime` 
        DESC LIMIT 20",
      "trace":""
    }

#### Your Environment

* YetiForce Version used: 4.0.367
* Browser name and version: Firefox 53.0.3
* Environment name and version: WAMP => PHP 5.6.25, MySQL 5.7.14

**Comment by mariuszkrzaczkowski** [comment]
Do you have a properly configured server ??
What value do you have in the sql_mode?

**Comment by WalterLuis** [comment]
Was by sql-mode, by default it had:

	sql-mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

I removed "ONLY_FULL_GROUP_BY", "STRICT_TRANS_TABLES" and now it goes well

In the Web page [103-web-server-requirements](https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html) It would be nice to add "ONLY_FULL_GROUP_BY" as a value that should not be
