### ISSUE TITLE
White page with install.php

### ISSUE THREAD

**Issue by miriampl** [YetiForceCompany/YetiForceCRM#447]
Bare yetiCRM clean installation. Enter this site and receives the white side.
I am trying to do this in Chrome / Firefox on my Linux Mint 17.1 and lamps + server + mysql apatche.

Any ideas?

----------
Goła czysta instalacja yetiCRM. Wchodzę na stronę i otrzymuje białą stronę. 
Próbuje zrobić to na Chrome / Firefox na moim Linux Mint 17.1 i serwerze lamp + apatche + mysql.

Jakieś pomysły ?

**Comment by bpabiszczak** [comment]
Biały ekran to zapewne błąd PHP. Pytanie jaka wersja php, jaka wersja yetiforce i co pokazują logi: Proponuje zapoznać się z tymi dwoma artykułami:

https://yetiforce.com/pl/pomys%C5%82y,-zmiany,-b%C5%82%C4%99dy/b%C5%82%C4%99dy/109-debugowanie.html

https://yetiforce.com/pl/pomys%C5%82y,-zmiany,-b%C5%82%C4%99dy/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html

**Comment by miriampl** [comment]
nie mam parametrów na serwerze nazwa.pl ative 
Nie mogę połowy rzeczy sprawdzić .. można zamknąć bo widocznie to jest to.

**Comment by bpabiszczak** [comment]
Część parametrów konfiguruje się w hostingach, należy podpytać ich jakie z tych parametrów można samemu zmienić i jak.
