### ISSUE TITLE
[BUG][4.0.367] The emails sent from the CRM are not saved

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#4471]
#### Issue

Translation of the browser console warning (gif):
- 'Los scripts no pueden cerrar ventanas que no hayan sido abiertas por un script.' => 'Scripts can not close windows that have not been opened by a script.'

#### How to trigger the error

1.
![bug_corporateemails2](https://user-images.githubusercontent.com/18419851/26883514-45d73b9c-4b95-11e7-8317-99549200dde9.gif)

2.
![bug_corporateemails3](https://user-images.githubusercontent.com/18419851/26883903-58ca56b6-4b96-11e7-9808-525043216c9c.gif)

#### Your Environment

* YetiForce Version used: 4.0.367
* Browser name and version: Firefox 53.0.3
* Environment name and version: WAMP => PHP 5.6.25, MySQL 5.7.14

**Comment by mariuszkrzaczkowski** [comment]
This is not a bug, such functionality has no phpmailer. This was added but the extra configuration was unnecessary
https://github.com/YetiForceCompany/YetiForceCRM/commit/472f22cbca4aa83fa1b87525dc714e2cc966135f

![image](https://user-images.githubusercontent.com/10198654/27155515-8cfc5f88-5159-11e7-9a52-fc328d195d47.png)
