### ISSUE TITLE
[BUG][4.0.368] Report - An error occurred when clicking on the graph

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4472]
An error occurred when clicking on the graph
![1121](https://user-images.githubusercontent.com/19627226/26887497-5d0ef39e-4bd2-11e7-8376-bc2310ceb674.gif)

**Comment by bpabiszczak** [comment]
Please check the latest version.
![generowanie_raportu](https://user-images.githubusercontent.com/10197525/30568190-210980b4-9cd4-11e7-9dd4-7393afd2f652.gif)

**Comment by migoi** [comment]
@ezbank can you please recheck with current gitdeveloper if this is still present?
