### ISSUE TITLE
[BUG][4.0.368] Can't add custom field

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4473]
same as #4449 
![1121](https://user-images.githubusercontent.com/19627226/26887850-63e26da8-4bd3-11e7-9cf6-6d25f5c564e9.gif)

**Comment by frankhzp** [comment]
How did y our guys install the version 4.0.368 ???

**Comment by mariuszkrzaczkowski** [comment]
The system name can not be a number, try x123
