### ISSUE TITLE
Cannot add project task

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#4474]
Cannot add project task due to some stage date. Also milestones should not be mandatory by default in project task module

![shot](https://user-images.githubusercontent.com/12969284/26906664-06953022-4c19-11e7-97e2-ece56dfe9f52.jpg)

**Comment by konadrian** [comment]
You can change this field as non mandatory in https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index

**Comment by konadrian** [comment]
Start date of task can't be greater than due date project milestone
