### ISSUE TITLE
Next stable release

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4475]
When Yeti's planning to crack on the next stable version?

**Comment by ezbank** [comment]
The plans have been overdue for a long time, do not know if they are developed further?

**Comment by SkavenKF** [comment]
Hmmm ...
![grafik](https://user-images.githubusercontent.com/10259801/27408835-dd2d2fd4-56de-11e7-94a6-7e2bb991ea43.png)

**Comment by reeid** [comment]
Would be nice to have compiled to stable current dev version. It contains lots of improvements comparing to 4.0
