### ISSUE TITLE
[BUG] Update Related Record

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4478]
#### Issue

The fields are not updated

#### Actual Behavior

![popo](https://user-images.githubusercontent.com/3030997/26991611-6c4acf26-4d31-11e7-9bcd-3d3539085683.gif)

#### Your Environment

* YetiForce Version used: 4.0.370 Dev
* Browser name and version: latest chrome and firefox
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
You have chosen the wrong type. You chose "Update related record" but you should "Update fields"

**Comment by skramanzia** [comment]
@mariuszkrzaczkowski I need to update the "field" in the related module. If I choose "update fields" I only see the current module field.

**Comment by skramanzia** [comment]
In the example, when run Manual Workflow in Project i need to update for example "type" in Opportunity module.

**Comment by mariuszkrzaczkowski** [comment]
I can not see the module Opportunities in the workflow for the project, is it a standard relationship or have you created your own?

**Comment by skramanzia** [comment]
@mariuszkrzaczkowski Thanks for reopening. Yes, create a relationship in https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&sourceModule=Project

**Comment by mariuszkrzaczkowski** [comment]
This works fine, just added a new relationship (related module) and you want to update the relationship field. For this to work then you need to select this record in the related module

![image](https://user-images.githubusercontent.com/10198654/26996255-8dad4abe-4d71-11e7-88f6-851864182ffc.png)

**Comment by mariuszkrzaczkowski** [comment]
Remember that it works in cron

**Comment by skramanzia** [comment]
@mariuszkrzaczkowski, Yes the relationship works fine. The issue is in workflow, when create to update opportunities field when for example I closed project.

**Comment by skramanzia** [comment]
@mariuszkrzaczkowski After apply "2f14cef" in my environment, nothing change and field update in related module doesnt work. :(

**Comment by skramanzia** [comment]
@paula-w @mariuszkrzaczkowski, Hi Team the issue still in the current version 4.0.373

**Comment by Marshal4582** [comment]
Update related record not working in 6.4
