### ISSUE TITLE
How do you create and use comments

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#4479]
#### Issue
How do you create and use comments in the advanced section of a custom module? Thank you

#### Your Environment

* YetiForce Version used:4.0
* Browser name and version:safari
* Environment name and version:
* Operating System and version:Windows2008

**Comment by vovpff** [comment]
You mean this one?
![image](https://user-images.githubusercontent.com/8545791/27013600-9006f6c8-4eef-11e7-9fdc-104986673e28.png)
You can use this field for anything information.

**Comment by vovpff** [comment]
For creation you need to go to advanced block managing
![image](https://user-images.githubusercontent.com/8545791/27013635-f35f49a0-4eef-11e7-8f6d-59c888b17754.png)
Click Add custom field for Additional line. Select comment at pick list and click save
![image](https://user-images.githubusercontent.com/8545791/27013640-1655bc0a-4ef0-11e7-9ad1-6cfc874ec231.png)

**Comment by copyyour** [comment]
Following your steps, I show this way

![snip20170612_1](https://user-images.githubusercontent.com/27992939/27017065-1bf006d0-4f58-11e7-8edd-12549c9280fc.png)

**Comment by vovpff** [comment]
@copyyour this is solution? Or you mean any another comments?

**Comment by copyyour** [comment]
my mean is any another comments

I want to add comments to the modules you create

thank you

**Comment by waran70** [comment]
That's from vtiger (adjust accordingly):
<?php
require_once 'vtlib/Vtiger/Module.php';
require_once 'modules/ModComments/ModComments.php';
$commentsModule = Vtiger_Module::getInstance('ModComments');
$fieldInstance = Vtiger_Field::getInstance('related_to', $commentsModule);
$fieldInstance->setRelatedModules(array('Invoice'));// Give the Module name for which you want to add comment
$detailviewblock = ModComments::addWidgetTo('Invoice');//Give the Module name for which you want to add comment
echo "Comments have been added for Invoice Module";
?>

**Comment by vovpff** [comment]
@copyyour @waran70 
If you need comments tab to new module please use this SQL query
`INSERT INTO `**yourdbname**`.`vtiger_fieldmodulerel` (`fieldid`, `module`, `relmodule`, `sequence`) VALUES (601, 'ModComments', '**yourmodulename**', NULL);`
Don't forget to change bold worlds to your values

**Comment by copyyour** [comment]
Thank you very much. It has been successful
I would also like to add summaries and updates. What should I do? Thanks again

**Comment by vovpff** [comment]
@copyyour I think Summary and updates will be more harder because this tabs not coded. For example summary tab not available for products and assets modules and I don't have idea how to activate them.

**Comment by nic86** [comment]
go to: Software configuration > Standard modules > Modules – Widgets > System settings

- select module from combo box where you want add widget.

- click button "Add Widget"

- select "fields summary" and "updates"

**Comment by vovpff** [comment]
@nic86 Thanks a lot! This works with Assets module. What you think about Products? Any ideas how to add summary to products?

**Comment by copyyour** [comment]
thank you  @vovpff @nic86  I was successfu。
Can I add documentation?
🙃

**Comment by nic86** [comment]
@vovpff sorry but I have never tried in the product module.

To enable updates, check if the custom module is active in: 
Software configuration > Standard modules > Modules – Track Changes / History > System settings

**Comment by copyyour** [comment]
How do you add documents to custom modules?

**Comment by vovpff** [comment]
@nic86 any ideas about summary to products module?

**Comment by vovpff** [comment]
@copyyour 

To add new relations between you need  to activate ability to add relations in "\config\developer.php" file.

'CHANGE_RELATIONS' => false, param must be **true**

After that go to "Software configuration > Standard modules > Modules – Relations", select custom module and click "Add relation" button and pick attachments from top pick list
![image](https://user-images.githubusercontent.com/8545791/27229593-ce55bd60-52b4-11e7-996e-612681f835fc.png)

**Comment by copyyour** [comment]
thank you @vovpff
