### ISSUE TITLE
YetiForce vs WHMCS do not work at the same time

### ISSUE THREAD

**Issue by rafamacedo** [YetiForceCompany/YetiForceCRM#4480]
Hello guys

I have been working with YetiForce for some time after several attempts to configure PHP and .htaccess to create the best possible environment for the proper functioning of the system. And finally I got it and I'm working on the Portuguese translation. I was very satisfied and well know the tools and options that the system offers. But an unexpected problem occurred when WHMCS stopped working because of the settings I made in favor of YetiForce.

Let's understand through the images below:

This screen has parameters selected and which make YetiForce run 100%...
![image](https://user-images.githubusercontent.com/26890198/27012014-6d3bef8c-4e9e-11e7-8193-a7340ca91f5c.png)

Already on this other screen WHMCS works and YetiForce stops working...
![image](https://user-images.githubusercontent.com/26890198/27012018-8a72884a-4e9e-11e7-808d-324d033bbc82.png)

![image](https://user-images.githubusercontent.com/26890198/27012800-37c33a12-4eae-11e7-9dd4-3a141f3a56df.png)

Look at the differences ...
The first screen shows that for YetiForce to work the parameters nd_mysql and nd_pdo_mysql must be enabled. And as a consequence of that WHMCS no longer logs into the system.

While on the second screen uncheck the parameters mentioned above and leave only mysql that YetiForce is no longer logged in while WHMCS returns to normal operation.

I noticed that if I had an active session in both WHMCS and YetiForce that everything works normally, but I log off depending on which setting is active according to the screens that one or the other system do not work. Therefore both WHMCS and YetiForce do not work at the same time on the login screen.

WHMCS is already fully powered by information and becomes the main system while YetiForce becomes second priority because I am still doing the system translation and preparing the vTiger data for export to the new system.

I contacted the technical support of the hosting and I informed in this way that I write to them. They tried for three days to solve this problem and informed the php.ini that both one and another system are trying to read the parameters. They tried to create two php.ini environments on the same hosting, but it did not work.

I tried to keep all these parameters active at the same time, however a critical message arises that there are conflicts between them and it is necessary to keep only mysql enabled or nd_mysql and nd_pdo_mysql enabled.

So I would like to ask this support for help about this situation. What do you think? Do you have any suggestions that I can pass on to the hosting support or have some manual configuration that I can apply?

Thanks for listening!

PHP 5.6
WHMCS 7.2.2
YetiForce 4.0

**Comment by mariuszkrzaczkowski** [comment]
Just try to enable nd_pdo_mysql
Verify that the latest version of the developer is running without a mysql

**Comment by rafamacedo** [comment]
@mariuszkrzaczkowski 

Thank you for your response. I did as directed and worked YetiForce, but WHMCS stopped working. Then I switched the PHP version to version 7 and ran both, but suddenly they both crashed simultaneously. I checked the parameters and again this nd_pdo_mysql can not function at the same time as pdo_mysql.

I tried editing the php.ini file that is inside the yetiforce folder, but I do not think I'm getting the command correctly:

```
error_reporting=E_WARNING & E_ERROR & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
default_socket_timeout = 600
mysql.connect_timeout = 600
innodb_lock_wait_timeout = 600
max_input_vars = 5000
memory_limit = 512M
suhosin.session.encrypt=Off
suhosin.request.max_vars=5000
suhosin.post.max_vars=5000
suhosin.post.max_value_length=1500000
session.gc_maxlifetime=86400
session.cache_expire=1440
session.gc_divisor=500
session.gc_probability=1
session.save_path=cache/session
display_errors = Off
upload_max_filesize=100MB
log_errors = On
upload_max_filesize = 100MB
max_input_vars = 10000
expose_php = Off
session.cookie_httponly = On
expose_php = Off
output_buffering=On
max_execution_time=600
max_input_time=600
wait_timeout=600
nd_pdo_mysql = On
extension=php_pdo_mysql.dll
```

Thanks

**Comment by rafamacedo** [comment]
Hello again!

I was able to make the YetiForce again work simultaneously with the WHMCS. Keeping the following configuration ...

![image](https://user-images.githubusercontent.com/26890198/27162182-417d3878-5156-11e7-976c-d3cc40643959.png)

However YetiForce has a feature that is in the path Configuration> Logs> Server Configuration. This screen tells me what extensions need to be configured to run the YetiForce. There are two parameters that are circled in red in the above image if they are enabled WHMCS stops working.

I understand that this site is only about YetiForce issues, but WHMCS manages all of my clients' hosting accounts and YetiForce complements my business from the time I manage my business to website creation.

Do not you have any possibility to configure YetiForce to use a php.ini exclusive for these two extensions?

Thanks!

**Comment by densousuds** [comment]
I have the same problem!!! "Aqui é BR tbm kkk"
I don't get use yetiforce on my WHMCS too!! Only on linux still works to me

**Comment by mariuszkrzaczkowski** [comment]
OPcache and APCu are not required

**Comment by rafamacedo** [comment]
Thanks @mariuszkrzaczkowski 

@densousuds tudo bem? Consegui resolver meu problema. Basta deixar ativado apenas o nd_pdo_mysql e o apcu e opcache desativados que o WHMCS e YetiForce funcionam perfeitamente. Veja abaixo como está a minha configuração e faça o mesmo no seu...

![image](https://user-images.githubusercontent.com/26890198/27234260-c681ccb8-5292-11e7-9335-739c0e12e187.png)

@densousuds sua versão do YetiForce é 4.0 e vc tem a tradução para o BR?
