### ISSUE TITLE
Picklist displaying 1 option multiple times

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#4482]
#### Actual Behavior

![picklist](https://user-images.githubusercontent.com/5912376/27023723-13387382-4f54-11e7-9443-4db04ffa567a.png)

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
Working fine on our 4.0 installations.

**Comment by mariuszkrzaczkowski** [comment]
Is this version installed or updated?
Check in vtiger_fieldmodulerel whether nei has duplicates

**Comment by kabelo38** [comment]
@mariuszkrzaczkowski 
Fantastic dude,Yes it was duplicates
I truncated vtiger_fieldmodulerel table and inserted new records found in data.sql on yeti install folder.
