### ISSUE TITLE
YetiForceCRM-4.0.0-complete - Fatal error: Unknown: Failed opening required '/var/www/html/yetiforce/index.php' 

### ISSUE THREAD

**Issue by infoslaw** [YetiForceCompany/YetiForceCRM#4483]
#### Issue

Unable to open YetiForceCRM website.

#### Actual Behavior

Warning: Unknown: failed to open stream: Permission denied in Unknown on line 0

Fatal error: Unknown: Failed opening required '/var/www/html/yetiforce/index.php' (include_path='.:/usr/share/php') in Unknown on line 0

#### Expected Behavior

Installation screen 

#### How to trigger the error

1. 
2.
3.

#### Your Environment

* YetiForce Version used: YetiForceCRM-4.0.0-complete
* Browser name and version: Opera 45.0.2552.898 or Firefox 53.0.3
* Environment name and version: 
Apache/2.4.18 (Ubuntu) - running OK
MySQL Server version: 5.7.18-0ubuntu0.16.04.1
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS ) - running OK
* Operating System and version: Linux Mint 18.1 MATE 64-bit

I did it all this steps to run your software:

chown -R www-data:www-data /var/www/html/yetiforce/

mysql -u root -p
CREATE DATABASE yetiforce;
GRANT ALL PRIVILEGES ON yetiforce.* TO 'yetiforce'@'localhost' IDENTIFIED BY 'your-password';:
FLUSH PRIVILEGES;
\q

nano /etc/apache2/sites-available/yetiforce.conf

<VirtualHost *:80>
ServerAdmin admin@yourdomain.com<mailto:admin@yourdomain.com>
DocumentRoot /var/www/html/yetiforce/
ServerName myyetiforce.com
ServerAlias www.myyetiforce.com<http://www.myyetiforce.com>
<Directory /var/www/html/yetiforce/>
Options FollowSymLinks
AllowOverride All
Order allow,deny
allow from all
</Directory>
ErrorLog /var/log/apache2/your-domain.com-error_log
CustomLog /var/log/apache2/your-domain.com-access_log common
</VirtualHost>

Bat unfortunately still get error when trying to run CRM:

Warning: Unknown: failed to open stream: Permission denied in Unknown on line 0
Fatal error: Unknown: Failed opening required '/var/www/html/yetiforce/index.php' (include_path='.:/usr/share/php') in Unknown on line 0

Really appreciate your help.

**Comment by mariuszkrzaczkowski** [comment]
You must give this error to the server administrator.
There are many possible causes for this error: wrong apache configuration, wrong PHP configuration, incorrect encoding of php files, wrong line end character in php files

**Comment by infoslaw** [comment]
Is it any guide how to install your software and to make any changes on the server?
Also saw that PHP 7.0 & PHP 7.1 it initial compatibility, can someone extend this subject?

Regards,

**Comment by infoslaw** [comment]
seems like classic permission issue, now I am able to get welcome screen with installation wizard however got 3 error lines:
Notice: Use of undefined constant ROOT_DIRECTORY - assumed 'ROOT_DIRECTORY' in /var/www/html/yetiforce/include/ConfigUtils.php on line 161

Notice: Undefined index: STYLES in /var/www/html/yetiforce/cache/templates_c/2a2396618a9ea14fb588efb7ea4b06c83645d1ae_0.file.Header.tpl.php on line 29

Notice: Trying to get property of non-object in /var/www/html/yetiforce/cache/templates_c/2a2396618a9ea14fb588efb7ea4b06c83645d1ae_0.file.Header.tpl.php on line 29

Perhaps PHP 7 incompatibility?

**Comment by bpabiszczak** [comment]
O ile dobrze kojarzę, to znasz PL :] 

Jeżeli widzisz błędy Notice to znaczy, że masz źle skonfigurowany serwer i nie jest on zgodnie skonfigurowany z naszymi wymaganiami opisanymi na stronie WWW: https://yetiforce.com/pl/wdro%C5%BCeniowiec/instalacja-aktualizacja/99-wymagania-dla-serwera-www.html. Musisz to poprawić, bez tego nie ma co iść dalej. 

System działa poprawnie dla PHP 7.x

Jeżeli chcesz tylko przetestować system, to możemy go zainstalować u nas na serwerze na 30 dni bezpłatnie w ramach testów.

**Comment by infoslaw** [comment]
Znam PL! :) Dzięki za podpowiedź i linka. Po zweryfikowaniu i konfiguracji PHP i MySQL udało się uruchomić instalację i z grubsza wszystko działa tak jak chciałem na VM!
Jeszcze raz dziękuję za pomoc.
Pozdrawiam,
Sławek
