### ISSUE TITLE
PDF How to Adjust Product Table / Proforma Invoice Samples

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#4485]
#### Issue

How to adjust ProductsTable and to configure decimals with thousands  separators and currency signs in PDF documents, like Proforma Invoices. 

I saw #4288 but I don't have those files on version 3.4.

#### Actual Behavior

He have the default view.

#### Expected Behavior

We will need to translate the headers, removing fields from the default view and configure the decimal values format.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4 (with hot fix pack)
* Browser name and version: Safari and Chrome
* Environment name and version: Softacolous via CPanel
* Operating System and version: Unix

**Comment by KatarzynaUlichnowska** [comment]
The current version of the system has new mechanisms for grouping and managing currencies and numbers, check if this solves your problem. If the current version of GitDeveloper doesn't solve your problem, you can do it yourself by modifying the functions that are responsible for creating the table  with products/services in PDF (e.g. https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/vendor/yetiforce/TextParser)
