### ISSUE TITLE
Upon installation of 4.0, admin credentials do not work

### ISSUE THREAD

**Issue by joshmans** [YetiForceCompany/YetiForceCRM#4486]
#### Issue
Installation of 4.0 seems to be successful (no errors), but the admin credentials do not work.

#### Actual Behavior
invalid username or password

#### Expected Behavior
Allowed to login

#### How to trigger the error

1. Install 4.0.0
2. Attempt to Login
3.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Most recent Chrome and Firefox
* Environment name and version: MySQL 5.5.54-cl; PHP 5.6.24
* Operating System and version: Linux - Kernel version 3.10.0-427.10.1.lve1.4.22.el7.x86_64

**Comment by mariuszkrzaczkowski** [comment]
Check mysqlnd
This is the duplicate already there are several similar issues like this

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/4427
https://github.com/YetiForceCompany/YetiForceCRM/issues/4160
https://github.com/YetiForceCompany/YetiForceCRM/issues/4028
