### ISSUE TITLE
Send email from modules

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4488]
I believe it will be convenient to have "send email" button on every view of modules (once they have email field). So far we can send email from summary view only (or list view)

**Comment by paula-w** [comment]
Unfortunately we’re not planning to implement that in the nearest future. More about ideas for development that we can’t currently add to YetiForce [HERE](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-development-ideas).
