### ISSUE TITLE
How to translate this?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4489]
#### Issue

How to translate home page widget label like on picture below?

![image](https://user-images.githubusercontent.com/8545791/27133842-5295ffe4-511c-11e7-8419-dd3274f09fe2.png)

#### Actual Behavior

No ability to translate label

#### Expected Behavior

Label can-be translated to any language without any problems.

**Comment by mariuszkrzaczkowski** [comment]
What is the type of widget?
You gave too little information, not knowing what the widget is

**Comment by vovpff** [comment]
@mariuszkrzaczkowski this is usual widget from filter. Filter from IGDN module.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski any ideas how to translate this stuff?

**Comment by konadrian** [comment]
You need to add translations to Home.php files
