### ISSUE TITLE
idea - creating new document

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#449]
When a new document is creating there is possibility to specify "Download type" (internal, external).
It would be very usefull to have defining path for external doc which is saved somewhere (button "choose path" the same princile like button "choose file"). This would be allowing to open it eaisly only by cliking... Now you have to specified name of the doc which after a while...

**Comment by bpabiszczak** [comment]
Soon a mechanism for an integration with WebDAV will be added and it will completely change a way documents are entered to the system and the way their location is specified.
