### ISSUE TITLE
How do I add spanish language to users before they login as in the stable version?

### ISSUE THREAD

**Issue by luespi** [YetiForceCompany/YetiForceCRM#4491]
I would love to make it this way:

https://gitstable.yetiforce.com/

or something similar, or is there anyother way in which you recommend that I set my installation into spanish?
(I think that as a last option I will just swap the language files)
I really really thank you for this amazing script and will donate as soon as I am able to

**Comment by mariuszkrzaczkowski** [comment]
The new language will be available as we publish a new version of the system
