### ISSUE TITLE
How i update the version 4.0.0 yetiforce to 4.0.38

### ISSUE THREAD

**Issue by densousuds** [YetiForceCompany/YetiForceCRM#4492]
#### Issue

I've using the yetiforce on my job, it's an amazing CRM open source system, but still have a little bugs that i have to confront. I want to import the contacts mapped on my accounts and i can't do it.
I've been search from here(Git Hub), and i found that's topic #4401. 

#### Actual Behavior

I have a problem  to import contacts mapped with accounts,
#### Expected Behavior

The contacts should to be imported mapped on accounts.
I want to update the version 4.0.0 yetiforce to 4.0.38
#### How to trigger the error

1.Update yetiforce version 4.0.0 to 4.0.38
2.Map contacts with accounts

#### Your Environment

* YetiForce Version used: YetiForce Version used: 4.0.0
* Browser name and version: Chrome
* Environment name and version: PHP-7.0.18-0ubuntu0.17.04.1
* Operating System and version: UbuntuServer 17.04.1

**Comment by vovpff** [comment]
@densousuds you can upgrade only if if Yeti crew prepare update package.

I have the same situation with import and solved problem with next steps:

1. Fresh installation of 3.4.0
2. Installation of hotfix
3. Import all data
4. Upgrade from 3.4.0 to 3.4.3.4.1427 (by update package)
5. Upgrade from 3.4.3.4.1427 to 4.0.0 (by update package)
6. Profit

**Comment by SkavenKF** [comment]
Actually should every month a bugfix appear, since yetiforce 4.0 as a lts version was marked ( #4093 ). This was already promised for 3.0 and unfortunately not done :-(
Yetiforce crm I think for a good crm system, because of the updating strategy it unfortunately risks for productive use.

**Comment by densousuds** [comment]
Good comment @SkavenKF !!!
@vovpff Greetings for sharing your success to fix it. I'm testing now !!!

I will post my status with these errors.

Thank you for your attention!

**Comment by densousuds** [comment]
@vovpff I don't had sucess.
When I finished import, don't mapped anything ... But if I can do it, I'll certainly post it here. Greetings!!! OBS: I'm still waiting if anyone know how to fix it bug!!!  :)
Thanks for all

**Comment by vovpff** [comment]
@densousuds what files format you use?

**Comment by densousuds** [comment]
@vovpff i'm using .csv

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/3a842b63d5540b57c4f5fb9d39b5ce23397e37ab

**Comment by vovpff** [comment]
@densousuds try to manually add code what @rskrzypczak posted.
I preferred import from XML because this is more flexible. I made some excel formulas to convert csv data from Vtiger to yeti xml.
