### ISSUE TITLE
How do two custom fields perform automatic calculations?

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#4493]
#### Issue
How do two custom fields perform automatic calculations?
thanks。

#### Your Environment

* YetiForce Version used:4.00
* Browser name and version:safari
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@copyyour let's use Workflows
https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=List&block=15&fieldid=24

**Comment by copyyour** [comment]
thanks you~~~
