### ISSUE TITLE
Workflow does not run

### ISSUE THREAD

**Issue by Jibe9191** [YetiForceCompany/YetiForceCRM#4494]
Issue
Workflow does not execute when any condition is added to workflow. I have tried to replicate by manual trigger by the user on https://gitstable.yetiforce.com and it the same result. 

![2017-06-16_15-22-07](https://user-images.githubusercontent.com/3746986/27230804-69c99080-52a8-11e7-915b-8520464ebc15.gif)

Your Environment
* YetiForce Version used: Version 4 Stable 
* Browser name and version: Chrome, Firefox, Safari
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
This was repaired in developer version

**Comment by Jibe9191** [comment]
Thank you for the update, but am using stable version 4.0 how do I resolve this issue since no update has been released.

**Comment by Jibe9191** [comment]
@mariuszkrzaczkowski Thank you for the update, but am using stable version 4.0 how do I resolve this issue since no update has been released.

**Comment by Jibe9191** [comment]
How do I resolve this since am using stable version 4.0

**Comment by mariuszkrzaczkowski** [comment]
You have the following options:

- Buy up support and we'll fix it
- Wait for publication of the update package
- Try to upload modified files yourself

**Comment by SkavenKF** [comment]
Ok, that's a clear statement :-(
I think therefore your statement to the LTS version is obsolete .... 
The only thing that changes are unfortunately version numbers and not the update strategy

look at #4093 
> 
> **LTS**
> 
> Version 4.0 is marked as LTS [Long-Term Support], which in practice means that **for 12 months we will release critical fixes for the system**. It applies only to **fixes related to security issues and problems with using all the tools available in the system.**
> We plan to release new versions once a month, and new LTS versions once per year at the end of each year [that is why 4.0 will be supported until the end of 2017, but we can extend that period if there is great interest in this version].
> We encourage you to to check all the release dates for new versions.
> Please bear in mind these are only assumptions, and therefore the dates might change
>
