### ISSUE TITLE
Where are the Translation“add record” characters in the custom module? 

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#4495]
#### Issue
Where are the Translation“add record” characters in the custom module? 

#### Your Environment

* YetiForce Version used:4.00
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by copyyour** [comment]
Each module adds records that translate different meanings

**Comment by vovpff** [comment]
@copyyour check here
https://gitdeveloper.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=4&fieldid=53

**Comment by copyyour** [comment]
With this change, all modules change, and I want each module to have different “add record” characters

**Comment by mariuszkrzaczkowski** [comment]
What value do you need?

**Comment by konadrian** [comment]
You have to find  'LBL_ADD_RECORD' => 'Add record', translation in your language files, add this translation if it’s missing in some modules and change how you want
