### ISSUE TITLE
When a workflow add records to a module, it adds data to other modules

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#4497]
#### Issue
When a workflow adds new records to a module, it adds data to other modules

#### Your Environment

* YetiForce Version used:4.0.0
* Browser name and version:safari
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Give more details and example

**Comment by copyyour** [comment]
For example, while I add new business records, workflow has also added new records to the project. But at the moment, I don't know how to set up such workflows

**Comment by mariuszkrzaczkowski** [comment]
You need to show an example workflow configuration so that we can verify it
