### ISSUE TITLE
All clients on the map

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#4498]
Hi,
is it possible to show all my clients on the map (Openstreetmap)?

#### Actual Behavior
I can see on the map only one client.

#### Your Environment
* YetiForce Version used: 4.0.0

**Comment by sirwinston1** [comment]
Can you show us the steps you are taking to view the map and clients.

**Comment by WalterLuis** [comment]
![marktomap](https://user-images.githubusercontent.com/18419851/27304598-771d0916-5536-11e7-8711-7d3b657027f8.gif)

Is done as in the gif, you only need to have the CRON activated and a valid address

**Comment by pflaz** [comment]
Great, thank you WalterLuis :)
