### ISSUE TITLE
Mask for phone and date

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#45]
Please add the ability to create a mask for phone and date, an example is shown here:

http://stackoverflow.com/questions/20197696/vtiger-and-jquery-phone-mask

In Header.tpl I have the js reference:

<script type="text/javascript" src="include/jquery/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="include/jquery/jquery.maskedinput.min.js"></script>
When I put the needed code in the header.tpl file, the page with the targeted phone field freezes.

<script type="text/javascript">
jQuery(function($){
   $("#phone").mask( "999-999-9999", { placeholder : "_" } );
   });
</script>

**Comment by mariuszkrzaczkowski** [comment]
Functionality will be available from versions 1.3.x
