### ISSUE TITLE
Error YetiForce 3.3.0

### ISSUE THREAD

**Issue by michelmarques1** [YetiForceCompany/YetiForceCRM#4500]
Hello,

Hello colleagues from the Community,

My instance of YetiForce version 3.3.0 has the following bug

![image](https://user-images.githubusercontent.com/18095104/27257003-e15955d6-539d-11e7-874d-62c77e6ac1d8.png)

Strict Standards: Non-static method OSSMail_Module_Model::getDefaultMailAccount() should not be called statically in /home/olharcri/public_html/crm/gestao/corpore/cache/templates_c/basic/940dc853bf9b06ade47fbf0c161f05cb4c54fcfd_0.file.BodyHeader.tpl.php on line 80

Could you help me solve it?

**Comment by mariuszkrzaczkowski** [comment]
Duplicate:
https://github.com/YetiForceCompany/YetiForceCRM/issues/3391
https://github.com/YetiForceCompany/YetiForceCRM/issues/937

https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
