### ISSUE TITLE
Error YetiForce 3.4.0

### ISSUE THREAD

**Issue by michelmarques1** [YetiForceCompany/YetiForceCRM#4501]
Hello colleagues from the Community,

My instance of YetiForce version 3.3.0 has the following bug
![image](https://user-images.githubusercontent.com/18095104/27257099-06a44668-53a1-11e7-8669-82624bf07704.png)

I could not understand what happened.

The version of my php is 5.6.

**Comment by mariuszkrzaczkowski** [comment]
You have an incorrect server configuration check the configuration requirements
