### ISSUE TITLE
Is it possible to add a picklist in the To Do module of Calendar?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4502]
I want to add a picklist to the To Do module which sits inside Calendar but there is no option to add Custom fields. I basically want to add Task type as a picklist. 

Is the function to add custom fields disabled in Calendar?

Kind regards

**Comment by konadrian** [comment]
we don't recomend doing changes in calendar module becasuse it's many dependencies. If you want possibility adding field in calendar you have change this https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Settings/LayoutEditor/models/Block.php#L29
