### ISSUE TITLE
strange problem about caldav on nginx server

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#4503]
#### Issue

i can visit http://localhost/api/dav.php
it returns:
![default](https://user-images.githubusercontent.com/15126825/27266033-e665153c-54cf-11e7-910c-5c4fe18d6496.png)
but if i visit http://localhost/api/dav.php/principals/Zelphar/
it returns some js source code
![default](https://user-images.githubusercontent.com/15126825/27266059-2b416e08-54d0-11e7-8ef4-666c80b633be.png)

if i open error log. it returns error like this:

> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
> <s:sabredav-version>3.1.3</s:sabredav-version>
> <s:exception>ErrorException</s:exception>
> <s:message>
> stream_get_contents() expects parameter 2 to be long, string given
> </s:message>
> <s:file>/data/crm/libraries/SabreDAV/HTTP/Message.php</s:file>
> <s:line>81</s:line>
> <s:code>0</s:code>
> <s:stacktrace>
> #0 [internal function]: exception_error_handler(2, 'stream_get_cont...', '/data/crm/libra...', 81, Array) #1 /data/crm/libraries/SabreDAV/HTTP/Message.php(81): stream_get_contents(Resource id #71, '') #2 /data/crm/libraries/SabreDAV/HTTP/Request.php(310): Sabre\HTTP\Message->getBodyAsString() #3 /data/crm/libraries/SabreDAV/Yeti/Debug.php(44): Sabre\HTTP\Request->__toString() #4 [internal function]: Yeti\Debug->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) #5 /data/crm/libraries/SabreDAV/Event/EventEmitterTrait.php(105): call_user_func_array(Array, Array) #6 /data/crm/libraries/SabreDAV/DAV/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array) #7 /data/crm/libraries/SabreDAV/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) #8 /data/crm/api/dav.php(80): Sabre\DAV\Server->exec() #9 {main}
> </s:stacktrace>
> </d:error>

#### Expected Behavior

it should return a page like demo

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: firefox and chrome
* Environment name and version: nginx+mysql
* Operating System and version: debian

**Comment by mariuszkrzaczkowski** [comment]
The problem is in the server configuration, check the rules in htacces and what files do not load the browser
