### ISSUE TITLE
[feature] Ability to assign a ticket to a contact

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#4505]
![assign a ticket to contact](https://user-images.githubusercontent.com/5912376/27283860-9e9e8d88-54f6-11e7-9987-3ab7b0254168.gif)

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Chrome
* Environment name and version: Ubuntu 16.10
* Operating System and version: Ubuntu 16.10

**Comment by kabelo38** [comment]
similar to this case https://github.com/YetiForceCompany/YetiForceCRM/issues/1063

**Comment by konadrian** [comment]
If you want to change your relations you should.Go to a file developer.php and change to
'CHANGE_RELATIONS' => true, 
Then in https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&block=2&fieldid=41 you can add relation
