### ISSUE TITLE
Workflow new record event

### ISSUE THREAD

**Issue by lelethered** [YetiForceCompany/YetiForceCRM#4506]
I Guys,
i'm tryng to update a custom field on new record event via workflow; we are able to do that by using manual workflow but when i set the new record on trigger they don't fired and nothing occur. We need to use the new record because must trigger only the first time the record will be generated

We are using the "Number" field in letter incoming module (we configured that with sequence numbering + variable post fix {{YYYY}} and our goal is to update a text custom field where to write Number + Pick list field value from another field (we use an expression concat in workflow).
It seems that variable present in the Number filed is not commited on DB so when workflow run, it able to write only the pick list field value.

Can you suggest a solution or workaround?

Best Regards

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by lelethered** [comment]
Yes, we have installed the last version 4.0.0.
Also i check if there are some code for updating the core inst but no find. If you need some screen shot we are at disposal
Best regards
Emanuele

**Comment by mariuszkrzaczkowski** [comment]
Test here https://gitdeveloper.yetiforce.com/
Include screenshots of workflow configuration

**Comment by lelethered** [comment]
Dear Marius, i test and configure WF in your env, and as you can see the record Letters Incoming with subject "test WF2" works fine on Document N. field

I suppose something strange con variable didn't work on my Environment, anyway we bought an Environment in your Hosting Service with config just done by your team, so we hope the problem will not occurs. In case in new env. the problem persist, i update this case.
Best Regards!Here the attach of WF config
![3](https://user-images.githubusercontent.com/29478429/27431068-66d4520a-574b-11e7-891d-4789f90daf66.jpeg)
![2](https://user-images.githubusercontent.com/29478429/27431067-66d165ea-574b-11e7-9b2a-dd7bbf27db9b.jpeg)
![1](https://user-images.githubusercontent.com/29478429/27431066-66d118c4-574b-11e7-9cb6-749616795be9.jpeg)

**Comment by lelethered** [comment]
Dear Marius,
we have the yetiforce installation on! I configured the WF as in the environment you suggest and tested but the problem persist. I would like understand what appen. Can i send you the address in private?
Best regards

**Comment by skramanzia** [comment]
@lelethered The problem was resolved in DEV environment, you can waiting to next release, if not you can  try to find the code to replace or buy support to resolved your problem.

**Comment by lelethered** [comment]
Thanks @skramanzia, but is not a good beginning! We have just begin to work today in your hosting service and we begin with a bug! Can you send me the reference of the issue that solve this bug so i can modify and solve?

**Comment by skramanzia** [comment]
This is not a Support Portal, it is to report errors to the developers, if you bought the support service and hosting this is not the means, you have to contact YF.
 I do not work for YF.

**Comment by lelethered** [comment]
OK thanks for your explanation

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/694b8cc096dae8b0314cc688106ce2fbefebccdb
https://github.com/YetiForceCompany/YetiForceCRM/commit/da3d04e351f882d6121932bb62697473b5bb7cf7
