### ISSUE TITLE
Invalid username or password after installing

### ISSUE THREAD

**Issue by USTMarketing** [YetiForceCompany/YetiForceCRM#4507]
Hello!

I encountered a weird problem when I tried installing version 4.0.0, more specifically after installing it when trying to login it just displays "Invalid username or password." and it won't let me login at all. I've been using version 3.2 for almost a year now and never had such an issue. I wanted to see some of the new features in version 4 and bumped into this. Any ideas?

Thanks!

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=✓&q=is%3Aissue%20Invalid%20username
#4427
#4160
#4028
