### ISSUE TITLE
sold services import

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#4508]
#### Issue
Hi,
I have a problem with import of sold services - 'related to' field.
What should I type in this field if I want to match sold services with accounts?

#### Actual Behavior
I have tried:
VAT ID
Account name
Account name + VAT ID
Accounts::::Account name VAT ID
account_no

In each case the record has not been imported.

#### Expected Behavior
I would like to know what shoud I type in 'related to' field to import records.

#### How to trigger the error
1. Database -> Sold services
2. Actions -> Import records
3. File type: csv, code: Windows-1250, semicolon, 

#### Your Environment
* YetiForce Version used: 4.0.0
* Browser name and version: FF, IE

Thanks in advance for your help.

**Comment by mariuszkrzaczkowski** [comment]
Add a test record and export it to see how it is done :)

**Comment by mariuszkrzaczkowski** [comment]
"Accounts::::Stach Energia Słońca Sp. z o.o."

**Comment by pflaz** [comment]
Unfortunately in my case something is wrong :/
I have exported test record - the result is:
Accounts::::Testowa firma 1231231212

In import I have tried:
Accounts::::Testowa firma 1231231212
Accounts::::Testowa firma
"Accounts::::Testowa firma"
"Accounts::::Testowa firma 1231231212"

Everything with no result:
Records not imported: 1/1

In details:
Wrong records
Column 1 - Related to: 0

**Comment by vovpff** [comment]
@pflaz I think cause of your problem is broken import feature at stable 4.0.0 version.
Let's check #4492 and implement manually code from 3a842b6 at your system.

**Comment by pflaz** [comment]
@vovpff thanks a lot - it works :)
