### ISSUE TITLE
In Password Module any field is imposible to be modified.

### ISSUE THREAD

**Issue by nkzach** [YetiForceCompany/YetiForceCRM#4510]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0 and latest GitDeveloper
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vahid-jml** [comment]
Hi
you can change or add field in system settings -> Standard modules -> edit fields .
select your module and changed fields .
![screenshot from 2017-06-22 18-58-13](https://user-images.githubusercontent.com/18072100/27439304-ef4d0e20-577c-11e7-9cc5-d20f5893c2f2.png)

**Comment by nkzach** [comment]
Hello
I mean, I can not edit the data values in the records.
After the recording is processed and saved, all the data returns to its original state.
