### ISSUE TITLE
Reports not returning data rows

### ISSUE THREAD

**Issue by rubysown** [YetiForceCompany/YetiForceCRM#4512]
#### Issue
After creating a Report for the Time Control module, if you add any Relational fields to the report, it will not return data.

#### Actual Behavior
Just column averages, sums, etc are displayed. The number of rows are correctly displayed at the top of the report (3 for this example). However, below the totaling rows, the data rows are not there.

![Report Results](http://i.imgur.com/3gH6y51.png)

#### Expected Behavior
Data from each Time event to be displayed in conjunction with the Process/SubProcess fields.

#### How to trigger the error
1. Create new Time Control report
2. Select any Time Control columns as well as any of the Relational fields columns (Process, Sub Process, etc)
3. Generate and save Report.

#### Your Environment

* YetiForce Version used: 4.0.392
* Browser name and version: Chrome/58.0.3029.110
* Environment name and version: Apache, MySQL
* Operating System and version: CentOS

**Comment by krobin8** [comment]
I was able to reproduce this as well.

Works without "Process" field:
![1](https://user-images.githubusercontent.com/12663988/27457504-9e826042-576a-11e7-914c-82515bf1edb3.PNG)
![2](https://user-images.githubusercontent.com/12663988/27457506-a0c5144e-576a-11e7-8f71-9494d078f6cc.PNG)

Does not work when "Process" field is added:

![3](https://user-images.githubusercontent.com/12663988/27457516-ab14ec44-576a-11e7-8116-db0fff65bca6.PNG)
![4](https://user-images.githubusercontent.com/12663988/27457561-ce7fd5a4-576a-11e7-87f3-240e49c5589c.PNG)

**Comment by TomaszQr** [comment]
Please check in current version

**Comment by rubysown** [comment]
Thanks! Confirmed the fix this morning.
