### ISSUE TITLE
Can receipts be created/sent on payment of an invoice?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4513]
Hi,

would anyone know if receipts can be created currently in the system on payment on an invoice? Basically I am wondering what the process is to mark invoices as paid and for those who were invoiced to be notified of this with some kind of receipt? Does it currently exist or is it something I would need to create myself?

Kind regards

**Comment by waran70** [comment]
pdf + workflows?
