### ISSUE TITLE
How create some Fields in join on a child module

### ISSUE THREAD

**Issue by lelethered** [YetiForceCompany/YetiForceCRM#4515]
We are creating a new Module “XXX”.

This module is child of Account with a relation 1:M, so we create a new Custom Field on “XXX” with:
Type —> “Related Field 1:M” 
Table —> Basic
Select Modules —> Account

After this we can go on Account and we can see under Account our new module “XXX” and create the child records.

After that we want to see on our records “XXX” some information about Account (example the Field “Type” on Module Account). How we can do this? How we can create some Fields in join on a child module?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4
* Browser name and version: Chrome/Firefox
* Environment name and version:
* Operating System and version:

**Comment by lelethered** [comment]
None has suggestion?

**Comment by paula-w** [comment]
If you want your new module to show the new field that shows data from the Account module then it’s possible [it’s like this in many modules] but it requires some programming work. 
It’s a simple operation, you only have to add a new text field, you disable edition of this field and you add an entry to one file.

**Comment by mjapple** [comment]
this is an interesting subject , I observed the tables for "vtiger_contactdetails" for contacts and help desk "vtiger_troubletickets" each has column with name "parentid" which indicates the relations  to the Accounts Record ID

**Comment by mjapple** [comment]
this is issue is resolved in version 4.4.0
