### ISSUE TITLE
PDF body overlapping

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4519]
pdf templater body content overlapping with header. 
It can be adjusted with margins, but logically body should be below header.

**Comment by vovpff** [comment]
Looks like I find this bug too!

**Comment by paula-w** [comment]
If we understood correctly, the header should be above the content in body, but it can be solved by manipulating the margins. If the problem can be bypassed, or you can create a template in a way to make it ok, then we don't have the time to change it right now and it will stay as it is. However, if you think this is a critical error then we can take care of it.
