### ISSUE TITLE
In the custom module date control

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#4521]
In the custom module
Does the date control not have to fill in the default date of the day?

#### Your Environment

* YetiForce Version used:4.0.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
You can use https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=List&block=15&fieldid=24
workflows to do this
