### ISSUE TITLE
Send emails stuck in "Emails to send" automatically. 

### ISSUE THREAD

**Issue by USTMarketing** [YetiForceCompany/YetiForceCRM#4522]
#### Issue
Hello, I've set up a workflow to send emails when some criteria is met, the problem is all of them are stuck in the Emails to send list (as shown below), and I have to click each one and press the "Send manually" button for each one, cron is simply not working for some reason. The Frequency(H:M) for Emails sender in cron is set at 00:01. (1 Minute)
![emails](https://user-images.githubusercontent.com/23361655/27534287-250e3a62-5a6f-11e7-9640-5345af16c3c0.png)

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Google Chrome 58.0.3029.110 (64-bit)
* Operating System and version: Windows 7 / Windows 10 (64-bit)

Thank you!

**Comment by sirwinston1** [comment]
Did you receive a confirmation email when you finished setting up your smtp settings? Also what does the cron log say?

**Comment by mariuszkrzaczkowski** [comment]
Cron must be enabled in order to send mails properly. 
If cron doesn't work for you then a lot of mechanisms in the crm won't work either.
