### ISSUE TITLE
Opportunity Estimated Value doesn't assume the correct value

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#4523]
#### Issue

Opportunity estimated value does not update correctly.

#### Actual Behavior

818.00 Kz

#### Expected Behavior

818020,00 Kz

#### How to trigger the error

1.
2.
3.
<img width="1154" alt="opportunities_-_detail" src="https://user-images.githubusercontent.com/12361370/27548311-8a6a5bcc-5a90-11e7-8c14-b8f7c6ad1b81.png">
<img width="1160" alt="currency" src="https://user-images.githubusercontent.com/12361370/27548388-bdf788f2-5a90-11e7-8249-4fa3028448a0.png">
<img width="1160" alt="currency" src="https://user-images.githubusercontent.com/12361370/27548405-c7556ff4-5a90-11e7-9817-b7b5e5c9c63e.png">
![Uploading Opportunities_-_Detail.png…]()

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version: Safari and Chrome
* Environment name and version: Softacolous
* Operating System and version: MacOS Sierra

**Comment by mariuszkrzaczkowski** [comment]
By default this field is not updated automatically, you have to describe the problem in more detail
