### ISSUE TITLE
How-to Create an Invoice from Proforma Invoice

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#4524]
#### Issue

How to create and invoice from a Proforma Invoice. Is there any way to do it?
Proforma Invoice would also be created by the Quotation Process, is there any functionality available to do it?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 3.4
* Browser name and version: Safari & Chrome
* Environment name and version: Softacolous
* Operating System and version: MacOS

**Comment by vovpff** [comment]
@PDMeira try this https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95
