### ISSUE TITLE
Random deletion of documents

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4525]
Morning all,

I'm running version 3.4.0 - on ubuntu 16.04 version 2.4.1 with php 7.0 on a virtual sever with 4tb space. For some reason documents are being deleted randomly from the system but still showing in crm. 

I've had a look at error logs and nothing to say its being removed from the system. Is this something you have seen before/maybe a fix? I'm currently moving all data across to version 4.0 to see if that will combat it.

I will find a screen shot of one of the files missing.

**Comment by mariuszkrzaczkowski** [comment]
There is no such mechanism that removes files from storage. Run full logs in CRM and on the server maybe this is another script on the server?
