### ISSUE TITLE
Q: roundcube lifetime

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4529]
is there any plan to replace roundcube with custom email client module?

**Comment by paula-w** [comment]
What is wrong with Roundcube in your opinion?

**Comment by waran70** [comment]
Nothing indeed, just this feeling that clicking "Send email" brings impression that not yetiforce window popping up... I dont mind that, but question blinking: if alternative (really internal) mail module might come one day

**Comment by paula-w** [comment]
You might have enabled the external mail client for the user, when you change this option the mail client will become internal.  
This button is called "internal mail composer" and can be found in  Software configuration > Permissions > Users in the "More information" section. 
Please check it and let me know if this is what you meant.

**Comment by waran70** [comment]
Checking or not "internal mail composer" changing nothing in email sending method behavior. 
Yetiforce using all the time Roundcube. 
I using clean install of 4.0 and roudncube is connected to gmail.

**Comment by waran70** [comment]
Another comments are that:
1. roundube popping-up as a full window (so we loosing focus on module/record we sending email from)
2. After sending email, it diverting to roundcube mailbox instead of module where we clicked
email link (checked on current dev)

**Comment by paula-w** [comment]
Please open a new issue for each of these problems and describe them in details if they still exist.

**Comment by paula-w** [comment]
There is some kind of an error in there, and to make it work you have to change the value in this field twice. But in our opinion it works properly after this change.

**Comment by kimborg** [comment]
With version 4.4, the issue persists. I set "Internal mail composer" to "Yes" on user, but clicking new mail still opens Roundcube.

**Comment by KatarzynaUlichnowska** [comment]
Hello kimborg, please add a new issue as it's a new problem.
