### ISSUE TITLE
Cannot Create Chart or Widget from Filter

### ISSUE THREAD

**Issue by krobin8** [YetiForceCompany/YetiForceCRM#4531]
#### Issue

I am attempting to add a widget or chart from a filter. I have selected the ability to use the filter in metrics. The problem is that when I drop down the "Select Module" drop down no modules appear.

#### Actual Behavior
"Select Module" drop down box returns "No Results Found"

#### Expected Behavior
Expect to see a list of modules from which to choose filters.

#### How to trigger the error

1. From home screen, select "Add widget from filter"
2. Drop Down "Select Module" (expect to see results)

![captureee](https://user-images.githubusercontent.com/12663988/27637539-b0b0d612-5bd5-11e7-8609-ea34cb51a5a5.PNG)

#### Your Environment

* YetiForce Version used: 4.0.407
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
I tested gitdeveloper and can not see the problem

**Comment by WalterLuis** [comment]
You need to create a custom filter in the module that you want to create the widget and check this button:

![chrome_2017-07-08_00-06-10](https://user-images.githubusercontent.com/18419851/27979921-7abc8bf2-6371-11e7-9104-e57c798d0a13.png)

**Comment by Dbinutu** [comment]
I am having this same issue, how can it be resolved ?

**Comment by vovpff** [comment]
@Dbinutu Set List in Metrics option when edit filter

**Comment by Dbinutu** [comment]
@vovpff  Thanks for your prompt response. I have set "List in Metrics" for a few filters through editing "Filters - Configuration" . The modules are still not showing up for those filters that I set. Can you please give me a step by step instruction. Thanks.

**Comment by z0lo13** [comment]
Start Having this issue - didnt change anything related to this module but have the same issue now - it does not let me choose the module

**Comment by z0lo13** [comment]
@bpabiszczak @krobin8 @mariuszkrzaczkowski does any php or apache extension required for this?

**Comment by mariuszkrzaczkowski** [comment]
- Upgrade to the latest version (or install the last stable version of the CRM system on the same server)
- attach screenshots from configuration verification
- attach full logs
- check if you have the mysqlnd extension

**Comment by dpboulder** [comment]
I'm unable to get widgets or charts to select a module. The "Select Module" dropdown is blank. I've tried making visible and uploading "widgetfix_v1" - still no luck getting this to work
<img width="399" alt="yeti-blank_dropdown" src="https://user-images.githubusercontent.com/16730093/51398033-68435c00-1af7-11e9-933f-f4520784c9dd.PNG">
Any help is appreciated.

**Comment by silmarwen89** [comment]
Hi there!
I have the same issue. I'm using YetiForce 4.4.0 and i can't add any widget beacuse "Select Module" dropdown is blank. I've installed "widgetfix_v1" but it is still not working. Any idea?
Thanks in advance.

**Comment by wrobeltomasz** [comment]
In my opinion this is dependent on hosting configuration. On my localhost (xampp) is ok, but on commercial host i have a problem. I test on same 4.40 version both environment. 


Commercial configuration screen below.

![1](https://user-images.githubusercontent.com/46556533/51856752-c14d9400-2330-11e9-97bd-11fb6d33144e.png)

![2](https://user-images.githubusercontent.com/46556533/51856855-096cb680-2331-11e9-96f1-80c6a038d28d.png)

**Comment by mariuszkrzaczkowski** [comment]
Correct the configuration and check if you have mysqlnd installed
