### ISSUE TITLE
Is it possible to change the labels for Assigned To and Share with users in a single module?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4533]
Hi,

I want to change the labels in one module for Assigned To and Share with users. I have gone through the language files for the module (tickets) but these are not included. Can this be done, if so is it a special file that requires changing?

The other option is to be able to create a similar selector that allows me to select from staff/users but I cannot see anything that allows this (this would be my preferred option).

Kind regards

**Comment by vovpff** [comment]
@PercyP i'm not sure but if you add some translation for this module new translation will appear. Module translation has higher priority than global translations.

**Comment by mariuszkrzaczkowski** [comment]
Yes, just add a translation to your module's language file. You only need to have the appropriate label for the field
