### ISSUE TITLE
Latest version of Customer Portal and Invoices, Sales etc.

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4534]
Hi,

has there been any update on the Customer Portal? Is there a version that looks like the one available here: https://gitdeveloper.yetiforce.com/portal

Also, will it be possible to view invoices, sales orders etc.? I noticed they don't exist in that demo but wondering is just a case of linking to the modules you want in the menu setup?

Kind regards

**Comment by PercyP** [comment]
Hi,

I found the latest version here: https://github.com/YetiForceCompany/YetiForcePortal/releases

However it doesn't seem to work. There are no workflows relating to it, it doesn't show up in the CRM (I am sure it used to?) and it does not send login details even when a contact is set to access customer portal.
In the config/api.php there is no reference to the portal (in the instructions it says to remove the comments from this file to activate the portal. 

Has anyone got it working? I am on yetiforce 4.0

Kind regards

**Comment by PercyP** [comment]
I think I am getting closer. So far I have:

1. Downloaded latest release of portal here: https://github.com/YetiForceCompany/YetiForcePortal/releases
2. uploaded and extracted it to my server
3. uncommented webservers webserver in config/api.php
4. added portal url to yetiforce/config/config_inc.php
5. added crm path to portal/config/config.php
6. Gone to yetiforce Configuration - Integration > Web service - users > System settings and completed the details as per the settings in the yetiforce demo here: https://gitdeveloper.yetiforce.com
6. added  webservice user as per the above demo in Integration > Web service - users
7. I created a contact and set the Customer Portal user to yes with valid start and end dates
8. no email is received after setting up the portal user. 
9. I go to the portal login page and try the login details I entered for the web service user earlier - doesn't work
10. I user the send password button - no email is received

Are there more settings/steps I am missing?

**Comment by konadrian** [comment]
We are starting work on portal2 soon, I think your steps to login into portal are correct

**Comment by rrajan94** [comment]
I downloaded all files from here:- 
https://github.com/YetiForceCompany/YetiForcePortal

Now, please give me some instruction to how to upload that all files and where to upload all files.
