### ISSUE TITLE
PDF template Value button broken

### ISSUE THREAD

**Issue by UPSduck** [YetiForceCompany/YetiForceCRM#4536]
#### Issue

In the PDF template tool to edit or create new templates, under steps 3,4&5 (header,body&footer contents) the Value button Loads the next step apposed to copying the Value. 

#### Actual Behavior

On selecting a field to copy when selection the Value button it responds as though I selected the Next Button and loads the next step.

#### Expected Behavior

When clicking the Value button I expect it to copy the field value so I can past it into the content.

#### How to trigger the error

1.  Software configuration > System tools > PDF > Edit 
2.  Step 3
3. Click on any Value button

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Chrome Version 59.0.3071.115
* Operating System and version: Windows 10 Pro version 1511

#### Note
on button hover error happens in console:
Uncaught TypeError: Cannot read property 'style' of undefined
    at p.reposition (ZeroClipboard.js?s=1476108520:9)
    at p.setCurrent (ZeroClipboard.js?s=1476108520:9)
    at HTMLButtonElement.d (ZeroClipboard.js?s=1476108520:9)

**Comment by vovpff** [comment]
@UPSduck check this bug in dev version
