### ISSUE TITLE
TextParser example

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#4538]
Can you guys give me a sample custom function what will print all contacts belonging to one account?
Appreciate enlightening :) 

I mean output in pdf of course..

**Comment by vovpff** [comment]
I'm interested too for some DIY TextParser examples

**Comment by mariuszkrzaczkowski** [comment]
Here is a similar example

https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/OSSTimeControl/textparsers/List.php

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/vendor/yetiforce/TextParser
