### ISSUE TITLE
Unable to import Email manually from Roundcube in Developer Version [ver. 4.0.392]

### ISSUE THREAD

**Issue by lcuevastodoit** [YetiForceCompany/YetiForceCRM#4541]
#### Issue
Unable to import Email manually from Roundcube in Developer Version [ver. 4.0.392]

#### Actual Behavior
Unable to import Email from Roundcube in Developer Version [ver. 4.0.392]. When I press the Import link It says the email was downloaded, but dont appear the account or contact buttons above the email to do that, No new import emails in database neither
#### Expected Behavior
When import email, I expect after I could  relate this with an account or contact eg

#### How to trigger the error
When I press the Import link It says the email was downloaded, but dont appear the account or contact buttons above the email to do that, No new import emails in database neither
![mail import](https://user-images.githubusercontent.com/25910807/27700678-eb0718c8-5cc3-11e7-8b0a-9cd75773ff9a.gif)

#### Your Environment

Developer Version [ver. 4.0.392]
From Firefox and Chrome same behavior

**Comment by mariuszkrzaczkowski** [comment]
Show what is in the browser console

**Comment by lcuevastodoit** [comment]
In the browser console I saw this
![cid error](https://user-images.githubusercontent.com/25910807/27921726-4b71c9a4-623e-11e7-9dd2-b23bf6cd591a.PNG)
After that I create a CID collumn in vtiger_ossmailview table, like this
![cid collumn](https://user-images.githubusercontent.com/25910807/27921778-7bc24cc8-623e-11e7-829b-f57ed66b29ec.PNG)
After this, I can import email from INBOX folder only, but in SENT folder I cannot import anything, then in SENT browser console showed vtiger_notes "filesize" collumn cannot be NULL, then I changed that to allow NULL, and the console error not appearing again, but I cannot import from SENT emails

**Comment by mariuszkrzaczkowski** [comment]
On the developer version works,
Do you have an updated system?

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=OSSMail&view=index

**Comment by lcuevastodoit** [comment]
I think I had the last version ver.4.0.392
