### ISSUE TITLE
Can mass import do

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4542]
Hi,

Is it possible when adding documents on  mass add or import the the title of the document to create a record in a custom module?

For instance a document called Monster IT gets created in a Candidate module with the First Name Monster and Surname IT.

Would this be possible if so what code would we need or could it be a feature request. I'm sure there are a few others who might find this useful. 
@vovpff @mariuszkrzaczkowski @bpabiszczak

**Comment by mariuszkrzaczkowski** [comment]
Yes it is possible but it requires programming work.
