### ISSUE TITLE
Error updating V3.4 to V.3.4.14.27

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#4545]
#### Issue

No errors during V3.4 update to V3.4.14.27, but logon screen is blank, nothing happens after the update

#### Actual Behavior

Blank logon screen

#### Expected Behavior

Normal logon screen

#### How to trigger the error

1. The only error message that I have got on log is Call to a member function getRoleDetail() on null in /home/admin/public_html/crm/vendor/yetiforce/PrivilegeQuery.php on line 80
2.
3.

#### Your Environment

* YetiForce Version used: V3.4.14.27 (after upgrade)
* Browser name and version: Safari & Chrome
* Environment name and version: Softaculous origin  (CPanel)
* Operating System and version: MacOS

**Comment by paula-w** [comment]
We need more detailed logs to investigate this problem
