### ISSUE TITLE
Opportunity editing closed

### ISSUE THREAD

**Issue by rafamacedo** [YetiForceCompany/YetiForceCRM#4547]
Hello dear friends

Recently I closed an opportunity like "Sale Completed" and now I had to edit the value of the opportunity just because I had not noticed the error. Now YetiForce does not allow me to do this edition. I researched here in the Community and found an article ([#3946](https://github.com/YetiForceCompany/YetiForceCRM/issues/3946)), However the solution only applies the version prior to what I am using which is version 4.

![image](https://user-images.githubusercontent.com/26890198/27766805-316c71b8-5eb4-11e7-9916-8003dffc7648.png)

Would anyone know how I can enable this possibility?

**Comment by vovpff** [comment]
@rafamacedo Check this  https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&page=2&view=List&sourceModule=&orderby=&sortorder=

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/SSalesProcesses/SSalesProcesses.php#L15

**Comment by rafamacedo** [comment]
Thanks @vovpff, but this solution did not answer or I could not understand what you wanted to say as a solution. And thanks to @mariuszkrzaczkowski because his response even though a manual solution in the code solved the problem. I believe that in a next version YetiForce has a more practical option to activate the field without having to tinker with the code. For now, your solution answers because I'm the only one who collaborates.

Thank you all!
