### ISSUE TITLE
Create user without admin

### ISSUE THREAD

**Issue by douglasfabianospecht** [YetiForceCompany/YetiForceCRM#4548]
Hello..
I'm starting with Yeltiforce, and I have one question that I need to know if it's possible for a non-admin user to create other users.
In the permissions does not appear to me the module permissions to assign to a profile.
I'm using version 4.0.0

**Comment by alextovey** [comment]
@douglasfabianospecht 
Hi,
 it is not, you need admin access to get to the backend of the system. Why would you want someone to grant user access, this will open up a whole can of worms with fake accounts etc.
