### ISSUE TITLE
Drag'n drop - documents

### ISSUE THREAD

**Issue by JohnMaverick** [YetiForceCompany/YetiForceCRM#4549]
Can uploading documents be done by drag & drop? This will be very convenient

**Comment by waran70** [comment]
Good idea

**Comment by paula-w** [comment]
Right now we are not planning to add this feature. The documents module will have a new functionality to load files once we start further developing this module.

**Comment by lazzzrus** [comment]
Is there any progress? 
This function would be highly appreciated!
