### ISSUE TITLE
do not have button to add new related module

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#4550]
#### Issue

Normally in system setting, we can create relationship between modules.
but now there is no add relation button on setting page

#### Actual Behavior

![image](https://user-images.githubusercontent.com/15126825/27769439-b09139c2-5f5b-11e7-99a0-c15bb6ca0d9b.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@zelphar plz activate relation editing in config/developer.php

**Comment by alextovey** [comment]
@zelphar you need it looking like this:
` // Change of fields visibility
        'CHANGE_VISIBILITY' => true,
        // Adding/Deleting relations between modules.
        'CHANGE_RELATIONS' => true,
`
