### ISSUE TITLE
Error!!! Sorry! Attempt to access restricted file.

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#4551]
![screenshot_20170703_061918](https://user-images.githubusercontent.com/24363648/27774845-ab2512a4-5fb7-11e7-8025-95ce4b11359d.png)
![screenshot_20170703_062106](https://user-images.githubusercontent.com/24363648/27774889-88de8260-5fb8-11e7-993b-79bdcd1541ab.png)

Yetiforce version 4
OpenSuse 4.2
PHP 7
10.0.30-MariaDB
-----------
When ever I select Leads - Edit Field I get the following error
Error!!! Sorry! Attempt to access restricted file.

http://localhost/xxxxx/index.php?parent=Settings&module=LayoutEditor&sourceModule=Leads

I have checked file permission they seem to be fine, 
/srv/www/htdocs/xxxxx/layouts/basic/modules/Leads/

other than Fields - Under Leads module, rest all works . 
Can you help me identifying whats wrong ..

**Comment by gkArvindr** [comment]
I found the below error in logs ....
[03-Jul-2017 06:33:15 Asia/Kolkata] PHP Notice:  Only variable references should be returned by reference in /srv/www/htdocs/xxxxx/vendor/yetiforce/Fields/Owner.php on line 186
[03-Jul-2017 06:33:15 Asia/Kolkata] PHP Notice:  Only variable references should be returned by reference in /srv/www/htdocs/xxxxx/vendor/yetiforce/Fields/Owner.php on line 186
[03-Jul-2017 06:33:15 Asia/Kolkata] PHP Warning:  Illegal string offset 'field' in /srv/www/htdocs/xxxxx/modules/Vtiger/uitypes/MultiReferenceValue.php on line 39
[03-Jul-2017 06:33:15 Asia/Kolkata] PHP Warning:  Illegal string offset 'module' in /srv/www/htdocs/xxxxx/modules/Vtiger/uitypes/MultiReferenceValue.php on line 40

**Comment by vovpff** [comment]
@gkArvindr check web-server requirements

**Comment by alextovey** [comment]
@gkArvindr all folders need to be 755, file 644. If you have root access then `sudo chown -R www-data:www-data /var/www/html/yetiforce/ ` replace /var/www/ folder with your folder location.

if filezilla then right click permissions set folder permissions.

**Comment by mariuszkrzaczkowski** [comment]
Your server is not compatible with the system requirements (because you can see in the "PHP Notice" logs) and this can cause many errors. Start by improving your server configuration.
https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65

**Comment by gkArvindr** [comment]
The system 755 permission is given still gives the same error . I checked all the other server parameters they are as per the requirement 
What does the below err refers if you know about it 
PHP Warning: Illegal string offset 'module' in /srv/www/htdocs/xxxxx/modules/Vtiger/uitypes/MultiReferenceValue.php on line 40

**Comment by alextovey** [comment]
@gkArvindr do you have root to the server? 

I see you are using opensuse. Might be worth putting on ubuntu,

**Comment by mariuszkrzaczkowski** [comment]
Take a screenshot of "Server configuration > System settings"

**Comment by gkArvindr** [comment]
![screenshot_20170703_205146](https://user-images.githubusercontent.com/24363648/27799164-ca5c35f6-6031-11e7-87ff-f7416849cfba.png)

Ubuntu might not be a option as it is clients requirement

**Comment by alextovey** [comment]
@gkArvindr i wouldn't go any higher than php 7.0. If you follow this tutorial it helps with yetiforce install. Client wants opensuse? bad decision tbh but thats my opinion.
http://idroot.net/linux/install-yetiforce-crm-ubuntu-16-04/

**Comment by mariuszkrzaczkowski** [comment]
Set error_reporting	= E_ALL & ~E_NOTICE
Show the rest of the configuration.
Why is the owner of the files is root, should be Apache ex. www-data?

**Comment by gkArvindr** [comment]
I took time see where to change the "error_report" variable, php.ini  and it has the right value , but yetiforce reports the below 
------------------
E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_USER_ERROR | E_USER_WARNING | E_USER_NOTICE | E_STRICT
------------------
out put of $php -ini
etc/php7/cli
Loaded Configuration File:         /etc/php7/cli/php.ini
Scan for additional .ini files in: /etc/php7/conf.d
---------------------
what could I be missing

**Comment by gkArvindr** [comment]
@mariuszkrzaczkowski  - i tried as root because , I wanted to rule out permission issue

**Comment by gkArvindr** [comment]
![screenshot_20170704_141124](https://user-images.githubusercontent.com/24363648/27822272-b68f2ce0-60c2-11e7-8985-f658319f4efc.png)
missing part as requested

**Comment by gkArvindr** [comment]
i took care of the sql-mode also, only thing remaining is the  ERROR setting, I seem to be lost

**Comment by mariuszkrzaczkowski** [comment]
Turn on full logs and check for errors

**Comment by gkArvindr** [comment]
I get error when adding custom fields , there is something wrong happening , the same error I got again while working with Products. if i restore the previous backup everything works fine, that means it is not something to do with file permission,  it has got to do with picklist 
out put from the error log....
12-Jul-2017 23:52:26 Asia/Kolkata] PHP Warning:  Illegal string offset 'field' in /srv/www/htdocs/bhoomi/modules/Vtiger/uitypes/MultiReferenceValue.php on line 41
[12-Jul-2017 23:52:26 Asia/Kolkata] PHP Warning:  Illegal string offset 'module' in /srv/www/htdocs/bhoomi/modules/Vtiger/uitypes/MultiReferenceValue.php on line 42
[12-Jul-2017 23:56:00 Asia/Kolkata] PHP Warning:  Illegal string offset 'field' in /srv/www/htdocs/bhoomi/modules/Vtiger/uitypes/MultiReferenceValue.php on line 41
[12-Jul-2017 23:56:00 Asia/Kolkata] PHP Warning:  Illegal string offset 'module' in /srv/www/htdocs/bhoomi/modules/Vtiger/uitypes/MultiReferenceValue.php on line 42

**Comment by gkArvindr** [comment]
what does it mean by "illegal String" , any clue will help me to identify and zero in

**Comment by gkArvindr** [comment]
$fieldInfo = vtlib\Functions::getModuleFieldInfoWithId($params['field']);
		echo $fieldInfo; die; --- I added this to the file /modules/Vtiger/uitypes/MultiReferenceValue.php on line 41
it did not display any errot but contined working with out error - many be you guys can give me a clue what to do

**Comment by gkArvindr** [comment]
public function getPicklistValues()
	{
		$picklistValues = $this->get('picklistValues');
		if (!empty($picklistValues)) {
			return $picklistValues;
		}
		$params = $this->get('field')->getFieldParams();
		$fieldInfo = vtlib\Functions::getModuleFieldInfoWithId($params['field']);
		echo $fieldInfo; die; <--------WHAT I ADDED
		$queryGenerator = new \App\QueryGenerator($params['module']);
		if ($params['filterField'] != '-') {
			$queryGenerator->addCondition($params['filterField'], $params['filterValue'], 'e');
		}
		$queryGenerator->setFields([$fieldInfo['fieldname']]);
		$values = $queryGenerator->createQuery()->indexBy($fieldInfo['column'])->column();
		$this->set('picklistValues', $values);
		return $values;
	}

**Comment by mariuszkrzaczkowski** [comment]
All logs are not just PHP errors
https://yetiforce.com/en/developer-documentation/engine/115-debugging.html#phplogs

**Comment by gkArvindr** [comment]
thanks Mariuszkrzaczkowski, 
after the last remove adding  "echo $fieldInfo; die; <--------WHAT I ADDED" in file MultiReferenceValue.php. I dont get the error, even after removing the added line the error seems to have disappeared. 

I have enable all logs except for the  Roundcube 

one error I got on the Screen is pasted below 
Fatal error: Uncaught Error: Call to a member function getMessage() on string in /srv/www/htdocs/bhoomi/vtlib/Vtiger/Functions.php:733 Stack trace: #0 /srv/www/htdocs/bhoomi/include/main/WebUI.php(257): vtlib\Functions::throwNewException('2: Illegal stri...', false) #1 /srv/www/htdocs/bhoomi/modules/Vtiger/uitypes/MultiReferenceValue.php(41): exception_error_handler(2, 'Illegal string ...', '/srv/www/htdocs...', 41, Array) #2 /srv/www/htdocs/bhoomi/modules/Vtiger/models/Field.php(395): Vtiger_MultiReferenceValue_UIType->getPicklistValues() #3 /srv/www/htdocs/bhoomi/modules/Vtiger/models/Field.php(725): Vtiger_Field_Model->getPicklistValues() #4 /srv/www/htdocs/bhoomi/modules/Settings/LayoutEditor/models/Field.php(261): Vtiger_Field_Model->getFieldInfo() #5 /srv/www/htdocs/bhoomi/cache/templates_c/basic/d36094ad984986b7306e026f5ec545bf759a96b6_0.file.Index.tpl.php(84): Settings_LayoutEditor_Field_Model->getFieldInfo() #6 /srv/www/htdocs/bhoomi/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): con in /srv/www/htdocs/bhoomi/vtlib/Vtiger/Functions.php on line 733

**Comment by mariuszkrzaczkowski** [comment]
You have incorrectly set the sql-mode, update to version 4.1 and check the error was

**Comment by mariuszkrzaczkowski** [comment]
Try updating or installing the latest version of your system and then test your error.
You wrote that the error is occurring as you add a field, record a video showing it.
