### ISSUE TITLE
Office 365 failing

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4553]
Morning, 
I've had this working before but not it's stopped with office 365. However it works with gmail. 

I've input all the details I had in this post
https://github.com/YetiForceCompany/YetiForceCRM/issues/4002

But it is now coming up as "Connection to IMAP Server failed"

Any help would be awesome please. As I'm struggling to find out why.

In the error logs  I get 
'[03-Jul-2017 11:43:58 +0100]: <bnejns0t> IMAP Error: Login failed for clare@projectstart.co.uk from 79.77.12.33. Empty startup greeting (outlook.office365.com:993) in /var/www/html/projectstart/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_imap.php on line 193 (POST /modules/OSSMail/roundcube/?_task=login&_action=login)'

But I can't figure out why it's failing.

**Comment by SkavenKF** [comment]
same with me .... (v4.0)

**Comment by alextovey** [comment]
sorry forgot to mention it is 4.0

I manually moved all data across from the old one.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=office365

**Comment by alextovey** [comment]
I've copied exactly and still not working @mariuszkrzaczkowski any chance you could shed a bit more light on the subject of how to configure with office 365, I am happy to setup a test 365 account for you to play with.

**Comment by mariuszkrzaczkowski** [comment]
This requires verification by the developer, I once configured but I do not remember what the settings were.
You need to change the default settings

**Comment by alextovey** [comment]
Why close it?????? still i've not had an answer as to how to configure. Considering most companies use office 365 now in the uk. this would be really useful to know.

**Comment by SkavenKF** [comment]
look at #4584 and change "tls" to "ssl" in "name of imap/smtp server"
when your domain is emty, you must log on with your complete o365 email
