### ISSUE TITLE
Purchase Order

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4555]
As everybody know Purchase Order is a one of the most common documents being issued between entities. Did notice that Yetiforce dont have such a module. Why?

**Comment by reeid** [comment]
They call it Sales enquiries - what is confusing. Changing Purchase order to some in-house created naming is not a perfect solution. I would love to see this module to get back to worldwide approved name.

**Comment by waran70** [comment]
indeed confusing

**Comment by waran70** [comment]
Reopened so maybe this can be reconsidered by Yeti's?

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=SSingleOrders&view=List&mid=124&parent=118
https://gitdeveloper.yetiforce.com/index.php?module=SRecurringOrders&view=List&mid=125&parent=118

**Comment by waran70** [comment]
Marius you pointed to Sales Order. Sales Order is a confirmation of having order from customer whiles Purchase Order is a confirmation that we willing to have service/product from supplier.
You should stick to generally approved naming convention, so no surprises would be recorded

**Comment by KatarzynaUlichnowska** [comment]
Use "Vendor enquiries" to request something from a supplier. 
Use "Goods Received Note" to accept goods from a supplier to a warehouse. 
Please note that our sales process is more advanced than in other systems, so the naming is also different. 
What naming would you suggest then?

**Comment by waran70** [comment]
You are not "enquiring" from Vendor. Your "Ordering"!
"Purchase Order" is a final stage of short negotiations with supplying party. It means that price and quantities has been agreed (email, previously accepted price or whatever), and if Supplier/Subcontractor don't accept PO, it can be voided any time without financial responsibility.
The way of dealing with suppliers is shorter than dealing with Customers. Who pay whom?
You say, your sales process is more advanced....! Are you discovering business stuff again? it 21 century guys? Dont try to be unique using artificial naming.... be straight and dont confuse specialist in marketing/sales/management fields.

You are welcome.

**Comment by KatarzynaUlichnowska** [comment]
Thank you, that's one opinion. What the rest of the community thinks? If there are more members, who think we should change it to Purchase Order, we will. I will leave this issue open for a few days.

**Comment by reeid** [comment]
There is few good examples:
Salesforce
vtiger
odoo

and.... ask auditor how to post Sales Enquiry to general ledger - I guess he will say I DONT KNOW
as the name of document misleading completely, and in this way creating row in logic of sales/purchase process.

**Comment by waran70** [comment]
SAP too

**Comment by raghukr80** [comment]
It should be purchase order, because 2 sale inquiries will confuse and  we will raise a PO to the supplier and get the products delivered to us, i will go with WARAN70

**Comment by KatarzynaUlichnowska** [comment]
The process since the time a Vendor enquiry is issued till the time goods are accepted to the warehouse is spread over time [in the ERP systems]. In Vtiger, this process was limited to one module and only the status determined its stage. This module was very faulty in Vtiger because many status changes added goods to stock multiple times, so the inventory control wasn't reliable. 

In most ERP systems that we know, this process is divided into the following stages: 
1. Vendor Enquiries
2. Vendor Orders
3. Advice Note
4. Goods Received Note

We want to follow this process, so the "Purchase Order" is just one of several modules and it means something like "Vendor Order" and I understand that you want us to add it because at the moment there are modules 1 and 4 but the entire process requires also 2 and 3. 

Of course, the system will be built in such way that it will be possible to use any module and a user won't be forced to use all 4.

**Comment by waran70** [comment]
Katarzyna, you focus on products, but where are services?

**Comment by myproducttrials** [comment]
We are working on multiple solutions of multiple products and purchase order is a standard implementation. Also trying to implement yeti and got rejected just for Purchase order and we are reviewing other products. Its a better cause to introduce Purchase order as its a fitting scenario in Asia, Africa, middle east as we see during our implementations.

**Comment by waran70** [comment]
Number 1,3,4 are useless in the core of such system. Those elements can be easily programmed on demand. Following all those steps will eat massive load of time in most of companies. OK, We can switch some modules off, rename others, but here we go again: naming convention and basic skeleton of each processes (marketing, sales). Dunnno actually how removing unnecessary modules could affect rest of system parts. I suggest to simplify processes, so it will be easier to digest for potential admins and users. 
Mind that most of users are "service" focused. Yeti is still behind fully featured ERP system, so lets build it on very stable foundations with simplified structure, but advanced flexibility.  Amen

**Comment by Rosalems** [comment]
It should be PO "Purchase Order"

**Comment by danxpar** [comment]
Bump.
Hi, I just started looking into yetiforce as an erp solution to a few clients.  Glad I am not the only one who thought it should be named 'Purchase Orders'.
I guess by now it is staying as "vendor enquiries" ?

**Comment by deepti4666** [comment]
PO "Purchase Order" would simplify/make the process more understandable.

**Comment by garryatbrighton** [comment]
Vendor Enquiries
Vendor Orders >>>>>>>>>>> Where are Vendor Orders?
Advice Note
Goods Received Note

Making process complicated doesnt make Yetiforce more powerfull.  Do PO, SO. INV and that i!
As Yetifirce have amaizing function of adding line items to any module, blowing up existing structure just get messy.

We need Purchase Order back! hehe
