### ISSUE TITLE
Is it possible to disable Products including in the Invoices module?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4556]
Hi,

is it at all possible to disable Products in Invoices? I did try to disable the Products and Outsourced Products in The Module Install section but it still shows up as Add Product in the Invoice - even though when clicked it throws an error because it is obviously disabled. 

Kind regards

**Comment by mariuszkrzaczkowski** [comment]
Have you tested gitdeveloper ???

**Comment by PercyP** [comment]
Hi,

I have just tested the gitdeveloper, that is working fine. I created a service, disabled the product tables and then did a test invoice and it works.

**Comment by mariuszkrzaczkowski** [comment]
Probably need more files to copy. In addition, I see that you have an incorrect server configuration
