### ISSUE TITLE
DAV sync not working and different address books mapping

### ISSUE THREAD

**Issue by StreetGuru** [YetiForceCompany/YetiForceCRM#4557]
Hi,<br /><br />First of let me say that I'm a fan of your work and would like to thank you for developing and sharing this project. I've recently been trying a range of systems, from sugar to suite, goint to vtiger and yeti - plus a few others like odoo and bitrix.<br /><br />I'm looking for a few essential (for me) functionalities in the CRM, namely the ability to sync with outlook and be able to acess it on my mobile (ideally through an app).<br /><br />What led me to yeti in the first place was the DAV integration, which I think is a must. I use the Caldav Outlook synchronizer to sync outlook with a Sogo instance and my phone. I'm looking for a way to map those address books and calendars to the crm as well.<br /><br />I've installed YetiForce and configure it well so far (or so I think). I've corrected all the errors in the php.ini suggested in the initial install script, I've enable DAV in the config/api.php (and set the browser, cardav, caldav and webdav to true) and I've correctly configured the cron service (using www-data crontab). <br /><br />I can import one of my address books succesfuly - in settings &gt; integration &gt; Dav Applications I can see the correct number of contacts listed - but they do not show up in my contacts tab (or anywhere else, such as leads or organizations). Also, I notice that the cron service (in settings &gt; automation &gt; cron is stuck running on the cardav. Any log I can check to figure out why?<br /><br />Also, I notice that there is only one address book when doing discovery through the dav server - but there are at least 4 different address books on the program - Leads, Organizations, Vendors, Contacts. I personnally keep a different address book within outlook for each of those categories and ideally would like the ability to map a sync of each address book individually. I'm thinking this may be easily implemented in yetiforce and that is probably of interest to other users?<br /><br />The same goes for the Calendar and being able to create several calendars (for projects, etc.) and have each one map to a unique caldav address so it could be mapped individually. This works great with sogo for example - and would provide an ability to integrate with it as well.<br /><br />Any help figuring out why contacts are not synching from the dav to the mai address book would be great, thanks.<br /><br />​​​​​​​Fred<br /><br /><br /><br /><hr />Generated by YetiforceCRM ver. 4.0.0<br />PHP: 5.6.30-0+deb8u1<br /><br /><strong>Server configuration errors:</strong><br />innodb_lock_wait_timeout: 50

**Comment by mariuszkrzaczkowski** [comment]
What version of system do you use? 
Test the latest version of the developer?
 If you have a problem with cron then you need to enable full logs and see if there are any errors.
Read the article
https://yetiforce.com/en/github/issues/126-issues.html

For every user there is only one book that contains everything. So I will agree with you that it would be better to do some address books, only first someone has to order it to add to the system. Especially that dav is not a simple integration.

Look at ours. Github has had some similar issues
