### ISSUE TITLE
[BUG] Password Gestion - Don't update information after creating

### ISSUE THREAD

**Issue by studiosynchro** [YetiForceCompany/YetiForceCRM#4561]
#### Issue
Module OSSpassword for manage Password don't update fields after you have created a new password.

Same problem on demo git dev.

* YetiForce Version used: v4
* Browser name and version: mozilla - chrome
* Environment name and version: Hosting on VPS linux ubuntu 16.04

**Comment by konadrian** [comment]
Can you show some screens or gif to explain your problem
