### ISSUE TITLE
Bug - email templates dont respect priviledges

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4562]
If I assign email template to admin and tick it "private" this email template can be edited by any user.
Seems to be super important bug, as every user can mess up ticketing system, notifications etc....

**Comment by reeid** [comment]
I confirm, this bug is in v 4.0. This is critical bug actually. Hope guys will prioritize it and it will work well in v 4.1

**Comment by mariuszkrzaczkowski** [comment]
I tested gitdeveloper and can not see the problem

**Comment by reeid** [comment]
Yet still functionality error. If record is public (Permissions/Module access) but admin "tick" private, user (non admin) after clicking got returned error.  If record is "private" (in Permissions/Module access) non admin user have assigned some random generated records but admin cannot see them... 
![yetiforce permission denied](https://user-images.githubusercontent.com/12969284/27980620-d0732360-63aa-11e7-99a2-be8fd0acf826.png)

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/4006
