### ISSUE TITLE
Function hlp

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#4565]
Gents, here is my custom function with use of which I need to create user. It not work. Can anyone en-light me where is an error?

============

function handleVendoUserGen($entity) {
    include_once 'modules/Users/Users.php';
    $user = new Users();
    $user_password = makeRandomPassword();
    $user_email = $entity->get('email');
    $role_id_to_assign = 'H6';
    
    $id = explode("x", $entity->get('id'));
    $vendorid = $id[1];
    
    $user->column_fields["user_name"] = $user_email;
    $user->column_fields["first_name"] = 'Test name'; 
    $user->column_fields["last_name"] = 'Test surename'; 
    $user->column_fields["email1"] = $user_email;
    $user->column_fields["roleid"] = $role_id_to_assign;
    
    $user->column_fields["status"] = 'Active';
    $user->column_fields["is_admin"] = 'off';
    $user->column_fields["user_password"] = $user_password;
    $user->column_fields["holidays"] = 'de,en_uk,fr,it,us,';
    $user->column_fields["workdays"] = '0,1,2,3,4,5,6,';
    $user->column_fields["weekstart"] = '1';
    $user->column_fields["namedays"] = '';
    $user->column_fields["reminder_interval"] = '1 Minute';
    $user->column_fields["reminder_next_time"] = date('Y-m-d H:i');
    $user->column_fields["date_format"] = 'dd-mm-yyyy';
    $user->save("Users");
    
}
=============

**Comment by mariuszkrzaczkowski** [comment]
This is the vtiger code. In yeti you have to use Vtiger_Record_Model
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/phpunit/02_AddUser.php
