### ISSUE TITLE
Import data error

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#4567]
Hello.
How i can increase limit for import data in version 3.4.0.
I see that in latest version we have a file called import.php

I am getting error when import more than 1000 records.

![errorynes](https://user-images.githubusercontent.com/30116021/28116396-a23c0d3a-6711-11e7-81e1-323c6ea7cf09.png)

I tried to install version 4.0.0 but after installing it's said to me that user password is incorrect when i try to login.

Thanks!

**Comment by konadrian** [comment]
We added that in the latest version. And one more thing - report one problem per issue.

**Comment by Ataraxiainc1** [comment]
Still waiting for a solution here. I am using YetiForce CRM 6.1 Service Pack v7 Importing 1900 Products

![image](https://user-images.githubusercontent.com/15527660/112737714-73da0b00-8f2a-11eb-8002-e6c1cba6be0b.png)


I can´t find any helpful command in the PHP documentation.
