### ISSUE TITLE
Custom Fields Dependency - Not Working as Mentioned 

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#4569]
How do I enable certain custom fields based on selection of parent field

Like , I have an " Old Property for  Sale " then certain information like the age of the property, condition of the property, should enable based on the parent selection. 
something like
IF OLD PROP then Display this fields else don't display

**Comment by gkArvindr** [comment]
something in line with Dynamic Fields & Layouts
not able to see documentation for it any help appreciated

**Comment by sirwinston1** [comment]
You could use the Fields - Hide Blocks module to hide fields if another field = X.  So if your user selects the property type as condo you could have it hide fields that are unique to a detached home (just an example).  Hopefully that helps

**Comment by gkArvindr** [comment]
I created a custom block and used hide block , gave the condtion rule but i did see the hide function working, . pl direct me to the related document page or video

**Comment by sirwinston1** [comment]
Could you post images or gif of the step you took so I can make sure we are talking about the same thing?

**Comment by gkArvindr** [comment]
![screenshot_20170714_035431](https://user-images.githubusercontent.com/24363648/28190377-34835004-6848-11e7-9a00-ced91307f3c8.png)

**Comment by sirwinston1** [comment]
Your view column is empty and needs to be set.  Edit view will hide the block when the user is in edit mode and detail will hide the block in detail view.  You can also choose both so the block is not visible in either.

**Comment by sirwinston1** [comment]
![123](https://user-images.githubusercontent.com/6587713/28191146-d80563b4-67eb-11e7-9260-3b7ec394d231.PNG)

![1234](https://user-images.githubusercontent.com/6587713/28191150-db7f6db4-67eb-11e7-895f-500ff881033c.PNG)

![12345](https://user-images.githubusercontent.com/6587713/28191154-dfa5480a-67eb-11e7-8ed0-156629b2b870.PNG)

![123456](https://user-images.githubusercontent.com/6587713/28191156-e26d7efe-67eb-11e7-9b73-5d8b0201fd4e.PNG)

**Comment by gkArvindr** [comment]
What you are saying is if I select Edit & Detail - the Block will not be visible,  in my case It does not work 
![screenshot_20170714_043009](https://user-images.githubusercontent.com/24363648/28191387-98628f5e-684d-11e7-80ac-a0bb8f584cc0.png)

![screenshot_20170714_043049](https://user-images.githubusercontent.com/24363648/28191368-7a04746e-684d-11e7-832f-14bd4c9071a9.png)

**Comment by gkArvindr** [comment]
Does it work for Custom Fields?

**Comment by gkArvindr** [comment]
thanks @sirwinston1 , got it done, it is pretty good now
