### ISSUE TITLE
Relation ship

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#4570]
https://wiki.vtiger.com/vtiger6/index.php/Fields_and_Layout_Editor

What is equivalent of the Relationship  in Vtiger in Yetiforce

**Comment by SkavenKF** [comment]
![grafik](https://user-images.githubusercontent.com/10259801/28184591-43476a6e-6814-11e7-96b0-e34694a1dffe.png)

**Comment by gkArvindr** [comment]
Thx, wiill explore
