### ISSUE TITLE
Change default related search field

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#4571]
Hello.
I need to make a relationship between Products module and a new module.
From default i can make a relationship based on default category field like Product name.
I need to make a relationship between a new field in Products and a field in the new module caleed Vendors Stock.

How i can do it?

Thanks!

**Comment by sirwinston1** [comment]
I am not sure I completely understand what you are tying to accomplish but maybe the mapping module will accomplish what you want? 

![relate](https://user-images.githubusercontent.com/6587713/28187025-6e9fada0-67da-11e7-80bd-1560d76fe86d.PNG)
