### ISSUE TITLE
Mass edit limit change

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#4572]
#### Issue
How i can change mass edit limit?

#### Actual Behavior
Now mass edit is working for up to 500 records.

#### Expected Behavior
Increase mass edit for up to 100k records or unlimited.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Google Chrome
* Environment name and version:
* Operating System and version: Windows 10

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/Import.php

**Comment by cltvchannel** [comment]
I don't need to change Import limit, i need to change mass edit limit.
Thanks !

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/config.template.php#L180

**Comment by aleterracciano** [comment]
Salve, ho lo stesso problema ma la versione 6.3.0, non trovo il file nel percorso. Potreste dirmi dove aumentare questi valori tramite ftp? Grazie
