### ISSUE TITLE
image in article in knowledge base

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#4577]
#### Issue
I cannot add an image in the article in knowledge base by 'send' button

#### Actual Behavior
I'm in:
Knowledge base -> Article -> Image -> Send
I choose an image and click 'send' button and I have an error: 
'Invalid request - Response For Illegal Access'

#### Expected Behavior
I would like to add the image from my computer

#### Your Environment
* YetiForce Version used: 4.0.0
* Browser name and version: FF, IE
* Operating System and version: Win10

**Comment by pflaz** [comment]
More information from browser console:

POST http://*****/index.php?module=KnowledgeBase&action=ImageUploadA…=KnowledgeBase_editView_fieldName_content_20&CKEditorFuncNum=1&langCode=pl 500 (Internal Server Error)

submit @ ckeditor.js?s=1497127912:546
c.onClick @ ckeditor.js?s=1497127912:534
(anonymous) @ ckeditor.js?s=1497127912:538
p @ ckeditor.js?s=1497127912:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js?s=1497127912:12
click @ ckeditor.js?s=1497127912:537
(anonymous) @ ckeditor.js?s=1497127912:529
p @ ckeditor.js?s=1497127912:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js?s=1497127912:12
(anonymous) @ ckeditor.js?s=1497127912:62

Does anybody have any idea?

**Comment by mariuszkrzaczkowski** [comment]
Logs....

**Comment by pflaz** [comment]
There are only errors in logs:

`[Wed Jul 19 00:10:03.032707 2017] [ssl:warn] [pid 24978:tid 139906246015104] AH01909: www.***.pl:443:0 server certificate does NOT include an ID which matches the server name

[Wed Jul 19 00:11:03.022623 2017] [ssl:warn] [pid 24978:tid 139906246015104] AH01909: www.***.pl:443:0 server certificate does NOT include an ID which matches the server name

[Wed Jul 19 01:01:07.002637 2017] [ssl:warn] [pid 11599:tid 140173153212544] AH01909: www.***.pl:443:0 server certificate does NOT include an ID which matches the server name

[Wed Jul 19 01:01:08.001746 2017] [ssl:warn] [pid 11599:tid 140173153212544] AH01909: www.***.pl:443:0 server certificate does NOT include an ID which matches the server name`

**Comment by pflaz** [comment]
In 4.1.0 works fine.
