### ISSUE TITLE
Closing Ticket from Portal

### ISSUE THREAD

**Issue by ousidahou** [YetiForceCompany/YetiForceCRM#4578]
Hello everyone,
A big thank you to all the team YETIFORCE for its effort,
I am on version 3.3.0 and I have installed version 3.2 of the client portal,
Normally everything works very well except that from the protail I can not close the ticket.

have an idea to solve this?

thank you.

![untitled](https://user-images.githubusercontent.com/22946462/28241289-9a94c804-6989-11e7-8c61-5198648c1838.gif)

**Comment by mariuszkrzaczkowski** [comment]
We no longer support the customer portal 1
