### ISSUE TITLE
Mass delete contacts

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#458]
For some reason I am unable to mass delete contacts. I can mass delete everything else (accounts, etc) but not contacts. I can delete on by one from the record, but not mass delete.

I checked any logs I could find, but i don't see anything. Do you know where I can check to see what's going on?

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/ideas,-changes,-bugs/bugs/126-how-to-report-bugs.html
