### ISSUE TITLE
Possibility to Copy Address from Partners module

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4580]
Hi,

I want to add a Copy from Partners button to the address field in 'another module'. So far I have added a 1:m from within my 'other module' with the target set as Partners module. I can select the Partner, but it doesn't display the copy from button. If I add a 1:m to the contacts module it correctly displays the Copy from Contact button. 

I have added a module relationship between partners and the other module and vice versa.

Is there a missing step to get this working?

**Comment by konadrian** [comment]
You need add button to this file https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/layouts/basic/modules/Vtiger/BlockHeader.tpl and add action in js file
