### ISSUE TITLE
[bug] cannot install dev 4.0.455

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#4582]
#### Issue

i would install the actual development version 4.0.455

#### Actual Behavior

when i enter the url, following error occured
![grafik](https://user-images.githubusercontent.com/10259801/28251892-da321824-6a86-11e7-9c01-9d7e0ceb4db2.png)

#### Expected Behavior

on same the same servers, version 4.0, 3.3 or lower runs (or install) without problems

#### How to trigger the error

1. download dev version
2. extract to htdocs
3. enter url

#### Your Environment

* YetiForce Version used: 4.0.455
* Browser name and version: chrome, firefox, edge
* Environment name and version: xampp, wamp, ...
* Operating System and version: w10

**Comment by ezbank** [comment]
replace all file in folder vendor at here (https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.0.0/YetiForceCRM-4.0.0-complete.zip)

**Comment by mariuszkrzaczkowski** [comment]
Use composer install

**Comment by SkavenKF** [comment]
@ezbank 👍 
@mariuszkrzaczkowski : what du you mean with "use composer install" ?

**Comment by SkavenKF** [comment]
@ezbank : no success 😢 
![grafik](https://user-images.githubusercontent.com/10259801/28258075-8a6163d8-6acf-11e7-8d22-a94d70f4241f.png)

**Comment by mariuszkrzaczkowski** [comment]
https://www.google.pl/search?q=composer+tutorial&oq=composer+tutorial&aqs=chrome..69i57j0l5.4204j0j7&sourceid=chrome&ie=UTF-8
https://www.dev-metal.com/composer-tutorial/

**Comment by SkavenKF** [comment]
Why do not I have to do this in version <=4.0.0

**Comment by mariuszkrzaczkowski** [comment]
Composer is from version 4.x

**Comment by mariuszkrzaczkowski** [comment]
Try the latest version 
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.1.0/YetiForceCRM-4.1.0-complete.zip
