### ISSUE TITLE
Global Search In YF 4 - Showing Results as "0"

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#4583]
HI 
I am getting search results as "0" 
I am on YF version 4. 
I checked the cron and it is running, what else should I check for 

![screenshot_20170717_043042](https://user-images.githubusercontent.com/24363648/28252035-bc44c894-6aa8-11e7-9a9b-c5cd5911a030.png)

**Comment by sirwinston1** [comment]
Does the search work when searching "all records"?

**Comment by gkArvindr** [comment]
no it did not work

**Comment by vovpff** [comment]
@gkArvindr are you try to search some data what was imported?

**Comment by gkArvindr** [comment]
NO just plain entered data, I am trying to search

**Comment by vovpff** [comment]
@gkArvindr check your cron.
Update field here https://gitdeveloper.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=13&fieldid=56

**Comment by mariuszkrzaczkowski** [comment]
I tested on gitdev, i can’t see the problem. 
I can't see anything in this screenshot, your cron is most likely malfunctioning, or your server configuration is wrong

**Comment by gkArvindr** [comment]
Hi again Mariuszkrzaczkowski ,
I want guidance to add custom field to  global search can you please direct me that link

**Comment by paula-w** [comment]
Please open a new issue for each new question unrelated to the original thread, otherwise it gets messy. 
More about submitting issues in [THIS](https://oldwww.yetiforce.com/en/github/issues.html) article.

**Comment by gkArvindr** [comment]
sure
