### ISSUE TITLE
Office365 mailbox configuration？

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#4584]
#### Issue
I'm using the office365 mailbox, and there's always an error when it's configured. I don't know if it's the right configuration

IMAP connection error

#### Your Environment

* YetiForce Version used:4.0.0
<img width="892" alt="qq20170717-074320 2x" src="https://user-images.githubusercontent.com/27992939/28252376-47d39262-6ac4-11e7-9f22-1a64011d9882.png">

* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by copyyour** [comment]
change ss://. it's ok

**Comment by SkavenKF** [comment]
@copyyour what do you mean with "change ssl://"?

**Comment by copyyour** [comment]
tls:// chang ssl://
