### ISSUE TITLE
Product's Commisions rate is not working

### ISSUE THREAD

**Issue by martinprog7** [YetiForceCompany/YetiForceCRM#4586]
#### Issue
I want to see commissions earned per sales, but I can not find them. Is there a module used to view commissions? 

#### Actual Behavior
Every time I make a sale, I do not find the commission for the sales. Whereas the Commission rate field of the product I have filled.
![product s commisions rate field](https://user-images.githubusercontent.com/28561573/28258230-4a367db8-6afa-11e7-8f20-366f0a285db4.JPG)

#### Expected Behavior

I can see commissions on each sale.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* https://gitstable.yetiforce.com

**Comment by paula-w** [comment]
Please check if the error also occurs in the [dev version](https://gitdeveloper.yetiforce.com/index.php).
