### ISSUE TITLE
Where is the correct file for updating from version 4.0i

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4593]
I want to update my version to the latest update as see some people on here have later versions than me i.e. 4.04xxx

My question is, where do you download these updates? I have looked in the following locations, the first one seems to have the latest:

https://github.com/YetiForceCompany/UpdatePackages

https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%202.x.x/Update%20packages/

Also, I have heavily customised my roundcube, is it possible to not update this? I have also customised my default theme, will the changes be overridden? 

Kind regards

**Comment by SkavenKF** [comment]
There are only updates for the stable versions. You must wait for the next release, maybe end august.
V4.0.xxxx are developer versions.

**Comment by PercyP** [comment]
@SkavenKF 

Thanks!
