### ISSUE TITLE
My Custom  module can't install on Yeti 4.0.0

### ISSUE THREAD

**Issue by boyinfotronics** [YetiForceCompany/YetiForceCRM#4607]
My  Custom module can't install on Yeti 4.0.0

I got a message **Module does not contain default language (en_us).**

but my custom module can work on vtiger 6.5.0
and **it already has language en_us** on a file structure and another file in zip is in UTF-8 Format

this is my module https://github.com/boyinfotronics/v

Please Help . Thank You

**Comment by mariuszkrzaczkowski** [comment]
Vtiger modules do not work on yetiforce systems.
