### ISSUE TITLE
Creating widgets from custom modules

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#4612]
Hi,

Is it possible to create widgets from custom modules? The new widgets look differnt from what i'm used too and I think staff will get confused from 3.0 i'm now running 4.0

**Comment by alextovey** [comment]
@vovpff @bpabiszczak 

Do you know how todo this please?

**Comment by alextovey** [comment]
@TomaszQr 
Can you explain to me what I need todo. 

I have two widgets i need to add data from on the homepage. first is called Activites, it's like your calendar but only in a text format without a view it includes a few fields such as name, caller, telephone, comments, etc.

Second is adding the new comments made through out the crm. 
This would be fantastic i've tried to follow https://github.com/YetiForceCompany/YetiForceCRM/issues/2119

But i'm struggling with it.

**Comment by KatarzynaUlichnowska** [comment]
Yes, you can create charts and widgets from custom modules.

**Comment by alextovey** [comment]
how please? @KatarzynaUlichnowska

**Comment by KatarzynaUlichnowska** [comment]
The same way as for regular modules. The system doesn't distinguish whether it is a custom module or not.

**Comment by alextovey** [comment]
Okay, so i'm creating a gif as as cannot seem to get this function to work correctly. it wont display for the homepage. when creating a widget module it works on the that module but cant see it on the homepage.
![widgets](https://user-images.githubusercontent.com/22075161/30154436-cb36ffd4-93b1-11e7-8026-e075697427f6.gif)

**Comment by KatarzynaUlichnowska** [comment]
You're showing two completely different functionalities. Widgets on home page and widgets on records are completely different, and in fact, they have nothing in common. In order for the new module to have widgets on the home page, you must add appropriate code and permissions in profiles. This requires a bit of programming because it has not yet been automated.

**Comment by xqmsg** [comment]
Is there ANY guide to program Yetiforce? I can not find ANY documentation or examples.

**Comment by rskrzypczak** [comment]
@xqmsg nothing more than that:  https://github.com/YetiForceCompany/YetiForceCRM#read-the-documentation-to-learn-more
