### ISSUE TITLE
Contact picture in PDF

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#462]
Seems not possible to get the Contact picture showing in an PDF template.
The variable #imagename# does only show a filename (but incomplete)
Pictures are stored with a number in front and even with a full URL it is not possible to get the full link.

**Comment by bpabiszczak** [comment]
It can be achieved through special functions, but it requires some programming. In the future we are going to redevelop the entire PDF module and there will be a possibility to display contact's image.
