### ISSUE TITLE
Is it possible to add part-payments to Invoices?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4626]
Hi,
in our organisation, sometimes an invoice is not paid in full and instead can be paid in one or more smaller payments. Is there any functionality in Yetiforce that allows us to record part payments of a parent invoice? Also be able to calculate/show the Amount Due (outstanding balance that needs to be paid)?

I don't know whether this is possible by adding a couple more custom fields, or whether there is a built in option/function that provides a better way to achieve this?

Any help would be most appreciated.

**Comment by PercyP** [comment]
Hi,

I think I am close to figuring out how this works - can someone tell me if I have this correct? 

I am trying to mimic the way accounting is done in my copy of Yetiforce to make it easier to produce our end of year accounts. There are 4 modules in Yetiforce that I think I need to use for this:

1. The invoices to produce the invoices for customers
2. The Bookkeeping (Journal?) to record transactions of credits and debits
3. The payments in to record money coming in (income)
4. The payments out to record money going out (expenses)
5. When I create an invoice, and a payment is received, I then create a Bookkeeping (journal transaction) when it is paid in full or part-paid - all payment records including part-paid show up in the Invoice's related record list - so part payments are shown this way - great
6. When invoices are paid I  also create a record in Payments in

My questions are:

a) Is that the correct way to use those 4 modules in terms of recording invoices and payment of invoices?
b) Is there any way, when an associated part payment is made in Bookkeeping (Journal) that the related invoice Payment status value can be automatically updated based on the amount paid - so if bill is paid in full it changes this to Fully paid, likewise, if it has been partially paid, it remains at that status until the full amount has been paid. If this doesn't currently happen (which I don't believe it does) is it something I can achieve using the Workflows or would this mess things up elsewhere?
c) Does adding transactions to the Bookkeeping module and also adding to the Payments In and Out in my example above cause any problems with duplication?

If anyone could advise as to whether I have the correct/incorrect understanding of how these modules work together it would be greatly appreciated.

Kind regards

**Comment by paula-w** [comment]
To calculate the balance in an invoice you can use the Payments In module. The system should automatically calculate the balance - if the clean version of the system doesn’t do that then it’s probably enough to enable this option. The remaining modules aren’t necessary to calculate the balance in the invoice. 
We are going to prepare a detailed description of the bookkeeping process (most likely in several months) once we finish implementing bookkeeping modules for a client.

**Comment by PercyP** [comment]
Hi Paula,

thanks for explaining. I am looking at the Payments In module (in both my instance and the developer version). How does it know to calculate the balance in the invoice? There isn't a 'related invoice' field as far as I can see. I went to the Edit Module and switched on Advanced Module (in mine) and looked in the Advanced fields but there isn't anything other than some empty blocks. I tried to view same area in developer version but it isn't available. 

Exciting news about the bookkeeping module! When is that likely to be available in yetiforce (without instructions)?

**Comment by zelphar** [comment]
want this feature too.
looking forward new update

**Comment by samuelsituma** [comment]
@PercyP Did you get a solution to this issue

**Comment by vovpff** [comment]
@samuelsituma this functionality available in system. You need to add Payment In related to invoice.

**Comment by samuelsituma** [comment]
Thank you so much brother let me check it out

**Comment by dechutvilhur** [comment]
> @samuelsituma this functionality available in system. You need to add Payment In related to invoice.

i added a Payment In lower than Invoice total related to an Invoice, and i got nothing. Can you please show me how it must look like ?

**Comment by paula-w** [comment]
Hello,
Thank you for your email. I’m currently on vacation until the 8th of January.
If your message is urgent, please send an email to ***@***.*** Otherwise, I will get in touch with you once I’m back.
Thank you for your patience.

Dzien dobry,
Dziekuje za wiadomosc. Do 08.01.2024 przebywam na urlopie.
W pilnych sprawach prosze o przeslanie maila na ***@***.*** W przeciwnym wypadku skontaktuje sie z Panstwem po powrocie.
Dziekuje za cierpliwosc.

**Comment by vovpff** [comment]
> > @samuelsituma this functionality available in system. You need to add Payment In related to invoice.
> 
> i added a Payment In lower than Invoice total related to an Invoice, and i got nothing. Can you please show me how it must look like ?

Change Payment In status to Accepted
