### ISSUE TITLE
Additional custom Time Control types do not show in the module's Type filter options

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4627]
![addtype](https://user-images.githubusercontent.com/10598886/28969602-1deac878-791d-11e7-8328-52e8a70fd036.png)
![pickvalues](https://user-images.githubusercontent.com/10598886/28969612-262d98bc-791d-11e7-9f95-92c7149edba4.png)

Hi,

I want to add additional Time Control Types and so added extra values to the Time Control picklist called Public holiday. I then went to the time control module and created a new time control event in the calendar. I selected my new type 'Public holiday' from the Type dropdown and saved the new event.

In the side bar there is a filter box Type. I would expect my new picklick item 'Public holiday to appear here - so I could just view all Public holiday entries. I deselected the option already there, then refreshed, then clicked in the Type box to select my new Public holiday entry, but it doesn't show as an option. Only the default options appear. 

How do I get the new picklist values to show as a filter option in Time Control module?

I have also tested this on the developer version with same outcome.
Kind regards

UPDATE: I HAVE ATTACHED SCREENSHOTS TO SHOW WHERE I MEAN

**Comment by konadrian** [comment]
![bez tytulu1](https://user-images.githubusercontent.com/3193498/29026473-3003c012-7b7c-11e7-9345-8a623b40863b.png)
![bez tytulu2](https://user-images.githubusercontent.com/3193498/29026474-301d1f8a-7b7c-11e7-92ae-a219abcc58ef.png)
Error does't occur on gitdev version
