### ISSUE TITLE
Type::Question calls from the CRM level on mobile phones

### ISSUE THREAD

**Issue by ssstorm** [YetiForceCompany/YetiForceCRM#4647]
Hi, I [asked ](https://github.com/YetiForceCompany/YetiForceCRM/issues/1970) and return to the subject:

calls from crm with mobile possible or not? if yes, have you any manual? I glad to see http://prntscr.com/fxykgw but can't to find more

**Comment by paula-w** [comment]
We no longer support Android modules. We might bring it back someday but it would have to be ordered by a client.
