### ISSUE TITLE
Record owner group in Openstreetmap module?

### ISSUE THREAD

**Issue by technologiegalwaniczne** [YetiForceCompany/YetiForceCRM#4648]
Hi

Is it possible to add grouping by record owner in the openstreetmap view for companies?

![screenshot_1](https://user-images.githubusercontent.com/29600665/28658398-6b7ffa0e-72ab-11e7-8e1b-759ce8c307e7.jpg)

Would appreciate to have this feature.

Best regards
Maciej

* YetiForce Version used: 4.0.49
* Browser name and version: Chrome 59
* Operating System and version:

**Comment by paula-w** [comment]
It would take 4 ~ 8 hours to add it, we can do that when someone purchases the hours needed to add this grouping option.
