### ISSUE TITLE
[BUG] Email Scanner v 1.4

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#466]
Dont Work Folder Email Scanner

It's work
![mailscanner](https://cloud.githubusercontent.com/assets/1402355/6918475/707dcb74-d7c8-11e4-9d18-477dc7061a04.JPG)
It's don't work
![mailscanner2](https://cloud.githubusercontent.com/assets/1402355/6918484/827f81b4-d7c8-11e4-9692-fc870e8508be.JPG)

Approve on test.yetiforce.com

**Comment by witer30** [comment]
i have the same issue. Based on the Yetiforce team with Gmail there is no issue... But not all companies use Gmail...

**Comment by waran70** [comment]
When you setup email account, your FIRST login to mailbox should be done with full email address (not only user name). It should fix the problem

**Comment by waw555** [comment]
In the first screenshot shows that the input I have done, I always prescribe login completely, not only works Folder Configuration, everything else is working.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/administrator-documentation/panel/82-mail-scanner/135-mail-scanner.html

**Comment by waw555** [comment]
I check everything on your test site, in version 1.3.0 did not seem to have that problem

Step 1 (Save config)
![mailsaveconfig](https://cloud.githubusercontent.com/assets/1402355/6971229/6e1f80b6-d994-11e4-9eb5-7f59e01cce49.PNG)


Step 2 (Empty)
![mailblank](https://cloud.githubusercontent.com/assets/1402355/6971234/7655bffc-d994-11e4-823b-b50d5b6201f5.PNG)


Step 3 (Enter)
![mail1](https://cloud.githubusercontent.com/assets/1402355/6971236/7bfbb13c-d994-11e4-85e4-5e64fd9630b4.PNG)


Step 4 (It's Work)
![inmail](https://cloud.githubusercontent.com/assets/1402355/6971244/8515cb5e-d994-11e4-9bf0-ebb2775d43c1.PNG)

Step 5 (It's Work)
![emailaccounts good](https://cloud.githubusercontent.com/assets/1402355/6971252/9baa137a-d994-11e4-862f-d4350d2363e4.PNG)

Step 6 (Add Actions)
![addaction](https://cloud.githubusercontent.com/assets/1402355/6971257/a8ee51e0-d994-11e4-8746-5a6a529ecf97.PNG)

Step 7 (It's Work)
![action](https://cloud.githubusercontent.com/assets/1402355/6971264/b7ca16ea-d994-11e4-99d0-28fbf0a5e1e9.PNG)

Step 8 (Don't Work)
![folder configuration dont work](https://cloud.githubusercontent.com/assets/1402355/6971270/c3e593dc-d994-11e4-92ce-bff74f8cef28.PNG)

Step 9 (It's Work)
![search works](https://cloud.githubusercontent.com/assets/1402355/6971280/d0e7336a-d994-11e4-8268-9b787b1c0cb8.PNG)

Step 10 (It's Work)
![pref works](https://cloud.githubusercontent.com/assets/1402355/6971284/db73214a-d994-11e4-8a40-432e6b882b00.PNG)

**Comment by bpabiszczak** [comment]
I'm not sure how I can help you. If all parameters are set, there should be no problem with roles. Is the problem on your CRM system. Did you test it on our testing website? Unfortunately, I'm afraid we won't be able to help you without receiving access to your system. It is probably a bug that is specific for a certain installation so we charge money for this type of fixes.
