### ISSUE TITLE
How to show related contacts in PDF form

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4666]
Hi,

I have created a custom module that has a primary contact and multiple 1:M related contacts which are added via the Module relationship (related to contacts). When I view a record I can see my additional contacts.

I want to display both the Primary contact and the related contacts on a PDF output. I can easily add the Primary contact and display it, but I am not sure how to add multiple contacts from the related Contacts module. I have created the relationships between the new module and Contacts, but the fields don't appear in the related module list. Is there another step I am missing to get the fields to show up, and if this is possible, will it also allow me to display all the contacts that are related to the record? 

I am not aware of any documentation yet for this - hense asking here.

Kind regards

**Comment by waran70** [comment]
You need to program it. Would be cool indeed to have this option resolved as in PDFMaker (vtiger)

**Comment by PercyP** [comment]
@waran70 

I am just researching on here and see this is being asked for quite a lot - slightly different requests but same thing:

https://github.com/YetiForceCompany/YetiForceCRM/issues/4466
https://github.com/YetiForceCompany/YetiForceCRM/issues/3984

There are a few others. 

The 'Fields from related modules' is miss-leading (for me at least) . I would expect that dropdown to contain fields from the related modules I created i.e. in my case the additional Contacts. I am guessing it refers to the inbuilt Created by, Assigned to etc. 

Like many others, I need to list more than one Contact, Address, Company etc. against a record and be able to print it out using the PDF (rather than a report). 

I am looking at this posted by @mariuszkrzaczkowski in one of the responses: 
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/TextParser/OverdueDeadlines.php

But without documentation I just don't know where to start, where to create the function, where to store it with regards to my custom module etc. etc.

Then, when this 'custom function' is finished, where does it show? would we see some new 'related fields' show up in the pdf's 'Fields from related modules' section? 

I wonder a) if this feature is currently being added (already purchased as custom work from someone else? b) if not, how much it would cost to have it built and c) how many would be willing to support the funding of it?

I have had custom work done bt YF in the past, and also currently having new custom work done, so don't have a lot of funds available just now to fund this solely also, so it would be good if others are interested in donating towards it.

**Comment by PercyP** [comment]
Nobody interested in having this done as custom work? Could Yetiforce tell me how much it would likely cost to have this function built? @paula-w  @mariuszkrzaczkowski @bpabiszczak

**Comment by mariuszkrzaczkowski** [comment]
I added new features to the parser text, the ability to list related records. See here
https://github.com/YetiForceCompany/YetiForceCRM/commit/c5a78668fd098ef59d619ecf6cdeafc2e9a4954f
List all records from the system:
https://github.com/YetiForceCompany/YetiForceCRM/commit/75f2b92c622f9da17e32219f0d60e568e6d9aa17
Here are some examples:
$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]|)$
$(recordsList : Contacts|||All)$
$(recordsList : Contacts)$

parameters: ModuleName|Columns|Conditions|CustomViewIdOrName|Limit

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

WOW! does this mean we can add fields from related modules? If yes, absolutely brilliant it makes a massive difference to what we can do!

Thank you :O)

**Comment by PercyP** [comment]
@waran70 
check out the developer, they have added it for us - looks brill!

**Comment by mariuszkrzaczkowski** [comment]
Yes you can display any field, you can set the filter name or id, you can give your own conditions.
Conditions built by the querygenerator so you can almost every condition to do
$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]|)$
 $(relatedRecordsList : Contacts||[[["firstname","a","Tom"]]]|)$

![image](https://user-images.githubusercontent.com/10198654/29162206-09402a58-7db9-11e7-9b9c-7b22ee755362.png)

List of operators and field types: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/vendor/yetiforce/QueryField

Phone example: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/QueryField/BaseField.php#L178

This gives you great opportunities

**Comment by mariuszkrzaczkowski** [comment]
It works in PDF and email notifications, in email templates

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

so pleased with this, it is what has been missing. Plus there are many extras which I wouldn't have thought of that are also extremely useful - It does give us lots of scope now and gets rid of a massive headache I personally was having. Excellent work and thanks!

**Comment by mariuszkrzaczkowski** [comment]
Adding this mechanism took about 5hours, if someone paid for it earlier it would've been added a long time ago.
Same applies to many other missing features, eg. table with products generated this way.
People don't want to invest in this system, but take advantage of open source instead. 
Think how many amazing things we would have if the community helped with development.

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

I 100% agree! It would be good if more of the community would help towards development costs. I believe in giving back (not just taking) and as soon as I start making money from my idea, will certainly be donating back to this project, as without it, my own ideas could never be brought to life. Sometimes I think people forget that there are a load of very skilled developers sat behind this project (who have to earn a living). I am sure I am not alone in appreciating 100% what you are all doing!

**Comment by aljoflo** [comment]
there is any possibility to add border to the table created in a PDF template of a relatedRecordsList? Currently when I add a related record list on PDF it show the table without border.
