### ISSUE TITLE
"Neglected Accounts"

### ISSUE THREAD

**Issue by joshmans** [YetiForceCompany/YetiForceCRM#4668]
#### Issue
I'm not sure this an "issue" but I can't find documentation on this -- what defines a 'neglected account' and can this definition be adjusted?

#### Actual Behavior
Accounts showing neglected; not real sure what defines this.

#### Expected Behavior
Being able to at least know what defines a neglected account, and modify it if possible.

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: Any
* Environment name and version:
* Operating System and version: Linux

**Comment by konadrian** [comment]
Do you want to know which users show in Neglected Accounts widget?

**Comment by joshmans** [comment]
What I want is to know what criteria deems an account to be 'neglected' (and how to alter this criteria if possible)  We have several accounts which are showing as neglected, but there are active logs going into these for customer contact, etc.

**Comment by technologiegalwaniczne** [comment]
I am also interested in this one. What are the criteria. Where can I set them?
