### ISSUE TITLE
[DISCUSSION] Document preview (.PDF, image)

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4672]
Being able to preview documents directly in the browser is essential, rather than having to download them. Vtiger 7 has built-in document preview .pdf, image format. Use the jquery library ViewerJS, pdf.js to do just that. Does Yetiforce plan to integrate this feature in 4.1?

**Comment by mariuszkrzaczkowski** [comment]
Vtiger 7 sends the document to a foreign server and then displays it is it safe?
Interesting idea, if someone pay it we will add
