### ISSUE TITLE
[BUG] Date range picker not working properly ver. 4.0.527

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4673]
![nh ch p man hinh 26](https://user-images.githubusercontent.com/19627226/28754580-675c1e16-7572-11e7-9200-18d7abdd4d2e.png)
It also does not work properly in modules such as reports, filters, workflows.
Tested on Chrome.

**Comment by ezbank** [comment]
Error still existing v4.1.44
![1121](https://user-images.githubusercontent.com/19627226/28874197-fd58b2a4-77ba-11e7-84e4-274563a87870.gif)

**Comment by mariuszkrzaczkowski** [comment]
This is a new error, because it occurs elsewhere.
 Add new issues
