### ISSUE TITLE
Field Mask does not work correctly

### ISSUE THREAD

**Issue by varlog11** [YetiForceCompany/YetiForceCRM#4674]
![animation](https://user-images.githubusercontent.com/1807261/28763419-f4bd6e52-75ce-11e7-8667-6afbc6c6b586.gif)

#### Issue
Field Mask does not work correctly

#### Your Environment
* YetiForce Version used: 4.0.530
* Browser name and version: Google Chrome 59.0.3071.115

**Comment by konadrian** [comment]
Fixed by 700376d5cce921691a8d8c64a161d46a3d7c7f4b
