### ISSUE TITLE
PDF Reports Language

### ISSUE THREAD

**Issue by visitekasia** [YetiForceCompany/YetiForceCRM#4675]
Hi, how can I change the language for all reports in PDF?
Everytime I generate the reports to PDF, the language used on that report is using PL or DE (Not sure which language).
How can I change it to English?

![image](https://user-images.githubusercontent.com/28915574/28765425-e4ca2640-75f4-11e7-9611-0b92bd7875e6.png)

Regards,
Nando

**Comment by PercyP** [comment]
Im not sure but think you have to change the pdfs manually?

**Comment by skramanzia** [comment]
Hi @visitekasia You can change PDF structure in this module

https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35

 Do you use stable version?Whats is your language? please check in this module

https://gitdeveloper.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=4&fieldid=53

**Comment by visitekasia** [comment]
Dear @skramanzia 
I am using the stable version of v4.0.0
The default language used in Language Management is English.
Only the PDFs which is not using English.
Thanks for the reply, the problem now is that I need to change all the PDFs format and language one by one.

Regards,
Nando

**Comment by konadrian** [comment]
You are using templates bult in yetiforce if yes pleasegive templates id. If you using your own templates show template code

**Comment by visitekasia** [comment]
Dear @konadrian 
I'm not using any templates, I leave it as it is (so it's default template).
What is the template ID? How can I retrieve the template ID or Code?

![image](https://user-images.githubusercontent.com/28915574/29057040-977df1ee-7c31-11e7-8523-cc62ec5a5a91.png)

Regards,
Nando

**Comment by konadrian** [comment]
Edit, your img and mark which pdf's you are use

**Comment by visitekasia** [comment]
Dear @konadrian 
The very first image that I posted here is the sales order report.

Regards,
Nando

**Comment by konadrian** [comment]
Can you show screens or create a gif with your problem. I'm not sure I understand it correctly
