### ISSUE TITLE
Currency symbol on PDF quotation

### ISSUE THREAD

**Issue by technologiegalwaniczne** [YetiForceCompany/YetiForceCRM#4678]
I am in the middle of a quotation facelift process and would like to ask for help.
In general I've started to modify the ProductsTableNew.php file to suite my needs and this is the result I have achieved: 

![screenshot_4](https://user-images.githubusercontent.com/29600665/28769729-f0536c00-75dc-11e7-9dbb-562113903b44.jpg)

To make the quotation more clear to the customer I would like to have the currency symbol next to the ammount. I am pretty sure that I shoud add some code after the line: 
 $html .= $field->getDisplayValue($itemValue);
but  unfortunatelly don't know what. 

Please help

Best regards
Maciej

YetiForce Version used: 4.0.49
Browser name and version: Chrome 59
Operating System and version:

**Comment by alextovey** [comment]
Would like to know this too. Would be very handy to know

**Comment by konadrian** [comment]
Here you have example how currency sign is created and used, it's enout to put it in the correct place
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/TextParser/ProductsTable.php#L47
