### ISSUE TITLE
Product photo on PDF quotation

### ISSUE THREAD

**Issue by technologiegalwaniczne** [YetiForceCompany/YetiForceCRM#4679]
I am in the middle of a quotation facelift process and would like to ask for help.
In general I've started to modify the ProductsTableNew.php file to suite my needs and this is the result I have achieved: 

![screenshot_4](https://user-images.githubusercontent.com/29600665/28769750-0835b044-75dd-11e7-9687-590a1a3fe856.jpg)

To make the quotation better looking I would like to have the product photo in a column next to the product description.

I believe it is not a big problem but I am not really a programmer to fix this on my own.

Best regards
Maciej

YetiForce Version used: 4.0.49
Browser name and version: Chrome 59
Operating System and version: Debian Stretch

**Comment by cltvchannel** [comment]
Hello.
Can you give me the code of your template?
It's look great.
Thanks !

**Comment by technologiegalwaniczne** [comment]
Hi
No problem but you have to modify the  ProductsTableNew.php to get the colors and horizontal line to the PDF.

`<?xml version="1.0" encoding="utf-8"?>
<pdf_template>
  <fields>
    <field>
      <module_name>SQuotes</module_name>
      <status>1</status>
      <primary_name>Oferty</primary_name>
      <secondary_name>*</secondary_name>
      <meta_author/>
      <meta_creator/>
      <meta_keywords/>
      <metatags_status>1</metatags_status>
      <meta_subject/>
      <meta_title/>
      <page_format>A4</page_format>
      <margin_chkbox>1</margin_chkbox>
      <margin_top>0</margin_top>
      <margin_bottom>0</margin_bottom>
      <margin_left>0</margin_left>
      <margin_right>0</margin_right>
      <header_height>0</header_height>
      <footer_height>0</footer_height>
      <page_orientation>PLL_PORTRAIT</page_orientation>
      <language>pl_pl</language>
      <filename>oferty</filename>
      <visibility>PLL_LISTVIEW,PLL_DETAILVIEW</visibility>
      <header_content><![CDATA[<div>$(organization : mailLogo)$ Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â </div>

<div style="text-align:right;"><strong><span style="color:#6699cc;"><span style="font-family:Tahoma, Geneva, sans-serif;"><span style="font-size:36px;">Oferta</span></span></span></strong></div>
]]></header_content>
      <body_content><![CDATA[<div style="text-align:right;"><br><br><br><br><span style="font-size:12px;"><span style="font-family:Arial, Helvetica, sans-serif;"><span style="line-height:20.8px;text-align:right;">Oferta nr</span><span style="line-height:20.8px;text-align:right;"> </span>$(record : RecordId)$<span style="line-height:20.8px;text-align:right;">Â waĹĽna do: $(record : valid_until)$</span></span></span></div>

<div style="text-align:right;"><span style="font-size:12px;"><span style="font-family:Arial, Helvetica, sans-serif;"><span style="text-align:right;">Oferta przygotowana przez:Â $(record : assigned_user_id)$</span></span></span></div>

<div style="text-align:center;">Â </div>

<div><span style="font-size:14px;"><span style="font-family:Arial, Helvetica, sans-serif;"><strong>Technologie Galwaniczne Sp. z o.o.</strong><br>
ul. Lodowa 101<br>
93-232 ĹĂłdĹş<br>
Tel: +48 42 647 09 01<br>
Fax: +48 42 647 09 16<br>
e-mail: tegal@tegal.pl</span></span><br>
Â </div>

<div style="text-align:right;"><span style="font-family:Tahoma, Geneva, sans-serif;">Oferta przygotowana dla:</span><br><span><span style="font-size:14px;"><span style="font-family:Arial, Helvetica, sans-serif;"><strong>$(record : accountid)$</strong><br>
$(record : addresslevel8a)$<br>
$(record : addresslevel7a)$Â $(record : addresslevel5a)$</span></span></span><br><br><span style="font-family:Tahoma, Geneva, sans-serif;">$(custom : ProductsTableNew)$</span><br><br><br><span style="font-family:Tahoma, Geneva, sans-serif;"><span style="font-size:12px;">W przypadku pytaĹ„ dotyczÄ…cych tej oferty proszÄ™ o kontakt</span>:<span style="font-size:12px;"><b>Â $(reletedRecord : assigned_user_id|email1|Users)$</b></span></span></div>

<div>Â </div>
]]></body_content>
      <footer_content><![CDATA[]]></footer_content>
      <conditions><![CDATA[[]]]></conditions>
      <default>1</default>
      <watermark_type>0</watermark_type>
      <watermark_text/>
      <watermark_size>0</watermark_size>
      <watermark_angle>0</watermark_angle>
      <template_members>Roles:H2,Roles:H38,RoleAndSubordinates:H2,RoleAndSubordinates:H10</template_members>
      <watermark_image/>
      <one_pdf/>
    </field>
  </fields>
</pdf_template>
`

**Comment by KatarzynaUlichnowska** [comment]
This modification requires programming. We can do it, but we will need to charge money for it.
