### ISSUE TITLE
Invalid username or password.

### ISSUE THREAD

**Issue by valcach** [YetiForceCompany/YetiForceCRM#4681]
#### Issue
can you help me

The user and the password does not work

How can I solve this?

what am I doing wrong

URL: https://ycrm.valcach.com.au/index.php
Username: admin
Password: 6$K$%$%YKAsgwv

Thank you

#### Actual Behavior
I uninstalled the current Yetiforce application and tried two more installs. 

One was done through cPanel > Softaculous again and another was done manually after downloading the latest version of Yetiforce from their site, uploading and extracting it, and following their manual installation steps.

Unfortunately they both had the same issue. I can see the admin user exists in the database in the vtiger_users table, but it never accepts the password on the login page.

For reference, here is the new user and admin that was set with the latest install, although it does not work:

URL: https://ycrm.valcach.com.au/index.php
Username: admin
Password: 6$K$%$%YKAsgwv

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.0.0
* Browser name and version:Chrome
* Environment name and version:Softaculos
* Operating System and version:

**Comment by skramanzia** [comment]
Please update information of close the ticket, 
![image](https://user-images.githubusercontent.com/3030997/28793063-25b1e78e-7608-11e7-8497-88b6b5324c45.png)

Its a server requirement issue, please check this link https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html

**Comment by konadrian** [comment]
https://yetiforce.com/en/administrator-documentation/errors/227-apache-500-internal-server-error-2.html
