### ISSUE TITLE
Front End API - QUESTION

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4688]
Hi Team, i need to create a new Front End to some users. Does YF use some api and do you have manuals or reference?
 I had try to configure "Web Service - Users" But cant see "Server"

![image](https://user-images.githubusercontent.com/3030997/28787957-bd8b2ff2-75f4-11e7-8b32-8b4f1460bd0d.png)

**Comment by skramanzia** [comment]
Hi @paula-w sorry for invoke you. Do you hace any manual or documentation of YetiForce API?

thanks

**Comment by mariuszkrzaczkowski** [comment]
look here
https://gitdeveloper.yetiforce.com/index.php?module=WebserviceApps&view=Index&parent=Settings&block=5&fieldid=100

**Comment by skramanzia** [comment]
@mariuszkrzaczkowski Thanks you, do you have some examples or documentation to how to use YF API?

**Comment by mariuszkrzaczkowski** [comment]
We do not have yet,
Here is a description of how to use it
https://github.com/YetiForceCompany/YetiForceCRM/issues/4163
https://github.com/YetiForceCompany/YetiForceCRM/issues/4023

**Comment by skramanzia** [comment]
@mariuszkrzaczkowski Thanks!!
