### ISSUE TITLE
Opportinities Filter/Search It does not work

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4690]
![gif](https://user-images.githubusercontent.com/3030997/28792280-723e827c-7605-11e7-9d47-8f233ba599de.gif)

**Comment by mariuszkrzaczkowski** [comment]
The error does not exist in the latest version

**Comment by skramanzia** [comment]
Hello @mariuszkrzaczkowski, i checked in current DEV ver. 4.1.0 at this moment and the error still occurred

**Comment by mariuszkrzaczkowski** [comment]
Are you sure I'm testing and it works.
What browser?

**Comment by skramanzia** [comment]
Yes, latest Chrome and this screen in new fresh firefox.

![untitled1](https://user-images.githubusercontent.com/3030997/28794965-93a15760-760e-11e7-8a75-1acb98fa0cc0.gif)

**Comment by SkavenKF** [comment]
same for me (gitdev 4.1.0) ff/chrome

**Comment by ezbank** [comment]
me too. safari/firefox/chrome/egde

**Comment by rskrzypczak** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/763ce1a3f89413b914c0f0146b3fa3267b2e0d0d
