### ISSUE TITLE
manual triggering workflow - php error

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#4691]
#### Issue
There is an php error during manual triggering workflow on sales opportunities.

#### Actual Behavior
I click "+" button in right up corner to trigger workflow. There is no effect, but in php logs I can see:

[31-Jul-2017 23:49:33 Europe/Sarajevo] PHP Fatal error:  Uncaught Error: Call to undefined method VTEntityCache::get() in /home/***/public_html/crm/modules/com_vtiger_workflow/VTJsonCondition.php:142
Stack trace:
#0 /home/***/public_html/crm/modules/com_vtiger_workflow/VTJsonCondition.php(36): VTJsonCondition->checkCondition(Object(VTEntityCache), Array)
#1 /home/***/public_html/crm/modules/com_vtiger_workflow/VTWorkflowManager.php(352): VTJsonCondition->evaluate('[{"fieldname":"...', Object(VTEntityCache))
#2 /home/***/public_html/crm/modules/Vtiger/views/WorkflowTrigger.php(42): Workflow->evaluate(Object(VTEntityCache), '68x9125')
#3 /home/***/public_html/crm/include/main/WebUI.php(218): Vtiger_WorkflowTrigger_View->process(Object(Vtiger_Request))
#4 /home/***/public_html/crm/index.php(21): Vtiger_WebUI->process(Object(Vtiger_Request))
#5 {main}
  thrown in /home/***/public_html/crm/modules/com_vtiger_workflow/VTJsonCondition.php on line 142

#### Expected Behavior
Triggering workflow.

#### How to trigger the error

1. Go to sales opportinity - details
2. Click "+" in right up corner to manually trigger workflow

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: IE, FF
* Environment name and version: PHP 7.0
* Operating System and version: Win10

**Comment by mariuszkrzaczkowski** [comment]
Check in developer version

**Comment by pflaz** [comment]
In 4.1.0 it works fine, thanks :)
