### ISSUE TITLE
Znikające wpisy urlopowe w kalendarzu

### ISSUE THREAD

**Issue by RobertBartczak** [YetiForceCompany/YetiForceCRM#4692]
Czemu po raportowaniu urlopu w ramach czasu pracy wpisy znikają z kalendarza?
Po wpisaniu urlopu mam widok jak poniżej:
https://user-images.githubusercontent.com/26707513/28813405-6acc4206-7699-11e7-833b-def35a535fbb.png
Ale po odświeżeniu strony część wpisów znika:
https://user-images.githubusercontent.com/26707513/28813543-edcef432-7699-11e7-816d-d3ebd0f79b01.png
przykład 2:
https://user-images.githubusercontent.com/26707513/28813815-2a288c94-769b-11e7-9e5a-35a3197eb47b.png
A po odświeżeniu:
https://user-images.githubusercontent.com/26707513/28813846-4c705408-769b-11e7-8d5c-f9a1e2d84a59.png

**Comment by waran70** [comment]
Why ticket has been closed?

**Comment by bpabiszczak** [comment]
Wrong place. This is internal issue.
