### ISSUE TITLE
incorrect export import via csv format

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#47]
Trying export and import fileds from modules to another instance I saw a problem in transport data via csv format expecially with description fields where is a data in html format. In consequence import of this data couses  duplicate fields. reading this export file for example in Open Office is possible without errors. 
Suggested improving import export mechanism.

**Comment by bpabiszczak** [comment]
Unfortunately, CSV import/export isn’t perfect. It is necessary to remember to format data properly before the actual import. Libreoffice does it very well and saves signs like " as appropriate codes what helps to avoid problems. If encoding and format of files is done properly, import works all right and in our opinion nothing needs to be fixed here at the moment.
