### ISSUE TITLE
Need Translate

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4705]
Current Dev Version 4.1.16

![image](https://user-images.githubusercontent.com/3030997/28825869-4d371036-769e-11e7-8c0b-6871cb6249db.png)

**Comment by mariuszkrzaczkowski** [comment]
What language ?

**Comment by skramanzia** [comment]
English

**Comment by ezbank** [comment]
Same as me

**Comment by SkavenKF** [comment]
same in german

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/9e41d45c04fa26ef8f048bf36b7c3244761a8c0d
https://github.com/YetiForceCompany/YetiForceCRM/commit/f7440d2b8bdf531a61202928102a178084fc4fad
