### ISSUE TITLE
Loop Next Page - Error

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4710]
#### Issue

![loop](https://user-images.githubusercontent.com/3030997/28839971-c4ca5400-76cb-11e7-9233-41040b82c278.gif)

Loop when click in next page, in OP module and custom module in currect Dev 4.1.25 and after update to 4.1.
 
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/4690
https://github.com/YetiForceCompany/YetiForceCRM/issues/4689
https://github.com/YetiForceCompany/YetiForceCRM/issues/4673
