### ISSUE TITLE
Git developer version not working

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4711]
Hi,

just to let you know the gitdeveloper version of yetiforce is not allowing logins. I t produces the following errors:

Warning: session_destroy(): Cannot call session save handler in a recursive manner in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/Session/Base.php on line 104

Warning: session_destroy(): Session object destruction failed in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/Session/Base.php on line 104

Warning: session_regenerate_id(): Session object destruction failed. ID: user (path: /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/cache/session) in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/Session/Base.php on line 90

Warning: Cannot modify header information - headers already sent by (output started at /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/Session/Base.php:104) in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Users/actions/Login.php on line 69

Kind regards

**Comment by mariuszkrzaczkowski** [comment]
Fixed
