### ISSUE TITLE
[bug] gitstable not working

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#4713]
#### Issue

![grafik](https://user-images.githubusercontent.com/10259801/28861611-ed6cbcea-7761-11e7-8cc3-6b0d5f533a36.png)

#### Actual Behavior

![grafik](https://user-images.githubusercontent.com/10259801/28861585-d3e43a82-7761-11e7-8d99-594ad22bbbd8.png)

#### How to trigger the error

1. go to https://gitstable.yetiforce.com
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Fixed
