### ISSUE TITLE
[bug] gitmaster not working

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#4714]
#### Issue

Server gitmaster not found

![grafik](https://user-images.githubusercontent.com/10259801/28861748-7c40d73a-7762-11e7-8f3c-a6e422607c90.png)

#### Actual Behavior

Server gitmaster not found

#### How to trigger the error

1. got ot https://gitmaster.yetiforce.com
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Gitmaster was removed because it is not needed
