### ISSUE TITLE
XLS or CSV Export Format

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4720]
#### Issue

When i export report to xls or csv the field have not format and cant perform  =SUM or any operation with numbers. I was need to change field format to Number or currency for example

#### Actual Behavior

![image](https://user-images.githubusercontent.com/3030997/28878312-43b25b74-7775-11e7-8f26-6896268188d6.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.1.52 and olders
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
We're not planning to change that right now, it would have to be ordered by a client, and we don't know when that will happen.
