### ISSUE TITLE
[questions] @YF about the release 4.1.0

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#4721]
@mariuszkrzaczkowski 
I'm a little irritated again.
Is there an official announcement to 4.1.0 release?
You named the actual release "YetiForce CRM 4.0.0 LTS + Service Pack 1", the version number is 4.1.0. What is correct? (x.1.x is Service Pack Number?) 
And when this is the SP1 for the LTS version, where is the developer version for the next stable release? 
Next question, what is the difference between stable and master?
And the last question, before you create a new version, you also make integration tests? 

I hope you can create a little for clarity 😃 Thanks.

**Comment by PercyP** [comment]
Hi @SkavenKF 

has 4.1 been released? I see it has disappeared from the milestones. Where have you read about it?

Kind regards

**Comment by PercyP** [comment]
I just found it. There is a file in there called 4.0.0_to_4.1.0_v1.zip maybe that is the the update? 
https://github.com/YetiForceCompany/YetiForceCRM/releases

What package in that section would we use to update?

**Comment by SkavenKF** [comment]
look at releases 😄 
![grafik](https://user-images.githubusercontent.com/10259801/28891000-4cdcb394-77c9-11e7-8bc4-1ed0829136e9.png)

**Comment by PercyP** [comment]
Hi,

which of these files do we use to update? Is it the zip? I am on version 4.0 at the moment.

Thanks in advance

**Comment by SkavenKF** [comment]
Answer to: "Next question, what is the difference between stable and master?"
=> see #4714  "it is not needed"

**Comment by PercyP** [comment]
@SkavenKF 

I am not sure what you mean here? I only want to know a) if this is an update that we should install, if so, which file is used for update.

**Comment by SkavenKF** [comment]
@PercyP 
you must use the 4.0.0 to 4.1.0_v1 zip
But i would recommend you **not** to change to 4.1.0. you can test with https://gitstable.yetiforce.com
For me are still too many critical errors, example #4690

**Comment by PercyP** [comment]
@SkavenKF 

thanks. I will give it a go on a test site, as I have a lot of customisations so things are more likely to go wrong

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/4842
