### ISSUE TITLE
how i can install the customer portal at whmcs? English

### ISSUE THREAD

**Issue by densousuds** [YetiForceCompany/YetiForceCRM#4722]
#### Issue

Hello community, i'm trying to install the customer portal in my WHMCS, i follow the steps to the link of documentation on official site "https://yetiforce.com/en/implementer/installation-updates/129-customer-portal-instalation.html" but, i can't do it because when the system send an email to me i don't receive the password to autenticate.

#### Expected Behavior

I need to do works fine the customer portal. What is the customer portal working on yetiforce4.0?

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: Chrome v.59.0.307
* Environment name and version: PHP7.0
* Operating System and version: CloudLinux Centos

**Comment by konadrian** [comment]
We don't support portal 1, the article how to use portal2 will be posted soon on our blog/webpage. Portal2 is still in progress. For portal2 you must create record in portal integration
https://gitdeveloper.yetiforce.com/index.php?module=WebserviceApps&view=Index&parent=Settings&block=5&fieldid=100
https://gitdeveloper.yetiforce.com/index.php?module=WebserviceUsers&view=List&parent=Settings&block=5&fieldid=106
