### ISSUE TITLE
[En]Problem with MailScan setting

### ISSUE THREAD

**Issue by frankhzp** [YetiForceCompany/YetiForceCRM#4723]
#### How to trigger the error

1.  error " ERR_INCORRECT_ACCESS_DATA" displayed when configure mailscan.
2.
3.
![1](https://user-images.githubusercontent.com/28562781/28913530-f4e0ee2e-786a-11e7-869b-1637d0fdfb9b.png)

![2](https://user-images.githubusercontent.com/28562781/28913535-fbd06d68-786a-11e7-8b38-1059fb8daabc.png)

#### Your Environment

* YetiForce Version used:  4.1.0
* Browser name and version: Chrome 61
* Environment name and version:  Xampp 7.1.4
* Operating System and version: windowa 10

**Comment by konadrian** [comment]
Could you please prepare a gif or paste a screenshot that would explain how you trigger this error? We need more info.

**Comment by frankhzp** [comment]
added two snapshots .please check.

**Comment by joelbcampos** [comment]
I have the same problem I have even installed the module again and it remains the same.

**Comment by konadrian** [comment]
Can you trigger this error on gitdeveloper version, for me works fine
![bez tytulu](https://user-images.githubusercontent.com/3193498/28957003-2d697362-78f0-11e7-8fff-5bc30e4d4343.png)

**Comment by frankhzp** [comment]
yes, same issue on version 4.1.71. Maybe it is ok with Gmail ,I didn't try Gmail. 
in version 4.0.0 ,it worked well with my mail box.

![434444](https://user-images.githubusercontent.com/28562781/28957169-5a2bf59a-7923-11e7-9edb-d1216cf8cba2.png)

**Comment by konadrian** [comment]
ERR_INCORRECT_ACCESS_DATA means that someone change password or haven't access do mail account. First check your password and next logs

**Comment by frankhzp** [comment]
But I can check emails without any problem. so I am sure it is not because of the password.

**Comment by konadrian** [comment]
As I said check your logs we need more info
