### ISSUE TITLE
Update bug#1 - Logo folder and some stuff is missed

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4730]
#### Issue

I tried to update from 4.0.0 to 4.1.0 and have found some bugs

#### Actual Behavior

After successful update all uploaded logos and pictures became missed

![image](https://user-images.githubusercontent.com/8545791/28922661-bd377a94-7863-11e7-9088-3383ffda0ebb.png)

![image](https://user-images.githubusercontent.com/8545791/28922684-d3492238-7863-11e7-83f7-0ec94b578b3b.png)

![image](https://user-images.githubusercontent.com/8545791/28922711-ed30b742-7863-11e7-93bb-cd43ea2dbe40.png)

storage/Logo folder is missed
layouts/basic/skins/icons folder moved to public_html folder but customized svg icons for menu was removed without notification.

#### Expected Behavior

All stuff must be moved and links to files must be raplaced

#### How to trigger the error

Update from 4.0.0 to 4.1.0

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Fixed in 4.0.0_to_4.1.0_v2.zip, thanks for finding fault
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.1.0

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I checked your update. The same situation. My custom logos became missed. What I can do with this?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I copied manually  logos and user icons from my 4.0.0 mirror and all stuff works. I think Logo and Icons folders must be copied to new destination and not be deleted as at v2 update package

**Comment by mariuszkrzaczkowski** [comment]
Report each error separately

**Comment by mariuszkrzaczkowski** [comment]
Improved log copying
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.1.0
