### ISSUE TITLE
Roundcube Login

### ISSUE THREAD

**Issue by UPSduck** [YetiForceCompany/YetiForceCRM#4734]
#### Issue

Logging into Mail via "my mailbox" module does not seem to be working. I setup mail configurations and received the "confirmation email" so I know mail is going out. 

#### Actual Behavior
Via "my mailbox" module mail login, it gets stuck loading and become unresponsive rather then logging in. 

I am using YF 4.0.0 within Chrome on a windows machine. 

When checking Logs under roundcube engine I found:

> **Checking available databases**
> Check which of the supported extensions are installed. At least one of them is required.
> OK - MySQL 
> OK - PostgreSQL 
> OK - SQLite 
> ERROR - SQLite (v2) | | http://www.php.net/manual/en/ref.pdo-sqlite.php
> ERROR - SQL Server (SQLSRV) | | http://www.php.net/manual/en/ref.pdo-sqlsrv.php
> ERROR - SQL Server (DBLIB) | | http://www.php.net/manual/en/ref.pdo-dblib.php
> 
> **Check for required 3rd party libs**
> This also checks if the include path is set correctly.
> OK - PEAR
> ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
> ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
> ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime

My best guess is the third party libs (or lack there of) are causing a problem. How do I remedy this?

**Comment by paula-w** [comment]
We're currently using version 4.2 and it works properly for us and our clients. To eliminate the problem with the configuration you should test it on the [gitdeveloper](https://gitdeveloper.yetiforce.com/index.php#) version using some test email, you can remove it after that. 
Unfortunately, you have to change the configuration to get rid of  Net_SMTP, IDNA2, and mime errors
