### ISSUE TITLE
send sms button

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#4735]
#### Issue

How can I send sms to only one record (i.e. from record view)?

#### Actual Behavior
I can send sms as mass sms sending.

#### Expected Behavior
I would like to see 'send sms' button in record view.

#### Your Environment

* YetiForce Version used: 4.1.0
* Browser name and version: IE, FF
* Environment name and version: PHP 7.0
* Operating System and version: Win10

**Comment by paula-w** [comment]
Right now sending SMS works from record list view only. In the future we are going to expand this mechanism and add more options to send SMS, but we don’t know when exactly; most likely when a client orders further development of that feature.
