### ISSUE TITLE
php warnings

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#4736]
#### Issue
After update to 4.1.0 I noticed php warnings in logs - during normally using system.

[03-Aug-2017 23:18:50 Europe/Sarajevo] PHP Warning:  Invalid argument supplied for foreach() in /home/***/public_html/crm/vendor/yetiforce/Field.php on line 185

#### How to trigger the error

1. Open an account (index.php?module=Accounts&view=Detail&record=112)
2. Open phpError.log

#### Your Environment

* YetiForce Version used: 4.1.0
* Browser name and version: IE, FF
* Environment name and version: PHP 7.0
* Operating System and version: Win10

**Comment by konadrian** [comment]
In current version error does't occur

**Comment by pflaz** [comment]
What file should I update?
I have 4.1.0 version and error occurs.

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/milestones
Update package will be next week

**Comment by pflaz** [comment]
unfortunatelly I have updated to 4.2.0 version and the errors still occurs when I open account's details :/

[14-Aug-2017 19:30:36 Europe/Sarajevo] PHP Warning:  Invalid argument supplied for foreach() in /home/***/public_html/crm/vendor/yetiforce/Field.php on line 185

**Comment by mariuszkrzaczkowski** [comment]
The error does not occur in a clean installation. You will need to give more details about your custom changes. Without that we can not help

**Comment by mariuszkrzaczkowski** [comment]
Have you added any reference fields?
