### ISSUE TITLE
An open modal window does not disappear by clicking in its area

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [YetiForceCompany/YetiForceCRM#4737]
#### Issue
An open modal window (quick creation, chat, notification ...) does not disappear by clicking in its area
It is very uncomfortable. They layered on each other. And overlap the working area.

#### Your Environment

* YetiForce Version used: 4.1
* Browser name and version: Chrome last
* Environment name and version: PHP 7.1
* Operating System and version: Win10

**Comment by mariuszkrzaczkowski** [comment]
Check parameter https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/config.template.php#L183

**Comment by Pomazan-Bogdan** [comment]
After the installation of this file there,
But these parameters are in the file config.inc.php

// Enable closing of mondal window by clicking on the background
$backgroundClosingModal = true;

**Comment by Pomazan-Bogdan** [comment]
https://youtu.be/Oe_v0eCO0EQ

**Comment by KatarzynaUlichnowska** [comment]
It was designed this way. In practical terms, it doesn't matter whether clicking outside the area closes the element or not. This can be added, but it is low priority, especially because in a few weeks, we are starting to rebuild the entire system interface in order for it to be more intuitive.
