### ISSUE TITLE
Ability to set which contact field an address is copied from

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4745]
I have a custom module which requires 3 contact types so I have 3 1:M fields linked to Contact module. 

In my first Custom Block I have 'Primary contact' 1M field followed by address fields (addresslevel1a, addresslevel5a etc. 

When I select a Primary contact, then select Copy it copies the address fields for that contact in to my address fields in the custom module - exactly how I want it to work!

In my second Custom Block I have Secondary contact 1:M field linked to Contact module, and a third Custom Block  for a 3rd contact type. 

The Copy From Contact address function only works on the last contact 1:M field. It seems to have some ordering criteria built in, to select the address details based on the Contact field in the last position within my module. It isn't the order created, but the order the field sits in the actual module - if I move the first field 'Primary contact' in to the third custom block it will populate the address fields with that contact's details. 

Is there any way of achieving the following:

Tell the address field to use the related details from the contact field above it or in the first position?
Or
Tell the address fields to use the 1:M contact field in the block the address is actually contained in?

Ideally it would be good to be able to create Custom blocks each with the ability to add related Contact and Address fields that use the Copy from Contact (or another module with address as desired). 

The reason I am trying to add the related contacts to the actual module (and not using the Related Module function is because I need to be able to include the related contact details in a PDF and the PDF does not allow us to add related modules (the only related module fields that can be selected in the PDF are those built in fields that are created when a custom module is created i.e. Assigned to etc.)

I have asked questions related to this in a number of posts, and here are some related:
 
https://github.com/YetiForceCompany/YetiForceCRM/issues/4666
https://github.com/YetiForceCompany/YetiForceCRM/issues/4664 
https://github.com/YetiForceCompany/YetiForceCRM/issues/3984

Is it incorrect to try and have more than 1 contact 1:M field and address fields in a single module? If it is, then will the PDF maker ever have the functionality to include related module details? It appears crucial it should have this.

Kind regards

**Comment by alextovey** [comment]
That would be great if possible. I know i struggle with this. instead of just copying from one source maybe a drop down select address from...

**Comment by paula-w** [comment]
The system is not handling these situations very well currently because if we have several contacts then the relation should be different. Of course people often add many fields of the same type to one module, but it has to be handled by a programmer in these cases. 
Unfortunately, we have no useful advice, it has to be handled from the programming perspective,
