### ISSUE TITLE
Notification status became read automatically 

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4746]
#### Issue

In new 4.1.0 version every notification became "read" after about 20-25 minutes without accepting them in notification bar. 

#### Actual Behavior

If notification arrives after 20-25 minutes this notification became read without confirmation and dissapears from notification bar.

#### Expected Behavior

Notification must be confirmed to became read. All notification must be stored for a long time. For example if user at businesses trip.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
What about this bug? Or this is feature?

**Comment by vovpff** [comment]
@konadrian what cronjob I must check? I use nly standart cron without any customisation.

**Comment by konadrian** [comment]
It's cron to sending notofications via email - Send notifications, number 13 on https://gitdeveloper.yetiforce.com/index.php?module=CronTasks&parent=Settings&view=List&block=15&fieldid=26

**Comment by vovpff** [comment]
@konadrian what I can check?
![image](https://user-images.githubusercontent.com/8545791/29084365-70bd01e2-7c74-11e7-8e19-7e74bfda93a8.png)
this cronjob active

**Comment by mariuszkrzaczkowski** [comment]
Have you set up smtp?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski Yes. Email notification works correct but notifications inside CRM became read.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski any ideas?
