### ISSUE TITLE
error mail escaner ERR_INCORRECT_ACCESS_DATA

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#4748]
<span lang="en" xml:lang="en"><span>Good morning.</span><br /><br /><span>I have reinstalled the module but it does not let me create the folders, it does not search in emailscaner.</span><br /><span>The mails do not link them to the crm.</span><br /><span>But the stmp configuration is correct as it receives and sends correctly.</span></span> <br /><hr />Generado por YetiforceCRM ver. 4.0.0<br />PHP: 5.6.31<br /><br /><strong>Errores de configuración del servidor:</strong><br />innodb_lock_wait_timeout: 50<br /><strong>Errores de librerías:</strong><br />apcu<br />

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/4723
