### ISSUE TITLE
calendar import

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#4750]
#### Issue
Is it possible to import calendar events linked to accounts, opportunities etc?

#### Actual Behavior
I have tried:
1. export some of events from YF to ical format but there is no links to accounts or opportunities
2. import csv file to YF calendar but there is no form to match fields from csv to YF fields

#### Expected Behavior

Import events (I have exported to csv from my current crm) to YF calendar - linked to accounts and opportunities.

#### Your Environment

* YetiForce Version used: 4.1.0
* Browser name and version: IE, FF
* Environment name and version: PHP 7.0
* Operating System and version: Win10

**Comment by vovpff** [comment]
try add to adress index.php?module=Calendar&view=Import but I'm not sure

**Comment by pflaz** [comment]
Thanks, @vovpff , but this way there is the same effect as go to Calendar -> List of records -> Actions -> Import. I can put csv file, but there is no possibility to match columns to YF fields. So the result is - 0 records imported :(

**Comment by paula-w** [comment]
Currently, it's not possible to mass import records into the calendar. We recommend CalDAV integration.
