### ISSUE TITLE
[bug] Tree manager not showing folders

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#4757]
![folder](https://user-images.githubusercontent.com/10330264/28979844-0ac8a83c-7954-11e7-9213-4999317e21fb.png)

#### Your Environment

* YetiForce Version used: 4.1.0 - 4.1.80
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by pflaz** [comment]
I have the same problem in Firefox (after update to 4.1.0). In IE works good.

**Comment by konadrian** [comment]
@kpaulaha Can you occur this error on gitdeveloper, for me works fine 
![bez tytulu](https://user-images.githubusercontent.com/3193498/29001432-acaa2a22-7a8a-11e7-83c8-f68063f17e87.png)

**Comment by kpaulaha** [comment]
Well, firefox seems to be is the one with which it's not working, works with other browsers.

**Comment by pflaz** [comment]
It seems in Firefox no trees as diplayed... In developer version as well:
![yf-loading](https://user-images.githubusercontent.com/29442233/29015823-ee578652-7b4f-11e7-84d7-547aa3d4670e.PNG)
