### ISSUE TITLE
[BUG] Display chat window

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#4758]
![image](https://user-images.githubusercontent.com/10221999/28995556-82127268-79ec-11e7-9fca-7a52e378aa41.png)

**Comment by rskrzypczak** [comment]
it's still
![image](https://user-images.githubusercontent.com/10221999/29043746-c74e82c8-7bbc-11e7-904d-1c267e7e1f63.png)

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/f307f35de5c9d3ac841b5b2e7ce6259d712af756
