### ISSUE TITLE
[bug] can't put '[...]' to event's topic

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#4760]
#### Issue
If I put something between '[' and ']' signs in event's topic (in calendar) the topic is not shown.

#### Your Environment

* YetiForce Version used: 4.1.0
* Browser name and version: IE
* Environment name and version: PHP 7.0
* Operating System and version: Win10

**Comment by konadrian** [comment]
Can you show some examples of this topic

**Comment by pflaz** [comment]
Of course:
I was tried to create new event with '[test]' in topic:
![yf-event1](https://user-images.githubusercontent.com/29442233/29015989-b0593bb0-7b50-11e7-8342-cc8956a13992.PNG)
When I have saved it, there is no topic in this event:
![yf-event2](https://user-images.githubusercontent.com/29442233/29016002-c1115dfc-7b50-11e7-969a-d0eaeb16c2b0.PNG)

![yf-event3](https://user-images.githubusercontent.com/29442233/29016005-c61edbb2-7b50-11e7-9a70-d041cc8f74a4.PNG)

**Comment by konadrian** [comment]
We are currently rewriting that, but it's a very tedious process that requires checking numerous places in the system, which also means it takes a lot of time. This action will be possible in the future.
