### ISSUE TITLE
[Question] can we have a very useful calculation function from related module?

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#4761]
just like this:
CALCULATE FIELDS for Vtiger
this plugin can sum value fields in related module and update target field in related module
http://www.its4you.sk/en/vtiger-extensions/crm-vtiger-extension-calculate-fields
I know we can do things like this with invoke custom function. but may be we can make it easier.

**Comment by PercyP** [comment]
I was just looking at this too at its4you. Like you I think this would be a brilliant addition!

**Comment by paula-w** [comment]
We’re not planning to add this feature right now. A similar feature will appear in the future, but it most likely is going to be new uitype fields instead of a panel.
