### ISSUE TITLE
[Question] [PL] Workflow Generate Customer Login Details  YF 4.1

### ISSUE THREAD

**Issue by MarekRomanowski** [YetiForceCompany/YetiForceCRM#4762]
Witam,

Cze ten Workflow Generate Customer Login Details będzie dostepny?
Do portalu można się dostać dodając ręcznie hasło dla użytkownika w webservice, natomiast nie ma takiej możliwości dla kontaktów. Także hasło nie jest generowane i wysyłane mailowo.
Nie można stworzyć worflow ręcznie bo brakuje zadań takich jak CreatePortalLoginDetails i MarkPasswordSent.
Mozna zaimportować z YT 3, ale nie działają.

Czy jest to jakiś wiekszy problem techniczny na dzień dzisiejszy czy mniej skomplikowana przeróbka?

**Comment by epsilonsc** [comment]
Witam @MarekRomanowski musisz w konfiguracji 
Konfiguracja systemu > Automatyzacja > Wyzwalacze > Konfiguracja systemu
Włączyć "Wyślij Szczegóły Loginu Klienta"

![zadanie](https://user-images.githubusercontent.com/10506580/29006743-304960d0-7af6-11e7-986b-3c85d291bb05.png)
