### ISSUE TITLE
Error on login: SQLSTATE[22001]: String data, right truncated...

### ISSUE THREAD

**Issue by koxu1996** [YetiForceCompany/YetiForceCRM#4763]
## Issue 
I installed YetiForceCRM in docker container. When I Iogin there is an error:
```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'user_ip' at row 1 The SQL being executed was: INSERT INTO `vtiger_loginhistory` (`user_name`, `user_ip`, `login_time`, `logout_time`, `status`, `browser`) VALUES ('admin', '172.19.0.2(X-Real-IP: 172.19.0.1,X-Forwarded-For: 172.19.0.1)', '2017-08-06 10:58:20', NULL, 'Signed in', 'Google Chrome 60')
```

I checked and column `user_ip` has 50 characters length, but function `getRemoteIP()` is generating much longer string.

## Solution
Increase `vtiger_loginhistory`.`user_ip` length or modify `getRemoteIP()` function to return only ip from `$_SERVER['REMOTE_ADDR']`.

**Comment by konadrian** [comment]
Which version of yeti are you using ?

**Comment by koxu1996** [comment]
Version 4.0.0, but this issue still persist in master:
https://github.com/YetiForceCompany/YetiForceCRM/blob/5f43367be5b2841d5fecd503f6a674bb29a8dfc0/install/install_schema/scheme.sql#L6148
