### ISSUE TITLE
task created by A assign to B does not displayed in task widget

### ISSUE THREAD

**Issue by zelphar** [YetiForceCompany/YetiForceCRM#4764]
updated to 4.1
when create project task, and assign to set to other users.
when login as other user. there is no task displayed in widget.

**Comment by konadrian** [comment]
Can you show screens or create a gif with your problem. I'm not sure I understand it correctly

**Comment by zelphar** [comment]
<img width="1538" alt="wx20170810-001342 2x" src="https://user-images.githubusercontent.com/15126825/29131910-eedd43c4-7d60-11e7-9d09-fb3e7ab17ab3.png">
log in as admin
then create lots of project task and assigned to Jun LI
then log in as Jun Li
create one task.
check out the widget
only the task create by Jun Li's User can be found in widget. task create by other people but set assign to as Jun Li. can not be found in widget.
<img width="1553" alt="wx20170810-001429 2x" src="https://user-images.githubusercontent.com/15126825/29132009-54080194-7d61-11e7-91ba-6e4b87492000.png">

**Comment by konadrian** [comment]
Try change filter option from mine to all

**Comment by zelphar** [comment]
![391c33fa-af35-45cf-b5fe-2103df59cf99](https://user-images.githubusercontent.com/15126825/29250011-5fd586fe-806d-11e7-89a8-2a2883cb937d.jpg)
it's same result.

**Comment by zelphar** [comment]
i have found that even A create record in module which access as public read/write/delete
B can not see that record in the list.

**Comment by paula-w** [comment]
These widgets only show the events that you created yourself and assigned to someone else. Switching users causes showing only these that you created yourself and assigned to the selected user. The system doesn’t allow you to display other events.
If this is not what you mean then please show us how to trigger it on a gif recorded on the gitdeveloper version.
