### ISSUE TITLE
set tax summary to a default value

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#4765]
Hi,
we only use one global tax rate for all invoices. Is there a  way to set the tax summary to a default value without the need to always use the set tax dialog?
![grafik](https://user-images.githubusercontent.com/10443220/29004726-c952cdea-7acc-11e7-9c25-94a3c9c6273a.png)
![grafik](https://user-images.githubusercontent.com/10443220/29004669-b548cc1a-7acb-11e7-85ac-73fb577bcd0a.png).
We need to avoid that invoices without taxes are send to clients and protect us from users forget to set the tax rate.

**Comment by YESMUN** [comment]
Is there an answer to this question? I also would like to have the tax set by default.

**Comment by mansooraliph** [comment]
Whether this is solved? any patch or plugin ?

**Comment by vovpff** [comment]
@mansooraliph this will be solved in 5.4 release.
