### ISSUE TITLE
[BUG] Do not display user image

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4771]
v4.1.93
The user account successfully uploaded the avatar image, but the update did not display
![screenshot 29](https://user-images.githubusercontent.com/19627226/29020707-247c84a2-7b8d-11e7-80d9-f849815b2ed8.png)

**Comment by ezbank** [comment]
![nh ch p man hinh 28](https://user-images.githubusercontent.com/19627226/29054229-1dea9c68-7c1f-11e7-8e04-ed734fd794c6.png)
it's still v4.1.105

**Comment by konadrian** [comment]
Fixed by https://github.com/YetiForceCompany/YetiForceCRM/commit/a9288bbfa1874ccb93b40bd0fd1ef455ea0203c2

**Comment by ezbank** [comment]
it's still v4.2.20
![nh ch p man hinh 31](https://user-images.githubusercontent.com/19627226/29217234-50a667fe-7edb-11e7-810c-939732fb483e.png)

**Comment by ezbank** [comment]
![123123123](https://user-images.githubusercontent.com/19627226/29442870-8402c160-83fe-11e7-908e-22ca20579b7f.png)

**Comment by ezbank** [comment]
hi! @mariuszkrzaczkowski  it's still v4.2.61
![nh ch p man hinh 32](https://user-images.githubusercontent.com/19627226/29492189-a093c996-859d-11e7-9e3f-760542221708.png)

**Comment by ezbank** [comment]
it's still v4.2.104
![3](https://user-images.githubusercontent.com/19627226/29743919-aeb4cd28-8ac4-11e7-89e7-3a5957d50d20.png)

**Comment by slawekk87** [comment]
I tested this on developer version.
![4771](https://user-images.githubusercontent.com/22735929/30375949-bf624b72-988a-11e7-96bc-792029a60835.gif)

**Comment by ezbank** [comment]
@slawekk87  In the comment section, the avatar is not visible
