### ISSUE TITLE
NGINX Conf .htaccess

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4780]
#### Issue

Hi Team, 
Does anyone have the ideal configuration to run the APIs in nginx? Nginx does not work with .htaccess.

Thank you

#### Actual Behavior

![image](https://user-images.githubusercontent.com/3030997/29029446-10600c70-7b5e-11e7-8c55-e20078988086.png)

#### Your Environment

* YetiForce Version used: 4.1
* Browser name and version: chrome and firefox
* Environment name and version:
* Operating System and version:

**Comment by skramanzia** [comment]
After add this line
![image](https://user-images.githubusercontent.com/3030997/29030890-e0dc89b0-7b62-11e7-975b-740d33c34e43.png)

Report this error
![image](https://user-images.githubusercontent.com/3030997/29030914-f034acbc-7b62-11e7-8e26-ea057af2e6d2.png)

User this conf:
![image](https://user-images.githubusercontent.com/3030997/29030924-f9ef796c-7b62-11e7-9730-5d194cd3d75f.png)

App Conf:
![image](https://user-images.githubusercontent.com/3030997/29030941-073a2b3a-7b63-11e7-9b5d-6c9f84ae1f10.png)

Thanks!

**Comment by skramanzia** [comment]
After change username:
http://demo.vr4it.com/api/webservice/Users/Login
![image](https://user-images.githubusercontent.com/3030997/29032017-65f5ef62-7b66-11e7-98d7-f0322f8b4fe9.png)

**Comment by skramanzia** [comment]
If run api/webservice/Methods/RecordsList
Display
![image](https://user-images.githubusercontent.com/3030997/29032376-8b09d70e-7b67-11e7-9292-ce0c579dbf57.png)

**Comment by mariuszkrzaczkowski** [comment]
try this http://winginx.com/en/htaccess

**Comment by bpabiszczak** [comment]
We do not support nginx
