### ISSUE TITLE
[bug] user language

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#4782]
Users language not saved when logged out and in, reverts to default. Of cource can be bypassed by setting the default language or allowing user to select language when logging in.

#### Your Environment

* YetiForce Version used: 4.1.102
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
Can you show screens or create a gif with your problem. I'm not sure I understand it correctly

**Comment by kpaulaha** [comment]
When user select language and log out/in the language is back to the default.
![lang](https://user-images.githubusercontent.com/10330264/29068321-ea293aea-7c3e-11e7-8c5e-d71667c7987e.gif)
