### ISSUE TITLE
[bug][4.1.107][process install] Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#4791]
#### Actual Behavior

The installation process can not be performed from the first step

#### How to trigger the error

1.
![chrome_2017-08-08_08-27-04](https://user-images.githubusercontent.com/18419851/29060847-61b905ee-7c13-11e7-885a-042596e7867f.png)

![chrome_2017-08-08_08-26-12](https://user-images.githubusercontent.com/18419851/29060823-4e7ac4ea-7c13-11e7-8ff0-d3584ea22f54.png)

#### Your Environment

* YetiForce Version used: 4.1.107
* Browser name and version: Chrome 60
* Environment name and version: php 7.1, apache 2.4
* Operating System and version: CentOS 7 in VM

**Comment by marcinkuk** [comment]
I agree. I spent 6 hours installing YetiForce 4.1.0 on 2 physical and 10 virtual server and could not change language and went to the next page.

**Comment by mariuszkrzaczkowski** [comment]
When updating jquery a blank file was uploaded.
I corrected this in this https://github.com/YetiForceCompany/YetiForceCRM/commit/31d45ec4a1609997dee2b5936b00d86c2c2ea70e
I fixed the update package and the complete package (YetiForceCRM-4.1.0-complete.zip)
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.1.0

**Comment by WalterLuis** [comment]
Okey, thanks
