### ISSUE TITLE
[BUG]  Recording Control | Action "Field value is unique." operation is not accurate

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4792]
v4.1.108
When checking a single value in the same module, it does not work correctly.
![bug](https://user-images.githubusercontent.com/19627226/29067154-c047307a-7c5b-11e7-9b67-c4aa47ffbe90.gif)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/5451
