### ISSUE TITLE
[question][4.1][Workflow] How can I update a field more quickly?

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#4795]
I have created a Custom Function and to update a field I tried with the parameter: `$entity->set('db_column', 'value')`, just as I use `$entity->get('db_column')` to get information, but did not update the field.

I currently update the fields with the Webservice using PUT, but updating a field takes about 5~10 seconds and a POST insertion of a record takes less than 1 second. I have discarded the problem of slow internet because I do queries with "https://localhost/api/webservice"

Is there any way to update a field faster?

Thanks in advance (:

**Comment by konadrian** [comment]
Try `$entity->save();` after
`$entity->set('db_column', 'value')`

**Comment by WalterLuis** [comment]
Good afternoon,

When creating a record using `$entity->save();` after `$entity->set('db_column','value')` creates me only  ~14000 records, instead of 1, giving after a few seconds the following error:

	Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 716800 bytes) in /var/www/sgc/vendor/yetiforce/EventHandler.php on line 67

And when updating a record is edited the record in which I am, but I get the same error after ~ 10 seconds.

Thanks for the quick reply

**Comment by WalterLuis** [comment]
And the workflow does not have any loop, it is a simple workflow collecting some values and updating a field if it fulfills a condition.

**Comment by mariuszkrzaczkowski** [comment]
It does not work, you have some errors:
$entity->set('db_column', 'value')  >>> $entity->set('field_name', 'value')
$entity  >>> $recordModel

Here you have the correct example:

```php
$recordModel->set('fieldName', 'value);
$recordModel->setHandlerExceptions(['disableWorkflow' => true]);
$recordModel->save();
```
Here is a sample file: 
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/com_vtiger_workflow/tasks/VTUpdateFieldsTask.php#L74

**Comment by WalterLuis** [comment]
Now yes, thank you very much to both :D
