### ISSUE TITLE
Mail Scaner error

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#4796]
Good morning.I get ERR_INCORRECT_ACCESS_DATA error in mail scaner.I use a domain with ssl, with gmail if I can create the folders but with my domain not.I can link from rouncube, accounts, potentials etc. I can send emails but I do not get assigned to the clients.  Generado por YetiforceCRM ver. 4.1.0PHP: 5.6.31Errores de configuración del servidor:output_buffering: 1innodb_lock_wait_timeout: 50Errores de librerías:apcu

**Comment by konadrian** [comment]
Just like in the case of https://github.com/YetiForceCompany/YetiForceCRM/issues/4723we need more info, you can also check if the hints from that ticket are helpful for you
