### ISSUE TITLE
Brak możliwości zapisu

### ISSUE THREAD

**Issue by EdiAndradina** [YetiForceCompany/YetiForceCRM#481]
Przy każdorazowej próbie zapisu np kontaktu otrzymuje komunikat ISE 500
Jak weryfikuje później kontakt dodaje się do bazy, lecz za każdym razem komunikat się wyświetla
Instalacja na home.pl w wersji 1.4.0

**Comment by bpabiszczak** [comment]
ISE 500 to błąd serwera, administrator serwera powinien Ci powiedzieć co powoduje błąd [np. jakiś skrypt zbyt długo się wykonuje].

**Comment by bpabiszczak** [comment]
Brak informacji dodatkowych zgodnych z tym dokumentem: https://yetiforce.com/pl/pomys%C5%82y,-zmiany,-b%C5%82%C4%99dy/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html. Zgłoszenie zamykam.
