### ISSUE TITLE
[BUG][4.1.126][OSSPassword] Can not save record

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#4818]
#### Issue

When the fields are complemented and you give the save button, it does nothing. There is no critical error or anything similar. 
It does not even enter the save process:

	I added in: /modules/OSSPasswords/actions/Save.php:34
	\App\Log::trace('Breakpoint in OSSPassword');

I activated the console in /config/debug.php and the trace does not appear

Maybe it's a nonsense but can not find the error

#### Your Environment

* YetiForce Version used: 4.1.126
* Browser name and version: Chrome 60
* Environment name and version: PHP 7.1
* Operating System and version: CentOS7

**Comment by DimitryY** [comment]
I try to debug this issue and fount that is the system problem:
All classes that extends Vtiger_Save_Action or Vtiger_SaveAjax_Action not used. 
PriceBooks_Save_Action, Contacts_Save_Action also don't work.

**Comment by mariuszkrzaczkowski** [comment]
I tested on gitdev, i can’t see the problem.

**Comment by WalterLuis** [comment]
now it works, thanks
