### ISSUE TITLE
Mail Scanner Email Attachments

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#482]
Where do you see the email attachments from corporate emails.

Everything works.

It says Has attachment, but I don't see the attachment under corporate email

**Comment by KatarzynaUlichnowska** [comment]
Hello,
could you explain it in more detail and provide screenshots?
https://yetiforce.com/en/ideas,-changes,-bugs/bugs/126-how-to-report-bugs.html

**Comment by Kulas182** [comment]
Cześć,
nie jestem pewien czy o to chodzi ale, mam zainstalowaną najnowszą wersję YetiForce i po uruchomieniu skanera maile są przenoszone do bazy:

![mail](https://cloud.githubusercontent.com/assets/1971239/7490381/0de72094-f3e0-11e4-9f17-5af5f916349a.png)

Jeden z nich, jak widać ze screena był z załącznikiem, jednak w CRM'ie nie jestem w stanie odnaleźć tego pliku (podstrona "Dokumenty" jest pusta). Czy pliki z załączników są gdzieś zapisywane w YetiForce?

**Comment by bpabiszczak** [comment]
Załącznik to również obrazek, który ładuje się podczas wyświetlania maila. Potrzebujemy konkretny przykład [np. podpiąć konto testowe gmail na wersje testową i pokazać na konkretnym mailu problem.

**Comment by amicheals** [comment]
Can I re open this?

**Comment by KatarzynaUlichnowska** [comment]
Please create a new issue with a step-by-step description.

**Comment by amicheals** [comment]
This works in version 2.0
