### ISSUE TITLE
[BUG] Cant Import data to module

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4827]
v.4.2.5
Tested on https://gitdeveloper.yetiforce.com
![screenshot 35](https://user-images.githubusercontent.com/19627226/29160100-2c71e152-7ddb-11e7-8776-b237e488195d.png)
![bug](https://user-images.githubusercontent.com/19627226/29160200-8bd9bee4-7ddb-11e7-8f9a-450a20a57944.gif)

**Comment by Irmina8591** [comment]
Witam problem dalej nie rozwiązany ;/ czy wiadomo coś w tej kwestii?

**Comment by mariuszkrzaczkowski** [comment]
Testowałem na https://gitdeveloper.yetiforce.com i błędu nie widzę. Proszę o pełny opis problemu jak wywołać wraz z zrzutami ekranu.

**Comment by Irmina8591** [comment]
Błąd wygląda następująco

Wybieram - więcej - importuj dane
Uzupełniam dane do importu oraz wybieram plik - klikam dalej i... pokazuje
się niepełna pusta plansza systemu. nie ważne ile czekam pozostaje bez
zmian. Przy próbie odświeżenia informuje że dane mogą zostać utracone, przy
próbie przejścia do innego modułu - dodaje "#" do adresu i nic nie robi.
Screeny w załączniku.

W dniu 18 września 2017 15:14 użytkownik Mariusz Krzaczkowski <
notifications@github.com> napisał:

**Comment by anderpydev** [comment]
Witam,

Problem jest naprawiony. Widzę w repozytorium commit Fixed #4820
Na stronie https://gitdeveloper.yetiforce.com również już działa import. Jak mogę fix tego problemu wprowadzić do wersji stable 4.2? Sama poprawka kodu z tego commitu nie naprawia importu u mnie. Czy są jeszcze jakieś pliki edytowane we wcześniejszych commitach, które naprawiają ten błąd?

**Comment by bpabiszczak** [comment]
Wkrótce wydamy wersje 4.3 i będzie można uaktualnić.

**Comment by aljofloz** [comment]
Hello, 

I have the same problem described, I'm currently using Yetiforce v4.2, do you know how can i solve this problem or when it will be solved?

Thank you for your support

**Comment by bpabiszczak** [comment]
@aljofloz check here: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.2.0 [ImportFix_unizp_to_root.zip].

**Comment by pflaz** [comment]
Unfortunatelly it does not resolve the problem. Probably there were more changes in the meantime what are not reflected in this fix.
It seems we have to wait for 4.3 pack and live without import possibility in CRM :(

**Comment by paula-w** [comment]
It should solve your problem because we fixed this issue using these scripts for many of our clients.

**Comment by pflaz** [comment]
Great, I am more than happy it resolved the problem for your clients. I know I am worse client because I try to use your system without pay for it directly so it is only my problem import still doesn't work on my instance.

**Comment by aljofloz** [comment]
Hi and thank you for your comments

I just try the scripts on my root folder, but it didn’t have any effect, I
still without being able to import.

**Comment by mariuszkrzaczkowski** [comment]
Instead of complaining someone may show logs. Without logs we will not be able to help. This is obviously obvious

**Comment by pflaz** [comment]
[10-Oct-2017 05:46:30 Europe/Sarajevo] PHP Warning:  require_once(include/Webservices/VtigerModuleOperation.php): failed to open stream: No such file or directory in /home/***/public_html/crm/include/Webservices/Utils.php on line 375

[10-Oct-2017 05:46:30 Europe/Sarajevo] PHP Fatal error:  require_once(): Failed opening required 'include/Webservices/VtigerModuleOperation.php' (include_path='.:/usr/local/php70/lib/php') in /home/***/public_html/crm/include/Webservices/Utils.php on line 375

**Comment by mariuszkrzaczkowski** [comment]
test it ImportFix_unizp_to_root_v2.zip
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.2.0/ImportFix_unizp_to_root_v2.zip

**Comment by pflaz** [comment]
Thank you, @mariuszkrzaczkowski , it works :)
Kind regards

**Comment by aljofloz** [comment]
It works! I would like to thank you for your kindly help

2017-10-10 7:17 GMT-05:00 pflaz <notifications@github.com>:

**Comment by sithu20** [comment]
Can not download  ImportFix_unizp_to_root_v2.zip .

**Comment by mariuszkrzaczkowski** [comment]
Test the upgrade package https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%204.x.x/4.2.0_to_4.3.0/zip

**Comment by sithu20** [comment]
<img width="938" alt="screen shot 2017-12-12 at 12 07 48 pm" src="https://user-images.githubusercontent.com/159703/33869210-f6e374b2-df35-11e7-817a-652b76d4f139.png">
