### ISSUE TITLE
YetiForce 4.1 & 4.2

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#4842]
Since we released YetiForce 4.0 LTS in February we've been working long and hard on improving and optimizing YetiForce, fixing issues reported by the community, and we also added a couple of new features. The list of all new changes, functionalities, and fixes we introduced is impressive, and YetiForce is, as always, entirely free and available for everyone. No limitations, no hidden fees.

We would like to thank our amazing community, we wouldn't be able to achieve this much without you. We appreciate everyone who supports us by ordering new features, improving our code, adding translations, and reporting issues.  We were able to achieve all of this thanks to our innovative product building strategy, our community, and amazing clients – we thank you, YetiForce wouldn't exist without you.

In other news – we gave our website [yetiforce.com](https://yetiforce.com/en/) a complete makoever, so we encourage you to check it out. Please bear in mind that it's still a work in progress.

### LINKS

- https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.1.0
- https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.2.0

**Note**: download the "complete" version (eg. YetiForceCRM-4.1.0-complete.zip), if you don't download the complete version you will have to use [composer](https://getcomposer.org/doc/01-basic-usage.md) before you install the system. 

### UPDATE & REQUIREMENTS

We would like to remind everyone that **updates should first be executed on a test version**, and only then on the production version [you should always have a backup copy of your environments].

- The list of current web server requirements necessary for version 4.1/4.2 to work properly can be found [here ](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements) 
- A detailed description of the installation process can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-update) 
- If you want us to update your system, we encourage you to purchase [this package](https://shop.yetiforce.com/en/migration/14-migration-vtiger-yetiforce.html) 

### CHANGELOG

A complete changelog for both versions will soon appear on out website. Below you can find the most important changes that 4.1 & 4.2 introduced: 

- updated key libraries to latest versions
- added new unit tests  [https://travis-ci.org/YetiForceCompany/YetiForceCRM]
- added session encryption key 
- expanded support for PHP 7.1.x, HHVM, W3C
- expanded support for PHP Standards Recommendations [http://www.php-fig.org/psr/]
- expanded Brute Force attacks protection [https://www.owasp.org/index.php/Blocking_Brute_Force_Attacks]
- removed outdated and redundant libraries [according to OWASP Secure Coding Practices]
- rewritten a large part of queries [compatibility with PostgreSQL and other SQL-92 standard engines]

- fixed the following security errors found during our external security audits: 
  - A1 - Injection, 
  - A3 - Cross-Site Scripting [XSS],
  - A5 - Security Misconfiguration, 
  - A9 - Using Components with Known Vulnerabilities,  
  - A10 - Underprotected APIs

-  introduced many recommendations we received after undergoing the security audits:
    - auto notifying the admin about detected irregularities
   -  moving all files not used by the user outside public_html
   -  added library vulnerability verification  [https://security.sensiolabs.org/]
   -  added header verification [https://observatory.mozilla.org/, https://securityheaders.io/?q=gitdeveloper.yetiforce.com&hide=on&followRedirects=on] 
   -  added detecting incorrect actions [first phase] [ according to OWASP Secure Coding Practices recommendations]
   -  added server configuration verification regarding safety 
   -  added safeguards for downloading/uploading attachments
   -  changed input parsing methodology 
   -  added protection against man-in-the-middle attacks

**Comment by PercyP** [comment]
This just gets better and better! Well done and thanks for such a great product.

**Comment by kpaulaha** [comment]
I agree, it's a great product, we have been using different OS CRM solutions for 13 and yf has great features. Unfortunately it has for us an critical bug, that has prevented us to use it's several latest versions for our customers, but I hope it will be fixed in some comming version. But we continue testing and waiting for the perfect product.

**Comment by PercyP** [comment]
@kpaulaha 

what is the critical bug?

**Comment by kpaulaha** [comment]
Hmm, maybe critical is a wrong world, but we in scandinavia use comma as decimal separator and full stop with dates. So using full stop with desimals is not natural for us and e.g. exporting to excel will mess things up. But we wait for the fix and use alternatives meanwhile.

**Comment by mariuszkrzaczkowski** [comment]
Have your bugs been reported on github?

**Comment by kpaulaha** [comment]
For some time ago #4029
