### ISSUE TITLE
Leads edit fields error

### ISSUE THREAD

**Issue by natyona** [YetiForceCompany/YetiForceCRM#4843]
![edits fileds errors](https://user-images.githubusercontent.com/10330799/29197461-37b0dfd2-7e44-11e7-8a3f-2223e55139e7.png)

Hi Friends
i have an error on edit field , when a want to click on drop list button , nothing work
see the pic, i dont cant erase or add a new fields and the footer is not appear

Request URL:http://xxxxxxxxxx/~click2crm/assureur34/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=Leads
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:111111111:80
Referrer Policy:no-referrer-when-downgrade

**maybe somebody have the same error**
Thanks Naty
* YetiForce Version used:3.4
* Browser name and version: chrome last update
* Environment name and version: linux centos 5
* Operating System and version: linux centos 5

**Comment by konadrian** [comment]
Check your console in the browser, you should get more info about this, or show this error at https://gitdeveloper.yetiforce.com/
