### ISSUE TITLE
[QUESTION] FEATURES ABOVE 4.1 "Added the ability to zoom widgets"

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4852]
v4.1.0
In version 4.1 there is a new feature is "Added the ability to zoom widgets". But I do not see where it is shown.
![image](https://user-images.githubusercontent.com/19627226/29207201-72ddf458-7eaf-11e7-9803-e838b235968d.png)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/d5b571a2f2172c632e58c363e725a485d669fa2f

**Comment by ezbank** [comment]
hi @bpabiszczak 
Can you tell me more about how it works?
Many thanks.

**Comment by paula-w** [comment]
This functionality is not enabled by default, it’s disabled. It used to work for one widget type only – the records list. It’s disabled by default because it caused problems.

**Comment by mariuszkrzaczkowski** [comment]
At the moment, magnification is only working for one type of widget - „Timeline”, it should work also for other widgets but it hasn’t been tested. Example below:
![2017-11-10_09-24-20](https://user-images.githubusercontent.com/10198654/32649787-a3431dba-c5fb-11e7-809a-43c98d77e33d.png)
![2017-11-10_09-25-44](https://user-images.githubusercontent.com/10198654/32649792-a49b2324-c5fb-11e7-84b0-9c05d30f3160.png)
![2017-11-10_09-26-00](https://user-images.githubusercontent.com/10198654/32649799-a6d6d9b2-c5fb-11e7-92da-9ab54625d207.png)
