### ISSUE TITLE
Error 500 updating from 4.0 to 4.2 - a solution that worked for me

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4858]
Hi, just in case others have the same problem as me when trying to upgrade from 4.0 to 4.2 (I was getting error 500) here are the steps I took. 
1. Download first package: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.2.0
and use the following version:
4.0.0_to_4.1.0_v4.zip

2. download second package: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.1.0
and use this file:
4.1.0_to_4.2.0_v1.zip

3.After installing the first package mine installed without an error message (says it was successful) but when I click on finish it goes to the Error 500 page. 

4. I went to my cpanel error log and found this error:

Invalid command 'SetEnv', perhaps misspelled or defined by a module not included in the server configuration

5. I am on a VPS with EasyApache 4 so I to install mod_env

6. I use Putty and so ran the following command:

yum install ea-apache24-mod_env.x86_64

Now my system loads

7. Installed the remaining update package

I am now on version 4.2. There are a couple of minor things that are not yet working, but I will submit these as issues

Kind regards

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/apache-500-internal-server-error-3

**Comment by bpabiszczak** [comment]
@mariuszkrzaczkowski what do you think about it?

**Comment by cliquei** [comment]
> Hi, just in case others have the same problem as me when trying to upgrade from 4.0 to 4.2 (I was getting error 500) here are the steps I took.
> 
> 1. Download first package: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.2.0
>    and use the following version:
>    4.0.0_to_4.1.0_v4.zip
> 2. download second package: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.1.0
>    and use this file:
>    4.1.0_to_4.2.0_v1.zip
> 
> 3.After installing the first package mine installed without an error message (says it was successful) but when I click on finish it goes to the Error 500 page.
> 
> 1. I went to my cpanel error log and found this error:
> 
> Invalid command 'SetEnv', perhaps misspelled or defined by a module not included in the server configuration
> 
> 1. I am on a VPS with EasyApache 4 so I to install mod_env
> 2. I use Putty and so ran the following command:
> 
> yum install ea-apache24-mod_env.x86_64
> 
> Now my system loads
> 
> 1. Installed the remaining update package
> 
> I am now on version 4.2. There are a couple of minor things that are not yet working, but I will submit these as issues
> 
> Kind regards

Thanks man your help was a 10 for me !
