### ISSUE TITLE
[BUG] Can not choose icon for folder

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4867]
v4.2.20
Can not choose icon for folder if icon is image
![1121](https://user-images.githubusercontent.com/19627226/29217756-e4b5ab70-7edc-11e7-81e9-3da04929bcd1.gif)

**Comment by vovpff** [comment]
@ezbank I think icon for folder must be in svg format (scalable)
How you add custom icons to icons list?

**Comment by bpabiszczak** [comment]
First icon is font. You must add images as a font. We currently only support images as fonts.

**Comment by vovpff** [comment]
@bpabiszczak how to add images as a font?

**Comment by bpabiszczak** [comment]
Example: https://stackoverflow.com/questions/11426172/add-custom-icons-to-font-awesome

**Comment by vovpff** [comment]
@bpabiszczak thx
