### ISSUE TITLE
[BUG] Error converting Lead to Account

### ISSUE THREAD

**Issue by varlog11** [YetiForceCompany/YetiForceCRM#4870]
#### Issue
Error converting Lead to Account

#### Environment
* YetiForce Version used: 4.2 and 4.2.24

![animation](https://user-images.githubusercontent.com/1807261/29239935-1f4d8b66-7f6b-11e7-978d-12a2bda05e41.gif)

**Comment by ezbank** [comment]
Error still exist v4.2.127
![zalo_screenshot_30_8_2017_1730259](https://user-images.githubusercontent.com/19627226/29886228-96daf458-8de3-11e7-8a53-ccfa26d3ed4a.png)
