### ISSUE TITLE
4.2.0 calendar GUI broken

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4873]
#### Issue

Day and week views has small height

![cal bug 2](https://user-images.githubusercontent.com/8545791/29249372-b9c01710-8036-11e7-852a-f6efcecb5994.gif)

4.0.0 has next height

![image](https://user-images.githubusercontent.com/8545791/29249401-b3c9ed4e-8037-11e7-9f11-d0b690cb5b44.png)

#### Actual Behavior

Height too small

#### Expected Behavior

Height must be like window height

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
I checker 4.2.24 and there are the same gui bug

**Comment by mariuszkrzaczkowski** [comment]
It adjusts automatically as there are more entries

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I checked this feature. Looks like it works correct. Sorry for your attention.
Check #4875 too

**Comment by vovpff** [comment]
Check #4881 too!
