### ISSUE TITLE
4.2.0 Invalid date at event creatin

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4874]
#### Issue

After 4.1.0 to 4.2.0 update when I try to create some events after start time changing end date and time became Invalid date. See gif.

![cal bug 1](https://user-images.githubusercontent.com/8545791/29249460-81260354-8038-11e7-9b0f-7efc92d76cdf.gif)

Current 4.2.24 don't has this bug

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@mariuszkrzaczkowski the same bug appears after update from 4.0.0 to 4.1.0 v5. To avoid this bug user date format must be yyyy-mm-dd. Another date formats cause Invalid Date.
#4875 here are too!

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
can you test it again on the latest [dev version](https://gitdeveloper.yetiforce.com/index.php)?

**Comment by vovpff** [comment]
@KatarzynaUlichnowska @mariuszkrzaczkowski 
bug not solved. The same situation. Works perfect only with yyyy-mm-dd date format. Any another settings cause Invalid Date

**Comment by konadrian** [comment]
Fixed By https://github.com/YetiForceCompany/YetiForceCRM/commit/622d287e920fe98d0529e368e079d804b36ba375
