### ISSUE TITLE
dev 4.2.24 event start and end time

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4875]
#### Issue

Current dev 4.2.24 version has bug with event dates and time. When you change start time end time became the same time excluding default call/event duration user parameters 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
Fixed by https://github.com/YetiForceCompany/YetiForceCRM/commit/622d287e920fe98d0529e368e079d804b36ba375
