### ISSUE TITLE
[bug] report chart

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#4876]
Making chart using date causes error

![chart1](https://user-images.githubusercontent.com/10330264/29249547-0fe63f18-803a-11e7-8c02-2f217812bd2a.png)
![chart3](https://user-images.githubusercontent.com/10330264/29304896-68b8527e-819e-11e7-84c8-9996e495081d.png)

#### Your Environment

* YetiForce Version used: 4.2.0-4.2.24
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
We need to see what you do before the error appears. We need more info

**Comment by kpaulaha** [comment]
Making chart counting projects by starting date. User date format dd.mm.yyyy
![report](https://user-images.githubusercontent.com/10330264/29409041-38cd2f7e-8353-11e7-9bc8-05274c1d9aea.gif)

**Comment by Raggazzoo** [comment]
Any news ? Thank's

**Comment by kpaulaha** [comment]
Hmm, have just to be patient, sure it will be fixed in some stage. We have an open issue from last February, which prevent us using YF, but belive it will be fixed in some time. Working long enough with os learns to be patient.

**Comment by ezbank** [comment]
still exits v4.2.472 @mariuszkrzaczkowski 
![bug report detail](https://user-images.githubusercontent.com/19627226/32671767-3acd8d26-c67b-11e7-96d7-7bebb40460dd.gif)

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6538
