### ISSUE TITLE
Update field value based on another field value from other module.

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#4879]
#### Issue
I have created 2 standard modules called Ordine Clienti and Contracte Clienti.

#### Actual Behavior
I have tried to make automation field update on Contracte Clienti record for field type picklist called Stadiu Contract when i add a new record on Ordine Clienti with status Inceput, update Contracte Clienti record Stadiu Contract.

#### Expected Behavior
I need a way to update field value based on another field value from other module.

#### How to trigger the error
I see on another issue a list with some extensions that are avabile for free on yetiforce and paid on vtiger. I think that one of that module help me.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Google Chrome
* Environment name and version:
* Operating System and version: Windows 7

**Comment by konadrian** [comment]
You can do this by workflow
https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=List&block=15&fieldid=24

**Comment by cltvchannel** [comment]
How i can do this. I don't know how to do .

**Comment by KatarzynaUlichnowska** [comment]
You need to create a new workflow and select ToDo "Update fields".
