### ISSUE TITLE
Time control calendar throws errors

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#4880]
Hi,

after updating from version 4 to 4.2 the time control calendar no longer works properly. If I use the quick create and then click Save it just hangs. If I refresh the page it has saved. If I go to Full form and then click Save I get an error 500 with white screen. 

I tested this on the version 4 and it works correctly. 

in phperrors.php this is what it shows:

`[14-Aug-2017 12:45:33 Europe/London] PHP Fatal error:  Uncaught Error: Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php:116
Stack trace:
#0 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(116): Exception->__construct(Object(VTExpressionToken))
#1 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(202): VTExpressionParser->atom()
#2 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(189): VTExpressionParser->unaryOp()
#3 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(179): VTExpressionParser->binOpPrec(-1)
#4 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(179): VTExpressionParser->binOpPrec(0)
#5 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(179): VTExpressionParser-> in /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php on line 116
[14-Aug-2017 12:47:12 Europe/London] PHP Fatal error:  Uncaught Error: Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php:116
Stack trace:
#0 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(116): Exception->__construct(Object(VTExpressionToken))
#1 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(202): VTExpressionParser->atom()
#2 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(189): VTExpressionParser->unaryOp()
#3 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(179): VTExpressionParser->binOpPrec(-1)
#4 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(179): VTExpressionParser->binOpPrec(0)
#5 /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php(179): VTExpressionParser-> in /home/mysite/public_html/crm/modules/com_vtiger_workflow/expression_engine/VTParser.php on line 116

ADDITIONAL INFO:
In chrome it display 3 errors, the first is a Post 500 error pointing to this file:
 /crm/public_html/libraries/csrf-magic/csrf-magic.js
the other 2 are internal server errors pointing to:
/crm/public_html/layouts/resources/app.js

**Comment by slawekk87** [comment]
It is a workflow related problem, after YetiForce CRM upgrade You need to update workflows. Notice was displayed at YF CRM update process.

**Comment by PercyP** [comment]
@slawekk87 

would you know where I could find the update notice? SO I can apply the update?

Kind regards
