### ISSUE TITLE
[bug] adding Event

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#4884]
Using user date format dd.mm.yyyy gives invalid End date&time as default  
![todo](https://user-images.githubusercontent.com/10330264/29307702-98a63340-81ab-11e7-832f-9eb058a3f920.png)

Yeti version: 4.4.0 - 4.2.24

**Comment by konadrian** [comment]
Can you trigger this error on gitdeveloper version, for me works fine

**Comment by kpaulaha** [comment]
Nix, not working in v. 4.2.34 if user uses date format dd.mm.yyyy and when adding new Event, sorry not ToDo, and changing activity type.

![cal1a](https://user-images.githubusercontent.com/10330264/29360610-66ea4d50-828c-11e7-8043-8feb2b314135.png)
![call1b](https://user-images.githubusercontent.com/10330264/29360618-6dd38136-828c-11e7-8c42-44f4ffa55047.png)

**Comment by konadrian** [comment]
Can you show how you trigger this error I clickedon calendar or click on quick create - both works fine for me

**Comment by vovpff** [comment]
@konadrian dev 4.2.34 in quick create and full form when you click + button at top of calendar.

![cal bug 4](https://user-images.githubusercontent.com/8545791/29364246-8096e29a-829b-11e7-8c35-197b89242960.gif)

**Comment by kpaulaha** [comment]
Jup, that's it, @vovpff was faster
