### ISSUE TITLE
Workflow Manual - Unknown error! Please inform the administrator

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#4886]
#### Issue

![wf2](https://user-images.githubusercontent.com/3030997/29320403-74718ea0-81ad-11e7-8e7f-f9132666a9eb.gif)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Stable Version and latest DEV
* Browser name and version: chrome + firefox latest version
* Environment name and version: LAB
* Operating System and version:

**Comment by konadrian** [comment]
Can you show how your worklow looks,what tasks it includes and please give bigger gif I don't see the error

**Comment by skramanzia** [comment]
@konadrian Yes sure, In my environment create some currency fields and workflow "sum" os subtract.
 In actual dev version  4.2.49, when create a WF, the icon(+) in OP for example Appears after several minutes of logoff and login again, afte that continue with the issue:
WF
![image](https://user-images.githubusercontent.com/3030997/29366095-6b5f8c32-826f-11e7-8195-c28e681d2672.png)

ISSUE:
![image](https://user-images.githubusercontent.com/3030997/29366127-87aa113c-826f-11e7-8060-fa6efbeff1d7.png)

**Comment by kpaulaha** [comment]
Same happens with other triggers too #4835
