### ISSUE TITLE
Notification configuration issue

### ISSUE THREAD

**Issue by frankhzp** [YetiForceCompany/YetiForceCRM#4891]
#### Issue

can not add users or group , no response by clicking Add
![22121](https://user-images.githubusercontent.com/28562781/29359940-3b22c888-82b3-11e7-99ab-72091402a4a3.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:  4.2.0 
* Browser name and version: chrome 61
* Environment name and version:  Xampp
* Operating System and version: windows 10

**Comment by frankhzp** [comment]
I had even  reinstalled the CRM ,same issue

**Comment by konadrian** [comment]
Can you trigger this error on gitdeveloper version, for me works fine
https://gitdeveloper.yetiforce.com/index.php?module=Notifications&view=Configuration&parent=Settings&block=4&fieldid=98
Or check your logs

**Comment by ezbank** [comment]
same as me
#4354

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/4354#issuecomment-321525657

**Comment by frankhzp** [comment]
on  https://gitstable.yetiforce.com   , same issue.

**Comment by mariuszkrzaczkowski** [comment]
Can you check this on the gitdev version?

**Comment by frankhzp** [comment]
Maybe you have fixed it in GitDev.  anyhow ,I am not able to test the developer version in local.

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/

**Comment by technologiegalwaniczne** [comment]
same issue on my 4.2.0 config

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/32648398-d993265e-c5f5-11e7-8f20-206d2504e2da.png)

**Comment by paula-w** [comment]
We fixed it and this problem should not bother you anymore after the update to version 4.3.
