### ISSUE TITLE
[BUG] dev 4.2.34 event dates bug

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4896]
#### Issue

When you change event start time end date dd and mm became reversed. See gif.

![cal bug 3](https://user-images.githubusercontent.com/8545791/29364143-3c0813f6-829b-11e7-9863-0c610fd89978.gif)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by PercyP** [comment]
Hi,

where did you find the upgrade to version v.2.34? I can only find 4.2

**Comment by vovpff** [comment]
@PercyP this dev 4.2.34

**Comment by mariuszkrzaczkowski** [comment]
duplicate
https://github.com/YetiForceCompany/YetiForceCRM/issues/4884
https://github.com/YetiForceCompany/YetiForceCRM/issues/4874
