### ISSUE TITLE
Import Records

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#4900]
#### Issue

While importing records, it is diverting to home page.
#### Actual Behavior

When we are importing any recrods, it is diverting to home page. 
Unable to import records in module
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2
* Browser name and version: Chrome
* Environment name and version: Stable
* Operating System and version: Linux

**Comment by basanthagarwal** [comment]
In demo version,

it is showing following error





Warning: require_once(include/Webservices/VtigerModuleOperation.php): failed to open stream: No such file or directory in /home/gitstable/domains/gitstable.yetiforce.com/public_html/include/Webservices/Utils.php on line 384

Fatal error: require_once(): Failed opening required 'include/Webservices/VtigerModuleOperation.php' (include_path='.:/usr/local/php56/lib/php') in /home/gitstable/domains/gitstable.yetiforce.com/public_html/include/Webservices/Utils.php on line 384

**Comment by konadrian** [comment]
Duplicated https://github.com/YetiForceCompany/YetiForceCRM/issues/4827

**Comment by pflaz** [comment]
Is there any possibility to do import in 4.2?
After update to 4.2 import does not work at all, I thought it will be fixed in 4.3 on 31st of August but today I see 4.3 has been moved to 15th of September...
IMHO import is quite important functionality in CRM...

**Comment by thedave444** [comment]
I'm also having this issue with PHP7.0 trying to import a 10 leads into Lead Module with .csv file using YetiForce 4.2

![fatalerrorpear](https://user-images.githubusercontent.com/31484590/30197840-9f2da552-9427-11e7-821a-623a0cb77016.JPG)

**Comment by mariuszkrzaczkowski** [comment]
#4827
