### ISSUE TITLE
Import Quote from Excel Table template to Yetiforce Quote Module

### ISSUE THREAD

**Issue by lcuevastodoit** [YetiForceCompany/YetiForceCRM#4901]
Hi Yetiforce team, thanks for your wonderful CRM
Only a question, Is It possible to import a Excel Quote (with a lot of products in a table) into the YetiCRM and from there make a quote?
Cause I see it is possible to import and export Quotes but the export format is one Quote by line.

**Comment by vovpff** [comment]
@lcuevastodoit You can transform your excel file to format understandable for yetiCRM. When I migrate from vtiger to Yeti I spend about week to prepare data for importing.
If you need I can try to help you if I have some free time. Pls contact me by email if you interested.
