### ISSUE TITLE
New Text Parser for PDF Quote request

### ISSUE THREAD

**Issue by lcuevastodoit** [YetiForceCompany/YetiForceCRM#4905]
Hi Yetiforce Team, and thanks again for your CRM
A question, Is it possible to add a new Text Parser for PDF Quote Export so this permit to add the following information at the end in the last column of the product table (maybe modifying ProductsTableNew.php) like this?:

![quote example](https://user-images.githubusercontent.com/25910807/29388480-9b222b4c-82aa-11e7-9eb5-ac24421b09d9.PNG)

Cause here in Latin America our Quotes and Invoice use  the end of the last table column to totalize or sum the Net prices, Discounts, Taxes, and then we obtain the Total to pay for.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
it requires some programming and we estimate it for 8h. We also replied to your email, so please check your mailbox.
