### ISSUE TITLE
Error.log

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#493]
System Logs
Apache2/error.log
File does not exist: /www/crm.ru/libraries/html5shim/respond.js, referer: http://crm.ru/

CRM Logs
cache/phpError.log

[09-Apr-2015 09:49:12 Asia/Yekaterinburg] 
/www/crm.ru/modules/Vtiger/models/Record.php(278): CRMEntity->retrieve_entity_info(122, 'Accounts')
/www/crm.ru/modules/Settings/DataAccess/models/Module.php(365): Vtiger_Record_Model::getInstanceById(122, 'Accounts')
 /www/crm.ru/modules/Vtiger/models/ListView.php(297): Settings_DataAccess_Module_Model->executeColorListHandlers('Accounts', 122, Object(Accounts_Record_Model))
 /www/crm.ru/modules/Vtiger/views/List.php(184): Vtiger_ListView_Model->getListViewEntries(Object(Vtiger_Paging_Model), '')
 /www/crm.ru/modules/Vtiger/views/List.php(39): Vtiger_List_View->initializeListViewContents(Object(Vtiger_Request), Object(Vtiger_Viewer))
 /www/crm.ru/include/main/WebUI.php(70): Vtiger_List_View->preProcess(Object(Vtiger_Request))
 /www/crm.ru/include/main/WebUI.php(188): Vtiger_WebUI->triggerPreProcess(Object(Vtiger_List_View), Object(Vtiger_Request))
 /www/crm.ru/index.php(22): Vtiger_WebUI->process(Object(Vtiger_Request))
 {main}

Error add accounts

Запись не найдена: 143 Accounts{"success":false,"error":{"code":"\u0417\u0430\u043f\u0438\u0441\u044c \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u0430: 143 Accounts","message":"\u0417\u0430\u043f\u0438\u0441\u044c \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u0430: 143 Accounts"}}

**Comment by waw555** [comment]
[15-Apr-2015 08:24:01 Asia/Yekaterinburg] PHP Warning:  mysqli_real_connect(): Headers and client library minor version mismatch. Headers:50541 Library:50623 in /www/crm.eurolock.ru/libraries/adodb/drivers/adodb-mysqli.inc.php on line 123

**Comment by mariuszkrzaczkowski** [comment]
Send a screenshot of error

**Comment by waw555** [comment]
![errorlog](https://cloud.githubusercontent.com/assets/1402355/7362671/4b310fce-ed86-11e4-82f6-a3463baa9102.JPG)
![errorlog2](https://cloud.githubusercontent.com/assets/1402355/7362672/51b18428-ed86-11e4-994d-c5b5108c2cfd.JPG)
