### ISSUE TITLE
install missing libraries??

### ISSUE THREAD

**Issue by Mpainter701** [YetiForceCompany/YetiForceCRM#4941]
Installed the latest 4.2.0 and when i login it always tells me im missing libraries PHPExcel, mPDF, Roundcube , Gantt, yet when i use the 'Download Library' Function, nothing ever happens?

**Comment by vovpff** [comment]
@Mpainter701 go to system settings and there are needed settings: modules -> modules installation

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8

**Comment by louisyssel** [comment]
I have follwed this exact procedure, but exactly the same happens as the Mpainter701 stated, but I am running version 4.3.0. Click on Download Library, and nothing happens, even tried it on the browser on the local server. Mine is running on AMPPS
