### ISSUE TITLE
Duplicate Button in Quote Module

### ISSUE THREAD

**Issue by lcuevastodoit** [YetiForceCompany/YetiForceCRM#4942]
#### Issue
In the module Quotes, when you open a Quote, the DUPLICATE button in the top right corner, to duplicate a quote, only appears if your user is administrator. Is that behavior normal? Can not a simple user duplicate a Quote?

#### Your Environment
Yeti [ver. 4.0.475]

**Comment by rskrzypczak** [comment]
Check your profile configuration.
![image](https://user-images.githubusercontent.com/10221999/29486597-3da15df2-84ea-11e7-92ad-4ced32542303.png)
