### ISSUE TITLE
Create DAV keys error

### ISSUE THREAD

**Issue by varlog11** [YetiForceCompany/YetiForceCRM#4943]
![animation](https://user-images.githubusercontent.com/1807261/29486025-ad882d32-84ed-11e7-9e42-13d1c2856967.gif)

#### Your Environment
* YetiForce Version used: 4.2.0 and 4.2.59

**Comment by erik7777** [comment]
I am also having issues with the Calendar Integration.  Could you confirm the Correct DAV URL for YetiForce

Thanks

**Comment by erik7777** [comment]
I am also having issues with the Calendar Integration. Could you confirm the Correct DAV URL for YetiForce

Thanks
