### ISSUE TITLE
[BUG] Can not create filter v4.2.68

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4945]
v4.2.68

![1](https://user-images.githubusercontent.com/19627226/29502723-456da1d0-865c-11e7-9bb2-3a993884936f.gif)

**Comment by ezbank** [comment]
it's still exist
![screenshot 46](https://user-images.githubusercontent.com/19627226/29516771-f05f199a-869b-11e7-915b-80fedf6c7f3c.png)

**Comment by konadrian** [comment]
Can you trigger still this error on gitdeveloper version? For me works fine

**Comment by ezbank** [comment]
work fine at the version 4.2.93
