### ISSUE TITLE
Convert Leads

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#495]
Where did the conversion function Leads?

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
if you're asking how to convert a Lead to an Account/Organization, you need to change its status to "Lead obtained" and a button for conversion will appear.
Please see the screenshot:
![zrzut ekranu 2015-04-09 o 19 20 16](https://cloud.githubusercontent.com/assets/10218164/7072591/f211ba84-deed-11e4-90e5-06e31f97be86.png)

**Comment by waw555** [comment]
Yes, Thanks

**Comment by waw555** [comment]
How to convert Leads contact?
When converting I can only see the Account

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/business-processes/marketing-process/122-how-to-enter-new-leads.html

**Comment by KatarzynaUlichnowska** [comment]
You can't convert a Lead to a Contact, you should probably read this article:
https://yetiforce.com/en/business-processes/marketing-process/122-how-to-enter-new-leads.html
It explains how to enter a new company or an individual.

**Comment by waw555** [comment]
I understood little changed approach, all right, legal or natural person shall be Accounts

Thank you very much!

Why is this button?
![check button](https://cloud.githubusercontent.com/assets/1402355/7083708/68f6b0ba-df7e-11e4-8b48-779769fbcaa3.JPG)

**Comment by KatarzynaUlichnowska** [comment]
When you place the cursor on it, a help icon will appear and explain you what it is for. 
When you click on this button you inform that you read and understood all changes performed on this record.

**Comment by waw555** [comment]
The essence of the little I knew, but I did not understand, I introduce changes and they should podverdit?

It seems to me he should confirm who is higher in the post?

Or is it an additional check changes?

**Comment by bpabiszczak** [comment]
This functionality hasn’t been completed yet. It is used to mark records on which new changes were made, but the owner of this record has not reviewed them. Currently there is no appropriate method to verify what kind of changes have been made by other employees on your records. This option will provide similar possibilities to the ones offered by GitHub in the notification icon. It will be possible to disable this functionality in the new version.

**Comment by waw555** [comment]
If you press the button to change the record and making no changes to click save, the button should not appear, because there was no change, and changes in general it would be better to allocate the user to see what has changed, and not looking where and what has changed.

**Comment by Seitrafficonline** [comment]
Hi 
on my crm i dont get any button when lead is converted to obtained. and i wish also to move the lead to client so no button "convert lead" appears. See attached screenshot.
![leads](https://cloud.githubusercontent.com/assets/16775027/13201967/8cb8638e-d890-11e5-9ddf-b38b874e06e0.jpg)
thanks

**Comment by billygoat-trump** [comment]
Hello, I found a change to the new 4.0.0 release, if you want to cover LEAD as a Contact and Account you must select: Lead status = For conversion
