### ISSUE TITLE
Update rules

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4951]
#### Issue

Now I use 4.0.0 stable version but I plan to update to 4.1.0 after some tests at local mirror. How to understand what update package will be final? Now latest update to 4.1.0 has 5th version. Is it final version?

Is it possible to install newest update over already updated system?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by KatarzynaUlichnowska** [comment]
Official releases can be found here: https://github.com/YetiForceCompany/YetiForceCRM/releases
If there is a newer version, it is published in the same place. Version 5 means there were 4 earlier package versions, which were testing versions.
