### ISSUE TITLE
Products search limitation for logistics modules

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4957]
In original VtigerCRM are some limitation available for products picking for invoices and etc. modules. If product active checkbox isn't checked you can not pick this product for invoice items list.

In YetiForce CRM there are no limitation and I can pick any product record what stored in database.

Is it possible to implement this limitation in YetiForce CRM?

**Comment by vovpff** [comment]
Any ideas?

**Comment by mariuszkrzaczkowski** [comment]
Can you describe exactly what is missing from you?
There is a limitation that only active products are available

**Comment by vovpff** [comment]
@mariuszkrzaczkowski maybe I don't understand some mechanisms.
I have database with about 600 products. Some products now can be deactivated (no ability to add them to items list) because quantity is 0 (out of stock) and no longer produced or supported. If I uncheck product active check box I can't see difference. What am I doing wrong?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski 

There are 5 fields available for products:

- Product active
- Sales start date 
- Sales end date
- Support start date
- Support expiry date

I tried different data for this fields to avoid product appearance in dropdown list or pick product popup window but there are no chance to get needed result.

What I must to do to exclude some "old" products from dropdown list?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski if I understand correct this functionality not realized now?

**Comment by mariuszkrzaczkowski** [comment]
Currently this is not possible, we have plans to add it when we have time.
You may want to try adding a condition to the list of products that should work.
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Products/models/Module.php#L27

**Comment by vovpff** [comment]
@mariuszkrzaczkowski sorry for stupid question
Now there are this code at line 27
`$condition = ['and', ['vtiger_products.discontinued' => 1]];`
This line must verify condition: Product Active field is checked but really this condition not works now?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I just added module names to https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Products/models/Module.php#L25 and got needed result. Thanks a lot for your help!

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I checked what I can't find deactivated product in pop up window but this product appears in dropdown list. Any ideas how to hide it?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I checked what changes of https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Products/models/Module.php#L25 and https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Products/models/Module.php#L27 affects only to popup search. Dropdown global search list every time contains deactivated products.

**Comment by paula-w** [comment]
This week we added a new mechanism that allows you to move a record to the archive [eg. products you don’t use], then the record is not visible by default in all views.

**Comment by vovpff** [comment]
@paula-w Thanks you! Cool stuff!
