### ISSUE TITLE
[BUG] Deletion user does not work

### ISSUE THREAD

**Issue by varlog11** [YetiForceCompany/YetiForceCRM#4961]
![animation](https://user-images.githubusercontent.com/1807261/29514500-debece46-8679-11e7-817a-d6becf64aea2.gif)

#### Your Environment

* YetiForce Version used: 4.2 and 4.2.71

**Comment by konadrian** [comment]
@mariuszkrzaczkowski  Error occurs due to missing VtigerModuleOperation file

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
