### ISSUE TITLE
Bug? Update custom module

### ISSUE THREAD

**Issue by DimitryY** [YetiForceCompany/YetiForceCRM#4963]
#### Issue

How to update custom module in production system?

I try to upload new version of custom module to production system and got:
Error!!!
Sorry! Attempt to access restricted file.

![accessrestricted](https://user-images.githubusercontent.com/31202316/29516662-e02310da-8679-11e7-99f0-b8392a79b0cd.png)

Zip file is export from developer system. All server config is same.

How to proper update modules?

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Chrome-64, v.60
* Environment name and version:
* Operating System and version: Debian 9

**Comment by konadrian** [comment]
First, check your logs

**Comment by DimitryY** [comment]
If I delete module and install again - all ok (except losing data :-) )

system.log in attachment.

phperror.log:

[22-Aug-2017 11:04:41 Europe/Moscow] PHP Fatal error:  Uncaught Exception\AppException: Sorry! Attempt to access restricted file. in /home/sales/yetidev/vtlib/Vtiger/Deprecated.php:241
Stack trace:
#0 /home/sales/yetidev/modules/Settings/ModuleManager/views/ModuleImport.php(178): vtlib\Deprecated::checkFileAccessForDeletion('cache/vtlib/use...')
#1 /home/sales/yetidev/include/runtime/Controller.php(90): Settings_ModuleManager_ModuleImport_View->updateUserModuleStep3(Object(App\Request))
#2 /home/sales/yetidev/modules/Settings/ModuleManager/views/ModuleImport.php(33): Vtiger_Controller->invokeExposedMethod('updateUserModul...', Object(App\Request))
#3 /home/sales/yetidev/include/main/WebUI.php(207): Settings_ModuleManager_ModuleImport_View->process(Object(App\Request))
#4 /home/sales/yetidev/index.php(25): Vtiger_WebUI->process(Object(App\Request))
#5 /home/sales/yetidev/public_html/index.php(11): require('/home/sales/yet...')
#6 {main}
  thrown in /home/sales/yetidev/vtlib/Vtiger/Deprecated.php on line 241

[system.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/1241251/system.zip)

**Comment by KatarzynaUlichnowska** [comment]
This requires an individual analysis of the update package for the custom module. We don't do this for free. If you can reproduce the problem on GitDeveloper, record a video, which shows your actions from the beginning.

**Comment by DimitryY** [comment]
Custom module is empty, created from another instance of yeti. Nothing custom functionality. Nothing update code. 
Reproduce: create module using interface. download module. Install module to another instance. Second attempt to install this module with changed version number: error

**Comment by slawekk87** [comment]
I tested this on gitdeveloper version:
Created a new basic module - OK
Exported module - OK
Local developer instance:
Imported module - OK
Change module version in the manifest file and import again:
Error message is displayed, but I can enable a checkbox to update the module, after this I get information about a successful update.
