### ISSUE TITLE
customer portal login details

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#4964]
Hi 
after update to version 4.2 when send customer portal login details  email password is empty .

**Comment by MarekRomanowski** [comment]
the password generator is not implemented since yf v4

U can check email template
Dear $(record : first_name)$ $(record : last_name)$,
Created for your account in the customer portal, below sending data access
Login: $(record : email)$
Password:

**Comment by vahid-jml** [comment]
Hi 
@MarekRomanowski 
i saw email template before. but i don't understand how to set dynamic Password to email template to send assigned password's to every portal user .

**Comment by PercyP** [comment]
Hi,

I believe 4.2 doesn't work with current portal. You have to wait for their upcoming release which is due September?

**Comment by KatarzynaUlichnowska** [comment]
New version of the Customer Portal will be released in a few weeks. Please, be patient because it's worth waiting for. We will publish the info, when the new version is ready.

**Comment by centoasa** [comment]
Still in 4.3 release the field password is empty in email tepleate, so new customers portal will never get desidered password.
