### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#4977]
#### Issue

<a href="https://image.ibb.co/hf23hQ/search.gif"><img src="https://image.ibb.co/hf23hQ/search.gif" alt="search" border="0"></a>
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: <b> GitStable & GitDeveloper </b>
* Browser name and version: <b> Chrome & Firefox </b>
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@alexandr256 maybe cron temportary broken

**Comment by alexandr256** [comment]
On my own system also does not work

**Comment by alexandr256** [comment]
4.2

**Comment by konadrian** [comment]
Check if your cron is running, without it the tables that are taken into consideration while searching are not updated
