### ISSUE TITLE
Password module error

### ISSUE THREAD

**Issue by DimitryY** [YetiForceCompany/YetiForceCRM#4978]
![passerror](https://user-images.githubusercontent.com/31202316/29532661-cfed86d6-86b6-11e7-8414-6ee3179b548b.gif)

I try create password record.
After press "save" button nothing happen.

I see 2 xhr request with params:
First:
__vtrftk:sid:c452179b70772382336e50e48145e7122e5f069e,1503339538
module:DataAccess
parent:Settings
action:ExecuteHandlers
param[mappingRelatedField]:[]
param[module]:OSSPasswords
param[action]:Save
param[record]:
param[defaultCallDuration]:60
param[defaultOtherEventDuration]:60
param[passwordname]:AdmPro
param[popupReferenceModule]:Accounts
param[linkto]:
param[linkto_display]:
param[username]:
param[password]:16NwWoRWLq9RK0
param[link_adres]:
param[assigned_user_id]:1
param[shownerid]:
param[private]:0
param[description]:
param[p_mappingRelatedField]:[]
param[p_module]:OSSPasswords
param[p_action]:Save
param[p_record]:
param[p_defaultCallDuration]:60
param[p_defaultOtherEventDuration]:60
param[p_passwordname]:
param[p_popupReferenceModule]:Accounts
param[p_linkto]:
param[p_linkto_display]:
param[p_username]:
param[p_password]:
param[p_link_adres]:
param[p_assigned_user_id]:1
param[p_shownerid]:
param[p_private]:0
param[p_description]:

Response:
{"success":true,"result":{"success":true,"data":[{"save_record":true}]}}

Second:
__vtrftk:sid:c452179b70772382336e50e48145e7122e5f069e,1503339538
module:OSSPasswords
action:CheckPass
password:16NwWoRWLq9RK0
id:

Response:
{"success":true,"result":{"success":true,"message":""}},

but password list is empty.

May be misconfiguration or any other things?

* YetiForce Version used: 4.2.0
* Browser name and version: chrome-64, v 60.
* Environment name and version:
* Operating System and version: Debian 9

**Comment by konadrian** [comment]
Duplicated https://github.com/YetiForceCompany/YetiForceCRM/issues/4818
