### ISSUE TITLE
Yetiforce Widgets not showing on Home page

### ISSUE THREAD

**Issue by hijab03** [YetiForceCompany/YetiForceCRM#4979]
#### Issue

The Add Widget Tab is showing "No Widgets" when I try to add the widgets.

#### Actual Behavior

"No Widget" showing
#### Expected Behavior

Widgets should be displayed
#### How to trigger the error

![image](https://user-images.githubusercontent.com/19935954/29543498-ed2b15b0-8724-11e7-96c3-258d02a89c74.png)

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: google chrome
* Environment name and version:
* Operating System and version: windows 7

**Comment by vovpff** [comment]
@hijab03 pls make short video how you add widgets step by step

**Comment by hijab03** [comment]
I figured it out. It's fixed now. Thanks

**Comment by rodrigolzd** [comment]
I have the same situation, how is this solved?

**Comment by paula-w** [comment]
Have you added widgets in the admin panel, and given the user permissions in the profile to add new widgets?

**Comment by eprempeh** [comment]
> I have the same situation, how is this solved?
https://github.com/YetiForceCompany/YetiForceCRM/issues/2900#issuecomment-213954663
