### ISSUE TITLE
How can I push data from webform to leads module? 

### ISSUE THREAD

**Issue by hijab03** [YetiForceCompany/YetiForceCRM#4980]
#### Issue

How can I push data from webform to leads module. My original form is currently on jotform and getting data from the website. I want the website data to be directed to Leads module directly. Please help.

**Comment by PercyP** [comment]
Hi,
it used to be done via webforms but this has gone now. I am not sure if there are plans to replace it with something else going forward.

**Comment by reeid** [comment]
I will need working webforms to migrate from vtiger.... this is the only blocker right now. If anyone interested in sharing solutions, I will appreciate it accordingly

**Comment by paula-w** [comment]
It can be done in 2 ways: 1 – writing a script that connects to API [just like the client’s portal works], or 2 – writing a script in the mail scanner and parsing what you receive in mail. Depending on how large the form is it should take from a few to 10+ hours.
