### ISSUE TITLE
Simple workflow calculation not working

### ISSUE THREAD

**Issue by hijab03** [YetiForceCompany/YetiForceCRM#4982]
#### Issue

I want to subtract two currency values (opportunity amount and agreed amount) and update the result in another currency field (balance)

I tried with update field action in workflows and tried it like this:
Opportunityamount- agreedamount 
And put it in balance.
It is not working. Even though i tried with all three fields as integer too. Still not working. 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
Duplicate #4835
