### ISSUE TITLE
YetiForce Calendar Integration Issues

### ISSUE THREAD

**Issue by erik7777** [YetiForceCompany/YetiForceCRM#4983]
I am trying to Integrate the YetiForce Calendar with Outlook and Android Calendars.

1.  Could some one please provide the Yetiforce Location of the DAV URL.

2.  How is the DAV Key Used?

3.  Is the DAV Username and Password the same as the YetiForce Account username and Password.

Thanks

**Comment by bpabiszczak** [comment]
Please check this tool: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Dav&view=Keys&block=5&fieldid=77
