### ISSUE TITLE
Brak reakcji na aktualizacje

### ISSUE THREAD

**Issue by MariuszWin** [YetiForceCompany/YetiForceCRM#4985]
Witam serdecznie!

Posiadam wersje YetiForce 3.1.0, ktora chcialbym zaktualizowac do najnowszej wersji. Sciagnalem wszystkie potrzebne paczki i przy probie wczytania pierwszej, czyli 3.1.0 do 3.2.0 nie dostaje zadnej informacji o powodzeniu, lub niepowodzeniu. Ponizej dolaczam screeny ekranu, ktory pojawia sie po probie uploadu, drugi screen to logi z serwera, jedyna informacja jaka jest odnosnie aktualizacji to proba wczytania za duzego pliku, co zostalo rozwiazane z poziomu serwera. Niestety nie jestem pewien jak poradzic sobie z tym problemem przez brak jakiegokolwiek punktu zaczepienia w postaci komunikatu. Czy jest mozliwosc, ze problem lezy po stronie serwera? 

Pozdrawiam 

![desktop](https://user-images.githubusercontent.com/31240188/29558888-c117a426-872d-11e7-8b2c-6700683035f1.png)

![errorlog](https://user-images.githubusercontent.com/31240188/29558543-aff5e014-872c-11e7-8487-aa60968450ef.png)

**Comment by bpabiszczak** [comment]
Czego to są logi? serwera czy aplikacji? Z tego co widzę serwera, więc proszę włączyć logi aplikacji i ponownie uruchomić aktualizacje na czystej kopii.

**Comment by MariuszWin** [comment]
Problem rozwiązałem poprzez instalację nowej wersji od zera, przepraszam za kłopot i dziękuję za odpowiedź.
