### ISSUE TITLE
 Sales > Opportunities > Detail > nazwa_szansy > Time Control. Nie ładują się wykresy

### ISSUE THREAD

**Issue by kristek92** [YetiForceCompany/YetiForceCRM#4986]
Dzień dobry
Chciałbym zgłosić poniższy problem.
Po dodaniu czasu pracy i przejściu ścieżki podanej w tytule pojawia się ekran ładowania i nie pojawiają się wykresy dotyczące czasu pracy. 
Problem ten nie występuje np dodając czas pracy w module projekty. Po przejściu ścieżki  Realization > Projects > Detail > nazwa_projektu > Time Control. Wykresy pojawiają się normalnie.

**Comment by bpabiszczak** [comment]
Wersja? Czy błąd występuje na gitdeveloper?

**Comment by kristek92** [comment]
4.1.0 własny hosting
oraz
4.2.81 demo ze strony https://gitdeveloper.yetiforce.com/

**Comment by bpabiszczak** [comment]
Nie rozumiem odpowiedzi, czy punkt drugi to pytanie czy odpowiedź. Jeżeli odpowiedź, to proszę nagrać filmik z przykładem lub opisać krok po kroku.

**Comment by kristek92** [comment]
Napisałem na których wersjach występuje ten problem (testowałem dwie - jedną na własnym hostingu, oraz drugą - Państwa demo online z podanej wyżej strony).
Jeżeli nadal nie rozumie Pan o co mi chodzi to podeślę dokładny opis.
