### ISSUE TITLE
[CRITICAL BUG] Can not create record when users at new profiles created

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4998]
v4.0 - v4.2.86
If you hidden field website of lead module. You can not create record **(fixed v4.2.98)**
![zalo_screenshot_23_8_2017_244699](https://user-images.githubusercontent.com/19627226/29596674-68f9c0c4-87e8-11e7-9ac9-dcd9b5a488c8.png)

![1121](https://user-images.githubusercontent.com/19627226/29596681-723ccbcc-87e8-11e7-9e15-d409b093b534.gif)

**Comment by ezbank** [comment]
Hi! @mariuszkrzaczkowski  , I can not create lead record with custom profiles.
v4.2.98
Tested on https://gitdeveloper.yetiforce.com
![1](https://user-images.githubusercontent.com/19627226/29667114-5efa0ec6-8905-11e7-8802-de74279f5be9.png)
![2](https://user-images.githubusercontent.com/19627226/29667115-5f07be18-8905-11e7-89cf-cb28227468c8.png)
![1121](https://user-images.githubusercontent.com/19627226/29667120-63f60394-8905-11e7-987e-87f6c32c0f0d.gif)

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
