### ISSUE TITLE
Feature request: Pre-populate required date fields

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#50]
If a date or time field is required, pre-populate it with the current date / time.

**Comment by bpibiza** [comment]
improvingly, in time of edition fields, if the start date is pre-populated with current date and has change for the expected date, the second filed in this module (expected end date field) should change for the date not sooner than the start date.

**Comment by bpibiza** [comment]
maybe something like that ?! http://jqueryui.com/datepicker/#date-range

**Comment by bpabiszczak** [comment]
This solution has existed since early versions of Vtiger 5.x. All you have to do is to put an appropriate value in the table: vtiger_fields, in the column: typeofdata, e.g. D~O~OTH~GE~start_date~Start Date
