### ISSUE TITLE
If condition in Yetiforce

### ISSUE THREAD

**Issue by vppismail** [YetiForceCompany/YetiForceCRM#5011]
Could anybody help me like if condition as mentioned below:-
If date field is expired, another filed must display " EXPIRED" otherwise "VALID"
I am beginner in CRM, and I wanted to store license information for the customers so, when I fill the details of license details and after saving the record I wanted to see the status of the license like aforementioned.
Thanks,

**Comment by konadrian** [comment]
You can do this by workflow 
https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=List

**Comment by vppismail** [comment]
Thank you for the help!!
If you dont mind, can you pls help me to do this.
Thanks in advance

**Comment by vppismail** [comment]
Duplicate of # please anybody can help me?

**Comment by ldgbc** [comment]
@vppismail if you still around, I suppose you would do it like that Issue #7359 I linked. Create a Task Event or Update Field instead.
