### ISSUE TITLE
bug with PHP7

### ISSUE THREAD

**Issue by sbruimen** [YetiForceCompany/YetiForceCRM#5022]
https://github.com/YetiForceCompany/YetiForceCRM/blob/909654c5a1d0b1edde73dcb1967aeaf5cabf4bb4/modules/Settings/PBXManager/models/Record.php#L70

--		                $parameters = ‘’;
++	                $parameters = array();

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/cc36b393c875cb93636cd48ca8fa1e01993dd440
You can make changes yourself and create a pull request

**Comment by sbruimen** [comment]
I am not developer, don't have environment and have not enough experience to commit pull request. Sorry.
