### ISSUE TITLE
 I want guidance to add custom field to global search can you please direct me that link

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#5027]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4,2
* Browser name and version:Mozilla 
* Environment name and version:PHP 5,6
* Operating System and version:Opensuse 4.2

Hi 
I want guidance to add custom field to global search can you please direct me that link

**Comment by setras** [comment]
did you try this settings page 
https://gitstable.yetiforce.com/index.php?module=Search&parent=Settings&view=Index&block=13&fieldid=56
