### ISSUE TITLE
[BUG] Quick Prewview v4.2.100

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5032]
![img_0158](https://user-images.githubusercontent.com/19627226/29699429-dcbb7b8e-8986-11e7-9fb8-1dc270e8f29b.PNG)

**Comment by ezbank** [comment]
still on v4.2.143

**Comment by slawekk87** [comment]
I checked on 4.2.0 and gitdeveloper and can't reproduce problem. Please attach full text of debug message and informations about permissions configuration related to the record.
