### ISSUE TITLE
Downgrade from 4.2.0 to 4.1.0

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#5033]
Hello there,

Does it possible to revert my upgrade from 4.1.0 LTS to the update package 4.2.0?
I got a lot of issues with permissions and blank reports.

My system is a lamp on ubuntu 16.04.3.

Thank you

**Comment by PercyP** [comment]
Hi @Raggazzoo 

do you have a backup? Thats the fastest way to revert back.
