### ISSUE TITLE
Mapa projektów

### ISSUE THREAD

**Issue by MariuszWin** [YetiForceCompany/YetiForceCRM#5034]
Witam ponownie!

Nie jest to problem, może bardziej pytanie. Czy istnieje możliwość dodania projektów do mapy, na takiej zasadzie jak kontrahentów i współpracowników? Czy jest może już zaimplementowana oddzielna mapa na same projekty właśnie?

**Comment by bpabiszczak** [comment]
Nie rozumiem, chodzi o wrzucenie na mapę open street map? Dane lokalizacyjne byłyby pobierane z kontrahenta podpiętego pod projekt?

Jeżeli o to Tobie chodzi, to obecnie nie ma takiej możliwości, potrzebujemy około 1-2 dni roboczych aby coś takiego dodać [cały mechanizm jest gotowy], tylko nie ma komu za to zapłacić.

**Comment by MariuszWin** [comment]
Chodzi bardziej o to, żeby w podczas dodawania nowego projektu była możliwość podania lokalizacji tego projektu. Moja firma zajmuje się projektami w różnych lokalizacjach i dużym ułatwieniem byłaby możliwość zobaczenia na mapie wszystkich lokalizacji do których wysyłamy pracowników. Tak samo jak mogę zobaczyć wszystkich kontrahentów i klientów. Jeśli jest to niemożliwe na dzień dzisiejszy, to rozumiem.

**Comment by bpabiszczak** [comment]
ale przecież ta inne lokalizacja [w większości przypadków] jest oddziałem klienta [no chyba, że ktoś buduje autostradę], wówczas zamiast klienta wskazujemy jego oddział. Chyba, że mamy tu przypadek, że lokalizacja nie ma nic wspólnego z żadnym oddziałem klienta. 

Dodać to możemy, ale pytanie nadal pozostaje, kto za to zapłaci?

**Comment by MariuszWin** [comment]
Buduje autostradę, albo kładzie światłowody. :)
Ja naprawdę rozumiem, nie wiem kto za to zapłaci, zadałem pytanie czy jest taka funkcjonalność, nie wymuszałem implementacji. Dziękuję za odpowiedź raz jeszcze.

**Comment by bpabiszczak** [comment]
Mechanizm był tak projektowany, że bez problemu to obsłuży, potrzeba tylko dokończy go dla procesów [projekty, umowy sla, szanse sprzedażowe] i dla podprocesów [zgłoszenia, oferty, zamówienia, faktury itd.].
