### ISSUE TITLE
Filter issue again

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#5035]
#### Issue
Contacts -> filters
When a filter has a selector set to 'contains' or "does not contain" and then one or more items from a dropdown field set, it fails.

We had this before in v2 or v3 which was fixed with an update and suddenly popped up again in V4.0 a few month ago. There was no update done or what so ever. We even started clean with v 4.0.

#### Actual Behavior
Even thought the filter is set to "does not contain" it still shows the records

#### Expected Behavior
Filter working and not showing excluded records

#### How to trigger the error
Always there. Could not replicate in a fresh version.

#### Your Environment

* YetiForce Version used: 4.2 but started in v4.0 and did not change in 4.1 or 4.2
* Browser name and version: Chrome OSX
* Environment name and version: Ubuntu 14LTS with Nginx proxy PHP 7

Screenshot shows filter setting and the result still containing the records excluded.

<img width="260" alt="screen shot 2017-08-25 at 10 47 35" src="https://user-images.githubusercontent.com/10379403/29706867-95615b6c-8983-11e7-9acc-60969df543a2.png">
<img width="932" alt="screen shot 2017-08-25 at 10 46 54" src="https://user-images.githubusercontent.com/10379403/29706869-95665acc-8983-11e7-8627-ac36efd1711c.png">

**Comment by konadrian** [comment]
If I corectly understand your problem , then for me on current dev version it's working fine
![animation](https://user-images.githubusercontent.com/3193498/29808594-13321f50-8c99-11e7-9257-370c04583b1e.gif)

**Comment by zebrahosting** [comment]
Hi guys, yes we noticed that is does not show up on all CRM instances we run. More worrying it was there one day after we run the CRM for a while.
We have reinstalled the CRM several times since v1.0 to make sure not to inherit issues from the past but have a lot of custom fields and pictures who can not transfer over. Every rebuild takes a lot of time so was hoping we could distille the issues from the previous fixes and point where that was solved. Of course it is strange it seems isolated to one setup and secondly. can popup suddenly.
All upgrades 4.0-> 4.1 -> 4.2 went smooth but did solve the issue. 

The old discussion: https://github.com/YetiForceCompany/YetiForceCRM/issues/1757

Has anything changed /  fixed after v 4.2? Not too eager to put a dev version over our production CRM but if there is a clear fix/file it is no problem of course.

**Comment by paula-w** [comment]
If something works properly in one version, but not in the other, it means that the systems differ from each other [either different files or configuration]. Sometimes when someone copies a system, file’s EOL changes and that can “break” the system. Unfortunately, each of these cases should be investigated individually, if it works on gitdeveloper then we don’t take care of the issue. Then it’s best to buy a support package and keep it for emergency situations like this.
We do our best to make sure each new version includes as few errors as possible, but the stability of our solution depends mostly on the community. The more errors the community finds, the more we can fix. Unlike Vtiger, SuiteCRM, or ODOO, we fix errors on an ongoing basis.
