### ISSUE TITLE
Centos minial install 7.3 php errors

### ISSUE THREAD

**Issue by timguyuk** [YetiForceCompany/YetiForceCRM#5038]
#### Issue
Installed centos minial 7.3 install which I have done many times for various opensrouce server solutions. php, etc all yum installed. When I try and run yeti I get the 500 error, looking at the httpd logs I get the following: 

PHP Fatal error:  require(): Failed opening required '/var/www/html/yeti/vendor/sabre/uri/lib/functions.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/yeti/vendor/composer/autoload_real.php on line 67

Originally I had
PHP Fatal error:  Can't use function return value in write context in /var/www/html/include/Webservices/PreserveGlobal.php on line 20

Are these simply permission errors or should I be looking somewhere else. I have set what I thought were correct permissions but I could be wrong, I'm not an expert.

Tim

* YetiForce Version used: What ever is version 25/08/2017
* Browser name and version: Edge and IE
* Environment name and version: Centos 7.3 apache,php yum installed 
* Operating System and version: Centos 7.3

**Comment by slawekk87** [comment]
Please provide environment information

**Comment by KatarzynaUlichnowska** [comment]
Did you download YetiForceCRM-4.2.0-complete.zip or something else?
There have already been a few similar issues:
#4582
#4043
#4004
#4582
