### ISSUE TITLE
HTTPS encryption emails

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#5039]
All our sites run under SSL (of course) but still the whole team gets messages like:

HTTPS encryption
Your connection to the server is not encrypted. If the connection is not established through the HTTPS protocol the communication may be intercepted or altered by third parties. The recommended configuration can be found in the "Web server requirements" article in the documentation.

Where can we switch this off? It's clearly fault and send to way to many people. Not a good idea....

**Comment by KatarzynaUlichnowska** [comment]
Hello, do you mean email notifications?
This [link](https://github.com/YetiForceCompany/YetiForceCRM/commit/baaad98bcf4b07131b3d5e1954a42ef38325a92f) may fix your problem but we are not sure if we understand you correctly. If not, please explain more.

**Comment by bpabiszczak** [comment]
They are all administrators? There should be only one administrator in the system :]

**Comment by zebrahosting** [comment]
Katarzyna, thank you for pointing me to the fix.
