### ISSUE TITLE
Advanced permissions not working properly

### ISSUE THREAD

**Issue by janecekmato** [YetiForceCompany/YetiForceCRM#5046]
Hello,
i am trying to set advanced permissions for specific user through:
Software configuration > Permissions > Advanced permissions

But every time i will try grant advanced permissions for user, this user cannot see anything from selected module.

My settings:

<img width="687" alt="snimka obrazovky 2017-08-28 o 4 13 50" src="https://user-images.githubusercontent.com/12688336/29756849-8ccba0fe-8ba7-11e7-914a-262d95a9154d.png">
<img width="1185" alt="snimka obrazovky 2017-08-28 o 4 14 08" src="https://user-images.githubusercontent.com/12688336/29756851-936f1526-8ba7-11e7-8cc3-e00bcfd99bd3.png">

I tried many combinations.

I have active cron, and 'CACHING_PERMISSION_TO_RECORD' => true,

Maybe I not properly understand this functionality.

My second question is, is it possible to add "Share with users" field to custom created module ?

Thanks

YetiForce Version used: '4.1.0',
Browser name and version: Chrome OSX - latest

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.

**Comment by mariuszkrzaczkowski** [comment]
Can you check this on the gitdev version again?

**Comment by janecekmato** [comment]
Hi sorry for my late reply, did you mean use this: 4.1.0_to_4.2.0 update ?
everytime when i try to use this update i will get blank page

my php version: 5.6

**Comment by janecekmato** [comment]
hello i can confirm that in dev version it is working
