### ISSUE TITLE
Adding external code to the footer area - it worked in vtiger but not in Yetiforce

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5061]
Hi,

I have an external component that I want to display in the yetiforce footer area. I used to be able to do this in Vtiger, but the same processes for displaying it don't work in yetiforce. 

Basically it is a chat bar. In the old vtiger I used to edit 2 files:

/crm/layouts/vlayouts/modules/vtiger/header.php

I added the following code just after the opening head tag:

<link type="text/css" rel="stylesheet" id="arrowchat_css" media="all" href="../arrowchat/external.php?type=css" charset="utf-8" />
<script type="text/javascript" src="../arrowchat/includes/js/jquery.js"></script>
<script type="text/javascript" src="../arrowchat/includes/js/jquery-ui.js"></script>

and:

/crm/layouts/vlayouts/modules/vtiger/footer.php 

I added the following code just before the closing body tag:

<script type="text/javascript" src="../arrowchat/external.php?type=djs" charset="utf- 8"></script>
<script type="text/javascript" src="../arrowchat/external.php?type=js" charset="utf- 8"></script>

This used to work fine. 

In Yetiforce I am adding the same code to /layouts/basic/modules/Vtiger/header.php and /layouts/basic/modules/Vtiger/footer.php

But it doesn't display.

Is the file I need to edit to show this component somewhere else now? Or are these the only 2 files that control the footer/header?

Does the code need to go somewhere else?

Any advice would be most appreciated

**Comment by KatarzynaUlichnowska** [comment]
1. This kind of advice is beyond what we call free support.
2. jQuery is loaded by default, so you don't have to load it manually - it may cause problems in version compatibility. 
3. Use vtiger_links, we expanded them quite a lot and they should help with your problem.

**Comment by ldgbc** [comment]
@PercyP how did you go with this issue? Manage to solve it?

**Comment by PercyP** [comment]
@ldgbc 

I didn't explore it further (got side-tracked) it is something I hope to go back to.
