### ISSUE TITLE
Image and Multiimage field.  How to enable it? 

### ISSUE THREAD

**Issue by serbiaserbia** [YetiForceCompany/YetiForceCRM#5063]
How to enable to get available new field (from user interface)  type Image or Multiimage field. 

Saw that 4.1 have added new uitype Multiimage field,  but can see it in menu when adding new field. 

#4465 in this question it is answered that it is temporarly disabed (ver 4.0 dev),  

Does anyone know how to enable it?

**Comment by vovpff** [comment]
@serbiaserbia I think you can activate them manually in database but this fields can be buggy an unstable for this time

**Comment by KatarzynaUlichnowska** [comment]
This field has been disabled because it isn't finished.
It works in the basic version but has bugs.

**Comment by PercyP** [comment]
@KatarzynaUlichnowska 

I had this built for my system. Will this mean my version also has errors/is not working correctly? As I upgraded to 4.2 recently.

**Comment by serbiaserbia** [comment]
@percyp how did you activeted this fields? 
Do I have to change some code?  And where?

**Comment by PercyP** [comment]
@serbiaserbia 

Go to: yetiforce/modules/Settings/LayoutEditor/models/model.php

then I think you remove this bit 

**//

from the following code - just before Multiimage (including the asterixes after it):

	public function getAddSupportedFieldTypes()
	{
		return [
			'Text', 'Decimal', 'Integer', 'Percent', 'Currency', 'Date', 'Email', 'Phone', 'Picklist', 'URL', 'Checkbox', 'TextArea', 'MultiSelectCombo', 'Skype', 'Time', 'Related1M', 'Editor', 'Tree', 'MultiReferenceValue', 'jsign','CategoryMultipicklist'**//, 'MultiImage'**

After that, you should see it in the Add custom fields bit. 

It seems to work perfectly in mine.

**Comment by mariuszkrzaczkowski** [comment]
This field has not yet been added a security layer and this field can be completely rebuilt. By doing this, you can simplify the data in these fields after the update

**Comment by serbiaserbia** [comment]
@Percyp great,  thanx a lot for fast answer.  You are king  😉

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

does this mean my version is risky?

**Comment by PercyP** [comment]
@serbiaserbia 

you are welcome. If we can each answer questions it takes the pressure of the developers who are busy working on all the more important stuff. So more people should post solutions here to 'lighten the load'. At least that is what I think.

**Comment by mariuszkrzaczkowski** [comment]
I do not know, maybe he will finish the field without big changes then it should work. That's why the field was turned off

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 
thanks for response. Sure they will let me know if my live version is 'risky' Anyway, I am guessing in the update of 4.3 its going to be addressed so I don't need to be worrying? My live version doesn't go 'live' anyway until end of September :O)

**Comment by mariuszkrzaczkowski** [comment]
I do not know in which version it will be finished.

**Comment by paula-w** [comment]
Right now adding the support for uploading many images at the same time is not in our schedule.
