### ISSUE TITLE
[BUG] PDF Templates Generator

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#5067]
#### Issue

I am trying to create a new pdf for invoices and i see that there is a bug when save template. The template is saved but all containing info are not displayed correctly.
for example: i want to put a text in footer section to be centered., when i save this, get back on left side.
I see the problem is the same on testing gitstable.yetiforce.com .

#### Actual Behavior

I can't work with this if the text arrangement is not saving.
#### How to trigger the error

1. Fix errors when saving template, to memorize all text formatting.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Google Chrome, Mozlla Firefox
* Environment name and version:
* Operating System and version:

**Comment by KatarzynaUlichnowska** [comment]
Hello, we haven't received enough info. Could you please make a short video and send us an example of a template?

**Comment by cristyxx** [comment]
I don't know how to make a video.
Please try to make a template in stable version from gitstable.yetiforce.com and save it, and after get back to modify template, and you will see how template format is saved.

**Comment by bpabiszczak** [comment]
http://www.screentogif.com/
