### ISSUE TITLE
The 'Add' glyphicons missing in Roundcube 

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5073]
When you open email in Roundcube the little 'add' glyphicons are missing. I think it is because it is looking for them in the old path of crm/libraries/bootstrap3/css/glyphicons.css

The bootstrap3 folder has now been moved under the public_html folder.

Where is the code that tells yetiforce where to look for this file so I can change the path?

Kind regards

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.

**Comment by PercyP** [comment]
Great thanks.

**Comment by PercyP** [comment]
Can I ask how I would repair mine until the new release is issued? Is there a particular file I could edit?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/lib_roundcube/commit/0b995a7f19b572fe603d5b171b75d7dfbd0f06d4
