### ISSUE TITLE
Style of left record actions

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5075]
I think if they are displayed the same then it would be better
![x](https://user-images.githubusercontent.com/19627226/29821469-446f32ac-8cf2-11e7-9791-a9c64fdfbbb6.png)
![z](https://user-images.githubusercontent.com/19627226/29821470-44910d14-8cf2-11e7-8cea-1d68d03ea531.png)

**Comment by paula-w** [comment]
Unfortunately we’re not planning to change that right now. In a few weeks we will optimize each view in the CRM, so there will be some changes in the appearance and maybe then we can fix it. Until then it’s going to stay like this.
