### ISSUE TITLE
Roles configuration question

### ISSUE THREAD

**Issue by lcuevastodoit** [YetiForceCompany/YetiForceCRM#5078]
Hi Yetiforce and thanks again for you CRM. A question
What does mean these options in the "related to record access part" in Role Configuration?

- Inactive
-  "parent record" 
- "according to hierarchy"

Version Yeti 4.0.475

**Comment by paula-w** [comment]
The system allows for inheriting permissions, which means that if we have access to a client then we can have access to projects related to him, and when we open a project – to tasks related to it. It works even if a user doesn't have access to view these records on the records list.

- for Projects the parent module is Account
- for Project Task the parent module is Project
- Hierarchy means Account → Project → Project task
