### ISSUE TITLE
Advanced permissions not working on new/edited records without recalculate perms

### ISSUE THREAD

**Issue by janecekmato** [YetiForceCompany/YetiForceCRM#5083]
When I will create advanced permission through:
Software configuration > Permissions > Advanced permissions
<img width="687" alt="snimka obrazovky 2017-08-28 o 4 13 50" src="https://user-images.githubusercontent.com/12688336/29871025-9142aaee-8d8a-11e7-9804-0746b73bc1f7.png">
<img width="1185" alt="snimka obrazovky 2017-08-28 o 4 14 08" src="https://user-images.githubusercontent.com/12688336/29871026-9143ea80-8d8a-11e7-84da-7b8641a9ee0d.png">

i  recalculate permissions and everything work correctly. But When i add new record, or change status, user cannot see new record, or existing record is not showed/hided.

When i again recalculate permissions everything work correct. 

Is it correct behavior ?

Thanks

php: 5.6
yetiforce: dev version

**Comment by paula-w** [comment]
Is your cron active?
Did you enable advanced permissions in configuration?

**Comment by janecekmato** [comment]
yes, i enabled it, and i manually run cron through domain/cron/vtigercron.php (only for test purpose)
i hope that it is enough

**Comment by paula-w** [comment]
You have to check the logs to see if cron was fully executed. We don't know how your permissions are configured, so we'll need more info to be able to help. Try to trigger that error [here](https://gitdeveloper.yetiforce.com/index.php#), and let us know what happened.

**Comment by janecekmato** [comment]
CACHING_PERMISSION_TO_RECORD is not configured in this test which you send to me

**Comment by waran70** [comment]
What cron doing together with permissions? Am I missing something?

**Comment by janecekmato** [comment]
i think that cron must recalculate permissions after you make some changes (and maybe also after you create/edit records)

**Comment by mariuszkrzaczkowski** [comment]
You need to give us more information, maybe a screenshot of all the configuration panel from the permissions. Or simply buy out support

**Comment by janecekmato** [comment]
Hello, i understand. 
Ok so I am sending you screenshot module access, advanced permissions is already here (only this one settings is setted in advanced permissions). If it is not enough for understeding this bug, i can send you you admin login details (it is fresh installation only for testing purpose)

thank you

<img width="1371" alt="snimka obrazovky 2017-09-02 o 17 29 53" src="https://user-images.githubusercontent.com/12688336/29996782-5ae7ad0a-9005-11e7-80bf-bf1e90a72a36.png">

**Comment by vovpff** [comment]
@janecekmato there was bug with permission if you use switch user feature. I'm not sure this bug is fixed. Maybe this a cause of problem.

**Comment by janecekmato** [comment]
@vovpff  hello, thanks, this feature was setted like default settings in fresh installation

**Comment by paula-w** [comment]
We fixed advanced permissions several times, please check if the problem exists on the gitdeveloper version. If it does – record a video how to trigger the error and open a new issue.
Some of our clients use this so it should work properly.
