### ISSUE TITLE
E-Mail Autologin - Button no available

### ISSUE THREAD

**Issue by cybworld** [YetiForceCompany/YetiForceCRM#5084]
Hello,

I Think i have found a bug ?!?

#### Issue
Since V 4.1,  also in 4.2
I can not see the configuration "E-Mail Autologin" anymore.

#### How to trigger the error
![image](https://user-images.githubusercontent.com/26028405/29881577-4127a926-8dab-11e7-970a-de429771127f.png)

NOT AVAILABE - Page does not change

What can i do?

#### Your Environment

* YetiForce Version used: 4.1 & 4.2
* Browser name and version: Chrome 60.0.3112.113 (64-Bit)
* Environment name and version: Debian 8
* Operating System and version: Windows 10 - 1703(64-Bit)

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/29890055-8f5b1dd8-8dc6-11e7-93c8-179678a7dc48.png)

https://gitstable.yetiforce.com/index.php?parent=Settings&module=Mail&view=Autologin&block=8&fieldid=78

Can you write more information?

**Comment by cybworld** [comment]
I'll try it :)

Normally, a selection button appears during configuration.
(See picture above)
In 4.0 it still works.
And also in the demo here it does not work.

Without this confirmation, you can not log in directly using the e-mail button.
The RoundCube login always appears.
So, at users / e-mails are newly created.
Where the function was configured before, it is still...

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/5155
