### ISSUE TITLE
Sales procedure logic broken

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#5085]
I see that Sales order is not tied to invoice anymore. Just to remind correct sales flow pls see attached.
On each step should be allowed conversion of base to related module.
![simplified](https://user-images.githubusercontent.com/6852348/29904954-c31804c8-8e35-11e7-8d34-eefeefb142d7.png)

**Comment by PercyP** [comment]
@waran70 

I was about to post similar. I am sure we used to be able to convert each one to the other at the click of a button. I went to do this earlier and noticed it is no longer possible. This is such an important process for us so hope it isn't deleted permanently?

**Comment by SkavenKF** [comment]
This is also a standard process for us. It is cumbersome with every update to check whether something has changed in process. We must then map the following processes over workflows, if they work at all after an update. Users must also receive appropriate training.
This also increases training expenses and operating costs.
A nice solution would be this in the settings to determine whether one would use the standard process.

**Comment by paula-w** [comment]
We are currently describing the processes in the https://www.visual-paradigm.com/ program.
They will first be described in Polish and then in English. When we finish the documentation we will publish it and then we can discuss processes.
