### ISSUE TITLE
Vtiger 7 google sync module

### ISSUE THREAD

**Issue by Lucipher** [YetiForceCompany/YetiForceCRM#5099]
Can Vtiger7 google sync module migration to YetiForce?

**Comment by paula-w** [comment]
We’re not planning to move this functionality to YetiForce. There’s the CalDAV mechanism in YetiForce that we think is a better solution and we will expand and improve this mechanism.

**Comment by Lucipher** [comment]
CalDAV is more trouble, the user needs to set up gmail, since there are ready to use why not use it.
