### ISSUE TITLE
remember user's decision about sorting a columns (which and what direction) will be a good solution

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#51]

**Comment by bpabiszczak** [comment]
We rebuilt the entire menu and as one of its elements we added a possibility to provide links to views - unfortunately saving the views [as well as saving sorting and its directions in the future] may mislead. Probably, we won't add such functionality automatically, in the future we will add a possibility to sort and set a column by which sorting will be done directly in a filter. Switching views will always reset to parameters indicated in the view and not to those set a minute ago.
