### ISSUE TITLE
Permissions Denied for Child Role records on Private Access settings

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#5103]
#### Issue

<img src="https://image.ibb.co/kXC1Ja/role.jpg" alt="role" border="0">

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
In our opinion, there is no error in here. If you think there is an error, please provide us with some description, screenshots only aren't enough for us to understand what you mean.

**Comment by alexandr256** [comment]
If the access module is set as private, then the child role entries are not available for the parent role. The entries are visible in list mode, but the detailed view is access denied
