### ISSUE TITLE
Błąd przy instalacji

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#5104]
Witam serdecznie
 Witam Wyświetla mi się błąd podczas instalacji SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dtsserwispl_6.s_yf_companies' doesn't exist Failed to prepare SQL: SELECT * FROM `s_yf_companies` WHERE `default`=:qp0  Proszę o pomoc

**Comment by bpabiszczak** [comment]
Jaka wersja YetiForce i jakie parametry serwera?

**Comment by Irmina8591** [comment]
Wersja najnowsza pobrana w piątek z github. Serwer nie należy do mnie więc ciężko mi powiedzieć (dostałam jedynie dane logowania) ale podczas instalacji wszystko się zgadzało. Zauważyłam jednak że osoba tworząca bazę danych dała metodę porównywania napisów Latin 1 , zamiast standardowej utf8. Czy to może być przyczyna? błąd wyskakuje przy próbie instalacji po wprowadzeniu i sprawdzeniu danych. Obecnie wgrałam spowrotem czyste pliki.

**Comment by bpabiszczak** [comment]
Pytanie pozostaje to samo, jaka wersja systemu? Bez tego nie ruszymy dalej :]

**Comment by Irmina8591** [comment]
4.2.0 Complete

**Comment by bpabiszczak** [comment]
Proszę odpalić instalacje na jakimś publicznym hostingu np. home.pl, mają za darmo przez 14 dni i spróbować tam zainstalować system, jeżeli się nie uda, proszę przesłać do nas dane dostępowe i logi, sprawdzimy co jest przyczyną. Jeżeli problem leży po stronie aplikacji to poprawimy to i prześlemy poprawioną paczkę instalacyjną.

**Comment by Irmina8591** [comment]
Witam ponownie
W programie instalacyjnym na czerwono podświetla mi się " Apache/2" 
Mamy hosting na nazwa.pl czy to może być przyczyna błędu i czy da się to naprawić czy konieczny jest inny serwer?

**Comment by Irmina8591** [comment]
Bo na moim prywatnym serwerze livemarket udało się zainstalować

**Comment by Irmina8591** [comment]
Na panelu instalacji znalazłam coś takiego 
Warning: PDO::query(): MySQL server has gone away in /home/dtsserwispl/ftp/biuro/include/database/PearDatabase.php on line 301

Fatal error: Call to a member function rowCount() on boolean in /home/dtsserwispl/ftp/biuro/include/database/PearDatabase.php on line 452

**Comment by Irmina8591** [comment]
Warning: PDO::query(): MySQL server has gone away in /home/dtsserwispl/ftp/biuro/include/database/PearDatabase.php on line 301

**Comment by Irmina8591** [comment]
Niestety, mimo prób nic nie wyszło z instalacji na hostingu nazwy, udostępniłam inny serwer lecz zauważyłam że opcja importu danych  nie działa.

**Comment by bpabiszczak** [comment]
Jutro/Pojutrze sprawdzimy czy działa instalacja na nazwa, jeżeli tak to nagram filmik. Możemy też pomóc odpłatnie, wówczas technik wejdzie na serwer i sprawdzi problem bezpośrednio na serwerze.

**Comment by mariuszkrzaczkowski** [comment]
Przetestowaliśmy instalację wersji 4.2.0 oraz wersji deweloperskiej i działa poprawnie.
Możesz poszukać pomocy w zamkniętych issues https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20install
