### ISSUE TITLE
Filters with conditions search broken

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#5105]
<img src="https://image.ibb.co/daTnbv/filter.gif" alt="filter" border="0">
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Can you check this on the gitdev version again?  The bug doesn’t exist in the newest version.
