### ISSUE TITLE
AccountsByIndustry and EstimatedValueByStatus widgets don't work since 4.0

### ISSUE THREAD

**Issue by Raggazzoo** [YetiForceCompany/YetiForceCRM#5108]
Hi there !

I got an issue with two widgets created by the YF team.
AccountsByIndustry and EstimatedValueByStatus stop to work since 4.0.

Today I'm in 4.1 LTS and the issue is till there.
I tried to go with 4.2 but no change.

Thank you in advance

**Comment by slawekk87** [comment]
I created two widgets on gitdeveloper and all seems to work ok.
![5108](https://user-images.githubusercontent.com/22735929/30369135-bafb2638-9873-11e7-87da-e99e321619b5.png)

**Comment by Raggazzoo** [comment]
Hello,

I tried to upgrade my dashboard widgets to the latest stable version and te result is the same.
I got this error
![image](https://user-images.githubusercontent.com/1357727/30380088-e9822b12-9898-11e7-965d-a08e0d53ae89.png)

Thank's

**Comment by mariuszkrzaczkowski** [comment]
Test the developer version
