### ISSUE TITLE
Add Module Profile  are "Invisible"

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#5109]
#### Issue

When enable "Storages" Module (for example), I can't see module, and in Profiles all Fields are "invisible".
 See Profiles Screen, this is Administrator Profile
![image](https://user-images.githubusercontent.com/3030997/30035182-c139ae9a-917d-11e7-8473-be4c78902318.png)

#### Your Environment

* YetiForce Version used: 4.1 ant 4.0
* Browser name and version: Chrome Latest
* Environment name and version: DEV
* Operating System and version:

**Comment by paula-w** [comment]
We're not planning to add the functionality you described.
