### ISSUE TITLE
[HELP] Field Mask

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#511]
Do not quite understand how it works Masks fields in the Phone can not adjust the mask field and in the company can be, why?

![fieldmaskaccount](https://cloud.githubusercontent.com/assets/1402355/7130050/023b795c-e283-11e4-9f61-9be6b9cd2536.JPG)

![fieldmaskphone](https://cloud.githubusercontent.com/assets/1402355/7130052/07eb069c-e283-11e4-91ce-8da4ff2b62fe.JPG)

**Comment by bpabiszczak** [comment]
We did masks for text fields for one of our customers. In case of different field types you need to copy field masks and adjust them. We didn’t have to use masks on different fields but it doesn’t require a lot of work to add them to all fields.

**Comment by waw555** [comment]
Well mask for the phone must be, by definition, I think so
