### ISSUE TITLE
Events relationship in Modules Relations throws an error in a Custom Module

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5110]
In yetifirce version 4.2 

When I add a new Module Relationship via Standard Modules - Modules Relations of the type Events and then try to open the related module in the record's summary view it throws the following error:

Error!!!
Unable to load template 'file:modules/Vtiger/uitypes/ActivityPicklistFieldSearchView.tpl' in 'modules/Vtiger/RelatedListContents.tpl'

I checked this location and neither of the files exist - nor do they exist in yetiforce development.

**Comment by paula-w** [comment]
Hi Chris,
Could you record a short video/gif on the gitdeveloper version how to trigger this error?

**Comment by PercyP** [comment]
Hi Paula,
I will re-check this later and try record a video if it is still current.

**Comment by bpabiszczak** [comment]
We will open issue if you record an example.
