### ISSUE TITLE
[BUG] You can remove the responsible

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#512]
Is it possible to remove the charge?

![deleteassigned](https://cloud.githubusercontent.com/assets/1402355/7130676/06e3bd38-e28e-11e4-8c55-46ffeec611f4.jpg)

**Comment by waw555** [comment]
You can delete any field, if you move it and store location
If you delete a field from the drop down list, the system hangs in the list editor

![dontedit](https://cloud.githubusercontent.com/assets/1402355/7131029/5bb20324-e293-11e4-8cd6-84f07d5a36ef.jpg)

![dontedit2](https://cloud.githubusercontent.com/assets/1402355/7131030/60e392fe-e293-11e4-8566-9d8b03a40f82.jpg)

![dontedit3](https://cloud.githubusercontent.com/assets/1402355/7131032/6472a6e4-e293-11e4-9d19-d59ca6810ec9.jpg)

**Comment by bpabiszczak** [comment]
We granted too many privileges for a regular user. We are going to create different working modes for the system [prod, demo, dev]. Switching a mode to DEV will allow to break the system, but in a default PROD mode it will not be possible. We will change that soon.

**Comment by waw555** [comment]
I understood you

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/6f4904d5d765a6c23cb48674d9261c05df33e877
