### ISSUE TITLE
[HELP] Sharing information

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#513]
You can learn more about on these functions

![ada7e999](https://cloud.githubusercontent.com/assets/1402355/7131183/4919fddc-e295-11e4-80cb-c2a3dea0ab3f.jpg)

**Comment by KatarzynaUlichnowska** [comment]
This function is going to be modified. When we finish, we will publish a documentation on our website. It is used to make private records available for other users. The inheritance function will be rebuilt completely.
