### ISSUE TITLE
Filter conditions: combination of ALL and ANY not possible?

### ISSUE THREAD

**Issue by fzeien** [YetiForceCompany/YetiForceCRM#5130]
#### Issue

It seems as if the conditions are ignored if there are 'All conditions' and 'Any conditions' defined.

#### Actual Behavior

All conditions are ignored if both types are set.

#### Expected Behavior

'All conditions' should be combined with 'Any conditions' ('All' = true AND 'Any' = true).

#### How to trigger the error

1. Create a filter with both condition types.
![combined-conditions](https://user-images.githubusercontent.com/31696448/30116490-f6399e6a-931d-11e7-9ad2-f07f959e2798.PNG)

2. Have records that satisfy the conditions and ones that don't in order to be able to tell whether the filter works or not.
![all-tickets](https://user-images.githubusercontent.com/31696448/30116553-21373d5c-931e-11e7-826e-e135cd0b4097.PNG)

3. Select the new filter.
![combined-conditions-results](https://user-images.githubusercontent.com/31696448/30116597-421e6298-931e-11e7-8d2c-83beb3344da6.PNG)

#### Your Environment

* YetiForce Version used: 4.1.0
* Browser name and version: Firefox 55.0.3 / Chrome 60.0.3112.113
* Environment name and version: Zend Engine v2.6.0 | PHP 5.6.30
* Operating System and version: Ubuntu 16.04.2 LTS

**Comment by nic86** [comment]
change [this line](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/QueryGenerator.php#L716) with:

`$this->query->andWhere(['and', array_merge(['and'], $this->conditionsAnd), array_merge(['or'], $this->conditionsOr)]);`

**Comment by fzeien** [comment]
thanks, solved this issue.
