### ISSUE TITLE
PHP Errors and maxed server memory usage.

### ISSUE THREAD

**Issue by thedave444** [YetiForceCompany/YetiForceCRM#5131]
Having a PHP error. My I/O Usage and Physical Memory Usage on server is pegged. It's shared hosting for now.

PHP Notice:  Undefined index: language in /home/hrloginw/yeti.hrlogin.work/vendor/yetiforce/Session/Base.php on line 50

and other errors.
[phpError.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/1282137/phpError.txt)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2
* Browser name and version: Firefox latest
* Environment name and version:
* Operating System and version: 
![server info](https://user-images.githubusercontent.com/31484590/30126741-336b441a-92fa-11e7-9bc0-053c7f456d0d.JPG)
![yeti1](https://user-images.githubusercontent.com/31484590/30126750-3ac245ec-92fa-11e7-918b-9ff24259af2e.JPG)
![yeti2](https://user-images.githubusercontent.com/31484590/30126755-3d64da26-92fa-11e7-8ca2-f253356fabcd.JPG)
![yeti3](https://user-images.githubusercontent.com/31484590/30126759-3f5b86d6-92fa-11e7-9f68-11bb958e21d6.JPG)
![yeti4](https://user-images.githubusercontent.com/31484590/30126762-412409ca-92fa-11e7-8b1f-4b68d7ebe728.JPG)

**Comment by thedave444** [comment]
I just upgraded my PHP to 7.0 and it is still throwing the errors. Thoughts?

**Comment by mariuszkrzaczkowski** [comment]
You have two php.ini configuration files that must be identical.
I suppose these errors generate php.ini from cron

**Comment by thedave444** [comment]
I'm really not a web server guy so I apologize for my ignorance. But where would these 2 php.ini files be? I did a search on my web server and only found one in my yeti folder. I also installed a fresh YetiForce install on another subdomain and it did the same exact thing without me making any changes to the database. Just FYI. 

Since its a shared web server I don't have access to all the files but the tech support people have been very responsive to make any changes I've needed so far. Should I ask them to do a search for these files for me?

I only have 2 cron jobs and one of them is just to do a database backup once a month. The errors were happening before I added the backup cron job.

Thank you for your reply btw!

![cronjobs](https://user-images.githubusercontent.com/31484590/30131719-0e9f274e-930b-11e7-9c5b-d49d32c2fa61.JPG)


![php search](https://user-images.githubusercontent.com/31484590/30131674-ddc01ebc-930a-11e7-8d5b-3d28c585b385.JPG)

**Comment by thedave444** [comment]
I know the htaccess file is asked for sometimes so I thought I would include it.

[htaccess.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/1282543/htaccess.pdf)

**Comment by mariuszkrzaczkowski** [comment]
![30126762-412409ca-92fa-11e7-8b1f-4b68d7ebe728](https://user-images.githubusercontent.com/10198654/30133188-3aee9134-9353-11e7-8d8f-56c8f53dd2d5.JPG)

**Comment by thedave444** [comment]
You said I have 2 php.ini files that are the same. I see where you pointed out one of them but where would the other be? The one found in the Yeti folder? Should I delete one of them? I'm not sure how to fix the issue if I do have 2 identical php.ini files.

**Comment by thedave444** [comment]
I've added a couple more into pieces.

![php7extensions](https://user-images.githubusercontent.com/31484590/30136421-1a8d17d0-931c-11e7-92d0-7c90104a0c02.JPG)
![php7options](https://user-images.githubusercontent.com/31484590/30136420-1a88fee8-931c-11e7-85bc-fcc6d830030f.JPG)

**Comment by thedave444** [comment]
I changed the path in my cron file so now it is showing that there is just one php.ini file being read I think. Still getting error log full and maxing my server memory. I'm just lost on what to do.

![fixed phpini](https://user-images.githubusercontent.com/31484590/30142441-0383f7c6-933e-11e7-8a29-182bdc98cb57.JPG)

**Comment by thedave444** [comment]
I seemed to fix the memory issue once I changed a couple things in my php.ini file and upgraded to PHP7.0. Now having issues with not being able to enable SOAP but I think I'll close this. Thank you for your help!
