### ISSUE TITLE
Nie działa import plików csv, xml itp.

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#5145]
Witam Serdecznie
W mojej wersji Yetiforce 4.2.0 zainstalowanej na serwerze Livemarket nie działa import plików w żadnym z modułów. Proszę o pomoc.

**Comment by KatarzynaUlichnowska** [comment]
Witamy,
prosimy sprawdzać czy ktoś wcześniej nie dodał już podobnego zgłoszenia. 
W tym przypadku istnieje już starsze zgłoszenie z tym samym problemem (#4827)  więc prosze je śledzić, a to zamykam.
