### ISSUE TITLE
Display name not showing in custom module

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5154]
Using version 4.0,

In the headser in contacts it show's first name - last name
but in the custom module it only shows the first name. Is there a way to show both?
First image is example second is the issue one.
![first](https://user-images.githubusercontent.com/22075161/30277087-ab8e10dc-96fe-11e7-9f2a-671750dc9d2b.GIF)

![second](https://user-images.githubusercontent.com/22075161/30277092-ae3d8060-96fe-11e7-91d6-68725daf76bd.GIF)

**Comment by mariuszkrzaczkowski** [comment]
To see the header you have to add a new file to your module DetailViewHeaderTitle.tpl
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/layouts/basic/modules/Contacts/DetailViewHeaderTitle.tpl

**Comment by alextovey** [comment]
@mariuszkrzaczkowski in the /var/www/html/yetiforce/layouts/basic/modules there is not a folder for the new module do i need to create one there?

**Comment by alextovey** [comment]
When I add it in there the whole page goes blank. Am i missing something.

**Comment by alextovey** [comment]
I've also tried adding the DetailViewHeaderTitle.tpl from accounts but no luck.
