### ISSUE TITLE
PDF Issues

### ISSUE THREAD

**Issue by ousidahou** [YetiForceCompany/YetiForceCRM#5182]
hi YETIFORCE Team,
Thanks for your all your work
however we just come to find this issue .
Any idea ?

 
![untitled](https://user-images.githubusercontent.com/22946462/30429534-c87d1f3c-994f-11e7-8ee3-edd441172126.gif)

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
