### ISSUE TITLE
Problem z ustawieniem cron job - fatal error w  PreserveGlobal.php (CentOS & Plesk) [PL]

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5185]
#### Issue
Witam,

Mam problem z konfiguracją cron. Utworzyłem dwa polecenia.
1. Uruchomienie skryptu php (httpdocs/cron/vtigercron.sh) - uruchamia się.
2. Uruchomienie polecenia (bash /var/www/vhosts/domena.com/httpdocs/cron/vtigercron.sh >> /var/www/vhosts/domena.com/httpdocs/cron/cron.log 2>&1) uwaga! sprawdzałem też oryginalny zapis polecenia w dokumentacji, również daje ten sam błąd (h /var/www/crm/cron/vtigercron.sh &>/var/www/crm/cache/logs/cron.log)

Drugie polecenie uruchamia się, ale z błędem. W pliku (domena / httpdocs / cache / logs / phpError.log)
dostaje info:

PHP Fatal error:  Can't use function return value in write context in /var/www/vhosts/domena.com/httpdocs/include/Webservices/PreserveGlobal.php on line 20

#### Actual Behavior
Uniemożliwia to uruchomienia cron job.
W panelu administracyjnym  Konfiguracja systemu > Automatyzacja > CRON > Konfiguracja systemu

Brak nadal info o starcie ostatniego skanowania.
Każda próba uruchomienia polecenia daje ten sam wpis w pliku logs/phpError.log
W pliku cache / logs / cron.log brak wpisów.

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:
Skonfigurowałem serwer według dokumentacji. Obecnie w logach systemu dostaje info o braku APCu, Header: X-Powered-By oraz Header: Server (że mam zawarte info o plesk i nginx). Serwer działą pod kontrolą Apache i NGINX (w wersji 7.0.23 Aplikacja FPM).
Baza Danych to MariaDB 10.01

Wszelkie kwestie uprawnień i dostępów też są poprawne.

**Comment by bpabiszczak** [comment]
Należy pamiętać, że CRON często ma inny plik PHP niż sama aplikacja, upewnij się, czy na pewno konfiguracja CRON PHP.INI jest taka sama jak dla aplikacji. Programista może coś więcej podpowie o błędzie...

**Comment by anderpydev** [comment]
Dziękuję za odpowiedź.

Nadałem uprawnienia w Plesk do wykonywania skryptów w non-chroot.
Teraz otrzymuję w pliku phpError.log taki komunikat:

[14-Sep-2017 18:43:23 Europe/Sarajevo] PHP Fatal error:  require_once(): Failed opening required 'include/Webservices/VtigerModuleOperation.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/domena.com/httpdocs/include/Webservices/Utils.php on line 384

**Comment by anderpydev** [comment]
Gdy robię to jak na screenie, cron sie uruchamia, ale w aplikacji nic się nie dzieje.
![cronjob](https://user-images.githubusercontent.com/26583746/30444323-da361246-9982-11e7-9d74-78ac56149f7f.png)

**Comment by anderpydev** [comment]
Okej, zrobiłem to inaczej:
Dałem uruchom polecenie (zmieniająć uprawnienia na pełne dla vtigercron.sh oraz cron.log
`/var/www/vhosts/domena.com/httpdocs/cron/vtigercron.sh &>/var/www/vhosts/domena.com/httpdocs/cache/logs/cron.log`

i dostałem wpis w cache/logs/cron.log

```
/var/www/vhosts/domena.com/httpdocs/cron/vtigercron.sh: line 10: $'\r': command not found
/var/www/vhosts/domena.com/httpdocs/cron/vtigercron.sh: line 15: $'\r': command not found
/var/www/vhosts/domena.com/httpdocs/cron/vtigercron.sh: line 16: cd: /var/www/vhosts/domena.com/httpdocs/cron/..

: No such file or directory
/var/www/vhosts/domena.comhttpdocs/cron/vtigercron.sh: line 18: $'php\r': command not found
```

**Comment by anderpydev** [comment]
Chyba właśnie rozwiązałem problem dla panelu Plesk - wydaje się oczywiste, a jednak :)

Jak to działa w Plesk, ano, zamiast używać pliku vtigercron.sh robimy jak na zdjęciu niżej:

1. Uruchom skrypt PHP + wersja PHP
2. Wybieramy plik vtigercron.php

![cronjob2](https://user-images.githubusercontent.com/26583746/30445487-5e335e3e-9986-11e7-8859-f320df572be7.png)
![cronjob3](https://user-images.githubusercontent.com/26583746/30445488-5e626620-9986-11e7-93b0-a0b166a0a1ca.png)
