### ISSUE TITLE
roundcube installation

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#5186]
Hello everyone :)

after a fresh yetiforce developer installation every additional module except roundcube can be installed....
i took a look into the log files and found the following missing file:

https://github.com/YetiForceCompany/lib_roundcube/archive/0.0.33.zip

why could the installation not download the file?? did i miss something?

Best Ralph

**Comment by mariuszkrzaczkowski** [comment]
No basic information such as system version etc.

**Comment by ralphkretzschmar** [comment]
Sorry for the missing Information.
The installed version is 4.2.175. 

i was able to fix it as well - i've changed the file version.php in the config folder.
befor it was
	'lib_roundcube' => '0.0.33',
i changed it to 
	'lib_roundcube' => '0.0.31',
after the change the version was able to download the missing lib

Best regards

**Comment by paula-w** [comment]
Downloading libraries works properly only in stable versions, in dev versions you have to switch library downloads to developer mode to make this mechanism work well.

**Comment by ericjbs** [comment]
@paula-w how to i can switch library downloads to developer mode? I search in manual but don't found this.
