### ISSUE TITLE
Nie dział import rekordów - moduł Leady [PL]

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5191]
#### Issue
Po wybraniu pliku i ustawieniu opcji importu, gdy klikam na importuj, strona odświeża się tylko z menu i pustym obszarem. Nie pojawia się kolejny krok importu.

W logach serwera w trakcie importu pojawia się błąd i wtedy jest przerywany proces: 

Error | Moje IP | 500 | POST /index.php HTTP/1.0

#### Actual Behavior
Wybieram plik, ustawiam opcje importu i dalej import jest przerwany.

![leady - google chrome_086](https://user-images.githubusercontent.com/26583746/30475864-81365cec-9a08-11e7-8d8b-55fcfac65718.png)

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version: CentOS 7, PLESK, PHP 7.0.23 (PHP-FPM), MariaDB 10.01, Apache+Nginx

Serwer raczej dobrze skonfigurowany bo w systemie crm nie mam żadnego info o błedach. Wszystkie parametry ustawione wg. dokumentacji.

**Comment by mariuszkrzaczkowski** [comment]
Duplikat #4827
