### ISSUE TITLE
php.ini file correct but server saying other wise.

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5197]
We are running 4.2 and the server config is stating that the php.ini files are incorrect but i've triple checked and they are correct.

here's a screen grab of what wrong. Could you point me in what needs to be enabled and how in the php to do this please.

![capture](https://user-images.githubusercontent.com/22075161/30492621-07f17462-9a39-11e7-8dc4-3aaaea3f9654.GIF)
![capture1](https://user-images.githubusercontent.com/22075161/30492622-07f34922-9a39-11e7-89c2-34526f7e162f.GIF)

**Comment by slawekk87** [comment]
output_buffering flag detection fixed, to fix other errors:
**public_html error:**
point your web serwer configuration to YetiForceCRM/public_html instead of YetiForceCRM/
**session_regenerate_id error:**
set $session_regenerate_id = true;
in YetiForceCRM/config/config.inc.php

**Comment by alextovey** [comment]
@slawekk87 done that but the public_html error is still present. I've changed the .conf file to point to the public_html folder instead but no joy.

though the session regen is now gone.

What about these emails im getting HTTPS encryption
Your connection to the server is not encrypted. If the connection is not established through the HTTPS protocol the communication may be intercepted or altered by third parties. The recommended configuration can be found in the "Web server requirements" article in the documentation.

**Comment by slawekk87** [comment]
Make sure Your apache vhost config look like this:
![5197](https://user-images.githubusercontent.com/22735929/30541190-9216ecec-9c7a-11e7-8555-11d89551c867.png)

Emails issue should be fixed in developer version.

**Comment by alextovey** [comment]
fixed it. thank you, there was another conf file because if let's encrypt. vhost-le-ssl.conf changed that and it worked. Thank you so much for your help slawekk87.
