### ISSUE TITLE
Question: How to delete an asset?

### ISSUE THREAD

**Issue by scsikid** [YetiForceCompany/YetiForceCRM#5198]
I've created an asset, however I can't seem to delete the asset. Is there a way to do this? I've googled and looked through the Issues tab.

**Comment by bpabiszczak** [comment]
Here you can disable blocking
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Assets/Assets.php#L17

**Comment by scsikid** [comment]
@bpabiszczak I'm not much of a coder so I don't know what to modify here. Do you think you can advise me? 

Also, is there anything in the active development to make this an option in the GUI?

**Comment by mariuszkrzaczkowski** [comment]
Modify as follows:
```
protected $lockFields = [];
```
