### ISSUE TITLE
Error Date Format

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#52]
Format daty w komunikacie (Modul Data Access) (Planowana data zakończenia nie może być większa od Terminu etapu) nie pasuje datę określoną w ustawieniach CRM, czyli jeśli określić format daty w wiadomości jest zawsze 12.12.2012 > 2012-12-12

**Comment by rskrzypczak** [comment]
Poproszę o szerszy opis. Zrzut ekranu byłby pomocny.

**Comment by waw555** [comment]
![error date](https://cloud.githubusercontent.com/assets/1402355/5719038/dce97ddc-9b35-11e4-92b1-88994f57e73f.JPG)

**Comment by waw555** [comment]
Po zapisaniu problem projektowania, wyślij pusty arkusz
