### ISSUE TITLE
Not able to Login, when I transfered the data base from local to hosting 

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#5200]
on the hosted site 
Using latest Yetiforce 4.2
Mysql : 5.5 

my local server
Using latest Yetiforce 4.2
Mysql : 5.6

i have imported with out any error on the hosted  site, except I am not able to login

**Comment by alextovey** [comment]
did you change the database and the passwords etc in the config files?

**Comment by gkArvindr** [comment]
yes I did, I am able to connect to the database, not able to login into yetiforce

**Comment by alextovey** [comment]
then it's a permissions issue. make sure you sudo chown www-data:www-data /var/www/html/

depending on your version of linux for ubuntu it's the above. running apache2

**Comment by gkArvindr** [comment]
it is running on a shared hosting, have check the permission & ownership that does not seem to a problem.  

I tried resetting password, it did not help. I assumed it may be connected with mysql version, to overcome the constrain of versions, I did a csv export from local server and imported it back on shared hosting server it got imported without any errors and I could see the data via myphpadmin 

one clarification do we have more  version of yetiforce 4.2 ? the one I used to develop was share by  mariuszkrzaczkowski in the early days, I did notice that some changes has been made to database structure in the latest download of yeti-force 4.2, example in field vtiger_user hash value column has been removed on the current download

**Comment by paula-w** [comment]
The answer to why you can’t log in is in the logs. If an incorrect password is the problem then you can reset the password. One of the ways to do that is enabling logs, copying the password hash visible in logs that the system is looking for in the table of users, and if it’s different then you can overwrite this hash for the user whose account you want to log in. 
As far as I remember what Mariusz deleted was related to a field that we didn’t use [Vtiger’s remainders, if I recall correctly, Vtiger used to store passwords there in MD5 but didn’t use this field].

**Comment by gkArvindr** [comment]
I dont think it a password mismatch problem, it a kind of strange experience, I export the database from the hosting and restore in the local database and  every thing works normal. I dont  know where I am going wrong. I checked the phperror.log I did not see any unusual error. 
same application running on two different server has different results.
I hosted on in siliconhouse server - it logins  but it keeps on giving me permission errors every now and then 
the one I hosted in Globehost Server - give me the error - invalid user name or passowrd

both have same php5 version and mysql-5.6 
both have  Centos  
I requested the service provider for a some insight into the issues, the suggestion provided was not useful

**Comment by paula-w** [comment]
The problem is that you don’t see the error in the logs. It doesn’t mean that the error isn’t there, because it definitely is there, but you have to know how to [enable and analyze logs](https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging) 
A programmer should log in and investigate the problem directly on the server. Unfortunately, we charge for this kind of service. There isn’t much to debate in here, a programmer has to see this and only then we will know for sure what the problem is.
