### ISSUE TITLE
Issue with email scanner

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5201]
can someone tell me how the scanner works i've tried to run it on office 365 but it wont pick up any emails. 
i'm running 4.2 however no error's the log say's its running okay. 

It wont let  me add any search email configuration though. I add it in then it does not save.

see screen shots please.
![1capture](https://user-images.githubusercontent.com/22075161/30516015-3265485c-9b2b-11e7-8087-ce733bc5013b.GIF)
![2capture](https://user-images.githubusercontent.com/22075161/30516017-3268524a-9b2b-11e7-8d7d-c56bfeffae3f.GIF)
![3capture](https://user-images.githubusercontent.com/22075161/30516016-3266a594-9b2b-11e7-8342-5cbdb896f19b.GIF)

**Comment by bpabiszczak** [comment]
You must add this action first: Create email message

**Comment by alextovey** [comment]
I've done that but still not picking them up. Any reason why? I've do so many test's. When i click on send email it stays on the screen.

**Comment by alextovey** [comment]
@paula-w @bpabiszczak 

I've done that and still not working with the email. :S is it because it's office 365?
