### ISSUE TITLE
Getting so many of these

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5202]
running 4.2 and the htaccess, the .conf file and the server config.inc.php is all https.

How am i still getting these messages.

HTTPS encryption
Your connection to the server is not encrypted. If the connection is not established through the HTTPS protocol the communication may be intercepted or altered by third parties. The recommended configuration can be found in the "Web server requirements" article in the documentation.

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.

**Comment by alextovey** [comment]
Well clearly it dies if I'm getting them. How to disable these bloody alerts! I'm getting 16 at a time.
