### ISSUE TITLE
The saving users takes a very long time

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#5203]
Hello!
I have a database with 300,000 entries in vtiger_сrmentity. When I change any property of the user and save it, then the saving takes a very long time, 30 - 40 minutes. Roles are configured as standard, tried different options for settings, but still very long.
What could be the reason? I correctly understand that it updates the field vtiger_crmentity.users, depending on the settings of the public access?
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2
* Browser name and version: Chrome/Firefox
* Environment name and version:
* Operating System and version: Debian

**Comment by bpabiszczak** [comment]
How many users you have?

**Comment by alexandr256** [comment]
65 users

**Comment by alexandr256** [comment]
And the creation of a new user is also very long

**Comment by alexandr256** [comment]
Today, the new user was saved for 5 hours. If set a public access for the module, then in the vtiger_crmentity in the users field all users are listed by comma. I have two such modules, documents and comments, the remaining modules list only those users who are set by special rules in SharingAccess

**Comment by alexandr256** [comment]
processor       : 4
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x19
cpu MHz         : 800.000
cache size      : 8192 KB

32 GB RAM

SSD RAID1

**Comment by mariuszkrzaczkowski** [comment]
I tested it for 500 users and I can't see the problem. I tested it on a regular laptop, I attached the recording. The performance depends on hardware configuration and system configuration, we can't help you unless you provide us with info about both, because we aren't able to trigger that problem.

![user](https://user-images.githubusercontent.com/10198654/32316327-faedb892-bfaf-11e7-924e-57f5af835b0d.gif)

**Comment by alexandr256** [comment]
This problem is not in the number of users, but in the number of records, users and sharing access. If there are a lot of records and users, the program recounts the access rights to all records.

**Comment by mariuszkrzaczkowski** [comment]
I made a test for 400 000 records and 500 users
![user](https://user-images.githubusercontent.com/10198654/32465897-6286bace-c345-11e7-93f5-d9f477c8d63b.gif)
Your case requires a developer analysis, the problem may be in hardware, the environment or in CRM.

**Comment by alexandr256** [comment]
In OSPanel:

Warning: PDO::commit(): MySQL server has gone away in C:\OpenServer\domains\saelog.crm\vendor\yii\db\Transaction.php on line 152

Warning: PDO::commit(): Error reading result set's header in C:\OpenServer\domains\saelog.crm\vendor\yii\db\Transaction.php on line 152
Ошибка!!!

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away Failed to prepare SQL: SELECT `userid` FROM `vtiger_user2role` INNER JOIN `vtiger_users` ON vtiger_users.id = vtiger_user2role.userid WHERE (`roleid`=:qp0) AND (`status` <> :qp1)

**Comment by paula-w** [comment]
Does this error exist in the newest version?

**Comment by alexandr256** [comment]
Yes. After update pack

**Comment by ezbank** [comment]
i confirm.
Tested on https://gitdeveloper.yetiforce.com 
4 Users on gitdev.
#### How to trigger the error
![1b](https://user-images.githubusercontent.com/19627226/33808961-72af045a-de21-11e7-9f6f-59132603c6cb.png)
![2b](https://user-images.githubusercontent.com/19627226/33808962-72d93e00-de21-11e7-9644-182ba230bdd8.png)
![3b](https://user-images.githubusercontent.com/19627226/33808963-730339b2-de21-11e7-88ee-6f1ea1f3a35d.png)
 and long loading time........

**Comment by mariuszkrzaczkowski** [comment]
@alexandr256 Test new changes
