### ISSUE TITLE
Nie działa tworzenie raportów

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#5207]
Witam serdecznie w Yetiforce 4.2.0 nie działa generowanie raportów.
Problem pojawia się w momencie próby zapisu raportu z danymi. System się wiesza.

**Comment by slawekk87** [comment]
Witam 
Proszę sprawdzić na wersji deweloperskiej czy problem został rozwiązany:
https://gitdeveloper.yetiforce.com/

**Comment by Irmina8591** [comment]
Fatal error: Uncaught Error: Undefined class constant 'tableName' in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Settings/Currency/models/Record.php:182 Stack trace: #0 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Reports/ReportUtils.php(201): Settings_Currency_Record_Model::getAll() #1 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Reports/ReportRun.php(2549): getReportFieldValue(Object(ReportRun), NULL, Object(stdClass), Array, 'PriceBooks__Cur...') #2 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Reports/models/Record.php(725): ReportRun->generateReport('PDF', false, true, 0, 1000) #3 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Reports/views/Detail.php(49): Reports_Record_Model->getReportData(Object(Vtiger_Paging_Model)) #4 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/include/main/WebUI.php(260): Reports_Detail_View->preProcess(Object(App\Request)) #5 /home/gitdevelop/ in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Settings/Currency/models/Record.php on line 182
