### ISSUE TITLE
Nie można edytować ani usuwać rekordów tabelki "Baza Wiedzy"

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#5208]
Witam
Yetiforce 4.2.0 stable
Nie  można edytować ani usuwać rekordów w tabelce " Baza Wiedzy" - jest to dosyć problematyczne w przypadku pomyłki. P.S Jeśli takie zlecenie pojawiło się już ale po angielsku to niestety nie jestem w stanie tego sprawdzić z powodu nieznajomości języka.

**Comment by bpabiszczak** [comment]
Proszę nagrywać filmiki za pomocą screen2gif na wersji GitDeveloper. 
Zapewne nie można edytować dla rekordów o statusach zablokowanych do edycji np.: 
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/KnowledgeBase/KnowledgeBase.php#L13 

Można wyczyścić tą tablicę i będzie można edytować.

**Comment by Irmina8591** [comment]
Witam nie wiem czy nadanie filmiku coś da  - w tej tabeli wcale nie ma
przycisku "Edytuj"
a przy "Masowe usuwanie pyta czy napewno po potwierdzeniu nic nie robi.

W dniu 18 września 2017 11:58 użytkownik Błażej Pabiszczak <
notifications@github.com> napisał:

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/KnowledgeBase/KnowledgeBase.php#L13

**Comment by Irmina8591** [comment]
dziękuję działa

2017-09-18 13:11 GMT+02:00 Mariusz Krzaczkowski <notifications@github.com>:
