### ISSUE TITLE
New Menu manager

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#521]
Tested the new menu manager and noticed that adding Home icon to the menu messes up the template.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
could you test it on the latest version? We use it and we haven't noticed anything like that, but if the problem still exists, please send us screenshots.

**Comment by kpaulaha** [comment]
It works fine with the latest versions, thanks

**Comment by witer30** [comment]
Dear,
Can you be so kind and tell me how to properly set up cron job...
I tried to do it on Ubuntu 14.04.2 LTS without success... 
thanks a lot for support
K.

**Comment by bpabiszczak** [comment]
https://wiki.vtiger.com/index.php/Cron
