### ISSUE TITLE
Tworzenie nowego modułu

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#5217]
Witam 
System Yetiforce 4.2.0 stable
Czy przy tworzeniu nowego "modułu" w ustawieniach programu, jest jakaś obcja dodania możliwości dodawania dokumentów do modułu (dodawanie np. skanów plików pod dany rekrod jak w przypadku np. tabeli "Pracownicy"

**Comment by bpabiszczak** [comment]
Można włączyć w systemie panel do tworzenia relacji, tak jak to widać tutaj: https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&block=2&fieldid=41
![image](https://user-images.githubusercontent.com/10197525/30799516-5fea46ca-a1dd-11e7-8381-a2865fcb745b.png)
