### ISSUE TITLE
Security warnings - where exactly do we change these settings? 

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5224]
Hi,

I am just checking my security settings as there were 11 warnings. I should have noticed these earlier (after updating to 4.2) but didn't think they would have changed.

Where/how exactly do we change these?

Kind regards
![security](https://user-images.githubusercontent.com/10598886/30599803-8b293c24-9d55-11e7-9756-c52630caf197.png)

**Comment by vovpff** [comment]
@PercyP for .htaccess and publick_html check your virtualhosts configuration for web server engine
for headers check web server configuration.

**Comment by PercyP** [comment]
@vovpff 

thanks for responding. I have been trying to do this all day. I have been looking around WHM (I have a VPS) but cannot (as yet) figure where to make the changes. There are tutorials online saying about editing the conf file. What files did you edit? What settings did you change?

Also, have you managed to move to php 7.1? I am stuck on 7.0 as when I try to upgrade it crashes my sites with error 500.

**Comment by vovpff** [comment]
@PercyP I will check my conf today evening/tomorrow.

**Comment by PercyP** [comment]
@vovpff 

thank you - I think it helps seeing other's settings. Mine were fine until the last upgrade so I am guessing it is because the added lots of new security features?

**Comment by vovpff** [comment]
@PercyP sorry, I have too much work and can't access to my server now...
I will answer you when I have some free time.

**Comment by bpabiszczak** [comment]
Each server can have a different configuration and different operating system and apache versions. It's the server admin who should know where these parameters can be modified.

Example for X-FRAME-OPTIONS
https://geekflare.com/secure-apache-from-clickjacking-with-x-frame-options/
