### ISSUE TITLE
hi .

### ISSUE THREAD

**Issue by yohananz** [YetiForceCompany/YetiForceCRM#5226]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by yohananz** [comment]
is there a  right to left theme for hebrew arabic .... etc?

**Comment by bpabiszczak** [comment]
No, but you can create it and add it to the core [YetiForce].
