### ISSUE TITLE
[ERROR] Convert Lead

### ISSUE THREAD

**Issue by paulokruz** [YetiForceCompany/YetiForceCRM#5234]
YetiForce Version: 4.2.0

When click in Covert Lead i get blank page .
Checking error log i see warning about missing file "include/Webservices/VtigerModuleOperation.php".

ERROR:
Warning: require_once(include/Webservices/VtigerModuleOperation.php): failed to open stream: No such file or directory in C:\xampp\htdocs\yetiforcecrm\include\Webservices\ConvertLead.php on line 39

Fatal error: require_once(): Failed opening required 'include/Webservices/VtigerModuleOperation.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\yetiforcecrm\include\Webservices\ConvertLead.php on line 39

In version 4.1 file exists but not in 4.2.0

Checking your demo i can see same problem when try Convert Lead.

![image](https://user-images.githubusercontent.com/5950623/30658306-29d97b36-9e32-11e7-82ba-be0800ecf8d7.png)

**Comment by slawekk87** [comment]
Can You record movie with procedure to generate error?
I checked on gitdeveloper:
Set Lead status to: for conversion
clicked convert lead and all worked ok
