### ISSUE TITLE
Role and Group error

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#5235]
Adding new Role or Group
<img src="https://image.ibb.co/mVEvYk/role.jpg" alt="role" border="0">
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/b70622dcd3a3c98d9e5eca6ddce6925f10b0bcbf https://github.com/YetiForceCompany/YetiForceCRM/commit/9f2d7fe1980755ff92571335d281452ce53439d3
