### ISSUE TITLE
Błąd integracji z mapami google

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#5236]
Witam  Takie coś pojawia się przy próbie integracji z api map google. 
![bez tytulu](https://user-images.githubusercontent.com/31611057/30681268-fd1926d2-9ea4-11e7-8388-ba058f2f2077.png)

Yetiforce 4.2.0 wersja stabilna
Błąd występuje również w wersji deweloperskiej 
Błąd występuje dla obu systemów api mapy

**Comment by mailo86** [comment]
any idea ? i have the same issues

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
