### ISSUE TITLE
Błąd dodawania urzytkownika

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#5237]
Witam
Yetiforce 4.2.0 wersja stabilna

po dodaniu użytkownika nie wyświetla się on na liście. (Ani w aktywnych ani w nieaktywnych)
Mimo to system twierdzi że użytkownik o podanym adresie mail jest już zarejestrowany. 

Dodany użytkownik nie może się też zalogować.

Problemy , wraz z problemami zmiany parametrów dodanych użytkowników pojawiły się po naprawie problemu z importowaniem danych z csv.

**Comment by mariuszkrzaczkowski** [comment]
Błąd nie występuje w wersji deweloperskiej.
Proszę się zapoznać z zasadami zgłaszania błędów https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/jak-zglaszac-bledy

> 3. JAKIE INFORMACJE SĄ DLA NAS NIEZBĘDNE ABY SZYBKO I SPRAWNIE ZAJĄĆ SIĘ BŁĘDEM
> A. CZY BŁĄD WYSTĘPUJE NA WERSJI DEWELOPERSKIEJ?
