### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by boolek** [YetiForceCompany/YetiForceCRM#524]
On the login page (https://test.yetiforce.com/) after click "forgot password" e-mail address is displayed as ***************

In my installation (1.4.0 RC) after entering login and e-mail and click to the link to create a new password system opens a blank page (.../jeti/modules/Users/actions/ForgotPassword.php) and doesn't change the password - I have no way to test it in demo.

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
this mechanism was fixed in the latest version. You can test it or wait for an update to 1.5.0. You can also perform a "partial" update and use this package: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%201.x.x/1.4.0RC_to_1.5.0RC
