### ISSUE TITLE
Komunikaty ERROR

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#5240]
Witam
Yetiforce 4.2.0 Wersja stabilna 

W Konfiguracja systemu > Logi > Serwer - konfiguracja > Konfiguracja systemu
 zakładka RoundCube wyświetlają mi się następujące komunikaty: 

Checking available databases

Check which of the supported extensions are installed. At least one of them is required.

OK - MySQL 
OK - PostgreSQL 
OK - SQLite 
ERROR - SQLite (v2) | | http://www.php.net/manual/en/ref.pdo-sqlite.php
ERROR - SQL Server (SQLSRV) | | http://www.php.net/manual/en/ref.pdo-sqlsrv.php
ERROR - SQL Server (DBLIB) | | http://www.php.net/manual/en/ref.pdo-dblib.php
Check for required 3rd party libs

This also checks if the include path is set correctly.

ERROR - PEAR | Failed to load PEAR.php | http://pear.php.net
ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime

**Comment by bpabiszczak** [comment]
Błędy SQL możesz zignorować.
Pozostałe 4 błędy należy naprawić poprzez zmianę konfiguracji serwera.
