### ISSUE TITLE
Cannot creat New PDF template

### ISSUE THREAD

**Issue by frankhzp** [YetiForceCompany/YetiForceCRM#5242]
#### Actual Behavior

not able to create new PDF template
<img width="1276" alt="1111" src="https://user-images.githubusercontent.com/28562781/30687637-89825b7c-9eee-11e7-954e-abc6c2bcc6bd.png">

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2.221
* Browser name and version: Chrome61
* Environment name and version:  Xampp
* Operating System and version:  windows 10

**Comment by TomaszQr** [comment]
Fixed via https://github.com/YetiForceCompany/YetiForceCRM/commit/bcf18f48a9d80e68f3d24e08482bf226ac38fcb9
