### ISSUE TITLE
not able to load the next pages of PDF templates

### ISSUE THREAD

**Issue by frankhzp** [YetiForceCompany/YetiForceCRM#5243]
#### Actual Behavior

not able to load the next pages of PDF templates. always showing "loading ,please wait..."
<img width="1278" alt="2222" src="https://user-images.githubusercontent.com/28562781/30687827-0b6e440c-9eef-11e7-943e-c2203f563251.png">

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2.221
* Browser name and version: Chrome61
* Environment name and version: Xampp
* Operating System and version: win10

**Comment by bpabiszczak** [comment]
Works on latest gitdeveloper version.
![image](https://user-images.githubusercontent.com/10197525/32653935-c245eb3a-c609-11e7-9b2d-2759a8e3ae5c.png)
