### ISSUE TITLE
[question] All users on the Calendar

### ISSUE THREAD

**Issue by boolek** [YetiForceCompany/YetiForceCRM#525]
Is it possible to set the calendar to always be seen all users?
![calendar](https://cloud.githubusercontent.com/assets/11717529/7176747/39da6914-e421-11e4-9335-5d16c7a5ae38.png)

Now every time you need from the list of "Activity Types" select "Users" and click "Refresh"

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
the look and feel of the Calendar will be improved and there will be an option to select all in a single click. It will look similar to the Calendar in this screenshot:
![kalendarz](https://cloud.githubusercontent.com/assets/10218164/7365446/b1fced86-ed90-11e4-9831-5c96ff30849e.jpg)
