### ISSUE TITLE
Opportunities page hangs when changing page or applying filter

### ISSUE THREAD

**Issue by xparadell** [YetiForceCompany/YetiForceCRM#5251]
#### Actual Behavior
After clicking the link to change page of opportunities or applying a diferent filter, page hangs showing the message "charging, please wait".

![imatge](https://user-images.githubusercontent.com/23243213/30702463-4fb5dabe-9eed-11e7-9c17-eb632aa48cdd.png)

With browser back button there is no problem to step back.

Thanks in advance

#### Expected Behavior
It is expected a rapid page update and not hanging

#### My Environment

LBL_OPERATING_SYSTEM | Linux esm11.siteground.biz 3.12.18-clouder0 #141 SMP Thu Jun 1 09:04:45 EEST 2017 x86_64

This is my server missconfiguration parameters: I dont' know if any off theme are causing the hangup:

OPcache | No | Optional
APCu | No | Optional

output_buffering | On | 4096
max_execution_time | 600 | 120
max_input_time | 600 | 120
default_socket_timeout | 600 | 20

max_input_vars | 10000 | 3000
mysql.connect_timeout | 600 | 20
innodb_lock_wait_timeout | 600 | 50
wait_timeout | 600 | 60
interactive_timeout | 600 | 20

* YetiForce Version used: 4.1.0
* Browser name and version: Firefox 55.0.3 (32 bits) / 
* Environment name and version:
* Operating System and version:

**Comment by xparadell** [comment]
I have 40 apportunities but it seems as if page control could not be able to see /obtein the rest of records when changing page and then hanging indefinitely.

**Comment by xparadell** [comment]
I also realise that after the descrived situation submenues stay hidden until a logoff and next login (without closing browser). May it be a problem with user interface.
(using Windows 10). Thanks again.

**Comment by mariuszkrzaczkowski** [comment]
This bug has been fixed before, test the developer version https://github.com/YetiForceCompany/YetiForceCRM/commit/6dfa42a6a2fdd2a5921846f736abf15e3bf04d63
