### ISSUE TITLE
[BUG] Can´t create product (error field validation interger )

### ISSUE THREAD

**Issue by paulokruz** [YetiForceCompany/YetiForceCRM#5260]
Bug exist in 4.2.0 version and in your develop  4.2.238 version 

How reproduce:
1) Go to prodcuts -> create new -> fill fields and try save product.
2) In Price Information Box bellow unit price if click in "more currencies>>"  ajax call stop with error.

Problem as i can see is in /vendor/yetiforce/Request.php in -->  public function getInteger

FUNCTION WITH ERROR
	public function getInteger($key, $value = 0)
	{
		if (isset($this->parseValues[$key])) {
			return $this->parseValues[$key];
		}
		if (!isset($this->rawValues[$key])) {
			return $value;
		}
		if ($value = filter_var($this->rawValues[$key], FILTER_VALIDATE_INT)) {
			return $this->parseValues[$key] = $value;
		}
		\App\Log::error('getInteger: ' . $this->rawValues[$key], 'BadRequest');
		throw new \App\Exceptions\BadRequest('LBL_NOT_ALLOWED_VALUE');
	}

HOW WE SOLVE PROBLEM:
public function getInteger($key, $value = 0)
	{
		if (isset($this->parseValues[$key])) {
			return $this->parseValues[$key];
		}
		if (!isset($this->rawValues[$key])) {
			return $value;
		} **else {
			return $this->rawValues[$key];
		}**
		if ($value = filter_var($this->rawValues[$key], FILTER_VALIDATE_INT)) {
			return $this->parseValues[$key] = $value;
		}
		\App\Log::error('getInteger: ' . $this->rawValues[$key], 'BadRequest');
		throw new \App\Exceptions\BadRequest('LBL_NOT_ALLOWED_VALUE');
	}

**Comment by paula-w** [comment]
I just checked that on the gitdeveloper version and it works. Check it once again and if it still doesn't work for you please send us a short video of how you trigger the error.
