### ISSUE TITLE
Need Help about Recurring Sales Orders

### ISSUE THREAD

**Issue by paulokruz** [YetiForceCompany/YetiForceCRM#5261]
I use YetiForce Version 4.2.0 and can´t auto generate Sales ordes with Recurring Sales Orders.

Can anyone explain what steps i need to do for Recurring Sales Orders auto generate Sales orders or invoices?

What i want is to make a sale or invoice for a service or product and after 3 months auto generate another sale (invoice) .

Is this possible or Yetiforce is not ready to accomplish this behavior?

**Comment by PercyP** [comment]
I too am interested in this

**Comment by paula-w** [comment]
Using the Mapping and Workflow functionalities you can make it automatic, unfortunately, I don’t remember if it works properly on the gitdeveloper or gitstable versions, it probably needs some help from a programmer.

Financial and logistic processes require some improvements and changes that we have planned for 2018, so some of these functionalities might not yet work ideally, in these cases some help from a programmer would be needed.

**Comment by Giorgos-Hellene** [comment]
Hi @paula-w !

Could you tell me please why there is Periodic generation on module Recurring Sales Orders ? 
https://prnt.sc/qtxgd3
What is its fuctionallity ?

Thank you !

**Comment by paula-w** [comment]
Hi @Giorgos-Hellene 
This is where you specify the recurrence details for each recurring sales order.

**Comment by Giorgos-Hellene** [comment]
@paula-w thank you for your reply !
I have created a reccuring order manually with one click or any Workflow. Ok it works fine. But i don't understand why there is this point.

If i specify it with workflow why there is Periodic generation ?
