### ISSUE TITLE
Automation > Recording Control - doesn't show colour selector 

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5262]
Hi,

I want to use the Coloring of lines within list of records feature under recording control. I have set this up, including the criteria, but when I click edit and go in to select the colours the picker is not there - just the headers. 
When I use Chrome inspection tool there are a number of javascript errors saying 404. 

DO I need to install this colour picker tool separately, or enable it somewhere? 

Any advice would be most appreciated. 

See images:

![colourselectorerrors](https://user-images.githubusercontent.com/10598886/30774699-a74ea138-a07e-11e7-978e-d1be17263dfb.png)

![nocolourselector](https://user-images.githubusercontent.com/10598886/30774697-9d9e85ae-a07e-11e7-8a2f-379ea39c0fa6.png)

**Comment by paulokruz** [comment]
Hi, this bug happens in 4.2.0 version (gitstable.yetiforce.com) and is ok in version 4.2.238 (gitdeveloper.yetiforce.com)

**Comment by PercyP** [comment]
@paulokruz 

thanks for letting me know. Hopefully the new release will be out this week and resolve it :)

**Comment by bpabiszczak** [comment]
1. This module has been deleted.
2. Below you have a screenshot of the new functionality.
![image](https://user-images.githubusercontent.com/10197525/32655546-4a1167de-c60e-11e7-88f0-6d652aa48d43.png)

**Comment by vovpff** [comment]
@bpabiszczak how this functionality works? How to check this stuff?

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/32657218-35289f34-c615-11e7-9506-c429177eafdb.png)

![image](https://user-images.githubusercontent.com/10197525/32657241-51279cd0-c615-11e7-8f33-1a7f22951b2b.png)

![image](https://user-images.githubusercontent.com/10197525/32657266-6c590304-c615-11e7-8099-0b9741d76e95.png)

Right now the colors are set automatically depending on whether the record is Active , Archived, In trashbin. Ultimately the colors will be taken from picklists configuration [you will be able to set a color for each picklist value]. Please keep in mind that this is just an early stage of the functionality.

**Comment by vovpff** [comment]
@bpabiszczak sound very interesting. When you plan to implement picklists coloring?

**Comment by bpabiszczak** [comment]
Soon
