### ISSUE TITLE
Question - CardDAV support

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#5263]
Hi,
I installed the Outlook CalDAV Synchroniser, connected it to my Yetiforce instance and the calendar is synchronizing without any problems. Great work, thanks!! 

Under Settings -> Integration > DAV Applications > System settings I can see that 235 cardDAV entires where synchronised as well but I can't find any changes made in Yetiforce or Outlook.

Please, can you give me a short explanation where I can find these synchrónized contact information in Yetiforce/Outlook or what I need to do to use them.

**Comment by paula-w** [comment]
We have to know what your version of the system is, also please provide us with CardDAV synchronization logs, and let us know if it's working on gitdeveloper.
