### ISSUE TITLE
Global Search for Users not possible

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#5264]
Hi,
under Software configuration > Search and filters > Search - Configuration > System settings you can configure the search fields for the users module but the global search does not search this module nor is the module listed in the drop-down list.
Is this a wanted behavior?
It would be great to be able to search for users and display their telephone number, like a  search address book feature.

Verified this behaviour on gitdeveloper.yetiforce.com

**Comment by paula-w** [comment]
This module shouldn’t really be there and we’re going to remove it from there.
