### ISSUE TITLE
How to migrate from WAMP to LAMP?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5267]
Hi Yeti community. I need your experience.

Now I need to migrate from WAMP server to LAMP server. How to implement this in correct way.

Looks like #3951 not works correct for WAMP to LAMP migration. Some data after migration is incorrect.

I found what PHP for cron has old windows path like C;/wamp/... and etc.

Any ideas?

**Comment by bpabiszczak** [comment]
https://stackoverflow.com/questions/1143334/porting-from-wamp-to-lamp

**Comment by vovpff** [comment]
@bpabiszczak is it possible to apply `chown -R www-data:www-data crm-root/` to Yeti CRM root? I need your opinion because you are expert.

**Comment by bpabiszczak** [comment]
I’m an expert when it comes to YetiForce, not when it comes to servers. Whether or not this command is proper depends on the operating system and server configuration. You have to determine that with your administrator. Permissions for files and folders are described here https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

**Comment by vovpff** [comment]
@bpabiszczak Thanks a lot. I'm self-taught admin of my server. I don't have enough experience with Linux (Ubuntu 16.04). My project is non-commercial and I can't pay for server adjustments. All stuff only by yourself.

**Comment by vovpff** [comment]
Solution:
LAMP server adjusted as required [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements).
`chown -R www-data:www-data /your_crm_root/`
Profit!
