### ISSUE TITLE
Roundcube problem (no config.inc.php) after 4.2 update

### ISSUE THREAD

**Issue by technologiegalwaniczne** [YetiForceCompany/YetiForceCRM#5268]
Please help.
After the update to YF 4.2 (from 4.0/4.1) Roundcube stopped working.
I am getting the following message: 
----------------------------
CONFIGURATION ERROR

config.inc.php was not found.
Please read the INSTALL instructions!
----------------------------
I am not sure if I shoud realy follow the "install instructions" in this case.

Anyone experienced the same problem?

Best regards
Maciej Janiak

**Comment by mariuszkrzaczkowski** [comment]
Make sure you have such a file
https://github.com/YetiForceCompany/lib_roundcube/blob/developer/config/config.inc.php

**Comment by technologiegalwaniczne** [comment]
The file was and is present in modules/OSSMail/roundcube/config/.

**Comment by technologiegalwaniczne** [comment]
Solved. 
I have coppied the OSSMail folder from the modules folder to the public_html folder.
Any idea why that was the solution:)?
