### ISSUE TITLE
Blank screen after logon and PHP Fatal error:  Call to a member function getRoleDetail() on null

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#5271]
#### Issue

After upgrade do version 3.4.1 to 3.4.1427 after logon screen with password, we have got an empty screen and nothing moves after that

#### Actual Behavior

Blank screen after logon

#### Expected Behavior

Application main meny should appear

#### How to trigger the error

1. Don't make sense send you a blank screen. I will attach the log
2.
3.

#### Your Environment

* YetiForce Version used:  3.4.1427
* Browser name and version: Chrome and Safari
* Environment name and version: CPanel (66 build 23), Apache 2.4.27, PHP 5.6.31, MySql 5.5.57-cll
[phpError.log](https://github.com/YetiForceCompany/YetiForceCRM/files/1329983/phpError.log)

* Operating System and version: Linux 2.6.32-673.26.1.lve1.4.30.el6.x86_64

**Comment by paula-w** [comment]
Once again your logs show that your server is not properly configured. We mentioned that a couple of times. Installation on a server that is not properly configured might cause issues in the future. Unfortunately, your case needs an individual analysis, we offer this service but we charge for it.
