### ISSUE TITLE
Bug? - custom autoloader not working for layouts folder

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#5272]
Hi,
with the introduction of the public_html directory in version 4.1 the custom autoloader function no longer works for the layout folder.
I have a custom skin and several module Javascript resources and the custom autoloader was a great feature to keep my customisations in a central place.
Is this a bug or a wanted behaviour?

**Comment by paula-w** [comment]
Custom autoloader should be working properly, please tell us what changes you made so we can duplicate the error.

**Comment by setras** [comment]
@paula-w  I changed the file layouts/basic/modules/Accounts/resources/Detail.js
In Version 4.0 I used the autoload function and applied my changed to file 'custom/layouts/basic/modules/Accounts/resources/Detail.js'

In Version 4.2 the original file was moved to the 'public_html' directory and my modified file was no longer loaded from the custom directory.
I tried to to add the 'public_html' path under the custom directory and added a 'custom' path in the public_html directory, neither worked.
