### ISSUE TITLE
Problem z generowaniem raportów dla zgłoszeń

### ISSUE THREAD

**Issue by kristek92** [YetiForceCompany/YetiForceCRM#5273]
Dzień dobry

Chciałbym stworzyć raport zawierający zamknięte zgłoszenia i zaakceptowany czas pracy dla nich.
1) Tworząc raport według poniższych kroków:
![image](https://user-images.githubusercontent.com/30728827/30858484-2abb5cd0-a2c0-11e7-8bff-24e821c493ba.png)

2)
![image](https://user-images.githubusercontent.com/30728827/30858524-51018f4a-a2c0-11e7-8cfe-56e8d2072df9.png)

3)
![image](https://user-images.githubusercontent.com/30728827/30858545-6ab6a2ae-a2c0-11e7-8dd6-9d3ff6bc3752.png)

4) Nie uzyskuję żadnych rekordów (mimo, że istnieją takie, które spełniają podane przeze mnie warunki): 
![image](https://user-images.githubusercontent.com/30728827/30858582-959df62a-a2c0-11e7-968d-6550a41be43e.png)

Moja wersja Yetiforce: 4.2.0

W wersji demo ze strony gitdeveloper.yetiforce.com (po uprzednim stworzeniu odpowiednich rekordów) uzyskuję to samo. Nie wiem czy to błąd systemu czy mój. Proszę o pomoc.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6538
