### ISSUE TITLE
Send email to all related records

### ISSUE THREAD

**Issue by reeid** [YetiForceCompany/YetiForceCRM#5274]
HI

Wondering if there is an option to configure workflow (variables) to allow sending emails to all related records (for instance: send emails to all contacts related to account triggered on particular status change in account record).

Help appreciated

**Comment by paula-w** [comment]
Right now we don’t have this mechanism. You can use something that was added in campaigns in related modules but it needs some programming work [1-2 days of work]. You can also add your own special function in workflow.
