### ISSUE TITLE
Error!!! SQLSTATE[HY000]: General error: 1364 Field 'taxparam' doesn't have a default value The SQL being executed was: INSERT INTO `u_yf_ssingleorders_inventory

### ISSUE THREAD

**Issue by infoTopcloudxl** [YetiForceCompany/YetiForceCRM#5283]
#### Issue
After updating to the latest Yetiforce (4.2) i receive an sql error when creating a sales order

#### Actual Behavior
I receive the following error
Error!!!
SQLSTATE[HY000]: General error: 1364 Field 'taxparam' doesn't have a default value The SQL being executed was: INSERT INTO `u_yf_ssingleorders_inventory` (`seq`, `qty`, `qtyparam`, `name`, `comment1`, `taxmode`, `currency`, `currencyparam`, `value1`, `id`) VALUES (1, '1', NULL, 8255, '', 0, 1, '{\"1\":{\"date\":\"2017-09-28\",\"value\":\"1\",\"conversion\":\"1\"}}', '', 8256)

#### Expected Behavior
It should create a sales order

**Comment by infoTopcloudxl** [comment]
Does anyone know how to solve this isseu? i had it working on a test envoirement, now have this error on our live envoirement!!

**Comment by infoTopcloudxl** [comment]
I removed ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES, in the SQL mode, seems to work for now.

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements
