### ISSUE TITLE
[bug] Language management

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5290]
Having to search missing translations in some modules not working, searching never ends.
![language management system settings](https://user-images.githubusercontent.com/10330264/31044792-d14d2e36-a5de-11e7-8cb3-db436bfbbead.png)

#### Your Environment

* YetiForce Version used: Latest dev 4.2.270
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/5c54cce7986a364250d75af08b7f3e6bbf2129f3
