### ISSUE TITLE
f.y.i. issues in dev version

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5291]
Had not much to do this morning, so installed fresh copy of dev version 4.2.270 and noticed that layouts for new/view/edit is broken for modules (ok on gitdeveloper.yetiforce.com)
![new](https://user-images.githubusercontent.com/10330264/31052827-8965a756-a697-11e7-9f22-3ed424cc07ec.png)
![view](https://user-images.githubusercontent.com/10330264/31052829-9056ef3e-a697-11e7-8b69-99b48fe318b3.png)
and after logging out, not able to log in any more. Delete this if known

* Browser name and version: chome
* Environment name and version:
* Operating System and version: centOS 7 PHP 7.0.23

**Comment by bpabiszczak** [comment]
Now it works fine.

**Comment by kpaulaha** [comment]
And so it does, great work folks!
