### ISSUE TITLE
Set view permissions

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#5293]
#### Issue
How i can set a view permissions based on a field value?

#### Actual Behavior
I have 2 options on a picklist field and i want to set a permission to a specific user to view only records based on that field value.
If i trying to use advanced permissions, the other users don't see records that are already created from other users.

#### Expected Behavior
A posibilitty to restrict viewing based on that field value.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
It’s best to test this functionality on versions 4.2 and higher because in 4.0 many things weren’t working. This is an optional configuration and you have to remember that in case or larger databases [in fact in case of a larger number of users and records] it might not work optimally.
