### ISSUE TITLE
How to change ProductsTableNew.php table font size

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#5296]
#### Issue

How can we change ProductsTableNew.php table font size. We want to reduce table row font.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2
* Browser name and version: Safari and Chrome
* Environment name and version: CPAnel
* Operating System and version: Linux Debian 8

**Comment by bpabiszczak** [comment]
Here: https://github.com/YetiForceCompany/YetiForceCRM/blob/99cd00bde516f6c1feca6e5c397e16809d940ab0/vendor/yetiforce/TextParser/ProductsTableNew.php
