### ISSUE TITLE
[BUG] REPORT DETAIL: Error when calling SQL query v4.2.279

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5298]
v4.2.279
![error report](https://user-images.githubusercontent.com/19627226/31110009-1b10ecdc-a82e-11e7-9829-001d1082ea3f.gif)

**Comment by ezbank** [comment]
it still exists at v4.2.435

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6538
