### ISSUE TITLE
Map account/lead/contact don't work 

### ISSUE THREAD

**Issue by piedpulse** [YetiForceCompany/YetiForceCRM#5300]
Map inside contacts don't work, i tried in system admin to insert api key, but give me error

Any suggestions?

Thank you

* YetiForce Version used: 4.2.0
* Browser name and version: friefox / Chrome
* Environment name and version:
* Operating System and version: Centos 7 64bit

**Comment by orablue** [comment]
You are not along. With version 4.2.0, I'm also getting a JS error when I enter my Google API key. 

With version 4.0.0, there's no error but how do I tell if it is working?

**Comment by mariuszkrzaczkowski** [comment]
Can you try to trigger it on gitdev?

**Comment by ldgbc** [comment]
@orablue @piedpulse 

Going to assume you didn't get the following done.

1) Enable the Module
2) Enter the API key of the module
3) Add some address to your Contact/Account/Etc
4) Run CRON job for it to update the Address to a Coordinate
5) Use Map function
6) Realize it not very accurate lol

I manage to get it to work, if you need help let me know.
