### ISSUE TITLE
[question] Problem z dodaniem pola dla modułu

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5302]
#### Issue
Chcę dodać nowe pole dla wybranego modułu, niech to będzie np. Kontakty. Co bym nie wpisał w "Nazwie etykiety" dostaje komunika "Wprowadzono niedozwolony znak". Skąd ten komunika? Próbowałem litery, cyfry...

Czy jest jakiś  schemat dla dodawania pół? W dokumentacji nie znalazłem nic na ten temat.

Pozdrawiam
![new_field_screencapture-gitdeveloper-yetiforce-index-php-1507049199675](https://user-images.githubusercontent.com/26583746/31137511-c35f81b8-a86b-11e7-9657-ffa5e368bebc.png)

**Comment by bpabiszczak** [comment]
to raczej problem z drugim polem, po drugie o ile pamiętam, jest gdzieś niedozwolona listą nazw a więc spróbuj użyć innej nazwy [bez test]. W nazwie systemowej usuń podkreślenie.

**Comment by anderpydev** [comment]
Widziałem w kodzie listę niedozwolonych loginów (o ile dobrze pamiętam), ale z listą niedozwolonych nazw chociażby w dokumentacji się nie spotkałem. Nazwę test_field tak tylko sprawdzałem, ale wcześniej inne też próbowałem, bez słowa "test" i to samo.

**Comment by anderpydev** [comment]
PS: Udało się, faktycznie to podkreślenie było problemem. Mylące jest to, że pola standardowe w nazwie systemowej posiadają podkreślenie_ a dodawane przez użytkownika muszą być bez, no i przede wszystkim komunikat o błędzie pojawia się przy nazwie etykiety, a nie przy nazwie systemowej :)

Dziękuję.

**Comment by bpabiszczak** [comment]
Oczywiście poprawimy, dobrze, że udało się namierzyć problem :]
