### ISSUE TITLE
I have set up yetiforce on local server and working like a charm. My problem is redirecting. I have web site where I direct to local IP address and yetiforce launches but the IP address is showing in URL. Question is how do I change .htaccess file to rewrite so website URL is showing. 

### ISSUE THREAD

**Issue by GARLAND122** [YetiForceCompany/YetiForceCRM#5314]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by skramanzia** [comment]
¿?
 Its not a YF  issue. You can edit "config/config.inc.php" file and in your public DNS redirect to the public IP the CNAME or NAME register.

**Comment by GARLAND122** [comment]
Thanks

**Comment by calvinsug** [comment]
in Yetiforce 5.1 i found $site_URL in config/main.php

It is the correct configuration ? Because when i changed the url i screwed up my application and i can't access it again, it redirected to http://192.168.64.3/yetiforce/install/Install.php
