### ISSUE TITLE
zdjęcia produktu w szablonach pdf

### ISSUE THREAD

**Issue by logostrade** [YetiForceCompany/YetiForceCRM#5324]
jak dodać do szablonu pdf zdjęcia załączonego produktu do oferty bądź faktury ?   nie znalazłem nawet opcji dodania pola do modułu z możliwością załączenia plików np jpg do dokumentów (oferta, faktura itp)  jest jakieś rozwiązanie?Generated by YetiforceCRM ver. 4.2.0PHP: 7.0.23-1~dotdeb+8.1Server configuration errors:output_buffering: 1innodb_lock_wait_timeout: 50

**Comment by bpabiszczak** [comment]
Należy zrobić to na poziomie skryptu PHP odpowiedzialnego np. za generowanie tabelki z produktami. Wystarczy odpowiednio zmodyfikować ten plik: https://github.com/YetiForceCompany/YetiForceCRM/blob/99cd00bde516f6c1feca6e5c397e16809d940ab0/vendor/yetiforce/TextParser/ProductsTableNew.php
