### ISSUE TITLE
[BUG] Role based status picklists and status change modal window

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5328]
#### Issue

Please see gif below. Bug available at 4.2 and 4.2.312

![rolebased statuses](https://user-images.githubusercontent.com/8545791/31389726-a33e67ae-adda-11e7-89fd-763b767d0efa.gif)

#### Actual Behavior

- You can't change record status trough full edit page if real record status not available for your role
- You can change status for every record to Accepted if this picklist value not available for your role trough Change Status modal window by clicking to green button.

#### Expected Behavior

- You can pick every possible value for your role
- You can't change status to Accepted if your role don't have permissions for this picklist value.

#### How to trigger the error

Try to repeat my actions on gitdev

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
