### ISSUE TITLE
How ActiveSale in Opportunities is automatically updated? 

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#5330]
#### Issue

How ActiveSale in Opportunities is automatically updated? My is always blank.
Is it possible to have a customized formula to update it?

#### Actual Behavior

ActiveSale field in Opportunities  is always blank

#### Expected Behavior

ActiveSale field in opportunities updated with actual sale.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2
* Browser name and version: Safari & Chrome
* Environment name and version: CPanel + Linux
* Operating System and version: Linux

**Comment by paula-w** [comment]
Can you explain it in a little more detail? Perhaps a short video would be a good idea. We don't really understand your question.
