### ISSUE TITLE
[Question on V4.2] Can products table be shared / copied from Quotes to Proforma Invoice and from Proforma Invoice to Sales Order and to Invoice?

### ISSUE THREAD

**Issue by PDMeira** [YetiForceCompany/YetiForceCRM#5331]
I am new at the Yeti CRM and most probably missing something.
Can a products / service table be shared between Quotes / Proforma Invoice / Sales Order / Invoice modules?
Do we need to fill that all the time in the four modules?

**Comment by vovpff** [comment]
@PDMeira try Software configuration > Standard modules > Mapping > System settings
on getdev you can find it here: https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95
