### ISSUE TITLE
Workflow error

### ISSUE THREAD

**Issue by marcogerm** [YetiForceCompany/YetiForceCRM#5332]
When I set an expression workflow I get 500 error. What can I do?

**Comment by vovpff** [comment]
@marcogerm check expression sintax first.
What epression you set?

**Comment by marcogerm** [comment]
@vovpff simple math operators

**Comment by JohnMaverick** [comment]
expression syntax should not throw error as such

**Comment by marcogerm** [comment]
with any expression I get 500 error

**Comment by skramanzia** [comment]
@marcogerm please tell us which version of YF you use, and example of four expressions.

#### How to trigger the error

**Comment by marcogerm** [comment]
@skramanzia 
the version of yf is 4.2.0, an example of expression is field1 * field2, but whatever expression
![yetiforce_error](https://user-images.githubusercontent.com/32359071/31531729-182b8082-afe9-11e7-932d-0271de858c77.gif)
 returns error.

**Comment by kpaulaha** [comment]
Duplicate #4835

**Comment by marcogerm** [comment]
perfect, resolved!
