### ISSUE TITLE
manual Email import with embedded image not working

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#5333]
when I try to manually import an Email that has an embedded image everything looks fine but the email is not imported
![man-import-failed](https://user-images.githubusercontent.com/10443220/31526109-15ffc72e-afc5-11e7-8d3e-2f041a161fa2.gif)

The email body contains this img code
`<img` width="97" height="92" id="Bild_x0020_1" src="cid:image001.jpg@01D33CF7.A4ACC0D0" alt="cid:image001.jpg@01CF6482.191F4700">`

I tracked the problem down to the file web/vendor/yetiforce/Fields/File.php function saveFromContent line 474: $record->file = [ .... ]
and as far I can see the record model does not have a object called 'file'

code is the same in the developer branch

**Comment by mariuszkrzaczkowski** [comment]
We will fix email import in a moment. I don’t know if the problem is related to what you are reporting, so please check if it’s working. Unfortunately you didn’t provide us with any info on your version so you have to check it yourself if everything works after our changes.

**Comment by setras** [comment]
@mariuszkrzaczkowski did you fixed this issue yet? can you give me the commit id.
btw - I'm using version 4.2.0

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/053183b296ade0eb9edfd557881fff678b57d4db
