### ISSUE TITLE
Problems importing emails created with Outlook/Office365

### ISSUE THREAD

**Issue by setras** [YetiForceCompany/YetiForceCRM#5334]
Emails created with Microsoft Outlook/Office365 contain a lot of styling and other unneeded html code, see [original content.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/1381180/original.content.txt).
The standard YF 4.2 CreateEmail parseContent() function only removes the `<html>`  and `<body>` tags but leaves the MS stylsheets and other code intact. This can cause rendering problems. [YF-4.2-sanitized-content.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/1381186/YF-4.2-sanitized-content.txt)
I modified the function to remove all of the unneeded MSO and styling code. [new-saitized-content.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/1381193/new-saitized-content.txt)

~/modules/OSSMailScanner/scanneractions/CreatedEmail.php
[CreateEmail.diff.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/1382710/CreateEmail.diff.txt)

**orginal code**
`>79,81c78,91``
>< 		$html = preg_replace('/<html[^>]+\>/', '', $html);
>< 		$html = preg_replace('/<body[^>]+\>/', '', $html);
>< 		$html = `str_replace(['<html>',` `'<body>',` `'</html>',` `'</body>'],` '', $html);

**modified code**
>        $html = preg_replace(
>					array(':<(head|style|script).+?</\1>:is', 	# remove <head>, <style> and <script> sections
>						  ':<!\[[^]<]+\]>:',            	# remove <![if !mso]> and friends
>						  ':<!DOCTYPE[^>]+>:',          	# remove <!DOCTYPE ... >
>						  ':<\?[^>]+>:',                	# remove <?xml version="1.0" ... >
>						  '~</?html[^>]*>~',              	# remove html tags
>						  '~</?body[^>]*>~',              	# remove body tags
>						  '~</?o:[^>]*>~',			# remove mso tags
>						  '~\sclass=[\'|\"][^\'\"]+[\'|\"]~i',	# remove class attributes
>					),
>					array('', '', '', '', '', '', '', ''), 
>					$html);
> 

**Another improvement for the parseContent() function:**
Sometimes the email content is not sent in the email body but instead as an .html attachment. Roundcube and other clients automatically display these attachments but not YF when imported.
```
78c78,88
<		$html = $mail->get('body');
---
> 		
>		$html = $mail->get('body');
> 		$attachments = $mail->get('attachments');
> 		if (count($html) < 2) {
> 			foreach($attachments as $attachment)
> 			{	
> 				if ((substr($attachment['filename'], -5) == ".html") or (substr($attachment['filename'], -4) == ".txt") ) {
> 					$html .= $attachment['attachment']  . "<hr />" ;
> 				}
> 			}
> 		}
> 

```

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/5488

**Comment by mariuszkrzaczkowski** [comment]
@setras Thanks
