### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by Pikaloko** [YetiForceCompany/YetiForceCRM#5336]
#### Issue

Creating new client 

#### Actual Behavior

Błąd!!!

ERR_INCORRECT_VALUE_WHILE_SAVING_RECORD

Cofnij sięStrona główna

#0 modules/Vtiger/uitypes/Base.php(47): Vtiger_Base_UIType->validate(Array)
#1 modules/Vtiger/actions/Save.php(132): Vtiger_Base_UIType->setValueFromRequest(Object(App\Request), Object(Accounts_Record_Model))
#2 modules/Vtiger/actions/Save.php(93): Vtiger_Save_Action->getRecordModelFromRequest(Object(App\Request))
#3 modules/Vtiger/actions/Save.php(74): Vtiger_Save_Action->saveRecord(Object(App\Request))
#4 include/main/WebUI.php(192): Vtiger_Save_Action->process(Object(App\Request))
#5 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#6 public_html/index.php(11): require('/home/gitdevelo...')
#7 {main}

#0 [trace] Entering getColumnFields(Users) method ...
#1 [trace] Exiting getColumnFields method ...
#2 [trace] Entering getColumnFields(Accounts) method ...
#3 [trace] Exiting getColumnFields method ...
#4 [trace] Entering App\Field::getFieldPermission: 6,accountname
#5 [trace] Entering App\Field::getFieldsPermissions: 6
#6 [trace] Entering App\Field::getFieldPermission: 6,accountname
#7 [trace] Entering App\Field::getFieldsPermissions: 6
#8 [trace] Entering App\Field::getFieldPermission: 6,account_no
#9 [trace] Entering App\Field::getFieldsPermissions: 6
#10 [trace] Entering App\Field::getFieldPermission: 6,account_no
#11 [trace] Entering App\Field::getFieldsPermissions: 6
#12 [trace] Entering App\Field::getFieldPermission: 6,account_id
#13 [trace] Entering App\Field::getFieldsPermissions: 6
#14 [trace] Entering App\Field::getFieldPermission: 6,account_id
#15 [trace] Entering App\Field::getFieldsPermissions: 6
#16 [trace] Entering App\Field::getFieldPermission: 6,industry
#17 [trace] Entering App\Field::getFieldsPermissions: 6
#18 [trace] Entering App\Field::getFieldPermission: 6,industry
#19 [trace] Entering App\Field::getFieldsPermissions: 6
#20 [trace] Entering App\Field::getFieldPermission: 6,accounttype
#21 [trace] Entering App\Field::getFieldsPermissions: 6
#22 [trace] Entering App\Field::getFieldPermission: 6,accounttype
#23 [trace] Entering App\Field::getFieldsPermissions: 6
#24 [trace] Entering App\Field::getFieldPermission: 6,assigned_user_id
#25 [trace] Entering App\Field::getFieldsPermissions: 6
#26 [trace] Entering App\Field::getFieldPermission: 6,assigned_user_id
#27 [trace] Entering App\Field::getFieldsPermissions: 6
#28 [trace] Entering App\Field::getFieldPermission: 6,was_read
#29 [trace] Entering App\Field::getFieldsPermissions: 6
#30 [trace] Entering App\Field::getFieldPermission: 6,was_read
#31 [trace] Entering App\Field::getFieldsPermissions: 6
#32 [trace] Entering App\Field::getFieldPermission: 6,shownerid
#33 [trace] Entering App\Field::getFieldsPermissions: 6
#34 [trace] Entering App\Field::getFieldPermission: 6,shownerid
#35 [trace] Entering App\Field::getFieldsPermissions: 6
#36 [error] ERR_INCORRECT_VALUE_WHILE_SAVING_RECORD => modules/Vtiger/uitypes/Base.php:62
#37 [warning] cannot translate this: 'ERR_INCORRECT_VALUE_WHILE_SAVING_RECORD' for module 'Vtiger' (or base or Vtiger), lang: pl_pl
#38 [warning] cannot translate this: 'ERR_INCORRECT_VALUE_WHILE_SAVING_RECORD' for module 'Vtiger' (or base or Vtiger), lang: en_us

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
It should already work, we are currently in the process of adding a new validation layer, and errors may occur.
