### ISSUE TITLE
Plans to remove languages (FR)

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#5338]
We noticed that there are plenty of missing translations in French. Unfortunately, this is not something we can accept and therefore this language will be no longer available in version 4.3. 

If there are any community members who want to add the missing translations and update these languages on a regular basis please let us know. Otherwise, version 4.3 will only be available in English, Polish, Spanish, Portuguese, Russian and German. The deadline for submitting translations is 2 weeks from now. 

Remember we require a signed CLA in order to add translations submitted by our community members. (more about CLA: [LINK](https://yetiforce.com/en/open-source/contribution)) 

**UPDATE**: We received Spanish translations from @WalterLuis , Russian from @Foxmillet , and @rodrigolzd will send us Portuguese translations around December, and therefore we decided to keep these languages in the system. However, since there has been no interest in the French language, it will not be available in the new version.

**Comment by WalterLuis** [comment]
Good Morning,

in principle I think I have uploaded all the translation into Spanish, and for my part I do not mind continuing to upload translations in my spare time, so I will try to upload the missing translations during this week.

**Comment by Foxmillet** [comment]
Hello!

I want to submit missing Russian translations as an individual contributor, but am not sure how to sign your CLA, because I don't have a company name or address or any representatives.

**Comment by paula-w** [comment]
@WalterLuis that would be great, thanks!
@Foxmillet you can skip the fields that ask for company details if you want to submit it as an individual, so you fill in rep's name, rep's email, rep's phone, and both signatures. Glad to hear you wanna help out, thanks a lot!

**Comment by WalterLuis** [comment]
@paula-w translation done #5357

**Comment by Bailundo** [comment]
Hello
I appreciate your work and I am willing to cooperate in the Portuguese translation of Portugal (pt_pt). It has been completely translated by me and may need periodic adjustments. If you are interested, can you tell me where to send it?

**Comment by paula-w** [comment]
Hi @Bailundo 
Thanks a lot! You can send us a pull request with your translations ([here's](https://help.github.com/articles/creating-a-pull-request/) a tutorial on how to do that).
We require a signed CLA from all our contributors, you can find it [here](https://yetiforce.com/en/open-source/contribution#issue_pr).

**Comment by Foxmillet** [comment]
Yay! Glad to see Russian is now onboard. <3 And sorry once again about spamming with patches and requests, I had to read the instructions more thoroughly before doing anything.

**Comment by rodrigolzd** [comment]
This is really sad, i'm about hours away from giving a client the option to use the software, and now i'm guessing i'll have to revert back to vtiger. which is not ideal as we require mobility and yetiforce is working fine on mobile phones.

I'd love to translate and help, but not in the timeframe proposed (My post grad thesis is due in 30 days)

I've been waiting to get version 4.3 to migrate from Vtiger 6.5 for my own business and 2 other friends. Please keep the translation.

**Comment by rodrigolzd** [comment]
I have to be honest, from the interface on the 4.2 test install I have, I cant agree there are lots of translations missing, in fact, the only one i can remember is the SMS notifier under integrations. 

Is 4.3 so different that many more translations are missing? is there a demo of 4.3 where I can see the missing translations?

**Comment by bpabiszczak** [comment]
https://gitdeveloper.yetiforce.com/

**Comment by rodrigolzd** [comment]
I have looked at the demo, and honestly feel it would be a mistake to remove the PT-BR translation.

On the front-end for users, there are so few translations missing that you have to hunt for them item by item in the menu, and the one translation that I've found missing the most is the "List of all records" button under a few modules, most modules have it translated anyway.

On the Administrative part, there are also very few translations missing, and I've found only 1 module that is missing the biggest translation, "Triggers",

Here is couple more worth mentioning for only parts missing: Colors, CRON (only 6 out of 30 jobs), 

So, IMHO, droping the translation would be a mistake, specially considering all the extra features it has over vtiger. I'll be signing up to translate soon, but right now I must focus on my Thesis. So the earliest I'll be able to start looking at this would be December, however, I think I might start using the software before that date, as I'm trying to get some mobility by migrating from Vtiger 6.5. 

Finally I'd say keep the translation, the missing parts are so few right now that its worth the wait of an update in the near future.

**Comment by michelmarquesbr** [comment]
@rodrigolzd 

Tenho interesse em ajudá-lo nas eventuais traduções.

**Comment by paula-w** [comment]
I updated the original issue to clearly state what stays and what goes.
To sum up -  ES, PT & RU stay in the system, unfortunately FR needs to go. 
**Huge thanks to our contributors for help!**

**Comment by te-deum** [comment]
I am working on French translation (aroud 98% done). Is it possible to send you my contribution or is it too late ?

**Comment by bpabiszczak** [comment]
It is never too late: P

**Comment by ldgbc** [comment]
I suppose you can always provide a partial translation in the community and use the Import (does that exist) function and import the language. At least that way you are not left without any other option.
