### ISSUE TITLE
Bad idea: $this->getByType('parent', 1);

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5339]
#### Issue

Sorry, I'm back (and have some new patches). Meanwhile one of the recent changes:
~~~php
...
$parentModule = $this->getByType('parent', 1);
...
~~~
is a real bad idea. "parent" can be empty or an numeric value. Checking against "word" and just throwing an exception will break the code on some places. What about a special "getParentName" that also translates the module id to the name. Later in code its value is compared to "Settings" which would not work even that check does not exist.

#### How to trigger the error

1. e.g. "ajax" select all organisations and look at the logs
2.
3.

**Comment by mariuszkrzaczkowski** [comment]
Where is the numeric value in this parameter?
I made a minor improvement this feature, see https://github.com/YetiForceCompany/YetiForceCRM/commit/70d3c62b6efb5c4cb9cc3be2f91db0db8fbeb804
How do you have an idea how to improve this code, create a pull request

**Comment by migoi** [comment]
@mariuszkrzaczkowski 

e.g. Calendar: 
~~~
index.php?module=Calendar&view=Calendar&mid=46&parent=44
~~~

or all that comes across this line
~~~php
$url = $moduleModel->getDefaultUrl() . '&mid=' . $row['id'] . '&parent=' . $row['parentid'];
~~~

I think those are generated and "hardcoded" stored in the menu_XY.php files in user_privileges.

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/70d3c62b6efb5c4cb9cc3be2f91db0db8fbeb804#diff-8fc61f07740ce64131415a96c0664ae2
Thanks
