### ISSUE TITLE
Translations in custom modules

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#534]
If you make a custom module with Module creator you are not able to translate fields to other language as with custom fields in ordinary modules. Tested with ver. 1.4.122.

**Comment by kpaulaha** [comment]
Not able to Install exported custom module if containing other language than English

**Comment by bpabiszczak** [comment]
I checked it and it can be translated, but you have to remember to select another language that has translations [e.g. English]. If you select only one language that doesn't have translations, it won't be possible to select from a list of modules. If in your opinion it still doesn't work, please describe step by step how we can test for this bug on our testing version.

Please add a new module [on our testing version] and attach it in an issue on GitHub.

**Comment by kpaulaha** [comment]
Well, checked it, same problem. If I make a simple module with two languages, English and Finnish (translated with Language editor), export it and install from file, I get


although it contains both language files. What have I missed?

Regards

Kpa

-------- Alkuperäinen viesti --------
Lähettäjä: Błażej Pabiszczak <notifications@github.com> 
Päivämäärä: 04.05.2015  10.50  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] Translations in custom modules (#534) 

I checked it and it can be translated, but you have to remember to select another language that has translations [e.g. English]. If you select only one language that doesn't have translations, it won't be possible to select from a list of modules. If in your opinion it still doesn't work, please describe step by step how we can test for this bug on our testing version.

Please add a new module [on our testing version] and attach it in an issue on GitHub.
