### ISSUE TITLE
Database structure and inital values

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5340]
On working with the development code its hard to keep track on table creation, renames, deletions or just keep the initial/default data on current state.

Basic cause for this is the fact, that in two database dumps most of the database table structure and initial data is handled.

For update packages, the steps to get to next versions data-structure is delivered by code, so the update is possible.

Why not defining the need structure and data per module and have a "healthcare" admin module, that will check and (auto-) repair the database to the current needed structure.

**Comment by mariuszkrzaczkowski** [comment]
We are working on a special mechanism that will be used for system installation and database repair.
Therefore, we want to replace the database structure stored in the SQL file to PHP, eg https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/install/install_schema/Admin.php
Moving a full base requires rebuilding some mechanisms and it takes a lot of time.
Example new mechanism:
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/finish/InstalNewDb.php#L31

It is used in the last update package and will be used in each subsequent. Just copy all the files of the new database structure from the clean system and run the update and make the missing changes.
https://github.com/YetiForceCompany/UpdatePackages/blob/developer/YetiForce%20CRM%204.x.x/4.1.0_to_4.2.0/updates/init.php#L72

**Comment by migoi** [comment]
yeah, that's the direction. Why not placing the "real information" inside a json or yaml like structure. With the object oriented notation (or xml) you will get a lot of overhead. The "loading / transition" of the json-data to the object-oriented could be automated and so much less writing.

One is the basic information like structure and default data. Another one is the transition from records, tables etc. I've had something like that many years before in another php project. 

Yes, the start is really time consuming, but the benefit should be worth the time cause you get a much easier to administer installation. For the kickoff those data-info-files could be generated from the dump sql files.

**Comment by mariuszkrzaczkowski** [comment]
> yeah, that's the direction. Why not placing the "real information" inside a json or yaml like structure. With the object oriented notation (or xml) you will get a lot of overhead. The "loading / transition" of the json-data to the object-oriented could be automated and so much less writing.

What do you mean "real information" ?
What are the benefits of storing data in xml? I do not see them and so it is then necessary to convert to a query that will add data to the database.

> One is the basic information like structure and default data. Another one is the transition from records, tables etc. I've had something like that many years before in another php project.

Do you know any ready scripts / frameworks that make it easy to map the database structure and records to the database?

> Yes, the start is really time consuming, but the benefit should be worth the time cause you get a much easier to administer installation. For the kickoff those data-info-files could be generated from the dump sql files.

At present we have a lot of work and the mechanism is waiting for completion, it would be great if the community helped in the development of the system.

**Comment by migoi** [comment]
in php the most common is
https://book.cakephp.org/3.0/en/phinx.html

**Comment by migoi** [comment]
those update script are currently hand-crafted?

**Comment by mariuszkrzaczkowski** [comment]
> in php the most common is
> https://book.cakephp.org/3.0/en/phinx.html

We can not use this because it would require changing the query handling.

> those update script are currently hand-crafted?

Yes
