### ISSUE TITLE
Error with "Choose fields that will be used to search for recipient of email message"

### ISSUE THREAD

**Issue by dva200** [YetiForceCompany/YetiForceCRM#5341]
#### Issue

Error with "Choose fields that will be used to search for recipient of email message."

#### How to trigger the error

Admin > Settings > Mail Tools > Mail – Scanner > General configuration > Search email configuration > Choose fields that will be used to search for recipient of email message.

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Tested at all of them
* Environment name and version:
* Operating System and version: windows 10

![error](https://user-images.githubusercontent.com/32871443/31664925-eaa58fc6-b34f-11e7-87c5-609f956e76bd.png)

**Comment by mariuszkrzaczkowski** [comment]
I tested on gitdev, i can’t see the problem.

**Comment by dva200** [comment]
I am not speaking about gitdev.
Test it on stable

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/5040 https://github.com/YetiForceCompany/YetiForceCRM/issues/4854
