### ISSUE TITLE
[Question@YF] About the REGULATION (EU) 2016/679

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#5343]
I have a question about the EU Regulation 2016/679. Since I know no schedule planning for yetiforce, I would be interested when these requirements are implemented and for which release these are planned?

[English](http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=DE)
[more languages](http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2016.119.01.0001.01.DEU)

**Comment by paula-w** [comment]
bpabiszczak's response:
We’re planning to implement all the necessary mechanisms required by the new EU regulation related to data protection. If I’m not wrong, the deadline is in May 2018. These mechanisms will be gradually added, within 3 – 6 months the system should be fully compliant with the new standards [as much as possible].
Everyone in Poland keeps talking about it so there is no way we will forget. We still don’t know what exactly we are supposed to do :] We changed the entire password management mechanism for starters :D
