### ISSUE TITLE
Purifier for fieldnames instead field id

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5344]
#### Issue

Purifier causes exception, since changing value via ajax e.g. for field "assigned_user_id".
Its tested against type 2 (word and int). 

current regex (vendor/yetiforce/Purifier.php)
~~~php
/^[[:alnum:]]*$/ 
~~~
wont let the underscore's pass

change to -> 
~~~php
/^[[:alnum:]_]*$/
~~~
or provide other solution please

#### How to trigger the error

1. visit organsiation. Change "belongs to"

**Comment by mariuszkrzaczkowski** [comment]
Added https://github.com/YetiForceCompany/YetiForceCRM/commit/c2e405f32727548d507f705582cc44aaae4ddf93#diff-c86116e72ccce596278304c10979c685R292 thanks
