### ISSUE TITLE
$this->record->getModule(); is not same to $recordModel->getModule(); 

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5348]
#### Issue

You changed (https://github.com/YetiForceCompany/YetiForceCRM/commit/b5aa48f87924cf8954a736cc4bfaa95a7c76a06f) in "modules/Vtiger/views/Edit.php":
~~~php
 -		$moduleModel = $recordModel->getModule();
+		$moduleModel = $this->record->getModule()
~~~

but some line before $recordModel is created various times depending on variables are set. Unfortunately "$this->record->" can be null at that location so the code will prevent editing data (new record). 

#### Actual Behavior

" Uncaught Error: Call to a member function getModule() on null "

#### Expected Behavior

No error :)

#### How to trigger the error

1. e.g. create new user

**Comment by migoi** [comment]
Test with: view users details

Almost same problem at "modules/Vtiger/views/Detail.php" 
line 72  ('Uncaught Error: Call to a member function getRecord() on boolean')
~~~php
	$recordModel = $this->record->getRecord();
~~~
since this in the preprocess, no record is set.

I've added:
~~~php
		if (empty($this->record)) {
			$this->record = Vtiger_DetailView_Model::getInstance($request->getModule(), $request->getInteger('record'));
		}
		$recordModel = $this->record->getRecord();
~~~

**Comment by mariuszkrzaczkowski** [comment]
Can you give a case where you trigger this error?
eg backtrace

**Comment by migoi** [comment]
@mariuszkrzaczkowski : sure - here it is

~~~
 PHP Fatal error:  Uncaught Error: Call to a member function getRecord() on boolean in modules/Vtiger/views/Detail.php:75 
Stack trace: 
#0 modules/Settings/Users/views/Detail.php(28): Vtiger_Detail_View->preProcess(Object(App\Request), false) 
#1 include/main/WebUI.php(294): Settings_Users_Detail_View->preProcess(Object(App\Request)) 
#2 include/main/WebUI.php(225): Vtiger_WebUI->triggerPreProcess(Object(Settings_Users_Detail_View), Object(App\Request)) 
#3 index.php(25): Vtiger_WebUI->process(Object(App\Request)) 
#4 {main} 
  thrown in modules/Vtiger/views/Detail.php
~~~

for url ... /index.php?module=Users&parent=Settings&view=Detail&record=1

**Comment by mariuszkrzaczkowski** [comment]
I tested on gitdev, i can’t see the problem.

**Comment by migoi** [comment]
@mariuszkrzaczkowski 
cannot reproduce it either with latest code.

Only if a new record is inserted by webservice/api, because no view is involved and the first access to $this->record is before a checkPermission. 
Maybe the same for cron jobs.

I cant guess how it should work, since its still the transition to the newer security model. Please test with api and cron.

**Comment by mariuszkrzaczkowski** [comment]
Yes, you're right, we didn't predict that, I fixed it. https://github.com/YetiForceCompany/YetiForceCRM/commit/0ec1e9bbeb6b8d80cbf0ec3b11107e692d2d1e62

**Comment by migoi** [comment]
@mariuszkrzaczkowski 
confirmed. However I need some help please. 
I cannot create new records via webservice anymore (tried with calendar).

I do not understand fully how the "new system" should work. 

Why it fails (as far i saw via debugging):
The request ($_REQUEST) will receive a 
~~~php
           [module] => Calendar 
            [action] => Record 
           [record]  =>
~~~
because of the url the request points to with the POST request. this is going to fail because of the new isInteger check (which is false because it is not an integer).

Further: 'record' is null and not - that's expected when looking into SaveAjax - an empty string ''
so i've added in api/webservice/Portal/BaseModule/Record.php 
~~~php
$this->controller->request->set('record', '');
~~~
This will bring me one step ahead, but now it tries to simply save the record instead to create a new one. This will fail because of the empty "record"->''

~~~
error while saving new data: SQLSTATE[23000] Integrity constraint violation: 1048 Column 'record' cannot be null 
~~~

form save and ajax-save seems to have completely different approach right now.

**Comment by mariuszkrzaczkowski** [comment]
I found a small mistake, it was already repaired. Check if it will fix your error. https://github.com/YetiForceCompany/YetiForceCRM/commit/09c886c4873515796524856be1fe9d7e83a943f3
Additionally, I added a test for integration API. https://github.com/YetiForceCompany/YetiForceCRM/commit/6bff9ac5db645b9d4507dcb313e5481dbe0a7c06

**Comment by migoi** [comment]
confirmed - working again.

Thank you!
