### ISSUE TITLE
ERR_ILLEGAL_FIELD_VALUE, but no further information

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5349]
#### Issue

Its nice that values are much better checked now, but whenever such a message "ERR_ILLEGAL_FIELD_VALUE" appears, there is no information where or what value causes the error. 

e.g.
~~~php
		if (!is_numeric($value)) {
			throw new \App\Exceptions\SaveRecord('ERR_ILLEGAL_FIELD_VALUE', 406);
		}
~~~
What about adding "$value" as parameter?
Or even let the admin/user know that it was called by "not a number"

#### Actual Behavior

It could be called at 1 of 18 different locations - so you got a chance of ~5% to get it on first try.

#### Expected Behavior

to get a clue what value causes that error.

**Comment by migoi** [comment]
one addition to this one:

I try to import a user. The desired calendar format is "24" - string or numeric - i dont know.

The validate function contains this one: (modules/Vtiger/uitypes/Base.php)
~~~php
		if ((!is_string($value) && !is_numeric($value)) || $value !== strip_tags($value)) {
			throw new \App\Exceptions\SaveRecord('ERR_ILLEGAL_FIELD_VALUE', 406);
		}
~~~

Any string or numeric value cannot pass this if block. && should become || - right?

**Comment by mariuszkrzaczkowski** [comment]
I've added improvements, check it out

**Comment by mariuszkrzaczkowski** [comment]
This mechanism has not been completed yet, and the system will have full error logs in accordance with OWASP requirements

**Comment by migoi** [comment]
confirmed - much better. Thank you!

**Comment by migoi** [comment]
@bpabiszczak 
this one is "old style":
~~~
[error] - ERR_NOT_ALLOWED_VALUE => vendor/yetiforce/Request.php:170 
~~~

**Comment by paula-w** [comment]
@migoi , can you explain it a little further, please? We're not sure what you mean.

**Comment by migoi** [comment]
@paula-w 
sorry. Thats just the line from the logs. No further information on what "$key" that exception happens. @bpabiszczak has improved the output for value checks. Maybe this should also been improved a little bit. Like 
~~~
throw new \App\Exceptions\BadRequest('ERR_NOT_ALLOWED_VALUE||'.$key, 406);
~~~

btw: the "ERR_NOT_ALLOWED_VALUE" is not translated
