### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by starpdp** [YetiForceCompany/YetiForceCRM#5351]
please be informed that I have installed yetiforceCRM and getting following error -

Notice: Undefined index: layout in /home/starpdp/erp.sasanghalam.com/vendor/yetiforce/Session/Base.php on line 50

Regards,

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
PHP Notice errors are acceptable in the system, every day there are fewer of them, but we need a few more months to completely remove them from the system. It’s something we inherited from vtiger, they didn’t pay much attention to that.
