### ISSUE TITLE
Version 4.3 release date

### ISSUE THREAD

**Issue by basanthagarwal** [YetiForceCompany/YetiForceCRM#5353]
Sir, ... When is new Version 4.3 going to release ?

We are stilling using 3.4 Version. 
We are using your software since 8 months ... and 
we have further requirements in Yetiforce. 
How shall i get in touch with you ?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by varlog11** [comment]
Any news of release date?

**Comment by ezbank** [comment]
![3a0cc0e2-fd39-4cf5-b1d4-be72f100ac4b](https://user-images.githubusercontent.com/19627226/32440600-6f2b4e8a-c326-11e7-9486-eb1ae89e8203.png)

**Comment by bpabiszczak** [comment]
This week

**Comment by ezbank** [comment]
I will try to find new bugs and hope it is fixed

**Comment by paula-w** [comment]
We are fixing the issues, keep testing the system and reporting any problems you find.
