### ISSUE TITLE
Search on lookup/related field does not work

### ISSUE THREAD

**Issue by elvissaba** [YetiForceCompany/YetiForceCRM#5358]
#### Issue

Search on related modules (accounts, contacts...etc) from Roundcube does not work.
![image](https://user-images.githubusercontent.com/20727670/31867209-725ae1ca-b78b-11e7-8b15-48770de49326.png)

When I select accounts for example...

![image](https://user-images.githubusercontent.com/20727670/31867223-ab85d3f6-b78b-11e7-8014-b1e03eb56ff8.png)

In general, search doesn't work on any  lookup/related field:

![image](https://user-images.githubusercontent.com/20727670/31938487-f8d152f2-b8b7-11e7-8c0a-0a353c2f3b00.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by elvissaba** [comment]
Solved. Thnx.

**Comment by KatarzynaUlichnowska** [comment]
Can you describe how you solved the problem? It will be helpful for the community.

**Comment by elvissaba** [comment]
I've tested on gitdeveloper version last week and it didn't occur.
