### ISSUE TITLE
[BUG] Fix Menu Lang File

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#536]
Now problem in

$languageStrings = array(
	
);

and 

$languageStrings = Array(
	
);

Fix please

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
could you explain what is the problem in here? We don't understand what's wrong with it.

**Comment by waw555** [comment]
When adding a new language variable in the language editor, lost all but a new variable in yaschzykovom file creates a new array.

there is an array

$ languageStrings = Array (

);

when adding a new variable is added to another array

$ languageStrings = array (

);
