### ISSUE TITLE
Incorrect request on custom module

### ISSUE THREAD

**Issue by elvissaba** [YetiForceCompany/YetiForceCRM#5360]
#### Issue

When Extended module created:
![image](https://user-images.githubusercontent.com/20727670/31937700-9d51ebe6-b8b5-11e7-9b11-fc1e84402ff5.png)
And TestField in additional table:
![image](https://user-images.githubusercontent.com/20727670/31937802-e1f57e8e-b8b5-11e7-91ac-22a957375ac9.png)

On module open, Incorrect request message apears:

![image](https://user-images.githubusercontent.com/20727670/31937899-295bbe78-b8b6-11e7-9fb7-078782eb9c8e.png)

#0 vendor/yetiforce/Request.php(133): App\Purifier::purifyByType('0', 1)
#1 include/runtime/Controller.php(285): App\Request->getByType('parent', 1)
#2 modules/Vtiger/views/Basic.php(30): Vtiger_View_Controller->preProcess(Object(App\Request), false)
#3 modules/Vtiger/views/Index.php(34): Vtiger_Basic_View->preProcess(Object(App\Request), false)
#4 modules/Vtiger/views/List.php(64): Vtiger_Index_View->preProcess(Object(App\Request), false)
#5 include/main/WebUI.php(258): Vtiger_List_View->preProcess(Object(App\Request))
#6 include/main/WebUI.php(189): Vtiger_WebUI->triggerPreProcess(Object(Vtiger_List_View), Object(App\Request))
#7 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#8 public_html/index.php(11): require('/home/gitdevelo...')
#9 {main}

#0 [trace] Entering getColumnFields(Users) method ...
#1 [trace] Exiting getColumnFields method ...
#2 [info] Opening DB connection: mysql:host=localhost;dbname=gitdevelop_crm;port=3306 || yii\db\Connection::open
#3 [info] INSERT INTO `u_yf_browsinghistory` (`userid`, `date`, `title`, `url`) VALUES (5, '2017-10-24 11:15:54', 'TestModule List', 'index.php?module=TestModule&view=List&mid=152&parent=0') || yii\db\Command::execute
#4 [error] purifyByType: 0 || BadRequest
#5 [error] ERR_NOT_ALLOWED_VALUE => vendor/yetiforce/Purifier.php:313

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
on which version did you test it? We tested it on the latest gitdeveloper version and it didn't occur.

**Comment by elvissaba** [comment]
On GitDeveloper: https://gitdeveloper.yetiforce.com , 3 hours ago.

**Comment by elvissaba** [comment]
Not solved. Problem occurs when I create Extended module type (not base module) and field in additional table (not basic field).

**Comment by elvissaba** [comment]
Solved.

**Comment by KatarzynaUlichnowska** [comment]
Can you describe how you solved the problem? It will be helpful for the community.

**Comment by elvissaba** [comment]
I've tested on gitdeveloper version last week and it didn't occur.
