### ISSUE TITLE
Yetiforce installation

### ISSUE THREAD

**Issue by tafsircamara** [YetiForceCompany/YetiForceCRM#5361]
Is there possible to install yetiforce on XAMPP server?

**Comment by migoi** [comment]
why not?

**Comment by SkavenKF** [comment]
yes, no problem. i use xampp or wamp(bitnami) on w10 or windows server.

**Comment by mariuszkrzaczkowski** [comment]
It works fine, but you need to configure it. Here version ready to run
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.0.0/xampp_YetiForceCRM-4.0.0-complete.zip
