### ISSUE TITLE
how to handle: Field does not exist

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5362]
#### Issue

because of the new access to field, i receive:
~~~
[warning] - Field does not exist: was_read in Vtiger_Module_Model::getFieldByName 
~~~
in the logs for this and other field names - depending on the module.

Should I report them?
Add them to vtiger_fields  or is there any (general) way to fix them?

**Comment by paula-w** [comment]
Can you tell us what version of the system you tested this on, how to trigger this error, and where does it show up? Looking at this description only we don’t really know what to do.
