### ISSUE TITLE
Campaigns - load from filter fails [ver. 4.2.406]

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#5364]
Adding related record to Campaigns results in never ending "Loading, please wait."

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/73643242676a23c8996b5d09cf1d7f771617c958

**Comment by waran70** [comment]
Still not working. Infinity loading....
