### ISSUE TITLE
Workflows on related records not triggering [ver. 4.2.406]

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#5365]
Workflow started manually on related records (Campaign > Leads) not trigger any record changes

**Comment by paula-w** [comment]
Please provide us with some more details, we have to know what behavior you are expecting and what you're doing to be able to trigger this error. A short video/gif would be really helpful.

**Comment by elvissaba** [comment]
This is similar to issue #5354. In my case, i made workflow task - update related record. Second is notification task in workflow. When workflow is triggered, i get notification, but related record is not updated. My workflow should update field Description in related Account with description field of Contact is updated.

**Comment by mariuszkrzaczkowski** [comment]
The bug has been fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/3c93adb0bcdca9a92dff233f657f3374de682dd7
