### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#541]
The following error appears when trying to install the 1.3.0RC_to_1.4.0RC_v2.zip using module manager
![screen shot 2015-04-17 at 10 43 20](https://cloud.githubusercontent.com/assets/10218164/7199371/82d98e50-e4f4-11e4-9151-bbe124b2450d.png)

**Comment by mariuszkrzaczkowski** [comment]
Make sure you properly set permissions on files. Settings > About YetiForce > Server configuration > Files/Folders
