### ISSUE TITLE
Permissions errors when a Campaign is created

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#5433]
#### Issue

When I create a new Campaign I have some permissions errors on the console.

#### Actual Behavior
![2017-10-25_14-01-20](https://user-images.githubusercontent.com/16593721/32000164-b0fdcf6a-b98d-11e7-996b-0bb1e131f510.gif)

	{"success":false,"error":{"code":406,"message":"LBL_NO_PERMISSIONS_FOR_THE_RECORD","trace":"
		#0 include\main\WebUI.php(239): Campaigns_RelationAjax_Action->checkPermission(Object(App\Request))
		#1 include\main\WebUI.php(185): Vtiger_WebUI->triggerCheckPermission(Object(Campaigns_RelationAjax_Action), Object(App\Request))
		#2 index.php(25): Vtiger_WebUI->process(Object(App\\Request))
		#3 public_html\index.php(11): require('C:\\wamp64\vhost...')
		#4 {main}
	"}}

#### Expected Behavior
Don't have these errors

#### Your Environment

* YetiForce Version used: 4.2.408. Dowloaded on 25th October 2017
* Browser name and version: Google Chrome
* Environment name and version: PHP 7.1 - MariaDB 10.2
* Operating System and version: Windows 10

**Comment by paula-w** [comment]
Please check it on the gitdeveloper version once again, we fixed a ton of issues and currently we don't see the one you reported.
