### ISSUE TITLE
Phone: custom fields in user needs the suffix '_extra'?

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5436]
#### Issue

Because of a 
~~~
 Field does not exist: XXXXX_extra in Vtiger_Module_Model::getFieldByName ~
~~~
in Users view with a custom, phone related "XXXXX"-field the above message is shown in logs.

That is because of this
~~~php
$extra = $recordInstance->getDisplayValue($this->get('field')->getFieldName() . '_extra');
~~~

Is there a (hardcoded) suffix needed from now on? And if so - why?

**Comment by paula-w** [comment]
This field is used for entering the internal number and in order to make it active you have to change this parameter https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/config.template.php#L209

**Comment by migoi** [comment]
ok, I just want to have at least one custom field at a user. Unfortunatly there is no "official" way to do that like for other modules, i had to do it the "hardcoded" way. But all those fields getting the "_extra" suffix.
