### ISSUE TITLE
(back-button) paging in popup broken

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5439]
#### Issue

Even with #5438 fixed by workaround, the back-button in paging is always grayed-out and so you can only move forward in the list

Test:
https://gitdeveloper.yetiforce.com/index.php?module=Accounts&src_module=HelpDesk&src_field=parent_id&src_record=985&view=Popup&triggerEventName=postSelection166

maybe cause:
the ajax info does not set the paging information.

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/0819b2f36aa20296188ad7f71eeeb38ea8b8912b
