### ISSUE TITLE
new generated password (fail check if e.g. no digit)

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5441]
The newly generated password will fail if the randomiser failed to include any digit. 

The new algo should try if the new password will validate and not continue before

**Comment by migoi** [comment]
can a admin have both: generated and set a password?
is a "impersonate" feature planed?

**Comment by mariuszkrzaczkowski** [comment]
I improved the password generator https://github.com/YetiForceCompany/YetiForceCRM/commit/8525e297d336afe215f32873073af9b698078cbb#diff-e39d682cd71b2f76833125f25a378f49R74
