### ISSUE TITLE
calculated activities (days) block save when negative value

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5443]
#### Issue

because of 
~~~
... 'crmactivity', 'vtiger_entity_stats', 1, 1, 'crmactivity', 'LBL_CRMACTIVITY', ... , 'NN~O', ...
~~~
no negative value is allowed. So every save command will fail becaucse of validation. The user has no chance to edit this fielld since it is calculated  from today to the next activity date. That might be in past - so a negative value is possible.

Workaround:
change field type from 
~~~
NN~O
~~~
 to
~~~
I~O
~~~~

this wlli also fix that the integer value is displayed as float / double - e,g, 10,00 -> 10

**Comment by mariuszkrzaczkowski** [comment]
Today added support negative values for numeric fields (NN ~ O)
