### ISSUE TITLE
Theme integration

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5444]
#### Issue

I want to integrate theme from Vtiger 7 to Yetiforce CRM.

#### Actual Behavior

I don't know if exist a theme development documentation or something that can help me.

#### Expected Behavior

Help me with a documentation or i need to know what files i need to change.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: Google Chrome
* Environment name and version:
* Operating System and version: Windows 10

**Comment by migoi** [comment]
as far as I know: there is no documentation on that.
The current html & css is some collected "whatever" and really hard to modifiy unless you know what you are doing. Somewhere in the issues should be a conversation, where the devs talk about a new system of templates and css, so it would be much easier and themes are really possible.

**Comment by cltvchannel** [comment]
I think the theme from vtiger7 is looking much better and is easier to work with that.
I hope in the future will be possible to integrate that,

**Comment by mariuszkrzaczkowski** [comment]
What exactly do you want to do, create only a theme (only to map colors) or create layouts (layout change)?

**Comment by cltvchannel** [comment]
I want to be exactly like vtiger 7 layouts and colors. (I want the menu, icons and layouts).

**Comment by cltvchannel** [comment]
Any update?

**Comment by mariuszkrzaczkowski** [comment]
theme you can do without a problem here are some examples:
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/public_html/layouts/basic/skins
The layout will be a little bit complicated because you have to create a new layout and modify a lot of files
