### ISSUE TITLE
Add "Mass edit" to related lists [improvement]

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#5445]
"Mass edit" button in related lists will improve both user experience and overall performance.
Pls consider that

**Comment by paula-w** [comment]
It's a good idea, unfortunately, just like in case of many other good ideas, there would have to be a client who'd order this functionality. More about why we can't implement all community ideas into the system in [HERE](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-development-ideas)
