### ISSUE TITLE
New stable version request

### ISSUE THREAD

**Issue by bobbie0001** [YetiForceCompany/YetiForceCRM#5446]
Hello Team

I have done lot of research of CRM. Finally i found YetiForce is best as per my requirements. Since 2 days i am trying to install Yeti on my hosting. I am not sure exactly lot errors with various versions. I have started installing 4.0.0 and end up with 2.3.16 version. For least version, i unable to find any kind of errors. because it is just back page. Then i keep reducing the version. Now finally 2.3.16 stable version, i could able to install properly. 
But i am not happy with version. My request to team to provide stable latest version link for me. Appreciate for your hard work.

Regards

**Comment by waran70** [comment]
![clint_ew](https://user-images.githubusercontent.com/6852348/32201002-1399a158-be07-11e7-810f-7b63c331b028.gif)

**Comment by paula-w** [comment]
All releases are available here: https://github.com/YetiForceCompany/YetiForceCRM/releases
If you have problems with installing any of the stable versions you should ask for help someone who knows how to analyze error logs. 
We can also perform installation but it's a service we charge for.
