### ISSUE TITLE
release date of version 4.3 and portal

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#5447]
Hi
first of all thanks for your great job.
can you tell when is release date of version 4.3 and new customer portal?
we use yetiforce since version 2 and we have so many problems with customer portal.

**Comment by paula-w** [comment]
New RC version of the system will be released next week – 2017-11-10, a week later the stable version will follow. The portal will be released together with version 5.0, which will be published at the beginning of next year.
