### ISSUE TITLE
Error occur while using YetiforceCRM API

### ISSUE THREAD

**Issue by sbchamadiya** [YetiForceCompany/YetiForceCRM#5448]
I have refered the link "https://github.com/YetiForceCompany/YetiForceScripts/blob/master/YetiREST/demo_yetiforce_api.php" for Restful api but while accessing the API to get data i got error something like this "This should only be called from console".Please help me where is the issue is, and if any demo is there realted to API then provide it.

**Comment by migoi** [comment]
this php is not to be called from a browser. Instead call it from the command-line. The API should work silently. A "gui" like "ready to go" implementation is the yeti-portal.

What do you want to achieve?

**Comment by sbchamadiya** [comment]
Hello sir,
 I am developing a mobile application so i need to pass data from backend
through API.And i want to use Yetiforce CRM in backend.So how can i acheive
this thing?

**Comment by migoi** [comment]
well using API should be one of the best options.

**Comment by sbchamadiya** [comment]
How to achieve the API options?Provide some demo regarding API.How to
implement it?

**Comment by mariuszkrzaczkowski** [comment]
Here's an example of communication
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/tests/Integrations/Api.php

**Comment by mariuszkrzaczkowski** [comment]
Here you have some information about api #4023 #4442

**Comment by sbchamadiya** [comment]
I have refered the link but i am not getting exactly how to implement
it.Please explain in brief.

**Comment by migoi** [comment]
that would depend on the desired programming language

**Comment by sbchamadiya** [comment]
I am working on PHP(version 5.5.30) language.
