### ISSUE TITLE
 Yetiforce CRM API

### ISSUE THREAD

**Issue by sbchamadiya** [YetiForceCompany/YetiForceCRM#5458]
**Hello i am beginner in Yetiforce CRM**.I have an existing application in PHP language.So my question regarding yetiforce is as below : 
**1) I want to convert admin panel of my application in Yetiforce CRM.
2) I have to pass data to mobile application from database,so  using yetiforce CRM how it is possible?
3) I want to transfer my data from Mysql to database of yetiforce.**

So, how can i achieve all the above mention points.**Please provide demo of yetiForce CRM if available.**

**Comment by bpabiszczak** [comment]
Check how portal2 was built: https://github.com/YetiForceCompany/YetiForcePortal2
and how API works: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/api

Unfortunately we don't provide free programming support.
