### ISSUE TITLE
Password change: UserAuthMethod not alway filled

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5459]
#### Issue

Password change: UserAuthMethod not alway filled.

so I added the check for the "empty" case like that: in "modules/Users/actions/Password.php"
~~~php
...
		$authMethod = \App\Session::get('UserAuthMethod');
		if (!$isOtherUser && !empty($authMethod) && $authMethod!== 'PASSWORD') {
			$response->setResult(['procesStop' => true, 'notify' => ['text' => \App\Language::translate('LBL_NOT_CHANGE_PASS_AUTH_EXTERNAL_SYSTEM', 'Users'), 'type' => 'error']]);
...
~~~

**Comment by migoi** [comment]
also it seems more than one password hash algo is active
this
~~~
return crypt($text, '$1$' . \AppConfig::main('application_unique_key'))
~~~
and
~~~
		return password_hash($password, PASSWORD_BCRYPT, ['cost' => AppConfig::security('USER_ENCRYPT_PASSWORD_COST')]);
~~~

which will return different hash for some password. This causes the "new password" dialogues to fail, where the old password is required.

**Comment by mariuszkrzaczkowski** [comment]
> Password change: UserAuthMethod not alway filled.
> so I added the check for the "empty" case like that: in "modules/Users/actions/Password.php"

This situation can not be that UserAuthMethod is empty, it must always be set.
The problem may appear after updating for currently logged on users.
How can I trigger this error?

> which will return different hash for some password. This causes the "new password" dialogues to fail, where the old password is required.

So it should be, just so this new password encryption mechanism works that each time it gives another hash. This is because random salt is used. 
https://secure.php.net/manual/en/faq.passwords.php

**Comment by migoi** [comment]
long time ago :timer_clock: 

Yes, it may be caused because of the transition. I've tested it with my development version and "locked" the password changing on the productive system since users cannot logged in and cannot generate new passwords (should be fixed and reported). I could give it another try, but first want to be sure the users can still logged on. Can you mark "deprecated" the old functions, so i can checked when those are called?

**Comment by mariuszkrzaczkowski** [comment]
> long time ago ⏲
Do you think I have nothing to do?   check commits :)

> Yes, it may be caused because of the transition. I've tested it with my development version and "locked" the password changing on the productive system since users cannot logged in and cannot generate new passwords (should be fixed and reported). 

Describe exactly what you did and what the problem is because for the moment I do not understand your problem

> Can you mark "deprecated" the old functions, so i can checked when those are called?
sorry but i do not understand you

**Comment by migoi** [comment]
just close the issue. I will report if its still present and a problem

**Comment by mariuszkrzaczkowski** [comment]
ok :)
