### ISSUE TITLE
Breadcrumb: html escaped

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5460]
#### Issue

When creating a filter (or editing) and leaving the edit with save or cancel, the breadcrumb navigation displays html

e.g.:
~~~html
Companies and Contacts > Accounts > List<div class="breadCrumbsFilter dispaly-inline font-small"> [Filter: Test 1]</div> [Filter: Test 1]
~~~

#### Expected Behavior

~~~html
Companies and Contacts > Accounts > List [Filter: Test 1]
~~~

#### How to trigger the error

1. goto https://gitdeveloper.yetiforce.com/index.php?module=Accounts&page=1&view=List&viewname=121&orderby=&sortorder=&entityState=Active&search_params=&search_key=accountname&search_value=
2. simply click "save"
3. see breadcrumb

**Comment by ezbank** [comment]
4.2.472
![zalo_screenshot_10_11_2017_1749844](https://user-images.githubusercontent.com/19627226/32671486-315c5ffc-c67a-11e7-9126-8dce7a6cfdd9.png)
