### ISSUE TITLE
[QUESTION] HOW TO ADD JAVASCRIPT EMBED CODES

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5466]
I use tawk.to to insert the chat widget. but it does not show. I have inserted it into /layouts/basic/modules/Vtiger/Header.tpl .
It only works on the Edge browser.
v4.2.435
```
	 * HTTP Public-Key-Pins (HPKP) pin-sha256
	 * For HPKP to work properly at least 2 keys are needed.
	 * https://scotthelme.co.uk/hpkp-http-public-key-pinning/
	 * https://sekurak.pl/mechanizm-http-public-key-pinning/
	 */
	'HPKP_KEYS' => [],
	/**
	 * Content Security Policy
	 */
	'CSP_ACTIVE' => false,
];
```
![zalo_screenshot_3_11_2017_1456685](https://user-images.githubusercontent.com/19627226/32380132-e9e69db0-c0e1-11e7-9f94-0e6f92c04837.png)

**Comment by cltvchannel** [comment]
What files you changed to make this login page template?

**Comment by PercyP** [comment]
I kind of need to do the same with another chat component. In vtiger I just added a couple of lines of code to the header and footer files. With yeti i can't get it to work. I too like your login screen.

**Comment by mariuszkrzaczkowski** [comment]
You have an example of how you can add a JS file
```php
$modCommentsModule = vtlib\Module::getInstance('ModComments');
$modCommentsModule->addLink('HEADERSCRIPT', 'ModCommentsCommonHeaderScript', 'modules/ModComments/ModCommentsCommon.js');
```

**Comment by cltvchannel** [comment]
@ezbank hey. can you help me make a login page template like you?
