### ISSUE TITLE
PDF Template Generating Error

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5468]
#### Issue
I tried to create a PDF template for Contact module for example.
![pdfproblem](https://user-images.githubusercontent.com/30116021/32417213-ad1cf694-c25e-11e7-82d3-1046739cde49.gif)

#### Actual Behavior

I have write some text and arange them in page, size and color.
When i try to modify again the template, all the text changes from the past (size, color, page align) are not saved.
#### Expected Behavior

Please solve this problem to make possibly to generate PDF templates for modules.
This error is in last version.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Google Chrome
* Environment name and version:
* Operating System and version:

**Comment by cltvchannel** [comment]
any update?

**Comment by cltvchannel** [comment]
<?php
return [
	'appVersion' => '4.2.0',
	'patchVersion' => '2017.08.09',
	'lib_mPDF' => '0.0.2',
	'lib_roundcube' => '0.0.32',
	'lib_PHPExcel' => '0.0.0',
	'lib_gantt' => '0.0.1',
];


is ok to change appVersion from 4.2.0 to 4.2.499?

**Comment by cltvchannel** [comment]
I can't find Edit1.js file. Version 4.2.0

**Comment by vovpff** [comment]
@cltvchannel betveen 4.2.0 and 4.2.499 are there 498 fixes and updates. wait for 4.3.0 release
