### ISSUE TITLE
Install v4.2.443 error 500

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5476]
Logs
`[07-Nov-2017 17:15:35 UTC] PHP Fatal error:  Uncaught Error: Class 'vtlib\Deprecated' not found in /home/xxx/xxx/dev/include/Loader.php:68
Stack trace:
#0 /home/xxx/xxx/dev/include/main/WebUI.php(16): Vtiger_Loader::includeOnce('include.runtime...')
#1 /home/xxx/xxx/dev/index.php(14): require('/home/xxx/...')
#2 {main}
  thrown in /home/xxx/xxx/dev/include/Loader.php on line 68`

**Comment by ezbank** [comment]
any updates?
I want to install successfully to find out the new bugs

**Comment by mariuszkrzaczkowski** [comment]
I tested the installer on me works you can show full logs
