### ISSUE TITLE
shared filter/custom view should be possible to set as favourite or default (but cannot be edited) by other 

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5481]
#### Actual Behavior

A custom view / filter can be shared with other, but those cannot set this filter as default or as favourite.

**Comment by bpabiszczak** [comment]
Right now the filters mechanism is quite advanced. We know we have to fix managing them but right now it has low priority. For now whether or not someone can modify/create filters can be set in permissions. You decide who has it as their favorite and who doesn’t, you also set who sees it as default but you do it from the panel:  https://gitdeveloper.yetiforce.com/index.php?module=CustomView&parent=Settings&view=Index&block=13&fieldid=57
If you still think you can’t set it then please record a short video where you show it and describe it well.
