### ISSUE TITLE
[PL} Problem z raportami i listami 

### ISSUE THREAD

**Issue by slawhodu** [YetiForceCompany/YetiForceCRM#5482]
wersja 4.2
przy próbie wygenerowania raportów mam komunikat:

Catchable fatal error: Argument 2 passed to vtws_listtypes() must be an instance of Users_Record_Model, instance of Users given, called in /crm/include/Webservices/WebserviceField.php on line 275 and defined in /crm/include/Webservices/ModuleTypes.php on line 20

Podobnie przy próbie eksportu rekordów listy z kalendarza (kalendarz lista rekordów - akcje - eksportowanie rekordów) 

Warning: require_once(include/Webservices/VtigerModuleOperation.php): failed to open stream: No such file or directory in /crm/include/Webservices/Utils.php on line 384

Fatal error: require_once(): Failed opening required 'include/Webservices/VtigerModuleOperation.php' (include_path='.:/:/usr/local/php56/lib/pear') in /mitechcrm/include/Webservices/Utils.php on line 384

co może być przyczyną powyższych problemów? Aktualizacje przeszły poprawnie. W wersjach 3.x działało...

**Comment by mariuszkrzaczkowski** [comment]
Duplikat: https://github.com/YetiForceCompany/YetiForceCRM/issues/4882
