### ISSUE TITLE
How to insert data in yetiforce CRM Database?

### ISSUE THREAD

**Issue by sbchamadiya** [YetiForceCompany/YetiForceCRM#5483]
I am beginner in yetiforce.I am not able to access the data from database using yetiforce CRM API.Please guide me.

**Comment by mariuszkrzaczkowski** [comment]
See here https://github.com/YetiForceCompany/YetiForceCRM/issues/4163 https://github.com/YetiForceCompany/YetiForceCRM/issues/4023 https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20%20api%20
