### ISSUE TITLE
Date time format bug in a new Event / ToDo window

### ISSUE THREAD

**Issue by netinteractivemsz** [YetiForceCompany/YetiForceCRM#5485]
#### Issue
When user wants to create a new Event (Quick create:  EVENT / TO DO window) we see that there is some strange behavior of End date & time field. 

#### How to trigger the error
Steps:
1. Open window - Create new Event / To Do
2. Click on Activity type and change it with any possible option
3. Date format in "End date & time" changes and it shows bad datetime format, something like "Fr-32-yyyy"

4. Click on "End date & time" field it shows below calendar, next you click on any white space - it shows again proper datetime.
5. Click again on Activity type and change it with any possible option - again it shows "End date & time" in wrong format

6. Click on "End date & time" and CHOOSE one of calendar date, it shows proper datetime, and you can progress further.

#### Your Environment

* YetiForce Version used: 
* Browser name and version: chrome, firefox

![yetiforce](https://user-images.githubusercontent.com/33486713/32551269-385128ba-c490-11e7-8127-d65516895516.jpg)

**Comment by paula-w** [comment]
Please record a gif on the gitdeveloper version how to trigger this error. I just checked it and didn't notice the error.
