### ISSUE TITLE
instalacja na nazwa pl

### ISSUE THREAD

**Issue by tomexsystem** [YetiForceCompany/YetiForceCRM#5486]
Witam serdecznie podczas instalacji na nazwie.pl Yetiforce wersji 4.2.0 mam 2 błedy
Warning: PDO::query(): MySQL server has gone away in /home/tomexsystem/ftp/yeti/include/database/PearDatabase.php on line 301

	public function query($query, $dieOnError = false, $msg = '')
	{
		$this->stmt = false;
		$sqlStartTime = microtime(true);

		try {
			\App\Log::beginProfile($query, __METHOD__);
			$this->stmt = $this->database->query($query);

Fatal error: Call to a member function rowCount() on boolean in /home/tomexsystem/ftp/yeti/include/database/PearDatabase.php on line 452
w pliku w lini 452 śa takie wpisy
	public function update($table, array $columns, $where = false, array $params = [])
	{
		$query = "UPDATE $table SET ";
		foreach ($columns as $column => $value) {
			$query .= $this->quote($column, false) . ' = ?,';
			$values[] = $value;
		}
		$query = trim($query, ',');
		if ($where !== false) {
			$query .= sprintf(' WHERE %s', $where);
		}
		$this->pquery(trim($query, ','), [array_merge($values, $params)]);
		return $this->stmt->rowCount();

po uruchomieniu yeti mam taki bład 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tomexsystem_yeti.s_yf_companies' doesn't exist Failed to prepare SQL: SELECT * FROM `s_yf_companies` WHERE `default`=:qp0

**Comment by mariuszkrzaczkowski** [comment]
Problem jest w konfiguracji serwera, duplikat: https://github.com/YetiForceCompany/YetiForceCRM/issues/2879
