### ISSUE TITLE
How do you get reports of users activities?

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5487]
HI,
Just wanted to know how you get reports of users activites to monitor staff usage?

**Comment by alextovey** [comment]
Sorry using 4.2 on ubuntu 16.04 with php 7.0 along, server has 6gb ram and 4 cores of virtual processor. 

Not sure why I cant run a report i just get a white screen. So not sure if i'm doing it correctly. any help would be great. Thank you.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/analyzer
