### ISSUE TITLE
Hiding blocks not working as expected

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#5489]
When I apply basic hide block condition and try to edit record, YF coming back to me with:

Error!!!
SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared The SQL being executed was: INSERT INTO `u_yf_browsinghistory` (`userid`, `date`, `title`, `url`) VALUES (5, '2017-11-10 00:01:39', 'Contacts Edit', 'index.php?module=Contacts&view=Edit&record=175')

**Comment by paula-w** [comment]
We hid the “contact information” block when the status is inactive on the gitdeveloper version and it worked. You have to remember that the system will hide or show the block only after you save the changes, so it doesn’t work right away, maybe we will change it in the future. Unfortunately, you didn’t describe how to trigger this error, so if it’s still not working for you please provide us with more details.
