### ISSUE TITLE
Search engine bug 

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5491]
#### Issue

![abcbug](https://user-images.githubusercontent.com/8545791/32656186-dc0b2ba8-c621-11e7-8ffe-b27d08b04f38.gif)

#### Actual Behavior

- Not possible to find product if you input whole first world of product name and with another conditions. Check Gif

#### Your Environment

* YetiForce Version used: dev ver. 4.2.468
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
Too fast. You have to wait until CRON is reloaded. You can also use the search icon on the right.

**Comment by vovpff** [comment]
@bpabiszczak Record was paused to 5-10 minutes before starting GRN creation 

P.S. searching through popup takes a lot of time.

**Comment by paula-w** [comment]
5- 10 minutes is still too short, because cron in the gitdeveloper version is set to 15 minutes, so try again and wait around 20 minutes. 
We will optimize the search speed in the future.

**Comment by vovpff** [comment]
@paula-w thanks for information about cron time in gitdev.

What you think about I can't find `abc` typing `abc` but can find `abc def` typing `def`? Looks like labels already up to date.
