### ISSUE TITLE
OSSMail issue.

### ISSUE THREAD

**Issue by salimcmd** [YetiForceCompany/YetiForceCRM#5492]
I have recently installed YetiForce  (4.2.460), But when i go to Virtual desk -> My Mail Box, it says 'Incorrect request, LBL_NOT_ACCESSIBLE' , I have installed lib_roundcube. But it wasn't populated in web_root/modules/OSSMail/roundcube folder, instead it was there  web_root/public_html/modules/OSSMail/roundcube, So i copied it to web_root/modules/OSSMail/. 
Still it says the error. What am i doing wrong?. Is there anything i  am missing..

My Server environment 
Ubuntu 16.4
PHP 7.0.22

![yt-error](https://user-images.githubusercontent.com/8142647/32656811-5f2d4450-c639-11e7-95e8-5919bcee864c.png)

**Comment by paula-w** [comment]
We recommend installing the stable version for testing mail because the for the developer version you installed you would need to change the Roundcube configuration.
