### ISSUE TITLE
cant seem login to roundcube, and no errors given

### ISSUE THREAD

**Issue by shaded2** [YetiForceCompany/YetiForceCRM#5498]
Before you create a new issue, please check out our [manual] (https://yetiforce.com/en/github/issues/126-issues.html)
fyi- this page is 404

#### Issue

I try to login to roundcube, but i just says loading for several seconds then there is no error. 

#### Actual Behavior

cant login, no error message

#### Expected Behavior

i would like to be logged in to roundcube

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: chrome
* Environment name and version: chrome
* Operating System and version: chrome os

**Comment by paula-w** [comment]
Unfortunately, we can’t help you without seeing your logs. The description of how to enable logs can be found here: https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging.
Might turn out that we will also need the mail server logs. We can only help you solve this issue when we find the error in your logs.
Thanks a lot for reporting the wrong link to the manual!
