### ISSUE TITLE
Can't change role of user.

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#5501]
after change user's role can't change it again.
i try by demo user in developer.yetiforce.com.

![bug2](https://user-images.githubusercontent.com/18072100/32719815-d9a8442a-c876-11e7-9887-e14c8710e56d.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/49e391c0bd096131db8202c6c24fb86329f10ca4
