### ISSUE TITLE
[BUG] Unable to upload avatar v4.2.487

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5504]
Unable to upload avatar v4.2.487
![bug avatar](https://user-images.githubusercontent.com/19627226/32735249-cceec470-c8c6-11e7-9aac-4e95baaf5fc8.gif)

**Comment by bpabiszczak** [comment]
It worked for me [check the image below], we might have fixed that issue together with a different one, or it depends on the file and/or configuration. Test different files on the gitdeveloper version and let us know if you find anything else.

![image](https://user-images.githubusercontent.com/10197525/32768078-86de3ad8-c916-11e7-901e-8dd8c5d29392.png)
