### ISSUE TITLE
[Question] Search Opportunities from Roundcube

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#5505]
#### Issue

Hello, How can I please to add more columns to search in the bar action of Roundcube, for example when I try to bind an email with an opportunity, I look  for an existing opportunity but I'm only able to see the Subject and Assigned User. I would like to see also the Account related to the opportunity

![image](https://user-images.githubusercontent.com/20831164/32763656-f600662c-c8ce-11e7-8537-ec26e700d4b5.png)

I have tried to add label on the search module without effect.

![image](https://user-images.githubusercontent.com/20831164/32763695-3652cc60-c8cf-11e7-8a32-fcd0391d921e.png)

#### Actual Behavior
NOt possibility to add columns in the search window module of Roundcube

#### Expected Behavior
To be able of look for ooportunities by subject and account on Roundcube

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.2-0
* Browser name and version:chrome/firefox
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
It can be configured like on the picture below. If it doesn’t work then you have to change it in the module file whose values are default for the popup window.

![image](https://user-images.githubusercontent.com/10197525/32767875-9fd737ac-c915-11e7-839a-d196f27237dd.png)
