### ISSUE TITLE
[BUG] Import records

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5508]
v4.2.506
Tested on https://gitdeveloper.yetiforce.com
![bug import](https://user-images.githubusercontent.com/19627226/32786216-eccd6912-c985-11e7-914e-11f068ade095.gif)

**Comment by mjapple** [comment]
How we can see the solution for this bug?

**Comment by thesxw** [comment]
made a sql insert to some tables the mysql ;)
for example:
Products
crmentity
products
productcf
product currency something ;)
and same for other records (i fix it like this for now)
later i will try to fix it myself

**Comment by mjapple** [comment]
When I do intend to do import i see white screen, and i see two errors in the cache > logs > phpError.log 
19-Nov-2017 06:44:29 Asia/Muscat] PHP Warning:  require_once(include/Webservices/VtigerModuleOperation.php): failed to open stream: No such file or directory in /home1/CRM_ROOT/include/Webservices/Utils.php on line 384
[19-Nov-2017 06:44:29 XXXXXX] PHP Fatal error:  require_once(): Failed opening required 'include/Webservices/VtigerModuleOperation.php' (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home1/CRM_ROOT/include/Webservices/Utils.php on line 384

**Comment by mariuszkrzaczkowski** [comment]
Duplicate #5473
