### ISSUE TITLE
[BUG][menu][4.2.511] error to load submenu from "My mailbox"

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#5512]
#### How to trigger the error

1.
![errormenu_2017-11-15_10-25-25](https://user-images.githubusercontent.com/18419851/32831369-ff11259a-c9ef-11e7-94f8-1a8af323b990.gif)

#### Your Environment

* YetiForce Version used: 4.2.511
* Browser name and version: Chrome x64 62.0
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: gitdeveloper.yetiforce.com

**Comment by WalterLuis** [comment]
#5512 Duplicated

**Comment by SkavenKF** [comment]
@WalterLuis i should close my ticket. please can you reopen yours 😏

**Comment by WalterLuis** [comment]
he got ahead of me xD
thanks C:

**Comment by thesxw** [comment]
Try to find file access to all files should be 755 as i think to work properly

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
