### ISSUE TITLE
[minor BUG][4.2.512][MappedFields] Fatal error in step2 from "Mapping"

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#5513]
#### How to trigger the error

1.
![mapping_2017-11-15_11-48-03](https://user-images.githubusercontent.com/18419851/32834713-78630890-c9fb-11e7-950a-24e62add70d4.gif)

#### Your Environment

* YetiForce Version used: 4.2.512
* Browser name and version: Chrome x64 62.0
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: gitdeveloper.yetiforce.com

**Comment by thesxw** [comment]
almost same problem here but page wont load

**Comment by WalterLuis** [comment]
#5537 Duplicated

**Comment by thesxw** [comment]
@WalterLuis but it still dont work so ... it will be somethink like reminder xD

**Comment by thesxw** [comment]
![image](https://user-images.githubusercontent.com/33422088/33067688-3dafd30a-ceaf-11e7-943b-b015a3ff7d65.png)
this is whats showing up maybe someone will help me ?

**Comment by WalterLuis** [comment]
@thesxw 
I did not close the incident because it was solved, I closed it because another person created the same incidence after mine and so that there were no duplicates I closed mine and linked it to the other. #5537
