### ISSUE TITLE
[BUG][4.2.513] Error from "System setting" using view="List"

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#5514]
#### Issue

From the web "gitdeveloper.yetiforce.com" I do not get any error but, if I download and install it from the git repository, I get the following error in the "System setting" section using the list view, as you can see on the following images

#### Actual Behavior

![error_automaticassignment_2017-11-15_12-58-49](https://user-images.githubusercontent.com/18419851/32839288-e2fe17c0-ca0b-11e7-9781-04266e72b696.png)
![error_crontasks_2017-11-15_13-32-53](https://user-images.githubusercontent.com/18419851/32839290-e323a738-ca0b-11e7-9524-cf9177c29743.png)
![error_loginhistory_2017-11-15_13-25-34](https://user-images.githubusercontent.com/18419851/32839291-e3536608-ca0b-11e7-8131-e17c867c3093.png)
![error_mail_2017-11-15_13-34-40](https://user-images.githubusercontent.com/18419851/32839293-e37d1098-ca0b-11e7-902f-34058c48991a.png)
![error_treesmanager_2017-11-15_13-02-15](https://user-images.githubusercontent.com/18419851/32839295-e3a1269a-ca0b-11e7-8444-ea8b4ced1bd4.png)
![error_webserviceusers_2017-11-15_13-29-22](https://user-images.githubusercontent.com/18419851/32839297-e3ef8240-ca0b-11e7-897e-61cc95279326.png)
![error_workflows_2017-11-15_13-32-28](https://user-images.githubusercontent.com/18419851/32839299-e41775f2-ca0b-11e7-82ac-04ba32a6742b.png)

#### How to trigger the error

1.

#### Your Environment

* YetiForce Version used: 4.2.513
* Browser name and version: Chrome 62.0 x64
* Environment name and version 1: WampServer => php7.1.9 apache 2.4.27
* Environment name and version 2: CentOS 7 => php7.1.11 apache 2.4.6
* Operating System and version: windows 10 x64

**Comment by ezbank** [comment]
Same as me. :((

**Comment by ezbank** [comment]
appears from the version v4.2.505
