### ISSUE TITLE
How i can change this list?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5515]
#### Issue
I want to change this list items for a related field view.
![request](https://user-images.githubusercontent.com/30116021/32857830-e5dad118-ca51-11e7-8356-1e2017e866c9.png)

How can i do this?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@cltvchannel it is possible to change only manually in \modules\Accounts\Accounts.php file lines from 52 to 59
