### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by drag0nhunter123** [YetiForceCompany/YetiForceCRM#5516]
#### Issue
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@website.dragondesigner.org to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

#### Your Environment
* YetiForce Version used: 4.2.0
* Browser name and version:  Chrome
* Link: http://website.dragondesigner.org/

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/apache-500-internal-server-error-3

**Comment by drag0nhunter123** [comment]
i tried all this
