### ISSUE TITLE
SetEnv

### ISSUE THREAD

**Issue by drag0nhunter123** [YetiForceCompany/YetiForceCRM#5517]
#### Issue
Invalid command 'SetEnv', perhaps misspelled or defined by a module not included in the server configuration,
#### Your Environment
* YetiForce Version used: 4.20
* Browser name and version: Chrome

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/4858
