### ISSUE TITLE
PDF creating error on step 1

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5519]
#### Issue
I have used this fix: https://github.com/YetiForceCompany/YetiForceCRM/commit/2037c0c104fa1cbbb706bde8ce34baf390d36a82    and now when i change the file edit.php   https://github.com/YetiForceCompany/YetiForceCRM/blob/2037c0c104fa1cbbb706bde8ce34baf390d36a82/modules/Settings/PDF/views/Edit.php   i can't show fields.

![isuee](https://user-images.githubusercontent.com/30116021/32900643-9ec00064-caf6-11e7-9b1a-c65608dbeabe.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@cltvchannel roll back to backup or try to check you actions more carefully

**Comment by cltvchannel** [comment]
I was very carefully, but that fix is not working.

**Comment by vovpff** [comment]
@cltvchannel I think you must implement all fixes before this one to achieve good result. This is crazy idea. Just wait for new version.

**Comment by mariuszkrzaczkowski** [comment]
can not upload one change, try to upload update package
