### ISSUE TITLE
[minor BUG][Colors][4.2.514] The colors of the picklist do not appear

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#5521]
#### Issue

Maybe I needed to activate something else so that the colors appeared?

#### How to trigger the error

1.
![picklist](https://user-images.githubusercontent.com/18419851/32913982-eaf40664-cb0b-11e7-8fc5-f649463a5036.gif)

#### Your Environment

* YetiForce Version used: 4.2.514
* Browser name and version: Chrome 62.0 x64
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: gitdeveloper.yetiforce.com

**Comment by ezbank** [comment]
I think it's not really ready to work

**Comment by WalterLuis** [comment]
#5533 Duplicated

**Comment by acoolov** [comment]
I am having the same issue in 5.2.0 version.
I choose colors for my drop down menu, but the colors don't appear in the detail view.
How is this closed when there is no solution proposed?

**Comment by vovpff** [comment]
I can confirm too. This bug every time happens after update/upgrade. To turn colors back you need manually change one color per every colored picklist

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/UpdatePackages/commit/7270d6318288577cddde562f671c6da519486407
