### ISSUE TITLE
Wrong day on "Quick create" calendar

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#5522]
#### Issue

When i want to create an event or to do, the calendar view on quick create show wrong days on the dates. But it doesn't occur on the calendar view module.

![image](https://user-images.githubusercontent.com/20831164/32927468-b308f890-cb1a-11e7-9d65-2d3bc9d5686e.png)
the picture show 12-21-2017 as Wednesday. But it actually is Thusrday.

On Calendar preview December 21th is Thursday as expected
![image](https://user-images.githubusercontent.com/20831164/32927506-f5bfd91a-cb1a-11e7-93dc-40d5c6f0c13c.png)

#### Actual Behavior
Wrong day on quick create calendar

#### Expected Behavior

Correct day on the calendar in quick create preview

#### How to trigger the error

1.Create an activity by quick create
2.
3.

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version:Firefox / chrome
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
Working ok on dev version
