### ISSUE TITLE
Backup YetiForce

### ISSUE THREAD

**Issue by Varico** [YetiForceCompany/YetiForceCRM#5524]
Hi i have a question. How can i make YetiForce backup modules (Accounts and Assets). Normal Export of rekords dont work, because i have to many rekord.

**Comment by PercyP** [comment]
Hi,

can you not use your cpanel backup process? Backup your yetifirce crm folder and backup the database?

**Comment by bpabiszczak** [comment]
@Varico należy użyć narzędzi wbudowanych w system operacyjny lub panel w systemie operacyjnym. Narzędzia które kiedyś mieliśmy działały za wolno... nie ma nic lepszego niż narzędzia wbudowane w wirtualizacje lub na poziomie systemu operacyjnego.
