### ISSUE TITLE
Error Export Accounts XML [4.2.0]

### ISSUE THREAD

**Issue by JhonMaca** [YetiForceCompany/YetiForceCRM#5525]
#### Issue

I want to import the data of my accounts to the new version of the CRM, the process of exporting the data in CSV or XML format works well. The problem happens when I try to import more than one account at a time in the XML format, if I perform the same procedure with full CSV format the import process without problem. Perform tests importing from a single account and for both formats work well.

#### Actual Behavior

Error SQLSTATE [42S01]
#### Expected Behavior

To be able to import the data from my accounts without errors in the XML format

#### How to trigger the error

1. Export without problem
![export account xml](https://user-images.githubusercontent.com/32772474/32905977-9c33ac74-cac9-11e7-8ae2-3224a239a20b.gif)
2.  I import a single account in CSV and XML format without problem, but when I import more than two accounts in XML format the error appears
![import account xml error](https://user-images.githubusercontent.com/32772474/32906182-2565a52e-caca-11e7-8d68-acbf652eed92.gif)

the SQL error is the following 

>Error!!!
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'u_yf_import_5' already exists The SQL being executed was: CREATE TABLE `u_yf_import_5` ( `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, `temp_status` smallint(1) DEFAULT 0, `recordid` int(11), `accountname` varchar(100), `industry` varchar(200), `sucursal` varchar(15), `vat_id` varchar(30), `digitverif` varchar(255), `tipoident` varchar(255), `was_read` smallint(1), `accounttype` varchar(200), `active` smallint(1), `assigned_user_id` varchar(255), `private` smallint(1), `shownerid` varchar(255), `account_id` varchar(255), `emailcta` varchar(100), `accounts_status` varchar(255), `telefonoppal` varchar(30), `telefonosec` varchar(30), `nombrecomer` varchar(35), `pdpersonales` smallint(1), `trataid` varchar(20), `tratamiento` varchar(255), `email1` varchar(100), `nombres` varchar(20), `email2` varchar(100), `apellidos` varchar(20), `website` varchar(100), `genero` varchar(255), `emailoptout` smallint(1), `phone` varchar(30), `no_approval` smallint(1), `otherphone` varchar(30), `verification` text, `cargo` varchar(20), `otrocontacto` varchar(20), `autsuscemail` smallint(1), `gestion` varchar(100), `nombreisiigo` varchar(50), `nombresiigo` varchar(50), `cantv1` varchar(100), `cantv2` varchar(100), `cantv3` varchar(100), `emailsusc` varchar(100), `replegautcol` smallint(1), `balance` decimal(25,8), `sum_time` decimal(10,2), `payment_balance` decimal(25,8), `inventorybalance` decimal(25,8), `discount` decimal(5,2), `creditlimit` int(10), `last_invoice_date` date, `isconvertedfromlead` smallint(3), `created_user_id` smallint(5), `employees` int(10), `products` text, `services` text, `ownership` varchar(50), `annual_revenue` decimal(25,8), `registration_number_2` varchar(30), `siccode` varchar(50), `registration_number_1` varchar(30), `legal_form` varchar(255), `direccionsiigo` varchar(20), `localnumbera` varchar(100), `direccionisiigo` varchar(20), `addresslevel7a` varchar(255), `buildingnumbera` varchar(100), `addresslevel5a` varchar(255), `addresslevel8a` varchar(255), `addresslevel3a` varchar(255), `addresslevel6a` varchar(255), `addresslevel1a` varchar(255), `addresslevel4a` varchar(255), `poboxa` varchar(50), `addresslevel2a` varchar(255), `buildingnumberb` varchar(100), `localnumberb` varchar(100), `addresslevel8b` varchar(255), `addresslevel7b` varchar(255), `addresslevel6b` varchar(255), `addresslevel5b` varchar(255), `addresslevel4b` varchar(255), `addresslevel3b` varchar(255), `addresslevel2b` varchar(255), `addresslevel1b` varchar(255), `poboxb` varchar(50), `buildingnumberc` varchar(100), `localnumberc` varchar(100), `addresslevel8c` varchar(255), `addresslevel7c` varchar(255), `addresslevel6c` varchar(255), `addresslevel5c` varchar(255), `addresslevel4c` varchar(255), `addresslevel3c` varchar(255), `addresslevel2c` varchar(255), `addresslevel1c` varchar(255), `poboxc` varchar(50), `description` text, `attention` text ) CHARACTER SET utf8 ENGINE=InnoDB

3.

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Google Chrome Versión 62.0.3202.94 (Build oficial) (32 bits)
* Environment name and version: Apache/2.4.18 (Ubuntu) /Version of PHP: 5.6.30-10+deb.sury.org~xenial+2
* Operating System and version: Windows 10 PRO Version 1703, Compilation of the operating system 15063.726

**Comment by mariuszkrzaczkowski** [comment]
Duplicate #5473
