### ISSUE TITLE
[4.3] charts on the home page don't work

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#5527]
#### Issue

I have configured the chart in 'Reports':
![yf1](https://user-images.githubusercontent.com/29442233/32983951-4cb7c862-cc9d-11e7-8a60-6dff9f9da3f8.PNG)

When I want to see that chart on the home page, there is a blank space:
![yf2](https://user-images.githubusercontent.com/29442233/32983971-7bcde30c-cc9d-11e7-8374-3c06e9f6aeae.PNG)

Of course I have rebuilded all widgets in Software configuration > Standard modules > Modules – Widgets.

Thanks in advance for your help.

#### Your Environment

* YetiForce Version used: 4.3

**Comment by mariuszkrzaczkowski** [comment]
You need to show you how to create a widget and which has the configuration
![2017-11-28_22-24-39](https://user-images.githubusercontent.com/10198654/33344972-fed0eaa2-d48a-11e7-8a51-b73fc2161511.png)
