### ISSUE TITLE
Adding product to invoice v.4.2.514

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5531]
#### Issue
Adding product to invoice not adding unit price. 4.2.514 and gitdev. Well it's firefox problem, working on others.
![price](https://user-images.githubusercontent.com/10330264/32989325-b24fd046-cd1c-11e7-87bc-168637b19c00.gif)

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.

**Comment by areksolek** [comment]
![invoicee](https://user-images.githubusercontent.com/25615135/34299714-bdeb3996-e724-11e7-92b9-2c4d9c5cfc7b.gif)
