### ISSUE TITLE
Multi image no longer working and freezes the screen if clicked in 4.3

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5535]
Hi,
I am testing version 4.3 upgrade. I have multi image installed and since upgrading the images no longer display - just the general no image icon (see attached screenshots). This is the same in record summary and details.

If I click on the image icon the screen freezes - same happens if I try to delete the image. 

I went to yetiforce/modules/Settings/LayoutEditor/models/module.php and enabled the MultiImage here:

`public function getAddSupportedFieldTypes()
	{
		return [
			'Text', 'Decimal', 'Integer', 'Percent', 'Currency', 'Date', 'Email', 'Phone', 'Picklist', 'URL', 'Checkbox', 'TextArea', 'MultiSelectCombo', 'Skype', 'Time', 'Related1M', 'Editor', 'Tree', 'MultiReferenceValue', 'CategoryMultipicklist', 'MultiImage'`

![noimage2](https://user-images.githubusercontent.com/10598886/33009907-44b4427e-cdd0-11e7-81f6-1951af2b3721.png)

![noimage](https://user-images.githubusercontent.com/10598886/33009901-3efc0e84-cdd0-11e7-9b96-283718121905.png)

**Comment by KatarzynaUlichnowska** [comment]
As far as I remember, it is only you who uses this mechanism [probably no one else knows about it because it is disabled by default]. It requires to be rebuilt and secured. I don't know if this field will work in 4.3 - maybe we will fix it later. 
Because you are our customer, we will do our best to rewrite this field so it will comply with the current standards. Normally we would get rid of it, because no one else uses it (except you) and it requires a lot of work from us.

**Comment by PercyP** [comment]
@KatarzynaUlichnowska 

a few people appear to be using it - there are some old threads on here regarding it. When it was created your team said it would be for integrating into the main system. It is a really good idea and sure if others know about it they would use it? 

Some custom work your team is doing for me right now requires this for it to work. Will it work for me once the custom work is completed as otherwise it will be unusable?

**Comment by waran70** [comment]
A lot of work? Can you break this work down? :-)
Jesus Christ... guys... please don't threat us as a bunch of idiots...

**Comment by bpabiszczak** [comment]
@PercyP it is already on the our testing server and soon we will upload it to GitDeveloper.

@waran70 Christmas was bad? Or did you have a bad day? If we write that something takes a lot of time, it is true. You can always prove that I'm wrong and fix the entire mechanism and secure it and then video it to show us how much time it took you.

**Comment by PercyP** [comment]
@bpabiszczak 
I just seen it on my custom work and it is looking great - thank you! Sure many users will find this really useful depending on the industry they are in :O)

**Comment by bpabiszczak** [comment]
Unfortunately, this mechanism will not work in 4.3.0 because it needs to be completely rewritten. All changes that we did for you, work on your version of the system and if they will be ok, we will upload it to your version of the system without the update to 4.3.0.

**Comment by PercyP** [comment]
Does that mean I will not be able to update to 4.3? I need to move to 4.3 as it irons out lots of issues I was having on 4.2

**Comment by bpabiszczak** [comment]
Certainly, you won't be able to update straight away. In 4.3 this loading doesn't work at all, if I remember correctly it was partly deleted from the system because of security reasons and now it requires rewriting [it may take 2-3 working days] and because we do it for free, it will have to wait until we have a spare moment. Answering your question, you will be able to migrate to a new version but it would be best to do when we add a missing mechanism, which will be in 4.4 version.

**Comment by PercyP** [comment]
@bpabiszczak 
thanks for your reply. Most appreciated. I understand. I will leave updating until version 4.4 - its worth waiting for.

**Comment by bpabiszczak** [comment]
We created from scratch a field that allows you to add images. Please test the new functionality on the gitdeveloper version and send us some feedback, if there’s anything missing we’ll do our best to add it

**Comment by PercyP** [comment]
@bpabiszczak 

I am just testing on gitdeveloper version and added a test multimage field (first in Contacts then in Competition). Then when I go to the add record I get an error message as follows:

Error!!!
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gitdevelop_crm.u_yf_attachments' doesn't exist Failed to prepare SQL: SELECT * FROM `u_yf_attachments` WHERE `attachmentid`=:qp0

Followed by this:

#0 vendor/yetiforce/yii2/db/Command.php(1143): yii\db\Command->prepare(true)
#1 vendor/yetiforce/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#2 vendor/yetiforce/yii2/db/Query.php(237): yii\db\Command->queryAll()
#3 modules/Vtiger/uitypes/MultiImage.php(122): yii\db\Query->all()
#4 modules/Vtiger/models/Field.php(1078): Vtiger_MultiImage_UIType->getEditViewDisplayValue(NULL, Object(Vtiger_Record_Model))
#5 cache/templates_c/basic/426c3bdb2fb19db7e24e6c592595c19c60468f0c_0.file.MultiImage.tpl.php(28): Vtiger_Field_Model->getEditViewDisplayValue(NULL, Object(Vtiger_Record_Model))
#6 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_5abcc60159a540_39710729(Object(Smarty_Internal_Template))
#7 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(172): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#8 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(206): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#9 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(372): Smarty_Internal_Template->render()
#10 cache/templates_c/basic/84d302f6d4d7f0fc9b8826453fe71dae28657e7a_0.file.EditViewBlocks.tpl.php(116): Smarty_Internal_Template->_subTemplateRender('modules/Vtiger/...', NULL, NULL, 0, 3600, Array, 0, true)
#11 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_5abcc5ca4f1a00_16484873(Object(Smarty_Internal_Template))
#12 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(172): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#13 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(206): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#14 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(372): Smarty_Internal_Template->render()
#15 cache/templates_c/basic/6e283430ebda4cbd082133c7ca3690d007fa7b5a_0.file.EditView.tpl.php(26): Smarty_Internal_Template->_subTemplateRender('modules/Vtiger/...', NULL, NULL, 0, 3600, Array, 0, true)
#16 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_5abcc5ca45c0a0_32248514(Object(Smarty_Internal_Template))
#17 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(172): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#18 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(206): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#19 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(216): Smarty_Internal_Template->render(false, 1)
#20 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(122): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)
#21 include/runtime/Viewer.php(207): Smarty_Internal_TemplateBase->display('modules/Vtiger/...')
#22 modules/Vtiger/views/Edit.php(144): Vtiger_Viewer->view('EditView.tpl', 'Competition')
#23 include/main/WebUI.php(182): Vtiger_Edit_View->process(Object(App\Request))
#24 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#25 public_html/index.php(11): require('/home/gitdevelo...')
#26 {main}
#0 [trace] Entering getColumnFields(Competition) method ...
#1 [trace] Exiting getColumnFields method ...
#2 [trace] Start DateTimeField::__convertToUserFormat a:1:{i:0;s:9:"2018-3-29";} | yyyy-mm-dd
#3 [trace] End DateTimeField::__convertToUserFormat
#4 [info] SELECT * FROM `u_yf_browsinghistory` WHERE `userid`=5 ORDER BY `id` DESC LIMIT 20 || yii\db\Command::query
#5 [info] Opening DB connection: mysql:host=localhost;dbname=gitdevelop_crm;port=3306 || yii\db\Connection::open
#6 [trace] Start DateTimeField::convertToUserTimeZone(today) method ...
#7 [trace] Start DateTimeField::convertTimeZone(today, Europe/Warsaw, Europe/Warsaw)
#8 [trace] End DateTimeField::convertTimeZone
#9 [trace] End DateTimeField::convertToUserTimeZone
#10 [trace] Start DateTimeField::convertToUserTimeZone(yesterday) method ...
#11 [trace] Start DateTimeField::convertTimeZone(yesterday, Europe/Warsaw, Europe/Warsaw)
#12 [trace] End DateTimeField::convertTimeZone
#13 [trace] End DateTimeField::convertToUserTimeZone
#14 [info] SELECT * FROM `u_yf_chat_messages` LIMIT 20 || yii\db\Command::query
#15 [trace] Entering getColumnFields(Announcements) method ...
#16 [trace] Exiting getColumnFields method ...
#17 [info] SELECT `u_yf_announcement`.`announcementid` AS `id`, `u_yf_announcement`.`subject` AS `subject`, `vtiger_crmentity`.`description` AS `description`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `u_yf_announcement`.`is_mandatory` AS `is_mandatory` FROM `u_yf_announcement` INNER JOIN `vtiger_crmentity` ON u_yf_announcement.announcementid = vtiger_crmentity.crmid WHERE (`vtiger_crmentity`.`deleted`=0) AND (`announcementstatus`='PLL_PUBLISHED') || yii\db\Command::query
#18 [trace] Entering isPermitted(Notification,DetailView,,) method ...
#19 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#20 [info] SELECT DISTINCT `vtiger_tab`.* FROM `vtiger_field` INNER JOIN `vtiger_tab` ON vtiger_tab.tabid = vtiger_field.tabid WHERE ((quickcreate = 0) OR (quickcreate = 2)) AND (`vtiger_tab`.`presence` <> 1) AND (`vtiger_tab`.`type` <> 1) AND (`vtiger_tab`.`name` NOT IN ('ModComments', 'PriceBooks', 'Events')) || yii\db\Command::query
#21 [trace] Entering isPermitted(Accounts,CreateView,,) method ...
#22 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#23 [trace] Entering isPermitted(Leads,CreateView,,) method ...
#24 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#25 [trace] Entering isPermitted(Contacts,CreateView,,) method ...
#26 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#27 [trace] Entering isPermitted(Campaigns,CreateView,,) method ...
#28 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#29 [trace] Entering isPermitted(HelpDesk,CreateView,,) method ...
#30 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#31 [trace] Entering isPermitted(Products,CreateView,,) method ...
#32 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#33 [trace] Entering isPermitted(Documents,CreateView,,) method ...
#34 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#35 [trace] Entering isPermitted(Calendar,CreateView,,) method ...
#36 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#37 [trace] Entering isPermitted(Vendors,CreateView,,) method ...
#38 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#39 [trace] Entering isPermitted(ServiceContracts,CreateView,,) method ...
#40 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#41 [trace] Entering isPermitted(Services,CreateView,,) method ...
#42 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#43 [trace] Entering isPermitted(Assets,CreateView,,) method ...
#44 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#45 [trace] Entering isPermitted(ProjectMilestone,CreateView,,) method ...
#46 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#47 [trace] Entering isPermitted(ProjectTask,CreateView,,) method ...
#48 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#49 [trace] Entering isPermitted(Project,CreateView,,) method ...
#50 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#51 [trace] Entering isPermitted(OSSTimeControl,CreateView,,) method ...
#52 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#53 [trace] Entering isPermitted(OutsourcedProducts,CreateView,,) method ...
#54 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#55 [trace] Entering isPermitted(OSSPasswords,CreateView,,) method ...
#56 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#57 [trace] Entering isPermitted(OSSEmployees,CreateView,,) method ...
#58 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#59 [trace] Entering isPermitted(PaymentsIn,CreateView,,) method ...
#60 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#61 [trace] Entering isPermitted(PaymentsOut,CreateView,,) method ...
#62 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#63 [trace] Entering isPermitted(Reservations,CreateView,,) method ...
#64 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#65 [trace] Entering isPermitted(OSSOutsourcedServices,CreateView,,) method ...
#66 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#67 [trace] Entering isPermitted(OSSSoldServices,CreateView,,) method ...
#68 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#69 [trace] Entering isPermitted(HolidaysEntitlement,CreateView,,) method ...
#70 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#71 [trace] Entering isPermitted(LettersIn,CreateView,,) method ...
#72 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#73 [trace] Entering isPermitted(LettersOut,CreateView,,) method ...
#74 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#75 [trace] Entering isPermitted(Announcements,CreateView,,) method ...
#76 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#77 [trace] Entering isPermitted(SSalesProcesses,CreateView,,) method ...
#78 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#79 [trace] Entering isPermitted(KnowledgeBase,CreateView,,) method ...
#80 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#81 [trace] Entering isPermitted(IStorages,CreateView,,) method ...
#82 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#83 [trace] Entering isPermitted(ISTN,CreateView,,) method ...
#84 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#85 [trace] Entering isPermitted(Notification,CreateView,,) method ...
#86 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#87 [info] SELECT `name`, `value` FROM `yetiforce_mail_config` WHERE `type`='mailIcon' || yii\db\Command::query
#88 [trace] Entering isPermitted(OSSMail,,,) method ...
#89 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#90 [info] SELECT `rcuser_id`, `crmuser_id`, `username`, `password` FROM `roundcube_users_autologin` INNER JOIN `roundcube_users` ON roundcube_users_autologin.rcuser_id = roundcube_users.user_id WHERE `roundcube_users_autologin`.`crmuser_id`=5 || yii\db\Command::query
#91 [trace] Entering isPermitted(Accounts,CreateView,,) method ...
#92 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#93 [trace] Entering isPermitted(Leads,CreateView,,) method ...
#94 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#95 [trace] Entering isPermitted(Contacts,CreateView,,) method ...
#96 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#97 [trace] Entering isPermitted(Campaigns,CreateView,,) method ...
#98 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#99 [trace] Entering isPermitted(HelpDesk,CreateView,,) method ...
#100 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#101 [trace] Entering isPermitted(Products,CreateView,,) method ...
#102 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#103 [trace] Entering isPermitted(Documents,CreateView,,) method ...
#104 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#105 [trace] Entering isPermitted(Calendar,CreateView,,) method ...
#106 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#107 [trace] Entering isPermitted(Vendors,CreateView,,) method ...
#108 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#109 [trace] Entering isPermitted(ServiceContracts,CreateView,,) method ...
#110 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#111 [trace] Entering isPermitted(Services,CreateView,,) method ...
#112 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#113 [trace] Entering isPermitted(Assets,CreateView,,) method ...
#114 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#115 [trace] Entering isPermitted(ProjectMilestone,CreateView,,) method ...
#116 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#117 [trace] Entering isPermitted(ProjectTask,CreateView,,) method ...
#118 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#119 [trace] Entering isPermitted(Project,CreateView,,) method ...
#120 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#121 [trace] Entering isPermitted(OSSTimeControl,CreateView,,) method ...
#122 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#123 [trace] Entering isPermitted(OutsourcedProducts,CreateView,,) method ...
#124 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#125 [trace] Entering isPermitted(OSSPasswords,CreateView,,) method ...
#126 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#127 [trace] Entering isPermitted(OSSEmployees,CreateView,,) method ...
#128 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#129 [trace] Entering isPermitted(PaymentsIn,CreateView,,) method ...
#130 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#131 [trace] Entering isPermitted(PaymentsOut,CreateView,,) method ...
#132 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#133 [trace] Entering isPermitted(Reservations,CreateView,,) method ...
#134 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#135 [trace] Entering isPermitted(OSSOutsourcedServices,CreateView,,) method ...
#136 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#137 [trace] Entering isPermitted(OSSSoldServices,CreateView,,) method ...
#138 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#139 [trace] Entering isPermitted(HolidaysEntitlement,CreateView,,) method ...
#140 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#141 [trace] Entering isPermitted(LettersIn,CreateView,,) method ...
#142 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#143 [trace] Entering isPermitted(LettersOut,CreateView,,) method ...
#144 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#145 [trace] Entering isPermitted(Announcements,CreateView,,) method ...
#146 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#147 [trace] Entering isPermitted(SSalesProcesses,CreateView,,) method ...
#148 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#149 [trace] Entering isPermitted(KnowledgeBase,CreateView,,) method ...
#150 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#151 [trace] Entering isPermitted(IStorages,CreateView,,) method ...
#152 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#153 [trace] Entering isPermitted(ISTN,CreateView,,) method ...
#154 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#155 [trace] Entering isPermitted(Notification,CreateView,,) method ...
#156 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#157 [trace] Entering isPermitted(Notification,DetailView,,) method ...
#158 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#159 [info] SELECT * FROM `vtiger_blocks` WHERE `tabid`=93 ORDER BY `sequence` || yii\db\Command::query
#160 [trace] Entering App\Field::getFieldPermission: 93,subject
#161 [trace] Entering App\Field::getFieldsPermissions: 93
#162 [trace] Entering App\Field::getFieldPermission: 93,subject
#163 [trace] Entering App\Field::getFieldsPermissions: 93
#164 [trace] Entering App\Field::getFieldPermission: 93,vat_id
#165 [trace] Entering App\Field::getFieldsPermissions: 93
#166 [trace] Entering App\Field::getFieldPermission: 93,vat_id
#167 [trace] Entering App\Field::getFieldsPermissions: 93
#168 [trace] Entering App\Field::getFieldPermission: 93,assigned_user_id
#169 [trace] Entering App\Field::getFieldsPermissions: 93
#170 [trace] Entering App\Field::getFieldPermission: 93,assigned_user_id
#171 [trace] Entering App\Field::getFieldsPermissions: 93
#172 [trace] Entering App\Field::getFieldPermission: 93,shownerid
#173 [trace] Entering App\Field::getFieldsPermissions: 93
#174 [trace] Entering App\Field::getFieldPermission: 93,shownerid
#175 [trace] Entering App\Field::getFieldsPermissions: 93
#176 [trace] Entering App\Field::getFieldPermission: 93,email
#177 [trace] Entering App\Field::getFieldsPermissions: 93
#178 [trace] Entering App\Field::getFieldPermission: 93,email
#179 [trace] Entering App\Field::getFieldsPermissions: 93
#180 [trace] Entering App\Field::getFieldPermission: 93,active
#181 [trace] Entering App\Field::getFieldsPermissions: 93
#182 [trace] Entering App\Field::getFieldPermission: 93,active
#183 [trace] Entering App\Field::getFieldsPermissions: 93
#184 [trace] Entering App\Field::getFieldPermission: 93,private
#185 [trace] Entering App\Field::getFieldsPermissions: 93
#186 [trace] Entering App\Field::getFieldPermission: 93,private
#187 [trace] Entering App\Field::getFieldsPermissions: 93
#188 [trace] Entering App\Field::getFieldPermission: 93,testimage
#189 [trace] Entering App\Field::getFieldsPermissions: 93
#190 [trace] Entering App\Field::getFieldPermission: 93,testimage
#191 [trace] Entering App\Field::getFieldsPermissions: 93
#192 [trace] Entering App\Field::getFieldPermission: 93,createdtime
#193 [trace] Entering App\Field::getFieldsPermissions: 93
#194 [trace] Entering App\Field::getFieldPermission: 93,createdtime
#195 [trace] Entering App\Field::getFieldsPermissions: 93
#196 [trace] Entering App\Field::getFieldPermission: 93,competition_no
#197 [trace] Entering App\Field::getFieldsPermissions: 93
#198 [trace] Entering App\Field::getFieldPermission: 93,competition_no
#199 [trace] Entering App\Field::getFieldsPermissions: 93
#200 [trace] Entering App\Field::getFieldPermission: 93,modifiedtime
#201 [trace] Entering App\Field::getFieldsPermissions: 93
#202 [trace] Entering App\Field::getFieldPermission: 93,modifiedtime
#203 [trace] Entering App\Field::getFieldsPermissions: 93
#204 [trace] Entering App\Field::getFieldPermission: 93,closedtime
#205 [trace] Entering App\Field::getFieldsPermissions: 93
#206 [trace] Entering App\Field::getFieldPermission: 93,closedtime
#207 [trace] Entering App\Field::getFieldsPermissions: 93
#208 [trace] Entering App\Field::getFieldPermission: 93,sum_time
#209 [trace] Entering App\Field::getFieldsPermissions: 93
#210 [trace] Entering App\Field::getFieldPermission: 93,sum_time
#211 [trace] Entering App\Field::getFieldsPermissions: 93
#212 [trace] Entering App\Field::getFieldPermission: 93,crmactivity
#213 [trace] Entering App\Field::getFieldsPermissions: 93
#214 [trace] Entering App\Field::getFieldPermission: 93,crmactivity
#215 [trace] Entering App\Field::getFieldsPermissions: 93
#216 [trace] Entering App\Field::getFieldPermission: 93,buildingnumbera
#217 [trace] Entering App\Field::getFieldsPermissions: 93
#218 [trace] Entering App\Field::getFieldPermission: 93,buildingnumbera
#219 [trace] Entering App\Field::getFieldsPermissions: 93
#220 [trace] Entering App\Field::getFieldPermission: 93,localnumbera
#221 [trace] Entering App\Field::getFieldsPermissions: 93
#222 [trace] Entering App\Field::getFieldPermission: 93,localnumbera
#223 [trace] Entering App\Field::getFieldsPermissions: 93
#224 [trace] Entering App\Field::getFieldPermission: 93,addresslevel8a
#225 [trace] Entering App\Field::getFieldsPermissions: 93
#226 [trace] Entering App\Field::getFieldPermission: 93,addresslevel8a
#227 [trace] Entering App\Field::getFieldsPermissions: 93
#228 [trace] Entering App\Field::getFieldPermission: 93,addresslevel7a
#229 [trace] Entering App\Field::getFieldsPermissions: 93
#230 [trace] Entering App\Field::getFieldPermission: 93,addresslevel7a
#231 [trace] Entering App\Field::getFieldsPermissions: 93
#232 [trace] Entering App\Field::getFieldPermission: 93,addresslevel6a
#233 [trace] Entering App\Field::getFieldsPermissions: 93
#234 [trace] Entering App\Field::getFieldPermission: 93,addresslevel6a
#235 [trace] Entering App\Field::getFieldsPermissions: 93
#236 [trace] Entering App\Field::getFieldPermission: 93,addresslevel5a
#237 [trace] Entering App\Field::getFieldsPermissions: 93
#238 [trace] Entering App\Field::getFieldPermission: 93,addresslevel5a
#239 [trace] Entering App\Field::getFieldsPermissions: 93
#240 [trace] Entering App\Field::getFieldPermission: 93,addresslevel4a
#241 [trace] Entering App\Field::getFieldsPermissions: 93
#242 [trace] Entering App\Field::getFieldPermission: 93,addresslevel4a
#243 [trace] Entering App\Field::getFieldsPermissions: 93
#244 [trace] Entering App\Field::getFieldPermission: 93,addresslevel3a
#245 [trace] Entering App\Field::getFieldsPermissions: 93
#246 [trace] Entering App\Field::getFieldPermission: 93,addresslevel3a
#247 [trace] Entering App\Field::getFieldsPermissions: 93
#248 [trace] Entering App\Field::getFieldPermission: 93,addresslevel2a
#249 [trace] Entering App\Field::getFieldsPermissions: 93
#250 [trace] Entering App\Field::getFieldPermission: 93,addresslevel2a
#251 [trace] Entering App\Field::getFieldsPermissions: 93
#252 [trace] Entering App\Field::getFieldPermission: 93,addresslevel1a
#253 [trace] Entering App\Field::getFieldsPermissions: 93
#254 [trace] Entering App\Field::getFieldPermission: 93,addresslevel1a
#255 [trace] Entering App\Field::getFieldsPermissions: 93
#256 [trace] Entering App\Field::getFieldPermission: 93,poboxa
#257 [trace] Entering App\Field::getFieldsPermissions: 93
#258 [trace] Entering App\Field::getFieldPermission: 93,poboxa
#259 [trace] Entering App\Field::getFieldsPermissions: 93
#260 [trace] Entering App\Field::getFieldPermission: 93,description
#261 [trace] Entering App\Field::getFieldsPermissions: 93
#262 [trace] Entering App\Field::getFieldPermission: 93,description
#263 [trace] Entering App\Field::getFieldsPermissions: 93
#264 [info] SELECT * FROM `vtiger_picklist_dependency` WHERE `tabid`=93 || yii\db\Command::query
#265 [trace] Entering isPermitted(Accounts,,,) method ...
#266 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#267 [trace] Entering isPermitted(Leads,,,) method ...
#268 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#269 [trace] Entering isPermitted(Vendors,,,) method ...
#270 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#271 [trace] Entering isPermitted(Partners,,,) method ...
#272 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#273 [trace] Entering isPermitted(Competition,,,) method ...
#274 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#275 [trace] Entering isPermitted(OSSEmployees,,,) method ...
#276 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#277 [trace] Entering isPermitted(Contacts,,,) method ...
#278 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#279 [trace] Entering isPermitted(SSalesProcesses,,,) method ...
#280 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#281 [trace] Entering isPermitted(Project,,,) method ...
#282 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#283 [trace] Entering isPermitted(ServiceContracts,,,) method ...
#284 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#285 [trace] Entering isPermitted(Campaigns,,,) method ...
#286 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#287 [trace] Entering isPermitted(FBookkeeping,,,) method ...
#288 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#289 [trace] Entering isPermitted(HelpDesk,,,) method ...
#290 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#291 [trace] Entering isPermitted(ProjectTask,,,) method ...
#292 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#293 [trace] Entering isPermitted(ProjectMilestone,,,) method ...
#294 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#295 [trace] Entering isPermitted(SQuoteEnquiries,,,) method ...
#296 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#297 [trace] Entering isPermitted(SRequirementsCards,,,) method ...
#298 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#299 [trace] Entering isPermitted(SCalculations,,,) method ...
#300 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#301 [trace] Entering isPermitted(SQuotes,,,) method ...
#302 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#303 [trace] Entering isPermitted(SSingleOrders,,,) method ...
#304 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#305 [trace] Entering isPermitted(SRecurringOrders,,,) method ...
#306 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#307 [trace] Entering isPermitted(FInvoice,,,) method ...
#308 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#309 [trace] Entering isPermitted(SVendorEnquiries,,,) method ...
#310 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#311 [info] SELECT * FROM `vtiger_apiaddress` || yii\db\Command::query
#312 [info] SELECT COUNT(1) FROM `vtiger_apiaddress` WHERE (`name`='nominatim') AND (`val` > 0) || yii\db\Command::query
#313 [info] SELECT * FROM `vtiger_blocks_hide` WHERE ((`enabled`=1) AND (`blockid`=303)) AND (`view` LIKE '%Edit%') || yii\db\Command::query
#314 [trace] Entering isPermitted(Competition,CreateView,,) method ...
#315 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#316 [trace] Entering isPermitted(Competition,CreateView,,) method ...
#317 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#318 [trace] Entering getUsers(,Active,,) method ...
#319 [trace] Exiting getUsers method ...
#320 [trace] Entering getGroups(,) method ...
#321 [trace] Entering getUsers(,Active,,) method ...
#322 [trace] Exiting getUsers method ...
#323 [trace] Entering getGroups(,) method ...
#324 [info] Cannot translate this: 'testimage' for module 'Competition', lang: en_us
#325 [info] Cannot translate this: 'testimage' for module 'Competition', lang: en_us
#326 [info] SELECT * FROM `u_yf_attachments` WHERE `attachmentid`='' || yii\db\Command::query
#327 [error] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gitdevelop_crm.u_yf_attachments' doesn't exist
Failed to prepare SQL: SELECT * FROM `u_yf_attachments` WHERE `attachmentid`=:qp0 => vendor/yetiforce/yii2/db/Command.php:264

Is it something I have done?

Kind regards

**Comment by mariuszkrzaczkowski** [comment]
It's not done yet
