### ISSUE TITLE
Handler not found: entityBeforeDelete

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5540]
tried to delete a record via API:
~~~
PHP Fatal error:  Uncaught App\Exceptions\AppException: LBL_HANDLER_NOT_FOUND in vendor/yetiforce/EventHandler.php:290 
~~~

and the handler is
~~~
[error] - Handler not found, class: ModTracker_ModTrackerHandler_Handler | entityBeforeDelete 
~~~

only place i could find is here: (modules/Vtiger/models/Record.php:516)
~~~php
	$eventHandler->trigger('EntityBeforeDelete');
~~~

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/31b266c312183d448746d7cf24e1579895db5ff9#diff-84bf8d161f17f15a5c8cbd9c87cead08
