### ISSUE TITLE
PBX configure

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5541]
Hi All, 

Using 4.2.514. Is it possible to connect the pbx to a sip phone system which uses SRV records? A new company which is sweeping the UK/Europe is Firstcom uk. They provide a full VOIP encrypted system for a very good price.

At the moment it's all password protected and encrypted due to the new gdpr coming in to effect.

**Comment by migoi** [comment]
no

**Comment by alextovey** [comment]
I've seen the setup and they are going to release an api access token and key for me.

**Comment by KatarzynaUlichnowska** [comment]
This integration requires some programming.
