### ISSUE TITLE
Calendar: invite users broken (wrong permission check and Handler not found)

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5544]
#### Issue

**first:** bad translation, since it should invite almost everyone _but_ users, since the users module is not queried. In spanish translation: "Invite users" is "Invitar Potencial/Empresa/Socio/Proveedor" which describes it better.

**second:** it does not work. 

#### Actual Behavior

tried on gitdeveloper and tried to invite "kraga" (valid account), but "no results found".

#### Expected Behavior

To also have Users included (and its worklng)

#### The (main) bug

in modules/Calendar/actions/Invitees.php:60
~~~php
if (\App\Privilege::isPermitted($row['moduleName'], 'DetailView', $row['crmid'])) {
~~~

should be changed to
~~~php
if (\App\Privilege::isPermitted($row['setype'], 'DetailView', $row['crmid'])) {
~~~

since $row looks like
~~~
    [crmid] => 57204 
    [setype] => Accounts 
    [searchlabel] => Foobar Company
~~~
and the permission check is working again and showing results.

Unfortunatly this will result in another error, that prevents the selected record to be added:
~~~
[error] - Error Vtiger_Loader::getComponentClassName(Action, GetMail, OSSMail): Handler not found 
~~~
(include/Loader.php:164)

**Comment by aljoflo** [comment]
Hi were you able to solve this issue?

**Comment by mariuszkrzaczkowski** [comment]
Does the problem still exist in the newest version?

**Comment by migoi** [comment]
seems to work on gitdeveloper for Lead, Employees etc.

Still not working for Users

**Comment by migoi** [comment]
no, close it. Now it is enhancement.
