### ISSUE TITLE
PHP fatal error in creating PDF template

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#5548]
#### Issue
During creating (or editing) PDF template, after step 5 (content of footer) the system has been stopped.
In logs I can see:
[22-Nov-2017 05:15:08 Europe/Sarajevo] PHP Fatal error:  Uncaught Error: Call to undefined method App\Layout::getTemplatePath() in /home/***/crm/cache/templates_c/basic/4da3c64af06d20d97443a9b2c02824610182ec8b_0.file.AdvanceFilterCondition.tpl.php:26
Stack trace:
#0 /home/***/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_5a14f90aeafe82_62380834(Object(Smarty_Internal_Template))
#1 /home/***/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(172): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /home/***/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(206): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /home/***/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(372): Smarty_Internal_Template->render()
#4 / in /home/***/crm/cache/templates_c/basic/4da3c64af06d20d97443a9b2c02824610182ec8b_0.file.AdvanceFilterCondition.tpl.php on line 26 

Please help...

#### Your Environment

* YetiForce Version used: 4.2.0

**Comment by mariuszkrzaczkowski** [comment]
Does the problem still exist in the newest version?

**Comment by pflaz** [comment]
In the newest version there are so many issues so I restored the system from backup to 4.2.0 (in example charts don't work on the home page, all closed opportunities are shown in 'open' tab - I have posted it on github).
