### ISSUE TITLE
error in global search in settings

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#5551]
handler not found error .

![bug3t](https://user-images.githubusercontent.com/18072100/33125238-f024da68-cf94-11e7-87ed-73317bb7d2a8.jpg)

**Comment by bpabiszczak** [comment]
Now work on gitdeveloper. 
![image](https://user-images.githubusercontent.com/10197525/33856548-c291d98c-dec8-11e7-8fc2-3b045d04ebf3.png)
