### ISSUE TITLE
New functionality in v4.3

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#5553]
We added a new functionality that allows you to place “related modules” in different places (tab, record summary, record details).

The functionality will be available in version 4.3.

Screenshots can be found [here](https://public.yetiforce.com/gallery/#15113522841629).

**Comment by kpaulaha** [comment]
Sounds interesting. Must try when available.

**Comment by bpabiszczak** [comment]
You can test here: https://gitdeveloper.yetiforce.com/

**Comment by vovpff** [comment]
Cool stuff!

**Comment by mariuszkrzaczkowski** [comment]
https://public.yetiforce.com/gallery/#15113522841629

**Comment by paulokruz** [comment]
Great job.
Works very well and it´s very usefull and simplifys how users manage crm.

**Comment by PercyP** [comment]
A brilliant and VERY useful addition. 

Thank you!

**Comment by bpabiszczak** [comment]
and check this
![2017-11-22_22-36-55](https://user-images.githubusercontent.com/10197525/33154238-608a95a2-cfe7-11e7-98e5-5b8e47610568.png)

**Comment by PercyP** [comment]
Wow! Love the totals feature. I have just tested it on developer. Can I ask, is there a way of re-setting the sum? For example, if I de-select one of the records the sum doesn't change - there is no clear or reset button or the ability to click sum again. You have to refresh the browser page instead. 

Another brilliant new feature we were not expecting :O)

**Comment by mariuszkrzaczkowski** [comment]
Calculating the sum of the fields in related modules
![2017-11-23_09-18-33](https://user-images.githubusercontent.com/10198654/33163549-5879eece-d02f-11e7-9a71-896d042abce4.png)

**Comment by mariuszkrzaczkowski** [comment]
@PercyP
I've added an upgrade to the calculation now button is not hidden
![2017-11-23_09-47-58](https://user-images.githubusercontent.com/10198654/33164503-663014f4-d033-11e7-9b8d-94ee6aafe0cd.png)

**Comment by PercyP** [comment]
Just tested. Works perfectly.
