### ISSUE TITLE
Update package issue (Failed to prepare SQL: Set FOREIGN_KEY_CHECKS = 0)

### ISSUE THREAD

**Issue by Foxmillet** [YetiForceCompany/YetiForceCRM#5558]
#### Issue
I'm using the YetiForce 4.2.0 stable build (that was automatically installed using Softaculous by my hosting).

Now I'm trying to install the newer update package that I downloaded from this GitHub repo.
I downloaded it and tried to install it using the YetiForce built-in interface for those purposes:
1. https://pp.userapi.com/c824201/v824201135/32039/mSly4nKZPss.jpg

It validates the package successfully:
2. https://pp.userapi.com/c824201/v824201135/32043/KXqlT-ZSiSI.jpg

But when I click on the "yes" button on the bottom of the screen, the whole system waits for about 3-5 minutes and then shows me the following error:
3. https://pp.userapi.com/c824201/v824201135/3204d/-sOtWS81Lwk.jpg

I contacted my hosting support (bc I thought it was an SQL server settings issue), they replied the following: 
"We are unable to diagnose if that is the exact reason that this error is displaying since our knowledge of this software is limited. Yetiforce CRM Support should at least be able to advise why the error is displaying and what is required to fix it. From there, we can see if it is something that can be done on our end."

Has someone faced this challenge before? Any tips on what should I do to complete the installation process?

Hosting: inMotion

**Comment by paula-w** [comment]
What's your mysql version?

**Comment by Foxmillet** [comment]
5.6.37

**Comment by Foxmillet** [comment]
So it's hopeless? :)

**Comment by Foxmillet** [comment]
I'm really sorry for bumping this thread again, but could anyone at least give me some direction or advice on where to look and what to do?

Thank you all in advance and have a great Friday!

**Comment by bpabiszczak** [comment]
This must be verified by a programmer!

**Comment by bpabiszczak** [comment]
The real problem is "mysql server gone away". Consult this error with the mysql server administrator.
