### ISSUE TITLE
Failed Module does not contain default language (en_us).

### ISSUE THREAD

**Issue by CostasChro** [YetiForceCompany/YetiForceCRM#5563]
#### Issue

Fail to install the default libraries after a clean install.

#### Actual Behavior

After a clean install, I downloaded the 4 .zip files ( lib_mPDF-master.zip // lib_roundcube-master.zip // lib_PHPExcel-master.zip // lib_gantt-master.zip) and tried to install them via the Software configuration > Standard modules > Modules – Installation > System settings. The result was: 
"Failed
Module does not contain default language (en_us)."

#### Expected Behavior
To be installed without a problem. 

#### How to trigger the error

1. Download the zip files.
2. Go to Software configuration > Standard modules > Modules – Installation > System settings.
3. "Install via File" (Top right blue button)
4. Choose one file at the time
5. "Import" (Green button)

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
* Environment name and version: 
* Operating System and version: Win 10 x64 Pro

**Comment by WalterLuis** [comment]
that installation process is to install a custom module similar to Accounts, Contacts, etc. is not ready to install the libraries

https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8

![install_2017-11-24_10-15-55](https://user-images.githubusercontent.com/18419851/33205957-a8d178f2-d100-11e7-9f1c-eee78d9e111c.png)

**Comment by CostasChro** [comment]
Thank you for your fast response.

The issue is that I tried to install the libraries via the blue buttons as you correctly shown in the screenshot but the is no progress. When I press them, the browser "flashes" (tries to get somewhere, but then returned to the initial screen - the screen that you show above).

How to solve this issue? Is this a problem of the server settings? If yes, please provide any information-"guideline" in order to contact my host provider and inform them accordingly.

Thank you.

**Comment by WalterLuis** [comment]
try change this value to TRUE
https://github.com/YetiForceCompany/YetiForceCRM/blob/b7d221e40c4b0608bbd72a4cae2592f39dbc3d0e/config/developer.php#L20

**Comment by CostasChro** [comment]
Unfortunately nothing changed... :(

**Comment by CostasChro** [comment]
Any other recommendation? 

Thank you.

**Comment by mariuszkrzaczkowski** [comment]
> After a clean install, I downloaded the 4 .zip files ( lib_mPDF-master.zip // lib_roundcube-master.zip // lib_PHPExcel-master.zip // lib_gantt-master.zip) and tried to install them via the Software configuration > Standard modules > Modules – Installation > System settings. The result was:
> "Failed
> Module does not contain default language (en_us)."

External libraries can not be installed using "Install from file" so it does not work.
> Any other recommendation?

Start with logs and debugging

**Comment by CostasChro** [comment]
Thank you for your interest.

Please inform me with what actions would you like me to perform.

Thank you.

**Comment by mariuszkrzaczkowski** [comment]
> Start with logs and debugging

**Comment by CostasChro** [comment]
I am not a programmer. Do you need to transfer (copy/paste) the log from a file or something like this?

Shall I follow something from this https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging ?

**Comment by mariuszkrzaczkowski** [comment]
Run full logs and send an e-mail github@yetiforce.com

**Comment by Akaki-1991** [comment]
hello, how i can to export/import modules  old version yeti to newer version?
