### ISSUE TITLE
Error displaying information

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5564]
Tested on https://gitdeveloper.yetiforce.com/index.php
![4fd7c68b-af52-4380-ac72-81cbdd7c757b](https://user-images.githubusercontent.com/19627226/33207681-2cfee4bc-d141-11e7-93f1-f90955b32434.jpeg)

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
