### ISSUE TITLE
advice on setting up linked module

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#5565]
Background:
We have been adding custom fields to contacts to a points it is getting too much to keep an overview. I am now looking for some pointers how to create a new module connected to contacts without the need to enter their details al the time, so linked to contacts.
I understand I will need to use 'linked fields'  but how this is done the best way is a bit of mystery.

**Comment by vovpff** [comment]
@zebrahosting try to make cusom module and add to contact module field 1:m related to new one

**Comment by PercyP** [comment]
Hi,
go to Standard Modules - Modules Installation - Create Custom Module (green button top right). Fill in boxes.

Then go to Edit Modules and add a new custom field

Select Related field 1:M
Select the COntact module as the field that contains the related contact name. See attached image

![linktocontact](https://user-images.githubusercontent.com/10598886/33243344-5df627f0-d2dc-11e7-93e0-d5edd9dd0b54.png)

Is that what you meant?

**Comment by PercyP** [comment]
Ah, someone had already answered - sorry :O)
