### ISSUE TITLE
Yetiforce not functioning

### ISSUE THREAD

**Issue by zatuamirah** [YetiForceCompany/YetiForceCRM#5567]
#### Issue
log in there and then try to click on anything on the crm. Nothing seems to open, it just stays on empty blank page with non functioning tools.

#### Actual Behavior
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' ". at index.php:36 
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' ". at index.php:36
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' ". at index.php:36
#### How to trigger the error
Just like the demo 

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Google Chrome  62.0.3202.94 (Official Build) (64-bit)
* Environment name and version:PHP 7.0.25 .
* Operating System and version: macOS Sierra 10.12.6

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version.
