### ISSUE TITLE
Mailscanner binds sent mails as received

### ISSUE THREAD

**Issue by worldwidehigh** [YetiForceCompany/YetiForceCRM#5568]
#### Issue
My Mailscanner binds every Mail as received Mail. In 4.1 it doesn´t

<img width="911" alt="unbenannt" src="https://user-images.githubusercontent.com/20869581/33254741-9318e8e6-d34a-11e7-8fad-cb29bbffee42.png">

<img width="435" alt="unbenannt" src="https://user-images.githubusercontent.com/20869581/33254859-2247b38a-d34b-11e7-9103-29a74b3a7307.png">

#### Your Environment
* YetiForce Version used: 4.2
* Browser name and version: Chrome
* Operating System and version: Win 10

**Comment by aljoflo** [comment]
Hello, did you find  how to fix it?

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/33628468-187680fe-da01-11e7-8ea6-80cbc4ec11aa.png)

**Comment by worldwidehigh** [comment]
No i didn't found a answer. I have set the folders correctly:

![unbenannt](https://user-images.githubusercontent.com/20869581/33645181-ca25e6f8-da49-11e7-917f-313ecede6827.png)

**Comment by mariuszkrzaczkowski** [comment]
Mails were sent in the mail client which is in crm?

**Comment by worldwidehigh** [comment]
Can you explain the question?

**Comment by aljoflo** [comment]
I also have set the folder properly, but the sent mails still bind as received. I'm sending the mails with the mail client in the CRM

**Comment by bpabiszczak** [comment]
Firstly, you need to remember that the scanner, which is built-in YetiForce, IGNORES forlders from which emails come. The scanner detects whether an email is incoming or outgoing on the basis of EMAIL ADDRESSES and this is the only factor that is vital for this mechanism.

The Scanner marks emails as: Sent, Received, Internal. It identifies it on the basis of email address of SMTP mailbox, if you send an email and in the field "FROM" will be the same address that SMTP mailbox, it will be a sent email. 

Thanks to this solution you can bind one folder [e.g. ALL folder in GMAIL] and scan all emails and the Scanner will separate them in a correct way.

You should verify this problem at GitDeveloper, GMAIL mailbox is bind there by default. Or you can download GitDeveloper loccally and check whether this occurs in the latest version. If so, then video how you configure the mailbox, the scanner and to whom you are sending an email.

I suppose that you may not entirely understand the mechanism, but is a single problem which requires programming analisys. If you want us to verify it for free, you need to show us how to trigger it. If you want us to do it for a payment, you need to buy a support package and send us access data.

**Comment by worldwidehigh** [comment]
Can you post a screenshoot where I find the smtp mailbox and a sample configuration?
