### ISSUE TITLE
Info: italian language

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5569]
How can I add italian language to your project?
Can I duplicate the English language file and then edit it in Italian?

**Comment by vovpff** [comment]
@centoasa You can add new language here: https://gitdeveloper.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=4&fieldid=53

**Comment by centoasa** [comment]
@vovpff after I've added my language, in the dropdown "edit language" I can't found just added language.

**Comment by vovpff** [comment]
@centoasa looks like this is bug.

@mariuszkrzaczkowski I tried at 4.2.550 to add Italy language. This language appears at Available languages tab but can be selected at Edit language tab

**Comment by centoasa** [comment]
@vovpff it's right

**Comment by mariuszkrzaczkowski** [comment]
try now

**Comment by centoasa** [comment]
with "missing cache deletion" new file, Yeti stuck while I try to add new language
![schermata 2017-11-29 alle 15 27 47](https://user-images.githubusercontent.com/5500935/33380102-4637ec58-d51a-11e7-9603-5144ccc92cf9.png)

**Comment by bpabiszczak** [comment]
You try on GitDeveloper version? For me work.

**Comment by centoasa** [comment]
it's right, works! I don't understand for me stuck!

**Comment by mariuszkrzaczkowski** [comment]
> with "missing cache deletion" new file, Yeti stuck while I try to add new language

GitDeveloper is a test environment, apcu Cache is enabled to accelerate work under heavy load.
This way it is easier to find errors in the system and thus be more stable.
If you want a stable environment then use GitStable

**Comment by centoasa** [comment]
As I says on Git works well. It’s only for me still doesn’t work.

**Comment by mariuszkrzaczkowski** [comment]
If gitdev is working then try updating your system https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%204.x.x/4.2.0_to_4.3.0/zip

**Comment by centoasa** [comment]
Just update done!
Add language works well!
sorry: on this new release, how can I do to edit a contact?
![schermata 2017-11-30 alle 09 27 26](https://user-images.githubusercontent.com/5500935/33421436-516c8bd6-d5b2-11e7-8855-23e183f8fe63.png)

**Comment by bpabiszczak** [comment]
New question new issue.

**Comment by centoasa** [comment]
I've translated a lot of part of Yeti in Italian language: how can I send to you my Italian language folder?

**Comment by centoasa** [comment]
How can I translate core of Yetiforce, as "first name" in contact, because in translation I've added Language variable=First name but nothing change.

**Comment by bpabiszczak** [comment]
One question = one issue

**Comment by mariuszkrzaczkowski** [comment]
> I've translated a lot of part of Yeti in Italian language: how can I send to you my Italian language folder?

You can send to us by e-mail or Pull requests

**Comment by centoasa** [comment]
@mariuszkrzaczkowski sorry, I'm not very able with github

**Comment by mariuszkrzaczkowski** [comment]
send by email github@yetiforce.com
