### ISSUE TITLE
Connecting Woocommerce

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#5570]
Anybody here with a working interface to Woocommerce or anybody interested in investing in this?
we would like to see address and sales automatically imported in YetiforceCRM so we can use it in filters etc.
We tested an existing plugin (Cart2CRM) but found it not working at all.

**Comment by kpaulaha** [comment]
We have preliminary interest in it depending on costs and schedule, at the moment we do not have free resources to handle the work.  We have been working with Opencart for years, but been moving more to wp family.

**Comment by paula-w** [comment]
I have a message from Błażej - we can provide you with cost and time estimates if you send us a very detailed business description of this integration.

**Comment by zebrahosting** [comment]
Guess it would be constructive to make that list here together. Like everyone we don't have time to make lists in details but together this might work.

For us it needs:
Sync the customer to contacts with address details and what product has been purchased.
That probably needs a sync of the products too.
We want to be able to set a status of a client when he has paid for a product and are not interested in invoicing, bookkeeping etc because we do this via WC to our own bookkeeping system.
We will also not use Yeti to run campaigns. Relative simpel and limited would be ok for us but can imagine some people want more.

**Comment by bpabiszczak** [comment]
do I have to close issue? ;)

**Comment by zebrahosting** [comment]
If no one else is interested including you, close it. But I still hope we can make a start with this.
Might also help to give a budget estimation for a simple solution.

**Comment by kpaulaha** [comment]
I thought about it and because we use in our projects Mautic to collect leeds etc, and because there is a working interface between woocommerce and mautic, we rather need it between mautic and yf, which is next on our schedule when 4.3 up and running. Agree with @zebrahosting  that would be nice to get a cost estimation for the work for future use.

**Comment by bpabiszczak** [comment]
@zebrahosting please provide us with a very detailed business description of these changes [if two modules are supposed to be synchronized you have to tell us which fields should be synchronized and in which direction]. We will then send you the estimate. I’m closing the issue.

**Comment by Pietrox** [comment]
Hmm, what about an api+workflow designer.
What I mean is first part would be a rest API designer that administrator is defining:

1. Module
2. Field
3. Method (POST or GET)
4. Generate Api key
5. Name the endpoint and generate api url
6. (Optional) limit by origin header domain or IP 

Reactive part would be in workflows to define:
1. Api URL to outside service.
2. Fields to pass + map and name them
3. Method (POST or GET)
4. Triggers (workflows as is)

From this point of view it should have comminucation with most of REST based api and only limitation would be to have the 3rd party to post to yetiforce.

I could squeeze around 30-40h budget. Maybe more, but is there any hourly calculation?

**Comment by ldgbc** [comment]
Currently I don't really do any commerce yet but will be needing it in the future. Unfortunately the current design of Yetiforce will be that difficult. Looking forward to more info on this topic though.
