### ISSUE TITLE
Error: virus in Yetiforce complete

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5571]
By cpanel-->fail manager, when I try to add YetiForceCRM-4.2.0-complete.zip ather I've this alert:
![schermata 2017-11-27 alle 11 27 19](https://user-images.githubusercontent.com/5500935/33262595-0e5634d4-d367-11e7-8b6b-e7217e070e03.png)

**Comment by WalterLuis** [comment]
Hello,

I downloaded the file 'YetiForceCRM-4.2.0-complete.zip' from 'https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.2.0' and I analyzed it with Kaspersky and it did not detect anything outside of the normal.
I have unzipped it and I can not find the file that your server detected when uploading the .zip called 'Atomicorp.zip', 'Atomicorp.bat' or anything similar.

Did you download the file 'YetiForceCRM-4.2.0-complete.zip' from another source?

**Comment by centoasa** [comment]
I've downloaded the zip from sourceforge and also from this github. Maybe cpanel internal antivirus has detected something strange!
So I've resolved uploaded the zip file by filezilla and unzipping by cpanel (more faster than 1 file per time)

**Comment by WalterLuis** [comment]
I tried the zip also from 'Sourceforge' and I did not find anything either. Just in case, analyze your computer in case you have a virus that has affected the .zip file before uploading it.
I do not know what it could be, except that as you said ... it's something from the cPanel, but I also can not find that file 'Atomicorp'

**Comment by WalterLuis** [comment]
I already understood, [Atomicorp](https://atomicorp.com/) is a kind of 'antivirus' that dectectó some .bat file 'Unofficial', being this something normal, since there are files with the .bat extension created by YetiForce for functionality in CRM.
as for example: 'cron/vtigercron.bat'

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/33311885-7ff6b0b8-d426-11e7-81a6-4dafa92e6dc6.png)

**Comment by centoasa** [comment]
@WalterLuis great!
