### ISSUE TITLE
Item name broken edit view

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5578]
#### Issue

When advanced module record added firs time there is no problem but when you try to edit already available record you can find this stuff

**Invoice**
_Record view_
![image](https://user-images.githubusercontent.com/8545791/33312210-426288a0-d438-11e7-9e88-b847cdb97dc1.png)

_Record edit view_

![image](https://user-images.githubusercontent.com/8545791/33312254-61a0baca-d438-11e7-9cbe-9881bb664d70.png)

**IGRN**

![image](https://user-images.githubusercontent.com/8545791/33312291-77a5342c-d438-11e7-81ea-47600c5cdbea.png)

**IGDN**

![image](https://user-images.githubusercontent.com/8545791/33312275-6d3f1ae8-d438-11e7-9ede-b7e7e7ce70dc.png)

Text sample before:

```
Inwertery Phoenix 180 W - 5 kW' data-fieldinfo='{"mandatory":true}' data-columnname="name" />
```

Text sample inside field:

```
<a class='modCT_Products showReferenceTooltip' href='index.php?module=Products&view=Detail&record=346' title='Product'>Inwertery Phoenix 180 W - 5 kW</a>
```

#### Your Environment

* YetiForce Version used: dev 4.2.551
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@mariuszkrzaczkowskichecked after update from 4.2.0 to 4.2.580. Bug is here
![image](https://user-images.githubusercontent.com/8545791/33515594-877c162c-d776-11e7-8f50-7177d1d1923f.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski  sorry for some confusion. my last comment not so correct. i will post my case tomorrow

**Comment by vovpff** [comment]
@mariuszkrzaczkowski 2nd comment not correct. Problem with innactive buttons appears if your browser cache not cleaned after system update.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski RC5 bug is here

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/5708
