### ISSUE TITLE
Migration tools

### ISSUE THREAD

**Issue by suburbanworrier** [YetiForceCompany/YetiForceCRM#558]
Hi,

I understand that the installation process offers a migration option for [current Vtiger](https://github.com/YetiForceCompany/YetiForceCRM/issues/22) to YetitForce versions. For those with older code are there tools/documentation/advice or other resources available?

I'm preparing to migrate from VT 5.3 and would dearly love to hear that I don't have to point upgrade through VT 5.4, 6.0, 6.1 etc to get to my end goal. As my 5.3 source code isn't completely standard I'm also concerned to correctly test at each stage - what are best practices for this?

Kind thanks in advance,

**Comment by KatarzynaUlichnowska** [comment]
Hello Matt,
unfortunately our tool allows to migrate from Vtiger 6.2. That means that you need to migrate your version the way you described it:  5.3 > 5.4 > 6.0 > 6.1 > 6.2 > YetiForce 1.4. What is even worse, migration packs between Vtiger versions are not always correct and the fact that your system was modified isn’t helpful either. It is a difficult process for our programmers who performed over 60 migrations from VT to YF so it will be even more difficult for you. 
For us it would take the entire working day, and if you want to do it on your own, it will take you 2-3 days [if you are familiar with the system and migrations].
