### ISSUE TITLE
[BUG][4.2.558][Users] some user fields are not saved

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#5583]
#### Issue

some user fields are not saved from the Edit view, but using the quick edit if they save the changes, as long as that field can be edited from the Detail view

#### Actual Behavior

![2017-11-28_20-38-36](https://user-images.githubusercontent.com/18419851/33343486-600737bc-d47d-11e7-811d-1160b3a971bd.gif)

#### Your Environment

* YetiForce Version used: 4.2.558
* Browser name and version: chrome 62
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: gitdeveloper.yetiforce.com

**Comment by elvissaba** [comment]
Confirmed. I had same issues and workarround was recreating users.
