### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5584]
Yeti 4.2.0 on apache-litespeed
![schermata 2017-11-29 alle 09 11 32](https://user-images.githubusercontent.com/5500935/33364612-76600b66-d4e5-11e7-9038-ef1d5011fd7d.png)
Try to delete a user, Yeti stuck.

**Comment by bpabiszczak** [comment]
Works on GitDeveloper.
