### ISSUE TITLE
Record preview on records list [new feature]

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#5585]
We are going to make video manuals for new functionalities in the nearest future, unfortunately right now we don’t have enough time for that. Below you can find some screenshots for a new feature that will be added in version 4.3. You can already test it on GitDeveloper!

![new_in_4 3_1](https://user-images.githubusercontent.com/10197525/33367960-89750f48-d4f0-11e7-8d6b-c9668f14d6ef.png)
![new_in_4 3_2](https://user-images.githubusercontent.com/10197525/33367969-8dd310da-d4f0-11e7-8c88-c46595526aa5.png)
![new_in_4 3_3](https://user-images.githubusercontent.com/10197525/33367973-90200898-d4f0-11e7-9d90-413497226ae1.png)

PS: What do you think about it?

**Comment by vovpff** [comment]
@bpabiszczak this will be cool feature.
When summary view will be available for products?

**Comment by bpabiszczak** [comment]
What do you mean? Can you paste a screenshot?

**Comment by vovpff** [comment]
@bpabiszczak there are ability to view summary of record and add widgets for all modules excluding products. For example for invoices:

there are ability to add widgets:

![image](https://user-images.githubusercontent.com/8545791/33371839-1095a458-d50d-11e7-8c98-1ac97109ec03.png)

ability to quick preview one record

![image](https://user-images.githubusercontent.com/8545791/33371895-37e5d938-d50d-11e7-9187-2439aab06390.png)

To quick preview list of summary or details

![image](https://user-images.githubusercontent.com/8545791/33371951-62b52e02-d50d-11e7-9ab4-76f1fb495c10.png)

![image](https://user-images.githubusercontent.com/8545791/33371957-68b06da8-d50d-11e7-9c44-e122a35df293.png)

But there are not available to add widgets for products module and there are no summary view for products record.

![image](https://user-images.githubusercontent.com/8545791/33371985-80686c98-d50d-11e7-8b13-8fde36c31ee9.png)

**Comment by bpabiszczak** [comment]
It’s open source, you can add whatever you want to the system. I don’t know how I can help you, this topic is about a new functionality, and I don’t know how your problem is related to this issue. The functionality you see in these screenshots was ordered and paid for by a client. You can also order development of the system from us and we will add anything you need!

**Comment by vovpff** [comment]
@bpabiszczak thanks a lot for information! I will email you after some time. Our company plan to introduce your system but I don't know our real requirements for this time.

**Comment by aljoflo** [comment]
Great functionality, can we add other column to the records preview list besides subject?

**Comment by vovpff** [comment]
@aljoflo there are columns from filter availble.

**Comment by aljoflo** [comment]
@bpabiszczak @vovpff  When a create a new module the quick preview is empty, do you know how can i select the records to show in quick preview?
