### ISSUE TITLE
[PL] Jak zmienić limit harmonogramu wykonywania zadań w obiegu informacji

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5587]
#### Issue
Obecnie w obiegu informacji jest limit dla harmonogramu wykonywania zadań do 10.
Jak go zmienić?

#### Actual Behavior
Maksymalny limit przekroczony : 10

#### Your Environment
* YetiForce Version used: 4.2.0

**Comment by bpabiszczak** [comment]
Mogę prosić o zrzut ekranu o które ograniczenie chodzi?

**Comment by anderpydev** [comment]
Jasne.
![handler_limit](https://user-images.githubusercontent.com/26583746/33373957-71f8f8ac-d504-11e7-823b-ddaeb3bda7be.png)

**Comment by anderpydev** [comment]
Witam,
Odświeżam pytanie. Mogę ten limit zmienić? Gdzie jest zapisana jego wartość?
Szukałem w plikach i db, ale nie mogę na to trafić.

**Comment by bpabiszczak** [comment]
w wolnej chwili sprawdzimy, mamy do wykonania dzisiaj dwie duże migracje.

**Comment by anderpydev** [comment]
Dobrze, dziękuję za odp.

**Comment by konadrian** [comment]
Limit pobierany jest w tej metodzie
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/com_vtiger_workflow/VTWorkflowManager.php#L166
