### ISSUE TITLE
[BUG][4.2.567][Relations] Searched a Contact related to an Account does not match

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#5588]
#### Issue
I saw this code on the file modules/Contacts/views/Popup.php
![2017-11-29_14-39-50](https://user-images.githubusercontent.com/16593721/33381398-d59bff2e-d515-11e7-852f-3204628881e3.png)

So I test it adding a related field to Contacts module on Project module.
![2017-11-29_14-42-44](https://user-images.githubusercontent.com/16593721/33381473-040c9616-d516-11e7-851d-f3667813b0c9.png)

With this field I wanted to assign a Contact from a certain Account to a project.

#### Actual Behavior
When I want to create a new Project and I choose an Account, I would like to search a Contact related to this Account, but it works bad because it's taking the Contacts related to the last change that I did (Contacts related to the Account saved on Database)

#### Expected Behavior
Choose an Account and see the Contacts related to this Account

#### How to trigger the error
![2017-11-29_14-56-16](https://user-images.githubusercontent.com/16593721/33381585-5a997d8c-d516-11e7-9c5c-4aa72a5fad81.gif)

I think it is a JavaScript problem

#### Your Environment
* YetiForce Version used: Latest version
* Browser name and version: Google Chrome
* Operating System and version: Windows 10

**Comment by elvissaba** [comment]
Cinfirmed. Not working on latest GitHub Dev version.

**Comment by bpabiszczak** [comment]
Firstly, you have added a new related field with "Contacts" module.... and in the Projects module there is already a relation with a related module and not a related field. This means that you have two relations in one module what, in our opinion, isn't correct from a business perspective as well as from the technical perspective.

If you want to change a relation or you want two relations in one module, you need to perform some programming.
