### ISSUE TITLE
permission check cannot be passed because of unknown variable

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5589]
#### Issue

in vendor/yetiforce/Privilege.php around line 260
~~~php
case 3:
	$permission = static::isPermitted($recordMetaData['setype'], 'DetailView', $id);
	$relatedPermission = $permission == 'yes' ? true : false;
	break;
~~~
with commit https://github.com/YetiForceCompany/YetiForceCRM/commit/efd6146d15232c919985e2e0b3f734289a9ef5a6#diff-d0914aafade29aa6e83902979c867ce2 the new "case 3" block is introduced. The variable $id is not set anywhere in this code. I guess it should read $record

**Comment by mariuszkrzaczkowski** [comment]
Thanks a lot, you are the best
