### ISSUE TITLE
[Question] How to avoid duplicated mail binds with mailscanner

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#5591]
#### Issue

Hello, do you have a recommendation to avoid duplicated relations with mailscanner. For example, I have two CRM user and both of them are copied in the same email, when both accounts receive an email the mailscanner action bind the email received twice to the same opportunity.

#### Expected Behavior
To avoid duplicate relations or mail exception for user

#### How to trigger the error

1.Mailscanner programed for two user and related sales process
2.Receive one same email with both account copied, mailscanner will related each email to the opportunity and therefore will be duplicated emails
3.

#### Your Environment

* YetiForce Version used:4.2.0
* Browser name and version:firefox
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Try setting this parameter to true
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/OSSMailScanner.php#L10
