### ISSUE TITLE
[BUG] Missing scroll bar of module users 

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5592]
v4.2.572
#### Actual Behavior
![zalo_screenshot_30_11_2017_713948](https://user-images.githubusercontent.com/19627226/33418531-e10ab74c-d5d8-11e7-9044-f3a85e955e1c.png)

#### Expected Behavior
![zalo_screenshot_30_11_2017_712852](https://user-images.githubusercontent.com/19627226/33418527-dd45a2b6-d5d8-11e7-99d9-40f61d44726b.png)

**Comment by mariuszkrzaczkowski** [comment]
#5723

**Comment by ezbank** [comment]
@mariuszkrzaczkowski theme twilight
![zalo_screenshot_23_12_2017_430775](https://user-images.githubusercontent.com/19627226/34316923-cf881768-e7d4-11e7-9626-d5fa973b8f98.png)
