### ISSUE TITLE
Global Search Not Working - YetiForce 4.2.0 

### ISSUE THREAD

**Issue by mjapple** [YetiForceCompany/YetiForceCRM#5594]
Good Time to Everyone

The Issue is for Global Search which is not functioning in my version as well as in _https://gitstable.yetiforce.com_  stable version

![globalserach](https://user-images.githubusercontent.com/6837503/33425833-5d73d8ea-d5d9-11e7-8810-76d0c5d5c759.gif)
The Actual behaviour is while we enter the data in the accounts or any other module the global search results are having shown the blank box
 
We expect to have the global search performing and finding the results which are already recorded

* YetiForce Version used:4.2.0
* Browser name and version: Chrome

* Operating System and version: OS X

**Comment by kpaulaha** [comment]
Works ok when cron in operation

**Comment by mariuszkrzaczkowski** [comment]
Can you try to trigger it on gitdev?

**Comment by mjapple** [comment]
@kpaulaha then now i need to check the cron.

**Comment by mjapple** [comment]
@mariuszkrzaczkowski Sure , means i try again on gitdev

**Comment by kpaulaha** [comment]
gitstable.yetiforce.com don't have cron on. gitdev has and there it works ok

**Comment by mjapple** [comment]
Well Thanks , i already made the cron setup in hosting . but seems not yet ok

**Comment by setras** [comment]
I just ran into the same problem after I changed the search configuration and pushed the 'Update Label' button.
My Problem was that the update process did not populate the 'userid' column in the 'u_yf_crmentity_search_label' database table, for testing I updated the field manually it worked again.

After some digging I made the following change to file 'vendor/yetiforce/Record.php' and it seems to work but I haven't really had the time to test or investigate it fully.
[modified-Record.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/1544435/modified-Record.zip)

```
209a210
> 			\App\PrivilegeUpdater::setUpdater($moduleName, $id, 6, 0);

```

**Comment by mariuszkrzaczkowski** [comment]
cron is already working

**Comment by bpabiszczak** [comment]
Now work on gitstable. 
![image](https://user-images.githubusercontent.com/10197525/33856699-39c0eeb2-dec9-11e7-8927-fc473e0a18db.png)

**Comment by mjapple** [comment]
Thanks for all answers Cron Should be Enabled , I understand that .
now i need to make sure what i tried is well done 
The PHP version is 7.0.30
I added the cron jobs to my cron section in hosting, as per command written in the link below:
https://yetiforce.com/en/knowledge-base/documentation/user-documentation/item/enable-cron
_Add a file to the crontab, e.g. in such format: */5 * * * * sh /var/www/crm/cron/vtigercron.sh &>/var/www/crm/cache/logs/cron.log [pay attention to a correct path to the YetiForce system]._ 

i made the permission as follow --> 775
Change file permissions /var/www/crm/cron/vtigercron.sh to 775 [or to other permissions that are compatible with an internal security policy in a company]. 

The 3rd step is puting the statement in vtigercron.php file as follow 
_Set a path in the file /var/www/crm/cron/vtigercron.sh to PHP: export USE_PHP=/usr/local/php56/bin/php [here it is also required to pay attention to the file, because it can be located differently on each server and also keep an eye on a path to PHP that is different for various servers. An administrator can provide information about this path or it can be checked in phpinfo]._ 

I did like this cause my PHP is 7.0.3  --> export USE_PHP=/usr/local/php70/bin/php70
[i am not sure of this step]

and not still the cron is not functioning 

btw the cron for our hosting is working fine with Vtiger
 Many Thanks and Wish everyone prosperity 

![server](https://user-images.githubusercontent.com/6837503/42890709-2b0eebdc-8ab6-11e8-9e9f-596e08afc64c.png)

![server-config](https://user-images.githubusercontent.com/6837503/42890628-fad9ab0a-8ab5-11e8-9073-9c327d503311.jpg)
