### ISSUE TITLE
[BUG][4.2.572][Decimal] Error entering an ilegal character in a decimal field

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#5595]
#### Issue
Error page when I enter an ilegal character in a decimal field

#### Actual Behavior
When I enter a decimal value ussing a different character of these:
![2017-11-30_10-56-10](https://user-images.githubusercontent.com/16593721/33427420-218bdb64-d5bd-11e7-9b0b-9919e7948ddd.png)

it shows me this error:
![chrome_2017-11-30_10-48-48](https://user-images.githubusercontent.com/16593721/33427290-c181008c-d5bc-11e7-8221-ea42ecfdad9d.png)

#### Expected Behavior
Show an alert.

#### Your Environment

* YetiForce Version used: Latest version
* Browser name and version: Google Chrome
* Operating System and version: Windows 10

**Comment by mariuszkrzaczkowski** [comment]
It has already been fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/98c2393c1182b07bd8e528d15ddf968e72e8b409#diff-468e9ac04e11402c8af788a41a683395
