### ISSUE TITLE
History Updates Not Available - My Server Configurations are not totally Met

### ISSUE THREAD

**Issue by mjapple** [YetiForceCompany/YetiForceCRM#5596]
Good Time,
The Issue is the history updating for accounts for contacts as of now only these two are not functioning
Means when a contact is created (or any new account is created) and later when i add or remove or edit the history of these actions are not reflected in the "history" tab at all.

![1](https://user-images.githubusercontent.com/6837503/33428516-9c738d20-d5e2-11e7-86d6-6f4393fafe02.gif)
![2](https://user-images.githubusercontent.com/6837503/33428518-9dfe4306-d5e2-11e7-9bd7-8f8234529e1d.gif)
![3](https://user-images.githubusercontent.com/6837503/33428521-9fbe90c4-d5e2-11e7-8683-217707ef9c5c.gif)
When I edit any part of the records the history is missed in the history updated tabs in yetiforce 4.2.0
#### Expected Behavior

I expected same as the stable version the histories would be shown in the updates tabs 
#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Chrome , Safari
* Environment name and version: Linux 3.10.0-614.10.2.lve1.4.48.el7.x86_64 #1 SMP Sun May 14 17:49:50 EDT 2017 x86_64
* Operating System and version: OS X

The system report is also attached

**Comment by mariuszkrzaczkowski** [comment]
Can you try to trigger it on gitdev?

**Comment by paula-w** [comment]
Please take a look at [this article](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs) and provide us with the missing info.

**Comment by mjapple** [comment]
@mariuszkrzaczkowski it is working fine in the gitdev
