### ISSUE TITLE
Phone prefix set to afgan

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5599]
Hi,

Running 4.2.514.   All phone numbers are defaulted to Afganastan, is it possible to change the default to United Kingdom instead?

**Comment by mariuszkrzaczkowski** [comment]
Yes, this is possible, but there is no configuration panel yet.
You can do this in the database, changing the sort order.
This change will be visible everywhere in the field of the phone and in the country field.
```sql
UPDATE `u_yf_countries` SET `sortorderid` = '0' WHERE `name` = 'United States'; 
```
![2017-11-30_21-43-17](https://user-images.githubusercontent.com/10198654/33453983-b5c36824-d617-11e7-83a6-92d5389baf3a.png)
![2017-11-30_21-44-33](https://user-images.githubusercontent.com/10198654/33453986-b7af0800-d617-11e7-80a3-f803b4a69f2f.png)

**Comment by nzi200779** [comment]
Is there a way i can add the countries table as a picklist field on Opportunities Module?

**Comment by vovpff** [comment]
@alextovey try here too
![image](https://user-images.githubusercontent.com/8545791/36979614-20216ccc-2099-11e8-988b-f15b8396273a.png)

**Comment by blu-IT** [comment]
> ... is it possible to change the default to United Kingdom instead?

Is the method described above still the way to change default prefix or is there some config option in the meanwhile (this ticket is from 2017)?

Thanks!

**Comment by js325** [comment]
I am on v5.3 and this seems to still be the only method of changing the default.
It seems to work on country fields but my default phone prefix has not changed. I have set 
sortorderid for Australia to 0 but US still defaults as the phone number field as you can see. 
Is there anything else that's needed to achieve this?

![yetiforce-default](https://user-images.githubusercontent.com/22556776/81130099-df6d5f80-8f89-11ea-9598-4aa4549e7655.png)

**Comment by blu-IT** [comment]
> I am on v5.3 and this seems to still be the only method of changing the default.
> It seems to work on country fields but my default phone prefix has not changed. I have set
> sortorderid for Australia to 0 but US still defaults as the phone number field as you can see.
> Is there anything else that's needed to achieve this?

Strange, it worked for me. Can you send a screenshot of your database table with the sortorder?

**Comment by rskrzypczak** [comment]
it depends on language
![lang](https://user-images.githubusercontent.com/10221999/81139806-6826d400-8f67-11ea-9130-dd0d325eeadf.gif)

**Comment by js325** [comment]
Heres a screenshot of db table
![yeti-db](https://user-images.githubusercontent.com/22556776/81164245-698de600-8fd3-11ea-8393-968ddc70655e.PNG)

I also created an en-AU language but still get the US default on phone numbers;
![yeti-lang](https://user-images.githubusercontent.com/22556776/81164451-ba9dda00-8fd3-11ea-8fe0-0df1e0b45e93.PNG)

**Comment by blu-IT** [comment]
@js325 

OK and which language is set in your personal profile? If en-US then try switching to en-AU and see if the behavior changes.
From your screenshot I can only see that (the system wide?) setting ist still en-US.

**Comment by js325** [comment]
Good pickup! That worked.
It still needed to be changed under user preference.
Thanks heaps.
