### ISSUE TITLE
Email not showing on records

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5601]
Morning, Version 4.2.514 on ubuntu with all server config setup as expected. 

We are not seeing contact's email on the main screen but go in the record and they are showing. Is this something that needs to be tweaked on the db or in the config? If so how can i do this.

Please see gif.
![emails](https://user-images.githubusercontent.com/22075161/33475432-5576400e-d676-11e7-86c9-1d2ee82ebd83.gif)

**Comment by alextovey** [comment]
@bpabiszczak @paula-w 
Found that it does not ignore a space after emails just removes the email itself. Can this please change on next release just removes the space on the email output please.

**Comment by mariuszkrzaczkowski** [comment]
4.2.583
![image](https://user-images.githubusercontent.com/10198654/33573038-fee58d32-d934-11e7-9bbe-cab96b9f2ae2.png)

**Comment by alextovey** [comment]
@mariuszkrzaczkowski you got the link for the update?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/f1f3d28de87724a66c46d0a5276974ba15063178

**Comment by alextovey** [comment]
@mariuszkrzaczkowski thank you :D 💃
