### ISSUE TITLE
Managers/Contacts field now showing on accounts/clients field summary

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5602]
Hi,

The managers are not showing once tagged to the client, as they were in version 4.2. as seen in this gif. Is it possible to re-enable this function?

Just seems to have happened in the latest release. Could be caused by modules needing to be re-registered or relations inputting but unsure. Would be good to get some idea's thrown at me.
![managersemail](https://user-images.githubusercontent.com/22075161/33476995-e281768a-d67b-11e7-9cf7-af1170d15dc0.gif)

**Comment by mariuszkrzaczkowski** [comment]
Try this:
Check the logs
delete and add widget

**Comment by bpabiszczak** [comment]
You have modified the system, you need to check it in its logs. You need to check if the same error occurs on gitdeveloper.
