### ISSUE TITLE
RC 4.2 - 4.3 - Currency symbol not displaying correctly in fields

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5605]
Hi,

the currency fields are not displaying the symbols in the fields i.e. $

Instead they are showing &#36;

See attached image
![currency](https://user-images.githubusercontent.com/10598886/33488633-31de091e-d6a9-11e7-9fd5-ffedabe84a41.png)

**Comment by alextovey** [comment]
@PercyP which module you running this on? I'll have a look as i've re written my currency field file to show GBP instead of dollars

**Comment by PercyP** [comment]
@alextovey 
it is in any module with a currency field. Ideally it should use the symbol of the default currency?

**Comment by alextovey** [comment]
@PercyP did you change the user's variables in their profile to show GBP, it auto changed after the last update. if not then it's a case of changing the language file to display £ instead of $

**Comment by PercyP** [comment]
@alextovey 
mine is in Australia dollars it appears to be missing in yetiforce. I changed the user preferences to GBP and USA dollars and they work fine - its just the Australian one that doesn't work.

**Comment by PercyP** [comment]
I was wrong, it only seems to display the symbol if GBP is set in user's preferences the US dollar doesn't show either

**Comment by PercyP** [comment]
I just tried to add Australia Dollars in the yetiforce developer (under System Tools - Currencies) and it throws an error and hangs:
![error](https://user-images.githubusercontent.com/10598886/33554236-d0703af6-d8f3-11e7-8521-539dce74d819.png)

**Comment by alextovey** [comment]
Message is that you've already got that in there. I would go through sql and send me the output for the vtiger_currency_info as it seems aud is in there twice maybe why it is not working.

**Comment by PercyP** [comment]
Hi @alextovey ,

that image I submitted was from the developer version of yetiforce so its in their database. I only have one AUD in mine. The only currency that works is GBP oddly enough

**Comment by alextovey** [comment]
@PercyP 
hmm i will do a test on my test system.

**Comment by alextovey** [comment]
@PercyP nope not working on mine either. infact i cant even get into the currency update tab on the admin section.

**Comment by PercyP** [comment]
@alextovey 
yes same with my instance. The yetiforce developer version opens at least, but it produces the error screen I posted earlier
