### ISSUE TITLE
RC 4.2 - 4.3 Multi image not working

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5606]
Hi,

I had the Multi image custom field created by yetiforce for my system and it no longer works after the last 2 upgrades I have tested. 

I can still select add image and upload it but they are not displaying. If I click on them they freeze the screen. They are not visible in the summary mode (like they used to be) either. 

I did try enabling the multiimage in modules/Settings/LayoutEditor/models/module.php by removing the // from the following line of code:

public function getAddSupportedFieldTypes()
	{
		return [
			'Text', 'Decimal', 'Integer', 'Percent', 'Currency', 'Date', 'Email', 'Phone', 'Picklist', 'URL', 'Checkbox', 'TextArea', 'MultiSelectCombo', 'Skype', 'Time', 'Related1M', 'Editor', 'Tree', 'MultiReferenceValue', 'CategoryMultipicklist', 'MultiImage'
		];

But this has no impact. 
I have to have this working in my system, so are there additional steps I need to perform to achieve this?

Kind regards

**Comment by migoi** [comment]
That's broken in two places:

Just for the display:
try changing modules/Vtiger/files/Basic.php line 32

from
~~~ php
$field = $request->getByType('field', 1);
~~~

to
~~~ php
$field = $request->getByType('field', 2);
~~~

reason: the generated url for a image looks like
~~~
/file.php?module=Accounts&action=MultiImage&record=212&attachment=12&field=2659
~~~
so *"field"* is numeric, but type "1" only allows words.

Thats just a workaround and you should wait for an offical fix.

**Comment by migoi** [comment]
Ah and the second is the creation.
It simply does not work.

Reason: (modules/Vtiger/uitypes/MultiImage.php)
~~~php
	public function getEditViewDisplayValue($value, $recordModel = false)
	{
		return $recordModel ? $this->getMultiImageQuery($value, [], false)->all() : [];
	}
~~~
return an **array** - thats ok but will cause trouble. The value will be auto-converted to a string in the template. But the result is **"Array"** and not a **String** with a list of value.

Change to 
~~~php 
	public function getEditViewDisplayValue($value, $recordModel = false)
	{
		$data = [];
		if (!empty($recordModel)) {
			$data = $this->getMultiImageQuery($value, [], false)->all();
		}
		return implode(',', $data);
	}
~~~

But there is another glitch: there is an empty "trashcan" for delete of a non existant entry in the form. That needs to be fixed in the .tpl file (php / html mix).

**Comment by PercyP** [comment]
Hi @migoi 

thanks for this. I shall see if the developers respond before trying to do a temporary fix as there may be more things wrong in addition to this?

Thank you so much for taking the time to post - most appreciated

**Comment by PercyP** [comment]
I just tried to apply those fixes in RC7 update but still doesn't work properly unfortunately.

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/5535
