### ISSUE TITLE
Question: How to customise the default theme

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5609]
Hi,
I am trying to create a custom theme (based on the Twilight one). This is what I have done so far:

1. Copied the Twilight theme folder and called it "newtheme"
2. To display the skin in the dropdown options (in User settings) go to crm/modules/vtiger/helpers/util.php

At around line 364 I added the new skin here:
public static function getAllSkins()
	{
		return ['twilight' => '#404952', 'modern' => '#0d9605', 'newtheme' => '#00b3d4'];

3. Opened the style.css inside the new theme folder and changed the colours (in my case using sharepoint designer) then saved it in my newtheme.

My question is, I have managed to change all colours except for the sub-menus, I cannot find the code for these as they don't seem to appear in the style.css.

**Comment by alextovey** [comment]
Would be nice to know how to change the theme...
