### ISSUE TITLE
Missing button reactive record v4.2.583

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5612]
![cant_reactive](https://user-images.githubusercontent.com/19627226/33510623-bf3eb41a-d740-11e7-9b78-f3bcba4bf177.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/92e14651c59270c5799a53a0a023e3e979435566
