### ISSUE TITLE
Module access broken after update RC2 and v4.2.583

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5613]
if leads of is group

#### Actual Behavior
![bug_module_access](https://user-images.githubusercontent.com/19627226/33511627-a712b5f2-d750-11e7-836d-1b28d07cb891.png)

On https://gitdeveloper.yetiforce.com

![bu_module_access_gitdev](https://user-images.githubusercontent.com/19627226/33511645-fbee93b6-d750-11e7-8849-56346789f9ec.png)

#### Log
`Stack trace:
#0 /home/zzz/vendor/yetiforce/UserPrivilegesFile.php(118): App\PrivilegeUtil::getUserModuleSharingObjects('Leads', 5, Array, 'H40', Array, Array)
#1 /home/zzz/modules/Settings/SharingAccess/models/Module.php(165): App\UserPrivilegesFile::createUserSharingPrivilegesfile(5)
#2 /home/zzz/modules/Settings/SharingAccess/models/Rule.php(384): Settings_SharingAccess_Module_Model::recalculateSharingRules()
#3 /home/zzz/modules/Settings/SharingAccess/actions/IndexAjax.php(56): Settings_SharingAccess_Rule_Model->save()
#4 /home/zzz/include/runtime/Controller.php(90): Settings_SharingAccess_IndexAjax_Action->saveRule(Object(App\Request))
#5 /home/zzz/modules/Settings/SharingAccess/actions/IndexAjax.php(24): Vtiger_Controller->invokeExposedMet in /home/zzz/vendor/yetiforce/PrivilegeUtil.php on line 1016`

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Duplicate #5238  fixed in update package from 4.2.0 to 4.2.613 RC6
