### ISSUE TITLE
Show incorrect role v4.2.583

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5614]
v4.2.583
![1b](https://user-images.githubusercontent.com/19627226/33511744-77d2dc10-d753-11e7-9002-49a9f5302579.png)
![2b](https://user-images.githubusercontent.com/19627226/33511745-782a55e4-d753-11e7-906e-12a4485a2ee1.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/da778a6e01b87793cc409253bf6a760c64f6e6b4
