### ISSUE TITLE
RC2 4.2 - 4.3 No 'add' image on roundcube email

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5619]
Hi,

I can't test this on the developer version as don't have an email login. 
When I open an email, the add symbols are missing from the icons used to attach email to a component (see image)
![noimage](https://user-images.githubusercontent.com/10598886/33550643-a1b05bd6-d8e6-11e7-99ff-37c6cb87f905.png)

**Comment by kpaulaha** [comment]
I have them there on  4.2.583
![email](https://user-images.githubusercontent.com/10330264/33553153-4a89b806-d900-11e7-89d5-dd99f6d08236.png)

**Comment by PercyP** [comment]
I tested it on the developer yetiforce and they are visible there, so it is my issue. I had a custom template installed and yetiforce added the mailscanner for me, there is something not working correctly since the restructuring of the folders, moving to the new public_html etc. and so my roundcube can't seem to load the glyphicons

**Comment by PercyP** [comment]
Hi,
this is the same issue as was reported/fixed here: https://github.com/YetiForceCompany/YetiForceCRM/issues/5073

I have tried to apply the fix as shown there but it doesn't work for me.

**Comment by PercyP** [comment]
I was wondering, the changes you added now point to the public_html folder:
$this->include_stylesheet($this->rc->config->get('public_URL') . 'layouts/basic/skins/icons/userIcons.css');
$this->include_stylesheet($this->rc->config->get('public_URL') . 'libraries/bootstrap3/css/glyphicon.css');

Can I ask, how would yetiforce be able to distinguish between the regular public_html and the one that sits inside yetiforce/public_html

I am wondering if this is why my icons are not showing because it is looking at the main public folder?
