### ISSUE TITLE
Import contacts causes an error 

### ISSUE THREAD

**Issue by elchris82** [YetiForceCompany/YetiForceCRM#5622]
Importing contacts from CSV fails with the following error message: 

    require_once(include/Webservices/VtigerModuleOperation.php): failed to open stream: No such file or directory in /var/www/html/crm/include/Webservices/Utils.php on line 384

The page has to be reloaded to continue working with the CRM. No contacts were imported.

**Comment by kpaulaha** [comment]
Working ok on  v. 4.2.583

**Comment by mariuszkrzaczkowski** [comment]
Duplicated #4827

**Comment by vog** [comment]
What does version "4.2.583" mean? There is neither a release tag nor a tarball for anything beyond version "4.2.0".

Does this refer to the latest Git commit? If so, does it refer to the "stable" or the "developer" branch?

**Comment by mariuszkrzaczkowski** [comment]
developer branch
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/version.php

**Comment by vog** [comment]
Thanks!
