### ISSUE TITLE
RC2 4.2 - 4.3 Currency update error and menus stop working

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5623]
I have just tested this in developer version. If you go to Integration - Currency Update it produces a white screen with error message. Also, this stops the menus from working. Click on a menu link and nothing happens:
![currency_001](https://user-images.githubusercontent.com/10598886/33568434-5bf3e576-d91e-11e7-86d4-e3f89c12caff.png)

**Comment by kpaulaha** [comment]
Working on our 4.2.588
![currency](https://user-images.githubusercontent.com/10330264/33598541-dc3b428c-d9ab-11e7-9c84-6cfe569f7067.png)

**Comment by mariuszkrzaczkowski** [comment]
Test the RC5 upgrade package

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 
Just tested - issues with currency are resolved in my version - thank you! Now just testing this release v5
