### ISSUE TITLE
Product image in PDF

### ISSUE THREAD

**Issue by akromdoo** [YetiForceCompany/YetiForceCRM#5630]
Hello recently i update from Yetiforce 3.8 to 4.2 in product PDF i hade image insert for each product.
I made additional fields and after uploading pictures i copied picture link in fields and it worked perfectly.

Now after update there is base64 encoding and i can not get it to work is there some way to disable encoding and just get url of images. Or if there is some other solution it would work.

**Comment by akromdoo** [comment]
[test.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/1544503/test.pdf)

Hello i made an test PDF file for product with image. I manage to bypass recent problem that i had before with changing the text field with text area but it dos not show the whole picture like on pdf i attached. I also tried from my Yetiforce also coveting pictures in other formats but problem the same.

Dose anyone have any solution.

**Comment by mariuszkrzaczkowski** [comment]
Can you describe step by step how you built a pdf template, and how to add image files

**Comment by akromdoo** [comment]
In version 3.8 i made in products module additional text field image url. After uploading image with upload button i saved the product and after saving i copied image url and paste it in field image uri.
I made pdf template for products in editor that is provided with text and forms.
I placed the image that i went to image icon and in image link field i copied image url like $imageurl$ set the dimensions and it worked.
For each product i made PDF i hade image for each individual product. 
Now in 4.2 version i had to replace image url text field with text area as text field is only for 255 characters. All other is the same as in 3.8 but as base64 encryption in long i think there is a problem in processing PDF as it only processes half of image.
Is there a way to simplify that and also is it possible to make more upload buttons like 12 of them and i could put just string of upload picture in pdf like logo for exemple.
I hope you understand what i wrote.
Thanks

**Comment by KatarzynaUlichnowska** [comment]
Hello, there was no version 3.8, so we don't know about which version you are talking about, maybe 3.4?
The data parsing mechanism in PDF has been changed and you have to rebuild what you created so that it will work with the new mechanism.

**Comment by akromdoo** [comment]
Hello Katarzyna,

To be totally honest you could just close the ticket without response like that. I know it is a free script and it is not a bug in your script but i needed your help for my issue and expected at least some direction not that after 15 days your answer is the thing i already know.

I think we all wasted time for discovering water is still water and not wine.

**Comment by KatarzynaUlichnowska** [comment]
Unfortunately, we do not provide programming advice [we charge for that] and unfortunately answering your question first requires analyzing what has been changed, then analyzing what needs to be improved and it will probably take 1-4 hours. We recommend buying one of our support packages, and we will answer after 2-3 days.

**Comment by akromdoo** [comment]
Thanks now that is more expected answer.

Have a great holidays!

**Comment by KatarzynaUlichnowska** [comment]
Thank you and the same to you! Happy Holidays :)

**Comment by ldgbc** [comment]
@akromdoo 
There is a few thread about Image and PDF Export, as far as I remember it is not possible at the moment. Plan to have it implemented in v4.5 or v5.0 apparently.

**Comment by mariuszkrzaczkowski** [comment]
> $(record : image|100px|50%)$

**Comment by ldgbc** [comment]
Look like all Image field can use that 

    $(record : image|100px|50%)$

I wonder if it possible to use that with documents .jpg/png/other image types.
