### ISSUE TITLE
Gmail SMTP issue

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5631]
Yesterday I checked what I don't receive any emails from my CRM.

I checked emails to send and found about 15 emails with status `Error while sending`

After that I checked my SMTP config:

![image](https://user-images.githubusercontent.com/8545791/33702967-f1772846-db36-11e7-8e84-7e8683981745.png)

After clicking edit and saving I receive next error.

```
Error!!!

SMTP Error: Could not connect to SMTP host.
 SMTP ERROR: QUIT command failed: MIAFOc8X%prB'ABմ#G2Ҟ8_|9-NUlKj>6pfvOwqh9/8g7LX[H|7C	=;ZU;瘆1,2
 u4"Bw?Gy5(H^;*Zhp}h4,)w%J&׊e=	~ݚ6r5Gv)An
 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```

Solution is to change mailer type from `smtp` to `sendmail`

What is a cause of this problem? Anybody has ideas?

**Comment by alextovey** [comment]
google are changing their encryption becuase of GDPR. however it's not come in to effect yet. I suggest there was maybe a issue on gmail have a look at their server status.

**Comment by bpabiszczak** [comment]
GitDeveloper use Gmail

![image](https://user-images.githubusercontent.com/10197525/33768335-debff526-dc25-11e7-8f00-811823623b3c.png)

Check your Gmail configurations and server configurations.

**Comment by vovpff** [comment]
@bpabiszczak I'm don't use roundcube. I'm use only outcoming emails trough gmail smtp and has this issue but last 2 years mailing from CRM works well.

**Comment by alextovey** [comment]
try removing the credentials and then adding a hotmail then re adding to gmail.

**Comment by vovpff** [comment]
@alextovey I don't have hotmail.

**Comment by skramanzia** [comment]
@alextovey, try this:
- Change port 587 to 465
- Change "Safety protocol" to ssl

**Comment by mariuszkrzaczkowski** [comment]
Look here https://github.com/PHPMailer/PHPMailer/issues?utf8=%E2%9C%93&q=is%3Aissue+gmail

**Comment by bpabiszczak** [comment]
and here:
1. https://stackoverflow.com/questions/47634630/smtp-error-could-not-connect-to-smtp-host-phpmailer-php
2. https://github.com/PHPMailer/PHPMailer/issues/1255

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/33872021-5fa5a0ae-df15-11e7-9671-d5a2499fa89a.png)
