### ISSUE TITLE
RC 4.2 - 4.3 Products problem in quoations, orders module. 

### ISSUE THREAD

**Issue by technologiegalwaniczne** [YetiForceCompany/YetiForceCRM#5632]
Hi. I have jut updated from 4.2 to 4.3 RC and  few problems apeared. 

1. When editing an quotation instead of product names line of code is apearing. 
![image](https://user-images.githubusercontent.com/29600665/33714174-58201410-db4e-11e7-80c9-54952d8be4f1.png)
2. When pushing "add product" nothing happens. The new line for the next product does not appear. 

I have the same issue in the  quotations as well as the order module.

Please help.

Best regards
Maciej Janiak

**Comment by mariuszkrzaczkowski** [comment]
Duplicate #5578
