### ISSUE TITLE
Question: In version 4.3 will be avabile an option similar to recording control to colorate fields?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5635]
#### Issue

The colored fields is a good function avabile on YetiForce.

#### Actual Behavior

I know that function was deprecated on version starting from 4.2
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
really lines coloring very cool function. Is it possible to combine lines coloring with colored picklist values?

**Comment by KatarzynaUlichnowska** [comment]
At the moment, it is possible to color picklist values, not lines. 
We don't plan to introduce anything else in terms of coloring in 4.3.
