### ISSUE TITLE
how to create a child theme?

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5637]
Hey,

Is it possible to create a child theme so I don't have to keep updating the language files? each time i update the system. For instance, accounts = Client, contacts = managers, tax = vat.

I spend most of my time faffing around with these files getting them back to how my non profit company wants them.

**Comment by vovpff** [comment]
@alextovey
1. add new language trough Language manager
2. Copy all current data from en_en to your language folder
3. Copy your language folder from `/languages` to this folder: `custom/languages/your_lang/`
4. Go here https://github.com/YetiForceCompany/YetiForceCRM/blob/ea3588766b17433cef506cf453cc2f7584b8816e/config/performance.php#L66 and change to true
5. Change your users language to your_language

**Comment by mariuszkrzaczkowski** [comment]
> 2. Copy all current data from en_en to your language folder

Do not copy, just add changes that are different from the original files

**Comment by PercyP** [comment]
@alextovey 
I just created a new language in the language manager and set it as the default, then added all the changes there. It doesn't get altered when I update.

**Comment by alextovey** [comment]
ohh thank you guys. @PercyP can you send me a copy or snippet so i can get an idea please.

**Comment by alextovey** [comment]
@mariuszkrzaczkowski i've done that but it's not showing up :S am i missing something I had to manually create the custom/languages/en_en folder
but it's not showing in the users section.

**Comment by alextovey** [comment]
Thank you got it :D Epic!
