### ISSUE TITLE
QUESTION: How to add a summary view on custom modules?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5641]
#### Issue

I have created new custom modules.

#### Actual Behavior

I want to add custom summary view like on Accounts and Contacts module.
#### Expected Behavior

I need a documentation of how to do this.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version:Google Chrome
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@cltvchannel gi here https://gitdeveloper.yetiforce.com/index.php?module=Widgets&parent=Settings&view=Index&block=2&fieldid=58, choose your module and add needed widget

**Comment by PercyP** [comment]
Hi @cltvchannel 

do you mean these summaries in the record page:

![summary](https://user-images.githubusercontent.com/10598886/33804115-0e39079a-dd96-11e7-9333-8024923b4cc5.png)

If yes, just go to Standard Modules - Module WIdgets and then add the sections you want to show on the record pages of your custom module (select your custom module from the list first. Just check out one of the existing modules layouts that you like and replicate it

**Comment by cltvchannel** [comment]
Thanks !
