### ISSUE TITLE
OSSPasswords

### ISSUE THREAD

**Issue by mikelakat** [YetiForceCompany/YetiForceCRM#5643]
#### Issue
The module OSSPasswords is not saving the data. When you click save not responting.

#### How to trigger the error

1. Click Save

#### Your Environment

* YetiForce Version used: 4.2
* Browser name and version: Chroe
* Environment name and version: -
* Operating System and version: Win 10

**Comment by mariuszkrzaczkowski** [comment]
Check the latest development version
Can you try to trigger it on gitdev?

**Comment by bpabiszczak** [comment]
On gitdeveloper work
![image](https://user-images.githubusercontent.com/10197525/33857019-53e90d32-deca-11e7-8e12-62deb3761821.png)
