### ISSUE TITLE
How to enable payment balance adjustments in invoices/Payments in

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5644]
Hi,
I asked a similar question a while back and never managed to work out a solution:
https://github.com/YetiForceCompany/YetiForceCRM/issues/4626

I want to be able to show part payments for an Invoice that has been issued so the following process happens:

1. I create an invoice for $400 and send it to the client
2. The client pays me $100
3. I create a Payments in for the amount that has just been paid to me and use the 1:M field I created to relate this payment to the invoice

In the previous post I was told 

"To calculate the balance in an invoice you can use the Payments In module. The system should automatically calculate the balance - if the clean version of the system doesn’t do that then it’s probably enough to enable this option."

Does anyone know what needs to be enabled? Has anyone got something like this to work? 

There is nothing in the Payments In to enable - no disabled fields etc. 

Kind regards

**Comment by bpabiszczak** [comment]
enable = a programmer must do it

**Comment by ldgbc** [comment]
Hi @PercyP I'm beginning to test out the Sale Invoice and PDF export too.

First I discover that Discount need to be Enable to for it work but not that not relate to this topic.
What I wanted to ask if you figure out how to do this?

I initially thought, why not add another service and products call "Partial Payment", and use a "negative value", e.g. -$500 but I got the error, "negative value can't be use". But that idea didn't work and here I am, searching issue to find solution.

How are you tackling this issue currently?

**Comment by dechutvilhur** [comment]
> enable = a programmer must do it

Hello, same issue here in 2023, can you please show me how to do this ?
