### ISSUE TITLE
Where is the language string for the new Discount block on Invoices?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5645]
There are a couple of language strings in the invoices Discount block that still refer to the Tax Discount. 

For example:
![discount1](https://user-images.githubusercontent.com/10598886/33804060-1825e56c-dd95-11e7-901c-000a0c4ce7ef.png)

And here:

![discount2](https://user-images.githubusercontent.com/10598886/33804085-702fae96-dd95-11e7-9d9b-5db5cff3be76.png)

![discount3](https://user-images.githubusercontent.com/10598886/33804088-76c5f210-dd95-11e7-87d1-cd1e252ff7a0.png)

**Comment by vovpff** [comment]
@PercyP I'm not sure but try to select `Vtiger` in Language Managerment tab

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/a1e6bad89c3d6604792ae5313cd69dbe8cf362fc/layouts/basic/modules/Vtiger/inventoryfields/EditViewDiscountMode.tpl#L4

https://github.com/YetiForceCompany/YetiForceCRM/blob/a1e6bad89c3d6604792ae5313cd69dbe8cf362fc/layouts/basic/modules/Vtiger/InventoryDiscounts.tpl#L9

https://github.com/YetiForceCompany/YetiForceCRM/blob/a1e6bad89c3d6604792ae5313cd69dbe8cf362fc/layouts/basic/modules/Vtiger/InventoryDiscountsType0.tpl#L6

https://github.com/YetiForceCompany/YetiForceCRM/blob/a1e6bad89c3d6604792ae5313cd69dbe8cf362fc/layouts/basic/modules/Vtiger/InventoryDiscountsType2.tpl#L5

https://github.com/YetiForceCompany/YetiForceCRM/blob/a1e6bad89c3d6604792ae5313cd69dbe8cf362fc/layouts/basic/modules/Vtiger/InventoryDiscountsType1.tpl#L6
