### ISSUE TITLE
QUESTION: How to set a default value to Document Title?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5648]
#### Issue

I have the document title field.
![documente](https://user-images.githubusercontent.com/30116021/33818845-f0875976-de4f-11e7-8f2c-07d0d7a43384.png)

#### Actual Behavior

I can't assign a default value to a system created field.

#### Expected Behavior

I want to assign a default value or automatically put the value from Record Number.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.2.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
This is the system field, it can not be changed.
