### ISSUE TITLE
QUESTION: File name/www open in browser

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5649]
#### Issue

I have File name/www field on Documents module.
![fieldname](https://user-images.githubusercontent.com/30116021/33819828-1c03d9bc-de55-11e7-87c0-adfa1401ba23.png)

#### Actual Behavior

Now when i click on it, ask me where i want to save it.

#### Expected Behavior

I want to preview in browser when i click on it. When attachament is .PDF file i want to preview it before saving.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.2.0
* Browser name and version: 
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
https://stackoverflow.com/questions/6293893/how-to-force-files-to-open-in-browser-instead-of-download-pdf

**Comment by cltvchannel** [comment]
And what files i need to change to implement this?

**Comment by bpabiszczak** [comment]
You can edit directly in the table [vtiger_fields], but I advise against!

**Comment by cltvchannel** [comment]
@bpabiszczak this table is located in yetiforce database?

**Comment by bpabiszczak** [comment]
YES.

**Comment by cltvchannel** [comment]
and this is the right way?

**Comment by bpabiszczak** [comment]
No. Correctly, the panel needs to be expanded! But who will pay for it?

**Comment by cltvchannel** [comment]
How much cost?

**Comment by bpabiszczak** [comment]
2-4 hours

**Comment by cltvchannel** [comment]
And for table module how much?

**Comment by bpabiszczak** [comment]
For table module? In table you can change yourself :] [5-10 min but I do not know if it will work]

**Comment by cltvchannel** [comment]
I need a professional work, not my work. I'm begginer.
I am able to pay for this.

**Comment by cltvchannel** [comment]
And i need posibility to make calculated fields.

**Comment by bpabiszczak** [comment]
describe exactly what you need and send us an email.

**Comment by cltvchannel** [comment]
ok. thanks!

**Comment by ldgbc** [comment]
@cltvchannel How did I miss this issue, tried searching for it. Anyway, read here if you haven't find the answer yet:
https://github.com/YetiForceCompany/YetiForceCRM/issues/7179
