### ISSUE TITLE
Table field

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5651]
#### Issue

I want to create a module where i need to add a table (similar to excel)

#### Actual Behavior

There is something similar avabile on invoice module.

#### Expected Behavior

I need a documentation about how i can add a table.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.2.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@cltvchannel when you create new module you must select `Extended module` for module type field.
![image](https://user-images.githubusercontent.com/8545791/33823713-19fc439e-de6d-11e7-9e0e-0a7c29d42a9c.png)

**Comment by vovpff** [comment]
@cltvchannel or you can change module type in future by clicking Basic switch near module selection to change it to advanced type

**Comment by cltvchannel** [comment]
Yes, i know that fields.
But what's happen when i want to add some calculations between that fields?

**Comment by vovpff** [comment]
@cltvchannel I think this functionality not implemented for this tyme
