### ISSUE TITLE
Module Builder for Yeti

### ISSUE THREAD

**Issue by GrtRmt** [YetiForceCompany/YetiForceCRM#5653]
Is there a module builder avaiilable as in Vtiger or JoForce ?
You can do a lot in Yetii but pparently you can't create any new modules.
I'm an insurance broker and I'd like to develop an Insurance CRM.
This will demand lots of customization and a module builder.

**Comment by vovpff** [comment]
@GrtRmt you can add self made modules by ourselves without any restrictions by standart tools included to system.

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/33852698-cb2495c4-debb-11e7-8f02-9bc3291af2af.png)

**Comment by GrtRmt** [comment]
Where can I find instructions to build modules ?
I have no programming knowledge and look voor a module builder as in Vtiger or JoForce.


Geert

Van: vovpff [mailto:notifications@github.com]
Verzonden: maandag 11 december 2017 21:37
Aan: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
CC: Geert | Remaut <geert@remaut.eu>; Mention <mention@noreply.github.com>
Onderwerp: Re: [YetiForceCompany/YetiForceCRM] Module Builder for Yeti (#5653)


@GrtRmt<https://github.com/grtrmt> you can add self made modules by ourselves without any restrictions by standart tools included to system.

**Comment by vovpff** [comment]
@GrtRmt https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8 try to add module by yourself by clicking Create ![image](https://user-images.githubusercontent.com/8545791/33881939-8612115a-df47-11e7-9361-9064304ad064.png) at right top corner

**Comment by GrtRmt** [comment]
Found it.
Tx


Geert

Van: vovpff [mailto:notifications@github.com]
Verzonden: dinsdag 12 december 2017 12:20
Aan: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
CC: Geert | Remaut <geert@remaut.eu>; Mention <mention@noreply.github.com>
Onderwerp: Re: [YetiForceCompany/YetiForceCRM] Module Builder for Yeti (#5653)


@GrtRmt<https://github.com/grtrmt> https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8 try to add module by yourself by clicking Create [image] <https://user-images.githubusercontent.com/8545791/33881939-8612115a-df47-11e7-9361-9064304ad064.png> at right top corner
