### ISSUE TITLE
Gantt print

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5654]
#### Issue

I need to print gantt from YetiForce.

#### Actual Behavior

Now, a print button or export to PDF is not avabile for Gantt.
#### Expected Behavior

I think a print option is needed.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.2.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-development-ideas
