### ISSUE TITLE
Header and footer in PDF dont work also sam with email signature

### ISSUE THREAD

**Issue by akromdoo** [YetiForceCompany/YetiForceCRM#5656]
I am using 4.2 version and in PDF when i insert header or footer after saving they transform to regular text as it also do with email signature.
![image](https://user-images.githubusercontent.com/34330433/33871389-a164dcb0-df12-11e7-8be3-d866473345e3.png)
and after saving it
![image](https://user-images.githubusercontent.com/34330433/33871450-db70ea52-df12-11e7-9d13-7e0a6e17b90c.png)

The same thing is with header or footer in PDF but also after making PDF the body text is power header text.

**Comment by mariuszkrzaczkowski** [comment]
duplicate #5468

**Comment by akromdoo** [comment]
I serched for that solution and couldend find any. 
Please tell me how do i update from 4.2 to 4.2.XXX as i cant find update file.
Thanks in advance.
