### ISSUE TITLE
[PL] Generator raportów

### ISSUE THREAD

**Issue by slawhodu** [YetiForceCompany/YetiForceCRM#5658]
Po reinstalacji na wersję 4 przypadku uruchomienia raportu wyrzuca błąd:
Catchable fatal error: Argument 2 passed to vtws_listtypes() must be an instance of Users_Record_Model, instance of Users given, called in /crm/include/Webservices/WebserviceField.php on line 275 and defined in /crm/include/Webservices/ModuleTypes.php on line 20

dodatkowo po reinstalacji jest problem w chrome (na Edge, IE, Firefox - chodzi):
504 little Server Error

The server cannot process the request due to a little internal error...

Dopiero po jakimś czasie wstaje także w Chrome....

**Comment by bpabiszczak** [comment]
Z tego co widzę to wczoraj poprawialiśmy coś w "starej paczce" aktualizacyjnej:
https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%203.x.x/3.4.0_to_4.0.0 

Może to rozwiąże problem, jednakże bez szczegółowych logów i po stronie apache i po stronie php/yetiforce to nie mamy jak pomóc.

W przypadku błędu z raportami, proszę sprawdzić na wersji GitDeveloper [tutaj: https://gitdeveloper.yetiforce.com/] bo może problem już rozwiązaliśmy.

**Comment by slawhodu** [comment]
Reinstalowałem dzisiaj do wersji 4.3...

**Comment by slawhodu** [comment]
Reinstalowałem dzisiaj na 4.3...

**Comment by bpabiszczak** [comment]
Nie rozumiem, to co piszesz w pierwszym poście to migrowałeś do 4.3 czy do 4.0?

**Comment by slawhodu** [comment]
było migrowane po kolei jak się pokazywały wersje. Problem pojawił się w wersji 4.0. Potem zgłosiłem, że nie mogę robić raportów. Zostało zapisane 'do zrobienia następnej wersji... więc podnoszę wersję w nadziei, że naprawione...

**Comment by bpabiszczak** [comment]
Czy błąd występuje na GitDeveloper?

**Comment by slawhodu** [comment]
Nie. Po aktualizacji na mojej instalacji...

**Comment by bpabiszczak** [comment]
Bez logów nic z tym nie da się zrobić. My musimy umieć błąd wywołać, jak go nie wywołamy, to nie wiemy co mamy poprawić. Musisz nam dostarczyć takie informacje, abyśmy mogli wywołać błąd po swojej stronie.
