### ISSUE TITLE
Can not change user information and password v4.2.628

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5660]
v4.2.628
Can't press button
![nh ch p man hinh 6](https://user-images.githubusercontent.com/19627226/33894149-d45e9174-df8f-11e7-9777-5c46371b4205.png)
![bug user](https://user-images.githubusercontent.com/19627226/33894179-e8064df2-df8f-11e7-8a39-ad9d79afeb7c.gif)

**Comment by yetiforce-wojtek77** [comment]
On developer website changing password is not allowed because of security.

**Comment by yetiforce-wojtek77** [comment]
Now you can edit my preference.

**Comment by ezbank** [comment]
test on my server not work :( .

**Comment by yetiforce-wojtek77** [comment]
It was fixed on #5718 please check again.
