### ISSUE TITLE
[PL] Moduły - Powiązania. Dlaczego brak przycisku "Dodaj relację"?

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5678]
#### Issue
Gdy w panelu administracyjnym przechodzę do Moduły - Powiązania, to nie mam przycisku "Dodaj relację" oraz możliwości usuwania powiązań.

Ta funkcja jest na GitDeveloper.
Dlaczego?

#### Your Environment

* YetiForce Version used: ver. 4.2.618
* Browser name and version: Chrome

Git Developer
![img1](https://user-images.githubusercontent.com/26583746/33959745-c14cca74-e048-11e7-82a0-f5c3eea43422.png)

U mnie
![img2](https://user-images.githubusercontent.com/26583746/33959855-20359052-e049-11e7-85d9-9062c0dd7d6f.png)

**Comment by netinteractive** [comment]
change in : config/developer.php

-	'CHANGE_RELATIONS' => false,		
+	'CHANGE_RELATIONS' => true,

**Comment by anderpydev** [comment]
Działa. Dzięki za pomoc.
