### ISSUE TITLE
[PL] Aktualizacja do 4.2.618 - biblioteka roundcube niedostępna

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5679]
#### Issue
Wykonałem aktualizację do wersji 4.2.618. Wszystko przebiegło pomyślnie.
Jednak po chwili dostałem info, że brak biblioteki roundcube. Status był "do aktualizacji".
Aktualizacja nie wykonuje się - mam status "niepobrana". Nic nie dzieje się gdy klikam na "Pobierz bibliotekę".

Brakuje mi na serwerze IMAP, ale wcześniej też go nie było i biblioteka roundcube działała.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
Biblioteka pobiera się tylko dla "pełnych" wersji np. 4.2.0, dla nie pełnych, należy ją pobrać i wgrać ręcznie do odpowiedniego folderu [przez FTP].
