### ISSUE TITLE
[PL] Pole powiązania 1:M - Nie działa dodawanie nowego rekordu (pola utworzone przed aktual.)

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5686]
#### Issue
Po aktualizacji z 4.2 do 4.2.618

Gdy klikam na "+" nie otwiera się popup z możliwością utworzenia nowego rekordu. Nic się nie dzieje.

Działa natomiast wyszukiwanie i usuwanie.

Na git developer działa. Co może być przyczyną? Czy to błąd, który został już naprawiony po udostępnieniu paczki update RC6?

#### Your Environment

* YetiForce Version used: 4.2.618
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

![ezgif-5-b5c2cc0d71](https://user-images.githubusercontent.com/26583746/33994094-7d370c78-e0d9-11e7-8f38-546e8990a954.gif)

**Comment by mariuszkrzaczkowski** [comment]
Wyczyść pamięć podręczną przeglądarki
