### ISSUE TITLE
[PL] Pole powiązania 1:M (Terminy) - Nie działa wyszukiwanie rekordu (pola utworzone po aktual.)

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5687]
#### Issue

1. Sprawdzone dla modułu powiązanego "Terminy":

Gdy klikam na "lupę" by wyszukać rekord dostaję komunikat w oknie popup.

Błąd!!!
Unable to load template 'file:modules/Vtiger/uitypes/ActivityPicklistFieldSearchView.tpl' in 'modules/Vtiger/PopupContents.tpl'

2. Sprawdzone:
Pole 1:M działa np. dla modułu "Dokumenty"

#### How to trigger the error

1. Utworzyć pole 1:M i powiązać moduł "Terminy"
2.
3.

#### Your Environment

* YetiForce Version used: 4.2.618
* Browser name and version: Chrome

![screenshot1](https://user-images.githubusercontent.com/26583746/33994336-714e3570-e0da-11e7-836c-742a987d09c0.png)

**Comment by mariuszkrzaczkowski** [comment]
potrzebne są dodatków informacje:
w jakim module utworzono pole
czy z panelu czy skryptem
zrzut ekranu  jak było dodawane pole 
sprawdzić  czy cos pojawilo sie w logach po dodaniu pola

**Comment by bpabiszczak** [comment]
W sumie to dokładny film jak wywołać to na wersji GitDeveloper.

**Comment by anderpydev** [comment]
Moduł: Korespondencja przychodząca.

1. Tworzę pole 1:M dla modułu Terminy w Korespondencji przychodzącej.
2. Gdy przejdę do tworzenia rekordu lub edycji w korespondencji przychodzącej i w polu Terminy Test chcę wybrać rekord i go przypisać dostaję wyżej wskazany błąd.

Wywołanie błędu na Git Developer (również występuje):

1. Tworzenie pola 1:M

![tworzeniepola-gitdeveloper-ezgif-5-752e231de4](https://user-images.githubusercontent.com/26583746/34070762-31dddc72-e26c-11e7-83d6-b7a422331350.gif)

2. Edycja rekordu w korespondencji przychodzącej:

![edycjarekordu-gitdeveloper-ezgif-5-752e231de4](https://user-images.githubusercontent.com/26583746/34070857-06befe76-e26d-11e7-9e59-c77010133918.gif)

PS: Sprawdzane tylko dla tego zachowania. Nie sprawdzałem jeszcze czy w innych modułach to występuje.

**Comment by anderpydev** [comment]
PS2: Błąd jest powtarzalny w innych modułach, sprawdziłem dla Kontrahentów i utworzenie pola 1:M dla modułu Terminy wywołuje ten sam błąd.

Gdy przypiszę pole 1:M dla np. modułu Dokumenty, wszystko działa poprawnie.
