### ISSUE TITLE
Parts not linked to storage incl stock not updated

### ISSUE THREAD

**Issue by Rosalems** [YetiForceCompany/YetiForceCRM#5690]
#### Issue
When completing a Good Received note its not updating my stock. 
I found out that when going to Storage the tab products does not have any parts linked to it when teh good are booked on stock

#### Expected Behavior
When using a test account on softaculous it can see that the parts should be linked to the Storage and then also update the stock levels

#### Your Environment

* YetiForce Version used: 4.2
* Its a fresh install from softaculous 
* The cron job works and have been set to ....cron/vtigercron.sh &> ..../cache/logs/cron.log

Do I need to setup another thing/setting as I tried this on 2 new installations with both the same behavior

Thanks in advance

**Comment by vovpff** [comment]
@Rosalems Are your storage active?

**Comment by Rosalems** [comment]
Hi,

Yes they are all active

**Comment by mariuszkrzaczkowski** [comment]
check if the error exists in the development version

**Comment by Rosalems** [comment]
Hi Where can i find the installation package for the development version?

**Comment by PercyP** [comment]
@Rosalems 
I think he means here: https://gitdeveloper.yetiforce.com/

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/archive/developer.zip

**Comment by Rosalems** [comment]
Hi thnx,

When I unzip this to the server and try to install it from the new folder I get the following error. any idea as what this means?

/*
Fatal error: require(): Failed opening required '/home/xxx/public_html/xxx/crm_yetiforce_dv1/vendor/composer/../sabre/uri/lib/functions.php' (include_path='.:/usr/local/php71/pear') in /home/xxx/public_html/xxx/crm_yetiforce_dv1/vendor/composer/autoload_real.php on line 67
*/

**Comment by mariuszkrzaczkowski** [comment]
> Download the latest version of CRM from GitHub: https://github.com/YetiForceCompany/YetiForceCRM/releases.
> NOTE: download the "complete" version (eg. YetiForceCRM-4.1.0-complete.zip), if you don't download the "complete" version you will have to use Composer before you install the system.

**Comment by Rosalems** [comment]
Hi

I downloaded the development version from the new URL you provided me yesterday but unfortunately I get the same error about line 67.

Anything else we can try or is it something needs to be fixed?

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/crm-installation
> Download the latest version of CRM from GitHub: https://github.com/YetiForceCompany/YetiForceCRM/releases.
> NOTE: download the "complete" version (eg. YetiForceCRM-4.1.0-complete.zip), if you don't download the "complete" version you will have to use Composer before you install the system.
