### ISSUE TITLE
Translation file does not wotk with PDF export

### ISSUE THREAD

**Issue by Rosalems** [YetiForceCompany/YetiForceCRM#5694]
#### Issue
When you create a PDF out of an Quote the translation file does not get used to print the labels. On the pdf the field name will be printed instead of the setup that have been done on the translation file

#### Actual Behavior
Source the label from the field 

#### Expected Behavior
It should source the translation from the languages translation file

#### Your Environment
* YetiForce Version used: 4.2

**Comment by mariuszkrzaczkowski** [comment]
check if the error exists in the development version

**Comment by Rosalems** [comment]
Hi Where can i find the installation package for the development version?

**Comment by bpabiszczak** [comment]
Test here [https://gitdeveloper.yetiforce.com/] this is the best place.
