### ISSUE TITLE
[PL] Pole z wielokrotnym zaznaczeniem - nie wyświetla wartości w podglądzie

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5695]
#### Issue
Gdy mam pole z wielokrotnym zaznaczeniem, to po wybraniu kilku pozycji i zapisaniu, wartości nie wyświetlają się na podglądzie rekordu.

Na git developer to działa.

Nie wiem dlaczego u mnie w konsoli chrome pojawiaj się ten błąd (na gitdeveloper ich nie ma):

`/index.php?module=LettersIn&view=Detail&record=117&mode=showDetailViewByMode&requestMode=full&tab_label=LBL_RECORD_DETAILS:1 Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.`

![multi-zaznaczenie-ezgif-5-bbff81f9c2](https://user-images.githubusercontent.com/26583746/34008540-f8929adc-e105-11e7-91f6-2cfb95c53e4d.gif)

#### Your Environment

* YetiForce Version used: ver. 4.2.618
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Z komunikatu wynika że twój serwer dwa razy wysyła nagłówek X-XSS-Protection a nie może dlatego to nie działa. 
https://stackoverflow.com/questions/36329776/why-this-error-in-dev-console-of-chrome-when-using-x-xss-protection#answer-40445835

**Comment by anderpydev** [comment]
Naprawiłem X-XSS. Na serwerze mam komercyjne reguły ModSecurity, dlatego dwa razy był wysyłany nagłówek. 

Pomógł wpis w htaccess:
Header unset X-XSS-Protection

Nadal jednak nie wyświetlają się wartości w polu. Teraz mam komunikat:

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

`

  |open | @ | csrf-magic.js:33
  | send | @ | jquery.min.js:9050
  | ajax | @ | jquery.min.js:8642
  | _request | @ | Connector.min.js:2
  | request | @ | Connector.min.js:2
  | saveFieldValues | @ | Detail.min.js:2
  | k | @ | Detail.min.js:2
  | i.handler | @ | jquery.ba-outside-events.min.js:9
  | dispatch | @ | jquery.min.js:4723
  | elemData.handle | @ | jquery.min.js:4535
  | trigger | @ | jquery.min.js:7793
  | jQuery.event.trigger | @ | jquery-migrate.min.js:493
  | triggerHandler | @ | jquery.min.js:7867
  | (anonymous) | @ | jquery.ba-outside-events.min.js:9
  | each | @ | jquery.min.js:351
  | each | @ | jquery.min.js:144
  | f | @ | jquery.ba-outside-events.min.js:9
  | dispatch | @ | jquery.min.js:4723
  | elemData.handle | @ | jquery.min.js:4535

`

**Comment by bpabiszczak** [comment]
Masz niestandardową konfiguracje, rozwiązanie problemów to wejście na serwer programisty/administratora i zmienienie tego co powoduje problemy. Takie usługi realizujemy odpłatnie.

**Comment by anderpydev** [comment]
Okej. Na takiej samej konfiguracji serwera była wersja 4.2 stable i nie było takich komplikacji, stąd jestem zaskoczony tymi błędami i Twoją sugestią o niestandardowej konfiguracji. 

Ten komunikat w konsoli występuje również na git developer
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

Tam jednak wszystko działa. Także być może faktycznie to kwestia czegoś na serwerze.

w logach phpError.log mam:

`[18-Dec-2017 15:06:45 Europe/Sarajevo] PHP Warning:  Invalid argument supplied for foreach() in /home/mika/domains/mika.areocrm.pl/public_html/modules/Vtiger/widgets/RelatedModule.php on line 21
[18-Dec-2017 15:06:45 Europe/Sarajevo] PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /home/mika/domains/mika.areocrm.pl/public_html/vendor/yetiforce/Purifier.php on line 360
[18-Dec-2017 15:06:45 Europe/Sarajevo] PHP Warning:  Invalid argument supplied for foreach() in /home/***/public_html/vendor/yetiforce/Field.php on line 186
[18-Dec-2017 15:06:45 Europe/Sarajevo] PHP Warning:  Invalid argument supplied for foreach() in /home/***/public_html/vendor/yetiforce/Field.php on line 186
[18-Dec-2017 15:06:46 Europe/Sarajevo] PHP Warning:  Invalid argument supplied for foreach() in /home/***/public_html/vendor/yetiforce/Field.php on line 186
[18-Dec-2017 15:06:46 Europe/Sarajevo] PHP Warning:  Invalid argument supplied for foreach() in /home/***/public_html/vendor/yetiforce/Field.php on line 186
`
Dziękuję za odp.
Pozdrawiam

**Comment by mariuszkrzaczkowski** [comment]
Takie błędy pojawiają się po aktualizacji systemu i nie skonfigurowaniu poprawnie widgetów.

**Comment by bpabiszczak** [comment]
Czyli usunięcie wszystkich widżetów i dodaniu na nowo ?

**Comment by anderpydev** [comment]
Tzn? Czytałem info w paczce aktualizacji, ale nie do końca rozumiem, o co chodzi z tą konfiguracją widgetów. Właśnie je usunąłem i dodałem na nowo po aktualizacji. Bo chyba o to chodziło?

**Comment by mariuszkrzaczkowski** [comment]
Widget "RelatedModule" na podsumowaniu rekordów został przebudowany i trzeba go wy-edytować i ustawić nowo dodane parametry których wcześniej nie było.

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/34111112-0fa2794e-e409-11e7-87f1-0c343fcffa03.png)
![image](https://user-images.githubusercontent.com/10198654/34111147-376b78fe-e409-11e7-9cf2-22be38e28f18.png)

**Comment by anderpydev** [comment]
Okej. Potwierdzam. Powtórzyłem czynność z usunięciem i dodaniem widgetów. Chyba coś za pierwszym razem poszło nie tak, jak robiłem to po aktualizacji.

Teraz został tylko błąd w logach:

`[18-Dec-2017 15:35:32 Europe/Sarajevo] PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /home/***/public_html/vendor/yetiforce/Purifier.php on line 360
`
Ale nadal nie działa wyświetlania wartości w polu słownikowym wielokrotnego wyboru, oraz w innych modułach mam problem z polem do podania nr. telefonu, np. jak tworze nowego Kontrahenta.

**Comment by bpabiszczak** [comment]
Jeden problem jedno zgłoszenie.

**Comment by anderpydev** [comment]
okej.
