### ISSUE TITLE
[PL] Nie zgodne wersje w RC6 i RC7 dla 4.3

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5706]
#### Issue
Kilka dni temu dokonałem aktualizacji paczką 4.2.0_to_4.3.0_RC6
Po aktualizacji mam w stopce wersję 4.2.618

Paczka, która wyszła wczoraj tj. 4.2.0 to 4.2.613 RC7 - wskazuje na aktualizację do wersji 4.2.613

Co wprowadza ta aktualizacja i powinienem dokonać w moim wypadku aktualizację z RC6 do RC7, a to tylko błąd w numeracji?

Pozdrawiam,

**Comment by bpabiszczak** [comment]
Błąd pewnie w pliku wersji... szkoda czasu aby to analizować, to paczki testowe a za 2-3 dni pojawi się ostatnia finalna :D

**Comment by anderpydev** [comment]
Pewnie tak :)
Więc będzie wersja finalna przed Świętami, super prezent ;D

Pozdrawiam
