### ISSUE TITLE
Question: how to apply a filter for something overdue by date

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5707]
Hi,
I want to create a filter that shows things that are overdue soon as a date in the record has passed. I can select things like today, yesterday, last week etc. but for example, once 'yesterday' or 'last week' have passed it it no longer considered as overdue because it is no longer yesterday or last week etc. 
I need to enter something that says if date is greater than e.g. 16/12/2017 then display, but there is no option for 'greater than'. How have others managed to produce a filter that does this?

Kind regards

**Comment by anderpydev** [comment]
I would do it.

1. I add the Selection field in the module. Name "Overdue".
2. Automation - Triggers - Information flow, for the module
3. Schedule, e.g. 01:00
4. Task - Update record - Field "Overdue" to "Yes"
5. I'm doing a filter with the "Overdue" column

**Comment by PercyP** [comment]
@anderpydev 

THANK YOU! very easy to follow instructions and works perfectly - I didn't even think to use workflows (In mine it says Automation - Workflows)

**Comment by mariuszkrzaczkowski** [comment]
Test new conditions in filters

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

just tested - brilliant. Can now filter on Less that today's date and Greater than today's date.

Thank you
