### ISSUE TITLE
RC7 - multiimage not working - clicking on an image freezes screen and freezes when upload

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5709]
Hi,
I am testing latest release candidate update. 
When I click on an existing multiimage for a record it opens the image but locks the screen with no way of closing it. Also when uploading an image it also freezes the screen and never uploads. 
Related issue:
https://github.com/YetiForceCompany/YetiForceCRM/issues/5606
https://github.com/YetiForceCompany/YetiForceCRM/issues/5535

**Comment by bpabiszczak** [comment]
Duplicate: https://github.com/YetiForceCompany/YetiForceCRM/issues/5535
