### ISSUE TITLE
Updates are not saved

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5710]
For a long time we thought it was a problem of cron, or workflow (related closed #5575 ), but @vovpff realized that the problem was the failure to update the contacs, accounts and so on.
![schermata 2017-12-17 alle 17 06 10](https://user-images.githubusercontent.com/5500935/34081451-3681efac-e34d-11e7-82a3-8f225fb96906.png)
Yesterday I've buy a new hosting in Register.it italian hoster, but even in this hosting the results were the same.
Just buy a new shared hosting on Siteground, and being proceed to normal installation via softaculous, installation was good but issue remain!
![schermata 2017-12-17 alle 17 08 13](https://user-images.githubusercontent.com/5500935/34081476-8754aca8-e34d-11e7-8fdc-a6c86340fe58.png)
So I can deduce that the problem is in Yetiforce 4.2.0 package, and also in its installation via Softaculous.
If someone has taken special precautions before, during or after the installation, or has not had any kind of problem using that particular hosting provider, please tell this community, so that me and other users like me in the same problem can finally use this crm.

**Comment by mariuszkrzaczkowski** [comment]
Try to install the package downloaded from github and not install via  Softaculous

**Comment by centoasa** [comment]
I have already tried many times with the same result. I also tried version 4.1, same thing. I'm trying to install version 4.0, but after installation I can not get in any way, not even with admin-admin, now it gives me "I have already tried many times with the same result. I also tried version 4.1, same thing. I'm trying to install version 4.0, but after installation I can not get in any way, not even with admin-admin, now it gives me"

**Comment by centoasa** [comment]
Sorry, all releases download give error:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>

**Comment by vovpff** [comment]
@centoasa try this https://www.dropbox.com/s/hrwpies2d211301/YetiForceCRM%20stable%204.2.0.zip?dl=0

**Comment by centoasa** [comment]
On all my tests I've faound a release that work: the 3.4.0!
But when I try to update to 3.4.1427 to raise to latest release, I've an sql error and when logout same issue user and password. I'm trying with your @vovpff zip file

**Comment by centoasa** [comment]
@vovpff I'm sorry but also your file doesn't work!

**Comment by vovpff** [comment]
@centoasa this is very strange...

**Comment by centoasa** [comment]
and the interesting thing is that I tried on 3 different hosting.

**Comment by centoasa** [comment]
I have just buy a new hosting space on A2 www.a2hosting.com and through softaculous I installed again. Again it does not work.
Today with @vovpff we’ve reached to solve but its installation was only on local machine, so he can’t solve this great issue.

**Comment by vovpff** [comment]
yesterday we tried to install fresh 4.2.0 to @centoasa hosting and I noticed what installation process takes about 10 seconds. Some server requirements aren't met.
At my local machine (server) installation takes about 10-20 minutes.

**Comment by mariuszkrzaczkowski** [comment]
Install the latest development version, it is possible that these problems have already been fixed

**Comment by vovpff** [comment]
@mariuszkrzaczkowski composer included to latest dev?
As @centoasa said there are not possible to download old versions from github Yeti releases page.

**Comment by centoasa** [comment]
@vovpff your is a local installation with LAMP
mine is a shared hosting installation. All my installation as prestashop, Suitecrm, vtiger, sugarcrm, wordpress, has not took no more than 2 minutes
@mariuszkrzaczkowski how can I download the development version, and how can I install it?

**Comment by mariuszkrzaczkowski** [comment]
From here you can 
https://github.com/YetiForceCompany/YetiForceCRM/releases
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%204.x.x/

**Comment by centoasa** [comment]
@mariuszkrzaczkowski 
The links that you have provided refer to the stable versions, which are just those that do not work.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski releases on github looks like crashed:
![image](https://user-images.githubusercontent.com/8545791/34203425-1e5c1ace-e58c-11e7-8d1d-5bc610604ba5.png)
Sourceforge is ok!

**Comment by centoasa** [comment]
I've been saying this for many days, but none of the developers have heard me

**Comment by mariuszkrzaczkowski** [comment]
Files updated

**Comment by centoasa** [comment]
Installed the 4.2.0 complete, always the same problem of unregistered updates of contact, account....), after done update via zip file 4.2.0 _to_ 4.3.0 _rc7. zip
The contact edit buttons disappear

**Comment by centoasa** [comment]
**SOLVED**
![schermata 2017-12-20 alle 22 33 33](https://user-images.githubusercontent.com/5500935/34229864-1e83c23c-e5d6-11e7-832b-d2d28cc0ff44.png)
the nd_pdo_mysql was not flagged!
Now all works well!
Merry Christmas to all!

**Comment by centoasa** [comment]
Note: I suggest add php modules requested in requirement page.

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/34246398-b620eeaa-e62e-11e7-95c4-bf17f24ada6b.png)

**Comment by centoasa** [comment]
All the problems I had previously was precisely for this reason: the module you indicate was activated, but nowhere do you talk about the module nd_pdo_mysql

**Comment by mariuszkrzaczkowski** [comment]
mysql and nd_pdo_mysql this is the same
