### ISSUE TITLE
Question How to import User

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5720]
How to import users from files csv or excel. I tried many times but failed. 

![123123123](https://user-images.githubusercontent.com/19627226/34141984-47eb892c-e4b7-11e7-98d9-48774aaf15c8.png)

**Comment by kpaulaha** [comment]
Same here, exporting ok, but when try to import same, nope.

**Comment by areksolek** [comment]
Hello,
I tested import. The file has been imported. Please send me an example of the generated file.

**Comment by kpaulaha** [comment]
[Users.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/1576286/Users.zip)

**Comment by areksolek** [comment]
File export has been fixed. Now, when importing a file, it is enough to fill in the default value for a password field and a confirm password field and click "import". I present the result of the entire import and export process in the attached gif. 
![export-import](https://user-images.githubusercontent.com/25615135/34251831-9ecb4328-e641-11e7-8344-8336e9383569.gif)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/5742
