### ISSUE TITLE
[question] Recycle Bin

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5721]
Maybe I'm coming blind, but where can the deleted records be found in 4.3 when there's no Recycle Bin -module?

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/34147403-dad1f0e2-e49d-11e7-91aa-19fceff9abf7.png)

**Comment by kpaulaha** [comment]
Damned, I'm coming blind, thanks.
