### ISSUE TITLE
Add same picklist values to picklist fields in many modules

### ISSUE THREAD

**Issue by echemik** [YetiForceCompany/YetiForceCRM#5732]
#### Actual Behavior
I need to use same picklist values in few modules (eg. picklist countries). Now I need to create separate picklist fields and add same values to each module

#### Expected Behavior
I need to have two picklist fields in each module with te same values. I understand its need coding or database changes - but where is best place to change. Thanks in advance

#### Your Environment
* YetiForce Version used: 4.2

**Comment by KatarzynaUlichnowska** [comment]
Hello, the list of countries has already been added and will be present in 4.3. If you need to add a country field in a new module, add uitype35 field. 
You can also add one picklist in many modules but it needs to have the same field name.

**Comment by echemik** [comment]
country is example, i will test same field name solution. Thanks!
