### ISSUE TITLE
Merry Christmas from the YetiForce Team!

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#5735]
Video: https://www.youtube.com/watch?v=ZPYbTTUuni4
![image](https://user-images.githubusercontent.com/10197525/34209189-81f1dce0-e591-11e7-981a-8d2a3929e302.png)

**Comment by centoasa** [comment]
Happy Christmas and good holidays to all users of this fantastic CRM, and also to all those who would like to use it.

**Comment by PercyP** [comment]
Ah thats nice! It is good to see some of the people behind Yetiforce. 
Thanks for everything you have done this past year. I am sure 2018 will see your continued growth and success.
