### ISSUE TITLE
Mass deleting users not working

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5738]
Mass archive & Mass move to Recycle Bin of users not working
![users system settings](https://user-images.githubusercontent.com/10330264/34217378-fe278216-e5b3-11e7-93bf-c248e0d35cf2.png)

#### Your Environment

* YetiForce Version used: Dev  4.2.681
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/5747
