### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5741]
Excuse me, I've tried a lot on this subject, but no exhaustive answer. From admin login admin, isn't there a classic "password recovery" to recover a user's lost password?
Thank you
yeti 4.2.0

**Comment by anderpydev** [comment]
Change of password via e-mail

1. edit filet: config/security.php
2. change

`$SECURITY_CONFIG = [
	// Possible to reset the password while logging in (true/false)
	'RESET_LOGIN_PASSWORD' => true,`

**Comment by centoasa** [comment]
And if admin lost password? the others users can reset admin password?

**Comment by anderpydev** [comment]
I don't understand your question. Everyone resets their own password via email.

**Comment by KatarzynaUlichnowska** [comment]
In the new 4.3 version, the system for resetting and restoring a password has been rebuilt. If you want to report a bug, please trigger it on GitDeveloper and describe it in a detailed way.
