### ISSUE TITLE
Error download rouncube

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#5746]
When updating the system.He asks me to download the rouncube library, but it comes out in red and he does not download it.I downloaded from https://github.com/YetiForceCompany/lib_roundcube but when I load it from the module loader it throws me error​​​​​​​Ha falladoEl módulo no contiene el idioma predeterminado (en_us).Generado por YetiforceCRM ver. 4.2.618PHP: 7.0.26Errores de configuración del servidor:output_buffering: 4096innodb_lock_wait_timeout: 50

**Comment by anderpydev** [comment]
Automatic update libraries (lib_roundcube) works only for full system versions.

You must do it manually or wait for version 4.3

**Comment by joelbcampos** [comment]
Thanks, I put it in developer mode and I already download it
