### ISSUE TITLE
upgrade from 4.2 to RC7 round cube fails

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5749]
All works well, until I've upgrade from 4.2.0 to RC7
Upgrade process was complete successfully, but require me to upgrade roundcube library. 
After do it, here is my library:
![schermata 2017-12-21 alle 18 17 58](https://user-images.githubusercontent.com/5500935/34267028-a662c5b8-e67b-11e7-9455-38c2ea093cf2.png)
and if I try to go on my mailbox:
Not Found
The requested URL /public_html/modules/OSSMail/roundcube/ was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by joelbcampos** [comment]
I had the same problem can be downloaded by modifying this parameter.
https://github.com/YetiForceCompany/YetiForceCRM/blob/b7d221e40c4b0608bbd72a4cae2592f39dbc3d0e/config/developer.php#L20

**Comment by centoasa** [comment]
Thank you so much now works well.
