### ISSUE TITLE
Jak dodać dodatkowe kolumny w oknie PopUp dla Pola Powiązanego 1:M

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5750]
#### Issue

Chcę dodać dodatkowe kolumny w oknie PopUp dla przypisanego modułu (Pole powiązania 1:M).
Teraz mam tylko pole utworzone razem z modułem i właściciel rekordu.

Jak to zmienić?

![screenshot4](https://user-images.githubusercontent.com/26583746/34278033-a1bed628-e6a8-11e7-9b2a-2a12d3934385.png)

#### Your Environment

* YetiForce Version used: 4.2.618
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
Czemu nie śpisz ? :P Jak my mamy zamknąć wersje jak  tutaj ciągle nowe issue się pojawiają... 
O ile pamiętam, to jest to tablica z głównego pliku modułu którego popup dotyczy [skąd wczytuje dane], jeżeli w popup byliby kontrahenci wówczas to poleciłbym zmienić tutaj: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Accounts/Accounts.php#L54
ale mylić się mogę... programista powinien to odnaleźć w kilka minut.

**Comment by anderpydev** [comment]
Widzę, że nie tylko ja :P Też chcę domknąć priorytetowe zadania przed świętami ;D
Na pierwszy rzut oka wygląda, że to co wskazałeś jest tym czego szukam.
Jak przetestuję, to dam tylko info, czy zadziało.

**Comment by bpabiszczak** [comment]
Super, że mogłem pomóc!

**Comment by anderpydev** [comment]
Dzięki! Właśnie sprawdziłem i działa ;)

![screenshot5](https://user-images.githubusercontent.com/26583746/34280223-a5a9b556-e6b6-11e7-8606-8dd879bddd8a.png)
