### ISSUE TITLE
Translate core of Yetiforce

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5752]
Yetiforce 4.2.61
How can I translate core of Yetiforce, as "first name" in contact, because in translation I've added Language variable=First name but nothing change.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/106ee00609c700f5a17c47fe4d069f3fbdd849d5/languages/pl_pl/Vtiger.php#L74
