### ISSUE TITLE
RC7 issue create contact from email

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5753]
Yetiforce 4.2.168
from email, when I try to add contact, I've now this issue:
![schermata 2017-12-22 alle 09 01 30](https://user-images.githubusercontent.com/5500935/34290273-c0772518-e6f6-11e7-8c78-b475b97975ce.png)

**Comment by bpabiszczak** [comment]
Work on gitdeveloper
![image](https://user-images.githubusercontent.com/10197525/34290279-cbf2a3e0-e6f6-11e7-824c-64e44393ab83.png)

**Comment by centoasa** [comment]
@bpabiszczak do you suggest me to replace 4.2.168 with the latest 4.2.692?

**Comment by bpabiszczak** [comment]
Use only the stable version. Wait for version 4.3.

**Comment by centoasa** [comment]
RC7 is a stable or developed version? I'm still testing Yetiforce for my company, so do you suggest me to install new istance of 4.2.0 to complete testing?

**Comment by anderpydev** [comment]
The stable version is now 4.2.
RC7 is a test version, before the release of the stable version 4.3

**Comment by KatarzynaUlichnowska** [comment]
This occurs because you have switched the Contacts module to the advanced module.
