### ISSUE TITLE
[BUG] Custom Module | Widget updates not work

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5757]
https://gitdeveloper.yetiforce.com/ ver. 4.2.692
![bug custom module](https://user-images.githubusercontent.com/19627226/34294256-4327918a-e73a-11e7-8462-204656efa35a.gif)

**Comment by anderpydev** [comment]
In my system I also have the same problem
Version 4.2.618

The change history is not displayed. When I click on the green button "Read the changes" the system hangs.

Console in Chrome:

`Failed to load resource: the server responded with a status of 406 ()`
`{"success":false,"error"{"code":406,"message":"LBL_NO_PERMISSIONS_FOR_THE_RECORD","trace":""}}`
`errorLog @ app.min.js?s=1513194348:2`

**Comment by mariuszkrzaczkowski** [comment]
You did not enable the change history registration, so you can not see the changed data
