### ISSUE TITLE
Question | How to add widget comments to Module custom

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5758]
![widget comments](https://user-images.githubusercontent.com/19627226/34294326-8f702b38-e73a-11e7-9e5c-4777ff9108ac.gif)

**Comment by yetiforce-wojtek77** [comment]
It is a correct situation because a new created module default have not active commentary.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/a0225fc862e7efd9481d75785457542447834b64/modules/SCalculations/SCalculations.php#L92-L98

**Comment by rioshaz** [comment]
@mariuszkrzaczkowski hi buddy,, is this fix still applicable for yf 6.1 ? if not how to get comments in custom modules ? pls help
