### ISSUE TITLE
Custom module not show in Quick create ver. 4.2.692

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5759]
![zalo_screenshot_22_12_2017_109416](https://user-images.githubusercontent.com/19627226/34294392-e6d9ea4e-e73a-11e7-8ccc-1e7a1e68b8bd.png)

**Comment by anderpydev** [comment]
It works in my system.
Version 4.2.618

I have three modules. Two modules are displayed in Quick Creation.
Now the question. Why?

I think it has a connection:
The module must have a binding field (1: M) to another module. Then the module has the option "Quick addition" (+)

![screenshot6](https://user-images.githubusercontent.com/26583746/34295171-23bab6fc-e70c-11e7-8587-0a9017052af3.png)
