### ISSUE TITLE
YetiPortal2 

### ISSUE THREAD

**Issue by akromdoo** [YetiForceCompany/YetiForceCRM#5760]
I managed somehow managed to get Yetiportal2 to work but after log in i get this

![image](https://user-images.githubusercontent.com/34330433/34297321-c463f158-e717-11e7-9a9c-402b2cabaffd.png)

**Comment by bpabiszczak** [comment]
I tested it on gitdeveloper and couldn't trigger it. Unfortunately, you didn't provide info about the version of the system and didn't describe how to trigger it in a testing environment, so we don't know how to help you. Please bear in mind that the new version of the portal isn't a production version, so errors may appear. 

![image](https://user-images.githubusercontent.com/10197525/34381763-de2737fc-eb0a-11e7-9955-e89aaf007475.png)

![image](https://user-images.githubusercontent.com/10197525/34381748-ccdcfe14-eb0a-11e7-9466-25ebe1ac9741.png)
