### ISSUE TITLE
PDF generated lost settings

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5761]
Yeti force 4.2.0
In the generated PDF, for the header and footer, all text formatting settings and/or tables are lost/ignored. Only the text without formatting appears. While for the body all the settings and/or tables are correct

**Comment by vovpff** [comment]
@centoasa test it on gitdev first.

**Comment by centoasa** [comment]
it happens on gitstable.
And also I can't found the translation for $(custom : ProductsTableNew)$
![schermata 2017-12-26 alle 16 42 23](https://user-images.githubusercontent.com/5500935/34359891-f795f78c-ea5b-11e7-9f7f-7a8d9e6f5669.png)

**Comment by bpabiszczak** [comment]
Please check on gitdeveloper.

**Comment by centoasa** [comment]
on gitdev is OK
tips> wait 4.3 or edit some files to adjust issue?
 translation for $(custom : ProductsTableNew)$   ???

**Comment by KatarzynaUlichnowska** [comment]
This week we are going to release 4.3, so you will be able to update.
