### ISSUE TITLE
Roundcube preview hide emails

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5762]
Yetiforce 4.2.0
![schermata 2017-12-22 alle 18 14 54](https://user-images.githubusercontent.com/5500935/34306564-2bacaac2-e744-11e7-87e1-68cf3f1c8728.png)
IN roundcube setting, if I check flag for "show preview" email, all emails disappears/not accessible.

**Comment by yetiforce-wojtek77** [comment]
Please you write how I can show the error.

**Comment by centoasa** [comment]
if you go on roundcube setting-->mailbox view-->flag on Show preview pane and save, all email disappers, and roundcube say "no message found in this mailbox"

**Comment by bpabiszczak** [comment]
The problem that you decribed has already been fixed and you can test it at GitDeveloper [try to trigger it and if you manage to do that, please record a video]. Additionally, today we are fixing this button, so it won't break "saving"of what kind of preview was set.
