### ISSUE TITLE
[PL] Aktualizacja z RC6 do RC8 ?

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5763]
Wiem, że ciężko pracujecie nad wydaniem stabilnej wersji 4.3, a cel jest już coraz bliżej, stos z issues maleje z każdym dniem ;)

W paczce aktualizacyjnej RC8 jest poprawionych kilka istotnych rzeczy, które chciał bym już przetestować. Obecnie mam 4.2.618 (RC6) i kilka zrobionych już rzeczy od tego czasu w systemie, których nie chcę utracić.

Czy wystarczy, że nadpiszę swoje pliki z folderu (paczka aktualizacyjna) YetiForce CRM 4.x.x/4.2.0_to_4.3.0/updates/files/ ?

bo w folderze YetiForce CRM 4.x.x/4.2.0_to_4.3.0/updates/dbscheme/ 
jest plik Base3.php zmieniony od wersji RC2

A może też wystarczy nadpisać ogólnie pliki z gałęzi developer? Mam zainstalowaną wersję 4.2 i update do 4.3 RC6, więc obejdzie się bez composera?

Będę wdzięczny za wskazówki.

Pozdrawiam

#### Your Environment

* YetiForce Version used: 4.2.618

**Comment by bpabiszczak** [comment]
Paczkę się instaluje, nie nadpisuje się plików. Czyli normalnie instalujemy jak moduł. Może być wymagana zmiana wersji w pliku konfiguracyjnym na jakąś stabilną np. 4.2.0.

**Comment by anderpydev** [comment]
Wiem. Tylko właśnie już wcześniej wykonałem instalację paczką RC6. I nie chciała mi wejść kolejna aktualizacja, ale okej, to było takie w zasadzie oczywiste, żeby zmienić w pliku konfiguracyjnym z 4.2.618 na stabilną np 4.2.0.

Dzięki!
