### ISSUE TITLE
Error update RC8

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5764]
![zalo_screenshot_23_12_2017_610346](https://user-images.githubusercontent.com/19627226/34317489-b94403b4-e7e2-11e7-9b26-4cafab1fd4cb.png)
![zalo_screenshot_23_12_2017_61282](https://user-images.githubusercontent.com/19627226/34317502-f505641a-e7e2-11e7-87a0-a3bf8a3ecbd8.png)
![zalo_screenshot_23_12_2017_611266](https://user-images.githubusercontent.com/19627226/34317501-f35347d6-e7e2-11e7-8cf2-aa76a21e26a5.png)

**Comment by PercyP** [comment]
@ezbank 

exact same error for me when trying to update - took much longer than normal then produced that error and the update was not performed

**Comment by witer30** [comment]
I have the same error...

**Comment by mariuszkrzaczkowski** [comment]
Fixed in 4.2.0_to_4.3.0_RC9 https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%204.x.x/4.2.0_to_4.3.0/zip
