### ISSUE TITLE
mail scanner-general configuration doesn't save setting

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5765]
Yetiforce 4.2.0
General configuration in mail scanner setting doesn't save settings.
![schermata 2017-12-23 alle 09 12 48](https://user-images.githubusercontent.com/5500935/34318237-6a8dc21a-e7c3-11e7-9946-c4b2e0397dfb.png)

**Comment by centoasa** [comment]
It happens on gitstauble, doesn't happens on gitdev.
May I know what's the issue solved so I can remain on stable version but resolve this issue?

**Comment by yetiforce-wojtek77** [comment]
The error does not occur on the latest version (gitdev).
