### ISSUE TITLE
Custom module translation not working

### ISSUE THREAD

**Issue by elvissaba** [YetiForceCompany/YetiForceCRM#5767]
#### Issue
Fields created in custom module can not be translated.

#### Actual Behavior

i.e: Testfield1 and Testfield2 can not be translated

![image](https://user-images.githubusercontent.com/20727670/34318612-f6d2d176-e7cc-11e7-8f52-ff23b19ff960.png)

![image](https://user-images.githubusercontent.com/20727670/34318614-153bf6c4-e7cd-11e7-9343-f35a9980c872.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
GiteDeveloper ver. 4.2.697 - online
* Browser name and version:
Firefox
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@elvissaba choose language and your module thru language manager.
Jast click `Add translation`  put variable `Testfield1` and fill translations

**Comment by vovpff** [comment]
@elvissaba you need to repeat this steps for every new field on system.
