### ISSUE TITLE
workflow send email when ticket change

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5768]
I've tried all possible configurations, but the workflow to send email record owner or account/contact for me doesn't works. I've also tried with "Every time a record is saved (eg. creating, modifying)" and these conditions ==>
![schermata 2017-12-23 alle 16 40 27](https://user-images.githubusercontent.com/5500935/34320720-9105149c-e800-11e7-97f2-d214f313d35e.png)
No email was sent.
cron OK
yetiforce stable 4.2.0
tried with smtp and sendmail
p.s.: the workflow when create ticket works well.

**Comment by mariuszkrzaczkowski** [comment]
check the development version

**Comment by centoasa** [comment]
same issue. 
On workflow for ticket I've add the condition "comment is adding"
Tested adding my company 100ASA Srl
tested adding my smtp server==>none
tested adding sendmail==>none

**Comment by centoasa** [comment]
Sorry, very sorry: I had not noticed that there is even a form dedicated to comments!
Great!!!
![schermata 2017-12-24 alle 12 32 15](https://user-images.githubusercontent.com/5500935/34326163-a02ee730-e8a6-11e7-8ffe-0aecba9075ed.png)
