### ISSUE TITLE
SQLSTATE[23000]: when create new ticket

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5769]
Yetiforce stable 4.2
when try to add new ticket I've this error:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`irnndaeb_yeti`.`s_yf_mail_queue`, CONSTRAINT `s_yf_mail_queue_ibfk_1` FOREIGN KEY (`smtp_id`) REFERENCES `s_yf_mail_smtp` (`id`) ON DELETE CASCADE) The SQL being executed was: INSERT INTO `s_yf_mail_queue` (`smtp_id`, `to`, `subject`, `content`, `priority`, `status`, `owner`, `date`) VALUES (1, '[\"Remigio.ruberto@icloud.com\"]', 'Creato H4:Nuovo ticket 4', '
![schermata 2017-12-23 alle 16 59 46](https://user-images.githubusercontent.com/5500935/34320853-b1bffa56-e802-11e7-8905-f62982a01aae.png)
new email sent succesfully

**Comment by mariuszkrzaczkowski** [comment]
check the development version

**Comment by centoasa** [comment]
Isolated issue. Monitor the situation and in case, reply here.

**Comment by centoasa** [comment]
Now I'm just change the status of a ticket, and same issue appear==>
![schermata 2018-01-04 alle 12 58 02](https://user-images.githubusercontent.com/5500935/34562679-b7441c86-f14f-11e7-9601-8bfed3f70586.png)

**Comment by ldgbc** [comment]
Did you mange to fix this or find out how?
I import many company via CSV, under the Industry I added in many different type of industry but now when I use Picklist editing it giving me the error.

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '45' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `vtiger_industry` (`industryid`, `industry`, `sortorderid`, `presence`, `picklist_valueid`) VALUES (45, 'Valuation', 13, 1, 1322)
