### ISSUE TITLE
Product descriptions not hooked up

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5774]
#### Issue

I checked what in dev ver. 4.2.699 when you pick any product in item list there are no description hooked automatically to comment field for Logistics modules.

For invoices comments hooks as usual.

#### Actual Behavior

After pick comment is empty

#### Expected Behavior

After pick up comment is filled with product description data.
Or this feature can be optional. For example can be linked to any another product field.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
checked at gitdev 4.3.0. for invoices comment hooked, for GRN not hooked

**Comment by vovpff** [comment]
@mariuszkrzaczkowski today I updated my system to 4.3.0 and checked work ability and found what bug is here. Problem not in product description only. There are no any fields values loaded for Logistics modules (GRN, GDN and etc.)
In my system (ver 4.0) I added column for GRN what hooks qty in stock read-only value for picked product. After that manually I add mapping for this field to `u_yf_igrn_invmap` table:
```
"module"  	"field"      	"tofield"
"Products"	"qtyinstock"	"valueXX"
```
For 4.2.0 this works perfect. After update to 4.3.0 something going wrong and value don't appears after product selection.
I checked database and found what  `u_yf_igrn_invmap` is well.
After that I made visible EAN-13 field (was invisible because not used) for GRN and this this field not updated too.
Next step was repeating all steps for Invoices module with Value advanced field and I noticed what for this module Value field works perfect!

**Comment by vovpff** [comment]
Anybody has ideas how to solve this?

**Comment by vovpff** [comment]
actual dev for today. #5963 is here too!

![descr bug](https://user-images.githubusercontent.com/8545791/35223971-67b95ac0-ff94-11e7-830f-8d54977e1583.gif)

**Comment by kpaulaha** [comment]
Same problem with sales modules

![calculations create](https://user-images.githubusercontent.com/10330264/35341594-adf85798-012e-11e8-8e58-ea8cf6dd9b7e.png)

**Comment by mariuszkrzaczkowski** [comment]
I created an update package for this patch InventoryFix.zip
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.3.0

**Comment by kpaulaha** [comment]
@mariuszkrzaczkowski What is the function of giving unit price in GRN? The price is not transferred to product as I can see.
![grn1](https://user-images.githubusercontent.com/10330264/35471316-7d4e89fc-0361-11e8-999f-9223991b8ed5.png)

![grn2](https://user-images.githubusercontent.com/10330264/35471317-8184e1f6-0361-11e8-9c7b-cba7e55d3418.png)

**Comment by vovpff** [comment]
@kpaulaha as I understand advanced module items list tabla can call value from product module. Not transfer to product. I think this is new issue.

**Comment by kpaulaha** [comment]
@vovpff  Well I have something with one of my updated 4.3 +inventoryfix. Sorry, my mistake, explained badly, I meant when adding a new product with GRN using the product quick create, it did not add the price to GRN productline and not to the new product. But with the other installation it works (not the product line on GRN). The one installation is a quite mess, must reinstall. 
I understand that the price from advanced module can not transfer to product price M:1, trying to solve out some sense with the whole logistics modules with pricing

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks! Problem solved!
