### ISSUE TITLE
Custom invoke function not working

### ISSUE THREAD

**Issue by kimnamcham** [YetiForceCompany/YetiForceCRM#5776]
I had registered successfull custom function for Leads Module. But when i change status or create record, nothing happened. How to check is it working in yeti force ?
![1](https://user-images.githubusercontent.com/6441065/34390188-bbf24198-eb70-11e7-81ef-4d477f843e54.png)
![2](https://user-images.githubusercontent.com/6441065/34390189-bc1f19d4-eb70-11e7-99bf-56048a631c13.png)

**Comment by kimnamcham** [comment]
Yeti crm version i am using is 4.2

**Comment by bpabiszczak** [comment]
Please check here: https://gitdeveloper.yetiforce.com/

**Comment by kimnamcham** [comment]
can you explain more?

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists on the development version
