### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#5778]
I know that you know this new EU law, which will be very important in all of the CRM applications. That's why YETIFORCE is the right choice!

The GDPR will apply in all EU member states from 25 May 2018. Because GDPR is a regulation, not a directive, the UK does not need to draw up new legislation - instead, it will apply automatically. While it came into force on 24 May 2016, after all parts of the EU agreed to the final text, businesses and organisations have until 25 May 2018 until the law actually applies to them.

While the overwhelming majority of IT security professionals are aware of GDPR, just under half of them are preparing for its arrival, according to a snap survey of 170 cyber security staff by Imperva.

Just 43% are assessing GDPR's impact on their company and changing their practices to stay in step with data protection legislation, Imperva found. While the respondents were mostly US-based, they would still be hit by GDPR if they handle - or contract another firm to handle - EU citizens' personal data.

Despite this, nearly a third said they are not preparing for the incoming legislation, and 28% said they were ignorant of any preparations their company might be doing.

**Comment by bpabiszczak** [comment]
@fbojan at the moment we are changing security layers in a significant way. Regarding GDPR from the user perspective, it will be implemented and will appper in 5.0. There is no point in keeping this issue open for a few months. GDPR is very crucial to us and will be implemnted for sure.
