### ISSUE TITLE
[QUESTION][4.2.700][Text messages] How to create a new text message

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#5781]
#### Question
How can I create a new text message?
I don't found the add button or any way to create and send text messages.

![2017-12-28_09-27-18](https://user-images.githubusercontent.com/16593721/34406709-6cbcfcd4-ebb2-11e7-8ee6-19c76418f449.png)

#### Your Environment
* YetiForce Version used: Latest Version (4.2.700)
* Browser name and version: Google Chrome
* Operating System and version: Windows 10

**Comment by bpabiszczak** [comment]
In order for "send SMS" buttons to be active, you need to configure an SMS gateway in the configuration panel.
