### ISSUE TITLE
Email Reply opens Mail App selection on Windows systems' Browsers

### ISSUE THREAD

**Issue by nandospc** [YetiForceCompany/YetiForceCRM#5783]
As you can see, on Windows 10 Pro x64, using both Firefox or Chrome on YetiForce CRM GitStable Release, clicking on reply mail, in the section "Companies&Contacts"->"Companies"->"Company"->"Emails"->"Email Preview", Yeti will open the app selection window to reply to the email. This is not happening in Mac systems using Safari.

Check the video here: https://www.dropbox.com/s/fazwc92p32jp3h6/2017-12-28_12-16-33.mp4?dl=0

Edit: link to the video updated, now it should work

**Comment by mariuszkrzaczkowski** [comment]
Can you try to trigger it on gitdev?

**Comment by nandospc** [comment]
Same behavior even on the gitdev demo.

**Comment by nandospc** [comment]
We tried the gitstable, i think already with the new code you fixed 5 days ago, but the problem still persists. Not fixed imho.

**Comment by mariuszkrzaczkowski** [comment]
Test https://gitdeveloper.yetiforce.com/

**Comment by nandospc** [comment]
Same behavior even there.
