### ISSUE TITLE
How to get list record of related module via API

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5792]
how to get list record of related module via api.
example: get list records opportunity of one account

**Comment by mariuszkrzaczkowski** [comment]
Currently, there is no such functionality in the API.
We are planning to add it in the near future.

**Comment by kbancerz** [comment]
Has anything changed in this regard? Is it possible now to get relations of certain objects with REST API?

**Comment by kbancerz** [comment]
Is it safe to assume, that this will not be implemented any time soon? This issue was added to 4.4 milestone and has been closed since, so I don't suppose there are any plans for adding this in the upcoming versions?

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/60627627-e61dca00-9dee-11e9-8720-5073412534ae.png)
