### ISSUE TITLE
Privileges Updater functionality question

### ISSUE THREAD

**Issue by echemik** [YetiForceCompany/YetiForceCRM#5794]
Please describe how should work Privileges updater cron and when it should udpate records.

As I understand when I turn config/security.php option 'CACHING_PERMISSION_TO_RECORD' to true, after every cron run, job PRIVILEDGES UPDATER should update vtiger_crmentity.users and put there ids of users who can see this.

Im asking because on 4.2 its not updating vtiger_crmentity.users table until I make some change in Module Access - its normal?

**Comment by bpabiszczak** [comment]
Firstly, we have a problem to understand your question [PS If I remember correctly, you speak Polish, so please write issues in Polish - it will be quicker and simplier].

Regarding your question, the "privileges updater" mechanism works in two dimensions:
- recalculates privileges
- updates labels

Recalculating privileges is also nedded for the "CACHING_PERMISSION_TO_RECORD" mechanism, but it recalculates parmissions whether or not this option is enabled.

Unfortunately, I don't have time to describie how this mechanism works in detail from a technical and business perspective. If a developer enters it, he will understand what is happening in this script.
