### ISSUE TITLE
Error - Update 4.2.0 => 4.3.0

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#5805]
#### Issue

I test the new update "4.2.0_to_4.3.0_v1.zip" and become the following error (after upgrade from 4.0.0=> 4.1.0 and 4.1.0=>4.2.0):
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date_modified' The SQL being executed was: ALTER TABLE `vtiger_users` DROP COLUMN `calendarsharedtype`

Any idea?

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: chrome
* Environment name and version: wamp
* Operating System and version: Windows 10

**Comment by mariuszkrzaczkowski** [comment]
Show the logs and structure of the vtiger_users table

**Comment by kpaulaha** [comment]
On our installations updating from "clean" 4.2 works ok, but when 4.2 has been updated from earlier versions update hangs up.

**Comment by SkavenKF** [comment]
My YF version has been updated since 3.0 (or 3.1). Unfortunately, I can only test again from 08.01.18

**Comment by paula-w** [comment]
Currently there is already the 5th version of the [update package](https://github.com/YetiForceCompany/YetiForceCRM/releases). Each time we found an issue when we migrated the system for our clients we fixed the package. If the newest package doesn't help you then only direct support from a programmer can.
