### ISSUE TITLE
PDF page numbering

### ISSUE THREAD

**Issue by rafamacedo** [YetiForceCompany/YetiForceCRM#5807]
Hello team!

In the PDF module I created a 9 page contract, however when generating this PDF in the Services Sold that in the footer I lack the page numbering. For example, that could have "Page 1 of 9".

How do I enable the page numbering feature or is there any special tags to include in the footer?

Thank you!

#### Your Environment
* YetiForce Version used: 4.0.0
* Browser name and version: Google Chrome 63.0.3
* Environment name and version: I do not know
* Operating System and version: Windows 10 Pro

**Comment by konadrian** [comment]
Hello I added this feature to our crm, you can also copy this "{nb} from {PAGENO}" it should parse the numer of page

**Comment by rafamacedo** [comment]
Hello @konadrian 

Thanks for the interaction with me. Solved my problem and several other documents that I issue through this powerful tool.
