### ISSUE TITLE
YetiForce 4.3 is here!

### ISSUE THREAD

**Issue by bpabiszczak** [YetiForceCompany/YetiForceCRM#5808]
![yf4_3_25 hd](https://user-images.githubusercontent.com/10197525/34446203-5ca9c28c-ecd9-11e7-8436-bc20de9fab44.jpg)

We are delighted to inform you that a long-awaited 4.3 version has been released today. 🎉  🎉  🎉  After nearly 5 months of development it is finally here. Thank you for your patience!

We would like to remind you that the new version of the system is released under a new version of the license. 

The list of all new changes, features, and fixes can be found below and will be also added later to our website.

Once again, we would like to take a moment to thank you - our community - for your cooperation and contribution. You play a significant role in this project and we appreciate your effort. We want to express our gratitude for all you've done for YetiForce CRM.

### LINKS
GitHub: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.3.0
SourceForge: https://sourceforge.net/projects/yetiforce/
YetiForce update package 4.2 → 4.3: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%204.x.x/4.2.0_to_4.3.0/zip

Enjoy!

**Comment by bpabiszczak** [comment]
**ADDED**

- Added the Italian language
- Added verification of permissions
- Added a generator for user and calendar colors
- Added picklist css generator
- Added verification of dangerous usernames
- Added ability to change username during installation
- Added enhancements to the system installer
- Added user name verification during installation
- Added new charts to widgets
- Added filtering by owner to widgets with charts
- Added advanced verification of phone numbers
- Added a new field - Country
- Added new graphs to widgets
- Added testing of a record list
- Added verification of data types while saving
- Added summation to charts
- Added testing of the record list
- Added tests for API integration
- Added a new functionality to reset a user’s password
- Added a new functionality to change a user’s password
- Added mass password reset
- Added new tests
- Added a new functionality to remember previous user’s passwords
- Added brute force to reset password
- Added user password lifetime
- Added configuration of user account lock time
- Added functionality to force user password change 
- Added a new filter for users 
- Added functionality for archiving records
- Added coloring for record states
- Added style enhancements
- Added confirmations to actions
- Added validation of entered data to inventory table
- Added filtering by record status to related module
- Added ability to define view of related module 
- Added functionality for calculating values in the related record list
- Added a new view with record’s preview
- Added comment archiving functionality
- Added a new field type hierarchy
- Added improvements in DAV integration
- Added improvements in the system installer
- Added the ability to filter on less that today's date and greater than today's date
- Added horizontal scrollbar to list

**IMPROVED**

- Changed the license to YetiForce Public License v3
- Improved error handling
- Improved TextParser
- Improved editor of Roundcube Configuration
- Reconstruction of group functions
- Improved the panel for the search configuration
- Improved mail scanner
- Updated user colors
- Updated composer.json
- Updated .gitignore
- Updated phpunit.xml
- Updated .travis.yml
- Updated purifier.php
- Updated README.md
- Improved security
- Improved the quick create form for calendar
- Improved sql queries
- Improved automatic loading of values
- Improved create the menu
- Moved colors to the new settings module
- Rebuilt handling errors and clearing input
- Rebuilt test structure
- Rebuilt the list of related records functionality 
- Reconstructed input data security
- Improved view of event information
- Improved phone number storage
- Improved translation mechanism
- Improved permissions to delete records
- Improved cache of data in installation
- Improved configuration saving in ApiAddress module
- Improved email binding
- Improved code quality
- Improved security of input data
- Improved security exceptions 
- Improved functions of dates
- Improved data cleaning
- Improved permissions for Custom View
- Improved the list of mass actions
- Improved the login functionality
- Improved record deletion
- Improved ModTracker for deleting reords
- Improved display of currency values
- Improved anti-XSS mechanism
- Improved data cleaning in the language editor module
- Rebuilt PDF template
- Improved calendar invitation
- Improvements in dav integration
- Improved action to preview location
- Improved configuration verification
- Changed Module name “Sales Orders” → “Purchase Orders”
- Cleaned up translations

**FIXED**

- Fixed loading of links
- Fixed a bug that appeared after opening an event in list view
- Fixed a bug that appeared when creating a filter
- Fixed calendar colors in configuration
- Fixed attaching emails in contacts
- Fixed an advanced filter condition
- Fixed filter conditions
- Fixed a deletion of email scanner accounts
- Fixed errors in permissions
- Fixed create user records
- Fixed displaying of user image
- Fixed import
- Fixed folder conditions on folder and email fields
- Fixed tests
- Fixed group and role creation
- Fixed deletion of groups
- Fixed workflows navigation 
- Fixed a function call
- Fixed deleting users
- Fixed add relation in quick create
- Fixed field validation
- Fixed global search
- Fixed quick create error
- Fixed the FAQ module
- Fixed a bug that didn’t allow to add comments
- Fixed validation of url
- Fixed adding events
- Fixed the display of working time in Competition
- Fixed Campaigns reports
- Added minor fixes to phone field
- Fixed compatibility functions
- Changed the password encryption algorithm
- Fixed an error in OSSPassword
- Fixed system installer
- Fixed bugs in Reports
- Fixed mass edit in Users
- Fixed bugs in Workflows
- Fixed a bug that didn’t allow to add or remove new widgets in modules
- Fixed a bug that didn’t allow to use advanced search when in the module
- Fixed a bug with permissions in profiles
- Fixed fields updating in the Geolocator
- Fixed Email Scanner
- Fixed related documents so that they become clickable
- Fixed a bug that appeared during generating a PDF Template
- Fixed mass SMS
- Fixed a fatal error in advanced block fields
- Fixed Contact relation with Sold Products and Services
- Fixed caching functionality
- Fixed calendar display
- Fixed Language Management
- Fixed a graph in Time Control
- Fixed a bug in filters
- Fixed the display of currency symbol

**REMOVED**

- Removed PearDatabase
- Removed GetParentGroups.php file
- Removed moduleColor css class
- Removed mt940 import
- Removed EditFieldByModal
- Removed redundant code
- Removed DataAccess module
- Removed an old password reset and password change functionality
- Removed the Recycle Bin module
- Removed console.php

**Comment by waran70** [comment]
You changed sales order to purchase order. So what module will record succesul business transaction from now on? Sales order is a kind of important part of sales process. Just asking...

**Comment by anderpydev** [comment]
Gratuluję, wydania kolejnej wersji, jest moc ;)
Bardzo się cieszę z tego.

Życzę całemu zespołowi YetiForce, oraz społeczności wszystkiego najlepszego w nadchodzącym roku i mam nadzieję, że 2018 będzie równie owocny i przyniesie kolejne wspaniałe wydania systemu ;)

Pozdrawiam serdecznie.
