### ISSUE TITLE
[PL] Błąd. Aktualizacja 4.2.618 => 4.3.0

### ISSUE THREAD

**Issue by anderpydev** [YetiForceCompany/YetiForceCRM#5809]
#### Issue
Posiadam wersję 4.2.618
Zmieniłem w pliku version.php wartość 'appVersion' => '4.2.618', na 4.2, żeby mogła wykonać się aktualizacja bez komunikatu o braku zgodności wersji.

Po wgraniu paczki i akceptacji upgradu, po kilku minutach wyskoczył błąd.

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '52-MassArchived' for key 'PRIMARY' The SQL being executed was: INSERT INTO `vtiger_actionmapping` (`actionid`, `actionname`, `securitycheck`) VALUES (52, 'MassArchived', 0)

#### Your Environment

* YetiForce Version used: 4.2.618 RC6
* Browser name and version: Chrome

**Comment by bpabiszczak** [comment]
a po co aktualizujesz z 4.2.618 a nie z 4.2.0? Produkcje masz na wersji 4.2.618?

**Comment by anderpydev** [comment]
Jeszcze nie produkcje, ale już zaczęty projekt :/

**Comment by bpabiszczak** [comment]
To nie dobrze :] W teorii po zmianie numeracji i próbie aktualizacji system powinien się zaktualizować, ale my tego nie testujemy i nie gwarantujemy, że to się powiedzie. Przede wszystkim dlatego, że paczki są testowane tylko od wersji stabilnej. 

Programista zerknie w zgłoszenie we wtorek po sylwestrze, jednakże jeżeli nie będzie wiedział co to jest, to tylko programista który wejdzie w kod będzie wstanie pomóc dlaczego tak się stało i co trzeba poprawić.

**Comment by anderpydev** [comment]
Dziękuję za odpowiedź. No nierozważnie postąpiłem z tą aktualizacją do RC, na zaczętym już projekcie :]

Okej, w takim razie, temat do odnowienia na nowym roku już.
Pozdrawiam

**Comment by bpabiszczak** [comment]
My tak samo postępujemy jak Ty, ale jak coś się "wysypie" to poprawka zajmuje na kilka chwil... firma bez specjalisty ma ciężko w takich sytuacjach.

**Comment by bpabiszczak** [comment]
Wymaga to programisty, który będzie analizował konkretny przypadek.
