### ISSUE TITLE
[bug] 4.3 import email issue

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5812]
Yetiforce 4.3 on apache 2.4.29/php7 shared hosting
https://www.useloom.com/share/1dc874f3cf6845809dead5c0d283e4e4
As you can see on this video, some email are not imported in no way, instead other emails are already imported or importing normally.
I've alreay able the log for file, but I dont't know exactly where and what search.
Thanks for help

**Comment by paula-w** [comment]
This type of errors requires an in-depth analysis of each case individually. You have to provide us with more info on how to trigger this error on the gitdeveloper version so we can look into that. If you are not able to trigger this issue on the gitdeveloper version then it will require an analysis of the problem on your server.

**Comment by centoasa** [comment]
This problem often happens when the sender is of the type "donotreply"
In gitdev I don't found "donotreply" sender, so I can't test it.
Also I would like to know how emails are flaggate as imported into the database, so I want to check if this sender could have some block or similar.

**Comment by centoasa** [comment]
just now new email does'nt import because
`Return-Path: <SRS0=3qSkm=D7=idealo.de=noreply-billing@100asa.it>
Received: from prohosting6.netsons.net
	by prohosting6.netsons.net with LMTP id sDiIDBVDTlr8/gUAUPAIQw
	; Thu, 04 Jan 2018 16:07:01 +0100
Return-path: <SRS0=3qSkm=D7=idealo.de=noreply-billing@100asa.it>
Envelope-to: info@100asa.it
Delivery-date: Thu, 04 Jan 2018 16:07:01 +0100
Received: from mail-01.idealo.de ([62.146.17.39]:29982)
	by prohosting6.netsons.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply-billing@idealo.de>)
	id 1eX76Z-002DUA-TC
	for info@100asa.it; Thu, 04 Jan 2018 16:07:01 +0100
Received: from IdealoCloudApp (unknown [10.205.129.5])
	by mail-01.idealo.de (Postfix) with ESMTP id B24E93F834
	for <info@100asa.it>; Thu,  4 Jan 2018 16:06:48 +0100 (CET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=idealo.de; s=mail;
	t=1515078408; bh=FCVQIsS1j7ziGja6Jbmcic520sfP5PK3r1qHquEz+sM=;
	h=Date:From:To:Subject;
	b=i3QRRcjlKNv9tYusMYX0cFVQje079Jv/hSvcxBBPTQOtq6Gqk2riOhhtZ2W3JgjzX
	 gvYVFrq7nFP2M3jNI+pdmuvaAbjH/mbLtXEJO0/eleAtBmE+XOGBSmwk9imo50UwQw
	 h7yXrNlogLJ/8zd/jbFzshIXld6hh129oQyEn2PE=
Date: Thu, 4 Jan 2018 16:06:45 +0100 (CET)
X-Idealo: mailcluster
From: noreply-billing@idealo.de
To: info@100asa.it`

**Comment by centoasa** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5500935/34814217-210ce834-f6ad-11e7-8486-10b257e97ee0.gif)

**Comment by bpabiszczak** [comment]
I tested it using two mails and it worked for me. Send us the email to yetiforcetestmail@gmail.com because the email is linked to GitDeveloper and if the error also pops up in there we will check it
