### ISSUE TITLE
[BUG][4.3.1][Popover] the popover windows will not show correctly

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#5816]
#### Actual Behavior

![2018-01-02_09-43-34](https://user-images.githubusercontent.com/18419851/34479982-9e88905a-efa1-11e7-8a62-c0cb6728b50f.gif)

#### Your Environment

* YetiForce Version used: 4.3.1
* Browser name and version: Chrome 63 x64 
* Environment name and version: https://gitdeveloper.yetiforce.com/
* Operating System and version: https://gitdeveloper.yetiforce.com/

**Comment by mariuszkrzaczkowski** [comment]
The bug doesn’t exist in the newest version
