### ISSUE TITLE
[bug] Product price not saved correctly

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5817]
Yetiforce 4.3 (upgraded from 4.2)
https://www.useloom.com/share/802b046d1db2449b9fe00e29ca9e9e9d
as you can see on video, altought there are updates for prices, the product price is not save correctly. Not happens on gitstable-dev.
![schermata 2018-01-02 alle 10 54 26](https://user-images.githubusercontent.com/5500935/34480210-5277b952-efab-11e7-9682-2284c4f35c25.png)

**Comment by centoasa** [comment]
SOLVED used a protected browser page (maybe cookie saved wrong data)

**Comment by konadrian** [comment]
Worked on gitdeveloper version
