### ISSUE TITLE
[bug] Vendor enquiries prices

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5818]
Yetiforce 4.3 
https://www.useloom.com/share/5ae84d66339240f9bd3aa9298fecb337
as you can see on video, as I input unit price with decimal dot or comma, the 6,81€ is saved always as 681,00€
It happens on gitstable-dev

**Comment by centoasa** [comment]
Instead if I write unit price with integer value as 129,00 ===>
![schermata 2018-01-02 alle 17 33 54](https://user-images.githubusercontent.com/5500935/34491349-68ceefb2-efe3-11e7-9880-e07aa679373e.png)

**Comment by mariuszkrzaczkowski** [comment]
Show separator configurations on the user

**Comment by centoasa** [comment]
https://screenshots.firefox.com/HJK7i75rcHynkCfm/crm.100asa.it

**Comment by konadrian** [comment]
Can you send the configuration one more time? The link has expired
