### ISSUE TITLE
Error Update 4.0->4.1->4.2->4.3

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#5824]
#### Issue

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '108' for key 'PRIMARY' The SQL being executed was: INSERT INTO `vtiger_settings_field` (`fieldid`, `blockid`, `name`, `iconpath`, `description`, `linkto`, `sequence`, `active`, `pinned`, `admin_access`) VALUES (108, 4, 'LBL_COUNTRY_SETTINGS', 'glyphicon glyphicon-picture', 'LBL_COUNTRY_DESCRIPTION', 'index.php?module=Countries&parent=Settings&view=Index', 12, 0, 0, NULL)

#### How to trigger the error
Update latest packaged zip

**Comment by nkzach** [comment]
Same error for me when update from 4.2 to 4.3. I Solved it,  by restore to 4.2, and manually changing the value of 'fieldid' in table 'vtiger_settings_field' from '108' to another not used number e.g. '110'. Then the update has completed successfully.
I think the change I made does not cause any other problem.

**Comment by rskrzypczak** [comment]
Fixed in [UpdatePackages v3](https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%204.x.x/4.2.0_to_4.3.0/zip)
