### ISSUE TITLE
cron list updates time

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5828]
Yetiforce 4.3 (upgraded from 4.2)
![schermata 2018-01-03 alle 12 38 20](https://user-images.githubusercontent.com/5500935/34519182-19978012-f083-11e7-80df-9a728b703689.png)
as you can see the updates time is empty, but the cron works normally
[cron.log](https://github.com/YetiForceCompany/YetiForceCRM/files/1600179/cron.log)
on gitstable-dev updates times are shown, unformatting html.
![schermata 2018-01-03 alle 12 39 20](https://user-images.githubusercontent.com/5500935/34519293-802c9d26-f083-11e7-8a3d-6239255b5a17.png)

**Comment by rskrzypczak** [comment]
You probably don't have the value set in the 'Preview date format' field in the user configuration. Change the value in this field and upload https://github.com/YetiForceCompany/YetiForceCRM/commit/f9f83636cdb41eecb0a26d5e31c73ec7b4332a0c
This should solve the problem.

**Comment by centoasa** [comment]
Thank you all works well. I've to edit single field FL_VIEW_DATE_FORMAT with field pencil, because if I click on edit button on users preferences page, I've...
![schermata 2018-01-06 alle 16 40 11](https://user-images.githubusercontent.com/5500935/34641181-6685474a-f300-11e7-9b50-0cdd6fa4f42f.png)

**Comment by mariuszkrzaczkowski** [comment]
new error new issue
