### ISSUE TITLE
BUG: edit calendar call

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5832]
Error!!!

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tiger_activity.activityid' in 'where clause' Failed to prepare SQL: SELECT `vtiger_activity`.*, `vtiger_crmentity`.`description`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_crmentity`.`modifiedtime`, `vtiger_crmentity`.`createdtime`, `vtiger_activity_reminder`.`reminder_time` FROM `vtiger_activity` INNER JOIN `vtiger_crmentity` ON vtiger_activity.activityid = vtiger_crmentity.crmid LEFT JOIN `vtiger_activity_reminder` ON vtiger_activity_reminder.activity_id = vtiger_activity.activityid WHERE (`vtiger_crmentity`.`deleted`=:qp0) AND (`tiger_activity`.`activityid`=:qp1)

Just edit a calendar call, Yetiforce stable 4.3

**Comment by mariuszkrzaczkowski** [comment]
Add trace log

**Comment by centoasa** [comment]
Sorry where I can found it?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/44d12701c3b7f92ba8b01457b46c3166e4610e8d/config/debug.php#L22
'LOG_TRACE_LEVEL' => 9,

**Comment by aljofloz** [comment]
I have the same problem and I modified the file as proposed in e9f28e2 but I still unable to send invitations in Events. After modifying im getting this error:

[16-Apr-2018 00:46:03 America/Bogota] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Vtiger_Export_Model::output() must be an instance of App\Request, string given, called in /home/modules/com_vtiger_workflow/tasks/VTSendNotificationTask.php on line 52 and defined in /home/modules/Vtiger/models/Export.php:197
Stack trace:
#0 /home/modules/com_vtiger_workflow/tasks/VTSendNotificationTask.php(52): Vtiger_Export_Model->output('', Array, Object(Calendar_Module_Model), '', true)
#1 /home/modules/com_vtiger_workflow/VTWorkflowManager.php(521): VTSendNotificationTask->doTask(Object(Calendar_Record_Model))
#2 /home/modules/Vtiger/handlers/Workflow.php(95): Workflow->performTasks(Object(Calendar_Record_Model))
#3 /home/vendor/yetiforce/EventHandler.php(287): Vtiger_Workflow_Handler->entityAfterSave(Object(App\EventHandler))
#4 /home/modules/Vtiger/models/Record.php(414 in /home/modules/Vtiger/models/Export.php on line 197

Yetiforce Version: 4.3

**Comment by TomaszQr** [comment]
In current version it work properly
