### ISSUE TITLE
Advance Block - Field Relations/Mapping

### ISSUE THREAD

**Issue by zroxxah** [YetiForceCompany/YetiForceCRM#5834]
#### Issue

I am tailoring this software to a specific industry. I have created an advanced custom module called 'Work Orders' and I am trying to use picklist values from one module to another.

**_Yes, I have read the documentation for both YetiForce and vTiger. Yes, I have searched before posting._**

 I've tried following the suggestions from this post but they do not make any sense....
#2465 

#### Actual Behavior

When linking the module in the 'basic line' of the advanced block editor, then going to create a new record, the dropdown list is not populated with the specified values.

#### Expected Behavior

I want to be able to select the predetermined values from the picklist.

My expected flow of work 'Create Contact > Create Work Order'

1. Contact fields are mapped to Work Order - OK
2. Using an advance block to have dynamic fields - OK
3. Need to have picklists in advance block (Type, Color, Area) - **NOT OK**

#### How to trigger the error

1.![yeti1](https://user-images.githubusercontent.com/35117471/34586881-22977420-f163-11e7-9e28-30bcdf82313e.jpg)
2.![yeti2](https://user-images.githubusercontent.com/35117471/34586882-22aeae1a-f163-11e7-90e6-221545312fbe.jpg)
3.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome 63.0.3
* Environment name and version: MySQL 5.7.19 / PHP 7.1.9 / Apache 2.4.27 on WAMP 3.1
* Operating System and version: Windows 10

**Comment by vovpff** [comment]
@zroxxah I'm not sure what I'm right but there are not possible to map picklist/value field from system UI. You can try to map advanced fields to related module fields thru database manually. As samle you can pick mapping tables for GDN module
