### ISSUE TITLE
Software configuration > Calendar, Labels and colors > Colors > System settings - SQL error

### ISSUE THREAD

**Issue by paulokruz** [YetiForceCompany/YetiForceCRM#5845]
#### Issue

In TAB Picklists in Software configuration > Calendar, Labels and colors > Colors > System settings , return SQL error:

{"success":false,"error":{"code":0,"message":"SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'admin_YetiCrm.vtiger_field.tabid' which is not in SELECT list; this is incompatible with DISTINCT\nFailed to prepare SQL: SELECT DISTINCT `vtiger_tab`.`tabid`, `vtiger_tab`.`tablabel`, `vtiger_tab`.`name` AS `tabname` FROM `vtiger_field` INNER JOIN `vtiger_tab` ON vtiger_field.tabid = vtiger_tab.tabid WHERE (`uitype` IN (:qp0, :qp1, :qp2)) AND (`vtiger_tab`.`name` <> :qp3) ORDER BY `vtiger_field`.`tabid`","trace":""}}

![image](https://user-images.githubusercontent.com/5950623/34619308-a16e9ef0-f239-11e7-9c2d-217e05878d5d.png)

#### Actual Behavior

Return SQL error.

In gitdeveloper.yetiforce.com it is ok.

#### Expected Behavior

Expected select box with available modules.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:  [ver. 4.3.0]
* Browser name and version: Chrome 
* Environment name and version: Linux
* Operating System and version: Ubuntu 16.04 TLS

**Comment by rskrzypczak** [comment]
You probably do not use mysql.

**Comment by paulokruz** [comment]
Hi,

I use mysql, and i can navigate and work with Aplication (add, edit, configure, etc).

My only bug is this.

MYSQL information --> mysql  Ver 14.14 Distrib 5.7.20

**Comment by paulokruz** [comment]
Hi,

Problem solved, i disable ONLY_FULL_GROUP_BY in mysql sql_mode .

The sql error comes from mysql 5.7+. Specifically ONLY_FULL_GROUP_BY mode being set as default.
You can see the changes list here :: 
https://dev.mysql.com/doc/refman/5.7/en/mysql-nutshell.html#mysql-nutshell-deprecations

ONLY_FULL_GROUP_BY specifications for mysql 5.7+:
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

**Comment by mariuszkrzaczkowski** [comment]
This is all described in "Web server requirements" https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

> REQUIREMENTS FOR DATA BASE ENGINE [MYSQL]
> 
> - SQL_MODE should not contain STRICT_TRANS_TABLE and ONLY_FULL_GROUP_BY
> - ENGINE=InnoDB should be available and enabled by default (enable --skip-innodb)
> - The system works optionally with MySQLi module.

**Comment by paulokruz** [comment]
Ohh,

Thanks for your response, my fault bypass info about MYSQL.

Sorry about your time and good work.
