### ISSUE TITLE
workflow to update status in service contract

### ISSUE THREAD

**Issue by Jibe9191** [YetiForceCompany/YetiForceCRM#5846]
I created a workflow based on Execution schedule daily for service contract to update status of records  with overdue dates from progress to complete. When the workflow runs as scheduled it is also changing status of records which dates are not yet due to complete.

I have recreated the workflow on a fresh Yetiforce stable 4.3 and also on GitStable and GitDeveloper with the same result. Status update on service contract is applied to all records with due date and those not yet due

I expected the workflow to only update records based on the due date condition set.

Please advise as these work perfectly well on version 3.4

**Comment by konadrian** [comment]
Can you give us more info about the problem, some screens will be helpful. We need to know how you set up the workflow
