### ISSUE TITLE
[bug] edit user preferences

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5847]
Yetiforce 4.3
https://www.useloom.com/share/34f0d14ec248469589cc36736eb76adc (admin logged in in italian language)
https://www.useloom.com/share/2bfd44143d504a65b4a51c4f22dbc48d (admin logged in english language)

**Comment by vovpff** [comment]
@centoasa this translation are missed for It langpack

**Comment by konadrian** [comment]
Can you trigger this error on gitdeveloper version?
