### ISSUE TITLE
[question] about pdf generator

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#5848]
On pdf generator, how can I do to have all products detail?
So, with the $(custom : ProductsTableNew)$ 
![schermata 2018-01-07 alle 13 02 29](https://user-images.githubusercontent.com/5500935/34649234-0affa400-f3ab-11e7-8bdc-a921105a964c.png)
instead I would all products detail, as vendor code, EAN and so on.Where I can get this informations?
And how ca I get the Name of the generated file with current date?
Thank you

**Comment by centoasa** [comment]
Please, can anyone help me to locate the Yetiforce variables to have all the full details of the product and details of sales/purchase to add in pdf vendor enquiries?

**Comment by mariuszkrzaczkowski** [comment]
You can do it in two ways:

- modify the file https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/vendor/yetiforce/TextParser/ProductsTableNew.php

- add additional columns that will be automatically loaded when selecting the product

**Comment by centoasa** [comment]
there is no way to add the "custom field" product code or vendor code.
![schermata 2018-02-02 alle 14 55 11](https://user-images.githubusercontent.com/5500935/35736969-3c9b1aba-082a-11e8-8f9b-f455877f1b32.png)

Specially for purchase order, it's very important add the product code and the vendor code (To avoid doubts about the products ordered)
If I would to edit file you suggested, what's the field name to add to
$fieldsTextAlignRight = ['TotalPrice', 'Tax', 'MarginP', 'Margin', 'Purchase', 'Discount', 'NetPrice', 'GrossPrice', 'UnitPrice', 'Quantity'];
Thank you

**Comment by vovpff** [comment]
@centoasa You can add value field but there are no possibility to map this field to product vendor code trough admin GUI. You can implement mapping manually in database.

**Comment by centoasa** [comment]
I think a workaround (if it is possible):
here https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=SVendorEnquiries
I would to add a relations with vendor_part_no in the vtiger_products db table, so when I add in the vendor purchase order the product I can have also the vendor part number, in the vendor purchase and also on the pdf.
But in the "add custom filed" list there isn't relations with vtiger products or/and vendor_part_no

**Comment by vovpff** [comment]
@centoasa you can add value field with name for example LBL-VENPARTNO. Make them as read only. After that add translation by Language manager.
Now go to db and look to module tables. There are must be _invmap and _invfield tables. In infield table you can find correct name for new field (like value#). In invmap you need to add string with data. As sample you can take usage unit string.

**Comment by centoasa** [comment]
There a re many table named _invfiled
![schermata 2018-02-10 alle 17 44 56](https://user-images.githubusercontent.com/5500935/36064363-36033c44-0e8a-11e8-9c80-7bcb633a3578.png)
Now I've add an input filed where I manually add the vendor code, because there are no fields related to the product fron the custom fields that you can add
@mariuszkrzaczkowski But I still believe that the management of the fields and relations to build the PDF should be much smoother and easy.

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-development-ideas

**Comment by bpabiszczak** [comment]
We can do anything in the PDF module, unfortunately it often requires some programming work. From the administrator interface side you can add fields to a block with products, but to be able to modify the table in PDF requires some changes in the code.

We know that it should be easier for the user to create PDF documents, but unfortunately we don’t have enough time to do that right now.
