### ISSUE TITLE
Edit button missing

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5851]
#### Issue

I have installed YetiForce 4.3 version.
![missing buttons](https://user-images.githubusercontent.com/30116021/34663200-517cc544-f45e-11e7-8915-9269c3a1436f.png)

#### Actual Behavior

If i create a record, Edit button, Generate record and Transfer ownership is MISSING.

#### Expected Behavior

How i can make it appears?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Google Chrome
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@cltvchannel as I see something wrong with your server configuration because updates widget are empty. Record creation must be appear in updates every time.

**Comment by batalhao** [comment]
@cltvchannel Are you solved this issue? 

I'm having the same problem.
