### ISSUE TITLE
[question] Quotes

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5855]
In 4.2 we have a button where to change the status of quote if needed to edit after acceptance.
![quote](https://user-images.githubusercontent.com/10330264/34682481-ae939778-f4a7-11e7-9c6f-b64b677b2b40.png)
 In 4.3 there is not such button, how can it be done there? Am I blind again?

**Comment by vovpff** [comment]
@kpaulaha as I understand you can change status thru picklist only in 4.3

**Comment by kpaulaha** [comment]
@vovpff Jup, but when one has status "Accepted" there is no way to edit it any more, as there is in 4.2. thrue the button.

**Comment by vovpff** [comment]
@kpaulaha I don't know how to roll back from Accepted status. Let's wait answer from yeti crew

**Comment by kpaulaha** [comment]
Best way is to make a duplicate and make the changes.

**Comment by vovpff** [comment]
@kpaulaha let's check block edition workflow for quotes module. This workflow blocks editing when status is cancelled or accepted. Try to deactivate workflow tasks.

**Comment by vovpff** [comment]
@kpaulaha for logistics modules I found some code what locks edition:
For exaxmple for `Pre-order` at file `\modules\IPreOrder\IPreOrder.php`
L16
```
	 protected $lockFields = ['ipreorder_status' => ['PLL_ACCEPTED']];
```

**Comment by kpaulaha** [comment]
Thank's @vovpff. Yup, one day when I was wandering around I also found that it was blocked in workflow. But I somehow liked the way it was in older versions, that it's blocked when accepted, but you are able to change the status somewhere whithout disabling workflow task. But changes come and go and just need to adjust the way operating.
