### ISSUE TITLE
phperror log issues

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5856]
Hi,

I keep getting these on 4.2.259

"[20-Dec-2017 09:10:36 Europe/London] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/projectstart/vendor/yetiforce/Field.php on line 186"

**Comment by ezbank** [comment]
it's still in v4.3

**Comment by mariuszkrzaczkowski** [comment]
How can induce this error?

**Comment by alextovey** [comment]
Everytime i go to accounts then contacts relation tab and click add record it comes with  loading, please wait and this is the only thing in the php error log.

**Comment by konadrian** [comment]
Can you trigger this error on gitdeveloper version, for me works fine
