### ISSUE TITLE
Custom profile user can't login with changed password

### ISSUE THREAD

**Issue by nguyenthien2392** [YetiForceCompany/YetiForceCRM#5857]
I created a custom profile, and one user have this profile.
This user changes old password to new one successfully, but then user can't login with the new password (Invalid username or password.)
Sorry for my bad english, please help me to resolve this issues
Thanks alot.

**Comment by mariuszkrzaczkowski** [comment]
I created an update package for this patch, test it.
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.3.0

**Comment by nguyenthien2392** [comment]
This problem was solved by "PasswordFix.zip" update package. Thank you so much.
