### ISSUE TITLE
Use Mail functionality on custom Module

### ISSUE THREAD

**Issue by lelethered** [YetiForceCompany/YetiForceCRM#5862]
#### Issue

We are on the way to implement a new process, and we would like extend some functionality. In detail we would implement Mail functionality. We read in documentation: 
"E-mails can be easily related to Contacts, Leads, Accounts, Partners or Competitors as well as to various processes and subprocesses"

In our application, we don't use the standard module Contact or Account, we implement a new custom module for our need

The question is, we can use the complete functionality of Email in our custom module and it's related module?

#### Actual Behavior

not applicable
#### Expected Behavior

not applicable
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0 on yetiforce server with planned upgrade to 4.3 in February/March
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
The mechanism is written universally, which means that a programmer can implement it to any number of other modules and build a custom relations hierarchy. 
Unfortunately, modifications like these require extensive programming knowledge and awareness of how the system is built from the inside. It requires a deeper analysis and it’s not something we can do on GitHub.
