### ISSUE TITLE
[QUESTION][Create a new record by Custom Function]

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#5864]
#### Issue
I want to create a Project Milestone automatically when I create a Project, so I add a Workflow on Project with a Custom Function.
In my code I have written this:

`$projectmilestone = \Vtiger_Record_Model::getCleanInstance('ProjectMilestone');`
`if (!$projectmilestone->isCreateable()) {
	throw new \Api\Core\Exception('No permissions to create record', 401);
 }`

`$isNewPM = $projectmilestone->isNew();`
`if ($isNewPM) {$projectmilestone->isNew = false;}`

`$projectmilestone->set('projectmilestonename', 'Test');`

`$projectmilestone->setHandlerExceptions([
    'disableWorkflow' => TRUE,
    'disableHandlers' => TRUE
  ]);`

`$projectmilestone->save();`

But it doesn't work and doesn't shows me any error

How can I do it?

**Comment by KatarzynaUlichnowska** [comment]
Unfortunately, we don't provide programming advice for free. If you buy a support package, we can prepare you an example of the function in workflow.
