### ISSUE TITLE
Module version import issue

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#5872]
Could not properly upgrade our CRM from 4.20 to 4.3 so decided to setup a fresh one.
Then did an export from our custom modules and tried to import them again in the new one but get an error about the wrong version.
Thought to be smart, setup a fresh 4.2, installed the custom modules, upgraded to 4.3, exported the custom modules and tried to import again in our online v4.3. Still the same error. 

The question is how do I get custom modules properly installing on a newer version?

**Comment by kpaulaha** [comment]
We had problems with some modules exported from 4.2., did not contain language files, some other did. After adding them manually, increasing the version number in xml file and testing it in validator, all installed ok.

**Comment by alextovey** [comment]
@zebrahosting change the mainfest.xml file to say version 4.3.0 and try again.
I've constantly had issues like this and found solutions on my own by tweaking the files around. let me know if that does not solve it.

**Comment by kpaulaha** [comment]
I have put it to 6.5, so don't need to change all the time

**Comment by zebrahosting** [comment]
Thanks for all the suggestions, but did that already and no luck, after uploading the new archive file it gives a language file missing. Seen this before with updates etc. May be my OSX. Might try on Windows if I can find it :-)
Other suggestions welcome.

**Comment by konadrian** [comment]
Import/Export of module works fine on the current version.
