### ISSUE TITLE
Issues after installation

### ISSUE THREAD

**Issue by arnoko** [YetiForceCompany/YetiForceCRM#5876]
Hi Guys!
I hope this is the right place to put my issues, but this is what happened;

I did set up a new domain at A2Hosting (unlimited space) and installed vTiger, after which I discovered the existence of Yetiforce, which I also installed; Congratulations! This is really an improvement and we decided to use this as our new platform. However I have some serious problems.

1. The system says there is not enough disk space
![image](https://user-images.githubusercontent.com/35276016/34769707-d49aeed2-f5fe-11e7-9249-541eb2015ccc.png)
(164 GB of 1872 GB): obviously that should be enough, but Yetiforce sees a problem?

2. After adding a project, and  a task I see that projects and activities can no longer be editted. It seems there should be some editbutton that disappeared?

![image](https://user-images.githubusercontent.com/35276016/34770514-b79e59c4-f601-11e7-9f2f-be805406619a.png)

3. The ganttchart does not appear:
![image](https://user-images.githubusercontent.com/35276016/34771197-08c5e9b4-f604-11e7-803a-a4bd2c0d9b78.png)

4. Adding an event seems to work, however after saving it is not being stored.

Obviousy there is a structural problem that causes these phenomenoms. My question is; whats wrong here??

If you want i can give you access to the app so you can see what the settins are and what happens.
Tnx for your support!

Arno
  
#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Google chrome 63.0.3239.132 (Officiële build) (64-bits)
* Environment name and version: php7.0
* Operating System and version: win 10

**Comment by alextovey** [comment]
@arnoko did you setup the cron jobs? im running 50gb ssd and it installed fine. I would take a look at your server config in the system and see what errors it's showing whats wrong with the server.

**Comment by arnoko** [comment]
Tnx Alex; these are the settings it complains about; i have no clue what they do and how to change them. BTW; for vTiger this seems to be ok.
Also I do not know what cron suppost to do here...

![image](https://user-images.githubusercontent.com/35276016/34786903-c326ada8-f635-11e7-9159-e6679f31781c.png)
![image](https://user-images.githubusercontent.com/35276016/34786965-faedf372-f635-11e7-9a88-be56141aca2d.png)

**Comment by mariuszkrzaczkowski** [comment]
Each issues should be reported separately

**Comment by mariuszkrzaczkowski** [comment]
Can you try to trigger it on gitdev?

**Comment by arnoko** [comment]
Tnx Mariusz! I am just a normal user with some basic knowledge of these things... I do not know how to use gitdev. If anyone could give me a clue what setting could cause the described fenomonen, I will try to get this changed. Thanks for giving me some clues what to look for..!

**Comment by alextovey** [comment]
what os are you running it on and what web pltform?

**Comment by arnoko** [comment]
Hi Alex; here is the full sepcs of our webserver (Swift):
https://www.a2hosting.com/web-hosting/compare

**Comment by alextovey** [comment]
I would say their server is not compatible with yeti force as they won't let you edit the server configuration.

**Comment by anderpydev** [comment]
I will just add that Gantt does not work, because the user could not take the missing libraries, among others lib_gantt.

The rest was well indicated by alextovey - the server is not compatible.

**Comment by arnoko** [comment]
I checked in detail and a2hosting also says:
**We do support Yeti Force on our shared web hosting platform. However, you're asking for a specific module lib_gant to be enabled which we don't support. Unfortunately, we can't enable this module on our shared web hosting platform.** 

I Tried to install on Webreus, following your instructions and it geberates an error 500...

Can you recommend a provider that has yetiforce installable?

It is a pity that this beautifull CRM system is not so easy to install...

**Comment by alextovey** [comment]
Yeti force do servers

**Comment by mariuszkrzaczkowski** [comment]
The system is very 
simple to install, but you need to carefully read the requirements and configure the server accordingly.
![image](https://user-images.githubusercontent.com/10198654/34961825-40dfd620-fa41-11e7-9fc7-
7267547edc4e.png)

![image](https://user-images.githubusercontent.com/10198654/34961849-51409568-fa41-11e7-98d3-f2afa0c56c5b.png)

**Comment by alextovey** [comment]
Get a vps and configure it. If you need help I can lend a hand we supply vps servers but they are £30 a month 2 cores with 4gb ram and 100gb storage.

**Comment by arnoko** [comment]
Mariusz; this is what I did; and still it did not work; it drives me nuts... i tried two providers...
I just saw you are providing hosting and service pack.
I understand it would cost me 130euro (per year I guess) for the hosting and 163 euro for basic support. If that gets us up and running: how fast can it be done?

**Comment by anderpydev** [comment]
**arnoko**

If you do not have basic technical knowledge, buy the hosting and support in YetiForce. It saves you time and problems with running the system.

They also helped me in a few issues, they have great support and good sla (reaction time).

Regards

**Comment by KatarzynaUlichnowska** [comment]
Hello,
do the problems still exist? We tested them and we can't trigger issues 1-4 on the latest version.

**Comment by alextovey** [comment]
This is why we stopped using this and went to vtiger!

**Comment by KatarzynaUlichnowska** [comment]
Support wasn't our key goal. In May, we are launching our own cloud for YetiForce and we will open new support channels, including chat.
