### ISSUE TITLE
All modules/relations tabs on upgrade not working

### ISSUE THREAD

**Issue by alextovey** [YetiForceCompany/YetiForceCRM#5885]
Hi,

All modules/relations tabs are not working when you click select record or add records after upgrade. They were working to start with but not working and all have now stopped working with either LBL_hanlder Error or loading, please wait.

See attached gif.
![tabs](https://user-images.githubusercontent.com/22075161/34782711-74a6511a-f621-11e7-8a6d-0e0ee6038cc8.gif)

Nothing in error logs except
PHP Warning: Invalid argument supplied for foreach() in /var/www/html/projectstart/vendor/yetiforce/Field.php on line 186

anbd this in the mysql log
InnoDB: page_cleaner: 1000ms intended loop took 1213966ms. The settings might not be optimal. (flushed=0 and evicted=0, during the time.)

**Comment by alextovey** [comment]
14 days and still nothing from any developer! The only answer I get is you have to pay for support. This defeats the purpose of opensource software!

**Comment by konadrian** [comment]
Can you trigger this error on gitdeveloper version?, for me works fine
