### ISSUE TITLE
[BUG] v4.3 Field invisible in preview header

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5887]
Test on: https://gitstable.yetiforce.com
![zalo_screenshot_11_1_2018_327394](https://user-images.githubusercontent.com/19627226/34807264-57c463cc-f6ba-11e7-94e2-49161ba2db95.png)
![zalo_screenshot_11_1_2018_327973](https://user-images.githubusercontent.com/19627226/34807265-57f0cdd6-f6ba-11e7-980e-3162ba4db481.png)

**Comment by vovpff** [comment]
I noticed the same situation after update!

**Comment by anderpydev** [comment]
I also confirm this bug. Own installation.
I will add that the field with the number of active contracts is displayed

![screenshot_2](https://user-images.githubusercontent.com/26583746/34881743-af021f08-f7b4-11e7-86de-d9ed33b7d978.png)
