### ISSUE TITLE
Problem with adding new field to module

### ISSUE THREAD

**Issue by technologiegalwaniczne** [YetiForceCompany/YetiForceCRM#5889]
Hi. 
I am experiencing problems with adding a new field any module. 
I get a LBL_HANDLER_NOT_FOUND error. 
![image](https://user-images.githubusercontent.com/29600665/34822949-edc47106-f6c8-11e7-849d-f80b86685817.png)

YF 4.3.0
PHP 7.0

Any ideas?

Best regards
Maciej Janiak

**Comment by konadrian** [comment]
Can you trigger this error on gitdeveloper version https://gitdeveloper.yetiforce.com/index.php
