### ISSUE TITLE
Installation prerequisites incorrect reporting

### ISSUE THREAD

**Issue by suburbanworrier** [YetiForceCompany/YetiForceCRM#589]
Hi,

I've noticed on a couple of test installations that the Installation Wizard incorrectly reports the php.ini display_errors value.
I've attached a screenshot from the phpinfo screen versus the YetiForce output FYI.
![phpinfo _-_2015-04-21_11 18 02](https://cloud.githubusercontent.com/assets/1905346/7250415/ff4307be-e819-11e4-85a0-4060bae1f8e9.png)
![yetiforce_-_2015-04-21_11 21 39](https://cloud.githubusercontent.com/assets/1905346/7250418/054966bc-e81a-11e4-9f5c-d61983b4050f.png)

**Comment by suburbanworrier** [comment]
On 1.4.293 RC this issue is still present despite Fix #589
The OS is Debian Wheezy
phpinfo() correctly reports the display_errors = On setting from my php.ini but the installer does not

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/728c703ad7211cb1dd6becd9684160cd9bb32591
