### ISSUE TITLE
Add "Image" field to a new module (not MultiImage)

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#5899]
#### Issue

I want to add a Image field (like in Products module) to a new module. (Not MultiImage)

#### Expected Behavior

Ability to add a Image field.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: v4.3
* Browser name and version: Google Chrome
* Environment name and version:
* Operating System and version:

**Comment by cltvchannel** [comment]
Nothing?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/6482
