### ISSUE TITLE
[Improvement] PDF Templater To allow configure blocks with special functionalities

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#59]
To allow configure blocks with special functionality in GUI mode.  
To allow standard php functions on database fields within pdf templates

**Comment by bpabiszczak** [comment]
Everything that cannot be done from GUI level, can be done from a special function level. Currently, we don’t have any plans to develop GUI from PDF. In the future, we are going to add special functions and ready-made templates, but it requires some time.
