### ISSUE TITLE
[bug] Date picker start day

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5900]
#### Issue

Date picker starting day of the week every time is Sunday an there are no ability to change this/

![image](https://user-images.githubusercontent.com/8545791/34872876-cd6d30b0-f7a3-11e7-9179-aed3b53443f8.png)

#### Actual Behavior

Every time Sunday

#### Expected Behavior

Must be changeable to another days. For example Monday for Russia.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
What version of the system?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski 4.2.0 (in the past), 4.3.0 (my current system), 4.3.58 (latest gitdev for now)

**Comment by paula-w** [comment]
In the older versions (up to version 4.3) it used to be hard coded in the language files of this library. In the new version (4.4) it will depend on the user’s settings.
