### ISSUE TITLE
[BUG] v4.3 Workflow: Update related record not work

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#5901]
v4.3 
Tested on https://gitstable.yetiforce.com
![workflow - update related record](https://user-images.githubusercontent.com/19627226/34875137-9af97bea-f7ce-11e7-9abd-ed5c6c5c8ada.gif)

**Comment by waran70** [comment]
Confirmed. Try update account picklist when modifying contact.

**Comment by rskrzypczak** [comment]
cron is required.
![image](https://user-images.githubusercontent.com/10221999/35136636-f8ad1696-fce4-11e7-83dd-33a5dd807363.png)

**Comment by nkzach** [comment]
It is not Cron problem, the workflow is saved normally (after 6f23642 commit), but the field on related module does not change

**Comment by rskrzypczak** [comment]
as I said - "cron is required".
It works for me.
![workrelfieldchange](https://user-images.githubusercontent.com/10221999/35296765-63f1e0da-007d-11e8-84d2-b5b123a02e8a.gif)
When you save changes, you must wait for the cron to be executed.

**Comment by nkzach** [comment]
Yes, it works... thank you very much!
