### ISSUE TITLE
Can I or how to install YetiForceCRM in local Xampp environement?

### ISSUE THREAD

**Issue by KC20cy** [YetiForceCompany/YetiForceCRM#5904]
Hi there,

As the title described, I would like to install YetiForceCRM in a Windowns laptop via Xampp environment, I tried but failed to find related information online. Please suggest.

Regards,

KC

**Comment by vovpff** [comment]
1. Install xampp and configure it according web server requirements (yetiforce.com)
2. Download latest release from gir or sourceforge.
3. Unpack zip to your www folder.
4. Type URL of your system in browser and install system.
5. Profit!

**Comment by anderpydev** [comment]
or check it out: https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.3.0/xampp_YetiForceCRM-4.3.0-complete.zip

**Comment by KC20cy** [comment]
Hi there,

Thanks for your attention. After reading your reply, while I still don't know the exact URL to put to the browser which was why I put the wrong URL and led to a failure and ended up here asking a question.  I then tried some URL I did not try, and then the browser took me into the installation page finally.  So I suggest it will be a good idea to specific the URL for installation in XAMPP environment if it is possible.

However, I did not get through to the final success, I got this error message❶ after creating a mysql database and user name and password, please suggest. Thanks.

Regards,

KC

❶ Error Message Image
https://farm5.staticflickr.com/4722/24811028667_a42c9189f8_o.png

**Comment by ldgbc** [comment]
Anyone know what the timeframe it is to install this XAMPP version? Not sure if it freezing or what, been quite long on this page:

Installation in progress...

Install loading
Please wait....
