### ISSUE TITLE
[Issue] Missing jQuery Library for GitDev?

### ISSUE THREAD

**Issue by zroxxah** [YetiForceCompany/YetiForceCRM#5907]
#### Issue

It appears that the GitDev instance of YetiForce is either missing it's jQuery library or it somehow has become corrupt. Tested on multiple computers (Home PC, Laptop, Work PC).

#### Actual Behavior

Any function utilizing jQuery cannot execute because it appears to be undefined. 

#### Expected Behavior

Working as intended — compare to GitStable.

#### How to trigger the error

1. https://gitdeveloper.yetiforce.com/
2. 
![yetiforcedev4 3 58_chrome](https://user-images.githubusercontent.com/35117471/34921313-8e7511f2-f93d-11e7-845f-81f4d1f16476.jpg)
3. 
![yetiforcedev4 3 58_chrome1](https://user-images.githubusercontent.com/35117471/34921314-8ea5f9f2-f93d-11e7-8560-29e772706528.jpg)
4.
![yetiforcedev4 3 58_chrome_devtools](https://user-images.githubusercontent.com/35117471/34921379-8d881a22-f93e-11e7-921e-3b236f385e46.gif)

#### Your Environment

* YetiForce Version used: YetiForce 4.3.58
* Browser name and version: Google Chrome Version 63.0.3 
* Environment name and version: https://gitdeveloper.yetiforce.com/
* Operating System and version: https://gitdeveloper.yetiforce.com/

**Comment by mariuszkrzaczkowski** [comment]
Fixed
