### ISSUE TITLE
[bug] dates when clicking widget

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5914]
#### Issue
Clicking record on chart widget alter date format in list view.
![my home page](https://user-images.githubusercontent.com/10330264/34980303-bf306286-faac-11e7-8bc5-7003a45e669e.png)
![project tasks list filter_ test 1](https://user-images.githubusercontent.com/10330264/34980374-fefd7f8e-faac-11e7-91c1-b44f6e46d449.png)

#### Your Environment

* YetiForce Version used: dev
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rafalpospiech** [comment]
we worked on this lately, some earlier commit resolves that,
i see that someone else is still working on it in latest commits
but we are wondering now how to implement dates in user format across the system
this is work in progress,
but more details about this issue will be appreciated
which widget it is? url of the page (widget), is this custom chart?

**Comment by kpaulaha** [comment]
It's custom line chart displaying start dates of project tasks. Could not test it on current dev version, on stable version it exists.

**Comment by rafalpospiech** [comment]
in next release it should be fixed
