### ISSUE TITLE
Small translation issue in menu

### ISSUE THREAD

**Issue by suburbanworrier** [YetiForceCompany/YetiForceCRM#592]
Hi,

There are two definitions for MEN_LEADS in languages/en_us/Menu.php
The second is clearly incorrect.

In my installation removing the "Firmy" definition _does not_ change the page output.  I assume the values are cached somewhere but I can't find where from grepping.

HTH

**Comment by waw555** [comment]
See Vtiger.php and System/Vtiger.php
