### ISSUE TITLE
Recurring Invoices or Recurring Sales Orders

### ISSUE THREAD

**Issue by paulokruz** [YetiForceCompany/YetiForceCRM#5920]
Hello,

As anyone been able to create a  Recurring Invoices or Recurring Sales Orders with sucess ?

If so ca anyone tell me how i can do it.

Also when i create Recurring Sales Orders all are with status draft, how i can change this status.

For now i'm testing YetiforceCRM 4.3.0

**Comment by paulokruz** [comment]
No one has testing Recurring Sales Orders ?

**Comment by reeid** [comment]
Sales process have fundamental design errors, so until this part is done, testing those modules might be just wasting time.

**Comment by bpabiszczak** [comment]
How many CRM class systems give you the possibility to automatically create orders? How many systems allow you configure it, given the mechanism exists in these systems? I don’t know these systems and there probably aren’t many of them.

We added the possibility to semi-automatically create records from module A to module B in this version, eg. from orders to invoice, or from quote to to orders, etc. It will work semi-automatically which means that the user decided which recurring orders change into what orders.

Regardless of that, mechanisms like that require automation and customization each time for each client. The fact that a module is in the system [eg. recurring orders] doesn’t mean that it’s 100% automated and fully configurable. Right now we’re finishing engine modifications and, most likely, starting from version 4.5 we will focus on automation and process improvement.

From the technical side all you have to do is writing a script in Workflow that will for example automate creating regular orders from recurring orders.

**Comment by paulokruz** [comment]
Thanks for explanation, i will explore Workflow script.

And thanks to all team for good work in YetiForce.
