### ISSUE TITLE
Product link in pdf quotation

### ISSUE THREAD

**Issue by technologiegalwaniczne** [YetiForceCompany/YetiForceCRM#5929]
What changes to the code or setup should i do to remove the link (URL) on each product name in ProductTableNew? I don't want the customers to have access to the CRM address.

![image](https://user-images.githubusercontent.com/29600665/34995316-62adbd5e-fad6-11e7-9b17-9459b08c2b10.png)

YF: 4.3

Best regards
Maciej Janiak

**Comment by worldwidehigh** [comment]
Same Question, too.

**Comment by worldwidehigh** [comment]
So here is my solution for the producttable:

`strip_tags($field->getDisplayValue($itemValue))`

**Comment by vovpff** [comment]
@worldwidehigh how to apply this?

**Comment by 06400pl** [comment]
/vendor/yetiforce/TextParser/ProductsTableNew.php
