### ISSUE TITLE
[PL] Problem z edycją wpisów po aktualizacji do 4.3 

### ISSUE THREAD

**Issue by ResqIT** [YetiForceCompany/YetiForceCRM#5936]
#### Issue
Po aktualizacji systemu do wersji 4.3, nie można edytować, modyfikować rekordów kalendarza. Przy próbie zapisu, po zmianie daty, godziny pojawiają się komunikaty: 
Nieprawidłowe zapytanie
Niedozwolona wartość w polu time_end (9:00:00)

lub 

Nieprawidłowe zapytanie
Wykryto niedozwoloną wartość, prosimy o kontakt z administratorem

Dodawanie nowych zdarzeń przebiega bez problemów, ale ich edycja niesie z sobą problem. Przy wersji 4.2, po aktualizacji z 4.1 pojawił się błąd polegający na zmianie sposobu wyświetlania daty po zmianie typu zadania(spotkanie-telefon). W polu end time był komunikat Invalid value i trzeba było ręcznie zmieniać datę i godzinę(jak się zapomniało to pojawiał się podobny to teraźniejszego komunikat)

W logach błędów php, nginx nie widzę błędu.

#### Expected Behavior
możliwość dowolnej zmiany daty, opisu zdarzenia

#### How to trigger the error
1. Wybieram zadanie w kalendarzu, opcja edytuj
2. Nanoszę odpowiednie zmiany i klikam zapisz
3. Widzę błąd.....

#### Your Environment
* YetiForce Version used: 4.3
* Browser name and version: firefox 57.04, chrome
* Environment name and version: windows 10, macos 
* Server Operating System and version: ubuntu 16.04lts, php 7.0, nginx z fpm

2017-01-27 15:00:24 | Update package | 3.2.0 | 3.3.0 | Poprawna 
2017-03-01 13:38:40 | Update package | 3.3.0 | 3.4.0 | Poprawna
2017-03-01 13:41:51 | Update package | 3.4.0 | 3.4.1427 | Poprawna
2017-03-20 21:27:52 | Update package | 3.4.1427 | 4.0.0 | Poprawna
  |  YetiForce CRM 4.0.0 LTS + Service Pack 1 | 4.0.0 | 4.1.0 | Poprawna
2017-08-23 20:03:18 | YetiForce CRM 4 LTS + Service Pack 1 | 4.1.0 | 4.2.0 | Poprawna
2018-01-13 01:19:33 |  YetiForce CRM 4 LTS + Service Pack 3 | 4.2.0 | 4.3.0 | Poprawna

**Comment by bpabiszczak** [comment]
Czy błąd występuje tutaj: https://gitdeveloper.yetiforce.com/ ?
Nagraj mi filmik jak wywołujesz u siebie błąd, sprawdzę na jakieś wersji migrowanej [np. nasz CRM mamy migrowany od pierwszej wersji], jeżeli to błąd migracji to i u mnie będzie występować.

**Comment by ResqIT** [comment]
błędu nie udało mi się wygenerować na gitdeveloper.... Poniżej krótki gif z nim właśnie... Po dłuższym testowaniu dochodzę do wniosku, że problem jest rodzaj zdarzenia. Przy wartościach domyślnych(telefon, spotkanie) nie występuje, przy wartościach dodanych pojawia się, choć nie przy każdej. Tj. u mnie np. montaż i obsługa powodują błąd, awaria nie....
W słowniku pól-> moduł terminarza, rodzaj zdarzenia widoczne są wszystkie typy...
![sty-17-2018 22-30-06](https://user-images.githubusercontent.com/26115729/35068010-0edfa2fe-fbd6-11e7-8108-1abeb6275518.gif)

**Comment by ResqIT** [comment]
Update...
po dodaniu na demie do słownika dla pola event/activity type pozycji remote help i service, a następnie próbie zmiany rekordu test w kalendarzu otrzymałem:

Incorrect request
Incorrect value detected, please contact your administrator

Home page

#0 vendor/yetiforce/Request.php(136): App\Purifier::purifyByType('Remote Help', 1)
#1 modules/Calendar/actions/Save.php(84): App\Request->getByType('activitytype')
#2 modules/Events/actions/Save.php(48): Calendar_Save_Action->getRecordModelFromRequest(Object(App\Request))
#3 modules/Events/actions/Save.php(22): Events_Save_Action->getRecordModelFromRequest(Object(App\Request))
#4 modules/Calendar/actions/Save.php(16): Events_Save_Action->saveRecord(Object(App\Request))
#5 include/main/WebUI.php(190): Calendar_Save_Action->process(Object(App\Request))
#6 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#7 public_html/index.php(11): require('/home/gitdevelo...')
#8 {main}
#0 [trace] Entering getColumnFields(Users) method ...
#1 [trace] Exiting getColumnFields method ...
#2 [trace] Entering isPermitted(Events,DetailView,2040,) method ...
#3 [info] SELECT `crmid`, `setype`, `deleted`, `smcreatorid`, `smownerid`, `createdtime`, `private` FROM `vtiger_crmentity` WHERE `crmid`=2040 || yii\db\Command::query
#4 [info] Opening DB connection: mysql:host=localhost;dbname=gitdevelop_crm;port=3306 || yii\db\Connection::open
#5 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#6 [trace] Entering getColumnFields(Calendar) method ...
#7 [trace] Exiting getColumnFields method ...
#8 [trace] Entering getColumnFields(Calendar) method ...
#9 [trace] Exiting getColumnFields method ...
#10 [info] SELECT `vtiger_activity`.`subject` AS `vtiger_activitysubject`, `vtiger_crmentity`.`smownerid` AS `vtiger_crmentityassigned_user_id`, `vtiger_activity`.`date_start` AS `vtiger_activitydate_start`, `vtiger_activity`.`time_start` AS `vtiger_activitytime_start`, `vtiger_activity`.`time_end` AS `vtiger_activitytime_end`, `vtiger_activity`.`due_date` AS `vtiger_activitydue_date`, `vtiger_activity`.`process` AS `vtiger_activityprocess`, `vtiger_activity`.`link` AS `vtiger_activitylink`, `vtiger_activity`.`status` AS `vtiger_activityactivitystatus`, `vtiger_activity`.`priority` AS `vtiger_activitytaskpriority`, `vtiger_activity`.`sendnotification` AS `vtiger_activitysendnotification`, `vtiger_crmentity`.`createdtime` AS `vtiger_crmentitycreatedtime`, `vtiger_crmentity`.`modifiedtime` AS `vtiger_crmentitymodifiedtime`, `vtiger_activity`.`activitytype` AS `vtiger_activityactivitytype`, `vtiger_activity`.`visibility` AS `vtiger_activityvisibility`, `vtiger_crmentity`.`description` AS `vtiger_crmentitydescription`, `vtiger_activity`.`duration_hours` AS `vtiger_activityduration_hours`, `vtiger_activity`.`duration_minutes` AS `vtiger_activityduration_minutes`, `vtiger_activity`.`location` AS `vtiger_activitylocation`, `vtiger_activity_reminder`.`reminder_time` AS `vtiger_activity_reminderreminder_time`, `vtiger_activity`.`notime` AS `vtiger_activitynotime`, `vtiger_crmentity`.`modifiedby` AS `vtiger_crmentitymodifiedby`, `vtiger_crmentity`.`shownerid` AS `vtiger_crmentityshownerid`, `vtiger_crmentity`.`closedtime` AS `vtiger_crmentityclosedtime`, `vtiger_activity`.`allday` AS `vtiger_activityallday`, `vtiger_activity`.`state` AS `vtiger_activitystate`, `vtiger_activity`.`followup` AS `vtiger_activityfollowup`, `vtiger_activity`.`subprocess` AS `vtiger_activitysubprocess`, `vtiger_crmentity`.`private` AS `vtiger_crmentityprivate`, `vtiger_activity`.`reapeat` AS `vtiger_activityreapeat`, `vtiger_activity`.`recurrence` AS `vtiger_activityrecurrence`, `vtiger_activity`.`linkextend` AS `vtiger_activitylinkextend`, `vtiger_crmentity`.`smcreatorid` AS `vtiger_crmentitycreated_user_id`, `vtiger_crmentity`.`was_read` AS `vtiger_crmentitywas_read`, `vtiger_crmentity`.`deleted` FROM `vtiger_crmentity` LEFT JOIN `vtiger_activity` ON vtiger_crmentity.crmid = vtiger_activity.activityid LEFT JOIN `vtiger_activity_reminder` ON vtiger_crmentity.crmid = vtiger_activity_reminder.activity_id LEFT JOIN `vtiger_activitycf` ON vtiger_crmentity.crmid = vtiger_activitycf.activityid WHERE (`vtiger_crmentity`.`crmid`=2040) AND (`vtiger_crmentity`.`setype`='Calendar') LIMIT 1 || yii\db\Command::query
#11 [info] SELECT DISTINCT `userid` FROM `u_yf_crmentity_showners` WHERE `crmid`=2040 || yii\db\Command::query
#12 [trace] Entering isPermitted(Events,EditView,2040,) method ...
#13 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#14 [info] SELECT `workflow_id`, `module_name`, `summary`, `test`, `execution_condition`, `defaultworkflow`, `type`, `filtersavedinnew` FROM `com_vtiger_workflows` WHERE `module_name`='Events' || yii\db\Command::query
#15 [trace] Entering App\Field::getFieldPermission: 9,subject
#16 [trace] Entering App\Field::getFieldsPermissions: 9
#17 [trace] Entering App\Field::getFieldPermission: 16,subject
#18 [trace] Entering App\Field::getFieldsPermissions: 16
#19 [trace] Entering App\Field::getFieldPermission: 9,subject
#20 [trace] Entering App\Field::getFieldsPermissions: 9
#21 [trace] Entering App\Field::getFieldPermission: 16,subject
#22 [trace] Entering App\Field::getFieldsPermissions: 16
#23 [trace] Entering App\Field::getFieldPermission: 9,assigned_user_id
#24 [trace] Entering App\Field::getFieldsPermissions: 9
#25 [trace] Entering App\Field::getFieldPermission: 16,assigned_user_id
#26 [trace] Entering App\Field::getFieldsPermissions: 16
#27 [trace] Entering App\Field::getFieldPermission: 9,assigned_user_id
#28 [trace] Entering App\Field::getFieldsPermissions: 9
#29 [trace] Entering App\Field::getFieldPermission: 16,assigned_user_id
#30 [trace] Entering App\Field::getFieldsPermissions: 16
#31 [trace] Entering App\Field::getFieldPermission: 9,date_start
#32 [trace] Entering App\Field::getFieldsPermissions: 9
#33 [trace] Entering App\Field::getFieldPermission: 16,date_start
#34 [trace] Entering App\Field::getFieldsPermissions: 16
#35 [trace] Entering App\Field::getFieldPermission: 9,date_start
#36 [trace] Entering App\Field::getFieldsPermissions: 9
#37 [trace] Entering App\Field::getFieldPermission: 16,date_start
#38 [trace] Entering App\Field::getFieldsPermissions: 16
#39 [trace] Start DateTimeField::convertToDBFormat s:10:"2018-01-03";
#40 [trace] End DateTimeField::convertToDBFormat
#41 [trace] Entering App\Field::getFieldPermission: 9,time_start
#42 [trace] Entering App\Field::getFieldsPermissions: 9
#43 [trace] Entering App\Field::getFieldPermission: 16,time_start
#44 [trace] Entering App\Field::getFieldsPermissions: 16
#45 [trace] Entering App\Field::getFieldPermission: 9,time_start
#46 [trace] Entering App\Field::getFieldsPermissions: 9
#47 [trace] Entering App\Field::getFieldPermission: 16,time_start
#48 [trace] Entering App\Field::getFieldsPermissions: 16
#49 [trace] Entering App\Field::getFieldPermission: 9,due_date
#50 [trace] Entering App\Field::getFieldsPermissions: 9
#51 [trace] Entering App\Field::getFieldPermission: 16,due_date
#52 [trace] Entering App\Field::getFieldsPermissions: 16
#53 [trace] Entering App\Field::getFieldPermission: 9,due_date
#54 [trace] Entering App\Field::getFieldsPermissions: 9
#55 [trace] Entering App\Field::getFieldPermission: 16,due_date
#56 [trace] Entering App\Field::getFieldsPermissions: 16
#57 [trace] Start DateTimeField::convertToDBFormat s:10:"2018-01-03";
#58 [trace] End DateTimeField::convertToDBFormat
#59 [trace] Entering App\Field::getFieldPermission: 9,time_end
#60 [trace] Entering App\Field::getFieldsPermissions: 9
#61 [trace] Entering App\Field::getFieldPermission: 16,time_end
#62 [trace] Entering App\Field::getFieldsPermissions: 16
#63 [trace] Entering App\Field::getFieldPermission: 9,time_end
#64 [trace] Entering App\Field::getFieldsPermissions: 9
#65 [trace] Entering App\Field::getFieldPermission: 16,time_end
#66 [trace] Entering App\Field::getFieldsPermissions: 16
#67 [trace] Entering App\Field::getFieldPermission: 9,shownerid
#68 [trace] Entering App\Field::getFieldsPermissions: 9
#69 [trace] Entering App\Field::getFieldPermission: 16,shownerid
#70 [trace] Entering App\Field::getFieldsPermissions: 16
#71 [trace] Entering App\Field::getFieldPermission: 9,shownerid
#72 [trace] Entering App\Field::getFieldsPermissions: 9
#73 [trace] Entering App\Field::getFieldPermission: 16,shownerid
#74 [trace] Entering App\Field::getFieldsPermissions: 16
#75 [trace] Entering App\Field::getFieldPermission: 9,duration_hours
#76 [trace] Entering App\Field::getFieldsPermissions: 9
#77 [trace] Entering App\Field::getFieldPermission: 16,duration_hours
#78 [trace] Entering App\Field::getFieldsPermissions: 16
#79 [trace] Entering App\Field::getFieldPermission: 9,duration_hours
#80 [trace] Entering App\Field::getFieldsPermissions: 9
#81 [trace] Entering App\Field::getFieldPermission: 16,duration_hours
#82 [trace] Entering App\Field::getFieldsPermissions: 16
#83 [trace] Entering App\Field::getFieldPermission: 9,activitystatus
#84 [trace] Entering App\Field::getFieldsPermissions: 9
#85 [trace] Entering App\Field::getFieldPermission: 16,activitystatus
#86 [trace] Entering App\Field::getFieldsPermissions: 16
#87 [trace] Entering App\Field::getFieldPermission: 9,activitystatus
#88 [trace] Entering App\Field::getFieldsPermissions: 9
#89 [trace] Entering App\Field::getFieldPermission: 16,activitystatus
#90 [trace] Entering App\Field::getFieldsPermissions: 16
#91 [trace] Entering App\Field::getFieldPermission: 9,duration_minutes
#92 [trace] Entering App\Field::getFieldsPermissions: 9
#93 [trace] Entering App\Field::getFieldPermission: 16,duration_minutes
#94 [trace] Entering App\Field::getFieldsPermissions: 16
#95 [trace] Entering App\Field::getFieldPermission: 9,duration_minutes
#96 [trace] Entering App\Field::getFieldsPermissions: 9
#97 [trace] Entering App\Field::getFieldPermission: 16,duration_minutes
#98 [trace] Entering App\Field::getFieldsPermissions: 16
#99 [trace] Entering App\Field::getFieldPermission: 9,activitytype
#100 [trace] Entering App\Field::getFieldsPermissions: 9
#101 [trace] Entering App\Field::getFieldPermission: 16,activitytype
#102 [trace] Entering App\Field::getFieldsPermissions: 16
#103 [trace] Entering App\Field::getFieldPermission: 9,activitytype
#104 [trace] Entering App\Field::getFieldsPermissions: 9
#105 [trace] Entering App\Field::getFieldPermission: 16,activitytype
#106 [trace] Entering App\Field::getFieldsPermissions: 16
#107 [trace] Entering App\Field::getFieldPermission: 9,sendnotification
#108 [trace] Entering App\Field::getFieldsPermissions: 9
#109 [trace] Entering App\Field::getFieldPermission: 16,sendnotification
#110 [trace] Entering App\Field::getFieldsPermissions: 16
#111 [trace] Entering App\Field::getFieldPermission: 9,sendnotification
#112 [trace] Entering App\Field::getFieldsPermissions: 9
#113 [trace] Entering App\Field::getFieldPermission: 16,sendnotification
#114 [trace] Entering App\Field::getFieldsPermissions: 16
#115 [trace] Entering App\Field::getFieldPermission: 9,createdtime
#116 [trace] Entering App\Field::getFieldsPermissions: 9
#117 [trace] Entering App\Field::getFieldPermission: 16,createdtime
#118 [trace] Entering App\Field::getFieldsPermissions: 16
#119 [trace] Entering App\Field::getFieldPermission: 9,createdtime
#120 [trace] Entering App\Field::getFieldsPermissions: 9
#121 [trace] Entering App\Field::getFieldPermission: 16,createdtime
#122 [trace] Entering App\Field::getFieldsPermissions: 16
#123 [trace] Entering App\Field::getFieldPermission: 9,location
#124 [trace] Entering App\Field::getFieldsPermissions: 9
#125 [trace] Entering App\Field::getFieldPermission: 16,location
#126 [trace] Entering App\Field::getFieldsPermissions: 16
#127 [trace] Entering App\Field::getFieldPermission: 9,location
#128 [trace] Entering App\Field::getFieldsPermissions: 9
#129 [trace] Entering App\Field::getFieldPermission: 16,location
#130 [trace] Entering App\Field::getFieldsPermissions: 16
#131 [trace] Entering App\Field::getFieldPermission: 9,taskpriority
#132 [trace] Entering App\Field::getFieldsPermissions: 9
#133 [trace] Entering App\Field::getFieldPermission: 16,taskpriority
#134 [trace] Entering App\Field::getFieldsPermissions: 16
#135 [trace] Entering App\Field::getFieldPermission: 9,taskpriority
#136 [trace] Entering App\Field::getFieldsPermissions: 9
#137 [trace] Entering App\Field::getFieldPermission: 16,taskpriority
#138 [trace] Entering App\Field::getFieldsPermissions: 16
#139 [trace] Entering App\Field::getFieldPermission: 9,modifiedtime
#140 [trace] Entering App\Field::getFieldsPermissions: 9
#141 [trace] Entering App\Field::getFieldPermission: 16,modifiedtime
#142 [trace] Entering App\Field::getFieldsPermissions: 16
#143 [trace] Entering App\Field::getFieldPermission: 9,modifiedtime
#144 [trace] Entering App\Field::getFieldsPermissions: 9
#145 [trace] Entering App\Field::getFieldPermission: 16,modifiedtime
#146 [trace] Entering App\Field::getFieldsPermissions: 16
#147 [trace] Entering App\Field::getFieldPermission: 9,closedtime
#148 [trace] Entering App\Field::getFieldsPermissions: 9
#149 [trace] Entering App\Field::getFieldPermission: 16,closedtime
#150 [trace] Entering App\Field::getFieldsPermissions: 16
#151 [trace] Entering App\Field::getFieldPermission: 9,closedtime
#152 [trace] Entering App\Field::getFieldsPermissions: 9
#153 [trace] Entering App\Field::getFieldPermission: 16,closedtime
#154 [trace] Entering App\Field::getFieldsPermissions: 16
#155 [trace] Entering App\Field::getFieldPermission: 9,notime
#156 [trace] Entering App\Field::getFieldsPermissions: 9
#157 [trace] Entering App\Field::getFieldPermission: 16,notime
#158 [trace] Entering App\Field::getFieldsPermissions: 16
#159 [trace] Entering App\Field::getFieldPermission: 9,notime
#160 [trace] Entering App\Field::getFieldsPermissions: 9
#161 [trace] Entering App\Field::getFieldPermission: 16,notime
#162 [trace] Entering App\Field::getFieldsPermissions: 16
#163 [trace] Entering App\Field::getFieldPermission: 9,state
#164 [trace] Entering App\Field::getFieldsPermissions: 9
#165 [trace] Entering App\Field::getFieldPermission: 16,state
#166 [trace] Entering App\Field::getFieldsPermissions: 16
#167 [trace] Entering App\Field::getFieldPermission: 9,state
#168 [trace] Entering App\Field::getFieldsPermissions: 9
#169 [trace] Entering App\Field::getFieldPermission: 16,state
#170 [trace] Entering App\Field::getFieldsPermissions: 16
#171 [trace] Entering App\Field::getFieldPermission: 9,visibility
#172 [trace] Entering App\Field::getFieldsPermissions: 9
#173 [trace] Entering App\Field::getFieldPermission: 16,visibility
#174 [trace] Entering App\Field::getFieldsPermissions: 16
#175 [trace] Entering App\Field::getFieldPermission: 9,visibility
#176 [trace] Entering App\Field::getFieldsPermissions: 9
#177 [trace] Entering App\Field::getFieldPermission: 16,visibility
#178 [trace] Entering App\Field::getFieldsPermissions: 16
#179 [trace] Entering App\Field::getFieldPermission: 9,modifiedby
#180 [trace] Entering App\Field::getFieldsPermissions: 9
#181 [trace] Entering App\Field::getFieldPermission: 16,modifiedby
#182 [trace] Entering App\Field::getFieldsPermissions: 16
#183 [trace] Entering App\Field::getFieldPermission: 9,modifiedby
#184 [trace] Entering App\Field::getFieldsPermissions: 9
#185 [trace] Entering App\Field::getFieldPermission: 16,modifiedby
#186 [trace] Entering App\Field::getFieldsPermissions: 16
#187 [trace] Entering App\Field::getFieldPermission: 9,allday
#188 [trace] Entering App\Field::getFieldsPermissions: 9
#189 [trace] Entering App\Field::getFieldPermission: 16,allday
#190 [trace] Entering App\Field::getFieldsPermissions: 16
#191 [trace] Entering App\Field::getFieldPermission: 9,allday
#192 [trace] Entering App\Field::getFieldsPermissions: 9
#193 [trace] Entering App\Field::getFieldPermission: 16,allday
#194 [trace] Entering App\Field::getFieldsPermissions: 16
#195 [trace] Entering App\Field::getFieldPermission: 9,private
#196 [trace] Entering App\Field::getFieldsPermissions: 9
#197 [trace] Entering App\Field::getFieldPermission: 16,private
#198 [trace] Entering App\Field::getFieldsPermissions: 16
#199 [trace] Entering App\Field::getFieldPermission: 9,private
#200 [trace] Entering App\Field::getFieldsPermissions: 9
#201 [trace] Entering App\Field::getFieldPermission: 16,private
#202 [trace] Entering App\Field::getFieldsPermissions: 16
#203 [trace] Entering App\Field::getFieldPermission: 9,reminder_time
#204 [trace] Entering App\Field::getFieldsPermissions: 9
#205 [trace] Entering App\Field::getFieldPermission: 16,reminder_time
#206 [trace] Entering App\Field::getFieldsPermissions: 16
#207 [trace] Entering App\Field::getFieldPermission: 9,reminder_time
#208 [trace] Entering App\Field::getFieldsPermissions: 9
#209 [trace] Entering App\Field::getFieldPermission: 16,reminder_time
#210 [trace] Entering App\Field::getFieldsPermissions: 16
#211 [trace] Entering App\Field::getFieldPermission: 9,reapeat
#212 [trace] Entering App\Field::getFieldsPermissions: 9
#213 [trace] Entering App\Field::getFieldPermission: 16,reapeat
#214 [trace] Entering App\Field::getFieldsPermissions: 16
#215 [trace] Entering App\Field::getFieldPermission: 9,reapeat
#216 [trace] Entering App\Field::getFieldsPermissions: 9
#217 [trace] Entering App\Field::getFieldPermission: 16,reapeat
#218 [trace] Entering App\Field::getFieldsPermissions: 16
#219 [trace] Entering App\Field::getFieldPermission: 9,recurrence
#220 [trace] Entering App\Field::getFieldsPermissions: 9
#221 [trace] Entering App\Field::getFieldPermission: 16,recurrence
#222 [trace] Entering App\Field::getFieldsPermissions: 16
#223 [trace] Entering App\Field::getFieldPermission: 9,recurrence
#224 [trace] Entering App\Field::getFieldsPermissions: 9
#225 [trace] Entering App\Field::getFieldPermission: 16,recurrence
#226 [trace] Entering App\Field::getFieldsPermissions: 16
#227 [trace] Entering App\Field::getFieldPermission: 9,link
#228 [trace] Entering App\Field::getFieldsPermissions: 9
#229 [trace] Entering App\Field::getFieldPermission: 16,link
#230 [trace] Entering App\Field::getFieldsPermissions: 16
#231 [trace] Entering App\Field::getFieldPermission: 9,link
#232 [trace] Entering App\Field::getFieldsPermissions: 9
#233 [trace] Entering App\Field::getFieldPermission: 16,link
#234 [trace] Entering App\Field::getFieldsPermissions: 16
#235 [trace] Entering App\Field::getFieldPermission: 9,process
#236 [trace] Entering App\Field::getFieldsPermissions: 9
#237 [trace] Entering App\Field::getFieldPermission: 16,process
#238 [trace] Entering App\Field::getFieldsPermissions: 16
#239 [trace] Entering App\Field::getFieldPermission: 9,process
#240 [trace] Entering App\Field::getFieldsPermissions: 9
#241 [trace] Entering App\Field::getFieldPermission: 16,process
#242 [trace] Entering App\Field::getFieldsPermissions: 16
#243 [trace] Entering App\Field::getFieldPermission: 9,subprocess
#244 [trace] Entering App\Field::getFieldsPermissions: 9
#245 [trace] Entering App\Field::getFieldPermission: 16,subprocess
#246 [trace] Entering App\Field::getFieldsPermissions: 16
#247 [trace] Entering App\Field::getFieldPermission: 9,subprocess
#248 [trace] Entering App\Field::getFieldsPermissions: 9
#249 [trace] Entering App\Field::getFieldPermission: 16,subprocess
#250 [trace] Entering App\Field::getFieldsPermissions: 16
#251 [trace] Entering App\Field::getFieldPermission: 9,followup
#252 [trace] Entering App\Field::getFieldsPermissions: 9
#253 [trace] Entering App\Field::getFieldPermission: 16,followup
#254 [trace] Entering App\Field::getFieldsPermissions: 16
#255 [trace] Entering App\Field::getFieldPermission: 9,followup
#256 [trace] Entering App\Field::getFieldsPermissions: 9
#257 [trace] Entering App\Field::getFieldPermission: 16,followup
#258 [trace] Entering App\Field::getFieldsPermissions: 16
#259 [trace] Entering App\Field::getFieldPermission: 9,linkextend
#260 [trace] Entering App\Field::getFieldsPermissions: 9
#261 [trace] Entering App\Field::getFieldPermission: 16,linkextend
#262 [trace] Entering App\Field::getFieldsPermissions: 16
#263 [trace] Entering App\Field::getFieldPermission: 9,linkextend
#264 [trace] Entering App\Field::getFieldsPermissions: 9
#265 [trace] Entering App\Field::getFieldPermission: 16,linkextend
#266 [trace] Entering App\Field::getFieldsPermissions: 16
#267 [trace] Entering App\Field::getFieldPermission: 9,description
#268 [trace] Entering App\Field::getFieldsPermissions: 9
#269 [trace] Entering App\Field::getFieldPermission: 16,description
#270 [trace] Entering App\Field::getFieldsPermissions: 16
#271 [trace] Entering App\Field::getFieldPermission: 9,description
#272 [trace] Entering App\Field::getFieldsPermissions: 9
#273 [trace] Entering App\Field::getFieldPermission: 16,description
#274 [trace] Entering App\Field::getFieldsPermissions: 16
#275 [trace] Start DateTimeField::convertToDBFormat s:10:"2018-01-03";
#276 [trace] End DateTimeField::convertToDBFormat
#277 [trace] DateTimeField::getDBInsertDateTimeValue
#278 [trace] Start DateTimeField::getDBInsertDateValue(2018-01-03 09:00:00)
#279 [trace] Start DateTimeField::__convertToUserFormat s:10:"2018-01-03"; | yyyy-mm-dd
#280 [trace] End DateTimeField::__convertToUserFormat
#281 [trace] Start DateTimeField::convertToDBTimeZone(2018-01-03 09:00:00)
#282 [trace] Start DateTimeField::convertTimeZone(2018-01-03 09:00:00, Europe/Sarajevo, Europe/Warsaw)
#283 [trace] End DateTimeField::convertTimeZone
#284 [trace] End DateTimeField::convertToDBTimeZone
#285 [trace] End DateTimeField::getDBInsertDateValue
#286 [trace] Start DateTimeField::getDBInsertTimeValue(2018-01-03 09:00:00)
#287 [trace] Start DateTimeField::convertToDBTimeZone(2018-01-03 09:00:00)
#288 [trace] Start DateTimeField::convertTimeZone(2018-01-03 09:00:00, Europe/Sarajevo, Europe/Warsaw)
#289 [trace] End DateTimeField::convertTimeZone
#290 [trace] End DateTimeField::convertToDBTimeZone
#291 [trace] End DateTimeField::getDBInsertTimeValue
#292 [trace] Start DateTimeField::convertToDBFormat s:10:"2018-01-03";
#293 [trace] End DateTimeField::convertToDBFormat
#294 [trace] DateTimeField::getDBInsertDateTimeValue
#295 [trace] Start DateTimeField::getDBInsertDateValue(2018-01-03 10:00:00)
#296 [trace] Start DateTimeField::__convertToUserFormat s:10:"2018-01-03"; | yyyy-mm-dd
#297 [trace] End DateTimeField::__convertToUserFormat
#298 [trace] Start DateTimeField::convertToDBTimeZone(2018-01-03 10:00:00)
#299 [trace] Start DateTimeField::convertTimeZone(2018-01-03 10:00:00, Europe/Sarajevo, Europe/Warsaw)
#300 [trace] End DateTimeField::convertTimeZone
#301 [trace] End DateTimeField::convertToDBTimeZone
#302 [trace] End DateTimeField::getDBInsertDateValue
#303 [trace] Start DateTimeField::getDBInsertTimeValue(2018-01-03 10:00:00)
#304 [trace] Start DateTimeField::convertToDBTimeZone(2018-01-03 10:00:00)
#305 [trace] Start DateTimeField::convertTimeZone(2018-01-03 10:00:00, Europe/Sarajevo, Europe/Warsaw)
#306 [trace] End DateTimeField::convertTimeZone
#307 [trace] End DateTimeField::convertToDBTimeZone
#308 [trace] End DateTimeField::getDBInsertTimeValue
#309 [error] purifyByType: Remote Help || BadRequest
#310 [error] ERR_NOT_ALLOWED_VALUE||Remote Help => vendor/yetiforce/Purifier.php:345

**Comment by bpabiszczak** [comment]
Czyli prawidłowo... do tego słownika nie można nic dodawać :] Jest "na sztywno" obsługiwany w kodzie w wielu miejscach. Jeżeli można modyfikować ten słownik w panelu, w kolejnej wersji zapewne zostanie to wyłączone.

**Comment by ResqIT** [comment]
Ok, czyli od wersji 4.3, w kalendarzu można obsługiwać tylko spotkania, zadania i telefony? W jaki sposób w systemie poprawnie obsługiwać inne typy działań nie związane bezpośrednio z marketingiem/handlem, a nie mieszczące się w kategorii zgłoszeń/problemów? Dodatkowo, dlaczego nie dotyczy to każdego z dopisanych do słownika wyrażeń?

**Comment by bpabiszczak** [comment]
Od zawsze czyli od 14 lat. Jest to jeszcze zaszłość po Vtiger, która wymaga przepisania. 
Dwóch ostatnich zdań nie rozumiem.

**Comment by ResqIT** [comment]
Z moich testów wynikało, że nie wszystkie dopisane wyrażenia powodowały błąd. W moim wypadku typ awaria nie powodował błędu, ale obsługa już tak. Mam pytanie czy system przewiduje obsługę w kalendarzu innych typów zadań/zdarzeń? Z odpowiedzi wyżej wynika, że nie i że już tak zostanie.
W niezrozumianym zdaniu chodziło mi o to, że  typ spotkanie i telefon dotyczą bardziej marketingu/handlu, obsługa zgłoszeń z modułu wsparcia raczej incydentów. Projekty w moim rozumieniu to proces tworzenia czegoś. 
W firmie zajmujemy się usługami i te dopisane typy obsługa/zdalna pomoc są nam potrzebne do monitorowania ciągłości usług, rozliczania różnych form działań. Do wersji 4.3 działało to bez zarzutu, choć w wersji 4.2 przestały na chwilę działać raporty rozliczeniowe(O dziwo w 4.3 działają znów bez zarzutu)

**Comment by bpabiszczak** [comment]
Problem pewnie stwarzają polskie znaki typu ł, ó, ż itd. Ale to są widoczne błędy, zapewne po takich zmianach przestaje działać wiele innych rzeczy takich jak CalDAV. 

Oczywiście nie jest to prawidłowe działanie, tak jak pisałem, mechanizm ten wymaga przepisania, ale na chwilę obecną ma to bardzo niski priorytet, chyba, że jakiś klient za to zapłaci. 

Nadal nie rozumiem, czy z typami kalendarzowymi ma cokolwiek wspólnego ze zgłoszeniami czy projektami.

**Comment by echemik** [comment]
Moim zdaniem przepisanie modułu kalendarza to must have w Yetiforce - wg mnie to jego jedyna słaba strona. Yetiforce to CRM - dla większości procesów w systemach tej klasy to się obija o sprzedaż, a sprzedaż obija się o aktywności na Klientach. Różne typy zadań w kalendarzu (rodzaje) to pytanie każdego naszego Klienta przy każdym wdrożeniu. Dodajemy typy np. "Prezentacja", "Szkolenie" czy "Event u Klienta", dodajemy marki, dodajemy efekty handlowe spotkania itd. i to dlatego że Klienci nie chcą na to osobnych modułów - wystarczy poziom ogólności kalendarza.

Ogólnie formularz aktywności w kalendarzu zawsze jest przez nas rozbudowywany i wg mnie jako kluczowa funkcjonalność CRM powinien być wciągnięty w roadmap z najwyższym priorytetem.

**Comment by bpabiszczak** [comment]
Mam odmienne zdanie :] We wszystkich wdrożeniach kalendarz był wystarczający a nawet jeżeli ktoś ma potrzebę dodania typu zdarzenia to można to łatwo zrobić będąc programistą [przypuszczam że to kilka h pracy]. Jak na razie nie mieliśmy takiej potrzeby, ale żeby od razu przepisywać cały kalendarz... po co. Po drugie to temat na oddzielny wątek.
