### ISSUE TITLE
Password saving issue

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5942]
#### Issue

I tried to change password for one of user from admin user. In password changing modal I put new password and click `change password` button. Password changed successful message appears but in reality password not changed. User can't login with new password but can login with old.

I checked database values and after attempt to change password  value in database not changed.

I can't check this bug at GitDev because demo user password changed and I can't login. After some attempts to login at gitdev I received next message. 

![image](https://user-images.githubusercontent.com/8545791/35094244-c4b1cfba-fc55-11e7-9ea9-705c7453a6ef.png)

Upd 1. If new user added to system then `user_password` value is (NULL) in database.

#### Your Environment

* YetiForce Version used: 4.3.0

**Comment by vovpff** [comment]
I checked gitdev (4.3.71) now and found what there are available 3 fields at password chaging modal: old password,new password and confirmation. My local system (4.3.0) has only two fields: new password and confirmation.

**Comment by mariuszkrzaczkowski** [comment]
I created an update package for this patch, test it.
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.3.0

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks a lot for this fix. After update looks like password problem solved.

I noticed next thing. I has two system: Main and sandbox. Usually I make copy of my main system and copy of database to get actual sandbox. I checked password changing/user creation at sandbox system without fix and found what there are no problem. Strange.

**Comment by mariuszkrzaczkowski** [comment]
New problem new issue

**Comment by vovpff** [comment]
@mariuszkrzaczkowski ok
