### ISSUE TITLE
[BUG][4.3.71][Calendar] Event saved with state "Completed"

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#5948]
#### Issue
When I create an Event for today, it's created with de value of field State like Completed.
For example, this happens if I create an event on 18/01/2018 14:30 for the same day at 18:30.

#### Expected Behavior
Event's state must be "Planned"

#### How to trigger the error
![2018-01-18_14-34-04](https://user-images.githubusercontent.com/16593721/35103095-d3335f5c-fc5c-11e7-8592-80c10aaa7018.gif)

#### Your Environment

* YetiForce Version used: Latest version (4.3.71)
* Browser name and version: Google chrome
* Operating System and version: Windows 10

**Comment by vovpff** [comment]
@MacarenaReina Try to click to green button. Blue button marks event as completed!

![image](https://user-images.githubusercontent.com/8545791/35104189-2323b50e-fc79-11e7-8e8f-0d5a615af33f.png)
