### ISSUE TITLE
[QUESTION][4.3.74][Calendar] How can I add another field to Quick create view?

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#5955]
#### Question
How can I add an existing field ("Send notification" field) to Quick create view in Calendar module?
In other modules you can add it editing a field:
![2018-01-19_08-33-51](https://user-images.githubusercontent.com/16593721/35141699-bacf6806-fcf3-11e7-8481-aa1240c19841.png)

But on Calendar module you can't edit any field.

#### Your Environment
* YetiForce Version used: 4.3.74
* Browser name and version: Google Chrome
* Operating System and version: Windows 10

**Comment by vovpff** [comment]
@MacarenaReina try to choose Events in picklist:

https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=Events

**Comment by anderpydev** [comment]
In the Calendar module the possibility of editing is very limited.
Most basic changes require editing in the code, among others here https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/modules/Calendar

**Comment by WalterLuis** [comment]
try this:

in the table DataBase 'vtiger_field'
filter where the column 'tablename' = 'vtiger_activity'
change the column 'quickcreate' to 0 for activate
and change order of fields with 'quickcreatesequence'
