### ISSUE TITLE
[bug] unit price in logistic modules

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5963]
Selecting product in any logistics module do not update unit price field as did in v. 4.2

![gin2](https://user-images.githubusercontent.com/10330264/35157003-4d154176-fd3b-11e7-8cd6-efb5597c10e0.gif)

#### Your Environment

* YetiForce Version used: 4.3 -> dev
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@kpaulaha the same as #5774
