### ISSUE TITLE
[PL] Problem z dodawaniem nowego użytkownika 

### ISSUE THREAD

**Issue by k0pacz0v** [YetiForceCompany/YetiForceCRM#5973]
#### Issue

Podczas dodawania nowego użytkownika, wyświetla komunikat o niedozwolonej wartości w polu language (pl).

#### How to trigger the error

1. http://upscale.com.pl/wp-content/uploads/2018/01/yeti.jpg

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Chrome 63

**Comment by matteoms** [comment]
Czy problem występuje na gitdeveloper? https://gitdeveloper.yetiforce.com
Masz na myśli pole "Język"? U mnie działa poprawnie dodawanie nowego użytkownika w wersji 4.3.0

**Comment by k0pacz0v** [comment]
> Czy problem występuje na gitdeveloper? https://gitdeveloper.yetiforce.com
Nie, tam nie występuje.

Wybierając opcję dodania nowego użytkownika u siebie, nie widzę nawet formularza - od razu wyświetla komunikat o niedozwolonej wartości.

**Comment by matteoms** [comment]
Rozumiem,
Musisz wywołać błąd u siebie, nagrać go i zamieścić.
Załącz ostatnie wpisy po wywołaniu błędu z pliku cache/logs/phpError.log i ewentualnie komunikat z konsoli np. Chrome (F12/Console)

Jakiej wersji php używasz? System był aktualizowany z poprzedniej stabilnej wersji czy czysta instalacja?

**Comment by k0pacz0v** [comment]
Czysta instalacja. Mimo wywołania w logach nie mam phpError.log.

**Comment by matteoms** [comment]
Przełącz wersję php na 7.0.x lub najwyżej 7.1.x, nie jestem pewny, ale YF może nie wspierać jeszcze 7.2
Miałem na myśli plik phpError.log. Nie masz w nim żadnych wpisów?

Pokaż jeszcze screen z YF Administracja/Ustawienia/Logi/Serwer - konfiguracja

**Comment by mariuszkrzaczkowski** [comment]
@k0pacz0v phpError.log to tylko jeden plików logów i nie zawsze będzie istniał (zależy od konfiguracji serwera)
Do rozwiązania problemu potrzebne są wszystkie logi, zapoznaj się z artykułem: https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-programistyczna/item/debugowanie

**Comment by bpabiszczak** [comment]
System nie wspiera jeszcze 7.2, a więc zalecamy 7.0/7.1

**Comment by Pomazan-Bogdan** [comment]
Fatal error: Cannot use 'Object' as class name as it is reserved
7.2 php version

**Comment by Pomazan-Bogdan** [comment]
https://github.com/yiisoft/yii2/issues/14823

**Comment by Pomazan-Bogdan** [comment]
https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2012
