### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by GVNaidu79** [YetiForceCompany/YetiForceCRM#5980]
#### Issue

Yetiforce test demo site is not working

#### Expected Behavior

Unscrambled webpages
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 
* Browser name and version: Chrome and IE 11.
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
fixed
