### ISSUE TITLE
Customization calendar or reservation.

### ISSUE THREAD

**Issue by dkrakowski** [YetiForceCompany/YetiForceCRM#5981]
It is any posible to custiomization calendar or reservation, and change this module in to advance mode? 
It is any option in source code or data base to enable full layout ediotr fir this modules?
I using YF v.4.3.0

**Comment by bpabiszczak** [comment]
Domyślnie mechnizm "advance mode" jest mechanizmem testowym i powinien być używany przez programistów. Mechanizm ten nie został zaprojektowany dla takich modułów jak kalendarz i nie widzę nawet sensu biznesowego aby tam był. Od strony technicznej można zrobić wszystko [czyli zmodyfikować kod tak aby pokazywał się w tych modułach], ale wymaga to pracy programisty.

Edycja tych modułów została celowo zablokowana, ponieważ kalendarz jest integrowany z wieloma innymi mechanizmami np. DAV i każda modyfikacja pól w module mogłaby popsuć inne integracje. Od strony programistycznej można sobie tą blokadę "wyłączyć", ale nie zalecamy tego.
