### ISSUE TITLE
CalDAV synchronizer imports event of other users than mine

### ISSUE THREAD

**Issue by technologiegalwaniczne** [YetiForceCompany/YetiForceCRM#5992]
Hi

Is there any chance to avoid sync events that are the records of other users than mine? The DAV sync works flawless between Outlook and YF. The only problems is that now i have besides of my events the events of other DAV user in my Outlook calendar.
Is there any think to set up not to mix the events all together?

Two seperate DAV keys (one for each account) are used.

YF 4.3.0

Best regards
Maciej Janiak

**Comment by SALITEL** [comment]
In my case, DAV does not work on iOS or Google Calendar.
Validate the password, it does not give an error but it does not work.
(YF 4.3)

**Comment by mariuszkrzaczkowski** [comment]
> Is there any chance to avoid sync events that are the records of other users than mine? The DAV sync works flawless between Outlook and YF. The only problems is that now i have besides of my events the events of other DAV user in my Outlook calendar.
> Is there any think to set up not to mix the events all together?
> Two seperate DAV keys (one for each account) are used.

Everything depends on the owner of the event, if you set the correct one, every user will see only their events.
Not enough information so that we can help.

> In my case, DAV does not work on iOS or Google Calendar.
> Validate the password, it does not give an error but it does not work.
> (YF 4.3)

Such comments do not help.
If you have a problem, you must give a complete set of information on how we can call and check this error.
