### ISSUE TITLE
Find and merge duplicates...

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#5993]
Everything works, but when I had to combine two contacts, I do not know what to do? But the buton is missing.

https://gitdeveloper.yetiforce.com/index.php?module=Accounts&page=1&view=List&viewname=4&orderby=&sortorder=ASC&entityState=Active&search_params=%5B%5B%5B%22accountname%22%2C%22a%22%2C%22yeti%22%5D%5D%5D

**Comment by vovpff** [comment]
@fbojan This is bug. I found this bug some days ago but not issued by me.
Looks like scrollbar and button missed.

**Comment by vovpff** [comment]
@fbojan Why you closed issue?

**Comment by fbojan** [comment]
Sorry

**Comment by bpabiszczak** [comment]
The mechanism responsible for duplicates has been rewritten [we're still working on it], a new mechanism will be released in version 4.4 [stable] or 5.0 RC.
