### ISSUE TITLE
[question] Product prices

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#5996]
One thing that has bothered me for long, is the price of products. 
Would it not be more practical if the product would contain purchase price as basic? 
Now the unit(selling) price follows the product beginning from received notes, you hardly know the selling price when adding a new product to stock, the purchase price you probably know. You can add the purchase field to received notes advanced block, but would be nice to have it transmitted to product details. It would also make it easier to calculate the value of stock. The selling price could be added to products directly or by sales margin. 
Well that's just a thought.

One thing, that I miss from vtiger, is possibility to pick several products from the list when adding them to e.g. invoice.

**Comment by paula-w** [comment]
We will work on these processes in version 5.0, it's unfortunately going to take some time.

**Comment by kpaulaha** [comment]
Thank you for the note.

**Comment by ldgbc** [comment]
@kpaulaha How are you tackling this problem at the moment? My Invoice/Services is bugged can't fixed it so don't know if it work.

Let say, Laptop cost $100 to for us to buy from Manufacturer. But we will sell it for $110 so we input that into Price of Product per Unit.

But I want to know the initial cost so I decide to try this idea.

Price of Product as $100 and put commission as 110%, but like I said, not sure if that the way to go.

**Comment by manwenick** [comment]
@ldgbc @kpaulaha @paula-w 
Hello everyone!
I just trying to go all the process of B2C by an example. 
It also maybe make a sense, if the purchase price incl. VAT. 
I try to implement YetiForce for a manufacturing company. They have different prices of a product: 
Cost for materials: X
Cost for production: X
Cost for 2nd leven production:X
All of these cost equal to SELFCOST OF THE PRODUCT
Then they want to see the purchase price incl. VAT. As per now the price is net, without the VAT.
Also they want to have a SALE Price which need to be activated from date x to date x.
Did you have any requirements in the past like this?

**Comment by paula-w** [comment]
The new version (5.2) is going to include some fixes related to calculating prices, margins, discounts, and taxes. Descriptions of these mechanisms will soon be published on our website.
