### ISSUE TITLE
[BUG] Product name dispayed incorrect

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5999]
#### Issue

Products with long names displayed incorrect at advanced modules. My local system:

![image](https://user-images.githubusercontent.com/8545791/35374588-8ec1d300-01b4-11e8-9caf-c57c08ed36a2.png)

Dev 4.3.89

![image](https://user-images.githubusercontent.com/8545791/35374892-df743260-01b5-11e8-8c45-b254079d0968.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by KatarzynaUlichnowska** [comment]
Hello, could you explain us a bit more because we don't understand what is the problem?

**Comment by vovpff** [comment]
solved by changing pameter 
https://github.com/YetiForceCompany/YetiForceCRM/blob/122e735249ef6025b76da38b00920f80c1ebdde8/config/config.template.php#L149
