### ISSUE TITLE
All activities widget

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#6]
Currently there exist two widgets, one called "Upcoming Activities" and one called "Overdue Activities". I would suggest to add an additional widget called "Pending Activities" which would include all not completed activities and mark those that are overdue in red. Here are some excerpts how this could be done:

http://sourceforge.net/p/yetiforce/tickets/90/

**Comment by bpabiszczak** [comment]
We haven't received enough information about this issue, that's why we are closing it. If the problem appears in the future, please send us more detailed descriptions.
