### ISSUE TITLE
Gmail in own domain + smtp bug

### ISSUE THREAD

**Issue by pexter1983** [YetiForceCompany/YetiForceCRM#600]
Hi,
how configure SMTP serwer when i have gmail in own domain. 
When i make smtp.gmail.com, and user is my.name@mydomain.com, and password. it is not working. Why?

**Comment by waw555** [comment]
Check the settings

Here is an example of work corporate e-mail in another domain
![mailsettings](https://cloud.githubusercontent.com/assets/1402355/7271587/e22b8e5a-e8fd-11e4-8d4a-e6cd640fa6d6.JPG)

**Comment by pexter1983** [comment]
Thx,
and another questions:
1. Can i make relations with my e-mails and contact in my email acounts? In this moment all mail i must make one and one create relationship. Can i automations?

**Comment by waw555** [comment]
Please rephrase your question

**Comment by bpabiszczak** [comment]
Please use mail scanner. https://github.com/YetiForceCompany/YetiForceCRM/issues/595
