### ISSUE TITLE
How to create a custom widget?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6002]
#### Issue

I need a simple time widget for my employees.

#### Actual Behavior

I have a widget sample, but i don't know how to do it in YetiForce.

Here is a sample:
![widget](https://user-images.githubusercontent.com/30116021/35380370-bb47e3c6-01c1-11e8-8b9c-06ce140abc4a.png)

#### Expected Behavior

Need some instructions of how to do it.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
All you need to do is add a new type of widget, that is, files:
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Vtiger/dashboards/Calendar.php
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/layouts/basic/modules/Vtiger/dashboards/Calendar.tpl

Add a new class to the JS file like this one
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js#L2011

Add a widget to the database
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/install/install_schema/Base3.php#L3159

After doing this, the widget will be available in the widget management panel
