### ISSUE TITLE
Login page files

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6003]
#### Issue

I want to customize login page. I want to add an image on the left of page and move submit button on the down side of login form.

#### Actual Behavior

I don't know where is the login page file.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: 
* Environment name and version:
* Operating System and version:

**Comment by setras** [comment]
You can find the template in folder '/layouts/basic/modules/Users' and the css in 'public_html/layouts/basic/skins'

**Comment by konadrian** [comment]
\layouts\basic\modules\Users\Login.Default.tpl here you

**Comment by ldgbc** [comment]
That interesting. 

> you need to create Login.Custom.tpl 

Does that mean all TPL file, we can create a .Custom and it won't get overwrite?

On-topic: did you guy make any changes to those Login Page, can you share?

**Comment by mariuszkrzaczkowski** [comment]
> Does that mean all TPL file, we can create a .Custom and it won't get overwrite?

Yes

https://github.com/YetiForceCompany/YetiForceCRM/blob/48dfb0102a58c16f709a0adb2bff9411a3a5a61c/layouts/basic/modules/Users/Login.tpl#L12-L20
