### ISSUE TITLE
[an error occurred while processing this directive]

### ISSUE THREAD

**Issue by mikelakat** [YetiForceCompany/YetiForceCRM#6004]
#### Issue
Hello,

When i try to install the version zip file 4.2.0_to_4.3.0_v4.zip i receive the following error when i try to update it.
**[an error occurred while processing this directive]**

#### How to trigger the error

1. Software configuration
2.Standard modules
3.Modules – Installation

#### Your Environment

* YetiForce Version used: 4.2.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version: WIN7 and WIN10

**Comment by mikelakat** [comment]
any news with this issue?

**Comment by vovpff** [comment]
@mikelakat try here  Software configuration > Logs > Updates > System settings

**Comment by KatarzynaUlichnowska** [comment]
Hello,
we need more info. What do logs show? What's your configuration? Please send us also complete info about the environment and screenshots with the verification of configuration.
