### ISSUE TITLE
Error when importing the phones.

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#6006]
Good morning.I get an error when importing the phones.Generado por YetiforceCRM ver. 4.2.618PHP: 5.6.33Errores de configuración del servidor:PHP: 5.6.33output_buffering: 0innodb_lock_wait_timeout: 50Errores de librerías:apcu

**Comment by paula-w** [comment]
Please provide us with more info about the error.

**Comment by fbojan** [comment]
It was the same problem because I should have a format of +43 XXX XXX XX. I added +43 to all phone numbers and I could import them

**Comment by joelbcampos** [comment]
Thank you very much, I did what you told me the import was done correctly
