### ISSUE TITLE
Configuration phone aplication

### ISSUE THREAD

**Issue by pexter1983** [YetiForceCompany/YetiForceCRM#601]
How configure android aplication in mobile phone? CRM i generate api key, and in api.conf enable mobile options, but it not working.

**Comment by waw555** [comment]
Install a mobile application and enter your login and generated key in the application

**Comment by bpabiszczak** [comment]
Use this tool: https://test.yetiforce.com/index.php?parent=Settings&module=MobileApps&view=MobileKeys&block=5&fieldid=69
