### ISSUE TITLE
Help e mail template.

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#6020]
Help e mail template.When I copy the html code for an email template, yetiforce respects us styles. If I copy the same code in Vtiger 7.0 it works correctly. What is the difference between one and the other? How can I do to respect the stigma in yetiforce? It's one of the few things I have left to solve in Yetiforce. I am delighted with your work.Generado por YetiforceCRM ver. 4.2.618PHP: 5.6.33Errores de configuración del servidor:PHP: 5.6.33output_buffering: 0innodb_lock_wait_timeout: 50Errores de librerías:apcu

**Comment by joelbcampos** [comment]
![imagen sin titulo vtiger](https://user-images.githubusercontent.com/29610537/35484911-b18f2d4c-0457-11e8-979a-7505043c9c0b.png)
![imagen sin titulo yetiforce](https://user-images.githubusercontent.com/29610537/35484913-b7e4a708-0457-11e8-9a9b-a80af3533bc5.png)

Same html code copied in vtiger and Yetiforce, different behaviors.

**Comment by mariuszkrzaczkowski** [comment]
Send us an email template to check it out.

**Comment by joelbcampos** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <title>Glif mail</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic&subset=latin,cyrillic" rel="stylesheet" type="text/css">
    <style media="all" type="text/css">
*
    {
        -webkit-text-size-adjust:none;
        -ms-text-size-adjust:none
    }
    html
    {
        width:100%
    }
    body
    {
        width:100%;
        height:100%;
        margin:0;
        padding:0;
        background-color:#242636;
        -webkit-font-smoothing:antialiased
    }
    p
    {
        margin:0
    }
    .full-image img
    {
        width:100%!important
    }
    </style>
    <style type="text/css">
@media only screen and (max-width: 768px) {
        .main-table
        {
            width:100%!important;
            min-width:0!important;
            clear:both
        }       
        .image img
        {
            width:100%!important;
            height:auto!important
        }
    }
    @media only screen and (max-width: 640px) {
        .container
        {
            width:320px!important;
            min-width:0!important
        }       
        .inner
        {
            width:260px!important
        }       
        .m-cell
        {
            display:block!important;
            float:left!important;
            width:100%!important;
            max-width:none!important;
            min-width:0!important
        }       
        .m-w100
        {
            width:100%!important;
            max-width:none!important;
            min-width:0!important
        }       
        .img-bg,.header
        {
            background-size:cover
        }       
        .nav
        {
            width:100%!important;
            clear:both;
            text-align:center
        }       
        .nav .text
        {
            width:31%
        }       
        .h0
        {
            display:none!important
        }       
        .h34
        {
            height:34px!important;
            line-height:34px!important
        }       
        .h40
        {
            height:40px!important;
            line-height:40px!important
        }       
        .btn td,.btn-1 td
        {
            padding:0!important
        }       
        .btn td a
        {
            display:block;
            padding:12px 20px
        }       
        .btn-1 td a
        {
            display:block;
            padding:11px 19px
        }       
        .footer .text
        {
            text-align:center!important
        }
    }
    @media only screen and (max-width: 380px) {
        .container
        {
            width:280px!important
        }       
        .inner
        {
            width:220px!important
        }
    }
    </style>
  
  
  </head>
  <body style="-webkit-text-size-adjust: none; margin: 0; padding: 0; font-family: 'Open Sans', Arial, sans-serif; background-color: #242636; color: #494949;">
    <table width="100%" align="center" cellpadding="0" cellspacing="0" border="0" style="background-color: #242636;">
      
      
      <tr>
        <td class="h0" height="30" style="font-size: 1px; line-height: 30px;">&nbsp;
          
        </td>
      </tr>
      
      <tr>
        <td class="table-wrap">
          
       
          <table class="main-table" width="100%" align="center" cellpadding="0" cellspacing="0" border="0" style="margin: 0 auto; max-width: 800px; min-width: 700px;">
            <tr>
              <td class="layouts-here">
                
                
                <table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
                  <tr>
                <td class="header" style="background-position: center top; background-repeat: no-repeat; background-color: #555c80; background-image: url('https://ahorralis.com/ftpimages/email/glf/241.png');" background="https://ahorralis.com/ftpimages/email/glf/241.png" align="center">
                      
                      
                      <table class="container" style="margin: 0 auto; width: 560px;" width="560" border="0" align="center" cellspacing="0" cellpadding="0">
                        <tr>
                      <td class="spacer" style="font-size: 1px; line-height: 30px;" height="30">&nbsp;
                            
                          </td>
                        </tr>
                        <tr>
                          <td>
                            <table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
                              <tr>
                            <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: middle;" align="left">
                                  
                                  
                              <table class="m-w100" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" border="0" align="left" cellspacing="0" cellpadding="0">
                                    <tr>
                                  <td class="logo" style="border-collapse: collapse; font-size: 0; text-align: center;"></td>
                                    </tr>
                                  </table>
                                
                                </th>
                            <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: top; width: 20px; line-height: 20px;" width="20" height="20" align="left">&nbsp;
                                  
                                </th>
                            <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: middle;" width="320" align="right">
                                  
                                  
                                  <table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
                                    <tr>
                                      <td align="right">
                                        <table class="nav" border="0" cellspacing="0" cellpadding="0">
                                          <tr>
                                        <td class="text" style="color: #ffffff; font-family: 'Open Sans', Arial, sans-serif; font-size: 13px; line-height: 16px; text-align: center;">&nbsp;
                                              
                                            </td>
                                        <td class="spacer" style="font-size: 1px; line-height: 18px;" width="35">&nbsp;
                                              
                                            </td>
                                        <td class="text" style="color: #ffffff; font-family: 'Open Sans', Arial, sans-serif; font-size: 13px; line-height: 16px; text-align: center;">&nbsp;
                                              
                                            </td>
                                        <td class="spacer" style="font-size: 1px; line-height: 18px;" width="35">&nbsp;
                                              
                                            </td>
                                        <td class="text" style="color: #ffffff; font-family: 'Open Sans', Arial, sans-serif; font-size: 13px; line-height: 16px; text-align: center;">&nbsp;
                                              
                                            </td>
                                          </tr>
                                        </table>
                                      </td>
                                    </tr>
                                  </table>
                                
                                </th>
                              </tr>
                            </table>
                          </td>
                        </tr>
                        <tr>
                      <td class="spacer" style="font-size: 1px; line-height: 55px;" height="55">&nbsp;
                            
                          </td>
                        </tr>
                        <tr>
                      <td style="height: 345px;" height="345" align="center">
                            <table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
                              <tr>
                                <td align="center">
                              <table class="m-w100" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 540px;" width="540" border="0" align="center" cellspacing="0" cellpadding="0">
                                    <tr>
                                  <td class="h4" style="font-family: 'Raleway', Arial, sans-serif; line-height: 1.2; font-size: 18px; font-weight: 700; color: #ffffff; text-align: center;">
                                    <span style="color: #2d2827;">Nombre de la Empresa</span><br>
                                      </td>
                                    </tr>
                                    <tr>
                                  <td class="spacer" style="font-size: 1px; line-height: 8px;" height="8">&nbsp;
                                        
                                      </td>
                                    </tr>
                                    
                                    <tr>
                                  <td class="h1" style="font-family: 'Raleway', Arial, sans-serif; line-height: 1.2; font-size: 35px; font-weight: 700; text-align: center; color: #ffffff;">
                                    <span style="color: #767676;">PROPUESTA DE AHORRO ENERGÉTICO</span><br>
                                      </td>
                                    </tr>
                                    
                                    <tr>
                                  <td class="spacer" style="font-size: 1px; line-height: 25px;" height="25">&nbsp;
                                        
                                      </td>
                                    </tr>
                                    <tr>
                                  <td class="text" style="color: #ffffff; font-family: 'Open Sans', Arial, sans-serif; font-size: 14px; line-height: 24px; text-align: center;">
                                    <span style="color: #2d2827;">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis aute irure dolor.</span>
                                      </td>
                                    </tr>
                                    <tr>
                                  <td class="spacer" style="font-size: 1px; line-height: 34px;" height="34">&nbsp;
                                        
                                      </td>
                                    </tr>
                                    <tr>
                                      <td align="center">
                                        <table border="0" align="center" cellspacing="0" cellpadding="0">
                                          <tr>
                                        <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: top;" align="left">
                                              
                                              
                                          <table class="btn" style="min-width: 140px;" border="0" align="center" cellspacing="0" cellpadding="0">
                                                <tr>
                                              <td style="border-radius: 5px; font-family: 'Raleway', Arial, sans-serif; font-size: 13px; font-weight: 700; line-height: 1; padding: 12px 20px; text-align: center; background-color: #26ad75; color: #ffffff;">
                                                <a href="#" style="text-decoration: none; color: #ffffff;">ACEPTAR</a>
                                                  </td>
                                                </tr>
                                              </table>
                                            
                                            </th>
                                        <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: top; width: 20px; line-height: 15px;" width="20">&nbsp;
                                              
                                            </th>
                                        <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: top;" align="left">
                                              
                                              
                                          <table class="btn-1" style="min-width: 140px;" border="0" align="center" cellspacing="0" cellpadding="0">
                                                <tr>
                                              <td style="border-radius: 5px; font-family: 'Raleway', Arial, sans-serif; font-size: 13px; font-weight: 700; line-height: 1; padding: 11px 19px; text-align: center; border: 1px solid #f01313; color: #030203;">
                                                <a href="#" style="text-decoration: none; color: #030203;">MÁS <span style="color: #2d2827;">INFORMACIÓN</span></a>
                                                  </td>
                                                </tr>
                                              </table>
                                            
                                            </th>
                                          </tr>
                                        </table>
                                      </td>
                                    </tr>
                                  </table>
                                </td>
                              </tr>
                            </table>
                          </td>
                        </tr>
                        <tr>
                      <td class="spacer" style="font-size: 1px; line-height: 20px;" height="20">&nbsp;
                            
                          </td>
                        </tr>
                        <tr>
                          
                          
                      <td class="icon" style="border-collapse: collapse; font-size: 0; text-align: center;"></td>
                        
                        </tr>
                        <tr>
                      <td class="spacer" style="font-size: 1px; line-height: 40px;" height="40">&nbsp;
                            
                          </td>
                        </tr>
                      </table>
                
                    </td>
                  </tr>
                </table>
                
                
                <table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
                  <tr>
                <td class="img-bg" style="background-position: center top; background-repeat: no-repeat; background-color: #3e51b5; background-image: url('https://ahorralis.com/ftpimages/email/glf/6352.png');" background="https://ahorralis.com/ftpimages/email/glf/6352.png">
                      
                      
                      <table class="container" style="margin: 0 auto; width: 560px; min-width: 560px;" width="560" border="0" align="center" cellspacing="0" cellpadding="0">
                        <tr>
                      <td class="spacer" style="font-size: 1px; line-height: 45px;" height="50">&nbsp;
                            
                          </td>
                        </tr>
                        <tr>
                      <td style="height: 155px;" height="155">
                            <table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
                              <tr>
                            <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: top; width: 180px;" width="180" align="left">
                                  <table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
                                    <tr>
                                      
                                      
                                  <td class="h3" style="font-family: 'Raleway', Arial, sans-serif; line-height: 1.2; font-size: 20px; font-weight: 700; color: #ffffff;">
                                    <span style="color: #2d2827;">Más de 10 años</span><br>
                                    <span style="color: #2d2827;">de experiencia</span><br>
                                      </td>
                                    
                                    </tr>
                                    <tr>
                                  <td class="spacer" style="font-size: 1px; line-height: 9px;" height="9">&nbsp;
                                        
                                      </td>
                                    </tr>
                                    <tr>
                                      
                                      
                                  <td class="text" style="color: #ffffff; font-family: 'Open Sans', Arial, sans-serif; font-size: 14px; line-height: 24px;">
                                    <span style="font-family: verdana, geneva; font-size: 12px;"><strong><span style="font-weight: normal;"><span style="color: #2d2827;">Tenemos la experiencia y formación necesaria para la gestión de&nbsp;proyectos de eficiencia energética.</span><br></span></strong></span>
                                      </td>
                                    
                                    </tr>
                                  </table>
                                </th>
                            <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: top; width: 10px; line-height: 34px;" width="10" height="34" align="left">&nbsp;
                                  
                                </th>
                            <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: top; width: 180px;" width="180" align="left">
                                  <table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
                                    <tr>
                                      
                                      
                                  <td class="h3" style="font-family: 'Raleway', Arial, sans-serif; line-height: 1.2; font-size: 20px; font-weight: 700; color: #ffffff;">
                                    <span style="color: #2d2827;">Social</span><br>
                                        <br>
                                      </td>
                                    
                                    </tr>
                                    <tr>
                                  <td class="spacer" style="font-size: 1px; line-height: 15px;" height="15">&nbsp;
                                        
                                      </td>
                                    </tr>
                                    <tr>
                                      <td>
                                        
                                        
                                        <table border="0" align="left" cellspacing="0" cellpadding="0">
                                          <tr>
                                        <td class="icon" style="border-collapse: collapse; font-size: 0px; text-align: center; width: 25px; background-color: #57b53e; border-radius: 3px;" width="25"></td>
                                        <td class="spacer" style="font-size: 1px; line-height: 24px; width: 10px;" width="10">&nbsp;
                                              
                                            </td>
                                        <td class="icon" style="border-collapse: collapse; font-size: 0px; text-align: center; width: 25px; background-color: #57b53e; border-radius: 3px;" width="25">
                                          <a href="https://www.facebook.com/horralis" style="text-decoration: none; color: #ffffff;"><img src="https://ahorralis.com/ftpimages/email/glf/ico-facebook-footer.png" alt="" style="border: none;" width="25"></a>
                                            </td>
                                        <td class="spacer" style="font-size: 1px; line-height: 24px; width: 10px;" width="10">&nbsp;
                                              
                                            </td>
                                        <td class="icon" style="border-collapse: collapse; font-size: 0px; text-align: center; width: 25px; background-color: #57b53e; border-radius: 3px;" width="25"></td>
                                        <td class="spacer" style="font-size: 1px; line-height: 24px; width: 10px;" width="10">&nbsp;
                                              
                                            </td>
                                        <td class="icon" style="border-collapse: collapse; font-size: 0px; text-align: center; width: 25px; background-color: #57b53e; border-radius: 3px;" width="25"></td>
                                          </tr>
                                        </table>
                                      
                                      </td>
                                    </tr>
                                  </table>
                                </th>
                            <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: top; width: 10px; line-height: 34px;" width="10" height="34" align="left">&nbsp;
                                  
                                </th>
                            <th class="m-cell" style="font-weight: 400; padding: 0; vertical-align: top; width: 180px;" width="180" align="left">
                              <table class="m-w100" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 180px;" width="180" border="0" align="center" cellspacing="0" cellpadding="0">
                                    <tr>
                                      
                                      
                                  <td class="h3" style="font-family: 'Raleway', Arial, sans-serif; line-height: 1.2; font-size: 20px; font-weight: 700; color: #ffffff;">
                                    <span style="color: #2d2827;">Localización</span><br>
                                        <br>
                                      </td>
                                    
                                    </tr>
                                    <tr>
                                  <td class="spacer" style="font-size: 1px; line-height: 9px;" height="9">&nbsp;
                                        
                                      </td>
                                    </tr>
                                    <tr>
                                      
                                      
                                  <td class="text" style="color: #ffffff; font-family: 'Open Sans', Arial, sans-serif; font-size: 14px; line-height: 24px;"><span style="color: #2d2827;">C/ demo nº 6 4º Planta</span><br />
                                    <span style="color: #2d2827;"><a href="#" style="text-decoration: none; color: #2d2827;">900 000 000 / 600 000 000</a></span><br />
                                    <span style="color: #2d2827;">info@demo.com</span></td>
                                    
                                    </tr>
                                  </table>
                                </th>
                              </tr>
                            </table>
                          </td>
                        </tr>
                        <tr>
                      <td class="spacer" style="font-size: 1px; line-height: 50px;" height="50">&nbsp;
                            
                          </td>
                        </tr>
                      </table>
                
                    </td>
                  </tr>
                </table>
              
              </td>
            </tr>
            <tr>
              <td>
                
                
                <table class="footer" width="100%" align="center" cellpadding="0" cellspacing="0" border="0">
                  <tr>
                <td class="color-bg" style="background-color: #000000;" align="center">
                  <table class="container" style="margin: 0 auto; width: 560px;" width="560" border="0" align="center" cellspacing="0" cellpadding="0">
                        
                        
                        <tr>
                      <td class="spacer" style="font-size: 1px; line-height: 25px;" height="25">&nbsp;
                            
                          </td>
                        </tr>
                        
                        <tr>
                      <td style="height: 40px;" height="40">
                            <table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
                              <tr>
                                <td>
                                  
                                  
                              <table class="m-w100" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="250" border="0" align="left" cellspacing="0" cellpadding="0">
                                    <tr>
                                  <td class="text" style="color: #ffffff; font-family: 'Open Sans', Arial, sans-serif; font-size: 14px; line-height: 22px;"> Copyright &copy; 2018 Demo<br /></td>
                                    </tr>
                                  </table>
                                  
                              <table class="m-w100" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="250" border="0" align="right" cellspacing="0" cellpadding="0">
                                    <tr>
                                  <td class="text" style="color: #ffffff; font-family: 'Open Sans', Arial, sans-serif; font-size: 14px; line-height: 22px; text-align: right;">
                                    <a href="#" style="text-decoration: none; color: #ffffff;">Dar de Baja</a>|
                                      </td>
                                    </tr>
                                  </table>
                                </td>
                              </tr>
                            </table>
                          </td>
                        </tr>
                        
                        <tr>
                      <td class="spacer" style="font-size: 1px; line-height: 25px;" height="25">&nbsp;
                            
                          </td>
                        </tr>
                      
                      </table>
                    </td>
                  </tr>
                </table>
              
              </td>
            </tr>
          </table>
        
        </td>
      </tr>
    </table>
  </body>
</html>
