### ISSUE TITLE
[BUG][4.3.93][Reports/OSSTimeControl] Bad format date on field start date

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#6025]
#### Issue
I create a Report of Time Control module and start date and end date are showing in different formats.

#### Expected Behavior
See both date fields with the same format

#### How to trigger the error
![2018-01-29_12-34-54](https://user-images.githubusercontent.com/16593721/35510780-6350b58e-04f1-11e8-9197-b9570435ca00.png)

#### Your Environment

* YetiForce Version used: Latest version (4.3.93)
* Browser name and version: Google Chrome
* Operating System and version: Windows 10

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6538
