### ISSUE TITLE
[How to?] Workflow update field task with translated field

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6028]
#### Issue

My target to combine some data in one WYSIWYG field in products module. I tried to use concat function for this but I found what usage units value takes with original translation (stored in database).

Sample: `concat(product_name,' ед.изм.: ',usageunit)`. For English result is `Бла-бла-бла ед. изм.: kit`. For Russian: `Бла-бла-бла ед. изм.: kit`. Pick list value not translated.

How to achieve translated picklist value?

**Comment by konadrian** [comment]
It requires some programming in the code, It's not a funcionallity that can be configured in the panel for now.

**Comment by vovpff** [comment]
@konadrian I think this is bug and must be fixed because in this case not possible to use system for multilingual companies what users uses different languages
