### ISSUE TITLE
Please amend modules

### ISSUE THREAD

**Issue by TonyM15** [YetiForceCompany/YetiForceCRM#6030]
There is a thread about inventory modules but it seems to be not seen, so I going to mention it here.
Current sales process is not ready for production. It lacks of correctly designed modules and relations. 
Naming used in current modules is also confusing.
https://github.com/YetiForceCompany/YetiForceCRM/issues/5810

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6111
