### ISSUE TITLE
Edit button missing (YetiForce 4.3) running on Mochahost hosting provider 

### ISSUE THREAD

**Issue by batalhao** [YetiForceCompany/YetiForceCRM#6033]
#### Issue

I've installed YetiForce 4.3 version.

When I create a new record, Edit button and Transfer ownership are missing.

I am having the same problem of this issue : https://github.com/YetiForceCompany/YetiForceCRM/issues/5851

#### Actual Behavior

Edit button missing 

#### Expected Behavior

How can I make it appears? Is it a configuration?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.0 
* Browser name and version: Google Chrome
* Environment name and version: 
* Operating System and version:

**Comment by vovpff** [comment]
@batalhao check your web server parameters
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

**Comment by batalhao** [comment]
@vovpff Apparently everything it's Ok.  
Do you recommend other hosting provider?

**Comment by vetergetto** [comment]
Не говорю по английски
Была такая же проблема
Включил как на изображении
Появилась кнопка редактировать
_____________________________
I do not speak English
There was a similar problem
Included as in the image
There was a button edit #
![default](https://user-images.githubusercontent.com/35401659/35584396-fca1621e-0605-11e8-8bc5-fb731a29ec1e.png)

**Comment by batalhao** [comment]
Hi @vetergetto  thank you for you message.  I made this change. But, unfortunately  without success.  

Russian: http://bit.ly/2nqbBdo

**Comment by vovpff** [comment]
@batalhao As you can see here #5575 and here #5710 there are another problem but cause in configuration.
You can check on your first screenshot what record created information not appaer in Updates section. this means what something going wrong with server config. A lot of simmilar problems grows from incorrect configuration of db. Try to clarify one more time.
Check ability to edit in your user profile.

**Comment by batalhao** [comment]
Hi @vovpff 

Now I have flagged the **nd_pdo_mysql** Look like that this problem was solved. 
I'll check all other functions.  Thank you very much for you attention and support.

**Comment by batalhao** [comment]
Hi @vovpff

Now I have flagged the **nd_pdo_mysql**

Look like that this problem was solved.
I'll check all other functions. Thank you very much for you attention and support.

**Comment by vovpff** [comment]
@batalhao no problem. Thanks you!
