### ISSUE TITLE
[BUG] PDF Document settings: doesn't save language selection and selected by default settings

### ISSUE THREAD

**Issue by worldwidehigh** [YetiForceCompany/YetiForceCRM#6035]
#### Issue
PDF Document settings: doesn't save language selection and selected by default settings
![fff](https://user-images.githubusercontent.com/20869581/35580386-2bdba156-05e9-11e8-8dfa-b608a8c6e01b.gif)

In database it saves false language code.
![unbenannt](https://user-images.githubusercontent.com/20869581/35580434-57536b84-05e9-11e8-8a1f-0d0bbcffe5de.png)
![unbenannt1](https://user-images.githubusercontent.com/20869581/35580452-5d792710-05e9-11e8-9803-233265abbbb6.png)
#### Expected Behavior
All settings should be save.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome 63
* Operating System and version: WIN10

**Comment by konadrian** [comment]
On current version works fine https://gitdeveloper.yetiforce.com

**Comment by LukeLak** [comment]
I have the same issue. Doesn't save language selection. Can someone check this?

**Comment by LukeLak** [comment]
Have someone checked this?

**Comment by konadrian** [comment]
I checked this problem one more time, and it's saving choosen language.   Could you show how you trigger this problem on https://gitdeveloper.yetiforce.com

**Comment by kimborg** [comment]
Language seem to be saved while editing, but when the template is closes and reopened, the setting is not there. See atttached video:
[Pdf System Settings - Invoice template.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/2663910/Pdf.System.Settings.-.Invoice.template.zip)
