### ISSUE TITLE
[bug] CRM phone extension

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#6037]
CRM phone extension, in the latest release, accept only number with prefix and its country, instead, as I believe its more right, the phone extension would be extension for internal pbx, from integer number from 1 to 9999

![schermata 2018-01-31 alle 08 56 09](https://user-images.githubusercontent.com/5500935/35611206-a4d1b548-0664-11e8-8391-cc76eb4eda42.png)

**Comment by konadrian** [comment]
Use the field marked in red for internal phones.
![bez tytulu](https://user-images.githubusercontent.com/3193498/37648188-93fabc20-2c2e-11e8-9c51-7bc3b1521e9c.png)
