### ISSUE TITLE
[Question] Is it possible that the mail scanner does not automatically save the attachments to documents?

### ISSUE THREAD

**Issue by worldwidehigh** [YetiForceCompany/YetiForceCRM#6038]
Is it possible that the mail scanner does not automatically save the attachments to documents, because attachments such as logos and pixels are not relevant.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome
* Operating System and version: WIN10

**Comment by paula-w** [comment]
You can do it by disabling a fragment of code responsible for that [it can’t be done in the panel]. In the future we will skip “images” that are used in mail contents, then it should solve the problem of redundant attachments.

**Comment by worldwidehigh** [comment]
It would be good if you can adjust this from the panel.
