### ISSUE TITLE
[enhancement] Local link custom field

### ISSUE THREAD

**Issue by worldwidehigh** [YetiForceCompany/YetiForceCRM#6050]
It would be great if there could be a custom field where you can enter a clickable local url. Of course, an extension of the url field would also be conceivable.

**Comment by bpabiszczak** [comment]
It's not a limitation on the system side, all local links are blocked by BROWSERS due to security concerns [and rightfully so]. There are ways to disable that [in each browser it can be done in a slightly different way] and then local links will work. You can find in google how to disable that.

**Comment by worldwidehigh** [comment]
Yes I know but in the URL field I can not put links with file: ///. Yetiforce blocks these links.
