### ISSUE TITLE
Account Balance not updated with Invoices

### ISSUE THREAD

**Issue by aylanet2** [YetiForceCompany/YetiForceCRM#6069]
#### Issue
After creating inoice to an account , the account balance doesnt update to show the new balance including the invoice, while the last invoice date is updated correctly

Any Ideas?
#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: chrome & edge

**Comment by konadrian** [comment]
Error doesn't occur, we fixed this recently

**Comment by mariuszkrzaczkowski** [comment]
Added new job to the workflow that allows aggregation of any field dependent module
https://github.com/YetiForceCompany/YetiForceCRM/pull/6946
