### ISSUE TITLE
PDF - FIELD "sum_gross" - problem

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#6070]
#### Issue

I have a problem with the sum_gross field in pdf.
After adding it to the template, the system does not generate a file.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.0
* Browser name and version: any
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by zimart** [comment]
empty...

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging
