### ISSUE TITLE
A user can see the email details of another user

### ISSUE THREAD

**Issue by mercesdes192** [YetiForceCompany/YetiForceCRM#6075]
hello,
I logged in into the email account of one user and when i signed out and logged in with another user account and click on my mailbox. I was able to see the email contents of the previously logged in user.
I was thinking that every user should have access to their email box per their email address provided when setting up the user. I hope that is the case. if it is then what can i do to resolve the problem.
Thanks

**Comment by PercyP** [comment]
Hi,
I think these are settings issues. Go to administrator area and click on mail tools and Auto login - make sure the correct people are assigned to mailbox. Also, not sure, but think you need to look at Mailscanner settings to.

**Comment by bpabiszczak** [comment]
https://gitstable.yetiforce.com/index.php?parent=Settings&module=Mail&view=Autologin&block=8&fieldid=78
