### ISSUE TITLE
[bug or not] products_table_related_module

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#6076]
Wondering how LBL_PRODUCTS_TABLE_RELATED_MODULE in PDF creator works if I want e.g. to display also corrections of Goods Dispatched Note. Any idea? 
Had a boring Sunday, so tested this, but did not manage having it working.
![pdf system settings](https://user-images.githubusercontent.com/10330264/35766523-fdc8350c-08e2-11e8-8a17-b421ac975bd7.png)

**Comment by TomaszQr** [comment]
The functionality is available for PDF from the  "Goods Received Notes Corrections" module. Below you can find a screenshot with an example,
An example of this template is in the system by default. Please test it on https://gitdeveloper.yetiforce.com/
![6076](https://user-images.githubusercontent.com/14273211/39232270-0c24452c-486d-11e8-9a47-4a1fc175c4d3.png)

**Comment by kpaulaha** [comment]
Could not test it because of error, but I belive you that it works.
![2018-04-25 11_09_43-yetiforce_ error](https://user-images.githubusercontent.com/10330264/39233544-4f3f2e60-4879-11e8-81cf-2333036dfd86.png)

**Comment by KatarzynaUlichnowska** [comment]
It was an error in the test data and our devs are fixing it.

**Comment by kpaulaha** [comment]
Seems to work, great.
