### ISSUE TITLE
[Bug or Not] Newly added fields missing from input panel. 

### ISSUE THREAD

**Issue by dannypingpong** [YetiForceCompany/YetiForceCRM#6077]
#### Issue and Actual Behavior
A newly added field (type "value from the related module") is missing from the input input screen. Not sure if it's a bug, or anything I've missed in some configuration in the first place. 

#### Expected Behavior
After a newly added field is added in Project module, it should show up in the input panel when adding or editing a record in the Project module. 

#### How to trigger the error

1. Go to settings --> standard modules --> edit fields --> select "projects" module --> in the first block add a new field called project_clients. See below URL for screen shot. 
http://jkonline.ca/danny/yeti/y0.png

Field type = Values from the related module
Label name = Project Client(s)
Field name = project_clients
Table = Basic
Related module = Contacts
Related field = First name

2. The new field is saved, activated, and placed in the top position.
http://jkonline.ca/danny/yeti/y1.png

3. However, when going back to the main panel --> realization --> projects --> add a new record --> the newly added project_clients field is not showing up. 
http://jkonline.ca/danny/yeti/y2.png

#### My Environment
- YetiForce 4.3 running on A2 hosting Linux hosting. 
- Newest Chrome on Windows 7 

Thanks!

**Comment by kpaulaha** [comment]
The field works in list view. Add the fiels to a list filter and it displays the records from related module.

**Comment by dannypingpong** [comment]
Thanks kpaulaha! Could you please kindly let me know where to go to get that "add the field to a list filter" done?

After I got your your reply 13 hours ago, I spent hours searching in "standard modules", "search & filters", and many other place. Just can't find it! 

Do appreciate your time and support kpaulaha. I'm quite new to Yeti...

**Comment by kpaulaha** [comment]
Add related fields to a filter
![list](https://user-images.githubusercontent.com/10330264/35845514-739824a6-0b1b-11e8-919c-80c46be0ac92.png)
Wait for cron to finalize the work
![luettelo](https://user-images.githubusercontent.com/10330264/35845535-92a4a234-0b1b-11e8-94ea-b76c73dc647a.png)

**Comment by dannypingpong** [comment]
Thanks for reply! 

I don't know what happened but I've removed the entire Yeti installation, reinstalled it, and then everything works well. Now the newly added fields show up without any extra work.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/a62a1efb5ba08759d8d3cf870ad98d2156159a23/config/config.template.php#L203
