### ISSUE TITLE
[BUG][Mapping Mail][4.3.115] It does not allow to map an email from the outbox to an Account, Lead, Contact, etc.

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#6092]
#### Issue

You can not assign an email sent to an Account / Contact / Lead, but the Roundcube does allow me to do a mapping from the "Inbox"

#### How to trigger the error

![chrome_2018-02-06_14-37-06](https://user-images.githubusercontent.com/18419851/35865030-5169dfde-0b4b-11e8-9fdb-9a72d0f1338a.png)

Complete video [1.7mb]: https://puu.sh/zhSB9/1d6e05fd52.mp4

#### Your Environment

* YetiForce Version used: 4.3.115 (gitdeveloper.yetiforce.com)
* Browser name and version: Chrome 64
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: gitdeveloper.yetiforce.com

**Comment by mariuszkrzaczkowski** [comment]
Log

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging
