### ISSUE TITLE
SQLSTATE issues

### ISSUE THREAD

**Issue by hdemendieta** [YetiForceCompany/YetiForceCRM#6103]
I just installed the YetiForceCRM 4.3.0 on my server and it is running now on my server but with some issues: 

1. Cannot manage users or add new users. 

When I try to add or manage users, I tog the following error. 

2. A similar issue when try to add an account: 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone_extra' in 'field list'
Failed to prepare SQL: INSERT INTO `vtiger_account` (`accountid`, `accountname`, `account_no`, `phone`, `website`, `fax`, `otherphone`, `parentid`, `email1`, `employees`, `email2`, `ownership`, `industry`, `siccode`, `account_type`, `annualrevenue`, `emailoptout`, `vat_id`, `registration_number_1`, `registration_number_2`, `verification`, `no_approval`, `balance`, `payment_balance`, `legal_form`, `sum_time`, `inventorybalance`, `discount`, `creditlimit`, `last_invoice_date`, `active`, `accounts_status`, `phone_extra`, `fax_extra`, `otherphone_extra`) VALUES (:qp0, :qp1, :qp2, :qp3, :qp4, :qp5, :qp6, :qp7, :qp8, :qp9, :qp10, :qp11, :qp12, :qp13, :qp14, :qp15, :qp16, :qp17, :qp18, :qp19, :qp20, :qp21, :qp22, :qp23, :qp24, :qp25, :qp26, :qp27, :qp28, :qp29, :qp30, :qp31, :qp32, :qp33, :qp34)

Is there anyone who can help me to understand what is causing this and how to resolve it?  

Thanks in advance for your help!

**Comment by vovpff** [comment]
@hdemendieta check your web server configuration!
