### ISSUE TITLE
Github authorization required

### ISSUE THREAD

**Issue by hdemendieta** [YetiForceCompany/YetiForceCRM#6104]
On my new yetiForceCRM installation, at the software configuration there is a Github authorization request, Where can I get that information. 

1. Your www.github.com username
24 character long unique client code, generated during application registration
40 character long unique account access code. Token creation manual can be found here

Thanks in advance for your help.

**Comment by TomaszQr** [comment]
To authorization you must have 2 things your username and special token

1. Your www.github.com username - it's your username - hdemendieta
2. 24 character long unique client code, generated during application registration - In the current version it was remove but in version 4.3 or later you can fill your username 
3. 40 character long unique account access code. Token creation manual can be found here - Here https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/ there is instruction how to generate special token for your account
