### ISSUE TITLE
[BUG] Reports in Dashboard

### ISSUE THREAD

**Issue by mixvoip** [YetiForceCompany/YetiForceCRM#6113]
#### Issue

Report charts not working on dashboard.

#### Actual Behavior

function generateChartData()'s `this.getContainer().find('input[name=data]').val()` returns undefined, resulting in JSON decode error 'Unexpected token u in JSON at position 0'. The reason for this is that the report class is initialised with "#reportContentsDiv" as container, which doesn't exist.

#### Expected Behavior

The report class and the dashboard need to be using a unique selector to initialise the report class with (dashboard may have more than 1 report chart, so using a class or static id selector won't work).

#### How to trigger the error

1. create a report chart
2. use created chart to create widget
3. add created widget to dashboard

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome
* Environment name and version: Apache
* Operating System and version: CentOS

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6538
