### ISSUE TITLE
Opportunities Summary Page cannot search Contact to link to Opportunity

### ISSUE THREAD

**Issue by hamzka** [YetiForceCompany/YetiForceCRM#6114]
#### Issue

version 4.3:  Upgrade from 4.2, The Opportunity Summary page, contact section have a select contact icon however not working. 

#### Actual Behavior

On the stable GIT version site, no select contact icon, also the GIt Developer site.  If you go into the details you can select the contact to add to the opportunity.

#### Expected Behavior

Should be able to search of the contacts to link to the opportunity.

#### How to trigger the error

Always

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome
* Environment name and version: Windows 10 latest update
* Operating System and version:

**Comment by konadrian** [comment]
Error doesn't occur, we fixed this recently
