### ISSUE TITLE
Permission Inspector - now available for free!

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#6120]
When we created our first paid modules we promised that at some point they will become free and available for everyone. I’m happy to inform you that one of these modules – **Permission Inspector**  – is now available free of charge to everyone. 

It’s a very useful module that allows you to check who can access modules and records without having to analyze all permissions in the system separately.  It also displays the number of unread emails and changes for users, and whether or not they track changes. 

A more detailed description of the module can be found in our store: https://yetiforce.com/en/permission-inspector 

You can test Permission Inspector on the gitdeveloper version: https://gitdeveloper.yetiforce.com/index.php

![pi1](https://user-images.githubusercontent.com/13310141/36031532-56271322-0dab-11e8-898d-b80512dfae6c.png)
![pi2](https://user-images.githubusercontent.com/13310141/36031533-56447c46-0dab-11e8-8724-ba7fc3d6f2b0.png)

**Comment by readyfl** [comment]
Where is the free version as its still trying to charge 325.00? Thanks!

**Comment by mariuszkrzaczkowski** [comment]
In dev version , try https://gitdeveloper.yetiforce.com/index.php

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/144980399272ede76daa98b88fe9b5ce50fc644d

**Comment by PercyP** [comment]
Hi,

I cannot see it in the dev version (it is selected in the Module installation but there is no icon - am I missing something? Also, where can we download it? It is still showing as buy?

**Comment by mariuszkrzaczkowski** [comment]
Everything can be seen on the screenshot :)

**Comment by ldgbc** [comment]
Was there other PAID Module? I can't find them on the website.

**Comment by ldgbc** [comment]
Yes, want to see what other Paid module there was. I saw only those two but they both Poland only. 
Thanks.
