### ISSUE TITLE
LBL_NO_PERMISSIONS_FOR_THE_RECORD

### ISSUE THREAD

**Issue by readyfl** [YetiForceCompany/YetiForceCRM#6121]
#### Issue
When I try to edit an event on the calendar I get a error "LBL_NO_PERMISSIONS_FOR_THE_RECORD". I am using the same super admin account username that I used to create the event but it states I do not have permission. I also noticed if I tried clicking on the event on the calendar itself, it seems to freeze up and I have to refresh the page.

#### Actual Behavior
LBL_NO_PERMISSIONS_FOR_THE_RECORD - Permission Denied when I try to edit an event. See pics

#### Expected Behavior
I expect to be able to make changes to events.

#### How to trigger the error

1. Go to Calendar
2. Hover over the event and click the "edit" button
3. Error shows up.

#### Your Environment

* YetiForce Version used: ver. 4.3.0
<img width="1440" alt="screen shot 2018-02-09 at 11 15 20 am" src="https://user-images.githubusercontent.com/36305682/36037502-f9ecb30c-0d8a-11e8-8159-e52ca982e332.png">
<img width="1440" alt="screen shot 2018-02-09 at 11 15 32 am" src="https://user-images.githubusercontent.com/36305682/36037505-fa0ce820-0d8a-11e8-9dd2-cb972c43ab07.png">
<img width="1440" alt="screen shot 2018-02-09 at 11 15 35 am" src="https://user-images.githubusercontent.com/36305682/36037507-fa322716-0d8a-11e8-8345-8c34320f60c1.png">
<img width="1440" alt="screen shot 2018-02-09 at 11 15 50 am" src="https://user-images.githubusercontent.com/36305682/36037509-fa567af8-0d8a-11e8-8f44-2805b32664e8.png">

* Browser name and version: Firefox & internet explorer
* Environment name and version:
* Operating System and version: Mac & Windows

**Comment by mariuszkrzaczkowski** [comment]
you must show logs

**Comment by Rianek** [comment]
![29258430_1603259639711133_6235521747550994432_o](https://user-images.githubusercontent.com/36565310/37553184-0de5881c-29c3-11e8-8e72-d2675d94d2b0.png)
