### ISSUE TITLE
How do I edit contacts?

### ISSUE THREAD

**Issue by readyfl** [YetiForceCompany/YetiForceCRM#6122]
#### Issue
I cant find a way to edit any contact info. The only edit feature I find is the mass editing but that is not what I need. 
<img width="1440" alt="screen shot 2018-02-09 at 11 15 50 am" src="https://user-images.githubusercontent.com/36305682/36037636-5b8190e2-0d8b-11e8-8144-7d409e57299e.png">
![Uploading Screen Shot 2018-02-09 at 11.20.22 AM.png…]()
![Uploading Screen Shot 2018-02-09 at 11.20.33 AM.png…]()
![Uploading Screen Shot 2018-02-09 at 11.20.40 AM.png…]()
![Uploading Screen Shot 2018-02-09 at 11.21.00 AM.png…]()

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by Rianek** [comment]
![29258430_1603259639711133_6235521747550994432_o](https://user-images.githubusercontent.com/36565310/37553107-7d0cbbd6-29c1-11e8-93af-8db2d07dc755.png)
