### ISSUE TITLE
Duplikat dokumentu nie pokazuję się w widoku Kontrahent -> Dokumenty

### ISSUE THREAD

**Issue by kristek92** [YetiForceCompany/YetiForceCRM#6141]
Dzień dobry

Kiedy tworzę duplikat dokumentu i zapisuję go pod zmienioną nazwą to nie pokazuje on się jako dokument powiązany z danym kontrahentem (moduły - powiązania).
Ten sam dokument jest widoczny normalnie, gdy wchodzę w dokumenty i jest powiązany z danym kontrahentem.
Problem ten występuje na wersji demo 4.3.0 oraz na moim serwerze - również wersja 4.3.0.
Dołączam gif obrazujący problem, żeby było łatwiej zrozumieć o co mi chodzi.

![bug-dokumenty](https://user-images.githubusercontent.com/30728827/36103665-4bf6c17e-1010-11e8-95e8-f4aaed9edd30.gif)

**Comment by mariuszkrzaczkowski** [comment]
To nie jest błąd, dublowanie rekordu nie dubluje relacji
