### ISSUE TITLE
[GUI] dev 4.3.137 GUI broken

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6151]
#### Issue

1. Too big icons for activities in accounts module. 
2. Records preview list mode broken at all.

Check gif.

![guibroken1](https://user-images.githubusercontent.com/8545791/36159916-f879dd42-10f0-11e8-902c-da835b7dcf81.gif)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
No chance to click buttons under wrench button. Info pop-up over actions buttons
![guibroken2](https://user-images.githubusercontent.com/8545791/36160209-ac725888-10f1-11e8-92c4-f9e13e784fb7.gif)

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/36160512-6c66118e-10f2-11e8-9a62-11f55b02345e.png)

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/36160537-7c546816-10f2-11e8-8769-a5b17041452b.png)

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/36160557-88842c7a-10f2-11e8-8a66-e8dbb2652dda.png)

**Comment by bpabiszczak** [comment]
It's not a bug, it's a feature ;) 
We change libraries [bootstrap, Font Awesome, jQuery etc.] in the system, it will take about one month.

**Comment by vovpff** [comment]
@bpabiszczak I think so! Thanks for your attention!
