### ISSUE TITLE
Can't get access to Yetiforce from another computer

### ISSUE THREAD

**Issue by cornutaurus** [YetiForceCompany/YetiForceCRM#6153]
#### Issue
I downloaded an installed Yetiforce and installed to Xampp. It would be http://localhost/yetiforce and it would work on the computer I installed on. However, when I use another computer and put in http://192.168.1.1XX/yetiforce it doesn't work. It would turn into localhost/yetiforce and give me an error

How can I get for it to work when using another computer on the same local network?

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Firefox and Chrome
* Operating System and version: Windows 7, Windows 10 Home and Pro

**Comment by vovpff** [comment]
@cornutaurus check line `$site_URL = 'http://....';` in  `\config\config.inc.php`. This line must be `http://192.168.1.1XX/yetiforce/`

**Comment by cornutaurus** [comment]
Thank you. Got it to work.

**Comment by artcien** [comment]
How did you manage to fix it? 

I'm having the same problem, however, my yetiforce (ver 4.4) does not have that file \config\config.inc.php

**Comment by vovpff** [comment]
@artcien check your config folder files for `$site_URL =` string

**Comment by cornutaurus** [comment]
> 
> 
> How did you manage to fix it?
> 
> I'm having the same problem, however, my yetiforce (ver 4.4) does not have that file \config\config.inc.php

Hello, it has been a while. I'm don't use Xampp anymore and is using Linux now. I don't remember exactly where the location is, but you can search for the file. It might be just config.php or it could be the whole thing config.inc.php. 
Then when you open the file just search for $site_URL then put in the IP code
