### ISSUE TITLE
[question] attach file button on comment 

### ISSUE THREAD

**Issue by centoasa** [YetiForceCompany/YetiForceCRM#6161]
On gitstable and git developer the attach file button on comment no longer exists
Why?
![schermata 2018-02-15 alle 08 15 07](https://user-images.githubusercontent.com/5500935/36244871-6da3003e-1228-11e8-9dc0-b1d3ab8fc030.png) (image from vtiger demo)

**Comment by mariuszkrzaczkowski** [comment]
There has never been such a button, it is only in vtiger

**Comment by centoasa** [comment]
So it's impossible to reply or comment attaching a file?

**Comment by mariuszkrzaczkowski** [comment]
It is possible only someone has to order it

**Comment by ldgbc** [comment]
Hi @centoasa I think suppose you can try add a Relation to Comments and Link it to a documents
