### ISSUE TITLE
Błąd po upgrade

### ISSUE THREAD

**Issue by mmstrzelec** [YetiForceCompany/YetiForceCRM#6178]
Po przeprowadzeniu upgrade nie mogę się zalogować pojawia się tylko strona z takim komunikatem:
Błąd!!!

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'itsblwww_yeti1.s_yf_companies' doesn't exist Failed to prepare SQL: SELECT * FROM `s_yf_companies` WHERE `default`=:qp0

czy można coś zaradzić ( nie mam backupu)

**Comment by bpabiszczak** [comment]
proszę przesłać dane dostępowe na sla@yetiforce.com w tym FTP/MySQL, zobaczymy co się da zrobić

**Comment by mmstrzelec** [comment]
Ten problem został rozwiązany. Dostawca serwera miał kopie i odtworzył mi poprzednia instancję. Problem mam jednak z aktualizacją karta aktualizacji podaje że mam wersję 3.4.21 a w stopce jest . [ver. 3.4.0] 
Poproszę o informacje jakie aktualizacje i w jakiej kolejności powinienem zainstalować aby cieszyć się najnowszą wersją yetiForce?
[Aktualizacje_.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/1737592/Aktualizacje_.pdf)

**Comment by mmstrzelec** [comment]
Niestety nie do końca został rozwiązany. Nie mogą zalogować się na Roundcube z dowolnego użytkownika. Ponadto próba edycji danych użytkownika kończy się błędem 
Błąd!!!

Calling unknown method: App\DB::isTableExists()

wysyłam dane dostępowe

**Comment by bpabiszczak** [comment]
Ciesze się że kopię udało się odzyskać, odnośnie problemu pierwszego którym zapoczątkowałeś to naprawienie tego bez "kopii" zajęłoby kilka godzin, ponieważ tam nieudała się migracja i z tego co pamiętam tam był system kilka razy migrowany i "błędy" się nawarstwiły. 

Odnośnie jakichkolwiek błędów to trzeba niestety kupić pakiet wsparcia płatnego... chcieliśmy pomóc wcześniej ponieważ "utraciłeś" system, a teraz chcesz rozwiązać "mniejszy" problem i tutaj zalecamy wykupić stałą opiekę SLA.
