### ISSUE TITLE
php 7.2  not support

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [YetiForceCompany/YetiForceCRM#6184]
#### Issue
php 7.2  not support

Fatal error: Cannot use 'Object' as class name as it is reserved

https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2012

#### Your Environment

* YetiForce Version used: 4.3.0

**Comment by bpabiszczak** [comment]
Full support for PHP 7.2 will be in version 4.4 or 5.0

**Comment by mariuszkrzaczkowski** [comment]
Added support for php 7.2, 7.3 dev https://travis-ci.org/YetiForceCompany/YetiForceCRM
