### ISSUE TITLE
TextParser bug with cyrillic symbols

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6189]
#### Issue

I found here #4666 some information about new features available for TextParser.

![image](https://user-images.githubusercontent.com/8545791/36431533-e1b89756-1668-11e8-958e-4fa0e1f70787.png)

I tried this and notice what this feature not works with Russian symbols. My code for PDF/email:

```
$(recordsList : Contacts|firstname,lastname,modifiedtime|[[["lastname","a","Потапов"]]]|)$
$(recordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","vov"]]]|)$
```

Result is:

![image](https://user-images.githubusercontent.com/8545791/36431647-262d92b0-1669-11e8-8c17-c9750ca274d8.png)

**Comment by mariuszkrzaczkowski** [comment]
What is wrong in this example?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski if condition contains Cyrillic there are table not generated. String only appears. More detailed:

Code:
```
Condition with Russian
$(recordsList : Contacts|firstname,lastname,modifiedtime|[[["lastname","a","Потапов"]]]|)$
Condition with English
$(recordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","vov"]]]|)$
```

Result:

![image](https://user-images.githubusercontent.com/8545791/36466860-2cd1a1f4-16ed-11e8-8891-36158e0d2f7f.png)

Contact what I want to find:

![image](https://user-images.githubusercontent.com/8545791/36466890-4a7c727e-16ed-11e8-9571-852059cfa90a.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I tried getdev but no chance:

![image](https://user-images.githubusercontent.com/8545791/36467064-0e3d9562-16ee-11e8-96ce-c674b6fd734e.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski any suggestions?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski is it possible to implement this commit in 4.3?

**Comment by mariuszkrzaczkowski** [comment]
yes, copy this line
https://github.com/YetiForceCompany/YetiForceCRM/blob/ed07d4064c0041df20c1cc03d016441f3e7eb000/app/TextParser.php#L351

**Comment by vovpff** [comment]
@mariuszkrzaczkowski no chance. Line replacement works good now Cyrillic but not works with automatic filling with data (no difference what language). Check gif:
https://www.dropbox.com/s/in71qk9ku6igg3s/rel%20lists%20in%20pdf.gif?dl=0

**Comment by mariuszkrzaczkowski** [comment]
Give an example of the code that you used in PDF

**Comment by vovpff** [comment]
@mariuszkrzaczkowski 

```
$(recordsList : Contacts||[[["parent_id","c","$(record : accountid)$"]]]|)$
$(recordsList : Contacts||[[["parent_id","c","YetiForce Sp. z o.o."]]]|)$
$(recordsList : Contacts||[[["parent_id","c","Йетифорс Зоо"]]]|)$
```

**Comment by mariuszkrzaczkowski** [comment]
Right now you can't create rules where you place code in code. 
It's a very good idea but unfortunately we can't add it to the current version.
We might add it in version 5.x. If you want you can add a new issue marked as [Improvement] so we can remember about it.
