### ISSUE TITLE
Problem with import the data

### ISSUE THREAD

**Issue by Jurek1992** [YetiForceCompany/YetiForceCRM#6191]
Hello everybody 
How in title i Have a problem with import the data .
When I load the file I see something like this 
Warning: require_once(include/Webservices/VtigerModuleOperation.php): failed to open stream: No such file or directory in /home/fajna/public_html/crm/include/Webservices/Utils.php on line 384

Fatal error: require_once(): Failed opening required 'include/Webservices/VtigerModuleOperation.php' (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home/fajna/public_html/crm/include/Webservices/Utils.php on line 384
What should I do that it'll be corect?

**Comment by mariuszkrzaczkowski** [comment]
Duplicated #4827

**Comment by tidus1042** [comment]
Hey,

I have this problem too.
I saw your post and understood that the Importfix is doing the job.
Unfortunately, I can't download it at all from: 
https://github.com/YetiForceCompany/YetiForceCRM/releases.

Can someone please upload it to somewhere else or fix the link?
Thanks!
