### ISSUE TITLE
User or password invalid

### ISSUE THREAD

**Issue by hdemendieta** [YetiForceCompany/YetiForceCRM#6204]
I created a new user on YetiForce 4.3.0 using the administrator user account.  The new user was created ok, but I cannot log in usint the new user credentials. 

I don't know how to fix it.  

Thanks for your help

**Comment by mariuszkrzaczkowski** [comment]
Try  PasswordFix.zip 
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.3.0

**Comment by hdemendieta** [comment]
Thank you very much mariuszkrzaczkowski.  I did it and now its working fine.
