### ISSUE TITLE
Empty Gantt Chart

### ISSUE THREAD

**Issue by PioKrk** [YetiForceCompany/YetiForceCRM#6227]
#### Issue

Empty Gantt Chart.

#### Actual Behavior
![image](https://user-images.githubusercontent.com/36865007/36717571-e0e762f4-1b9e-11e8-867c-902da55dfc6b.png)

#### How to trigger the error

1. Create new project with tasks
2. Go to Gantt Chart

#### Your Environment

* YetiForce Version used: ver. 4.3.0
* Browser name and version: Google Chrome 64.0.3282, Microsoft Edge 41.16299, 
* Environment name and version: PHP 7.1.14
* Operating System and version: Linux sv61.ifastnet10.org 3.10.0-714.10.2.lve1.4.77.el7.x86_64 #1 SMP Tue Dec 5 17:19:40 EST 2017 x86_64 Server API - litespeed
-- | --

**Comment by kpaulaha** [comment]
fixed #5876

**Comment by bpabiszczak** [comment]
Work on GitDeveloper [ver. 4.3.182]]

**Comment by PioKrk** [comment]
Yes on production in https://sourceforge.net/projects/yetiforce/ the same problem.
![image](https://user-images.githubusercontent.com/36865007/36969154-f7a7e520-2064-11e8-9f35-9d6fe447d588.png)
Dev work fine. I will try it.

**Comment by mariuszkrzaczkowski** [comment]
Specially for you ProjectGanttFix.zip https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.3.0
