### ISSUE TITLE
[BUG] Row numbering

### ISSUE THREAD

**Issue by deniscuculic** [YetiForceCompany/YetiForceCRM#6231]
This happens when row numbering is added.

So, when i click add new record to Quotes, and then I'm adding service and deleting empty product row.
After that saving and exporting to pdf.

![row_number](https://user-images.githubusercontent.com/16257947/36738774-a8ca3cee-1bde-11e8-8d66-350043058f16.PNG)

This happens on gitstable aswell.

**Comment by vovpff** [comment]
@deniscuculic gitstable works not so perfect. try on gitdev or on local installation

**Comment by cltvchannel** [comment]
I have the same issue.
