### ISSUE TITLE
[IDEA]Auto update Currency Conversion

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#625]
It would be good to add an automatic data acquisition from the site of the central bank's current rate of these currencies and automatically convert them into the system when creating a manual or an invoice for payment

**Comment by bpabiszczak** [comment]
The problem with it is that there are always 2/3 places for every country to download data from. Additionally, every download has some parameters determining the type of conversion (we got 4 types in Poland). It's a very complex issue, I'm wondering how to solve this problem globally. We can build the possibility to obtain the rate from EBC, but in yours and other countries it would have to be obtained from other banks, and we don't really do that unless some client orders us to. 
Do you have any idea how to solve it universally?

**Comment by MaciejStencel** [comment]
Panel for configuring automatic currency exchange rates updates was added.

Please test it here:
https://gitdeveloper.yetiforce.com/index.php?module=CurrencyUpdate&view=Index&parent=Settings

By default there is only one currency set, for it to work properly you must atleast one more currency. For example russian rubles :)

https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Currency&view=List&block=4&fieldid=16

Now in the currency update settings you can choose from what central bank to download exchange rates. By default you can choose Polish National Bank or European Central Bank.

When you choose a bank it is automaticly set as active bank (used in automatic update by cron). By clicking buttons on the right you can check what crm currencies are supported and unsupported by this bank. Blue button shows supported currencies. If you choose bank that doesnt give rates for one of the system currencies, then there will be visible red button, when you click it it will show you what currencies are not supported.

In example below i chose ECB bank and one of crm active currencies ukrainian hrywna is not supported:
![no_uah](https://cloud.githubusercontent.com/assets/10218610/9415449/cc8cbbf4-483f-11e5-8d22-a0b93dcecaa8.png)

In the list below if you havent chosen any date yet you will see all downloaded rates in this month. 
In the above picture there is only one rate in history, russian rubble. From that list you can see that 1  Russian ruble = 0,05 Polish zloty (or 5 Grosze).

When you choose date youll see only rates from that date. If it wasnt earlier download it will be now.

NBP and ECB banks give rates only for work days not weekends. If you choose rate from present day it will fetch official rate from yesterday.


CRON:
There is added cron script that will be fetching currency rates everyday for yesterdays rate. It is set by default to run every 24h.

https://gitdeveloper.yetiforce.com/index.php?module=CronTasks&parent=Settings&view=List&block=4&fieldid=26

This script will also update system currency rates here:
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Currency&view=List&block=4&fieldid=16

Please test it and if you have any questions ask.

**Comment by waran70** [comment]
How to add bank?

**Comment by bpabiszczak** [comment]
Add new file here: https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/modules/Settings/CurrencyUpdate/models/BankModels

**Comment by MaciejStencel** [comment]
waran70 you can add new bank with little coding skills. As Błażej posted you need to create file in BankModels folder. It uses abstract class from folder above, but easiest way is to copy existing bank class, rename file and main class and change content of functions.

The most important function there is getRates() there programmer must put script that parses data from bank, most commonly xml file. There it must add new exchange rates to db or update existing ones. Rest functions are simply name of the bank, main/local currency of the bank, parsing of supported  currencies and soruces which are the links from where script fetches exchange rates.
