### ISSUE TITLE
How to cancel relation?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6251]
#### Issue

I has self made module what related to Contacts module. I checked what some relations are incorrect and I can't cancel relation between my module and Contact.

How to cancel relation?

![image](https://user-images.githubusercontent.com/8545791/36890551-6ebc47d0-1e0f-11e8-997d-41a40bbd9e55.png)

**Comment by vovpff** [comment]
Hey community! Any ideas?

**Comment by setras** [comment]
there are two ways:

1.  UI
- in config file 'developer.php' change entry ''CHANGE_RELATIONS' to true
- this will enable a new settings page where you can disable or delete the relations for a module
 Software configuration > Standard modules > Modules – Relations 

2. vtlib
 - see Step 5- https://www.vtiger.com/products/crm/help/5.2.0/VtigerCRM_5.2.0_Vtlib.pdf 
- https://wiki.vtiger.com/index.php/Vtlib_Related_Entities

**Comment by vovpff** [comment]
@setras sorry but you don't understand me.
I make an mistake and relate wrong record to contact. As I understand there are no possility to unrelate record back.

**Comment by setras** [comment]
Oh, I see normally when you delete the entry in the related list view it will only delete the relationship and not the record

![delete related](https://user-images.githubusercontent.com/10443220/37201988-975b7f7e-2389-11e8-9e85-060cc501eda9.gif)


But if you want to be on the safe site there is another option:
- For a 1:N (UItype 10 field) relation it is enough to clear the related field in the related module record

![grafik](https://user-images.githubusercontent.com/10443220/37200781-219bb34c-2386-11e8-9ad4-effb55abebe8.png)

- For a m:m relation you can delete the relation entry in the datebase table 'vtiger_crmentityrel' 
![grafik](https://user-images.githubusercontent.com/10443220/37200899-72a85d76-2386-11e8-8878-82badaeeb3b7.png)

**Comment by vovpff** [comment]
@setras thnx a lot!
