### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by mishapchen** [YetiForceCompany/YetiForceCRM#6258]
Hi!
I have a problem (or a misunderstanding) of how to use filters.

**Current situation**
When a list is opened by an admin the filter is working as defined in the filter configuration and set-up in the "menu configuration". When the same list is opened by a non-admin the only column shown is "assigned to" while none of the configured filters should show this column.

**Desired situation**
That the configured filter can both be viewed by admins as well as non-admins.

**When the error occurs**
When a list is viewed by a non-admin

Am I doing something wrong, overlooking or is this a bug?

Thank you in advance!

**Comment by vovpff** [comment]
@mishapchen looks like your non-admin user permissions are broken. I don't have solution for this. At first check non-admin profile permissions.
P.S. Maybe something going wrong at installation time. Usual cause incorrect server config.

**Comment by mishapchen** [comment]
Hi @vovpff , thank you for your reply!
All the permissions are set correctly for the profiles so it has to be an incorrect server configuration.

Could you advice me on which incorrect setting may cause the filter to not work? These are the errors:
Server configuration errors:
output_buffering: 4096
default_socket_timeout: 60
innodb_lock_wait_timeout: 50
wait_timeout: 60
interactive_timeout: 30
Library errors:
ldap_connect
opcache_get_configuration
apcu


Thank you in advance!!

**Comment by vovpff** [comment]
@mishapchen no idea for this time. Cron are activated? Maybe community can help

**Comment by mishapchen** [comment]
@vovpff Thank you for your help! I am relatively new to the YetiForce community and such; where can I find this community?

**Comment by vovpff** [comment]
@mishapchen this github is community. Welcome!

**Comment by vovpff** [comment]
@mishapchen pls take a screen or your CRON
Sample:
![image](https://user-images.githubusercontent.com/8545791/36979724-65807f24-2099-11e8-8256-18852f36e1ca.png)

**Comment by mishapchen** [comment]
@vovpff Ah, perfect! Thank you!

From comparing your screenshot and how mine looks I can almost certainly tell that CRON is not enabled:
![cron](https://user-images.githubusercontent.com/36995760/36995724-20ab8a26-20b5-11e8-9fcf-2fc076e7677c.png)

Though I have no clue on how to activate CRON

**Comment by vovpff** [comment]
@mishapchen I don't have big experience in hostings. My system works on local server.
For cron check this: https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron
