### ISSUE TITLE
Add Country Picklist field on Opportunity Module

### ISSUE THREAD

**Issue by nzi200779** [YetiForceCompany/YetiForceCRM#6269]
Is there a way i can add the countries table(u_yf_countries) as a picklist field on Opportunities Module?

**Comment by mishapchen** [comment]
I have been thinking about country pick lists as well; would it be an idea to have a country pick-list as a field type?

**Comment by nzi200779** [comment]
It is available on the Contacts Module, however i cannot get a way to link it to Opportunities. I want to be able to slice opportunities per country.

**Comment by mishapchen** [comment]
What I can think of currently is creating a module as a database, input all countries in there and link the opportunities to the countries.

I might look into this myself later today.

**Comment by nzi200779** [comment]
Let me know how you get along , thanks!

**Comment by mishapchen** [comment]
Did some quick work and got the following out of it:
- Module with all countries specified in the used document (`https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv`)
- Module should be used as a database; use the "Related Field"-type to use them

The module: `https://ufile.io/xsywh` - please note that the file will be deleted after 30 days

**Comment by vovpff** [comment]
@nzi200779 maybe this helps:
1. add text field to opportunity
2. change manually in your database uitype of this field from 1 to 35

**Comment by rafalpospiech** [comment]
Custom country field added in  https://github.com/YetiForceCompany/YetiForceCRM/pull/6647
