### ISSUE TITLE
Cebuano Localization

### ISSUE THREAD

**Issue by jbeguna04** [YetiForceCompany/YetiForceCRM#6270]
Hi Good Day! I would like to request to contribute in your project. Please allow me to have translation in Cebuano. Hoping for your positive response!
Thank You!

**Comment by waran70** [comment]
![fg-7](https://user-images.githubusercontent.com/6852348/37012699-9023a5aa-2128-11e8-91b0-eeedbaf17dd3.gif)

**Comment by jbeguna04** [comment]
what the meaning of this sir?

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
happy to hear you want to contribute to our project. 
Here is some information about it: https://yetiforce.com/en/open-source/contribution
If you want to send translations, you should do it by creating pull requests and GitHub explains how to do it: https://help.github.com/articles/creating-a-pull-request/ 
Let me know if you need more information.
