### ISSUE TITLE
Documentation: Web Server Requirements

### ISSUE THREAD

**Issue by suburbanworrier** [YetiForceCompany/YetiForceCRM#628]
On https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html

There are a handful of conflicting php.ini requirements listed under "Primary Configuration" and then contradicted in "Parameters enabled":
* zend.ze1_compatibility_mode
* session.auto_start
* magic_quotes_sybase
* magic_quotes_runtime

**Comment by suburbanworrier** [comment]
mysqli support isn't in the documentation but gets checked during installation

**Comment by bpabiszczak** [comment]
Fixed [tommorow we update en version].
