### ISSUE TITLE
Adding a Product to Price Book not functioning

### ISSUE THREAD

**Issue by fluidsc** [YetiForceCompany/YetiForceCRM#6291]
Adding a product to a Price Book does not function. Odds are I am doing something incorrectly? I was able to add a product to the Price Book when I created it, but upon adding a second product to the Products database, I cannot add that product to the Price Book

#### Actual Behavior

When I go to a Price Book and attempt to add a product from the Product tab, it walks me through the steps but the product is never added.

#### Expected Behavior
I expected the product to be listed in the price book.

#### How to trigger the error

1.Go to Sales and then Price Books
2. Open the desired Price Book
3. Click the Products tab and attempt to add a new product

Video available here: https://www.youtube.com/watch?v=MI9CaKW7ZTY

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Tried Chrome 64.0.3282.186 and Firefox 58.0.2
* Environment name and version: centos-release-6-9.el6.12.3.x86_64
* Operating System and version: Windows 10 build 16299.248

**Comment by kpaulaha** [comment]
As I remember it's not working properly in 4.3. Test it in dev.

**Comment by fluidsc** [comment]
I should have mentioned that it works on the YetiForce demo site. I literally just got Yetiforce. Is the demo site the same as dev? Are there instructions anywhere on installing the development branch if not, because I tried and it failed to work.

Sorry, I am absolutely new to Yetiforce (and vTiger). I have SuiteCRM up and running, and really would prefer this, as it seems far more flexible.

**Comment by TomaszQr** [comment]
Please test this functionality on the current developer version, https://gitdeveloper.yetiforce.com/
