### ISSUE TITLE
Cannot get images to display in pdf yetiforce v4.3x

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6296]
Hi,

Logo and other images will not display in pdf. I add the url for the pdf and the image does not display - only the missing image icon displays (little red cross).

I have ensured the cache/uploads is set at 777 but it still doesn't work. 

Can anyone suggest what else I can try?

Kind regards

**Comment by kpaulaha** [comment]
I have images in a root folder, working ok.
![pdf](https://user-images.githubusercontent.com/10330264/37217886-7cb95a72-23c7-11e8-84ba-5138e903ae76.png)

**Comment by PercyP** [comment]
Hi,
it seems it is just existing images that are not showing. I just tried adding a new image (without https:www.) and the images are inserting/showing. 

Thanks for your help
