### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6297]
Problem with yetiforce developer menus - opening and closing too quickly

was just testing developer version and there is a problem with the menus. The move too quickly so it is difficult to select a sub menu.
If you click on the parent menu the try to select a sub menu it closes before give a chance to select.

Regards

**Comment by fluidsc** [comment]
Just looked back at the development system. There is a gap to the left of the pop-out menu when you hover over a main menu item. Because of that margin, the menu closes when you attempt to go to a subitem.

**Comment by fluidsc** [comment]
This seems fixed now.

**Comment by PercyP** [comment]
Yes, just checked too - it is fixed :)
