### ISSUE TITLE
Change columns width

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6298]
#### Issue

I have removed some columns from invoice, and now i want to change the width of each column from Invoice PDF Template, and also i want to change characters limit for Item name column.
![invoicepdf](https://user-images.githubusercontent.com/30116021/37241830-5bd25fe2-2468-11e8-8091-7b1c3d6bdad8.png)

#### Actual Behavior

I searched on ProductsTable and ProductsTableNew and i don't have finded values for this.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Google Chrome
* Environment name and version: CPanel
* Operating System and version:CentOS

**Comment by vovpff** [comment]
@cltvchannel column width can de changed thru field editor. For character limitation I don't has ideas.
Greatest solution to prepare selfmade product table if you have coding experience.

**Comment by setras** [comment]
The table is rendered using the TextParser class.
In your PDF template the used TextParser ist called by the $(custom: xxx)$ variable e.g. $(custom : ProductsTableNew)$
The name of the called class is on the right of the colon. 'ProductsTableNew'. This calls the file with the same name in folder 'vendor/yetiforce/TextParser'. In there is the php code that creates the html table code.

**Comment by cltvchannel** [comment]
@setras hi.
i know where is the file, but i don't know what i need to change in the code for my request.

**Comment by setras** [comment]
@cltvchannel , 
before changing the code did you try as @vovpff  suggested to change the column witdh in the field editor. (sum of all field witdh settings must be 100)
![grafik](https://user-images.githubusercontent.com/10443220/37437496-dfaab2a0-27ed-11e8-8f0b-205dc66a950c.png)

the character limit can be set in the config.inc.php file, variable: $listview_max_textlength

**Comment by cltvchannel** [comment]
@setras Thanks!
