### ISSUE TITLE
Bug Currency update

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#6311]
![currence update](https://user-images.githubusercontent.com/1402355/37329564-2107195c-26c0-11e8-9f05-e89796d77745.gif)

**Comment by kakarata** [comment]
Hi, I have same issue. Using version 4.3.0 installed from Softaculous on Cpanel (not using modsecurity).
Tested with Chrome and IE 11.

**Comment by mariuszkrzaczkowski** [comment]
logs

**Comment by WalterLuis** [comment]
Edit this line:
https://github.com/YetiForceCompany/YetiForceCRM/blob/ccb806c350bb4ead08b332a3c1296e48c438276e/modules/Settings/CurrencyUpdate/models/Module.php#L217

by this:
https://github.com/YetiForceCompany/YetiForceCRM/blob/ff0c3edf9dfdbaf64d52adece671cb86082a1887/modules/Settings/CurrencyUpdate/models/Module.php#L222

and it should work
