### ISSUE TITLE
Bug Units

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#6312]
Does not show the unit of measurement, in calculations, too, does not show

![bug unit](https://user-images.githubusercontent.com/1402355/37329827-f3503b3c-26c0-11e8-8e9a-e56016744346.gif)

**Comment by vovpff** [comment]
@waw555 как я на себе прочувствовал, ед. изм. цепляются только из продуктов. На данный момент это видимо нормальная ситуация. Попробуй поковырять базу данных для модулей (таблицы с _invmap на конце)

**Comment by vovpff** [comment]
@waw555 с любыми модулями кроме продуктов происходят какие-то чудеса.
