### ISSUE TITLE
Error transferring data

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#6313]
Data from the calculation is not transferred to the Offer, it is necessary to add goods and services

![bug data transfer](https://user-images.githubusercontent.com/1402355/37330179-11b37ea8-26c2-11e8-884b-60708a7622b3.gif)

**Comment by vovpff** [comment]
@waw555 не совсем правильно решение, но можно настроить mapping из расчета в квоту в 1 клик.

**Comment by waw555** [comment]
Не понял! Разве товары и услуги не должны переносится?

**Comment by vovpff** [comment]
@waw555 по логике должны, в тигре переносились. Тут не переносились начиная примерно с 3й версии.

**Comment by paula-w** [comment]
You must additionally add mapping in system configuration in order to make it work.
