### ISSUE TITLE
Limit results on widget.

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6321]
#### Issue

I want to create some widgets with statistics from invoices, customers etc.

#### Actual Behavior

I don't have an option to limit.
Example: Show only first 10 results.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Google Chrome
* Environment name and version: cPanel
* Operating System and version: CentOS

**Comment by epsilonsc** [comment]
Hi, @cltvchannel you can change limit result in  https://gitstable.yetiforce.com/index.php?module=Widgets&parent=Settings&view=Index&block=2&fieldid=58 by edit 
![obraz](https://user-images.githubusercontent.com/10506580/37401301-e95459e8-2787-11e8-9a0b-83c71ce66f12.png)

**Comment by cltvchannel** [comment]
@epsilonsc sorry. not on this widgets. i need to limit entries for dashboard widgets.

**Comment by KatarzynaUlichnowska** [comment]
Hello,
when you create an issue, please provide as much info as possible because we don't know which widgets you mean. It's best to add screenshots.

**Comment by konadrian** [comment]
Here you can change the limit 
![bez tytulu](https://user-images.githubusercontent.com/3193498/37591209-08b78198-2b6b-11e8-8458-83f1809320c5.png)

**Comment by cltvchannel** [comment]
@konadrian Is this option avabile for all types of widgets?

**Comment by konadrian** [comment]
It's depends on widget type

**Comment by cltvchannel** [comment]
@konadrian and how i can modify to be avabile for all types of widgets?

**Comment by konadrian** [comment]
It requires some programming in the code, It's not a funcionallity that can be configured in the panel

**Comment by cltvchannel** [comment]
@konadrian In the future this will be a great function, if will be implemented by default. I tested it on others crm and i think is great to have this function.

**Comment by cltvchannel** [comment]
@konadrian where is the code reponsabile for limit results for list widgets?
