### ISSUE TITLE
Zablokowanie duplikowania rekordów w kartotekach

### ISSUE THREAD

**Issue by totkom** [YetiForceCompany/YetiForceCRM#6322]
Witam, od miesiąca wdrażam yetiforce w swojej firmie i zatrzymałem się na pewnie prostym problemie do rozwiązania, już mówię.
Wersja najnowsza yetiforce zainstalowana
Problem: przy dodawaniu nowej kartoteki system pozwala dodać istniejącego już klienta. Jak zrobić aby sprawdzał czy istnieje już adres mailowy w bazie danych, aby nie powielać wpisów?
Z poważaniem
Jacek Jacheć

**Comment by bpabiszczak** [comment]
Kiedyś był pod to panel [DataAccess], ale został usunięty... Najlepiej napisać małą funkcje w JS która weryfikuje to co chcemy weryfikować [np. NIP czy występuje w bazie]. Na pewno wymaga to drobnej pracy programisty [pewnie 2-6h w zależności od tego co chcemy osiągnąć]
