### ISSUE TITLE
Convert Lead to Opportunity

### ISSUE THREAD

**Issue by nzi200779** [YetiForceCompany/YetiForceCRM#6333]
Hi, Im on version 4 and would like to know if i could convert Lead to Opportunity

According to this post , you should be able to
https://github.com/YetiForceCompany/YetiForceCRM/issues/1785

Currently can only convert Lead to Account

**Comment by KatarzynaUlichnowska** [comment]
If you want to have it in the "old" form, it requires programming. The simplest way is to create an Opportunity manually after the conversion from a Lead to an Account.

**Comment by nzi200779** [comment]
thank you!
