### ISSUE TITLE
Problem z dodaniem nowego użytkownika

### ISSUE THREAD

**Issue by SPartys** [YetiForceCompany/YetiForceCRM#6345]
Przy próbie dodania nowego użytkownika wyskakuje błąd 
Nieprawidłowe zapytanie. Niedozwolona wartość w polu language(pl).
Chodziło dobrze do czasu działań z ustawieniem poczty. 
![image](https://user-images.githubusercontent.com/37423090/37494564-9f0dcefa-28a9-11e8-8507-cb063329ac48.png)
Prośba może ktoś wie gdzie to można poprawić.

**Comment by bpabiszczak** [comment]
Jaka wersja systemu? Czy wgrano "poprawki"?

**Comment by SPartys** [comment]
System wgrany wczoraj więc pewnie zawiera poprawki
YetiForceCRM-4.3.0-complete
Z Github zrobione aktualizacje

**Comment by bpabiszczak** [comment]
Proszę wgrać wszystkie poprawki [są w tym samym miejscu czyli tutaj:  https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.3.0, w nazwie mają FIX].

**Comment by mariuszkrzaczkowski** [comment]
Proszę o zrzuty z weryfikacji konfiguracji oraz włączenie pełnych logów przed dodaniem uzytkownika.
