### ISSUE TITLE
Kategorie w produktach (pscategory)

### ISSUE THREAD

**Issue by totkom** [YetiForceCompany/YetiForceCRM#6359]
Witam, (najnowszy yetiforce)
Jak można zmienić kategorie.
Teraz są takie:
Sprzęt
Oprogramowanie
Aplikacje CRM
Antywirus
Kopia zapasowe

Gdzie można je edytować?

Mam nadzieję że pytanie nie będzie głupie ale chyba jestem ślepy.

Pozdrawiam
JJ

**Comment by konadrian** [comment]
Tutaj masz śćieżkę na https://gitdeveloper.yetiforce.com/index.php?module=TreesManager&parent=Settings&view=Edit&record=2

**Comment by totkom** [comment]
Dziękuję.
