### ISSUE TITLE
[BUG] Selecting "New added" PDF Templates in List

### ISSUE THREAD

**Issue by thesxw** [YetiForceCompany/YetiForceCRM#6373]
#### Issue
Issue shows up with infinite loading template while u change selected template to second one

#### My Personal fix is

hash this code as i do it will fix it for now and pdf's will load right away ;P
Its my fix so i assume to be in changelog of that pseudo fix ?
file name: PDF.js
directory:  MAIN YETI FOLDER\public_html\layouts\basic\modules\Vtiger\resources\PDF.js
code is arround 75 - 120 line
ofcorse i replace same code from PDF.js in PDF.min.js

> registerListViewCheckRecords: function (container) {
> 		var thisInstance = this;
> 		container.find('[name="pdf_template[]"]').on('change', function () {
> 			/*
> 			document.progressLoader = jQuery.progressIndicator({
> 				message: app.vtranslate('JS_PDF_RECALCULATING'),
> 				position: 'html',
> 				blockInfo: {
> 					enabled: true
> 				}
> 			});
> 			var selectedRecords = container.find('[name="selectedRecords"]').val();
> 			var selectedTemplates = [];
> 			container.find('[name="pdf_template[]"]:checked').each(function (i) {
> 				selectedTemplates[i] = jQuery(this).val();
> 			});
> 
> 			var params = {};
> 			params.data = {
> 				module: app.getModuleName(),
> 				action: 'PDF',
> 				mode: 'validateRecords',
> 				records: selectedRecords,
> 				view: app.getViewName(),
> 				templates: selectedTemplates
> 			};
> 			params.dataType = 'json';
> 			AppConnector.request(params).then(
> 					function (data) {
> 						var response = data['result'];
> 						if (data['success']) {
> 							container.find('[name="validRecords"]').val(JSON.stringify(response.valid_records));
> 							container.find('#recordsInfo').text(response.message);
> 							setTimeout(function () {
> 								document.progressLoader.progressIndicator({'mode': 'hide'})
> 							}, 500);
> 							thisInstance.validateSubmit(container);
> 						}
> 					},
> 					function (data, err) {
> 						app.errorLog(data, err);
> 					}
> 			);
> 			*/
> 		});
> 	},

**Comment by konadrian** [comment]
Could you give us more info about the bug some screens or gif will be helpful.

**Comment by thesxw** [comment]
i give u code that solve this problem ... for 3.1 YT version
i fix it by this so i cant show it i will try gimme sec

**Comment by thesxw** [comment]
![111111](https://user-images.githubusercontent.com/33422088/38134867-57897f8a-3415-11e8-8088-546226ad3c4a.jpg)

**Comment by thesxw** [comment]
here u go screenshot 
![111111](https://user-images.githubusercontent.com/33422088/38134933-9b2d7764-3415-11e8-881a-cfa906a42ed9.jpg)

**Comment by konadrian** [comment]
Error doesn't occur in current version
