### ISSUE TITLE
Mail not found in the database. Import mail manually

### ISSUE THREAD

**Issue by CobaJashi** [YetiForceCompany/YetiForceCRM#6376]
Two problems.

1.) E-mails are not assigned. Who has ideas for how we can solve this?

2.) All e-mails are created as a ticket. We do not want that. How can we turn this off?

#####

OSS module is loaded.

! [Image] (https://user-images.githubusercontent.com/20491699/37707069-02012d20-2d02-11e8-8147-dc75d2312187.png)

Scanner is loaded

! [Image] (https://user-images.githubusercontent.com/20491699/37707176-82065450-2d02-11e8-85f5-b9faba4a2685.png)

E-Mail search too

! [Image] (https://user-images.githubusercontent.com/20491699/37707235-bfecea40-2d02-11e8-8210-2ff1c4c881da.png)

Yeti cronjobs are active

! [Image] (https://user-images.githubusercontent.com/20491699/37707295-fcbda50e-2d02-11e8-93f2-67812cf3d2bd.png)

Our cronjobs are active

! [Image] (https://user-images.githubusercontent.com/20491699/37707411-5030bc30-2d03-11e8-8c4d-2306abd6e7fe.png)

Emails are not transferred to the organization. Manual import also does not work.

! [Image] (https://user-images.githubusercontent.com/20491699/37707558-cf54aabc-2d03-11e8-8f5b-b7eaf1af3ed7.png)

E-mail is not imported ...

! [Image] (https://user-images.githubusercontent.com/20491699/37707620-0f97a304-2d04-11e8-98a3-7e47b82f7b47.png)

... but a ticket is created  In threefold edition :-)

! [Image] (https://user-images.githubusercontent.com/20491699/37707663-3b6f8e1a-2d04-11e8-8b59-a14af17bbbf0.png)

E-mails in the Inbox / Inbox would all be imported into the tickets

! [Image] (https://user-images.githubusercontent.com/20491699/37707815-b7d7fea6-2d04-11e8-87e0-f934bcd7d34e.png)

#### Environment

Yeti Force 4.3
Chrome Version 64.0.3282.186 (Official Build) (64-bit)
PHP 7 / Webhosting Debian

**Comment by PercyP** [comment]
I have problems with email binding too - the first error I got was same as yours, then the toolbar (that allows you to attach emails to contacts etc. doesn't display. I have a custom email template, but have also tries with default Larry and still same issue.

**Comment by CobaJashi** [comment]
nobody has an idea?

**Comment by PercyP** [comment]
Did you ever manage to get it working?

**Comment by CobaJashi** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Hello PercyP,
thank you very much for thinking of me, we have meanwhile switched to SuiteCRM. On the LTS version and are super satisfied.

But thanks a lot again for thinking of me.


Best Regards
Dragan Nikolic

Telefon: 0157 - 30 4787 30
Email: nd@computerbutler.de
Web: www.computerbutler.de

Berlin, Stuttgart, Frankfurt, Nürnberg, München, Regensburg


PercyP schrieb am 12.05.2018 16:20:


@CobaJashi

If it helps you, I fixed mine. The solution is here:

#6753
