### ISSUE TITLE
Developer version install error.

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6377]
#### Issue

I have tried to install developer version on Wamp. Also i tried to install this on CentOS webserver with cPanel and get the same error.

#### Actual Behavior

When i try to install i get the following message:

Warning: require(C:\wamp64\www\vendor\composer/../sabre/uri/lib/functions.php): failed to open stream: No such file or directory in C:\wamp64\www\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'C:\wamp64\www\vendor\composer/../sabre/uri/lib/functions.php' (include_path='.;C:\php\pear') in C:\wamp64\www\vendor\composer\autoload_real.php on line 66

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: Google Chrome
* Environment name and version: Wamp 3.1
* Operating System and version: Windows 10

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/4582

**Comment by cltvchannel** [comment]
@mariuszkrzaczkowski i have solved the problem with composer, but when i access http://127.0.0.1/install/Install.php and click on Install button, nothing happened.

**Comment by SkavenKF** [comment]
the same thing happens to me too (dev 4.3.236)
