### ISSUE TITLE
OSSPdf Translation

### ISSUE THREAD

**Issue by vctrin** [YetiForceCompany/YetiForceCRM#638]
Hi,

Please... What's "PNL" in line 29 of OSSPdf file [TAXES_IN_PLN' => 'Tax in PLN',]?

Best regards,

Valmir

**Comment by maikst** [comment]
Google is your friend

http://de.wikipedia.org/wiki/PLN

2015-04-24 16:45 GMT+02:00 Valmir C Trindade <notifications@github.com>:

**Comment by vctrin** [comment]
Sorry, but you don't helped me! Before I post this question I searched in our friend Google. The Google search is always my practice. The "PLN" term/acronym is very subjective [See content in Wikipedia link that you sent]. Maybe for you, it may be obvious, but for me not. We live in another reality, another country/language and isn't easy for us understand certain terms, maybe commonly used in your country or region. If you know what signify this term/acronym, why you don't speak and contribute with your knowledge?

**Comment by maikst** [comment]
Sorry.
The company who is working on Yeti comes from Poland...
So, PLN is the currency in Poland.

Have a nice weekend
Maik


2015-04-24 17:50 GMT+02:00 Valmir C Trindade <notifications@github.com>:

**Comment by vctrin** [comment]
Hi Maik... thanks!

Have a nice weekend too.

Valmir
