### ISSUE TITLE
[BUG][4.3.242] Incorrect request in forms with inventory

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#6392]
#### Issue

If you do not add any product / service in the inventory, give the following error:

        0 modules/Vtiger/inventoryfields/Name.php(79): App\Request->getInteger('name1')
        1 modules/Vtiger/models/Record.php(1194): Vtiger_Name_InventoryField->getValueFromRequest(Array, Object(App\Request), 1)
        2 modules/Vtiger/models/Record.php(431): Vtiger_Record_Model->initInventoryData()
        3 modules/Vtiger/actions/Save.php(80): Vtiger_Record_Model->save()
        4 modules/Vtiger/actions/Save.php(58): Vtiger_Save_Action->saveRecord(Object(App\Request))
        5 include/main/WebUI.php(183): Vtiger_Save_Action->process(Object(App\Request))
        6 index.php(25): Vtiger_WebUI->process(Object(App\Request))
        7 public_html/index.php(11): require('/home/gitdevelo...')
        8 {main}

        0 [trace] Entering getColumnFields(SQuoteEnquiries) method ...
        1 [trace] Exiting getColumnFields method ...
        2 [trace] Entering App\Field::getFieldPermission: 85,subject
        3 [trace] Entering App\Field::getFieldsPermissions: 85
        4 [trace] Entering App\Field::getFieldPermission: 85,subject
        5 [trace] Entering App\Field::getFieldsPermissions: 85
        6 [trace] Entering App\Field::getFieldPermission: 85,category
        7 [trace] Entering App\Field::getFieldsPermissions: 85
        8 [trace] Entering App\Field::getFieldPermission: 85,category
        9 [trace] Entering App\Field::getFieldsPermissions: 85
        10 [trace] Entering App\Field::getFieldPermission: 85,squoteenquiries_no
        11 [trace] Entering App\Field::getFieldsPermissions: 85
        12 [trace] Entering App\Field::getFieldPermission: 85,squoteenquiries_no
        13 [trace] Entering App\Field::getFieldsPermissions: 85
        14 [trace] Entering App\Field::getFieldPermission: 85,salesprocessid
        15 [trace] Entering App\Field::getFieldsPermissions: 85
        16 [trace] Entering App\Field::getFieldPermission: 85,salesprocessid
        17 [trace] Entering App\Field::getFieldsPermissions: 85
        18 [trace] Entering App\Field::getFieldPermission: 85,accountid
        19 [trace] Entering App\Field::getFieldsPermissions: 85
        20 [trace] Entering App\Field::getFieldPermission: 85,accountid
        21 [trace] Entering App\Field::getFieldsPermissions: 85
        22 [trace] Entering App\Field::getFieldPermission: 85,squoteenquiries_status
        23 [trace] Entering App\Field::getFieldsPermissions: 85
        24 [trace] Entering App\Field::getFieldPermission: 85,squoteenquiries_status
        25 [trace] Entering App\Field::getFieldsPermissions: 85
        26 [trace] Entering App\Field::getFieldPermission: 85,assigned_user_id
        27 [trace] Entering App\Field::getFieldsPermissions: 85
        28 [trace] Entering App\Field::getFieldPermission: 85,assigned_user_id
        29 [trace] Entering App\Field::getFieldsPermissions: 85
        30 [trace] Entering App\Field::getFieldPermission: 85,shownerid
        31 [trace] Entering App\Field::getFieldsPermissions: 85
        32 [trace] Entering App\Field::getFieldPermission: 85,shownerid
        33 [trace] Entering App\Field::getFieldsPermissions: 85
        34 [trace] Entering App\Field::getFieldPermission: 85,private
        35 [trace] Entering App\Field::getFieldsPermissions: 85
        36 [trace] Entering App\Field::getFieldPermission: 85,private
        37 [trace] Entering App\Field::getFieldsPermissions: 85
        38 [trace] Entering App\Field::getFieldPermission: 85,description
        39 [trace] Entering App\Field::getFieldsPermissions: 85
        40 [trace] Entering App\Field::getFieldPermission: 85,description
        41 [trace] Entering App\Field::getFieldsPermissions: 85
        42 [trace] Entering App\Field::getFieldPermission: 85,attention
        43 [trace] Entering App\Field::getFieldsPermissions: 85
        44 [trace] Entering App\Field::getFieldPermission: 85,attention
        45 [trace] Entering App\Field::getFieldsPermissions: 85
        46 [trace] Entering App\Field::getFieldPermission: 85,response_time
        47 [trace] Entering App\Field::getFieldsPermissions: 85
        48 [trace] Entering App\Field::getFieldPermission: 85,response_time
        49 [trace] Entering App\Field::getFieldsPermissions: 85
        50 [trace] Entering App\Field::getFieldPermission: 85,sum_time
        51 [trace] Entering App\Field::getFieldsPermissions: 85
        52 [trace] Entering App\Field::getFieldPermission: 85,sum_time
        53 [trace] Entering App\Field::getFieldsPermissions: 85
        54 [trace] Entering App\Field::getFieldPermission: 85,createdtime
        55 [trace] Entering App\Field::getFieldsPermissions: 85
        56 [trace] Entering App\Field::getFieldPermission: 85,createdtime
        57 [trace] Entering App\Field::getFieldsPermissions: 85
        58 [trace] Entering App\Field::getFieldPermission: 85,modifiedtime
        59 [trace] Entering App\Field::getFieldsPermissions: 85
        60 [trace] Entering App\Field::getFieldPermission: 85,modifiedtime
        61 [trace] Entering App\Field::getFieldsPermissions: 85
        62 [trace] Entering App\Field::getFieldPermission: 85,closedtime
        63 [trace] Entering App\Field::getFieldsPermissions: 85
        64 [trace] Entering App\Field::getFieldPermission: 85,closedtime
        65 [trace] Entering App\Field::getFieldsPermissions: 85
        66 [trace] Entering App\Field::getFieldPermission: 85,crmactivity
        67 [trace] Entering App\Field::getFieldsPermissions: 85
        68 [trace] Entering App\Field::getFieldPermission: 85,crmactivity
        69 [trace] Entering App\Field::getFieldsPermissions: 85
        70 [trace] Entering Vtiger_Record_Model::initInventoryData
        71 [info] SHOW TABLES || yii\db\Command::query
        72 [info] Opening DB connection: mysql:host=localhost;dbname=gitdevelop_crm;port=3306 || yii\db\Connection::open
        73 [info] SELECT * FROM `u_yf_squoteenquiries_invfield` WHERE `presence`=0 ORDER BY `sequence` || yii\db\Command::query
        74 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
        75 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
        76 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
        77 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
        78 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
        79 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
        80 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
        81 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
        82 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
        83 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
        84 [error] ERR_NOT_ALLOWED_VALUE||name1|| => app/Request.php:195

  - happend in Sales enquiries
  - happend in Sales requirements
  - happend in Calculations
  - happend in Quotes
  - happend in Sales Orders
  - happend in Recurring Sales Orders
  - happend in Vendor enquiries
  - happend in Invoices
  - happend in Proforma invoices
  - happend in Correcting Invoices
  - happend in Cost invoices
  - happend in Goods Received Note
  - happend in Goods Received Notes Corrections
  - happend in Goods Dispatched Notes Corrections
  - happend in Goods Dispatched Note
  - happend in Pre-order
  - happend in Storage Transfer Received Notes
  - happend in Storage Transfer Dispatched Notes

#### Your Environment

* YetiForce Version used: 4.3.242
* Browser name and version: Firefox 59
* Environment name and version: WampServer - PHP 7.1, MariaDB 10.2
* Operating System and version: Windows 10

**Comment by konadrian** [comment]
Can you trigger this error on gitdeveloper version https://gitdeveloper.yetiforce.com/index.php or give me some screens, gif

**Comment by WalterLuis** [comment]
of course: https://puu.sh/zTl0U/85f3519f1e.mp4

this bug is related in part to this other issue #6391, but, if it is normal that a record must necessarily have at least 1 product or 1 service, this issue can be closed.

**Comment by WalterLuis** [comment]
in 4.3.329 is working
