### ISSUE TITLE
[BUG] Workflow to send email is not working where I add event from quick create

### ISSUE THREAD

**Issue by echemik** [YetiForceCompany/YetiForceCRM#6402]
Issue
I add workflow, when add new event to calendar send email. Its working when I use full form to add event, but its not work if I add event from quick create form.

Actual Behavior
Email is not send

Expected Behavior
Email is send

Your Environment
YetiForce Version used: 4.3 (Stable)
Browser name and version: Google Chrome Version 64.0

**Comment by aljoflo** [comment]
Were you able to solve this problem? Aditionally i can assign an event to a group, it is not listed in full form but it is at quick create field.
