### ISSUE TITLE
Problem with email in the Accounts screen

### ISSUE THREAD

**Issue by rafamacedo** [YetiForceCompany/YetiForceCRM#6404]
Hello

I recently updated my version from 4.0.0 to 4.3.0 and found the new version to be great. However I encountered some issues like the Emails in the Summary tab.

![image](https://user-images.githubusercontent.com/26890198/37849113-3954822c-2eb5-11e8-98da-be26303f5ad4.png)

You are displaying an error code as shown above. In version 4.0.0 did not have this problem, but this new version happened. Could someone tell me a solution?

Thank you!

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Google Chrome
* Environment name and version: I do not know to inform
* Operating System and version: Windows 10 Pro

**Comment by paula-w** [comment]
Does the error exist on GitStable and GitDeveloper? If not then it’s possible that something went wrong when you migrated your version from 4.0 to 4.3. Remember to install all available fixes for the 4.3 version.
