### ISSUE TITLE
Need Help in recovering admin password 

### ISSUE THREAD

**Issue by gkArvindr** [YetiForceCompany/YetiForceCRM#6405]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

I am not able to login as admin, how do I change password

**Comment by bpabiszczak** [comment]
version?

**Comment by gkArvindr** [comment]
4.2.0 is the version 
Found my own work around, installed a new instance, exported the vtiger_users table and imported it into the older instance. it was pretty easy and able to login.
It will be nice to know the standard the we should follow in yetiforce

**Comment by mariuszkrzaczkowski** [comment]
it's the easiest way to use a script
https://github.com/YetiForceCompany/YetiForceScripts/tree/master/PasswordReset

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/8f5b0424addb3b1c2b092bb88f7cf3cd7671a80d/config/security.php#L12

**Comment by hilligsmann** [comment]
Hello, 

I get the message "Your password has expired, please contact your administrator to reset your password."

Where could I download the ResetPassword.php file? I only see a code on the screen. 

Afterwards, where have I to copy it? 

Thank you.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceScripts/tree/master/PasswordReset

**Comment by hilligsmann** [comment]
When I click on the file, I only see a code on the screen. How could I get the file?

**Comment by vovpff** [comment]
@hilligsmann check readme

**Comment by hilligsmann** [comment]
Thank you for answer. 

The readme unfortunately doesn‘t help me if I can‘t download the file. Where could I download it?

**Comment by hilligsmann** [comment]
I now copied the code to a new file I named PasswordReset.php. Inside the file, I completed the username and password. I then copied the file to the FTP folder public_html.

Nothing happening ...

**Comment by hilligsmann** [comment]
I'm very sorry for my informatical ignorance. 

Could you PLEASE help? I can't work for half a day now ...

Many, many thanks! 

Daniel

**Comment by vovpff** [comment]
@hilligsmann you need to put this `PasswordReset.php` file to `public_html` folder. After that you need o go to `http://yourdomain.com/PasswordReset.php` and see new password.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?q=PasswordReset

**Comment by hilligsmann** [comment]
I copied the file to the directory.

Then when opening the URL I get the error message "The requested URL was not found on this server“.

**Comment by vovpff** [comment]
@hilligsmann this can be problem of your web server configuration or user rights for this file. This is not CRM fault.

**Comment by hilligsmann** [comment]
How could I recover access to my data?

**Comment by vovpff** [comment]
@hilligsmann hmm... What you mean?

**Comment by hilligsmann** [comment]
There‘s all my business data inside the crm. I‘m not able to acceed it anymore. 

Username and password worked perfectly right now. Now the crm lockes me out.

I copied your code into the ftp and entered the address mentionned. Doesn‘t work.

So what could I do? Username and password are right.

Once again, very sorry for my low informatic knowledge.

**Comment by vovpff** [comment]
@hilligsmann you need to see some webpage with next data

```
Login: admin1488
Password: ....
Full name: Administrator Yeti
```

You don't need to replace password and name in file. User id 1 is admin and when you achieve access to admin you can change other stuff.

If you don't see page with login-password data you need to check your web server configuration data.. .htaccess can block all pages besides index.php.

There is tons of causes and ways to solve problem.

**Comment by mariuszkrzaczkowski** [comment]
did you have brute force enabled on the login page?

**Comment by hilligsmann** [comment]
Many many thanks for your precious follow-up!

When trying to connect to the website using the data below (admin1488), the system tells „username or password invalid“. 

I can see the 3 active users inside the MySQL. Could I do anything there? 

I don’t know what brute force is. But inside the MySQL, I see different IP addresses inside the bruteforce_blocked table, timely corresponding to my login attemps. 

I didn’t change anything about the website configuration since last time I used the CRM. 

The website url is crm.emotion.....

**Comment by waran70** [comment]
Not the best idea to publish username and url

**Comment by hilligsmann** [comment]
Could you please help?

**Comment by hilligsmann** [comment]
Hello,

Show could I PLEASE (!) acceed my CRM again?

Is there a wau via MySQL?

What do our passwords not work anymore?

PLEASE!

**Comment by bpabiszczak** [comment]
please send access to crm sla@yetiforce.com [ftp/sql].

**Comment by gkArvindr** [comment]
is the problem resolved

**Comment by hilligsmann** [comment]
Done.

 

Von: Błażej Pabiszczak <notifications@github.com> 
Gesendet: Dienstag, 22. Dezember 2020 22:35
An: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
Cc: hilligsmann <info@emotion-artists.com>; Mention <mention@noreply.github.com>
Betreff: Re: [YetiForceCompany/YetiForceCRM] Need Help in recovering admin password (#6405)

 

please send access to crm sla@yetiforce.com <mailto:sla@yetiforce.com>  [ftp/sql].

**Comment by hilligsmann** [comment]
Hello, 

 

no, the problem is still not solved. 

 

I sent you all necessary access data as requested. Could you please help? 

 

Many, many thanks!!!!

 

Daniel 

 

Von: Arvind GK <notifications@github.com> 
Gesendet: Mittwoch, 23. Dezember 2020 13:29
An: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
Cc: hilligsmann <info@emotion-artists.com>; Mention <mention@noreply.github.com>
Betreff: Re: [YetiForceCompany/YetiForceCRM] Need Help in recovering admin password (#6405)

 

is the problem resolved

**Comment by mariuszkrzaczkowski** [comment]
@hilligsmann I have reset your password, check your email
