### ISSUE TITLE
[bug] percent field

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#6407]
Percent field does not allow adding value using comma as separator though set in user settings. Using full stop, changes it to comma after saving.
![perc](https://user-images.githubusercontent.com/10330264/37864950-406da286-2f7e-11e8-880e-3d72e6ddc982.gif)

#### Your Environment

* YetiForce Version used: 4.3.250
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by kpaulaha** [comment]
Current dev allow comma, but edit/saved show different values
![perc](https://user-images.githubusercontent.com/10330264/39115398-38598ed8-46ea-11e8-9da4-d377ba4b20f7.gif)

**Comment by rskrzypczak** [comment]
I'm unable to duplicate this on the latest developer version.
Please verify the issue once again. If the error still exists attach user's settings.

**Comment by kpaulaha** [comment]
@rskrzypczak Seems to work on current dev, great.
