### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by jayo2005** [YetiForceCompany/YetiForceCRM#643]
PHP Version 5.5.9-1ubuntu4.9

I am trying to install but all I get is the install page. When I click on Install nothing happens. In address bar I get yeti/install/Install.php#

I noticed there is no config.php etc in root. Is this Correct?

**Comment by florek41** [comment]
I have the same problem. In my opinion this is becouse #636 (boostrap-switch support) causes JS error:

TypeError: selectElement.bootstrapSwitch is not a function
selectElement.bootstrapSwitch(params);

After comment changes in  layouts/vlayout/resources/app.js
(lines 1006-1012 and 1021) it works.
