### ISSUE TITLE
Is Yetiforce version 4.4 likely to be released on 31st March?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6437]
Hi,

I am just looking at the Milestones and wondered how likely it is that Yetiforce 4.4 will be released on 31st March?

Kind regards

**Comment by bpabiszczak** [comment]
No :( We need 2-3 weeks.

**Comment by PercyP** [comment]
@bpabiszczak 

thanks for the update - more important that any issues are addressed before it is released :)
