### ISSUE TITLE
[Need HELP] auto choose products after selecting existing invoice with products

### ISSUE THREAD

**Issue by thesxw** [YetiForceCompany/YetiForceCRM#6441]
#### How it should work
after we chose FInvoice from popup window (or from invoice directly) it should auto make up (create fields) with all products selected in invoice.

Could it work with mapped fields ?

if needed more information just tell i will answer than i could (maybe it will help someone)

**Comment by vovpff** [comment]
@thesxw this functionality of vtiger cutted off. You can add mapping from finvoice to target module.

**Comment by thesxw** [comment]
ye im done this by generating record from finvoice
anyway mapping have infinite loading time so i was forced to add it in database directly

**Comment by konadrian** [comment]
Could you give us info about your enviroment?

**Comment by thesxw** [comment]
![1111](https://user-images.githubusercontent.com/33422088/38235390-512995a8-3721-11e8-9704-3709968576d7.jpg)
i think this will do.

**Comment by bpabiszczak** [comment]
Niestety nie do końca rozumiem w jakim miejscu jesteś w systemie, z którego miejsca system powinien pobierać produktu. Proszę o zrzuty ekrany tak aby zobrazować problem.
