### ISSUE TITLE
[BUG?] disconnecting/timeout in OSSMail

### ISSUE THREAD

**Issue by thesxw** [YetiForceCompany/YetiForceCRM#6453]
#### Actual Behavior
Timeout after a few minutes with no action or while uploading files for sending

#### Expected Behavior
Not to get any timeout etc

#### How to trigger the error
1. upload larger file like 8MB or so

#### Your Environment
Vtiger CRM 6.4.0 rev. 14548
Bootstrap [MIT] - v3.3.5
Smarty [LGPL] - v3.1.31

**Comment by konadrian** [comment]
You confused github repositories, we're YetiForce not Vtiger

> Your Environment
Vtiger CRM 6.4.0 rev. 14548

**Comment by thesxw** [comment]
Yetiforce version: 4.2.0 ( i found it in manifest.xml in ftp )
