### ISSUE TITLE
Add "Forgot password link"

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6459]
#### Issue

How to add forgot password link on login page?
I see by default is not show this.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/security.php
