### ISSUE TITLE
Shared hosteing

### ISSUE THREAD

**Issue by yodacohen** [YetiForceCompany/YetiForceCRM#646]
I have a shared hosting account and when I attempted to install Yetiforce, it requested root path and root password.  Is it not possible to install on shared hosting?  Also, the Yetiforce website says they will be happy to help with or do an install.  I responded 4 days ago requesting help and nothing.  Really would like to get Yetiforce installed on SiteGround hosting and compare to VTiger.  It looks exciting.

**Comment by florek41** [comment]
I thik everything depends on your hosting configuration.
Ex. i have shared hosting too, but on Kylos.pl and I can install without any problem and without asking about root path and root password

**Comment by bpabiszczak** [comment]
Unfortunately, I don’t quite understand your problem [what it mean that it requests root path and root password]. The installation process of YetiForce is that same as in Vtiger, Joomla, Wordpress – it’s different in a few places. During the installation, the system asks about access data to the database, you can find an article about the installation process here: https://yetiforce.com/en/administrator-documentation/instalation/101-crm-installation.html 
The latest version of the system requires PHP 5.4 or more.

I don’t remember any email from you; please send it directly to me [b.pabiszczak@yetiforce.com].

**Comment by yodacohen** [comment]
Hello Błażej, 

First of all, I am not a server or linux techie or programmer. I'm an older businessman, very tech oriented, but do have my limits. Know enough about a webserver and WAMP to be dangerous! 

I am about to do some CRM consulting in Houston, TX, and have worked quite a bit with VTiger open source. The VTiger organization, documentation, and software are beginning to frustrate me. It was absolutely absurd that they offered Google Calendar and Google Contact Sync through Google API's and did nothing for months when Google changed its API's for the interface, making the capability, shall we say, incapable. I also was less than thrilled when they removed the mass emailing when they released V6.0 . 

Reading through their discussions, I came across a lot of criticism of their poor documentation in general, and their trac system for bug fixes and new development ideas. One poster referenced Yetiforce and how you use Github. So I did search and came to your website. I like what I saw in your demo. 

I do not own a server, but have two shared hosting accounts, one on SiteGround.com and one on GoDaddy. VTiger 6.2.0 is successfully installed on both. And the Google API situation is working. 

I attempted to install Yetiforce in a subdomain of crmsanity.com at SiteGround a week or two ago, and looking back, I think I may have messed up, causing the error I referenced. I think I may have failed to create the subdomain, but put the url in the browser as though the subdirectory was actually set up as a subdomain on the server hosting account. The parameter screen (as is / should be) screen came up, with several discrepancies. SiteGround has a tool on CPanel where you can change PHP variables. I did so. Some took, some didn't. I called SiteGround. One of the variable changes would have had to be a server-wide setting change, which their tech told me would have a detrimental effect on overall server performance and they won't make that change. He said it shouldn't make much difference to the operation of the application. Hm. I wonder if he knew what he was talking about. 

Then the install proceeded. I got the screen to enter all the pathing, but it was wanting the root path and the root password. That's what I referenced in the post. I am not 100% certain that I properly set up the subdomain, although I think I did and I don't think I would have gotten to the install process if I hadn't, based on the format of the url I entered in the browser. 

I blew it off. After your email this morning, I delved in depth on your website's server requirements and went from understanding some of it to lost. I set up a yetiforce subdomain on my GoDaddy shared hosting account and uploaded the expanded install files there. Over 11,000 files. I copied the php settings into a php.ini file and uploaded it to the top Yetiforce folder. HTAccess? I don't have a clue. How to set the other stuff ? Not sure. I may have failed to put the server url in the config.inc.php file in the top directory and that may have contributed to a 500 internal server error. I need to fix that. 

So I called GoDaddy. Totally worthless. They will help troubleshoot installs of applications available through CPanel (Softaculous, etc), but not much else. Which means I either get some help from you somehow, pay a web developer in Houston IF I can find one that does php, etc, or blow the whole thing off. 

Your advice? 

Roy Cohen 
Houston 
832 368-4160 
And I do have skype and use Teamviewer 
roymcohen@comcast.net 







----- Original Message -----

**Comment by rlstanek** [comment]
Hi Roy,

I'd encourage you to look into hosting with http://www.tmdhosting.com/ it's
super affordable and once you purchase your hosting and domain name you
simply open a support ticket and ask them to install the Yetiforce for you.
They do it for free and all you have to do is log in. Once they install it
they will reply back to the ticket and will give you the link and Yetiforce
username and password. Good luck!

Here is a sample of a support ticket you can submit to them for Yetiforce:















*Hello,Would you please install Yetiforce onto domain: "yourdomain.com
<http://yourdomain.com>"Yetiforce download links are
here: https://github.com/YetiForceCompany/YetiForceCRM
<https://github.com/YetiForceCompany/YetiForceCRM>Additional install and
database instructions are
here: https://yetiforce.com/en/administrator-documentation/instalation.html
<https://yetiforce.com/en/administrator-documentation/instalation.html>Additional
database instructions are
here: https://yetiforce.com/en/administrator-documentation/optimization.html
<https://yetiforce.com/en/administrator-documentation/optimization.html>Please
name location for database, etc as "yetiforce" or similar so I can easily
identify it.TMDHosting to access my TMD account:username: your tmdhosting
usernamepassword:  your tmdhosting passwordThank you!*


Best regards,
Rebecca

Email: rlstanek@gmail.com

**Comment by bpabiszczak** [comment]
1. In case of every system its designers do something that seems irrational to users. We know how it is with vTiger [that's why we gave up on it] and we hope that it will be better with us, we are open. 

2. YetiForce works on shared hosting, but unfortunately some of them aren't flexible and might be used for a simple websites and not for advanced CRM systems. The installation of YetiForce is as simple as the one in Joomla, Vtiger, Wordpress. Not all PHP parameters are required, some are only recommended. Unfortunately the information you added is insufficient for us to be able to help you. Please find the links at the end of this message and they should help you. 

3. The deployment of CRM requires adequate professionals. Your problems are common among non-tech individuals. At the beginning of our adventures we also had problems with the installation process and the configuration, but at the moment we don't have any problems that we aren't able to solve and some of them can be solved right away. If you properly document your problem and add it to GitHub, we will try to help asap.

Recommended documentation:

https://yetiforce.com/en/administrator-documentation/instalation/101-crm-installation.html
https://yetiforce.com/en/ideas,-changes,-bugs/bugs/126-how-to-report-bugs.html

**Comment by bpabiszczak** [comment]
http://www.softaculous.com/apps/erp/YetiForce_CRM

**Comment by labaiktours** [comment]
Hello, I have installation problem. I have uploaded the yetifoce files to webserver 

"installation wizard from a web level"  what should be the link to start installaton wizard? it is not mentioned in documentation.  my server shows 404 not found if i just do   http://webserveraddress/yetiforce/  ( yetifoce is the folder i created)

i also tried with http://webserveraddress/yetiforce/install  but nothing comes up.

Please guide. thanks.

**Comment by informes** [comment]
Hi everybody

I host my sites in Godaddy Linux cpanel Shared hosting.  I'm trying to install an instance of Yetiforce but no first step can do according errors that appear. The YetiforceCRM was obtained via git with clone command keeping from there developer repository. 

As I understand from the YetiforceCRM documentation page just index.php have to be the launch page, for configuration. Then this error message appear when I launch http://mydomain.com (address where yetiforce is depployed)

Did I loose any step to do before run?

Adrian

Error:

Warning: require(/home/MyGodaddyInstance/public_html/mydomain.com/vendor/composer/../ezyang/htmlpurifier/library/HTMLPurifier.composer.php): failed to open stream: No such file or directory in /home/MyGodaddyInstance/public_html/mydomain.com/vendor/composer/autoload_real.php on line 67

Fatal error: require(): Failed opening required '/home/MyGodaddyInstance/public_html/mydomain.com/vendor/composer/../ezyang/htmlpurifier/library/HTMLPurifier.composer.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/MyGodaddyInstance/public_html/mydomain.com/vendor/composer/autoload_real.php on line 67

**Comment by ezbank** [comment]
Use source https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.0.0/YetiForceCRM-4.0.0-complete.zip

**Comment by informes** [comment]
Hi ezbank

thanks a lot!
