### ISSUE TITLE
Cannot save new custom fields in gitdeveloper version

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6460]
Hi,

was just testing gitdeveloper version and adding a new field in Layout editor. When I create the field (i.e. a text box) and click Save it just hangs. The Save button remains in pressed position and nothing happens. I tried adding the custom field to the Contacts module.

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/f0d1bf46af6ec7fe87398523ed387dd272ff4dfd
