### ISSUE TITLE
[Bug?] Notifications- Share with users

### ISSUE THREAD

**Issue by nkzach** [YetiForceCompany/YetiForceCRM#6461]
In Notifications module, the field "Share with users" does not work. Nothing saved in the field.

* YetiForce Version used: 4.3 and gitdeveloper
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
This is how the mechanism works by default. If you create a notification and add users in “Share with users” field then the system will automatically create individual notifications for these users and remove them from this field so that each of them have their own notification.
