### ISSUE TITLE
[BUG][4.3.262] Fatal error when creating a field from LayoutEditor

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#6462]
https://github.com/YetiForceCompany/YetiForceCRM/blob/1cd3804e4a8f9afe65338b5451b22d04a744662c/app/Db/Drivers/Mysql/ColumnSchemaBuilder.php#L12

when creating a field from LayoutEditor

    yii\db\ColumnSchemaBuilder and App\Db\Drivers\ColumnSchemaBuilderTrait define the same property ($autoIncrement) in the composition of App\Db\Drivers\Mysql\ColumnSchemaBuilder. 
    However, the definition differs and is considered incompatible. Class was composed in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/app/Db/Drivers/Mysql/ColumnSchemaBuilder.php on line 12

#### Your Environment

* YetiForce Version used: 4.3.262
* Browser name and version: Chrome 65
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: gitdeveloper.yetiforce.com

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/f0d1bf46af6ec7fe87398523ed387dd272ff4dfd
