### ISSUE TITLE
Problem Installing. Blank Page

### ISSUE THREAD

**Issue by HectorMacLeod** [YetiForceCompany/YetiForceCRM#6465]
Guys, I got a problem trying to install the Yetiforce V.4.3, after put all the information the page stay in blank. Please, can you help me?. 

Thanks
![error yetiforce installing](https://user-images.githubusercontent.com/37811995/38216720-15a97fa4-36a2-11e8-9f84-ce8f430164db.png)

**Comment by WalterLuis** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/category/test-2-en

**Comment by HectorMacLeod** [comment]
I got all the requirements cover, but the problem of the blank page persist. What can I do?.

**Comment by HectorMacLeod** [comment]
And, I have intalled the Yetiforce version 3.0, and no problem to install... So i dont understand.

**Comment by WalterLuis** [comment]
Did you get the crm from this link?
https://github.com/YetiForceCompany/YetiForceCRM/releases

![chrome_2018-04-03_15-23-48](https://user-images.githubusercontent.com/18419851/38255199-15f6a1b0-3753-11e8-8ec9-315896c5cab8.png)

**Comment by WalterLuis** [comment]
If so, it would be good what error you got.
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging

**Comment by SteveGodreau** [comment]
same here

**Comment by HectorMacLeod** [comment]
Nothing that helps me. I don't understand the blan page. It is like the installation doesn't not call the other process, and don't tell me anything on the Development tool

**Comment by WalterLuis** [comment]
well... yes, but i do not know what operating system it uses, nor the php version, nor the mysql / mariadb version, nor the steps you followed for the installation..., between version and version of yetiforce there are new compatibilities and requirements that influence when installing it.
things that I can not know because you deleted the template instead of completing it when creating the issue, that helps a lot in solving the incident. :)

![notepad_2018-04-03_15-40-58](https://user-images.githubusercontent.com/18419851/38256097-6e90dd48-3755-11e8-9c4b-f8b6eb925735.png)

**Comment by mrpiano05** [comment]
I have this problem.

* YetiForce Version used: 4.30
* Browser name and version: Opera
* Environment name and version: I do not know what it is
* Operating System and version: Windows 10

If necessary, I will answer your questions.

**Comment by mariuszkrzaczkowski** [comment]
Start with this
> well... yes, but i do not know what operating system it uses, nor the php version, nor the mysql / mariadb version, nor the steps you followed for the installation...,

**Comment by mrpiano05** [comment]
PHP 7.0.28, MySQL 5.5, web hosting: nazwa.pl, ActiveCloudBiznes.

Installs as instructed.
After step with the requirements, it shows a blank page.

**Comment by bpabiszczak** [comment]
please check logs:
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/apache-500-internal-server-error-3
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging
+ server logs [apache, php]

**Comment by karamatf** [comment]
Hi i have done the same and now getting the error 

This page isn’t working
app.libertas-fund.com is currently unable to handle this request.
HTTP ERROR 500

this is a blank server i have done the reinstall and made sure all plugins are installed

**Comment by mariuszkrzaczkowski** [comment]
> please check logs:
> https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/apache-500-internal-server-error-3
> https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging
> 
> * server logs [apache, php]

you did not attach the required information without this we are not able to help
