### ISSUE TITLE
Graph generation error in Widgets

### ISSUE THREAD

**Issue by rafamacedo** [YetiForceCompany/YetiForceCRM#6466]
Hello guys

All the Widgets I create to appear on the main / home CRM tab are failing. There is no graph of financial control or leads or even opportunities. In the old version I ran it was 4.0.0 and the graphics worked perfectly, but after upgrading to 4.3.0 it all went wrong.

I have already installed the patch packages that shipped with the 4.0.0 version update package. to 4.3.0, but the system is still not generating graphics.

It works perfectly with filter widgets to bring results in just text, but no graphics. I already generated reports with graphics, but in the main / home tab that does not display the graphics. I've researched the community on this issue with multiple search terms, and I can not find someone with the same problem except for ticket #5527 whose response was not satisfactory.

I made access to the YetiForce Demo through Softaculous and the same way I set up a graph widget and got the same error. Interesting!

Could someone tell me some update package to generate graphics in the widget?

![image](https://user-images.githubusercontent.com/26890198/38222676-9750ba1c-36bc-11e8-8509-3c1152c00238.png)

![image](https://user-images.githubusercontent.com/26890198/38222782-652df436-36bd-11e8-8b82-9a7f24df24a9.png)

#### Actual Behavior
It does not display the widgets' graphs on the home page or the reports it creates.

#### Expected Behavior
I was hoping that a chart widget or widget widget widget or even the reports already created can be displayed on the main page instead of white space.

#### Your Environment
* YetiForce Version used: 4.3.0
* Browser name and version: Google Chrome
* Environment name and version: Linux PHP 7.0
* Operating System and version: Windows 10 Pro

**Comment by rafalpospiech** [comment]
we moved to chartjs and in current developer version everything should be ok
