### ISSUE TITLE
Filter not working on Widget creation

### ISSUE THREAD

**Issue by nzi200779** [YetiForceCompany/YetiForceCRM#6472]
Hi

I have a question on how to use filters correctly when creating Widgets, so far on the Filter option i see "Mine" only option, and I cant even select that to create a chart or a reports etc

![image](https://user-images.githubusercontent.com/37071779/38249254-5511fc6c-374b-11e8-8dd4-ff6427e3e3d1.png)
![filter not working](https://user-images.githubusercontent.com/37071779/38249300-8307d2ea-374b-11e8-9670-56aa96d80291.PNG)

**Comment by paula-w** [comment]
You have to enable "list in metrics" to make filters appear on the list. Check the screenshot below:
![filters](https://user-images.githubusercontent.com/13310141/38249888-7df2db5e-374d-11e8-9911-acac8ba2ccac.png)

**Comment by nzi200779** [comment]
Thank you!
