### ISSUE TITLE
Username is not editable

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6478]
#### Issue

Cannot add username when i try to add user.

#### Actual Behavior

I changed in config/modules/users function user name is editable to "true", but not working.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.3
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by cltvchannel** [comment]
In gitdeveloper version is ok.
In my installation was ok until 1 week ago, but now i don't know where i have modified or what happened.
![error](https://user-images.githubusercontent.com/30116021/38303701-73b3a110-380f-11e8-9cd5-f01856ab76c2.png)

**Comment by KatarzynaUlichnowska** [comment]
You should upload Fixes (especially this one: SharingPrivilegesFix.zip and then reload the profile of the user that is trying to change the username).
