### ISSUE TITLE
Where can I find these Free Modules for Yetiforce especially Geotools

### ISSUE THREAD

**Issue by nzi200779** [YetiForceCompany/YetiForceCRM#6479]
Modules that are free in YetiForce [similar features], but are commercial in Vtiger:

[$200] GeoTools 
[$100] PDFMaker 
[$500] Duplicate Check & Merge 
[$150] Module Creator 
[$100] Automatic Discounts Module 
[$80] Colorizer & [$25] Rainbow List 
[$100] Global Search 
[$150] Google Address Lookup 
[$20] Related Count 
[$10] Add to Favorites 
[$15] Quick Reminder 
[$25] QuickView 
[$20] Waybill (DDT / Documento di Trasporto) 
[$20] Mass Map 
[$200] Boru Update Pricing 
[$15] Address Autocomplete 
[$100] Force Secure Passwords 
[$30] Mighty Merge 
[$300] Vlastic Search 
[$80] One SMTP Per User 
[$100] Multi FROM Addresses 
[$5] Custom Key Metrics Block in Dashboard 
[$100] NotifierPro 
[$50] Advanced Funnel Charts 
[$200] Related Record/List Colors 
[$30] Language Editor 4 You 
[$250] Related List/Record Search 
[$50] Customers Life Time Value 
[$250] Document/Folder Manager 
[$50] Org Screen Projects Widget 
[$50] Oppt Summary Screen - Historical Oppt to Buy 
[$50] Org Summary Screen - Contacts Widget 
[$250] Kanban/Pipeline View 
[$150] Hide Empty/Blank Fields 
[$29] ListView2Excel 
[$100] Notifier 
[$100] Outgoing Email Server(Per User) 
[$200] Related Record Count 
[$150] Item Details on Quote/Inv/Order 
[$300] Listview Colors 
[$200] Field Tooltip Manager 
[$70] Export to Excel 
[$50] MailManager Tools 
[$50] Org Screen Assets Widget 
[$50] Organization Screen Historical Activities Widge 
[$150] Multiple Shipping Addresses 
[$50] Opportunity Screen Contacts Widget 
[$50] Org Screen Tickets Widget
[$300] Related & Listview Edits
[$400] PopUp Reminder Tool
[$40] SpecialFields
[$200] Charts/Graphs On Dashboard
[$250] Multi User Assignment
[$25] Count All The Things
[$300] Table Block (Similar to Excel)
[$50] WYSIWYG Spreadsheet Exporter
[$20] MailBadge
[$100] Duplicate Preventer
[$100] Charts Widget
[$15] Convert Sales Order to Purchase Order
[$390] Facturación CFDI for Vtiger CRM
[$100] Prevent Duplicate Emails
[$100] Related Module Updates
[$100] Convert Sales Order to Projects (or Tickets)
[$5] Duplicate your Filter
[$100] Click to Add an Asset
[$10] Edit All Filter and Duplicate
[$200] Templates for Quotes/Invoices/SO
[$300] Profit Calculator
[$200] Masked Field Input
[$200] Related & List View Advanced Preview
[$50] Lead Company Lookup
[$150] Product And Service Lookup
[$100] Popup Alerts
[$200] Field Auto Fill
[$100] Dynamic Blocks
[$300] Convert to Purchase Order

**Comment by nzi200779** [comment]
Morning, Is version 4.4 available now?

**Comment by bpabiszczak** [comment]
Version 4.4 will be published on 2018-04-28 and it will most likely be RC version.

**Comment by bpabiszczak** [comment]
It's a very old list. All modules are available directly in YetiForce. Each of them can work a little bit different than commercial modules in Vtiger, but their business functionalities are very similar. FOr example the Maps module is available directly on the records list in a few modules:

![image](https://user-images.githubusercontent.com/10197525/39113164-06412456-46db-11e8-9e21-16f7bd5eee7f.png)

**Comment by bpabiszczak** [comment]
In the latest version you can show data from the “companies and contacts” modules, in the versions released in the future you will be able to show data from other modules. In order for the system to show the data it must take the latitude and longitude, which requires enabled CRON and configured API.
