### ISSUE TITLE
[Question] How are Users and Employees related?

### ISSUE THREAD

**Issue by websafe** [YetiForceCompany/YetiForceCRM#6488]
Hello,

I'm trying to find any documentation that will help me understand how `users` and `employees` are related but I'm somehow unable to find anything that would make sense to me.

When I create a new user I'm able to login to **YetiForce** with the provided credentials.
But when I create a new employee - what then? Can employees login?

I'm asking because in `module=OSSEmployees` each employee has a calendar, related docs etc. but how can employees access/manage their calendars/documents/anything?

Am I missing something? Do I have to somehow assign an employee to a user?

I found things like this <https://www.vtiger.com/docs/employees>:

> Employees are key assets of your company, to ensure that they are taken care provide them the support they deserve. 
Primarily, the Employees module is used by the Internal Help Desk module, so that employees can raise an internal issue about IT, facilities, payroll, etc.. Every user is an employee, but not all employees are the users of Vtiger. So, when you create a user record, the employee records are created automatically.

related to vtiger but I'm not sure if this is true for YetiForce.

**Comment by paula-w** [comment]
Only users can log into the system. You can add an employee and relate it to a user using the “Assigned To” field.

**Comment by ldgbc** [comment]
@websafe Found my understanding it is as follow:
User have access to Yetiforce system. With restricted apply based on their (1) profile and (2) their role .

Where as Employee is your Employee data, information, and tracking. Pretty much for your Human Resources or Management access. So it contain (1) employee information, (2) their work schedule (calendar) (3) their documents, etc.

But it not accessible to them as they don't need access to it. For example, you have a Trial Employee that is in training, you would use Yeti to have information on them but as they still trial they won't get access, or even know about your Yetiforce system.
