### ISSUE TITLE
 [PL] Użytkownik nie może ustawić filtru jako domyślny

### ISSUE THREAD

**Issue by chrisdebuud** [YetiForceCompany/YetiForceCRM#6491]
#### Issue

Ustawianie filtra jako domyślny dla użytkownika

#### Actual Behavior

Użytkownik po zdefiniowaniu filtru klika ikonę " Ustaw jako domyślny filtr", zapisuje i nadal domyślnym filtrem jest "Wszystkie". Problem nie dotyczy użytkowników  z uprawnieniami administratora.
Z drugiej przeglądarki nadaję userowi prawa administratora, na koncie usera odświeżam stronę - filtr staje się domyślnym. Odbieram mu prawa, przeładowuję stronę - znowu domyślnym jest "Wszystkie"

#### Expected Behavior

Użytkownik może ustawić swój filtr jako domyślny

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Firefox, Chrome
* Environment name and version:  Debian 9 ( 4.9.82-1+deb9u3 (2018-03-02) ) 
* Operating System and version: Windows 10, Windows 7

**Comment by konadrian** [comment]
Możesz wywołać błąd na https://gitdeveloper.yetiforce.com użytkownik u uprawnieniami admina to
l: admin
h: admin
Zwykły user l: sales h: sales
