### ISSUE TITLE
Problem z powtarzalnością terminu w przypadku użycia własnej wartości słownikowej w polu "Rodzaj aktywności"

### ISSUE THREAD

**Issue by websafe** [YetiForceCompany/YetiForceCRM#6492]
Chcę móc dodawać w kalendarzu powtarzające się co miesiąc terminy. Chcę jednak, aby ten termin w "Rodzaj zdarzenia", zamiast standardowo dostępnych "Telefon" i "Spotkanie" miał dodatkowe pole "Czynność" (bo np. chcę dodać do kalendarza wpis w stylu "Upewnić się, że wyszły przelewy do ZUS".

W tym celu przechodzę do:  *Konfiguracja systemu* -> *Moduły standardowe* -> *Pola - słowniki*
i tam wybieram moduł "Terminy"  oraz pole słownikowe "Rodzaj aktywności".

Dodaję *wartość* "Czynność" i przypisuję ją do "Wszystkie role" i zapisuję.
 
Wracam do Kalendarza, próbuję dodać nowy termin, w *Rodzaj zdarzenia* ustawiam "Czynność" i ustawiam powatarzanie co 1 miesiąc.

Kiedy próbuję zapisać taki wpis otrzymuję komunikat:

> Nieprawidłowe zapytanie
> Wykryto niedozwoloną wartość, prosimy o kontakt z administratorem
> 
> Strona główna

Czyli lipa ;-)

Problem **NIE WYSTĘPUJE** jeśli zrezygnuję z "powtarzania" terminu, czyli jeśli nie zaznaczę żadnej opcji w sekcji *Szczegóły powtarzalności terminu* to taki termin mogę zapisać z moją indywidualną wartością słownikową "Czynność", jednak jeśli tylko spróbuję ruszyć przy takim wpisie powtarzanie (np. edytując później taki wpis) to jest kaplica i pojawia się wspomniany wyżej błąd.

Jestem na ostatniej stabilnej.

**Comment by bpabiszczak** [comment]
Nie można dodawać nowego typu w kalendarzu, ponieważ jest to "na sztywno" zakodowane w wielu miejscach. Nawet jeżeli panel na to pozwala [a nie powinien] to dodanie nowego typu, może wiele rzeczy w systemie popsuć np. synchronizacje CalDAV. Może kiedyś to przepiszemy, ale teraz ma to niski priorytet.
