### ISSUE TITLE
https://gitdeveloper.yetiforce.com/portal/ - can't login

### ISSUE THREAD

**Issue by websafe** [YetiForceCompany/YetiForceCRM#6493]
The README mentions <https://gitdeveloper.yetiforce.com/portal/> but there's currently no way to log in. After clicking on "Sign in" we're being redirected back to the sing-in page. 

`logo.png` <https://gitdeveloper.yetiforce.com/portal/layouts/Default/skins/images/logo.png> seems to be missing too.

**Comment by paula-w** [comment]
The portal will be released together with CRM version 4.5 or 5.0. Until then the portal under this address won't work.
