### ISSUE TITLE
[PL] Użytkownik nie jest w stanie zmienić swojego hasła

### ISSUE THREAD

**Issue by tkome** [YetiForceCompany/YetiForceCRM#6510]
#### Issue
Brak możliwości efektywnej zmiany hasła przez użytkownika nie będącego administratorem.

#### Actual Behavior
Użytkownik mimo dostępu do funkcjonalności zmiany hasła (przez moje ustawienia lub wymuszone przez administratora) nie jest w stanie efektywnie zmienić hasła. Po próbie zmiany hasła wyświetlany jest komunikat 'Twoje hasło zostało pomyślnie zmienione' natomiast nadal działa stare hasło. Powyższe dotyczy prób zmiany hasła przez zwykłego użytkownika, zmiana hasła przez administratora działa jak należy.
Mimo to próby zmiany hasła są rejestrowane, nie da się powtórnie podjąć próby ustawienia tego samego hasła (które wcześniej rzekomo udało się ustanowić). 
Nie udało się zreplikować tego zachowania na wersji demo - brak możliwości zmiany hasła (nieaktywny przycisk 'zmień hasło')

Początek pliku config/security.php dot. haseł:

        // Possible to reset the password while logging in (true/false)
        'RESET_LOGIN_PASSWORD' => false,
        // Show my preferences
        'SHOW_MY_PREFERENCES' => true,
        // Changing the settings by the user is possible true/false
        'CHANGE_LOGIN_PASSWORD' => true,

Polityka haseł:
       Minimalna długość hasła: 6
       Maksymalna długość hasła: 32
       Hasło musi zawierać wielkie litery od A do Z: tak
       Hasło musi zawierać małe litery od a do z: tak
       Hasło musi zawierać cyfry: tak
       Hasło musi zawierać znaki specjalne: tak	
       Wymuś zmianę hasła co: 183
       Maksymalny okres zmiany hasła (dni): 5

#### Expected Behavior
Jest możliwość zalogowania się na nowe hasło ustawione przez użytkownika

#### How to trigger the error

1. Administrator tworzy nowego użytkownika: login: test@somedomain.com, hasło: !User9
2. test@somedomain.com logowanie - Twoje hasło straciło ważność, prosimy o kontakt z administratorem w celu zresetowania hasła.
3. admin - reset hasła, hasło z maila: (HJj"$2Xt)
4. test@somedomain.com logowanie((HJj"$2Xt)) - logowanie ok
5. admin - zaznaczenie wymuszenia zmiany hasła
6. test@somedomain.com logowanie ((HJj"$2Xt)) - logowanie ok, wymuszona zmiana hasła, nowe hasło: #NewPass90! - Twoje hasło zostało pomyślnie zmienione.
7. test@somedomain.com logowanie(#NewPass90! - nowe hasło) - Niepoprawna nazwa użytkownika lub hasło.
8. test@somedomain.com logowanie ((HJj"$2Xt) - poprzednie hasło) - logowanie ok, brak monitu o zmianę hasła
9. test@somedomain.com zmiana hasła w moich ustawieniach na #NewPass90! - Takie hasło było już kiedyś używane, system ze względów bezpieczeństwa nie pozwala na używanie takich samych haseł.
10. test@somedomain.com zmiana hasła w moich ustawieniach na $AnotherPass777 - Twoje hasło zostało pomyślnie zmienione.
11. test@somedomain.com logowanie ($AnotherPass777) - Niepoprawna nazwa użytkownika lub hasło.
12. test@somedomain.com logowanie ((HJj"$2Xt) - poprzednie hasło) - logowanie ok, brak monitu o zmianę hasła

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Google Chrome; Wersja 65.0.3325.181
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Czy zostały wgrane fix-y? https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.3.0

**Comment by tkome** [comment]
Została wykonana instalacja nowego systemu z paczki YetiForceCRM-4.3.0-complete.zip, nie wgrywaliśmy żadnych fixów. Należy do tej instalacji dograć wszystkie fixy dostępne pod wskazanym linkiem?

**Comment by mariuszkrzaczkowski** [comment]
Tak

**Comment by tkome** [comment]
Zainstalowaliśmy wszystkie dostępne fixy. Wprawdzie pkt 2 opisanego przeze mnie scenariusza nadal występuje to tytułowy problem zniknął, użytkownik może samodzielnie zmienić hasło. Dziękuję za pomoc i pozdrawiam.
