### ISSUE TITLE
When will be avabile the new menu?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6525]
#### Issue

A few days ago i see in a post that will be avabile a new menu.
Will be something diferent than now?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
http://cssmenumaker.com/menu/modern-jquery-accordion-menu#
