### ISSUE TITLE
Cannot add custom fields in yetiforce developer

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6526]
Hi,

I am just testing the yetiforce developer version and tried adding some custom fields. When I create the field (I tested with Text field and Multi image field) It saves and no error is produced but the field isn't added and not does it appear in the module front end.

Kind regards

Chris

**Comment by konadrian** [comment]
Can you trigger this error on gitdeveloper version https://gitdeveloper.yetiforce.com/index.php or show some screens/gif
