### ISSUE TITLE
[PL] Ginące uprawnienia przy eksporcie kontaktów

### ISSUE THREAD

**Issue by chrisdebuud** [YetiForceCompany/YetiForceCRM#6529]
#### Issue

Moduł ustawiony jako prywatny. Użytkownik znajdujący się w hierarchii wyżej eksportuje wyfiltrowane dane do Excela - ale w pliku poza nazwami kolumn nie ma nic.

#### Actual Behavior

Eksport danych zaczyna działać po zmianie hasła użytkownika. Profil użytkownika próbującego dokonać eksporu, jego uprawnienia - nie były modyfikowane. Zmieniane były inne ustawienia systemu - włączyłem moduł "moja poczta". Wczoraj - analogiczne zgłoszenie, dodawałem nowy profil. Hasło zostało zmienione na to samo które było wcześniej. 
Wniosek - coś sypie się z uprawnieniami do eksportowaniado Excela przy zmianach konfiguracji systemu.
W logach apache nic nie ma.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Firefox, Chrome
* Environment name and version: Debian Linux
* Operating System and version: Windows 10, Windows 7

**Comment by bpabiszczak** [comment]
Proszę przetestować na wersji GitDeveloper [https://gitdeveloper.yetiforce.com/] i GitStable [https://gitstable.yetiforce.com/]. Jeżeli błąd występuje w którejś z tych wersji, proszę nagrać film jak go wywołać np. za pomocą narzędzia screen2gif.
