### ISSUE TITLE
[bug] workflow dev 

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#6530]
Updating fieds window
![settings](https://user-images.githubusercontent.com/10330264/38660127-dbe74e14-3e34-11e8-8698-a13cb9b29416.png)

#### Your Environment

* YetiForce Version used:  4.3.289
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
Fixed
![image](https://user-images.githubusercontent.com/10197525/39111967-4fdabc66-46d7-11e8-8c1b-15ffa4a1482b.png)

**Comment by paula-w** [comment]
Can you tell us exactly where this bug pops up? We're not sure we're looking at the same place.

**Comment by kpaulaha** [comment]
![1settings](https://user-images.githubusercontent.com/10330264/39112759-28da9aea-46e2-11e8-8b83-6e03383d2167.png)
![2settings](https://user-images.githubusercontent.com/10330264/39112763-2c11e56a-46e2-11e8-93b6-e60d8a4a9b30.png)
