### ISSUE TITLE
Removed reports module

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#6538]
We removed the reports module today and it will not appear in the new version of YetiForce. 
As a substitute for reports, we expanded the capabilities of charts and widgets, so that the majority of reports can be generated using different built-in tools. In 90% of all cases the existing tools (filters, charts) should be sufficient for the users. 

We decided to remove the reports module due to security concerns and outdated code (written 10 years ago). The most important reason for removing it was discovering vulnerabilities in the basic mechanism responsible for reports. Fixing that issue would take 5 – 7 days in order to write the mechanism from scratch.

In the nearest future we will add new reports with extensive analytical capabilities, fully based on QueryGenerator. Unfortunately, right now we are not able to tell you which YetiForce version will introduce the new reports. 

https://github.com/YetiForceCompany/YetiForceCRM/pull/6537

**Comment by cltvchannel** [comment]
Removing reports module is a big loose.
I think a lot of people will go other CRM because of this.

**Comment by ezbank** [comment]
Oh no :(

**Comment by PercyP** [comment]
I suppose sometimes you have to go backwards to move forward?
This is a blow for us too as we will rely heavily on producing ad-hoc reports, but if the charts and widgets (and now with the option to add additional tabs) it should still be possible to produce the outputs we need?
Al in the name of progress :)

**Comment by bpabiszczak** [comment]
New charts: https://github.com/YetiForceCompany/YetiForceCRM/pull/6542

**Comment by cltvchannel** [comment]
@bpabiszczak this maybe will be enough for users, but will be great if we can have an option to limit number of results on all type of widgets.
eg. if i have 100 acounts with same criteria, i want to show only first 10.
I see this option, but not in all widgets.

**Comment by PercyP** [comment]
@bpabiszczak 
WOW! The new charts are amazing - can't wait to start using them!

**Comment by WalterLuis** [comment]
I think it would be fine as possible enhancements to maintain the functionality that the reporting module had and so it would not be necessary to create the reports module in the future:
- To relate more than one modules (it could be more interesting to have this possibility since the creation of the filter).
- To have to possibility to export to a .xls sheet.
- To resize the window widget from the dashboard, as we do on "System settings > Standard modules > Modules - Widgets".

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/6554

**Comment by ezbank** [comment]
If you remove the report module, how to send the excel list on schedule.

**Comment by PercyP** [comment]
@ezbank 
Good question I would like to know too as this is needed

**Comment by Carolinercraig** [comment]
> We removed the reports module today and it will not appear in the new version of YetiForce.
> As a substitute for reports, we expanded the capabilities of charts and widgets, so that the majority of reports can be generated using different built-in tools. In 90% of all cases the existing tools (filters, charts) should be sufficient for the users.
> 
> We decided to remove the reports module due to security concerns and outdated code (written 10 years ago). The most important reason for removing it was discovering vulnerabilities in the basic mechanism responsible for reports. Fixing that issue would take 5 – 7 days in order to write the mechanism from scratch.
> 
> In the nearest future we will add new reports with extensive analytical capabilities, fully based on QueryGenerator. Unfortunately, right now we are not able to tell you which YetiForce version will introduce the new reports.
> 
> #6537

Any update on when the new reports with extensive analytical capabilities will be made available? Im really astonished to find something super important as this was removed.

**Comment by umbz** [comment]
Me too , any news ?

**Comment by umbz** [comment]
If you want a good analitycal engine (but external) check metabase

**Comment by waran70** [comment]
Well, the reports module is the heart of those who do various mass operations (campaigns, data analysis). Also, many of guys require scheduled reports, which is a common feature in modern CRM, ERP systems. 
Removing modules is not the best solutions as it clipping many wings. Instead, improving 'em should take place. Imagine you have 300 yetiforce users who rely on reports, and they will not get it in next update? Frustrating like hell :-)

**Comment by Carolinercraig** [comment]
I created my reports manually. It was basic, but still took time. I'm sure
if the report module was included, it would have saved me alot of time.  I
wanted to share this sw with other ppl but without a report module, really
doesn't make sense.

**Comment by elvissaba** [comment]
I agree with Waran. Decision makers like scheduled reports. In my company, they did not take into consideration Yetiforce as a replacement for the current CRM for that reason.

**Comment by ad1rie1** [comment]
Any News ?
