### ISSUE TITLE
Show field from related module

### ISSUE THREAD

**Issue by jayo2005** [YetiForceCompany/YetiForceCRM#654]
I need to show a field from a related module ( List VIew) . Example.-  You have Contacts, Service Contracts and Tickets.

From Tickets in List View I need to be able and see the End Date of the Service Contract that is related to that Ticket.

**Comment by bpabiszczak** [comment]
It's not that difficult, but requires programming changes. It is necessary to create a system field that is editable by a user in a module where you want to search/filter data. Then each time you change a record with handlers it is required to update this field. At the moments, we don't plan to add such a functionality to the panel.
