### ISSUE TITLE
Tax field shortcode

### ISSUE THREAD

**Issue by YESMUN** [YetiForceCompany/YetiForceCRM#6545]
#### Issue
Cannot add the tax amount as a single field on an order or invoice, only have the option to add a tax summary.

#### Actual Behavior
No option to add tax amount in a custom field.

#### Expected Behavior
To be able to add the Tax Amount in a custom field.

I can add the invoice amount before and after tax with these two inserts into the template:

**Sub Total: $(record : sum_total)$
Grand Total: $(record : sum_gross)$**

But then there is no field that says what the tax amount is, so I would like to be able to add in there:

TAX: (and here have it insert the tax amount.

I can put in the tax summary using:

**$(custom : TableTaxSummary)$** 

But that does not fit into the layout and does work for what I need. Is there a way to insert only the tax amount? 

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome
* Operating System and version: Centos with cPanel

**Comment by YESMUN** [comment]
This is what I would like to be able to create:

![image](https://user-images.githubusercontent.com/24837231/38785451-896942ca-4120-11e8-9c12-b6596ef678ba.png)

This is what I am getting:

![image](https://user-images.githubusercontent.com/24837231/38785486-ff9efebc-4120-11e8-8ea8-99f7982172cf.png)

**Comment by YESMUN** [comment]
Nobody can help with this?

**Comment by bpabiszczak** [comment]
You can add products with different tax rates in the system so the summary is the best way to present the list of taxes and their amounts. Of course you can change it in any way you want but it's going to require some programming work.

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/39111847-d3f5caa0-46d6-11e8-83e8-6b735e3ae025.png)
