### ISSUE TITLE
Product image upload error

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6550]
#### Issue

Tried to upload a product image and get error.
I get 2 errors.

1st try: 
![prod3](https://user-images.githubusercontent.com/30116021/38689877-5b8077fe-3e85-11e8-8e9b-5bf421b331a3.png)
2nd try:
![prod1](https://user-images.githubusercontent.com/30116021/38689590-b6301be2-3e84-11e8-9eda-3e354c075cb2.png)
Save:
![prod2](https://user-images.githubusercontent.com/30116021/38689591-b6678b0e-3e84-11e8-9498-b71637e9bd1e.png)

#### Actual Behavior

Tested on gitdeveloper

#### Expected Behavior

Be able to upload image.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.290
* Browser name and version: Google Chrome
* Environment name and version: Gitdeveloper
* Operating System and version:

**Comment by rafalpospiech** [comment]
thanks for report, we are working on this

**Comment by PercyP** [comment]
I tested too. Same error but realised it was still being worked on.

**Comment by rafalpospiech** [comment]
This bug (below) should be fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/6581
Problem with code injection still exists but we are working on this

![image](https://user-images.githubusercontent.com/30116021/38689591-b6678b0e-3e84-11e8-9498-b71637e9bd1e.png)

**Comment by mariuszkrzaczkowski** [comment]
1 - this is not an error, the image includes executable php code, that's why it was blocked by the server
2 - the error has been already fixed in #6587 , #6581
