### ISSUE TITLE
Cannot edit Leads or Contacts

### ISSUE THREAD

**Issue by DanGoodSoftware** [YetiForceCompany/YetiForceCRM#6561]
#### Issue
Fresh installation of Yetiforce CRM 4.3 using Softaculous via cPanel on A2 Hosting.  Immediately after successful install, log in and create a Lead.  Save the Lead, view the Lead, cannot edit any fields of the Lead.

#### Actual Behavior
When viewing a Lead or Contact, mousing over any field does not reveal the pencil icon to edit.  It is not possible to edit anything.  Behavior is the same in latest version of Chrome, Firefox, Waterfox and Edge.

#### Expected Behavior
Existing installation of 4.2 works as expected.  When viewing a Lead or Contact, mousing over any field reveals the pencil icon and information can be edited.

#### How to trigger the error
1. Install Yetiforce using Softaculous.
2. Create a Lead.
3. View the Lead and mouse-over an editable field and look for pencil icon.

#### Your Environment
* YetiForce Version used: 4.3
* Browser name and version: Chrome, Firefox, Waterfox, Edge
* Environment name and version: cPanel / A2 Hosting
* Operating System and version: CentOS 7

**Comment by SALITEL** [comment]
I have the same problem. What is the solution?

**Comment by DanGoodSoftware** [comment]
I don't see either of those setting anywhere on the server configuration page.  Where do I go to make the same change myself?
Thank you!

**Comment by DanGoodSoftware** [comment]
Okay, I found this in the PHP settings for the server.  Changing this broke the current Yetiforce installation.  Had to re-install.  But I can edit now.

Why does v4.2 not care about pdo_mysql / nd_pdo_mysql and but 4.3 only works with nd?
