### ISSUE TITLE
How to add Balance to a custom module?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6568]
#### Issue

I want to add Balance field to a custom module, that show total sum from payments module and a custom module called Invoices but only with a currency field (simple module, not advanced)  (like in Account module)

#### Actual Behavior

I have connected with a relation between the modules (payments and custom module).
Also, i want to create 
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.3 /4.4
* Browser name and version: Google Chrome, Mozilla, Safari
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
This is what handlers are for, you only need a small amount of code to get what you want. Here's a similar example: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/HelpDesk/handlers/TicketRangeTime.php

**Comment by cltvchannel** [comment]
@bpabiszczak And where i need to add this handler?
I don't know programming.

Please help me with a more detailed description.

Thanks !

**Comment by bpabiszczak** [comment]
newModule/handlers/

**Comment by cltvchannel** [comment]
Also please can you share with me the code that working on Accounts module for Balance field?

Thanks!
