### ISSUE TITLE
New functions

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6570]
#### Issue

It will be great if functions from next link will be implemented:

Eg.   https://www.modlabs.com/uncategorized/sugarcrm-calculated-fields-guide

https://www.vtexperts.com/product/vtiger-rollup-fields/

I reffer to related records formulas, like rollup.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.3 / 4.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/component/zoo/item/system-development-ideas?highlight=WyJpZGVhcyJd
