### ISSUE TITLE
Fatal Error - DEV GIT

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#6574]
![image](https://user-images.githubusercontent.com/3030997/38837994-98ecec62-41aa-11e8-910d-0c5f16587416.png)

Fatal error: Uncaught Error: Call to undefined method Users_Login_View::isSessionExtend() in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/include/main/WebUI.php:171 Stack trace: #0 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/index.php(25): Vtiger_WebUI->process(Object(App\Request)) #1 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/public_html/index.php(11): require('/home/gitdevelo...') #2 {main} thrown in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/include/main/WebUI.php on line 171

**Comment by mariuszkrzaczkowski** [comment]
Fixed
