### ISSUE TITLE
What exactly is a legal mobile phone number during Contact Import?

### ISSUE THREAD

**Issue by DanGoodSoftware** [YetiForceCompany/YetiForceCRM#6585]
#### Issue
I am importing Contacts that are assigned to existing Leads.  The import fails with an error stating: Incorrect request - Illegal value in field mobile (111-222-3333)

#### Actual Behavior
Cannot import Contacts because I cannot define a legal value for mobile field.  Tried +1 111-222-3333 and (111) 222-3333 and 111-222-3333.

#### Expected Behavior
I would expect to be able to use the same field value for Office phone and Mobile phone.

#### How to trigger the error
1. Attempt to import a Contact with Mobile phone number

#### Your Environment
* YetiForce Version used: 4.3
* Browser name and version: Waterfox 56.x
* Environment name and version: ?
* Operating System and version: CentOS 7

**Comment by TomaszQr** [comment]
Phone format should be compatible with E164, e.g. +441174960123

**Comment by littledove22** [comment]
With the "+1 " required before each phone number, it is impossible to create a csv from google sheets or similar.  (Its seen as math.)  So until the country code for "in country" (Same country as Admin), all phone numbers either have to be added to a different field without syntax, or they have to be fatfingered.
