### ISSUE TITLE
Unable to select groups in event form but not in quick create

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#6586]
#### Issue

I can't assign an event to a group in event complete forms but i can do it in quick create. I have assigned calendar module and user in groups.

#### Actual Behavior

Groups are not listed in event complete form but it does in quick create,

#### Expected Behavior

Be able to assign groups in complete form

#### How to trigger the error

1.Assign to Groups is unavailable in event complete form, but available in quick create
2.
3.

#### Your Environment

* YetiForce Version used: 4.3 & Dev
* Browser name and version: Chrome 
* Environment name and version:
* Operating System and version:

**Comment by rskrzypczak** [comment]
The error no longer occurs in the current dev version
