### ISSUE TITLE
[BUG] Related List view

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#6612]
If the record is deleted or archived, it is not displayed in related records list view on parent record. 

Somewhere in the query generator is deleted = 0

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/39110178-6a69e036-46d0-11e8-99a0-2cc55eba8528.png)
![image](https://user-images.githubusercontent.com/10197525/39110206-8a43467c-46d0-11e8-80ff-bdd91723054a.png)
In the new version you can display active, archived, and trashed records directly on the records list (also in a related module)
