### ISSUE TITLE
Calculation from related module

### ISSUE THREAD

**Issue by danieloutsourcing** [YetiForceCompany/YetiForceCRM#6641]
#### Issue

How i can sum value fields from a column in related module and update target field in related module?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by PercyP** [comment]
I would like to know too.

Kind regards

**Comment by paula-w** [comment]
This is fairly simple, but it has to be done by a programmer. 
We added that feature to the SLA module, it sums up the time based on tickets.

**Comment by cltvchannel** [comment]
@paula-w  I'm interested in this feature. Can you give me an example?

**Comment by cristyxx** [comment]
@paula-w I'm also need this feature.
Please give a more detailed example with all steps, or tell me how much cost this feature.
Thanks !
