### ISSUE TITLE
[How to] How to clean update history?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6677]
#### Issue

This is question for developers. Some time ago I made workflow what combine data from some products fields to one WISYWIG field with formatting. This was good solution but now I found more comfortable solution and want to clean traces in update history. 

Is it right to clean up ```vtiger_modtracker_detail``` table manually by deleting lines with some conditions? Are the conflicts can be in this case?

Can somebody  advice some more rational solution for my question?

P.S. Now I have about 20k lines in ```vtiger_modtracker_detail``` table and 95% of them is trashy unusable information what can be deleted but I don't know how to make it properly.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I tried next steps to clean updates history. This was made manually in database.

Cleaning history of description

```
DELETE
FROM `dev400`.`vtiger_modtracker_detail`
WHERE `fieldname`='description'
AND `postvalue`='some value'
select * from `dev400`.`vtiger_modtracker_detail`;
```

```
DELETE
FROM `dev400`.`vtiger_modtracker_detail`
WHERE `fieldname`='description'
AND `prevalue`='some value'
select * from `dev400`.`vtiger_modtracker_detail`;
```

Cleaning history for refresh field

```
DELETE
FROM `dev400`.`vtiger_modtracker_detail`
WHERE `fieldname`='etprodrefresh'
select * from `dev400`.`vtiger_modtracker_detail`;
```

Cleaning of custom description

```
DELETE
FROM `dev400`.`vtiger_modtracker_detail`
WHERE `fieldname`='etproddescr'
select * from `dev400`.`vtiger_modtracker_detail`;
```

Cleaning of another one custom field

```
DELETE
-- SELECT *
FROM `dev400`.`vtiger_modtracker_detail`
WHERE `fieldname`='etprodadminnotes'
select * from `dev400`.`vtiger_modtracker_detail`;
```

Cleaning of basic modtracket table:

```
DELETE
from dev400.vtiger_modtracker_basic where NOT EXISTS (
    SELECT *
    FROM dev400.vtiger_modtracker_detail
    WHERE id=dev400.vtiger_modtracker_basic.id
)
AND status!='7';
```

Is it correct solution of my problem?

Can this somehow affect the performance of the system in future?

**Comment by paula-w** [comment]
It’s hard to give a definite answer because the business defines what’s needed and what’s not. In theory you can clean all tables related to tracking updates history but then the entire history will be cleaned as well. You can of course clean elements related to one field (if you build a proper query) but it requires an individual analysis. 

So yes, in theory you can clean it and it shouldn’t cause any problems, but you should check:
a) in the code, whether or not it really has no consequences
b) test it on a test version

From the technical perspective the module should be rewritten and auto-archiving of data older than specified amount of time, eg. 12 months should be added.

**Comment by vovpff** [comment]
@paula-w I has no chance for point a because no programmer experience, can anybody help with this? I tested this actions in my mirror system and looks like there are no problem.

Is it missed id in database can be critical?

**Comment by ldgbc** [comment]
Can you explain what the "comfortable solution" is?

**Comment by vovpff** [comment]
@ldgbc this is question for me?

**Comment by ldgbc** [comment]
@vovpff Yes. It seem like you found a MUCH better way after you learn https://github.com/YetiForceCompany/YetiForceCRM/issues/6677#issuecomment-387981913 from this post(?)

I like to read Yetiforce issue, collect document for two purpose, (1) I might need it some day and (2) Help build that Wiki that I would expect them to host by now.
