### ISSUE TITLE
[question] contact to quotes

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#668]
When I have a Opportunity with a Contact and I create a Quote of it, would be nice if also the name of the Contact tranfers to the Quote, it it possible somehow?

**Comment by bpabiszczak** [comment]
We changed relations in modules: Opportunity & Quote. Please test last version.

**Comment by kpaulaha** [comment]
Tested the latest version, but not working for me. When I add a custom field for contact in opportunity and quote the name of contact transfers to quote if I make the quote directly from contact, but not if I make first opportunity and convert that to a quote.

//Kpa

Ps. The new version looks fine now

-------- Alkuperäinen viesti --------
Lähettäjä: Błażej Pabiszczak <notifications@github.com> 
Päivämäärä: 12.05.2015  0.24  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] [question] contact to quotes (#668) 

We changed relations in modules: Opportunity & Quote. Please test last version.

**Comment by bpabiszczak** [comment]
Unfortunately I don't understand. We changed a relation [there is no contact for an opportunity but there is a related contacts module] so how would you like to move a contact to a quote if the field for contact has been removed from quotes?

**Comment by kpaulaha** [comment]
Sorry, I try to explain what I mean. If you make a opportinity for a contact from the contact module the name is added to the opportinity, but when you make an quote from the same opportinity the name is not added to the quote nor the related contacts module. It works if you make an quote directly from contact, but not when converting quote from opportunity. The name of an organization is added to the related field/module in that case.

Best regards

Kpa

-------- Alkuperäinen viesti --------
Lähettäjä: Błażej Pabiszczak <notifications@github.com> 
Päivämäärä: 12.05.2015  14.22  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] [question] contact to quotes (#668) 

Unfortunately I don't understand. We changed a relation [there is no contact for an opportunity but there is a related contacts module] so how would you like to move a contact to a quote if the field for contact has been removed from quotes?

**Comment by bpabiszczak** [comment]
Firstly, a relation between a quote and a contact will be changed to M:M so it will be impossible to bind them. Secondly, a relation on an opportunity has been changed from 1:M to M:M so when copying, it wouldn't detect to which contact it should be related.

**Comment by kpaulaha** [comment]
Ok, thanks.

//kpa

-------- Alkuperäinen viesti --------
Lähettäjä: Błażej Pabiszczak <notifications@github.com> 
Päivämäärä: 15.05.2015  19.33  (GMT+02:00) 
Saaja: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com> 
Kopio: kpaulaha <kimmo@tigersoft.fi> 
Aihe: Re: [YetiForceCRM] [question] contact to quotes (#668) 

Firstly, a relation between a quote and a contact will be changed to M:M so it will be impossible to bind them. Secondly, a relation on an opportunity has been changed from 1:M to M:M so when copying, it wouldn't detect to which contact it should be related.
