### ISSUE TITLE
Bug when adding record in widget to the comments in Module Accounts

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#67]
Bug when adding a widget to the comments of the page is not updated and the comment does not appear in the widget until you refresh the page manually
![wiget comments in accounts](https://cloud.githubusercontent.com/assets/1402355/5693008/ce108284-992c-11e4-8b48-d7a93ec9ab44.PNG)

**Comment by rskrzypczak** [comment]
Which web browser do you use?

**Comment by waw555** [comment]
google hrome

**Comment by waw555** [comment]
In Internet Explorer, also a comment is added after the page is updated

**Comment by rskrzypczak** [comment]
I'm not able to test for a described problem. Please add Ajax  and server loggs.
