### ISSUE TITLE
[bug] adding widget

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#6703]
Adding widget not working.
![settings](https://user-images.githubusercontent.com/10330264/39365387-aff260f8-4a39-11e8-9742-59759f6d5bbf.png)

#### Your Environment

* YetiForce Version used: 4.3.327
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
Can you trigger this error on current  dev version https://gitdeveloper.yetiforce.com ?

**Comment by kpaulaha** [comment]
Seems to work on dev, thanks.
