### ISSUE TITLE
YetiForce v4.4 RC1

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#6707]
We’re excited to announce that we have just released version 4.4. This is an RC version for now, so please keep in mind that there might be some bugs that managed to hide from us, and if you stumble upon any of them - please let us know so we can fix them ASAP!

First of all we would like to thank our community, contributors, and clients for helping us get so far and achieve so much. We don’t say it enough but we really appreciate that you decided to choose YetiForce - thank you for your patience, understanding, and effort. Every single bug report, pull request, and suggestion helps us a lot, and shows us that you care about the system as much as we do. 

## Version 4.4
There are a few major things that make this release different and very important. For the past 3 years we’ve been working really hard on the technical aspects of the software; we added some new features, some we had to rewrite from scratch, some we unfortunately had to remove. All these decisions, even the controversial ones, were made with one thing on our mind - to provide you with a reliable and secure CRM. Version 4.4 is a milestone for us, because it’s the last version that brings these huge changes. From now on we will mostly focus on development, improvements and optimization.
One of these huge changes in this version was removing the reports module and substituting it with a number of charts and widgets. [This issue](https://github.com/YetiForceCompany/YetiForceCRM/issues/6538) explains in more detail why we decided to remove them. If you want to see the new tools, please take a look [here](https://github.com/YetiForceCompany/YetiForceCRM/pull/6542) and [here](https://github.com/YetiForceCompany/YetiForceCRM/pull/6554). 

Version 4.4 stable will be released in about 2 weeks from now, before GDPR comes into force and will be fully compliant with the new regulations. Right now we’re still working on all the issues related to GDPR compliance.

Moreover, we will fix all GitHub issues (bug reports) before we release version 4.4 stable, so please test the RC version thoroughly and report all the bugs you find; the more bugs we find and fix in the RC version, the fewer of them will sneak into the stable version. 
We’re also planning to open new communication channels apart from GitHub once we fix all the issues and make sure the current channels are properly managed. The community suggested a forum and a chat a couple of times, so we will gradually add them and keep you informed.

We recently also opened our own [store](https://yetiforce.shop). The store is our place to sell services related to hosting and support. We WILL NOT release a ton of new modules that you can only purchase, we still believe that all necessary and useful functionalities should be available to everyone for free. Apart from  the 3 support packages we currently offer you will find 4 affordable cloud hosting options. 
We’re still working on it as far as the appearance and product descriptions are concerned, if you have any comments please send us your feedback!

## LINKS

- https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.4.0_RC1
- We're working on the update package, it will be available around the 10th of May 

## UPDATE & REQUIREMENTS

We would like to remind everyone that updates should first be executed on a test version, and only then on the production version (you should always have a backup copy of your environments).
- The list of current web server requirements necessary for version 4.4 to work properly can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements)
- A detailed description of the installation process can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-update)

## CHANGELOG
A complete changelog can be found in the comments below, and will soon be published on our website.

**Comment by paula-w** [comment]
## ADDED

- Added Permission Inspector as a free module
- Added the Turkish language
- Added the ability to filter by event type in widgets
- Added Font Awesome
- Created saas project structure
- Added a plugin to check allowed domains in urls
- Added PHP CS Fixer Config
- Added minor improvements in the Mail module
- Added an improvement in html purify
- Added batch methods
- Added the possibility to encrypt and decrypt passwords
- Added an option to turn off encryption
- Added encryption of password for API and DAV
- Added improvements in picklist setting
- Added multi image upload
- Added multi filter charts
- Added auto logout
- Bootstrap 4
- Added multiple selection of records in modal records list
- Added a template to Invoices
- Added possibility to select more than one photo in the product

## IMPROVED

- General UI changes
- General code improvements
- Improved verification of configuration
- Improved SQL queries
- Improved switch users
- Updated README.md
- Updated libraries: font-awesome, libphonenumber-for-php, security-checker, lib_roundcube
- Updated framework yii2
- Changed global functions to static functions
- Changed many icons
- Improved searching Accounts when convert Lead
- Improved summary of Products and Services
- Improved an action to configure RoundCube
- Improved owner colors
- Improved export to XLS
- Improved loading of widgets
- Improved Quick Create for Notifications
- Improved validation of the CRSF token
- Improved Language Management panel
- Improved autocomplete in Quick Create modals
- Improved file upload
- Improved multi image upload
- Improved process panels
- Improved privilege updater
- Improved records import
- Improved functions getAccessibleGroups and getAccessibleUsers
- Improved Credits
- Improved the appearance of “Widgets” in configuration
- Improved selection of records in the inventory
- Improved permissions to filters
- Corrected code formatting
- Corrected modals
- Corrected create filter view
- Changed module name from Purchase Orders to Sales Orders
- Changed the format of language files (json)
- Changed file permissions
- Cleaned up code
- Refactored pagination
- Refactored copy to clipboard

## FIXED

- Fixed recalculation of sharing rules
- Fixed an error that appeared when creating a widget from filter
- Fixed list of users
- Cleaned and corrected FullCalendar
- Fixed configuration of Marketing Process
- Fixed date parsing on widgets
- Fixed filtering by date
- Fixed Gantt
- Fixed webservice
- Fixed a password saving issue
- Fixed Events widget
- Fixed related lists in the Products module
- Fixed assigning “Reporting To”
- Fixed Calendar scroll
- Fixed a bug in Related lists in Products
- Fixed filtering in Gantt
- Fixed permissions for Widgets
- Fixed PBX integration
- Fixed Calendar Quick Create 
- Fixed Time Control Quick Create
- Fixed a bug that allowed to save a record with empty mandatory fields when the block was collapsed
- Fixed DAV integration
- Fixed clock click
- Fixed TextParser
- Fixed pagination page search
- Fixed the ability to edit product if quantity is negative
- Fixed TextParser bug with Cyrillic symbols

## REMOVED

- Removed Terms and Conditions
- Removed unused libraries: handsontable, Guiders, symfony/var-dumper, jQuery and Snoopy
- Removed “add cron task” action
- Removed fileUpload
- Removed an old image field
- Removed the Reports module
- Removed mobile menu

**Comment by skramanzia** [comment]
Hi @paula-w !! good news!!!, Is the update available by zip file? i cant find in UpdatePackages

**Comment by paula-w** [comment]
Hi @skramanzia 
the update package is not ready yet, we're working on it, it will be available around the 10th. I updated my issue to include this info. Thanks!

**Comment by skramanzia** [comment]
Excellent @paula-w! Thanks!!

**Comment by mariuszkrzaczkowski** [comment]
Install the YetiForceCRM-4.4.0RC1-complete.zip version
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.4.0_RC1/YetiForceCRM-4.4.0RC1-complete.zip

**Comment by PercyP** [comment]
Hi,
great work!
Can those of us who want to update to latest version not use this package? Do we need to wait untiol 10th May?

Kind regards

**Comment by PercyP** [comment]
Hi,
I am trying to install the new complete version (linked to by @mariuszkrzaczkowski ) and I cannot get the install to run. I have changed file/folder permissions to 755 and 644 and also tried disabling htaccess but still get HTTP ERROR 500.
I checked the error log:

`[28-Apr-2018 09:18:22 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
[28-Apr-2018 09:19:02 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
[28-Apr-2018 09:23:12 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
[28-Apr-2018 09:23:25 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
[28-Apr-2018 09:56:57 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
[28-Apr-2018 09:56:58 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
[28-Apr-2018 10:00:06 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
[28-Apr-2018 10:00:37 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
[28-Apr-2018 10:01:42 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
[28-Apr-2018 10:01:48 UTC] PHP Fatal error:  Uncaught Exception: Wrong PHP version, recommended version >= 7.0 in /home/mysite/public_html/new/include/RequirementsValidation.php:9
Stack trace:
#0 /home/mysite/public_html/new/index.php(13): require()
#1 {main}
  thrown in /home/mysite/public_html/new/include/RequirementsValidation.php on line 9
`
My current php version is ea-php70.

What might I by doing wrong?

**Comment by WalterLuis** [comment]
@PercyP use PHP 7.1.XX, and put things as in the next image and should go all right 😄 
![chrome_2018-04-28_11-48-19](https://user-images.githubusercontent.com/18419851/39395770-c99b49ec-4ada-11e8-9fc1-e67d069a2975.png)

**Comment by kpaulaha** [comment]
I also tried first with php 7.0.xx, did not work out, changed to 7.1. Then no problems.

**Comment by PercyP** [comment]
@kpaulaha 

I have been trying all morning to move to php 7.1 (via easyapache 4) but when I do my site produces Error 503 and totally inaccessible.

How did you move to 7.1?

**Comment by kpaulaha** [comment]
@PercyP I have Plesk hosting platform one server. Can change php from site settings.

**Comment by vovpff** [comment]
What php version required for 4.4?

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/user-documentation/item/web-server-requirements

We will check problems with 7.0.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thx

**Comment by krishnaragu** [comment]
Please let me know why report module is removed, which is very impotent. Also, please let me know if any plugin with unlimited shipping address as well.

Note: I am ready to contribute for this project by testing any modules.

**Comment by PercyP** [comment]
@mariuszkrzaczkowski thanks for letting us know.

I have managed to install 4.4 and can now do some testing :)

I finally updated my server to 7.1x.  My problem was initially because my php was still on 7.0 and also with the existing .htaccess file in the end - causing the 503 errors.

I used cpanel EasyApache to update to 7.1 (and 7.2 in readiness). The I used Multiphp Editor to make the changes for server requirements as specified in Yetiforce documentation. 
I also went through the PHP 7.1 documentation and made sure all the php extensions were installed.

**Comment by krishnaragu** [comment]
Hi , we should have an option to create invoice from quote module directly .So that again no need to enter information again in invoice module. Please build this for all modules.

**Comment by vovpff** [comment]
@krishnaragu try mapping from quote to invoice

**Comment by krishnaragu** [comment]
Can you please let me know how to mapping briefly in 2 lines. Thanks

**Comment by krishnaragu** [comment]
I got how to map.thank you very much

**Comment by vovpff** [comment]
@krishnaragu sorry. I have read you request for explanation 3 min ago. I think you satisfied with mupping result

**Comment by vovpff** [comment]
@paula-w I think [this article](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements) must be updated with new requirements of 4.4 ver, eg php version 7.1+

**Comment by bpabiszczak** [comment]
We will update this article when we public GA version.

**Comment by mariuszkrzaczkowski** [comment]
Here is the current list of requirements, the same is during the installation https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65
