### ISSUE TITLE
Gitdeveloper: added custom widget from filter to Test A dashboard and broke site 

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6712]
Hi,

I was just testing the adding of a new widget (in tab named Test A on dashboard page).
I chose create widget from filter, filled in all but the last box in the widget creation then selected save. This caused the following error:

Error!!!
LBL_NOT_FOUND_VIEW

`#0 app/CustomView.php(378): App\CustomView->_getCustomViewFromFile(NULL)
#1 app/CustomView.php(401): App\CustomView->_getColumnsListByCvid(NULL)
#2 app/QueryGenerator.php(607): App\CustomView->getColumnsListByCvid(NULL)
#3 modules/Vtiger/models/MiniList.php(80): App\QueryGenerator->initForCustomViewById(NULL)
#4 modules/Vtiger/models/MiniList.php(88): Vtiger_MiniList_Model->initListViewController()
#5 modules/Vtiger/models/DashBoard.php(78): Vtiger_MiniList_Model->getTitle()
#6 modules/Vtiger/views/DashBoard.php(96): Vtiger_DashBoard_Model->getDashboards()
#7 include/main/WebUI.php(184): Vtiger_DashBoard_View->process(Object(App\Request))
#8 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#9 public_html/index.php(11): require('/home/gitdevelo...')
#10 {main}
#0 [trace] Start DateTimeField::__convertToUserFormat a:1:{i:0;s:9:"2018-4-28";} | yyyy-mm-dd
#1 [trace] End DateTimeField::__convertToUserFormat
#2 [info] SELECT * FROM `u_yf_browsinghistory` WHERE `userid`=5 ORDER BY `id` DESC LIMIT 20 || yii\db\Command::query
#3 [info] Opening DB connection: mysql:host=localhost;dbname=gitdevelop_crm;port=3306 || yii\db\Connection::open
#4 [trace] Start DateTimeField::convertToUserTimeZone(today) method ...
#5 [trace] Start DateTimeField::convertTimeZone(today, Europe/Warsaw, Europe/Warsaw)
#6 [trace] End DateTimeField::convertTimeZone
#7 [trace] End DateTimeField::convertToUserTimeZone
#8 [trace] Start DateTimeField::convertToUserTimeZone(yesterday) method ...
#9 [trace] Start DateTimeField::convertTimeZone(yesterday, Europe/Warsaw, Europe/Warsaw)
#10 [trace] End DateTimeField::convertTimeZone
#11 [trace] End DateTimeField::convertToUserTimeZone
#12 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:21:25) method ...
#13 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:21:25, Europe/Warsaw, Europe/Warsaw)
#14 [trace] End DateTimeField::convertTimeZone
#15 [trace] End DateTimeField::convertToUserTimeZone
#16 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:21:25)
#17 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:21:25) method ...
#18 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:21:25, Europe/Warsaw, Europe/Warsaw)
#19 [trace] End DateTimeField::convertTimeZone
#20 [trace] End DateTimeField::convertToUserTimeZone
#21 [trace] End DateTimeField::getDisplayTime
#22 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:21:22) method ...
#23 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:21:22, Europe/Warsaw, Europe/Warsaw)
#24 [trace] End DateTimeField::convertTimeZone
#25 [trace] End DateTimeField::convertToUserTimeZone
#26 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:21:22)
#27 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:21:22) method ...
#28 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:21:22, Europe/Warsaw, Europe/Warsaw)
#29 [trace] End DateTimeField::convertTimeZone
#30 [trace] End DateTimeField::convertToUserTimeZone
#31 [trace] End DateTimeField::getDisplayTime
#32 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:21:16) method ...
#33 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:21:16, Europe/Warsaw, Europe/Warsaw)
#34 [trace] End DateTimeField::convertTimeZone
#35 [trace] End DateTimeField::convertToUserTimeZone
#36 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:21:16)
#37 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:21:16) method ...
#38 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:21:16, Europe/Warsaw, Europe/Warsaw)
#39 [trace] End DateTimeField::convertTimeZone
#40 [trace] End DateTimeField::convertToUserTimeZone
#41 [trace] End DateTimeField::getDisplayTime
#42 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:21:13) method ...
#43 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:21:13, Europe/Warsaw, Europe/Warsaw)
#44 [trace] End DateTimeField::convertTimeZone
#45 [trace] End DateTimeField::convertToUserTimeZone
#46 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:21:13)
#47 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:21:13) method ...
#48 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:21:13, Europe/Warsaw, Europe/Warsaw)
#49 [trace] End DateTimeField::convertTimeZone
#50 [trace] End DateTimeField::convertToUserTimeZone
#51 [trace] End DateTimeField::getDisplayTime
#52 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:53) method ...
#53 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:53, Europe/Warsaw, Europe/Warsaw)
#54 [trace] End DateTimeField::convertTimeZone
#55 [trace] End DateTimeField::convertToUserTimeZone
#56 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:20:53)
#57 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:53) method ...
#58 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:53, Europe/Warsaw, Europe/Warsaw)
#59 [trace] End DateTimeField::convertTimeZone
#60 [trace] End DateTimeField::convertToUserTimeZone
#61 [trace] End DateTimeField::getDisplayTime
#62 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:43) method ...
#63 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:43, Europe/Warsaw, Europe/Warsaw)
#64 [trace] End DateTimeField::convertTimeZone
#65 [trace] End DateTimeField::convertToUserTimeZone
#66 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:20:43)
#67 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:43) method ...
#68 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:43, Europe/Warsaw, Europe/Warsaw)
#69 [trace] End DateTimeField::convertTimeZone
#70 [trace] End DateTimeField::convertToUserTimeZone
#71 [trace] End DateTimeField::getDisplayTime
#72 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:35) method ...
#73 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:35, Europe/Warsaw, Europe/Warsaw)
#74 [trace] End DateTimeField::convertTimeZone
#75 [trace] End DateTimeField::convertToUserTimeZone
#76 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:20:35)
#77 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:35) method ...
#78 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:35, Europe/Warsaw, Europe/Warsaw)
#79 [trace] End DateTimeField::convertTimeZone
#80 [trace] End DateTimeField::convertToUserTimeZone
#81 [trace] End DateTimeField::getDisplayTime
#82 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:33) method ...
#83 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:33, Europe/Warsaw, Europe/Warsaw)
#84 [trace] End DateTimeField::convertTimeZone
#85 [trace] End DateTimeField::convertToUserTimeZone
#86 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:20:33)
#87 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:33) method ...
#88 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:33, Europe/Warsaw, Europe/Warsaw)
#89 [trace] End DateTimeField::convertTimeZone
#90 [trace] End DateTimeField::convertToUserTimeZone
#91 [trace] End DateTimeField::getDisplayTime
#92 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:26) method ...
#93 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:26, Europe/Warsaw, Europe/Warsaw)
#94 [trace] End DateTimeField::convertTimeZone
#95 [trace] End DateTimeField::convertToUserTimeZone
#96 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:20:26)
#97 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:26) method ...
#98 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:26, Europe/Warsaw, Europe/Warsaw)
#99 [trace] End DateTimeField::convertTimeZone
#100 [trace] End DateTimeField::convertToUserTimeZone
#101 [trace] End DateTimeField::getDisplayTime
#102 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:23) method ...
#103 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:23, Europe/Warsaw, Europe/Warsaw)
#104 [trace] End DateTimeField::convertTimeZone
#105 [trace] End DateTimeField::convertToUserTimeZone
#106 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:20:23)
#107 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:23) method ...
#108 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:23, Europe/Warsaw, Europe/Warsaw)
#109 [trace] End DateTimeField::convertTimeZone
#110 [trace] End DateTimeField::convertToUserTimeZone
#111 [trace] End DateTimeField::getDisplayTime
#112 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:13) method ...
#113 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:13, Europe/Warsaw, Europe/Warsaw)
#114 [trace] End DateTimeField::convertTimeZone
#115 [trace] End DateTimeField::convertToUserTimeZone
#116 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:20:13)
#117 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:13) method ...
#118 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:13, Europe/Warsaw, Europe/Warsaw)
#119 [trace] End DateTimeField::convertTimeZone
#120 [trace] End DateTimeField::convertToUserTimeZone
#121 [trace] End DateTimeField::getDisplayTime
#122 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:11) method ...
#123 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:11, Europe/Warsaw, Europe/Warsaw)
#124 [trace] End DateTimeField::convertTimeZone
#125 [trace] End DateTimeField::convertToUserTimeZone
#126 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:20:11)
#127 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:20:11) method ...
#128 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:20:11, Europe/Warsaw, Europe/Warsaw)
#129 [trace] End DateTimeField::convertTimeZone
#130 [trace] End DateTimeField::convertToUserTimeZone
#131 [trace] End DateTimeField::getDisplayTime
#132 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:58) method ...
#133 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:58, Europe/Warsaw, Europe/Warsaw)
#134 [trace] End DateTimeField::convertTimeZone
#135 [trace] End DateTimeField::convertToUserTimeZone
#136 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:19:58)
#137 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:58) method ...
#138 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:58, Europe/Warsaw, Europe/Warsaw)
#139 [trace] End DateTimeField::convertTimeZone
#140 [trace] End DateTimeField::convertToUserTimeZone
#141 [trace] End DateTimeField::getDisplayTime
#142 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:49) method ...
#143 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:49, Europe/Warsaw, Europe/Warsaw)
#144 [trace] End DateTimeField::convertTimeZone
#145 [trace] End DateTimeField::convertToUserTimeZone
#146 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:19:49)
#147 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:49) method ...
#148 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:49, Europe/Warsaw, Europe/Warsaw)
#149 [trace] End DateTimeField::convertTimeZone
#150 [trace] End DateTimeField::convertToUserTimeZone
#151 [trace] End DateTimeField::getDisplayTime
#152 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:46) method ...
#153 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:46, Europe/Warsaw, Europe/Warsaw)
#154 [trace] End DateTimeField::convertTimeZone
#155 [trace] End DateTimeField::convertToUserTimeZone
#156 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:19:46)
#157 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:46) method ...
#158 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:46, Europe/Warsaw, Europe/Warsaw)
#159 [trace] End DateTimeField::convertTimeZone
#160 [trace] End DateTimeField::convertToUserTimeZone
#161 [trace] End DateTimeField::getDisplayTime
#162 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:32) method ...
#163 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:32, Europe/Warsaw, Europe/Warsaw)
#164 [trace] End DateTimeField::convertTimeZone
#165 [trace] End DateTimeField::convertToUserTimeZone
#166 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:19:32)
#167 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:32) method ...
#168 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:32, Europe/Warsaw, Europe/Warsaw)
#169 [trace] End DateTimeField::convertTimeZone
#170 [trace] End DateTimeField::convertToUserTimeZone
#171 [trace] End DateTimeField::getDisplayTime
#172 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:28) method ...
#173 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:28, Europe/Warsaw, Europe/Warsaw)
#174 [trace] End DateTimeField::convertTimeZone
#175 [trace] End DateTimeField::convertToUserTimeZone
#176 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:19:28)
#177 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:28) method ...
#178 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:28, Europe/Warsaw, Europe/Warsaw)
#179 [trace] End DateTimeField::convertTimeZone
#180 [trace] End DateTimeField::convertToUserTimeZone
#181 [trace] End DateTimeField::getDisplayTime
#182 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:27) method ...
#183 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:27, Europe/Warsaw, Europe/Warsaw)
#184 [trace] End DateTimeField::convertTimeZone
#185 [trace] End DateTimeField::convertToUserTimeZone
#186 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:19:27)
#187 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:27) method ...
#188 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:27, Europe/Warsaw, Europe/Warsaw)
#189 [trace] End DateTimeField::convertTimeZone
#190 [trace] End DateTimeField::convertToUserTimeZone
#191 [trace] End DateTimeField::getDisplayTime
#192 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:21) method ...
#193 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:21, Europe/Warsaw, Europe/Warsaw)
#194 [trace] End DateTimeField::convertTimeZone
#195 [trace] End DateTimeField::convertToUserTimeZone
#196 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:19:21)
#197 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:19:21) method ...
#198 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:19:21, Europe/Warsaw, Europe/Warsaw)
#199 [trace] End DateTimeField::convertTimeZone
#200 [trace] End DateTimeField::convertToUserTimeZone
#201 [trace] End DateTimeField::getDisplayTime
#202 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:18:53) method ...
#203 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:18:53, Europe/Warsaw, Europe/Warsaw)
#204 [trace] End DateTimeField::convertTimeZone
#205 [trace] End DateTimeField::convertToUserTimeZone
#206 [trace] Start DateTimeField::getDisplayTime(2018-04-28 12:18:53)
#207 [trace] Start DateTimeField::convertToUserTimeZone(2018-04-28 12:18:53) method ...
#208 [trace] Start DateTimeField::convertTimeZone(2018-04-28 12:18:53, Europe/Warsaw, Europe/Warsaw)
#209 [trace] End DateTimeField::convertTimeZone
#210 [trace] End DateTimeField::convertToUserTimeZone
#211 [trace] End DateTimeField::getDisplayTime
#212 [info] SELECT * FROM `u_yf_chat_messages` LIMIT 20 || yii\db\Command::query
#213 [trace] Entering Vtiger_DashBoard_Model::verifyDashboard(Home)
#214 [trace] getBlocksFromModule(Home, H3) method ...
#215 [info] SELECT * FROM `vtiger_module_dashboard_blocks` WHERE ((`tabid`=3) AND (`dashboard_id`=2)) AND (`authorized`='H3') || yii\db\Command::query
#216 [info] SELECT `vtiger_module_dashboard`.*, `vtiger_links`.`tabid` FROM `vtiger_module_dashboard` INNER JOIN `vtiger_links` ON vtiger_links.linkid = vtiger_module_dashboard.linkid WHERE `vtiger_module_dashboard`.`blockid`=2 || yii\db\Command::query
#217 [info] SELECT EXISTS(SELECT * FROM `vtiger_module_dashboard_widgets` WHERE (`userid`=5) AND (`templateid`=12)) || yii\db\Command::query
#218 [info] SELECT EXISTS(SELECT * FROM `vtiger_module_dashboard_widgets` WHERE (`userid`=5) AND (`templateid`=13)) || yii\db\Command::query
#219 [info] SELECT EXISTS(SELECT * FROM `vtiger_module_dashboard_widgets` WHERE (`userid`=5) AND (`templateid`=14)) || yii\db\Command::query
#220 [info] SELECT EXISTS(SELECT * FROM `vtiger_module_dashboard_widgets` WHERE (`userid`=5) AND (`templateid`=15)) || yii\db\Command::query
#221 [info] SELECT EXISTS(SELECT * FROM `vtiger_module_dashboard_widgets` WHERE (`userid`=5) AND (`templateid`=16)) || yii\db\Command::query
#222 [info] SELECT EXISTS(SELECT * FROM `vtiger_module_dashboard_widgets` WHERE (`userid`=5) AND (`templateid`=17)) || yii\db\Command::query
#223 [info] SELECT EXISTS(SELECT * FROM `vtiger_module_dashboard_widgets` WHERE (`userid`=5) AND (`templateid`=18)) || yii\db\Command::query
#224 [info] SELECT EXISTS(SELECT * FROM `vtiger_module_dashboard_widgets` WHERE (`userid`=5) AND (`templateid`=19)) || yii\db\Command::query
#225 [trace] Exiting Vtiger_DashBoard_Model::verifyDashboard
#226 [info] SELECT `vtiger_links`.*, `mdw`.`userid`, `mdw`.`data`, `mdw`.`active`, `mdw`.`title`, `mdw`.`size`, `mdw`.`filterid`, `mdw`.`id` AS `widgetid`, `mdw`.`position`, `vtiger_links`.`linkid` AS `id`, `mdw`.`limit`, `mdw`.`cache`, `mdw`.`owners`, `mdw`.`isdefault` FROM `vtiger_links` LEFT JOIN `vtiger_module_dashboard_widgets` `mdw` ON vtiger_links.linkid = mdw.linkid WHERE (`mdw`.`userid`=5) AND (`vtiger_links`.`linktype`='DASHBOARDWIDGET') AND (`mdw`.`module`=3) AND (`active`=0) AND (`mdw`.`dashboardid`=2) || yii\db\Command::query
#227 [info] SELECT `vtiger_module_dashboard_widgets`.`module`, `vtiger_module_dashboard_blocks`.`tabid` FROM `vtiger_module_dashboard` LEFT JOIN `vtiger_module_dashboard_blocks` ON vtiger_module_dashboard_blocks.id = vtiger_module_dashboard.blockid LEFT JOIN `vtiger_module_dashboard_widgets` ON vtiger_module_dashboard_widgets.templateid = vtiger_module_dashboard.id WHERE ((`userid`=5) AND (`vtiger_module_dashboard_widgets`.`dashboardid`=2)) OR (`authorized`='H3') GROUP BY `module`, `tabid` || yii\db\Command::query
#228 [trace] Entering getColumnFields(Announcements) method ...
#229 [trace] Exiting getColumnFields method ...
#230 [info] SELECT `u_yf_announcement`.`announcementid` AS `id`, `u_yf_announcement`.`subject` AS `subject`, `vtiger_crmentity`.`description` AS `description`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `u_yf_announcement`.`is_mandatory` AS `is_mandatory` FROM `u_yf_announcement` INNER JOIN `vtiger_crmentity` ON u_yf_announcement.announcementid = vtiger_crmentity.crmid WHERE (`vtiger_crmentity`.`deleted`=0) AND (`announcementstatus`='PLL_PUBLISHED') || yii\db\Command::query
#231 [info] Cannot translate this: 'yetiforce.com' for module 'Menu', lang: en_us
#232 [info] Cannot translate this: 'yetiforce.com' for module 'Menu', lang: en_us
#233 [trace] Entering isPermitted(HelpDesk,CreateView,,) method ...
#234 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#235 [info] Cannot translate this: 'Profil' for module 'Menu', lang: en_us
#236 [info] Cannot translate this: 'Profil' for module 'Menu', lang: en_us
#237 [info] Cannot translate this: 'LBL_MENU' for module '_Base', lang: en_us
#238 [info] SELECT `name`, `value` FROM `yetiforce_mail_config` WHERE `type`='mailIcon' || yii\db\Command::query
#239 [trace] Entering isPermitted(OSSMail,,,) method ...
#240 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#241 [info] SELECT `rcuser_id`, `crmuser_id`, `username`, `password` FROM `roundcube_users_autologin` INNER JOIN `roundcube_users` ON roundcube_users_autologin.rcuser_id = roundcube_users.user_id WHERE `roundcube_users_autologin`.`crmuser_id`=5 || yii\db\Command::query
#242 [info] Cannot translate this: 'LBL_EMAIL' for module '_Base', lang: en_us
#243 [info] Cannot translate this: 'LBL_ACTION_MENU' for module '_Base', lang: en_us
#244 [info] SELECT DISTINCT `vtiger_tab`.* FROM `vtiger_field` INNER JOIN `vtiger_tab` ON vtiger_tab.tabid = vtiger_field.tabid WHERE ((quickcreate = 0) OR (quickcreate = 2)) AND (`vtiger_tab`.`presence` <> 1) AND (`vtiger_tab`.`type` <> 1) AND (`vtiger_tab`.`name` NOT IN ('ModComments', 'PriceBooks', 'Events')) || yii\db\Command::query
#245 [trace] Entering isPermitted(Accounts,CreateView,,) method ...
#246 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#247 [trace] Entering isPermitted(Leads,CreateView,,) method ...
#248 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#249 [trace] Entering isPermitted(Contacts,CreateView,,) method ...
#250 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#251 [trace] Entering isPermitted(Campaigns,CreateView,,) method ...
#252 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#253 [trace] Entering isPermitted(HelpDesk,CreateView,,) method ...
#254 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#255 [trace] Entering isPermitted(Products,CreateView,,) method ...
#256 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#257 [trace] Entering isPermitted(Documents,CreateView,,) method ...
#258 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#259 [trace] Entering isPermitted(Calendar,CreateView,,) method ...
#260 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#261 [trace] Entering isPermitted(Vendors,CreateView,,) method ...
#262 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#263 [trace] Entering isPermitted(ServiceContracts,CreateView,,) method ...
#264 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#265 [trace] Entering isPermitted(Services,CreateView,,) method ...
#266 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#267 [trace] Entering isPermitted(Assets,CreateView,,) method ...
#268 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#269 [trace] Entering isPermitted(ProjectMilestone,CreateView,,) method ...
#270 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#271 [trace] Entering isPermitted(ProjectTask,CreateView,,) method ...
#272 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#273 [trace] Entering isPermitted(Project,CreateView,,) method ...
#274 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#275 [trace] Entering isPermitted(OSSTimeControl,CreateView,,) method ...
#276 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#277 [trace] Entering isPermitted(OutsourcedProducts,CreateView,,) method ...
#278 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#279 [trace] Entering isPermitted(OSSPasswords,CreateView,,) method ...
#280 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#281 [trace] Entering isPermitted(OSSEmployees,CreateView,,) method ...
#282 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#283 [trace] Entering isPermitted(PaymentsIn,CreateView,,) method ...
#284 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#285 [trace] Entering isPermitted(PaymentsOut,CreateView,,) method ...
#286 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#287 [trace] Entering isPermitted(Reservations,CreateView,,) method ...
#288 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#289 [trace] Entering isPermitted(OSSOutsourcedServices,CreateView,,) method ...
#290 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#291 [trace] Entering isPermitted(OSSSoldServices,CreateView,,) method ...
#292 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#293 [trace] Entering isPermitted(HolidaysEntitlement,CreateView,,) method ...
#294 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#295 [trace] Entering isPermitted(LettersIn,CreateView,,) method ...
#296 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#297 [trace] Entering isPermitted(LettersOut,CreateView,,) method ...
#298 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#299 [trace] Entering isPermitted(Announcements,CreateView,,) method ...
#300 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#301 [trace] Entering isPermitted(SSalesProcesses,CreateView,,) method ...
#302 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#303 [trace] Entering isPermitted(KnowledgeBase,CreateView,,) method ...
#304 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#305 [trace] Entering isPermitted(IStorages,CreateView,,) method ...
#306 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#307 [trace] Entering isPermitted(ISTN,CreateView,,) method ...
#308 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#309 [trace] Entering isPermitted(Notification,CreateView,,) method ...
#310 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#311 [trace] Entering isPermitted(Notification,DetailView,,) method ...
#312 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#313 [trace] Entering Settings_WidgetsManagement_Module_Model::getSpecialWidgets(Home) method ...
#314 [info] SELECT * FROM `vtiger_links` WHERE (`tabid`=3) AND (`linklabel` IN ('Mini List', 'Notebook', 'Chart', 'ChartFilter', 'Rss')) || yii\db\Command::query
#315 [trace] Exiting Settings_WidgetsManagement_Module_Model::getSpecialWidgets() method ...
#316 [info] Cannot translate this: 'Test A' for module '_Base', lang: en_us
#317 [info] Cannot translate this: 'Test B' for module '_Base', lang: en_us
#318 [info] Cannot translate this: 'Test C' for module '_Base', lang: en_us
#319 [info] Cannot translate this: 'Test D' for module '_Base', lang: en_us
#320 [info] Cannot translate this: 'Test E' for module '_Base', lang: en_us
#321 [info] SELECT `vtiger_links`.*, `mdw`.`userid`, `mdw`.`data`, `mdw`.`active`, `mdw`.`title`, `mdw`.`size`, `mdw`.`filterid`, `mdw`.`id` AS `widgetid`, `mdw`.`position`, `vtiger_links`.`linkid` AS `id`, `mdw`.`limit`, `mdw`.`cache`, `mdw`.`owners`, `mdw`.`isdefault` FROM `vtiger_links` LEFT JOIN `vtiger_module_dashboard_widgets` `mdw` ON vtiger_links.linkid = mdw.linkid WHERE (`mdw`.`userid`=5) AND (`vtiger_links`.`linktype`='DASHBOARDWIDGET') AND (`mdw`.`module`=3) AND (`active`=1) AND (`mdw`.`dashboardid`=2) || yii\db\Command::query
#322 [trace] Entering isPermitted(Home,CreateDashboardFilter,,) method ...
#323 [trace] Exiting isPermitted method ... - yes
#324 [trace] Entering getColumnFields(Accounts) method ...
#325 [trace] Exiting getColumnFields method ...
#326 [trace] App\CustomView::getColumnsListByCvid - 
#327 [trace] App\CustomView::_getColumnsListByCvid - 
#328 [trace] App\CustomView::_getCustomViewFromFile - 
#329 [info] Cannot translate this: 'LBL_NOT_FOUND_VIEW' for module '_Base', lang: en_us
#330 [error] LBL_NOT_FOUND_VIEWcvId: 
#331 [error] LBL_NOT_FOUND_VIEW => app/CustomView.php:330`

**Comment by Hammerman3000** [comment]
I found the corrupt widget at "vtiger_module_dashboard" and deleted the line from the table, problem solved
