### ISSUE TITLE
Leadsource questions

### ISSUE THREAD

**Issue by SALITEL** [YetiForceCompany/YetiForceCRM#6714]
#### Issue

Two questions:

How can the LeadSource field be added to Accounts?

How can the LeadSource label be renamed for the Spanish language?

Thanks

#### Actual Behavior

Now it is only found in Leads and Contacts

#### Expected Behavior

Make it available in Leads, Contacts and Accounts.

#### Your Environment

* YetiForce Version used: 4.3.0 stable
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@SALITEL app picklist field with name ```leadsource```. This actions adds this pi k let.

For translation you need to found variable name and put translation in language manager

**Comment by konadrian** [comment]
1) Here you can add fields to modules https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&block=2&fieldid=33

2) You can change the translation for Lead Source label here https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/languages/es_es/Leads.json#L33
