### ISSUE TITLE
Link offers directly to leads and accounts

### ISSUE THREAD

**Issue by SALITEL** [YetiForceCompany/YetiForceCRM#6723]
#### **Enhancement**

I think it would be an improvement to be able to link a lead or an account with an offer/quote request.

#### Actual Behavior

Right now it is not possible to register an offer for a lead

#### Expected Behavior

To make an offer to a lead and if it approves then turns to account.
For the accounts it seems more logical and quick to link directly to the offer.

#### Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Chrome

**Comment by WalterLuis** [comment]
Buenos días,

- la relación a "Empresa" ya está hecha desde la "Oferta / Presupuestos", el campo se rellena automáticamente proveniente de la "Oportunidad"
![image](https://user-images.githubusercontent.com/18419851/40298292-95fa9432-5cda-11e8-8afe-3473b00ed02f.png)

- En este caso, si ves necesario añadir una relación también a "Potenciales", sería siguiendo el siguiente video: 
    - https://puu.sh/Aq89C/51fe80f92b.mp4
    - /index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=SQuotes

espero que te sirva de ayuda.
