### ISSUE TITLE
Three columns layout

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#6725]
#### Issue

I want to adjust layout for some blocks to 3 columns.
Where i need to modify files to get this layout?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
add a screenshot where you want to have three columns

**Comment by cristyxx** [comment]
![3columns](https://user-images.githubusercontent.com/18266619/39507869-a6d3c09a-4de8-11e8-9133-f5ffb5fe5f49.png)

I want to change columns in different blocks in some modules.

Also, for future will be a great option if we can change this from dashboard.

**Comment by PercyP** [comment]
+1
This would be good to have to make the most of the available viewing space.

**Comment by paula-w** [comment]
We will take this idea into consideration when we change the template. Thanks a lot!

**Comment by cltvchannel** [comment]
@paula-w Can you give me some ideas where i need to make changes?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/layouts/basic/modules/Vtiger/DetailViewBlockView.tpl

**Comment by ldgbc** [comment]
Can you share your changes so there is a possibility of it being added as a theme or other user like me can use it?

I don't like the 2 column design either, certain field don't need half the column. Especially with the Checkbox one.

It will be awhile before I try my luck with modifying the file, hopefully v5.0 will include a Template or Layout moving.
