### ISSUE TITLE
No Chat Notification (sound or visual)

### ISSUE THREAD

**Issue by ra-uk** [YetiForceCompany/YetiForceCRM#6730]
#### Issue
Chat alerts - there is no sound when a message arrives

#### Actual Behavior
message arrives, no sound or visual notification.

#### Expected Behavior
A sound is played on or shortly after arrival

#### How to trigger the error
1. log into Yetiforce demo as demo
2. log into Yetiforce demo as admin (incognito browsing)
3. send messages between users

#### Your Environment
* YetiForce Version used: 4.3.327
* Browser name and version: both Edge and Opera tried 
* Environment name and version: Managed by Yetiforce
* Operating System and version:  Windows 10

**Comment by paula-w** [comment]
Update: the chat has been completely rebuilt and you can use sound notifications.
