### ISSUE TITLE
seeking Help:Custom filters not appearing in widget creation

### ISSUE THREAD

**Issue by yetiuser** [YetiForceCompany/YetiForceCRM#6731]
We are using yetiforce 4.3.0 in our organisation. When i try to create a widget (under standard modules -&gt; widget configuration)custom filters added for each module is not displayed under filter option and hence it cannot be added to dasboard.Also while trying to add charts from reports to dashboard its also not displaying in home page.Also please let us know is there any task management module extension available with yetiforce?​​​​​​​Generated by YetiforceCRM ver. 4.3.0PHP: 7.0.28-1+ubuntu14.04.1+deb.sury.org+1Server configuration errors:output_buffering: 4096

**Comment by paula-w** [comment]
You have to enable "list in metrics".
Check this issue  https://github.com/YetiForceCompany/YetiForceCRM/issues/6472
