### ISSUE TITLE
Can not edit fields in Standard modules Calendar/Events

### ISSUE THREAD

**Issue by R88888888** [YetiForceCompany/YetiForceCRM#6736]
#### Issue

Try to edit fields in Calendar/Events, let Calendar and Events is more suitable for our purpose.

#### Actual Behavior

Can not edit fields in Calendar/Events 
#### Expected Behavior

Can edit them and let this two modules according to our needs 
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/5542#issuecomment-354111100

**Comment by ldgbc** [comment]
Have to hard edit (file and SQL) if you want to update it. Otherwise only Picklist can be edit I think.
