### ISSUE TITLE
[BUG]Files does not attach at"file from CRM" using RoundCube Module 

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#6737]
#### Issue

No files is attached from "file from CRM" option at RoundCube option nor "email file as attachment" option since documents module icon.

#### Actual Behavior

No files attached on Roundcube nor when you click the Documents module icon "email file as attachment"
#### Expected Behavior

To be able to attach documents since Roundcube and documents module icon
#### How to trigger the error

![file from crm](https://user-images.githubusercontent.com/20831164/39668648-e5f87dc6-5098-11e8-9e1a-60ce0e7e8cf4.gif)

#### Your Environment

* YetiForce Version used: 4.3 & 4.3.327
* Browser name and version: Chrome, Firefox, IE
* Environment name and version:
* Operating System and version:

**Comment by cristyxx** [comment]
Confirm issue.
+1

**Comment by aljoflo** [comment]
Hello, I would like to confirm if anyone knows how to solve this issue. Thanks!

**Comment by kakarata** [comment]
Confirmed on 4.3.0 version

**Comment by TomaszQr** [comment]
Closed via https://github.com/YetiForceCompany/lib_roundcube/commit/26daf5fa307dbfeec6e57490b0cce235db1d2180

**Comment by aljoflo** [comment]
I tried changing the lines at @26daf5f but there is not results. I tried in dev version and it's not possible to attach a document from Roundcube. Am i missing something? Thanks!

**Comment by TomaszQr** [comment]
This change is not compatible with the version you are using. I'm attaching a gif with a test on https://gitdeveloper.yetiforce.com/
![6737](https://user-images.githubusercontent.com/14273211/41023483-dc28735e-696c-11e8-99b5-49257356dc8f.gif)
