### ISSUE TITLE
[bug] workflow

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#6740]
If 1 workflow with manual triggers, show only one in record view.
![wf1](https://user-images.githubusercontent.com/10330264/39674423-4d4b3fe8-5154-11e8-96ab-78e5c3826f4f.png)
![wf3](https://user-images.githubusercontent.com/10330264/39674424-539521e8-5154-11e8-8f95-a694e9c91bbc.png)

#### Your Environment

* YetiForce Version used: 4.4RC1
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rafalpospiech** [comment]
resolved in #6786
