### ISSUE TITLE
[bug or feature] No ability to compare fields values for Filter condition

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6741]
#### Issue

There are not possible to add filter with condition what compares field with another one. Example for products:

![image](https://user-images.githubusercontent.com/8545791/39677484-5bfebc9c-5184-11e8-94eb-52e62e757009.png)

But for workflow there are ability to compare with value(string)/field/expression

![image](https://user-images.githubusercontent.com/8545791/39677520-e1532ea0-5184-11e8-9616-e947e12fc261.png)

This is bug or feature?   

P.S. Modal looks like crashed (Title) and after first step of workflow editing when you click to field filled with field code appears red pop up what tolds "must be decimal"

**Comment by paula-w** [comment]
These are 2 independent mechanisms, when we rewrite workflows from scratch we will take care of that.
