### ISSUE TITLE
not possible to edit fields of  the advanced block

### ISSUE THREAD

**Issue by frankhzp** [YetiForceCompany/YetiForceCRM#6742]
#### Issue

Not possible to edit field of advanced block. 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:  gitdeveloper 4.3.327
* Browser name and version:  Chrome 63
* Environment name and version: 
* Operating System and version:

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I can confirm this. GUI broken

![image](https://user-images.githubusercontent.com/8545791/39701151-b0adfea4-5208-11e8-9b65-8bdcc661bc88.png)

**Comment by poradz** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/6761

**Comment by rohanjhanepal** [comment]
This same problem arised for me in yetiforce 6.0 , i changed all that asked for in #6761 , still doesnt work!!! How do i fix it??
