### ISSUE TITLE
SMS Gateway - only one provider SMSAPI

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6745]
Hi,
I am testing version 4.4 and starting to look into adding SMS service but when I go to new configeration there is only one option to select under Provider which is SMSAPI - are we restricted to just this one provider?

Kind regards

**Comment by paula-w** [comment]
We support one SMS gateway by default but you can add your own gateway. Here you can find an example of a class for a new gateway:  https://github.com/YetiForceCompany/YetiForceCRM/tree/c605a91a40fad95409b7940e6cfbabc09301a3b0/modules/SMSNotifier/providers

**Comment by cltvchannel** [comment]
@paula-w link is not working.

**Comment by ldgbc** [comment]
Hi @PercyP 
I'm planning to look more into self-hosted SMS API. I have a phone is that Unlimited call and SMS so there is no need to use some sort of SMS gateway or provider.

I'm only sending SMS within my country so self-host SMS is viable for the time being. I'm looking into finding way to do that and is still learning.

Currently I'm learning how to "Turn my Android Phone to a SMS Gateway", then eventually connect Yetiforce to that Self-Host SMS Gateway to send out SMS for me. Of course the weakness at the moment is, I can send but I can't see the "Received" SMS.

Anyway, what do you think of this idea? Are you going to just stick with SMSAPI?
