### ISSUE TITLE
Where do we set the System security configuration for public_html and headers?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6752]
Hi,

Checking my server configuration the are a couple of settings I haven't managed to change. I have root access to my server (WHM Cpanel and via SSH). My public_html is currently set to No and unsure what file holds this data so I can change it. The same with the header sections and some of these are missing (see images).

![server](https://user-images.githubusercontent.com/10598886/39708897-50b44848-5210-11e8-9e47-0ed9761b4e97.png)

![sql](https://user-images.githubusercontent.com/10598886/39708999-901be55e-5210-11e8-98c6-eb953d1c34ac.png)

Any pointers would be greatly appreciated.

Kind regards

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6707#issuecomment-385165787

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

I am not sure what you are pointing me to with that link. I know what the server requirements are but just wondered if someone could tell me what files are used to change the settings

**Comment by paula-w** [comment]
Each server can have different configuration and sometimes it might allow you to change settings through .htaccess, sometimes through php.ini files, and sometimes through vhost configuration files. If you google each of these parameters you should find where to look for them. The best solution would be to contact the administrator of your server.

**Comment by onpoint01** [comment]
@PercyP To take care of the "public_html" setting... go to cPanel >> Subdomains (or Addon domain)

Find your subdomain (or domain via addon domain) and change the DocumentRoot.

For myself, it was a subdomain would go:

subdomain.mysite.com >> /home/(username)/yetforcecrm/public_html

Now every time you go to subdomain.mysite.com -- it'll direct you to the public_html folder

Be warned! Once I did this, I had a few issues pop up... one being that although Cron was still running, it wasn't reflecting on the CRM side. Took care of this by updating the "export PHP" in Cron.sh

Good luck
