### ISSUE TITLE
Testing 4.4 cannot get mail binder working

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6753]
Hi,
I have installed the new 4.4 to test and cannot get the mail binder to work. 

1. I set up the SMTP Configuration
2. Have set up Roundcube Mail
3. I have added all the actions in Mail Scanner settings and selected the user.
4. I cannot select the folders as have the error: Incorrect access data (I have checked passwords and they are correct - the same as in the roundcube_users table etc. )
In my site cache/logs files I see the following:
`[01-May-2018 14:46:54 +0100]: <a31e813d> IMAP Error: Login failed for mysite@gmail.com from 86.156.253.184. AUTHENTICATE PLAIN: Invalid credentials (Failure) in /home/mysite/public_html/new/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_imap.php on line 193 (POST /new/public_html/modules/OSSMail/roundcube/?_task=login&_action=login)
[07-May-2018 16:12:03 Europe/London] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/mysite/public_html/new/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 438`

Firstly, I am not sure where it is getting the gmail email address from in the above error as I have set all the configurations to my own email account etc.

Secondly, I get the following error in my regular site errors:

`[Mon May 07 15:12:17.954111 2018] [autoindex:error] [pid 4217:tid 139675480090368] [client 46.32.229.182:38998] AH01276: Cannot serve directory /home/mysite/public_html/yetiforce/user_privileges/: No matching DirectoryIndex (index.php) found, and server-generated directory index forbidden by Options directive, referer: https://www.mysite.com/yetiforce/user_privileges/
[Mon May 07 15:12:17.888868 2018] [autoindex:error] [pid 4274:tid 139675490580224] [client 46.32.229.182:38994] AH01276: Cannot serve directory /home/mysite/public_html/yetiforce/storage/: No matching DirectoryIndex (index.php) found, and server-generated directory index forbidden by Options directive, referer: https://www.mysite.com/yetiforce/storage/
[Mon May 07 15:12:17.822154 2018] [autoindex:error] [pid 4217:tid 139675490580224] [client 46.32.229.182:38990] AH01276: Cannot serve directory /home/mysite/public_html/yetiforce/cache/: No matching DirectoryIndex (index.php) found, and server-generated directory index forbidden by Options directive, referer: https://www.mysite.com/yetiforce/cache/
[Mon May 07 15:12:17.752830 2018] [autoindex:error] [pid 4274:tid 139675570292480] [client 46.32.229.182:38986] AH01276: Cannot serve directory /home/mysite/public_html/yetiforce/config/: No matching DirectoryIndex (index.php) found, and server-generated directory index forbidden by Options directive, referer: https://www.mysite.com/yetiforce/config/
[Mon May 07 15:0`

**Comment by kpaulaha** [comment]
I got binding manually working, but functions with cron not.

**Comment by PercyP** [comment]
Hi @kpaulaha 
how did you get it manually working?
I notice that the vtigercron.sh and .php are now missing from the cron folder too - maybe this has something to do with it not working?

**Comment by kpaulaha** [comment]
@PercyP By manually binding from the incoming post. Sorry, roundcube in Finnish.
![post](https://user-images.githubusercontent.com/10330264/39744770-01fc16f6-52ae-11e8-8731-c6410df71dbd.png)

Jup, I have noticed that cron runs from public_html/cron.php.

**Comment by kpaulaha** [comment]
Me neither if I have actions with the account, but when I remove them it works.
![settings](https://user-images.githubusercontent.com/10330264/39745824-181e8d12-52b1-11e8-89fa-185511120e3c.png)

**Comment by PercyP** [comment]
I tried it without those values, still can't get it working. I wonder if it has anything to do with that gmail address that was displayed in the error log in my first post? It is getting that from somewhere - but not from my configuration. Very odd

**Comment by kpaulaha** [comment]
Odd, I have 2 different installations on different servers and both working as I explained.

**Comment by PercyP** [comment]
@kpaulaha 
are all your configuration settings correct? I am thinking this is behind my problem i.e. all the headers, the public_html folder is showing as off and so on. I have been trying to add to the http.conf via WHM server configuration but the settings don't take affect. Would you have an example of your .htaccess, php.ini?

**Comment by PercyP** [comment]
Hi,
At last! finally figured it out. It was ridiculously stupid in the end. Basically I had the Verify certificate box ticked in the Roundcube mail settings. Once I removed this I could see the mail binding boxes within the email. I could also add the mail scanner actions and set the folders. 
Hope this is of help to others who have the same problem.

**Comment by paula-w** [comment]
We provided an answer in https://github.com/YetiForceCompany/YetiForceCRM/issues/6810

**Comment by artcien** [comment]
I have tried everything on this post to fix the exact same problem 

> Mail not found in the database. Import mail manually

Roundcube on my system "Verified Certificate" has been unticked since the beginning. 

The folders from mail scanner, I have also removed, changed... done everything but no luck.

any ideas?
