### ISSUE TITLE
New UI type

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#6755]
Can you add a new UI type - data from the related module when the relation is 1: M. Very often there are situations when i need to see in the filter from such a relation. For example, to see the type of account in Sales Orders.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by alexandr256** [comment]
This will save duplication of information ....
Or maybe you can tell what entities to create and in what places, except the folder UITypes, I will try to understand and develop myself

**Comment by paula-w** [comment]
There are already mechanisms in the system that are used for that, one of them is creating mapping (you first create a filed in a module where you want data to be filled automatically) and you create mapping similar to this: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/user_privileges/moduleHierarchy.php#L76
This should solve your problem. We know that the ideal solution would be to do that from the panel but it would require 1 – 3 days and someone would have to order that functionality.

**Comment by bpabiszczak** [comment]
Just write a small handler

**Comment by vovpff** [comment]
@bpabiszczak do you have any example?

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/HelpDesk/handlers/TicketRangeTime.php

**Comment by alexandr256** [comment]
I use handlers to automate processes, but here I'll have to write code for each new field and when changing data in the base module, change them in the child module. This is not difficult to do, but it violates the basic principle of database design, when data should not be duplicated.
It's much easier to add a JOIN on the link field to the database query.
A simple example
I divide Accounts into three types of new, permanent and VIP. I want to see at a glance from which of them she is. Now when I change the Account type, I need to change this field in all Sales Orders.
