### ISSUE TITLE
BUG Massedit

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#6756]
The condition filter shows only part of the records. If you click on "select all" when editing, all the records are changed, not only those that show the filter

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by alexandr256** [comment]
В первый раз я столкнулся с  этим в  версии 2.х, в последний раз 4.3.3
Действия выполнялись с учетной записи администратор. Поменялись все записи в системе, потом пришлось восстанавливать по истории.

**Comment by alexandr256** [comment]
В среду попробую обновиться до 4.4 и протестировать там.

**Comment by paula-w** [comment]
Can you please check it on the gitdeveloper version once again? In our opinion it's fixed now.

**Comment by Pietrox** [comment]
Do you have info on which commit it was made maybe?
We would need to isolate it and add it as we are still on 4.3 and waiting for full release.
