### ISSUE TITLE
User Edit generates an error when changing the "Reports to" field

### ISSUE THREAD

**Issue by theedoms** [YetiForceCompany/YetiForceCRM#6759]
#### Issue
When inserting a value in the field "Reports to" and saving, the system generates an error page.

#### Actual Behavior
page index.php is displayed with message:
Incorrect request
Illegal value in field reports_to_id (1)
#### Expected Behavior
Expect user to be updated and displayed

#### How to trigger the error
Edit a user and select a user name in the "Reports to" pop-up window

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Chrome Version 66.0.3359.139 (Build officiel) (64 bits)
* Environment name and version: 
* Operating System and version: DEBIAN

**Comment by paula-w** [comment]
The error has been fixed in the dev version.
