### ISSUE TITLE
[bug 4.3] Modtracker duplicates updates for products

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6764]
#### Issue

I found strange bug in my 4.3 system: every modification of product record saves 2 records about modification to updates tab.

![image](https://user-images.githubusercontent.com/8545791/39756133-0e3c1f38-52d1-11e8-9378-fd9c20f0d7cc.png)

 I checked ```vtiger_modrtacker_detail``` too an there are a lot of duplicates too:

![image](https://user-images.githubusercontent.com/8545791/39756225-680cd5de-52d1-11e8-928a-1ca2d0ca90e4.png)

How to trigger why it happens?

**Comment by konadrian** [comment]
Could you trigger this error on https://gitdeveloper.yetiforce.com/ ?

**Comment by vovpff** [comment]
@konadrian no. But I have this bug on my production system and looking for solution? How to find a cause?

**Comment by vovpff** [comment]
Any ideas? What info do you need?

**Comment by paula-w** [comment]
If the problem exist locally then a programmer has to check it locally. We can't blindly guess what might be wrong, it's not worth the time. Your system must be analyzed to find the problem.

**Comment by vovpff** [comment]
@konadrian @paula-w 
There are system bug because can be triggered on git developer:
I just added 2 field to products
- PickList field with two values
- Text field
And workflow:
If picklist has changed to ```plv_1``` then update text field.
There is gif with duplicating on git:
![wf_dup](https://user-images.githubusercontent.com/8545791/40473348-8fef0520-5f44-11e8-99df-b330ed3c5127.gif)
I has everytime duplicating because condition on step 2 was ```is``` instead ```has changed to```
