### ISSUE TITLE
Counter widgets

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#6769]
#### Issue

I think counter widgets are needed to display some statistics.
For future will be great to see widgets like this.
Eg.
![dashboard 16](https://user-images.githubusercontent.com/18266619/39758473-9f8ab01a-52d8-11e8-9590-f9ea9546b622.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
We will add more widgets in different places in the system but right now I can't give you a schedule when particular widgets will be added.
