### ISSUE TITLE
Export to Excel [BUG]

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#6772]
#### Issue

When I try to export data from a module, the data is moved with a column on the left. This means that the data on the first column is not exported, and the other data does not match the columns it belongs to.
![export to excel problem](https://user-images.githubusercontent.com/18266619/39772290-8e964cf4-52fd-11e8-8f36-9a1d232a8fe0.gif)

This error is present on all Modules.

#### Actual Behavior

The data is moved with a column on the left, but columns are exported ok.

#### How to trigger the error

1. Log on gitdeveloper.yetiforce.com
2. Go to Accounts module
3.Try to export data to Excel.

#### Your Environment

* YetiForce Version used: 4.3.329
* Browser name and version: Google Chrome
* Environment name and version: gitdeveloper
* Operating System and version:

**Comment by synchu** [comment]
This does not work as expected again. 

RelationAjax.php needs to be patched at wherever there is a reference to $col in a function (such as setCellValueExplicitByColumnAndRow, getStyleByColumnAndRow) should become $col + 1. 

This might be an issue with (expected) changes to PhpSpreadsheet implementation of the respective functions, but didn't have the time to dig further.
