### ISSUE TITLE
How to Integrated voip PBX with YetiForce 4.3

### ISSUE THREAD

**Issue by nam23690** [YetiForceCompany/YetiForceCRM#6793]
Dear all,
How to Integrated voip PBX with YetiForce 4.3 or a charge extension to integrate it.
Thanks

**Comment by paula-w** [comment]
Here's a [link](https://github.com/YetiForceCompany/YetiForceCRM/search?q=PBX&type=Issues) with all the questions we've answered so far, you can find more information in these issues.
Right now we don't have any clients who are using the PBX manager, so we're not supporting it. 
However, we noticed that more and more users are interested in this solution, so in the future we're going to create an integration like that.
