### ISSUE TITLE
where to enable the public_html folder as specified in server configuration

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6801]
Hi,

in the server configuration logs under the public_html the information icon says:

"We suggest that you install the system so that only the public_html folder is used. This improves data security by not having access to unpublic directories and files directly from the address"

Does this not happen automatically when yetiforce is installed?

Mine is currently set to off, but not sure where to change this setting

**Comment by PercyP** [comment]
Hi @slawekk87 

I still don't understand. Are you able to tell me exactly where you mean? Is it a configuration file somewhere?

**Comment by vovpff** [comment]
@I know what this can be solved by webserver parameters but I don't have experience to get public_html working configeration.

**Comment by mariuszkrzaczkowski** [comment]
Example for configuration in wampserver
C:\wamp\bin\apache\apache2.4.29\conf\extra\httpd-vhosts.conf
DocumentRoot c:/www/YetiForceCRM/**public_html**
```
<VirtualHost *:80>
  ServerName localhost
  ServerAlias localhost
  DocumentRoot c:/www/YetiForceCRM/public_html
   <Directory  "c:/www/YetiForceCRM/public_html/">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    #Require local
    Require all granted
   </Directory>
</VirtualHost>
```

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks for example
@PercyP my steps (on ubuntu)

New file added ```/var/www/html/crm/apache.conf```

```
Alias /crm /var/www/html/crm/public_html/

   <Directory  /var/www/html/crm/public_html/>
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    #Require local
    Require all granted
   </Directory>
```

After than added line at the end of ```/etc/apache2/apache2/conf```

```
Include /var/www/html/crm/apache.conf
```

Restart apache. Profit.

Next question how to change ```session_regenerate_id``` to on? Do you have any ideas?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/5ec15132d733212573e1e65158283525ffed1906/config/config.template.php#L161

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thx

**Comment by PercyP** [comment]
Hi,

I am back to this. I have nearly completed all the settings but there are still a couple outstanding. I am on CENTOS 6.10 and can access the pre-include file via WHM I found the structure for my document path by examining the global conf file in SSH. 

I don't know if it matters but my crm is in a sub folder on my site (in example the sub folder is called myfile:

<VirtualHost *:80>
ServerName localhost
ServerAlias localhost
DocumentRoot /home/mysite/myfile/public_html
<Directory "/home/mysite/myfile/public_html/">
Options +Indexes +Includes +FollowSymLinks +MultiViews
AllowOverride All
#Require local
Require all granted
</Directory>
</VirtualHost>

When I restart apache it still doesn't set the configuration to the correct values. So I still have the following configuration settings outstanding:


Recommended security settings | Required value | Present values

.htaccess | On | Off
public_html | On | Off
Header: Server |   | apache

And no matter what I do I cannot change the value for:

output_buffering | On | 1

Which is set incorrectly as 1

I have added this to my php.ini file for 7.1x and even via the WHM Cpanel multiphp editor but the value just doesn't change.

Has anyone else managed to get these configuration settings working on a EasyApache/CENTOS6.10 VPS?

**Comment by PercyP** [comment]
@mariuszkrzaczkowski,

I was about to reply to this :)

I was seeking answers by looking for your php.ini and stumbled across your test file which inclueded that line so I added it to my php.ini file and it worked. Does it have to go in the .user.ini file instead?

I also got the character_set_database error sorted by running this query on the mysql database: 

ALTER DATABASE dbname CHARACTER SET utf8;

Now I just have   the last 3 configurations to fix 

.htaccess | On | Off
public_html | On | Off
Header: Server |   | apache

**Comment by PercyP** [comment]
I am getting close I think. 

In WHM-Service Configuration-Apache Configuration-Include Editor - Pre Virtual Host Include - All versions 

I added the following:

<IfModule security2_module>
SecRuleEngine on
ServerTokens Full
SecServerSignature "Off"
</IfModule>

But this changes the configuration value to:
off mod_bwlimited/1.4

I did try leaving it blank as in your test example
SecServerSignature " "

But that changes the value to

mod_bwlimited/1.4

I also tried 

SecServerSignature Off

Nothing produces the empty result that yeti configuration wants to see

**Comment by PercyP** [comment]
Hi I am nearly there. I fixed the .htaccess by copying your htaccess file in the root yetiforcecrm and adding the content to the one in my crm root. Now it is just the HEADER SERVER and the document root left to fix. If anyone knows how to do those I would be eternally grateful :)

**Comment by ohandy1** [comment]
I'm trying to sort this same problem, though I don't want to hijack this thread if my issue isn't the same.
I run my server with WHM, I put softaculous on it. All the domains are in a shared environment as typical in WHM.  Every domain uses a public_html directory with WHM, so the questions is, would redirecting via htaccess to the nested public_html folder satisfy the security requirements?  I can't change the Apache configuration without affecting every domain on the server.

I'm happy to make a new thread, but since my question is very much like this one it might be good to consider alternative use cases.

**Comment by sundersingh179** [comment]
@mariuszkrzaczkowski unable to set public_html to On. below is the conf file.
[root@yetiforcecrm ~]# cat /etc/httpd/conf.d/yetiforce.conf
<VirtualHost *:80>
     ServerAdmin <email>
     ServerName <url>
     DocumentRoot /var/www/public_html

     <Directory /var/www/public_html/>
 	  Options +Indexes +Includes +FollowSymLinks +MultiViews
          AllowOverride All
          Require all granted
     </Directory>

     ErrorLog /var/log/httpd/yetiforce_error.log
     CustomLog /var/log/httpd/yetiforce_access.log combined
</VirtualHost>

Please advise how to fix it.
