### ISSUE TITLE
4.3 and PHP 7.2 Fatal error

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6802]
#### Issue

I'm established LAMP with php 7.2 and found what I can't install fresh 4.3 system with error:

```Fatal error: Cannot use 'Object' as class name as it is reserved in /var/www/html/yf/vendor/yii/base/Object.php on line 76```

As I understand there are not possible to migrate from another one server with 4.3?

**Comment by PercyP** [comment]
Hi,
I found that php 7.2 doesn't work with 4.3 - it works with 4.4 fine though.

**Comment by paula-w** [comment]
PHP 7.2.x is supported from YetiForce version 4.4.x on.

**Comment by vovpff** [comment]
@paula-w @mariuszkrzaczkowski How I can update from 4.3 to 4.4 (I mean in future) if I have only PHP 5.6 or 7.2?

**Comment by WalterLuis** [comment]
From yetiforce 4.3 to 4.4 is better use php 7.1

**Comment by ldgbc** [comment]
@vovpff PHP 5.6 won't work after v 4.2 (?). With v4.3 it require 7.1.10, when it v4.4 then you can use 7.2.

But to upgrade (through patch or download release) from 4.3 to 4.4 I think you will need to have v7.1 install someway else prepare to have White screen or crash.

**Comment by vovpff** [comment]
@ldgbc thanks. my 4.3 works perfect on php 5.6. Now I found solutipn for updating from 4.3 to 4.4
