### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#6807]
fatal error in import module
![untitled-1](https://user-images.githubusercontent.com/18072100/39940590-036e6e80-556f-11e8-809c-2b0a0210efbf.jpg)
tested on 4.3.331

**Comment by mariuszkrzaczkowski** [comment]
attach the file you imported, take a screenshot with field mapping

**Comment by vahid-jml** [comment]
Hi 
my csv file 
[Leads.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/1997291/Leads.zip)
![untitled-2](https://user-images.githubusercontent.com/18072100/39953659-ef6fc44a-55c5-11e8-8d03-d401716f744e.jpg)

**Comment by frankhzp** [comment]
same problem with the gitdeveloper version.  tried export data ,then tried to import , return the same fatal error as listed up.
