### ISSUE TITLE
Email Binding - missing the Add and Relate symbols on buttons

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6808]
Also tested this in the Developer version.

The Email binding buttons to Add record and Relate to existing record buttons are missing the icons i.e. the + symbol to add record.

See attached image taken for developer version

![missingsymbols](https://user-images.githubusercontent.com/10598886/39959018-6acd7bb8-5603-11e8-925f-925106a747d7.png)

**Comment by TomaszQr** [comment]
Fixed via https://github.com/YetiForceCompany/lib_roundcube/commit/d1223499acd87b4b5a0bd588d7818a3e61258eb7
