### ISSUE TITLE
[testing 4.4RC1] File upload partially working 

### ISSUE THREAD

**Issue by neerajwagh** [YetiForceCompany/YetiForceCRM#6809]
#### Issue

Did a fresh install of 4.4.0RC1-using the zip file posted here: https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.4.0_RC1/YetiForceCRM-4.4.0RC1-complete.zip

File upload feature seems to be partially broken. I tried the following operations:
1. adding new documents inside project using documents tab. This works properly only if "Full Form" is used. For "Quick Create", the UI stays the same, upload doesn't happen.
2. adding "multi image file" to a project task (added a new field for this) using Add Record under Project Tasks tab. Operation fails with HTTP 500.
3. For "Mass Add" under Project documents, the UI gets stuck. Upload does not go through:
![screenshot from 2018-05-13 02-59-24](https://user-images.githubusercontent.com/17927658/39961717-f8341d94-5659-11e8-995f-a56062509121.png)

#### Logs

1. Here is the "required vs current settings" list which was accepted during installation.
[YetiForce_installation_requirements_check.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/1997864/YetiForce_installation_requirements_check.pdf)

2. Here is what httpd error log shows for operation 1 mentioned above:
`[Sat May 12 20:59:14.174078 2018] [php7:error] [pid 12456] [client 103.54.19.224:35208] PHP Fatal error:  Uncaught Error: Class 'yii\\base\\NotSupportedException' not found in /home/yetiforce/yetiforce-4.4.0RC1/vendor/yetiforce/yii2/db/Connection.php:827\nStack trace:\n#0 /home/yetiforce/yetiforce-4.4.0RC1/vendor/yetiforce/yii2/db/Connection.php(836): yii\\db\\Connection->getSchema()\n#1 /home/yetiforce/yetiforce-4.4.0RC1/app/Db/Query.php(27): yii\\db\\Connection->getQueryBuilder()\n#2 /home/yetiforce/yetiforce-4.4.0RC1/app/Db/Query.php(97): App\\Db\\Query->createCommand(Object(App\\Db))\n#3 /home/yetiforce/yetiforce-4.4.0RC1/app/Company.php(36): App\\Db\\Query->one()\n#4 /home/yetiforce/yetiforce-4.4.0RC1/app/Controller/View.php(162): App\\Company::getInstanceById()\n#5 /home/yetiforce/yetiforce-4.4.0RC1/modules/Users/views/Login.php(35): App\\Controller\\View->preProcess(Object(App\\Request), false)\n#6 /home/yetiforce/yetiforce-4.4.0RC1/include/main/WebUI.php(261): Users_Login_View->preProcess(Object(App\\Request))\n#7 /home/yetiforce/yetiforce-4.4.0RC1/include/main/WebUI.php(183): Vtiger_WebUI->triggerPreProcess(Object(Users_Login_Vi in /home/yetiforce/yetiforce-4.4.0RC1/vendor/yetiforce/yii2/db/Connection.php on line 827
`
3. httpd error log for operation 2: 
`[Sat May 12 11:53:32.030483 2018] [php7:error] [pid 4959] [client 103.54.19.224:60016] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\\Fields\\File::getUploadFile() must be of the type string, null given, called in /home/yetiforce/app/Fields/File.php on line 1012 and defined in /home/yetiforce/app/Fields/File.php:1046\nStack trace:\n#0 /home/yetiforce/app/Fields/File.php(1012): App\\Fields\\File::getUploadFile(NULL)\n#1 /home/yetiforce/modules/Vtiger/uitypes/MultiImage.php(25): App\\Fields\\File::updateUploadFiles(Array, Object(Faq_Record_Model), Object(Vtiger_Field_Model))\n#2 /home/yetiforce/modules/Vtiger/actions/Save.php(111): Vtiger_MultiImage_UIType->setValueFromRequest(Object(App\\Request), Object(Faq_Record_Model))\n#3 /home/yetiforce/modules/Vtiger/actions/Save.php(79): Vtiger_Save_Action->getRecordModelFromRequest(Object(App\\Request))\n#4 /home/yetiforce/modules/Vtiger/actions/Save.php(58): Vtiger_Save_Action->saveRecord(Object(App\\Request))\n#5 /home/yetiforce/include/main/WebUI.php(184): Vtiger_Save_Action->process(Object(App\\Request))\n#6 /home/yetiforce/index.php(25): Vtiger_WebUI->process(Object( in /home/yetiforce/app/Fields/File.php on line 1046
`
4. relevant settings in php.ini:
file_uploads = On
upload_max_filesize = 100M
max_file_uploads = 20

#### Your Environment

* YetiForce Version used: 4.4.0RC1-complete.zip
* Browser name and version: Google Chrome Version 65.0.3325.146 (Official Build) (64-bit)
* Environment name and version: PHP 7.1.17, Apache 2.4, MariaDB 5.5.56
* Operating System and version: CentOS Linux release 7.5.1804 (Core)

**Comment by rafalpospiech** [comment]
Image / Multi image bug fixed
[view video](https://drive.google.com/uc?id=1YMM8tZHkDMT8ikaV3a8irRnp9pF_XMHN)
Upload files from project view fixed
[view video](https://drive.google.com/uc?id=1IuEvTxpScf9D-Z1vBRS9y6AHANTpY9eI)

**Comment by neerajwagh** [comment]
Looks great, thank you!
