### ISSUE TITLE
Roundcube Mail Scanner problem SaveActions.php after updating library via module installation

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6810]
After finally getting my Roundcube email binding working I am now back to square one. Foolishly I updated the library by clicking on the Update button in the Modules Installation area. 

I am still on Yetiforce 4.3 (waiting for the Update package to 4.4) and think I may have done the wrong thing updating Roundcube library as can see there are some file changes which possibly only work with 4.4? 

Now binding no longer works. I get the Incorrect access data error when trying to set up the scanner folders. 

I have tried everything I did in the past to get it working again, but they don't work. 

In my php error log I have these 2 messages:
`[13-May-2018 13:08:06 Europe/London] PHP Warning:  implode(): Invalid arguments passed in /home/linkprocrm/public_html/mysite/modules/OSSMailScanner/actions/SaveActions.php on line 31
[13-May-2018 13:10:42 Europe/London] PHP Warning:  implode(): Invalid arguments passed in /home/linkprocrm/public_html/mysite/modules/OSSMailScanner/actions/SaveActions.php on line 31`

In the cpanel error log I see these last few error messages:

`[Sun May 13 17:59:03.681125 2018] [:error] [pid 16390:tid 140390130722560] [client 165.120.60.125:50407]   thrown in /home/mysite/public_html/yetiforce/public_html/modules/OSSMail/roundcube/plugins/yetiforce/yetiforce.php on line 138, referer: https://www.mysite.com/yetiforce/public_html/modules/OSSMail/roundcube/
[Sun May 13 17:59:03.680970 2018] [:error] [pid 16390:tid 140390130722560] [client 165.120.60.125:50407] #1 /home/mysite/public_html/yetiforce/public_html/modules/OSSMail/roundcube/index.php(139): rcube_plugin_api->exec_hook('login_after', Array), referer: https://www.mysite.com/yetiforce/public_html/modules/OSSMail/roundcube/
[Sun May 13 17:59:03.680851 2018] [:error] [pid 16390:tid 140390130722560] [client 165.120.60.125:50407] #0 /home/mysite/public_html/yetiforce/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): yetiforce->loginAfter(Array), referer: https://www.mysite.com/yetiforce/public_html/modules/OSSMail/roundcube/
[Sun May 13 17:59:03.680592 2018] [:error] [pid 16390:tid 140390130722560] [client 165.120.60.125:50407] PHP Fatal error:  Uncaught Error: Call to undefined method App\\Encryption::getInstance() in /home/mysite/public_html/yetiforce/public_html/modules/OSSMail/roundcube/plugins/yetiforce/yetiforce.php:138, referer: https://www.mysite.com/yetiforce/public_html/modules/OSSMail/roundcube/
[Sun May 13 17:35:28.813190 2018] [:error] [pid 16502:tid 140390183171840] [client 165.120.60.125:50274]   thrown in /home/mysite/public_html/yetiforce/public_html/modules/OSSMail/roundcube/plugins/yetiforce/yetiforce.php on line 138, referer: https://www.mysite.com/yetiforce/public_html/modules/OSSMail/roundcube/
[Sun May 13 17:35:28.812996 2018] [:error] [pid 16502:tid 140390183171840] [client 165.120.60.125:50274] #1 /home/mysite/public_html/yetiforce/public_html/modules/OSSMail/roundcube/index.php(139): rcube_plugin_api->exec_hook('login_after', Array), referer: https://www.mysite.com/yetiforce/public_html/modules/OSSMail/roundcube/
[Sun May 13 17:35:28.812834 2018] [:error] [pid 16502:tid 140390183171840] [client 165.120.60.125:50274] #0 /home/mysite/public_html/yetiforce/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): yetiforce->loginAfter(Array), referer: https://www.mysite.com/yetiforce/public_html/modules/OSSMail/roundcube/
`
I hope someone can help me as this issue with the mail binding has become the bane of my life :O(

Kind regards

**Comment by paula-w** [comment]
Hi Chris,
The problems you are experiencing result from the fact that you are modifying core files, which always has consequences. You can do that but it’s a waste of your time.
We can take a look at it, but unfortunately we will have to charge for that :(

**Comment by PercyP** [comment]
Hi Paula,

are you saying because of my property customisation it created the problems with the mail? or is it because of my template (there were only 2 files that you edited in that both css files).

**Comment by KatarzynaUlichnowska** [comment]
We don't know what might be the reason but you must eliminate any changes in the files.

It's best to install a clean version of the system and send us the access data (www, ftp, mysql) and describe how we can trigger the error. However, it needs to be on a clean and unmodified version.

**Comment by PercyP** [comment]
Hi I will try do that - many thanks
