### ISSUE TITLE
[bug] Field update incorrect (moduleHierarchy)

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6815]
#### Issue

Field update mechanism not update field if record mapped:

If Sales Order generated from Quote by mapping tool Company name field not filled automatically as written here: https://github.com/YetiForceCompany/YetiForceCRM/blob/2cc001445f35b1a439fd22fe89a9fbb1f32a942c/user_privileges/moduleHierarchy.php#L55

P.S. Another one issue: Field Company name not updated automatically if related company name changed.

**Comment by paula-w** [comment]
As far as the first issues is concerned - we will check it.
When it comes to the second issue - this is how it should work.

**Comment by arek1-618** [comment]
Two versions of the solution to the problem:
1) Auto-complete fields.
![2018-11-19_14-52-12](https://user-images.githubusercontent.com/32322851/48712427-03aa7480-ec0e-11e8-8564-3d29bb3b87cc.gif)
https://github.com/YetiForceCompany/YetiForceCRM/pull/8607/files

2) Field mapping.
![2018-11-19_15-04-36](https://user-images.githubusercontent.com/32322851/48712470-25a3f700-ec0e-11e8-9d79-6cade4dbed7d.gif)
How to configure field mapping.
![2018-11-19_15-09-51](https://user-images.githubusercontent.com/32322851/48712478-2a68ab00-ec0e-11e8-955a-fc12e54c4d6e.gif)

Please, let me know if this is what you are looking for.

**Comment by vovpff** [comment]
@arek1-618 thanks a lot. What about hooking up updated data from related modules? For example if Account name changed?

**Comment by arek1-618** [comment]
In this case, the account name will also be changed automatically.
![2018-11-19_15-55-46](https://user-images.githubusercontent.com/32322851/48714897-027c4600-ec14-11e8-8e81-9357063c8fb5.gif)

**Comment by vovpff** [comment]
@arek1-618 oh sorry. I mean `Company name` field.

**Comment by mariuszkrzaczkowski** [comment]
This field isn't updated on purpose because according to law, we must have a company name when a record/document was created.
If you want to have a current name, you can find it in the reference field.
