### ISSUE TITLE
Question: Accounting, Bookkeeping & Bank Reconciliation App - is it a possibility? Who else is interested?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6817]
Hi,
I remember a while back Yetiforce mentioned they would be working on a proper accountancy/bookkeeping component. We are looking for this and I was wondering how many others were also interested? Basically we need something that can also carry out banking reconciliation (via an API?), Ledger/Journal etc. 

I did look into this last year and you can get Sage, Quickbooks, MYOB etc. integrations but I think @bpabiszczak said they would be more inclined to build their own rather than use another solution (think that was what he meant). This makes much more sense.  

My questions are:
1. How many Yetiforce users would be interested in a proper component for this?
2. If you are interested, would you be interested (if it is doable) in helping towards cost of having it built?
3. And the most important question is for @bpabiszczak @paula-w  is this something Yetiforce would ever consider? If yes, what would be the likely cost?

Kind regards

Chris

**Comment by PercyP** [comment]
Hi @cbdesignsbybre,

the beauty of having one built into the system is there will be no extra costs to pay to third party providers (as would happen with Sage, Quickbooks, MYOB etc. Plus, we wouldn't have issues upgrading to future versions of Yetiforce as the new component would be part of their core. 

I currently have a number of 3rd party integrations and it is a nightmare to upgrade every time a new version of Yetiforce is released. I keep having to have a new version of the component created which costs me every time.

I do hope this is something the team at Yetiforce can introduce, and hope once we get enough people interested in having an accountancy component incorporated we can start the ball rolling.

**Comment by cltvchannel** [comment]
Yes, me too i'm interested.

**Comment by ra-uk** [comment]
Would certainly enhance it as a CRM and add to the possibility of companies using it as every person, asset, opportunity and project (for example) all go back to finance - it would be a very good addition  :)

**Comment by PercyP** [comment]
@ra-uk 
I totally agree. It would be good having all the applications you need to run your business in one system. For us, Yetiforce is the most complete and user friendly system and very customisable so has endless possibilities and with each new release it just keeps on getting better!

**Comment by paula-w** [comment]
Hi guys, thanks a lot for the suggestion! 
We definitely want to improve the bookkeeping functionality in YetiForce but it requires tremendous amount of work, which unfortunately means that the costs of developing such a module would amount to ~100k €. 
For now we can't tell you when this functionality will be added because currently no clients are interested in developing it.

**Comment by jcsanchesgithub** [comment]
> Hi guys, thanks a lot for the suggestion!
> We definitely want to improve the bookkeeping functionality in YetiForce but it requires tremendous amount of work, which unfortunately means that the costs of developing such a module would amount to ~100k €.
> For now we can't tell you when this functionality will be added because currently no clients are interested in developing it.

could you please create a crowfund project for those missing feautures Bookkeeping and Bank Reconciliation. I beleive we will have interested people to support that project.

Thanks and kind regards
Joao Sanches
