### ISSUE TITLE
Workflow - Count duplicate values

### ISSUE THREAD

**Issue by noexcuses2018** [YetiForceCompany/YetiForceCRM#6836]
Good Night Friends ! 

I need count duplicate values ​​and show in another field, for example the tickets that were opened more than once, if the insert value already exist add all
 I'm trying to do with triggerts but ,no success! Thks for help !!

![help](https://user-images.githubusercontent.com/39356664/40153148-b1af3a0e-595e-11e8-9ac7-98af9cd5789c.png)

**Comment by vovpff** [comment]
@noexcuses2018 you can try to update value (custom field) with trigger to some status of ticket has been changed to open with expression ```filedname +1```

**Comment by paula-w** [comment]
We don’t really understand what you mean. We assume you might mean custom record marking via Workflow. It can be done by a custom function but it might it be better to do it via handler in some cases.
No matter which method you pick, you will need a programmer to do that.
