### ISSUE TITLE
Handler not found when export pdf. Help needed.

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6854]
#### Issue

Aftem moving from WAMP to LAMP I can't export pdfs with error

```Error!!!
LBL_HANDLER_NOT_FOUND
```

system.log

```
2018-05-22 11:28:39.5001 [error] - Error Vtiger_Loader::getComponentClassName(Pdf, Mpdf, IGDN): Handler not found
2018-05-22 11:28:39.5001 [error] - LBL_HANDLER_NOT_FOUND => /var/www/html/etwh/include/Loader.php:164
2018-05-22 11:28:39.4864 [info][application] - 
$_GET = [
    'module' => 'IGDN'
    'action' => 'PDF'
    'mode' => 'generate'
]
$_POST = [
    '__vtrftk' => 'sid:xxx'
    'all_records' => '[]'
    'selectedRecords' => '[]'
    'validRecords' => '[]'
    'template' => '25'
    'single_pdf' => '0'
    'email_pdf' => '0'
    'record' => '3032'
    'fromview' => 'Detail'
    'pdf_template' => [
        0 => '25'
    ]
]
```

Why it happens? How to solve this?

**Comment by vovpff** [comment]
PFD templates edition not possible too. Endless loading after step 7

**Comment by vovpff** [comment]
In what direction should I dig for the find cause of the problem? This is apache/php configuration problem or some missing parameters for crm system?

**Comment by vovpff** [comment]
@paula-w @bpabiszczak @mariuszkrzaczkowski @konadrian 
Can you help me?

**Comment by paula-w** [comment]
You didn’t provide us with the basic details so we can’t really help at the moment.
You should check if the same bug exists on GitStable, if it doesn’t then it means that the bug depends on configuration. The two most common problems we stumble upon are wrong file/folder permissions and a reference to a nonexisting image in the template we’re trying to trigger. 
In order to verify what the problem is a programmer should access your server and verify it directly in there.

**Comment by vovpff** [comment]
@paula-w this is some local problem but I can't understand why it happens.
Fresh 4.3 and 4.4RC1 works perfect on my Ubuntu server but my production 4.3 system not works.
All permission is 0777 and template doen not contain images and etc. Only text.
I'm confused...

**Comment by mariuszkrzaczkowski** [comment]
>  Error Vtiger_Loader::getComponentClassName(Pdf, Mpdf, IGDN): Handler not found

and

>  Uncaught Error: Class 'Vtiger_Mpdf_Pdf' not found

that means there is no file modules/Vtiger/pdfs/Mpdf.php
check if the size of the letters, because there was such a issue, in the new version the update package will fix it.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks for your advice. It works when file renamed. Old name was mPDF.php. Thanks you!
