### ISSUE TITLE
Fields of the related module in listview.

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#6866]
Since the module report was removed in version 4.4, there is now no way to export the excel file with the information fields of the related module. Is it possible to integrate a related module field into a listview?

![zalo_screenshot_23_5_2018_104712](https://user-images.githubusercontent.com/19627226/40418030-75a67f70-5eab-11e8-9c6b-40cf133221f2.png)
![zalo_screenshot_23_5_2018_103223](https://user-images.githubusercontent.com/19627226/40418031-75e65c12-5eab-11e8-9223-7b8ec69d2e7c.png)

**Comment by vovpff** [comment]
@ezbank try this #6815

**Comment by ezbank** [comment]
@vovpff it could not resolve problem :(

**Comment by vovpff** [comment]
@ezbank this is solution. What is your parent module?

**Comment by paula-w** [comment]
We're planning to add this feature in the nearest future.

**Comment by ldgbc** [comment]
Off-topic:
@ezbank How do keep track of your "Referral Number"? Do you just type them? 

How do you link them? For example Referral: 106 refer all these contact that easy to display and link like Account>Related to Contact

I'm trying to setup a Referral system too and would like to get some idea.

**Comment by bpabiszczak** [comment]
We are currently working on a report module. It will also be possible to show fields from the related module [only 1: M]
