### ISSUE TITLE
RODO 

### ISSUE THREAD

**Issue by epsilonsc** [YetiForceCompany/YetiForceCRM#6877]
Witam zgodnie z RODO przestaje już istnieć pojecie ABI oraz GIODO a w rejestrze zbiorów jest 
-"Zbiór zgłoszony do GIODO"
-Wpisany do obowiazkowego rejestru ABI

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: https://gitdeveloper.yetiforce.com/
![rodo-rejestr zbiorow](https://user-images.githubusercontent.com/10506580/40478995-cfee44dc-5f4a-11e8-90ce-2d985da79c00.PNG)

* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by simryc** [comment]
Na początek witam wszystkich,

sory za offtop:
skąd można pobrać moduł giodo/rodo jak na screenie wyżej?
obecnie uzywam 4.4.0rc1

**Comment by bpabiszczak** [comment]
@simryc https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.4.0_RC1

**Comment by bpabiszczak** [comment]
@epsilonsc zmienimy na szybko nazwy, jednak będziemy to jeszcze głębiej analizować w przyszłym tygodniu.
