### ISSUE TITLE
[Question] How to connect with OAuth2?

### ISSUE THREAD

**Issue by ra-uk** [YetiForceCompany/YetiForceCRM#6878]
Can't find anything at https://yetiforce.com/en/knowledge-base/documentation/developer-documentation on OAuth or API.

What are the API URL details or where can I find them please?

Maybe the Access key in My Preferences?

Thank you.

**Comment by paula-w** [comment]
The code responsible for API can be found here:  https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/api/webservice

Unfortunately right now we don’t have any documentation that describes it, we’re working on it. However, it shouldn’t be difficult for a good programmer.

Keep in mind that there are 2 tools in the panel in the Integration category, one of them configures apps that can access the system, the other one configures users who can have access to the system (an example of that configuration for Portal can be found on [GitDeveloper](https://gitdeveloper.yetiforce.com/))

**Comment by ra-uk** [comment]
@paula-w Thank you for that. I get this error:

`{"status":0,"error":{"message":"Webservice - Service is not active"}}`

How do I activate the service?

**Comment by ra-uk** [comment]
Also, in the Webservice module I can only add a Portal 'Type' when I try to add a new Key. How do I add a standard key to access the API externally? Or is that the key in user preferences?

**Comment by ra-uk** [comment]
Lastly, do I use Basic Auth or OAuth 2.0?

Thank you.
