### ISSUE TITLE
Status appearance

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6884]
#### Issue

I want to show something like this for status on modules where i have status field.
![status](https://user-images.githubusercontent.com/30116021/40527404-de15eac4-5ff4-11e8-8f76-184bb1a84066.png)

Top CRM's have already implemented this.

#### Actual Behavior

Eg. Status of a project will become more visible than is now on a field.

#### Expected Behavior

I need some instructions.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: gitdeveloper.yetiforce.com
* Browser name and version: Google Chrome
* Environment name and version:
* Operating System and version:

**Comment by PercyP** [comment]
+1 looks like a nice feature to have

**Comment by simryc** [comment]
+1

**Comment by SALITEL** [comment]
+ 1

**Comment by aljoflo** [comment]
It wil be awesome to have this implemented in the opportunities as well

**Comment by ldgbc** [comment]
I guess it can be use for other thing such a Project Milestone too.

**Comment by ldgbc** [comment]
I recently discover Color Picklist. Isn't that good enough?

**Comment by cltvchannel** [comment]
Not the color was the idea. The idea was the way that show status.

**Comment by aljoflo** [comment]
Awesome feature, is there any way it can be added to the stable version?

**Comment by bpabiszczak** [comment]
will be available in version 4.5
