### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#6885]
#### Issue

When will be avabile the new version?
We need to use modules for GDPR.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
This is what @bpabiszczak said:

We need some more time to finish what we’re  currently working on, we have to:

1. Finish GDPR modules
2. Finish WCAG/RWD
3. Finish 2FA
4. Take care of a few smaller problems, and we want to close all GitHub issues.

We simply need some more time to do all that.
