### ISSUE TITLE
4.4RC1 - Update label and record status

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6886]
#### Issue

I checked this bug in my 4.3 system but bug can be triggered in gitdev.

Records what checked as archived by button

![image](https://user-images.githubusercontent.com/8545791/40533226-afb519d2-600a-11e8-8fed-808ad7b09ec9.png)
 
Don't became unsearchable for uitype 10 fields after:

- status changing time (archibe record)
- automatic start of CRON "Update Labels" task

Easier: Strings in database table ```u_yf_crmentity_search_label``` not updated automatically after clicking Archive record button or CRON task

Needed result can be achieved only if you click to update labels button from admin panel ```Software configuration - Search and filters - Search Configuration``` to forced fields label update.

I can't provide gif because process takes a lot of time (CRON interval).

**Comment by paula-w** [comment]
Can you clarify a little bit what you mean? I can't understand what you mean that records "don't became unsearchable for uitype10 fields". Thanks!

**Comment by vovpff** [comment]
@paula-w example with products:
Active product record can be searched in advanced modules items table in dropdown list.

![image](https://user-images.githubusercontent.com/8545791/40650799-c0d5568e-633c-11e8-81b7-a6924479c8ad.png)

 If product record moved to archive this product must disappear from dropdown list but now ```u_yf_crmentity_search_label``` table not updated automatically if record moved to archive. ```u_yf_crmentity_search_label``` table can be updated only by admin with forced fields label update.
