### ISSUE TITLE
Installtion Problems

### ISSUE THREAD

**Issue by jsutherlandwest** [YetiForceCompany/YetiForceCRM#6889]
Hi I am not sure where to post for help to do with yetiforcecrm, so thought here would be a good start. I am trying to run Version 4.3.0 on Ubuntu Server 16.04.4 with apache 2.4.18 MariaDB 10.0.33 and PHP 7.0 (I have also tried 7.1 & 7.2) So I go through the setup procedures everything looks fine and we get the green installation bar after this nothing happens. I enabled the debuging and below are the error logs. any help in getting this up and running would be great.

**_phpError Log_**

 Stack trace:

0 /var/www/clients/client1/web11/web/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_5b06a759d70323_48441077(Object(Smarty_Internal_Template))
1 /var/www/clients/client1/web11/web/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(172): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
2 /var/www/clients/client1/web11/web/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(206): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
3 /var/www/clients/client1/web11/web/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(372): Smarty_Internal_Template->render()
4 /var/www/clients/client1/web11/web/cache/templates_c/basic/71fbc5bb5d6cd4d4bdf449bcbb6889823229fba4_0.file.Header in /var/www/clients/client1/web11/web/cache/templates_c/basic/7193bc63218adf5e09b6b078e8e4403dc5b06f55_0.file.Body.tpl.php on line 27

_**System.log**_ 

]==================================================================================================================================== 2018-05-25 09:47:18.2371 [info][yii\db\Command::query] - SELECT * FROM s_yf_companies WHERE default=1 2018-05-25 09:47:18.2372 [info][yii\db\Connection::open] - Opening DB connection: mysql:host=localhost;dbname=c1yeticrm;port=3306 2018-05-25 09:47:18.2372 [profile begin][yii\db\Connection::open] - Opening DB connection: mysql:host=localhost;dbname=c1yeticrm;port=3306 2018-05-25 09:47:18.2381 [profile end][yii\db\Connection::open] - Opening DB connection: mysql:host=localhost;dbname=c1yeticrm;port=3306 2018-05-25 09:47:18.2383 [profile begin][yii\db\Command::query] - SELECT * FROM s_yf_companies WHERE default=1 2018-05-25 09:47:18.2385 [profile end][yii\db\Command::query] - SELECT * FROM s_yf_companies WHERE default=1 2018-05-25 09:47:18.2441 [info][yii\db\Command::query] - SELECT * FROM vtiger_tab 2018-05-25 09:47:18.2442 [profile begin][yii\db\Command::query] - SELECT * FROM vtiger_tab 2018-05-25 09:47:18.2444 [profile end][yii\db\Command::query] - SELECT * FROM vtiger_tab 2018-05-25 09:47:18.2271 [info][application] - $_COOKIE = [ '_hp2_id_3731580590' => '{\"userId\":\"8127074596400446\",\"pageviewId\":\"2766794053778015\",\"sessionId\":\"3967800177103554\",\"identity\":\"28610\",\"trackerVersion\":\"4.0\",\"identityField\":null,\"isIdentified\":1}' 'sugar_user_theme' => 'SuiteP' 'ck_login_language_20' => 'en_us' 'EmailGridWidths' => '0=10&1=10&2=150&3=250&4=175&5=125' 'PHPSESSID' => 'ohupfu19snumdfvc2hg4uoqsj6' 'ck_login_id_20' => 'eef6ef63-141f-bfad-a8a5-5b056aab5e1d' 'YTSID' => '393m8hidmh5acal4u5bo2dupr4' ] $_SESSION = [ 'default_language' => 'en_us' 'config_file_info' => [ 'module' => 'Install' 'mode' => 'step5' 'lang' => 'en_us' 'db_type' => 'mysql' 'db_hostname' => 'localhost' 'db_port' => '3306' 'db_username' => 'c1yeticrm' 'db_password' => 'DBPassword' 'db_name' => 'c1yeticrm' 'db_root_username' => '' 'db_root_password' => '' 'currency_name' => 'England, Pounds' 'user_name' => 'admin243' 'password' => 'Password' 'retype_password' => 'Password' 'firstname' => 'Admin' 'lastname' => 'Administrator' 'admin_email' => 'info@mydomain.co.uk' 'dateformat' => 'dd-mm-yyyy' 'timezone' => 'Europe/London' 'authentication_key' => 'd3095f8c409ee144b31054015acaede0d9d0dea0' 'site_URL' => 'https://crm.mydomain.co.uk/' 'currency_code' => 'GBP' 'currency_symbol' => '£' ] 'timezone' => 'Europe/London' ] $Libs = [ 0 => 'ldap_connect' ] $PHP = [ 'session.gc_probability' => '0'

**_viewer-debug.log_** 

URI: /, TYPE: GET\nVIEW: modules/Users/Header.tpl > modules/Vtiger/Header.tpl, FOUND: 1\nDATA: APPTITLE, TYPE: literal\nDATA: YETIFORCE_VERSION, TYPE: literal\nDATA: MODULE_NAME, TYPE: literal\nDATA: PAGETITLE, TYPE: literal\nDATA: BREADCRUMB_TITLE, TYPE: literal\nDATA: HEADER_SCRIPTS, TYPE: array\nDATA: STYLES, TYPE: array\nDATA: SKIN_PATH, TYPE: literal\nDATA: LAYOUT_PATH, TYPE: literal\nDATA: LANGUAGE_STRINGS, TYPE: array\nDATA: LANGUAGE, TYPE: literal\nDATA: HTMLLANG, TYPE: literal\nDATA: SHOW_BODY_HEADER, TYPE: literal\nDATA: SHOW_BREAD_CRUMBS, TYPE: literal\nDATA: USER_MODEL, TYPE: Users_Record_Model\nDATA: MODULE, TYPE: literal\nDATA: VIEW, TYPE: literal\nDATA: PARENT_MODULE, TYPE: literal\nDATA: COMPANY_DETAILS, TYPE: App\Company\nDATA: COMPANY_LOGO, TYPE: Vtiger_Image_Model\nDATA: QUALIFIED_MODULE, TYPE: literal\n

**Comment by paula-w** [comment]
Version 4.3 works only with PHP version 7.1.x. We haven’t tested it on MariaDB for 4.3 so we are not sure if it works properly. For version 4.4 MariaDB is being tested.
Unfortunately these problems can only be solved if a programmer can access your server, would be best if he had full access to your logs. Each case should be verified individually and directly on the server where the problem exists. Unfortunately we charge for this kind of support. 
If you are interested [THIS](https://yetiforce.shop/index.php?option=com_djcatalog2&view=items&cid=8:technical-support&Itemid=1071) is where you can find our support packages.
