### ISSUE TITLE
[Suggestion] To be able to configure the phone format

### ISSUE THREAD

**Issue by SALITEL** [YetiForceCompany/YetiForceCRM#6890]
#### Issue
Currently the telephone format is +34 000 00 00 00 but there is another alternative format more used in mobile telephones +34 000 000 000

Is it possible to configure this format?

#### Actual Behavior

Display format: +34 000 00 00 00

#### Expected Behavior

New Display Format: +34 000 000 000

#### How to trigger the error

No error

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome
* Environment name and version: Windows 10
* Operating System and version: CentOS on server

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/config.template.php#L203

**Comment by paula-w** [comment]
We added a library that has its own configuration to the system :
https://github.com/giggsey/libphonenumber-for-php#documentation

You can check how it can be changed, by default we display the format that the library imposes for a given country and phone type. However, this is just a visual matter, we always search in the database omitting whitespace.

**Comment by ldgbc** [comment]
@SALITEL did you understand what to do after those two comments? I'm still confuse as how to make the edit.
