### ISSUE TITLE
[Question] - Unsure as to why the chat is global as opposed to P2P?

### ISSUE THREAD

**Issue by ra-uk** [YetiForceCompany/YetiForceCRM#6895]
The chat in YF is global, I was wondering why this is, as it would make good business sense to have P2P chats and even user groups?

Is this something YF will ever change or implement?

Thank you.

**Comment by paula-w** [comment]
We're planning to add more features to the chat in the future, as it's an integral part of the system. Right now I can't tell you when exactly these changes will be introduced, but it's definitely something we want to do.
