### ISSUE TITLE
Generate record - can this function be added to other existing and custom modules?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6896]
Hi,

I just spotted the Generate record icon when in Accounts etc. I wondered if there is an option for us to add this feature ourselves to other modules and custom modules? 

Kind regards

**Comment by vovpff** [comment]
@PercyP just add new mapping trough admin panel and this button must apear in module. For example mapping from accounts to vendors

https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95

**Comment by PercyP** [comment]
@vovpff 
thank you! that opens up a whole new set of possibilites for me :)

**Comment by ldgbc** [comment]
@PercyP Can you share those possibilities of what you planning to do with them?

Currently all I can think of is to convert Employee to Contact for example. Or vice versa.

For future reference:

Mapping or Generate Record basically Copy Information (according to your Mapping) from one Module (for example: Contact) to another Module (for example: Accounts).
