### ISSUE TITLE
How to add the Google map in another module with new address fields

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6898]
Hi,

I have added address fields to the ticket module and trying to get the google map to show on the record summary page (the way it is displayed for Contacts etc.) 

I have checked the widget mapping but cannot see anything for maps. Does this need to be added in a different way?

**Comment by paula-w** [comment]
Hi Chris,
First of all the integration with google maps requires a commercial license that costs ~$10.000, and you shouldn’t integrate with Google maps unless you have the license.
Secondly, the map only works with modules from the “Companies and contacts” tab by default, if you want it to work with different modules it will require some programming work.
It applies to the standard version, I’m not sure if you are asking about the standard version or the version we modified for you.

**Comment by PercyP** [comment]
Hi Paula thanks for response.

I didn't mean integration of another Google maps, I just meant being able to have the map link for other modules where there is an  address as I assumed it could appear in any module.

Thanks for explaining

**Comment by PercyP** [comment]
![map](https://user-images.githubusercontent.com/10598886/40986068-3d5d9bd0-68dd-11e8-897e-d89eab0dd269.png)
This is what I meant

**Comment by PercyP** [comment]
I think I can get around it by using the Partnes module as that has the map in it :)

**Comment by ldgbc** [comment]
@PercyP how did you get your Menu to display downward like that instead of 2 column on hover?

**Comment by PercyP** [comment]
Hi,
that is the git developer version. It is the new menu in version 4.4 - I am still on 4.3 as waiting for the upgrade which won't be released until 15th June now. If you go check out git developer version you will see new menu style
