### ISSUE TITLE
Is possible to export comments in PDF with the owner name

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#6899]
#### Issue

Currently when you export comments on template emails or PDF the comments are not market with the creator name, it is just the comment. There is a way to export this with the name of the user who creates the comments?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Dev
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
Can you please provide us with more details? We need to see how and where you configure the export. Screenshots will be helpful.

**Comment by aljoflo** [comment]
Thank for the reply. What i mean is when i try to show the comments related to a module, in this case opportunities, the comments are shown but without the user name and date who created this comment, just text and i would like to show the user detail on the PDF document or email template.

You will see it here on the gif, it's the same with the Dev version:
![gif](https://user-images.githubusercontent.com/20831164/40854481-461b46d0-6597-11e8-8107-5a99d4d8f383.gif)

**Comment by mariuszkrzaczkowski** [comment]
I added this option, here is an example 

```
$(record : Comments|0|true)$
```

**Comment by johndiff44** [comment]
This works great. Now what would I add to also see the time stamp of each comment
