### ISSUE TITLE
Time Control Record List

### ISSUE THREAD

**Issue by FredFaraday** [YetiForceCompany/YetiForceCRM#6905]
#### Issue
Time control record list - Subprocess Column - How to add or change output from Title to subprocess record number

#### Your Environment

* YetiForce Version used: 4.3.0

**Comment by vovpff** [comment]
@FredFaraday 1st add new field to time control.
2nd try to understand how this file works and put here new relations to subprocess record number https://github.com/YetiForceCompany/YetiForceCRM/blob/efdbae599e4cc47364a85c5c72043c16a5a186b7/user_privileges/moduleHierarchy.php#L33
3rd change time control filter column subprocess to record number

**Comment by bpabiszczak** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=CustomView&view=Index&parent=Settings&sourceModule=HelpDesk
