### ISSUE TITLE
Negative stock value

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6915]
#### Issue

I need to stop ad product quantity on invoice bigger than current stock.
Eg. If Product have stock 24, don't allow to add 25 on invoice.

#### Actual Behavior

Currently i can add any value to product quantity on invoices and logistics modules.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: GItdeveloper
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
Stock control only works in logistic modules. Issuing an invoice for products should follow issuing a storage document eg. Goods Dispatched Note.
It can of course be changed but it will require some programming work.

**Comment by cltvchannel** [comment]
@paula-w Where i need to change?
