### ISSUE TITLE
Mail notifications

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6931]
#### Issue

There is a posibility to integrate notifications to roundcube library?
I think is very useful to have a notification when receive emails. (somethink like desktop notifications)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
https://gitstable.yetiforce.com/index.php?parent=Settings&module=Mail&view=Config&block=8&fieldid=79
