### ISSUE TITLE
Brand new installation fails to import

### ISSUE THREAD

**Issue by thebravoman** [YetiForceCompany/YetiForceCRM#6934]
#### Issue

Installed with Softwacolus. Brand new installation
#### Actual Behavior

Go to import. Select a CSV. Map first, last name, email, phone, assigned to from an existing email and an error occurs

````
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'u_yf_import_1' already exists The SQL being executed was: CREATE TABLE `u_yf_import_1` ( `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, `temp_status` smallint(1) DEFAULT 0, `recordid` int(11), `firstname` varchar(40), `lastname` varchar(80), `jobtitle` varchar(100), `phone_extra` varchar(100), `email` varchar(100), `description` text, `assigned_user_id` varchar(255) ) CHARACTER SET utf8 ENGINE=InnoDB
````
#### Expected Behavior

I would expect the contacts to be importet

#### How to trigger the error

I wnet to screentogif but page said - Project 'screentogif' was not found
1.
2.
3.

#### Your Environment

* YetiForce Version used: [ver. 4.3.0] [Page loading time: 0.187s.]
* Browser name and version: Firefox 60.0.1
* Environment name and version: 
* Operating System and version: LInux

**Comment by vovpff** [comment]
@thebravoman Looks like previous import attempt finished unsuccessful and  table ```u_yf_import_1``` was not removed by system.
Попробуйте ручками удалить в БД таблицы, которые import_1 и import_inventory если таковые имеются и по новой импорт запустить.

**Comment by KatarzynaUlichnowska** [comment]
Hello, try to trigger this error at https://gitstable.yetiforce.com/ and then try to trigger it at https://gitdeveloper.yetiforce.com/ and if you manage it do that, please send us the imported file and we will check what's wrong.
