### ISSUE TITLE
Users cannot view records according to their role.

### ISSUE THREAD

**Issue by antonio-bcn** [YetiForceCompany/YetiForceCRM#6935]
In my Yetiforce installation users cannot see any record created by people with lower role. For example an order created by a user with Sales role is not visible by people with top role in the organisation, even if shared with them, and even if the records are not private.

Every user can see only his own records. I'm unable to find the solution in the documentation

Expected Behavior
Top roles should see any record created by lower roles.

Environment
* YetiForceCRM v4.3.0
* Google Chrom v66.0.3359.181
* Shared hosting Linux

Thanks for your help.

**Comment by mariuszkrzaczkowski** [comment]
a similar error has been repaired recently, check gitdev
https://github.com/YetiForceCompany/YetiForceCRM/commit/571af0a954ac29dd565f436b872b27775fabed12

**Comment by antonio-bcn** [comment]
I've tried it, but it didn't fix the issue. The users still see only their own records.

**Comment by KatarzynaUlichnowska** [comment]
@mariuszkrzaczkowski I don't remember if a user couldn't view the records on the list if a module is public. 

@antonio-bcn Can you trigger this bug at https://gitdeveloper.yetiforce.com/ and https://gitstable.yetiforce.com/ That's how we can check the problem.

**Comment by antonio-bcn** [comment]
It shouldn't be a bug. In https://gitstable.yetiforce.com/  I've created, as demo user, a Sale Requirement called "Test sale requirement" and a user with userid testuser with role Board of management. When logged in as testuser I can see the sale requirement created as demo. But in my installation it doesn't work this way and I'm unable to understand why.

Attached you can see my roles. I assume that records created by users woth role Swascan Team should be visible by users with roles Fastweb and Admin. But they are not.
![org](https://user-images.githubusercontent.com/39597902/40920488-02052c2c-680d-11e8-9cd4-8cb300046db8.jpeg)

This one of the Sales Requirements that are not visible as expected. It has been created by the user Vena Simona and it's assigned to the same user that has role Swascan Team, but it's not visible to other users with the same role and to users with higher role.

![sales_requirement](https://user-images.githubusercontent.com/39597902/40921667-67998e0e-6810-11e8-995c-f88962833cf9.jpg)

**Comment by paula-w** [comment]
If you change a module to “private” then all users will only see their own records (it doesn’t matter what their role is). The only exception is the admin user and adding a profile in the “Special access” tab.
If you want someone from a higher role to have access to the records that belong to people in lower roles then you should use  Software configuration > Permissions > Module access > System settings and use the “Advance sharing rules” option.

**Comment by antonio-bcn** [comment]
I didn't set any module as private. And also administrators can only see their own records.
![access](https://user-images.githubusercontent.com/39597902/40963386-a8ba7b3a-68a8-11e8-946e-4e2d2eeabaf6.jpg)

**Comment by KatarzynaUlichnowska** [comment]
Users can view records according to the hierarchy, e.g. users higher in a hierarchy (role) can see records of users who are lower in a hierarchy. There can be many different reasons why it doesn't work, one of them might be a wrong configuration (mysqlnd). 
If you manage to trigger it at GitDeveloper or GitStable and describe what you did, it will be easier for us to investigate the problem. 
If this problem exists only on your server, we can only help you if you buy one of our support packages.

**Comment by ezbank** [comment]
@KatarzynaUlichnowska #6954
