### ISSUE TITLE
Cannot download Impotfix v2 from releases

### ISSUE THREAD

**Issue by tidus1042** [YetiForceCompany/YetiForceCRM#6941]
Hey,

I'm tring to fix my import bug using the ImportFix_unizp_to_root_v2.zip file in the releases.

unfortunately, I can't download it and i saw some fore files has the same problem:

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>28060246/f617d3d0-adbb-11e7-9a8b-024dfee804ac</Key>
<RequestId>13DD08F481CB6F10</RequestId>
<HostId>
0eh6x7XYelG/Wb/4cBGkXl1qcRhC5GZJaEyzX064leX5bVyl88buxjSeX+MvIkMCKfIZ1A61J3E=
</HostId>
</Error>

Can you help me? 
I really appricate it if you wiil fix the link or just upload it somewhere else, it's really urgent.

**Comment by bpabiszczak** [comment]
All you need is here: https://github.com/YetiForceCompany/YetiForceCRM/releases

**Comment by vovpff** [comment]
@bpabiszczak there are no import fix  in list

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6948
