### ISSUE TITLE
Automatic installation of Yetiforce using Softaculous installer on A2hosting result in empty Gantt Chart in project Module

### ISSUE THREAD

**Issue by nidals** [YetiForceCompany/YetiForceCRM#6943]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: IE and Chrome
* Environment name and version:  Automatic install using softacoulas in A2 Hosting 
* Operating System and version:

**Comment by bpabiszczak** [comment]
Please install all patches: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.3.0

**Comment by nidals** [comment]
I tried to install them via the Software configuration > Standard modules > Modules – Installation > System settings.  "Install from file"...... The result was:
"Failed
Module does not contain default language (en_us)."

how to install all patches?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=Module+does+not+contain+default+language

**Comment by vovpff** [comment]
@nidals i think updates and fixes must be installed from updates tab.
