### ISSUE TITLE
[Question] How to add current time on workflow expresions

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#6944]
#### Issue

I would like to update a time field manually in time control module using workflow. When i go to update field in workflow i try to look for some expression of the current time but there is only expression for current date. I've tried with getTime() or Time() but not results

#### Actual Behavior

There is not current time expresion in workflow update field.

#### Expected Behavior

To be able to update a field with current time when workflow is activated manually in a record.

#### How to trigger the error

![gif 2](https://user-images.githubusercontent.com/20831164/40855388-11a3e56c-659a-11e8-907a-ce8a324a2e90.gif)

#### Your Environment

* YetiForce Version used: Stable & DEV
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@aljoflo you can add custom expressions by yourself

**Comment by paula-w** [comment]
It requires some programming work, you can add your own methods in workflow. In the nearest future we are going to rewrite workflow from scratch because the code is very outdated.
