### ISSUE TITLE
[Question] How to add a new field to the Module User

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#6945]
How to add a new field to the Module User (picklist, date, text, number....)
Thanks.

**Comment by bpabiszczak** [comment]
The programmer must use vtlib

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Settings/ModuleManager/models/Module.php#L195

**Comment by ezbank** [comment]
There is a much simpler way. 
http://xyz/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=Users

I do not understand why it is hidden in the layout editor :))
