### ISSUE TITLE
4.4 Release date?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6947]
Hi,

I am "patiently" :O)  waiting for the release of 4.4 update. I am assuming there are some new issues/bugs hense it not being added on 31st as planned?

Any idea when it may become available. Any news would be greatly appreciated.

Kind regards

Chris

**Comment by bpabiszczak** [comment]
2018-06-08 or 2018-06-15
On 2018-06-18 we have conferences.

**Comment by PercyP** [comment]
Thanks for update so it will be on or before 15th June?

**Comment by bpabiszczak** [comment]
"ON"

**Comment by PercyP** [comment]
Ah great. Many thanks for letting us know :O)

**Comment by PercyP** [comment]
I look forward to it. I also appreciate it as Yetiforce is allowing me to start my own little business so thank you :)
