### ISSUE TITLE
[BUG] Permissions | Module access

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#6954]
if this is an bug, it was already exists from the v3.4
Users Guest cannot access Demo's record
![1](https://user-images.githubusercontent.com/19627226/40900409-9fd0ae44-67f5-11e8-8206-d535c4db8e97.png)
![2](https://user-images.githubusercontent.com/19627226/40900412-a00b2dd0-67f5-11e8-8714-339f6e0d0c04.png)
![3](https://user-images.githubusercontent.com/19627226/40900413-a05107ba-67f5-11e8-8c54-64e2d7501a19.png)

#### Your Environment

* YetiForce Version used: gitdev - v3.4 -> v4.3
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6935
