### ISSUE TITLE
[Question] How can I place a read-only field with values from a related module?

### ISSUE THREAD

**Issue by antonio-bcn** [YetiForceCompany/YetiForceCRM#6959]
Hi,

this is my Companies module (the companies are the clients actually). The 1A column contains a client code, while the column 2A contains the company name.
![companies](https://user-images.githubusercontent.com/39597902/40929386-d7309ee2-6824-11e8-8d7b-6ff55761a5d3.jpg)

I've set up a relationship between the Companies module and the Sales Requirements module in order to select the company the sale requirement is related to (field 1B)
![sales](https://user-images.githubusercontent.com/39597902/40929505-33e77f66-6825-11e8-8745-4f7db8abb44b.jpg)

I would like to add a read-only field that would display the client code, coming from the Companies module column 1A, related to the company selected in the field 1B. I've tried by using a custom field with the type "Values from the related module" but it doesn't display anything.

How could I do it? Moreover I would like to use the field in the filter.

I'm using YetiForceCRM v4.3.0.

Thanks.

**Comment by vovpff** [comment]
@antonio-bcn try to understand how this file sectio works https://github.com/YetiForceCompany/YetiForceCRM/blob/e325d8fadc7df0bf90faa14404a28401fb1f3d4d/user_privileges/moduleHierarchy.php#L28
Add new field visible but not editable.
Put new field values to file.
Profit

**Comment by paula-w** [comment]
What you are asking about requires a change in the programming (we have a mechanism that copies these data, but I’m not sure it can be used in this case). We’re planning to add the option to configure these fields (and autofill) directly from the panel in the nearest future.

**Comment by ldgbc** [comment]
@antonio-bcn Hi,

I see that you use a "Client Code" system like I am rather than Yeti-Automate Prefix version (which doesn't allow to make modification to it, that is: change number or reset the number to lower than value).

How are you keeping track of it so (1) it doesn't make duplicate and (2) the number increase by one from the last added. Workflow? Programming?

Thank you.
