### ISSUE TITLE
[bug] Item list changes not triggered as updates

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6965]
#### Issue

I checked what system not trigger item list changes as record update. As example: if invoice (or any advanced module) items changed there is no changes appears at updates tab.

**Comment by KatarzynaUlichnowska** [comment]
Hello, it isn't a bug, the system registers when you e.g. relate an Invoice to an Account, but all changes in an Invoice can be seen in the Invoice's view, not in the Account's view.

**Comment by vovpff** [comment]
@KatarzynaUlichnowska you right but and this is undersandable but this answer not for my question (issue). Maybe there are needed nore detailed explanation of my issue.

For invoices update will be tracked if products has non zero price. In this case tracked Net, Total and Gross:

![image](https://user-images.githubusercontent.com/8545791/41233283-b1f0a89e-6d91-11e8-8c3f-e5dd92f612b1.png)

But for IGDN, IGRN and etc modules this fields (Net, Total and Gross) not available and changes of this modules can't be tracked.

Do you understand what I mean?

**Comment by vovpff** [comment]
@bpabiszczak @paula-w 
Thanks what you found this as bug.

**Comment by ldgbc** [comment]
@vovpff  too bad it 5.0 RC lol

**Comment by vovpff** [comment]
@mariuszkrzaczkowski this issue will be solved for 5.0 RC?

**Comment by vovpff** [comment]
Upd: Can't check on 4.4.46 because after attempt to save IGDN:
```
Notice: Array to string conversion in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yii2/db/ColumnSchema.php on line 157

Warning: Cannot modify header information - headers already sent by (output started at /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yii2/db/ColumnSchema.php:157) in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/actions/Save.php on line 77
```

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/8910
