### ISSUE TITLE
How to add new skin to roundcube?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#6970]
#### Issue

I have tested mail module from YetiForce, a module that have integrated Rouncube. I think current theme is old.

#### Actual Behavior

I know how to add a new theme, but i don't know what changes require for working with yetiforce. I see some custom changes of default roundcube.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Latest version
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by cltvchannel** [comment]
I'm working on a new skin for roundcube.
![template](https://user-images.githubusercontent.com/30116021/41083932-4f103478-6a3b-11e8-92cc-cf28d5f5646d.png)

This is what i have changed for now.

**Comment by PercyP** [comment]
Hi,

I went down the path of purchasing skins for yetiforce from roundcubeskins.net they are beautiful on mobile too. Yetiforce team did some custom work for me to integrate them (required adaption of 2 css files to add the mailbinding). The skins have to be licenced to the server so I believe you can have more than one instance of yetiforce on the server with the skin in each. Reason I bought it rather than try adapting existing one was for the mobile version as the existing one isn't mobile ready - as far as I tested. Maybe it is now?

Your version is already looking more modern - be good to see it when finished :)

**Comment by cltvchannel** [comment]
@PercyP I also see on github that is a desktop notification plugin for roundcube.
I will try to integrate into roundcube, because is more visible if notifications apear directly on desktop.
My theme will be responsive.

**Comment by PercyP** [comment]
That would be good, also regarding the responsive theme. I wonder why roundcube haven't done this already given most people access email via mobile these days

**Comment by ldgbc** [comment]
I can't seem to see any changed (probably need a demo to see compare). But it good to see you are updating it. Hope to see it get share.

In term of roundcube, I suppose you could always do a manual update can't you? I probably be looking to doing that once I used the Mail system more. Currently it still too buggy for my setup.

**Comment by paula-w** [comment]
1. Roundcube is licensed under GPL so we will most likely be replacing it with another mail program, so we’re not sure if it’s really worth it to create new themes for Roundcube.
2. You can compare the original Roundcube files and our files to see what changes we made in Roundcube, it’s all in one folder.
3. A decent programmer should have no problems with implementing a new theme, we generally don’t  help with this type of modifications on GitHub as it unfortunately goes beyond our free support services :(

**Comment by cltvchannel** [comment]
@paula-w Some plans for future to change roundcube with another mail client?

**Comment by ldgbc** [comment]
@paula-w Isn't it good that it is GPL license? Which, "which guarantees end users the freedom to run, study, share and modify the software."

For what reason is being moved away from GPL? 

I assume this change is for v5.0 or 6.0+?

Let hope the new one is more compatible with Yeti then.

**Comment by kamiro16** [comment]
@cltvchannel 
Sorry for the digging up but I have a question for you. How did you change the colors of the upper bar and menu? I would like to develop my style.
