### ISSUE TITLE
Custom Module Idea and Concept (Questions and Discussion)

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#6973]
#### Issue
Currently there is only 1 to 1 relationship. For example, 1 Contact can be linked to 1 Company. But that 1 Company but display all Contact that is linked to the Company.

I'm currently thinking of creating a way to create Multiple Relationship field and a module that can be use for linking relationship on a personal or business level. Be great if someone who have already devise way to do just that can share their input.

#### Actual Behavior
As above.

#### Expected Behavior
Discussion as per below

#### Your Environment
* YetiForce Version used: 3.4
* Browser name and version: Firefox 60
* Environment name and version: XAMPP
* Operating System and version: Windows

### Discussion
Idea one is to create multiple 1:M field in Contact. Then added in an additional Text field to write their relationship.
For example. 

Name: John Smith 
related to: CompanyA (default field)

(custom field)
Name: John Smith 
relation2 to: CompanyB
RelationshipType: Director

Of course with this method it mean that I would like to create many 1:M field if I want to add more than 2.

Second idea: Create a new module for relationship building.
Same idea as the previous one but a Module have almost nothing but many 1:M field and additional Text field for typing.

For example.
Name: John Smith 
Related to: Family ABC 
Relationship: Father

Name: Jane Smith
Related to: Family ABC
Relationship: Mother

Name: Jill Smith
Related: Family ABC
Relationship: Daughter

Then in Family ABC, under Contact it can be setup that link and display as follow

Contacts:
John Smith    Father
Jane Smith     Mother
Jill Smith        Daughter

Of course the weakness to this is (1) new module, (2) relationship are static and not dynamic, for example, John Smith and Jane is husband and wife and it is considered as Mother.

### What situation can this system be used.
1) Relationship between contacts
2) Client Referral Tracking
3) Relevant Contact linking: for example: who this person accountant, who this person doctor, who this person emergency contact, who is this person reference, etc
4) Company linking: currently you can link to 1 Vendor which I usually Branch to Head Office. But this system can link them to their: partnership company, legal representative, accountant, warehouse, etc.

There is a few more concept and idea I want to use it for but until a decent solution can be create I will stop for now. 

@PercyP I remember that you are usually available to provide good feedback. Hope you are around. Thanks.

**Comment by PercyP** [comment]
Hi I needed something like this a number of years ago when I was using vtiger. At first I used a 3rd party module to do this but it no longer worked when I updated. So I created a new module myself called Relationships and added a few fields i.e. Contact 1:M and Companies 1:M and then a picklist with the relationships, and relationship start and end dates then I associated the module to the Contacts and Companies and added a tab to the details page for records. Then I could add multiple relationships for a contact or company. This worked very well for me :O)

**Comment by KatarzynaUlichnowska** [comment]
If you have a few problems or ideas, each of them needs to be added and described separately. 
We don't quite understand what your issue is, so right now we aren't able to help.

**Comment by PercyP** [comment]
Hi, @KatarzynaUlichnowska , @ldgbc 

I provided the solution for @ldgbc in my reply. I created a similar thing many years ago which worked brilliantly. It is simply creating a new custom module call Relationships as I mentioned above :) In vtiger this was harder as had to be done manually via vtlib etc. but in yetiforce it is so simple.

Hope that helps

**Comment by KatarzynaUlichnowska** [comment]
Thank you Percy for your clarification :)

**Comment by ldgbc** [comment]
@KatarzynaUlichnowska I know, I don't expect you to be able to. I'm just waiting for that "overhaul" of 1-to-many-relationship to be possible maybe 1 years (or most likely 5 years) down the line.

@PercyP Thank you. Are you able to show some screenshot of your setup/setting for this purpose? I understand to the create a
1) New Module, 
2) Create bunch of "Related to:" field
3) Create Picklist (or Text) to associated those "Related to" field
4) Show it relation in your main Module (e.g Contacts or Account)

Part 4 is where I'm having trouble with, how do I link those information or "integrate it"? I want it to easily be use to Show those information, rather than it hiding in some "Full Details" or "More > Module" section.

I thinking that I have to create equal amount of "Data from another Field/Module" in the Contact/Account Full Detail page.

Please help! Thanks.

**Comment by PercyP** [comment]
Hi @ldgbc 
If you mean show it in the tabs for a record then go to System Settings - Standard Modules - Module Relations.
Then in top right corner select the module you want to display your new relationship module in, then click the add button and find your Relationship module. In display position leave it as Tabs - you can click in that field to add it to other areas too. Next click in the Standard Fields and select the fields you want to show in your list when it is opened. Finally, move your new relationship to the position you want to display it by dragging it. I think after the 7th position it automatically puts it in the More bit.

Hope that is what you were after
