### ISSUE TITLE
[Question] How to sort records on related modules and widget modules

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#6976]
#### Issue

Is possible to sort the records on a related module and widget module? currently when I sort in a principal module on filters section it works, but when i check the records on a related module or a widget module this is not sorted as the principal

#### Expected Behavior

Be able to sort records on related modules and widget modules for example by dates

#### Your Environment

* YetiForce Version used:4.3 & Dev
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/cd7903f69e36ba150bcce79434ed0fa1270744f0/modules/HelpDesk/HelpDesk.php#L72
https://github.com/YetiForceCompany/YetiForceCRM/blob/cd7903f69e36ba150bcce79434ed0fa1270744f0/modules/Contacts/Contacts.php#L82

**Comment by KatarzynaUlichnowska** [comment]
The examples are above but you need to be careful because sorting significantly reduces performance.
