### ISSUE TITLE
Brak możliwości edycji rekordów [PL]

### ISSUE THREAD

**Issue by jacentys** [YetiForceCompany/YetiForceCRM#6977]
#### Issue

Brak możliwości edycji rekordów w "czystej" instalacji Yetii.

#### Actual Behavior

Po zainstalowaniu Yetii (v4.3) mogę tworzyć oraz usuwać rekordy, ale nie mogę ich edytować.
Obojętnie - czy są to rekordy importowane, czy tworzone od zera.
Widnieję jako właściciel rekordu który chcę edytować.
Jedną z rzeczy która mnie zastanawia jest błąd:
MySQL Native Driver (mysqlnd) - NIE.
provider: progreso.pl

#### Expected Behavior

Edycja rekordu

#### How to trigger the error

1. Instalacja
2. Stworzenie rekordu
3. Błąd.

#### Your Environment

* YetiForce Version used:
ver 4.3.0

* Browser name and version:
Safari 11.1.1, Firefox

* Environment name and version:

* Operating System and version:

**Comment by bpabiszczak** [comment]
mysqlnd musi być zainstalowany

**Comment by jacentys** [comment]
Tzn. jego brak skutkuje takim zachowaniem Yeti?

**Comment by bpabiszczak** [comment]
Tak. W nowej wersji nie będzie wymagany (o ile dobrze pamiętam).

**Comment by jacentys** [comment]
Witam. Rozmawiałem dzisiaj z supportem progreso. Dostałem taką odpowiedź:

Adam Suder | Problem edycji na pewno nie jest związany z MySQLem. Przykładowo można przenieść rekord do archiwum, co jest tak naprawdę modyfikacją rekordu w bazie. Brak przycisków do edycji to problem po stronie samego oprogramowania.
-- | --

**Comment by jacentys** [comment]
Żeby było śmieszniej - zainstalowałem Yeti na komputerze stacjonarnym pod Mamp - ten błąd nie występuje, za to pojawiają się inne (np. Problem z zainstalowaniem biblioteki roudcube oraz PDF).

**Comment by bpabiszczak** [comment]
Bo hosting źle zrozumiał problem, to nie kwestia problemu edycji na bazie danych, lecz np. braku mysqlnd który powoduje problemy w aplikacji. 

Problem możemy zweryfikować my, ale u nas to usługa odpłatna... bo dotyczy w jakimś zakresie problemu na Twoim serwerze.
