### ISSUE TITLE
Mobile site

### ISSUE THREAD

**Issue by elvissaba** [YetiForceCompany/YetiForceCRM#6978]
#### Issue

Details view of any module on mobile not working

#### Actual Behavior

Button Detail view on any module not working. Details tab on any module has bug too
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: chrome
* Environment name and version: Android
* Operating System and version: Android

**Comment by kpaulaha** [comment]
duplicate and fixed #6738

**Comment by elvissaba** [comment]
Is there fix for 4.3 version?

**Comment by KatarzynaUlichnowska** [comment]
The problem is solved in the latest GitDeveloper version. We aren't planning to add a fix to 4.3 version as 4.4 will be soon released.

**Comment by elvissaba** [comment]
4.3 is latest stable release. Can I see at least code change related to issue?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/compare/master...developer

**Comment by elvissaba** [comment]
Can I get more precise? Commit number or code diff?
