### ISSUE TITLE
[Bug] If sum not changed there are update not tracked

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#6991]
#### Issue

First explanation of bug was here #6965 . I found some more buggy thing. If Total, Margin and Gross not changed after edition of item list record update not tracked.

Example:

There are 3 products
- Product A - 100$
- Product B - 50$
- Product C - 50$

If invoice (or etc advanced record) contains products A and B sum will be 150. If somebody replace product B to product C with the same unit price record update will be not tracked by system.

Or product replaced for another one but price corrected to achieve equal total sum.

I think record update for advanced modules should be tracked in any case if product table updated. 

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by adudekyeti** [comment]
Duplicate #6965
