### ISSUE TITLE
Recommend Photo Ratio for Contact

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#6992]
#### Issue
What is the current (v4.3 or v4.4) ratio and resolution for Contact Photo, currently it I'm using a 1:1 ratio and resolution of 208x208. However it have blank space and look a bit deformed on the Header.

#### Actual Behavior
Image look squish

#### Expected Behavior
Contact photo should scale to width/height automatically or a recommend ratio and resolution is added to Manual or Tooltips.
#### How to trigger the error

1. Edit Contact
2. Browse Photo
3. Upload and Save and View.

#### Your Environment

* YetiForce Version used:  4.3
* Browser name and version: Firefox 60
* Environment name and version: XAMPP
* Operating System and version: Windows

**Comment by adudekyeti** [comment]
Hi,
After upload image to contact I checked and the error does not occur.
![6992](https://user-images.githubusercontent.com/39482453/42509262-aac99b0e-844b-11e8-896a-7161f9bb5f9e.png)

**Comment by ldgbc** [comment]
@adudekyeti Thanks! Yes, v4.3 developer seem to fix this issue. It scale properly now. Just need it to be release!
