### ISSUE TITLE
Question: Is it possible to change UI template in Yetiforce

### ISSUE THREAD

**Issue by nzi200779** [YetiForceCompany/YetiForceCRM#6996]
Question:

Im using version 4.3 and want to know if its possible to add or change a template in Yetiforce. Im looking at a complete different look and feel from the current UI (different Menu positions, etc) . I'm hoping theres a way i can buy a template i can buy online and incorporate it with my current Yetiforce solution?

**Comment by paula-w** [comment]
The system is built according to MVC which means the template is separated from the rest of the system and it can be modified in any way you want. Right now we don’t know about any other templates (there used to be 2 other templates but they are not updated, eg. https://github.com/YetiForceCompany/YetiForceScripts/tree/master/DeletedFunctionalAndCode])

Version 4.4 will bring a couple of changes (including a new menu), but  version 5.0 will change a lot as far as modern appearance is concerned.
