### ISSUE TITLE
Generated PDF does not print: Fonts are missing

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#7]
1. Create a PDF document using the OSSPdf module => See File1.pdf
2. PDF displays correctly in Acrobar 10.0
3. Print PDF, e.g. on a Lexmark CN3 PS3 (PostScript driver) printer
4. Fonts are not printing => See File2.pdf (scanned paper output)

See the link for attachments:
http://sourceforge.net/p/yetiforce/tickets/110/

**Comment by bpabiszczak** [comment]
At the moment, we are not going to support PostScript. The community can also make amendments that will add such functionality. We will do it, if a customer asks us to do it commercially. It results from the fact that this problem applies only to a small group of recipients.
