### ISSUE TITLE
[PL] Skaner poczty, pobieranie załączników z wiadomości

### ISSUE THREAD

**Issue by Kulas182** [YetiForceCompany/YetiForceCRM#700]
Witam,
Wydaje mi się, że w systemie jest problem z pobieraniem załączników z wiadomości email do CRM'a. Stworzyłem testowe konto na gmailu i wysłałem na nie 4 wiadomości z załącznikami różnego typu. Były to: zwykły plik tekstowy, dokument WORD, plik EXCEL, czy też dokument PDF.

Konto jest prawidłowo podpięte pod skaner mailowy na waszej testowej wersji (http://test.yetiforce.com) i wiadomości są pobierane, jednak bez załączników? Czy załączniki powinny być pobierane do YetiForce?

![screen1](https://cloud.githubusercontent.com/assets/1971239/7532851/ee5c6e4a-f56b-11e4-95c4-59b0735d46b7.png)
![screen2](https://cloud.githubusercontent.com/assets/1971239/7532853/f1f1804a-f56b-11e4-9f86-aea08bb4de15.png)
![screen3](https://cloud.githubusercontent.com/assets/1971239/7532859/fc9f4db0-f56b-11e4-8081-18e68986ccce.png)

Jak widać w Roundcube te załączniki są w wiadomościach dostępne:
![screen4](https://cloud.githubusercontent.com/assets/1971239/7532866/3af0e9de-f56c-11e4-902f-3541b2daa67c.png)

**Comment by bpabiszczak** [comment]
#Fixed: https://github.com/YetiForceCompany/YetiForceCRM/commit/831eac790af50a12077076cf78d94494c70befec
