### ISSUE TITLE
Project Task and Workflow Automation

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7012]
#### Issue
Many project are duplicated in the nature of what it is required to do. I need to set up automated Task to generate Project Type.

#### Actual Behavior
Can't choose Project Task in Workflow "Add Tasks"

#### Expected Behavior
Can choose Project Task in Workflow just like Adding Event/To Do.

#### How to trigger the error

1. Workflow setting > index.php?module=Workflows&parent=Settings&view=Edit
2. Fill out any detail until Step 3
3. "Add to do"

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Firefox 60
* Environment name and version: XAMPP
* Operating System and version: Windows

**Comment by ldgbc** [comment]
Seem like you can Automated Contact or Account task but not Project for some reason. I wonder if I create the workflow in Contact then go into the Database and convert that to Project will it work?

**Comment by adudekyeti** [comment]
Hi,
This mechanism exist in system.
This is the best way how you can do it:
On Step 3 in "Add task" you have to choice - "Create entity".
Then you can select "Projects" module in row "Modules to create record".
Then you can fill the required fields in modal window:
![7012](https://user-images.githubusercontent.com/39482453/42509020-d824a9b4-844a-11e8-8ff2-b1de6749e00f.png)

**Comment by deepti4666** [comment]
I would like to a list of tasks with milestones for a certain project type, how would I go about doing this?
