### ISSUE TITLE
Relation picklist value is wrong

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#7015]
https://gitstable.yetiforce.com
No any warning or reject any input if the 2 picklist has wrong related
![b1](https://user-images.githubusercontent.com/19627226/41390037-1c4858d0-6fbe-11e8-80b3-437cc74b592d.png)
![bug pl](https://user-images.githubusercontent.com/19627226/41390040-20d1eab0-6fbe-11e8-98ef-0b986e8a7b7a.gif)

**Comment by adudekyeti** [comment]
Hi,
This bug doesn't exist in the newest version of Yetifoce CRM.
![7015](https://user-images.githubusercontent.com/39482453/42570434-298a5dfc-8514-11e8-8157-9e2271b49f07.gif)

**Comment by ezbank** [comment]
it still exists, You should try my way.

**Comment by ezbank** [comment]
A new bug has been generated, when click on field picklist 1, the value of picklist 2 will be removed although values of picklist1 not changed

**Comment by ezbank** [comment]
It does not work correctly with the Module - Widget Type: "Edit selection list"

![1](https://user-images.githubusercontent.com/19627226/43498628-fb0668cc-9571-11e8-8079-376d37fee87c.png)
![2](https://user-images.githubusercontent.com/19627226/43498629-fb4024d6-9571-11e8-9693-75810268c85d.png)
![3](https://user-images.githubusercontent.com/19627226/43498630-fb76bdd4-9571-11e8-8a4f-811902fcff2b.png)
