### ISSUE TITLE
Sharing rules do not update themselves if a new user is added or the user changes roles

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#7016]
v4.3 vgitdev

Sharing rules do not update themselves if a new user is added or the user changes roles
#### Actual Behavior
have rules leads of role sales department can be accessed by User1.
after creating more users2 with role is sales department.
but users1 cannot access lead of users2 if as I don't access to Software configuration> Permissions> Module access> System settings update and update this rule.
#### Expected Behavior
Should have rule autoupdate if changes of user related rule.
![a1223](https://user-images.githubusercontent.com/19627226/41390477-08e1a966-6fc0-11e8-95fa-71e9a01efc78.png)

**Comment by mariuszkrzaczkowski** [comment]
Recalculate is performed on the next call cron
