### ISSUE TITLE
[Question] How to fix Contacts to Account relations

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#7036]
#### Issue

On testing I delete manually trough the relation module the relations in Account to Contacts, when i created again there is not contacts related in the contacts tabs on Accounts.

Do you know please how can this be fixed?

#### Actual Behavior

NO logs showed
#### Expected Behavior

Be abble to see again the contacts tn the Contact Tab on Accounts

#### How to trigger the error

![contact](https://user-images.githubusercontent.com/20831164/41426879-b47a8d24-6fca-11e8-9406-fd840700d3cf.gif)

#### Your Environment

* YetiForce Version used: 4.3 & dev
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@aljoflo you can implement this manually:
1) Go to database
2) Try to find string where string with your recent added relation. Should be at the end of list.
3) Change value in ```name`` column from ```getRelatedList``` to ```getDependentsList```
4) Refresh page in browser

**Comment by aljoflo** [comment]
Thank you @vovpff 
I went to vtiger_relatedlists on the database and changed the relations as you mentioned

**Comment by vovpff** [comment]
@aljoflo you are welcome!
