### ISSUE TITLE
YetiForce RC2 will be released instead of 4.4 GA/RTW

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#7043]
We planned to release YetiForce 4.4 GA/RTW today but unfortunately, it needs to be postponed until the end of June.

Instead of releasing GA/RTW, we will release RC2 today, so please keep testing the system and report any problems you find.

We know you are waiting for the new version, but this week we have been extensively testing the software and we discovered some new issues. Therefore, we decided we can’t release GA/RTW because we need more time. 

Please accept our sincere apologies. We want YetiForce to be a better product with each version, so we hope you will understand our decision. On our side, we promise to do our best to deal with the issues as quickly as we can. We are aware of the fact that there are about two more weeks of hard and intense work ahead of us but after that YetiForce will simply shine.

**Comment by PercyP** [comment]
Ah ... been checking all day. Is there an upgrade version for RC2? Or will that be end of June?
I think we would all prefer a stable release so another 2 weeks will be worth the wait. I just can't progress until its release sadly. 

Thanks for the update and will test the RC2

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases

**Comment by mariuszkrzaczkowski** [comment]
[YetiForce CRM ver. 4.4.0 RC2](https://github.com/YetiForceCompany/YetiForceCRM/releases)

**Comment by PercyP** [comment]
Hi @mariuszkrzaczkowski 

can that be used to upgrade too?

**Comment by bpabiszczak** [comment]
No.

**Comment by ldgbc** [comment]
Any specific reason / issue that caused the delay?

Will a XAMPP be build or upgrade compatible when v4.4 is release or have to wait

PS: How to backup XAMPP install in case my upgrade fail?

**Comment by PercyP** [comment]
@bpabiszczak OK thanks - appreciate the update.  Excited to finally work with the new release :)

**Comment by MacarenaReina** [comment]
Hi,
Will this new version have Reports module or something similar?
Thanks so much!

**Comment by KatarzynaUlichnowska** [comment]
Hello @MacarenaReina, you will find the answer to your question in this issue #6538 
The Reports module won't be back in this version but we have introduced many new charts.
