### ISSUE TITLE
Email configuration problems

### ISSUE THREAD

**Issue by vmalyshev1** [YetiForceCompany/YetiForceCRM#7048]
#### Issue

Email is not working. 

#### Actual Behavior

I get th is error when sending it from Yeti

Checking available databases
Check which of the supported extensions are installed. At least one of them is required.

OK - MySQL 
OK - PostgreSQL 
OK - SQLite 
ERROR - SQLite (v2) | | http://www.php.net/manual/en/ref.pdo-sqlite.php
ERROR - SQL Server (SQLSRV) | | http://www.php.net/manual/en/ref.pdo-sqlsrv.php
OK - SQL Server (DBLIB) 
Check for required 3rd party libs
This also checks if the include path is set correctly.

ERROR - PEAR | Failed to load PEAR.php | http://pear.php.net
ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime
#### Expected Behavior

to work all config data entered
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
google
* Environment name and version:
* Operating System and version:
microsoft

**Comment by vmalyshev1** [comment]
oh  and this error

Web application doesn't work properly
There was some error while running application/script. 
For more information you can look to you error.log in logs folder.

**Comment by vmalyshev1** [comment]
to follow up I have been advised by the hosting company:

You can set in .htaccess file https, header and these php values: max_execution_time, default_socket_timeout, short_open_tag, max_input_vars, session.use_strict_mode. Mysql settings cannot be changed.

So they suggest making changes in htaccess file, which not sure will. What do you think?

**Comment by mariuszkrzaczkowski** [comment]
You did not give enough information about the problem.
Where there is a problem, the lack of screenshots.
Run and check the logs.

**Comment by vmalyshev1** [comment]
![image](https://user-images.githubusercontent.com/39116109/41502343-a141cf9c-71af-11e8-9cd8-7f31f216d04e.png)
![image](https://user-images.githubusercontent.com/39116109/41502345-a806c18e-71af-11e8-9bad-0890f7a7d970.png)
![image](https://user-images.githubusercontent.com/39116109/41502346-ad21fa8a-71af-11e8-9c70-bd60205363ea.png)
![image](https://user-images.githubusercontent.com/39116109/41502347-b29bec28-71af-11e8-8c73-26e2c6b91849.png)

**Comment by vmalyshev1** [comment]
![image](https://user-images.githubusercontent.com/39116109/41502349-c068c934-71af-11e8-9e0c-8026ee3fbfb6.png)

**Comment by vmalyshev1** [comment]
![image](https://user-images.githubusercontent.com/39116109/41502359-ec5ca27c-71af-11e8-866e-6431bce2c375.png)

![image](https://user-images.githubusercontent.com/39116109/41502360-f08272f0-71af-11e8-956f-d298a55a7796.png)

**Comment by vmalyshev1** [comment]
![image](https://user-images.githubusercontent.com/39116109/41502365-22303882-71b0-11e8-92e5-ff4716caaef1.png)

**Comment by vmalyshev1** [comment]
Hello Mariusz


I would appreciate a call about this and other matters. I am now deciding between Yeti and Saleforce and with Yeti being flexible and the fact that its open source, SF seems more user friendly.


You could live me your number and I can ring


Thanks


Vlad


________________________________

**Comment by mariuszkrzaczkowski** [comment]
With little information about the error, we can do nothing without accurate information.
We need full apache, php and crm logs.
First, correct the wrong configuration so that the system is fully compliant with the requirements, without this there will always be some errors.
It is best to write to the server administrator to check what the problem is, he will definitely know what is wrong.

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging

**Comment by vmalyshev1** [comment]
Hi Mariusz


Is this the log you mean?


Checking PHP extensions

The following modules/extensions are required to run Roundcube:

OK - PCRE
OK - DOM
OK - Session
OK - XML
OK - JSON
OK - PDO

The next couple of extensions are optional and recommended to get the best performance:

OK - FileInfo
OK - Libiconv
OK - Multibyte
OK - OpenSSL
OK - Mcrypt
OK - Intl
OK - Exif
Checking available databases

Check which of the supported extensions are installed. At least one of them is required.

OK - MySQL
OK - PostgreSQL
OK - SQLite
ERROR - SQLite (v2) | | http://www.php.net/manual/en/ref.pdo-sqlite.php
ERROR - SQL Server (SQLSRV) | | http://www.php.net/manual/en/ref.pdo-sqlsrv.php
OK - SQL Server (DBLIB)
Check for required 3rd party libs

This also checks if the include path is set correctly.

ERROR - PEAR | Failed to load PEAR.php | http://pear.php.net
ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime
Checking php.ini/.htaccess settings

The following settings are required to run Roundcube:

OK - mbstring.func_overload
OK - suhosin.session.encrypt

The following settings are optional and recommended:

OK - allow_url_fopen
OK - date.timezone


________________________________

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging
full logs which are described here and description of the environment with configuration

**Comment by vmalyshev1** [comment]
Hi Certain settings can not be changed as this is a shared server. Would it be possible to have a look at what exactly needs changing. May be it can be done through .htaccess ?


Also, is it possible to integrate a outbound telephony like skype or similar, which one woudl you suggest?


________________________________

**Comment by mariuszkrzaczkowski** [comment]
Logs???
to know what to change you have to have an error message without it is not known

**Comment by mariuszkrzaczkowski** [comment]
new question new issue

**Comment by vmalyshev1** [comment]
here it is again


Checking PHP extensions

The following modules/extensions are required to run Roundcube:

OK - PCRE
OK - DOM
OK - Session
OK - XML
OK - JSON
OK - PDO

The next couple of extensions are optional and recommended to get the best performance:

OK - FileInfo
OK - Libiconv
OK - Multibyte
OK - OpenSSL
OK - Mcrypt
OK - Intl
OK - Exif
Checking available databases

Check which of the supported extensions are installed. At least one of them is required.

OK - MySQL
OK - PostgreSQL
OK - SQLite
ERROR - SQLite (v2) | | http://www.php.net/manual/en/ref.pdo-sqlite.php
ERROR - SQL Server (SQLSRV) | | http://www.php.net/manual/en/ref.pdo-sqlsrv.php
OK - SQL Server (DBLIB)
Check for required 3rd party libs

This also checks if the include path is set correctly.

ERROR - PEAR | Failed to load PEAR.php | http://pear.php.net
ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime
Checking php.ini/.htaccess settings

The following settings are required to run Roundcube:

OK - mbstring.func_overload
OK - suhosin.session.encrypt

The following settings are optional and recommended:

OK - allow_url_fopen
OK - date.timezone


________________________________

**Comment by mariuszkrzaczkowski** [comment]
these are not logs

**Comment by vmalyshev1** [comment]
Hi, it seems that the problem was that the Roundcube has not been installed. Does it not come with the Yeti package? How can I upload it at the stage when CRM has been installed?

**Comment by vmalyshev1** [comment]
Email has been configured ok, coz I have received this email via Yeti once I have applied changes to configuration


Welcome to platform YetiForce Sp. z o.o.
--
Dear Administrator Administrator,This is a test mail sent to confirm if a mail is actually being sent through the smtp server that you have configured. Feel free to delete this mail. CRM address: http://aleshop.cz/ | Dear Administrator Administrator,This is a test mail sent to confirm if a mail is actually being sent through the smtp server that you have configured. Feel free to delete this mail. CRM address: http://aleshop.cz/
Dear Administrator Administrator,This is a test mail sent to confirm if a mail is actually being sent through the smtp server that you have configured. Feel free to delete this mail. CRM address: http://aleshop.cz/

**Comment by ldgbc** [comment]
You need to install the Roundcube and activate it. I think because the filesize is too large (30MB?) and they don't want to increase Yetiforce size (150MB?)

**Comment by vmalyshev1** [comment]
Hi. Thanks for reply. How do I install it? There is no option to upload it through Yeti. Also, what do you mean they dont want to increase it? You mean server or whom?


________________________________

**Comment by vmalyshev1** [comment]
Ive successfully set up SMPT configs, email configs no errors. 

Whenin my email i get this message 

Web application doesn't work properly
There was some error while running application/script. 
For more information you can look to you error.log in logs folder.

Im absolutely run out of ideas, this is really annoying. What to do?!!!

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/b160aa9172486bcabf092d898f7bfe7b37391f4d/config/debug.php#L70-L71
set true
https://github.com/YetiForceCompany/YetiForceCRM/blob/b160aa9172486bcabf092d898f7bfe7b37391f4d/config/debug.php#L42-L50
set true

**Comment by mariuszkrzaczkowski** [comment]
> Web application doesn't work properly

describe in more detail

**Comment by vmalyshev1** [comment]
I get the message within Yeti, when trying to enable My Mailbox in System settings of Mail scanner.


Hot on earth do you enable roundcube. Can you just write proper instructions? Its been a flipping month and a half now - no progress. Are you having a laugh?


________________________________

**Comment by ldgbc** [comment]
Seem like you already got it to install if you can use those function. As for Filesize I mean Yetiforce's Developer, it they include it by default in their Release.

In here: https://gitstable.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8

Name - Status
roundcube - Downloaded

After that you play with these setting:
 | Software configuration > Mail tools > Mail – Configuration > System settings
 | Software configuration > Mail tools > Mail – RoundCube > System settings
 | Software configuration > Mail tools > Mail –  ............

Try using a GMAIL account as default, see if that work for you before using your (own?) host.
