### ISSUE TITLE
Delete roles / No documentation

### ISSUE THREAD

**Issue by silenthunter206** [YetiForceCompany/YetiForceCRM#7050]
#### Issue

I have just installed yetiforce crm. I am still learning how to to use it. I saw that there is assign role. After creating one, i am unable to delete it. It says "Assign ownership to other role" but the input field is greyed out and i cant type. There is no documentation on how this works. 

I even tried using demo version from this link [https://gitstable.yetiforce.com/](url) but it is still the same. Please update yr documentation / tutorial so its easier for non IT background to understand

![1](https://user-images.githubusercontent.com/34612511/41518418-f5e0f5f0-72f4-11e8-8046-e747ef583368.png)

![2](https://user-images.githubusercontent.com/34612511/41518469-3fad729e-72f5-11e8-9d91-7a2c7bc456e4.png)

**Comment by ldgbc** [comment]
@silenthunter206 documentation won't get update sadly.

Can't help you with that though. Does it have issue with the Developer version too?

**Comment by vovpff** [comment]
@silenthunter206 I'm not sure but there are was fix available for this bug

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/6697
![image](https://user-images.githubusercontent.com/10198654/42515104-4531b8ac-845b-11e8-9886-92f1855fb1c1.png)
