### ISSUE TITLE
Material design skin

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7051]
#### Issue

Now YetiForce is upgraded to Bootstrap 4. Can someone provide me some instructions where i need to change to integrate material design.

#### Actual Behavior

Skin already look better than in the past.
#### Expected Behavior

Bootstrap 4 + Material Design is a great future, of how should look a modern web app.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Gitdeveloper version
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by ldgbc** [comment]
@cltvchannel how can you tell it Bootstrap 4?

**Comment by poradz** [comment]
You can load scripts from this site https://fezvrasta.github.io/bootstrap-material-design/
or from other implementation of material design in bootstrap4, probably you would find some of them also here https://bootswatch.com/

It shouldn't be a problem, but we haven't tested it yet.

**Comment by cltvchannel** [comment]
@ldgbc What you want to say?
