### ISSUE TITLE
Change side menu

### ISSUE THREAD

**Issue by nzi200779** [YetiForceCompany/YetiForceCRM#7052]
HI what settings do I need to change for my side menu to look as the example below

System setting >> Company Information >> Company Details >> Edit
Link: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Vtiger&view=CompanyDetails&block=3&fieldid=14

**Comment by PercyP** [comment]
Hi I think you need to be on their very latest release for this.

**Comment by ldgbc** [comment]
Could try to find where their CSS/HTML setting is and do a manual upgrade I suppose. But just wait.
