### ISSUE TITLE
[PL] Długie ładowanie okna rozpoczęcie instalacji następnie natychmiastowe zakończenie

### ISSUE THREAD

**Issue by simryc** [YetiForceCompany/YetiForceCRM#7054]
#### Issue
W trakcie instalacji https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.4.0_RC_2/YetiForceCRM-4.4.0RC2-complete.zip
okno (wprowadź dane firmy) po kliknięciu w dalej (jak w załączeniu) było około 4-5 minut po czym przeskoczyło na okno z zielonym ładującym paskiem - to okno trwało około 2-3 sekund i instalacja zakończyła się sukcesem (ostatnie okno)

#### How to trigger the error
instalacja na czystym i świeżym ubuntu 18.0.4

#### Your Environment
* YetiForce Version used: 4.3.388
* Browser name and version: Chrome 66.0.3359.181 64bit
* Environment name and version: 
Ubunru 18.04, 
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
apache2 2.4.29-1ubuntu4.1
PHP 7.2.5-0ubuntu0.18.04.1

![bez_reakcji](https://user-images.githubusercontent.com/20447090/41559957-eebd4afc-7345-11e8-80cf-5f891627dabb.png)

**Comment by bpabiszczak** [comment]
Za mało informacji, nic z tym nie da się zrobić.... bez logów nie pchniemy tego dalej.
