### ISSUE TITLE
[PL] problem z pobraniem biblioteki roundcube

### ISSUE THREAD

**Issue by simryc** [YetiForceCompany/YetiForceCRM#7056]
#### Issue
Klikając przycisk pobierz bibliotekę strona się odświeża a biblioteka nie zostaje pobrana.

#### Error log:
w logach apacha pojawia się wpis:
[Mon Jun 18 20:32:06.770937 2018] [php7:warn] [pid 10755] [client XXXXXXXX] PHP Warning:  Header may not contain more than a single header, new line detected in /var/www/html/include/http/Response.php on line 171
[Mon Jun 18 20:35:23.513700 2018] [php7:warn] [pid 10752] [client XXXXXXXX] PHP Warning:  file_get_contents(https://github.com/YetiForceCompany/lib_roundcube/archive/0.0.47.zip): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found\r\n in /var/www/html/modules/Settings/ModuleManager/models/Library.php on line 127

#### How to trigger the error

1. Konfiguracja systemu > Moduły standardowe > Moduły - instalacja > Konfiguracja systemu > pobierz bibliotekę w sekcji roundcube

#### Your Environment
* YetiForce Version used: 4.3.388
* Browser name and version: Chrome 66.0.3359.181 64bit
* Environment name and version: 
Ubunru 18.04, 
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
apache2 2.4.29-1ubuntu4.1
PHP 7.2.5-0ubuntu0.18.04.1

**Comment by mariuszkrzaczkowski** [comment]
Duplikat https://github.com/YetiForceCompany/YetiForceCRM/issues/4434 https://github.com/YetiForceCompany/YetiForceCRM/issues/3884
