### ISSUE TITLE
[PL] Ręczna aktualizacja i wgrywanie poprawek

### ISSUE THREAD

**Issue by miszeli** [YetiForceCompany/YetiForceCRM#7058]
Witam , 
Czy jest możliwość ręcznego wgrywania update systemu i drobnych napraw błędów z paczek zip, gdzie je ewentualnie uploadować ? 
Gdy wgrywam przez panel zawsze występuje błąd za dużego pliku , niestety nie mam możliwości zmiany konfiguracji serwera.

#### How to trigger the error

1. Moduły instalacja - wybierz plik

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Chrome 67.0.3396.87 64-bit
* Environment name and version:  OVH
* Operating System and version: Windows 10

**Comment by bpabiszczak** [comment]
Zrobić update lokalnie za pomocą WAMP lub XAMPP lub zmienić hosting. Nie ma innej opcji.
