### ISSUE TITLE
[bug] workflow

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#7061]
update fields/update related record not opening pop up for adding formula etc. Deleting row not working.

![2018-06-19 18_10_29-workflow system settings](https://user-images.githubusercontent.com/10330264/41606549-943540c4-73ec-11e8-9294-2de361ec65c3.png)

#### Your Environment

* YetiForce Version used: 4.3.388
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by cltvchannel** [comment]
Confirm issue.

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/7077
