### ISSUE TITLE
Default Value on System Field

### ISSUE THREAD

**Issue by lelethered** [YetiForceCompany/YetiForceCRM#7063]
#### Issue
We need to implement a default value on a System Field for a custom module, we read on issue #5648 that this option is under verification or question (i don't understand).
But is present a workaround managed via Workflow or something else for this functionality?

We test in stable version 4.3 and 4.3.3 but is not still present this option, and the system field remain not clickable for default value option

Best regards

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:4.2,4.3,4.33
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by cristyxx** [comment]
@lelethered You can do this only changing on database.
From the panel you can't do this.

**Comment by lelethered** [comment]
Thanks @cristyxx , but It not seems to be the solution. on my db didn't work a predefault value on the column! Other suggestion?
Thank's

**Comment by ldgbc** [comment]
@lelethered seem like it is the only way. I doubt Yetiforce will by default allow you to change it from the Front-End.

**Comment by adudekyeti** [comment]
Hi,
On which module and which system field do you want to have default value?
