### ISSUE TITLE
CUSTOM MODULE:  No "SAVE/CANCEL" buttons when custom module is related, cannot edit records.

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#7064]
Hello !

After creating a basic custom module and making a relation to 'accounts" (for example) after creating some records in it correctly, when trying to edit a record the "SAVE" or "CANCEL" buttons dissapeared. 
Cannot edit fields with pencil neither.
No Permissions has been assignet yet (using it as Admin - SuperUser)

**This happens when Custom Module is related to another**. If the custom module is not related editing works fine

#### Actual Behavior
No SAVE or CANCEL button, and cannot edit with pencil at Custom Relationed Modules records.

![screenshot_3](https://user-images.githubusercontent.com/40429279/41657557-a90b1cf4-748b-11e8-9e05-5943358848aa.jpg)

#### Expected Behavior
Can edit fields normally and save record.

#### How to trigger the error
1. Make a custom module, fill with some basic fields
2. Make relations, in accounts, for example.
3. Fill with some records, normally
4. Try to edit any record. No buttons for SAVE or CANCEL are available below, cannot edit with pencil neither.

#### Your Environment

* YetiForce Version used: YetiForce 4.3 no adittions
* Browser name and version: Chrome, Firefox and Edge last versions tested
* Environment name and version:  PHP 7.0.30
* Operating System and version: Centos OS 7, mariadb, standars installation as specified

**Comment by mariuszkrzaczkowski** [comment]
it means that some error occurred check the PHP and crm logs

**Comment by adudekyeti** [comment]
Hi,
This bug doesn't exist in the newest version of Yetifoce CRM.
