### ISSUE TITLE
Please help! How to add related to custom module in to Calendar

### ISSUE THREAD

**Issue by varlog11** [YetiForceCompany/YetiForceCRM#7067]
How to add related to custom module in to Calendar

![image](https://user-images.githubusercontent.com/1807261/41682121-dc4a1a6e-74e7-11e8-8d8f-24b4fc906867.png)

**Comment by MacarenaReina** [comment]
You must add a new line in "modulesHierarchy" array like this one, but with your custom module name:
https://github.com/YetiForceCompany/YetiForceCRM/blob/50beed79b92c3ed72b001541f94a8871a93a7e94/user_privileges/moduleHierarchy.php#L9

**Comment by varlog11** [comment]
Сool. It works! Thank you!!!
Maybe you know how to add widget Calendar to the list?

![image](https://user-images.githubusercontent.com/1807261/41711311-e5eb4e50-7558-11e8-9f57-28a538242069.png)

**Comment by MacarenaReina** [comment]
If you want to view Calendar on Widgets in Home page
![image](https://user-images.githubusercontent.com/16593721/41715535-aae61676-754b-11e8-8a3e-51acb73fd7dc.png)
You have to add it on Widgets configuration:
![image](https://user-images.githubusercontent.com/16593721/41715621-f2087878-754b-11e8-8533-c3947859a72e.png)
![image](https://user-images.githubusercontent.com/16593721/41715674-1b351b8e-754c-11e8-9e41-b73afeeec5f2.png)

You can also create a widget using a filter you have on Calendar module. This filter must have permissons for use it on widgets:
![image](https://user-images.githubusercontent.com/16593721/41715841-8dc8dd2a-754c-11e8-821a-9b4d996f04a9.png)
![image](https://user-images.githubusercontent.com/16593721/41715902-bb3742e2-754c-11e8-8116-09b45071d38e.png)

**Comment by varlog11** [comment]
Thanks for the help! I mean adding the Calendar widget to a custom module for example as in the  Account or Contact module

![image](https://user-images.githubusercontent.com/1807261/41759237-6f15b0c6-75fe-11e8-8bb1-86737eeceff1.png)
