### ISSUE TITLE
[BUG][4.3.388][Inventory modules] Save inventory data via custom function

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#7070]
#### Issue
I create a workflow on Sales Orders that invokes a custom function.
On my custom function code I want to modify an inventory field value, so I have modified inventory data array, I update it with this line
* `$recordModel->setInventoryData($d['productos']);`

and I save the record with this another line
* `$recordModel->save()`

#### Actual Behavior
It's not modifying the value of the inventory field.
I think that's because save function have theses lines
https://github.com/YetiForceCompany/YetiForceCRM/blob/50beed79b92c3ed72b001541f94a8871a93a7e94/modules/Vtiger/models/Record.php#L427-L429

#### Expected Behavior
Modify the value

#### Your Environment

* YetiForce Version used: Latest version
* Browser name and version: Google Chrome
* Operating System and version: Windows 10

**Comment by mariuszkrzaczkowski** [comment]
this condition is correct. checks if the module is the right type
