### ISSUE TITLE
CGST and IGST TAX

### ISSUE THREAD

**Issue by KrishnaPB** [YetiForceCompany/YetiForceCRM#7080]
Dear Team,

How we can incorporate CGST and IGST tax structure for India in yatiforce. I tried in yatiforce but unable to get it done. Kindly suggest.

**Comment by KrishnaPB** [comment]
Team, Please update on this.

**Comment by ldgbc** [comment]
@KrishnaPB I assume you are using Stable. 
Not sure if this what you looking for:

https://gitstable.yetiforce.com/index.php?module=Inventory&parent=Settings&view=Taxes&block=11&fieldid=90

 | Software configuration > Advanced modules > Taxes – Rates > System settings
