### ISSUE TITLE
Installation problem - Ubuntu 16.04 LTS - not start. crazy result.

### ISSUE THREAD

**Issue by euroonesistemi** [YetiForceCompany/YetiForceCRM#7082]
New installation error not start.
Environmen:

    Ubuntu 16.04 LTS
    PHP 7.0.30 - FCGId (run as virtual server owner)
    Apache/2.4.18
    Versione del client del database: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id:  
    Versione PHP: 7.0.30-0ubuntu0.16.04.1

    PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
    Copyright (c) 1997-2017 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

    Server: Localhost via UNIX socket
    Tipo di server: MySQL
    Connessione Server: SSL inattivo Documentazione
    Versione del server: 5.7.22-0ubuntu0.16.04.1 - (Ubuntu)
    Codifica caratteri del server: UTF-8 Unicode (utf8)

   Browser all version

 * Operating System and version:
 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

After unzip YetiForceCRM-4.3.0-complete.zip in /home/yeti/public_html/
anc have set up correct perimission owenr an group, installation non start.

I don't understand what is possible problem.

I test with Vtiger in same directory and work fine. ( installation start )
i attach output result.
![firefox_screenshot_2018-06-22t13-43-26 333z](https://user-images.githubusercontent.com/1251660/41780776-f94a8ba4-7635-11e8-8c7d-68075fa7f2f5.png)

I haven't finded information around.
Best Regards.

**Comment by euroonesistemi** [comment]
https://yeti.euroonesistemi.com for testing problems.

https://yeti.euroonesistemi.com/mytest.php for tect configuration.

**Comment by SkavenKF** [comment]
version 4.4 is compatible with PHP 7.1 and 7.2.
version 7.0 and lower will not work because some libraries no longer support these versions

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/41800850-a75cedc2-7677-11e8-90c6-ffd3728723e5.png)
You have a problem with the Apache configuration, check the logs

**Comment by euroonesistemi** [comment]
TNKS a LOT.

**Comment by euroonesistemi** [comment]
Last YetiForce version compatible with 7.0 ?

**Comment by bpabiszczak** [comment]
7.1
