### ISSUE TITLE
Workflow task: Sum filed values from related module fields  [NOT WORKING]

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7086]
#### Issue

I have tried to add a workflow task to sum values from Payments In module and show on Accounts Value field.
![payments work](https://user-images.githubusercontent.com/30116021/41821095-3f6d937e-77e4-11e8-91ca-e94eb891a4d1.png)

#### Actual Behavior

When add payment get next error:
![workflow sum](https://user-images.githubusercontent.com/30116021/41821089-1b7eebde-77e4-11e8-9c72-13957568e661.png)
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Gitdeveloper.yetiforce.com
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by cltvchannel** [comment]
Also i have a question:
This task work for sum fields from any modules?

**Comment by mariuszkrzaczkowski** [comment]
Yes
