### ISSUE TITLE
[BUG][4.3.390][Mobile menu] Not showing left side menu on mobile phone

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#7091]
#### Issue
If I want to see left side menu on mobile phone (iPhone 6), I click on the button but it doesn't do anything.
![screenshot_7](https://user-images.githubusercontent.com/16593721/41895972-51c748b6-791b-11e8-8827-805b76c69733.png)

#### Actual Behavior
Doesn't show the menu.

#### Expected Behavior
Show the menu.

#### Your Environment
* YetiForce Version used: Latest version (4.3.390)
* Browser name and version: Safari 
* Operating System and version: iOS

**Comment by cltvchannel** [comment]
Confirm not working on Iphone 7-8-X.

**Comment by poradz** [comment]
The previous commit caused bugs on other platforms than ios, here is the final version:
https://github.com/YetiForceCompany/YetiForceCRM/pull/7135/commits/a7552e7159a57f4a20e1d719460f40470844221b
