### ISSUE TITLE
[PL] Edycja Leada

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#7095]
* YetiForce Version used: 4.3
* Browser name and version: Chrome Wersja 67.0.3396.87
Apache Version | 2.4.33
PHP Version | 7.1.17
MySQL Version | 5.6.39
Operating System | linux

Witam.

Próbuje edytować już stworzonego leada ale nie ma żadnej opcji do tego przeglądałem to forum.
Znalazłem post:
https://github.com/YetiForceCompany/YetiForceCRM/issues/6561

Wykonałem wszystko co było opisane bez efektów.

-- | --

-- | --

-- | --

**Comment by mariuszkrzaczkowski** [comment]
Logi..

**Comment by bpabiszczak** [comment]
Wszystko czyli co? W większości przypadków problem jest w braku mysqlnd [czyli niepoprawna konfiguracja serwera]. Proszę również przesłać pełne logi na logs@yetiforce.com wówczas zobaczymy, czy coś można tam znaleźć, przez pełne logi mam na myśli apache, php, mysql, yetiforce.

**Comment by mskoczek** [comment]
Przepraszam za swój brak wiedzy. Czy mogli byście mnie trochę pokierować co gdzie znajdę? Wiem że to brzmi trochę nie profesjonalnie ale nigdy tego wcześniej nie robiłem a zależy mi a by yetiforce poprawnie działał.

**Comment by bpabiszczak** [comment]
a kto administruje tym serwerem? Macie dostęp do root czy tylko panel w hostingu?

**Comment by mskoczek** [comment]
Jest to hosting. Poprosiłem ich o pełne logi z apache,mysql i php

**Comment by bpabiszczak** [comment]
ale takie proszenie nic pewnie nie da, bo to muszą być logi z momentu problemu a nie wszystkie, bo trudno będzie wyłapać problem [np. osoba po stronie CRM wywołuje problem po stronie interfejsu a admin zbiera wówczas szczegółowe logi].

Co to za hosting?

Nie odpowiedziałeś na pytanie co do mysqlnd czy jest włączone czy nie.

**Comment by mskoczek** [comment]
![bez tytulu](https://user-images.githubusercontent.com/40525437/41967393-cd125c68-7a01-11e8-84e7-a4dd7218dc32.jpg)
To są ustawienia

**Comment by bpabiszczak** [comment]
który pakiet został wybrany [tak z ciekawości, czy coś oprócz YetiForce tam jest?].

**Comment by bpabiszczak** [comment]
Proszę zobaczyć, że jest tam mysqlnd wyłączone [opcje nd_pdo_mysql chyba trzeba wyłączyć, ale tego nie jestem pewien].

**Comment by mskoczek** [comment]
Mam https://www.unlimitedwebhosting.co.uk/web-hosting mam go już lata i nigdy nie było z nim problemu. Na tym serwerze mam jeszcze 3 strony www

**Comment by bpabiszczak** [comment]
Po drugie na początku posta pisze Pan o 7.1 PHP a na screenie widać konfiguracje dla 7.0.

**Comment by mskoczek** [comment]
Słuszna uwaga zw
![bez tytulu2](https://user-images.githubusercontent.com/40525437/41967983-5cc2674e-7a03-11e8-897b-6bfdeac9837b.jpg)

**Comment by bpabiszczak** [comment]
proszę zmienić na domyślny szablon graficzny [Twilight], bo tej nie supportujemy. 
Czy wgrał Pan wszystkie łatki dostepne do wgrania?

**Comment by mskoczek** [comment]
Już zmieniam i tak wgrałem wszystko

**Comment by bpabiszczak** [comment]
nadal nie działa edycja? Jeżeli tak, to proszę przesłać na SLA@yetiforce.com dostęp do CRM-a [administrator yetiforce, ftp i mysql] a my sprawdzimy co jest nie tak.

**Comment by bpabiszczak** [comment]
dane dostępowe weźmiemy sobie z pliku konfiguracyjnego, hosting powinien mieć link pod którym można logować się np. do phpmyadmin lub innego webowego edytora sql.

**Comment by mskoczek** [comment]
Ok wszystko wysłałem proszę o potwierdzenie odbioru i poprawność hasła

**Comment by bpabiszczak** [comment]
Jutro sprawdzimy.

**Comment by mskoczek** [comment]
Bardzo dziękuje.

**Comment by bpabiszczak** [comment]
a więc:

1. Serwer do wymiany bo działa bardzo wolno.
2. Limity w Apache/PHP są do korekty, ponieważ serwer "przerywa" działanie CRM ponieważ system osiąga limity czasowe dla skryptów.

Należy spytać administratora hostingu, dlaczego system ma problem:

[Mon Jun 18 13:22:40.983806 2018] [core:error] [pid 586412:tid 140454901286656] [client 193.164.255.85:63095] Script timed out before returning headers: index.php, referer: https://biuro.mskoczek.co.uk/index.php?module=Users&action=EditView&record=1
[Tue Jun 19 12:09:21.562496 2018] [hostinglimits:error] [pid 760926:tid 140454792181504] mod_hostinglimits: Error on LVE enter: LVE(1016) HANDLER(application/x-httpd-ea-php71) HOSTNAME(biuro.mskoczek.co.uk) URL(/index.php) TID(760978) errno (7) Read more: http://e.cloudlinux.com/MHL-E2BIG min_uid (1000)

**Comment by bpabiszczak** [comment]
Ogólnie problem leży po stronie hostingu [ograniczenia], nie mamy tutaj jak Tobie pomóc.

**Comment by mskoczek** [comment]
A jak zmienic te limity ? 

:-)

**Comment by bpabiszczak** [comment]
To wie tylko administrator hostingu, on musi powiedzieć, które limity zostały przekroczone i podpowiedzieć jak je zmienić [o ile można je zmienić]. Masz bardzo tani hosting, a więc ja bym nie wymagał od niego zbyt wiele :] 

My udostępniając chmurę dla YetiForce która jest dostępna w sklepie [https://yetiforce.shop/index.php?option=com_djcatalog2&view=item&id=42:private-cloud-1&cid=12:private-cloud&Itemid=1071](url) skonfigurowaliśmy wszystkie parametry optymalnie właśnie pod tą aplikacje, a hostingi robią parametry tak, aby przypadkiem nie obciążyć serwera bo jest na nim 200 innych klientów.

**Comment by mskoczek** [comment]
A mogl byś polecic hosting ?

:-)

**Comment by bpabiszczak** [comment]
Ogólnie nie polecamy już hostingów.... bo mają zbyt wiele ograniczeń. Obecnie mogę polecić VPS-y, gdzie użytkownik ma pełną kontrolę nad każdym parametrem i tak jak wcześniej mówiłem, mogę polecić również naszego VPS w chmurze, ale cena zaczyna się od 290 zł brutto miesięcznie [w zamian użytkownik otrzymuje wsparcie, wydajność, wysokim poziom bezpieczeństwa, szybki czas reakcji] i dużo miejsca na dane:

The Private Cloud 1 plan includes the following drives:
Drive I : 10GB Intel® Optane™ NVMe interface – to store the production version’s SQL database
Drive II : 100GB SSD - to store the operating system and test versions’ SQL databases
Drive III : 250 GB secure SAS disk array - extra space for other files like attachments or documents

**Comment by bpabiszczak** [comment]
Tutaj są OVH VPS jeżeli ktoś szuka czegoś tańszego niż to co my oferujemy: https://www.ovh.pl/vps/vps-cloud.xml ale do tego należy doliczyć administratora, który będzie tym zarządzał i wsparcie techniczne dla systemu YetiForce i dodatkowo gdzieś trzeba magazynować kopię zapasowe....

**Comment by mskoczek** [comment]
Czy jesteś mi wstanie powiedzieć czy te ustawienia dały by rade pociągnąć
Yeti ?
VPS Cloud 2
KVM OpenStack
SLA 99,99 %
2 vCore(s)
3,1 GHz
4 GB RAM
50 GB
High Availability (Ceph)


pt., 29 cze 2018 o 23:03 Błażej Pabiszczak <notifications@github.com>
napisał(a):

**Comment by bpabiszczak** [comment]
A na ilu użytkowników i co będą robić w systemie [aby mieć pewność, należy zrobić testy wydajności]. Sądzę, że spokojnie dla 10-20 użytkowników serwer da radę.  Trochę mało przestrzeni dyskowej, ale jeżeli ktoś nie używa skanera mailowego i nie podpina dużych plików, to powinno wystarczyć.

**Comment by mskoczek** [comment]
2 do 6 użytkowników maks.

pon., 2 lip 2018 o 11:54 Błażej Pabiszczak <notifications@github.com>
napisał(a):
