### ISSUE TITLE
Question - Copy User

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#71]
Where can i found the function for copy a user?

**Comment by mariuszkrzaczkowski** [comment]
![duplicate](https://cloud.githubusercontent.com/assets/10198654/5999745/358535b8-aad5-11e4-9c99-fda65bff4632.png)

**Comment by mariuszkrzaczkowski** [comment]
The possibility to duplicate users was removed in Vtiger 6.0, we added it in 1.3.x version. The option for duplication will be available on the list of users, as it is shown on the screenshot above
