### ISSUE TITLE
Reports module

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7105]
#### Issue

I want to know if it's planned to release a new report module in one of the next versions?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by ldgbc** [comment]
@PercyP lol "Coming out today".

I didn't get to use the Report module but supposedly the Gantt Chart will replace it until Report v2.0 come out. Then we will have Gantt Chart + Report 2.0.

You may want to stick with v4.3 if you want that. It might be v5.0 before Report come back.
