### ISSUE TITLE
Filter - Max Columns 12 

### ISSUE THREAD

**Issue by fricgabriel** [YetiForceCompany/YetiForceCRM#7124]
Hello, 

How to modify "max Columns 12" ?

![image](https://user-images.githubusercontent.com/39228143/42136313-4813bc38-7d2f-11e8-831c-b99cf8fcecc3.png)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/2ab09cec4fce4553d6bc881a473ae4e12e042275/public_html/layouts/basic/modules/CustomView/resources/CustomView.js#L113

**Comment by ezbank** [comment]
Many thanks
