### ISSUE TITLE
Rekord przeniesiony do archiwum - gdzie go znaleźć

### ISSUE THREAD

**Issue by chrisdebuud** [YetiForceCompany/YetiForceCRM#7130]
#### Issue

Po kliknięciu "Archiwizuj" rekord staje się niemożliwy do wyszukania
#### Expected Behavior

W wyszukiwarce/filtrach możliwość wyszukania zarchiwizowanych elementów lub osobny magiczny przycisk z dostępem do nich.

**Comment by areksolek** [comment]
Proszę postępować zgodnie ze wskazówką
![archiwum](https://user-images.githubusercontent.com/25615135/42225222-4b88bcd4-7edc-11e8-805c-061089ab931b.gif)

**Comment by chrisdebuud** [comment]
Pięknie dziękuję.
