### ISSUE TITLE
PERMISSIONS

### ISSUE THREAD

**Issue by sergiohacks3** [YetiForceCompany/YetiForceCRM#7142]
someone knows how to do or set permissions for modules for example in the contacts module, when you create a contact with a user only appears to him and not others ??

**Comment by sergiohacks3** [comment]
He tried everything ... and I can not do it ..

**Comment by ldgbc** [comment]
Yes, that the simple using the "Hierarchy" or Group/Organization structure and the User account setting permission.

I think in most case you want to use the Organization structure. For example, 

Manager
 >>Admin
 >>>> Low Level Admin

Manager can see everyone below him.
Admin can't see what Manager create. If you allow it, Admin can see Low Level.
Low Level can only see them self or you can set it, Low Level can see all other Low Level.
