### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by sergiohacks3** [YetiForceCompany/YetiForceCRM#7143]
does not the contact module to establish ??

http://prntscr.com/k2jllz

**Comment by sergiohacks3** [comment]
In these panels ... in Vtiger Crm .. the Contacts panel .. I had it in private in the users only in reading and writing .. here is the same panel but the Contacts section is missing to introduce that .. such and like this example ..:

https://prnt.sc/k2mpkq

Where is the Contacts module ?? .. so I did it in vtiger crm and it worked perfect, or how could I do it? What I want is the following:

I want that when creating a Contact only when creating it, only the Contact that is assigned to it sees it, I also want it to be seen by a team leader or someone more superior to him .. but only that person .. the other departments do not....

**Comment by sergiohacks3** [comment]
I want to buy several extensions of your store .. but first I want to make this work ..

**Comment by bpabiszczak** [comment]
Accounts and Contacts - they are connected

![image](https://user-images.githubusercontent.com/10197525/42294883-3383bb52-7fe5-11e8-90e7-33d546410c7d.png)

**Comment by sergiohacks3** [comment]
Can hide the module ?? or that is not shown in the menu of all users ??, nose to work ..

**Comment by bpabiszczak** [comment]
here: https://gitstable.yetiforce.com/index.php?module=Menu&view=Index&parent=Settings&block=2&fieldid=40

**Comment by sergiohacks3** [comment]
I can not find the way to do it ... what I explain to you ... When creating a Contact, it does not show them to other users ..

**Comment by bpabiszczak** [comment]
one question = one issue

**Comment by sergiohacks3** [comment]
I just want this ..

Example:

User 1 Create Contact1

User2 In your panel shows you Contact1

User 2 Create Contact

User 1 Do not see User Contacts 2

**Comment by sergiohacks3** [comment]
sorry for so much discomfort ... I am very happy with YetiForce .. I think I know what happens ... I can access the registry but in the Contacts list it does not show it .. I put the url in the contact's browser and I can edit it and see it and others, but in the list it does not show me .. ??
