### ISSUE TITLE
problem with hierarchy records with permissions ..

### ISSUE THREAD

**Issue by sergiohacks3** [YetiForceCompany/YetiForceCRM#7147]
I can not make the records show for some users or even for admins .. only shows its own record of its own user .. I have all the permissions .. I have tried everything .. with any module .. not what I've got ??

**Comment by ldgbc** [comment]
Is it Private? I think even Admin can't see private or something. Need step to reproduce this, can't to see at the moment.

**Comment by adudekyeti** [comment]
Hi,
Please give me more information how you add a new record, what account do you use, in which module did you do that.

**Comment by mariuszkrzaczkowski** [comment]
Close because insufficient information to diagnose the problem
