### ISSUE TITLE
[PL] Połączenie modułu Księgowego z magazynem

### ISSUE THREAD

**Issue by FeniksPC** [YetiForceCompany/YetiForceCRM#7150]
Issue
Wszelkie operacje wykonywane w module księgowym nie mają odzwierciedlenia w części magazynowej.

Actual Behavior
Wystawianie faktur czy faktur kosztowych nie generuje ruchu PZ/WZ na poziomie magazynu.

Expected Behavior
Przy wystawianiu faktury sprzedażowej na produkt, mile by była widziana opcja wybrania magazynu z którego dany produkt ma zostać odjęty. W momencie kiedy stan magazynowy jest = 0, informacja zwrotna, że danego produktu nie ma na magazynie. Aktualnie po wystawieniu faktury na produkt, który znajduje się na magazynie i ma stan dodatni, nie powstaje dokument WZ, który automatycznie zmieniałby stan magazynowy produktu.

* YetiForce Version used:
* Environment name and version: 4.4

Próbowałem powiązać moduły z pomocą Mapowania ale chyba przerasta mnie to zadanie. Czy aktualnie jest możliwość połączenia z sobą tych dwóch kwestii czyli faktur i magazynu?

**Comment by bpabiszczak** [comment]
Nie generuje, ponieważ firma sama może zdecydować, kiedy dokumenty i jakie się generują [czy magazynowe z księgowych czy księgowe z magazynowych].

Jednocześnie automatyzacja i raportowanie dla tych modułów nie zostały zrobione [czekają na pierwszego dużego klienta] a jak to już się stanie, wówczas system będzie można nazywać małym ERP :P Tak więc to jeszcze przed nami. 

To na pewno wymaga porządnego przetestowania i odrobiny automatyzacji, ale i tak wyjdzie taniej niż licencje na niejeden ERP.

**Comment by FeniksPC** [comment]
W którym miejscu tego szukać? Bo walczę z tym od wczoraj... Wyzwalacze> AUtomatyzacja czy raczej moduły powiązane?

**Comment by bpabiszczak** [comment]
To trzeba oprogramować, bo przecież nie są to dokumenty 1:1 [na magazynie nie mamy usług, podatków itd.].
