### ISSUE TITLE
Announcements cannot close after "mark as read" or "remind me later" 

### ISSUE THREAD

**Issue by Tingfe** [YetiForceCompany/YetiForceCRM#7157]
Announcements cannot close after "mark as read" or "remind me later" ​​​​​​​<br><hr>Generated by YetiforceCRM ver. 4.3.388<br>PHP: 7.2.4<br><br><strong>Server configuration errors:</strong><br>date.timezone: Invalid time zone:Asia<br><strong>Library errors:</strong><br>ldap_connect

**Comment by ldgbc** [comment]
Can't help you there @Tingfe  but your post look interesting. Are you posting these directly from your Yetiforce installation?
