### ISSUE TITLE
notification "title"and "contents " at the same row

### ISSUE THREAD

**Issue by Tingfe** [YetiForceCompany/YetiForceCRM#7158]
notification "title"and "contents " at the same row​​​​​​​<br><hr>Generated by YetiforceCRM ver. 4.3.388<br>PHP: 7.2.4<br><br><strong>Server configuration errors:</strong><br>date.timezone: Invalid time zone:Asia<br><strong>Library errors:</strong><br>ldap_connect

**Comment by adudekyeti** [comment]
#7209 Fixed
