### ISSUE TITLE
Popup Selection Search Magnifying Glass Column List [Question]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7160]
#### Issue
Can't find the setting to make this edit, need some pointer.

#### How to trigger the error
Use the Stable version 4.3, use this link: https://gitstable.yetiforce.com/index.php?module=Contacts&view=Edit&record=114

Next to "Member of", click the Magnifying (Search) Button. it Between the X and +.

Look at the popup (which is this one here: https://gitstable.yetiforce.com/index.php?module=Accounts&src_module=Contacts&src_field=parent_id&src_record=114&view=Popup&triggerEventName=postSelection3018

How do I change those column? For example from VAT column to Phone Number, etc. Where is the setting to edit these?

#### Your Environment
* YetiForce Version used: 4.3
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by cltvchannel** [comment]
Hi @ldgbc You can change columns here: https://github.com/YetiForceCompany/YetiForceCRM/blob/b13d9a861cb8fecdf9bc1747ca61053c95df9079/modules/Accounts/Accounts.php#L38

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/42824426-1dc4dc4c-89e0-11e8-80e5-3382f48d55a7.png)

**Comment by ldgbc** [comment]
Look like word is better to demostrate
@mariuszkrzaczkowski 

![issue 7160-pic 3](https://user-images.githubusercontent.com/1805303/42921195-e98bbebc-8b5d-11e8-8151-be624d489841.png)

**Comment by ldgbc** [comment]
I guess no GUI yet then. Editing it is.

**Comment by ldgbc** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/5505
