### ISSUE TITLE
[PL] CRON nie odpala

### ISSUE THREAD

**Issue by FeniksPC** [YetiForceCompany/YetiForceCRM#7163]
Prześledziłem wcześniejsze tematy związane z CRONem i niestety nie znalazłem rozwiązania problemu.

Mianowicie wszelkie zadanie w CRONie nie startują.  Wywołanie vtigercron.sh z poziomu konsoli wyrzuca błedy. Zawartość vtigercron.sh
export VTIGERCRM_ROOTDIR=`dirname "$0"`/..
export USE_PHP=php
#export USE_PHP=/usr/local/php53/bin/php
#export USE_PHP=/usr/local/php56/bin/php56

cd $VTIGERCRM_ROOTDIR
# TO RUN ALL CORN JOBS
$USE_PHP -f cron/vtigercron.php

Konsola:
sh /var/www/html/YetiForce/cron/vtigercron.sh
/var/www/html/YetiForce/cron/vtigercron.sh: 10: /var/www/html/YetiForce/cron/vti: not found 
/var/www/html/YetiForce/cron/vtigercron.sh: 15: /var/www/html/YetiForce/cron/vti: not found 
/var/www/html/YetiForce/cron/vtigercron.sh: 16: cd: can't cd to /var/www/html/YetiForce/cron/..
/var/www/html/YetiForce/cron/vtigercron.sh: 18: /var/www/html/YetiForce/cron/vti: not found /usr/share/php

Wersja PHP i wymagania serwerowe są ok. 
Gdzie popełniam błąd?

**Comment by mariuszkrzaczkowski** [comment]
TO jest problem z kodowaniem pliku powinno być UNIX
