### ISSUE TITLE
Install classic vTiger extension module [ Question ]

### ISSUE THREAD

**Issue by ovidiubularda** [YetiForceCompany/YetiForceCRM#7166]
Hi guys, 

The extension module functionality is it still there, like in vTiger ?

For example:
http://community.vtiger.com/help/vtigercrm/developers/extensions/examples/hello-world-v1.html
The system seems to recognize it but I cannot configure it to appear in the left menu bar.

**Comment by ldgbc** [comment]
Usually these extension or plugin rely on a language call API. I don't think Yetiforce have those yet so it be quite a while before you get it to work.

From my understanding some vTiger extension change the system itself rather than going through API request.
