### ISSUE TITLE
How to: Have different ListView and DetailView files for each module?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7167]
#### Issue

I want to make some changes on ListView and DetailView files for each module. I need to show different layouts.

#### Actual Behavior

I don't know where to change to use different .tpl file .
#### Expected Behavior

A way to complete issue.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
here's an example
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/layouts/basic/modules/Events

**Comment by ldgbc** [comment]
@cltvchannel Please share your update. Maybe even pull request it?

**Comment by cltvchannel** [comment]
@ldgbc I'm working on this.
Here it's a starting concept for DetailView look.
![detailview concept](https://user-images.githubusercontent.com/30116021/42674422-58b913a6-8678-11e8-9e03-4d7f3cddfc74.png)
