### ISSUE TITLE
Document Internal Browser View [Question]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7179]
#### Issue
Can't view Documents/File internal (support extension) in-line or new tab within the browser rather than downloading.

#### Actual Behavior
Save As option popup when you open file.

#### Expected Behavior
Support file (image, PDF, maybe .txt) should be allow to open or view internal within the Web Browser.

#### How to trigger the error
1. Open a document using the "File/www"
2. Open to Save File will be offered.
3. Then you can either save or (download in temp) and open the file.

What I want to ask if I can change the server setting (or is this Browser setting?) to open certain file internally within my Web Browser. For example, my web browser (Chrome and Firefox) can view PDF file, which is good enough for me in most case as my document are scanned as PDF. Same with PNG or JPG image.

On a related topic, is there any plugin, extension that I can install on my webserver or link Yetiforce to open other common document files in-line or view-in-new-tab? In-line is it will view within Yetiforce force using an iframe or something without having to use external Software or in new tab. 
View-in-new-tab, mean you have to change tab to view it but at least it is support natively without the need to open it in a separated Software.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Firefox
* Environment name and version: XAMPP
* Operating System and version: Windows

**Comment by cltvchannel** [comment]
@ldgbc  You can make some changes here and it will work.
For me worked.

https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/modules/Documents/models/Record.php

**Comment by ldgbc** [comment]
@cltvchannel Thanks. But can you advise me on what change I need to make?

Would you know if make this changed stop me from using "Right Click > Save As"?

**Comment by cltvchannel** [comment]
@ldgbc You can see an example here:
https://discussions.vtiger.com/discussion/185573/resolved-documents-module-open-pdf-files-in-a-new-tab

This change not stop you using Right Click.

**Comment by ldgbc** [comment]
@cltvchannel Thanks! Going to close this and try it later.

Hmm considering you reference the VTiger, I guess if I read through the vTiger forum there should be quite many interesting thing I can do with YetiForce. Assuming of course that it still using vTiger module.

**Comment by cltvchannel** [comment]
You can specify what types of extensions open in browser. You need small changes of code.

**Comment by vovpff** [comment]
@cltvchannel could you please provide info what changes needed?

**Comment by cltvchannel** [comment]
See this link:
https://stackoverflow.com/questions/6293893/how-do-i-force-files-to-open-in-the-browser-instead-of-downloading-pdf

**Comment by ldgbc** [comment]
@vovpff After my failure I tried to find alternative. Manage to come across this: https://addons.mozilla.org/en-US/firefox/addon/open-in-browser/?src=search
I'm going to use this instead until I learn more on what to do, probably this is no longer an issue thanks to that Add-on. Of course the weakness is you have to use Firefox, then again it is a Web-extension so it might work or easy to port over to somewhere else like Chrome. Chrome might already have their own version.

@cltvchannel Yeah I tried searching more information and came acrossed that. Fixed to add those into htacess and MIME but it was too hard for me. The instruction provided didn't baby step me, jump straight into, "I expect you to know this."

Anyway, that 1 more issue solved, closing this again.
