### ISSUE TITLE
Can't stay logged in

### ISSUE THREAD

**Issue by chazkame** [YetiForceCompany/YetiForceCRM#7180]
#### Issue

I've juste finished installing YetiForce to try. I logged in using admin account, but whenever I clicked to any link, it brings me to the login page. I can't even start doing the configuration yet.

Kindly tell me what should I do please.

Thank you

#### Your Environment

* YetiForce Version used: 4.3.

**Comment by ldgbc** [comment]
Sound like a Cookies problem. Use another browser?

Else it would be a installation problem, which I have previously because my host don't support Yetiforce newer version and it was missing function for it to keep working.

You install it on your host? or Local?

**Comment by bpabiszczak** [comment]
Most likely, the system can not change session id [try to disable this parameter: https://github.com/YetiForceCompany/YetiForceCRM/blob/ae26ac0e7dd1d161f0b80826652e969c405ef861/config/config.template.php#L161]

or 

check if you have the correct parameter https://github.com/YetiForceCompany/YetiForceCRM/blob/ae26ac0e7dd1d161f0b80826652e969c405ef861/config/config.template.php#L53

**Comment by chazkame** [comment]
Hi,

I'm sorry for the late reply. 
@bpabiszczak I modified $session_regenerate_id = false; but it still doesn't work.
I've tried using other browsers too : Mozilla, IE, Chrome, Safari. Same problem. I've installed Yeti 4.3.0 on a linux vps using the softaculous. 

Any help is very much appreciated.

Thanks

**Comment by mariuszkrzaczkowski** [comment]
check the lifetime of sessions and cookies
