### ISSUE TITLE
Incorrect request

### ISSUE THREAD

**Issue by abelramosc** [YetiForceCompany/YetiForceCRM#7181]
I'm getting this message when adding a new user after a fresh install.I didn't set spanish configuration anywhere.​​​​​​​Thanks!Incorrect requestIllegal value in field language (es)Generated by YetiforceCRM ver. 4.3.0PHP: 7.0.30Server configuration errors:output_buffering: 4096max_execution_time: 30max_input_time: -1default_socket_timeout: 60post_max_size: 8.00 MBupload_max_filesize: 2.00 MBmax_input_vars: 1000innodb_lock_wait_timeout: 50Library errors:opcache_get_configurationapcu

**Comment by mariuszkrzaczkowski** [comment]
The minimum php version is 7.1.x
