### ISSUE TITLE
[PL] [Sugestia] Tagowanie.

### ISSUE THREAD

**Issue by jacentys** [YetiForceCompany/YetiForceCRM#7192]
Czy można zaimplementować w YF tagowanie?
Byłoby to bardzo przydatne przy szybkim wyszukiwaniu rekordów.

**Comment by jacentys** [comment]
Dla mnie niestety to wada - korzystam już z takiego rozwiązania jak zasugerowane, ale grzebanie w setup-ie za każdym razem gdy chce się dodać nowy tag nie jest dobrym rozwiązaniem. Nie wspominając o tym, że trzeba by to robić dla każdego modułu osobno.

**Comment by bpabiszczak** [comment]
Wystarczy dodać nowy uitype który jest dynamicznym słownikiem [i pewnie najlepiej niezależnym od użytkownika, każdy może mieć własne wartości]. Szacuje, że to 1-2 dni roboty.

**Comment by bpabiszczak** [comment]
Jeżeli ktoś chce za to zapłacić, to zapraszamy do kontaktu :] Dla nas ta funkcjonalność ma bardzo niski priorytet.
