### ISSUE TITLE
[PL] Mail - szybkie przypisywanie wielu maili.

### ISSUE THREAD

**Issue by jacentys** [YetiForceCompany/YetiForceCRM#7193]
#### Actual Behavior

Brak możliwości szybkiego przypisywania maili do projektów / zdarzeń etc.
#### Expected Behavior

Może nie znalazłem pomimo poszukiwań - jak przypisać wiele maili do projektu / szansy sprzedaży?
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
Proszę pamiętać o tym artykule: http://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/pomysly-zwiazane-z-rozwojem-systemu

Jeżeli maile są już w systemie zeskanowane [występują w mailach firmowych] to można korzystać z opcji "resetuj powiązane maile" która jest na widżecie lub też z opcji "przypisz maile" która jest dostępna na liście maili firmowych. 

One "wywołują" mechanizm odpowiedzialny za "powiązywanie maili".
