### ISSUE TITLE
List of related records

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7225]
#### Issue

I want to change the layout for List of related records from PDF export.
![listofrelated](https://user-images.githubusercontent.com/30116021/42674927-5727a2ee-867a-11e8-8c6d-284e39c73535.png)

#### Actual Behavior

Now related records list doesn't look so good.
Eg.
![listofrelatedpdf](https://user-images.githubusercontent.com/30116021/42674967-8c85a4f4-867a-11e8-9161-5b18a9d8f54c.png)

Someone asked here: https://github.com/YetiForceCompany/YetiForceCRM/issues/4666 for how to add a border to relatedRecordsList header.

What files are responsible for generating list template?
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/85b95deb009620a1b077318400c5afc3dceb9073/app/TextParser.php#L778-L791

**Comment by cltvchannel** [comment]
@mariuszkrzaczkowski can you help me add a header border?

**Comment by cltvchannel** [comment]
@mariuszkrzaczkowski And for this?
![llll](https://user-images.githubusercontent.com/30116021/42676306-51292236-8680-11e8-94af-1ccd3e206aff.png)

Thanks !

**Comment by mariuszkrzaczkowski** [comment]
I've added a class, you can use styles https://github.com/YetiForceCompany/YetiForceCRM/commit/ebd0d7635d1dfd7b45da7e5289e2393f4b955a6e#diff-9bbcf5e46afe9f7f00c6b43dc8c2d3c7R792

**Comment by cltvchannel** [comment]
Thanks !

**Comment by cltvchannel** [comment]
@mariuszkrzaczkowski 
It's ok to put the class in Main.css file?

**Comment by mariuszkrzaczkowski** [comment]
Not because these styles do not work in pdf, you must use inline styles

**Comment by JohnMaverick** [comment]
Guys, can you gimme example how to use class mentioned?
