### ISSUE TITLE
This part of code not working when export to Excel.

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7227]
This code not working anymore like in 4.3 version.
https://github.com/YetiForceCompany/YetiForceCRM/blob/682f24c46910006dde6b302941f722dcc12b6f3a/modules/Vtiger/actions/QuickExport.php#L42

**Comment by cltvchannel** [comment]
Try to export an Excel file from one of the modules.
If i know, this code is responsable for adding a background and Bold Text to first row (row with columns name).

**Comment by rafalpospiech** [comment]
["it works on my machine"](https://drive.google.com/uc?id=1Cb-Wy65Br6FUrfr3s8Ff28_AqnswwiVC)
which version of yeti do you have installed? exact version

**Comment by rafalpospiech** [comment]
ahhh I understand bold title is missing, we will fix this soon :)

**Comment by cltvchannel** [comment]
@rafalpospiech Yes, bold title and background.
If is needed, the user can make changes to add a header?

**Comment by cltvchannel** [comment]
![listofrelated](https://user-images.githubusercontent.com/30116021/42691889-7b6630c0-86b2-11e8-94b5-e182db9e8a3f.png)
