### ISSUE TITLE
When will 4.4 upgrade be released?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#7229]
Hi,
are you able to tell me when 4.4 upgrade version will be released? I know there are still a number of bugs being 'squashed' :) but getting a little desperate now to finish my CRM as cannot use it without the working multi-image (which has never worked in 4.3). 

Is there a possibility it will be today?

Kind regards

**Comment by bpabiszczak** [comment]
No :(
We correct issues all the time.

**Comment by Tingfe** [comment]
Still waiting for the RC3 Update / Full Release / XAMMP package.

**Comment by ldgbc** [comment]
@Tingfe Good news https://github.com/YetiForceCompany/YetiForceCRM/issues/7386#issuecomment-409220580
