### ISSUE TITLE
Is it possible to create a workflow that sends an xml export to an email account?

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#7257]
Hi,

I want to create an xml export every time a record is saved and send it to either an email address or a url (ftp). Is this possible using Workflows?

I can see that Send PDF is an option but not Send as XML.

Is there a way to achieve this?

If it isn't possible with workflows is there any other way this could be achieved?

Kind regards

**Comment by mariuszkrzaczkowski** [comment]
This requires writing a handler or a custom workflow
