### ISSUE TITLE
[PL] Dodatkowe pola w module Księgowość - Faktury

### ISSUE THREAD

**Issue by FeniksPC** [YetiForceCompany/YetiForceCRM#7265]
Aktualnie w pionie oświaty potrzebny jest Nabywca i Odbiorca. W standardzie mamy Informacje Podstawowe gdzie wybieramy kontrahenta, który automatycznie jest nabywcą. Natomiast nie ma możliwości dodać Odbiorcy (nazwa placówki, adres bez NIPu). 
Nawet jeśli zmienię szablon wydruku to tych danych nie zaciągnę bo nie mam skąd.

Jest możliwość dodanie tego z poziomu użytkownika za pomocą wbudowanych narzędzi czy to kwestia dodatkowego kodu?

**Comment by mariuszkrzaczkowski** [comment]
Tak można z panelu admina
![image](https://user-images.githubusercontent.com/10198654/42880150-973ba980-8a93-11e8-9d81-a97333994891.png)
