### ISSUE TITLE
webservice api error

### ISSUE THREAD

**Issue by disemelo** [YetiForceCompany/YetiForceCRM#7276]
#### Issue

Hi,
I get errors when testing webservice api via postman, please see below for screenshots. 
regards
#### Actual Behavior

![postman](https://user-images.githubusercontent.com/11823394/42924466-a1576296-8b2a-11e8-8524-6b94411edcd8.png)
server/php configuration
![config1](https://user-images.githubusercontent.com/11823394/42924525-e5502d20-8b2a-11e8-8417-d68d0bc4a002.png)
![config2](https://user-images.githubusercontent.com/11823394/42924526-e5a4ea36-8b2a-11e8-80ab-26140c965328.png)
![config3](https://user-images.githubusercontent.com/11823394/42924527-e5de9600-8b2a-11e8-9989-f9a39a8a3f41.png)
![config4](https://user-images.githubusercontent.com/11823394/42924529-e6197e28-8b2a-11e8-853e-068a8c62ff01.png)
![config5](https://user-images.githubusercontent.com/11823394/42924531-e6530cf6-8b2a-11e8-8e92-88da6e77f80a.png)
logs
[Wed Jul 18 23:07:43.721938 2018] [mpm_prefork:notice] [pid 25954] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Jul 18 23:07:43.722007 2018] [core:notice] [pid 25954] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jul 18 23:07:50.447233 2018] [php7:notice] [pid 25958] [client 127.0.0.1:34490] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /var/www/html/done/install/views/Index.php on line 43, referer: http://127.0.0.1/done/install/Install.php
[Wed Jul 18 23:07:53.777375 2018] [php7:warn] [pid 25957] [client 127.0.0.1:34488] PHP Warning:  fsockopen(): unable to connect to www.google.com:80 (Connection timed out) in /var/www/html/done/app/RequestUtil.php on line 140
[Wed Jul 18 23:30:15.354602 2018] [php7:notice] [pid 25960] [client 127.0.0.1:34504] PHP Notice:  Undefined variable: application_unique_key in /var/www/html/done/install/views/Index.php on line 275
[Wed Jul 18 23:30:15.839523 2018] [php7:warn] [pid 25960] [client 127.0.0.1:34504] PHP Warning:  rmdir(/var/www/html/done/install): Permission denied in /var/www/html/done/vtlib/Vtiger/Functions.php on line 571
[Thu Jul 19 07:09:24.925753 2018] [php7:notice] [pid 25960] [client 127.0.0.1:34984] PHP Notice:  Undefined index: IP_ADDRESS in /var/www/html/done/vendor/yetiforce/csrf-magic/src/Csrf.php on line 251, referer: http://127.0.0.1/done/index.php
[Thu Jul 19 07:16:11.296409 2018] [php7:notice] [pid 25961] [client 127.0.0.1:34990] PHP Notice:  Undefined variable: table_ in /var/www/html/done/modules/Settings/WebserviceUsers/models/Record.php on line 195
[Thu Jul 19 07:16:11.296447 2018] [php7:notice] [pid 25961] [client 127.0.0.1:34990] PHP Notice:  Undefined variable: index_seq in /var/www/html/done/modules/Settings/WebserviceUsers/models/Record.php on line 195
[Thu Jul 19 07:35:18.669996 2018] [php7:error] [pid 25961] [client 127.0.0.1:36346] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/done/api/webservice/Portal/Users/Login.php on line 11

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.413
* Browser name and version: Chrome 67.0.33
* Environment name and version: Apache 2.4, php 7.1.19, mysql 5.6
* Operating System and version: Mint 18.2

**Comment by disemelo** [comment]
Here is an update of server configuration. I'm not sure what is missing...

![config1](https://user-images.githubusercontent.com/11823394/42944327-a6cfe988-8b65-11e8-9c47-144295930d9b.png)
![config2](https://user-images.githubusercontent.com/11823394/42944328-a70b528e-8b65-11e8-9772-baa76deb1ca4.png)
![config3](https://user-images.githubusercontent.com/11823394/42944329-a7bc4c88-8b65-11e8-86fe-1e057466682e.png)
![config4](https://user-images.githubusercontent.com/11823394/42944330-a7fd0610-8b65-11e8-9732-2c041c9aac5c.png)
![config5](https://user-images.githubusercontent.com/11823394/42944332-a837758e-8b65-11e8-932d-f46d4cbddb0c.png)
![portal](https://user-images.githubusercontent.com/11823394/42944334-a8cdfa9a-8b65-11e8-9a63-e087474bce3e.png)
![portal-config php](https://user-images.githubusercontent.com/11823394/42944336-a90cd38c-8b65-11e8-8f1f-5dd3e8d8139c.png)
![portal-config](https://user-images.githubusercontent.com/11823394/42944337-a947f264-8b65-11e8-8e1e-d549f1e669cc.png)
=========== apache error.log
[Thu Jul 19 14:18:39.740102 2018] [php7:error] [pid 15101] [client 127.0.0.1:40742] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:32.244782 2018] [php7:error] [pid 15101] [client 127.0.0.1:40774] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:36.233366 2018] [php7:error] [pid 15097] [client 127.0.0.1:40776] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:36.966852 2018] [php7:error] [pid 15107] [client 127.0.0.1:40778] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:37.425403 2018] [php7:error] [pid 15102] [client 127.0.0.1:40780] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:37.736844 2018] [php7:error] [pid 15284] [client 127.0.0.1:40782] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:37.952814 2018] [php7:error] [pid 15100] [client 127.0.0.1:40784] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:38.169730 2018] [php7:error] [pid 15098] [client 127.0.0.1:40786] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:38.554059 2018] [php7:error] [pid 15101] [client 127.0.0.1:40788] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:38.723421 2018] [php7:error] [pid 15097] [client 127.0.0.1:40790] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:38.889525 2018] [php7:error] [pid 15107] [client 127.0.0.1:40792] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11
[Thu Jul 19 14:26:39.072218 2018] [php7:error] [pid 15102] [client 127.0.0.1:40794] PHP Fatal error:  Class 'Api\\Core\\BaseAction' not found in /var/www/html/test/api/webservice/Portal/Users/Login.php on line 11

**Comment by paula-w** [comment]
Please wait about 3 to 6 weeks until we will add all necessary fixes to portal2 so that it can work with the newest CRM version.
