### ISSUE TITLE
[PL] Nazwy produktów, hiperłącza, stopka PDF

### ISSUE THREAD

**Issue by FeniksPC** [YetiForceCompany/YetiForceCRM#7278]
Zmodernizowałem wygląd faktury na taki jak potrzebuję ale mam w dalszym ciągu 3 problemy. 
1. Wszystkie produkty są podlinkowane i kierują mnie do bazy danych>Produkty. Zmiana wyglądu tabelki (ukrycie podlinkowania) jest ignorowane, wychodzi na to, że plik źródłowy daje już element z hiperłączem.

2. Dłuższe nazwy produktów są ucinane. Teoretycznie nie powinno być ograniczenia długości nazwy produktu lub jeśli takowe ograniczenie jest to powinno one obowiązywać również w momencie tworzenia kartoteki produktu. 

3. W stopce faktury umieściłem informację o odsetkach i administrowaniu danymi. Przy większej ilości produktów tekst nie przechodzi na drugą stronę, tylko tabelka z produktami i podsumowanie nachodzi na tekst w stopce.  Screen poniżej.
![bez tytulu](https://user-images.githubusercontent.com/40859939/42940310-49d059d6-8b59-11e8-9c42-961e09cc74a7.png)

**Comment by mariuszkrzaczkowski** [comment]
Każdy pytanie/problem zgłaszamy oddzielnie.
Brak wystarczających informacji do analizy błedów.
Zapoznaj się z regulaminem zgłaszania problemów.
Przetestuj wersje deweloperską.
