### ISSUE TITLE
PHP Fatal error while installation

### ISSUE THREAD

**Issue by gerripeach** [YetiForceCompany/YetiForceCRM#7283]
#### Actual Behavior
PHP Fatal error is thrown while instalaltion, probably after creating all the tables.
Installation stucks in "Installation in progress"
If you reload Installation page you can enter pw/username
If you do so -> "invalid user name or password"

#### Expected Behavior
finish Installation without any problems.

#### How to trigger the error
1. Download YetiForceCRM-4.4.0RC3-complete.zip
2. unzip
3. start installation
4. wait till "finished"
5. faliure

#### Your Environment
* YetiForce Version used:  YetiForceCRM-4.4.0RC3
* Browser name and version: Chrome
* Environment name and version: Apache2, PHP 7.2
* Operating System and version: Ubuntu 18.04

Error Log:
```
[Fri Jul 20 14:13:26.704328 2018] [php7:error] [pid 8909] [client ::1:53708] PHP Fatal error:  Uncaught App\\Exceptions\\Security: Gro\xc3\x9fbuchstaben von A bis Z in /var/www/yeti/modules/Vtiger/uitypes/Password.php:23\nStack trace:
#0 /var/www/yeti/modules/Users/models/Record.php(241): Vtiger_Password_UIType->validate('asdasd')
#1 /var/www/yeti/modules/Users/models/Record.php(196): Users_Record_Model->getValuesForSave()
#2 /var/www/yeti/modules/Users/models/Record.php(178): Users_Record_Model->saveToDb()
#3 /var/www/yeti/install/models/InitSchema.php(114): Users_Record_Model->save()
#4 /var/www/yeti/install/models/InitSchema.php(23): Install_InitSchema_Model->setDefaultUsersAccess()
#5 /var/www/yeti/install/views/Index.php(260): Install_InitSchema_Model->initialize()
#6 /var/www/yeti/install/views/Index.php(126): Install_Index_View->step7(Object(App\\Request))
#7 /var/www/yeti/install/Install.php(32): Install_Index_View->process(Object(App\\Request))
#8 {main} thrown in /var/www/yeti/modules/Vtiger/uitypes/Password.php on line 23

```

**Comment by gerripeach** [comment]
```
Database type | MySQL
Host name | localhost
Host port | 3306
```
Installation Information:
https://web.enraged-rg.de/~karn/yeti/YetiForce1.html

**Comment by mariuszkrzaczkowski** [comment]
You have an incorrect server configuration, you have to correct it because without it it will not work.
