### ISSUE TITLE
Roundcube will not download in YetiForce CRM ver. 4.4.0 RC3

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#7286]
Hi,

I am just testing latest release candidate and trying to install Roundcube via module installation. When Download is clicked it doesn't install and no error message on screen. So, I enabled My Mailbox and the following error occurs:

Message
Could not find required roundcube library. Some features were disabled. Go to &lt;a href=&quot;index.php?module=ModuleManager&amp;parent=Settings&amp;view=List&quot;&gt;Modules – installation&lt;/a&gt; to download.

Then when I click the Standard Modules again the settings for My mailbox are unticked again. The Download installation doesn't work.

**Comment by raimondomartire** [comment]
I can confirm this error

**Comment by PercyP** [comment]
Also, I do have 

allow_url_fopen = On

**Comment by mariuszkrzaczkowski** [comment]
try now

**Comment by raimondomartire** [comment]
After modified your last string I've 508 Loop Detected error

**Comment by cltvchannel** [comment]
I have tried now, and for me it's ok.

**Comment by PercyP** [comment]
To get around it I edited the OSSMail.php (under config/modules in main root) and changed the default settings there to my own. However there is still a write error when I open the roundcube mail settings and try to save. The folder permissions for the OSSMail.php is set at 0664

**Comment by PercyP** [comment]
Hi @paula-w 

I have already opened issue - its here: https://github.com/YetiForceCompany/YetiForceCRM/issues/7324

:O)

**Comment by raimondomartire** [comment]
I don't have PercyP problem but for me always problem in download library. But if I download manually library from https://github.com/YetiForceCompany/lib_roundcube I can solve coping it in public_html/modules/OSSMail/roundcube/?

**Comment by mariuszkrzaczkowski** [comment]
you can just download eg
https://github.com/YetiForceCompany/lib_roundcube/archive/0.0.48.zip
rename the file and put it in this location

> cache/upload/lib_roundcube.zip

and click the download should work

**Comment by raimondomartire** [comment]
@mariuszkrzaczkowski Thanks in this way work without issue

**Comment by danielmalkmus** [comment]
have a look in modules/settings/ModuleManager/models/Library.php

Search for following code in function download:

`if (isset($headers['status']) && strpos($headers['status'], '302') !== false) {`

This condition will fail, because the first char in $header['status'] has changed on my Server

the original code is $header['Status']

i have updated to 5.3 successfully. They way, YF downloads some libs has changed in further versions.
