### ISSUE TITLE
Project gantt

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#7292]
#### Issue
Not quite sure if gantt shows dates as it should, or do I miss something.
![pr1](https://user-images.githubusercontent.com/10330264/43072670-89bc0cec-8e7f-11e8-91a3-702f1b743ceb.png)
![pr2](https://user-images.githubusercontent.com/10330264/43072676-8e08323a-8e7f-11e8-94e5-132599cad7e1.png)
![pr3](https://user-images.githubusercontent.com/10330264/43072681-92fa69ca-8e7f-11e8-98fc-bc558555a1f7.png)
![pr4](https://user-images.githubusercontent.com/10330264/43072685-96578e7c-8e7f-11e8-93bf-18ff6b6c0422.png)

#### Your Environment

* YetiForce Version used: 4.4 rc3
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rafalpospiech** [comment]
fixed in https://github.com/YetiForceCompany/YetiForceCRM/issues/7292
