### ISSUE TITLE
How to choose columns from related record in the filter

### ISSUE THREAD

**Issue by varlog11** [YetiForceCompany/YetiForceCRM#7305]
May i choose columns from related record in the filter?
![image](https://user-images.githubusercontent.com/1807261/43121872-3d00c71a-8f30-11e8-81f2-0bb5c41c3641.png)

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by cltvchannel** [comment]
This feature is scheduled for version 5.0 .
Read this https://github.com/YetiForceCompany/YetiForceCRM/issues/6866

**Comment by varlog11** [comment]
Thanks for the answer
