### ISSUE TITLE
Sum filed values from related module fields.

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7307]
#### Issue

I have added a workflow action to sum filed values from Payments In module.
When i add a payment sum calculation is ok, but when i delete a payment sum calculation not updating.
I need to add a new payment to update.

#### Expected Behavior

Update sum when i delete a payment.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Latest version 4.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Add workflow that updates the sum during removal
![image](https://user-images.githubusercontent.com/10198654/43124180-a3a22446-8f26-11e8-970f-125f24939c66.png)

**Comment by cltvchannel** [comment]
@mariuszkrzaczkowski 
I have added a workflow, but nothing happened.

**Comment by mariuszkrzaczkowski** [comment]
Describe how you have set up the workflow with full details, we will try to call the error.

**Comment by cltvchannel** [comment]
1. I have created a new currency field on Accounts called Total payments.

2. I have added a workflow with "Sum filed values from a related module" on Payments In module.
Field: Value [Payments In] sum in Total payments [Account] .
Executing when Create record.

3. I have added a workflow with "Sum filed values from a related module" on Payments In module.
Field: Value [Payments In] sum in Total payments [Account] .
Executing when Delete record.

When i add a record in Payments In, sum is updated in Total payments from Account module, but when i delete record from Payments In, sum is not updated in Total payments from Account module.

**Comment by cltvchannel** [comment]
@mariuszkrzaczkowski @konadrian  This commit not fixed issue.
![videoupload](https://user-images.githubusercontent.com/30116021/43193106-ceeff04c-9007-11e8-968e-3b1d66fd7f91.gif)

Also, i have tried to permanently delete payments record and nothing happened.
Correct me if something wrong.

**Comment by cltvchannel** [comment]
Now it's OK.
Great job.
Thanks !

**Comment by cltvchannel** [comment]
@mariuszkrzaczkowski @konadrian 
Also please check conditions for this function.
Look like conditions don't work.
I have created a job to sum filed values only when status from Payments in is "Paid".
Function sum values with all Statuses.

**Comment by mariuszkrzaczkowski** [comment]
summing the values held without conditions, in the future we will add support for conditions.

**Comment by cltvchannel** [comment]
Ok. Thanks !

**Comment by cltvchannel** [comment]
@manwenick If you want to sum 3 fields, you need to choose "Update field" workflow.
Sum filed values is for sum values from one field for all records and show in another field.

**Comment by manwenick** [comment]
@cltvchannel Thank you for advise! 
Which expression should I use for it? I can choose the field which contains currency, then I need to choose expression, but there is no expression for addition oder for sum.

**Comment by manwenick** [comment]
@cltvchannel @mariuszkrzaczkowski 
Hi there, I did it as you said&
Step 1: Enter basic details of the workflow --> Mdule Products -->  Every time a record is saved (eg. creating, modifying) --> next
Step 2: Choose filter conditions --> no filters 
Step 3: add to Do --> "update fileds" --> set field values --> add field --> choose field4
--> expression --> choose field --> field1 + field2 + field3

Result: If I've filled out the fields 1to3 and try to save, I get an empty screen.

**Comment by slawekk87** [comment]
Hi i checked this on gitstable 4.4.0 and its working, my procedure:
create 4 currency fields on accounts module:
CUS1
CUS2
CUS3
CSUM
create new workflow in accounts module:
any record save action
create new task for workflow:
Update record
select field CSUM and use expression: cus1+cus2+cus3

Try to create any record with filled cus1,cus2,cus3

**Comment by manwenick** [comment]
@slawekk87 
Hi, I checked it on gitdeveloper, it also was working. 
I checked log files in cache/logs, but there is no entries from the last days. 
Is there another one directory where I can find any log files?

**Comment by slawekk87** [comment]
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging try to increase debugging levels and try again.
