### ISSUE TITLE
Search (Pop-Up) Selection, Default Opening Width Size [question]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7310]
Reference: https://github.com/YetiForceCompany/YetiForceCRM/issues/7160

#### Issue
I want to change the default size of the Popup. Popup size revert to default width/height. Need to modify it to be bigger (or smaller).

#### Actual Behavior
Popup revert to the default width/height size.

#### Expected Behavior
Either to be able to change the default width/height or remember last size.

#### How to trigger the error
1. /index.php?module=Assets&view=Edit
2. Related to > Search (glass)
3. /index.php?module=Accounts&src_module=Assets&src_field=parent_id&src_record=&view=Popup&triggerEventName=postSelection6611
4. Change the size of the Step 3 Pop-up using /modules/Accounts/Accounts.php ???

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Firefox 61
* Environment name and version: XAMPP
* Operating System and version: Windows 7

**Comment by mariuszkrzaczkowski** [comment]
Check how it works in the development version, there are no popup windows, only modal windows.
Your problem no longer occurs.

**Comment by ldgbc** [comment]
@mariuszkrzaczkowski Thanks marius, but is there a way to temporary make that edit? Who know how many more month until v4.4 is release.

**Comment by mariuszkrzaczkowski** [comment]
optimist with you, wait a few days and you will get :)
