### ISSUE TITLE
How to: ProductsTableLongVersion field Name align value text to left ?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7312]
#### Issue

How i can align value from "Name" field on ProductsTableLongVersion to left?
I know how to align the column name to left, but i cannot align row value to left only for "Name" field.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Latest version 4.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@cltvchannel for ProductTableNew I made next modifications:

```
			// '.productTable .tHeader {background:#ddd, text-transform: capitalize !important;}' .
			'.productTable .tHeader {background:#ddd, text-transform: capitalize !important; border: 1px solid #000; padding:5px;text-align:left; }' .
```
and
```
			// '.productTable tr td{border-bottom: 1px solid #ddd; padding:5px;text-align:center; }' .
			'.productTable tr td{border: 1px solid #000; padding:5px;text-align:left; }' .
```

This is not perfect but works well for me

**Comment by cltvchannel** [comment]
@vovpff What file you changed?

**Comment by cltvchannel** [comment]
@vovpff This is ok, but me i need only Name field to be aligned to left. The other fields must remain aligned to center.
