### ISSUE TITLE
Close site question

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7316]
#### Issue

dev ver. 4.3.446

When clicking Save button edit edit view every time appears window.

![image](https://user-images.githubusercontent.com/8545791/43148379-c8fce2b6-8f6d-11e8-91e4-93b3563a7670.png)
 
Sorry for Russian. Translation: Perhaps the changes you have made will not be saved.

#### Actual Behavior

Bothersome window

#### Expected Behavior

Save witout any problems

#### How to trigger the error

1. Open any record
2. Click edit
3. Click save

#### Your Environment

* YetiForce Version used: current dev ver. 4.3.446
* Browser name and version: Chrome
* Operating System and version: Win 10

**Comment by cltvchannel** [comment]
@vovpff In version 4.3.452 this window not appear anymore.
I think this issue is ok now.

**Comment by mlorencik** [comment]
Please show us a console log, there is probably a javascript error

**Comment by vovpff** [comment]
@mlorencik dev 4.3.453 popup with question not appear. In logs only:
```
index.php?module=IGDN&view=Detail&record=3690:5 GET https://www.google-analytics.com/analytics.js 0 ()
(anonymous) @ index.php?module=IGDN&view=Detail&record=3690:5
(anonymous) @ index.php?module=IGDN&view=Detail&record=3690:6
jquery.js:9488 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js:9488
ajax @ jquery.js:9206
_request @ Connector.js:130
request @ Connector.js:35
loadWidget @ Detail.js:325
(anonymous) @ Detail.js:297
each @ jquery.js:354
each @ jquery.js:189
loadWidgets @ Detail.js:295
registerEvents @ Detail.js:2521
(anonymous) @ app.js:1535
mightThrow @ jquery.js:3534
process @ jquery.js:3602
setTimeout (async)
(anonymous) @ jquery.js:3640
fire @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
fire @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
completed @ jquery.js:3888
```

**Comment by mlorencik** [comment]
I check this our new version (4.4.34) and all works fine, please update

**Comment by vovpff** [comment]
This message apperas sometimes from version to version. Looks like some code not finished

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/ddaa3c7c5b74561973e552dcde356aad22ff1848 https://github.com/YetiForceCompany/YetiForceCRM/commit/1728ec2d4f9f93f124f413c07d53707b5cbd2f41
