### ISSUE TITLE
[BUG][4.3.447][Related records] Showing contacts of all accounts

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#7322]
#### Issue
If I select an account and I want to search a contact related to this account, it shows all the contacts that match with the name I wrote even if the contact is of another account.

#### Expected Behavior
Show only the contacts that match the search and the selected account.

#### How to trigger the error
Searching by name:
![screenshot_1](https://user-images.githubusercontent.com/16593721/43194296-ef374912-8ff9-11e8-90bf-a8edecd11d4e.png)

Selecting a contact:
![screenshot_2](https://user-images.githubusercontent.com/16593721/43194298-ef54cf0a-8ff9-11e8-9246-22eaeca71f6f.png)

#### Your Environment

* YetiForce Version used: Latest version (4.3.447)
* Browser name and version: Google chrome
* Operating System and version: Windows 10

**Comment by vovpff** [comment]
@MacarenaReina you mean Contacts selection like in vTiger? This function never works in Yeti

**Comment by paula-w** [comment]
It works properly, this is how uitype10 works by default, we can change it but we’re not sure we want to.
If you only want to select contacts related to certain account it’s enough that you click the magnifying glass icon and there in the first view the system displays only contacts related to this account.
