### ISSUE TITLE
Unable to change Name of Imap server RC3

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#7324]
In trying to set up mail on RC3 the Roundcube setup field does not allow editing:

Name of imap server. It has a default value for gmail that cannot be removed.

When I try to save the settings it produces the following error:

Incorrect request
Invalid request - validate Write Access

**Comment by mlorencik** [comment]
Please check file in path "config\modules\OSSMail.php", in $config['default_host'] we have array with hosts. You can change default or add more hosts.

**Comment by mariuszkrzaczkowski** [comment]
Fixed in #7352
