### ISSUE TITLE
Picklist entries are not accepted on Accounts Module

### ISSUE THREAD

**Issue by indigoleo** [YetiForceCompany/YetiForceCRM#7328]
#### Issue
Modules=>Edit Fields=>Picklist Value creation does not accept entries on YF GitDeveloper

#### Actual Behavior
Entered picklist values (all Latin 1 encoded characters) are not accepted, program displays "Entered illegal character" error;

![yferror_picklists](https://user-images.githubusercontent.com/36971475/43207633-2923aad0-9031-11e8-9bc2-170e0526e3fd.gif)

#### Expected Behavior
Program to accept the inputted options as pciklist values;

#### How to trigger the error

1.Go to Modules=>Edit Fields=>Select "Accounts" as Module;
2.Select "Add custom field" , select "picklist" from field type dropdown. Select EITHER basic or additional from "Table" dropdown;
3. Input picklist values, left mouse click on inputted picklist to enter another entry until done. Then click "Save"

#### Your Environment

* YetiForce Version used: GitDeveloper 4.3.452
* Browser name and version: Mozilla Firefox 61.0.1 64 Bit
* Environment name and version:
* Operating System and version: Ms Windows 10 Pro

**Comment by ldgbc** [comment]
Sorry, off-topic but what the difference between Additional and Basic?

**Comment by vovpff** [comment]
@ldgbc if choose basic new field will be added as row to vtiger_modulename table. If you choose Additional then field will be added to vtiger_modulename**cf**.

As for me this is no principal difference

**Comment by mariuszkrzaczkowski** [comment]
@indigoleo Attach a list of values you are trying to add

**Comment by indigoleo** [comment]
They are:

Parts manufacturer
Importer
Distributor
Softwarehouse

FYI, even if you input only one of the above and click save, the same error message reoccurs.

**Comment by ldgbc** [comment]
@vovpff I suppose one advantage is you don't have to type in Field Name with the ### Additional  option. But I never use Additional because I'm scare it might break YF.

@indigoleo  have you tried with just 1 Item? For example

Distributor

and see if it get error.
