### ISSUE TITLE
Record View - Change or Edit Header Information [question]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7339]
#### Issue
Can't find how to change this information (Record Top Header Viewer Summary). Tried searching on Github, I remember changing the information in v3.3 or v3.4 but struggling to find where it is in v4.3 or v4.4.

#### How to trigger the error
1. ![issue - header record view 1](https://user-images.githubusercontent.com/1805303/43301027-ee1a2d58-91a5-11e8-82cb-0ecaf555582b.png)
2. Highlight in orange.
3.

#### Your Environment
* YetiForce Version used: ver. 4.3.453
* Browser name and version: Firefox 62
* Environment name and version: YF
* Operating System and version: YF

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/b245ae4bd6758368b43f6b3c14ec2bfc5646afbe/layouts/basic/modules/Contacts/DetailViewHeaderTitle.tpl#L27-L58

**Comment by ldgbc** [comment]
@mariuszkrzaczkowski Thanks! Was the GUI/Interface way removed or did I remember it wrong?

Would this be the correct edit
```
<h4 class="recordLabel pushDown marginbottomZero u-text-ellipsis" title="{$RECORD->getDisplayValue('salutationtype',$RECORD->getId(), true)}&nbsp;{$RECORD->getName()}"> 
 			{if $RECORD->getDisplayValue('salutationtype')} 
 				<span class="salutation">{$RECORD->getDisplayValue('salutationtype')}</span>**{$RECORD->getDisplayValue('parent_id',$RECORD->getId(), true)}&nbsp;{$RECORD->getName()}"> 
 			{if $RECORD->getDisplayValue('parent_id')} 
 				<span class="salutation">{$RECORD->getDisplayValue('parent_id')}</span>**&nbsp; 
 			{/if} 
 			<span class="modCT_{$MODULE_NAME}">{$RECORD->getName()}</span> 
 			{assign var=RECORD_STATE value=\App\Record::getState($RECORD->getId())} 
 			{if $RECORD_STATE !== 'Active'} 
 				&nbsp;&nbsp; 
 				{assign var=COLOR value=AppConfig::search('LIST_ENTITY_STATE_COLOR')} 
 				<span class="badge badge-secondary" {if $COLOR[$RECORD_STATE]}style="background-color: {$COLOR[$RECORD_STATE]};"{/if}> 
 					{if \App\Record::getState($RECORD->getId()) === 'Trash'} 
 						{\App\Language::translate('LBL_ENTITY_STATE_TRASH')} 
 					{else} 
 						{\App\Language::translate('LBL_ENTITY_STATE_ARCHIVED')} 
 					{/if} 
 				</span> 
 			{/if} 
 		</h4> 
 	</div> 
 	<div class="paddingLeft5px"> 
 		{$RECORD->getDisplayValue('parent_id')} 
 		<div> 
 			<span class="muted"> 
 				{\App\Language::translate('Assigned To',$MODULE_NAME)}: {$RECORD->getDisplayValue('assigned_user_id')} 
 				{assign var=SHOWNERS value=$RECORD->getDisplayValue('shownerid')} 
 				{if $SHOWNERS != ''} 
 					<br />{\App\Language::translate('Share with users',$MODULE_NAME)} {$SHOWNERS} 
 				{/if} 
 			</span> 
 		</div> 
 	</div> 
 </div> 


```

**Comment by ldgbc** [comment]
Wow! That was dangerous. Almost broke the system when I play with this. The DetailView was blank as I refresh after each change made. Anyway looked into the PHPerror log and found a path:

\cache\templates_c\basic\

I suppose after awhile (enough refresh) YF will start using these Cache instead of /layouts/basic/modules/Contacts/DetailViewHeaderTitle.tpl

So even if you revert that DetailViewHeaderTitle file back to the original and refresh it still doesn't work because it using the Cache version. So I basically delete the whole basic folder. Did a refresh and it start working again.

**Comment by mariuszkrzaczkowski** [comment]
@ldgbc what effect are you trying to get?

**Comment by ldgbc** [comment]
@mariuszkrzaczkowski 

Going to do with a template like this:

[Salutation] [First Name] [Middle Name] [Last Name]
[Mobile] [Email]
[Street Number] [Street Name], [City] [State] [Postcode]
[Member of] (Assigned to: [Assigned to])
I'm trying to restore a version v3.4 to see if that GUI method is there. But appreciate if you can help me or give me clue on how to make the proper edit.

**Comment by ldgbc** [comment]
/index.php?module=Search&parent=Settings&view=Index&block=13&fieldid=56

I discovered this GUI method. Look like this was previous what I was using in v3.4. Anyway by changing the field:
"Main columns for a module (including a label for uitype 10)"
You can manipulate that first line.

I suppose by editing that first line as you see fit, go to the DetailViewHeaderTitle and make the necessary copy/paste you should be able to change the 2nd lines.

**Comment by ldgbc** [comment]
Update: 
This file: /layouts/basic/modules/Contacts/DetailViewHeaderTitle.tpl
is the default fall back file when the template_c file is blank.

So I went to the \templates_c\basic 
and search the DetailViewHeaderTitle

But the coding in this Cache file is weird, it seem to pull data from a "smarty_tpl" file, which I would assume it the "Main columns for a module (including a label for uitype 10)" section.
