### ISSUE TITLE
Column width [%] - Less than 10% [question][bug]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7346]
#### Issue
There is a few field that I want a small as possible (checkbox for example). It seem that you can't go any lower than 10%, anything below 10% (1 2 3 ... 7 8 9) size is still same as 10%.

How can I make the column really small?

#### Actual Behavior
Size doesn't change.

#### Expected Behavior
Size change for 1% to 9% still work.

#### How to trigger the error
1.![issue - column width](https://user-images.githubusercontent.com/1805303/43316529-fb1ea7ae-91dc-11e8-888d-e417662651fd.png)
2. Left image I use 10%, middle top show how it look like at 10%
3. Right image I use 1%, middle bottom show how it look like at 1%.
4. 1% and 10% is the same.
5. Image below show Last Name column at 40% or something.
![image](https://user-images.githubusercontent.com/1805303/43316624-331d3724-91dd-11e8-9abb-2c2091768782.png)

#### Your Environment

* YetiForce Version used: [ver. 4.3.453]
* Browser name and version: Firefox 61
* Environment name and version: Yetiforce
* Operating System and version: Yetiforce

**Comment by vovpff** [comment]
@ldgbc this is limitation of field template (not sure what this is correct name of cause). The same situation with picklists. I have picklist what contains 4 three symbols positions: [Y], [G], [C] and [W] but in list view column takes a tot of space:

Firstly I tried to change field name length (translation of field name) but there are limitation too.

My example:

![image](https://user-images.githubusercontent.com/8545791/43316962-bf3a172a-91a3-11e8-91f1-b06ac4d46a7c.png)

**Comment by poradz** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/7350

**Comment by vovpff** [comment]
@poradz Any ideas how to change width of Additional Information column for phone number fields. Usually this field filled with phone extension what contains 3-5 digits but for list view this takes too much space.

**Comment by vovpff** [comment]
@poradz Checked on dev ver. 4.3.454. Looks like this fix not applied.

**Comment by ldgbc** [comment]
@vovpff Additional Information probably have to edit files for that one.

@vovpff dev ver. 4.3.454. Same. checked and it still look like it 10%. I think it because of this: 
@mariuszkrzaczkowski mariuszkrzaczkowski merged commit cbf2732 into YetiForceCompany:developer 17 hours ago
4 of 7 checks passed 

It need to wait till 7 of 7 checks passed before it get Committed into Developer(?). But this is great. Another good feature that we get to this in (we need to wait who know for how many month ;) )

**Comment by ldgbc** [comment]
@vovpff Wait 3 days and I retry the 2% but it still big with the first name. Can you get it to work or it just me?

Can't seem to reproduce it like @poradz https://github.com/YetiForceCompany/YetiForceCRM/pull/7350

https://github.com/YetiForceCompany/YetiForceCRM/issues/7362

**Comment by vovpff** [comment]
@ldgbc looks like dev still not updated with this fix.

**Comment by ldgbc** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/f04768a00cc3762b87aad34da940a511e039e9d4 Seem to fixed it. @vovpff

**Comment by vovpff** [comment]
@ldgbc cool for text fields but not works with checkbox (Contacts - Permission to call checkbox)
![image](https://user-images.githubusercontent.com/8545791/43515813-33274464-958c-11e8-862a-c2a1a74fa652.png)

and picklists (Account - Status picklist)
![image](https://user-images.githubusercontent.com/8545791/43515801-29874df0-958c-11e8-8b75-cd7c30a1752e.png)

**Comment by poradz** [comment]
@vovpff It still works, but you can't adjust narrower width because of the select's placeholder width ("Select an option").

**Comment by ldgbc** [comment]
@vovpff  I suppose a workaround is to create another "English" translation and change the "Select an option" to "Select" and you can make the column thinner.

**Comment by vovpff** [comment]
@ldgbc you can use custom translation as standard English modification.
