### ISSUE TITLE
[Question] how to synchronize documents with google drive

### ISSUE THREAD

**Issue by raimondomartire** [YetiForceCompany/YetiForceCRM#7358]
I'm try to syncronize documents with my google drive using DAv Application menu. I've configured config/api.ini but I don't understand how I can save my documents on external google drive space. 
My goal is to provide the client with a document and return it to me, but I want these documents to be kept in folders outside the database and my server. 
I think that same way that I hope you indicate me work also for owncloud.
Can you help me, please?<br><hr>Generato da YetiforceCRM ver 4.3.453<br>PHP: 7.2.8<br><br><strong>Errori di configurazione del server:</strong><br>output_buffering: 4096<br>default_socket_timeout: 60<br>memory_limit: 512 MB<br>session.gc_maxlifetime: 1440<br>auto_detect_line_endings: Off<br><strong>Errori di libreria:</strong><br>apcu

**Comment by ldgbc** [comment]
Hi,

DAV isn't meant to be use for Synching any documents I think. DAV have two purpose (well 3)
(1) Contact information (e.g. Rain Martie (Full Name), Phone: 123 123, Email: 123@email, etc, etc)
(2) Calendar information (e.g. 01/01/2018 New Year Day, 25/12/2018 Christmas, etc, etc)
(3) To-Do or Task information. Not many support this yet. But for example: [ ] Install Yetiforce, [ ] Create an Account.

I don't think Yetiforce automatic scan a Folder then Add a record of new Documents yet. Maybe you can do it with CRON jobs (but I'm not sure how).

In term of how I would handle this would be using MailScanner. It will Scan all email from Client ABC and link that email to Client ABC Account/Contact. The attachment will get download too (automatically and there no way to disable it easily) and I think the attachment goes into Documents.

Anyway I could be wrong, I haven't use MailScanner yet. Did a test this morning but there was too many email so I left it overnight and haven't check on it yet.

**Comment by raimondomartire** [comment]
@Idgbc Thanks for reply but in your opinion there is (except email) a way to add attachment on project not in database but on my google drive? Regards

**Comment by ldgbc** [comment]
@raimondomartire I totally forgotten about WebDAV feature. To be honest I haven't really used WebDAV before (have played with Nextcloud/Owncloud setup but didn't really touch it, I assume Nextcloud is using WebDAV).

I will keep an eye on this issue but can't help any further. I tried doing a search for tutorial on how it can be done but sadly nothing of value was found.

I did a local search on my Webserver for Documents I have already upload into Yetiforce but couldn't find anything with it native filename. That would mean Yetiforce encode the file so a direct sync is not possible (I think).

I download a file and open it directly from browser to see where it is located at, however it it from a temp folder with a filename, "file.php" so it seem that Yetiforce is generating the file.

I remember from my v3.4 I found the folder, maybe there was an issue that give clue to find that.

**Comment by paula-w** [comment]
Right now the system doesn’t have the option to sync google drive documents, it can be added but it requires some programming work.
There’s DAV integration in YetiForce but for now only the CalDAV and CardDAV parts have been integrated with the CRM. We’re planning to also add webDAV but all documents will be stored in the CRM.

**Comment by ldgbc** [comment]
Based on @paula-w, it sound like it going to be some sort of CRON + Mass Add (Filename from Title) scenario.

Looking forward to it since there are documents (updated form, template, letter, etc) that would benefit from this.

**Comment by rioshaz** [comment]
can yetiforce scan gdrive now ? if yes how to do it..
