### ISSUE TITLE
Workflow - Read Record Data and Input Record Data in Task Name [question]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7361]
#### Issue
I am using Workflow to create Task/Event/To-Do. I want to name the task name with data from a record.
Is that possible?
For example, I used PDF Template to get the data name: $(translate : Contacts|First Name)$ so the Task/Event/To-Do can add the "First Name" to the Task Event.

#### Actual Behavior
Record's Data is ignored. "Happy Birthday - First Name"

#### Expected Behavior
Record's Data is read and input. For example, for Tom Kowalski. I can get task name (Workflow) to create it as:
Happy Birthday - Tom Kowalski

#### How to trigger the error
1. Developer version bugged so I can't test on that. Using Stable. https://gitstable.yetiforce.com/
2. Use "manual user trigger"
3. Create a Workflow for Contact as follow:
![issue - record data workflow](https://user-images.githubusercontent.com/1805303/43363757-27acbcfc-934f-11e8-99b2-689edeca9f2b.png)

4. Go to one of the Contact: https://gitstable.yetiforce.com/index.php?module=Contacts&view=Detail&record=114
5. Start Workflow tool
6. Result ignore First Name (Tom)
![issue - record data workflow 2](https://user-images.githubusercontent.com/1805303/43363759-3334fd32-934f-11e8-8ab7-b5906026278a.png)

#### Your Environment

* YetiForce Version used: v4.3 Stable
* Browser name and version: Firefox 61
* Environment name and version: YF
* Operating System and version: Windows 7

**Comment by adudekyeti** [comment]
Hi,
You put there a variable with name of "first name" field.
To get the value from field you have to use (for example): $(record : firstname)$

All of accesible variables you can easly find on email template settings:
![2018-07-31_10-00-13](https://user-images.githubusercontent.com/39482453/43446286-be2a47bc-94a8-11e8-8445-b36b1795652c.gif)

**Comment by ldgbc** [comment]
@adudekyeti Beautiful! Thank you!

Workflow "asdasdasd" must have been yours.
