### ISSUE TITLE
additional info width

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7362]
Additional Information column for phone number fields takes a lot of space in list view. Usually this field filled with phone extension what contains 3-5 digits but for list view this takes too much space.

This field width should be adjustable by admin.

**Comment by ldgbc** [comment]
It one of the reason why I disable the Phone field all together and create a separate Text Field for phone. However I do like they way it have Country selection and auto phone formatting.

But realistically, these additional info is only useful for those that have PBX setup isn't it?

**Comment by poradz** [comment]
By default the width of the columns is determined by the the widest value. So you can't make columns narrower than, for example, column's header "Additional information" like below:

![image](https://user-images.githubusercontent.com/31520119/43451668-c1cbf48a-94b5-11e8-9300-0325f7443ea5.png)

But this field is already adjustable by admin: 

![image](https://user-images.githubusercontent.com/31520119/43451720-e032a0d6-94b5-11e8-8ff5-721a2723830c.png)
![image](https://user-images.githubusercontent.com/31520119/43451731-e70244a2-94b5-11e8-987e-4bf9cb2df3e0.png)

So it's not an issue - I suggest to change the column's label for a shorter name to avoid this problem.

**Comment by vovpff** [comment]
@poradz thanks for your explanation!!!

**Comment by poradz** [comment]
No problem!

**Comment by vovpff** [comment]
@poradz I can't find correct place for translation of phone extension. Can you hel me?

![image](https://user-images.githubusercontent.com/8545791/47990351-5f4a0d80-e0f8-11e8-90eb-8a644917d672.png)
