### ISSUE TITLE
[4.3.454] Related Module Record Total Count in Record View Tab [enhancement]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7367]
#### Issue
I would like to know or at least some indication that this record is linked to other module's record. Either a total count of related record or some highlight dot (can be anything) indicating that this record have a related record. Otherwise it will be default and is blank.

Hopefully it won't go into the [ignore] tag. But it might be resource heavy (?).

#### Actual Behavior
Can't tell if this record any have other related record in the Tabs view.

#### Expected Behavior
Some sort of visual aid indication (numbers of record) related to this record.

#### How to trigger the error
1. Go to any record: https://gitdeveloper.yetiforce.com/index.php?module=Contacts&view=Detail&record=115 
2. Create an Activities or Upload a document or anything to this Contact.
3. Activities should display a (1) or Document should display a (1).
3a. Activities (1) Documents (5) Project (1)
4. See photo:

Current layout:
![issue visual aid 1](https://user-images.githubusercontent.com/1805303/43389463-1fd74b92-942f-11e8-99bc-bc42a14ae63b.png)

Proposed visual cue:
![issue visual aid 2](https://user-images.githubusercontent.com/1805303/43389464-2023b414-942f-11e8-9d9e-15e12b1945e3.png)

#### Your Environment

* YetiForce Version used: 4.3.454
* Browser name and version: Firefox 62
* Environment name and version: YF
* Operating System and version: YF

**Comment by SkavenKF** [comment]
It's a very important function ;-)

You can activate this in file "config/relation.php"
You must set the parameter 
![grafik](https://user-images.githubusercontent.com/10259801/43398761-45022246-9409-11e8-9152-dda0ae203d97.png)

**Comment by SkavenKF** [comment]
Hmm, in 440RC3. it looks .. a little bit ... different :-(
![grafik](https://user-images.githubusercontent.com/10259801/43403611-c3f404be-9415-11e8-8e05-8fc8934075a2.png)

Bug or Feature?

**Comment by vovpff** [comment]
@SkavenKF looks like broken GUI

**Comment by SkavenKF** [comment]
The rest looks good ...
