### ISSUE TITLE
[4.3.454] Workflow's Add Tasks - Duplicate / Copy existing task [enhancement]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7385]
#### Issue
Sometime the Task in Workflow is almost an duplicate of each other, maybe you only change the field type. I would like to be add to "duplicate" these task to speed up the Workflow system.

#### Actual Behavior
Have to create from the beginning of each task although they are duplicate (albeit small difference).

#### Expected Behavior
Able to quickly make duplicate and edit only the field that require editing.

#### How to trigger the error
1. Create a workflow, for example: Contact > Next > Next > Add Tasks:
https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=Edit
Please note: Developer Workflow is bugged, I used Stable Version.
2. Create a task.
3. No Duplicate task button, can only create a new Tasks.

Image: current configuration and recommend Button.
![issue - duplicate task workflow](https://user-images.githubusercontent.com/1805303/43453858-893aee8e-94fe-11e8-9a9a-8fe694eab337.png)

Duplicate button on Contact.
![issue - duplicate task workflow 2](https://user-images.githubusercontent.com/1805303/43453862-8b75e4ba-94fe-11e8-9050-1a4487ea5431.png)

But instead of Contact. Duplicate Workflow Task.

#### Your Environment

* YetiForce Version used: 4.3.454
* Browser name and version: Firefox 61
* Environment name and version: YF Stable
* Operating System and version: YF Stable

**Comment by paula-w** [comment]
Right now we’re not planning to add it because we would gladly remove the entire workflow feature and write it from scratch… unfortunately this feature has to wait until the new workflow is created so I’m going to close this issue for now. It might take weeks or even months, unless someone orders the functionality from us.
