### ISSUE TITLE
[4.3.454] Record Name in Web Browser Tab instead of Module Name [question][enhancement]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7386]
#### Issue
Each Tab name will use the module name only. Is it possible to have the Record name display instead?

#### Actual Behavior
[Module name] [module section] is being display on the Tab Name.

#### Expected Behavior
[Record name] [module section] display on the Tab name instead. For easier management, navigation and tab searching.

#### How to trigger the error
1. Open a Record (e.g. Contact: Tom) https://gitdeveloper.yetiforce.com/index.php?module=Contacts&view=Detail&record=115
2. Look at your Web Browser's tab name: 
![issue - web browser tab name 1](https://user-images.githubusercontent.com/1805303/43454407-47c5bf72-9500-11e8-8125-9314e1561904.png)

3. _Propose/draft_ tab name like this: 
![issue - web browser tab name 2](https://user-images.githubusercontent.com/1805303/43454418-4e9093fe-9500-11e8-8647-e03cd01405c3.png)

#### Your Environment

* YetiForce Version used: 4.3.454
* Browser name and version: Firefox 61
* Environment name and version: YF Developer
* Operating System and version: YF Developer

**Comment by arek1-618** [comment]
![7386](https://user-images.githubusercontent.com/32322851/43457827-5a2ff0a2-94c8-11e8-891e-31c1fef1cd02.png)

**Comment by mariuszkrzaczkowski** [comment]
We're just creating an update package
