### ISSUE TITLE
Email Template - How to Use?

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7396]
#### Issue
I don't understand how the Email Template work. There seem to be two system. How to use email template?

#### Actual Behavior
Email template is separate from Roundcube email.

#### Expected Behavior
Roundcube should have access to Email Template(?). Send a email from Record view (Contact/Account/etc)

#### How to trigger the error
1. ![issue - email template usage 1](https://user-images.githubusercontent.com/1805303/43466451-1738e48c-94cf-11e8-814a-a914b52da880.jpg)

^ This option is what I see in Roundcube email template.

![issue - email template usage 2](https://user-images.githubusercontent.com/1805303/43466452-17735b9e-94cf-11e8-9b71-774eda677510.jpg)

^ No idea how to activate these email template in the Email Template module.

#### Your Environment

* YetiForce Version used: 4.3.454
* Browser name and version: Firefox 61
* Environment name and version: YF Developer
* Operating System and version: YF Developer

**Comment by paula-w** [comment]
This is the same email template list, but the one you can see in Roundcube only displays the templates whose type is "Message", and the list you can see in the Email Templates module displays all types of templates - "Message" and "Record".

**Comment by asktechchef** [comment]
what is the difference between "Message" and "Record" email template type
