### ISSUE TITLE
[BUG] Assets language pl_pl

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#741]
![assets](https://cloud.githubusercontent.com/assets/1402355/7610788/1e58b6e0-f999-11e4-8451-0e017d432706.JPG)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
do you mean it should be the other way round?
If so, I fixed it [here] (https://github.com/YetiForceCompany/YetiForceCRM/commit/57db72a6fd3028c90f08359e2fda8a1aff779c0d)
