### ISSUE TITLE
Show only "YES" in printed reports

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#7429]
#### Issue

Hello!
This is a little question you may know. I'm trying to print reports with many checkboxes. The idea is that only the values with yes are shown. ¿Any idea how can I implement it? ¿Any basic code?

Thank you so much for your big help

#### Actual Behavior

In printed reports the checkboxes fields are showing YES or NO. See Image:

![image](https://user-images.githubusercontent.com/40429279/43547763-1fe7b422-95d4-11e8-9789-c205c7e8b46d.png)

#### Expected Behavior

Show only YES when the checkbox is activated as YES and blank when is activated as NO

#### How to trigger the error

1. No error, only a little question I'd like to solve.
2.
3.

#### Your Environment

* YetiForce Version used: last one
* Browser name and version: all browser
* Environment name and version: lamp php 7.0 and mariadb
* Operating System and version: Centos OS

**Comment by ldgbc** [comment]
Personally I haven't tried it yet, but can you use the Filter Condition? Make it =equal to "Yes"?

**Comment by santyabreu** [comment]
Still looking how to make this with no success... any idea?

@mariuszkrzaczkowski  @vovpff

**Comment by santyabreu** [comment]
The only thing that left to try is to change the PDF code so when a boolean is marked as 1 the system returns Yes and when 0 returns nothing. 

Do you know how can I modify this piece of code?

**Comment by paula-w** [comment]
Unfortunately both of these issues require a programmer to code it, you won’t be able to do it in the panel. We might add it in the future, but we only add such detailed changes when a client orders them from us.
