### ISSUE TITLE
[BUG] Install module PDF Maker

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#743]
Install the module in PDF Maker can not create the link in the menu on the unit, it does not exist in the list.

The Module Manager successfully installed

**Comment by waran70** [comment]
If you mean PDF Maker from ITSolutions it is not compatible with yeti as it try create entry in menu table what I guess not exist in YF due to different menu module.

**Comment by bpabiszczak** [comment]
Report an error for module authors.

**Comment by waw555** [comment]
Yes, this manufacturer Module. I will write to them, but they are responsible for a long time and not the fact that they will remake the module under the Yeti, as well as the module is a very nice and functional.

**Comment by bpabiszczak** [comment]
This module is very similar but closed, encrypted and its license it's beneficial for an end user. We prefer to focus and write PDF module from the scratch or fix the existing one than fix a module that doesn't really influence the development of YetiForce. You were not first who asked ITSolutions for the adjustment to YetiForce. If they ignore customers, maybe it's time to focus on what we have and improve it.

If I remember it correctly, the PDFMaker license doesn't allow to introduce ANY changes within the module so we cannot even touch this module.

**Comment by waw555** [comment]
Well, what is strange they take the money and for the client to adapt do not want to approach the client is not very good. In such a case, the law in our country to ignore the license))))
