### ISSUE TITLE
YetiForce 4.4 released!

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#7447]
We just **released version 4.4**  and this new version makes YetiForce even more advanced, and at the same time more secure. By choosing our system, you can be certain that you receive the quality and innovation at the highest possible level. 

This is the last version that introduces so many significant changes to YetiForce’s engine. From now on, **we will focus more on what our customers and our community need**. Our change of approach can already be seen in [Issues](https://github.com/YetiForceCompany/YetiForceCRM/issues), where we closed all the major ones and now we are more open to new changes. In the subsequent versions, we want to make some significant improvements, such as rewriting Workflows, however, changes in the future won’t be as critical as before.

The YetiForce community is growing and plays an increasingly more important role in the project. If you want to help develop the system, tell others about your experience with YetiForce and add a review at [Capterra](https://www.capterra.com/reviews/159123/Yetiforce/new). If you know how the system works, help other community members and contribute at GitHub, so that we will be able to focus more on programming.

In particular we **would like to thank our awesome community members** @ldgbc, @vovpff, @cltvchannel, @PercyP, @WalterLuis, @SkavenKF for all the work and effort you put into helping us develop YetiForce for the last couple of months. Check your email inboxes, we have a surprise for you!  

We’d like to remind you about our new [online store](https://yetiforce.shop/) and the services it offers. Every single purchase helps develop the project and each new functionality is then added to the system and becomes free for everyone. 

We have introduced an interesting promotion for those of you who are interested in purchasing our cloud services - if you purchase 6 months at once, you get 1 month for free, while if you purchase 12 months, you get 2 months for free.
Additionally to the first offer, we’re providing free access to our [Private Cloud 1 package](https://yetiforce.shop/index.php?option=com_djcatalog2&view=item&id=42:private-cloud-1&cid=12:private-cloud&Itemid=1071) for testing. The testing period lasts for 2 months, during this time you will receive all the benefits that are included in the package. After these 2 months are up you can either continue using our hosting services at their regular prices, or we will provide you with a full copy of your system that you can install on your own server.   

- **Modern interface**
An improved user interface, based on the latest version of Bootstrap 4 that was built to be used on various devices. 
- **Available for everyone**
Our user interface complies now with strict WCAG 2 requirements at the AA level, so that everyone can take advantage of the system’s potential.
- **Two Factor Authentication (2FA)**
Now access to the system is even more secure because you can use your phone for additional authentication. 
- **Security**
Security mechanisms were expanded with the OWASP ASVS 3.1 practices and obsolete libraries were removed. 
- **New Gantt charts** 
The mechanism responsible for visualising the task schedule and milestones was rewritten.
- **New widgets for everyone**
Widgets in the system were redesigned and now can be dynamically expanded and generated from every location within the system. 
- **Modern menu**
The menu was redesigned, so that it is more responsive on mobile devices and it’s easier to use. 
- **Innovation as a standard**
Almost 100 libraries were updated to the latest available versions, so now you can use the most up-to-date technologies.
- **GDPR tools**
New modules were added and they allow you to register and supervise the most important tasks related to new standards for personal data protection. 
- **Permission inspector**
From now on, you will be able to verify permissions to data and functionalities from the user level and without the need to login to the admin panel.  
- **New language**
The Romanian language was added to the system. Now YetiForce is available in 10 languages. 
- **New installation wizard** 
System installation will be more efficient and even more secure because the system verifies over 100 parameters of your server. 
- **New icons**
From now on, you can customize the user interface even more than before, so that your system becomes more intuitive. 
- **Modern views**
The mechanism responsible for displaying data in pop-up windows was rebuilt and that makes working on data even simpler. 
- **Improved comments**
The comments widget was rebuilt and now allows you to view information that are embedded in processes and subprocesses. 
- **Currency management**
The currency management panel was expanded for our community. Now you can change the default currency after the installation of the system. 
- **Hundreds of smaller improvements**
Changes are being constantly introduced and they make using the system more simple and enjoyable with each new version. Additionally, the latest version of the system is compatible with PHP 7.2.

**A more detailed changelog will be posted in the comments below.**

**LINKS**

- https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/4.4.0
- https://sourceforge.net/projects/yetiforce/files/latest/download?source=files

**UPDATE & REQUIREMENTS**
We would like to remind everyone that updates should first be executed on a test version, and only then on the production version [you should always have a backup copy of your environments].

- The list of current web server requirements necessary for version 4.4 to work properly can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements)

- A detailed description of the installation process can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-update)

**Comment by paula-w** [comment]
Version 4.4 CHANGELOG:

ADDED
- Added a new language - Romanian ro_ro
- Added DataSetRegister module
- Added Activity Register module
- Added Location Register module
- Added Incident Register module
- Added Merge Records module
- Added Audit Register module
- Added many new icons
- Added a mechanism that prevents adding a value that is out of the allowed range
- Added status field to the project milestones
- Added a warning about encryption
- Added a function to animate modals
- Added two factor authentication
- Added Gantt view to all projects
- Added missing privileges in the profiles
- Added new types of Inventory fields
- Added an option to change the default currency 


IMPROVED
- Compatibility with PHP 7.2
- Rebuilt a search engine for addresses
- Improved responsiveness
- Improved saving attachments
- Improved an installation wizard
- Improved checking of server configuration
- Improved tax information
- Improved compatibility to support mysqlnd
- Improved Travis
- Improved front end filters
- Improved 2FA authentication
- Improved validation in import from ZIP
- Improved responsiveness 
- Improved permissions after save
- Improved pagination
- Improved adding a task
- Improved in cron email template
- Improved TextParser
- Updated database structure
- Numerous updates to Bootstrap 4
- Changed the sequence of steps in the installation
- Optimized database
- Rebuilt address search engine


FIXED
- Fixed Time Control Widget
- Fixed clear history
- Fixed a problem with digital separator and digit grouping symbol
- Fixed editing and viewing the Calendar detail through calendar widget
- Fixed permissions in generating PDFs
- Fixed adding picklist values when adding new field
- Fixed a global search
- Fixed sharing permissions
- Fixed a bug modifying field visibility
- Fixed translations management
- Fixed importing and exporting of a language
- Fixed “Recurrence” field in Events
- Fixed deleting DAV accounts
- Fixed adding calendar record in widget
- Fixed updating of a currency symbol
- Fixed adding events in Reservations
- Fixed adding relation between Products and Pricelist
- Fixed some layout bugs while adding widgets from filters in the Admin panel
- Fixed exporting to PDF
- Fixed importing
- Fixed DAV integration
- Fixed many modals


REMOVED
- Removed unused code
- Removed divided charts
- Removed the action “mass activate users”
- Removed axis type chart

**Comment by cristyxx** [comment]
@mariuszkrzaczkowski @bpabiszczak @paula-w  Please update it on Softaculous.

Thanks !

**Comment by skramanzia** [comment]
Hi Team, great work!, please check this errors, i have a problem to fresh install and update too. #7451

**Comment by Tingfe** [comment]
Hi Team, How to upgrade 4.4RC2 to 4.4 Release？

**Comment by ldgbc** [comment]
@Tingfe I don't think you can. These update patch are for "Stable to Stable" only.

@paula-w lol I'm still an unverified email account. Enjoy your bounce email. I wonder what it is: @vovpff, @cltvchannel, @PercyP, @WalterLuis, @SkavenKF 

@YetiTeam Thank you! Congratulations guys. After so many complain we finally get to see v4.4. It too bad the wait for v4.5 and all new fixed going to be another 6 months+, any plan for a rapid release patching system? Looking forward to the XAMPP built for testing.

**Comment by kpaulaha** [comment]
3 new installations and 2 upgrades from 4.3 done on different servers, all seems ok after noticed the preistallation needed for upgrading, first try went to the dogs without it.

**Comment by KatarzynaUlichnowska** [comment]
@Tingfe We didn't test that but you can try - just change the version number to 4.3.0

@cristyxx We are in constant contact with Softaculous and testing their version. Soon, it will be also published.

@ldgbc We are going to publish smaller patches for major bugs and probably the first one will be released in a week. XAMPP will be also published soon.

**Comment by ldgbc** [comment]
@kpaulaha How long did your upgrade take? I tried it without the "Preinstalled" Patch because that sound like it for fresh installation only. It been about 5 minutes now for me. Maybe I should have enable Debug logs to see what happening.

**Comment by mariuszkrzaczkowski** [comment]
You must install in this order:
4.3.0_to_4.4.0_PreInstall.zip - a few seconds
4.3.0_to_4.4.0.zip - on the clean version on the local laptop about 200 seconds

**Comment by kpaulaha** [comment]
@ldgbc I have one old installation, from 1.xx.something. Last version 4.3. First the preinstallation took a few seconds, then update to 4.4 a few minutes. Did not notice the preinstallation on first try, so had to rollback to 4.3 and run the preinstallation first. Then ok.

**Comment by ldgbc** [comment]
@mariuszkrzaczkowski Going to try what Marius said here. Here the report for my first Attempt.
Made a copy of the XAMPP version. Use the Update feature: /index.php?parent=Settings&module=Updates&view=Index&block=14&fieldid=63
Probably after 10-15 it must have timed out. The page finally load again but I don't see the update successfully. Deleted that installation and made a new copy again. Open it up and trying the method described above with _PreInstall first.

I tried enabling log in php.ini but doesn't seem to work
Changed from ";display_errors" to "display_errors = On". Maybe I forgot to restart Apache.

Goods new is, about 5 minute later the page refreshed. But it looked weird, I saw this (forgot to screenshot) but there was no CSS. It was white background with massive lines of this: 

```
{"JS_UPDATED_MODULE":"Update Successful","JS_UPDATE_SUCCESSFULL":"Update Successful","JS_IMPORTED_MODULE":"Installation 

Successful","JS_IMPORT_SUCCESSFULL":"Installation Successful","JS_FOR_INSTALLATION":"for 

installation","JS_CLICK_HERE":"Click here","JS_ON":"On","JS_REMOVED_MODULE":"Removed 

module","JS_SPECIAL_CHARACTERS_NOT_ALLOWED":"Special characters like & < > ' \" : , are not 

allowed","JS_SUMMARY":"Summary","JS_LOADING_PLEASE_WAIT":"Loading, please wait.","JS_SELECTED_RECORDS":"Selected 

```
I guess that was the "display error?" or that just Update Note. But all those "Successful" word is a good sign. Crossed my finger, did a refresh on the home page and looking good so far. Widget was out of place but v4.4 let you drag and drop it anywhere (cool).

Open Contact and Account. Did some editing and notice this:
![issue - v4 40 update](https://user-images.githubusercontent.com/1805303/43637355-22b2ba78-9758-11e8-899f-c8b1b6cc0089.png)

That is so cool! It pretty much fixed this issue here for me: https://github.com/YetiForceCompany/YetiForceCRM/issues/7339
Just need to find out how to change some of that field.

But I find it weird, was it always there or did they added that "City/**Village**"

Now time to test and hope not bug is found and system doesn't break.

**Comment by mariuszkrzaczkowski** [comment]
Please, all problems with the new version and update for reporting in separate issues. This meaning makes work easier

@ldgbc 
Describe your problem so that we can analyze it,
in the new version we have added a new field to the contact and user image.

**Comment by PercyP** [comment]
I AM SO EXCITED!!! Away at the moment so internet access a bit of a problem. Cannot wait to install. Well done to all the Yetiforce team you have done an amazing job with a fantastic product. It is always worth the wait. Cannot wait to get stuck in!.

Want to do more to help in the community so will try to do that and learn more as I go. 

So thrilled and will let you know how my upgrade goes 👍

**Comment by Tingfe** [comment]
@KatarzynaUlichnowska Is there any plan to release 4.4RC2_to_4.4 update PKG?

**Comment by vovpff** [comment]
@Tingfe no. Update packages only from stable to stable version.

**Comment by ldgbc** [comment]
@Tingfe Did the rename trick work for you? that ie. change version from 4.4RC2 to 4.3 and update it?

**Comment by vovpff** [comment]
@ldgbc ha-ha

**Comment by ldgbc** [comment]
@vovpff  wasn't a joke. see: https://github.com/YetiForceCompany/YetiForceCRM/issues/7447#issuecomment-410200233

Also it the same trick back when we did update from v3.4 > v3.4RC(x) > v3.4. I wasn't here went it was 3.4 > v4.0 but I assume it is the same. Of course for safety and lower risk of breaking the system best not to update it like that.

Maybe it better to learn how to do a Pull Request and constantly keep update to date with the developer version. I suppose that my next goal. Pull commit that fixed some of the issue I'm having with v4.4.0 to my stable.

**Comment by Tingfe** [comment]
@ldgbc I tried that, but failed.

**Comment by ldgbc** [comment]
@Tingfe did you make the same mistake as I did? Used in a Live (production) server and not make any backup of it?

If there isn't much changed added to your database, best to just reset it with a fresh v4.4. Otherwise you are stuck I think.

**Comment by bpabiszczak** [comment]
It will not work. Requires programmer intervention.

**Comment by Tingfe** [comment]
@ldgbc I have backup files. Hope someone have a good solution.
one more thing, how to export and import "comments"?

**Comment by ldgbc** [comment]
@Tingfe I don't think you can export and import comments. Previously I copy/paste it which isn't ideal. Maybe it better to find where it is store in the MYSQL database and export and import from there. In term of solutions you just have to pay either Yetiforce or a programmer that can assist you. There is some quite knowledgeable members but they don't have time for free support.

@KatarzynaUlichnowska Is that XAMPP version still being worked on?

@paula-w Send an email but haven't heard anything. Not sure if I got spam filtered.

**Comment by mariuszkrzaczkowski** [comment]
@ldgbc 
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.4.0/xampp_YetiForceCRM-4.4.0-complete.zip

**Comment by paula-w** [comment]
@ldgbc We checked the inbox and the spam folder and we got no emails from you. Can you try again and CC @mariuszkrzaczkowski - m.krzaczkowski@yetiforce.com ?

**Comment by ldgbc** [comment]
@mariuszkrzaczkowski Thank you. Don't forget to post it here too: https://github.com/YetiForceCompany/YetiForceCRM/releases

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/44518888-c8121400-a6cb-11e8-9297-a52f107a2389.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski when update 4.3 to 4.4v3 will arrive?

**Comment by mariuszkrzaczkowski** [comment]
I do not know
