### ISSUE TITLE
Cannot configure My Mailbox - LBL_HANDLER_NOT_FOUND

### ISSUE THREAD

**Issue by mahomedh** [YetiForceCompany/YetiForceCRM#7450]
Hi

I hope someone can help or guide me in the right direction. I have done a new clean install of YetiCRM 4.4 on Ubuntu 18.04 with PHP 7.2.

I have cleared all critical System and Security Errors.

The issue I have is that when I got to Module Install > System Settings > My Mailbox > Module Configuration, I get the error LBL_HANDLER_NOT_FOUND.

Below is the output from errors.log

```
/var/www/html/yeticrm/cache/logs# tail -f errors.log 
E_ERROR: Uncaught Error: Call to a member function has() on null in /var/www/html/yeticrm/app/Cache.php:65
Stack trace:
#0 /var/www/html/yeticrm/app/Language.php(286): App\Cache::has('LanguageFiles', 'Other/Exception...')
#1 /var/www/html/yeticrm/app/Language.php(246): App\Language::loadLanguageFile(false, 'Other/Exception...')
#2 /var/www/html/yeticrm/vtlib/Vtiger/Functions.php(497): App\Language::translateSingleMod('E_WARNING: coun...', 'Other/Exception...')
#3 /var/www/html/yeticrm/app/ErrorHandler.php(77): vtlib\Functions::throwNewException('E_WARNING: coun...', false)
#4 /var/www/html/yeticrm/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_plugin_api.php(438): App\ErrorHandler::errorHandler(2, 'count(): Parame...', '/var/www/html/y...', 438, Array)
#5 /var/www/html/yeticrm/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_config.php(404): rcube_plugin_api->exec_hook('config_get', Array)
#6 /var/www/html/yeticrm/public_html/modules/OSSMail/roundcube/program/include/rcmail.php(99): in /var/www/html/yeticrm/app/Cache.php, line 65
#0  >>  App\ErrorHandler->fatalHandler()

```

Please could you let me know what I need to do to fix this? Let me know if you need any other files or logs.

Generated by YetiforceCRM ver. 4.4.0
PHP: 7.2.7-0ubuntu0.18.04.2

Server configuration errors:
output_buffering: 1

Issue occurs in Chrome and Firefox

p.s. apologies if this duplicates, the first one was logged through YetiForceCRM but it did not show up so posting from GitHub directly

![image](https://user-images.githubusercontent.com/8697001/43598501-bf587fe8-967c-11e8-80f8-abb4d98a7c99.png)
![image](https://user-images.githubusercontent.com/8697001/43598514-c5f5149c-967c-11e8-989c-d1899ea27120.png)
![image](https://user-images.githubusercontent.com/8697001/43598522-ca9f0f7a-967c-11e8-94d6-ba88f25efbd4.png)

**Comment by mahomedh** [comment]
I am not sure if this helps, but when I go to Virtual Desk > My Mailbox, I get a blank page and the following in the error log

```
E_WARNING: count(): Parameter must be an array or an object that implements Countable in /var/www/html/yeticrm/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_plugin_api.php, line 438
#0 public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_config.php (404)  >>  rcube_plugin_api->exec_hook('config_get',[plugins,array,array])
#1 public_html/modules/OSSMail/roundcube/program/include/rcmail.php (99)  >>  rcube_config->get('plugins',[])
#2 public_html/modules/OSSMail/roundcube/program/include/rcmail.php (79)  >>  rcmail->startup()
#3 public_html/modules/OSSMail/roundcube/index.php (43)  >>  rcmail->get_instance(0,NULL)
E_ERROR: Uncaught Error: Call to a member function has() on null in /var/www/html/yeticrm/app/Cache.php:65
Stack trace:
#0 /var/www/html/yeticrm/app/Language.php(286): App\Cache::has('LanguageFiles', 'Other/Exception...')
#1 /var/www/html/yeticrm/app/Language.php(246): App\Language::loadLanguageFile(false, 'Other/Exception...')
#2 /var/www/html/yeticrm/vtlib/Vtiger/Functions.php(497): App\Language::translateSingleMod('E_WARNING: coun...', 'Other/Exception...')
#3 /var/www/html/yeticrm/app/ErrorHandler.php(77): vtlib\Functions::throwNewException('E_WARNING: coun...', false)
#4 /var/www/html/yeticrm/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_plugin_api.php(438): App\ErrorHandler::errorHandler(2, 'count(): Parame...', '/var/www/html/y...', 438, Array)
#5 /var/www/html/yeticrm/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_config.php(404): rcube_plugin_api->exec_hook('config_get', Array)
#6 /var/www/html/yeticrm/public_html/modules/OSSMail/roundcube/program/include/rcmail.php(99): in /var/www/html/yeticrm/app/Cache.php, line 65
#0  >>  App\ErrorHandler->fatalHandler()
```

**Comment by mahomedh** [comment]
Hi

I see this is added to the 5.0 RC, but is there any chance of a workaround for 4.4? I really need to present this system to my directors by the end of today and getting this working would really help a lot please.

**Comment by mariuszkrzaczkowski** [comment]
We do not recommend php 7.2 for production yet, the same RC we use does not work for this version yet.
Check on php 7.1.x

**Comment by mariuszkrzaczkowski** [comment]
show full configuration verification, on the right side at the top there is a download button.
![image](https://user-images.githubusercontent.com/10198654/43636960-d9a9a880-9713-11e8-9827-a1398aa192e0.png)

**Comment by mariuszkrzaczkowski** [comment]
Please note that you have a lot of configuration errors which can cause a lot of problems

**Comment by mariuszkrzaczkowski** [comment]
you need to unify the configuration of apache with cli, because they can not differ

**Comment by vovpff** [comment]
@mariuszkrzaczkowski sorry for off-topic. What PHP version more preferable?

**Comment by mariuszkrzaczkowski** [comment]
for production is 7.1.x

**Comment by mahomedh** [comment]
I have done a completely fresh install again (new db, new web dir) and I have unified the config as much as possible. For some reason `output_buffering` and `OPcache` won't show correctly even though I have the following in both config files.

```
output_buffering = On
opcache.enable=1
```

Still trying to workout how to get php 7.1 back on the server.

![yetiforce_settings 1](https://user-images.githubusercontent.com/8697001/43648031-323c9a12-9731-11e8-9cba-18519ed10c19.png)

**Comment by mahomedh** [comment]
I have now installed php 7.1 but it has not resolved this issue. Screenshots below.

![image](https://user-images.githubusercontent.com/8697001/43651148-8151cbc4-9739-11e8-8c79-c64fc1127266.png)
![image](https://user-images.githubusercontent.com/8697001/43651155-84ff4d0a-9739-11e8-807e-73bc4a5b4e7e.png)
![yetiforce_settings 2](https://user-images.githubusercontent.com/8697001/43651170-8f268c1c-9739-11e8-9189-f39f59bd04b4.png)

**Comment by mariuszkrzaczkowski** [comment]
try to change in the URL from index to Index

**Comment by mahomedh** [comment]
Please could you be more specific?

When I change:
`http://yeticrm.cdc.local/index.php?module=OSSMail&parent=Settings&view=index&block=4&fieldid=`

to

`http://yeticrm.cdc.local/index.php?module=OSSMail&parent=Settings&view=Index&block=4&fieldid=`

it automatically redirects to the page with the lower case `view=index`. Changing `index.php` to `Index.php` just doesn't work

**Comment by mahomedh** [comment]
Wow! What a struggle this has been. 

Based on what you have said about changing index to Index, and the error message, I have created the following symlinks

In `/modules/OSSMail` I have run `ln -s views/ Views` then I was able to get the login page for RoundCube.

Then when I tried to login, I was getting `The krb5 extension is required for GSSAPI authentication` so I had to add `$config['imap_auth_type'] = LOGIN;`  to `config/modules/OSSMail.php`

I understand that these are workarounds and they should be removed before upgrade, but hopefully this means you can actually fix the issue?

**Comment by mariuszkrzaczkowski** [comment]
you have an incorrect URL should be like this
https://gitdeveloper.yetiforce.com/index.php?module=OSSMail&view=Index
without patent parameter

uncomment this line
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/OSSMail.php#L48

**Comment by mahomedh** [comment]
Interesting, I just managed to cause the same error on the gitdeveloper.yetiforce.com website. So this is definitely not something I am doing wrong.

![image](https://user-images.githubusercontent.com/8697001/43674234-a796f248-97c8-11e8-9089-c918252a77ca.png)

**Comment by mahomedh** [comment]
I have managed to fix the error in this screenshot

![image](https://user-images.githubusercontent.com/8697001/43674154-f12c14b2-97c6-11e8-8844-d45a6afd753f.png)

by creating the symlink that's in this screenshot

![image](https://user-images.githubusercontent.com/8697001/43674270-3eb27ae4-97c9-11e8-80a2-6b2eeaceb3f1.png)

This means that 4.4.0 must have a bug somewhere with using Views/views and Index/index in the URL

**Comment by mahomedh** [comment]
@mariuszkrzaczkowski do you still require more information?

**Comment by danielmalkmus** [comment]
Hi @alll!

Have a look at

> `'/modules/Settings/OSSMail/views/index.php'`

if the File is lowercase "index.php" rename it to "Index.php"

The Autoloader will then find the handler.

I have running YF 5.3 as an upgrade from 4.2. The filename was not changed. A fresh install from 5.3 
works.

Please let me know, if it helps!
