### ISSUE TITLE
Fresh Install 4.4.0

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#7451]
#### Issue

User Panel:
![image](https://user-images.githubusercontent.com/3030997/43617598-9b13358e-9699-11e8-8055-e3b0e4872174.png)

System Setting
![image](https://user-images.githubusercontent.com/3030997/43617605-a8127b46-9699-11e8-8d10-e9e0dab38ba4.png)

![image](https://user-images.githubusercontent.com/3030997/43617632-ea7e3060-9699-11e8-9e30-e1fc5d90c63f.png)

Add Invoice
When click to search Account

![image](https://user-images.githubusercontent.com/3030997/43617999-4951d810-969c-11e8-8e7c-a8f41fd9c6ed.png)

#### How to trigger the error

1. Login to YF
2. Click on System Setting and click in System Warnings for example

In Firefox, works ok.

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Latest Chrome
* Environment name and version: 
* Operating System and version:

**Comment by kpaulaha** [comment]
Works ok with all of mine 4 browsers.

**Comment by mariuszkrzaczkowski** [comment]
@skramanzia Remove the browser's cache, refer to the old code that no longer exists.

**Comment by skramanzia** [comment]
My Bad!.. thanks all!
