### ISSUE TITLE
[v4.4.0] Accounts Visual issue overlap Member of Count and Account Name

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7458]
#### Issue
Account's member of count overlap with Account Name.

#### Actual Behavior
Overlapping.

#### Expected Behavior
Shift the text to the right or move the numbers to the left.

#### How to trigger the error
1. Open Account.
2. Wait till it load the Module Count.
3. See image:
![issue - visual error](https://user-images.githubusercontent.com/1805303/43638335-c14c969c-975b-11e8-99b0-4467fab1c469.png)

#### Your Environment

* YetiForce Version used: v4.4.0
* Browser name and version: Firefox 61
* Environment name and version: YF Developer
* Operating System and version: YF Developer

**Comment by cltvchannel** [comment]
@ldgbc There is already a pull request for this issue.
See it here: https://github.com/YetiForceCompany/YetiForceCRM/pull/7453

**Comment by ldgbc** [comment]
@cltvchannel Thanks. Never checked that section until now. Closing.

**Comment by mariuszkrzaczkowski** [comment]
Fixed  #7453
