### ISSUE TITLE
[v.4.4.0] Product table missed in edit mode

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7469]
#### Issue

Logistics (IGRN, IGDN and etc) modules edit view GUI broken: Products tabla at the end of page missed.

Detail view:

![image](https://user-images.githubusercontent.com/8545791/43658109-8ec2b490-9760-11e8-8a8a-ea3ce7e16e64.png)

Edit view:

![image](https://user-images.githubusercontent.com/8545791/43658148-ad71122e-9760-11e8-960d-2e34a72da3d1.png)

Checked on dev: https://gitdeveloper.yetiforce.com/index.php?module=IIDN&view=Edit&record=2216. The same situation... Cry...

#### Actual Behavior

Not possible to edit product table

#### Expected Behavior

Product table editable

#### How to trigger the error

1. Open IGDN
2. Click edit
3. Try to find table at the end of page

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Chrome
* Environment name and version: 
* Operating System and version:

**Comment by cltvchannel** [comment]
I confirm issue, this is present on existing modules and also on new custom modules.

**Comment by vovpff** [comment]
@cltvchannel bug appears not in all modules. for example at my local system table appears in quotes and sales order module.
I can't check dev because 4.4.3 detail view and and edit view btoken at all now

**Comment by cltvchannel** [comment]
@vovpff Yes, bug not appear in al modules. But in logistic modules and in all new created modules.

**Comment by rtorrescodes** [comment]
Ok ok its fixed now, i really really thank you so much for this.  I love Yeticrm and now its 100% useful.  
By the way, im using 4.4 installed on cpanel softaculous.   You can close this issue and i'll work more active here to help somehow.  Thanks again.
