### ISSUE TITLE
[4.3 > 4.4] Update Issue XAMPP - Documents and User Contact is Missing

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7470]
#### Issue
After I update from v4.3 to v4.4 using the Patch, all User Contact Image seem to disappear. And 99% Documents and it relationship is gone. Anyone have the same issue? Could just be me.

#### Actual Behavior
Only two documents survived. Maybe cause it wasn't link to any relationship.

#### Expected Behavior
Documents and user contact image it still there.

#### Reference:
https://github.com/YetiForceCompany/YetiForceCRM/issues/7447#issuecomment-410208970

#### How to trigger the error
1. Upload User Contact image.
2. Mass add some Documents to a contact.
3. Admin Setting > Logs > Update > v4.3_4.4_Preinstall > v4.3_4.4.zip
4. Wait for install
5. Open User Contact image. It gone.
6. Open Documents. It gone too.

Going to check it more thoroughly for a 100% reproducible step.

#### Your Environment

* YetiForce Version used: v4.3 > v4.4
* Browser name and version: Firefox 61
* Environment name and version: XAMPP
* Operating System and version: Windows 7

**Comment by ldgbc** [comment]
Move this off-topic here:
-----

Off-topic: Did anyone else lose all their Contact Image after the update? All my Contact Image seem to be gone. 

All my documents is gone too. Only 2 document remains. So all Relation is gone also I think. Maybe because it was a XAMPP version and file is not store inside that folder? Hmm not sure what to do now, updating mean I have to re-link all my documents again.

Testing it on another system, I just notice the "CRON" thing, maybe that the issue? I forgot to check if CRON finish running, do I have to manually activate this if my CRON task isn't schedule yet?

Contact Image I can understand because it got converted from Single Image to Multi-Image field.

Seem like the OpenCage API is reset too. Need to enable it again.

**Comment by ldgbc** [comment]
Update: It seem like my original XAMPP folder, all the documents is all gone too. 

Where are the file store in the XAMPP version. This is bad.

**Comment by kpaulaha** [comment]
@ldgbc Just tested with one update, it seems to have kept all documents linked ok.

**Comment by ldgbc** [comment]
@kpaulaha on XAMPP? But I think my indexing is damaged when I did a Copy/Paste (Backup) of my XAMPP folder.

**Comment by kpaulaha** [comment]
@ldgbc Nix, on CentOS. Have one on XAMPP, but not had time to upgrade it yet.

**Comment by ldgbc** [comment]
Update: I mass added a test.txt file into Documents to see if it still working. After Adding the file, it refresh and all the file appear again.

Look like it was just hidden and out of sight or the index got rebuild. Will be closing this issue now.

Contact image is still gone though but those are easy to get since I didn't that that many.

**Comment by ldgbc** [comment]
Look like the error is back. I found out it is due to this error:

Anyone know how I can repair the Corrupt table?
`
 Fatal error: session_set_save_handler(): Session handler's function table is corrupt in \XAMPP\htdocs\app\Session.php on line 32`

Line 32:
`			\session_set_save_handler(static::$pool, true);`

**Comment by ldgbc** [comment]
I guess I will close this for now since it seem like an isolated issue. Eventually I hope to fix this issue:

`Fatal error: session_set_save_handler(): Session handler's function table is corrupt in \XAMPP\htdocs\app\Session.php on line 32`

Which seem to be crashing my APACHE.

**Comment by echemik** [comment]
If you change the document root (eg. server), and you cant download documents you should manually update path (I think its bug in YF 4.3).

`update vtiger_attachments set path = replace(path,'oldpartofpath','newpartofpath')`
