### ISSUE TITLE
[v4.4.0] Webservice api broken, needs documentation

### ISSUE THREAD

**Issue by noelhunter** [YetiForceCompany/YetiForceCRM#7472]
#### Issue

The webservice api cannot be configured, and cannot be accessed on a default 4.4.0 install with apache2

#### Actual Behavior

API cannot be called (404 errors), and Application account cannot be set

#### Expected Behavior

Calls to the webservice urls should work, and application account setting should work

#### How to trigger the error

1. Call the webservice URLs such as /api/webservice/Users/Login

2. Access Software configuration
Integration
Web service - Applications
System settings
and try to set an account

The error can be bypassed as follows:

1. Edit the .htaccess file, and change the rewrite rules that begin with RewriteRule ^webservice to RewriteRule ^api/webservice

2. Manually edit the w_yf_servers table, and enter the appropriate accounts_id from the vtiger_users table

3. Also, if needed, edit config/api.php and enable services

#### Your Environment

* YetiForce Version used:
4.4.0
* Browser name and version:
Firefox, Chrome
* Environment name and version:
* Operating System and version:
Ubuntu Server LTS 18

**Comment by KatarzynaUlichnowska** [comment]
Hello, could you send us the logs?

**Comment by noelhunter** [comment]
I didn't have yetiforce logging turned on.  It was a clean 4.4.0 install on a new virtual machine.  The .htaccess changes I needed were:

`<IfModule mod_rewrite.c>
        Options +FollowSymLinks
        RewriteEngine On
        RewriteRule ^favicon.ico layouts/basic/images/favicon.ico [L,NC]
        RewriteRule ^api/webservice/(.*)/(.*)/(.*)$ webservice.php?module=$1&action=$2&record=$3 [QSA,NC,L]
        RewriteRule ^api/webservice/(.*)/(.*)$ webservice.php?module=$1&action=$2 [QSA,NC,L]
        RewriteRule ^api/webservice/(.*)$ webservice.php?action=$1 [QSA,NC,L]
`

When I accessed to page at:

/index.php?module=WebserviceUsers&view=List&parent=Settings&block=5&fieldid=106

and tried to enter "User", the search would never complete, and values entered for user were not saved.  I manually edited the table w_yf_servers, and entered my account_id, and then the form and field worked. 

I hope that helps.  If someone else experiences this, maybe they will have logging turned on.

**Comment by TomaszQr** [comment]
I tested on stable version 4.4 and it work properly. 
You should call address http://yeti/webservice/Users/Login
Please check if mod_rewrite is enabled
screens 
![api](https://user-images.githubusercontent.com/14273211/48828498-26ed3500-ed70-11e8-8d6d-222f47040180.png)
