### ISSUE TITLE
Error during installation 

### ISSUE THREAD

**Issue by echemik** [YetiForceCompany/YetiForceCRM#7473]
#### Issue
Installation stops at the begining. Logs show error

#### Actual Behavior
Error in logs mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'yii\\base\\NotSupportedException' not found in /var/www/crm/vendor/yetiforce/yii2/db/Connection.php:827

#### Expected Behavior
Should install with no errors

#### How to trigger the error
Start Install

#### Your Environment
* YetiForce Version used: 4.4.0 LTS
* Browser name and version: Chrome 67
* Environment name and version: Apache 2.4, PHP 7.1
* Operating System and version: Debian GNU/Linux 8 (jessie)

Screens :

![screencapture-crmuser-netinteractive-pl-install-install-php-2018-08-05-11_08_46](https://user-images.githubusercontent.com/13561089/43684405-b11f5206-989f-11e8-94f0-b54c6caebe3e.png)

![screencapture-crmuser-netinteractive-pl-install-install-php-2018-08-05-11_11_18](https://user-images.githubusercontent.com/13561089/43684418-df90be36-989f-11e8-96b0-09643c90dae8.png)

**Comment by KatarzynaUlichnowska** [comment]
Hello, we need full logs, because the error message isn't enough.

**Comment by echemik** [comment]
Here is full logs, if I could record more please give me information how to get it.

[Tue Aug 07 16:42:13.983545 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'yii\\base\\NotSupportedException' not found in /home/crm/domains/crmuser.pl/vendor/yetiforce/yii2/db/Connection.php:827
[Tue Aug 07 16:42:13.983660 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: Stack trace:
[Tue Aug 07 16:42:13.983664 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: #0 /home/crm/domains/crmuser.pl/vendor/yetiforce/yii2/db/Connection.php(836): yii\\db\\Connection->getSchema()
[Tue Aug 07 16:42:13.983668 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: #1 /home/crm/domains/crmuser.pl/app/Db/Query.php(27): yii\\db\\Connection->getQueryBuilder()
[Tue Aug 07 16:42:13.983677 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: #2 /home/crm/domains/crmuser.pl/app/Db/Query.php(95): App\\Db\\Query->createCommand(Object(App\\Db))
[Tue Aug 07 16:42:13.983680 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: #3 /home/crm/domains/crmuser.pl/app/Company.php(36): App\\Db\\Query->one()
[Tue Aug 07 16:42:13.983684 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: #4 /home/crm/domains/crmuser.pl/app/Controller/View.php(162): App\\Company::getInstanceById()
[Tue Aug 07 16:42:13.983687 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: #5 /home/crm/domains/crmuser.pl/modules/Users/views/Login.php(35): App\\Controller\\View->preProcess(Object(App\\Request), false)
[Tue Aug 07 16:42:13.983690 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: #6 /home/crm/domains/crmuser.pl/include/main/WebUI.php(260): Users_Login_View->preProcess(Object(App\\Request))
[Tue Aug 07 16:42:13.983693 2018] [fcgid:warn] [pid 18460:tid 140113008903936] [client 79.187.156.229:56312] mod_fcgid: stderr: #7 /home/crm/domains/crmuser.pl/i in /home/crm/domains/crmuser.pl/vendor/yetiforce/yii2/db/Connection.php on line 827

**Comment by mariuszkrzaczkowski** [comment]
This error occurs when the installation hasn't been completed successfully. There must have been an error during the installation, you need to enable full logs during the installation.

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-uzytkownika/item/debugging

**Comment by rskrzypczak** [comment]
I'm closing this due to no answer.
