### ISSUE TITLE
[4.4.0] Advanced field - Reference

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7477]
#### Issue

As litted in new features here #7447 there are added some advanced additional fields.

Reference field can't be unfilled when save record. Looks like this field checked as mandatory by default but this is not so complecated for some reasons. Try to image 100 items invoice what need to fill all this reference. This field should have mandatory checkbox when created.

Uncomfortable.

**Comment by paula-w** [comment]
Can you provide us with some more details? Take some screenshots and let us know what's not working properly, please. Thanks!

**Comment by vovpff** [comment]
@paula-w record can't be saved if reference empty:

![ref_new](https://user-images.githubusercontent.com/8545791/45099851-f4e51300-b130-11e8-9b77-824197ded097.gif)

Let's see what happens if you already has advanced module records what contains a lot of products items per record and reference field just added:

![ref_old](https://user-images.githubusercontent.com/8545791/45100101-789eff80-b131-11e8-8c8b-ba192c42faa2.gif)

I think users stop work in this condition.

There are should be mandatory checkbox for reference field when field creating
