### ISSUE TITLE
Stuck in Installation in progress

### ISSUE THREAD

**Issue by saikatever** [YetiForceCompany/YetiForceCRM#7479]
#### Issue
Stuck in Installation in progress. Before installation i checked every requirements and also entered correct information. Please help. Thanks in advance.
Screenshot (https://user-images.githubusercontent.com/14279635/43687709-a05e20f2-98f7-11e8-8b59-8ff7af3f29c5.png)

#### My Environment
* YetiForce Version used: 4.4.0
* Browser name and version: Firefox Developer Edition 62.0b14 (64-bit)
* Operating System and version: Windows 10 64Bit

**Comment by echemik** [comment]
maybe this duplicate #7473

**Comment by saikatever** [comment]
@vovpff I'm using PHP Ver. 7.2
Screenshots : 
![fireshot capture 001 - cpanel - php selector i extensions_ - https___sln crystalregistry com_20](https://user-images.githubusercontent.com/14279635/43695593-3d57b1fc-9957-11e8-8c86-a4a4f2b66b00.png)

![fireshot capture 002 - cpanel - php selector i options_ - https___sln crystalregistry com_20](https://user-images.githubusercontent.com/14279635/43695605-453c832a-9957-11e8-8fa7-fc598910da14.png)

**Comment by vovpff** [comment]
@saikatever for first try to change php to 7.2 if possible to 7.1. Check all possible logs. Activate errors visibility in php.ini.
Do you have requirements page screenshot?

**Comment by saikatever** [comment]
@vovpff i don't have installarion requirements page screenshot. but as per you i will change php 7.2 to 7.1. After that i will take every screenshots and i will post here.

**Comment by mariuszkrzaczkowski** [comment]
Attach screenshots from verification of configuration

**Comment by mariuszkrzaczkowski** [comment]
Enable debugging and check every logs

**Comment by saikatever** [comment]
I'm tried to install again but same thing happened. Here are all screenshots :

![fireshot capture 012 - cpanel - php selector i options_ - https___sln crystalregistry com_20](https://user-images.githubusercontent.com/14279635/43987817-dd52bb02-9d44-11e8-8409-b5de614e1651.jpg)
![fireshot capture 004 - yetiforce - https___swtestserver tk_install_install php](https://user-images.githubusercontent.com/14279635/43987818-dd8b25d2-9d44-11e8-885f-5124906f9b18.jpg)
![fireshot capture 005 - yetiforce - https___swtestserver tk_install_install php](https://user-images.githubusercontent.com/14279635/43987819-de9df71a-9d44-11e8-9afd-853112c7eae9.jpg)
![fireshot capture 006 - yetiforce - https___swtestserver tk_install_install php](https://user-images.githubusercontent.com/14279635/43987820-deff9d58-9d44-11e8-9dde-24a38fa2b45e.jpg)
![fireshot capture 009 - yetiforce - https___swtestserver tk_install_install php](https://user-images.githubusercontent.com/14279635/43987822-df3638ea-9d44-11e8-934b-1a4613ed5acd.jpg)
![fireshot capture 010 - yetiforce - https___swtestserver tk_install_install php](https://user-images.githubusercontent.com/14279635/43987823-df6e5608-9d44-11e8-8843-9da305613959.jpg)
![fireshot capture 011 - cpanel - php selector i extensions_ - https___sln crystalregistry com_20](https://user-images.githubusercontent.com/14279635/43987824-dfa258c2-9d44-11e8-93fc-bbed14c48ada.jpg)

**Comment by TomaszQr** [comment]
You can find the answer to this error in logs, you need to enable system and PHP logs. 
It is also possible that the hosting is based on HDD disks that are very slow and php or apache/nginx settings don't allow for the installation.
You can install the system locally and then transfer the files and the database to hosting.
Another solution to this problem is our cloud offer as we perform the installation. If this doesn't meet your expactations, after two months you will be able to transfer the system and all data to another server
