### ISSUE TITLE
[PL] Szablony projektów - nie można stworzyć szablonu

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#748]
Po uzupełnieniu wszystkich pól i zapisaniu wracamy do listy szablonów gdzie w dalszym ciągu nie ma żadnego, który próbowało się stworzyć.
Testowane zarówno na własnej instalacji oraz na instalacji testowej test.yetiforce.com

**Comment by waran70** [comment]
Confirmed here too
