### ISSUE TITLE
[4.4.0] Relation Type: Many to Many vs Separation of Data [question]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7482]
#### Issue
/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&sourceModule=Contacts

With this page here, when you add Relation Type, there is 3 option.
(1) Many to Many
(2) Many to Many with Separation of Data
(3) Attachment

Does anyone know what the difference between the 3 (three) are? I don't see any different between Option (1) and (2). (3) didn't work for me so let ignore it for now.

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Firefox 61
* Environment name and version: XAMPP
* Operating System and version: XAMPP

**Comment by mariuszkrzaczkowski** [comment]
> (1) Many to Many

relationships are stored in one table for all modules

> (2) Many to Many with Separation of Data

relationships are stored in a separate table

> (3) Attachment

module of related documents

**Comment by waran70** [comment]
Marius, what is practical use between (1) and (2)?

**Comment by mariuszkrzaczkowski** [comment]
performance

**Comment by ldgbc** [comment]
I take it that (1) will be quicker for small sample set as everything is loaded. Whereas (2) for small scale will be slow but much faster in large scale as you don't need to load one giant (1) table but with (2) you only load table you need and it smaller size.
