### ISSUE TITLE
[4.4.3] Holiday Calendar Improvement - Repeatable Holiday

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7500]
#### Issue
Current Holiday system only allow for 1 single day. Which is rather pointless considering most holiday are Annual event with a few tweak such as "First of Month" or "2nd Monday of the Week", etc.

#### Actual Behavior
Holiday date is static.

#### Expected Behavior
Should be able to create re-accuring date.

#### How to trigger the error
1. https://gitdeveloper.yetiforce.com/index.php?module=PublicHoliday&view=Configuration&parent=Settings&block=12&fieldid=73
2. Add Holiday
3. Only option is choose a date and a name.
4. For example, should be able to add Christmas as 25/12/YYYY.
4a. Queen Birthdays, should be able to add as "2nd Monday June of YYYY)

#### Your Environment
* YetiForce Version used: 4.4.3
* Browser name and version: Firefox 61
* Environment name and version: YF
* Operating System and version: YF

**Comment by paula-w** [comment]
We're not planning to introduce any changes into this module for the time being. You can use our OpenCollective to donate towards a full time developer who is going to take care of GitHub issues like this one (more info on the collective's page): https://opencollective.com/yetiforcecrm
