### ISSUE TITLE
[ 4.3.0 ] How to do update.

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#7512]
I did first that
4.3.0_to_4.4.0_PreInstall.zip
then I receive error 500.
After removing everything and try install fresh install YetiForceCRM-4.4.0-complete.zip i still receive error 500

**Comment by SkavenKF** [comment]
which PHP Version does you use?

**Comment by mskoczek** [comment]
PHP
7.0.30-0+deb9u1
--

**Comment by SkavenKF** [comment]
You must use PHP 7.1.x (my server runs with 7.1.19, with 7.0.x i have many problems)

**Comment by mskoczek** [comment]
But manual still says PHP 7.0

**Comment by SkavenKF** [comment]
#6707
![grafik](https://user-images.githubusercontent.com/10259801/43738065-b536ae0a-99c3-11e8-8056-a03d5741aceb.png)

**Comment by mskoczek** [comment]
Mate, you just save me a lot of my time :)
Could you be so nice and check that #7471 
I try any options but still not working
