### ISSUE TITLE
Question - Reports in 4.4

### ISSUE THREAD

**Issue by skramanzia** [YetiForceCompany/YetiForceCRM#7513]
Hello team, in the current version the modules of the report were deleted, as announced.
In previous versions, I used the reports to send Excel reports on certain dates. How can I do it in the current version?

Thanks!

**Comment by SkavenKF** [comment]
We use the report module to send our management a current status overview by mail (excel) 2 times a week.
@YF: is there any planning for the new report module or an overview of the future functions?

**Comment by ldgbc** [comment]
Report will be returning in v4.5 or v5.0 (long way away). The replacement is the GANTT Chart module but not sure how it is use to do what you guys needing it to do. Haven't really explore that yet.

**Comment by bpabiszczak** [comment]
Good news. We have started building a report module.
