### ISSUE TITLE
Scheduling and sending newsletters question

### ISSUE THREAD

**Issue by DanVancPdx** [YetiForceCompany/YetiForceCRM#7515]
This is a question and a request to point me in the right direction.

I am evaluating Yetiforce to use as my new CRM.  But I have a critical functionality requirement that I can't seem to nail down.

Questions re: sending mass emails.
1) Can YetiForce send a newsletter using a template to 700 leads/contacts at once?  (note: I notice that leads and contacts are different... so does it require two different actions, or one?)
2) Can mass emails be scheduled to happen at a certain time.  Sometimes I choose emails to be sent at, for example, this coming Tuesday at 1am.
3) is there any tracking opened email capabilities when emails are opened? Where can I see these?

Thanks very much for those who answer, and I hope this helps others looking at YetiForce.

**Comment by ldgbc** [comment]
Hi @DanVancPdx I personally don't use email yet but from the look of it, yes you can send mass email out. But from memory it used CRON so it can't send all at once, it will need to run under a scheduled time.

Also your email host (unless it self host) might flag 700 as spam/hack and lock you out, so be careful with how many you send each time.

In term of tracking, how all email tracking work is using a cookies or hidden image to track it user. As for linking those tracking in Yetiforce I'm not sure if that possible. Maybe through a WEB API system.

**Comment by mgiammarco** [comment]
I would like to know if mail tracking is possible.
I can understand that Yetiforce documentation is very minimal. Resources are limited and are used for developing and not for documentation. Also if you make a good documentation nobody will pay for support. 
But at least you should put a complete features list on your website, updated reading comments on github.
Thanks, 
Mario

**Comment by paula-w** [comment]
1. You can send the email to as many people as you want, YetiForce doesn’t limit the number of emails you’re sending.
2. Right now scheduling is not available, all the mass emails are sent to a queue and wait until someone approves them to be sent.
3. You can’t currently do that using YetiForce.

We are planning to expand the marketing capabilities of the system and all the missing features will be added.

**Comment by deepyes02** [comment]
Hello, I want to switch from Hubspot to Yeti. I have downloaded but waiting for someone to answer these questions before I install.
1. Can Yeti Force (YF) be used to create contact form and newsletter sign up form in the website? If not, can it be at least used to collect contact form data and save it to the CRM like hubspot?
2. Can it send automated emails to clients when they fill up a contact form, or a newsletter sign up form?
3. Are website visitors activity tracked and updated in the CRM like Hubspot? For, eg, the page they visited, etc.
4. Can it used to send newsletters with personalised field. For e.g [Dear (customer name)] that can be customized from the database?

Looking forward to the answer. :-)

**Comment by mariuszkrzaczkowski** [comment]
1. yes, the API provides this option.  There is an example on github

2. yes, this is the workflow

3. No, you had to code using the API

4. yes, you can use any field value from the system to send emails

**Comment by deepyes02** [comment]
Hello Mariusz. Thank you for the information and bringing this amazing software to life. 

Deepesh Dhakal
