### ISSUE TITLE
[PL] Aktualizacja i instalacja modułów bezpośrednio z adresu URL

### ISSUE THREAD

**Issue by marcineqpol** [YetiForceCompany/YetiForceCRM#7516]
#### Issue
Propozycja do rozwoju: Umieszczenie w "instalacja modułów" możliwości instalowania modułów bezpośrednio z adresu URL.

#### Actual Behavior
Konieczne jest pobranie paczki i jej upload.

#### Expected Behavior
Można umieścić paczkę na serwerze i wpisać jej bezpośredni adres lub podać adres do konkretnego pakietu.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
ale po co? Skoro na chwilę obecną do YetiForce nie ma żadnych modułów [oprócz dwóch naszych], ponieważ system posiada setki funkcjonalności domyślnie wbudowanych.

Jaką to daje korzyść biznesową?

**Comment by marcineqpol** [comment]
Owszem, lecz chodziło mi np. o dogranie aktualizacji - gdy podnosiłem YF z 4.2 do 4.3 upload zajmował mi dużo czasu. Pomyślałem, że łatwiej byłoby wskazać bezpośredni adres  z którego ma YF pobrać sobie aktualizację, niż pobierać i uploadować na serwer.

**Comment by bpabiszczak** [comment]
Na pewno... szukając... można znaleźć korzyść.... ale ma to tak niski priorytet.... że nie planujemy tego nawet w odległej przyszłości.
