### ISSUE TITLE
[question] Adding a custom field

### ISSUE THREAD

**Issue by legroen** [YetiForceCompany/YetiForceCRM#7526]
Hello,

I have 2 questions concerning custom fields.

1. When adding a custom field I need to choose a table, I can only choose between vtiger_account and vtiger_accountcf. Is this expected behavior? I understand we need to select a table to save the actual data, but looking at the structure of this 2 tables,  they look to me that they have something todo with account info instead of custom fields. I would expect that you would have to choose a table related to the selected module.

2. When a custom field is created, do we need to manually add the field to the selected table or is this automatically done? When I create a custom field and I try to use it I get a sql error but maybe this is a bug/issue related to my first question.

thx

**Comment by legroen** [comment]
OK nevermind my second question, just saw that the custom fields are indeed created in the table of the selected module

**Comment by ldgbc** [comment]
The difference between the Basic and Advance seem to be Basic let you choose Field Name whereas Advance will automatic give it automatic field name, e.g. CF_2398 for example.

Just create a bunch of test field, refresh the module that you are testing and see how it behave. If you scare of littering your database, then use Stable/Developer build hosted by Yetiforce. Alternatively create a Development version.
