### ISSUE TITLE
[PL} Rozwój: wiele kont bankowych

### ISSUE THREAD

**Issue by marcineqpol** [YetiForceCompany/YetiForceCRM#7532]
#### Issue

YetiForce nie obsługuje wielu rachunków przy dodawaniu faktury sprzedażowej. Konieczność dopisywania numeru rachunku bankowego albo w szablonie albo w uwagach dokumentu - problem przy posiadaniu wielu numerów rachunków bankowych.

#### Actual Behavior

Konieczna zmiana numeru rachunku bankowego w szablonie PDF
#### Expected Behavior

Możliwość wybrania numeru rachunku bankowego w momencie przygotowania faktury - wystawienia faktury. Opcja domyślna ale i pole rozwijalne do wyboru.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 5.4.0
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
Obsługuje, ale na poziomie wydruku. Jak ktoś chce, może przygotować 3 szablony z różnymi kontami bankowymi. Może to rozbudować bardziej i uzależnić od wprowadzonych danych w rekordzie https://gitstable.yetiforce.com/index.php?parent=Settings&module=Companies&view=List&block=3&fieldid=14, ale wymaga to zaprogramowania.

Ogólnie koncepcja słuszna, lecz na chwilę obecną nie mamy tego w planach, ponieważ szablony rozwiązują większości osób ten problem.  Na pewno przy rozbudowanie części ERP, będzie to trzeba rozbudować. Niestety na chwilę obecną nie wiemy kiedy to nastąpi.
