### ISSUE TITLE
[PL] Przyporządkowanie wiadomości email / dokumentów do klienta

### ISSUE THREAD

**Issue by Kulas182** [YetiForceCompany/YetiForceCRM#754]
Poprzedni błąd zgłaszany przeze mnie dotyczący pobierania załączników został rozwiązany, jednak teraz pojawił się trochę inny.

Po przyporządkowaniu maila wchodzimy do zakładki konkretnego klienta, którego przesłany mail dotyczył. W widgecie "Emaile" widzimy, że ta wiadomość jest dostępna dla tego klienta, jednak w zakładkach po prawej stronie wciąż widnieje liczba 0 (gdy przejdziemy na nie jest pusto). Ten sam błąd dotyczy prawdopodobnie dokumentów.

Niestety na waszym demie nie ma zainstalowanej najnowszej wersji YF, dlatego screen z mojej instalacji.
![klient](https://cloud.githubusercontent.com/assets/1971239/7628127/657fe33c-fa1f-11e4-931a-d293549421d0.png)

**Comment by bpabiszczak** [comment]
Proszę o wywołanie tego na naszej wersji testowej https://test.yetiforce.com [została uaktualniona] ponieważ wszystko zależy co robiłeś ze swoim systemem. Zmienialiśmy logikę przechowywania informacji o powiązaniu, aby działało to po aktualizacji, należało uruchomić aktualizacje zawierającą skrypt przenoszący powiązanie z miejsca A do miejsca B.

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/2dad7a548ccfc9e837998ae1764bf318fc806770
