### ISSUE TITLE
[Question]How to enable/create product bundles

### ISSUE THREAD

**Issue by legroen** [YetiForceCompany/YetiForceCRM#7542]
How can I create product bundles? Vtiger has them and also the online dev version has them.

I installed 4.4.0 and 4.4.4 but in the product detail page I have only a products tab (Wich gives me an erro when I click on it) and no product bundles tab. 

Is it an option?

**Comment by vovpff** [comment]
@legroen sometimes dev version can be broken. This is normal condition because yeti crew work on system witout stops.  Try to install 4.4.0 ver and try it but I'm not sure what product bundles correct.

**Comment by TomaszQr** [comment]
@legroen In current version it work properly
![product_bundles](https://user-images.githubusercontent.com/14273211/48780013-26ee2600-ecd9-11e8-957c-a063b10e7313.gif)
