### ISSUE TITLE
[HELP] Calendar

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#755]
There may be more to describe the purpose of the button?

![calendar](https://cloud.githubusercontent.com/assets/1402355/7628481/4cb8c710-fa3d-11e4-94cc-018720f3fd72.JPG)
![calendar2](https://cloud.githubusercontent.com/assets/1402355/7628480/4cb88e4e-fa3d-11e4-9e24-ba8709bd1460.JPG)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
this button is used to switch between things that wait for processing and things that are completed. The same button can be seen in widgets for organizations and opportunities.
