### ISSUE TITLE
In my Automation->Cron section right top it show Last start:  49 years 3 months ago Total time:  0s & not send mail on ticket creation

### ISSUE THREAD

**Issue by rrajan94** [YetiForceCompany/YetiForceCRM#7552]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@rrajan94 Are you enbled CRON?

**Comment by rrajan94** [comment]
how to do this?

**Comment by rrajan94** [comment]
![opera snapshot_2018-08-08_134027_trikon anaxus net](https://user-images.githubusercontent.com/25589618/43824891-e1117584-9b10-11e8-94b3-993b79b14cf8.png)

**Comment by vovpff** [comment]
@rrajan94 https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

You need to put into CRON command correct php path

**Comment by rrajan94** [comment]
will you please tell me that command and path.

**Comment by rrajan94** [comment]
Actually i don't know where to write this code and how to execute in cpanel file manager...

Add a file to the crontab, e.g. in such format: */5 * * * * sh /var/www/crm/cron/vtigercron.sh &>/var/www/crm/cache/logs/cron.log [pay attention to a correct path to the YetiForce system]. 
Change file permissions /var/www/crm/cron/vtigercron.sh to 775 [or to other permissions that are compatible with an internal security policy in a company]. 
Set a path in the file /var/www/crm/cron/vtigercron.sh to PHP: export USE_PHP=/usr/local/php56/bin/php [here it is also required to pay attention to the file, because it can be located differently on each server and also keep an eye on a path to PHP that is different for various servers. An administrator can provide information about this path or it can be checked in phpinfo].

**Comment by vovpff** [comment]
@rrajan94 I think you can find all this information from your hoster.

**Comment by ldgbc** [comment]
CRON is relatively a universal thing, you can probably find a Video showing you how to do it if it easier. I also wrote about how I go about enabling CRON last year if you want to dig through Yetiforce issue.

Best just watch a video.

**Comment by arek1-618** [comment]
Hello sir,
Could you show log file 'cron.log' ? It would be very helpful to solve your problem.

**Comment by rrajan94** [comment]
I didn't find the cron.log file. This file is doesn't exist in my panel

**Comment by arek1-618** [comment]
It seems that cron is not configured correctly. Our documentation has changed, please follow the instructions.
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron
I hope it will help.

**Comment by rrajan94** [comment]
https://gitdeveloper.yetiforce.com/cron.php?app_key=xxxx,

after replace the xxxx with my key nothing is happen.

**Comment by mariuszkrzaczkowski** [comment]
You haven't provided required info. Please add it or we will close the issue.
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/44026786-8883522e-9ef4-11e8-9fcd-98723b33cf62.jpg)
