### ISSUE TITLE
Filters not working in v 4.4?

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/YetiForceCRM#7559]
YetiForce Version used: 4.4 v2
Browser name and version: Chrome / Safari
Environment name and version: PHP 7.1 and tested 7.2 too
Operating System and version: Linux Ubuntu 14 LTS

We just upgraded our dev and live site from 4.3 to 4.4 v2 and (contact) filters no longer react. We also lost the option to create/modify them.

Are they working for everybody or is this not only our issue?

**Comment by vovpff** [comment]
@zebrahosting on my system [4.3 to 4.4] filters works without any troubles.
Check user permissions. There are a lot of updates for permissions was implemented in this update.

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/43834827-e5474314-9b0f-11e8-9409-66a7b75fec17.png)

**Comment by zebrahosting** [comment]
Clearing the browser cache solved the filter issue
