### ISSUE TITLE
[4.4.0 & 4.4.6][Widgets] The Click event of the Save button doesn't work in the creation of a chart on the dashboard

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#7563]
##### Developer ver.
![2018-08-08_12-21-49](https://user-images.githubusercontent.com/18419851/43834465-1a182234-9b06-11e8-8d12-4a91d96e37f6.gif)

##### Stable ver.
![2018-08-08_12-26-28](https://user-images.githubusercontent.com/18419851/43834569-6bdfd742-9b06-11e8-813e-0dc637847781.gif)

#### Your Environment

* YetiForce Version used: 4.4.0 and 4.4.6
* Browser name and version: Firefox and Chrome
* Environment name and version: gitstable.yetiforce.com && gitdeveloper.yetiforce.com
* Operating System and version: gitstable.yetiforce.com && gitdeveloper.yetiforce.com

**Comment by TomaszQr** [comment]
Fixed via https://github.com/YetiForceCompany/YetiForceCRM/commit/256729cab0f59306a2289e07dddaf061d545e390

**Comment by liviubbo** [comment]
Thanks for the fix ! It`s working perfectly !
