### ISSUE TITLE
[Question] Is there any way to send invitations when an event is created

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#7589]
#### Actual Behavior

I would like to know if there is any way when you create an event and the notification is enable, an email with a .ICS file would be attached in order to the person who receives the email be able to accept or decline.

Currently when the workflow "send invitation" is enabled, it just send an email to notify but it doesn't allow to accept or decline and also it wont be on the calendar of the person who receives the invitation

#### Expected Behavior

To be able to send an .ICS file on V4.4.0 in order to accept or decline events invitations

#### Your Environment

* YetiForce Version used: v4.4.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

**Comment by rskrzypczak** [comment]
The developer version includes the option to send .ics invitations, however, there is not option to send them automatically; thought it wouldn't take too long to add it. There is also no accept/decline option for the invitation.
Version 4.4 is no longer supported, so I would recommend updating to the latest version that will be out very soon.
![ics](https://user-images.githubusercontent.com/10221999/97575812-96084500-19ed-11eb-879f-4c49b8258246.gif)

I'm closing this issue as there isn't much more to say in this matter.
