### ISSUE TITLE
[Improvement] Quotes end Calculations

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#76]
In calculations and quotes a selection unit of products and services, you must add a mapping units and the possibility of change

**Comment by waw555** [comment]
Again raises the question of adding units in the proposals, invoices, and so on. D.

**Comment by bpabiszczak** [comment]
I don’t understand why someone would like to change units in proposals or invoices. A unit of measure (if I understand correctly) is a permanent element of products/services. The selection of such units should be done in Products/Services, but not in documents. Currently, this field exists in Products (it will be improved from a business point of view).

**Comment by waw555** [comment]
Depending on the company, there is need for the same goods measured in units. m2 and, on this basis, for goods appears 2 identical items in the piece. and m2, while creating business proposals, there is no way to understand what unit installed until Print as PDF

**Comment by waw555** [comment]
Please add to version 2.0 display units !!!

**Comment by eptapsyxos** [comment]
Please bring yetiforce UI to 2015!
I mean to be mobile ready..bootsraps nice themes!
Make it clear and simple!
Its so powerfull and promising and tone of coding
but too much complicating even for people familiar with crm's....

see this guys what amazing work they ve done to vtiger customer portal
http://demo.makeyourcloud.com/myc-customer-portal/

Colloborate with them!

Stabilize the version and please give attention to ui!

thank you very much!

**Comment by bpabiszczak** [comment]
1. One problem/question – one issue. Please don’t mix different issues, if this reply is insufficient, create a new issue. 
2. Our Customer Portal is based on MYC, there is info about it in the portal, have you been there?: https://github.com/YetiForceCompany/YetiForcePortal 
3. They don’t want to cooperate, we sent them many remarks and security bugs but they ignored them. If we notice anything interesting there, we will introduce it in our portal, too.
4. I suppose that their template will work on our version, but you won’t know until you check it ;]

**Comment by eptapsyxos** [comment]
bpabiszczak sorry i didnt notice that i post in another issue/request 

Anyway

Thank you very much for your response!
have a nice day there
