### ISSUE TITLE
Deploying to the cloud such as heroku or google cloud

### ISSUE THREAD

**Issue by RRHalley** [YetiForceCompany/YetiForceCRM#7610]
Has anyone attempted to deploy this product to heroku or google cloud? If so how was this achieved.

I've tried with heroku and have had no success , it takes me through the install process and just eventually starts over which i assume to be a timeout.

**Comment by ldgbc** [comment]
Sorry, haven't tried it yet. Yetiforce don't play well with Shared Hosting (due to restriction on Server Control and your webhoster will lose that money).

See if you can make your server setting matches with Yetiforce setting, if you can't then it no good, you can't use Yetiforce.

**Comment by bpabiszczak** [comment]
We recommend a server over which you have full control, eg VPS
