### ISSUE TITLE
SMTP issue/bug/ My Error :(

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#7612]
Hi. Could I ask for help? I don't know if that is my mistake or bug/issue.
From 3 days I try to send out an email by Yetiforce module My Mailbox. With no effect. Today I manage to send email but with SMTP port 25, not SSL 587. Below i provide print screen and configuration.

**Configure outgoing mail servers**

Name | Siły Natury
-- | --
Mailer type | mail
Default | Yes
Host | mail.sily-natury.pl
Port | 587
Authentication | No
User name | kontakt
Password | ********************
Individual delivery | No
Safety protocol | ssl
Individual delivery | No
Sender name | Siły Natury
Sender email | kontakt@sily-natury.pl
Reply to |  
Additional parameters |  
Do you want to save a sent email? | No

**Roundcube configuration**
Name Siły Natury
Validate certificate  - no

Add type and protocol to address - yes

*Name of IMAP server  - mail.sily-natury.pl
*Port used to connect to  - IMAP 143
*Name of SMTP server - mail.sily-natury.pl
*Login to SMTP server ("%u" - login of logged in user) - %u
*Password to SMTP server ("%p" - password of logged in user) - %p
*SMTP port (default 25; 465 for SSL; 587) - 587
*Language (RFC 1766 code): en_US, pl_PL

Domain (automatically added to login) - sily-natury.pl
*Logo

/images/null.png
Check IP address of client while giving authorization - no

*Lifetime of session in minutes 30

PHP 7.1.20
YetiForce 4.4.0
Chrome
Debian 4.9.110-1
![smtp config 25](https://user-images.githubusercontent.com/40525437/43929889-11b9c8c2-9c37-11e8-9158-704eba426a9a.jpg)
![smtp config 587](https://user-images.githubusercontent.com/40525437/43929899-1eef0624-9c37-11e8-9587-7128d3abeb68.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Turn on the log and see what is wrong
https://github.com/YetiForceCompany/YetiForceCRM/blob/147bce72b2eaa4b51cac1ec9eba1335079ee1973/config/debug.php#L86-L87

https://github.com/YetiForceCompany/YetiForceCRM/blob/147bce72b2eaa4b51cac1ec9eba1335079ee1973/config/debug.php#L98-L99

**Comment by PercyP** [comment]
Hi,

my settings are slightly different but they do work. These are my SMTP:

Name * mysite
Mailer type SMTP
Default
Host mysite.com
Port 465
Authentication Yes
User name admin@mysite.com
Password ••••••••
Individual delivery 
Safety protocol ssl
Sender name mysite
Sender email admin@mysite.com
Reply to admin@mysite.com
Additional parameters 

And these are Roundcube:

Name mysite
Validate certificate
Add type and protocol to address Yes
Name of IMAP server ssl://imap.mysite.com
Port used to connect to IMAP 993
Name of SMTP server ssl://smtp.mysite.com
Login to SMTP server ("%u" - login of logged in user) %u
Password to SMTP server ("%p" - password of logged in user) %p
SMTP port (default 25; 465 for SSL; 587) 465
Language (RFC 1766 code): en_US, pl_PL
Domain (automatically added to login) mysite.com
Logo /images/null.png
Check IP address of client while giving authorization
Spell check module yes
Level of access to identity
Lifetime of session in minutes 60

Maybe give the above a try and see how it goes?

**Comment by mskoczek** [comment]
I cannot swich on 

**Mailer type SMTP**

**Comment by PercyP** [comment]
Maybe you need to switch on the option to use SMTP on your server? Contact your host provider to see if they can can make sure it is enabled. 

I don't know if that is the correct answer but work asking

**Comment by mariuszkrzaczkowski** [comment]
Turn on the logs and you'll know why it does not work

**Comment by mskoczek** [comment]
**office/cache/logs**
[errors.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2281291/errors.txt)


**debug.php**
[debug.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2281287/debug.txt)
