### ISSUE TITLE
Picklist relations - ability to only show the related values when the parent item is selected

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#7615]
Hi,

I have a picklist that for example contains Fruit and Veg. If i click on Fruit it filters the associated picklist and shows apples, pears, bananas etc. If I select Veg is shows potatoes, carrots, cabbage etc. 

If I don't first select either Fruit or Veg it will display all fruit and veg in the associated list. 

What should ideally happen is that the related list (containing all fruit and veg) should be empty and not selectable (maybe even hidden) until the choice has been made from the first picklist (i.e. Fruit or Veg).

I don't believe it is possible to do in the current yetiforce version so would like to put it forward as a feature request (maybe others would find it useful too?)

Kind regards

Chris

**Comment by ldgbc** [comment]
Need some screenshot, as I'm having difficulties understanding it however I get the idea of it. Haven't touched the Related Picklist feature yet so I haven't run into this problem but in future I'll be using related field.

What stop me from using it is due to longer loading.

**Comment by TomaszQr** [comment]
Fixed via https://github.com/YetiForceCompany/YetiForceCRM/commit/e94118aa0a45c7ce34dc8aad0efc77b6271b6dec
