### ISSUE TITLE
Custom modules: unable to extract zip file.

### ISSUE THREAD

**Issue by KrishnaPB** [YetiForceCompany/YetiForceCRM#7618]
Dear Team, I am unable to properly extract the custom module created by using module builder. I am getting error and i have attached in the sreenshot. I have tested in both inhouse installation and your installation at https://gitdeveloper.yetiforce.com/. Please help me to resolve this.
![force](https://user-images.githubusercontent.com/11535185/43948343-3598df00-9ca8-11e8-90c0-025071a77be6.png)

Also, I have issue with the TAX. I need to add 3 TAX coloumn as CGST,SGST and IGST instead of TAX. How can I achieve this.

**Comment by vovpff** [comment]
@KrishnaPB what module builder you mean?

**Comment by mariuszkrzaczkowski** [comment]
Give more details about how you created the module, what data, etc.

**Comment by KrishnaPB** [comment]
Data is for delivery note. I have created module using module builder in yatiforce.

Also, I have issue with the TAX. I need to add 3 TAX coloumn as CGST,SGST and IGST instead of TAX. How can I achieve this. Kindly help on this.

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/7629
