### ISSUE TITLE
Doesn't send Portal Password

### ISSUE THREAD

**Issue by vjstyla** [YetiForceCompany/YetiForceCRM#762]
I have created the contact and the crm did send me the Id but not the pass...

The password line is empty...please help

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/ideas,-changes,-bugs/bugs/126-how-to-report-bugs.html

1. What version of CRM?
2. What version of the portal client?

**Comment by vjstyla** [comment]
Hi,

CRM is ver. 1.3.0 RC
Portal version' => "6.0.1 (found in portal.php)

**Comment by bpabiszczak** [comment]
Upgrade to 1.4 [and then to 1.5]. In version 1.4 we fixed this error.
There is no such version of the portal, from where you downloaded it?

**Comment by vjstyla** [comment]
I downloaded the zip file from Github and intalled its says 1.4....where I can get the copy of 1.5 ?

Also the final Portal files?
