### ISSUE TITLE
Where are the field tool tips? Version 4.4

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#7623]
Hi,

where are the field tooltips now in version 4.4? They used to be in the Language area but all I can see is the language edit and Statistics.

Kind regards

**Comment by PercyP** [comment]
Aha! Found it. Now in the field editor - much better!

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/43960320-ec33198e-9cb1-11e8-8c71-84a13722491d.png)
