### ISSUE TITLE
unable to link email to accounts or contacts in mail scan.

### ISSUE THREAD

**Issue by frankhzp** [YetiForceCompany/YetiForceCRM#7624]
#### Actual Behavior
 unable to link email to accounts or contacts.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: gitdeveloper
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by frankhzp** [comment]
Mail scanner can be implemented and email can be downloaded ,but email can not link to accounts or contact automaticly.

**Comment by PercyP** [comment]
Hi,
have you set up the Email -Scanner in the Settings area? You have to create the folders and select the actions and attach them to the user that you logged in as (you need to have logged in once to do this).

**Comment by frankhzp** [comment]
yes , I am sure i set them correctly.

**Comment by frankhzp** [comment]
I tested on the Gitdeveloper version : Add an acount with email address. then through that email address send an email to yetiforcetest@gmail.com   , then run mail scanner , the email was downloaded but not linked to the created account.

**Comment by mattscooter** [comment]
Hi,
I am currently trying to setup a new installation with v4.4 and am experiencing the same issue.  
Emails are setup and being picked up and can be seen in the "corporate emails" list but they are not being allocated to accounts or contacts or leads. 

My config in the mail-scanner is:

![image](https://user-images.githubusercontent.com/16009490/45275910-cab19d80-b502-11e8-82e8-4a49f96246e9.png)

Is there any update on this?

**Comment by rskrzypczak** [comment]
It works but you have to set in configuration which mail fields should be used for searching for relations.
![image](https://user-images.githubusercontent.com/10221999/49015360-20e9c080-f183-11e8-81a2-5e867625db87.png)
