### ISSUE TITLE
YetiForce Cron problem

### ISSUE THREAD

**Issue by rrajan94** [YetiForceCompany/YetiForceCRM#7627]
![opera snapshot_2018-08-11_162844_trikon anaxus net](https://user-images.githubusercontent.com/25589618/43991173-b56c575c-9d84-11e8-81fc-42013f3c1089.png)
How to resolve this issue ??

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron
