### ISSUE TITLE
[BUG][PL] Sortowanie produtów błąd podczas sortowania

### ISSUE THREAD

**Issue by konadrian** [YetiForceCompany/YetiForceCRM#763]
W produktach i usługach w module kontrahenci po dodaniu rekordu do bloku gdzie mogę dodawać rekordy i kliknięciu na strzałke w celu sortowania? Dostaję błąd js.
"TypeError: this.loadRelatedList(...) is undefined"
![Error](https://cloud.githubusercontent.com/assets/3193498/7631524/9c8084c6-fa43-11e4-8bcc-2370ba9e64d4.png)

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/commit/01c0cf49d992b70eecc11fbb757f53bcc1b35e4d
