### ISSUE TITLE
Indian TAX CGST, SGST and IGST

### ISSUE THREAD

**Issue by KrishnaPB** [YetiForceCompany/YetiForceCRM#7639]
#### Issue
I have issue with the TAX. I need to add 3 TAX column as CGST,SGST and IGST instead of TAX. How can I achieve this. I have tried, in latest version 4.4.0 but unable to get this. Kindly help me on this.

**Comment by KrishnaPB** [comment]
Dear Team, Kindly update on this matter.

**Comment by KrishnaPB** [comment]
Dear Team,

I have attached 3 images. 
1. scst_cgst
2. igst
3. yatiforce tax screenshot.
Fro example, if I done quote/invoice/sales order etc for all modules I should be able to configure the Indian GST tax. At the moment I am unable to add the tax as I am only able to select single tax at the moment as shown in the 3rd image. In this image you can see the tax structure. There instead of TAX, I should be able to bifurcate TAX to SGST, CGST and IGST.   In the PDF file I should be able to get the result as shown in the images explained in the 1 and 2.

![sgst_cgst](https://user-images.githubusercontent.com/11535185/44200455-3868e480-a164-11e8-88db-4f213dd9e1a9.png)

![igst](https://user-images.githubusercontent.com/11535185/44200453-3868e480-a164-11e8-8b91-e995304e35d6.png)

![3rd image](https://user-images.githubusercontent.com/11535185/44200452-3868e480-a164-11e8-9d4e-5e89132acece.png)

**Comment by vovpff** [comment]
@KrishnaPB I'm not sure what you looking for this https://gitdeveloper.yetiforce.com/index.php?module=Inventory&parent=Settings&view=Taxes&block=11&fieldid=90 but let's try!

**Comment by KrishnaPB** [comment]
Yes that only, but while selecting I am able to select only 1 tax structure as in the attached screenshot. Where I should be able to select multiple tax and able to see the calculation of that TAX with the TAX name. Tax name also should be appear.
Images.
1. Tax selection issue.
2. Name of the tax is not appear.

![yati_tax](https://user-images.githubusercontent.com/11535185/44202510-ce533e00-a169-11e8-8569-e737298b26b2.png)

![tax_name_not seen](https://user-images.githubusercontent.com/11535185/44202458-a663da80-a169-11e8-92c2-78075c5848a1.png)

**Comment by KrishnaPB** [comment]
Also, should be able to select bifurcated tax in PDF. So that we can properly design the templates for invoice, sales order, quotes etc.

**Comment by vovpff** [comment]
@KrishnaPB what about custom tax(line under IGST on your screenshot)?

**Comment by KrishnaPB** [comment]
This is good to having all taxes added over custom tax also. If the above my query is corrected then it's fine. However if you solved in custom tax as well so we have more flexibility in the software.

**Comment by vovpff** [comment]
@KrishnaPB I don't have ideas

**Comment by KrishnaPB** [comment]
Dear Team,

Any one from team help on this.

@mariuszkrzaczkowski and @bpabiszczak

**Comment by paula-w** [comment]
Hi @KrishnaPB 
How urgent is this matter? If it's very urgent and you need it asap then we can do it but we will have to charge for it.
If you can wait a couple of weeks then we can implement this for you for free.

**Comment by KrishnaPB** [comment]
Yes I wait for couple of weeks.

**Comment by KrishnaPB** [comment]
Dear Team,
Any update on this?

**Comment by bpabiszczak** [comment]
No

**Comment by KrishnaPB** [comment]
Hi @paula-w is there any update from your end?

**Comment by KrishnaPB** [comment]
Dear Team,

Please update on this matter

**Comment by KrishnaPB** [comment]
Dear Team,

Kindly help on this matter.

**Comment by bpabiszczak** [comment]
You must be patient

**Comment by KrishnaPB** [comment]
sure

**Comment by KrishnaPB** [comment]
Dear Team,

Any update on this?

**Comment by KrishnaPB** [comment]
any update on this?

**Comment by z0lo13** [comment]
It is more than a year passed, and you promised @KrishnaPB to do it in a couple of weeks

**Comment by paula-w** [comment]
this is @bpabiszczak 's response
We're sorry but we won't be able to implement this functionality due to the lack of time.
It will have to wait until a client orders this functionality from us or enough money is collected on Opencollective.

**Comment by mansooraliph** [comment]
Hi Team, 

Any update on this?

**Comment by shekharsaad** [comment]
We really need a pdf invoice xml format to be make quotes and invoices

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/marketplace/wsparcie-development

**Comment by TonyM15** [comment]
>It will have to wait until a client orders this functionality from us or enough money is collected on Opencollective.

My advice is you guys stop begging for money. We all understand money is essential, but believe me, your way makes more damage than you would be expecting. It is unprofessional and shallow in terms of common sense and business logic standing. 
If you want to encourage individuals to share some money, do it off the public space to avoid comments like this one.
As I care of you guys as developers (no, not marketing/diplomacy specialists at all) please be aware that bullying my comment would be another mistake in terms of what has been said above.
One more note: If I pay for developing some stuff like in this thread, I wouldn't be happy if other chaps using it for free. So please stop giving somebody cash for free, as this is another brilliant statement making you look poor in mind.

No hard feelings please, Love & Peace!

**Comment by panchtatvam** [comment]
Is multiple tax addition possible in YetiForce now ?

**Comment by mariuszkrzaczkowski** [comment]
yes https://gitdeveloper.yetiforce.com/index.php?module=Inventory&parent=Settings&view=TaxConfiguration
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/10198654/dc61b276-6af1-4fa8-8a10-b6b2f8954b16)

**Comment by panchtatvam** [comment]
Great !

Is this available in stable release ?

**Comment by panchtatvam** [comment]
Please ignore the last comment. I found it in [stable release](https://gitstable.yetiforce.com/index.php?module=Inventory&parent=Settings&view=TaxConfiguration) as well.
Will test this out.
Thank you YetiForce team for this integration.
