### ISSUE TITLE
Klonowanie modułu / Export modułu

### ISSUE THREAD

**Issue by piotr-siedlak** [YetiForceCompany/YetiForceCRM#7641]
#### Issue

Czy jest możliwość exportu wbudowanych modułów bądź jego klonowanie.
Chodzi o moduł Faktur, niestety nie zostały przewidziane faktury zaliczkowe a potrzebuję taki moduł doinstalować idealnie by było skopiować moduł faktur sprzedażowych lub proforma

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by bpabiszczak** [comment]
Można sobie zbudować, można sobie dograć, można zlecić stworzenie takiego modułu. Nawet jeżeli moglibyśmy moduł wyeksportować [a można to zrobić, tylko domyślnie jest to wyłączone o ile dobrze pamiętam] to i tak nie moglibyśmy go zaimportować bez korekty w wielu miejscach a to wymaga wiedzy programistycznej. Prościej stworzyć własny moduł. 

Zresztą dodanie modułu wymaga stworzenia relacji, stworzenia pól sumujących itd. W przyszłości dodamy faktury zaliczkowe do systemu, ale daty nie znamy.
