### ISSUE TITLE
Cron problem

### ISSUE THREAD

**Issue by piotr-siedlak** [YetiForceCompany/YetiForceCRM#7642]
#### Issue

Po aktualizacji i przełączeniu wersji php na wersję 7.1 nie mogę uruchomić crone.

Przy wywołaniu cron.sh otrzymuję następujący błąd:
PHP Fatal error:  Can't use function return value in write context in /home/users/xxzzyy/public_html/xxzzyy/include/main/WebUI.php on line 154

Fatal error: Can't use function return value in write context in /home/users/xxzzyy/public_html/xxzzyy/include/main/WebUI.php on line 154

Zawartość pliku cron.sh
export CRM_ROOT_DIR=`dirname "$0"`/..
export USE_PHP=php
#export USE_PHP=`/usr/multiphp/php7.1/bin/php`
#export USE_PHP=/usr/local/php56/bin/php56

cd $CRM_ROOT_DIR
# TO RUN ALL CORN JOBS
$USE_PHP cron.php

Po zmianie pliku cron.sh:
export CRM_ROOT_DIR=`dirname "$0"`/..
#export USE_PHP=php
export USE_PHP=`/usr/multiphp/php7.1/bin/php`
#export USE_PHP=/usr/local/php56/bin/php56

cd $CRM_ROOT_DIR
# TO RUN ALL CORN JOBS
$USE_PHP cron.php

Wykonanie polecenia ./cron.sh nie daje żadnego rezultatu (zawiesza się)

#### How to trigger the error

1. Wywołanie wykonania pliku: ./cron.sh
2.
3.

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Chrome/Safari
* Environment name and version: Kei hosting
* Operating System and version: php 7.1.13, apache

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/44032415-5547a24e-9f07-11e8-86c5-5d0f099e8b90.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Ostatnio zaktualizowaliśmy artykuł opisujący uruchomienie crona proszę spróbować tak jak tam jest opisane https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-administratora/item/uruchamianie-crona
