### ISSUE TITLE
REST API Webservice

### ISSUE THREAD

**Issue by disemelo** [YetiForceCompany/YetiForceCRM#7645]
#### Issue

Hi,
Any help on how to upload images via rest api.

#### Actual Behavior

a new record is created however the image is not uploaded.
#### How to trigger the error

1.
curl -i -X POST \
   -H "Authorization:Basic cG9ydGFsOnBvcnRhbA==" \
   -H "X-API-KEY:r7N8sXSEPwJTCwhv8npJ8BX9ztzyrSbx" \
   -H "userName:portal" \
   -H "password:portal" \
   -H "X-TOKEN:2151ae12afc0942305ec4ca57f6a2e9e" \
   -H "Content-Type:multipart/form-data" \
   -F "imagename=@/home/saron/workers-3.jpg" \
 'http://192.168.1.4/final/api/webservice/Contacts/Record?firstname=Sam&lastname=Coleman'
2.
3.

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Chrome 67.0.3396.99
* Environment name and version: Apache 2.4
* Operating System and version: Debian 9

**Comment by ldgbc** [comment]
Off-topic:

I would like to how to use Webservice and API, are you able to provide instruction?

**Comment by mariuszkrzaczkowski** [comment]
Add in https://github.com/YetiForceCompany/YetiForceCRM/pull/8612 
```
	$recorddata = array(
		'firstname' => 'test',
		'lastname' => 'test',
		'imagename' => json_encode([[
			'name' => '0.jpg',
			'baseContent' => base64_encode(file_get_contents('0.jpg'))
		]])
	);
```
