### ISSUE TITLE
Creating custom field in users... something I'm missing

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#7649]
Hello Friends

This is a little question you may help me

I'm trying to create a custom field called "colegiado" in users, this is a code needed for every user in crm. 

Well I've created the entry in vtiger_users

![image](https://user-images.githubusercontent.com/40429279/44053969-295641d6-9f39-11e8-86ec-fe21109a9ced.png)

And created the entry in vtiger_fields

![image](https://user-images.githubusercontent.com/40429279/44054034-5c6c727a-9f39-11e8-8c29-2ca8d314503f.png)

But I cannot make it appear in the form "Users". any idea please?
Big Thankyou!

#### Actual Behavior
Cannot make visible a reviusly created custom field in users

#### Expected Behavior
The field should appear

#### How to trigger the error

1. Create the field in vtiger_users table
2. Create the field in vtiger_fields
3. Nothing appears in the form

#### Your Environment

* YetiForce Version used: Last One
* Browser name and version: All browsers
* Environment name and version: lamp php 7.0  over mysql 5.x
* Operating System and version: centos 7

**Comment by mariuszkrzaczkowski** [comment]
manually created entries in the database? if it does not work then you have to use vtlib
