### ISSUE TITLE
[v4.4.x] SSalesProcess - the status query is hard coded to block changes

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#7667]
#### Issue

In the SalesProcess the status query is hard-coded to block changes! Thus, it is not possible to reopen the module for editing.
![grafik](https://user-images.githubusercontent.com/10259801/44141386-4df38b9e-a07d-11e8-93ed-416464548a39.png)

#### Actual Behavior

I cannot edit a salesprocess, when it has a final status.
I need a solution, to reopen a single record, for editing.

#### Expected Behavior

1. The system block the status with Workflow, as in module Quotes, etc.
2. I would create a manuell Workflow, to set to a non-final status. (or is there another way to open a record?)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: v4.4.x
* Browser name and version: chrome
* Environment name and version: gitdeveloper
* Operating System and version: Windows 10

**Comment by bpabiszczak** [comment]
This is the configuration file.
