### ISSUE TITLE
Cant relate the project with Contacts

### ISSUE THREAD

**Issue by vjstyla** [YetiForceCompany/YetiForceCRM#767]
Hi can you guide me how to relate a project with contacts as its only giving me the option to relate the record with Organisation

Please help, loving your solution though

**Comment by bpabiszczak** [comment]
A project might be only related to an organization.

In the new version we will add a possibility to relate it to contacts but it will be 1:M relation and filling in a field with an organization will be mandatory.

**Comment by vjstyla** [comment]
No, I don't agree with you here....I think the project can be related to an individual as well as its in vTigerCRM...... I have related the project to organisation but I cant see that in customer portal as making it visible in portal a record has to be related to contacts but not organization.

We get lots of Individual customers coming with their project, I hope you getting that

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/business-processes/marketing-process/121-b2c-vs-b2b-2.html

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/business-processes/marketing-process/122-how-to-enter-new-leads.html
