### ISSUE TITLE
[PL] Generowanie faktury z zamówienia | Generowanie projektu

### ISSUE THREAD

**Issue by marcineqpol** [YetiForceCompany/YetiForceCRM#7684]
#### Issue

W dokumentacji i oryginalnym VTiger widziałem opcję "generuj projekt" i "Generuj fakturę" z "zamówienia od klienta". Niestety w YetiForce nie widzę takiej opcji. 

#### Actual Behavior

Generując z zakończonego zamówienia od klienta fakturę - muszę wszystko wykonywać ręcznie.
Zamówienie przekształcając w projekt - muszę ręcznie dodać w projekt.
#### Expected Behavior

Kliknięcie przy zamówieniu od klienta "generuj fakturę" tworzy fakturę.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
W vtiger to było w kodzie na sztywno zrobione, w yeti jest od tego specjalny mechanizm który umożliwia  włączenie tego dla każdego z modułów.
https://public.yetiforce.com/gallery/#15344863572857/15344863991159

Obecnie przepisujemy ten mechanizm na nowy który będzie bardziej rozbudowany https://github.com/YetiForceCompany/YetiForceCRM/pull/6597
