### ISSUE TITLE
WYSIWYG Field Default value - Enhanced Typing field[enhancement]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7685]
#### Issue
The **WYSIWYG** can do many thing using (HTML code?) such as Bold, Italic, Font Size, New line/paragraph, etc. The current Yetiforce's, under the Default Value it is limited in option. WYSIWYG field default value should be able to use of it function or at least a few function.

#### Actual Behavior
WYSIWYG  default values is limited.

#### Expected Behavior
Full or partial WYSIWYG in default values.

#### How to trigger the error
1. Go to Field Editor: index.php?module=LayoutEditor&parent=Settings&view=Index&block=2&fieldid=33
2. Go to description. Edit field. Choose Defaults Value.

**### Current:** 
![yetiforce - default value wysiwyg basic](https://user-images.githubusercontent.com/1805303/44246042-60694e00-a21f-11e8-893e-ba1a2ae5edcb.png)

**### Full WYSIWYG** 
![yetiforce - default value wysiwyg new enhance](https://user-images.githubusercontent.com/1805303/44246043-6101e480-a21f-11e8-9217-a8be62242c73.png)

3. If FULL WYSIWYG can't be done, in term of partial, it should be able to do at least Bold and paragraph support.

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: FF 61
* Environment name and version: XAMPP 4.3
* Operating System and version: Windows

**Comment by rskrzypczak** [comment]
In current (dev) version:
![image](https://user-images.githubusercontent.com/10221999/48634652-54c82780-e9c6-11e8-807e-43cade198101.png)

**Comment by vovpff** [comment]
Cool
