### ISSUE TITLE
Blank Page on Round Cube Configuration after update

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#7704]
#### Issue

Blank Page when Round Cube configuration is clicked. This happened after update from 4.3.0 to 4.4.0v2

#### Actual Behavior

I don´t have access to Round Cube configuration, It worked on 4.3.0.

#### Expected Behavior

To be abble to change the parameters on Round Cube configurations
#### How to trigger the error

1.Go to system settings
2. Click on mail setting - Round Cube settings
3.

#### Screenshot of configuration

![image](https://user-images.githubusercontent.com/20831164/44295757-422e3d00-a275-11e8-95d7-ce41f8be1494.png)

#### PHP/Apache/Browser Logs

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 The SQL being executed was: INSERT INTO `o_yf_csrf` (`username`, `date`, `ip`, `referer`, `url`, `agent`) VALUES ('Florez Alvaro', '2018-08-17 23:20:45', '1.111.111.111', '-', 'https://crm.crmyeti.com.co/index.php?module=OSSMail&amp;parent=Settings&amp;action=Save&amp;product_name=Crmyeti&amp;validate_cert=false&amp;imap_open_add_connection_type=false&amp;imap_open_add_connection_type=true&amp;default_host=mail.crmyeti.com&amp;default_port=143&amp;smtp_server=mail.crmyeti.com&amp;smtp_user=%25u&amp;smtp_pass=%25p&amp;smtp_port=587&amp;language=en_US&amp;username_domain=crmyeti.com&amp;skin_logo=%2Fimages%2Fnull.png&amp;ip_check=false&amp;enable_spellcheck=false&amp;enable_spellcheck=true&amp;identities_level=0&amp;session_lifetime=60&amp;__vtrftk=sid%3A37bf44c0ac185c3b77da392ce8265ad68cbf96d2%2C1534566034', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36')

#### Your Environment

* YetiForce Version used: 4.4.0 updated from 4.3.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

**Comment by PercyP** [comment]
Hi,

have you gone to the Settings-Standard Modules then Download Roundcube?

You have to do this each time you update. Plus make sure after this that My Mailbox in Standard Modules is enabled

**Comment by mariuszkrzaczkowski** [comment]
Delete the browser cache

**Comment by ldgbc** [comment]
Are you able to test it on a fresh installation of v4.4 to see if it working at all for you. Then do a v4.3 update to v.4.4 and try that again?
