### ISSUE TITLE
[PL] Szablony mailowe bez obrazów i znaczników <img>

### ISSUE THREAD

**Issue by draki7** [YetiForceCompany/YetiForceCRM#7705]
#### Issue

Tworzenie szablonów usuwa wszystkie obrazy < img > po każdym zapisie. 
Wstawianie obrazów poprzez WYSIWYG również nie funkcjonuje.
Wszystkie edycje zawsze są wprowadzane na kodzie źródłowym, edytorem WYSIWYG kiedy wstawiany jest obraz również po zapisie cały znacznik < img > znika.

#### How to trigger the error

1. Utworzenie nowego szablonu, każda edycja
2. Tworzenie poprzez wstawienie obrazu WYSIWYG również usuwa < img >
3. W demo YETIFORCE niestety nie można tworzyć szablonów poprzez edytor WYSIWYG, natomiast wklejenie szablonu HTML ze znacznikiem obrazu również usuwa wszystkie obrazy.

#### Screenshot of configuration

![Image](https://plissandroll.pl/UP/SHARE/PIC.PNG)

![Image](https://plissandroll.pl/UP/SHARE/PIC-OK.PNG)
#### Your Environment

* YetiForce Version used: 4.4 na maszynie testowej w chmurze

**Comment by mariuszkrzaczkowski** [comment]
Proszę o przykład kodu html

**Comment by draki7** [comment]
Część kodu z IMG
```
<table style="margin: 0 auto;" cellspacing="0" cellpadding="0" align="center" bgcolor="#F5F5F5">
  <tbody>
    <tr>
      <td width="50%">&nbsp;</td>
      <td style="padding: 36px 20px 10px 20px;" align="center">
        <a title="Strona gł&oacute;wna" href="https://link.pl" target="_blank" rel="noopener"> <img title="Strona gł&oacute;wna" src="https://link.pl/UP/MAIL/LOGO-SCIEZKA.png" width="250" height="100" border="0" /> </a>
      </td>
      <td width="50%">&nbsp;</td>
    </tr>
  </tbody>
</table>
```

Po wrzuceniu i zapisaniu, kod wygląda tak:

```
<table align="center" bgcolor="#F5F5F5" cellpadding="0" cellspacing="0" style="margin:0 auto;">
	<tbody>
		<tr>
			<td width="50%">&nbsp;</td>
			<td align="center" style="padding:36px 20px 10px 20px;"><a title="Strona główna"> </a></td>
			<td width="50%">&nbsp;</td>
		</tr>
	</tbody>
</table>
``

**Comment by mariuszkrzaczkowski** [comment]
WYSIWYG w systemie czyści wszystkie odwołania do zewnętrznych plików graficznych, można dodać domenę do zaufanych to wtedy nie usunie. 
https://github.com/YetiForceCompany/YetiForceCRM/blob/825c553529b23d9b02e11160e32de0ce56ed0441/config/security.php#L55-L56
