### ISSUE TITLE
instalation problem

### ISSUE THREAD

**Issue by RustemHesenov** [YetiForceCompany/YetiForceCRM#7706]
I am trying to install but the screen is white. What do you recommend?

<img width="1792" alt="screen shot 2018-08-19 at 00 37 41" src="https://user-images.githubusercontent.com/7926881/44303066-1af47000-a348-11e8-9965-3183bc8987bb.png">

PHP Version 7.0.8

**Comment by RustemHesenov** [comment]
Sorry,

I noticed that it was in the php version of the error and I updated it. Current version 7.1.19

Thank you for making such a best crm system.

**Comment by RustemHesenov** [comment]
Edit:

I have updated the php version. But he is not installing.
<img width="1792" alt="screen shot 2018-08-19 at 01 05 46" src="https://user-images.githubusercontent.com/7926881/44303223-28abf480-a34c-11e8-9edb-9c2f3192d97f.png">

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements
![image](https://user-images.githubusercontent.com/10198654/44303224-65232480-a33b-11e8-8d6c-f008ad57ddd7.png)

**Comment by RustemHesenov** [comment]
@mariuszkrzaczkowski  pls help me...

I would be grateful if you could give us information about what the error is on the installation.

**Comment by mariuszkrzaczkowski** [comment]
![yetiforce_settings](https://user-images.githubusercontent.com/10198654/44303236-af0c0a80-a33b-11e8-83d8-7466e18ea35c.png)
and logs

**Comment by ldgbc** [comment]
You can open up a file call, "debug"

\config\debug.php

and enable Display logs and Debug if you want to see the error. But white screen usually mean your server is missing something (so make sure your configuration like that image mariuszkrzaczkowski posted).

If you are like, you can also just use the XAMPP server.

**Comment by cakrina** [comment]
I have similar issue on my host, I feel there is incorrect wording here in requirements
It's says php 7.1 recommended while it's actually required. Recommended meand suggested but not required.
Also I suggest change lines 8 and 9 in include/RequirementsValidation.php
if (version_compare(PHP_VERSION, '7.1', '<')) {
	throw new Exception('Wrong PHP version, recommended version >= 7.0');
To required version >=7.1
Not sure if I should report a separate issue. This was my case during install it would throw error-500 adding display_errors On to .user.ini revealed 
Fatal error: Uncaught exception 'Exception' with message 'Wrong PHP version, recommended version >= 7.0' in /home/kinkaric/crm.kinkari.com/include/RequirementsValidation.php:9 Stack trace: #0 /home/kinkaric/crm.kinkari.com/index.php(13): require() #1 {main} thrown in /home/kinkaric/crm.kinkari.com/include/RequirementsValidation.php on line 9

**Comment by vovpff** [comment]
required

**Comment by cakrina** [comment]
Thank you! So how do we go about adjusting 7.1 recommended to 7.1 required in documentation etc as well as in RequirementsValidation.php error message ? I understand it's minor yet it would of saved me a lot of time

**Comment by rafalzda** [comment]
Hi, i have a similaar problem. I am trying to install **YetiForceCRM-4.4.0-complete.zip** but the screen is white.
![20190130_013828](https://user-images.githubusercontent.com/47144661/51950195-c5141000-242f-11e9-89da-3fdcd8d225d0.png)

httpd logs:
[yetiforce_log.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2810338/yetiforce_log.txt)
[yetiforce-error_log.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2810339/yetiforce-error_log.txt)

environment (Google Cloud):
```
PHP 7.1.26 (cli) (built: Jan  9 2019 08:02:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.26, Copyright (c) 1999-2018, by Zend Technologies
Server version: Apache/2.4.6 (CentOS)
Server built:   Nov  5 2018 01:47:09
mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1
```

```
[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```
**/etc/httpd/conf.d/yetiforce.conf**
```
<VirtualHost *:80>

ServerAdmin admin@yourdomain.com
DocumentRoot /var/www/html/yetiforce/
ServerName myyetiforce.com
ServerAlias www.myyetiforce.com

<Directory /var/www/html/yetiforce/>
Options FollowSymLinks
AllowOverride All
Order allow,deny
allow from all
</Directory>

ErrorLog /var/log/httpd/yetiforce-error_log
CustomLog /var/log/httpd/yetiforce_log common
</VirtualHost>
```

How can I deal with it?

**Comment by mariuszkrzaczkowski** [comment]
see in the logs is everything, you have a problem with file permissions

[Wed Jan 30 00:20:12.313254 2019] [php7:warn] [pid 5504] [client MY.IP.MY.IP:60200] PHP Warning:  chmod(): Permission denied in /var/www/html/yetiforce/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 284
[Wed Jan 30 00:20:12.313300 2019] [php7:warn] [pid 5504] [client MY.IP.MY.IP:60200] PHP Warning:  Directory /var/www/html/yetiforce/cache/vtlib/HTML not writable, please chmod to 775 in /var/www/html/yetiforce/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297
[Wed Jan 30 00:20:12.333947 2019] [php7:warn] [pid 5504] [client MY.IP.MY.IP:60200] PHP Warning:  chmod(): Permission denied in /var/www/html/yetiforce/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 284

[Wed Jan 30 00:28:13.162025 2019] [php7:warn] [pid 5779] [client MY.IP.MY.IP:61242] PHP Warning:  Directory /var/www/html/yetiforce/cache/vtlib/HTML not writable, please chmod to 775 in /var/www/html/yetiforce/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297
[Wed Jan 30 00:28:13.165910 2019] [php7:warn] [pid 5779] [client MY.IP.MY.IP:61242] PHP Warning:  chmod(): Permission denied in /var/www/html/yetiforce/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 284
[Wed Jan 30 00:28:13.165934 2019] [php7:warn] [pid 5779] [client MY.IP.MY.IP:61242] PHP Warning:  Directory /var/www/html/yetiforce/cache/vtlib/HTML not writable, please chmod to 775 in /var/www/html/yetiforce/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297
[Wed Jan 30 00:28:13.165972 2019] [php7:warn] [pid 5779] [client MY.IP.MY.IP:61242] PHP Warning:  chmod(): Permission denied in /var/www/html/yetiforce/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 284
[Wed Jan 30 00:28:13.165976 2019] [php7:warn] [pid 5779] [client MY.IP.MY.IP:61242] PHP Warning:  Directory /var/www/html/yetiforce/cache/vtlib/HTML not writable, please chmod to 775 in /var/www/html/yetiforce/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297
[Wed Jan 30 00:28:13.168817 2019] [php7:warn] [pid 5779] [client MY.IP.MY.IP:61242] PHP Warning:  SessionHandler::read(): open(/var/www/html/yetiforce/cache/session/sess_d2urisr2249vi0e3iuhqism9kl, O_RDWR) failed: Permission denied (13) in /var/www/html/yetiforce/app/Session.php on line 34
[Wed Jan 30 00:28:13.168852 2019] [php7:warn] [pid 5779] [client MY.IP.MY.IP:61242] PHP Warning:  session_start(): Failed to read session data: user (path: /var/www/html/yetiforce/cache/session) in /var/www/html/yetiforce/app/Session.php on line 34
[Wed Jan 30 00:28:13.180214 2019] [php7:error] [pid 5779] [client MY.IP.MY.IP:61242] PHP Fatal error:  Uncaught  --> Smarty: unable to write file /var/www/html/yetiforce/cache/templates_c/wrt5c50ef9d2bf502_20934145 <-- \n  thrown in /var/www/html/yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_writefile.php on line 49

**Comment by mariuszkrzaczkowski** [comment]
I do not know the environment configuration, it is best to ask the server administrator for the correct configuration of file permissions

**Comment by rafalzda** [comment]
I configure the environment  with this commands only + tutorial how to install:
```
yum -y install epel-release
yum -y install mariadb-server mariadb
systemctl start mariadb.service
systemctl enable mariadb.service
mysql_secure_installation
yum -y install httpd
systemctl start httpd.service
systemctl enable httpd.service
firewall-cmd --permanent --zone=public --add-service=http 
firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --reload
rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum -y install yum-utils
yum update
yum-config-manager --enable remi-php71
yum -y install php php-opcache
yum install php-{fpm,mbstring,mcrypt,phpdbg,dev,curl,sqlite3,json,gd,cli,zip,soap,ldap,apcu,imap}
systemctl restart httpd.service
yum search php
yum -y install php-mysqlnd php-pdo
yum -y install php-gd php-ldap php-odbc php-pear php-xml php-xmlrpc php-mbstring php-soap curl curl-devel
systemctl restart httpd.service
```
**php.ini**:
[php.ini.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2811423/php.ini.txt)

Please help me, I'm not a specialist :(

**Comment by mariuszkrzaczkowski** [comment]
it must verify the administrator is not a crm error

**Comment by cakrina** [comment]
Make sure directory has correct ownership. For Ubuntu it’s chown-R www-data:www-data

**Comment by rafalzda** [comment]
@cakrina thanks, i'll try :)
