### ISSUE TITLE
[How to?] Emails for users if record modified.

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7728]
This is question.

What I need to do to achieve next condition of YetiForce mailer:

When record (for example Account) modified I need to send email notification for some users who works with this account. Now I can automatically send email to Assigned user by workflow. This is cool. I can add group what contain list of users and put this group as assigned. This actions gives me ability to send some emails for different users in group if record modified but in this case I can't assign specific user to record.

If more simply: I need one hard assigned user and some list of users what need to me notified with any modifications.

What I can do in this case?

**Comment by vovpff** [comment]
Any suggestions?

**Comment by slawekk87** [comment]
Currently this can be done by 'watch record' functionality - user that want to monitor record can mark item as watched and configure notifications to be send.
![image](https://user-images.githubusercontent.com/22735929/48841578-1b126a80-ed92-11e8-8dcb-f031d1146863.png)
![chrome_2018-11-21_13-34-42](https://user-images.githubusercontent.com/22735929/48841900-1c906280-ed93-11e8-857e-0913af530c68.png)
![chrome_2018-11-21_13-39-18](https://user-images.githubusercontent.com/22735929/48841912-22864380-ed93-11e8-813f-765085d499b3.png)
