### ISSUE TITLE
how to make a pick list from other module field?

### ISSUE THREAD

**Issue by BraulioBracamonte** [YetiForceCompany/YetiForceCRM#7738]
#### Issue

#Example: i made module a with fields : descrip, addres, location, myRecord#
and each myRecord# may have multiple items. then i made other mudule with fields: myRecord#, brand, model, serial, type
how do i make that the myRecord# on module 2 is a pick list of myRecord# from module1?

so far i only got to select the full record of module 1.

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: chrome V 68.0.3440.106
* Environment name and version:
* Operating System and version:

**Comment by BraulioBracamonte** [comment]
thanks!

**Comment by BraulioBracamonte** [comment]
Ok, thanks.
and when i create a relation, and i go to a record, it shows a tab with the relation, but when i click on it, it gives this error
`{"success":false,"error":{"code":42,"message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'vtiger_notes.filetype' in 'field list'\nFailed to prepare SQL: SELECT `vtiger_compras`.`factura` AS `factura`, `vtiger_compras`.`comprasid` AS `id`, `vtiger_notes`.`filetype` FROM `vtiger_compras` INNER JOIN `vtiger_crmentity` ON vtiger_compras.comprasid = vtiger_crmentity.crmid INNER JOIN `vtiger_senotesrel` ON vtiger_senotesrel.notesid= vtiger_notes.notesid INNER JOIN `vtiger_crmentity` `crm2` ON crm2.crmid = vtiger_senotesrel.crmid WHERE (`vtiger_crmentity`.`deleted`=:qp0) AND (((`crm2`.`crmid`=:qp1))) ORDER BY `vtiger_compras`.`comprasid` DESC LIMIT 21","trace":""}}`

What should i look for, read or configure?
Thanks

**Comment by vovpff** [comment]
@BraulioBracamonte try on gitdev.
You configuration can fail adding of new relation.

**Comment by BraulioBracamonte** [comment]
ok. thanks
