### ISSUE TITLE
Can we restrict the records to be shown only to the assigned to users - yetiforce

### ISSUE THREAD

**Issue by mjapple** [YetiForceCompany/YetiForceCRM#7768]
Hello
Good time,
Is there any way across the CRM to set restriction for users to view and access only the records which they are assigned to ?

"Yetiforce version 4.3.0"

Thanks and Best Regards

**Comment by mjapple** [comment]
@vovpff if i understand correctly each user put the record private and the admin can see that specific record?

for now , what i was trying to do was to put this code in class of each div
and put set the css style to > display: hidden; for each specific module and each specific user

in order to prevent user 3 not to see the records which are made by user1 or user2
in layout files I limited users like this  
<div class="{$MODULE}{$PARENT_MODULE}{$USER_MODEL->getName()}">
it will be something like <div class="SSalesProcessesUSER1">
and in a css file i hide it .SSalesProcessesUSER1 {display:hidden !important;} .SSalesProcessesUSER2 {display:hidden !important;}
only if they know how to read the source code they can access to the data.

**Comment by vovpff** [comment]
@mjapple your hardcoded solution not flexible and after every update you need to patch you system. Let's try to use built-in features.

**Comment by ldgbc** [comment]
You set up by the user role. For example, Level 3 staff can't review any other level 3 staff, Level 2 can view Level 3 staff and themselves but level can't view other level 2 for example.

You want this one: https://gitdeveloper.yetiforce.com/index.php?module=Roles&parent=Settings&view=Index&block=1&fieldid=2

For example look under the setting:
https://gitdeveloper.yetiforce.com/index.php?module=Roles&parent=Settings&view=Edit&parent_roleid=H14

You want to play with this setting here:
Should the list of records, related to the records we can access, be shared:
Should the preview of records, related to the records we can access, be shared:
Permissions for the related records are field-based:
Should the edition of records (that we do not own), related to our records, be enabled:
Whether or not browsing other users' graphical calendars is possible:
