### ISSUE TITLE
[4.4.0] Can not add photo to PDF template

### ISSUE THREAD

**Issue by turek93** [YetiForceCompany/YetiForceCRM#7773]
#### Issue

Hello,
after installing the new version of YetiForce 4.4.0 I can not add photos to the template. This is important for printed reports, invoices, offers from the system on paper with the company logo.

#### Actual Behavior

After adding the image in the jpg, png etc format to the pdf template it does not appear on the printout.
#### Expected Behavior

I would like to receive a company logo on paper on a PDF file. In the future, many people will probably add photos to PDF templates.
#### How to trigger the error

Path to reproduce the problem:
1. Adds a new PDF template
2. I upload the company logo
3. I get url photos, e.g. htttp: //customurl.com/layouts/resources/Logo/company_logo.jpg
4. Obtains the <img> attribute in the source code with the file path
5. The photo shows itself in the preview
6. After saving and trying to print from the module, the pictures do not add up
7. An empty space appears
#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Google Chrome, Mozilla Firefox, Safari (all newest version)
* Environment name and version:  PHP 7.1, Apache
* Operating System and version: Ubuntu 17.10

The problem concerns files with the extension jpg png etc.
I found a workaround by changing the file format to base64. Then everything works correctly.

I checked and the same problem occurs on gitstable.yetiforce.com
Please, let me know what the problem may be
Greeting
Wojtek

**Comment by KatarzynaUlichnowska** [comment]
Hello, please enclose the template.
The system by default blocks the loading of external photos, so you need to add the domain to the trusted ones and then upload.
Wojtek, I suppose you are Polish, so have a look [here](https://github.com/YetiForceCompany/YetiForceCRM/issues/7705#issuecomment-414208372) as it is in Polish and was very similar to your issue.

**Comment by vovpff** [comment]
@KatarzynaUlichnowska 

> so you need to add the domain to the trusted ones and then upload

How to do it?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/7705#issuecomment-414208372

**Comment by turek93** [comment]
Thank you very much for your response and support.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks!

**Comment by ldgbc** [comment]
@turek93 @vovpff 
Do you guys know how it work? Is it like this?

	'PURIFIER_ALLOWED_DOMAINS' => [www.github.com/*;www.yetiforce.com/*], 
or maybe?
	'PURIFIER_ALLOWED_DOMAINS' => [github.com], 
	'PURIFIER_ALLOWED_DOMAINS' => [yetiforce.com],
or maybe?
	'PURIFIER_ALLOWED_DOMAINS' => [*.github.com/*], 
	'PURIFIER_ALLOWED_DOMAINS' => [*.yetiforce.com/*], 

Also any idea how to add local image?

Maybe?
'PURIFIER_ALLOWED_DOMAINS' => [127.0.0.1:123/], 

or Maybe?
'PURIFIER_ALLOWED_DOMAINS' => [C:\\image\\logo.jpg], 
or Maybe?
'PURIFIER_ALLOWED_DOMAINS' => [\\storage\\logo.jpg],

**Comment by mariuszkrzaczkowski** [comment]
'PURIFIER_ALLOWED_DOMAINS' => ['github.com','yetiforce.com','img.yetiforce.com'],

**Comment by LukeLak** [comment]
I am using yetiforce 4.4.0 and have added this, but it is not saving in the template. Why?

'PURIFIER_ALLOWED_DOMAINS' => ['mycrm.domain.eu'],

**Comment by maeglin4** [comment]
> 'PURIFIER_ALLOWED_DOMAINS' => ['github.com','yetiforce.com','img.yetiforce.com'],

ive added 	public static $PURIFIER_ALLOWED_DOMAINS = ['myDomain.cloud'];

and now the photo save's in my .PDF template but does not show for printing. is there a specific folder that i need to put the images in ?

**Comment by mjapple** [comment]
I am trying to add images from crm directory itself <img src="/logo.png"> 
but after saving and finishing the images are disappearing ...

**Comment by mjapple** [comment]
I tried svg but is not working as well

**Comment by mjapple** [comment]
['HPKP_KEYS' => [],
	// Content Security Policy
	'CSP_ACTIVE' => false,
	// List of allowed domains for fields with HTML support
	'PURIFIER_ALLOWED_DOMAINS' => ['fonts.googleapis.com/*','fonts.googleapis.com/','https://fonts.googleapis.com/css','/','tru.tools/logo.png','http://tru.tools/tuv.png','http://tru.tools/logo.png','tru.tools/tuv.png','/tuv.png','/logo.png','fonts.googleapis.com/css?family=Comfortaa:300,400,500,600,700&display=swap&subset=cyrillic,cyrillic-ext'],](url)

**Comment by mariuszkrzaczkowski** [comment]
open a new issue, this one is now out of date
