### ISSUE TITLE
[BUG][PL] Błędy wyświetlania FF + 1280x1024px

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#779]
Kilka błędów w wyświetlaniu - zaznaczone na czerwono.

![css](https://cloud.githubusercontent.com/assets/4824588/7672102/7f755136-fce6-11e4-90a5-c2ea5d6fef2d.JPG)

**Comment by bpabiszczak** [comment]
Widżety na stronie głównej zostały poprawione w wielu miejscach. Wydaje mi się, że pozostałe kwestie również. Proszę przetestować na najnowszej wersji z github.

**Comment by waw555** [comment]
What is your screen resolution?

**Comment by bpabiszczak** [comment]
Można też testować tutaj: https://test.yetiforce.com

**Comment by florek41** [comment]
o, świetnie !

Faktycznie widżety na mojej instalacji i nowej testowej są OK, jednak pierwsze dwa problemy występują dalej (właściwie jeden problem, który ciągnie za sobą kolejny). 

Problematycznym elementem jest span z klasą noMails_* odpowiadający za wyświetlanie ilości nieprzeczytanych maili i występuje tylko kiedy w skrzynce takie maile się znajdują.

Element w tej chwili ma nadany `font-size: 0;`, wg. mnie lepszym rozwiązaniem jest całkowite ukrycie go za pomocą `display:none`, tylko pojawia się pytanie - *czy nie lepiej, żeby ta ilość była cały czas widoczna ?* (przy rozdzielczości 1280x1024px wyświetlana jest tylko ikona koperty)

Kolejny problem, który dotyczy tego samego elementu, ale przy rozdzielczości 1366x768px: niewystarczająca szerokość elementu nadrzędnego ( #headerLinks.span5.row-fluid ) w momencie kiedy mamy zaraportowany czas pracy:
![css_2](https://cloud.githubusercontent.com/assets/4824588/7689904/09f563cc-fdb0-11e4-955e-d5756c859821.JPG)

**Comment by bpabiszczak** [comment]
Jutro albo pojutrze na to zerkniemy, jednakże widzę, że masz wiedzę w zakresie HTML, a więc może zaproponujesz i prześlesz rozwiązanie ;]

**Comment by florek41** [comment]
już nad tym pracuję ;)
