### ISSUE TITLE
How can fix when the Net Total is zero?

### ISSUE THREAD

**Issue by daveloh** [YetiForceCompany/YetiForceCRM#7802]
![image](https://user-images.githubusercontent.com/42636821/44512923-978fa180-a6ee-11e8-9ff0-ce0692bb3829.png)

Refer to picture about. YetiForce version 4.3.0.

I am making a new quotation, and try to test a few value in variable.
When Gross Total in Words is not empty, why Net Total, Gross Total, and Calculation - Net Total is zero value?

Very much appreciate.

Thank you.

**Comment by mjapple** [comment]
Hey , Did you change the fields to advance fields ?

**Comment by slawekk87** [comment]
Can You retest this on developer version (https://gitdeveloper.yetiforce.com/)? If issue still exists attach video.
