### ISSUE TITLE
Issue with unit price when import of products

### ISSUE THREAD

**Issue by manwenick** [YetiForceCompany/YetiForceCRM#7804]
#### Issue
Import of products. The imported currency is not correct.

#### Actual Behavior
Imported products from CSV file. They contain different kind of fields: text, currency, figures etc. Only one currency is available in the system. (second currency was deleted due to failures at the first import try). 
I have RUB in the system, but imported products have EUR. There is no EUR currency in the system anymore. 

#### Expected Behavior
1. After import of the data, the system selected currency should apear. 
2. Or the possibility to bulk change the currency of the products. In this case, there is no available currencies apear. 

#### How to trigger the error
1. Go to products --> Select import
2. Finish import, without failures.
3. List of products --> the currency is not correct. 
4. choose product --> edit product --> no currencies are available to be selected.

#### Screenshot of configuration
![screenshot_2018-08-23 server configuration system settings 2](https://user-images.githubusercontent.com/34367573/44514416-5aacb600-a6c0-11e8-9a81-a41aa99a714d.png)
![screenshot_2018-08-23 server configuration system settings 3](https://user-images.githubusercontent.com/34367573/44514417-5aacb600-a6c0-11e8-8035-2429ef176ca4.png)
![screenshot_2018-08-23 server configuration system settings](https://user-images.githubusercontent.com/34367573/44514418-5b454c80-a6c0-11e8-907e-63b1117316ce.png)
![screenshot_2018-08-23 server configuration system settings 1](https://user-images.githubusercontent.com/34367573/44514419-5b454c80-a6c0-11e8-81e4-d477823f7404.png)

#### PHP/Apache/Browser Logs
-

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Mozilla Firefox Quantum 61.0.2 
* Environment name and version: 
* Operating System and version:
![screenshot_2018-08-23 server configuration system settings 4](https://user-images.githubusercontent.com/34367573/44514679-10780480-a6c1-11e8-9040-acbde4819fd2.png)

**Comment by vovpff** [comment]
@manwenick maybe this helps:
Set RUB currency by default before import here https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=Currency&view=List&block=4&fieldid=16

**Comment by manwenick** [comment]
@vovpff thanks for advise!
I deleted the imported products. --> changed the currency to RUB (I deleted EUR and USD completely), then I imported the data again. 
Still the same. But I also see two different issues:
1. On the imported products (after importing) if I try to edit them, there is no currency at all, which I can select to change. See att. 
![screenshot_2018-08-23 products edit](https://user-images.githubusercontent.com/34367573/44523337-cbac9780-a6d9-11e8-8506-9517ad7b49fa.png)
2. On the product, which I added manually I see following:
![screenshot_2018-08-23 products create](https://user-images.githubusercontent.com/34367573/44523392-eda61a00-a6d9-11e8-9df4-75ac2a4665de.png)
And this is how the system currency values are set:
![screenshot_2018-08-23 currency system settings](https://user-images.githubusercontent.com/34367573/44523405-00b8ea00-a6da-11e8-87e1-47981d843471.png)
QUESTION: Is there a different db entries for imported products?
I also have a problem to change the product category as a bulk, which on manually added product works very well:
![screenshot_2018-08-23 products list](https://user-images.githubusercontent.com/34367573/44523718-301c2680-a6db-11e8-9f55-b164bc644b97.png)

**Comment by vovpff** [comment]
Guys, sorry for Russian
@manwenick вы что вообще импортировать пытаетесь? Скиньте сюда пример заголовков и строки вашего CSV?

**Comment by manwenick** [comment]
@vovpff вот пример:
"category";"productname";"usageunit";"unit_price";"taxes";"prod_description_ru";"prod_art_no";"qtyunitsizexs";"qtyunitsizes";"qtyunitsizel";"qtyunitsizem";"qtyunitpossible";"prod_fabric_value";"qtyunitsizeallsize";

**Comment by vovpff** [comment]
@manwenick а саму строку с данными дадите?

**Comment by manwenick** [comment]
@vovpff конечно, если поможет. :)
"03 Брюки";"Брюки коричневое бордо.";"pcs.";"6400.00";"2";"Вельветовые бананы. Мягкие, удобные и сочетаются с практически любым топом!";"031703022";"0";"0";"0";"0";"0";"50% хлопок, 50% вискоза";"0";

**Comment by vovpff** [comment]
@manwenick попробую подумать. А откуда экспортировали?

**Comment by manwenick** [comment]
@vovpff из bitrix24.
Я пробовал по разному модифицировать. И в xml тоже эксопртировал даты из yeti, чтоб пример был, как выглядит один товар. Там в вальте было значение примерно такое: 9600.00000000 
Но самой валюты не былл нигде. В битриксе наооборот, с ценой 9600,00 (с разделительной запятой) и в следующем стринге передается валюта. Например >RUB< или >EUR<.
Владимир, я вам по мэйлу писал, когда сервер пытался настроить. Может я там чего-то не доделал. Хотя вроде всё нормально выглядит.
Ник

**Comment by vovpff** [comment]
@manwenick вероятно писали. Я уже не помню.
В общем, я из ваших данных сделал такой файлик
[new 12.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2317289/new.12.txt)
Только переименовать надо в csv.
Импортирую в gitdev: 
![image](https://user-images.githubusercontent.com/8545791/44568792-ed148e80-a780-11e8-84b9-de72131d8bde.png)
![image](https://user-images.githubusercontent.com/8545791/44568813-01588b80-a781-11e8-8203-abbef57aabf9.png)
Тут по умолчанию стоит валиюта zl по этому и импортировалось так.
Дальше тот же файл импортирую в свою локальную песочницу:. Валюта по умолчанию рубли. Других валют вообще не имеется в системе.
![image](https://user-images.githubusercontent.com/8545791/44568888-35cc4780-a781-11e8-8d1b-9b171ef6bb64.png)
В чем проблема?

**Comment by manwenick** [comment]
@vovpff Я вам на емайл ответ отправил.

**Comment by manwenick** [comment]
@vovpff I tried to import your file also in https://gitdeveloper.yetiforce.com. After importing this product I see the system default currency. BUT if I want to change it there is the same situation with currency. I can't select another currency. 
Maybe bug?

**Comment by vovpff** [comment]
![unit price](https://user-images.githubusercontent.com/8545791/44628055-b20d8900-a941-11e8-968a-e30c9b093158.gif)

**Comment by manwenick** [comment]
@mariuszkrzaczkowski Hello Mariusz, is there some timeline when this bug will be fixed? I would like to know, when I can start with import of the prods. We have a lot of products. Without this function we can't start. :( 
Thank you!

**Comment by manwenick** [comment]
@mariuszkrzaczkowski still no assignment to a milesstone. :(

**Comment by mariuszkrzaczkowski** [comment]
> @vovpff I tried to import your file also in https://gitdeveloper.yetiforce.com. After importing this product I see the system default currency. BUT if I want to change it there is the same situation with currency. I can't select another currency.
> ![2018-08-24 16_08_32-products edit](https://user-images.githubusercontent.com/34367573/44589154-0f75ce80-a7b8-11e8-8c55-3f828f3ccc87.jpg)
> ![2018-08-24 16_07_43-products list](https://user-images.githubusercontent.com/34367573/44589155-0f75ce80-a7b8-11e8-9794-324673fbf076.jpg)
> 
> Maybe bug?

FIxed in https://github.com/YetiForceCompany/YetiForceCRM/commit/ddaa3c7c5b74561973e552dcde356aad22ff1848
