### ISSUE TITLE
[QUESTION] Limitations of the system?

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#7811]
I have a question:
What happens if I have more than 4,000 active users? Can the system work?
Is there a limit to the number of records and users?
Thanks for your help.

**Comment by ldgbc** [comment]
That quite a numbers of user active at the same time. I think that would usually mean you need to increase your server limitation, for example memory. I'm no administration but there is probably few other setting you need to increase. See how yours is doing right now with the numbers user you currently have:

Under **Server information**
/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65

Then the second part is hardware, can you HDD handle that much changes? Can your CPU process it fast enough?

In term of software, I remember reading one of the admin saying how effective Yetiforce was build and that it can do amazingly thing in term of that. I can't find where it is but I think it was an issue of collaboration with this Paid PDF module.

But whether Yetiforce force can live up to that claim or not require a stress test which I don't think has ever been done yet.

**Comment by bpabiszczak** [comment]
"FROM SMALL SCALE DEPLOYMENTS, TO DEPLOYMENTS FOR 12.000 USERS IN ONE SYSTEM"

**Comment by acsinsurancegroup** [comment]
Greetz :)

I don't have an issue at all. Great system! I just have a simple question. Please forgive me as I am new to this platform so don't know if this is the right place to ask, or if this has already been answered. From a customization standpoint, how do you add like a corporate background or something to the login page so it's not just a blank page?

YetiForce Version used: 4.4.0
Browser name and version: Chrome / Latest
Environment name and version: Stable Version
Operating System and version: Linux Mint 19

Thanks so much!

**Comment by ldgbc** [comment]
Manage to find this, if you want to further push the limit of your system, tweak that. I haven't tried it yet but will be trying it. Another chance to corrupt and break my system (hopefully it just crash and not corrupt anything).

https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/performance.php

**Comment by acsinsurancegroup** [comment]
Thank you @Idgbc :)
