### ISSUE TITLE
Click on widget broke List view

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7829]
#### Issue

I tried to view records from widget and when click on these show me broken List view.

#### Actual Behavior

![widgetlistviewbroken](https://user-images.githubusercontent.com/30116021/44567124-ac654700-a779-11e8-8c1f-9d190f9f421e.gif)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: Gitdev
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rafalpospiech** [comment]
This problem shows up only in demo version of yeti, because of bugged test data generation.
Your local version should be ok.
Anyway we are working on it, thanks for report!
