### ISSUE TITLE
Error when export PDF

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7830]
#### Issue

Tried to export PDF, and showing me error.

#### Actual Behavior

![pdfexport](https://user-images.githubusercontent.com/30116021/44567293-7379a200-a77a-11e8-8056-1b7bac5feb40.png)

Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/mPDF/mpdf.php on line 10894

Warning: Cannot modify header information - headers already sent by (output started at /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/mPDF/mpdf.php:10894) in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/mPDF/mpdf.php on line 9403

#0 modules/Vtiger/pdfs/Mpdf.php(284): mPDF->Output('invoice_en.pdf', 'I')
#1 modules/Vtiger/pdfs/Mpdf.php(336): Vtiger_Mpdf_Pdf->output('invoice_en.pdf', 'I')
#2 modules/Vtiger/models/PDF.php(517): Vtiger_Mpdf_Pdf->export('1016', 'FInvoice', 27, '', '')
#3 modules/Vtiger/actions/PDF.php(98): Vtiger_PDF_Model::exportToPdf('1016', 'FInvoice', 27)
#4 [internal function]: Vtiger_PDF_Action->generate(Object(App\Request))
#5 app/Controller/ExposeMethod.php(63): call_user_func_array(Array, Array)
#6 app/Controller/ExposeMethod.php(76): Vtiger_PDF_Action->invokeExposedMethod('generate', Object(App\Request))
#7 include/main/WebUI.php(183): Vtiger_PDF_Action->process(Object(App\Request))
#8 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#9 public_html/index.php(11): require('/home/gitdevelo...')
#10 {main}

#0 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#1 [info] Opening DB connection: mysql:host=localhost;dbname=gitdevelop_crm;port=3306 || yii\db\Connection::open
#2 [info] SELECT `crmid`, `setype`, `deleted`, `smcreatorid`, `smownerid`, `createdtime`, `private` FROM `vtiger_crmentity` WHERE `crmid`='1016' || yii\db\Command::query
#3 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#4 [info] SELECT * FROM `a_yf_pdf` WHERE `pdfid`=27 LIMIT 1 || yii\db\Command::query
#5 [trace] Entering getColumnFields(FInvoice) method ...
#6 [trace] Exiting getColumnFields method ...
#7 [info] SELECT `u_yf_finvoice`.`subject` AS `u_yf_finvoicesubject`, `u_yf_finvoice`.`paymentdate` AS `u_yf_finvoicepaymentdate`, `u_yf_finvoice`.`saledate` AS `u_yf_finvoicesaledate`, `u_yf_finvoice`.`accountid` AS `u_yf_finvoiceaccountid`, `u_yf_finvoice`.`finvoice_formpayment` AS `u_yf_finvoicefinvoice_formpayment`, `u_yf_finvoice`.`number` AS `u_yf_finvoicenumber`, `vtiger_crmentity`.`smownerid` AS `vtiger_crmentityassigned_user_id`, `vtiger_crmentity`.`createdtime` AS `vtiger_crmentitycreatedtime`, `vtiger_crmentity`.`modifiedtime` AS `vtiger_crmentitymodifiedtime`, `u_yf_finvoice_address`.`poboxa` AS `u_yf_finvoice_addresspoboxa`, `u_yf_finvoice_address`.`localnumbera` AS `u_yf_finvoice_addresslocalnumbera`, `u_yf_finvoice_address`.`buildingnumbera` AS `u_yf_finvoice_addressbuildingnumbera`, `u_yf_finvoice_address`.`addresslevel8a` AS `u_yf_finvoice_addressaddresslevel8a`, `u_yf_finvoice_address`.`addresslevel7a` AS `u_yf_finvoice_addressaddresslevel7a`, `u_yf_finvoice_address`.`addresslevel6a` AS `u_yf_finvoice_addressaddresslevel6a`, `u_yf_finvoice_address`.`addresslevel5a` AS `u_yf_finvoice_addressaddresslevel5a`, `u_yf_finvoice_address`.`addresslevel4a` AS `u_yf_finvoice_addressaddresslevel4a`, `u_yf_finvoice_address`.`addresslevel3a` AS `u_yf_finvoice_addressaddresslevel3a`, `u_yf_finvoice_address`.`addresslevel2a` AS `u_yf_finvoice_addressaddresslevel2a`, `u_yf_finvoice_address`.`addresslevel1a` AS `u_yf_finvoice_addressaddresslevel1a`, `u_yf_finvoice`.`sum_total` AS `u_yf_finvoicesum_total`, `u_yf_finvoice`.`sum_gross` AS `u_yf_finvoicesum_gross`, `u_yf_finvoice`.`finvoice_status` AS `u_yf_finvoicefinvoice_status`, `u_yf_finvoice`.`finvoice_paymentstatus` AS `u_yf_finvoicefinvoice_paymentstatus`, `u_yf_finvoice`.`finvoice_type` AS `u_yf_finvoicefinvoice_type`, `vtiger_crmentity`.`private` AS `vtiger_crmentityprivate`, `vtiger_crmentity`.`shownerid` AS `vtiger_crmentityshownerid`, `vtiger_crmentity`.`attention` AS `vtiger_crmentityattention`, `vtiger_crmentity`.`description` AS `vtiger_crmentitydescription`, `u_yf_finvoice`.`pscategory` AS `u_yf_finvoicepscategory`, `vtiger_crmentity`.`deleted` FROM `vtiger_crmentity` LEFT JOIN `u_yf_finvoice` ON vtiger_crmentity.crmid = u_yf_finvoice.finvoiceid LEFT JOIN `u_yf_finvoicecf` ON vtiger_crmentity.crmid = u_yf_finvoicecf.finvoiceid LEFT JOIN `u_yf_finvoice_address` ON vtiger_crmentity.crmid = u_yf_finvoice_address.finvoiceaddressid WHERE (`vtiger_crmentity`.`crmid`='1016') AND (`vtiger_crmentity`.`setype`='FInvoice') LIMIT 1 || yii\db\Command::query
#8 [info] SELECT DISTINCT `userid` FROM `u_yf_crmentity_showners` WHERE `crmid`='1016' || yii\db\Command::query
#9 [trace] Start DateTimeField::convertToUserTimeZone(2018-08-24 07:46:26) method ...
#10 [trace] Start DateTimeField::convertTimeZone(2018-08-24 07:46:26, Europe/Warsaw, Europe/Warsaw)
#11 [trace] End DateTimeField::convertTimeZone
#12 [trace] End DateTimeField::convertToUserTimeZone
#13 [trace] Start DateTimeField::__convertToUserFormat s:10:"2018-08-24"; | yyyy-mm-dd
#14 [trace] End DateTimeField::__convertToUserFormat
#15 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#16 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#17 [trace] Entering App\Field::getFieldPermission: 95,saledate
#18 [trace] Entering App\Field::getFieldsPermissions: 95
#19 [trace] Start DateTimeField::__convertToUserFormat a:1:{i:0;s:10:"2018-07-28";} | yyyy-mm-dd
#20 [trace] End DateTimeField::__convertToUserFormat
#21 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#22 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#23 [trace] Entering App\Field::getFieldPermission: 95,finvoice_formpayment
#24 [trace] Entering App\Field::getFieldsPermissions: 95
#25 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#26 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#27 [trace] Entering App\Field::getFieldPermission: 95,number
#28 [trace] Entering App\Field::getFieldsPermissions: 95
#29 [info] Cannot translate this: 'LBL_COMPANY_LOGO' for module '_Base', lang: en_us
#30 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#31 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#32 [info] SELECT `crmid`, `setype`, `deleted`, `smcreatorid`, `smownerid`, `createdtime`, `private` FROM `vtiger_crmentity` WHERE `crmid`=241 || yii\db\Command::query
#33 [trace] Entering getColumnFields(Accounts) method ...
#34 [trace] Exiting getColumnFields method ...
#35 [info] SELECT `vtiger_account`.`accountname` AS `vtiger_accountaccountname`, `vtiger_account`.`account_no` AS `vtiger_accountaccount_no`, `vtiger_account`.`phone` AS `vtiger_accountphone`, `vtiger_account`.`website` AS `vtiger_accountwebsite`, `vtiger_account`.`fax` AS `vtiger_accountfax`, `vtiger_account`.`otherphone` AS `vtiger_accountotherphone`, `vtiger_account`.`parentid` AS `vtiger_accountaccount_id`, `vtiger_account`.`email1` AS `vtiger_accountemail1`, `vtiger_account`.`employees` AS `vtiger_accountemployees`, `vtiger_account`.`email2` AS `vtiger_accountemail2`, `vtiger_account`.`ownership` AS `vtiger_accountownership`, `vtiger_account`.`industry` AS `vtiger_accountindustry`, `vtiger_account`.`siccode` AS `vtiger_accountsiccode`, `vtiger_account`.`account_type` AS `vtiger_accountaccounttype`, `vtiger_account`.`annualrevenue` AS `vtiger_accountannual_revenue`, `vtiger_account`.`emailoptout` AS `vtiger_accountemailoptout`, `vtiger_crmentity`.`smownerid` AS `vtiger_crmentityassigned_user_id`, `vtiger_crmentity`.`createdtime` AS `vtiger_crmentitycreatedtime`, `vtiger_crmentity`.`modifiedtime` AS `vtiger_crmentitymodifiedtime`, `vtiger_crmentity`.`modifiedby` AS `vtiger_crmentitymodifiedby`, `vtiger_crmentity`.`description` AS `vtiger_crmentitydescription`, `vtiger_account`.`isconvertedfromlead` AS `vtiger_accountisconvertedfromlead`, `vtiger_crmentity`.`smcreatorid` AS `vtiger_crmentitycreated_user_id`, `vtiger_account`.`vat_id` AS `vtiger_accountvat_id`, `vtiger_account`.`registration_number_1` AS `vtiger_accountregistration_number_1`, `vtiger_account`.`registration_number_2` AS `vtiger_accountregistration_number_2`, `vtiger_accountaddress`.`addresslevel1a` AS `vtiger_accountaddressaddresslevel1a`, `vtiger_accountaddress`.`addresslevel1b` AS `vtiger_accountaddressaddresslevel1b`, `vtiger_accountaddress`.`addresslevel2a` AS `vtiger_accountaddressaddresslevel2a`, `vtiger_accountaddress`.`addresslevel2b` AS `vtiger_accountaddressaddresslevel2b`, `vtiger_accountaddress`.`addresslevel3a` AS `vtiger_accountaddressaddresslevel3a`, `vtiger_accountaddress`.`addresslevel3b` AS `vtiger_accountaddressaddresslevel3b`, `vtiger_accountaddress`.`addresslevel4a` AS `vtiger_accountaddressaddresslevel4a`, `vtiger_accountaddress`.`addresslevel4b` AS `vtiger_accountaddressaddresslevel4b`, `vtiger_accountaddress`.`addresslevel5a` AS `vtiger_accountaddressaddresslevel5a`, `vtiger_accountaddress`.`addresslevel5b` AS `vtiger_accountaddressaddresslevel5b`, `vtiger_accountaddress`.`addresslevel6a` AS `vtiger_accountaddressaddresslevel6a`, `vtiger_accountaddress`.`addresslevel6b` AS `vtiger_accountaddressaddresslevel6b`, `vtiger_accountaddress`.`addresslevel7a` AS `vtiger_accountaddressaddresslevel7a`, `vtiger_accountaddress`.`addresslevel7b` AS `vtiger_accountaddressaddresslevel7b`, `vtiger_accountaddress`.`addresslevel8a` AS `vtiger_accountaddressaddresslevel8a`, `vtiger_accountaddress`.`addresslevel8b` AS `vtiger_accountaddressaddresslevel8b`, `vtiger_accountaddress`.`addresslevel1c` AS `vtiger_accountaddressaddresslevel1c`, `vtiger_accountaddress`.`addresslevel2c` AS `vtiger_accountaddressaddresslevel2c`, `vtiger_accountaddress`.`addresslevel3c` AS `vtiger_accountaddressaddresslevel3c`, `vtiger_accountaddress`.`addresslevel4c` AS `vtiger_accountaddressaddresslevel4c`, `vtiger_accountaddress`.`addresslevel5c` AS `vtiger_accountaddressaddresslevel5c`, `vtiger_accountaddress`.`addresslevel6c` AS `vtiger_accountaddressaddresslevel6c`, `vtiger_accountaddress`.`addresslevel7c` AS `vtiger_accountaddressaddresslevel7c`, `vtiger_accountaddress`.`addresslevel8c` AS `vtiger_accountaddressaddresslevel8c`, `vtiger_account`.`verification` AS `vtiger_accountverification`, `vtiger_accountaddress`.`buildingnumbera` AS `vtiger_accountaddressbuildingnumbera`, `vtiger_accountaddress`.`localnumbera` AS `vtiger_accountaddresslocalnumbera`, `vtiger_accountaddress`.`buildingnumberb` AS `vtiger_accountaddressbuildingnumberb`, `vtiger_accountaddress`.`localnumberb` AS `vtiger_accountaddresslocalnumberb`, `vtiger_accountaddress`.`buildingnumberc` AS `vtiger_accountaddressbuildingnumberc`, `vtiger_accountaddress`.`localnumberc` AS `vtiger_accountaddresslocalnumberc`, `vtiger_account`.`no_approval` AS `vtiger_accountno_approval`, `vtiger_crmentity`.`attention` AS `vtiger_crmentityattention`, `vtiger_account`.`balance` AS `vtiger_accountbalance`, `vtiger_crmentity`.`shownerid` AS `vtiger_crmentityshownerid`, `vtiger_crmentity`.`closedtime` AS `vtiger_crmentityclosedtime`, `vtiger_accountaddress`.`poboxa` AS `vtiger_accountaddresspoboxa`, `vtiger_accountaddress`.`poboxb` AS `vtiger_accountaddresspoboxb`, `vtiger_accountaddress`.`poboxc` AS `vtiger_accountaddresspoboxc`, `vtiger_crmentity`.`was_read` AS `vtiger_crmentitywas_read`, `vtiger_account`.`payment_balance` AS `vtiger_accountpayment_balance`, `vtiger_account`.`legal_form` AS `vtiger_accountlegal_form`, `vtiger_account`.`sum_time` AS `vtiger_accountsum_time`, `vtiger_account`.`inventorybalance` AS `vtiger_accountinventorybalance`, `vtiger_account`.`discount` AS `vtiger_accountdiscount`, `vtiger_account`.`creditlimit` AS `vtiger_accountcreditlimit`, `vtiger_account`.`products` AS `vtiger_accountproducts`, `vtiger_account`.`services` AS `vtiger_accountservices`, `vtiger_entity_stats`.`crmactivity` AS `vtiger_entity_statscrmactivity`, `vtiger_account`.`last_invoice_date` AS `vtiger_accountlast_invoice_date`, `vtiger_account`.`active` AS `vtiger_accountactive`, `vtiger_account`.`accounts_status` AS `vtiger_accountaccounts_status`, `vtiger_crmentity`.`private` AS `vtiger_crmentityprivate`, `vtiger_account`.`phone_extra` AS `vtiger_accountphone_extra`, `vtiger_account`.`fax_extra` AS `vtiger_accountfax_extra`, `vtiger_account`.`otherphone_extra` AS `vtiger_accountotherphone_extra`, `vtiger_crmentity`.`deleted` FROM `vtiger_crmentity` LEFT JOIN `vtiger_account` ON vtiger_crmentity.crmid = vtiger_account.accountid LEFT JOIN `vtiger_accountaddress` ON vtiger_crmentity.crmid = vtiger_accountaddress.accountaddressid LEFT JOIN `vtiger_accountscf` ON vtiger_crmentity.crmid = vtiger_accountscf.accountid LEFT JOIN `vtiger_entity_stats` ON vtiger_crmentity.crmid = vtiger_entity_stats.crmid WHERE (`vtiger_crmentity`.`crmid`=241) AND (`vtiger_crmentity`.`setype`='Accounts') LIMIT 1 || yii\db\Command::query
#36 [info] SELECT DISTINCT `userid` FROM `u_yf_crmentity_showners` WHERE `crmid`=241 || yii\db\Command::query
#37 [trace] Entering isPermitted(Accounts,DetailView,241,) method ...
#38 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#39 [trace] Entering App\Field::getFieldPermission: 6,accountname
#40 [trace] Entering App\Field::getFieldsPermissions: 6
#41 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#42 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#43 [trace] Entering isPermitted(Accounts,DetailView,241,) method ...
#44 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#45 [trace] Entering App\Field::getFieldPermission: 6,addresslevel8a
#46 [trace] Entering App\Field::getFieldsPermissions: 6
#47 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#48 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#49 [trace] Entering isPermitted(Accounts,DetailView,241,) method ...
#50 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#51 [trace] Entering App\Field::getFieldPermission: 6,buildingnumbera
#52 [trace] Entering App\Field::getFieldsPermissions: 6
#53 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#54 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#55 [trace] Entering isPermitted(Accounts,DetailView,241,) method ...
#56 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#57 [trace] Entering App\Field::getFieldPermission: 6,addresslevel7a
#58 [trace] Entering App\Field::getFieldsPermissions: 6
#59 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#60 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#61 [trace] Entering isPermitted(Accounts,DetailView,241,) method ...
#62 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#63 [trace] Entering App\Field::getFieldPermission: 6,addresslevel5a
#64 [trace] Entering App\Field::getFieldsPermissions: 6
#65 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#66 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#67 [trace] Entering isPermitted(Accounts,DetailView,241,) method ...
#68 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#69 [trace] Entering App\Field::getFieldPermission: 6,vat_id
#70 [trace] Entering App\Field::getFieldsPermissions: 6
#71 [info] SHOW TABLES || yii\db\Command::query
#72 [info] SELECT * FROM `u_yf_finvoice_invfield` WHERE `presence`=0 ORDER BY `sequence` || yii\db\Command::query
#73 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#74 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#75 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#76 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#77 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#78 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#79 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#80 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#81 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#82 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#83 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#84 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#85 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#86 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#87 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#88 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#89 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#90 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#91 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#92 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#93 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#94 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#95 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#96 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#97 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#98 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#99 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#100 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#101 [info] SELECT * FROM `u_yf_finvoice_invfield` WHERE `presence`=0 ORDER BY `sequence` || yii\db\Command::query
#102 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#103 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#104 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#105 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#106 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#107 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#108 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#109 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#110 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#111 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#112 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#113 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#114 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#115 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#116 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#117 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#118 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#119 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#120 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#121 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#122 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#123 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#124 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#125 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#126 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#127 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#128 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#129 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#130 [info] SELECT * FROM `vtiger_currency_info` WHERE `defaultid` < '0' LIMIT 1 || yii\db\Command::query
#131 [trace] Entering Vtiger_Record_Model::getInventoryData
#132 [info] SELECT * FROM `u_yf_finvoice_inventory` WHERE `id`=1016 || yii\db\Command::query
#133 [trace] Exiting Vtiger_Record_Model::getInventoryData
#134 [info] SELECT `crmid`, `setype`, `deleted`, `smcreatorid`, `smownerid`, `createdtime`, `private` FROM `vtiger_crmentity` WHERE `crmid`=646 || yii\db\Command::query
#135 [trace] Entering Vtiger_Record_Model::getInventoryData
#136 [trace] Exiting Vtiger_Record_Model::getInventoryData
#137 [info] SELECT * FROM `vtiger_currency_info` WHERE `defaultid` < '0' LIMIT 1 || yii\db\Command::query
#138 [trace] Entering Vtiger_Record_Model::getInventoryData
#139 [trace] Exiting Vtiger_Record_Model::getInventoryData
#140 [info] SELECT * FROM `vtiger_currency_info` WHERE `defaultid` < '0' LIMIT 1 || yii\db\Command::query
#141 [trace] Entering Vtiger_Record_Model::getInventoryData
#142 [trace] Exiting Vtiger_Record_Model::getInventoryData
#143 [info] SELECT * FROM `vtiger_currency_info` WHERE `defaultid` < '0' LIMIT 1 || yii\db\Command::query
#144 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#145 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#146 [trace] Entering App\Field::getFieldPermission: 95,sum_gross
#147 [trace] Entering App\Field::getFieldsPermissions: 95
#148 [trace] Entering isPermitted(FInvoice,DetailView,1016,) method ...
#149 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#150 [trace] Entering App\Field::getFieldPermission: 95,attention
#151 [trace] Entering App\Field::getFieldsPermissions: 95
#152 [error] Some data has already been output to browser, can't send PDF file
MpdfException: Some data has already been output to browser, can't send PDF file in vendor/mPDF/mpdf.php:9405
Stack trace:
#0 modules/Vtiger/pdfs/Mpdf.php(284): mPDF->Output('invoice_en.pdf', 'I')
#1 modules/Vtiger/pdfs/Mpdf.php(336): Vtiger_Mpdf_Pdf->output('invoice_en.pdf', 'I')
#2 modules/Vtiger/models/PDF.php(517): Vtiger_Mpdf_Pdf->export('1016', 'FInvoice', 27, '', '')
#3 modules/Vtiger/actions/PDF.php(98): Vtiger_PDF_Model::exportToPdf('1016', 'FInvoice', 27)
#4 [internal function]: Vtiger_PDF_Action->generate(Object(App\Request))
#5 app/Controller/ExposeMethod.php(63): call_user_func_array(Array, Array)
#6 app/Controller/ExposeMethod.php(76): Vtiger_PDF_Action->invokeExposedMethod('generate', Object(App\Request))
#7 include/main/WebUI.php(183): Vtiger_PDF_Action->process(Object(App\Request))
#8 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#9 public_html/index.php(11): require('/home/gitdevelo...')
#10 {main}

#### How to trigger the error

1. Log in gitdev
2.Go to Sales Invoice
3. Export PDF

#### Your Environment

* YetiForce Version used: Gitdev
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Environment?

**Comment by rafalpospiech** [comment]
We are changing PDF generation library right now. We are building html to pdf generator from scratch. After we finish, problem will vanish.

**Comment by bpabiszczak** [comment]
We display all errors on gitdeveloper, this causes errors.
