### ISSUE TITLE
Connection to storage server failed. Roundcube mail issue

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#7833]
#### Issue

I am trying to connect to round cube and when I try to connect I get the error after some time loading about 1-2 minutes. That the connection to storage server failed

#### Actual Behavior

The error is Connection to storage server failed.

#### Expected Behavior

I would like to be able to use roundcube to access my mail

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Opera version 55.0
* Environment name and version: Linux Mint 19
* Operating System and version:Linux MInt 19

**Comment by ldgbc** [comment]
Need logs for something like this. Please learn how to enable debug logs.

My best suggestion is to figure out if it YOUR email server having issue, configuration issue or administration error.

Best to test it with a well know email server that is more "open" (yahoo, hotmail, gmail, etc). See if that work.

**Comment by bangde** [comment]
Thank you. I will enable the debug logs.

My server configuration is correct. I am using Zoho mail and the system was able to send a test email to my Zoho mail. The issue is starting Roundcube in the CRM system.

I will take your advice and enable the debug log and  post what I get

**Comment by bangde** [comment]
hi there after going to my log i can see this issue

[25-Aug-2018 01:46:45 +0800]: <8985decf> IMAP Error: Login failed for sheldon@sjconsultinggroup-asia.com from 210.185.167.135. Empty startup greeting (mail.sjconsultinggroup-asia.com:993) in /home/smartfar/crm.smartfarms.asia/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_imap.php on line 196 (POST /public_html/modules/OSSMail/roundcube/?_task=login&_action=login)

**Comment by bangde** [comment]
Hi there
PLease see the  screen shot of my mail settings
![smartfarms_current_settings](https://user-images.githubusercontent.com/7829825/44658372-2e33c980-aa33-11e8-98d2-9aeed377e236.png)

This is my server mail settings
![mail setting screenshot](https://user-images.githubusercontent.com/7829825/44658395-460b4d80-aa33-11e8-8b8c-25e9effd00ee.png)

**Comment by ldgbc** [comment]
Everything seem good on the email setting. So it most likely Installation or Server configuration.

Are you able to do a test on a XAMPP version? Can't really help you any further, this is out of my league.

**Comment by thejdc** [comment]
@bangde 
If you are still having this issue please read this post: [https://github.com/roundcube/roundcubemail/issues/6016](url) . I was having the same issue as you are. In that post CRtEurope posts: "Change $config['default_host'] = 'tls://mail.example.com'; to $config['default_host'] = 'ssl://mail.example.com';
in the IMAP section. Then it should work."

No need to edit any files. Just add the ssl:// or tls:// to your server names in your mail settings, for example ssl://mail.sjconsultinggroup-asia.com . Hopefully it will work. I notice you have the box checked for adding this automatically (I think thats what its supposed to do) but I don't think it's doing it.

Hope that helps, good luck.

**Comment by rskrzypczak** [comment]
Yes, add ssl:// or tls:// to the server name like @thejdc said.
Check if you disabled verification of ssl https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/OSSMail.php#L69-L80
If this doesn't help try to enable roundcube logs (link), maybe that will provide some answers https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/debug.php#L81-L101.
