### ISSUE TITLE
[v4.4.0] Edit Language/Translation for Address File [question]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7835]
#### Issue
Would like to modify the address field, "City/Village" to something else. Copying "_Base.json", and changing it doesn't seem to work. Open all file to search for it, couldn't find anything. Tried using the /index.php?module=LangManagement&parent=Settings&view=Index&block=4&fieldid=53
but there is nothing there.

#### Actual Behavior
Unable to modify any of the text for City/Village.

#### Expected Behavior
Able to change it.

#### How to trigger the error
1. https://github.com/YetiForceCompany/YetiForceCRM/blob/b24212b4d5e8a201d364b4013f3c8ac7eb629ac8/languages/en_us/_Base.json
2. Create a new English file based on en-us. For example: en-au.
3. Try to modify the 
"AddressLevel5": "City/Village" field into something like  "AddressLevel5": "City",
4. Is unable to.

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: FF61
* Environment name and version: XAMPP
* Operating System and version: XAMPP

**Comment by arek1-618** [comment]
Hello, Sir
To add a new language, use the panel. 

![2018-11-21_14-51-05](https://user-images.githubusercontent.com/32322851/48846410-641ceb80-ed9f-11e8-9fdd-7cb818dffe25.gif)

Then you have to edit the /en_au/_Base.json file.

![phpstorm64_2018-11-21_15-01-43](https://user-images.githubusercontent.com/32322851/48846436-6f701700-ed9f-11e8-859a-e769f4e19a7a.png)
![firefox_2018-11-21_15-03-24](https://user-images.githubusercontent.com/32322851/48846482-89a9f500-ed9f-11e8-9a40-de99fb006a84.png)
