### ISSUE TITLE
[BUG][4.4.33][Multipicklist field] Records doesn't match with the filter on multipicklist field

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#7840]
#### Issue
I have a multipicklist field in a filter and I want to show all records that match with my filter. 
It doesn't show the records where the last value of the field is the value i'm searching for, but if it is not the last value, it shows me.

#### Actual Behavior
Doesn't show all records that match the value of the field.

#### Expected Behavior
Show all records that match the value of the field.

#### How to trigger the error
![2018-08-24_14-09-48](https://user-images.githubusercontent.com/16593721/44586613-39bf9000-a7a8-11e8-96e4-63eaa8bdc948.gif)

#### Your Environment
* YetiForce Version used: Latest version (4.4.33)
* Browser name and version: Google Chrome
* Operating System and version: Windows 10

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/c3ed8e5d7ba8595f11bd389b556022df841db94b
