### ISSUE TITLE
[4.4 v2] Popup in calendar not dissapear

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7842]
#### Issue

When agenda mode for week and day view active after long time click appears small popup but not dissapear when quick window appears. Only page refresh helps (F5)

Can't be tested on gitdev because agenda option can't be activated.

![cal popup](https://user-images.githubusercontent.com/8545791/44629089-d160e200-a952-11e8-92b0-f09a66f4d0d7.gif)

Configurations of all system perfect.

#### Your Environment

* YetiForce Version used: 4.3, 4.4v2
* Browser name and version: Chrome
* Environment name and version: last LAMP with PHP 7.1
* Operating System and version: Ubuntu

**Comment by poradz** [comment]
This bug is already fixed so I close this issue
![popover-calendar](https://user-images.githubusercontent.com/31520119/46459204-7b385780-c7b8-11e8-8536-8d577453c98c.gif)

**Comment by vovpff** [comment]
@poradz thx!
