### ISSUE TITLE
Global search resolve nothing

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#7853]
#### Issue
Trying to find any search in the global search form, any know value that should appear

#### Actual Behavior
There is always zero result

#### Expected Behavior
Resolve the search query

#### How to trigger the error

1. Make any search at global search, indicating any value (All records)
2. Resolves nothing (see attached)
3.

#### Screenshot of configuration

* YetiForce Version used: last one
* Browser name and version: all browsers
* Environment name and version: LAMP Centos 7 PHP 7.0 Mysql 5.56
* Operating System and version: Centos 7

**Comment by vovpff** [comment]
@santyabreu what about your cron? is it activated?

**Comment by ldgbc** [comment]
Like vovpff suggested, you need CRON to search. Basically, CRON (scheduling service), run a Task (Update Index), Search (Ctrl+Find information from index).

You might also want to change the UI Search field to include more search information. Anyway once CRON is activate and run successfully you can search.

**Comment by vovpff** [comment]
@santyabreu check `u_yf_crmentity_search_label` table in your CRM database. This table must be filled with a lot of data for every `crmid` in you system.
