### ISSUE TITLE
[Question] Advanced search

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#7858]
I tried to turn it off but it does not seem to work. I have tried on many previous versions and also gitdev.
am i misunderstanding something?
![zalo_screenshot_28_8_2018_911124](https://user-images.githubusercontent.com/19627226/44713391-347e8000-aadd-11e8-812e-b065dea7a8eb.png)
![zalo_screenshot_28_8_2018_911618](https://user-images.githubusercontent.com/19627226/44713421-43653280-aadd-11e8-9b42-893dbe4c556d.png)
![zalo_screenshot_28_8_2018_912530](https://user-images.githubusercontent.com/19627226/44713422-43fdc900-aadd-11e8-9b1b-daedcd5fd796.png)

**Comment by ldgbc** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Roles&parent=Settings&view=Edit&record=H2

Can confirm with version: 4.4.33. I made change to the Board of Management as a test but it get revert back after refresh.

**Comment by vovpff** [comment]
@ezbank looks like check box not working proper
