### ISSUE TITLE
[ver. 4.4.33] User large avatar/profile [bug]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7859]
#### Issue
Big avatar/profile image in user.

#### Actual Behavior
Taking up screen estate.

#### Expected Behavior
Smaller, maybe 100px?

#### How to trigger the error
1. https://gitdeveloper.yetiforce.com/index.php?module=Users&parent=Settings&view=List&block=1&fieldid=1
2. 
![image](https://user-images.githubusercontent.com/1805303/44714271-428dca00-aaf8-11e8-9d0d-a54d364f89d0.png)

#### Your Environment

* YetiForce Version used:  4.4.33
* Browser name and version: FF61
* Environment name and version: YF
* Operating System and version: YF

**Comment by mlorencik** [comment]
in 4.4.34, I don't see anything like you sent
![przechwytywanie](https://user-images.githubusercontent.com/11301300/44844031-14b89a80-ac4a-11e8-8256-e849dd041fb0.PNG)
