### ISSUE TITLE
QUESTION YetiForce Sale process for B2C

### ISSUE THREAD

**Issue by manwenick** [YetiForceCompany/YetiForceCRM#7860]
Hello everyone, 

I try to implement YetiForce on a client site for e-commerce business. At the moment we have a problem with a sale process. Maybe there is a work-around possible. Maybe it could be enchancement for YetiForce in future releases. 
Our clients are privat persons. They ask for products, which we offer. 
If the client contact us, I need to save the data about a contact (not about an account, because there is no one and there will be no account regarding to this contact). After I have saved the information about the contact, I need to create a sales order, which should rely to a contact before. 
Is there any options which can help us to connect the sales orders module with contact module?
Or any other ideas?

In B2B everything works fine.

What do the community think about it?

**Comment by ldgbc** [comment]
Personally I set up mine as follow: Account = Company, Contact = Person. Of course Yetiforce isn't design like that.

Account is where most information matter and it is the central part. Maybe reading this page will help you:

https://yetiforce.com/en/knowledge-base/documentation/user-documentation/category/sales-process
https://yetiforce.com/en/knowledge-base/documentation/user-documentation/item/b2c-vs-b2b-in-marketing

Overall page: https://yetiforce.com/en/knowledge-base/documentation/user-documentation

**Comment by manwenick** [comment]
@ldgbc It sounds good. But If I want to see kind of 360° analysis about a customer i.e. which products he/she had bought in the past, I can't see this at the moment. Only if I rely any products to Account. Also if I want to see the leads who is interesting in some products, so I can better plan the production of these products based on the interess of the end customer. 
I also tried to do it the way you describe: Account = Company, Contact = Person. In my case it doesn't make a sense to create account with the same name. If I issue a bill I need the first name, last name, adress of the contact (I didn't found the fields in account) and the products which are related to this sale order. 
Maybe I don't know YetiForce good enough and there is a way to realize this requirement?

**Comment by ldgbc** [comment]
Hi @manwenick 

Currently I'm issuing invoice on a separate system, I haven't learn YF invoice system well enough. Creating the PDF export is also troublesome at the moment, it static and won't allow too much of editing freedom which from a design point of view is good.

But from a dynamic view, it is restrictive and if I want to add minor changes I need to create a new field for it.

Unfortunately like I said, the Account = Company, Contact = Person is unconventional so it won't work well with YF unless you tweak it.

For your 360 overview you can just refer to this page:
https://gitstable.yetiforce.com/index.php?module=Accounts&view=Detail&record=217&mode=showRelatedProductsServices&requestMode=summary&tab_label=LBL_RECORD_SUMMARY_PRODUCTS_SERVICES

For your First Name and Last Name, you can just create a new field in your Accounts Module.

With regard to Leads, Leads should be converted to an Account once there is an Opportunity or sales.

Of course this is just all my understanding. On our system it is more of, "Company, Contact, Client, Activity, Documents, Projects and Assets". We don't really use other function until I integrate it successfully.
