### ISSUE TITLE
question, field for file upload in custom module

### ISSUE THREAD

**Issue by BraulioBracamonte** [YetiForceCompany/YetiForceCRM#7864]
hi, is there a way to create a "upload file" field in a custom module?

**Comment by vovpff** [comment]
@BraulioBracamonte i think you need to add attachment relation for this custom module.

**Comment by TomaszQr** [comment]
If you want to add files to your own module you have to add a relation between documents and your new module. If you only want to add images then the system has the option to add a gallery field.
![7864](https://user-images.githubusercontent.com/14273211/44785455-40c41500-ab91-11e8-83b4-1dda943d50b5.png)
