### ISSUE TITLE
integration with freepbx or asterisk 

### ISSUE THREAD

**Issue by MicroSolve** [YetiForceCompany/YetiForceCRM#7874]
Dears , good day i have issue with my crm 4.4.0 as i try to integration with freepbx server but i fail.

there is any doc to help and how to ?! integration with asterisk or freepbx 

thanks !!

**Comment by ldgbc** [comment]
There is no official documents showing how to integrate. I don't have an account so I can't guide you either.

But based on experience I would say this is what you need to do:
(1) find your account setting, API, Username, Server, Port Number, URL
2) Enable it in Yetiforce and enter the information.
3) Use it as normal

Of course there is a few issue you have to find a solution yourself:
Where is the setting?
Does my server support this feature?
Is there a configuration error or module that stopping it from functioning?

A search on search engine give me some of these link that might give you a better understanding.
https://www.smackcoders.com/blog/setup-vtiger-crm-telephony-integration-asterisk.html

A search for "integrate freepbx" I would assume yield similar result.

**Comment by paula-w** [comment]
FreePBX is indeed not currently supported. We can create that integration but it's a service we charge for.
More info on why we can't implement all ideas - [article](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-development-ideas)

**Comment by groupgloval** [comment]
Hi, I need to integrate yetiforce with FreePBX, when will it be ready?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/tree/developer/app/Integrations/Pbx
