### ISSUE TITLE
[PL] Niewidoczne pola zaawansowane w module (produkty i usługi)

### ISSUE THREAD

**Issue by marcineqpol** [YetiForceCompany/YetiForceCRM#7876]
#### Issue

Po wejściu w tworzenie lub edycję: kalkulacji, zapytania do dostawcy, karty wymagań nie widać pól, w których można wybrać usługę lub produkt. Przez to moduły stają się niefunkcjonalne.
Pola te są widoczne w wersji developerskiej.

#### Actual Behavior

Nie można przypisać produktu/usługi w polach karty wymagań, kalkulacji, zapytania do dostawcy.
#### Expected Behavior

Pola widoczne jak na demo developer.
#### How to trigger the error

1.
![yeti](https://user-images.githubusercontent.com/29989759/44823509-1a3dc280-ac01-11e8-931b-268e8b32c61a.gif)

2.
3.

#### PHP/Apache/Browser Logs

EDIT: W logach nie ma nic, co można z tym powiązać.
#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Chrome 68.0.3440.106
* Environment name and version: PHP 7.2
* Operating System and version: Ubuntu (współdzielony hosting)

**Comment by marcineqpol** [comment]
Być może to samo co #7469

**Comment by bpabiszczak** [comment]
Jeśli to samo, to jest tam gotowy FIX. 
Niestety oprócz tego, że nie ma "pola" to nie wiemy nic. Pole to można włączać/wyłączać w panelu, może ktoś wyłączył pole?

**Comment by marcineqpol** [comment]
Chodziło dokładnie o te pola, o których mowa w oznaczonym przeze mnie issue. #7469 rozwiązuje problem.

**Comment by bpabiszczak** [comment]
Super, że jest tam Twoje rozwiązanie!
