### ISSUE TITLE
Product line missing

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#7881]
When i want to add a Goods Received Note, i am missing product line, to select the product and quantity. Strangely, even in  fresh installation or demo server ?!?! 

#### Your Environment
* YetiForce Version used: 4.4.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version:

**Comment by liviubbo** [comment]
![untitled](https://user-images.githubusercontent.com/42461923/44844440-3ebe8c80-ac4b-11e8-85c6-b42333fc9ee7.jpg)

**Comment by vovpff** [comment]
the same as #7469 Bug fixed but not implemented in production version
