### ISSUE TITLE
[4.3.0] Security errors

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7882]
#### Issue

Every time I get a lot of security errors at home page of admin panel.

For this time I has correct configuration except HTTPS.

I receive a lot of messages like this:

![image](https://user-images.githubusercontent.com/8545791/44845328-eb9e0700-ac55-11e8-84ec-b4b7487a5aba.png)

But I can't understand why?

**Comment by paula-w** [comment]
This error informs you that someone tried to get access to something they shouldn't be able to access.  These are logs of unauthorized events.
