### ISSUE TITLE
[Feature] QR codes

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7887]
Are the developers crew plan to implement QR codes inside system and pdf?

This feature would be very useful for some tasks.

**Comment by marcineqpol** [comment]
[PL] Przydałaby się również możliwość wydruku kodów paskowych (zwykłych 1D) w PDF. Dobre rozwiązanie do wyszukiwania np. faktur w systemie.

**Comment by bpabiszczak** [comment]
Można: https://mpdf.github.io/reference/html-control-tags/barcode.html

**Comment by marcineqpol** [comment]
:/ Jak próbuję dodać przez WYSIWYG poprzez Źródło dokumentu - nie generuje mi się kod, a po zapisaniu się z tego PDFa usuwa. Gdy wklejam bezpośrednio (wiem, godne Janusza :D ) do edycji PDF - też nie działa.

**Comment by bpabiszczak** [comment]
Nie twierdzę, że za działa "od ręki", może wymagać jakiś prac programistycznych [np. może czyścimy jakieś rzeczy przy zapisaniu w WYSIWYG].... Od strony technicznej nie ma żadnych "przeciwwskazań", ale ktoś musi do tego usiąść i to przetestować.

**Comment by vovpff** [comment]
@bpabiszczak what file need to be checked to understand why source cleaned after saving?

**Comment by ldgbc** [comment]
Yetiforce already have mPDF installed isn't it? That mean we can just use that code to generate code.

**Comment by vovpff** [comment]
@ldgbc any suggestions how to do it?

**Comment by paula-w** [comment]
We’re currently working on a new PDF library that will support QR codes and barcodes. Additionally, new variables will be added to the system for full support. 
Code generation will most likely use https://github.com/milon/barcode

**Comment by vovpff** [comment]
@paula-w thanks a lot for information. I'm already tested new PDF variables
