### ISSUE TITLE
Smarty Debug Console - memory limit

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#789]
I tried to turn on Smarty debug console.

And get this errror:

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 351665 bytes) in /home/[DOMAIN]/public_html/libraries/Smarty/libs/plugins/modifier.debug_print_var.php on line 46

strange since php memory limit is 1024 on the server.

**Comment by bpabiszczak** [comment]
It's an error that is returned by the server. I don't know how we can help you with that? You need to contact your server administrator.
