### ISSUE TITLE
More then 1 email account

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#7898]
#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: Hhrome
* Environment name and version:
* Operating System and version:

Hi.
Can i ask for help.
I try add mre email account then 1.
One is my business and i try add my privet.

**Comment by mskoczek** [comment]
I set up Roundcube for all users with business email, but i wish add my private email to. Some of my clients use my private emails.

**Comment by ldgbc** [comment]
You can add as many email as you want.

I think what you need to do is, log out of current email. Then log in new one. Then go into Setting and Add your Username to have access to that email.

The you can click the arrow button to choose all email you have access to. You can also have access to email to all your staff/employee too if you link the email in your Admin setting.

Of course if they change the password or if you don't know the password I don't think you can log it.

**Comment by mskoczek** [comment]
Ok let me say somthing.
Ok i set up Roundcube for main email ( business )
How i can add other settings for other email account ?
Do i have to remowe settings for Business and add new.
Yeti will remember old seting and new one ?

**Comment by poradz** [comment]
Hi, 

you should add another IMAP server for your private account here:
![image](https://user-images.githubusercontent.com/31520119/48841365-827bea80-ed91-11e8-8021-f1be62612b70.png)
Now you can choose server on login screen
![image](https://user-images.githubusercontent.com/31520119/48841510-ed2d2600-ed91-11e8-84eb-5bfc5732ec44.png)

and then you should do what @ldgbc said.
