### ISSUE TITLE
show related field values

### ISSUE THREAD

**Issue by ralphkretzschmar** [YetiForceCompany/YetiForceCRM#7907]
hello everyone,

i've tried to create a "show-related-field-value" field on the opportunity page, which shows a KPI from an account. (something like employees number) 

but it seems that its not possible to select data from account level.

the account is also in a relationship to the opportunity or?

does anyone have an idea to get this work?

Best regards,
Ralph

**Comment by vovpff** [comment]
@ralphkretzschmar you need to add field to opportunity and change this file https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/user_privileges/moduleHierarchy.php
