### ISSUE TITLE
Can not get the cron job to run on crm system

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#7908]
#### Issue

I am trying to get the cron job to run as it is needed for updating a few things for the crm system to run smoothly. I am on a shared hosting account where I have  added what I believe is the correct cron script to  run every 15 minutes

#### Actual Behavior

The cron is running on the server successfully but on the crm system its not running at all.

#### Expected Behavior

If the cron job is to run successfully it should get the global search working and also the location on the maps working

#### How to trigger the error

1.
2.
3.

#### Screenshot of configuration

![cron_screenshot](https://user-images.githubusercontent.com/7829825/44944677-a7edfd80-ae0d-11e8-9f3b-21d6a6195a7d.png)

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: Opera
* Environment name and version: Shared  Hosting
* Operating System and version:

**Comment by vovpff** [comment]
I'm not linux guru but I think you need to put php path into cron.sh file and remove php path from cron command

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

**Comment by bangde** [comment]
I Think I have it running now

Thanks
