### ISSUE TITLE
I dont understand how the map works and function

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#7909]
#### Issue

I see that in accounts or contacts there is a  Map. What exactly is the map for and what are the steps needed for it to work. I have tried looking for documentation and there is none. Yetiforce great software but the documentation is very minimal its hard to navigate and understand without proper documentation.

I  thought it was to show where the address of the contact or the account on the map. However, when I go to the demo as well it is not working. Can someone shed some light on the matter  or tell me the steps how to make it work

#### Actual Behavior

Just shows a  map
#### Expected Behavior

I thought it would have a marker of the location of the contact or account address

#### How to trigger the error

1.
2.
3.

#### Screenshot of configuration

![map](https://user-images.githubusercontent.com/7829825/44947289-96bce500-ae3d-11e8-96f7-da633e48346e.png)
 
#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: Firefox
* Environment name and version: Shared Hosting
* Operating System and version:

**Comment by ldgbc** [comment]
Hi: https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=map

https://github.com/YetiForceCompany/YetiForceCRM/issues/7047
https://github.com/YetiForceCompany/YetiForceCRM/issues/6826
https://github.com/YetiForceCompany/YetiForceCRM/issues/6898

Good luck.

**Comment by areksolek** [comment]
The mechanism works after turning on the cron.
![cron](https://user-images.githubusercontent.com/25615135/45952860-9fea3d80-c008-11e8-929a-cdf19def1cd1.png)
