### ISSUE TITLE
How to edit State field to State/Province in Leads, Contacts and Accounts

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#7910]
#### Issue

I would like to know how to change the field from State to State/Province in the contacts, leads and accounts section 

#### Actual Behavior

Edit field names

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: chrome
* Environment name and version: shared hosting
* Operating System and version:

**Comment by vovpff** [comment]
@bangde you mean name of field? You can change all language variables trough language manager

**Comment by bangde** [comment]
Yes that's right the field.

I did not know there was a language manager. Where is the language manager found?

Thanks for replying

**Comment by cltvchannel** [comment]
@bangde You can find variables on Sistem Module.

**Comment by bangde** [comment]
Great I found it thanks Citvchannel.
Not where I would expect to find States.
All good thanks

**Comment by bangde** [comment]
I tried what citvchannel suggested and went to system module in language manager but it did not work. Can someone please advice where to go to change the word State that is found in the contacts and accountants to  Province /State. I have tried to go to the language but there is no language string for state in contacts and accounts

**Comment by vovpff** [comment]
@bangde look for `AddressLevel2` lang variable in list.
Before
![image](https://user-images.githubusercontent.com/8545791/45028245-f806d300-b04c-11e8-89c8-39c9fbb8d3fc.png)
After
![image](https://user-images.githubusercontent.com/8545791/45028282-1967bf00-b04d-11e8-9a32-c247697a0b95.png)

**Comment by bangde** [comment]
Thank you very much vovpff that fixed my issue.

Cheers

**Comment by vovpff** [comment]
@bangde no problem
