### ISSUE TITLE
Cant select module in charts widget

### ISSUE THREAD

**Issue by hanzoF** [YetiForceCompany/YetiForceCRM#7912]
Hello guys 
When select widget from filter or charts.. I cant select any modules.. its empty.
How do I enable this...?

![one 0](https://user-images.githubusercontent.com/42919069/44961485-489b0500-af55-11e8-8415-519c794e3374.gif)

Thanks in advance

**Comment by vovpff** [comment]
@hanzoF before adding widget you need to check  option `list in metrics` for filter

**Comment by areksolek** [comment]
Hello,
At gitstable.yetiforce.com and gitdeveloper.yetiforce.com this error was not found. The new version is good.

![test12311](https://user-images.githubusercontent.com/25615135/45880648-fc4f2200-bda8-11e8-962a-dd1756123e1f.gif)
