### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#7913]
#### Issue

I have tried to import Sales invoices and get error for tree field import and date.
Tried on local server, dedicated server, gitstable.yetiforce.com and gitdeveloper.yetiforce.com .
Same error on all.
Error avabile both on CSV and XML.

#### Actual Behavior

1. Go to Sales Invoices module.
2. Export current records.
3. Delete current records.
4. Re-import records.
#### Expected Behavior

Correct error for tree field and date field.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: v4.4, Gitdeveloper Yetiforce, Gitstable Yetiforce
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@cltvchannel I can confirm date bug in my local 4.4.0 (updated from 4.3.0).

Gitstable and Gitdev does not work at all now.

**Comment by cltvchannel** [comment]
I see that there is an error also for currency field import.

**Comment by cltvchannel** [comment]
@TomaszQr Commit not fixed issue.
