### ISSUE TITLE
Error: File contains dangerous PHP code and was rejected

### ISSUE THREAD

**Issue by manwenick** [YetiForceCompany/YetiForceCRM#7920]
#### Issue
If I try to upload a picture to the product. I get the error message:

"File contains dangerous PHP code and was rejected [filename.JPG]"

#### Actual Behavior
Picture has not been uploaded, the error message appear: 
File contains dangerous PHP code and was rejected [filename.JPG]

#### Expected Behavior
Picture should be uploaded.

#### How to trigger the error
1. Open Product --> Edit product
2. Choose file for uploading
3. After confirm the upload, the error message appear.

#### Screenshot of configuration
Still the same: #7804

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Mozilla Firefox 
* Environment name and version:
* Operating System and version:
![filewasrejected](https://user-images.githubusercontent.com/34367573/44991494-89fed500-af94-11e8-9a43-5376c330fcfd.JPG)

**Comment by areksolek** [comment]
The system has mechanisms that check these files in terms of security. The content of the file may have illegal characters. Could you send a file in a comment  (-not good file-) ?

**Comment by manwenick** [comment]
@areksolek here is the file
![img_0239](https://user-images.githubusercontent.com/34367573/46026359-735b2200-c0eb-11e8-8ab8-a46cd8f5e472.JPG)

**Comment by manwenick** [comment]
@areksolek if the file is more than 1MB this fealure occures. 
But if I resize it, then it works. 
But there is also files, which are bigger than 1MB (2.1MB) which has been uploaded without any problems. 
I thought maybe it can be, servier settings (upload max_filesize). But all php settings are right. I have all upload sizes from 128MB.

**Comment by areksolek** [comment]
@manwenick
The photo you sent has illegal characters. This is not about characters in the file name. The system worked correctly.

**Comment by ezbank** [comment]
> @manwenick
> The photo you sent has illegal characters. This is not about characters in the file name. The system worked correctly.
I think it's more complicated than that. @areksolek 
![bug_jpg](https://user-images.githubusercontent.com/19627226/46076515-ee8a0a00-c1b7-11e8-98e5-d3ea7b07f94b.gif)

**Comment by manwenick** [comment]
@ezbank 
I see the icons of the added jpg files also different. What is the purpose of this difference?
@areksolek 
What exactly do you mean "photo has illegal characters"? Is there any description which characters in the files will be classified as illegal? Is there any work-arounds? I mean, there should be understandable reason for declining the update of some files?

**Comment by rafalpospiech** [comment]
Image data contains dangerous characters sequence for example `<?` which means the file could execute arbitary php code. This security feature is sometimes annoying and we know it.
We have plans to improve this, but i don't know when exactly. @mariuszkrzaczkowski could we remove this security feature safely now?

**Comment by ezbank** [comment]
any information?
