### ISSUE TITLE
Mechanizm szyfrowania

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#7944]
Witam Serdecznie 

Jestem osobą początkującą jeśli chodzi o instalację i konfigurację tego typu systemu, dlatego prosiła bym o co chodzi z aktywowaniem mechanizmu szyfrowania? Jak to zrobić i co jest mi do tego potrzebne. Piszę ponieważ nie znalazłam nigdzie takich informacji. Jeśli się powielam to przepraszam.

**Comment by bpabiszczak** [comment]
Hej, miło, że używasz naszego produktu. Informacja o szyfrowaniu mówi, że są dane takie jak hasła do poczty, klucze dostępowe itd. nie są w bazie danych szyfrowane. Aby zwiększyć poziom bezpieczeństwa swojego systemu, należy te dane zaszyfrować i jest to bardzo proste, wystarczy wejść do panelu: Konfiguracja systemu > Bezpieczeństwo > Szyfrowanie i tam wybrać metodę i hasła [ważne, abyśmy sobie zapisali i metodę i hasło bo jeżeli coś się stanie i system przestanie działać, będzie można zaszyfrowane dane odszyfrować].
