### ISSUE TITLE
 Installation prerequisites ver 4.3.0

### ISSUE THREAD

**Issue by rezeyle1** [YetiForceCompany/YetiForceCRM#7963]
How do I solve this problem. Follow the print in the attachment.

I already applied the following command but it did not solve: 

sudo apt install php7.1-cli php7.1-common php7.1-curl php7.1-gd php7.1-json php7.1-mbstring php7.1-mysql php7.1-xml

![erro1](https://user-images.githubusercontent.com/41129112/45118826-011ca080-b130-11e8-912a-d48467d55f14.PNG)

**Comment by vovpff** [comment]
@rezeyle1 maybe you have some different versions of php?
As you wrote you installed modules for php 7.1 but real active version can be 5.6 for example:
Cytcr your version `php -v`

**Comment by rezeyle1** [comment]
PHP 7.1.20-1+0~20180725103315.2+stretch~1.gbpd5b650 (cli) (built: Jul 25 2018 10:33:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.20-1+0~20180725103315.2+stretch~1.gbpd5b650, Copyright (c) 1999-2018, by Zend Technologies

**Comment by rezeyle1** [comment]
I resolved:

sudo apt-get install php7.1-{fpm,mbstring,mcrypt,phpdbg,dev,curl,sqlite3,json,gd,cli,zip,soap,ldap,apcu,imap}

sudo service apache2 restart
