### ISSUE TITLE
I can not search any file in the dropdown search box

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#7965]
#### Issue
I can not search any file in the dropdown search box. I would like to quickly select a product, a customer or a supplier, but I always have to go to a table search, which is very hard and takes some time.

#### Actual Behavior
I know that it worked in version 4.3, but I searched everything but and  I can not find the solution myself.

http://e-clan.si/dropdown.jpg

#### PHP/Apache/Browser Logs

PHP 7.2

#### Your Environment

* YetiForce Version used: 4.4.
* Browser name and version:GOOGLE CHROME
* Operating System and version: WIN XP

**Comment by vovpff** [comment]
@fbojan dropdown search will work only if you activate CRON. Now you have some products records but products names not listed in search table in DB.
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron
