### ISSUE TITLE
Change color of the gantt picklist

### ISSUE THREAD

**Issue by Saszalez** [YetiForceCompany/YetiForceCRM#7969]
#### Issue

I have modified the Status Values of Project and Project Milestones. The Gantt colors are now all gray, regardless of the Status. How can the Gantt colors be modified for each Status?

#### Screenshot of configuration
![image](https://user-images.githubusercontent.com/20907326/45145793-6c5e8500-b1b9-11e8-9322-1a6915c141e2.png)

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Firefox 61.0.1
* Environment name and version: Apache 2.4.1  PHP 7.1
* Operating System and version: Debian Stretch

**Comment by paula-w** [comment]
There is going to be a new and better Gantt library in the system soon.
