### ISSUE TITLE
Recent Activities tab missing from custom module 

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#7970]
hello all ! 

I created some custom modules and i am missing the recent activities tab for tracking the changes in the records. 
Is there a workaround for this ? Thanks ! 

YetiForce 4.4 - Self hosted on Plesk Onyx/Linux

**Comment by vovpff** [comment]
@liviubbo you need to apply modtracker for custom module: https://gitdeveloper.yetiforce.com/index.php?module=ModTracker&parent=Settings&view=List&block=2&fieldid=71

**Comment by liviubbo** [comment]
Thank you very much !
