### ISSUE TITLE
Why no quick Contact- Is this intentional or a Bug

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#7976]
#### Issue

I am wondering why there is no quick create contact ?

#### Actual Behavior

No quick create contact ?
#### Expected Behavior

I thought there would be a quick create contact just like there is a way to quick create others but i don't see it

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version:Opera
* Environment name and version: shared hosting
![no quick contact](https://user-images.githubusercontent.com/7829825/45155306-26331100-b20d-11e8-8c1f-617f8df9b0ed.png)

* Operating System and version:

**Comment by bangde** [comment]
Thanks but how do I add the fields. What I see is a blank area and nowhere
![blank](https://user-images.githubusercontent.com/7829825/45157712-84172700-b214-11e8-88f4-fcf6babb62c7.png)
 to insert fields.
Can you let me know what I need to do 

Thanks

**Comment by bangde** [comment]
I have found out the issue.

![basic](https://user-images.githubusercontent.com/7829825/45162981-d4e14c80-b221-11e8-8b64-a3837de81a3a.png)
It appears that when you select basic in the edit field section of contacts the quickly create contacts appear. If you choose advanced it disappears,

I am not sure the logic of this but thanks for pointing me in the right direction to solve the issue

Cheers

**Comment by vovpff** [comment]
@bangde this is solution too!
