### ISSUE TITLE
Project progress

### ISSUE THREAD

**Issue by Saszalez** [YetiForceCompany/YetiForceCRM#7979]
#### Issue

Hi. I have a project with two milestones and 4 tasks (two tasks for each milestone). When I put a percentage of progress in the tasks (30% and 40%, for example) in the milestone a 35% progress is made. The problem is that the progress of the project (35% of a milestone and 0% of another milestone) is not added or taken into account. How can I do so that the progress of the project is calculated according to the progress of the milestones?

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Firefox 61.0.1
* Environment name and version: Apache 2.4.10,  PHP 7.1.14
* Operating System and version: Debian Stretch

**Comment by Saszalez** [comment]
Hi. I understand that this sum can not be made and is being considered as an improvement for the next version. it is right?

**Comment by rafalpospiech** [comment]
We are replacing gantt chart now to [gantt-elastic](https://github.com/neuronetio/gantt-elastic) so when we finish de replacement we take a look at this.

**Comment by arek1-618** [comment]
Hello,
We are just working on a mechanism for automatically calculating the progress of the project. The progress of projects and milestones will be counted automatically based on the progress of the tasks.

https://github.com/YetiForceCompany/YetiForceCRM/pull/8718

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/8833
