### ISSUE TITLE
Any Documentation on Services need to see how to add on accounts? 

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#7995]
#### Issue

I would simply like to be able to know what services my client has. I thought i can create services and attach those services that my client has. So when I am looking up a company such as ABC company i can quickly see what services this client has at a glance.

However what i see when I go to account is 
Interested Services 
Services Outsourced

I am trying to understand the logic

The already have my services so it won't be **interested in services** and the services I sell to the client is not **outsourced.**

I just want to see what services this ABC client has.

How is this possible or can be seen at the accounts or contact level.

I do see services sold but I don't see this in Accounts but in contact module it has it. Do I need to add this to accounts?

I hope someone can suggest the best way to show services at the account level
Thanks

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
"Sold services" are also visible in the Accounts module, here's an example from our gitdeveloper version - [sold services](https://gitdeveloper.yetiforce.com/index.php?module=Accounts&view=Detail&record=226&mode=showRelatedProductsServices&requestMode=summary&tab_label=LBL_RECORD_SUMMARY_PRODUCTS_SERVICES)
![image](https://user-images.githubusercontent.com/13310141/49067646-f05a6300-f224-11e8-8142-cca62886186f.png)
