### ISSUE TITLE
Loading of roundcube mail  timeouts

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#7996]
#### Issue

I am trying to use the email  round cube and it opens but the loading of the emails time out. This is one of the most import areas of the crm system and I would like to be able to load the email and do my work without waiting.

It just says loading  then times out

How to fix it

#### Actual Behavior

Loading and Time out

#### Expected Behavior

Not time out and just work with no issues

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
You didn’t attach any logs (yetiforce, php, imap) so we can’t really help you.
The most common issues are:
1. Very slow mail server
2. Displaying emails on the homepage
