### ISSUE TITLE
[dev 4.4.39] Product descriptions missed in advanced modules

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7997]
#### Issue

When add any new advanced record there are some bugs with product table.

1. Not possible to open description for second and all nexs products. Only for 1st product description available.
2. Height of description field not comfortable (only one line visible)
3.  After saving description not available in table for 2nd and all next products.

See git

![desription_2](https://user-images.githubusercontent.com/8545791/45253733-f43cbe80-b374-11e8-8ad6-fd11950931a2.gif)

**Comment by vovpff** [comment]
@TomaszQr @areksolek Local system system 4.3 to 4.4 to 4.4.44
Bug not fixed with improved update package


But I can't repeat this bug in gitdev %)

**Comment by vovpff** [comment]
@areksolek @TomaszQr Local system system 4.3 to 4.4 to 4.4.44, browsed Chrome and Opera.
Both templates of advanced modules not works proper. There are two issues:
1) Description not hooked and not available for just added product.
2) Two clicks needed to open description for products what already in

![adv_descr4](https://user-images.githubusercontent.com/8545791/46334871-587a3780-c62e-11e8-9e62-bd74e1974d77.gif)

**Comment by rskrzypczak** [comment]
Probably it was fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/1e871bbf59511fab1f8e7325de56c8724302a611

**Comment by vovpff** [comment]
@rskrzypczak ver. 4.4.55 works well
