### ISSUE TITLE
[BUG] Template PDF Edit View

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#80]
![bug editor pdf template](https://cloud.githubusercontent.com/assets/1402355/5704116/f1ff75ba-9a8f-11e4-9cf2-a16c2fcb3e52.JPG)
![bug 2 editor pdf template](https://cloud.githubusercontent.com/assets/1402355/5704119/f50c6218-9a8f-11e4-88ca-209d3a6fe305.JPG)

**Comment by waran70** [comment]
MS Paint? :) Yea  seems that PDF Templater needs more attention.

**Comment by waw555** [comment]
This is a pair of scissors in Windows 8

**Comment by waw555** [comment]
I have a PDF Maker Professional license, if the guys will build it, it would be great

**Comment by waran70** [comment]
waw555, did you get workflows working with PDF Templater? It seems few people got issue... if not I will post ticket
