### ISSUE TITLE
QUESTION User permissions, Roles, Profiles, Groups.

### ISSUE THREAD

**Issue by manwenick** [YetiForceCompany/YetiForceCRM#8004]
Question: I have a question regarding to the permissions of the users. 
I have following story: I have a role of an employee of production department. This employee works on the product module. 
Then I have a role of an employee of a selling department. This employee works on the Sales module. 
Now I want the same user, to work 50% on products and 50% on selling. 
I can only assign the profile to the role with permissions of modules. Not the profile to the user. 
Do somebody have an idea, how I can resolve this requirement?

Thank you in advance!

#### Your Environment

* YetiForce Version used: 4.4.0

**Comment by MacarenaReina** [comment]
Hi!

I think you can create another role called "Production and Sales Department" with these two profiles, and add the other two roles like children of this one. So the user that works on both departments would have the new role "Production and Sales Department"

![yeti](https://user-images.githubusercontent.com/16593721/46737242-e5f30280-cc92-11e8-95ee-d5f215a7922e.png)

**Comment by raguvaran7232** [comment]
i have one question in software configuration . Its not opening error log is empty. 
I got this error:
{"success":false,"error":{"code":0,"message":"The web service did not return alerts count.","trace":""}}
and Server error 500

**Comment by paula-w** [comment]
@manwenick   
1. profiles are defined at the role level, it can’t be done on the user level
2. profiles only define access to functionalities (modules, fields, actions)

@raguvaran7232 
please open a new issue for all problems unrelated to the topic of the issue. It’s easier for us to track issues if we follow the “one problem per issue” rule. Here’s an article about error 500: https://yetiforce.com/en/knowledge-base/documentation/user-documentation/item/apache-500-internal-server-error-3
