### ISSUE TITLE
Can not send email from second email  account

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#8005]
#### Issue

Here is the problem i have two email accounts. One email account i can send and receive emails no issue. When I log out and log in with the second email account which happens to be a gmail account. I am only able to receive emails but when I try to create and send from that email I get smtp error 535.

I even tried changing the settings in round cube to not send email from the default SMTP settings but the one i have added, however, that did not work. 

Can someone point me in the right direction to solve this small but important issue I am having

The first email account is using the built-in server mail hosting while the second email account is using gmail account. I am not sure if this makes any difference

#### Actual Behavior

Sending email from second email account does not allow me to send only receive.

#### Expected Behavior

I want to be able to send to emails r

#### How to trigger the error

1.
2.
3.

#### Screenshot of configuration

![error](https://user-images.githubusercontent.com/7829825/45283996-f4be8c00-b511-11e8-8cb3-81024f24b0d9.png)

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: Google Chrome
* Environment name and version: shared hosting
* Operating System and version:

**Comment by bangde** [comment]
This is the error log i got

/home/zindelap/crm.zindela.properties/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube.php on line 1648 (POST /public_html/modules/OSSMail/roundcube/?_task=mail&_unlock=loading1536571366110&_lang=en_US&_framed=1&_action=send)
[10-Sep-2018 17:38:58 +0800]: <5f30bf5f> IMAP Error: Login failed for admin@sjconsultinggroup.com from 209.133.208.100. AUTHENTICATE PLAIN: Authentication failed. in /home/zindelap/crm.zindela.properties/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_imap.php on line 193 (POST /public_html/modules/OSSMail/roundcube/?_task=login&_action=login)
[10-Sep-2018 17:49:50 +0800]: <882803f8> IMAP Error: Login failed for admin@sjconsultinggroup.com from 209.133.208.100. AUTHENTICATE PLAIN: Authentication failed. in /home/zindelap/crm.zindela.properties/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_imap.php on line 193 (POST /public_html/modules/OSSMail/roundcube/?_task=login&_action=login)

**Comment by mariuszkrzaczkowski** [comment]
https://www.google.pl/search?q=roundcube+AUTHENTICATE+PLAIN%3A+Authentication+failed.&oq=roundcube+AUTHENTICATE+PLAIN%3A+Authentication+failed

**Comment by bangde** [comment]
I am sorry but the link you sent me has not helped me solve the problem but only make me more confused. 
I reached to my hosting company that said this below.  Can someone please tell me what i need to do  to fix this authentication error. 





While trying to send mail from admin@sjconsultinggroup.com through crm, I am getting authentication error. I am getting the same error with logs also.

======
dovecot_login authenticator failed for (YetiForceCRM) [103.116.16.36]:36280 I=[103.116.16.36]:26: 535 Incorrect authentication data (set_id=admin@sjconsultinggroup.com
======

The same error you are getting from the domain logs also.

====
IMAP Error: Login failed for admin@sjconsultinggroup.com from 209.133.208.100. AUTHENTICATE PLAIN: Authentication failed. i
=====

This is something related to either login details issue of the authentication mechanism that you uses in the software.

**Comment by bangde** [comment]
I fixed the problem. I had to do with the settings in RoundCube when adding multiple email accounts.
