### ISSUE TITLE
Edit status project tasks

### ISSUE THREAD

**Issue by Saszalez** [YetiForceCompany/YetiForceCRM#8020]
#### Issue
When I try to edit the status values of the project tasks I can not do it because they are blocked. Nor can they be eliminated.

#### Screenshot of configuration
![image](https://user-images.githubusercontent.com/20907326/45297435-40b30600-b4fd-11e8-91ad-3d436bd458b3.png)

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Firefox 61.0.1
* Environment name and version: Apache 2.4.10, PHP 7.1.14
* Operating System and version: Debian Stretch

**Comment by adudekyeti** [comment]
Unfortunately these values cannot be deleted or edited because they are a process system fields.
Of course you can change visibility of every value individually for every role.
