### ISSUE TITLE
Mail Scanner - No folder configuration  ( I get the error incorrect access data)

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#8023]
#### Issue

I am trying to get the mail scanner working for my second email account. However, it seems like its not working for the secound email account I have setup on the system. I have setup the email correctly as i can send and receive email properly. However, the email scanner to setup the folders is not working and  I am getting the error incorrect access data.

What does it mean and where do i go to see the error logs

Does anyone have any idea on how to fix it

#### Actual Behavior

no folders display and email scanner does not work for the second email

#### Expected Behavior

folders should display

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: Google chrome
* Environment name and version: Shared hosting
* Operating System and version:

![incorreect acces date](https://user-images.githubusercontent.com/7829825/45312221-12194780-b55e-11e8-90ff-797720c7c6c6.png)
![no folder config](https://user-images.githubusercontent.com/7829825/45312243-22312700-b55e-11e8-8a24-463a998065e9.png)

**Comment by bpabiszczak** [comment]
https://support.google.com/mail/answer/7126229?authuser=2&authuser=2&hl=en&authuser=2&visit_id=636789048192680785-3924345931&rd=2
