### ISSUE TITLE
Translate custom fields

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8038]
Hello all ! 

 First, thank you all for all the support i am getting here ! It was really helpful ! It`s a nice community here.

 I made some custom modules, and modified existing modules, adding some custom fields. Problem is, that we are using the system in two languages and, i cannot translate the custom fields that i added. 
 I can`t find the fields in translations, anywhere. 
 Any way to translate ?

 YetiForce 4.4 , self hosted.

**Comment by fbojan** [comment]
First, set a new language. I have Slovene si_si. Then translate into System tools
Language Management. All changes are then saved in / custom / languages / si_si. At check-in, you can also choose in which language you will work. The first option is in user settings or System tools
System - Configuration Show language selection on the login page!

**Comment by liviubbo** [comment]
So, i am refering to existing languages.
Example : i want to translate CUSTOM FIELDS that i added, from Romanian to Deutsch. 
Right now i don`t have anywhere the CUSTOM FIELDS that i have added. No option to translate.

**Comment by liviubbo** [comment]
Thanks ! It`s working like charm ! Thanks all !
