### ISSUE TITLE
Błąd zapisu danych w Poczta-RoundCube 

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#8049]
Witam 
Wersja systemu 4.4 v3

Nie działa u mnie zapis danych dla ustawień Poczta-RoundCube 
Po edycji danych i próbie zapisania nie dzieje się nic. W błędach systemu natomiast dodaje się nowa informacja o ogólnym braku dostępu dla użytkownika. Co może być nie tak ?

**Comment by Irmina8591** [comment]
Problem rozwiązany - wystarczy podać ssl://smtp.%z 
temat można zamknąć.

**Comment by bpabiszczak** [comment]
System obsługuje różne SMTP i różne konta IMAP dla użytkownika.
