### ISSUE TITLE
Percentage calculation in custom field

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8055]
Hello all ! 

   I have create some custom fields with values, and also with percentage.

   Now i want an automatic calculation of those. 
 
   I have read the documentation made here [#2043](https://github.com/YetiForceCompany/YetiForceCRM/issues/2043) , but i cannot apply it to my problem.
   
![calculation](https://user-images.githubusercontent.com/42461923/45485341-8ff47300-b757-11e8-8f16-056793149480.jpg)

**Comment by liviubbo** [comment]
I have tried field name:1,19% and is not working. I tried this, in hope that maybe, the output of NET will be with 19% substracted.

**Comment by vovpff** [comment]
@liviubbo net must be `brut - (brut*19)/100`? Use this expression.

**Comment by liviubbo** [comment]
It`s working  ! Thank you ! 
For a fixed percentage it`s perfect.
But, what if i want to add to SKONTO for example , 3% and calculate to SKONTO BETRAG : NET-3% ? 
The SKONTO field is not fixed. Always changing, depending on the invoice, and it`s always percentage.

**Comment by cltvchannel** [comment]
@liviubbo I think a solution is to create a number field (and hide that field) and use workflow.

**Comment by vovpff** [comment]
@liviubbo condition OR brut, vate, has changed. Update field task 1 Expression `net = brut - (brut*vate)/100`
Update field task 2 `skonto bertag = net - (net*skonto)/100`

**Comment by liviubbo** [comment]
First of all, i want to thank you all for helping. 

I want to write exactely what helped me.

This is the formula used for tax (19%) calculation. 

1. You can make a custom currency field for example, with name Brut and field name paymentsvalue 
2. Go to Automation->Workflows and add a new workflow for the module. 
3. Select Any time the record is saved, 
4. Click next.
5. Leave empty and click next
6. Add task -> Add To do -> Update Fields
7. Add a name and ADD FIELD - here you select the field WHERE you want to get the result. For example, i want the result to be input in NETTO, so here i select NETTO.
8. Select EXPRESSION
7. Add the formula paymentsvalue/1.19 to get exactely 19%

![1](https://user-images.githubusercontent.com/42461923/45492759-70684500-b76d-11e8-965a-c3be21e99121.jpg)

This is the formula used for a custom percentage calculation. I extracted from brut a custom percentage. Skontoplata field is a percentage field.

So - brut - (brut*skontoplata*skontoplata)/100
![2](https://user-images.githubusercontent.com/42461923/45492847-a6a5c480-b76d-11e8-91f0-5c8df8cf6d1f.jpg)
