### ISSUE TITLE
problem with validating email addresses

### ISSUE THREAD

**Issue by WMCyn** [YetiForceCompany/YetiForceCRM#8057]
The javascript validation (when creating/editing accounts) allows a space at the end of the email address, but the validator on save errors and does not save the record.

/layouts/resources/validator/FieldValidator.js 

line approx 40 could be changed something like:

validateValue: function (fieldValue) {
		var emailFilter = /^[_/a-zA-Z0-9*]+([!"#$%&'()*+,./:;<=>?\^_`{|}~-]?[a-zA-Z0-9/_/-])*@[a-zA-Z0-9]+([\_\-\.]?[a-zA-Z0-9]+)*\.([\-\_]?[a-zA-Z0-9])+(\.?[a-zA-Z0-9]+)?$/;
		var illegalChars = /[\(\)\<\>\,\;\:\\\"\[\]]/;

  var endSpace = /\s$/;

		if (!emailFilter.test(fieldValue)) {
			this.setError(app.vtranslate('JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS'));
			return false;

		} else if (fieldValue.match(illegalChars)) {
			this.setError(app.vtranslate('JS_CONTAINS_ILLEGAL_CHARACTERS'));
			return false;
		} else if (endSpace.test(fieldValue)){
			this.setError(app.vtranslate('Email cannot end with space'));
			return false;
        }

**Comment by slawekk87** [comment]
Please retest this on https://gitdeveloper.yetiforce.com/ email with space at end is not valid in js validator.
