### ISSUE TITLE
Relations tab view not saving

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8059]
Hy all ! 

   I want to change the view for module relations, but it`s not saving. I tried also to change in PHP file of the module, but it seems it can`t put product name in view. 

![relation](https://user-images.githubusercontent.com/42461923/45495706-10c16800-b774-11e8-8189-8adbe42c4ccc.gif)

**Comment by liviubbo** [comment]
I tested on git and its working perfectly. I don`t know where is the issue.

**Comment by areksolek** [comment]
The first option is used (Standard fields): to give which columns to be visible in the related module
The second option (Advanced block fields): is used to show the values from the product table
Both options work correctly.
![test222](https://user-images.githubusercontent.com/25615135/45877225-65c93380-bd9d-11e8-9490-1cebdc12b114.gif)
