### ISSUE TITLE
Jednostki miary towaru - zapis a tłumaczenie

### ISSUE THREAD

**Issue by artbski** [YetiForceCompany/YetiForceCRM#8060]
Dobry wieczór.<br><br>Jest taki mały "bug". <br>​​​​​​​<br>Moduł "Faktury sprzedażowe" -&gt; wybór towaru z jednostką miary "szt" a po zapisie, jednostka miary "pcs".<br><br><hr>Generated by YetiforceCRM ver. 4.4.0<br>PHP: 7.1.20-1+0~20180910100430.3+jessie~1.gbp17c613<br><br><strong>Server configuration errors:</strong><br>output_buffering: 1

**Comment by areksolek** [comment]
Witam, 
W nowszej wersji systemu błąd został naprawiony.
![test12222](https://user-images.githubusercontent.com/25615135/45882611-f6f4d600-bdae-11e8-9490-e852b2db7489.gif)
