### ISSUE TITLE
LBL_NO_EMAIL_TEMPLATE error on outgoing mail server

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8064]
I have an error when trying to add an outgoing email for smtp. I have added email templates in Email template module.
![mail](https://user-images.githubusercontent.com/42461923/45542313-ce4e6880-b811-11e8-9fec-46b459d1dbf2.jpg)

Yetiforce 4.4.0 , self hosted.

**Comment by liviubbo** [comment]
Bump ?

**Comment by slawekk87** [comment]
Verify that You have correct template in table 'u_yf_emailtemplates'  with sys_name 'TestMailAboutTheMailServerConfiguration'
![image](https://user-images.githubusercontent.com/22735929/46861089-1614df80-ce12-11e8-804b-bf069bc295d6.png)

**Comment by liviubbo** [comment]
I guess i dont have it. Should i intstall a local Yeti and copy the original table to my db?

**Comment by liviubbo** [comment]
I just checked and i dont have it. What should i do?

**Comment by liviubbo** [comment]
@slawekk87 - Should i create the table ?

**Comment by slawekk87** [comment]
To get this to work You need to create this entry - try to copy from clean install or database dump.

**Comment by slawekk87** [comment]
It is clean 4.4 install or upgrade from previous version?

**Comment by liviubbo** [comment]
Its clean but i guess i have deleted that email template entry. I will try to copy that table from a clean install.
