### ISSUE TITLE
Automatic notification workflow error

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8065]
Hello all ! 
 I wanted to create a workflow, that sends notification when the date is due. In this example, the date is today. So, when the record has the date, it needs to send a notification.  
Unfortunately is not working. Works only when i select : Every time a record is saved.
Problem is that i want the workflow for expiring contracts, e.t.c. 
![workflow](https://user-images.githubusercontent.com/42461923/45542880-6a2ca400-b813-11e8-80bd-18e029f8394c.gif)

**Comment by vovpff** [comment]
@liviubbo maybe this can help. Try to change date to 15th and check one more time tomorrow?

**Comment by liviubbo** [comment]
Yes ! It`s working like that (changing to 15, and after, back to 14) ! I change it again for tomorrow, and see tomorrow what`s happening. Thanks !

**Comment by vovpff** [comment]
@liviubbo no problem

**Comment by liviubbo** [comment]
It`s not working. I change like you said, and the next day, the workflow wasn`t working.

**Comment by liviubbo** [comment]
But i need it when conditions are met, but where not changed by any intervention ( eg. modified, or saved). Thats why i chose Only once, when all conditions are met. I really need it to be :  all the time when conditions are met, but no interventions needed to trigger (eg. edit of the record).
Hope i explained good :)

**Comment by liviubbo** [comment]
Should i chose System for that ?

**Comment by vovpff** [comment]
@liviubbo `Only once, when all conditions are met` will be ok for you but this workflow will work only once for record.
I'm not really know how `System` workflow works.

**Comment by liviubbo** [comment]
@vovpff - thanks !  I will try it

**Comment by liviubbo** [comment]
I don`t know witch is : every time the conditions are met but , no need for intervention

**Comment by vovpff** [comment]
@liviubbo what?

**Comment by liviubbo** [comment]
I can`t manage it ! First, thanks for all the help, but, the workflow i need to be automatical. To work without any intervention.
For example : i create a record that has a date field, with value 01-01-2019 - lets call it field A. 
I create a workflow , that creates a notification for field A 
I want that notification to appear, without any intervention on the record, in 01-01-2018

So, wich is it ? 
Is it System type workflow , run once when all conditions are met ? Or wich is it ?

**Comment by vovpff** [comment]
@liviubbo if you need notification only once than use `once when all conditions are met`. If you need every day checking you can make scheduled workflow what checks all records everyday and if data is today than send notification. In this case you can change data in record and next time then date will equal today you receive notification.

**Comment by liviubbo** [comment]
So, lets try again.
I have a record, with field A value 16-09-2018
I created a workflow with this condition : Once, when all conditions are met -> Condition : Field A equals 1 day before -> Task : Send notification - Title / Title / Content. 

I run CRON , i see it was the workflow was updated, but no notification !

**Comment by liviubbo** [comment]
Thank you for extended tutorial ! Its very explicative ! 
Problem here is that the trigger is SAVE.
I need to trigger automaticaly when date is due, without need to check every entry manually and save. 
I did this, what you wrote here, and it`s not working.
How i did it is date i set the date BEFORE creating the workflow.  I created the workflow and nothing. :( The only trigger is save and i will have about 1000 entries that i need to be parsed automaticaly, and triggered by system, not by hand.

**Comment by vovpff** [comment]
@liviubbo try this params:
![image](https://user-images.githubusercontent.com/8545791/45670062-7faf1000-bb2a-11e8-85a7-7baae58da074.png)

**Comment by liviubbo** [comment]
I have set it up. I just wait for 10:00 oclock when it was scheduled :)

**Comment by vovpff** [comment]
@liviubbo you can add additional condition like status is not canceled. In this case this workflow will avoid records wit cancelled status.

**Comment by vovpff** [comment]
@liviubbo I don't know what is your time but you can change time from 10 to 15 (Moscow GMT+3) and put today data. At 15 workflow must add notification.

**Comment by liviubbo** [comment]
I have set it up and wait for tomorrow ! Maybe it will start automaticaly tomorrow morning. Thanks for all the help.

**Comment by liviubbo** [comment]
Workflow is working as expected, i set to run every day. Now i have another problem : admin doesn`t get notifications :))

**Comment by vovpff** [comment]
@liviubbo cool

**Comment by ezbank** [comment]
@liviubbo your version?

**Comment by liviubbo** [comment]
4.4.0

**Comment by slawekk87** [comment]
@liviubbo What is status of this issue, all problems resolved?
