### ISSUE TITLE
[PL] Nowe kolumny w ramach modułów powiązanych

### ISSUE THREAD

**Issue by cedeka78** [YetiForceCompany/YetiForceCRM#8070]
#### Issue
Brak możliwości dodawania nowych kolumn w ramach modułów powiązanych

#### Actual Behavior
Konfiguracja systemu / moduły - powiązania istnieje opcja Dodaj więcej kolumn, jednak dodanie tych kolumn nic nie daje. Faktycznie nie zmienia się widok modułu (brak dodanych nowych kolumn) w ramach modułów powiązanych.

#### Expected Behavior
Dowolne dostosowanie widoku modułu wyświetlanego jako zakładka w innym module

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Chrome
* Environment name and version: shared hosting
* Operating System and version:

**Comment by areksolek** [comment]
Witam, 
W nowszej wersji systemu problem został rozwiązany.
![test1212](https://user-images.githubusercontent.com/25615135/45877715-1257e500-bd9f-11e8-9a74-72d5b93a1c87.gif)
