### ISSUE TITLE
Cron Jobs in setting happen to have html codes visible ( last scanned started  <span title="2018 ....")

### ISSUE THREAD

**Issue by mjapple** [YetiForceCompany/YetiForceCRM#8075]
#### Issue

When I open the setting>automation>cron jobs I see the cron jobs "last scan started" and the "last scan ended" has html codes in the rows  like this <span title="2018-09-15 at 09:00  (Saturday)">7 seconds ago</span>

![screen shot 2018-09-15 at 9 00 25 am](https://user-images.githubusercontent.com/6837503/45582752-96552d00-b8c6-11e8-93e4-5e368effb913.png)
is this ok ? t
Thanks in advance

**Comment by vovpff** [comment]
@mjapple this is ok for 4.3. Already fixed 4.4

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/5828
