### ISSUE TITLE
Company field in quotes- where this field get populated

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#8077]
#### Issue

I would like to know that there is a field called company in quotes. This field can not be edited and it gets populated but from where I dont know.

#### Actual Behavior

Company field shows but cannot be edited.

#### Expected Behavior

How this field gets populated in quotes

#### How to trigger the error

1.
2.
3.

#### Screenshot of configuration

![company name](https://user-images.githubusercontent.com/7829825/45583166-7b4ae300-b8ef-11e8-892c-13d503d51f3e.png)

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: chrome
* Environment name and version: shared hosting
* Operating System and version:

**Comment by vovpff** [comment]
@bangde company name value should be hooked from opportunity. Let's check on gitdev

**Comment by bangde** [comment]
OKay because I have checked in opportunity and do not see any trace of the company field anywhere it only shows in the quotation section and its not even editable

**Comment by vovpff** [comment]
@bangde 
![companyname](https://user-images.githubusercontent.com/8545791/45610864-24b3e500-ba66-11e8-88a7-ad190f4f84ec.gif)
If you need to change `Compeny name` you can make it editable.

**Comment by bangde** [comment]
Thank you. I now have a better understanding of how its populated.

**Comment by vovpff** [comment]
@bangde you are welcome!
