### ISSUE TITLE
[Question] PDF module - recordlist - parameter condition

### ISSUE THREAD

**Issue by basiliusgj** [YetiForceCompany/YetiForceCRM#8078]
I got a examples script for display relatedRecordlist on pdf module as following :

$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","Tom"]]]|)$
$(recordsList : Contacts|||All)$
$(recordsList : Contacts)$

parameters: ModuleName|Columns|Conditions|CustomViewIdOrName|Limit

QUESTIONS:
I would like replace “Tom” with a value from record field with $(record : nickname)$

Then i change the script as below:
$(relatedRecordsList : Contacts|firstname,lastname,modifiedtime|[[["firstname","a","$(record : nickname)$"]]]|)$

But not working. 

Do anyone could give me advise, how to write correct the script ?

 

Actual Behavior
Expected Behavior
How to trigger the error
	1	
	2	
	3	
Screenshot of configuration
PHP/Apache/Browser Logs
Your Environment
	•	YetiForce Version used: 4.3
	•	Browser name and version: Chrome
	•	Environment name and version: shared hosting
	•	Operating System and version:A

**Comment by vovpff** [comment]
@basiliusgj this is not possible to put script inside script now. Maybe in future this feature will arrive.

**Comment by basiliusgj** [comment]
@vovpff, Is there any work around solution ? Or Does it possible to replacing “Tom” with variable ?

**Comment by vovpff** [comment]
@basiliusgj check my old issues. I had the same. Developers has no plans to improve this functionality. If you need this you can pay for it or program by yourself.

**Comment by basiliusgj** [comment]
@vocpff, Thanks for your advice.
