### ISSUE TITLE
How and where to edit ckeditor to allow uploading of images in editor

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#8079]
#### Issue

I would like to know where I can edit the ckeditor so that it will allow me to add a plugin to ckeditor so that i can upload images easily with the editor as the default one is not good. I want to be able to drag and drop and upload multiple images at once that can be displayed in  yet force such as quotations, opportunities etc

#### Actual Behavior

where to edit ckeditor config.js to make changes

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: Google chrome
* Environment name and version: shared hosting
* Operating System and version:

**Comment by PercyP** [comment]
Hi,

I was trying to achieve this a while back. The options I think have been removed. I did manage to get it working by adding ckeditor myself using their download file (from ckeditor) but it is messy and the code gets overwritten when you update. If that has changed then maybe yetiforce team can let up know. I think it is an issue that they changed the usage of ckeditor but not 100% sure as it has been a while.

**Comment by bangde** [comment]
I sure hope some yeti can help out with this. CK editor should have at least the opportunity to upload images. I am lost on how to do it.

Do you have instructions on how to do it?

**Comment by PercyP** [comment]
Hi,

like I said it was a while ago. The file structure has changed enormously. I basically had to re-integrate ckeditor by taking a download from the ckeditor website. If I remember correctly you have to build your download and add the extra fields you want (i.e. image uploader). Then I replaced the version in yetiforce with that. I am sorry I can't be more helpful. I gave up in the end as like I said earlier, when you next update yetiforce all your changes get overwritten. 

The best thing would be to wait and see if they provide an alternative as at least then you know it will be properly integrated.

Will the multi image field not work for your scenario? That allows you to upload multiple images but not inside the editor.

**Comment by waran70** [comment]
Can we get some update on it? I have to write like 50 various templates. Imagine how PITA it is without proper handling images?
