### ISSUE TITLE
How to fill unit price for all products? 

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8083]
#### Issue

I have about 1000 products in database with 0 price. How to fill this products with correct price quick as possible? I tried to update database values but values in system not updated

Any ideas?

**Comment by liviubbo** [comment]
All products have the same price ? 
If yes, select all products and click MASS EDIT

**Comment by vovpff** [comment]
@liviubbo no, price should be different

**Comment by liviubbo** [comment]
Maybe if you try to export them in CSV or EXCEL, edit the file accordanly, easier in columns/cells, and then import it back. 
Of course, you need to delete the products after export.

**Comment by liviubbo** [comment]
Check HeidiSQL software. Maybe it will help you.

**Comment by vovpff** [comment]
@liviubbo thanks but this is not solution! Manually changed values in database not applied in system gui. If  I change 0 to 100 this value not appear at product page.

**Comment by paula-w** [comment]
You can’t add changes manually to the database but you can use a script for that because it’s not entered in just one place. But you have to know how the system is built to be able to do that.

**Comment by vovpff** [comment]
@paula-w could you advice me how to do it?

**Comment by TomaszQr** [comment]
Mass edit of the unit price field is possible after exporting the records, then you need to modify the exported file and import it but remember to enable detecting duplicates in the record overwrite mode (see the screenshot). Bear in mind that only the price for the basic currency in the system will be modified.  
![import_products](https://user-images.githubusercontent.com/14273211/49072836-695fb780-f231-11e8-8339-ff1b66538d6e.png)

**Comment by vovpff** [comment]
Thx
