### ISSUE TITLE
[Question] API - Upload file - Document module

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#8086]
Does the webservice support creating logs with attachments?
I tried the references at https://github.com/YetiForceCompany/YetiForceScripts but no results.
So how to create a record with the field as a picture or file via webservice.

**Comment by slawekk87** [comment]
Try this on developer version:
`$yr = new YetiRest($host, $wsname, $wspass, $wstoken);
if ($yr->login($user, $pass)) {
	$recorddata = [
		'imagename' => json_encode([[
			'name' => 'test.jpg',
			'baseContent' => base64_encode(file_get_contents('0.jpg'))
		]])
	];
	$response = $yr->updateRecord($module, $id, $recorddata);
}`
