### ISSUE TITLE
[PL] [4.4.0] Ucięte znaki podczas generowania dokumentu PDF z dużą ilością znaków

### ISSUE THREAD

**Issue by turek93** [YetiForceCompany/YetiForceCRM#8087]
#### Issue
Dzień dobry,
próbuję stworzyć PDF o znacznej ilości znaków (22 strony). 
Przy utworzeniu wszystkich stron i próbie wygenerowania pliku PDF otrzymuję 15 stron. 
Problem wygląda w ten sposób, że w pewnym momencie jest ucinany dalszy HTML.
Przykładowo ostatnie zdanie wygląda następująco:
Ala ma pięknego szarego kota.
Zakładamy, że PDF wygeneruje zdanie: Ala ma pięknego szarego ko
Po usunięciu spacji między pięknego, a szary pojawi się zdanie: Ala ma pięknegoszarego kot

Wygląda na to, że kończy się ilość dozwolonych znaków.
Próbowalem na standardowym Lorem Ipsum (bez tagów HTML) o dużej ilości znaków i ten problem również się pojawia w ten sam sposób. Ucięte nagle zdanie i brak dalszej części. Po usunięciu jednej spacji cofa się jedna litera i pokazuje itd.

Sprawdziłem rozwiązania dostępne w Sieci i żadne nie pomaga. Dokumentacja mPDF również nie pomaga. Zmieniałem limity zgodnie z: https://mpdf.github.io/troubleshooting/memory-problems.html
W logach nie są pokazywane żadne błędy ani ostrzeżenia. 
Sprawdziłem i jest wysyłany cały HTML - problem jest już na poziomie generowania PDF.

Zmieniałem również wartość ini_set("pcre.backtrack_limit", "1000000");

#### Expected Behavior
Chciałbym uzyskać pełny wydruk PDF - bez ograniczenia. 

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Google Chrome, Mozilla Firefox, Safari
* Environment name and version: PHP 7.1, Apache 
* Operating System and version: Ubuntu 17.10

**Comment by bpabiszczak** [comment]
Na pewno wynika to z limitu przekazywanego HTML-a do PDF-a na warstwie konfiguracji [zapewne] serwera. Ktoś musi to zweryfikować, kto ma dostęp do środowiska, gdzie jest to obcinane, ponieważ u nas na serwerze inny parametr może "obcinać znaki". 

Ciężko powiedzieć, który parametr za to odpowiada, trzeba zapewne zweryfikować różne parametry.

**Comment by turek93** [comment]
Nie zgodzę się w tej kwestii. 
Pracowaliśmy nad rozwiązaniem tego problemu.
Okazało się, że trzeba zmienić typ pola w tabeli a_yf_pdf z TEXT na LONGTEXT.

U mnie problem został dzięki temu rozwiązany.

**Comment by bpabiszczak** [comment]
ale to oznacza, że nie obcinał przy wydruku, lecz zrobił to przy zapisaniu szablonu :]
