### ISSUE TITLE
[PL] Schowanie ostrzeżenia systemowego

### ISSUE THREAD

**Issue by marcineqpol** [YetiForceCompany/YetiForceCRM#8095]
#### Issue

Pomimo zaktualizowania biblioteki smarty, ostrzeżenie pojawia się nadal.

#### Actual Behavior

Pomimo zaktualizowania biblioteki smarty, ostrzeżenie pojawia się nadal.

#### How to trigger the error

1. Podmiana plików w vendor/smarty/smarty/libs
2. Uruchomienie wszystkich poleceń CRON w tym powiadomienia o ostrzeżeniach
3.
![screenshot_7](https://user-images.githubusercontent.com/29989759/45704104-6338c500-bb76-11e8-8412-8820ddd14f18.png)

#### Your Environment

* YetiForce Version used: 4.40
* Browser name and version:Chrome
* Environment name and version: Hosting współdzielony
* Operating System and version:

**Comment by TomaszQr** [comment]
W jaki sposób była aktualizowana biblioteka? Stworzyliśmy paczkę 4.4.0_SecuritySmartyFix_v1.zip
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.4.0/4.4.0_SecuritySmartyFix_v1.zip która aktualizuje biblioteke Smarty i dodatkowe pliki które sa wykorzystywane podczas weryfikacji podatnosci.

**Comment by marcineqpol** [comment]
Okej, sprawa wyjaśniona. Podmieniłem pliki zgodnie ze źródłem, a nie skorzystałem z przygotowanej przez Was aktualizacji. Wczoraj będąc na githubie, zanim zgłosiłem issue sprawdzałem release i nie zauważyłem wydania poprawki.

**Comment by bpabiszczak** [comment]
Najważniejsze, że problem został rozwiązany! Super, że korzystasz z YetiForce!
