### ISSUE TITLE
After changing PHP version, I got APACHE 500 error

### ISSUE THREAD

**Issue by Kavaf** [YetiForceCompany/YetiForceCRM#8101]
#### Issue

I want to do an update to 4.4 from 4.3.0 but I am using PHP 7.0 right now.

When I change the PHP 7.2 from 7.0, I can't access the application and I see 500 Internal Error.
Then I change back to 7.0 and everything is okey. 

How can I solve this problem. I read some things about php.ini , .htaaccess but there is no clear explanation and step by step guideline. 

Thank you in advance,

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome/Opera 
* Environment name and version: 
* Operating System and version:

**Comment by vovpff** [comment]
@Kavaf recommended php version for 4.4 is 7.1.x.

**Comment by Kavaf** [comment]
> @Kavaf recommended php version for 4.4 is 7.1.x.

When I change to PHP 7.1, I get an error like this. 
![image](https://user-images.githubusercontent.com/43413089/45761025-1b787300-bc34-11e8-9740-ded120265c18.png)

**Comment by bpabiszczak** [comment]
Check the server configuration because it most likely is incorrect.

**Comment by Kavaf** [comment]
Hello,

The Host provider did fresh installation and now I can use 4.4 but I have another issue and  I will create another topic. 

Thank you,
