### ISSUE TITLE
[PL] Brak możliwości dodawania niektórych haseł

### ISSUE THREAD

**Issue by marcineqpol** [YetiForceCompany/YetiForceCRM#8104]
#### Issue

Dodając hasło do systemu, gdy będzie ono nieco dłuższe lub bardziej skomplikowane - pojawia się błąd, że hasło jest za długie.

#### Expected Behavior

Dodawanie hasła jest możliwe nawet dla dłuższych haseł.
#### How to trigger the error

1. Hasła > utwórz rekord
2. Wprowadź hasło np. "QqJMP37e0)u#HCz*" (generalnie powyżej 15 znaków)
3.Hasła nie da się zapisać.

**Problem odtworzyłem również na wersji demo.**
![hasla](https://user-images.githubusercontent.com/29989759/45787511-0fada080-bc76-11e8-9494-a8d77a3308fd.gif)

#### Your Environment

* YetiForce Version used: 4.40
* Browser name and version: Chrome
* Environment name and version: Shared hosting
* Operating System and version:

**Comment by areksolek** [comment]
Witam,
Proszę zmienić ustawienia dotyczące hasła a w szczególności należy zmienić "Maksymalna długość:"
w "Ustawienia->Bezpieczeństwo->Hasła - szyfrowanie->Konfiguruj hasło"
![haslo](https://user-images.githubusercontent.com/25615135/45868829-0ceea080-bd87-11e8-8b73-8b408d9d39cb.gif)
