### ISSUE TITLE
[PL] Tłumaczenie zmiennych w tworzeniu PDF

### ISSUE THREAD

**Issue by marcineqpol** [YetiForceCompany/YetiForceCRM#8105]
#### Issue

Nie mam pojęcia, jak zmienić tłumaczenie YF i udostępnić poprawkę światu, więc robię to w ten sposób. 

#### Actual Behavior

Podczas tworzenia PDF, wprowadzając zmienną o nazwie "Numer aktualnej strony" dostępne są dwie zmienne o tej samej nazwie, lecz wprowadzające zupełnie inne wartości.
#### Expected Behavior

Poprawka opisu jednej z nich na "Liczba stron"
#### How to trigger the error

1.
2.
3.
![numer strony](https://user-images.githubusercontent.com/29989759/45787732-0244e600-bc77-11e8-9e18-2922bcdb9d16.gif)

#### Your Environment

* YetiForce Version used: 4.40
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rafalpospiech** [comment]
Tak, tłumaczenia nr stron wprowadzają w błąd.
W chwili obecnej tworzymy nowy mechanizm generowania PDFów więc jak skończymy wstawimy od razu wersję z poprawką tłumaczeń.
