### ISSUE TITLE
Product bundles can not locate component usage  quantities

### ISSUE THREAD

**Issue by sooxwq** [YetiForceCompany/YetiForceCRM#8106]
#### Issue

![image](https://user-images.githubusercontent.com/2231741/45792040-c2a1ec80-bcbe-11e8-82b1-2d91481ad66d.png)

#### Actual Behavior

when select product bundles，the columns is not contains uasge qty with parent Product
and can not define the columns informantion (records list can not be defined)
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by TomaszQr** [comment]
You can define columns in list:
![product_boundles](https://user-images.githubusercontent.com/14273211/49009880-f0e5f180-f171-11e8-880e-51e689f52cfb.gif)
