### ISSUE TITLE
Payments by counterparty

### ISSUE THREAD

**Issue by ipanchenko1990** [YetiForceCompany/YetiForceCRM#8121]
Is it possible to deduce the total amount of payments to a counterparty in the financial result section? And use this data to calculate the residual debt for the transaction.

**Comment by ipanchenko1990** [comment]
How can I use incoming payments to monitor the transaction in automatic mode?

**Comment by PercyP** [comment]
I need this too

**Comment by paula-w** [comment]
Of course it can be done but it requires a script that knows what and when to add. From the technical perspective it’s simple, from the business perspective it’s more complicated, as we have to establish the basis module for it to add up (orders, invoices, payments), which statuses to take into consideration and which ones to ignore, whether or not the client has a merchant limit, or whether or not any negative value on the account should block anything in the subsequent opportunities, etc. 
Regardless of the business needs, it’s going to require some programming work (probably around 1 – 2 work days)
