### ISSUE TITLE
[BUG][4.4.44][Checkbox field] Put checkbox fields as not editable doesn't work

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#8124]
#### Issue
I update the visibility of a checkbox field and put it like "Field visible everywhere, not editable".
It doesn't work, I can edit this field.

#### Actual Behavior
Can edit a checkbox field

#### Expected Behavior
Cannot edit a checkbox field

#### How to trigger the error
![2018-09-24_10-22-27](https://user-images.githubusercontent.com/16593721/45945049-22acd180-bfe4-11e8-9fc7-0fe64e721e50.gif)

Also if I put this field in a filter it shows like:
![bug](https://user-images.githubusercontent.com/16593721/45945528-b03cf100-bfe5-11e8-9c4f-cb35086945ef.png)

#### Your Environment
* YetiForce Version used: Latest version (4.4.44)
* Browser name and version: Google Chrome
* Operating System and version: Windows 10

**Comment by MacarenaReina** [comment]
@arek1-618 thanks so much! it works fine.
But do you know what's happening on list view with non editable checkbox?

**Comment by arek1-618** [comment]
> @arek1-618 thanks so much! it works fine.
> But do you know what's happening on list view with non editable checkbox?
Thank you for your attention. I just corrected the list view.
