### ISSUE TITLE
How to Remove currency symbol in invoice?

### ISSUE THREAD

**Issue by ccm0101** [YetiForceCompany/YetiForceCRM#8127]
hi, i am new on yetiforce crm. my crm version is v4.4.0.

when i edit my invoice, the currency symbol display after amount, may i know how to disable the currency symbol?

![invoice](https://user-images.githubusercontent.com/43539028/45950212-6bd74280-c031-11e8-81f3-bfc8cc582bec.jpg)

**Comment by paula-w** [comment]
Hi and welcome to our community!
To remove your currency symbol you have to manually edit a script that is responsible for invoice generation. You can find the file in \app\TextParser\ProductsTableShortVersion.php
