### ISSUE TITLE
Can't search for '&'

### ISSUE THREAD

**Issue by gerripeach** [YetiForceCompany/YetiForceCRM#8130]
#### Issue
You can't search for **&**.

#### Actual Behavior
Create a record named 'foo & bar'. And search for it. This record can't be found.

#### Expected Behavior
Records with a '&' should be found.

#### How to trigger the error
1. Create a record named "foo & bar"
2. Search for "foo & bar" or "foo &" or "&"
3. Find nothing
https://gerripeach.tk/yetiforce_search_bug.gif

#### Screenshot of configuration
**YOUR** https://gitstable.yetiforce.com/

#### PHP/Apache/Browser Logs
Maybe this helps: Searching for **&** creates this query:
`2018-09-25 08:18:25.4279 [info][yii\db\Command::query] - SELECT `vtiger_account`.`accountid` AS `id`, `vtiger_account`.`accountname` AS `accountname`, `vtiger_account`.`website` AS `website`, `vtiger_account`.`phone` AS `phone`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_account`.`phone_extra` AS `phone_extra` FROM `vtiger_account` INNER JOIN `vtiger_crmentity` ON vtiger_account.accountid = vtiger_crmentity.crmid WHERE (`vtiger_crmentity`.`deleted`=0) AND (`vtiger_account`.`accountname` LIKE '%&amp;%') LIMIT 21`

Looks like **&** gets escaped for the search. (**&am p;**). In the table vtiger_account the record is saved with & not with &am p;

#### Your Environment
**YOUR** https://gitstable.yetiforce.com/

* Browser name and version: Chrome 69
* Operating System and version: Ubuntu 18.04 LTS

**Comment by mlorencik** [comment]
In 4.4.0 version is not working but try our newest version on https://gitdeveloper.yetiforce.com/ 

I add Lead with & in name and i find this without problems
