### ISSUE TITLE
Decimal separator " , " 

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#8134]
https://www.youtube.com/watch?v=fYSt1nVpf_c&feature=youtu.be

I do not know where to look for a mistake.
When the decimal separator of the dot (.) Then somehow goes and the tax is not counted right, but if the comma is a little confusing.

**Comment by manwenick** [comment]
@fbojan 
I don't understand exactly what you mean. 
Is there a problem with the sum of net to gross in the invoices? Or you have a problem with the separators?

**Comment by fbojan** [comment]
![pika](https://user-images.githubusercontent.com/25682437/46094735-fd25f080-c1ba-11e8-88c6-63b21abd1cb5.jpg)
![vejica](https://user-images.githubusercontent.com/25682437/46094737-fd25f080-c1ba-11e8-8a3a-75378ec36426.jpg)

**Comment by fbojan** [comment]
If the decimal separator is "," the program does not work properly because it does not count the number after the decimal separator. At least in the Tax summary and  on PDF reports is the wrong calculation.

**Comment by fbojan** [comment]
I'm sorry I did not answer before. Once again I tested the problem with the separator and really one part is aligned but unfortunately there are still differences. 

In Slovenia, Austria and countries where I work, due to the usual format (also because of the keyboard) "123.456,79" The dot is only used for the date format  "12.12.2012."

Here are some examples of how you can not use decimal numbers

[DDV1.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/2447427/DDV1.zip)
[dd2.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/2447439/dd2.zip)
[ddv3.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/2447440/ddv3.zip)






* YetiForce Version used: 4.4.46
* Browser name and version: CHROME
* Environment name and version:
* Operating System and version:
