### ISSUE TITLE
STORAGE SUMM

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#8135]
You have two storages. Main and subordinate storage. You get 10 pieces of product in the main storage. You then transfer 4 to the subordinate storage. Logically, you have a stock of 10 pieces of product in stock of which 6 on the main and 4 in the subordinate storage.

What is the method of data entry? Goods Received Note 10 pieces ... Goods Issued Note 4 pieces ???

If I Sell, then Goods Dispatched Note 1 Pieces from Slave Storage ??

THANK YOU

**Comment by vovpff** [comment]
GRN 6 pcs to master storage and GRN 4 pcs for slave.

When you sell 1 pc you need to add GDN with 1 pc and chose master/slave storage.

**Comment by vovpff** [comment]
@fbojan this is better than nothing :)

**Comment by paula-w** [comment]
If your products are supposed to be in 2 storages then you have to use 2 documents. It works like @vovpff  described. We will optimize it in the future.
