### ISSUE TITLE
[PL] Wyłączenie stanów magazynowych + produkty bez powiazania z bazą produktów

### ISSUE THREAD

**Issue by florek41** [YetiForceCompany/YetiForceCRM#814]
Zastanawiam się czy logicznym, z waszego punktu widzenia, byłaby możliwość wyłączenia zarządzania stanami magazynowymi ?
W.g mnie w niektórych przypadkach jest to uzasadnione, a czasem wręcz niezbędne - za przykład może posłużyć moja obecna firma.
Zajmujemy się główne projektowaniem, produkcją. W 80-90% są to produkty niestandardowe i niepowtarzalne, o różnych wymiarach, specyfikacjach i z różnych materiałów, więc i w różnych cenach.
Są to produkty 'na życzenie' i w związku z tym nie ma większego sensu wprowadzanie ich na magazyn.

Myślałem o tym, żeby dla każdego produktu była możliwość oznaczenia go jako magazynowy lub nie - przy wyłączonej tej opcji system nie wyświetlałby informacji o braku na magazynie.
Oczywiście globalne wyłączenie magazyny też ułatwiłoby pracę, ale w w/w konfiguracji byłaby możliwość wprowadzania zarówno produktów w magazynie (wraz z monitorowaniem ich stanu) oraz tych niemagazynowych.

Druga sprawa to możliwość wprowadzania dowolnej nazwy produktu bez konieczności wcześniejszego jego dodawania do systemu.
Jak wcześniej pisałem - robimy różne produkty i różnie je nazywamy, często opisowo, żeby klient miał pojęcie o co chodzi.
Chciałbym, żeby system nie wymagał ode mnie wybrania produktu/usługi z listy, ale żebym mógł sam, ręcznie wpisać co to jest.

Na chwilę obecną nie znalazłem systemu, który miałby zaimplementowane te dwie rzeczy, a patrząc na rozwój i postęp YF można się spodziewać sporo - zrobiliście kawał dobrej roboty i oby tak dalej !

**Comment by bpabiszczak** [comment]
W przyszłości planujemy stworzyć zaawansowany moduł magazynowy ze wszystkimi modułami pobocznymi. Jednakże wprowadzanie kompletnego systemu magazynowego to nie dni ani tygodnie a raczej miesiące pracy. Plan jest taki, aby był to system kompletny a nie tylko coś co nazywamy obecnie CRM. 

Odnośnie określania nazwy produktu. Nie uważam aby Twój pomysł był dobry. Nawet jeżeli produkt za każdym razem jest inny np. sprzęt komputerowy to nie ma znaczenia czy w środku jest procesor i5 czy procesor i7. A więc do dokumentów typu kalkulacje, oferty, zamówienia, faktury używamy nazwy ogólnej natomiast w opisie produktu możemy wkleić konkretne parametry. W przyszłości rozbudowany magazyn będzie miał tzw. mechanizm wytwarzania produktu i on będzie się składał ze składników.

Odnośnie sprawdzania czy produkt podlega weryfikacji magazynowej, aktualnie w systemie dla każdego modułu mamy parametr [od strony programistycznej], który pozwala włączyć lub wyłączyć globalnie taką weryfikacje:

function save_module($module) {
     $updateInventoryProductRel_deduct_stock = true;

Można w tym miejscu dodać sobie warunki poboczne i spowodować aby walidacja działała tak jak Ty chcesz czyli na podstawie checkbox-a czy sprawdzać stan czy też nie.
