### ISSUE TITLE
900.000 notifications ? 

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8145]
Hy all ! 

    I got this morning at the office, opened up YetiForce and just got 900.000 notifications. Also, i found this document on server, called xxxx.txt in root installation of Yeti.
    About notifications i am sure it`s not normal, sql table was 200MB, so i guess nothing normal would trigger such a massive amount of notifications. Also, was nobody at work.
    I will check server logs today, also, Yeti logs, and all i can check.
    Can someone please tell me, based on the symtoms described : We were hacked ? 
    If yes, how can i protect Yeti better and what did i do wrong ?
    If not, what went wrong ? 
    Yeti installation is 4.4.0 self hosted. Also, i had some workflows that were set daily and weekly. 
    I will put some code of the xxxx.txt down, it`s just a sample.
//
Array
(
    [0] => Array
        (
            [Accept-Language] => Array
                (
                    [0] => en-US, en;q=0.7, *;q=0.5
                )

            [User-Agent] => Array
                (
                    [0] => DAVdroid/2.0.4-gplay (2018/09/08; dav4android; okhttp/3.11.0) Android/8.1.0
                )

            [Accept-Encoding] => Array
                (
                    [0] => gzip
                )

            [Content-Type] => Array
                (
                    [0] => application/xml; charset=utf-8
                )

            [Depth] => Array
                (
                    [0] => 0
                )

            [Content-Length] => Array
                (
                    [0] => 290
                )

            [Connection] => Array
                (
                    [0] => close
                )

            [X-Accel-Internal] => Array
                (
                    [0] => /internal-nginx-static-location
                )

            [X-Real-Ip] => Array
                (
                    [0] => 188.98.xx.xxx (**here was an ip)
                )

            [Host] => Array
                (
                    [0] => mydomain.com
                )

            [Authorization] => Array
                (
                    [0] => 
                )

        )

)
//

**Comment by liviubbo** [comment]
I had normal Notifications workflow, trigerred automaticaly every day or weekly. Until yesterday all went well so ...

**Comment by paula-w** [comment]
Check your logs, you will definitely find info on what generates these notifications. Then just disable whatever it is and that’s it.
