### ISSUE TITLE
I can't download mPDF in Ver 4.4.0 

### ISSUE THREAD

**Issue by Kavaf** [YetiForceCompany/YetiForceCRM#8155]
#### Issue

When I click to Download mPDF, The page reloads itself but nothing is happening. 

I had a same problem with roundcube but I solved with the issue number: #7286
"Roundcube will not download in YetiForce CRM ver. 4.4.0 RC3" 

#### How to trigger the error

![pdf_library](https://user-images.githubusercontent.com/43413089/46208353-1d78bb00-c333-11e8-9fe7-93718e27e110.gif)

1.
2.
3.

#### Screenshot of configuration

![yeti-webserver](https://user-images.githubusercontent.com/43413089/46208157-84e23b00-c332-11e8-965f-399344404b08.PNG)

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by afarral** [comment]
I have the same issue, new install from softaculous, both for mPDF and roundcube, the download button does nothing, without PDF i cannot use!!!

**Comment by ReginaldGouws** [comment]
> 
> 
> I have the same issue, new install from softaculous, both for mPDF and roundcube, the download button does nothing, without PDF i cannot use!!!

Same here also installed from softaculous, my roundcube also does not work. Installed today.

**Comment by mariuszkrzaczkowski** [comment]
logs

**Comment by afarral** [comment]
Hi, what logs do you need?

**Comment by mariuszkrzaczkowski** [comment]
All

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging
