### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Carolinercraig** [YetiForceCompany/YetiForceCRM#8159]
I was unable to use any of the repository files. I ended up downloading for sourceforge instead. Am I missing something?

**Comment by vovpff** [comment]
@Carolinercraig what OS and webserver?

**Comment by Carolinercraig** [comment]
I am using Windows 7 and WAMP 64.

**Comment by vovpff** [comment]
@Carolinercraig There are should be no problem with WAMP but linux more preferable. What is your problem?
