### ISSUE TITLE
800.000 entries in database ! 

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8161]
Hello all ! 

   I return again with my problem ! I have some entries in database that i am really concerned about. I got two (or more) tables that have over 800k entries. Also, i have a total of 1.700.000 entries in the database.
   First, i want to mentions that i am really sure that all of my entries ar less than 1.000 in the YetiForce system.
   I reported here : #8145 about another similar issue that occured last week.
   I want to ask if i can delete those two tables (empty them). And also, if i delete them, i will lose some of my data ? 
   Thanks ! 
![wrong](https://user-images.githubusercontent.com/42461923/46273139-8db25700-c554-11e8-9920-076cdf5f12ae.jpg)

**Comment by vovpff** [comment]
@liviubbo what data this tables contain?

**Comment by liviubbo** [comment]
I will tell you in about half an hour if i manage to make a restore, because i deleted them and now i have nothing in my installation. All data lost ! 👎 :(

**Comment by TomaszQr** [comment]
In the u_yf_crmetity_label and u_yf_crmentity_search_label tables, there are record labels for displaying and searching, data from these tables are automatically restored by cron.
