### ISSUE TITLE
CACHING_PERMISSION_TO_RECORD

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8168]
#### Issue

```
	/*
	 * Configuration of the permission mechanism on records list.
	 * true - Permissions based on the users column in vtiger_crmentity
	 * false - Permissions based on adding tables with permissions to query (old mechanism)
	 */
	'CACHING_PERMISSION_TO_RECORD' => true,
```

**Comment by bpabiszczak** [comment]
?

**Comment by rskrzypczak** [comment]
TRUE - permissions are not verified in real time. They are updated via cron. This option is more optimal in case of granting some advanced and complex permissions to records. We do not recommend using this option by default.

FALSE - Default permission verification mechanism.
