### ISSUE TITLE
Duplicating profile

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8169]
#### Issue

Any ideas how to duplicate profiles here: `Software configuration > Permissions > Profiles > System settings`?

This is crazy every time add new profile with some differences.

**Comment by vovpff** [comment]
@manwenick sorry. My question for 4.3.0. I'm not updated for 4.4 at this time.

**Comment by rskrzypczak** [comment]
Please update to new version :)

**Comment by vovpff** [comment]
@rskrzypczak already updated. Thanks!
