### ISSUE TITLE
Cron Issue

### ISSUE THREAD

**Issue by FredFaraday** [YetiForceCompany/YetiForceCRM#8170]
#### Issue
Failing to get scheduled cron jobs to run on version 4.4. Have tried on live host and local bitnami lampstack. Both hosts are running php 7.2.9 which is the only version of php that Yetiforce 4.4 worked for me so far. Hosting support are failing to assist and therefore am turning to Yetiforce to hopefully shed more light regarding this cron issue. 

#### PHP/Apache/Browser Logs
Live Cpanel: (Default softaculous install and auto created cron job)
[14-Sep-2018 18:00:02 UTC] PHP Fatal error:  require_once(): Failed opening required 'include/ConfigUtils.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home/uthjtxes/public_html/include/main/WebUI.php on line 11

Local Bitnami Lampstack 7.2.9:
PHP Warning:  require_once(include/ConfigUtils.php): failed to open stream: No such file or directory in /opt/bitnami/apache2/htdocs/yt44/include/main/WebUI.php on line 11
PHP Fatal error:  require_once(): Failed opening required 'include/ConfigUtils.php' (include_path='.:/opt/bitnami/php/lib/php:/opt/bitnami/frameworks/smarty/libs') in /opt/bitnami/apache2/htdocs/yt44/include/main/WebUI.php on line 11

#### Your Environment

* YetiForce Version used: 4.4 Stable
* Browser name and version: 
* Environment name and version:
* Operating System and version:

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/8117
