### ISSUE TITLE
[ENHANCEMENT][4.4.46][Import] Import zip with .csv files

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#8172]
#### Actual Behavior
I have only the option to import .zip files that contains .xml files.
![yeti](https://user-images.githubusercontent.com/16593721/46338802-0e428780-c629-11e8-96ac-1250461d532e.png)

#### Expected Behavior
It would be so util to import .zip files that contains .csv files.

#### Your Environment

* YetiForce Version used: Latest version (4.4.46)
* Browser name and version: Google chrome
* Operating System and version: Windows 10

**Comment by paula-w** [comment]
Thanks a lot for the idea. However, we're currently working on some higher priority functionalities, but we'll keep your idea in mind for the future.
If you want to find out why we can't develop all the community requested functionalities take a look at [this](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/why-was-the-issue-ignored) article
