### ISSUE TITLE
Add filter modal not showing

### ISSUE THREAD

**Issue by DonnieRich** [YetiForceCompany/YetiForceCRM#8173]
#### Issue
Cannot create a new filter, because the modal is not showing.
This problems seems to be resolved on the developer demo available online.

#### Actual Behavior
When trying to create a new filter from Filters - Configuration or from the Product module the Modal Popup won't show. It's loaded in the HTML but not showing on the page.
From the browser console I don't see any error related to this behavior.

#### Expected Behavior
The new filter modal should be visible.

#### How to trigger the error
1. Go to System Settings
2. Open Filters - Configuration
3. Click on Add Filter

#### Screenshot of configuration
Will add this as soon as possible

#### PHP/Apache/Browser Logs
The error doesn't show up in the logs, neither in the browser console.

#### Your Environment
* YetiForce Version used: 4.4.46
* Browser name and version: Chrome 69.0.3497.100 (64 bit), Firefox 62.0.2 (64 bit), Safari 12.0 (64 bit)
* Environment name and version: 
* Operating System and version:

**Comment by mlorencik** [comment]
You don't have any errors in console log in browser or you think any to this problem? Error mayby will be in other than browser log, so please send us all off posible logs.

**Comment by rskrzypczak** [comment]
Probably fixed in:
https://github.com/YetiForceCompany/YetiForceCRM/commit/cc32ba3712074821c241de953bb19d434956a5d7
https://github.com/YetiForceCompany/YetiForceCRM/commit/e202edba62287590e39a91f6aa793a9279aafc4d
Bug doesn't exist in current version.
