### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#8188]
Do we have Full Manual how set up Yeti.
I try set up for 2 users. But range of service is wide.

**Comment by paula-w** [comment]
You can find our documentation [here](https://yetiforce.com/en/knowledge-base/documentation). We know it's incomplete and we're working on it.
In case the documentation doesn't help you solve your problem we can offer you our Private Cloud 1  services for 2 months for free. It includes updates, backup, and basic tech support, so we could solve your problem. After these 2 months you can either keep using the service at its regular price, or we will provide you with a copy of your system that you can place on your own server.
More details about Private Cloud 1 [here](https://yetiforce.shop/index.php?option=com_djcatalog2&view=item&id=42:private-cloud-1&cid=12:private-cloud&Itemid=1071).
