### ISSUE TITLE
New list for a module

### ISSUE THREAD

**Issue by ipanchenko1990** [YetiForceCompany/YetiForceCRM#8194]
How to create a new list for a module?

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/46469774-a761d180-c7d4-11e8-9f81-4a0eb08203a2.png)

**Comment by ipanchenko1990** [comment]
![1](https://user-images.githubusercontent.com/35902241/46470135-3b846680-c7de-11e8-9b83-bee50438b5e7.JPG)

**Comment by ipanchenko1990** [comment]
Here you need to add a new list.
