### ISSUE TITLE
New picklist

### ISSUE THREAD

**Issue by ipanchenko1990** [YetiForceCompany/YetiForceCRM#8195]
![1](https://user-images.githubusercontent.com/35902241/46472377-a1282100-c7e5-11e8-90b3-1f3ecb200ff2.JPG)
How to add a record?

**Comment by vovpff** [comment]
@ipanchenko1990 at first you need to add now picklist field here `Software configuration >Standard modules > Edit fields > System settings`

**Comment by ipanchenko1990** [comment]
Thank you!
