### ISSUE TITLE
Bugfix - How to apply?

### ISSUE THREAD

**Issue by brenomachado67** [YetiForceCompany/YetiForceCRM#8200]
#### Issue
How to apply the bug fixes?

Is there an automated process for applying bug fixes?

I see several issues solved and I do not see the bug fix files for these issues on the releases page (https://github.com/YetiForceCompany/YetiForceCRM/releases).

#### Actual Behavior
NA

#### Expected Behavior
NA

#### How to trigger the error
1. NA
2. NA
3. NA

#### Screenshot of configuration
NA

#### PHP/Apache/Browser Logs
NA

#### Your Environment

* YetiForce Version used: 4.4.0 + AttachmentsFix + ImageFix + SecuritySmartyFix + WidgetsFix
* Browser name and version: NA
* Environment name and version: NA
* Operating System and version: NA

**Comment by vovpff** [comment]
@brenomachado67 you need to wait new update package

**Comment by paula-w** [comment]
Here https://github.com/YetiForceCompany/YetiForceCRM/releases you can find the essential fixes. All the other fixes will be added when you update your CRM to a new version.
