### ISSUE TITLE
Cannot add chart from filter

### ISSUE THREAD

**Issue by faraimupfuti** [YetiForceCompany/YetiForceCRM#8203]
#### Issue

**I am using Yetiforce on Wamp server . I am struggling to add a chart from a filter onto the dashboard. I went to the Filter Configuration from System Settings, and created custom filters for each specific module (Leads, opportunities..etc), soon afterwards i activated, "LIST IN METRICS";  "ADD TO  FAVORITES" ; "SET AS DEFAULT"; "SET AS PUBLIC"  as stated in the documentation. 

Afterwards i then proceed to towards adding chart from filter on the dashboard, and once i click the "SAVE" Button, NOTHING HAPPENS. NO CHART SHOWS UP.**

#### Actual Behavior

**No Chart pops up after i click on the "SAVE" Button of the "add chart from filter" modal. But when i checked the Yetiforce demo online, the charts pops up easily.** 

#### Expected Behavior

**I should easily add a chart from filter with ease. Each time i create a filter and activate the "LIST IN METRICS" option, The charts i create should display, after i click on the save button of the "add chart from filter" modal.** 

#### Your Environment

* YetiForce Version used:    **version 4.3 and YetiForce Public License v3**

* Browser name and version:  **Google chrome Version 68.0.3440.106 (Official Build) (64-bit)**
* Environment name and version:
* Operating System and version: **windows 7 proffessional**

**Comment by rezeyle1** [comment]
The same thing happens to me ... I can not add the graphics. simply not saved. He does not show me any mistakes, but he does not save them.

**Comment by faraimupfuti** [comment]
> The same thing happens to me ... I can not add the graphics. simply not saved. He does not show me any mistakes, but he does not save them.

Did you also try to activate the , **"LIST IN METRICS"** option ?? Because i even did that and still no Charts can be added.

**Comment by rezeyle1** [comment]
I tried, but clicking "Add", Add Chart From Filter does not happen... #8306

**Comment by z0lo13** [comment]
Exactly same issue - nothing happens when i try to add a chart from filter - my filters listed in metrics and working in other modules

**Comment by rezeyle1** [comment]
This needs to be corrected urgently. An ERP with no report and no widget graphic is a dead ERP. It is a critical bug that deserves attention from the entire community because it is not working as it needs to. Please pay attention to this topic!

**Comment by fbojan** [comment]
The exact same problem

**Comment by rezeyle1** [comment]
Apparently this solves the problem. If you can test it too.

https://github.com/YetiForceCompany/UpdatePackages/blob/developer/YetiForce%20CRM%204.x.x/4.4.0_WidgetFix/zip/4.4.0_WidgetFix_v1.zip

**Comment by z0lo13** [comment]
> 
> 
> Apparently this solves the problem. If you can test it too.
> 
> https://github.com/YetiForceCompany/UpdatePackages/blob/developer/YetiForce%20CRM%204.x.x/4.4.0_WidgetFix/zip/4.4.0_WidgetFix_v1.zip

It does work with a fix

**Comment by faraimupfuti** [comment]
> > Apparently this solves the problem. If you can test it too.
> > https://github.com/YetiForceCompany/UpdatePackages/blob/developer/YetiForce%20CRM%204.x.x/4.4.0_WidgetFix/zip/4.4.0_WidgetFix_v1.zip
> 
> It does work with a fix

Perfect! let me try this and see if it works....

**Comment by mariuszkrzaczkowski** [comment]
if the fix does not work then you must give more information about the error
