### ISSUE TITLE
COMMENT_MAX_LENGTH option

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8204]
#### Question

I found option in `/config/relation.php` file:

```
$RELATION_CONFIG = [
	// Maximum length of a comment visible in the related module
	'COMMENT_MAX_LENGTH' => 20,
```
What comment mentioned here?

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/48182677-6d806f80-e32c-11e8-9844-db1ffff567d3.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski thanks. I found this comments but no ability to edit them. How to activate edition ability?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski comment edition available only in Products and Services tab. For any another related tabs not possible to change comment:
![image](https://user-images.githubusercontent.com/8545791/48183470-d1606380-e33f-11e8-8195-37d41520f9f7.png)

**Comment by mariuszkrzaczkowski** [comment]
vtiger_relatedlists
![image](https://user-images.githubusercontent.com/10198654/48183536-4b3c2100-e32f-11e8-9678-6aab6e093f81.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I know about this table. Thanks. But I can't edit comment at usual related tabs. Edit button available only in `Products and Services` tab. What's wrong?

**Comment by slawekk87** [comment]
this works only for basic M2M relation.

**Comment by vovpff** [comment]
@vovpff ok but i can't change comment with standard relation between opportunity and contact. There are no edit button at comment columm.

**Comment by slawekk87** [comment]
This is not the same functionality as comments in record detail view, some conditions must be meet to get this working. We will rename this.

**Comment by vovpff** [comment]
@slawekk87 I understand what this is different type of comments.
What conditions you mean?
There are two examples what I can see:
**1st**
I **can** change comment when I select product for account (M2M relation) trough `Products and Services` tab
**2nd**
I **can't** edit comment when I select contact for opportunity (M2M relation) trough `Contacts` tab

**Comment by slawekk87** [comment]
For this functionality to work a relation must be defined in the vtiger_crmentityrel table,
in the future it may be rebuilt, but currently it has a low priority.
