### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by ITVinci** [YetiForceCompany/YetiForceCRM#8213]
hi, I would like to know if someone works in the Italian language

**Comment by cltvchannel** [comment]
@ITVinci Hi. I will start translating in Italian language, but i will need some time to get finished.
If you want, you can help me. 
Thanks !

**Comment by mgiammarco** [comment]
Hello,
I see too that italian translation is half completed. I understand that it the actual state of art and not a problem of my instdallation. How can I contribute?
Thanks,
Mario

**Comment by paula-w** [comment]
@mgiammarco you can contribute by sending your translations in a Pull Request. Thanks!
