### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by akiyoshik** [YetiForceCompany/YetiForceCRM#8215]
#### Issue

I downloaded YetiForceCRM-4.3.0-complete.zip and installed on a shared server hosted by InMotion Hosting. The installation failed with error messages shown in attached screenshot.

It appears that it failed while attempting to update 'vtiger_users' table. I checked the corresponding databases, it was empty; there were no tables at all.

#### How to trigger the error

1. Download YetiForceCRM-4.3.0-complete.zip
2. Unzip to a directory and following installation instructions

#### Screenshot of configuration

![installation_error](https://user-images.githubusercontent.com/43900517/46567724-a91eb880-c8ec-11e8-9276-ddf6ca38e88d.jpg)

#### PHP/Apache/Browser Logs

PHP 7.0.32 (cli) (built: Sep 19 2018 20:06:03) ( NTS )

#### Your Environment

* YetiForce Version used:
YetiForceCRM-4.3.0
* Browser name and version:
Chrome - Version 69.0.3497.100 (Official Build) (64-bit)
* Environment name and version:
* Operating System and version:
Linux 2.6.32-896.16.1.lve1.4.51.el6.x86_64 #1 SMP Wed Jan 17 13:19:23 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by akiyoshik** [comment]
Part of system.log which shows the errors
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2454826/system.log)

**Comment by slawekk87** [comment]
"General error: 2006 MySQL server has gone away"
Its looks like MySQL server unexpectedly closed connection. Database related settings in php/mysql is set to recommended values?

**Comment by akiyoshik** [comment]
Thanks for the suggestion.

I rechecked the server requirement document. I set the following settings to required values:
- innodb_lock_wait_timeout
- wait_timeout
- interactive_timeout

Note that, since I don't have the permission to do the settings, I executed the settings
SET SESSION innodb_lock_wait_timeout = 600;
SET SESSION wait_timeout = 600;
SET SESSION interactive_timeout = 600;

With those settings, I was able to proceed further. 

I still see the following error repeated:

[08-Oct-2018 23:00:49 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Class 'yii\base\NotSupportedException' not found in XYZ\
/vendor/yetiforce/yii2/db/Connection.php:827
Stack trace:
#0 XYZ/vendor/yetiforce/yii2/db/Connection.php(836): yii\db\Connection->getSchema()
#1 XYZ/app/Db/Query.php(27): yii\db\Connection->getQueryBuilder()
#2 XYZ/app/Db/Query.php(95): App\Db\Query->createCommand(Object(App\Db))
#3 XYZ/app/Company.php(36): App\Db\Query->one()
#4 XYZ/app/Controller/View.php(162): App\Company::getInstanceById()
#5 XYZ/modules/Users/views/Login.php(35): App\Controller\View->preProcess(Object(App\Request), false)
#6 XYZ/include/main/WebUI.php(260): Users_Login_View->preProcess(Objec in XYZ/vendor/yetiforce/yii2/db/Connection.php on line 827

**Comment by akiyoshik** [comment]
In developer console, we notice that there were an error while loading jquery.min.js. It was loaded from an incorrect directory. I corrected it and everything started working fine. The frontend tried to load the js file from /public_html/<some prefix>/DebugBar/Resource/vendor/<...>
