### ISSUE TITLE
cannot assign incoming or outgoing e-mails to contact

### ISSUE THREAD

**Issue by midotka** [YetiForceCompany/YetiForceCRM#8216]
#### Issue
I was setting up the Mail Configuration:
![image](https://user-images.githubusercontent.com/25798541/46576355-e60bad80-c9c7-11e8-9016-59b80948b41a.png)

Setting Up Roundcube (trying with and without SSL)
![image](https://user-images.githubusercontent.com/25798541/46576405-fe2ffc80-c9c8-11e8-9e92-3a5de8d350f1.png)

setting up Mail Scanner
![image](https://user-images.githubusercontent.com/25798541/46576412-27508d00-c9c9-11e8-8662-b5abe0dfa9a9.png)

![image](https://user-images.githubusercontent.com/25798541/46576423-4818e280-c9c9-11e8-8927-9a59d01d3d0c.png)

setting up auto login
![image](https://user-images.githubusercontent.com/25798541/46576430-7ac2db00-c9c9-11e8-9ee8-5a04f4e58bfc.png)

cron is also working
![image](https://user-images.githubusercontent.com/25798541/46576438-ae9e0080-c9c9-11e8-9bd9-1099460ff43b.png)

#### Actual Behavior
No e-Mail is bind to the existing and related contact
![image](https://user-images.githubusercontent.com/25798541/46576464-1eac8680-c9ca-11e8-8ac1-e8cd2a730d4d.png)

#### Expected Behavior
emails should be shown on the summary

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Chrome newest
* Environment name and version: cent OS - newest
* Operating System and version: cent OS - newest

Installed with softaclouds

could someone please help

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/7624#issuecomment-441629733
