### ISSUE TITLE
[PL] Pole osoby współdzielące - zasada działania

### ISSUE THREAD

**Issue by turek93** [YetiForceCompany/YetiForceCRM#8224]
#### Issue
Dzień dobry,
kieruję swoje pytanie odnośnie działania/logiki pola Osoby współdzielące (np. w Kalendarzu).
Czy pole to służy do przypisania osoby, u której również powinno pojawić się zdarzenie w kalendarzu?
Przykładowa sytuacja: osoba X zakłada zadanie i w polu Osoba współdzieląca wybiera osobę Y.
Czy obie osoby X i Y powinny widzieć zdarzenie w kalendarzu?

#### Actual Behavior

Dodaję z konta X zadanie przypisane do siebie i wskazuję osobę Y jako osobę współdzielącą. W kalendarzu osoby Y nie widzę przypisanego zadania.
#### Expected Behavior

Chciałbym dodać zadanie, które będą widziały obie osoby X i Y w kalendarzu.
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: all browsers
* Environment name and version: apache,nginx
* Operating System and version:ubuntu

**Comment by bpabiszczak** [comment]
Tak, jeżeli ktoś ma przypisaną swoją osobę w Osoby współdzielące, to w teorii jest to również jego rekord. Natomiast nie oznacza to, że w każdym widoku czy widżecie, będzie widział jak swoje, zależy to od konfiguracji czy to filtrów czy widżetów.
