### ISSUE TITLE
[dev 4.4.47] Total margin percentage every save updated

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8225]
#### Issue

I noticed what current dev system every time hooks up `Total margin percentage` value updates if nothing changed:

![total_margin](https://user-images.githubusercontent.com/8545791/46613418-e026e100-cb1b-11e8-9e8f-4f8c11c5fbc2.gif)

Or if all price, tax and margin columuns are hidden:

![total_margin2](https://user-images.githubusercontent.com/8545791/46613469-fdf44600-cb1b-11e8-9f86-f31e85666cc8.gif)

#### Your Environment

* YetiForce Version used: dev 4.4.47
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/8871
