### ISSUE TITLE
Decimal separator comma 1

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#8229]
#### Issue

When a comma is used as Decimal separator, the application does not work properly!

Permissions Users Detail "Currency and number field configuration"

![vejica1](https://user-images.githubusercontent.com/25682437/46649493-8b29b000-cb99-11e8-8273-d35c8d918a77.jpg)

Taxes – Rates The amount is correct (9.5%) and does not correctly save it (9.0%)

![vejica2](https://user-images.githubusercontent.com/25682437/46649930-296a4580-cb9b-11e8-8ba3-cdcdde2160a3.jpg)

![vejica3](https://user-images.githubusercontent.com/25682437/46650234-0c824200-cb9c-11e8-9d07-8fcd7d170184.jpg)

**Comment by SkavenKF** [comment]
also problems with decimal separator comma #7630
