### ISSUE TITLE
Decimal separator comma 2

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#8230]
#### Issue

**Incorrectly calculates tax and amounts in general , when a comma is used as Decimal separator.

1. Sales invoices: Tax from the list of available taxes can not be taken because it is wrong.**

![vejica5](https://user-images.githubusercontent.com/25682437/46652532-9b468d00-cba3-11e8-81eb-3f6bf9a7f8fd.jpg)

If I enter manual custom tax, the calculation is correct until here.
![vejica6](https://user-images.githubusercontent.com/25682437/46652701-2758b480-cba4-11e8-9fa6-beb15b8a1e97.jpg)

**Correct calculation until I save my account**

![vejica7](https://user-images.githubusercontent.com/25682437/46652919-caa9c980-cba4-11e8-8b18-e578f9460996.jpg)

**The first error is in the account overview**

![vejica8](https://user-images.githubusercontent.com/25682437/46653237-c5994a00-cba5-11e8-9489-6ef63b437677.jpg)

**If i go to fool edit view, the tax itself changes from 9.5% to 95%**

![vejica9](https://user-images.githubusercontent.com/25682437/46653346-15781100-cba6-11e8-8fe4-a487f5414db3.jpg)

**However, if we add another product with another tax of 23%**

![vejica10](https://user-images.githubusercontent.com/25682437/46653720-15c4dc00-cba7-11e8-95aa-3a1eb5c081cc.jpg)

https://gitdeveloper.yetiforce.com/index.php?module=FInvoice&view=Detail&record=3617

**Comment by SkavenKF** [comment]
also problems with decimal separator comma #7630

**Comment by SkavenKF** [comment]
problem exists, i have tested at gitdeveloper ... 
look at the video at the end
1. change the user parameter
2. save with comma it is correct
3. display is also correct
4. when i change, it changed from ',' to '.' and th sum is not correct

![comma](https://user-images.githubusercontent.com/10259801/48789469-6f174380-eced-11e8-9d39-70f6e569f7de.gif)

**Comment by slawekk87** [comment]
Duplicated: #7630

**Comment by SkavenKF** [comment]
not fixed 😞 
![bugdec1](https://user-images.githubusercontent.com/10259801/48844691-d939f200-ed9a-11e8-8439-24a7f42459d1.gif)

**Comment by slawekk87** [comment]
provided value: 1.5 has bad separator - it was converted to 15,00 and 15,00* 500,00 = 7.500,00
@SkavenKF  reopen #7630, this ticket is for other module.
@mariuszkrzaczkowski
