### ISSUE TITLE
help - help to integrate yetirest api

### ISSUE THREAD

**Issue by sreejith77** [YetiForceCompany/YetiForceCRM#8242]
hello all , I am new to this.

I was trying to do an integration of yetiforce with one of our application using YetiRest and api/webservice. 

tried to do this through postman, terminal and curl. but all the time I was getting an error as 

**{"status":0,"error":{"message":"No action found","code":405}}**, 
can anyone help me to get ride of this. Please.

Please find the screenshot from postman. 

Also please note, when i try url as, **_http://hostname/api/webservice/Users/Login_** , its giving url not found error.
but , **_http://hostname/webservice/Users/Login_** , this one is working - is it okay???

Note : **mod_rewrite** is _enabled_ and **allowoverride** set to _all_

![image](https://user-images.githubusercontent.com/5688623/46691559-e4cbc200-cc0d-11e8-812a-d9248bd8195d.png)

#### Your Environment

* YetiForce Version used: 4.4
* Browser name and version: chrome and postman for windows
* Operating System and version: ubuntu 18.04

**Comment by MacarenaReina** [comment]
Hi!

Yes, the second URL is OK.
On POSTMAN, What do you have on "Authorization" and "Body" tabs?

You have to put name and password that you found on "Web service - Applications" on Authorization tab 
![yeti1](https://user-images.githubusercontent.com/16593721/46997600-00583080-d118-11e8-841a-e83fdd8d722e.png)

And the login and password you found on "Web service - Users" on Body tab like a json
![yeti2](https://user-images.githubusercontent.com/16593721/46997610-05b57b00-d118-11e8-8ab4-a1a257692546.png)

**Comment by mariuszkrzaczkowski** [comment]
you wrote the name of the module from lowercase letters and this is the difference

**Comment by rskrzypczak** [comment]
The previous comments probably solved your issue.
If you still experience problems please enable webservice logs 
https://github.com/YetiForceCompany/YetiForceCRM/blob/c4efe6bdc9b79a2e5f808dd4683ca05aa1da5d72/config/debug.php#L69-L72
