### ISSUE TITLE
CRON settings

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#8244]
I know that CRON is one of the important parts of YETIFORCE, and in version 4.3. Everything worked fine for me. I have been trying for some time, but in version 4.4. I do not know how to set up the settings correctly. I've already reviewed a lot of instructions, but unfortunately it's not. Is there any suggestion, what am I doing wrong?

YETIFORCE 4.4.
GOOGLE CHROME

![yetiforce_settings 5](https://user-images.githubusercontent.com/25682437/46718508-b11f8500-cc6b-11e8-98e6-46e0768dd8f8.png)

![cron2](https://user-images.githubusercontent.com/25682437/46718584-e6c46e00-cc6b-11e8-9a08-bf0505be0e54.jpg)
![cron3](https://user-images.githubusercontent.com/25682437/46718595-f17f0300-cc6b-11e8-999c-44a1a65e7e26.jpg)

/home/eclansi/public_html/vehovardoo/cron.php
/home/eclansi/public_html/vehovardoo/cron/cron.sh

```
export CRM_ROOT_DIR=`dirname "$0"`/..
export USE_PHP=php
#export USE_PHP=/usr/local/php53/bin/php
#export USE_PHP=/usr/local/php56/bin/php56

cd $CRM_ROOT_DIR
# TO RUN ALL CRON JOBS
$USE_PHP -f cron.php 
```

**Comment by vovpff** [comment]
@fbojan as you can see on 3rd screenshot your cron never started in the past.
I think problem with php path `export USE_PHP=php`. I don't know how your hosting works but try `php72` as path.
![image](https://user-images.githubusercontent.com/8545791/46720725-04003900-cc7a-11e8-984e-d88aa994c368.png)

**Comment by fbojan** [comment]
_**

> `/home/eclansi/public_html/perfekt/cache/logs/cron.log`

**_

/home/eclansi/public_html/perfekt/cron/cron.sh: line 5: 
: command not found
/home/eclansi/public_html/perfekt/cron/cron.sh: line 6: cd: /home/eclansi/public_html/perfekt/cron/..

: No such file or directory
/home/eclansi/public_html/perfekt/cron/cron.sh: line 8: php
: command not found

**Comment by vovpff** [comment]
@fbojan on your configuration screenshot is different:
![image](https://user-images.githubusercontent.com/8545791/46789703-c832a580-cd45-11e8-9811-b9e5614f1f16.png)

**Comment by fbojan** [comment]
Sorry that I sent the wrong configuration, but I did another installation from YETIFORCE / PERFECT /, but unfortunately there are the same problems.


/home/eclansi/public_html/vehovardoo/cache/logs/cron.log

/home/eclansi/public_html/vehovardoo/cron/cron.sh: line 5:
: command not found
/home/eclansi/public_html/vehovardoo/cron/cron.sh: line 6: cd: /home/eclansi/public_html/vehovardoo/cron/..

: No such file or directory
/home/eclansi/public_html/vehovardoo/cron/cron.sh: line 8: php
: command not found

**Comment by vovpff** [comment]
@fbojan 

My `cron.php`

```
export CRM_ROOT_DIR=`dirname "$0"`/..
export USE_PHP=/usr/bin/php7.1
#export USE_PHP=/usr/local/php53/bin/php
#export USE_PHP=/usr/local/php56/bin/php56

cd $CRM_ROOT_DIR
# TO RUN ALL CORN JOBS
$USE_PHP -f cron.php
```

try to hardcode system path

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-uzytkownika/item/enable-cron
