### ISSUE TITLE
Need Help or suggestion  in Process  for cleints to manage a project

### ISSUE THREAD

**Issue by bangde** [YetiForceCompany/YetiForceCRM#8256]
I have a project that is with an account that I have set up in the system. I want users to have access to the project I have set up for the account and I want them not to have access to nothing else as the purpose is for them to see the project, not to do anything else with the system since they are my clients.

How can this be done?

I welcome your suggestions and feedback

**Comment by mariuszkrzaczkowski** [comment]
make a private module and set it on the role


Should the list of records, related to the records we can access, be shared: according to hierarhy
