### ISSUE TITLE
Module - Sharing access | loading takes long time.

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#8267]
My system has over 500 users. Every time you change settings in the sharing access module, loading takes long time.

	 * Configuration of the permission mechanism on records list.
	 * true - Permissions based on the users column in vtiger_crmentity
	 * false - Permissions based on adding tables with permissions to query (old mechanism)
	 */
	'CACHING_PERMISSION_TO_RECORD' => true,
![catco](https://user-images.githubusercontent.com/19627226/46847601-6d658080-ce0f-11e8-9177-f729c7ce1949.png)

#### Your Environment

* YetiForce Version used: v4.3 v4.4
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by paula-w** [comment]
This module requires refactoring, we know it takes a lot of time. We’re waiting for a client who will pay for this optimization. This is currently not a priority for us.
