### ISSUE TITLE
Notification workflow 

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8274]
Originaly started here #8065 

I have created hundreds of workflows, but neither works ! 
I really dont know what else to do ! 
I need a workflow that starts on every day/week and checks entries from a given module.
Let`s say : Employees module. 
So, the workflow should start automaticaly every day/week, checks Employees modules, and if Contract Expiration Day is after 1 day , to create a notification. 

I have created every kind of workflows, even the Execution Schedule that i thought it will be appropiate, but no luck. 
On Every time the record is saved, it works. 

So, i guess its something wrong with Execution schedule. 

Please, what can i do ? I really need this to work ! 
Where should i look for seeing if something its wrong with the script/system.

PS : I have tested on GitDeveloper but no luck. With the entries available, i have created a workflow with Execution Schedule -> Daily -> set the time after 20 minutes (because i have seen that CRON is set to 15 minutes) -> Added condition -> Added notification task and receiver -> and nothing. :( 

YetiForce 4.4.0

**Comment by vovpff** [comment]
@liviubbo maybe problem here #8228

**Comment by liviubbo** [comment]
@vovpff - did you apply the commit and worked?

**Comment by liviubbo** [comment]
I applied the commit and still is not working.

**Comment by slawekk87** [comment]
I checked this on developer version and it worked:
![cond](https://user-images.githubusercontent.com/22735929/46880895-45474300-ce4a-11e8-94f9-adc0594ac9db.png)
![noti](https://user-images.githubusercontent.com/22735929/46880897-45474300-ce4a-11e8-88c1-a44939ac4280.png)
![task](https://user-images.githubusercontent.com/22735929/46880899-45474300-ce4a-11e8-9b2c-18edc4696a78.png)
![time](https://user-images.githubusercontent.com/22735929/46880900-45dfd980-ce4a-11e8-9be8-ef041894a3c9.png)

**Comment by liviubbo** [comment]
I applied the fix, and still not working ! 
I followed all instruction and still not working.
I have stock YetiForce, nothing modified (except the fixes above), and it`s not working. 
I really need this workflow. Its essential for our company.

**Comment by liviubbo** [comment]
@slawekk87  - can you please help me ? :(

**Comment by slawekk87** [comment]
![image](https://user-images.githubusercontent.com/22735929/46970144-8ba1d980-d0b8-11e8-9e8a-f980e64011e0.png)
![image](https://user-images.githubusercontent.com/22735929/46970221-c572e000-d0b8-11e8-8962-23e8f00c7536.png)
Try this settings on gitdeveloper its working

**Comment by slawekk87** [comment]
![image](https://user-images.githubusercontent.com/22735929/46970961-f6541480-d0ba-11e8-88a3-5f93fd69bdae.png)
![image](https://user-images.githubusercontent.com/22735929/46970976-01a74000-d0bb-11e8-9de4-1811cbd9bcfa.png)

**Comment by liviubbo** [comment]
Thanks, i will try it.  Problem is that i need the workfliw to work for futute dates, not past. Example: i have contract expiration date and i need to be notified two weeks before that, not after.
