### ISSUE TITLE
Users list | LBL_NOT_FOUND_QUERY_FIELD_CONDITION

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#8283]
When adding a "report to" field to the list, an error occurs
![users_list_bug](https://user-images.githubusercontent.com/19627226/46912310-28228980-cf9c-11e8-8702-b1c90b33a046.gif)

#### Your Environment

* YetiForce Version used: gitdev
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
Filter management for the user module is disabled, it is a custom module and all rules will not work.
To change columns in the list, edit the file
https://github.com/YetiForceCompany/YetiForceCRM/blob/7cd9d852eaea29da425c05e2db6d87c4fe77c939/modules/Users/Users.php#L78-L98

**Comment by ezbank** [comment]
The user module can be supported by the filter manager, layout editor, and workflow. it will be great.
