### ISSUE TITLE
New user - Can't seem to get workflows to run

### ISSUE THREAD

**Issue by jackzam** [YetiForceCompany/YetiForceCRM#8285]
Hi Everyone,

I'm a new user to YetiForce, and I'm considering starting to use it on a daily basis.
However, I'm very depended on workflows, espcially workflows that update fields, when another field is changed. (Let's say you change country to US, and you have a custom field saying "Full country name", that has to be "United States of America")

So, i've installed and configured everything, and YetiForce is running.
I've created a test workflow, but it never runs, no matter what i do, or what triggers I've set.

I've noticed in the CRON section, that last start is "01-01-1970 01:00"

Can anyone help me?

**Comment by vovpff** [comment]
You need to configure cron at your server. This is some help link https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

**Comment by jackzam** [comment]
Thank you!
