### ISSUE TITLE
Incorrect username or password

### ISSUE THREAD

**Issue by AL2018** [YetiForceCompany/YetiForceCRM#8287]
I have downloaded VF 4.4 from Source Forge and installed per the installation instructions on your web site to a localhost XAMPP installation (PHP7.2.1) on a WIN 7 machine. The server config passes the evaluation and installs, but never progresses past "Installation in progress" (even after 1 hr). However it is clear that the intall is 'finished' and i can access the YF login page. However I am unable to login which reports "Incorrect username or password". I can see that the MySQL database is populated and the admin user is correctly registered in the tables.  It would seem that either

1. The install was not complete
2. There is a communication failure with between client/PHP and MySQL. 

I have looked at published issues but they mostly relate to old PHP versions and earlier YF.    

Can you assist?

**Comment by mariuszkrzaczkowski** [comment]
1. logs?
2. hardware specification, what is your hard drive?

**Comment by AL2018** [comment]
1. mySQL table vtiger_loginhistory reports each attempt as "failed login" . I guess that demonstrates that the client is communicating with mySQL. user_name is reported correctly so there is no parsing/collation issue. Browser column report "Chrome 69" This is latest Chrome. If there is another log, where should I look?
2. Hard drive spec is LITEONIT LCT 256M3S. Driver is up to date. CPU is Xeon 3.4GHz, 64 bit 16Gb RAM

**Comment by AL2018** [comment]
Case sensitivity issue with password :(
