### ISSUE TITLE
Images in products are broken

### ISSUE THREAD

**Issue by manwenick** [YetiForceCompany/YetiForceCRM#8308]
#### Issue
If I upload image in products, I see the picture after upload. 
After few days I see only empty pic
![grafik](https://user-images.githubusercontent.com/34367573/46996356-ad34ac80-d11c-11e8-8598-9c43d08b4c3b.png)

Maybe similar with #7920 

#### Actual Behavior
Image of products appear as broken.

#### Expected Behavior
Image should be shown

#### How to trigger the error
1. Upload an image to the product
2. Save the product
3. After few days the image is empty.

#### Screenshot of configuration
as required

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: firefox, chrome.
* Environment name and version:
* Operating System and version: ubuntu 18.04

**Comment by mariuszkrzaczkowski** [comment]
check the development version
