### ISSUE TITLE
Set UP Email Ports

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#8322]
I set up smtp and RoundCube all work fine almost :)
Its only work on smtp port 25.
I am just tired of fight with it please help.

YetiForce  4.4.0
![roundcube](https://user-images.githubusercontent.com/40525437/47038056-d25b0680-d180-11e8-9f1d-a72037d67b53.jpg)
![smtp](https://user-images.githubusercontent.com/40525437/47038057-d25b0680-d180-11e8-9ef9-8e030a22e425.jpg)

**Comment by manwenick** [comment]
@mskoczek maybe you need to change mailer type in SMTP settings to SMTP?

**Comment by mskoczek** [comment]
@manwenick I did and no change. Why i rise a New issue

**Comment by bpabiszczak** [comment]
try host name with protocol like on gitdeveloper.

**Comment by mskoczek** [comment]
@bpabiszczak That config its Ok ? Safe ?

**Comment by bpabiszczak** [comment]
Yes.
