### ISSUE TITLE
Modules are not loading up when trying to create charts from filter

### ISSUE THREAD

**Issue by Dbinutu** [YetiForceCompany/YetiForceCRM#8324]
#### Issue

I have tried on the online demo and it is working nicely. In my implementation however, I am not able to see the modules when trying to create chart from filter. The modules drop down is simply non existent on that page. I can see the modules however on other parts of the system.  So for example, when I go to "Standard Modules=> Modules-Widgets" , I see the modules that I have but I do not see them when I try to create chart . Thanks

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/47351661-c4454280-d6b8-11e8-9fd3-7f23f87f823c.jpg)
