### ISSUE TITLE
Conditional Layouts

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#8325]
![conditionallayouts](https://user-images.githubusercontent.com/19627226/47065707-1fd18500-d20e-11e8-9410-eda8936b1b60.gif)

Conditional Layouts is an Extension allowing to have unique layouts for different types of records. It allows the system administrator to configure what fields/blocks to show based on other field values. It was built using vTiger Workflow capabilities and has an intuitive interface to configure conditions as well as fields to be show, hidden and made mandatory.

Control Record Layouts using field values/workflows < Supported outcomes: Hide Field, Make Mandatory, Make Read Only Compatible with Edit/Create & Detail Views

**Comment by vovpff** [comment]
This is feature request?

**Comment by cltvchannel** [comment]
+1

**Comment by SunnieG** [comment]
would love a feature like this … also how would we go about donating to Yetiforce if we wanted to

**Comment by bpabiszczak** [comment]
Want to back this issue? Post a bounty on it! We accept bounties via Bountysource .
