### ISSUE TITLE
Default sorting as DESC 

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8328]
Hy all,

    I want all my records to be sorted DESCENDING by default, by created time or modified time.

    Can YetiForce do that ? 
    I searched all options, but, nothing found.

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/47075959-f6a8f880-d1fd-11e8-8942-bcae18c6d97d.png)
or globally in the module
https://github.com/YetiForceCompany/YetiForceCRM/blob/ef7a6afc14a2ec8f2ef8cc6c491aa5bcf2979be9/modules/Accounts/Accounts.php#L79-L80
