### ISSUE TITLE
Workflow designer

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#8348]
Hi,
Any plans in the future for creating a workflow designer?

Thanks !

**Comment by cltvchannel** [comment]
@ezbank Yes.

**Comment by paula-w** [comment]
The entire workflow module will be rewritten in the nearest future.

**Comment by paula-w** [comment]
We unfortunately don't currently have enough time to implement this feature. However, if this is something urgent for the community and we get enough donations towards this functionality (https://opencollective.com/yetiforcecrm) we'll make it our priority.
