### ISSUE TITLE
Import data to related modules

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#835]
What is the process the import our existing data.

I have many accounts and many contacts per account.

Manually, 
I enter organization
Go to the contacts tab, add contact

How do I import many organizations and automatically map to contacts?

If I create a "related to" field in the module organization and choose contacts as the related module, the system creates the contact, but does not map it to the organization. I have to manually go to the related tab "contacts" under organizations and either add or select the created contact.

I cannot do this one by one. There is too much data.

Is there a way to import accounts and contacts and have them map together from an excel spreadsheet?

**Comment by bpabiszczak** [comment]
A similar problem: Import Question #907

**Comment by MaciejStencel** [comment]
This revision https://github.com/YetiForceCompany/YetiForceCRM/commit/7179ae0b4293369e1f4a88e417861bf9eb002424 should fix Your problem.
