### ISSUE TITLE
[BUG] Role based picklist

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8352]
#### Issue

Found on my 4.3.0. Also tested on gitdev.

Simple example:

I just added two picklist values to Quotes status

- pl admin - available only for admin user
- pl demo - available only for demo user

#### Actual Behavior

If picklist already has value what not available for your role you can't change this value.

Pls see gif.

#### Expected Behavior

Ability to change value to values what available to user role

#### How to trigger the error
![role based pl](https://user-images.githubusercontent.com/8545791/47144137-7226aa80-d2cf-11e8-8f15-8683a9070b56.gif)

#### Your Environment

* YetiForce Version used: gitdev 4.4.50
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
Any ideas?

**Comment by vovpff** [comment]
Just checked on gitdev 4.4.74
The same conditions like on gif: not possible to change status by picklist field but possible to change status to status progress bar

**Comment by rskrzypczak** [comment]
A user can't modify the field with a picklist value for which he doesn't have permissions. That's how the system works. In our opinion, it isn't a bug.
Second issue fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/8608/commits/6b121dcea43905eb775cfe241148fab8c76d627c

**Comment by vovpff** [comment]
@rskrzypczak ok. I has next situation.
One user (profile) should set some value to this picklist. Only this profile has this permissions. Another users (another profile) need to change status to next one step but they cant because field value not editable.

**Comment by bpabiszczak** [comment]
In my opinion the current mechanism is enough and logically correct. The current logic assumes that everyone who has permissions should be able to set previous, current, and next status, eg:

User 1: A, B
User 2: B, C
User 3: C, D
User 4: D, E

According to your logic it’s like this:

User 1: B
User 2: C
User 3: D
User 4: E

which means that everyone has one status they can set. In my opinion this is not what this field is for, if you only want to check that someone has done something you can use different fields, eg. the ‘checkbox’ field. If we adopted your approach it would cause more problems, eg. blocking statuses that people shouldn’t be able to access.

In my opinion you can achieve anything you want, but you have to assume what I described above.

**Comment by vovpff** [comment]
@bpabiszczak thanks for your explanation. Your mechanism correct. I need to rebuild my statuses list.
