### ISSUE TITLE
[Question] Purchase price in Sales orders.

### ISSUE THREAD

**Issue by manwenick** [YetiForceCompany/YetiForceCRM#8362]
#### Question
If I create a sale order, I have a possibility to insert the purchase price into the product line. 
Usually all products have a purchase price and the selling price. Is it possible, to create a field with purchase price on the product item site and automatically insert this value to the sale order, if choosing the product. Because of now, there is always manually edit needed, to get "real" margin of the price. 
Do someone have the same requirement in your sales process?

**Comment by vovpff** [comment]
@manwenick You can use price books for selling price

**Comment by manwenick** [comment]
@vovpff Hi Vladimir, 
I tried to find it. Maybe I didn't understood you right. 
I go to sales --> price books --> create new. There I only can create a name of the price book, choose currency and assignee. How can I assign / choose the products? 
Kind regards,
Nick

**Comment by paula-w** [comment]
It depends on where the system should take this price from. 
You can either create a new field, which is the easier method, or the system can take the prices from the Goods Received Note module but this requires a complex mechanism.

**Comment by vovpff** [comment]
Напиши мне на почту, я вечером постараюсь подсказать!
