### ISSUE TITLE
Editing user

### ISSUE THREAD

**Issue by ipanchenko1990** [YetiForceCompany/YetiForceCRM#8364]
When editing the user gives an error after saving.

* YetiForce Version used: 4.4.48
* Browser name and version: Google Chrome 69.0.3497.100
* Operating System and version: Windows 10
![default](https://user-images.githubusercontent.com/35902241/47203633-a9599200-d389-11e8-95f6-e70c64ab770c.JPG)

**Comment by mariuszkrzaczkowski** [comment]
Logs
