### ISSUE TITLE
[ENHANCEMENT][4.4.50][Inventory modules] Show updates of products/services rows

### ISSUE THREAD

**Issue by MacarenaReina** [YetiForceCompany/YetiForceCRM#8366]
#### Actual Behavior
No saving updates of the rows of a record in an inventory module.
![yeti1](https://user-images.githubusercontent.com/16593721/47207064-313b9e00-d382-11e8-8f5e-0c1be77470f8.png)

#### Expected Behavior
It would be so util for the user to show updates that a user has made in the rows (products or services) of a record in an inventory module.
![yeti2](https://user-images.githubusercontent.com/16593721/47207239-a60ed800-d382-11e8-8f98-26bebb319f3b.png)

#### Your Environment

* YetiForce Version used: Latest version (4.4.50)
* Browser name and version: Google chrome
* Operating System and version: Windows 10

**Comment by mariuszkrzaczkowski** [comment]
duplicate #6965
