### ISSUE TITLE
No Email Notification

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#8379]
I set up email account and check everything but i am not reciving notifications of new emails.
Please Help
YetiForce 4.4.0

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by mskoczek** [comment]
@mariuszkrzaczkowski directory cache/logs/ it is empty

**Comment by mskoczek** [comment]
@mariuszkrzaczkowski I check directory cache/logs/ and ther its no logs :(

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging

**Comment by mskoczek** [comment]
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2501435/system.log)
@ It is that what you want ?

**Comment by mskoczek** [comment]
@mariuszkrzaczkowski do you wish somthing else ?

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/82f5bd32887312717769e392c026afc16dd0fb66
