### ISSUE TITLE
Data integration API

### ISSUE THREAD

**Issue by mgiammarco** [YetiForceCompany/YetiForceCRM#8380]
Hello,
I plan to try YetiForce CRM.
I need to synchronize contacs, inventory and so on with other software.
I understand you have a rest API. I am looking for detailed documentation.
I would like to know if I can get a list of records modified after a certain date to have an easier synchronization.
Or if I can get database id of record I read.
Thanks,
Mario

**Comment by mgiammarco** [comment]
I suppose that if you have carddav/caldav integrated you already have time range queries.

**Comment by mariuszkrzaczkowski** [comment]
start with this
https://github.com/YetiForceCompany/YetiForceCRM/search?utf8=✓&q=carddav+caldav&type=Issues

Https://github.com/YetiForceCompany/YetiForceCRM/search?utf8=✓&q=API+webservice&type=Issues

https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST
