### ISSUE TITLE
Invalid request - validate Write Access

### ISSUE THREAD

**Issue by alihelal11** [YetiForceCompany/YetiForceCRM#8392]
Hi, After you install the program and when you try to login to the control panel this message appears
![default](https://user-images.githubusercontent.com/34680082/47326566-997fcd80-d669-11e8-9240-d8fdf906dc33.png)

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by alihelal11** [comment]
Where is this logs ?

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/47358835-463e6700-d6cb-11e8-9d0f-953a67a3e86b.jpg)

**Comment by alihelal11** [comment]
hello , I ask about his place

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/knowledge-base/documentation/user-documentation/item/debugging
