### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by alihelal11** [YetiForceCompany/YetiForceCRM#8395]
When you try installation what appears in the video!
Video : https://vimeo.com/296630419
* YetiForce Version used: 4.4.0
* Browser name and version: Google
* Operating System and version: Mac

**Comment by alihelal11** [comment]
PHP 7.2

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/how-to-report-bugs
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/47361720-ecda3600-d6d2-11e8-8088-163760e7da6c.jpg)
