### ISSUE TITLE
Cannot add chart from filter 

### ISSUE THREAD

**Issue by 1to10** [YetiForceCompany/YetiForceCRM#8396]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/47358835-463e6700-d6cb-11e8-9d0f-953a67a3e86b.jpg)

**Comment by 1to10** [comment]
![bug](https://user-images.githubusercontent.com/9332876/47405549-a71f7b00-d76f-11e8-8076-73daeaf9fe34.png)
this is scren shot

**Comment by 1to10** [comment]
![server](https://user-images.githubusercontent.com/9332876/47405602-fa91c900-d76f-11e8-8cf6-b3e051b908d6.png)

**Comment by 1to10** [comment]
![bug](https://user-images.githubusercontent.com/9332876/47405700-7724a780-d770-11e8-84ce-89ac8c80e5be.png)

**Comment by 1to10** [comment]
![bug](https://user-images.githubusercontent.com/9332876/47405720-928fb280-d770-11e8-95af-3ec1c9474d7c.png)

**Comment by 1to10** [comment]
![bug](https://user-images.githubusercontent.com/9332876/47405753-b3f09e80-d770-11e8-938a-a1f15ea23ed1.png)

**Comment by 1to10** [comment]
![bug](https://user-images.githubusercontent.com/9332876/47405795-e26e7980-d770-11e8-938a-502149ad876c.png)

**Comment by 1to10** [comment]
![server](https://user-images.githubusercontent.com/9332876/47405826-1184eb00-d771-11e8-9da2-9eb8ef876459.png)

**Comment by 1to10** [comment]
![server1](https://user-images.githubusercontent.com/9332876/47405879-5e68c180-d771-11e8-9adb-c9e4633eb773.png)

**Comment by 1to10** [comment]
![server2](https://user-images.githubusercontent.com/9332876/47405924-c5867600-d771-11e8-9b3d-89f0bef0a366.png)

**Comment by 1to10** [comment]
![server4](https://user-images.githubusercontent.com/9332876/47406001-1302e300-d772-11e8-81e8-61c520771d2e.png)

**Comment by 1to10** [comment]
please give me solution

**Comment by mariuszkrzaczkowski** [comment]
Test the development version, the filter edition has been rebuilt.
