### ISSUE TITLE
LDAP - Providing username/password for LDAP server

### ISSUE THREAD

**Issue by jackzam** [YetiForceCompany/YetiForceCRM#8398]
Hi!

I'm new to YetiForce, but not CRM-systems in general.
I love everything about YetiForce, but it has some minor setbacks though.

One of them is the LDAP integration.

I have a test DC, but no matter what i do i can't talk to it, using YetiForce.
The reason is that it doesn't allow anonymous LDAP requests - so i need to provide it with a username/password to make requests.

Is there anywhere in the code i can change something, to make this a possibility (binding a user to the lookup)?

It would also be lovely if i were able to select a Search DN

I'm _not_ a programmer, but looking at the code, it doesn't seem to difficult.
This page should have all information needed:

https://pear.php.net/manual/en/package.authentication.auth.storage.ldap.php

Also, looking at /modules/Users/authmethods at looks like it does some kind of bind on line 54, but I'm not sure where it is actually used.

**Comment by mariuszkrzaczkowski** [comment]
You do not need DC, you only need to know the domain, see ttps://github.com/YetiForceCompany/YetiForceCRM/issues/4490
for authorization in ldap we use the ldap_bind function not of the library you sent.ttp://php.net/manual/en/function.ldap-bind.php
