### ISSUE TITLE
Fix notifications workflow

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#8405]
Again, after posting here #8274 and here #8065 , and havin no solution yet, i am writing again.
I have tried all solutions presented to this problem and didnt managed to sort it out. 
I have tried even on gitdeveloper version and still doenst work there.

I really need the notifications.
So, if there is anyone to help me, even if i dont have much money, i can pay for someone to look into the situation (reasonable amount) or, if someone is willing to help just pro bono, will be wellcomed. 

I say again, i didnt made any changes in the script, so, i guess it should work.
I dont know why is not triggering the event. CRON is working, everythingelse is working, but this. 

I am writing so often because, for me, these notifications are vital.

**Comment by vovpff** [comment]
@liviubbo i will try to help you. Pls explain shortly what is the problem?
I can implement anything on my local sandbox 4.3 version system.

**Comment by liviubbo** [comment]
@vovpff - the same thing as in all tickets i have posted.

  - I need some workflows, that that automaticaly (scheduled), and triggered on date. 
    Example : i have emplooyes that have - contract expiration date - with to weeks before date is due, i need a notification for 3 user profiles. 

    Now, i have tried workflows on gitdeveloper, i have tried all that was posted here (even by you), and nothing. I guess is a bug.

**Comment by vovpff** [comment]
> Example : i have emplooyes that have

You mean system users?

**Comment by liviubbo** [comment]
@vovpff  - No, not users, module Employees. The entry has a field created by me : Contract expiration date.

**Comment by vovpff** [comment]
Thx. I will try to implement it and answer you.

**Comment by liviubbo** [comment]
@vovpff - Thank you !

**Comment by vovpff** [comment]
@liviubbo vhat condition you use for date triggering?

**Comment by liviubbo** [comment]
Just created a workflow on Gitdeveloper. 
I set at one employee, birth date : today - i have create a workflow with scheduled (default time intervals) , daily, with starting hour (after 25 minutes), condition : birth day is today , action - notification.

Its not working. I got no notification. :(

**Comment by liviubbo** [comment]
Nothing ?

**Comment by vovpff** [comment]
For this time yes. I tried to check but has no result

**Comment by liviubbo** [comment]
@vovpff - You cannot replicate, or fix ?

**Comment by liviubbo** [comment]
@vovpff  - Thank you anyway for the help. Do you know were i can find some YetiForce specialist to fix this ? Because i don`t want to post on Freelancer. There are alot of scammers there.

**Comment by vovpff** [comment]
@liviubbo i think this is some bug with workflow start on some condition. But I can't catch dependency

**Comment by liviubbo** [comment]
SOLVED here #8511
