### ISSUE TITLE
[Question] Widgets country coloring

### ISSUE THREAD

**Issue by Pietrox** [YetiForceCompany/YetiForceCRM#8406]
Hello,

I recently started to prepare to update the CRM to 4.4. Specially for the reports/widgets new design that can at least partially replace our BI.
But I'm stuck at configuring the colors. I can't find where to define the colors for country field. It's not available in country section and it does not appear in picklists, am I missing something? It works on demo - Poland is colored as green, while our fresh install is greying all records.
Talking about "Group by" to be more specific.

**Comment by Pietrox** [comment]
Any info on it? I know I havent posted version, OS etc, but this is only about configuration or at least where to look in SQL would really help.

**Comment by paula-w** [comment]
Right now you can’t configure colors for the “country” field. If there is no defined color for a bar then the system will pick one of the default colors.
