### ISSUE TITLE
Cron not running generates Syntax error

### ISSUE THREAD

**Issue by Andrew-W-Robinson** [YetiForceCompany/YetiForceCRM#8409]
<p>To summarise, the system/server itself is running cron jobs as expected, when it runs the vtiger cron (that triggers all the workflows etc to run) it encounters the following PHP Syntax Error:<br></p><pre style="padding:12px;background-color:#444;color:#f8f8f8;"><code>PHP Parse error:  syntax error, unexpected '?' in /home/buco/domains/british-utilities.co.uk/public_html/crm1/include/database/PearDatabase.php on line 808
</code></pre> <br><hr>Generated by YetiforceCRM ver. 4.4.0<br>PHP: 7.1.17<br><br><strong>Server configuration errors:</strong><br>session.gc_maxlifetime: 1440<br>auto_detect_line_endings: Off<br><strong>Library errors:</strong><br>exif_read_data<br>ldap_connect<br>opcache_get_configuration<br>apcu<br>

**Comment by mariuszkrzaczkowski** [comment]
attach the PearDatabase.php file to the github

**Comment by Andrew-W-Robinson** [comment]
[PearDatabase.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/2525930/PearDatabase.zip)

**Comment by Andrew-W-Robinson** [comment]
Pear database attached

**Comment by TomaszQr** [comment]
Please check the PHP version for CLI, it's most likely outdated.
You can check it here : Software configuration -> Logs -> Server configuration

**Comment by Andrew-W-Robinson** [comment]
The cronCLI section appears to be blank. I have  modified the vtigercron.sh script and tried specifying the binaries for both PHP 7.1 and 7.2, which are the recommended versions listed. After re-running the cron the below error is now being presented.
PHP Fatal error:  Uncaught Error: Call to undefined function vglobal() in /home/buco/domains/british-utilities.co.uk/public_html/crm1/cron/vtigercron.php:37
Stack trace:
#0 {main}
  thrown in /home/buco/domains/british-utilities.co.uk/public_html/crm1/cron/vtigercron.php on line 37

[vtigercron.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/2562354/vtigercron.zip)

**Comment by slawekk87** [comment]
In v4.4 there is no such file as vtigercron.php:
https://github.com/YetiForceCompany/YetiForceCRM/tree/4.4.0/cron

You need to update config to use one of: 
YetiForceCRM/cron.php or YetiForceCRM/public_html/cron.php
