### ISSUE TITLE
Any plans for one of these features?

### ISSUE THREAD

**Issue by cristyxx** [YetiForceCompany/YetiForceCRM#8410]
There are any plans to inregrate one of these features?
- Calculation field (SUM, MIN, MAX, AVG)
- Multi columns block (ability to chose 2,3,4 blocks display)
- List view colors (Color list row based on a value) (This was avabile in the past but deprecated)
- Conditional Layouts (There is already a feature request for this)
- PDF Maker (something like in SuiteCRM)
- Reports (A must have module)

Thanks !

**Comment by paula-w** [comment]
1. We’re currently not planning any changes in the display of 2,3,4 column configuration. You can freely place widgets on your dashboard. In record preview you can specify 1,2,3 columns in summary. You can add the “record details” widget in summary, it displays everything in one block. There are many options in the system already, and we believe there are more important things that require our attention right now.
2. You can color any picklist field you want, we don’t see the need to color entire rows.
3. Not sure what you mean by PDFMaker, what you can find in YetiForce currently is more advanced than the functionality in SuiteCRM.
4. Reports are currently under development.

**Comment by cristyxx** [comment]
@paula-w 2,3,4 columns configuration is needed for record detail view.
PDFMaker from SuiteCRM is easier to use. 
Eg. If you want to create an invoice template, the invoice table is harder to change right now, and it's not possible what columns need to show and what column don't need to show on Invoice PDF.
Colored field it's avabile only for picklist field and it's not helping so much.
And something about calculated field?
