### ISSUE TITLE
Cron not running generates Syntax error

### ISSUE THREAD

**Issue by Andrew-W-Robinson** [YetiForceCompany/YetiForceCRM#8418]
&lt;?php<br>/* * *******************************************************************************<br> * The contents of this file are subject to the SugarCRM Public License Version 1.1.2<br> * ("License"); You may not use this file except in compliance with the<br> * License. You may obtain a copy of the License at http://www.sugarcrm.com/SPL<br> * Software distributed under the License is distributed on an  "AS IS"  basis,<br> * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for<br> * the specific language governing rights and limitations under the License.<br> * The Original Code is:  SugarCRM Open Source<br> * The Initial Developer of the Original Code is SugarCRM, Inc.<br> * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc.;<br> * All Rights Reserved.<br> * Contributor(s): YetiForce.com<br> * ****************************************************************************** */<br><br>class PearDatabase<br>{<br>    protected $database;<br>    protected $stmt = false;<br>    public $dieOnError = false;<br>    private static $dbCache = false;<br>    protected $dbType;<br>    protected $dbHostName;<br>    protected $dbName;<br>    protected $userName;<br>    protected $userPassword;<br>    protected $port;<br>    // If you want to avoid executing PreparedStatement, set this to true<br>    // PreparedStatement will be converted to normal SQL statement for execution<br>    protected $avoidPreparedSql = false;<br><br>    /**<br>     * Performance tunning parameters (can be configured through performance.prefs.php)<br>     * See the constructor for initialization.<br>     */<br>    protected $isdb_default_utf8_charset = false;<br>    protected $hasActiveTransaction = false;<br>    protected $hasFailedTransaction = false;<br>    protected $transCnt = 0;<br>    protected $autoCommit = false;<br><br>    const DEFAULT_QUOTE = '`';<br><br>    protected $types = [<br>        PDO::PARAM_BOOL =&gt; 'bool',<br>        PDO::PARAM_NULL =&gt; 'null',<br>        PDO::PARAM_INT =&gt; 'int',<br>        PDO::PARAM_LOB =&gt; 'blob',<br>        PDO::PARAM_STR =&gt; 'string',<br>        PDO::PARAM_STMT =&gt; 'statement',<br>    ];<br><br>    /**<br>     * Constructor.<br>     */<br>    public function __construct($dbtype = '', $host = '', $dbname = '', $username = '', $passwd = '', $port = 3306)<br>    {<br>        $this-&gt;loadDBConfig($dbtype, $host, $dbname, $username, $passwd, $port);<br>        $this-&gt;isdb_default_utf8_charset = AppConfig::performance('DB_DEFAULT_CHARSET_UTF8');<br>        $this-&gt;setDieOnError(AppConfig::debug('SQL_DIE_ON_ERROR'));<br>        $this-&gt;connect();<br>    }<br><br>    /**<br>     * Manage instance usage of this class.<br>     */<br>    public static function &amp;getInstance($type = 'base')<br>    {<br>        if (self::$dbCache !== false) {<br>            return self::$dbCache;<br>        }<br>        $config = AppConfig::main('dbconfig');<br>        if ($config === false) {<br>            include 'config/config.inc.php';<br>            if (file_exists('config/config_override.php')) {<br>                include 'config/config_override.php';<br>            }<br>            $config = $dbconfig;<br>        }<br>        $db = new self($config['db_type'], $config['db_server'], $config['db_name'], $config['db_username'], $config['db_password'], $config['db_port']);<br><br>        if ($db-&gt;database === null) {<br>            \App\Log::error('Database getInstance: Error connecting to the database', 'error');<br>            $db-&gt;checkError('Error connecting to the database');<br><br>            return false;<br>        } else {<br>            self::$dbCache = $db;<br>        }<br>        return $db;<br>    }<br><br>    public function connect()<br>    {<br>        // Set DSN<br>        $dsn = $this-&gt;dbType . ':host=' . $this-&gt;dbHostName . ';dbname=' . $this-&gt;dbName . ';port=' . $this-&gt;port;<br><br>        // Set options<br>        $options = [<br>            PDO::ATTR_EMULATE_PREPARES =&gt; false,<br>            PDO::ATTR_ERRMODE =&gt; PDO::ERRMODE_EXCEPTION,<br>            PDO::ATTR_TIMEOUT =&gt; 5,<br>        ];<br>        // Create a new PDO instanace<br>        try {<br>            $this-&gt;database = new PDO($dsn, $this-&gt;userName, $this-&gt;userPassword, $options);<br>            $this-&gt;database-&gt;exec('SET NAMES ' . $this-&gt;database-&gt;quote('utf8'));<br>        } catch (\App\Exceptions\AppException $e) {<br>            // Catch any errors<br>            \App\Log::error('Database connect : ' . $e-&gt;getMessage());<br>            $this-&gt;checkError($e-&gt;getMessage());<br>        }<br>    }<br><br>    protected function loadDBConfig($dbtype, $host, $dbname, $username, $passwd, $port)<br>    {<br>        if ($host == '_SERVER_') {<br>            \App\Log::error('No configuration for the database connection');<br>        }<br>        $this-&gt;dbType = $dbtype;<br>        $this-&gt;dbHostName = $host;<br>        $this-&gt;dbName = $dbname;<br>        $this-&gt;userName = $username;<br>        $this-&gt;userPassword = $passwd;<br>        $this-&gt;port = $port;<br>    }<br><br>    public function setDBCache()<br>    {<br>        self::$dbCache = $this;<br>    }<br><br>    public function getDatabaseName()<br>    {<br>        return $this-&gt;dbName;<br>    }<br><br>    public function println($msg)<br>    {<br>        return $msg;<br>    }<br><br>    public function checkError($message, $dieOnError = false, $query = false, $params = false)<br>    {<br>        if ($this-&gt;hasActiveTransaction) {<br>            $this-&gt;rollbackTransaction();<br>        }<br>        if ($this-&gt;dieOnError || $dieOnError) {<br>            $backtrace = false;<br>            if (AppConfig::debug('DISPLAY_EXCEPTION_BACKTRACE')) {<br>                $backtrace = \App\Debuger::getBacktrace();<br>            }<br>            $message = [<br>                'message' =&gt; $message,<br>                'trace' =&gt; $backtrace,<br>                'query' =&gt; $query,<br>                'params' =&gt; $params,<br>            ];<br>            vtlib\Functions::throwNewException($message, true, 'DatabaseException.tpl');<br>        }<br>    }<br><br>    public function errorMsg()<br>    {<br>        $error = $this-&gt;database-&gt;errorInfo();<br><br>        return $error[2];<br>    }<br><br>    public function isMySQL()<br>    {<br>        return stripos($this-&gt;dbType, 'mysql') === 0;<br>    }<br><br>    public function isOracle()<br>    {<br>        return $this-&gt;dbType == 'oci8';<br>    }<br><br>    public function isPostgres()<br>    {<br>        return $this-&gt;dbType == 'pgsql';<br>    }<br><br>    public function setDieOnError($value)<br>    {<br>        $this-&gt;dieOnError = $value;<br>    }<br><br>    public function setAttribute($attribute, $value)<br>    {<br>        $this-&gt;database-&gt;setAttribute($attribute, $value);<br>    }<br><br>    public function startTransaction()<br>    {<br>        $this-&gt;transCnt += 1;<br><br>        if ($this-&gt;hasActiveTransaction) {<br>            return $this-&gt;hasActiveTransaction;<br>        } else {<br>            $this-&gt;autoCommit = false;<br>            $this-&gt;hasActiveTransaction = $this-&gt;database-&gt;beginTransaction();<br><br>            return $this-&gt;hasActiveTransaction;<br>        }<br>    }<br><br>    public function completeTransaction()<br>    {<br>        $this-&gt;transCnt -= 1;<br><br>        if ($this-&gt;transCnt == 0) {<br>            $this-&gt;database-&gt;commit();<br>            $this-&gt;autoCommit = false;<br>            $this-&gt;hasActiveTransaction = false;<br>        }<br>    }<br><br>    public function hasFailedTransaction()<br>    {<br>        return $this-&gt;hasFailedTransaction;<br>    }<br><br>    public function rollbackTransaction()<br>    {<br>        if ($this-&gt;hasActiveTransaction) {<br>            $this-&gt;hasFailedTransaction = true;<br>            $result = $this-&gt;database-&gt;rollback();<br>            $this-&gt;autoCommit = false;<br>            $this-&gt;transCnt -= 1;<br><br>            return $result;<br>        }<br>        return false;<br>    }<br><br>    public function getRowCount(PDOStatement $result)<br>    {<br>        if (method_exists($result, 'rowCount')) {<br>            return $result-&gt;rowCount();<br>        }<br>        App\Log::warning('No rowCount function');<br><br>        return 0;<br>    }<br><br>    public function numRows(PDOStatement $result)<br>    {<br>        return $result-&gt;rowCount();<br>    }<br><br>    public function getFieldsCount(PDOStatement $result)<br>    {<br>        return $result-&gt;columnCount();<br>    }<br><br>    public function fetchArray(PDOStatement $result)<br>    {<br>        return $result-&gt;fetch(PDO::FETCH_ASSOC);<br>    }<br><br>    public function getSingleValue(PDOStatement $result)<br>    {<br>        return $result-&gt;fetchColumn();<br>    }<br><br>    public function getRow(PDOStatement $result)<br>    {<br>        return $result-&gt;fetch(PDO::FETCH_ASSOC);<br>    }<br><br>    public function getColumnByGroup(PDOStatement $result)<br>    {<br>        return $result-&gt;fetchAll(PDO::FETCH_GROUP | PDO::FETCH_COLUMN);<br>    }<br><br>    public function getArray(PDOStatement $result)<br>    {<br>        return $result-&gt;fetchAll(PDO::FETCH_ASSOC);<br>    }<br><br>    public function getArrayColumn(PDOStatement $result, $column = 0)<br>    {<br>        return $result-&gt;fetchAll(PDO::FETCH_COLUMN, $column);<br>    }<br><br>    public function disconnect()<br>    {<br>        if (isset($this-&gt;database)) {<br>            unset($this-&gt;database);<br>        }<br>    }<br><br>    public function query($query, $dieOnError = false, $msg = '')<br>    {<br>        $this-&gt;stmt = false;<br>        $sqlStartTime = microtime(true);<br><br>        try {<br>            \App\Log::beginProfile($query, __METHOD__);<br>            $this-&gt;stmt = $this-&gt;database-&gt;query($query);<br>            \App\Log::endProfile($query, __METHOD__);<br><br>            $this-&gt;logSqlTime($sqlStartTime, microtime(true), $query);<br>        } catch (PDOException $e) {<br>            $error = $this-&gt;database-&gt;errorInfo();<br>            \App\Log::error($msg . 'Query Failed: ' . $query . ' | ' . $error[2] . ' | ' . $e-&gt;getMessage());<br>            $this-&gt;checkError($e-&gt;getMessage(), $dieOnError, $query);<br>        }<br>        return $this-&gt;stmt;<br>    }<br><br>    /* Prepared statement Execution<br>     * @param $sql -- Prepared sql statement<br>     * @param $params -- Parameters for the prepared statement<br>     * @param $dieOnError -- Set to true, when query execution fails<br>     * @param $msg -- Error message on query execution failure<br>     */<br><br>    public function pquery($query, $params = [], $dieOnError = false, $msg = '')<br>    {<br>        $this-&gt;stmt = false;<br>        $sqlStartTime = microtime(true);<br>        $params = $this-&gt;flattenArray($params);<br>        if (empty($params)) {<br>            return $this-&gt;query($query, $dieOnError, $msg);<br>        }<br>        try {<br>            $this-&gt;stmt = $this-&gt;database-&gt;prepare($query);<br><br>            \App\Log::beginProfile($query, __METHOD__);<br>            $this-&gt;stmt-&gt;execute($params);<br>            \App\Log::endProfile($query, __METHOD__);<br><br>            $this-&gt;logSqlTime($sqlStartTime, microtime(true), $query, $params);<br>        } catch (PDOException $e) {<br>            $error = $this-&gt;database-&gt;errorInfo();<br>            \App\Log::error($msg . 'Query Failed: ' . $query . ' | ' . $error[2] . ' | ' . $e-&gt;getMessage());<br>            $this-&gt;checkError($e-&gt;getMessage(), $dieOnError, $query, $params);<br>        }<br>        return $this-&gt;stmt;<br>    }<br><br>    public function prepare($query)<br>    {<br>        $this-&gt;stmt = $this-&gt;database-&gt;prepare($query);<br><br>        return $this-&gt;stmt;<br>    }<br><br>    public function bind($param, $value, $type = null)<br>    {<br>        if (is_null($type)) {<br>            switch (true) {<br>                case is_int($value):<br>                    $type = PDO::PARAM_INT;<br>                    break;<br>                case is_bool($value):<br>                    $type = PDO::PARAM_BOOL;<br>                    break;<br>                case is_null($value):<br>                    $type = PDO::PARAM_NULL;<br>                    break;<br>                default:<br>                    $type = PDO::PARAM_STR;<br>            }<br>        }<br>        $this-&gt;stmt-&gt;bindValue($param, $value, $type);<br>    }<br><br>    public function execute()<br>    {<br>        try {<br>            $this-&gt;stmt-&gt;execute($params);<br>            $this-&gt;logSqlTime($sqlStartTime, microtime(true), $query, $params);<br>        } catch (\App\Exceptions\AppException $e) {<br>            $error = $this-&gt;database-&gt;errorInfo();<br>            \App\Log::error($msg . 'Query Failed: ' . $query . ' | ' . $error[2] . ' | ' . $e-&gt;getMessage());<br>            $this-&gt;checkError($e-&gt;getMessage());<br>        }<br>        return $this-&gt;stmt;<br>    }<br><br>    /**<br>     * A function to insert data into the database.<br>     *<br>     * @param string $table Table name<br>     * @param array  $data  Query data<br>     *<br>     * @return array Row count and last insert id<br>     */<br>    public function insert($table, array $data)<br>    {<br>        if (!$table) {<br>            \App\Log::error('Missing table name');<br>            $this-&gt;checkError('Missing table name');<br><br>            return false;<br>        } elseif (!is_array($data)) {<br>            \App\Log::error('Missing data, data must be an array');<br>            $this-&gt;checkError('Missing table name');<br><br>            return false;<br>        }<br>        $columns = '';<br>        foreach ($data as $column =&gt; $cur) {<br>            $columns .= ($columns ? ',' : '') . $this-&gt;quote($column, false);<br>        }<br>        $insert = 'INSERT INTO ' . $this-&gt;quote($table, false) . ' (' . $columns . ') VALUES (' . $this-&gt;generateQuestionMarks($data) . ')';<br>        $this-&gt;pquery($insert, $data);<br><br>        return ['rowCount' =&gt; $this-&gt;stmt-&gt;rowCount(), 'id' =&gt; $this-&gt;database-&gt;lastInsertId()];<br>    }<br><br>    /**<br>     * A function to remove data from the database.<br>     *<br>     * @param string $table  Table name<br>     * @param string $where  Conditions<br>     * @param array  $params Query data<br>     *<br>     * @return int Number of deleted records<br>     */<br>    public function delete($table, $where = '', array $params = [])<br>    {<br>        if (!$table) {<br>            \App\Log::error('Missing table name');<br>            $this-&gt;checkError('Missing table name');<br><br>            return false;<br>        }<br>        if ($where != '') {<br>            $where = sprintf('WHERE %s', $where);<br>        }<br>        if (count($params) === 0) {<br>            $this-&gt;query(sprintf('DELETE FROM %s %s', $table, $where));<br>        } else {<br>            $this-&gt;pquery(sprintf('DELETE FROM %s %s', $table, $where), $params);<br>        }<br>        return $this-&gt;stmt-&gt;rowCount();<br>    }<br><br>    /**<br>     * A function to update data in the database.<br>     *<br>     * @param string $table   Table name<br>     * @param array  $columns Columns to update<br>     * @param string $where   Conditions<br>     * @param array  $params  Query data<br>     *<br>     * @return int Number of updated records<br>     */<br>    public function update($table, array $columns, $where = false, array $params = [])<br>    {<br>        $query = "UPDATE $table SET ";<br>        foreach ($columns as $column =&gt; $value) {<br>            $query .= $this-&gt;quote($column, false) . ' = ?,';<br>            $values[] = $value;<br>        }<br>        $query = trim($query, ',');<br>        if ($where !== false) {<br>            $query .= sprintf(' WHERE %s', $where);<br>        }<br>        $this-&gt;pquery(trim($query, ','), [array_merge($values, $params)]);<br><br>        return $this-&gt;stmt-&gt;rowCount();<br>    }<br><br>    public function queryResult(&amp;$result, $row, $col = 0)<br>    {<br>        return $this-&gt;queryResultRaw($result, $row, $col);<br>    }<br><br>    public function queryResultRaw(&amp;$result, $row, $col = 0)<br>    {<br>        if (!is_object($result)) {<br>            \App\Log::error('Result is not an object');<br>            $this-&gt;checkError('Result is not an object');<br>        }<br><br>        if (!isset($result-&gt;tmp)) {<br>            $result-&gt;tmp = $result-&gt;fetchAll(PDO::FETCH_ASSOC);<br>        }<br>        if (!isset($result-&gt;tmp[$row]) || !isset($result-&gt;tmp[$row][$col])) {<br>            return null;<br>        }<br>        return $result-&gt;tmp[$row][$col];<br>    }<br><br>    // Function to get particular row from the query result<br>    public function queryResultRowData(&amp;$result, $row = 0)<br>    {<br>        return $this-&gt;rawQueryResultRowData($result, $row);<br>    }<br><br>    /**<br>     * Get an array representing a row in the result set<br>     * Unlike it's non raw siblings this method will not escape<br>     * html entities in return strings.<br>     *<br>     * The case of all the field names is converted to lower case.<br>     * as with the other methods.<br>     *<br>     * @param &amp;$result The query result to fetch from<br>     * @param $row The row number to fetch. It's default value is 0<br>     */<br>    public function rawQueryResultRowData(&amp;$result, $row = 0)<br>    {<br>        if (!is_object($result)) {<br>            \App\Log::error('Result is not an object');<br>            $this-&gt;checkError('Result is not an object');<br>        }<br>        if (!isset($result-&gt;tmp)) {<br>            $result-&gt;tmp = $result-&gt;fetchAll(PDO::FETCH_ASSOC);<br>        }<br>        return $result-&gt;tmp[$row];<br>    }<br><br>    /**<br>     * Flatten the composite array into single value.<br>     * Example:<br>     * $input = array(10, 20, array(30, 40), array('key1' =&gt; '50', 'key2'=&gt;array(60), 70));<br>     * returns array(10, 20, 30, 40, 50, 60, 70);.<br>     */<br>    public function flattenArray($input, $output = null)<br>    {<br>        if (empty($input)) {<br>            return null;<br>        }<br>        if (empty($output)) {<br>            $output = [];<br>        }<br>        foreach ($input as $value) {<br>            if (is_array($value)) {<br>                $output = $this-&gt;flattenArray($value, $output);<br>            } else {<br>                array_push($output, $value);<br>            }<br>        }<br>        return $output;<br>    }<br><br>    public function getColumnNames($tablename)<br>    {<br>        $stmt = $this-&gt;database-&gt;query('SHOW COLUMNS FROM ' . $tablename, PDO::FETCH_OBJ);<br>        $columns = [];<br>        foreach ($stmt as $col) {<br>            $columns[] = $col-&gt;Field;<br>        }<br>        return $columns;<br>    }<br><br>    public function getColumnsMeta($tablename)<br>    {<br>        $stmt = $this-&gt;database-&gt;query('SHOW COLUMNS FROM ' . $tablename, PDO::FETCH_OBJ);<br>        $columns = [];<br>        foreach ($stmt as $col) {<br>            if (strpos($col-&gt;Type, '(') !== false) {<br>                $showType = explode('(', $col-&gt;Type); //PREG_SPLIT IS BETTER<br>            }<br>            $type = $showType[0];<br>            $vals = explode(')', $showType[1]);<br>            if (is_int((int) $vals[0])) {<br>                $maxLength = $vals[0];<br>            } elseif (strpos($vals[0], ',') !== false) {<br>                $vs = explode(',', $vals[0]);<br>                $vs = array_map('str_replace', $vs, ['\'', '', $vs[0]]);<br>                $maxLength = [];<br>                foreach ($vs as $v) {<br>                    $maxLength[] = $v;<br>                }<br>            }<br>            $column = new stdClass();<br>            $column-&gt;name = $col-&gt;Field;<br>            $column-&gt;notNull = $col-&gt;null == 'NO' ? true : false;<br>            $column-&gt;primaryKey = $col-&gt;Key == 'PRI' ? true : false;<br>            $column-&gt;uniqueKey = $col-&gt;Key == 'UNI' ? true : false;<br>            $column-&gt;hasDefault = $col-&gt;Default === null ? false : true;<br>            if ($column-&gt;hasDefault) {<br>                $column-&gt;default = $col-&gt;Default;<br>            }<br>            $column-&gt;maxLength = $maxLength;<br>            $column-&gt;type = $type;<br>            $columns[strtoupper($column-&gt;name)] = $column;<br>        }<br>        return $columns;<br>    }<br><br>    public function updateBlob($table, $column, $val, $where)<br>    {<br>        $success = $this-&gt;pquery("UPDATE $table SET $column=? WHERE $where", [$val]);<br><br>        return $success;<br>    }<br><br>    public function getEmptyBlob()<br>    {<br>        return 'null';<br>    }<br><br>    public function fetchByAssoc(&amp;$result, $rowNum = -1)<br>    {<br>        if (isset($result) &amp;&amp; $rowNum &lt; 0) {<br>            $row = $this-&gt;getRow($result);<br><br>            return $row;<br>        }<br>        if ($this-&gt;getRowCount($result) &gt; $rowNum) {<br>            $row = $this-&gt;rawQueryResultRowData($result, $rowNum);<br>        }<br>        return $row;<br>    }<br><br>    //To get a function name with respect to the database type which escapes strings in given text<br>    public function sqlEscapeString($str, $type = false)<br>    {<br>        if ($type) {<br>            $search = ['\\', "\0", "\n", "\r", "\x1a", "'", '"'];<br>            $replace = ['\\\\', '\\0', '\\n', '\\r', "\Z", "\'", '\"'];<br><br>            return str_replace($search, $replace, $str);<br>        } else {<br>            return $this-&gt;database-&gt;quote($str);<br>        }<br>    }<br><br>    public function getUniqueID($seqname)<br>    {<br>        $tableName = $seqname . '_seq';<br>        if ($this-&gt;checkExistTable($tableName)) {<br>            $result = $this-&gt;query(sprintf('SELECT id FROM %s', $tableName));<br>            $id = ((int) $this-&gt;getSingleValue($result)) + 1;<br>            $this-&gt;database-&gt;query("update $tableName set id = $id");<br>        } else {<br>            $result = $this-&gt;query('SHOW COLUMNS FROM ' . $this-&gt;quote($seqname, false));<br>            $column = $this-&gt;getSingleValue($result);<br>            $result = $this-&gt;query("SELECT MAX($column ) AS max FROM " . $this-&gt;quote($seqname, false));<br>            $id = ((int) $this-&gt;getSingleValue($result)) + 1;<br>        }<br>        return $id;<br>    }<br><br>    public function checkExistTable($tableName, $cache = true)<br>    {<br>        $tablePresent = Vtiger_Cache::get('checkExistTable', $tableName);<br>        if ($tablePresent !== false &amp;&amp; $cache) {<br>            return $tablePresent;<br>        }<br><br>        $dieOnError = $this-&gt;dieOnError;<br>        $this-&gt;dieOnError = false;<br><br>        $tablename = $this-&gt;sqlEscapeString($tableName);<br>        $tableCheck = $this-&gt;query("SHOW TABLES LIKE $tablename");<br>        $tablePresent = 1;<br>        if (empty($tableCheck) || $this-&gt;getRowCount($tableCheck) === 0) {<br>            $tablePresent = 0;<br>        }<br>        $this-&gt;dieOnError = $dieOnError;<br>        Vtiger_Cache::set('checkExistTable', $tableName, $tablePresent);<br><br>        return $tablePresent;<br>    }<br><br>    // Function to get the last insert id based on the type of database<br>    public function getLastInsertID()<br>    {<br>        $lastInsertID = $this-&gt;database-&gt;lastInsertId();<br><br>        return $lastInsertID;<br>    }<br><br>    public function formatDate($datetime, $strip_quotes = false)<br>    {<br>        // remove single quotes to use the date as parameter for Prepared statement<br>        if ($strip_quotes === true) {<br>            return trim($datetime, "'");<br>        }<br>        return $datetime;<br>    }<br><br>    public function getOne($sql, $dieOnError = false, $msg = '')<br>    {<br>        $result = $this-&gt;query($sql, $dieOnError, $msg);<br>        $val = $this-&gt;getSingleValue($result);<br><br>        return $val;<br>    }<br><br>    public function getFieldsDefinition(PDOStatement $result)<br>    {<br>        $fieldArray = [];<br>        if (!isset($result) || empty($result)) {<br>            return 0;<br>        }<br>        foreach (range(0, $result-&gt;columnCount() - 1) as $columnIndex) {<br>            $meta = $result-&gt;getColumnMeta($columnIndex);<br>            $column = new stdClass();<br>            $column-&gt;name = $meta['name'];<br>            $column-&gt;type = $this-&gt;types[$meta['pdo_type']];<br>            $column-&gt;max_length = $meta['len'];<br>            array_push($fieldArray, $column);<br>        }<br>        return $fieldArray;<br>    }<br><br>    public function getFieldsArray(PDOStatement $result)<br>    {<br>        $fieldArray = [];<br>        if (!isset($result) || empty($result)) {<br>            return 0;<br>        }<br>        foreach (range(0, $result-&gt;columnCount() - 1) as $columnIndex) {<br>            $meta = $result-&gt;getColumnMeta($columnIndex);<br>            array_push($fieldArray, $meta['name']);<br>        }<br>        return $fieldArray;<br>    }<br><br>    /**<br>     * Function to generate question marks for a given list of items.<br>     */<br>    public function generateQuestionMarks($items)<br>    {<br>        // array_map will call the function specified in the first parameter for every element of the list in second parameter<br>        return implode(',', array_map(function ($a) {<br>            return '?';<br>        }, is_array($items) ? $items : explode(',', $items)));<br>    }<br><br>    public function concat($columns, $space = '" "')<br>    {<br>        $concat = 'CONCAT(';<br>        foreach ($columns as $key =&gt; $column) {<br>            if ($key != 0 &amp;&amp; $space) {<br>                $concat .= $space . ',';<br>            }<br>            $concat .= $column . ',';<br>        }<br>        return rtrim($concat, ',') . ')';<br>    }<br><br>    // create an IN expression from an array/list<br>    public function sqlExprDatalist($array)<br>    {<br>        if (!is_array($array)) {<br>            \App\Log::error('sqlExprDatalist: not an array');<br>            $this-&gt;checkError('sqlExprDatalist: not an array');<br>        }<br>        if (!count($array)) {<br>            \App\Log::error('sqlExprDatalist: empty arrays not allowed');<br>            $this-&gt;checkError('sqlExprDatalist: empty arrays not allowed');<br>        }<br>        foreach ($array as $key =&gt; $val) {<br>            $l .= ($l ? ',' : '') . $this-&gt;quote($val);<br>        }<br>        return ' ( ' . $l . ' ) ';<br>    }<br><br>    public function getAffectedRowCount(PDOStatement $result)<br>    {<br>        $rows = $result-&gt;rowCount();<br><br>        return $rows;<br>    }<br><br>    public function requirePsSingleResult($sql, $params, $dieOnError = false, $msg = '')<br>    {<br>        $result = $this-&gt;pquery($sql, $params, $dieOnError, $msg);<br><br>        if ($this-&gt;getRowCount($result) == 1) {<br>            return $result;<br>        }<br>        \App\Log::error('Rows Returned:' . $this-&gt;getRowCount($result) . ' More than 1 row returned for ' . $sql);<br>        $this-&gt;checkError('Rows Returned:' . $this-&gt;getRowCount($result) . ' More than 1 row returned for ' . $sql, $dieOnError);<br><br>        return '';<br>    }<br><br>    public function columnMeta(PDOStatement $result, $col)<br>    {<br>        $meta = $result-&gt;getColumnMeta($col);<br>        $column = new stdClass();<br>        $column-&gt;name = $meta['name'];<br>        $column-&gt;type = $this-&gt;types[$meta['pdo_type']];<br>        $column-&gt;max_length = $meta['len'];<br><br>        return $column;<br>    }<br><br>    public function quote($input, $quote = true, $type = null)<br>    {<br>        // handle int directly for better performance<br>        if ($type == 'integer' || $type == 'int') {<br>            return (int) $input;<br>        }<br><br>        if (is_null($input)) {<br>            return 'NULL';<br>        }<br><br>        $map = [<br>            'bool' =&gt; PDO::PARAM_BOOL,<br>            'integer' =&gt; PDO::PARAM_INT,<br>        ];<br><br>    <span style="background-color:#f1c40f;">    $type = $map[$type] ?? PDO::PARAM_STR;</span><br><br>        if ($quote) {<br>            return strtr($this-&gt;database-&gt;quote($input, $type), [self::DEFAULT_QUOTE =&gt; self::DEFAULT_QUOTE . self::DEFAULT_QUOTE]);<br>        } else {<br>            return self::DEFAULT_QUOTE . $input . self::DEFAULT_QUOTE;<br>        }<br>    }<br><br>    // SQLTime logging<br><br>    protected $logSqlTimeID = false;<br>    protected $logSqlTimeGroup = 1;<br><br>    public function logSqlTime($startat, $endat, $sql, $params = false)<br>    {<br>        if (!AppConfig::performance('SQL_LOG_INCLUDE_CALLER')) {<br>            return;<br>        }<br>        $db = self::getInstance('log');<br>        $now = date('Y-m-d H:i:s');<br>        $group = $this-&gt;logSqlTimeGroup;<br>        $logTable = 'l_yf_sqltime';<br>        $logQuery = 'INSERT INTO ' . $logTable . '(`id`, `type`, `qtime`, `content`, `date`, `group`) VALUES (?,?,?,?,?,?)';<br><br>        if ($this-&gt;logSqlTimeID === false) {<br>            $stmt = $db-&gt;database-&gt;query(sprintf('SELECT MAX(id) FROM %s', $logTable));<br>            $this-&gt;logSqlTimeID = (int) $this-&gt;getSingleValue($stmt) + 1;<br><br>            $type = PHP_SAPI;<br>            $data = '';<br>            if (isset($_SERVER['REQUEST_METHOD'])) {<br>                $uri = $_SERVER['REQUEST_URI'];<br>                $qmarkIndex = strpos($_SERVER['REQUEST_URI'], '?');<br>                if ($qmarkIndex !== false) {<br>                    $uri = substr($uri, 0, $qmarkIndex);<br>                }<br>                $data = $uri . '?' . http_build_query($_SERVER['REQUEST_METHOD'] == 'GET' ? $_GET : $_POST);<br>            }<br>            $stmt = $db-&gt;database-&gt;prepare($logQuery);<br>            $stmt-&gt;execute([$this-&gt;logSqlTimeID, $type, null, $data, $now, $group]);<br>        }<br><br>        $type = 'SQL';<br>        $data = trim($sql);<br>        if (is_array($params) &amp;&amp; !empty($params)) {<br>            $data .= '[' . implode(',', $params) . ']';<br>        }<br>        $qtime = round(($endat - $startat) * 1000) / 1000;<br>        $stmt = $db-&gt;database-&gt;prepare($logQuery);<br>        $stmt-&gt;execute([$this-&gt;logSqlTimeID, $type, $qtime, $data, $now, $group]);<br><br>        $type = 'CALLERS';<br>        $data = [];<br>        $callers = debug_backtrace();<br>        for ($calleridx = 0, $callerscount = count($callers); $calleridx &lt; $callerscount; ++$calleridx) {<br>            if ($calleridx == 0) {<br>                continue;<br>            }<br>            if ($calleridx &lt; $callerscount) {<br>                $callerfunc = $callers[$calleridx + 1]['function'];<br>                if (isset($callers[$calleridx + 1]['args'])) {<br>                    $args = '';<br>                    foreach ($callers[$calleridx + 1]['args'] as &amp;$arg) {<br>                        if (!is_array($arg) &amp;&amp; !is_object($arg) &amp;&amp; !is_resource($arg)) {<br>                            $args .= "'$arg'";<br>                        }<br>                        $args .= ',';<br>                    }<br>                    $args = rtrim($args, ',');<br>                }<br>                if (!empty($callerfunc)) {<br>                    $callerfunc = " ($callerfunc)";<br>                }<br>                if (!empty($args)) {<br>                    $callerfunc .= "[$args] ";<br>                }<br>            }<br>            $data[] = 'CALLER: (' . $callers[$calleridx]['line'] . ') ' . $callers[$calleridx]['file'] . $callerfunc;<br>        }<br>        $stmt = $db-&gt;database-&gt;prepare($logQuery);<br>        $stmt-&gt;execute([$this-&gt;logSqlTimeID, $type, null, implode(PHP_EOL, $data), $now, $group]);<br>        ++$this-&gt;logSqlTimeGroup;<br>    }<br><br>    public static function whereEquals($val)<br>    {<br>        if (is_array($val)) {<br>            if (count($val) &gt; 1) {<br>                return 'IN (\'' . implode("','", $val) . '\')';<br>            } else {<br>                $val = array_shift($val);<br>            }<br>        }<br>        return '=\'' . $val . '\'';<br>    }<br>}<br><br><br><hr>Generated by YetiforceCRM ver. 4.4.0<br>PHP: 7.1.17<br><br><strong>Server configuration errors:</strong><br>session.gc_maxlifetime: 1440<br>auto_detect_line_endings: Off<br><strong>Library errors:</strong><br>exif_read_data<br>ldap_connect<br>opcache_get_configuration<br>apcu<br>

**Comment by mariuszkrzaczkowski** [comment]
As a file to report issue 8409
