### ISSUE TITLE
When updating, it gives an error.

### ISSUE THREAD

**Issue by ipanchenko1990** [YetiForceCompany/YetiForceCRM#8429]
When updating, it gives an error.

YetiForce Version used: 4.4.48
Browser name and version: Google Chrome 69.0.3497.100
Operating System and version: Windows 10
![001](https://user-images.githubusercontent.com/35902241/47616758-1da2dc80-dad2-11e8-99e6-0bb8560c27ac.PNG)

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/47358835-463e6700-d6cb-11e8-9d0f-953a67a3e86b.jpg)
