### ISSUE TITLE
organizations - invoices tab empty

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#843]
the invoices tab on the organization card is empty
so even though invoices has been issued to a company no invoice are showed here:

/index.php?module=Accounts&relatedModule=Invoice&view=Detail&record=144&mode=showRelatedList&tab_label=Invoice

**Comment by bpabiszczak** [comment]
This error does not occur in the last version.
You can test it here: http://www.ak.dev.opensaas.pl/yeti2.0.74 l: admin , h: dBHec0de

**Comment by lalord** [comment]
ok,
