### ISSUE TITLE
How I upgrade the version from 4.4.0 to 4.4.48?

### ISSUE THREAD

**Issue by brenomachado67** [YetiForceCompany/YetiForceCRM#8443]
Hi,

How I upgrade the version from 4.4.0 to 4.4.48? 

P.s: sorry for open a pull request about this question.

**Comment by vovpff** [comment]
@brenomachado67 https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%204.x.x/4.4.0_to_5.0.0
but in future you can't update from 4..4.48 to newer versions!
This update only for testing current developers version.
