### ISSUE TITLE
Logic behind sales order => Recurring invoice

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#845]
Questions from Jack:

Can one you try to help describe the logic begind "Recurring invoice".
(would be good to know how system is based).
I have a yeti 1.4 that created recurring daily even though 
 
Lets say I create a sales order with recurring start period 2015-05-21 monthly.
(tomorrow)
 
1. I would expect the system to generate an invoice tomorrow. OK
 
2. What happens if data was set to yesterday? will it then generate invoice next time cron runs?
 
3. what happens if I create a manual invoice from same sales order - will it take over the coming recurring invoice?
 
4. what happens if I change the start date?
 
5. basicly, is there a count somewhere so system knows how many invoices it should have created after 6 moths (for montly recurring)? And how does the system react when dates are changed?
 
6. why are recurring end date and payment date related or has a validation on creation/save?
(End period should be less than or equal to payment date) makes no sense to me.
 
7. how do I make sure that all recurring generated invoices are set with correct payment date? 
 
 
would be good with some clarification on this subject...
 
:)

**Comment by ChristopheLux** [comment]
Hello
for information vtiger release in the commercial version the management of subscription with the management of the recurring invoice https://blogs.vtiger.com/?p=2760

**Comment by bpabiszczak** [comment]
The operational logic of the product modules and automatic invoice generating will be completely changed in 2.2/2.3 version. Then we'll release a manual for that mechanism.
Some of the questions require code analysis, because it wasn't us who wrote it . I'm closing this issue, if there are any comments about the new mechanism open a new issue please.
