### ISSUE TITLE
Multi PDF generation

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8474]
#### Issue

If more than one of PDF types for record checked then error appears

![multi pdf](https://user-images.githubusercontent.com/8545791/47909344-b190f180-dea0-11e8-8d6d-3762b0281f92.gif)

#### Your Environment

* YetiForce Version used: dev 4.4.55
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by thesxw** [comment]
My personal fix to checkboxes in export to PDF
Function on clicked checkbox
`function() {
  $(".checkbox").attr("checked", false); //uncheck all checkboxes
  $(this).attr("checked", true); //check the clicked one
}`
They forgot to made function who disables other checked PDF templates I will put it in my repositories after i found full code in my yetibetty

**Comment by thesxw** [comment]
psttt just uploaded it here is ur fix
https://github.com/thesxw/Yetiforce-specials/blob/master/Fix%20Export%20to%20PDF.php

**Comment by vovpff** [comment]
@thesxw Thanks! But this is temporary solution. Dev crew must fix this bug

**Comment by thesxw** [comment]
@vovpff  putting this code fixing the issue so ;) it just disallow users to check 2 boxes but we can also make that non of them will be selected at the start so user need to choose one
