### ISSUE TITLE
Invoice period of service

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#8475]
Yetiforce 4.4.0

Can any one explain me how add period of service i provide for client.

Example i provide serivice from 01/10/2018 to 31/10/2018

**Comment by bpabiszczak** [comment]
My używamy do tego modułu umowy SLA, wprowadzamy tam obie daty a następnie wrzuciliśmy sobie widżet, który pokazuje nam, jakie usługi wygasają w przeciągu 30 dni.
