### ISSUE TITLE
Invoice Nr - question

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#8476]
YetiForce 4.4.0
I make test invoice but then i deleted from system. When i make new one number of invoice is not 1 but next example 5. How to delete that from system ?

**Comment by vovpff** [comment]
@mskoczek standard invoice number is autoincrement number. Every record in invoice module has this unique number. If you need to specify number you can add field what would be your number.

**Comment by mskoczek** [comment]
I am aware of that i want that Yeti generate nr of invocie i just want remowe the test nr invoice what i was use.

**Comment by vovpff** [comment]
@i think you can change prefix or record and start from 1

**Comment by mskoczek** [comment]
But how ? :)

**Comment by mskoczek** [comment]
Ok a manage finde where to start prefix in invoice but i have message 

LBL_PREFIX_IN_USE

**Comment by vovpff** [comment]
You need to change prefix

**Comment by mskoczek** [comment]
I did it was 5 and i put 1. Then i try save after presing save i have that info LBL_PREFIX_IN_USE
I remove old test invoice.

**Comment by mskoczek** [comment]
Ok i will do Thank You

**Comment by thesxw** [comment]
HERE U GO u need to enter your PHPMyAdmin
log into it and search in ur database for table named similar to this "vtiger_modentity_num"
you can determinate which you want to reverse by tabid or prefix (row) then just change this number to number u want
![database check](https://user-images.githubusercontent.com/33422088/48400965-1ad9f580-e728-11e8-87b9-fbb36dd5a50e.jpg)
