### ISSUE TITLE
Invoice Prefix Bug ?

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#8478]
Hi. 
I made 4 test invoice and then i remove them from system. But system stil think that prefix is in use.
I manage finde place where to change prefix and i put 1 when i pres save i have that message:

LBL_PREFIX_IN_USE

YetiForce 4.4.0

**Comment by vovpff** [comment]
To start from 1 yu need to change prefix at all!

**Comment by vovpff** [comment]
@mskoczek I can't trigger this on gitdev and my local systems. Pls make video

**Comment by mskoczek** [comment]
It look like that
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40525437/47987539-a673d680-e0d7-11e8-84eb-1fec9a7c61dc.gif)

**Comment by vovpff** [comment]
Looks starnge. Your server config is correct?

**Comment by mskoczek** [comment]
Yes if you notice it is on yetiforce.eu domain.

**Comment by paula-w** [comment]
@mskoczek dziękujemy za zgłoszenie, proszę pamiętać, że dla naszych klientów chmurowych mamy maila sla@yetiforce.com. Następnym razem błędy prosimy zgłaszać tam, zostaną rozwiązane priorytetowo.

**Comment by bpabiszczak** [comment]
@mskoczek o ile wiem, problem jest już rozwiązany, jeżeli jednak coś nadal jest nie tak, proszę napisz do mnie maila bezpośrednio lub na SLA@yetiforce.com to się tym zajmiemy.

**Comment by SunnieG** [comment]
how did this get solved? I am having the exact same issue
