### ISSUE TITLE
Translation logics

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8482]
#### Issue

Every my new widget from filter or field has name like `WFILT_MODULE_FILTERNAME` or `LBL-FIELDNAME`. For multilingual system I use this names to prepare translation. Now I has no english users and newer add english translations.

For translation to russian I add translation to current module translation list. But from admin (english language GUI) I can't see translation because they are empty. 

![image](https://user-images.githubusercontent.com/8545791/47987109-bd262780-e0ef-11e8-97d1-b893772f994d.png)

^name invisible because empty for `en_us` langpack

In past version (4.3) there are appears original label if string translation for language empty. If field added with correct label like `Payment status` and this string missed for `en_us` lang but available for `ru_ru` than english users can't see this field label.
#### Your Environment

* YetiForce Version used: Local 4.4.0, gitdev 4.4.57
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by adudekyeti** [comment]
If you add a new translation for your language and you don't add it in all the other languages then in the other ones you will see an untranslated label.

**Widget settings (French):**
![translation-1](https://user-images.githubusercontent.com/39482453/49010979-24764b00-f175-11e8-8591-25578ee042e3.PNG)

**French language settings:**
![translation-2](https://user-images.githubusercontent.com/39482453/49010974-217b5a80-f175-11e8-87f6-be2e3055edb4.PNG)

**Widget settings (English):**
![translation-3](https://user-images.githubusercontent.com/39482453/49010938-09a3d680-f175-11e8-91b3-5ee0ded8d374.PNG)
If you add an empty translation of a phrase to other languages then no translations or labels will be displayed.
