### ISSUE TITLE
Is there a way to import pdf page from pdf file ?

### ISSUE THREAD

**Issue by thesxw** [YetiForceCompany/YetiForceCRM#8485]
Hello 
i got a question how i could export a 1 page from pdf into PDFTemplate from existing pdf file

im trying to use 
`$this->pdf->SetImportUse();
$pagecount = $this->pdf->SetSourceFile(ROOT_DIRECTORY.'/_bar/test.pdf');
$import_page = $this->pdf->ImportPage($pagecount);
//$this->pdf->SetPageTemplate($import_page);//notwork
//$this->pdf->SetDocTemplate($import_page, true);//notwork
$test = $this->pdf->UseTemplate($import_page);
$this->print_error(ROOT_DIRECTORY.'/_bar/test.pdf');
$this->pdf->WriteHTML("test");
$this->pdf->Output();`

but it returns No Template or no pages returns in Yeti errors

anyway in libraries mpdf.php file i include some files to be sure its not fault of no libraries

```
require_once _MPDF_PATH . 'mpdfi/filters/FilterASCII85.php'; //
 require_once _MPDF_PATH . 'mpdfi/filters/FilterLZW.php'; //
 require_once _MPDF_PATH . 'FPDI-lib/src/autoload.php'; //
 require_once _MPDF_PATH . 'mpdfi/pdf_parser.php'; //
 require_once _MPDF_PATH . 'mpdfi/pdf_context.php'; //
 require_once _MPDF_PATH . 'mpdfi/fpdi_pdf_parser.php'; //

 require_once _MPDF_PATH . 'src/TCPDF-lib/tcpdf.php';
require_once _MPDF_PATH . 'FPDI-lib/src/FpdfTplTrait.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/FpdiTrait.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/Tcpdf/Fpdi.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/TcpdfFpdi.php'; //
require_once _MPDF_PATH . 'MoreLibs/fpdf17/fpdf.php';
require_once _MPDF_PATH . 'FPDI-lib/src/FpdfTpl.php';
require_once _MPDF_PATH . 'FPDI-lib/src/Fpdi.php';
require_once _MPDF_PATH . 'FPDI-lib/src/FpdiException.php'; //

require_once _MPDF_PATH . 'FPDI-lib/src/PdfParser/PdfParser.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/PdfParser/PdfParserException.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/PdfParser/StreamReader.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/PdfParser/Tokenizer.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/PdfParser/Type/PdfType.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/PdfParser/Type/PdfTypeException.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/PdfParser/Type/PdfArray.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/PdfParser/Type/PdfBoolean.php'; //
require_once _MPDF_PATH . 'FPDI-lib/src/PdfParser/Type/PdfDictionary.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Type/PdfHexString.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Type/PdfIndirectObject.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Type/PdfIndirectObjectReference.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Type/PdfName.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Type/PdfNull.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Type/PdfNumeric.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Type/PdfStream.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Type/PdfString.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Type/PdfToken.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Filter/FilterInterface.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Filter/FilterException.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Filter/Flate.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Filter/FlateException.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Filter/Lzw.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Filter/LzwException.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Filter/Ascii85.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Filter/Ascii85Exception.php'; //
require_once _MPDF_PATH . 'src/PdfParser/Filter/AsciiHex.php'; //
require_once _MPDF_PATH . 'src/PdfParser/CrossReference/ReaderInterface.php'; //
require_once _MPDF_PATH . 'src/PdfParser/CrossReference/AbstractReader.php'; //
require_once _MPDF_PATH . 'src/PdfParser/CrossReference/CrossReference.php'; //
require_once _MPDF_PATH . 'src/PdfParser/CrossReference/CrossReferenceException.php'; //
require_once _MPDF_PATH . 'src/PdfParser/CrossReference/FixedReader.php'; //
require_once _MPDF_PATH . 'src/PdfParser/CrossReference/LineReader.php'; //
````

im just put everything there to be sure its not this issue

any ideas ?

**Comment by vovpff** [comment]
@thesxw you need to make PDF template manualy trough admin panel.

**Comment by thesxw** [comment]
@vovpff i need to go like this in mPDF.php ... 
and check $this-html to find my values i want to search but its still ... writed

`$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage2);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage3);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage4);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage5);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage6);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage7);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage8);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage9);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage10);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage11);
$this->pdf->AddPage();
$this->pdf->WriteHTML($FrontPage12);`

**Comment by vovpff** [comment]
@vovpff I\m little bit confised

**Comment by thesxw** [comment]
@vovpff i just want to do this for specified module, specified template and specified product i choose from product list

is there a way to import PDF page from existing PDF in this YF ? or what libraries i should use to achive that

**Comment by vovpff** [comment]
@thesxw you need to build your own template by PDF edition tool https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35 what included to YF.
There are no ability to build template from PDF file because PDF format can be used for storing documents not for storing templates.

**Comment by bpabiszczak** [comment]
We're finishing creating a new PDF library: https://github.com/YetiForceCompany/YetiForcePDF
