### ISSUE TITLE
Błąd "Ta strona nie działa" już po instalacji

### ISSUE THREAD

**Issue by McTommy007** [YetiForceCompany/YetiForceCRM#8491]
Cześć,
Po zainstalowaniu, oprogramowanie działa.
Dopiero kiedy próbuję zapisać kontrahenta, kontakt wyświetla mi się ten błąd.
Ale żeby było weselej, rekord jest zapisany.
Odświeżanie tej strony nic nie daje. Muszę od nowa wchodzić na główną.
Czy zna ktoś może powód tego błędu?

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/47999955-67a84580-e104-11e8-8689-86bf07fb988e.jpg)

**Comment by bpabiszczak** [comment]
Można tutaj, ale bez podstawowych informacji nie ma jak pomóc.

**Comment by McTommy007** [comment]
Cześć,
Po zainstalowaniu, oprogramowanie działa.
Dopiero kiedy próbuję zapisać kontrahenta, kontakt wyświetla mi się ten błąd.
Także w innych przypadkach strona się wyłącza.
Ale żeby było weselej, rekord jest zapisany.
Odświeżanie tej strony nic nie daje. Muszę od nowa wchodzić na główną.
Czy zna ktoś może powód tego błędu?
Oprogramowanie jest na hostingu MyDevil.net
Mój komputer ma Win10 64 Pro.
Przyznam się też że nie do końca wiem jak zmienić ustawienia bezpieczeństwa w Yeti. To znaczy gdzie w jakich plikach. Załączam błędy systemowe
![strona](https://user-images.githubusercontent.com/44274278/48051076-63336980-e1a4-11e8-9e98-ecbf65d91e23.jpg)
![bledy-1](https://user-images.githubusercontent.com/44274278/48051182-b1486d00-e1a4-11e8-9386-c646de1c50b5.jpg)
![bledy-2](https://user-images.githubusercontent.com/44274278/48051185-b5748a80-e1a4-11e8-9d37-79df3db59cfe.jpg)

**Comment by bpabiszczak** [comment]
To jest tylko mały wycinek wszystkich parametrów z konfiguracji, proszę wkleić całość i proszę przesłać logi [github@yetiforce.com].

**Comment by McTommy007** [comment]
Cały raport:

Konfiguracja bezpieczeństwa systemu
--
|zalecana konfiguracja | Wartość obecna

display_errors | Wyłączony | Wyłączony
HTTPS | Włączony | Wyłączony
.htaccess | Włączony | Wyłączony
public_html | Włączony | Wyłączony
session.use_strict_mode | Włączony | Wyłączony
session.use_trans_sid | Wyłączony | Wyłączony
session.cookie_httponly | Włączony | Włączony
session.use_only_cookies | Włączony | Włączony
expose_php | Wyłączony | Włączony
Header: X-Frame-Options | SAMEORIGIN | sameorigin
Header: X-XSS-Protection | 1; mode=block | 1; mode=block
Header: X-Content-Type-Options | nosniff | nosniff
Header: X-Robots-Tag | none | none
Header: X-Permitted-Cross-Domain-Policies | none | none
Header: X-Powered-By |   |  
Header: Server |   | nginx
Header: Expect-CT | enforce; max-age=3600 | enforce; max-age=3600
Header: Referrer-Policy | no-referrer | no-referrer
Header: Strict-Transport-Security | max-age=31536000; includeSubDomains; preload | max-age=31536000; includesubdomains; preload
session_regenerate_id | Włączony | Włączony

[2018-11-05.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2552343/2018-11-05.log)
dziękuję
Tomasz

**Comment by mariuszkrzaczkowski** [comment]
![strona](https://public.yetiforce.com/gallery/uploads/big/ceb2f2109e99a7690dcdf916e14652eb.jpg)

**Comment by McTommy007** [comment]
ups

**Comment by McTommy007** [comment]
Ale ja tego nie mam ☹
[cid:image001.png@01D475B9.B8921D10]

**Comment by McTommy007** [comment]
Załączam pełną konfigurację.
![yetiforce_settings](https://user-images.githubusercontent.com/44274278/48055136-23be4a80-e1af-11e8-828c-09584bc067f4.png)

**Comment by McTommy007** [comment]
A mogę poprosić o zdjęcie ignorka?
