### ISSUE TITLE
Brak dostępu do systemu

### ISSUE THREAD

**Issue by Irmina8591** [YetiForceCompany/YetiForceCRM#8500]
Yetiforce 4.4 stable

Witam w wyniku zabezpieczenia moje hasło do systemu (jako jedynego admina) straciło ważność, nie mogę się zalogować, Gdzie zmienić hasło / parametry aby dostać się do systemu.

**Comment by mariuszkrzaczkowski** [comment]
Jeśli skonfigurowano SMTP to można włączyć opcję resetu na stronie logowania::
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/security.php#L12
Jeśli nie to można skryptem:
https://github.com/YetiForceCompany/YetiForceScripts/tree/master/PasswordReset

**Comment by Irmina8591** [comment]
:D dziękuję działa

**Comment by bpabiszczak** [comment]
Super, @Irmina8591 jak możesz napisz opinię produktu tutaj: https://www.g2crowd.com/products/yetiforce-sp-z-o-o-yetiforce-crm/reviews potrzebujemy tego aby nas wyróżniono :]
