### ISSUE TITLE
CRM mini na bazie Yeti

### ISSUE THREAD

**Issue by McTommy007** [YetiForceCompany/YetiForceCRM#8502]
Cześć,
Zajmuję się sprzedażą od prawie dwudziestu lat. Wdrażałem od strony biznesowej kilka razy CRM. W większości były to produkty przygotowywane pod firmę. 
Oglądam z uwagą Yeti i mam pewne obawy co do kierunku rozwoju projektu. W porównaniu do Sugara sprzed powiedzmy 10 lat to jest tak jakby porównywać windę 3.11 do 10.
Rozumiem że wersja musi być jak najszersza aby klient wybrał sobie to co chce. 
Ja sam szukałem dość długo CRM-a dla siebie. I prawdę mówiąc znalazłem ale za 120 zł miesięcznie. I to też moloch, z którego korzystałbym może w 15%. 
I tutaj pojawia się mój pomysł. Jeżeli chcecie mógłbym napisać wam funkcjonalność prostego CRM-a dla naprawdę dużej grupy docelowej. Pracowałem w wielu branżach i doskonale wiem co jest a co nie jest potrzebne. Żaden z polskich systemów w wersjach SaaS nie spełnia tych wymagań. A jak ktoś zainstaluje Yeti to w pierwszym momencie jest przerażony ilością funkcji i rezygnuje.
Co o tym szanowni Państwo myślicie?
pozdrawiam
Tomasz

**Comment by bpabiszczak** [comment]
Przejdźmy na TY, tak będzie prościej :] 
Niestety nie podałeś żadnego przykładu co byś chciał zmienić, a więc ciężko się do tego odnieść. Wyłączenie 95% modułów i zrobienie wersji "lite" systemu, to kwestia 30 min i każdy zawsze może tak zrobić, przy czym takim "Lite" systemów są setki na świecie, więc pytanie, gdzie byłaby tu nasza przewaga.

**Comment by McTommy007** [comment]
Cześć Błażej,
Tak jest lepiej.
Zróbmy tak. Ja jestem teraz trochę zabiegany (a Yetiforce mi nie działa 😊)
Daj mi proszę kilka dni a stworzę coś czego tak naprawdę na rynku nie ma.
Wtedy pomyślimy czy coś takiego da się zrobić na podstawie Sugara czy też nie. Wydaje mi się że tak.
Zrobię też parę layoutów. Niestety w Corelu więc będą paskudne ale chodzi o wizualizację.
Systemów na świecie w istocie są setki ale większość jest tworzona przez programistów bez udziału biznesu więc w przeważającej większości to unusuall poo. 😊
Ale może uda się zrobić coś fajnego. W Polsce potencjalnych użytkowników jest przynajmniej 350 tysięcy.
Pozdrawiam
Tomek

**Comment by bpabiszczak** [comment]
możemy Tobie uruchomić CRM u nas w chmurze, bezpłatnie do końca roku, potem możesz cały system przenieść albo do siebie albo zostać u nas [sam decydujesz]...

mamy tysiące pomysłów... ot chociażby można wzorować się na nich: https://monday.com, tylko kto to wszystko zrobi ;)

**Comment by McTommy007** [comment]
Dzięki,
Jeśli to rozwiąże moje problemy to chętnie a jak potem będę mógł przenieść moje dane na „nowy” to jeszcze lepiej.
Jutro zapoznam się z Monday.com
Co do założeń to ja zawsze w pracy stosowałem semantykę KISS (keep it simple stupid). Powstała w latach 60-tych w USA. Wiele koncernów to olewało a IT w szczególności. I zagłaskanie króliczka stało się faktem.
Może razem stworzymy coś fajnego?
Ja pracowałem dla wielu firm: International Paper, PPWK, Sofidel, C.H.Beck, Infor PL, Gadu-Gadu.
Zawsze sprzedaż i zawsze kurczę CRMy.
Doceniłem to rozwiązanie dopiero w 2005 roku ale potem już „poszło”.
Zawsze miałem CRM-a
Pozdrawiam
Tomasz
P.S. Mój pierwszy CRM zrobiła firma Organix z Poznania. Po moich zmianach i uwagach zaczęła go w mojej wersji sprzedawać jako swój „osobisty” projekt i działało to przez wiele lat. Więc moje doświadczenie coś dało. 😊

**Comment by bpabiszczak** [comment]
a wiesz, że to co piszesz jest na Github, bo pewnie odpowiadasz na powiadomienie w mailu ;) Jak mamy utworzyć crm w chmurze, to prześlij proszę na info@yetiforce.com dane firmy i jutro Tobie zainstalujemy system i damy dostępy.

**Comment by McTommy007** [comment]
Holly Molly
OK
Dzięki za info 😊

**Comment by Pietrox** [comment]
O jaka fajna konwersacja ;)
My korzystamy z Yeti od dwóch lat dla call center i retencji.
Praktycznie wersja mini do call center i podstawy BI to największa grupa odbiorców z zachodu. Wystarczy wywalić całą logikę typowego ERP (czasem jak patrzę to jakbym widział CDN XL bez modułu produkcji) i zostawić leads (rejestracje) conversion -> accounts. My już i tak dużo pozmienialiśmy w systemie i teraz męczymy się z przejściem na 4.4 ;)
Jakbyście chcieli robić mini wersje płatną w swoim cloudzie i dockerować instancje to mogłoby dać radę, lub per user.
vTiger płatny trzepie niezłą kasę na tym.

**Comment by bpabiszczak** [comment]
Zawsze można wyłączyć nadmiarowe funkcjonalności :] Nie planujemy wydawać dwóch różnych wersji systemu. Fajnie słyszeć, że używasz system, jeżeli to nie jest dla Ciebie problem @Pietrox to daj nam w tych dwóch miejscach rekomendacje: 

1. https://www.g2crowd.com/products/yetiforce-sp-z-o-o-yetiforce-crm/reviews 
2. https://www.capterra.com/p/159123/Yetiforce/ 

to nam bardzo pomaga w promocji produktu, a to dla nas ważne, bo produkt jest bezpłatny i od jego promocji zależy jak bardzo rozwijamy produkt.

**Comment by epsilonsc** [comment]
Witaj @Pietrox a masz spiętego Yeti z jakimś Asteriskiem ? w call center.

**Comment by bpabiszczak** [comment]
Kusi nas ten asterisk :P

**Comment by Pietrox** [comment]
Chętnie dam review w wolnej chwili ;)

@epsilonsc Mieliśmy na około. W list view templatce dodawaliśmy id= i nazwe pola - w primary phone wrzucaliśmy do jquery skrypt na init call i stop call, na stop call insert do tabeli modułu call history i do crmentity. Po przejściu na 4.3 zrezygnowaliśmy z tego, bo reintegracja zajęłaby dużo czasu i teraz używamy własnego API do manipulowania CRM. 

Dla call center się nie obejdzie bez jednego Backenda - customizacja tego CRM jest na prawdę ciężka i sam system nie ma litości dla błędów, raz obiekt raz strukturalnie i tak w kółko. Pozostałości po vTiger.
Ale co nowsza wersja to widać że refaktor idzie. Nawet npm się pojawił śladowo ;)

**Comment by mariuszkrzaczkowski** [comment]
> Nawet npm się pojawił śladowo ;)

nie npm tylko yarn :)

**Comment by Pietrox** [comment]
Ooo to jeszcze lepiej, my dopiero przeklikujemy nową wersję więc dużo nie wiemy.
A ogólnie będziecie odchodzić od jQuery?

**Comment by bpabiszczak** [comment]
a jQuery ma jakąś konkretną wadę?

**Comment by Pietrox** [comment]
Młodzi front-endzi i ich zatrudnianie pod to :/ Niechętnie przychodzą.
Rekrutacje pod naszą apke Angularową idą lepiej jak pod jQuery.

**Comment by bpabiszczak** [comment]
Bo to zatrudnia się JavaScriptowc-a a to czy on przy okazji grzebie w jQuery czy Angular nie powinno mieć większego znaczenia. Są to dwa niezależne elementy które stanowią niewielki % tego co programista JavaScript powinien znać.

**Comment by Pietrox** [comment]
Ja się nie kłócę ;) Przypominam że napisałem "Młodzi" - nic tylko by chcieli Angular, React albo Vue.

**Comment by bpabiszczak** [comment]
i słusznie :P Niech się uczą

**Comment by McTommy007** [comment]
Niestety odpuszczam Yetiforce z open source-a. Mam hosting w mydevil.net i do tej pory mi nie działa. Podczas zapisywania wyskakuje mi że strona nie działa. A ostatecznie rekord się zapisał. Nie mogę skonfigurować poczty.
Kurcze, czy to nie mogłoby działać jak stary Sugar? Bez wodotrysków ale w podstawowej funkcjonalności?
Może znajdę coś innego.
Niemniej pracuję nad opisem funkcjonalności CRM lite/mini czy jak ja go nazwałem CRM Blank page.
Chłopaki. Im więcej dodajecie tym na mniejszej liczbie maszyn to działa. Nie macie Boga w sercu.
Open source jest nie tylko dla profesjonalistów ale też dla takich lamerów jak ja. Potrafię założyć bazę, zainstalować na serwerze czy zrobić jeszcze parę innych rzeczy. Ale nie wszystko.

**Comment by bpabiszczak** [comment]
Nie wiem o jakich problemach mówisz, bo nie zostały one zgłoszone [chyba]. 
Możesz dostać system w naszej chmurze do końca roku bezpłatnie [a potem możesz wziąć kopię i przenieść do siebie na serwer]. 

Nie dziwię się hostingowi MyDevil że nie działa, ponieważ oferując usługę za 15 zł na miesiąc, muszą na jednym serwerze zmieścić setki klientów, ograniczać sztucznie serwer i nie świadczyć porządnego wsparcia.... a to jest system biznesowy, który wymaga co najmniej profesjonalnego podejścia do instalacji i konfiguracji aby mieć pewność, że system maksymalnie będzie chronił nasze dane. 

Jeżeli już na tym etapie masz problemy [instalacja i podstawowa konfiguracja], to proponuje naszą chmurę, gdzie za instalację i konfigurację my odpowiadamy, a dodatkowo świadczymy wsparcie na każdej warstwie.

**Comment by bpabiszczak** [comment]
Na pewno wszystkim nie dogodzimy, dla jednych za mało funkcji dla innych za dużo, innym kolory się podobają a jeszcze innym zupełnie nie :] W chmurze świadczymy wsparcie, jak jest za dużo funkcjonalności to w 30s wyłączyć 95% z nich :]
