### ISSUE TITLE
No images embedded in email templates

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#8504]
When I put an image in the email template, it does not show me that image when I send the emails. I tried to insert the html code in the email and neither. I have added the doomino in config.security.php and they do not see it either.<br><hr>Generado por YetiforceCRM ver. 4.4.0<br>PHP: 7.1.23<br><br><strong>Errores de configuración del servidor:</strong><br>error_reporting: E_ALL<br>output_buffering: 4096<br>default_socket_timeout: 60<br>memory_limit: 50 MB<br>max_input_vars: 1500<br>session.gc_maxlifetime: 1440<br>auto_detect_line_endings: Off<br>

**Comment by mariuszkrzaczkowski** [comment]
attach an example code or whole template if you can

**Comment by joelbcampos** [comment]
`<img alt="" src="https://crm.doomain.com/cache/images/image.jpg" style="float:left;width:143px;height:90px;"><br><br>
 <br><br><br><br><strong>$(general : CurrentDate)$<br><br>
Estimado cliente:<br><br><span style="font-size:14px;">$(record : company)$</span></strong><br>
 
<p style="margin:0cm 0cm 8pt;"><span style="font-size:16px;"><span style="line-height:107%;">Nos ponemos en contacto con usted para realizar una propuesta de ahorro energético en el suministro situado en </span>$(record : addresslevel8a)$<span style="line-height:107%;">, </span>$(record : buildingnumbera)$<span style="line-height:107%;"> </span>$(record : localnumbera)$<span style="line-height:107%;">, </span>$(record : addresslevel7a)$<span style="line-height:107%;">, </span>$(record : addresslevel5a)$<span style="line-height:107%;"> -</span>$(record : addresslevel2a)$<span style="line-height:107%;">.</span></span></p>

<p style="margin:0cm 0cm 8pt;"><span style="font-size:16px;"><span style="line-height:107%;">Según nuestros registros, su punto de suministro eléctrico tiene próximo su vencimiento de contrato, por ello, desde <span style="color:#c0392b;"><strong>AXPO IBERIA S.L</strong></span>, queremos realizar una propuesta de ahorro energético.</span></span></p>

<p style="margin:0cm 0cm 8pt;"><span style="font-size:16px;"><span style="line-height:107%;">A continuación, le mandamos una simulación de la facturación que hubiera tenido con nuestra compañía basándonos en los consumos registrados por la distribuidora el año anterior.</span></span></p>

<p style="margin:0cm 0cm 8pt;"><span style="font-size:16px;"><span style="line-height:107%;">Si lo desea también puede hacer llegarnos la factura <a href="mailto:nombre@doomain.com?subject=Adjunto%20factura&body=Adjunto%20factura%20para%20su%20an%C3%A1lisis."><span style="color:#e74c3c;">aquí</span></a>, con la finalidad de poder realizar una comparativa real frente a los precios de los que está disfrutando actualmente.</span><br><br><span class="value" style="white-space:normal;">El día <strong>$(record : fechaproximocontacto)$</strong> nos pondremos en contacto con usted para poder explicarles los beneficios de nuestra propuesta. </span> </span></p>

<p style="margin:0cm 0cm 8pt;"><span style="font-size:16px;"><span style="line-height:107%;"><span style="line-height:107%;"><span style="color:#333333;">Reciba un cordial saludo.</span></span></span></span></p>
 

<p style="margin-bottom:.0001pt;margin:0cm 0cm 10pt;"><span style="font-size:11pt;"><span style="line-height:normal;"><span><b><span><span style="font-size:20px;"><span style="color:rgb(225,0,25);"> </span></span><img alt="" height="63" src="https://crm.domain.com/cache/images/image.jpg" width="99"></span></b></span></span></span></p>

<p style="margin-bottom:.0001pt;margin:0cm 0cm 10pt;"><span style="font-size:11pt;"><span style="line-height:normal;"><span><b><span>Joel Campos<br><span style="color:#e10019;">Agente Colaborador</span></span></b></span></span></span></p>

<p><span style="font-size:11pt;"><span style="line-height:normal;"><span><span style="font-size:8.5pt;"><span><span style="color:#000000;">Direccion</span></span></span></span></span></span></p>
<span style="font-size:11pt;"><span style="line-height:normal;"><span><span style="font-size:8.5pt;"><span style="color:#000000;">T 975 397 479 | M 646 036 239 | <a href="mailto:nombre@domain.com%7C">nombre@domain.com</a></span><span><span style="color:#000000;"><a href="nombre@domain.com%7C">|</a> </span></span></span><span style="font-size:8.5pt;"><span><span style="color:#000000;"><a href="http://www.axpo.com/" target="_blank" rel="noreferrer noopener"><span style="color:#000000;">www.axpo.com</span></a></span></span></span></span></span></span>

<p style="margin:0cm 0cm .0001pt;"><span style="font-size:10pt;"><span><a href="https://www.linkedin.com/company/" target="_blank" rel="noreferrer noopener"><span style="color:#0000FF;"><span style="text-decoration:none;"><span><img alt="cid:part2.CA26621D.AE152E10@iprisma.es" src="https://crm.domain.com/cache/images/in.png" style="width:21px;height:20px;"></span></span></span></a><a href="https://twitter.com/?lang=es" target="_blank" rel="noreferrer noopener"><span style="color:#0000FF;"><span style="text-decoration:none;"><span><img alt="cid:part4.C235FAD6.BE842D03@iprisma.es" src="https://crm.doomain.com/cache/images/twit.png" style="width:21px;height:20px;"></span></span></span></a><a href="https://www.facebook.com/" target="_blank" rel="noreferrer noopener"><span style="color:#0000FF;"><span style="text-decoration:none;"><span><img alt="cid:part6.B7AB591E.C13561C2@iprisma.es" src="https://crm.domain.com/cache/images/face.png" style="width:21px;height:20px;"></span></span></span></a></span></span></p>

<p style="margin-bottom:.0001pt;margin:0cm 0cm 10pt;"><span style="font-size:11pt;"><span style="line-height:normal;"><span><img alt="EmailSignature%20Energy%20Risk%202017" height="71" src="https://crm.domain.com/cache/images/correo%20email%20completo.png" width="479"></span></span></span></p>

<p style="margin-bottom:.0001pt;margin:0cm 0cm 10pt;"><span style="font-size:11pt;"><span style="line-height:normal;"><span><span style="font-size:10pt;"><span><span style="color:#808080;">La información contenida en este correo  está destinada únicamente a la persona o entidad a la que se dirige y puede contener material confidencial y / o privilegiado. Queda prohibida toda revisión, reproducción, difusión u otro uso de esta información por personas o entidades distintas del destinatario previsto. Si ha recibido esta comunicación por error, por favor, elimínela de cualquier soporte y póngase en contacto con el remitente.</span></span></span></span></span></span></p>

<p style="margin-bottom:.0001pt;margin:0cm 0cm 10pt;"><span style="font-size:11pt;"><span style="line-height:normal;"><span><span style="font-size:10pt;"><span><span style="color:#808080;">The information contained in this email is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission or other use of this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.</span></span></span></span></span></span></p>

<div> </div>

<div class="s3gt_translate_tooltip_mini_box" style="border:;margin:auto;font-size:13px;font-family:'X-LocaleSpecific', sans-serif, Tahoma, Helvetica;line-height:13px;vertical-align:top;opacity:.35;">
<div class="s3gt_translate_tooltip_mini"> </div>
</div>

<div class="s3gt_translate_tooltip_mini_box" style="border:;margin:auto;font-size:13px;font-family:'X-LocaleSpecific', sans-serif, Tahoma, Helvetica;line-height:13px;vertical-align:top;opacity:.35;"> </div>

<div class="s3gt_translate_tooltip_mini_box" style="border:;margin:auto;font-size:13px;font-family:'X-LocaleSpecific', sans-serif, Tahoma, Helvetica;line-height:13px;vertical-align:top;opacity:.35;">
<div class="s3gt_translate_tooltip_mini"> </div>
</div>
`

**Comment by mariuszkrzaczkowski** [comment]
attach as a file because not all characters are saved correctly

**Comment by joelbcampos** [comment]
[Plantilla.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2557630/Plantilla.txt)

**Comment by joelbcampos** [comment]
A question. Previously I had a tiket because it did not relate to me, the fields in the module emailtemplate, but I modified in php and I managed to correct the error, this failure can be due to a bad configuration of my hosting.
![ashampoo_snap_2018 11 07_15h54m42s_001_](https://user-images.githubusercontent.com/29610537/48139046-dcff4c00-e2a5-11e8-9c6d-59bc196e859a.jpg)

**Comment by z0lo13** [comment]
Can confirm - works only if i put the html code right in the database

**Comment by joelbcampos** [comment]
I tried to put the html code in the database directly but it does not work

**Comment by TomaszQr** [comment]
@joelbcampos 
In file config/security.php in section 'PURIFIER_ALLOWED_DOMAINS' please write your allowed domains, example:
'PURIFIER_ALLOWED_DOMAINS' => ['crm.domain.com'],
and save your email template again.
