### ISSUE TITLE
Going Live Error

### ISSUE THREAD

**Issue by Carolinercraig** [YetiForceCompany/YetiForceCRM#8506]
I am currently using ipage to host my site, however I have gotten this error when I go to settings:

{"success":false,"error":{"code":0,"message":"An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received..","trace":""}}

I contacted Ipage and they told me that they do not have an ETA on updating curl and I need to contact the code providers:

For now, please contact the plugin provider and allow one of the currently supported ciphers to fix the issue.

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/47999955-67a84580-e104-11e8-8689-86bf07fb988e.jpg)
