### ISSUE TITLE
Record preview broken

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8520]
Current gitdev
![image](https://user-images.githubusercontent.com/8545791/48138580-ab8e7c80-e2b5-11e8-94ae-4718f4e7cf1f.png)

**Comment by vovpff** [comment]
@bpabiszczak @poradz sometimes there are a lot of errors and bugs in developer version. Should I report them?

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/8527/commits/d8ec76ab90a4700b36f12cc5f3113d04705587c0
