### ISSUE TITLE
YetiForce needs your help (and gives gifts in return)!

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#8524]
Hi guys, we need **your** help.

We’re looking for more reviews at G2Crowd, which is a platform where you can review and rate different software. Positive reviews really help us spread the word about YetiForce. The higher in rankings we are, the more people learn about us, which brings more people to the community - one of the key elements of any open source project. 

**For each review you post you will be able to pick either 2 hours of free direct support (the kind we sell in our [support packages](https://yetiforce.shop/index.php?option=com_djcatalog2&view=items&cid=8:technical-support&Itemid=1071)) or 1 month of free cloud services ([Private Cloud 1](https://yetiforce.shop/index.php?option=com_djcatalog2&view=item&id=42:private-cloud-1&cid=12:private-cloud&Itemid=1071)).** 

Free support/cloud also applies to opinions posted on Capterra or Sourceforge, for example, if you review YetiForce on all 4 platforms you will get either 4 months of free cloud services, or 8h free support. Right now G2C is our priority.

If you want to help us and let others know what you like about YetiForce - here are the links:
G2C: https://www.g2crowd.com/products/yetiforce-sp-z-o-o-yetiforce-crm/reviews
Capterra: https://reviews.capterra.com/new/159123 
SourceForge: https://sourceforge.net/software/product/Yetiforce/reviews/new
FinancesOnline: https://reviews.financesonline.com/p/yetiforce-crm/#user-review
Gartner: https://www.gartner.com/reviews/market/sales-force-automation/vendor/yetiforce

Thank you in advance!

**Important** - Please send us an email to reviews@yetiforce.com and attach screenshots of your reviews so we can get in touch with you directly and arrange the support/cloud services.

**Comment by liviubbo** [comment]
![1](https://user-images.githubusercontent.com/42461923/48405124-026ed880-e732-11e8-95a2-bc2d41bb6862.jpg)

**Comment by serban999** [comment]
![yeti1](https://user-images.githubusercontent.com/16606367/48677493-6eac6a80-eb7e-11e8-8fef-c2ba3efc2599.jpg)

**Comment by KatarzynaUlichnowska** [comment]
Hello everyone,
thank you so much for submitting the reviews. We really appreciate your efforts. Everyone who added a review is asked to send us an email to reviews@yetiforce.com and attach screenshots with your reviews. We request that as not all of you have your emails in your GitHub profiles and we couldn't contact you directly.

**Comment by joelbcampos** [comment]
![snap_2018 11 22_15h51m02s_002_](https://user-images.githubusercontent.com/29610537/48910718-fa6d1200-ee70-11e8-8ea2-b8193755d7c2.jpg)

**Comment by paula-w** [comment]
@joelbcampos & @fbojan please send us an email to reviews@yetiforce.com because we don't have your emails and we have to get in touch with you regarding scheduling the free services.

**Comment by paula-w** [comment]
Huge thanks to everyone who helped us get more reviews, we appreciate your help and we're very grateful.
