### ISSUE TITLE
Etapy szans sprzedaży

### ISSUE THREAD

**Issue by szczepanszczepan** [YetiForceCompany/YetiForceCRM#854]
Witajcie, czy i gdzie można zmienić ilość etapów szans sprzedaży w panelu? Nie potrzebuję tyle etapów i chciałbym zbudować swoją ścieżkę. Czy jest to możliwe?

**Comment by bpabiszczak** [comment]
Witam,

możesz zmienić dowolnie:
Tutaj wartości etapów: https://test.yetiforce.com/index.php?parent=Settings&module=Picklist&view=Index&block=2&fieldid=9
Tutaj automatyzacja [np. wyskakujące automatycznie zadania]: https://test.yetiforce.com/index.php?module=Workflows&parent=Settings&page=1&view=List&sourceModule=Potentials
