### ISSUE TITLE
DO NOT SELECT LIST

### ISSUE THREAD

**Issue by joelbcampos** [YetiForceCompany/YetiForceCRM#8540]
I do not know what the problem is, but the selection of lists has stopped working for me.<br><br>And I have been generated a large number of errors that were not before.<br><hr>Generado por YetiforceCRM ver. 4.4.0<br>PHP: 7.1.23<br><br><strong>Errores de configuración del servidor:</strong><br>error_reporting: E_ALL<br>output_buffering: 4096<br>default_socket_timeout: 60<br>memory_limit: 50 MB<br>max_input_vars: 1500<br>session.gc_maxlifetime: 1440<br>auto_detect_line_endings: Off<br>

**Comment by joelbcampos** [comment]
[errores yeti.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2566128/errores.yeti.txt)
![ashampoo_snap_2018 11 09_15h04m32s_001_](https://user-images.githubusercontent.com/29610537/48266902-19ab7e80-e431-11e8-8cfb-3ef956c0ac1c.jpg)

**Comment by vovpff** [comment]
@joelbcampos I'm not sure but looks like your user role don't have  access to `PLL_PENDING` value. If record has this status your user can't change this status. Check this #8352 Same situation?

**Comment by vovpff** [comment]
Check this picklist rules for your role

**Comment by joelbcampos** [comment]
Thank you. It is solved. But I wonder how this has changed, since I have not touched it? Thank you.

**Comment by vovpff** [comment]
@joelbcampos no ideas
