### ISSUE TITLE
net::ERR_SPDY_PROTOCOL_ERROR /index.php:1

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#8545]
#### Issue
The system was working perfectly i almost finished setting it up, however my host updated the SSL certificate and cpanel on my server and now i am not able to open system setting page as well as some other pages. In firefox i was not able to found out any error code or something related, however in Chrome i have an error  Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR /index.php:1

I tried reinstalling whole system from scratch - installing developer version as well as 4.3.0 version, i even did install the yetiforce on another domain but in the same server, nothing help.
It could be apache, ssl or php configuration error after hosting updated the software. 

#### Actual Behavior
When you press system setting button it open "start" tab by default however it just keep endlesssly loading and never show up, same when i go to "Security" tab but there if i uncheck one of 3 variables it does loads.

#### Expected Behavior
Press Setting - Open Start Tab

#### Screenshot of configuration
https://prnt.sc/lgifb1

#### PHP/Apache/Browser Logs
Apache Logs
[Fri Nov 09 18:39:58.057269 2018] [proxy_fcgi:error] [pid 10826:tid 47157022762752] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu
[Fri Nov 09 18:40:00.773769 2018] [proxy_fcgi:error] [pid 10826:tid 47157087901440] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu
[Fri Nov 09 18:40:03.115652 2018] [proxy_fcgi:error] [pid 10826:tid 47157024864000] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu
[Fri Nov 09 18:40:04.751270 2018] [proxy_fcgi:error] [pid 10826:tid 47157085800192] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu
[Fri Nov 09 18:40:05.831724 2018] [proxy_fcgi:error] [pid 10826:tid 47157024864000] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu
[Fri Nov 09 18:40:07.333158 2018] [proxy_fcgi:error] [pid 10826:tid 47157087901440] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu
[Fri Nov 09 18:40:08.814829 2018] [proxy_fcgi:error] [pid 10826:tid 47157020661504] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu
[Fri Nov 09 18:40:11.026660 2018] [proxy_fcgi:error] [pid 10826:tid 47157024864000] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu
[Fri Nov 09 18:40:13.220588 2018] [proxy_fcgi:error] [pid 10826:tid 47157020661504] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu
[Fri Nov 09 18:40:17.612981 2018] [proxy_fcgi:error] [pid 10826:tid 47157024864000] [client 50.100.193.65:52476] Invalid status line from script 'index.php': 0 The web service did not retu

Chrome

POST https://yeti.hmcvanlines.ca/index.php net::ERR_SPDY_PROTOCOL_ERROR                 Csrf.min.js:1
send @ Csrf.min.js:1
send @ jquery.min.js?s=1516469212:2
ajax @ jquery.min.js?s=1516469212:2
o @ Connector.js:131
c @ Connector.js:36
j @ Index.js:577
(anonymous) @ Index.js:327
dispatch @ jquery.min.js?s=1516469212:2
y.handle @ jquery.min.js?s=1516469212:2
trigger @ jquery.min.js?s=1516469212:2
(anonymous) @ jquery.min.js?s=1516469212:2
each @ jquery.min.js?s=1516469212:2
each @ jquery.min.js?s=1516469212:2
trigger @ jquery.min.js?s=1516469212:2
a @ Index.js:284
a @ Index.js:598
(anonymous) @ app.js:1537
l @ jquery.min.js?s=1516469212:2
c @ jquery.min.js?s=1516469212:2
setTimeout (async)
(anonymous) @ jquery.min.js?s=1516469212:2
u @ jquery.min.js?s=1516469212:2
fireWith @ jquery.min.js?s=1516469212:2
fire @ jquery.min.js?s=1516469212:2
u @ jquery.min.js?s=1516469212:2
fireWith @ jquery.min.js?s=1516469212:2
ready @ jquery.min.js?s=1516469212:2
_ @ jquery.min.js?s=1516469212:2

CHROME LOG FROM chrome://net-internals/#events
t=11208 [st=  0] +REQUEST_ALIVE  [dt=704]
                  --> priority = "MEDIUM"
                  --> url = "https://yeti.hmcvanlines.ca/index.php"
t=11208 [st=  0]    NETWORK_DELEGATE_BEFORE_URL_REQUEST  [dt=0]
t=11208 [st=  0]   +URL_REQUEST_START_JOB  [dt=704]
                    --> load_flags = 16384 (MAYBE_USER_GESTURE)
                    --> method = "POST"
                    --> upload_id = "0"
                    --> url = "https://yeti.hmcvanlines.ca/index.php"
t=11208 [st=  0]      NETWORK_DELEGATE_BEFORE_START_TRANSACTION  [dt=0]
t=11208 [st=  0]      HTTP_CACHE_GET_BACKEND  [dt=0]
t=11208 [st=  0]     +HTTP_STREAM_REQUEST  [dt=1]
t=11208 [st=  0]        HTTP_STREAM_JOB_CONTROLLER_BOUND
                        --> source_dependency = 10931 (HTTP_STREAM_JOB_CONTROLLER)
t=11209 [st=  1]        HTTP_STREAM_REQUEST_BOUND_TO_JOB
                        --> source_dependency = 10932 (HTTP_STREAM_JOB)
t=11209 [st=  1]     -HTTP_STREAM_REQUEST
t=11209 [st=  1]      UPLOAD_DATA_STREAM_INIT  [dt=0]
                      --> is_chunked = false
                      --> net_error = 0 (?)
                      --> total_size = 159
t=11209 [st=  1]     +HTTP_TRANSACTION_SEND_REQUEST  [dt=0]
t=11209 [st=  1]        HTTP_TRANSACTION_HTTP2_SEND_REQUEST_HEADERS
                        --> :authority: yeti.hmcvanlines.ca
                            :method: POST
                            :path: /index.php
                            :scheme: https
                            accept: text/html, */*; q=0.01
                            accept-encoding: gzip, deflate, br
                            accept-language: en-US,en;q=0.9
                            content-length: 159
                            content-type: application/x-www-form-urlencoded; charset=UTF-8
                            cookie: YTSID=afb8f07325549458e6509f9e4052cec3
                            origin: https://yeti.hmcvanlines.ca
                            user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
                            x-requested-with: XMLHttpRequest
t=11209 [st=  1]        UPLOAD_DATA_STREAM_READ  [dt=0]
                        --> current_position = 0
t=11209 [st=  1]        HTTP2_STREAM_UPDATE_SEND_WINDOW
                        --> delta = -159
                        --> stream_id = 101
                        --> window_size = 65376
t=11209 [st=  1]     -HTTP_TRANSACTION_SEND_REQUEST
t=11209 [st=  1]      **HTTP_TRANSACTION_READ_HEADERS  [dt=703]
                      --> net_error = -337 (ERR_SPDY_PROTOCOL_ERROR)
t=11912 [st=704]   -URL_REQUEST_START_JOB
                    --> net_error = -337 (ERR_SPDY_PROTOCOL_ERROR)
t=11912 [st=704]    URL_REQUEST_DELEGATE_RESPONSE_STARTED  [dt=0]
t=11912 [st=704] -REQUEST_ALIVE
                  --> net_error = -337 (ERR_SPDY_PROTOCOL_ERROR)**

#### Your Environment

* YetiForce Version used: 4.40
* Browser name and version: Chrome, Firefox
* Operating System and version: Windows 7,8,10

**Comment by z0lo13** [comment]
Do i have to consider yetiforce support DEAD? - The Configuration of The Server is simply absent - just some configs regarding php.ini and thats it? What about php extensions what about apache? i installed the crm on 3 different servers all 3 of them have different errors. I even wanted to purchase support hours and wrote an email - no one wrote me back.

**Comment by bpabiszczak** [comment]
Tomorrow someone will look at it.

**Comment by mariuszkrzaczkowski** [comment]
Your problems are the reason for incorrect Apache configuration, in addition you have http2 enabled, which we do not support yet.
You need an administrator who solves your problems, the error is not on the side of CRM
