### ISSUE TITLE
Import Leads with CSV

### ISSUE THREAD

**Issue by mskoczek** [YetiForceCompany/YetiForceCRM#8547]
Hi.
Does any one have template for importing lest of leads to yeti.
I have strugly with header.

**Comment by joelbcampos** [comment]
It is not necessary to have a template. You can assign to each header, its location in the import to Yetiforce.
When you upload the information you want to assign, you upload the file and in the next step it lets you assign the values.

**Comment by mskoczek** [comment]
Yes i did that but unfortunatly i have that from last 11H 
I try with that and i dont know what is wrong.
![import](https://user-images.githubusercontent.com/40525437/48316278-e9571200-e5e1-11e8-983b-e01b5bbf4985.jpg)
![phone number](https://user-images.githubusercontent.com/40525437/48316279-e9571200-e5e1-11e8-95d1-99b6f40d43d8.jpg)

**Comment by bpabiszczak** [comment]
Ciągle zapominam, że macie u nas system :/ Takie rzeczy robimy od ręki dla klientów chmury, tylko trzeba przesyłać na adres SLA@yetiforce.com. Proszę przesłać przykładowy plik, jaki chce Pan zaimportować, sprawdzimy problem we wtorek od rana.

**Comment by mskoczek** [comment]
Wysłałem mejla i pliki. Dziękuje.

**Comment by acsinsurancegroup** [comment]
I'm having the hardest time doing a basic import right now with the most recent up to date version 5.0 Complete. It's with the phone number. I have exhausted every avenue and have tried several CSV files with Phone numbers in them and get this same issue every time no matter what I do. See screenie.

![Screenshot (8)](https://user-images.githubusercontent.com/42642523/54067366-b5dd6a80-4204-11e9-94d1-103921e97ca7.png)

Please help, I'm several days behind getting our leads into the updated system. Thank you :)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6585
Or 
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/ConfigTemplates.php#L297

**Comment by acsinsurancegroup** [comment]
@mariuszkrzaczkowski Thanks for your suggestion. Unfortunately that didn't do anything for me. What I did to get it to work however was this.

I replaced all of the first ( in the phone number with +1 ( throughout the list and then it finally imported all of our leads list. Yay, it worked and thanks again.
