### ISSUE TITLE
Can't activate Change history action for profile

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8549]
#### Issue

I made some tests and changes for profiles configuration and can't turn on `Change history` action for profile. Every time after saving profile this checkbox became unchecked.

#### Actual Behavior

Updates tab invisible for this profile

*Upd* I checked gitdev. Checkbox don't make sense for Updates tab visibility at all.

Se gif. There is my situation and after that gitdev.

![updates tab1](https://user-images.githubusercontent.com/8545791/48354741-7a41f200-e6a3-11e8-9e94-95e4fa04562d.gif)

#### Expected Behavior

Tab should have ability to activation for profile.

#### How to trigger the error

1. Go to profiles
2. Uncheck `Change history`
3. Save
4. Edit and check `Change history`
5. History tab not activated

#### Your Environment

* YetiForce Version used: 4.4.0
* Browser name and version: Latest Chrome
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
Is it possible to change this params manually?

**Comment by mariuszkrzaczkowski** [comment]
run all functions from the file, it will fix errors in the permission structure
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app/Db/Fixer.php
example: App\Db\Fixer::profileField();

**Comment by mariuszkrzaczkowski** [comment]
you create a file like this:
https://github.com/YetiForceCompany/YetiForceScripts/blob/master/PasswordReset/PasswordReset.php

you upload to the main catalog

in the file you call all functions from the file
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/app/Db/Fixer.php

**Comment by vovpff** [comment]
@mariuszkrzaczkowski 
file `fix.php` in `public_html`

```
<?php

include_once 'app/Db/Fixer.php';
$fix = \App\Db\Fixer::profileField();
```

Result HTTP ERROR 500

**Comment by mariuszkrzaczkowski** [comment]
`chdir(__DIR__ . '/../');`

**Comment by mariuszkrzaczkowski** [comment]
include_once 'include/main/WebUI.php';

**Comment by vovpff** [comment]
@mariuszkrzaczkowski 
`\App\Db\Fixer::profileField();` - result: blank page, no visible changes seen
`\App\Db\Fixer::baseModuleTools();` - result: blank page, no visible changes seen
`\App\Db\Fixer::baseModuleActions();` result: HTTP 500 error page

**Comment by mariuszkrzaczkowski** [comment]
check the logs

**Comment by vovpff** [comment]
@mariuszkrzaczkowski php logs empty. What additional logs you need?

**Comment by mariuszkrzaczkowski** [comment]
Did you change the primary administrator profile?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski no. I has changed usual user profile. I'm not tested `\App\Db\Fixer::baseModuleActions();` code yet because too much work.

**Comment by mariuszkrzaczkowski** [comment]
Check
```SQL
UPDATE
   vtiger_profile2standardpermissions
SET
   `permissions` = '0'
WHERE `profileid` = '1'
```

**Comment by vovpff** [comment]
@mariuszkrzaczkowski this works. As I understand `profileid = '1'` is Admin profile. For another profiles I need to change profile value.

How this variable should be filled here?

https://github.com/YetiForceCompany/YetiForceCRM/blob/2bb6a0628a6ff02add781da92201a9ed3cfd1a0e/app/Db/Fixer.php#L79

**Comment by mariuszkrzaczkowski** [comment]
profileid user profile id on which you are logged in to the system

**Comment by vovpff** [comment]
Why in this case function `\App\Db\Fixer::baseModuleActions();` return 500 error?

**Comment by mariuszkrzaczkowski** [comment]
logs...

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I don't know why 500 error appears in the past but now i checked one more time and there is no errors.

My php file

```
<?php

// require 'app/Db/Fixer.php';
// include_once 'app/Db/Fixer.php';
if (file_exists('include/main/WebUI.php')) {
	include_once 'include/main/WebUI.php';
} else {
	chdir(__DIR__ . '/../');
	if (file_exists('include/main/WebUI.php')) {
		include_once 'include/main/WebUI.php';
	} else {
		chdir(__DIR__ . '/../../');
		if (file_exists('include/main/WebUI.php')) {
			include_once 'include/main/WebUI.php';
		}
	}
}
$fix1 = \App\Db\Fixer::profileField();
$fix2 = \App\Db\Fixer::baseModuleTools();
$fix3 = \App\Db\Fixer::baseModuleActions();
echo 'Done';
```

But I can't feel the difference after calling this file. Admin as usual has all rights. For usual user profile nothing changed.

**Comment by paula-w** [comment]
Is this problem solved @vovpff ?

**Comment by vovpff** [comment]
@paula-w problem solved with sql code with modified `profileid`
```
UPDATE
   vtiger_profile2standardpermissions
SET
   `permissions` = '0'
WHERE `profileid` = '1'
```

But `Fixer.php` not works proper.

**Comment by harshdoshihd** [comment]
Another simple solution I found to same problem was to change php.ini settings for server configuration requirement:
yourdomain.com/index.php?parent=Settings&module=ConfReport&view=Index

![image](https://user-images.githubusercontent.com/61234565/102816528-2e221980-43f4-11eb-93bc-2611d53db008.png)

reference: https://discussions.vtiger.com/discussion/21976/profile-privileges-doesnt-save-update-for-some-modules

**Comment by vovpff** [comment]
@harshdoshihd this value should be greater or smaller than 10000?

**Comment by harshdoshihd** [comment]
> @harshdoshihd this value should be greater or smaller than 10000?

Equals to 10000 or may be greater than that

I have a shared server, dont know how do I update the Cron [CLI] settings to 10000 due to which even I am unable to update certain permissions. But this has worked in my test environment as I have complete control over test environment.
