### ISSUE TITLE
[PL] BUG

### ISSUE THREAD

**Issue by szczepanszczepan** [YetiForceCompany/YetiForceCRM#859]
Witajcie, coś się dzieje z YF. Konfiguruję ustawienia i w pewnym momencie zauważyłem, że większość linków z configuracji i menu głównego przenosi do strony http://templates.send360.pl/8205/2680a147-4554-4d2c-b676-f3888d2a9814/?module=Vtiger&parent=Settings&view=Index, gdzie po ? wstawia odpowiedni link. Co się mogło stać?

**Comment by bpabiszczak** [comment]
Kiedyś tak się działo, gdy brakowało odizolowania w widżetach okna z mailami i zaszyte w mailach js wywalały wiele rzeczy. O ile wiem było to poprawiane kilka miesięcy temu. 

Aby móc cokolwiek z tym zrobić, to potrzebujemy więcej informacji zgodnie z tą instrukcją: https://yetiforce.com/pl/pomys%C5%82y,-zmiany,-b%C5%82%C4%99dy/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html

Proszę również spróbować wywołać błąd u nas na wersji testowej: https://test.yetiforce.com/

**Comment by szczepanszczepan** [comment]
Nie wiem jak wywołać błąd na testowej wersji. W przypadku tego błędu zmianie ulegają linki raz  w sekcji sprzedaży, raz z ustawieniach, raz z Leadach.
Za każdym razem inaczej.
Wedługo mojej wiedzy mam najnowszą wersję.[ver. 1.5.0 RC]

**Comment by bpabiszczak** [comment]
Przyczyn może być wiele, trzeba by było zalogować się do Pana na serwer i sprawdzić przyczynę, jednakże usługa taka nie jest bezpłatna.
