### ISSUE TITLE
PDF header and body overlapping

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8605]
#### Issue

If automatic main margin checked then body of pdf overlap pdf header

![image](https://user-images.githubusercontent.com/8545791/48710650-19be3200-ec1a-11e8-826f-453e656c9e4d.png)

If unchecked then  

![image](https://user-images.githubusercontent.com/8545791/48710673-2e022f00-ec1a-11e8-9916-841060506250.png)

#### Your Environment

* YetiForce Version used: 4.4.79
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
we are working on a new PDF and this problem has already been resolved
