### ISSUE TITLE
PDF watermark

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8606]
#### Issue

PDF watermark should be at center of page

![image](https://user-images.githubusercontent.com/8545791/48710800-8c2f1200-ec1a-11e8-9e0e-56053f3229d6.png)

Now there are no ability to change position.

#### Your Environment

* YetiForce Version used: 4.4.79
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by rafalpospiech** [comment]
We are making brand new library for pdf generation which is available here [YetiForcePDF](https://github.com/YetiForceCompany/YetiForcePDF/tree/developer) so when we finish (very soon) this problem will not occur anymore.
Most likely watermark settings will be more advanced too, so you will be able to change watermark as you wish :)
