### ISSUE TITLE
new field type - random value

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#861]
would be great with a field creating unique random value.

This could be used as token for eg. online payment system... as we want to send a unique url along with invoices and here we would need a token ... eg 6 random characters.

**Comment by waran70** [comment]
fielt?  haha :o)
workflow should do the same:  date*record number plus current time divided by   :-)

**Comment by bpabiszczak** [comment]
We would like to create such a field but at the moment it seems to me that there is no appropriate way to create a universal field. It all depends on needs, for example a confirmation of a transaction [universal id] requires an individual approach. Just like waran70 wrote, adding such a field isn’t difficult programming-wise and adding something like that to the system requires in-depth analysis and integration with external systems. We will of course do it, but we will do it slowly, along with the development of the system.
