### ISSUE TITLE
"Archive record" and "Move to Recycle Bin"

### ISSUE THREAD

**Issue by RabbitDuck** [YetiForceCompany/YetiForceCRM#8616]
* YetiForce Version used: 4.4.0

Hi,

Is it possible to disable or hidden the "Archive record" and "Move to Recycle Bin" buttons?

![screenshot_2018-11-20 project milestones debugstate](https://user-images.githubusercontent.com/31124140/48751703-c652ef00-ecc0-11e8-942b-133d0e771d61.png)

**Comment by mariuszkrzaczkowski** [comment]
if you want to hide it you can do it in profiles, deselect this action

**Comment by RabbitDuck** [comment]
Thank You.
