### ISSUE TITLE
Custom order tabs

### ISSUE THREAD

**Issue by ikyamoet** [YetiForceCompany/YetiForceCRM#8622]
Hi everyone!

I saw here and there that tabs in contact lists can be custom ordered (for example to show image miniatures instead of assigned members like in the attached image).

I know, it may be a very simple thing to do but I'm more than stuck here.. :)

Thanks to help!

Yetiforce 4.4
![124257](https://user-images.githubusercontent.com/35991543/48768506-80465d00-ecb9-11e8-8ee6-8adc87d5eb67.png)

**Comment by vovpff** [comment]
here https://gitdeveloper.yetiforce.com/index.php?module=CustomView&parent=Settings&view=Index&block=13&fieldid=57 you can manage filters and add them as favorites to different users|groups|roles

**Comment by vovpff** [comment]
@ikyamoet no problem
