### ISSUE TITLE
Not attache file from CRM to Email

### ISSUE THREAD

**Issue by varlog11** [YetiForceCompany/YetiForceCRM#8647]
![animation](https://user-images.githubusercontent.com/1807261/48842296-540c0880-edad-11e8-9ca2-6d5e055dfa93.gif)

#### Your Environment

* YetiForce Version used: 4.3.0, 4.4.0, 4.4.84
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mskoczek** [comment]
On my working perfect 4.4.0.
i select 4 files and add to email.
Ok on video what you show you dont atacht files. They are empty. Go to secend page of files and try add Document. That is a file.

**Comment by varlog11** [comment]
Right. Problem only in version 4.3
