### ISSUE TITLE
Profiles mechanism. How it works?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8674]
#### Question

I need to achieve next condition.

Role 1 and Role 2 must have the same permissions for module/records

Only one difference between this roles. Role 1 must be able to view and add comments. Role 2 don't need access to comments.

I have two profiles:
Profile 1 what has access for all needed modules. Profile 2 with access only to comments.

If this two profiles applied to Role 1 user with this role don't has access to records or comments. Looks like active only first profile in in filed here

![image](https://user-images.githubusercontent.com/8545791/48936184-2644d200-ef1b-11e8-974f-fd31bfe6fcaa.png)

Any suggestions?

**Upd**: 4.4.0

**Comment by paula-w** [comment]
Could you perhaps give us some more details? The description seems a bit contradictory.

**Comment by manwenick** [comment]
@vovpff 
From my point of view, it depends of the determined hierarchy of permissions level in YF, which may have impact on this case. 
My assumption:
1st level = role (has no access to view and add comments= your case no. 2)
2nd level = profile (1. profile = has access to view and add comments; 2. profile has NO access to view and add comments)
3rd level = group

I think 1st level permissions, would have the possibility to show you only determined scope of permissions which are assigned from 1st level, even if the 2nd level allows you to do more.

**Comment by vovpff** [comment]
Paula, i will prepare explanation at next week
