### ISSUE TITLE
Search - Configuration

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#8685]
We have more data, it's harder to find them. I do not remember, but I think it was possible to set up search filds for yourself in Search - Configuration. An example of a product search for a vendor. Is it a bug or I'm doing something wrong?

![film1](https://user-images.githubusercontent.com/25682437/48968004-4e9b0200-efe9-11e8-8de9-10366d830951.gif)

* YetiForce Version used:
* Browser name and version:  [ver. 4.4.87
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
This search configuration only for dropdown list. If you put part of product name you will see product name and vendor name. For replacement of columns in modal you need to edit /modules/products/products.php file. This is easy!
