### ISSUE TITLE
New Reports Module

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#8706]
When will the new report module be available for testing? 😃 
#7513

**Comment by bpabiszczak** [comment]
Soon :P [2-3 weeks]

**Comment by cakrina** [comment]
Is it available for testing yet? where and how do I get it?

**Comment by bpabiszczak** [comment]
We need more time

**Comment by SkavenKF** [comment]
I have seen that the next date for version 5.0 is the 31.1. Until when can we expect the new report module, because we still want to do some tests with it?

**Comment by SkavenKF** [comment]
Thank you Paula. I hope that it comes soon. possibly as a pre-patch, since there is currently no possibility to perform an automatic reporting to the management 😞

**Comment by SkavenKF** [comment]
Any news ❓

**Comment by SkavenKF** [comment]
#9480
