### ISSUE TITLE
Edit view in current yatiforce version

### ISSUE THREAD

**Issue by KrishnaPB** [YetiForceCompany/YetiForceCRM#8722]
Dear Team,

Edit view in current yatiforce version is little odd. In the older view it was easy to see all the products details. Now we need to scroll each and every-time. The older look was good. This is just my suggestion. Screenshot of latest version is attached for your reference.
![yati](https://user-images.githubusercontent.com/11535185/49222031-c78ec500-f400-11e8-8c15-9663059ec03d.png)

**Comment by vovpff** [comment]
This is optional layout. Ypo can use old one or this new one

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/a243657c9aa0dcfc17d9dd4294e4e299a1781267/config/performance.php#L94-L95
