### ISSUE TITLE
[BUG]"Add Condition" and "Add Group" buttons in create new filter are not working

### ISSUE THREAD

**Issue by kennethcado** [YetiForceCompany/YetiForceCRM#8728]
#### Issue

When I create new filter in clean install version 4.4.95, the "Add Condition" or "Add Group" function is not working properly. But there are normal in gitdeveloper.yetiforce.com and stable version, kindly help to investigate. 

#### Actual Behavior
No Response

#### Expected Behavior
Prompt fields picklist and choose operator

#### How to trigger the error

1. Create a new filter 
2. Under session "Choose filter conditions:"
3. Click "Add Condition" or "Add Group" button

#### Your Environment

* YetiForce Version used:4.4.95
* Browser name and version: Chrome 70.0.3538.102
* Environment name and version: PHP 7.1.20, Apache/2.4.34
* Operating System and version: Windows 10

**Comment by mariuszkrzaczkowski** [comment]
In order for the developer version to work properly, it needs to be switched to the developer mode. It is necessary because some elements require reloading, e.g. min files.
https://github.com/YetiForceCompany/YetiForceCRM/blob/211bf13ce822363314eef7ec09a1065dff30de2c/config/developer.php#L11-L14
