### ISSUE TITLE
MAX_LIFETIME_SESSION

### ISSUE THREAD

**Issue by SunnieG** [YetiForceCompany/YetiForceCRM#8738]
Hi Guys,

Note sure if i'm being daft here but:
in the config folder > security.php when chaing the MAX_LIFETIME_SESSION from 21600 seconds to 10 seconds (so that the user gets logged out every 10 seconds of no acivity), I found it doesn't work for me.

I am hosting yetiforce on A2 shared hosting and have installed it via CPanel Sofalicious .. I think it's currently version 4.3.

Forgive me if I'm doing something silly by missing out something.

This is a great system and I really apprecitate the work you guys have put into it.

**Comment by adudekyeti** [comment]
Hi,
Minimal life time session is depends on the cron settings and php configuration.
We do not recommend setting a short time life session, because user will be very often log out. Also for example user will not be able to fill form data without logout.
