### ISSUE TITLE
Widgets - Info Request

### ISSUE THREAD

**Issue by Luxx99** [YetiForceCompany/YetiForceCRM#8746]
Hi, I'm rather new with YetiForce 4.4 
I'm setting up the wigets, and I need your help to understand what I'm doing wrong.

I'm in the widget-configuration admin page, and I added to my role all the widgets available. This worked fine.
When I tried to add a "widget with filter" or a "chart from filter" I begin to have problems. For both widgets, the field "select module" is always empty. Why? What do I have to setup to have this field filled in, with the list of (available) modules?

Besides, always in the same configuration page, in the top right corner there is a field (combo box) with a list of a few modules: "my home page", "notifications", "opportunities", etc ... what I do not understand is the usage of this field. 
First question is: why there are only some modules? How can I change this list of modules? 
Then, I added all the (two) widgets related to "opportunities", always to my role. 
Second question is: where can I see/use them? I went back to My Home Page, but I cannot see these last 2 widgets between the available to add.

Last, but not least, is there a widget that deals with sales invoices (i.e. invoices list filtered by month), or I have to create it?

Please help!
Thank you in advance
Fabrizio

**Comment by areksolek** [comment]
Please add a screenshot showing the error. Are all modules active (System settings ->  Standard modules ->Modules – Installation )?

**Comment by Luxx99** [comment]
Here are the screenshots.
In the pic below you can see the emply "module" field when adding a new "widget with filter"
![error-widget with filter](https://user-images.githubusercontent.com/23698008/49384691-d4225e80-f71b-11e8-822e-4797dd9b9c71.jpg)

In the pic below you can see the emply "module" field when adding a new "chart from filter"
![error-chart from filter](https://user-images.githubusercontent.com/23698008/49384693-d4baf500-f71b-11e8-9a18-aabfef749056.jpg)

This is the printscreen of my modules installed. Of course not all are active, but the ones active should be listed in the fields mentioned above.
![modules installation](https://user-images.githubusercontent.com/23698008/49384694-d4baf500-f71b-11e8-81a6-6a41c9acdc92.jpg)

**Comment by mariuszkrzaczkowski** [comment]
attach a screenshot of the configuration verification

**Comment by Luxx99** [comment]
![yetiforce_settings](https://user-images.githubusercontent.com/23698008/49398373-66d3f500-f73e-11e8-96b8-d1ba0ead7e9a.png)

**Comment by mariuszkrzaczkowski** [comment]
you need to improve the server configuration

**Comment by mariuszkrzaczkowski** [comment]
you need to improve the server configuration

**Comment by Luxx99** [comment]
this is the max config allowed for the server. 
Do you thing that the problem is related to that?

**Comment by mariuszkrzaczkowski** [comment]
Yes, test our gitdev

**Comment by Luxx99** [comment]
You're right. I improved the server configuration and now the widgets works. thank you
