### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by subbu5801** [YetiForceCompany/YetiForceCRM#8757]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/b032559c7815884d1f759ca3808e568f1572b69e/modules/Users/models/DetailView.php#L22L95

**Comment by subbu5801** [comment]
> https://github.com/YetiForceCompany/YetiForceCRM/blob/b032559c7815884d1f759ca3808e568f1572b69e/modules/Users/models/DetailView.php#L22L95

Where we are write code in yetiforce please tell me

**Comment by KatarzynaUlichnowska** [comment]
@subbu5801 we don't understand your last comment, could you explain it a bit more?

**Comment by subbu5801** [comment]
Hi Katarzyna Ulichnowska,
you sent me code for the new button where should i write that code.is there any possibility to write code in yetiforce

**Comment by subbu5801** [comment]
ok thanks
