### ISSUE TITLE
Card View while selecting products in Quote

### ISSUE THREAD

**Issue by KrishnaPB** [YetiForceCompany/YetiForceCRM#8778]
While selecting the product in Quotes or any other inventory module, the pop up is appearing as shown in the screenshot. That is now in table view. 

Is there anyway to change this in card view with image as shown in the other attached image. So that we can see more number of products in single page with image.

Current Table view:
![quote](https://user-images.githubusercontent.com/11535185/49512866-3d89a500-f8b5-11e8-9858-c6fcba8fbd4a.png)

Card View:
![card_view](https://user-images.githubusercontent.com/11535185/49512876-42e6ef80-f8b5-11e8-9eea-3d1b2f7305c1.png)

**Comment by bpabiszczak** [comment]
Low priority.
