### ISSUE TITLE
BUG - Roundcube address contacts book 

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#8784]
UPDATE:

i have managed to turn it on - but it works only with one email - when i have 10 emails it does work only on one email.  I was trying to add another email to gitdeveloper and gitstable but google didnt allowed me to proceed

#### Issue
Address | Contact book doesnt work 

#### Actual Behavior
Nothing happens

#### Expected Behavior
Auto Fill email address when enter some of the values

#### How to trigger the error
![111](https://user-images.githubusercontent.com/23143958/49553878-286e3f80-f8d0-11e8-8b83-a1f4739ad7ad.gif)

#### PHP/Apache/Browser Logs
no errors in browser console 
let me know what logs you need exactly

#### Your Environment
* YetiForce Version used: 4.4.0
* Browser name and version: Chrome Firefox

**Comment by vovpff** [comment]
Cron активирован?

**Comment by z0lo13** [comment]
да активирован - все другие функции работают

**Comment by vovpff** [comment]
@z0lo13 тогда не подскажу. Я почтой внутри системы не пользуюсь. По идее крон должен собирать все адреса в адресную книгу. По какой причине этого не происходит не знаю.

Не уверен на 100%, но мне кажется этот кронтаск отвечает за список адресов.
![image](https://user-images.githubusercontent.com/8545791/49568393-f1d10d00-f941-11e8-98b2-6778515489d8.png)
Он стартует и завершается корректно?

**Comment by z0lo13** [comment]
@vovpff да все стартует ошибок не отображает 

so what other setting are related to this? I have only one contact (which I created manually) in rouncube_contacts table. I added directly to table
