### ISSUE TITLE
[BUG] Graphical Calendar not working properly

### ISSUE THREAD

**Issue by kennethcado** [YetiForceCompany/YetiForceCRM#8785]
Am I missing something? I tried to install several developer versions and also changed to same version of PHP and Apache but it still not working properly. I am appreciated if you could help on this issue or advise me how to solve it,

#### Issue
Calendar is not working properly on Developer version 4.4.xx to 4.4.102

#### Actual Behavior
Prompted error message or No Graphical Calendar View

#### Expected Behavior
Developer version found on https://gitdeveloper.yetiforce.com
![error](https://user-images.githubusercontent.com/24854404/49559026-2778f480-f948-11e8-9ef6-54fe1db7319d.png)

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by poradz** [comment]
Hi, when CALENDAR_VIEW parameter has changed (https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/modules/Calendar.php#L52),
you should compiled menu file by just editing and saving any value here: https://gitdeveloper.yetiforce.com/index.php?module=Menu&parent=Settings&view=Index&roleid=0
Otherwise menu link is incorrect and causes bugs.

**Comment by kennethcado** [comment]
Thank you for your prompt reply. I tried to edit and save some value in Menu - Configuration, even remove and create again, the calendar module has some changed but still no luck. Any comments are appreciated.
![yetiforce_calendar](https://user-images.githubusercontent.com/24854404/49690295-5fab4d80-fb69-11e8-857d-7f76901e6956.jpg)

**Comment by poradz** [comment]
We need more info. Do you get any message in develeoper tools' console (click F12)?

**Comment by kennethcado** [comment]
Please find the message in developer console here.
![image](https://user-images.githubusercontent.com/24854404/49764671-09761000-fd0b-11e8-8113-
7e58217833fa.png)

**Comment by poradz** [comment]
Please provide remaining details about your enviroment:
**Your Environment**
Browser name and version:
Environment name and version:
Operating System and version:

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/49784271-fcfab300-fd1c-11e8-96d9-42f182fb85ec.jpg)

**Comment by kennethcado** [comment]
Thank you so much, guys. 

Browser name and version:
Google Chrome 71.0.3578.80 (64bit)

Environment name and version:
CRM version: 4.4.105
PHP 7.1.20

Operating System and version:
Xampp server installed in Windows Server 2008 R2 Standard Edition Service Pack 1
My Desktop: Win10

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by dub34** [comment]
Thanks. I solved this problem with babel. Just compiled source code on babeljs online compiler with ES 2017 preset and minify settings. And this solved my problem
