### ISSUE TITLE
Pewien problem z powiadomieniami

### ISSUE THREAD

**Issue by jakubmusiol** [YetiForceCompany/YetiForceCRM#8789]
Dzień dobry,

chciałbym zapytać o szczegóły działania powiadomień w systemie yetiforce. Póki co, wydają się one dziwnie losowe - niektóre powiadomienia wysyłane od jednego pracownika nie trafiają do drugiego. Zauważyliśmy, że jeśli 1 administrator przesyła powiadomienie 2 administratorowi, to powiadomienia raczej dochodzą. Jednak kiedy wysyła administrator powiadomienie "zwykłemu" pracownikowi, to jest już gorzej.

Jak można to samemu sprawdzić i ustawić?

**Comment by bpabiszczak** [comment]
Wyjaśniłem telefonicznie, dziękuję!
