### ISSUE TITLE
Problem z instalacją YetiForce 2.0

### ISSUE THREAD

**Issue by jucia** [YetiForceCompany/YetiForceCRM#879]
Po rozpakowaniu i próbie instalacji występuje problem:

Fatal error: Can't use function return value in write context in /crm/include/Webservices/Utils.php on line 1005

**Comment by bpabiszczak** [comment]
Niestety za mało informacji. 

Skąd została pobrana paczka? Dane dotyczące serwera itd. Proszę przeczytać ten artykuł:
https://yetiforce.com/pl/pomys%C5%82y,-zmiany,-b%C5%82%C4%99dy/b%C5%82%C4%99dy/125-jak-zg%C5%82asza%C4%87-b%C5%82%C4%99dy.html

Dodatkowo można samemu znaleźć przyczynę, proponuję przeczytać ten artykuł:
https://yetiforce.com/pl/pomys%C5%82y,-zmiany,-b%C5%82%C4%99dy/b%C5%82%C4%99dy/109-debugowanie.html

**Comment by jucia** [comment]
Problemem było php.

Dodałem:

:Location /*.php
Use php56
:Location

do pliku 
.htaccess

i poszło :)

zatem testuję :)

**Comment by bpabiszczak** [comment]
zatem zamykam :]
