### ISSUE TITLE
[Improvement] - please add to YF one of the available open source module creators 

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#88]
its very reasonable to add module creator for improving functionality of the YF. 
Now there is no possibility to add new table or fields in the separated module, and merge it with core modules YF. 
This modules developed for VTiger are not possible to install with YF becouse it are'nt polish language as dafault.

**Comment by bpibiza** [comment]
I think that, if you already have a menu wizard, just that you will be able to create a database (database table), which acts as a module. Rest of the functionalities are implemented at all.

**Comment by waw555** [comment]
Today I installed the module, and I wrote a mistake that is not in the language module ru_ru, in fact it turned out that there is no language in modulet pl_pl and en_gb, and ru_ru there, I unpacked the unit, added language to the folder (the languages that have I was in the system), the language files from en_us and packed back, the installation was no problem. That is, it turns out, if the module does not have the languages that you have in your system, then you do not install the module!

**Comment by bpibiza** [comment]
Today i have resolved similar problem. Most of the open source modules uses as default English language. This language should be used in time of the installation of the YF. After that we can to change users language, and it works fine. Some problem is in time when we use language different like english in installation proces YF . I don't know the mechanic of the Yeti (vtiger) but maybe better will be use one language as default in installation and translate on the fly as is in the change of users language. Of course install module should be translated to, but the system language (core) should stay in english as developer standard.

**Comment by mariuszkrzaczkowski** [comment]
Mandatory language that is required during the instalation is a default language of the system: $default_language z config\config.inc.php. Yes, I agree that English should be a primary language of the system, but the lack of a language file doesn't cause any errors within the system, but only a lack of translation.

I added to the system a simplified option for creating modules . Only 4 names needs to be entered in ModuleManager and the system creates a modul and all fields are added by LayoutEditor.

**Comment by bpibiza** [comment]
W dniu 2015-01-16 o 08:45, Mariusz Krzaczkowski pisze:
>
> Mandatory language that is required during the instalation is a 
> default language of the system: $default_language z 
> config\config.inc.php. Yes, I agree that English should be a primary 
> language of the system, but the lack of a language file doesn't cause 
> any errors within the system, but only a lack of translation.
>
> I added to the system a simplified option for creating modules . Only 
> 4 names needs to be entered in ModuleManager and the system creates a 
> modul and all fields are added by LayoutEditor.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/YetiForceCompany/YetiForceCRM/issues/88#issuecomment-70218518>.
>
Tested a minutes ago.... REVELATION !!!
On the first look everything is ok.

thanks a lot
