### ISSUE TITLE
REST Documentation (OAI)

### ISSUE THREAD

**Issue by Niko9911** [YetiForceCompany/YetiForceCRM#8809]
Is there any OpenApi Specifications about the rest which Yeti Provides?

**Comment by mariuszkrzaczkowski** [comment]
We don't currently have API documentation, we will create it but we don't know why. You can find a lot of info at github. https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+api+OR+rest+OR+Webservice+

**Comment by Niko9911** [comment]
Not useful and affects choice of CRM. As for now because there is not documentation, we cannot even think about YetiForce, which means also we do not need support from you. (And getting support from you would mean big money for you.)
