### ISSUE TITLE
Is it possible to add an editable spreadsheet to a custom module so that data can be added when a record is created? 

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#8810]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Comment by vovpff** [comment]
@hobejeans if you mean item list for custom module you need to change your module type from basic to advanced.
If you mean some special filed with spreadsheet - this type not available in YetiForce
