### ISSUE TITLE
Activating “Internal Mail Composer” in user prefs has no effect

### ISSUE THREAD

**Issue by kimborg** [YetiForceCompany/YetiForceCRM#8812]
Version 4.4:
When clicking “Send email” on a Contact or Account, I get the Roundcube mail composer, even though I’ve set user prefs to “Internal mail composer”.

**Comment by mariuszkrzaczkowski** [comment]
![internal mail composer](https://user-images.githubusercontent.com/10198654/49728438-0af3f980-fc73-11e8-8528-84a90c00ca1f.gif)

**Comment by kimborg** [comment]
OK, so here's what it looks to me:
I'm in Companies and Contacts/Contacts/Detail/<Contactname>, and I click the "Send email" icon
1. User prefs internal mail composer "Off": Starts local email client (in my case, Thunderbird)
2. User prefs internal mail composer "On": Starts Roundcube
So theres no way I can recreate the internal mil composer window in the screen above.

**Comment by arek1-618** [comment]
![2018-12-11_11-31-51](https://user-images.githubusercontent.com/32322851/49794878-e6faeb80-fd38-11e8-89f7-a7f032edb81c.gif)
![2018-12-11_11-35-05](https://user-images.githubusercontent.com/32322851/49794896-ef532680-fd38-11e8-9368-c8b64c3cf9d5.gif)
It seems that everything works fine.

**Comment by kimborg** [comment]
So what you are saying is that Internal Mail composer set to "On" should give Roundcube? I had the impression that there was an internal mail composer inside YetiForce that would substitute Roundcube.
