### ISSUE TITLE
Been here for a good 20 mins. Is something wrong?

### ISSUE THREAD

**Issue by Thirdy-jea** [YetiForceCompany/YetiForceCRM#8814]
#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

![image](https://user-images.githubusercontent.com/40558801/49726699-95efe680-fca9-11e8-949a-a4a36f270677.png)

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/49727050-ac794c00-fc6f-11e8-85f3-b0de07a3d6ff.jpg)
