### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Thirdy-jea** [YetiForceCompany/YetiForceCRM#8815]
#### How to trigger the error

1. I think this was due to the system timeout that occurred, I think it was connected to my previous dilemma, that the installation time took longer than usual.

#### Screenshot of configuration
![image](https://user-images.githubusercontent.com/40558801/49727673-cc2e6580-fcab-11e8-940f-c0c4feae0976.png)

#### Your Environment

* YetiForce Version used: ver. 4.4.105
* Browser name and version: Chrome Version 71.0.3578.80 (Official Build) (64-bit)
* Environment name and version: PHP 7.2.12
* Operating System and version:  Windows 10 pro (64 bit)

**Comment by Thirdy-jea** [comment]
Some of the widgets and icons are missing from the dashboard UI. Any possible fix on this?

**Comment by Thirdy-jea** [comment]
![image](https://user-images.githubusercontent.com/40558801/49727929-6393b880-fcac-11e8-9628-aea848629f26.png)

Additional Info

**Comment by mariuszkrzaczkowski** [comment]
is a dev version and requires the crm to be set to developer mode, which is why it doesn't work for you.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?q=is%3Aissue+developer+mode+is%3Aclosed

**Comment by vovpff** [comment]
@Thirdy-jea looks like your system installation not finished successful

**Comment by mariuszkrzaczkowski** [comment]
@Thirdy-jea 
Please attach a screenshot from verification of configuration
