### ISSUE TITLE
Russia missing from the country code in Phone Number module / Accounts.

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#8822]
#### Issue
Russia is missing from the country code, Phone Number module.  

While adding the phone number, The Country code drop down menu lists all the countries . Russia is missing from the list.

#### Actual Behavior

The country code should have Russia with the country code of +7

#### Expected Behavior

Russia should have been listed in the Country list. Also, It would be great if the default value can be changed to specific country rather than scrolling through the entire list. 

#### How to trigger the error
Add phone number module in Accounts and Russia is missing from the list.

#### Screenshot of configuration

![screenshot 2018-12-10 at 16 14 46](https://user-images.githubusercontent.com/21019034/49735057-2ec93680-fc97-11e8-8fb1-867f4cdaf025.png)

#### Your Environment

* YetiForce Version used: 4.3
* Browser name and version: Chrome
* Environment name and version: 
* Operating System and version: Linux

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/49737625-9e3a2880-fc8d-11e8-8515-7e666f1b6a63.png)
