### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Thirdy-jea** [YetiForceCompany/YetiForceCRM#8830]
![image](https://user-images.githubusercontent.com/40558801/49770164-2536e180-fd1e-11e8-89d4-30718273791c.png)

What do I do here?

I tried bypassing this and it led to a malfunction on the system itself. Someone help please, thanks.

**Comment by mariuszkrzaczkowski** [comment]
these extensions in php are missing
https://unix.stackexchange.com/questions/167975/how-to-know-which-php-extensions-are-installed
https://askubuntu.com/questions/795629/install-php-extensions-in-ubuntu-16-04

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.4.0/xampp_YetiForceCRM-4.4.0-complete.zip
