### ISSUE TITLE
bugs in mPDF 

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#8850]
i wanted to test the developer version of yetipdf module - how soon you will release it?
#### Issue
mPDF
Cant find any variables i can use with "generated PDF name" option only generates the name exactly with the phrase which i put in the box e.g. Contract then file will be Contract.pdf. i tried Contract $(record : company)$ but it didnt work.

Another Bug is that it actually does not matter what page size you will choose in the begining of the template creation, mPDF will print A4 size anyways. It is very inconvenient as in Canada most common paper format is Letter size. I checked on gitstable - it has same issue there.

#### Actual Behavior
simple name, A4 Size

#### Expected Behavior
more choices for a name option, Letter Size

#### How to trigger the error
Change page size to any other than a4 - there will be no changes
Place Contract $(record : company)$ and the pdf will be Contract $(record : company)$.pdf

#### Your Environment

| Environment      | Version / name |
| ---------------- | ---------- |
| YetiForce        |4.4.0
| Browser          |Firefox
| PHP              |7.1
| Operating System |Windows

**Comment by rafalpospiech** [comment]
In upcoming version of YefiForceCRM there will be new pdf generation engine so this problems will not occur.

**Comment by rtorrescodes** [comment]
Ok so thats why i dont have mPDF in 5.1 new version? i was about to open a issue, but now im reading it was removed.  Should i wait? Thanks a lot

**Comment by rafalpospiech** [comment]
since 5.0 there is an YetiForcePDF engine https://github.com/YetiForceCompany/YetiForcePDF/tree/developer

**Comment by rtorrescodes** [comment]
And How can i use it or install it? In versión 4 i just needed to click on the mPDF library installation button. Now i only get the roundcube installation button.  Thanks a lot.

**Comment by rafalpospiech** [comment]
It's already installed by default
