### ISSUE TITLE
Can't filter by contacts by type

### ISSUE THREAD

**Issue by Hammerman3000** [YetiForceCompany/YetiForceCRM#8852]
I can't figure out how to filter by contact type.
E.g. I want to see all contacts that are members of Vendors or all contacts that are members of Competition.
However, when creating a filter condition I can only set values that are directly searched within the "member of" attribute field as part of the company name and not relate to the actual type of the contact to it.
Am I overlooking something or was this simply forgotten as an option to filter for?

**Comment by TomaszQr** [comment]
In the developer version, the filters were expanded with the ability to display and filter on fields from the base module as well as from related modules. 
You can test it here - https://gitdeveloper.yetiforce.com

![conditions](https://user-images.githubusercontent.com/14273211/49855787-7c0bec00-fdee-11e8-9fe7-ad638b00698f.png)

**Comment by vovpff** [comment]
@TomaszQr cool conditions system!
