### ISSUE TITLE
Oddziały Kontrahenta

### ISSUE THREAD

**Issue by kstelm** [YetiForceCompany/YetiForceCRM#8853]
Dzień dobry,

Mam takie pytanie, bo nie wiem jak to wyklikać. Chciałbym dodać kilka oddziałów dla jednego Kontrahenta.
Na przykład kontrahentem jest Amazon, który ma odział w PL i DE. Jak należy skonfigurować aplikację (z czego skorzystać), aby później operator/użytkownik aplikacji mógł dodać kontrahenta oraz jego odziały.
Z tymi oddziałami będę chciał później wiązać definicję oferty w stylu transport z oddziału A do oddziału B.

W aplikacji są Oddziały, ale chyba to nie jest to, bo pojawiają się w innym miejscu niż kontrahenci i są pomieszani, bo są wszystkie oddziały, a nie pogrupowane po kontrahentach.

Z góry dziękuje za informację i pomoc.

**Comment by bpabiszczak** [comment]
Oddziały to oddziały naszej firmy.
W module Kontrahenci możemy stworzyć hierarchię [czyli oznaczyć, który kontrahent podlega pod którego kontrahenta] tworząc wielowymiarową hierarchię.

**Comment by kstelm** [comment]
Dziękuję, udało się.
Jedno pytanie jeszcze uszczegółowiające: czy w przypadku gdy wejdę w podgląd kontrahenta, to czy da się zmienić nazwę wyświetlanego bloku z listą kontrahentów podrzędnych na inną niż "Kontrahenci" (domyślna), np. chciałby aby ten blok nazywał się "Oddziały kontrahenta" ?

**Comment by bpabiszczak** [comment]
a gdzie to się wyświetla? Proszę o zrzut ekranu.

**Comment by kstelm** [comment]
W podglądzie Kontrahenta (tj. podgląd kontrahenta nadrzędnego).
Zależy mi na możliwości zmiany nazwy "Kontrahenci" na inną nazwę, na tej konkretnej podstronie.

<img width="742" alt="kontrahenci" src="https://user-images.githubusercontent.com/45801095/49903324-232c6a00-fe67-11e8-866f-abccb96a6540.png">
