### ISSUE TITLE
search multiple values in text column

### ISSUE THREAD

**Issue by sunilgareja** [YetiForceCompany/YetiForceCRM#8854]
Is there a way of searching/filtering multiple values in one text column:

For example : 
ORDER REFERENCE = text field
**order ref 1
ref 2
random string 3** 
+ imagine there are 1000 more records, all with different data 

I want to search for this field containing **order ref 1** and **ref 2** out of the 1000 records .

I know you have the select 2 option availible for picklist field searching but I was just wondering if you are able to do similar with the text field?

Thanks

![multiple text filter](https://user-images.githubusercontent.com/19517899/49833937-03c40d00-fd93-11e8-98cc-d639b792dc44.png)

**Comment by paula-w** [comment]
Right now you can either use filters (set suitable conditions) or use global search (keep in mind that the fields you want to search by should be added in the search engine’s configuration). IF you use global search you can get a result similar to the one in the screenshot:
![fce3e9f5](https://user-images.githubusercontent.com/13310141/62028738-44b54880-b1e1-11e9-9233-957f117175b5.png)
