### ISSUE TITLE
This page isn’t working on install

### ISSUE THREAD

**Issue by karamatf** [YetiForceCompany/YetiForceCRM#8863]
Hi i have done the same and now getting the error

This page isn’t working
app.libertas-fund.com is currently unable to handle this request.
HTTP ERROR 500

this is a blank server i have done the reinstall and made sure all plugins are installed

**Comment by mariuszkrzaczkowski** [comment]
duplicate #6465
https://github.com/YetiForceCompany/YetiForceCRM/issues/6465#issuecomment-446632593

**Comment by karamatf** [comment]
> duplicate #6465
> [#6465 (comment)](https://github.com/YetiForceCompany/YetiForceCRM/issues/6465#issuecomment-446632593)

not duplicate that user is getting a screen im not getting anything ?

**Comment by karamatf** [comment]
http://app.libertas-fund.com/info.php
here with all the php configs and the version is 4.4.0

**Comment by mariuszkrzaczkowski** [comment]
Please, attach a screenshot of configuration verification and full logs

**Comment by karamatf** [comment]
reinstalling the lamp any writeups to follow to install everything once

**Comment by karamatf** [comment]
CPU: two cores
4 GB RAM (guaranteed)
300 GB disk space (SSD-boosted)
SSD boost
lamp+webmin 
running Cent os 7

**Comment by karamatf** [comment]
will give logs when it comes back online i ran the instalation now

**Comment by karamatf** [comment]
going to attempt to reinstall this all over again http://app.libertas-fund.com/

**Comment by vovpff** [comment]
@karamatf try to increase execution time on server. 600 is ok for already installed system. On me slow server I used about 60000 ms value.

**Comment by karamatf** [comment]
> @karamatf try to increase execution time on server. 600 is ok for already installed system. On me slow server I used about 60000 ms value.

i am gonna try that i  will update shortly
