### ISSUE TITLE
Warning: Error while sending STMT_CLOSE packet. PID=27103 in /home/u891505882/public_html/finance/YetiForceCRM-4.3.0-complete/include/database/PearDatabase.php 

### ISSUE THREAD

**Issue by mohamed2682016** [YetiForceCompany/YetiForceCRM#8864]
During run setup give me this error
Warning: Error while sending STMT_CLOSE packet. PID=27103 in /home/u891505882/public_html/finance/YetiForceCRM-4.3.0-complete/include/database/PearDatabase.php on line 296

Fatal error: Uncaught Error: Call to a member function rowCount() on boolean in /home/u891505882/public_html/finance/YetiForceCRM-4.3.0-complete/include/database/PearDatabase.php:452 Stack trace: #0 /home/u891505882/public_html/finance/YetiForceCRM-4.3.0-complete/install/models/InitSchema.php(89): PearDatabase->update('vtiger_users', Array) #1 /home/u891505882/public_html/finance/YetiForceCRM-4.3.0-complete/install/models/InitSchema.php(24): Install_InitSchema_Model->setDefaultUsersAccess() #2 /home/u891505882/public_html/finance/YetiForceCRM-4.3.0-complete/install/views/Index.php(230): Install_InitSchema_Model->initialize() #3 /home/u891505882/public_html/finance/YetiForceCRM-4.3.0-complete/install/views/Index.php(107): Install_Index_View->step7(Object(App\Request)) #4 /home/u891505882/public_html/finance/YetiForceCRM-4.3.0-complete/install/Install.php(31): Install_Index_View->process(Object(App\Request)) #5 {main} thrown in /home/u891505882/public_html/finance/YetiForceCRM-4.3.0-complete/include/database/PearDatabase.php on line 452

**Comment by mariuszkrzaczkowski** [comment]
![2018-08-13_12-24-39](https://user-images.githubusercontent.com/10198654/49728333-b6e91500-fc72-11e8-83a3-f2906d67082a.jpg)
