### ISSUE TITLE
Yeti PDF - dont respect page formats

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#8899]
#### Issue
If you create the PDF template with a letter size the system generates A4 anyways. I created template on Developer. 
https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List

#### Actual Behavior
A4 Page

#### Expected Behavior
Letter Page

#### How to trigger the error

1. https://gitdeveloper.yetiforce.com/index.php?module=Leads&view=Detail&record=221
2. Press Generate PDF
3. Check the size of the page

#### Your Environment

| Environment      | Version / Name |
| ---------------- | -------------- |
| YetiForce        |  4.4.113
| Web server       |  Apache
| PHP-FPM              |  7.1
| Browser          |  Firefox
| Operating System |  Windows 10

**Comment by rafalpospiech** [comment]
This has already been implemented but repo is not up to date. Till Monday it should be fixed.

**Comment by z0lo13** [comment]
@rafalpospiech @bpabiszczak 
 it is never been fixed - even now, on gitdeveloper and gitstable. PDF generation dont respect format you placed it print A4 anyway.
https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List
