### ISSUE TITLE
Calendar tasks - can not to active or inactive function which is responsible for view in summary popup 

### ISSUE THREAD

**Issue by bpibiza** [YetiForceCompany/YetiForceCRM#89]
management of the fields in calendar tasks is inactive. I can only to add new fields.

**Comment by rskrzypczak** [comment]
Fields editing is disabled by default in this module. It might be changed in the future.

**Comment by bpabiszczak** [comment]
The majority of fields in the Calendar is mandatory, there will never be a possibility to disable or change them. New fields can be added. If someone wants to disable a field, it can be done from a database level, but this person takes responsibility for it. We think that the currently existing solution is enough.
