### ISSUE TITLE
My Mail Module & RoundCube 404

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#8904]
#### Issue
Software configuration/Standard modules/Modules – Installation/System settings/My mailbox
Module Configuration
![screenshot 2018-12-15 at 19 27 10](https://user-images.githubusercontent.com/21019034/50045177-7852c080-009f-11e9-95f4-474a9d1933d9.png)
![screenshot 2018-12-15 at 19 18 56](https://user-images.githubusercontent.com/21019034/50045104-79cfb900-009e-11e9-889e-dc18bd3c4e0e.png)

My Mailbox gets 404
![screenshot 2018-12-15 at 19 03 10](https://user-images.githubusercontent.com/21019034/50045111-ad124800-009e-11e9-8b71-e928db29f9b1.png)

#### Error Logs:

PHP Warning: imap_append() expects parameter 1 to be resource, boolean given in /home/path/app/Mailer.php on line 513
 
PHP Warning: imap_close() expects parameter 1 to be resource, boolean given in /home/path/app/Mailer.php on line 514 

#### Your Environment

| Environment      | Version / Name |
| ---------------- | -------------- |
| YetiForce        |  4
| Web server       |  Apache
| PHP              |  7.2
| Browser          | 
| Operating System | 
| Database         |

**Comment by maninvatsa** [comment]
Well I guess I figured out the issues. 

The problem seems to reoccur when the domain is redirected. Software/ Security / Public_html

Once it's disabled, Everything works fine. 

The option must be off by default or greyed out. It keeps coming up as security threat and enabling the redirection leads to 404. 

![screenshot 2018-12-17 at 02 34 12](https://user-images.githubusercontent.com/21019034/50060395-5ee76c80-01a4-11e9-9290-78d52b362429.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/50073790-0c28a780-01da-11e9-917d-f631400c5c54.jpg)

**Comment by maninvatsa** [comment]
#### Issue

The issue is Virtual Box/My mail gets to 404 after enabling redirection. 
Software/ Security / Public_html

#### Actual Behavior

Error 404 

#### Expected Behavior

My mail should load username and password, login box

#### How to trigger the error

1. Enabling redirection of domain from https://yourdomain.com to https://yourdomain.com/public_html/
2. Software/ Security / Public_html
2. System security configuration


#### Screenshot of configuration

![screenshot 2018-12-19 at 00 31 06](https://user-images.githubusercontent.com/21019034/50184362-eb6d6880-0325-11e9-9728-95186e3a9c67.png)
![screenshot 2018-12-19 at 00 32 10](https://user-images.githubusercontent.com/21019034/50184453-3ab39900-0326-11e9-8b6a-faa0db8da53c.png)


#### PHP/Apache/Nginx/Browser/CRM Logs




```
Logs
```
There are some logs left from the support tickets I raised with the host. It's here. 
[15-Dec-2018 15:43:05 Europe/London] PHP Warning: imap_append() expects parameter 1 to be resource, boolean given in /path/app/Mailer.php on line 513
[15-Dec-2018 15:43:05 Europe/London] PHP Warning: imap_close() expects parameter 1 to be resource, boolean given in /path/app/Mailer.php on line 514

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce         | 4.4
| Web server      | Apache
| PHP                 | 7.2
| Browser           | Mozilla, Chrome
| Operating System | Linux
| Database         | MySQL

**Comment by maninvatsa** [comment]
@mariuszkrzaczkowski Any updates?
