### ISSUE TITLE
Was working fine before

### ISSUE THREAD

**Issue by Thirdy-jea** [YetiForceCompany/YetiForceCRM#8906]
This was working well up until I returned to the office after the weekend. How this happened? I do not know for sure. 
![image](https://user-images.githubusercontent.com/40558801/50061320-fadf9b00-01d9-11e9-9a50-f16d3ac098e3.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/50073427-cfa87c00-01d8-11e9-829a-f7ae8c6b308d.jpg)
