### ISSUE TITLE
Events module fields management

### ISSUE THREAD

**Issue by Luxx99** [YetiForceCompany/YetiForceCRM#8916]
Hi, I'm customizing some modules and now I'm working on the events module. I'd like to hide some fields, but I cannot, as selecting a single field, I cannot see the "edit icon". This is true for any single field.

![immagine](https://user-images.githubusercontent.com/23698008/50088482-76a20d80-0203-11e9-91ba-5e4ef4b22fcd.png)

Another thing I notice is that the events module is not present between the installed module. On the other hand, I can use it without any problem. Is it correct?

![immagine](https://user-images.githubusercontent.com/23698008/50088637-d8fb0e00-0203-11e9-9042-eb6b648bdafd.png)

Thank you in advance for the support.

**Comment by arek1-618** [comment]
Calendar is a typical system module and any change in fields can cause errors in the system.
For example, integration with CalDAV may stop working.
Therefore, these fields have been blocked.
Furthermore in the new version of the Events module, has been  included in the Calendar module.

**Comment by arek1-618** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/6736
https://github.com/YetiForceCompany/YetiForceCRM/issues/5542#issuecomment-354111100
