### ISSUE TITLE
Goods Dispatched Note

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#8923]
![izdaja1](https://user-images.githubusercontent.com/25682437/50104623-d2cc5800-022a-11e9-9f17-b81955989e0d.gif)

![izdaja2](https://user-images.githubusercontent.com/25682437/50107092-ef1fc300-0231-11e9-899e-1014bbfb7ca7.gif)

| YetiForce         |  [ver. 4.4.115] 
| Web server      | 
| PHP                 | 
| Browser           | 
| Operating System | 
| Database         |

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/8940/commits/9c2418ece903b7691997c08f730af6f273c998eb, https://github.com/YetiForceCompany/YetiForceCRM/pull/8920
