### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#893]
I am trying to install the yeti 
but i get this message

Wrong PHP version, recommended version >= 5.4.0

is from hosting server problem?

**Comment by eptapsyxos** [comment]
Ok i am on php 5.3 and i have to upgrade...i figure it out.thank you

**Comment by waw555** [comment]
Core software for the server 
Mint, CentOS, Debian, Ubuntu - works on most Linux distributions. We do not recommend MS Windows operating system as well as MS Windows Server. Although our system works all adequately on Windows servers, it is not an optimal environment in terms of web applicatons.
Apache 2.4 - works also properly with previous versions, i.e. 2.1, 2.2, 2.3 (the latest versions are recommended). You can also use alternative software as lolng as it is compatible. 
MySQL 5.6 -works also properly with previous versions, i.e. 5.5, 5.1 (the latest versions are recommended). You can also use alternative software as long as it is compatible.
PHP 5.5 - works also fine with previous versions, i.e. 5.4, 5.3 (the latest versions are recommended).


https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html
