### ISSUE TITLE
export module (invoices)

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#894]
The export module needs a way to select which columns to export.

eg. when exporting invoices all freetext / description data is also added to csv file. If long texts are added as description / nots - the csv data cant be imported in a usefull way for Excel.

How about adding a tick for export saying "export only filter columns"

**Comment by rlstanek** [comment]
If wanting to export just specific fields/columns create a  Report for
exactly what you want. Then in Reports you have a feature option to export
there.

**Comment by bpabiszczak** [comment]
lalord 
What is currently in the system has been inherited from Vtiger. We are planning to implement a complex financial system that will use current standards. It means that it will be possible to export documents mainly to EDI format so you will be able to move documents between CRM and ERP or send them automatically to customers in PDF/XML formats. Unfortunately, such implementation requires a few months of changes within the system but we are heading this way.

rlstanek 
Good idea provided that a list of products and services isn’t required :p
