### ISSUE TITLE
Record list

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#8941]
#### How to trigger the error

1.
2.
3.

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce         | 
| Web server      | 
| PHP                 | 
| Browser           | 
| Operating System | 
| Database         |

**Comment by vovpff** [comment]
@gopi12343 you can change record order for filter here:
https://gitdeveloper.yetiforce.com/index.php?module=CustomView&parent=Settings&view=Index&block=13&fieldid=57

Example:

![image](https://user-images.githubusercontent.com/8545791/50276507-2ae5a300-0453-11e9-9904-4140573cdc08.png)

![image](https://user-images.githubusercontent.com/8545791/50276547-42bd2700-0453-11e9-9a1a-6308fc13c440.png)

**Comment by gopi12343** [comment]
thank  you for your replay but  if we give like this all records will come ascending order or descending order .but my requirement is  never change existing record . new records only will come on first page.

**Comment by vovpff** [comment]
@gopi12343 choose created time instead mopified time
