### ISSUE TITLE
Increase Custom Label Lenght

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#8944]
Hi, I have created some custom fields in vendors where the I want to increase the label name character lenght. Can you please help.

**Comment by adudekyeti** [comment]
Hi,
The easiest way to do that is set as label translation label.
For example you can set label name: LBL_EXAMPLE_NAME, and then in translations you have to add a new phrase.

**Comment by indrabhusanroy** [comment]
When I go to create a new custom field, there I have to add a Label Name whose default maximum lenght is 50. I want to increase that to 100. How can I do this or where I will find this to change the lenght to 100.

Also When I use a WYSIWYG Editor, If I give a default value whose maximum lenght exceed around 8621, it shows a error. I want to increase the lenght to 10,000. Please help to change this kindly.
