### ISSUE TITLE
reports module - error in 2.0

### ISSUE THREAD

**Issue by lalord** [YetiForceCompany/YetiForceCRM#895]
Can create any new reports in yeto 2.0.

"Add folder" does not save new folders.
"add report" just returns "blank" body area. see attachment.
![report-blank](https://cloud.githubusercontent.com/assets/10504154/7783594/9f7eea18-0147-11e5-8fc2-eb4563cc0711.png)

**Comment by lalord** [comment]
From browser inspection I get server error 500

?module=Reports&view=Edit&folder=All

**Comment by waran70** [comment]
Same here. Additional when creating new report I got message: 
Input Array does not match ?: select * from vtiger_field where vtiger_field.tabid in ('vtiger_emaildetails') and vtiger_field.block in () and vtiger_field.displaytype in (1,2,3) and vtiger_field.presence in (0,2) AND tablename NOT IN ('vtiger_attachments',

**Comment by mariuszkrzaczkowski** [comment]
I verified it on test.yetiforce.com and I didn't see this error. I need more details explaining how to trigger it.
