### ISSUE TITLE
Ui Questions+Contribute Translation

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#896]
Hello from greece

Are you have on your roadmap a holistic change to Yetiforce UI?
using bootstrap and latests javas html5 etc?

I have worked hard for the greek translation of vtiger 6.** and its free of course
i can do the same for the yetiforce if you want it to.

**Comment by mariuszkrzaczkowski** [comment]
hello, how you can do it translation into Greek. we are currently in Greece 
in Zakynthos. as you like, we can get together and talk. we are currently 
working on changes Ui, we want to use the latest version bootstramp

Wiadomość została wysłana przy pomocy AquaMail dla systemu Android
http://www.aqua-mail.com


Dnia 23 maja 2015 14:11:30 eptapsyxos <notifications@github.com> napisał(a):

**Comment by eptapsyxos** [comment]
zakynthos! you are very lucky!
i leave in north greece..far away from zakynthos.
i live in a city called serres(google map it)its near thessaloniki.

I can translate direct from the test site?or i have to download specific files?
give me some instructions and i can start the translation.
from programming i dont know a thing but i have a great passion for opensource crms and programers.

**Comment by mariuszkrzaczkowski** [comment]
please use Language Editor
 https://test.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=10&fieldid=53
