### ISSUE TITLE
Ver 2.0 I get white screen when unzipping - fresh installation

### ISSUE THREAD

**Issue by vjstyla** [YetiForceCompany/YetiForceCRM#897]
Hi there, I have downloaded the files from here and unzipped it in root folder now when I am trying to access it from url it just giving me white screens?

Please suggest

**Comment by amicheals** [comment]
I have this problem as well. I see this on the page:

Fatal error: Can't use function return value in write context in /xxxxx/xxx/xxx/YetiForceCRM-2.0.0/include/Webservices/Utils.php on line 1005

**Comment by amicheals** [comment]
I think it's because of your php version. the test server is working on php 5.6

**Comment by amicheals** [comment]
I tested it with php 5.6 and I got the install page. @vjstyla

**Comment by vjstyla** [comment]
@amicheals , @vctrin @mariuszkrzaczkowski  @joebordes  Hi There,

Thanks for the reply, I am using php 5.4.37 , is it not good enough? Please help me to sort this out friends....Here I am keeping the files http://sitarwebs.com/yeti and see its all blank...to check the php version you can replace /yeti with /phpinfo.php and see

PLEASE HELP

**Comment by vjstyla** [comment]
Ok its solved, i have installed php 5.5 and its working
