### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#8977]
#### Issue

I exported the accounts from the CRM and While Importing, It keeps failing. It happened many times. The real issue seems to be date but Date is of great importance for me. The accounts are sorted to the date of interaction. The date fields are exactly the way CRM exported and Yet it keeps failing. If i uncheck the Date as Mandatory value, The import works but there's no dates to the account which literally makes no sense. 

#### Actual Behavior

Error importing. Records failed importing

#### Expected Behavior

The record should be imported because It was exported from the CRM and It's barely 1 accounts with two fields. Account name and Date. 

#### How to trigger the error

![yeti bs](https://user-images.githubusercontent.com/21019034/50309248-2fd84000-04af-11e9-9038-1799ff7fb2df.gif)

#### Screenshot of configuration

![screenshot 2018-12-19 at 00 31 06](https://user-images.githubusercontent.com/21019034/50309275-4d0d0e80-04af-11e9-935b-93dca6d70ecf.png)
![screenshot 2018-12-19 at 00 32 10](https://user-images.githubusercontent.com/21019034/50309278-4f6f6880-04af-11e9-9247-11d2e0dea1f2.png)

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

Environment | Version / Name
-- | --
YetiForce | 4.4
Web server | Apache
PHP | 7.2
Browser | Mozilla, Chrome
Operating System | Linux
Database | MySQL

**Comment by vovpff** [comment]
Idea: replace your exported date to YYYY-MM-DD hh:mm:ss and try to import

**Comment by adudekyeti** [comment]
There was a problem with date format. In the newest version this bug is fixed.

**Comment by cakrina** [comment]
Just to add my 5 cents, I've noticed during import not only date format has to be YYYY-MM-DD but user settings for date format has to match YYYY-MM-DD and if it's not import will fail

**Comment by maninvatsa** [comment]
> Just to add my 5 cents, I've noticed during import not only date format has to be YYYY-MM-DD but user settings for date format has to match YYYY-MM-DD and if it's not import will fail

This totally worked for me. Thanks @cakrina

**Comment by apcloic** [comment]
Bear in mind that YYYY-MM-DD is not available for all languages, at least it's not available in french.
So first, you also have to change YF user language to English (United States), then you will be able to select YYYY-MM-DD date format before doing the import process.
Quite boring but at least, it's working ;)
