### ISSUE TITLE
V 2.0 migration script broken

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#898]
Migration needs to be revised. It contains many errors such as  VT602_to_YT_create.sql dont creating vtiger_calculations table. In the same script it will be wise to use ONLY CREATE TABLE IF NOT EXISTS

**Comment by bpabiszczak** [comment]
From what we have observed, this error doesn’t exist. It may be a result of the fact that an option of disabling foreign_key_checks didn’t work on your installation for some reason. It should be disabled at the beginning and then enabled again [maybe mysql user doesn’t have privileges for it]. Please verify it on a different server too, e.g. WAMP.

If you still think that the problem exists in the system, you need to describe step-by-step how to trigger it, e.g. on a clean WAMP version and describe it in a new issue.
