### ISSUE TITLE
Layout editor - block visibility icons missed

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8983]
#### Issue

![image](https://user-images.githubusercontent.com/8545791/50334725-394ac200-051a-11e9-95f2-12cec6269baa.png)

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce         |  gitdev 4.4.20
| Web server      | 
| PHP                 | 
| Browser           | 
| Operating System | 
| Database         |

**Comment by vovpff** [comment]
Looks like block visibility modes functionality missed too.

**Comment by TomaszQr** [comment]
In current version icons are visible
