### ISSUE TITLE
504 Gateway Error

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9002]
#### How to trigger the error

1.
2.
3.

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce         | 
| Web server      | 
| PHP                 | 
| Browser           | 
| Operating System | 
| Database         |

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/50556557-0c956800-0cdb-11e9-8961-7c05c418887b.jpg)
