### ISSUE TITLE
504 Gateway Error

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9008]
#### How to trigger the error

1.
2.
3.

#### Screenshot of configuration

https://snag.gy/NO60dP.jpg
https://snag.gy/ysAnlu.jpg

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce         | 4.4
| Web server      | 
| PHP                 | 
| Browser           | 
| Operating System | 
| Database         |

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-uzytkownika/item/apache-500-internal-server-error-3
![github](https://user-images.githubusercontent.com/10198654/50590677-3641c100-0e8c-11e9-81cc-f0fc62eb8ef5.jpg)
