### ISSUE TITLE
How can I add Contact drop-down in "Related to" in Projects Module?

### ISSUE THREAD

**Issue by vjstyla** [YetiForceCompany/YetiForceCRM#902]
Hello There,

Can you please explain how can I add a contact "Relation to" in Project module, I really want to use this CRM as there are many added feature but just because of no contact can be related to project I cant use this....Please help me with this

Best Regards:
VJ

**Comment by eptapsyxos** [comment]
Good Question.
I have the same question.

**Comment by waran70** [comment]
On the right menu tree you have contacts related  list. Not sure how this approach working with customer portal but at lease allows assign more than one contact to project

**Comment by eptapsyxos** [comment]
War an thanks for reply.
