### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9022]
#### Issue:
 I created a report for an Module but that is not created.it has been loading for 10 days, 
if we open home page it will load 10 minuets  after that i am getting 504 gateway time out error .  

#### Actual Behavior: 
report is created by system but not created 

#### Expected Behavior: 
i want remove this loading page
 i want to remove that loading report page
#### How to trigger the error

1.504 gateway timeout error
2.
3.

#### Screenshot of configuration

![loading page](https://user-images.githubusercontent.com/45963919/50624099-be00fb80-0f70-11e9-83eb-edd6176aeb28.JPG)

#### PHP/Apache/Nginx/Browser/CRM Logs

![gateway1](https://user-images.githubusercontent.com/45963919/50625189-7e3f1180-0f7a-11e9-850a-4e5b59e141f5.JPG)

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce         | 4.4
| Web server      |Apache
| PHP                 | 7.2
| Browser           |  Google chrome
| Operating System | Windows 7
| Database         |  MySQL

**Comment by gopi12343** [comment]
![yetiforce_settings](https://user-images.githubusercontent.com/45963919/50626562-0de8be00-0f83-11e9-9c18-d435bf193074.png)
![console](https://user-images.githubusercontent.com/45963919/50626561-0d502780-0f83-11e9-88d3-7ac767abb386.JPG)

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/6bb53abeddd56543e815ca46f94961f8a7252e21/config/debug.php#L9-L77
Set the configuration so and try to call error
```php
'LOG_TO_FILE' => true,
'LOG_LEVELS' => ['error', 'warning'],
'LOG_TRACE_LEVEL' => 9,
'SQL_DIE_ON_ERROR' => true,
'DEBUG_CRON' => true,
'SMARTY_ERROR_REPORTING' => E_ALL & ~E_NOTICE,
'JS_DEBUG' => true,
'DISPLAY_EXCEPTION_BACKTRACE' => true,
'DISPLAY_EXCEPTION_LOGS' => true,
'EXCEPTION_ERROR_LEVEL' => E_ALL & ~E_NOTICE,
'DAV_DEBUG_EXCEPTIONS' => true,
'DAV_DEBUG_PLUGIN' => true,
'WEBSERVICE_SHOW_ERROR' => true,
'WEBSERVICE_DEBUG' => true,
'MAILER_DEBUG' => true,
```
If there are no logs then changle this code
```php
// Turn on the error handler
'EXCEPTION_ERROR_HANDLER' => true,
// Save logs to file (cache/logs/errors.log)
'EXCEPTION_ERROR_TO_FILE' => true,
// Display errors
'EXCEPTION_ERROR_TO_SHOW' => true,
```

attach all files from the catalog "cache/logs"
