### ISSUE TITLE
[Question] E-Mail assignment, Mailbox access & permission settings

### ISSUE THREAD

**Issue by Hammerman3000** [YetiForceCompany/YetiForceCRM#9024]
Hi there,

first of all a disclaimer: i am aware that this may be an easy question and quick to set with permissions, but I simply couldn't figure out a way how. I check many old posts and documentation and played with the settings but it is beyond my imagination how the solution may look like.

Challenge:
Every user has a mailbox, plus there is a general mailbox assigned to admin account
User Pirate: pirate@company.com
User Princess: princess@company.com
User Admin: mail@company.com

Now a client, lets say goodclient@gmail.com e-mails to princess@company.com

Expected behaviour: the e-mail and eventual replies should be visible to anyone who can see the client record. However, not the mailbox princess@company.com

Actual behaviour: I need to give access to the mailbox of user princess to all other users in order to have the e-mail displayed in the client record.

Question: How can I make the received and sent e-mails between a user and a lead/contact/account etc. visible in the system without granting full mailbox access to every other user?

Thanks,
Hamfred

**Comment by paula-w** [comment]
The system works like this by default. If you enable mail scanner all emails will be saved in the “Company mail” module and access to emails in this module can be configured in the configuration panel. An employee can access all email communication with the client as long as he has all the required permissions.
