### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by aranjo** [YetiForceCompany/YetiForceCRM#9026]
Hi
The installationprozess stuck.
This the Error Log:

Uncaught Error: Class 'yii\base\NotSupportedException' not found
yeti/vendor/yetiforce/yii2/db/Connection.php Zeile 827
Backtrace
#0 yeti/vendor/yetiforce/yii2/db/Connection.php(836): yii\db\Connection->getSchema()
#1 yeti/app/Db/Query.php(27): yii\db\Connection->getQueryBuilder()
#2 yeti/app/Db/Query.php(95): App\Db\Query->createCommand(Object(App\Db))
#3 yeti/app/Company.php(36): App\Db\Query->one()
#4 yeti/app/Controller/View.php(162): App\Company::getInstanceById()
#5 yeti/modules/Users/views/Login.php(35): App\Controller\View->preProcess(Object(App\Request), false)
#6 yeti/include/main/WebUI.php(260): Users_Login_View->preProcess(Object(App\Request))
#7 yeti/include/ma in /home/webpages/lima-city/freemensland/yeti/vendor/yetiforce/yii2/db/Connection.php on line 827

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=NotSupportedException
