### ISSUE TITLE
Agile Kanban Board - next to Gantt

### ISSUE THREAD

**Issue by gitdevusr** [YetiForceCompany/YetiForceCRM#9028]
Dear YetiForce Team, 

Kanban for simple handling of changing states is desired.  Why not using your great vertically workflow and adding a agile board module, next to the spoken Gantt? Keep fingers crossed, you becomming the best and adding what your potentially bill payers desire. :-)

![board](https://user-images.githubusercontent.com/44125056/50725259-5c20cd00-10fb-11e9-96f1-5f0a16fea444.png)

**Comment by epsilonsc** [comment]
Hi @gitdevusr Maybe we'll pay for this functionality together ?

**Comment by gitdevusr** [comment]
Why not, we are swiss company with 12 young people who need a long lasting crm tool with simple hand able techniques. We all need a tool for non dev people, surviving living cost.

Check out nur.design



On January 10, 2019 11:45:14 PM UTC, Sebastian <notifications@github.com> wrote:
>Hi @gitdevusr Maybe we'll pay for this functionality together ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/YetiForceCompany/YetiForceCRM/issues/9028#issuecomment-453304805

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by epsilonsc** [comment]
@gitdevusr  It's like us. We have a similar number of employees. We provide IT services for health care, and we also do not write software. In principle, you could put tasks and tickets on the Kanban Board.
@bpabiszczak , can you give the amount for writing?

**Comment by gitdevusr** [comment]
Having a one man software company next to it, supporting the team, being ready for writing desktop modules and interfaces.
Like many technique enthusiast, I do need to earn the money for studying, dev time and common things. Maybe overtime

instead one time budget, maybe 500 CHF per Month, may for a year. If we can profit and handle well, maybe more.

 

Von: Sebastian <notifications@github.com> 
Gesendet: Freitag, 11. Januar 2019 01:06
An: YetiForceCompany/YetiForceCRM <YetiForceCRM@noreply.github.com>
Cc: gitdevusr <dev@harbo.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [YetiForceCompany/YetiForceCRM] Agile Kanban Board - next to Gantt (#9028)

 

@gitdevusr <https://github.com/gitdevusr>  It's like us. We have a similar number of employees. We provide IT services for health care, and we also do not write software. In principle, you could put tasks and tickets on the Kanban Board.
@bpabiszczak <https://github.com/bpabiszczak>  , can you give the amount for writing?

**Comment by paula-w** [comment]
You can now donate to our project through OpenCollective: https://opencollective.com/yetiforcecrm 
All the donations (apart from the 3 dedicated tiers) are going to be spent towards one full time programmer whose only task will be providing support for GitHub issues and suggestions.

**Comment by Pietrox** [comment]
Instead of developing a kanban board, integrating with Trello would be much more better for Yeti.
At least better than twitter :)

**Comment by gitdevusr** [comment]
Really possible but then you can't host it by yourself, so.. maybe the informational self-determination is lost anyway... but why they say, data is the oil of the 21century?

**Comment by paula-w** [comment]
This is @bpabiszczak 's response:
As far as Kanban or Trello integration are concerned - we can create them if they are ordered by a client or enough money is collected on OpenCollective.

**Comment by swainr** [comment]
@paula-w Could you provide an estimate of how much would need to be raised to support the kanban development?

**Comment by bpabiszczak** [comment]
1.500 EUR
