### ISSUE TITLE
Record Number

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#9029]
1. I have created a custom module that should generate a record number once a record has been created. For some reason the record number field is empty when a new record is created. Is there any way to fix this issue with out recreating the module from scratch? 

2. if i decide to delete the custom module & create a new one is there a way to save the picklist(s) that were created for that module so that i can add them to the new one?

**Comment by vovpff** [comment]
1. Empty record number? You can add missing symbols for this first record manually in database.
2. Create new module and add picklist with the same field name. I think after that you can remove old module.

**Comment by hobejeans** [comment]
Solved... 
Go to the module... Software configuration /Standard modules/Modules – Installation/System settings - 
select the module edit button - when the window pops up click on module sequence numbering. Set your preferences the click the blue button to update missing record sequence. That did the trick.
