### ISSUE TITLE
Greek Translation Problems

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#903]
1)A lot of fields after i translate it to greek they are remaining in english
2)The same on the header menu.

On the language translate settings i see the greek translation but after refresh nothing seems to happend.

Extra Question:How can i translate the widgets on summary view of the modules?

**Comment by waw555** [comment]
Add language language editor
Set the default language
Change the language in the user settings

![2015-5-25_9-46-41 22](https://cloud.githubusercontent.com/assets/1402355/7791983/672184dc-02c3-11e5-8c37-68f089098e25.jpg)
![2015-5-25_9-47-3 301](https://cloud.githubusercontent.com/assets/1402355/7791985/6ad63bcc-02c3-11e5-936e-40f7810bd267.jpg)
![2015-5-25_9-47-56 244](https://cloud.githubusercontent.com/assets/1402355/7791986/6d64ef14-02c3-11e5-9f00-a734eff2d649.jpg)
![2015-5-25_9-48-20 412](https://cloud.githubusercontent.com/assets/1402355/7791988/6fe68734-02c3-11e5-972d-371cb3b86e92.jpg)

**Comment by waw555** [comment]
When using the site test.yetiforce.com, do not forget that you are not alone and someone else can also change the language at the moment.

**Comment by eptapsyxos** [comment]
Waw555 thanks for the tutorial but I ve all ready working on that way. Maybe is need translation on core files that is not available on in site translator,like the vtiger.php which I can find here in the repo. You can confirm that I ve mentioned if you drop down some menus like project Greek ΕΡΓΑ .the project task module for example remains in English although I have translate it to Greek.

**Comment by waw555** [comment]
The original language is Polish, if you are translating from English, the language of the variables can not be translated, using as a basis, together with the Polish language English

**Comment by waw555** [comment]
I usually do so
![langedit](https://cloud.githubusercontent.com/assets/1402355/7792705/0ae98054-02d0-11e5-8122-a454320f314f.JPG)

**Comment by KatarzynaUlichnowska** [comment]
1.	If you report a bug, please try to trigger it on our testing version, provide a link and a step-by-step description. 
2.	From your description we are not able to deduct the cause of your problem. The description below should help you. 

Translations are downloaded in the following way: 
User level:
1.	A language file of a module 
2.	The main language file Vtiger.php
3.	Data base
4.	And when there is none of them, it returns a value of the variable

Administrator level:
1.	A language file of a module 
2.	The main language file Settings/Vtiger.php
3.	The main language file Vtiger.php
4.	Data base
5.	And when there is none of them, it returns a value of the variable

Translations should be added to modules but if it doesn’t work, they should be added to the main file and if even this doesn’t work, report it as a bug and provide a detailed description.

**Comment by eptapsyxos** [comment]
Ok
Where to upload the zip file i ve made including inside it the Vtiger.Php for user and settings
?????
Because i can import it from inside the site translator..there is an option only for export not for import.
