### ISSUE TITLE
Export size

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9039]
#### How to trigger the error

1.
2.
3.

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       | 4.4
| Web server (name nad version) |apache
| PHP  |7.2
| Browser (name and version)  | Google chrome
| Operating System (name nad version)  | Windows7
| Database (name nad version) | mysql

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/1384b815af5e58724b1a809f3f353bbe654b2e24/config/performance.php#L40-L41
