### ISSUE TITLE
customer portal does not show sales orders or invoices

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#905]
To recreate.

Add a sales order.

Log into the customer portal.
Go to the sales order tab.

Results:
There are no records in this module.

**Comment by amicheals** [comment]
My developer fixed this issue. I'll ask him to share what he did.

**Comment by bpabiszczak** [comment]
If the problem still exists, add a new issue and provide a step-by-step description of how we can trigger it on our testing version:

CRM: https://test.yetiforce.com/ 
PORTAL: https://test.yetiforce.com/portal/
