### ISSUE TITLE
Chart from widget group by company

### ISSUE THREAD

**Issue by wrobeltomasz** [YetiForceCompany/YetiForceCRM#9058]
When I click on the chart, the filter does not show data.
I've verified on several environments.

the system has prepared a link: 

https://gitdeveloper.yetiforce.com/index.php?module=Calendar&view=List&viewname=138&search_params=[[[%22link%22,%22e%22,492]]]

Recording:
![nagrywaj_2019_01_10_09_10_49_165](https://user-images.githubusercontent.com/46556533/50955313-137d6100-14b9-11e9-8b27-9e3878480d9e.gif)

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version

**Comment by bpabiszczak** [comment]
I checked and works correctly.
