### ISSUE TITLE
Import Question

### ISSUE THREAD

**Issue by amicheals** [YetiForceCompany/YetiForceCRM#907]
When I import contacts and choose member of, the system automatically imports into the vendors table. 

I need to be able to specify what type of organization the contact is for. I needed the information imported into the organization tab

How do I exit that

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/835

**Comment by MaciejStencel** [comment]
Now you can specify the default module for reference fields, or prefix each/all columns with parent module information, MODULENAME::::VALUE ex.
Accounts::::value
