### ISSUE TITLE
Override language file with custom

### ISSUE THREAD

**Issue by ad1rie1** [YetiForceCompany/YetiForceCRM#9070]
#### Issue
I want to overide some language entry, so i have activated "'LOAD_CUSTOM_FILES' => true,'

And, i have make a copy of the CRM language file to "custom\languages\fr_fr"
the file placed is : SSalesProcesses.json 
and it contain  : 
{
  "php": {
    "FL_MEMBER_OF": "Affaire maitre",
    "SSalesProcesses": "Affaires",
    "SINGLE_SSalesProcesses": "Affaire",
    "LBL_SSALESPROCESSES_INFORMATION": "D\u00e9tails Affaires",
    "FL_ESTIMATED_DATE": "\u00c9ch\u00e9ance Affaire",
  },
  "js": []
}

#### Actual Behavior
In the CRM the field not overided

#### Expected Behavior
Oportunity is remplaced by Affaire

#### How to trigger the error
1. Navigate in the CRM and go to Oportunity module

#### Your Environment
| YetiForce       v4.4
| Web server (name and version)  WAMP apache 2.4.35
| PHP   7.2.10
| Browser (name and version)  Chrome v71.0.3578.98
| Operating System (name and version)  W10
| Database (name and version)  Mysql 5.7.23

**Comment by vovpff** [comment]
There are should be fr-FR language in system. Check here https://gitdeveloper.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=4&fieldid=53
You don't need any copies of files. Just use language manager for corrections or translations

**Comment by ad1rie1** [comment]
Oh thanck you :)
