### ISSUE TITLE
Create Advanced bloc Basic Line without module links

### ISSUE THREAD

**Issue by ad1rie1** [YetiForceCompany/YetiForceCRM#9074]
Hello, 

the functionality that I ask is to be able to create the generic line without being linked to a module: 

![image](https://user-images.githubusercontent.com/1949622/51031721-b9a29700-159d-11e9-8f4d-3fa42e8a568a.png)

Actually without the field " Item name" it dont working : 
Item name
Mandatory basic field, specifies modules to select records from. Additionally includes limit settings to block record saving when the credit limit is reached.

**Comment by rafalpospiech** [comment]
I think you need to write custom module for this behaviour, or let the yetiforce team do it for you for some fee.

What is the "Item name" and why it's not working?
Is Item name a custom field you want to add?
Is this a bug / feature / question ?

> to be able to create the generic line without being linked to a module
You want fields that are not placed in any module?

> Additionally includes limit settings to block record saving when the credit limit is reached.
What credit? what limit?

**Comment by rafalpospiech** [comment]
For now this field is mandatory, it must exists if you want to display form.

However, you can set `Mandatory` option to `No` to be able to save record without specifying any inventory.
![chrome_2019-02-11_08-53-00](https://user-images.githubusercontent.com/36499752/52550964-b38d1980-2dda-11e9-9827-266330f7f08d.jpg)

**Comment by rafalpospiech** [comment]
I'm closing this issue, but you can freely respond here.
