### ISSUE TITLE
Import/Sync Calendars and Contacts

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#9083]
The wonderful CRM seriously lacks the ability to Import/Sync Calendars and Contacts from other sources especially Google. 

I wonder how did the developers ignored it. Developers please look into this. In fact, You can vote and I am sure the majority would love it.

**Comment by paula-w** [comment]
The system has built in integration with CalDAV and CardDAV, which allows you to sync your calendar and contacts with any program/device that supports this international standard: 
    • Android
    • iOS
    • Thunderbird
    • Outlook
