### ISSUE TITLE
Is it possible to mass import activities?

### ISSUE THREAD

**Issue by remyscherer** [YetiForceCompany/YetiForceCRM#9087]
We are currently trying YetiForce Online Version out and have a testaccount. Now we would like to import all data from our old system into the new one. 
I added customers and contacts, but unfortunately I found no way to add activities with an import or script.

Can someone help me out?

**Comment by mariuszkrzaczkowski** [comment]
You can achieve this with ICS or with API. HERE you have an example of using:

https://github.com/YetiForceCompany/YetiForceScripts/blob/1ff0bfa65331243488a28343f1a116e0c46a0db9/YetiREST/demo_yetiforce_api.php#L99-L102

We are currently rebuilding the import mechanism in the Calendar module, so it will be the same as in the other modules, and will be added to the developer version in a few days.
