### ISSUE TITLE
Items moving not available for some modules

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9094]
#### Issue

Impossible to move lines in table for some modules

Calculations:
![image](https://user-images.githubusercontent.com/8545791/51182169-60f53600-18de-11e9-8062-c4f4fb2cdde1.png)

Sales Orders:
![image](https://user-images.githubusercontent.com/8545791/51182206-7a967d80-18de-11e9-9372-587e9dcebdff.png)

But possible for IGDN:
![image](https://user-images.githubusercontent.com/8545791/51182230-900ba780-18de-11e9-8280-d2ba604ddc43.png)

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       |  gitdev 4.4.133

**Comment by rskrzypczak** [comment]
The sorting option is available after you add a field with item numbering (No.) in advanced block configuration. 
If you don't want this field to be visible, you can hide it by changing its visibility in field settings.

**Comment by vovpff** [comment]
@rskrzypczak thanks. Cool option!
