### ISSUE TITLE
Updates when items sorting

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9098]
#### Issue

If `Item Number` column active there are available updates if positions sorted

![image](https://user-images.githubusercontent.com/8545791/51234925-34ddc180-197f-11e9-9d05-4280f63c6d48.png)

But if `Item Number` are hidden then updates also available to one string.

![image](https://user-images.githubusercontent.com/8545791/51234948-49ba5500-197f-11e9-88f0-d4342bb68860.png)

There are should be line breaks or sorting ignored for modtracker if `Item Number` hidden.

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       |  gitdev 4.4.134

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/46b90c074c975ea097f76550f18876fbddbc62a4
