### ISSUE TITLE
where to upload vtiger.php tranlated to greek?

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#910]
Where to upload the zip file i ve made including inside it the Vtiger.Php for user and settings
?????i mean for the greek tranlation.
Because i can import it from inside the site translator..there is an option only for export not for import.

**Comment by waw555** [comment]
Make a copy of the folder in the en_us folder languages in the folder and rename gr_gr, add the language setting, the code language and translate gr_gr
![gr_gr](https://cloud.githubusercontent.com/assets/1402355/7797405/05ec86a2-0305-11e5-8a90-d62bfcf35c01.JPG)

**Comment by waw555** [comment]
![gr_gr2](https://cloud.githubusercontent.com/assets/1402355/7797419/45e28374-0305-11e5-96a8-efcdb20792e6.JPG)

**Comment by eptapsyxos** [comment]
Ok thanks again.i will try it in couple of ours and i will feedback.

**Comment by eptapsyxos** [comment]
Ok.I have the vtiger.php file ready.How i merge it?or upload it on test site?

**Comment by eptapsyxos** [comment]
Ok i found it...sorry i am noob :-)
