### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by Jshilova** [YetiForceCompany/YetiForceCRM#9101]
Hi,

We are using YetiForce ver. 4.3.0 and trying to get Contacts and SSalesProcesses via API from this page: https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST

Unfortunately, various errors occur:
1. 

```
record with id #185413 for module Contacts
REST Error (401): No permissions to view record
updating recordREST Error (401): No permissions to edit record
```

However, we work using admin account.

2. ListRecord just doesn`t return anything, even error.
```
list records for Contacts
Array
(
    [headers] => Array
        (
            [firstname] => Имя
        )
    [records] => Array
        (
        )
    [count] => 0
    [isMorePages] => 
```

3. We can not get a record from SSalesProcesses, but it definetely exists `cause we have just created it via API. 
```
list records for SSalesProcesses
REST Error (400): Invalid module, no relationship
Array
(
)
************************
updating recordREST Error (401): Record doesn't exist
Array
(
)
create new recordArray
(
    [id] => 319779
)
```

Our version of CRM is a customized one. Can these errors be related with that? Does it mean that we should ask the company that customized CRM to provide us with new API files? Or can we find something that can help us here in Git?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/51240057-386f4980-197b-11e9-92f9-dd70bb55844e.jpg)
