### ISSUE TITLE
YetiForce CRM joined Crowdin

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#9104]
Dear Community,
we are happy to announce that YetiForce CRM joined Crowdin. It’s a platform that allows you to do translations through a visual interface. It is free to join and you can volunteer to translate parts of the system. 
Here is our project page: https://crowdin.com/project/yetiforcecrm 
We have already integrated it with our GitHub repository. 
If you don't have a Crowdin account, please register at Crowdin.com or use your current GitHub account for the registration.
The source language of our Crowdin project is currently English. You will be notified whenever there is something new to translate. 
We have prepared [a short guide](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/adding-translations-via-crowdin) explaining how to add translations via Crowdin.

Additionally, in the 5.0 version there will be a new mechanism for downloading languages. 

We look forward to your involvement!

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/51311675-bc900280-1a49-11e9-8187-89f9544aac12.png)
![image](https://user-images.githubusercontent.com/10198654/51311680-bef25c80-1a49-11e9-82c4-75d5ed0a62bb.png)
