### ISSUE TITLE
Picklists in progress bar

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9114]
#### Issue

There are should arrive cool feature progress bar in preview header but this feature applicable only for status picklists.

I checked what there are ability to activate this type of preview in header for every picklist and this is result.

![image](https://user-images.githubusercontent.com/8545791/51323938-89199c00-1a7a-11e9-8ea0-ab7a757225d3.png)

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       |  gitdev 4.4.135

**Comment by paula-w** [comment]
We are going to keep this functionality in its current state because we don't want to limit our users options as far as the preview is concerned.  We know it looks messy if you show all 4 elements, but we believe our users will only choose the one they need to see in the preview.
