### ISSUE TITLE
Payment In error

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#9129]
#### Issue

Incorrect request
Incorrect value detected, please contact your administrator

#### Actual Behavior

Incorrect request
Incorrect value detected, please contact your administrator

#### Expected Behavior

Supposed to show the payment

#### How to trigger the error

1.
2.
3.

#### Screenshot of configuration

![yeti bs](https://user-images.githubusercontent.com/21019034/51423891-79fc3080-1bd7-11e9-901b-264f2d862e9e.gif)

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```
[19-Jan-2019 03:30:02 Europe/London] PHP Warning:  file(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /path/modules/Settings/CurrencyUpdate/bankmodels/NBP.php on line 123
[19-Jan-2019 03:30:02 Europe/London] PHP Warning:  file(http://www.nbp.pl/kursy/xml/dir.txt): failed to open stream: no suitable wrapper could be found in /path/modules/Settings/CurrencyUpdate/bankmodels/NBP.php on line 123
[19-Jan-2019 03:30:02 Europe/London] PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity "" in /path/modules/Settings/CurrencyUpdate/bankmodels/NBP.php on line 146
[19-Jan-2019 03:30:02 Europe/London] PHP Fatal error:  Uncaught Error: Call to a member function children() on boolean in /path/modules/Settings/CurrencyUpdate/bankmodels/NBP.php:148
Stack trace:
#0 /path/modules/Settings/CurrencyUpdate/models/Module.php(78): Settings_CurrencyUpdate_NBP_BankModel->getRates(Array, '2019-01-18', false)
#1 /path/modules/Settings/CurrencyUpdate/cron/CurrencyUpdateCron.php(15): Settings_CurrencyUpdate_Module_Model->fetchCurrencyRates('2019-01-18', true)
#2 /path/cron.php(70): require_once('/path/...')
#3 {main}
  thrown in /path/modules/Settings/CurrencyUpdate/bankmodels/NBP.php on line 148

Environment | Version / Name
-- | --
YetiForce | 4.4
Web server | Apache
PHP | 7.2
Browser | Mozilla, Chrome
Operating System | Linux
Database | MySQL

**Comment by mariuszkrzaczkowski** [comment]
attach a configuration verification screen shot

**Comment by maninvatsa** [comment]
Well, I am guessing you will point me to the same thing again. 
It was working fine and It worked fine with a new installation. I am pretty positive it has nothing to do with the server configuration. I understand the server config are required But it's on 3rd party host and I can't demand additional resources as mentioned in the requirements. 

If you have anything new to tell me then I will be glad

Thank you.

**Comment by mariuszkrzaczkowski** [comment]
missing full logs attach them
configuration is very important, that's why I verify because very often it has a problem and not CRM itself.
see us on gitdev or gitstable if your problem occurs there. I pre-see that you have blocked downloading files from outside. And this is a configuration error

**Comment by maninvatsa** [comment]
Here's the configurations:

Can you please tell me where can if ind the error logs for payment in module? 

I have checked the error logs and it no longer has the issues I highlighted above. I managed to fix all the issues. I just can't seem to access the payment in module. Everything else seems to work fine. 

![screenshot 2019-01-24 at 12 59 23](https://user-images.githubusercontent.com/21019034/51670560-f88e0f00-1fd7-11e9-8e5e-26951fecc06b.png)

![screenshot 2019-01-24 at 12 59 39](https://user-images.githubusercontent.com/21019034/51670573-fd52c300-1fd7-11e9-8688-69d74281fb50.png)

**Comment by maninvatsa** [comment]
Here are some more error messages:

![screenshot 2019-01-24 at 14 58 31](https://user-images.githubusercontent.com/21019034/51676742-91c52180-1fe8-11e9-9a6b-274dd2806115.png)


#0 app/Base.php(48): App\Purifier::purifySql('date-paid', true)
#1 modules/Vtiger/models/ListView.php(416): App\Base->getForSql('orderby')
#2 modules/Vtiger/models/ListView.php(481): Vtiger_ListView_Model->loadListViewOrderBy()
#3 modules/Vtiger/views/List.php(281): Vtiger_ListView_Model->getListViewEntries(Object(Vtiger_Paging_Model))
#4 modules/Vtiger/views/List.php(101): Vtiger_List_View->initializeListViewContents(Object(App\Request), Object(Vtiger_Viewer))
#5 include/main/WebUI.php(260): Vtiger_List_View->preProcess(Object(App\Request))
#6 include/main/WebUI.php(182): Vtiger_WebUI->triggerPreProcess(Object(Vtiger_List_View), Object(App\Request))
#7 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#8 {main}

Log files:

2019-01-24 11:53:24.2124 [error][IllegalValue] - purifySql: date-paid
 - 0 app/Purifier.php (265)  >>  App\Log->error('purifySql: date-paid','IllegalValue')
 - 1 app/Base.php (48)  >>  App\Purifier->purifySql('date-paid',true)
2019-01-24 11:53:24.2126 [error] - ERR_NOT_ALLOWED_VALUE||date-paid
App\Exceptions\IllegalValue: ERR_NOT_ALLOWED_VALUE||date-paid in /path/yeti/app/Purifier.php:266
Stack trace:
#0 /path/yeti/app/Base.php(48): App\Purifier::purifySql('date-paid', true)
#1 /path/yeti/modules/Vtiger/models/ListView.php(416): App\Base->getForSql('orderby')
#2 /path/yeti/modules/Vtiger/models/ListView.php(481): Vtiger_ListView_Model->loadListViewOrderBy()
#3 /path/yeti/modules/Vtiger/views/List.php(281): Vtiger_ListView_Model->getListViewEntries(Object(Vtiger_Paging_Model))
#4 /path/yeti/modules/Vtiger/views/List.php(101): Vtiger_List_View->initializeListViewContents(Object(App\Request), Object(Vtiger_Viewer))
#5 /path/yeti/include/main/WebUI.php(260): Vtiger_List_View->preProcess(Object(App\Request))
#6 /path/yeti/include/main/WebUI.php(182): Vtiger_WebUI->triggerPreProcess(Object(Vtiger_List_View), Object(App\Request))
#7 /path/yeti/index.php(25): Vtiger_WebUI->process(Object(App\Request))
#8 {main}
 - 0 include/main/WebUI.php (186)  >>  App\Log->error('ERR_NOT_ALLOWED_VALUE||date-paid
App\\Exceptions\\IllegalValue: ERR_NOT_ALLOWED_VALUE||date-paid in app/Purifier.php:266
Stack trace:
#0 app/Base.php(48): App\\Purifier::purifySql(\'date-paid\', true)
#1 modules/Vtiger/models/ListView.php(416): App\\Base->getForSql(\'orderby\')
#2 modules/Vtiger/models/ListView.php(481): Vtiger_ListView_Model->loadListViewOrderBy()
#3 modules/Vtiger/views/List.php(281): Vtiger_ListView_Model->getListViewEntries(Object(Vtiger_Paging_Model))
#4 modules/Vtiger/views/List.php(101): Vtiger_List_View->initializeListViewContents(Object(App\\Request), Object(Vtiger_Viewer))
#5 include/main/WebUI.php(260): Vtiger_List_View->preProcess(Object(App\\Request))
#6 include/main/WebUI.php(182): Vtiger_WebUI->triggerPreProcess(Object(Vtiger_List_View), Object(App\\Request))
#7 index.php(25): Vtiger_WebUI->process(Object(App\\Request))
#8 {main}')
 - 1 index.php (25)  >>  Vtiger_WebUI->process()
2019-01-24 11:53:24.1576 [info][application] -
$_GET = [
    'module' => 'PaymentsIn'
    'view' => 'List'
    'mid' => '72'
    'parent' => '71'
]
$_POST = []
$_FILES = []
$_COOKIE = [
    'YTSID' => '0bda69f528d027f017f3156f185d1c55'
]
$_SESSION = [
    'last_activity' => 1548330804.1605
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => 'cf0f7e8b99f8353228e749ca6898f1a1750be977'
    'user_name' => 'myusername'
    'full_user_name' => 'My full name'
    'fingerprint' => '8e5604af-99db-47a5-b5e9-465040486690'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
    ]
    'lvs' => [
        'PaymentsIn' => [
            'sortby' => 'date-paid'
            'sorder' => 'ASC'
            'viewname' => 73
        ]
        'Accounts' => [
            'sortby' => 'dandt'
            'sorder' => 'DESC'
            'viewname' => 4
        ]
        'PaymentsOut' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 74
        ]
        'FInvoiceCost' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 108
        ]
        'Announcements' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 77
        ]
        'ServiceContracts' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 39
        ]
        'HelpDesk' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 13
        ]
        'SQuoteEnquiries' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 79
        ]
        'SRequirementsCards' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 81
        ]
        'SCalculations' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 82
        ]
    ]
]
$Libs = [
    0 => 'apcu'
]====================================================================================================================================

**Comment by maninvatsa** [comment]
Any updates on it?

**Comment by vovpff** [comment]
@maninvatsa looks like your installation is broken and this errors appears. At first some of your webserver params not applicable for system.

**Comment by vovpff** [comment]
I'm not sure but with so small webserver values your system your system can be installet not successful. At firt you need to condigure webserver, after that install fresh system and try it!

**Comment by rafalpospiech** [comment]
First line of the first log from php says:
> [19-Jan-2019 03:30:02 Europe/London] PHP Warning: file(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /path/modules/Settings/CurrencyUpdate/bankmodels/NBP.php on line 123

We are not using `file()` function there, now we are using `GuzzleHttp` lib so this problem may not exists anymore.
We will publish 5.0.0 version today or tomorrow so you will be able to check if problem still exists on your server.
On developer version everything seems to be allright https://gitdeveloper.yetiforce.com/index.php?module=PaymentsIn&view=List&mid=72&parent=71

I'm closing this issue for now, and after update, you can create new one with fresh logs or comment here and I we will reopen this issue if this problem will still exists.

**Comment by harshdoshihd** [comment]
I noticed a random behaviour in my system:

At first I tried to export user list and I got an error:
![image](https://user-images.githubusercontent.com/61234565/102988649-3d12e400-453a-11eb-8c3e-b9e13f4234c8.png)

Broke my head for sometime and casually clicked (CTRL+click) on side menu
![image](https://user-images.githubusercontent.com/61234565/102988710-5b78df80-453a-11eb-9a35-e7f8da8333f3.png)

& I got this page:
![image](https://user-images.githubusercontent.com/61234565/102988748-6af82880-453a-11eb-87cc-3091b6a3b335.png)

And finally was able to download the user list

**Comment by harshdoshihd** [comment]
I saw an unusual error:

I was trying to pull user list and selected some users then clicked on export button, i was redirected to the below page:
![image](https://user-images.githubusercontent.com/61234565/102989201-38026480-453b-11eb-9697-ed0b6ec9eeec.png)

Broke my head for sometime, the casually clicked on side menu (crtl+click):
![image](https://user-images.githubusercontent.com/61234565/102989277-5d8f6e00-453b-11eb-821b-47c5134f4b34.png)

To my surprise, I was redirected to export page with limitations:
![image](https://user-images.githubusercontent.com/61234565/102989388-8adc1c00-453b-11eb-9008-9dc14e3f1204.png)

But the error still persist related to downloading partial list
