### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by miriampl** [YetiForceCompany/YetiForceCRM#913]
Witam serdecznie - 

Na tej stronie widzę, że jest integracja z google calendar
[Search for Google](https://github.com/YetiForceCompany/YetiForceCRM/search?utf8=%E2%9C%93&q=google)

Jak i gdzie to aktywować, nie znalazłem tego w dokumentacji.

**Comment by bpabiszczak** [comment]
Integracje ma Vtiger, my ją częściowo usunęliśmy a docelowo zostanie ona całkowicie do usunięcia z systemu. Została ona zastąpiona integracją z CalDAV i CardDAV, daje to o wiele większe możliwości i pozwala na integracje z dowolnym urządzeniem i dowolną aplikacją działającą z tym standardem.
