### ISSUE TITLE
Calendar's notifications postponed

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#9130]
Nothing happens

![calendar s notifications](https://user-images.githubusercontent.com/25682437/51431372-1b12d780-1c28-11e9-9ce2-9eacd18cd81d.gif)

| YetiForce       | . [ver. 4.4.136]

**Comment by areksolek** [comment]
Did this error appear on gitdeveloper?

**Comment by fbojan** [comment]
YES

**Comment by adudekyeti** [comment]
I can not reproduce the error. Could you tell me is this still exist in the version 4.4.143? If yes, could you explain me how to do that?

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/51821282-f4fccf80-22d8-11e9-852d-654ccebe575d.png)
