### ISSUE TITLE
[PL] Brak pola z modułu powiązanego 

### ISSUE THREAD

**Issue by marcin1987a** [YetiForceCompany/YetiForceCRM#9133]
#### Issue
Nie moge wyświetlić nowo utworzonego pola Podstawowy Adres email , powiązanego z modułem Kontrahenci w widoku do edycji w nowo utworzonym module - Zamówienia . Wzorowałem się na przykładzie modułu wbudowanego zamówienia, dodałem również powiązania potrzebne aby wyświetlić typ danych pochodzących z modułu wbudowanego Kontrahenci, ale kiedy przechodzę do edycji danych pokazuję się moje noto utworzone pole ale nie ma w nim wartości "Mail podstawowy " z Kontrahenta.  

#### Actual Behavior
Pokazuje się nazwa pola , ale brak pola input tak jakby nie pobierał danych (przy czym we właściwościach pola dodałem widoczność )

#### Expected Behavior
Chciałbym aby pokazał się  podstawowy adres email wybranego kontahenta. 

#### How to trigger the error

1.
2.
3.

#### Screenshot of configuration

<a href="https://ibb.co/SnDnXd8"><img src="https://i.ibb.co/PhshZ9n/tworzenie-pola.jpg" alt="tworzenie-pola" border="0"></a>
<a href="https://ibb.co/Ltgb04q"><img src="https://i.ibb.co/nc1ZwhV/wlasciwosci-widocznosci.jpg" alt="wlasciwosci-widocznosci" border="0"></a>
<a href="https://ibb.co/zGLbtyr"><img src="https://i.ibb.co/jgxGjcT/brak-pola.jpg" alt="brak-pola" border="0"></a>
Widok z bazy : 
<a href="https://ibb.co/CbmBKJH"><img src="https://i.ibb.co/N9tx21y/baza.jpg" alt="baza" border="0"></a>

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       | ver 4.4.0
| Web server (name and version) | nginx 
| PHP  | 7.1
| Browser (name and version)  | opera , firefox 63.0.3
| Operating System (name and version)  | Windows 7 pro
| Database (name and version) | mariadb 10.1.37

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/51608281-4bec5880-1f17-11e9-9833-d32f6135829e.jpg)

**Comment by rafalpospiech** [comment]
Dla przykładu: w module Leads można dodać mail kontrahenta jako pole z modułu powiązanego.
Jeżeli tworzysz nowy moduł spróbuj wzorować się na tym co jest i działa.
Przeszukaj też bazę danych może nie ma jakichś połączeń, albo są niewłaściwe.

![chrome_2019-01-23_14-07-53](https://user-images.githubusercontent.com/36499752/51608630-55c28b80-1f18-11e9-8e0f-0d85dd6180f3.jpg)

**Comment by marcin1987a** [comment]
Proszę o otworzenie ponownie zgłoszenia, przedstawione przez Państwa ustawienia nie działają , chciałbym uzupełnić problem o brakujące dane

**Comment by arek1-618** [comment]
> Nie moge wyświetlić nowo utworzonego pola Podstawowy Adres email , powiązanego z modułem Kontrahenci w widoku do edycji w nowo utworzonym module - Zamówienia 

Pole "Wartości z modułu powiązanego" jest polem nieedytowalnym bezpośrednio przez użytkownika. Więc nie wyświetla się w widoku edycji. Wartości tego pola wyświetlają się tylko na liście.
