### ISSUE TITLE
Products gets imported without Image

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9135]
Hi, I am trying to import products from a csv file. I have mapped all the necessary fields. Now the products gets imported with all its fields except its image. This is the problem.

In my csv file the Image is a link as the Image is stored in another site.

In my yeti force installation, Image field is "Image File" 

Please help...

**Comment by indrabhusanroy** [comment]
Hi, I need to upload a lot of products, only easy option is to import products via a csv file. I cannot update each image individually and if I put put this picture by link to Description field, it does not works as it only shows the link and this link is not clickable. So If I need to see the image, then I will have to copy that link to view it in my browser. So how to solve this so that images gets imported via a csv file...

Thanks for your time...

**Comment by vovpff** [comment]
You need to put link with html markup. Also I'm not sure but I think you need allow domains of web sites of this links in configuration files to allow images. I can't help with this because never used this before.

**Comment by indrabhusanroy** [comment]
html markup is of no use here, I have tried that. Thanks

**Comment by vovpff** [comment]
I checked images inside descriptions fields and what what something works unwell:
`security.php`
```
	'CSP_ACTIVE' => true,
	// List of allowed domains for fields with HTML support
	'PURIFIER_ALLOWED_DOMAINS' => ['www.eurointech.ru', 'eurointech.ru'],
```
Pictures unavailable in this case. 

If `'CSP_ACTIVE' => true,` is false then pictures appear. @TomaszQr Any suggestions?

**Comment by indrabhusanroy** [comment]
Hi, I tried making 'CSP_ACTIVE' is false. After that when I add a image in description fields, its now accepting an image but when I save it, it disappears completely. It shows no image after I save.

**Comment by indrabhusanroy** [comment]
I also tried adding an image by this way: <img src="http://protocol8.com/mealplaninterf/wp-content/uploads/2018/10/lemon-water-1-e1540787934377.png" alt="lemon water" height="210" width="210">
It shows the image but if you save it disappears completely.

**Comment by indrabhusanroy** [comment]
Now I tried using: 
<a href="http://protocol8.com/mealplaninterf/wp-content/uploads/2018/10/lemon-water-1-e1540787934377.png">lemon water</a>

It does not shows the image only shows "lemon water" & this text "lemon water" cannot be clicked also.

**Comment by indrabhusanroy** [comment]
Here the above example can be clicked to view the image but it is not happening in description field...
