### ISSUE TITLE
access denied 

### ISSUE THREAD

**Issue by karamatf** [YetiForceCompany/YetiForceCRM#9143]
Dear ,

When i am saving the smtp settings i get access denied 

Version of yetiforce  [ver. 4.4.0]
Server Centos 7 
Php 7.2
Smtp : yandex 
![13eb2a85e98e9ed8](https://user-images.githubusercontent.com/20407825/51474738-e10d1700-1d88-11e9-8486-f51dd2581035.jpg)
![5883db5fa1b8424d](https://user-images.githubusercontent.com/20407825/51474745-e4080780-1d88-11e9-80b6-435b2d67ab21.jpg)

**Comment by karamatf** [comment]
We have done the rights on the folder and installed the oss mail patch and stilll the same issue tried to hard code the smtp details  on the config same issue seems like a product error ?

**Comment by karamatf** [comment]
Name | Path | Permission
-- | -- | --
Configuration directory | config/ | Allowed
Configuration file | config/config.inc.php | Allowed
User privileges directory | user_privileges/ | Allowed
Tabdata file | user_privileges/tabdata.php | Allowed
Menu file | user_privileges/menu_0.php | Allowed
User privileges file | user_privileges/user_privileges_1.php | Allowed
Logo directory | public_html/layouts/resources/Logo/ | Allowed
Cache directory | cache/ | Allowed
Address book directory | cache/addressBook/ | Allowed
Image cache directory | cache/images/ | Allowed
Import cache directory | cache/import/ | Allowed
Logs directory | cache/logs/ | Allowed
Session directory | cache/session/ | Allowed
Cache templates directory | cache/templates_c/ | Allowed
Cache upload directory | cache/upload/ | Allowed
Vtlib test directory | cache/vtlib/ | Allowed
Vtlib test HTML directory | cache/vtlib/HTML | Allowed
Cron modules directory | cron/modules/ | Allowed
Modules directory | modules/ | Allowed
Libraries directory | public_html/libraries/ | Allowed
Storage directory | storage/ | Allowed
Product image directory | storage/Products/ | Allowed
User image directory | storage/Users/ | Allowed
Contact image directory | storage/Contacts/ | Allowed
MailView attachments directory | storage/OSSMailView/ | Allowed
Roundcube directory | public_html/modules/OSSMail/ | Allowed

**Comment by karamatf** [comment]
[Server configuration System settings.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/2778960/Server.configuration.System.settings.pdf)

**Comment by karamatf** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/3521
https://github.com/YetiForceCompany/YetiForceCRM/issues/3788
These fixes have been tried no success

**Comment by rafalpospiech** [comment]
This problem could be fixed in the latest developement version of YetiForceCRM
Try setup smtp at gitdeveloper.yetiforce.com and let me know if problem still exists.

**Comment by karamatf** [comment]
![image](https://user-images.githubusercontent.com/20407825/51610873-87daea00-1f26-11e9-8d93-2721030ed177.png)
there it works

**Comment by rafalpospiech** [comment]
Update your version to current developement ver of YetiForceCRM or wait a while for stable reales and problem solved :)
