### ISSUE TITLE
Mysql Log in Yeti v2.0

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#915]
Again going back to the question of the correct server settings for yetiforce, found the net again, debian, apache, php, mysql, and again error on setting and changing the profile of the system settings. I started to understand and noticed one interesting thing I have a log file mysql goes to infinity with the following contents in the table vtiger_profile2field more than 25 pages of data, where to dig, where to look for the cause?

A feeling that Apache thinks that all end and an error data is not received, although mysql still performs queries

63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1301,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1302
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1302,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1199
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1199,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1196
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1196,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1194
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1194,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1192
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1192,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1190
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1190,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1188
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1188,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1186
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1186,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1184
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1184,0,0)
150 526 63 9:55:38 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1491
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1491,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1303
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1303,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1304
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1304,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1200
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1200,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1197
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1197,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1195
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1195,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1193
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1193,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1191
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1191,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1189
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1189,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1187
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1187,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1185
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1185,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1498
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1498,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1354
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1354,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1355
150 526 63 9:55:39 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1355,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1356
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1356,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 351
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 351,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 350
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 350,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 352
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 352,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 353
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 353,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 354
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 354,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 356
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 356,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 357
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 357,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 359
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 359,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 360
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 360,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 361
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 361,0,0)
63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 362
63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 362,0,0)

**Comment by KatarzynaUlichnowska** [comment]
Hello, 

the problem that you described requires a more extensive level of
analysis and probably access to your server. All known requirements have
been described and if there are any additional ones, we don't know about
them or they seem obvious to us. When we check servers of our customers,
we base our verification on a mechanism that is built-in to YetiForce
and used for checking server configuration and it has been enough so
far. 

We can have a closer look at this problem but next week. 
---

Z poważaniem / Kind regards
Katarzyna Ulichnowska

M: +48 884 310 123
E: k.ulichnowska@yetiforce.com

-------------------------

We created an innovative open source project called YetiForceCRM. You
can test it here [2], download [3] it for free or read its documentation
[4]. Follow us on Twitter [5] to get real-time info about new
functionalities and articles.

W dniu 2015-05-26 07:02, Алексей napisał(a): 

> Again going back to the question of the correct server settings for yetiforce, found the net again, debian, apache, php, mysql, and again error on setting and changing the profile of the system settings. I started to understand and noticed one interesting thing I have a log file mysql goes to infinity with the following contents in the table vtiger_profile2field more than 25 pages of data, where to dig, where to look for the cause? 
> 
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1301,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1302
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1302,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1199
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1199,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1196
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1196,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1194
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1194,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1192
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1192,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1190
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1190,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1188
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1188,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1186
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1186,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1184
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1184,0,0)
> 150 526 63 9:55:38 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1491
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1491,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1303
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1303,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1304
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1304,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1200
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1200,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1197
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1197,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1195
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1195,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1193
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1193,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1191
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1191,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1189
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1189,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1187
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1187,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1185
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1185,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1498
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1498,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1354
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1354,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1355
> 150 526 63 9:55:39 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1355,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 1356
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 1356,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 351
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 351,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 350
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 350,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 352
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 352,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 353
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 353,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 354
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 354,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 356
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 356,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 357
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 357,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 359
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 359,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 360
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 360,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 361
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 361,0,0)
> 63 Query DELETE FROM vtiger_profile2field WHERE profileid = '1' AND tabid = '21 'AND fieldid = 362
> 63 Query INSERT INTO vtiger_profile2field (profileid, tabid, fieldid, visible, readonly) VALUES ('1', '21', 362,0,0) 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/YetiForceCompany/YetiForceCRM/issues/915
[2] https://test.yetiforce.com/
[3] https://github.com/YetiForceCompany/YetiForceCRM
[4] https://yetiforce.com/en/documentation.html
[5] https://twitter.com/YetiForceEN

**Comment by waw555** [comment]
and you can give /etc/mysql/my.cnf file from the test server? I want to try your settings

**Comment by waw555** [comment]
Changed file modules \ Settings \ Profiles \ models \ Record.php following lines 620-621 and 632

It turned out like this, whether errors in this change?

foreach ($ fieldPermissions as $ fieldId => $ stateValue) {
/ * $ Db-> pquery ('DELETE FROM vtiger_profile2field WHERE profileid =? AND tabid =? AND fieldid =?',
array ($ profileId, $ tabId, $ fieldId)); * /
if ($ stateValue == Settings_Profiles_Record_Model :: PROFILE_FIELD_INACTIVE) {
$ Visible = Settings_Profiles_Module_Model :: FIELD_INACTIVE;
$ ReadOnly = Settings_Profiles_Module_Model :: IS_PERMITTED_VALUE;
} Elseif ($ stateValue == Settings_Profiles_Record_Model :: PROFILE_FIELD_READONLY) {
$ Visible = Settings_Profiles_Module_Model :: FIELD_ACTIVE;
$ ReadOnly = Settings_Profiles_Module_Model :: FIELD_READONLY;
} Else {
$ Visible = Settings_Profiles_Module_Model :: FIELD_ACTIVE;
$ ReadOnly = Settings_Profiles_Module_Model :: FIELD_READWRITE;
}
$ Sql ​​= 'UPDATE vtiger_profile2field SET (profileid, tabid, fieldid, visible, readonly) VALUES (?,?,?,?,?)';
$ Params = array ($ profileId, $ tabId, $ fieldId, $ visible, $ readOnly);
$ Db-> pquery ($ sql, $ params);
}

**Comment by waw555** [comment]
Strains next line

[Code] $ sql = 'UPDATE vtiger_profile2field SET (profileid, tabid, fieldid, visible, readonly) VALUES (?,?,?,?,?)';
$ Params = array ($ profileId, $ tabId, $ fieldId, $ visible, $ readOnly); [/ code]

there is no WHERE in

[Code] $ db-> pquery ('DELETE FROM vtiger_profile2field WHERE profileid =? AND tabid =? AND fieldid =?',
                        array ($ profileId, $ tabId, $ fieldId)); [/ code]

I can not as doperet his prisobachit here.

By the logic of the source code, delete data that match profileid =? AND tabid =? AND fieldid =?

[Code] $ db-> pquery ('DELETE FROM vtiger_profile2field WHERE profileid =? AND tabid =? AND fieldid =?',
                        array ($ profileId, $ tabId, $ fieldId)); [/ code]

And I have now updated the data is not clear what, as I understand it, too, need to use WHERE?

**Comment by KatarzynaUlichnowska** [comment]
Hello,
unfortunately we are not able to follow what is the problem and what is your question any more. Please expalin from the beginning why you opened a new issue, where is an error, how we can trigger it and why you are modifying anything in the code?
Please describe it clearly.
