### ISSUE TITLE
[PL] problem z yetirest

### ISSUE THREAD

**Issue by ArturGabrys** [YetiForceCompany/YetiForceCRM#9152]
#### Issue
Ogólnie, chce wykorzystać API żeby zaimportować konta z innego CRM'a, niestety już na początku mam problem z połączeniem się z webservice. Dostaje komunikat:

`Not Found
The requested URL /yeti/webservice/Accounts/Record/ was not found on this server.
REST Error ():`

Chyba, że możecie zasugerować jakieś inne rozwiązanie, chce zaimportować tylko dane kontaktowe i komentarze z poprzedniego CRM'a.

#### Screenshot of configuration
https://i.ibb.co/Bt4YX8c/yeti.png

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       |  4.4.0
| Web server (name and version) |  Apache
| PHP  | 7.2

W tym momencie yeti postawiony jest lokalnie, na wirtualnej maszynie TurnKey.

Dziękuję.

**Comment by bpabiszczak** [comment]
To jest open source, nawet jak czegoś nie ma to można szybko dodać :P
