### ISSUE TITLE
Increase Image size

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9155]
Hi, when I use the image field to add a image, The image that appears after saving is very small and does not looks good even thought it increases in size on clicking it. It will very king if you can help to increase the size a bit more as presently it looks very tiny.

Thanks...

**Comment by rafalpospiech** [comment]
![chrome_2019-01-23_10-58-53](https://user-images.githubusercontent.com/36499752/51598503-f3f52800-1efd-11e9-82f6-9915539978a0.jpg)
