### ISSUE TITLE
Missing Suddenly All Translations

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#916]
What Happened?
![trans](https://cloud.githubusercontent.com/assets/6897502/7806361/85636fb2-0388-11e5-921e-f11636874580.jpg)

**Comment by mariuszkrzaczkowski** [comment]
restored Trial test versa on, Please check now

**Comment by eptapsyxos** [comment]
Now GREEK LANGUAGE IS GONE....

**Comment by mariuszkrzaczkowski** [comment]
Test version is once for a couple of days cleaned and restored from backup.
We do not recommend creating a language pack there, creating a language to make the local version.

**Comment by eptapsyxos** [comment]
Οκ i have the file on my hard disk,
can i send it to you?
to restore it on test site so to have the ability to work and continue my process.
