### ISSUE TITLE
How to prevent a image from getting downloaded

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9170]
Hi, here Images can be downloaded. I don't want the images to be downloaded specially for guest users. Can this be done. Kindly help....

Thanks...

**Comment by indrabhusanroy** [comment]
Hi, I have a custom field Image using field type: Image File. Now after adding a Image when I click on the Image, the image pops up and it has a download option now. I don't want the download option or in the best case the image does not pops up on clicking.

![image download](https://user-images.githubusercontent.com/44740513/51668075-6e4da700-1fe7-11e9-9d66-cc99d490e27f.png)

**Comment by neuronetio** [comment]
@indrabhusanroy You can copy [this file](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/public_html/layouts/resources/fields/MultiImage.js) to `public_html/custom/layouts/resources/fields/MultiImage.js` (or something like that) and edit this file as you wish.
I think you could add another field to your module like `downloadable` and basing on this value you can change image field behaviour.

**Comment by indrabhusanroy** [comment]
solved..thanks
