### ISSUE TITLE
I can't add services or products to the calculation page

### ISSUE THREAD

**Issue by rtorrescodes** [YetiForceCompany/YetiForceCRM#9174]
Hi, im learning about YetiForce, and for now, i can add services and products to final quote, but not to the calculations page.

In documentation i can see, there's a place to add products and service that the quote will use.
(https://yetiforce.com/en/knowledge-base/documentation/user-documentation/item/3-calculations)

![1](https://user-images.githubusercontent.com/28415396/51649114-be296100-1f48-11e9-9de7-a1181a6e3bdd.JPG)

Can you help me?

**Comment by bpabiszczak** [comment]
![gh](https://user-images.githubusercontent.com/10197525/51828622-42cf0300-22ec-11e9-9a49-71652e99cc01.png)

**Comment by rtorrescodes** [comment]
Ok thanks, i add a new block and i see in managing an a advanced block there are the products fields, but i dont know how to drag those fields or that basic line product block to the calculations form in detail view layout.  As i understand, thats why calculation must have products and prices, so we can calculate an estimated quote before generate it.  Can you help me ?  Thanks a lot

**Comment by bpabiszczak** [comment]
new question = new issue
