### ISSUE TITLE
Multiple record selection 

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9189]
#### Actual Behavior: I have created call Field in contact module with 'Related field 1:M'  data type,
![1](https://user-images.githubusercontent.com/45963919/51726498-e2597f00-20bb-11e9-9cba-3fdf054b2bec.JPG)

 I want select multiple record at a time 

![4](https://user-images.githubusercontent.com/45963919/51726561-23ea2a00-20bc-11e9-88f9-9fb2285fd52b.JPG)

 but i can able to select  at a time one record how should i select multiple records at a time 

![3](https://user-images.githubusercontent.com/45963919/51726628-67449880-20bc-11e9-80f3-7b9073289efc.JPG)

#### How to trigger the error

1.
2.
3.

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       | 4.4.0
| Web server (name and version) |(apache)
| PHP  |7.1.x, 7.2.x (dev)
| Browser (name and version)  | Google chrome
| Operating System (name and version)  | windows 7
| Database (name and version) | mysql

**Comment by vovpff** [comment]
With 1:M you can select only one record. If you need M:M you need to add relation with some module and use this module tab in Detail View

**Comment by gopi12343** [comment]
is it possible in edit page ?

**Comment by gopi12343** [comment]
We have only 1:M relation ship in data type how should i create M:M relation ship? Please  give me example for how create M:M Relation 
![5](https://user-images.githubusercontent.com/45963919/51728290-d7a2e800-20c3-11e9-9b9f-a5882627a90d.JPG)

**Comment by vovpff** [comment]
you need to activate this param
https://github.com/YetiForceCompany/YetiForceCRM/blob/e3a2dbce628600e4fba11a36475dec866a8f4801/config/developer.php#L18
After that you achieve `Add Relation` button here:
https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&mode=showRelatedListLayout&block=2&fieldid=41

**Comment by gopi12343** [comment]
I have activated this relation we can able to create this relation in a detail page or summary page but i want create this relation in a edit page how should i create 

![editpage](https://user-images.githubusercontent.com/45963919/51813555-124a9180-230b-11e9-9716-a0ab706c043a.JPG)

**Comment by gopi12343** [comment]
I have created Call field with 1:M relationship,instead of that place i want M:M relationship field 
is it possible in yetiforce 

![3](https://user-images.githubusercontent.com/45963919/51821466-636b7d00-232d-11e9-9e55-16eca93beafa.JPG)
