### ISSUE TITLE
Issue: Calendar: incorret request

### ISSUE THREAD

**Issue by manwenick** [YetiForceCompany/YetiForceCRM#9190]
#### Issue
If user creates a task in calendar and try to save it, failure appears:
Incorrect request
Incorrect value detected, please contact your administrator

![calendar_incorrect_request](https://user-images.githubusercontent.com/34367573/51734452-e027fe00-2084-11e9-9cc7-da799027c70f.JPG)

If I create a task using the quick create, the task can be saved, but can not be changed. The same failure appears.

#### Actual Behavior
Failure appears if saving the task.
Failure appears if made changes and try to save. 

#### Expected Behavior
Task should be saved and no error should appear.

#### How to trigger the error
Create a task and try to change or create a task using quick create, save the task, open it again and try to change the date. 

#### Screenshot of configuration
![environment info1](https://user-images.githubusercontent.com/34367573/51734911-3ba6bb80-2086-11e9-912a-d6c9972fa5c7.JPG)
![environment info2](https://user-images.githubusercontent.com/34367573/51734912-3ba6bb80-2086-11e9-9165-338523ee9d69.JPG)
![dbinfo](https://user-images.githubusercontent.com/34367573/51734913-3c3f5200-2086-11e9-95d8-c713074e5e0c.JPG)
![systemstabilityinfo](https://user-images.githubusercontent.com/34367573/51734915-3c3f5200-2086-11e9-8209-f412740c601e.JPG)
![supportedlibraries](https://user-images.githubusercontent.com/34367573/51734916-3c3f5200-2086-11e9-93fd-c5340346927d.JPG)

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       | 4.4.0
| Web server (name and version) | Apache
| PHP  | 7.2
| Browser (name and version)  | firefox
| Operating System (name and version)  | Linux Ubuntu
| Database (name and version) | Maria DB

**Comment by rafalpospiech** [comment]
Clear your php error.log, trigger the error and paste content/ upload here.
On gitstable.yetiforce.com and gitdeveloper.yetiforce.com everything seems to be allright.
