### ISSUE TITLE
yetiforceportal2 not working getting error in language.php

### ISSUE THREAD

**Issue by studsu** [YetiForceCompany/YetiForceCRM#9202]
Here is the error log.<br><br><pre>[25-Jan-2019 14:47:32 Etc/GMT] PHP Fatal error:  Uncaught Error: Call to undefined method App\Config::get() in /public_html/xxxxxxxxx.com.com/crm/portal/app/Language.php:64
Stack trace:
#0 /public_html/xxxxxxxxx.com.com/crm/portal/modules/Base/View/Index.php(46): App\Language::getLanguage()
#1 /public_html/xxxxxxxxx.com.com/crm/portal/app/WebUI.php(101): YF\Modules\Base\View\Index-&gt;preProcess(Object(App\Request))
#2 /public_html/xxxxxxxxx.com.com/crm/portal/app/WebUI.php(69): App\WebUI-&gt;triggerPreProcess(Object(YF\Modules\Users\View\Login), Object(App\Request))
#3 /public_html/xxxxxxxxx.com.com/crm/portal/index.php(27): App\WebUI-&gt;process(Object(App\Request))
#4 {main}
  thrown in /public_html/xxxxxxxxx.com.com/crm/portal/app/Language.php on line 64</pre><br><hr>Generated by YetiforceCRM ver. 4.4.0<br>PHP: 7.1.18<br><br><strong>Server configuration errors:</strong><br>session.gc_maxlifetime: 1440<br>auto_detect_line_endings: Off<br><strong>Library errors:</strong><br>ldap_connect<br>opcache_get_configuration<br>apcu

domain is replaced by xxxxxxxx.com

**Comment by setras** [comment]
same problem, class App\Config extents \Conf\Config but  \Conf\Config is not loaded and I can not find the file

**Comment by dimitrisand** [comment]
Did you enter the correct values in config/config.php (portal)? API name password?

**Comment by bpabiszczak** [comment]
We are still working on this component, it can be tested here: https://gitdeveloper.yetiforce.com/portal/
