### ISSUE TITLE
A complete description of sharing a calendar with Thunderbird

### ISSUE THREAD

**Issue by websafe** [YetiForceCompany/YetiForceCRM#9203]
Hello!

I have a fresh installation. The user name is `admin666`.

I have some entries in my calendar (`User panel` -> `Virtual desk` -> `Calendar`).

My `config/api.php` looks like this:
```php
<?php
/**
 * API config.
 *
 * @copyright YetiForce Sp. z o.o
 * @license YetiForce Public License 3.0 (licenses/LicenseEN.txt or yetiforce.com)
 */
/* +********   active services   *********** */
//List of active services. To enable you must uncomment the appropriate line.
$enabledServices = [
    'dav',
    'webservices',
    'webservice',
];
/* +***************   DAV   **************** */
$enableBrowser = true;
$enableCardDAV = true;
$enableCalDAV = true;
$enableWebDAV = true;

/* +*********   Webservice config  ********* */
$API_CONFIG = [
    'ENCRYPT_DATA_TRANSFER' => false,
    'AUTH_METHOD' => 'Basic',
    'PRIVATE_KEY' => 'config/private.key',
    'PUBLIC_KEY' => 'config/public.key',
];
```

I've added a key in `System settings` -> `Integration` -> `DAV Applications`.
But the `Number of events` contains `0`...

`/dav.php/calendars/demo/YFCalendar/` returns:
```xml
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.2.2</s:sabredav-version>
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Principal with name demo not found</s:message>
</d:error>
```

`/dav.php/calendars/admin666/YFCalendar/` returns:
```xml
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>3.2.2</s:sabredav-version>
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Node with name 'YFCalendar' could not be found</s:message>
</d:error>
```

`/dav.php/calendars/admin666` requires me to login with admin666 and the defined key, then returns a site with:
```
Nodes
+ inbox | Collection, Inbox
+ outbox | Collection, Outbox
+ YFAddressBook | Collection, Calendar

Properties
....

Actions
Create new calendar
...
```

So in general my question: is there a place where I can see a step by step tutorial how to integrate my calendar  (`User panel` -> `Virtual desk` -> `Calendar`) into Mozilla Thunderbird? Because I tried almost every combination of url's, but nothing seems to work...

This tutorial https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-uzytkownika/item/integracja-systemu-z-mozilla-thunderbird is working but only when I use the demo instance (URL: https://gitdeveloper.yetiforce.com/dav.php/calendars/demo/YFCalendar/).
When I'm trying to achieve the same on my local instance by using url's like:
 + https://localhost/yetiforce/dav.php/calendars/demo/YFCalendar/
 + https://localhost/yetiforce/dav.php/calendars/admin666/YFCalendar/
 + https://localhost/yetiforce/dav.php/calendars/admin666/

I'm hitting the wall... Any help would be greatly appreciated.

**Comment by LOCOSP** [comment]
Same problem here, please help !

**Comment by mariuszkrzaczkowski** [comment]
In the last version there was an error in the name of the created directory, try this
https://localhost/yetiforce/dav.php/calendars/admin666/YFAddressBook/

**Comment by LOCOSP** [comment]
> In the last version there was an error in the name of the created directory, try this
> https://localhost/yetiforce/dav.php/calendars/admin666/YFAddressBook/

Yes, with above syntax I was able to configure Thunderbird with that calendar, and could create new records via thunderbird but it's not show up in yetis's calendar and all records created in yeti's calendar didn't show up in ```dav.php/calendars/admin666/YFAddressBook/```- no sync at all...

**Comment by mariuszkrzaczkowski** [comment]
do you have a working cron in CRM? attach a dump from configuration verification

**Comment by LOCOSP** [comment]
> do you have a working cron in CRM? attach a dump from configuration verification

Yes, cron is working ...

![yetiforce_settings](https://user-images.githubusercontent.com/4149309/52556393-b09b2480-2dec-11e9-896d-f46923293db1.png)

**Comment by mariuszkrzaczkowski** [comment]
you need to improve the server configuration
