### ISSUE TITLE
Chat Module Doesn't Display Correctly

### ISSUE THREAD

**Issue by acsinsurancegroup** [YetiForceCompany/YetiForceCRM#9204]
#### Issue
My Chat module looks nothing like the chat module in the current demo version. I took screenshots of both our system and your demo system but no upload function here. Basically the demo version the module is wide and has all of the options you would need for a chat and you can search participants, it's layed out properly etc. In our version it only shows on the right side of the screen and you cannot see any participants or search or anything. No way to tell if anyone is on or available. It's the original version that was launched and no updates.

#### Actual Behavior
Modules are different. Obviously the one in the Developer version has fixed everything from the original version we installed.

#### Expected Behavior
For our chat module to work like the one in the Yeti demo version.

#### How to trigger the error
Simply by clicking on the chat icon of our system.

#### Screenshot of configuration
Yes server configuration is setup perfectly without any errors. The only thing anywhere there marked in red is APCu which is optional and ours says No. Everything else is spot on and setup perfectly as it should be.

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       | v4.4.0 Complete Version
| Web server (name and version) | Plesk Onyx 17.8.11 on CentOS 7 Cloud Server
| PHP  | 7.2.14
| Browser (name and version)  | Google Chrome & Firefox both totally up to date.
| Operating System (name and version)  | Windows 10 fully up to date and Linux Mint 19 and Manjaro Linux 18.0.2
| Database (name and version) | 5.5.60-MariaDB

**Comment by paula-w** [comment]
The chat module is displayed correctly, but you're looking at two different versions. The chat you see in current dev version will be released in version 4.5 (probably this week) and after you update your CRM it will look and work the same way it now does in the dev version.

**Comment by paula-w** [comment]
Not yet, we will make an announcement here on GitHub and on all our social media once we release it.

**Comment by acsinsurancegroup** [comment]
@paula-w Thank you :)
