### ISSUE TITLE
Comment export

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#9206]
#### Issue

Exporting account, contact,lead,competition list, partner list doesn't include comments tagged to it. 

If this is actual behavior, How can we export the comments attached to accounts,lead,competition list, partner list, Vendors? 

#### Actual Behavior

The export doesn't include comments

#### Expected Behavior

The comments should be included in the output file

#### How to trigger the error

1. Export accounts, lead,competition list, partner list
2. The export file has no Comments section

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       | 
| Web server (name and version) |
| PHP  |
| Browser (name and version)  | 
| Operating System (name and version)  | 
| Database (name and version) |

**Comment by vovpff** [comment]
@maninvatsa now solution only to export comments manually from database.

**Comment by paula-w** [comment]
Right now you can import/export comments via API, however, we're planning to change that in the future.

**Comment by maninvatsa** [comment]
So I have to export 3000 or more comments manually and restore them manually? 

I hope you would understand how tedious it would be. 

Also, The comments are related to different modules, Can you image How long it would take to restore them manually?

My system is broken and I had to redo the whole thing again and Now i have to redo the comment?

**Comment by maninvatsa** [comment]
> Right now you can import/export comments via API, however, we're planning to change that in the future.

@paula-w , Do you have any support documents for exporting the comments via API?

**Comment by paula-w** [comment]
I don’t know between what systems you are transferring the data but you have to write a script that will do that. Right now comments can’t be exported/imported using the built-in tool to import/export data.
