### ISSUE TITLE
Share With Users:    Chosen Users DISAPPEARS

### ISSUE THREAD

**Issue by andrewchaosun** [YetiForceCompany/YetiForceCRM#9208]
There is a Share With User field in Contacts, however, after I chose the users to share with the contact, it disappears and the Share With Users choice leaves as blank. <br><br>​​​​​​​<br><hr>Generated by YetiforceCRM ver. 4.4.0<br>PHP: 7.1.18<br><br><strong>Server configuration errors:</strong><br>session.gc_maxlifetime: 1440<br>auto_detect_line_endings: Off<br><strong>Library errors:</strong><br>ldap_connect<br>opcache_get_configuration<br>apcu

**Comment by andrewchaosun** [comment]
![image](https://user-images.githubusercontent.com/46634935/51804315-3c17a000-229a-11e9-904b-f326d6d2bcb4.png)

**Comment by andrewchaosun** [comment]
![image](https://user-images.githubusercontent.com/46634935/51804326-4fc30680-229a-11e9-9e1e-85e75110495a.png)

**Comment by rafalpospiech** [comment]
Try to trigger this error on gitdeveloper.yetiforce.com.
It seems that this bug was resolved in developer version already. 
We will publish new version very soon.
I'm closing this issue, but if problem still exists we will reopen it.
Feel free to write here.

**Comment by andrewchaosun** [comment]
That is great. I will update it to version 5.

cheers,

andrew

**Comment by andrewchaosun** [comment]
great. So when do you predict the new version will be officially published?

**Comment by mariuszkrzaczkowski** [comment]
today maybe tomorrow

**Comment by bpabiszczak** [comment]
today or tomorrow

**Comment by andrewchaosun** [comment]
> today maybe tomorrow

Many thanks for your hard work. Looking forward to that.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.0.0
