### ISSUE TITLE
I can't add product fields in calculation form, using advanced mode.

### ISSUE THREAD

**Issue by rtorrescodes** [YetiForceCompany/YetiForceCRM#9218]
#### Issue
I can't add product fields in calculation form, using advanced mode.  I can see the fields i need to use but i dont know how to drag them to the detail view layout. I've created a new block, i can add custom fields but i want to have the normal product, unit, price lines to make what i think calculation module is made for.... calculations before making a quote.  Thanks @mariuszkrzaczkowski

#### How to trigger the error

1.
2.
3.

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       | 
| Web server (name and version) |
| PHP  |
| Browser (name and version)  | 
| Operating System (name and version)  | 
| Database (name and version) | 

 #9174

**Comment by mariuszkrzaczkowski** [comment]
Have you tested on the development version?

**Comment by vovpff** [comment]
@rtorrescodes as I written in #9174 looks like something wrong with your installation. Calculations should be advanced as standard.
![image](https://user-images.githubusercontent.com/8545791/51833702-3f964000-2309-11e9-851f-910d27c9d929.png)
![image](https://user-images.githubusercontent.com/8545791/51833721-52a91000-2309-11e9-9f5a-732d68687695.png)
Try this `Managing an advanced block`

**Comment by rtorrescodes** [comment]
![12](https://user-images.githubusercontent.com/28415396/51873841-51391100-2324-11e9-9508-2a3292d46cec.JPG)
Thats my problem.  Calculation never has that product line.  I made another installation and i don't have that options.   In advanced mode i see the same screen you add.  But i dont know how to drag those options or product line to the calculation form.  Thanks

**Comment by vovpff** [comment]
You have 4.3 system updated to 4.4? I will try to find for you solution in some hours.

**Comment by rtorrescodes** [comment]
Ok ok its fixed now, i really really thank you so much for this. I love Yeticrm and now its 100% useful.
By the way, im using 4.4 installed on cpanel softaculous. You can close this issue and i'll work more active here to help somehow. Thanks again.

**Comment by vovpff** [comment]
@rtorrescodes you are welcome
