### ISSUE TITLE
Fetch price of another module 

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9223]
Hi, when I  am using the FInvoiceCost Module there is a option to add products. Now on selecting a products,its unit price gets automatically fetched. Now here In addition to products I have added payments out module, so that I can select a payments out just like a products, but when I select a payment out, it does not fetch it price. How to do this.

Thanks...

**Comment by indrabhusanroy** [comment]
solved

**Comment by jjbautist1** [comment]
solution?
