### ISSUE TITLE
Error in new type recurring event

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#9228]
Hello friends

There's a bug in calendar creating an event

First we create new type of events:

![image](https://user-images.githubusercontent.com/40429279/51873851-a5f57f80-2356-11e9-99ba-7586e5bec8a5.png)

Later we try to create a new event, with recurring dates:

![image](https://user-images.githubusercontent.com/40429279/51873908-d4735a80-2356-11e9-8a03-61c20b9aab82.png)

Just when clickin on Save button we get this error:

![image](https://user-images.githubusercontent.com/40429279/51873946-ef45cf00-2356-11e9-8ad2-919cb0b08a59.png)

This only happens with new type of event, with the default ones there's no problem.

#### Actual Behavior
We get the error detailed above

#### Expected Behavior
Must create recurring of new type of events

#### How to trigger the error
Explained avobe
1.
2.
3.

#### Screenshot of configuration
We get no issues in configuration

#### PHP/Apache/Nginx/Browser/CRM Logs
No log founded reporting this error

```
Logs
```

#### Your Environment
Centos 7 x64 with Apache 2.6 and Php 7.1 MariaDb 
| YetiForce   4.4 this error happened too in 4.3
|

**Comment by TomaszQr** [comment]
In current version (on https://gitdeveloper.yetiforce.com) it works properly. 
![activity_types](https://user-images.githubusercontent.com/14273211/51909473-06270880-23cd-11e9-85e7-8ac53bee0f93.gif)

**Comment by santyabreu** [comment]
Thank you @TomaszQr 

What files should I change from the 4.4 stable to make it work while 5.0 is developed?
