### ISSUE TITLE
Calendar New Defined personalized status cannot be changed

### ISSUE THREAD

**Issue by santyabreu** [YetiForceCompany/YetiForceCRM#9229]
Hello Friends

We need to work with more event status, as we did in Vtiger. In our system of work the status can be changed all the time keeping the same time and hour due to multiple departaments handling the calendar. In this moment (we dont understand why) you only admit Held, Pospose, Cancel statuses.

We have defined this statuses:
![image](https://user-images.githubusercontent.com/40429279/51874552-60868180-2359-11e9-9733-0ed633f73f53.png)

When creating a new event the status is greyed out, and when trying to change to any personalized status is not possible. We consider this a bug, so we can define personalized status that we cannot work with.

![image](https://user-images.githubusercontent.com/40429279/51874376-9840f980-2358-11e9-9693-81ad619d02d4.png)

Maybe free this lock sould make a solution for us, or maybe in this screen adding more buttons (need procedure to code this) to change the status:

![image](https://user-images.githubusercontent.com/40429279/51874422-caeaf200-2358-11e9-8a48-8dedd88f3138.png)

We have been trying rounding ideas to adapt us to this, but it is impossible. Need any solution please!

#### Actual Behavior
Cannot handle personalized event status

#### Expected Behavior
We consider a bug, after configure them we must be able to use them.

#### PHP/Apache/Nginx/Browser/CRM Logs
No log error reported

```
Logs
```

#### Your Environment
Centos 7 Apache 2.6 Php 7.1 Mariadb

| YetiForce       4.4
| Web server (name and version) |
| PHP  |
| Browser (name and version)  | 
| Operating System (name and version)  | 
| Database (name and version) |

**Comment by paula-w** [comment]
You want  to complicate things that are already too complicated for regular users. 
The calendar has to synchronize with many other calendars (outlook, thunderbird, mobiles). Your statuses are artificial and it would make more sense for you to work with a different module (eg. “internal tickets”), then you have more control over what’s going on.

**Comment by santyabreu** [comment]
@paula-w really?

We solvet it, and it is working... and in fact. **There is a bug on this status modules**. When you put an space in the status between words, the calendar brings error when updating. Putting a "_" or "-" or simply a status with no spaces the calendar does the job perfectly.

It is not artificial, just personalized and the system brings open option to do this. Ah!! and it syncronizes perfectly. Perhaps you sould investigate a bit (only a bit) before handling tickets so light. 

Thank you so much! 

@bpabiszczak  could you mark this to bug please (if you consider)

**Comment by mariuszkrzaczkowski** [comment]
can you give an example?with screenshot

**Comment by santyabreu** [comment]
Of course, 

![image](https://user-images.githubusercontent.com/40429279/62083835-c643bf80-b24f-11e9-8e05-50dc9e653a49.png)

In type of activity the fields have to be with no spaces. 
I'm going to ser a event
![image](https://user-images.githubusercontent.com/40429279/62084008-16228680-b250-11e9-84d1-d0032d83da5b.png)

That is saved correctly, now I will change activity

![image](https://user-images.githubusercontent.com/40429279/62084057-2dfa0a80-b250-11e9-8bda-596bebbb52f8.png)

Done, it works!!!
I you put an space in those new fields, the system return an error

Best Regards, and thank you for your fast reply

**Comment by vovpff** [comment]
How you input names of picklist values? Directly when addind? This is not so correct condition. Also bug with space is here.
You can add value like picklistvalue1 and add translation for it.

**Comment by bpabiszczak** [comment]
This is not a solution, you've changed one thing [incorrectly] and you've broken some others.
