### ISSUE TITLE
What framework is used on YetiForce?

### ISSUE THREAD

**Issue by cltvchannel** [YetiForceCompany/YetiForceCRM#9240]
Hi,
What framework is used to develop YetiForce?
And what programming languages?

(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Comment by bpabiszczak** [comment]
**Framework:**
- Vtiger
- YetiForce
- https://david-dm.org/YetiForceCompany/YetiForceCRM

**Programming languages:**
![lang](https://user-images.githubusercontent.com/10197525/51920037-e4d21680-23e4-11e9-9974-76a93708a2bb.png)

**Comment by cltvchannel** [comment]
Thanks !
