### ISSUE TITLE
Custom module - Add image wont work

### ISSUE THREAD

**Issue by fetti** [YetiForceCompany/YetiForceCRM#9245]
#### Issue
I created a new custom mode. I added an Image filed, but when I'm uploading an image, after I save the picture wont show.

#### Actual Behavior
After saving the new record I only see just an empty square, and I couldn't see the image and I can't download it. In a premade module, like Products, the image field works well.

#### How to trigger the error

<img src="http://www.kepfeltoltes.eu/images/2019/01/937yetiforce.gif"/>

**Comment by TomaszQr** [comment]
In current version it works properly.
Can you trigger bug on https://gitdeveloper.yetiforce.com ?
