### ISSUE TITLE
Hide menu from guest users

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9247]
Hi, Is there a way to hide menu items from guest users. see the image below
![image](https://user-images.githubusercontent.com/44740513/51942033-12967a00-243c-11e9-9123-c79175dc93ee.png)
I understand that modules can be made private and I have done the same so that guest users cannot access them but still they can see a menu which they have no access to. These looks bad, it would be better if these modules can be made hidden.
Thanks...

**Comment by indrabhusanroy** [comment]
Thanks, I got it now....

**Comment by drakub** [comment]
> 
> 
> Thanks, I got it now....

How did you do this?

**Comment by drakub** [comment]
> 
> 
> You can change menu for every different role in the system. Where is a problem?

How is this done in Yetiforce 6.1.0?

**Comment by vovpff** [comment]
@job-bob-draku https://gitdeveloper.yetiforce.com/index.php?module=Menu&view=Index&parent=Settings

**Comment by drakub** [comment]
> 
> 
> @job-bob-draku https://gitdeveloper.yetiforce.com/index.php?module=Menu&view=Index&parent=Settings

Thanks a lot. This work very well.

**Comment by drakub** [comment]
> 
> 
> @job-bob-draku https://gitdeveloper.yetiforce.com/index.php?module=Menu&view=Index&parent=Settings

Can you help on how to escalate tickets in YetiForce. I kinda failed to get it

**Comment by vovpff** [comment]
@job-bob-draku I has never used this in the past. What is it?
