### ISSUE TITLE
Graphical calendar view not showing new Event

### ISSUE THREAD

**Issue by wrobeltomasz** [YetiForceCompany/YetiForceCRM#9251]
Add a new Event in the calendar and assigns it to another user.
Event is not visible on the graphical calendar.

![1](https://user-images.githubusercontent.com/46556533/51971272-0aa8fb00-2479-11e9-99a3-3f18dd0bd2c6.gif)

When i save the event again using the owner's account.
Event is appears in the graphic calendar.
 
![2](https://user-images.githubusercontent.com/46556533/51971298-1c8a9e00-2479-11e9-832d-1d88db604994.gif)
 
 
Browser name and version:
Firefox 64
Environment name and version:
CRM version: 4.4.
PHP 7.2.14
Operating System and version:
Linux x86_64

**Comment by poradz** [comment]
Have you tried to trigger this error on https://gitdeveloper.yetiforce.com/index.php ?

It seems, that this error is fixed in the developer version.

**Comment by wrobeltomasz** [comment]
Yes, I tried on gitdeveloper, no error. 
Do you know when the 5.0 version will be available for download?
