### ISSUE TITLE
Brak możliwości zalogowania się po instalacji.

### ISSUE THREAD

**Issue by jacentys** [YetiForceCompany/YetiForceCRM#9261]
#### Actual Behavior

Świeża instalacja YF. Pod koniec okno "trwa instalacja" nie zmienia się.
Po kilkudziesięciu minutach otwieram drugie okno przeglądarki, pokazuje mi się formularz logowania.
Wpisanie użytkownika / hasła skutkuje komunikatem: Niepoprawna nazwa użytkownika lub hasło.

#### Expected Behavior

Możliwość zalogowania się.

#### How to trigger the error

1. Instalacja na czystym systemie wszystkich składników.
2. Edycja php.ini tak by wartości były zgodne z wytycznymi
3. Odpalanie instalacji - wszystko ok. do momentu po wpisaniu danych firmy. Okno "wisi"
4. Próba logowania się - komunikat o błędzie.

#### PHP/Apache/Nginx/Browser/CRM Logs

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       |  4.4
| Apache | 2.4
| PHP  | 7.2
| Safari  | 
| Ubuntu 18.0.4  | 
| MySql 5.7
[phpinfo.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/2812824/phpinfo.pdf)
 |

**Comment by bpabiszczak** [comment]
W logach instalacji [o ile były włączone] widać czy system zainstalował się poprawnie [do końca] czy nie. Pewnie się nie zainstalował poprawnie.

**Comment by jacentys** [comment]
Zapewne tak. Logi instalacji? Chodzi o logi apach-e?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/9022#issuecomment-451073137

https://github.com/YetiForceCompany/YetiForceCRM/blob/6bb53abeddd56543e815ca46f94961f8a7252e21/config/debug.php#L9-L77
Set the configuration so and try to call error
```php
'LOG_TO_FILE' => true,
'LOG_LEVELS' => ['error', 'warning'],
'LOG_TRACE_LEVEL' => 9,
'SQL_DIE_ON_ERROR' => true,
'DEBUG_CRON' => true,
'SMARTY_ERROR_REPORTING' => E_ALL & ~E_NOTICE,
'JS_DEBUG' => true,
'DISPLAY_EXCEPTION_BACKTRACE' => true,
'DISPLAY_EXCEPTION_LOGS' => true,
'EXCEPTION_ERROR_LEVEL' => E_ALL & ~E_NOTICE,
'DAV_DEBUG_EXCEPTIONS' => true,
'DAV_DEBUG_PLUGIN' => true,
'WEBSERVICE_SHOW_ERROR' => true,
'WEBSERVICE_DEBUG' => true,
'MAILER_DEBUG' => true,
```
If there are no logs then changle this code
```php
// Turn on the error handler
'EXCEPTION_ERROR_HANDLER' => true,
// Save logs to file (cache/logs/errors.log)
'EXCEPTION_ERROR_TO_FILE' => true,
// Display errors
'EXCEPTION_ERROR_TO_SHOW' => true,
```

attach all files from the catalog "cache/logs"

**Comment by mariuszkrzaczkowski** [comment]
Logi prosimy nie załączać na github (mogą zawierać poufne dane np. dane dostępowe) tylko wysłać na adres github@yetiforce.com

**Comment by jacentys** [comment]
No i jasne. Nieprawidłowe hasło przy instalacji - nie zwróciłem uwagi na ostrzeżenie o złym formacie hasła, a proces instalacyjny nie zatrzymuje, tylko przepuszcza dalej co skutkuje błędem przy logowaniu. Dziękuję, temat można zamknąć.
BTW. Wyskakuje w google kilka instrukcji na temat instalacji YF na ubuntu podających linki do archiwum YF wersji bodajże 3. Logicznie rzecz biorąc jeśli w linku zmienię numer na aktualny, powinna ściągnąć się wersja aktualna. Niestety ściąga się jakaś inna wersja (update?) co skutkuje pustym ekranem przy próbie zainstalowania - trochę czasu mi zajęło aby zorientować się że chodzi o to, a nie błędy w php czy ustawieniach serwera www. Można by umieścić takie info aby ktoś się nie męczył przez kilka godzin....

**Comment by bpabiszczak** [comment]
A mogę prosić o zrzut ekranu gdzie widać te linki?

**Comment by jacentys** [comment]
Po wpisaniu do przeglądarki "yetiforce ubuntu" pierwsze 2 link np.:
https://www.rosehosting.com/blog/install-yetiforce-crm-on-ubuntu-16-04/
https://www.globo.tech/learning-center/install-yetiforce-crm-ubuntu-16/

wskazują na pliki:
wget https://github.com/YetiForceCompany/YetiForceCRM/archive/3.1.0.zip

**Comment by bpabiszczak** [comment]
Dziękuję, zerkniemy co tam ludzie piszą :P Dla nas jedyne źródło aktualnych plików znajduje się pod tym adresem: https://github.com/YetiForceCompany/YetiForceCRM/releases tam zawsze najnowsza wersja jest na górze. 

Ogólnie powinno się ściągać plik oznaczony YetiForceCRM-4.4.0-complete.zip
