### ISSUE TITLE
User Modules

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9266]
#### Issue:  How can i enable user module for workflows
My CRM
![user module1](https://user-images.githubusercontent.com/45963919/52038062-1f72b500-2585-11e9-82c7-31250bb4bb7d.JPG)

Yetiforce CRM:![user module2](https://user-images.githubusercontent.com/45963919/52038073-27325980-2585-11e9-99a0-9ebabe507a23.JPG)

#### How to trigger the error

1.
2.
3.

#### PHP/Apache/Nginx/Browser/CRM Logs should be sent to github@yetiforce.com

```
Logs
```

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce       | 4.4
| Web server (name and version) |apache
| PHP  |7.1.x, 7.2.x
| Browser (name and version)  | Google chrome
| Operating System (name and version)  | Windows 7
| Database (name and version) | Mysql

**Comment by paula-w** [comment]
We added that in the dev version and it will be published together with the next stable version.

**Comment by gopi12343** [comment]
ok

**Comment by TomaszQr** [comment]
In new version, the system send notifications about new user
Added via https://github.com/YetiForceCompany/YetiForceCRM/pull/9089

**Comment by gopi12343** [comment]
Which means , is it possible in this  version  or next new version

**Comment by vovpff** [comment]
@gopi12343 next new

**Comment by gopi12343** [comment]
ok thanks
