### ISSUE TITLE
Workflow calculation

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#9267]
Hello all ! 

    I am trying to create a new workflow, that calculates two fields.
    I am using this formula : 
                        Update fields -> Expression -> predare-eu-incarcare - preluare-eu-incarcare
    Fields are integer types and i need the result in other integer field. 
   PS : predare-eu-incarcare is the field name.
   PPS : what i need is A minus B

**Comment by vovpff** [comment]
`Update fields -> Expression -> predare-eu-incarcare - preluare-eu-incarcare` This is not works proper?

**Comment by liviubbo** [comment]
No. :( I have tried about 20 times. With space, without space.

**Comment by liviubbo** [comment]
I have renamed fields from preluare-eu-incarcare to preluareeuincarcare , all of the fields. I have re-added the workflow with this new fields, and nothing happens. I have added with space, without space. 

 Ex workflow : preluareeuincarcare-predareeuincarcare (i have tried with space between minus sign and without space)

**Comment by liviubbo** [comment]
Its working. Sorry, i didnt see that ive selected FIELD not EXPRESSION. Thank you all for your help.
