### ISSUE TITLE
[PL] Numerowanie faktur           

### ISSUE THREAD

**Issue by aplauz** [YetiForceCompany/YetiForceCRM#9289]
Dzień dobry, 

1. Jak zresetować numerowanie w następnym miesiącu? Znalazłem tego typu pytanie z 2016 jednak odpowiedzi nijak nie mogę odnieść do wersji YF4. 
2. Wszelkie próby walki z problemem sprawiły, że mam już wygenerowanych X pustych faktur. Niestety nie mogę zostawić takiej dziury w numeracji. Gdzie w bazie jest zapisana aktualny numer żeby go cofnąć? 
3. Jak wstawić fakturę jeszcze z zeszłego miesiąca?

Actual Behavior
Używaj prefiksu: NR
Początek sekwencji*: 1
Używaj postfiksu: /{{MM}}/{{YY}}

Wygląda to tak, że mam:
NR 1/01/2019
NR 2/02/2019

Expected Behavior
Potrzebna mi jest zmienna dla resetowania automatycznie numeracji w każdym nowym miesiącu
Faktura VAT NR 1/01/2019
[...]
Faktura VAT NR 13/01/2019
Faktura VAT NR 1/02/2019
Faktura VAT NR 2/02/2019
itd.

Your Environment: Yetiforce 4.0.0

**Comment by rafalpospiech** [comment]
Ustawienia -> Moduły standardowe -> Moduły prefixy -> Resetowanie sekwencji
Tylko ta opcja jest chyba w nowszej wersji dopiero, w której nie pamiętam.

![chrome_2019-02-01_11-03-57](https://user-images.githubusercontent.com/36499752/52116533-a9685f80-2611-11e9-8a8b-1494de4ac6c6.jpg)

**Comment by aplauz** [comment]
Dziękuję Panie Rafale za podpowiedź :) Czyli to ta wersja developer?
Można ja zainstalować na wersję 4.0.0 żeby jakoś nie stracić danych i ustawień a kontynuować pracę (coś jak aktualizacja) ?

**Comment by mariuszkrzaczkowski** [comment]
Tak można, do każdej wersji jest paczka aktualizacyjna, dostępna na:
https://github.com/YetiForceCompany/UpdatePackages/tree/master/YetiForce%20CRM%204.x.x
