### ISSUE TITLE
[PL] Problem z aktualizacja 4.0.0 do 5.0.0

### ISSUE THREAD

**Issue by aplauz** [YetiForceCompany/YetiForceCRM#9297]
Dzień dobry,

ściągnąłem aktualizację 4.0.0 do 5.0.0 jednak podczas aktualizacji wyświetla komunikat: Niepowodzenie - Moduł nie zawiera domyślnego języka systemu (en_us).
To samo się dzieje po zmianie języka podstawowego na Polski.
Pobrałem paczki językowe z YetiForceCompany/YetiForceCRMLanguages ale wciąż to samo.
Co robię niewłaściwie?

![zrzut ekranu 2019-02-1 o 14 45 28](https://user-images.githubusercontent.com/46876516/52126639-2c98ae00-2630-11e9-9617-179e096891a6.png)

![yetiforce_settings](https://user-images.githubusercontent.com/46876516/52126771-88fbcd80-2630-11e9-8eac-832989afc664.png)

Fragment loga:
2019-02-01 13:50:06.2799 [warning] - Language file does not exist, module: Settings//Vtiger ,language: pl_pl
2019-02-01 13:50:06.2837 [warning] - Language file does not exist, module: Settings/Vtiger ,language: pl_pl
2019-02-01 13:50:06.3182 [warning] - Language file does not exist, module: ModuleManager ,language: pl_pl
2019-02-01 13:50:06.3337 [warning] - Language file does not exist, module: Password ,language: pl_pl
2019-02-01 13:50:06.3374 [warning] - Language file does not exist, module: ApiAddress ,language: pl_pl
2019-02-01 13:50:06.3529 [warning] - Language file does not exist, module: Chat ,language: pl_pl
2019-02-01 13:50:06.3685 [warning] - Language file does not exist, module: Vtiger ,language: pl_pl
2019-02-01 13:50:06.196 [info][application] - 
$_GET = []
$_POST = [
    '__vtrftk' => 'sid:dd8dce0377fe9a54a078f48294dfee28a144f027,1549028721'
    'module' => 'ModuleManager'
    'parent' => 'Settings'
    'view' => 'List'
]
$_FILES = []
$_COOKIE = [
    'YTSID' => 'ee9c3a4947312a283cecc44cbf90bf8b'
]
$_SESSION = [
    'last_activity' => 1549029006.1966
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 1
    'app_unique_key' => 'd7fae58dd99d5dc58f13fee076aa28f2e47aa2bb'
    'user_name' => 'irek'
    'full_user_name' => 'XXX'
    'fingerprint' => '8e5604af-99db-47a5-b5e9-465040486690'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
    ]
]
$Libs = [
    0 => 'apcu'
]====================================================================================================================================

**Comment by mariuszkrzaczkowski** [comment]
wersji 5.0 jeszcze nie ma, które paczki zostały wgrane i skąd pobrane ?

**Comment by aplauz** [comment]
Stąd Panie Mariuszu: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%204.x.x/4.4.0_to_5.0.0

Generalnie wciąż walczę z numeracją faktur. Niestety wersja 4.4.0 nie posiada jeszcze tego co Pan mi przesłał rano. Dlatego w rozpaczy ściągam już co popadnie :(

**Comment by bpabiszczak** [comment]
a nie prościej wziąć u nas chmurkę? Za 65 euro jest spory VPS [360GB na dane], wsparcie, bezpłatne aktualizacje. A jeżeli za drogo, to też da się coś z tym zrobić.
PS.: aktualizacje robi się z wersji na wersje czyli z 4.0 > 4.1 > 4.2 > 4.3 > 4.4

**Comment by aplauz** [comment]
Pewnie byłoby prościej Panie Błażeju ale już płacę za serwer i wolałbym mieć wszystko w jednym miejscu. Drugi argument jest taki, że wykorzystuję Wasze narzędzie może w 1% bo prowadzę działalność jednoosobową (w zasadzie do faktur). Zrozumiałe, że nie mam potrzeby rozdzielania zadań i używania całej masy ciekawych funkcjonalności, które umożliwia Wasz system. Swoją drogą fantastyczny. Mówiąc inaczej ... to jeszcze nie ten czas.

Ja chciałbym tylko zaktualizować do takiej wersji, która umożliwi mi resetowanie numerów faktur po zmianie miesiąca 1/01/2019, 1/02/2019 itd. ale nie wiem, który plik pobrać żeby zaktualizować do 4.4.156. W zasadzie to wszystko na tę chwilę.

**Comment by bpabiszczak** [comment]
Tutaj jest instrukcja: https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/aktualizacja-systemu

Wszystkie paczki aktualizacyjne są w tym folderze: https://github.com/YetiForceCompany/UpdatePackages

Aktualizacja to niestety trudny proces [hostingi mocno ograniczają serwery robiąc różne limity, co powoduje często błędy przy aktualizacji].

**Comment by bpabiszczak** [comment]
Musisz pobrać paczki dla każdej wersji niezależnie, np. z 4.0 do 4.1 znajduje się pod tym adresem: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%204.x.x/4.0.0_to_4.1.0/zip
