### ISSUE TITLE
Field Mapping Not Functioning for Non Admin Users

### ISSUE THREAD

**Issue by mjapple** [YetiForceCompany/YetiForceCRM#9302]
### ⁉️ Describe the bug

I would like to thank everyone for such an amazing software, well done and much of appreciation.
What I am currently facing is the mapping option which is very very useful and again thanks. Mapping this wonderful option is available only for admin currently means any non admin user can not use this option even if i select their profile(role) at the end of making new mapping. 

### 🔥 How to trigger the error

1. Click on Setting

1. Click on setting
2. Go to Standard Modules
3. Mapping
4. Create any new mapping and define the conditions and on step 4 for "permissions" select the proper groups to have access to the mapping
5. Go to the defined module and open the record. (since i did not put any condition for my mapping it should appear on all records)
6. Try to generate the new record from this current record

### 👎 Actual Behavior

Actual behavior is the non admin users can not see the option of "generating new record on top right corner" but the admin can see, if i change the specific user to admin then she/he can see the "generate" option as well

Please see the gif below ⬇️ 
[http://xiasste.com/files/1.gif](url)
[http://xiasste.com/files/2.gif](url)
[http://xiasste.com/files/3.gif](url)
![screen shot 2019-02-02 at 2 40 23 pm](https://user-images.githubusercontent.com/6837503/52163205-895f9b80-26f8-11e9-8077-50a283efad85.png)
`app.js?s=1534963798:1549 {"success":false,"error":{"code":403,"message":"LBL_PERMISSION_DENIED","trace":""}}`
`POST http://192.168.9.2/index.php 403 (LBL_PERMISSION_DENIED)`
`LBL_PERMISSION_DENIED`
`{"success":false,"error":{"code":403,"message":"ERR_NOT_ACCESSIBLE","trace":""}}`
`app.js?s=1534963798:1555 ERR_NOT_ACCESSIBLE`
`POST http://192.168.9.2/index.php 403 (ERR_NOT_ACCESSIBLE)`

This is the error from the Chrome Browser 

### 👍 Expected Behavior

Expected behavior is the users those who are in the group which is selected in the mapping to have the option of "generate"
### 📷 Screenshot of configuration

![screen shot 2019-02-02 at 2 31 12 pm](https://user-images.githubusercontent.com/6837503/52163159-ad6ead00-26f7-11e9-93e7-61cc7aa19269.png)
![screen shot 2019-02-02 at 2 30 52 pm](https://user-images.githubusercontent.com/6837503/52163161-ae9fda00-26f7-11e9-845e-4ca1d5a26c80.png)
![screen shot 2019-02-02 at 2 30 42 pm](https://user-images.githubusercontent.com/6837503/52163162-b0699d80-26f7-11e9-9148-1d8d99dc1a11.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

[phpError.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2824310/phpError.log)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  4.3.0
| Web server (name and version)|	Mac OS X Self Host	| 
| PHP  |				7.1				| 
| Browser (name and version)  | Chrome		| 
| Operating System (name and version)  | 	macos High Sierra	| 
| Database (name and version) | 	MYSQL	|

**Comment by rafalpospiech** [comment]
Try to trigger this error on gitdeveloper.yetiforce.com (passwords are the same as user names).
It seems this problem was resolved already in newer version.
You need to update your version.
If problem still exists we will reopen this issue. 
Feel free to write here anyway.
