### ISSUE TITLE
How can we create an new conversion button 

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9304]
# 🐞 bug report

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by rskrzypczak** [comment]
You can try use Mapping panel:
![image](https://user-images.githubusercontent.com/10221999/52191982-a656b480-2847-11e9-8d58-6f4245fe57fb.png)

**Comment by gopi12343** [comment]
Now i am able to converting from account to contact but in lead to account whenever  we save the  Lead record  status is for conversion then automatically conversion button will appear but in my custom conversion is not working is like that ,the button is  appearing   after the reload the entire page ,how the conversion button will appear automatically

**Comment by vovpff** [comment]
@gopi12343 go here https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&view=List&block=2&fieldid=95 and click `Add Mapping`
