### ISSUE TITLE
Error when printing pdf-template

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#932]
Printing pdf-template from modules does not work in 2.0

**Comment by florek41** [comment]
Any details ? Blank page ?
What you have in logs ? (https://yetiforce.com/en/ideas,-changes,-bugs/bugs/115-debugging.html)
I have problem with this element too, but I don't know thas this is the same problem.

**Comment by amicheals** [comment]
I have the same issue. I'm wondering if it is a problem with permissions.

**Comment by kpaulaha** [comment]
Yes blank page. Must check logs when time. But it did not work on test.yetiforce either.

**Comment by florek41** [comment]
I don't have access to my installation right now, but i remeber that - problem is with default language - try to set lang in settings ( not user but system ) and it should works. Waiting for results :)

**Comment by kpaulaha** [comment]
Nope, changing the default language has no effect. I have the same problem on all servers Have to go deeper in the problem during weekend.

**Comment by kpaulaha** [comment]
test.yetiforce.com gives this:

![pdf](https://cloud.githubusercontent.com/assets/10330264/7879200/fa370374-05f6-11e5-8948-85e3f9485b2a.png)

**Comment by MaciejStencel** [comment]
This particular error shown by kpaulaha was fixed few days ago in revision 2.0.20.

https://github.com/YetiForceCompany/YetiForceCRM/commit/71b6e9d601211118fc1cfce8d981c81232dec144

You can review there changes and use this fix. For now it is YF developer git, soon will be pushed to master.
