### ISSUE TITLE
Where can i  create login email account in OSSMail module 

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9322]
# 🐞 bug report:  Where can i  create login email account in OSSMail module, i din't find any OSSMail  module in module  installation page
![ossmail](https://user-images.githubusercontent.com/45963919/52256597-6f79bf00-296b-11e9-888c-84a2ee266174.JPG)

![instalation](https://user-images.githubusercontent.com/45963919/52256342-6f2cf400-296a-11e9-869e-6e2bcba28c44.JPG)

### ⁉️ Describe the bug: Actually whenever i am trying login into OSSMail module,  i am getting login failed error  how can i login into this OSSMail module 

![my mailbox](https://user-images.githubusercontent.com/45963919/52256503-042fed00-296b-11e9-8de5-5b045ee7685e.png)
 

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 4.4
| Web server (name and version)|	Apache	|
| PHP  |						7.2 		| 
| Browser (name and version)  | 	google chrome 	|
| Operating System (name and version)  | windows 7 	|
| Database (name and version) | 	MySQL 	|

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by mariuszkrzaczkowski** [comment]
Duplicate https://github.com/YetiForceCompany/YetiForceCRM/issues/9335
