### ISSUE TITLE
Error 500  when installing client portal 

### ISSUE THREAD

**Issue by teka325** [YetiForceCompany/YetiForceCRM#9323]
Hi I tried following the instruction of installing the client portal but I get the error 500 on the browser, how can i fix this?

**Comment by setras** [comment]
@teka325 have a look at issue #9202 it may help
make sure that the configuration variable $config['crmPath'] ist set to a valid URL. The default value causes a Error 500

**Comment by dimitrisand** [comment]
Check that te appkey name and portal are correct in the config/config.php of portal

**Comment by bpabiszczak** [comment]
A stable version of the portal will appear in version 5.2
