### ISSUE TITLE
[BUG][PL] Brak walidacji pól

### ISSUE THREAD

**Issue by rskrzypczak** [YetiForceCompany/YetiForceCRM#933]
Tworząc rekord w dowolnym module, nie występuje walidacja pól znajdujących się w bloku, który jest zwinięty.
![bug2](https://cloud.githubusercontent.com/assets/10221999/7832052/3ea8999c-045c-11e5-922e-466fbd342e7d.jpg)

**Comment by bpabiszczak** [comment]
O ile wiem, to bloki które mają pola wymagane nie powinny się zwijać [a przynajmniej tak to działało]. Pytanie czy jeżeli zaczniemy takie zwinięte bloki walidować czy system nam rozwinie blok i pokaże pole które nie jest wypełnione tak jak jest w przypadku bloków rozwiniętych.
