### ISSUE TITLE
[bug] MY Mailbox login 

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9335]
# 🐞 bug report: Whenever i trying to login my mailbox that time i am getting the Login failed  error Please tell me which username and password i need to give first time Login into my mailbox. 
![my mailbox](https://user-images.githubusercontent.com/45963919/52319451-d5bf1a00-2a1d-11e9-8278-877ebe78c3dd.png)
Please help me anybody 
### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/52325536-9bd22180-29e5-11e9-8f6d-d52b34bcbdb3.jpg)

**Comment by gopi12343** [comment]
# 🐞 bug report: Whenever i trying to login my mailbox that time i am getting the Login failed  error Please tell me which username and password i need to give first time Login into my mailbox. 
![my mailbox](https://user-images.githubusercontent.com/45963919/52319451-d5bf1a00-2a1d-11e9-8278-877ebe78c3dd.png)


Software configuration -Mail tools-Mail – Scanner

![ossmail](https://user-images.githubusercontent.com/45963919/52326521-0b273000-2a3d-11e9-864c-e8964d2b6b7c.JPG)

Software configuration -Standard modules-Modules – Installation


While Login to email account in OSSMail module that time i got LBL_HANDLER_NOT_FOUND error 

![my mail box](https://user-images.githubusercontent.com/45963919/52326516-0793a900-2a3d-11e9-86f9-c2573f6fd64f.JPG)


### ⁉️ Describe the bug: 











### 🔥 How to trigger the error


Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### 👎 Actual Behavior


### 👍 Expected Behavior


### 📷 Screenshot of configuration


### 📝 PHP/Apache/Nginx/Browser/CRM Logs



### 🌍  Your Environment 



| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 4.4
| Web server (name and version)|	(apache)	|
| PHP  |			7.1.x, 7.2.x (dev)					|
| Browser (name and version)  | 	Google chrome 	|
| Operating System (name and version)  | 	Windows 7	|
| Database (name and version) | Mysql		|

### ❓ Additional context
Add any other context about the problem here.

**Comment by mariuszkrzaczkowski** [comment]
Check if you have the latest version of the module and whether it is active

![image](https://user-images.githubusercontent.com/10198654/52327180-747e5300-29eb-11e9-9aa9-5e24a2b57306.png)

**Comment by gopi12343** [comment]
How could i Check  the latest version of the module

![1](https://user-images.githubusercontent.com/45963919/52327340-ea140e80-2a3f-11e9-9e78-59c0d3297525.JPG)

I if click on the my mailbox module configuration that time i got below error 
![my mail box](https://user-images.githubusercontent.com/45963919/52327385-1039ae80-2a40-11e9-8140-15e8ce608c9a.JPG)

if click on mail scanner module configuration  that  time i got below page 
![ossmail](https://user-images.githubusercontent.com/45963919/52327409-20ea2480-2a40-11e9-9ef1-9b9563b50c1b.JPG)

**Comment by gopi12343** [comment]
Hi yetiforce teams still i am facing the same problem.

**Comment by mariuszkrzaczkowski** [comment]
is this a version updated to 4.4.0?

**Comment by gopi12343** [comment]
I  updated this version on 24-11-2018 
![updates system settings](https://user-images.githubusercontent.com/45963919/52392989-55b9b280-2af8-11e9-9dde-638b211aebd1.png)

**Comment by mariuszkrzaczkowski** [comment]
send us a log in there you will see which file is not found

**Comment by gopi12343** [comment]
sorry i am not getting you, which log you are asking for

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/52395737-875a5b80-2aaf-11e9-88e0-09e2757d8e4a.png)

**Comment by gopi12343** [comment]
Please give me two days i will send error log file

**Comment by z0lo13** [comment]
there is no bug, configure first you server in roundcube setting, then login > your record will appear in mailscanner and autologin

**Comment by pagosasia** [comment]
have configured settings in roundcube with my gmail and tried to login OSSMail with my gmail account also failed. It keeps getting "Login Failed"
