### ISSUE TITLE
Migration from VTiger 6.2 to Yetiforce 2.0

### ISSUE THREAD

**Issue by yodacohen** [YetiForceCompany/YetiForceCRM#935]
Possible to write up instructions on how to perform migration from VTiger 6.2 to Yetiforce 2.0?
Using Google translate to translate to Polish, so please pardon any language mistakes!

Można napisać instrukcje jak wykonać migrację z vTiger 6.2 Yetiforce 2,0 ?
Za pomocą Google Translate przetłumaczyć na polski , więc proszę wybaczyć ewentualne błędy językowe !
dziękuję!

**Comment by KatarzynaUlichnowska** [comment]
Hello,
Google Translate did a good job with the Polish translation but we understand English too so you can just write in EN.
The process of migration is very simple and is similar to updates in Vtiger. That means you upload a clean version of YetiForce 2.0, select migration on the first screen and then you specify paths to Vtiger in the next steps. 
Soon, the manual will appear on our website.

**Comment by yodacohen** [comment]
Hello Katarzyna, 

Ok, have attempted to install 2.0 using migration from VTiger 6.2. 
I get a login screen after install and launch from url. 

I get the following error: 

Fatal error : Can't use function return value in write context in /home/crmsanit/public_html/yetiforcetest2/include/Webservices/Utils.php on line 1005 


Am attaching referenced file. 

Would you mind having a developer take a look? Directory and all sub directories are set for PHP 5.4. The previous version was installed by my hosting company, Siteground, techs, after some adjustments, and I am impressed. The only issue I immediately noted was strange labels on days of week on calendar display.: 

JS_MON JS_TUE JS_WED JS_THU JS_FRI JS_SAT JS_SUN 

I really like Yetiforce and am going to show it to some businesses in Houston, Texas, where I live. 

Thank you very much, 

Roy Cohen 
roymcohen@comcast.net 
www.crmsanity.com 

----- Original Message -----

**Comment by yodacohen** [comment]
Katarzyna, 

I just noticed I am getting this error at top of login page: 

Deprecated : mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/crmsanit/public_html/yetiforcetest2/libraries/adodb/drivers/adodb-mysql.inc.php on line 476 


Would you mind forwarding this, along with my other email, to developer? 

Thanks again, 

Roy Cohen 
Houston 
roymcohen@comcast.net 



----- Original Message -----

**Comment by yodacohen** [comment]
Katarzyna, 

I have also attached here my config.ini.php file. This is the error I am now getting: 

Fatal error : Can't use function return value in write context in /home/crmsanit/public_html/yetiforcetest2/include/Webservices/Utils.php on line 1005 

There is a reference to default language and it is my understanding that the default language is set in the config.ini.php file. It appears in this file to be set correctly as en_us . 

I have also commented out the sql port number, as my host, Siteground.com, says it should not be there in Siteground's server configuration. It was removed for the earlier version of Yetiforce and allowed proper installation and functionality. 

I have noticed that in Vtiger 1.4.206 RC the config.ini.php sits in the top directory folder. Here it is sitting in the config folder under the top directory Yetiforce folder. Why the difference? 

My suspicion is that the error has nothing to do with server settings and everything to do with conversion from Vtiger 6.2 . 

Would very much like to get this resolved so that I may demonstrate the software next week! 

Thank you, 

Roy Cohen 
Houston 

----- Original Message -----

**Comment by KatarzynaUlichnowska** [comment]
Hello Roy!
1. I suggest you to download a clean version of Vtiger 6.2 and then download a stable version of YetiForce. Enable logs during the migration process to see whether everything goes well. When you finish, verify if files and database match the clean version of YetiForce.
2. The error that you reported was related to PHP 5.4 and has been solved 
https://github.com/YetiForceCompany/YetiForceCRM/commit/881ec76759396e272f4d5cfe4624c002f1e7a986  [verify it also on 5.5 and 5.6] and when you have a spare moment we recommend these articles: 
- https://yetiforce.com/en/developer-documentation/bugs/126-how-to-report-bugs.html 
- https://yetiforce.com/en/developer-documentation/bugs/115-debugging.html 
3. Labels have been fixed too in the latest version [thanks for reporting it].
4. Please read this as well: http://stackoverflow.com/questions/13944956/the-mysql-extension-is-deprecated-and-will-be-removed-in-the-future-use-mysqli,
We are going to change the engine for communication with database to PDO.
5. We have changed the structure of the system [it inherited too much mess from Vtiger] and we will continue changing it in the future. 

NEXT TIME PLEASE ADD BUGS IN SEPARATE ISSUES, NOT ALL IN ONE :)
Different developers are responsible for solving different problems so it will be easier for them and faster for you :)
