### ISSUE TITLE
[bug] Roundpoint Composing Email Failure

### ISSUE THREAD

**Issue by bryan190** [YetiForceCompany/YetiForceCRM#9352]
# 🐞 bug report

### ⁉️ Describe the bug

Setup my mail client within yeti.  Emails are being received and mirror round cube from cpanel, yet anything being sent out just hangs on sending message popup notification, and then fail.  Emails are being sent without issue from within cpanel.

Get failure email returned to email

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  admin@site.com
    No Such User Here

Even though the email was sent to a different address.  Not sure where it is pulling this email from and replacing the one placed in to: field.

### 👎 Actual Behavior

Failure to send email, smtp settings all check out.

### 👍 Expected Behavior

Successful email sent

### 📷 Screenshot of configuration

https://ibb.co/47xN2gw
https://ibb.co/pZvS2rZ

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|   4.3
| Web server (name and version)|	cpanel	|
| PHP  |		7.2.13
| Browser (name and version)  | 	chrome	|
| Operating System (name and version)  | 	windows 10	|
| Database (name and version) | 	10.0.38-MariaDB	|

**Comment by mariuszkrzaczkowski** [comment]
Check if the error exists in the dev version
