### ISSUE TITLE
Strict Standards: Only variables should be assigned by reference in

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#937]
Finally what this crm need to work?
I cant even load the install page...

a bundge of line refering several issues starting with the phrase

Strict Standards: Only variables should be assigned by reference in

HELP!

**Comment by eptapsyxos** [comment]
With php 5.5 i get a lot of errors... with php 5.4 less but still can continue

Strict Standards: Only variables should be assigned by reference in /var/sites/m/medicross.gr/public_html/YetiForceCRM-master/include/database/PearDatabase.php on line 20

Strict Standards: Only variables should be assigned by reference in /var/sites/m/medicross.gr/public_html/YetiForceCRM-master/include/database/PearDatabase.php on line 21

Strict Standards: Declaration of AntlrLexer::matchAny() should be compatible with BaseRecognizer::matchAny($input) in /var/sites/m/medicross.gr/public_html/YetiForceCRM-master/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::recover() should be compatible with BaseRecognizer::recover($input, $re) in /var/sites/m/medicross.gr/public_html/YetiForceCRM-master/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /var/sites/m/medicross.gr/public_html/YetiForceCRM-master/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrLexer::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /var/sites/m/medicross.gr/public_html/YetiForceCRM-master/libraries/antlr/AntlrLexer.php on line 297

Strict Standards: Declaration of AntlrParser::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /var/sites/m/medicross.gr/public_html/YetiForceCRM-master/libraries/antlr/AntlrParser.php on line 98

Strict Standards: Declaration of AntlrParser::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /var/sites/m/medicross.gr/public_html/YetiForceCRM-master/libraries/antlr/AntlrParser.php on line 98

Fatal error: Can't use function return value in write context in /var/sites/m/medicross.gr/public_html/YetiForceCRM-master/modules/Users/Users.php on line 927

**Comment by bpabiszczak** [comment]
https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/3558ad8f7a02a07489f0e8e643a13f4b33e4c9c6
