### ISSUE TITLE
How do I unlink "Opportunity" on a Quotation?

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#9372]

**Comment by bpabiszczak** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=LayoutEditor&parent=Settings&view=Index&sourceModule=SQuotes

**Comment by MyBlissIT** [comment]
Hi, When I open the "Edit" field and Mark Opportunities as "Inactive", this adversely affects the "Account" call-up command.

In that, the "Account" command on the Quotation becomes unselectable
