### ISSUE TITLE
[Question] Cost of Goods Sold

### ISSUE THREAD

**Issue by sapper6fd** [YetiForceCompany/YetiForceCRM#9399]
I've been able to enter our products and pricing into YetiForce, but I don't see anywhere that I can associate our cost of those goods with each of the products in the the CRM.  Is there somewhere I'm I haven't looked yet to enter these costs?  Does YetiForce track these detail and build margin reports based off of sales? 

I'm running version 4.4.0 just as an FYI

**Comment by sapper6fd** [comment]
Any updates on this?

**Comment by bpabiszczak** [comment]
> Does YetiForce track these detail and build margin reports based off of sales?
No
