### ISSUE TITLE
Multiple Branch 

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#9418]
### Description

How can We setup multiple branch option?

I tried staging branch options but I guess I did something wrong. I tried adjusting the Roles and The the accounts can still be accessed from other users. 

How do I completely separate accounts Branch to Branch?

Thanks

**Comment by maninvatsa** [comment]
Any guess what should be done for Multi Branch setup?

**Comment by vovpff** [comment]
What you mean as Branch?

**Comment by maninvatsa** [comment]
We have multiple offices located in different locations. How can we setup different branches for the organization?

**Comment by maninvatsa** [comment]
Does any one have any idea? I'm trying to setup multiple branches under one installation. 

https://prnt.sc/mkhxku

Thanks.

**Comment by maninvatsa** [comment]
We have a Head Office and three sub offices or Branch. All the Branch works independently.  Every offices has Branch head and Other Employees are working under the Branch Head. The Branch head is responsible for running all the other Sales, Support, Inventory etc. The data in the branch are unique and the users too.

How can I setup YetiForce to ensure the same modules can be used by multiple branches and the Employees can maintain separate entity.  I can actually install multiple instances but It would need a lot of resource which totally beats the goal of having a central system to manage the customers. 

I am trying to achieve the model below in the diagram. 
![screenshot 2019-02-16 at 02 28 48](https://user-images.githubusercontent.com/21019034/52890690-27db0a80-3197-11e9-8bdd-43c814754e12.png)

If anyone has acheived the model, I would be glad to hear from you. 

Thank you.

**Comment by mariuszkrzaczkowski** [comment]
one of the possibilities is to mapping in the roles of your structure, modules to be made private

https://gitdeveloper.yetiforce.com/index.php?module=Roles&parent=Settings&view=Index&block=1&fieldid=2

first you map branches and then the structure in a given branch

**Comment by maninvatsa** [comment]
Thank you Marius. 

Can you please send me any links to read about the roles and structure? I have read about the roles and structure on Vtiger. It didn't seems to answer too much. 

Modules being private meaning the settings below? I tried making it private and all the user's except admin were blocked from accessing any modules. It's weird but I'm yet to play with the settings. 

![screenshot 2019-02-16 at 21 01 09](https://user-images.githubusercontent.com/21019034/52903404-07aa5a80-322e-11e9-97f8-e7d8a4d4b3f4.png)

**Comment by maninvatsa** [comment]
Any updates?

**Comment by maninvatsa** [comment]
> one of the possibilities is to mapping in the roles of your structure, modules to be made private
> 
> https://gitdeveloper.yetiforce.com/index.php?module=Roles&parent=Settings&view=Index&block=1&fieldid=2
> 
> first you map branches and then the structure in a given branch

Can you please elaborate on it?

**Comment by paula-w** [comment]
All the documentation we have can be found on our website - https://yetiforce.com/en/knowledge-base/documentation
In a public module everyone can see everything, and in a private module users can only see their own records, and records they have access to because of the configuration (eg supervisor sees subordinates’ records).
If there’s anything else you want to get an answer to please open a new issue for each of these questions/problems.
