### ISSUE TITLE
1:M relationship

### ISSUE THREAD

**Issue by gopi12343** [YetiForceCompany/YetiForceCRM#9429]
# 🐞 bug report
In the below screen short, we have 1:M relationship field is contact ,That contact field contain the Account,lead,employee,Competition,partner and vendors, i want to remove partner,competition from that  Contact field  ,where can i remove that please help 
![remove module](https://user-images.githubusercontent.com/45963919/52613022-4bc0f680-2ee0-11e9-83fd-0137c562dbdb.JPG)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 4.4
| Web server (name and version)|	Apache	|
| PHP  |					7.2			|
| Browser (name and version)  | 	Google chrome	|
| Operating System (name and version)  | 	Windows 7	|
| Database (name and version) | 	MySQL	|

**Comment by vovpff** [comment]
@gopi12343 I'm not sure what this is the bug. You can remove this relations manually from database.

**Comment by gopi12343** [comment]
ok
