### ISSUE TITLE
[Question]  If statement in workflow calculation

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#9433]
Hello all ! 

     I want to calculate some fields with IF statement.
     So i have this : 

    A-B -> if the result is NOT zero then  add result at C and substract from D
  
    Another example : 
    C - initial value = 5
    D - initial value = 2
    (A) 7 - (B) 5 = 2  then (C) equals 7 and (D) equals 0
    Another example : 
    C - initial value = 5
    D - initial value = 2
   (A) 7 - (B) 7 = 0 then C and D remains the same.

**Comment by konadrian** [comment]
In workflows you have the possibility to add your own methods where you can write your code in PHP. So you can add a new workflow task which will calculate it for you.
