### ISSUE TITLE
[bug] Language downloading not working proper

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9466]
# 🐞 bug report

### ⁉️ Describe the bug

langpack downloading don't add new language to list. 

### 🔥 How to trigger the error

1. Go to 'language manager'
2. Click on 'download language'
3. Pick any available language by clicking download 
4. ?!

### 👎 Actual Behavior

New languages does not appear in list

### 👍 Expected Behavior

language should be downloaded and available to use/edit

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  gitdev 5.0.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mariuszkrzaczkowski** [comment]
fixed https://github.com/YetiForceCompany/YetiForceCRMLanguages/commit/a2c96a9546960b5c719c71d39922479456051716
