### ISSUE TITLE
Milestone for new UI        

### ISSUE THREAD

**Issue by laportem** [YetiForceCompany/YetiForceCRM#9475]
### Description

Hi there

Can you confirm which milestone the new UI described in #8255 is coming out
We are evaluating a CRM for an upcoming project and Yeti meets the criteria but the current UI feels cluttered and outdated. The propose one looks friendly.

**Comment by paula-w** [comment]
This is what we would call an outdated interface:  http://epe.si/pl/screenshots/ 
The current version supports the newest technologies, including the latest version of bootstrap; you can say the appearance is „raw”, but not „outdated” for sure. The vast amount of options makes the system seem cluttered, but you can disable/change 95% of these things, so customization possibilities are great. 
We do know that some changes are required (currently we’re planning migration to Vue + Quasar) but this is a very large system and changing its appearance requires several months of work. The appearance will change for sure, but we’re not able to tell you if it’s going to be in 3, 6, or 9 months.
