### ISSUE TITLE
YetiForce 5.0 is out! 🎉

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#9477]
The long awaited **version 5.0** is finally here. Thank you for your patience!

Our community keeps growing every day and we would like to **thank all of you** for all your support and effort. We wouldn’t have gotten this far without you. Every single contribution, pull request, suggestion, and issue helps us develop the system for you and motivates us to work every day.  

As some of you know, we recently joined **Crowdin**, which is a platform that allows the community to translate various applications to various languages. If you’d like to see YetiForce translated to your language - now it’s easier than ever before!  If you want to find out more, take a look at this issue: https://github.com/YetiForceCompany/YetiForceCRM/issues/9104

**LOG**
There have been several significant changes in this version that we believe will make your work with YetiForce even easier. The most noteworthy being: 
- A new chat that accelerates your sales
- A new mechanism to generate PDF files
- A new calendar
- Twitter integration 
- A new panel to manage your backups
- A  new Gantt view

* the entire changelog can be found on our [website](https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/yetiforce-5-0) 

**LINKS**

* https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.0.0
* https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/5.0.0/
* update package: https://github.com/YetiForceCompany/YetiForceCRM/issues/9477#issuecomment-463639175

**UPDATE & REQUIREMENTS**
We would like to remind everyone that updates should first be executed on a test version, and only then on the production version (you should always have a backup copy of your environments).

* The list of current web server requirements necessary for version 5.0 to work properly can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements)
* A detailed description of the installation process can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-update)

**Comment by cltvchannel** [comment]
@paula-w  When will be avabile on Softaculous?
Thanks !

**Comment by liviubbo** [comment]
Hello ! 
     When will the update packages be available for download ?

**Comment by mariuszkrzaczkowski** [comment]
🎉🎉The update package has been released🎉🎉
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.0.0
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%204.x.x/Update%20packages/

**Comment by paula-w** [comment]
@cltvchannel  Hi! unfortunately that's not up to us, it's entirely up to Softaculous. We asked them and they said it might take up to 4 days.

**Comment by paula-w** [comment]
@cltvchannel version 5.0 is now available on softaculous :)
