### ISSUE TITLE
[bug] Multifilter widget broken

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9479]
# 🐞 bug report

### ⁉️ Describe the bug

Multifilter widget does not save of filter condition when page refreshed or widgets tab changed.

### 🔥 How to trigger the error

![multifilter widget](https://user-images.githubusercontent.com/8545791/52718876-85affc80-2fb5-11e9-851c-83efccadfd46.gif)

### 👎 Actual Behavior

Every time widget window empty

### 👍 Expected Behavior

Actual condidtion should be saved

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  gitdev 5.0.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by adudekyeti** [comment]
Hi,
If you want to have permanent list on MultiFilter you have to set filter in widget management:
![2019-02-21_10-51-39](https://user-images.githubusercontent.com/39482453/53159910-1e9ed300-35c7-11e9-9eff-89da01747db2.gif)

If you want to have it temporary (until logout) you can use cache option:
![2019-02-21_10-57-39](https://user-images.githubusercontent.com/39482453/53160138-9bca4800-35c7-11e9-8b4a-b57fb7410708.gif)
