### ISSUE TITLE
reporting tool

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#9480]
I can't find the reporting tool in 5.0, I don't know where it is, thank you.

**Comment by cakrina** [comment]
Is there an issue to track New Reports Module progress?
#8706 #7513 are both closed as question is answered, but is it really a question? Missing reports module is  a big issue for many and simply answering "Yes we working on it, and soon it will be released" and closing an issue only to get same question again later don't seam to be very logical. How do one check if Module is planned/scheduled for release in 5.1 ?

**Comment by bpabiszczak** [comment]
Status: suspended

**Comment by paula-w** [comment]
This is @bpabiszczak 's comment:

We expanded the filter mechanism to allow users to display data from other modules. On top of that, charts can handle data from other modules than the main module. In our opinion both mechanisms (filters + widgets) give you the old reports functionality (of course it’s not exactly the same thing, but it can substitute the old module in 95%). Right now we’re not planning to add any changes to this functionality until we have a client who is willing to pay for developing the mechanism further.
