### ISSUE TITLE
[bug]  5.0.0 Broken WYSIWYG

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#9484]
# 🐞 bug report

### ⁉️ Describe the bug
Impossible to add WYSIWYG widget to any module

### 🔥 How to trigger the error

1. Go to https://gitstable.yetiforce.com/index.php?module=Widgets&parent=Settings&view=Index&block=2&fieldid=58
2. Click on Add Widget
3. Scroll down to WYSIWYG
4. ADD
5. See that nothing happened

### 👎 Actual Behavior
Dont work

### 👍 Expected Behavior
Work

### 📷 Screenshot of configuration
Dev and stable git

### ❓ Additional context
I am not sure that 5.0.0 is stable update to use on production crm. The size of the widget after the update was too high, i wanted to recreate a widget, but now it disaperead at all

Take a look on record with a WYIWYG field https://gitstable.yetiforce.com/index.php?module=Leads&view=Detail&record=267&mode=showDetailViewByMode&requestMode=full&tab_label=LBL_RECORD_DETAILS

**Comment by vovpff** [comment]
I can approve what this bug in gitdev 5.0.0

**Comment by z0lo13** [comment]
@rskrzypczak @mariuszkrzaczkowski 

WYSIWYG

adding uncountable <br> if the table added, in both widget view and details view

**Comment by vovpff** [comment]
1 bug = 1 issue
