### ISSUE TITLE
Errors Creating Profile

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#9485]
# 🐞 bug report
I had this issue before and the developers ignored it. Now it's on the https://gitdeveloper.yetiforce.com/ 
Please look into to this urgently. We can't add any new profiles. We are literally stuck. 
### 🔥 How to trigger the error

1. Go to '...'https://gitdeveloper.yetiforce.com/
2. Click on '....' Add profile 
3. Scroll down to '....'Save profile

### 👎 Actual Behavior

Some default profiles are missing and The new profile doesn't save the permissions. It gives cross to almost all the settings. 

### 👍 Expected Behavior
It should save all the privileges to the profile. 

![yeti bs 23](https://user-images.githubusercontent.com/21019034/52753719-de5cb500-3008-11e9-89fb-fed93b4bbf27.gif)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mariuszkrzaczkowski** [comment]
check if the error occurs on https://gitstable.yetiforce.com because we have started the PHP 7.3 test and it is not completely configurable

**Comment by maninvatsa** [comment]
It worked fine in the https://gitstable.yetiforce.com. 

What is the issue here? PHP 7.3 or Server configuration?

**Comment by mariuszkrzaczkowski** [comment]
it has not been configured correctly yet so there are problems
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65

**Comment by mariuszkrzaczkowski** [comment]
the php configuration for gitdev has been fixed

**Comment by arek1-618** [comment]
Tests have shown that everything is fine now.
