### ISSUE TITLE
Bugs in version 2.0

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#949]
mistakes which we have already corrected, repeated again in version 2.0

for example

Not saved mail address where to send a message about backing up
![backup](https://cloud.githubusercontent.com/assets/1402355/7883084/26b08746-062d-11e5-8f46-f8d695c4cbf6.JPG)

Do not save the parameters responsible for the inclusion of a folder with backups in the backup
![backup2](https://cloud.githubusercontent.com/assets/1402355/7883093/45a076f2-062d-11e5-9d29-9d7e5c025887.JPG)

Backup does not work
![backuparhive](https://cloud.githubusercontent.com/assets/1402355/7883107/66b1bacc-062d-11e5-8f28-5f135bb34dda.JPG)

Save button for some reason is not translated in previous versions has been translated like
![bruteforce](https://cloud.githubusercontent.com/assets/1402355/7883126/7e7d62a0-062d-11e5-8446-12a7f581c36b.JPG)

The file htaccess, obviously not correct the data specified in the documentation https://yetiforce.com/en/administrator-documentation/instalation/103-web-server-requirements.html
![htaccess](https://cloud.githubusercontent.com/assets/1402355/7883145/98af5b9c-062d-11e5-8b96-d82c8e584962.JPG)

Again translation is not enough
![leadname](https://cloud.githubusercontent.com/assets/1402355/7883166/cb2a4c8a-062d-11e5-8950-ee199f4dd428.JPG)

Notification settings are not saved
![maillogs](https://cloud.githubusercontent.com/assets/1402355/7883174/dd11e2fa-062d-11e5-9033-31536ac434eb.JPG)

phpError.log scored warnings
![phperrorlog](https://cloud.githubusercontent.com/assets/1402355/7883185/f195342a-062d-11e5-8b2d-faac0c5e58c4.JPG)

Server configuration is not displayed correctly, all parameters are set to the recommended
![server configuration](https://cloud.githubusercontent.com/assets/1402355/7883199/0d5709b8-062e-11e5-9521-5a4ea225d535.JPG)

Do not add to the details of the field
![companydetails](https://cloud.githubusercontent.com/assets/1402355/7883214/38e1faca-062e-11e5-97f7-085dfae0ddb4.JPG)

**Comment by KatarzynaUlichnowska** [comment]
It’s possible that some of the changes weren’t uploaded from lab or dev version to master branch, we will check it and will make any necessary corrections.
It’s a pity that you didn’t create separate issues because these things are different and different developers will take care of different problems.

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/issues/984 - Save button for some reason is not translated

**Comment by mariuszkrzaczkowski** [comment]
Fixed  https://github.com/YetiForceCompany/YetiForceCRM/issues/987 - The file htaccess, obviously not correct the data specified in the documentation

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/issues/988 - Again translation is not enough

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/issues/989 - Notification settings are not saved

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/issues/992 - Server configuration is not displayed correctly

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/issues/993 - Do not add to the details of the field

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/issues/996 - Not saved mail address where to send a message about backing up

**Comment by mariuszkrzaczkowski** [comment]
Fixed https://github.com/YetiForceCompany/YetiForceCRM/issues/997 - Do not save the parameters responsible for the inclusion of a folder with backups in the backup

**Comment by bpabiszczak** [comment]
Module "backup" has been redesigned and improved.
