### ISSUE TITLE
[Question] How to apply yeti settings for users, modules and for custom fields after switch from 4.4.0 to 5.0.0

### ISSUE THREAD

**Issue by manwenick** [YetiForceCompany/YetiForceCRM#9490]
Hello everyone!

I have a running version of yeti 4.4.0
Now I installed yeti 5.0.0 on the same VM, but in different folder. 
After installation it works fine!
Now I would like to apply all settings from 4.4.0 to 5.0.0
I mean settings for users, settings for modules, settings for custom fields, settings for automations and cronjobs which I created on the 4.4.0
Is it possible? 
I remember a tread here, where @mariuszkrzaczkowski said, that some folders in the root need to be overwritten.
Thank you!

**Comment by vovpff** [comment]
@manwenick wait for update package

**Comment by mariuszkrzaczkowski** [comment]
🎉🎉The update package has been released🎉🎉
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.0.0
https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%204.x.x/Update%20packages/
