### ISSUE TITLE
[Question] Convert Lead to Account

### ISSUE THREAD

**Issue by Tebasak1** [YetiForceCompany/YetiForceCRM#9495]
### Description

Just recently installed Yetiforce, and I thought that once you set a lead to Converted you get a convert button, however I did have that work for me, but my manager requested me change the wording of converted and I think it doesn't work anymore (or maybe there's a different required field for this button to trigger?)

Update: apparently, I didn't get it working, I saw it working on one of the demo sites. how can I replicate that process?

**Comment by lokses-od** [comment]
Hi. I spent two minutes for search: https://github.com/YetiForceCompany/YetiForceCRM/issues/6951#issuecomment-396167869
