### ISSUE TITLE
In Documentation

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#950]
It is necessary to add to the documentation that you can not create a database - in the name of the database

For Example 

yeti-force
yetiforce-crm
yeti-crm

Only fused combination

yetiforce
yetiforcecrm
yeticrm

**Comment by waran70** [comment]
O.O maybe that's why some of my migrations sucked. What about database name: database_crm_copy_1? Underscore also get errors?

**Comment by eptapsyxos** [comment]
"Your PHP MySQL library version 5.0.77 differs from your MySQL server version 5.6.21. This may cause unpredictable behavior."  
is that you mentioned related with this problem i ve get?

**Comment by waw555** [comment]
waran70
Regarding underscores do not know the probability is lower than with a hyphen, but mezhet be.

eptapsyxos
I have no problem with such versions, everything works fine, there is no conflict.

**Comment by waw555** [comment]
I have a parameter sql-mode = STRICT_TRANS_TABLES, there is a lot of mistakes, including a backup, please check if this is so, it is necessary to remove the item from the documentation

Requirements for data base engine [MySQL]
SQL_MODE should not contain STRICT_TRANS_TABLE

**Comment by waw555** [comment]
The horror, the translated text in multiple translators
SQL_MODE nie powinno zawierać STRICT_TRANS_TABLE
SQL_MODE should not contain STRICT_TRANS_TABLE

Everywhere a different translation, where transfers, which should contain, and where that is not.

Here they are, the difficulties of translation !!!

**Comment by waran70** [comment]
So, basically all underscores "_" in database names should be removed?

**Comment by bpabiszczak** [comment]
1. As far as I know hyphens are allowed in mysql, have a look at this article, maybe it will help: http://stackoverflow.com/questions/18670394/using-dash-in-mysql-table-name

2. We will verify the parameter STRICT_TRANS_TABLES and we will let you know whether it should be enabled or no. We haven't verified it, it has been inherited from Vtiger.

3. We don't understand your comment about translations. Is there a wrong translation somewhere or you just complaining about translators that don't translate things correctly?

**Comment by waw555** [comment]
I'm just complaining that the translators translate differently, spent a lot of time because STRICT_TRANS_TABLES, do not need a setting in the server
