### ISSUE TITLE
[bug] Incorrect Request ERR_NO_PERMITTED_TO_VIEW Filter Does Not Wok (Cron works mostly)

### ISSUE THREAD

**Issue by andrewchaosun** [YetiForceCompany/YetiForceCRM#9502]
![image](https://user-images.githubusercontent.com/46634935/52835591-02f88000-3122-11e9-96b1-44cabac61145.png)
#0 modules/Vtiger/views/List.php(88): App\CustomView->getViewId()
#1 include/main/WebUI.php(260): Vtiger_List_View->preProcess(Object(App\Request))
#2 include/main/WebUI.php(182): Vtiger_WebUI->triggerPreProcess(Object(Vtiger_List_View), Object(App\Request))
#3 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#4 {main}
#0 [info] SELECT * FROM `vtiger_tab` || yii\db\Command::query
#1 [info] Opening DB connection: mysql:host=localhost;dbname=buukcguc_yeti623;port=3306 || yii\db\Connection::open
#2 [info] SELECT * FROM `vtiger_entityname` || yii\db\Command::query
#3 [trace] Entering CustomView_Record_Model::getAll (Contacts) method ...
#4 [info] SELECT * FROM `vtiger_customview` WHERE (`entitytype`='Contacts') AND ((`userid`='30') OR (`status`=0) OR (`status`=3) OR (`userid` IN (SELECT `vtiger_user2role`.`userid` FROM `vtiger_user2role` INNER JOIN `vtiger_users` ON vtiger_users.id = vtiger_user2role.userid INNER JOIN `vtiger_role` ON vtiger_role.roleid = vtiger_user2role.roleid WHERE `vtiger_role`.`parentrole` LIKE 'H1::H2::H38::%'))) ORDER BY `sequence` || yii\db\Command::query
#5 [trace] Exiting CustomView_Record_Model::getAll method ...
#6 [info] Cannot translate this: 'test chaosun' for module 'Contacts', lang: en_us
#7 [info] SHOW FULL COLUMNS FROM `u_yf_browsinghistory` || yii\db\Command::query
#8 [info] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'u_yf_browsinghistory' AND kcu.table_name = 'u_yf_browsinghistory' || yii\db\Command::query
#9 [info] INSERT INTO `u_yf_browsinghistory` (`userid`, `date`, `title`, `url`) VALUES (30, '2019-02-15 13:02:40', 'Contacts List [Filter: test chaosun]', 'index.php?module=Contacts&amp;page=1&amp;view=List&amp;viewname=136&amp;orderby=&amp;sortorder=&amp;entityState=Active&amp;search_params=&amp;search_key=lastname&amp;search_value=') || yii\db\Command::execute
#10 [trace] Entering CustomView_Record_Model::getAll (Contacts) method ...
#11 [info] Cannot translate this: 'test chaosun' for module 'Contacts', lang: en_us
#12 [info] SELECT * FROM `vtiger_links` || yii\db\Command::query
#13 [info] SELECT * FROM `s_yf_companies` WHERE `default`=1 LIMIT 1 || yii\db\Command::query
#14 [trace] Start DateTimeField::__convertToUserFormat a:1:{i:0;s:9:"2019-2-15";} | yyyy-mm-dd
#15 [trace] End DateTimeField::__convertToUserFormat
#16 [info] SELECT * FROM `u_yf_browsinghistory` WHERE `userid`='30' ORDER BY `id` DESC LIMIT 20 || yii\db\Command::query
#17 [trace] Start DateTimeField::convertToUserTimeZone(today) method ...
#18 [trace] Start DateTimeField::convertTimeZone(today, Asia/Taipei, Asia/Brunei)
#19 [trace] End DateTimeField::convertTimeZone
#20 [trace] End DateTimeField::convertToUserTimeZone
#21 [trace] Start DateTimeField::convertToUserTimeZone(yesterday) method ...
#22 [trace] Start DateTimeField::convertTimeZone(yesterday, Asia/Taipei, Asia/Brunei)
#23 [trace] End DateTimeField::convertTimeZone
#24 [trace] End DateTimeField::convertToUserTimeZone
#25 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 13:02:40) method ...
#26 [trace] Start DateTimeField::convertTimeZone(2019-02-15 13:02:40, Asia/Taipei, Asia/Brunei)
#27 [trace] End DateTimeField::convertTimeZone
#28 [trace] End DateTimeField::convertToUserTimeZone
#29 [trace] Start DateTimeField::getDisplayTime(2019-02-15 13:02:40)
#30 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 13:02:40) method ...
#31 [trace] Start DateTimeField::convertTimeZone(2019-02-15 13:02:40, Asia/Taipei, Asia/Brunei)
#32 [trace] End DateTimeField::convertTimeZone
#33 [trace] End DateTimeField::convertToUserTimeZone
#34 [trace] End DateTimeField::getDisplayTime
#35 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 13:00:59) method ...
#36 [trace] Start DateTimeField::convertTimeZone(2019-02-15 13:00:59, Asia/Taipei, Asia/Brunei)
#37 [trace] End DateTimeField::convertTimeZone
#38 [trace] End DateTimeField::convertToUserTimeZone
#39 [trace] Start DateTimeField::getDisplayTime(2019-02-15 13:00:59)
#40 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 13:00:59) method ...
#41 [trace] Start DateTimeField::convertTimeZone(2019-02-15 13:00:59, Asia/Taipei, Asia/Brunei)
#42 [trace] End DateTimeField::convertTimeZone
#43 [trace] End DateTimeField::convertToUserTimeZone
#44 [trace] End DateTimeField::getDisplayTime
#45 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 13:00:51) method ...
#46 [trace] Start DateTimeField::convertTimeZone(2019-02-15 13:00:51, Asia/Taipei, Asia/Brunei)
#47 [trace] End DateTimeField::convertTimeZone
#48 [trace] End DateTimeField::convertToUserTimeZone
#49 [trace] Start DateTimeField::getDisplayTime(2019-02-15 13:00:51)
#50 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 13:00:51) method ...
#51 [trace] Start DateTimeField::convertTimeZone(2019-02-15 13:00:51, Asia/Taipei, Asia/Brunei)
#52 [trace] End DateTimeField::convertTimeZone
#53 [trace] End DateTimeField::convertToUserTimeZone
#54 [trace] End DateTimeField::getDisplayTime
#55 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 12:59:29) method ...
#56 [trace] Start DateTimeField::convertTimeZone(2019-02-15 12:59:29, Asia/Taipei, Asia/Brunei)
#57 [trace] End DateTimeField::convertTimeZone
#58 [trace] End DateTimeField::convertToUserTimeZone
#59 [trace] Start DateTimeField::getDisplayTime(2019-02-15 12:59:29)
#60 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 12:59:29) method ...
#61 [trace] Start DateTimeField::convertTimeZone(2019-02-15 12:59:29, Asia/Taipei, Asia/Brunei)
#62 [trace] End DateTimeField::convertTimeZone
#63 [trace] End DateTimeField::convertToUserTimeZone
#64 [trace] End DateTimeField::getDisplayTime
#65 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 12:57:28) method ...
#66 [trace] Start DateTimeField::convertTimeZone(2019-02-15 12:57:28, Asia/Taipei, Asia/Brunei)
#67 [trace] End DateTimeField::convertTimeZone
#68 [trace] End DateTimeField::convertToUserTimeZone
#69 [trace] Start DateTimeField::getDisplayTime(2019-02-15 12:57:28)
#70 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 12:57:28) method ...
#71 [trace] Start DateTimeField::convertTimeZone(2019-02-15 12:57:28, Asia/Taipei, Asia/Brunei)
#72 [trace] End DateTimeField::convertTimeZone
#73 [trace] End DateTimeField::convertToUserTimeZone
#74 [trace] End DateTimeField::getDisplayTime
#75 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 12:57:14) method ...
#76 [trace] Start DateTimeField::convertTimeZone(2019-02-15 12:57:14, Asia/Taipei, Asia/Brunei)
#77 [trace] End DateTimeField::convertTimeZone
#78 [trace] End DateTimeField::convertToUserTimeZone
#79 [trace] Start DateTimeField::getDisplayTime(2019-02-15 12:57:14)
#80 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 12:57:14) method ...
#81 [trace] Start DateTimeField::convertTimeZone(2019-02-15 12:57:14, Asia/Taipei, Asia/Brunei)
#82 [trace] End DateTimeField::convertTimeZone
#83 [trace] End DateTimeField::convertToUserTimeZone
#84 [trace] End DateTimeField::getDisplayTime
#85 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 12:57:08) method ...
#86 [trace] Start DateTimeField::convertTimeZone(2019-02-15 12:57:08, Asia/Taipei, Asia/Brunei)
#87 [trace] End DateTimeField::convertTimeZone
#88 [trace] End DateTimeField::convertToUserTimeZone
#89 [trace] Start DateTimeField::getDisplayTime(2019-02-15 12:57:08)
#90 [trace] Start DateTimeField::convertToUserTimeZone(2019-02-15 12:57:08) method ...
#91 [trace] Start DateTimeField::convertTimeZone(2019-02-15 12:57:08, Asia/Taipei, Asia/Brunei)
#92 [trace] End DateTimeField::convertTimeZone
#93 [trace] End DateTimeField::convertToUserTimeZone
#94 [trace] End DateTimeField::getDisplayTime
#95 [info] SELECT * FROM `vtiger_actionmapping` || yii\db\Command::query
#96 [trace] Entering CustomView_Record_Model::getAll (Contacts) method ...
#97 [trace] App\CustomView::getViewId
#98 [trace] App\CustomView::isPermittedCustomView
#99 [trace] App\CustomView::getStatusAndUserid
#100 [info] SELECT * FROM `vtiger_customview` WHERE `cvid`=136 LIMIT 1 || yii\db\Command::query
#101 [info] SELECT `vtiger_users`.`id` FROM `vtiger_customview` INNER JOIN `vtiger_users` WHERE (`vtiger_customview`.`cvid`=136) AND (`vtiger_customview`.`userid` IN (SELECT `vtiger_user2role`.`userid` FROM `vtiger_user2role` INNER JOIN `vtiger_users` ON vtiger_user2role.userid = vtiger_users.id INNER JOIN `vtiger_role` ON vtiger_user2role.userid = vtiger_role.roleid WHERE `vtiger_role`.`parentrole` LIKE '%H1::H2::H38::%')) || yii\db\Command::query
#102 [info] SHOW FULL COLUMNS FROM `o_yf_access_for_user` || yii\db\Command::query
#103 [info] Opening DB connection: mysql:host=localhost;dbname=buukcguc_yeti623;port=3306 || yii\db\Connection::open
#104 [info] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'o_yf_access_for_user' AND kcu.table_name = 'o_yf_access_for_user' || yii\db\Command::query
#105 [info] INSERT INTO `o_yf_access_for_user` (`username`, `date`, `ip`, `module`, `url`, `agent`, `request`, `referer`) VALUES ('SUN Chao General', '2019-02-15 13:02:40', '182.101.58.27(HTTP_X_FORWARDED_FOR: 137.59.148.201)', 'Contacts', 'http://erp.overseaser.com/index.php?module=Contacts&amp;page=1&amp;view=List&amp;viewname=136&amp;orderby=&amp;sortorder=&amp;entityState=Active&amp;search_params=&amp;search_key=lastname&amp;search_value=', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36', '{\"module\":\"Contacts\",\"page\":\"1\",\"view\":\"List\",\"viewname\":\"136\",\"orderby\":\"\",\"sortorder\":\"\",\"entityState\":\"Active\",\"search_params\":\"\",\"search_key\":\"lastname\",\"search_value\":\"\",\"__utmz\":\"268026320.1545735325.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)\",\"__utma\":\"146133216.1277113011.1545754158.1545754158.1545754158.1\",\"mybb\":{\"lastvisit\":\"1545888430\",\"lastactive\":\"1545888535\"},\"loginattempts\":\"1\",\"mybbuser\":\"1_9y7ryd3iojwt72c3cbk2jeomry4bdzzefh7uxjlgtstcddjjbz\",\"YTSID\":\"9fb2892295e5916714cddb17cc7fdaed\"}', '-') || yii\db\Command::execute
#106 [error] ERR_NO_PERMITTED_TO_VIEW
App\Exceptions\NoPermitted: ERR_NO_PERMITTED_TO_VIEW in app/CustomView.php:644
Stack trace:
#0 modules/Vtiger/views/List.php(88): App\CustomView->getViewId()
#1 include/main/WebUI.php(260): Vtiger_List_View->preProcess(Object(App\Request))
#2 include/main/WebUI.php(182): Vtiger_WebUI->triggerPreProcess(Object(Vtiger_List_View), Object(App\Request))
#3 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#4 {main}

# 🐞 bug report

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by andrewchaosun** [comment]
cron status: http://erp.overseaser.com/index.php?module=CronTasks&parent=Settings&view=List&block=15&fieldid=26

**Comment by vovpff** [comment]
@andrewchaosun community can't reach your cron status

**Comment by mariuszkrzaczkowski** [comment]
show the result of the query
```sql
SELECT cvid,viewname FROM `vtiger_customview` WHERE  entitytype = 'Contacts'
```

**Comment by andrewchaosun** [comment]
> @andrewchaosun community can't reach your cron status
![Uploading image.png…]()

**Comment by andrewchaosun** [comment]
> @andrewchaosun community can't reach your cron status

![image](https://user-images.githubusercontent.com/46634935/52859985-2d216080-3169-11e9-9657-3f990cf662bb.png)

**Comment by andrewchaosun** [comment]
> show the result of the query
> 
> ```sql
> SELECT cvid,viewname FROM `vtiger_customview` WHERE  entitytype = 'Contacts'
> ```

Please give me more instructions about how to do that.  Many thanks.

**Comment by andrewchaosun** [comment]
> show the result of the query
> 
> ```sql
> SELECT cvid,viewname FROM `vtiger_customview` WHERE  entitytype = 'Contacts'
> ```
I only found the following: 
#4 [info] SELECT * FROM `vtiger_customview` WHERE (`entitytype`='Contacts') AND ((`userid`='30') OR (`status`=0) OR (`status`=3) OR (`userid` IN (SELECT `vtiger_user2role`.`userid` FROM `vtiger_user2role` INNER JOIN `vtiger_users` ON vtiger_users.id = vtiger_user2role.userid INNER JOIN `vtiger_role` ON vtiger_role.roleid = vtiger_user2role.roleid WHERE `vtiger_role`.`parentrole` LIKE 'H1::H2::H38::%'))) ORDER BY `sequence` || yii\db\Command::query
#5 [trace] Exiting CustomView_Record_Model::getAll method ...

**Comment by vovpff** [comment]
Go to your database manager and run this code

**Comment by andrewchaosun** [comment]
> Go to your database manager and run this code

Hi, Vov, Is this PHPMYADMIN my data base manager?

![image](https://user-images.githubusercontent.com/46634935/52897671-1d118b80-3212-11e9-9403-93774efaa1f9.png)

**Comment by andrewchaosun** [comment]
> Go to your database manager and run this code

Is this right?

![image](https://user-images.githubusercontent.com/46634935/52897940-133c5800-3213-11e9-9ff5-976a324b9f11.png)

**Comment by vovpff** [comment]
Looks like yes. @mariuszkrzaczkowski should check

**Comment by mariuszkrzaczkowski** [comment]
attach a screenshot of verification of configuration

**Comment by andrewchaosun** [comment]
![yetiforce_settings 6](https://user-images.githubusercontent.com/46634935/53325710-deb95200-391e-11e9-8e70-bd5a8270bccc.png)

IS THIS THE ONE REQUIRED, PLEASE?

**Comment by andrewchaosun** [comment]
![image](https://user-images.githubusercontent.com/46634935/54251861-b0c14800-4583-11e9-8602-09c013139ea1.png)
Not much progress.

**Comment by mariuszkrzaczkowski** [comment]
show the result of the query and  logs
```sql
SELECT * FROM `vtiger_customview` WHERE  entitytype = 'Contacts'
```

**Comment by konadrian** [comment]
I closed the issue because we've waited too long for an answer
