### ISSUE TITLE
  Upload Documents using Image File Field Type

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9510]
Hi, Is there a way to upload PDF & word documents using image file field type. It currents accepts only jpg/png formats.

**Comment by vovpff** [comment]
@indrabhusanroy image means image formats. PDF and word - document format.

**Comment by indrabhusanroy** [comment]
Basically I want to upload documents with format word & PDF. So I thought if the Image file Field type can be used upload pdf & word documents.

**Comment by indrabhusanroy** [comment]
Currently the image file field only accepts jpg/png. So If the word/pdf format are added, can it upload documents with formats:doc/pdf?

**Comment by vovpff** [comment]
For image no. You can upload this files as documents

**Comment by indrabhusanroy** [comment]
Solved...
