### ISSUE TITLE
[bug] English can't be updated

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9513]
# 🐞 bug report

### ⁉️ Describe the bug

On my fresh updated 5.0.0 I cant update English langpack.

![image](https://user-images.githubusercontent.com/8545791/52857436-3514dc80-3138-11e9-9c33-e8e8ae99db80.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mariuszkrzaczkowski** [comment]
You do not need to update English, this is the base language that is always up to date

**Comment by vovpff** [comment]
Ok. But I has missing english translations. I can attach screenshot tomorrow. Wait little bit

**Comment by mariuszkrzaczkowski** [comment]
We will check the download of the translation and the missing one as you send

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I found only one missing translation at this time.
![image](https://user-images.githubusercontent.com/8545791/52910410-1897b200-32a8-11e9-88eb-1c5af66e797e.png)
This is not so big problem. How to translate this string?
Why last update for english is `4 years 7 months ago`. Is it ok?

**Comment by mariuszkrzaczkowski** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/9573
