### ISSUE TITLE
[bug] 5.0.0 Broken WYSIWYG Continued

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#9516]
# 🐞 bug report

### ⁉️ Describe the bug
When you add table, and press save it render a lot of "< br>" tags above and after the table, **i have made a research and find out that it is due to unminified HTML code. You actually can place minified content right to database, and then it is not going to render "< br>".**

### 🔥 How to trigger the error

Steps to reproduce the behaviour:
1. Go to 'https://gitdeveloper.yetiforce.com/index.php?module=Leads&view=Detail&record=267&mode=showDetailViewByMode&requestMode=full&tab_label=LBL_RECORD_DETAILS'
2. Click on 'Full Edit'
3. Scroll down to 'Description'
4. Add a table by placing your code in source or through table create shortcut
5. make sure that there is No "< br>" before and after the table
6. Press save you and go details and scroll down to description.
7. See the code  a lot of "< br>"

### 👎 Actual Behavior
Dont work

### 👍 Expected Behavior
Work

### 📷 Screenshot of configuration
Gitdeveloper/Gitstable

### ❓ Additional context
5.0.0 is not a stable update to use on production crm, waiting for bug fixing.

**Comment by vovpff** [comment]
![image](https://user-images.githubusercontent.com/8545791/52958204-a1941380-33a4-11e9-82a2-098db12c6dcd.png)
:(

**Comment by z0lo** [comment]
@mariuszkrzaczkowski @rskrzypczak The wysiwyg is very ultimate tool in the curent crm aspecially with tables, please take a look on the issue

**Comment by z0lo13** [comment]
@mariuszkrzaczkowski @rskrzypczak The wysiwyg is very ultimate tool in the curent crm aspecially with tables, please take a look on the issue
