### ISSUE TITLE
The Account has no active SLA

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9518]
### Description

When ever i am saving new record in ticket that time  showing the The Account has no active SLA  please help me why am i  getting that message  
![no sla](https://user-images.githubusercontent.com/47585969/52895998-d9208580-3215-11e9-85d4-bbdf820cbc9c.png)

**Comment by vovpff** [comment]
Relataded account also need to has SLA with active status. You nees to add SLA

**Comment by guide5232** [comment]
Ok thanks Now i am not getting that message

**Comment by Giorgos-Hellene** [comment]
I have the same issue

How can i relate the sla with account ?
Thank you

**Comment by vovpff** [comment]
@Giorgos-Hellene https://gitdeveloper.yetiforce.com/index.php?module=ServiceContracts&view=List&mid=65&parent=63

**Comment by Giorgos-Hellene** [comment]
@vovpff  Thank you for your reply. 
I try to relate it and now seems a yellow bar http://prntscr.com/qtfvsi 
When i press click on it, this is doing nothing but it works on gitdeveloper.yetiforce.com .

Also i can not see the bar of progress as here http://prntscr.com/qtfy15

Do you have an idea what happens ?

**Comment by vovpff** [comment]
@Giorgos-Hellene you need to fill all data to get working SLA.
Progress bar can be activated in Status field options.

**Comment by Giorgos-Hellene** [comment]
Hi @vovpff !
i filled all data but unfortunately SLA label is the same. It can't relate the ticket with SLA.

Where are the Status Field Options ? could you show me a printscreen ?

thank you !

**Comment by vovpff** [comment]
@guide5232 
![image](https://user-images.githubusercontent.com/8545791/73243473-a9fdec80-41b8-11ea-89d8-ba584dc10680.png)
![image](https://user-images.githubusercontent.com/8545791/73243486-b5e9ae80-41b8-11ea-90e9-401f84631aca.png)

**Comment by vovpff** [comment]
@guide5232 I'm not using tickets now but I has tried them on the past and them works well

**Comment by Giorgos-Hellene** [comment]
@guide5232 Yessssssss !! It is works fine. Thank you very very much !!
