### ISSUE TITLE
Convert Lead to Account Pt2 [Question]           

### ISSUE THREAD

**Issue by Tebasak1** [YetiForceCompany/YetiForceCRM#9519]
### Description

Just recently installed Yetiforce, and I thought that once you set a lead to Converted you get a convert button, my manager requested me change the wording of converted and I think it doesn't work anymore (or maybe there's a different required field for this button to trigger?) Is there a doc to actually create the mapping?

Note: I have gone through all the other posts before, and none of them provided me a solution.

![image](https://user-images.githubusercontent.com/20876336/52900003-819efd00-31b6-11e9-875c-a16497aee782.png)

**Comment by Tebasak1** [comment]
Or maybe show me how to create that kind of connection?

What does VerificationRequired mean?

**Comment by areksolek** [comment]
It has been tested on gitdeveloper. The test showed that everything is good.
![coversion](https://user-images.githubusercontent.com/25615135/53092413-09696c00-3515-11e9-89b5-fa87d31289dc.gif)

**Comment by Tebasak1** [comment]
Thank you for showing me the process by which to take a lead to conversion. Why, then, do you suppose that it's not working on my installed version?

**Comment by mariuszkrzaczkowski** [comment]
what is your system version?

**Comment by Tebasak1** [comment]
Yetiforce v4.3

**Comment by mariuszkrzaczkowski** [comment]
the error does not occur in the latest version, we recommend updates.

**Comment by Tebasak1** [comment]
Thank you for the information. It looks like there's a few big bugs that still need to be worked out before I'm confident we can upgrade. I look forward to this feature in the future.
