### ISSUE TITLE
[Question] Can you determine differences in use case of Costs and Payments-out?

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#952]
It seems like forcing to double entry Costs and than payment out.
How is it working in your scenario?

**Comment by bpabiszczak** [comment]
1. Costs are purchase invoices.

2. Payments in – are incoming payments received to your bank account, can be imported from your bank in MT940 format.

3. Payments out – are outgoing payments that will be automatically generated in the future on the basis of e.g. a Cost document. If I remember it correctly, now it’s also possible to import outgoing payments from your bank.

Of course, what you can see today is only a small part of a functionality that will be created for the financial system. These modules will change.

**Comment by amicheals** [comment]
@bpabiszczak 
Operation
Purchase Order to vendor for products
Then create costs based on purchase order

Then create payments in from the sale of the product
Costs are connected to payments out. You need a costs item before you create a payments out item?
