### ISSUE TITLE
[bug] 5.0 installation

### ISSUE THREAD

**Issue by Luxx99** [YetiForceCompany/YetiForceCRM#9520]
# 🐞 bug report

### ⁉️ Describe the bug
During the installation of version 5.0, a brand new installation, I get a blank page, whitout any other message.

### 🔥 How to trigger the error
simply following the installation procedure

### 📷 Screenshot of configuration
![yetiforce_settings](https://user-images.githubusercontent.com/23698008/52901178-fe09fe00-31ff-11e9-935b-e134e914a0a2.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
 cache/logs/errors.log 
E_ERROR: Uncaught Error: Class 'Locale' not found in C:\Program Files (x86)\Ampps\www\y5\app\Language.php:717
Stack trace:
#0 C:\Program Files (x86)\Ampps\www\y5\app\Controller\Base.php(23): App\Language::initLocale()
#1 C:\Program Files (x86)\Ampps\www\y5\install\views\Index.php(66): App\Controller\Base->__construct()
#2 C:\Program Files (x86)\Ampps\www\y5\install\Install.php(34): Install_Index_View->__construct()
#3 {main}
  thrown in C:\Program Files (x86)\Ampps\www\y5\app\Language.php, line 717
#0  >>  App\ErrorHandler->fatalHandler()

### 🌍  Your Environment 
I'm using a local test environment on AAMPS/windows 10

### ❓ Additional context
nothing

**Comment by mariuszkrzaczkowski** [comment]
duplicate
https://github.com/YetiForceCompany/YetiForceCRM/issues/9482
