### ISSUE TITLE
   Members under group name

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9522]
Hi, here groups can be created, But if I assign a module to a group, then all the members of the group gets access to that module. But I want to assign a particular member of the group to the module. Here I can select a particular member but I cannot be sure which group this user belongs unless while selecting a group It shows the members like dropdown selection under the Group Name which it currently does not. So can this be done anyhow, so that under every group its members are shown and then I assign that particular member to that module/document or anything.

**Comment by paula-w** [comment]
Currently the system doesn't show that and we're not planning to add that because you are the first person who asked about this feature. We can add it if a client wants to order such a feature from us.
