### ISSUE TITLE
[bug] Date format

### ISSUE THREAD

**Issue by kpaulaha** [YetiForceCompany/YetiForceCRM#9524]
# 🐞 bug report

Date format dd.mm.yyyy not accepted.

![date](https://user-images.githubusercontent.com/10330264/52912809-6835a800-32bf-11e9-90e8-d3ea5b69e836.png)

![date1](https://user-images.githubusercontent.com/10330264/52912811-6c61c580-32bf-11e9-8eb3-2489620cbc04.png)

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by aplauz** [comment]
I have the same :(

**Comment by rskrzypczak** [comment]
Is this a clean version of YetiForce 5.0.0 or was it updated? 
Either way, please clean browser cache (shift + F4, ctrl + shift + r) and verify if the error still exists.

**Comment by kpaulaha** [comment]
It was a updated version. Seems to work on the other clean version.

**Comment by aplauz** [comment]
Both. Refreshing, cleansing cache does not change anything.

**Comment by manwenick** [comment]
I have the same problem on the clean version 5.0.0

**Comment by kpaulaha** [comment]
For me the problem seems to appear with firefox, works ok with others.
