### ISSUE TITLE
[Question] New calendar layout?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9525]
### Description

After update I has old Calendar layout
![image](https://user-images.githubusercontent.com/8545791/52932529-0e85ba00-3361-11e9-8843-c2823546d4f2.png)

instead new one 
![image](https://user-images.githubusercontent.com/8545791/52932538-1a717c00-3361-11e9-8d0e-3222cc2dd90b.png)

How to apply new layout?

**Comment by rskrzypczak** [comment]
It's enough to save the selected menu element once again for a given role and clean browser cache.
![git-calendar](https://user-images.githubusercontent.com/10221999/52948611-2289e580-337a-11e9-8d5b-894e625572a4.gif)

**Comment by vovpff** [comment]
@rskrzypczak thanks!
