### ISSUE TITLE
Cron settings. How to do it        

### ISSUE THREAD

**Issue by Luxx99** [YetiForceCompany/YetiForceCRM#9528]
### Description
Hi, lookink at the system configuration I noticed that the CRON configuration does not fit the YF requirements. My question is: where/how can I change it?

![image](https://user-images.githubusercontent.com/23698008/52937148-9e763480-335e-11e9-85c9-d4187bae2e7e.png)

thank you
L

**Comment by mariuszkrzaczkowski** [comment]
you probably have separate php.ini files for cli and www
![image](https://user-images.githubusercontent.com/10198654/52947909-5532de80-3378-11e9-957d-372f02130c69.png)
