### ISSUE TITLE
Assign a module to multiple users

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9529]
Can a module be assigned to multiple users in private mode. Here I have three level of users working on the same module. One user will assign the module to another users who will in turn assign to other user. But If do this when a user assigns a module to another user, then he cannot see the module after it has been assigned to another user. How to solve this so that even after assigning the module, he keeps to view that module.

**Comment by paula-w** [comment]
1. If I understand you correctly, you mean a record, not a module.
2. If you assign records from user A to user B, and user A no longer sees user B’s records, then it means your permissions aren’t configured according to your business needs. You should configure it in the permission panel.
3. Apart from the „assigned to” field, you might want to check out the „share with” field.
