### ISSUE TITLE
[bug] Line not cleared

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9544]
# 🐞 bug report

### ⁉️ Describe the bug

When x clicked near product search field not cleared. Check gif.

### 🔥 How to trigger the error

![lineitems](https://user-images.githubusercontent.com/8545791/52959063-73afce80-33a6-11e9-8b5d-dbb29e4de42a.gif)

**Comment by vovpff** [comment]
If line not cleared and record saved - error

**Comment by vovpff** [comment]
Is this fix will be available with new version of Update to 5.0?

**Comment by rafalpospiech** [comment]
It will be available in 5.1

**Comment by vovpff** [comment]
@rafalpospiech when 5.1 will arrive?

**Comment by bpabiszczak** [comment]
@vovpff  1-2 weeks.

**Comment by vovpff** [comment]
Thx!
