### ISSUE TITLE
How configure php.ini

### ISSUE THREAD

**Issue by T1133** [YetiForceCompany/YetiForceCRM#9545]
Hello,

After configuration php.ini as crm require i result only white website. Is there any mistakes in requirements?
LAMP installed correctly because previously install wizard have been run, Apache still working, status result OK, Runing withour any problems
------------------------------------

Witam,

Po konfiguracji php.ini mam białą stronę, pakiet LAMP jest zainstalowany poprawnie ponieważ wcześniej odpalała się instalacja. Apach działa, a polecenie status nie zwraca żadnych błędów. Czy może byc jakis błąd w wymaganiach php.ini??

Distribution/Dystrybucja: Ubuntu 16.04 LTS

**Comment by vovpff** [comment]
If your old configuration works well in the past you need to check your new php config for your mistakes. I has LAMP on Ubuntu and every problem what I has was my mistakes.

**Comment by mariuszkrzaczkowski** [comment]
see this .user.ini file here you have all the required changes in PHP.ini

https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/.user.ini

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-uzytkownika/item/web-server-requirements
