### ISSUE TITLE
[Question]   Sending email was unsuccess

### ISSUE THREAD

**Issue by copyyour** [YetiForceCompany/YetiForceCRM#9546]
After I set up STMP, I can receive the notification email with successful settings. Then I set up the workflow and start using it, but I can't send the mail. I can send the mail in the settings, and wait for the mail status to be sent---A few hours later. I tried to click send manually, the display was successful, but I still haven't received the mail. Please help solve it, thank you.

**Comment by aplauz** [comment]
Maybe you should try to change the cron settings (time) in hosting panel.

**Comment by copyyour** [comment]
The main problem is that I now click to send manually and the email will not be sent successfully.

**Comment by mariuszkrzaczkowski** [comment]
check what you have in the table `l_yf_mail`

**Comment by mariuszkrzaczkowski** [comment]
We added error handling in the email queue, so now when an error occurs, it will visible.
https://github.com/YetiForceCompany/YetiForceCRM/pull/11103
