### ISSUE TITLE
[bug] [PL] nazwa faktury pdf

### ISSUE THREAD

**Issue by aplauz** [YetiForceCompany/YetiForceCRM#9547]
# 🐞 bug report

1. Jeśli ustawi się nazwę pliku faktury jako FV-$(record / number)$.pdf  (co powinno dać FV-01/02/2019.pdf) system wygeneruje a przeglądarka pobierze plik o nazwie 2019.pdf. Może można ustawić żeby zmieniał slashe na kropki? Wyszedłby plik o nazwie FV-01.02.2019.pdf, ktory jest w sumie akceptowalny przez wszystkie systemy operacyjne.

2. Jeśli ustawi się wyzwalacz: wyślij szablon z plikiem PDF system wyśle maila z załącznikiem o nazwie FV-$(record / number)$.pdf

![zrzut ekranu 2019-02-18 o 21 55 33](https://user-images.githubusercontent.com/46876516/52976215-e3cf4c00-33c8-11e9-89a9-2eeaff16262a.png)

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0.0
| Web server (name and version)|		|
| PHP  |	7.1							|
| Browser (name and version)  | 	FF, Chrome	|
| Operating System (name and version)  | 	OSX 10.14.3	|
| Database (name and version) | 		|

**Comment by bpabiszczak** [comment]
Poprawka dostępna powyżej [do ręcznej implementacji], wersja 5.1 będzie zawierała w sobie tą poprawkę.
