### ISSUE TITLE
Problem with date and time      

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9550]
### Description

Workflow condition not checking the 
![post1](https://user-images.githubusercontent.com/47585969/52992174-b4b9e880-3463-11e9-8c8d-927b163935bc.png)
![post2](https://user-images.githubusercontent.com/47585969/52992176-b8e60600-3463-11e9-8c50-3c7e28b754f4.png)

It is not firing after fours .if i created new record at 2PM,this record has to fire after the four hours like 6 PM but it is not firing. i am not getting any email notification. 

I have checked for all condition

  Creating record
  Modifying record
  Every time a record is saved (eg. creating, modifying)
  Only once, when all conditions are met
  Deleting record
  Execution schedule (defined time intervals)
  System
  Manual trigger by the user
  Block edition

if i take created time field that time  are not firing.

  Execution schedule (defined time intervals):In this schedule it not waiting for four hours .it is firing with in one hour

**Comment by guide5232** [comment]
I have one doubt about it,Can i change this code in my local files or yetiforce team will include in 5.1 version

**Comment by guide5232** [comment]
Please give me reply

**Comment by areksolek** [comment]
[guide5232](/guide5232) What is your system version?

**Comment by guide5232** [comment]
4.4 Version

**Comment by guide5232** [comment]
Please tell me ,Can i change this code in my local files or it will come in  new version

**Comment by vovpff** [comment]
You can try to implement commit but there can be a lot of modifications of files in the past

**Comment by areksolek** [comment]
Please wait for the upgrade pack.  It can be expected up to 2 weeks.
