### ISSUE TITLE
[Question]   PDF Font 

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#9553]
### Description

Jaki mechanizm odpowiada za tworzenie PDF w wersji 5 ? jak zmienić domyślny font ?

**Comment by aplauz** [comment]
Podepnę się pod pytanie.

**Comment by rafalpospiech** [comment]
Silnik: https://github.com/YetiForceCompany/YetiForcePDF

Paczkę fontów dodatkowych można pobrać z [YetiForceFonts](https://github.com/YetiForceCompany/YetiForceFonts/tree/master/zip) i zainstalować jako moduł w panelu admina.
