### ISSUE TITLE
[PL][bug] Kalendarz 

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#9555]
# 🐞 bug report

[PL] Nie daje się utworzyć zdarzenia , spotkania w kalendarzu - niepoprawna data.

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5,0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by rafalpospiech** [comment]
Jakie masz ustawienia daty w panelu?
Otwórz konsolę i zrób kilka zrzutów gdy wystąpi błąd, najlepiej jakbyś nagrał gifa / mp4.
Na gitdeveloper.yetiforce.com wydaje sie że wszystko działa.

**Comment by bpabiszczak** [comment]
Tak jak napisał Rafał. Sprawdzić format daty i spróbować wywołać błąd na wersji https://gitdeveloper.yetiforce.com/ oraz https://gitstable.yetiforce.com/. Musimy wiedzieć jak błąd wywołać aby móc pomóc.

Aktualny opis nie jest wystarczający aby z tym zrobić coś więcej.
