### ISSUE TITLE
[Question] Archive record/ recycle bin

### ISSUE THREAD

**Issue by kilim1983** [YetiForceCompany/YetiForceCRM#9562]
### Description

Maybe I'm coming blind, but where can the deleted/archived records be found in 4.3

How can I remove this label from records?

I found Question Recycle Bin #5721 but I cannot see options on the picture in my web console.

Thanks
Damian

**Comment by kilim1983** [comment]
Ok I found it. In my opinion the icon graphic is misleading :)

**Comment by bpabiszczak** [comment]
@kilim1983  you are right, we will change it!
