### ISSUE TITLE
ERR_NOT_FOUND_FIELD_MODEL

### ISSUE THREAD

**Issue by Fvsvcs** [YetiForceCompany/YetiForceCRM#9564]
On new installation of 5.0.0 going to Database, click on products the error comes up. Please help.
![yeti database product error](https://user-images.githubusercontent.com/40373720/53065130-6246ef00-3498-11e9-97ce-27483c192294.PNG)

**Comment by vovpff** [comment]
What about other modules? Pls provide logs also

**Comment by Fvsvcs** [comment]
i logged out and back in. its now working
