### ISSUE TITLE
[bug] Some minimal column width overrides set value in detail view

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9568]
# 🐞 bug report

### ⁉️ Describe the bug

At detail view column widths doesn't match specified params:

![image](https://user-images.githubusercontent.com/8545791/53083944-e50b9080-3510-11e9-8007-47426e6b301a.png)

At edit view all ok

![image](https://user-images.githubusercontent.com/8545791/53084008-09676d00-3511-11e9-91df-f1d4c2020c42.png)
 
Qty - 3%
Unit - 2%

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.0.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

### ❓ Additional context

I can't check gitdev because broken

**Comment by areksolek** [comment]
The test showed that everything is good (tested on gitdeveloper). The columns adjust to the width of the browser window and to the contents of the cell. The difference of one percent is hardly visible, but if you look closely, the column "Unit" in the attached picture is a bit narrower.
