### ISSUE TITLE
Summary View Like Contacts on Custom Created Modules

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#957]
How we can achieve the summary preview style of contacts
to other custom created modules?

I ve tried to import widgets of related modules on custom modules summary review(through module summary widget on settings)
but nothing seems to happend.

Is that possible right now?
Or it will be on feature update?

**Comment by eptapsyxos** [comment]
Find a solution for the basic template

Create a folder for the custom module under layouts/vlayout/modules and create 2 files:

DetailViewSummaryContents.tpl:
{strip}
	{include file='SummaryViewWidgets.tpl'|vtemplate_path:$MODULE_NAME}
{/strip}

ModuleSummaryView.tpl:
{strip}
	<div class="recordDetails">
		{include file='SummaryViewContents.tpl'|vtemplate_path:$MODULE_NAME}
	</div>
{/strip}

But i have to do something more...I am close
![summarylayout](https://cloud.githubusercontent.com/assets/6897502/7901629/27f2a90e-079a-11e5-8f82-1223d1acbd4d.jpg)

The details view work as normal

**Comment by mariuszkrzaczkowski** [comment]
Do you added widgets (Settings> Studio> Module summary widgets) ?

**Comment by eptapsyxos** [comment]
I tried your method mariusz twice.
the first time when i ve just created the module (i tried the module summary widget)
Nothing happend
And i ve tried again with the module summary widget when i import the two files i ve created
(the modulesummary.tpl and the DetailViewSummaryContents.tpl)
Again nothing

I searched for example the folder of the layout of the contacts module and i saw that is needed more files to add.

**Comment by mariuszkrzaczkowski** [comment]
I did a little test on test.yetiforce.com: 
I created a new module Testtest, 
added a file DetailViewSummaryContents.tpl, 
added a widget 'Summary'  
and marked fields to make them visible on summary, 

please check it works: https://test.yetiforce.com/index.php?module=Testtest&view=Detail&record=232

**Comment by eptapsyxos** [comment]
Worked like a charm!!!
