### ISSUE TITLE
[bug] Call to a member function gettablename() boolean

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#9570]
Hello all ! 

    I have a problem with inventory module, more exactly with Products module. When i want to access the history of the product, IGDN on a specific product, i get an error. 
    System : Yetiforce 5.0 
    Gif attached.
![error](https://user-images.githubusercontent.com/42461923/53089810-dec7e500-350d-11e9-99a1-f7fb97e36035.gif)
![boleean-error](https://user-images.githubusercontent.com/42461923/53089817-e2f40280-350d-11e9-8c7f-97c6dd65596e.png)

**Comment by arek1-618** [comment]
I can't trigger error. Could you attach the php and CRM logs

* cache/logs/phpError.log
* cache/logs/system.log

**Comment by acsinsurancegroup** [comment]
I'm having this exact issue on version 5.2 Stable. When I click on Services in the main menu and then select an actual service data record. In the detailed area with the tabs you see in the screenshot below all the tabs work except Marketing Campaigns. 

It will just sit and spin and say "Loading, please wait." forever and nothing happens.

![Services_issue](https://user-images.githubusercontent.com/42642523/75137086-4928dd80-56ac-11ea-8fb9-5d3026944e5d.png)

When I try to stop it, I get the following error just like the original post as seen in this screenie:

![Marketing_campaign_tab](https://user-images.githubusercontent.com/42642523/75137240-b89ecd00-56ac-11ea-92cb-56f7978cbf81.png)

His issue was back in Feb 2019 and this still occurs in Version 5.2 stable with the latest Update v19 installed? 

How can I resolve this @mariuszkrzaczkowski thank you sir :)
