### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by T1133** [YetiForceCompany/YetiForceCRM#9574]
After install all packages of LAMP i cannot pass installation because i have sombe errors in logs. As i checked it's problem with time datazone. may i ask for help?

[Wed Feb 20 15:36:03.433762 2019] [php7:error] [pid 3534] [client 10.134.40.17:56758] PHP Fatal error: Uncaught Error: Class 'Local’ not found in /var/www/html/YetiForceCRM-5.0.0-complete/app/Language.php:717\nStack trace:\n#0 /var/www/html/YetiForceCRM-5.0.0-complete/app/Controller/Base.php(23): App\\Language::initLocale()\n#1 /var/www/html/YetiForceCRM-5.0.0-complete/install/views/Index.php(66): App\\Controller\\Base->__construct()\n#2 /var/www/html/YetiForceCRM-5.0.0-complete/install/Install.php(3views/Index.php(66): App\\Controller\\Base->__construct()\n#2 /var/www/html/YetiForceCRM-5.0.0-complete/install/Install.php(34): Install_Index_View->__construct()\n#3 {main}\n thrown in /var/www/html/YetiForceCRM-5.0.0-complete/app/Language.php on lp on line 717

**Comment by mariuszkrzaczkowski** [comment]
duplicate
#9482

**Comment by T1133** [comment]
Thank you!
