### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#9578]
SEPARATOR #8883

Unfortunately, the tax is still not working if the separator is "," It works only if there are integers, but if the tax is 9,5%, it changes to 9 or 95.
--------------------------------

![untitled-8](https://user-images.githubusercontent.com/25682437/53111889-4ac24180-353e-11e9-87e2-f4b542dbfc99.gif)

![untitled-4](https://user-images.githubusercontent.com/25682437/53111699-e43d2380-353d-11e9-99ad-900ff0eebd2d.gif)

**Automatically transfer 9% of the tax from the product. Of course it can be corrected individually and everything is ok and then close the edit view.**

![untitled-6](https://user-images.githubusercontent.com/25682437/53111794-18b0df80-353e-11e9-9eb5-fc4767543915.gif)

**### Then reopen**

![untitled-7](https://user-images.githubusercontent.com/25682437/53111851-3bdb8f00-353e-11e9-97cd-9b9070d6f57b.gif)

### ??  Your Environment 

| YetiForce			|  ver. 5.0.1 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by arek1-618** [comment]
Hello, Sir.
In the latest version it looks like there is no longer this error.

![chrome_2019-02-27_13-11-53](https://user-images.githubusercontent.com/32322851/53489827-66739d80-3a92-11e9-9d76-7d4b12620d49.png)
![2019-02-27_13-11-38](https://user-images.githubusercontent.com/32322851/53490119-2b259e80-3a93-11e9-8607-b067cc8ad3e5.gif)

**Comment by fbojan** [comment]
Unfortunately, the assue still exists in version [ver. 5.0.9]. Now it's calculated correctly, but when you want to re-edit an existing record, 95% instead of 9.5 is displayed again.

> Hello, Sir.
> In the latest version it looks like there is no longer this error.
> 
> ![chrome_2019-02-27_13-11-53](https://user-images.githubusercontent.com/32322851/53489827-66739d80-3a92-11e9-9d76-7d4b12620d49.png)
> ![2019-02-27_13-11-38](https://user-images.githubusercontent.com/32322851/53490119-2b259e80-3a93-11e9-8607-b067cc8ad3e5.gif)

**Comment by fbojan** [comment]
Because I do not understand exactly what the # 9578 fix for wrong tax format is (7.3.2019), because it's in ver. 5.0.14 the tax still does not work properly. When testing, you must be careful to reopen the record again. Because at that time, the tax is 95% wrong.
