### ISSUE TITLE
I can't  upgrade the new version from 4.4 to 5 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9587]
# 🐞 bug report
Please help me how can i solve this errors
While executing the upgrade to version 4.4 to 5.0
[errors.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2887496/errors.txt)
[Uploading system.log…]()
[Uploading errors.log…]()

, I got the following: Error!!!
### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 4.4
| Web server (name and version)|	Apache	|
| PHP  |				7.2				|
| Browser (name and version)  | google chrome 		|
| Operating System (name and version)  | 	windows10	|
| Database (name and version) | 	MySQL	|

**Comment by mariuszkrzaczkowski** [comment]
attach the php and CRM logs
* cache/logs/phpError.log
* cache/logs/system.log

**Comment by guide5232** [comment]
[errors.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2888734/errors.log)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2888735/system.log)

**Comment by mariuszkrzaczkowski** [comment]
the phone number in the company's data is incorrectly entered

```
2019-02-20 17:53:34.9234 [error] - ERR_ILLEGAL_FIELD_VALUE||phone||1300880687
App\Exceptions\Security: ERR_ILLEGAL_FIELD_VALUE||phone||1300880687 in /home/yfprod/public_html/modules/Vtiger/uitypes/Phone.php:41
Stack trace:
#0 /home/yfprod/public_html/modules/Vtiger/models/Record.php(517): Vtiger_Phone_UIType->validate('1300880687')
#1 /home/yfprod/public_html/modules/Vtiger/models/Record.php(479): Vtiger_Record_Model->getValuesForSave()
#2 /home/yfprod/public_html/modules/Vtiger/models/Record.php(442): Vtiger_Record_Model->saveToDb()
#3 /home/yfprod/public_html/cache/updates/updates/init.php(392): Vtiger_Record_Model->save()
#4 /home/yfprod/public_html/cache/updates/updates/init.php(471): YetiForceUpdate->migrateCompanies()
#5 /home/yfprod/public_html/vtlib/Vtiger/PackageImport.php(991): YetiForceUpdate->update()
#6 /home/yfprod/public_html/vtlib/Vtiger/PackageImport.php(548): vtlib\PackageImport->importUpdate()
#7 /home/yfprod/public_html/modules/Settings/ModuleManager/views/ModuleImport.php(144): vtlib\PackageImport->import('cache/vtlib/use...')
#8 [internal function]: Settings_ModuleManager_ModuleImport_View->importUserModuleStep3(Object(App\Request))
#9 /home/yfprod/public_html/app/Controller/ExposeMethod.php(63): call_user_func_array(Array, Array)
#10 /home/yfprod/public_html/modules/Settings/ModuleManager/views/ModuleImport.php(34): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod('importUserModul...', Object(App\Request))
#11 /home/yfprod/public_html/include/main/WebUI.php(183): Settings_ModuleManager_ModuleImport_View->process(Object(App\Request))
#12 /home/yfprod/public_html/index.php(25): Vtiger_WebUI->process(Object(App\Request))
#13 /home/yfprod/public_html/public_html/index.php(11): require('/home/yfprod/pu...')
#14 {main}
```

**Comment by andrewchaosun** [comment]
YES. I had the same problem. It says the phone number is not correct. My phone number is correct. However, I can put another number (the ones the system "Thinks" it is correct).  Please if you can let me know how to change the phone number?

**Comment by mariuszkrzaczkowski** [comment]
example +481234567

**Comment by andrewchaosun** [comment]
Got that. Where can I change it, pls.

**Comment by andrewchaosun** [comment]
And more errors in #9523

**Comment by guide5232** [comment]
We have more number of tool free number like  this +61 1300 880 687,please tell us where should i remove that spaces in between the numbers

**Comment by andrewchaosun** [comment]
> I have entered correct phone number, but u saying incorrectly phone numbers We have more number of tool free number like this +61 1300 880 687,please tell us where should i remove that spaces in between the numbers

Where can you change the phone number, as I can not even found mine? I am facing a similar problem.

**Comment by guide5232** [comment]
I didn't change any phone number i am waiting for yetiforce team replay

**Comment by guide5232** [comment]
Software configuration---->Company information----->Company details

**Comment by andrewchaosun** [comment]
> Software configuration---->Company information----->Company details

Many thanks. Now mine is updated successfully.
