### ISSUE TITLE
[Question] Leads Status Pick List and system values.

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#9588]
Good day to you.

I started using YetiForceCRM for approx. 2 weeks now. I did some configuration adjustments in the System Admin section to fit our needs. Especially the Pick List section. And I encountered some "minor" issues.

I assumed that all system related values in pick list are locked. So, I started adjusting here and there. I did this also for the Leads Status pick list. I am able to delete and rename all the values, except for the value "Pending". So, I assumed that I was free to do so.

I renamed the majority of the values and added some others. I renamed **For conversion** into **For Conversion** to streamline to proper writing as I did for the other values also.

Everything is working, and I am able to work with the values in the CRM Leads section. Until I changed the status of a Lead to **For Conversion** to be converted. I wanted to press the upper right button to convert the Lead, but the button was missing. So I assumed that it had to do to something with the naming. So, I renamed back **For Conversion** to **For conversion** in the Lead Status pick list. And, I was hoping that the button would show now. Still nothing.

So I checked in the database and compared with a test database. I found out that the following values are standard values in **vtiger_leadstatus** table. These values are probably also referred to here and there throughout the CRM:
* PLL_TO_REALIZE
* PLL_CONTACTS_IN_THE_FUTURE
* PLL_LEAD_UNTAPPED
* PLL_LEAD_ACQUIRED
* PLL_PENDING
* PLL_IN_REALIZATION
* PLL_INCORRECT

I also found out that probably the best way to change these names is to change them in Language Management under System Tools.

So I renamed all the values back in the pick list to the (PLL_) values as mentioned above. And the Lead Status pick list now shows all the pick list values as encoded in the Language Management.

I also changed the field **presence** in the **vtiger_table** to be **0** for these records, similar to the **PLL_PENDING** record. So, now if I open the Lead Status pick list, it clearly states that all the above values (shown as encoded in the Language Management) are locked. I changed the naming afterwards as I wanted in the Language Management section.

Only issue now is that Language Management now shows a recycle bin next to the PLL_* fields that I previously had changed.

_**All is working well, but I don't know if this is the proper way of doing and also shall result in the required behavior or not. So, if you have any advise, please let me know. It is more than welcome and much appreciated.**_

A very nice CRM by the way. I have high hopes for the future of this CRM.

**Comment by alagmouch** [comment]
Ok. Thanks. Will wait.

**Comment by alagmouch** [comment]
Apologies for asking, but where you able to have some time to replicate the same?

**Comment by konadrian** [comment]
1) Remove leads status values, you can change them because you can manage when you would show the button
https://gitdeveloper.yetiforce.com/index.php?module=MarketingProcesses&view=Index&parent=Settings&block=6&fieldid=83
2) Default picklist values are stored in database in a special form because we translate these values to user language,
so If you want to change the value displayed to you, you can find the translations in a file under a language folder and change it, or you can use our Lang Managment module.
This recycle bin icon shows when you have translations in a language file and you are able to delete them

**Comment by alagmouch** [comment]
Hi @konadrian Thanks a lot. I understand both answer very clearly. So if I'm not mistaken, the only value which should be locked in the database and not possible to delete or rename is the status **Pending**? The rest is ok to do with what I want, as long as I define in the MarketingProcesses section the status that should be used for conversion, correct?

**Comment by konadrian** [comment]
We don't block any value, because you can decide when you want to convert lead into account.

**Comment by alagmouch** [comment]
Ok. Understood that indeed. Thanks.
