### ISSUE TITLE
PDF tool        

### ISSUE THREAD

**Issue by fbojan** [YetiForceCompany/YetiForceCRM#9590]
Suggestions or help! The final result of each work with CRM customers is sent to Sales Ivoice. The format and content of the document is different from user to user and right here is the biggest problem. In the current YETIFORCE PDF, it's almost impossible to adjust the font, color, and alignment. In one of the previous versions, you can also build reports like stock. quantity, value. We can export to an excel file, but it is not possible to add or group data. Does anyone know any tool with which to link to some data tables and easily create PDF Invoices or other documents.

**Comment by paula-w** [comment]
All the old mechanisms still exist in the system, you can assign different templates to different users, you can modify the colors and fonts. We generate different documents in the company, like quotes, invoices, and orders, and it all works as it should. If it doesn’t work for you, could you send us some screenshots?

As far as generating reports about stock, quantity, and value is concerned, it’s enough to write a small function to calculate it. 

Could you explain in more detail what the problem with adding and grouping data is?

**Comment by fbojan** [comment]
Thank you for the reply PAULA and of course I do not want to write anything without evidence and examples, so I will shortly open a new issue and I will describe my problems in more detail here. I hope that, of course, you are taking all of this as a positive critique that YETIFORCE will be in the fastest possible time number one CRM ...

**Comment by rafalpospiech** [comment]
> In the current YETIFORCE PDF, it's almost impossible to adjust the font, color, and alignment.

You can build your templates basing on tables to get different layout and element alingment.

Additional fonts you can install from this zip https://github.com/YetiForceCompany/YetiForceFonts/tree/master/zip

Text color and alignment should work, but you must add your styles **inline** - classes are not supported yet.

**Comment by MyBlissIT** [comment]
> > In the current YETIFORCE PDF, it's almost impossible to adjust the font, color, and alignment.
> 
> You can build your templates basing on tables to get different layout and element alingment.
> 
> Additional fonts you can install from this zip https://github.com/YetiForceCompany/YetiForceFonts/tree/master/zip
> 
> Text color and alignment should work, but you must add your styles **inline** - classes are not supported yet.

Hi, I am finding it hard to create a Quote PDF template, I do not know what to add and how to add it on "Edit Document Content" of the PDF Template Maker.
