### ISSUE TITLE
Product Categroy cannot be edited

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9593]
Hi, I want to add and rename some product categories and create subcategories. I went to field-folders, there it is not showing the product category tree. See the image below:

![image](https://user-images.githubusercontent.com/44740513/53161786-aa792500-35f0-11e9-877a-579ac107f279.png)

But in your demo site I have tested that it can be done. So please help to solve this problem.

Thanks

**Comment by vovpff** [comment]
@indrabhusanroy something broken. Trees should work perfect.

**Comment by indrabhusanroy** [comment]
yes but can you guide me to solve this..

**Comment by vovpff** [comment]
check dev console (F12 in Chrome) and erro logs!
Also try to put some stuff by `Add new item`

**Comment by indrabhusanroy** [comment]
Hi, I have now created a new installation where product categories are showing up in field folders, but everytime I try to change the name or even adding a new category, it showing a error message.

**Comment by vovpff** [comment]
@indrabhusanroy what message? My be you server configuration is wrong

**Comment by indrabhusanroy** [comment]
It seems everything is going okay now. I have another question regarding this. I have created some sub categories, but when I select a Subcategory while adding a new product, It does not selects the main category, only shows the subcategory selected. How can this be solved..

**Comment by vovpff** [comment]
![tree1](https://user-images.githubusercontent.com/8545791/53167425-f1631c80-35e8-11e9-8069-634dfdc2b691.gif)
I found this error.

**Comment by vovpff** [comment]
@arek1-618 it works!

**Comment by indrabhusanroy** [comment]
Hi, I am using yetifiorce 4.4, the above solution does not works for yetiforce 4.4. can you please help for yetiforce 4.4 as I don't want to update and change everything.

**Comment by vovpff** [comment]
@indrabhusanroy in 4.4 folders should work perfect!
I can't help you if you don't want to change something.
