### ISSUE TITLE
[question] Custom date range in filters

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#9595]
Hy all ! 

    I wanted to search for something using custom date range in filters but, in 5.0 is missing. Is it a temporary problem that has come with the update or its out from Yetiforce ? 
   I was using it very often to check activities, and it was helpful.

**Comment by arek1-618** [comment]
Hello, Sir.
I just checked "Custom date range in filters". It looks like it works. 
Could you tell me how to trigger the error?
![2019-02-26_14-43-19](https://user-images.githubusercontent.com/32322851/53417226-724d5a00-39d5-11e9-9897-5a3662696ad2.gif)
