### ISSUE TITLE
[Question]   How to add WYSIWYG styles and fonts on PDF modules like WYSIWYG on regular modules        

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#9596]
### Description

How can I add the styles from a regular WYSIWYG editor To the WYSIWYG PDF editor module as shown below. Currently if I add info at the regular WYSIWYG and then I export the info on a PDF document I get an error.

**WYSIWYG styles and fonts on regular modules:**

![image](https://user-images.githubusercontent.com/20831164/53188454-5f9ce480-35d3-11e9-99e4-cc293a61fd8b.png)

**WYSIWYG Styles and fonts on PDF Editor:**

![image](https://user-images.githubusercontent.com/20831164/53188351-24021a80-35d3-11e9-897e-40ca627d5649.png)

This is the error when I try to export a PDF document from a regular module:

![image](https://user-images.githubusercontent.com/20831164/53188563-ab4f8e00-35d3-11e9-9725-267a3b2cb77c.png)

**Comment by fbojan** [comment]
I have exactly the same issuie

**Comment by rafalpospiech** [comment]
If you need more fonts, just install this extension https://github.com/YetiForceCompany/YetiForceFonts/tree/master/zip

Explain in more details how to trigger this error also.

**Comment by z0lo13** [comment]
@aljoflo i have noticed since the update the new pdf noes not support margin:1px you have to specify -left-right-top-bottom separately, same with padding, also color like yellowgreen does not work

**Comment by rafalpospiech** [comment]
classes has arrived https://github.com/YetiForceCompany/YetiForceCRM/pull/9835
