### ISSUE TITLE
[Improvement] Decimal separator in the proposals, invoices, etc.

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#96]
In the proposal, calculations, accounts and so on, in the field where the sum is driven, it is necessary to check for integer divider that can be administered as a comma or a point, and let the system itself puts an end. In Russia, on the numeric keypad instead of a comma - and not convenient enough to constantly switch the keyboard to make your point

**Comment by KatarzynaUlichnowska** [comment]
Hello,
you can change the decimal separator in "My preferences". 
If that is not the case, we will require more info from you.
