### ISSUE TITLE
[Question] [PL] Problem z PDF

### ISSUE THREAD

**Issue by aplauz** [YetiForceCompany/YetiForceCRM#9601]
Dzień dobry,

mam kilka pytań dotyczących generowania PDF. Napotkałem kilka problemów.
1. Wyrównanie w kolumnie. Szablon przeniesiony z YF4.4.0 traci wyrównania do prawej. O tym ktoś raportował dziś fbojan https://github.com/YetiForceCompany/YetiForceCRM/issues/9590

2. Po osadzaniu zmiennych firmy np. logo ($(organization : 1|logo)$) pojawia się błąd:

![zrzut ekranu 2019-02-21 o 19 34 44](https://user-images.githubusercontent.com/46876516/53192887-cc35d480-360f-11e9-8d7a-b7bf712fca4f.png)

W bazie MySQL jest ID 1.
Można osadzić obraz za pomocą <img src="data:image/png;base64,iVBORw0KGgoA... a inne dane firmy wpisać na stałe ale jest to uciążliwe i chyba nie o to chodziło.

3. Wyjściowy plik PDF (bez żadnej grafiki) waży 2.3Mb a ten sam dokument w YF4.4.0 104 Kb (z grafiką).
Można jakoś odciążyć dokument?
![zrzut ekranu 2019-02-21 o 19 36 59](https://user-images.githubusercontent.com/46876516/53192979-1323ca00-3610-11e9-8d79-c1d184f2bfc4.png)

Wnętrze pliku również się różni:
![zrzut ekranu 2019-02-21 o 19 44 25](https://user-images.githubusercontent.com/46876516/53193410-2daa7300-3611-11e9-8512-ed49ab17550a.png)

CRM po update do 5.0.0

Pozdrawiam, Ireneusz Mazur

**Comment by neuronetio** [comment]
1. W yeti 5 jest nowy silnik generujący pdf i stare szablony (które z resztą były kiepskie) trzeba zrobić od nowa lub niebawem w sklepie pojawią się gotowce.
Jeżeli zainstalujesz na czysto 5 to powinieneś mieć kilka przykładów.
Zajrzyj też do https://github.com/YetiForceCompany/YetiForcePDF i zobacz które style css są obsługiwane a które już nie.

2. Zgaduję ale czy masz utworzony chociaż jeden oddział w Firma -> struktura organizacji? i czy jest tam dodane logo?

3. Rozmiar pliku jest spory ze względu na osadzone czcionki - w następnych wersjach czcionki mają być okrojone i zawężone tylko do znaków z których korzysta pdf
