### ISSUE TITLE
Main menu 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9607]
# 🐞 bug report
I have removed all sections and module  for sales department profile in menu configuration. 
![sales1](https://user-images.githubusercontent.com/47585969/53235799-d080f100-36e6-11e9-819b-90fc216e98fc.JPG)

I have given this profile to users 
![sales2](https://user-images.githubusercontent.com/47585969/53235800-d080f100-36e6-11e9-9823-4762358a4b80.png)

but still users are seeing  all main menu section and not modules .how can i remove main section from layout  

![sales3](https://user-images.githubusercontent.com/47585969/53235801-d1198780-36e6-11e9-8b14-94df9ef4d2ab.JPG)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 4.4
| Web server (name and version)|	Apache	|
| PHP  |								|
| Browser (name and version)  | 	google chrome	|
| Operating System (name and version)  | 	windows7	|
| Database (name and version) | 	MySQL 	|

**Comment by arek1-618** [comment]
Hello, Sir
In the last version, this problem does not occur.

**Comment by guide5232** [comment]
But I have faced this problem please give solution solution for that

**Comment by mariuszkrzaczkowski** [comment]
Upgrade to the latest version

**Comment by guide5232** [comment]
Ok thanks

**Comment by guide5232** [comment]
We have upgraded 5.0 but again we are getting this main menu problem please help me

**Comment by adudekyeti** [comment]
There is a problem with browser cache. After deleting items in menu, log out and log in on modified menu account. Additionally after that try to clear browser cache (Ctrl+Shift+Del in Google Chrome).
