### ISSUE TITLE
[bug]  Email templates information is not showed on Roundcube

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#9616]
# 🐞 bug report

### ⁉️ Describe the bug

 Email templates content description doens't show up on Roundcube

### 🔥 How to trigger the error

1. Create Email Template.
2. Go To RoundCube and select the created template
3. You will see the subject but not the content description of the email template created

### 👎 Actual Behavior

Content description is missing on roundcube after select an email template
### 👍 Expected Behavior

To see content description and subject on Roundcube email creating 
### 📷 Screenshot of configuration

1. Create email Template with content:
![image](https://user-images.githubusercontent.com/20831164/53254809-31320e80-3692-11e9-8ded-feaf8c0c46b8.png)

2. Select email template created on RoundCube:

![image](https://user-images.githubusercontent.com/20831164/53254858-4dce4680-3692-11e9-9194-e63fb9fcbc66.png)

3. See error, no information is showing up:
![image](https://user-images.githubusercontent.com/20831164/53254951-853cf300-3692-11e9-9d98-0559cff10c94.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
 No logs created

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0
| Web server (name and version)|		|
| PHP  |								|7.1
| Browser (name and version)  | 		|Chrome
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by z0lo13** [comment]
Can confirm this issue is on 5.0.0 however 5.0.4 working fine - please let us know how to fix that

**Comment by z0lo13** [comment]
@aljoflo I have found temporarily solution:
in file public_html/public_html/modules/OSSMail/roundcube/plugins/yetiforce/compose.min.js
remove 'use strict'; in the begining

**Comment by arek1-618** [comment]
This error only occurs on gitstable. On the git developer, everything works fine.
![chrome_2019-02-25_08-42-02](https://user-images.githubusercontent.com/32322851/53321642-53699d80-38d9-11e9-9cd0-40ba00f7c12b.png)

![2019-02-25_08-41-39](https://user-images.githubusercontent.com/32322851/53321693-772ce380-38d9-11e9-9ce8-c9f1216b2f4b.gif)

**Comment by z0lo13** [comment]
> 
> 
> This error only occurs on gitstable. On the git developer, everything works fine.
> ![chrome_2019-02-25_08-42-02](https://user-images.githubusercontent.com/32322851/53321642-53699d80-38d9-11e9-9cd0-40ba00f7c12b.png)
> 
> ![2019-02-25_08-41-39](https://user-images.githubusercontent.com/32322851/53321693-772ce380-38d9-11e9-9ce8-c9f1216b2f4b.gif)
@arek1-618 @mariuszkrzaczkowski 
so but the stable system is 5.0.0 not 5.0.5 what exactly been changed to have it working? Why the build name is stable if developer is more stable then stable built.

**Comment by aljoflo** [comment]
> This error only occurs on gitstable. On the git developer, everything works fine.
> ![chrome_2019-02-25_08-42-02](https://user-images.githubusercontent.com/32322851/53321642-53699d80-38d9-11e9-9cd0-40ba00f7c12b.png)
> 
> ![2019-02-25_08-41-39](https://user-images.githubusercontent.com/32322851/53321693-772ce380-38d9-11e9-9ce8-c9f1216b2f4b.gif)

May you please inform how can it be solved on Stable Version?

**Comment by alagmouch** [comment]
Hi @mariuszkrzaczkowski Is this issue still open? I did an update to 5.1.0 and afterwards also using the ServicePack to solve the **Share with users:** field, as per issue [9908](https://github.com/YetiForceCompany/YetiForceCRM/issues/9908) and all went well.

I was just testing something with the email templates in roundcube and encountered the same issue as above. After selecting the template in roundcube, the subject is filled from the template, but the body not.

I did as @z0lo13 mentioned above and changed **'use strict';** into **//'use strict';** in the file _public_html/public_html/modules/OSSMail/roundcube/plugins/yetiforce/compose.min.js_

This helped. Do you think you guys will be able to add something for this in the patch of Monday also?

**Comment by alagmouch** [comment]
This issue is till present in 5.1.0, even with the ServicePack. In case you wish to know. The fix does it though. But I don't know if that is the preferred way of course.
