### ISSUE TITLE
custom main menu loading 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9619]
# 🐞 bug report
When trying to create custom menus, some menus created no problem in the configuration but a few of the created menus as well as my defualt menu will not load. The loading cursor just spins and nothing ever happens.the custom menu is not effected on user page layout.i have restricted some module and section.modules are restricted but still users seeing the menu section names  
![reloding](https://user-images.githubusercontent.com/47585969/53317626-8420f580-3920-11e9-8dcc-5d7f1a378879.JPG)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0
| Web server (name and version)|	Apache	|
| PHP  |		7.1.x, 7.2.x, 7.3.x (dev)						|
| Browser (name and version)  | 	google chrome 	|
| Operating System (name and version)  | windows 7		|
| Database (name and version) | 	MySQL	|

**Comment by mariuszkrzaczkowski** [comment]
```
📝 PHP/Apache/Nginx/Browser/CRM Logs
Please send a part of logs that describes the circumstances when the error occurred to the following email address: github@yetiforce.com. 
DO NOT paste the logs in the issues, as they might contain sensitive info, such as credentials. 
The more info you provide, the quicker we will be able to solve your problem. 
Description how to enable logs can be found here: https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging 
Additionally, include a screenshot of your browser’s console (e.g. press F12 in Google Chrome).
ex. 

* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log 
```

logs

**Comment by guide5232** [comment]
[Importer.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2899923/Importer.log)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2899924/system.log)
[updateLogsTrace.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2899925/updateLogsTrace.log)
[errors.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2899933/errors.txt)



Once we enable error log the we getting below page 

![err](https://user-images.githubusercontent.com/47585969/53329554-6ebbc380-3940-11e9-9a21-29b83e6d5588.png)
