### ISSUE TITLE
edit user

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9620]
# 🐞 bug report
 I have updated latest version 5.0.after update the new version i am facing problem with user module .  whenever  i am editing user details  and trying to save the details  that time i am getting **Illegal value in field othereventduration (["Array"])** error 
![users edit2](https://user-images.githubusercontent.com/47585969/53320816-eaab1100-392a-11e9-94d5-c69c634626ed.png)

![authodication error](https://user-images.githubusercontent.com/47585969/53320444-cb5fb400-3929-11e9-9dea-3c87f6bb3ae9.JPG)
How should i rectify this error 

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0
| Web server (name and version)|	Apache	|
| PHP  |			7.1.x, 7.2.x, 7.3.x (dev)					|
| Browser (name and version)  | 	google chrome	|
| Operating System (name and version)  | 	windows 7	|
| Database (name and version) | 	mysql	|

**Comment by adudekyeti** [comment]
Please clear browser cache. If problem still exist please insert logs here.

**Comment by guide5232** [comment]
Now i am not getting any error but some user details page showing the differences between user to user
![users edit4](https://user-images.githubusercontent.com/47585969/53330518-cb1fe280-3942-11e9-9eb4-ceed5f5bee8c.png)

The user details page is showing difference between user to user.is this any effect on user event


![users edit5](https://user-images.githubusercontent.com/47585969/53330519-cbb87900-3942-11e9-944e-adfdda937611.png)

**Comment by adudekyeti** [comment]
It happened, because every user can have set individual event duration time.
