### ISSUE TITLE
[Question]           Problem z instalacją YetiForce na serwerze

### ISSUE THREAD

**Issue by MichalBol** [YetiForceCompany/YetiForceCRM#9621]
Witam,

mam pytanie, ściągnąłem Państwa CRM z poniższego źródła:
https://sourceforge.net/projects/yetiforce/

całość po rozpakowaniu wgrałem testowo tutaj:
http://swiatczekolad.pl/Crm

niestety po wielu próbach, nie odpala się instalacja systemu. Instalowałem wielokrotnie różne tego typu projekty, nigdy nie miałem z tym problemu, chodź znawcą tematu nie jestem, tutaj niestety nie mogę sobie poradzić.

Czy mogę prosić o wskazówkę, pomoc?

Pozdrawiam
Michał

**Comment by adudekyeti** [comment]
Witam,
Na początku proszę o zapoznanie się z dokumentacją umieszczoną na naszej stronie: [Instalacja CRM](https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/instalacja-crm).
Proszę również zweryfikować czy serwer spełnia wszystkie [wymagania](https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/wymagania-dla-serwera-www).
W przypadku gdyby nadal nie udało się uruchomić instalacji systemu, czy mogę prosić o umieszczenie logów, które pomogłyby nam w zlokalizowaniu problemu?

**Comment by bpabiszczak** [comment]
@MichalBol możemy też uruchomić system testowo na 30 dni u nas w chmurze, do tego czasu dobrze go poznacie i dopasujecie do siebie, potem możecie wziąć kopię i uruchomić u siebie. Jeżeli będziecie mieli problemy z instalacją, możecie również zamówić u nas usługę instalacji. 

Co do błędu, to najprawdopodobniej jest problem z plikiem htaccess [pewnie jakaś reguła nie jest przez serwera wspierana] lub zła wersja PHP [lub brak biblioteki] - to widać na pewno w logach serwera i tam należy szukać odpowiedzi.

**Comment by MichalBol** [comment]
Dziękuję Panie Błażeju za bardzo szybką reakcję .
Jaka wersja PHP jest wymagana , czytałem instrukcje instalacji, ale tam takich danych i na stronie nie znalazłem.
Postaram się znaleźć logi i pozwolę sobie przesłać.
Dziękuję za propozycje skorzystania z chmury, wolałbym jednak uruchomić całość na naszych serwerach.
Hosting mamy wykupiony w hekko.

Pozdrawiam
Michał Ból

Wysyłane z ProtonMail mobile

-------- Oryginalna wiadomość --------
Dnia 25.02.2019, 14:51, Błażej Pabiszczak napisał(a):

**Comment by bpabiszczak** [comment]
Wszystko jest opisane tutaj: https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-wdrozeniowa/item/wymagania-dla-serwera-www

**Comment by MichalBol** [comment]
Bardzo dziękuję, takich informacji potrzebowałem.
Udało mi się uruchomić system. Mam pewne poprawki do zrobienia z ustawieniami serwera ale teraz już jestem wstanie sobie ze wszystkim poradzić.

Dziękuję za pomoc zabieram się za testowanie.

Pozdrawiam
Michał Ból

Wysyłane z ProtonMail mobile

-------- Oryginalna wiadomość --------
Dnia 25.02.2019, 19:31, Błażej Pabiszczak napisał(a):
