### ISSUE TITLE
[bug] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'crmid' in 'where clause' Failed to prepare SQL: SELECT * FROM `vtiger_contactdetails_inventory` WHERE `crmid`=:qp0 URGENT: PROBLEM IN SAVING

### ISSUE THREAD

**Issue by andrewchaosun** [YetiForceCompany/YetiForceCRM#9625]
![image](https://user-images.githubusercontent.com/46634935/53328136-458d3a00-3924-11e9-8962-963d7cfbb666.png)

I had problem when save any contacts now. It worked well before. 
[Security errors.docx](https://github.com/YetiForceCompany/YetiForceCRM/files/2899825/Security.errors.docx)
![yetiforce_settings 6](https://user-images.githubusercontent.com/46634935/53328318-a74da400-3924-11e9-9e6c-c894fbd81f8b.png)

**Comment by arek1-618** [comment]
Hello Sir,
Please try to change the module type to "Base module"

**Comment by andrewchaosun** [comment]
> Hello Sir,
> Please try to change the module type to "Base module"

Dear Arek, Many thanks for the swift reply. Please kindly let me know how to change the Contact Nodule to Base Module.

**Comment by andrewchaosun** [comment]
This is my vtiger_contactdetails_inventory file.
![image](https://user-images.githubusercontent.com/46634935/53329713-a0746080-3927-11e9-9144-7fe3690bbc94.png)

**Comment by arek1-618** [comment]
Please try to do as below
![2019-02-25_12-39-33](https://user-images.githubusercontent.com/32322851/53335090-cd5e4e80-38fa-11e9-92a6-94c05679fd8a.gif)

**Comment by andrewchaosun** [comment]
> Please try to do as below
> ![2019-02-25_12-39-33](https://user-images.githubusercontent.com/32322851/53335090-cd5e4e80-38fa-11e9-92a6-94c05679fd8a.gif)

Dear Arek, Amazing. It is sorted. You are a STAR. Many thanks. Andrew
