### ISSUE TITLE
[bug] TextParser and mentions

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9626]
# 🐞 bug report

### ⁉️ Describe the bug

If some WYSIWYG field containing mention parsed by TextParser for PDF or Email there is `##ID##` appear.

Email

![image](https://user-images.githubusercontent.com/8545791/53329438-2202c900-38fd-11e9-99db-c6b55abf8679.png)

PDF

![image](https://user-images.githubusercontent.com/8545791/53329475-2e872180-38fd-11e9-91a2-45e1fbd62194.png)

### 👎 Actual Behavior

`##ID##`

### 👍 Expected Behavior

Should be search label

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  gitdev 5.0.4/stable 5.0.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by adudekyeti** [comment]
Hi,
Could you give me more informations how it should work?

**Comment by vovpff** [comment]
@adudekyeti As i think this should be like you can see in system GUI
I see this in system like this:
![image](https://user-images.githubusercontent.com/8545791/53419422-ea724a80-39ea-11e9-99c3-ad262af10306.png)

but in PDF and Email as `##CRMID##`

For Emails this mention can be clickable. This will be more useful

**Comment by adudekyeti** [comment]
Could you tell me why in PDF you want to use _##CRMID##_ instead of _$(record : subject)$_ ?
Do you want to set the same CRMID for every pdf/email?

**Comment by vovpff** [comment]
Sorry, I think there are some misunderstanding. I will explain one more time. For example I has IGDN with description what contains mention to another one IGDN:
![image](https://user-images.githubusercontent.com/8545791/53477198-3d004500-3a85-11e9-953f-673a4c5b38fd.png)

Source of description field:

```
Договор №КО-2019/24 от 12.02.2018<br />
<br />
Just for test&nbsp;<a data-id="#1412" href="#">I-GDN2 Cosmic 18.06.2014</a>
```

My PDF template contains this description of IGDN. PDF generated from this record does contain `##CRMID##` instead mentioned record subject.

![image](https://user-images.githubusercontent.com/8545791/53477589-11318f00-3a86-11e9-8ad4-00f404122bd3.png)

The same situation with Email notification what contains description field

![image](https://user-images.githubusercontent.com/8545791/53477671-3c1be300-3a86-11e9-88d8-d737e6c7aa84.png)

**Comment by vovpff** [comment]
will be cool if mentioned record inside email be clickable!
