### ISSUE TITLE
[bug] Buggy mentions or global search?

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9627]
# 🐞 bug report

### ⁉️ Describe the bug

I use next search labels for GDN modules: `Number` `Subject`.

1. Problem with number.

Number like `GDN-YY-No` - `GDN-19-19`

I can't find `GDN-19-19 blah blah blah` using mentions or global search if put `GDN-19-19`

2. Problem with subject. Subject usually contains `/` symbol (popular in Russia). 

I can't find record with label `GDN-19-19 2019/01` using mentions or global search if I put `2019/01`

Looks like symbols `-` and `/` buggy for global search and mentions.

Just tested on gitdev 5.0.4 with invoices:

![image](https://user-images.githubusercontent.com/8545791/53330286-2def8a80-38ff-11e9-91d6-ddbb82a9bb25.png)

![image](https://user-images.githubusercontent.com/8545791/53330314-3cd63d00-38ff-11e9-9299-4542c442b4f6.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.0.0.
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mlorencik** [comment]
If in the configuration in the GLOBAL_SEARCH_DEFAULT_OPERATOR variable we have 'FulltextBegin' or 'FulltextWord', special characters like - or / are treated as a word separation, and the search shows us the results that are the most relevant.

In the case type, the best solution is to set GLOBAL_SEARCH_DEFAULT_OPERATOR to the 'Contain' value, and the search should start with *, and  *2015/10/16 return us these specific records.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski @mlorencik 
v 5.2 SP13
Sorry for reopening. I can't use mentions for searching records what labels contains `-` and `/` symbols. I checked `GLOBAL_SEARCH_DEFAULT_OPERATOR` parameter and there is no affect to mentions.
Maybe I'm doing something wrong? Could you help?

**Comment by konadrian** [comment]
Please check it 
![GlobalSearch](https://user-images.githubusercontent.com/3193498/75527663-406d3a00-5a13-11ea-876e-562999a618fe.gif)
