### ISSUE TITLE
[bug] PDF name and slash

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9628]
# 🐞 bug report

### ⁉️ Describe the bug

I tried next filename for generated PDF `$(record : number)$ $(record : subject)$`

If subject of record contains some restricted symbols then only right part after symbol goes to file name.

As an example GDN called `Д КО-2019/24` and when exported as PDF has name `24.pdf`.

I know what symbol `/` strict for file names but this symbol very popular for file names and in Russia also.

I think this prohibited symbols should be replaced with something like `-` automatically at export action.   

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  stable 5.0.0 / gitdev 5.0.4 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by vovpff** [comment]
@mariuszkrzaczkowski sorry. Why ignored?

**Comment by mariuszkrzaczkowski** [comment]
there was no description, and now it is
