### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by T1133** [YetiForceCompany/YetiForceCRM#9632]
Hi,

I would like to ask for help with installation. my settings meet the all requirements, except security because i'm going to test Yeti. I did not configured SSL,.htaccess and public html. 

I fill up all fields and go farther for installation. Display "In program" and after few seconds, "Unsucesfull etc" 

I got these logs:

apaches error:
[Mon Feb 25 13:06:04.430159 2019] [mpm_prefork:notice] [pid 1399] AH00169: caught SIGTERM, shutting down
[Mon Feb 25 13:06:05.527518 2019] [mpm_prefork:notice] [pid 2651] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal oper$
[Mon Feb 25 13:06:05.527579 2019] [core:notice] [pid 2651] AH00094: Command line: '/usr/sbin/apache2'

127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/layouts/resources/app.js?s=$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/layouts/resources/Fields.js$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/libraries/jQuery-Validation$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/layouts/resources/helper.js$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/layouts/resources/ProgressI$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/layouts/resources/Tools.js?$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/libraries/tributejs/dist/tr$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/layouts/resources/Connector$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/libraries/blueimp-file-uplo$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/layouts/basic/modules/Chat/$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/libraries/jQuery-Validation$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/libraries/datatables.net-re$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/install/tpl/resources/Index$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/libraries/datatables.net-bs$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/libraries/datatables.net-re$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/libraries/datatables.net/js$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/vendor/ckeditor/ckeditor/ck$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:10 +0100] "GET /YetiForceCRM-5.0.0-complete/public_html/layouts/resources/Logo/logo$
127.0.1.1:80 ::1 - - [25/Feb/2019:13:06:16 +0100] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) (internal dummy connectio$
127.0.1.1:80 ::1 - - [25/Feb/2019:13:06:17 +0100] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) (internal dummy connectio$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:19 +0100] "POST /YetiForceCRM-5.0.0-complete/install/Install.php HTTP/1.1" 200 7917$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:29 +0100] "POST /YetiForceCRM-5.0.0-complete/install/Install.php HTTP/1.1" 200 4234$
127.0.1.1:80 10.134.40.17 - - [25/Feb/2019:13:06:38 +0100] "GET /YetiForceCRM-5.0.0-complete/install/Install.php HTTP/1.1" 200 11164$

What internal problem i can have?? Permissions were checked by installation wizard and it didn't report problem..   (Ubuntu) (internal dummy connectio$

**Comment by T1133** [comment]
As i search it's can be a problem with SSL. I'm looking for solution

**Comment by mariuszkrzaczkowski** [comment]
This is not an error log only access log
![github](https://user-images.githubusercontent.com/10198654/53390729-73aa6280-3994-11e9-919e-44967da89464.jpg)

**Comment by T1133** [comment]
Understood comment above. Lucky i fix te problem which was SSL protocol on my computer. After i configure it correctly YF install sucessfully. Thank you for will of help.
