### ISSUE TITLE
IMAP / SMTP servers not allowing domain name in user name are not supported

### ISSUE THREAD

**Issue by diderich** [YetiForceCompany/YetiForceCRM#964]
When configuring a "Mail client" and thereafter accessing e-mail, the system add the domain name to the user name specified (as indicated under "Domain (automatically added to login)"). Unfortunately our system uses a username only policy to login to the imap server.

Recommended change: The domain name is not added to the login name. The "Login to SMTP server" field should contain something linke %u@example.com if a domain is required for login and %u if no domain is required

**Comment by mariuszkrzaczkowski** [comment]
Did you try to enter an empty value to field "Domain (automatically added to login)" ?
