### ISSUE TITLE
[bug] After update v5.0 custom advance modules has sql errors

### ISSUE THREAD

**Issue by aljoflo** [YetiForceCompany/YetiForceCRM#9640]
# 🐞 bug report

### ⁉️ Describe the bug

Customs advance modules has errors after update from v4.0 to V5.0

### 🔥 How to trigger the error

I created two customs modules on v4.0. After I updated to v5.0 all my customs advance modules has the following error:

1. SQLSTATE[42S22]: Column not found: 1054 Unknown column 'crmid' in 'where clause' Failed to prepare SQL: SELECT * FROM `u_yf_productpricelist_inventory` WHERE `crmid`=:qp0

2. SQLSTATE[42S22]: Column not found: 1054 Unknown column 'crmid' in 'where clause' Failed to prepare SQL: SELECT * FROM `u_yf_productsquote_inventory` WHERE `crmid`=:qp0

### 👎 Actual Behavior

SQLSTATE error on custom advance module after updating
### 👍 Expected Behavior

To be able to use a custom advance module created on v4.0 in v5.0
### 📝 PHP/Apache/Nginx/Browser/CRM Logs

The only log error I see is on Updatelogtrace

YetiForceUpdate::preupdate| 2018-08-08 18:48:04
YetiForceUpdate::preupdate| 2018-08-08 18:48:04 | 0 mim.
YetiForceUpdate::update| 2018-08-08 18:48:04
YetiForceUpdate::dav| 2018-08-08 18:48:12
YetiForceUpdate::dav| 2018-08-08 18:48:14 | 0.03 mim.
YetiForceUpdate::updateScheme| 2018-08-08 18:48:14
YetiForceUpdate::dropIndex| 2018-08-08 18:48:15
YetiForceUpdate::dropIndex| 2018-08-08 18:48:16 | 0.02 mim.
YetiForceUpdate::updateScheme| 2018-08-08 18:48:16 | 0.04 mim.
YetiForceUpdate::addRecords| 2018-08-08 18:48:18
YetiForceUpdate::addRecords| 2018-08-08 18:48:18 | 0 mim.
YetiForceUpdate::updateData| 2018-08-08 18:48:18
YetiForceUpdate::updateData| 2018-08-08 18:48:19 | 0.01 mim.
YetiForceUpdate::updateCron| 2018-08-08 18:48:19
YetiForceUpdate::updateCron| 2018-08-08 18:48:19 | 0 mim.
YetiForceUpdate::removeModule| 2018-08-08 18:48:19
YetiForceUpdate::removeModule| 2018-08-08 18:48:19 | 0 mim.
YetiForceUpdate::workflowTask| 2018-08-08 18:48:19
YetiForceUpdate::workflowTask| 2018-08-08 18:48:19 | 0 mim.
YetiForceUpdate::addModules| 2018-08-08 18:48:19
YetiForceUpdate::postInstalModule | PermissionInspector | 2018-08-08 18:48:19
YetiForceUpdate::widgets | PermissionInspector | 2018-08-08 18:48:19
YetiForceUpdate::widgets | PermissionInspector | 2018-08-08 18:48:19 | 0 mim.
YetiForceUpdate::postInstalModule | PermissionInspector | 2018-08-08 18:48:19 | 0 mim.
YetiForceUpdate::postInstalModule | DataSetRegister | 2018-08-08 18:48:20
YetiForceUpdate::widgets | DataSetRegister | 2018-08-08 18:48:20
YetiForceUpdate::widgets | DataSetRegister | 2018-08-08 18:48:20 | 0 mim.
YetiForceUpdate::postInstalModule | DataSetRegister | 2018-08-08 18:48:20 | 0 mim.
YetiForceUpdate::postInstalModule | ActivityRegister | 2018-08-08 18:48:21
YetiForceUpdate::widgets | ActivityRegister | 2018-08-08 18:48:21
YetiForceUpdate::widgets | ActivityRegister | 2018-08-08 18:48:21 | 0 mim.
YetiForceUpdate::postInstalModule | ActivityRegister | 2018-08-08 18:48:21 | 0 mim.
YetiForceUpdate::postInstalModule | LocationRegister | 2018-08-08 18:48:22
YetiForceUpdate::widgets | LocationRegister | 2018-08-08 18:48:22
YetiForceUpdate::widgets | LocationRegister | 2018-08-08 18:48:23 | 0 mim.
YetiForceUpdate::postInstalModule | LocationRegister | 2018-08-08 18:48:23 | 0 mim.
YetiForceUpdate::postInstalModule | IncidentRegister | 2018-08-08 18:48:24
YetiForceUpdate::widgets | IncidentRegister | 2018-08-08 18:48:24
YetiForceUpdate::widgets | IncidentRegister | 2018-08-08 18:48:24 | 0 mim.
YetiForceUpdate::postInstalModule | IncidentRegister | 2018-08-08 18:48:24 | 0 mim.
YetiForceUpdate::postInstalModule | AuditRegister | 2018-08-08 18:48:25
YetiForceUpdate::widgets | AuditRegister | 2018-08-08 18:48:25
YetiForceUpdate::widgets | AuditRegister | 2018-08-08 18:48:25 | 0 mim.
YetiForceUpdate::postInstalModule | AuditRegister | 2018-08-08 18:48:25 | 0 mim.
YetiForceUpdate::addModules| 2018-08-08 18:48:25 | 0.1 mim.
YetiForceUpdate::updateLangFiles| 2018-08-08 18:48:25
YetiForceUpdate::updateLangFiles| 2018-08-08 18:48:25 | 0 mim.
YetiForceUpdate::addLanguages| 2018-08-08 18:48:25
YetiForceUpdate::addLanguages| 2018-08-08 18:48:25 | 0 mim.
YetiForceUpdate::addFields| 2018-08-08 18:48:25
YetiForceUpdate::addFields| 2018-08-08 18:48:26 | 0.01 mim.
YetiForceUpdate::actionMapp| 2018-08-08 18:48:26
YetiForceUpdate::actionMapp| 2018-08-08 18:48:28 | 0.04 mim.
YetiForceUpdate::updateSecondData| 2018-08-08 18:48:28
YetiForceUpdate::setTrees| 2018-08-08 18:48:28
YetiForceUpdate::setTrees| 2018-08-08 18:48:28 | 0 mim.
YetiForceUpdate::updateSecondData| 2018-08-08 18:48:28 | 0.01 mim.
YetiForceUpdate::updateConfigurationFiles| 2018-08-08 18:48:28
YetiForceUpdate::updateConfigurationFiles| 2018-08-08 18:48:28 | 0 mim.
YetiForceUpdate::update| 2018-08-08 18:48:28 | 0.4 mim.
YetiForceUpdate::postupdate| 2018-08-08 18:48:31
YetiForceUpdate::postupdate| 2018-08-08 18:48:32 | 0.01 mim.
YetiForceUpdate::update| 2019-02-14 21:32:39
YetiForceUpdate::migrateCalendarDefaultTime| 2019-02-14 21:32:40
YetiForceUpdate::migrateCalendarDefaultTime| 2019-02-14 21:32:40 | 0 mim.
YetiForceUpdate::imageFix| 2019-02-14 21:33:58
YetiForceUpdate::imageFix| 2019-02-14 21:33:58 | 0 mim.
YetiForceUpdate::attachmentsFix| 2019-02-14 21:33:58
YetiForceUpdate::attachmentsFix| 2019-02-14 21:33:58 | 0 mim.
YetiForceUpdate::migrateDefOrgField| 2019-02-14 21:33:58
YetiForceUpdate::migrateDefOrgField| 2019-02-14 21:33:58 | 0 mim.
YetiForceUpdate::addFields| 2019-02-14 21:33:58
YetiForceUpdate::addFields| 2019-02-14 21:34:02 | 0.07 mim.
YetiForceUpdate::updateData| 2019-02-14 21:34:05
YetiForceUpdate::updateData| 2019-02-14 21:34:06 | 0.02 mim.
YetiForceUpdate::addPicklistValues| 2019-02-14 21:34:06
YetiForceUpdate::addPicklistValues| 2019-02-14 21:34:06 | 0.01 mim.
YetiForceUpdate::removeEventsModule| 2019-02-14 21:34:06
YetiForceUpdate::removeWorkflowTask| 2019-02-14 21:34:07
YetiForceUpdate::removeWorkflowTask| 2019-02-14 21:34:07 | 0 mim.
YetiForceUpdate::removeEventsModule| 2019-02-14 21:34:07 | 0 mim.
YetiForceUpdate::updateCron| 2019-02-14 21:34:07
YetiForceUpdate::updateCron| 2019-02-14 21:34:07 | 0 mim.
YetiForceUpdate::removeFields| 2019-02-14 21:34:07
YetiForceUpdate::removeFields| 2019-02-14 21:34:07 | 0 mim.
YetiForceUpdate::migrateCvColumnList| 2019-02-14 21:34:07
YetiForceUpdate::migrateCvColumnList| 2019-02-14 21:34:10 | 0.06 mim.
YetiForceUpdate::updateHeaderField| 2019-02-14 21:34:10
YetiForceUpdate::updateHeaderField| 2019-02-14 21:34:11 | 0 mim.
YetiForceUpdate::removePbxManager| 2019-02-14 21:34:12
YetiForceUpdate::addModules| 2019-02-14 21:34:16
YetiForceUpdate::addModules| 2019-02-14 21:34:16 | 0 mim.
YetiForceUpdate::updateInventory| 2019-02-14 21:34:16
**YetiForceUpdate::updateInventory| Error: ProductsQuote, tablename: u_yf_productsquote_inventory
YetiForceUpdate::updateInventory| Error: ProductPriceList, tablename: u_yf_productpricelist_inventory**
YetiForceUpdate::updateInventory| 2019-02-14 21:34:25 | 0.15 mim.
YetiForceUpdate::update| 2019-02-14 21:34:26 | 1.77 mim.
YetiForceUpdate::postupdate| 2019-02-14 21:34:28
YetiForceUpdate::postupdate| 2019-02-14 21:34:29 | 0 mim.

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by TomaszQr** [comment]
Fixed via https://github.com/YetiForceCompany/UpdatePackages/commit/d92d29f0f48f43652dddebb04cd517893b1792db. Use this package  https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.0.0/4.4.0_to_5.0.0_v4.zip
