### ISSUE TITLE
[bug] Cant Create related module widget

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#9641]
# 🐞 bug report

### ⁉️ Describe the bug

Can't add widget with a related module. Any module, let's say leads to contacts, if you delete one developer you won't be able to add it.
### 🔥 How to trigger the error

1. Go to Module Widgets
2. Click on Add Widget
3. Scroll down to Related Module
4. Add any related module and fields
5. Nothing happens 

### 👎 Actual Behavior
bug

### 👍 Expected Behavior

no bug
### 📷 Screenshot of configuration

Gitdeveloper
### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Gideveloper

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/53389880-7061a780-3991-11e9-9982-d1cb926fb142.jpg)

**Comment by z0lo13** [comment]
> 
> 
> ![github](https://user-images.githubusercontent.com/10198654/53389880-7061a780-3991-11e9-9982-d1cb926fb142.jpg)

it is on your server http://gitdeveloper.yetiforce.com/, also described the bug as requested

**Comment by z0lo13** [comment]
so did you find the bug or you need more information?
