### ISSUE TITLE
[Question]Pdf Milestones and performance

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#9642]
### Description

After the 5.0.0 update it seems that yetipdf support less rules as well as provide less performance in creating large tables, as now you have to use strict table layout, would there be any milestones for pdf feature updates?

**Comment by mariuszkrzaczkowski** [comment]
can you attach a sample html file with which you have a problem?

**Comment by rafalpospiech** [comment]
We have plans to improve pdf engine a lot, but I don't really know right now when we will publish some enhancements.

**Comment by z0lo13** [comment]
@mariuszkrzaczkowski @rafalpospiech 
https://github.com/YetiForceCompany/YetiForceCRM/issues/16560
I have managed re-code the templates without floats and other rules but now the background-image become a problem.


```
<table border="1" cellpadding="1" cellspacing="1" style="font-size:8px; width:100%">
	<tbody>
		<tr>
			<td>
			<div style="background-image:url(image1.png)">Text1<br />
			text1<br />
			text1</div>
			</td>
			<td>
			<div style="background-image:url(image2.png)">Text2<br />
			text2<br />
			text2</div>
			</td>
		</tr>
	</tbody>
</table>
```

//Replace Image1 and Image2 with the images from your enviroment - the rule doesn't work, despite as it mentioned in Readme as a working rule. I have tried to use watermark div inside the div but the watermark actually could only be possible to place from the pdf template interface, if i am using the rule listed in the YetiforcePDF readme it doesn't work:

```
<div data-watermark style="text-align:center;">
    <div style="display:inline-block;font-size:20px;opacity:0.25;">
        <img src="Image.jpg">
    </div>
</div>

```
or to use <div data-watermark...... from [here](https://github.com/YetiForceCompany/YetiForcePDF/blob/developer/examples/PagesTables.html)

Could you please describe how to use watermark or background-image: rule in the pdf?- ussual implementiation wont work through the Pdf Interface, as the template i am creating doesn't need any background or watermark on first two pages.

**Comment by rafalpospiech** [comment]
use just `background:url('...')`

**Comment by rafalpospiech** [comment]
yetiforcepdf readme applies to standalone instance of the library in other systems.
Inside crm some features will not work because they have already implemented in crm like `<div data-watermark ...`

**Comment by rafalpospiech** [comment]
or u can use image inside watermark `<img src="" style="width:400px">` (added in pdf admin panel)
Images right now do not support height style because of some bug- specify width and height will be automatically calculated with proper aspect ratio

**Comment by z0lo13** [comment]
@rafalpospiech 
1. use just `background:url('...')` it does not work - i have to place the file into storage? and have the url like "https://gitdeveloper.yetiforce.com/storage/pdf/image.png" ot seems that the rule does not work...

i tried on gitdeveloper and it does not work there as well

`<div style="background:url('https://gitdeveloper.yetiforce.com/layouts/resources/Logo/logo')"></div>`

2. use image inside watermark `<img src="" style="width:400px">` how can i get use image inside watermark? if <div data-watermark cannot be added in html? when i am using div data-watermark it just places the image as a ussual div element, and evertything will be above or below it. 

could you please give a working sample code with an image?

**Comment by z0lo13** [comment]
@rafalpospiech 

```
Notice: Undefined variable: break in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1185

Notice: Undefined variable: break in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1185

Notice: Undefined variable: break in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1185

Notice: Undefined variable: break in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1185

Notice: Undefined variable: break in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1185

Notice: Undefined variable: break in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1185

Notice: Undefined variable: break in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1185

Notice: Undefined variable: break in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1185

Notice: Undefined variable: break in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1185

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vendor/yetiforce/yetiforcepdf/lib/Page.php on line 1310

```

Thats the error i got after the document template for 5 pages been generating _( it took maybe 5-6 minutes after the error appeared - the log is available in the gitdeveloper, i guess. ~18:50 EST.)_

**Comment by rafalpospiech** [comment]
@z0lo13 We have enabled Content Security Policy to not allow images from outside the domain.
You can try to set image src as base64 image (jpg, png)

Watermark settings are on the first page at the bottom of pdf layout configuration - try to use base64.

**Comment by rafalpospiech** [comment]
we are working on `Fatal error: Allowed memory size of ...` and couple of other bugs right now so be patient

**Comment by rafalpospiech** [comment]
undefined variable break fixed in https://github.com/YetiForceCompany/YetiForceCRM/pull/9735

**Comment by z0lo13** [comment]
> 
> 
> undefined variable break fixed in #9735

0.1.14 was adding unneccessary <br> instead oh spaces. break-word:normal didnt help, i have rolled back to 0.1.13

**Comment by mariuszkrzaczkowski** [comment]
> @rafalpospiech @mariuszkrzaczkowski
> 
> 1. use just `background:url('...')` it does not work - i have to place the file into storage? and have the url like "https://gitdeveloper.yetiforce.com/storage/pdf/image.png" ot seems that the rule does not work...
> 
> i tried on gitdeveloper and it does not work there as well
> 
> `<div style="background:url('https://gitdeveloper.yetiforce.com/layouts/resources/Logo/logo')"></div>`
> 
> 1. use image inside watermark `<img src="" style="width:400px">` how can i get use image inside watermark? if <div data-watermark cannot be added in html? when i am using div data-watermark it just places the image as a ussual div element, and evertything will be above or below it.
> 
> could you please give a working sample code with an image?

so that you can use pictures from external domains then you need to add the domain to trusted
https://github.com/YetiForceCompany/YetiForceCRM/blob/b93f3e64f6e91ddc24fc94b082ce680278c38476/config/Security.php#L92-L93

https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+PURIFIER_ALLOWED_DOMAINS+

**Comment by rafalpospiech** [comment]
@z0lo13 this is your template in browser with A4 format, what is the problem exactly with 0.1.14?
![image](https://user-images.githubusercontent.com/36499752/53788588-8b4c9280-3f22-11e9-8ebf-dd5a1e12c57b.png)

**Comment by rafalpospiech** [comment]
and here is rendered pdf in versio 0.1.14 - they looks the same
![image](https://user-images.githubusercontent.com/36499752/53788666-bc2cc780-3f22-11e9-9c00-99ecd6690f0d.png)

**Comment by rafalpospiech** [comment]
try to remove `&nbsp;` maybe it will help

**Comment by z0lo13** [comment]
> 
> 
> and here is rendered pdf in versio 0.1.14 - they looks the same
> ![image](https://user-images.githubusercontent.com/36499752/53788666-bc2cc780-3f22-11e9-9c00-99ecd6690f0d.png)

the problem is in my instance as i cant replicate the wrong rendering on gitdeveloper with the same code, but the problem is that i havent changed anything in pdf, it seems like it does not respect font-size and still rendering as it left untouched.

from gitdeveloper
http://prntscr.com/mtm2wi
from my instance with the 0.1.14
http://prntscr.com/mtm3bx


same code:

```
<table border="1" cellpadding="1" cellspacing="1" style="font-size:8px; width:100%">
	<tbody>
		<tr>
			<td style="width:40%">
			<table cellpadding="0" cellspacing="0" style="border-collapse:collapse; width:100%">
				<tbody>
					<tr>
						<td style="background-color:#dcdcdc; width:50%">Street streets:</td>
						<td style="width:50%">test test test</td>
					</tr>
					<tr>
						<td style="background-color:#dcdcdc; border-top-color:#4979aa; border-top-style:solid; border-top-width:1px">City:</td>
						<td style="border-top-color:#4979aa; border-top-style:solid; border-top-width:1px">test</td>
					</tr>
					<tr>
						<td style="background-color:#dcdcdc; border-top-color:#4979aa; border-top-style:solid; border-top-width:1px">Province:</td>
						<td style="border-top-color:#4979aa; border-top-style:solid; border-top-width:1px">test</td>
					</tr>
					<tr>
						<td style="background-color:#dcdcdc; border-top-color:#4979aa; border-top-style:solid; border-top-width:1px">Postal Code:</td>
						<td style="border-top-color:#4979aa; border-top-style:solid; border-top-width:1px">test</td>
					</tr>
					<tr>
						<td style="background-color:#dcdcdc; border-top-color:#4979aa; border-top-style:solid; border-top-width:1px">Dwelling Type:</td>
						<td style="border-top-color:#4979aa; border-top-style:solid; border-top-width:1px">test</td>
					</tr>
					<tr>
						<td colspan="2" style="background-color:#dcdcdc; border-top-color:#4979aa; border-top-style:solid; border-top-width:1px; text-align:center">Additional Pickup:</td>
					</tr>
					<tr>
						<td colspan="2">test</td>
					</tr>
					<tr>
						<td colspan="2" style="background-color:#dcdcdc; border-top-color:#4979aa; border-top-style:solid; border-top-width:1px; text-align:center">Additional Pickup:</td>
					</tr>
					<tr>
						<td colspan="2" style="border-bottom-color:#4979aa; border-bottom-style:solid; border-bottom-width:1px">test</td>
					</tr>
				</tbody>
			</table>
			</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</tbody>
</table>
```

is there any way to debug the pdf? i think it does not respect the font size prior rendering the width:

**Comment by rafalpospiech** [comment]
I'm working on performance right now, and the behavior from version 0.1.13 has been restored.
I will let you know when the new version 0.1.15 will be available

**Comment by rafalpospiech** [comment]
https://github.com/YetiForceCompany/YetiForcePDF/releases/tag/0.1.15
It seems to be much faster

**Comment by rafalpospiech** [comment]
and currently it generate something like this
![image](https://user-images.githubusercontent.com/36499752/53899904-87f8fa00-403b-11e9-9776-d55f5bcbf166.png)

**Comment by rafalpospiech** [comment]
https://github.com/YetiForceCompany/YetiForcePDF/releases/tag/0.1.17
YetiForcePDF is about 50% faster!
