### ISSUE TITLE
where we can delete error and change Server configuration in CRM

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9643]
where we can delete error and change Server configuration in CRM

​

Security configuration
Detected errors in the configuration of parameters related to system security. There may be problems with the system, or the entered data may be damaged or deleted. More information can be found in the article Web server requirements at yetiforce.com. Adjust the following parameters:

Server configuration
Server configuration was not set properly. There may be problems with the system, or the data entered may be damaged or deleted. More information can be found in the article Web server requirements at yetiforce.com. Detected problems:
Performance:
  opcache.enable_cli = 'cron: Off' (Recommended: 'On')
  opcache.interned_strings_buffer = 'cron: 8' (Recommended: '100')
  opcache.revalidate_freq = 'cron: 10' (Recommended: '30')
  realpath_cache_ttl = 'cron: 120' (Recommended: '600')
  mysqlnd.collect_statistics = 'cron: On' (Recommended: 'Off')

**Comment by vovpff** [comment]
this is PHP settings. Usually you can chage them in php.ini file

**Comment by adudekyeti** [comment]
Hi,
Here you have all informations about web server requirements:
[https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements)
