### ISSUE TITLE
In roundcube 0.0.66, I can not open the email templates

### ISSUE THREAD

**Issue by Bailundo** [YetiForceCompany/YetiForceCRM#9647]
# 🐞 bug report

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by adudekyeti** [comment]
Hi,
If you want to edit or add some email templates you need to go to: **_Databases > Email templates_** and set type as **_"Message"_**. 

Then you can use it in RoundCube: 
![image](https://user-images.githubusercontent.com/39482453/53415560-dcfc9680-39d1-11e9-8f6a-d820c3ae7b24.png)

**Comment by jimlee213** [comment]
I did check it. here is the screenshot:
thanks
![image](https://user-images.githubusercontent.com/44873199/80741575-dbec5b00-8ae7-11ea-86d8-f04db281a636.png)
