### ISSUE TITLE
ERROR IN TRANSLATIONS

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9654]
Hi, suddenly ADD RECORD BECOMES LBL_ADD_RECORD and this is happening everywhere. see the pic:

![image](https://user-images.githubusercontent.com/44740513/53417250-362cf000-39fb-11e9-828c-1e62e3ff317b.png)
 Please help...

Thanks

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/53417399-c9532f00-39d5-11e9-9884-3d49a75bb97f.jpg)

**Comment by mariuszkrzaczkowski** [comment]
What language ?

**Comment by indrabhusanroy** [comment]
English
 Yetifoce5.0

**Comment by indrabhusanroy** [comment]
sorry yetiforce5.0

**Comment by mariuszkrzaczkowski** [comment]
what did you change that you lost your language?
Was this the case after the installation?

**Comment by indrabhusanroy** [comment]
No, nothing changed and it has been second day when it happened suddenly.

**Comment by indrabhusanroy** [comment]
Hi, I just did a new install and again the same problem of translations happened.

**Comment by indrabhusanroy** [comment]
I just did a new installation and the same problem of translations exists.

**Comment by mariuszkrzaczkowski** [comment]
check what languages ​​you have in the languages ​​directory, try updating the translation you can do it from the panel https://gitdeveloper.yetiforce.com/index.php?module=LangManagement&parent=Settings&view=Index&block=4&fieldid=53

**Comment by mariuszkrzaczkowski** [comment]
attach configuration verification

**Comment by indrabhusanroy** [comment]
I have only english in language directory and there is a option to update and export only, does not shows the default button as it shows in the demo version of yours. Then I update the language, but the problem remains the same.

**Comment by rskrzypczak** [comment]
try to edit your account
https://gitdeveloper.yetiforce.com/index.php?module=Users&parent=Settings&view=List

**Comment by indrabhusanroy** [comment]
Thanks it worked, the language was not selected. Thank to all for your wonderful support..
