### ISSUE TITLE
[bug] 12 Hour Format Clock Picker is not working in 5.0.0

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#9659]
# 🐞 bug report

### ⁉️ Describe the bug

If you set up the user to use **12 hour format** - it will not be able to create any records from **Full  /Quick Edit View** to time fields as they are not saving. 
https://gitstable.yetiforce.com/index.php?module=OSSTimeControl&view=Calendar&mid=78&parent=76

### 🔥 How to trigger the error

1. Go to 'user setting and change time format to 12 hours'
2. Click on 'Time Control module' and go to full or quick edit view
3. Try to add any value 
4. nothing saves 

### 👎 Actual Behavior
Time does not change

### 👍 Expected Behavior
Time changes

### ❓ Additional context
It is working fine on gitdeveloper but i was not able to find any commit that describe exactly that bug - how to repair "stable 5.0.0" version

**Comment by z0lo13** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/9507/commits

are these commits that fixes that?

**Comment by vovpff** [comment]
I checked my system from smartphone. Clock picker appears but time can't be changed because you can click to any time and result in field will be "now" time. Something wrong.

**Comment by mlorencik** [comment]
Problem solved with new version, check on https://gitdeveloper.yetiforce.com/

**Comment by z0lo13** [comment]
> 
> 
> Problem solved with new version, check on https://gitdeveloper.yetiforce.com/

I mentioned that it is working on the gitdeveloper. how i enable it on my production? North America dont use 24 hours format
