### ISSUE TITLE
SLA date format

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9662]
# 🐞 bug report
I have given correct date format in user module 

![date format](https://user-images.githubusercontent.com/47585969/53462259-55795b00-3a97-11e9-806d-7bf63901fee4.png)

Whenever i am trying to create a tickets

![date6](https://user-images.githubusercontent.com/47585969/53462526-24e5f100-3a98-11e9-9926-b529d35a2012.png)

In tickets,if i select sla in ticket that time i got below error and without select sla in tickets i can able to save the ticket record 
![date2](https://user-images.githubusercontent.com/47585969/53462262-59a57880-3a97-11e9-9285-72355a3f5c47.png)

I have given correct date in service contract 
![date3](https://user-images.githubusercontent.com/47585969/53462268-5ca06900-3a97-11e9-9da0-4d5ab3bbbd4e.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mariuszkrzaczkowski** [comment]
Version , logs, ...
![github](https://user-images.githubusercontent.com/10198654/53467091-dfec9b00-3a54-11e9-8d9f-d61c04830cf0.jpg)

**Comment by guide5232** [comment]
# 🐞 bug report
I have given correct date format in user module 

![date format](https://user-images.githubusercontent.com/47585969/53462259-55795b00-3a97-11e9-806d-7bf63901fee4.png)

Whenever i am trying to create a tickets

![date6](https://user-images.githubusercontent.com/47585969/53462526-24e5f100-3a98-11e9-9926-b529d35a2012.png)

In tickets,if i select sla in ticket that time i got below error and without select sla in tickets i can able to save the ticket record 
![date2](https://user-images.githubusercontent.com/47585969/53462262-59a57880-3a97-11e9-9285-72355a3f5c47.png)

I have given correct date in service contract 
![date3](https://user-images.githubusercontent.com/47585969/53462268-5ca06900-3a97-11e9-9da0-4d5ab3bbbd4e.png)

[errors.txt](https://github.com/YetiForceCompany/YetiForceCRM/files/2908684/errors.txt)
[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2908685/system.log)

### ⁉️ Describe the bug






### 🔥 How to trigger the error


Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### 👎 Actual Behavior


### 👍 Expected Behavior


### 📷 Screenshot of configuration


### 📝 PHP/Apache/Nginx/Browser/CRM Logs



### 🌍  Your Environment 



| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0
| Web server (name and version)|	Apache	|
| PHP  |			7.1.x, 7.2.x, 7.3.x (dev)					|
| Browser (name and version)  | 	google chrome	|



| Operating System (name and version)  | 	windows7	|
| Database (name and version) | mysql	|

### ❓ Additional context
Add any other context about the problem here.
