### ISSUE TITLE
Automatize creating tickets when receiving mails

### ISSUE THREAD

**Issue by T1133** [YetiForceCompany/YetiForceCRM#9664]
Morning! :)

I'd like to ask is that possible to automatize creating tickets when receiving mails. I configured mailbox and use mail scanner to creating tickets for user and set observing folders for all in mailbox. That is correct? Fot tests i'm using gmail box. 

I'm using:
YetiForce 5.0.0 complete
I did not install CRON yet (will it help me with this issue?)

**Comment by T1133** [comment]
I have read on site the cron can be require to work scanner so i'm on it and let you know if it will not dispel my doubts

**Comment by T1133** [comment]
If i cannot find vtigercron.sh should i create it?

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-uzytkownika/item/enable-cron

**Comment by T1133** [comment]
Thank you but i saw it. I dont have vtigercron.sh in cron or vtlib directory. Cannot find it using command prompt. Instruction doesn't tell i should create it (maybe because it should be default) but if i don't have it it's mean something did not install?

**Comment by mariuszkrzaczkowski** [comment]
do you have an cron/cron.sh file?

**Comment by T1133** [comment]
Yes, i have

**Comment by mariuszkrzaczkowski** [comment]
```
*/5 * * * * sh /var/www/cron/cron.sh > /var/www/cache/logs/cron.log 2>&1 [pay attention to a correct path to the YetiForce system],

*/5 * * * * php /var/www/cron.php > /var/www/cache/logs/cron.log 2>&1
```

**Comment by T1133** [comment]
Ok so here must be set i though crontab -e and there

**Comment by mariuszkrzaczkowski** [comment]
I added additional methods to run the cron if there is a problem with PHP for the CLI
https://yetiforce.com/en/knowledge-base/documentation/administrator-documentation/item/enable-cron

**Comment by T1133** [comment]
Nice, thank you. For now everything working on! Tickets also :) such help is encouraging to purshase :)
