### ISSUE TITLE
[bug] Software Configuration 'Start' and 'System Warnings' not loading.

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#9686]
Anyone encountering the following at the moment?

The screen remains on **Loading** after you click in the System Admin section on **Summary**. The loading hangs on the tabs **Start** and **System Warnings**.

The **cache/logs/system.log** shows the following error:

`[error] - An error occurred: Could not resolve host: security.sensiolabs.org; Unknown error.`
`SensioLabs\Security\Exception\RuntimeException: An error occurred: Could not resolve host: security.sensiolabs.org;`

It seems that **security.sensiolabs.org** is offline. Also the domain **sensiolabs.org** has some issues. It started the day before yesterday, I believe.

Any workarounds for now?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/sensiolabs/security-checker/issues/149

**Comment by mariuszkrzaczkowski** [comment]
What is your CRM version?

**Comment by alagmouch** [comment]
Version 4.4.

**Comment by z0lo13** [comment]
> 
> 
> Anyone encountering the following at the moment?
> 
> The screen remains on **Loading** after you click in the System Admin section on **Summary**. The loading hangs on the tabs **Start** and **System Warnings**.
> 
> The **cache/logs/system.log** shows the following error:
> 
> `[error] - An error occurred: Could not resolve host: security.sensiolabs.org; Unknown error.`
> `SensioLabs\Security\Exception\RuntimeException: An error occurred: Could not resolve host: security.sensiolabs.org;`
> 
> It seems that **security.sensiolabs.org** is offline. Also the domain **sensiolabs.org** has some issues. It started the day before yesterday, I believe.
> 
> Any workarounds for now?
https://github.com/YetiForceCompany/YetiForceCRM/issues/8545
i had it for a couple month, hosting was trying to reslove it, cpanel trying to resolve it nothing helped - it was abnormal for my server so i had to migrate to another machine where installed everything from the scratch including apache and php, another solution is 5.0.0 which seems dont have an issue with this.

**Comment by mariuszkrzaczkowski** [comment]
in version 5.0.0 this problem has been solved, you need to update the entire library
it requires changes in the engine
