### ISSUE TITLE
[performance] got impression YF5 is slow

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#9689]
I have the impression that YF5 is pretty slow. Anyone noticed that or it just me>

**Comment by mariuszkrzaczkowski** [comment]
any specific places or the whole system?

**Comment by waran70** [comment]
I would say, it looks like the whole app gets kind of weight... 
Maybe some independent tools like https://tools.pingdom.com/ ?
Can you all guys help testing?

**Comment by waran70** [comment]
Ignore it. Testing with my mate, who messed with debug.php. All seems to be ok.

**Comment by acsinsurancegroup** [comment]
@waran70 Yeah I turned my debug on for another issue I'm getting help with and it slowed my system to a crawl and practically crashes the server. So in my case the Debug option is unusable.

**Comment by mariuszkrzaczkowski** [comment]
Check if you have the xgebug extension that is slowing down

**Comment by acsinsurancegroup** [comment]
@mariuszkrzaczkowski You mean xdebug? It was off and I turned it on and tried turning debug on again so I could get you the server logs for issue #9859 but same deal. Slowed my CRM to a crawl so had to disable the xdebug extension and turn off debugging in config file again and all is fast again.
