### ISSUE TITLE
Multi Mail Boxes

### ISSUE THREAD

**Issue by T1133** [YetiForceCompany/YetiForceCRM#9692]
Hello,

I have preoblem with adding more MailBox them 1. 

YetiForce 5.0.0 Complete
I configured CRON and Backups path.

I add a mailbox using "Mailbox - RoundCube", set all require deteils. Data save and mail box work with out problem. But when i try add new through "Mailbox - RoundCube" override each other and i'm losing previous settings :( I did it wrong way? 

I already checked requirements on website and other issues on git but they are about old verions 3.5 -3.8 of Yeti

**Comment by T1133** [comment]
Also i notice that system creating 2 ticets / 1 mail.

**Comment by T1133** [comment]
Any ideas what can be wrong?

**Comment by T1133** [comment]
I found confi/Modules/OSSMail.php and there are parametres which i set up but it doesn't look like i could add more mailboxes..

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/53734018-f47cc900-3e82-11e9-9314-5276a52175d6.png)
