### ISSUE TITLE
[Question]          Cron  Cpanel 

### ISSUE THREAD

**Issue by zimart** [YetiForceCompany/YetiForceCRM#9707]
### Description

Nie mogę poradzić sobie z cronem w wersji 4.4 
Miałem przesiąść się na 5.0 - ale nie działa mapowanie między modułami - póki co.

Nie wiem czy dobrze robię... ponieważ aktualizacja z 4.4 do 5.0 nie powiodła mi się na czystych systemach.

używam jeszcze wersji 3.2 - cron działa poprawnie przez wget.

Przy próbach z 4.4 mam ustawienia:

* | * | * | * | * | wget -q -O /dev/null "http://44.hosting-sanok.pl/cron.php" > /dev/null 2>&1 | 
 
* | * | * | * | * | /usr/local/bin/ea-php71 /home/panel44/public_html/cron.php 
 
* | * | * | * | * | /usr/local/bin/php /home/panel44/public_html/cron.php 
 
* | * | * | * | * | /usr/local/bin/php /home/panel44/public_html/cron/cron.sh

I zwrotki : 

cron.sh
#*********************************************************************************
# The contents of this file are subject to the vtiger CRM Public License Version 1.0
# ("License"); You may not use this file except in compliance with the License
# The Original Code is:  vtiger CRM Open Source
# The Initial Developer of the Original Code is vtiger.
# Portions created by vtiger are Copyright (C) vtiger.
# All Rights Reserved.
#
# ********************************************************************************

export CRM_ROOT_DIR=`dirname "$0"`/..
export USE_PHP=php
#export USE_PHP=/usr/local/php53/bin/php
#export USE_PHP=/usr/local/php56/bin/php56

cd $CRM_ROOT_DIR
# TO RUN ALL CORN JOBS
$USE_PHP -f cron.php 

Przy  /usr/local/bin/php /home/panel44/public_html/cron.php

Warning: require_once(include/ConfigUtils.php): failed to open stream: No such file or directory in /home/panel44/public_html/include/main/WebUI.php on line 11

Fatal error: require_once(): Failed opening required 'include/ConfigUtils.php' (include_path='.:/opt/cpanel/ea-php71/root/usr/share/pear') in /home/panel44/public_html/include/main/WebUI.php on line 11

przy : /usr/local/bin/ea-php71 /home/panel44/public_html/cron.php

Jak wyżej
Czy może ktoś poprowadzić ?

DODAM ZE W PANELU MAM - NP:
statnie uruchomienie crona:  7 sekund temu
Łączny czas:  0s

ale np - zadanie uruchomiono.. ileś tam czasu temu...

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/8170
