### ISSUE TITLE
[bug] Notifications stays forever

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#9709]
Whatever is done here (delete a record, switch off module etc) notifications in the right-top corner don't get away unless I reload tab.

**Comment by mlorencik** [comment]
what system version do you use? in the javascript error console something appears?

**Comment by waran70** [comment]
nothing in the console. The error does not exist in Chrome. FF stucks on those dialogs, so cannot even close it

**Comment by mlorencik** [comment]
I tested notifications on FF and Chrome, in both cases everything works fine at https://gitdeveloper.yetiforce.com/. I tested the appearance of a new notification (added in another tab), disappearing, marking as read, deleting and everything works, so you could describe the problem you have more accurately?

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/53642646-8fcb2f80-3c32-11e9-8249-652cf386b5f2.jpg)
