### ISSUE TITLE
[improvement] PDF templated & delete icon

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#9710]
In PDF templates list there are three icons on right, where red one deleting the record. 
The dangerous fact is when we press this icon, it just deletes a record without any confirmation dialog.
Would be cool to add it

**Comment by waran70** [comment]
Same in module manager :-)

**Comment by mlorencik** [comment]
there is no deletion in the module manager, so what action do you mean?

**Comment by waran70** [comment]
Custom modules can be removed.
