### ISSUE TITLE
[Question] Been asked to remove user profile    

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#9711]
Any shortcut to remove user panel icon from profiles which are not admins?

**Comment by paula-w** [comment]
Could you give us some more details, please? We're not sure what you want to achieve. Thanks.

**Comment by waran70** [comment]
Mean that user can change own preferences by clicking User icon (right top corner). Just wanna remove it from users profiles. Some use cases need such an approach.

**Comment by konadrian** [comment]
Disabling/Enabling this icon can be managed only by changing value of $SHOW_MY_PREFERENCES variable.
In the future access to "my preferences" will be blocked and it will be replaced by a different mechanism.

**Comment by JohnMaverick** [comment]
Hi Konradian, where should $SHOW_MY_PREFERENCES be placed? Did in Main.php but it not works

**Comment by vovpff** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/config/Security.php
