### ISSUE TITLE
*** Need Instructions on how to update to 5.0 ***

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#9723]
Please show step by step instructions on how to update to version 5.0
It is taking way too long for me to try to figure this out on my own.
There are no proper instructions for this. A video tutorial or screen shots would help a lot. Thanks

**Comment by z0lo13** [comment]
back up, _even better copy and test update on a copied instance._
Upload zip to update module in settings 
update
modify any custom edits you ve made to the code, also all custom modules have to be update to 5.0.0 manually

**Comment by vovpff** [comment]
1. Disable cron for you system.
2. Backup everything
3. Go to admin panel System logs - > Updates
4. Click upload update. Upload zip and start update process. 
5. If you have correct server configuraration you will get updated system in 5-10 minutes. 
6. Enable cron

**Comment by hobejeans** [comment]
Thanks for the info. I will try to follow the steps & let you know...

**Comment by hobejeans** [comment]
How do I disable Cron?

**Comment by vovpff** [comment]
What is your server? Some hosting?

**Comment by hobejeans** [comment]
I am using cPanel via Instafree hosing
I installed 5 months ago using saftaculous. In the app softaculous it shows me the link where the cron folder is located. 
home/.......................com/cron/cron.sh
home/.......................com/cache/logs/cron.log 2>&1

What code do I use to disable cron & where do I insert it?

**Comment by hobejeans** [comment]
I get this error when I go to 
Software configuration/Standard modules/Modules – Installation/System settings

![screen-capture](https://user-images.githubusercontent.com/45261773/53701377-912f6000-3dca-11e9-8306-02c03b74c174.jpg)

I increased the upload file size in my settings but I still get the same error message. Where exactly should I go to increase file upload size? Thanks

***Ok, so I figured out how to increase the upload file size. I changed under php option (**upload_max_filesize**). Now after uploading several times I get the error...

![error after uploading update](https://user-images.githubusercontent.com/45261773/53702522-ee7cde80-3dd5-11e9-94c8-3b556b1b3b21.jpg)

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by hobejeans** [comment]
What do you mean logs?

**Comment by vovpff** [comment]
I don't really know how to be with softaculous but you need to temporary disable this cron. Usually you can disamle by commenting line.
If you have error you need to check/share your logs

**Comment by mariuszkrzaczkowski** [comment]
### 📝 PHP/Apache/Nginx/Browser/CRM Logs
Please send a part of logs that describes the circumstances when the error occurred to the following email address: github@yetiforce.com. 
DO NOT paste the logs in the issues, as they might contain sensitive info, such as credentials. 
The more info you provide, the quicker we will be able to solve your problem. 
Description how to enable logs can be found here: https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging 
Additionally, include a screenshot of your browser’s console (e.g. press F12 in Google Chrome).
ex. 

* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log

**Comment by hobejeans** [comment]
Ok Thanks. I will get it over to you right away

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-uzytkownika/item/system-update

**Comment by paula-w** [comment]
@vovpff gave you complete instructions on how to update your system.

Usually 99% of all update problems result from the server’s limitations. We have a special environment in the company with extremely high limits to make the updates easier, as we update dozens of systems each month.

If there are any errors in your log please open a new issue and describe what the problems are, as this issue initially asked for instructions, which were provided. Thanks!
