### ISSUE TITLE
Test environment 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9724]
### Description

I am new for yetiforce CRM,I have worked on another CRM . in that CRM we have two separated environments,first one is testing environment another one is live production.once testing completed then after we deployed that code without disturb live production.

 This type of environments have we in yetiforce CRM

**Comment by vovpff** [comment]
Every time then you need you u can deploy full copy of your system, apply code and test.

**Comment by z0lo13** [comment]
> 
> ### Description
> 
> I am new for yetiforce CRM,I have worked on another CRM . in that CRM we have two separated environments,first one is testing environment another one is live production.once testing completed then after we deployed that code without disturb live production.
> 
> This type of environments have we in yetiforce CRM
copy you system to another subdomain, including db and use it for developing

**Comment by guide5232** [comment]
How can i do it Please  give some examples

**Comment by paula-w** [comment]
1. The files that you modified and tested can be moved to the production environment.
2. If you added any changes in the test database you also have to add these changes to the production database.

Unfortunately you have to do all that manually.
