### ISSUE TITLE
[Question]   what is this for?        

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#9725]
See attached. This is Reservations module. What is this red highlighted thing for?

![strange](https://user-images.githubusercontent.com/6852348/53683038-d43bf580-3d2e-11e9-8490-f5804492ae4b.jpg)

**Comment by vovpff** [comment]
This is list uf users ans list of available stuff fir reservation

**Comment by waran70** [comment]
for what it is here?
