### ISSUE TITLE
[Question] *Urgent* 12 Hour Format Clock Picker is not working on stable 5.0.0

### ISSUE THREAD

**Issue by z0lo13** [YetiForceCompany/YetiForceCRM#9727]
### Description
https://github.com/YetiForceCompany/YetiForceCRM/issues/9659

When are you planning to publish the fix for clockpicker? Currently any module related to time not usable in 12 hour format, it is a great problem for a north america.
Service pack 1 does not fix the issue

**Comment by konadrian** [comment]
We will prepare an update which will be a service pack that fixes this error. This update should be released by11.03
