### ISSUE TITLE
Problem with logo

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9731]
# 🐞 bug report
In version 4.4, We got company logo in email notification bottom but we are not getting company logo in version 5.0.
In have given $(organization : mailLogo)$  logo clipboard but no use
![logo code](https://user-images.githubusercontent.com/47585969/53716309-a37fcb80-3ea8-11e9-9166-9cfc59ad41bd.png)

In version 4.4 we have logo in bottom
![email2](https://user-images.githubusercontent.com/47585969/53716339-b72b3200-3ea8-11e9-9de9-9d3c69bf2371.png)

In version 5.0 We don't have logo in button 
![email logo](https://user-images.githubusercontent.com/47585969/53716333-b397ab00-3ea8-11e9-99c4-548fa0bcdf16.png)

I have copied this from $(organization : 1|logo)$ company details but we are getting another error 
![logo2](https://user-images.githubusercontent.com/47585969/53716321-ac709d00-3ea8-11e9-886d-faf2248b13c9.png)
![logo error](https://user-images.githubusercontent.com/47585969/53716316-a7135280-3ea8-11e9-8046-eea99a70afab.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0
| Web server (name and version)|	Apache	|
| PHP  |			7.1.x, 7.2.x, 7.3.x (dev)					|
| Browser (name and version)  | google chrome 	|
| Operating System (name and version)  | windows 7		|
| Database (name and version) | 	MySQL	|

**Comment by areksolek** [comment]
The logo is now downloaded from the Departments module Departments(MultiCompany).  You need to add a record there and assign a logo to the logo field. Then you have to choose from which company the logo will be downloaded. "$(organization :1|logo)$" Digits indicate the record number.

![image](https://user-images.githubusercontent.com/25615135/53733999-e9c23400-3e82-11e9-96e2-29269de10d12.png)

**Comment by guide5232** [comment]
We did not get any logo
![logo7](https://user-images.githubusercontent.com/47585969/53780909-9ae7cd80-3f5a-11e9-9e9a-febcd37b48d5.png)

**Comment by mariuszkrzaczkowski** [comment]
$(organization :1|logo|250)$

**Comment by acsinsurancegroup** [comment]
Hello I am having an issue with the 5.1 latest version install not displaying the YetiForce logo on the Login screen nor inside once you login at the top left corner by the company name. Just shows a broken code type image and the word Logo underneath. 

I right click on the where the image file should display and copy the image address which leads me to /public_html/layouts/resources/Logo/logo but at the end where it says logo there's no file extension whatsoever. Is that the issue and were would I change that so the Logo's show up? @mariuszkrzaczkowski

**Comment by acsinsurancegroup** [comment]
Does anyone have a suggestion or a solution for my question above? Thanks :)
