### ISSUE TITLE
[Question]  change database      

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#9732]
How to switch databases.? Got few clean installations (files) and want to switch same database between em

**Comment by vovpff** [comment]
put your database name and settings for every system to config.

**Comment by mariuszkrzaczkowski** [comment]
File: config/Db.php

![image](https://user-images.githubusercontent.com/10198654/53733125-4112d500-3e80-11e9-98e9-494d2d7c3256.png)
