### ISSUE TITLE
More them on Mailbox

### ISSUE THREAD

**Issue by T1133** [YetiForceCompany/YetiForceCRM#9736]
Hello,

Can i add more mailboxes them 1? 

Yetiforce 5.0.0 Complete
on ubuntu 16.04

**Comment by mariuszkrzaczkowski** [comment]
yes

**Comment by T1133** [comment]
OK, so when i save configuration in roundcube it's overrides settings. Not add new mail, how add more mailboxes?

**Comment by bpabiszczak** [comment]
![poczta](https://user-images.githubusercontent.com/10197525/53732608-c4332b80-3e7e-11e9-872d-29f2dfa78ff3.png)

**Comment by T1133** [comment]
Understood. Thank you
