### ISSUE TITLE
some strange action on My mailbox

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#974]
I test many mail server,some work well,some work has some problem.I find some strange action,when set the qq.com ,which imap.qq.com,smtp.qq.com;when login into the mailbox,the mail list is empty,but on the bottom status,it display the mail numbers.like this:
![snip20150601_1](https://cloud.githubusercontent.com/assets/12697896/7915506/8a2c7b1a-08b0-11e5-985c-b6533790a51d.png)

**Comment by bpabiszczak** [comment]
Please create a testing account and send us access data. There might be various reasons, but the most common one is that these servers can send a response for too long. Please read also this article: https://yetiforce.com/en/administrator-documentation/optimization/107-connection-to-the-mail-server.html
