### ISSUE TITLE
Select and apply more than one tax from the list of available Taxes

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9740]
Hi, can you please help me to select 3 tax instead of one from list of available taxes as I have a total of four tax to be applied on the products but currently I can apply two, one selected from the list of available taxes and the other from the custom tax. So If I can select three tax from the list of available tax, that will work. Please help me solve this problem..

Regards
Indra

**Comment by konadrian** [comment]
Could you attach an image or gif with more details

**Comment by indrabhusanroy** [comment]
Hi, I can select three tax from the list of available taxes but they are not applied while calculating the tax, only the first one is selected and the rest is not. See the pic below...
![image](https://user-images.githubusercontent.com/44740513/53817214-f92ca480-3f8a-11e9-937e-f660b54273dd.png)
Can you please help so that all the selected taxes are taken into calculation the total tax..
