### ISSUE TITLE
[Feature] How to do not clear quantity

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9748]
### Describe the solution you'd like

At 4.4 and older versions when you clear line in advanced module quantity of product/service was not cleared. This feature (or bug) was very useful because you can replace product/service very quick only by typing new name for search.

### Is your feature request related to a problem? Please describe.

No

### Describe alternatives you've considered

No ideas.

**Comment by konadrian** [comment]
This is not an error this works as it should works

**Comment by vovpff** [comment]
@konadrian I don't say what this is error. I said what in later versions product replacement was quicker and simpler. You never need keep in mind qty when replace products.
