### ISSUE TITLE
[bug] Pdf template print variables instead data

### ISSUE THREAD

**Issue by integrator2** [YetiForceCompany/YetiForceCRM#9749]
# 🐞 bug report

Pdf template print variables instead data
If I push "Export to PDF" button the system generate .pdf file from template but with variables instead data (screenshot)

### 🔥 How to trigger the error
If I push "Export to PDF" button the system generate .pdf file from template but with variables instead data (screenshot)
With any PDF template, new or embedded on system.
[447_goods_dispatched_note_1551622434_57.pdf](https://github.com/YetiForceCompany/YetiForceCRM/files/2928009/447_goods_dispatched_note_1551622434_57.pdf)

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 4.4.0
| Web server (name and version)|	ngnix	|
| PHP  |				7.0.0				|
| Browser (name and version)  | 	google Chrome	|
| Operating System (name and version)  | 	Ubuntu 16.04 or MacOS	|
| Database (name and version) | 		|

**Comment by vovpff** [comment]
@integrator2 i'm not sure but try to make one new PDF template for IGDN from scratch. Put variables what you need and check!

**Comment by rafalpospiech** [comment]
You have wrong variable names.
Paste your html code here.

**Comment by vovpff** [comment]
This is some old template what migrate from version to version and contains variables what not supported from 3.x versions

**Comment by integrator2** [comment]
It is ok but I cannot find crowdin.yml file on my system.
Could you help to find?

serveruser@Server030:~$ ls -l myYetiForce.com/
total 212
-rw-r--r--  1 serveruser serveruser   1441 Mar 20  2018 LICENSE
-rw-rw-r--  1 serveruser serveruser   5113 Mar 20  2018 README.md
drwxr-xr-x  3 serveruser serveruser   4096 Mar 20  2018 api
drwxrwxr-x  2 serveruser serveruser   4096 Mar 20  2018 backup
drwxrwxr-x 14 serveruser serveruser   4096 Mar  4 15:09 cache
-rw-r--r--  1 serveruser serveruser   2375 Mar 20  2018 composer.json
-rw-r--r--  1 serveruser serveruser 105461 Mar 20  2018 composer.lock
drwxrwxr-x  3 serveruser serveruser   4096 Mar  4 15:09 config
drwxrwxr-x  4 serveruser serveruser   4096 Mar 20  2018 cron
-rw-r--r--  1 serveruser serveruser   5430 Mar 20  2018 favicon.ico
-rw-r--r--  1 serveruser serveruser    650 Mar 20  2018 file.php
drwxrwxr-x 13 serveruser serveruser   4096 Mar 20  2018 include
-rw-rw-r--  1 serveruser serveruser   1052 Mar 20  2018 index.php
drwxrwxr-x  9 serveruser serveruser   4096 Mar 20  2018 languages
drwxrwxr-x  3 serveruser serveruser   4096 May 18  2016 layouts
drwxrwxr-x 11 serveruser serveruser   4096 Mar  4 15:09 libraries
drwxrwxr-x  2 serveruser serveruser   4096 Mar 20  2018 licenses
drwxrwxr-x 92 serveruser serveruser   4096 Mar  4 15:09 modules
drwxr-xr-x  8 serveruser serveruser   4096 Mar 20  2018 public_html
-rw-rw-r--  1 serveruser serveruser    188 Mar 20  2018 robots.txt
-rw-rw-r--  1 serveruser serveruser    686 Mar 20  2018 shorturl.php
drwxrwxr-x  9 serveruser serveruser   4096 Mar  4 15:09 storage
drwxrwxr-x  2 serveruser serveruser   4096 Mar  4 15:09 user_privileges
drwxr-xr-x 19 serveruser serveruser   4096 Mar 20  2018 vendor
drwxrwxr-x  5 serveruser serveruser   4096 Mar 20  2018 vtlib
-rw-r--r--  1 serveruser serveruser   3991 Mar 20  2018 webservice.php

**Comment by vovpff** [comment]
@integrator2 why you need it?

**Comment by integrator2** [comment]
because of this
https://github.com/YetiForceCompany/YetiForceCRM/pull/9747/files
Or how to make working template?
If the system use another variables I need ti have it. Or at lest several samples.

**Comment by rafalpospiech** [comment]
@integrator2  go to
https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=List&block=4&fieldid=35
or 
https://gitdeveloper.yetiforce.com/index.php?module=PDF&parent=Settings&view=Edit&record=33
and from top of the page you have all variables, just select what you need and click copy button on the right - paste it when you want to variable show up

you can also copy and paste invoice template as example

**Comment by rafalpospiech** [comment]
classes has arrived https://github.com/YetiForceCompany/YetiForceCRM/pull/9835

**Comment by integrator2** [comment]
I am sorry to tell that I have no result.
My system recognise only this variables:
$(translate : Other.PDF|LBL_STAGE)$:
$(translate : Other.PDF|LBL_COMMENTS)$

from list below:

$(translate : Other.PDF|LBL_COMMENTS)$
$(record : attention)$
$(translate : Other.PDF|LBL_STAGE)$: $(record : assigned_user_id)$

$(translate : FInvoiceProforma|SINGLE_FInvoiceProforma)$ $(record : number)$	$(translate : Other.PDF|LBL_SALE_DATE)$ $(record : saledate)$
$(translate : Other.PDF|LBL_SALE_DATE)$	$(translate : FInvoiceProforma|FL_PAYMENT_DATE)$	$(translate : Other.PDF|LBL_PAYMENT_METHOD)$
$(record : saledate)$	$(record : paymentdate)$	$(record : finvoiceproforma_formpayment)$
$(translate : Other.PDF|LBL_DEALER)$	$(translate : Other.PDF|LBL_BUYER)$
$(organization : 1|company_name)$
$(organization : 1|addresslevel8a)$ $(organization : 1|buildingnumbera)$
$(organization : 1|addresslevel7a)$ $(organization : 1|addresslevel5a)$
$(translate : Other.PDF|LBL_VATID)$: $(organization : 1|vat)$	$(relatedRecord : accountid|accountname|Accounts)$
$(relatedRecord : accountid|addresslevel8a|Accounts)$ $(relatedRecord : accountid|buildingnumbera|Accounts)$
$(relatedRecord : accountid|addresslevel7a|Accounts)$ $(relatedRecord : accountid|addresslevel5a|Accounts)$
$(translate : Other.PDF|LBL_VATID)$: $(relatedRecord : accountid|vat_id|Accounts)$
$(translate : FInvoiceProforma|SINGLE_FInvoiceProforma)$: $(record : number)$

$(custom : ProductsTableShortVersion)$
$(custom : TableTaxSummary)$	$(custom : TableDiscountSummary)$
$(custom : TableCurrencySummary)$	
$(translate : Other.PDF|LBL_TO_PAY)$
$(record : sum_gross)$
$(translate : Other.PDF|LBL_COMMENTS)$
$(record : attention)$
$(translate : Other.PDF|LBL_STAGE)$: $(record : assigned_user_id)$
$(translate : Other.PDF|LBL_SALE_DATE)$	$(translate : FCorectingInvoice|FL_PAYMENT_DATE)$	$(translate : Other.PDF|LBL_PAYMENT_METHOD)$
$(record : saledate)$	$(record : paymentdate)$	$(record : fcorectinginvoice_formpayment)$
$(translate : Other.PDF|LBL_DEALER)$	$(translate : Other.PDF|LBL_BUYER)$

$(organization : 1|company_name)$
$(organization : 1|addresslevel8a)$ $(organization : 1|buildingnumbera)$
$(organization : 1|addresslevel7a)$ $(organization : 1|addresslevel5a)$
$(translate : Other.PDF|LBL_VATID)$: $(organization : 1|vat)$
$(relatedRecord : accountid|accountname|Accounts)$
$(relatedRecord : accountid|addresslevel8a|Accounts)$ $(relatedRecord : accountid|buildingnumbera|Accounts)$
$(relatedRecord : accountid|addresslevel7a|Accounts)$ $(relatedRecord : accountid|addresslevel5a|Accounts)$
$(translate : Other.PDF|LBL_VATID)$: $(relatedRecord : accountid|vat_id|Accounts)$
$(translate : FCorectingInvoice|SINGLE_FCorectingInvoice)$: $(record : number)$

$(translate : Other.PDF|LBL_TO_FINVOICE_NUMBER)$: $(relatedRecord : finvoiceid|number|FInvoice)$
$(translate : FCorectingInvoice|LBL_BEFORE_CORRECTION)$
$(custom : ProductsTableCorrectingBefore)$
$(translate : FCorectingInvoice|LBL_AFTER_CORRECTION)$
$(custom : ProductsTableShortVersion)$
$(custom : TableTaxSummary)$	$(custom : TableDiscountSummary)$
$(custom : TableCurrencySummary)$	
$(translate : Other.PDF|LBL_TO_PAY)$
$(record : sum_gross)$
$(translate : Other.PDF|LBL_COMMENTS)$
$(record : attention)$
$(translate : Other.PDF|LBL_STAGE)$: $(record : assigned_user_id)$

**Comment by rafalpospiech** [comment]
update yetiforcecrm to latest version

**Comment by vovpff** [comment]
@rafalpospiech he works with 4.4.0 version. There are no new YetiForce PDF...

**Comment by dimitrisand** [comment]
Same problem here 
ubuntu 16
apache2
php7.3
yetiforce 5.1

Created PDF for calendar events
Only the name of the company shows up.
Two languages enabled English Default and Greek.
