### ISSUE TITLE
[Question] Exporting modules           

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/YetiForceCRM#9755]
In VT I could export modules with:

<?php
ini_set("error_reporting", "6135");
include_once 'includes/main/WebUI.php';
include_once 'vtlib/Vtiger/PackageExport.php';
include_once 'include/utils/utils.php';
require_once 'includes/Loader.php';
require_once('vtlib/Vtiger/Package.php');
require_once('vtlib/Vtiger/Module.php');
$package = new Vtiger_Package();
$package->export(Vtiger_Module::getInstance('Leads'),'test/vtlib','Leads_Export.zip',true);
echo '<pre>';
print_r("Lead module exported");
?>

Whats approch for YF?

**Comment by mlorencik** [comment]
I do not fully understand but when it comes to module export, you can export the customs modules in the module manager and then import from file. The data from modules is also easily exported or imported in list views.

**Comment by waran70** [comment]
Dont mean custom. Was able to export all vt modules in this way

**Comment by konadrian** [comment]
$moduleName = 'Leads';
$moduleModel = \vtlib\Module::getInstance($moduleName);
$package = new vtlib\PackageExport();
$package->export($moduleModel, '', sprintf('%s-%s.zip', $moduleModel->name, $moduleModel->version), true);

**Comment by waran70** [comment]
Fatal error: Uncaught Error: Class 'vtlib\Module' not found in /var/www/html/crm1/exportmod.php:3 Stack trace: #0 {main} thrown in /var/www/html/crm1/exportmod.php on line 3

**Comment by mariuszkrzaczkowski** [comment]
version of the CRM system?

**Comment by waran70** [comment]
5.1

**Comment by mariuszkrzaczkowski** [comment]
add this at the beginning of the file
```php
require __DIR__ . '/include/main/WebUI.php';
```

**Comment by waran70** [comment]
Hmm, things still troublesome:
- exported module zip file is wrecked (need to change zip to rar, unpack, zip again
- once done above, import got the problem with blocks.
- the imported module in this way don't refresh specific to module relations
**What I need to achieve is, to completely refresh module so it works like out of the box after fresh** 
Attaching my exported module.

[OSSEmployees.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/2993439/OSSEmployees.zip)

**Comment by paula-w** [comment]
Could you please open a new issue for the new problem you want to report? Otherwise it'll get messy.
Thanks!
