### ISSUE TITLE
Field Mask for Phone number is gone???

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#9756]
# 🐞 bug report

### ⁉️ Describe the bug
The field mask for phone numbers is missing in version 5. Is it removed from version:5 ?

### 🔥 How to trigger the error

1. Go to edit phone number field
2. Scroll down to Default value 

### 📷 Screenshot of configuration

![screenshot 2019-03-05 at 14 05 57](https://user-images.githubusercontent.com/21019034/53801337-f5c7f780-3f4f-11e9-819d-6ebf20d3b08b.png)
![screenshot 2019-03-05 at 14 06 10](https://user-images.githubusercontent.com/21019034/53801339-f791bb00-3f4f-11e9-9f17-27c80e2fd588.png)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mlorencik** [comment]
yes, the phone's mask has been removed for a refined field for this type of value. Masks have other fields, e.g. text or numeric
