### ISSUE TITLE
Converting Lead to Account

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#9763]
# 🐞 bug report
I can't convert Lead to Account anymore. 

This is silly But I changed the Lead Status fields to other names without reading https://github.com/YetiForceCompany/YetiForceCRM/issues/495  and then I realized I can't seem to convert the lead to account anymore

I tried to rename the field back to For Conversion but the dual arrow for Convert lead doesn't show up. 

I checked the custom field mapping but again futile. 

Does anyone know how can I get it fixed? 
 
![shit theme 3](https://user-images.githubusercontent.com/21019034/53837531-d2c73300-3fa3-11e9-9731-81ee62f2e9e6.gif)

### 🔥 How to trigger the error

https://gitdeveloper.yetiforce.com/
1. Go to     Software configuration
    Standard modules
    Fields – Picklists
2. Select Modules Leads
3.  Select picklist in Leads Lead Status
4. Edit Field name to Anything else
5. The arrow in below image disappears.

![screenshot 2019-03-05 at 22 42 45](https://user-images.githubusercontent.com/21019034/53833298-3b5ce280-3f99-11e9-9324-c87851438d14.png)

Edit it back to For Conversion and It sure doesn't work 

Here's how it looks 
![shit theme 3](https://user-images.githubusercontent.com/21019034/53836979-71529480-3fa2-11e9-9d09-b2488a6666a0.gif)

### 📷 Screenshot of configuration

Why is the "For Conversion" editable if it's such an important part of the Lead? How about make it non-editable to ensure no one else falls into the same pit. 
 
![shit theme 3](https://user-images.githubusercontent.com/21019034/53836747-d063d980-3fa1-11e9-900b-8fa817a345eb.gif)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by konadrian** [comment]
Here you can select which status allows converting lead
![image](https://user-images.githubusercontent.com/3193498/53859187-3883e100-3fdd-11e9-96cd-9eef232007be.png)
For conversion is editable because you can manage status like you wish. If you would like change this value as not editable. You need to set presence value to 0 in database in picklist table. In this case it is **vtiger_leadstatus**
