### ISSUE TITLE
***Update custom Modules for version 5.0***

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#9779]
1. I have installed a new instance version 5.0. I created custom modules using version 4.4 - when I try to import the module I get an error stating the modules are not compatible with version 5.0. How do I update the modules?
2. How do I export picklists from version 4.4 & import into 5.0?

**Comment by maeglin4** [comment]
yes , it would be nice to be able to import custom modules from V4.4 to V5.0 or 5.1

**Comment by bpabiszczak** [comment]
You need to correct the XML file of your module, there is a CRM version for which the module works.
