### ISSUE TITLE
[bug] record list can't be scrolled with touchscreen

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9783]
# 🐞 bug report

### ⁉️ Describe the bug

I have HP laptop transformer. When I tried touchscreen with yetiforce I found what this is impossible to scroll list of records. At gitdev with standard 20 records at list view I can see only 17-18 records in list (1920x1080 resolution)

### 🔥 How to trigger the error

1. Go to any module and try to scroll using touchscreen.

I don't have ideas how to record this bug.

### 👎 Actual Behavior

:(

### 👍 Expected Behavior

:)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.0.10, 5.0.0
| Web server (name and version)|		|
| PHP  |								|
| Browser (name and version)  | 		|
| Operating System (name and version)  | 		|
| Database (name and version) | 		|

**Comment by mlorencik** [comment]
can not you scroll down the table? I do not have a touch screen to test it, but it should work in the same way as on smartphones, so you should move the finger to further results

**Comment by vovpff** [comment]
@mlorencik I can scroll everywhere except lists what have this type of scrollbar
![image](https://user-images.githubusercontent.com/8545791/54114259-13d3a300-43fb-11e9-8613-cf001af8637b.png)
This is records list and lists in widgets at home page.

**Comment by poradz** [comment]
Please provide a screenshot of the dashbord view on your device. It would facilitate the diagnostic ;)
https://gitdeveloper.yetiforce.com/index.php?module=Home&view=DashBoard

**Comment by vovpff** [comment]
I have just usual HP laptop (win10, chrome) with touchscreen.
Also I have troubles with system from my android with latest chrome.
I will prepare sone videos next week

**Comment by vovpff** [comment]
@poradz 
Pls check videos
https://www.dropbox.com/s/kdatot5uttx120p/2019-07-29%2010.45.29.mp4?dl=0
https://www.dropbox.com/s/w038l7vdklzrkie/2019-07-29%2010.52.13.mp4?dl=0

**Comment by poradz** [comment]
Thanks for the videos @vovpff, we will fix those bugs soon.

**Comment by poradz** [comment]
The Android bug is already fixed on the current version (5.2.30) as well as touchscreen laptop issues. However, please let us know, if you still experience those issues on the current version.

**Comment by vovpff** [comment]
@poradz for Android scrolling works better 
For laptop: now I can't scroll list of records in list view...
