### ISSUE TITLE
[bug] YetiForce 5.0.0 forgets "HostName" during setup  

### ISSUE THREAD

**Issue by ajl-ewp** [YetiForceCompany/YetiForceCRM#9785]
Setting up on ubuntu with recommended settings and then going through the install process has an error. 

Database host name has underscores: yeti_mysql_1

No matter how many ways I put in a database host name (with or without http, trailing slash, no trailing slash, etc), YetiForce always forgets it in the "Confirm Configuration Settings" page. I've tested this on a couple machines, and get this error as well.

I have error display turned on in php.ini and no error is produced. I'm betting a variable name or form element name changed somewhere. It's just no populating that field.

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/53933211-83652d80-409d-11e9-9ffa-8dda54c12c75.jpg)

**Comment by vovpff** [comment]
`Database host name has underscores: yeti_mysql_1` means what DB name should me `yeti_mysql_1`

Are you want to use local or remote database?
