### ISSUE TITLE
[Question]          Reports Module - to be or not to be

### ISSUE THREAD

**Issue by cakrina** [YetiForceCompany/YetiForceCRM#9787]
Can we get a **definite answer** to the question about **future of the Reports Module** as controdictory answeres were given by Yetiforce team. 
Is it WIP and will be available in nearest releases or is it EOL unless somebody pays for it?
Please see your replies quoted below.

#7513 - "Good news. We have started building a report module." @bpabiszczak commented on Oct 9, 2018

#8706 - "Unfortunately we don’t have the time to finish it now; it will be released most likely not too long after we publish 5.0, so it will probably be available in 5.1" @paula-w commented on Jan 24

#9480 - "This is @bpabiszczak 's comment:We expanded the filter mechanism to allow users to display data from other modules. On top of that, charts can handle data from other modules than the main module. In our opinion both mechanisms (filters + widgets) give you the old reports functionality (of course it’s not exactly the same thing, but it can substitute the old module in 95%). Right now we’re not planning to add any changes to this functionality until we have a client who is willing to pay for developing the mechanism further." @paula-w commented 15 hours ago"

**Comment by paula-w** [comment]
As you see these posts are from October, January, and March. We were informing you about the module status/progress as the time passed. We thought this was better than not informing the community about anything. 
We abandoned the reports module in order to rewrite the engine. The new engine is called Vue - https://vuejs.org/. 
We don’t know when we can find a client who’d like to order the reports module, we can’t really guess the future.

**Comment by acsinsurancegroup** [comment]
@paula-w Reporting is a standard feature in all CRMS even the crappiest of systems. With YetiForce being probably the best out there in my opinion, why wouldn't there have been a focus on the very least some basic reporting?

Also, shouldn't there be a focus on a user being able to use various email accounts? For instance, why can't you create multiple accounts and have all those messages come into the system?

While I'm asking, is it possible to add some sort of functionality where you can API forms from like JotForm or one of the many other options out there?

Again, the above topics are the norm within almost every other system out there. I can't understand why the best system in the world hasn't implemented such basic functionality that is available elsewhere. Mind you there systems still suck and I would never use them, but you guys are geniuses.

No disrespect intended, just curious is all and are there any plans to catch up with the other systems in those areas? You can rest assured, you guys will surpass all others when you do.

Thanks for an awesome project, just trying to share some insight.

**Comment by paula-w** [comment]
This is @bpabiszczak’s response:
1. We tell you that there are the same reporting functionalities in the system, and you tell us there is no reporting. I don’t know what else to say about that.
2. You can have multiple email accounts in the system (for both – sending and receiving messages)
3. There’s API in the system, you can create any integration you wish using this API, and if something is missing it can always be added (it’s open source after all).

Our only disadvantage is the lack of proper documentation… we need time to fix that.

**Comment by acsinsurancegroup** [comment]
@paula-w @bpabiszczak Thanks for the response. Wow, I wasn't aware that it already did number two and three. I guess that would fall under the disadvantage of not having the documentation necessary which makes sense. 

Could you kindly point me in the right direction on where these multiple email accounts can be created? I mean as system user without Admin access where would I go to setup multiple email accounts? If I can't do this as a system user, being a system admin, where would I go to create this for the regular system users? 

As for the API with forms, I'm assuming this is done in the System settings menu under Integration and Web Service Applications and Users correct? After creating the necessary API's though, how would the form data be setup to come into the appropriate module like a Lead or Contact area?

The reporting aspect, I understand that you may see a lot of the information by playing with the widgets and what not but it's so much simpler to just have a reporting menu for the non techie user. Make sense? Not everyone knows how to use the system in the manner we do, so IMO it should be more end user friendly. 

Again, just offering some friendly insight and suggestions and absolutely no disrespect intended. Please let me know about the other two questions. Thanks guys, you're awesome.

**Comment by elvissaba** [comment]
Nice words and likes don't pay bills.
Crowd funding for top listed features on wishlist could be a good idea.
