### ISSUE TITLE
My mailbox send mail not via Outgoing Server? 

### ISSUE THREAD

**Issue by 1250572980** [YetiForceCompany/YetiForceCRM#979]
I delete the data of the Outgoing Server from datebase,after that,I send mail by My mailbox to lead,contact,it still work well.I want to know My mailbox use  smtp server  in iteself,not Outgoing server,
I want to know which use the Outgoing server,for example workflow?

**Comment by bpabiszczak** [comment]
Yes, only system [worflows, handlers etc.] use Outgoing Server.
