### ISSUE TITLE
Cron confiuration: cron.sh

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#9793]
Hello,

I'm fight with cron configuration. I used a instructions from website. Because wrond config of file system generate duplicates of tickets. The problem he report earlier was wrong End Line Syntax. Now he have problem with begin of line.. Any time i change something in file and trying test, few of first tickets create correctly but later duplicates are generating.

CRON.LOG ERROR:
22: /my_path/ cron/cron.sh: */5****: not found   

My path in file looks like that:  
*/5**** php /var/www/my_path/cron.php > /var/www/my_path/cache/logs/cron.log 2>&1  0x0A, \n

BETWEEN  "*/5****" and "php" and "/var...." are line spacing

![image](https://user-images.githubusercontent.com/21024857/53943576-ab648900-40bd-11e9-8b4c-dac77c2c4dbf.png)

**Comment by vovpff** [comment]
```
*/5 * * * * sh /var/www/cron/cron.sh
```

For line spacing you mean space?

**Comment by mariuszkrzaczkowski** [comment]
https://yetiforce.com/pl/baza-wiedzy/dokumentacja/dokumentacja-uzytkownika/item/enable-cron
