### ISSUE TITLE
Updates Missing for users except Admin. 

### ISSUE THREAD

**Issue by maninvatsa** [YetiForceCompany/YetiForceCRM#9815]
### Description

I am almost done setting up the Version 5. I ran into issues again. I have imported Accounts and Leads, Contact etc but I can't seem to figure out how do I enable the updates for other users? 

I tried to check the Module settings and all seems to be fine. The users can't see the changes in Accounts, Leads, Contacts and so on. 

![screenshot 2019-03-07 at 22 59 52](https://user-images.githubusercontent.com/21019034/53985494-ca4e3400-412c-11e9-9f14-bfd7da31003f.png)
![screenshot 2019-03-07 at 23 00 11](https://user-images.githubusercontent.com/21019034/53985497-cc17f780-412c-11e9-9c58-9de73c6b1492.png)

**Comment by paula-w** [comment]
The system automatically hides updates related to fields that a user has no permissions for. 
You can’t disable the “Updates” tab.
Please duplicate the issue on gitstable or gitdeveloper to help us investigate this problem.

**Comment by maninvatsa** [comment]
Thanks Paula. 

I am not trying to disable the updates tab. I am trying to figure out How can the updates be enabled for other users. i couldn't find the Updates modules for the permission. 

Where can I find the permission for the Updates Tab?

Thanks.

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?module=Profiles&parent=Settings&view=Edit&record=1
![image](https://user-images.githubusercontent.com/10198654/54028851-b21afb00-41a6-11e9-93d8-ee3069ed56ba.png)

**Comment by maninvatsa** [comment]
Thank you Marius. 

I have enabled the settings in Account, Leads and other modules. 

The users can see the Users and Review history but the users can't see the changes like the admin can. 

![screenshot 2019-03-07 at 22 59 52](https://user-images.githubusercontent.com/21019034/54029024-27db9280-41b8-11e9-8efa-28606271582c.png)
![screenshot 2019-03-07 at 23 00 11](https://user-images.githubusercontent.com/21019034/54029028-2a3dec80-41b8-11e9-9b9b-69f935954189.png)

**Comment by paula-w** [comment]
You can enable/disable updates only in profiles (there is no other mechanism), there might be something wrong with your system. Try to duplicate this issue on gitdeveloper or gitstable, if you can’t duplicate it then all you can do is hire a programmer to fix it for you (it would probably take an hour for us to fix but until we see it we won’t know for sure what the cause is and how much time it will take).
