### ISSUE TITLE
Create ticket from quick create

### ISSUE THREAD

**Issue by nunocosta78** [YetiForceCompany/YetiForceCRM#9817]
![tickets](https://user-images.githubusercontent.com/47648556/53993579-b7853080-4127-11e9-9010-977abf46c5d1.png)

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/54009501-5c752d00-416b-11e9-9093-d17b63b341f3.jpg)

**Comment by mrzewnicki** [comment]
You can change require fields if you don't want to assigne to Account all tickets.

**Comment by vovpff** [comment]
I found that there is not possible to change order of related modules. usually I work with customers and when create ticket Vendor usually on 1st place. every time I need to change every time to Account.

**Comment by mariuszkrzaczkowski** [comment]
![image](https://user-images.githubusercontent.com/10198654/54028622-e9d57300-41a5-11e9-9d76-36cec779d9f6.png)

**Comment by nunocosta78** [comment]
Thanks!
