### ISSUE TITLE
Tax Enhancement

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [YetiForceCompany/YetiForceCRM#982]
Hello, 
last week we received a suggestion from Christophe Humbert to add such enhancement:
https://wiki.vtiger.com/vtiger6/index.php/Tax_Enhancement

This enhancement would allow to manage local and international tax rates and it would work on the same basis as in Vtiger On Demand.

**Comment by waran70** [comment]
Definitely good idea. This option will expand scope of users definitely. Some of my customers got problems with compound tax. For this I managed to mess with negative values but I am still afraid it might create issues later on

**Comment by KatarzynaUlichnowska** [comment]
Polish translation of the functionality: 

![image](https://cloud.githubusercontent.com/assets/10218164/8081345/42d54358-0f74-11e5-8382-6878cbfcec3a.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081353/530706ee-0f74-11e5-966d-7ecfcbe69bfb.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081357/5bcd3348-0f74-11e5-8d8b-1ddc4e739b65.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081364/62c74648-0f74-11e5-90d1-8b7911ca3057.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081366/6a559978-0f74-11e5-9330-de6faaf05de1.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081368/7294f7d2-0f74-11e5-99af-2d2469408485.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081377/86dc3f48-0f74-11e5-8b84-0293597ea587.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081380/8ea74dbc-0f74-11e5-938b-3f7bc23bd72e.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081383/96b3b6da-0f74-11e5-88ff-f0e6845e72c1.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081387/9d3438ae-0f74-11e5-94a7-e67bb62558c9.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081394/a7e0a3b4-0f74-11e5-9cff-c5afd77a4bd0.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081397/b0bede1a-0f74-11e5-9853-e82f6b227632.png)
![image](https://cloud.githubusercontent.com/assets/10218164/8081431/fb191228-0f74-11e5-82f2-09c543508ec3.png)

**Comment by florek41** [comment]
Agree, good idea.

Additionaly I think that in we should have possibility to set default tax type in Settings  - Group or Individual.
For ex. in Poland we have individual tax and we need to change tax type for every new entity.

**Comment by bpabiszczak** [comment]
The work principles of tax in the new module will be redesigned from scratch. The new work principles will be described in the manual. Once a new functionality appears and there are some questions please open a new issue. The new module will be ready for testing in a little over a week.
