### ISSUE TITLE
[Question]   Class 'Locale' not found

### ISSUE THREAD

**Issue by MyBlissIT** [YetiForceCompany/YetiForceCRM#9821]
Hi,

I updated YetiForce from version 4 to Version 5 and I could not gain access to the new site. Alternatively, I "removed" version 4 and installed version 5.

On the "Install" page, I am now getting this error = "Class 'Locale' not found" How can I resolve this?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue++Locale

https://github.com/YetiForceCompany/YetiForceCRM/issues/9482
https://github.com/YetiForceCompany/YetiForceCRM/issues/9520

**Comment by MyBlissIT** [comment]
> https://github.com/YetiForceCompany/YetiForceCRM/issues?utf8=%E2%9C%93&q=is%3Aissue++Locale
> 
> #9482
> #9520

When I click on this link I am redirected back to this Reply, which it doesnt have a solution.

Also, why do you "Close" a Question within minutes of your reply, without awaiting response from the person who posted it?

**Comment by davidtaylorjr** [comment]
I am having the same issue.

**Comment by MyBlissIT** [comment]
Please ensure that 1. You are using the latest php version and 2. That your
php installs include all those found on YetiForce web server requirements.

*N.B. I am not in front of a PC hence I have not attached screenshots.



Kind Regards


Sinethemba Gayiza
Cell: 073 543 4118
Fax: 086 275 4572
www.gayiza.wordpress.com

AN ACKNOWLEDGEMENT OF RECEIPT WILL BE APPRECIATED!!!!!!

This email is intended only for the person to whom it is address and/or
otherwise authorized personnel. The information contained herein and
attached is confidential and the property of SINETHEMBA GAYIZA. If you are
not the intended recipient, please be advised that viewing this message and
any attachments, as well as copying, forwarding, printing, and
disseminating any information related to this email is prohibited, and that
you should not take any action based on the content of this email and any
attachment. Please note that the views and opinions expressed herein are
solely those of the author and do not necessarily reflect those of the
company. While antivirus protection tools have been employed, you should
check this email and attachments for the presence of viruses. No warranties
or assurances are made in relation to the safety and content of this email
and attachments. SINETHEMBA GAYIZA accepts no liability for any damage
caused by any virus transmitted by or contained in this email and
attachments. no liability is accepted for any consequences arising from
this email.

**Comment by mariuszkrzaczkowski** [comment]
> Also, why do you "Close" a Question within minutes of your reply, without awaiting response from the person who posted it?

Posts contain comprehensive information, no more comments required

https://github.com/YetiForceCompany/YetiForceCRM/issues/9482#issuecomment-463541359
https://github.com/YetiForceCompany/YetiForceCRM/issues/9482#issuecomment-470963564
https://github.com/YetiForceCompany/YetiForceCRM/issues/9482#issuecomment-471056759
