### ISSUE TITLE
Prohibit: Delete record from system

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#9825]
Hello,

I would like to refuse permissions to completely deleting the records for normal users. I'd like to allow them move record to trash but no destroying it by one click.
is that possible using standard permissions or i must active advanced?

Yetiforce 5.0.0 complete on ubuntu 16.04

**Comment by bpabiszczak** [comment]
W systemie są trzy akcje:

1. Do archiwum
2. Do kosza
3. Do usunięcia

Profilami decydujemy kto jakie akcje może używać. W menu można dodać sobie kosz, aby przeglądać wszystkie rekordy ze wszystkim modułów wrzucone do kosza.

**Comment by mrzewnicki** [comment]
Dziękuje za odpowiedź, odznaczyłem opcje usuwania w rekordzie ale to wciąż pozostawiło mi opcje "Usuń rekord z systemu" a jej bym nie chciał, bo jeśli dobrze rozumiem to ona nieodwołalnie usuwa rekord z systemu.

![image](https://user-images.githubusercontent.com/21024857/54028007-ca3d4b00-41a3-11e9-96a9-ba8111dd6de1.png)

**Comment by mrzewnicki** [comment]
@bpabiszczak  Czy to jest jakiś błąd czy coś źle robie?

**Comment by bpabiszczak** [comment]
hmm niestety nie wiem czy dobrze to zrobiłeś czy nie, nie wiem co znaczy, że odznaczyłeś. Może zrobiłeś to na złym profilu... Może wywołaj ten problem na gitdeveloper nagrywając film lub dokładnie opisując co robisz.

**Comment by mrzewnicki** [comment]
ok, tak zrobię. dziękuje
