### ISSUE TITLE
[Question] Edit default "Industry" row          

### ISSUE THREAD

**Issue by sz4dy** [YetiForceCompany/YetiForceCRM#9831]
How can I edit default "Industry" row when adding new "Accounts" ?
I would liek to change it to multi choice instead of single choice. 
There is no way to delete default row.. or change. Or am I missing something?

**Comment by mlorencik** [comment]
deletion as well as change of the field type requires in this case changes directly in the database, however, from the system level you can deselect the active field and the field will be hidden
