### ISSUE TITLE
Skaner mailowy wybór folderów

### ISSUE THREAD

**Issue by itnet24** [YetiForceCompany/YetiForceCRM#9836]
Witam
podczas próby wybrania folderów dla skanera cały czas jest komunikat jak na załączonym zrzucie.
![yetiforce_skaner_mailowy_foldery](https://user-images.githubusercontent.com/48365279/54050832-8583d500-41e0-11e9-977d-8a75061b6304.jpg)

**Comment by konadrian** [comment]
Czy pojawia się coś w logach?

**Comment by bpabiszczak** [comment]
Proszę uaktualnić system do najnowszej wersji.
