### ISSUE TITLE
[Question] PDF generation fails, undefined function call

### ISSUE THREAD

**Issue by nikolateslax** [YetiForceCompany/YetiForceCRM#9837]
Hi guys, I've scoured up and down the issue tracker and am having a crazy time pinning down my problem. Working on a custom template, with a custom parser, for PDF-exporting quotes. However, I'm now getting `Call to undefined method YetiForcePDF\Layout\BlockBox::appendTableRowGroupBox()` as an error on generation. Maybe this is just me, which is why it's posted under questions. Any ideas what's wrong here? Output from system.log, my custom TextParser, and my template, are at the link below. Thanks for any help!

http://mini.nikolateslax.net/yetiforce.txt

**Comment by vovpff** [comment]
I can check only what `BlockBox.php` does not contain `appendTableRowGroupBox` function.

**Comment by nikolateslax** [comment]
I can confirm that `BlockBox.php` does not contain a function definition for `appendTableRowGroupBox`. My `/vendor/yetiforce/yetiforcepdf` directory is stock. Line 267 is the only place in that file this text exists. As a test, I re-extracted that directory from the `YetiForceCRM-5.0.0-complete.zip` archive, with the issue remaining.

BlockBox.php: https://github.com/YetiForceCompany/YetiForcePDF/blob/developer/lib/Layout/BlockBox.php

Problematic call in ElementBox.php: https://github.com/YetiForceCompany/YetiForcePDF/blob/developer/lib/Layout/ElementBox.php#L267

**Comment by vovpff** [comment]
@rafalpospiech pls take a look for this issue

**Comment by rafalpospiech** [comment]
Paste your html code here.
BlockBox should not contain any TableRowGroupBox elemenent - only TableBox.
I can't tell anything for now, I must se html code to investigate this issue.

**Comment by rafalpospiech** [comment]
yeah something weird happened in ElementBox - I've did not change table-footer-group behaviour - maybe it is a php formatter plugin that have messed my code lately. I will fix this, thanks

**Comment by rafalpospiech** [comment]
paste some html code here :)

**Comment by vovpff** [comment]
@rafalpospiech check txt file in first post. There are PDF template and custom function.

**Comment by nikolateslax** [comment]
I know you guys are busy, so I'll go ahead and pop this in here for you.

    <div style="font-size:9px;width:100%;">
    <table border="0" cellpadding="1" cellspacing="1" style="width:100%">
    	<thead>
    		<tr>
    			<th scope="col" style="text-align:left;font-size:12px;">Requested Quote -&nbsp;$(record : subject)$</th>
    		</tr>
    	</thead>
    	<tbody>
    		<tr>
    			<td>Reference #$(record : RecordId)$ - Generated&nbsp;$(general : CurrentDate)$</td>
    		</tr>
    	</tbody>
    </table>
    
    <table border="0" cellpadding="1" cellspacing="1" style="width:100%">
    	<thead>
    		<tr>
    			<th scope="col" style="text-align:left; width:34%">Service Provider</th>
    			<th scope="col" style="text-align:left; width:33%">Service Recipient</th>
    			<th scope="col" style="text-align:left; width:33%"></th>
    		</tr>
    	</thead>
    	<tbody>
    		<tr>
    			<td>Business</td>
    			<td>$(relatedRecord : accountid|accountname|Accounts)$</td>
    			<td></td>
    		</tr>
    		<tr>
    			<td>Addr 1</td>
    			<td>$(record : buildingnumbera)$&nbsp;$(record : addresslevel8a)$</td>
    			<td></td>
    		</tr>
    		<tr>
    			<td>Addr 2</td>
    			<td>$(record : addresslevel5a)$,&nbsp;$(record : addresslevel2a)$&nbsp;$(record : addresslevel7a)$</td>
    			<td></td>
    		</tr>
    		<tr>
    			<td>Email</td>
    			<td>$(relatedRecord : accountid|email1|Accounts)$</td>
    			<td></td>
    		</tr>
    		<tr>
    			<td>Phone</td>
    			<td>$(relatedRecord : accountid|phone|Accounts)$</td>
    			<td></td>
    		</tr>
    	</tbody>
    </table>
    <br>&nbsp;<br>
    $(custom : ProductsTableCustomised)$
    </div>

**Comment by rafalpospiech** [comment]
Problem is in your html code inside text parser
![image](https://user-images.githubusercontent.com/36499752/54085198-6baad500-433b-11e9-97b2-0cd2c62be459.png)
Table cannot be a block - it must be a table
Position property isn't supported
!important isn't supported

![image](https://user-images.githubusercontent.com/36499752/54085269-a103f280-433c-11e9-8bfe-11a3dbde3b80.png)
cell width 100%?
