### ISSUE TITLE
Error when saving record

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#9838]
I get this error message when I try to save a record... I do I fix this issue?

![error message](https://user-images.githubusercontent.com/45261773/54066303-b7eefb80-41fb-11e9-945d-faff2f4f2ab7.jpg)

**Comment by hobejeans** [comment]
How do I fix this issue?

**Comment by vovpff** [comment]
You inveroinmet

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/54068317-ded51e00-424b-11e9-85ff-a91567d58479.jpg)

**Comment by mlorencik** [comment]
Custom inventory modules have this problm after upgrade to 5.0, you must change name of field to crmid in u_yf_workorder_inventory

**Comment by manwenick** [comment]
> 
> 
> Custom inventory modules have this problm after upgrade to 5.0, you must change name of field to crmid in u_yf_workorder_inventory

Hi @mlorencik @mariuszkrzaczkowski !
I have the same problem after upgrade to 5.x
I found also the work around and changed by hand the rows with name "id" in DB to "crmid" 
Is there any information about this change in db name structure? I didn't found any release notes about it. 

Kind regards
