### ISSUE TITLE
[Question] How to make custom table for PDF

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#9840]
### Description

I'm looking for any examples how to achieve custom product table for advanced modules what contains more info about products (fields from the product record) what not displayed at usual detail view of advanced module. 

Something like this:

| Item no     | Item name	| Qty  | Value 1  |  Value 2  | ...  |Value n	|
| ----------------	|	--------------	| ----------------	|	--------------	| ----------------	|	--------------	| ----------------	|
| 1			|  Prod 1 |
| 2  | Prod 2 |
| 3| Prod 3| 

Values 1-n will be hooked from product record

**Comment by rafalpospiech** [comment]
You need to add custom text parser - example text parses are in `app/TextParser/...`

**Comment by vovpff** [comment]
@rafalpospiech this is not enougth for me...

**Comment by mariuszkrzaczkowski** [comment]
we plan to write table generation using variables but we do not know where the version will be added

**Comment by vovpff** [comment]
@mariuszkrzaczkowski iny suggestions then it happens?

**Comment by waran70** [comment]
Little offtopic  - how to make PDF generator draw a border around cells and tables? In template is OK but after generating it borders colors are invisible

**Comment by rafalpospiech** [comment]
@waran70 `<td style="border:1px solid black;">...</td>`

**Comment by mariuszkrzaczkowski** [comment]
@vovpff Especially for you for all your contributions to YetiForce. I hope it's enough.

```
$(inventory : type=table columns=name,qty,price href=yes)$
$(inventory : type=table columns=seq,name,qty,unit,price,total,net href=no)$
```

https://github.com/YetiForceCompany/YetiForceCRM/commit/4e8c904f804c1c249d7ad90c32d806b3d8205fd5
![image](https://user-images.githubusercontent.com/10198654/54181809-0ae8dd00-44a0-11e9-8387-8b41f367b7c1.png)

**Comment by vovpff** [comment]
Looks cool. Many many thanks. What about other values from product record?  mean to call values from `vtiger_products` table? For example batch number? I

**Comment by mariuszkrzaczkowski** [comment]
in the future we will expand it, it is just the beginning

**Comment by waran70** [comment]
> td style="border:1px solid black;">

Hi Rafal, what about <td style="border-color:#444444">Row details sample</td>
The code generated while designing template should determine color of borders, background etc, but output shows nothing but text

**Comment by rafalpospiech** [comment]
@waran70 you must add `bodrer-width` property too, because by default it is 0
YetiForcePDF does not support legacy `<table border="" cellspacing="">` properties - only css

**Comment by waran70** [comment]
It should not be considered by CKEditor gents? Maybe little upgrade here?

**Comment by rafalpospiech** [comment]
Yes, the ckeditor will be replaced, but I think it may take some time, as we are currently in the process of completely replacing the front-end

**Comment by ippeas1** [comment]
> $(inventory : type=table columns=name,qty,price href=yes)$

You said the code for quote. it works very well.

Could you tell me the same for PaymentIn and PaymentOut? i want to create custom table of any field.
Thank you !

**Comment by Ilamparithi-Tamizhanangu** [comment]
> @vovpff Especially for you for all your contributions to YetiForce. I hope it's enough.
> 
> ```
> $(inventory : type=table columns=name,qty,price href=yes)$
> $(inventory : type=table columns=seq,name,qty,unit,price,total,net href=no)$
> ```
> 
> [4e8c904](https://github.com/YetiForceCompany/YetiForceCRM/commit/4e8c904f804c1c249d7ad90c32d806b3d8205fd5) ![image](https://user-images.githubusercontent.com/10198654/54181809-0ae8dd00-44a0-11e9-8387-8b41f367b7c1.png)

hi,

Thanks for the details.

$(inventory : type=table columns=name,qty,price href=yes)$
$(inventory : type=table columns=seq,name,qty,unit,price,total,net href=no)$

It will create the table in the quotation with predefined column names. How to adjust the column width for each column and give different names for the row headers. 

Also i wish to get the product description alone. We dont want to get the item name. How to get only comment in the products table. (It works in the dynamic inventory columns. But we are unable to change the row headers.

Please post the keywords for selecting the different columns. 

Thanks in advance.

**Comment by mariuszkrzaczkowski** [comment]
@RajasekaranJeni  create a new discussion thread
