### ISSUE TITLE
[PL][Pytanie] Przypisywanie Ticketów do Kontaktu

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#9848]
Witam,

Czy można utworzyć powiązanie pomiędzy zgłoszeniami a kontaktami? Tak by Ticket przypisywał się do kontaktu o tym mailu i przechowywał się tam? W "Powiązaniach" widzę że jest tylko powiązanie z mailami wewnętrznymi. Pewnie trzeba robić to przez mapowanie, ale czy to w ogóle możliwe?

Pytam ponieważ w opcji Skanery wybrałem dodanie powiązania z kontaktem.
-> Kontakt jest utworzony
--->Przychodzi Mail z tego maila
------>Tworzy Ticket
----------> tworzenie powiązania z Kontaktem jest w historii zmian ticketu
ale nie ma nic w kontakcie :(

Próbowałem równiez przez Widget ale Moduł powiązany chyba nie zaciąga dnaych przez to że nie ma wcześniej zdefiniowanego powiązania czyli wracam do mapowania..

**Comment by bpabiszczak** [comment]
W systemie domyślnie jest powiązanie modułu kontaktów ze zgłoszeniami co widac na GitDeveloper
![image](https://user-images.githubusercontent.com/10197525/54124877-d58eb180-4403-11e9-98fd-e7fc668cafc0.png)

więc nie bardzo rozumiem pytanie.

**Comment by mrzewnicki** [comment]
Oczywiście to logiczne że jest ponieważ Skaner daje opcje stworzenia powiązania z kontaktem. Podejrzewam że rekord Kontaktu musi być stworzony ręcznie ponieważ w mailu nie zawsze są informacje wymagane do stworzenia kontaktu. Pytanie czy jeśli ten kontakt będzie to czy system będzie sam wiązał Tickety z Kontaktem czy za każdym razem muszę robić to ręcznie, po przez "Wybierz rekord" widzialnym na screenie. Przez tą opcje udało mi się dodać ale ręcznie.

**Comment by bpabiszczak** [comment]
a więc, akacja widoczna na skanerze "Tworzenie powiązania z kontaktem" nie ma nic wspólnego [a przynajmniej tak myślę] z tym, czy kontakt zostanie automatycznie powiązany ze zgłoszeniem. Za to odpowiada akcja skanera, która mechanizm powiązania z Kontaktem i Umową SLA ma zaszytą "na sztywno". Dla pewności polecam zerknąć w skrypt.

**Comment by websafe** [comment]
Mam utworzony Account z adresem e-mail a@b.com, do tego konta (Account) mam dodany Contact z takim samym adresem e-mail (a@b.com). Dedykowaną skrzynkę e-mail skanuje mailscanner-em, który ma dodane już WSZYSTKIE dostępne akcje, włącznie z `Create HelpDesk`, `Relate with Accounts`, `Relate with Contacts`, `Relate with HelpDesk` i tak dalej, a mimo to w liście ticketów dany ticket pokazuje się jako nieprzypisany do żadnego konta (`The ticket is not related to any Account. Please create a relation.`). Co robię źle?

**Comment by bpabiszczak** [comment]
Proszę ustawić konfigurację na GitDeveloper i zobaczyć czy działa czy nie, jeżeli nie działa nagrać filmik który pokazuje pełną konfiguracje.

**Comment by websafe** [comment]
@bpabiszczak OK, spróbuję, jeśli dobrze rozumiem mam spróbować sklonowac mój config na gitdevelopera, jest tylko problem, bo na gitdeveloperze jest już jakiś problem z modułem mailscanner:
https://gitdeveloper.yetiforce.com/index.php?module=ModuleManager&parent=Settings&view=List&block=2&fieldid=8
![image](https://user-images.githubusercontent.com/412013/61108627-187c9680-a483-11e9-8bf3-e6d6d48dcc70.png)

**Comment by bpabiszczak** [comment]
ona pokazuje zmiany programistów z ostatnich kilku godzin, a Ci uwielbiają psuć... sprawdź na gitstable.

**Comment by LOCOSP** [comment]
Dzień dobry,
Na gitstable jest dokładnie to samo:
- tworzę kontrahenta
![image](https://user-images.githubusercontent.com/4149309/61138316-906cb000-a4c7-11e9-8b3e-797b98e73fe6.png)

- dodałem wszystkie filtry i folder 'RECEIVED' w mail tools
![image](https://user-images.githubusercontent.com/4149309/61138302-8945a200-a4c7-11e9-98fd-c4888a6b58a2.png)

-mail dotarły
![image](https://user-images.githubusercontent.com/4149309/61138376-b5612300-a4c7-11e9-9aa1-55c5b3e137de.png)

lecz nadal nie są przypisywane do kontrahenta 
![image](https://user-images.githubusercontent.com/4149309/61138454-d32e8800-a4c7-11e9-9951-a3c025cf0de9.png)

mało tego, podejrzałem już przypisane zgłoszenia i większość z nich była dostawcami, tak że dodałem siebie (mojego maila z którego wysyłam zgłoszenie) do dostawców 
![image](https://user-images.githubusercontent.com/4149309/61138546-02dd9000-a4c8-11e9-88e8-d227642c69c6.png)

lecz efekt jest ten sam, ticket nie jest z automatu przypisany do pasującego adresu email(kontrahenta/dostawcy).

**Comment by websafe** [comment]
@LOCOSP Identyczne zachowanie na naszych lokalnych instalacjach. Maile wpadają bez problemu na listę ticketów, ale nie są przypisywane automatycznie do konta (`Account`).
cc: @bpabiszczak

**Comment by bpabiszczak** [comment]
Najprawdopodobniej nie zaznaczyliście w skanerze po jakich polach mailowych ma działać skaner.... 
![image](https://user-images.githubusercontent.com/10197525/61152310-5eb81100-a4e8-11e9-9db5-a41a9c2fa9e6.png)

**Comment by websafe** [comment]
@bpabiszczak Bingo! Dziękuję, działa!

`System settings` -> `Mail tools` -> `Mail - Scanner` -> `General configuration` -> `Search email configuration`

cc: @LOCOSP
