### ISSUE TITLE
Installation Problem with 5.0 Version PHP Fatal Error

### ISSUE THREAD

**Issue by untecnologo** [YetiForceCompany/YetiForceCRM#9852]
# 🐞 Installation Problem with 5.0 Version PHP Fatal Error

### ⁉️ Describe the bug

I have a problem when I am trying to install this version in my new VPS Go Daddy. Previous I was working with a re-seller VPS plan of Hostgator and everything worked very nice, this is the reason why I did and update of my services to stablish this platform in a big organization. When I try to open the install file it gives me a HTTP Error 500. I can't understand what is going on.. I have installed the ea-PHP71 (https://crm.unitech-ikk.com)

Thanks for your support.

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

This is my error log:

[11-Mar-2019 11:03:24 UTC] PHP Fatal error:  Uncaught Error: Class 'Locale' not found in /home/digitalunitech/public_html/crm.unitech-ikk.com/app/Language.php:717
Stack trace:
#0 /home/digitalunitech/public_html/crm.unitech-ikk.com/app/Controller/Base.php(23): App\Language::initLocale()
#1 /home/digitalunitech/public_html/crm.unitech-ikk.com/install/views/Index.php(66): App\Controller\Base->__construct()
#2 /home/digitalunitech/public_html/crm.unitech-ikk.com/install/Install.php(34): Install_Index_View->__construct()
#3 {main}
  thrown in /home/digitalunitech/public_html/crm.unitech-ikk.com/app/Language.php on line 717
[11-Mar-2019 12:02:38 UTC] PHP Fatal error:  Uncaught Error: Class 'Locale' not found in /home/digitalunitech/public_html/crm.unitech-ikk.com/app/Language.php:717
Stack trace:
#0 /home/digitalunitech/public_html/crm.unitech-ikk.com/app/Controller/Base.php(23): App\Language::initLocale()
#1 /home/digitalunitech/public_html/crm.unitech-ikk.com/install/views/Index.php(66): App\Controller\Base->__construct()
#2 /home/digitalunitech/public_html/crm.unitech-ikk.com/install/Install.php(34): Install_Index_View->__construct()
#3 {main}
  thrown in /home/digitalunitech/public_html/crm.unitech-ikk.com/app/Language.php on line 717

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.0
| Web server (name and version)|	Apache/2.4.38	|
| PHP  |					7.1 			|
| Browser (name and version)  | 	Chrome	|
| Operating System (name and version)  | 	CentOs (Capnel)	|
| Database (name and version) | Versión del servidor: 5.6.43 - MySQL Community Server (GPL)	|

**Comment by untecnologo** [comment]
After to read a lot of forums I found that my error was (php71-php-intl). It should be enable. 

Thanks for your support.

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/9821#issuecomment-470866641
