### ISSUE TITLE
¿Does YetiForceCRM has a support for creating multiple, personalized pipelines/ sales funnel ?

### ISSUE THREAD

**Issue by P-Flores** [YetiForceCompany/YetiForceCRM#9858]
Hi, I've been checking out YetiForceCRM's demo (https://gitdeveloper.yetiforce.com/index.php), but I couldn't find a way to create pipelines. Our company is looking for a CRM which allows to create at least 3 personalized pipelines or sales funnels. I'd like to know if this is possible with YetiForceCRM, before installing it in our server.

Thank you for your time.

**Comment by bpabiszczak** [comment]
like this? 
![image](https://user-images.githubusercontent.com/10197525/54150159-17394f80-4438-11e9-853e-df1da7d4d228.png)

**Comment by P-Flores** [comment]
Yes, that's what I'm looking for. I'd like to know how can I edit it and create two more funnels, something like the image below. Thank you.
![image](https://user-images.githubusercontent.com/16752260/54217125-0aa90b80-44b9-11e9-9409-30d583393aa3.png)

**Comment by bpabiszczak** [comment]
![funnel](https://user-images.githubusercontent.com/10197525/54232184-6354c480-450a-11e9-838c-d66ab0c68a44.gif)

**Comment by bpabiszczak** [comment]
![funnel2](https://user-images.githubusercontent.com/10197525/54232190-68197880-450a-11e9-9871-ff31ec6ac7c5.gif)
