### ISSUE TITLE
Yetiforce crm version 5 Contacts are not visible to other user after gave permission changes 

### ISSUE THREAD

**Issue by raguvaran7232** [YetiForceCompany/YetiForceCRM#9860]
In version 5 I gave special permission to all user . Contact module are in public access.
Case1 : I create one contact and shared with all user But other user cant to access htat contact

**Comment by vovpff** [comment]
Cron enabled?

**Comment by raguvaran7232** [comment]
After CRON enable the issue is resolved. Thanks for your help.
