### ISSUE TITLE
[bug] IGDN - Error for deleted products ? 

### ISSUE THREAD

**Issue by liviubbo** [YetiForceCompany/YetiForceCRM#9861]
Hy all ! 

   I got this error for some IGDN entries : 

![screencapture-birou-maiortrans-de-index-php-2019-03-12-09_36_21](https://user-images.githubusercontent.com/42461923/54185981-97000200-44aa-11e9-90fb-87b18005ab09.png)

Yetiforce 5.0 - error was not visible before update

**Comment by vovpff** [comment]
I'm not sure but I think I has this error also in the past. If you check `u_yf_igdn_inventory` table you can find NULL values for EAN. In this case replace all NULL to emptiness

**Comment by liviubbo** [comment]
@vovpff - Thank you ! 👍

**Comment by arek1-618** [comment]
Please provide more details. For example, how to trigger this error or attach logs from CRM.

**Comment by vovpff** [comment]
@arek1-618 as I understand in older versions possible to store NULL values in `_inventory` tables. This happens if you has some advanced module records and add some column to inventory table. In this case all old records became filled with NULL. From 5.0.0. there are error appears for this values.

**Comment by liviubbo** [comment]
@arek1-618 - I will search for logs and post.

**Comment by liviubbo** [comment]
File log is too big. It`s 1GB almost and will not open by Notepad++. :(

**Comment by konadrian** [comment]
This error has been corrected, check the latest version
