### ISSUE TITLE
language label missed

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#9885]
The months of the year have full and short versions (maybe in js only)

"JS_JAN": "Jan",
"JS_JANUARY": "January",

For May it is impossible to make this distinction because there is only "JS_MAY"

File: languages/en_US/_Base.json: 1528

It would be advisable to have a full and short version for each month name

**Comment by vovpff** [comment]
How you can shorten May?

**Comment by davide-alghi** [comment]
It cannot. The problem is that it's impossible define full and short name with just one variable: JS_MAY.

I think the solution is to have different month variable names for full and short, e.g.

"JS_MAY_FULL": "MAY"
"JS_MAY_SHORT": "MAY"

and in italian (and maybe in many other languages)

"JS_MAY_FULL": "MAGGIO"
"JS_MAY_SHORT": "MAG"

Actually in calendar, in italian, it is showed "MAGGIO" everywhere

I know my suggestion require a code modification too
