### ISSUE TITLE
Po instalacji 5.0 na home.pl brakuje pliku config.inc.php 

### ISSUE THREAD

**Issue by fundacjaamdg** [YetiForceCompany/YetiForceCRM#9898]

**Comment by fundacjaamdg** [comment]
Instalacja przebiegła poprawnie. Nie było żadnych komunikatów. Po skonfigurowaniu serwera z pomocą z home.pl wszystko działa. w katalogu config nie ma plików config.inc.php i config.php

**Comment by mariuszkrzaczkowski** [comment]
Od wersji 5.0.0 nie ma już pliku config.inc.php jest mowy Main.php
