### ISSUE TITLE
Fix Color Button Add Campaings

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#99]
Must be white button
And Module
Calculations
Quotes
Sales Order
Purchase Order
Invoice
Costs
Corporate emails
Documents

![add campaigns](https://cloud.githubusercontent.com/assets/1402355/5756388/d9c7487c-9cd0-11e4-8ec1-e046de5860f1.JPG)

**Comment by KatarzynaUlichnowska** [comment]
Hello,
could you please explain us why you would like it in white? Do you mean the background of the button "Add record" or something else? Or maybe you would like the possibility to color the buttons, like in the menu bar?

**Comment by waw555** [comment]
Yes, I would like to have the same form everywhere, but not often.

**Comment by KatarzynaUlichnowska** [comment]
Black letters and white background for the button "Add record" for every module, right? 
What about the second thing you marked on the screenshot above?

**Comment by bpabiszczak** [comment]
We have added colors in the new files. Must suffice :]
https://github.com/YetiForceCompany/YetiForceCRM/commit/f870ec39b89c8853da462cb380c1742a56b0adfe
