### ISSUE TITLE
Unable to select data

### ISSUE THREAD

**Issue by KrishnaPB** [YetiForceCompany/YetiForceCRM#9907]
Hi, I have selected name in the attached image. But user ID is not displaying. User ID should take from the Employee module automatically while selecting. Please guide on achieving this.
![name](https://user-images.githubusercontent.com/11535185/54303404-ea786a00-45e8-11e9-9912-929470c60315.png)

**Comment by KrishnaPB** [comment]
I have used yatiforce version 5.0.0

**Comment by vovpff** [comment]
@KrishnaPB to achieve this you need to change this file `CRM/user_privileges/moduleHierarchy.php`

**Comment by vovpff** [comment]
@KrishnaPB as example try to understand how this file works with Quotes when you select related Opportunity

**Comment by KrishnaPB** [comment]
Thank you @vovpff . I have created a module called AccessList. From employee module, if I fetch the data to Acceelist module for the filed User Name the User ID should pick up automatically. Could you provide me sample code/steps to do this.

**Comment by KrishnaPB** [comment]
By mistakenly closed.

**Comment by vovpff** [comment]
@KrishnaPB as I wrote you need to change file `CRM/user_privileges/moduleHierarchy.php` or try to use this type of field
![image](https://user-images.githubusercontent.com/8545791/54355429-1ee03a80-466a-11e9-986d-9fde3b34cc2b.png)

**Comment by KrishnaPB** [comment]
I have added below codes as you said.

'RMHAccess' => ['level' => 1], 

//Map links between modules

'RMHAccess' => [
			'accountid' => ['Accounts' => ['user_id' => ['user_id']]],
		],

// Base => Parent link
'RMHAccess' => ['Accounts'],

But I am not getting automatically. Please help in this code.

**Comment by mlorencik** [comment]
check name of fields, in standard Accounts have accountid

**Comment by konadrian** [comment]
I closed the issue because we've waited too long for an answer
