### ISSUE TITLE
[bug] "Share with users:" field generates error if a group is selected.

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#9908]
# 🐞 bug report

### ⁉️ Describe the bug

I upgraded from 4.4.0 to 5.0, updated the Language Management, made sure that the Server Configuration was ok, and afterwards upgraded to 5.1.

Opening an existing Lead gives the error **Call to a member function get() on null**. Creating a new Lead gives the same error. Issue is in the field **Share with users:**. If I select a user or keep it blank, the Lead is saved and can be opened for viewing.

If I select a group to share with, the error occurs. I tried to reproduce this in the developer version git, and got the same error.

### 🔥 How to trigger the error

1. Go to System Settings\Permissions\Groups.
2. Edit an existing group or create a new one, and select Leads, Accounts, and Contacts in the Modules field, and select some users in the Group Members field. Save settings.
3. Go back to the User Panel Companies and Contacts\Leads and create a new Lead. In the **Share with users** field, make sure you select the previously edited group and save the settings.  
4. Error **Call to a member function get() on null** occurs.

### 👎 Actual Behavior

Error message is given.

### 👍 Expected Behavior

New Lead to save the details, or existing Leads to open.

### 🌍  Your Environment & Logs

Not applicable. Is reproducible on the developer version on Git. 

### ❓ Additional context
This applies to Accounts, Leads, and Contacts. And maybe each module that has the **Share with users field**.

Existing records are not opening at all due to having a value of a group in that field already prior to the upgrade. Furthermore, this has also influence on the **Updates** section. Hangs on loading and after refreshing, the same error is given as mentioned above. I also experience a huge delay in loading data from Activities from Leads, Accounts and Contacts. I have a feeling that the issue above has to do with it.

**Looks like I'm rolling back again to version 4.4.0.**

**Comment by alagmouch** [comment]
I was testing a little with emptying the **Share with users:** field. I was able to mass edit the Accounts, Leads, and Contacts section and empty those fields. I was not able to do this for the Activities (no Mass Edit available. Seems to be having a low priority if I'm not mistaken). The Updates section is not opening at all for any of the records, as described above also.

**Comment by alagmouch** [comment]
The Updates section everywhere in the CRM is causing major issues at my side. I have in all the Activities the field **Share with users:** filled. I cleared the other modules already. Do you have an sql syntax I can used to clear it in the database for the Activities and also for the Updates.

At least to be able to see if the hanging of the application stops.

**Comment by alagmouch** [comment]
Ok. Sorry for all the messages, but this is how far I came and the hanging stopped (worked around actually) and the speed in the Activities tab is back again. **But the issue is not solved of course.**

1. As I mentioned above I cleared the **Share with users:** field from all the Accounts, Contacts, and Leads records.
2. I then deleted all the records in the table **u_yf_crmentity_showners** to empty the shared owners field in the Activities.
3. I turned of the Tracking of Changes for Accounts, Leads, Contacts, and Calendar (Activities).

With the current data, after the adjustments, the hanging stopped, and the speed is back. Is a workaround for now, of course only as long as the delete from **u_yf_crmentity_showners** is legit and the **Share with users:** is used for sharing with users only (no groups!).

Can you tell me if this is a workable approach for now? Or should I go back to 4.4.0 and wait for the next milestone? Thanks in advance for the prompt response.

**Comment by alagmouch** [comment]
Hi @mariuszkrzaczkowski sorry to write you directly. Do you think it is possible to fix the issue of the **Share with users:** field and have a v2 available soon of 5.1? (That is, if I'm not doing something wrong myself, of course.)

It would help a lot. Currently, upgrading goes well, but it is impossible to use the system, with the current records and the delays that are caused while loading the tabs.

Otherwise I will have to update all the existing records and assign users instead of the groups. But the **Updates** sections will still hang every area in the CRM Where **Updates** are shown, most probably.

Thanks in advance for your efforts, and please let me know if you need more info.

**Comment by bpabiszczak** [comment]
On Monday, we will publish a patch for version 5.1.

**Comment by bpabiszczak** [comment]
You can test this: https://github.com/YetiForceCompany/UpdatePackages/tree/developer/YetiForce%20CRM%205.x.x/5.1.0_ServicePack/zip

**Comment by alagmouch** [comment]
Thanks a lot for the prompt response. Much appreciated. I will test the service pack today and report.

**Comment by alagmouch** [comment]
I used the ServicePack. Kindly find below a report of the steps I took and the results:
1. Cloned the production environment and database for testing, which is on version 4.4.0 (including the 6 patches (AttachmentsFix, ImageFix, SecurityPHPMailerAndPhpSpreadsheetFix, SecuritySmartyFix, WidgetsFix, CalendarDateFormatFix).
2. Paused cron and upgraded to 5.0.0 with **4.4.0_to_5.0.0_v3.zip**.
3. Downloaded the languages, selected Polish as default and then back to English, logged out and in again, and tried to open a Lead. Still works.
4. Upgraded to 5.1.0 with **5.0.0_to_5.1.0_v1.zip**.
5. Updated the languages, cleared the browser cache, logged out and in again.
6. Tried opening an existing Lead. The error message was given (as expected).
7. Applied the ServicePack **5.1.0_ServicePack_v1.zip**.
8. Tried opening an existing Lead/Account, which works now. Also tried creating a new Lead/Account while inputting a group in the **Share with users:** field. This also works. Did the same for an Activity. Also works.
9. From the Lead/Account summary, I navigated to the Contact of that Lead/Account, and while in the Contact, I navigated to the Activities Tab. **Takes a while to load**.
10. Also, while in the Summary of the Contact, I clicked on **History** in Calendar Widget, takes approx. 10 seconds to load. While everything else in the CRM loads in a fraction of a second (except for the rights in Profiles of course).
11. I shall try to replicate the delay in the developer version on git, and accordingly create an issue for this delay. Unless it is related to issue [9910](https://github.com/YetiForceCompany/YetiForceCRM/issues/9910), which got solved I believe.

**Comment by alagmouch** [comment]
**Update to previous comment, point 11:**

It seemed that I had a relation to the **Leads** module in the **Contacts** Module in **[Modules - Relations]**. The relation to Leads was showing as a Tab in the Contacts records. Clicking on this tab was hanging completely (probably also logic) and caused especially the Activities tab to delay in showing. I don't know anymore what I did to have the Leads module show as a relation in the Contacts module.

Anyway, once I set the **Leads** tab in the Contacts on hidden, the speed for the Activities section was back again while working in Contacts.

I then turned on the following setting in **config/Developer.php**:
`/** Adding/Deleting relations between modules. */`
`public static $CHANGE_RELATIONS = true;`

And was able to delete the relation to Leads in the Contacts Module in **[Modules - Relations]**. And afterwards turned the setting off again. 

I'm not an expert in databases, but probably this had to do with there being already a 1:M relationship between the Leads Module and the Contacts Module, and that I probably did something in the past that created another, which resulted in probably a relationship the other way around from Contacts to Leads. (If I'm not mistaken.)

As conclusion, it works very fine at the moment. The issue with the **Share with users:** is solved, and speed is good again.

Thanks a lot for the efforts and the quick response. Will be waiting for the patch on Monday.

**Comment by alagmouch** [comment]
I just encountered one remaining issue in regards to the **Updates** tab. For the existing Activities, once I open one record for viewing and click on the tab of **Updates**, the screen hangs and keeps on loading. Same as how it was doing for the **Updates** tab in the Lead/Account/Contact records previously when the **Share with users:** field was not fixed yet.

The hanging is not happening for new Activities that I create, even if it is for the same Contact that has an existing activity where the **Updates** tab hangs.

So the hanging of the **Updates** Tab is occurring only with existing activities in detail view, while newly created ones do not have this issue at all.

I have attached the [system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/2973284/system.log) for your reference.

**Comment by alagmouch** [comment]
Hi @bpabiszczak do you know if any patch is released in coming days? Or else, can I use the ServicePack which is there to update? It worked well, except for the delay in loading the Updates Tab (as explained in my message above also). Your prompt response is much appreciated. Thanks.

**Comment by bpabiszczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.1.0

**Comment by alagmouch** [comment]
Thanks. Will test it out.
