### ISSUE TITLE
Invoice creation ERR_ILLEGAL_FIELD_VALUE when creation Invoice

### ISSUE THREAD

**Issue by raguvaran7232** [YetiForceCompany/YetiForceCRM#9912]
When i creating invoice i got  ERR_ILLEGAL_FIELD_VALUE  error

**Comment by adudekyeti** [comment]
Hi,
Could you give us more informations how to reproduce this bug?
Please also attach log files, it will be very useful.

**Comment by raguvaran7232** [comment]
`ERR_ILLEGAL_FIELD_VALUE||name||
App\Exceptions\Security: ERR_ILLEGAL_FIELD_VALUE||name|| in /var/www/html/livecrm/modules/Vtiger/inventoryfields/Name.php:108
Stack trace:
#0 /var/www/html/livecrm/modules/Vtiger/inventoryfields/Basic.php(473): Vtiger_Name_InventoryField->validate(NULL, 'name', true)
#1 /var/www/html/livecrm/modules/Vtiger/models/Record.php(1205): Vtiger_Basic_InventoryField->setValueToRecord(Object(FInvoice_Record_Model), Array, true)
#2 /var/www/html/livecrm/modules/Vtiger/models/Record.php(1230): Vtiger_Record_Model->initInventoryData(Array)
#3 /var/www/html/livecrm/modules/Vtiger/actions/Save.php(123): Vtiger_Record_Model->initInventoryDataFromRequest(Object(App\Request))
#4 /var/www/html/livecrm/modules/Vtiger/actions/Save.php(87): Vtiger_Save_Action->getRecordModelFromRequest(Object(App\Request))
#5 /var/www/html/livecrm/modules/Vtiger/actions/Save.php(61): Vtiger_Save_Action->saveRecord(Object(App\Request))
#6 /var/www/html/livecrm/include/main/WebUI.php(183): Vtiger_Save_Action->process(Object(App\Request))
#7 /var/www/html/livecrm/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#8 {main}
2019-03-15 12:06:03.3039 [info][application] - 
$_GET = []
$_POST = [
    '__vtrftk' => 'sid:611e9fcb7c336f96cf79193235c189eaab955128,1552631738'
    'picklistDependency' => '[]'
    'mappingRelatedField' => '[]'
    'module' => 'FInvoice'
    'action' => 'Save'
    'defaultOtherEventDuration' => '[{\"activitytype\":\"Call\",\"duration\":\"60\"},{\"activitytype\":\"Meeting\",\"duration\":\"60\"},{\"activitytype\":\"Task\",\"duration\":\"60\"}]'
    'subject' => 'wwwwww'
    'paymentdate' => ''
    'saledate' => ''
    'issue_time' => ''
    'finvoice_formpayment' => 'PLL_TRANSFER'
    'popupReferenceModule' => 'Services'
    'accountid' => ''
    'accountid_display' => ''
    'finvoice_paymentstatus' => 'PLL_AWAITING_PAYMENT'
    'finvoice_status' => ''
    'private' => '0'
    'finvoice_type' => 'PLL_DOMESTIC_INVOICE'
    'pscategory' => ''
    'pscategory_display' => ''
    'assigned_user_id' => '14'
    'shownerid' => ''
    'addresslevel8a' => ''
    'localnumbera' => ''
    'buildingnumbera' => ''
    'poboxa' => ''
    'addresslevel7a' => ''
    'addresslevel6a' => ''
    'addresslevel5a' => ''
    'addresslevel4a' => ''
    'addresslevel3a' => ''
    'addresslevel2a' => ''
    'addresslevel1a' => ''
    'inventory' => [
        1 => [
            'currencyparam' => '{\"1\":{\"date\":\"2019-03-14\",\"value\":1,\"conversion\":1}}'
            'currency' => '1'
            'discountmode' => '0'
            'taxmode' => '0'
        ]
        2 => [
            'currency' => '1'
            'currencyparam' => '{\"1\":{\"date\":\"2019-03-14\",\"value\":1,\"conversion\":1}}'
            'discountmode' => '0'
            'taxmode' => '0'
            'name' => '20282'
            'unit' => ''
            'subunit' => ''
            'qty' => '1'
            'price' => '0.00'
            'total' => '0.00'
            'discount' => '0.00'
            'discountparam' => ''
            'net' => '0.00'
            'tax' => '0.00'
            'taxparam' => '[]'
            'gross' => '0.00'
            'comment1' => ''
        ]
    ]
    'description' => ''
    'attention' => ''
]
$_FILES = []
$_COOKIE = [
    'YTSID' => 'c64df81868446d9e5fc35713d9535304'
]
$_SESSION = [
    'last_activity' => 1552631763.3052
    'UserAuthMethod' => 'PASSWORD'
    'authenticated_user_id' => 14
    'app_unique_key' => '12a4f559a55fdc5dc581ec7467d952e0cfb9fe9d'
    'user_name' => 'suriya@qq.com'
    'full_user_name' => 'R Suriya'
    'fingerprint' => 'b23793f8-29e0-4f35-b7d2-977f3ec1e59b'
    'DashBoard' => [
        'Home' => [
            'LastDashBoardId' => 1
        ]
    ]
    'SystemWarnings' => true
    'lvs' => [
        'Services' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 40
        ]
        'Products' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 24
        ]
        'FInvoice' => [
            'sortby' => ''
            'sorder' => ''
            'viewname' => 89
        ]
    ]
]
$stability = [
    'error_reporting' => 'E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_USER_ERROR | E_USER_WARNING | E_USER_NOTICE (22519)'
    'output_buffering' => '0'
    'max_execution_time' => '30'
    'default_socket_timeout' => '60'
    'memory_limit' => '128 MB'
    'log_errors' => 'Off'
    'post_max_size' => '8.00 MB'
    'upload_max_filesize' => '2.00 MB'
    'max_input_vars' => '1000'
    'session.gc_divisor' => '100'
    'date.timezone' => 'Invalid time zone:'
    'auto_detect_line_endings' => 'Off'
]
$security = [
    'HTTPS' => 'Off'
    'public_html' => 'Off'
    'display_errors' => 'On'
    'session.use_strict_mode' => 'Off'
    'expose_php' => 'On'
    'disable_functions' => ''
    'Header: server' => 'Apache/2.4.6 (CentOS) PHP/7.2.12'
]
$libraries = [
    'apcu' => 'LBL_NO'
    'imagick' => 'LBL_NO'
]
$database = [
    'character_set_server' => 'latin1'
    'character_set_database' => 'latin1'
]
$performance = [
    'opcache.enable_cli' => 'Off'
    'opcache.max_accelerated_files' => '4000'
    'opcache.interned_strings_buffer' => '8'
    'opcache.revalidate_freq' => '2'
    'opcache.save_comments' => '1'
    'opcache.file_update_protection' => '2'
    'realpath_cache_ttl' => '120'
    'mysqlnd.collect_statistics' => 'On'
]
`

**Comment by adudekyeti** [comment]
Could you tell me how to reproduce this bug?

**Comment by adudekyeti** [comment]
In version 5.1 working correctly.
