### ISSUE TITLE
Version 5.1 released!

### ISSUE THREAD

**Issue by paula-w** [YetiForceCompany/YetiForceCRM#9914]
We just released **version 5.1** and would like to thank everyone who contributed to this release. We’re extremely lucky to have such an amazing and helpful community Thank you once again for your time, effort, and willingness to help us create this project!

We’re still looking for new translators (and languages)! If you’d like to help translate YetiForce into one of the languages already available or add a new language, please check this issue https://github.com/YetiForceCompany/YetiForceCRM/issues/9104 for more info.

**LOG**
This version mostly focuses on fixing errors but there have been a few other changes as well. The entire changelog can be found on [our website](https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/yetiforce-5-1).

**LINKS**
- GitHub: https://github.com/YetiForceCompany/YetiForceCRM/releases/tag/5.1.0
- Sourceforge: https://sourceforge.net/projects/yetiforce/files/YetiForce%20CRM%205.x.x/5.1.0/

**UPDATE & REQUIREMENTS**
We would like to remind everyone that updates should first be executed on a test version, and only then on the production version (you should always have a backup copy of your environments).
- The list of current web server requirements necessary for version 5.1 to work properly can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements).
- A detailed description of the installation process can be found [here](https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/system-update).

**Comment by elvissaba** [comment]
My installation is not registered yet. I am waiting on registration code. Is there a problem with registration process?

**Comment by bpabiszczak** [comment]
Q: Is there a problem with registration process?
A: No

**Comment by elvissaba** [comment]
What have I done wrong? Registration status is pending for two days.

**Comment by bpabiszczak** [comment]
Please send me you crm key b.pabiszczak@yetiforce.com
![image](https://user-images.githubusercontent.com/10197525/54559921-70b5f700-49c1-11e9-8de0-3819ec32de5b.png)

**Comment by MyBlissIT** [comment]
Hi, I have the same issue of having a Registration that is still pending, it has been over a week. Mine is online version
