### ISSUE TITLE
[bug] Can't change default language

### ISSUE THREAD

**Issue by rtorrescodes** [YetiForceCompany/YetiForceCRM#9917]
# 🐞 bug report

Hello. I installed 5.0, then upgraded to 5.1.  When i try to change the default language i get a warning saying: Are you sure you want to change a default language?    With no confirmation, or even enter responding.  I can't delete existing languages. Same problem, a warning with: Are you sure you want to delete this language?. 

### 🔥 How to trigger the error

Installed Spanish language, then changed it to default language. Now i can't get back to English to default language or even delete spanish to try again. 

### 👎 Actual Behavior

Im stuck on changing default language or even delete the installed ones.

### 👍 Expected Behavior

Language must be changed, desinstalled, etc.

### 📷 Screenshot of configuration

https://snag.gy/Pzqmf8.jpg

**Comment by rtorrescodes** [comment]
I can't even install PDF support. It says YetiForcePDF-developer.zip i downloaded here from the github, does not contains the spanish language (because i still stuck on that default language, thats why i tried to change to English, to install PDF support (its not installed on default YetiCRM installation). Before 5.0, mPDF library was ready to install on just one click. Now its only roundcube only.  Thanks, i hope i can help.

**Comment by rtorrescodes** [comment]
I found, in database, none of those languages was marked as default.  Im adding 1 to default to English. This must be happened since 5.1 upgrade maybe.   https://snag.gy/D9cRHn.jpg

But i still cant delete Spanish https://snag.gy/b6t15L.jpg   to try to download mPDF Lib that keeps with the same error:     https://snag.gy/tZn1K7.jpg

**Comment by alagmouch** [comment]
Which browser are you using? I had the same while using Chrome. And when I tested it in Mozilla Firefox, the buttons were showing.

**Comment by rtorrescodes** [comment]
Thank you so much, i used now Firefox for that option and now it works. Im closing issue and i'll open one more for the mPDF that isn't working now.  Thanks @alagmouch  

https://snag.gy/TyiZuV.jpg

**Comment by alagmouch** [comment]
You are most welcome @rtorrescodes.

**Comment by rskrzypczak** [comment]
Most likely, all you need to do is clear cache in your Chrome browser.

**Comment by alagmouch** [comment]
You are completely right @rskrzypczak.
