### ISSUE TITLE
[PL][Pytanie] Skryptowanie w YetiForce

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#9918]
Witam,

Co chce zrobić:
Chciałbym utworzyć sobie pole w Module Zgłoszeń, do którego zaciągnę sobie część tematu, pożądana przeze mnie część to są tylko liczby i zawsze mają długość 9-10 cyfr. Później ten ciąg chce sobie wstrzyknąć w nie zmieniający się link i w ten sposób automatycznie tworzyć HyperLink dla każdego Ticketu do inne źródła danych. 

Moje pytanie brzmi: Czy mogę sobie taki skrypt napisać np w mapowaniu pola z tematu ( zmapować sobie moge nawet temat ze zgłoszenia wewnętrznego bo jest identyczne ) w php, W Mapowaniu ta funkcja nazywa się "wyrażeniem". Czy muszę robić to na sztywno tworząc pliki PHP na swoim serwerze i podpiąć je pod akcje scannera albo tworzenia Ticketu?

W "Wyzwalaczach" znalazłem jeszcze opcje "Uruchom funkcje niestandardową" ale nic tam nie ma i nie wiem jak ją stworzyć, może tym by się dało?

Yetiforce 5.0.0 complete na Ubuntu 16.04.  Dziękuje za wszelkie rady/spostrzeżenia.

**Comment by bpabiszczak** [comment]
ale komplikujesz życie ;)

Skoro coś z tematu kopiujesz w inne pole to albo ta informacja nie powinna być w temacie albo w innym polu, przechowywanie dwa razy tej samej informacji w różnych miejscach jest niepraktyczne i niezgodne z wieloma standardami.

Skrypt może wszystko, a więc nie musisz być w żaden sposób ograniczony. A jeżeli zgłoszenie jest generowane automatycznie ze skanera, to również możesz wszystko dopasowując ten skrypt do swoich potrzeb.

Mapowania do tego bym nie używał bo zostało do czegoś innego zaprojektowane, do tego co potrzebujesz jest workflow, handlery oraz parsery na warstwie JS.

**Comment by mrzewnicki** [comment]
OK, dzięki wielkie!!
