### ISSUE TITLE
[Question] Mails Stored      

### ISSUE THREAD

**Issue by quasi754** [YetiForceCompany/YetiForceCRM#9927]
I'm new in Yetiforce so, Hello everyone! 

I did install YF 5.0.0 Complete on ubuntu and everythig work very well. GJ YT Team. 

I would like to ask where mails which I download using imap are stored in DB?
and where Tickets are stored, because in  "vtiger_ticketcf" i found only id numbers. I view few tables with vtiget_ticket......  and roundcube_...... but found nothing.

If you cannot share these infomations i will understand

**Comment by quasi754** [comment]
i found i guess 😄  good challenge. Thank you anyway

**Comment by guide5232** [comment]
@quasi754 
 Hi
Please tell me where we can find mails stored
