### ISSUE TITLE
Multiple Tax application

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9930]
Hi, I need to apply atleast 4 Tax. Now presently I can apply one from the list of tax and a custom tax. So can you please help me to apply more than 2 taxes.

Thanks.

**Comment by mlorencik** [comment]
You can go to System settings > Advanced modules > Taxes – Rates  and define new taxes

**Comment by indrabhusanroy** [comment]
Yes I can create as many Tax as I want from Advanced modules--Tax Rates. But here I am not asking for this. I am asking to apply more than than two Tax. see the pic below:

![image](https://user-images.githubusercontent.com/44740513/54603014-4881d300-4a69-11e9-94ed-3d9798b69f35.png)

Here I can apply only Two Tax only, one from list of the available Tax( These are the ones created from advanced modules) and the another from Custom Tax where I can provide any value.

So even if I create as many tax rates as I want, I can apply only one tax from the list of available taxes and I can also add a tax from the custom tax rate. So In all I can apply 2 Tax rates on products/services.

But I have 5 Tax to applied on products. So I think best of doing this is to allow multiple tax selection from the list of available rates so that I can apply more than one Tax Rate from the Tax List I have created and these Taxes should be applied on the products and should be shown in the Tax summary.

see the pic below:
![image](https://user-images.githubusercontent.com/44740513/54603428-479d7100-4a6a-11e9-8480-b12cdb45f746.png)

So In the Tax summary all the Tax applied should be shown with the Tax Rate in percentage and the Amount.

Also It will be better if the Tax Label is shown besides the Tax Rate in Tax Summary..



Thanks

**Comment by mlorencik** [comment]
You can select one of tax for product or one for all products (tax group), but you can't add 4 tax to one product. If you have 4 product with 4 diffrent tax then you can see 4 tax in summary. Tax you can set from general taxes, taxes from products/services or custom

**Comment by indrabhusanroy** [comment]
Thanks
