### ISSUE TITLE
  Tree field database identification Problem

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9931]
Hi, I have a created a category for a custom module from field-folders(TREE TEMPLATE MANAGER). Now I need to see the database of this category. When I look for the database of the custom module I have created, I cannot find the category field in there, but there is a separate database for this category filled but even there the category I have created is not showing properly, it's only showing values like T11, T14 e.t.c. So how can I identify which one is T11 and which is T14. Is there a way to identify this.

Please help me in this...

Thanks.

**Comment by vovpff** [comment]
This is normal condition fot trees. This is not a bug. You can change and see everything trough GUI and doesn't matter how it stored in database.
