### ISSUE TITLE
[Question]           Relation 1:M. Only select in record edit view.

### ISSUE THREAD

**Issue by alexandr256** [YetiForceCompany/YetiForceCRM#9935]
### Description
![изображение](https://user-images.githubusercontent.com/15902980/54421202-21a86180-4736-11e9-9e31-06b929ff6203.png)
What needs to be changed so that in the editing of the record the link can only be selected by search, but you cannot start the quick creation, as in the picture above (Quote).

Quote - only SELECT
Opportunity - SELECT,ADD

**Comment by mlorencik** [comment]
basically you answered it yourself, if we only have SELECT, then we can only choose the record, if we also have ADD, we can also add it

**Comment by alexandr256** [comment]
Where to do it in the database? Set the value of the SELECT in the table vtiger_relations did not help.

**Comment by mlorencik** [comment]
My mistake. The ability to add is for modules that are not advanced modules. The possibility of adding the possibility of adding is not possible for such modules, in turn if you want to disable this possibility, one of the options is to restrict the user to adding records to the associated module.

**Comment by alexandr256** [comment]
Thank! I just made this module extended without additional fields. )
