### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by slawhodu** [YetiForceCompany/YetiForceCRM#994]
Witam,
jak uaktualnić z wersji beta? Mam wersję beta 0.11 i nie ma paczek przejściowych pomiędzy beta i RC.

**Comment by bpabiszczak** [comment]
o ile dobrze pamiętam, to pisaliśmy, że wersje te nie będą miały paczek aktualizacyjnych. Jedyną metodą jest porównanie wersji 0.11 z wersją stabilną i ręczne wprowadzenia zmian. Nam by to zajęło pewnie cały dzień, ktoś kto tym się nie zajmuje na co dzień, pewnie kilka dni i do tego obstawiam na 99% że wykona to źle. 

To jest bardzo trudny proces. Więcej czas zajmuje nie wgrywanie zmian, tylko testowanie czy wszystko jest ok a następnie poprawki, jeżeli coś jest nie tak.
