### ISSUE TITLE
Problem with Roundcube configuration

### ISSUE THREAD

**Issue by jakubmusiol** [YetiForceCompany/YetiForceCRM#9940]
Hi,

i can't save Roundcube configuration when i'm changing something in "IMAP server name". How can I fix that?

**Comment by mrzewnicki** [comment]
Give more information, any error view? After you save, you should go to "Virtualdesk" and sign in to mail. After that in Mail scanner you will see a option to configure for this mail and you will be able to set something. 

Give more info about problem.
