### ISSUE TITLE
[Question] How to correct the Status picklists for Project Module?

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#9944]
### Description

Upon upgrading from 5.0.0 to 5.1.0 the following message was shown:

`After the system update, please verify if the "Status" picklists are correct in the following modules: Projects, Project milestones and Project tasks`

Accordingly, I checked the picklists status values for all three modules. I have the following labels that are not being translated at the moment:

**[Projects Milestones]**
`PLL_PLANNED`, `PLL_IN_PROGRESSING`, `PLL_ON_HOLD`, `PLL_IN_APPROVAL`

**[Project Tasks]**
`PLL_PLANNED`, `PLL_IN_PROGRESSING`, `PLL_COMPLETED`, `PLL_ON_HOLD`, `PLL_CANCELLED`, `PLL_SUBMITTED`, `PLL_IN_APPROVAL`

**[Projects]**
`PLL_PLANNED`, `PLL_IN_PROGRESSING`, `PLL_COMPLETED`, `PLL_ON_HOLD`, `PLL_CANCELLED`, `PLL_IN_APPROVAL`

Furthermore, the following three values available in the dropdown field **Automation** if you edit one of those values are not translated also:
`LBL_AUTOMATION_NO_CONCERN`, `LBL_AUTOMATION_OPEN`, `LBL_AUTOMATION_CLOSED`

All the above values are not editable in the **Edit** function of the picklist. I was thinking to go ahead and add them myself in the Language Management module, if they are not present already. So I compared with the Developer version on git to reflect the same, but I was not able to find those labels there.

**Can't this be corrected in Crowdin by default, so that a language update can solve this? Or should I do myself some corrections in Language Management in the CRM?**

**Comment by acsinsurancegroup** [comment]
@alagmouch I manually had to add in the Projects, Project Tasks & Project Milestones language files each translation after the update and it fixed all of my statuses.

As for the issue in Automation, mine didn't have an issue.

**Comment by alagmouch** [comment]
Thanks a lot for the direction @acsinsurancegroup. I think I will do the same then.

**Comment by acsinsurancegroup** [comment]
@alagmouch No worries, glad I could help. Enjoy!
