### ISSUE TITLE
[bug] Blank screen on edit/view details event in pop-up in Extended Calendar Quick Create.

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#9946]
# 🐞 bug report

### ⁉️ Describe the bug

The CRM gives a blank screen and/or yellow screen upon clicking on the edit or details buttons in the pop-up after hovering over an event in the Extended Calendar view while in Quick Create mode.

### 🔥 How to trigger the error

1. Go to a Contact, and Quick create an activity from the Calendar widget in the Summary page.
2. In the Extended Calendar view, hover over an already existing event, so that the pop-up shows with the details of the event.
3. Click in the pop-up either on edit or on details.
4. The Screen will go white blank (if you click on edit) or yellow blank (if you click on details).

### 👎 Actual Behavior

Blank screen.

### 👍 Expected Behavior

Show the details or edit the details of the existing event.

### 🌍  Your Environment 

Not applicable. This has been tested and reproduced in the developer version on git.

### ❓ Additional context
Maybe it is not needed to show both those buttons (edit and details) while hovering over the existing event in the Quick create view. Because if someone opens a Quick Create then he/she wishes to create an event. And see of course which dates and timings are still available.

And if still required to edit or view details from the pop-up, then opening in a new window maybe. (Just a suggestion.)

**Comment by mlorencik** [comment]
What version do you have? Any errors on console? On gitdeveloper after click edit or detail the right side is reload and presenting data

**Comment by alagmouch** [comment]
![Screenshot of the pop-up.](https://user-images.githubusercontent.com/47819025/54932913-1c68c500-4f35-11e9-8b1b-45b89a459cca.png)

The screenshot shows the pop-up I mean. It is not the right side of the Quick Create form. It is the details pop-up that shows when you hover over an existing activity in the calendar on the left side. Both buttons provide a blank/yellow screen.

**Comment by mlorencik** [comment]
I test this now, after pop-up i click on the buttons edit/detail and on the right side is detail or edit form, all it works

**Comment by alagmouch** [comment]
Ok. I understand. That is strange indeed. Can it be related to my browser?

I will try to record it and upload so that it can be more clear.

**Comment by mlorencik** [comment]
what browser do you use?

**Comment by alagmouch** [comment]
Chrome and Firefox. Both give the same issue. I made a recording of it and attached as gif here below.

![pop-up-errors](https://user-images.githubusercontent.com/47819025/55038407-2c1e0180-503a-11e9-8697-c922e1c6e36a.gif)
