### ISSUE TITLE
Import date field 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9947]
### Description
I am trying to import Lead records from a csv file. I have mapped all the necessary fields. Now the lead records gets imported with all its fields.All fields shows concern field data except  date field.How to merge date data

**Comment by fbojan** [comment]
Import date field can only be in the form yyyy-mm-dd. I solved this by temporarily setting my system settings to this format and importing the data easily. Later, I changed the system's user format to dd.mm.yyyy again
