### ISSUE TITLE
[Question Poss Issue] Calendar Permission

### ISSUE THREAD

**Issue by acsinsurancegroup** [YetiForceCompany/YetiForceCRM#9948]
### Description
Hello! I have a question regarding the Calendar permissions. I created a test entry and when I click and try to drag that entry to a different day I get the following error message:

"You do not have permission to modify Calendar entries"

How is that possible when it's an event I created? 

I'm using the latest 5.1 version of the CRM on a Plesk server running CentOS 7. the latest and PHP 7.1 something.

Here is a screenshot of the error:

![Screenshot (12)](https://user-images.githubusercontent.com/42642523/54480663-03576a00-47f9-11e9-88e9-8ee2d388450f.png)

However, if I click on edit, I can change the date without issues. I should be able to just drag it wherever I need it though but it's not working that way as you can see in the error.

Thanks in advance :)

**Comment by mlorencik** [comment]
Can you check response from server after drag entry? maybe there is error and that it's problem, in normal case response have result = true/1
