### ISSUE TITLE
[bug] Several minor issues related to the Context-sensitive help field.

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#9950]
# 🐞 bug report

### ⁉️ Describe the bug

Using the **Context-sensitive help** field in the **Edit Fields** section of the Modules backend, has some minor issues.

1. The body text as filled in the backend (Settings area), shows as HTML in the frontend.
**How it is filled up in the backend body of the Context-sensitive help field:**
`ATC = Attempt To Contact`
`CFU = Client Follow Up`
`CR = Call Request`
**How it is shown in the frontend, while hovering the Context-sensitive help icon:**
`<ul><li>ATC = Attempt To Contact</li><li>CFU = Client Follow Up</li><li>CR = Call Request</li</ul>`
2. While editing the Context-sensitive help field, changing to the Arabic language causes the screen to hang. (Might be something to do with the Language Management.)
3. The Context-sensitive help icon shows as a small square in the front end, next to the field.
4. Saving the Context-sensitive help field causes the changes to be saved, but the pop-up form remains on the screen until you click on **Close**.

### 🔥 How to trigger the error

1. Edit the Context-sensitive help field in the Calendar Module for  the field **Subject**.
2. Create 4 list-items in the body, each below one another.
3. Select all views in the **Show in views** field.
4. Save the form. Changes are saved, but the form is closed only if you click on Close.
5. Create an activity from the Calendar widget in the Summary of a Contact.
6. See the icon besides the **Subject** field. It shows as a small square.
7. Hover over the icon. The text shows as with HTML codes.
8. If you go back to Edit that same Context-sensitive help field in the Calendar Module and change the language in the pop-up form to Arabic, the screen hangs.

### 👎 Actual Behavior

* Value shows including HTML codes.
* Pop-up form does only close if you click on Close, after having clicked on Save already.
* The Context-sensitive help icon shows as a square besides the field in the front end.
* Changing the language to Arabic in the Context-sensitive help icon makes the screen hang.

### 👍 Expected Behavior

* Value shows without HTML codes.
* Pop-up closes also if one presses **Save**.
* Context-sensitive help icon should show the actual icon.
* Changing the language to Arabic in the Context-sensitive help icon should not cause the screen to hang.

### 🌍  Your Environment 

Not applicable. Has been reproduced in the developer version on github.

**Comment by mariuszkrzaczkowski** [comment]
Bugs add one by one

**Comment by alagmouch** [comment]
Ok.

**Comment by alagmouch** [comment]
@mariuszkrzaczkowski is done, separate issues created.
