### ISSUE TITLE
[bug] Body text in the Context-sensitive help field shows HTML markup.

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#9954]
# 🐞 bug report

### ⁉️ Describe the bug

The body text as filled in the backend (Settings area), shows HTML markup in the frontend.

**How it is filled up in the backend body of the Context-sensitive help field:**
`ATC = Attempt To Contact`
`CFU = Client Follow Up`
`CR = Call Request`

**How it is shown in the frontend, while hovering the Context-sensitive help icon:**
`<ul><li>ATC = Attempt To Contact</li><li>CFU = Client Follow Up</li><li>CR = Call Request</li</ul>`

### 🔥 How to trigger the error

1. Edit the Context-sensitive help field in the Calendar Module for  the field **Subject**.
2. Create 4 list-items in the body, each below one another.
3. Select all views in the **Show in views** field.
4. Save and Close the form.
5. Create an activity from the Calendar widget in the Summary of a Contact.
6. Hover over the icon. The text shows with HTML markup.

### 👎 Actual Behavior

Value shows HTML markup.

### 👍 Expected Behavior

Value shows without HTML markup.

### 🌍  Your Environment 

Not applicable. Has been reproduced in the developer version on github.

**Comment by konadrian** [comment]
On the gif result how it works on gitdeveloper version. Showing list using wysiwyg wokrs fine.
![HelpIcon](https://user-images.githubusercontent.com/3193498/58475729-0d79db00-814f-11e9-866d-9ba930a8a663.gif)
