### ISSUE TITLE
[bug] Context-sensitive help field edit form does not close after Save.

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#9955]
# 🐞 bug report

### ⁉️ Describe the bug

Saving the Context-sensitive help field causes the changes to be saved, but the pop-up form remains on the screen until you click on **Close**.

### 🔥 How to trigger the error

1. Edit the Context-sensitive help field in the Calendar Module for  the field **Subject**.
2. Fill in some text.
3. Select some views in the **Show in views** field.
4. Save the form. Changes are saved, but the form is closed only if you click on Close.

### 👎 Actual Behavior

Pop-up form does only close if you click on Close, after having clicked on Save already.

### 👍 Expected Behavior

Pop-up closes also if one presses **Save**.

### 🌍  Your Environment 

Not applicable. Has been reproduced in the developer version on github.

**Comment by rskrzypczak** [comment]
It's not an error, it's intentional. 
Thanks to that it's possible to immediately preview and verify the set value.
It's also possible to add contextual help for many languages at once, without having to reopen the modal window.

**Comment by alagmouch** [comment]
Ah ok. Now I understand. It's logic indeed.
