### ISSUE TITLE
[Question] Roundcube email stored

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#9959]
Hello,

I would like to ask about way of automations cleaning mail box. I must clean Roundcube manually by selecting all and move to Thrash or can i automatize it somehow? I ask because i never work with Roundcube and i'm afraid about storage space. Copy of mails i keep in tickets so i do not see any sens to keep mails too.  Thank you for the advise.

YetiForce 5.0.0 Complete
Ubuntu 16.04

**Comment by bpabiszczak** [comment]
Jeżeli to nie problem to najlepiej w PL, będzie szybciej. Z poziomu roundcube mamy opcje zaznacz wszystko i możemy usunąć co tylko chcemy. Działa to po IMAP a więc usunięte w dowolnym miejscu ma skutek bezpośrednio na serwerze. 

Najprościej ustawić bezpośrednio na serwerze poczty, aby usuwał maile po jakimś okresie np. 60 dniach.

**Comment by mrzewnicki** [comment]
PL oczywiście nie jest problemem ale z myślą o anglojęzycznych członków, myślę że już społeczności YetiForce 😄  Dzięki za rade. 👏 za 5.1

**Comment by bpabiszczak** [comment]
Wersja 5.x jest już używana przez ponad 1000 firm z 75 krajów tak więc przypuszczam, że i tak większość używa translatora ;)
