### ISSUE TITLE
[Question] Making a workflows

### ISSUE THREAD

**Issue by quasi754** [YetiForceCompany/YetiForceCRM#9963]
In what script language is wrote this fragment?

if mailingcountry == 'India' then concat(firstname,' ',lastname) else concat(lastname,' ',firstname) end

**Comment by waran70** [comment]
For me looks like English mixed with some undefined

**Comment by quasi754** [comment]
That's why i think it's MySql but i'm not sure because concat function is avaiable in few language but syntax end of line "end" is using in MySql. I tried script in Yeti but didn't work so i'm asking.

**Comment by bpabiszczak** [comment]
this is vtiger language ;P
