### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown 

### ISSUE THREAD

**Issue by guide5232** [YetiForceCompany/YetiForceCRM#9965]
# 🐞 bug 
I have crated M:M relation ship between the two module and if  i used that relationship field in filter condition   that time i am getting this error  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'u_yf_testleadcf.cf_2796' in 'on clause' Failed to prepare SQL: SELECT `u_yf_testlead`.`testleadid` AS `id`, `u_yf_testlead`.`testleadname` AS `testleadname`, `u_yf_testlead`.`number` AS `number`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `u_yf_testproductsnamecf_2796`.`testproductsnameid` AS `cf_2796Testproductsnameid`, `u_yf_testproductsnamecf_2796`.`testproduct` AS `cf_2796Testproductsnametestproduct` FROM `u_yf_testlead` INNER JOIN `vtiger_crmentity` ON u_yf_testlead.testleadid = vtiger_crmentity.crmid LEFT JOIN `u_yf_testproductsname` `u_yf_testproductsnamecf_2796` ON u_yf_testleadcf.cf_2796 = u_yf_testproductsnamecf_2796.testproductsnameid WHERE `vtiger_crmentity`.`deleted`=:qp0 LIMIT 21  error

![Yetiforce error](https://user-images.githubusercontent.com/47585969/54592102-c4871580-4a7f-11e9-819b-e2e4127dbdda.JPG)

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			| 5.1
| Web server (name and version)|Apache		|
| PHP  |			7.1					|
| Browser (name and version)  | google chrome	|

| Operating System (name and version)  | 	windows 7	|
| Database (name and version) | 	MySQL 	|

**Comment by guide5232** [comment]
This type of problem we are getting for all module 
![Yetiforce video recoded](https://user-images.githubusercontent.com/47585969/54656845-5a23b300-4b1b-11e9-8917-ad7254ec9638.gif)

**Comment by guide5232** [comment]
Hi team please check above video

**Comment by mariuszkrzaczkowski** [comment]
attach logs

**Comment by guide5232** [comment]
[_Importer.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3002417/_Importer.log)
[_system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3002418/_system.log)

[system.log](https://github.com/YetiForceCompany/YetiForceCRM/files/3002421/system.log)

**Comment by guide5232** [comment]
Hi team please check above logs
