### ISSUE TITLE
[Question] How can I display all quotes (or sales order) for a product?          

### ISSUE THREAD

**Issue by SkavenKF** [YetiForceCompany/YetiForceCRM#9967]
### Description
I can't find a way to display all quotes or sales orders for a product.

Our Requirement: As a product owner I would like to see all quotes or sales orders of the last 30 days in which my product was used.

**Comment by waran70** [comment]
Reports module missing so much.... statistic is a core of any business. Maybe we gather and throw 20 bucks each for yeti guys to speed it up?

**Comment by SkavenKF** [comment]
Good idea, actually we wanted to support this some time ago, but then came the statement that the report module for version 5 will be released at the latest 5.1 (history #9787). 

Unfortunately, all the companies I had introduced YF to were totally enthusiastic, but after the non-existent release planning, the unannounced discontinuation of functions, the inadequate official documentation, they all jumped off quickly again.

Since we need automated KPIs for our management, we are currently looking for a professional solution that can also be used for reasonable, long-term planning.

But depending on the costs, I might support this privately (via crowdfunding!?) 😃

**Comment by vovpff** [comment]
You can write selfmade relation betveen product and see list of advanced modules what contain product.

**Comment by SkavenKF** [comment]
That's true, but this should be a standard function and not a custom development. At least one possibility for evaluation should be provided by the standard.

**Comment by vovpff** [comment]
I'm nit sure. This feature was requested only once by me in 3 year time.

**Comment by SkavenKF** [comment]
I think this is a question in which industry you would like to use the software. Even for smaller companies this is usually not such a problem. It is e.g. about a solution which can link and evaluate the tables with each other, if this is not provided in the standard delivery, here unfortunately the suitable reporting is missing at present.
I would like to give here only a few thought-provoking impulses, which I discussed with other partners already. In my opinion, there are a lot of possibilities that could make YF an excellent CRM.
 
Also please don't misunderstand, I support YF from the beginning, because I see a big potential and a committed group of people with big goals. I had hoped over the last years to motivate a few more people in my environment, which unfortunately didn't work due to the already mentioned factors. There are also different opinions about "standard software", but there are other more suitable software.

But the most important thing is that the team behind yf exists on the market with fun, a clear concept and a business model. (and the community is more involved/informed in the planning 😄 )

**Comment by liviubbo** [comment]
I can join the crowdfunding for the reports module. I dont have much to trow, but i have some.

**Comment by paula-w** [comment]
In order to display all quotes, orders, and invoices related to the product, the easiest way is to add related modules in products and services modules. You can also add a new field type that will display products and services directly on the list of quotes, orders, and invoices (the same way we did it in the Accounts module).
If the community needs a reports module then we suggest donating towards it through the “Reports contribution” tier in our Open Collective (https://opencollective.com/yetiforcecrm), it’s a special tier we made just for this purpose.
