### ISSUE TITLE
 Adding multiple calculations , don't know where to find the section 

### ISSUE THREAD

**Issue by indrabhusanroy** [YetiForceCompany/YetiForceCRM#9974]
Hi,
I'm struggling with the calculations in your invoice module where the product price and quantity is being auto multiplied. Now my situation is that I want to add some more multiplication fields and also add some division fields into it. I would really appreciate if you can tell me how and where exactly in your backend code will I be able to find this section where I can insert my code to do the needful. I thank you in advance for your help.... kindly understand that my main problem is not being able to find the backend section where I can inject my code... so kindly let me know that so that I can get started. Cheers

**Comment by indrabhusanroy** [comment]
Where can I find advanced block code so that I can add a new field...

**Comment by indrabhusanroy** [comment]
Just like margin%, quantity, unit price e.tc.

**Comment by mlorencik** [comment]
You can start in modules/vtiger/inventoryfields folder, there is code for fields, some is in inventory.js in public_html/layouts/basic/modules/vtiger

**Comment by indrabhusanroy** [comment]
Okay Thanks...
