### ISSUE TITLE
[PL][Pytanie] SMTP Problem

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#9979]
Witam, 
Wersja 5.0.0 Complete

Mam problem z połączeniem z moim serverem SMTP. Od początu działał poprawnie i wysyłał maile, po zmianie konfiguracji przdzychodzi wiadomość testowa na mojego maila potwierdzająca że działa(od tygodnia nic nie zmieniałem na SMTP bo działał od pierwszej konfiguracji):
![image](https://user-images.githubusercontent.com/21024857/54677295-e07fcb00-4b02-11e9-86b5-95629cbbecfa.png)

Lecz podczas próby wysłania maila z poziomu Roundcube, pojawia się następujący komunikat:
![image](https://user-images.githubusercontent.com/21024857/54677356-fa211280-4b02-11e9-8d8b-84ba5c40cc42.png)

Log:
[20-Mar-2019 10:43:27 +0100]: <tnqmg9tn> SMTP Error: Connection failed: Failed to connect socket: stream_socket_client(): unable to connect to ssl://mail.my-host.pl:587 (Unknown error) in /var/www/my_path/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube.php on line 1667 (POST /my_path/public_html/modules/OSSMail/roundcube/?_task=mail&_unlock=loading1553075025160&_lang=pl&_framed=1&_action=send)

Aktualizowałem już biblioteki Roundcube. Sprawdzałem Firewalla i jego reguły, Server pocztowy i aliasy.  Ogólnie poczta działa tylko nie na CRM. Zapewne to wina RoundCube.
Prosze o pomysły co może być nie tak..

**Comment by mrzewnicki** [comment]
[PL] Problem rozwiązany: z nazwy servera usunąłem przedrostek protokołu ssl://  pomimo że wcześniej bez tego nie chciał łykać. Ważne że działa

[ENG] Delete prefix of server address ssl:// and should work

**Comment by bpabiszczak** [comment]
o ile pamiętam, to powoli wszyscy rezygnują z SSL-a na rzecz TLS-a ale mylić się mogę. Nie tak dawno głośno o tym było w gmailu
