### ISSUE TITLE
Backup does not work

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [YetiForceCompany/YetiForceCRM#998]
![img](https://cloud.githubusercontent.com/assets/1402355/7883107/66b1bacc-062d-11e5-8f28-5f135bb34dda.JPG)

**Comment by waw555** [comment]
This problem is due - in the name of the database

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
do you mean that this problem still exists? Please expalin a bit your comment.

**Comment by waw555** [comment]
The problem was I, because of the fact that the database name contained a hyphen, and is not recommended. You can add to the documentation, that the name of the database must not contain a hyphen

https://github.com/YetiForceCompany/YetiForceCRM/issues/950

**Comment by bpabiszczak** [comment]
Module "backup" has been redesigned and improved.
