### ISSUE TITLE
Roundcube Update causes Error 500

### ISSUE THREAD

**Issue by Hammerman3000** [YetiForceCompany/YetiForceCRM#9984]
I'm on 5.1 and the update of the roundcube library causes an Error 500

![image](https://user-images.githubusercontent.com/45795852/54694032-e8059b00-4b27-11e9-903f-6af0a329a085.png)

**PHP Log** 
```
POST /index.php?module=ModuleManager&parent=Settings&action=Library&mode=update&name=roundcube HTTP/1.0
--
```

**Server Config**
![image](https://user-images.githubusercontent.com/45795852/54694003-dde39c80-4b27-11e9-9314-16799385b362.png)

**Comment by mariuszkrzaczkowski** [comment]
Logs

**Comment by Hammerman3000** [comment]
I just reproduced the issue once more. Here are the corresponding server logs

Date | Type | IP | Code | Message | Source
-- | -- | -- | -- | -- | --
21.03.2019 08:40 | Access | [Server IP] | 200 | GET /   HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Server IP] | 200 | GET /   HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Server IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Server IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:39 | Error | [Hammermann's IP] | 500 | POST /index.php?module=ModuleManager&parent=Settings&action=Library&mode=update&name=roundcube   HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:39 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:39 | Error | [Hammermann's IP] | 500 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | GET /error_docs/styles.css HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   read data timeout in 45 seconds | Apache error
21.03.2019   08:40 | Error | [Hammermann's IP] | -- | End of   script output before headers: index.php | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 304 | GET /error_docs/server.svg HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   read data timeout in 45 seconds | Apache error
21.03.2019   08:40 | Error | [Hammermann's IP] | -- | End of   script output before headers: index.php | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:40 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:41 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:41 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:41 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:41 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:41 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:41 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:41 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:41 | Access | [Hammermann's IP] | 200 | POST /index.php HTTP/1.0 | Apache SSL/TLS access
21.03.2019   08:41 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error
21.03.2019   08:41 | Warning | [Hammermann's IP] | -- | mod_fcgid:   stderr: PHP Warning: Zend OPcache can't be temporary enabled (it may be only   disabled till the end of request) in Unknown on line 0 | Apache error

**Comment by Hammerman3000** [comment]
Is this going the same direction as https://github.com/YetiForceCompany/YetiForceCRM/issues/8918 now?
just silencing it until it becomes forgotten?

**Comment by mariuszkrzaczkowski** [comment]
I meant full logs, that is
* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log 

```
### 📝 PHP/Apache/Nginx/Browser/CRM Logs
<!--  Please send a part of logs that describes the circumstances when the error occurred to the following email address: github@yetiforce.com. The subject of the email MUST include your issue number.
DO NOT paste the logs in the issues, as they might contain sensitive info, such as credentials. 
The more info you provide, the quicker we will be able to solve your problem. 
Description how to enable logs can be found here: https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging 
Additionally, include a screenshot of your browser’s console (e.g. press F12 in Google Chrome).
ex. 

* cache/logs/phpError.log
* cache/logs/system.log
* cache/logs/errors.log 

-->
```

**Comment by mariuszkrzaczkowski** [comment]
Do you have a ServicePack installed ([5.1.0_ServicePack_v5.zip](https://github.com/YetiForceCompany/YetiForceCRM/releases/download/5.1.0/5.1.0_ServicePack_v5.zip))?
