### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#9987]
Add a '**Deposit module**' in the Advance Module section.
I need deposits to be subtracted from the total cost of a product on an invoice or sales order. I tried to create a product called deposit & use a (-) to subtract it from the total cost but when I try to save the invoice it does not allow negative numbers. This would be a great added feature for companies who require a deposit for initial payment. Thanks in advanced.

**Comment by paula-w** [comment]
We use independent documents to record such payments, adding that is not something difficult, it would probably take 2~3 work days for a programmer to code it in a few places. 
The community can donate towards it through Open Collective: https://opencollective.com/yetiforcecrm. 
All donations (apart from the 3 dedicated tiers) will be spent towards a full time programmer who will support the GitHub community, solve the reported issues and answer questions.
