### ISSUE TITLE
Product Variable

### ISSUE THREAD

**Issue by hobejeans** [YetiForceCompany/YetiForceCRM#9988]
Each product cost can be determined by an added feature. This would help a lot with quotes.

for example:             Variable 1               Variable 2                  Variable 3               Total
Product                    Style                          Color                        Gender                  Price
T-shirt                     sleeveless             red,green, blue           men/women           ($15.00)
T-shirt                     Short sleeve          red,green, blue          men/women            ($17.00)
T-shirt                     Long Sleeve         red,green, blue           men/women            ($22.00)

Maybe this feature is already implemented in the system but I don't know how to use it. Please explain

**Comment by mlorencik** [comment]
We don't have anythink like you need in the system, each variable must be added separately as a product
