### ISSUE TITLE
Question:How to Add More Columns In list Preview

### ISSUE THREAD

**Issue by eptapsyxos** [YetiForceCompany/YetiForceCRM#999]
Noob question i know...but i ve get stucked.

How to add More columns in liste preview(on a custom module)like contacts etc..
![list preview](https://cloud.githubusercontent.com/assets/6897502/7941028/335e61f6-095d-11e5-97c6-7aa707af9080.jpg)

**Comment by bpabiszczak** [comment]
Please check this tool: https://test.yetiforce.com/index.php?module=CustomView&parent=Settings&view=Index&block=2&fieldid=57
