### ISSUE TITLE
[Question] Custom functions and workflows

### ISSUE THREAD

**Issue by quasi754** [YetiForceCompany/YetiForceCRM#9996]
How cna i create a Custom functions or Custom workflow? Because i don't see any option to upload or i did not seen directory where are keeped. I unders i must write it on my own.

**Comment by liviubbo** [comment]
Hy there ! 

You cand go to : 

   System settings -> Automation -> Workflows -> Create a new workflow

**Comment by liviubbo** [comment]
If you need a custom module : 

   System settings -> Standard Modules -> Modules installation -> Create Module

**Comment by quasi754** [comment]
Sorry, my bad. I mean custom funcitons because there is always empty. I need it because Task Send Mail always convert my topic to html and that's disturbed me.

![image](https://user-images.githubusercontent.com/48558884/54808176-b9023d00-4c7f-11e9-9a35-20ce215b8112.png)

**Comment by quasi754** [comment]
Solution: After programing you must add WorkFlow to DB.
