### ISSUE TITLE
[bug] Updates Tab hangs in the Calendar Activity item Detail view.

### ISSUE THREAD

**Issue by alagmouch** [YetiForceCompany/YetiForceCRM#9997]
# 🐞 bug report

### ⁉️ Describe the bug

After upgrading from 4.4.0 to 5.0.0 using **4.4.0_to_5.0.0_v4.zip**, all existing activities that do not have the **To Do** as **Activity Type** cause hanging of the **Updates** Tab in the Details view of the selected activity.

All existing **To Do** activity types do not have this issue. All newly entered activities do also not have this issue.

Upgrading from 5.0.0. to 5.1.0 with **5.0.0_to_5.1.0_v1.zip** does not fix the issue. Using the **5.1.0_ServicePack_v1.zip** after the upgrade does not fix the issue also.

### 🔥 How to trigger the error

1. Install a fresh version 4.4.0 with an empty database, and apply all the 4.4.0 fixes (4.4.0_AttachmentsFix_v1.zip, 4.4.0_CalendarDateFormatFix.zip, 4.4.0_ImageFix_v3.zip, 4.4.0_SecurityPHPMailerAndPhpSpreadsheetFix.zip, 4.4.0_SecuritySmartyFix_v1.zip, 4.4.0_WidgetFix_v1.zip).
2. Allow the group **Team Selling** to be used in the **Share with users:** field.
3. Enter a test Lead with one Contact, share both records with a group in the **Share with users:** field.
4. Create 4 activities: a) a **To Do** which is not shared with Team Selling, b) a **To Do** which is shared with Team Selling, c) a **Call** which is not shared with Team Selling, and d) a **Call** which is shared with Team Selling.
4. While in version 4.4.0, open each of those Activities in Detail view and click on the **Updates** Tab. It will load properly.
5. Upgrade from 4.4.0 to 5.0.0 using **4.4.0_to_5.0.0_v4.zip**, and open those same activities in the Detail view and click on the **Updates** Tab. It will hang, except for the **To Do** Activity type.
6. While in 5.0.0, create also some new activities and view them in the Detail view and click on the **Updates** Tab. It will work properly for the newly created activities, for all Activity Types.
6. Upgrade from 5.0.0 to 5.1.0 using **5.0.0_to_5.1.0_v1.zip**. After the upgrade you will not be able to open the Lead or the Contact, due to the **Share with users:** field issue. The next step solves that to proceed forward.
7. Use the ServicePack **5.1.0_ServicePack_v1.zip** to patch the 5.1.0 version. Now you are able to open the Lead and the Contact. Open those previously created activities in Detail view, and click on the **Updates** Tab. It will hang for all the Activity Types, except the **To Do** Activity type. And any newly created activities will not have this issue.

### 👎 Actual Behavior

The **Updates** tab in the Detail view of an activity hangs while loading, after clicking on the tab.

### 👍 Expected Behavior

The **Updates** tab should load normally. 

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce |  v4.40 to v5.1.0
| Web server (name and version) | Nginx v1.15.8
| PHP  | PHP 7.2.14 with Zend OPcache v7.2.14 |
| Browser (name and version)  | Mozilla Firefox 65.0.1 |
| Operating System (name and version)  | Centos 7 |
| Database (name and version) | Mysql 10.1.37-MariaDB |

### ❓ Additional context
Reference to a previous issue related to the **Share with users:** field in version 5.1.0. ([Issue 9908](https://github.com/YetiForceCompany/YetiForceCRM/issues/9908)). Is already closed, but I encountered there the same, while using a copy of the production database. This time I took a fresh install and empty database to try to replicate the same.

**Comment by alagmouch** [comment]
Hi @bpabiszczak, @mariuszkrzaczkowski. You guys are probably already overloaded. Apologies for issuing this bug. Because anyone who is installing 5.0.0 and above will not face this issue. But for those who updated from 4.4.0, it will remain for all the old input of activities until a fix is introduced.

In case you are able to have a fix available for this part also, it will be tremendous. I did quite some testing in the past days, and I believe that the above remaining issue shall be the last obstacle for someone to move fully from 4.4.0 to 5.1.0 (including ServicePack).

There is only an issue remaining related to the day view in the Calendar, but it's not that crucial for now. At least if the **Updates** Tab issue is fixed, I will move to 5.1.0 and then test the Calendar day view issue next week to see if it can be reproduced.

Your kind response and efforts are much appreciated. (*I am eager to move to 5.1.0 because of the custom fields in the Calendar. It gives some more possibilities to standardise the input, in combination with workflow rules.*)

**Comment by alagmouch** [comment]
You may ignore the urgent tone of above request. I installed a fresh 5.1.0 and applied the ServicePack patch, and started over again. I figured that more fundamental changes are applied in 5.0.0 (comparing with 4.4.0), that it would be better to start from 5.1.0 while the data is still not that much. Although, I still believe that a fix for the **Updates** Tab hanging behavior shall help others that are still on 4.4.0 with more data and which want to move towards 5.1.0.

**Comment by paula-w** [comment]
This is @bpabiszczak 's response:
Sometimes you can encounter issues like the one you described if there are some problems with your update, that's why logs are so important.
